### ISSUE TITLE
Error after upgrade: invalid request header X-Amz-Content-Sha256

### ISSUE THREAD

**Issue by fabio42** [hashicorp/vault#10005]
After upgrading from `vault 1.2.4` to `vault 1.2.7`, all my AWS IAM auth clients are failing with error code **400** and the following message :

```
invalid request header: X-Amz-Content-Sha256
```

Applying the following setting fix the problem:

```
vault write auth/aws/config/client allowed_sts_header_values="X-Amz-Content-Sha256"
```

I'm wondering if this header should be added as part of `defaultAllowedSTSRequestHeaders` here: https://github.com/hashicorp/vault/blob/master/builtin/credential/aws/backend.go#L22-L28

Thank you.

**Comment by kalafut** [comment]
Thank you for the report and confirmation of the workaround. Yes, we'll add that one to the default list.

**Comment by Nagarajuwas** [comment]
We also face same problem and after adding it is working fine.

**Comment by jorge-gr-globant** [comment]
Is there a way to read these headers via vault read?
Thank you beforehand

**Comment by kalafut** [comment]
@jorge-gr-globant `vault read auth/aws/config/client` will show you the _additional_ headers you've added. The default list is: https://github.com/hashicorp/vault/blob/master/builtin/credential/aws/backend.go#L22-L29

**Comment by kalafut** [comment]
Fixed in https://github.com/hashicorp/vault/pull/10009
