### ISSUE TITLE
Cert renewal enhancements

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#1000]
We should check against CRLs when renewing in `cert`. It may also be a good idea to require that the certificate used for renewal is the same one that originally performed the authentication.

**Comment by vishalnayak** [comment]
@jefferai If we require that the certificate used for renewal to be the same that performed authentication, Vault admin might not renew the token on behalf of the client right?
Or is it just the client's responsibility to get the token renewed?

**Comment by jefferai** [comment]
It's usually the client's responsibility. Usually admins shouldn't have access to client tokens.

**Comment by jefferai** [comment]
Also this can/should be a toggleable option, although it should probably default to on.

**Comment by vishalnayak** [comment]
Okay, I agree that it should be client's responsibility.

I am thinking of getting the matching certEntry of the renewal request (just like during login request) and then check if it is same as the certEntry pointed by the auth metadata.

By toggleable option, do you mean something like **verify_renew** in CertEntry(?), to decide whether to do the verification during renewal or not?

**Comment by jefferai** [comment]
Oh, by toggleable, I meant, channel-binding at all. There will be orgs that will may find it far more trouble than it's worth if they are turning over certs very quickly.

**Comment by kaelumania** [comment]
@jefferai it should also be checked when renewing a token from `auth/cert/certs` if the policies have changed. And if the policies have changed, then the renewal request should be rejected! e.g.:

`user` with `cert` and policy `admin` request a token (`auth/cert/login`)
...
an operator updates the policy for the `cert` to `normal`
...
the user is still able to renew their token :( he can stay `admin` forever.

**Comment by jefferai** [comment]
@kaelumania I'm going to track that in #477 which is still open; once this is commited I'll close that ticket.
