### ISSUE TITLE
unable to resolve ARN to internal ID: unable to fetch client for account ID, default client is for account

### ISSUE THREAD

**Issue by volwei** [hashicorp/vault#10013]
**Describe the bug**
I use auth method iam for accessing vault secrets. The authentication works fine in the same aws account as my vault server runs. I created a role for that (vault write). If i want to create another role for accessing vault secrets from a different account, i mostly get the following errror:
`Code: 400. Errors: unable to resolve ARN "arn:aws:iam::<account_id_a>:role/<iam_role_name>" to internal ID: unable to fetch client for account ID "<account_id_a>" -- default client is for account "<account_id_b>"`
account_id_b is the aws account where my vault server runs. account_id_a is the other account. 
But it doesn't always fail. Every then and now the command is successful:
`Success! Data written to: auth/aws/role/<role_name>`

**To Reproduce**
1. Run `vault write auth/aws/role/<role_name> auth_type=iam policies=<policy_name> max_ttl=1h token_no_default_policy=true token_num_uses=1  bound_iam_principal_arn=arn:aws:iam::<account_id:role/<iam_role_name`
3. See error above

**Expected behavior**
The vault cmd is always successful.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.2
* Vault CLI Version (retrieve with `vault version`): 1.3.2
* Server Operating System/Architecture: Kubernetes (Kops)

Vault server configuration file(s):
Rollout with helm (https://github.com/hashicorp/vault-helm/archive/v0.5.0.tar.gz)

**Comment by volwei** [comment]
I also get an error when i try to login from the aws account where my vault server does not run:
`Code: 400. Errors:
* error looking up full ARN of entity &{aws <account_id_a> assumed-role  <iam_role> <instance_id>}: error creating IAM client: unable to fetch client for account ID "<account_id_a" -- default client is for account "<account_id_b"`

account_id_b is the aws account where my vault server runs. account_id_a is the other account.

**Comment by volwei** [comment]
The configuration in which is configured which aws role vault should use to validate the request in the other account (cross account) was not configured. After that the write command is always successfull.

**Comment by krudelydunn** [comment]
Hi, I am running into the same issue you described above. Mind explaining what resolved this issue? I am a little confused by what you said above.

**Comment by mdshoaib707** [comment]
Hi @krudelydunn 
As per the [vault doc](https://www.vaultproject.io/api-docs/auth/aws#sts_endpoint), they say if `sts_endpoint` is set then `sts_region` should also be set.
Previously it was failing for me when I had only set `sts_endpoint` but later when `sts_region` was set then the error was gone.

Commands for setting the sts region and endpoint
```
vault write auth/aws/config/client sts_endpoint=https://sts.eu-west-1.amazonaws.com
vault write auth/aws/config/client sts_region=eu-west-1

vault read auth/aws/config/client
```

**Comment by computerphilosopher** [comment]
Hi, I was suffered from same issue and solved now.

In my case, I retry the write operation after logging in with the access key, and the issue was solved.

**Comment by georgesmith2017** [comment]
I struggled with this issue until I discovered that my IAM user was accidentally deleted and therefore its access and secret keys were no longer valid, but still part of the AWS auth method's config. Once I created another user, generated new keys, and updated Vault's AWS auth config, the problem was resolved.

**Comment by Rahulrama211** [comment]
Hi,

I have running vault in my local machine using the command vault server-dev and I configured AWS secret engine 
vault auth enable was
vault write auth/aws/config/client access_key=<ACCESS KEY> secret_key=<SECRET KEY> region=us-east-1
vault write auth/aws/role/my-iam-role auth_type=iam bound_iam_principal_arn=<ARN VALUE> policies=demopolicy token_ttl=500h

-----
AWS:
I CREATED A IAM USER AND ATTACHED A POLICY 

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances",
                "iam:GetInstanceProfile",
                "iam:GetUser",
                "iam:GetRole"
            ],
            "Resource": "*"
        }
    ]
}

PS C:\WINDOWS\system32> vault write auth/aws/role/my-iam-role auth_type=iam bound_iam_principal_arn="arn:aws:iam::050752617604:user/hashiawsiam" policies=demopolicy max_ttl=500h
Error writing data to auth/aws/role/my-iam-role: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/aws/role/my-iam-role
Code: 400. Errors:

* unable to resolve ARN "arn:aws:iam::050752617604:user/hashiawsiam" to internal ID: unable to fetch current caller: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
        status code: 403, request id: 2a092bb3-e400-4374-8c93-82aa283b455c IM GETTING THIS ERROR CAN SOME ONE HELP
