### ISSUE TITLE
Error starting vault when setting default_lease_ttl and max_lease_ttl

### ISSUE THREAD

**Issue by rhoml** [hashicorp/vault#1004]
* default_lease_ttl (optional) - Configures the default lease duration for tokens and secrets, specified in hours. Default value is 30 days. This value cannot be larger than max_lease_ttl.

* max_lease_ttl (optional) - Configures the maximum possible lease duration for tokens and secrets, specified in hours. Default value is 30 days.

when setting this parameters to 700 and 720 respectively vault refuses to start.

**Comment by jefferai** [comment]
Fixed, thanks!

**Comment by rhoml** [comment]
Thanks, much appreciated

Pardon any typo. This mail has been sent from my iPhone

Disculpe si existen errores ortográficos. Este email ha sido enviado desde mi iPhone
