### ISSUE TITLE
OIDC alias case sensitive problem 

### ISSUE THREAD

**Issue by papovyr** [hashicorp/vault#10063]
Hi,
I have two vault envariments PROD and UAT
They are deployed in eks cluster, with helm chart.
Vault version: 1.4.2
Backend is DynamoDB,
All configuration is manages by terraform so I have exact copy for UAT and PROD

Before onboarding users to vault I will create Entities and alias with there email (I will create email in low case ex `name.lastname@domain.com`).
But email can be `Name.Lastname@domain.com`
And everything worked fine unit recently
 
Now in PROD when users try to login with OIDC it will create a new entitie and alias, alias will be case sensitive 
In this case i have pre created alias `name.lastname@domain.com` but it will create a new one `Name.Lastname@domain.com`

However this is happening only in PROD env UAT env works fine(In UAT it maps user to pre created email all low case ).

I didn't do any updates. only thing that i found there was a vault container restart 
My guess will be that DynamoDB has some temp values that needs to be cleaned?

I installed vault with helm and apply same config with terraform everything works fine (Im not able to reproduce)
But I need to fix PROD env
Any ideas on this ? 

Thank you,

**Comment by raskchanky** [comment]
Hi @papovyr! Thanks for reaching out. Are you aware of [our forum](https://discuss.hashicorp.com/c/vault/30) for Vault? I think you'll have more luck getting an answer to your question if you post it over there. We try and reserve GH issues for bug reports and enhancement requests. I'm going to close this issue, as I don't think there's anything for us to do here. Thanks again!
