### ISSUE TITLE
Identity groups not properly cleaned/merged with identity/entity/merge request

### ISSUE THREAD

**Issue by mdgreenfield** [hashicorp/vault#10084]
**Describe the bug**
Assume there are two entities, `toEntity` and `fromEntity`. `fromEntity` is a member of `groupA`. If `fromEntity` is merged into `toEntity` a success message is returned. However, there are several problems:

1. `groupA` does not have the `fromEntity` ID removed from `member_entity_ids`. Trying to update `groupA`'s name only results in an error.
1. `toEntity` does not have its `direct_group_ids` updated to include the `groupA` ID of `fromEntity`.

**To Reproduce**
1. Run `vault server -dev`
1. Create `fromEntity` - `fromEntity=$(vault write -field=id identity/entity name=child)`
1. Create `toEntity` - `toEntity=$(vault write -field=id identity/entity name=parent)`
1. Create `groupA` - `groupA=$(vault write -field=id identity/group name=groupA member_entity_ids=$fromEntity)`
1. Merge `fromEntity` into `toEntity` - `vault write identity/entity/merge to_entity_id=$toEntity from_entity_ids=$fromEntity`
1. Update `groupA` name to `updatedGroupA` - `vault write identity/group/id/$groupA name=updatedGroupA`. Observe this results in the following error:
    ```
    Error writing data to identity/group/id/08dabd46-bfa9-8bc1-ce15-1a154e9fa50a: Error making API request.

    URL: PUT http://127.0.0.1:8200/v1/identity/group/id/08dabd46-bfa9-8bc1-ce15-1a154e9fa50a
    Code: 500. Errors:

    * 1 error occurred:
            * invalid entity ID "ff767f9f-aa78-a4c0-98f8-f1bf1548ab66"
    ```
1. Fetch `groupA` member entity ID - `groupA_member_id=$(vault read -field=member_entity_ids -format=json identity/group/id/$groupA | jq -r '.[0]')`
1. Read the member entity ID and observe it does not exist - `vault read identity/entity/id/$groupA_member_id`
1. Read the group IDs linked to `toEntity` and observe that the group IDs are valid - `vault read -field=group_ids identity/entity/id/$toEntity`

**Expected behavior**
The `groupA` `member_entity_ids` should not contain an effectively deleted entity ID and merged entities should have their groups merged into the parent entity.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.5.4
* Vault CLI Version (retrieve with `vault version`): 1.5.4

**Additional context**
Whether or not groups _should_ get merged into the `toEntity` I'm less sure about because when `identity/entity/merge` is called policies are [not merged](https://github.com/hashicorp/vault/blob/ecf46c578967b9d0ebefa262e8e1417afe1b1bba/vault/identity_store_entities.go#L175). However, it does look like policies maybe [get merged](https://github.com/hashicorp/vault/blob/ecf46c578967b9d0ebefa262e8e1417afe1b1bba/vault/identity_store_util.go#L406) when an implicit entity is created on login.

- [Link to the `mergeEntity` func](https://github.com/mdgreenfield/vault/blob/master/vault/identity_store_entities.go#L608)
- [Related PR](https://github.com/hashicorp/vault/pull/5786)

**Comment by hghaf099** [comment]
Waiting for response in the PR
