### ISSUE TITLE
Secrets exploration

### ISSUE THREAD

**Issue by carroarmato0** [hashicorp/vault#1010]
I'm not sure whether or not this is a limitation of using  **file** as a backend, or a feature not being able to explore which secrets are available to you through the policy enforcement with the CLI.

At the moment it seems to me that you either need to know the paths by heart, write them down, or figure them out based on the folder structure on disk.

I haven't found anything of the sorts in the documentation.

**Comment by jefferai** [comment]
List support for the `generic` backend is coming in 0.5 which will allow listing the available keys/prefixes at a given path. I think that will solve your problem!

**Comment by carroarmato0** [comment]
awesome, thanks!
