### ISSUE TITLE
"pki/sign-verbatim/$role" ignores "not_before_duration" #8505

### ISSUE THREAD

**Issue by sooslaca** [hashicorp/vault#10104]
Hello,

Can we reopen that issue? #8505
The same problem we have, see Naugrimm last comment on that thread.

Thanks

**Comment by raskchanky** [comment]
After reading @jefferai 's reason for closing the issue, I don't think reopening it is the right move. Making the change requested in https://github.com/hashicorp/vault/issues/8505 sounds like it would defeat the purpose of the sign-verbatim endpoint. It sounds like if the sign endpoint supported custom x509v3 extensions, there wouldn't be a need to use sign-verbatim in this case. Feel free to open a feature request if that's the case. Thank you!
