### ISSUE TITLE
Expose ssh algorithm_signer in web interface

### ISSUE THREAD

**Issue by zeha** [hashicorp/vault#10114]
**Is your feature request related to a problem? Please describe.**
When configuring an SSH CA role, I cannot see the `algorithm_signer` setting in the web interface. Neither on the edit page or in the (readonly) settings view.

**Describe the solution you'd like**
`algorithm_signer` should be editable and viewable.

**Describe alternatives you've considered**
`vault read ssh-host-signer/roles/hostrole` shows it, but it's nicer to view it in the web to check the current setting.

**Explain any additional use-cases**
n/a

**Additional context**
n/a

**Comment by aphorise** [comment]
I guess this could an editable view the same as most other places and without any contextual validations? - to API calls are expecting. @zeha or are you are thinking of generic text editor of sorts?

hey @cipherboy I saw some commits on the fork you'd done and was wondering if you knew what the status was here?

**Comment by cipherboy** [comment]
@aphorise Probably just need to poke @ivana-mcconnell and @hellobontempo and re-confirm https://github.com/hashicorp/vault/pull/10299 is good to land. I don't recall why we didn't just land it, but I think we got distracted by SF.

**Comment by hellobontempo** [comment]
Resolved by #10299
