### ISSUE TITLE
Roles don't fetch correctly in UI with multiple Kubernetes clusters

### ISSUE THREAD

**Issue by FalconerTC** [hashicorp/vault#10127]
**Describe the bug**
When multiple Kubernetes auth methods are configured and you attempt to view/modify the role for them through the UI, the roles of the first loaded cluster is shown for all clusters

**To Reproduce**
1. Enable Kubernetes auth (cluster1) and create a role (role1)
2. Enable Kubernetes auth (cluster2) and create a role (role2)
3. Logout and log back in
4. Access roles in cluster 1 (/ui/vault/access/cluster1/item/role) and see role1
5. Access roles in cluster 2 (/ui/vault/access/cluster2/item/role) and you will see role1, not role2

**Expected behavior**
Different instances of Kubernetes auth should load the rules for the selected cluster

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.5.2
* Vault CLI Version (retrieve with `vault version`): 1.5.2
* Server Operating System/Architecture: MacOS

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by Monkeychip** [comment]
@FalconerTC This has been fixed and backported to the 1.5.x release branch, which means it will either be in the 1.5.5. release or 1.5.6. https://github.com/hashicorp/vault/pull/10122
