### ISSUE TITLE
clarification on Transit Secrets Engine 

### ISSUE THREAD

**Issue by anubnair** [hashicorp/vault#10129]
I am going through https://www.vaultproject.io/api-docs/secret/transit#signature_algorithm
Found that it supports ED25519 and ECDSA curves. Is it pkcs11? Can create keypair and sign using the P-256 elliptic curve with vault?

I tried the same I couldn't successfully broadcast that transaction. I am aware that ethereum vault pluggin is available. But if the native signing works, I can use vault transit for different blockchain/signing.

**Comment by raskchanky** [comment]
Hi @anubnair! Thanks for reaching out. Are you aware of the [Vault forums](https://discuss.hashicorp.com/c/vault/30)? We encourage people to post these types of questions there, as GitHub issues are usually reserved for bug reports and feature requests. I'm going to close this issue now, as I don't think there's much for us to do here. Thanks again!
