### ISSUE TITLE
Removal of the credentials_file config option is not mentioned in the upgrade guidelines.

### ISSUE THREAD

**Issue by flaper87** [hashicorp/vault#10135]
The [1.5.0 upgrade guidelines](https://github.com/hashicorp/vault/blob/master/website/pages/docs/upgrading/upgrade-to-1.5.0.mdx) don't mention https://github.com/hashicorp/vault/pull/9424 which can break a deployment depending on it. I found out about it the hard way and then found: https://discuss.hashicorp.com/t/vault-gcs-backend/11177/4

**Comment by kalafut** [comment]
Thanks for highlighting this! We'll add a reference to the upgrade guide.
