### ISSUE TITLE
Make limited allowed transit key types configurable 

### ISSUE THREAD

**Issue by lngoquy1** [hashicorp/vault#10134]
**Feature Request:**
For security compliance reasons, when enabling Vault Transit Engine, we would want to restrict creation of transit keys with certain key types listed [here](https://www.vaultproject.io/api-docs/secret/transit#type), e.g. AES and RSA key types should be valid, any requests with other key types should be invalid. 

We notice that for [signing](https://www.vaultproject.io/api-docs/secret/transit#parameters-12), using sha1 can be blocked by having this policy
```
path "/transit/sign/:name/sha1" {
  capabilities = ["deny"]
}
``` 
Maybe there could be a way to block transit key creation with non-allowed key types?

**Environment:**

* Vault Version: 1.5.*
* Operating System/Architecture: any

**Comment by shwuandwing** [comment]
You can use Vault policy's parameter constraints to do this.

https://www.vaultproject.io/docs/concepts/policies#parameter-constraints

e.g.
#  create keyrings restrictions
path "transit/keys/+" {
  capabilities = ["create", "update", "read", "list"]
  denied_parameters = {
    # Prevent rsa keys from being created
    "type" = ["rsa-2048", "rsa-3072", "rsa-4096"]
  }
}

**Comment by raskchanky** [comment]
@lngoquy1 Does the solution @shwuandwing presented meet your needs?

**Comment by lngoquy1** [comment]
Thanks, I will try that @shwuandwing @raskchanky and let you know!
