### ISSUE TITLE
leader-ca-cert in cli and config

### ISSUE THREAD

**Issue by ingtarius** [hashicorp/vault#10153]
**Describe the bug**
leader-ca-cert in CLI and in config working in different ways

**To Reproduce**
Create 2 vault node with self-signed ssl and raft storage, unseal first node and add retry_join section to second node like this:
```  
retry_join {
    leader_api_addr = "https://node1:8200"
    leader_ca_cert = "/vault/ssl/rootCA.crt"
  }
```
After start second node - many errors `"x509: certificate signed by unknown authority"` in logs and second node cant connect to first node.
You can run this command:
`vault operator raft join -leader-ca-cert=@/vault/ssl/rootCA.crt https://node1:8200`
and second node will be joined to cluster.
It looks like `leader-ca-cert` ignored in retry_join section, even if i spell it with `@` symbol

**Expected behavior**
Second node joined to cluster without cli commands

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```Key                     Value
---                     -----
Seal Type               shamir
Initialized             true
Sealed                  false
Total Shares            5
Threshold               3
Version                 1.5.4
Cluster Name            vault-cluster-4b5cede5
Cluster ID              a2c9a7ec-e587-fc96-ceaf-7b8c65376ffd
HA Enabled              true
HA Cluster              https://node1:8201
HA Mode                 active
Raft Committed Index    50
Raft Applied Index      50
```
* Vault CLI Version (retrieve with `vault version`):
```Vault v1.5.4 (1a730771ec70149293efe91e1d283b10d255c6d1)```
* Server Operating System/Architecture:
vault running in docker container, from docker hub

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
ui = true
disable_mlock = true

service_registration "consul" {
  address = "127.0.0.1:8500"
  service = "vault"
  service_address = ""
}

storage "raft" {
  path    = "/vault/data"
  node_id = "node1"
  retry_join {
    leader_api_addr = "https://active.vault.example.com:8200"
    leader_ca_cert = "/vault/ssl/rootCA.crt"
  } 
}

listener "tcp" {
  address     = "10.10.10.10:8200"
  tls_disable = "false"
  tls_cert_file = "/vault/ssl/active.vault.example.com.crt"
  tls_key_file = "/vault/ssl/active.vault.example.com.key"
  tls_client_ca_file = "/vault/ssl/rootCA.crt"
  tls_require_and_verify_client_cert = "false"
  tls_disable_client_certs = "true"
}

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = "false"
  tls_cert_file = "/vault/ssl/active.vault.example.com.crt"
  tls_key_file = "/vault/ssl/active.vault.example.com.key"
  tls_client_ca_file = "/vault/ssl/rootCA.crt"
  tls_require_and_verify_client_cert = "false"
  tls_disable_client_certs = "true"
}

api_addr = "https://127.0.0.1:8200"
cluster_addr = "https://node1:8201"
log_level = "Debug"
```

**Additional context**
Used envs is
```
VAULT_CACERT=/vault/ssl/rootCA.crt
VAULT_ADDR=https://127.0.0.1:8200
VAULT_SKIP_VERIFY=true
```

May be, retry_join is used only for rebooted members? In this case i should joined new nodes by hands any time?

**Comment by raskchanky** [comment]
@ingtarius From looking at [the raft storage docs](https://www.vaultproject.io/docs/configuration/storage/raft#retry_join-stanza), it looks like the config option is written in snake case instead of kebab case, e.g. try `leader_ca_cert` instead of `leader-ca-cert`.

**Comment by ingtarius** [comment]
@raskchanky  sorry for this error in report, i paste it from console.
Re-check my config, with section
```
storage "raft" {
  path    = "/vault/data"
  node_id = "node5"
  retry_join {
    leader_api_addr = "https://active.vault.example.com:8200"
    leader_ca_cert = "/vault/ssl/rootCA.crt"
  }
}
```
i see errors about certificate authority `x509: certificate signed by unknown authority"` and this error gone after `vault operator raft join -leader-ca-cert=@/vault/ssl/rootCA.crt "https://active.vault.example.com:8200"`

**Comment by raskchanky** [comment]
@ingtarius I'm glad you got it sorted out!
