### ISSUE TITLE
HashiCorp Vault's press-kit.zip is actually HashiCorp Consul's press-kit.zip

### ISSUE THREAD

**Issue by reubendevries-cta** [hashicorp/vault#10157]
**Describe the bug**

HashiCorp Vault's press-kit.zip is actually HashiCorp Consul's press-kit.zip

**To Reproduce**

1. Go to [https://github.com/hashicorp/vault/tree/master/website/public/files](https://github.com/hashicorp/vault/tree/master/website/public/files)
2. Download press-kit.zip
3. Extract zip file and inspect files in folder.

**Expected behavior**
When I download the press-kit.zip for Vault I expect to get the press-kit regarding Hashicorp Vault, not Hashicorp Consul.

**Comment by kalafut** [comment]
@jescalan Could you look into this?

**Comment by jescalan** [comment]
Definitely, I will get this patched up tomorrow morning. Thanks for catching!
