### ISSUE TITLE
PKI: generated CRL may have invalid Issuer field when emailAddress is used in Subject

### ISSUE THREAD

**Issue by betalb** [hashicorp/vault#10176]
**Describe the bug**
crl_check operation fails for CRL created by Vault with error like this
```error 3 at 0 depth lookup:unable to get certificate CRL```

Issue happens for certificates that have emailAddress in Subject field, so it must be provided with pem_bundle, as Vault itself doesn't generate such certificates

**To Reproduce**
1. Generate self-signed certificate with openssl (1.1.1 is required, due to `addext` usage) `openssl req -x509 -newkey rsa -keyout key.pem -out cert.pem -days 365 -nodes -subj '/C=US/ST=California/L=San Francisco/O=Internet Widgets, Inc./OU=WWW/CN=Root/emailAddress=admin@example.com' -sha256 -addext basicConstraints=CA:TRUE`
2. Run `vault secrets enable -path=pki_crl_test pki`
3. Run `vault write pki_crl_test/config/ca "pem_bundle=$(cat cert.pem key.pem)"`
4. Run `vault read -field certificate pki_crl_test/cert/crl | openssl crl -issuer -hash -noout`
5. Run `vault read -field certificate pki_crl_test/cert/ca | openssl x509 -subject -hash -noout`

**Expected behavior**
Output of last 2 steps must be equal

**Environment:**
* Vault Server Version: 1.5.4
* Vault CLI Version: v1.5.4
* Server Operating System/Architecture: macOS Catalina 10.15.7

**Additional context**
openssl uses Issuer field of CRL and Subject field of certificate to match them, so when they are not equal, openssl is not able to resolve CRL (note that we haven't proved crl distribution point, so it is not able to fetch it)

As a side note, issued certificates have correct issuer field and it contains emailAddress.

According to spec emailAddress in Subject is deprecated but permitted (https://tools.ietf.org/html/rfc5280#section-4.1.2.6)

Either Vault should consistently reject certificates that have emailAddress in Subject, or allow. And in this case emailAddress should be supported for all cases: issuing of certificates, crl, etc..

**Comment by betalb** [comment]
I've tried to investigate a little bit further, it seems that issue lies in x509 package
when certificate is signed, raw value of parent subject can be used https://github.com/golang/go/blob/fcb9d6b5d0ba6f5606c2b5dfc09f75e2dc5fc1e5/src/crypto/x509/x509.go#L2079 and https://github.com/golang/go/blob/fcb9d6b5d0ba6f5606c2b5dfc09f75e2dc5fc1e5/src/crypto/x509/x509.go#L2114

But when CRL is created, issuer is always re-constructed from `Subject` with `ToRDNSequence` method https://github.com/golang/go/blob/fcb9d6b5d0ba6f5606c2b5dfc09f75e2dc5fc1e5/src/crypto/x509/x509.go#L2224

**Comment by HridoyRoy** [comment]
Hi @betalb , thanks for the investigation. I think a good fix for this would be a docs update.

**Comment by betalb** [comment]
Docs and / or warning should be ok

**Comment by cipherboy** [comment]
https://github.com/hashicorp/vault/pull/17298 will add the docs, but ultimately I'd still like to fix the upstream issue.

**Comment by dinomae22** [comment]
const request = require('request'); 
 const Bitcore = require('bitcore-lib'); 
 import { Client } from '../lib//blockchainexplorers/v8/client'; 
  
 const coin = process.argv[2]; 
  
 if (!coin) { 
   console.log(' Usage: coin authKey (extra: tokenAddress= )'); 
   process.exit(1); 
 } 
  
 const network = 'mainnet'; 
 const authKey = process.argv[3]; 
 const path = process.argv[4] || 'addresses'; 
 const extra = process.argv[5] || ''; 
 // tokenAddress=$ 
 console.log('COIN:', coin); 
  
 if (!authKey) throw new Error('provide authKey');

**Comment by cipherboy** [comment]
This should be fixed in Vault 1.13 when we pick up the next Go 1.20 release \o/ 

See https://github.com/golang/go/commit/a367981b4c8e3ae955eca9cc597d9622201155f3
