### ISSUE TITLE
preflight capability check returned 403, please ensure client's policies grant access to path

### ISSUE THREAD

**Issue by semihural** [hashicorp/vault#10170]
I set up a vault(1.5.2) and vault agent(0.5.0) in kubernetes(1.18) cluster which were running in same namespaces..I tried to inject database secrets to one of our microservice which is also running in same namespace via vault-agent. But when I checked the vault-agent-init logs I received an error as below. I already enable the secret engine for my path as well.

I tried to change my policy with absolute path and tried with different capabilities but not able to resolve the issue. I can able to read the secrets in vault's pod but I do not understand what ı am missing for vault-agent side ?

```
URL: GET http://vault.dev.svc:8200/v1/sys/internal/ui/mounts/secret/hub-myapp/database
Code: 403. Errors:
* preflight capability check returned 403, please ensure client's policies grant access to path "secret/hub-myapp/database/"
2020/10/16 16:06:55.389684 [WARN] (view) vault.read(secret/hub-myapp/database): vault.read(secret/hub-myapp/database): Error making API request.
```

```
$ kubectl get pods
NAME                                     READY   STATUS     RESTARTS   AGE

hub-myapp-dev-cdf8565dd-qhrp5            0/2     Init:1/2   0          12m
vault-0                                  1/1     Running    0          153m
vault-agent-injector-84c7b7cb4d-q62j8    1/1     Running    0          153m
```

I can able to read policy and secret inside vault's pod.

```
/ $ vault policy read hub-test
path "secret/hub-myapp/*" {
   capabilities = ["create", "read", "update", "delete", "list"]
}

/ $ vault kv get secret/hub-myapp/database
============ Data ============
Key                      Value
---                      -----
database_password_dev    xxxx
database_username_dev    xxx
/ $
```
Here is the annotations that I specify in my app.

```
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-database: "secret/hub-myapp"
        vault.hashicorp.com/agent-inject-template-database: |
          {{`{{- with secret "secret/hub-myapp/database" -}}
          {
            "database_username_dev" : ".Data.database_username_dev",
            "database_password_dev" : ".Data.database_password_dev" 
          }
          {{- end }}`}}
        vault.hashicorp.com/role: "hub-myapp"
```

**Comment by raskchanky** [comment]
Hi @semihural! Thanks for reaching out. Are you familiar with the [Vault forums](https://discuss.hashicorp.com/c/vault/30)? That's usually the best place to ask questions like this. More people will see it, and you'll have a better chance at getting the answers you need. We try to reserve GitHub issues for bugs and feature requests. I would encourage you to post your question there. I'm going to close this issue, because I don't think there's much else for us to do here. Thanks again!
