### ISSUE TITLE
vault read secret/hello not always returns value

### ISSUE THREAD

**Issue by jurgen-kluft** [hashicorp/vault#1018]
Machine: Windows 7, Core i7 (64-bit) 24GB

Running vault server -dev

After executing vault write secret/hello value=World, repeated calls to 'vault read secret/hello' sometimes returns a value, sometimes nothing.

**Comment by jefferai** [comment]
Hi @jurgen-kluft ,

What version of Vault is this? What does the Vault log have in it?

Thanks!

**Comment by jurgen-kluft** [comment]
Hi Jeff,

let me know if the below is enough for you.

Thanks


Vault v0.4.1.

On my own and another machine i am running Consul and have configured Vault to use Consul as the back-end. When starting Consul i don't see any errors, the same with Vault, no errors.



-----------------------------------------------------------------------------------------------------------------
D:\Programs\Hashicorp>vault server -config=example.hcl
==> WARNING: mlock not supported on this system!

  The `mlock` syscall to prevent memory from being swapped to
  disk is not supported on this system. Enabling mlock or
  running Vault on a system with mlock is much more secure.

==> Vault server configuration:

         Log Level: info
             Mlock: supported: false, enabled: true
           Backend: consul (HA available)
 Advertise Address: http://127.0.0.1:8200
        Listener 1: tcp (addr: "127.0.0.1:8200", tls: "disabled")
           Version: Vault v0.4.1

==> Vault server started! Log data will stream in below:

2016/02/03 18:24:45 [INFO] core: vault is unsealed
2016/02/03 18:24:45 [INFO] core: entering standby mode
2016/02/03 18:24:45 [INFO] core: acquired lock, enabling active operation
2016/02/03 18:24:45 [INFO] core: post-unseal setup starting
2016/02/03 18:24:45 [INFO] core: mounted backend of type generic at logical/7d1fb969-d97f-9621-cf15-ef0c9d42fb37/
2016/02/03 18:24:45 [INFO] core: mounted backend of type cubbyhole at logical/435ff48e-7eaa-1e66-5920-49fd22745a24/
2016/02/03 18:24:45 [INFO] core: mounted backend of type system at sys/
2016/02/03 18:24:45 [INFO] rollback: starting rollback manager
2016/02/03 18:24:45 [INFO] core: post-unseal setup complete

**Comment by jefferai** [comment]
Hi Jurgen,

When it doesn't return a value, what happens? Does it hang? Does it say that nothing was found? Knowing how it behaves may help figure out what the issue is.

Thanks!

**Comment by jurgen-kluft** [comment]
I only have had it hang rarely (1%), 50% of the time it outputs nothing (it
doesn't hang), the other 49% of the time it outputs the correct result.

**Comment by jefferai** [comment]
Definitely strange. How are you running Consul, and which version? Is it an HA setup? Do you have anything of interest in the Consul logs?

Usually the only thing that causes a Vault read to hang is if it can't talk to Consul as Vault itself is kind of like a crypto passthrough to the backend. So the fact that you are occasionally seeing hangs suggests some kind of error with Consul or with communication to Consul.

**Comment by jurgen-kluft** [comment]
Well i am experiencing the same (from 'hang' to outputting nothing) with a 'vault server -dev' instance.

**Comment by jefferai** [comment]
That's good to know. I'll try to reproduce...it's a Windows 10 box though.

**Comment by jefferai** [comment]
Hi @jurgen-kluft 

Unfortunately I just can't reproduce it. I started `.\vault.exe server -dev` in one powershell and opened up another, set `VAULT_ADDR`, wrote a value, then used the following:

```
PS C:\Users\Jeff\Downloads> for(
>>> $i=0
>>> $i -le 1000
>>> $i++) {
>>> echo $i
>>> .\vault.exe read secret/hello
>>> }
```

It worked exactly as it should -- no blank values, no hangs, all the way through to 1000.

**Comment by jurgen-kluft** [comment]
Hi @jefferai,

I followed your point and used Powershell, when starting vault i get this in the log and when using vault to write a key i still get these possible outcomes; hang, no output, success:

.\vault.exe : 2016/02/06 14:42:31 [INFO] core: security barrier initialized (shares: 1, threshold 1)
At line:1 char:1
+ .\vault.exe server -dev
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (2016/02/06 14:4...1, threshold 1):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
2016/02/06 14:42:31 [INFO] core: post-unseal setup starting
2016/02/06 14:42:31 [INFO] core: mounted backend of type generic at logical/f6225056-af03-62a4-1126-49780a9adb9d/
2016/02/06 14:42:31 [INFO] core: mounted backend of type cubbyhole at logical/5bd0f55b-85f9-f28e-8113-ab56de64ac31/
2016/02/06 14:42:31 [INFO] core: mounted backend of type system at sys/
2016/02/06 14:42:31 [INFO] core: post-unseal setup complete
2016/02/06 14:42:31 [INFO] core: root token generated
2016/02/06 14:42:31 [INFO] core: pre-seal teardown starting
2016/02/06 14:42:31 [INFO] rollback: starting rollback manager
2016/02/06 14:42:31 [INFO] rollback: stopping rollback manager
2016/02/06 14:42:31 [INFO] core: pre-seal teardown complete
2016/02/06 14:42:31 [INFO] core: vault is unsealed
2016/02/06 14:42:31 [INFO] core: post-unseal setup starting
2016/02/06 14:42:31 [INFO] core: mounted backend of type generic at logical/f6225056-af03-62a4-1126-49780a9adb9d/
2016/02/06 14:42:31 [INFO] core: mounted backend of type cubbyhole at logical/5bd0f55b-85f9-f28e-8113-ab56de64ac31/
2016/02/06 14:42:31 [INFO] core: mounted backend of type system at sys/
2016/02/06 14:42:31 [INFO] core: post-unseal setup complete
2016/02/06 14:42:31 [INFO] rollback: starting rollback manager

**Comment by jefferai** [comment]
It'd be helpful if you can try with 0.5.0-rc2 released a couple of days ago. At least that initial error *should* be gone.

**Comment by jurgen-kluft** [comment]
@jefferai, obtaining the v0.5.0 version does give me a sense something has changed but now after a couple of executions i get an exception, i haven't gotten an empty return anymore. So now it has changed to Ok or Exception. 

The details of the exception is:
Exception 0xe06d7363 0x19930520 0x6f9c0 0x7fefd6fb16d
PC=0x7fefd6fb16d

syscall.Syscall9(0x7feff0b13b0, 0x7, 0x254, 0xc0820214b0, 0x1, 0xc082021498, 0x0, 0xc082021468, 0x0, 0x0, ...)
        /goroot/src/runtime/syscall_windows.go:150 +0x5c
syscall.WSASend(0x254, 0xc0820214b0, 0x1, 0xc082021498, 0x0, 0xc082021468, 0x0, 0x0, 0x0)
        /goroot/src/syscall/zsyscall_windows.go:1529 +0xc4
net.(*netFD).Write.func1(0xc082021468, 0x0, 0x0)
        /goroot/src/net/fd_windows.go:513 +0x8c
net.(*ioSrv).ExecIO(0xc08202a2d8, 0xc082021468, 0x1314768, 0x7, 0x15b3c00, 0x9483c0, 0x0, 0x0)
        /goroot/src/net/fd_windows.go:160 +0xd5
net.(*netFD).Write(0xc082021380, 0xc0821f0000, 0xc9, 0x1000, 0x0, 0x0, 0x0)
        /goroot/src/net/fd_windows.go:514 +0x181
net.(*conn).Write(0xc08202a2e0, 0xc0821f0000, 0xc9, 0x1000, 0x0, 0x0, 0x0)
        /goroot/src/net/net.go:184 +0xeb
bufio.(*Writer).flush(0xc0821e6180, 0x0, 0x0)
        /goroot/src/bufio/bufio.go:562 +0xe7
bufio.(*Writer).Flush(0xc0821e6180, 0x0, 0x0)
        /goroot/src/bufio/bufio.go:551 +0x34
net/http.(*persistConn).writeLoop(0xc0820e54a0)
        /goroot/src/net/http/transport.go:1017 +0x2b8
created by net/http.(*Transport).dialConn
        /goroot/src/net/http/transport.go:686 +0xca4

goroutine 1 [select]:
net/http.(*persistConn).roundTrip(0xc0820e54a0, 0xc08217e980, 0x0, 0x0, 0x0)
        /goroot/src/net/http/transport.go:1164 +0xb14
net/http.(*Transport).RoundTrip(0xc082062bd0, 0xc082086d20, 0x0, 0x0, 0x0)
        /goroot/src/net/http/transport.go:235 +0x537
net/http.send(0xc082086d20, 0x2684800, 0xc082062bd0, 0xc0821e0a80, 0x0, 0x0)
        /goroot/src/net/http/client.go:220 +0x533
net/http.(*Client).send(0xc0821e07e0, 0xc082086d20, 0x25, 0x0, 0x0)
        /goroot/src/net/http/client.go:143 +0x161
net/http.(*Client).doFollowingRedirects(0xc0821e07e0, 0xc082086d20, 0x15b3e38, 0x0, 0x0, 0x0)
        /goroot/src/net/http/client.go:380 +0xbc7
net/http.(*Client).Do(0xc0821e07e0, 0xc082086d20, 0x0, 0x0, 0x0)
        /goroot/src/net/http/client.go:178 +0x18f
github.com/hashicorp/vault/api.(*Client).RawRequest(0xc0821e2440, 0xc0821dfa10, 0xc0821e07b0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/api/client.go:248 +0xd3
github.com/hashicorp/vault/api.(*Logical).Write(0xc0821dfac0, 0xc082004270, 0xc, 0xc0821e07b0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/api/logical.go:52 +0x2f4
github.com/hashicorp/vault/command.(*WriteCommand).Run(0xc0820e5340, 0xc08200a420, 0x2, 0x2, 0xc08217e3e0)
        /gopath/src/github.com/hashicorp/vault/command/write.go:58 +0x6f0
github.com/mitchellh/cli.(*CLI).Run(0xc08213c0c0, 0xc08213c0c0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/mitchellh/cli/cli.go:153 +0x5f5
github.com/hashicorp/vault/cli.RunCustom(0xc08200a410, 0x3, 0x3, 0xc0821a5da0, 0x6)
        /gopath/src/github.com/hashicorp/vault/cli/main.go:44 +0x455
github.com/hashicorp/vault/cli.Run(0xc08200a410, 0x3, 0x3, 0xa287a7)
        /gopath/src/github.com/hashicorp/vault/cli/main.go:11 +0x53
main.main()
        /gopath/src/github.com/hashicorp/vault/main.go:10 +0x67

goroutine 5 [syscall]:
os/signal.loop()
        /goroot/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
        /goroot/src/os/signal/signal_unix.go:28 +0x3e

goroutine 7 [semacquire]:
sync.runtime_Syncsemacquire(0xc08213c1c0)
        /goroot/src/runtime/sema.go:237 +0x20f
sync.(*Cond).Wait(0xc08213c1b0)
        /goroot/src/sync/cond.go:62 +0xa2
io.(*pipe).read(0xc08213c180, 0xc0821e4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /goroot/src/io/pipe.go:52 +0x2d9
io.(*PipeReader).Read(0xc08202a280, 0xc0821e4000, 0x1000, 0x1000, 0x4021d5, 0x0, 0x0)
        /goroot/src/io/pipe.go:134 +0x57
bufio.(*Scanner).Scan(0xc082164d80, 0x2)
        /goroot/src/bufio/scan.go:180 +0x87e
github.com/hashicorp/vault/command.(*Meta).FlagSet.func1(0xc082164d80, 0xc0820e5340)
        /gopath/src/github.com/hashicorp/vault/command/meta.go:187 +0x2c
created by github.com/hashicorp/vault/command.(*Meta).FlagSet
        /gopath/src/github.com/hashicorp/vault/command/meta.go:190 +0x5ed

goroutine 10 [IO wait]:
net.runtime_pollWait(0x268a6a8, 0x72, 0xc0821fc010)
        /goroot/src/runtime/netpoll.go:157 +0x67
net.(*pollDesc).Wait(0xc0820214f0, 0x72, 0x0, 0x0)
        /goroot/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc08202a2d0, 0xc0820213e0, 0x1314760, 0x7, 0x15b3bf8, 0x0, 0x0, 0x0)
        /goroot/src/net/fd_windows.go:182 +0x177
net.(*netFD).Read(0xc082021380, 0xc0821e5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /goroot/src/net/fd_windows.go:463 +0x17e
net.(*conn).Read(0xc08202a2e0, 0xc0821e5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /goroot/src/net/net.go:172 +0xeb
net/http.noteEOFReader.Read(0x268a768, 0xc08202a2e0, 0xc0820e54f8, 0xc0821e5000, 0x1000, 0x1000, 0xc0821f8000, 0x0, 0x0)
        /goroot/src/net/http/transport.go:1370 +0x6e
net/http.(*noteEOFReader).Read(0xc0821e27e0, 0xc0821e5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd7
bufio.(*Reader).fill(0xc08217c600)
        /goroot/src/bufio/bufio.go:97 +0x1f0
bufio.(*Reader).Peek(0xc08217c600, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /goroot/src/bufio/bufio.go:132 +0xd3
net/http.(*persistConn).readLoop(0xc0820e54a0)
        /goroot/src/net/http/transport.go:876 +0xfe
created by net/http.(*Transport).dialConn
        /goroot/src/net/http/transport.go:685 +0xc7f
rax     0x3eae228f
rbx     0x6f9c0
rcx     0x6f250
rdi     0x180069528
rsi     0x46bfb20
rbp     0x6f990
rsp     0x6f860
r8      0x0
r9      0x0
r10     0x180000000
r11     0x6f8a0
r12     0x46bfb20
r13     0x1
r14     0xc0820214b0
r15     0x254
rip     0x7fefd6fb16d
rflags  0x202
cs      0x33
fs      0x53
gs      0x2b

**Comment by jefferai** [comment]
I ran my test script from before with 0.5.0 and still cannot reproduce. I'm using the amd64 binary on Windows 10. I unfortunately do not have a Windows 7 box to test on.
