### ISSUE TITLE
Website: Create and maintain a list of Vault tools

### ISSUE THREAD

**Issue by maticmeznar** [hashicorp/vault#1019]
It would be great if Vault website - https://www.vaultproject.io/ had a list of tools that use or extend Vault, identical to what already exists for Consul - https://www.consul.io/downloads_tools.html. A list like this would increase discoverability of tools, which will increase the usability of Vault and increase its adoption/popularity, leading to a better Vault experience for everyone.

**Comment by jefferai** [comment]
Thanks for the suggestion!

**Comment by jippi** [comment]
if this gets done, id like to put my php sdk out there https://github.com/jippi/vault-php-sdk

**Comment by jefferai** [comment]
@jippi We already have a list of libraries (https://www.vaultproject.io/docs/http/libraries.html). I'll add it to the list!
