### ISSUE TITLE
Cannot change or remove rate-limit

### ISSUE THREAD

**Issue by gnugnug** [hashicorp/vault#10191]
I'm trying to set up a quota on issuing certificates with Vault 1.5.4 on Linux x64:

```
# Configure rate-limit
vault write sys/quotas/rate-limit/pki-issue-limit path=pki/ rate=1
Success! Data written to: sys/quotas/rate-limit/pki-issue-limit

vault write pki/issue/testrole common_name="test1"
Error writing data to pki/issue/testrole: Error making API request.
URL: PUT https://vault:8200/v1/pki/issue/testrole
Code: 400. Errors:
* common name test1 not allowed by this role

vault write pki/issue/testrole common_name="test2"
Error writing data to pki/issue/dm-server-netze-pki: Error making API request.
URL: PUT https://vault:8200/v1/pki/issue/testrole
Code: 429. Errors:
* request path "pki/issue/testrole": rate limit quota exceeded

# Change path and rate-limit
vault write sys/quotas/rate-limit/pki-issue-limit path=pki/issue/ rate=2
Success! Data written to: sys/quotas/rate-limit/pki-issue-limit

vault write pki/issue/testrole common_name="test1"
Error writing data to pki/issue/testrole: Error making API request.
URL: PUT https://vault:8200/v1/pki/issue/testrole
Code: 400. Errors:
* common name test1 not allowed by this role

vault write pki/issue/testrole common_name="test2"
Error writing data to pki/issue/dm-server-netze-pki: Error making API request.
URL: PUT https://vault:8200/v1/pki/issue/testrole
Code: 429. Errors:
* request path "pki/issue/testrole": rate limit quota exceeded
```
Expected behaviour: Here I would have expected to be able to send a second request due to rate=2

```
# Delete rate-limit
vault delete sys/quotas/rate-limit/pki-issue-limit
Success! Data deleted (if it existed) at: sys/quotas/rate-limit/pki-issue-limit

vault list sys/quotas/rate-limit
No value found at sys/quotas/rate-limit/

vault write pki/sign/testrole common_name="test1"
Error writing data to pki/sign/testrole: Error making API request.
URL: PUT https://vault:8200/v1/pki/sign/testrole
Code: 400. Errors:
* "csr" is empty

vault write pki/sign/testrole common_name="test2"
Error writing data to pki/sign/testrole: Error making API request.
URL: PUT https://vault:8200/v1/pki/sign/testrole
Code: 429. Errors:
* request path "pki/sign/testrole": rate limit quota exceeded
```
Expected behaviour: Even after deleting the rate-limit, I still receive rate-limit errors. I even changed the path.
This is only fixed by restarting Vault. What am I doing wrong? Unfortunately the documentation does not give any explanation what can be entered as _path_ and if the rate-limit applies globally, or per client IP, or per logged in identity, ...

**Comment by raskchanky** [comment]
Hi @gnugnug! Thanks for reaching out. Are you aware of the [Vault forums](https://discuss.hashicorp.com/c/vault/30)? I think you'll have a better chance at getting an answer to your question if you post it there. We try to reserve GitHub issues for bugs or feature requests. I'm going to close this issue now, as I don't think there's much left for us to do. Thanks again!

**Comment by gnugnug** [comment]
Hello @raskchanky,
I believe that when Vault lists no existing quotas at sys/quotas/rate-limit and I still receive HTTP 429 errors, that this is actually a bug. Or am I missing something here and this is just an user error? Then I'm fine with moving over to the forums.

**Comment by raskchanky** [comment]
Unfortunately, I don't know enough about the rate limiting feature to tell if this is a legitimate bug or just misconfiguration. If it's a legitimate bug then we should definitely reopen this and investigate. @vishalnayak or @alexanderbez can either of you weigh in on this?

**Comment by gnugnug** [comment]
I added more explanations in the first comment on what I believe doesn't work as expected.
