### ISSUE TITLE
Make physical backends more visible in docs

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vault#1020]
Having 3 separate sections with quite a prominent link on the main docs page:
- Secret Backends
- Auth Backends
- Audit Backends

I'm thinking that physical backends deserve such separate section too.
It took me a while to find the full list of supported physical backends and I think it should have much more prominent position in docs than just a bullet-pointed list in the Configuration section:
https://www.vaultproject.io/docs/config/index.html

https://github.com/hashicorp/vault/tree/master/physical

**Comment by Niks-JJ** [comment]
I agree. I spent 1 day setting up dynamic secret backend and realised later that I wanted a storage backend

**Comment by Niks-JJ** [comment]
Also, I am new to Vault-Consul concepts. 
Trying to set up vault with Consul storage backend. 
Is anyone aware that do we explicitly write to Consul backend or write to secret backend actually writes to backend storage, consul in my case. Ex. 
vault write secret/myKey3 value=xyz

Will this actually write to consule?

**Comment by sethvargo** [comment]
Hey there,

We did this awhile ago, albeit not a completely separate section of "backends", but a subset of the configuration: https://www.vaultproject.io/docs/configuration/storage/index.html
