### ISSUE TITLE
Vault Integrated Storage : Snapshot Agent

### ISSUE THREAD

**Issue by venky999** [hashicorp/vault#10211]
**Is your feature request related to a problem? Please describe.**
At the moment we don't see any feature like `consul snapshot agent` for vault integrated storage

**Describe the solution you'd like**
Please provide mechanism to automatically take snapshots of vault integrated storage backend like we have with consul.

https://www.consul.io/commands/snapshot/agent

**Comment by ncabatoff** [comment]
Hi @venky999,

We're going to include functionality equivalent to the Consul snapshot agent in Vault Enterprise 1.6, due out in the not so distant future.
