### ISSUE TITLE
Vault HA configuration with consule backend

### ISSUE THREAD

**Issue by Niks-JJ** [hashicorp/vault#1022]
I need configuration details on setting up consul storage backend in Vault with Vault in High Availability mode so that in case my active vault server goes down, I can still make use of backup Vault and consul. But below link does not provide details on configuration.

https://www.vaultproject.io/docs/concepts/ha.html 

Any pointer will be great help.

**Comment by jefferai** [comment]
Hi there,

Please look at the configuration file information at https://www.vaultproject.io/docs/config/index.html

Thanks!
