### ISSUE TITLE
Dynamic credentials for GCP cloud SQL not working

### ISSUE THREAD

**Issue by omerlh** [hashicorp/vault#10252]
**Describe the bug**
I enabled the db plugin and pointed it to a CloudSQL postgres instance. The credentials generated by the plugin are not accepted by the DB

**To Reproduce**
Use the following TF code to configure the backend:

```
resource "vault_mount" "db" {
  path = "postgres"
  type = "database"
}

resource "vault_database_secret_backend_connection" "db" {
  backend       = "${vault_mount.db.path}"
  name          = "postgres"
  allowed_roles = ["readonly"]

  postgresql {
    connection_url = "postgres://<user>:<password>@localhost:5432/<db>?sslmode=disable"
  }

}

resource "vault_database_secret_backend_role" "role" {
  backend             = "${vault_mount.db.path}"
  name                = "readonly"
  db_name             = "${vault_database_secret_backend_connection.db.name}"
  creation_statements = ["CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';",
        "GRANT SELECT ON <> TO \"{{name}}\";"]
  default_ttl         = 1
  max_ttl             = 24
}
```

Then I generated credentials using

```
vault read --address=<> postgres/creds/readonly
Key                Value
---                -----
lease_id           postgres/creds/readonly/<>
lease_duration     1s
lease_renewable    true
password           <>
username          <>
```

When trying to login with those credentials I am getting an error:

```
psql -h <> <> -U <>
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Password for user <>: 
psql: error: could not connect to server: FATAL:  password authentication failed for user "<>"
FATAL:  password authentication failed for user "<>"
```

And I can see the user exists when running `\du`.

**Expected behavior**
Being able to connect to the DB using the dynamic creds. I think there is similar issue to #4052
**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.4.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.5.5 ('f5d1ddb3750e7c28e25036e1ef26a4c02379fc01+CHANGES')
* Server Operating System/Architecture: Kubernetes (GKE)

**Comment by omelnyk1** [comment]
@omerlh could you please check your SQL instance. Does it deployed in private (via peering) or public network?
Can you find user created by vault in `gcloud sql users list`  output ?

**Comment by omerlh** [comment]
Nope. The DB is public, and I could see the users with `\du`

**Comment by swayne275** [comment]
Hi @omerlh 

Is it possible that the issue is being caused by your specified durations? `lease_duration` is `1s` (one second),`default_ttl` is 1 (one second), and `max_ttl` is 24 (twenty-four seconds). See [this](https://www.vaultproject.io/api-docs/secret/databases).

Please let me know if that addresses the issue you're facing. Thanks!

**Comment by omerlh** [comment]
Yes! Thank you - it was it 🤦 Sorry for the stupid mistake...
