### ISSUE TITLE
Add namespace info in the audit logs when a lease is revoked in Enterprise Vault

### ISSUE THREAD

**Issue by srinivasan-palani** [hashicorp/vault#10255]
**Is your feature request related to a problem? **

In Enterprise Vault when a lease is revoked, namespace is not logged in the audit log, 
we have the same role-name defined in multiple namespaces, quite hard to determine which namespace lease got revoked.

**"revoked lease: lease_id=aws/sts/{role-name}/oSehgGReJrq9NwiGIJRayaEW.i58RH**

**Describe the solution you'd like**
Add namespace in audit-logs while revoking lease for Enterprise Vault

**Comment by hairesis** [comment]
Not a Vault developer, but the last bit **.i58RH** of your lease should represent the namespace id, which also shows up in the audit logs.

**Comment by srinivasan-palani** [comment]
we forward vault audit logs to Datadog for log monitoring. Without namespace info in the revoke lease log, its hard to apply filter for alerting.
