### ISSUE TITLE
Feature request: Amazon CloudWatch logs audit backend

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/vault#1027]
Add an audit backend that posts to Amazon CloudWatch logs.

**Comment by skyzyx** [comment]
:+1:

**Comment by jefferai** [comment]
No current plans, anyone interested can write a PR though.

**Comment by iw** [comment]
Hi, We have a CloudWatch Logs Audit Device we are running locally - https://github.com/eseyecom/vault/tree/cloudwatch-audit-device.

If an appetite remains on inclusion, then we would be super happy composing some PR.

**Comment by nelg** [comment]
> Hi, We have a CloudWatch Logs Audit Device we are running locally - https://github.com/eseyecom/vault/tree/cloudwatch-audit-device.
> 
> If an appetite remains on inclusion, then we would be super happy composing some PR.

Hi Ian (@iw ),

Did you end up writing a pull request for this?  I'd like to use it in a project.

Regards
Glen Ogilvie

**Comment by iw** [comment]
Hi @nelg, I'm afraid this work was abandoned. Ash, a fab engineer with us at the time, orchestrated a sweeter `vault` cluster, with out-of-process publishing to CloudWatch Logs.

Good luck with your efforts.

**Comment by nelg** [comment]
Was that using a file / syslog based audit and a shipper to
cloudwatch/other log tool?

Glen.

**Comment by iw** [comment]
> Was that using a file / syslog based audit and a shipper to cloudwatch/other log tool? Glen.
> […](#)

It was.

I could catch up with Ash on details on choices (assuming his memory is still good on this 😂).

**Comment by nelg** [comment]
Yeah, it makes sense I think to keep the logging out of band, form a
performance/ha perspective.

Glen.
