### ISSUE TITLE
Consul memory gradually increasing to 25G and still remains on the same and raft DB increased upto 300G

### ISSUE THREAD

**Issue by sathuish** [hashicorp/vault#10300]
**Describe the bug**
Consul memory gradually increasing to 25G and still remains on the same and raft DB increased up to 300G since the ttl login tokens are not getting cleaned up even after 5hrs is the RCA we have identified.
ttl set as 5hrs based on our application use case. We have around 4 Million stale login session ids.

**To Reproduce**
1. Run `vault login....` continuously to create 40L login ttl login tokens

**Expected behavior**
The expired token should be cleaned up after 5hrs.

**Environment:**
* Vault Server Version (retrieve with `vault status`):

Key             Value
---             -----
Seal Type       shamir
Sealed          false
Total Shares    5
Threshold       3
Version         0.10.4
Cluster Name    vault-cluster-574ad53a
Cluster ID      14a6a13c-dd51-1807-2b5e-96d63ddf0441
HA Enabled      true
HA Cluster      https://<vault -ip>:<vault-port>
HA Mode         active

* Vault CLI Version (retrieve with `vault version`):

Vault v0.10.4 ('e21712a687889de1125e0a12a980420b1a4f72d3')

* Server Operating System/Architecture:

CentOS Linux release 7.8.2003 (Core)
Kernel Version: 3.10.0-1127.8.2.el7.x86_64
RAM: 32G
CPU: 8 cores

Vault server configuration file(s):
disable_mlock = true
storage "consul" {
    scheme        = "https"
    address       = "<ip>:5912"
    path          = "/sslcerts/vault/vaultdata"
    service       = "vault"
    tls_ca_file   = "/sslcerts/vault/vault-cert.pem"
    tls_cert_file = "/sslcerts/vault/vault-cert.crt"
    tls_key_file  = "/sslcerts/vault/vault-cert.key"
}
api_addr =  "http://<ip>:5920"
cluster_addr = "http://<ip>:5921"
listener "tcp" {
    address             = "0.0.0.0:5920"
    cluster_address     = "0.0.0.0:5921"
    tls_disable         = 0
    tls_require_and_verify_client_cert = 1
    tls_client_ca_file  = "/sslcerts/vault/vault-cert.pem"
    tls_cert_file       = "/sslcerts/vault/vault-cert.crt"
    tls_key_file        = "/sslcerts/vault/vault-cert.key"
    tls_min_version     = "tls12"
    tls_cipher_suites   = "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_RC4_128_SHA,TLS_ECDHE_RSA_WITH_RC4_128_SHA,TLS_ECDHE_ECDSA_WITH_RC4_128_SHA"
 }

```

**Additional context**
Since I'm new to consul and vault, please suggests the best way to set up the vault/consul in production servers. What are items to be considered when setup the vault/consul server to boost up the performance?

**Comment by jeffsanicola** [comment]
That looks to be a pretty dated version of Vault. Does the issue still occur on a more recent release?

**Comment by aphorise** [comment]
@sathuish were you just loging in with those tokens? - also how many did you create?

**Comment by swayne275** [comment]
Hi! Thanks for pointing this out. As this is a very old version of vault [current: 1.6.x, reported: 0.10.x], I'm going to close this issue for now. If it does describe a Vault bug, it was probably fixed long ago. Please re-open if you are still experiencing this on newer versions of vault, and have a great day!

P.S.: You may be able to find additional guidance on the [forum](https://discuss.hashicorp.com/c/vault/) if need be.
