### ISSUE TITLE
aws secret backend can fail when generated userName is too long

### ISSUE THREAD

**Issue by blalor** [hashicorp/vault#1031]
A request to retrieve dynamic AWS credentials failed with a 400 to the client; I found this in the audit log after I enabled `log_raw`:

```json
  "response": {
    "secret": null,
    "data": {
      "error": "Error creating IAM user: ValidationError: 1 validation error detected: Value 'vault-token-perm-instance-dev-aws-gen-us-west-_-i-__c_a_dc-1454701703-5513' at 'userName' failed to satisfy constraint: Member must have length less than or equal to 64\n\tstatus code: 400, request id: 6aae8249-cc41-11e5-ac7c-6b766251e9ee"
    },
    "redirect": ""
  }
```

Vault should make sure the `userName` is valid when creating the IAM user.

**Comment by jefferai** [comment]
Is the policy `perm-instance-dev-aws-gen-us-west-.....` one that got derived from an ARN or does it refer to an inline policy you configured? I could put a limit on the policy length (it'd be 36 characters, it seems) but if the name is ARN-provided then that's a separate constraint. But in that case it would seem that the ARN to your policies are significantly longer than those that implemented the ARN functionality in the first place.

**Comment by blalor** [comment]
I don't really understand the question.  I created the role with

    vault write aws/example/roles/my-role policy=@/path/to/policy.json

So that's an inline policy.  The `display_name` of the token I used to request the AWS credentials is `token-perm-instance-dev-aws-gen-us-west-2-i-06c9a5dc`, which was generated [here](https://github.com/bluestatedigital/centralbooking/blob/master/instance/instance.go#L63-L76); apparently that gets munged quite a bit by Vault.

**Comment by jefferai** [comment]
Ah, ok. Thanks, that helps. There are a few ways that username can get generated so I wasn't sure which.

**Comment by blalor** [comment]
I probably should have mentioned that I’m using a custom build of 0.4.1 with the commit from #912 cherry-picked.

**Comment by jefferai** [comment]
Looked at where the token name was coming from -- looks like central booking, which, BTW, I hadn't seen before, and it's cool! I'd suggest adding information into the readme describing how authentication is performed -- e.g. I assume it does a check on instance metadata provided by the instance, but what keeps someone from spoofing that?

I'm happy to add a check on the total username size; actually decreasing the size (of the token display name) seems like something that needs to be done within central booking.

**Comment by blalor** [comment]
Thanks! centralbooking (or centralborking, as we've come to call it) is pretty nascent but it's one of the core components of our next-gen infrastructure.  I stole the name from @tmclaugh. :-) We will be adding validation when instances register, but I just haven't gotten that in, yet.  It's mentioned in the @todos section of the README, if you know what to look for.  We'll be supporting AWS and GCE.

I agree that the the display name is excessively long coming from centralbooking, but it doesn't feel right to expose the weakness/limitation in AWS to Vault's clients directly.  Chopping it arbitrarily also doesn't seem feasible, especially since you could end up with non-unique usernames in IAM.  Maybe hash it somehow if the `display_name` is too long to be used directly?  Otherwise I'd suggest you should cap the length of the `display_name` property at the time the token's created, and that feels too arbitrary.

**Comment by jefferai** [comment]
The last bits of the IAM role are a timestamp and a random int, so chopping the token name at a certain cutoff should be okay. Plus Vault can return a warning to the client that it did this...

**Comment by blalor** [comment]
Ah, yes; that I like.
