### ISSUE TITLE
Error from AWS when creating IAM User is hashed in audit log

### ISSUE THREAD

**Issue by blalor** [hashicorp/vault#1032]
Related to #1031.  The hashing of the error makes it impossible for the operator to determine what the issue is without enabling `raw_log` on the audit backend.

client:

```
curl -v -ksfS --tlsv1.2 -H "X-Vault-Token: THIS-IS-A-VALID-TOKEN" https://vault.example.com/v1/aws/example/creds/tf-env-dev
```

audit log:

``` json
{
  "time": "2016-02-05T19:48:23Z",
  "type": "request",
  "auth": {
    "display_name": "token-perm-instance-dev-aws-gen-us-west-2-i-06c9a5dc",
    "policies": [
      "instance-management",
      "etcd-member",
      "ci-agent",
      "default"
    ],
    "metadata": {
      "account": "gen",
      "environment": "dev",
      "instance_id": "i-06c9a5dc",
      "provider": "aws",
      "region": "us-west-2",
      "role": "gocd-agent"
    }
  },
  "request": {
    "operation": "read",
    "client_token": "THIS-IS-A-VALID-TOKEN",
    "path": "aws/example/creds/tf-env-dev",
    "data": null,
    "remote_address": "10.1.18.51"
  },
  "error": ""
}
{
  "time": "2016-02-05T19:48:23Z",
  "type": "response",
  "error": "",
  "auth": {
    "display_name": "",
    "policies": [
      "instance-management",
      "etcd-member",
      "ci-agent",
      "default"
    ],
    "metadata": {
      "account": "gen",
      "environment": "dev",
      "instance_id": "i-06c9a5dc",
      "provider": "aws",
      "region": "us-west-2",
      "role": "gocd-agent"
    }
  },
  "request": {
    "operation": "read",
    "client_token": "",
    "path": "aws/example/creds/tf-env-dev",
    "data": null,
    "remote_address": "10.1.18.51"
  },
  "response": {
    "secret": null,
    "data": {
      "error": "hmac-sha256:5e21bd4e662b6f63ed1dd9406250c362b455217985188692ed50b2ecc4ffe046"
    },
    "redirect": ""
  }
}
```

Without enabling `log_raw` on the audit backend, I couldn't even tell if there was a problem with the client's token, within AWS (like an account limit), or within Vault itself.  In this case, the error was

```
"Error creating IAM user: ValidationError: 1 validation error detected: Value 'vault-token-perm-instance-dev-aws-gen-us-west-_-i-__c_a_dc-1454701703-5513' at 'userName' failed to satisfy constraint: Member must have length less than or equal to 64\n\tstatus code: 400, request id: 6aae8249-cc41-11e5-ac7c-6b766251e9ee"
```

The 400 from AWS should not have been passed back to the client, and an operator-friendly error should be put into the audit log.

**Comment by jefferai** [comment]
I will have to start a conversation internally. The policy for the audit log is to hash all strings, regardless of location, and my guess is that this will not change -- errors passed in from various libraries or services may contain sensitive information (accidentally or on purpose) and we want to ensure nothing sensitive is in the audit log.

**Comment by blalor** [comment]
How about, instead of hashing data in the audit log, it’s encrypted in such a way that it can be decrypted through Vault, perhaps using the transit backend?

**Comment by jefferai** [comment]
There is a lookup function that exists to allow you to get the hashed value from a string you provide.

**Comment by blalor** [comment]
Right, but that’s only if I know (or suspect) what the string already is.  If I knew what the error from AWS was, I wouldn’t need to hash it. :-)

**Comment by jefferai** [comment]
Yes, it's true. But we can't access keys in `transit` from the audit backends, so we'd have to build an entirely separate mechanism. Not that it can't happen, but so far feedback we've gotten from security experts has not been to allow decryptable values, to actually to beef up the hashing with an HMAC instead of a bare SHA :-)

**Comment by jefferai** [comment]
In 0.9.6 you'll be able to configure specific data values to not be HMAC'd.
