### ISSUE TITLE
Please include go.mod file in pre-built binaries and docker image.

### ISSUE THREAD

**Issue by christinahaig** [hashicorp/vault#10323]
**Is your feature request related to a problem? Please describe.**
Both the binary provided on the Vault website and the docker image provided at DockerHub (https://hub.docker.com/_/vault) don't appear to have the go.mod file built into the file - whereas if you do a simple make or make dev on the vault source code, that information is built in.  It makes it challenging to discover versions on dependent modules and report them.

**Describe the solution you'd like**
Build these images with go.mod.  Other projects such as helm, minikube, couchbase, istio, harbor, prometheus, terraform, and grafana, are providing pre-built binaries with this info file.

**Describe alternatives you've considered**
To do what we hope to do, we'd have to build our own docker container from the source code instead of relying on the dockerhub version.

**Explain any additional use-cases**
Vault doesn't provide a manifest of third-party modules - we rely on SCA tools to get a manifest.  We need to know what the versions are being used.

**Additional context**
Thanks for your consideration!

**Comment by swayne275** [comment]
Thanks for your comment! I'll bring it up with my team to discuss.

**Comment by swayne275** [comment]
Closing because this issue has been without update for 30+ days. Please re-open if it hasn't been resolved.
