### ISSUE TITLE
Vault 1.6.0-rc build fix

### ISSUE THREAD

**Issue by he32** [hashicorp/vault#10330]
**Describe the bug**

Tried to build 1.6.0-rc, failed with

```
work/src/github.com/hashicorp/vault/plugins/database/redshift/redshift-database-plugin/main.go:25:29: too many arguments in call to redshift.New
        have (bool)
        want ()
work/src/github.com/hashicorp/vault/plugins/database/redshift/redshift-database-plugin/main.go:25:29: multiple-value redshift.New() in single-value context
```

**To Reproduce**
1. Try to build 1.6.0-rc, watch it fail as per the above

**Expected behavior**
The build should complete without errors.

**Environment:**
* Server Operating System/Architecture:
NetBSD/i386 8.0
(Yes, I have minor patches which could well be upstreamed...)

**Suggested fix:**
```
--- plugins/database/redshift/redshift-database-plugin/main.go.orig     2020-11-02 20:22:40.000000000 +0000
+++ plugins/database/redshift/redshift-database-plugin/main.go
@@ -22,7 +22,7 @@ func main() {
 
 // Run instantiates a RedShift object, and runs the RPC server for the plugin
 func Run(apiTLSConfig *api.TLSConfig) error {
-       dbType, err := redshift.New(true)()
+       dbType, err := redshift.New()
        if err != nil {
                return err
        }
```

**Comment by mladlow** [comment]
Hey @he32 - I tried this on the head of the 1.6 release branch and got the build working - it also built on our build systems when we made binaries for the RC and 1.6 GA.

I did the following (I'm building on a mac):
```
make bootstrap
XC_OSARCH=netbsd/386 make
```

That being said, my IDE did warn me about that line. Could you elaborate on how you're building Vault?

**Comment by he32** [comment]
I built this natively on NetBSD/i386 8.0 using go version 1.15 using the pkgsrc package system, in the `security/vault` package directory.  This uses the `../../lang/go/go-package.mk` makefile fragment, which sets a few environment variables in `MAKE_ENV`, and by default does `${RUN} ${_ULIMIT_CMD} ${PKGSRC_SETENV} ${MAKE_ENV} ${GO} install -v ${GO_BUILD_PATTERN}`, and `GO_BUILD_PATTERN` is by default `${GO_SRCPATH}/...`
