### ISSUE TITLE
PHP Client

### ISSUE THREAD

**Issue by timbroder** [hashicorp/vault#1033]
Do you know of anyone who has made or started one?

If not, I'll volunteer to make a [Guzzle](https://github.com/guzzle/guzzle) based one

Thanks

**Comment by jefferai** [comment]
Here's our current list: https://www.vaultproject.io/docs/http/libraries.html

So -- no. That would be great!

**Comment by timbroder** [comment]
@jefferai Just wanted to update here. We have a version of this working internally. It's written specifically for transit right now, but will be fleshing it out over the next month or so and open sourcing it

Also working on a package for Laravel that will be the same easy setup as your Rails module (this part is complete)

**Comment by timbroder** [comment]
Also if people have questions about using vault in PHP or this type of library, please feel free to point the here and I'll answer any questions I can

**Comment by jefferai** [comment]
Very neat! Will be sure to point people your way.

**Comment by jippi** [comment]
I just pushed mine here https://github.com/jippi/vault-php-sdk

**Comment by timbroder** [comment]
Nice. I'll try to push what I have in the next week or so just so people can see what I'm thinking
