### ISSUE TITLE
CollectHostInfo() for different arch 

### ISSUE THREAD

**Issue by Nayana-ibm** [hashicorp/vault#10337]
This is about tests : _github.com/hashicorp/vault/helper/hostutil_  and _github.com/hashicorp/vault/http_ ( as a part of make test execution) 
These tests makes use of routines from https://github.com/shirou/gopsutil/blob/master/cpu/cpu_linux.go#L116 to read /proc/cpuinfo
I could see that this code is mainly used for test cases.  Does it gets used in actual vault functionality? Does it affects any usage?

I could build vault from source as mentioned [here ](https://github.com/hashicorp/vault/tree/v1.5.5)however these two tests are failing for s390x architecture ( with an error: Expected non-nil CPU value) as this arch's /proc/cpuinfo has different contents than intel x86. 

Please let me know.

**Comment by ncabatoff** [comment]
As far as I know only the `vault debug` command depends on this information, more specifically anything hitting the https://www.vaultproject.io/api-docs/system/host-info endpoint.  If you don't use that these failing tests shouldn't concern you.  `vault debug` is a support tool used to collect information from Vault and its environment to help diagnose problems, so it would be unfortunate not to have it available, but not the end of the world.

**Comment by Nayana-ibm** [comment]
Thanks @ncabatoff for insight.
