### ISSUE TITLE
OIDC only with default role

### ISSUE THREAD

**Issue by cpoule23** [hashicorp/vault#10339]
**Is your feature request related to a problem? Please describe.**
Today, i have to create one role per customer to associate a policy.
The user log in with OIDC and have to select the role I have created before.

For a enduser, "role" is not really clear. If all solution have it's own custom parameter for accessing on it, it will be complex to maintain :/

**Describe the solution you'd like**
Like LDAP, have a default role but associate a policy to a custom group get from the idp.

My user is from a support_group CS-TEAM-1. I bound on this field on oauth process, associate a policy TEAM-1 and provide the access on vault on path secrets/TEAM1.

My user is from a support_group CS-TEAM-2. I bound on this field on oauth process, associate a policy TEAM-2 and provide the access on vault on path secrets/TEAM2

and so on 👍 ...

**Describe alternatives you've considered**
today OIDC is working but with one role per feature. I prefer to use ldap who is more clear but need a user / password.

**Comment by kalafut** [comment]
Today you can set the [groups_claim](https://www.vaultproject.io/api/auth/jwt#groups_claim) which will put the user in groups (which do need to exist already in Vault) based on the list of groups in the specified claim. Those identity groups can have whatever policies you want associated with them. This will allow just using a default role and getting additional permission based on IdP group membership.

**Comment by cpoule23** [comment]
Hello, ok I understand this process.

It's working as wanted. Thanks
