### ISSUE TITLE
TLS backend: add slack to NotBefore timestamp

### ISSUE THREAD

**Issue by danderson** [hashicorp/vault#1035]
Occasionally, when I mint a new TLS client cert to talk to my cluster infrastructure, the cert is rejected for a brief period of time. This turns out to be caused by a tiny amount of clock skew within my cluster, which made the server think the cert was only valid in the future. The skew was sub-second, my software and network was just fast enough to beat the clock :).

A common way to deal with this is to add a little slack to the NotBefore timestamp in the cert, e.g. put it 10-60s in the past (I've seen some folks suggest as much as 10 minutes). Vault should add such slack when issuing certificates.

It might also be worth calling out the importance of time synchronization (e.g. with NTP) in the TLS backend documentation. Combined with a small amount of slack, NTP sync should eliminate this class of mysterious failures (mysterious because most TLS stacks will just spit back "bad certificate", and people don't tend to question NotBefore).

**Comment by jefferai** [comment]
Sounds like a fine idea. I don't think ten minutes is necessary...NTP should be able to keep things pretty close on most systems. I would think 10 ought to be fine, but how does 20 sound? Or do you think more?

**Comment by jefferai** [comment]
Seconds, those are. :-)

**Comment by jefferai** [comment]
FYI, I used 30 seconds.

**Comment by danderson** [comment]
30s sounds great. In my case, the clock skew was magnified because my desktop had done a one-time sync, but then had been on for days with the clock drifting. Even in such a "worst case" for clock skew, the skew was something like 0.5s. 30s should be enough to work around even long-term broken time synchronization.

Thanks!
