### ISSUE TITLE
Better health checking for leader election

### ISSUE THREAD

**Issue by blalor** [hashicorp/vault#1037]
I've been bitten by #867, it seems.  I'm using the Consul backend for HA.  I've found that when this happens, Vault just drops client connections.  It's clearly unhealthy, but the leader still retains its leader status because the Consul session doesn't have a health check beyond `serfHealth`.    There should be another health check that's part of the leader election session that ensures Vault is actually healthy.

**Comment by jefferai** [comment]
Adding yet another Consul lock/session check on top of the multiple already performed by the Consul client won't help, because the issue isn't experienced by that connection as it's already open. It's a fairly pathological state. 0.5 fixes this though and is out really, really, really soon.
