### ISSUE TITLE
Unable to disable, enable or use auth method

### ISSUE THREAD

**Issue by DeviaVir** [hashicorp/vault#10381]
**Describe the bug**

Trying to enable our vault method returns:
```
$ vault auth enable -path=gke-alpha kubernetes
Error enabling kubernetes auth: Error making API request.

URL: POST https://XXX/v1/sys/auth/gke-alpha
Code: 400. Errors:

* path is already in use
```

Disabling returns an OK (as documented it does that no matter what):
```
$ vault auth disable gke-alpha
Success! Disabled the auth method (if it existed) at: gke-alpha/
```

However a `vault auth list` still returns it:
```
$ vault auth list
Path                   Type          Accessor                    Description
----                   ----          --------                    -----------
gke-alpha/             kubernetes    auth_kubernetes_e12776d0    n/a
```
(redacted other auth methods)

Trying to use it, however, returns errors like:
```
Error: error writing Kubernetes auth backend config "auth/gke-alpha/config": Error making API request.

URL: PUT https://XXX:8200/v1/auth/gke-alpha/config
Code: 404. Errors:

* no handler for route 'auth/gke-alpha/config'
```
and
```
Error: error writing Kubernetes auth backend role "auth/gke-alpha/role/jenkins-health-checker--XXX": Error making API request.

URL: PUT https://XXX/v1/auth/gke-alpha/role/jenkins-health-checker--XXX
Code: 404. Errors:

* no handler for route 'auth/gke-alpha/role/jenkins-health-checker--XXX
```

**To reproduce**
Unfortunately, I am not sure how we ended up in this situation, so reproduction steps are not readily available. Reinstalling the entire cluster is not an option for us. **Is there another way we can try to remove this auth method so that we can start it from scratch?**

**Expected behavior**
We expected a `vault auth disable` to remove the auth method so we could re-enable it.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.11.6
* Vault CLI Version (retrieve with `vault version`): v1.5.4
* Server Operating System/Architecture: Ubuntu minimal container

Vault server configuration file(s):

```hcl
ui = true

storage "spanner" {
    database = "XXX/vault-backend"
    max_parallel = 15000
    redirect_addr = "XXX"
    cluster_addr = "XXX"
}

ha_storage "spanner" {
    ha_enabled = "true"
    database = "XXX/vault-backend"
    redirect_addr = "XXX"
}

telemetry {
    statsd_address = "127.0.0.1:9125"
}

listener "tcp" {
    address = "0.0.0.0:8200"
    cluster_address = "0.0.0.0:8201"
    tls_cert_file = "/ca-bundle.pem"
    tls_key_file = "/keystore.pem"
}

listener "tcp" {
    address = "127.0.0.1:8100"
    tls_disable = true
}

plugin_directory = "/usr/lib/vault/plugins"
```

**Additional context**
Note that we have multiple `gke-XXX` auth methods that are not having trouble. We are also able to add a new `gke-alpha2` and remove that without trouble:
```
$ vault auth enable -path=gke-alpha2 kubernetes
Success! Enabled kubernetes auth method at: gke-alpha2/

$ vault auth list
Path                   Type          Accessor                    Description
----                   ----          --------                    -----------
[...]
gke-alpha2/            kubernetes    auth_kubernetes_bc2fb5bd    n/a
[...]

$ vault auth disable gke-alpha2
Success! Disabled the auth method (if it existed) at: gke-alpha2/

$ vault auth list
(no longer shows gke-alpha2)
```

**Comment by mikegreen** [comment]
Could you share the policy you're using here?

**Comment by DeviaVir** [comment]
@mikegreen I'm using a root token here, no other policy involved.

**Comment by mikegreen** [comment]
Just noticed the CLI + Server ver differences.
Can you try with the CLI on the same version? https://releases.hashicorp.com/vault/0.11.6/

You can mix versions for CLI (and agent use) but that far might be an issue to rule out here.

**Comment by DeviaVir** [comment]
@mikegreen looks like the same behavior:

```
$ ./vault version
Vault v0.11.6 ('dad2b6048153fea5efbc0c06a5f35c06c767b308')
$ ./vault auth disable gke-alpha/
Error disabling auth method at gke-alpha/: Delete https://XXX/v1/sys/auth/gke-alpha: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
$ ./vault auth disable gke-alpha/
Success! Disabled the auth method (if it existed) at: gke-alpha/
$ ./vault auth list
Path                   Type          Accessor                    Description
----                   ----          --------                    -----------
gke-alpha/             kubernetes    auth_kubernetes_e12776d0    n/a
```

**Comment by DeviaVir** [comment]
Interestingly I was able to run the commands from the vault-server instance directly, which immediately seemed to take effect. I'll close this bug as it's been resolved for me, not sure if this piece of context leads to something actionable.
