### ISSUE TITLE
Consistent return code for 'vault status' when not initialized

### ISSUE THREAD

**Issue by chifflier** [hashicorp/vault#1038]
Somewhere between 0.4.0 and 0.5.0, it seems the return code for the 'vault status' command has changed when the vault is not initialized

vault 0.4.0: returns 2
vault 0.5.0: returns 1 (documentations says 1 is when vault is not unsealed)

Can this be fixed to have a specific, fixed return code (2 would be fine) when vault is not initialized ? I use this when automatically provisioning a vault install, and would prefer to test the return code rather than parse the text on stderr to know if I need to init the vault.

Thanks,
Pierre

**Comment by jefferai** [comment]
The return code for vault being initialized is consistent, but as noted in the Changelog, it has changed from 0.4 to 0.5.

Thanks for pointing out that the documentation hadn't been updated; I've fixed this.

**Comment by chifflier** [comment]
Ah, OK, so the error codes were just swapped, but that was intentional.
Thanks for the quick reply

**Comment by jefferai** [comment]
Yep! Most commands return 1 for error so we wanted to make that consistent with the status command too. There documentation fix will be in 0.5.
