### ISSUE TITLE
Support migrating autoseal to a new key in Azure Key Vault

### ISSUE THREAD

**Issue by braunsonm** [hashicorp/vault#10390]
**Describe the solution you'd like**
With Vault 1.6.0 supporting KMS migration, I would like to see it support the same migration with Azure Key Vault so new keys can be used for the auto unseal process with Key Vault.

**Describe alternatives you've considered**
There is currently no alternative.

**Explain any additional use-cases**
When a key was created awhile ago with a small bitcount it would be nice to be able to move to a new key with a higher bitcount.

**Additional context**
Vault 1.6.0 supports this with Shamir and AWS KMS keys, this would just extend it to Key Vault.

**Comment by ncabatoff** [comment]
Hi @braunsonm,

I'm not aware of anything preventing this from working in 1.6, though I've never actually used key vault for autoseal.  Can you share what's not working for you?

**Comment by braunsonm** [comment]
Hi @ncabatoff 

According to the docs:

> The seal can be migrated from Shamir Seal to KMS Seal, KMS Seal to Shamir Seal, and KMS Seal to another KMS Seal.

Thus, it is only possible to migrate from AWS KMS to another AWS KMS. You cannot migrate directly from an Azure Key Vault to another without first going to a Shamir Seal.

Or am I missing something?

**Comment by ncabatoff** [comment]
I guess I need to improve those docs be less confusing.  As of 1.6, you should be able to migrate directly from any seal to any seal, including the case where both seals are of the same type but with different config.  I'll try to get the docs improved today.

**Comment by ncabatoff** [comment]
Updated the docs in https://github.com/hashicorp/vault/pull/10414.
