### ISSUE TITLE
Error when installing github.com/hashicorp/vault

### ISSUE THREAD

**Issue by wheiderman** [hashicorp/vault#10405]
go get  github.com/hashicorp/vault

go: downloading github.com/hashicorp/vault v1.6.0
go: github.com/hashicorp/vault upgrade => v1.6.0
go: downloading github.com/hashicorp/consul/api v1.4.0
go: downloading github.com/hashicorp/vault/sdk v0.1.14-0.20201109203410-5e6e24692b32
go: downloading github.com/hashicorp/vault-plugin-auth-gcp v0.8.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/hashicorp/vault-plugin-auth-oci v0.6.0
go: downloading github.com/hashicorp/vault-plugin-database-couchbase v0.2.1
go: downloading github.com/hashicorp/vault-plugin-database-mongodbatlas v0.2.1
go: downloading github.com/hashicorp/vault-plugin-secrets-azure v0.8.0
go: downloading github.com/hashicorp/go-kms-wrapping v0.5.16
go: downloading github.com/hashicorp/vault-plugin-auth-centrify v0.7.0
go: downloading github.com/hashicorp/vault-plugin-auth-kerberos v0.2.0
go: downloading github.com/hashicorp/vault-plugin-auth-azure v0.6.0
go: downloading github.com/hashicorp/vault-plugin-secrets-alicloud v0.7.0
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/hashicorp/vault-plugin-auth-alicloud v0.7.0
go: downloading github.com/hashicorp/go-version v1.2.1
go: downloading github.com/hashicorp/vault-plugin-auth-kubernetes v0.8.0
go: downloading gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading gopkg.in/mgo.v2 v2.0.0-20180705113604-9856a29383ce
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/hashicorp/vault-plugin-secrets-mongodbatlas v0.2.0
go: downloading github.com/hashicorp/go-syslog v1.0.0
go: downloading github.com/hashicorp/go-multierror v1.1.0
go: downloading github.com/hashicorp/vault-plugin-auth-cf v0.7.0
go: downloading github.com/hashicorp/go-gcp-common v0.6.0
go: downloading github.com/hashicorp/vault-plugin-secrets-ad v0.8.0
go: downloading github.com/hashicorp/golang-lru v0.5.3
go: downloading github.com/hashicorp/go-memdb v1.0.2
go: downloading github.com/hashicorp/nomad/api v0.0.0-20191220223628-edc62acd919d
go: downloading gopkg.in/square/go-jose.v2 v2.5.1
go: downloading github.com/hashicorp/vault-plugin-database-elasticsearch v0.6.1
go: downloading github.com/hashicorp/go-uuid v1.0.2
go: downloading cloud.google.com/go v0.56.0
go: downloading github.com/hashicorp/vault/api v1.0.5-0.20201001211907-38d91b749c77
go: downloading github.com/hashicorp/vault-plugin-secrets-gcp v0.8.0
go: downloading github.com/hashicorp/vault-plugin-secrets-gcpkms v0.7.0
go: downloading github.com/hashicorp/consul-template v0.25.1
go: downloading github.com/hashicorp/go-immutable-radix v1.1.0
go: downloading github.com/hashicorp/vault-plugin-secrets-openldap v0.3.0
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading gopkg.in/ini.v1 v1.42.0
go: downloading github.com/hashicorp/go-raftchunking v0.6.3-0.20191002164813-7e9e8525653a
go: downloading github.com/hashicorp/go-hclog v0.14.1
go: downloading github.com/hashicorp/go-retryablehttp v0.6.7
go: downloading github.com/hashicorp/go-discover v0.0.0-20200812215701-c4b85f6ed31f
go: downloading github.com/hashicorp/go-rootcerts v1.0.2
go: downloading github.com/hashicorp/raft v1.1.3-0.20201002073007-f367681f9c48
go: downloading github.com/hashicorp/serf v0.8.3
go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
go: downloading github.com/hashicorp/go-plugin v1.0.1
go: downloading github.com/hashicorp/vault-plugin-secrets-kv v0.7.0
go: downloading github.com/hashicorp/logutils v1.0.0
go: downloading github.com/hashicorp/vault-plugin-auth-jwt v0.8.0
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/hashicorp/go-kms-wrapping/entropy v0.1.0
go: downloading github.com/hashicorp/raft-snapshot v1.0.3
go: downloading github.com/hashicorp/vic v1.5.1-0.20190403131502-bbfe86ec9443
go: downloading github.com/hashicorp/go-msgpack v0.5.5
go: downloading github.com/hashicorp/yamux v0.0.0-20181012175058-2f1d1f20f75d
go: downloading github.com/hashicorp/mdns v1.0.1
go: downloading gopkg.in/resty.v1 v1.12.0
go: downloading cloud.google.com/go/storage v1.6.0
go: downloading cloud.google.com/go/spanner v1.5.1
# github.com/hashicorp/vault/command
../../../go/pkg/mod/github.com/hashicorp/vault@v1.6.0/command/operator_raft_join.go:189:10: joinReq.AutoJoin undefined (type *"github.com/hashicorp/vault/api".RaftJoinRequest has no field or method AutoJoin)
../../../go/pkg/mod/github.com/hashicorp/vault@v1.6.0/command/operator_raft_join.go:190:10: joinReq.AutoJoinScheme undefined (type *"github.com/hashicorp/vault/api".RaftJoinRequest has no field or method AutoJoinScheme)
../../../go/pkg/mod/github.com/hashicorp/vault@v1.6.0/command/operator_raft_join.go:191:10: joinReq.AutoJoinPort undefined (type *"github.com/hashicorp/vault/api".RaftJoinRequest has no field or method AutoJoinPort)

**Comment by aphorise** [comment]
@wheiderman - I believe something specific to your setup like for example the Go vesrion and or the dependencies being pulled or maybe OS?

1. Have you attempted any other OS or version of Go?
2. Have you also attempted `-u / -f` options related to the `go get`?
  Those flags can help to reverify what's pulled in and their versions.

I dont see any issue when for example using the setup below (with complete Arch & OS details):

```bash
uname -pisorv && go version && lscpu ;
  # Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) unknown unknown GNU/Linux
  # 
  # go version go1.15.5 linux/amd64
  # 
  # Architecture:        x86_64
  # CPU op-mode(s):      32-bit, 64-bit
  # Byte Order:          Little Endian
  # Address sizes:       39 bits physical, 48 bits virtual
  # CPU(s):              1
  # On-line CPU(s) list: 0
  # Thread(s) per core:  1
  # Core(s) per socket:  1
  # Socket(s):           1
  # # // ...

go get github.com/hashicorp/vault ;

go/bin/vault  --version ;
  # Vault v1.6.0-dev (cgo)
```

**Comment by swayne275** [comment]
I'm closing this issue since it's been waiting for response for over a month
