### ISSUE TITLE
Cannot View Version History of Secret in Web UI When There is Whitespace in the Path

### ISSUE THREAD

**Issue by andrew0wells** [hashicorp/vault#10418]
**Describe the bug**
Version history web page displays error message "Unable to find secret at /. Try going back to the root and navigating from there." when the path for this secret contains a whitespace character.

**To Reproduce**
1. Create a secret with white in the path to the secret. via the web interface (IE "Test Problem")
2. Click the History button
3. Click "View version history" from the drop-down menu
4. Error message "Unable to find secret at /. Try going back to the root and navigating from there." is displayed.

**Expected behavior**
Version history should display in the web UI regardless of whether there is a whitespace character in the path. 

**Environment:**
* Vault Server Version (retrieve with `vault status`): 

```hcl
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       5
Version         1.6.0
Storage Type    file
Cluster Name    vault-cluster-1593d935
Cluster ID      66d79008-fb4f-0ee7-5ac6-4a0187233b6f
HA Enabled      false
```

* Vault CLI Version (retrieve with `vault version`): Vault v1.6.0 (7ce0bd9691998e0443bc77e98b1e2a4ab1e965d4)

* Server Operating System/Architecture:  
```hcl
Get-ComputerInfo | Select-Object OsName, OsVersion

OsName                                 OsVersion 
------                                 --------- 
Microsoft Windows Server 2019 Standard 10.0.17763
```

Vault server configuration file(s):

```hcl
storage "file" {
  path    = "<storage location>"
}


listener "tcp" {
address = "<IP>:8200"
tls_cert_file = "<cert file location>"
tls_key_file  = "<key file location>"
tls_disable_client_certs = "false"
}

api_addr = "https://<IP>:8200"
cluster_addr = "https://<IP>:8201"
ui = true
```

**Additional context**
Google Chrome displays the following error message in the Chrome console when then error message "Unable to find secret at /. Try going back to the root and navigating from there." displays:

```hcl
vendor-b965e34fb26c54d097fa32549a3d857a.js:2121 Error while processing route: vault.cluster.secrets.backend.versions Ember Data Request GET /v1/andrew.wells/metadata/Test%2520Problem returned a 404
Payload (application/json)
[object Object] Error: Ember Data Request GET /v1/andrew.wells/metadata/Test%2520Problem returned a 404
Payload (application/json)
[object Object]
    at n.se (https://<IP>:8200/ui/assets/vendor-b965e34fb26c54d097fa32549a3d857a.js:8945:19)
    at new n (https://<IP>:8200/ui/assets/vendor-b965e34fb26c54d097fa32549a3d857a.js:8947:56)
    at n.handleResponse (https://<IP>:8200/ui/assets/vendor-b965e34fb26c54d097fa32549a3d857a.js:9380:17)
    at n.handleResponse (https://<IP>:8200/ui/assets/vault-d9440ad6d1d15fadae0f358def87da57.js:14:243)
    at n [as handleResponse] (https://<IP>:8200/ui/assets/vendor-b965e34fb26c54d097fa32549a3d857a.js:2457:9)
    at n.ajaxError (https://<IP>:8200/ui/assets/vendor-b965e34fb26c54d097fa32549a3d857a.js:9680:10)
    at https://<IP>:8200/ui/assets/vendor-b965e34fb26c54d097fa32549a3d857a.js:9677:9
```
I believe the problem lies in the URL that's being used to access the metadata: /v1/andrew.wells/metadata/**Test%2520Problem** It should be encoded as Test%20Problem, but the web code appears to be encoding the % in "%20", which produces "Test%2520".

Accessing the path with whitespace works fine via a REST call: 
```hcl
$header = @{"X-Vault-Token" = "<Token>"}
Invoke-RestMethod -Uri "https://<IP>:8200/v1/andrew.wells/metadata/Test%20Problem" -Headers $header -Method GET
```

**Comment by swayne275** [comment]
Thanks for the details! I'll bring it up with my team!
