### ISSUE TITLE
"Notify" backend: per-user non-blocking notifications of access

### ISSUE THREAD

**Issue by autocracy** [hashicorp/vault#1041]
Permit a user to attach a backend that records the time, accessed secret, and a monotonic counter and sends it through a handler. Initial thought is that I'd like to map access to all vault transactions via my credential to notify my cell phone.

This is separate from audit logging in that it doesn't record the full transaction, shouldn't be blocking, and shouldn't substitute for any other audit backends.

**Comment by jefferai** [comment]
This is something that might be possible with some enhancements we're planning to the Vault core and base layers, but isn't actually possible right now. I'm slotting it into the future milestone to reevaluate as things change internally. Thanks for the suggestion!

**Comment by jefferai** [comment]
This is pretty trivially handled with anything consuming audit logs, so closing as we don't plan to implement it.
