### ISSUE TITLE
Vault data write API with postgres DB not working 

### ISSUE THREAD

**Issue by gauravdeshmukh612** [hashicorp/vault#10419]
We configure vault with storage as postgres, we use following API should to store our data in vaulthttp://127.0.0.1:8200/v1/database/localdConfigata.

This gives 404 or not API defined 

Another question
We create one user using userpass auth method and added storage /secret engine as database. we are getting "permission Denied " when we are using user vault token in API

{
“errors”: [
“1 error occurred:\n\t* permission denied\n\n”
]
}

**Comment by gauravdeshmukh612** [comment]
It give following exception 

Error writing data to database/test/dev: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/test/dev
Code: 404. Errors:

* no handler for route 'database/test/dev'

**Comment by swayne275** [comment]
do the actions in question work for you using the CLI?

**Comment by gauravdeshmukh612** [comment]
no it is not working from CLI command like vault write command

**Comment by HridoyRoy** [comment]
Hi @gauravdeshmukh612 , no handler for route 'database/test/dev' means that no secret engine was mounted to this path. The `permissions denied` error occurs when the policy associated with a token does not allow for the token to access the path that is being accessed. In this case, the policy for the token generated via a Userpass auth needs access to the secret engine. 

I am going to close this issue, but please feel free to direct debugging and setup related questions to our [discussion forums](https://discuss.hashicorp.com/c/vault/30) . Thanks!
