### ISSUE TITLE
Unable to renew ldap backend token

### ISSUE THREAD

**Issue by driskell** [hashicorp/vault#10412]
**Describe the bug**
After authenticating using vault login -method=ldap, the token cannot be renewed even though vault token lookup states it is renewable.

**To Reproduce**
1. Setup a LDAP backend using Authenticated Search
2. Run vault login -method=ldap username=testuser
3. Run vault token lookup. Note renewable.
4. Run vault token renew. See an error: failed to bind as user

**Expected behavior**
Token renewal to occur

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.6.0
* Vault CLI Version (retrieve with `vault version`): Vault v1.6.0 ('7ce0bd9691998e0443bc77e98b1e2a4ab1e965d4+CHANGES')
* Server Operating System/Architecture: CentOS 7 3.10.0-1127.19.1.el7.x86_64

Vault server configuration file(s):
If needed can try to make concise

**Additional context**
I can see logs in Directory Service (386ds - part of FreeIPA):

```
conn=225516 op=0 BIND dn="uid=vault,cn=users,cn=accounts,dc=local,dc=testdomain,dc=com" method=128 version=3
conn=225516 op=0 RESULT err=0 tag=97 nentries=0 etime=0.004230674 dn="uid=vault,cn=users,cn=accounts,dc=local,dc=testdomain,dc=com"
conn=225516 op=1 SRCH base="cn=users,cn=accounts,dc=local,dc=testdomain,dc=com" scope=2 filter="(uid=testuser)" attrs=ALL
conn=225516 op=1 RESULT err=0 tag=101 nentries=1 etime=0.003682120
conn=225516 op=2 BIND dn="uid=testuser,cn=users,cn=accounts,dc=local,dc=testdomain,dc=com" method=128 version=3
conn=225516 op=2 RESULT err=49 tag=97 nentries=0 etime=0.000938243
```

It appears to do authenticated bind to search for the user. Then it attempts to bind as that user and gets LDAP err 49 Invalid Credentials - but it's a renewal so unless the token renewal can ask for authentication again I don't see how that could work (and in fact may as well re-login.)

**Comment by johnnybubonic** [comment]
@driskell I was running into this too (on `1.6.3`) until I forgot I didn't set `token_period`. Do you have [`token_period`](https://www.vaultproject.io/api-docs/auth/ldap#parameters) set on your LDAP mount? You won't be able to renew past the `creation_ttl` if not, from my understanding. I'm about to confirm this.

The documentation unfortunately is a bit lacking on this point as it's only mentioned once or twice in other places throughout.

**Comment by aphorise** [comment]
Hey @driskell did you test the suggestion regarding `token_period` perhaps also using a more recent versions of Vault or is this still relevant for you?

**Comment by aphorise** [comment]
Closing due to no follow up. Kindly re-open if applicable again.
