### ISSUE TITLE
After `setcap cap_ipc_lock`, getting `Operation not permitted`

### ISSUE THREAD

**Issue by thalesfsp** [hashicorp/vault#1042]
Following recommendations [here](https://www.vaultproject.io/docs/config/):

"In production, you should only consider setting the disable_mlock option on Linux systems that only use encrypted swap or do not use swap at all. Vault does not currently support memory locking on Mac OS X and Windows and so the feature is automatically disabled on those platforms. To give the Vault executable access to the mlock syscall on Linux systems"

I'm doing `sudo setcap cap_ipc_lock=+ep $(readlink -f $(which vault))` and after that, when I try to call `vault`, I get:

```bash
root@714f0d1236a0:/# vault
bash: /usr/local/bin/vault: Operation not permitted
```

PS: Running inside docker, Ubuntu 14.04

Thanks!

**Comment by jefferai** [comment]
Hi there,

I don't know if this is supported inside Docker or what the runtime requirements are to give the correct permissions.

**Comment by jefferai** [comment]
Looks like #121 should help you out!

**Comment by thalesfsp** [comment]
Tkx!
