### ISSUE TITLE
Provide a way to install vault injector without Helm installer either by documenting or by providing yaml files/ kustomize etc

### ISSUE THREAD

**Issue by fernando-villalba** [hashicorp/vault#10439]
It looks as if all the documentation assumes that to use the vault injector, you are going to install vault in the cluster you are using it with Helm. I see two issues with this approach:

1. You may not want to use Helm at all (I don't)
2. The documentation seems to assume you are going to be using vault and the injector in the same cluster and that you want to install both. This is contradictory because in other parts of the documentation I have seen recommending not to install vault in the same cluster where you are going to be using it for additional security and resilience.

I have vault installed already on a separate cluster (not kubernetes) and I just want to be able to install and configure the injector and nothing else in the target kubernetes cluster where I want to enable the auth, and ideally do it without Helm. I know it is possible for me to do this myself by digging through the Helm templates and others, but it would be very helpful to document and provide a solution for this possibility.

If there is already documentation somewhere or I am somehow misunderstanding the ideal use case of the injector, feel free to add a note and close this.

**Comment by fernando-villalba** [comment]
I found [this](https://github.com/hashicorp/vault-k8s/tree/master/deploy) hidden away.

@jasonodonnell thank you for this. Is there any reason why this is not part of the official documentation? I think it would be very helpful to explain how to do this without doing the entire helm deployment and assuming we want everything in the same cluster.

**Comment by hsimon-hashicorp** [comment]
Hello, is this still an issue with newer versions of Vault? Please let me know if you still think a docs update is needed and I'll add that to the queue. Thanks!

**Comment by raskchanky** [comment]
Since it's been awhile with no response, I'm going to close this issue. Please reopen if there's more to add here.
