### ISSUE TITLE
Support for delegating granting per policy/role

### ISSUE THREAD

**Issue by sigmunau** [hashicorp/vault#1043]
In our company we have several applications/services with different teams responsible for each. I would like to be able to have different policies defined for each application and then delegate to the representatives of that application the ability to give that policy to a newly created node. None of the auth backends allows this currently as far as I can figure out. To solve this the following commands could be added:

certs backend: 
`vault write auth/cert/roles/myrole/config policies=app1,app2`
`vault write auth/cert/roles/myrole/certs/web display_name=web certificate=@web.pem`

app-id backend:
`vault write auth/app-id/members/foo/bar cidr_block=10.0.0.0/16`
This adds user-id bar to app-id foo

ldap backend:
`vault write auth/ldap/group-members/engineers/tesla`
This adds user `tesla` to the group `engineers`

This allows for a cleaner separation between authentication and authorization. It would also allow for easier changing of user rights ref #909. It would allow workflows where config management or virtualization systems provides newly created nodes with a "user" that exists in vault but has little or no access, and then the responsible person for a given app can verify the node and give it permissions for his or her app.

As a bonus feature, this could allow us to trust a CA certificate and grant different policies to different certificates issued by that CA based on CN or serial, but that might be a different ticket altogether.

**Comment by kaelumania** [comment]
this would be awesome

**Comment by jefferai** [comment]
Delegation has been on our radar for a while, but I must admit, I don't really understand the initial ask here. You can already use ACLs to grant access to paths, and give policies in accordance. Can you explain where this is breaking down for you?

**Comment by sigmunau** [comment]
The simples possible case: You have one organization with two applications. And different teams behind each application. Using app-id as authentication mechanism. Team A wants to put a new worker node in their application. To do this they need to run something like: `vault write auth/app-id/map/user-id/newnode value=Aapp`. To do this they need to have write access to `auth/app-id/map/user-id/*` probably, and they could then easily put their node into Bapp in stead. By including the app-id in the path used when creating the mapping between an app-id and a user-id you could give members of team A  the possibility to assign new nodes to their app without having the possibility to clutter with team Bs app and vica versa.

**Comment by jefferai** [comment]
@sigmunau I think that's a fine case of a useful enhancement...I think my disconnect here is that I don't think of that as delegation so much as adding extra paths to allow ACL policies to control this functionality (although unfortunately the design of the app-id backend somewhat makes it difficult to actually implement this).

**Comment by sigmunau** [comment]
Ok. Glad we cleared that up. I'm not a native english speaker, nor that into the security jargon, so I might have used the wrong term.

**Comment by sigmunau** [comment]
I see 0.5.2 comes with a role consept that solves this for me using the token auth backend. Still missing for app-id

**Comment by tasdienes** [comment]
Similar request: https://groups.google.com/forum/#!topic/vault-tool/lqLgiBV5dd0

**Comment by jefferai** [comment]
App-ID has been deprecated for quite a while and is no longer supported, so using the token store roles may be your best bet.
