### ISSUE TITLE
Write only access

### ISSUE THREAD

**Issue by sigmunau** [hashicorp/vault#1044]
Our virtualization platform allows setting the root password when creating a new VM. It would be nice to have the frontend of that platform auto-generate a password and store it in vault when a VM is created, but I do not want the frontend to have credentials to read all our VMs' root passwords. If I could create a token that could write, but not read a given namespace the worst case scenario caused by a breaking of the frontend app would be that it could overwrite our stored version of the passwords. Even better would be if I could create a token that could write entries within a path only if they did not already exist

**Comment by jefferai** [comment]
Write only access is coming in 0.5, out *very* soon!
