### ISSUE TITLE
Vault 1.6 UI Secrets/AuthMethod visual selector bug

### ISSUE THREAD

**Issue by krastin** [hashicorp/vault#10459]
**Describe the bug**
It seems that on Vault v.1.6, when adding a Secrets engine or an Auth Method, clicking exactly on the radio button will not select the item. Clicking on the Logo or Text, however, will select it. Visually, the green area works, while the red one does not. Both Chrome and Firefox seem to be affected from my testing.
<img width="629" alt="ui_bug" src="https://user-images.githubusercontent.com/1161924/100359777-50449980-2ff8-11eb-884d-2f9cae44fb0e.png">

**To Reproduce**
1. Run `vault server -dev` for version 1.6
2. Open up the Vault UI
3. Try to add a new secrets engine or an auth method and click specifically the radio button of your selection

**Expected behavior**
The item's radio button should become selected

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.6.0 and 1.6.0+ent
* Vault CLI Version (retrieve with `vault version`): 1.6.0 and 1.6.0+ent
* Vault UI Browser : Firefox / Chrome
* Server Operating System/Architecture: Ubuntu 18.04

Vault server configuration file(s): running in development mode, as well as the following
```hcl
storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault"
}

listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = true
}

ui = true
```

**Additional context**
Not an issue with v.1.5.5

**Comment by aphorise** [comment]
Hey @krastin thanks for reporting this which has since been resolved.
