### ISSUE TITLE
Issues with nomad secret engine with tls

### ISSUE THREAD

**Issue by Oloremo** [hashicorp/vault#10462]
Hi!

I deployed Nomad with self-signed certs from Vault PKI. Now I'm trying to enable nomad secret engine and read from `nomad/creds/operator` got the:
```
Put "https://localhost:4646/v1/acl/token": x509: certificate signed by unknown authority
```
Looks like Vault supports setting a TLS configuration for Nomad secret engine since https://github.com/hashicorp/vault/pull/8083

Ok so I updated my nomad secrets engine configuration:
```
vault write nomad/config/access address="https://localhost:4646" token="REDACTED" ca_cert='/opt/nomad/tls/ca.crt' client_cert='/opt/nomad/tls/cli.crt' client_key='/opt/nomad/tls/cli.key'
```
And now I get the:
```
$ vault read nomad/creds/operator
Error reading nomad/creds/operator: Error making API request.

URL: GET https://127.0.0.1:8200/v1/nomad/creds/operator
Code: 500. Errors:

* 1 error occurred:
	* tls: failed to find any PEM data in certificate input
```

Paths are correct, files are present and contain valid cert, key and CA.
Any ideas what is wrong?

Vault version: v1.5.4
Nomad version: 1.0.0-beta3

P.S. It would be nice to print tls configuration info in `nomad/config/access`. Currently, it only shows the `address` and `max_token_name_length`

**Comment by Oloremo** [comment]
Ok so the issue was the fact that those arguments expect not the path but the cert itself.

I'd suggest updating https://www.vaultproject.io/docs/secrets/nomad to cover this case.

**Comment by swayne275** [comment]
Thanks for the info! I've labeled it so our docs team can take a look.

**Comment by Oloremo** [comment]
Also, it's absolutely not clear how to monitor that certificate, so it's "uploaded" into Vault, how can I check its expiration time or anything?

**Comment by Oloremo** [comment]
Created a separate issue about certificates monitoring and maintenance: https://github.com/hashicorp/vault/issues/10628

**Comment by adeleglise** [comment]
> Ok so the issue was the fact that those arguments expect not the path but the cert itself.
> 
> I'd suggest updating https://www.vaultproject.io/docs/secrets/nomad to cover this case.

Hi, sorry for the grave digging, but I'm in the same configuration and I can't get how to "upload" the ca_cert to the nomad backend configuration. As it's not trivial to use the pki backend for this configuration, I'm using cfssl to generate cert. The cert is in x509 format but Vault still complains about the format :
```
Code: 500. Errors:

* 1 error occurred:
	* Error appending CA: Couldn't parse PEM
```
Any idea how to fix this ? Is there a good doc around using the pki backend to serve consul and nomad TLS ?

**Comment by Oloremo** [comment]
@adeleglise Hey, in my case I had to replace still like 
```
vault write nomad/config/access address="https://localhost:4646" token="REDACTED" ca_cert='/opt/nomad/tls/ca.crt' client_cert='/opt/nomad/tls/cli.crt' client_key='/opt/nomad/tls/cli.key'
```
to the
```
vault write nomad/config/access address="https://localhost:4646" token="REDACTED" ca_cert='@/opt/nomad/tls/ca.crt' client_cert='@/opt/nomad/tls/cli.crt' client_key='@/opt/nomad/tls/cli.key'
```
So from paths to the files to the content of the files via `@`

**Comment by adeleglise** [comment]
It works ! Thanks a lot @Oloremo

**Comment by tomiles** [comment]
We generate our client cert/key for nomad with vault pki and use consul-template to write them out to files.
How can I trigger Nomad's vault secret engine config to update when these are rotated? 
Is there a handier way than making _consul-template_ run the `vault write nomad/config/access` with the new values? maybe allowing us to set cert/key paths instead of content and send a SIGHUP to vault to reload from the file?

**Comment by cipherboy** [comment]
@Oloremo said:
> Ok so the issue was the fact that those arguments expect not the path but the cert itself.
> 
> I'd suggest updating https://www.vaultproject.io/docs/secrets/nomad to cover this case.

Per comment above, and seeing as [the parameter](https://www.vaultproject.io/api-docs/secret/nomad#ca_cert) mentions being a PEM encoded certificate (and not a path), going ahead and closing this as solved :-) 

@tomiles said:
> We generate our client cert/key for nomad with vault pki and use consul-template to write them out to files. How can I trigger Nomad's vault secret engine config to update when these are rotated? Is there a handier way than making _consul-template_ run the `vault write nomad/config/access` with the new values? maybe allowing us to set cert/key paths instead of content and send a SIGHUP to vault to reload from the file?

I believe that'd best be a separate issue. I believe the write you mentioned is the correct way of doing things though.
