### ISSUE TITLE
vault starts in standby mode with s3 backend after old instance terminated

### ISSUE THREAD

**Issue by cludden** [hashicorp/vault#1048]
Had a vault server running on an AWS EC2 instance with s3 backend. The instance was terminated, a new instance was launched with same settings, however it starts in standby mode and I am not sure how to resolve.

Issuing a GET to /v1/sys/health returns:
```json
{
  "initialized": true,
  "sealed": true,
  "standby": true
}
```
Any ideas?

**Comment by jefferai** [comment]
A sealed Vault cannot be an active node, so simply unseal it and you should be good to go.

As a separate comment, are you using a separate HA backend? `standby: true` is a bit odd there; for instance, on a dev instance, after sealing Vault I get:
```
{"initialized":true,"sealed":true,"standby":false}
```

**Comment by cludden** [comment]
When I try to unseal it, it says the keys don't work. When I check the leader status:
```json
{
  "ha_enabled": false,
  "is_self": false,
  "leader_address": ""
}
```

**Comment by jefferai** [comment]
Please post your config and log output from the beginning through the unseal attempts -- it's hard to know what's going on without more context.

Thanks!

**Comment by cludden** [comment]
So, I killed that instance, launched a new one, and was able to unseal it, everything seems to functioning normally. Not sure what happened, but closing for now. Thanks for the quick response!

**Comment by jefferai** [comment]
Very strange, please do let us know if it happens again!
