### ISSUE TITLE
When the next github.com/hashicorp/vault/api version release?

### ISSUE THREAD

**Issue by hiyosi** [hashicorp/vault#10490]
**Is your feature request related to a problem? Please describe.**

The latest `github.com/hashicorp/vault/api` v1.0.4 doesn't have `api.LifetimeWatcher`.
I'd like to use api.LifetimeWatcher in an external package that uses the vault api to improve the handling of renew tokens.

**Describe the solution you'd like**

The new version of  `github.com/hashicorp/vault/api` is released and it inclues `LifetimeWatcher`
Do you have any plan to release the next api version?

**Describe alternatives you've considered**

**Explain any additional use-cases**

**Additional context**

**Comment by rgl** [comment]
any news about this? :-)

**Comment by HridoyRoy** [comment]
Hello everyone,
Currently we do not have an established release cycle for the vault api and sdk packages. However as a temporary workaround, you should be able to pin to a commit or branch so as to only pull in the changes you want.

**Comment by HridoyRoy** [comment]
Hi @rgl , does the above workaround provides a working solution?

**Comment by rgl** [comment]
@HridoyRoy , using something like `go get github.com/hashicorp/vault/api@371fbb8614e858161b0a38144bc40020a1076e08`?

**Comment by hiyosi** [comment]
@HridoyRoy I understand that there is a workaround as above, but I would like to use the release version if possible.

**Comment by hiyosi** [comment]
v1.1.x has been released. Thank you!
