### ISSUE TITLE
Okta as an authentication backend

### ISSUE THREAD

**Issue by shpsec-dennis** [hashicorp/vault#1049]
Similar to https://github.com/hashicorp/vault/issues/571 this a feature request to have an Okta authentication backend.

**Comment by radeksimko** [comment]
Isn't this covered in https://github.com/hashicorp/vault/issues/370 since Okta provides a SAML-based auth?

**Comment by shpsec-dennis** [comment]
It looks like it, though #370 it seems much more general. 

Providing Google Apps and Okta SSO would be a great start and the aim for this FR.

**Comment by stephansnyt** [comment]
https://techcrunch.com/2016/08/30/okta-extends-identity-management-to-apis/

Is this news relevant to this issue?

**Comment by sstarcher** [comment]
Would hashicorp be interested in an implementation that specifically supports the Okta API mentioned by @stephansnyt

**Comment by jefferai** [comment]
Hi @sstarcher ,

We're interested, for sure, but it will depend on the exact mechanism. The TechCrunch article mentions that it uses OAuth 2.0, which is a very difficult workflow for a Vault backend, but in looking at their documentation it *seems* like the actual API that would be used is http://developer.okta.com/docs/api/resources/authn.html which is fully JSON-driven and doesn't appear to require a browser.

**Comment by sstarcher** [comment]
@jefferai ya I mistakenly mentioned that article prior to actually reading it.  You are correct on your link in their docs that they have full api support without opening a browser.

**Comment by sstarcher** [comment]
How about taking the path of least resistance and following the example of the LDAP auth.

`vault auth -method=okta username=mitchellh`
`vault write auth/okta/users/mitchellh policies=foo,bar`
