### ISSUE TITLE
Display actual raft status

### ISSUE THREAD

**Issue by squaricdot** [hashicorp/vault#10496]
When checking vault operator raft list-peers or ui

it doesn't show the actual state of the peer whether it's available or not.

Please provide an actual valid member state.

**Comment by swayne275** [comment]
Which version of Vault? Can you provide more information about your configuration?

**Comment by swayne275** [comment]
Is your issue at all related to this discussion on our forum: https://discuss.hashicorp.com/t/vault-operator-raft-join-seems-to-work-but-operator-raft-list-peers-shows-only-leader/8617

**Comment by swayne275** [comment]
Closing because this issue has been without update for 30+ days. Please re-open if it hasn't been resolved.

**Comment by squaricdot** [comment]
Sorry @swayne275 for not replying on short notice.

I mean when either checking

$ vault operator raft list-peers
Node                                    Address               State       Voter
----                                    -------               -----       -----
aa1e3fa6-280c-68b8-2381-3be10c005da0    172.21.19.241:8201    leader      true
a2dfe732-3d77-8dc3-f384-618b73d72186    172.21.6.241:8201     follower    true
9245dd26-1eec-66e7-3f57-ce3a0782aafc    172.21.6.242:8201     follower    true

or checking https://vault/ui/vault/storage/raft
