### ISSUE TITLE
Fails to read binary data from field

### ISSUE THREAD

**Issue by corvax19** [hashicorp/vault#1050]
Hi,

Can anyone from DEVs/OWNERs confirm that Vault is not handling binary data in fields?
If it DOES, what's wrong with following?
```
[vault@box ~]$ dd if=/dev/random of=./my.file bs=1 count=128
128+0 records in
128+0 records out
128 bytes (128 B) copied, 4.74832 s, 0.0 kB/s
[vault@box ~]$ vault write test/my.file file_data=@./my.file
Success! Data written to: test/my.file
[vault@box ~]$ vault read -format=binary -field=file_data test/my.file > my.file.from.Vault
[vault@box ~]$ ll my.file*
-rw-rw-r-- 1 vault vault 128 Feb 10 12:00 my.file
-rw-rw-r-- 1 vault vault 240 Feb 10 12:01 my.file.from.Vault
[vault@box ~]$ md5sum ./my.file
dba46e84d8b9fef3ac1cc9555c79b5a3  ./my.file
[vault@box ~]$ md5sum ./my.file.from.Vault 
129f86158f92119a2d86deb398852917  ./my.file.from.Vault
```

Thanks in advance!

Regards
/Romans

**Comment by jefferai** [comment]
Hi,

Vault's API is JSON based and as such binary values cannot be represented properly without encoding. You are most likely hitting an artifact of the Golang JSON library not bailing on the data you're trying to send in but not putting in what you expect either.

See the last few comments in #205 for examples of how to store binary data in Vault via the CLI...they should be exactly what you need!
