### ISSUE TITLE
After successful login, other CLI requests freeze.

### ISSUE THREAD

**Issue by queglay** [hashicorp/vault#10507]
**Describe the bug**
I've been using vault 1.5.5 fine for most of the day, and then just now after successful logins, requests just freeze.  I'm unsure how easy this will be to reproduce after I redeploy the HA servers in AWS to get at the data in the s3 backend, I'm sure it will be fine after I do that, but this behaviour is concerning.

**To Reproduce**
1. Run `vault login`.  this will succeed.
2. Run `vault status`.  it will freeze forever.  so will any vault kv list command.

**Expected behavior**
No freezing.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.5.5
* Vault CLI Version (retrieve with `vault version`): 1.5.5
* Server Operating System/Architecture: Amazon Linux 2

**Comment by aphorise** [comment]
I believe this is likely to have been specific to the OS setup or environment especially if network appliances (LB's / Proxies) were in use.

@Hey @queglay - I'm curious if you've re-attempted your mock / tests perhaps using a more recent version (1.11.3) of Vault and how relevant this issue might be still?

**Comment by aphorise** [comment]
Closing as there's been no follow-up. Please re-open if still relevant.
