### ISSUE TITLE
`vault token create -ttl` creates a periodic token

### ISSUE THREAD

**Issue by phemmer** [hashicorp/vault#10508]
**Describe the bug**
Passing the `-ttl` parameter to `vault token create` creates a periodic token while the documentation states this should not happen.

**To Reproduce**
```
/ # vault token create -policy default -ttl 1h
Key                  Value
---                  -----
token                s.fpeT5mtUcc3FvosFZk6t75p5
token_accessor       khQ80cE6p2U8qfQEei5cJ71P
token_duration       1h
token_renewable      true
token_policies       ["default"]
identity_policies    []
policies             ["default"]

/ # vault token lookup s.fpeT5mtUcc3FvosFZk6t75p5
Key                 Value
---                 -----
accessor            khQ80cE6p2U8qfQEei5cJ71P
creation_time       1607357641
creation_ttl        1h
display_name        token
entity_id           n/a
expire_time         2020-12-07T17:14:01.088614596Z
explicit_max_ttl    0s
id                  s.fpeT5mtUcc3FvosFZk6t75p5
issue_time          2020-12-07T16:14:01.088620166Z
meta                <nil>
num_uses            0
orphan              false
path                auth/token/create
policies            [default]
renewable           true
ttl                 59m54s
type                service

/ # vault token renew s.fpeT5mtUcc3FvosFZk6t75p5
Key                  Value
---                  -----
token                s.fpeT5mtUcc3FvosFZk6t75p5
token_accessor       khQ80cE6p2U8qfQEei5cJ71P
token_duration       1h
token_renewable      true
token_policies       ["default"]
identity_policies    []
policies             ["default"]

/ # vault token lookup s.fpeT5mtUcc3FvosFZk6t75p5
Key                  Value
---                  -----
accessor             khQ80cE6p2U8qfQEei5cJ71P
creation_time        1607357641
creation_ttl         1h
display_name         token
entity_id            n/a
expire_time          2020-12-07T17:14:10.05374318Z
explicit_max_ttl     0s
id                   s.fpeT5mtUcc3FvosFZk6t75p5
issue_time           2020-12-07T16:14:01.088620166Z
last_renewal         2020-12-07T16:14:10.05374326Z
last_renewal_time    1607357650
meta                 <nil>
num_uses             0
orphan               false
path                 auth/token/create
policies             [default]
renewable            true
ttl                  59m58s
type                 service
```
^ Note that `expire_time` increased after renewal.

**Expected behavior**
A non-periodic token with specified TTL should be created.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
/ # vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.6.0
Storage Type    inmem
Cluster Name    vault-cluster-d05d072b
Cluster ID      be4d8d3c-bb0a-3667-bf0f-d5da923a471a
HA Enabled      false
```
* Vault CLI Version (retrieve with `vault version`):
```
/ # vault version
Vault v1.6.0 (7ce0bd9691998e0443bc77e98b1e2a4ab1e965d4)
```
* Server Operating System/Architecture:
https://hub.docker.com/layers/vault/library/vault/1.6.0/images/sha256-f5e6af78549d376a2cb1ccedab8f16e0ce72ea40454ab45f488ce9bc280ecce2?context=explore

Vault server configuration file(s):

```hcl
```

**Additional context**
I'm not sure if this is a documentation issue, or a bug.

[The documentation](https://www.vaultproject.io/docs/concepts/tokens) states:
> In the general case, where there is neither a period nor explicit maximum TTL value set on the token, the token's lifetime since it was created will be compared to the maximum TTL.
> ...
> At issue time, the TTL of a periodic token will be equal to the configured period. At every renewal time, the TTL will be reset back to this configured period, and as long as the token is successfully renewed within each of these periods of time, it will never expire. Outside of root tokens, it is currently the only way for a token in Vault to have an unlimited lifetime.

This statement is obviously incorrect as period was not specified during token creation.

[API documentation](https://www.vaultproject.io/api-docs/auth/token):
> `ttl` `(string: "")` - The TTL period of the token, provided as "1h", where hour is the largest suffix. If not provided, the token is valid for the default lease TTL, or indefinitely if the root policy is used.
> `period` `(string: "")` - If specified, the token will be periodic; it will have no maximum TTL (unless an "explicit-max-ttl" is also set) but every renewal will use the given period. Requires a root token or one with the sudo capability.

Note that `period` clearly documents it will create a periodic token, while `ttl` does not mention anything of the sort.

**Comment by calvn** [comment]
The token that you created in your example is a renewable non-periodic token. Even though this is a renewable token, it is non-periodic in the sense that the renewal is capped to a max TTL value and cannot be renewed indefinitely. This value is may be determined from various places -- from the system, the backend, a token role, or a param during token creation (`explicit_max_ttl`). If you want to hard cap the TTL value, you can set `renewable` to false or `explicit_max_ttl` to be the same as your `ttl` value.

In your case, it looks like it's a simple token creation request so it will use the system's default value, which is 32 days, unless otherwise specified in the Vault config or tuned to a different value on the mount. You can check whether the token auth mount is using the system's default max TTL through `vault auth list --detailed`.

The response from a token lookup will look slightly different for a periodic token. More specifically, a `period` is returned as part of the payload/CLI output.

```
› vault token create -policy default -period 2h
Key                  Value
---                  -----
token                s.wVbeG31SMzkaRIa2zfc8Rl2T
token_accessor       4kWuISYKw0xqwO0EWVSH03iQ
token_duration       2h
token_renewable      true
token_policies       ["default"]
identity_policies    []
policies             ["default"]

› vault token lookup s.wVbeG31SMzkaRIa2zfc8Rl2T
Key                 Value
---                 -----
accessor            4kWuISYKw0xqwO0EWVSH03iQ
creation_time       1607387065
creation_ttl        2h
display_name        token
entity_id           n/a
expire_time         2020-12-07T18:24:25.089644-08:00
explicit_max_ttl    0s
id                  s.wVbeG31SMzkaRIa2zfc8Rl2T
issue_time          2020-12-07T16:24:25.089648-08:00
meta                <nil>
num_uses            0
orphan              false
path                auth/token/create
period              2h
policies            [default]
renewable           true
ttl                 1h59m52s
type                service
```

**Comment by phemmer** [comment]
> Even though this is a renewable token, it is non-periodic in the sense that the renewal is capped to a max TTL value and cannot be renewed indefinitely.

This would not appear to be the case. This issue arose after discovering a coworker created a token in this fashion approximately a year ago and has been renewing it ever since. 

```
# vault token lookup -accessor asdf
Key                  Value
---                  -----
accessor             asdf
creation_time        1581604637
creation_ttl         731h
display_name         token
entity_id            n/a
expire_time          2021-01-07T03:00:02.184274548Z
explicit_max_ttl     0s
id                   n/a
issue_time           2020-02-13T14:37:17.985926889Z
last_renewal         2020-12-07T16:00:02.184274697Z
last_renewal_time    1607356802
meta                 <nil>
num_uses             0
orphan               false
path                 auth/token/create/cdn_deploy
policies             [cdn_deploy default]
renewable            true
role                 cdn_deploy
ttl                  722h15m44s
type                 service

# vault auth list --detailed
Path      Plugin    Accessor               Default TTL    Max TTL    Token Type         Replication    Seal Wrap    External Entropy Access    Options    Description                UUID
----      ------    --------               -----------    -------    ----------         -----------    ---------    -----------------------    -------    -----------                ----
token/    token     auth_token_5ca589e6    system         system     default-service    replicated     false        false                      map[]      token based credentials    c37a0cd8-3932-69c8-582c-38c547f161b5

# grep max_lease_ttl /etc/vault/vault-server.json 
<empty>
```

**Comment by calvn** [comment]
It looks like this token was created through a token role called `cdn_deploy`. Can you read the role, `vault read /auth/token/roles/cdn_deploy`, and share that output here?

**Comment by phemmer** [comment]
Yes, that appears to be it. Did not notice that it was inheriting from a role. Apologies for the noise.

**Comment by calvn** [comment]
No problem, glad you got it sorted out!
