### ISSUE TITLE
auto_join (discover-aws) uses IP address and fails when SSL enabled

### ISSUE THREAD

**Issue by matt-slalom** [hashicorp/vault#10502]
**Describe the bug**
For the `discover-aws` provider, `auto_join` identifies the IP addresses of potential cluster nodes, but when it attempts to connect, it does so via the IP address. When TLS is enabled, the joining node cannot match the IP name to the SSL certificate unless subjectAltName (SAN) includes the IP address of the other node.

Manually connecting using the DNS name works (but defeats the purpose of `auto_join`).

A simple fix would seem to be performing a DNS lookup on the IP addresses in `discover-aws` for the discovered nodes and then using that to connect.
```
[root@vm3 config]# getent hosts 10.0.72.157
10.0.72.157     vm2.test.local
```

**To Reproduce**
1. Create SSL certificates for two Vault nodes, named vm2.test.local and vm3.test.local. Embed in the SAN `DNS:vm2.test.local,IP:127.0.0.1` or `DNS:vm3.test.local,IP:127.0.0.1`
2. Start Vault and unseal the leader node (vm2)
3. Start vm3 and the errors about SSL are in the log:

```
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.346Z [INFO]  core: [DEBUG] discover: Using provider "aws"
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.346Z [INFO]  core: [DEBUG] discover-aws: Using region=us-west-1 tag_key=Project tag_value=Vault addr_type=private_v4
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.346Z [INFO]  core: [DEBUG] discover-aws: No static credentials
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.346Z [INFO]  core: [DEBUG] discover-aws: Using environment variables, shared credentials or instance role
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.346Z [INFO]  core: [INFO] discover-aws: Region is us-west-1
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.346Z [INFO]  core: [DEBUG] discover-aws: Creating session...
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.346Z [INFO]  core: [INFO] discover-aws: Filter instances with Project=Vault
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.401Z [INFO]  core: [DEBUG] discover-aws: Found 3 reservations
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.401Z [INFO]  core: [DEBUG] discover-aws: Reservation r-00524d480552b6e6f has 1 instances
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.401Z [INFO]  core: [DEBUG] discover-aws: Found instance i-08cb787992f2b4246
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.401Z [INFO]  core: [INFO] discover-aws: Instance i-08cb787992f2b4246 has private ip 10.0.72.157
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.401Z [INFO]  core: [DEBUG] discover-aws: Reservation r-02bce70c1349c66f3 has 1 instances
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.401Z [INFO]  core: [DEBUG] discover-aws: Found instance i-03204bc58099a88a5
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.401Z [INFO]  core: [INFO] discover-aws: Instance i-03204bc58099a88a5 has private ip 10.0.44.77
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.401Z [INFO]  core: [DEBUG] discover-aws: Reservation r-02c2034a9a3d21961 has 1 instances
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.401Z [INFO]  core: [DEBUG] discover-aws: Found instance i-0fb4ad337f2f21abc
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.401Z [INFO]  core: [INFO] discover-aws: Instance i-0fb4ad337f2f21abc has private ip 10.0.4.210
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.401Z [INFO]  core: [DEBUG] discover-aws: Found ip addresses: [10.0.72.157 10.0.44.77 10.0.4.210]
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.402Z [INFO]  core: security barrier not initialized
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.402Z [INFO]  core: attempting to join possible raft leader node: leader_addr=https://10.0.72.157:8200
Dec  4 21:56:10 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:10.421Z [WARN]  core: join attempt failed: error="error during raft bootstrap init call: Put "https://10.0.72.157:8200/v1/sys/storage/raft/bootstrap/challenge": x509
: certificate is valid for 127.0.0.1, not 10.0.72.157"
```
4. Connect via DNS name (`vault operator raft join https://vm2.test.local:8200`) and the node now successfully joins the cluster
```
Dec  4 21:56:11 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:11.023Z [INFO]  core: attempting to join possible raft leader node: leader_addr=https://vm2.test.local:8200
Dec  4 21:56:11 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:11.129Z [INFO]  core.cluster-listener.tcp: starting listener: listener_address=0.0.0.0:8201
Dec  4 21:56:11 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:11.129Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=[::]:8201
Dec  4 21:56:11 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:11.134Z [INFO]  storage.raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:raft-node-19351 Address:vm2.test.local:8201} {Suffrage:Voter ID:raft-node-3
0284 Address:vm3.test.local:8201}]"
Dec  4 21:56:11 ip-10-0-4-210 vault[53626]: 2020-12-04T21:56:11.134Z [INFO]  core: successfully joined the raft cluster: leader_addr=https://vm2.test.local:8200
```

**Expected behavior**
I expected `auto_join` on the follower to successfully join the leader.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.6.0
* Vault CLI Version (retrieve with `vault version`): Vault v1.6.0 (7ce0bd9691998e0443bc77e98b1e2a4ab1e965d4)
* Server Operating System/Architecture: centos 8

Vault server configuration file(s):

```hcl
cluster_name = "temp"
api_addr = "https://127.0.0.1:8200"
# Try setting api_addr to https://vm3.test.local:8201
cluster_addr = "https://vm3.test.local:8201"

listener "tcp" {
  address                  = "0.0.0.0:8200"
  cluster_address          = "0.0.0.0:8201"
  tls_disable              = "false"
  tls_disable_client_certs = "false"
  tls_cert_file   = "/opt/vault/tls/cert.crt"
  tls_key_file    = "/opt/vault/tls/privkey.key"
}
storage "raft" {
  path       = "/opt/vault/data"
  node_id      = "raft-node-30284"
  retry_join {
      auto_join = "provider=aws addr_type=private_v4 tag_key=Project tag_value=Vault region=us-west-1"
      auto_join_scheme = "https"
  }
}
seal "awskms" {
  region     = "us-west-1"
  kms_key_id = "arn:aws:kms:us-west-1:XXXXXXXXXXXX:alias/vault"
}
ui       = true  

```

**Additional context**
Some discussion here: https://discuss.hashicorp.com/t/ip-subjectaltname-makes-cloud-use-really-difficult/18477/8

**Comment by bortzvk** [comment]
We have 100% the same issue as you described, now the question is how to solve it. We have couple of ideas on our own, but all of them are crutches and won't actually solve the issue, but just quick-fix to move on, just a temporary solutions. Is there anyone who is going to look at it and suggest something?

**Comment by mgriffin13** [comment]
I worked through Hashicorp support regarding this issue, and the solution we came to wasn't perfect, but it was workable (for me).

1. Use vault-issued PKI certificates that include the IP SAN and are automatically issued when a new instance comes online
2. Create a second TCP listener in vault that uses the second certificate, kinda like a "side-door"
3. Configure the cluster api to use this second listener

Something like this

```
cluster_name = "temp"
api_addr = "https://127.0.0.1:8100"
cluster_addr = "https://127.0.0.1:8101"

listener "tcp" {
  address                  = "0.0.0.0:8200"
  cluster_address          = "0.0.0.0:8201"
  tls_disable              = "false"
  tls_disable_client_certs = "false"
  tls_cert_file   = "/opt/vault/tls/cert.crt"
  tls_key_file    = "/opt/vault/tls/privkey.key"
}

listener "tcp" {
  address = "0.0.0.0:8100"
  tls_cert_file = "/opt/vault/tls/vault-issued-cert.crt"
  tls_key_file = "/opt/vault/tls/vault-issued-key.crt"
}

storage "raft" {
  path       = "/opt/vault/data"
  node_id      = "raft-node-30284"
  retry_join {
      auto_join = "provider=aws addr_type=private_v4 tag_key=Project tag_value=Vault region=us-west-1"
      auto_join_scheme = "https"
      auto_join_port = 8100
      leader_ca_cert_file = "/opt/vault/tls/vault-issued-ca.crt"
  }
}
seal "awskms" {
  region     = "us-west-1"
  kms_key_id = "arn:aws:kms:us-west-1:XXXXXXXXXXXX:alias/vault"
}
ui       = true  
```

You could also limit access to the 8100/8101 ports via security groups for that extra layer of security.

Of course, using vault-issued certs somewhat presents a chicken/egg problem, but if you're just standing up a new cluster, then you could simply disable TLS while the cluster is coming online, then enable it once you have the PKI backend functional.

**Comment by matt-slalom** [comment]
In terms of suggestions on how to solve this, I think the best options requires code changes:

1. Rely on the `PrivateDnsName` that shows up in the Describe EC2 instances command when connecting to a node. The code is already relying on permissions to describe EC2 instances in order to get the tags that tell it which node(s) are part of the cluster. Unfortunately, this `compute.internal` does not match the actual domain name of the system, so that's a pretty major flaw.
2. Rely on a different Tag field to identify the DNS name for each host. We're already relying on tags to identify the nodes, so an additional field doesn't seem like a stretch.
3. Rely on reverse DNS (in-addr) entries to go from IP address to DNS name and connect that way. This is a lot more work on the setup side of things since EC2 instances that rely on DHCP don't auto-register with Route 53. We'd have to setup CloudWatch triggers, Lambda functions, and a DynamoDB table to track instance lifecycle and then update Route 53 accordingly. Ugh.

Option 2 seems like the most straightforward option, IMHO...

**Comment by welderpb** [comment]
@mgriffin13 thank you for your solution.. But not so clear, where we can get this "vault-issued PKI certificates" during the node starting. The main idea, that node can start from AMI and automatically join the cluster without human intervention.

**Comment by welderpb** [comment]
@matt-slalom 
Yes, i also agree with option 2.. Tag field with DNS name will be preferable options..

**Comment by bortzvk** [comment]
> * Rely on a different Tag field to identify the DNS name for each host. We're already relying on tags to identify the nodes, so an additional field doesn't seem like a stretch.

I absolutely agree that second option would be most optimal one, since we already use that approach (Tags for auto-discovery). Is there any chance someone from Hashicorp's team could look at it at the code level?

**Comment by mgriffin13** [comment]
> 
> 
> @mgriffin13 thank you for your solution.. But not so clear, where we can get this "vault-issued PKI certificates" during the node starting. The main idea, that node can start from AMI and automatically join the cluster without human intervention.

I use the [vault pki backend](https://www.vaultproject.io/docs/secrets/pki) and then use [vault agent aws auto auth](https://www.vaultproject.io/docs/agent/autoauth/methods/aws) to issue a new cert during the bootstrap sequence.

https://learn.hashicorp.com/tutorials/vault/agent-aws?in=vault/app-integration

**Comment by matt-slalom** [comment]
I looked at the code @ncabatoff merged in and, at least to me, it does not really address the problem. The leader in a Vault cluster can change, and if I knew the name of the leader in advance, I wouldn't really need auto discovery and auto join (the code changes add a `LeaderTLSServerName` option).

I'd love to see Hashicorp further the use of tags in auto discovery and auto join, as has been suggested in this thread.

**Comment by ncabatoff** [comment]
Hi @matt-slalom,

I've written some docs relating to this issue here: https://github.com/hashicorp/vault/pull/10865

I think maybe you're thinking that LeaderTLSServerName has to match the actual DNS name of the leader node, which isn't the case.  You can put a shared name (e.g. "vault") in the DNS SANs of the certificates of all your nodes - perhaps in addition to other real DNS names, or not, either way.

If it helps, here's my fork of a repo I used to test this feature on AWS: https://github.com/hashicorp/terraform-aws-vault-starter/tree/test-cloud-auto-join.  In particular, [here I set up the DNS SAN](https://github.com/hashicorp/terraform-aws-vault-starter/blob/test-cloud-auto-join/modules/vault_cluster/scripts/install_hashitools_vault.sh.tpl#L47), and [here I reference it](https://github.com/hashicorp/terraform-aws-vault-starter/blob/test-cloud-auto-join/modules/vault_cluster/scripts/install_hashitools_vault.sh.tpl#L108).

**Comment by matt-slalom** [comment]
Hi @ncabatoff. You are right: I misunderstand what that field is intended to do. Thank you for taking the time to document and setup tests. I will have to check it out!

**Comment by matt-slalom** [comment]
I tested this but I was unsuccessful at getting 1.6.2 to rely on this new feature. I get the same errors I reported in this bug. I don't want to divert the purpose of this bug report, so if I'm able to definitively determine it's not just my own misunderstanding, I may need to open a separate bug.

```
# openssl x509 -in cert.crt -text|grep DNS
                DNS:vm2.test.local, DNS:vault.test.local, IP Address:127.0.0.1
```
```
storage "raft" {
  path       = "/opt/vault/data"
  node_id      = "raft-node-25643"
  retry_join {
      auto_join = "provider=aws addr_type=private_v4 tag_key=Project tag_value=Vault region=us-west-1"
      auto_join_scheme = "https"
      leader_tls_servername = "vault.test.local"
  }
}
```

**Comment by ncabatoff** [comment]
Hi @matt-slalom,

I've been leaving this issue open until my docs PR got merged, and until I had time to investigate your last comment.  However, re that last comment, I suspect you might be hitting a bug in the leader_tls_servername code I wrote for 1.6.2: #11189.  I'll try to get a fix out for that soon.
