### ISSUE TITLE
Split away code for decoding root tokens into a function

### ISSUE THREAD

**Issue by ptzianos** [hashicorp/vault#10504]
**Is your feature request related to a problem? Please describe.**
When using the API client to generate a temporary root token using the unseal keys, there is no way of easily decoding the root token that is returned. The piece of code that performs this function is inside the `command/operator_generate_root.go` file and can't be re-used.

**Describe the solution you'd like**
Split away the code into a function that can be re-used by anyone who wants to create a temp root token using the API client

**Comment by PayalSasmal10** [comment]
can we decode the root token from this code using API?

**Comment by ptzianos** [comment]
@PayalSasmal10 the workflow that I had in mind (and that I implemented based on this) is that you get a new token via the API and then decode it using the helper function. so in pseudo-Go it looks like this:
```
var tempRootToken string
for i, unsealKey := range unsealKeys {
	resp, err := client.Sys().GenerateRootUpdate(string(unsealKey[:]), rootInitResp.OTP)
	if resp.Complete {
		tempRootToken, err = token.DecodeRootToken(resp.EncodedRootToken, rootInitResp.OTP, rootInitResp.OTPLength)
		break
	}
}
```

**Comment by PayalSasmal10** [comment]
Thanks @ptzianos . Waiting for merging this commit.
