### ISSUE TITLE
Return a not found page when UI url is incorrect for tools path

### ISSUE THREAD

**Issue by marcosnils** [hashicorp/vault#10534]
**Is your feature request related to a problem? Please describe.**
I got frustrated today when I tried to access the unwrap tool and for some reason it didn't seem to be working until I realized that I had a typo and I was typing `unwarp` instead. Seems like the `/tools/*` path doesn't handle unexisting resources

**Describe the solution you'd like**
Get the standard 404 Vault page that you get elsewhere in the UI

**Describe alternatives you've considered**
N/A

**Explain any additional use-cases**
N/A

**Additional context**
N/A

**Comment by hellobontempo** [comment]
Thank you for reporting! This is resolved in more recent versions of Vault. I can confirm 1.15.1, and I believe 1.14 as well. Please reopen if this is still an issue for you and include which version of Vault you are using.
