### ISSUE TITLE
github auth via http api, using documented example, fails with curl, but token works in gui client

### ISSUE THREAD

**Issue by wkhatch** [hashicorp/vault#10584]
**Describe the bug**
I get an errors response "missing client token" when using curl to test github auth, upon login. The token I'm using works fine in the UI, and, the format of my request matches the documented auth format. The auth is mounted at github/

**To Reproduce**
issue curl command, using a valid github dev token and valid host url, and note as previously mentioned, this is mounted at github, not auth/github/, like:
```
curl --request POST --data '{"token":"the token that works in the UI"}' https://myserver.com/v1/github/login
{"errors":["missing client token"]}
```

Example per your documentation, here:
```
curl \
    --request POST \
    --data '{"token": "MY_TOKEN"}' \
    http://127.0.0.1:8200/v1/auth/github/login
```

**Expected behavior**
I expected to get back an auth token. Not an error

**Comment by swayne275** [comment]
Hi! It might be that your auth needs to be mounted under the `auth/` prefix. Could you try that and let me know if it is still not working?

per the example you referenced (and https://www.vaultproject.io/docs/auth#enabling-disabling-auth-methods) it sounds like that might be the solution.

**Comment by HridoyRoy** [comment]
Hi, I'm closing this issue due to 30 days having passed since the waiting for response tag was added. Please feel free to reopen with further details. Thanks!
