### ISSUE TITLE
ZooKeeper Backend: Authnetication and Authorization support

### ISSUE THREAD

**Issue by eyal-lupu** [hashicorp/vault#1058]
Current implementation of ZooKeeper back-end doesn’t use authentication and authorization ACL support – it sets any ZK node with the public access ACL (‘world:anyone:rwcda’). As a result anyone connected to ZK can modify those nodes and, in practice, take Vault out of service. 

Reading Vault data out of ZK nodes is less of an immediate problem since data is encrypted. However by modifying the data one can:
- Delete the _keyring node- which made the vault, after restarting, think that it was not initialized
- Modify a secret with some arbitrary data - which caused Vault to return an error when attempting to read that secret

A suggested solution is to modify ZooKeeper back-end to be configured with
- Authentication information 
- ACL format for nodes created by Vault

**Comment by eliasgrander** [comment]
This issue has a merged PR and the ZK backend supports authentication and authorization without known problems with "auth_info" and "znode_owner" optional settings, so why was this issue opened again?

**Comment by jefferai** [comment]
It was reopened because it was accidentally closed. But I'm happy to close it again if the task was completed.
