### ISSUE TITLE
How to deploy Hashicorp Opensource Vault in Docker Container

### ISSUE THREAD

**Issue by MohdRashid01** [hashicorp/vault#10608]
Hi All,

I have one problem i have given one task but i’m not understand how can i do it…if anyone knows please help with clear steps so that i can easily do it

    Deploy a Hashicorp Opensource Vault container ===> DONE
    Using CLI or UI add username/password of NetBanking App ===> DONE
    Using Vault API with Token retrieve NetBanking app’s username/password using @Cmd
    Next call another NetBanking App’s token generation apis with the credentials

And after searching in google i have done little bit till here…
image
image913×423 23.4 KB

after that i want to .do this how can i do it please help me…
Using Vault API with Token retrieve NetBanking app’s username/password using @Cmd

    Next call another NetBanking App’s token generation apis with the credentials

Please let me know…

**Comment by swayne275** [comment]
Hi Mohd! I think this question would be better discussed in our [forum](https://discuss.hashicorp.com/c/vault/30). Best of luck!
