### ISSUE TITLE
VAULT DOWN IN PRODUCTION 

### ISSUE THREAD

**Issue by lagging** [hashicorp/vault#1060]
We are using vault in production for storing secret and using mysql as its backend. We are using tls authentication .Few days back our vault got down we are unable to find the issue. Attached are the logs. If any one can help

--------------------------------------------
[MySQL] 2016/02/01 22:36:16 packets.go:118: write tcp 10.245.25.142:39997->10.245.30.156:3306: write: broken pipe
[MySQL] 2016/02/01 22:36:16 packets.go:118: write tcp 10.245.25.142:39997->10.245.30.156:3306: write: broken pipe
[MySQL] 2016/02/01 22:36:16 packets.go:118: write tcp 10.245.25.142:39997->10.245.30.156:3306: write: broken pipe
[MySQL] 2016/02/01 22:36:16 packets.go:118: write tcp 10.245.25.142:39997->10.245.30.156:3306: write: broken pipe
[MySQL] 2016/02/01 22:36:16 packets.go:118: write tcp 10.245.25.142:39986->10.245.30.156:3306: write: broken pipe
[MySQL] 2016/02/01 22:36:16 packets.go:118: write tcp 10.245.25.142:39986->10.245.30.156:3306: write: broken pipe
[MySQL] 2016/02/01 22:36:16 packets.go:118: write tcp 10.245.25.142:39986->10.245.30.156:3306: write: broken pipe
[MySQL] 2016/02/01 22:36:16 packets.go:118: write tcp 10.245.25.142:39986->10.245.30.156:3306: write: broken pipe
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x809f82]

goroutine 44406 [running]:
database/sql.(*Rows).Next(0x0, 0xc82076b910)
        /usr/local/go/src/database/sql/sql.go:1633 +0x22
github.com/hashicorp/vault/physical.(*MySQLBackend).List(0xc820185cc0, 0xc82048f380, 0x3a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/physical/mysql.go:174 +0x331
github.com/hashicorp/vault/physical.(*Cache).List(0xc8201cf420, 0xc82048f380, 0x3a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/physical/cache.go:83 +0x77
github.com/hashicorp/vault/vault.(*AESGCMBarrier).List(0xc8201da720, 0xc82048f380, 0x3a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:664 +0x210
github.com/hashicorp/vault/vault.(*BarrierView).List(0xc8200b9420, 0xc8208afe00, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/barrier_view.go:44 +0x17f
github.com/hashicorp/vault/vault.(*TokenStore).revokeTreeSalted(0xc820248cc0, 0xc8208afdd0, 0x28, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/token_store.go:494 +0xb8
github.com/hashicorp/vault/vault.(*TokenStore).RevokeTree(0xc820248cc0, 0xc8208afce0, 0x24, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/token_store.go:483 +0x1cb
github.com/hashicorp/vault/vault.(*ExpirationManager).revokeEntry(0xc8201d1700, 0xc8206f6500, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/expiration.go:481 +0x83
github.com/hashicorp/vault/vault.(*ExpirationManager).Revoke(0xc8201d1700, 0xc8203e25c0, 0x38, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/vault/expiration.go:188 +0x1bf
github.com/hashicorp/vault/vault.(*ExpirationManager).expireID(0xc8201d1700, 0xc8203e25c0, 0x38)
        /gopath/src/github.com/hashicorp/vault/vault/expiration.go:465 +0x104
github.com/hashicorp/vault/vault.(*ExpirationManager).updatePending.func1()
        /gopath/src/github.com/hashicorp/vault/vault/expiration.go:438 +0x37
created by time.goFunc
        /usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 4867 minutes]:
github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc82022e000, 0xc82000a160, 0x2, 0x2, 0xc820220be8)
        /gopath/src/github.com/hashicorp/vault/command/server.go:258 +0x3560
github.com/mitchellh/cli.(*CLI).Run(0xc820218370, 0xc820218370, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/mitchellh/cli/cli.go:112 +0x698
github.com/hashicorp/vault/cli.RunCustom(0xc82000a150, 0x3, 0x3, 0xc8201c6ba0, 0x2)
        /gopath/src/github.com/hashicorp/vault/cli/main.go:44 +0x452
github.com/hashicorp/vault/cli.Run(0xc82000a150, 0x3, 0x3, 0x9c2d00)
        /gopath/src/github.com/hashicorp/vault/cli/main.go:11 +0x4c
main.main()
        /gopath/src/github.com/hashicorp/vault/main.go:10 +0x60

goroutine 5 [syscall, 4867 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 17 [select, 4867 minutes, locked to thread]:
runtime.gopark(0x1485d78, 0xc820026728, 0x1212448, 0x6, 0x42c618, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820026728, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820026728)
        /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 18 [chan receive, 4867 minutes]:
github.com/hashicorp/vault/cli.makeShutdownCh.func1(0xc8201da3c0, 0xc8201da360)
        /gopath/src/github.com/hashicorp/vault/cli/commands.go:296 +0x36
created by github.com/hashicorp/vault/cli.makeShutdownCh
        /gopath/src/github.com/hashicorp/vault/cli/commands.go:299 +0x195

goroutine 19 [semacquire, 4867 minutes]:
sync.runtime_Syncsemacquire(0xc82022e100)
        /usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc82022e0f0)
        /usr/local/go/src/sync/cond.go:62 +0x9b
io.(*pipe).read(0xc82022e0c0, 0xc82019d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:52 +0x2d2
io.(*PipeReader).Read(0xc8201cc060, 0xc82019d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:134 +0x50
bufio.(*Scanner).Scan(0xc8201d2300, 0x0)
        /usr/local/go/src/bufio/scan.go:180 +0x877
github.com/hashicorp/vault/command.(*Meta).FlagSet.func1(0xc8201d2300, 0xc82022e020)
        /gopath/src/github.com/hashicorp/vault/command/meta.go:187 +0x25
created by github.com/hashicorp/vault/command.(*Meta).FlagSet
        /gopath/src/github.com/hashicorp/vault/command/meta.go:190 +0x5e6

goroutine 20 [chan receive, 4867 minutes]:
database/sql.(*DB).connectionOpener(0xc8201de820)
        /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 21 [select, 4867 minutes]:
github.com/armon/go-metrics.(*InmemSignal).run(0xc8201d0780)
        /gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/armon/go-metrics/inmem_signal.go:63 +0xf2
created by github.com/armon/go-metrics.NewInmemSignal
        /gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/armon/go-metrics/inmem_signal.go:37 +0x22b

goroutine 22 [sleep]:
time.Sleep(0x3b9aca00)
        /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/armon/go-metrics.(*Metrics).collectStats(0xc8201ca6e0)
        /gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/armon/go-metrics/metrics.go:67 +0x25
created by github.com/armon/go-metrics.New
        /gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/armon/go-metrics/start.go:61 +0xdb

goroutine 23 [IO wait]:
net.runtime_pollWait(0x7f4b634b3398, 0x72, 0xc8200101b0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820215100, 0x72, 0x0, 0x0)
        /goroot/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820215100, 0x0, 0x0)
        /goroot/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8202150a0, 0x0, 0x7f4b634b38e8, 0xc8202660e0)
        /goroot/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8201cc1a8, 0xc82088f320, 0x0, 0x0)
        /goroot/src/net/tcpsock_posix.go:254 +0x4d
github.com/hashicorp/vault/command/server.tcpKeepAliveListener.Accept(0xc8201cc1a8, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/command/server/listener_tcp.go:35 +0x41
crypto/tls.(*listener).Accept(0xc8202842e0, 0x0, 0x0, 0x0, 0x0)
        /goroot/src/crypto/tls/tls.go:46 +0x60
net/http.(*Server).Serve(0xc82026db60, 0x7f4b634b3810, 0xc8202842e0, 0x0, 0x0)
        /goroot/src/net/http/server.go:1887 +0xb3
created by github.com/hashicorp/vault/command.(*ServerCommand).Run
        /gopath/src/github.com/hashicorp/vault/command/server.go:232 +0x2df6

goroutine 33 [select]:
github.com/hashicorp/vault/vault.(*RollbackManager).run(0xc82026dbc0)
        /gopath/src/github.com/hashicorp/vault/vault/rollback.go:96 +0x1df
created by github.com/hashicorp/vault/vault.(*RollbackManager).Start
        /gopath/src/github.com/hashicorp/vault/vault/rollback.go:73 +0x35

goroutine 34 [select]:
github.com/hashicorp/vault/vault.(*Core).emitMetrics(0xc82021c4e0, 0xc820415920)
        /gopath/src/github.com/hashicorp/vault/vault/core.go:1694 +0x151
created by github.com/hashicorp/vault/vault.(*Core).postUnseal
        /gopath/src/github.com/hashicorp/vault/vault/core.go:1432 +0x697

goroutine 44391 [IO wait]:
net.runtime_pollWait(0x7f4b634f9c58, 0x72, 0xc8200101b0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8206f4290, 0x72, 0x0, 0x0)
        /goroot/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8206f4290, 0x0, 0x0)
        /goroot/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8206f4230, 0xc82014a000, 0x400, 0x400, 0x0, 0x7f4b634ee050, 0xc8200101b0)
        /goroot/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8201cc058, 0xc82014a000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /goroot/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8208af8c0, 0x7f4b634f30b0, 0xc8201cc058, 0x5, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82007fb80, 0x16, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).readHandshake(0xc82007fb80, 0x0, 0x0, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:776 +0xd3
crypto/tls.(*serverHandshakeState).readClientHello(0xc820243b28, 0xc82003fb10, 0x0, 0x0)
        /goroot/src/crypto/tls/handshake_server.go:107 +0x5b
crypto/tls.(*Conn).serverHandshake(0xc82007fb80, 0x0, 0x0)
        /goroot/src/crypto/tls/handshake_server.go:48 +0xab
crypto/tls.(*Conn).Handshake(0xc82007fb80, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:976 +0x169
net/http.(*conn).serve(0xc8205f46e0)
        /goroot/src/net/http/server.go:1303 +0x31a
created by net/http.(*Server).Serve
        /goroot/src/net/http/server.go:1910 +0x3f6

goroutine 44389 [IO wait]:
net.runtime_pollWait(0x7f4b634ca790, 0x72, 0xc8200101b0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8206f41b0, 0x72, 0x0, 0x0)
        /goroot/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8206f41b0, 0x0, 0x0)
        /goroot/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8206f4150, 0xc820129c00, 0x400, 0x400, 0x0, 0x7f4b634ee050, 0xc8200101b0)
        /goroot/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8201cc048, 0xc820129c00, 0x400, 0x400, 0x0, 0x0, 0x0)
        /goroot/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8208ae6c0, 0x7f4b634f30b0, 0xc8201cc048, 0x5, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82007f8c0, 0x16, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).readHandshake(0xc82007f8c0, 0x0, 0x0, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:776 +0xd3
crypto/tls.(*serverHandshakeState).readClientHello(0xc820769b28, 0xc82003fb10, 0x0, 0x0)
        /goroot/src/crypto/tls/handshake_server.go:107 +0x5b
crypto/tls.(*Conn).serverHandshake(0xc82007f8c0, 0x0, 0x0)
        /goroot/src/crypto/tls/handshake_server.go:48 +0xab
crypto/tls.(*Conn).Handshake(0xc82007f8c0, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:976 +0x169
net/http.(*conn).serve(0xc8205f44d0)
        /goroot/src/net/http/server.go:1303 +0x31a
created by net/http.(*Server).Serve
        /goroot/src/net/http/server.go:1910 +0x3f6

**Comment by jefferai** [comment]
I'm not sure where the first part of your logs came from
```
[MySQL] 2016/02/01 22:36:16 packets.go:118: write tcp 10.245.25.142:39997->10.245.30.156:3306: write: broken pipe
[MySQL] 2016/02/01 22:36:16 packets.go:118: write tcp 10.245.25.142:39997->10.245.30.156:3306: write: broken pipe
```
Did those come from Vault?

Overall it looks like either Vault cannot talk to your MySQL server, or was disconnected from your MySQL server.

**Comment by lagging** [comment]
Hi yeah i got it this might be due to connection pool problem in mysql .

**Comment by lagging** [comment]
[vault_log.txt](https://github.com/hashicorp/vault/files/132543/vault_log.txt)

This is total logged available .This is critical as our vault is in production. Any suggestion would be greatly helpful.

**Comment by jefferai** [comment]
Closing since #1084 is identical with the same reporter.
