### ISSUE TITLE
ReadWithData is not allowed for identity/group-alias 

### ISSUE THREAD

**Issue by josedev-union** [hashicorp/vault#10627]
I reconcile to put the group-alias by consuming vault api.
i.e. need to keep the group-alias with specified `mount_accessor`, `canonical_id` and `name`.

External group can only have one alias so if the group-alias is existing with the same `mount_accessor` and `name`, then it is not able to write.
So if it exists, need to check if the `canonical_id` is the same with reconcilng one. If same, then skip while if not same, delete and recreate the group-alias with new canonical_id.

The problem is how to get group-alias using `mount_accessor` and `name` (without `id`).
I tried to use logical().ReadWithData() but it returns error like this;
```
Error making API request.\n\nURL: GET https://vault.xxx.com/v1/identity/group-alias?canonical_id=dcbf4a2d-1338-7d42-f34a-3bedb5a01914&mount_accessor=auth_oidc_6fe3940a&name=test\nCode: 405. Errors:\n\n* 1 error occurred:\n\t* unsupported operation\n\n
```

So `identity/group-alias` is not allowing readWithData?

**Comment by swayne275** [comment]
Thanks for the comment! This might be better resolved/understood in our forum. If it turns out there is some bug/feature-request from that then please let us know!

https://discuss.hashicorp.com/c/vault/30
