### ISSUE TITLE
Use subkey derivation for AEAD ciphers

### ISSUE THREAD

**Issue by DemiMarie** [hashicorp/vault#10621]
**Is your feature request related to a problem? Please describe.**
AES-GCM keys need to be rotated frequently, which is annoying.

**Describe the solution you'd like**
Vault generates a key at startup (using HKDF or similar) from a master key and a long random nonce.  This key is per-process, so the nonce can be generated randomly at startup and subsequently incremented for every encryption.

**Describe alternatives you've considered**
Use an AEAD such as XChaCha20/Poly1305 that has a longer nonce.

**Explain any additional use-cases**
This avoids the monitoring required by AES-GCM.

**Additional context**
Inspired by #10612.

**Comment by sgmiller** [comment]
Just FYI, that PR is just the first part of a larger effort.

**Comment by mladlow** [comment]
Hi @DemiMarie - ultimately, we decided to address the annoyance of frequent key rotation requirements by adding automatic rotation (https://github.com/hashicorp/vault/pull/11007, https://www.vaultproject.io/docs/upgrading/upgrade-to-1.7.0#barrier-key-auto-rotation). We discussed the solution proposed in this issue and the alternatives. I'm going to close this issue in light of that work.
