### ISSUE TITLE
Azure MSI support doesn't support App Service

### ISSUE THREAD

**Issue by mbrancato** [hashicorp/vault#10623]
**Describe the bug**
The Azure MSI endpoint used in App Service is different than the instance metadata endpoint. The Azure `storage` and `seal` use-cases both fail to use the MSI identity.

```
2020-12-27T07:28:26.779968907Z Error parsing Seal configuration: error initializing Azure Key Vault wrapper client: failed to get oauth token from MSI: parameter 'msiEndpoint' cannot be empty
```

```
2020-12-27T06:32:15.538396501Z Error initializing storage of type azure: failed to obtain auth token from IMDS "AzurePublicCloud": the MSI endpoint is not available. Failed HTTP request to MSI endpoint: Get "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01": dial tcp 
```

Note: there is also a SSRF token header required with App Service.
https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity

This is implemented upstream in `go-autorest/adal`, but I'm not sure if Vault can use `adal` for everything.

**Expected behavior**
Vault should get valid tokens

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.6.1
* Vault CLI Version (retrieve with `vault version`): 1.6.1
* Server Operating System/Architecture: Linux amd64

Vault server configuration file(s):

```hcl
storage "azure" {
  accountName = "my-storage-account"
  container   = "container-efgh5678"
  environment = "AzurePublicCloud"
}
seal "azurekeyvault" {
  tenant_id      = "46646709-b63e-4747-be42-516edeaf1e14"
  vault_name     = "hc-vault"
  key_name       = "vault_key"
}
```

**Comment by mbrancato** [comment]
The error regarding a missing MSI endpoint value was due to App Service not injecting the `MSI_ENDPOINT` or `IDENTITY_ENDPOINT` env vars using the Docker compose configuration.

**Comment by elsesiy** [comment]
Good catch @mbrancato, I didn't think of App service support when I implemented this
