### ISSUE TITLE
STS driven AWS secret backend is creating names that are far too long

### ISSUE THREAD

**Issue by mostman79** [hashicorp/vault#1063]
One of the differences between using IAM users and STS tokens is that the limit on the entity name changes. For IAM Users, the limit on `name` is 64 characters. For STS tokens, the `name` is limited to 32 characters. See here:

http://docs.aws.amazon.com/STS/latest/APIReference/API_GetFederationToken.html

Anything longer than 32 and you will hit this:

```Error generating STS keys: ValidationError: 1 validation error detected: Value 'vault-token-xxxxxxx-1455248919-4059' at 'name' failed to satisfy constraint: Member must have length less than or equal to 32```

So here is the problem, the name formatting for the STS token appears to be using the same helper function that was used for IAM Users. Specifically, this one:

```
func genUsername(displayName, policyName string) string {
	// Generate a random username. We don't put the policy names in the
	// username because the AWS console makes it pretty easy to see that.
	return fmt.Sprintf(
		"vault-%s-%s-%d-%d",
		normalizeDisplayName(displayName),
		normalizeDisplayName(policyName),
		time.Now().Unix(),
		rand.Int31n(10000))
}
```

By my count, that is 28 characters before we use `policyName`. I'm not exactly clear on how `displayName` can be adjusted, but it always seems to be `token` for me. This leaves room for a 4 character policy name.

I don't have a firm opinion on how this might be truncated, but I think that `displayName` field might be a good start. The thing is, the identity of the STS token will likely never be seen. Its unlike IAM Users in that there isn't a place one could just go to and browse and see these. So, really, any random string would work. Time plus a random number would be enough.

**Comment by jefferai** [comment]
Related to #1031.

**Comment by mostman79** [comment]
Thanks @jefferai - Yep, looks to be similar and the same solution would work here. The truncation would just have to be smart enough to know how much it has to chop as, in that case, 64 is workable.
