### ISSUE TITLE
vault 1.6.1 build fixes

### ISSUE THREAD

**Issue by he32** [hashicorp/vault#10638]
**Describe the bug**

I tried to build vault 1.6.1.  In addition to the function signature failure reported in #10330, this build
uncovered new function signature failures.

**To Reproduce**
1. Build vault with go 1.15
2. See error

**Expected behavior**

The build ought to succeed without any type or function signature errors.

**Environment:**

* Operating System/Architecture: NetBSD/i386 8.0.
* The build is done inside the scaffolding provided by the pkgsrc package system, but it eventually ends up doing `/usr/pkg/go115/bin/go install -v github.com/hashicorp/vault/...` after the source has been checksum-verified, extracted and moved to the right spot, plus the environment has been "cleaned".

Part of the build log showing the build error:

```
# github.com/hashicorp/vault/plugins/database/mysql/mysql-database-plugin
work/src/github.com/hashicorp/vault/plugins/database/mysql/mysql-database-plugin/main.go:22:15: not enough arguments in call to mysql.New
        have (bool)
        want (int, int, int)
github.com/hashicorp/vault/plugins/database/mysql/mysql-legacy-database-plugin
# github.com/hashicorp/vault/plugins/database/mysql/mysql-legacy-database-plugin
work/src/github.com/hashicorp/vault/plugins/database/mysql/mysql-legacy-database-plugin/main.go:22:15: not enough arguments in call to mysql.New
        have (bool)
        want (int, int, int)

```

Even though I'm a `go` novice, an inspection of the `mysql.go` file shows that the `New` function
does indeed take three `int` arguments, not a single `bool` argument, ref.
`plugins/database/mysql/mysql.go` from line 48:

```
// New implements builtinplugins.BuiltinFactory
func New(displayNameLen int, roleNameLen int, maxUsernameLen int) func() (interface{}, error) {
        return func() (interface{}, error) {
                db := newMySQL(displayNameLen, roleNameLen, maxUsernameLen)
                // Wrap the plugin with middleware to sanitize errors
                dbType := dbplugin.NewDatabaseErrorSanitizerMiddleware(db, db.SecretValues)

                return dbType, nil
        }
}
```

It seems that these patches fix the issue:

```
--- plugins/database/mysql/mysql-database-plugin/main.go.orig   2020-12-15 00:54:07.000000000 +0000
+++ plugins/database/mysql/mysql-database-plugin/main.go
@@ -19,7 +19,7 @@ func main() {
 // Run instantiates a MySQL object, and runs the RPC server for the plugin
 func Run() error {
        var f func() (interface{}, error)
-       f = mysql.New(false)
+       f = mysql.New(32, 32, 32)
        dbType, err := f()
        if err != nil {
                return err
--- plugins/database/mysql/mysql-legacy-database-plugin/main.go.orig    2020-12-15 00:54:07.000000000 +0000
+++ plugins/database/mysql/mysql-legacy-database-plugin/main.go
@@ -19,7 +19,7 @@ func main() {
 // Run instantiates a MySQL object, and runs the RPC server for the plugin
 func Run() error {
        var f func() (interface{}, error)
-       f = mysql.New(true)
+       f = mysql.New(32, 32, 32)
        dbType, err := f()
        if err != nil {
                return err
```

**Additional context**

Do you need anything else?

The question I sit with is how this is not flagged by your release machinery?

**Comment by kalafut** [comment]
@pcman312 I do get a build error if I target the `main` package explicitly: `go build ./plugins/database/mysql/mysql-database-plugin`

**Comment by pcman312** [comment]
Thanks for the bug report @he32! This does look like a missed change in the MySQL plugin main and I'll get a fix up for this shortly. As for why this is being hit now, I believe you are seeing the issue because your tooling is building `github.com/hashicorp/vault/...` instead of `github.com/hashicorp/vault/`. The former ends up building every sub-package under Vault in addition to the Vault main. The MySQL plugin (as well as the Redshift plugin) are built into Vault so the main file you are seeing this error from (`.../mysql-database-plugin/main.go`) is not normally built. To fix your build, you will want to make it run `/usr/pkg/go115/bin/go install -v github.com/hashicorp/vault` or utilize our Makefile. The default `make` command will build it and place the binary within `/path/to/vault/bin/` as well as in your GOPATH: `${GOPATH}/bin/vault`.

**Comment by he32** [comment]
> Thanks for the bug report @he32! This does look like a missed change in the MySQL plugin main and I'll get a fix up for this shortly. As for why this is being hit now, I believe you are seeing the issue because your tooling is building `github.com/hashicorp/vault/...` instead of `github.com/hashicorp/vault/`.

That was it, and it's easily compensated for in the package; now done.
