### ISSUE TITLE
Database MS SQL: AWS RDS - failed to revoke user.

### ISSUE THREAD

**Issue by iusergii** [hashicorp/vault#10648]
**Describe the bug**
Vault deletes login but fails to remove the user on revoke.

**To Reproduce**
1. Create DB config:
```
vault write test-database/config/sa-config \
    plugin_name=mssql-database-plugin \
    connection_url='sqlserver://{{username}}:{{password}}@mydev.db.com:1433' \
    allowed_roles="*" \
    username="admin" \
    password="password" \
    max_open_connections=1
```
2. Create DB Role with [revokation statement ](https://www.vaultproject.io/docs/secrets/databases/mssql#amazon-rds)
```
vault write test-database/roles/tenant-1 \
    db_name=sa-config \
    creation_statements="USE [master]; CREATE LOGIN [{{name}}] WITH PASSWORD = '{{password}}', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF; USE [tenant-1]; CREATE USER [{{name}}] FOR LOGIN [{{name}}]; ALTER ROLE [db_owner] ADD MEMBER [{{name}}];"\
    revocation_statements="\
     USE tenant-1; \
     IF EXISTS \
       (SELECT name \
        FROM sys.database_principals \
        WHERE name = N'{{name}}') \
     BEGIN \
       DROP USER [{{name}}] \
     END \

     IF EXISTS \
       (SELECT name \
        FROM master.sys.server_principals \
        WHERE name = N'{{name}}') \
     BEGIN \
       DROP LOGIN [{{name}}] \
     END"
      default_ttl="1h" \
      max_ttl="24h"
```
3. Generate a new credentials `vault read test-database/creds/tenant-1`
4. Revoke lease `vault lease revoke test-database/creds/tenant-1-xxxxxxxxx`

**Expected behavior**
Both login and user are deleted. 

**Environment:**
`Vault v1.5.4`

**Additional context**
Looks like an SQL statement for the user drop is run on master DB.

**Comment by iusergii** [comment]
Removing semicolon from revocation_statements `USE tenant-1;` -> `USE [tenant-1]` seems helps.

**Comment by HridoyRoy** [comment]
> Removing semicolon from revocation_statements `USE tenant-1;` -> `USE [tenant-1]` seems helps.

Hi @iusergii , did this fix the problem?

**Comment by iusergii** [comment]
@HridoyRoy yes, that helped.

**Comment by HridoyRoy** [comment]
Great! I will go ahead and close out this issue then.

Thanks so much!

**Comment by dragoonTND** [comment]
Not to comment on a closed issue. We saw this too and this did help resolve it for us as well. Not just a AWS RDS issue but generically for MS SQL DB credentails.

The issue is why is this different (or is it), for creation statements vs. revocation statements.
