### ISSUE TITLE
Agent: Allow setting vault retry params for rendering templates

### ISSUE THREAD

**Issue by ibspoof** [hashicorp/vault#10646]
**Is your feature request related to a problem? Please describe.**
MR #9670 enabled consul retry config to be used when rendering the vault agent templates, but only the defaults are used which have a short timeout (<10m).  

Our use case of the agent requires that the agent may be disconnected from Vault due to a network issue for up to one hour and needs to have configurable retry settings including attempts, backoff and max backoff.  This should be in accordance with consul templates usage of retries.

**Describe the solution you'd like**
Add retry settings under vault in the agent configs to override the default values from consul-template and apply retry to all templates to be rendered.

Example config:
```
vault {
   address = "http://localhost:8200"

   # retry up to 95m (~1.5 hours)
   retry {
     enabled = true
     attempts = 10
     backoff = "30s"
     max_backoff = "16m"
  }
}
```

**Describe alternatives you've considered**
None

**Explain any additional use-cases**
In combination with using `error_on_missing_key` once the agent is in a bad state the agent will exit it's process and stop requests to the Vault service.  This is especially important when using a single use auth credentials and the token is expired.  

**Additional context**
Merge request #10644 adds feature requested.

**Comment by HridoyRoy** [comment]
Thanks for the feature request and PR @ibspoof ! I'll take a look asap.

**Comment by HridoyRoy** [comment]
I @ibspoof , I've merged the PR above. I'm going to go ahead and close this PR, but please feel free to reopen it if necessary. Thanks so much!
