### ISSUE TITLE
PKI backend returns 500 when cert is not found

### ISSUE THREAD

**Issue by phinze** [hashicorp/vault#1065]
Steps to reproduce:

```
vault mount pki
vault write pki/root/generate/internal common_name=example.com
vault read pki/cert/ab:12:cd:34
```

Expected behavior:

 * 404 response from API
 * Ends up being translated to "No value found at {{path}}" message on CLI I believe

Observed behavior:

```
Error reading pki/cert/ab:12:cd:34: Error making API request.

URL: GET http://127.0.0.1:8200/v1/pki/cert/ab:12:cd:34
Code: 500. Errors:

* certificate with serial number ab:12:cd:34 not found
```

**Comment by jefferai** [comment]
Yeah, this could be a 4xx. Depends whether it's not found because of physical store failure, but probably just user error.
