### ISSUE TITLE
Policy with wildcard secret path

### ISSUE THREAD

**Issue by josedev-union** [hashicorp/vault#10669]
I am trying to grant permissions on wildcard secret path.
So the expectation is;
When the user has such policy, 
```
path "/mysecret-*/*" {
    capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
```
then user can manage all secrets on any path `/mysecret-*/*` like `/mysecret-kv/*`, `/mysecret-kv1/*` and etc.

**Comment by HridoyRoy** [comment]
Hi @josedev-union , from https://www.vaultproject.io/docs/concepts/policies, `The glob character referred to in this documentation is the asterisk (*). It is not a regular expression and is only supported as the last character of the path!`

There is a `+` character which would allow you to do something like the following: `path "/+/*"`, but I believe you cannot do something like `path "/mysecret-+/*"` .

**Comment by josedev-union** [comment]
I used `/mysecret/*` instead of `/mysecret-*/*`.
Yes, exactly the asterisk is not a regex character.
Thank you @HridoyRoy
