### ISSUE TITLE
generating root token when using auto unseal mode

### ISSUE THREAD

**Issue by surajnarwade** [hashicorp/vault#10665]
I can see there's [documentation](https://learn.hashicorp.com/tutorials/vault/generate-root) about regenerating the root token using unseal key, but there's no documentation to generate root token if auto unseal mode is enabled?

**Comment by ncabatoff** [comment]
As a general rule, APIs that take as inputs unseal keys will instead accept recovery keys when auto unseal is in use.

**Comment by HridoyRoy** [comment]
Hi, I'm going to close this issue as it has been 30 days since the `waiting-for-response` label was added. Please feel free to reopen with more details. Thanks!
