### ISSUE TITLE
Create Token Endpoint that returns a user's policy/capabilities for a given path

### ISSUE THREAD

**Issue by ericchapman** [hashicorp/vault#1069]
The request is to expose Vault's capability decision making for a particular token to allow external systems to leverage Vault's policy logic.  (See issue https://groups.google.com/forum/#!topic/vault-tool/8BdGLNEs-V0).  I would expect the API call to have the following

 - The token in question (different from the X-Vault-Token being used to make the call)
 - The specific path in question

And the call would return the capabilities for the given path.  This would allow an external system to use the Vault logic to apply policies and capabilities to a system outside of Vault.

**Comment by jefferai** [comment]
I'm slotting this in for 0.5.1 but no promises :)
