### ISSUE TITLE
Starting server gives "Error initializing core: missing advertisement address" message

### ISSUE THREAD

**Issue by abaird** [hashicorp/vault#107]
I was going through the docs today, particularly http://vaultproject.io/intro/getting-started/deploy.html where it gives a sample server config file and then has you run the following
`vault server --config=example.hcl`
However, when I use the configuration file, I get the following error:
`Error initializing core: missing advertisement address`
Here is the example.hcl file:
```
backend "consul" {
  address = "demo.consul.io:80"
  path = "abvault12345"
}

listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
}
```

It seems that when you use Consul backend, it needs the .hcl file to be more like this:
```
backend "consul" {
  address = "demo.consul.io:80"
  path = "abvault12345"
  advertise_addr = "127.0.0.1"
}

listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
}
```
(I have no idea what kind of address advertise_addr wants)

Using this file, I was able to get the server started successfully. You can read more about the server configuration here: http://vaultproject.io/docs/config/index.html#advertise_addr.

Also, in your examples, frequently the "--" is rendered as a long dash instead of two. Probably most people know about this, but it will trip up new users.

**Comment by sethvargo** [comment]
Related to https://github.com/hashicorp/vault/issues/103

**Comment by mitchellh** [comment]
I'm going to just close as dup for #103, the solution will be the same.
