### ISSUE TITLE
Unable to create transit key with "create" capability in policy

### ISSUE THREAD

**Issue by jza201** [hashicorp/vault#10701]
**Describe the bug**
We want to create a new policy for team members who can only create keys in transit engine, but cannot update existing keys which are created by others. The policy we have is:
```
path "transit/keys/*" {
    capabilities = [ "create" ]
}
```
However we got the permission error when running `vault write -f transit/keys/my-key`
```
Error writing data to transit/keys/my-key: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/transit/keys/my-key
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

**To Reproduce**

1. Login as root
2. Run `vault secrets enable transit`
3. Create a new policy 
```
path "transit/keys/*" {
    capabilities = [ "create" ]
}
```
4. Login with this new policy
5. Run `vault write -f transit/keys/my-key`

**Expected behavior**
Transit key is created. 

**Environment:**
* Vault Server Version: 1.4.2
* Vault CLI Version: 1.4.2
* Server Operating System/Architecture: Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-123-generic x86_64)

**Comment by HridoyRoy** [comment]
Hi @jza201 , because the same API is used to create and update transit keys, you would need the associated policy to have the "update" capability as well. 

We could potentially separate out the create endpoint from the update endpoint and restrict access to those endpoints separately, but so far we haven't come across a use case where a party is allowed to create keys but not update them, so we haven't introduced that complexity. 

Please let me know if there's anything else we can help with, or if we can close out this issue. 
Thanks so much!

**Comment by HridoyRoy** [comment]
Hi @jza201 , I'm reopening this issue for discussion, as making this change would, to the best of my knowledge, require an [existence check](https://github.com/hashicorp/vault/pull/10717) to be added on the create operation for transit keys. As such, this would require existing vault customers to change all policies that allow for the creation of transit keys with the update operation to have both create and update permissions.

**Comment by jza201** [comment]
Thanks @HridoyRoy. The reason we would like to just allow users "create" capability is that we don't want users to change transit keys created by others. Let's say that user1 creates a transit key and use it to encrypt some text, then user2 updates the transit key and then user1 cannot decrypt with this transit key. I did some testing and found out that updating an existing transit key actually does cause the problem I mentioned above. So for now the need for the capabilities of both "create" and "update" work for us.

**Comment by HridoyRoy** [comment]
That is great to hear! I'm going to go ahead and close out this issue, since for now it seems like using the update capability as both create and update works for this use case. 

Feel free to reopen this issue if you'd like to follow up. 
Thanks so much!
