### ISSUE TITLE
Multiple lease count quotas on a mount path causes Vault to enter an inoperable state - "conflicting quota definitions detected"

### ISSUE THREAD

**Issue by rhys-evans** [hashicorp/vault#10712]
We enabled quotas on our non-production Vault cluster, and we somehow entered a state where all our auth mounts had duplicated quotas, which caused us to be completely locked out of our Vault cluster because logins fail with the error "conflicting quota definitions detected". We had to generate a new root token in order to clean-up the duplicated quotas.

We manage our Vault configuration, including quotas, with Terraform. It's unclear how we ended up in this state. However, it appears that it is possible to create two quotas on the same mount path by creating a quota on a different path, and then updating it to a path which already has a quota.

To Reproduce

I can reproduce this with a Vault server running in dev mode on Docker.

docker run -p 8200:8200 --rm -ti vault:latest
export VAULT_ADDR=http://localhost:8200
vault login <root token>
vault write sys/quotas/lease-count/token max-leases=100

vault write sys/quotas/lease-count/token-2 max-leases=200

We now have issues globally

vault token lookup
Error looking up token: Error making API request.

vault list sys/quotas                                                                                                                                                                                  
Error listing sys/quotas/: Error making API request.

URL: GET https://vault/v1/sys/quotas?list=true
Code: 500. Errors:

* 1 error occurred:
	* conflicting quota definitions detected
Expected behavior

I expect to not enter this state. I can think of two ways to avoid this:

Validation on creating / updating quotas should not allow for two quotas to be created on the same path.

OR

Having conflicting quotas should emit a warning and not prevent the affected backend from functioning.

Environment:

Vault Server Version (retrieve with vault status): Vault v1.5.6
Vault CLI Version (retrieve with vault version): Vault v1.5.6 
Server Operating System/Architecture: Linux amd64
Vault server configuration file(s): None (works with vault server -dev)

Additional context

We are building a terraform vault_quota_lease_count resource (https://github.com/hashicorp/terraform-provider-vault/pull/948) in order to create lease count quotas. There might also be a bug in terraform-provider-vault that causes duplicate quotas to be created.

I think this a duplicate of this issue, but for lease counts https://github.com/hashicorp/vault/issues/10319

**Comment by mladlow** [comment]
Hi @rhys-evans,

I believe that as of Vault 1.5.6 and 1.6.0, creating conflicting quotas should not be possible. When I ran the docker command, the version was 1.5.5, so we may need to update something there.

You may have figured this out, but if your cluster is stuck in a conflicting state, you can use recovery mode (https://www.vaultproject.io/docs/concepts/recovery-mode) to list and delete conflicting quotas.

**Comment by rhys-evans** [comment]
hmm, not sure how I go into that state then, manually testing now, not being able to reproduce, close this for now. Will reraise if I need to , and once I can reproduce again. Apologies for jumping the gun

**Comment by mladlow** [comment]
No worries at all, it's a serious issue. I do think it's fixed, but am definitely interested to know if it happens again.
