### ISSUE TITLE
Allow for pki/ca/pem, etc. endpoints to function after the expiration of the root certificate's TTL

### ISSUE THREAD

**Issue by captain-kark** [hashicorp/vault#10733]
When a root certificate authority passes its expiration, you can no longer retrieve its public certificate through vault's unauthenticated endpoint `$VAULT_ADDR/v1/$MOUNT/ca/pem`. It doesn't print anything, or warn the user about this in any way, but does report a `null` response for `"http_raw_body"`, as well as a 204 status in the audit logs.

**Describe the solution you'd like**

Printing some warning to stderr about the expiration of the CA while still displaying the public certificate.

**Describe alternatives you've considered**

[Storing the public certificate myself](https://tools.ietf.org/html/rfc5280#section-3.1):

> "Because a certificate's signature and timeliness can be independently checked by a certificate-using client, certificates can be distributed via untrusted communications and server systems, and can be cached in unsecured storage in certificate-using systems."

I'd rather rely on vault for this, since the endpoint is already well defined, provides proper access control for public/private key matter, and can be trusted to remain tied to the underlying private key better than an external system can.

**Explain any additional use-cases**

Anyone using a CA for the organization and structural benefits, without actually issuing certificates. It isn't common but does have some advantages.

**Additional context**

My use case would pair nicely with https://github.com/hashicorp/vault/issues/8486 as it's more to do with tying an actual CA for issuing certificates to an intermediary (or even an unaffiliated root CA) which is used to support the former in other contexts that aren't a good fit for certificate issuers, e.g., encryption and decryption. Something like what I've described here would allow me to keep these two entities more tightly coupled when compared to tracking this in a `transit/` mount.

**Comment by HridoyRoy** [comment]
Hi @captain-kark , thanks for filing this issue. This looks like an interesting feature to have!

**Comment by HridoyRoy** [comment]
Hi @captain-kark , thanks for your patience with this ticket! Do you have the steps to reproduce the behavior where reading expired CAs results in an error? I'm creating a CA with vault 1.7 with an expiry time of 1 minute. After the minute is up, I am still able to read the certificate via 
`curl \
    http://127.0.0.1:8200/v1/pki/ca/pem`

Thanks!

**Comment by captain-kark** [comment]
This was something I found while working on something that is, likely by now, a squashed commit on a branch that may or may not only exist on my machine, so your patience may be needed as I recall what happened.

I know for certain that the version of vault was `1.2.2` I will see if I can bisect this and see where I no longer have this happen once I get a test put together.

**Comment by captain-kark** [comment]
I have a makefile that creates my docker image, and then runs an init script before turning over a repl environment for testing. I can't share the source but I can use it to try a few things.

```
make Dockerfile.v1.2.2
make Dockerfile.v1.3.0
make Dockerfile.v1.4.0
make Dockerfile.v1.5.0
```

All of these came up fine. It was version 1.6.0 that started complaining about using a CN without SANs.

```
docker build --quiet --pull --build-arg PROJECT_ID=workstuff --target exampleservice -t local/exampleservice .
sha256:8fc8b2914c73cbc202e647c94a7552306c7926ec241a057ce9bba3e62702e0a8
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6
Error enabling: Post "https://localhost:8200/v1/sys/mounts/kv": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
Error enabling: Post "https://localhost:8200/v1/sys/mounts/clusters/k8s-wizzbang-doodad": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
Error tuning secrets engine clusters/k8s-wizzbang-doodad/: Post "https://localhost:8200/v1/sys/mounts/clusters/k8s-wizzbang-doodad/tune": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
Error writing data to clusters/k8s-wizzbang-doodad/config/urls: Put "https://localhost:8200/v1/clusters/k8s-wizzbang-doodad/config/urls": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
bash-5.0# 
```

Turns out this was caused by checking in a static "test.key.pem" file to run the vault server's TLS connections for a test suite. It was generated with openssl, not vault so it was being picky about missing SANs, which isn't surprising. I swapped this out for dynamic keys generated by a throwaway instance of a vault server for producing a single key pair for handling test runs. I can confirm that public certificates are being returned for expired certificate authorities, without the additional context from these warnings it implied that the root cause was elsewhere.

Thanks for your help.
