### ISSUE TITLE
Improve user experience at login page

### ISSUE THREAD

**Issue by j-zimnowoda** [hashicorp/vault#10753]
**Is your feature request related to a problem? Please describe.**
Hi, I  am getting error as in the screenshot below

<img width="639" alt="image" src="https://user-images.githubusercontent.com/17126497/105715837-5e426800-5f1e-11eb-9ba0-17a225004668.png">
I found out that it is my web browser, which blocks pop-up windows by default. Of course I have workaround for that.

Anyway, I would like to suggest to change error message, to something more actionable, e.g.:
```
Perhaps your web browser has blocked pop-up window.
```

Regardless my suggestion, I am wondering why pop-up window is needed in the first place. As far I know, authentication process can be performed in the same window/tab with many redirects.

Cheers

**Comment by rileytg** [comment]
this actually fully preventing me from logging in on mobile safari. cannot seem to figure out a workaround.

**Comment by rileytg** [comment]
nvm. here’s mobile workaround 
![Uploading 06239338-C1AF-4759-95CD-1C2F49066A04.png…]()

**Comment by rileytg** [comment]
![359848DA-40AF-4F1D-AC51-557012469ABD](https://user-images.githubusercontent.com/692817/130128733-f8261f8f-53e8-4030-a246-6faae2ae5bb7.png)

**Comment by aphorise** [comment]
Circling back - the related PR #17076 with the requested text improvement is likely to be in 1.12.0  @j-zimnowoda FYI
