### ISSUE TITLE
Consul Secrets Engine - Support Consul ACL Roles

### ISSUE THREAD

**Issue by BrandonIngalls** [hashicorp/vault#10752]
**Is your feature request related to a problem? Please describe.**

The current [Consul Secrets Engine](https://www.vaultproject.io/api/secret/consul#create-update-role) `role` does not support Consul's [ACL Roles](https://www.consul.io/api-docs/acl/roles).

I can logically assign Consul policies to a Consul role, but right now I have to replicate that logic in Vault to mimic the Consul role I already created.

See hashicorp/terraform-provider-vault#951

**Describe the solution you'd like**

Allow creation of a token that is assigned roles and policies, not just policies.

**Describe alternatives you've considered**

* Make an API call to get a list of policies currently applied to the desired Consul role
    * **NOTE:** This would likely get out-of-sync pretty fast
    * The tokens vault creates will not get changes Consul admins make to Consul roles

**Explain any additional use-cases**

Consul supports ACL roles to help reduce duplication of work, and to make management of tokens much easier.

**Additional context**

n/a

**Comment by dekimsey** [comment]
It's worth noting this would also help Consul Connect integration. Currently Service Identity (integrated, templated policies managed by Consul) aren't actual policies exposed to the user. They are only assigned internally to roles. This means when trying to configure Vault for Consul Connect services, one *cannot* use Service Identities to assign privileges. So now the operator is in the position of having to manually replicate these auto-managed policies.

Native role assignment would be desirable.

![image](https://user-images.githubusercontent.com/90741/110525971-df267f00-80da-11eb-8596-83d4cac94419.png)


```
./vault read consul/creds/magic
Error reading consul/creds/magic: Error making API request.

URL: GET https://vault-cluster.private.vault.1337.aws.hashicorp.cloud:8200/v1/consul/creds/magic
Code: 400. Errors:

* Unexpected response code: 500 (rpc error making call: rpc error making call: No such ACL policy with name "magic")
```
