### ISSUE TITLE
How to connect multiple nodes of vault behind ELB/haproxy for HA.

### ISSUE THREAD

**Issue by shubhamstriker** [hashicorp/vault#1077]
I am facing problem  connecting multiple nodes of vault behind ELB/haproxy for HA. As i am using Mysql as backend, so I can't use the HA facility provided by vault. To overcome this I am adopting the above approach. I have enabled TLS authentication using selfsigned certificates and hence facing problems. What is the remedy for this?

**Comment by lagging** [comment]
I am also facing same problem.

**Comment by jefferai** [comment]
You haven't said what problems you are encountering, but multiple simultaneous Vault servers with a non-HA backend is not supported.

**Comment by narayan8291** [comment]
I have multiple VAULT servers (master and slave) connected to my load-balancer (haproxy) and it works fine for me. Things that I have done, 

1. Two servers in the same DC with config file,
A:
backend "zookeeper" {
  address = "xxx"
  path = "yyy"
  advertise_addr = "https://A:8200"
}
listener "tcp" {
 address = "A:8200"
 tls_disable = 0
}

B:
backend "zookeeper" {
  address = "xxx"
  path = "yyy"
  advertise_addr = "https://B:8200"
}
listener "tcp" {
 address = "B:8200"
 tls_disable = 0
}

These two servers are connected to a haproxy which also sits on the same DC. I have written my own config file and this is the health check module, 

backend vaultsrvs
    	mode http
    	option httpchk GET /v1/sys/health HTTP/1.1
    	http-check expect status 200
    	server vaultmaster A:8200 check inter 1500
    	server vaultslave B:8200 check inter 1500

This architecture works great. Even if master goes down, the health checks from the haproxy can be used to detect the active guy and the slave becomes the master.

**Comment by lagging** [comment]
But we are using mysql  with generic backend and tls authentication.
Vault-serverA,Vault-serverB both points to same mysqlDB so i want to know how to setup HA proxy infront of these Vault Server and one more thing we are using self signed certificate for tls authentication.

**Comment by narayan8291** [comment]
We use our wildcard certs for tls authentication. I assume, if you have the proper health checks queried to the path /v1/sys/health of both the vault servers, you should be able to load-balance between your servers irrespective of the backend being used.

**Comment by lagging** [comment]
@narayan8291  since i am beginner can you elaborate more regarding configuration in ELB.
I am trying to use HA proxy.

client--------------->HAProxy ---------->vaultServers(server1,server2,server3) 
(Https)                      (?)                        (Https) 


---------------------------------------------------------------------------------------------------------

if you can give snapshot of your configuration file of HAProxy.

**Comment by narayan8291** [comment]
Here is my snapshot of the haproxy's config file,

global
	maxconn 4096
	user nobody
	group nobody
	stats socket /srv/var/haproxy.sock
defaults
   	log global
    	retries 3
    	option redispatch
    	maxconn 4096
	timeout connect 5000
	timeout client  10000
	timeout server  10000
frontend html
        bind *:443 ssl crt <your cert stack> ciphers <your cipher list>
       default_backend vaultsrvs
#
# Back-end definition.
#
backend vaultsrvs
    	mode http
    	option httpchk GET /v1/sys/health HTTP/1.1
    	http-check expect status 200
    	server vaultmaster <SERVER A> check inter 1500
    	server vaultslave <SERVER B> check inter 1500

listen admin_page *:42424
    mode http
    stats uri /

Both the connections (1. From client to haproxy) and (2. From haproxy to servers) are served over TLS.

**Comment by lagging** [comment]
#---------------------------------------------------------------------
# Example configuration for a possible web application.  See the
# full configuration options online.
#
#   http://haproxy.1wt.eu/download/1.4/doc/configuration.txt
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# Global settings
#---------------------------------------------------------------------
global
    # to have these messages end up in /var/log/haproxy.log you will
    # need to:
    #
    # 1) configure syslog to accept network log events.  This is done
    #    by adding the '-r' option to the SYSLOGD_OPTIONS in
    #    /etc/sysconfig/syslog
    #
    # 2) configure local2 events to go to the /var/log/haproxy.log
    #   file. A line like the following can be added to
    #   /etc/sysconfig/syslog
    #
    #    local2.*                       /var/log/haproxy.log
    #
    log         127.0.0.1 local2

    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        nobody
    group       nobody
    daemon

    # turn on stats unix socket
    stats socket /var/lib/haproxy.sock

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    log                     global
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         5000s
    timeout client          10000
    timeout server          10000
    maxconn                 4096

#---------------------------------------------------------------------
# main frontend which proxys to the backends
#---------------------------------------------------------------------
frontend https-in
    bind *:443 ssl crt /home/centos/apc-certs/bundle.pem
    log global
    default_backend             app

#---------------------------------------------------------------------
# static backend for serving up images, stylesheets and such
#---------------------------------------------------------------------
backend static
    balance     roundrobin
    server      static 127.0.0.1:4331 check

#---------------------------------------------------------------------
# round robin balancing between the various backends
#---------------------------------------------------------------------
backend app
    mode http
    option httpchk GET /v1/sys/health HTTP/1.1
    http-check expect status 200
    balance     roundrobin
    server server1 vault1.apc.com:8200 check inter 1500
    server server2 vault1.apc.com:8200 check inter 1500
  
    
-----------------------------------------------------------------------------------------------------------------------
above is my ha configuration    


But my vault is showing: 

016/02/18 16:58:58 http: TLS handshake error from 10.41.80.232:34285: tls: first record does not look like a TLS handshake
2016/02/18 16:59:00 http: TLS handshake error from 10.41.80.232:34288: tls: first record does not look like a TLS handshake
2016/02/18 16:59:01 http: TLS handshake error from 10.41.80.232:34291: tls: first record does not look like a TLS handshake
2016/02/18 16:59:03 http: TLS handshake error from 10.41.80.232:34294: tls: first record does not look like a TLS handshake
2016/02/18 16:59:04 http: TLS handshake error from 10.41.80.232:34296: tls: first record does not look like a TLS handshake
2016/02/18 16:59:06 http: TLS handshake error from 10.41.80.232:34299: tls: first record does not look like a TLS handshake
2016/02/18 16:59:07 http: TLS handshake error from 10.41.80.232:34302: tls: first record does not look like a TLS handshake
2016/02/18 16:59:09 http: TLS handshake error from 10.41.80.232:34305: tls: first record does not look like a TLS handshake




and curl request from client side showing

<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

--------------------------------------------------------------------------------------------------------------

**Comment by Shinzu** [comment]
just a guess , do you terminate ssl on the ELB and or HAProxy?

i would not do that , it is better to expose ssl only on the vault instances and let ELB/HAProxy route the plain tcp stream to vault

**Comment by lagging** [comment]
@Shinzu  you are correct . My following configuration worked thanks for suggestion



---------------------------------------------------------------------------------------------------------------------------------------




global
        log 127.0.0.1   local0
        log 127.0.0.1   local1 notice
        maxconn 4096
        chroot /var/lib/haproxy
        user haproxy
        group haproxy
        daemon
        #debug
        #quiet

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        option redispatch
        retries 3
        maxconn 2000
        contimeout      5000
        clitimeout      50000
        srvtimeout      50000

listen stats :8080
        balance
        mode http
        stats enable
        stats auth me:password


listen sslss :26
        mode tcp
        option tcplog
        balance roundrobin

        server server1 vault11.snapdeal.com:8200 check
        server server2 vault12.snapdeal.com:8200 check

**Comment by jefferai** [comment]
I'll reiterate again that this is *not* a supported Vault configuration. Attempting to point two Vault servers at the same data store when not using an HA backend is asking for serious trouble. The good news is that if you can't use an HA backend, you also don't need haproxy...easy peasy.

**Comment by lagging** [comment]
@jefferai  actually we are doing pt on vault because of #1092  issue we were trying mysql with galera. any suggestions?

**Comment by jefferai** [comment]
@lagging I don't really follow -- what do you mean by "doing pt on vault"? How does #1092 have bearing on choosing MySQL?

**Comment by lagging** [comment]
pt meaning performance testing. Actually we are using haproxy only for load balancing not for HA so that we can use single url to hit vault in case 1 gets down.

**Comment by jefferai** [comment]
>  so that we can use single url to hit vault in case 1 gets down.

But how will you have two up and running in the first place? MySQL is not an HA backend...

**Comment by lagging** [comment]
We thought like this, that in consul since request passes through single master node we planned that we will place haproxy(for load balancing in round robin fashion) they will hit two different vault server having common backend i.e mysql so we will be able to distribute load and hit a common url i.e haproxy url  and in case one vault goes down we will be able to handle request successfully.

In case of consul since request passes through single consul master node we will not be able to distribute load. Our main concern is regarding load balancing .

**Comment by narayan8291** [comment]
@lagging We have HA in VAULT by using haproxy to load balance and also to find the active server which can accept the request. Users requesting the secrets have to hit the haproxy url (single url for both the vault servers). 

In addition, we have ZooKeeper as the backend which provides HA. Even if one node goes down, data is replicated across all the nodes in the cluster so VAULT can make use of the active node to get the secrets. 

I guess, in your case HA of secrets is not possible since your instance of vault uses MySql for backend storage. If MySql goes down then Vault cannot get the secrets.

**Comment by jefferai** [comment]
@lagging No. You *cannot* do that. Vault only supports HA with HA-enabled backends, and MySQL is *not* one of them. Vault does not support active/active. It only supports active/standby.
