### ISSUE TITLE
"panic: Failed to find SetConsoleMod procedure in kernel32.dll: The specified procedure could not be found"

### ISSUE THREAD

**Issue by nabeelomer** [hashicorp/vault#108]
I tried to run it on Win 8.1, and the console gave me this error.

**Comment by mitchellh** [comment]
Fixed in master, will be part of 0.1.1!

**Comment by nabeelomer** [comment]
@mitchellh Then how do I use it right now?

**Comment by mitchellh** [comment]
We have detailed instructions on compiling from source both in the README and on the docs. Otherwise, you'll have to wait until 0.1.1

**Comment by nabeelomer** [comment]
@mitchellh ok, thanks anyway.

**Comment by nabeelomer** [comment]
@mitchellh Is there a workaround for this?

**Comment by sethvargo** [comment]
Hi @nabeelomer 

There is no workaround other than building Vault from source against master.
