### ISSUE TITLE
Glob pattern support for Rate Limit Quota

### ISSUE THREAD

**Issue by mitsutaka** [hashicorp/vault#10803]
**Is your feature request related to a problem? Please describe.**
My custom secret engine has an unauthenticated endpoint and I wanted to set a rate limit quota to limit the number of requests. According to the [documentation](https://www.vaultproject.io/api-docs/system/rate-limit-quotas#path), we can limit it using rate-limit-quota, but `path` accepts only namespace (Enterprise only) or the mount path. In other words, it is the mount path-wide configuration, so setting rate-limit-quota for my plugin limits other unnecessary endpoints of quota.

We can use [rate_limit_exempt_paths](https://www.vaultproject.io/api-docs/system/quotas-config#rate_limit_exempt_paths) to exclude rate limit quotas, but I don't think it makes sense to specify all rate limit unnecessary paths. Also, it doesn't support glob pattern.

**Describe the solution you'd like**
Suggest to support glob pattern for rate-limit-quota path to set a limit with particular endpoints. For example

```json
{
  "path": "<plugin mount path>/<endpoint>",
  "rate": 897.3,
  "interval": "2m",
  "block_interval": "5m"
}
```

In the case of an additional path that mostly defined as `:name`
```json
{
  "path": "<plugin mount path>/<endpoint>/*",
  "rate": 897.3,
  "interval": "2m",
  "block_interval": "5m"
}
```

**Describe alternatives you've considered**
I implemented rate-limit into my secret engine for particular endpoints rather than using rate-limit-quota 

**Explain any additional use-cases**

**Additional context**

**Comment by mdgreenfield** [comment]
@vishalnayak @alexanderbez, based on https://github.com/hashicorp/vault/issues/6795#issuecomment-496978932 I understand that Vault has some customers that are very latency sensitive.

I'm curious if that is why the original Rate Limit Quotas were implemented with a go-memdb index per-namespace+mount as opposed to per-namespace+endpoint and using go-memdb's `txn.LongestPrefix` on a custom index to support partial matches based on each path segment (i.e. `strings.Split(path, "/")`)? If that is the case, is the work here to add a new `memdb.CompoundMultiIndex` to support endpoints and update https://github.com/hashicorp/vault/blob/cefcaccedd12d1e1dcd269ec859d078e2ee3af4a/vault/quotas/quotas.go#L466-L499 to check for an endpoint rate limit quota first before checking per- mount, namespace or the global quotas?

**Comment by anantmishra036** [comment]
I am also looking for a solution where I can put a rate limit based on secret path.
Is there any way to achieve this or Vault doesn't support a secrets path-based rate limit?

`{
  "path": "<plugin mount path>/<path to stored secret>",
  "rate": 100,
  "interval": "60s",
  "block_interval": "60s"
}
 `

**Comment by VioletHynes** [comment]
Hey there! I just spotted this FR still open, and I wanted to report back with the good news that we support trailing globs on quotas now!

Notably, they do need to be _after_ a mount path, i.e. you can't do `*/<some-path>`, but you can do, for example `kv/<some-path>/*`!

Please see the docs for more info: https://developer.hashicorp.com/vault/api-docs/system/rate-limit-quotas#path

I'll be closing this issue as a result. Thanks for the report!
