### ISSUE TITLE
Safely backup into kubernetes pods (raft mode)

### ISSUE THREAD

**Issue by gerardgorrion** [hashicorp/vault#10804]
**Is your feature request related to a problem? Please describe.**
There's some way to do local or remote copy of our vault?, something like this configuration:
[https://www.vaultproject.io/api-docs/system/storage/raftautosnapshots](https://www.vaultproject.io/api-docs/system/storage/raftautosnapshots)
We have a helm vault deployed with integrated storage and we only can save snapshots of EBS but is no possible to restore it in new raft cluster. Some idea to do it in not enterprise version?

**Describe the solution you'd like**
We need to do automatic snapshots of vault in raft mode into kubernetes pods deployed with vault helm chart. 

Thanks!

**Comment by HridoyRoy** [comment]
Hi @gerardgorrion , thanks so much for filing this issue! 

As far as I am aware, there is no way to create a full copy of a running vault cluster via snapshots. The best way to have a copy of vault is to create a DR cluster. 

In general, storage snapshots for vault should work in the same way that any other cloud snapshots work -- https://aws.amazon.com/blogs/containers/using-ebs-snapshots-for-persistent-storage-with-your-eks-cluster/ . Any methods for deploying snapshots into EKS clusters would not be vault specific.
