### ISSUE TITLE
VAULT Upgrade - In Production

### ISSUE THREAD

**Issue by narayan8291** [hashicorp/vault#1081]
I have two vault servers master and a slave running v0.4. I decided to upgrade my vault so I brought the slave server down and uninstalled the current version of Vault in the linux box and then installed v0.5. I did the same for the master server by bringing back the slave. Is there a better way to do this ? May be a cli command to upgrade vault machines.

**Comment by jefferai** [comment]
This is the correct procedure.

**Comment by narayan8291** [comment]
@jefferai  Thank you.
