### ISSUE TITLE
vault golang api should make use of vault injector env variables

### ISSUE THREAD

**Issue by sjpotter** [hashicorp/vault#10822]
**Is your feature request related to a problem? Please describe.**

we are adding support for vault secrets to our kubernetes operator.  Instead of managing the token by hand, we are using the vault injector and sidecar to do that for us.  As we are an operator, we can't inject the needed secrets as they will depend on the content of custom resources as users specify them.  Therefore, we are using our own vault client to read the secret and parse the data out of it.  However, that means we have to build the client by hand, which can be buggy on our end.

**Describe the solution you'd like**
api.NewClient(nil) should construct a Config object out of standard environment variables if they exist.  Including setting up https with cert verification correctly, to not require each user to reinvent the wheel.  It's possible that it might also SetToken() if /vault/secrets/token exists.

**Describe alternatives you've considered**
currently I build it by hand for http (haven't gotten to https yet).  by reading VAULT_SERVICE_HOST and VAULT_SERVICE_PORT_HTTP.  while this "works", this should be functionality provided by vault.  As an example k8s's go-client can use on environment variables or on disk information to setup a client automatically from within a pod without any user intervention.

**Explain any additional use-cases**
N/A

**Additional context**
N/A

**Comment by sjpotter** [comment]
in digging into the code, I see

```
// DefaultConfig returns a default configuration for the client. It is
// safe to modify the return value of this function.
//
// The default Address is https://127.0.0.1:8200, but this can be overridden by
// setting the `VAULT_ADDR` environment variable.
//
// If an error is encountered, this will return nil.
```

so obviously there is an idea of building the client from env variables, as well as `ReadEnvironment()` which does setup based on many environment variables, but speaking from experience, doesn't seem to be what environment variables the vault injector is actually injecting into the pod.

am i doing something wrong?

**Comment by HridoyRoy** [comment]
Hi @sjpotter , 
I did a manual test where I set up a vault client and confirmed that the client can use the VAULT_ADDR environment variable, which means this might be an issue related to local setup. I am going to mark this issue as closed for now, but please feel free to ask about setup details in the HashiCorp discuss forums: https://discuss.hashicorp.com/c/vault/30. 
Thanks!

**Comment by sjpotter** [comment]
ok, but that wasn't what I said.  I agree it uses VAULT_ADDR.  vault injector on kubernetes doesn't inject that env variable, these are the variables I see injected by it

```
VAULT_AGENT_INJECTOR_SVC_PORT=tcp://10.68.17.7:443
VAULT_AGENT_INJECTOR_SVC_PORT_443_TCP=tcp://10.68.17.7:443
VAULT_AGENT_INJECTOR_SVC_PORT_443_TCP_ADDR=10.68.17.7
VAULT_AGENT_INJECTOR_SVC_PORT_443_TCP_PORT=443
VAULT_AGENT_INJECTOR_SVC_PORT_443_TCP_PROTO=tcp
VAULT_AGENT_INJECTOR_SVC_SERVICE_HOST=10.68.17.7
VAULT_AGENT_INJECTOR_SVC_SERVICE_PORT=443
VAULT_PORT=tcp://10.68.26.233:8200
VAULT_PORT_8200_TCP=tcp://10.68.26.233:8200
VAULT_PORT_8200_TCP_ADDR=10.68.26.233
VAULT_PORT_8200_TCP_PORT=8200
VAULT_PORT_8200_TCP_PROTO=tcp
VAULT_PORT_8201_TCP=tcp://10.68.26.233:8201
VAULT_PORT_8201_TCP_ADDR=10.68.26.233
VAULT_PORT_8201_TCP_PORT=8201
VAULT_PORT_8201_TCP_PROTO=tcp
VAULT_SERVICE_HOST=10.68.26.233
VAULT_SERVICE_PORT=8200
VAULT_SERVICE_PORT_HTTP=8200
VAULT_SERVICE_PORT_HTTPS_INTERNAL=8201
```
