### ISSUE TITLE
Wild cards are allowed for both service account and namespace in k8s auth role creation; documentation says otherwise...

### ISSUE THREAD

**Issue by jonZlotnik** [hashicorp/vault#10830]
**Describe the bug**
Wild cards are allowed for both service account and namespace in k8s auth role creation; documentation says otherwise...

**To Reproduce**
1. Create a k8s auth backend
2. Configure it
3. Read the [docs](https://www.vaultproject.io/api/auth/kubernetes#create-role)
4. Ignore the docs, and try putting "\*" for both service account and namespace binding restrictions
5. Realize the docs don't match the [code of the k8s auth plugin](https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/78/commits/70bc47384bedfc895d08d1df17a45b0c4ea8b6de).

**Expected behavior**
Docs should match code behaviour.

**Comment by jonZlotnik** [comment]
pls link to https://github.com/hashicorp/vault/pull/10829

**Comment by HridoyRoy** [comment]
Hi @jonZlotnik , thank you for raising the issue and adding to the docs!
