### ISSUE TITLE
Vault Raft Backup snapshots grow over time

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/vault#10838]
Today we do frequent back ups of our Vault cluster.   We are observing that the backup size grows continuously over time.

We are simply using ```vault operator raft snapshot save``` 

Here's a snippet of what we see (and this size never gets smaller, only ever bigger over time)

```
-rw-r--r-- 1 X X 206M Feb 4 11:30 snapshot-2021-02-04-113000.snap
-rw-r--r-- 1 X X 207M Feb 4 12:00 snapshot-2021-02-04-120000.snap
-rw-r--r-- 1 X X 207M Feb 4 12:30 snapshot-2021-02-04-123000.snap
-rw-r--r-- 1 X X 208M Feb 4 13:00 snapshot-2021-02-04-130000.snap
-rw-r--r-- 1 X X 209M Feb 4 13:30 snapshot-2021-02-04-133001.snap
-rw-r--r-- 1 X X 209M Feb 4 14:00 snapshot-2021-02-04-140000.snap
```

It may also be related but as these grow we do observe spikes in CPU on nodes, specifically around journal writing (it seems).

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault 1.6.1

**Comment by Tomasfire** [comment]
Same issue here. Vault version 1.7.1

**Comment by Tomasfire** [comment]
For me, issue was caused by newly created tokens that occupied space. After I decreased TTL so the token revoke between snapshot creation, size became stable.

**Comment by Raghunathareddyp** [comment]
Were applications keep on doing authentication for new tokens, instead of reusing existing valid token, what was token duration and how much duration is it right now. Just to get some rough idea.

**Comment by Tomasfire** [comment]
Script is authenticating with newly generated token and creating snapshot every hour. Default token TTL for it was 32 days, so every hour I created new token with 32 days TTL that occupied space on disk and increased size of snapshot. I changed the setting of appropriate approle to TTL 1 minute, so the token is deleted after snapshot creation finished.

**Comment by Raghunathareddyp** [comment]
Thanks for sharing this, I noticed it in vault performance tuning doc.

**Comment by ncabatoff** [comment]
Hi @idrennanvmware,

If your snapshots are growing, it's because the data in your Vault's storage is growing.  This may well indicate a problem, as some of the comments above hint at.  It's not likely to be a Vault bug, however, Vault is just doing what you've asked it to do.  I recommend if you're still observing this that you ask for help at https://discuss.hashicorp.com/c/vault/30.
