### ISSUE TITLE
Support for scheduled task plugins

### ISSUE THREAD

**Issue by axfelix** [hashicorp/vault#10839]
Hi, 

It doesn't seem currently possible to write a plugin that will run a set of scheduled tasks against the Vault API based on business logic to migrate or expire permissions without needing to authenticate to Vault remotely, which could create security headaches around deployment. Are there any plans to expand the plugin API to allow this?

Thanks!

**Comment by sgmiller** [comment]
Not at this time, though we are tracking enhancements to the plugin system.  There are some tricky security concerns about a plugin acting alone, and not via an authenticated request.
