### ISSUE TITLE
Transit API: Wrong encryption context results in 500 rather than 400

### ISSUE THREAD

**Issue by washtubs** [hashicorp/vault#10842]
**Describe the bug**

While decrypting a data key, if the client presents an encryption context which differs from the encryption context supplied on data key creation, the server should respond with a 400. At some point this changed to a 500 with a more obscure error: "cipher: message authentication failed". Our code retries on 500 which is inline with the guidance here: https://www.vaultproject.io/api-docs. Obviously retrying is not great in this case.

This appears to have been introduced somewhere between 1.4.0 and 1.6.0. 

**To Reproduce**
Start a dev server...

    vault secrets enable transit
    vault write -f transit/keys/my-key convergent_encryption=true derived=true
    vault write -f transit/datakey/plaintext/my-key context=$(echo 100 | base64)
    # obtain the ciphertext, using it unmodified while modifying the context
    vault write -f transit/decrypt/my-key ciphertext=<ciphertext> context=$(echo 101 | base64)
     
    URL: PUT http://127.0.0.1:8200/v1/transit/decrypt/my-key
    Code: 500. Errors:

    * 1 error occurred:
            * cipher: message authentication failed

**Expected behavior**

It should respond with a 400.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.6.0
* Vault CLI Version (retrieve with `vault version`): 1.6.0
* Server Operating System/Architecture: Darwin Kernel Version 19.6.0 (also tested linux)

Vault server configuration file(s):

None needed, just use the dev server

**Comment by Freyert** [comment]
I believe the error you were seeing before was:

```
Error writing data to transit/decrypt/my-key: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/transit/decrypt/my-key
Code: 400. Errors:

* invalid ciphertext: no prefix
```

**Comment by washtubs** [comment]
It's a 400 so functionally the same but the error I was seeing was:

```
Error writing data to transit/decrypt/my-key: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/transit/decrypt/my-key
Code: 400. Errors:

* invalid ciphertext: unable to decrypt
```

**Comment by NeilMadden** [comment]
I'm also running into this with Vault 1.6.2 - supplying an invalid GCM authentication tag results in a 500 error and we have to scan through the error messages looking for `message authentication failed` to detect this case.

**Comment by victorr** [comment]
I have verified that PR#13111 fixes this issue.

Following the steps in the description of the bug, we now get a 400 response code:
```
$ vault write -f transit/decrypt/my-key ciphertext=vault:v1:W500XgamNfz5OYDc9l5gBiwGtfQ9viN15E9HkMB1amvUanVCNKRGKfpu9IB9LruiRGc2hOhX/gBv0rRj context=$(echo 101 | base64)
Error writing data to transit/decrypt/my-key: Error making API request.

URL: PUT http://localhost:8200/v1/transit/decrypt/my-key
Code: 400. Errors:

* cipher: message authentication failed
```

Thank you for filing this issue.
