### ISSUE TITLE
Unable to trace profile standby mode servers

### ISSUE THREAD

**Issue by tionebsalocin** [hashicorp/vault#10845]
**Describe the bug**
Using /sys/pprof endpoints on standby mode servers does not work due to token check issue

**To Reproduce**
1. Run the following command targeting a standby mode server:
```
curl \
    --header "X-Vault-Token: ..." \
    http://standby-server:8200/v1/sys/pprof/trace
```

2. Get the following error;
`{"errors":["error performing token check: Vault is in standby mode"]}`

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`): `1.5.7`
* Vault CLI Version (retrieve with `vault version`): `1.5.7`
* Server Operating System/Architecture: `CentOS 7 5.4.93-1.el7.x86_64`

Vault server configuration file(s):

```json
{
  "api_addr": "http://server1:8200",
  "disable_mlock": true,
  "ui": true,
  "plugin_directory": "/var/opt/vault/plugins/",
  "listener": {
    "tcp": {
      "address": "0.0.0.0:8200",
      "tls_disable": "true"
    }
  },
  "storage": {
    "consul": {
      "address": "http://localhost:9500",
      "token": "..."
    }
  },
  "ha_storage": {
    "consul": {
      "address": "http://localhost:9500",
      "path": "ha-vault",
      "token": "..."
    }
  },
  "telemetry": {
    "prometheus_retention_time": "24h",
    "disable_hostname": true
  }
}
```

**Additional context**
Vault runs on 3 different servers
Storage backend is consul

**Comment by HridoyRoy** [comment]
I _think_ this is a bug, and the correct behavior should be that the request is routed to the leader.

**Comment by ncabatoff** [comment]
I disagree with the solution being routing the request to the leader: we want to be able to profile standby nodes too.  I see two easy options: add an "unauthenticated" listener-level option to allow profiling without a token, like we do for metrics.  Option 2: listen for SIGUSR1 like go-metrics does, and in addition to our current behaviour of dumping metrics to the logs, if some new config is enabled, also generate a `vault debug` style dump in the filesystem where the config specifies to put it.

Another option that's more involved but shouldn't be ruled out: add an RPC method that allows standbys to ask the active node to verify a token.  Then we can support the same pprof interface that's already being used on the active node and on perf standbys, without needing new config.

**Comment by ncabatoff** [comment]
We went with the unauthenticated listener option to allow profiling without a token, in #11324.  This can be used for any node, including the leader, which addresses the problem described in this issue.
