### ISSUE TITLE
Lowercase conversion is causing inconsistent behaviour in PKI backend

### ISSUE THREAD

**Issue by gnugnug** [hashicorp/vault#10852]
**Describe the bug**
Our users have a habit of writing hostnames in uppercase (eg MYSERVER.INT). When issuing certificates through the PKI backend of Vault this has odd outcomes, because Vault converts the subject alternative names to lowercase via `ParseDedupLowercaseAndSortStrings()`, but leaves the common name as it is. After that both the subject alternative names and the common name are sent through `validateNames()`, which performs a case-senstive comparison.

That means the SANs are converted to lowercase before the case-senstive validation takes place and the common name is converted to lowercase after this validation. In the end certificate requests are allowed or denied depending on the order of the DNS names in the certificate, which is confusing to the users.

**To Reproduce**
Preparations:
```
>vault version
Vault v1.6.2
>vault secrets enable pki
Success! Enabled the pki secrets engine at: pki/
>vault write pki/root/generate/internal common_name=my-root
certificate      -----BEGIN CERTIFICATE-----
[...]
>vault write pki/roles/example allowed_domains="example.net, EXAMPLE.COM" allow_bare_domains=true
Success! Data written to: pki/roles/example
```
Request a certificate:
```
>vault write pki/issue/example common_name="EXAMPLE.COM" alt_names="example.net" ttl=1
[Success]
```
Request the same certificate with DNS names in reversed order:
```
>vault write pki/issue/example common_name="example.net" alt_names="EXAMPLE.COM" ttl=1
Error writing data to pki/issue/example: Error making API request.
* subject alternate name example.com not allowed by this role
```
One could argue that allowed_domains should not contain upperspace characters, but this results in other inconsistent behaviour:
```
>vault write pki/roles/example allowed_domains="example.net, example.com" allow_bare_domains=true
Success! Data written to: pki/roles/example
```
Certificate request for two DNS names succeeds:
```
>vault write pki/issue/example common_name="example.com" alt_names="EXAMPLE.NET" ttl=1
[Success]
```
If we remove example.com it suddenly fails:
```
>vault write pki/issue/example common_name="EXAMPLE.NET" ttl=1
Error writing data to pki/issue/example: Error making API request.
* common name EXAMPLE.NET not allowed by this role
```

**Expected behavior**
`validateNames()` should compare DNS names in a case insensitive way, because DNS names **are** case insenstive. As a result PKI roles that allow EXAMPLE.COM, would allow requests containing the DNS name example.com or eXaMpLe.CoM as well, since it is not possible that they refer to different hosts.
In the end, Vault puts the DNS names in the resulting certificates in lowercase anyway, so it is not meaningful that Vault performs the validation before this step in a case sensitive way.

If this is unwanted, at least alt_names and common_name should be treated the same. Either convert both to lowercase before performing the comparison, or none of them.

**Comment by Freyert** [comment]
Just to add more info to the ticket case insensitive comparisons for DNS records are specified in [RFC 1035: DOMAIN NAMES - IMPLEMENTATION AND SPECIFICATION](https://tools.ietf.org/html/rfc1035) section 2.3.3.

**Comment by HridoyRoy** [comment]
Hi folks,
Thanks so much for the PR! I've added a quick comment. Thanks again!
