### ISSUE TITLE
Raft auto-join skip tls verify

### ISSUE THREAD

**Issue by Hrachos** [hashicorp/vault#10854]
**Describe the bug**
using Vault 1.6 raft auto-join feature with a self-signed TLS certificate produces an error: 
```
join attempt failed: error="error during raft bootstrap init call: Put "https://172.15.79.115:8200/v1/sys/storage/raft/bootstrap/challenge": x509: cannot validate certificate for 172.15.79.115 because it doesn't contain any IP SANs
```
Despite the VAULT_SKIP_VERIFY flag being set in the vault systemd unit.

**Expected behavior**
The x509 error should be ignored and the raft cluster should be joined.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.6.0
* Vault CLI Version (retrieve with `vault version`): 7ce0bd9691998e0443bc77e98b1e2a4ab1e965d4
* Server Operating System/Architecture: Ubuntu 

Vault server configuration file(s):

```hcl
retry_join {
        auto_join = "provider=aws region=${aws_region} addr_type=private_v4 tag_key=Name tag_value=vault.${environment}"
 }
```

**Additional context**
I could add the relevant IP addresses as SANs to the certificate, the problem is that the IPs can change on node failure, as we are running vault in an auto scaling group in AWS.

**Comment by ncabatoff** [comment]
Hi @Hrachos,

VAULT_SKIP_VERIFY only applies to the CLI, and isn't used for raft join.  I don't know if it's possible to skip tls verifification with raft join and https, but if so it's ill-advised.  

Instead I suggest you look at these not-yet-merged docs: https://github.com/hashicorp/vault/pull/10865

**Comment by bartdzkan** [comment]
Ran into this issue as well. I had to use an unmanaged group, set the VM instance names, add the localhost name  to the SAN cert. Not ideal but it works.

**Comment by Hrachos** [comment]
We have solved the issue using the loadbalancer approach, which works well enough.

**Comment by ncabatoff** [comment]
Great, glad you found a solution that works for you!
