### ISSUE TITLE
After unseal need to add sleep statement before login

### ISSUE THREAD

**Issue by ravi-stiwari** [hashicorp/vault#10878]
**BUG DESCRIPTION**
After unsealing the vault whenever I try to login using userpass it returns error but if I add wait for 1 second then it logs me in. Tried using Python (hvac) and Golang (github.com/hashicorp/vault/api) both are having same issue.

**To Reproduce**
1. Unseal using 3 keys
2. Try to login immediately
3. See error

**Expected behavior**
After unsealing the vault there should not be any wait required explicitly.

**Environment:**
* Vault Server Version (retrieve with `vault status`):

Key                    Value
---                    -----
Seal Type              shamir
Initialized            true
Sealed                 false
Total Shares           5
Threshold              3
Version                1.6.1
Storage Type           s3
Cluster Name           vault-cluster-b4b8b47e
Cluster ID             XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX
HA Enabled             true
HA Cluster             https://XXX.XX.XX.XX:8201
HA Mode                standby
Active Node Address    http://vault-server.example.com

* Vault CLI Version: Vault v1.6.1 (6d2db3f033e02e70202bef9ec896360062b88b03)

* Server Operating System/Architecture: CentOS Linux release 7.9.2009 (Core) x86_64 GNU/Linux

Vault server configuration file(s):

```hcl
#ui = true
#
#log_level = "ERR"
#
#api_addr = "http://vault-server.example.com"
#
#cluster_addr = "http://XXX.XX.XX.XX:8201"
#
#storage "s3" {
#  access_key = "XXXXXXXXXXXXXXX"
#  secret_key = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
#  bucket     = "vault-storage"
#  region     = "us-east-1"
#  path       = "store"
#  kms_key_id = "XXXXXXX-XXXXX-XXXX-XXXX-XXXXXXXX"
#}
#
#ha_storage "dynamodb" {
#  access_key = "XXXXXXXXXXXXXXX"
#  secret_key = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
#  ha_enabled = "true"
#  region     = "us-east-1"
#  table      = "vault-ha-storage-lock-only"
#  kms_key_id = "XXXXXXX-XXXXX-XXXX-XXXX-XXXXXXXX"
#}
#
#listener "tcp" {
# address     = "XXX.XX.XX.XX:8200"
# tls_disable = 1
#}

```

**Below is the python code I had to add try catch to get it working if i remove seal statement then it works fine**
#!/usr/bin/python3

import hvac
import time
import boto3

client = hvac.Client(url="http://vault-server.xyz.com")

#These are three keys which will be used to unseal the vault
keys = ['abc','def','geh']

if client.sys.is_sealed():
  client.sys.submit_unseal_keys(keys)
if not client.is_authenticated():
  try:
    #This fails
    client.auth_userpass("admin-user","password")
  except hvac.exceptions.InternalServerError as e:
    #This seems like a bug it takes around a second after unsealing the vault sometimes.
    print("Going to retry after 1 second...")
    time.sleep(1)
    client.auth_userpass("admin-user","password")
client.sys.seal()

**Comment by HridoyRoy** [comment]
Hi @ravi-stiwari , vault operations can only be performed when vault is unsealed, so the code needs to check whether vault has finished unsealing before performing operations against vault. I am going to close this issue, but please feel free to reopen it if vault login does not work after vault returns the unseal status. 
Thanks!
