### ISSUE TITLE
static open(url: string)

### ISSUE THREAD

**Issue by oudomskn** [hashicorp/vault#10874]
**Describe the bug**

**To Reproduce**
1. Run `vault write ...`
2. Run `vault login....`
3. See error

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by HridoyRoy** [comment]
Hi @oudomskn , I'm going to close this git issue, but please feel free to reopen with more details. Thanks!
