### ISSUE TITLE
LDAP secret backend

### ISSUE THREAD

**Issue by dmzaytsev** [hashicorp/vault#1087]
It would be great to have a LDAP secret backend.

A possible use case is an application that has own users management and uses LDAP for users authorization. The application running inside a docker container. Right now we need to set a bind DN for this application and change it periodically.

Using the LDAP secret backend will allow us to create a new Bind DN on start of the application and delete it after stop. The application script can be authorized against Vault using the App ID auth backend.

**Comment by vishalnayak** [comment]
Hi @dmzaytsev, thanks for the suggestion. This is already being tracked here https://github.com/hashicorp/vault/issues/546.

**Comment by jefferai** [comment]
This is a separate ask; #546 is tracking enhancements to the LDAP auth backend. @dmzaytsev is asking for a secret backend to generate LDAP credentials, similar to the database backends.

**Comment by dmzaytsev** [comment]
@jefferai that's exactly what I meant, thanks

**Comment by mattroeske** [comment]
+1

**Comment by dmzaytsev** [comment]
@jefferai if you have accepted this ticket will it be assigned to a milestone or maybe be labeled as enhancement ?

**Comment by sepiroth887** [comment]
👍 we have a need for this as well. If I find the time I might take a stab at it. @dmzaytsev any particular flavor? OpenLDAP vs Microsoft AD? 

Reason I ask is that for example group types can be significantly different. 

What I'm thinking right now would be the following features: 

1) Create user and creds on the fly (duh. i guess :) )
2) Assign a user to either a posixGroup or groupOfNames
3) First iteration use Vault to track and remove users by tracking them via Vault's storage backend
  3.1) Use LDAP to expire password 
  3.2) Investigate LDAP user cleanup natively.
4) Profit!

**Comment by dmzaytsev** [comment]
@sepiroth887 I need ldap backend to use with Openldap. But it doesn't matter.
I believe we need a customizable plugin.

* create user and assign it to a group using a template of the user entry(and group) , maybe in json, something like 
```
{
"dn": "cn:$username$,ou=people,dc=example,dc=com"
"attributes": { "objectclass": "inetOrgPerson",
"cn": "$username$",
"sn": "autocreated account",
"userpassword": "$password$"},
"groupDn":"ou=read,ou=apps,ou=groups,dc=example,dc=com",
"groupMemberAttribute":"member"
}
```
* detete the user entry and maybe remove it from the group

@sepiroth887 @jefferai what do you think?


@sepiroth887 unfortunately  I'm not familar enough with Golang and Vault doesn't allow to use plugins.
Anyway it would be great if you  could implement this backend

**Comment by jefferai** [comment]
@dmzaytsev I think that there is a high probability that until Vault gains a plugin mechanism this is unlikely to be merged, unless this can be done in a way that is likely to work for nearly all LDAP servers without the code being awful. The authentication backend for LDAP is already problematic enough simply trying to do a user and group search; adding user/group creation and revocation into the mix gives me the willies.

**Comment by sepiroth887** [comment]
Yea the various flavors of LDAP make this really annoying. 
Though major :+1 on the plugin model. 

Im thinking for the first iteration vanilla openLDAP and MS AD could be a start. That is if the golang LdAP libraries are any good

**Comment by sepiroth887** [comment]
Ill report back when I got a rough idea how and when we might try an implementation.

**Comment by kasimon** [comment]
We also would have a lot of interest for a dynamic secret backend for LDAP accounts.

**Comment by croessner** [comment]
Any chance to get this feature implemented? 😊

**Comment by 2994186010** [comment]
Is there available LDAP secret backend now?

**Comment by tomhjp** [comment]
Thanks for the interest, as of early this year we now have an OpenLDAP secrets engine - docs [here](https://www.vaultproject.io/docs/secrets/openldap). It supports automatic and manual password rotations of static roles, as well as root credential rotation.

It does not currently support the dynamic role creation mentioned in a few comments here, but feel free to request that over in the the [plugin repo](https://github.com/hashicorp/vault-plugin-secrets-openldap).
