### ISSUE TITLE
PostgreSQL secret backend connection_url doesn't seem to work

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#1089]
It looks like `value` was deprecated for setting the connection url in favor of `connection_url`, but `connection_url` does not parse the string as a connection string.

Steps to reproduce:

1. Start up a basic pg instance
2. `vault mount postgresql`
3. `vault write postgresql/config/connection connection_url="postgres://postgres@localhost/myapp"
4. The connection will fail because it's trying to connect with `$USER` that vault is running, not the supplied user connection string

I think this is because value was deprecated, but it's still used as part of the "validation" procedure (and connection_url is not).

**Comment by jefferai** [comment]
Probably can copypasta from #1096. Not ideal, but things are going to change in the near future anyways.
