### ISSUE TITLE
Policy Prioritization Is Broken.  Permissions For Broad Paths Supersede Those For Specific Paths

### ISSUE THREAD

**Issue by BinaryWizard904** [hashicorp/vault#10905]
**Describe the bug**
According to your documentation on [Policy Syntax](https://www.vaultproject.io/docs/concepts/policies#policy-syntax), explicit paths without wildcards should take precedence over those with wildcards.  However under Vault v1.6.2, the prioritization is inverted, and the more specific path is ignored.

For example, the example policy from your Policy Syntax documentation (linked above) claims that you can grant broad permissions to "secret/*" while denying access to "secret/super-secret" via the following policy.
```HCL
# This section grants all access on "secret/*". Further restrictions can be
# applied to this broad policy, as shown below.
path "secret/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

# Even though we allowed secret/*, this line explicitly denies
# secret/super-secret. This takes precedence.
path "secret/super-secret" {
  capabilities = ["deny"]
}
```
Let's try this out shall we.

**To Reproduce**
1. Start a fresh development instance of the official Docker Vault image and login as root.
2. Run `vault kv put secret/super-secret my=secret` to create a test key.
3. Create the `test-policy` policy by running
```HCL
vault policy write test-policy - << EOF
# This section grants all access on "secret/*". Further restrictions can be
# applied to this broad policy, as shown below.
path "secret/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
# Even though we allowed secret/*, this line explicitly denies
# secret/super-secret. This takes precedence.
path "secret/super-secret" {
  capabilities = ["deny"]
}
EOF
```
4. Run `vault token create -policy=test-policy` to create a token constrained by this policy.
5. Run `vault login <token>` to login using the token you just generated.
6. Run `vault kv get secret/super-secret` and observe that despite being denied all permissions on that key, you are still able to view it.
7. Run `vault kv put secret/super-secret not=secret` and observe that you were able to edit this key, despite being denied all permissions on it.

**Expected behavior**
Tokens constrained by the policy above should be able to create, read, update, delete, and list all children within secret/* _except_ "secret/super-secret", to which access should be denied.

**Environment:**
* Vault Server Version (retrieve with `vault status`):

 Key | Value
------ | -------
Seal Type | shamir
Initialized | true
Sealed | false
Total Shares | 1
Threshold | 1
Version | 1.6.2
Storage Type | inmem
Cluster Name | vault-cluster-8dad5aa3
Cluster ID | 17072b58-d4cc-94fe-e2e9-e6849e945c2a
HA Enabled | false
* Vault CLI Version (retrieve with `vault version`): Vault v1.6.2 (be65a227ef2e80f8588b3b13584b5c0d9238c1d7)
* Server Operating System/Architecture: The latest version of the [Official Docker Vault Image](https://registry.hub.docker.com/_/vault/).
* Vault server configuration file(s): N/A, applies to the default development environment.

**Comment by ncabatoff** [comment]
Hi @BinaryWizard904,

I suggest you try using the `-output-curl-string` option to verify that the paths being hit by the vault CLI match what you think they are:

```
$ vault kv get -output-curl-string secret/foo
curl -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" http://localhost:8200/v1/secret/data/foo
```

As you can see, with KVv2 the paths used for accessing secrets aren't quite what you would expect.  More details and examples here:  https://www.vaultproject.io/docs/secrets/kv/kv-v2#acl-rules

**Comment by HridoyRoy** [comment]
Hi @BinaryWizard904 , echoing @ncabatoff , kv2 operations prefix paths with "secret/data". So, `vault kv put secret/super-secret not=secret` writes to `secret/data/super-secret`, which is allowed by the policy above. 
Thanks!
