### ISSUE TITLE
Vault install on Docker fails with "Operation not permitted"

### ISSUE THREAD

**Issue by bnsh** [hashicorp/vault#10924]
**Describe the bug**
I made a very simple docker file to install vault, when I run it as
    `/usr/bin/vault --version`

from within the docker, I get a "bash: /usr/bin/vault: Operation not permitted"... If I run it with
    `docker container run --rm binesh/single /usr/bin/vault --version`
    
 instead, I get a slightly more helpful `standard_init_linux.go:211: exec user process caused "operation not permitted"`

In digging further, I found that if I tell the docker to simply re-install vault, then it works. 
**To Reproduce**
1. Here's my gist: [https://gist.github.com/bnsh/b3fbe0214b9a26e09fc8de43b25f5579](https://gist.github.com/bnsh/b3fbe0214b9a26e09fc8de43b25f5579)

**Expected behavior**
I expect vault to just work on a single install.

**Environment:**
* Vault Server Version (retrieve with `vault status`): Not applicable
* Vault CLI Version (retrieve with `vault version`): Vault v1.6.2 (be65a227ef2e80f8588b3b13584b5c0d9238c1d7)
* Server Operating System/Architecture: Linux client 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by HridoyRoy** [comment]
Hi @bnsh ,
I'm pretty sure this issue is with the ubuntu image and not with Vault. Running vault from ubuntu via:

`FROM ubuntu

LABEL maintainer="Binesh Bannerjee <binesh_binesh@hotmail.com>"

RUN \
	apt update && apt install -y wget unzip \
	&& wget https://releases.hashicorp.com/vault/1.6.2/vault_1.6.2_linux_amd64.zip \
	&& unzip vault_1.6.2_linux_amd64.zip	

CMD ["/bin/bash"]`

works with only 1 installation and does not require a reinstall. 

I'm going to close this issue. For followup questions on vault setup, check out our [discuss forums](https://discuss.hashicorp.com/c/vault/30). Thanks!

**Comment by elasticdotventures** [comment]
It's worth mentioning this happens on a fresh install using:
```
sudo apt-get install vault
```

The vault_1.6.2_linux_amd64.zip reference works properly, but the default ubuntu version did not.

**Comment by ieugen** [comment]
I've also encountered this in docker ubuntu-20.04 today. 
Reinstalling RUN apt-get install --reinstall -y vault seems to fix this - at least inside the container. Building the docekr image ..

**Comment by dustindortch** [comment]
Same in a CentOS container using the RHEL repo from Hashicorp.

**Comment by gianluca-mascolo** [comment]
Hi,
I'm installing vault 1.7.3 on Debian Buster using Hashicorp apt repository and I experienced the same problem.
```
devops@8440a39205da:/$ vault --version
bash: /usr/bin/vault: Operation not permitted
devops@8440a39205da:/$
```
After inspecting the deb package I found that in the post-install phase a cap_ipc_lock capabilities is added to vault executable.
Executing the container with  `--cap-add=CAP_IPC_LOCK` solve the issue
Additional reference for this behaviour may be found here. https://www.vaultproject.io/docs/configuration

**Comment by wagnerbianchijr** [comment]
I came here researching about the same issue, and the --reinstall fixed it. But I'm sure it should be revisited at some point.
```
root@1a4a1cf7f2ad:/# vault
bash: /usr/bin/vault: Operation not permitted
--
root@1a4a1cf7f2ad:/# apt-get install --reinstall -y vault
Reading package lists... Done
Building dependency tree
Reading state information... Done
--
root@1a4a1cf7f2ad:/# vault
Usage: vault <command> [args]

Common commands:
    read        Read data and retrieves secrets
    write       Write data, configuration, and secrets
    delete      Delete secrets and configuration
    list        List data or secrets
    login       Authenticate locally
    agent       Start a Vault agent
    server      Start a Vault server
    status      Print seal and HA status
    unwrap      Unwrap a wrapped secret
...

```

**Comment by kinvaris** [comment]
Similar issue on CentOS 8 from [Dockerhub](https://hub.docker.com/layers/centos/library/centos/centos8.4.2105/images/sha256-8bcb67d4c816e16f79bdea8079c5e30e88f404f4aa8fa124245864830d7852d2?context=explore): `centos:centos8.4.2105`

**Comment by esemeniuc** [comment]
I can confirm that `setcap -r /usr/bin/vault` works for me

**Comment by EtienneBruines** [comment]
@HridoyRoy could this issue be reopened? The issue seems to be within `vault`, or at least the installation process of `vault` / packaging. https://github.com/hashicorp/vault/tree/main/.release/linux

 `apt-get install vault` should "just work", even within docker.

**Comment by kwaegel** [comment]
`setcap -r /usr/bin/vault` fixes this issue for me with Ubuntu 20.04 inside Docker. It would be nice if this extra step wasn't needed.

**Comment by sj-porter-knime** [comment]
I also experienced this. Adding `RUN apt-get install --reinstall -y vault` to the Dockerfile (after the original install) is a workaround that worked for me.

**Comment by eytanhanig** [comment]
@HridoyRoy This issue still occurs intermittently for fresh Vault installs on AWS Linux, as well as other distros identified above. Please reopen the issue.

**Comment by hsimon-hashicorp** [comment]
Hi folks, I wanted to bring your attention to a comment from a user above who was able to resolve this: https://github.com/hashicorp/vault/issues/10924#issuecomment-872323330
If that does not work, please let me know.

**Comment by SamSpiri** [comment]
> Hi folks, I wanted to bring your attention to a comment from a user above who was able to resolve this: [#10924 (comment)](https://github.com/hashicorp/vault/issues/10924#issuecomment-872323330) If that does not work, please let me know.

as workaround it works.
but in original vault image additional line must be added:
RUN setcap -r /usr/bin/vault

one line to fix... no need to keep waisting thousand workhours worldwide for investigation of hashicorp's bugs.

**Comment by eytanhanig** [comment]
@HridoyRoy This issue still occurs intermittently for fresh Vault installs on AWS Linux, as well as other distros identified above. Please reopen the issue.

**Comment by hsimon-hashicorp** [comment]
The reason we don't bake `setcap` into the images is because it can cause security issues. The team is discussing how to handle this, however, in the meantime I'm going to lock the thread. Thanks for understanding.

**Comment by hsimon-hashicorp** [comment]
Please note: we hear that this is an inconvenience. However, baking in the set cap changes requested here would make Vault less secure. The workaround is documented here. You may choose to make this choice for yourself, however, this is not a choice that the Vault engineers will choose to make. Thank you for understanding.
