### ISSUE TITLE
agent: accept log_level in the config

### ISSUE THREAD

**Issue by calvn** [hashicorp/vault#10928]
**Is your feature request related to a problem? Please describe.**
Agent currently accepts log level via the `-log-level` flag. We should also make it so that this can be provided in the config.

**Describe the solution you'd like**
Agent config accepts and honors `log_level` in its config.

**Describe alternatives you've considered**
The current alternative is to provide this via the option flag.

**Explain any additional use-cases**
Be able to declare log level through code/config. This also allows the log level to be re-set through a config update + SIGHUP, for instance, if/when that's implemented.

**Additional context**
N/A

**Comment by VioletHynes** [comment]
This was implemented as part of https://github.com/hashicorp/vault/pull/18031!
