### ISSUE TITLE
Method to issue ssh cert with full set of allowed principals

### ISSUE THREAD

**Issue by candlerb** [hashicorp/vault#10946]
**Is your feature request related to a problem? Please describe.**

I'm trying to automate cert issuance defined by central policy.  I'm happy for the client to know which ssh role they need to access, but I'm trying to avoid duplicate configuration where the client also has to know what principals to ask for.

Therefore, I would like a way to issue an ssh cert with all available principals to the user, when they don't know which principals to ask for.  At the moment they get a certificate with no principals, which isn't very useful[^1], or else a static `default_user` which does not support template expansion.

I tried the following:

```
  "allowed_users": "root,{{identity.entity.metadata.ssh_username}}",
  "allowed_users_template": true,
  "default_user": "root,{{identity.entity.metadata.ssh_username}}",
```

Result:

```
$ vault write -field=signed_key ssh-user-ca/sign/ssh-admin public_key=@$HOME/.ssh/id_rsa.pub >alice.cert
Error writing data to ssh-user-ca/sign/ssh-admin: Error making API request.
...
Code: 400. Errors:

* {{identity.entity.metadata.ssh_username}} is not a valid value for valid_principals
```

**Describe the solution you'd like**
I suggest being able to set

```
  "default_user": "*"
```

to mean "the default user is the same as all `allowed_users`".

`*` already has a special meaning (as in `"allowed_users": "*"`), so it seems very unlikely that anyone would actually want to issue a cert with `*` as the principal by default.

**Describe alternatives you've considered**

* Being able to template `default_user`, so it can be configured identically to `allowed_users`, would work.  It's messier, although it might be useful to have a default set of principals which is smaller than the allowed set.  Also, I'm unsure if `default_user` currently permits a *list* of principals in CA mode, but if necessary it could be changed to do this.
* If `default_user` is empty *and* the incoming request has no principals, then issue a cert containing all principals in `allowed_users`. This would be a change of behavior, although I would argue that the current behavior in this scenario (issue a certificate with no principals) is not useful
* I could grant the client read access to the signing policy, but then they'd still have to expand strings like `{{identity.entity.metadata.ssh_username}}` themselves, which means another request to fetch their own entity metadata plus the logic to decide how to interpolate it.
* I could put the set of principals to request in a separate item of entity metadata.  The client would still have to request their own metadata, and I'd need to keep the extra metadata up to date (but at least it's centrally controlled)
* I could create a separate ssh role for every user (and a separate policy), so they get their custom `default_user`.  Ugh.

**Explain any additional use-cases**
N/A

**Additional context**
[^1] User certificates without principals cannot be used to authenticate with `TrustedUserCAKeys`, as it always requires at least one principal in the certificate. From `sshd_config(5)`:

> Note that certificates that lack a list of principals will not be permitted for authentication using TrustedUserCAKeys

AFAICS, the only place you can use such certificates is if you add an entry to `~/.ssh/authorized_keys` which specifies `cert-authority` without any `principals="..."`.  That would allow *anyone* to login to your account who has a certificate signed by that CA (regardless of what principals it does or does not contain), which is very insecure.

I'd quite like to be able to disable the issuing of certs with no principals entirely, but that would be a separate feature request.

**Comment by robison** [comment]
Any change of this moving forward? Happy to submit a PR to resolve this.

**Comment by cipherboy** [comment]
@robison I think it makes sense from my PoV. If you think it'd be fairly easy, happy to review a PR, but if its non-trivial we might want to champion it internally a little more (to make sure we understand the security impacts first).

**Comment by candlerb** [comment]
How are you planning to provide this?

* `"default_user_template": true`
* `"default_user: "*"`
* something else?

**Comment by cipherboy** [comment]
@candlerb Did you happen to see #16350 and its corresponding PR? Did it happen to solve your use case, or is there more work you wanted? 

I realized you said it was messier, but I only just now realized its also already implemented and considered :-) Just curious if you've had a chance to try it out.

**Comment by candlerb** [comment]
I saw that, but haven't tried it.  Whether it will work for me depends on whether the templated "default_user" allows a comma-separated *list* of principals, like "allowed_users".

The [documentation](https://www.vaultproject.io/api-docs/secret/ssh#parameters-2) says:

> For the CA type, if you wish this to be a valid principal, it must also be in `allowed_users`.

This implies to me that only a single principal is allowed, but as I say, I've not tested it yet.

**Comment by cipherboy** [comment]
Ah that's fair. I think #16622 is what allows multiple principals, I'll have to see if someone has cycles to take a look at that one.

**Comment by candlerb** [comment]
Tried it with vault v1.11.3 and it seems the `default_user_template` isn't available there yet.

However, if I set default_user to a list like "foo@baz,bar@baz" then I *do* get a certificate with two separate principals.  So this looks promising.

#16622 is something else: it's about whether `allowed_users` can contain a single expansion element like `{{identity.entity.metadata.blah}}` which returns a comma-separated list.

**Comment by cipherboy** [comment]
Right sorry, this is in the not-yet-released 1.12, so you'd have to build it from `main` or pull one of the builds from a recent GH Actions run.

I think, if I recall the earlier PR to allow `default_user_template` correctly, it'd have the same bug with `allowed_users`, wherein `default_users` template would only expand to one principal, but maybe I'm misremembering.

**Comment by candlerb** [comment]
Currently behaviour of `allowed_users` isn't exactly a bug.  It does work if you do:

```
"allowed_users": "www-data,{{identity.entity.metadata.foo}},{{identity.entity.metadata.bar}}"
```

Where it fails is if you want a single expanded value to contain a comma-separated list itself, and that's what #16622 addresses.

This gets pretty ugly if you want to permit individual values which contain commas.

TBH, string-based templating is an utter nightmare for this, especially for a security-critical product like Vault - but given how long the product has been around, I can understand why it was done this way when it was.

If it were started today, then I'd suggest using Jsonnet, where you can explicitly build list values instead of strings:

```
"allowed_users": ["www-data", identity.entity.metadata.username] + identity.entity.metadata.extra_principals
```

**Comment by candlerb** [comment]
Tested with v1.12.4: `default_user` together with `"default_user_template": true` works perfectly. If you set `default_user` to be identical to `allowed_users`, and the client doesn't specify valid-principals, then they get a certificate with the full set of allowed principals.

Thank you - I think this issue can now be closed!
