### ISSUE TITLE
Recovery is not working with raft and auto unseal 

### ISSUE THREAD

**Issue by Slm0n87** [hashicorp/vault#10950]
**Describe the bug**
I have a standalone vault A running in shamir mode which is desired to to auto unseal other clusters only.  
Then I have a raft cluster vault B with 3 nodes running which is using vault A as transit for auto unsealing.  

If I would loose the vault A my understanding of the Recovery mode is that I am able to open a single raft node of vault B and recover the raft cluster.

**To Reproduce**
1. Stop all 4 instances (1x standalone vault A & 3x raft nodes B)
2. Try to start one node aut of raft cluster B in recovery mode
3. Error:
```bash
~# /usr/bin/vault server -recovery -config=/etc/vault.d/vault.hcl  -log-level=trace
Error parsing Seal configuration: Put "http://<IP-of-standalone-vault-A>:8200/v1/transit/encrypt/unseal_key": dial tcp <IP-of-standalone-vault-A>:8200: connect: connection refused
 [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=

```

**Expected behavior**
Vault on the node should start to be able to continue with recovery-token generation...

**Environment:**
* Vault Server Version (retrieve with `vault status`): v1.6.2
* Vault CLI Version (retrieve with `vault version`):v1.6.2
* Server Operating System/Architecture: Ubuntu

Vault server configuration file(s):
Config of raft cluster vault B node:
```hcl

storage "raft" {
  path    = "/space/raft-storage/my-nodename"
  node_id = "my-nodename"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  cluster_address = "10.1.2.3:8201"
  tls_disable = "true"
}

seal "transit" {
  address = "http://10.3.2.1:8200"
  token = "xxxx"
  disable_renewal = "true"
  // Key configuration
  key_name           = "unseal_key"
  mount_path         = "transit/"
}

cluster_addr = "http://10.1.2.3:8201"
api_addr = "http://my-ha-vault.local:8200"
cluster_name = "vault"
raw_storage_endpoint = "true"
ui = "true"
```

**Additional context**
I also tried to change my config file by commenting out the seal transit block, to that vault does not try to connect to the unseal node, but then I get a different error:
```bash
~# vault operator generate-root -generate-otp -recovery-token
[ERROR] core: barrier seal type does not match expected type: barrier_seal_type=transit loaded_seal_type=shamir
Error getting root generation status: Error making API request.

URL: GET http://web-infra-test-vault-03-ljwe90wg:8200/v1/sys/generate-recovery-token/attempt
Code: 500. Errors:

* barrier seal type of "transit" does not match expected type of "shamir"
```

**Comment by ncabatoff** [comment]
Hi @Slm0n87,

> If I would loose the vault A my understanding of the Recovery mode is that I am able to open a single raft node of vault B and recover the raft cluster.

I'm afraid that's not the case.  If you lose access to the system that supports your auto-unseal, there is no way to regain access to your Vault data once it seals.

**Comment by Slm0n87** [comment]
Thanks for the reply and clarification.  
In the meantime it makes sense to me that the raft cluster an not be unsealed, because the master key only exists in the transit of vault A.
