### ISSUE TITLE
[Documentation] ssh ca default_extensions: map, or list of maps?

### ISSUE THREAD

**Issue by candlerb** [hashicorp/vault#10958]
**Describe the issue**
The documentation for [api/secret/ssh](https://www.vaultproject.io/api/secret/ssh#parameters-2) says that `default_extensions` for an ssh role is a `map<string|string>` with default None.  There is an example later in the page:

```
  "default_extensions": {},
```

However, the documentation at [secrets/ssh/signed-ssh-certificates](https://www.vaultproject.io/docs/secrets/ssh/signed-ssh-certificates#signing-key-role-configuration) shows it as a *list of maps*:

```
  "default_extensions": [
    {
      "permit-pty": ""
    }
  ],
```

Put together, this implies there could be three different ways to set multiple extensions:

*Case 1*

```
  "default_extensions": {
    "permit-pty": "",
    "permit-agent-forwarding": ""
  },

```

*Case 2*

```
  "default_extensions": [
    {
      "permit-pty": "",
      "permit-agent-forwarding": ""
    }
  ],
```

*Case 3*

```
  "default_extensions": [
    {
      "permit-pty": ""
    },
    {
      "permit-agent-forwarding": ""
    }
  ],
```

**Empirical answer (tested with vault v1.6.2)**

All three appear to work.  In all three cases, retrieving the role with `vault read` shows the value as a simple map:

```
$ vault read ssh-user-ca/roles/ssh-test
Key                         Value
---                         -----
...
default_extensions          map[permit-agent-forwarding: permit-pty:]
...
```

*Aside:* as expected, a plain list in the form `"permit-pty,permit-agent-forwarding"` or `["permit-pty","permit-agent-forwarding"]` is rejected:

```
	* error converting input permit-pty,permit-agent-forwarding for field "default_extensions": '' expected a map, got 'string'
	* error converting input [permit-pty permit-agent-forwarding] for field "default_extensions": '[0]' expected a map, got 'string'
```

**Code analysis**

There are test cases for both forms: e.g. [here](https://github.com/hashicorp/vault/blob/master/builtin/logical/ssh/backend_test.go#L1100) and [here](https://github.com/hashicorp/vault/blob/master/builtin/logical/ssh/backend_test.go#L804) (although with only one extension, so they don't distinguish case 2 and case 3).

I couldn't find the code which merges the list of maps into a single map.  I note that Vault uses [github.com/mitchellh/mapstructure](https://github.com/mitchellh/mapstructure) but I wasn't able to replicate this behaviour - [1](https://play.golang.org/p/LGAiho1nelc), [2](https://play.golang.org/p/R9OX8K4DLHf).

**Suggestion**

I don't see any particular reason to wrap the options in a list, so my suggestion is to remove the "list of maps" form from the documentation - *or* to document in the API that both forms are acceptable when creating or updating an ssh role.

**Comment by HridoyRoy** [comment]
Hi,
Thanks for the issue and the testing! I'll let others weigh in on this, but I think updating the documentation is the way to go.
