### ISSUE TITLE
LDAP Backend AD integration error ---- LDAP search failed: LDAP Result Code 201 "": ldap: invalid characters for escape in filter

### ISSUE THREAD

**Issue by astrally2000** [hashicorp/vault#1097]
Hi All,
I am loving all the Hashicorp tools and how they solve common infrastructure challenges. In particular vault seems to offer some unique solutions to security challenges I hadn't even considered. So good work on a great feature set guys :)
I'm really keen to hook it up to our Active Directory to provide central auth as opposed to spawning even more stand alone LDAP directories and shadow IT.

I'm familiar enough with integrating LDAP for other java type applications and have tried a number of different approaches. Ideally I'm intending on connecting to a load balanced VIP but have removed that for simplicity and simply trying to attach to a domain controller.

My knowledge of GO is non-existant.

I've referred to this issue #546 and tried using cn as well as sAMAccountName. In my experience sAMAccountName is preferable as it's unique and generally doesn't contain special characters.

Below are my commands
vault write auth/ldap/config url="ldaps://domaincontroller.domain.com:636" userattr=sAMAccountName upndomain="domain.com" userdn="OU=Accounts,DC=domain,DC=com" groupdn="OU=Groups,OU=Accounts,DC=domain,DC=com" insecure_tls=true starttls=true
Success! Data written to: auth/ldap/config

H:\>vault auth -method=ldap username=username
Password (will be hidden):
Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/ldap/login/l059493
Code: 400. Errors:

* LDAP search failed: LDAP Result Code 201 "": ldap: invalid characters for escape in filter

What is interesting to note is that when I put in incorrect password LDAP responds correctly, ie Invalid creds. so the backend appears to be connected.

URL: PUT http://127.0.0.1:8200/v1/auth/ldap/login/l059493
Code: 400. Errors:

* LDAP bind failed: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr
: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1

We are running Active Directory forest level 2008 R2 if that helps.
What sort of additional debugging can I provide, when I 
started using >
vault server -log-level=debug -dev 
I didn't get the sort of debugging I'd expect.

I'm using a Windows 0.5 version of vault

2016/02/19 17:53:20 [DEBUG] rollback: attempting rollback on secret/
2016/02/19 17:53:20 [DEBUG] rollback: attempting rollback on cubbyhole/
2016/02/19 17:53:20 [DEBUG] rollback: attempting rollback on sys/

**Comment by jefferai** [comment]
Hi @astrally2000 -- glad to hear you love our products!

This is _probably_ the same root cause as #1030. I'm going to put some fixes in soon for that. If you like, I can send you an updated binary with those fixes and you can test it out and see how it goes.

If that sounds good, let me know (you can send email to jeff at hashicorp dt com) if there is some real-time way we can talk. That way if things are still not working I can get some debugging from you and spin out new builds. If we do this, any chance that you are able to do testing on a 64-bit Linux box/VM? It'd make it easier for me to get binaries spun out for you.

Thanks!

**Comment by astrally2000** [comment]
Thanks for shipping me a compiled windows version of the 0.5.1 update Jeff, 
This works.
As a side note for any other Windows users I didn't need to provide any line separators, simply spaces as above. When defining the admin group to map to a policy I simply used the common name and not the full distinguished name.
vault write auth/ldap/groups/"SOME_ADMIN_USERS" policies=root
I will close this issue, given that this item appears fixed in the next release.
Thanks again, 
Andrew

**Comment by astrally2000** [comment]
Thanks for shipping me a compiled windows version of the 0.5.1 update Jeff,
This works.
As a side note for any other Windows users I didn't need to provide any line separators, simply spaces as above. When defining the admin group to map to a policy I simply used the common name and not the full distinguished name.
vault write auth/ldap/groups/"SOME_ADMIN_USERS" policies=root
I will close this issue, given that this item appears fixed in the next release.
Thanks again,
Andrew
