### ISSUE TITLE
Searchable documentation

### ISSUE THREAD

**Issue by siddharthist** [hashicorp/vault#1098]
Right now, the documentation available at https://www.vaultproject.io/docs/index.html isn't searchable :cry:. Now, an external search engine works just as well but a built-in search bar would be user-friendly! 

As I'm looking through all the HashiCorp products, I notice that this is a trend...

**Comment by jefferai** [comment]
I'll file this as an internal roadmap issue, since we share underlying web code bases. Thanks!
