### ISSUE TITLE
Implement a FUSE filesystem which presents secrets as files

### ISSUE THREAD

**Issue by emk** [hashicorp/vault#110]
Vault looks like a really great program! Thank you for releasing it.

A possible feature suggestion:

One of the nice features of [keywhiz](http://square.github.io/keywhiz/) is keywhizfs, a FUSE-based filesystem that makes secrets available as ordinary files, for use with programs that expect secrets to be stored as files.

There's a go [go-fuse](https://github.com/hanwen/go-fuse) library that might simplify the implementation here.

**Comment by knuckolls** [comment]
I'd like to second this. I haven't yet grokked all of the vault documentation but one feature that I did think was an excellent idea was the FUSE filesystem that exposes read only secrets.

**Comment by stevendborrelli** [comment]
+1 on this.

**Comment by myspotontheweb** [comment]
Would a template solution like [consul template[[1] be a simpler fit for this use case?

I'll reserve judgement. If this enhancement can solve the problem of securely managing files like SSH private keys and SSL certs I'm in!

[1]: https://github.com/hashicorp/consul-template

**Comment by knuckolls** [comment]
Symlinks to the fuse vault seem like an interesting use case. It's unix
permissions like any other file at that point.

**Comment by davitb** [comment]
+1

**Comment by keithchambers** [comment]
+1

**Comment by ecylmz** [comment]
+1

**Comment by activars** [comment]
This is great to have :+1:

**Comment by armon** [comment]
The current way to get something very close is to use a tmpfs volume alongside consul-template

**Comment by dlin128** [comment]
+1
Would love this.

**Comment by jefferai** [comment]
I'm going to close this because there are currently no plans to implement this within Vault itself, _however_, one of our partners (Asteris) is playing with such a system. I'd encourage you to give them encouragement!  https://github.com/asteris-llc/vaultfs

**Comment by jboero** [comment]
I know this is closed but I've done this. Repo here:
https://github.com/jboero/hashifuse
