### ISSUE TITLE
I started a migration, pointing at the old S3 datastore(from vault 1.5.4), and at the local dir for the new raft endpoint (vault 1.5.4), which started fine, but fails to resume

### ISSUE THREAD

**Issue by sosiskin2000** [hashicorp/vault#11026]
**To Reproduce**

Login to container with vault 1.5.4
rm -Rf /vault/data/*
cat <<EOT > /tmp/migrate.hcl
storage_source "oci" {
        namespace_name = "XXXXXXX"
        bucket_name = "vault_data"
        ha_enabled = "true"
        lock_bucket_name = "vault_leader_lock"
}
storage_destination "raft" {
        path = "/vault/data"
        retry_join {
          leader_api_addr = "http://vault-raft:9200"
        }
}
cluster_addr = "https://vault-raft-0.vault-raft-internal:8201"
EOT

2. Run `vault operator migrate -config=./migrate.hcl` on the new container with 1.5.4
3. After some time ctrl-c or otherwise kill the migration
4. Run `vault operator migrate -config=./migrate.hcl -start=auth` (or any other key you'd like to resume from)
5. get error `Error migrating: error mounting 'storage_destination': could not bootstrap clustered storage: error bootstrapping cluster: cluster already has state` 

**Expected behavior**
Expected migration to resume at the key I provided in the start flag

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.5.4
* Vault CLI Version (retrieve with `vault version`): 1.5.4
* Server Operating System/Architecture: official k8s container via helm chart x86_64

**Comment by HridoyRoy** [comment]
Hi @sosiskin2000 ,
Is vault offline? Also, how many nodes does vault have after pausing the migrate? 
Thanks!

**Comment by sosiskin2000** [comment]
Of course Vault offline. Because he cannot start if it's not in online.

пн, 8 мар. 2021 г., 19:08 Hridoy Roy ***@***.***>:

**Comment by vishalnayak** [comment]
Closing the issue due to staleness.

Closing stale issues helps us keep the issue count down and the project healthy. Keeping the issue count under a manageable number helps us provide faster responses and better engagement with the community.

If you feel that the issue is still relevant, or if it is wrongly closed, please leave a comment and we'd be happy to reopen it.
