### ISSUE TITLE
Enable a "forward rolling" PKI strategy that does not break AIA or CRLs -- symlink strategy

### ISSUE THREAD

**Issue by maxb** [hashicorp/vault#11024]
I'd like to credit @abriening for the issue and problem statement, which I have copied from #10947 - I am suggesting an alternative strategy to solve the same issue.

**Is your feature request related to a problem? Please describe.**

As documented in other issues the pki rotation isn't as clear or clean as it could be.

Related to #2581

**Describe the solution you'd like**

Here are the steps to create a "forward rolling" PKI strategy that does not break AIA or CRLs.

I propose that a way to create a "symlink" in the Vault URL namespace be created.

This could take the form of a secrets engine which forwarded requests internally to another secrets engine.

With this functionality available, you could then:

* Set up your first PKI secrets engine at `/pki-g1` - configuring your CRL and AIA URLs to point to `/pki-g1`
* Set up a "symlink" at `/pki` forwarding requests to `/pki-g1`
* Instruct your applications to obtain certificates from `/pki/issue/:name` and similar APIs

At time of CA renewal:

* Set up new PKI secrets engine at `/pki-g2`
* Update "symlink" at `/pki` to forward to `/pki-g2`

This has a few benefits over the #10947 approach:
* Each PKI secrets engine created is given its own uniquely identifying mount path, rather than being `/sys/remount`ed to different paths throughout its lifecycle. This is easier to explain and reason about.
* Even the brief downtime implied by "remount CURRENT to PREVIOUS" then "remount NEXT to CURRENT" is eliminated
* There is no need for the root/intermediate CA providing the signed intermediate certificate, to also be a Vault CA
* There is no need to include multiple CRL URLs, one of which will end up returning an incorrect CRL for a different CA

On the other hand, this approach does require creating this notion of a "symlink" in the Vault URL space, which, even if implemented as a secrets engine that forwards requests, is a complex feature.

**Describe alternatives you've considered**
 
* #10947 - `/sys/remount`; multiple CRL URLs; AIA URL points to another Vault CA (as compared with above)
* Use the "rotate between two pki mounts and make clients externally discover which to use" method (requires extra logic in every client)
* Be willing to break AIA and CRL and endure downtime whilst getting a new intermediate certificate signed (not good, breaks some features)
* #10815 - Don't change the CA key, just re-sign the same key with extended validity (not secure in the long term)
* Stick an HTTP proxy in front of Vault and do URL rewriting there (possible, but means a crucial tiny part of CA admin needs to be done in a different system outside Vault)

**Comment by cipherboy** [comment]
@abriening and @maxb -- do you want to test out the new multi-issuer functionality in #15277 and doc'd in #15238 and see if this addresses it? I suspect it does :-)
