### ISSUE TITLE
Update docs to reflect the consequences of Go >= 1.5 being a copying GC...

### ISSUE THREAD

**Issue by sean-** [hashicorp/vault#1103]
`Go>=1.5` is a copying GC.  There are some consequences to this change in behavior that need to be documented.

**Comment by jefferai** [comment]
Note that the documentation never actually claims to zero out any memory. The closest we get to that is in `website/source/intro/getting-started/deploy.html.md` where we say when Vault is sealed it clears the encryption key from memory -- which it does, out of Vault's active memory space, but we don't make any claims that it disappears from memory entirely (and even outside of Go that might be difficult on all OS/ARCH).

We may want to put a comment in the memzeroing code about its limited utility.
