### ISSUE TITLE
Prevent someone able to access Kubernetes pod from stealing secrets.

### ISSUE THREAD

**Issue by luizgn** [hashicorp/vault#11034]
**Is your feature request related to a problem? Please describe.**
Kubernetes integration is very impressive, congratulations to Vault team.

However, if a understand correctly, if hackers get access into a pod in some way, they will be able to use the Kubernetes service account to legitimately access Vault and steal secrets.

I think this is exactly what most people want to prevent when moving secrets from Kubernetes to Vault.

**Describe the solution you'd like**
Solution 1: Add some option to limit number of Kubernetes Authentications from same pod.

Solution 2: Add some option to prevent Kubernetes Authentication to be used if pod is alive for a period of time.

Solution 3: Use vault-k8s injector service to create authentication credentials (AppRole) which can be used only once and inject them into init and sidecar containers to be used instead of Kubernetes service account credentials.

**Describe alternatives you've considered**
I didn't figure out any alternative using available Vault features but I appreciate if you can provide some direction.

**Comment by kalafut** [comment]
Hi. A recent PR (https://github.com/hashicorp/vault-k8s/pull/213, not yet released) adds support for all auth methods and should help with proposal 3.

**Comment by luizgn** [comment]
Thanks @kalafurt, but I think feature [hashicorp/vault-k8s#213](https://github.com/hashicorp/vault-k8s/pull/213) has same behavior. 

Using Kubernetes Auth, we can perform Secure Introduction and we won't need to deal with secrets on CI/CD anymore, that is really great. But, secret zero (Service Token) is available on pod forever and a person (hacker) who gets improper access into pod can use it to steal secrets from Vault.

On the procedure described on [hashicorp/vault-k8s#213](https://github.com/hashicorp/vault-k8s/pull/213), we still need to mount a secret (with AppRole secret or certificate), which cannot be unmounted neither deleted like Service Token, so, secret zero will still into pod forever again.

What I tried to describe on option 3 is vault-k8s injector acting as a Trusted Orchestrator and providing a wrapped token to init/sidecar containers. In this way, an intruder won't be able to use data on pod to steal secrets from Vault.

Regards,
Luiz

**Comment by Chili-Man** [comment]
Another potential option is to mount the service account only in the containers that are required for the vault authentication, that way the main application container wont have access to the service account and wont be able to directly retrieve credentials from vault. We've been looking at ways to reduce the attack surface as well in this context

**Comment by luizgn** [comment]
Hi @Chili-Man, thanks for support, it looks a good idea, however, I tried using vault-k8s without success.

First, I created a new secret for service account and disabled `automountServiceAccountToken`. After, I configured vault-k8s to mount new secret in `/vault/custom` using `agent-extra-secret` annotation and added a config map using `agent-configmap` annotation to set `token_path` to `/vault/custom/token` (I also tried `/vault/custom`).

ReplicaSet failed to create pod with message `admission webhook "vault.hashicorp.com" denied the request: error validating agent configuration: no service account name or path found`.

I'm not sure if I did all correctly. Should I open an issue on vault-k8s repository?
Or, even better, can I ask vault-k8s team to add an annotation to set `token_path` to work with `agent-extra-secret`?

Best regards,
Luiz

**Comment by tvoran** [comment]
Along the lines of what @Chili-Man suggested, https://github.com/hashicorp/vault-k8s/pull/288 will be adding support for projected service account tokens, which can be mounted only on the vault-agent containers, and are periodically renewed.

**Comment by reegnz** [comment]
@luizgn Did you consider using https://www.vaultproject.io/docs/auth/jwt instead of the kubernetes auth method?
The OpenID Connect discovery URL is now built into kubernetes, you just have to expose it so vault can query the well-known discovery URL for public keys. No secret keys need to be exchanged. No connectivity from vault to the cluster API is required to validate JWT tokens.

**Comment by hsimon-hashicorp** [comment]
Since it looks like this has been addressed by the ecosystem team, I'm going to go ahead and close this issue. Please feel free to re-open if the solutions provided don't meet your needs. Thanks!
