### ISSUE TITLE
SSH CA: generate_signing_key to support ed25519 keys

### ISSUE THREAD

**Issue by candlerb** [hashicorp/vault#11035]
**Is your feature request related to a problem? Please describe.**
Vault's SSH CA is able to sign certificates using elliptic curve ciphers like ed25519, but cannot generate the private key.  If you set `generate_signing_key` to `true` (which is the default), you always get an RSA key.

Therefore, to use these key types, you have to generate the private key externally and import it.

RSA keys are problematic for SSH CAs:
* Modern versions of OpenSSH (8.2+) disable the `ssh-rsa` algorithm by default, as it's based on weak SHA1
* Only relatively recent versions (7.2+) support `rsa-sha2-256` and `rsa-sha2-512`. This excludes RHEL ≤ 6 and Debian ≤ 8, which are still widely deployed
* However, `ssh-ed25519` has been supported since 6.5, and `ecdsa-sha2-nistp256/384/521` since 5.7

This makes the elliptic curve ciphers much more widely applicable for a CA covering a mixed estate.

**Describe the solution you'd like**
A new parameter to [ssh/config/ca](https://www.vaultproject.io/api-docs/secret/ssh#submit-ca-information) to specify the key type when `generate_signing_key` is true.

For backwards compatibility, this can default to RSA.

(Arguably this would be a good place to specify other key parameters, particularly key size)

**Describe alternatives you've considered**
As mentioned, it is already possible to generate an elliptic curve key externally, and import it using the `private_key` and `public_key` fields.

However this exposes the CA private key on the machine where it is generated. Special care is required to ensure it does not persist on disk - e.g. by booting an ISO image with ramdisk only.

**Explain any additional use-cases**
N/A

**Additional context**
Relates to #10067, where a user tried to set `algorithm_signer` when signing an rsa user key with an ed25519 CA key. (Of course an RSA signing algorithm makes no sense when signing with an ed25519 CA key - even if the user key being signed is RSA)

Documentation is poor in this area, it's not even clear that you *can* use non-RSA keys for the CA.  `algorithm_signer` accepts only RSA-based signature types, enforced in code:

```
                        algorithmSigner = algorithmSignerRaw.(string)
                        switch algorithmSigner {
                        case ssh.SigAlgoRSA, ssh.SigAlgoRSASHA2256, ssh.SigAlgoRSASHA2512:
                        case "":
                                // This case is valid, and the sign operation will use the signer's
                                // default algorithm.
                        default:
                                return nil, fmt.Errorf("unknown algorithm signer %q", algorithmSigner)
                        }
```

But if you leave it empty, the default algorithm for a non-RSA CA key works.

~~It would be more user-friendly to accept all algorithms, but instead validate that the algorithm chosen is compatible with the given private key type.  (That could be a separate FR)~~ In the go crypto/ssh code, for key types other than RSA, the only valid values for algorithm signer are empty string or the pubkey type name (and these are treated identically).  Therefore, there is no need to accept anything other than empty string for all other key types.

**Comment by sh7dm** [comment]
I think default should be changed in some version. While following the guide, users with sshd 8.2+ need to enable insecure key types in config:
```
PubkeyAcceptedKeyTypes +ssh-rsa-cert-v01@openssh.com
CASignatureAlgorithms +ssh-rsa
```
This might not be obvious and so following the guide on setting up an SSH CA will cause auth not to work by default, so at least docs should be fixed.

**Comment by candlerb** [comment]
That is a different issue, and I think should have a separate ticket.

The issue you describe is what signature algorithm Vault should use by default, when making a signature using an RSA key.  Currently it defaults to `ssh-rsa`, rather than `rsa-sha2-256` or `rsa-sha2-512`.  It makes no difference to the key itself.

You can fix this yourself by setting

```
"algorithm_signer": "rsa-sha2-256",
```

in the signing role.  Doing this means that you do *not* have to enable "insecure and deprecated SHA1-based algorithms" in your clients or servers: the settings you quoted are not needed, and security is not compromised.  However you will find you are unable to use OpenSSH clients and servers prior to 7.2.

I agree that this ought to be the default today.  Hashicorp can't change defaults without breaking backwards compatibility.  However when a *new* signing role is created, if the algorithm_signer is not selected, they could set it to `rsa-sha2-256`. You can open a ticket for this if you like.

**Comment by sh7dm** [comment]
Yes, so RSA, as stated by issue author, is not the best compatibility-wise, so probably Ed25519 can be default.
Also docs should be updated to include info about incompatibility of Vault's defaults with OpenSSH 8.2+ server defaults.

**Comment by candlerb** [comment]
Certainly if generate_signing_key were to support generating ed25519 keys, then it could also be made the default.  And I agree that at least documentation could explain the alternative of importing your own key, and why this is a good idea.

**Comment by sh7dm** [comment]
As far as `generate_signing_key` is concerned, it can take multiple values for simplicity:
- `true` for default
- `rsa`
- `ecdsa`
- `ed25519`

So no extra property is required actually.

**Comment by arusso** [comment]
> As far as `generate_signing_key` is concerned, it can take multiple values for simplicity:
> 
> * `true` for default
> * `rsa`
> * `ecdsa`
> * `ed25519`
> 
> So no extra property is required actually.

We were greeted with a parsing error when attempting to do this and looking at the docs [docs](https://www.vaultproject.io/api-docs/secret/ssh) and the [code](https://github.com/hashicorp/vault/blob/7ca2caf3d0b9aebe6ecc4ef13de9f9fc895b4bcd/builtin/logical/ssh/path_config_ca.go#L42), it seems like this is in fact _not_ possible and only true/false are accepted.

**Comment by sh7dm** [comment]
@arusso I just proposed how it __could__ look like when implemented. For now you can only provide pre-generated keypair.

**Comment by arusso** [comment]
Ah thanks, sorry I misunderstood and thought you were saying this was already possible.

**Comment by cipherboy** [comment]
Hey there @candlerb and others -- this was recently merged (with bugfix) to the main branch. If anyone wants to try out the feature before v1.10.0 GA and provide feedback, that'd be appreciated :-)

**Comment by andreaso** [comment]
I just performed a quick local test using `Vault v1.10.0-dev ('e9adaffead120eb6ccdce76c2b401e7cd9013280')`.

It worked just as expected to have Vault generate an ed25519 SSH CA, and then use that CA to produce a host certificate.

Thanks!

**Comment by candlerb** [comment]
Code LGTM, so if @andreaso has tested this then I'm happy.  Thank you!
