### ISSUE TITLE
vault read gives different value on each read.

### ISSUE THREAD

**Issue by shazinahmed** [hashicorp/vault#11045]
**Describe the bug**

I have created a secrets engine for Signed SSH certificates. I created the role initially with 5m ttl and then udpated it to 24h ttl. When I run a vault read for the role, the result set has different ttl values each time (5m or 24h). 

**To Reproduce**
1. Create a new role with 5m ttl
 ```
vault write ssh-client-signer/roles/signer-role -<<"EOH"
{
  "allow_user_certificates": true,
  "allowed_users": "*",
  "allow_user_key_ids": true,
  "allowed_extensions": "permit-pty,permit-port-forwarding,login@github.com",
  "default_extensions": [
    {
      "permit-pty": ""
    }
  ],
  "key_type": "ca",
  "ttl": "5m",
}
EOH
```

2. Update the the ttl to 24h by changing 5m to 24h in the above script and run it again.
3. Do a vault read for the above role (Below are the results of 2 vault reads I ran in a span of a minute on my machine)
```❯ vault read ssh-client-signer/roles/signer-role
Key                         Value
---                         -----
algorithm_signer            n/a
allow_bare_domains          false
allow_host_certificates     false
allow_subdomains            false
allow_user_certificates     true
allow_user_key_ids          true
allowed_critical_options    n/a
allowed_domains             n/a
allowed_extensions          permit-pty,permit-port-forwarding,login@github.com
allowed_user_key_lengths    map[]
allowed_users               *
allowed_users_template      false
default_critical_options    map[]
default_extensions          map[permit-pty:]
default_user                n/a
key_bits                    0
key_id_format               n/a
key_type                    ca
max_ttl                     0s
ttl                         5m
❯ vault read ssh-client-signer/roles/signer-role
Key                         Value
---                         -----
algorithm_signer            n/a
allow_bare_domains          false
allow_host_certificates     false
allow_subdomains            false
allow_user_certificates     true
allow_user_key_ids          true
allowed_critical_options    n/a
allowed_domains             n/a
allowed_extensions          permit-pty,permit-port-forwarding,login@github.com
allowed_user_key_lengths    map[]
allowed_users               *
allowed_users_template      false
default_critical_options    map[]
default_extensions          map[permit-pty:]
default_user                n/a
key_bits                    0
key_id_format               n/a
key_type                    ca
max_ttl                     0s
ttl                         24h
```
Notice the ttl is different on each run. I have ran this multiple times and there is no consistent pattern of which value is shown.

4. Create a signed certificate and i get a certificate with 5m validity.

**Expected behavior**
ttl should be the udpated value (24h).

**Environment:**
* Vault Server Version : 1.6.1
* Vault CLI Version : 1.6.2
* Server Operating System/Architecture: Amazon Linux
* Storage backend: Postgres

Is this a bug or am I doing something wrong?

**UDPATE**
I played around a bit more.

1. I updated the ttl to 1h. The read results were still inconsistent, but the newly signed certificate had 1h validity, which is expected.
2. I updated the ttl again to 48h. The read results still inconsistent, but the newly signed certificate has 24h validity (which was the second value i had set), which is baffling.
3. I updated ttl to 36h, now my certificates are signed with 48h validity. 

I can go on, but somewhere it is picking up the old values for signing. I don't know why.

**Comment by candlerb** [comment]
I can't reproduce this with vault 1.6.3 using a single server and the file storage backend.  Can you describe:

1. Is your vault environment a HA cluster of any sort?
2. If so, are you also using postgres for the [HA lock](https://www.vaultproject.io/docs/concepts/ha), or something else ?
3. How many vault servers? Are they behind any sort of load balancer?  If so, have you tried talking directly to individual vault servers instead?
4. Is postgres itself a single instance, or some sort of cluster you have built yourself, or Amazon RDS, or something else?

**Comment by HridoyRoy** [comment]
Hi @shazinahmed ,
In addition to the questions above, is this issue happening for other roles and other secrets engines as well (if you try to change the ttl), or are you observing this only with the SSH secrets engine? 
Thanks!

**Comment by shazinahmed** [comment]
@candlerb  1. Yes, this is an HA cluster on EKS with two nodes.
2. I am using Postgres as a storage backend and haven't defined any other backend for HA lock.
3. 2 Nodes. There is an EKS ELB that is used as a load balancer. No i haven't tried directly accessing the vault servers.
4. The postgres is an AWS RDS instance.

@HridoyRoy I have observed a similar issue with KV backend. 
```
❯ vault kv get kv/secrets-manager-backend/dev/gh
No value found at kv/data/secrets-manager-backend/dev/gh
❯ vault kv get kv/secrets-manager-backend/dev/gh
No value found at kv/data/secrets-manager-backend/dev/gh
❯ vault kv get kv/secrets-manager-backend/dev/gh
====== Metadata ======
Key              Value
---              -----
created_time     2021-03-05T21:39:50.893278017Z
deletion_time    n/a
destroyed        false
version          1

======== Data ========
Key             Value
---             -----
gh.authToken    xxMaskedxx
```
The command was ran thrice in a span of a minute. If you have noticed, twice it said value does not exist and then on the third time it gave a result.

So i have a hunch that somewhere data replication (if exists) is failing.

**Comment by shazinahmed** [comment]
Here is the ha/storage section of values file i had used for Vault installation.

```
  # Run Vault in "HA" mode.
  ha:
    enabled: true
    replicas: 2
    raft:
      enabled: false
      # setNodeId: true

    config: |
      ui = true
      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/vault-server-crt/tls.crt"
        tls_key_file = "/vault/userconfig/vault-server-crt/tls.key"
        tls_ca_cert_file = "/vault/userconfig/vault-ca-crt/tls.crt"
      }

      storage "postgresql" {
        connection_url = "postgres://dev_vault_user:password@demo-db-pg-db.myrdsinstance.us-east-1.rds.amazonaws.com:7964/dev_vault_db"
      }   
```

**Comment by sgmiller** [comment]
Could you post the output of "vault status" run against each individual Vault instance?  This and trying your experiment on a particular instance could prove illuminating.  If it's difficult to connect directly due to private networking, you could try manually adjusting the ELB target instances so that only one Vault node is hit at a time.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.

**Comment by shazinahmed** [comment]
I came back on this project after a break and I was able to figure out the issue. As mentioned above this cluster has HA enabled. But I didn't know that i had to explicitly add this in the postgres config too. Here is the new postgres config:

`      storage "postgresql" {
        connection_url = "postgres://user:pwd@dev-pg-db.xxxxxxxxxx.rds.amazonaws.com:7964/dev_vault_db"
        ha_enabled = true
      }    `
