### ISSUE TITLE
-dev-plugin-dir flag does not appear in the help output

### ISSUE THREAD

**Issue by irbekrm** [hashicorp/vault#11053]
**Describe the bug**

`-dev-plugin-dir` flag does not appear in the output of `vault server --help`. (The flag itself works though).

**To Reproduce**
1. Run `vault server --help`
2. Observe that the 'Dev Options' section does not include `-dev-plugin-dir` flag

**Expected behavior**
I can see a section describing how to use `-dev-plugin-dir` flag.

**Environment:**
* Vault CLI Version (retrieve with `vault version`): Vault v1.6.3 (b540be4b7ec48d0dd7512c8d8df9399d6bf84d76)
* Server Operating System/Architecture: Linux

**Comment by catsby** [comment]
Hello there 👋 

There several `-dev` flags that are intentionally not documented and omitted from any `--help` output. The primary reason would be that we offer no "warranty" or backwards-compatibility promise with them, and should be used solely for _development_ of Vault and plugins. That said, some of them are documented on the web (`dev-plugin-dir` being one). 

That being said, I don't believe this is a bug, strictly speaking. We can leave it open but I don't anticipate any changes here. 

- https://www.vaultproject.io/docs/commands/server#dev-options

- https://github.com/hashicorp/vault/blob/66cbbe79821a55ef4ed9261147b0342cd8c25a32/command/server.go#L264-L360

**Comment by irbekrm** [comment]
Thanks for the reply! That makes sense- happy to close this issue.
