### ISSUE TITLE
Register a Consul TTL healthcheck

### ISSUE THREAD

**Issue by mterron** [hashicorp/vault#1105]
Since Consul is the prefered & recommended physical backend for Vault, I think it'd be a good idea to register a TTL healtcheck when you use Consul as the physical and or HA backend. The health check could improve failover time for an HA deployment of Vault.
A short TTL could be used with a timer in Vault to allow Consul to detect a failed Vault instance. Also it should ensure that when Vault is sealed, the timer stops refreshing the health check.
The proposed logic could be:
1. On unseal -> if instance mode is active: register a service **V** with a TTL health check **H** in Consul with a TTL of x seconds & start a timer **t** that does a PUT to **H** HTTP endpoint every x - n seconds
2. On seal (or lost of active status for any cause) -> stop **t** & unregister **V** (and **H**? not sure of the semantics)

This way there will always be a vault.service.consul DNS endpoint pointing to the active Vault instance.

Caveat, this will work well as long as Vault remains active-warm standby. If Vault ever becomes active-active this logic should be revisited as it will not make sense anymore.

**Comment by jefferai** [comment]
Hi @mterron,

I'm slotting this into 0.5.1 since that's our active milestone right now but I do expect it to slip. In which case we will try to get it into 0.5.2 but can't promise it will happen.

**Comment by mterron** [comment]
Thanks Jeff, it is not a major thing, so there's no rush. Only a nice to have feature (and being a well behaved citizen on the Hashicorp ecosystem)

**Comment by doublerebel** [comment]
:+1:

**Comment by jefferai** [comment]
This was fixed via #1355
