### ISSUE TITLE
Vault HA newbie question

### ISSUE THREAD

**Issue by Niks-JJ** [hashicorp/vault#1109]
Hi Guys, 

With 1 server set up of Vault with consul backend on my laptop, I am able to achieve desired goals of transit backend encryption in vault  and key value store of consul.

Now I need to prototype  a set up for production, Vault in High Availability with two datacenters, and consul backend.

Came across only below link for a similar set up but not that detailed. Read many issues and blogs too, but not clear.
http://sysadminsjourney.com/blog/2015/10/30/replicating-hashicorp-vault-in-a-multi-datacenter-setup/  

I need 
datacenter A     : Read+write source

server 1,2,3   and a web UI

datacenter B : Read only destination
server 4,5,6 and a web UI(for disaster recovery).

All servers have local instance of vault and consul

questions:

1) isn't it an overhead to maintain vault, consul in all servers, in terms of maintaining so many servers?
2) I understand how a consul cluster by LAN and WAN gossip. How about Vault cluster?
3) High Availability in vault : active and stand by servers need to be in same datacenter?
4) Out of these 6, will there be only 1 active vault server(only in datacenterA)? or each datacenter has 1 active vault server?

I am very confused in understanding this set up. If I cant propose it right, covering HA, its not useful in production as there wont be any disaster recovery.

Please suggest or send a useful link. 

Is 1 vault instance in 3 server consul cluster, in each datacenter ideal?

**Comment by Niks-JJ** [comment]
Correction: 
datacenter B will use consule- replicate to replicate datacenter A

**Comment by jefferai** [comment]
Hi @Niks-JJ ,

This is not a supported configuration. If you want to have multi-datacenter replication as described in the blog, you will indeed need to deal with the overhead and coordination of keeping the multiple services replicated, and be aware that if you run into problems we may not be able to help you.

**Comment by Niks-JJ** [comment]
Thanks Jeff.

Correct me if I am wrong.

Consul supports multiple datacenters.

Vault HA is within datacentre (in face there is no concept of datacentre in vault)

So if we use consul replicate to back up data in datacentre B, stand by vault instance , when primary is down, cannot switch to the replicated consul instance as storage backend to retrieve Vault ACL policies and other data required by vault , unless explicitly done.

**Comment by jefferai** [comment]
> Consul supports multiple datacenters.

Correct.

> Vault HA is within datacentre (in face there is no concept of datacentre in vault)

Also correct. Vault is using Consul for storage, but does not have a concept of a datacenter, partially because it does not support federation.

> So if we use consul replicate to back up data in datacentre B, stand by vault instance , when primary is down, cannot switch to the replicated consul instance as storage backend to retrieve Vault ACL policies and other data required by vault , unless explicitly done.

The data stored in Vault is just a data store, so yes -- if you exactly replicate all data from datacenter A to datacenter B, you could then spin up a Vault node in datacenter B and make use of the data. But:

* You *cannot* safely run Vault in both datacenter A and datacenter B concurrently off of the replicated Consul data -- this includes simply running in a sealed fashion. For a very specific subset of operations you can follow that blog post and try to make it work, but be aware that it is not supported.
* To go back to datacenter A, you'd have to stop Vault in B, consul-replicate all of the data back over, and then start Vault in DC A.

Your other option is simply to connect to the Consul cluster in datacenter A with your Vault node in datacenter B. You'd have higher latency, but it could be unsealed and a full HA member.

**Comment by Niks-JJ** [comment]
Thanks a ton Jefferai.

Did not understand your last statement.
"Your other option is simply to connect to the Consul cluster in datacenter A with your Vault node in datacenter B. You'd have higher latency, but it could be unsealed and a full HA member."

My whole purpose of datacenter B is for disaster recovery, when datacenter A goes down. So Vault in DC B will have to point to Consul in datacenter B.

Only issue I find in this is, 

Consul replicate is one way, so there is overhead of consul replicate data from DC B back to A, to recover data updated during DC B takes over.

In my scenario, Consul will be used for key values(through consul web UI), and Vault for cryptography(transit backend).
I  can avoid key value updates in consul in DC B.

But to decypt data, which was encrypted when DC B takes over (considering no new policies and encryption keys generated), when we switch back to DC A, do you then DC B to DC A data replication will be needed.

I want to stick to one way consul replicate to avoid complexicities. So thinking of all possibilities.
.

**Comment by jefferai** [comment]
Hi @Niks-JJ ,

What I meant was that Vault in DC B could point to Consul in DC A unless DC A goes down, at which point Vault could be switched over. 

As you noted, there are issues with synchronizing replication back and forth when one datacenter goes down. You could manage this by ensuring that nothing in DC A comes back up automatically, giving you time to ensure that replication has occurred back to DC A before switching services over to using Consul/Vault in DC A.
