### ISSUE TITLE
Vault 0.4: when unsealing vault (3 keys required), third key throws error

### ISSUE THREAD

**Issue by lagging** [hashicorp/vault#1110]
We are facing same issue as in

https://groups.google.com/forum/#!searchin/vault-tool/vault$20unseal$20/vault-tool/XKGoxWwzbWQ/Jb0FJWogEQAJ

what might be the cause of this ?? 

There is no problem in copy pasting as this problem was faced by many of our friends. We are using mysql . Our config file is as follow :-

what can be solution now ?

----------------------------------------------------------------------------------------------------------------------------
backend "mysql" {
		  username= "vault_user"
		  password= "V@334ault%"
		  address = "20.0.0.65:3307"
		}
listener "tcp" {
		  address = "vault-stg.klikpay.int:8200"
		  tls_cert_file = "/apps/vaultmaster/ssl/vault-stg.klikpay.int.crt" 
		  tls_key_file= "/apps/vaultmaster/ssl/vault-stg.klikpay.int.key"
                  tls_min_version= "tls10"
		}

disable_mlock=true
 
----------------------------------------------------------------------------------------------------------------------------------

Error: Error making API request.

URL: PUT https://vault-stg.klikpay.int:8200/v1/sys/unseal
Code: 500. Errors:

* Unseal failed, invalid key

**Comment by vishalnayak** [comment]
@lagging As Jeff mentions in the mail thread, all the entered unseal keys are used to reconstruct a key which then decrypts the master key. If any one of the unseal key is incorrect, unseal operation fails. If any of the entered unseal key is incorrect, the error only appears only when the reconstructed key fails to decrypt the master key.

Just to check if unseal operation is working properly, you can reduce the number of key shares and the key threshold, both to 1 (`$vault init -key-shares=1 -key-threshold=1`). This way you will have to only enter a single key to unseal vault. (Please remember that this is only for testing and this is not recommended for production use)

Hope this helps!

**Comment by jefferai** [comment]
Closing due to lack of reply.
