### ISSUE TITLE
How to migrate vault data from a physical backend (eg S3) to another (eg Consul)

### ISSUE THREAD

**Issue by joaocc** [hashicorp/vault#1111]
We are currently assessing Vault and, for our current purposes, the S3 backend seems fine.
However, we could not find how to "upscale" Vault when the time comes to, say, a consul backed server.

Is physical back-end migration a supported scenario? Where can documentation on this process be found?

**Comment by jefferai** [comment]
Hi @joaocc ,

It is not a supported scenario, and as such there is no documentation. A good place for questions like this is the mailing list (https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/vault-tool) -- at times people have made some statements about writing migration utilities, but I don't know if any of those ever came to pass.
