### ISSUE TITLE
Vault Golang Library Logical Error Handling 

### ISSUE THREAD

**Issue by llivingstone** [hashicorp/vault#11123]
**Describe the bug**

Apologies if this has been sent in before, i've been searching old issues and nothing seems to be matching what i'm seeing. I'm also unsure if this has been fixed with a later Vault server version.

When using Vault's Golang library, specifically [logical read](https://pkg.go.dev/github.com/hashicorp/vault/api@v1.0.4#Logical.Read) the function's error handling for 404s fails to return  an error in my testing.

**To Reproduce**
The following test code doesn't return an error. However, If I reduce the Token's scope of access, and try and Read a path i don't have access to, then i do get an error response with a 403.

```
package main

import (
	"github.com/hashicorp/vault/api"
)

func main() {
	var Config = &api.Config{
		Address: "http://127.0.0.1:8200",
	}

	client, err := api.NewClient(Config)
	if err != nil {
		panic(err)
	}

	client.SetToken("test")

	_, err = client.Logical().Read("secret/data/path/does/not/exist")
	if err != nil {
		panic(err)
	}
}
```

Looking at the [https://github.com/hashicorp/vault/blob/485b4d173e543aa52d93bb8df973101699d2369c/api/logical.go#L76](ReadWithData) code when the GET gets called, the response body from Vault is `{{"errors":[]}}` and the `resp.StatusCode` is 404, `ParseSecret` gets called and returns a empty Secret (below) and a `nil` as `parseErr`.

The conditional on [L#85](https://github.com/hashicorp/vault/blob/485b4d173e543aa52d93bb8df973101699d2369c/api/logical.go#L85) then passes and returns `nil`, `nil`.

Empty Secret:
```
{RequestID: LeaseID: LeaseDuration:0 Renewable:false Data:map[] Warnings:[] Auth:<nil> WrapInfo:<nil>}
```

**Expected behavior**
The `ReadWithData` function handles 404s and returns a error, rather than `nil`

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.4.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.6.3 ('b540be4b7ec48d0dd7512c8d8df9399d6bf84d76+CHANGES')

Vault server configuration file(s):

Don't have to hand, but can provide if needed.

**Comment by llivingstone** [comment]
Looking at the `terraform-provider-vault`, it seems like there is a workaround for this already:

https://github.com/hashicorp/terraform-provider-vault/blob/master/vault/data_source_generic_secret.go#L85

**Comment by ncabatoff** [comment]
Hi @llivingstone,

I wasn't around at the time, so I don't know what the rationale was, but this is absolutely by design and it's been this way from day one.  Changing it would break everyone's code, so I don't see that happening.  Now that you're aware of it though it shouldn't be a big deal, it just means that after a read you have to test both the err is nil and secret is non-nil.  And if you really hate it you could always write a wrapper for Client that makes it an error.
