### ISSUE TITLE
STS token generation fails when policy is identified by ARN

### ISSUE THREAD

**Issue by mhurne** [hashicorp/vault#1113]
I am using Vault 0.5.0.

STS token generation works when I use a user inline policy:

```
➜  ~ vault write aws/roles/foo policy=@policy.json
Success! Data written to: aws/roles/foo
➜  ~ vault read aws/sts/foo
Key            	Value
lease_id       	aws/sts/foo/<...>
lease_duration 	3599
lease_renewable	true
access_key     	<...>
secret_key     	<...>
security_token 	<...>
```

but fails when I use an ARN to identify the policy:

```
➜  ~ vault write aws/roles/bar arn=arn:aws:iam::aws:policy/ReadOnlyAccess
Success! Data written to: aws/roles/bar
➜  ~ vault read aws/sts/bar
Error reading aws/sts/bar: Error making API request.

URL: GET http://127.0.0.1:8200/v1/aws/sts/bar
Code: 400. Errors:

* Error generating STS keys: MalformedPolicyDocument: The policy is not in the valid JSON format.
	status code: 400, request id: ...
```

**Comment by jefferai** [comment]
This is not a bug; I'm not sure about upstream, but the official AWS SDK requires token creation to pass an inline document. See http://docs.aws.amazon.com/sdk-for-go/api/service/sts.html#type-GetFederationTokenInput

If they add support for passing in PolicyArn, as you can do when generating IAM users, we'll be happy to add support in Vault.

Sorry!

**Comment by mhurne** [comment]
Sorry, I created this issue with a barebones description with the intent of providing more information...one of the things I meant to note is that I suspect this is because GetFederationToken doesn't support using a policy by ARN. So I agree that this isn't a bug per se. I do think the documentation should be updated to make note of this, and I wonder if the output from Vault could be a bit more helpful?

**Comment by jefferai** [comment]
@mhurne Ah. Sure, makes sense. Any chance you want to tackle this and send a PR? Probably checking the given policy for a string starting with "arn:" and erroring rather than continuing would be a good idea.

**Comment by mhurne** [comment]
@jefferai It would be my pleasure! I'm new to Go, but I'll give it a shot. I won't be able to work on it until this evening, though.

**Comment by jefferai** [comment]
No problem! Thanks!
