### ISSUE TITLE
Error while changing namespace - when logged in using root token

### ISSUE THREAD

**Issue by spg7484** [hashicorp/vault#11133]
**Describe the bug**
While logged in using root token, error is thrown when changing namespaces or changing from one of the namespace to root namespace

```
Cannot read property 'userRootNamespace' of null
```

**To Reproduce**
1. Login to Vault UI using root token
2. Change to one of the namespaces
3. Try moving back to Root namespace

**Expected behavior**
Move to the root namespace and list down all the namespaces available

**Environment:**
* Vault Server Version  - Vault 1.6.3+prem.hsm
* Server Operating System/Architecture: Windows Chrome - Version 89.0.4389.72

**Comment by aphorise** [comment]
The UI behaviour in the most recent versions (1.11.x) is different where only a single login can be made against any namespace switch made in the UI instead of allowing for changing between namespaces.

Hey @spg7484 have you tried the most recent version and if so is it ok to close this issue?

**Comment by aphorise** [comment]
Closing due to no follow up. Please re-open if still relevant.
