### ISSUE TITLE
Vault pods sealing by itself and requires unseal manually

### ISSUE THREAD

**Issue by sjoel** [hashicorp/vault#11144]
Hey team,

Vault pods are sealing itself and requires to be manually unsealed by following the article
https://www.vaultproject.io/docs/concepts/seal

Is this a known issue and any fix available?

This is blocking our Azure DevOps pipeline deployments as the application is trying to read secrets from the vault but is sealed. 

Let me know if you require more details.

Thanks

**Comment by ncabatoff** [comment]
Hi @sjoel,

It's known that Vault nodes can seal themselves in some extreme circumstances, like if a storage level error occurs during certain critical operations.  Have you looked at the server logs preceding the sealing?

**Comment by sjoel** [comment]
Thanks for the response. Vault is running as a pod in openshift environment and couldn't check the pod logs prior to unseal. But can keep an eye on the logs the next time. Is there a way to reduce this occurence from happening as this is causing the pipeline deployments fail to fetch the vault secrets?

**Comment by sjoel** [comment]
Hi team,

Is this a bug with any specific version? we had the same issue again now.

There is not much information in the logs but just says
"vault is sealed, code 503 errors, retry attempt 7 after 16s"

Thanks

**Comment by ncabatoff** [comment]
I think my colleague was a bit hasty in applying the `bug` label.  We don't know enough about what's happening yet to treat this as a bug.  Can you share the logs with us?  If you'd rather not put them in GH, you can email them to me, my email address is my GH username @ hashicorp.com.

**Comment by aphorise** [comment]
This general happens in scenarios like for example:  
 - where there are issues with the autounseal mechanism (if applicable) 
 - if as mentioned earlier there's issues during critical store related operations.
 - connectivity issues between leader & follower standby nodes.

hey @sjoel I wonder:
 1. have you retested this in a more recent (1.11.3) version?
 2. [`TRACE` log_level](https://www.vaultproject.io/docs/configuration#log_level) entries from leader & follower nodes when this happens?
 3. how applicable is this issue for you still?

**Comment by aphorise** [comment]
Closing as there's been no follow-up. Please re-open if still relevant.
