### ISSUE TITLE
[Plugin Portal] Plugin Submission - <TFE/TFC Authentication backend>

### ISSUE THREAD

**Issue by gitrgoliveira** [hashicorp/vault#11202]
Please provide details for the plugin to be listed. All fields are required for a submission to be included in the [Plugin Portal](https://www.vaultproject.io/docs/plugin-portal) page.

**Plugin Information**
Name as it would appear listed: TFE/TFC Authentcation Plugin
Plugin type (secrets/auth/database): auth
Repository link: https://github.com/gitrgoliveira/vault-plugin-auth-tfe

**Comment by calvn** [comment]
Thanks for the submission! It should be up on the portal now.
