### ISSUE TITLE
Unclear error with AWS Authentication: "Invalid request header: X-Amz-Security-Token"

### ISSUE THREAD

**Issue by sriedel** [hashicorp/vault#11210]
**Describe the bug**
Following https://www.vaultproject.io/docs/auth/aws to set up IAM authentication for EC2 instances, I'm at the step where I'm attempting to login for the first time. I'm using the vault login convenience method as described in https://www.vaultproject.io/docs/auth/aws#perform-the-login-operation

    $ vault login -method=aws header_value=$VAULT_SERVER_HOST role=$VAULT_CLIENT_ROLE
    Error authenticating: Error making API request.
    
    URL: PUT https://$VAULT_SERVER_HOST:8200/v1/auth/aws/login
    Code: 400. Errors:
    
    * invalid request header: X-Amz-Security-Token

Replicating the call as a cURL command from the -output-curl-string option of the vault login command, adding -i and --verbose flags gives the response:
    
     HTTP/2 400
    cache-control: no-store
    content-type: application/json
    content-length: 60
    date: Fri, 26 Mar 2021 06:32:06 GMT
    
    {"errors":["invalid request header: X-Amz-Security-Token"]}

This error message is unclear as to who encountered the error (the vault client, when attempting to gather the required data from the AWS environment, or the vault server when trying to verify the provided authentication data? I'm assuming the later here; however is the invalid header encoded in the data provided by the client somewhere, or is this with the vault servers direct communication with the AWS STS service?), why the header is invalid (was one seen at all? if so, what was the content and which part is considered invalid? is the mere existance of the header considered to be invalid?), and what can be done to address the issue (the vault documentation doesn't seem to mention this header at all). Checking the vault server logs, nothing about this request or the error was logged.

**Expected behavior**
An indication in the error message as to which party encountered the header in question and why the header is considered invalid, in order for the user to have an idea on how to proceed.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.5.2
* Vault CLI Version (retrieve with `vault version`): 1.6.3
* Server Operating System/Architecture: Linux, Ubuntu 18.04 LTS, intel 64 bit

**Comment by sriedel** [comment]
Just on a hunch I added the header to allowed_sts_header_values in auth/aws/config/client, and kept adding headers as they popped up in the same error message, in the end I had added X-Amz-Security-Token,X-Amz-Date,User-Agent,Authorization,Content-Length,Content-Type,X-Vault-Aws-Iam-Server-Id however then the headers in the error message started repeating those I had explicitly allowed (and vault read auth/aws/config/client does not show the allowed_sts_header_values key.

Now, invoking the vault login command from the original ticket description just results in an invalid request header error with one of the headers above.

**Comment by sgmiller** [comment]
I believe this issue was fixed in Vault 1.5.3, can you try upgrading?

**Comment by sriedel** [comment]
Sorry for the long response time; I've upgraded the server to 1.5.7 and this has indeed solved the problem. Thanks for your help!
