### ISSUE TITLE
Dead links in role tab

### ISSUE THREAD

**Issue by sullrich84** [hashicorp/vault#11254]
**Describe the bug**
All links on the `role` tab (*/ui/vault/secrets/database/list?tab=role*) link to 
`show/some-role` which results in 404 error responses.

**To Reproduce**
1. Create a new role

**Expected behavior**
Links should redirect to `show/role/some-role` instead.

**Environment:**
* Vault Server Version 1.7.0

**Comment by hashishaw** [comment]
Thanks for reporting @sullrich84! We'll get this fixed ASAP. As a workaround, you can click on the white space of any of those list items rather than the text, and it should take you to the correct place.

**Comment by mladlow** [comment]
Since it looks like we have a fix to be released in 1.7.2, but I _think_ I linked it too late for the merge to automatically close this issue, I'm going to go ahead and close it.
