### ISSUE TITLE
Uploading JSON file with vault write escapes JSON

### ISSUE THREAD

**Issue by grobinson-blockchain** [hashicorp/vault#1125]
I'm trying to figure what is the expected behaviour of `vault write` when using the `@` prefix to upload a file, for example, `vault write secret/mysecret value=@secret.json`.

I expected that vault would require the file to be valid JSON and then store the JSON in the data attribute. However, it appears that the contents of the file are simply escaped and inserted as-is, whether valid JSON or not.

Is there a way to write a JSON file to vault such that the JSON is stored as is rather than in its escaped representation? If not, would you be willing to accept a pull request for such a feature?

Thanks for making such great software!

**Comment by jefferai** [comment]
I believe that this is due to the CLI treating the input file as a string. If you use the API directly, it should be possible to set and fetch pure JSON values.

**Comment by AnonymousRandomPerson** [comment]
This is still open, although I've had success with writing JSON values by using the -format=json option.
`vault write -format=json <path> @<filename>.json`

**Comment by jefferai** [comment]
`format` is only an output option. But yes, using `@` with a file will upload directly. The difference with the OP is that he was assigning a key (`value`) to have a value of the JSON file, so it was necessarily treating that as a string and escaping as needed.

Closing.

**Comment by AAGJKPRT** [comment]
vault write secret/data/Frontend.WebApp.Dev/V1 value=@payload.json
Error writing data to secret/data/Frontend.WebApp.Dev/V1: Error making an API request.
URL: PUT http://127.0.0.1:8200/v1/secret/data/Frontend.WebApp.Dev/V1
Code: 400. Errors:
* no data provided

Any example of how to use this json upload?

**Comment by jefferai** [comment]
Also, if you are wanting to use CAS or other values in the options field, you need to either use the `-cas` flag to `vault kv put` or use the HTTP API, because the command will take everything you give it and put it in the `data` field as you can see in the output above.

**Comment by AAGJKPRT** [comment]
@jefferai 
Appreciate your help.
Yes I am using KVv2 and wondering why it is not working for my case, This time it says :
`vault write kv/test value=@payload.json`
Failed to parse K=V data: invalid key/value pair "value=@payload.json": error reading file: open payload.json: The system cannot find the file specified.

File data:
`{
	"data":    {
			"Key1": "Value1",
			"Key2": "Value2",
			"Key3": "Value3",
			}
}`

**Comment by AAGJKPRT** [comment]
When I am trying using CRUL Command it worked!
any clue why not working for `Vault write` ?
`curl  --header "X-Vault-Token: ..." --request POST --data @payload.json http://127.0.0.1:8200/v1/secret/data/testing.app`

**Comment by clanesf** [comment]
For anyone else who comes across this very old issue, you can do this by passing the json data in this format
`vault kv put -format=json <key path> @filename.json`

The json file in question should be formatted as such
```
{
   "key": "value",
   "key2":"value2
}
```

**Comment by tbielawa** [comment]
> For anyone else who comes across this very old issue, you can do this by passing the json data in this format `vault kv put -format=json <key path> @filename.json`
> 
> The json file in question should be formatted as such ...

I'd like to add a slight clarification about this example. It's correct because it uses double-quotes around the keys and values. If you write with single quotes around keys/values it will throw the confusing `Failed to parse K=V data: invalid key/value pair "@certs_corp_pki.json"` error message.

This too me more time to figure out that I'd like to admit :+1:

**Comment by jefferai** [comment]
Yes -- double quotes are mandated by the spec, see https://www.json.org/json-en.html

**Comment by rembun** [comment]
Hi,

I am able to write json on vault without any issue using the below command and read 

vault write secret/aws/security/dev/asw-security.json @asw-security.json

to read json format

vault read -format=json secret/aws/security/dev/asw-security.json

all done

**Comment by jeffmccune** [comment]
This works with bash to copy secret data without writing to a file:

```
vault read -format=json one/data/mysecret | jq .data | vault write two/data/mysecret @/dev/stdin
```
