### ISSUE TITLE
Clarification -- Default port

### ISSUE THREAD

**Issue by nandhusriram** [hashicorp/vault#1126]
How do I change the default port from 8200  , while running in dev mode?

**Comment by jefferai** [comment]
Hi @nandhusriram,

Dev mode is opinionated -- you cannot change any of its settings. You could run Vault with the `inmem` backend in non-dev mode, but you would need a configuration file and to init/unseal it.

**Comment by nandhusriram** [comment]
Thanks I tried that but  vault init still looking for port 8200. Here is my config

listener "tcp" {
  address = "127.0.0.1:8300"
  tls_disable = 1
}
backend "inmem" {
}

**Comment by jefferai** [comment]
@nandhusriram my guess is that you're still passing `-dev` when using that config :-)

**Comment by nandhusriram** [comment]
This is what I am doing

myserver:/var/opt/vault> sudo ./vault server  -config=./vaultconfig.hcl &
[1] 31707
@myserver:/var/opt/vault> ==> Vault server configuration:

         Log Level: info
             Mlock: supported: true, enabled: true
           Backend: inmem
        Listener 1: tcp (addr: "127.0.0.1:8300", tls: "disabled")
           Version: Vault v0.5.0

==> Vault server started! Log data will stream in below:


myserver:/var/opt/vault> ./vault init
Error initializing Vault: Put https://127.0.0.1:8200/v1/sys/init: net/http: TLS handshake timeout

**Comment by vishalnayak** [comment]
@nandhusriram You will have to change VAULT_ADDR environment variable to point at 8300, as well.
Vault is listening at port 8300.

**Comment by nandhusriram** [comment]
@vishalnayak Got it didnt think about  exporting the vault addr. Thanks

**Comment by jefferai** [comment]
@nandhusriram Or you can use the `-address` parameter to the Vault client for the same effect.
