### ISSUE TITLE
POST on `/sys/leases/revoke` endpoint with specific payload causes internal server error

### ISSUE THREAD

**Issue by matusf** [hashicorp/vault#11308]
**Describe the bug**
Making a POST request on `/sys/leases/revoke` with specific payload causes internal server error

**To Reproduce**
Hi, I was fuzzing vault and found this bug. To reproduce it, just run `vault server -dev` and make a request. The request is described in enclosed zip (single JSON file inside). The JSON has also the `curl` formated of the request, however, the request contains some wild unicode characters that your terminal may not like (at least mine does not :smile:). Therefore is better to use the `resender` utility that I made (along with the fuzzer). You may find it in my [repo (github.com/matusf/openapi-fuzzer)](https://github.com/matusf/openapi-fuzzer), with all installation instructions. Basically just run `openapi-fuzzer-resender file.json` to make the request.

This issue might be related to https://github.com/hashicorp/vault/issues/11306 as there is the same response & lag message.

[sys-leases-revoke.zip](https://github.com/hashicorp/vault/files/6275058/sys-leases-revoke.zip)

See error from request: `"{\"errors\":[\"no namespace\"]}\n"`
In logs: 
```
[WARN]  core: error looking up namespace from the token's namespace ID: error="no namespace"
```

**Expected behavior**
Response with non 500 status code.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
{
    "cluster_id": "ff96e72d-8a50-1574-3044-567db781e3c3",
    "cluster_name": "vault-cluster-f4d3b0c5",
    "initialized": true,
    "migration": false,
    "n": 1,
    "nonce": "",
    "progress": 0,
    "recovery_seal": false,
    "sealed": false,
    "storage_type": "inmem",
    "t": 1,
    "type": "shamir",
    "version": "1.7.0-rc1"
}
```
* Vault CLI Version (retrieve with `vault version`): `Vault v1.7.0-rc1 (9af08a1c5f0f855984a1fa56d236675d167f578e)`
* Server Operating System/Architecture: Ubuntu 18.04/x86_64

**Comment by aphorise** [comment]
Closing as I believe this issue was specific to the rc1 release of that time and I've tested in 1.10.5 and get a valid HTTP-403 response code:

```shell
curl -v -X POST -d '{"lease_id":"󈻻𮤰󴜸𶇺󌸝𝅘𝅥𝅱􉤁󈐠󾄏𫟹񪲖񯣁񛪊漓񖱂󖃿򋷍񸶕񲳛󘦢򚈐𦲜󅬵񼕡񑋍񅞽𓷾񗮸􌾶񔖧󠌵񁩢𿆢Ⅰ𲧫򣴤򪐯𙙒𠮐򕀒徎􋜳򽩴񗓒񘧩肇񊎎痬󆝝񎵅򦢼񄳕򗙜񖩺󚣂󗬢󰩻򨣦񳯔𡭊𺱺柫ﶱ랶󃒃򲃤󉈥𡨫󃜻񚃮򦥚򈉑􌍾񔞦񷆊 𘞆񆅇񴅞򝿇𞘇󗭒򼍬󎈽򨲕򑯘򀣕󺄗򫸦󡚅𐕟彳񗊟񙃬ᙔ񛚶􍕩渨󂽈񿗏𰄚󙫟񗠺󠢶򩺖𗱷񴉳𬋱񞥜񰚶󬟠񰽶񚘖𾦍񰞁𔃨񕅒󥞭򈁋񜘯󼩧𩁰򷺿寉󨅡򚢨񕎽𴰄񉙒򻾱󉿐𨉆򞉯񷄘𩟾񖿦󿯞󹾃򪹹񱿊𣔛𬀜򚄲󻖠󦸂񉡺嗟񴽒󳣌𦉪􃂽񟻏򆶄񇙋񴍳󚿍򢴝󡻯󲮨󢒜󨳠򳺟򓱊󼓏󴍬򉟗𯒶򟦑󺅎񲔯󘥫􌸴󌋛򶑈􀿄񜧖󆕯𐑶󊁍ấ󧜱񂇫􊺛𔀇򍦤򓌠񤓈󹷸󙔎􎣓󦧒񻒳񔉚򐄺􍹼𞺉񆴽󵲃򠁈󚁺􍖌󫏠򡈦򌯁񥧘򊡓򤎔򛿕𹬲󯗬񩊣󰼜򉇠󑞨밇񉠭򢊣󭛜򧎑񻜂𫴅򎫀󣷌񾯨򋎨򤏜򟢃򕙢ᠷ󅯄𹀖󒟈󴿢󉁊񥹇󁽡񷙢񩌀򩯏𶜱􃪡򣨳򣱗򠄕𦇑􏠬񁼟񮺍򙖷򷵫򿭕𔍘񗔦󗶊򍝋񎴐󐭶􃁏򬅊𨈕򢍷󧣙󜇺񕆆򴛽󘮿򋞶󬃰󙂝𵞽󃦸򜫬񝃴򅂮饁򇜮󹼁򾷥𣜉𴯬򵇒𔁽񈟐𵐜񤑷򥏗򬐶񻿕󑼹񅐕󨫈𻽛󩘺󹲦񀁉񉫷󕡷󚃻񟬩񒲓𐞽򻤥󤣝󴔺􂡓񳍯񖺣􆌌󌤿񲥱񰟢񁪍񡡲󳼽𤎾􎹵󺢰󑎡󶨐𽗊𜥫񻓡󅘂򽰓񜇧񊑍󡭋𖇶󌵵򄞍𴿆񥹑򉴡󑛁񫯺򩻦򳖆񴚚󕣩񍃝񖄨󛇊ᕯ񦺩𢥡򟗛𔁞󳅮񭚫􈉰񓆺𑖂򆐨󿂘󑕼𸙱򃻥󳑓񩩻򰣴.𩀕񋹱񘫉𣻪򻅗𪭃򱀔񜾍󪭻󞒪򟥅󔌵򦟬󇙢񿮤𩽎򴉼񞫖񈱽񚣓𠷤𘪫񫳰󮈑񦕁򲩥񺼫򇯹򑺑񜭚㼺󖱾򮍹򴭚񈗯񧿷󹆧񺚨񡛐򟉵򘿀񲝹󪀮򞻮𕥿񝗁􈪬􈿿􈾒񢱖𖴚󪁼󹙬󽐶񨤵񉦘򡭫򴽊󜷃𦻖򬉒𦱄񓥹𻀷񏡉󀺍󲨷򐪔󡆉󏂑򜪑򷬻󽬤󼯗򲿉򨌴񅴜򡹂󳬺򃄞񛀨񕎨🇓񛵷󙪕񐙞𚫅򖣪򒘯𺛦𰶇񕱎񗏝𠜕񟴥򳉔򓣈󪚤򾰻񩄹˚󚰻񃤖󙾌𿰗򁋟𽫎񫆡񮌉󢉨𕤔򘹯􇽌󎸥򂹈󭘩򶯌謪򤐾񶇫󺹙񻣻򢣨򽓵񚰎𕵡򸚩񬓤񠋡􊆷񫟤񘽦񿁠򫗗࿀񞅛󢖕򝁤򦜕򠒥򷌇􃢐󿚛󥻴񕼤񅽘񂛯񎬑񽮱ꀿ򘴂򮓏􎁢󓶳񀗙򦠕򞎛񕭄󧔚멎󢵾񭽼򡭢𑚤𖋆𙔷𕙸𮘂󡼴󌾑𱑑򃬵񜛐ᢱ񛐙񥲌񴻰󎊫񹾥󫶜򦍭󏟶򞨘󣶘𽼦񐕥㠌փ􃗌𷝣񯅪񘵪򌚱󯌳󉨓򗸃񒐿񹗍𡱈󂙮㍞򠳁򢏅𬿋񊓟񹃥𗤫񖘚򧛅񔢼⤫𜌨󜂏󯨽򮶅𘠴􎠦􁗌򃚏򅡴񍲥󋱪򦻧󱜙󺍿򅭤򟭉񈓩򲵩󪷺񫧳󘯦𛷳𷍰󫂨󁗎񓜆𐬎򻏎󣗉󝆾񂇟񴟭񾃰񍶝񿅵󆅓󽴒񨪙󱂌𫈟񕠸񫺦𼳎󅆀򀛢񴃡񇠧򤟰󳉠򐌄󸄉𻮧𱰆㟓󶷙򇳼񤰤񐙑򩝵ﺿ𔍸󢞁󋡇𝅎񤑔񌑧򠪳򋂉򢒙񁁡򊳈򤗛󡛶񦜛󱞅󲙫󁃲𕝿𶸡􈃡󊁢񗚗񽉻𺟭򠹰􈽎򤕅󰵥콉嬽񬽳􂽻񕪋𩁏𙃢𰇄𞪤񈖧𯑪𴷖񯟜򋕵𩯔򆶐󙙧񭲳򅍧񯣺򜨁𿍙󓠂󴘶𰆩𢹷񣚣论󟉇񣂎򕸚񃞝𺮟򐽾𳾠󙨗񰸘󼛾򑿌󃄥􊸎𻱍𪟰󤅔񁾁񡌖󹾘򉠫񯁢𳀁򁭕񳋟𸤭񹎓쏿𕷦󞘳򭲌𵛚𜕉𣆬𪳻𩮹𱞲񸗘𭓈󒭀򀙮򚓼󎎭󚊉󼉫󹵐󕼘󃚇򏮹󓾻򨌫𸿳򧄌􊼳򁶕䤷𰙅򇸥򠤜󛮿󱔠󹉬󽘪󰲘󖐀󰚽򸞐򲩺󺾕𢦝󒆙𯖻񉺐򄺒𾪊𛔐򡛘񮈶󙽔򪾬󝾮𚄠󳈹󐭋浃𙚾𦁝𣥅􂀍񱃽񛍉񂗐󔉑𲠨󢕦򊂮𗷽񡵙󵑯󉢄򵶍񾩾񸸴񍪓󦼿𪐿🅙􈿜󇰓򰆘򹆿򕲘𤦸𶚛򍇄􀶊񻺄󦐥𦳹𚆈󦫔򠜕򖻇򒰊𠍅񪴥𩌬󗠨򒕫򖛔󳎞󌫷򍛹񫣇󶿣򶛴","sync":true,"url_lease_id":""}' ${VAULT_ADDR}/v1/sys/leases/revoke
  # < HTTP/2 403
  # # //...
  # {"errors":["permission denied"]}
```

Hey @matusf thank you for reporting this when you did.
