### ISSUE TITLE
POST on `/sys/seal` endpoint causes internal server error

### ISSUE THREAD

**Issue by matusf** [hashicorp/vault#11304]
**Describe the bug**
Making a POST request on `/sys/seal` endpoint causes internal server error

**To Reproduce**
1. Run `vault server -dev.`
2. Run `curl -X POST http://localhost:8200/v1/sys/seal`
3. See error: `{"errors":["1 error occurred:\n\t* missing client token\n\n"]}`

**Expected behavior**
Get response with non 500 status code.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
{
    "cluster_id": "ff96e72d-8a50-1574-3044-567db781e3c3",
    "cluster_name": "vault-cluster-f4d3b0c5",
    "initialized": true,
    "migration": false,
    "n": 1,
    "nonce": "",
    "progress": 0,
    "recovery_seal": false,
    "sealed": false,
    "storage_type": "inmem",
    "t": 1,
    "type": "shamir",
    "version": "1.7.0-rc1"
}
```
* Vault CLI Version (retrieve with `vault version`): `Vault v1.7.0-rc1 (9af08a1c5f0f855984a1fa56d236675d167f578e)`
* Server Operating System/Architecture: Ubuntu 18.04/x86_64

**Comment by aphorise** [comment]
I believe this issue was specific to the rc1 build and having tested 1.10.5 I can confirm that it's no longer applicable.

```shell
curl -v -X POST ${VAULT_ADDR}/v1/sys/seal
  # < HTTP/2 403
  # # ....
  # {"errors":["permission denied"]}
```

Hey @matusf thanks for reporting this when you did.
