### ISSUE TITLE
Support for Okta Number Challenge 

### ISSUE THREAD

**Issue by rade4404** [hashicorp/vault#11329]
**Is your feature request related to a problem? Please describe.**
In March, Okta released a new Number Challenge feature for Android and iOS users with Okta Verify for high risk sign-in attempts.  My company has this feature enabled and after accepting the Okta Verify Push notification, the CLI and UI do not return the random number that Okta needs to verify the sign-in attempt.  The Vault CLI and UI sits for a period of time and will finally timeout.  It is possible to authenticate with the new Number Feature, but you have to guess the correct number through the Okta app, so you will have to authenticate to Vault until you are lucky enough to guess the correct number.  Once you have guessed the correct number, it does not prompt you again for the number challenge.

**Describe the solution you'd like**
Could you please update the Okta auth backend to support the new Number Challenge feature from Okta.  This article... 

https://help.okta.com/en/prod/Content/Topics/Mobile/ov-admin-config.htm?cshid=csh-okta-verify-number-challenge-v1#enable-number-challenge 

The 2nd bullet point under the "Before you begin" section.  Here is Okta's Response example:

https://developer.okta.com/docs/reference/api/authn/?_ga=2.205809299.1082730225.1617980049-952871850.1598631336#response-example-waiting-for-3-number-verification-challenge-response

**Describe alternatives you've considered**
I am currently running 1.6.3, but have been looking to upgrade to 1.7.0, so users can take advantage of the Okta totp support, if they receive the Number Challenge.

**Comment by trodemaster** [comment]
Supporting numbers challenge needs to happen with LoginMFA capability.

**Comment by austingebauer** [comment]
Hello! Support for the number challenge was introduced to the Okta auth method in [1.11.0](https://github.com/hashicorp/vault/blob/main/CHANGELOG.md#1110) via https://github.com/hashicorp/vault/pull/15361. I'm going to close this issue now.
