### ISSUE TITLE
Vault 1.7.0 (with Raft) Follower Node Joining Fails (works with v1.6.0)

### ISSUE THREAD

**Issue by coofercat** [hashicorp/vault#11323]
**Describe the bug**

A fresh install on Vault 1.7.0 (onto Centos 8, from RPMs in the Hashicorp repo), with Raft storage fails to join an initialised node, with a 500 error from the leader saying `Preventing server addition that would require removal of too many servers and cause cluster instability`. This prevents second (follower) nodes joining a Raft cluster. Downgrading to 1.6.0 solves the problem (no other changes required).

**To Reproduce**
 1. Take a fresh Centos 8 machine, install the Hashicorp repo and then vault. Configure vault with something like this:
```
storage "raft" {
        path = "/opt/vault/raft"
        node_id = "vault1"

        retry_join {
                leader_api_addr = "https://vault1.internal:8200"
                leader_ca_cert_file = "/opt/vault/tls/cacert.pem"
                leader_client_cert_file = "/opt/vault/tls/vault1.internal.crt.pem"
                leader_client_key_file = "/opt/vault/tls/vault1.internal.key.pem"
        }
        retry_join {
                leader_api_addr = "https://vault2.internal:8200"
                leader_ca_cert_file = "/opt/vault/tls/cacert.pem"
                leader_client_cert_file = "/opt/vault/tls/vault2.internal.crt.pem"
                leader_client_key_file = "/opt/vault/tls/vault2.internal.key.pem"
        }

}

listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/opt/vault/tls/vault1.internal.crt.pem"
  tls_key_file  = "/opt/vault/tls/vault1.internal.key.pem"
}

performance_multiplier = 1
cluster_name = "mycluster"
disable_mlock = true

cluster_addr = "https://vault1.internal:8201"
api_addr = "https://vault1.internal:8200"
ui = true
```
2. Start vault and use the UI to initialise a new Raft. Unseal the vault and verify it seems to be working correctly.
3. On a second, fresh machine, apply an almost identical config (except the raft node_id)
4. Start the second vault, head to the UI and note it will be asking for an unseal key.
5. Enter the unseal key - note that the page does not change/reload or acknowledge the key being entered
6. Observe the log (/var/log/messages) says things like:
```
Apr  8 16:06:58 vault2 vault[73788]: 2021-04-08T17:06:58.569+0100 [INFO]  core: security barrier not initialized
Apr  8 16:06:58 vault2 vault[73788]: 2021-04-08T17:06:58.569+0100 [INFO]  core: attempting to join possible raft leader node: leader_addr=https://vault1.internal:8200
Apr  8 16:06:58 vault2 vault[73788]: 2021-04-08T17:06:58.627+0100 [WARN]  core: join attempt failed: error="failed to send answer to raft leader node: Error making API request.
Apr  8 16:06:58 vault2 vault[73788]: URL: PUT https://vault1.internal:8200/v1/sys/storage/raft/bootstrap/answer
Apr  8 16:06:58 vault2 vault[73788]: Code: 500. Errors:
Apr  8 16:06:58 vault2 vault[73788]: * Preventing server addition that would require removal of too many servers and cause cluster instability"
Apr  8 16:06:58 vault2 vault[73788]: 2021-04-08T17:06:58.628+0100 [INFO]  core: security barrier not initialized
Apr  8 16:06:58 vault2 vault[73788]: 2021-04-08T17:06:58.628+0100 [INFO]  core: attempting to join possible raft leader node: leader_addr=https://vault2.internal:8200
Apr  8 16:07:58 vault2 vault[73788]: 2021-04-08T17:07:58.628+0100 [WARN]  core: join attempt failed: error="error during raft bootstrap init call: context deadline exceeded"
Apr  8 16:07:58 vault2 vault[73788]: 2021-04-08T17:07:58.629+0100 [ERROR] core: failed to retry join raft cluster: retry=2s
```
7. Stop both vault processes.
8. Delete /opt/vault/raft/*
9. Downgrade vault to 1.6.0 (yum downgrade vault-1.6.0-1)
10. Repeat the above steps, but observe that the secondary node joins the leader immediately, and the logs show success, and also the UI on the secondary allows the unseal and then moves to normal UI operation.

**Expected behavior**
Secondary/follower nodes should join the leader correctly.

**Environment:**
Centos 8
Vault 1.7.0 (and Vault 1.6.0)
x86_64

**Comment by briankassouf** [comment]
Thanks for filing this issue! Could you find the logs from the active node at around the time the follower failed to join? Additionally could you do a `vault operator raft list-peers` on the active node?

**Comment by briankassouf** [comment]
Also, in vault2's configuration are you updating these two fields as well?

```
cluster_addr = "https://vault1.internal:8201"
api_addr = "https://vault1.internal:8200"
```

If not, AutoPilot will think you're trying to replace the node with this address. Which results in attempting to remove node1 and an error since you cannot remove the only node in the cluster.
