### ISSUE TITLE
AWS Dynamic Secrets to support SES SMTP password

### ISSUE THREAD

**Issue by feiming** [hashicorp/vault#11336]
**Is your feature request related to a problem? Please describe.**
AWS SES SMTP requires `secret_key` to be converted to SMTP password. Not every system that utilise SES SMTP password have the capability to convert `secret_key` into SMTP password.
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html#smtp-credentials-convert

**Describe the solution you'd like**
Define a SES SMTP path in AWS Dynamic Secrets. All roles stored this path returns SES SMTP password instead of `secret_key`. 

**Describe alternatives you've considered**

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by BeryJu** [comment]
@feiming Any reason for closing this? Looking through the docs this is still an "issue"/has to be solved externally
