### ISSUE TITLE
OIDC flow -  Cannot add/remove policies assigned to external group, as IDP only knows group name not group id

### ISSUE THREAD

**Issue by creslinux** [hashicorp/vault#11335]
https://github.com/hashicorp/vault/pull/10812 had the unexpected? impact of breaking the API to be able resolve a group-id from external group name.   

An impact for solutions that make use of groups from an IDP over OIDP such as Auth0, Keycloak, Okta etc is only the Group name is known, not the internal vault assigned group-id, from the IDPs userinfo.

External logic trusting the IDP as source or truth of what groups the user is part of cannot dynamically update vaults existing external groups with new policies, as unable to resolve the group-id from name to do so.

see: https://github.com/hashicorp/vault/issues/10223#issuecomment-802953284
also: https://github.com/hashicorp/vault/issues/11334

**Comment by mladlow** [comment]
Hi @creslinux in answer to your question on the other issue, you can discover the ID from the name via `vault read -field=id identity/group/name/<group name>`. I think this should work for internal and external groups. I see what you mean about breaking the OIDC Auth Method guide (I think you're talking about this one https://learn.hashicorp.com/tutorials/vault/oidc-auth) - once you've already created the group, just running the command again won't get you the group ID. I've submitted a PR to update the learn guide.

**Comment by creslinux** [comment]
> Hi @creslinux in answer to your question on the other issue, you can discover the ID from the name via `vault read -field=id identity/group/name/<group name>`. I think this should work for internal and external groups. I see what you mean about breaking the OIDC Auth Method guide (I think you're talking about this one https://learn.hashicorp.com/tutorials/vault/oidc-auth) - once you've already created the group, just running the command again won't get you the group ID. I've submitted a PR to update the learn guide.

Confirmed, can read the group-id from the command suggested - thank you
```
# vault read -field=id identity/group/name/c001_admin
dbd9f462-7774-0b8f-ef81-xxxxxxxxxxxx
```
