### ISSUE TITLE
Separate configuration options and secrets for connections

### ISSUE THREAD

**Issue by johnt337** [hashicorp/vault#1133]
We recently experience this issue #1132 

During that triage, it was difficult to determine what the vault server was doing in terms of configuration versus behavior. We expected the default behavior of 2, but saw hundreds. We had no way to validate the config without a root token.

Is there a way to trace vault activity? #667

While trying to maintain effective security policies against a keyspace...is there a way to make certain information visible? Such as connection info and the number of connections to an instance while still preserving the secrets?

Similar to how noted here:

```API

/mysql/config/connection

POST

DESCRIPTION
Configures the connection DSN used to communicate with MySQL. This is a root protected endpoint.
METHOD
POST
URL
/mysql/config/connection
PARAMETERS
value required The MySQL DSN
max_open_connections optional Maximum number of open connections to the database. Defaults to 2.
RETURNS
A 204 response code```

from https://www.vaultproject.io/docs/secrets/mysql/index.html

**Comment by jefferai** [comment]
@johnt337 If you've had the backend around for a while, it's possible you configured it before the options were added to control the number of connections/idle connections, in which case it'd default to 0 (unlimited), not 2, until you re-posted to the connection endpoint. You don't say what version of Vault you're running but keep in mind that the website docs always correspond to the latest released version of Vault.

**Comment by johnt337** [comment]
Sorry for the delayed response. So it was vault 0.5.0 (possibly the rc) if I recall, upgraded from 0.4.2.

I was not involved in the original implementation, only recently and so I really can't speak to what what there in terms of initial configuration. I can only talk to looking at this recent situation where we upgrade from the 0.4.x family to the 0.5.x family.

I was investigating a "too many open file handles" error when we stumbled upon the large number of DB connections. I did not look back at the version specific docs for 0.4.2, as you said I read the current release version docs.

We are exercising permissions that lock down read of connection info. So this may be a matter of our policy versus vault functionality.

I guess overall is a desire to maintain operational visibility whilst ensuring operational security.

**Comment by jefferai** [comment]
@johnt337 If you're running an RC of 0.5.0 I do recommend that you upgrade to the final release (or, at this point, 0.5.1).

The "too many open file handles" issue was a bug with an upstream dependency that should be solved in 0.5.

I'm not entirely sure what the ask is here. What is it you are looking for Vault to do?

**Comment by johnt337** [comment]
Thanks for the follow-up. Will make sure we are running stable. 

I was asking for a way to interrogate connection info without divulging secrets associated with the connection.

**Comment by jefferai** [comment]
Not currently, sorry, but we should have something along those lines eventually.

**Comment by johnt337** [comment]
Thanks for info!
