### ISSUE TITLE
core: failed to read local auth table

### ISSUE THREAD

**Issue by pmbapat** [hashicorp/vault#11338]
**Describe the bug**
Users started reporting 503 errors from Vault. 
Vault would not start.
Logs shows error. `core: failed to read local auth table: error="decryption failed: cipher: message authentication failed`
We restored the Consul backup from a few days back and it started working again. 

**To Reproduce**
This is hard to reproduce. 
Specific to our environment, we did the following.
1. Restore Consul backup from the date when it was failing. 
2. Try start Vault. Fails with above error.
3. From Consul, remove path `kv/vault/core/local-auth`
4. Vault starts ok. Is able to unseal itself. 

This points in the direction of `local-auth` being either corrupt or misconfigured. But issue is, we don't have any local-auth methods in our setup.

**Expected behavior**
Vault should start.

**Environment:**
* 2 Vault Instances backed by 3 Consul servers. 
* Vault version 1.6.0 
* Consul version 1.4.0
* Using AWS KMS for unsealing.
* Has been in use for couple of years. 

Vault server configuration file(s):

```hcl
ui = true

listener "tcp" {
  address          = "172.31.129.96:8200"
  cluster_address  = "172.31.129.96:8201"
  tls_disable      = "true"
}

storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault/"
  scheme = "http"
}

seal "awskms" {
    region= "us-east-1"
    kms_key_id = "-----"
    access_key = "----"
    secret_key = "----"
}

telemetry {
  prometheus_retention_time = "30s"
  statsite_address = "127.0.0.1:8126"
  disable_hostname = true
}

api_addr = "https://vault.example.org:8200"
cluster_addr = "https://vault.example.org:8201"

log_level = "Debug"
```

**Additional context**

**Comment by sgmiller** [comment]
That error message is fairly generic, meaning the value was either corrupted or encrypted with a different key.  Is there any chance another Vault instance was ever configured to use the same Consul backend, or that the master key or unseal method was changed?

**Comment by pmbapat** [comment]
Thanks for looking at this. Much appreciated. 

Master key and unseal method were never changed. 

We have 2 Vault Servers running in HA mode. Where one is active and other on standby. We were upgrading the instance sized (this is AWS) because of low memory. Thats the only time I can think of the active/standby were switched. 

Will it cause this issue ? In that case this would be a bug!

**Comment by sgmiller** [comment]
I don't believe that would do it.  Can you describe the procedure you followed when changing the instance size?

**Comment by pmbapat** [comment]
Basically a stop-resize-start on AWS.

I think this would definitely have switched the active/standby nodes. But should that cause a local-auth to fail? Let me try and simulate this.

**Comment by sgmiller** [comment]
It definitely should not have altered or corrupted storage.  Can you obtain the output of /sys/key-status before and after the restore?  You may also want to hash the keyring before and after to see if anything changed:

`consul kv get  vault/core/keyring|shasum`

**Comment by vishalnayak** [comment]
Closing the issue due to staleness.

Closing stale issues helps us keep the issue count down and the project healthy. Keeping the issue count under a manageable number helps us provide faster responses and better engagement with the community.

If you feel that the issue is still relevant, or if it is wrongly closed, please leave a comment and we'd be happy to reopen it.
