### ISSUE TITLE
service_registration Doesn't Work With Non-HA Backends

### ISSUE THREAD

**Issue by codyja** [hashicorp/vault#11337]
**Describe the bug**
Hi! I'm vault 1.7.0 in a home lab. I'm running Docker on a SynologyNAS appliance and have a set of Raspberry PIs for a consul cluster. For Vault, I'm using the File backend and persisting data to the local NAS the container is running on. When I try to add a service_registration stanza I get the following error and Vault won't start fully:
```service_registration is configured, but storage does not support HA```

I'm slightly confused because I would think the backend shouldn't matter, I just want to register my vault instance as a service in the consul cluster. The docs say:
`service_registration stanza is designed for use cases where you would like to use a system like Consul for service discovery, but use a different system for the storage backend.`

**To Reproduce**
Example Vault config:
```
service_registration "consul" {
  address      = "10.1.100.20:8500"
}

# docker mounts NAS Volume1/vault-backend-data to /vault/file in container
storage "file" {
  path = "/vault/file"
}

listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_disable = "true"
}

ui = true
```

**Comment by sgmiller** [comment]
The message is a little confusing, but what service registration requires is a backend that supports locking, so it can consistently update the service registration.  The file backend does not support this.  You may try the Raft backend for this.
