### ISSUE TITLE
error_on_missing_key no longer working in vault 1.7

### ISSUE THREAD

**Issue by adamstrawson** [hashicorp/vault#11349]
**Describe the bug**
Upgrading from Vault 1.4 to 1.7, the behaviour of the template option `error_on_missing_key` no longer works as expected.

Previously, `error_on_missing_key = false` would result in a `WARN` for a missing key, however on Vault 1.7, it is returned as an `ERROR`

vault 1.4
```
2021/04/13 17:09:35.001560 [WARN] (view) vault.read(secret/foobar/service.v1): no secret exists at secret/foobar/service (retry attempt 11 after "1m0s")
```

vault 1.7
```
2021/04/13 17:09:35.001560 [ERROR] (view) vault.read(secret/foobar/service.v1): no secret exists at secret/foobar/service (retry attempt 11 after "1m0s")
```

**To Reproduce**

Using the below config, which remains the same between Vault 1.4 and 1.7 during the upgrade.

```hcl
exit_after_auth = true
pid_file = "/home/vault/pidfile"

auto_auth {
    method "kubernetes" {
        mount_path = "auth/kubernetes-foobar"
        config = {
            role = "vault-auth-foobar"
        }
    }

    sink "file" {
        config = {
            path = "/home/vault/.vault-token"
        }
    }
}

template {
  source               = "/home/vault/template/vault-secrets.json"
  destination          = "/etc/secrets/vault-secrets.json"
  error_on_missing_key = false
  left_delimiter       = "<<"
  right_delimiter      = ">>"
}
```

```hcl
vault-config-json.tmpl: <<- with secret "secret/foobar/service?version=1">> <<- end >>
```

**Expected behavior**
The secret key `secret/foobar/service` doesn't exist, and since `error_on_missing_key` is `false` a `WARN` should be returned.

**Environment:**
* Vault Server Version (retrieve with `vault status`): `1.7.0`
* Vault CLI Version (retrieve with `vault version`): `Vault v1.7.0 (4e222b85c40a810b74400ee3c54449479e32bb9f)`
* Server Operating System/Architecture: EKS v1.16.15, using the vault helm chart v0.10.0

**Comment by adamstrawson** [comment]
Hey! Hate to be the guy to nudge on an issue, but would be great to get some eyes/feedback on this? It's creating quite a few headaches/noise for us and ideally don't want to have to rollback from `1.7.0`

**Comment by kalafut** [comment]
cc: @calvn as this may be related to the retry changes

**Comment by kalafut** [comment]
@adamstrawson Are you seeing the [ERROR] version of the message only after Agent gives up retrying (after a default of 12 times)?

**Comment by adamstrawson** [comment]
@kalafut Yep `[ERR]` after the retries (we have retries set to `3`, log below;

```
...
[WARN] (view) vault.read(secret/<redacted>/service.v3): no secret exists at secret/data/<redacted>/service (retry attempt 1 after "250ms")
[WARN] (view) vault.read(secret/<redacted>service.v3): no secret exists at secret/data/<redacted>/service (retry attempt 2 after "500ms")
[WARN] (view) vault.read(secret/<redacted>/service.v3): no secret exists at secret/data/<redacted>/service (retry attempt 3 after "1s")
[ERR] (view) vault.read(secret/c<redacted>/service.v3): no secret exists at secret/data/<redacted>/service (exceeded maximum retries)
[ERR] (runner) watcher reported error: vault.read(secret/<redacted>/service.v3): no secret exists at secret/data/<redacted>/service
[INFO] (runner) stopping
[DEBUG] (runner) stopping watcher
[DEBUG] (watcher) stopping all views
[INFO]  template.server: template server stopped
[INFO]  auth.handler: shutdown triggered, stopping lifetime watcher
[INFO]  auth.handler: auth handler stopped
```
 
Because the init container fails, the pod restarts or enters `CrashBackoffLoop`

**Comment by calvn** [comment]
@adamstrawson there was a change on 1.6.0 (https://github.com/hashicorp/vault/pull/9670) where we actually error out after a number of attempts in order to prevent agent from indefinitely running if there's a persistent error.

There's a draft PR on https://github.com/hashicorp/vault/pull/11711 that aims to revert this (i.e. indefinite retry on templating error) by optionally allowing this behavior to happen.

> Because the init container fails, the pod restarts or enters `CrashBackoffLoop`

The flip side to this is that the container would be running happily even though it's not really able to render any secrets. Is this a considered false-positive that can lead to upstream failure, for example on apps that might depend on secrets being rendered?

**Comment by calvn** [comment]
In Vault 1.8 we made adjustments on Agent to allow for indefinite retries. The net result is that Agent should now behave similar to the way it was in 1.5 and earlier, with the option to exit on retry failure if that's desired. Please give Vault Agent 1.8.x a try and feel free to re-open if there are any issues with it.
