### ISSUE TITLE
Vault ssh backend with rsync/scp?

### ISSUE THREAD

**Issue by jaychris** [hashicorp/vault#1134]
Is there any way to make the Vault ssh-backend work with rsync-over-ssh or scp for securely copying files?  It's great for managing access without having to copy keys all over the place, but I would think copying files would be right behind that in priority...

**Comment by mrPsycho** [comment]
@jaychris, why you closed without ANY comment?

**Comment by earthday** [comment]
```
vault ssh [options] username@ip-address cat file.txt > local_file.txt
```
This work for me to copy files from the server to the local.
