### ISSUE TITLE
vault cli: -no-print=true is not honored

### ISSUE THREAD

**Issue by Ravenwater** [hashicorp/vault#11351]
**Describe the bug**
As per documentation, I am using the flag `-no-print=true`  to stop the vault CLI from reporting the token in the log

**To Reproduce**
1. Run `vault login -method=github token=**** -no-print=true`

```
$ vault login -method=github token=*** -no-print=true

Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

Key                    Value
---                    -----
token                  *****
token_accessor         *****
token_duration         12h
token_renewable        true
token_policies         [***]
identity_policies      []
policies               [***]
token_meta_org         vault-auth
token_meta_username    ****
```

**Expected behavior**
I was expecting that `-no-print=true` did not echo the output to the log:
```
-no-print (bool: false) - Do not display the token. The token will be still be stored to the configured token helper. The default is false.
```

**Environment:**
* 1.5.3
* Server Operating System/Architecture: Ubuntu

**Comment by ncabatoff** [comment]
Hi @Ravenwater,

I think you must provide the `-no-print` option *before* the arguments to login.

```
$ vault login -h
Usage: vault login [options] [AUTH K=V...]
```

So it's an option like `-method` in that it precedes the K=V key-value arguments to login.

**Comment by Ravenwater** [comment]
aha: confirmed:
```
$ vault login -no-print=true -method=github token=***
```
