### ISSUE TITLE
etcd: poor error reporting on sync

### ISSUE THREAD

**Issue by stevenschlansker** [hashicorp/vault#1141]
It looks like the error path for `etcd` sync operations [throws away an error](https://github.com/hashicorp/vault/blob/master/physical/etcd.go#L158-L163).

```go
ctx, cancel := context.WithTimeout(context.Background(), client.DefaultRequestTimeout)
syncErr := c.Sync(ctx)
cancel()
if syncErr != nil {
    return nil, EtcdSyncClusterError
}
```
When you hit this error, even with trace level logging, it is extremely confusing what went wrong from an end user perspective:
```
% docker run --cap-add IPC_LOCK --net=host vault server -log-level=trace -config=/config/pp-sf/vault.hcl
Error initializing backend of type etcd: client setup failed: unable to sync etcd cluster
```

**Comment by stevenschlansker** [comment]
The problem ended up being a typo in the etcd host -- so it couldn't resolve.  If that error came out, I would have saved half an hour of debugging :)

**Comment by stevenschlansker** [comment]
Wow, thanks for the quick turnaround! :100:

**Comment by jefferai** [comment]
Hah -- super easy fix, not worth postponing :-D
