### ISSUE TITLE
tls_disable not disabling?

### ISSUE THREAD

**Issue by SephVelut** [hashicorp/vault#1147]
I have a consul server running with `consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul`.

```
backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
}

listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
}
```

Next I run `vault server -config=example.hcl` and receive 

> Error initializing listener of type tcp: 'tls_cert_file' must be set

I don't want to use tls. I haven't set any other configurations, simply following the guide. Tried removing tls_disable, setting it to different values "yes", "false", "", 0, true etc.

**Comment by jefferai** [comment]
That's strange. This is the setup I use all the time for testing:

```
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}
```

What version of Vault is this?

**Comment by jefferai** [comment]
Also, what happens if you put
```
scheme = "http"
```
In the consul section?

**Comment by SephVelut** [comment]
I destroyed the vagrant box `trusty64` and tried again. Works fine now and I can't figure out a way to reproduce the error.

`Vault v0.5.1`
`Consul v0.6.3`

**Comment by jefferai** [comment]
Wow.... a strange situation made stranger...  :-)

**Comment by SephVelut** [comment]
The box was highly tainted so I would just chalk up to the env. I repeated my steps with new boxes and haven't been able to reproduce. 

but after starting vault server I get this error whenever I run a typical command such as `vault status`.
`Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: http: server gave HTTP response to HTTPS client`

`curl http://127.0.0.1:8200/v1/sys/seal-status` without https - returns just fine with `{"errors":["server is not yet initialized"]}`. I tried with and without `scheme = "http"`.

**Comment by jefferai** [comment]
The default address of the client uses https. Just set the -address parameter or set the VAULT_ADDRESS env var and you'll be good to go.

**Comment by SephVelut** [comment]
Thanks for the help.

**Comment by jefferai** [comment]
Sure!

**Comment by brainonmute** [comment]
I've roughly reproduced this error. Following the quick start on Ubuntu with a Consul backend you will get the "http: server gave HTTP response to HTTPS client" if you do not deviate from the directions. If you use the tls_disable = 1 you need to use a command such as vault init -address http://127.0.0.1:8200 to do the first run.

**Comment by HeathNaylor** [comment]
Fixed this by setting `VAULT_ADDR=http://127.0.0.1:8200`

**Comment by kareemyousef** [comment]
Hi, I have the same issue here, I can't initialize the vault either by CLI
`vault init`
which returns 

> Error initializing Vault: Put https://127.0.0.1:8200/v1/sys/init: http: server gave HTTP response to HTTPS client

or HTTP API:
`curl http://127.0.0.1:8200/v1/sys/init`
which returns 

> {"initialized":false}

I have tried both consul and file with no luck. Here is both configurations I tried:

Using consul:

> disable_cache = true
> disable_mlock = true
> backend "consul" {
>   advertise_addr = "http://127.0.0.1:8200"
>   address = "127.0.0.1:8500"
>   path = "vault"
>   scheme = "http"
>   tls_disable = 1
> }
> listener "tcp" {
>  address = "127.0.0.1:8200"
>  tls_disable = 1
> }

Using File:

> disable_cache = true
> disable_mlock = true
> backend "file" {
>   path = "/home/kyousef/vault.stg"
> }
> listener "tcp" {
>  address = "127.0.0.1:8200"
>  tls_disable = 1
> }

Any help will be much appreciated.

**Comment by jefferai** [comment]
@kareemyousef The answer is the same: if using the Vault CLI, set the -address parameter or set the `VAULT_ADDRESS` env var. The `curl` response is correct, so it is working as intended.

**Comment by kareemyousef** [comment]
Thanks for the fast response. I've already set the VAULT_ADDRESS env var to http://127.0.0.1:8200/ and I get the same behavior

**Comment by jefferai** [comment]
Sorry, it's `VAULT_ADDR`.

**Comment by kareemyousef** [comment]
@jefferai , I already tried that before and it didn't work. But, it worked now after I restarted my machine. Seems like a bug. Thanks for your help :+1:

**Comment by joslinm** [comment]
FWIW, I configured my listener as `127.0.0.1:8200` with `tls_disable = 1`and it complained about receiving an HTTP response to an HTTPS client. When I changed the address to `0.0.0.0:8200`, it was ok.

**Comment by jhovell** [comment]
Also seeing this issue using the docker image v0.6.0. 
docker-compose.yml:
```yaml
vault:
  image: vault:v0.6.0
  container_name: 'vault'
  cap_add: 
    - IPC_LOCK
  restart: always
```
command:

```
$ docker exec -it vault vault status
Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: http: server gave HTTP response to HTTPS client
```

Restarting has solved the issue but seems rather random as @joslinm mentions as well.

**Comment by jhovell** [comment]
adding address WITH http:// prepended (undocumented? - most verbiage I've seen says this should be the ip:port not the URL) fixes the problem. Leaving out the http:// gives the unsupported protocol scheme "". 
```
$ docker exec -it vault vault status -address=http://127.0.0.1:8200
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0

```

**Comment by jefferai** [comment]
It's an HTTP API, so the address would normally include the scheme. If a scheme isn't provided the client assumes HTTPS for safety, as assuming an unencrypted connection can lead to various attacks.

**Comment by sysadmin1337** [comment]
I can confirm I get the same with configuration:
```
backend "file" {
  path = "/etc/vault/file"
}

listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = 1
}
```
On manjaro linux. How do I reload the configuration? It's not refreshing my updated edit to make it `0.0.0.0`.

**Comment by jefferai** [comment]
@sysadmin1337 you need to restart Vault

**Comment by sysadmin1337** [comment]
After a restarts it's actually not refreshing my configuration file. Still `Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: http: server gave HTTP response to HTTPS client`.

**Comment by sysadmin1337** [comment]
Error now turned: `Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: dial tcp 127.0.0.1:8200: getsockopt: connection refused`

**Comment by sysadmin1337** [comment]
Running `vault status -address=http://0.0.0.0:8200` returns:

```
Error checking seal status: Error making API request.

URL: GET http://0.0.0.0:8200/v1/sys/seal-status
Code: 400. Errors:

* server is not yet initialized
```

**Comment by jefferai** [comment]
Please paste your configuration file and any VAULT_ env vars.

**Comment by sysadmin1337** [comment]
Started with `sudo vault server -config=/etc/vault/vault.hcl`

`vault.hcl`
```
backend "file" {
  path = "/etc/vault/file"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}
```

No VAULT vars. Still: `Error initializing Vault: Put https://127.0.0.1:8200/v1/sys/init: http: server gave HTTP response to HTTPS client` when running init.

**Comment by sysadmin1337** [comment]
I just successfully started the vault server with the same instructions/configuration on a Ubuntu 16.04 vagrant machine, so I can confirm this must be a bug.

**Comment by jefferai** [comment]
it's not misleading at all...it's telling you exactly what's wrong. You're connecting via https to an http server.

**Comment by sysadmin1337** [comment]
Your right, because you're basically telling the vault client to go to http address while setting the VAULT_ADDR, and default it's probably https when it's not set. Maybe some of the people above also forgot to set the VAULT_ADDR var. Thanks.

**Comment by ianmiell** [comment]
FWIW The vault intro docs need updating, as they don't work out of the box due to this.

https://www.vaultproject.io/intro/getting-started/dev-server.html

**Comment by JithinPavithran** [comment]
Make sure you use the same terminal tab after setting `VAULT_ADDR`.  
This is to make sure that the variable is correctly loaded.  
(Verify the output of `echo $VAULT_ADDR`.)  
I too got this issue in Terminator until I realised that I was trying `vault status` in the wrong Tab.  
__BASH variable set by `export` does not load existing tabs automatically__

**Comment by omarabid** [comment]
@JithinPavithran verifying the output through $VAULT_ADDR was not enough for me. Luckily, export solved the issue. But I'd say this is actually a "Problem" because Vault has to follow what is inside the configuration file and not environment variables (or at least when they don't exist)

**Comment by jefferai** [comment]
@omarabid The configuration file is for the Vault server, not the other Vault commands (in which it acts as a client).

**Comment by omarabid** [comment]
@jefferai Oops I get it now.

**Comment by karimofthecrop** [comment]
I know this is closed, and I am thankful this thread is here. I will say it is non-obvious that you must set VAULT_ADDR for the operator command. Can I suggest it be added to the docs? Is there some reason it isn't already there?

**Comment by jefferai** [comment]
@karimofthecrop You don't need to. You can use `-address` with any CLI command, as documented in in the `-h` output of any CLI command, which also in the same output lets you know that you can set `VAULT_ADDR` instead.

**Comment by karimofthecrop** [comment]
@jefferai - thanks! I didn't see that. I was reading https://www.vaultproject.io/docs/commands/operator/init.html which doesn't seem to have the full complement of flags.

**Comment by haseebeqx** [comment]
no need to restart machine just give the following command
```bash
export VAULT_ADDR='http://127.0.0.1:8200'
```

**Comment by yhamouni** [comment]
Hi everyone, I'm trying to build a vault cluster with a consul backend, on docker, has any one been a success to do that?
My problem I cannot interrogate vault server with a curl !! :/

**Comment by phalcon30964** [comment]
I rebooted and it worked.

**Comment by sasiarivukalanjiam** [comment]
Error was : Error initializing Vault: Put https://127.0.0.1:8200/v1/sys/init: http: server gave HTTP response to HTTPS client
Env: Ubuntu 16.04

Solution : export VAULT_ADDR='http://127.0.0.1:8200' was added in /etc/environment

**Comment by pandugathrinath** [comment]
@jefferai I see the same issue after adding the env variable and in the config file. neither of them worked. 

sudo vault server -config=/etc/vault/config.json
Error initializing listener of type tcp: listen tcp: address http://0.0.0.0:8200: too many colons in address
 export VAULT_ADDR=http://127.0.0.1:8200
sudo vault operator init
Error initializing: Put https://127.0.0.1:8200/v1/sys/init: http: server gave HTTP response to HTTPS client

**Comment by r0039** [comment]
> Make sure you use the same terminal tab after setting `VAULT_ADDR`.
> This is to make sure that the variable is correctly loaded.
> (Verify the output of `echo $VAULT_ADDR`.)
> I too got this issue in Terminator until I realised that I was trying `vault status` in the wrong Tab.
> **BASH variable set by `export` does not load existing tabs automatically**

@JithinPavithran unbelievable,  I got the same issue. Thank you!

**Comment by song-liu** [comment]
Just use
$ vault status -address http://127.0.0.1:8200/

**Comment by yeshu044** [comment]
thank you guys
for your answers...

**Comment by 3cham** [comment]
Have the same problem and I'm lost right now.

Started with following command:

docker run -d --cap-add=IPC_LOCK  --name=dev-vault -e 'VAULT_DEV_ROOT_TOKEN_ID=myroot' -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200' -p 8200:8200 vault

Then set the environments outside with following:
export VAULT_ADDR=http://0.0.0.0:8200
export VAULT_DEV_ROOT_TOKEN_ID=myroot

And expect that running ``vault status`` would show some status, but receiving:
  Error checking seal status: context deadline exceeded
instead. Could anyone tell me what's wrong here?

**Comment by AlexisMateo** [comment]
> Sorry, it's `VAULT_ADDR`.

thanks you

**Comment by stevenvandorpe** [comment]
> Just use
> $ vault status -address http://127.0.0.1:8200/

Thanks for this solution! It seems to be working for me.

It's just quite annoying I have to add -`address http://127.0.0.1:8200/` to every single command. My environment variable `VAULT_ADDR` is set to exactly the same value. Any ideas?

**Comment by Ninjamannn** [comment]
> My environment variable `VAULT_ADDR` is set to exactly the same value. **Any ideas?**

echo "export VAULT_ADDR=http://127.0.0.1:8200" >> ~/.bashrc
source ~/.bashrc

**Comment by pencilcap123** [comment]
Kind of break-down....

I've tried all of the solutions above but none worked. 

here is my docker-compose with official latest docker image `vault:1.6.1` :
![image](https://user-images.githubusercontent.com/41630875/104983180-39925000-5a47-11eb-9212-fea85ccd60c6.png)

and get following error:
```
Error initializing listener of type tcp: error loading TLS cert: open : no such file or directory
2021-01-19T03:13:57.796Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
```

**Comment by pencilcap123** [comment]
> Kind of break-down....
> 
> I've tried all of the solutions above but none worked.
> 
> here is my docker-compose with official latest docker image `vault:1.6.1` :
> ![image](https://user-images.githubusercontent.com/41630875/104983180-39925000-5a47-11eb-9212-fea85ccd60c6.png)
> 
> and get following error:
> 
> ```
> Error initializing listener of type tcp: error loading TLS cert: open : no such file or directory
> 2021-01-19T03:13:57.796Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
> ```

Oops After numbers of try, got a work-around:
compose:
![image](https://user-images.githubusercontent.com/41630875/104984549-d950dd80-5a49-11eb-9fdc-f419c0be0ef7.png)

config:
![image](https://user-images.githubusercontent.com/41630875/104984571-e79ef980-5a49-11eb-9185-58232749a00f.png)
