### ISSUE TITLE
metadata `user` vs `username` inconsistency

### ISSUE THREAD

**Issue by bendemott** [hashicorp/vault#11479]
**Describe the bug**
Metadata for Kerberos auth defines user via "user" key, wheras other auth methods seem to use "username"
If this is intentional and not an oversight please close this issue.  Thanks.

**To Reproduce**
1. Perform vault auth with LDAP, note the response metadata: ``'metadata': {'username': 'admin'},``
2. Perform vault auth with KERBEROS, note the response metadata ``'metadata': {'user': 'admin', 'domain': 'EXAMPLE.COM'}``

**Expected behavior**
I would expect the metadata keys to be as consistent as possible.

**Environment:**
* Vault Server Version: `1.6.3`
* Using CURL
* Server Operating System/Architecture: `Redhat 7`

**Comment by hsimon-hashicorp** [comment]
Hi folks! Is this still an issue in newer versions of Vault? Please let me know so I can bubble it up accordingly. Thanks!

**Comment by raskchanky** [comment]
Since it's been awhile with no response, I'm going to close this issue. Please reopen if there's more to add here.
