### ISSUE TITLE
Certificates added for cert auth are not validated

### ISSUE THREAD

**Issue by carlpett** [hashicorp/vault#1148]
I'm trying out the cert auth backend, and just picked a web server certificate I had lying around. I added it with `vault write auth/cert/certs/test-cert certificate=@mycert.pem policies=default`, and no complaints from vault. 
However, when I then try to auth with this cert, I run into problems that I think could have been detected already when I add it:
1. I did not include the intermediate certificates needed. This gives me a 400 error "invalid certificate or no client certificate supplied". Could/should vault have detected that it couldn't find a trusted CA?
2. My certificate has extended key usage TLS Web Server´only, which gives me a 500 "failed to verify client's certificate: x509: certificate specifies an incompatible key usage". 

While I shouldn't have used some random certificate, it would still be nice with some pre-validation.

**Comment by jefferai** [comment]
Hi @carlpett ,

For (2), I assume you are seeing this during authentication? In that case, what other behavior did you expect (other than it maybe being a `4xx` instead of `5xx` status code)? Or did you see this at some other point?

Thanks,
Jeff

**Comment by carlpett** [comment]
Hey @jefferai,
In both cases, the error happens during authentication. If possible, I think they should happen already when I try to add them, since vault should (I think) be able to realize already at that time that it cannot successfully be used. Or am I missing something that makes it only possible to check when authing?

**Comment by carlpett** [comment]
@vishalnayak: Cool! I'm not fluent enough in Go to really follow the patches, so just for verification: this will actually do checks when I add certificates?

**Comment by vishalnayak** [comment]
@carlpett 
Non-CA certificates can be added to the backend as trusted certificates.

If the certificate being added is a non-CA certificate, before registering it, Vault ensures that the certificate either has "extended key usage attribute: client authentication" or "extended key usage attribute: any". 

While you were able to add any certificate previously as well, the authentication would fail. Now, the authentication won't fail as long as the presented client certificate matches the registered certificate (in terms of the serial number and the issuer).

You shouldn't see both the problems you mentioned earlier, even for "some random certificate" :)

**Comment by v6** [comment]
I guess what you're saying is that Vault will _not_ trust a client certificate that does not have this EKU?
