### ISSUE TITLE
x509: certificate signed by unknown authority error while login

### ISSUE THREAD

**Issue by revit13** [hashicorp/vault#11480]
**Describe the bug**
Getting x509: certificate signed by unknown authority error 

**To Reproduce**

1. execute commands in https://www.vaultproject.io/docs/platform/k8s/helm/examples/standalone-tls to create secret vault-server-tls 
2. deploy vault in kuberenets
3. Run `vault login` with root password (also tried with --ca.crt= option)
4. See error: Error authenticating: error looking up token: Get https://127.0.0.1:8200/v1/auth/token/lookup-self: x509: certificate signed by unknown authority

**Expected behavior**
login to Vault

**Environment:**
* Vault Server Version 1.6.2 (retrieve with `vault status`):
* Vault CLI Version: Vault v1.5.4 (cgo) (retrieve with `vault version`):
* Server Operating System/Architecture:
* kind v0.8.1 go1.15.6 linux/amd64

Vault server configuration file(s):

```hcl
global:
  enabled: true
  tlsDisable: false
server:
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-server-tls/vault.crt
  logLevel: debug
  logFormat: standard
  debug: true
  readinessProbe:
    enabled: false
  # authDelegator enables a cluster role binding to be attached to the service
  # account.  This cluster role binding can be used to setup Kubernetes auth
  # method.  https://www.vaultproject.io/docs/auth/kubernetes.html
  authDelegator:
    enabled: true
  volumes:
    - name: data
      emptyDir: {}
  extraVolumes:
    - type: secret
      name: vault-server-tls # Matches the ${SECRET_NAME} from above
  volumeMounts:
    - mountPath: /vault/data/
      name: data
      readOnly: false
  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
        tls_key_file  = "/vault/userconfig/vault-server-tls/vault.key"
        tls_client_ca_file = "/vault/userconfig/vault-server-tls/vault.ca"
      }
      storage "file" {
        path = "/vault/data"
      }
  postStart:
    - "sh"
    - "-c"
    - |
      sleep 5
      # vault operator init commands works only if no data exists
      rm -rf /vault/data/*
      vault operator init | tee /tmp/vault.init > /dev/null
      cat /tmp/vault.init | grep '^Unseal' | awk '{print $4}' | for key in $(cat -); do
        vault operator unseal $key
      done
      export ROOT_TOKEN=$(cat /tmp/vault.init | grep '^Initial' | awk '{print $4}')
      echo "Remove master keys from disk"
 ```

**Additional context**

**Comment by sgmiller** [comment]
I notice you tried with "--ca.crt", rather than "--ca-cert" in your writeup.  Was that a typo?  The error strongly implies Vault CLI can't verify the certificate against known CAs.

**Comment by revit13** [comment]
@sgmiller yes thanks it was a typo sorry about that. will close the issue. BTW when using cert-manager with self-signed certificate I get the same error (Getting x509: certificate signed by unknown authority error); is it because the certificate is self-signed? thanks again
