### ISSUE TITLE
Add / extend token-renew CLI command to enable self-renewal

### ISSUE THREAD

**Issue by lorenzph** [hashicorp/vault#1150]
token-renew currently expects the user to pass in the token to be renewed. In some scenarios this may not be desired as the command line of the spawned vault process in general is world readable (and as such the token being renewed may leak).

Adding a new command to support self renewal (based on the content of VAULT_TOKEN) or reading the token from stdin could mitigate this issue.

**Comment by jefferai** [comment]
We should treat this like `token-lookup` and call renew-self if no token is passed in.
