### ISSUE TITLE
Configure oidc auth method with localhost redirect uri prompt unauthorized redirect_uri: redirect_uri

### ISSUE THREAD

**Issue by ccy** [hashicorp/vault#11511]
**Describe the bug**

I try to configure a `oidc` auth method.  When I configure redirect uri of the role, using 

    allowed_redirect_uris="http://localhost:8200/ui/vault/auth/oidc/oidc/callback" 

prompt warning in console when I try to use browser access `http://127.0.0.1:8200/ui/vault/auth?with=oidc` on console:

    [WARN]  auth.oidc.auth_oidc_90cba0fa: unauthorized redirect_uri: redirect_uri=http://127.0.0.1:8200/ui/vault/auth/oidc/oidc/callback

If I change the uri using `127.0.0.1` instead of `localhost`, everything works as expected:

    allowed_redirect_uris="http://localhost:8200/ui/vault/auth/oidc/oidc/callback" 

**To Reproduce**

Configure an oidc auth method:

```bash
$ vault write auth/oidc/config \
  oidc_discovery_url="$discovery_url" \
  oidc_client_id="$client_id" \
  oidc_client_secret="$client_secret" \
  default_role="$role"

$ vault write auth/oidc/role/$role \
  policies="default" \
  user_claim="sub" \
  allowed_redirect_uris="http://localhost:8200/ui/vault/auth/oidc/oidc/callback" \
  bound_audiences="$client_id" \
  oidc_scopes="openid" \
  role_type="oidc"
```
Access the following URL with browser:

    http://127.0.0.1:8200/ui/vault/auth?with=oidc`

**Expected behavior**
Both redirect uri using `localhost` and `127.0.0.1` shall work.

**Environment:**
* Vault Server Version: 1.7.1 run in development mode
* Vault CLI Version: 1.7.1
* Windows 10 WSL (Debian)

**Comment by g-psantos** [comment]
You should be able to specify multiple redirect URIs:

```
allowed_redirect_uris="http://localhost:8200/ui/vault/auth/oidc/oidc/callback,http://127.0.0.1:8200/ui/vault/auth/oidc/oidc/callback"
```

**Comment by vishalnayak** [comment]
Closing the issue due to staleness.

Closing stale issues helps us keep the issue count down and the project healthy. Keeping the issue count under a manageable number helps us provide faster responses and better engagement with the community.

If you feel that the issue is still relevant, or if it is wrongly closed, please leave a comment and we'd be happy to reopen it.
