### ISSUE TITLE
[ Feature Request ] Unclear messaging with using Vault Enterprise level cli commands

### ISSUE THREAD

**Issue by djdta** [hashicorp/vault#11539]
**Is your feature request related to a problem? Please describe.**
Currently, when using the Vault OSS for creating namespaces the error that appears does not give a clear indication that this is an enterprise feature only

**Describe the solution you'd like**
When using vault command which for enterprise features only, when you try to run them the error received does not clearly mention this is an enterprise feature only.  

Example of the error received.

Error creating namespace: Error making API request.

URL: PUT http://vault:8200/v1/sys/namespaces/testing
Code: 404. Errors:

* 1 error occurred:
        * unsupported path

Suggestion 1

Error:
The command you are trying to use is an enterprise-level feature.  If you wish to use this please use the vault enterprise

Suggestion 2:

To add a description note to the command that this is a enterprise-level feature and should only be used with vault enterprise.

**Describe alternatives you've considered**
This was just any idea of how to be more clear around using cli commands against OSS version and Enterprise level

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

Some examples

using vault namespaces create

**Additional context**

**Comment by marcboudreau** [comment]
This issue has been resolved and will appear in version 1.14.
