### ISSUE TITLE
How to inject hashicorp valt secrets  to running docker container 

### ISSUE THREAD

**Issue by lakshmisivareddy** [hashicorp/vault#11536]
Hi 
i am having running docker containers , i want to understand   how can i  configure hashicorp valt secrets  to running docker container

**Comment by sgmiller** [comment]
I would suggests using Vault Agent's templates (https://learn.hashicorp.com/tutorials/vault/agent-templates), to write the secrets you need to the running container or a sidecar.  Note that you will have to pick a way to authenticate, which depends on your overall operational stack.

**Comment by vishalnayak** [comment]
@lakshmisivareddy See if the following links help you:
https://learn.hashicorp.com/tutorials/vault/kubernetes-sidecar
https://learn.hashicorp.com/tutorials/vault/kubernetes-secret-store-driver
https://learn.hashicorp.com/tutorials/vault/kubernetes-external-vault

The learn website has many more tutorials that can potentially guide you to solve what it is that you are trying to solve.

Hope this helps!
