### ISSUE TITLE
MySQL/PostgreSQL secret backend: Allow reading configuration back out

### ISSUE THREAD

**Issue by phinze** [hashicorp/vault#1157]
Currently the configuration endpoints for both of the SQL backends only support POST, not GET.

 * `/{mysql|postgresql}/config/connection`
 * `/{mysql|postgresql}/config/lease`

I'm attempting to write code that configures these backends via API, and I'd like to verify that my configuration makes it into Vault. Currently there's no way to do this other than functionally testing the effects of a given config.

Outside of testing, I think from an operational perspective it's useful to be able to inspect the live configuration of a backend. For example, it'd be important to know what `max_open_connections` is set to when looking for performance bottlenecks in a running system.

**Comment by ShimiTaNaka** [comment]
+1
