### ISSUE TITLE
Namespace in HTTP API docs.

### ISSUE THREAD

**Issue by brentonannan** [hashicorp/vault#1158]
Not sure if this is the correct place to put this, but I was trying out the HTTP API on my vault installation this morning and was getting 404s from the endpoints listed down the left side [here](https://www.vaultproject.io/docs/http/index.html). I didn't start at the index page, so I missed the comment:

> All API routes are prefixed with /v1/
> So did not understand why I was getting 404s on listed endpoints (especially as I'm quite accustomed to seeing the `/v1/` on [the consul docs](https://www.consul.io/docs/agent/http/agent.html).

It'd be much more intuitive if you namespaced your docs as: `https://www.vaultproject.io/docs/http/v1/index.html` and had the listing down the side actually show the `/v1/`.

Don't get me wrong, I prefer this layout to the the consul docs, just had me scratching my head for a good 10 minutes.

Cheers.

**Comment by vishalnayak** [comment]
@brentonannan Sorry you had to face some confusion due to this.
But having `/v1/` on all the API references can turn out to be a documentation problem when the API changes to `v2`, `v3`...
We hope that users will see the overview page while using the API :)

**Comment by brentonannan** [comment]
@vishalnayak yeah, but you could namespace your docs, and link to the different versions' index page on the index page.

That way, you'll have correct docs for all of your versions!

**Comment by vishalnayak** [comment]
@brentonannan This suggestion can certainly be considered when `/v2/` gets ready. So, I'll mark this as `future` for now. Thanks for bringing this our notice!

**Comment by brentonannan** [comment]
Cheers, @vishalnayak. Thanks to the team for vault (and consul... and terraform!), I'm enjoying working with them.

**Comment by sethvargo** [comment]
Hi there,

We recently did a revamp of the API docs. While we don't have namespacing on the API itself, we are working on global versioning of all the documentation which should roll out soon.
