### ISSUE TITLE
Oracle Database Plugin - checksums did not match

### ISSUE THREAD

**Issue by hysel** [hashicorp/vault#11598]
Hi There

We are trying to use the Oracle DB plugin, we have configured it in our vault but when we are trying to use it, we are getting an error message.

Here are the commands we used (i have removed server identifiers etc.):

```
vault write <<namespace>>/config/oracle plugin_name=vault-plugin-database-oracle allowed_roles="*" connection_url="oracle://{{username}}:{{password}}@<<HOST>>:2484/<<SID>> username="<<USER>>" password="<<PWD>>"
Error writing data to <<namespace>>/config/oracle: Error making API request.

URL: PUT https://server:8200/v1/odbc/config/oracle
Code: 400. Errors:

* error creating database object: invalid database version: 2 errors occurred:
* checksums did not match
* checksums did not match
```

**Comment by vishalnayak** [comment]
@hysel It seems like the database plugin version is mismatching. Can you please provide more information on what versions of plugins and Vault?

In the meanwhile, see if this [readme](https://github.com/hashicorp/vault/blob/master/sdk/database/dbplugin/README.md) helps you.

**Comment by hysel** [comment]
> @hysel It seems like the database plugin version is mismatching. Can you please provide more information on what versions of plugins and Vault?
> 
> In the meanwhile, see if this [readme](https://github.com/hashicorp/vault/blob/master/sdk/database/dbplugin/README.md) helps you.

Yes, we were using 1.6 at the time so we had to select an older version of the plugin. would be great if there was some sort of a table in the download page that tell which version to download based on your Vault version

all is good for now
