### ISSUE TITLE
Unable to login to root namespace when VAULT_NAMESPACE is set

### ISSUE THREAD

**Issue by jlrgraham23** [hashicorp/vault#11612]
**Description**
The Vault CLI fails to override the value of `VAULT_NAMESPACE` when explicitly specified (or at least there is no apparent way to explicitly specify the root namespace as the target).  This means that an application where `VAULT_NAMESPACE` is set for ease of use, but logins are still use common authenticators (ie: Okta) that are configured in the root namespace fail.

Additionally, they produce a confusing `missing client token` message:

```
/usr/local/bin/vault login -method=okta username=foouser -namespace=""
Password (will be hidden):
Error authenticating: Error making API request.

URL: PUT https://vault.local/v1/auth/okta/login/foouser
Code: 400. Errors:

* missing client token
```

**To Reproduce**
1. Configure Vault with an authentication mechanism in the root namespace.
2. Create a namespace for other resources.
3. Set the `VAULT_NAMESPACE` environmental to the new namespace
4. Attempt to login to the root namespace

**Expected behavior**
The explicitly provided value on the CLI should override the environmental variable.

**Environment:**
* Vault Server Version: v1.7.1
* Vault CLI Version: v1.7.1
* Server Operating System/Architecture: Linux/AMD64

**Additional context**

Also attempted using variations on the value of the `-namespace` argument without success, ex:
* `-namespace="/"`
* `-namespace=" "`
* `-namespace="root"`
* etc.

**Comment by peteski22** [comment]
Hi, apologies for the open/closed PR for this (it can be totally ignored).

I tried to reproduce this issue using the `userpass` auth method, and I wasn't able to run into the issue where Vault ignored the namespace on the CLI. However, I think the issue may be where you're placing the `-namespace` or -`ns` flag. 

Could you try this for me please and let me know if you're still having the same issue:

`/usr/local/bin/vault login -namespace="" -method=okta username=foouser`

Thanks
Peter

**Comment by jlrgraham23** [comment]
Hi @peteski22, thank you.  Yes I can confirm that the argument ordering appears to be the options.  Sorry for the noise and thanks for following up here.

**Comment by PatMis16** [comment]
Does this also work for Vault OSS?
