### ISSUE TITLE
Incorrect expiration date in the UI

### ISSUE THREAD

**Issue by zerkms** [hashicorp/vault#11619]
**Describe the bug**

![image001](https://user-images.githubusercontent.com/302295/118415928-352e2900-b701-11eb-8c2b-091d3b51b1b3.png)

See it says it will expire on May 137th.

**To Reproduce**
I'm not really sure how to reproduce it: the last authentication was done today, May 17th.

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.7.1
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by olafz** [comment]
This issue is also (still?) present in Vault 1.8:

![image (2)](https://user-images.githubusercontent.com/80709/131848031-3f806898-de85-4591-8aca-038015a94ca7.png)
