### ISSUE TITLE
Revoke certficate for PKI secret engine doesn't seem to be working as expected

### ISSUE THREAD

**Issue by kennyatzeroeyes** [hashicorp/vault#11614]
**Describe the bug**
When I browse in the UI to PKI/PKI_INT certificates and revoke expired certificates manually the button doesn't seem to have any effect and I'm not seeing any errors in the Developer console. Nothing coming through that indicates an error in the logs either. I get a 204 "No Content" response if I manually hit the API endpoint for revoke and pass the serial of the cert in question.

**To Reproduce**
1. Open Vault/UI or equivilant API call
2. Browse to certificates for PKI secret engine
3. Click in the UI to revoke (expired) certificate

**Expected behavior**
Certificate is revoked and added to the CRL

**Environment:**
1.7.1
Ubuntu 18.04 Linux

Vault server configuration file(s):

```hcl
log_level = "Trace"

api_addr = "http://ip.address.hidden:8200"
cluster_addr = "http://ip.address.hidden:8201"
ui = true

disable_mlock = true

storage "gcs" {
  bucket = "hidden"
}

# HTTPS listener
listener "tcp" {
  address       = "[::]:8200"
  tls_cert_file = "/path/to/self/signed/file.crt"
  tls_key_file  = "/path/to/self/signed/file.key"
}

```

**Additional context**
Endpoints are added and tested in Postman if revoke in any way hits those endpoints.
Apologies if I'm doing something wrong. Thanks in advance

**Comment by hghaf099** [comment]
Thank you very much for filing this issue. I tested the issue and the revocation is indeed happening. Note that when a non-CA certificate is revoked, a revocation time is added to that certificate. This revocation time could be an indication of a successful revoked certificate. 
With regards to the UI give a clearer indication of a certificate revocation happened, this has been identified as an issue that we will be working on. We cannot guarantee when it will be released, but we know it is an area for growth. I am going to close this issue for now, but please feel free to reopen this issue, or open a new one if you would like to discuss more on the matter.
