### ISSUE TITLE
Wrong API call when creating secrets while running the guide

### ISSUE THREAD

**Issue by HaehnleinMar** [hashicorp/vault#11643]
When running the Guide in the UI on a fresh vault install I get the message `Error [object Object]` on Step 4: `Adding a secret`.

![image](https://user-images.githubusercontent.com/9468979/118623733-d502ba00-b7c8-11eb-9002-90aa1c524c57.png)

On further inspection I noticed that without the guide running, the API call looks like this:

```
curl 'https://vault-vault.apps.okd.ntsretail.com/v1/<engine>/data/<path>' \
  -H 'X-Vault-Token: <token>' \
  -H 'content-type: application/json; charset=UTF-8' \
  --data-raw '{"data":{"<key>": "<value>"},"options":{"cas":0}}' \
  --compressed
```

However, when running the Guide, the call looks like this:

```
curl 'https://vault-vault.apps.okd.ntsretail.com/v1/<engine>/<path>' \
  -H 'X-Vault-Token: <token>' \
  -H 'content-type: application/json; charset=UTF-8' \
  --data-raw '{"<key>": "<value>"}' \
  --compressed
```

**To Reproduce**
1. Setup Vault `1.7.0` with the Helm chart `0.11.0`
2. Init, unseal and add raft members
3. Access UI and run the Guide

**Expected behavior**
A secret is added.

**Environment:**
* Vault Server Version: `1.7.0`
* Vault CLI Version: `Vault v1.7.0 (4e222b85c40a810b74400ee3c54449479e32bb9f)`
* Server Operating System/Architecture: `Alpine Linux v3.13.5 (Linux 5.10.19-200.fc33.x86_64)` on OKD `4.7.0-0.okd-2021-04-24-103438`

Vault server configuration file(s):

```hcl
disable_mlock = true
ui = true

listener "tcp" {
  tls_disable = 1
  address = "[::]:8200"
  cluster_address = "[::]:8201"
}

storage "raft" {
  path = "/vault/data"
}

service_registration "kubernetes" {}
```

**Comment by hghaf099** [comment]
@HaehnleinMar Thank you for filing this issue. We believe that this issue has been fixed in the 1.7.1 release.  If possible please try your steps in the later releases. I will close this ticket for now, but please feel free to open a new issue if you encountered one.
