### ISSUE TITLE
Plugin Initialization Error - Unrecognized remote plugin message and symbol not found error

### ISSUE THREAD

**Issue by GeorgePals** [hashicorp/vault#11684]
I need to run my custom plugin on a Vault pod, deployed with the official Helm chart.

The plugin has 2 dependencies (libpbc and libgmp). In the beginning, I had issues [because of the dependencies](https://stackoverflow.com/questions/67609597/kubernetes-pod-external-library-dependency), but in the end, I resolved the issue.

However, now I have another problem. While trying to enable the plugin under some path, I get some errors.
Some hours ago, the most common error that I would get, would be:
```
Code: 400. Errors:

* fork/exec /vault/plugins/custom_plugin: no such file or directory
```
While everything was, at least seemed to be, okay (executing `ldd custom_plugin` was showing that all the libraries were linked), now, I'm getting another kind of error. And I really do not know how I achieved this (lol).
```
URL: POST http://0.0.0.0:8200/v1/sys/mounts/some_path
Code: 400. Errors:

* Unrecognized remote plugin message: 

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```
Running `ldd` again, I'm getting:
```
/vault/plugins $ ldd some_plugin
	/lib64/ld-linux-x86-64.so.2 (0x7f7613fb4000)
	libpbc.so.1 => /usr/local/lib/libpbc.so.1 (0x7f7613f61000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x7f7613efb000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f7613fb4000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f7613fb4000)
Error relocating some_plugin: __vfprintf_chk: symbol not found
Error relocating some_plugin: __fprintf_chk: symbol not found
```
I've tried valiano's 1st and 2nd  suggestions, found [here](https://stackoverflow.com/questions/66963068/docker-alpine-executable-binary-not-found-even-if-in-path), but the error remains.

I do not really want to move to an image other than Alpine.

One more thing that I would like to mention, is that **I can** register and enable the plugin, by running the vault's binaries locally (without docker, on host -Ubuntu-):

```
Success! Registered plugin: custom_plugin
Success! Enabled the custom_plugin secrets engine at: some_path/
```

Any ideas?
Thanks!

**Comment by calvn** [comment]
What do you get if you try to execute the plugin directly from the container, i.e. `./some_plugin`?

**Comment by GeorgePals** [comment]
Hello calvn. Thank you for your support!

```
/vault/plugins $ ./some_plugin
Error relocating ./some_plugin: __vfprintf_chk: symbol not found
Error relocating ./some_plugin: __fprintf_chk: symbol not found
```

The funny thing, and which I forgot to mention, is that I have also reached a state where I would get an error about: checksums don't match, while trying to enable the plugin.

**Comment by GeorgePals** [comment]
Issue solved!

As a last solution, and without anything else to do in mind, I (because `libpbc` is under /usr/local/lib):

```
RUN export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib
RUN export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib 
```
and, it worked!

```
Success! Registered plugin: custom_plugin
Success! Enabled the custom_plugin secrets engine at: some_path/
```
and `./custom_plugin`:
```
/vault/plugins $ ./some_plugin 
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```
`ldd  custom_plugin` still gives some errors:

```
/vault/plugins $ ldd abe
	/lib64/ld-linux-x86-64.so.2 (0x7f940f8c9000)
	libpbc.so.1 => /usr/local/lib/libpbc.so.1 (0x7f940f876000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x7f940f810000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f940f8c9000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f940f8c9000)
Error relocating abe: __vfprintf_chk: symbol not found
Error relocating abe: __fprintf_chk: symbol not found
```
but I'll check if everything is okay, tomorrow. For now, the plugin was installed on Vault and Alpine. Phew.
