### ISSUE TITLE
Scheduled token refresh failing

### ISSUE THREAD

**Issue by piyush-narvar** [hashicorp/vault#11693]
I am using the Kubernetes auth method with Vault. The “client_token” lease duration is 1 hr. The library itself calls the “renew-self” API in. “LifecycleAwareSessionManager.java”. However in my case as soon as the renewal is scheduled, executor service is shutting down.
Below is the logs in order

* Initializing ExecutorService ‘vaultThreadPoolTaskScheduler’
* Scheduling Token renewal
* Shutting down ExecutorService ‘vaultThreadPoolTaskScheduler’

According to the code, shutdown should be called when the I am using the Kubernetes auth method with Vault. The “client_token” lease duration is 1 hr. The library itself calls the “renew-self” API in. “LifecycleAwareSessionManager.java”. However in my case as soon as the renewal is scheduled, executor service is shutting down.
Below is the logs in order

Initializing ExecutorService ‘vaultThreadPoolTaskScheduler’
Scheduling Token renewal
Shutting down ExecutorService ‘vaultThreadPoolTaskScheduler’
This all is happening instantly. Can someone guide me here?
From the code it seems that executor service will shutdown when the BeanFactory destroys the task executor instance. But it seems this is not the case. 

Vault version - spring.vault.core - 2.1.2-release

**Comment by NicoleS021** [comment]
> I am using the Kubernetes auth method with Vault. The “client_token” lease duration is 1 hr. The library itself calls the “renew-self” API in. “LifecycleAwareSessionManager.java”. However in my case as soon as the renewal is scheduled, executor service is shutting down.
> 
> Below is the logs in order
> 
> 
> 
> * Initializing ExecutorService ‘vaultThreadPoolTaskScheduler’
> 
> * Scheduling Token renewal
> 
> * Shutting down ExecutorService ‘vaultThreadPoolTaskScheduler’
> 
> 
> 
> According to the code, shutdown should be called when the I am using the Kubernetes auth method with Vault. The “client_token” lease duration is 1 hr. The library itself calls the “renew-self” API in. “LifecycleAwareSessionManager.java”. However in my case as soon as the renewal is scheduled, executor service is shutting down.
> 
> Below is the logs in order
> 
> 
> 
> Initializing ExecutorService ‘vaultThreadPoolTaskScheduler’
> 
> Scheduling Token renewal
> 
> Shutting down ExecutorService ‘vaultThreadPoolTaskScheduler’
> 
> This all is happening instantly. Can someone guide me here?
> 
> From the code it seems that executor service will shutdown when the BeanFactory destroys the task executor instance. But it seems this is not the case. 
> 
> 
> 
> Vault version - spring.vault.core - 2.1.2-release

**Comment by piyush-narvar** [comment]
@NicoleS021 Are you also facing the same issue?

**Comment by vishalnayak** [comment]
Hey there, would it be possible for you to provide Vault logs? It is hard for us to determine what the issue could be based on your description. Note that this is a Golang code base and there are no java files in this repository.

**Comment by hsimon-hashicorp** [comment]
Since it's been a few months since there was last activity on this issue, I'll go ahead and close it now. If you have further bug reports, or more activity on this issue, please feel free to re-open it. Don't forget you can get help on our discuss forum, as well! https://discuss.hashicorp.com/c/vault/30
