### ISSUE TITLE
Add Redis Secret backend

### ISSUE THREAD

**Issue by josegonzalez** [hashicorp/vault#11697]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to create/remove redis users automatically via a Vault Secret Backend. This would allow operators to setup rotating credentials via Vault in Redis 6+.

**Describe the solution you'd like**

We currently have Redis clusters that have hard-coded passwords. Rotating the passwords is painful. We would like to be able to do this automatically with Vault.

**Describe alternatives you've considered**

We could alternatively:

- not rotate passwords (unsafe)
- manually rotate them (painful, easy to forget to do on)
- run a nomad job to handle rotation (would still tie us to 1 credential per job)

**Explain any additional use-cases**

- This would allow us to provision credential-per-container for any Nomad allocations talking to Redis.
- This would enable tracking user access to Redis.

**Additional context**

Page describing  Redis ACL rules: https://redis.io/commands/acl-setuser

**Comment by vishalnayak** [comment]
Thanks for submitting this! For those others who are also interested in this, please hit the thumbs up emoji on the issue.

**Comment by remilapeyre** [comment]
This has been added at https://developer.hashicorp.com/vault/docs/secrets/databases/redis. @hsimon-hashicorp I think this issue can be closed.
