### ISSUE TITLE
ldap operation failed: failed to bind as user

### ISSUE THREAD

**Issue by nkhljswl** [hashicorp/vault#11726]
Hello Folks,

I have installed Vault for first time and it's working perfectly with username and password authenication. However, while integrating with my AD i facing bind issue.

Here is my ldap confguration

```
Key                             Value
---                             -----
anonymous_group_search          false
binddn                          CN=Vault,CN=Users,DC=hip,DC=com
case_sensitive_names            false
certificate                     n/a
deny_null_bind                  true
discoverdn                      false
groupattr                       samAccountName
groupdn                         CN=Service Accounts,CN=Users,DC=hip,DC=com
groupfilter                     (&(objectClass=user)(samAccountName={{.Username}}))
insecure_tls                    false
starttls                        false
tls_max_version                 tls12
tls_min_version                 tls12
token_bound_cidrs               []
token_explicit_max_ttl          0s
token_max_ttl                   0s
token_no_default_policy         false
token_num_uses                  0
token_period                    0s
token_policies                  []
token_ttl                       0s
token_type                      default
upndomain                       n/a
url                             ldap://xxxxxxx.yy.zzz:389
use_pre111_group_cn_behavior    false
use_token_groups                false
userattr                        samaccountname
userdn                          ou=IT,dc=hip,dc=com
```
I tried to autheticate user from terminal and UI but didn't work.

```
Error authenticating: Error making API request.

URL: PUT http://172.15.15.15:8200/v1/auth/ldap/login/vault
Code: 400. Errors:

* ldap operation failed: failed to bind as user
```
I tried connecting to AD server with ldapsearch command and i was successfully able to query AD.

Any help would be appreciated.

**Comment by vishalnayak** [comment]
@nkhljswl It seems like a user error, but I am not able to figure out what it is offhand. There are some automated tests in Vault on that backend that are successfully run. Maybe looking at the configuration on those might help you figure out what the missing part is. https://github.com/hashicorp/vault/blob/master/builtin/credential/ldap/backend_test.go#L266

I am not sure if you are comfortable looking at the code and figuring it out, but I leaned on the side of sharing the link anyways. Let us know how it goes!

**Comment by nkhljswl** [comment]
@vishalnayak 

It seems like package are removed from repository.
``
[root@localhost ldap]# go run backend.go
backend.go:11:2: cannot find package "github.com/go-ldap/ldap/v3" in any of:
        /usr/local/go/src/github.com/go-ldap/ldap/v3 (from $GOROOT)
        /root/go/src/github.com/go-ldap/ldap/v3 (from $GOPATH)
backend.go:12:2: cannot find package "github.com/go-test/deep" in any of:
        /usr/local/go/src/github.com/go-test/deep (from $GOROOT)
        /root/go/src/github.com/go-test/deep (from $GOPATH)
backend.go:13:2: cannot find package "github.com/hashicorp/go-hclog" in any of:
        /usr/local/go/src/github.com/hashicorp/go-hclog (from $GOROOT)
        /root/go/src/github.com/hashicorp/go-hclog (from $GOPATH)
backend.go:14:2: cannot find package "github.com/hashicorp/vault/helper/namespace" in any of:
        /usr/local/go/src/github.com/hashicorp/vault/helper/namespace (from $GOROOT)
        /root/go/src/github.com/hashicorp/vault/helper/namespace (from $GOPATH)
backend.go:15:2: cannot find package "github.com/hashicorp/vault/helper/testhelpers/ldap" in any of:
        /usr/local/go/src/github.com/hashicorp/vault/helper/testhelpers/ldap (from $GOROOT)
        /root/go/src/github.com/hashicorp/vault/helper/testhelpers/ldap (from $GOPATH)
backend.go:16:2: cannot find package "github.com/hashicorp/vault/helper/testhelpers/logical" in any of:
        /usr/local/go/src/github.com/hashicorp/vault/helper/testhelpers/logical (from $GOROOT)
        /root/go/src/github.com/hashicorp/vault/helper/testhelpers/logical (from $GOPATH)
backend.go:17:2: cannot find package "github.com/hashicorp/vault/sdk/helper/ldaputil" in any of:
        /usr/local/go/src/github.com/hashicorp/vault/sdk/helper/ldaputil (from $GOROOT)
        /root/go/src/github.com/hashicorp/vault/sdk/helper/ldaputil (from $GOPATH)
backend.go:18:2: cannot find package "github.com/hashicorp/vault/sdk/helper/policyutil" in any of:
        /usr/local/go/src/github.com/hashicorp/vault/sdk/helper/policyutil (from $GOROOT)
        /root/go/src/github.com/hashicorp/vault/sdk/helper/policyutil (from $GOPATH)
backend.go:19:2: cannot find package "github.com/hashicorp/vault/sdk/helper/tokenutil" in any of:
        /usr/local/go/src/github.com/hashicorp/vault/sdk/helper/tokenutil (from $GOROOT)
        /root/go/src/github.com/hashicorp/vault/sdk/helper/tokenutil (from $GOPATH)
backend.go:20:2: cannot find package "github.com/hashicorp/vault/sdk/logical" in any of:
        /usr/local/go/src/github.com/hashicorp/vault/sdk/logical (from $GOROOT)
        /root/go/src/github.com/hashicorp/vault/sdk/logical (from $GOPATH)
backend.go:21:2: cannot find package "github.com/mitchellh/mapstructure" in any of:
        /usr/local/go/src/github.com/mitchellh/mapstructure (from $GOROOT)
        /root/go/src/github.com/mitchellh/mapstructure (from $GOPATH)
``

**Comment by nkhljswl** [comment]
Solved!

Issue was with userdn.
