### ISSUE TITLE
vault operator raft list-peers to show health status of each raft nodes

### ISSUE THREAD

**Issue by ausmartway** [hashicorp/vault#11733]
**Is your feature request related to a problem? Please describe.**
`vault operator raft list-peers` will list each node's leader/follower status and if they are voter or not, without listing their health status. In order to check the health of each node I have to use `vault operator raft autopilot state` command, this is really frastrating.

**Describe the solution you'd like**
It would be good if we can extend the output to include health status of each node.

**Describe alternatives you've considered**
The only alternative is to use `vault operator raft autopilot state`, which contains too much information. I just want a simple healthy indicator.

**Comment by vishalnayak** [comment]
@ausmartway I can provide some context on why it is that way. Vault started supporting raft storage from v1.2.0, and started supporting autopilot functionalities from v1.6.0. Between those versions, `vault operator raft list-peers` did the job of informing the nodes in the cluster. Going forward, it is better to adopt the output of `vault operator raft autopilot state` API for fetching the nodes in the cluster and their respective health statuses as well. Note that there is also a cluster level health field in the state API response that list-peers can't provide.

We understand that the output has a bulk of information. All the items in that response is a direct result of years of user feedback on the similar API that Consul supports. Vault is attempting to provide all those information from the get-go to avoid customer difficulties that Consul users faced over years.

Also, we try and avoid redundant information across different APIs in Vault. This applies here as well. When a comprehensive node and health information is responded by one API, it may not be a good idea to do the same from another. It gets hard to say no to folks to request for even more information to be added to it in future.

Let me know your thoughts!
