### ISSUE TITLE
Discussion: Horizontally Scaling Transit

### ISSUE THREAD

**Issue by quixoten** [hashicorp/vault#1174]
I primarily use vault for providing encyrption/decryption for other services using the transit backend. It works very well, but I'd like to learn more about how this might be scaled across multiple vault nodes using postgresql as the storage backend, e.g.,

```
+--------------+    +--------------+
|    vault1    |    |    vault2    |
+------------+-+    +-+------------+
             |        |
             |        |
          +--v--------v--+
          |  postgresql  |
          +--------------+
```

As far as I can tell, this should mostly work, but the policy cache introduces some difficulties. When a key is rotated, or the min key version is updated, one of the nodes will left with an outdated policy and potentially missing keys or allowing decryption of deprecated versions.

This could in part be fixed by renewing the cached policy before rejecting a request to decrypt a key version that is beyond the versions available in the currently cached policy. Alternatively, they keys themselves could be written to storage and cached separately.

The problem with min key version might be resolved by adding a maximum lifetime to the policies in the cache, so that they must be refreshed within some configurable interval.

I'm sure those more familiar with the code will have better ways to accomplish this use case. More generally, I just wanted to get some feedback on the feasibility of using vault in this way. What caveats haven't I planned for? Would the changes to make it work be better or worse for the long term goals of vault?

**Comment by jefferai** [comment]
Hi @quixoten ,

I am curious what the driver is here -- have you found transit to be too slow? We've done some benchmarking on it and found it to be extremely fast -- able to handle multiple tens of thousands of requests per second. Generally it has been the storage system that is the limiting factor, so hooking up multiple Vaults to the same storage system may not actually provide much or any benefit.

**Comment by jefferai** [comment]
To clarify -- transit obviously caches things and so isn't really beholden to the storage subsystem for speed, but generally when people ask about horizontally scaling Vault, the blocker isn't Vault, it's something else. So I'm curious what the end goal is.

**Comment by quixoten** [comment]
My goals are these:

- Enable a high-availability solution that works with the services that we already have in place (no consul, zookeeper, or etcd).
- Limit, wherever possible, dependencies on coordination between services.
- Prefer technologies that lend themselves to scaling out rather than up.

**Comment by horsehay** [comment]
https://github.com/hashicorp/vault/pull/1685

**Comment by jefferai** [comment]
?

**Comment by horsehay** [comment]
I believe that #1685 is pertinent to this discussion. @quixoten states that the goal is to have two vault instances with one postgres backend (which is non-HA). You said when closing #1685 that this would never be supported, but is exactly what would be needed to scale with postgresql backend.

**Comment by jefferai** [comment]
Vault requires consistency. Hacks to maybe-possibly-sortof make it work with non-HA backends are unlikely to ever be merged, because once they are it becomes our onus to maintain this functionality in a backwards-compatible way that we don't support in the first place.

**Comment by horsehay** [comment]
I don't disagree that the PR is a hackish way to work around the caching. I'm eager, though, to find the right solution to enable a vault node to refresh its cache when appropriate when the backend has been updated. I'm happy to contribute, just trying to understand the direction you (as a maintainer) want to go, but still make it work in the spirit of open-source.

**Comment by quixoten** [comment]
@jefferai, are you open to a refactoring which stores each key version separately, rather than one large object? A key would be fetched and cached the first time it's used rather than pulling back a potentially large set of keys (some of which may be dormant) all at once. This would eliminate the need for the logic and data shuffling around archived keys because only the keys needed would ever be pulled from storage. It should also make it easier for users to permanently delete old keys whereas the archived keys currently grow unbounded in one large object.

This refactoring would assist in the use case stated here, but it may also be an improvement for the official use case as well. I'm more than happy to take on the coding of such a refactor if you think it could be done without compromising the goals of your project.

**Comment by jefferai** [comment]
> I'm eager, though, to find the right solution to enable a vault node to refresh its cache when appropriate when the backend has been updated.

You could set `disable_cache` true and turn the cache off. Any other solution would need to keep the cache in working order but not fundamentally undercut Vault's data consistency model. The code in your PR may look simple, but it imposes a maintenance burden whereby we have to consider consistency models counter to the entire rest of Vault, which also means that fundamental changes to Vault's core may break that functionality even if the rest of Vault hums along happily.

@quixoten We had considered that model when introducing key archiving but shied away from it because some of the available data stores get unhappy with huge numbers of keys. Some users are targeting 1M+ keys, and some are targeting somewhere between 100k-1M keys with potentially thousands of rotations each. We wanted to reduce the chance of a billion-key transit backend. IIRC, depending on the particular instance, the current logic is also more performant, from slightly to significantly, as it's more likely to hit warm caches. 

If we ever introduce key version deletion, it's actually easier logic to perform with the current setup than by having each key be a separate file, because it's a single read-modify-write.

**Comment by horsehay** [comment]
Yeah, I considered disabling caching altogether, but the thought of having to go to the backend for every transit request makes me sad 😿 . That would mean an increase of requests to my backend over 1000x in my current architecture.

**Comment by jefferai** [comment]
Replication in Vault Enterprise does this quite nicely!
