### ISSUE TITLE
Add ParseDurationMillisecond() in parseutil

### ISSUE THREAD

**Issue by mahalrs** [hashicorp/vault#11761]
**Is your feature request related to a problem? Please describe.**

It would be nice to have a ParseDurationMillisecond() in [parseutil](https://github.com/hashicorp/vault/blob/master/sdk/helper/parseutil/parseutil.go). This would enable parsing input values as milliseconds for use cases such as making [RetryWaitMin](https://github.com/hashicorp/vault/blob/master/api/client.go#L937) and [RetryWaitMax](https://github.com/hashicorp/vault/blob/master/api/client.go#L938) configurable as described in this [issue](https://github.com/hashicorp/vault/issues/11675).

**Describe the solution you'd like**

Add ```ParseDurationMillisecond()``` in [parseutil](https://github.com/hashicorp/vault/blob/master/sdk/helper/parseutil/parseutil.go) like [ParseDurationSecond()](https://github.com/hashicorp/vault/blob/master/sdk/helper/parseutil/parseutil.go#L96).

**Comment by vishalnayak** [comment]
Closing based on conversation in https://github.com/hashicorp/vault/issues/11675.
