### ISSUE TITLE
list functionality not working if server running in -dev mode

### ISSUE THREAD

**Issue by nickithewatt** [hashicorp/vault#1177]
Hi 

I am try to do some testing running vault in dev mode, i.e. `vault server -dev` (0.5.1) however it appears that the list functionality does not work.

for example, via command line the issue presents itself as:
```
$ vault mount -path=bob generic
Successfully mounted 'generic' at 'bob'!

$  vault write bob/a value=a-val
Success! Data written to: bob/a

$  vault read bob/a 
Key           	Value
lease_duration	2592000
value         	a-val

$  vault list bob
No value found at bob/
```

if issuing an authenticated GET against http://127.0.0.1:8200/v1/bob?list=true, the result returned is:
```
{
  "errors": []
}
```

Note: Running against a non dev server (consul backend), this DOES seem to work

**Comment by nickithewatt** [comment]
Apologies, I see that my path to the vault I was using was incorrect, this does infact work and can simply be closed / marked as not a problem.

**Comment by jefferai** [comment]
No problem!
