### ISSUE TITLE
vaulth authetication with RedHat IDM

### ISSUE THREAD

**Issue by rht-rkaruppu** [hashicorp/vault#11791]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by rht-rkaruppu** [comment]
Vault authentication through Rredhat-IDM (like LDAP) is not enabled sofar. Is it possible to  include to authentication method? or any process already exist to integrate vault with IDM authentication?

**Comment by vishalnayak** [comment]
If it is not in the sidebar in the [auth methods](https://www.vaultproject.io/docs/auth) documentation, it doesn't exist.
We do welcome PRs for new authentication methods submitted by the community though!
