### ISSUE TITLE
Declarative configuration

### ISSUE THREAD

**Issue by Ais8Ooz8** [hashicorp/vault#11790]
We have an example https://www.hashicorp.com/blog/codifying-vault-policies-and-configuration

This may be a good option, but in some cases the Vault logic hurts when it comes to declarativeness. 

For example, group/group alias, identity/identity alias

```
vault list identity/entity/id
vault list identity/entity-alias/id
vault list identity/group/id
vault list identity/group-alias/id
```
Let's say I am using OIDC 

OIDC role -> Vault external group 

And let's dive in here  https://learn.hashicorp.com/tutorials/vault/identity

Run the following command to store the accessor value in a file named accessor.txt
```
$ vault auth list -format=json | jq -r '."oidc/".accessor' > accessor.txt
```

Create an external group named education. **Be sure to copy the generated group ID**.
```
$ vault write identity/group name="education" \
        policies="education" \
        type="external" \
        metadata=organization="Product Education"
```

Create a group alias where canonical_id is the group ID and the name is the actual GitHub team name. 
```
$ vault write identity/group-alias name="training" \
        mount_accessor=$(cat accessor.txt) \
        canonical_id="<group_ID>"
```

It seems that it is not very declarative

Please tell us what is your vision of declarative configuration in the context of Vault and how this approach, from your point of view, should be applicable to Vault

**Comment by vishalnayak** [comment]
@Ais8Ooz8 
It is hard to be declarative about access granted to each user/entity beforehand, specifically when the existence of users/entities are very dynamic in nature. Vault supports [templating](https://www.vaultproject.io/docs/concepts/policies#templated-policies) in the policies, to help with dynamically changing values such as these.

Let us know if it works out for you.

Hope this helps!
