### ISSUE TITLE
vault pki offers revoked certificates

### ISSUE THREAD

**Issue by sheldonh** [hashicorp/vault#1180]
Is there something I can do to prevent the pki/cert/SERIAL endpoint from providing revoked certificates?

I understand that this would be an optimization. I can get what I want by:

* Fetching pki/cert/SERIAL.
* Fetching pki/crl.
* Verifying that pki/cert/SERIAL does not appear in the CRL.

But if I could configure pki/cert/SERIAL to not provide revoked certificates, that would save me a roundtrip.

**Comment by sheldonh** [comment]
To clarify:

```
$ raw_serial=$( \
  curl -H "X-Vault-Token: $VAULT_TOKEN" \
    -XPOST \
    --data '{"common_name": "example.auto-h.net"}' \
    $VAULT_ADDR/v1/pki/issue/auto-h-dot-net \
    | jq -r .data.certificate \
    | openssl x509 -noout -serial \
    | perl -p -e 's/^serial=//')
$ serial=$(echo $raw_serial | perl -pe 's/(\w\w)(?!\Z)/$1:/g')
$ echo $serial
5F:8D:27:4B:39:8C:DA:4D:77:AB:33:4A:D1:71:F7:76:40:F2:31:89
$ curl -H "X-Vault-Token: $VAULT_TOKEN" \
    -XPOST \
    --data '{"serial_number": "'$serial'"}' \
    $VAULT_ADDR/v1/pki/revoke
{"lease_id":"","renewable":false,"lease_duration":0,"data":{"revocation_time":1457361703},"warnings":null,"auth":null}
$ curl $VAULT_ADDR/v1/pki/crl/pem | openssl crl -noout -text | grep $raw_serial
    Serial Number: 5F8D274B398CDA4D77AB334AD171F77640F23189
$ curl $VAULT_ADDR/v1/pki/cert/$serial | jq -r .data.certificate
-----BEGIN CERTIFICATE-----
MIIFOzCCAyOgAwIBAgIUX40nSzmM2k13qzNK0XH3dkDyMYkwDQYJKoZIhvcNAQEL
...
```

What I would like is for that last call to pki/cert/SERIAL to fail predictably.

**Comment by jefferai** [comment]
The ability to fetch any issued cert is a feature, not a bug. CRLs are a well-understood way of checking for certificate revocation. So not providing the certificates on request is not something we'll do.

That said, I can still try some optimization: I could have revoked certificates include revocation information in the output. If there is a revocation time that is non-zero, you'll know it's revoked.

How does that sound?

**Comment by sheldonh** [comment]
Yup, I like that even more than my suggestion, @jefferai.

I initially hoped to use `.lease_duration` in the pki/cert/SERIAL response, but that's always 0 in my testing. So I'm happy to inspect some other `.data` property of the response, and your promosed optimization won't break existing expectations.

**Comment by jefferai** [comment]
Yeah, in the `pki/cert/SERIAL` path it's zero because it's not actually set -- that's only set when a lease has been issued (so it will be non-zero when the cert is first issued/signed). It wouldn't do what you want anyways -- it would tell you the expiration but not whether it's been revoked.

**Comment by sheldonh** [comment]
I built master (99dc7ad) and I see `revocation_time: 0` for revoked certificates, as demonstrated by the attached test script.

```
+ curl -fH X-Vault-Token: b14a3f25-dec4-b7f6-4378-330c4e0b5288 -XPOST --data {"common_name": "example.auto-h.net"} http://localhost:8200/v1/pki/issue/auto-h-dot-net
+ jq -r .data.certificate
+ openssl x509 -noout -serial
+ perl -p -e s/^serial=//
+ raw_serial=326567611E2A88430A7B47BF70A1ADD081C1D90F
+ echo 326567611E2A88430A7B47BF70A1ADD081C1D90F
+ perl -pe s/(\w\w)(?!\Z)/$1:/g
+ serial=32:65:67:61:1E:2A:88:43:0A:7B:47:BF:70:A1:AD:D0:81:C1:D9:0F
+ curl -fH X-Vault-Token: b14a3f25-dec4-b7f6-4378-330c4e0b5288 -XPOST --data {"serial_number": "32:65:67:61:1E:2A:88:43:0A:7B:47:BF:70:A1:AD:D0:81:C1:D9:0F"} http://localhost:8200/v1/pki/revoke
{"lease_id":"","renewable":false,"lease_duration":0,"data":{"revocation_time":1457442418},"warnings":null,"auth":null}
+ curl http://localhost:8200/v1/pki/crl/pem
+ openssl crl -noout -text
+ grep 326567611E2A88430A7B47BF70A1ADD081C1D90F
    Serial Number: 326567611E2A88430A7B47BF70A1ADD081C1D90F
+ curl http://localhost:8200/v1/pki/cert/32:65:67:61:1E:2A:88:43:0A:7B:47:BF:70:A1:AD:D0:81:C1:D9:0F
+ jq -r .data.revocation_time
+ revocation_time=0
+ [ 0 = 0 ]
+ echo error: revocation_time is 0 for revoked certificate
error: revocation_time is 0 for revoked certificate
+ exit 1
```

[test.sh.txt](https://github.com/hashicorp/vault/files/163190/test.sh.txt)

**Comment by jefferai** [comment]
Hm. I'll try it out; my unit tests are passing and explicitly checking that it not zero, so something is odd somewhere.

**Comment by sheldonh** [comment]
Yeah, sorry about the gross test. I got lost reading the Golang test code. I couldn't see how the test requests revocation prior to checking the `revocation_time`.

**Comment by jefferai** [comment]
The `pki` backend tests are rather difficult to parse. No worries!

**Comment by jefferai** [comment]
Hi @sheldonh ,

This is working for me. I have a much simpler test script for you, although it relies on having `jq` and `http` (httpie.org) installed. The latter is pretty trivially turned into straight `curl`.

Note that you'll need to rebuild from `master`. During this testing I found that the serial number had disappeared from issue/sign output (not for root/intermediate certs, but for regular certs), and this testing relies on it being present. (This wasn't a problem in the unit tests since they were revoking the intermediate cert.)

This is against a `vault server -dev` running with fresh `master`:
```
vault mount pki
vault write pki/root/generate/internal common_name=example.com
vault write pki/roles/example allowed_domains="example.com" ttl_max="1h" ttl="1h" key_type="rsa" key_bits="2048"
http POST http://127.0.0.1:8200/v1/pki/issue/example X-Vault-Token:$(cat ~/.vault-token) common_name="localhost" | jq -r .data.serial_number > serial
vault read pki/cert/$(cat serial)
vault write pki/revoke serial_number=$(cat serial)
vault read pki/cert/$(cat serial)
```
At the end I get output like:
```
Key             Value
certificate     -----BEGIN CERTIFICATE-----
MIIDLzCCAhegAwIBAgIUGpdauNaD8S0yyJl5tLSNt/CxwTMwDQYJKoZIhvcNAQEL
BQAwFjEUMBIGA1UEAxMLZXhhbXBsZS5jb20wHhcNMTYwMzA4MTQzNDQ2WhcNMTYw
MzA4MTUzNTE2WjAUMRIwEAYDVQQDEwlsb2NhbGhvc3QwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQDAbmrwGSob7G/KgLO4P//0mHpZWBmgNydiC5/ynHmx
7d3Zmsc0bEnjtuetdIL7SN93LWpdcitg/QdFiKu+p7izZECpLve+JBKRJYVIYvJF
SI6qElDTf6+Kk2unHlxMBVPhmY8OPBbz0uf00xprWtThSk44ObWSi33vMoc8zBdx
AqBgxFeIj7ne0giwFsp42cJQGRpAShwemUYAdU/wbmTSBUePREre95W+1/vs+8Vy
dTNLfPHu9KaHW6fe2FtydFEdOXqKmb5tEvUBs93jEwle9AvcSJwx/0zHm0nWLgnz
7HeMtZAtK5xtW/W5W/nvZ2CGxQmrNBhde8fqvnSxytbNAgMBAAGjdzB1MB0GA1Ud
JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4EFgQUxM4GlZHYfkWMilSN
VRzCqpLHMEAwHwYDVR0jBBgwFoAUA6wasWSCMO5WbV+0dKT+Pw5LQiMwFAYDVR0R
BA0wC4IJbG9jYWxob3N0MA0GCSqGSIb3DQEBCwUAA4IBAQAq6nRu+w2LfWDeCPkG
CT5k6x0krCWmZWgWIl8PkCk289UTHgL8+mNkIjbnVq40+2gtP2eEPPNWLwMnCYwu
nCcr3LuxkxwJQEAHQ0EGhBGUXNzYxyzC0Rn6J8XEuduphi+HfcNZMaYwwy3G9eDh
troFlWHkB8oPG8DOajaco5FYbjS6SBe4vW58T2VvE/wdphPqxLOSwUF9V/pKuPob
vc2/FTCy9aQStJ4wUw23EQyhMdsJnAf1jU1CPJizyJdzXHxXPuSltdH5+OrZBEm6
jHrQN1jQnzRlYU6ekVh/YgAcxZ3d2XD2/2KFkVhB7Ehfg8LrGcIX0dWelbpWFiv6
WIJt
-----END CERTIFICATE-----
revocation_time 1.457447717e+09
```

**Comment by sheldonh** [comment]
Yup, your test works for me. I'll try to isolate what my problem is. Thanks!

**Comment by jefferai** [comment]
I think I figured it out. I think it's because AB != ab. Vault is using lowercase hex-formatted serial numbers, but OpenSSL prints them out in uppercase, which means they don't string match.

**Comment by jefferai** [comment]
Looks like we to a ToLower in `/pki/cert/...` but not in the revocation path. Fixing!

**Comment by sheldonh** [comment]
Works for me. Thanks, Jeff!
