### ISSUE TITLE
Vault Enterprise Replication

### ISSUE THREAD

**Issue by rht-rkaruppu** [hashicorp/vault#11811]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by rht-rkaruppu** [comment]
We have to set-up for vault enterprise repllcation as we have multiple data center across the globe. Would like to know if the vault-enterprise is free (opensoruce) version to test.? 
And for the paid version (if  only ) would like to get the quote

**Comment by mikegreen** [comment]
Hi - 
Please contact sales via this form for a trial license:
https://www.hashicorp.com/contact-sales
