### ISSUE TITLE
Feature Request: (PKI) Support for generating ECDSA certificates

### ISSUE THREAD

**Issue by c4milo** [hashicorp/vault#1182]

**Comment by jefferai** [comment]
It's supported ECDSA certificates since 0.2! You set the key type in the role parameters.

**Comment by c4milo** [comment]
ops, I didn't find docs about it. Thanks!

**Comment by c4milo** [comment]
Now I see it: 

![](https://cldup.com/ULJfssNzCd.png)

**Comment by jefferai** [comment]
That endpoint is only for root certificate generation. But there are `key_type` parameters in several other paths too, if you search around.

**Comment by learning813** [comment]
what would be the key type of ecdsa ? will it be just ec ?
