### ISSUE TITLE
image: burtlo/devwebapp-ruby:k8s should use VAULT_TOKEN environment variable instead of hard coded root

### ISSUE THREAD

**Issue by darkedges** [hashicorp/vault#11847]
**Describe the bug**
Hard coded vault token in the pod used in https://learn.hashicorp.com/tutorials/vault/kubernetes-external-vault

```
root@devwebapp:/app/lib# cat service.rb
require "sinatra"
require "faraday"
require "json"
require "logger"

$stdout.sync = true

class ExampleApp < Sinatra::Base

  set :port, ENV['SERVICE_PORT'] || "8080"

  configure :development do
    logger = Logger.new(STDOUT)
    logger.level = Logger::DEBUG
    set :raise_errors, true
    set :logger, logger

    set :vault_url, ENV["VAULT_ADDR"] || "http://localhost:8200"
  end

  configure :production do
    logger = Logger.new(STDOUT)
    logger.level = Logger::INFO
    set :vault_url, ENV["VAULT_ADDR"] || "http://vault:8200"
  end

  # GET "/"
  get "/" do
    logger.info "Received Request."

    # Set up an undefined state and set the vault server and secrets path
    secrets = { "username" => "undefined", "password" => "undefined" }
    vault_token = "root"

    secrets_path = "secret/data/devwebapp/config"

    # Ask for the secret at the path
    vault_response = Faraday.get "#{settings.vault_url}/v1/#{secrets_path}" do |req|
      req.headers['Content-Type'] = 'application/json'
      req.headers['X-Vault-Token'] = vault_token
    end

    if vault_response.status != 200
      raise Exception.new "The secret request failed: #{vault_response.body}"
    end

    # Parse the JSON
    content = JSON.parse(vault_response.body) rescue {}

    # Traverse the response to find the secrets in the response
    if content.key?('data') and content['data'].key?('data')
      secrets = content['data']['data']
    end

    # Return secret
    secrets.to_s
  end
```

the line `vault_token = "root"` ideally should be `set :vault_token, ENV["VAULT_TOKEN"] || "root"`

This will allow anybody to configure the `vault_token` via the ENV configured in the pod yaml file.

**To Reproduce**
Follow the deployment instructions on set :vault_url, ENV["VAULT_ADDR"] || "http://vault:8200"

**Expected behavior**
Should use `VAULT_TOKEN` defined in the Environment Variable for the pod.
This then allows the example to be used on any Vault instance.

**Environment:**
* Vault Server Version (retrieve with `vault status`): `1.7.2`
* Vault CLI Version (retrieve with `vault version`): `Vault v1.6.0-dev (bab5d07f01390d47fbeb79edc4b570e3153263f0+CHANGES) (cgo)`
* Server Operating System/Architecture: `Windows 10`

Vault server configuration file(s):

**Additional context**
N/A

**Comment by burtlo** [comment]
Thanks I'll make that change.
