### ISSUE TITLE
Refactor api module's logical type to be able to read kv v2

### ISSUE THREAD

**Issue by adrianord** [hashicorp/vault#11853]
**Is your feature request related to a problem? Please describe.**
In the Api module, the Logical type which facilitates logical backend operations cannot read from kv v2 without a lot of additional help.

**Describe the solution you'd like**
Move [`kv_helpers`](https://github.com/hashicorp/vault/blob/f8d255ead6521c02f458a0497183e459e6789f8e/command/kv_helpers.go) into the Api module, possible expose the functions to be public, and align the Api module with the Command module. kv_get has the logic to be able to read kv v1 and kv v2 that `Logical.ReadWithData` should have.

https://github.com/hashicorp/vault/blob/f8d255ead6521c02f458a0497183e459e6789f8e/command/kv_get.go#L89-L181

**Explain any additional use-cases**
The Command module could use the Logical type to read, list, and write kv for v1 and v2 if it were refactored to support v2, rather than having this logic repeated per command.

**Comment by mahalrs** [comment]
@vishalnayak I will work on this. Based on my understanding, we want to move [kv_helpers](https://github.com/hashicorp/vault/blob/f8d255ead6521c02f458a0497183e459e6789f8e/command/kv_helpers.go) to `vault/api` directory, and expose all the functions to be public. Then, update `vault/command/kv_get.go` to use `vault/api/kv_helpers.go`. Please guide me with any additional details that may be helpful.

**Comment by johnernaut** [comment]
@mahalrs You still planning on looking into this?  Otherwise, I'd be happy to give it a shot.  This is a current blocker for me.

**Comment by pmmukh** [comment]
Hi! Thanks for submitting this feature request! After looking through it and the corresponding PR, we don't think this is something we want to handle at this time. There is certainly some validity here, moving the kv_helpers.go file into a layer where both the command and api modules can access it easily, is something we're interested in. However, we don't think moving it directly into the api module is the right call, as well as updating the generic functions `ReadWithData` and `List` to be aware of kv-v2 requests. ( the PR author did note attempting this broke a few tests ) 
Hence, I'll be closing out the linked PR, as I don't think that is the direction we want to go in, and swapping the `good-first-issue` label with an `internal` label, cause while this is something our devex team may want to take a look at in the future, we won't be accepting external contributions on this at this time.

**Comment by averche** [comment]
Hi @adrianord!

I believe @digivava may have addressed the main concern raised in this issue by introducing [kv-v1](https://github.com/hashicorp/vault/blob/main/api/kv_v1.go) and [kv-v2](https://github.com/hashicorp/vault/blob/main/api/kv_v2.go) wrappers in in the `/api` module in #15305. 

You can find examples of how to use the new modules in our sample-code repo, [hello-vault-go](https://github.com/hashicorp/hello-vault-go):

https://github.com/hashicorp/hello-vault-go/blob/761a79fe815c6cd8670eee062d7ac4057fc3fd3a/quick-start/main.go#L31-L48

Hope this helps address your issue!
