### ISSUE TITLE
UI: Show date of creation in version history (KV)

### ISSUE THREAD

**Issue by tsohst** [hashicorp/vault#11851]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A field in the version history which shows the date when the version was created
![image](https://user-images.githubusercontent.com/32710648/121865626-79134e80-ccfe-11eb-81f6-2c5079f17c7b.png)

**Describe alternatives you've considered**
None

**Explain any additional use-cases**
We're using KV for SSL-Certificates and want to see when new certificates we're created.

**Additional context**
None

**Comment by jgod** [comment]
Very welcome UX improvement

**Comment by hsimon-hashicorp** [comment]
We believe this has been addressed in #12663, please feel free to re-open if that's not the case. Thanks!
