### ISSUE TITLE
Backup (archive) option doesn't exist in init command

### ISSUE THREAD

**Issue by eyal-lupu** [hashicorp/vault#1185]
Starting with Vault 0.5.0 the rekey command supports archiving of generated keys in the backend storage (if PGP is used to encrypt the keys). This option is turned on using the -backup flag.

However is seems that the init command doesn't support archiving (checked against 0.5.1). 

Is this is a bug or was that intended?

**Comment by jefferai** [comment]
That's correct, it doesn't. It could at some point, we just haven't had the time to add it; plus it is fairly common to perform a rekey once Vault is initially set up, so that a smaller number of people are key holders with a lower threshold are needed during initial testing.
