### ISSUE TITLE
golang vault client always validates config vars, even if passed config struct

### ISSUE THREAD

**Issue by tigerquoll** [hashicorp/vault#11865]
The golang vault client construction code at
https://github.com/hashicorp/vault/blob/438e9cb0eb23f7ba2beaeea8c5c57312fc59d2fa/api/client.go#L413
has descriptive comments of:
`If the configuration is nil, Vault will use configuration from DefaultConfig(), which is the recommended starting configuration.`

But even if the client configuration is non-nil, the code still validates environment variables, and will terminate client construction if any of these environment variables are invalid, regardless if they are being used for client initialisation or not.

**Comment by marcboudreau** [comment]
This problem looks pretty straightforward to fix, I'll take a stab at it.

**Comment by ncabatoff** [comment]
> This problem looks pretty straightforward to fix, I'll take a stab at it.

I recommend that you leave DefaultConfig's current behaviour intact for backward compatibility reasons.  One way to address the issue would be to factor out a new helper (`DefaultConfigNoReadEnv`?) which doesn't look at environment variables.

**Comment by hsimon-hashicorp** [comment]
Hi @marcboudreau - any updates on this, or questions for @ncabatoff's feedback? Please let us know if we can help, or if your PR is ready for review and merging. Thanks! (Since the PR has been open for a while, you may wish to rebase it.)
