### ISSUE TITLE
Spring config server and vault

### ISSUE THREAD

**Issue by inamjr** [hashicorp/vault#11879]
Can  Spring Config Server get its own properties from vault?

**Describe the bug**
I am trying to save the the properties of the config server in vault, not just the client (microservices). I am using vault version 1

**To Reproduce**
1. In the application.properties file i have  ` spring.application.name=demovault ` and i have a file called secret/demovault in my vault . 
2. I am unable to get the properties of the config server from vault.

**Environment:**
* Vault Server Version 1

Vault server configuration file(s):

```hcl
spring.cloud.vault.kv.enabled=true
spring.application.name=demovault
spring.profiles.active=vault
spring.cloud.config.server.vault.kvVersion: 2
spring.cloud.vault.authentication=token
spring.cloud.vault.token= s.GBAasAyRQq
spring.cloud.config.server.vault.token=s.GBAasAyRQq
spring.cloud.config.server.vault.defaultKey=shared
spring.cloud.config.server.vault.port=8201
spring.cloud.config.server.vault.uri=http://127.0.0.1:8201
spring.cloud.vault.uri= http://127.0.0.1:8201
#spring.cloud.vault.kv.application-name=demovault
```

**Additional context**

**Comment by vishalnayak** [comment]
Sorry. The details you have provided doesn't seem to be applicable for this repository. Please report in the client library that you are using to interact with Vault.
