### ISSUE TITLE
Vault LDAP auth: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by DaveDeCaprio** [hashicorp/vault#11882]
**Describe the bug**
Starting a few days ago, our LDAP authentication stopped working.  When we log in through the vault UI or through the CLI we get the error message:
Authentication failed: 1 error occurred: * error connecting to host "ldaps://ldap.google.com:636": LDAP Result Code 200 "Network Error": x509: certificate signed by unknown authority

We use Google Secure LDAP as our ldap server.  This exact configuration has been working suince August 2020 and just started failing a couple days ago.  I've verified and all the certificates are correct.

**To Reproduce**
Our vault configuration is (domain name changed):
vault write auth/ldap/config \
  url="ldaps://ldap.google.com:636" \
  userdn="ou=Users,dc=mydomain,dc=ai" \
  userattr="uid" \
  groupdn="ou=Groups,dc=mydomain,dc=ai" \
  groupattr="cn" \
  insecure_tls=false \
  certificate=@gts1o1.pem \
  client_tls_cert=@Google_2024_06_16_12248.crt \
  client_tls_key=@Google_2024_06_16_12248.key \
  deny_null_bind=false \
  anonymous_group_search=true
 
The Google client certificates were downloaded from the Google admin interface.  
The gts1o1.pem file was downloaded from https://pki.goog/repository/.  (https://pki.goog/repo/certs/gts1o1.pem)

To confirm that this was the correct certificate I ran:
  openssl s_client -connect ldap.google.com:636 --showcerts

It shows the ldap.google.com was issue by GTS CA 101, which is the specified certificate.

If I set "insecure_tls" to true everything works correctly, so I know it is just a certificate issue.
Using vault version 1.7.3

**Expected behavior**
I'd expect to be able to set insecure_tls to true and have things work.  This was working for almost a year.  We made no changes and it just started failing.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.7.3
* Vault CLI Version (retrieve with `vault version`):  1.7.1
* Server Operating System/Architecture:  Docker vault container.

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```
We are running the official vault docker container.  No config changes.  The only update we make to the container is adding our own CA cert to update-ca-certificates.

**Additional context**

**Comment by vishalnayak** [comment]
@DaveDeCaprio It doesn't seem like an issue in Vault to me. Did something change in the platform where this certificate is placed, like the file/directory permissions, file extensions? Or if the cert is moved to a different place by mistake?

It could be completely unrelated but googling this error fetched me [this](https://github.com/grafana/grafana/issues/4118#issuecomment-187379336). Worth a shot I guess?

**Comment by DaveDeCaprio** [comment]
The cert doesn't live in the file system, it is specified in the configuration of the LDAP vault auth.  The attached ldap.config.txt shows that vault has the certificate correctly stored within the configuration.  This is the result of calling `vault read auth/ldap/config`

[ldap.config.txt](https://github.com/hashicorp/vault/files/6671065/ldap.config.txt)

So the problem isn't that it's not finding the certificate, it's that Vault is not validating it correctly, which I believe is a vault problem.

I have also tried not specifying the certificate in the vault config and seeing if it will use the OS CA store, which is what your google link is referring to.  The certificate is in the store (I can validate that with `openssl s_client -connect ldap.google.com:636 --showcerts`, but that doesn't work either.

**Comment by hsimon-hashicorp** [comment]
@DaveDeCaprio, is the certificate and its intermediates available in your container? Can you drop into the container and verify the certificate validity there? Did it work previously with your CA being installed in the container? Thanks!

**Comment by DaveDeCaprio** [comment]
Yes, from running within the container I was able to run openssl s_client to verify that that certificate was there.  This was all working and then it suddenly stopped.

**Comment by hsimon-hashicorp** [comment]
Hi! Can you provide the output of the openssl command? We're a little stumped, ourselves, and we may figure out what other questions we can ask after seeing it. Thanks! :)

**Comment by hsimon-hashicorp** [comment]
Hi! Since this issue has been in waiting-for-response since July, I'm going to close this issue now. Please feel free to re-open it if you can provide the requested info. Thanks!
