### ISSUE TITLE
Issues in the windows for the Redis DB plugin Setup

### ISSUE THREAD

**Issue by brianblaze14** [hashicorp/vault#11927]
I ran all the below commands for setting the redis db in the windows environment,

vault redis plugin url details: https://github.com/fhitchen/vault-plugin-database-redis

$ go build -o build/redis-database-plugin ./cmd/redis-database-plugin/

$ sudo shasum -a 256 ./go_test/vault-plugin-database-redis/build/redis-database-plugin | cut -d' ' -f1
496b9951eb492ad4d844bfd82c0261af625e3585150b45a8011684ad71a522cf

Vault run command:
$ vault server -dev -dev-root-token-id=root -dev-plugin-dir=./vault/plugins

Role creation:

$ vault login root

$ vault write sys/plugins/catalog/database/redis-database-plugin sha256="496b9951eb492ad4d844bfd82c0261af625e3585150b45a8011684ad71a522cf" command=redis-database-plugin
Output : Success! Data written to: sys/plugins/catalog/database/redis-database-plugin
$ vault secrets enable database

$ vault write database/config/redis-db plugin_name="redis-database-plugin" host="localhost" port=6379 username="test" password="root" allowed_roles="*"

Last command output: Error writing data to database/config/redis-db: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/redis-db
Code: 400. Errors:

_* error creating database object: invalid database version: 2 errors occurred:
* exec: "D:\\Applns\\vault_1.6.1_windows_amd64\\vault\\plugins\\redis-database-plugin": file does not exist
* exec: "D:\\Applns\\vault_1.6.1_windows_amd64\\vault\\plugins\\redis-database-plugin": file does not exist_

But the binary file is available in the following path, attached the screenshot for reference, the above worked fine in a Linux based environment, but not working in the windows machine

![image](https://user-images.githubusercontent.com/55305942/123106720-80e99600-d456-11eb-83ad-17d9c937c367.png)

**Comment by vishalnayak** [comment]
@brianblaze14 I'd check if there are other applications on the OS that is not allowing this file read, like firewalls and/or virus scanners.

https://golang.org/doc/faq#virus

**Comment by brianblaze14** [comment]
@vishalnayak  I have disabled the antivirus in the system and then I am still getting the same issue, 

Error writing data to database/config/redis-db: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/redis-db
Code: 400. Errors:

* error creating database object: invalid database version: 2 errors occurred:
        * exec: "D:\\Applns\\vault_1.6.1_windows_amd64\\vault\\plugins\\redis-database-plugin": file does not exist
        * exec: "D:\\Applns\\vault_1.6.1_windows_amd64\\vault\\plugins\\redis-database-plugin": file does not exist

**Comment by vishalnayak** [comment]
Unfortunately I don't have a windows machine to test this out and am falling short of ideas on what could be going wrong.

**Comment by brianblaze14** [comment]
@vishalnayak issue is fixed it was because while building the golang plugin had to give the command as,  

go build -o build/redis-database-plugin.exe ./cmd/redis-database-plugin/

with .exe extension and after the sha key generation the registering command, should be as, vault write -tls-skip-verify sys/plugins/catalog/database/redis-database-plugin sha256="25ef67570485a190019f17604e93102d0ad0cdc2dfc9845c5b0385f3159d314a" command=redis-database-plugin.exe
with  command=redis-database-plugin.exe, 

Thanks for the support hence closing this issue

**Comment by vishalnayak** [comment]
Ah, interesting! Well, glad that it worked out for you.
