### ISSUE TITLE
UI. The values ​​written in Cyrillic are not hidden

### ISSUE THREAD

**Issue by stBlackD** [hashicorp/vault#11926]
**Describe the bug**
In the web interface, the values ​​written in Cyrillic are not hidden
![image](https://user-images.githubusercontent.com/5266226/123097355-855b8200-d449-11eb-99e7-0693c6c04021.png)

**Expected behavior**
Hide values

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.7.3
* Server Operating System/Architecture: ubuntu 20.04

**Comment by hellobontempo** [comment]
Thanks, @stBlackD for the bug report! Our team is currently working on a fix.

**Comment by stBlackD** [comment]
Fiexed in 1.8.0. Thx. 👍🏿

**Comment by hsimon-hashicorp** [comment]
> Fiexed in 1.8.0. Thx. 👍🏿

Thanks for confirming! I'll close this now - thanks for reporting it, too!
