### ISSUE TITLE
Add option to configure TLS cipher suites

### ISSUE THREAD

**Issue by coderanger** [hashicorp/vault#1193]
The default Go cipher configs are a bit wonky, it would be nice to be able to put in a cipher string in the config to override it. I know bupkiss about Go's TLS listener API, but a quick look over of the docs made this seem non-trivial.

**Comment by jefferai** [comment]
Any chance you can define "wonky"?

**Comment by coderanger** [comment]
`Ciphersuite order is chosen so that ...  RC4 comes before AES (because of the Lucky13 attack).`

Granted I can't really blame them, CBC vs. RC4 is likely choosing which finger you would like blown off. Would rather just disable both, and maybe 3DES while I'm at it because :crying_cat_face: downgrade attacks are sadmaking.

**Comment by coderanger** [comment]
For reference https://github.com/golang/go/blob/master/src/crypto/tls/cipher_suites.go#L78-L94 is Go's default cipher ordering I think.

**Comment by jefferai** [comment]
Note that you can easily disable this on the client side as well.

**Comment by coderanger** [comment]
"easily" would depend on what TLS client library you were using, and from a compliance PoV it is nice to just knock out everything related to MitM downgrades at once (like you can already do with TLS versions).

**Comment by jefferai** [comment]
I think Go's defaults are pretty sane here, and they update them with each release based on current thinking in the security community. But I'm happy to look at a PR if one pops up...shouldn't be too bad, since Go has constants that map to the uint16 values. It would just need to basically have a string array and logic to do the mapping.

**Comment by coderanger** [comment]
Was this closed for an actual reason?

**Comment by vishalnayak** [comment]
@coderanger 

Some of the Vault issues were closed by mistake from a syncing software. We apologize for the confusion caused. We have reopened the issues that were closed and are investigating the problem that caused this. Again, we are very sorry for the inconvenience.

**Comment by rhuddleston** [comment]
+1

I just got this from a pen tester:

Sweet32: Birthday attacks on 64-bit block ciphers

https://sweet32.info/ 
https://www.openssl.org/blog/blog/2016/08/24/sweet32/

nmap --script +ssl-enum-ciphers -p 8200 node1.dev.xxx.corp

PORT     STATE SERVICE
8200/tcp open  trivnet1
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (secp256r1) - C
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|     compressors:
|       NULL
|     cipher preference: client
|     warnings:
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|_  least strength: C

So at the least we need to disable these ciphers:

TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA

**Comment by jefferai** [comment]
@rhuddleston if you're willing to do the work it'll get done much faster than leaving it to us :-) if so let me know and we can figure out the design. Shouldn't be too bad.

**Comment by roman-vynar** [comment]
@jefferai I have added PR on this if you have a chance to take a look.

**Comment by jefferai** [comment]
Closed via #2293

**Comment by ryhoo2** [comment]
How to enforce those ciphers also for the cluster_address (default port 8201)? If I set the tls_cipher_suites parameter it works only for the main TCP listener (port 8200) and not the cluster one. With the example listener like this:

listener "tcp" {
address = "0.0.0.0:8200"
cluster_address = "0.0.0.0:8201"
tls_min_version = "tls12"
tls_cert_file = "/certs/server.crt"
tls_key_file = "/certs/server.key"
tls_cipher_suites = "TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
tls_prefer_server_cipher_suites = "true"
}

The ciphers are properly configured only on port 8200, and port 8201 still goes with what seems like to be the Go's default for the TLS v1.2. Here's the output from the TLS scan:
# 
$ ./o-saft.pl --no-sslv2 --no-tlsv13 --ignore-output=https_body --no-dns --enabled --no-header +cipherall 172.28.135.239:**8200**
172.28.135.239, 8200, SSLv3  (0x0300), no SNI,             ,           ,

172.28.135.239, 8200, TLSv1  (0x0301), no SNI,             ,           ,

172.28.135.239, 8200, TLSv11 (0x0302), no SNI,             ,           ,

172.28.135.239, 8200, TLSv12 (0x0303), no SNI, Server Order, 0x0300009C, **AES128-GCM-SHA256**           , RSA_WITH_AES_128_GCM_SHA256
172.28.135.239, 8200, TLSv12 (0x0303), no SNI, Server Order, 0x0300009D, **AES256-GCM-SHA384**           , RSA_WITH_AES_256_GCM_SHA384
172.28.135.239, 8200, TLSv12 (0x0303), no SNI, Server Order, 0x0300C02F, **ECDHE-RSA-AES128-GCM-SHA256** , ECDHE_RSA_WITH_AES_128_GCM_SHA256 , (ecdh, (primary) named_curve: ecdh_x25519, 255 bits)

# 
$ ./o-saft.pl --no-sslv2 --no-tlsv13 --ignore-output=https_body --no-dns --enabled --no-header +cipherall 172.28.135.239:**8201**
172.28.135.239, 8201, SSLv3  (0x0300), no SNI,             ,           ,

172.28.135.239, 8201, TLSv1  (0x0301), no SNI,             ,           ,

172.28.135.239, 8201, TLSv11 (0x0302), no SNI,             ,           ,

172.28.135.239, 8201, TLSv12 (0x0303), no SNI, No Order    , 0x0300C009, **ECDHE-ECDSA-AES128-SHA**      , ECDHE_ECDSA_WITH_AES_128_CBC_SHA  , (ecdh, (primary) named_curve: ecdh_x25519, 255 bits)
172.28.135.239, 8201, TLSv12 (0x0303), no SNI, No Order    , 0x0300C00A, **ECDHE-ECDSA-AES256-SHA**      , ECDHE_ECDSA_WITH_AES_256_CBC_SHA  , (ecdh, (primary) named_curve: ecdh_x25519, 255 bits)
172.28.135.239, 8201, TLSv12 (0x0303), no SNI, No Order    , 0x0300C02B, **ECDHE-ECDSA-AES128-GCM-SHA256**, ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, (ecdh, (primary) named_curve: ecdh_x25519, 255 bits)
172.28.135.239, 8201, TLSv12 (0x0303), no SNI, No Order    , 0x0300C02C, **ECDHE-ECDSA-AES256-GCM-SHA384**, ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, (ecdh, (primary) named_curve: ecdh_x25519, 255 bits)
172.28.135.239, 8201, TLSv12 (0x0303), no SNI, No Order    , 0x0300CCA9, **ECDHE-ECDSA-CHACHA20-POLY1305-SHA256**, ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, (ecdh, (primary) named_curve: ecdh_x25519, 255 bits)
