### ISSUE TITLE
KV V2 key name is limited to 110 characters.

### ISSUE THREAD

**Issue by IAmAStealer** [hashicorp/vault#11940]
KV V2 key name is limited to 110 characters. Nothing is documented about this limit. **-dev** servers cannot reproduce the error

**To Reproduce**
1. Set up a simple vault server
2. Run `vault server -config config.hcl`
3. Go on the interface http://127.0.0.1:8200 or Run `vault operator init`
4. Unseal the vault server
5. Connect with the root token
6. Enable a KV-v2
7. Add a key into this new KV-v2 more than 110 characters

**Expected behavior**
I expect the error to happen in dev server and some documentation about this limitation OR
Have a higher limit and get a documentation on this limit as well.

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault v1.6.2 (be65a227ef2e80f8588b3b13584b5c0d9238c1d7)
* Vault CLI Version (retrieve with `vault version`): 1.6.2
* Server Operating System/Architecture: Debian
* Expected to see that other versions have the problem.

Vault server configuration file(s):

```hcl
storage "file" {  path = "/tmp/vaul-store"}
listener "tcp" {  address     = "127.0.0.1:8200"  tls_disable = "true"}
api_addr = "http://127.0.0.1:8200"
cluster_addr = "https://127.0.0.1:8201"
ui = true
disable_mlock = true
```

**Additional context**
Key names come from old system to store password and keys can be long. So we encounter this problem while testing our migration

**Comment by hsimon-hashicorp** [comment]
Hello! Are you using the CLI or the UI to create this key-value pair? Are you receiving a specific error when you hit this issue? Thanks in advance!

**Comment by IAmAStealer** [comment]
We use API but I tried with the UI too and I still got the error.

**Comment by IAmAStealer** [comment]
Here is the response received : 
 1 error occurred: * open /tmp/vaul-store/logical/d57ba96a-9368-6667-2c30-1f271ed072ab/c6d87ff8-b5b5-5f9f-53d4-89f8b8ecaf5f/metadata/_1yYiSxomFesS14ls0F4zIMA7sIqpmTlavpzfW0wyOLbsZXdI7Vg1OLNTDtCkYCcnVTOPPtL3J6Sx0C7XjMfy2pUdHe7wcV7A9tTjyen6mDXI25gdZV0xnlcX80zcNZJ1BgIG0SW0Jv9PgGhRCm0HxbKYEKf6J6vSe4yLoY2Tvevr6P42q64dggb7Tmjvp4LBYA4uWkB8s55Lc8FEq3CE7EwrZ8PMnEAVpkYpD2f94U6GYJuB27ozljDNqMndDuClRHR6hYC22YqKmB8kPfxQ2GDtNcsiqw71LtSKnow0xS5Idd47JoXZ5j2gSlc8FUpQHaco0rICxio65DbUZB6VkJ6cIPkoQNkvF8DKN9gxCNf9Ch8ejRDX9J4LN0GplTtjz5bqnIO7h1yS662KjOGexPpNVT3weOSisaXkM115U37dhRhKVKhAT1bbH2Wvl5hLif4lZpV57e1f: file name too long

**Comment by hsimon-hashicorp** [comment]
Hi! Thanks for the information. Unfortunately this is a limitation of the filesystem itself, and cannot be changed by vault. There's no way for us to change the way the storage backend writes the files to disk. Please see the following for documentation on these filesystem limits:
https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

I'm going to mark this issue as closed, but if you have any further questions please feel free to re-open it. Thanks!
