### ISSUE TITLE
leases lookup blocked by syslog audit

### ISSUE THREAD

**Issue by rjhornsby** [hashicorp/vault#11946]
**Describe the bug**

When auditing is configured for syslog, the vault server endpoint `sys/leases/lookup/consul/creds/<role>` can be easily blocked by too many active leases. It looks like this is because this endpoint attempts to list and log a hash for every lease id in a single syslog message.

The error message received is

```
Jun 26 20:49:18 vault-host vault: 2021-06-26T20:49:18.624-0400 [ERROR] audit: backend failed to log response: backend=syslog/ error="write unixgram @->/dev/log: write: message too long"
Jun 26 20:49:18 vault-host vault: 2021-06-26T20:49:18.624-0400 [ERROR] core: failed to audit response: request_path=sys/leases/lookup/consul/creds/agent-role/
Jun 26 20:49:18 vault-host vault: error=
Jun 26 20:49:18 vault-host vault: | 1 error occurred:
Jun 26 20:49:18 vault-host vault: | #011* no audit backend succeeded in logging the response
```

After switching the audit log to `file`, it was discovered we have >3000 active leases. This is what was rejected by syslog, and thus blocked because of the inability to write the audit log.

It is acknowledged that this is partly a caching issue on us to solve[1], because that's far too many leases for our environment. However, at the same time, it seems excessive to write all 3000 `hmac-sha256:...` values to the audit log during normal operations in response to a `list` request.

[1] https://learn.hashicorp.com/tutorials/vault/blocked-audit-devices

**To Reproduce**
1. Set the vault audit logging to `syslog`
2. Create some large, arbitrary number of token leases with the consul? engine
3. Use either the UI or the API `sys/leases/lookup/consul/creds/some-role` to list the active leases
4. Error - the operation will be blocked with the above error message about `no audit backend...`

**Expected behavior**
The process or procedure that generates the message containing all of the sha256 hashes should not be a) generating this list or b) shipping it to the audit log handler for writing out. It should be sufficient to note the request for the list was made, and perhaps the number of entries returned.

When an individual lease's details are requested, certainly the lease id or other relevant information should be written to the audit logs. I could be wrong, but I'm having a hard time seeing any utility here in auditing the literal list of "here's the hashes of <items> returned in the response"

**Environment:**
* Vault Server Version: 1.7.2
* Vault CLI Version: 1.7.3
* Server Operating System/Architecture: CentOS 7, x86_64

**Comment by hsimon-hashicorp** [comment]
Hi!

This is due to using UDP with the syslog audit method. The audit message is longer than the maximum size of a UDP packet, as seen in your error:
"write unixgram @->/dev/log: write: message too long"
You can work around this by configuring a TCP listener for your syslog, or using file and syslog to prevent Vault from being blocked.
More information is available here: https://www.vaultproject.io/docs/audit/syslog

I'm going to go ahead and close this issue, but please feel free to re-open it if you have further questions. Thanks!

**Comment by rjhornsby** [comment]
Hello - thanks for the explanation. I definitely understand the message size is too large for UDP transport.  My concern - and the bug report - is that the message size is too large in general, and is logging far more than necessary or useful.

I changed the audit log to a type `file` to unblock the operation, and that's when I discovered that it was sending 3000+ sha256 hashes (one for each active lease) to the audit log all at once (one huge message) when a request for the leases `sys/leases/lookup/consul/creds/<role>` was made. One example audit log entry I'm looking at is 257KB long - a single log entry on a single (but very, very long) line.

It's hard to imagine a scenario where that sort of behavior is _not_ a bug?

**Comment by hsimon-hashicorp** [comment]
@rjhornsby I'll pass that along to the product team, as we're always looking for ways to improve the audit logs. I personally agree with you - that's a lot of data on a single line. However there may be other architectural concerns, so I'll leave this issue closed for now but I'll keep it in mind as we discuss the roadmap and future vision. Thanks so much for the feedback! :)

**Comment by jrutkowski** [comment]
Hello,

Shouldn't this issue be handled in other way than just crashing the request? One can imagine, that this could render whole vault unusable on some rare system configuration if the error would appear when trying to disable syslog device.
