### ISSUE TITLE
vault agent exit unexpected with [code=killed, signal=PIPE]

### ISSUE THREAD

**Issue by huaerfan** [hashicorp/vault#11948]
vault agent process killed by PIPE signal unexcepted. I can't find any information from syslog, message to solve this issue.

**Environment:**
* Vault Version: 1.7.2

"systemctl status vault" command output:
Process: 18765 ExecStart=/usr/bin/vault agent -config=/etc/vault.d/vault-agent.hcl (code=killed, signal=PIPE)
 Main PID: 18765 (code=killed, signal=PIPE)

my vault.service file:
[Unit]
Description="HashiCorp Vault - A tool for managing secrets"
Documentation=https://www.vaultproject.io/docs/
Requires=network-online.target
After=network-online.target
ConditionFileNotEmpty=/etc/vault.d/vault-agent.hcl
StartLimitIntervalSec=60
StartLimitBurst=3

[Service]
User=vault
Group=vault
ProtectSystem=full
ProtectHome=read-only
PrivateTmp=yes
PrivateDevices=yes
SecureBits=keep-caps
AmbientCapabilities=CAP_IPC_LOCK
Capabilities=CAP_IPC_LOCK+ep
CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK
NoNewPrivileges=yes
ExecStart=/usr/bin/vault agent -config=/etc/vault.d/vault-agent.hcl
ExecReload=/bin/kill --signal HUP $MAINPID
KillMode=process
KillSignal=SIGINT
Restart=on-failure
RestartSec=5
TimeoutStopSec=30
LimitNOFILE=65536
LimitMEMLOCK=infinity

[Install]
WantedBy=multi-user.target

**Comment by vishalnayak** [comment]
@huaerfan I don't know of a reason why agent would be killed like that. Is it happening more often or was it a one time thing?

**Comment by huaerfan** [comment]
@vishalnayak , It happened several times a week, my vault agent run in AWS EC2 instance, I guess this caused by go, because my vault.service file configured  ExecStart with "/usr/bin/vault agent -config=/etc/vault.d/vault-agent.hcl", this is to say, vault agent will write data to os.Stdout or os.Stderr. 

Here's some information with golang
> On Unix-like systems, when a write to os.Stdout or os.Stderr (more precisely, an os.File opened for file descriptor 1 or 2) fails due to a broken pipe error, the program will raise a SIGPIPE signal. By default this will cause the program to exit; this may be changed by calling the os/signal Notify function for syscall.SIGPIPE. A write to a broken pipe on a file descriptor other 1 or 2 will simply return syscall.EPIPE (possibly wrapped in os.PathError and/or os.SyscallError) to the caller. The old behavior of raising an uncatchable SIGPIPE signal after 10 consecutive writes to a broken pipe no longer occurs.

**Comment by hsimon-hashicorp** [comment]
@huaerfan, is your request to have more information logged when there's a broken pipe? I want to make sure that I understand the issue when working with our engineering teams on how we could improve the situation for you. Thanks!

**Comment by huaerfan** [comment]
@hsimon-hashicorp, I request for two things.

Firstly,  confirm if the vault agent process exits in the case when there's a broken pipe?

Secondly, are there any suggestions to solve this problem？

**Comment by ncabatoff** [comment]
It looks like the SIGPIPE is caused by journald restarts, based on the discussion in https://github.com/prometheus/node_exporter/issues/587.

I'm in agreement with this suggestion:
> If you can control systemd service definitions, the simplest way is to add either
Restart=always or RestartForceExitStatus=SIGPIPE in it.

I don't think there's anything we want to change in Vault for this: from what I understand, if we ignored the SIGPIPE, that would lead to logs being lost.
