### ISSUE TITLE
from vault UI getting this error Make sure the policy for the path sys/capabilities-self includes capabilities = ['update'].

### ISSUE THREAD

**Issue by savanipoojan78** [hashicorp/vault#11950]
**Describe the bug**
I have define a policy and attach that policy to a entity the policy is here

```
path "sys/capabilities-self" {
   capabilities = ["update","create"]
}
path "sys/capabilities" {
	capabilities = ["create", "update"]
}
path "sys/capabilities-accessor" {
	capabilities = ["create", "update"]
}
path "DEV/kv/data/{Project_name}" {
  capabilities = ["create", "update", "read"]
}
path "DEV/kv/metadata/*" {
  capabilities = ["list","read"]
}
```

here DEV is a ns
after this when i login i am getting this error

Your auth token does not have access to sys/capabilities-self. Vault Enterprise uses this endpoint to determine what actions are allowed in the interface.
Make sure the policy for the path sys/capabilities-self includes capabilities = ['update'].

using kv version 2

Vault server configuration file(s):

help would be apricated

**Comment by hsimon-hashicorp** [comment]
Hi!
First off, I recommend opening a support ticket if you haven't already, since it appears you're a Vault Enterprise customer. A support ticket will ensure proper tracking and escalation as needed.
If you run a "vault token capabilities" check, do you see the expected results? If you use the command with no token or path arguments, it should use the sys/capabilities-self path for your locally registered token, as described here:
https://www.vaultproject.io/docs/commands/token/capabilities
Thanks!

**Comment by savanipoojan78** [comment]
Hello Thanks for your reply 
what I want to achieve is I have some user just for them only I want to give access to there project secrets only for that I have create policy and attach that policy to that user and now when they login from vault UI This is the error that they are getting 

![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/33199323/123744252-1f994b00-d8cc-11eb-8c6d-be414bd0f0f0.png)

for the same user when I login from the cli and run this command I got this output

```
vault token capabilities sys/capabilities-self
create, update

vault token capabilities sys/capabilities
create, update

vault token capabilities sys/capabilities-accessor
create, update

vault token capabilities DEV/kv/data/adt-iper-azure-sink
create, read, update

vault token capabilities 'DEV/kv/metadata/*'
list, read
```

but from the UI side I am facing this issue

I am not sure how do I open one support ticket if u have any documentation for that process I will definitely do that.

**Comment by savanipoojan78** [comment]
The strange thing is when I login using the cli and run the command I am getting output but from UI getting the error shown in previous image 
vault read DEV/kv/data/{ProjectName} :- I am able to retrieve the secrets 

but from the UI this api is failing not sure why I have given access to this user for that capabilities 

![InkedMicrosoftTeams-image (10)_LI](https://user-images.githubusercontent.com/33199323/123748964-86216780-d8d2-11eb-8c3c-cd5b5d5f5ea1.jpg)
![MicrosoftTeams-image (12)](https://user-images.githubusercontent.com/33199323/123748975-87eb2b00-d8d2-11eb-85cf-348c710e32b8.png)

**Comment by savanipoojan78** [comment]
@hsimon-hashicorp any update in this?

**Comment by hsimon-hashicorp** [comment]
@savanipoojan78 I'll take another look at this today. Thanks for the extra information!

**Comment by hsimon-hashicorp** [comment]
It looks like you might need to create a sys/capabilities-self within your DEV name space, like so:
```
rule {
    path         = "+/sys/capabilities-self"
    capabilities = ["create", "read", "update", "list"]
    description  = "Read special mount in tenant namespace"
  }

```
Can you try that and let me know if it resolves the issue? If not, then we will keep digging. Thanks! :)

**Comment by savanipoojan78** [comment]
Not sure why it is able to get the secrets from cli and not from vault-UI i have added 
```
path "+/sys/capabilities-self"{
    capabilities = ["create", "read", "update", "list"]
    description  = "Read special mount in tenant namespace"
}
```
I have added this in default policy in dev ns 
I don't have any policy in dev as of now

**Comment by savanipoojan78** [comment]
the thing is we have 3 ns DEV,STAGE,TEST and root NS ECP okay auth is only enabled at root ns and via policy at the root ns we are giving access to different ns to different user

**Comment by savanipoojan78** [comment]
Closing this issue i someway resolved this 
if u are using NS then your hcl file should look like this 
```
path "sys/capabilities-self" {
   capabilities = ["update","create"]
}
path "sys/capabilities" {
	capabilities = ["create", "update"]
}
path "DEV/sys/capabilities-accessor" {
	capabilities = ["create", "update"]
}
path "DEV/sys/capabilities-self" {
   capabilities = ["update","create"]
}
path "DEV/sys/capabilities" {
	capabilities = ["create", "update"]
}
path "sys/capabilities-accessor" {
	capabilities = ["create", "update"]
}
path "DEV/kv/data/{Project_name}" {
  capabilities = ["create", "update", "read"]
}
path "DEV/kv/metadata/*" {
  capabilities = ["list","read"]
}

```

**Comment by christophermaier** [comment]
I ran into this yesterday. Is this expectation documented anywhere? This was rather surprising to discover, particularly since the token can perform the tasks via the CLI without issue.
