### ISSUE TITLE
Support new JWT token structure on k8s 1.21

### ISSUE THREAD

**Issue by gabrielrinaldi** [hashicorp/vault#11953]
**Is your feature request related to a problem? Please describe.**
Yes, the current version of Vault (including 1.8) Kubernetes backend does not support Kubernetes clusters on version 1.21.x

**Describe the solution you'd like**
I would like to be able to use Vault with the latest version of the Kubernetes cluster that includes a new more secure JWT token

**Describe alternatives you've considered**
I considered disabling the token claim verification (currently is disabled) or creating a service to rewrite the token in a format that Vault would be able to process 

**Additional context**
Current token format:
```
{
  "iss": "kubernetes/serviceaccount",
  "kubernetes.io/serviceaccount/namespace": "namespace",
  "kubernetes.io/serviceaccount/secret.name": "vault-token-7h4st",
  "kubernetes.io/serviceaccount/service-account.name": "vault",
  "kubernetes.io/serviceaccount/service-account.uid": "6c40a476-8620-869f-a102-6a0d9ad73ef3",
  "sub": "system:serviceaccount:namespace:vault"
}
```

New token format:
```
{
  "aud": [
    "https://container.googleapis.com/v1/projects/project-name/locations/europe-west1/clusters/cluster-name"
  ],
  "exp": 1656040272,
  "iat": 1624504272,
  "iss": "https://container.googleapis.com/v1/projects/project-name/locations/europe-west1/clusters/cluster-name",
  "kubernetes.io": {
    "namespace": "namespace",
    "pod": {
      "name": "tmp",
      "uid": "cc2866c7-fee8-5613-a563-15613d152ee2"
    },
    "serviceaccount": {
      "name": "vault",
      "uid": "6c40a476-8620-869f-a102-6a0d9ad73ef3"
    },
    "warnafter": 1624507879
  },
  "nbf": 1624504272,
  "sub": "system:serviceaccount:namespace:vault"
}
```

**Comment by tomhjp** [comment]
Hi @gabrielrinaldi, thanks for raising awareness of this. It looks like as of 1.21, most clusters will default to using ephemeral projected service account tokens instead of the default long-lived token which uses the legacy issuer of `kubernetes/serviceaccount`. We've had people run into very similar issues with the Vault CSI provider pre-1.21 because that project also uses ephemeral tokens which change the issuer away from the default/legacy value.

I think you should be able to resolve your problem by setting the [`issuer`](https://www.vaultproject.io/api-docs/auth/kubernetes#issuer) field when configuring Kubernetes auth. We have some documentation in the [Vault CSI provider docs](https://www.vaultproject.io/docs/platform/k8s/csi#setting-issuer-for-kubernetes-authentication) to help figure out what to set `issuer` as. But now that Kubernetes is defaulting to projected service account tokens in 1.21, I think it's time to include some extra details on that in the main [Kubernetes auth docs](https://www.vaultproject.io/docs/auth/kubernetes) to give it more prominence.

Let me know if there's anywhere else that you think would also benefit from having an extra link or bit of documentation too, and hopefully the above helps.

**Comment by Happycoil** [comment]
@tomhjp Just hit this issue and eventually found the `issuer` workaround. I think documentation of the workaround in the kubernetes auth docs would be very helpful.

**Comment by Itiho** [comment]
The alternative soluction no work for me. I'm try two forms in my lab kind with K8S 1.21 

```
kubectl proxy &
ISSUER=$(curl --silent http://127.0.0.1:8001/api/v1/namespaces/default/serviceaccounts/default/token -H "Content-Type: application/json" -X POST -d '{"apiVersion": "authentication.k8s.io/v1", "kind": "TokenRequest"}' | jq -r '.status.token' | cut -d. -f2 | base64 -d | jq -r .iss)
K8S_TOKEN=$(kubectl -n hashicorp exec vault-0 -- cat /var/run/secrets/kubernetes.io/serviceaccount/token)
K8S_CA=$(kubectl -n hashicorp exec vault-0 -- cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt)
K8S_ADDRESS="https://$(kubectl -n hashicorp exec vault-0 -- sh -c 'echo $KUBERNETES_PORT_443_TCP_ADDR'):443"
vault write auth/kubernetes-kind/config token_reviewer_jwt="$K8S_TOKEN" kubernetes_host="$K8S_ADDRESS" kubernetes_ca_cert=$K8S_CA issuer=$ISSUER`
```
and

```
K8S_TOKEN=$(kubectl -n hashicorp exec vault-0 -- cat /var/run/secrets/kubernetes.io/serviceaccount/token)
K8S_CA=$(kubectl -n hashicorp exec vault-0 -- cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt)
K8S_ADDRESS="https://$(kubectl -n hashicorp exec vault-0 -- sh -c 'echo $KUBERNETES_PORT_443_TCP_ADDR'):443"
vault write auth/kubernetes-kind/config token_reviewer_jwt="$K8S_TOKEN" kubernetes_host="$K8S_ADDRESS" kubernetes_ca_cert=$K8S_CA disable_iss_validation=true`
```

In lab with kind and k8s 1.20.7 works fine.

**Comment by hsimon-hashicorp** [comment]
@Itiho When you say the alternative solution doesn't work, what behavior are you seeing? If you could let us know where we can focus our efforts to get this resolved, we'd appreciate it a lot. :)

Thanks!

**Comment by Itiho** [comment]
@hsimon-hashicorp I tried again, and again and again until I got

https://github.com/Itiho/hashicorp-vault/tree/main/deploy/kind

**Comment by tvoran** [comment]
Hi folks, we've added info for discovering the issuer here: https://www.vaultproject.io/docs/auth/kubernetes#discovering-the-service-account-issuer

**Comment by Oro** [comment]
As far as my tests go, the kubernetes auth with JWT works fine as long as the vault pod(s) are not deleted. Once the pods are deleted, login no longer works (until kubernetes auth config is written again)

Here are the steps to reproduce my issue, I hope that someone else can also chime in and confirm them (or, better, tell me what I'm doing wrong :) )

```sh
# Create k8s cluster, install vault
minikube start --cpus 2 --memory 6000 --kubernetes-version v1.21.3 --driver=podman
helm repo add hashicorp https://helm.releases.hashicorp.com
helm repo update
helm install vault hashicorp/vault --version 0.15.0

# Init & Unseal
kubectl exec -ti vault-0 -- vault operator init # save unseal + root token
kubectl exec -ti vault-0 -- vault operator unseal # unseal vault with keys, 3 is default

# Configure kubernetes auth
kubectl port-forward svc/vault 8200 &
export VAULT_ADDR='http://[::]:8200'
vault login # use root token saved with operator init
vault auth enable kubernetes
K8S_ISSUER=$(kubectl exec vault-0 -- cat /var/run/secrets/kubernetes.io/serviceaccount/token | cut -d. -f2 | base64 -d | jq -r '.iss')
K8S_TOKEN=$(kubectl exec vault-0 -- cat /var/run/secrets/kubernetes.io/serviceaccount/token)
K8S_CA=$(kubectl exec vault-0 -- cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt)
K8S_ADDRESS="https://$(kubectl exec vault-0 -- sh -c 'echo $KUBERNETES_PORT_443_TCP_ADDR'):443"
vault write auth/kubernetes/config token_reviewer_jwt="$K8S_TOKEN" kubernetes_host="$K8S_ADDRESS" kubernetes_ca_cert="$K8S_CA" issuer="$K8S_ISSUER"

# Create role which is able to login
vault write auth/kubernetes/role/oro-role bound_service_account_names=jwt-test bound_service_account_namespaces=default

cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jwt-test
---
apiVersion: v1
kind: Pod
metadata:
  name: oro-test
spec:
  serviceAccountName: jwt-test
  containers:
    - name: oro-test
      image: vault:1.7.3
      command: ["/bin/sh", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
EOF

kubectl exec -ti oro-test -- sh -c 'VAULT_ADDR=http://vault:8200 vault write auth/kubernetes/login role=oro-role jwt=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)'
```

Up until here everything works fine, but after deleting vault-0 and unsealing the newly created vault-0, the login via the serviceaccount token fails and vault logs
> 2021-09-10T10:57:18.279Z [ERROR] auth.kubernetes.auth_kubernetes_518098cd: login unauthorized due to: lookup failed: service account unauthorized; this could mean it has been deleted or recreated with a new token


```sh
kubectl delete pod vault-0
kubectl exec -ti vault-0 -- vault operator unseal # 3 times again
kubectl exec -ti oro-test -- sh -c 'VAULT_ADDR=http://vault:8200 vault write auth/kubernetes/login role=oro-role jwt=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)'
```

> Error writing data to auth/kubernetes/login: Error making API request.
> 
> URL: PUT http://vault:8200/v1/auth/kubernetes/login
> Code: 403. Errors:
> 
> * permission denied

After writing the kubernetes config endpoint again, the login works (until the vault pod restarts)

Within kube-apiserver logs I can see the line
> E0910 10:57:18.278251       1 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, Pod UID (330446ed-7841-44c9-8b26-457e0981ef6c) does not match claim (2cecd1d4-09e1-4b68-b773-cb6c8ce0a4fa)]"
I assume this has to do with the `token_reviewer_jwt` which is no longer valid after the pod is deleted? But that might be a red herring...

Would you like me to create a new issue for that or does this still belong here?

**Comment by thomasgouveia** [comment]
Hello @Oro, any update on this ? I'm facing the same problem, and I didn't find a solution right now

**Comment by tvoran** [comment]
Hi @Oro, this question would be a better fit in the [discuss forums](https://discuss.hashicorp.com/).

**Comment by Oro** [comment]
Added the comment to https://discuss.hashicorp.com/t/after-upgrading-to-kubernetes-1-21-kubernetes-authentication-request-to-vault-fails-with-permission-denied/29392 , thanks for the pointer

**Comment by ArchiFleKs** [comment]
I guess it should also be specified in the docs to get the `token_reviewer_jwt` from the vault service account secret and not from inside the pods, because using the one inside the pod breaks kubernetes auth everytime vault restart.

**Comment by wilmanpabel** [comment]
AKS 1.21+ in JWT ISSUER or token_reviewer_jwt  section add fqdn of master inside "" 
token_reviewer_jwt="\"myapimaster.abc.io\""

**Comment by adelca** [comment]
Not all Vault versions support _disable_iss_validation=true_ option:
https://github.com/external-secrets/kubernetes-external-secrets/issues/721#issuecomment-955088967

**Comment by hsimon-hashicorp** [comment]
Hi folks, if there's a need for a new issue, please feel free to open one. Otherwise, the waters get muddied in terms of what's needed. Also, there's the [Discuss forums](https://discuss.hashicorp.com/c/vault/30) for chat about problem-solving. Thanks in advance!

**Comment by jasonyic** [comment]
> https://discuss.hashicorp.com/t/after-upgrading-to-kubernetes-1-21-kubernetes-authentication-request-to-vault-fails-with-permission-denied/29392

to fix the issue related to vault pod restarting with **disable_local_ca_jwt** as default (false):
1. set disable_local_ca_jwt to true
2. add a clusterrolebinding for the service account which access vault
  ```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: application
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: app-sa
    namespace: application
```

**Comment by kppullin** [comment]
> I had the same issue with EKS 1.21 + managed node group. here is what I did to resolve:
>
  ...SNIP...
>
> 
>     4. update **auth/kubernetes/config**
> 
> 
> ```
> vault write auth/kubernetes/config  issuer="${ISSUER}"
> ```

I found that the `kubernetes_host` value is required with our setup and had to add `kubernetes_host=https://172.20.0.1` to the `write` command (the value already exists and can be seen in the `read` output from step 3. Adjust accordingly).

**Comment by ArchiFleKs** [comment]
I think that Vault 1.9 has deprecated the issuer field right ?

I have no issue with eks 1.21 on 1.8 and 1.9 with our without disable_iss_validation.

To setup the vault kubernetes auth, the long live service account token should be used by describing the secret in vault namespace and not by using the token mounted inside the vault pod (otherwise when pod restart auth will break)

**Comment by fabioformosa** [comment]
Hi @ArchiFleKs , how did you configure the `kubernetes auth` to use a long live service account token instead of the deprecated iss field?

**Comment by ArchiFleKs** [comment]
@fabioformosa by using the service account token directly from the secret inside the vault namespace and not using the projected on mounted into the pod in `/var/run/secrets/kubernetes.io/serviceaccount/token`

**Comment by ArchiFleKs** [comment]
Here is an example with a TF module to configure Vault clusters https://github.com/particuleio/terraform-vault-kubernetes-config/blob/main/data.tf

**Comment by fabioformosa** [comment]
Thank you for the fast answer. So, if I've got the point, (doing it without terraform) when I enable the `k8s auth`:

```
vault write auth/kubernetes/config \
    token_reviewer_jwt="<your reviewer service account JWT>" \
    kubernetes_host=https://192.168.99.100:<your TCP port or blank for 443> \
    kubernetes_ca_cert=@ca.crt
```
prior to Vault 1.9, I put `/var/run/secrets/kubernetes.io/serviceaccount/token` in the field `token_reviewer_jwt`, instead now I have to put 
`kubectl get secret "$(kubectl get serviceaccount default -o jsonpath='{.secrets[0].name}')"` into the `token_reviewer_jwt`.

(correct me if I'm wrong)

**Comment by liggitt** [comment]
> now I have to put
> `kubectl get secret "$(kubectl get serviceaccount default -o jsonpath='{.secrets[0].name}')"` into the `token_reviewer_jwt`.

I would *strongly* discourage using auto-generated secret-based tokens this way. Those tokens are only intended to be used to mount into pods, and since the projected tokens are now GA, will no longer be auto-generated.

**Comment by ArchiFleKs** [comment]
> > now I have to put
> > `kubectl get secret "$(kubectl get serviceaccount default -o jsonpath='{.secrets[0].name}')"` into the `token_reviewer_jwt`.
> 
> I would _strongly_ discourage using auto-generated secret-based tokens (the ones recorded in the service account `.secrets` list) this way. Those tokens are only intended to be used to mount into pods, and since the projected tokens are now GA, will no longer be auto-generated in future Kubernetes releases.

@liggitt what would be the right way to setup the vault auth then ?

**Comment by liggitt** [comment]
I can't speak to the vault aspects, but my understanding was that Vault 1.9+ supports using projected service account tokens by default (https://github.com/hashicorp/vault-plugin-auth-kubernetes/issues/125#issuecomment-981815186). If that's the case, I'd recommend you use that, since use of secret-based service account tokens is discouraged, since they are not as secure as projected service account tokens (they don't expire, and you can't scope the audience to anything other than the Kubernetes API server).

If my understanding is incorrect and you still need to use a secret-based token, https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token has details for manually creating a secret-based service account token for use (rather than scraping the auto-created token for independent use).

**Comment by fabioformosa** [comment]
> I would _strongly_ discourage using auto-generated secret-based tokens

Hi @liggitt, I've reported what is written the Vault doc here: https://www.vaultproject.io/docs/auth/kubernetes#continue-using-long-lived-tokens
```
kubectl get secret "$(kubectl get serviceaccount default -o jsonpath='{.secrets[0].name}')"
```
I agree that using default tokens is not a best practice. So, you say the Vault doc is doing only an example of how to use a service-account token and it's recommended to generate its own service account with a related token. Right?

**Comment by liggitt** [comment]
Yeah, I just opened https://github.com/hashicorp/vault/issues/13844 to report that the instructions on that page are not robust. They happen to work by piggy-backing on the secrets created for mounting, but will not work in future releases.

**Comment by ArchiFleKs** [comment]
Not sure how to use it because even if they removed the issuer verification on 1.9 by default, projected service account are short live and live only during the lifetime of Vault pods. The issue I was having even when disabling issuer verification on 1.8 was that after a Vault restart, Kubernetes Auth was broken because the token stored in Vault was not valid anymore

**Comment by ArchiFleKs** [comment]
So the solution would be to manually create the service account for Vault auth based on this : https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token

**Comment by tomhjp** [comment]
As mentioned, there are two separate changes to tokens that became prominent for Vault Kubernetes auth with k8s 1.21 - the issuer changed and their lifetime became finite.

For the issuer change, we recommend disabling issuer verification and that is the new default when creating new k8s auth mounts from 1.9.0.

For the finite lifetime change, we recommend using the newly released auto-reloading feature in 1.9.3. That should be documented on our website, but I've just checked and it hasn't been updated for 1.9.3 which I'll chase on. However, you can see a preview [here](https://vault-git-main-hashicorp.vercel.app/docs/auth/kubernetes#use-local-service-account-token-as-the-reviewer-jwt) (ignore the 1.10+ requirement, it is backported to 1.9.3 too, and that will be reflected on the main site soon). So as of 1.9.3, you can now skip specifying the CA or reviewer JWT when configuring k8s auth as long as Vault is running in the same k8s cluster, and it will automatically read in its own pod's service account token for use as the reviewer JWT. It automatically refreshes that JWT regularly to ensure it picks up new tokens when k8s rotates them.

**Comment by ArchiFleKs** [comment]
Thanks a lot for your answer @tomhjp, what about when connecting other cluster with external Kubernetes Auth ?

Right know what I’m doing is using the long lived service account token created by the vault injector when I install it on other cluster and add this to my new Kubernetes Auth. 

The prefered method for this would be to manually create long lived token on the external Kubernetes cluster ?

**Comment by tomhjp** [comment]
If Vault is outside the cluster you're authenticating from, that leaves you with 3 main options, summarised [here](https://www.vaultproject.io/docs/auth/kubernetes#how-to-work-with-short-lived-kubernetes-tokens):

* Apply the `system:auth-delegator` ClusterRole to all service accounts that are clients of Vault, and don't set `token_reviewer_jwt` when configuring k8s auth. Then the client token is used as the reviewer token
* Use a long-lived token, as described [here](https://www.vaultproject.io/docs/auth/kubernetes#continue-using-long-lived-tokens) - it's up to you which long-lived token you use, but we would recommend creating a dedicated one as in those instructions.
* Or my personal favourite for Vault-outside-the-cluster, use JWT auth and treat Kubernetes as an OIDC provider, as detailed [here](https://www.vaultproject.io/docs/auth/jwt/oidc_providers#kubernetes).

IMHO there is no one-size-fits-all solution when Vault is outside the cluster, so your preferred method will depend on your own requirements.

**Comment by asenyaev** [comment]
Hi, @tomhjp!

If I use `system:auth-delegator` for all service accounts and set `enableSecretRotation: true` in helm chart of [secrets-store-csi-driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/charts/secrets-store-csi-driver/values.yaml#L200), then I have a lot of tokens inside of Vault (`/vault/data/sys/token`) at some moment. 10Gb (default space for PV) can be reached after a week and all services will be down, because they cannot sync secrets.

Do you know why these secrets don't get deleted after a while?
