### ISSUE TITLE
Anywhere Vault expects a Go time.ParseDuration string it should be documented (e.g. ttl)

### ISSUE THREAD

**Issue by grempe** [hashicorp/vault#1195]
I could only find a single link in the documentation (on a deep sub-page) where it was documented how you can format `ttl` and other options that expect something parseable by the Go `time.ParseDuration` call.

I had to search in the code to figure out what was accepted.

https://github.com/hashicorp/vault/search?p=1&q=time.ParseDuration&utf8=✓

The documentation from Go should be pulled into Vault and any option that expects this type of option should document what it accepts (or point to a single location that explains it).  Don't assume people know that Vault is implemented in Go or what Go's conventions are.

https://golang.org/pkg/time/#ParseDuration

I was also ask for consideration that everywhere that takes one of these values be modified to accept simple Integers and cast those to seconds.  So `15` and `15s` would be equivalent and you can represent values of arbitrary size in seconds.

**Comment by jefferai** [comment]
> The documentation from Go should be pulled into Vault and any option that expects this type of option should document what it accepts (or point to a single location that explains it).

@grempe Agreed, when this format is used, it ought to be documented, and in a large number of cases it already is.

> I was also ask for consideration that everywhere that takes one of these values be modified to accept simple Integers and cast those to seconds. So 15 and 15s would be equivalent and you can represent values of arbitrary size in seconds.

This is already the case in a large number of places, but not everywhere.

PRs are welcome for the gaps in both places!

**Comment by grempe** [comment]
Hi. It's not clear why this issue was closed when you seemed to agree that a doc and code fix would be welcome.

**Comment by jefferai** [comment]
Hi @grempe ,

Code/doc fixes would come in the form of a/some PR(s), which would have separate state.

**Comment by chiefy** [comment]
This had me scratching my bald head for 20-30 minutes until I got out POSTMan, gonna make a PR later.

**Comment by grempe** [comment]
Hmmm. Confused as to why @vishalnayak has closed this issue (**again**) without any comment. It seemed that @chiefy was on this.  Not sure why this is apparently controversial.

**Comment by jefferai** [comment]
Hi @grempe,

It was reopened by mistake. Sorry about that!
