### ISSUE TITLE
UI - Long key names overlap values

### ISSUE THREAD

**Issue by axi92** [hashicorp/vault#11972]
**Describe the bug**
Long key names in the web ui overlap values
![grafik](https://user-images.githubusercontent.com/1394837/124095533-11793500-da5a-11eb-97e9-50b286352a72.png)

**To Reproduce**
1. Use a long key name in the vault ui
2. See overlapping

**Expected behavior**
On the right side there is a lot of space that could be used.
![grafik](https://user-images.githubusercontent.com/1394837/124095703-38d00200-da5a-11eb-996c-17005037c985.png)

If the Key rows would not have the class "is-one-quarter" it would look like this:
![grafik](https://user-images.githubusercontent.com/1394837/124096221-ac720f00-da5a-11eb-9b23-a22d0d242d1e.png)

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault 1.7.3
* Server Operating System/Architecture: photonOS

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by hellobontempo** [comment]
Hi @axi92,
Thanks for the bug report! I've created a ticket, and we'll be looking into this for 1.9.

**Comment by mladlow** [comment]
@hellobontempo did we fix this?

**Comment by hellobontempo** [comment]
@mladlow - Nope - we have a ticket for it, but it's in the backlog. Would you like me to pull it into the next sprint?

**Comment by mladlow** [comment]
@hellobontempo sounds good. I'm going to remove the milestone from this issue, since we have it tracked somewhere else, and the milestone is confusing when we're prepping a release.

**Comment by hellobontempo** [comment]
@mladlow Ah right - thank you!
