### ISSUE TITLE
Not Able to List secrets from Vault with Template 

### ISSUE THREAD

**Issue by lakshmisivareddy** [hashicorp/vault#11976]
Hi Team 

i am trying to list vault secrets using vault agent template 
i am using below .hcl file and template.ctmpl , there is no error but i am not able  list in my destination file 

please find the attached logs and screen shorts

vault{
 address="http://127.0.0.1:8200"
}
pid_file = "/vault/config/pidfile"

auto_auth {
  method "approle" {
    mount_path = "auth/approle"
       config = {
           role_id_file_path = "/vault/config/localroleid"
           secret_id_file_path = "/vault/config/localsecretid"
           remove_secret_id_file_after_reading = false 
       }
   }
   sink "file" {
       config = {
           path = "/vault/config/vault_token"
       }
   }
}

template {
  source      = "/vault/config/template.ctmpl"
  destination = "/vault/config/render.txt"
}

template.ctmpl:
{{ with secret  "mytest/foo"  }}
{{ range $k, $v := .Data }}
{{ $k }}: {{ $v }}
{{ end }}{{ end }}

{{ range secrets "mytest/" }}
{{ . }}{{ end }}

{{ range secrets "mytest/" }}
{{ with secret (printf "mytest/%s" .) }}{{ range $k, $v := .Data }}
{{ $k }}: {{ $v }}
{{ end }}{{ end }}{{ end }}

Valut agent Logs:
==> Vault agent started! Log data will stream in below:

==> Vault agent configuration:

                     Cgo: disabled
               Log Level: debug
                 Version: Vault v1.7.1
             Version Sha: 917142287996a005cb1ed9d96d00d06a0590e44e

2021-07-01T16:41:39.248Z [INFO]  sink.file: creating file sink
2021-07-01T16:41:39.251Z [INFO]  sink.file: file sink configured: path=/vault/config/vault_token mode=-rw-r-----
2021-07-01T16:41:39.253Z [INFO]  template.server: starting template server
[INFO] (runner) creating new runner (dry: false, once: false)
2021-07-01T16:41:39.253Z [INFO]  sink.server: starting sink server
2021-07-01T16:41:39.253Z [INFO]  auth.handler: starting auth handler
2021-07-01T16:41:39.253Z [INFO]  auth.handler: authenticating
[DEBUG] (runner) final config: {"Consul":{"Address":"","Namespace":"","Auth":{"Enabled":false,"Username":"","Password":""},"Retry":{"Attempts":12,"Backoff":250000000,"MaxBackoff":60000000000,"Enabled":true},"SSL":{"CaCert":"","CaPath":"","Cert":"","Enabled":false,"Key":"","ServerName":"","Verify":true},"Token":"","Transport":{"DialKeepAlive":30000000000,"DialTimeout":30000000000,"DisableKeepAlives":false,"IdleConnTimeout":90000000000,"MaxIdleConns":100,"MaxIdleConnsPerHost":9,"TLSHandshakeTimeout":10000000000}},"Dedup":{"Enabled":false,"MaxStale":2000000000,"Prefix":"consul-template/dedup/","TTL":15000000000,"BlockQueryWaitTime":60000000000},"DefaultDelims":{"Left":null,"Right":null},"Exec":{"Command":"","Enabled":false,"Env":{"Denylist":[],"Custom":[],"Pristine":false,"Allowlist":[]},"KillSignal":2,"KillTimeout":30000000000,"ReloadSignal":null,"Splay":0,"Timeout":0},"KillSignal":2,"LogLevel":"DEBUG","MaxStale":2000000000,"PidFile":"","ReloadSignal":1,"Syslog":{"Enabled":false,"Facility":"LOCAL0","Name":""},"Templates":[{"Backup":false,"Command":"","CommandTimeout":30000000000,"Contents":"","CreateDestDirs":true,"Destination":"/vault/config/render.txt","ErrMissingKey":false,"Exec":{"Command":"","Enabled":false,"Env":{"Denylist":[],"Custom":[],"Pristine":false,"Allowlist":[]},"KillSignal":2,"KillTimeout":30000000000,"ReloadSignal":null,"Splay":0,"Timeout":30000000000},"Perms":0,"Source":"/vault/config/template.ctmpl","Wait":{"Enabled":false,"Min":0,"Max":0},"LeftDelim":"","RightDelim":"","FunctionDenylist":[],"SandboxPath":""}],"Vault":{"Address":"http://127.0.0.1:8200","Enabled":true,"Namespace":"","RenewToken":false,"Retry":{"Attempts":12,"Backoff":250000000,"MaxBackoff":60000000000,"Enabled":true},"SSL":{"CaCert":"","CaPath":"","Cert":"","Enabled":false,"Key":"","ServerName":"","Verify":false},"Transport":{"DialKeepAlive":30000000000,"DialTimeout":30000000000,"DisableKeepAlives":false,"IdleConnTimeout":90000000000,"MaxIdleConns":100,"MaxIdleConnsPerHost":9,"TLSHandshakeTimeout":10000000000},"UnwrapToken":false},"Wait":{"Enabled":false,"Min":0,"Max":0},"Once":false,"BlockQueryWaitTime":60000000000}
[INFO] (runner) creating watcher
2021-07-01T16:41:39.262Z [INFO]  auth.handler: authentication successful, sending token to sinks
2021-07-01T16:41:39.262Z [INFO]  auth.handler: starting renewal process
2021-07-01T16:41:39.262Z [INFO]  template.server: template server received new token
[INFO] (runner) stopping
[DEBUG] (runner) stopping watcher
[DEBUG] (watcher) stopping all views
[INFO] (runner) creating new runner (dry: false, once: false)
[DEBUG] (runner) final config: {"Consul":{"Address":"","Namespace":"","Auth":{"Enabled":false,"Username":"","Password":""},"Retry":{"Attempts":12,"Backoff":250000000,"MaxBackoff":60000000000,"Enabled":true},"SSL":{"CaCert":"","CaPath":"","Cert":"","Enabled":false,"Key":"","ServerName":"","Verify":true},"Token":"","Transport":{"DialKeepAlive":30000000000,"DialTimeout":30000000000,"DisableKeepAlives":false,"IdleConnTimeout":90000000000,"MaxIdleConns":100,"MaxIdleConnsPerHost":9,"TLSHandshakeTimeout":10000000000}},"Dedup":{"Enabled":false,"MaxStale":2000000000,"Prefix":"consul-template/dedup/","TTL":15000000000,"BlockQueryWaitTime":60000000000},"DefaultDelims":{"Left":null,"Right":null},"Exec":{"Command":"","Enabled":false,"Env":{"Denylist":[],"Custom":[],"Pristine":false,"Allowlist":[]},"KillSignal":2,"KillTimeout":30000000000,"ReloadSignal":null,"Splay":0,"Timeout":0},"KillSignal":2,"LogLevel":"DEBUG","MaxStale":2000000000,"PidFile":"","ReloadSignal":1,"Syslog":{"Enabled":false,"Facility":"LOCAL0","Name":""},"Templates":[{"Backup":false,"Command":"","CommandTimeout":30000000000,"Contents":"","CreateDestDirs":true,"Destination":"/vault/config/render.txt","ErrMissingKey":false,"Exec":{"Command":"","Enabled":false,"Env":{"Denylist":[],"Custom":[],"Pristine":false,"Allowlist":[]},"KillSignal":2,"KillTimeout":30000000000,"ReloadSignal":null,"Splay":0,"Timeout":30000000000},"Perms":0,"Source":"/vault/config/template.ctmpl","Wait":{"Enabled":false,"Min":0,"Max":0},"LeftDelim":"","RightDelim":"","FunctionDenylist":[],"SandboxPath":""}],"Vault":{"Address":"http://127.0.0.1:8200","Enabled":true,"Namespace":"","RenewToken":false,"Retry":{"Attempts":12,"Backoff":250000000,"MaxBackoff":60000000000,"Enabled":true},"SSL":{"CaCert":"","CaPath":"","Cert":"","Enabled":false,"Key":"","ServerName":"","Verify":false},"Transport":{"DialKeepAlive":30000000000,"DialTimeout":30000000000,"DisableKeepAlives":false,"IdleConnTimeout":90000000000,"MaxIdleConns":100,"MaxIdleConnsPerHost":9,"TLSHandshakeTimeout":10000000000},"UnwrapToken":false},"Wait":{"Enabled":false,"Min":0,"Max":0},"Once":false,"BlockQueryWaitTime":60000000000}
[INFO] (runner) creating watcher
[INFO] (runner) starting
[DEBUG] (runner) running initial templates
[DEBUG] (runner) initiating run
[DEBUG] (runner) checking template 6ea337dad71ae0d5357b63d3722c4e8b
[DEBUG] (runner) missing data for 2 dependencies
[DEBUG] (runner) missing dependency: vault.read(mytest/foo)
[DEBUG] (runner) missing dependency: vault.list(mytest)
[DEBUG] (runner) add used dependency vault.read(mytest/foo) to missing since isLeader but do not have a watcher
[DEBUG] (runner) add used dependency vault.list(mytest) to missing since isLeader but do not have a watcher
[DEBUG] (runner) was not watching 2 dependencies
[DEBUG] (watcher) adding vault.read(mytest/foo)
[DEBUG] (watcher) adding vault.list(mytest)
[DEBUG] (runner) diffing and updating dependencies
[DEBUG] (runner) watching 2 dependencies
2021-07-01T16:41:39.267Z [INFO]  sink.file: token written: path=/vault/config/vault_token
2021-07-01T16:41:39.269Z [INFO]  auth.handler: renewed auth token
[DEBUG] (runner) receiving dependency vault.list(mytest)
[DEBUG] (runner) initiating run
[DEBUG] (runner) checking template 6ea337dad71ae0d5357b63d3722c4e8b
[DEBUG] (runner) missing data for 1 dependencies
[DEBUG] (runner) missing dependency: vault.read(mytest/foo)
[DEBUG] (runner) missing data for 1 dependencies
[DEBUG] (runner) diffing and updating dependencies
[DEBUG] (runner) vault.read(mytest/foo) is still needed
[DEBUG] (runner) vault.list(mytest) is still needed
[DEBUG] (runner) watching 2 dependencies
[DEBUG] (runner) receiving dependency vault.read(mytest/foo)
[DEBUG] (runner) initiating run
[DEBUG] (runner) checking template 6ea337dad71ae0d5357b63d3722c4e8b
[DEBUG] (runner) rendering "/vault/config/template.ctmpl" => "/vault/config/render.txt"
[DEBUG] (runner) diffing and updating dependencies
[DEBUG] (runner) vault.read(mytest/foo) is still needed
[DEBUG] (runner) vault.list(mytest) is still needed
[DEBUG] (runner) watching 2 dependencies
[DEBUG] (runner) all templates rendered

![image](https://user-images.githubusercontent.com/33150961/124159334-aad73400-dab8-11eb-8d15-ca925c3b8b29.png)

![image](https://user-images.githubusercontent.com/33150961/124159378-b9255000-dab8-11eb-90b1-a26e7807dc39.png)

**Comment by lakshmisivareddy** [comment]
i am able to fix the problem

**Comment by chucknelson01** [comment]
How did you resolve?
