### ISSUE TITLE
Avoid printing vault token to stdout w/ vault login

### ISSUE THREAD

**Issue by i5hi** [hashicorp/vault#11986]
When using vault login while inputting the `Token` is hidden. As soon as it is executed it prints the token  to the screen.  

Would be nice if this was not default behavior.

```bash
$ vault login
Token (will be hidden): 
Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

Key                  Value
---                  -----
token                s.***********************************
token_accessor       ********************************
token_duration       ∞
token_renewable      false
token_policies       ["root"]
identity_policies    []
policies             ["root"]
 
$ vault -v
Vault v1.7.3 (5d517c864c8f10385bf65627891bc7ef55f5e827)

```

I will also look into how I could implement this in a fork. Should be fun poking into the source. 

Vault has been awesome by the way. We have been using it for over a year now and not had the chance to thank the entire community for such an awesome core tool!

**Comment by ncabatoff** [comment]
Hi @i5hi ,

If you don't want the token printed to the screen, you can use the `-no-print` option for the login command: https://www.vaultproject.io/docs/commands/login#no-print

**Comment by i5hi** [comment]
Oh awesome. Thanks! 

Would'nt this be better default behaviour? With `-print` as an option if the user wants to see the token - which in most cases they dont.

Its a bit of a nit, but if the team is open to it, I wouldnt not mind looking into making this update.

**Comment by i5hi** [comment]
Usually a `login` method would not display your username and password if successful.

**Comment by ncabatoff** [comment]
> Would'nt this be better default behaviour? With -print as an option if the user wants to see the token - which in most cases they dont.

There was a similar discussion in https://github.com/hashicorp/vault/issues/2758 where the `-no-print` option was introduced.

In my mind `vault login` is intended to be used by humans rather than machines, and is probably going to be followed up by other commands that may or may not be run on the same machine or use the CLI - which is why it's nice for the user to see the token without having to remember where they can get it from on disk.  The fact that the resulting token is written to disk unencrypted means that it's not a super-secure command.  It's more on the "convenience" end of the security/convenience spectrum.



There's also backwards compatibility to consider.  Since it's been like this for years, we have to assume that there's code out there that relies on the current behaviour (even if the intent was that this command would be used interactively.)

**Comment by i5hi** [comment]
Thanks for clarifying!

**Comment by leviathanbadger** [comment]
To be frank... printing the token directly contradicts what it says when you enter the token in the first place. It indicates the token "will be hidden". It's also not even useful information. The user already knows what token they put in, they just typed or pasted it themselves. For manual use, this behavior is shocking, even if it might not be dangerous in most cases.

Automated use is where this crosses the line. CI/CD pipelines often don't protect their run logs as much as they do secret environment variables. Backwards compatibility is important, at least until you start protecting it in favor of _glaring security holes._ And if manual use is the only officially supported use case, then this isn't even technically a breaking change; automated consumption is out of scope.

I get that there's now a flag for this; but the entire point of vault is to protect secret values. Why are access tokens printed to stdout _as the default behavior_? I can't be the only one to be shocked by this, and I _know_ some people won't notice or realize the need to look up a flag to silence it.

**Comment by injeniero** [comment]
This is also shocking to me. I would normally use a CLI in scripts in favor of raw HTTP requests. I'm also facing this issue with our on EC2, we use Vault to keep secrets using AMI login, but the token gets printed on the logs, so it travels all around in our log collector system that everyone in the org can read. 

Now I will add the `-no-print` option, but it feels pretty weird to have to add a parameters to make Vault default behavior secure.
