### ISSUE TITLE
Safari - no popup for OIDC connection

### ISSUE THREAD

**Issue by NevenVucinic-TomTom** [hashicorp/vault#11989]
**Describe the bug**
On Safari browser there is **no popup for OIDC authentication** ,after the user clicks "Sign in with OIDC Provider" , there is an instant error message : 
**The provider window was closed before authentication was complete. Please click Sign In to try again.**
The users cannot access Vault on Safari.

**To Reproduce**
1. Open Safari browser
2. Open URL of your Vault instance
3. Click on "Sign in with OIDC Provider"

**Expected behavior**
Popup with connection to our auth provider prompting for username // password. 

**Environment:**
* Vault Server Version: 1.6.2
* Vault CLI Version" 1.7.1
* Server Operating System/Architecture: Big Sur 11.4 // Safari 14.1.1

**Additional context**
**All users** using Safari are not able to log in to Vault. Users using other browsers (Firefox, Chrome) have no problem with login.

**Comment by pascal-hofmann** [comment]
You have to [allow popups](https://apple.stackexchange.com/a/349407) in Safari.

Apart from that, there is also this [known issue](https://github.com/hashicorp/vault/pull/11906) which will be fixed in the [next release](https://github.com/hashicorp/vault/pull/11906#issuecomment-870815093).

**Comment by NevenVucinic-TomTom** [comment]
Thanks!
