### ISSUE TITLE
Improve postgresql secret backend revoke.

### ISSUE THREAD

**Issue by BSick7** [hashicorp/vault#1198]
## Problem

Currently, the postgresql secret backend allows configuration of role creation through 
```$ vault write postgresql/roles/readonly sql="..."```

There is no way to configure role revocation; this works great if your role creation is similar to the documentation of granting select.

We configure for a role that runs migrations with
```
CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';
GRANT ALL ON ALL TABLES IN SCHEMA public TO "{{name}}";
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO "{{name}}";
```

Since the built-in revocation only removes privileges from tables, the revocation will fail if the role has privileges to any sequence.

I imagine that a role could also have privileges to many other objects (functions, etc.).

### Part 1
Allow a user to configure revocation on a role.
```
$ vault write postgresql/roles/readonly/revoke sql="..."
```

### Part 2
If revocation is not configured, current revocation process will happen.

### Part 3 (out of scope perhaps)
Allow user to do
```
$ vault write postgresql/roles/readonly default=true
$ vault write postgresql/roles/readonly/revoke default=true
```

**Comment by jefferai** [comment]
Hi there,

I'm closing this as it's already something we're working on!

**Comment by BSick7** [comment]
I love you guys. :)

**Comment by jefferai** [comment]
Haha, thanks. Just to clarify, it won't appear in 0.5.2 but it's currently planned for 0.6.
