### ISSUE TITLE
Policy not getting attached to the role 

### ISSUE THREAD

**Issue by shona1ikea** [hashicorp/vault#11991]
**Describe the bug**
During the role creation , even though if we mention any policies to be attached , its not getting attached instead only default policy is getting attached

**To Reproduce**
1. already have a policy jenkins
2. vault write auth/approle/role/jenkins token_policies="jenkins" token_ttl=1h token_max_ttl=4h
                      Success! Data written to: auth/approle/role/jenkins
3. vault read auth/approle/role/jenkins
         Key                      Value
---                      -----
bind_secret_id           true
bound_cidr_list          <nil>
local_secret_ids         false
period                   0s
policies                 [default]
secret_id_bound_cidrs    <nil>
secret_id_num_uses       0
secret_id_ttl            0s
token_bound_cidrs        <nil>
token_max_ttl            4h
token_num_uses           0
token_ttl                1h

**Expected behavior**
vault read auth/approle/role/jenkins should show policy as jenkins as below

Key                        Value
---                        -----
bind_secret_id             true
local_secret_ids           false
secret_id_bound_cidrs      <nil>
secret_id_num_uses         0
secret_id_ttl              0s
token_bound_cidrs          []
token_explicit_max_ttl     0s
token_max_ttl              4h
token_no_default_policy    false
token_num_uses             0
token_period               0s
token_policies             [jenkins]
token_ttl                  1h
token_type                 default

**Environment:**
* Vault Server Version (retrieve with `vault status`):  0.10.3
* Vault CLI Version (retrieve with `vault version`): Vault v1.7.0 (4e222b85c40a810b74400ee3c54449479e32bb9f)
* Server Operating System/Architecture: Windows

Vault server configuration file(s):

```hcl
{
"listener": [{
"tcp": {
"address" : "0.0.0.0:8200",
"tls_disable" : 1
}
}],
"api_addr": "http://34.78.125.185:8200",
"storage": {
"gcs": {
"bucket" : “devopscube-demo",
"ha_enabled" : "true"
}
},
"max_lease_ttl": "10h",
"default_lease_ttl": "10h",
"ui":true
}
```

**Comment by ncabatoff** [comment]
Hi @shona1ikea,

0.10.3 is a very old version of Vault.  In that version there was no `token_policies` field in approle roles; instead, the field was named simply `policies`.  This was changed back in https://github.com/hashicorp/vault/pull/7020.

I highly recommend you upgrade, there have been quite a number of serious bugfixes since 0.10.3, including security fixes.
