### ISSUE TITLE
/sys/health should always return 200 if it returns valid JSON information.

### ISSUE THREAD

**Issue by garthy** [hashicorp/vault#1199]
The HTTP error code returned should be the state of the HTTP call and have nothing to do with the service state. That is well represented in the JSON content. 

Vault service state in the error code makes the logic hard to get correct and when vault returns a 500 for a real error gets messy.

This endpoint should always return 200 if it returns vaild JSON that represents the state of the service

https://www.vaultproject.io/docs/http/sys-health.html

**Comment by jefferai** [comment]
Hi @garthy,

The status codes returned conform to expected status codes for certain service discovery mechanisms. If you want to only use the JSON content, simply ignore the status code.

**Comment by jefferai** [comment]
Hi @garthy ,

> What are these "certain service discovery mechanisms" and where are these defined?

https://www.consul.io/docs/agent/checks.html

> Vault returning the JSON on 500 seems incorrect as Vault has serviced my request and returned the data I asked for?

It adheres to the documentation for that endpoint, which is more specific than the general API documentation (https://www.vaultproject.io/docs/http/sys-health.html)

**Comment by garthy** [comment]
It's fine as I can use the /sys/init endpoint for my use case. I was confusing /sys/health with a generic health of service endpoint. The fact that I can call other endpoints after a 500 on the service confused me.

I have a Cli code that setup/upgrades all our services via compose then waits for the vault service to come up so it can decide what to do. 

I loop on an endpoint and wait for 200 (Or in vaults case 200, 429 or 500)

The problem with this is the 500 can also return an actual error [1].

So I need to complicate my logic.

But the fact that 500 is overloaded means that I need to check the JSON payload and ignore the status code. It just confused me 

[1] -  "{"errors":["failed to check for initialization: Unexpected response code: 500"]}"

**Comment by jefferai** [comment]
I see a few potential ways forward here:

1) Switch from 500 to 503 for the health check. It's more correct ("Service Unavailable"). For backwards compatibility this wouldn't be nice, but:

2) Allow the caller to specify the return codes used.

Let me get some discussion going internally about the 500->503 switch. We could maybe do that for 0.6, with appropriate information in the upgrade notes.

**Comment by jefferai** [comment]
Reopened so I don't forget about it.

**Comment by rhoml** [comment]
I do agree with exploring other error codes, 429 seems pretty vague when a vault server is initialized and unsealed. I would like consul to consider that server as healthy

**Comment by jefferai** [comment]
@rhoml Consul considering standby servers healthy will in most cases simply vastly increase the numbers of redirects your clients experience.

Not everything can parse JSON, but if you have the ability to, you can easily parse Consul's service catalog and pick and choose the statuses you want. Or you can use prepared queries. Or you can simply set the already-existing `standbyok` parameter. Lots of options!

**Comment by rhoml** [comment]
Indeed I can buy I have to obviate the http status code too which is quite weird because the service is healthy.

**Comment by garthy** [comment]
its a 503. Sorry should have printed it in my tests script.
