### ISSUE TITLE
Vault API explorer is returns "There was a problem navigating to the api explorer" on first `api` command in UI

### ISSUE THREAD

**Issue by sirjobzy** [hashicorp/vault#12009]
The first time I open and  type `api` in vault browser CLI, I get "There was a problem navigating to the api explorer". Although it loads the API explorer, it will be nice not to have this error shown. Subsequent invocation of api command loads up without any error.

I am using the root token.

**To Reproduce**
1. Login to vault UI
2. open the Vault Browser CLI
3. Type `api`

**Expected behavior**
It should return:
'Welcome to the Vault API explorer! 
You can search for endpoints, see what parameters they accept, and even execute requests with your current token.'

**Environment:**
* Vault Server Version : Vault 1.7.1+ent, Vault 1.7.3
* Server Operating System/Architecture: Ubuntu

**Comment by ncabatoff** [comment]
Hi @sirjobzy,

Thanks for the bug report!  I've reproduced your issue and tagged the UI team in.

**Comment by arnav28** [comment]
Hi @sirjobzy 
We have fixed the issue and it will be available in 1.7.5 version. Thanks :)
