### ISSUE TITLE
Array-type metadata values

### ISSUE THREAD

**Issue by kristian-lesko** [hashicorp/vault#12039]
**Is your feature request related to a problem? Please describe.**
I love the possibility of using metadata values in policies, but I'm feeling a bit limited by only `string`-type metadata values being supported. Some use cases requiring `1:1` mapping of users to Vault paths are easily modeled by this, such as "user X can manipulate Vault path subtree Y"; however, a `1:n` mapping of users to paths is not easy to model - for example, "user X can manipulate Vault path subtrees Y, Z and W".

**Describe the solution you'd like**
I'd love it if, for example, an array of values could be set as metadata and then used in policies. For example, given an entity metadata value of `subtrees=[tree1, tree2]` (note: this could be a group metadata just as easily) and a policy like the following:
```hcl
path "secret/data/{{identity.entity.metadata.subtrees}}/data/*" {
  capabilities = ["read", "list"]
}
```
the policy would allow both `secret/tree1/data/*` and `secret/tree2/data/*` to be accessed by the user.

**Describe alternatives you've considered**
The only alternative I see to this is to have multiple policies, which can be provisioned by a configuration management tool (e.g., Terraform), in order to model the same level of access.

**Comment by ncabatoff** [comment]
Hi @kristian-lesko ,

Are you sure that identity metadata allows arrays?  My sense from looking at the code is that it does not, though I might be missing something.

**Comment by kristian-lesko** [comment]
Hello @ncabatoff,

it's very possible it is currently not supported at all; hence my proposal:
> I'd love it if, for example, an array of values could be set as metadata and then used in policies.

I've done some testing where I was able to pass an array-like structure (either comma-separated or JSON array), but these were most probably evaluated as a string, which is why it didn't have the desired effect for me.

**Comment by cwchristerw** [comment]
I would like this to become true one day :smile:
