### ISSUE TITLE
Gitlab auth backend support?

### ISSUE THREAD

**Issue by geovanisouza92** [hashicorp/vault#1203]

**Comment by jefferai** [comment]
Nope, we don't have one, sorry.

**Comment by geovanisouza92** [comment]
Any plans to include it? Maybe an OpenID?

**Comment by jefferai** [comment]
There aren't any current plans, but if someone wants to tackle it we could provide guidance.

**Comment by zaquestion** [comment]
@jefferai could you provide said guidance and insight on the level of work?

**Comment by zaquestion** [comment]
@jefferai Hey just wanted to poke you again post-holidays

**Comment by jefferai** [comment]
If GitLab supports OIDC, that's coming already.

**Comment by zaquestion** [comment]
@jefferai I'm not super familiar with the space. From this doc ( https://docs.gitlab.com/ee/integration/openid_connect_provider.html ) looks like a yes, could you possibly try to confirm?

Looks like the implementation is: https://github.com/doorkeeper-gem/doorkeeper-openid_connect

**Comment by zaquestion** [comment]
Additionally, is any assistance needed? We found out late into our migration to GitLab that we rely on GitHub as a auth backend for vault, so we're motivated to help support this.

**Comment by kalafut** [comment]
@zaquestion I can confirm that the Gitlab provider does work with our WIP OIDC code. Their response pattern is a little different than some of the other providers, so this was a useful experiment 🙂.
