### ISSUE TITLE
External Vault auth with kubernetes

### ISSUE THREAD

**Issue by anemptyair** [hashicorp/vault#12038]
I enabled vault auth kubernetes with annother path as an external vault. 

vault auth enable --path="**usw2x-test-eks**" kubernetes

And install only with vault agent in k8s cluster. Trying to inject secrets into pod. But get errors:

2021-07-12T10:37:35.506Z [ERROR] auth.handler: error authenticating:
  error=
  | Error making API request.
  |
  | URL: PUT http://a24edacfffda24a0997bf96f021c4acc-268595448.us-west-2.elb.amazonaws.com:8200/v1/auth/kubernetes/login
  | Code: 400. Errors:
  |
  | * invalid role name "agent-test"

How to make the url from
http://a24edacfffda24a0997bf96f021c4acc-268595448.us-west-2.elb.amazonaws.com:8200/v1/auth/**kubernetes**/login

to
http://a24edacfffda24a0997bf96f021c4acc-268595448.us-west-2.elb.amazonaws.com:8200/v1/auth/**usw2x-test-eks**/login

Command:
vault auth enable --path="**usw2x-test-eks**" kubernetes

vault write auth/usw2x-test-eks/config \
token_reviewer_jwt="$TOKEN_REVIEW_JWT" \
kubernetes_host="$KUBE_HOST" \
kubernetes_ca_cert="$KUBE_CA_CERT"

vault write auth/usw2x-test-eks/role/agent-test \
   bound_service_account_names=agent-test \
   bound_service_account_namespaces="*" \
   policies=agent-vault \
   ttl=0

**Comment by ncabatoff** [comment]
Hi @anemptyair,

We reserve github issues for bug reports and feature requests, which this doesn't appear to be.  As such, I'm going to close this and suggest that you ask about this at https://discuss.hashicorp.com/c/vault/30.
