### ISSUE TITLE
Feature Request: memfd_secret support.

### ISSUE THREAD

**Issue by jboero** [hashicorp/vault#12037]
**Is your feature request related to a problem? Please describe.**
A new feature hits the Linux kernel with version 5.14 called `memfd_secret`.  You might compare this to `mlock` in that it allows memory areas to be allocated hidden from other processes and process tables.  This interesting feature could be used to protect master keys or keyrings and block a memory attack as described in my hardening post here: https://medium.com/hashicorp-engineering/how-id-attack-your-hashicorp-vault-and-how-you-can-prevent-me-system-hardening-ce151454e26b

The feature is described here, and I'm not sure yet how Go will support it:
https://min.news/en/tech/cc3aa8ba67a20223352b0ea6f0a26129.html
https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.14-memfd_secret

**Describe the solution you'd like**
Vault probably shouldn't store everything using memfd_secret but critical core secrets like the key ring would benefit from being stored in a secret memory area.  It would be nice to have a config option `memfd_secret_enabled=true` where supported systems could store critical bits inside hidden memory.  The feature is disabled by default for backwards compatibility.  If enabled on an unsupported system (Linux <5.14) an error should prevent Vault running as a user might assume it's working fine.

**Additional context**
The Vault team is probably best to decide priority on what data would benefit from hidden memory.

**Comment by hsimon-hashicorp** [comment]
Hi @jboero - would you be willing to create an Asana item for this?

**Comment by jboero** [comment]
@hsimon-hashicorp yes that would be great.  I'll do it today.

**Comment by hsimon-hashicorp** [comment]
@jboero I'm going to go ahead and close this issue, as we will be tracking this internally. Thanks!

**Comment by awnumar** [comment]
Hey 👋 
Are there updates on this? It would be nice to be able to track progress in the open
