### ISSUE TITLE
Web UI PGP Init Bug

### ISSUE THREAD

**Issue by joeyberkovitz** [hashicorp/vault#12056]
**Describe the bug**
When attempting to initialize Vault using PGP encryption for unseal keys, only `PGP KEY 1` is displayed if `Encrypt output with PGP` menu is opened before entering number of key shares.

**To Reproduce**
1. Start new Vault server
2. Open Vault web interface in browser
3. Expand `Encrypt output with PGP` menu
4. Enter number of `Key shares` using value greater than 1
5. Confirm that only one PGP key input is listed in the `Encrypt output with PGP` menu

**Expected behavior**
The number of PGP key inputs should always match the specified number of key shares.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.7.3
* Vault CLI Version (retrieve with `vault version`): Vault v1.7.3 (5d517c864c8f10385bf65627891bc7ef55f5e827)
* Server Operating System/Architecture: CentOS 7.9.2009
* Browser: Chrome 91.0.4472.124

Vault server configuration file(s):
Same as provided by Vault RHEL repo
```hcl
ui = true

storage "file" {
  path = "/opt/vault/data"
}

# HTTPS listener
listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/opt/vault/tls/tls.crt"
  tls_key_file  = "/opt/vault/tls/tls.key"
}
```

**Comment by hashishaw** [comment]
Thank you for reporting this bug @joeyberkovitz! We'll work on a fix right away. In the meantime if you toggle the "Encrypt output with PGP" link, it will refresh the number of inputs shown. 

![pgp-ui-workaround](https://user-images.githubusercontent.com/82459713/127232512-616a6038-1a6a-4beb-9f3d-fe59d760fca5.gif)

**Comment by hashishaw** [comment]
This issue has been fixed! Please feel free to re-open this issue if you see it crop up again.
