### ISSUE TITLE
Vault INIT fails with version 0.5.1

### ISSUE THREAD

**Issue by gandg** [hashicorp/vault#1206]
>> vault init 
Error initializing Vault: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/init
Code: 400. Raw Message:

400 Bad Request: invalid header value

>> vault -v
Vault v0.5.1

**Comment by jefferai** [comment]
Hi @gandg ,

What is Vault's configuration? What is in Vault's log? What version of the server is running?

Thanks!

**Comment by gandg** [comment]
64 bit OSX version.  simple config: file backend with tls disabled. both client and server are v0.5.1.  
I set log output to debug and did not see anything on the log output

==> WARNING: mlock not supported on this system!

  The `mlock` syscall to prevent memory from being swapped to
  disk is not supported on this system. Enabling mlock or
  running Vault on a system with mlock is much more secure.

==> Vault server configuration:

         Log Level: debug
             Mlock: supported: false, enabled: true
           Backend: file
        Listener 1: tcp (addr: "127.0.0.1:8200", tls: "disabled")
           Version: Vault v0.5.1

==> Vault server started! Log data will stream in below:

**Comment by jefferai** [comment]
@gandg Unfortunately nobody on the Vault team has an OSX machine at the moment. I will see if I can get someone else to give this a try and see if they encounter a similar error.

**Comment by gandg** [comment]
No problem.  The workaround is that I was able to init with 0.5.0, then update to v0.5.1 and all worked

**Comment by jefferai** [comment]
Interesting. That's an excellent data point to have...

**Comment by jefferai** [comment]
Hi @gandg ,

I just got my paws on an OSX box and downloaded our 64-bit 0.5.1 release. I used this config:
```
backend "file" {
path="/Users/....../vault-file"
}
listener "tcp" {
address="127.0.0.1:8200"
tls_disable="true"
}
```
I was able to start the server, then run `vault init` against it with no issues.

This is on 10.10 -- what version of OSX are you on?

Thanks!

**Comment by gandg** [comment]
OSX 10.10.5

**Comment by jefferai** [comment]
That's what I was on too. That is very strange. Init code wasn't touched between the releases, and I couldn't reproduce it with the same binary and OSX version. It is definitely strange about the "Bad header value" error as that doesn't come directly from Vault. Any chance you are running Little Snitch or some other kind of software that may munge with connections?

**Comment by jmccarty3** [comment]
I had this issue as well on my Mac. Deleting the old ~/.vault-token and re-authing seems to have fixed the issue.

**Comment by jefferai** [comment]
No response from OP so closing -- please request to be reopened if needed!

**Comment by waliul-cse** [comment]
Hello guys,
If I execute the following command to run vault server in production mode from windows 8 machine then got a **WARNING: mlock not supported on this system!**

backend "file" {
  path = "C:\\Keymanager\\consul"

}
listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
}

**and shows the following message..**
The mlock syscall to prevent memory from being swapped to
disk is not supported on this system. Enabling mlock or
running Vault on a system with mlock is much more secure.
==> Vault server configuration:

     Log Level: debug
         Mlock: supported: false, enabled: true
       Backend: file
    Listener 1: tcp (addr: "127.0.0.1:8200", tls: "disabled")
       Version: Vault v0.5.1
==> Vault server started! Log data will stream in below:

Please help me out.Thanks in advance.

**Comment by jefferai** [comment]
@waliul-cse Your question is not related to the subject of this issue. Please raise your question on the mailing list. Thanks!

**Comment by waliul-cse** [comment]
Hello @jefferai  can you provide me the email on where i got that solution? thanks

**Comment by waliul-cse** [comment]
Hello @jefferai  my question is also on subject type cause I can't init vault due to not successfully run the vault server.My OS is Windows 8.1 and vault v0.5.1 and my configuration is like ..

backend "file" {
  path = "C:\\Keymanager\\consul"

}
listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
}
Please give me some suggestion that how I can run vault server without getting mlock warning and then can execute vault init command.Thanks in advance.
