### ISSUE TITLE
Starting in Docker container: Error initializing core

### ISSUE THREAD

**Issue by heytrav** [hashicorp/vault#121]
I'm attempting to follow the tutorial using a  `ubuntu:trusty` Docker container and am getting the following error when I try to start vault:

```
root@31a7d422e87f:/# vault server -dev
Error initializing core: failed to lock memory: cannot allocate memory
```

I'm not sure if this is due to Docker, or if there is something special about memory allocation in general in Docker that needs to be done here so vault will work.

Here is the [Dockerfile](https://gist.github.com/heytrav/aec594be5af402e13390)

**Comment by ryanking** [comment]
https://github.com/hashicorp/vault/issues/97

**Comment by heytrav** [comment]
Thanks! Closing as a duplicate.

**Comment by mitchellh** [comment]
@heytrav Its not a bug, you need to give your container the MLOCK cap

**Comment by heytrav** [comment]
I figured it would be something like that. I just hadn't run across this in Docker before and wasn't sure.

**Comment by heytrav** [comment]
I added `--cap-add IPC_LOCK` as in the other #59 and it worked.
