### ISSUE TITLE
Export vault secrets to envs with source command failed.

### ISSUE THREAD

**Issue by anemptyair** [hashicorp/vault#12109]
I want to export vault secrets to envs into pod, add source /vault/secrets/db refer to 
https://www.vaultproject.io/docs/platform/k8s/injector/examples#environment-variable-example
But it did't work. If i enter into pod with kubectl exec and run source then it work.
My yaml of test pod :

apiVersion: v1
kind: Pod
metadata:
  name: vault-agent-test
  namespace: default
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-init-first: "true"
    vault.hashicorp.com/agent-inject-secret-db: "agent-vault/qa"
    vault.hashicorp.com/agent-inject-template-db: |
      {{ with secret "agent-vault/qa" -}}
        export order_database="{{ .Data.database }}"
        export order_username="{{ .Data.username }}"
        export order_password="{{ .Data.password }}"
      {{- end }}
    vault.hashicorp.com/role: "agent-test"
    vault.hashicorp.com/auth-path: "auth/euc1b2-dev-eks"
spec:
  containers:
  - image: busybox
    command: ["/bin/sh"]
    args: ["-c", "echo 'hello' && source /vault/secrets/db && echo 'end' && sleep 3600"]
    imagePullPolicy: IfNotPresent
    name: busybox
  serviceAccountName: agent-test
  restartPolicy: Always

**Comment by hsimon-hashicorp** [comment]
Hi @anemptyair! Could you provide more information about this, please? For example, do you receive an error when you try to run the export? Thanks!

**Comment by anemptyair** [comment]
> Hi @anemptyair! Could you provide more information about this, please? For example, do you receive an error when you try to run the export? Thanks!

No , I have not saw any error. Just run "env" , I can't get "order_database" "order_usrname" and "order_password"

**Comment by syamsullivan** [comment]
i had same issue when env not working properly when using template

**Comment by hsimon-hashicorp** [comment]
Hi @anemptyair! The environment variables won't be visible to you, only to your busybox process. You should be able to see the variables in the output of your container logs. Alternately, you may wish to try using the Vault CSI provider, which can allow for a better experience using envs: https://www.vaultproject.io/docs/platform/k8s/csi/examples#environment-variable-dynamic-database-credentials

**Comment by hsimon-hashicorp** [comment]
Since this has been in waiting-for-response since July 29th, I'm going to close this issue at this time. Please feel free to re-open it if you think that it's needed. Thanks!
