### ISSUE TITLE
Make it obvious in Getting Started docs that KV PUT will wipe out existing keys

### ISSUE THREAD

**Issue by vaibhavdesai137** [hashicorp/vault#12170]
**Is your feature request related to a problem? Please describe.**
When joining a new company that already uses Vault, it's fair to say you'll be appending keys to existing paths. With no prior vault experience, first thing I searched for is "vault create secret" and I got pointed to official docs. Without reading anything (my bad), I simply copied the `kv put` command, changed the path, added the key-value I needed and executed it. To my surprise, all previous keys under that path were wiped out. This is not what I was expecting. I then went back to the docs and it does say somewhere `The vault kv put command creates a new version of the secrets and replaces any pre-existing data at the path if any`. It was too late already. Thankfully, restoring to previous version was straight forward.

The getting started doc is here: https://learn.hashicorp.com/tutorials/vault/getting-started-first-secret

**Describe the solution you'd like**
Change the documentation with a warning box at the top BEFORE showing the command to create a new secret to avoid accidents. And having a link to `kv patch` in the warning would be helpful if the user wants to append a new key to existing path.

**Describe alternatives you've considered**
None

**Explain any additional use-cases**
None

**Additional context**
None

**Comment by ThisIsNotTheUserYouAreLookingFor** [comment]
Although I agree a warning box would be nice, this complies with traditional restful design, put being idempotent and a full overwrite, and patch being a partial update.

**Comment by vaibhavdesai137** [comment]
> Although I agree a warning box would be nice, this complies with traditional restful design, put being idempotent and a full overwrite, and patch being a partial update.

Yes, I know that now. When getting started, it wasn't intuitive that `kv put` would follow `HTTP PUT` :)

**Comment by yhyakuna** [comment]
Updated the tutorial based on your feedback.
