### ISSUE TITLE
Add option to define mysql usernames [mysql backend]

### ISSUE THREAD

**Issue by lr-d** [hashicorp/vault#1217]
Currently vault creates dynamic mysql accounts based on this logic "username := fmt.Sprintf("%s-%s", displayName, userUUID)" and assigns it to {{name}}.  I thought it will be nice if there was an option to create static accounts (if there isn't already), which I think some might find useful.  I understand that vault returns an error when the same account is created twice.

**Comment by jefferai** [comment]
Hi @laurence-d 

Can you explain what you mean by "static accounts"? You mean accounts that never expire?

**Comment by laurence-d** [comment]
Hi Jeff, I was referring to the way mysql usernames get created.  As an example this sql statement will create a mysql username derived from the vault auth username + generated UUID:
sql="CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT SELECT ON *.* TO '{{name}}'@'%';"
name will be something like vault-username-xyz123

**Comment by gyoza** [comment]
This would be great for us as well. +1

**Comment by ekristen** [comment]
Curious, what is the use case? Just having predictable usernames? If so, why?

**Comment by gyoza** [comment]
Corporate Policy Denotes that all logins have some trace to the name of the user.

**Comment by ekristen** [comment]
@gyoza can you elaborate? It seems to me that the way usernames are generated this already qualifies? IE if my username is `ekristen`, then I get something like `token-ekristen-8b12981e-bb69-4161-bf34-c227d2bc4a3c`

**Comment by gyoza** [comment]
AAah in out testing we've only seen "token". Ok, we could probably work with this.

**Comment by brianshumate** [comment]
Confirming that current token format is for example, `v-username-readonly-37yz28r001y01v99`.

I think this can be closed now.
