### ISSUE TITLE
vault unseal key not working only during reboot

### ISSUE THREAD

**Issue by vaultnewuser** [hashicorp/vault#12193]
**Describe the bug**
We have vault server launched in our device. We had 1 key created during our development to init/unseal vault. This key is working properly during first boot of vault. 
init:
KEY = vault operator init -key-shares=1 -key-threshold=1 

During reboot, we see the vault is already initialised but sealed.  To unseal the vault, we try the same command, which was used in first boot of vault as shown below:
unseal:
vault operator unseal -tls-skip-verify "$KEY"

Here we see the $KEY seems to be emptied out. Any reason why/when the key can be emtpied out?

**To Reproduce**
1. Launch vault first time with key=1, threshold=1
2. Reboot the system
3. Vault is unable to unseal

**Expected behavior**
Vault should be able to unseal

**Environment:**
* Vault Server Version (retrieve with `vault status`):
vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.2.3
Cluster Name    xxx
Cluster ID      xxxx
HA Enabled      false
* Vault CLI Version (retrieve with `vault version`):Vault v1.2.3
* Server Operating System/Architecture:Linux

Vault server configuration file(s):

disable_mlock = true
storage "file" {
    path = "/xx/xx/xx/vault/"
}

listener "tcp" {
    address = "127.0.0.1:xxxx"
    tls_min_version = "tls12"
    tls_cert_file = "/xx/xx/xx/xx.crt"
    tls_key_file = "/xx/xx/xx/xx.key"
    tls_client_ca_file = "/xx/xx/xx/xx.crt"
}
api_addr = "https://127.0.0.1:xxxx"

**Additional context**

**Comment by hsimon-hashicorp** [comment]
Hi @vaultnewuser! Welcome to the HashiCorp Vault community. This looks like it may be a problem more with the $KEY variable itself, so I would recommend asking in our Discuss forums for help, as you're much more likely to get assistance there and we tend to use GitHub more for bug reports and feature / enhancement requests. You can find the Discuss forum here: https://discuss.hashicorp.com/c/vault/30
Thanks! :)

**Comment by vaultnewuser** [comment]
Hi ,
Thanks for the quick come back, the reason for posting it as an issue is we see the with the same vault key where it is not emptied out is still unable to unseal the vault during reboot the device. Can i re-open this?

**Comment by hsimon-hashicorp** [comment]
Hi @vaultnewuser, there isn't enough information in your issue description to be able to tell why that might be. Can you manually unseal Vault using the key? The output you initially shared is showing an unsealed status. Also, version 1.2.3 is a very old version. We just released 1.8, you may wish to check it out: https://www.vaultproject.io/docs/release-notes/1.8.0

Because this version is so old, we would not be able to perform any bug fixes. Thanks for your understanding!
