### ISSUE TITLE
brew vault update 1.7.3 -> 1.8 broken due to nodejs 16.5.0 -> 16.6.0 dependency on MacOS 10.13

### ISSUE THREAD

**Issue by mvilain** [hashicorp/vault#12221]
**Describe the bug**
can't upgrade vault from 1.7.3 to 1.8 on MacOS 10.13.6 due to nodejs dependency.  Nodejs 16.5.0 is the last version supported on 10.13 due to 16.6.0 requiring Xcode 11.

**To Reproduce**
1. brew upgrade vault

==> Upgrading node
  16.5.0 -> 16.6.0

==> Downloading https://registry.npmjs.org/npm/-/npm-7.19.1.tgz
######################################################################## 100.0%
==> Downloading https://nodejs.org/dist/v16.6.0/node-v16.6.0.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/node/16.6.0 --without-npm --with-intl=system-icu --shared-libuv --shared-nghttp2 --shared-openssl --shared-
==> make install
Last 15 lines from /Users/vilain/Library/Logs/Homebrew/node/02.make:
In file included from ../deps/v8/src/libplatform/tracing/recorder-mac.cc:7:
../deps/v8/src/libplatform/tracing/recorder.h:17:10: fatal error: 'os/signpost.h' file not found
#include <os/signpost.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [/private/tmp/node-20210731-15723-5k7cto/node-v16.6.0/out/Release/obj.target/v8_libplatform/deps/v8/src/libplatform/tracing/recorder-mac.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ../deps/v8/src/libplatform/tracing/trace-writer.cc:14:
../deps/v8/src/libplatform/tracing/recorder.h:17:10: fatal error: 'os/signpost.h' file not found
#include <os/signpost.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [/private/tmp/node-20210731-15723-5k7cto/node-v16.6.0/out/Release/obj.target/v8_libplatform/deps/v8/src/libplatform/tracing/trace-writer.o] Error 1
rm f1a3fb87c0d50a356717503bc1e0e06fe802a845.intermediate
make: *** [node] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Error: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

==> Upgrading vault
  1.7.3 -> 1.8.0

**Expected behavior**
brew will upgrade and install nodejs and vault on MacOS 10.13.

**Environment:**
* Vault Server Version (retrieve with `vault status`): not running
* Vault CLI Version (retrieve with `vault version`): Vault v1.7.3 ('5d517c864c8f10385bf65627891bc7ef55f5e827+CHANGES')
* Server Operating System/Architecture: MacOS 10.13.6

**Additional context**

brew configuration needs to be dependent on an older version of nodejs in order to support MacOS 10.13

https://github.com/nodejs/node/issues/39584

**Comment by ncabatoff** [comment]
Hi @mvilain,

We're not the ones maintaining that, though it is possible to install Vault using homebrew that is HashiCorp-maintained, see https://www.hashicorp.com/blog/announcing-hashicorp-homebrew-tap.
