### ISSUE TITLE
Test report

### ISSUE THREAD

**Issue by waghanza** [hashicorp/vault#1222]
Hi,

I'm try to build a **production** release of `vault` (`0.5.2`) :+1: for this **version**
Is there a way to run test suite verbosely, and transmit test logs (building on a docker instance) ?

Regards,

PS : In fact, some tests are ignored (probably cause of docker env)
```
?   	github.com/hashicorp/vault/builtin/audit/file	[no test files]
?   	github.com/hashicorp/vault/builtin/audit/syslog	[no test files]
```

**Comment by jefferai** [comment]
Hi @waghanza ,

As the output says, there are no test files for those packages. They aren't ignored, there's just nothing to test.

There isn't a way to get verbose output, although you'll automatically get verbose output if a test fails.
