### ISSUE TITLE
[Token Auth] Roles not returning token_no_default_policy 

### ISSUE THREAD

**Issue by tristanmorgan** [hashicorp/vault#12225]
**Describe the bug**
The status of token_no_default_policy is not being returned when reading token role configuration.

**To Reproduce**
1. Run `vault auth enable token`
1. Run `vault write auth/token/roles/test token_no_default_policy=true`
2. Run `vault read auth/token/roles/test`
3. token_no_default_policy is not being returned in response

**Expected behavior**
token_no_default_policy should be displayed (if the default value had been overwritten?)

**Environment:**
* Vault Server Version: 1.8.0, 1.7.3, 1.6.5
* Vault CLI Version : 1.8.0
* Server Operating System/Architecture: Linux amd64

Vault server configuration file(s):

```hcl
-dev","-dev-listen-address=0.0.0.0:8200
```

**Additional context**
I thought it was a problem with the Terraform Vault Provider but even checking cURL showed it was Vault.

**Comment by tristanmorgan** [comment]
**Additional additional context**
`vault read sys/raw/sys/token/roles/test` does show that data is present.

**Comment by tristanmorgan** [comment]
Seems the code is missing from _vault/token_store.go_ `tokenStoreRoleRead()`

**Comment by hsimon-hashicorp** [comment]
Hi @tristanmorgan! We will be taking a look at this soon, however, please feel free to work on a PR and submit it for review too if this is an issue you might feel comfortable tackling. Thanks! :)
