### ISSUE TITLE
Deadlock blocking leader election

### ISSUE THREAD

**Issue by s3than** [hashicorp/vault#12223]
**Describe the bug**
Duplicate of https://github.com/hashicorp/vault/issues/11436

Possibly related to:
https://github.com/hashicorp/vault/issues/5968

The metrics for DynamoDB show little to no traffic until we restored the leader by deleting the instance blocking, once the leader was resolved a large burst of transactions took place.

**To Reproduce**
Unable to repoduce

**Expected behavior**
Either post-election task self recovered or leadership to be taken over by another vault instance.

**Environment:**
* 1.7.2
* Kubernetes, DynamoDB backend

Vault server configuration file(s):

These three screen shots below show the items that occurred during the period

Goroutines increasing
![Screen Shot 2021-08-02 at 8 36 32 AM](https://user-images.githubusercontent.com/6881648/127787338-a8e6ba21-a3e6-4d32-8a5b-f5ce16686d29.png)

Vault Expire Num Leases
![Screen Shot 2021-08-02 at 8 36 51 AM](https://user-images.githubusercontent.com/6881648/127787355-c7473c4b-6cc7-49a4-bbd1-84b66382be87.png)

Vault Expire Revoke
![Screen Shot 2021-08-02 at 8 37 12 AM](https://user-images.githubusercontent.com/6881648/127787369-0dbd86ed-5553-4a60-8f58-5e510b76d652.png)

**Comment by s3than** [comment]
@ncabatoff as requested I've created this new issue.
https://github.com/hashicorp/vault/issues/11436#issuecomment-890341071

**Comment by ncabatoff** [comment]
Thanks @s3than.  Next time this happens, can you get a stack trace please?  Send a SIGUSR2 to the active node and look in the logs for "goroutine trace".  Would also be good to see your HCL config, just redact any bits you'd rather not share.

**Comment by s3than** [comment]
```
"api_addr" = "https://vault.vault:8200"

"listener" "tcp" {
  "address" = "0.0.0.0:8200"

  "telemetry" = {
    "unauthenticated_metrics_access" = true
  }

  "tls_cert_file" = "/vault/tls/server.crt"

  "tls_key_file" = "/vault/tls/server.key"
}

"service_registration" "kubernetes" {
  "namespace" = "vault"
}

"storage" "dynamodb" {
  "ha_enabled" = "true"

  "region" = "us-east-1"

  "table" = "tooling-vault"
}

"telemetry" = {
  "disable_hostname" = true

  "prometheus_retention_time" = "24h"
}

"ui" = true
```

**Comment by hsimon-hashicorp** [comment]
Hi @s3than! Just wanted to check in and see if you'd been able to get the stack trace requested. Let us know, so we can take a peek. Thanks!

**Comment by s3than** [comment]
@hsimon-hashicorp Unfortunately I have not been able to replicate the issue directly.. we did notice that it occurred when the DynamoDB backend was being rate limited and the TTL for Tokens that had the default 32 day period were being cleared.. 

The following items have stopped the related issues.

* Upsizing DynamoDB read/write minimums
* Configuring the TTL's for tokens to be a lower period of time

Given that I have been unable to replicate I'm happy to close off this issue.
