### ISSUE TITLE
vault secrets disable database fails

### ISSUE THREAD

**Issue by mcku** [hashicorp/vault#12238]
I have two databases whose auths are handled by vault. 
Recently I had issues with leases and therefore I wanted to disable the database secret engine through the cli.
It does not disable and I don't get any feedback from the cli.
How can i debug this?

**Environment:**

* Vault Version: 1.7.0
* Operating System/Architecture: kubernetes

**Vault Config File:**
vault + kubernetes role + 2 creds per each db (one user, one root)
dynamic secrets is enabled (but not root rotation)

**Startup Log Output:**
nothing bad

**Expected Behavior:**
The database secret engine should be deleted 

**Actual Behavior:**
context deadline exceeded

**Steps to Reproduce:**
in the vault cli,
`vault secrets disable database` simply hangs

**Important Factoids:**
```
$ vault secrets disable database
Error disabling secrets engine at database/: context deadline exceeded
```

**References:**

**Comment by ncabatoff** [comment]
Hi @mcku ,

This is the same issue as https://github.com/hashicorp/vault/issues/12228: you're timing out trying to clean up the data associated with the database secrets engine.  Have a look there for steps you can take to address this.
