### ISSUE TITLE
InfluxDB 2.x database connection support

### ISSUE THREAD

**Issue by gary-dickenson** [hashicorp/vault#12230]
Here is the issue:

**Terminal 1:**
vault server -dev -dev-root-token-id=root

**Terminal 2:**
export VAULT_ADDR="http://127.0.0.1:8200"
vault secrets enable database

docker run -d -p 8086:8086 \
-e DOCKER_INFLUXDB_INIT_MODE=setup \
-e DOCKER_INFLUXDB_INIT_USERNAME=admin \
-e DOCKER_INFLUXDB_INIT_PASSWORD=adminpass \
-e DOCKER_INFLUXDB_INIT_ORG=my-org \
-e DOCKER_INFLUXDB_INIT_BUCKET=my-bucket \
influxdb:2.0

vault write database/config/my-influxdb-database \
plugin_name="influxdb-database-plugin" \
host=127.0.0.1 \
username=admin\
password=adminpass \
allowed_roles=vault-admin

**Result:**
Error writing data to database/config/my-influxdb-database: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/my-influxdb-database
Code: 400. Errors:

* error creating database object: error verifying connection: error getting if provided username is admin: received status code 401 from server

**This appears to  be cause by the query here:**
https://github.com/hashicorp/vault/blob/v1.8.0/plugins/database/influxdb/connection_producer.go

func isUserAdmin(cli influx.Client, user string) (bool, error) {
	q := influx.NewQuery("SHOW USERS", "", "")

Looks like this is not supported by the v2 client.

**Comment by gary-dickenson** [comment]
The issue is also referenced here:
https://github.com/hashicorp/vault/issues/11109

**Comment by gary-dickenson** [comment]
Creating legacy auth for v1 api:

**Comment by priyaaank** [comment]
It looks like the influx 1.x client library is now moved to a [here](https://github.com/influxdata/influxdb1-client) and the latest 2.x library is [here](https://github.com/influxdata/influxdb-client-go)

Maybe the clients were bundled into repo earlier, but split now. They will need to be reimported and used as per the latest docs I suppose.

**Comment by gary-dickenson** [comment]
Not sure what the intention is.

See this for background

https://github.com/influxdata/influxdb/issues/11035

I would imagine support for V2 and v1.x would be best, driven by config at
the plug-in

**Comment by priyaaank** [comment]
Thanks for linking that issue. It helped in understanding what happened historically with the library. There are two options to drive this

* Query influx DB to retrieve the version and take an approach to query users. This works transparently and does not require a config. 
* Allow a small config to make user query accordingly. This may need some sort of influx version config to be set, possibly as part of the Influx config itself. 

Will explore both a bit more and will recommend an approach before implementing.

**Comment by priyaaank** [comment]
Question to vault core team,

The InfluxDb2.0 has a new client library as well as breaking changes for the newer version. The current plugin code is for version1.x. Adding the code and support for InfluxDB 2.x requires adding both libraries and configuration in parallel. Please confirm that intention to support both version is there and plugin should be able to work with both versions simultaneously.

**Comment by gary-dickenson** [comment]
Hi @briankassouf @gitirabassi, Are you able to recommend the approach to take here please?

**Comment by Zlaticanin** [comment]
Closing this for the same reason Max detailed [here](https://github.com/hashicorp/vault/pull/14035#issuecomment-1260025563)
