### ISSUE TITLE
Dont expose current Vault Version in UI

### ISSUE THREAD

**Issue by Slm0n87** [hashicorp/vault#12250]
**Is your feature request related to a problem? Please describe.**
The vault ui exposes its installed vault version even for unauthorized user.  
This is an sensitive information.  
For example if there came up a known vulnerability in some version, a attacker can directly scan if the instance is affected.  

**Describe the solution you'd like**
There should be an configuration option to disable the output of the vault version in the ui.  
Similar to the "server_tokens off;" option in nginx or "ServerTokens Prod" in apache2.  

**Describe alternatives you've considered**
 May there could be an additional option to show the version for authorized users only.

**Explain any additional use-cases**
-

**Additional context**
![Bildschirmfoto 2021-08-04 um 18 13 56](https://user-images.githubusercontent.com/15322260/128216587-ff9512e5-6391-48cc-95a0-429db9aacc6c.png)

**Comment by aphorise** [comment]
@Slm0n87 can you kindly input if this is still relevant for you and if so why you cant:

> 1. Use a LB or Proxy (HAProxy, Nginx, etc) in front to strip these from the response.
> 2. Make your own build of Vault with the adjustments you're after in the API & UI.

I believe this request should be closed as there are already alternatives in place and there's been no further request for this in the past year since it was raised.

**Comment by aphorise** [comment]
Closing as there's been no follow-up and possible solutions already avaible already noted.
