### ISSUE TITLE
[Packaging] systemd EnvironmentFile overwritten during updates

### ISSUE THREAD

**Issue by hexa2k9** [hashicorp/vault#12275]
**Describe the bug**
When updating Vault from HashiCorp RPM Repositories (running RHEL 8 here) the EnvironmentFile (defaults to `/etc/vault.d/vault.env`) shipped since 1.8.0 (I think) gets overwritten without backup. In my case I've had `GOOGLE_APPLICATION_CREDENTIALS` for Auto-Unseal using Cloud KMS in this. Lacking the variable made Vault fail to start - obviously.

**To Reproduce**
1. Add HashiCorp RPM Repo to system 
2. `dnf install vault-1.8.0`
3. `echo FOO=bar | tee -a /etc/vault.d/vault.env`
4. `dnf update vault`
5. `cat /etc/vault.d/vault.env` # empty :(

**Expected behavior**
When updating the Package it should install the `vault.env` as `.rpmnew` in case changed rather than overwriting it.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.8.1
* Vault CLI Version (retrieve with `vault version`): 1.8.1
* Server Operating System/Architecture: RHEL 8

**Comment by mladlow** [comment]
Hi @hexa2k9,

Thanks for filing the issue, and for the detailed write up!

This will be fixed for the Vault 1.8.2 release, and we've pushed 1.8.1-2 packages where the config files are properly flagged so they won't overwrite user-edited files.

**Comment by hexa2k9** [comment]
Thank you 👍

To make the cycle complete I can confirm it's fine. I ran the update to vault-1.8.1-2.x86_64, `vault.env` was left intact.
