### ISSUE TITLE
systemd issue with vault 1.8.1 on Debian Bullseye

### ISSUE THREAD

**Issue by agh** [hashicorp/vault#12280]
```
● vault.service - "HashiCorp Vault - A tool for managing secrets"
     Loaded: loaded (/lib/systemd/system/vault.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: https://www.vaultproject.io/docs/

Aug 06 21:22:12 brain-sea systemd[1]: /lib/systemd/system/vault.service:29: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.
Aug 06 21:25:00 brain-sea systemd[1]: /lib/systemd/system/vault.service:29: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.
Aug 06 21:25:05 brain-sea systemd[1]: /lib/systemd/system/vault.service:29: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.
```

```
# cat /lib/systemd/system/vault.service
[Unit]
Description="HashiCorp Vault - A tool for managing secrets"
Documentation=https://www.vaultproject.io/docs/
Requires=network-online.target
After=network-online.target
ConditionFileNotEmpty=/etc/vault.d/vault.hcl
StartLimitIntervalSec=60
StartLimitBurst=3

[Service]
EnvironmentFile=/etc/vault.d/vault.env
User=vault
Group=vault
ProtectSystem=full
ProtectHome=read-only
PrivateTmp=yes
PrivateDevices=yes
SecureBits=keep-caps
AmbientCapabilities=CAP_IPC_LOCK
CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK
NoNewPrivileges=yes
ExecStart=/usr/bin/vault server -config=/etc/vault.d/vault.hcl
ExecReload=/bin/kill --signal HUP $MAINPID
KillMode=process
KillSignal=SIGINT
Restart=on-failure
RestartSec=5
TimeoutStopSec=30
StartLimitIntervalSec=60
StartLimitBurst=3
LimitNOFILE=65536
LimitMEMLOCK=infinity

[Install]
WantedBy=multi-user.target
```

```
# apt info vault
Package: vault
Version: 1.8.1
Priority: extra
Section: default
Maintainer: HashiCorp <support@hashicorp.com>
Installed-Size: 173 MB
Depends: openssl, passwd, libcap2-bin
Homepage: https://www.vaultproject.io/
License: MPL-2.0
Vendor: HashiCorp
Download-Size: 64.8 MB
APT-Manual-Installed: yes
APT-Sources: https://apt.releases.hashicorp.com bullseye/main amd64 Packages
Description: A tool for secrets management, encryption as a service, and privileged access management. Please submit issues to https://github.com/hashicorp/vault/issues

N: There are 44 additional records. Please use the '-a' switch to see them.
```

```
# systemd --version
systemd 247 (247.3-6)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

On the latest version of Vault (1.8.1) there still seems to be a packaging issue for Debian, it looks like systemd 247 is used with Bullseye, and this does appear to be packaged specifically for Bullseye (obtained from apt.releases.hashicorp.com) but one of the key names (StartLimitIntervalSec) under [Service] isn't valid so results in warnings being printed to the service log.

This also appears to be the case with Vault (1.8.1) using the Buster packages.

Interestingly, Vault appears to be packaged for Bullseye, but Consul does not appear to exist in the Bullseye repositories so it is also currently harder than necessary to setup Vault using Consul as the backend on Debian Bullseye -- do you want me to file that as an issue separately, and if so, against Vault, or against Consul?

Thank you very much for all that you do in creating and maintaining Vault, Consul and all the Hashicorp products 👏🏻

**Comment by kpenfound** [comment]
Hi @agh, thanks for reporting this!  You're correct, it looks like `StartLimitIntervalSec` isn't valid under [Service], and it's also defined in the correct place under [Unit]. I'll correct this and validate the rest of the options on systemd 247+ as well.

As for the Bullseye repo, all products are intended to be there, but it looks like there's an issue with our tool for adding new deb distros.  I'll get those packages updated for Bullseye. Sorry for the inconvenience!

**Comment by kpenfound** [comment]
The bullseye repo is now updated with all packages available on other distros

**Comment by hsimon-hashicorp** [comment]
This looks like it was fixed in the linked PR, and will be included in future Vault releases. Thanks!
