### ISSUE TITLE
[Plugin Portal] Plugin Submission - artifactory-secrets-plugin

### ISSUE THREAD

**Issue by MitaliBo** [hashicorp/vault#12292]
Please provide details for the plugin to be listed. All fields are required for a submission to be included in the [Plugin Portal](https://www.vaultproject.io/docs/plugin-portal) page.

**Plugin Information**
Name as it would appear listed: Artifactory
Plugin type (secrets/auth/database):secrets
Repository link: https://github.com/jfrog/artifactory-secrets-plugin

**Comment by swenson** [comment]
Thanks for this! It looks like it was added in https://github.com/hashicorp/vault/commit/6f8a68779bc7cc2707c83a25871fb95264e53baf
