### ISSUE TITLE
Vault MySQL SSL settings not working

### ISSUE THREAD

**Issue by tom171296** [hashicorp/vault#12306]
**Describe the bug**
I try to configure my Azure MySQL configuration. When I configure the connection with an SSL certificate I get the error:  "error creating database object: failed to append CA to client options". 

This is weird because I followed the documentation and don't really know what the problem is now. The documentation that I followed:
- https://www.vaultproject.io/api/secret/databases/mysql-maria#parameters
- https://docs.microsoft.com/en-us/azure/mysql/concepts-ssl-connection-security#ssl-default-settings

In kubernetes I created a secret where I stalled the base64 encoded content of the CA and client certificate. This secret is mapped as an extra volume inside the vault helm chart.

**To Reproduce**
1. https://{{your.vault.uri.here}}/v1/sys/mounts/database
{
  "type": "database",
  "config": {
    "force_no_cache": true
  }
}
2. https://{{your.vault.uri.here}}/v1/database/config/mysql
{
  "plugin_name": "mysql-database-plugin",
  "allowed_roles": "*",
  "connection_url": "{{username}}:{{password}}@tcp({{db_address}}:3306)/",
  "max_open_connections": 5,
  "max_connection_lifetime": "5s",
  "username": "{{username}}",
  "password": "{{password}}",
  "tls_certificate_key": "/vault/userconfig/mysql-pem/client_pem",
  "tls_ca": "/vault/userconfig/mysql-pem/ca_pem"
}

3. See error
"error creating database object: failed to append CA to client options". 

**Expected behavior**
I expect the connection to be configured using the CA that I downloaded from azure or it would tell me what is wrong. More specfic than "failed to append CA to client options".

**Environment:**
* Vault version 1.7.3 (deployed with helm chart)
* Server Operating System/Architecture: Kubernetes with vault helm chart version 0.13.0

**Comment by tom171296** [comment]
Solved it.

**Comment by sycured** [comment]
Hi @tom171296 , can you share your fix?
I've the same issue on Azure and I can't disable the secure transport.
Thanks

**Comment by MeijerM1** [comment]
What we did was put the entire content of the client and ca files as string in their respective fields.

**Comment by sycured** [comment]
Ok thanks
