### ISSUE TITLE
PostgreSQL database connections not configurable in UI

### ISSUE THREAD

**Issue by tl-eddie-hoffman** [hashicorp/vault#12303]
**Describe the bug**
Apologies in advanced if PostgreSQL connections are not supported via the UI, but there seemed to be some limited support in 1.7.0.

When creating a new connection in the Vault UI the `postgresql-database-plugin` is not available.

![image](https://user-images.githubusercontent.com/73109001/128950209-b7047fa6-8caf-4ea3-a780-df7aeebe52c2.png)

We have PostgreSQL database connections configured via Terraform and these do not display once clicked on in the UI.

![image](https://user-images.githubusercontent.com/73109001/128950050-662f2c92-b7c1-49b9-b20b-965840bbf84d.png)

The following error is shown in the browser console:

```
vault-3684fc7119ad3ceb320da0abcc6c3c1c.js:2579 Uncaught (in promise) TypeError: Cannot read property 'fields' of undefined
    at r.<anonymous> (vault-3684fc7119ad3ceb320da0abcc6c3c1c.js:2579)
    at vendor-8c9677c796ecebe64358c8c3f0ab97e6.js:1667
    at e.untrack (vendor-8c9677c796ecebe64358c8c3f0ab97e6.js:4097)
    at i.o.get (vendor-8c9677c796ecebe64358c8c3f0ab97e6.js:1667)
    at r.showAttrs (vendor-8c9677c796ecebe64358c8c3f0ab97e6.js:1627)
    at xe (vendor-8c9677c796ecebe64358c8c3f0ab97e6.js:1643)
    at n.o.compute (vendor-8c9677c796ecebe64358c8c3f0ab97e6.js:3350)
    at vendor-8c9677c796ecebe64358c8c3f0ab97e6.js:3320
    at e.track (vendor-8c9677c796ecebe64358c8c3f0ab97e6.js:4096)
    at n.t.value (vendor-8c9677c796ecebe64358c8c3f0ab97e6.js:3320)
```

**To Reproduce**
1. Go to create a connection for the database mount
2. PostgreSQL is not visible

1. Click on an exiting PostgreSQL connection configured via API
2. Only the name of the connection is shown

**Expected behavior**
A connection can be created and configured using the UI.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.8.1
* Vault CLI Version (retrieve with `vault version`):  N/A
* Server Operating System/Architecture: Ubuntu 18.04

**Additional context**
SQL statements were not visible in Vault 1.7.0 before upgrading and "Write Concern" was shown instead. The majority of the configuration was still visible though.

![image](https://user-images.githubusercontent.com/73109001/128950837-e68413e5-c1ea-4691-b208-953a615d8b2c.png)

**Comment by DejfCold** [comment]
+1
I just wanted to file this issue as well.

Also, there is this error in the browser console:
![image](https://user-images.githubusercontent.com/12591578/130672238-88d9307c-5495-4678-974d-7350440d7283.png)

**Comment by DejfCold** [comment]
Hi! @Monkeychip & @chelshaw! Could you please take a look?
I've seen something that looks like a major change (https://github.com/hashicorp/vault/pull/10655) that could be related to this?
Especially seeing that MySQL had to be re added in https://github.com/hashicorp/vault/pull/11532

I've not understood, what exactly changed to cause this apart that it isn't listed in `connections.js` while previously it wasn't listed anywhere, yet still worked.

**Comment by hashishaw** [comment]
Hi @DejfCold, thank you for your detailed report (with screenshots! ❤️) and apologies for the delayed response. We didn't immediately roll out Postgres support with the UI Database Secrets Engine, but as of 1.9 and #12945 it is supported. Please feel free to reopen this issue if you feel we did not sufficiently address your concern.
