### ISSUE TITLE
Prometheus

### ISSUE THREAD

**Issue by Nalum** [hashicorp/vault#1230]
Are there any plans to add prometheus.io as a telemetry option?

**Comment by jefferai** [comment]
There aren't currently. If someone is interested on working on a PR, we could discuss the best way to implement it.

**Comment by carlpett** [comment]
@jefferai I made a quick spike, and since armon/go-metrics already has some support for Prometheus, the changes needed to get it working were quite minor ("working" but with some rough edges). I'll open a pull request and we can discuss if the direction is the right one.

**Comment by mbjelac** [comment]
@carlpett - any updates on this?

**Comment by carlpett** [comment]
@mbjelac My PR was closed due to including networking code from outside Vault, which was a security concern. There is (was?) discussion about building a custom endpoint to avoid that part of the library here: https://github.com/hashicorp/vault/pull/1415#issuecomment-240397398
