### ISSUE TITLE
ISSUE while running VAULT server

### ISSUE THREAD

**Issue by Rakshithakrishna2** [hashicorp/vault#12331]
Hi,

I am wanted to configure vault with consul in order to enable edgex security, while trying to run the vault server using command,
vault server –dev -config=/etc/vault.d/vault.hcl (or)
sudo vault server –dev -config=/etc/vault.d/vault.hcl (or)
vault server –dev -config=vault.hcl 

I am facing issue like in,

"Must specify at least one config path using -config"

I am running the vault server while running the consul server.
Please do provide me solution for the same.
Thank you.

**Comment by pmmukh** [comment]
Hi @Rakshithakrishna2 ! Sorry you've been running into setup issues while adding the config, looking at it, I can't immediately see any problem with what you're doing. However, we typically reserve github issues for bug reports and feature requests, which this doesn't appear to be.  As such, I'm going to close this and suggest that you ask about this at https://discuss.hashicorp.com/c/vault/30, which is a better forum for such setup issues.
