### ISSUE TITLE
Failed to unseal fully initialised vault

### ISSUE THREAD

**Issue by oliverjanik** [hashicorp/vault#12342]
![image](https://user-images.githubusercontent.com/2280140/129846100-7a7793e3-5edb-43c4-be8a-02e643443ac2.png)

version 1.8.1

```
listener "tcp" {  
  address = "0.0.0.0:8200"
  tls_disable = "true"
}

storage "dynamodb" {
  ha_enabled = "true"
  table      = "vault-table"
}

seal "awskms" {
  kms_key_id = "2dc7ed90-dbda-49e6-a0ff-05653bac5c5b"
}
```

The vault has been previously initialised and had data in it.

**Comment by pmmukh** [comment]
@oliverjanik I'm gonna go ahead and close this out, from reading through the conversation it appears that the doubt's been answered. Please feel free to reopen if i'm wrong on that! 
thanks for the followups @ncabatoff  and @aphorise !!
