### ISSUE TITLE
Provide an API model for Vault (e.g., Swagger, RAML)

### ISSUE THREAD

**Issue by skyzyx** [hashicorp/vault#1236]
We're deploying Vault in-house. In order for our various applications to fetch secrets from the vault, we're looking at developing SDKs for Vault in PHP 5.6, Python 3.5 and Java 8.

In an effort to simplify the development of these SDKs and facilitate talking to Vault, it would be incredibly helpful if there were an API model for Vault that we could use for auto-configuring the SDKs for hitting the various endpoints.

[Swagger](http://swagger.io) and [RAML](http://raml.org) are a couple of examples of widely-used API modeling formats.

**Comment by jefferai** [comment]
Hello @skyzyx,

Presently no HashiCorp tools offer such API models and it is not our policy to create them. If this becomes our norm in the future, we will be sure to include Vault when we create them!
