### ISSUE TITLE
Vault 1.8.1 Arm64 crashes during entity creation

### ISSUE THREAD

**Issue by VictorCovalski** [hashicorp/vault#12370]
**Describe the bug**
Vault server crashes when attempting to create an identity entity.

**To Reproduce**
1. Run `vault server -dev -dev-root-token-id=test`
2. Open another shell and run: `VAULT_TOKEN=test VAULT_ADDR=http://localhost:8200 vault write entity/identity name="victor"`
3. See error

**Expected behavior**
An entity should be created and it's id returned.

**Environment:**
* Vault Server Version (Vault v1.8.1 (4b0264f28defc05454c31277cfa6ff63695a458d)) Darwin ARM64 (Mac M1):
* Vault CLI Version (Vault v1.8.1 (4b0264f28defc05454c31277cfa6ff63695a458d)) Darwin ARM64 (Mac M1):
* Server Operating System/Architecture: MacBook Air M1 8GB RAM 256GB SSD

**Additional context**
* Full terminal output [error.txt](https://github.com/hashicorp/vault/files/7016636/error.txt)
* uname -a `Darwin Victors-MacBook.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64`

**Comment by ncabatoff** [comment]
Hi @VictorCovalski , thanks for reporting this.  I'm going to close it since it's a dup of #12368.
