### ISSUE TITLE
Java clients fail to authenticate via Kerberos

### ISSUE THREAD

**Issue by bendemott** [hashicorp/vault#12380]
I haven't been able to get anywhere with this bug, so I'm reaching out here - hopefully someone can point me in the right direction.  

**Describe the bug**
I'm forking the **bettercloud** java driver and adding `Kerberos` support.  
I'm unable to authenticate to Vault via Kerberos from Java clients.  

I described the issue in the [**gokrb5 github project issues**](https://github.com/jcmturner/gokrb5/issues/447)
in greater detail.

I believe this is caused by the fact that Vault does not implement the `gssapi.StatusContinueNeeded` response from `gokrb5`.  - I see in the logs ``continue needed``.

**Vault should** respond with `WWW-Authenticate` header and `401` response when `continue` is required to allow the kerberos session to initialize. 

Some clients (such as the native `gssapi`) are able to perform `pre-emptive` or `opportunistic` authentication where they fully establish the `gss-context` before they even issue a request.

It seems Java cannot do this, so it requires a roundtrip from the server to fully establish the`GSSContext`.

**To Reproduce**
Generate a kerberos `Authorization` header using Java, I did this using [kerb4j](https://github.com/bedrin/kerb4j) 
```
    SpnegoClient spnegoClient = SpnegoClient.loginWithKeyTab("user@EXAMPLE.COM", "./user.keytab");
    SpnegoContext spnegoClient.createContextForSPN("service/host.example.com");
    String spnegoToken = context.createTokenAsAuthroizationHeader();
    System.out.println("Spnego Token is: " + spnegoToken);
```

**Expected behavior**
Continue response from server

**Environment:**
* Vault Server Version: 1.8.1
* Server Operating System/Architecture: RedHat/x86

**Comment by qerub** [comment]
I believe this issue has been resolved with the update to vault-plugin-auth-kerberos v0.5.0 (https://github.com/hashicorp/vault/pull/12930) that brings in gokrb5 v8.4.2 (https://github.com/hashicorp/vault-plugin-auth-kerberos/issues/54 / https://github.com/hashicorp/vault-plugin-auth-kerberos/pull/60) that in turn brings in this bugfix: https://github.com/jcmturner/gokrb5/pull/406

**Comment by bendemott** [comment]
@pmmukh as @qerub said, this should resolve this issue with the merging of #12930 

I'm closing this issue.
