### ISSUE TITLE
auth > tune readme file -- add information how to view configuration

### ISSUE THREAD

**Issue by tograla** [hashicorp/vault#12397]
The [auth - tune readme file](https://github.com/hashicorp/vault/blob/main/website/content/docs/commands/auth/tune.mdx) ([official documenation](https://www.vaultproject.io/docs/commands/auth/tune)) does not show how to view configuration prior and post editing.

**Describe the solution you'd like**
I suggest to add information how to view auth configuration. It really wasn't easy and took me a decent while to figure this out but eventually I managed to confirm my settings using the following commands:
Firstly the most verbose output formatted in the default table fashion:
```
$ vault read /sys/auth
Key          Value
---          -----
approle/     map[accessor:auth_approle_48059fa4 config:map[default_lease_ttl:0 force_no_cache:false max_lease_ttl:0 token_type:default-service] description: external_entropy_access:false local:false options:<nil> seal_wrap:false type:approle uuid:e73f9405-4e50-ea19-9c73-228a47c1da73]
token/       map[accessor:auth_token_290aaf74 config:map[default_lease_ttl:0 force_no_cache:false max_lease_ttl:0 token_type:default-service] description:token based credentials external_entropy_access:false local:false options:<nil> seal_wrap:false type:token uuid:21bb6a05-d330-53ee-572d-ba20f83944d0]
userpass/    map[accessor:auth_userpass_8fac179a config:map[default_lease_ttl:3600 force_no_cache:false max_lease_ttl:14400 token_type:default-service] description: external_entropy_access:false local:false options:<nil> seal_wrap:false type:userpass uuid:1e85c903-a948-5f16-b350-f034ba514818]
$
```
Works but isn't very pretty, so I started experimenting with ```-format=json```, and here is what I managed to get:

The below lists ```type``` of every auth method enabled and then lists the ```.config``` section for each. This is more useable than the above ```table``` format providing you have no more than a handful of methods enabled.
```
$ vault read -format=json /sys/auth/ | jq '.data[].type, .data[].config'
"approle"
"token"
"userpass"
{
  "default_lease_ttl": 0,
  "force_no_cache": false,
  "max_lease_ttl": 0,
  "token_type": "default-service"
}
{
  "default_lease_ttl": 0,
  "force_no_cache": false,
  "max_lease_ttl": 0,
  "token_type": "default-service"
}
{
  "default_lease_ttl": 3600,
  "force_no_cache": false,
  "max_lease_ttl": 14400,
  "token_type": "default-service"
}
```
Finally the most clean output but requiring more advanced use of ```jq```:
```
$ vault read -format=json /sys/auth/ | jq '.data[] | select(.type == "userpass") | {config}'
{
  "config": {
    "default_lease_ttl": 3600,
    "force_no_cache": false,
    "max_lease_ttl": 14400,
    "token_type": "default-service"
  }
}
$
```
It's kinda "_SELECT config FROM data WHERE type = userpass_" query.

**Comment by tograla** [comment]
Maybe the page describing [vault read](https://www.vaultproject.io/api/system/auth#read-auth-method-tuning) should be enhanced. As shown above the output of the command can be a bit cluttered.

**Comment by pmmukh** [comment]
Hi @tograla ! Thanks for submitting the issue! Looks like we actually did have this functionality supported, via the `vault read sys/auth/my-auth/tune` command, we have a PR open https://github.com/hashicorp/vault/pull/12479 to add this to the docs. Sorry about the confusion!

**Comment by yhyakuna** [comment]
@tograla The [doc](https://www.vaultproject.io/docs/commands/auth/tune) is updated now.  Thank you so much for your input.
