### ISSUE TITLE
Role based tokens cannot be renewed?

### ISSUE THREAD

**Issue by JoeOrtiz** [hashicorp/vault#1239]
I started playing with role-based tokens, and it appears that those tokens cannot be renewed by envconsul anymore.

The TTL on those tokens do come with a TTL 0, but I do notice the tokens do last for the token duration, but envconsul cannot renew them anymore, just errors out with lease not found.

**Comment by jefferai** [comment]
Hi @JoeOrtiz ,

What configuration are you using for the token role and what parameters are you providing upon token creation? Tokens coming from roles should never have a TTL of 0 unless they are using a root policy.

**Comment by JoeOrtiz** [comment]
I kinda figured it out. Well if you create a roletoken using the -role parameter, those come out with a 0 TTL, but if I then do a /create without role using the -role token created one, then it shows a lease.

My only concern now is if I create a token out of the role token.. and if the role token creation TTL expires (only thing I see expiring) , and if its an orphan, it won't affect the token created from the role, right?

**Comment by jefferai** [comment]
> I kinda figured it out. Well if you create a roletoken using the -role parameter, those come out with a 0 TTL, but if I then do a /create without role using the -role token created one, then it shows a lease.

It shouldn't:
```
$ vault write auth/token/roles/foo allowed_policies="foo,bar"
Success! Data written to: auth/token/roles/foo

$ vault token-create -role foo -policy=foo 
Key                                                             Value
token                                                           869fe86f-e213-e3b5-e3ec-d06e1f8d401a
token_accessor                                                  c5633b2f-6e18-211c-d227-beaeebefc737
token_duration                                                  2592000
token_renewable                                                 true
token_policies                                                  [default foo]

The following warnings were returned from the Vault server:
* policy "foo" does not exist
```
Please, provide your configuration and the parameters you are using in your calls.

**Comment by JoeOrtiz** [comment]
That shows fine, but can you try a token-lookup on  869fe86f-e213-e3b5-e3ec-d06e1f8d401a ?

**Comment by jefferai** [comment]
TTL is not zero:
```
Key             Value
accessor        fcc18603-3ad7-df2f-83b1-b6d4dbd6073f
creation_time   1.458756161e+09
creation_ttl    2.592e+06
display_name    token
id              bf39f299-b9ca-e39d-816d-5706333cfa63
meta            <nil>
num_uses        0
orphan          false
path            auth/token/create/foo
policies        [default foo]
role            foo
ttl             2.591992e+06
```
I'm closing this as not reproducible. I've asked multiple times for the configuration and parameters you are using; if you can still reproduce it using your setup, please provide this information and I'll try again.
