### ISSUE TITLE
Token based auth vs Cookie

### ISSUE THREAD

**Issue by sherzberg** [hashicorp/vault#124]
I'm curious if it would be possible to also support non cookie auth. I would really like to just pass the token in a header like `Authorization: token <xxx>`.

Any thoughts on supporting this as well?

**Comment by mitchellh** [comment]
Its certainly possible, anything is possible. We'll support both, why not.

**Comment by sherzberg** [comment]
Awesome. I just didn't know if there was some architectural/security reason why cookies are used. Thanks!

**Comment by sethvargo** [comment]
This would certainly be easier for writing API clients. I think the reason we used the cookie approach (/cc @armon) is because of the Login() functionality. Instead of sending a token back, Vault sends back an authenticated cookie.

**Comment by mitchellh** [comment]
@sethvargo Yeah it sends both. 

The historical reasoning is because we also implemented a web UI (which we haven't released yet) and the fact it sends a cookie makes a lot of auth _just work_.

**Comment by mitchellh** [comment]
Fixed
