### ISSUE TITLE
docs: Add page "Vault vs Kerberos"

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vault#1240]
I'm fully aware of https://github.com/hashicorp/vault/issues/306

When I talk to people about Vault's SSH and DB backends, they often argue _"hm, so these kids are trying to reinvent Kerberos?"_.
In fact some of those turn this into tweets: https://twitter.com/unixdaemon/status/710837729844707332

It would be helpful to have a page dedicated to "Vault vs Kerberos" aka how is Kerberos different to Vault feature-wise and what kind of problem is it trying to solve, how easy/difficult it is to integrate with existing systems etc.

**Comment by atomicpirate** [comment]
+1 for this, there is already a page for "Vault vs XYZ" and it would be great to have a "Vault vs Kerberos" section:

https://www.vaultproject.io/intro/vs/index.html

**Comment by jefferai** [comment]
Please PR a comparison if you'd like to see it!
