### ISSUE TITLE
OIDC UI based login not possible with MetaMask installed

### ISSUE THREAD

**Issue by ThomasK33** [hashicorp/vault#12436]
**Describe the bug**
When the [MetaMask](https://metamask.io/) extension is installed and enabled for all sites in Chrome, OIDC based logins are not possible anymore.

**To Reproduce**
1. Run:
	  ```none
	  vault write auth/oidc/config \
	     oidc_client_id="your_client_id" \
	     oidc_client_secret="your_client_secret" \
	     default_role="your_default_role" \
	     oidc_discovery_url="https://login.microsoftonline.com/tenant_id/v2.0"
	  ```
2. Run:
	  ```none
	  vault write auth/oidc/role/your_default_role \
	     user_claim="email" \ 
	     allowed_redirect_uris="http://localhost:8250/oidc/callback,https://online_version_hostname:port_number/ui/vault/auth/oidc/oidc/callback"  \
	     groups_claim="groups" \
	     oidc_scopes="https://graph.microsoft.com/.default" \
	     policies=default
	  ```
3. Install [MetaMask in Chrome](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn) and enable it for all sites.
4. Head over to http://localhost:8200 and try logging in using OIDC in the UI

**Expected behavior**
One should be able to login using OIDC independent of browser extensions.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
  ```none
  Key             Value
  ---             -----
  Seal Type       shamir
  Initialized     true
  Sealed          false
  Total Shares    1
  Threshold       1
  Version         1.8.1
  Storage Type    inmem
  Cluster Name    vault-cluster-66939b64
  Cluster ID      f371d18c-979f-3489-d45d-a57a0e36b8ec
  HA Enabled      false
  ```
* Vault CLI Version (retrieve with `vault version`): `Vault v1.8.1 ('4b0264f28defc05454c31277cfa6ff63695a458d+CHANGES')`
* Server Operating System/Architecture: macOS Big Sur (Version 11.5.2)

Vault server configuration file(s):

Default dev server configs.
Server started using: `vault server -dev -dev-root-token-id=token`

**Additional context**

The `oidcState` variable used in [auth-jwt.js](https://github.com/hashicorp/vault/blob/main/ui/app/components/auth-jwt.js#L128) is getting minified to `t` and apparently MetaMask is overriding it.
This issue started with Vault version 1.8.0 and does not exist in earlier versions.

<img width="2672" alt="Screenshot 2021-08-25 at 20 56 17" src="https://user-images.githubusercontent.com/2198487/130849302-81bdd28f-dd97-4e66-bbfa-847cbe9dd706.png">
<img width="2672" alt="Screenshot 2021-08-25 at 20 56 22" src="https://user-images.githubusercontent.com/2198487/130849315-c244049d-573d-4137-aacc-4588dfe02856.png">

The error message in the UI:
```none
The callback from the provider did not supply all of the required parameters. Please click Sign In to try again. If the problem persists, you may want to contact your administrator.
```
<img width="2672" alt="Screenshot 2021-08-25 at 21 13 09" src="https://user-images.githubusercontent.com/2198487/130851087-9e5aec95-fd59-4fbe-8f08-e998a8cd775d.png">

**Comment by adrianNEMO** [comment]
I am having the same issue. Is there a temporary fix to get OIDC working?

**Comment by hsimon-hashicorp** [comment]
Thanks for the report! I'll take a look at this now. Apologies for the delay.

**Comment by edg956** [comment]
I experienced the same issue with Vault 1.8.4 and the extension `React Developer Tools==5.0.0` on Brave v1.61.114. Solved it by disabling the extension.
