### ISSUE TITLE
Should role deletion also revoke existing leases?

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vault#1243]
When I ran

```sh
vault delete aws/roles/s3-ro
```
I received
```
Success! Deleted 'aws/roles/s3-ro'
```

and expected the IAM User `vault-%s%d-%d` to be gone (since `vault write aws/roles/s3-ro` originally created that user), or at least the access key to be inactive or deleted.

None of that happened, so I went back to find all existing lease IDs to run `vault revoke aws/creds/s3-ro/...`.

Is this a feature or a bug? If it's a feature I think it should be better documented.

**Comment by jefferai** [comment]
This is neither a feature nor a bug. Deleting configuration in Vault does not affect issued leases, although in many/most cases it will prevent renewal of those leases. You can revoke the leases separately if you wish.

**Comment by radeksimko** [comment]
I see, this is basically what I was looking for:

```sh
vault revoke -prefix=true aws/creds/s3-ro/
```
I didn't know about the `prefix` flag.

**Comment by jefferai** [comment]
The CLI is just a wrapper around the JSON API, so it can be useful to take a look at the `sys` endpoints to see what's available rather than hunting through CLI flags: https://www.vaultproject.io/docs/http/index.html
