### ISSUE TITLE
Vault UI > Transit > Verify: UI shows verification is false despite api showing its correct

### ISSUE THREAD

**Issue by firstdorsal** [hashicorp/vault#12442]
**Describe the bug**

Vault UI > Transit > Verify: UI shows verification is false despite api showing its correct

api request with nodejs also works.

![Screenshot-20210826174754-3832x1596](https://user-images.githubusercontent.com/10563452/130995121-3b2f5577-603a-4a09-9c50-05de27cedbdc.png)

**Environment:**
docker-image:  vault:latest
running in development on local machine in latest chromium

**Comment by firstdorsal** [comment]
🥳

**Comment by hsimon-hashicorp** [comment]
> 🥳

Thank you so much for the report, and for your patience!
