### ISSUE TITLE
Add support for AWS ECR as secret backend

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vault#1244]
The idea is to allow CI and deployment systems and users to be able to `docker pull` images from private ECR repositories.

http://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_AWSCLI.html

It is an open question how this would work with the existing AWS backend or whether it should be completely separate.

**Comment by mtougeron** [comment]
I would also like to have this feature. We have some users that should not have general AWS access but they do need to be able to pull or push containers from ECR (we are looking to migrate from dockerhub to ECR). It is a hassle to have to maintain an account for them in AWS just for this purpose.

**Comment by jefferai** [comment]
We have no current plans for a built-in backend to do this, but with our plugin capabilities this can now be easily created by an interested third-party!
