### ISSUE TITLE
SSH/ca/role - Templating for "default_user" field.

### ISSUE THREAD

**Issue by systemmonkey42** [hashicorp/vault#12469]
I would like to ensure a user requesting a signed SSH certificate is assigned a default principal based on their username eg. `{{identity.entity.aliases.auth_userpass_xxxxxxxx.name}}`.

I find myself supporting users who get a certificate signed, and cannot log into the target machine because they didn't use the correct process and supply a principal. 

(Certificates with no `principals` have either no power, or too much power and I want to avoid them.)

```
{
  "algorithm_signer": "rsa-sha2-256",
  "allow_user_certificates": true,
  "allowed_users": "admin,mysql,{{identity.entity.aliases.auth_userpass_xxxxxxxx.name}}",
  "allowed_users_template": true,
  ],
  "key_type": "ca",
  "default_user": "{{identity.entity.aliases.auth_userpass_xxxxxxxx.name}}",
}
```
Currently I can only provide a fixed value for the default user, which can cause unexpected behaviour if the user does not specify their username as the principal.

The workaround I am considering is to specify a `default_user` which is _not_ in the `allowed_user_list` thus triggering the request to fail.  I would rather it succeeded and provided a certificate with a valid principle.

**Comment by hsimon-hashicorp** [comment]
Hello @systemmonkey42! Just to make sure I understand, and that there isn't a separate proposal / fix already available, what kind of behavior would you expect to see in this scenario? What would the correct process look like for you here? Thanks in advance! :)

**Comment by systemmonkey42** [comment]
> Hello @systemmonkey42! Just to make sure I understand, and that there isn't a separate proposal / fix already available, what kind of behavior would you expect to see in this scenario? What would the correct process look like for you here? Thanks in advance! :)

Hi @hsimon-hashicorp 
I was only considering SSH-CA role, where a role definition can currently include a "default_user" field which is used when the client does not specify "valid_principals" in the request.

Today, if I want users (or scripts) to request a signed ssh-cert, the "valid_principals" field is optional, but will result in an unusable certificate if not specified. (unusable in that I require principals at the ssh-server end).  The `default_user` allows me to ensure they get a generic pricipal which matches the role, however I would like be able to provide a  dynamic set of principals and derived from the users token. 

For example, if a user requests from the "dba" role, they can get a certificate with a principal of "dba".  I can use the `allowed_users` template to allow them to REQUEST a certificate with dba and their user name, but I cannot, by _default_, return a certificate with "dba" and their "username".

Many Thanks

**Comment by systemmonkey42** [comment]
A bit of digging points me to #7547 (identity propogation), but I can't tell if that resolves into a working PR I can safely test.

**Comment by ncabatoff** [comment]
This is jogging my memory now, thanks for digging up those old tickets.  I think when we were getting PRs to add templating they offered to include default_user in the scope, and I advised against it from the perspective of keeping the PR simpler.  Probably a mistake, in hindsight.  We're open to this change, but I'm not sure when we'll get around to it.  We'd welcome a PR, if you or anyone reading this is so inclined.

**Comment by systemmonkey42** [comment]
I've started work on this, starting with converting all templating functions to return string slices.

This gives me scope to convert the various individual template expansions to return a single item (slice of one) or a list (eg, all group names, alias names).   Support for "splitting" a string on ',' is something I would want to think about. I like the idea of a metadata entry containing a comma separated list of principals, but as mentioned elsewhere, there is a security risk if the user has access to modify this. (unless that is the intention)

Question:
is `make test` sufficient to run the required validate tests?

It currently builds, runs and passes test, but I'm of the opinion it shouldn't pass.  There is probably more to it.

Thanks

**Comment by hsimon-hashicorp** [comment]
Hi @systemmonkey42 and @ncabatoff if you have the institutional knowledge - what validate tests are we referring to, here? We do have automated CircleCI tests that run for PRs, but I want to make sure I understand the question before signing off on it. Thanks! :)

**Comment by ncabatoff** [comment]
I assume @systemmonkey42 is simply referring to the Go tests, the ones invoked by CircleCI for PRs as you say.

Yes, `make test` will run our tests, though that'll run every test we have, which is almost certainly overkill.  You probably only need to run the tests in `./builtin/logical/ssh` and `./vault` to test your changes.  I usually do that without using `make`, either in my IDE or with the CLI like

```
go test ./vault ./builtin/logical/ssh
```

You'll need Docker to run some of the ssh tests.

**Comment by systemmonkey42** [comment]
> go test ./vault ./builtin/logical/ssh

This is perfect.  The full test suite was taking a very long time and possibly not completing.   Running this command clearly shows the issues I was expecting.

Many thanks.

**Comment by hsimon-hashicorp** [comment]
Hi @systemmonkey42 - I wanted to check in and see if you had further questions, comments, concerns, or a PR you wished to link here. Please let me know how we can help. Thanks!

**Comment by hsimon-hashicorp** [comment]
Hi, @systemmonkey42 - since this issue has been open for a while, I'm going to go ahead and close it for now. Please re-open if you need to or have any further updates. Thanks so much!

**Comment by michaeljs1990** [comment]
Is it possible to re-open this? As it currently stands if you want to limit the principal on a signed CA to the username which I think should/would be a fairly common thing to want you can't do it without the user supplying a `valid_principals` argument to sign.

It seems like since we already can limit the user to the username we should also be able to properly produce a key without input from them.

```
 write \
  -field=signed_key ssh/sign/bastion \
  public_key=@/home/eatingthenight/.ssh/id_rsa.pub \
  valid_principals=myusername
  ```
  
  is currently needed and can lead to user confusion if the system user is different from the vault username.
