### ISSUE TITLE
HTTP API documentation doesn't list Status 405

### ISSUE THREAD

**Issue by saites** [hashicorp/vault#12465]
**Describe the bug**
The HTTP API documentation does not document HTTP status 405. That's not a big deal, but [the docs in question](https://www.vaultproject.io/api-docs#http-status-codes) explicitly request that I open a bug report:

> The following HTTP status codes are used throughout the API. Vault tries to adhere to these whenever possible, but in some cases may not -- feel free to file a bug in that case to point our attention to it!

**To Reproduce**
1. Start a Vault server
2. Make a request with an invalid method, e.g. 
     ```
     curl http://localhost:8200/v1/sys/health --data '{"sealedcode": 200}' -w '%{response_code}'
     ``` 
     (the [sys/health](https://www.vaultproject.io/api-docs/system/health#read-health-information) endpoint uses HEAD and GET + query parameters, so I shouldn't have used `--data`).
3. Observe the HTTP status is (correctly) 405:
     ```
    {"errors":[]}
    405
    ```

**Expected ~~behavior~~ documentation**
The HTTP API status code list might should mention 405.

**Environment:**
* Vault Server Version: 1.8.1
* Vault CLI Version: 1.8.1
(running as a Docker container)

**Additional context**
Thanks for the awesome product and all-around great documentation. I won't be offended if you feel it need not be mentioned.

**Comment by ncabatoff** [comment]
Hi @saites,

Thanks, I'd forgotten of the existence of this table.  I'm adding 405 and also 412, another one that was overlooked.
