### ISSUE TITLE
Matching with ldap group containing "_" not working 

### ISSUE THREAD

**Issue by TH3VenGeuR** [hashicorp/vault#12490]
LDAP Groups containing "_" in the name are not working with vault 1.8.1 (maybe other, did not try)

**To Reproduce**
1. Configure vault to use ldap auth
2. Open syslog in order check user connection
3. Connect with a user which is in a group containing _ in the name
   => Confirm through logs that group list of the user only contains groups without "_" 

**Expected behavior**
All group should be listed in memberlist of a user

**Environment:**
* Vault Server 1.8.1
* Debian 10
* ldap server is freeipa

Maybe this is a known limitation, but did not found in documentation.

**Comment by aphorise** [comment]
@sbutler curious if you'd ever tried this?

**Comment by hsimon-hashicorp** [comment]
@aphorise Did you mean to provide more information here?

**Comment by aphorise** [comment]
@hsimon-hashicorp - I was wondering if this was ever tested - I dont have an LDAP setup otherwise I could give it a try.

@TH3VenGeuR - do you have a ldiff file you can attach for a set of users / groups that I can apply to mock the LDAP setup you'd tested?

**Comment by TH3VenGeuR** [comment]
I just checked and, sorry,  freeipa does not provide ldiff file :( How can i give you more information ? maybe explain the ldap scheme ?

**Comment by aphorise** [comment]
I believe all the related functionality is provided in: [sdk/helper/ldaputil](https://github.com/hashicorp/vault/tree/main/sdk/helper/ldaputil) - there's also [EscapeLDAPValue](https://github.com/hashicorp/vault/blob/main/sdk/helper/ldaputil/client.go#L391) however I dont see `_` underscore in the list.

@TH3VenGeuR - are you able to use: [osixia/docker-openldap](https://github.com/osixia/docker-openldap) instead to provide a complete reproduction? - it's possible to provide ldiffs using that too. A complete setup with the underscored groups and a few users would be good.

**Comment by aphorise** [comment]
@TH3VenGeuR we've not heard back from you. I believe this issue is not relevant (as per my earlier note) and should be closed - if you have a reproduction please share.

**Comment by aphorise** [comment]
There's been a number of LDAP related updates as per the notes in the [CHANGELOG.md](https://github.com/hashicorp/vault/blob/main/CHANGELOG.md).

Hey @TH3VenGeuR if you get a chance to provide a reproduction using for example the docker tool I mention above and with a recent version (1.11.3) of Vault then please do re-open. Closing for now as we've not hear back from you.
