### ISSUE TITLE
Vendoring not working with //go:embed web_ui/*

### ISSUE THREAD

**Issue by heppu** [hashicorp/vault#12507]
I tried to use main branch of vault as dependecy since it has the fix which is needed for Go 1.17 and that's when I found a new problem. When running go mod vendor Go will now try to copy also all files described with //go:embed directive. Since those files are not part of the vaults git repo vault cannot be vendored.

**To Reproduce**
```sh
$ go get -d github.com/hashicorp/vault@main
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
$ go mod vendor
go mod vendor: pattern web_ui/*: no matching files found
```

**Expected behavior**
Running go mod vendor should work with vault as dependecy.

**Environment:**
go1.17 linux/amd64
github.com/hashicorp/vault@main

**Comment by hsimon-hashicorp** [comment]
As this is not a HashiCorp-supported method of using Vault, I will close this issue. If you would like to submit a PR to address this, we'd be happy to review it, but at this time, we will not be making these changes. Thanks for understanding.

**Comment by heppu** [comment]
@hsimon-hashicorp  I have now created the PR so should we reopen this issue or should I create a new one?
