### ISSUE TITLE
approle doc on learning site has an error

### ISSUE THREAD

**Issue by rgevaert** [hashicorp/vault#12510]
Hi,

The example https://learn.hashicorp.com/tutorials/vault/pattern-approle?in=vault/recommended-patterns#worker-spawns-job-runner-and-passes-wrapped-secretid for jenkins isn't correct.

when requesting a wrapped secret-id the json returned is: 
```
{
  "request_id": "",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": null,
  "wrap_info": {
    "token": "s....",
    "accessor": "s....",
    "ttl": 120,
    "creation_time": "2021-09-08T15:12:28.246338145+02:00",
    "creation_path": "auth/approle/role/myrole/secret-id"
  },
  "warnings": null,
  "auth": null
}
```
So the code in the tutorial should be `jq -r '.wrap_info.token'` and not ` jq '.data.secret_id'`

**Comment by hsimon-hashicorp** [comment]
@taoism4504 A pretty simple fix, should be quick? Let me know if I can help here.

**Comment by sxt90128** [comment]
Is that fixed, I can work on this.

**Comment by yhyakuna** [comment]
Fixed. Thank you for reporting!
