### ISSUE TITLE
Support CORS Credentials

### ISSUE THREAD

**Issue by betandr** [hashicorp/vault#12537]
We have a client to Vault which uses MTLS with a certificate to authenticate a user. We'd like to use this client with Vault although need an extra CORS header of `Access-Control-Allow-Credentials`. 

The proposal is to add this header to the `http` package in the `http/cors.go`, such as:

```
w.Header().Set("Access-Control-Allow-Credentials", credentials)
```

...where `credentials` would be true. Currently the `Access-Control-Allow-Origin` header value is true if the `Origin` request is set so maybe it could do something like this to provide the ``Access-Control-Allow-Credentials: true` header if credentials are supplied. 

How would you feel about a PR of this type? Thanks!

**Comment by hsimon-hashicorp** [comment]
Hi @betandr! If you'd like to file a PR for us to review, we'd be happy to do so! Thank you so much for volunteering. :)

**Comment by mickael-hc** [comment]
Thanks for opening this issue. Once the changes in https://github.com/hashicorp/vault/pull/12485 are released, it will be possible to set headers in the configuration file, including `Access-Control-Allow-Credentials` . Release is tentatively scheduled for Vault 1.9.0
