### ISSUE TITLE
token is not hidden after authenticating

### ISSUE THREAD

**Issue by renier** [hashicorp/vault#1253]
renier@artifacts:~$ vault auth
    Token (will be hidden):
    Successfully authenticated!
    token: <token shown here!>
    token_duration: 0
    token_policies: [root]

If the token is not echoed while you are typing it (for security reasons), why is it shown when you authenticate?

**Comment by doublerebel** [comment]
:+1: I would like to see the token mostly sanitized in the confirmation output.

**Comment by jefferai** [comment]
You can use `-no-verify` for this behavior. Basically when you give it the token it performs a lookup and returns the results. You also don't need to use `vault auth`, as its only function is to pop the value you've given it into `~/.vault-token`, and optionally to first verify it and let you know if it's still valid.

**Comment by renier** [comment]
I would like to see the verification, but not the token shown back to me. Does that fit within `vault auth`?

**Comment by jefferai** [comment]
I'm not sure what you mean by "does that fit within `vault auth`"?

**Comment by renier** [comment]
Wondering if showing the verification, but hiding the token, fits within the way `vault auth` currently works.

By default, it already tries to keep the token from the screen, given how the interactive entering of the token is coded. Then it shows the verification with the token displayed. It seems the design of the interactive entering of the token contradicts how verification is shown.

**Comment by jefferai** [comment]
I think that hiding the input wasn't the main intent here, it's just coming from re-using code for entering various types of secrets. The point, instead, was simply keeping the token off of the command line so it didn't show up in terminal history.

Feel free to submit a PR changing this!
