### ISSUE TITLE
vault/api token renew endpoint 

### ISSUE THREAD

**Issue by findmyname666** [hashicorp/vault#12556]
Hello,
I noticed nonconformity between Vault DOC and Vault API client.
This issue focuses on renew endpoint for tokens - **/auth/token/renew**.

1) The [DOC](https://www.vaultproject.io/api/auth/token#renew-a-token) says that client should do **POST** request with some increment. Increment can be of string type e.g. you can probably use value such **1h** as parsed by time.Duration.

2) The [golang Vault API lib](https://github.com/hashicorp/vault/blob/api/v1.1.1/api/auth_token.go#L139) do **PUT** request with increment which has to be of **int** type. However used URL contains API version **/v1/auth/token/renew**.

The same apply also to endpoint [renew-self](https://github.com/hashicorp/vault/blob/api/v1.1.1/api/auth_token.go#L159).
_Please note the client lib seems to work as expected so this issue doesn't affect it's functionality so far._

Side note: DOC mentions that provided increment can be ignored by Vault server. However it is not clear why and in which cases. I just noticed that it isn't necessary for periodic tokens.

```
increment (string: "") - An optional requested lease increment can be provided. This increment may be ignored.
```

**Comment by pmmukh** [comment]
Hi @findmyname666 ! Thanks for filing this issue! You are correct, there is indeed a discrepancy between the docs and the API, the API accepts an integer input, like how the client library works. Also yes, after looking at the code I too think `This increment may be ignored.` applies to periodic tokens, and that the current wording is not very clear about that. I'll update the docs with both changes, thanks for pointing them out!

**Comment by pmmukh** [comment]
Ah this is actually because both go's time.Duration strings, and integer representing seconds, are valid inputs here, based on this input type https://github.com/hashicorp/vault/blob/main/sdk/framework/field_type.go#L16, I'll update the docs to be clearer on that.

**Comment by findmyname666** [comment]
@pmmukh thx a lot.

**Comment by pmmukh** [comment]
I updated the docs to be clearer around when the increment might be ignored, and how the string input is provided. I didn't update the datatype in the docs though, cause while the field can be either string or integer, we'd like only one option in our external docs, so as long as we're saying it's a string everywhere, that should be fine.
