### ISSUE TITLE
inconsistent logic between login and auth-renew

### ISSUE THREAD

**Issue by grunzwei** [hashicorp/vault#1256]
flow that causes problems:

you have a token that is associated with no policies according to its credential backend, after login.

the code in core.handleLoginRequest adds the "default" policy:
			// Add the default policy
			policyMap["default"] = true

later the expiration manager does RegisterAuth.
now you try to renew the token, and reach auth-renew. once again, your credential backend returns that there are no policies for it. 
the auth from cache, however, contains the default policy. 
the policies don't match.

in general, most credential backends will throw an exception here, because they don't know someone changed the policies behind their backs.

**Comment by grunzwei** [comment]
also note that comparison by reflect.DeepEqual, as done in github pathLogin for example, is problematic once core has rebuilt the policy from a map, as order cannot be guaranteed (unless go is special in that regard)
core:
e.Policies = []string{}
			for k, _ := range policyMap {
				te.Policies = append(te.Policies, k)
			}

github/path_login:
if !reflect.DeepEqual(verifyResp.Policies, req.Auth.Policies) {
		return logical.ErrorResponse("policies do not match"), nil
	}

**Comment by grunzwei** [comment]
PS IMO Policies can be a type with a "normalize" method.
the code from core could be moved there and reused by backends to prevent this issue.

**Comment by jefferai** [comment]
Thanks for reporting this! It's a good catch.

We don't normally use `reflect.DeepEqual` for exactly this reason...it slipped through it seems.

Changing policies to a type at this point would lead to backwards compatibility problems, but it's certainly easy to create a method that takes in a `[]string` and treats the contents as policies.
