### ISSUE TITLE
TOTP get expire before period

### ISSUE THREAD

**Issue by zishanj** [hashicorp/vault#12575]
I have set the period to 900 (15 mins) and skew to 1 but the generated TOTP code get expires before it. Am I doing something wrong?

**Comment by hsimon-hashicorp** [comment]
Hi! Can you please provide your config, logs, etc? Also, please feel free to ask for help in our [Discuss](https://discuss.hashicorp.com/c/vault/30) forums, as GitHub issues are primarily for bugs. Thanks!

**Comment by zishanj** [comment]
I thought this is a bug because it should have work out of the box but unfortunately it does not. I have checked the huge log but there is no error related to TOTP.

**Comment by hsimon-hashicorp** [comment]
Hi, please provide your Vault configs (with any sensitive data removed) so we can help. Thanks!

**Comment by zishanj** [comment]
This is vault status info:

```
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    1
Threshold                1
Version                  1.7.1
Storage Type             raft
Cluster Name             vault-cluster-1aaa440f
Cluster ID               65640491-63c0-c4a7-6eb5-4fa062ff870d
HA Enabled               true
HA Cluster               https://vault-1:8201
HA Mode                  active
Active Since             2021-06-30T13:15:41.24155442Z
Raft Committed Index     3951028
Raft Applied Index       3951028
```
Let me know if there is any other specific command that provides you with further required config

**Comment by hsimon-hashicorp** [comment]
Can you please provide information about your totp config? For more assistance, please see the following:
https://www.vaultproject.io/api/system/mfa/totp
https://www.vaultproject.io/api/secret/totp
