### ISSUE TITLE
Vault UI not displaying any internal components

### ISSUE THREAD

**Issue by canadianakin** [hashicorp/vault#12576]
**Describe the bug**
I am running a single node of Vault using Raft storage to test using an NGINX reverse proxy. When logging in to the UI, using the root token, no content is displayed, not even the cubbyhole. In the UI terminal executing the command `vault read /sys/mounts` returns my cubbyhole and other secret engines I've created. 
![image](https://user-images.githubusercontent.com/17092060/133845155-d0f8fe6b-f953-4781-b6f2-e100e709736a.png)
When executing the command `vault read /sys/internal/ui/mounts` the response is:  
auth: {},
secret: {}

The same issue is happening with all paths, like Auth Methods, Policies, etc.

**To Reproduce**
1. Log into vault via UI

![image](https://user-images.githubusercontent.com/17092060/133845031-0cd2b0f1-4bdd-4430-aa9d-660671fa9d59.png)

**Expected behavior**
Visible Secret Engines, Auth Methods, Policies, etc.

**Environment:**
* Vault Server Version (retrieve with `vault status`): v1.8.2
* Vault CLI Version (retrieve with `vault version`): v1.8.2
* Server Operating System/Architecture: Debian 10/x86_x64

Vault server configuration file(s):

```hcl
ui = true

max_lease_ttl = "10h"
default_lease_ttl = "10h"

api_addr = "http://127.0.0.1:8200"
cluster_addr = "http://127.0.0.1:8201"

disable_mlock = true

storage "raft" {
  path = "/opt/vault/data"
  node_id = "node_1"
}

# HTTP listener
listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = 1
}
```

**Additional context**
TLS is terminating at the proxy.

**Comment by canadianakin** [comment]
I'm not completely sure to be honest. I nuked my whole nginx installation and started over using this config as a reference: https://codepre.com/nginx-reverse-proxy-for-hashicorp-vault-in-centos-8.html

I wish I had the answer, but I didn't have the time to test what was explicitly causing the issue.

**Comment by kafeinnet** [comment]
OK, thanks for replying.
