### ISSUE TITLE
Systemd Unit file still uses 'StartLimitIntervalSec' in 'Service' section (Vault 1.8.2 / CentOS 8)

### ISSUE THREAD

**Issue by kBite** [hashicorp/vault#12584]
**Describe the bug**
Systemd Unit file still uses `StartLimitIntervalSec` in 'service' section (Vault 1.8.2 / CentOS 8)

```
# systemctl cat vault | grep 'Unit\|Service\|StartLimitIntervalSec'
[Unit]
StartLimitIntervalSec=60
[Service]
StartLimitIntervalSec=60

# systemctl status vault | grep StartLimitIntervalSec
Sep 20 13:33:14 hostname systemd[1]: /usr/lib/systemd/system/vault.service:29: Unknown lvalue 'StartLimitIntervalSec' in section 'Service'
Sep 20 13:33:33 hostname systemd[1]: /usr/lib/systemd/system/vault.service:29: Unknown lvalue 'StartLimitIntervalSec' in section 'Service'
```

This is also present here: https://learn.hashicorp.com/tutorials/vault/deployment-guide

**To Reproduce**

- Install `vault` from Hashicorp repository

**Expected behavior**

Remove `StartLimitIntervalSec` from service file (and related documentations).

**Environment:**

* Vault 1.8.2
* Systemd 239
* Server Operating System/Architecture: x86_64

**Additional context**
related issues

- #7278
- #12280

**Comment by hsimon-hashicorp** [comment]
This is fixed in the following PR: https://github.com/hashicorp/linux-packaging/pull/89

**Comment by bastelfreak** [comment]
@hsimon-hashicorp the repo seems to be private, any chance to make it public?

**Comment by hsimon-hashicorp** [comment]
@bastelfreak I mostly placed the link here for HashiCorp folks to cross-reference; when the release is packaged for upcoming releases it will be included as part of the build process. Thanks!
