### ISSUE TITLE
Report a bug that mutates a not-used copy of a struct.

### ISSUE THREAD

**Issue by guodongli-google** [hashicorp/vault#12590]
**Describe the bug**

At: https://github.com/hashicorp/vault/blob/main/command/server/config.go#L530

"v" is of type "[]token.Pos" whose elements will be copied by value since "token.Pos" is a struct. Here "p" is a copy that is not used elsewhere, and mutating it doesn't do anything to the original slice "v". As a consequence, this mutation has no meaningful effect, and the file names in "result.UnusedKeys" won't be updated.
```
type UnusedKeyMap map[string][]token.Pos

type Pos struct {
	Filename string // filename, if any
	Offset   int    // offset, starting at 0
	...
}
    
for _, v := range result.UnusedKeys {
	for _, p := range v {
		p.Filename = source
	}
}
```
A fix is to write back the Filename into the slice using the element's address:
```
	for i := range v {
		v[i].Filename = source
	}
}
```

Found by #deepgo.

**Expected behavior**

**Additional context**

**Comment by hghaf099** [comment]
Thanks for filing this issue. The issue is fixed in 1.9.
