### ISSUE TITLE
Switch to Consul's TLS config helper

### ISSUE THREAD

**Issue by slackpad** [hashicorp/vault#1259]
Since we needed this logic in other projects, we extracted Vault's `setupTLSConfig()` function as a helper in the API client - https://github.com/hashicorp/consul/pull/1876. We can switch Vault over to this new one to share the code.

**Comment by jefferai** [comment]
I don't think this is the right way forward. If we want to share code, we should make it a library. But there's no need to have Vault dependent upon this in Consul's API library instead of its own.
