### ISSUE TITLE
Easy Install

### ISSUE THREAD

**Issue by RnbWd** [hashicorp/vault#126]
FYI I just wrote this: https://github.com/rnbwd/vault-bin

It's just a one-line-command to download and link the binary (assuming npm is installed)

`npm install -g vault-bin`

let me know if someone on the team wants to be a collaborator to keep the version up to date :)

**Comment by mitchellh** [comment]
Thanks, we'll defer to you for this. We'd rather maintain official control over binaries in just the way we do for security reasons (controlling checksums and a single source), but we're happy the community does things like this. :)

**Comment by RnbWd** [comment]
It's downloading source from vault's site - but the library unzips the file before I can checksum - although I could check the binary itself... I like this library :)
