### ISSUE TITLE
Allow for Custom Deprovisioning in Mysql Secret Backend

### ISSUE THREAD

**Issue by maguec** [hashicorp/vault#1260]
Version v0.5.1

When provisioning a user with the Mysql we limited the networks in the grant statement:

```
vault write mysql/roles/teama_search_only sql="GRANT SELECT ON SOMEDB.* TO '{{name}}'@'10.%' IDENTIFIED BY '{{password}}';GRANT SELECT ON OTHERDB.* TO '{{name}}'@'192.168.0.0/255.255.254.0' IDENTIFIED BY '{{password}}';"
```

These users are not being removed because the code below only allows for '%' 

https://github.com/hashicorp/vault/blob/47309289ae8f53ff97be17a4ab21b4a5afa317ef/builtin/logical/mysql/secret_creds.go#L47

Would it be possible to also include a revoke_sql setting in this backend?

**Comment by jefferai** [comment]
Hi there,

I'm closing this because it's already on our roadmap (ideally for 0.6, but no promises). If someone wants to submit a PR to implement this ahead of time, we'll be happy to review it!
