### ISSUE TITLE
Oracle database plugin breaks with vault versions above 1.7.2

### ISSUE THREAD

**Issue by sabarisankarj** [hashicorp/vault#12609]
**Describe the bug**
Oracle database plugin breaks with vault versions above 1.7.2

**To Reproduce**
1. vault read database/creds/my-role
2. Internal Error 
Error 500 
1 error occurred: *unable to create database instance: invalid database version: 2 errors occurred: * error verifying checksum: open /etc/vault/plugins/vault-plugin-database-oracle: permission denied * error verifying checksum: open /etc/vault/plugins/vault-plugin-database-oracle: permission denied   

**Expected behavior**
Able to generate dynamic credentials for database, which is happening as expected in Vault 1.7.2. Above highlighted error with Vault 1.7.3, 1.7.4 and 1.8.2

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.7.3 or above
* Vault CLI Version (retrieve with `vault version`): 1.7.3 or above
* Server Operating System/Architecture: Ubuntu 20.04

**Comment by hsimon-hashicorp** [comment]
Hi @sabarisankarj! Are you able to verify the checksum for the plugin? The "error verifying checksum" usually means the plugin didn't register correctly. Also, as an added check, if you try to run the plugin directly, you should receive a message that the plugin can't be run standalone and needs to be called from a binary. Any other message indicates a problem. Thanks!

**Comment by sabarisankarj** [comment]
Hi @hsimon-hashicorp, thanks for the comment. Additional hardening in plugin folder broke the config. I fixed it by sorting the permission issues.
