### ISSUE TITLE
Consider allowing listing of all configured AppIDs and UserIDs

### ISSUE THREAD

**Issue by hobbeswalsh** [hashicorp/vault#1261]
Hi there,

It would be very useful for us to be able to list all UserIDs associated with a given AppID -- and for that matter, list all AppIDs too. Is this currently planned?

Thanks!

**Comment by jefferai** [comment]
This isn't currently planned on our side, no, although I think we'd be happy to work with someone on a PR. I think listing App IDs isn't a problem, but listing User IDs is -- they're raw authentication material, the (ideally) secret part of the equation. We wouldn't want them to be listed for the same reason you don't let people list passwords from a random user in LDAP. Also, they're stored hashed, so getting the plaintext out is hard or impossible anyways.  :-)

What are your specific use-cases around listing User IDs? Maybe there's another way to accomplish it.

**Comment by hobbeswalsh** [comment]
@jefferai You're right about the UserIDs; I wasn't really thinking. But my use-case would be the ability to answer the question "what are the currently active AppIDs and what policies are they associated with" in order to answer the question "should I make a new AppID for this thing?" I know AppIDs are effectively free, but having the ability to see and organize them would be nice.

**Comment by jefferai** [comment]
That sounds totally reasonable. Like I said, nothing against adding support to list AppIDs except time :-)

**Comment by tomalok** [comment]
Giving at least root the ability to also list UserID maps would be useful -- otherwise we'll need to track/manage them elsewhere...  Our UserIDs are generated per instantiated docker container (but are manually added).  There's a low rate of churn in production for persistent containers, but the UserIDs start piling up as shorter-lived containers come-and-go in development and pre-production.

**Comment by jefferai** [comment]
It's not a matter of root vs. someone else... they are stored hashed and cannot be listed in any meaningful way. If you want to be able to delete the hashed entries via the hashed value that's something that can be done but you wouldn't be able to correlate those to the original entries.

**Comment by tomalok** [comment]
Is there (or could there) be any metadata associated with those stored hashes, such that it could be determined when they were last used?

**Comment by jefferai** [comment]
Not currently, no.

**Comment by hobbeswalsh** [comment]
You'd have to grep through audit logs to see when a given UserID was last used, which sounds like the right way to access the data in the first place.

**Comment by hobbeswalsh** [comment]
(assuming the hashed value is listed in the logs)

**Comment by jefferai** [comment]
The SHA1 value is indeed in the audit logs; if you know the plaintext you can find the usage. (This may change to SHA256 in the future, but the principle would remain the same.)

**Comment by jefferai** [comment]
Closing since AppRole implements this, App-ID can't, and App-ID is now deprecated.
