### ISSUE TITLE
Error configuring snapshot-auto (Unsupported Path)

### ISSUE THREAD

**Issue by josephlim75** [hashicorp/vault#12625]
**Describe the bug**
When trying to configure `snapshot-auto` as described from 
https://www.vaultproject.io/api-docs/system/storage/raftautosnapshots, 
I got error `unsupported path`

**To Reproduce**

### Payload.json
```json
{
  "interval": "24h",
  "retain": 7,
  "path_prefix": "raft-daily",
  "storage_type": "local",
  "local_max_space": 10000000
}
```

Have tried changing `path_prefix` to `/opt/vault/snaphosts/` but error still persist.  Confirmed path exists in the same node where vault is running

### Command
```
curl   --header "X-Vault-Token: $VAULT_TOKEN" \
  --request POST \
  --data @payload.json \
  https://vault-0:8200/v1/sys/storage/raft/snapshot-auto/config/daily
```
### Error
```
{"errors":["1 error occurred:\n\t* unsupported path\n\n"]}
```

**Expected behavior**
Snapshot should configure successfully and should expect to see a copy of snapshot daily

**Environment:**
Vault version: **1.8.2**
Platform: Docker with Debian (Buster) image
Host OS:  MacOS

Vault server configuration file(s):

```hcl
disable_cache = true
disable_mlock = true
ui            = true

listener "tcp" {
  address       = "0.0.0.0:8200"
  cluster_addr  = "0.0.0.0:8201"
  tls_disable   = 0
  tls_cert_file = "/opt/letsencrypt/certs/fullchain.cer"
  tls_key_file  = "/opt/letsencrypt/certs/cert.key"
}

storage "raft" {
  node_id      = "vault-0"
  path         = "/opt/vault/raft"

  retry_join {
      leader_api_addr = "https://vault-0:8200"
    }

  retry_join {
      leader_api_addr = "https://vault-1:8200"
    }

  retry_join {
      leader_api_addr = "https://vault-2:8200"
    }
}

cluster_addr  = "https://vault-0:8201"
api_addr      = "https://vault-0:8200"
```

**Comment by hghaf099** [comment]
Thank you for filing this issue, would you please let us know if you are using Vault Enterprise or not? Note that this feature is only available in the Enterprise Vault.

**Comment by josephlim75** [comment]
Oh..Sorry, missed the documentation saying is for Enterprise.  I am actually using opensource.  I am closing the issue now.
