### ISSUE TITLE
obfuscate LDAP bindpass

### ISSUE THREAD

**Issue by makered** [hashicorp/vault#1263]
I recently started experimenting with the LDAP auth backend (thanks for including it!), however one area of concern is that the bindpass value can be returned/displayed in plaintext (e.g. `vault read auth/ldap/config`). 

This is a sensitive secret that should probably not be exposed once entered.

**Comment by jefferai** [comment]
Thanks for the info!

**Comment by shomron** [comment]
Why is this any more or less sensitive than all the other secrets one stores in Vault? They too are returned in plaintext when permissions allow.

**Comment by jefferai** [comment]
In most cases we just add a warning on write that read will display the data in plaintext.
