### ISSUE TITLE
Raft snapshot restoration from UI fails: TypeError: Window.fetch: 'signal' member of RequestInit does not implement interface AbortSignal.

### ISSUE THREAD

**Issue by dekimsey** [hashicorp/vault#12641]
**Describe the bug**
Raft snapshot restoration from GUI fails, but works via cli. This appears to me to be an issue in the UI/Javascript and not in the vault backend.

    TypeError: Window.fetch: 'signal' member of RequestInit does not implement interface AbortSignal.

This was reported in hashicorp/docker-vault but is not a container issue. I have duplicated/paraphrased the contents of that ticket here to get the proper escalation.

**To Reproduce**
1. Create vault cluster
2. Create snapshot
3. Attempt to restore via GUI

**Expected behavior**
Snapshot loads successfully

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    1
Threshold                1
Version                  1.8.2
Storage Type             raft
Cluster Name             vault-cluster-bba87881
Cluster ID               dead-beef
HA Enabled               true
HA Cluster               https://127.0.0.1:8201
HA Mode                  standby
Active Node Address      https://vault.private.example.com:8200
Raft Committed Index     421
Raft Applied Index       421
```
* Vault CLI Version (retrieve with `vault version`):
```
Vault v1.8.2 (aca76f63357041a43b49f3e8c11d67358496959f)
```
* Server Operating System/Architecture:
CentOS 7 x86_64

Vault server configuration file(s):

(This configuration sample is from the associated ticket in hashicorp/docker-vault)

```json
{
"listener": [{
"tcp": {
"address" : "0.0.0.0:8200",
"tls_disable" : 0,
"tls_cert_file":"/vault/config/fullchain.pem",
"tls_key_file":"/vault/config/key.pem"
}
}],
"api_addr": "https://127.0.0.1:8200",
"cluster_addr": "https://127.0.0.1:8201",
"storage": {
  "raft": {
    "path": "/vault/raft",
    "node_id": "raft_node_1"
  }
},
"max_lease_ttl": "10h",
"default_lease_ttl": "10h",
"ui":true
}
```

**Additional context**

- https://github.com/hashicorp/docker-vault/issues/235

**Comment by hsimon-hashicorp** [comment]
Hello! Thanks for the report. We are also tracking a very similar issue internally ([VAULT-3181](https://hashicorp.atlassian.net/browse/VAULT-3181) for fellow HashiCorp folks). I'll update the Jira ticket with this information, so as to make sure folks know its relative impact.

**Comment by nightspotlight** [comment]
probably fixed in 1.9.1 with #13107, will test soon

**Comment by nightspotlight** [comment]
yes, does not reproduce in 1.9.1

**Comment by hsimon-hashicorp** [comment]
Thank you @nightspotlight! Closing this now.
