### ISSUE TITLE
Policy doesn't work, always permission denied

### ISSUE THREAD

**Issue by speller** [hashicorp/vault#12665]
I can't make policies working, it always denies access. 

```
$ vault policy write jdm-yahoo-api - <<EOF
path "kv/jdm/yahoo/account" {
  capabilities = [ "read" ]
}
EOF

$ vault kv get kv/jdm/yahoo/account
====== Metadata ======
Key              Value
---              -----
created_time     2021-09-29T02:46:24.309419404Z
deletion_time    n/a
destroyed        false
version          1

====== Data ======
Key         Value
---         -----
login       ***
password    ***

$ export TMP_TOKEN=$(vault token create -policy="jdm-yahoo-api" -field=token)
$ VAULT_TOKEN=$TMP_TOKEN vault kv get kv/jdm/yahoo/account
Error reading kv/data/jdm/yahoo/account: Error making API request.

URL: GET https://***.aws.hashicorp.cloud:8200/v1/kv/data/jdm/yahoo/account
Code: 403. Errors:

* 1 error occurred:
        * permission denied
```

What's wrong? I've set the exact key name to permit the read access to it. Why it can not be accessed?

**Comment by mbillow** [comment]
Vault ACLs use the API path, so if you look at the [KVv2 docs](https://www.vaultproject.io/api/secret/kv/kv-v2#read-secret-version), you will see the actual request `vault kv get` is making is actually to `{mount_path}/data/{kv_path}`. The ACL in your example should be for `kv/data/jdm/yahoo/account`.

**Comment by hghaf099** [comment]
Would you please specify which Vault version are you using? and would you please post all the steps to reproduce the issue?
