### ISSUE TITLE
FEAT: Add username templating into the AWS Secret Engine's IAM users

### ISSUE THREAD

**Issue by iniinikoski** [hashicorp/vault#12669]
**Is your feature request related to a problem? Please describe.**

Not sure if this should belong into this repository - but could not find a Vault AWS plugin repository...

When logged into Vault using an OIDC and provisioning an AWS IAM user, the default user becomes quite long (gets truncated really badly) - and Vault's client part also throws an error "[the calling token display name/IAM policy name were truncated to fit into IAM username length limits]". This causes issues with any clients which use the Vault code library (e.g. Teller - https://github.com/SpectralOps/teller)

AWS Secrets Engine is not found in here: https://learn.hashicorp.com/tutorials/vault/username-templating?in=vault/secrets-management#solution - unfortunately.

Also, looking at the API documentation, this seems to be the case: https://www.vaultproject.io/api/secret/aws

**Describe the solution you'd like**

The AWS Secrets Engine should also support username templating for AWS IAM users - like with usernames with other supported Secrets Engines.

**Describe alternatives you've considered**
No alternatives / workarounds here... Or maybe to make the error quiet?

**Comment by iniinikoski** [comment]
Ha, looks like this is also arriving in 1.9 release of Vault: https://github.com/hashicorp/vault/pull/12066 - awesome!

**Comment by pjastrzabek** [comment]
I am trying to configure this with terraform
`
resource "vault_aws_secret_backend" "aws" {
  region = var.region
  default_lease_ttl_seconds = 11 * 60 * 60 # = 12h
  max_lease_ttl_seconds     = 11 * 60 * 60 # = 12h
  path = "somepath/aws"
  username_template = "{{ printf '%s' (unix_time) | truncate 15 }}"
}
`
but as soon as I set any user_template when I try to get Iam User I am getting error:
**the username generated by the template exceeds the IAM username length limits of 64 chars**

It does not matter what template I will set.
I also tried template from the doc (which should be the default anyway)

My backend vault is 1.9.2 (it's a hasihcorp cloud vault - maybe that is important)

Could someone confirm that it should be working?

**Comment by hsimon-hashicorp** [comment]
Closing as per @iniinikoski - thanks!
