### ISSUE TITLE
Example for `bound_cidrs` in documentation, please

### ISSUE THREAD

**Issue by con-f-use** [hashicorp/vault#12678]
I have yet to see an example value of the [`secred_id_bound_cidrs`](https://www.vaultproject.io/api-docs/auth/approle#secret_id_bound_cidrs) or `token_bound_cidrs` parameter anywhere in the Vault documentation.

I assume it would be something like:
```console
$ vault  write auth/approle/role/my-role secred_id_bound_cidrs=10.20.30.0/24,10.20.31.31/32
Success! Data written to: auth/approle/role/my-role
```

But without an example, who knows? :wink:

**Comment by hghaf099** [comment]
Thank you very much for submitting this issue. Please follow the following links to find examples and workflows for those parameters. I hope you find them helpful. I am going to close this issue for now, but please feel free to open a new issue for further requests. 
https://learn.hashicorp.com/tutorials/vault/approle-best-practices?in=vault/auth-methods
https://learn.hashicorp.com/tutorials/vault/approle?in=vault/auth-methods
