### ISSUE TITLE
"What is Vault?" description that Vault is a tool is very simplistic

### ISSUE THREAD

**Issue by softveda** [hashicorp/vault#12684]
**Describe the bug**
https://www.vaultproject.io/docs/what-is-vault
The "What is Vault?" content is too simplistic. It states
```Vault is a tool for securely accessing secrets.```

A tool is usually perceived as just a CLI executable, whereas Vault is also a networked and distributed/replicated server app which is more than a 'tool'.

**Expected behavior**
A better description of "What is Vault?"

**Additional context**
I am a Senior CSA at HashiCorp.

**Comment by hghaf099** [comment]
Thank you for raising this issue. We have filed an internal ticket for this which can be found https://app.asana.com/0/563192436488770/1201106002588624/f
I am going to close this ticket for now.
