### ISSUE TITLE
Create a module for installing vault in kubernetes using helm

### ISSUE THREAD

**Issue by val3r10** [hashicorp/vault#12690]
**Is your feature request related to a problem? Please describe.**
At the moment the recommended way to install vault in Kubernetes is to use Helm. However when this is done through terraform the code looks like this:

```
resource "helm_release" "Vault" {
  name        = "vault"
  chart       = "vault"
  repository  = "https://helm.releases.hashicorp.com"
  namespace   = "vault"
  
    values = [
    "${file("vaultinstall.yaml")}"
  ]
}
```

Due to the high number of settings using a yaml file is necessary as is not possible or at least is not documented how to pass the configuration using this format:

```
resource "helm_release" "Vault" {
  name        = "vault"
  chart       = "vault"
  repository  = "https://helm.releases.hashicorp.com"
  namespace   = "vault"

  set {
    name  = "settings"
    value = "true"
      }
  }
```

For example for this kind of settings that we can find in the yaml

```
config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "consul" {
        path = "vault"
        address = "HOST_IP:8500"
      }

```
Or even something like this:
```
annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet:

```

What happen is that also using the yaml file the experience with Terraform is not good as we cannot refer to other terraform resources or pass terraform variables. 

**Describe the solution you'd like**
Will be great to have all the settings documented in Terraform format or a Terraform module.

**Describe alternatives you've considered**
We are still deploying with the yaml but is not ideal

**Comment by tvoran** [comment]
Hi @val3r10, thanks for bringing this up! I agree we should add some examples to our documentation to show how to configure the vault-helm chart using terraform.

To your specific questions, setting a value with a multi-line string can be done like this:

```hcl
  set {
    name = "server.ha.config"
    value = <<EOT
ui = true

listener "tcp" {
  tls_disable = 1
  address = "[::]:8300"
  cluster_address = "[::]:8301"
}
storage "consul" {
  path = "vault"
  address = "HOST_IP:8500"
}

service_registration "kubernetes" {}"
EOT
  }
```

And since most of our `annotations` values in the chart accept yaml-formatted multi-line strings, the `yamlencode` function can help. For example:

```hcl
  set {
    name = "server.ingress.annotations"
    value = yamlencode({
      "service.beta.kubernetes.io/azure-load-balancer-internal": "true"
      "service.beta.kubernetes.io/azure-load-balancer-internal-subnet": "0.0.0.0/0"
    })
    type = "auto"
  }
```

**Comment by tvoran** [comment]
And to set those annotations as a yaml map, something like this will work:

```hcl
  set {
    name = "server.ingress.annotations.service\\.beta\\.kubernetes\\.io/azure-load-balancer-internal"
    value = "true"
    type = "string"
  }

  set {
    name = "server.ingress.annotations.service\\.beta\\.kubernetes\\.io/azure-load-balancer-internal-subnet"
    value = "0.0.0.0/0"
  }
