### ISSUE TITLE
Option to read out current mount-tune parameters for auth backends

### ISSUE THREAD

**Issue by sigmunau** [hashicorp/vault#1269]
Currently the `vault mounts` command lists default and max ttl for secret backends, however these can also be set for auth backends, but there is no way to find what the current values are for auth backends

**Comment by jefferai** [comment]
This should currently be doable via the API directly, but agreed that it'd be nice to have CLI support.

**Comment by sigmunau** [comment]
I have a very distinct feeling that the mount-tune parameters I did set for ldap backend has been reset somehow. I'm trying to confirm this, but I can't find the api to read mount-tune parameters for auth backends. The `/sys/auth` end point does not output this information

**Comment by jefferai** [comment]
You can find it under `/v1/sys/mounts/<path>/tune`, so `/v1/sys/mounts/auth/ldap/tune` most likely.

**Comment by sigmunau** [comment]
Auth backends are not listed in the output of `/v1/sys/mounts`, so it seems be strange for it to be located there. Also, this endpoint is not documented in the api documentation. But it did give the information required

**Comment by jefferai** [comment]
Agreed, it's a bit strange. But it is documented: https://www.vaultproject.io/docs/http/sys-mounts.html

**Comment by sigmunau** [comment]
Oh, indeed. It's kind of hard to tell where the docs for `/sys/mounts` end and the docs for `/sys/mounts/<mountpoint>/tune`  begins. I thought they were all for the same entry. Also I don't see it mentioned anywere that auth backends are actually mounted under `auth/<path>`.

**Comment by jefferai** [comment]
I'm going to put this on the 0.6 milestone to try to get the auth tune stuff under sys/auth, but it's not super high priority right now so may slip.
