### ISSUE TITLE
When is the binary release for v0.1.1 coming?

### ISSUE THREAD

**Issue by nabeelomer** [hashicorp/vault#127]
When is the binary release for v0.1.1 coming?

**Comment by mitchellh** [comment]
Hopefully later today :)

**Comment by nabeelomer** [comment]
@mitchellh Its been 9 hours and still the binary's on the website are v0.1.0.

**Comment by knuckolls** [comment]
You can build from master if you need binaries asap.

**Comment by nabeelomer** [comment]
@knuckolls I don't have no experience with the language. Moreover I use visual studio to build on windows, so I don't have make and other utilities.

**Comment by knuckolls** [comment]
Guaranteed if you're interested in this project at the nascent stages you'll want to figure out a way to build a binary, even if it's from within a vagrant box.

**Comment by mitchellh** [comment]
@nabeelomer I think you're being cached (we cache the website aggressively, browser-side), 0.1.1 is out! :)

**Comment by nabeelomer** [comment]
@mitchellh Yes, thanks, it turns out that my phone was being cached, on my computer it shows v0.1.1.
