### ISSUE TITLE
Support listing ldap group to policy mappings

### ISSUE THREAD

**Issue by sigmunau** [hashicorp/vault#1270]
I would very much like to have to be able to periodically review which ldap groups gives which policies. Currently this requires you to know up front which groups are configured since the `auth/ldap/groups` path does not support listing. These groups does not even need to exist in ldap, so iterating over all ldap groups does not work either. 

Worst case scenario, this could allow a illoyal vault admin to create a backdoor that other vault admins can not find and plug. More likely scenario is that some mapping is created and later forgotten leaving certain users with more accesses than they were supposed to

**Comment by jefferai** [comment]
I've slotted it in for 0.6 currently, and we'll see if we can get to it for that milestone. It's pretty simple to do, so PRs are welcome if you're interested :-)
