### ISSUE TITLE
vault read auth/config/github 500 error

### ISSUE THREAD

**Issue by rileytg** [hashicorp/vault#1272]
I'm not sure if there's a reason for this or I'm experiencing a bug...

```
$ vault read auth/github/config 
Error reading auth/github/config: Error making API request.

URL: GET http://127.0.0.1:8200/v1/auth/github/config
Code: 500. Errors:

* unsupported operation
```

**Comment by jefferai** [comment]
Read is not a supported operation on that endpoint!

**Comment by rileytg** [comment]
got that from the error. why? is it a security concern? if so why not be controlled like in a policy?

**Comment by jefferai** [comment]
It's not implemented.

**Comment by rileytg** [comment]
Could I submit a pull for this? or is it purposely not implemented?

**Comment by jefferai** [comment]
AFAIK there is nothing security sensitive in the configuration, so no particular reason it's purposefully not implemented. PR welcome!
