### ISSUE TITLE
Support issuing AWS Session Tokens via GetSessionToken

### ISSUE THREAD

**Issue by grahamc** [hashicorp/vault#12734]
**Is your feature request related to a problem? Please describe.**

Sometimes people will give you an AWS access key and secret and not
be interested in setting up a better approach for key exchange.

**Describe the solution you'd like**

In cases like this, options are limited for distributing access to
the key material. However, AWS's STS GetSessionToken can be used
to general ephemeral credentials "underneath" that token. This
at least limits the spread of that root key, and the duration of
its users' access.

I'd like to use GetSessionToken + Vault to distribute key material
in this way.

**Describe alternatives you've considered**

- Lobbying collaborators and clients to exchange authority better (not always successful.)
- Never delegate work that involves pre-shared keys
- Delegate work that involves pre-shared keys and hope the employee doesn't make a mistake with the key material

**Explain any additional use-cases**
n/a

**Additional context**
n/a

**Comment by hsimon-hashicorp** [comment]
Closing this issue as per #12735 - please do feel free to re-engage if this problem is still existent for you; we truly value your contributions and effort. Thanks!

**Comment by grahamc** [comment]
This problem persists. The S3 credentials are provided by an external organization, who is not able or willing to implement better key sharing.

**Comment by hsimon-hashicorp** [comment]
Re-opening!
