### ISSUE TITLE
Make TOTP MFA an Open Source feature for supported auth methods

### ISSUE THREAD

**Issue by con-f-use** [hashicorp/vault#12753]
Rationale: At least one open, widespread and widely supported OTP standard should be officially supported for Vault open-source users. I know, this was probably discussed a lot when TOTP was introduced as an enterprise feature and probably still comes up every so often. I'm also very aware that Hashicorp is and should be a for-profit organization. Thankfully, Hashicorp is already very FOSS-leaning. A strong and healthy business behind Vault keeps it growing and financed, which is good for open-source users, too. However, in a world of constant security breaches and increasing compute power to break passwords, I think the benefit of protecting the FOSS community's sensitive data outweighs the revenue caused by TOPT as an enterprise feature. Additionally, MFA has become more ubiquitous every moment since TOTP was introduced as an enterprise feature in Vault and, as such, is less of an enterprise-only technology now.

So, I kindly ask you reconsider making TOPT a feature in the open-souce version Vault.

**Comment by hghaf099** [comment]
@con-f-use  Thank you for your feature request. We rolled out Vault version 1.10.0 recently, and we have included support for [Login MFA](https://www.vaultproject.io/docs/auth/login-mfa) which supports TOTP, Duo, Okta, and PingID. I am going to close this feature request. Thank you for your keen interest in Vault.
