### ISSUE TITLE
Static role creation in MongoDB fails! 

### ISSUE THREAD

**Issue by ghost** [hashicorp/vault#12785]
I created a user named “user1” inside a “test” db with “userAdmin” role.

I established a connection to “test” db from vault using the connection string "mongodb://{username}:{password}@0.0.0.0:27017/test"

In place of username, I gave “user1” and corresponding password and verified the connection.

Then I tried to create a static role and rotate the “user1”'s password, but when I gave the “user1” name in place of username field, vault is saying "failed to find user1@admin"
![Screenshot from 2021-10-09 19-56-01](https://user-images.githubusercontent.com/73845897/136666645-379fec32-a8db-441b-b3fe-2a8310153f51.png)

My question is why vault is trying to find the “user1” inside “admin” db instead of “test” db? Kindly suggest your ideas.

Vault version: 1.8.2 in dev mode, MongoDB version: 5.0.2

**Comment by ajaysg94** [comment]
@pcman312

**Comment by hsimon-hashicorp** [comment]
Hi @ajaysg94 - does this scenario work with the API? We're trying to reproduce it, but we're having some troubles doing so, if you can provide more information that would be great. Thanks! :)

**Comment by ajaysg94** [comment]
@hsimon-hashicorp I have tried the same flow with API too. It gives the same error.
