### ISSUE TITLE
Support age for encrypting the shamir shares and root token on init

### ISSUE THREAD

**Issue by googol** [hashicorp/vault#12786]
**Is your feature request related to a problem? Please describe.**
Currently vault supports GPG for encrypting the shamir shares and root token when initializing. This is of course a good thing as it protects these values from unwanted users. However GPG is a complicated and old system, and using it safely is not trivial; explaining GPG keys and operations to new users is difficult, and because of its age and backwards compatibility it's possible that weak ciphers get used (with GPG in general, I don't know about the implementation or configuration within vault).

**Describe the solution you'd like**
Age (https://age-encryption.org/) is a simple program for encrypting files with asymmetric keys. It uses modern crypto only, and the keys are nice and short with nothing special one needs to understand about them. It is provided as a cli and a go library. The maintainers of age released a stable 1.0.0 version in September 2021.

I would like to see age being supported as an alternative to the GPG encryption options for shamir shares and root tokens.

I see no reason to remove GPG support, but having a simpler, possibly more secure tool as an alternative seems like a good thing to me

**Comment by ixe013** [comment]
Was there any cryptanalisys done on "age" ? Couldn't find any...

**Comment by ncabatoff** [comment]
Not very current, but there's this: https://neilmadden.blog/2019/12/30/a-few-comments-on-age/

**Comment by hsimon-hashicorp** [comment]
Hello! Vault has no plans to implement this in the foreseeable future, however, we're keeping an eye on Age, user demand, and additional cryptanalysis to be conducted. Thanks for understanding.
