### ISSUE TITLE
LDAP, Error writing data

### ISSUE THREAD

**Issue by 0x9090** [hashicorp/vault#1279]
When trying to configure Vault for LDAPS auth backend
```
vault write auth/ldap/config url="ldaps://###:636" userattr=### userdn="ou=###,dc=###,dc=###" groupdn="dc=###,dc=###" upndomain="###" insecure_tls=false starttls=false
```
it throws the error,
```
Error writing data to auth/ldap/config: Put https://###:8200/v1/auth/ldap/config: EOF
```
I am on Vault 0.5.2 running on a fully patched Debian Jessie box

**Comment by jefferai** [comment]
This can happen with some error conditions when configuring or opening LDAP connections -- instead of a useful error message being returned it panics. The good news is that the fix for this is already in `master`!
