### ISSUE TITLE
Auto-generated OpenAPI is *incorrect* for `/aws/creds`

### ISSUE THREAD

**Issue by maxb** [hashicorp/vault#12794]
**Describe the bug**

The auto-generated OpenAPI (from `/sys/internal/specs/openapi`) generates **incorrect** documentation for the AWS secrets engine API.

**To Reproduce**

1. Mount an instance of the AWS secrets engine
2. Visit the built-in Vault Swagger UI (at `/ui/vault/api-explorer`)
3. Find the endpoint `/aws/creds`
4. Compare with the actual API docs for the AWS secrets engine
5. Realise that actually there is no such API endpoint `/aws/creds`, only `/aws/creds/{name}`

**Expected behavior**

Auto-generated OpenAPI should accurately reflect the actual APIs in Vault.

**Additional context**

It would seem highly likely that the bug is that the Vault OpenAPI generator doesn't correctly understand what to do with regexs employing alternatives:

```
		Pattern: "(creds|sts)/" + framework.GenericNameWithAtRegex("name"),
```
https://github.com/hashicorp/vault/blob/818502bc835e10da4d61ec89ae3ce5f323077a7c/builtin/logical/aws/path_user.go#L20

**Comment by averche** [comment]
Resolved in #13487
