### ISSUE TITLE
S3 backend has troubles with regions other us-east-1

### ISSUE THREAD

**Issue by SunSparc** [hashicorp/vault#1281]
_Note: This was tested against version 5.2 (which is 15 days old as of this posting)._

I setup Vault to use S3 as the backend. I created two buckets. One bucket was in the us-east-1 (aka "US Standard") region and the other was in us-east-2 (Oregon). I setup IAM permissions for a user. I setup my vault config files on two different machines.

    backend "s3" {
      bucket = "myvault-east" // and bucket = "myvault-west"
      access_key = "*********************"
      secret_key = "****************************************"
    }
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }

Then I launched the Vault server: `sudo vault server -config=vault.hcl`.

On the server using the S3 bucket in the East, everything was fine. I initialized the server and the files showed up in the bucket without problem.

On the server using the S3 bucket in the West, I got this message:

    Error initializing backend of type s3: unable to access bucket 'myyvault-west': :
        status code: 403, request id: 12345678901234567

I check the permissions over and over. They were fine.

Then I installed `s3cmd` on the machine with the West config and tried to access the same bucket. This is what I saw:

    $ s3cmd ls s3://myyvault-west
    WARNING: Redirected to: myvault-west.s3-us-west-2.amazonaws.com

Apparently since East is the "Standard" region for S3, there are no redirects. But the West regions do. Perhaps the S3 backend for Vault is not handling these redirects properly.

Just for kicks, I setup a bucket in us-west-1 (Northern California) as well and got the same problem.

**Comment by jefferai** [comment]
Hi @SunSparc ,

We're using the official AWS Go SDK and as far as I can tell that error is coming straight from the SDK, so I'm not sure there's much we can do (other than bump the version if this is something that has been fixed since the last time we bumped). The S3 backend is community-supported and our internal team is pretty swamped right now so if you're interested in digging into the problem yourself that'd be the fastest way to resolution.

P.S. Like your GitHub handle!

**Comment by SunSparc** [comment]
Thank you for the response. I will evaluate my possibilities.

**Comment by SunSparc** [comment]
So I went back into `vault/physical/s3.go` and changed the `region` assignment on line 62 to be `us-west-2` instead of `us-east-1`. Then I rebuilt, launched Vault, and initialized it. No errors. Backend files showed up in the S3 bucket without issue.

This made me wonder if I was just holding it wrong. :(

I consulted [the documentation](https://www.vaultproject.io/docs/config/index.html#region) again and noticed the `region` parameter. I had overlooked it, probably because it was marked as "optional". I then went back to my `hcl` file and added the region that my bucket is in. It worked.

So it turns out that I was indeed holding it wrong. To be fair, I think a reword in the documentation might be in order. True, the `region` parameter is optional, if I am just planning to use the default ("US Standard", aka "us-east-1") region. Otherwise, the parameter is most certainly required.

Thank you for your time. I hope this can help someone in the future.

**Comment by jefferai** [comment]
Oh, neat! That's a good idea about the doc fix; I'll do that now.

**Comment by jefferai** [comment]
Hm. The docs do say "will default to `us-east-1` if not specified. However, that was in "quotes" not `backticks` so it won't catch the eye as much...

**Comment by SunSparc** [comment]
Yes, I agree, the docs are clear for me now. At least in hindsight. I take full credit for the improper use of the tool.

Perhaps something like this could be helpful:

`region (optional, conditionally) - The AWS region. It can be sourced from the AWS_DEFAULT_REGION environment variable and will default to "us-east-1" if not specified. If you using a region other than the "US Standard" default region, this parameter is required.`
