### ISSUE TITLE
Panic with github.com/denisenkom/go-mssqldb.passthroughConn.SetWriteDeadline(...)

### ISSUE THREAD

**Issue by mrcooperpcf** [hashicorp/vault#12830]
**Describe the bug**
After upgrading to 1.8 from 1.7 we frequently get error “panic not implemented” (see details below). We also have frequent restarts that appear related to this panic. 31 restarts in 4 days. After some searching I learned the denisenkom package is not compatible with go 1.16. Read here Not implemented panic in go 1.16 · Issue #639 · denisenkom/go-mssqldb · GitHub. When will Vault fix this issue? I’m considering down revving to try to get back to a stable platform. We primarily use Vault for dynamic DB credentials.

github.com/denisenkom/go-mssqldb.passthroughConn.SetWriteDeadline(...)
/gopath/pkg/mod/github.com/denisenkom/go-mssqldb@v0.0.0-20200428022330-06a60b6afbbc/net.go:167

**To Reproduce**
1. Request a dynamic credential vault read <path>/creds/<role>
3. See error

**Expected behavior**
To get a credential and to not get a panic error.

**Environment:**
/ $ vault status
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    5
Threshold                3
Version                  1.8.3
Storage Type             raft
Cluster Name             vault-cluster-83fa7ee4
Cluster ID               c31e1e9a-6f03-159b-08c7-69528604793c
HA Enabled               true
HA Cluster               https://vault-3.vault-internal:8201
HA Mode                  active
Active Since             2021-10-14T11:16:42.273387483Z
Raft Committed Index     2164966
Raft Applied Index       2164966
* Vault CLI Version (retrieve with `vault version`): Vault v1.8.3 (73e85c3c21dfd1e835ded0053f08e3bd73a24ad6)
* linux. Docker image https://hub.docker.com/_/vault vault:1.8.3

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```
disable_mlock = true
ui = true

listener "tcp" {
tls_disable = 1
address = "0.0.0.0:8200"
cluster_address = "0.0.0.0:8201"
}

storage "raft" {
path = "/vault/data"
retry_join {
leader_api_addr = "http://vault-0.vault-internal:8200"
}
retry_join {
leader_api_addr = "http://vault-1.vault-internal:8200"
}
retry_join {
leader_api_addr = "http://vault-2.vault-internal:8200"
}
retry_join {
leader_api_addr = "http://vault-3.vault-internal:8200"
}
retry_join {
leader_api_addr = "http://vault-4.vault-internal:8200"
}
}

service_registration "kubernetes" {
namespace = "vault"
}

seal "azurekeyvault" {
client_id = "redacted"
client_secret = "redacted"
tenant_id = "redacted"
vault_name = "redacted"
key_name = "redacted"
}

autopilot {
cleanup_dead_servers = "true"
last_contact_threshold = "200ms"
last_contact_failure_threshold = "10m"
max_trailing_logs = 250000
min_quorum = 3
server_stabilization_time = "10s"
}

**Comment by hsimon-hashicorp** [comment]
Thanks for that, @calvn! Hugely appreciated.

**Comment by mrcooperpcf** [comment]
When will this get deployed to GA? Is it going to be part of release 1.8.5?

**Comment by calvn** [comment]
@mrcooperpcf sorry for the late reply, but yes it should be on 1.9.0, 1.8.5, and 1.7.6!
