### ISSUE TITLE
ssh: DefaultPublicKeyInstallScript ignores errors from grep

### ISSUE THREAD

**Issue by mmickan** [hashicorp/vault#1285]
In the default public key install script, a temporary file is created with:

```
grep -vFf "$PUBLIC_KEY_FILE" "$AUTH_KEYS_FILE" > temp_$PUBLIC_KEY_FILE || true
```

Errors, such as not having read permission to read another user's authorized keys file, are ignored, then the temporary file is used to replace that authorized_keys file.  This effectively deletes _all_ existing keys from the target authorized_keys file.  At the very least that grep requires sudo to ensure it can read the authorized_keys file, but the error code should probably be checked too.  I'm not sure of the correct action if there is an error from the grep though - if the next line in the script isn't actioned, there's potential for a key to not be uninstalled... perhaps removing all keys from the file _is_ the right thing to do from a "fail secure" standpoint?

Note that it's fairly common to have the .ssh directory mode 0700 - that's the permissions set by ssh-keygen for example (at least on Ubuntu 14.04 where I've been testing).

**Comment by jefferai** [comment]
Hi @mmickan ,

You're right about both the problem, and the difficulty of figuring out what to do if things go wrong. We tend to favor "fail secure" in Vault, but if you come up with another scenario that seems better we'll be happy to hear it!
