### ISSUE TITLE
Unseal vault with multiples keys via HTTP request

### ISSUE THREAD

**Issue by will2294** [hashicorp/vault#1287]
Hello, i'm using Postman to try to unseal a vault with consul as a backend, and i'm facing the following issue:
i have a vault with 5 Key shares and 3 Key Treshold, if i make the http request 3 times with 3 different unseal keys i get to open the vault, but the fact is that i'm trying to unseal it in just one HTTP request but i'm not able to find the mistake, this is what i get when i try to make the request, passing the 3 keys as a json array of keys
![3 keys vault](https://cloud.githubusercontent.com/assets/9334322/14262519/422fc9c2-fab6-11e5-98ba-121106843b76.png)

Thanks for helping me

**Comment by vishalnayak** [comment]
@will2294 By design, the unseal operation is meant to take only one key at a time.
