### ISSUE TITLE
Cassandra backend: error=gocql: no hosts available in the pool

### ISSUE THREAD

**Issue by qk4l** [hashicorp/vault#12878]
**Describe the bug**
Vault do not restore connection with Cassandra nodes after there restart.
Then last of Cassandra node in cluster would restart Vault starts return 500 error
```
error="gocql: no hosts available in the pool
```

**To Reproduce**
1.Configure Vault to use Cassandra backend
2. Subsequence stop/start each Cassandra node in cluster based cluster availability
3. After last node stop Vault failed

**Expected behavior**
Vault should return Cassandra nodes to pool after there restore

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.8.4

Vault server configuration file(s):

```hcl
storage "cassandra" {
   hosts            = "1.cdb.vault.example.com,2.cdb.vault.example.com,3.cdb.vault.example.com"
   consistency      = "QUORUM"
   protocol_version = "2"
   keyspace = "vault"
   username = "admin"
   password = "PASSWORD"
   connection_timeout = "10"
   simple_retry_policy_retries = "3"
}
```

**Additional context**
It's a bug in gocql/gocql#915

**Comment by voltbit** [comment]
Hi @hsimon-hashicorp would it be possible for the proposed fix to make it into the next release? We would benefit from it as we have observed the same behaviour.
