### ISSUE TITLE
How do you regenerate the unseal keys?

### ISSUE THREAD

**Issue by fire** [hashicorp/vault#129]
There doesn't seem to be a way to make a new seal. For example if you had the seal keys lost, but have enough for an unseal.

**Comment by mitchellh** [comment]
Do you mean if you lose the root token? I'm unsure of the terminology you're using. Please clarify, thanks!

**Comment by fire** [comment]
Assume you have 3 of the 5 keys for the seal, but you've lost the two other ones. Is it possible to rekey vault?

**Comment by mitchellh** [comment]
Ah, the internals were designed to allow this to be possible but we haven't exposed it yet. Tagged

**Comment by armon** [comment]
Fixed by #277

**Comment by ShubhamDX** [comment]
Can we regenerate the unseal keys(i.e. master key) once we have lost the threshold number of shares?

**Comment by jefferai** [comment]
@ShubhamDX Sorry, but it cannot be done.

**Comment by ShubhamDX** [comment]
Is there any TTL for the unseal keys also as I have faced a problem in which the keys were unable to unseal and as a result my whole data was lost?

**Comment by jefferai** [comment]
@ShubhamDX No, there is no TTL. However, if Vault has been rekeyed, old keys will no longer work.

**Comment by ShubhamDX** [comment]
What are the possible situations in which unseal couldn't happen(if any)?

**Comment by jefferai** [comment]
Assuming no other errors were seen in your Vault logs, incorrect keys are the only reason that the unseal would not work.

Note that we have seen situations where people copying and pasting keys have been unaware that they have been introducing whitespace in the front or back of the key, causing failures as a result.

**Comment by brettcave** [comment]
A bit of an afterthought - would it not make sense to trim unseal keys - assuming that generated unseal keys would never start or end with one, and the risk of increasing this attack vector is minimal. It would reduce unseal resets by bad copy/paste....

**Comment by jefferai** [comment]
@brettcave In recent versions of Vault (> 0.3 or so) this is already done!

**Comment by brettcave** [comment]
@jefferai great, didn't realise it :+1:

**Comment by vaibhavbhanawat01** [comment]
I forget to note the Root Token and Unseal Key. Is there is any way to retrieve the Both Keys

**Comment by hushanxue** [comment]
@vaibhavbhanawat01  if you forget to note the Root Token and Unseal Key, how to solve it?
