### ISSUE TITLE
PKI: can't create cert with CA usage to use outside Vault (Certificate Sign, CRL Sign)

### ISSUE THREAD

**Issue by sirmax123** [hashicorp/vault#12917]
**What I need**
I'd like to use Vault PKI to issue one more (intermediate)cert, used to sign other certs OUTSIDE the Vault. (use with k8s, I guess it is needed to create tokens, etc)

I have not found way to generate cert with extentions like:
```
 X509v3 Key Usage: critical
    Certificate Sign, CRL Sign
 X509v3 Basic Constraints: critical
CA:TRUE
```

**To Reproduce**
* Configure PKI
* Create Role 
```
vault write \
    pki_intermediate_ca/roles/k8s-home-CA-crt \
    country="Ukraine" \
    locality="Kharkov" \
    street_address="some street"\
    postal_code="61000" \
    organization="some org" \
    ou="IT" \
    max_ttl="87600h" \
    key_bits="2048" \
    key_type="rsa" \
    key_usage="KeyUsageCertSign,KeyUsageCRLSign" \
    allow_any_name=true \
    client_flag=false \
    server_flag=false \
    require_cn=false
```
Issue crt:
```
domain="cluster.k8s.home"

vault \
    write \
    -format=json \
    pki_intermediate_ca/issue/k8s-home-CA-crt \
    ttl="43800h" > ${domain}.crt.json

cat \
    ${domain}.crt.json \
    | jq -r '.data.private_key' > /etc/k8s/certs/ca/${domain}.key

cat \
    ${domain}.crt.json \
    | jq -r '.data.certificate' > /etc/k8s/certs/ca/${domain}.pem
    
```
**Actual behavior**
```
openssl x509 -noout -text -in cluster.k8s.home.pem
```
...
```
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                9E:8E:A5:2C:15:36:F8:35:FB:CA:23:E7:2C:59:C7:F1:A6:B1:5F:9C
            X509v3 Authority Key Identifier:
                keyid:57:CC:17:CF:CF:21:94:71:42:B8:AB:06:7C:FD:FC:45:6D:F9:6A:4F

            Authority Information Access:
                CA Issuers - URI:http://vault.home:8200/v1/pki_intermediate_ca/ca

            X509v3 CRL Distribution Points:

                Full Name:
                  URI:http://vault.home:8200/v1/pki_intermediate_ca/crl
```
**Expected behavior**
```
        X509v3 extensions:
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
```
**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.7.3
Storage Type    consul
Cluster Name    vault-cluster-ca9225e6
Cluster ID      2728d008-d6a6-7bd0-727b-159f7cc26376
HA Enabled      true
HA Cluster      https://192.168.1.223:8201
HA Mode         active
Active Since    2021-09-06T15:04:10.240959572Z
```
* Vault CLI Version (retrieve with `vault version`):
```
Vault v1.8.4 (925bc650ad1d997e84fbb832f302a6bfe0105bbb)
```

* Server Operating System/Architecture:
```
uname  -a
Linux pi-node-1.home 5.10.63-v8+ #1459 SMP PREEMPT Wed Oct 6 16:42:49 BST 2021 aarch64 GNU/Linux
```

**Comment by ixe013** [comment]
Shouldn't you set [`basic_constraints_valid_for_non_ca`](https://www.vaultproject.io/api-docs/secret/pki#basic_constraints_valid_for_non_ca)?

**Comment by cipherboy** [comment]
@ixe013 I don't believe so. From my read of [the code](https://github.com/hashicorp/vault/blob/main/sdk/helper/certutil/helpers.go#L665-L671) all that does is set `IsCA = false` which isn't what @sirmax123 is attempting to achieve. In particular, in order to issue a valid intermediate certificate, `IsCA` needs to be set to true.

The bigger problem, IMO, is that the [API doesn't allow setting `IsCA` to true](https://github.com/hashicorp/vault/blob/87c355e2bb34018b03e886f2e9155a6b3aba69fb/sdk/helper/certutil/helpers.go#L665-L671), which would trigger the [KUs requested](https://github.com/hashicorp/vault/blob/87c355e2bb34018b03e886f2e9155a6b3aba69fb/sdk/helper/certutil/types.go#L725-L729).

**Comment by cipherboy** [comment]
@sirmax123 a workaround might be to create an intermediate CA managed by Vault (see e.g., https://learn.hashicorp.com/tutorials/vault/pki-engine#step-2-generate-intermediate-ca) via the `type=exported` API parameter: https://www.vaultproject.io/api-docs/secret/pki#generate-intermediate. Once issued, this cert _should_ have the necessary key usages and the private key+cert can be directly copied into k8s. It does mean that any further control might be harder, but I think as stated, it should work around this particular issue. 

There's some "gotchas" with this approach, namely that the intermediate endpoint shouldn't be used inside Vault and there's less control over things like name constraints, serial numbers, CRLs, &c. But as an intermediate step, it should work.

**Comment by hsimon-hashicorp** [comment]
Thanks @cipherboy! @sirmax123 did you have any further questions? Would that workaround proposed by Alex work for you? Please let me know - thanks!

**Comment by avoidik** [comment]
an intermediate CA will return a CSR altogether with the private and public certificates, which would require a valid cross-signed certificate by a root CA to become valid, so it cannot be uploaded as is, but if your own another root CA in Vault it's possible to `sign-intermediate` ([ref.](https://www.vaultproject.io/api-docs/secret/pki#sign-intermediate)), and then `set-signed` ([ref.](https://www.vaultproject.io/api-docs/secret/pki#set-signed-intermediate)) will render it as trusted

**Comment by cipherboy** [comment]
@avoidik My understanding is that `sirmax123` simply needed an intermediate that they could issue outside of Vault, but that the Vault root CA (and/or intermediate) were trusted. If you need an external CA to be the root of trust (and not the newly generated intermediate), yes, cross-signing would be the way to go. 

HTH :-)

**Comment by cipherboy** [comment]
@sirmax123 One other thought, could you use [`/pki/root/sign-intermediate`](https://www.vaultproject.io/api/secret/pki#sign-intermediate) or [`/pki/root/sign-self-issued`](https://www.vaultproject.io/api/secret/pki#sign-self-issued) for this purpose? I'm fairly sure both endpoints work regardless of if your mount has a root or an intermediate.

**Comment by cipherboy** [comment]
This should definitely be addressed in the rotation work https://github.com/hashicorp/vault/pull/15277 (docs in https://github.com/hashicorp/vault/pull/15238); feel free to test it out! You'll want to call `/issuer/:issuer_ref/sign-intermediate` or the existing `/root/sign-intermediate` endpoint. This is slated for 1.11.
