### ISSUE TITLE
Vault not reloading certificates on SIGHUP

### ISSUE THREAD

**Issue by nathan-march** [hashicorp/vault#12923]
**Describe the bug**
When I send vault a SIGHUP and a reload is triggered, it does not properly reload/apply an updated web certificate.

This seems to have popped up a couple of times in earlier tickets (#5442), where they indicated there was an issue with the cert. I've checked mine more times than I count and can't see anything wrong.

My certificate is formatted as such:

```
-----BEGIN CERTIFICATE-----
My servers certificate
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
Cert for C = US, O = Let's Encrypt, CN = R3
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
Cert for Subject: C = US, O = Internet Security Research Group, CN = ISRG Root X1
-----END CERTIFICATE-----
```

Not sure how to debug this further, cranking up the debug log level doesn't show anything useful.

**To Reproduce**
1. Replace the certificate file with a new one
2. `killall -SIGHUP vault` 
3. Confirm in the docker logs that you see "Vault reload triggered"
4. Test the cert and confirm it hasn't updated

**Expected behavior**
I expect it to switch to the new cert

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.7.0
* Vault CLI Version (retrieve with `vault version`): Vault v1.7.0 (4e222b85c40a810b74400ee3c54449479e32bb9f)
* Server Operating System/Architecture: vault docker image b359df68a663

Vault server configuration file(s):

```hcl
storage "mysql" {
  username = "vault"
  password = "XXXXX"
  database = "vault"
}

# We bind on both 443 and 8200, since many tools default to 8200
listener "tcp" {
  address     = "0.0.0.0:443"
  tls_cert_file = "/ssl/XXXXX.fullchain.pem"
  tls_key_file = "/ssl/XXXXX.key"
}

listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_cert_file = "/ssl/XXXXX.fullchain.pem"
  tls_key_file = "/ssl/XXXXX.key"
}

# Bump the default logging level
log_level = "debug"

# Allow GUI access
ui = true
```

**Comment by nvx** [comment]
If Vault is restarted does the new certificate load properly? If not you might have an issue with the cert and key (eg, the private key does not match the certificate).

If a restart of Vault does load the certificate properly, the next guess would be since you're running in Docker, how are you loading the certificates into the container? If you're doing `-v /some/path/XXXXX.fullchain.pem:/ssl/XXXXX.fullchain.pem` this is likely the issue, as changes to the file inode will not propagate (which can happen for a lot of reasons). The better option would be to mount a directory containing the certificate files with `-v` then reference that, eg `-v /some/path:/ssl`

**Comment by jeremyspykerman** [comment]
I'm running a newer version of vault (1.8.3) and I'm experiencing the same issue.

I'm running vault in k8s and I'm sending the SIGHUP from inside the running container.

Not sure if it makes a difference, but the volume containing the key, certificate and root certificate is mounted from a secret created by cert-manager.

Also, in case it makes a difference I'm using the raft storage backend.

Yes, killing the pods does load the new certificate.

**Comment by hsimon-hashicorp** [comment]
Thanks, folks! I'm checking with our engineering teams about this. Personally, I agree that checking the certs again on a SIGHUP is expected, however, I can't make any guarantees about past design decisions. I'll be sure to let folks know what we find - thank you for your patience!

**Comment by jsaletan** [comment]
Vault 1.9.0 is behaving as expected* for me on Ubuntu 20.04 (not containerized), using a cert and key updated by consul-template after sending vault a SIGHUP.  However my Chrome browser (96.0.4664.55 on macOS) had old cert details cached, so even though it displayed "Connection is secure" and a locked padlock icon, the cert details showed the old expiration date and the red text "certificate is expired".  I was able to clear this on Chrome by restarting the browser.

My recommendation: Download the cert with `openssl s_client -connect <myhost>:<port>` and check it with `openssl x509 -text -noout -in <certfile>` to eliminate any weird browser behavior.

*Expected == It uses the updated cert and does not seal the vault.

**Comment by arbfay** [comment]
Had the same issue. Vault v1.9.2 (f4c6d873e2767c0d6853b5d9ffc77b0d297bfbdf) on Ubuntu 20.04 and no container. I tried the commands `kill -1 <pid>` and `pkill --signal SIHUP vault`.
Checked the certificates with the command `openssl s_client -connect $VAULT_ADDR -showcerts | openssl x509 -noout -text`.

However, a service restart did the update.

**Comment by cipherboy** [comment]
I'm unable to reproduce this. On Fedora 34, I've tested the following versions:

```
Vault v1.10.0-dev ('69bdb574aad709503e59734f7a1a91824831cadd')
Vault v1.9.3 ('7dbdd57243a0d8d9d9e07cd01eb657369f8e1b8a')
Vault v1.9.2 ('f4c6d873e2767c0d6853b5d9ffc77b0d297bfbdf')
Vault v1.9.0 ('6dae166b52e0d65147991d143045ad929eb3d71b')
Vault v1.8.3 ('73e85c3c21dfd1e835ded0053f08e3bd73a24ad6+CHANGES')
 ^ had a http/web_ui folder lying around that I didn't remove.
```

<details>

<summary> Complete testing scenario </summary>

I ran:

```
sscg --client-file=client.pem --client-key-file=client-key.pem --subject-alt-name=IP:127.0.0.1/255.0.0.0 --force
cat service.pem ca.crt > chain.pem
```

to generate the certificates.

My entire vault config is:

```hcl
telemetry {
  usage_gauge_period = "5s"
  prometheus_retention_time = "24h"
  disable_hostname = true
}

storage "inmem" {}
disable_mlock = true

listener "tcp" {
  address       = "0.0.0.0:8100"
  disable_clustering = true
  tls_cert_file = "/home/cipherboy/devvault/chain.pem"
  tls_key_file  = "/home/cipherboy/devvault/service-key.pem"
  tls_client_ca_file = "/home/cipherboy/devvault/ca.crt"
}

listener "tcp" {
  address       = "0.0.0.0:8200"
  disable_clustering = true
  tls_cert_file = "/home/cipherboy/devvault/chain.pem"
  tls_key_file  = "/home/cipherboy/devvault/service-key.pem"
  tls_client_ca_file = "/home/cipherboy/devvault/ca.crt"
}
```

which I executed via:

```
vault server -log-level=trace -config=/home/cipherboy/devvault/config.hcl > /home/cipherboy/devvault/vault.log 2>&1
```

I used this command to check certificates:

```
openssl s_client -connect localhost:8200 <<< ""
```

When I initially connected, I got a certificate with serial number `5944479862054057753` on both ports (8100 and 8200). This matches from `openssl x509`. 

I re-executed the `sscg` + `cat` commands to rebuild the chain.

I issued a SIGHUP via:

```
killall -SIGHUP vault
```

from the same user as was running vault (`cipherboy` in this case). This caused the following line in the logs:

```
2022-02-04T10:56:08.411-0500 [DEBUG] would have sent systemd notification (systemd not present): notification=RELOADING=1
2022-02-04T10:56:08.414-0500 [DEBUG] core: set config: sanitized config="{\"api_addr\":\"\",\"cache_size\":0,\"cluster_addr\":\"\",\"cluster_cipher_suites\":\"\",\"cluster_name\":\"\",\"default_lease_ttl\":0,\"default_max_request_duration\":0,\"disable_cache\":false,\"disable_clustering\":false,\"disable_indexing\":false,\"disable_mlock\":true,\"disable_performance_standby\":false,\"disable_printable_check\":false,\"disable_sealwrap\":false,\"disable_sentinel_trace\":false,\"enable_response_header_hostname\":false,\"enable_response_header_raft_node_id\":false,\"enable_ui\":false,\"listeners\":[{\"config\":{\"address\":\"0.0.0.0:8100\",\"disable_clustering\":true,\"tls_cert_file\":\"/home/cipherboy/devvault/chain.pem\",\"tls_client_ca_file\":\"/home/cipherboy/devvault/ca.crt\",\"tls_key_file\":\"/home/cipherboy/devvault/service-key.pem\"},\"type\":\"tcp\"},{\"config\":{\"address\":\"0.0.0.0:8200\",\"disable_clustering\":true,\"tls_cert_file\":\"/home/cipherboy/devvault/chain.pem\",\"tls_client_ca_file\":\"/home/cipherboy/devvault/ca.crt\",\"tls_key_file\":\"/home/cipherboy/devvault/service-key.pem\"},\"type\":\"tcp\"}],\"log_format\":\"\",\"log_level\":\"\",\"log_requests_level\":\"\",\"max_lease_ttl\":0,\"pid_file\":\"\",\"plugin_directory\":\"\",\"raw_storage_endpoint\":false,\"storage\":{\"cluster_addr\":\"\",\"disable_clustering\":false,\"redirect_addr\":\"\",\"type\":\"inmem\"},\"telemetry\":{\"add_lease_metrics_namespace_labels\":false,\"circonus_api_app\":\"\",\"circonus_api_token\":\"\",\"circonus_api_url\":\"\",\"circonus_broker_id\":\"\",\"circonus_broker_select_tag\":\"\",\"circonus_check_display_name\":\"\",\"circonus_check_force_metric_activation\":\"\",\"circonus_check_id\":\"\",\"circonus_check_instance_id\":\"\",\"circonus_check_search_tag\":\"\",\"circonus_check_tags\":\"\",\"circonus_submission_interval\":\"\",\"circonus_submission_url\":\"\",\"disable_hostname\":true,\"dogstatsd_addr\":\"\",\"dogstatsd_tags\":null,\"lease_metrics_epsilon\":3600000000000,\"maximum_gauge_cardinality\":500,\"metrics_prefix\":\"\",\"num_lease_metrics_buckets\":168,\"prometheus_retention_time\":86400000000000,\"stackdriver_debug_logs\":false,\"stackdriver_location\":\"\",\"stackdriver_namespace\":\"\",\"stackdriver_project_id\":\"\",\"statsd_address\":\"\",\"statsite_address\":\"\",\"usage_gauge_period\":5000000000}}"
```

When I connected with `openssl s_client` again, on both 8100 and 8200, I got a certificate with the new serial number `580666867079522094`. This matches from `openssl x509`. 

</details>

I believe @jsaletan has the correct answer here. Browsers and most TLS consumers (e.g., databases using OpenSSL or NSS) will cache session resumption tickets from the server, which Go's TLS server issues by default. These persist throughout the lifetime of the server (up to the Go max resumption window of 7 days or if cache is full, then older entries are purged). When using a session resumption ticket, the client and server already know a previous master secret value (as both have completed the full handshake negotiation) and thus do _not_ need to exchange certificate information. It is likely that browsers cache existing certificates for a connection as long as they persist the TLS session resumption ticket (or at least, the short time we've been looking at from our `SIGHUP` testing).

Restarting Vault clears the resumption cache but simply sending a SIGHUP doesn't (see e.g. #13518).

This is likely why `openssl s_client` shows the correct value but a browser may not. 

Feel free to reopen if I've missed something, but as it is, I'm unable to reproduce this without more details.

**Comment by Cookiezzz** [comment]
Apologies for returning this from the grave but I'm encountering this issue today.
Nor systemctl reload nor kill will reload my certificates. I encounter this behavior on 3 different nodes.
I also read through https://github.com/hashicorp/vault/issues/5442 but nothing there really.

**Expected behavior**
Vault reloads the certificates from the paths configured in the .hcl config without me having to restart and manually enter unseal keys.

**Environment:**
* Vault Server Version **1.18.0**
* Server Operating System/Architecture: **Debian GNU/Linux 11 (bullseye)** No containers

The output below is from the openssl command. I blanked out most details except for the serial numbers.

![Image](https://github.com/user-attachments/assets/05caaef0-3d33-4b3b-8ece-3d245e05d9bd)
