### ISSUE TITLE
`LifetimeWatcher` should accept `api.Secret`s created by `/auth/token/lookup` calls

### ISSUE THREAD

**Issue by michaelbeaumont** [hashicorp/vault#12928]
**Is your feature request related to a problem? Please describe.**
It appears that `LifetimeWatcher` doesn't work if `Secret` is set to the return value of an `/auth/token/lookup` call, since this call returns the token data under the `"data"` key and not under `"auth"`.

https://github.com/hashicorp/vault/blob/5dc90d80817cc6f4225b6fef1d56ea3550c3fa11/api/lifetime_watcher.go#L239-L248

The `default` case is taken and all the values checked there are empty for `/auth/token/lookup` responses, causing the `LifetimeWatcher` not to function.

A workaround is doing something like (doesn't compile):

```
token.Auth = &vault_api.SecretAuth{
	Renewable:     token.TokenIsRenewable(),
	LeaseDuration: token.TokenTTL(),
	ClientToken:   client.Token(),
}
```

Methods on `Secret` like `TokenTTL` and `TokenIsRenewable` already support `/auth/token/lookup` because they also check under `"data"`.

**Describe the solution you'd like**
`api.Secret`s created from `/auth/token/lookup` calls should be supported.

**Comment by hsimon-hashicorp** [comment]
Hi @michaelbeaumont! Would you be willing to share more information about the use case for this fix? Would love to know more about the problem you're trying to solve, and what sorts of configuration you're working with. Thanks in advance!

**Comment by hsimon-hashicorp** [comment]
Wanted to check in again, @michaelbeaumont - we'd still be very interested in hearing about the kind of problem you're running into! Thanks. :)

**Comment by michaelbeaumont** [comment]
@hsimon-hashicorp My use case I think is basically as described in the original comment. I have a `vault_api.Client` authorized via token and want to fetch the token as a `Secret` in order to create a `LifetimeWatcher`. If I do this via `clien.Auth().Token().LookupSelf()`, `LifetimeWatcher` is as described unable to handle the resulting `Secret`. The methods on `Secret` already handle this case perfectly well so I suspect `LifetimeWatcher` should too, but I may not be using the API optimally.

**Comment by hsimon-hashicorp** [comment]
Thanks, @michaelbeaumont! We may have more questions to ensure we understand the ask. I appreciate your patience!

**Comment by pmmukh** [comment]
Hi @michaelbeaumont ! Thanks for the additional clarification on your use case! However, I think we might still need a little more information from your end. So typically, the vault agent on startup fetches a token and instantiates the LifetimeWatcher with it. I am assuming in your case, you aren't using the vault agent. So not sure how exactly your use case looks. Could you provide additional details, as to why you need to create a separate LifetimeWatcher, if the process that fetches the token is separate from the process that renews it, etc., like those sorts of details ? I think we understand the code flows you're trying to use, but not your overall setup.

**Comment by raskchanky** [comment]
This hasn't had a response in awhile now, so I'm going to close it due to inactivity. Please feel free to reopen if you feel this was a mistake, or if there is additional information to add. Thanks!
