### ISSUE TITLE
Vault LDAP Group Policy

### ISSUE THREAD

**Issue by 0x9090** [hashicorp/vault#1294]
I'm trying to map our global "Domain Users" group to all have LDAP login into Vault.
```
vault write auth/ldap/groups/"Domain Users" policies=default
Success! Data written to: auth/ldap/groups/Domain Users
```
I am using the default policies included with Vault. When I try a CURL login call, I get,
```
curl -X POST https://###/v1/auth/ldap/login/### -d '{"password":"###"}'
{"errors":["user is not a member of any authorized group"]}
```
I am on version 0.6.0-dev of Vault and a fully patched Debian Jessie box

AD Group Details looks like,
```
PS C:\> Get-ADPrincipalGroupMembership ###

distinguishedName : CN=Domain Users,OU=###,OU=###,DC=###,DC=###
GroupCategory : Security
GroupScope : Global
name : Domain Users
objectClass : group
objectGUID: ###
SamAccountName: Domain Users
SID : ###
```

**Comment by jefferai** [comment]
I have seen another post where the group in question had a space in it. It would help if you could make some code changes to track down what group names are being considered where -- I have a feeling that this has to do with comparing escaped vs non-escaped values somewhere along the way.

I'll paste what I told the other user:

It'd be helpful if you could put in some debugging in
`builtin/credential/ldap.backend.go`. I'd first look at line 185 (based
on current `master`) and put in something to print out the value of
`allgroups`:
```
panic(fmt.Sprintf("%#v", allgroups))
```
This will help you know whether the group is found in LDAP but not
matching what's been stored or whether it was not parsed successfully
in the first place.

**Comment by shomron** [comment]
I have found that the current code does not correctly query for nested group membership on Active Directory. I believe the fix to this will require changing `builtin/credential/ldap/backend.go` to use a query closer to `(member:1.2.840.113556.1.4.1941:=<userDnGoesHere>)`.

**Comment by jefferai** [comment]
There's a discussion about fixing this in #1245 so I'm going to close this in favor of it.
