### ISSUE TITLE
Rename -insecure flag

### ISSUE THREAD

**Issue by sean-** [hashicorp/vault#130]
Pedantic comment/suggestion: `-insecure` is a value judgement and not an actual global mode of operation for vault.  The help dialog indicates it "doesn't verify TLS" but the effect of that is not clear.  Is hostname verification disabled or is peer not verified against trusted CA's?  To answer that, you have to chase back to Go's docs.

```go
        // InsecureSkipVerify controls whether a client verifies the
        // server's certificate chain and host name.
        // If InsecureSkipVerify is true, TLS accepts any certificate
        // presented by the server and any host name in that certificate.
        // In this mode, TLS is susceptible to man-in-the-middle attacks.
        // This should be used only for testing.
        InsecureSkipVerify bool
```

Which is a long way of saying, `-insecure` in what regard?  I don't like anything insecure about where I store passwords.  The argument name comes from Go and seems like a byproduct of mental priming.

How about `--no-verify-tls` or something more explicit?  If this weren't a critical security application, I wouldn't have an opinion about the nomenclature, but in this case, being pedantic and explicit feels important.   It's also early enough that this change could be made reasonably easily.

**Comment by knuckolls** [comment]
I'm always for being explicit with nomenclature. This is a good idea. :+1:

**Comment by armon** [comment]
Agreed as well. We will try to get this in the next release. We can alias `-insecure` as well, so it shouldn't break anything.

**Comment by mitchellh** [comment]
Done
