### ISSUE TITLE
Can't issue a consul token using a consul secret engine

### ISSUE THREAD

**Issue by dmitryzarubin** [hashicorp/vault#13021]
**Describe the bug**
Hello. 
I can't issue a consul token using a consul secret engine.  

**To Reproduce**
1. Run Vault in docker container using the official image (all the commands below were executed inside the vault container)
2. Run Consul in docker container using the official image
3. I used vault pki engine to generate certs for vault and consul. All certs were stored into ../Config/ folder and added as a volume to docker container (path in the container is /vault/config/) 
4. I enabled and configured a consul secret engine:
```
vault secrets enable consul

vault write consul/config/access \
    address=https://169.254.1.1:8551 \
    scheme=https \
    ca_cert=/vault/config/consul-ca.crt \
    client_cert=/vault/config/dc1-consul-tls.crt \
    client_key=/vault/config/dc1-consul-tls-key.key \
    token=a8a463c5-a284-8f0e-9595-86218b40cd7d

vault write consul/roles/agent-role policies=agent-policy
```
5. I tried to issue a consul token:
```
vault read consul/creds/agent-role
```

**Actual behavior**
I got an error:
```
/ # vault read consul/creds/agent-role
Error reading consul/creds/agent-role: Error making API request.

URL: GET https://169.254.1.1:8200/v1/consul/creds/agent-role
Code: 500. Errors:

* 1 error occurred:
        * tls: failed to find any PEM data in certificate input
```

**Expected behavior**
I get a consul token or more detailed description of the cause of the error (what I need to change to fix the error)

**Environment:**
* Vault Server Version:  1.8.4
* Vault CLI Version: 1.8.4
* Server Operating System/Architecture: Docker (host is Ubuntu 20.04.3 LTS)

Vault server configuration file(s):

```hcl
storage "file" {
  path = "/vault/data"
}

listener "tcp" {
  address             = "169.254.1.1:8200"
  tls_disable         = "false"
  tls_cert_file       = "vault/config/dc1-vault-tls.crt"
  tls_key_file        = "vault/config/dc1-vault-tls-key.key"
  tls_client_ca_file  = "vault/config/vault-ca.crt"
  tls_require_and_verify_client_cert = "true"
}

api_addr            = "https://169.254.1.1:8200"
cluster_addr        = "https://169.254.1.1:8201"
log_level           = "Trace"
log_format          = "json"
ui                  = "true"
disable_clustering  = "true"
```

**Additional context**
- I have attached my consul certs to this ticket and I can connect to my consul server using them.
[certs.zip](https://github.com/hashicorp/vault/files/7463810/certs.zip)
- I also tried to use different formats of the path to certificates, but it didn't work
    ca_cert='/vault/config/consul-ca.crt' \
    ca_cert=@/vault/config/consul-ca.crt \

**Comment by hsimon-hashicorp** [comment]
Hi there! You're providing file names, but the CLI is expecting actual certificates. If you pre-pend the names with @, so the CLI knows to look for a file, you may have more luck. Try that, and let me know. :)

**Comment by dmitryzarubin** [comment]
@hsimon-hashicorp, hi!
Thank you for your reply, it really helped me!

I tried to use @ in names but it didn't work for me, I don't know why, maybe I did something wrong.
But I put the contents of the certificates in the command parameters and it worked.
Something like this:
```
vault write consul/config/access \
    address=https://169.254.1.1:8551 \
    scheme=https \
    ca_cert="$(<consul-ca.crt)" \
    client_cert="$(<dc1-consul-tls.crt)" \
    client_key="$(<dc1-consul-tls-key.key)" \
    token=a8a463c5-a284-8f0e-9595-86218b40cd7d
```

**Comment by hsimon-hashicorp** [comment]
I'm so glad you got it to work! I'll go ahead and close this issue now. Please always feel free to ask questions over on our Discuss forums - it often gets more views from subject matter experts who can help out. If you ever need to file a bug report, though, of course GitHub issues are also always open! :)
