### ISSUE TITLE
Wrong url to changelog in the vault uI

### ISSUE THREAD

**Issue by Noobgam** [hashicorp/vault#13047]
**Describe the bug**
Very minor issue, but link to changelog seems to point to master branch, which is stale, perhaps you've changed the name of work branch to 'main'
![image](https://user-images.githubusercontent.com/10178515/140336769-ab0a798c-da68-4067-abbb-24cd40fd6b3e.png)

**To Reproduce**
1. Click on "Vault {version}" on the bottom of any page

**Expected behavior**
I expect to see the URL to my version vault.

Pretty sure it's unrelated to anything in regards to my system environment, guess this is happening on any vault 1.8.0+

**Comment by Noobgam** [comment]
couldn't find it in code myself, maybe it's already fixed in main branch
perhaps adding this to changelog is reasonable then

**Comment by ncabatoff** [comment]
Thanks for the bug report @Noobgam.

Duplicate of https://github.com/hashicorp/vault/issues/12764, closing.
