### ISSUE TITLE
request:  Add go socket templating to vault config.

### ISSUE THREAD

**Issue by Daxcor69** [hashicorp/vault#13053]
I am trying to add the following to my config,

from 
api_addr            = "http://10.10.10.x:8200"
cluster_addr        = "https://10.10.10.x:8201"

to
api_addr            = "http://{{ GetInterfaceIP \"enp94s0f1\" }}:8200"
cluster_addr        = "https://{{ GetInterfaceIP \"enp94s0f1\" }}:8201"

Because there is no templating, I have to edit each server config.  This is counter productive and differs from your other product offering.

Thanks

**Comment by hsimon-hashicorp** [comment]
Hi @Daxcor69! Thanks for submitting this request. I can't make any guarantees with regards to other products, but I'll certainly pass your feedback along to our engineering team for future consideration. Thanks again! :)

**Comment by ncabatoff** [comment]
We added this in https://github.com/hashicorp/vault/pull/9109, should be available in 1.9.0.
