### ISSUE TITLE
docs:  constant key names for tls across applications.

### ISSUE THREAD

**Issue by Daxcor69** [hashicorp/vault#13052]
Also your configuration key names differ from product to product. Let me show you

Consul:
ca_file = “/etc/consul.d/cert/consul-agent-ca.pem”
cert_file = “/etc/consul.d/cert/miami-server-consul.pem”
key_file = “/etc/consul.d/cert/miami-server-consul-key.pem”

nomad:
ca_file = “/etc/nomad.d/cert/consul-agent-ca.pem”
cert_file = “/etc/nomad.d/cert/server.pem”
key_file = “/etc/nomad.d/cert/server-key.pem”

Vault:
tls_cert_file = “/etc/vault.d/cert/server.pem”
tls_key_file = “/etc/vault.d/cert/server-key.pem”
tls_client_ca_file = “/etc/vault.d/cert/consul-agent-ca.pem”

This makes the docs even more confusing.

**Comment by hsimon-hashicorp** [comment]
Hi @Daxcor69! Thanks for submitting this request. I can't make any guarantees with regards to other products, but I'll certainly pass your feedback along to our engineering team for future consideration. Thanks again! :)
