### ISSUE TITLE
vault file backend

### ISSUE THREAD

**Issue by ramyathulasingam** [hashicorp/vault#1311]
Hi, I am new to vault I followed the docs on setting up locally the auth using app-id mentioned under - 
https://www.vaultproject.io/intro/getting-started/apis.html. They worked great the first time.
I did not store the output of 
"$ curl  -X PUT  -d "{\"secret_shares\":1, \"secret_threshold\":1}" http://localhost:8200/v1/sys/init"  the very first time. I don't have my root token. Now I am completely stuck. Is there a way to reinitialize again and get the root token, so I can setup the auth using app-id.  I don't really care about the data since its all local anyways, all I want to do is able to setup the app-id auth backend locally again and be able to use it. simply put I want to be able to start over from the beginning. 

Any help on this is greatly appreciated.

**Comment by jefferai** [comment]
Hi there,

Just delete the directory configured for the file backend. That will reset everything to a clean state where you can init again!

**Comment by ramyathulasingam** [comment]
@jefferai  Thank you!

**Comment by jefferai** [comment]
@ramyathulasingam No problem!
