### ISSUE TITLE
Show missing databases in UI

### ISSUE THREAD

**Issue by OmgImAlexis** [hashicorp/vault#13112]
**Is your feature request related to a problem? Please describe.**
I would like to know which database plugins are compatible with the UI.

**Describe the solution you'd like**
I'd like to see the missing databases in the UI dropdown but with "(coming soon)" and the `disabled` attribute.

**Describe alternatives you've considered**
A mark on each database in the "database-capabilities" table https://www.vaultproject.io/docs/secrets/databases#database-capabilities showing which ones are in the UI and which ones require a `rc` release or `cli` to use.

**Explain any additional use-cases**
It'd make it easier for users to find which databases work but just don't have UI support yet.

**Additional context**
https://discuss.hashicorp.com/t/missing-database-types/31758

**Comment by hellobontempo** [comment]
We've added the UI supported databases to our docs (these will be live during our next release which should be around the beginning of august. We're discussing internally about adding the disabled databases options to the connection dropdown list.
