### ISSUE TITLE
"Connection will be verified" can't be toggled off for postgres

### ISSUE THREAD

**Issue by OmgImAlexis** [hashicorp/vault#13119]
**Describe the bug**
I can't disable "Connection will be verified" in the UI for postgres.

**To Reproduce**
1. Create postgres DB in UI
2. Edit that DB and untick "Connection will be verified" and save
3. See the setting is still enabled

**Expected behavior**
The checkbox to work.

**Environment:**
* Vault Server Version (retrieve with `vault status`): `vault:1.9.0-rc1`
* Vault CLI Version (retrieve with `vault version`): N/A
* Server Operating System/Architecture: Docker

Vault server configuration file(s):

N\A using default from docker

**Additional context**
```
docker run  -p 8200:8200 -e 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/tmp/config.hcl"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'   --cap-add=IPC_LOCK  vault:1.9.0-rc1
```

**Comment by hsimon-hashicorp** [comment]
Thanks for this issue report! Since this is against an RC build, I'll make sure to get it looked at soon.

**Comment by hsimon-hashicorp** [comment]
@OmgImAlexis thanks again! Chelsea has merged a fix for this issue, and it'll be included in future builds. Keep an eye out for it, and let us know if the issue persists. I'm going to close this issue now, but please feel free to comment or re-open if needed. :)
