### ISSUE TITLE
Vault mysql backend shows secrets in dropdown with explicit deny.

### ISSUE THREAD

**Issue by Apollorion** [hashicorp/vault#13120]
**Describe the bug**
If I have a policy setup in vault as such:
```
path "mysql/creds/*" {
  capabilities = ["deny"]
}
path "mysql/creds/write" {
  capabilities = ["deny"]
}
path "mysql/creds/readonly" {
  capabilities = ["read", "list"]
}
```
If this policy is assigned to a user in vault, the vault mysql engine shows the `write` role as an option when trying to get credentials even though it is explicitly denied in the policy. If you choose that option and click `Get Credentials`, then you're taken to an error page. But it feels like a bug since they both show up when a user only has access to one.

![Screen Shot 2021-11-05 at 12 48 02 PM](https://user-images.githubusercontent.com/13936290/141315734-22e0f0fc-a3a0-4216-943a-519baba9aac0.png)

Initially I thought this was just chrome cacheing the dropdown, but I've cleared cache and everything else and they still show up even though my role doesn't allow it.

**To Reproduce**
1. Create a vault mysql engine with a readonly role and a write role, if using terraform you can use `vault_database_secret_backend_connection`
2. Create the policy listed above
3. Navigate in the vault UI to the engine and on the `Get Credentials` page you'll see the dropdown lists both roles.

**Expected behavior**
Only one role shows up in the dropdown.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.11.2
* Server Operating System/Architecture: Ubuntu 18.04 amd64

**Comment by hsimon-hashicorp** [comment]
Hi @Apollorion - just a note, the first thing that we'd suggest doing is updating your version. 0.11 is quite old - over three years old by now - and many bug fixes have been introduced in [newer versions](https://www.vaultproject.io/docs/release-notes). We only take bug reports on versions that are n-2, which means 1.6 at this time. Thanks for understanding!
