### ISSUE TITLE
How to restrict user1 to see user2 folder under secret engine kv

### ISSUE THREAD

**Issue by anuj1366** [hashicorp/vault#13188]
**Describe the bug**
We are using KV Secrets Engines. Inside Secrets folder we are creating multiple folder like below and inside each folder we have "account_detail" where we have password stored.
![image](https://user-images.githubusercontent.com/91662053/142257018-50404400-8e0c-41b3-84ae-2313d536fb6b.png)
![image](https://user-images.githubusercontent.com/91662053/142257294-6c22a956-1a34-41d5-ad10-699823e706d7.png)
![image](https://user-images.githubusercontent.com/91662053/142257375-579800fe-e944-4de0-98bb-abff9b0850d1.png)

Now we have create below policy for each folder like below
![image](https://user-images.githubusercontent.com/91662053/142258439-4e446c16-defd-414f-91d1-ff4a9dac4f5b.png)
![image](https://user-images.githubusercontent.com/91662053/142258385-99ff1e9a-2053-438e-9ab7-1c1432ba5e57.png)

Now the issue is when the user login to the vault using client token, he can see all folder present inside Secret folder but my requirement is he should see only his specific folder instead of all the folder. but if we remove below line from policy, he can not see even his folder as well.
path "secret/*" {
  capabilities = ["list"]
}

**Expected behavior**
One client should not see other folder under /secret folder

**Environment:**
Running vault as a docker container inside AWS ec2 instance

**Additional context**
Please let me know is there any way to achieve the above requirement.

**Comment by hsimon-hashicorp** [comment]
Hello! What version of Vault are you using? Thanks!

**Comment by anuj1366** [comment]
https://releases.hashicorp.com/vault/0.10.3/vault_0.10.3_linux_amd64.zip

**Comment by hsimon-hashicorp** [comment]
Thanks, @anuj1366 - that is quite an old version, released in 2018. Please check the [releases page](https://releases.hashicorp.com/vault/) for more information on available versions - and in fact, 1.9 was released today! :)
Since we only accept issues and bug reports for versions "`n-2`", where `n` is the current version, I'm going to close this issue now. Please do check out the newer versions, as many of these sorts of issues have been identified and resolved. Thanks for your understanding.

**Comment by anuj1366** [comment]
Hi Team,
Now I am using vault_1.8.5 and facing same issue.

**Comment by hsimon-hashicorp** [comment]
Hi @anuj1366 - please provide repro steps and other information, and we'll take a look.

**Comment by hsimon-hashicorp** [comment]
Also, note that we did some kv revamp work in 1.9 to make this management easier. While "list" is required to navigate, there's a search bar in 1.9 for KV v2, as well. For example:
![image (4)](https://user-images.githubusercontent.com/84740964/142462257-39940b2f-49e5-43a1-86cc-aeb0b4b89a0d.png)
The ACL / policy experience is better in KV v2, so please do check that out too! https://www.vaultproject.io/docs/secrets/kv/kv-v2#acl-rules

**Comment by maxb** [comment]
The Vault ACL policy system only accomodates allowing a list operation, or denying it - it does not have the capability to filter the returned results to disclose only the child keys that a user has further permissions to.

(Note: I'm not affiliated with HashiCorp; I'm just a fellow user who happened to know the answer.)

**Comment by scud328** [comment]
I think it is possible via:

path "secretkvname/data/atomic/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "secretkvname/data/atomic" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

# Delete any version of a key
path "secretkvname/delete/atomic/*" {
  capabilities = ["update"]
}

# Undelete data
path "secretkvname/undelete/atomic/*" {
  capabilities = ["update"]
}

# Destroy versions
path "secretkvname/destroy/atomic/*" {
  capabilities = ["update"]
}

# List keys
path "secretkvname/metadata/atomic/*" {
  capabilities = ["list"]
}

# View metadata for each version
path "secretkvname/metadata/atomic/*" {
  capabilities = ["read"]
}

# Permanently remove all versions and metadata for a key
path "secretkvname/metadata/atomic/*" {
  capabilities = ["delete"]
}

path "secretkvname/*" {
  capabilities = ["list"]
}


atomic is my folder name
