### ISSUE TITLE
UI - user can't delete secret under specific path

### ISSUE THREAD

**Issue by lukpep** [hashicorp/vault#13180]
**Describe the bug**
user with policy:
```
path "app-secrets/data/application_1/*" {
  capabilities = ["create", "update", "read", "delete", "list"]
}

# required so that users can navigate in the UI - related to https://github.com/hashicorp/vault/issues/5362
path "app-secrets/*" {
  capabilities = ["list"]
}
```
is able to create and edit secrets (as expected) only under `application_1` path in `app-secrets` engine.  Delete is not possible - option is missing in UI menu:
![CleanShot 2021-11-17 at 15 06 46](https://user-images.githubusercontent.com/2960580/142215593-7238fd2c-cf63-4e9f-9ab9-59c40f049564.png)

![CleanShot 2021-11-17 at 15 07 00](https://user-images.githubusercontent.com/2960580/142215632-b5964498-e5b7-4e86-9823-ef61cb71df36.png)

only after I add this to a user policy:
```
path "app-secrets/*" {
  capabilities = ["delete"]
}
```
option in UI appears:
![CleanShot 2021-11-17 at 15 09 14](https://user-images.githubusercontent.com/2960580/142215970-ebf59a45-b3f0-43bd-8252-d13a50e7fe57.png)

**To Reproduce**
create user with the above policy and verify options available in the UI

**Expected behavior**
Users should be allowed to delete secrets under the specific paths with this first policy.

**Environment:**
* Vault Server Version 1.8.4
* Vault CLI Version Vault v1.8.4 (925bc650ad1d997e84fbb832f302a6bfe0105bbb)
* Server Operating System/Architecture: K8s linux x86

**Comment by hsimon-hashicorp** [comment]
Hi @lukpep! This is fixed in version 1.9. It was not backported to 1.8, because so much work went into the kv revamp in 1.9 that it would have been difficult to get all of those updates in 1.8. Please try 1.9 and let me know if it fixes the issue for you. Thanks!

**Comment by lukpep** [comment]
Yep - upgraded my clusters and now it works as expected ;-)
Although https://github.com/hashicorp/vault/issues/5362 is still there - the user has to  be able to list all secret paths / or now exactly what to look for:
![CleanShot 2021-11-18 at 19 05 56](https://user-images.githubusercontent.com/2960580/142478540-0c960ffa-1553-4601-aae9-ceb8b3c072f3.png)

**Comment by hsimon-hashicorp** [comment]
Thanks @lukpep! We'll keep looking for ways to make the kv v2 experience better. Really appreciate your time! :)
