### ISSUE TITLE
GitHub Deploy Key secret backend

### ISSUE THREAD

**Issue by EvanKrall** [hashicorp/vault#1319]
Github currently supports having one or more deploy keys per repository, but deploy keys cannot be shared among multiple repositories. This makes managing keys a bit of a hassle if I have multiple actors working on multiple repos.

It would be nice if Vault could manage GitHub Deploy Keys for me, creating keys on demand, deleting them when the lease expires, etc.

**Comment by jefferai** [comment]
We have no current plans for a built-in backend to do this, but with our plugin capabilities this can now be easily created by an interested third-party!
