### ISSUE TITLE
Web-UI errors with EC certs on PKI backend

### ISSUE THREAD

**Issue by tristanmorgan** [hashicorp/vault#13219]
**Describe the bug**
The new PKI UI fails with an error when trying to view certificates generated with an EC key

**To Reproduce**
1. log into the Vault UI
2. generate a certificate with EC keys configured
3. See error

<img width="849" alt="Issue ECC cert error" src="https://user-images.githubusercontent.com/6336384/142508599-a08d1acb-190e-46e3-9568-16addf95b8c4.png">

**Expected behavior**
if the JS library can't decode the certificate it should fail gracefully.

**Environment:**
* Vault Server Version: 1.9.0
* Vault CLI Version: 1.9.0 
* Server Operating System/Architecture: macOS

Vault server configuration file(s):

```hcl
seal "awskms" {
  region     = "ap-southeast-2"
  kms_key_id = "alias/vault"
  endpoint   = "http://10.10.10.115:8080"
}

storage "raft" {
  path    = "raft/"
  node_id = "vault_1"
}

service_registration "consul" {
  scheme       = "http"
  service_tags = "urlprefix-vault.service.consul/"
}

listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = true

  telemetry {
    unauthenticated_metrics_access = true
  }
}

telemetry {
  prometheus_retention_time = "30s"
  disable_hostname          = true
}

default_lease_ttl    = "1h"
max_lease_ttl        = "12h"
ui                   = true
raw_storage_endpoint = true
api_addr             = "http://{{GetPrivateIP}}:8200"
cluster_addr         = "https://{{GetPrivateIP}}:8201"
```

**Additional context**
Seems this stems from an upstream issue [ECC Support #116](https://github.com/digitalbazaar/forge/issues/116)

**Comment by hsimon-hashicorp** [comment]
Hi @tristanmorgan! Can you show the error you're seeing? The screenshot looks sort of empty. (Or, is that the error?) Let me know, and we'll get our engineering teams on it. Thank you! :)

**Comment by tristanmorgan** [comment]
Hi @hsimon-hashicorp, Yes, the error is the missing certificate details.

Related to this error is what happens when looking at an existing certificate, this error is shown:
<img width="849" alt="existing ecc certificat error" src="https://user-images.githubusercontent.com/6336384/142514533-6add46e1-bd18-4264-bdb4-d75af86a7567.png">

**Comment by hsimon-hashicorp** [comment]
Perfect, thank you so much! I'll look into this and pass the findings onto our amazing UI engineers.

**Comment by hsimon-hashicorp** [comment]
@tristanmorgan thank you again from me - I validated the issue, and we did in fact add `node-forge` in 1.9 to handle PKI metadata. We're on it, and I appreciate your patience!
