### ISSUE TITLE
Panic when vault attempts to rotate a corrupt/missing OIDC Key

### ISSUE THREAD

**Issue by rigrassm** [hashicorp/vault#13223]
**Describe the bug**
It appears there is a scenario where a needed value in a [namedKey](https://github.com/hashicorp/vault/blob/main/vault/identity_store_oidc.go#L48) object can be missing resulting in a Vault panic when the OIDC key rotation periodic job is fired off for it.

I just finished recovering our cluster from an outage which is when I found this occurring but based on a preliminary investigation, it appears that the outage was likely caused by something else and was likely the cause of this panic scenario. 

I suspect there is possibly a race condition occurring allowing for a namedKey to be saved with incomplete data such that the key is seen as needing to be rotated despite the fact that not all of the values needed to perform the rotation are present(not exactly sure exactly which value was missing). 

Below is the stack trace output provided during the panic.

```
Nov 19 06:57:01 vault-5.example.com vault[84552]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 19 06:57:01 vault-5.example.com vault[84552]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x27445dc]
Nov 19 06:57:01 vault-5.example.com vault[84552]: goroutine 1696 [running]:
Nov 19 06:57:01 vault-5.example.com vault[84552]: github.com/hashicorp/vault/vault.(*namedKey).rotate(0xc000cf4510, {0x5e4e9b8, 0xc0010347e0}, {0x5f1ade0, 0xc001065800}, {0x5e502e0, 0xc000b2c0c0}, 0xffffffffffffffff)
Nov 19 06:57:01 vault-5.example.com vault[84552]:         /home/runner/work/vault/vault/vault/identity_store_oidc.go:1492 +0x29c
Nov 19 06:57:01 vault-5.example.com vault[84552]: github.com/hashicorp/vault/vault.(*IdentityStore).oidcKeyRotation(0xc000feea00, {0x5e4e9b8, 0xc0010347e0}, {0x5e502e0, 0xc000b2c0c0})
Nov 19 06:57:01 vault-5.example.com vault[84552]:         /home/runner/work/vault/vault/vault/identity_store_oidc.go:1821 +0x6c5
Nov 19 06:57:01 vault-5.example.com vault[84552]: github.com/hashicorp/vault/vault.(*IdentityStore).oidcPeriodicFunc(0xc000feea00, {0x5e4e9b8, 0xc0010347e0})
Nov 19 06:57:01 vault-5.example.com vault[84552]:         /home/runner/work/vault/vault/vault/identity_store_oidc.go:1870 +0x3d9
Nov 19 06:57:01 vault-5.example.com vault[84552]: github.com/hashicorp/vault/vault.NewIdentityStore.func1({0x5e4e9b8, 0xc0010347e0}, 0x0)
Nov 19 06:57:01 vault-5.example.com vault[84552]:         /home/runner/work/vault/vault/vault/identity_store.go:110 +0x30
Nov 19 06:57:01 vault-5.example.com vault[84552]: github.com/hashicorp/vault/sdk/framework.(*Backend).handleRollback(0xc000b61860, {0x5e4e9b8, 0xc0010347e0}, 0xc001033480)
Nov 19 06:57:01 vault-5.example.com vault[84552]:         /home/runner/work/vault/vault/sdk/framework/backend.go:531 +0x5f
Nov 19 06:57:01 vault-5.example.com vault[84552]: github.com/hashicorp/vault/sdk/framework.(*Backend).HandleRequest(0xc000b61860, {0x5e4e9b8, 0xc0010347e0}, 0xc0015e4300)
Nov 19 06:57:01 vault-5.example.com vault[84552]:         /home/runner/work/vault/vault/sdk/framework/backend.go:196 +0x111
Nov 19 06:57:01 vault-5.example.com vault[84552]: github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc0006c0370, {0x5e4e9b8, 0xc0010347e0}, 0xc0015e4300, 0x0)
Nov 19 06:57:01 vault-5.example.com vault[84552]:         /home/runner/work/vault/vault/vault/router.go:708 +0x15ec
Nov 19 06:57:01 vault-5.example.com vault[84552]: github.com/hashicorp/vault/vault.(*Router).Route(...)
Nov 19 06:57:01 vault-5.example.com vault[84552]:         /home/runner/work/vault/vault/vault/router.go:505
Nov 19 06:57:01 vault-5.example.com vault[84552]: github.com/hashicorp/vault/vault.(*RollbackManager).attemptRollback(0xc000dd0d80, {0x5e4e9f0, 0xc000cc6ff0}, {0xc000e1af86, 0x9}, 0xc00090c1c0, 0x1)
Nov 19 06:57:01 vault-5.example.com vault[84552]:         /home/runner/work/vault/vault/vault/rollback.go:225 +0x5d0
Nov 19 06:57:01 vault-5.example.com vault[84552]: created by github.com/hashicorp/vault/vault.(*RollbackManager).startOrLookupRollback
Nov 19 06:57:01 vault-5.example.com vault[84552]:         /home/runner/work/vault/vault/vault/rollback.go:161 +0x298
```

I will be performing a full postmortem investigation tomorrow for the outage which should verify whether the outage was caused by this issue alone, something else entirely, or a combination of things.

I do have a snapshot saved of the vault cluster taken prior to deleting the OIDC keys we had stored so if there is anything that I can do with that to dig out anything that may be helpful let me know and I will be happy to do so

**To Reproduce**
No reproduction steps at this time. Will be diving deeper into the issue though and will update if I am able to find something.

**Expected behavior**
Vault should be aware of the possibility of a nil pointer from these objects and handle the panic without crashing.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
root@vault-5:/etc/vault.d# vault status | grep Version
Version                  1.9.0
```
* Vault CLI Version (retrieve with `vault version`):
```
root@vault-5:/etc/vault.d# vault version
Vault v1.9.0
```
* Server Operating System/Architecture:
```
root@vault-5:/etc/vault.d# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
```
Vault server configuration file(s):

```hcl
max_lease_ttl      = "168h"
default_lease_ttl  = "1h"
log_level          = "Debug"
api_addr           = "https://<server-ip>:8200"
cluster_addr       = "https://10.2.66.204:8201"
plugin_directory   = "/etc/vault.d/plugins"

seal "transit" {
  address = "https://seal-server.example.com:8200"
  disable_renewal = "false"
  key_name = "autounseal"
  mount_path = "transit/"
  tls_skip_verify = "true"
}

ui = true

storage "raft" {
  path    = "/opt/vault/data"
  node_id = "vault-5"

  retry_join {
    leader_api_addr = "https://vault-3.example.com:8200"
  }
  retry_join {
    leader_api_addr = "https://vault-4.example.com:8200"
  }
}

service_registration "consul" {
  address      = "127.0.0.1:8500"
  service_address = ""
  service_tags    = "traefik.enable=true,traefik.http.services.vault.loadbalancer.server.scheme=https,traefik.http.routers.vault.service=vault,traefik.http.routers.vault.rule=Host(`vault.svc.example.com`),traefik.http.routers.vault.tls.certResolver=services"
}

listener "tcp" {
  address         = "0.0.0.0:8200"
  tls_disable     = 0
  tls_cert_file   = "/etc/vault.d/ssl/vault.crt"
  tls_key_file    = "/etc/vault.d/ssl/vault.key"
  tls_min_version = "tls12"
}

```

**Additional context**
None at the moment.

**Comment by hsimon-hashicorp** [comment]
Hi @rigrassm! Thanks so much for this issue report. I'd be very interested in more data from your post-mortem, but this is also a good start. My engineering teams are mostly out today (11/19), but we'll be picking this up next week. Thanks again! :)

**Comment by rigrassm** [comment]
@hsimon-hashicorp Unfortunately, digging through the logs on our vault servers didn't provide us with any additional insight into what caused the OIDC key to wind up in the state it was in (mainly due to losing logs from 2 of the 3 vault servers, one of which appears to have been the active node at the time).  It's possible that the panic itself was the underlying cause of the outage but we can't be sure.

**Comment by hsimon-hashicorp** [comment]
@rigrassm That's okay. We'll see what information we can glean from what you've provided and go from there - thanks so much for this report!

**Comment by njoerd114** [comment]
We're facing the same issue:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x27445dc]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x27445dc]
2021-11-21T18:26:37.749+01:00	goroutine 3938 [running]:
2021-11-21T18:26:37.751+01:00	github.com/hashicorp/vault/vault.(*namedKey).rotate(0xc001faa240, {0x5e4e9b8, 0xc002006de0}, {0x5f1ade0, 0xc000bf1530}, {0x5e502e0, 0xc000baef00}, 0xffffffffffffffff)
2021-11-21T18:26:37.751+01:00	/home/runner/work/vault/vault/vault/identity_store_oidc.go:1492 +0x29c
2021-11-21T18:26:37.754+01:00	github.com/hashicorp/vault/vault.(*IdentityStore).oidcKeyRotation(0xc001133b80, {0x5e4e9b8, 0xc002006de0}, {0x5e502e0, 0xc000baef00})
2021-11-21T18:26:37.754+01:00	/home/runner/work/vault/vault/vault/identity_store_oidc.go:1821 +0x6c5
2021-11-21T18:26:37.754+01:00	github.com/hashicorp/vault/vault.(*IdentityStore).oidcPeriodicFunc(0xc001133b80, {0x5e4e9b8, 0xc002006de0})
2021-11-21T18:26:37.754+01:00	/home/runner/work/vault/vault/vault/identity_store_oidc.go:1870 +0x3d9
2021-11-21T18:26:37.754+01:00	github.com/hashicorp/vault/vault.NewIdentityStore.func1({0x5e4e9b8, 0xc002006de0}, 0x0)
2021-11-21T18:26:37.754+01:00	/home/runner/work/vault/vault/vault/identity_store.go:110 +0x30
2021-11-21T18:26:37.757+01:00	github.com/hashicorp/vault/sdk/framework.(*Backend).handleRollback(0xc000bff380, {0x5e4e9b8, 0xc002006de0}, 0xc002021a80)
2021-11-21T18:26:37.757+01:00	/home/runner/work/vault/vault/sdk/framework/backend.go:531 +0x5f
2021-11-21T18:26:37.757+01:00	github.com/hashicorp/vault/sdk/framework.(*Backend).HandleRequest(0xc000bff380, {0x5e4e9b8, 0xc002006de0}, 0xc002026900)
2021-11-21T18:26:37.757+01:00	/home/runner/work/vault/vault/sdk/framework/backend.go:196 +0x111
2021-11-21T18:26:37.757+01:00	github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc000b75db0, {0x5e4e9b8, 0xc002006de0}, 0xc002026900, 0x0)
2021-11-21T18:26:37.757+01:00	/home/runner/work/vault/vault/vault/router.go:708 +0x15ec
2021-11-21T18:26:37.757+01:00	github.com/hashicorp/vault/vault.(*Router).Route(...)
2021-11-21T18:26:37.757+01:00	/home/runner/work/vault/vault/vault/router.go:505
2021-11-21T18:26:37.757+01:00	github.com/hashicorp/vault/vault.(*RollbackManager).attemptRollback(0xc000c9e1b0, {0x5e4e9f0, 0xc001978750}, {0xc000bd45d6, 0x9}, 0xc00127c700, 0x1)
2021-11-21T18:26:37.757+01:00	/home/runner/work/vault/vault/vault/rollback.go:225 +0x5d0
2021-11-21T18:26:37.757+01:00	created by github.com/hashicorp/vault/vault.(*RollbackManager).startOrLookupRollback
2021-11-21T18:26:37.757+01:00	/home/runner/work/vault/vault/vault/rollback.go:161 +0x298
```

We're running Vault in Version `1.9.0` on AWS ECS using dynamodb as the backend.

**Comment by fairclothjm** [comment]
Hi @rigrassm  thanks for reporting.

Could you please provide the following information:
- `rotation_period` and `verification_ttl` of the keys
- approximate uptime of the Vault 1.9.0 server before the panic

**Comment by rigrassm** [comment]
> Hi @rigrassm  thanks for reporting.
> 
> Could you please provide the following information:
> - `rotation_period` and `verification_ttl` of the keys

> - approximate uptime of the Vault 1.9.0 server before the panic

I'll have to check the ttls when I get back to the house.

It'll probably be around 30 days of server uptime and service uptime was the time between 1.9 release and this issues open date.

**Comment by fairclothjm** [comment]
Thanks again @rigrassm we are looking into the issue. We will update as soon as we know something.

Any more details you can provide around the key/role configuration would be helpful. Especially the ttls.

**Comment by rigrassm** [comment]
> Any more details you can provide around the key/role configuration would be helpful. Especially the ttls. 

Wanted to double check before responding earlier. The keys we had installed were installed using the Terraform provider and the rotation and verification ttl values were not being set in that Terraform so they would have been whatever the default is for those options.

Just to clarify, these keys were installed/configured as part of testing deployment of Consul agents with auto config so we deleted the keys in the meantime. The setup pretty much followed the Consul auto config learn guide but instead of manual commands, we used the equivalent Terraform provider resources.

**Comment by rigrassm** [comment]
OK, A little more context that may be of help.

1. There were 3 separate keys provisioned at the time when the panics started, unfortunately, due to needing to get our cluster back up, all 3 were deleted so it's not clear if it was a specific key or all 3 that were triggering the issue
2. The keys were all provisioned while running Vault 1.8.4
3. The keys were all provisioned using v2.24.1 of the Vault Provider using the code below.
```
resource "vault_identity_oidc_key" "consul_key" {
  name      = var.oidc_key_name
  algorithm = "RS256"
  allowed_client_ids = ["${var.oidc_role_name}"]
}
```

I know there were some changes recently to both the Vault OIDC key configuration behavior and the Vault Terraform provider so I'm suspecting there may be something going on with valid configurations in pre-1.9 not lining up with what's being expected in 1.9.

**Comment by rigrassm** [comment]
Sorry for spamming!

I just looked and it appears that the default values for`rotation_ttl` and `verification_ttl` are both 24h.

I finished the Vault cluster upgrade to 1.9 around 7PM on November 17th. We were alerted to a service outage caused by a pipeline not being able to connect to Vault at 8:30PM the following day, a little over 25 hours after the upgrade was done.

I haven't tested anything yet but I'm pretty confident that the key (pun unintended) to reproducing the issue will likely be generating the keys and roles on v1.8.4 and then upgrading to 1.9.

**Comment by hsimon-hashicorp** [comment]
@rigrassm It's not spamming if there's good, new information. :) Thanks again! We're researching this in our engineering teams, too - really appreciate all of this!

**Comment by hsimon-hashicorp** [comment]
(And if you get more insights or data, please - spam away!!) <3

**Comment by eroteme** [comment]
Hi, we think we hit this same issue using the identity token backend.  Roles where all ok and had data but all tokens where blank and could not recreate

We rolled back to 1.8.5 from 1.9.0 and we had to delete and recreate the identity key. Luckily we have a kubernetes controller that creates the roles again. After all this was recreated our services using the identity tokens started to work again.

It would be great to know why 1.9.0 seem to make the tokens disappear after the TTL . Wondering is something in the /sys paths of vault had changed

**Comment by eroteme** [comment]
BTW: 
rotation_period       24h
verification_ttl      24h

Took 24hr until we saw the issue start. We'd left dev -> prod for a few hour but unfortunately... not long enough

**Comment by fairclothjm** [comment]
Hello, thanks for all the details. We have identified the issue and will be submitting a fix shortly.

A workaround for this issue is to delete all keys before updating to Vault 1.9. New keys can then be created after upgrading Vault to 1.9.
