### ISSUE TITLE
Obfuscated password values in WebUI shows if a password contains certain characters

### ISSUE THREAD

**Issue by kafeinnet** [hashicorp/vault#13270]
**Describe the bug**

When a secret value contains some accentuated characters (é, à, è, ...), the obfuscated value in the WebUI shows where those characters are.

**To Reproduce**

1. Store some accentuated characters in a secret value, like é ou à
2. Look a the obfuscated value

![image](https://user-images.githubusercontent.com/4932189/143261506-5a7009a8-cb85-4ba7-a68d-a05704357311.png)

![image](https://user-images.githubusercontent.com/4932189/143261451-58504c96-2b11-4b83-b62b-741bea4c4f39.png)

**Expected behavior**

No hints about the stored value should be displayed (imho, not even the length of the password).

**Environment:**

```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.8.4
Storage Type    consul
Cluster Name    xxx
Cluster ID      xxx
HA Enabled      true
HA Cluster      https://xx.xx.xx.xx:8201
HA Mode         active
Active Since    2021-10-21T08:27:17.605793713Z
```

**Comment by evsasha** [comment]
I confirm. Obfuscation  work correct on versions 1.6.7, 1.7.7 but not work in 1.9.1 and 1.8.6

**Comment by arnav28** [comment]
Thanks @evsasha for pointing it out. We have taken both the changes (font discrepancy and length of obfuscated values) in consideration and will hopefully be pushing a fix as soon as it's prioritized. 👍
