### ISSUE TITLE
Add support for vault automatic seal

### ISSUE THREAD

**Issue by donpdonp** [hashicorp/vault#1329]
The workflow I use is to open the vault long enough to launch the daemons that read the secrets, then seal the vault. This window is perhaps 10 minutes a couple times a week. 

This setup would be more secure if there were a feature where an unsealed vault has a time limit. The vault automatically seals after X minutes from unseal. That way I wont forget to seal the vault after use.

**Comment by jefferai** [comment]
This isn't going to be added, so closing.

**Comment by donpdonp** [comment]
@skippy mostly because only the Vault daemon knows for sure when the vault has been successfully unsealed, but also its an operation I'd want to be very sure was going to succeed. the bash/sleep is a workaround but has plenty of failure modes.

@jefferai thx for the consideration, anyways :)
