### ISSUE TITLE
Vault Azure backend storage not syncing 

### ISSUE THREAD

**Issue by san6789** [hashicorp/vault#13305]
Hi,

I have created a container in azure and updated  my  config.hcl file like below

sudo cat <<EOF > config.hcl
{
"listener": [{
"tcp": {
"address" : "0.0.0.0:8200",
"tls_disable" : 1
}
}],
"api_addr": "http://xx.xx.xx.xx:8200",
"storage": {
    "azure": {
    accountName = "mystorageaccount name ",
    accountKey  = "keysof my avult ",
    container   = "container name",
    environment = "AzurePublicCloud"
    }
 },
"max_lease_ttl": "10h",
"default_lease_ttl": "10h",
"ui":true
}

but my storage container is not sync with vault data.

is there way i can sync my vault with azure backend storage please suggest

**Comment by hsimon-hashicorp** [comment]
Hello, can you provide more details such as requested in the issue template? Vault version, any errors, etc? Thanks in advance!

**Comment by san6789** [comment]
we are using vault version "Vault v1.9.0" 

we are not getting any error but i am not sure why sync is not happing between vault KV with azure container .

is there way to sync data between azure container?

**Comment by hsimon-hashicorp** [comment]
Hello! First, the Azure blob storage backend is "community-supported", meaning that while we will try and help as best we can, HashiCorp are not the maintainers of that storage backend. For KV stores, the 4MB is the maximum size for your data. You may receive an error when attempting to store more than 4MB. Please let me know if this answers your question. Thanks!

**Comment by hsimon-hashicorp** [comment]
Correction - the 4MB is per secret in a KV store. A secret larger than 4MB may error out.

**Comment by san6789** [comment]
thanks for reply
