### ISSUE TITLE
ACL Policies wildcard usage at odds with the Idiomatic Unix glob pattern usage

### ISSUE THREAD

**Issue by RoopGuron** [hashicorp/vault#13319]
**Feature Request:**
Comment on the **_ACL Policies path pattern/wildcard design_** 
It is quite **_counter Intuitive and not aligned_** with the most accepted path regex pattern semantics espoused by the Unix [GLOB](https://en.wikipedia.org/wiki/Glob_(programming))

**Environment:**
* Vault Version: 1.9.0
* Operating System/Architecture: Alpine Linux Docker Container on K8s
* 
* I did find [HashiCorp’s glob usage](https://www.vaultproject.io/docs/concepts/policies) at odds with what is the accepted and prevalent glob behavior in most implementations( Python,Java and Unix/Linux)
--------------------------------------------------------------------------------------------------------
**Basic Globbing - Globbing cheatsheet**
```
Character Description
* Matches any character zero or more times, except for /
** Matches any character zero or more times, including /
? Matches any character except for / one time
[abc] Matches any characters inside the brackets. For example, [abc] would match the characters a, b or c, and nothing else.
Notes:

* typically does not match dotfiles (file names starting with a .) unless explicitly enabled by the user via options
? also typically does not match the leading dot
More than two stars in a glob path segment are typically interpreted as a single star (e.g. /***/ is the same as /*/)
```
https://docs.python.org/3/library/glob.html is aligned to the summary above and so is Java, looking at a build files for subdirectories under path: **/*.java in ant files

that begs the question why would HashiCorp not align their path pattern matching to glob accepted semantics?
for instance in HashiCorp, 

```
secret/data/test/* would match secret/data/test/one, secret/data/test/one/tester and secret/data/test/two
Also,
secret/data/test* would match secret/data/testtwo, secret/data/test/two, secret/data/test-one but not secret/data/tes/one

```

And their use of + in path based patterns(which is not a glob token)
NonPlussed and Counter Intuitive implementation to say the least.

Thanks

**Comment by ncabatoff** [comment]
Hi @RoopGuron,

This is indeed counter-intuitive, unfortunately.  However, we didn't want traditional regex or glob semantics for this use case: they weren't the right fit for the functionality we wanted to offer.  And we were constrained as to what symbols were available to use: we had to use symbols that couldn't exist already in paths, we wanted them to be ASCII rather than weird unicode symbols, and that really didn't leave many options.

Sorry, it's just one of those things you're going to have to get used to when working with Vault.
