### ISSUE TITLE
vault with v1.9.0 - 1.8.5

### ISSUE THREAD

**Issue by maugomez77** [hashicorp/vault#13317]
**Describe the bug**
hey there

when running my project with v1.9.0 till v1.3.10

is complaining about this part: 

 go mod tidy

go: github.com/hashicorp/vault@v1.9.0 requires

	github.com/hashicorp/vault/api/auth/approle@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

go: github.com/hashicorp/vault@v1.9.0 requires

	github.com/hashicorp/vault/api/auth/approle@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

and if i want to build with 1.8.5:

go build 

golang.org/x/net/http/httpguts

github.com/hashicorp/vault/sdk/helper/parseutil

github.com/hashicorp/go-cleanhttp

github.com/gorilla/mux

github.com/spf13/afero

symantec/ams/src/log

golang.org/x/net/http2

github.com/hashicorp/go-retryablehttp

symantec/ams/src/gc

symantec/ams/src/db

github.com/spf13/viper

symantec/ams/src/api

symantec/ams/src/router

golang.org/x/net/http2/h2c

github.com/hashicorp/vault/api

github.com/hashicorp/vault/command/agent/auth

# github.com/hashicorp/vault/command/agent/auth

../../go/pkg/mod/github.com/hashicorp/vault@v1.8.5/command/agent/auth/auth.go:211:16: clientToUse.AddHeader undefined (type *api.Client has no field or method AddHeader)

Any fix for this ?

**Comment by hsimon-hashicorp** [comment]
This was fixed today in https://github.com/hashicorp/vault/pull/13321. Thanks!

**Comment by maugomez77** [comment]
Perfect, thanks

Any idea when this will be released?

Thanks.

**Comment by hsimon-hashicorp** [comment]
@maugomez77 To the best of my understanding, this should be an immediate change if you pull in the changes from the `main` branch. Let me know if you have issues. :)

**Comment by dieterdemeyer** [comment]
We’re also experiencing issues with this.
Any idea when we can expect a new version tag to have this change ?
We prefer to use go modules with specific release tags instead of the main branch.

**Comment by maugomez77** [comment]
now when i run like this: 

github.com/hashicorp/vault a06ac651c3fe896cc5dacb1352ae76ab605fb418


is show up this one:
go: finding module for package github.com/hashicorp/vault/sdk/helper/roottoken
symantec/ams/src/vault imports
	github.com/hashicorp/vault/command/agent/auth tested by
	github.com/hashicorp/vault/command/agent/auth.test imports
	github.com/hashicorp/vault/vault imports
	github.com/hashicorp/vault/sdk/helper/roottoken: module github.com/hashicorp/vault/sdk@latest found (v0.3.0), but does not contain package github.com/hashicorp/vault/sdk/helper/roottoken

**Comment by jeffwidman** [comment]
I can replicate the above error even when I pull in the specific commit that includes the fix for #13321:
```
$ go get  github.com/hashicorp/vault@4339cfa37173a3400eb230ede702714929324a50
...
github.com/hashicorp/vault imports
	github.com/hashicorp/vault/command imports
	github.com/hashicorp/vault/sdk/helper/roottoken: cannot find module providing package github.com/hashicorp/vault/sdk/helper/roottoken
```

So looks like there's currently no workable commit that fixes this issue w/o encountering a new issue that breaks the dep tree.

**Comment by askmike1** [comment]
The latest released version does not yet have this fix: https://github.com/hashicorp/vault/blob/v1.9.2/go.mod#L117-L118

**Comment by aabouzaid** [comment]
This issue should be opened again since it's not really resolved.

**Comment by hsimon-hashicorp** [comment]
> This issue should be opened again since it's not really resolved.

Can you please provide more information?

**Comment by aabouzaid** [comment]
> Can you please provide more information?

@hsimon-hashicorp It's exactly this:

> The latest released version does not yet have this fix: https://github.com/hashicorp/vault/blob/v1.9.2/go.mod#L117-L118

The `v1.9.2` still uses the invalid version.

**Comment by jeffwidman** [comment]
@aabouzaid It was fixed in https://github.com/hashicorp/vault/issues/13528 via https://github.com/hashicorp/vault/pull/13580 so will arrive in the next `1.9.x` release (likely `1.9.3`).
