### ISSUE TITLE
download vault v1.8.4

### ISSUE THREAD

**Issue by maugomez77** [hashicorp/vault#13331]
hey there

go version go 1.13 linux/amd64

go.mod: 
-----------------

module symantec/ams

go 1.17

require (
	github.com/hashicorp/vault v1.8.5
)

-----------------

when downloading one of the vault libraries is pop up this error:

go: finding golang.org/x/crypto v0.0.0-20210513164829-c07d793c2f9a
go: finding github.com/mattn/go-colorable v0.1.11
build symantec/ams: cannot load github.com/hashicorp/vault/api: unzip /root/go/pkg/mod/cache/download/github.com/hashicorp/vault/@v/v1.8.4.zip: malformed file path "website/pages/api-docs/[[...page]].jsx": double dot

any idea what might be ?

regards.

**Comment by Vinayaks439** [comment]
Even I faced the same issue with this module but when I upgraded my go version from `1.13.7` to  `go1.17.6 linux/amd64`, it was resolved. Please try with go v1.17.6.

**Comment by maxb** [comment]
This is a known defect in older Go versions - according to https://github.com/golang/go/issues/27299 it was fixed in Go 1.14.

**Comment by hsimon-hashicorp** [comment]
@maxb, you're officially my MVP today. Thank you again. :)
