### ISSUE TITLE
latest main vault with issue

### ISSUE THREAD

**Issue by maugomez77** [hashicorp/vault#13333]
when running my project with vault: 

go 1.17

require (
	github.com/hashicorp/vault a06ac651c3fe896cc5dacb1352ae76ab605fb418
)

is complaning about this: 

go: finding module for package github.com/hashicorp/vault/sdk/helper/roottoken
symantec/ams/src/vault imports
	github.com/hashicorp/vault/command/agent/auth tested by
	github.com/hashicorp/vault/command/agent/auth.test imports
	github.com/hashicorp/vault/vault imports
	github.com/hashicorp/vault/sdk/helper/roottoken: module github.com/hashicorp/vault/sdk@latest found (v0.3.0), but does not contain package github.com/hashicorp

**Comment by raskchanky** [comment]
Hi @maugomez77 

Are you still having this problem? Is there any further documentation you can provide about the structure of your project or what commands you're running?

I tried to reproduce this by creating a new go.mod file using:

```go
go 1.17

require (
  github.com/hashicorp/vault a06ac65
)
```

I ran `go mod tidy` and then was able to build everything with no errors. Any additional information you can provide would be helpful. Alternatively, if this is no longer an issue for you, feel free to close this. Thanks!

**Comment by HridoyRoy** [comment]
Closing this issue, please feel free to reopen with a comment if it requires additional investigation.
Thanks!
