### ISSUE TITLE
how to hide 8200 port form fqdn or public ip

### ISSUE THREAD

**Issue by san6789** [hashicorp/vault#13346]
is there amy why i can hide the vault port number 8200 from my fqdn or my vm ip .

please let me know to hide

**Comment by hsimon-hashicorp** [comment]
Hi! This may be a question better suited for the discuss forum, as it is not a bug: https://discuss.hashicorp.com/c/vault/30
That being said, you may wish to use a network ACL / security group or a firewall to limit who has access to the port, but it can't be "hidden".
