### ISSUE TITLE
Add certificate extensions as metadata

### ISSUE THREAD

**Issue by peterverraedt** [hashicorp/vault#13347]
**Is your feature request related to a problem? Please describe.**
I'm running a configuration management tool (puppet) on ~1000 nodes in a decentralized manner, and each node needs access to vault, limited to a number of scopes depending on the node properties (role such as webserver/compute node/..., hostname, ...). The number of nodes and the set of possible "roles" changes regularly, and I want rather static vault policies based on identity metadata.

This is currently partially possible by using the puppet host certificates combined with the cert authentication method: the certificate name, common name and serial number are already available as identity metadata and can be used in policy templates. This means that I can already create a policy that restricts read access to paths in vault containing the hostname (= certificate common name) as a variable. However, I would need more key value metadata retrieved from the certificate to work efficiently.

**Describe the solution you'd like**
All certificate ASN1 extensions should be added as key/value pairs in the metadata.

**Describe alternatives you've considered**
Creating a single approle role and different secret_id's for each host, with metadata, but I ran into #11798. Creating a role_id per host is too dynamic and would require manually creating policies and assignments, when my set of host "roles" grows. 

**Explain any additional use-cases**
Any situation where certificates carry embedded metadata as ASN1 extensions, would benifit from the possibility to use it in vault policy templating.

**Comment by pmmukh** [comment]
Hey @peterverraedt ! Thanks for submitting this feature request and the linked PR, the ask makes sense and the solution looks to be on the right path! :) The only major concern we have with the approach, is that it might lead to large amounts of metadata getting added to entities and thus eating up disk space, leading to performance problems. One solution we've thought of for that problem, is to make this functionality opt-in, and also to be more explicit about which extensions to add into the entity_metadata. 
We think that adding a field to https://www.vaultproject.io/api-docs/auth/cert#create-ca-certificate-role specifying the valid extension Ids to add , and checking the cert extensions against this list when logging in with the certificate, adding only those extensions that were explicitly requested, would make sense. The list would be an optional argument, so for anyone not specifying it when creating the cert role, the entity metadata would be populated as it is today. Please let me know how that addition to the approach sounds to you!

**Comment by peterverraedt** [comment]
Thanks for the feedback, @pmmukh . I've updated the PR to include a `metadata_extensions` field in the role configuration.

**Comment by voiprodrigo** [comment]
@peterverraedt can you please provide an example of policy template using certificate metadata, like CN? I've tried templating with `{{identity.entity.aliases.__ACCESSOR__.metadata.common_name}}` but it doesn't work. It does work if I use `{{identity.entity.aliases.__ACCESSOR__.name}}`, but that does not make sense to me. Thanks!

**Comment by h4l** [comment]
@voiprodrigo (or anyone else looking for this) you probably need to enable the [`enable_identity_alias_metadata` option](https://developer.hashicorp.com/vault/api-docs/auth/cert#enable_identity_alias_metadata):
```console
# vault write auth/cert/config enable_identity_alias_metadata=true
```

Without this enabled, the entity alias created when authenticating does not contain the metadata, so the ACL template can't populate it. Verify the alias is populated correctly by reading its alias data from `identity/entity-alias/id/<id>`:

```console
# vault read identity/entity-alias/id/7fb503bd-5039-df91-a5fd-c83ba1b8a1fa
Key                          Value
---                          -----
canonical_id                 e25fd73a-51c1-c723-f363-2f92bafef24a
creation_time                2023-03-01T14:42:18.073514135Z
custom_metadata              <nil>
id                           7fb503bd-5039-df91-a5fd-c83ba1b8a1fa
last_update_time             2023-03-01T14:42:18.073514135Z
local                        false
merged_from_canonical_ids    <nil>
metadata                     map[1-3-6-1-4-1-34380-1-1-8:super-db authority_key_id: cert_name:testbed common_name:db1.superapp.example.local serial_number:119173039740046606856485670279679599198664210762 subject_key_id:]
mount_accessor               auth_cert_f67089d9
mount_path                   auth/cert/
mount_type                   cert
name                         db1.superapp.example.local
namespace_id                 root
```
(You can find the entity-alias ID by `vault token lookup <token>` to find the token's `entity_id`, then read the entity via that id from `identity/entity-alias/id/<id>`, the entity-alias id will be in the entity metadata.)

If you can see the metadata there, the policy template can reference it like any normal entity alias metadata, e.g:

```hcl
path "secret/data/app/{{identity.entity.aliases.${cert_mount_accessor}.metadata.1-3-6-1-4-1-34380-1-1-8}}" {
    capabilities=["read","list"]
}
```

**Comment by redat00** [comment]
Hi everyone ! 

Hate to be that guy who just dig up very old conversation but I'm really struggling in setting up a policy that would use the `common_name` of a certificate. 

I've tried every syntax I could find but in the end none has seem to be working as expected. 

My question is more targeted for @h4l : In your example of policy, how is the `${cert_mount_accessor}` variable defined ? In my case, it seems to not be working at all.. And I'm starting to think that I'm missing something !

I'm trying to have a policy that would allow the access to a folder, where the name of the folder is the `common_name` value of a certificate (in my case a Puppet issued certificate). 

Thanks in advance for any help !

**Comment by redat00** [comment]
So, after a good night of sleep I was able to get my head straight to work on this !

Putting this in here for anyone like me who's trying to set up a similar environment.

Turns out the `mount accessor` can't really be put in place dynamically within Vault policies, you have to give the actual ID. 

The only way to do this (AFAIK, and I think that is what's done for the example above) is by configuring Vault with Terraform, you would then be able to use the resource `vault_auth_backend` [accessor attribute](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/auth_backend#accessor).
