### ISSUE TITLE
Azure Rotate Root: unsupported path

### ISSUE THREAD

**Issue by iusergii** [hashicorp/vault#13349]
**Describe the bug**
Rotate Root [API](https://www.vaultproject.io/api/secret/azure#rotate-root) fails with unsupported path error massage. 

**To Reproduce**
```bash
vault write azure/config \            
    subscription_id=xyz \
    tenant_id=xyz \
    client_id=xyz \
    client_secret=xyz \
    use_microsoft_graph_api=true

curl \
  --header "X-Vault-Token: s.xyzm" \
  --request POST \
  https://127.0.0.1:8200/v1/azure/rotate-root
{"errors":["1 error occurred:\n\t* unsupported path\n\n"]}
```

**Additional context**
Version v1.8.1

**Comment by kalafut** [comment]
Hi @iusergii. Azure rotate-root was just recently [added in Vault 1.9](https://github.com/hashicorp/vault/pull/13034), so please give that a try. Better clarity in docs of when features are added is definitely something we're looking into.

**Comment by iusergii** [comment]
@kalafut  Thank you!
