### ISSUE TITLE
Please cleanup stale github branches

### ISSUE THREAD

**Issue by jeffwidman** [hashicorp/vault#13356]
There's a ton of stale orphaned/outdated git branches listed here: https://github.com/hashicorp/vault/branches

Maybe cleanup some of them? Especially the ones that were merged and have 0 commits diverging, but never got cleaned up?

**Comment by hsimon-hashicorp** [comment]
Hi there! Is this causing you problems in your ability to contribute? We do try to tidy things up pretty regularly, but if it's blocking you, please do let me know. Thanks! :)

**Comment by jeffwidman** [comment]
It slowed me down last week when I was trying to research why something was the way it was, and whether I should submit a fix or not. So not blocking, but a subpar experience.

> We do try to tidy things up pretty regularly

I appreciate the sentiment, but looking at https://github.com/hashicorp/vault/branches/stale, I see multiple stale branches that are 4-6 years old...

**Comment by hsimon-hashicorp** [comment]
Thanks for the feedback! We have found value in leaving old branches in place from time to time, as it can provide useful context around changes for folks who are newer to the codebase. We'll have a discussion with leadership on how we can balance the two viewpoints in the future. :)
