### ISSUE TITLE
API/UI returns error when trying to login with a username that ends in a period "."

### ISSUE THREAD

**Issue by firstdorsal** [hashicorp/vault#13353]
**Describe the bug**

API/UI returns error when trying to login with a username that ends in a period "."
This happens in the UI/API when trying to login with the userpass method.
If the username is `test.` it returns the error `unsupported path`
this also happens when creating it manually like that: 
`http://127.0.0.1:8200/v1/auth/userpass/users/test.` -> `1 error occurred: * unsupported path` and for some reason 404

I can create these userpass accounts by first creating an entity.
then an userpass account.
then an alias connecting both.

your documentation is saying that it supports userpass accounts like that:
*The username for the user. Accepted characters: alphanumeric plus "_", "-", "." (underscore, hyphen and period); username cannot begin with hyphen or period.*
https://www.vaultproject.io/api/auth/userpass#parameters

The same is true when creating a transit encryption key.

**archlinux/docker/x86/latest**

**Comment by hsimon-hashicorp** [comment]
Hi @firstdorsal! Can you confirm what version of Vault you're seeing this bug with? Thanks! :)

**Comment by firstdorsal** [comment]
Vault v1.8.5 (647eccfe0bd5817bdd8628f3c3171402dfc8a8fc)

**Comment by arnav28** [comment]
Hi @firstdorsal 
Thanks for pointing this out. After discussing with our team, we will be updating docs to notify that no path parameters can begin or end with period.
