### ISSUE TITLE
vault cli `-output-curl-string` does not include client cert info

### ISSUE THREAD

**Issue by bmendric** [hashicorp/vault#13376]
**Environment:**
* Vault Version: 1.8.4, 1.8.5, 1.9.0
* Operating System/Architecture: Ubuntu 18.04 x86_64

**Expected Behavior:**

Performing the following command:
  `vault login -method=cert -address=https://localhost:1234 -client-cert=client.crt -client-key=client.key -output-curl-string`
should result in the curl command:
  `curl -X PUT -H "X-Vault-Request: true" -d '{"name":""}' --cert ./client.crt --key ./client.key https://localhost:1234/v1/auth/cert/login`

**Actual Behavior:**

Performing the following command:
  `vault login -method=cert -address=https://localhost:1234 -client-cert=client.crt -client-key=client.key -output-curl-string`
should result in the curl command:
  `curl -X PUT -H "X-Vault-Request: true" -d '{"name":""}' https://localhost:1234/v1/auth/cert/login`

**Steps to Reproduce:**

See above commands; only need validly PEM encoded crt and key files to test

**References:**

- https://www.vaultproject.io/api-docs/auth/cert#login-with-tls-certificate-method
- https://www.vaultproject.io/docs/auth/cert#via-the-cli
- https://www.vaultproject.io/docs/auth/cert#via-the-api

**Comment by hsimon-hashicorp** [comment]
@bmendric This should be good to start, we'll let you know if we have questions. :)

**Comment by remilapeyre** [comment]
Thanks for reporting this @bmendric, this was also affecting other commands like `vault read`, `vault write` and `vault delete`.
