### ISSUE TITLE
Using Go API to write Secrets/Cubbyhole

### ISSUE THREAD

**Issue by frodopwns** [hashicorp/vault#1338]
Hello

I am using the code in api/ (https://github.com/hashicorp/vault/blob/master/api/logical.go) to write values to secret/*.  

When I use this same code to write to cubbyhole/* I am running into problems where i dont get errors when writing the cubbyhole secret but cant seem to read anything back.

Could anyone suggest some reasons why this might be the case?  I am using github auth tokens if that helps at all. eg https://gist.github.com/frodopwns/05022429594318cf2e86a413ed2b4b13

Thanks

**Comment by jefferai** [comment]
Hi there,

I don't actually see any write in that code? What is the actual code that is not working where you are writing a value in and reading it out?

Thanks!

**Comment by frodopwns** [comment]
importing these:
	"github.com/hashicorp/vault/api"
	"github.com/hashicorp/vault/builtin/credential/github"

assume pathArg is something like "cubbyhole/test"

```go
	vaultCFG := *api.DefaultConfig()
	vaultCFG.Address = "https://vault_url:8200"

	var err error
	vClient, err = api.NewClient(&vaultCFG)
	if err != nil {
		log.Fatal(err)
	}

	// get user data so we can find their dotfiles
	usr, err = user.Current()
	if err != nil {
		log.Fatal("Could not find user's homedir")
	}

	gitToken := os.Getenv("GITHUB_TOKEN")
	if gitToken == "" {
		log.Fatal("You must set a GITHUB_TOKEN env var")
	}

	mountInput := map[string]string{
		"mount": "github",
		"token": gitToken,
	}

	cliHandler := github.CLIHandler{}
	var cTok string
	cTok, err = cliHandler.Auth(vClient, mountInput)
	if err != nil {
		log.Fatalln("Error while authenticating with vault.", err)
	}
	vClient.SetToken(cTok)
	vault = *vClient.Logical()

        secret := make(map[string]interface{})
        secret["value"] = "test secret"

        _, err = vault.Write(pathArg, secret)
	if err != nil {
		log.Fatal(err)
	}
```

Works with no error but then when i do 

```go
		s, err := vault.Read(pathArg)
		if err != nil {
			log.Fatal(err)
		}
```

s is nil

**Comment by frodopwns** [comment]
Also I have the root policy mapped to my github team

**Comment by jefferai** [comment]
I simplified your test case a bit and can't replicate it:

```go
package main

import (
        "log"

        "github.com/hashicorp/vault/api"
)

func main() {
        pathArg := "cubbyhole/mysecret"

        vaultCFG := api.DefaultConfig()
        vaultCFG.Address = "http://127.0.0.1:8200"

        var err error
        vClient, err := api.NewClient(vaultCFG)
        if err != nil {
                log.Fatal(err)
        }

        vClient.SetToken("7269298c-1542-8bad-ade8-6c11402da30e")
        vault := vClient.Logical()

        secret := make(map[string]interface{})
        secret["value"] = "test secret"

        _, err = vault.Write(pathArg, secret)
        if err != nil {
                log.Fatal(err)
        }

        s, err := vault.Read(pathArg)
        if err != nil {
                log.Fatal(err)
        }
        if s == nil {
                log.Fatal("secret was nil")
        }

        log.Printf("%#v", *s)
}
```

Running, I get: 

```
$ go run main.go 
2016/04/20 18:45:08 api.Secret{LeaseID:"", LeaseDuration:0, Renewable:false, Data:map[string]interface {}{"value":"test secret"}, Warnings:[]string(nil), Auth:(*api.SecretAuth)(nil)}
```

Also, you generally never want to map root tokens to _anyone_, especially in production. Root tokens can do *anything* in Vault.

**Comment by frodopwns** [comment]
So if I run this

```go
package main

import (
	"log"
	"os"

	"github.com/hashicorp/vault/api"
	"github.com/hashicorp/vault/builtin/credential/github"
)

func main() {
	pathArg := "cubbyhole/mysecret"

	vaultCFG := api.DefaultConfig()
	vaultCFG.Address = "https://sanctuary.url.com:8200"

	var err error
	vClient, err := api.NewClient(vaultCFG)
	if err != nil {
		log.Fatal(err)
	}

	gitToken := os.Getenv("GITHUB_TOKEN")
	if gitToken == "" {
		log.Fatal("You must set a GITHUB_TOKEN env var")
	}

	mountInput := map[string]string{
		"mount": "github",
		"token": gitToken,
	}

	cliHandler := github.CLIHandler{}
	var cTok string
	cTok, err = cliHandler.Auth(vClient, mountInput)
	if err != nil {
		log.Fatalln("Error while authenticating with vault.", err)
	}
	vClient.SetToken(cTok)

	//vClient.SetToken("7269298c-1542-8bad-ade8-6c11402da30e")
	vault := vClient.Logical()

	secret := make(map[string]interface{})
	secret["value"] = "test secret"

	_, err = vault.Write(pathArg, secret)
	if err != nil {
		log.Fatal(err)
	}

	s, err := vault.Read(pathArg)
	if err != nil {
		log.Fatal(err)
	}
	if s == nil {
		log.Fatal("secret was nil")
	}

	log.Printf("%#v", *s)
}

```

I get 

```
➜  src go run testv.go
2016/04/20 14:21:35 api.Secret{LeaseID:"", LeaseDuration:0, Renewable:false, Data:map[string]interface {}{"value":"test secret"}, Warnings:[]string(nil), Auth:(*api.SecretAuth)(nil)}
```

But if I then comment out this part

```
	// secret := make(map[string]interface{})
	// secret["value"] = "test secret"
	//
	// _, err = vault.Write(pathArg, secret)
	// if err != nil {
	// 	log.Fatal(err)
	// }
```

I get

```
➜  src go run testv.go
2016/04/20 14:23:30 secret was nil
exit status 1
```

Shouldn't the secret still be there from the last run? Or is there something about cubbyhole I don't understand here?

**Comment by frodopwns** [comment]
Is it possible that the github authenticating is resulting in a token that changes and thus sets up a new cubbyhole?

**Comment by frodopwns** [comment]
This does appear to be the issue:

```
/ # vault auth -method=github token=my_github_token
Successfully authenticated!
token: some_token1
token_duration: 0
token_policies: [root]
/ # vault write cubbyhole/testme name=bob
Success! Data written to: cubbyhole/testme
/ # vault read cubbyhole/testme
Key 	Value
name	bob
/ # vault auth -method=github token=my_github_token
Successfully authenticated!
token: some_token2
token_duration: 0
token_policies: [root]
/ # vault read cubbyhole/testme
No value found at cubbyhole/testme
```

I assume this is expected?

**Comment by jefferai** [comment]
Absolutely. Cubbyhole's storage is scoped per token. You cannot access another token's cubbyhole and it is destroyed when the token is revoked.

**Comment by frodopwns** [comment]
So I guess cubbyhole is useless to people using github auth.

Thanks for helping me figure this one out.

**Comment by jefferai** [comment]
@frodopwns Cubbyhole is useful for a certain set of operations, regardless of where the token comes from, and behaves the same way regardless of origin. I'm not really sure what you were trying to achieve, but if you want to elaborate then maybe I can provide some guidance.

**Comment by frodopwns** [comment]
I want Cubbyhole secrets that apply to github token instead of whatever session specific token that maps to.  That would allow me to provide personal secret space to anyone on a github team I have given access.

**Comment by jefferai** [comment]
Hi,

No two authentications to Vault, regardless of auth backend, will ever produce the same Vault token. If you want to share a cubbyhole space, simply have one person create a token and share that with your team.

**Comment by frodopwns** [comment]
Well i told you how I would like it to work.  If vault can't do that its no big deal.  Maybe something you guys can fix in the future.

**Comment by jefferai** [comment]
@frodopwns It's not anything to fix, really; Vault doesn't and won't tie internal resources to tokens generated externally. You *cannot* be secure by doing this; Vault provides security in part by having tight control over authentication and authorization.

If you want to have a space destined for your team, but not tied to a particular Vault token, you can use a `generic` mount or a part of a mount (like a sub-path in `secret`) and have a policy that gives access to that area assigned to any Vault token generated with your GitHub token.

**Comment by frodopwns** [comment]
Sure but if we were to make it work the way I want it to then it would need to be fixed or improved if you prefer ;-).

But I can see you are sticking with the "Works as designed" line so I think we can drop this issue at this point.

**Comment by jefferai** [comment]
@frodopwns It's less "works as designed" and more "I think you can already do what you want just in a slightly different way"  :-)  Using policies you can have an area walled off for your team in a non-cubbyhole generic mount, where anyone with either the same GitHub token or appropriate GH organization/team membership can access it, and nobody else can.

**Comment by frodopwns** [comment]
@jefferai sure but can I make a generic secret mount per user without having to create a github team for every user?

**Comment by jefferai** [comment]
You can map policies to teams in GitHub. That's the only level of granularity currently offered. But I don't understand why this would be an issue, since you said that you're sharing the GH token around with many users. In that case you just need one GH team.

**Comment by frodopwns** [comment]
No that is not the case.  Each user generates their own Github token and that is used to authenticate with our instance of Vault.

**Comment by frodopwns** [comment]
This was happening because I was re-authenticating via github every time I accessed vault rather than saving the token that gets created at the time of auth.  Misunderstanding on my part.

Thanks

**Comment by jefferai** [comment]
Glad it's solved.
