### ISSUE TITLE
How to config vault policy for cert authentication access?

### ISSUE THREAD

**Issue by linuxbee** [hashicorp/vault#1339]
I am trying to configure a vault policy for certificate authentication access. However, the following configuration does not seem to work -- producing permission denied message. Can you please provide some help?

my_policy.conf:
===============
path "sys" { policy="deny" }
path "auth/token/revoke-self" { policy="write" }
path "secret/myapp" { policy="read" }

vault commands:
===============
vault policy-write myapp my_policy.conf
vault write auth/cert/certs/myapp policies=myapp certificate=@myapp_cert.pem

I tried to login the vault to access/read the secret/myapp section in the Java code, but I got the error message:

04/19/2016 00:53:49,988  WARN main client.RestTemplate:608 - GET request for "https://127.0.0.1:8001/v1/secret/myapp” resulted in 403 (Forbidden); invoking error handler

On the other hand, I used the curl command to do the same thing, but it results in the same error:

curl -v -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Vault-Token: fcb79f84-7164-ac3b-3545-7d1fe77b050e" --cacert CACert.pem --cert myapp.p12:mypassword https://127.0.0.1:8001/v1/secret/myapp

*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8001 (#0)
* WARNING: SSL: Certificate type not set, assuming PKCS#12 format.
* Client certificate: MyApp Certificate
* WARNING: using IP address, SNI is being disabled by the OS.
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
* Server certificate: Vault Certificate
* Server certificate: Intermediate CA Certificate
> POST /v1/secret/myapp HTTP/1.1
> Host: 127.0.0.1:8001
> User-Agent: curl/7.43.0
> Content-Type: application/json
> Accept: application/json
> X-Vault-Token: fcb79f84-7164-ac3b-3545-7d1fe77b050e
> 
< HTTP/1.1 403 Forbidden
< Content-Type: application/json
< Date: Tue, 19 Apr 2016 07:42:28 GMT
< Content-Length: 33
< 
{"errors":["permission denied"]}
* Connection #0 to host 127.0.0.1 left intact

What went wrong in this policy configuration? Also what is the certificate parameter in the “vault write” command line? I tried either the myapp cert or the intermediate cert, but neither one works.

vault write auth/cert/certs/myapp policies=myapp certificate=@myapp_cert.pem
or 
vault write auth/cert/certs/myapp policies=myapp certificate=@intermediate_ca.pem

**Comment by jefferai** [comment]
Does your token actually have the `myapp` policy attached to it (if you do an `auth/token/lookup-self` call on it)?

The `certificate` parameter is for the CA cert that issued your client certificate.

One other comment: the block `path "sys" { policy="deny" }` won't do anything other than block access to `sys` exactly. You probably want to use `path "sys/*" { policy="deny" }`

**Comment by linuxbee** [comment]
It looks like that the myapp policy is not attached to the token:

$ vault read auth/token/lookup-self
Key          	Value
accessor     	ed6c2cb1-8e06-d718-db8a-0ff4dcdef351
creation_time	1.460987802e+09
creation_ttl 	0
display_name 	root
id           	fb4bfb0f-3038-287e-0c53-2084a8a5970a
meta         	<nil>
num_uses     	0
orphan       	true
path         	auth/token/root
policies     	[root]
role         	
ttl          	0
$ 

So what should I have done to get the mayor policy attached to the token?

**Comment by jefferai** [comment]
How did you acquire the token? Did you get any errors during login?

**Comment by jefferai** [comment]
Wait, it's a root token. So it seems like you never actually logged in after configuring it.

Did you actually write a secret to `secret/myapp`?

**Comment by linuxbee** [comment]
Yes, I did login first to acquire the token in my Java code. I successfully got the token by the login API with the myapp key/cert credential.

1. First API to login and get a token:

#### DEBUG auth: {"accessor":"93871d84-4f3b-1141-e349-5f2a23f83c90","client_token":"fcb79f84-7164-ac3b-3545-7d1fe77b050e","lease_duration":2592000,"renewable":true,"policies”:[“my_policy","default"],"metadata":{"authority_key_id":"b0:52:bc:d4:39:74:f8:8f:55:65:cd:35:de:aa:45:25:ed:0b:c4:ab","cert_name”:”myapp”,”common_name”:”App Certificate", "subject_key_id”:”33:24:ce:64:28:77:67:ec:22:3e:b3:69:22:d4:d2:4c:e7:17:b4:ab"}}
#### DEBUG vault token: fcb79f84-7164-ac3b-3545-7d1fe77b050e
#### DEBUG getKey: GET https://127.0.0.1:8001/v1/secret/myapp

2. Second API call to retrieve data from secret/myapp, but failed:

callAPI - GET https://127.0.0.1:8001/v1/secret/myapp, token: fcb79f84-7164-ac3b-3545-7d1fe77b050e

04/19/2016 00:53:49,988  WARN main client.RestTemplate:608 - GET request for "https://127.0.0.1:8001/v1/secret/myapp" resulted in 403 (Forbidden); invoking error handler

I had previously populated secret/myapp, and the data are there:

$ vault read secret/myapp
Key                             	Value
lease_duration                  	2592000
data.enabled            	        true
data2                			value2
…… <snip >……

**Comment by jefferai** [comment]
Does the `vault read` work correctly when using the generated token?

**Comment by linuxbee** [comment]
Hmmm... Great question.

The previous vault cli login (using root token) allows to show vault read secret/myapp. 

However, if I use the Java code generated token from the first API call to login, and then do the cli vault read secret/myapp, it also does fail. So the token generated from Java is consistent with the cli in failing to read secret/myapp.

Details:

* Successful cli login using token from Java code:
$ vault auth 6277e6db-df9e-03f8-ea56-c3e5e3fa6e56
Successfully authenticated!
token: 6277e6db-df9e-03f8-ea56-c3e5e3fa6e56
token_duration: 2591950
token_policies: [myapp, default]

* Failed cli read after login with Java generated token:
$ vault read secret/myapp
Error reading secret/myapp: Error making API request.

URL: GET http://127.0.0.1:8200/v1/secret/myapp
Code: 403. Errors:

* permission denied

**Comment by jefferai** [comment]
I can't replicate this:

```
$ cat poltest.hcl 
path "sys" { policy="deny" }
path "auth/token/revoke-self" { policy="write" }
path "secret/myapp" { policy="read" }

$ vault policy-write myapp poltest.hcl
Policy 'myapp' written.

$ vault write secret/myapp foo=bar
Success! Data written to: secret/myapp

$ vault token-create -policy=myapp
Key             Value
token           6185a3dc-0841-4c7b-5b7e-f9dc13dcd586
token_accessor  7a4424bc-cb0b-8e61-65f0-e15aecaebb9f
token_duration  2592000
token_renewable true
token_policies  [default myapp]

# Show that an invalid token has an effect
$ VAULT_TOKEN="a" vault read secret/myapp
Error reading secret/myapp: Error making API request.

URL: GET http://127.0.0.1:8200/v1/secret/myapp
Code: 403. Errors:

* permission denied

$ VAULT_TOKEN="6185a3dc-0841-4c7b-5b7e-f9dc13dcd586" vault read secret/myapp
Key             Value
lease_duration  2592000
foo             bar
```

What version of Vault are you using?

**Comment by linuxbee** [comment]
$ vault -version
Vault v0.5.2


Using the Java generated token, I could not see the “vault policies” either, but “vault status” is OK.

$ vault policies
Error: Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/policy
Code: 403. Errors:

* permission denied

$ vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: active
	Leader: https://127.0.0.1:8501


Note that using root token to login again, the “vault policies” works well. I re-login with root token, and there is the “vault policies”:

$ vault auth fb4bfb0f-3038-287e-0c53-2084a8a5970a
Successfully authenticated!
token: fb4bfb0f-3038-287e-0c53-2084a8a5970a
token_duration: 0
token_policies: [root]


$ vault policies
myapp
default
myapp2
myapp3
root

**Comment by linuxbee** [comment]
OK, I see you specified the policy while generating the token. 

$ vault token-create -policy=myapp

That's different from mine. I only use the myapp credential (key/cert) to successfully login and receive the generated token -- with specifying the policy name when login in the Java code. Do I somehow specify the policy name when login in the Java code? If that's the case, then it seems to beat the purpose of creating the policies in the vault backend with admin (root) preivileges.

**Comment by linuxbee** [comment]
Sorry -- WITHOUT specifying the policy when I login in the java code.

**Comment by jefferai** [comment]
When you use the certificate authentication backend, the policies to set on the token are controlled within the backend configuration.

Can you please try out the steps in my last post and see if you have the same result?

Thanks!

**Comment by linuxbee** [comment]
Hmmm... I could completely reproduce what you showed me:

$ cat poltest.hcl 
path "sys" { policy="deny" }
path "auth/token/revoke-self" { policy="write" }
path "secret/myapp" { policy="read" }

$ vault policy-write myapp poltest.hcl
Policy 'myapp' written.

$ vault write secret/myapp foo=bar
Success! Data written to: secret/myapp

$ vault token-create -policy=myapp
Key            	Value
token          	97b7adf0-ccb8-418c-feda-aa862881fc1c
token_accessor 	a7caac5d-ed90-b15a-30b4-5ddaad612f5a
token_duration 	2592000
token_renewable	true
token_policies 	[default myapp]

$ VAULT_TOKEN="a" vault read secret/myapp
Error reading secret/myapp: Error making API request.

URL: GET http://127.0.0.1:8200/v1/secret/myapp
Code: 403. Errors:

* permission denied

$ VAULT_TOKEN=97b7adf0-ccb8-418c-feda-aa862881fc1c vault read secret/myapp
Key           	Value
lease_duration	2592000
foo           	bar

$ 

So does that mean my version of myapp policy is not configured correctly? But it looks exactly the same as your test policy.

$ cat policy_myapp.conf
path "sys" { policy="deny" }
path "auth/token/revoke-self" { policy="write" }
path "secret/myapp" { policy="read" }

**Comment by linuxbee** [comment]
So if the token that I generate in the Java code needs to be somehow associated with a policy, how do I do that in the login API call?

**Comment by linuxbee** [comment]
If I use the same token generation step (associated with the policy name) that you showed me for another policy myapp2, then I could also read its own storage as expected.

$ vault token-create -policy=myapp2
Key            	Value
token          	558d3ca2-dde0-a3c6-5cec-bac3aaa15eb9
token_accessor 	9947743b-05a1-3fdb-d3aa-fd37bc9b4b6a
token_duration 	2592000
token_renewable	true
token_policies 	[default myapp2]

$ VAULT_TOKEN=558d3ca2-dde0-a3c6-5cec-bac3aaa15eb9 vault read secret/myapp2
Key                             	Value
lease_duration                  	2592000
app2var1                                value1
app2var2                                value2

So the question goes back to using the myapp key/cert credential to login, shouldn’t I be able to receive the token permitted for its own secret space?

**Comment by jefferai** [comment]
If you get a token from logging in via the cert auth backend and the token has the correct policy applied, then as you can see from the CLI test it should read that value just fine.

**Comment by linuxbee** [comment]
I have made some progress as shown below, but with some follow-up question.

The token generated from Java code login (with myapp key/cert credential) to vault’s myapp: b2308d24-b866-9526-43bb-9afed3c537ea
(Of course, when the Java code tries the second API to read secret/myapp with that token, it still failed.)

I then used that Java-generated token on the vault cli to “lookup-self”, and found that the token was actually generated by an old policy “oldapp” — that’s the reason why the Java code always fails at the second API when it tries to read secret/myapp, whereas the token only allows to read secret/oldapp.


$ VAULT_TOKEN=b2308d24-b866-9526-43bb-9afed3c537ea vault read auth/token/lookup-self
Key          	Value
accessor     	074ede89-164a-bf5f-b52f-9dceed17b686
creation_time	1.461182282e+09
creation_ttl 	2.592e+06
display_name 	cert-oldapp
id           	b2308d24-b866-9526-43bb-9afed3c537ea
meta         	map[authority_key_id:cb:64:bd:ec:40:69:e2:8f:d0:72:be:63:bc:43:74:e2:ed:0b:c4:ab cert_name:oldapp common_name:My App Certificate subject_key_id:42:b2:bf:50:14:66:67:ec:17:ee:a8:69:33:d4:d2:44:e7:17:a3:ab]
num_uses     	0
orphan       	true
path         	auth/cert/login
policies     	[oldapp default]
role         	
ttl          	2.590698e+06


Note that the “display_name cert-oldapp” and “policies [oldapp default]” in the output of the above lookup-self command point to the oldapp. However the “common_name:My App Certificate” is actually what I am using and need to use for the myapp login.

As a result of this mixup, the myapp key/cert credential (as shown in the “common_name” from the lookup-self) that I use to login always tied to the oldapp policy. That is the problem.

So my next question is: how to properly fix this mixup of the policies? 

I tried to remove the “oldapp” policy, but the myapp credential’s login still ties to the secret/oldpp.

vault policy-delete oldapp
Policy ‘oldapp' deleted.

I am not familiar with the internal working of the vault, and therefore don’t know exactly how to fix this problem so that the myapp credential can be tied to the myapp rather than oldapp.

**Comment by linuxbee** [comment]
Strangely, below is another piece of information that I found. I generated a new token with the myapp policy, and used that token to lookup-self. Compared to lookup-self from the token of oldapp, I found that for myapp:

* there is no “meta” field ( <nil> ) to link a cert_name to myapp policy (as opposed to a map of “common_name” and “cert_name” in oldapp). 
* the “path” field is only for the “auth/token/create” (as opposed to “auth/cert/login” in oldapp).
* the “display_name” field is “token” (a opposed to a cert name “cert-oldapp” in oldapp).

Here are the details (where I also marked "<== this is different."):

$ vault token-create -policy=myapp
Key            	Value
token          	0a2d616c-d0ef-48de-3afd-4a2d4062381f
token_accessor 	4452e47c-b6e0-4adc-3d78-36cabe0d083b
token_duration 	2592000
token_renewable	true
token_policies 	[default myapp]

$ VAULT_TOKEN=0a2d616c-d0ef-48de-3afd-4a2d4062381f vault read auth/token/lookup-self
Key          	Value
accessor     	4452e47c-b6e0-4adc-3d78-36cabe0d083b
creation_time	1.461191726e+09
creation_ttl 	2.592e+06
display_name 	token     <== this is different.
id           	0a2d616c-d0ef-48de-3afd-4a2d4062381f
meta         	<nil>     <== this is different.
num_uses     	0
orphan       	false
path         	auth/token/create     <== this is different.
policies     	[default myapp]
role         	
ttl          	2.591938e+06


I am following the same step to write the policy for myapp as I did for oldapp, but the results seem different for the two:

$ cat policy_oldapp.conf 
path "sys" { policy="deny" }
path "auth/token/revoke-self" { policy="write" }
path "secret/oldapp" { policy="read" }

vault policy-write oldapp policy_oldapp.conf
vault write auth/cert/certs/oldapp policies=oldapp certificate=cacert.pem

$ cat policy_myapp.conf 
path "sys" { policy="deny" }
path "auth/token/revoke-self" { policy="write" }
path "secret/myapp" { policy="read" }

vault policy-write myapp policy_myapp.conf
vault write auth/cert/certs/myapp policies=myapp certificate=cacert.pem

**Comment by linuxbee** [comment]
Here are some more finding. I deleted the myapp policy, and re-created a new policy for myapp. I then re-generated a token with this newly-generated policy. I used this token to lookup-self, and the result is still the same as before. However, if I read auth/cert/certs/myapp directly, it shows the updated cert info.


Below are the Details:
=======================

$ vault policy-delete myapp
Policy ‘myapp’ deleted.


$ cat policy_myapp.conf 
path "sys" { policy="deny" }
path "auth/token/revoke-self" { policy="write" }
path "secret/myapp” { policy="read" }


$ vault policy-write myapp policy_myapp.conf
Policy ‘myapp’ written.


$ vault write auth/cert/certs/myapp display_name=myapp_cert policies=myapp certificate=@CACert.pem
Success! Data written to: auth/cert/certs/myapp

$ vault token-create -policy=myapp
Key            	Value
token          	d4901970-f954-c734-11b2-426715f77ebb
token_accessor 	f815b042-ef62-98c1-8242-755037a80f2b
token_duration 	2592000
token_renewable	true
token_policies 	[default myapp]


$ VAULT_TOKEN=d4901970-f954-c734-11b2-426715f77ebb vault read auth/token/lookup-self
Key          	Value
accessor     	f815b042-ef62-98c1-8242-755037a80f2b
creation_time	1.461199488e+09
creation_ttl 	2.592e+06
display_name 	token
id           	d4901970-f954-c734-11b2-426715f77ebb
meta         	<nil>
num_uses     	0
orphan       	false
path         	auth/token/create
policies     	[default myapp]
role         	
ttl          	2.59198e+06


Note that the “display_name” is still "token" (not "myapp_cert" as expected), “meta” (<nil>) and “path”  (auth/token/create) are still the same as before (unchanged).

However, if I read the auth/cert/certs/myapp directly, I got the correct policy entry for “display_name” and “policies”:

$ vault read auth/cert/certs/myapp
-----BEGIN CERTIFICATE-----

… <snip the cert entry here> …

——END CERTIFICATE-----

display_name	myapp_cert
policies    	myapp
ttl         	2.592e+06

$ 


I even restarted the vault server, and and then repeat the above commands to delete the policy and re-create it, but to no avail.

**Comment by linuxbee** [comment]
OK, the issue is now resolved. I just needed to delete the oldapp cert in addition to the oldapp policy.

$ vault delete auth/cert/certs/oldapp
Success! Deleted 'auth/cert/certs/oldapp'

$ vault read auth/cert/certs/oldapp
No value found at auth/cert/certs/oldapp

Token generated from vault CLI:
===============================
(This token still shows the non-cert credential.)

$ vault token-create -policy=myapp
Key            	Value
token          	9ae32190-e82d-6c9a-1e81-fb870ccf44fa
token_accessor 	99c3d093-4dae-6c58-eba0-08dc7e2cd938
token_duration 	2592000
token_renewable	true
token_policies 	[default myapp]


$ VAULT_TOKEN=9ae32190-e82d-6c9a-1e81-fb870ccf44fa vault read auth/token/lookup-self
Key          	Value
accessor     	99c3d093-4dae-6c58-eba0-08dc7e2cd938
creation_time	1.461222736e+09
creation_ttl 	2.592e+06
display_name 	token
id           	9ae32190-e82d-6c9a-1e81-fb870ccf44fa
meta         	<nil>
num_uses     	0
orphan       	false
path         	auth/token/create
policies     	[default myapp]
role         	
ttl          	2.591975e+06


Token received in the Java code:
================================
(This token reveals the normal myapp and its cert credential)

$ VAULT_TOKEN=aed00ece-0543-6d06-16a9-901164be4365 vault read auth/token/lookup-self
Key          	Value
accessor     	f5856ae4-4dae-9433-39f0-9103efa45b58
creation_time	1.46122212e+09
creation_ttl 	2.592e+06
display_name 	cert-myapp_cert
id           	aed00ece-0543-6d06-16a9-901164be4365
meta         	map[authority_key_id:c3:22:d5:c1:40:68:e2:8f:d0:72:be:63:bc:43:74:e2:ed:0b:c4:ab cert_name:myapp common_name:My App Certificate subject_key_id:6f:b2:ea:42:23:56:32:ec:46:6e:a8:69:70:d4:e6:3e:e9:40:a4:ba]
num_uses     	0
orphan       	true
path         	auth/cert/login
policies     	[common default myapp]
role         	
ttl          	2.591216e+06

$

**Comment by jefferai** [comment]
Hi @linuxbee ,

When you use the `vault token-create` CLI command you are using the `token` authentication backend, not the `cert` authentication backend. The configuration you set in the `cert` backend will have no effect; instead the token generated will have the parent token's policies unless overridden on the command line (and this must be a subset of the parent token's policies).

See https://www.vaultproject.io/docs/auth/cert.html for an example of authenticating against the `cert` backend from the CLI. This should let you generate tokens with similar policies and properties from both the CLI and your Java code.

**Comment by linuxbee** [comment]
Thanks a lot, Jefferai, for the explanation. Yes, I have read the cert section a few times over. However, with your explanation to differentiate the auth between cert and token, it is much clearer to go back and read the document again. That solves my puzzle about the different outputs both from the cli (token auth) and from the Java code (cert auth). This also makes clear the concept about the path in the vault.

I am familiar with PKI stuff and had built the complete CA hierarchy for my vault application. It's the generic terms used in the vault documentation that causes my confused a bit. For example, I am assuming the TLS between Vault and Consul can be configured for mutual cert authentication (client authentication and server authentication using incoming and outgoing tls -- please correct me if I misunderstood what the document really meant.) However, by reading the documentation, it is not clear to me which CA cert should be placed where in the vault and consul (I remember at least one CA is not required to be specified in the vault config?). In theory, there should be vault.key, vault.cert, vaultCA.cert, consul.key, consul.cert, consulCA.cert. In the configuration, the vault.key, vault.cert and consulCA.cert are on the vault side. The consul.key, consul.cert and vaultCA.cert are on the consul side. (I am skipping the intermediate CA stuff for the sake of simplicity.)

Now, adding the mutual cert authentication between the vault server and client app, you can see how quickly the picture could become much complicated -- if the documentation is not very clear and precise about which cert and which CA should be placed where in the config file. (To me, it's where in the config file I should apply what cert that confused me a bit, not how the mutual authentication works. One example is that whether vault is applying the cert chain one the client side, or on the CA side. I had to figure it out by trial and error with the vault config and consul config.)

Nevertheless, the vault and consul prove to be very useful for some security applications. With your help, I can better understand the concept of the vault internals. I think I can use the tools well once I learned better what the vault documentation really means in the configurations.

**Comment by jefferai** [comment]
Closing for now, please reopen/poke if you still have issues!
