### ISSUE TITLE
add new file type support while putting k/v pairs

### ISSUE THREAD

**Issue by developer-guy** [hashicorp/vault#13403]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**

IIRC, JSON files are the only files that are supported by Vault while putting k/v pairs to K/V Secret engines. 

What we are proposing is that add new file types support such as TOML, YAML, etc while putting k/v pairs.

**Describe alternatives you've considered**

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

cc: @dentrax

**Comment by Dentrax** [comment]
We are converting req body to [JSON](https://github.com/hashicorp/vault/blob/f421fa96c4ad1b7a419c2865ce97dc258245822a/api/logical.go#L134) in the `api/logical.go`. But couldn't find much where we handle this _secret put request_ from the server side. Probably we do JSON unmarshal'ing (`map[string]interface{}`) there. 🤔

**Comment by hghaf099** [comment]
@developer-guy thank you for filing this issue. To help us better assist you, would you please let us know what precise problem are you trying to solve by adding "native" support for Non-Json formats? Note that you can have Json-wrapped data put in KV. In addition, if your data is of type non-string you can store it as a base64-encoded string. So, there are some work arounds that you can choose from.

**Comment by raskchanky** [comment]
This hasn't had a response in awhile now, so I'm going to close it due to inactivity. Please feel free to reopen if you feel this was a mistake, or if there is additional information to add. Thanks!
