### ISSUE TITLE
token-lookup creation time in the wrong format?

### ISSUE THREAD

**Issue by Fitzsimmons** [hashicorp/vault#1341]
I assume that `creation_time` is supposed to be a unix timestamp? It's formatted in scientific notation, which I assume is not intended.

```
vault token-lookup abcd-1234
Key          	Value
[...]
creation_time	1.461171256e+09
[...]
```

Scientific notation is also used in the JSON and YAML output formats.

**Comment by jefferai** [comment]
Yes, this is a very old known issue. Closing for now as it's already on our TODO.
