### ISSUE TITLE
Add conjur comparison

### ISSUE THREAD

**Issue by ggonchar** [hashicorp/vault#1344]
It would be nice to know how vault compares to https://www.conjur.net/products/secrets-management which is so far one of the the closest alternatives. Please add comparison with conjur https://www.vaultproject.io/intro/vs/index.html

**Comment by shdobxr** [comment]
This would be extremely helpful in building out my gap analysis to my colleagues so that our decision to go with Vault is clearer.

**Comment by joescii** [comment]
See also #3045

**Comment by shdobxr** [comment]
@joescii to be completely transparent. Conjur was recently acquired by CyberArk.  Especially considering the note from #3045. Their product is >< as well.

**Comment by joescii** [comment]
Good clarifying note, @shdobxr. I was indeed aware of the acquisition, but perhaps others who find this issue aren't.

**Comment by jefferai** [comment]
We have a feature matrix at https://www.hashicorp.com/products/vault#features; we prefer discussing how we compare to other enterprise software via customer calls, as we don't want to have information on our web site that is out of date.

**Comment by Idanatcox** [comment]
I think adding this comparison could still be valuable

**Comment by archmangler** [comment]
No comparison yet? This would really be useful when bringing the case for vault vs. conjur to enterprise customers.
