### ISSUE TITLE
(*S3Backend).Get: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by emk** [hashicorp/vault#1345]
Thank you for your great work on vault! We're really loving it.

Running vault v0.5.1 on Amazon Linux under Docker version 1.9.1, build a34a1d5/1.9.1. The backtrace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x9f62fb]

goroutine 245 [running]:
panic(0x1189fe0, 0xc820012080)
	/goroot/src/runtime/panic.go:464 +0x3e6
github.com/hashicorp/vault/physical.(*S3Backend).Get(0xc8204002c0, 0xc82076c500, 0xe, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/physical/s3.go:130 +0x34b
github.com/hashicorp/vault/physical.(*Cache).Get(0xc820401200, 0xc82076c500, 0xe, 0x2, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/physical/cache.go:59 +0x185
github.com/hashicorp/vault/vault.(*AESGCMBarrier).Get(0xc8203457a0, 0xc82076c500, 0xe, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:621 +0x206
github.com/hashicorp/vault/vault.(*AESGCMBarrier).CheckUpgrade(0xc8203457a0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:509 +0x291
github.com/hashicorp/vault/vault.(*Core).checkKeyUpgrades(0xc820168540, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/core.go:1477 +0x67
github.com/hashicorp/vault/vault.(*Core).periodicCheckKeyUpgrade(0xc820168540, 0xc82062c120, 0xc82062c180)
	/gopath/src/github.com/hashicorp/vault/vault/core.go:1463 +0x144
created by github.com/hashicorp/vault/vault.(*Core).runStandby
	/gopath/src/github.com/hashicorp/vault/vault/core.go:1363 +0x12b
```

This happens once a day or so, with plenty of vault activity.

Our config file looks like:

```
backend "s3" {
  bucket = "<REMOVED>"
  # These keys are added by ./start_server.
  access_key = "@access_key@"
  secret_key = "@secret_key@"
  region = "us-east-1"
}

ha_backend "etcd" {
  # ...stuff
}
```

We use a regular IAM user with the policy:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::REMOVED"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::REMOVED/*"
            ]
        }
    ]
}
```

We've been seeing our vault crash fairly often recently, and I suspect this issue may be responsible. #836 looks superficially related at first glance,, but it's crashing in a different location.

We're happy to provide more information. Thank you for any advice you can provide!

**Comment by seamusabshere** [comment]
that's crazy!

**Comment by jefferai** [comment]
I see where in the code this is coming from (a response to the GetObject call from the Amazon SDK), although not much more. Any chance you can build from a branch and test?

**Comment by emk** [comment]
Sure, we'd be happy to build from a branch, if that helps track this down.

**Comment by jefferai** [comment]
@emk is a branch off master fine, or do you need it off of 0.5.1? I can't promise downgrading back to 0.5.1 would work, so you'd either want to test against a copy of your data, or plan to stay on the branch up until either a later master or the next release.

**Comment by emk** [comment]
We could risk staying on a branch for a bit.

**Comment by jefferai** [comment]
Cool -- see https://github.com/hashicorp/vault/tree/s3-nil

There is a place where you're seeing the crash where the code checks for one type of error, but not all types. So this will still be an error (coming from S3) but shouldn't be a crash.

**Comment by emk** [comment]
With these patches applied, our cluster fails with the following errors:

core: post-unseal setup failed: failed to list upgrades: nil response from S3 but no error
Apr 26 04:16:54 54.84.127.65 logger:  /ecs-vault-a-19-vault-e6e8acbe82cdc4a51500 2016/04/26 11:16:54 [INFO] core: acquired lock, enabling active operation
Apr 26 04:16:54 54.84.127.65 logger:  /ecs-vault-a-19-vault-e6e8acbe82cdc4a51500 2016/04/26 11:16:54 [INFO] core: post-unseal setup starting
Apr 26 04:16:54 54.84.127.65 logger:  /ecs-vault-a-19-vault-e6e8acbe82cdc4a51500 2016/04/26 11:16:54 [ERR] core: failed to list entries in core/leader: nil response from S3 but no error

I'm going to try to revert to the last working build.

**Comment by jefferai** [comment]
This happened on upgrade for you? What build were you on before?

**Comment by jefferai** [comment]
@emk Fixed the typo in my patch that caused the failure. The branch should be good again and will actually show the error you're getting.

**Comment by jefferai** [comment]
FYI I've merged the fixed version of this patch into `master`. See #1353 .

**Comment by emk** [comment]
Excellent! I'm juggling a bunch of stuff, but I'll try upgrading our cluster to master again shortly.

Thank you very much for tracking this down! We're very happy with vault.

**Comment by jefferai** [comment]
Glad to hear it!

Just to reiterate: this will stop the panic and return the error instead, but the error is coming from S3 so it may still cause wonky behavior.

**Comment by emk** [comment]
OK, we're on the latest master as of this morning. I'll let you know if we see any more problems.

We've been averaging maybe 1 vault server crash per week (out of a three-machine cluster) lately, using the older version. Let's see what happens with the new version.

**Comment by seamusabshere** [comment]
@emk update on this bug?

**Comment by jefferai** [comment]
Closing due to lack of response. Please let me know if it needs to be reopened.

**Comment by emk** [comment]
We're definitely still seeing roughly weekly vault server crashes, possibly related to this issue, but getting a working HA setup has been a higher priority.

**Comment by jefferai** [comment]
Are the stack traces the same?
