### ISSUE TITLE
No ability to get verify TOTP-result via API

### ISSUE THREAD

**Issue by pauelstv** [hashicorp/vault#13453]
**Describe the bug**
I try to get TOTP-code verify result by API. I used official documentation on official site of project: https://www.vaultproject.io/docs/secrets/totp
As a result I have only error message.

**To Reproduce**
1. I do: curl --header "X-Vault-Token: xxxx" --request POST --data '{"code":"123802"}' http://localhost:8200/v1/totp/keys/totp-key
3. I see error message from API: {"errors":["the key value is required"]}

**Expected behavior**
I wish I could get normael result such as: {  "data": {    "valid": true  }}

**Environment:**
* Vault Server Version (1.9.1):
* Vault CLI Version (1.9.1):
* Official docker image/amd64:

Vault server configuration file(s):

```
docker run --cap-add=IPC_LOCK \
    --name vault \
    --hostname vault.xxxxxx.com \
    --restart=always \
    -e 'VAULT_LOCAL_CONFIG={"backend": {"mysql": {"ha_enabled": "true", "address": "xxx.xxx.xxx.xxx:3306", "username": "vaultdbuser", "password": "xxxxxxxx", "database": "vaultstorage" }}, "default_lease_ttl": "168h", "max_lease_ttl": "720h", "api_addr": "http://xxx.xxx.xxx.xxx:8200", "ui": "true", "listener": [{"tcp":{ "address": "0.0.0.0:8200", "cluster_address": "0.0.0.0:8201", "tls_disable": "0", "tls_cert_file": "/etc/ssl/vault.pem", "tls_key_file": "/etc/ssl/vault.key"}}] }' \
    -e 'VAULT_SKIP_VERIFY=true' \
    --network dockernet \
    -p 8200:8200 \
    -p 8201:8201 \
    -d vault:latest server

```

**Additional context**
I've tried to use new test standalone instance in developer mode  with -dev key. And I got similar result  -  {"errors":["the key value is required"]}

**Comment by hsimon-hashicorp** [comment]
Hi there! Please check the API documentation as located here: https://www.vaultproject.io/api-docs/secret/totp
It looks like you're missing your payload in your curl command. Please let me know if this helps. Thanks!

**Comment by pauelstv** [comment]
> Hi there! Please check the API documentation as located here: https://www.vaultproject.io/api-docs/secret/totp It looks like you're missing your payload in your curl command. Please let me know if this helps. Thanks!

No, I tried to do it how requiring it the official documentation either. Of course I tried compile curl command with @payload and a behaviour was similar.
It seems to me it requires some additional header, but documentation don't contains it. Or format of payload which described in documentations is not correct.

**Comment by hsimon-hashicorp** [comment]
@pauelstv understood, thank you for the clarification. I'll do some research.

**Comment by pauelstv** [comment]
I've found mistake in my API query, sorry. 
I must use `/totp/code/key-name` instead `/totp/keys/key-name`
