### ISSUE TITLE
vault server -dev with TLS?

### ISSUE THREAD

**Issue by maxramqvist** [hashicorp/vault#13467]
**Is your feature request related to a problem? Please describe.**
I would like to run the dev server with TLS for testing integrations with the certifificate login backend. I can't seem to figure out how to provide my TLS certificates to Vault when running in dev mode. Is it possible?

**Describe the solution you'd like**
I would like to have flags or environment variables to specify cert and key that the Vault server in dev-mode will use.

**Describe alternatives you've considered**
I could use the not-dev/production mode of Vault but would then have to do the unseal parts, when I just want to run some integration tests.

**Explain any additional use-cases**
Integration tests with features that require TLS, like the cert auth backend.

**Comment by hsimon-hashicorp** [comment]
Currently, the Vault dev server mode is insecure by design, to allow for quick and easy testing. However, I will take your use case back to our engineering and product teams to see if there's a way that TLS testing could be included as an option. Thanks for your patience!

**Comment by VinnyHC** [comment]
@maxramqvist I believe what you're after can be achieved by something like this:
`dev-tls-config.hcl`
```hcl
listener "tcp" {
  address       = "0.0.0.0:8400"
  tls_cert_file = "/vault/certificate.crt"
  tls_key_file  = "/vault/private.pem"
}
```
Kick off `vault` with something like:
```shell
vault server -dev -dev-listen-address="0.0.0.0:8200" -config=dev-tls-config.hcl
```
and it'll listen to insecure traffic on `:8200` and use the TLS setup on `:8400`
More info here: https://www.vaultproject.io/docs/commands/server#config

**Comment by maxramqvist** [comment]
That works great, thank you!

**Comment by priyanshu281** [comment]
@maxramqvist how do we generate certs and key files because the command i am using is this `openssl req   -out tls.crt   -new   -keyout tls.key   -newkey rsa:4096   -nodes   -sha256   -x509   -subj "/O=HashiCorp/CN=Vault"   -addext "subjectAltName = IP:<loopbackIP>,DNS:<host>"   -days 3650`  but openssl version doesnt recognize -addext option and other ways are also not working

**Comment by austingebauer** [comment]
You can also use the `-dev-tls` flag of the `vault server` command to quickly get a TLS-enabled Vault dev server running. It'll generate the CA, certificate, and key for you along with configuring Vault to use them.

```
$ vault server --help
  -dev-tls
      Enable TLS development mode. In this mode, Vault runs in-memory and
      starts unsealed, with a generated TLS CA, certificate and key. As the
      name implies, do not run "dev-tls" mode in production. The default is
      false.
...
```

**Comment by mdgreenwald** [comment]
> @maxramqvist I believe what you're after can be achieved by something like this: `dev-tls-config.hcl`
> 
> ```terraform
> listener "tcp" {
>   address       = "0.0.0.0:8400"
>   tls_cert_file = "/vault/certificate.crt"
>   tls_key_file  = "/vault/private.pem"
> }
> ```
> 
> Kick off `vault` with something like:
> 
> ```shell
> vault server -dev -dev-listen-address="0.0.0.0:8200" -config=dev-tls-config.hcl
> ```
> 
> and it'll listen to insecure traffic on `:8200` and use the TLS setup on `:8400` More info here: https://www.vaultproject.io/docs/commands/server#config

This is a great solution, but it can be even better if you swap:
`dev-listen-address="0.0.0.0:8400` and `listener.address="0.0.0.0:8200"`.
This way you can use TLS over the standard vault port `8200` and access insecurely over 8400.
