### ISSUE TITLE
CVEs found in 1.9.1

### ISSUE THREAD

**Issue by itsokov** [hashicorp/vault#13473]
Scanning a docker image including the 1.9.1 vault binary with Trivy reports the following CVEs
![TrivyScan](https://user-images.githubusercontent.com/25243928/146772424-dbef359c-4d80-4ac8-97f6-61da6b87066a.png)

The same scan on Docker Image with Vault version 1.7.3 does not report vulnerabilities.

**Comment by mladlow** [comment]
Hi @itsokov, please report security issues by emailing security@hashicorp.com.
