### ISSUE TITLE
Ensure non-zero and unique co-efficients for generating polynomials

### ISSUE THREAD

**Issue by supriya-premkumar** [hashicorp/vault#13498]
[Recommendations for ensuring non-zero and unique co-efficients for generating polynomials](https://www.zkdocs.com/docs/zkdocs/protocol-primitives/shamir/#what-can-go-wrong)

**Zero Share Problem**
```
Any co-efficient if it is set to zero will compromise the secret because the shard holder will not have to evaluate the polynomial (0, S) which reveals the secret to the ith share holder.
```

**Non Unique Shares**
```
This happens when we interpolate lagrangian. In case if the two coefficients are the same their modulo inverse will be 0 and will crash 
```

**Comment by cipherboy** [comment]
Hi @supriya-premkumar -- please see my response on the pull request. Thank you!

**Comment by hsimon-hashicorp** [comment]
Hi @supriya-premkumar - wanted to chime in for the New Year and see if you had any questions or comments for Alex. Thanks!

**Comment by supriya-premkumar** [comment]
Hi @hsimon-hashicorp, Yes. Just responded to @cipherboy.
Happy New Year to you both!
