### ISSUE TITLE
Vault cli kv patch performs call to api v1

### ISSUE THREAD

**Issue by gprzyby** [hashicorp/vault#13502]
**Describe the bug**
When executing `vault kv patch` it shows error with 405 http response with path `https://vault_domain/v1/secret/data/my_secrets`
Rollback to version 1.7 resolved problem

**To Reproduce**
1. Run `vault kv patch`
2. See error

**Expected behavior**
Command should without any problems make patch request to api v2, which supports patch request 

**Environment:**
* vault version 1.9.1:
* Fedora 34

**Comment by hsimon-hashicorp** [comment]
Hello! Could you provide more details about this? Also, here's some documentation on using `patch` with kv-v2: https://www.vaultproject.io/api/secret/kv/kv-v2#patch-secret

**Comment by TonioGela** [comment]
I can confirm the bug. The vault v1.9.2 calls the v1 APIs and gives error, at least on Darwin

**Comment by bunnybilou** [comment]
I have the same behaviour with v1.9.2 and v1.9.1. 
I have rollbacked to v1.8.7 and patch is working properly.

**Comment by brissenden** [comment]
Same issue for me on Darwin (latest).

**Comment by ncabatoff** [comment]
Hi @gprzyby,

Thanks for the bug report.  A fix should be available in the upcoming 1.9.3 release.

**Comment by gprzyby** [comment]
Glad to hear that! Thanks for fix ;)
