### ISSUE TITLE
Vault Doc Link

### ISSUE THREAD

**Issue by Merikanto** [hashicorp/vault#13534]
Hello, 

I was reading the Vault docs:
https://www.vaultproject.io/docs/concepts/ha

And here, when I tried to click the link for the Consul backned, the link doesn't work.
![Screenshot from 2021-12-30 14-24-19](https://user-images.githubusercontent.com/45705788/147723961-7c366bd6-8d9f-4331-8b0b-e8832fbc22e8.png)

https://www.vaultproject.io/docs/storage/consul

Thanks!

**Comment by hsimon-hashicorp** [comment]
@taoism4504, it looks like the links in Storage Support are all 404s now (except for the "configuration page" link). Did these get migrated?
Thanks for this report, @Merikanto!

**Comment by taoism4504** [comment]
Looking into it...

**Comment by Merikanto** [comment]
Thanks~
