### ISSUE TITLE
POST /auth/token/lookup not behaving as expected

### ISSUE THREAD

**Issue by iricha** [hashicorp/vault#1354]
The Vault project documentation for tokens lists two requests for calling /auth/token/lookup.  One with the token included in the path (GET) and the other including it in the request body (POST).

The GET method for this path works as documented, but has one downside for our organization; the token in the path is shown in plaintext in the audit log.

The POST method would appear to address this, except it returns the wrong token data.

When making a HTTP request against this endpoint, Vault returns the token data for the token found in the X-Vault-Token header, not the one in the request body.

Example curl command:

> curl -iv -H "X-Vault-Token: &lt;token_1&gt;" \
>     -X POST -d '{"token":"&lt;token_2&gt;"}' \
>     http://localhost:8200/v1/auth/token/lookup
> 

Is this intended?  Is the documentation just out of date?  I also noticed that under the POST subsection it has the Method listed as GET.

Reference: https://www.vaultproject.io/docs/auth/token.html  /auth/token/lookup[/token] section.

**Comment by jefferai** [comment]
> Is this intended? Is the documentation just out of date? I also noticed that under the POST subsection it has the Method listed as GET.

That's a documentation bug, will fix that ASAP.

The rest, I'm looking into...
