### ISSUE TITLE
Make dev Error 1

### ISSUE THREAD

**Issue by lovepr16** [hashicorp/vault#13569]
When I run make dev command it gives me the following error -->
==> Checking that build is using go version >= 1.16.2...
==> Using go version 1.17.3...
==> Removing old directory...
==> Building...
Number of parallel builds: 1

-->     linux/amd64: github.com/hashicorp/vault

1 errors occurred:
--> linux/amd64 error: exit status 1
Stderr: go build github.com/hashicorp/vault/vendor/github.com/aws/aws-sdk-go/service/ec2: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
go build github.com/hashicorp/vault/vendor/github.com/hashicorp/go-msgpack/codec: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
go build github.com/hashicorp/vault/vendor/github.com/softlayer/softlayer-go/services: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
go build github.com/hashicorp/vault/vendor/github.com/vmware/govmomi/vim25/types: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
go build github.com/hashicorp/vault/vendor/github.com/aws/aws-sdk-go/service/s3: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed

make: *** [dev] Error 1

**Comment by ncabatoff** [comment]
Hi @lovepr16,

What branch are you trying to build?  We haven't used vendor dirs in quite a while. 

How much memory do you have?  Sometimes I've seen the go compiler killed due to lack of memory when building a large project.

**Comment by ncabatoff** [comment]
What does the command `free` report on that server?  e.g. on my server `mal` I have 32GB and I get:

```
ncc@mal:~$ free
              total        used        free      shared  buff/cache   available
Mem:       32821620      711496    30597980        3976     1512144    31717412
Swap:       2097148           0     2097148
```

**Comment by lovepr16** [comment]
I am getting this output -->
golang@node108631-env-8522720 ~ $ free
              total        used        free      shared  buff/cache   available
Mem:         786432       83928      344364         124      358140      702356
Swap:        393216           0      393216

**Comment by lovepr16** [comment]
I am getting this output -->
golang@node108631-env-8522720 ~ $ free
              total                  used               free      shared   buff/cache   available
Mem:         786432       83928       344364         124      358140      702356
Swap:        393216           0             393216

**Comment by ncabatoff** [comment]
That does look a bit light for compiling a project of this size.  I don't know how much memory is needed, but it should be pretty easy to try giving the server more and see if it helps, right?

**Comment by ncabatoff** [comment]
Closing issue as stale.
