### ISSUE TITLE
Navigation bar is missing

### ISSUE THREAD

**Issue by alexandernst** [hashicorp/vault#13581]
**Describe the bug**
I upgraded from 1.2.2 to 1.9.2 and the very first thing I noticed is that the navigation UI is missing. In 1.2.2 the UI had a small breadcrumbs-like navigator at the top that allowed me to easily navigate to any part of the path (e.g. `foo > bar > 123 > xyz > abc`, I could click on `bar` and I'd end up listing the path `foo > bar`).

In 1.9.2 I'm just getting an input that get's updated with the path that I'm currently listing. I get to see the old "breadcrumb-like navigator" only when I navigate to a secret, but not when I'm listing paths.

![Vault](https://user-images.githubusercontent.com/89727/148268500-333aef8f-289f-40af-ae16-ccee30d679f9.png)

This means that instead of being able to go back to a "previous" path with a single click, now I must use both my mouse and keyboard in order to focus the input field and then delete the part of the path that I'm not interested in listing. This is plain terrible UX.

Why was the breadcrumbs navigator removed? Is that a bug or was it decided to be removed?

**To Reproduce**
1. Open Vault UI
2. Navigate to any path
3. See error

**Expected behavior**
I'd like to be able to navigate paths as I used to in 1.2.2.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.9.2
* Vault CLI Version (retrieve with `vault version`): N/A
* Server Operating System/Architecture: Debian Buster

Vault server configuration file(s):

```hcl
storage "mysql" {
  address = "++++++++"
  username = "++++++++"
  database = "++++++++++"
  password = "++++++++++++"
}

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = 1
}

ui = true
log_level = "warning"
```

**Additional context**
N/A

**Comment by hsimon-hashicorp** [comment]
Thank you for the report, @alexandernst! Claire has merged a PR that resolves this issue. Really appreciate the find!

**Comment by hellobontempo** [comment]
@alexandernst Yes - thank you! This will also be backported to our next release of 1.7 😄
