### ISSUE TITLE
Vault becomes unresponsive after a restore.

### ISSUE THREAD

**Issue by beeradb** [hashicorp/vault#1358]
I'm attempting to restore a fully failed instance of Vault which was running with a DynamoDB backend.

During restoration I am using the following config:
```
backend "dynamodb" {
  recovery_mode = 1
  region = "us-west-2"
  table = "table"
  access_key = "$ACCESS_KEY"
  secret_key = "$SECRET_KEY"
  advertise_addr = "http://$PUBLIC_IP"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/etc/certs/server.pem"
  tls_key_file = "/etc/certs/server.key"
}
```

The vault instance comes back up and will report the following when running "vault status":
```
Sealed: true
Key Shares: 10
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: sealed
```

After unsealing, I get output as expected:
```
Sealed: false
Key Shares: 10
Key Threshold: 3
Unseal Progress: 0
```

However, after unsealing the vault instance becomes fully unresponsive. Commands issued via the client or directly via HTTPs all time out. The client reports the following error when running vault status:
```
Error checking seal status: Get https://somedomain.com:8200/v1/sys/seal-status: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

Additionally, here are the logs from the vault server. Everything here looks as expected to me.
```
==> Vault server configuration:

         Log Level: info
             Mlock: supported: true, enabled: true
           Backend: dynamodb (HA available)
 Advertise Address: http://SOME_IP_HERE
        Listener 1: tcp (addr: "0.0.0.0:8200", tls: "enabled")
           Version: Vault v0.5.2

==> Vault server started! Log data will stream in below:

2016/04/29 21:25:26 [INFO] core: vault is unsealed
2016/04/29 21:25:26 [INFO] core: entering standby mode
2016/04/29 21:25:28 [INFO] core: acquired lock, enabling active operation
2016/04/29 21:25:28 [INFO] core: post-unseal setup starting
2016/04/29 21:25:29 [INFO] core: mounted backend of type generic at secret/
2016/04/29 21:25:29 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/04/29 21:25:29 [INFO] core: mounted backend of type system at sys/
2016/04/29 21:25:29 [INFO] rollback: starting rollback manager
```

Any thoughts on what could be causing the issue? There were two vault instances running in HA against this dynamo table an hour ago which were working as expected.

**Comment by jefferai** [comment]
Honestly, no idea. As you said, the logs look fine. Maybe try stopping any other instances that may be running first (if there are any), in case the Dynamo backend is having some strange locking behavior.

**Comment by beeradb** [comment]
This is the only instance running on the entire account, so it shouldn't be that :(

**Comment by jefferai** [comment]
I don't really have any insight into DynamoDB, the extent of my knowledge around it is "it exists". I'm assuming it's related to that just because Vault being generally unresponsive is not something we see.

My only other thought right now is that it's possible that it's not really hung but that you have some huge number of leases being loaded that is either very slow with Dynamo or that is exhausting resources and causing OOM or swapping. Is there a way for you to get insight into how many entries are in Dynamo for Vault?

**Comment by beeradb** [comment]
item count is listed as 13,553. Total DB size is 7.32MB (as reported by Dynamo in AWS)

It could very well be something in the DB as I was able to migrate and restore a vault instance with a single key written to the secret backend.

We're not doing anything outside of vanilla usage, though. We're just using the secret backend with GitHub auth enabled.

**Comment by beeradb** [comment]
It's also worth noting that we have a surprisingly high number of 'sys/expire/id/auth/github/login' keys (~4500). If these store temp tokens and/or auth details for GitHub logins as I would expect, that's a surprisingly high number of records for the amount of users we have.

**Comment by beeradb** [comment]
One additional piece of information which seems pertinent. If you enable debug mode, then after unsealing vault appears to go into a "rollback" loop.

`2016/05/02 17:09:38 [INFO] rollback: starting rollback manager
2016/05/02 17:10:38 [DEBUG] rollback: attempting rollback on sys/
2016/05/02 17:10:38 [DEBUG] rollback: attempting rollback on secret/
2016/05/02 17:10:38 [DEBUG] rollback: attempting rollback on cubbyhole/
2016/05/02 17:11:38 [DEBUG] rollback: attempting rollback on sys/
2016/05/02 17:11:38 [DEBUG] rollback: attempting rollback on secret/
2016/05/02 17:11:38 [DEBUG] rollback: attempting rollback on cubbyhole/
2016/05/02 17:12:38 [DEBUG] rollback: attempting rollback on secret/
2016/05/02 17:12:38 [DEBUG] rollback: attempting rollback on cubbyhole/
2016/05/02 17:12:38 [DEBUG] rollback: attempting rollback on sys/
2016/05/02 17:13:38 [DEBUG] rollback: attempting rollback on sys/
2016/05/02 17:13:38 [DEBUG] rollback: attempting rollback on secret/
2016/05/02 17:13:38 [DEBUG] rollback: attempting rollback on cubbyhole/
2016/05/02 17:14:38 [DEBUG] rollback: attempting rollback on sys/
2016/05/02 17:14:38 [DEBUG] rollback: attempting rollback on secret/
2016/05/02 17:14:38 [DEBUG] rollback: attempting rollback on cubbyhole/
2016/05/02 17:15:38 [DEBUG] rollback: attempting rollback on sys/
2016/05/02 17:15:38 [DEBUG] rollback: attempting rollback on secret/
2016/05/02 17:15:38 [DEBUG] rollback: attempting rollback on cubbyhole/
2016/05/02 17:16:38 [DEBUG] rollback: attempting rollback on sys/
2016/05/02 17:16:38 [DEBUG] rollback: attempting rollback on secret/
2016/05/02 17:16:38 [DEBUG] rollback: attempting rollback on cubbyhole/`

It's also worth noting the "file" audit backend is enabled.

**Comment by jefferai** [comment]
> It's also worth noting that we have a surprisingly high number of 'sys/expire/id/auth/github/login' keys (~4500). If these store temp tokens and/or auth details for GitHub logins as I would expect, that's a surprisingly high number of records for the amount of users we have.

This means you have users re-authenticating instead of reusing their tokens. Once a token is issued it isn't removed until it's either revoked manually or expires, and the same tokens are never re-issued -- they're not stateful for a given user (that would be...bad  :-) ).

> If you enable debug mode, then after unsealing vault appears to go into a "rollback" loop.

Those are one minute apart -- normal rollback manager behavior!

I'm still baffled. Any chance you could try `strace` or something and see if you can figure out what, if anything, it's waiting on?

**Comment by beeradb** [comment]
Well, I have some good news.. I've been able to restore the instance. There is still something that seems very broken, though.

Here's the process I used:

- I stood up a single instance with "recovery_mode" on and unsealed it.
- The process went unresponsive for 5-10 minutes. I've tried this on several instance sizes (t2.micro, t2.large, m4.xlarge) and instance size appears to have no bearing on how long it takes. For the scenario I currently describing it was a t2.micro.
- I stood up a second instance, also pointing at the dynamo table, this time without "recovery_mode" on. After unsealing the second instance the two instances fought over leadership, and each time a new leader was elected (which was often) vault would go unresponsive for 5 to 10 minutes. As expected, each time one would acquire the lock I would see messages similar to the following in the logs

```
2016/05/02 20:27:17 [WARN] core: leadership lost, stopping active operation
2016/05/02 20:27:17 [INFO] core: pre-seal teardown starting
2016/05/02 20:27:17 [INFO] rollback: stopping rollback manager
```

Additionally, I would periodically see dynamo related errors such as the following:
```
2016/05/02 20:27:12 [ERR] core: failed to read seal configuration: ProvisionedThroughputExceededException: The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API
	status code: 400, request id: SUPER_LONG_REQUEST_ID
```

However, the dynamo table is at the max read/write capacity allowed by AWS (25/25).

I was finally able to end this cycle by killing off the first instance, removing "recovery_mode" from the config, and bringing a new instance back online.

To distill this, it seems there are two problems here:

- Unsealing takes a very long time. Long enough that I assumed it was just not going to work.
- Recovery mode appears to cause continual cycling between vault instances in a HA setup.

Here's a log from the non "recovery_mode" instance when the two instances were fighting over leadership. As you can see, it cycled leaders 3 times in a 20 minute period. As I said above, each time it did this vault would remain unresponsive for at least 5-10 minutes.

```
2016/05/02 20:19:34 [INFO] rollback: stopping rollback manager
2016/05/02 20:19:34 [INFO] core: pre-seal teardown complete
2016/05/02 20:19:36 [INFO] core: acquired lock, enabling active operation
2016/05/02 20:19:36 [INFO] core: post-unseal setup starting
2016/05/02 20:19:36 [INFO] core: mounted backend of type generic at secret/
2016/05/02 20:19:36 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/05/02 20:19:36 [INFO] core: mounted backend of type system at sys/
2016/05/02 20:19:36 [INFO] rollback: starting rollback manager
2016/05/02 20:25:59 [INFO] expire: restored 169 leases
2016/05/02 20:25:59 [INFO] core: post-unseal setup complete
2016/05/02 20:26:51 [ERR] core: failed to read seal configuration: ProvisionedThroughputExceededException: The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API
  status code: 400, request id: REQUEST ID 
2016/05/02 20:27:17 [WARN] core: leadership lost, stopping active operation
2016/05/02 20:27:17 [INFO] core: pre-seal teardown starting
2016/05/02 20:27:17 [INFO] rollback: stopping rollback manager
2016/05/02 20:27:17 [INFO] core: pre-seal teardown complete
2016/05/02 20:27:18 [INFO] core: acquired lock, enabling active operation
2016/05/02 20:27:18 [INFO] core: post-unseal setup starting
2016/05/02 20:27:19 [INFO] core: mounted backend of type generic at secret/
2016/05/02 20:27:19 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/05/02 20:27:19 [INFO] core: mounted backend of type system at sys/
2016/05/02 20:27:19 [INFO] rollback: starting rollback manager
2016/05/02 20:34:48 [INFO] expire: restored 169 leases
2016/05/02 20:34:48 [INFO] core: post-unseal setup complete
2016/05/02 20:34:48 [WARN] core: leadership lost, stopping active operation
2016/05/02 20:34:48 [INFO] core: pre-seal teardown starting
2016/05/02 20:34:48 [INFO] rollback: stopping rollback manager
2016/05/02 20:34:48 [INFO] core: pre-seal teardown complete
2016/05/02 20:34:49 [INFO] core: acquired lock, enabling active operation
2016/05/02 20:34:49 [INFO] core: post-unseal setup starting
2016/05/02 20:34:50 [INFO] core: mounted backend of type generic at secret/
2016/05/02 20:34:50 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/05/02 20:34:50 [INFO] core: mounted backend of type system at sys/
2016/05/02 20:34:50 [INFO] rollback: starting rollback manager
2016/05/02 20:38:30 [INFO] expire: restored 169 leases
2016/05/02 20:38:30 [INFO] core: post-unseal setup complete
```

I'll see if I can bring this down again and enable strace to determine what might cause the long unseal times.

**Comment by jefferai** [comment]
@seiffert Any chance you have some insight here? I figure you know this code/DynamoDB behavior better than anyone else :-)

**Comment by seiffert** [comment]
Hi, thanks for pinging me, @jefferai! 

@beeradb: I'm not sure whether I understand completely what's going on, but maybe I can help debug this issue. Situations in which DynamoDB requests seem to hang, are often caused by request throttles combined with retries performed by the SDK. Could you please provide screenshots of the CloudWatch graphs of the DynamoDB metrics `ProvisionedReadCapacityUnits`, `ProvisionedWriteCapacityUnits`, `ConsumedReadCapacityUnits`, `ConsumedWriteCapacityUnits`, and `WriteThrottleEvents` of the respective table for the timeframe during which the issue occurred?
The AWS SDK we use in Vault performs 10 retries of every failed request by default. These retries are performed with an exponential backoff which could cause those long times where Vault seems to hang.

I'm not sure why you can't set more than 25 read/write capacity units, but I've definitely seen tables with higher provisioned throughput. Can you maybe try to increase these numbers during the restore?

**Comment by jefferai** [comment]
I'm assuming due to lack of response that this has been sorted out? If not, please reply and we can re-open.
