### ISSUE TITLE
agent: support an agent specific healthcheck/metrics endpoint

### ISSUE THREAD

**Issue by dekimsey** [hashicorp/vault#13602]
**Is your feature request related to a problem? Please describe.**
As an operator, if I'm running a vault agent on a box I'd like to be able to verify it's running healthy. Right now, my only option is a tcp listen check as all connections are forwarded as the agent doesn't have it's own API to query.

**Describe the solution you'd like**
I propose the agent expose some paths on the same listeners.
/_agent/v1/status/health
/_agent/v1/status/metrics
Or perhaps:
/-/health
/-/metrics

**Describe alternatives you've considered**
I currently use TCP checks. I've tried HTTP and found my Consul service registration was in effect monitoring the vault cluster via the agent. Whoops!

**Explain any additional use-cases**
However, what I'm mostly interested in right now is that the agent is connected and authenticated to vault. Ideally, all templates/sinks wrote okay too.

The metrics portion is optional, just suggesting it's an opportunity to add some visibility to what the agent is doing. How many secrets are in the cache? How many failures to refresh (denials)? Is vault responding? How many template renders have occurred?

**Additional context**
n/a

**Comment by hsimon-hashicorp** [comment]
Hi! Is this similar to the ask in #8649 ?

**Comment by dekimsey** [comment]
@hsimon-hashicorp Bah! I searched too to check before I filed thinking this had to be something others have asked about. So sorry for the duplicate! Thanks you for catching this.

**Comment by hsimon-hashicorp** [comment]
No worries at all! I'll close this one, and we'll track on the other issue. We've been discussing it internally as well. :)
