### ISSUE TITLE
Oracle KMS seal: "did not find a proper configuration for private key"

### ISSUE THREAD

**Issue by fhilgers** [hashicorp/vault#13607]
**Describe the bug**
When using the ocikms seal provider with `auth_type_api_key = true` I am getting the following error:

Error parsing Seal configuration: error initializing OCI KMS client: failed creating NewKmsCryptoClientWithConfigurationProvider: can not create client, bad configuration: did not find a proper configutation for private key

I've already checked that my configuration file in `~/.oci/config` is correct and can confirm that it works with both the cli and the oci-go-sdk library.

**To Reproduce**
1. Use the ocikms seal stanza and ensure that `auth_type_api_key = true`:
2. Run `vault server -config ./config.hcl`
3. See error

**Expected behavior**
I expected Vault to run normally and use the Oracle KMS provider.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.9.2
* Vault CLI Version (retrieve with `vault version`): 1.9.2
* Server Operating System/Architecture: Ubuntu 20.04

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
storage "inmem" {}

listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = true
}

seal "ocikms" {
  key_id = "XXX"
  crypto_endpoint = "XXX"
  management_endpoint = "XXX"
  auth_type_api_key = true
}
```

**Additional context**
I have already submitted an issue to hashicorp/go-kms-wrapping#45 which is as far as I am aware the source of this problem. It uses a very old version (v13.1.0+incompatible) of the oracle/oci-go-sdk. Updating the version of the oracle sdk in go-kms-wrapping fixes my issue.

I have also noticed that vault is using the oracle sdk in some other places as well and also uses the same old version as hashicorp/go-kms-wrapping. This might also need updating as there were quite a lot of changes made to this library since 2019.

**Comment by flyxi121** [comment]
So after playing around with it for a while I realized that the version which fixed my problem is `oci-go-sdk 22.0.0`

This version added support for `PKCS#8 format API Keys` and apparently the api key which was generated by the oracle cloud web console was in this format.

**Comment by flyxi121** [comment]
It would make sense to either provide a note in the documentation that vault does not support the newer features of the oci-go-sdk (especially the key format) or just update dependency if that is possible without too much fuss.

**Comment by giovannicandido** [comment]
I'm experiencing the same error but trying to login to vault with the oci as per command: `vault login -method=oci auth_type=apiKey role=vaultadminrole`
Then I get the error: 

```
Error authenticating: can not create client, bad configuration: did not find a proper configuration for private key
```

The oci cli works fine.

**Comment by fhilgers** [comment]
This can be closed as it was just a problem with the oracle sdk used in https://github.com/hashicorp/go-kms-wrapping/issues/45.
