### ISSUE TITLE
docstring for api.DefaultConfig() explains error case wrongly

### ISSUE THREAD

**Issue by majewsky** [hashicorp/vault#13636]
The current docstring is https://github.com/hashicorp/vault/blob/33d61b5ca647f308c173e29506727e3d643e51aa/api/client.go#L180-L187

However, the function never actually returns nil. If there is an error, a non-nil Config instance is returned and `config.Error` will be filled accordingly. I was going to do a PR, but I won't bother with the CLA stuff for a one-line patch.

**Comment by digivava** [comment]
Thanks for pointing this out! I've just fixed the doc string and it will be reflected in the next api release.
