### ISSUE TITLE
Policies can only have lower case names but upper case gets accepted and then mangled to lower case

### ISSUE THREAD

**Issue by firstdorsal** [hashicorp/vault#13647]
Policies get accepted if they have an uppercase name and without any further notice mangled to their lowercase representation.

IMO policy names should be rejected if they contain anything else but lowercase and not silently be mangled to lowercase as this behaviour causes issues.

**Comment by ncabatoff** [comment]
Hi @firstdorsal,

I would prefer that behaviour too.  I don't think it's likely we change this though due to backwards compatibility concerns.  I'll leave this open for now, possibly our developer experience team would like to think through whether we ought to change this and how it might be done safely.

**Comment by maxb** [comment]
This problem also exists elsewhere in Vault - identity entity and identity group names, come to mind - although there the behaviour is case-insensitive but case-preserving. This can cause some decidedly awkward interactions when using other software to orchestrate Vault configuration, and that other software assumes names will simply be used as is, and can be simply compared (case-sensitively) to enforce uniqueness.

**Comment by digivava** [comment]
Thanks for bringing this to our attention! For now we have just added a warning to both the CLI output and the API response object whenever the resulting policy name differs from the one in the request. Hopefully this at least calls some attention to this behavior when it occurs.

**Comment by Fuco1** [comment]
This is also annoying when using terraform to automatically generate some policies for example for applications registered in azure or aws.  Often they have upper case names and the policies are created with upper case names but then converted to lowercase.  Every terraform run it now gives me a change set with the cases. :/  I'll update the terraform script to lower-case the policy names, but it is annoying.
