### ISSUE TITLE
OIDC CLI login redirecting to localhost (with Azure AD)

### ISSUE THREAD

**Issue by Akanksha-P97** [hashicorp/vault#13663]
Hi Everyone,

When logging in using the **OIDC auth** method,  I'm unable to authenticate and receive a callback/redirect to localhost. When I run the command to login via oidc `vault login -method=oidc role=default` I receive the " *Complete the login via your OIDC provider. Launching browser to:* " following the provided link they authenticate to Azure AD, and redirected back to localhost. 

Azure AD Callback urls:
```
http://localhost:8200/oidc/callback
https://<vault ip>:8200/oidc/callback
https://<vault ip>:8200/ui/vault/auth/oidc/oidc/callback
```

Command issue to login:
```
[vault@host~]$ vault login -method="oidc" role="reader" port=8200
Complete the login via your OIDC provider. Launching browser to:

https://login.microsoftonline.com/fbc82b/oauth2/v2.0/authorize?client_id=d8fd&nonce=n_ME2xYa&redirect_uri=http%3A%2F%2Flocalhost%3A8250%2Foidc%2Fcallback&response_type=code&scope=openid+https%3A%2F%2Fgraph.microsoft.com%2F.default&state=st_**
```

**Anyone please help me!! It's urgent and I am stuck since 2 days. Tried nearly every possible configurations but nothing is working. I'm always redirected to localhost.**

I have posted in the discussion form as well: https://discuss.hashicorp.com/t/oidc-cli-login-redirecting-to-localhost-with-azure-ad/34199/4

**Comment by austingebauer** [comment]
Hi, @Akanksha-P97! I'm happy to help you get this fixed up. From what I can see, I think it's a configuration issue. 

From your question in the discussion post, you'll want to supply the "value" instead of the "Secret ID" from your Azure AD app to the `oidc_client_secret` configuration parameter.

I've also noticed that you're supplying a port number of 8200 for the redirect port. Is there a specific reason you're doing so? The `redirect_uri` in the authorize URL has a mismatching port of 8250, which is why you're not seeing the redirect after successfully authenticating via the browser. I'd suggest to remove the `port=8200` parameter from the `vault login` command and change your redirect_uris (in both Azure and Vault) to use 8250.

**Comment by Akanksha-P97** [comment]
Thanks for responding.

Yes, I modified the configuration by providing the value of secret id and providing the redirect uri's as below:

```
https://host:8200/ui/vault/auth/oidc/oidc/callback
http://localhost:8250/oidc/callback
```

But this is also not working. 

Also I have one doubt- my vault server is running on an azure instance and not in my local setup. 
So should I change the redierct uri from localhost to this?:
```
http://host:8250/oidc/callback
```

**Comment by austingebauer** [comment]
I'd suggest to set the following redirect URIs in Vault's [allowed_redirect_uris](https://www.vaultproject.io/api-docs/auth/jwt#allowed_redirect_uris) and in the Azure application's Redirect URIs setting.

Redirect URI needed for logging in through the Vault CLI (e.g., `vault login -method="oidc" role="reader"` without the `port` parameter):
```
http://localhost:8250/oidc/callback
```

Redirect URI needed for logging in through the Vault UI:
```
http://{<your vault host>:<your vault port>/ui/vault/auth/oidc/oidc/callback
```

If that doesn't work, it'd be helpful if you can provide any errors. It'd also be helpful if you can provide what your redacted [configuration](https://www.vaultproject.io/api-docs/auth/jwt#read-config) and [role](https://www.vaultproject.io/api-docs/auth/jwt#read-config) look like. Thanks!

**Comment by Akanksha-P97** [comment]
Yes, I''m firing this command to login to vault:
`vault login -method=oidc role=default`

My vault configurations:

**Step 1**: vault auth enable oidc
**Step2**: vault write auth/oidc/config -<<"EOH"
{
   "oidc_client_id": "d*********fd",
   "oidc_client_secret": "-aI******nF",
   "default_role": "default",
   "oidc_discovery_url": "https://login.microsoftonline.com/my-tenant-id/v2.0",
   "provider_config": {
      "provider": "azure"
   }
}
EOH

After this I always get success message:  **_Success! Data written to: auth/oidc/config_**
**Step 3**: vault write auth/oidc/role/default @azure-config.json
Below are the file contents of ` azure-config.json`-

```
{
    "allowed_redirect_uris": [
        "https://localhost:8250/oidc/callback",
        "https://20.197.56.50:8200/ui/vault/auth/oidc/oidc/callback"
    ],
    "groups_claim": "groups",
    "oidc_scopes": [
        "https://graph.microsoft.com/.default,profile,email"
    ],
    "policies": [
        "oidc"
    ],
    "user_claim": "email",
    "bound_audiences": [
        "d8**********fd"
    ],
    "verbose_oidc_logging": "true"
}
```
**Step 4**: vault login -method=oidc role=default


**Configuartion on Azure AD:**
**Step1**: Created an Azure App Registration allowing my redirect URLs
```
http://localhost:8250/oidc/callback
https://hostname:8200/ui/vault/auth/oidc/oidc/callback
```
**Step 2**: In Azure API permissions I have:
email
Group.Read.All
GroupMember.Read.All
openid
profile
User.Read
![Capture55](https://user-images.githubusercontent.com/46327641/149461269-021ecd3e-533a-495d-9453-c041fff52366.PNG)


**Step 3**: Generated a secret and and its token from the portal
**Step 4**: Token configuration:
![Capture54](https://user-images.githubusercontent.com/46327641/149461639-37455070-19d1-46f4-a470-df554570e2cd.PNG)

**Step 4**: I am using the v2.0 endpoints https://login.microsoftonline.com/{my_tenant_id}/v2.0
**Step 5**: I modified the app manifest with "groupMembershipClaims": "All",

**Comment by Akanksha-P97** [comment]
And this is the error after I'm redirected to localhost:

```
AADSTS650053: The application 'Test' asked for scope '.default,profile,email' that doesn't exist on the resource '00000003-*****'. Contact the app vendor.
```

**Comment by austingebauer** [comment]
@Akanksha-P97 - I suggest to make the following edits to your role:

1. Change the CLI redirect URI to `http://localhost:8250/oidc/callback` (https -> http)
2. Start simple by requesting no additional scopes. Let's see if we can get through the flow successfully and add scopes from there.

```
{
    "allowed_redirect_uris": [
        "http://localhost:8250/oidc/callback",
        "https://20.197.56.50:8200/ui/vault/auth/oidc/oidc/callback"
    ],
    "groups_claim": "groups",
    "oidc_scopes": [],
    "policies": [
        "oidc"
    ],
    "user_claim": "email",
    "bound_audiences": [
        "d8**********fd"
    ],
    "verbose_oidc_logging": "true"
}
```

**Comment by Akanksha-P97** [comment]
It's http only. I just typed https by mistake hetre. But in my configs-it's` http://localhost:8250/oidc/callback` only

**Comment by austingebauer** [comment]
@Akanksha-P97 - Closing this issue based on our discussions (outside of GitHub) to help get this set up. Thanks!

**Comment by Akanksha-P97** [comment]
Thanks @austingebauer

**Comment by sing011** [comment]
@austingebauer  Facing similar issue in https://github.com/hashicorp/vault/issues/14534 . Any chance you can assist?

**Comment by sing011** [comment]
@Akanksha-P97  how did you solve this? could use some help

**Comment by borisgorbunov** [comment]
how did you solve this? could use some help!!??
