### ISSUE TITLE
Zookeeper backend upgrade issue

### ISSUE THREAD

**Issue by kenbreeman** [hashicorp/vault#1367]
Upgrading Vault backed by Zookeeper from version 0.3.1 to either 0.4.0 or 0.5.2 results in the entire cluster panicking due to a bug in the `go-zookeeper` library. On leader election, the rollback manager is started and promptly crashes.

https://github.com/samuel/go-zookeeper/pull/118
https://github.com/samuel/go-zookeeper/pull/104

```
2016/04/28 19:32:35 [INFO] core: mounted backend of type generic at logical/bdd599de-6a72-8414-e702-70589ff73415/
2016/04/28 19:32:35 [INFO] rollback: starting rollback manager
panic: runtime error: slice bounds out of range

goroutine 14 [running]:
github.com/samuel/go-zookeeper/zk.(*Conn).recvLoop(0xc820094c40, 0x7fbacf355748, 0xc82002a3a0, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/conn.go:656 
+0x1290
github.com/samuel/go-zookeeper/zk.(*Conn).loop.func2(0xc820094c40, 0xc82019c240, 0xc82019ef80)
        /gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/conn.go:325 
+0x51
created by github.com/samuel/go-zookeeper/zk.(*Conn).loop
        /gopath/src/github.com/hashicorp/vault/Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/conn.go:332 
+0x843
```

**Comment by kenbreeman** [comment]
One workaround is standing up a fresh new cluster and importing all configuration and secrets from the previous one, but it is a less than ideal upgrade path.

**Comment by jefferai** [comment]
There's not much I can do until upstream fixes the issue -- there are three PRs so it's not like this issue is unknown. If Samuel really is totally abandoning the package, may be worth some interested people forking it together, but it's really hard to know if this is the case, given some recent commits. In the meantime, my suggestion would be to pull down one of the patches and build Vault locally.

**Comment by kenbreeman** [comment]
Fair enough, think it makes sense to leave this open till then so anyone else using the ZK backend is aware?

**Comment by jefferai** [comment]
Sure.  Feel free to ping back when you think there's a way forward on the upstream side!

**Comment by talbright** [comment]
I've been following along and using the library for a few months. While it hasn't been completely abandoned, it mostly has. The build was broken for a few weeks, with a couple of people offering up patches to fix it. Eventually the author fixed it. That's been the only noticeable activity since Nov 2, 2015. 
The author hasn't been responding to PR's.

We aren't in production yet with go-zookeeper, so it's not ideal for us to take it on completely but I'm more than happy to help or work with someone on creating a maintained fork.

**Comment by kenbreeman** [comment]
@talbright I'm interested. We're using this in Production and I have a fair amount of operational experience with Zookeeper but Go is not one of my stronger languages.

**Comment by talbright** [comment]
@kenbreeman 2 > 0 😄 
One place that needs work is improving the tests and build (can go into the details later). That's a good place to start for anyone newer to a language or library.

@jefferai would hashicorp be willing to fork the repo and then add me as a contributor? There might be more synergy given the name recognition.

**Comment by jefferai** [comment]
@talbright We would not...we generally avoid "owning" repositories that we are not actively maintaining. Name recognition goes both ways after all :-D

**Comment by talbright** [comment]
Gotcha, any suggestions on a path forward?

**Comment by jefferai** [comment]
The best suggestion I can think of offhand would be to fork it (potentially into a new organization if you don't want it to live under a specific person's namespace) and have a community of the interested maintain it. When upstream disappears sometimes it's the only way to go.

**Comment by talbright** [comment]
Yup. Of course there's 189 forks so far ([mine](https://github.com/talbright/go-zookeeper) included), so not sure which one "wins".

**Comment by jefferai** [comment]
Generally speaking, with a fork, the one that wins is the one that the community coalesces around. If you're active and planning on actively maintaining it, spread the word around and see if you can get others to contribute. As ZK is a community-supported backend in Vault, I think Vault's backend will follow where the community of Vault ZK users goes.

**Comment by talbright** [comment]
I've been maintaining it to some extent for us internally, but only cherry picking or adding features we need. I'm happy to take it on, it would be very helpful if there's some coalescing 👨‍👩‍👧‍👧

https://github.com/talbright/go-zookeeper

**Comment by talbright** [comment]
@kenbreeman if you have an inclination head over to my repo and feel free to jump in. I've spent the better part of the day stabilizing the tests and improving the build, so there's at least some level of confidence in merging PRs. The test coverage is a little low, but that can be improved with time.

**Comment by jefferai** [comment]
Hi @talbright @kenbreeman 

FYI, the package in Vault was updated (#1447), but that doesn't preclude migrating to something that will be better supported going forward.

At the same time, @mariocastroc please be aware of this issue -- you may want to run testing and help with establishing something supported.

**Comment by talbright** [comment]
The more support the better, just need active maintainers ;-D

**Comment by kenbreeman** [comment]
I'm fine with either version, so long as this bug is fixed I'm happy :smile:

**Comment by jefferai** [comment]
I guess I'd rather use whichever will have people actively supporting it.

**Comment by jefferai** [comment]
@talbright @kenbreeman @mariocastroc I would like us to land on something before 0.6 comes out. There are three of you and you are the users that have reported problems, so I'm happy letting you three take a vote and going with the majority.

**Comment by jefferai** [comment]
Closing due to lack of responses.
