### ISSUE TITLE
Acess does not work 

### ISSUE THREAD

**Issue by Vincent1984** [hashicorp/vault#13674]
**Describe the bug**
Access can not work fine , neither KV1 or KV2 style

**To Reproduce**
1. create user & password in Access, attach police “acl_bijinming"
![image](https://user-images.githubusercontent.com/3183359/149659947-2ee0b08c-7ab9-440c-aef2-9cb222841110.png)

2. Create the policy "bijinming" as the following shows
![image](https://user-images.githubusercontent.com/3183359/149660175-5556f045-085e-499c-b008-8073d679c70e.png)

3. create kv2 secret in test/test path
<img width="1080" alt="1642336427(1)" src="https://user-images.githubusercontent.com/3183359/149660151-5c8f9e64-2929-43d0-ab8e-25da38cc9ada.png">

4. login with new user 
<img width="1080" alt="1642336781(1)" src="https://user-images.githubusercontent.com/3183359/149660286-93743ff8-b5ef-4dcd-8b84-cc983174fac7.png">

**Expected behavior**
secret in path 'test/test' could be see, and other secret can not be see.

**Environment:**
* Vault Server Version: vault:1.9.0

Vault server configuration file(s):

```hcl
disable_mlock = true
ui = true

listener "tcp" {
tls_disable = 1
address = "[::]:8200"
cluster_address = "[::]:8201"
}
storage "file" {
path = "/vault/data"
}
```

**Additional context**
when I remove the data and set the access path as "test/test/*", it does not work fine either!

**Comment by Vincent1984** [comment]
@hsimon-hashicorp this is not ui issue, it is ACL Policies problems,  I just show the ui, in client it also shows "no permission"

**Comment by HridoyRoy** [comment]
Hi @Vincent1984 , I'm not able to reproduce this problem. Do you mind including the CLI commands you used to test this as opposed to the UI screenshots? I'm not too familiar with how the UI errors translate to backend errors, so with the CLI commands I might be able to get a better understanding of the underlying problem.
Thanks!

**Comment by HridoyRoy** [comment]
Hi again @Vincent1984 ! 
We noticed that in the screenshots you provided one of the paths you are accessing is `test/test` and the other is `secrets/test`. The policy on the token you're using has access to the path `test/data/test` which gives you access to secrets in `test/test`, not to `secrets/test`. For this reason, the behavior you're observing is that you can access and write to `test/test`, but not to `secrets/test`.
