### ISSUE TITLE
vault cli to support only fields output

### ISSUE THREAD

**Issue by kucharskim** [hashicorp/vault#13701]
Ability to list fields under specific key. During administrative work I often only want to see what fields are present under specific key, without exposing sensitive content of those fields:

```
$ vault kv get -format json secret/keys/tls/example.com | jq -r '.data.data|keys[]'
CERT
KEY
```

Having convenient vault cli option for same above output would be good feature to have.

**Comment by ccapurso** [comment]
Hi, @kucharskim. Thank you for your submission! We are planning to include a new KVv2 endpoint with the 1.10 release that should provide a solution to your request. The KV secret engine PR can be found [here](https://github.com/hashicorp/vault-plugin-secrets-kv/pull/59). The linked pull request is associated with the docs updates which will be merged once the KVv2 dependency has been updated.

**Comment by kucharskim** [comment]
How is this going to be visible from a user perspective? Is this specific Vault version or combination of components?

**Comment by ccapurso** [comment]
That's a great question. The KV secret engine is [built-in](https://www.vaultproject.io/docs/internals/plugins#built-in-plugins) and thus the [changes](https://github.com/hashicorp/vault-plugin-secrets-kv/pull/59) made to add this endpoint will be made available with version 2 of the KV secret engine in the upcoming Vault 1.10.0 release. This [new section](https://github.com/hashicorp/vault/blob/336332daba822b8927a31ad6c46892cb906cf700/website/content/api-docs/secret/kv/kv-v2.mdx#read-secret-subkeys) discussing the endpoint will be added to Vault's API docs (https://www.vaultproject.io/api-docs) once the release has been made available. As with with other KV-related endpoints, access to this endpoint will need to be made available via your policies.

**Comment by abdennour** [comment]
I asked similar question somewhere since 3 years.. I can see the question is duplicated again.. This means that there is big demand on this feature... For the time being, this is our refuge script:

```sh
path=secret/keys/tls/example.com
vault kv get -format json ${path} | jq -r '.data.data|keys[]' | while read -r key;do
    vault kv get -format json ${path} | jq -r ".data.data[${key}]"  > ${key}
done

```

This beautiful script will load vault path into a set of files where names of files are the keys, and content of these files are the values of those keys.
