### ISSUE TITLE
New HMAC-as-a-service feature

### ISSUE THREAD

**Issue by joelthompson** [hashicorp/vault#1373]
I think it would be useful for Vault to include some sort of HMAC-as-a-service feature. I imagine it would be a part of the `transit` backend. In addition to the existing `encrypt` and `decrypt` operations, you could have `sign` and `verify` operations that could be permissioned separately, and could operate against the same named keys as the `encrypt` and `decrypt` operations. That way, the HMAC keys never leave the Vault server, all operations are logged, we can enforce key rotation, etc.

I realize that the `encrypt` and `decrypt` operations also ensure integrity via use of GCM, and that I could achieve something similar by just encrypting the data and then trying to decrypt it, but that feels a little hackish (and the length of the encrypted data is the length of the plaintext data + length of the IV + length of the GMAC tag + potentially overhead for hexlify/base64/base85 encoding to get to plain text, when I might want a relatively small HMAC to store somewhere; I could potentially get around this by doing a sha256sum on the input data first and then encrypting and decrypting, but that just feels like too much work).

Thoughts?

**Comment by jefferai** [comment]
I'm closing this as it's already roadmapped. I just can't talk about the "when" at this point.
