### ISSUE TITLE
Feature Request: JSON Schema Validation

### ISSUE THREAD

**Issue by frodopwns** [hashicorp/vault#1377]
I have implemented the ability to validate secrets in specific paths in my personal vault cli tool.

To achieve this I create secrets in secret/validation/schemas that contain JSON Schemas.

ie `secret/validation/schemas/account` contains:

```
{
        "$schema": "http://json-schema.org/draft-04/schema#",
        "description": "A user account schema",
        "properties": {
            "email": {
                "description": "email for account if required",
                "type": "string"
            },
            "password": {
                "description": "account password",
                "type": "string"
            },
            "username": {
                "description": "The login for a user account",
                "type": "string"
            }
        },
        "required": [
            "password",
            "username"
        ],
        "title": "Account",
        "type": "object"
}
```

Then in secret/validation/maps/ I create a secret that maps other paths to the schemas I want to apply.

ie. secret/validation/maps/client/accounts contains:

```
schemas:
- account
```

and signifies that the account schema should be applied to secret/client/accounts whenever a new secret is created.

I am curious if this is something that could/should be implemented directly into vault?

**Comment by jefferai** [comment]
Hi @frodopwns,

I think it's a neat idea and I encourage you to share it on the mailing list, but it's really too specific to put in as a feature on the backend... we'd prefer that stay on the client side. Thanks for sharing it!

**Comment by frodopwns** [comment]
What is too specific? You provide any schema you want and apply it to any path you want...

**Comment by jefferai** [comment]
The `generic` backend is generic on purpose -- it just provides key/value storage. Specific solutions for specific schema needs are better provided on the client side, to keep the backend agnostic and simple.
