### ISSUE TITLE
Cannot install from Hashicorp Repo

### ISSUE THREAD

**Issue by ptous** [hashicorp/vault#13849]
**Describe the bug**
The Vault package is broken, causing apt commands to fail. This is the same issue reported for Consul [here](https://github.com/hashicorp/consul/issues/12181).

**To Reproduce**
```
$ curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
$ sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
$ sudo apt-get update && sudo apt-get install vault
```

This will produce output containing a message like so:
```
Reading package lists...
    STDERR: E: Encountered a section with no Package: header
    E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_bionic_main_binary-amd64_Packages.lz4
    E: The package lists or status file could not be parsed or opened.
```

**Expected behavior**
Vault is installed by the packaging system.

**Environment:**
* Vault Server Version (retrieve with `vault status`): Attempting to install 1.3.0 (yeah, we know it's old), but version doesn't matter.
* Vault CLI Version (retrieve with `vault version`): N/A as install fails
* Server Operating System/Architecture: Ubuntu 18.04, in a container in this context, but it actually fails anywhere.

Vault server configuration file(s): N/A
**Additional context**
This appears to be a general issue with the package files for Hashicorp's repo, which we switched to so we could get more recent versions than the OS provided packages.

**Comment by hsimon-hashicorp** [comment]
Thanks! We're working with our Release Engineering team on this now. I appreciate your patience!

**Comment by hsimon-hashicorp** [comment]
Hi @ptous - our release engineering team believes they've resolved this issue. Can you try `sudo apt-get clean && sudo apt-get update` and let me know if the problem persists? Thanks!

**Comment by ptous** [comment]
Yes! I can confirm this is now resolved. Thanks for the fix and update!

**Comment by hsimon-hashicorp** [comment]
> Yes! I can confirm this is now resolved. Thanks for the fix and update!

Hooray! Thanks for the report, it helped a lot. :)
