### ISSUE TITLE
Two HA Vault not working properlyif respective consul address is used

### ISSUE THREAD

**Issue by chrisrana** [hashicorp/vault#1385]
I am trying to implement HA Vault.I have two node(two VM) and each node has Vault and consult installed (Bosh release).Vault version is Vault v0.5.2. Below is the config description.

When using Respective Consul address(local consul)
---------------------------------------------------------
Node 1 VM1
backend "consul"{  address = "10.20.0.252:8200" ........}

Node 2 VM2
 backend "consul"{  address = "10.20.0.254:8200" ....... }

In this case Node1 is leader and in active state.Node 2 is in standby state.
Now If I restart Node1, Node2 going in to active state.but Node is also going in to Active state after it comes up and after restart.

When using Same Consul address
---------------------------------------------------------
Here I am using same consul address (10.20.0.252 ) for both the node .It works fine and i could see state changing as expected.

Node1 (10.20.0.252)
-------------------------------------------
backend "consul"{
  path = "vault/"
  address = "10.20.0.252:8200"
  advertise_addr = "https://10.20.0.252:8200"
}

listener "tcp" {
 address = "10.20.0.252:8200"
 tls_disable = 1
 tls_cert_file = "/var/vcap/jobs/vault/ssl/certificate.pem"
 tls_key_file  = "/var/vcap/jobs/vault/ssl/key.pem"
}

Node 2 (10.20.0.254)
--------------------------------------------
backend "consul"{
  path = "vault/"  
  address = "10.20.0.252:8500"
  advertise_addr = "https://10.20.0.254:8200"
}

listener "tcp" {
 address = "10.20.0.254:8200"
 tls_disable = 1
 tls_cert_file = "/var/vcap/jobs/vault/ssl/certificate.pem"
 tls_key_file  = "/var/vcap/jobs/vault/ssl/key.pem"
}

1. Is this correct behaviour ? If not what is missing in my config.

2. I have also read some where that two vault active standby possible in same Node.Is this correct and how to acheive this?
https://groups.google.com/forum/#!msg/vault-tool/4_Drhb5TiqM/--JkPCRfBgAJ

**Comment by jefferai** [comment]
What's happening is almost certainly that your two Consul nodes are not actually in the same cluster and are not sharing data. As a result each Vault thinks it's the only one running.

**Comment by chrisrana** [comment]
Thank Jefferai for Quick Reply.Now I am exploring cluster now.

Out of curiosity If  Node 1 is active and consul there is down.Node 2 is standby.Do cluster mechanism help redirect  request to Node2 consul ?

**Comment by justenwalker** [comment]
@chrisrana The API will send a 301 redirect to the current leader if you hit a node in standby - but unlike Consul, it will not route the request transparently for you.

This is probably because:
1. The Vault nodes are not technically in a cluster, they are just hot stand-by nodes
2. API also supports Client Certs, which cannot by proxied.

One problem with the redirect approach is that POST requests generally become GET requests, or otherwise lose their body when HTTP clients follow redirects. With curl, there are options to disable this behavior: `--post301, --post302 and -post303`. the vault cli does this automatically.

**Comment by jefferai** [comment]
Note that it's actually a `307`, not `301`.

**Comment by jefferai** [comment]
@justenwalker in the past some cases issued a 307 and some a 302; it is now 307 everywhere.

**Comment by jefferai** [comment]
Closing due to lack of response from OP.
