### ISSUE TITLE
Vault secret mysql: Error 1269: Can't revoke all privileges for one or more of the requested users

### ISSUE THREAD

**Issue by apdl** [hashicorp/vault#1386]
We are using Vault v0.5.2 with Consul as a backend to dynamically generate credentials in our mysql database with a minimal configuration(for now). We are experiencing errors with revoking its leases see below:

_vault revoke bs-1/creds/test/dbdb03e7-3721-3bfc-6647-cdf34dca4a37
Revoke error: Error making API request._
URL: PUT http://IPADDR:8200/v1/sys/revoke/bs-1/creds/test/dbdb03e7-3721-3bfc-6647-cdf34dca4a37
Code: 400. Errors:
_* failed to revoke entry: Error 1269: Can't revoke all privileges for one or more of the requested users_

**Vault User**
GRANT CREATE USER ON \*.\* TO 'vault'@'%' IDENTIFIED BY PASSWORD '<password>' WITH GRANT OPTION
* CREATE USER = Enable use of CREATE USER, DROP USER, RENAME USER, and REVOKE ALL PRIVILEGES. Level: Global.

**Lease Settings**
Key      	        Value
lease    	        1h0m0s
lease_max	24h0m0s

**Role**
vault read bs-1/roles/test
Key	Value
sql	CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT SELECT ON \*.\* TO '{{name}}'@'%';

I have no idea why we are getting this error as we have the right privileges for the vault users to create, drop, revoke, etc... We verified this by directly running mysql command with either revoking privilege or dropping the dynamic credentials using the vault mysql user. 

Does vault revoke command revoke lease and delete the dynamic credentials created in mysql? What is /sys/revoke api exactly do?

**Comment by apdl** [comment]
So the issue was vault revoke command assumes that the mysql credentials to be revoke has a host of **'%'**. However, in our case the dynamic credential's host is eg. 'token-191e3ab8-b1'@**'1.1.%'**

tcpdump from our database shows vault revoke lease id command is running:
REVOKE ALL PRIVILEGES, GRANT OPTION *.* FROM 'token-191e3ab8-b1'@'%';

**Comment by jefferai** [comment]
Sounds like this problem will go away when the ability to add the revoke SQL is added.

**Comment by jippi** [comment]
@jefferai when are ^ planned for?

**Comment by jpweber** [comment]
I am seeing this on on vault 0.6.1. Are there any updates on this?

**Comment by jefferai** [comment]
No updates right now. Ideally Vault 0.6.3 but cannot promise anything.

**Comment by jpweber** [comment]
I might want to take a stab at trying ti implement this. Would this issue the the appropriate place for questions or is there a better place to discuss some of the details?

**Comment by jpweber** [comment]
pr created for this #1914

**Comment by vishalnayak** [comment]
Fixed by #1914
