### ISSUE TITLE
ui: some chars destroys the list view until page reload / the "View secret" prompt should not be cached

### ISSUE THREAD

**Issue by Schluggi** [hashicorp/vault#13875]
**Describe the bug**
If you type-in `"/` into the secret filter you get an error that prevent you to see any secret until you go back and reload the page.

**To Reproduce**
1. Go to the UI
2. Select any secret engine
3. Use the secret filter and type-in `"/`
4. You should see this: 
![grafik](https://user-images.githubusercontent.com/43608073/152157631-b14deb10-90c7-41e2-960e-465dfb3c05b6.png)
5. Go back to the overview of the secret engines
6. Navigate to the same engine you select in **2.**
7. The view is still the same as in **4.**
8. Reload the page (for example by pressing F5) and you'll get back your list view
 
**Expected behavior**
First of all i don't think the chars should have this effect at all. I would expect the "There are no secrets matching" massage to appiers.
Moreover the browser should not cache this message. On point **7** I would expect to see the list view that I can see after reloading the page because the filter value is not longer path of the url.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.9.2
* Vault CLI Version (retrieve with `vault version`): v1.9.2
* Server Operating System/Architecture: CentOS 7

Vault server configuration file(s):
I can't paste any configuration files due to our company guidelines :/

**Additional context**
This issue maybe relates to #13866 and first notices after upgrading from v1.6.3 to v1.9.2.

The "View secret" prompt (I shared in the image) is also cached if I try to open an engine without having the `list` permissions:
1. Open an engine without having the `list` permissions
2. The "View secret" prompt appiers
3. Go to eny other engine where you have the `list` permission
4. The "View secret" prompt is still there
5. Reloading the page fixes the view

Sometimes the "View secret" prompt also appiers and get cached after deleting a secret. But I was not able to reproduce this. I think there is a general problem whith the caching method of this prompt.

**Comment by hsimon-hashicorp** [comment]
Hi there! We're having some trouble reproducing this internally:
![Screenshot from 2022-02-04 15-57-14](https://user-images.githubusercontent.com/84740964/153279892-e4d1c324-ef55-4f56-99a6-86522b4ec584.png)
Can you provide more information about the policies being used here? Also, can you verify that both your server and your UI are on 1.9.2? Thanks! :)

**Comment by hsimon-hashicorp** [comment]
Thanks @tizzir! This helps. We'll do some more investigation and see if we can repro it with this information. :)

**Comment by hsimon-hashicorp** [comment]
This is fixed in #13880 and will be in 1.10. Thanks for your patience!
