### ISSUE TITLE
[MongoDB Engine] Get Credentials button doesn't work

### ISSUE THREAD

**Issue by ichasco-heytrade** [hashicorp/vault#13874]
Hi, 

I am not able to get credentials from `overview` --> Get credentials button. It is always disabled, but if I go through the `Roles` tab and then select the role and `generate credentials` it works

And there isn't any error in the logs

Thanks

**Comment by hsimon-hashicorp** [comment]
Hi, can you please provide more information? What version of Vault are you using? Thanks!

**Comment by ichasco-heytrade** [comment]
Hi, upgrading to `1.9.2` it has been fixed. 

Thanks!
