### ISSUE TITLE
LDAP auth backend does not support nested groups in Active Directory

### ISSUE THREAD

**Issue by shomron** [hashicorp/vault#1389]
The current LDAP auth backend does not support nested group resolution against Active Directory. It will resolve only direct group membership (via member field). This can remedied by allowing custom search queries to be configured, rather than trying to build a universal query that will work across all LDAP servers / schemas.

In the case of Active Directory, we would want to enable the `LDAP_MATCHING_RULE_IN_CHAIN` matching rule as in the following example:

`(&(objectClass=group)(member:1.2.840.113556.1.4.1941:={{.UserDN}}))`

Reference: https://msdn.microsoft.com/en-us/library/aa746475(v=vs.85).aspx

**Comment by shomron** [comment]
First attempt at addressing this issue: https://github.com/hashicorp/vault/pull/1388

**Comment by jefferai** [comment]
Closing as this is all in #1388
