### ISSUE TITLE
possibility of vertica compatibility for postgres secret backend

### ISSUE THREAD

**Issue by consultantRR** [hashicorp/vault#1391]
Vertica (the columnar database) is in many ways wire compatible to postgres. Preliminary testing indicates to me that the current postgres secret backend will likely out of the box with Vertica. Almost. The issue I am hitting right now is that Vertica disallows hyphens in ROLE names and USER names, so when Vault tries to create a name such as `root-1430162075-7887`, the operation fails with a syntax error.

Here is a manual example from psql:

```
=> CREATE USER root-1430162075-7887 IDENTIFIED BY '34205e88-0de1-68b7-6267-72d8e32c5d3d';
ERROR:  Syntax error at or near "-"
LINE 1: CREATE USER root-1430162075-7887 IDENTIFIED BY '34205e88-0de...
```

Might there be any interest in enhancing the postgres secrets backend to optionally eliminate hyphens from names in order to broaden the compatibility of this particular backend?

**Comment by consultantRR** [comment]
Sorry, please ignore. Hyphenated usernames can be created by quoting them. I will do further testing as to Vertica compatibility with this backend, and maybe submit a documentation enhancement PR if it is found to work for sure.

**Comment by consultantRR** [comment]
I can confirm that this backend works fine with Vertica, although note that Vertica does not currently support `VALID UNTIL`.

**Comment by vishalnayak** [comment]
@consultantRR Glad that things worked out. A small point in the PostgreSQL page, mentioning that it is compatible with Vertica (along with caveats) wouldn't hurt. Thanks!

**Comment by consultantRR** [comment]
Actually, there are some additional nuances which I have discovered which in will add here shortly. Additionally, I am thinking a PR with new code may be in order.

**Comment by chuckha** [comment]
@consultantRR I'm interested in your findings. Would love to know what you discovered when trying to do this.

**Comment by jefferai** [comment]
@briankassouf probably of interest

**Comment by consultantRR** [comment]
Hi @chuckha, I'll need to look back at this in more detail, as it has been a while, but other than the `VALID UNTIL` issue I note above which I believe made expirations/revocations difficult or impossible, I think there was an additoinal issue in regards to Vertica not being 100% compatible to Postgres in the SQL commands needed to make users/grants/roles work properly, and (at the time at least) some Postgres SQL was hardcoded into the Vault backend.

I had planned to submit a PR to make the hardcoded SQL configurable, but then heard from a little birdie that a more abstracted database backend in which all the SQL was configurable for the exact purpose of supporting multiple databases in a more elegant way was in the works, so I held off. Don't know if that is/was 100% accurate or if it is still the case.

If not, I'll get myself back up to speed on this issue and contribute some additional detail. I'd personally like to see Vault working with Vertica and Redshift at the very least.

**Comment by chuckha** [comment]
[There is still some hardcoded psql in there](https://github.com/hashicorp/vault/blob/master/builtin/logical/postgresql/secret_creds.go#L71). I'll talk to some folk and see if I can find more info about that project :) Thanks so much for the update!

**Comment by consultantRR** [comment]
VoltDB is another one, although that's a whole other can of worms in that the user/grants table is defined in an XML doc. Certainly out of scope for this particular discussion.
