### ISSUE TITLE
CIDR Check failing

### ISSUE THREAD

**Issue by jwaldrip** [hashicorp/vault#1392]
I have the following user set:
```
vault write auth/app-id/map/user-id/user value=app cidr_block=10.0.0.0/16
```

But when trying to auth with HTTP:
```
curl -XPOST -d '{"app_id":"app", "user_id": "user"}' "http://127.0.0.1:8200/v1/auth/app-id/login"
```

I get the following error:
```
{"errors":["unauthorized source address"]}
```

My host address is 10.0.0.4, the server I am calling is localhost via 127.0.0.1.

***UPDATE:***

This works if I use a cidr of `10.0.0.0/15`, doesn't seem right.

**Comment by vishalnayak** [comment]
@jwaldrip 

From what I can infer, the connection is originating from `127.0.0.1` address and not from `10.x`, in case you are testing from the same machine where server is hosted.
