### ISSUE TITLE
Sub Paths with Transit Backend

### ISSUE THREAD

**Issue by nemothekid** [hashicorp/vault#1398]
I have multiple services that need to use the transit backend, and those services keep track of multiple keys based on a group of users. 

On one service I wish to have an acl like so:
```
path "transit/keys/organizations/*" {
	"capabilities" = ["create", "read", "update", "delete", "list"]
}

path "transit/encrypt/organizations/*" {
	"capabilities" = ["create", "read", "update", "delete", "list"]
}
```
(so it can encrypt, but not decrypt, **only** keys under the `/organization` path).

Where that service can create an encryption keys like `transit/keys/organizations/microsoft/garage`, `transit/keys/organizations/microsoft/closet` and `transit/keys/organization/google/garage`.

Currently it looks like the transit backend doesn't support any path that has any sub paths (so `transit/keys/microsoft` works, but `transit/keys/organizations/microsoft/` doesn't).

The advantage here is I can scope what transit keys are available to certain services

**Comment by jefferai** [comment]
Hi @nemothekid 

Unfortunately this is not supported.

**Comment by stevenscg** [comment]
@jefferai I just ran into this same issue while trying to scope my keys by service and field name. The other backends I've used have been flexible in their paths, but it never occurred to me that this one might not.

Still a no-go like it was back in May?

**Comment by jefferai** [comment]
Still a no-go. I recommend using `-` or `_` instead of slashes if you want to do this kind of separation.

**Comment by stevenscg** [comment]
Thanks! Not a problem. Underscored keys are working out well.

**Comment by ericssen** [comment]
Is it possible to encrypt path? I am trying to connect vault with Nomad using Nomad secret enabled, but when TLS enabled I always receive message that certificate is signed by unknow authority which is not true because I signed it with the same CA. I appreciate any help!
http: TLS handshake error from [IPADDRESS] remote error: tls: bad certificate
