### ISSUE TITLE
Add support for write-only policies

### ISSUE THREAD

**Issue by ernesto-jimenez** [hashicorp/vault#140]
Would you consider adding write-only policy?

Use case: you receive some secrets in your front-end app servers that you want to store securely and limit access to backend services that are cannot be accessed from the internet.

In that case, it would be good to grant a write-only policy to the app servers so they can store secrets in the vault but are forbidden from reading the secrets back.

**Comment by st33v** [comment]
+1

**Comment by jefferai** [comment]
I actually didn't know about this issue, but it's already fixed for 0.5.

**Comment by st33v** [comment]
AWESOME! you made my day. Thanks.
