### ISSUE TITLE
Can't create management consul tokens

### ISSUE THREAD

**Issue by monwolf** [hashicorp/vault#14004]
**Describe the bug**
I set up the consul ACLs and enabled the consul engine in vault and it's working fine all except when I try to generate management tokens.

![image](https://user-images.githubusercontent.com/1116133/153367375-822ed3b2-4a63-4dbf-990d-cd105e38bf66.png)

I'm using Vault 1.9.3 and Consul v1.11.2

**Comment by maxb** [comment]
In older versions of Consul, there were two types of token, client (normal), and management (superuser).

In later versions, there is only one type of token. Superuser privileges are now represented by assigning the special policy named `global-management`.

So, do not configure Vault to generate Consul management tokens, when using a modern Consul version.

(Note: I'm not affiliated with HashiCorp; I'm just a fellow user who happened to know the answer.)

**Comment by hsimon-hashicorp** [comment]
@maxb you are my favorite person today. @monwolf please let me know if that reply helps. :)
