### ISSUE TITLE
UI - User with required policy can't create new secret version

### ISSUE THREAD

**Issue by lukpep** [hashicorp/vault#14016]
user with policy:

```
path "app-secrets/data/application_1/*" {
  capabilities = ["create", "update", "read", "delete", "list", "patch"]
}

# required so that users can navigate in the UI - related to https://github.com/hashicorp/vault/issues/5362
path "app-secrets/*" {
  capabilities = ["list"]
}
```

has `Create new version` button grayed-out and inactive
![CleanShot 2022-02-11 at 14 12 08](https://user-images.githubusercontent.com/2960580/153597457-1e3b48d4-b88c-4449-8174-859bc170daa3.png)

but... if user clicks on this button with `cmd` / `ctrl` button new tab opens in the browser and user can edit the relevant secret ...

To Reproduce
create user with the above policy and verify options available in the UI

Expected behavior
Users should be allowed to create new version of secrets under the specific paths with this policy.

Environment:

Vault Server Version 1.9.2
Server Operating System/Architecture: K8s linux x86

**Comment by hashishaw** [comment]
Thank you for the detailed report @lukpep! We were able to replicate the behavior and will work on a fix. In the meantime, your workaround of clicking the button with `cmd` / `ctrl` is useful, although definitely not desired 😅
