### ISSUE TITLE
Support tls_ca_file in tcp listener

### ISSUE THREAD

**Issue by cmclaughlin** [hashicorp/vault#1405]
I don't see any support for intermediate CA certs in the tcp listener.  Looking at the docs and vault/command/server/listener.go I don't see a tls_ca_file option, like the backends support.

This would be a much appreciated addition - so we don't have to manage and specify certs on the client side.

(I'm doing my initial Vault install, so please correct me if I'm wrong)

**Comment by jefferai** [comment]
Hi @cmclaughlin ,

Similar to e.g. `nginx`, intermediate certificates can be concatenated directly to the server certificate, in chain order. 

Let me know if this doesn't solve your issue!

**Comment by cmclaughlin** [comment]
Thanks... that would be a nice addition to the docs.
