### ISSUE TITLE
Adding a File as a secret for Kubernetes

### ISSUE THREAD

**Issue by MazenElzanaty** [hashicorp/vault#14076]
I'm not sure there's a way to achieve that

**Is your feature request related to a problem? Please describe.**
I have a secret that has multiple files being mounted on the Pods

**Describe the solution you'd like**
Adding a File as secret so I can use it.

**Explain any additional use-cases**
Mounting Files on pods

**Comment by MazenElzanaty** [comment]
For example if you have a secret that has some configurations, like jdbc config

**Comment by hsimon-hashicorp** [comment]
Is there a storage backend that you could use for this scenario? https://www.vaultproject.io/docs/configuration/storage

**Comment by MazenElzanaty** [comment]
Kv should work but I trying to figure out a way to pass the binary value of files

**Comment by hsimon-hashicorp** [comment]
Would the CSI provider be of help here? https://www.hashicorp.com/blog/kubernetes-vault-integration-via-sidecar-agent-injector-vs-csi-provider
You could also consider using a Vault Agent template and the kv store. https://www.vaultproject.io/docs/agent/template

**Comment by MazenElzanaty** [comment]
I will take a look
