### ISSUE TITLE
400 error from resultant-acl endpoint

### ISSUE THREAD

**Issue by candlerb** [hashicorp/vault#14097]
**Describe the bug**
The Vault web UI is generating requests to `/v1/sys/internal/ui/resultant-acl` which are rejected by the server with error 400.

**To Reproduce**
1. Open an incognito window
2. Open the browser developer console, network tab
3. Connect to Vault
4. Look at network activity

![image](https://user-images.githubusercontent.com/44789/154251198-987fe580-6ce9-4bdd-909c-1bd26577a908.png)
![image](https://user-images.githubusercontent.com/44789/154251439-3096f5a3-beb2-439d-9053-3b2a253adfb7.png)

I am using Chrome 98 under macOS 12.2.1

**Expected behavior**
This isn't causing any problems that I can tell, except that it confused me while debugging another login problem which turned out to be unrelated - i.e. this error led me down a blind alley.

The [documentation](https://www.vaultproject.io/api-docs/system/internal-ui-resultant-acl) says that "this ... is an unauthenticated endpoint", and therefore I was surprised to see these errors.

If a token is required to access this endpoint (as the response implies), then I think it would be better if the UI were not to submit the request in the first place, knowing that it doesn't have one.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.9.3
* Vault CLI Version (retrieve with `vault version`): N/A
* Server Operating System/Architecture: Ubuntu 20.04 x86_64

**Comment by zofskeez** [comment]
@candlerb thanks for reporting this! #17139 updates the documentation and the UI no longer sends requests to that endpoint when unauthenticated.
