### ISSUE TITLE
Chef Client as Auth Backend

### ISSUE THREAD

**Issue by icebourg** [hashicorp/vault#141]
Would be great to be able to use Chef client credentials to be able to auth against vault. (I'm thinking of this specifically so a chef-client run can request certain credentials from vault using nothing more than Chef's built in PKI)

I may work on it myself if free time allows.

**Comment by sethvargo** [comment]
Hi @icebourg 

Thank you for opening an issue. Since Chef's PEM files are just PKI, couldn't you use the existing [TLS certificate](https://www.vaultproject.io/docs/auth/cert.html) support?

**Comment by icebourg** [comment]
Thanks for the suggestion. I may use that to prototype my ideas of using Chef to access secrets in Vault, but it definitely is not suitable for what I'm picturing.

We use Chef-vault right now for our secrets, and there's a fair amount of pain revolving around bootstrapped instances. I would love to do away with that pain with this workflow:

When a Chef recipe needs a secret, it queries Vault. Vault uses the provided Chef cert to validate the client against the [Chef api](https://docs.chef.io/api_chef_server.html#id16), then approves/denies the secret request based on that. Whether it's the initial node bootstrap or not, it should work exactly the same way every time.

If we used the auth module, we would need to import all the keys we are interested in to Vault. I'm unclear from the docs if it's even possible to automate that ("an operator must configure it") and even if you can, we'd have a race condition on bootstrap of making sure the key was imported before the bootstrap process needs the secret. To say nothing of maintaining yet another source of truth.

A Chef auth backend solves all those problems. The Chef key has to be on the Chef server before Chef will dole out the recipes, so barring any caching the Chef-api might do, as soon as the recipe needs a secret, Vault will authorize it reliably, even on bootstrap. That also opens a whole new world of automation that we can't currently do with Chef-vault. (at least easily/reliably)

AJ

**Comment by sethvargo** [comment]
Hi @icebourg 

It's still a bit unclear to me what problem you are trying to solve. The client isn't fully registered with the Chef Server until after the first CCR has successfully completed. Thus, during an initiation bootstrap, the Vault authentication would fail anyway.

> The Chef key has to be on the Chef server before Chef will dole out the recipes

That's not how the initial bootstrap process works unfortunately. During bootstrap, the node is provisioned using a run_list that is sent as json in a first-boot.json file. Only after the first CCR successfully completes is the node fully registered with the Chef Server and the run_list is persisted.

We created the [AppID auth backend](https://www.vaultproject.io/docs/auth/app-id.html) for such a purpose (and to avoid this race condition). I do not think it makes sense to have the Chef Server as the central source of trust.

**Comment by icebourg** [comment]
Hey Seth,

Correct, the run list and node info isn't saved until the first Chef run is successful. My bad on that but the key and node/clients do exist even if the node data is empty (Chef vault can't work without the key) it just means you can't use ACLs against run list items at bootstrap which would be a handy feature but not totally necessary for what I'm looking for. 

> I do not think it makes sense to have the Chef Server as the central source of trust.

I would love to hear your reasoning because that's basically exactly what I want.

Thanks

AJ

**Comment by sandstrom** [comment]
*a friendly note: @icebourg you probably know, but Seth used to work at OpsCode/Chef; not that it precludes him from mistakes, but I think it's likely that he knows what he's talking about :)*

**Comment by icebourg** [comment]
I am aware, that's why I asked for his thoughts. Thanks.

**Comment by mfischer-zd** [comment]
Having Chef Server be the principal or proxy isn't a terrible idea.  Maybe you could ask Chef about that?  Perhaps they can add an API endpoint and client support for obtaining secrets.

That said, I can't imagine what you'd do with the secrets gathered by chef-client other than write them in the clear to disk, which sort of defeats the purpose of keeping them in a Vault.

**Comment by icebourg** [comment]
Hey @mfischer-zd,

So my initial thought was to use Chef as the authorization backend for Vault so that you can use Vault secrets in Chef recipes.

For example: I need to write a database password to an app's configuration. So in my recipe, to get the password, I call some library that calls out to the Vault server. And to authenticate the call, the library uses the PKI infrastructure already in place with Chef. It's the same as the [TLS backend](https://vaultproject.io/docs/auth/cert.html) -- but it takes out the administrative overhead of syncing the Vault data with the Chef server. Let the Chef server be the single source of truth.

However, I've lost most of my interest in Vault as I realized that this scheme wouldn't allow us to ACL secrets by Chef run list (because of how Chef works as Seth pointed out earlier). I originally thought that it wouldn't be a big deal, but the more I consider it, the more I think it's a deal breaker for my situation.

I know a lot has been happening on the Chef side for bootstrapping of nodes, so I'm going to be watching there to see if the situation changes. But I'll go ahead and close this issue since I doubt I will be working on this idea in the immediate future.

AJ
