### ISSUE TITLE
Vault with File system storage backend

### ISSUE THREAD

**Issue by Niks-JJ** [hashicorp/vault#1411]
Hi,

For our application, we want to use Vault's transit backend  for cryptography. Some questions on storage backend, in order to decide a suitable backend 

1) Do we necessarily need a storage backend if we are using it only for encryption/decryption and return values back through rest end point?
I think yes, as encrypy/decrypt end point use keys and keys will be stored in backend, right?
2) Consuls works very well as backend but involves consul set up, clustering etc. 
How about File system? Apart from fact that it does not support HA, any other issue?
In case of any fail over, can file from file system be simply copied and pointed to vault on another server, and make it encrypt/decrypt with same keys as before?

3) How about MySQL and s3?
In case of any fail over, can data from from these servers be simply copied and entered into another server's database and pointed to vault , and make it encrypt/decrypt with same keys as before?

Thanks.
Niks

**Comment by BRMatt** [comment]
> 1) Do we necessarily need a storage backend if we are using it only for encryption/decryption and return values back through rest end point?

Yes, the encryption keys the transit backend uses will need to be stored in the storage backend. If you don't store the keys you won't be able to decrypt the ciphertext. 😃 

> 2) Consuls works very well as backend but involves consul set up, clustering etc. 
How about File system? Apart from fact that it does not support HA, any other issue? In case of any fail over, can file from file system be simply copied and pointed to vault on another server, and make it encrypt/decrypt with same keys as before?

Lack of HA is probably the biggest issue, and will likely make it extremely difficult to operate without downtime. I wouldn't recommend trying to do this, it'd be easier to run consul for coordination. If you're just using the transit backend then vault should be able to serve the majority of requests out of its in memory cache. 

> In case of any fail over, can data from from these servers be simply copied and entered into another server's database and pointed to vault , and make it encrypt/decrypt with same keys as before?

If you're using MySQL/S3 then you can point all vault servers at the same database/bucket, though you'll need to configure an [`ha_backend`](https://www.vaultproject.io/docs/config/index.html#ha_backend) (e.g. consul, zookeeper) to ensure that only 1 vault server is handling requests and writing to the storage backend. Vault uses a number of in-memory locks, so it's not safe for multiple servers to write to the storage backend at the same time.

**Comment by Niks-JJ** [comment]
Thanks Matt.
1 ) Yes, agreed
2) Regarding: Lack of HA is probably the biggest issue, and will likely make it extremely difficult to operate without downtime. I wouldn't recommend trying to do this, it'd be easier to run consul for coordination. If you're just using the transit backend then vault should be able to serve the majority of requests out of its in memory cache. 

--> Even for Vault transit backend, storage backend is required, as we discussed in point 1. in memory cache is just for performance, storage backend is still must. Right?

3) Didn't understand. If we are using MySQL/S3 as storage backend, how can we configure another backend for storage? Can you please elaborate

4) Another questions: 
4a) Does Vault and consul need to be on same server? or backend consul can be configured on another server?
4b) Is it recommended that Vault HA should have a cluster of consul or even I consul server is ok if we make sure of it's availability?

Thanks

Niks

**Comment by jefferai** [comment]
Hi @Niks-JJ ,

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
