### ISSUE TITLE
The default schema used in the mysql backend is insufficient for KVv2 storage

### ISSUE THREAD

**Issue by drawks** [hashicorp/vault#14114]
**Describe the bug**
When upgrading a KVv1 mount to KVv2 on a server using the mysql backend the column width of `vault_key` will be insufficient for storing the values used with the KVv2 mount.

**To Reproduce**
1.  Configure vault with a KVv1 mount `vault secrets enable -version=1 kv`
2. Store some secrets in the KVv1 mount at an arbitrary depth ala `vault kv put /kv/foo/bar/bing/band/bong/ding/dong baz=boo`
3. Upgrade mount with `vault kv enable-versioning secret/`
4. Observe command returns, but vault never completes KVv2 upgrade and mount becomes unusable.
```
$ vault kv get /kv/foo/bar/bing/band/bong/ding/dong
Error reading kv/data/foo/bar/bing/band/bong/ding/dong: Error making API request.

URL: GET http://127.0.0.1:8200/v1/kv/data/foo/bar/bing/band/bong/ding/dong
Code: 400. Errors:

* Upgrading from non-versioned to versioned data. This backend will be unavailable for a brief period and will resume service shortly.
```
And there is a single error in the logs detailing what happened
```
Feb 13 07:21:32 localhost.localdomain vault[30523]: 2022-02-13T07:21:32.529Z [INFO]  secrets.kv.kv_fb3379c9: collecting keys to upgrade
Feb 13 07:21:32 localhost.localdomain vault[30523]: 2022-02-13T07:21:32.530Z [INFO]  secrets.kv.kv_fb3379c9: done collecting keys: num_keys=2
Feb 13 07:21:32 localhost.localdomain vault[30523]: 2022-02-13T07:21:32.538Z [ERROR] secrets.kv.kv_fb3379c9: upgrading resulted in error: error="Error 1406: Data too long for column 'vault_key' at row 1" progress=1/2```

**Expected behavior**
Mount is successfully upgraded and continues working.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.9.1
* Vault CLI Version (retrieve with `vault version`): 1.9.1
* Server Operating System/Architecture: CentOS 7

**Additional context**
Manually updating the schema of the vault database before conducting the upgrade results in proper operation: `alter table vault modify vault_key varchar(3072);`

**Comment by drawks** [comment]
@hsimon-hashicorp I've updated my issue with a bit more detail, I suspect that this is a very small PR to fix this.

Updating `512` to `3072` here: https://github.com/hashicorp/vault/blob/main/physical/mysql/mysql.go#L123 should do the trick for making new vault installations work correctly. Updating the schema on existing installations will require a bit more code though.

**Comment by hsimon-hashicorp** [comment]
@drawks Please feel free to get a PR filed for this, and we will be happy to review it! If you prefer, I can certainly have our team take a look and get a fix taken care of, but it might take a little longer. Thanks for your diligence, it's always appreciated. :)

**Comment by drawks** [comment]
@hsimon-hashicorp The above PR is at least a partial fix. I'm not sure how best to handle the case of existing installations. I'm reticent to start issuing table modifications on existing databases automatically. Perhaps raising some log noise would be appropriate? Similarly I'm not sure if there is a sane way to handle rolling back a failed KVv1>KVv2 upgrade since that happens a layer above the physical layer.
