### ISSUE TITLE
vault ssh fails when node is not in known_hosts

### ISSUE THREAD

**Issue by consultantRR** [hashicorp/vault#1413]
Fails:

```
$ vault ssh -role ssh-role user@172.17.20.5
Failed to establish SSH connection:exit status 6
```

Now adding to known_hosts:

```
$ ssh user@172.17.20.5
The authenticity of host '172.17.20.5 (172.17.20.5)' can't be established.
ECDSA key fingerprint is SHA256:t10ECPpGGRvCPk7Cwnr0o2zL/Q6XAaeGTZgozIeT2Eg.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '172.17.20.5' (ECDSA) to the list of known hosts.
Password: 
<<ctrl-c>>
```

Now it works:

```
$ vault ssh -role ssh-role user@172.17.20.5
Last login: Fri May 13 16:33:43 2016 from 172.17.20.2
```

**Comment by steve-jansen** [comment]
I'm also seeing `Error while running ssh command:exit status 255` when the host identity (key) changes (ie., new AWS instance on a previously used IP address)

**Comment by jefferai** [comment]
@vishalnayak I think your recent fixes fix this too, right?

**Comment by vishalnayak** [comment]
@jefferai, yes.
Both host key checking and the remote fingerprint changing can be
suppressed with the options now.

On Saturday, June 4, 2016, Jeff Mitchell <notifications@github.com> wrote:

> @vishalnayak <https://github.com/vishalnayak> I think your recent fixes
> fix this too, right?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hashicorp/vault/issues/1413#issuecomment-223758309>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC6YaDbltKbeCfpqnQtIh3U8-B_qxmXSks5qIYpJgaJpZM4IeLzY>
> .
>


-- 
vn

**Comment by jefferai** [comment]
:+1:
