### ISSUE TITLE
Unable to put .pas file on the vault

### ISSUE THREAD

**Issue by snehavenkatayogi** [hashicorp/vault#14146]
**Describe the bug**
A clear and concise description of what the bug is: error says it cannot parse the file

**Expected behavior**
A clear and concise description of what you expected to happen: Requirement is to put a pascal file which contains credentials in the vault and access the credentials through Jenkins.

**Environment:**
* Vault Server Version (retrieve with `vault status`): latest
* Vault CLI Version (retrieve with `vault version`): latest
* Server Operating System/Architecture: windows 10

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
storage "raft" {
  path    = "./vault/data"
  node_id = "node1"
}

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = "true"
}

api_addr = "http://127.0.0.1:8200"
cluster_addr = "https://127.0.0.1:8201"
ui = true

```

**Additional context**

**Comment by hsimon-hashicorp** [comment]
Can you provide more information about the error? Thanks! :)

**Comment by maxb** [comment]
(Note: I'm not affiliated with HashiCorp; this issue just caught my eye whilst browsing the issue tracker)

Vault does not support storing files. It supports storing text data in its KV secrets engine, though. Depending on the specifics of your use case, this might be suitable.

Adding a file's content to a KV using the Vault CLI:
```
vault kv put kv/myfile content=@myfile
```

Reading it back:
```
vault kv get -field=content kv/myfile
```

WARNING: The file's content must be valid UTF-8 text - binary files get silently corrupted.

The maximum file size will be limited by limitations on the size of an individual item in the Vault storage backend. For Raft I believe this is around 1MB.
