### ISSUE TITLE
[1.5.2] inconsistent behavior /sys/policies/acl vs /sys/policy

### ISSUE THREAD

**Issue by peppe77** [hashicorp/vault#14149]
K8S 1.20
Vault 1.5.2

Using terraform/vault provider and when tried to update (write) to an existing policy, get a 403. After some digging, this is what tf sends to vault ->  PUT /v1/sys/policies/acl/ though as you can see below, the admin-policy should have allowed it. 

Admin-policy
```
path "*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
```
Here did some testing with postman and you can see that /sys/policy works for read, list and write though /sys/policies/acl does not work for most (only works for read)

```LIST
[GET] v1/sys/policies/acl/ - 405
[GET] v1/sys/policy/:name - works

READ
[GET] v1/sys/policy/:name - works
[GET] v1/sys/policies/acl/:name - works

WRITE
[PUT] /v1/sys/policies/acl/:name - 403
[PUT] /v1/sys/policy/cdshop-auth-policy - works
```

```
"request":{"id":"49893e8c-ae24-2e81-86ae-c11cc1ac4d7d","operation":"update","mount_type":"system","client_token":"hmac-sha256:ac375f9b218a15297616e02b7d5e9107f2ce712118ce88a5f3c5ba1ee41cb6f2","client_token_accessor":"hmac-sha256:f15640a8bebedfc517823eb186a6d1a6ab4cf3a68cf9017b37a01eb36e88253c","namespace":{"id":"root"},"path":"sys/policies/acl/cd-auth-policy","data":{"rules":"hmac-sha256:2b1335b313b9ae9d2658e6141ea60f209db8aa4485fed267517457b0eb74ff37"},"remote_address":"100.118.104.84"},"response":{"mount_type":"system","data":{"error":"hmac-sha256:eba39ca7b22534ebc427b9fbcc7d70571281a04982b0fc736af6cc5c40ac282b"}},"error":"1 error occurred:\n\t* permission denied\n\n"}
```

**Comment by maxb** [comment]
> [GET] v1/sys/policies/acl/ - 405

This is expected, you want GET v1/sys/policies/acl/?list=true (or the custom LIST HTTP verb)



> [PUT] /v1/sys/policies/acl/:name - 403

My **guess** is that you have been tripped up by the sometime-surprising way Vault combines policies.

Let's imagine you have a `general-user` policy that contains
```hcl
path "sys/policies/acl/*" {
  capabilities = ["read", "list"]
}
```
and you assign this to every user so they can see what policies are in force.

If you now have a user who has both your `admin-policy` policy and the `general-user` policy, can they write to `sys/policies/acl/:name`? Turns out the answer is no, because Vault treats the more specific path as overriding the capabilities granted on `path "*"`.

**Comment by peppe77** [comment]
@maxb we have not written any policy for sys/policies/acl, therefore the admin-policy should be the only one. This can be illustrated by the fact that we can write[PUT] towards many other polices (204 is returned and can confirm that update went through). Why we can then update all polices via /sys/policy though thats not the same case when we try via /sys/policies/acl - as reported - in this case some works and some fails.
It i interesting to note that the ones that fails (only via /sys/policies/acl) we also noticed that edit option via UI is not rendered. (and polices have been provisioned via same way - TF/Vault provider). It seems a bug, no?

**Comment by maxb** [comment]
(Note: I should clarify, just to make sure there's no misunderstanding, that I'm not affiliated with HashiCorp, I'm just a fellow user who saw an issue that sounded possibily familiar.)

So, you're saying that you see the behaviour:
```
PUT /v1/sys/policies/acl/some-policy-name - succeeds
PUT /v1/sys/policies/acl/some-different-policy-name - permission denied
```
?

I cannot imagine how that could come about, other than via policy configuration.
That you see that the edit option in the web UI is disabled for some policies supports this - the UI checks using `sys/capabilities-self` what capabilities you are granted on each policy to know which operations to display.

My suggestion for how to debug this further, would be to get a list of all policies associated with the logged in token exhibiting this behaviour, and either carefully examine them, or post their full contents here for others to help.

It looks like you posted a fragment of audit log JSON previously - you can find the policies at auth.policies within the audit log entry.

It would also be useful to mention whether you're using Vault Enterprise, so we know whether Sentinel policies could also be contributing to the issue.

Lastly, Vault 1.5 is *really* old now...

**Comment by peppe77** [comment]
@maxb I do agree that 1.5.2 is old and will look into upgrading it in the near future. However, still curious about this problem. The polices are all provisioned the same way  :) Just took compared working/not-working case: Policy A == Policy B. Considering that - still having hard time to understand how some policy A can be updated via the below endpoint and Policy B can not?

```
PUT /v1/sys/policies/acl/some-policy-name - succeeds (Let's call Policy A)
PUT /v1/sys/policies/acl/some-different-policy-name - permission denied (Let's call Policy B)
```

I can also add that when I call:
```
[GET] /v1/sys/internal/ui/resultant-acl

Only see some of the polices shown for  "sys/policies/acl/" even though every single policy has it. 
```

That would explain why some polices can be updated via the above endpoint and some can not. Imhpo, it feels like a bug if you consider that all polices in question are pretty much the same. They all have  "sys/policies/acl/" though as mentioned above,  when I call " /v1/sys/internal/ui/resultant-acl" then only few shows " /v1/sys/internal/ui/resultant-acl [capabilities]"

Not using Vault Enterprise, therefore Sentinel is not a factor in our case.

**Comment by maxb** [comment]
> I can also add that when I call:
> 
> ```
> [GET] /v1/sys/internal/ui/resultant-acl
> 
> Only see some of the polices shown for  "sys/policies/acl/" even though every single policy has it. 
> ```

This tells me a lot - the fact that any of your policy names are showing up in the resultant-acl endpoint indicates you have fine-grained permissions applied to individual policy paths - which both explains the behaviour you're seeing and isn't something you've mentioned before in this issue.

I believe we've hit a point where any further progress requires you to show the actual contents of all policies applying to your Vault request.

**Comment by peppe77** [comment]
Polices looks like below shown though some can be updated and some can not (via /sys/policies/acl). Moreover, the ones that can not be updated are the ones that shown in the resultant-acl (specifically sys/policies/acl/ capabilities - which exists in all the policies for all KVs). The one that applies to me (admin) is in my first post to this thread.

```
# Team can manage their own KV secrets backend
path "pedro-kv/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

# Team can manage their own Transit secrets backend
path "pedro-transit/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

# Team can manage their own PKI secrets backend
path "pedro-pki-root/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "pedro-pki-intermediate/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "pedro-database/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

# Team can login with Kubernetes auth backend
path "auth/pedro-kubernetes/login" {
  capabilities = ["create", "read"]
}

path "auth/pedro-kubernetes/*" {
  capabilities=["read"]
}

# Team can read their namespace policy (required for teams to be able to plan with TF)
path "sys/policies/acl/pedro-policy" {
  capabilities=["read"]
}
```

**Comment by maxb** [comment]
Right, here is the answer. As I expected, it's because of the way Vault combines policies.

You possess both `admin-policy` and `pedro-policy`.

You are expecting that when you attempt to write to `sys/policies/acl/pedro-policy`, that the permissions from `admin-policy` will apply:
```
path "*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
```

But you also possess `pedro-policy`. That has a more restrictive rule:
```
path "sys/policies/acl/pedro-policy" {
  capabilities=["read"]
}
```

Vault chooses to apply the second, where you only have `"read"` capability. It does *NOT* merge in the permissions from the `path "*"` block.

Try this: remove `pedro-policy` from your user, so that you ONLY have `admin-policy`. Now you'll be able to write to `sys/policies/acl/pedro-policy`.

**Comment by peppe77** [comment]
Not sure if I follow you. Have over 60 polices (KVs) that looks like the one I shared. Some can be updated and some can not - considering that there is no difference between them other than the policy name/kv then why vault would allow updates to some policies and not to others?

**Comment by maxb** [comment]
Please could you do this:
```
vault token lookup | grep policies
```
and share the result?

**Comment by peppe77** [comment]
hmm. I see now what you meant. As I belong to different teams (tenants) as well as infra(admin), ended up having problems to update polices due to the more restrictive teams policies associated (as you had mentioned earlier). Have to remove myself from tenants' teams and that shall leave me only the admin-policy. In this case, I should then be able to manually and/or via TF/vault provider to update the polices as there wont be any other more restrictive police. 

Should have paid more attention to the long list returned when I do vault login via CLI as it returns the same as command you posted above.  Appreciated the help
