### ISSUE TITLE
Instructions to install vault using apt package uses deprecated too apt-key

### ISSUE THREAD

**Issue by shwuandwing** [hashicorp/vault#14169]
**Describe the bug**
Instructions to install vault on ubuntu/debian using [apt](https://learn.hashicorp.com/tutorials/vault/getting-started-install) use deprecated tool apt-key.  Users get a message -- "Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8))."  Looking up the warning online, it mentions apt-key was deprecated to impreove security.

**To Reproduce**
1. Go to https://learn.hashicorp.com/tutorials/vault/getting-started-install
2. Follow instructions to Hashicorp GPG key (curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -)
3. See warning message.

**Expected behavior**
Step to install hashicorp apt gpg key using trusted.gpg.d like the warning message.

**Comment by brotherdust** [comment]
If anyone else stumbles on this issue, here's what I did:
```
curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null; echo "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com jammy main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
```

**Comment by kitography** [comment]
Fixed here: https://github.com/hashicorp/tutorials/commit/dd6da994c53439757f9f7089bbd39e2ef8a7e6a3
