### ISSUE TITLE
raft snapshot certificate error

### ISSUE THREAD

**Issue by mmittel2** [hashicorp/vault#14177]
**Describe the bug**
When running the command `vault operator raft snapshot save 0001.snap` on a follower node running in a vault ha cluster:
```Error taking the snapshot: Get "https://192.168.1.40:8200/v1/sys/storage/raft/snapshot": x509: certificate is valid for 127.0.0.1, not 192.168.1.40```
Looks like on snapshot creation the follower is connecting to the leader by ip, though I configured raft to use the domain. Other communication seems to be working. 
To me it looks like a bug. Maybe I missed a config option?

**To Reproduce**
1. Setup Vault ha cluster with raft using the helm chart using a certificate for the domain *.vault-internal, localhost, 127.0.0.1
2. Init and unseal every node.
3. Run `vault operator raft snapshot save 0001.snap` on any follower node.

**Expected behavior**
The snapshot command should connect to the leader node by using its domain name.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.9.2
* Vault CLI Version (retrieve with `vault version`): 1.9.3
* Server Operating System/Architecture: Official docker container  

Vault server configuration file(s):

```hcl
disable_mlock = true
ui = true
listener "tcp" {
  address = "[::]:8200"
  cluster_address = "[::]:8201"
  tls_ca_cert_file = "/vault/userconfig/vault-cert/ca.crt"
  tls_cert_file = "/vault/userconfig/vault-cert/tls.crt"
  tls_key_file = "/vault/userconfig/vault-cert/tls.key"
}

storage "raft" {
  path = "/vault/data"
  retry_join {
    leader_api_addr = "https://vault-0.vault-internal:8200"
    leader_ca_cert_file = "/vault/userconfig/vault-cert/ca.crt"
    leader_client_cert_file = "/vault/userconfig/vault-cert/tls.crt"
    leader_client_key_file = "/vault/userconfig/vault-cert/tls.key"
  }
  retry_join {
    leader_api_addr = "https://vault-1.vault-internal:8200"
    leader_ca_cert_file = "/vault/userconfig/vault-cert/ca.crt"
    leader_client_cert_file = "/vault/userconfig/vault-cert/tls.crt"
    leader_client_key_file = "/vault/userconfig/vault-cert/tls.key"
  }
  retry_join {
    leader_api_addr = "https://vault-2.vault-internal:8200"
    leader_ca_cert_file = "/vault/userconfig/vault-cert/ca.crt"
    leader_client_cert_file = "/vault/userconfig/vault-cert/tls.crt"
    leader_client_key_file = "/vault/userconfig/vault-cert/tls.key"
  }

  autopilot {
    cleanup_dead_servers = "true"
    last_contact_threshold = "200ms"
    last_contact_failure_threshold = "10m"
    max_trailing_logs = 250000
    min_quorum = 5
    server_stabilization_time = "10s"
  }

}
```

**Additional context**

Certificate resource:

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-cert
  namespace: vault
spec:
  secretName: vault-cert
  dnsNames:
    - "localhost"
    - "*.vault-internal"
  ipAddresses:
    - "127.0.0.1"
  issuerRef:
    name: vault-ca-issuer
```

**Comment by aphorise** [comment]
Hey @mmittel2 - is this still relevant for you and did you already try the above suggestion?

**Comment by aphorise** [comment]
Closing due to no response. Please reopen if still relevant.
