### ISSUE TITLE
ssh otp throwing errors while parsing credentials response

### ISSUE THREAD

**Issue by sokoow** [hashicorp/vault#1418]
I got something like this while using otp with newest vault-ssh-helper:

```
 vault ssh -role otp_key_role sokoow@XX.XX.XX.XX
Error parsing the credential response:1 error(s) decoding:

* 'port' expected type 'int', got unconvertible type 'json.Number'
```

**Comment by jefferai** [comment]
@vishalnayak did vault-ssh-helper get a release recently? It will need a release (and updating for this) when the new release of Vault is out. I have a feeling this is coming from self-built though.

**Comment by sokoow** [comment]
It is indeed Self built on my side

**Comment by jefferai** [comment]
Actually, I think that this is in Vault itself and is rather subtle. The `ssh` command takes the decoded Secret response and uses `mapstructure` to pull it into a struct. What's actually complaining here is `mapstructure`. Probably the necessary thing to do is to change the struct in `command/ssh.go` to have the port be a `json.Number` and then use the string value of that for the port; however, it *may* simply work to make that a string.

**Comment by jefferai** [comment]
Actually, the best thing to do here would be to fix mapstructure to do the right thing when it encounters a json.Number.

**Comment by sokoow** [comment]
Any idea on when this is going to be fixed ? It basically pulls down a whole functionality
