### ISSUE TITLE
jwt auth API: document `client_nonce`

### ISSUE THREAD

**Issue by candlerb** [hashicorp/vault#14188]
**Describe the bug**
The API documentation for the JWT/OIDC Auth Method doesn't mention that the `auth_url` and `callback` endpoints both accept a `client_nonce` parameter.

**To Reproduce**
<https://www.vaultproject.io/api-docs/auth/jwt#oidc-authorization-url-request>
<https://www.vaultproject.io/api-docs/auth/jwt#oidc-callback>

**Expected behavior**
`client_nonce` should be documented.  There is some code which uses it [here](https://github.com/hashicorp/vault-plugin-auth-jwt/blob/v0.11.4/cli.go#L192-L198) and [here](https://github.com/hashicorp/vault-plugin-auth-jwt/blob/v0.11.4/cli.go#L149-L154) (auth_url and callback respectively)

**Comment by WeetA34** [comment]
Hello,
I tested on my environment. It works with and without client_nonce.
I'm also curious to know if it's useful.
Thank you

**Comment by austingebauer** [comment]
@candlerb - Thanks for finding this. I'll get the docs updated now.

@WeetA34 - The `client_nonce` is not a part of the OIDC spec or required for the auth flow. We use the value to ensure that the client (e.g., Vault CLI, Vault UI) that obtained the original authorization URL is the same one that posts back to the `callback` endpoint. It's an additional (yet optional) security measure we take by default in our clients.

**Comment by WeetA34** [comment]
Hello @austingebauer 
thank you for the explanation.
I just tested. As expected I got `invalid client_nonce` error if send client_nonce in auth_url data but not (or a wrong one) in call_back data.
It seems that client_nonce can be something other than a 20 characters base62 string.
