### ISSUE TITLE
Generated credentials’s Time-to-Live on UI is not reflecting real value

### ISSUE THREAD

**Issue by RafaelMontegordoFelix** [hashicorp/vault#14191]
**Describe the bug**
On vault version 1.9.3 when accessing the ui on the Database roles screen the "Generated credentials’s Time-to-Live" is always 1h.

**To Reproduce**
1. Open Ui
2. Enable Database secrets engine
3. Create a database connection with plugin mssql-database-plugin
4. Create a role, set the TTL diferent from 1h
5. The screen will show 1h as ttl.
6. It's a visual problem only.

**Expected behavior**
It should reflect the value introduced by the user.

**Environment:**
![image](https://user-images.githubusercontent.com/16720099/155105860-0d3b4db8-4c21-4099-aa7b-251870a0e1f0.png)
* Server Operating System/Architecture:
* Ubunto 18.04.5 LTS

Vault server configuration file(s):

**Comment by hashishaw** [comment]
Hi @RafaelMontegordoFelix, thank you very much for this detailed bug report and repro steps! We will have a fix for it shortly. Have a great week!
