### ISSUE TITLE
Vault Agent: support static tokens from `vault login`

### ISSUE THREAD

**Issue by grahamc** [hashicorp/vault#14200]
**Is your feature request related to a problem? Please describe.**

I'm working on something involving `vault agent`. The interesting part of my project doesn't involve how Vault gets its token. Setting up extra Vault infrastructure around automatic authentication is a bit of a chore for this. 

**Describe the solution you'd like**

While iterating on the configuration, it would be neat if `vault agent` would/could use the token on my workstation which I got from `vault login`.

**Describe alternatives you've considered**

Setting up a local test cluster of Vault, or creating an approle that I can use locally for testing.

**Explain any additional use-cases**

This is essentially intended in a "just run once and let's see what happened" development environment scenario.

**Additional context**

n/a

**Comment by HridoyRoy** [comment]
Hi @grahamc ,
Could you expand a little on the functionality you're looking for with this change? Vault agent should already pick up the token from your environment, so long as auto-auth is not enabled.

**Comment by hsimon-hashicorp** [comment]
Hi @grahamc - since it's been a while since we've heard from you on this request, I'm going to go ahead and close it now. Please feel free to re-open or open a new issue as needed. Thanks! :)

**Comment by VioletHynes** [comment]
Hi there! Just wanted to report some good news, as this feature has been implemented in https://github.com/hashicorp/vault/pull/18740 and will be available in Vault 1.13.

Thanks for the report. The enthusiasm for this feature helped us prioritize it!
