### ISSUE TITLE
feature-request: vault returns a unique identifier to vault-ssh-helper

### ISSUE THREAD

**Issue by ProbablyRusty** [hashicorp/vault#1421]
Could Vault perhaps return a unique identifer to vault-ssh-helper that it could log, while Vault itself also logs this identifier in its own audit backend(s) so that vault-ssh-helper logs on a node can be easily correlated with audit logs on Vault?

Additionally (and I haven't yet thought through how easy or difficult this would be to implement), could vault-ssh-helper perhaps populate an env var in the user's login shell with this unique identifier for other uses? (I'm thinking of perhaps an immutable env var in an rbash shell which could be used by other processes to better identify the particular Vault user in that particular shell session.)

If the above is messy to implement, or an undesirable feature design for other reasons, then are there other ideas out there as to how to correlate specific users to specific ssh logins in a case where, say, many users ssh into a host as the same generalized linux account name?

**Comment by jefferai** [comment]
Generally this is supported by using the OTP or CA versions of the backend so I'm going to close this.
