### ISSUE TITLE
too many open files with consul backend

### ISSUE THREAD

**Issue by st33v** [hashicorp/vault#1428]
My vault server seems to be opening 1024 connections to localhost:8500 and then running out of open files. I've tried setting max_parallel in the consul backend but it doesn't seem to do anything.

```
[root@ip-10-48-106-69 a568347]# vault -v
Vault v0.5.2
[root@ip-10-48-106-69 a568347]# consul -v
Consul v0.6.3
Consul Protocol: 3 (Understands back to: 1)
[root@ip-10-48-106-69 a568347]# cat /etc/vault/vault.config 
backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault" 
  token = "foo"
  max_parallel = 4
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/etc/pki/tls/certs/vault.pem"
  tls_key_file = "/etc/pki/tls/private/vault.key"
}

disable_mlock = true
[root@ip-10-48-106-69 a568347]# lsof -p $(pidof vault) |wc -l
533
[root@ip-10-48-106-69 a568347]# lsof -p $(pidof vault) |wc -l
773
etc.....
```

**Comment by st33v** [comment]
This might be unrelated to the consul backend. the clients that are connecting are using the consul secrets backend to request a consul token. I believe that request is establishing new connections and not removing the old ones.

**Comment by jefferai** [comment]
Sorry about this. I've identified a fix and will close this shortly.

**Comment by st33v** [comment]
Thanks. I appreciate the quick response!

--steve


On May 17, 2016, at 7:47 PM, Jeff Mitchell <notifications@github.com> wrote:

Sorry about this. I've identified a fix and will close this shortly.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/hashicorp/vault/issues/1428#issuecomment-219896017>
