### ISSUE TITLE
Vault UI Displays Non-Existent Dates for Token Expiring

### ISSUE THREAD

**Issue by BrianH824** [hashicorp/vault#14299]
**Describe the bug**
The warning popup for an expiring token displays the incorrect date. Example: 
"We've stopped auto-renewing your token due to inactivity. It will expire in about 1 hour. On February 59th 2022, 8:47:48 AM"

**To Reproduce**
ui/vault/secrets -> Dropdown from user profile icon in upper right corner

**Expected behavior**
I would expect this to display "We've stopped auto-renewing your token due to inactivity. It will expire in about 1 hour. On February 28th 2022, 8:47:48 AM"

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.7.0
* Vault CLI Version (retrieve with `vault version`): 1.9.3
* Server Operating System/Architecture: Windows 10--Chrome

**Additional context**

![image](https://user-images.githubusercontent.com/61054830/155994439-2906e294-f0e8-435e-9489-d8b14509aa34.png)

**Comment by hsimon-hashicorp** [comment]
Hi! This was fixed in this PR: https://github.com/hashicorp/vault/pull/11984 that was milestoned for 1.7.5. Thanks! :)
