### ISSUE TITLE
Cannot delete database secret engine, once a dynamic user/password was issued

### ISSUE THREAD

**Issue by weitzjdevk** [hashicorp/vault#14296]
**Describe the bug**
Cannot delete database secret engine, once a dynamic user/password was issued

**To Reproduce**

# main.tf

```terraform
terraform {
  required_version = ">= 0.13.7, < 2"

  required_providers {
    vault = {
      source  = "hashicorp/vault"
      version = ">= 3.2.1, < 4"
    }
  }
}

resource "vault_mount" "example" {
  path        = "postgres-database"
  type        = "database"
  description = "This is an example mount"
}

resource "vault_database_secret_backend_connection" "postgres" {
  backend       = vault_mount.example.path
  name          = "postgres"
  allowed_roles = ["dev", "prod"]

  postgresql {
    connection_url = var.postgres_connection_url
  }
}

resource "vault_database_secret_backend_role" "role" {
  backend             = vault_mount.example.path
  name                = "dev"
  db_name             = vault_database_secret_backend_connection.postgres.name
  creation_statements = ["CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';"]
}

```

# dynamic_creds_test.go (valid test, generates a username/password)

```go
// this is a working test and returns without errors
// the test generates credentials on the fly
config := vault.DefaultConfig()
config.Address = "https://vault-terratest-hqq4g5.canary.example.org"
client, err := vault.NewClient(config)
require.NoError(t, err)
client.SetToken("mytoken")

// generate a new Postgres connection string
vaultSecret, vaultErr := client.Logical().Read("postgres-database/creds/dev")
require.NoError(t, vaultErr)
require.NotNil(t, vaultSecret)
require.NotNil(t, vaultSecret.Data)

username, ok := vaultSecret.Data["username"]
require.True(t, ok)
userNameString, typeCastOK := username.(string)
require.True(t, typeCastOK, "should be a type:string")
require.NotEmpty(t, userNameString)
```

**Expected behavior**
I should be able to delete the vault-mount via terraform (when usernames, password were created)
This works, if I create a backend with terraform but never used it.

**Environment:**
* Vault Server Version: vault-1.9.3 linux amd64
* `go.mod`   github.com/hashicorp/vault/api v1.4.1
* Server Operating System/Architecture: Linux AMD54

**Additional context**

Error Log from terraform delete:

        	            	Error: error deleting from Vault: Error making API request.
        	            	
        	            	URL: DELETE https://vault-terratest-hqq4g5.canary.example.org/v1/sys/mounts/postgres-database
        	            	Code: 400. Errors:
        	            	
        	            	* failed to revoke "postgres-database/creds/dev/R75eG0ZCkYwQrndACWj5RFv6" (1 / 1): failed to revoke entry: resp: (*logical.Response)(nil) err: failed to find entry for connection with name: "postgres"

Error Message in Vault-UI:

There was an error disabling the database Secrets Engine at postgres-database/: failed to revoke "postgres-database/creds/dev/R75eG0ZCkYwQrndACWj5RFv6" (1 / 1): failed to revoke entry: resp: (*logical.Response)(nil) err: failed to find ent

![image](https://user-images.githubusercontent.com/52415337/155845941-a3eea208-4ec3-4d39-956b-3e3950f523db.png)
        	            	
        	            	
![image](https://user-images.githubusercontent.com/52415337/155845920-e69356b4-373c-4b62-8f31-78025a9bcc98.png)
![image](https://user-images.githubusercontent.com/52415337/155845925-9e46099c-580b-4ec3-97d5-5f29615704fd.png)
![image](https://user-images.githubusercontent.com/52415337/155845930-79884c7b-bd52-4b2c-a3aa-c566c0b38b39.png)
![image](https://user-images.githubusercontent.com/52415337/155845931-aca1a89f-2d9e-4115-bbc2-d408d7637b6a.png)
![image](https://user-images.githubusercontent.com/52415337/155845933-4695ace9-5136-45b5-bc21-ddd6a51864b0.png)

**Comment by maxb** [comment]
This bit me too recently.

It seems that you have to either allow the database secret engine to cleanly delete everything it created first, or you have to use the `sys/leases/revoke-force/...` endpoint to clean up.

If you look long enough, relevant information can be found in the docs, but it's quite easy to miss if you don't luck into the right search term, which is apparently "irrevocable leases".

Personally, I think Vault could do more to lead an admin encountering this issue for the first time in the right direction.

**Comment by weitzjdevk** [comment]
Thank you for your hints.

So `terraform init, terraform apply, terraform destroy` does not cut it any more. Good to know.

**Comment by weitzjdevk** [comment]
This is how you would revoke from Google Go:


```go
const leasePath = "postgres-database"
revoke, revokeErr := client.Logical().Write(path.Join("sys/leases/revoke-prefix/", leasePath), map[string]interface{}{
    // synchronous API-call, delete immediately and wait.
    "sync": true,
})
require.NoError(t, revokeErr)
require.Nil(t, revoke)
```

**Comment by calvn** [comment]
@weitzjdevk thanks for the report! We're aware of this issue and are tracking this internally. We will be working on coming up with a way to address this in the near future.

**Comment by weitzj** [comment]
@calvn Do you know the minimum capabilities one needs to revoke a lease using a glob path

sys/leases/revoke-prefix/*

read,update did not work 
Neither sudo

**Comment by maxb** [comment]
You need both update and sudo on the path.

Additionally, because of an obscure detail of how Vault processes trailing slashes, if your policy is:

```
path "sys/leases/revoke-prefix/*" {
  capabilities = ["update", "sudo"]
}
```

Then it will not match a write to `sys/leases/revoke-prefix/` itself - only `sys/leases/revoke-prefix/something`.

(Because Vault strips trailing slashes from non-list paths before processing.)
