### ISSUE TITLE
can't run valut in window 

### ISSUE THREAD

**Issue by ftyszyx** [hashicorp/vault#143]
when i build the valut success,then i run it use:"vault server -dev  " in the win7 system,it show that:

###### sh: C:srcgithub.combinvault.exe: command not found

can anyone tell me the reason?

**Comment by sethvargo** [comment]
Hi @ftyszyx 

Thank you for opening an issue. This looks suspiciously the same as https://github.com/hashicorp/vault/issues/95, and we already have a lot of history and conversation in that issue. Could you please track that issue instead? Thanks!
