### ISSUE TITLE
Possible issue when renewing leases

### ISSUE THREAD

**Issue by jorgemarey** [hashicorp/vault#1433]
Hi!

I was playing a bit with Vault (5.2) and Consul (6.4) and I found something weird.
I mounted the consul backend, configured the access and created a role to get tokens. To test token renewal I changed the default ttl lease to 30 seconds.

```bash
vault mount consul
vault write consul/config/access \
  address=myip:port \
  token=mytoken
echo 'key "docker/" { policy = "write" }' | base64 | vault write consul/roles/docker policy=- token_type=client
vault mount-tune -default-lease-ttl=30s consul
```
If I request a token, everything works fine:

```bash
vault read -format=json consul/creds/docker 
{
	"lease_id": "consul/creds/docker/2b3e5140-c1f3-4052-9a20-a7ec8931bf1e",
	"lease_duration": 30,
	"renewable": true,
	"data": {
		"token": "614c0705-4747-ffdf-70fb-7d224e36a18a"
	},
	"warnings": null
}
```
And after 30 seconds the token is removed in vault and deleted from consul, so everything works fine.
But if I try to renew the token, the response is the next one:
```bash
vault read -format=json consul/creds/docker 
{
	"lease_id": "consul/creds/docker/106b532f-c605-c6f6-4287-6fcc752a725e",
	"lease_duration": 30,
	"renewable": true,
	"data": {
		"token": "2b424dfc-b23c-8825-df39-450d696ae4f7"
	},
	"warnings": null
}
vault renew -format=json consul/creds/docker/106b532f-c605-c6f6-4287-6fcc752a725e 10
{
	"lease_id": "consul/creds/docker/106b532f-c605-c6f6-4287-6fcc752a725e",
	"lease_duration": 10,
	"renewable": true,
	"data": null,
	"warnings": null
}
```
The *lease_duration* that is received is 10 (the same as I sent as increment). Shouldn't it be remaining + increment?
Another weird thing is that if I try to renew the token after that 10 seconds, Vault sais that: `lease not found or lease is not renewable`. I guess that I should receive this after 40 seconds, not 10.
Lastly, if I make the renew, the token its never removed from consul (at least not after those 10 or 40 seconds). I check after half an hour and the token is still in consul. I'm able to use it. 

I don't know if this is a specific problem for consul secret backend or affects all of them. 

Maybe part of the problem is [here](https://github.com/hashicorp/vault/blob/master/logical/framework/lease.go#L81). 

Maybe this is the expected behaviour and I'm doing something wrong...

**Comment by jefferai** [comment]
The increment is the increment from now, not from the end of the current lease, so when you specify 10 seconds the lease duration is adjusted to 10 seconds. This is so that if you want to decrease the duration of a lease it's simple to reason about rather than having to start dealing with negative increments.

When you say:

> Lastly, if I make the renew, the token its never removed from consul 

Do you mean when you are seeing Vault say that the lease is not found/new renewable that the token is still in Consul?

What version of Vault are you using, and can you attach logs?

**Comment by jorgemarey** [comment]
Ok, I get why the use of increment as time from now.

Yes, exactly. I can't renew the token, but it's still in Consul. Steps to reproduce:

```bash
#Launch consul
consul agent -data-dir=/tmp/consul -log-level=debug -advertise=127.0.0.1 -server -bootstrap-expect=1 -config-file=config.json

#Launch vault (configured with consul as backend)
vault server -config=v.hcl -log-level=debug

#Initialize and unseal vault
vault init
vault unseal ....

#Configure consul secret backend
vault mount consul
vault mount-tune -default-lease-ttl=30s consul
vault write consul/config/access address=127.0.0.1:8500 token=<consul master token>
echo 'key "test/" { policy = "write" }' | base64 | vault write consul/roles/test policy=- token_type=client

#Get one token
vault read -format=json consul/creds/test
{
	"lease_id": "consul/creds/test/0167fa9b-8294-952a-f1d6-4dd8e988cbbf",
	"lease_duration": 30,
	"renewable": true,
	"data": {
		"token": "a1ae6db1-8b26-ff65-37fa-5a541d3e9a14"
	},
	"warnings": null
}

#Check token is there
curl http://127.0.0.1:8500/v1/acl/list?token=<master token> | python -m json.tool
[
....
    {
        "CreateIndex": 75,
        "ID": "a1ae6db1-8b26-ff65-37fa-5a541d3e9a14",
        "ModifyIndex": 75,
        "Name": "Vault root 1463992368",
        "Rules": "key \"test/\" { policy = \"write\" }\n",
        "Type": "client"
    },
....
]

#Renew token (it doesn't matter if is less o more time than remaining)
vault renew -format=json consul/creds/test/0167fa9b-8294-952a-f1d6-4dd8e988cbbf 60
{
	"lease_id": "consul/creds/test/0167fa9b-8294-952a-f1d6-4dd8e988cbbf",
	"lease_duration": 60,
	"renewable": true,
	"data": null,
	"warnings": null
}

#After a few minutes the token is still there, seems like it will never be deleted (it should be removed after 60 seconds)
curl http://127.0.0.1:8500/v1/acl/list?token=<master token> | python -m json.tool
[
...
    {
        "CreateIndex": 75,
        "ID": "a1ae6db1-8b26-ff65-37fa-5a541d3e9a14",
        "ModifyIndex": 75,
        "Name": "Vault root 1463992368",
        "Rules": "key \"test/\" { policy = \"write\" }\n",
        "Type": "client"
    },
...
]
```

If I create a token and I don't renew the lease it gets removed from consul correctly.

In the logs I don't see anything unusual.

After those 60 seconds vault sais:

```bash
2016/05/23 10:34:07 [INFO] expire: revoked 'consul/creds/test/0167fa9b-8294-952a-f1d6-4dd8e988cbbf'
```

And consul:

```bash
2016/05/23 10:34:07 [DEBUG] http: Request PUT /v1/acl/destroy/?token=<hidden> (19.307µs) from=127.0.0.1:59917
2016/05/23 10:34:07 [DEBUG] http: Request DELETE /v1/kv/vault/sys/expire/id/consul/creds/test/0167fa9b-8294-952a-f1d6-4dd8e988cbbf?token=<hidden> (4.033034ms) from=127.0.0.1:59906
2016/05/23 10:34:07 [DEBUG] http: Request DELETE /v1/kv/vault/sys/expire/token/57907b5efb2f3b848094bb1acfb6f01713e690d1/56496b9abb24fe23708ce42d702bf77c227ec9ba?token=<hidden> (3.883769ms) from=127.0.0.1:59906
2016/05/23 10:34:07 [DEBUG] http: Request PUT /v1/session/renew/accad749-8f5a-f1e9-f025-d3cb927d8406?token=<hidden> (299.598µs) from=127.0.0.1:59906
```

I hope that helps.

**Comment by jefferai** [comment]
Thanks for the detail! We'll look into it.
