### ISSUE TITLE
UI - Patch Secret

### ISSUE THREAD

**Issue by AdrianFarmadin** [hashicorp/vault#14337]
**Is your feature request related to a problem? Please describe.**
Some users don't have to have a read permission on secrets, but still are able patch a secret.
Such user is forced to use Vault CLI or API, because patch is not implemented in UI.

**Describe the solution you'd like**
UI supports "patch secret" in an user-friendly way.

**Describe alternatives you've considered**
Vault CLI or API.

**Explain any additional use-cases**
A developer should be able to rotate a secret, but not be able to use the secret for local development//testing.

**Comment by RemcoBuddelmeijer** [comment]
I would argue that this is already implemented in the UI without a separate "patch" or "update" button.

Whenever you patch a secret it will not remove old key-value pairs from your secret. It will only either update existing ones or add a new key-value pair.
Whenever you update a secret it will completely overwrite the entire secret's content, this includes deleting old entries if not specified.
Both of the operations create a new version.

Now looking at the UI. If you press "create new version" it will pre-fill the already existing key-value pairs. You are now allowed to change these values or delete them. This is both related to a patch and update functionality.
I hope this helps!

**Comment by hsimon-hashicorp** [comment]
Thank you, @RemcoBuddelmeijer! That's very helpful. @AdrianFarmadin please let me know if this answers your use case, or if you can provide more information about what you're looking for. Thanks!

**Comment by AdrianFarmadin** [comment]
Let me better describe the use-case.

A user A creates a secret in "kv/show/some/path" with following values:

- key1 = value1
- key2 = value2
- key3 = value3
![secret-values](https://user-images.githubusercontent.com/14540375/157649686-1a65f487-5925-4daa-879d-58194d43e7d9.png)

Another user B with write-only policy granted needs to update the key1

Wrtie-only policy:
```
path "kv/data/*" {
  capabilities = [ "create", "update", "patch", "delete", "list" ]
}

path "kv/metadata/*" {
  capabilities = [ "read", "list" ]
}
```
![write-only-policy](https://user-images.githubusercontent.com/14540375/157650345-3880e2a2-144c-4ba5-a0bc-a8cddaf0ddc4.png)

The user B can open the secret path and edit the secret, but can't view any values:
![write-only-view](https://user-images.githubusercontent.com/14540375/157650461-34a8aa16-d82b-4c3c-b031-ca4f549c2cb8.png)

The user B clicks on "Create new version +" and defines only key1 with new value. The new secret version will contain only the single defined key.
![edit-secret-write-only](https://user-images.githubusercontent.com/14540375/157651754-38f6b601-f3d7-43dd-9b4f-f83094fd720a.png)
 
New version
![new-secret-version](https://user-images.githubusercontent.com/14540375/157651811-e663b872-c604-401b-af13-1ebf5783879d.png)

Patch Secret functionality allows an user to update a single key without overwriting the other keys.
https://www.vaultproject.io/api-docs/secret/kv/kv-v2#patch-secret

It would be great if an user had a possibility to choose if he wants to overwrite the secret or update defined keys.

**Comment by hsimon-hashicorp** [comment]
Hi @AdrianFarmadin - can you confirm your Vault version? I believe we fixed this in a relatively recent release, but I'd like to make sure. Thanks!

**Comment by AdrianFarmadin** [comment]
Version: Vault v1.9.4
Version Sha: fcbe948b2542a13ee8036ad07dd8ebf8554f56cb

Image: vault:latest vault@sha256:6c551f51032fdefc676576c94eb810741214dcaf9670ac0700a4ca71753b4ff5

**Comment by AdrianFarmadin** [comment]
@hsimon-hashicorp any update?

Should Vault v1.9.4 contain a fix?

**Comment by evan361425** [comment]
Same here in Vault v1.10.0 (7738ec5d0d6f5bf94a809ee0f6ff0142cfa525a6)

**Comment by tcoenraad** [comment]
[This](https://github.com/hashicorp/vault/issues/14337#issuecomment-1063959279) is still the behavior in 1.14.0.

**Comment by TrueBurn** [comment]
Can `/ui/vault/tools/api-explorer` not be updated to also include a PATCH endoint for `/kv/data/{path}` ?

**Comment by heatherezell** [comment]
This has been implemented in Vault Enterprise as of 1.18. We will continue to evaluate possible inclusion into CE, depending on customer needs and product leadership decisions. Please feel free to comment here if you are a CE user and wish for this to be included in the future. Thanks!

**Comment by noppakorn** [comment]
@heatherezell is it possible to include this features in CE as well?

**Comment by forestoden** [comment]
we would also like this feature in CE

**Comment by jakov-motsenov-pawatech** [comment]
We would like to have this functionality in CE as well
