### ISSUE TITLE
No failover with DynamoDB as HA backend on v0.5.2

### ISSUE THREAD

**Issue by sinneduy** [hashicorp/vault#1434]
initial configuration in 3 nodes:

```
backend "dynamodb" {
  advertise_addr = "<host*>"
}

ha_backend "dynamodb" {
  advertise_addr = "<host*>"
}

listener "tcp" {
 address = "0.0.0.0:443"
 tls_cert_file = "<redacted>.crt"
 tls_key_file = "<redacted>.key"
}

disable_mlock = true
default_lease_ttl = "24h"
max_lease_ttl = "720h"
```

Initial statuses:
```
# VAULT_ADDR="host1" vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: active
	Leader: host1
# VAULT_ADDR="host2" vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: standby
	Leader: host1
# VAULT_ADDR="host3" vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: standby
	Leader: host1
```

After host1 comes back:
```
VAULT_ADDR="host1" vault status
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: sealed
# VAULT_ADDR="host2" vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: standby
	Leader: host1
# VAULT_ADDR="host3" vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: standby
	Leader: host1
```

After unsealing host1:

```
# VAULT_ADDR="host1" vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: standby
	Leader: host1
# VAULT_ADDR="host2" vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: standby
	Leader: host1
# VAULT_ADDR="host3" vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: standby
	Leader: host1
```

Am I missing something?  How can I debug this further?

**Comment by sinneduy** [comment]
https://github.com/hashicorp/vault/pull/878

**Comment by jefferai** [comment]
Take a look at the description of the recovery_mode option in #878...probably you need to use that. Dynamo is not good at recovering on its own when Vault does not shut down properly. Btw, if the backend and ha_backend are the same, you only need backend!

**Comment by sinneduy** [comment]
sorry, so just to clarify, the only acceptable "failure" that will cause a failover is if you seal?

**Comment by sinneduy** [comment]
Also, could you speak to how well the other HA storage backends recover on their own?  Is this an issue at all in Consul?

**Comment by jefferai** [comment]
That is a [documented](https://www.vaultproject.io/docs/config/index.html#recovery_mode) limitation of the Dynamo backend. If that trade-off is not acceptable to you, you should not use the Dynamo backend for HA, or have mechanisms in place to quickly detect and fix this condition.

The other HA backends do not have this drawback. I can't comment on etcd or zookeeper as I have no experience with them in the context of Vault, but any time a Consul cluster is healthy, Vault active node selection should work properly.

**Comment by sinneduy** [comment]
Might I suggest that you not really call this high availability?  I realize that recovery mode is documented, but it isn't clear to me from reading what you have linked how prevalent those circumstances might be, or even what `shut down properly` means.  I for one would would have appreciated some sort of note indicating that dynamodb is really more of a "high availability in limited circumstances" situation. 

That being said, documentation is hard and its just a suggestion.  Perhaps this thread will be sufficient for the next person who comes along.

Its good to hear that this isn't an issue with Consul - I will look into migrating there.

**Comment by ShahidH** [comment]
@sinneduy I was about to try Dynamo until I read this issue. Are you using Consul for HA now?

**Comment by sinneduy** [comment]
Yes, however, keep in mind this was from vault `0.6.*`, so it may have had some improvements overall.  That being said, I would say that consul is the only backend that is officially supported, and I would try to stick to it as much as possible

**Comment by xueshanf** [comment]
@efferai: Is the `recovery_mode` no longer needed? This [dynamodb storage](https://www.vaultproject.io/docs/configuration/storage/dynamodb.html) documentation doesn't mention it, and the implementation now supports  "session lifetimes on its locks".  We are trying to decide which ha_storage backend to go with, and using dynamodb would  mean no need to manage an etcd/consul cluster just for vault. Thanks!

**Comment by moofish32** [comment]
@xueshanf  - appears to be solved by https://github.com/hashicorp/vault/pull/2141 (I found this by checking the changelog).
