### ISSUE TITLE
Add method for simple intermediate CA pki creation

### ISSUE THREAD

**Issue by F21** [hashicorp/vault#1438]
To stand up an intermediate CA using the PKI backend, the current process is to:
1. Generate the CSR: `vault write intermediatepki/intermediate/generate/exported common_name=vault.example.com`
2. Save the CSR to a location on your PC.
3. Sign it with the root: `vault write rootpki/root/sign-intermediate csr=@csr.pem use_csr_values=true ttl=4380h`
4. Submit the signed certificate and private key to vault: `vault write/pki/intermediate/set-signed certificate=@signed.pem`

It would be nice if there's a way to simplify this if we are using Vault to run the root and intermediate CAs. For creating an intermediate CA, something like this would be very nice:

1. Set the intermediate CA to use the root: `vault write intermediatepki/config/root rootpath=/rootpki`
2. Create the intermediate CA certificate: `vault write intermediatepki/intermediate/generate common_name=intermediate.example.com`

**Comment by jefferai** [comment]
Backends in vault cannot talk to each other, so there is no way to have the intermediate mount talk to the root mount. Sorry!
