### ISSUE TITLE
Customizing num_uses and ttl per approle secret id

### ISSUE THREAD

**Issue by kent007** [hashicorp/vault#14390]
**Is your feature request related to a problem? Please describe.**
When I generate a new secret ID for an approle, I would like to customize the TTL and/or num_uses for that secret ID, similarly to how I can customize the [cidr_list](https://www.vaultproject.io/api-docs/auth/approle#cidr_list) and [token_bound_cidrs](https://www.vaultproject.io/api-docs/auth/approle#token_bound_cidrs-1). 

**Describe the solution you'd like**
Additional API parameters for the [approle secret ID creation](https://www.vaultproject.io/api-docs/auth/approle#generate-new-secret-id) allowing custom values to be set for `num_uses` and `ttl`.

**Describe alternatives you've considered**
Since `num_uses` and `ttl` are currently tied to the role configuration, any use case for an approle that requires a different value for either parameter than the default means I have to create an entirely new approle with identical policies but different configuration. This is possible, but tedious.

**Explain any additional use-cases**
In particular, this can be useful for the recommended [approle use pattern that involves wrapping](https://learn.hashicorp.com/tutorials/vault/pattern-approle?in=vault/recommended-patterns). For example, it would be very convenient to specify the `num_uses` for a new secret ID being passed to automation, even if the approle configuration did not have `num_uses` set.

**Comment by RemcoBuddelmeijer** [comment]
This seems like an interesting case. Did you have anything written for this yourself?

**Comment by kent007** [comment]
> This seems like an interesting case. Did you have anything written for this yourself?

I'm not sure I understand. I haven't opened the vault code and evaluated the feasibility of a PR for this feature, although I'd be happy to.

In our system, for some approles we maintain one or more secret-ids that are long lived (ttl 90+ days) and generate others that are supposed to be short lived (1+ hours) to hand off to various automation. We have a system set up for tagging the short-lived approles with custom metadata and a reaper program that runs periodically to purge them...since we can't set the TTL in vault all the "short-lived" secret-ids ttls are only being enforced by the reaper, which means Vault would still consider them valid.

**Comment by RemcoBuddelmeijer** [comment]
> > This seems like an interesting case. Did you have anything written for this yourself?
> 
> I'm not sure I understand. I haven't opened the vault code and evaluated the feasibility of a PR for this feature, although I'd be happy to.

Sorry for the confusion! When saying “written anything for this” I was referring to having worked on the code yourself. I have had a look at your use case and I would say it’s pretty feasible.
If you want to go ahead and make a PR yourself go ahead, otherwise I am always happy to do so! 😄

**Comment by kent007** [comment]
> If you want to make a PR yourself please by all means go ahead, otherwise I am always happy to do so! 😄

Much obliged! Realistically speaking I wouldn't be able to work on this feature for a few weeks, although I'll be happy to test if it becomes available soon.  Our enterprise release is back by a few versions anyway, we're still on 1.6.3 and I'm not sure what our upgrade schedule is

**Comment by RemcoBuddelmeijer** [comment]
> Much obliged! Realistically speaking I wouldn't be able to work on this feature for a few weeks, although I'll be happy to test if it becomes available soon. 
Since that's the case. I'll go ahead and put in the work and refer this issue for testing and tracing purposes! 😄 

> Our enterprise release is back by a few versions anyway, we're still on 1.6.3 and I'm not sure what our upgrade schedule is
Perhaps attempting to put this as something that can be back-ported would be beneficial?

**Comment by RemcoBuddelmeijer** [comment]
@kent007 I have gone ahead and added the fields. Feel free to test them 😃

**Comment by kent007** [comment]
@RemcoBuddelmeijer I read through your changes, they look great and should hopefully do exactly what we need!

Is there a test binary published anywhere I can download to experiment with? I'm unfamiliar with circle-ci -- if it'll be faster to download your branch and build it locally, I can do that as well

**Comment by RemcoBuddelmeijer** [comment]
@kent007 I didn't build any test binary, best would to build it yourself using `make dev`. This would yield the same results.

**Comment by kent007** [comment]
I kicked the tires on a test binary for a little bit, seems to be working great. Very excited to see this feature added.

As far as backporting, our enterprise support team seems to be open to upgrading to a significantly newer version. If it's not too much trouble to backport I think it would be valuable, but it's not a deal breaker.

I'd also like to recommend that the docs regarding the [recommended approle pattern for CI environments](https://learn.hashicorp.com/tutorials/vault/pattern-approle?in=vault/recommended-patterns#implementation-specifics) be updated with a few details: 
* that `secret_id_ttl` and `num_uses` can be set individually for the wrapped secret-ids
* if operating in an environment that generates _lots_ of secret-ids, these are stored persistently inside vault and might need to be cleaned out periodically. As far as I can tell, there are two conditions where an expired secret-id is automatically purged:
  * when the last of `num_uses` logins has been executed
  * attempting to use the secret-id after the ttl has run out. There's no good reason for well tuned automation to attempt a second login after the ttl, so these secret-ids will likely build up over time

**Comment by RemcoBuddelmeijer** [comment]
> I kicked the tires on a test binary for a little bit, seems to be working great. Very excited to see this feature added.

Great to hear!

> As far as backporting, our enterprise support team seems to be open to upgrading to a significantly newer version. If it's not too much trouble to backport I think it would be valuable, but it's not a deal breaker.

I will discuss this in the PR and/or make another PR out of it to backport it. Shouldn't be too big of an issue since it doesn't contain any breaking API changes.

> I'd also like to recommend that the docs regarding the [recommended approle pattern for CI environments](https://learn.hashicorp.com/tutorials/vault/pattern-approle?in=vault/recommended-patterns#implementation-specifics) be updated with a few details:

After the PR has been merged, I will make an attempt to get all the other Learns, Best Practices, etc. to be updated. For now the API docs have been updated and will include the new changes.

**Comment by kent007** [comment]
Stumbled into another question related to this feature today...

Once we have the ability to set `TTL` and `num_uses` for individual secret-ids, we would like to be able to require a TTL and/or num_uses via a policy. Will the functionality already present for [setting required and allowed parameters](https://www.vaultproject.io/docs/concepts/policies#parameter-constraints) work for this? For example, something like would enforce a TTL of 1 hour and num_uses of 1:

```
path "auth/approle/role/<my approle here>/secret-id" {
  capabilities = ["create", "update"]
  allowed_parameters = {
    "ttl" = ["1h"]
    "num_uses" = ["1"]
  }
}
```

**Comment by RemcoBuddelmeijer** [comment]
Hey @kent007 

My apologies for the late answer.
Yes this works out of the box! Just to be sure I have gone ahead and tested it for you. For both cases where I presented other parameters I was welcomed with a "permission denied".
