### ISSUE TITLE
vault auth from remote api client

### ISSUE THREAD

**Issue by aliatsis** [hashicorp/vault#1439]
I'm a little confused as to the best way to deploy, init, and auth into vault.
I would like to read and write secrets from an AWS Lambda function.
Since these functions are transient, I want to deploy an Elastic Beanstalk application with an internal load balancer exclusively for Vault and communicate with the Vault HTTP API from my Lambda functions.

Is this even a reasonable setup for Vault?
If so, what is the best way for the remote Lambda functions to auth into the Vault HTTP API since the unseal keys are created and deployed on separate machines?

I'm obviously new to Vault so any experienced advice would be greatly appreciated.

**Comment by jefferai** [comment]
I unfortunately have zero Lsmbda experience and really cannot help. Please ask on the mailing list (https://groups.google.com/group/vault-tool) as there are many more eyes there and many more people with extensive AWS experience. Thanks!
