### ISSUE TITLE
feature request - work with aws KMS + DynamicDB

### ISSUE THREAD

**Issue by SydOps** [hashicorp/vault#1440]
I recently work on credstash (https://github.com/fugue/credstash), and like the Simplicity.

Credstash uses aws dynamicDB, plus KMS (Key Management Service) to manage the key/values. With it, I needn't setup a separate EC2 instance for Vault service (especially in production, we need think about clustering for this service)

 Compare what credstash can do, Vault does more. So I recommend if you can add the feature from credstash to Vault directly?

And same features for other clould platforms as well?

**Comment by jefferai** [comment]
What exactly are you asking for here? There is already a DynamoDB storage backend for Vault, although it has unfavorable HA behavior. I'm not sure what KMS would be used for.

**Comment by SydOps** [comment]
@jefferai 

Where can I find the document about the dynamoDB storage backend for Vault?

Go through `secret backends`, aws is in the list, but didn't tell me what used in backend, and dynamoDB is not in the list.

go through `auth backends`, AWS Key Management Service (https://aws.amazon.com/kms) is not in list. 

So the idea here is, after create `KMS`, the permission can be assigned to IAM users or roles. Then the users or the instance installed with that role can get password directly. 

KMS as a auth key in this idea. 

Hope I explain clearly.

**Comment by vishalnayak** [comment]
Hi @SydOps,

Vault uses "backend" to mean different things based on different contexts.

> Where can I find the document about the dynamoDB storage backend for Vault?

1) There are storage backends in which anything and everything in Vault is -- encrypted -- and stored.
DynamoDB is one of the storage backends and is a community-supported backend.
Options to configure it or many others are documented here: https://www.vaultproject.io/docs/config/index.html

> Go through secret backends, aws is in the list, but didn't tell me what used in backend, and dynamoDB is not in the list.

2) There are secret backends which can be used to generate dynamic secrets.
https://www.vaultproject.io/docs/secrets/index.html

The AWS secret backend which you saw, is used to create AWS credentials dynamically.

> go through auth backends, AWS Key Management Service (https://aws.amazon.com/kms) is not in list.

3) There are auth backends which are used to authenticate and authorize Vault clients.
https://www.vaultproject.io/docs/auth/index.html

Vault currently does not support AWS KMS as an authentication mechanism.
There is a new AWS-EC2 auth method (already in master), which will be released in the next version of Vault.
https://github.com/hashicorp/vault/blob/116e2cf0242dd26dacf3c86e6bc9c9eb2ff2e371/website/source/docs/auth/aws.html.md

And for completeness, 4) There are audit backends to log all the requests and responses. https://www.vaultproject.io/docs/audit/index.html

Hope this helps!

Regards,
Vishal

**Comment by SydOps** [comment]
@vishalnayak 

Thanks for the explanation, I can close it now.

**Comment by SydOps** [comment]
@vishalnayak @jefferai 

Any chances to have search functions on value docs pages?

https://www.vaultproject.io/docs/index.html

With that, I can simply search the key word `DynamoDB` and got the related documents. 

Now I have to go back to github and search in github for these informations.

**Comment by jefferai** [comment]
I believe it was discussed earlier and we didn't find a search plugin that worked better than Google. After all a Google search for 'vault dynamodb' pulls up the relevant page as the first hit.
