### ISSUE TITLE
Other languages support

### ISSUE THREAD

**Issue by sergiomarotco** [hashicorp/vault#14417]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I want interface in Russian language and i would like help u to translate interface and other

**Describe alternatives you've considered**
Cry

**Explain any additional use-cases**
Translation of the web interface would be enough for me

**Additional context**
give me text or links to files and i will translate, i can probably make pull requests

**Comment by hsimon-hashicorp** [comment]
Hi @sergiomarotco! This is something I will definitely bring up to our leadership. As our company grows, and our userbase expands globally, I personally believe this will become increasingly important. I can't make any promises about languages or timelines, but please know this is something I am very interested in, myself. :) Right now, please "watch this space", in future releases and updates. Thanks for being an engaged user!

**Comment by sergiomarotco** [comment]
@hsimon-hashicorp Have you got some news?
