### ISSUE TITLE
Prepare Kubernetes Auth documentation for KEP-2799

### ISSUE THREAD

**Issue by RemcoBuddelmeijer** [hashicorp/vault#14410]
**Is your feature request related to a problem? Please describe.**
The Kubernetes Auth documentation is currently not up-to-date with an upcoming breaking change for Kubernetes. This will cause Vault clusters to break under certain circumstances if not guided correctly.

**Describe the solution you'd like**
Update the Vault documentation to include a section on the change and how to fix it. Can be included as a sub section. 
A warning/note should be posted on when and where to watch.

**Describe alternatives you've considered**
None

**Additional context**
I have some docs written myself that I would like to put forward.

**Comment by hsimon-hashicorp** [comment]
Tagging @taoism4504 for visibility.

**Comment by kevinlmadison** [comment]
Hey @RemcoBuddelmeijer are your docs available somewhere, I have a feeling I might be running into these breaking changes.

**Comment by RemcoBuddelmeijer** [comment]
Hey @kevinlmadison, I am currently still finishing a useable version of my documentation. I will let you know through this thread once it's available. 
However, before doing so. Is your issue related to an already existing Kubernetes version or are you using a bleeding edge version of Kubernetes?

**Comment by kevinlmadison** [comment]
I'm on k8s 1.22.6, using rke2

**Comment by RemcoBuddelmeijer** [comment]
KEP-2799 has been moved to the [v1.25](https://github.com/kubernetes/enhancements/milestone/25) milestone. Since the enhancement proposal has been approved, the doc can be prepared for.

**Comment by RemcoBuddelmeijer** [comment]
> It is continuing work in 1.25, but the first portion of KEP-2799 was implemented and released in 1.24

Thank you for the update! I just noted that the LegacyServiceAccountTokenNoAutoGeneration will remain in beta throughout 1.25. Is it already known in what version this will move to stable? Probably the two other features will reach stable a release after?

**Comment by liggitt** [comment]
> I just saw that the LegacyServiceAccountTokenNoAutoGeneration will remain in beta throughout 1.25.

Correct, but scraping auto-generated token secrets is not correct in any version, and the supported alternatives are already GA:
* the `TokenRequest` API is GA since v1.20
* manually creating a secret-based token is documented and supported in all versions since v1.0

> Is it already known in what version this will move to stable? Probably the two other features will reach stable a release after?

The schedule for reaching GA is not known yet

**Comment by RemcoBuddelmeijer** [comment]
> Correct, but scraping auto-generated token secrets is not correct in any version, and the supported alternatives are already GA:

Actually looks like the team has gone ahead and updated the setup where this was still being done. (The issue was created when this information was not yet shared.) https://learn.hashicorp.com/tutorials/vault/kubernetes-external-vault?in=vault/kubernetes#install-the-vault-helm-chart (Step 6)
Because of this the issue, which was to inform, can be closed. Thank you all team! 😄
