### ISSUE TITLE
Why app-id login api need token besides appid & userid?

### ISSUE THREAD

**Issue by ZeeShen** [hashicorp/vault#1442]
My reference https://www.vaultproject.io/docs/auth/app-id.html
> It works by requiring two hard-to-guess unique pieces of information: a unique app ID, and a unique user ID.

I thought `app_id` and `user_id` were the only 2 elements required. But I tried:

```
# vault server machine
vault write auth/app-id/map/app-id/xxxAppIdxxx display_name=xxx,value=POLICY_NAME
vault write auth/app-id/map/user-id/xxxUserIdxxx value=xxxAppIdxxx cidr_block=10.0.0.0/16

# client machine (no `~/.vault-token`, no `VAULT_TOKEN` enviroment variable)
vault write auth/app-id/login/xxxAppIdxxx user_id=xxxUserIdxxx # to get token from output
```
Output
```
Error writing data to auth/app-id/map/login/xxxx: Error making API request.

URL: PUT http://localhost:8087/v1/auth/app-id/map/login/xxxx
Code: 400. Errors:
```
Not sure my operation is right. 
What I want is authenticating a new instance who has a configured user-id and access to app-id. 
What should I do? Give a token to new instance to access `login` path ? A little strange.

Hope for your help.

**Comment by jefferai** [comment]
Hi @ZeeShen,

You cut off the actual error in the output...what is the error you get?

**Comment by ZeeShen** [comment]
Hi @jefferai 
Sorry. The complete output is
```
Error writing data to auth/app-id/map/login/xxx: Error making API request.

URL: PUT http://localhost:8087/v1/auth/app-id/map/login/57b21528-20cb-11e6-b848-02ae1e45ae78
Code: 400. Errors:

* missing client token
```

**Comment by ZeeShen** [comment]
Sorry. Found my mistake myself. Wrong api path. `auth/app-id/map/`

**Comment by vishalnayak** [comment]
Hi ZeeShen,

The login path to fetch the token is an unauthenticated path and there is
no need for a "~/.vault-token" or a VAULT_TOKEN env var.
As you expected, app_id and user_id are the only 2 pieces of information
which is required to get a Vault token.

The error message in your post is showing this path
"auth/app-id/map/login/xxxx".
The term "map" in the login path is not required and could be the culprit.

Hope this helps!

Regards,
Vishal



On Mon, May 23, 2016 at 7:55 AM, ZeeShen <notifications@github.com> wrote:

> My reference https://www.vaultproject.io/docs/auth/app-id.html
>
> It works by requiring two hard-to-guess unique pieces of information: a
> unique app ID, and a unique user ID.
>
> I thought app_id and user_id were the only 2 elements required. But I
> tried:
>
> # vault server machine
> vault write auth/app-id/map/app-id/xxxAppIdxxx display_name=xxx,value=POLICY_NAME
> vault write auth/app-id/map/user-id/xxxUserIdxxx value=xxxAppIdxxx cidr_block=10.0.0.0/16
>
> # client machine (no `~/.vault-token`, no `VAULT_TOKEN` enviroment variable)
> vault write auth/app-id/login/xxxAppIdxxx user_id=xxxUserIdxxx # to get token from output
>
> Output
>
> Error writing data to auth/app-id/map/login/xxxx: Error making API request.
>
> URL: PUT http://localhost:8087/v1/auth/app-id/map/login/xxxx
> Code: 400. Errors:
>
> Not sure my operation is right.
> What I want is authenticating a new instance who has a configured user-id
> and access to app-id.
> What should I do? Give a token to new instance to access login path ? A
> little strange.
>
> Hope for your help.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/vault/issues/1442>
>



-- 
vn
