### ISSUE TITLE
Go API Token RenewSelf fails - incorrect HTTP method

### ISSUE THREAD

**Issue by jaredpetersen** [hashicorp/vault#14421]
**Describe the bug**
Attempts to call the [RenewSelf](https://pkg.go.dev/github.com/hashicorp/vault/api#TokenAuth.RenewSelf) function on a token fails, likely because of an incorrect HTTP method.

If you look at the [HTTP API documentation](https://www.vaultproject.io/api/auth/token#renew-a-token-self), you can see that the request is `POST /auth/token/renew-self`.

However, the Go API calls `PUT /auth/token/renew-self`:

https://github.com/hashicorp/vault/blob/api/v1.4.1/api/auth_token.go#L161

**To Reproduce**
Code reproducing the behavior:

```go
// Client previously created and authenticated

secret, err := client.Auth().Token().RenewSelf(0)

// Error text is `Error making API request.\n\nURL: PUT http://vault.vault:8200/v1/auth/token/renew-self\nCode: 403. Errors:\n\n* permission denied`
```

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.9.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.9.2 (f4c6d873e2767c0d6853b5d9ffc77b0d297bfbdf)
* Server Operating System/Architecture: Kubernetes running in minikube, HA with Raft

Vault server configuration file(s):

```hcl
# Not relevant
```

**Additional context**
None

**Comment by ncabatoff** [comment]
Hi @jaredpetersen,

We don't distinguish between PUT and POST in the backend.  I suspect your 403 is happening for other reasons, most likely policies.

**Comment by jaredpetersen** [comment]
@ncabatoff Ah, interesting. I thought I was on to something for sure when I saw the discrepancy. I will close this out then and investigate the 403 separately. Thank you!
