### ISSUE TITLE
Allow LDAP authentication by a group

### ISSUE THREAD

**Issue by TerryHowe** [hashicorp/vault#1444]
I don't know much about AD, but I have a group that has a password and I cannot authenticate with that group.  It gets kicked out right here:

https://github.com/hashicorp/vault/blob/master/builtin/credential/ldap/backend.go#L183

There must be some other way to get that DN so I can have a group authenticate.

**Comment by shomron** [comment]
@TerryHowe I don't understand the use case for that. Users should authenticate as themselves, and use groups to manage policy mappings. For applications / services we create service users or use the token / appid backends. What does authenticating as a group even mean?

**Comment by TerryHowe** [comment]
Well, applicationX is a group that has secrets.  All the developers are in the applicationX group and applicationX has its own password.

**Comment by jefferai** [comment]
I don't actually see why it shouldn't work if you put the group DN as the user DN. But I really, really don't know  :-D

**Comment by shomron** [comment]
I still don't see it.  Those developers should be authenticating as themselves and access to the secrets would be based on their membership to the aaplicationX group.

**Comment by TerryHowe** [comment]
Well, when Jenkins or any other application is accessing vault, it needs creds.  No one wants their creds in an application because they could be used to access direct deposit, etc.  Ldap admin insists that each user is a real person, but you can have a group with a password.  That is just the situation I have to deal with.

**Comment by TerryHowe** [comment]
Somewhat related, I wrote a ansible module for vault.  If there was something out there, I couldn't find it https://pypi.python.org/pypi/ansible-modules-hashivault

**Comment by jcornell123** [comment]
You would need to create a service account user for the application that is in the AD group.  You authenticate with users that are members of groups as groups don't have credentials to authenticate with.  https://technet.microsoft.com/en-us/library/dd548356(v=ws.10).aspx

**Comment by jefferai** [comment]
I'm with @jcornell123 here. The normal way to handle services is with service accounts, in a different OU than users. I don't think it's a good idea to introduce support for this not well supported feature simply to work around one LDAP admin that is not following normal practices. Sorry...
