### ISSUE TITLE
Vault master key remains in process memory after vault is sealed

### ISSUE THREAD

**Issue by Vayu** [hashicorp/vault#1446]
I wrote a little script which looks for master key in the process memory https://github.com/Vayu/vault_recover. It seems like vault master key can be extracted even after the vault was sealed. Below is an example shell session on a vault running with file backend created for testing (tested on Linux, probably won't work on OS X):

```
% vault unseal
Key (will be hidden): 
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

% sudo vault_recover.py --keyring data/core/_keyring --pid `pgrep vault`                   
INFO:root:Trying pid 24795
INFO:root:Scanning pid 24795 range c81ffd8000-c820500000 [stack:24796];
INFO:root:Found 12 candidate pointers
INFO:root:Key 40555ee300bb7b1d2da2bc8b18390c4206f3890b1de455d964effbf35f5c2a14
INFO:root:Plaintext {"MasterKey":"QFVe4wC7ex0toryLGDkMQgbziQsd5FXZZO/7819cKhQ=","Keys":[{"Term":1,"Version":1,"Value":"l0mQe7OqpAvnhyNZoNiYzikZaAWtK90UzP67kyCjN4M=","InstallTime":"2016-05-24T10:50:02.839355393+02:00"}]}

% vault seal                                                                    
Vault is now sealed.

% sudo vault_recover.py --keyring data/core/_keyring --pid `pgrep vault`
INFO:root:Trying pid 24795
INFO:root:Scanning pid 24795 range c81ffd0000-c820600000 [stack:24796];
INFO:root:Found 6 candidate pointers
INFO:root:Key 40555ee300bb7b1d2da2bc8b18390c4206f3890b1de455d964effbf35f5c2a14
INFO:root:Plaintext {"MasterKey":"QFVe4wC7ex0toryLGDkMQgbziQsd5FXZZO/7819cKhQ=","Keys":[{"Term":1,"Version":1,"Value":"l0mQe7OqpAvnhyNZoNiYzikZaAWtK90UzP67kyCjN4M=","InstallTime":"2016-05-24T10:50:02.839355393+02:00"}]}
```

**Comment by beeyeas** [comment]
This looks like a potential threat, are you loading it from the proc?

**Comment by Vayu** [comment]
Yes, check /proc/[pid]/maps, then read from /proc/[pid]/mem everything which looks like a key and try to decrypt the keyring.

**Comment by sethvargo** [comment]
Hi @Vayu 

Thank you for opening an issue. In the future, please use [responsible disclosure](https://www.hashicorp.com/security.html) and do not open a public issue for these types of things.

If you examine [Vault's published threat model](https://www.vaultproject.io/docs/internals/security.html), we specifically call out that dumping the Vault memory process or providing unauthorized access to Vault server is beyond Vault's threat model.

**Comment by Vayu** [comment]
I'm aware that inspecting memory of unsealed vault should yield the keys and that is outside the scope of the threat model (although I think documentation does not stress this point strong enough).

The 'seal' command use-cases and guarantees are not documented clearly anywhere, so I'm not sure if finding keys after sealing vault is within the scope. If not, then the utility of the 'seal' command is pretty limited (to initiate HA fail-over?) and it might be even a bit misleading.

**Comment by vishalnayak** [comment]
Hi Valery,

When Vault is sealed, the master key is zeroed out (rather tried to be
zeroed out) from the memory and all operations will be stalled until Vault
is unsealed again, and the master key regenerated. Any remnants of master
key in memory after a seal operation, will not be known to Vault. This is a
side-effect of the Go's copying garbage collector which was introduced in
Go v1.5.

Regarding the documentation around memory analysis, almost always access to
memory is a "game over" scenario. The threat model does state that
inspecting memory may lead to compromise of confidentiality. Stressing too
much about it isn't going to help in any way.

The semantics of seal/unseal are explained at the following places:
https://www.vaultproject.io/docs/concepts/seal.html
https://www.vaultproject.io/docs/internals/architecture.html

If you need more clarifications about what seal/unseal guarantees, feel
free write back.

Hope this helps!

Regards,
Vishal

Regards,
Vishal


On Wed, May 25, 2016 at 12:49 PM, Valery Yundin <notifications@github.com>
wrote:

> I'm aware that inspecting memory of unsealed vault should yield the keys
> and that is outside the scope of the threat model (although I think
> documentation does not stress this point strong enough).
>
> The 'seal' command use-cases and guarantees are not documented clearly
> anywhere, so I'm not sure if finding keys after sealing vault is within the
> scope. If not, then the utility of the 'seal' command is pretty limited (to
> initiate HA fail-over?) and it might be even a bit misleading.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/vault/issues/1446#issuecomment-221633364>
>



-- 
vn

**Comment by Vayu** [comment]
One might argue that stressing it could make people quicker realize that single operator with SSH and sudo on the Vault host has effectively the same access privileges as 3+ people holding unseal key parts. And therefore design their procedures and policies with that knowledge in mind.

Correct me if I'm wrong, but I don't notice any attempt to zero-out the master key in `barrier_aes_gcm.go`.
```
// Seal is used to re-seal the barrier. This requires the barrier to
// be unsealed again to perform any further operations.
func (b *AESGCMBarrier) Seal() error {
	b.l.Lock()
	defer b.l.Unlock()

	// Remove the primary key, and seal the vault
	b.cache = make(map[uint32]cipher.AEAD)
	b.keyring = nil
	b.sealed = true
	return nil
}
```

Documentation which you linked implies that sealing the Vault is a good way to deal with intrusion. What kind of intrusion is assumed here? Maybe add a remote shutdown command?

>This way, if there is a detected intrusion, the Vault data can be locked quickly to try to minimize damages. It can't be accessed again without access to the master key shards.

**Comment by jefferai** [comment]
@Vayu The point of seal is that it's an API command. Someone wanting to stop Vault from being in service and is authorized to do so can cause Vault to stop serving requests. When remotely sealing in this fashion, you don't have access to the process memory anyways.

If you're on the Vault host, there isn't much reason to seal rather than to (gracefully) shut down the Vault process.

**Comment by jefferai** [comment]
> One might argue that stressing it could make people quicker realize that single operator with SSH and sudo on the Vault host has effectively the same access privileges as 3+ people holding unseal key parts. And therefore design their procedures and policies with that knowledge in mind.

I just wanted to add that `sudo` should be limited to specific commands, and if an operator does have (via `sudo`) access to dump Vault's memory, they can do this while Vault is unsealed.

Generally speaking, in practice, Vault does not stay in a sealed state very long -- it's usually only sealed when shutting down. It's also sealed on startup before being unsealed, but it doesn't have the master key in memory at that point.

**Comment by Vayu** [comment]
@jaidesai 
> The point of seal is that it's an API command. Someone wanting to stop Vault from being in service and is authorized to do so can cause Vault to stop serving requests.

I can imagine a use case for that. Although wouldn't it simply cause fail-over in HA mode? Then maybe smth like `cluster-seal` could be useful. In any case, one can at least try to erase the key from memory, otherwise "sealed after restart" and "sealed after 'seal'" are principally different states.

> I just wanted to add that sudo should be limited to specific commands, and if an operator does have (via sudo) access to dump Vault's memory, they can do this while Vault is unsealed.

Absolutely, my comment was mostly about accessing memory of unsealed vault. The docs are detailing the Shamir sharing scheme in multiple places, but don't stress enough that it is completely defeated by memory access (and setups with no-one having root access are pretty uncommon). In security explicit is better than implicit.

**Comment by jefferai** [comment]
>  In any case, one can at least try to erase the key from memory, otherwise "sealed after restart" and "sealed after 'seal'" are principally different states.

Yes -- and the master key is (it's in `core.go`) but you are right that the barrier keyring isn't. I'll add that in.

> The docs are detailing the Shamir sharing scheme in multiple places, but don't stress enough that it is completely defeated by memory access

We'll consider adding such a statement in. Vault is not unique here -- the same technique can read your TLS cert private keys out of basically any process, for instance.

**Comment by Vayu** [comment]
>> The docs are detailing the Shamir sharing scheme in multiple places, but don't stress enough that it is completely defeated by memory access

> We'll consider adding such a statement in. Vault is not unique here -- the same technique can read your TLS cert private keys out of basically any process, for instance.

Please do consider it, especially since Vault is trying to offer an approach where at least N people are required to reconstruct the master key. This constraint remains in effect only if no-one is authorized to have root-access/read memory of a running Vault (for instance pre-built verified VM images with locked root and very limited sudo).

**Comment by jefferai** [comment]
@Vayu Many, many constraints are no longer in effect if an untrusted person is given root access -- in Vault or anywhere else. :-)

**Comment by beeyeas** [comment]
Agreed, with the limitation on "sudo / root access to vault host" ( giving sudo access to production vault server , is like giving bank key to someone " ). Also i agree to the fact that vault / consul documentation could be better and lots more scope for improvements.

**Comment by InclinedScorpio** [comment]
hey! How to get the master key ? My vault is sealed and I am not able to find anywhere about it.
