### ISSUE TITLE
Anyone can see token by inspecting elements

### ISSUE THREAD

**Issue by bhargav2427** [hashicorp/vault#14475]
**Describe the bug**
When we authenticate using any method our token is visible in inspect elements and I think it should not be there.

**To Reproduce**
Steps to reproduce the behaviour:
1. In browser open vault.
2. Open Inspect elements menu and go to the Network tab.
3. Now log in using any authentication method. ( at the end vault uses a token to authenticate a user ).
4. Now in the resultant-acl packet you can see the token. ( If you do not find a token in this packet then check the first one or two packets you will be able to see your token  ).

**Expected behavior**
Token should not be visible in plain text format. Encrypt it.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.6.1
* Vault CLI Version (retrieve with `vault version`): 1.6..1
* Server Operating System/Architecture: Ubuntu 20.04.4 LTS

You can see screenshots.

![Screenshot 2022-03-13 145926](https://user-images.githubusercontent.com/47673253/158053852-96723224-9825-49c3-b9b2-975fe07aabfe.png)

![Screenshot 2022-03-13 144611](https://user-images.githubusercontent.com/47673253/158053882-6f35cc00-7049-465b-b23a-96aeb0b2828f.png)

**Comment by sgmiller** [comment]
Closing this as expected behavior.  The contents of any HTTP request made to Vault should be considered sensitive (including of course the request, parameters, response body, etc).  Vault should be accessed over TLS, wher all these values are encrypted.

**Comment by mickael-hc** [comment]
For any future security issues, please use security@hashicorp.com, per our [security policy](https://github.com/hashicorp/vault/security/policy).
