### ISSUE TITLE
PKI backend should validate input

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#1449]
During training today, almost half the class entered a silly and easy typo and Vault happily accepted the value.

```
vault write pki/roles/my-vault-com allowed_domains="my-vault.com" allowed_subdomains="true"
```

The actual config is:

``` diff
- allowed_subdomains
+ allow_subdomains
```

This is a really easy mistake since the prior value is `allowed_domains`. Could we validate the input and say something like:

> Unknown key(s): [allowed_subdomains]

/cc @jefferai

**Comment by jefferai** [comment]
This is more of a larger question around validating input based on endpoint schemas, which Vault doesn't do anywhere. But we could do something targeted here due to the value switch.
