### ISSUE TITLE
PKI backend reports useless allowed_base_domain key

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/vault#1452]
The following is the output for `vault read pki_mount/roles/ROLE`

However:

* `allowed_base_domain` isn't a thing - or is it?

```
Key                    	Value
allow_any_name         	false
allow_bare_domains     	false
allow_base_domain      	false
allow_ip_sans          	true
allow_localhost        	true
allow_subdomains       	true
allow_token_displayname	false
allowed_base_domain    	
allowed_domains        	example.com
client_flag            	true
code_signing_flag      	false
email_protection_flag  	false
enforce_hostnames      	true
key_bits               	2048
key_type               	rsa
lease                  	
lease_max              	
max_ttl                	(system default)
server_flag            	true
ttl                    	(system default)
use_csr_common_name    	true
```

**Comment by jefferai** [comment]
It used to be, but now the value that was there is converted into `allowed_domains`. It's a good point though, that should be suppressed from the output.

**Comment by gautaz** [comment]
Sorry to post again here but using vault 0.8.3 still displays the option when reading a PKI role.
That feels strange as the removal was merged last year and vault 0.8.3 was released on September this year.

Has something been reverted on this particular subject lately?

**Comment by jefferai** [comment]
Cannot reproduce:
```
$ vault read pki/roles/foo
Key                     Value
---                     -----
AllowExpirationPastCA   false
allow_any_name          false
allow_bare_domains      false
allow_base_domain       false
allow_glob_domains      false
allow_ip_sans           true
allow_localhost         true
allow_subdomains        false
allow_token_displayname false
allowed_domains         foobar.com
client_flag             true
code_signing_flag       false
email_protection_flag   false
enforce_hostnames       true
generate_lease          false
key_bits                2048
key_type                rsa
key_usage               DigitalSignature,KeyAgreement,KeyEncipherment
max_ttl                 768h0m0s
no_store                false
organization           
ou                     
server_flag             true
ttl                     0s
use_csr_common_name     true
use_csr_sans            true
```

**Comment by gautaz** [comment]
@jefferai I have misread something, I was under the impression that the OP was wondering what was the usage of `allow_base_domain` and why it was displayed when reading a PKI role (which is also obviously the case in your command line excerpt).

But in fact it was `allowed_base_domain` and not `allow_base_domain`. What originally bothered me and made me stump over this issue is that `allow_base_domain` is undocumented by `path-help`. If `allow_base_domain` is in fact undocumented, I will open a new issue if none exists on this particular subject for now.

Can you confirm?

**Comment by jefferai** [comment]
Fixed ^

**Comment by jefferai** [comment]
Correct!
