### ISSUE TITLE
Error checking seal status: context deadline exceeded

### ISSUE THREAD

**Issue by deepeshuniyal** [hashicorp/vault#14520]
**Describe the bug**
Using the vault server version 1.8.4., once in a 2 month (approx) suddenly vault stops responding and the error ``context canceled`` prints in the logs, at the same time when we hit status command it is giving error ``Error checking seal status: context deadline exceeded`` after few seconds.

after 10 min its failover and start working with passive server.
we checked the the network logs and disk, cpu , memory stats but it is not related that.

**To Reproduce**
We are not able to reproduce this error, it's happning once in 2 months. 

**Expected behavior**
The vault should not stop working, and if any problem some logs should be printed with details.

**Environment:**
```hcl
vault/1
Key             Value
---             -----
Seal Type       ***
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.8.4
Storage Type    consul
Cluster Name    vault-cluster-***
Cluster ID      ******
HA Enabled      true
HA Cluster      https://****:**
HA Mode         active
Active Since    2022-03-13T13:57:58.734095669Z
```

Vault server configuration file(s):

```hcl
backend "consul"{
  path = "vault/"
  address = "******:8500"
  scheme = "https"
  check_timeout = "5s"
  max_parallel = "128"
    tls_skip_verify = "true"
    
    tls_min_version = "tls12"
    tls_ca_file = "/var/vcap/jobs/vault/ssl/ca_certificate.pem"
    tls_cert_file = "/var/vcap/jobs/vault/ssl/consul_certificate.pem"
    tls_key_file  = "/var/vcap/jobs/vault/ssl/consul_key.pem"
  
    redirect_addr = "https://*****:8200"
}

listener "tcp" {
 address = "0.0.0.0:8200"
 tls_cert_file = "/var/vcap/jobs/vault/ssl/certificate.pem"
 tls_key_file  = "/var/vcap/jobs/vault/ssl/key.pem"
 tls_min_version = "tls12"
}

log_level = "Debug"

```

**Additional context**
The error is coming suddenly, that time system and load is normal.

**Comment by swayne275** [comment]
can you provide some logs or steps to reproduce?

**Comment by deepeshuniyal** [comment]
Hi @swayne275 ,

We are getting Error ``context canceled`` in the logs and when we hit the ``vault status`` command it was hang for few seconds and then return the error ``Error checking seal status: context deadline exceeded``.
we are not able to reproduce because it's happning once in 40-60 days and after 15 min its automatically recovered.
