### ISSUE TITLE
Huge number of leases when using k8s auth method

### ISSUE THREAD

**Issue by lukpep** [hashicorp/vault#14531]
We have vault deployed on k8s cluster and  integrated with several other k8s clusters using CSI driver to provide secrets to workloads there - it all works ok but...:
list of leases for every cluster is several thousand pages long...  e.g.
<img width="571" alt="CleanShot 2022-03-16 at 17 31 56@2x" src="https://user-images.githubusercontent.com/2960580/158641333-56a7430e-a615-484e-af66-65e04915a6fa.png">

which corresponds to the huge size of vault.db:

```
/vault/data $ ls -lh
total 8G
drwxrws---    2 root     vault      16.0K Nov 15 19:42 lost+found
-rw-rw----    1 vault    vault         36 Nov 15 19:42 node-id
drwxrwsr-x    3 vault    vault       4.0K Nov 15 19:42 raft
-rw-------    1 vault    vault       8.0G Mar 16 16:33 vault.db
```
and pods memory consumption:

```
(⎈ |gke-devops-prod:vault) ~  k top pods
NAME                                  CPU(cores)   MEMORY(bytes)
in-cluster-vault-0                    13m          79Mi
in-cluster-vault-1                    28m          369Mi
in-cluster-vault-2                    63m          9557Mi
```
Is it expected? We don't have like a big number of workloads there (maybe 20-30 with vault integration) - vault is being hit with no more than 1.5-2 RPS (not 2k rps - just 2 rps)

I believe it also translates to the fact that vault takes forever to restart / roll a new version - like 90-120 min per single pod and while this is happening other pod resource consumption goes to 11GB of data ...
What could be a misconfiguration on our side?

```
/ $ vault status
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    5
Threshold                3
Version                  1.9.2
Storage Type             raft
Cluster Name             vault-cluster-9a31ef1e
Cluster ID               2c73b387-93b4-792a-a2f4-f992dea448c0
HA Enabled               true
HA Cluster               https://in-cluster-vault-2.in-cluster-vault-internal:8201
HA Mode                  active
Active Since             2022-03-16T14:31:28.294057706Z
Raft Committed Index     23988789
Raft Applied Index       23988789
```

**Comment by lukpep** [comment]
we configure vault using terraform and our configuration is:

```
resource "vault_auth_backend" "k8s-apps-dev" {
  type = "kubernetes"
  path = "k8s-apps-dev"
  tune {
    default_lease_ttl = "1m"
    max_lease_ttl     = "1m"
  }
}

resource "vault_kubernetes_auth_backend_config" "k8s-apps-dev-config" {
  backend            = vault_auth_backend.k8s-apps-dev.path
  kubernetes_host    = "https://xxx.xx.xxx.xx"
  issuer             = "https://container.googleapis.com/v1/projects/xxxxxx/locations/europexxxxx/clusters/apps-dev-cluster"
  kubernetes_ca_cert = file("auth_data/apps-dev-cluster/ca_cert.crt")
  token_reviewer_jwt = file("auth_data/apps-dev-cluster/token.jwt")
}
```
tune section was added today in the hope that this may reduce the number of leases - I will wait for a couple of days to see if it helps somehow (the previous TTL was a default one of 768h).
Sadly I can't use any API / CLI method to revoke all leases under a specific prefix - it timeouts with information about context being canceled or something like that.

**Comment by maxb** [comment]
I made a few suggestions in #14415 which may be of use here too.

**Comment by lukpep** [comment]
It seems that i's by design after all - I had a fruitful discussion about it [here](https://discuss.hashicorp.com/t/huge-number-of-leases-while-using-auth-kubernetes/37137/14) - just to summarize:
 

> What is “broken” in the current CSI driver implementation in my opinion:
> 
> not making use of the lease TTL - instead rotation-poll-interval from [here](https://secrets-store-csi-driver.sigs.k8s.io/topics/secret-auto-rotation.html) is what defines the number of leases created per hour / month etc. Token created via single login should be cached and reused for the TTL it was created with
> CSI driver should not make requests (and logins) per pod in the replica set - it is counter-intuitive that deployment of 100 pods enforces 100 logins and 100 GETs for the same secret once every rotation-poll-interval (2 minutes by default) - it also creates inconsistency in the secret itself since this sync interval is bound to pod lifetime (counter starts when pod is created) and therefore can be a time period when the secret was refreshed in some portion of pods and not yet in other - and in max, it could last to rotation-poll-interval once again - which is definitely not desired.

**Comment by ncabatoff** [comment]
Hi @lukpep,

I don't have any real background with CSI, so I won't speak to your issue, but: can we close this issue on Vault in this case?  There's a repo for Vault CSI, if you'd like to open an issue there: https://github.com/hashicorp/vault-csi-provider

**Comment by lukpep** [comment]
sure - will move this topic to CSI repo
