### ISSUE TITLE
Okta authentication MFA_REQUIRED case does not recognize GOOGLE provider TOTP type

### ISSUE THREAD

**Issue by wenslayer** [hashicorp/vault#14535]
**Describe the bug**
When authenticating via Okta, Vault does not recognize the Google provider TOTP type.

**To Reproduce**
1. As a user in Okta, configure your "extra verification" to configure Google Authenticator.
2. Run `vault login -method=okta username=my.okta.username`
3. Get the following error:

```text
Error authenticating: Error making API request.

URL: PUT https://vault.my.domain/v1/auth/okta/login/my.okta.username
Code: 400. Errors:

* Okta Verify Push or TOTP factor is required in order to perform MFA
```

**Expected behavior**
The flow of being prompted for the TOTP.

**Environment:**
* Vault Server Version: 1.9.3
* Vault CLI Version: 1.9.4
* Server Operating System/Architecture: macOS 12.3

Vault server configuration file(s): 

```json
      {
        "storage": {
          "s3": {
            "bucket": "my.vault.bucket",
            "region": "${AWS_REGION}"
          }
        },
        "ha_storage": {
          "consul": {
            "address": "127.0.0.1:8500",
            "path": "vault"
          }
        },
        "service_registration": {
          "consul": {
            "address": "127.0.0.1:8500"
          }
        },
        "listener": {
          "tcp": {
            "address": "127.0.0.1:8200",
            "tls_disable": true
          }
        },
        "listener": {
          "tcp": {
            "address": "${IPV4}:8200",
            "tls_cert_file": "/etc/vault/certs/vault-pub.pem",
            "tls_key_file": "/etc/vault/certs/vault-priv.pem",
            "tls_min_version": "tls12"
          }
        },
        "ui": true,
        "api_addr": "https://${IPV4}:8200",
        "cluster_addr": "https://${IPV4}:8201"
      }
```

**Additional context**
It appears this code block is simply bypassing any provider that is NOT "OKTA", when it could accept the case when the provider is "GOOGLE" and the type matches `mfaTOTPMethod`.
* https://github.com/hashicorp/vault/blob/v1.9.4/builtin/credential/okta/backend.go#L182-L191

I see in the [Okta API documentation for supported factors for providers](https://developer.okta.com/docs/reference/api/factors/#supported-factors-for-providers):

Provider | Factor Type
-- | --
...
GOOGLE | token:software:totp
...
OKTA | token:software:totp

**Comment by wenslayer** [comment]
For comparison, [Nike-Inc/gimme-aws-creds](https://github.com/Nike-Inc/gimme-aws-creds/blob/9600146c5e6cd07fa024335b975e29a41117e8c6/gimme_aws_creds/okta.py#L548) authenticates against Okta and is able to properly handle when the extra verification is the Google token:software:totp.

**Comment by wenslayer** [comment]
Appears the problem persists in v1.10.0:

* https://github.com/hashicorp/vault/blob/v1.10.0/builtin/credential/okta/backend.go#L182-L191

**Comment by hghaf099** [comment]
The issue was fixed in https://github.com/hashicorp/vault/pull/14985
