### ISSUE TITLE
Unable to install Vault on Fedora using instructions from the official documentation

### ISSUE THREAD

**Issue by rosmanov** [hashicorp/vault#14570]
**Describe the bug**
Unable to install Vault on Fedora using dnf as described in the [official documentation](https://www.vaultproject.io/downloads).

**To Reproduce**
1. `sudo dnf install -y dnf-plugins-core`
2. `sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo`

**Expected output**

No error.

**Actual output**

```
Adding repo from: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
Status code: 405 for https://rpm.releases.hashicorp.com/fedora/hashicorp.repo (IP: 151.101.14.49)
Error: Configuration of repo failed
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): N/A
* Vault CLI Version (retrieve with `vault version`): N/A
* Server Operating System/Architecture: Fedora Linux 35 Workstation Edition

Vault server configuration file(s): N/A

**Comment by swayne275** [comment]
thanks for the call out. would you mind trying again? we're unable to reproduce this issue on F34. Thanks!

**Comment by solutiongeek** [comment]
Because of the conflict underway in Ukraine, HashiCorp is prohibiting availability of our products and services in Russia and Belarus.
