### ISSUE TITLE
Vault VM failing to start after restart

### ISSUE THREAD

**Issue by chrisrana** [hashicorp/vault#1458]
I have 3 Node Vault/Cluster cluster setup and I am  using DNS name in address filed in vault config file.It works fine, but when I stop and restart,it fails to restart.
I tried with IP address address =10.20.0.45 it failed

But when I change the address =127.0.0.1 it start it again it starts successfully .Look like socket problem.I am not getting any log also.Please help me what is going wrong here

```
backend "consul"{
  path = "vault/"
  address = "0.vault-consul.ccc-service-net.cf-devtest100vik.microbosh:8500"

  advertise_addr = "http://0.vault-consul.ccc-service-net.cf-devtest100vik.microbosh:8200"
}

listener "tcp" {
 address = "0.vault-consul.ccc-service-net.cf-devtest100vik.microbosh:8200"
 tls_disable = 1
 tls_cert_file = "/var/vcap/jobs/vault/ssl/certificate.pem"
 tls_key_file  = "/var/vcap/jobs/vault/ssl/key.pem"
}
default_lease_ttl = "17520h"

max_lease_ttl = "17520h"
```

**Comment by jefferai** [comment]
It seems like the DNS entries are no longer valid after a restart. Perhaps they change. If the machine has a Consul agent running locally, connecting via 127.0.0.1 is the recommended method anyways.

**Comment by chrisrana** [comment]
DNS is valid and I can see ping and dig command giving IP out dns name.

**Comment by jefferai** [comment]
What does Vault's log show?

**Comment by chrisrana** [comment]
It shows nothing ....looks like it is not writing ..before writing it is exitng

**Comment by chrisrana** [comment]
If I run vault using 127.0.0.1 i am not able to curl it from other VM.This is the reason I am running it using dns and IP address.

**Comment by jefferai** [comment]
0.0.0.0:8200 should work!

**Comment by chrisrana** [comment]
microbosh assign  each VM with dns and IP liek this
0.vault-consul.ccc-service-net.cf-devtest100vik.microbosh 10.20.0.45
1.vault-consul.ccc-service-net.cf-devtest100vik.microbosh 10.20.0.45
2.vault-consul.ccc-service-net.cf-devtest100vik.microbosh 10.20.0.45

If i do 
curl http://0.vault-consul.ccc-service-net.cf-devtest100vik.microbosh:8200/v1/sys/leader

**Will it work ?**

Anyway I am trying it ..let you know..Thanks !

**Comment by chrisrana** [comment]
Vault is coming up with 0.0.0.0:8200 ..but cluster is not working ..looks like consul/vault it not able to connect with this approach.
