### ISSUE TITLE
Web GUI doesn't show login window for OIDC providers not on oidc/ mount path

### ISSUE THREAD

**Issue by yee379** [hashicorp/vault#14606]
**Describe the bug**

OIDC providers on the non-default `oidc/` mount path, when configured, do not show the login prompt/window from the vault web gui.
 
**To Reproduce**

generically, the following works fine:

```
export VAULT_AUTH_PATH=oidc
export VAULT_LOGIN_ROLE=login

vault auth enable  -path=${VAULT_AUTH_PATH} oidc

vault write auth/${VAULT_AUTH_PATH}/config \
    oidc_client_id="${OIDC_VAULT_APP_ID}" \
    oidc_client_secret="${OIDC_CLIENT_SECRET}" \
    default_role="${VAULT_LOGIN_ROLE}" \
    oidc_discovery_url="https://dex.example.com"

vault write auth/${VAULT_AUTH_PATH}/role/${VAULT_LOGIN_ROLE} \
   user_claim="email" \
   allowed_redirect_uris="http://localhost:8250/oidc/callback" \
   allowed_redirect_uris="${VAULT_ADDR}/ui/vault/auth/oidc/oidc/callback"  \
   groups_claim="" \
   policies="default" \
   oidc_scopes="email profile"
```

ie when i use `oidc` as the Mount path in the GUI, i can log into the oidc provider and vault is all good.

however, if i change `VAULT_AUTH_PATH` to (for example) `otheroidc` with exactly the same configuration that worked with the above example under `oidc`. The I then attempt to log in via the vault web frontend - using

```
Sign in to Vault -> Other -> Method=OIDC, Role=(empty), Mount path=otheroidc
```

but when i click onto 'Sign in with OIDC Provider', there is no window popup for login.

if i inspect the webpage, i can see what when i use `oidc` as the Mount path, a http request is sent to vault with `data.auth_url`. however, when i use `otheroidc` the `data.auth_url` value is empty.

**Expected behavior**

A user is able to log in to any configured oidc provider on any mount path.

**Environment:**

vault 1.9.4

**Comment by austingebauer** [comment]
Hi, @yee379. Can you try to add another allowed redirect URI to the role? I think `allowed_redirect_uris="${VAULT_ADDR}/ui/vault/auth/${VAULT_AUTH_PATH}/oidc/callback"` should work. I believe that the `data.auth_url` is coming back empty because there isn't an `allowed_redirect_uri` that has the non-default mount path.

I also recognize that having to inspect the web page to figure out the error isn't ideal. The team is aware of this and is working to improve the experience.

**Comment by yee379** [comment]
duh of cousre! sorry my bad! i should have looked at the uri more closely - many thanks.
