### ISSUE TITLE
Feature request: Oracle database secret backend

### ISSUE THREAD

**Issue by mnatter** [hashicorp/vault#1460]
It'd be tremendously useful to have an Oracle DB secret backend for Vault, and dramatically broaden the incorporation of Vault into our (and I suspect many other groups') projects. Because our open source must be compatible for distribution over a range of enterprise stacks, we need to make sure that most everything we support can utilize both MS SQL and Oracle, as well as of course MySQL or postgreSQL.

**Comment by jefferai** [comment]
There is a company that has developed this internally and use planning on open sourcing it when finished. So I expect one will appear over time.

**Comment by mnatter** [comment]
Thanks for the info. Would be happy to provide testing and feedback on it.

**Comment by sirlatrom** [comment]
Any progress on this?

**Comment by jefferai** [comment]
Not yet.

**Comment by zhsc** [comment]
I'd also like to express my interest in this.  Maybe even if not a fully integrated backend,  maybe some tips on how to go about it.  I'm sure it depends on the situation,  but maybe a start point? 

Thanks, I think vault is great,   keep up the great work!

**Comment by tass6773** [comment]
Is this on the road map.  I am interested in this.

**Comment by jefferai** [comment]
As far as I know the company is still planning on developing/open sourcing this but are waiting on some things to be done in Vault first.

**Comment by sirlatrom** [comment]
@jefferai Just a quick ping to hear if said company might still be developing/open sourcing this, and to offer to collaborate/contribute if necessary

**Comment by simkin2004** [comment]
Do you have a timeframe for when the Oracle Secrets provider may be available?

**Comment by hazcod** [comment]
Ping
