### ISSUE TITLE
Dynamic Database Credencials on Kubernetes generates 2 credencials on pod startup

### ISSUE THREAD

**Issue by RafaelMontegordoFelix** [hashicorp/vault#14634]
**Describe the bug**
When a kubernetes pod is starting up and it requests a database dynamic credencial via kubernetes annotations, 2 credencials are created on sql server.
One is created before pod starts, then another is created after 1 or 2 seconds.
I notice this, because i read the secret file to environment variables, and i get the first credencial from the secrets file, but this credencial stops working after ttl is expired, because vault creates another and the last one is the one that vaults refresh.

**To Reproduce**
1. Follow the tutorial https://learn.hashicorp.com/tutorials/vault/kubernetes-external-vault?in=vault/kubernetes
2. Activate database engine
```
vault write database/config/sqlserver \
    plugin_name=mssql-database-plugin \
    connection_url='sqlserver://{{username}}:{{password}}@ipaddress' \
    allowed_roles="*" \
    username="user" \
    password="password"
```
3. Create a Role
```
vault write database/roles/some-db db_name=sqlserver \
creation_statements="CREATE LOGIN [{{name}}] WITH PASSWORD = '{{password}}';,Use DATABASE;,CREATE USER [{{name}}] FOR LOGIN [{{name}}];,ALTER ROLE [db_owner] ADD MEMBER [{{name}}];" \
revocation_statements="Use DATABASE DROP USER [{{name}}],DROP LOGIN [{{name}}]" \
default_ttl="3600" \
max_ttl="604800"
```
4. Apply kubernetes annotation on deployment
```
  # Database Credencials
  vault.hashicorp.com/agent-inject-secret-datasecuritydb: 'database/creds/database-db'
  vault.hashicorp.com/agent-inject-template-datasecuritydb: |
   {{- with secret "database/creds/datasecurity-db" -}}
     DBUSER="{{ .Data.username }}"
     DBPASSWORD="{{ .Data.password }}"
   {{- end }}
```

**Expected behavior**
It should only create one credencial at start up.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.9.3
Storage Type    consul
Cluster Name    vault-cluster-a30c57b2
Cluster ID      8bc415b6-73fb-e67b-3866-2e2e1650475a
HA Enabled      true
HA Cluster      https://vault.address.com
HA Mode         active
Active Since    2022-02-21T21:45:50.628010018Z
```

* Vault CLI Version (retrieve with `vault version`):
Vault v1.9.3 (7dbdd57243a0d8d9d9e07cd01eb657369f8e1b8a)

* Server Operating System/Architecture:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

Vault server configuration file(s):

```hcl
listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_disable = "false"
  tls_cert_file = "path/cert.pem"
  tls_key_file  = "path/key.pem"
}

storage "consul" {
  address = "127.0.0.1:8500"
  path = "vault/"
  token = "token"
}

api_addr = "https://vault.address.com"
ui = true

telemetry {
  prometheus_retention_time = "24h"
  disable_hostname = true
  unauthenticated_metrics_access = true
}

```

**Additional context**
As a work arround i added a 5 second delay before reading the secrets file to env variables.
With the 5 seconds delay i am getting the second created credencials.
But it is a gamble, if it takes more than 5 seconds, the app stops working.

Thanks

**Comment by abh** [comment]
Have you enabled the agent cache? Are you running the vault agent with both the init container and the sidecar?

**Comment by RafaelMontegordoFelix** [comment]
I do not have agent cache enabled.
When the pod is schedule, i have a init container, a vault agent container and my container.

**Comment by ajiteb** [comment]
Is there a solution to this problem?
This is also affecting me with postgresql database.

**Comment by tvoran** [comment]
Hi folks! As @abh alluded to, this is the issue that prompted us to add a persistent caching option to Vault agent: https://www.vaultproject.io/docs/agent/caching/persistent-caches/kubernetes

With persistent caching enabled, leased credentials (like database secrets) aren't immediately re-fetched by the sidecar container. Enable it by adding the annotation [`vault.hashicorp.com/agent-cache-enable: true`](https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-cache-enable) to your deployments.

I'll see if we can get the learn guide updated too.
