### ISSUE TITLE
Vault re-boot time is too slow on new node - bold db open takes longer

### ISSUE THREAD

**Issue by harsimranmaan** [hashicorp/vault#14635]
**Describe the bug**
When restarting vault after a node reboot, the boot is slow.
The metric vault_raft_storage_fsm_open_db_file is at ~550s. 
The time is spent open the bolt database at https://github.com/hashicorp/vault/blob/da0155ba197e3dc9f50695f49c52288a18ba8f1e/physical/raft/fsm.go#L173 

Started happening after upgrading from 1.7.9 to 1.8.9

**To Reproduce**
1. Terminate the node running vault 
2. Create a new node with same storage and run vault on it

**Expected behavior**
Vault boots up with the almost the same time as it would for a graceful restart.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.8.9 
* Vault CLI Version (retrieve with `vault version`): n/A
* Server Operating System/Architecture: Ubuntu linux amd64, 3 node integrated storage cluster, vault.db file ~2GB on SSD

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**
Observed when an instance running vault is terminated and a new one is brought back with the same storage attached. Seems related to https://support.hashicorp.com/hc/en-us/articles/4410227493651-Raft-startup-is-very-slow-after-upgrading-to-Vault-Enterprise-from-Vault-OSS.

**Comment by swayne275** [comment]
thanks for bringing this up. what sort of "disk" are you using? HDD? SSD?

**Comment by harsimranmaan** [comment]
Thanks @raskchanky. I read through the boldb code and figured out some optimization technique around freelists.  Like etcd, does vault provide a defrag option?

**Comment by harsimranmaan** [comment]
One thing that I still could not figure out, how is a restart of the vault process still so fast? Are the freelists synced to disk during a restart? The issues seems to be limited to a node restart

**Comment by raskchanky** [comment]
@harsimranmaan Vault does not provide a defrag option at this time.

Regarding the node restart vs the Vault process restart - when the node itself is rebooted, all of the OS caches are cleared, which means the rebuild process takes the longest. After Vault is running, if just the Vault process itself is restarted, it's fast because some of the data required for the freelist rebuild process is cached by the OS. But the freelist isn't synced to disk unless the `VAULT_RAFT_FREELIST_SYNC` environment variable is set.

**Comment by raskchanky** [comment]
I'm going to close this issue, as it's been open for awhile and I don't think there's much for us to do here at the moment. We realize the situation as it stands is sub-optimal and are frequently trying to improve performance during each release. Please feel free to reopen if you disagree and think there's more to do here right now.
