### ISSUE TITLE
auth/token is a mount but doesn't appear on the list

### ISSUE THREAD

**Issue by eherot** [hashicorp/vault#1463]
In case it's not clear I'm talking about this list:
```
$ /opt/vault/0.5.2/vault mounts
Path        Type       Default TTL  Max TTL  Description
cubbyhole/  cubbyhole  n/a          n/a      per-token private secret storage
secret/     generic    system       system   generic secret storage
sys/        system     n/a          n/a      system endpoints used for control, policy and debugging
```

- This makes it impossible to see the current TTL settings for tokens
- Had these been here in *some* capacity it would have saved me a lot of digging around trying to figure out how the TTL settings for auth/token are governed.
- It seems to be a mount, so clearly it should be listed

**Comment by jefferai** [comment]
`vault auth -methods` shows the list of auth mounts. You can use the `sys/mounts/(auth/token)/tune` (substituting in the correct path) to see TTL settings.

**Comment by jefferai** [comment]
Just to be clear -- you cannot adjust the TTL settings for auth mounts unless you are on vault `master`. This will work in the next released version, but does not work in 0.5.2.

**Comment by eherot** [comment]
Hmm, I guess the relationship between auth backends and mounts wasn't immediately apparent to me. I feel like this could probably be clearer in the docs. Similar to not showing `auth/*` in the mounts list, I would say that not showing the TTL settings under `GET sys/auth` is also confusing.

**Comment by jefferai** [comment]
TTL settings are not shown under `sys/auth` because modifying these is not currently supported. Now that it is, they will likely be added to the output in some near point (PRs welcome).
