### ISSUE TITLE
404 Not Found  UI error - after vault kv metadata put

### ISSUE THREAD

**Issue by ShriprasadM** [hashicorp/vault#14656]
**Describe the bug**
404 Not Found  UI error - after vault kv metadata put

**To Reproduce**
1.  vault kv metadata put app-config/config/shriprasad-test/project1
2.  Open vault UI and navigate through app-config/config/shriprasad-test/project1
3. 404 Not Found - page is shown with message - Unable to find secret at app-config/. Try going back to the [root](http://vault.localui/vault/secrets/app-config/list) and navigating from there.
 
**Expected behavior**
I should show project1 with no key values within it

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.8.3
* Vault CLI Version (retrieve with `vault version`): Vault v1.8.3 (73e85c3c21dfd1e835ded0053f08e3bd73a24ad6)
* Server Operating System/Architecture: Alpine Linux (Using Vault docker)

Vault server configuration file(s):

```hcl
no hcl file
```

**Additional context**

**Comment by hsimon-hashicorp** [comment]
Hi there. Are you using kv v1, or kv v2? If you're using kv v2, it may be trying to add `data` to your path. Let me know, and we can get it sorted. Thanks! :)

**Comment by ShriprasadM** [comment]
Hello @hsimon-hashicorp , I am using kv v2. not sure if it is adding `data` part. because I am using `vault` command

Another thing.

I am trying to create the same structure using REST API https://www.vaultproject.io/api-docs/secret/kv/kv-v2#create-update-metadata . but I am getting 204 no content.

My goal is to create empty directories on vault without having any key-values.

**Comment by ShriprasadM** [comment]
any updates here?

**Comment by ShriprasadM** [comment]
any updates here?

**Comment by ShriprasadM** [comment]
any updates here?

**Comment by ShriprasadM** [comment]
any updates here?

**Comment by ShriprasadM** [comment]
any updates here?

**Comment by hellobontempo** [comment]
Hi @ShriprasadM - could you give us more information surrounding your issue? We've made quite a few changes since 1.8 and I recommend upgrading to a newer version. 

A screen recording or screenshots of the issue you're seeing with the network tab visible would help debug
