### ISSUE TITLE
Unable to install Vault on RHEL using instructions from the official documentation

### ISSUE THREAD

**Issue by WhyJee** [hashicorp/vault#14667]
**Describe the bug**
Unable to install Vault on RHEL using dnf as described in the [official documentation](https://www.vaultproject.io/downloads).

**To Reproduce**
1. `sudo yum install -y yum-utils`
2. `sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo`
3. `sudo yum -y install vault`

Step 1 and 2 are ok but step 3 fails with:
```
failure: repodata/0619b86d206083e07b08aa06ee5a313bdde4b687-primary.xml.gz from hashicorp: [Errno 256] No more mirrors to try.
https://rpm.releases.hashicorp.com/RHEL/7/x86_64/stable/repodata/0619b86d206083e07b08aa06ee5a313bdde4b687-primary.xml.gz: [Errno 14] HTTPS Error 404 - Not Found
```

**Expected behavior**
Install successful

**Environment:**
* Vault Server Version (retrieve with `vault status`): N/A
* Vault CLI Version (retrieve with `vault version`): N/A
* Server Operating System/Architecture: RHEL x86_64 7 and 8

Vault server configuration file(s): N/A

**Comment by WhyJee** [comment]
thanks for the workaround @cpatanjali. I do confirm it seems to solve the issue.

**Comment by hsimon-hashicorp** [comment]
This has been fixed by our release engineering team. Can you please try again? Thanks! :)

**Comment by WhyJee** [comment]
@hsimon-hashicorp on our side it is ok. The problem is fixed.
Thanks for the quick resolution.

**Comment by hsimon-hashicorp** [comment]
Thanks for confirming! :)
