### ISSUE TITLE
Apache Zookeeper as an HA-enabled secrets backend.

### ISSUE THREAD

**Issue by rtkwgray** [hashicorp/vault#147]
We like what Vault offers so far, but it would be awesome if we could use our existing Apache Zookeeper deployment as a high-availability data store for Vault.

**Comment by mitchellh** [comment]
That could certainly work!

**Comment by sherzberg** [comment]
I'm halfway done with zk physical store. Hope to have a PR this afternoon.

**Comment by sherzberg** [comment]
non-ha implemented: https://github.com/hashicorp/vault/pull/149

**Comment by mitchellh** [comment]
Done!

**Comment by lclarkmichalek** [comment]
Hi, this was closed as non HA implemented, but looking at https://github.com/hashicorp/vault/blob/master/physical/zookeeper.go#L200 it seems that the zookeeper backend implements `LockWith`, and thus `physical.HABackend` (https://github.com/hashicorp/vault/blob/master/physical/physical.go#L30). What would be required for Zookeeper to be a full HABackend at this point?

**Comment by sherzberg** [comment]
@lclarkmichalek zk ha was implemented in https://github.com/hashicorp/vault/pull/252. so you should just need to setup the config file with the proper zk connection string.

**Comment by lclarkmichalek** [comment]
Great! One thing then; the documentation needs updating: https://github.com/hashicorp/vault/blob/master/website/source/docs/config/index.html.md Sorry for the noise :+1:

**Comment by jonashaag** [comment]
This is still missing from the docs

**Comment by jefferai** [comment]
@jonashaag Sorry, can you give me more context? The docs specify that ZK is an HA backend, and details the parameters `path` and `address`, and in the code for the ZK physical backend I see no checks for any other configuration parameters.

**Comment by jonashaag** [comment]
Oh. It wasn't clear to me until this point that storage and secret backends aren't the same concept, so I expected ZK to appear in the secret backends list. Maybe this could be made more explicit somewhere. The only place that this is explained that I found is in the Configuration section.

**Comment by jefferai** [comment]
Physical backends are configured in Vault's configuration file, not through it's API; that's why it's in the configuration section.
