### ISSUE TITLE
Use context in Kubernetes authentication

### ISSUE THREAD

**Issue by nicolascb** [hashicorp/vault#14724]
**Is your feature request related to a problem? Please describe.**

Today the Login method via Kubernetes receives a context but does not use it: [api/auth/kubernetes/kubernetes.go#L70](https://github.com/hashicorp/vault/blob/main/api/auth/kubernetes/kubernetes.go#L70)

**Describe the solution you'd like**

Using the latest version of the api, we can solve this problem like this:

[api/auth/kubernetes/kubernetes.go#L77](https://github.com/hashicorp/vault/blob/main/api/auth/kubernetes/kubernetes.go#L77)
```diff
-       resp, err := client.Logical().Write(path, loginData)
+       resp, err := client.Logical().WriteWithContext(ctx, path, loginData)
```

**Describe alternatives you've considered**
N/A

**Explain any additional use-cases**
N/A

**Comment by averche** [comment]
Hi @nicolascb!

Thank you for this suggestion! Now that we have `WithContext` methods, this change is quite easy. I have a PR that takes care of all of our current auth helpers in on shot: #14775

**Comment by averche** [comment]
I have merged the PR. Thank you for contributing to HashiCorp!
