### ISSUE TITLE
vault delete removes from consul but still shows up in vault

### ISSUE THREAD

**Issue by d4v3y0rk** [hashicorp/vault#1475]
when using `vault delete` on a path like `secret/apps/thing` when `thing` contains folders and keys the delete reports `success` and the folder and all its contents are removed from consul but `vault list secret/apps` still shows the `thing` folder and all its contents. 

Vault Version 0.5.2

**Comment by vishalnayak** [comment]
For anyone who wonders about this, `vault delete` is meant for deleting individual secrets and not for deleting a folder of secrets.

So, if there existed a secret by name `secret/apps/thing`, it would have been deleted.
Since there was a `secret/apps/thing/`, it wasn't deleted, as expected.
