### ISSUE TITLE
Update Documentation for STDOUT logging feature

### ISSUE THREAD

**Issue by AlyRagab** [hashicorp/vault#14772]
**Describe the solution you'd like**
Update the below documentation regarding the STDOUT as an audit logging feature along side with the file_path support
https://www.vaultproject.io/docs/audit

**Additional context**
Outputting logs to STDOUT is enabled as per this PR so we just need to make it clear in the official docs
PR : https://github.com/hashicorp/vault/pull/3235

**Comment by cipherboy** [comment]
This is doc'd on the file audit logging page: https://www.vaultproject.io/docs/audit/file#file_path
