### ISSUE TITLE
Vault in HA behind Haproxy LB not being directed to master

### ISSUE THREAD

**Issue by qgriffith** [hashicorp/vault#1482]
I have setup three vault (0.5.3) servers using consul as the backend. Consul is running in a three node cluster as well.  I have vault setup to go through haproxy as a load balancer to all there vault servers. The advertise_addr is set to point at the load balancer IP.  When I run a vault read command I will get an error every so often

```
vault read secret/foo
Error reading secret/foo: EOF 
```

I am guessing that this is because the load balancer is directing traffic to the standbye vault nodes.  Reading the documentation on setting up an HA cluster it looks like you can use the LB IP as the advertise_addr.  Vault is running in docker so using the containers IP address as the advertise_addr per vault node will not work in my situation since nothing will be able to route to the docker IP address.  Has anyone created a vault cluster using docker and an LB before?

**Comment by jefferai** [comment]
When you say "every so often", is it randomly distributed or do you see a cluster of them...for instance, for 10 seconds you get that result, then it clears up? It sounds like this could be from your Vault leader losing leadership but the LB not yet having an active node to redirect to (or directing to a standby but no active node for it to direct to).

**Comment by qgriffith** [comment]
If I run the vault read command three times in a row, at least one of them will fail with the error. It is the same error that I see if I try to read directly from a standby node. So my guess is the LB is sending me a standby node and the standby node isn't sending me back to the LB to try to get the active node.

**Comment by jefferai** [comment]
Can you try using `curl -v` to get a better idea of what's going on? My guess is that the LB is routing you to a standby, which routes you back to the LB, which then routes you to a standby, and this repeats until you hit a maximum number of redirects. `curl` can give much more information about what's going on than the Vault CLI.

We don't generally recommend LBs for reasons such as this, and because they usually take longer to converge when the active node fails over.

**Comment by qgriffith** [comment]
Here is the output of three curls only one of them worked.  If an LB is not recommend how do you send traffic to a cluster? Does the vault client take an array of hosts?

```
> GET /v1/secret/foo HTTP/1.1
> Host: 10.6.100.52:8200
> User-Agent: curl/7.43.0
> Accept: */*
> X-Vault-Token: RETRACTED
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Thu, 02 Jun 2016 18:32:17 GMT
< Content-Length: 110
<
{"lease_id":"","renewable":false,"lease_duration":2592000,"data":{"value":"bar"},"warnings":null,"auth":null}
* Connection #0 to host 10.6.100.52 left intact

```

```
> GET /v1/secret/foo HTTP/1.1
> Host: 10.6.100.52:8200
> User-Agent: curl/7.43.0
> Accept: */*
> X-Vault-Token: RETRACTED
>
< HTTP/1.1 307 Temporary Redirect
< Location: http://10.6.100.52:8200/v1/secret/foo
< Date: Thu, 02 Jun 2016 18:32:11 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 10.6.100.52 left intact
```

**Comment by jefferai** [comment]
@qgriffith Please use the `-L` option to `curl` to follow redirects. As you can see in the second example you got a 307 back because the LB sent you to a standby, but we can't see what happened after. (You may want to look at why the LB is sending you to standby nodes so often.)

You can avoid a load balancer by using a service discovery mechanism (like Consul) or you can use a load balancer but also have direct access to your nodes, so that if there is a redirect you are sent to the leader directly rather than back to the LB that sent you to the standby in the first place.

**Comment by qgriffith** [comment]
@jefferai  Here are the results from the -L option it looks like curl is following the redirects and is getting the value after all the redirects

No Redirects
```
*   Trying 10.6.100.52...
* Connected to 10.6.100.52 (10.6.100.52) port 8200 (#0)
> GET /v1/secret/foo HTTP/1.1
> Host: 10.6.100.52:8200
> User-Agent: curl/7.43.0
> Accept: */*
> X-Vault-Token: RETRACTED
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Thu, 02 Jun 2016 19:12:06 GMT
< Content-Length: 110
<
{"lease_id":"","renewable":false,"lease_duration":2592000,"data":{"value":"bar"},"warnings":null,"auth":null}
* Connection #0 to host 10.6.100.52 left intact
```

Redirect 
```
GET /v1/secret/foo HTTP/1.1
> Host: 10.6.100.52:8200
> User-Agent: curl/7.43.0
> Accept: */*
> X-Vault-Token: RETRACTED
>
< HTTP/1.1 307 Temporary Redirect
< Location: http://10.6.100.52:8200/v1/secret/foo
< Date: Thu, 02 Jun 2016 19:12:04 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 10.6.100.52 left intact
* Issue another request to this URL: 'http://10.6.100.52:8200/v1/secret/foo'
* Found bundle for host 10.6.100.52: 0x7f90eac0a330
* Re-using existing connection! (#0) with host 10.6.100.52
* Connected to 10.6.100.52 (10.6.100.52) port 8200 (#0)
> GET /v1/secret/foo HTTP/1.1
> Host: 10.6.100.52:8200
> User-Agent: curl/7.43.0
> Accept: */*
> X-Vault-Token: RETRACTED
>
< HTTP/1.1 307 Temporary Redirect
< Location: http://10.6.100.52:8200/v1/secret/foo
< Date: Thu, 02 Jun 2016 19:12:04 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 10.6.100.52 left intact
* Issue another request to this URL: 'http://10.6.100.52:8200/v1/secret/foo'
* Found bundle for host 10.6.100.52: 0x7f90eac0a330
* Re-using existing connection! (#0) with host 10.6.100.52
* Connected to 10.6.100.52 (10.6.100.52) port 8200 (#0)
> GET /v1/secret/foo HTTP/1.1
> Host: 10.6.100.52:8200
> User-Agent: curl/7.43.0
> Accept: */*
> X-Vault-Token: RETRACTED
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Thu, 02 Jun 2016 19:12:04 GMT
< Content-Length: 110
<
{"lease_id":"","renewable":false,"lease_duration":2592000,"data":{"value":"bar"},"warnings":null,"auth":null}
* Connection #0 to host 10.6.100.52 left intact
```

**Comment by qgriffith** [comment]
Side not I am testing with the ruby gem and I am not able to get it to fail. The ruby gem seems to follow the redirects and always gets a response.

**Comment by jefferai** [comment]
OK, this definitely explains it. For security the Vault CLI will only follow a single redirect -- it's not really designed for situations where a load balancer is giving it bad addresses. I think the way forward is to fix your load balancer status checks such that it always directs to the active node -- it seems like it's more or less round-robin-ing.
