### ISSUE TITLE
LDAP aliases will be created with the login name not the corresponding LDAP user attribute

### ISSUE THREAD

**Issue by anxstj** [hashicorp/vault#14823]
**Describe the bug**

If LDAP authentication is activated then user accounts will be created in Vault on the first login. In that case, Vault creates an entity and an alias. The alias name is the same as the login name, entered by the user on the first login. This is unexpected because the alias name should match the LDAP user attribute.

In our case, we use the samAccountName as user attribute. The samAccountName might be, for example, "jdoe", but the user logins in with "JDoe" then the alias name will be created as "JDoe", but that doesn't match the samAccountName attribute.
In our case every user will get its own secret engine, in this example `users/JDoe` and the following policy will be added to each account:

```
path "users/{{ identity.entity.aliases.auth_ldap_ff66461a.name }}/*" {
  capabilities = ["create", "update", "read", "list", "delete"]
}
```

So the secret engine's path must match the alias name (that's done by a tool that reads the alias name and create the secret engine if not present). But an external tool that tries to write a secret into the secret engine has difficulties getting the correct path because it's constructed from the accounts alias name, but that must not match the login name (`jdoe` vs `jDoe`) nor must it match the user attribute (samaccountname).

**To Reproduce**

* Enable LDAP auth
* Configure LDAP:
```
{
  "binddn": "CN=...",
  "bindpass": "secret",
  "deny_null_bind": true,
  "discoverdn": false,
  "groupattr": "cn",
  "groupdn": "OU=Groups,...",
  "groupfilter": "(\u0026(objectClass=group)(member:1.2.840.113556.1.4.1941:={{.UserDN}}))",
  "insecure_tls": false,
  "starttls": false,
  "url": "ldaps://10.10.10.10:636",
  "userattr": "sAMAccountName",
  "userdn": "OU=Users,..."
}
```
* Chose a LDAP user to test the login. In this example the user is called John Doe with a samaccountname of "jdoe".
* Login as "jdoe". An entity with the alias "jdoe" will be created
* Remove the newly created entity
* Login as "JDoe". An entity with the alias "JDoe" will be created

**Expected behavior**

In every case, regardless of the user's login name "jdoe" or "JDoe", an alias name will be created that matches the LDAP user attribute.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.7.3
* Vault CLI Version (retrieve with `vault version`): 1.7.3
* Server Operating System/Architecture: Debian 10 (buster), x86_64

Vault server configuration file(s):

```hcl
storage "file" {
  path = "/data"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  cluster_address = "0.0.0.0:8201"
  tls_cert_file = "/etc/vault.d/vault_cert.pem"
  tls_key_file  = "/etc/vault.d/vault_privkey.pem"
  telemetry {
    unauthenticated_metrics_access = true
  }
  proxy_protocol_behavior = "allow_authorized"
  proxy_protocol_authorized_addrs = "172.17.0.2"
}

api_addr = "https://linux-debian-10"
cluster_addr = "https://172.17.0.2:8201"
ui = true
log_level = "info"

default_lease_ttl = "25h"
max_lease_ttl = "768h"

default_max_request_duration = "90s"
```

**Comment by calvn** [comment]
Hi @anxstj the introduction of user filters in Vault 1.9 also made adjustments the way that `userattr` is used for the alias entity name. IIUC you want the alias to not be based on the login username but rather the value of userattr (e.g. the value of a user's `sAMAccountName`) that's on the LDAP side. This should be handled if you're on Vault 1.9 or above. In your example, if the `sAMAccountName` in LDAP is "jdoe", login in as either "JDoe" or "jdoe" will result in an alias with the name "jdoe" given your sample configuration.

I also wanted to mention that on Vault 1.10, we re-introduced an option to revert back to the behavior of alias name mapping against login username, if desired, through the `username_as_alias` parameter. You can read more about the details of the alias mapping change in [this section](https://www.vaultproject.io/docs/release-notes/1.10.0#ldap-auth-method-entity-alias-mapping) of our 1.10 release notes page.

**Comment by anxstj** [comment]
@calvn, thanks for your detailed answer. And great that this is already fixed.
