### ISSUE TITLE
transit seal not renewing its token with upstream vault

### ISSUE THREAD

**Issue by candlerb** [hashicorp/vault#14833]
**Describe the bug**
I have a situation with two local vault VMs (vault1 and vault2) which are configured for transit unseal with an upstream "root" vault which is running in GCP with KMS unseal.

```
   vault-root
    ^      ^
    |      |
 vault1  vault2
```

Configuration on vault1 and vault2:

```
seal "transit" {
  address = "https://vault-root.example.net:8200"
  token = "s.XXXXXXXX"
  key_name = "autounseal"
  mount_path = "transit/"
  disable_renewal = "false"
}
```

(vault1 and vault2 have their own tokens, from when transit unseal was set up)

This works fine.  In fact, it works so well that many weeks have passed since I last had to restart vault1 or vault2.

Unfortunately, when I recently restarted vault1 and vault2 I find that the unseal fails :-(

```
Apr 01 14:42:58 vault1 systemd[1]: Started Vault secret store.
Apr 01 14:42:59 vault1 vault[432769]: Error parsing Seal configuration: Error making API request.
Apr 01 14:42:59 vault1 vault[432769]: URL: PUT https://vault-root.example.net:8200/v1/transit/encrypt/autounseal
Apr 01 14:42:59 vault1 vault[432769]: Code: 403. Errors:
Apr 01 14:42:59 vault1 vault[432769]: * permission denied
Apr 01 14:42:59 vault1 vault[432769]: 2022-04-01T14:42:59.154Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
Apr 01 14:42:59 vault1 vault[432769]: 2022-04-01T14:42:59.647Z [INFO]  seal.transit: unable to renew token, disabling renewal:
Apr 01 14:42:59 vault1 vault[432769]:   err=
Apr 01 14:42:59 vault1 vault[432769]:   | Error making API request.
Apr 01 14:42:59 vault1 vault[432769]:   |
Apr 01 14:42:59 vault1 vault[432769]:   | URL: PUT https://vault-root.example.net:8200/v1/auth/token/renew-self
Apr 01 14:42:59 vault1 vault[432769]:   | Code: 403. Errors:
Apr 01 14:42:59 vault1 vault[432769]:   |
Apr 01 14:42:59 vault1 vault[432769]:   | * permission denied
Apr 01 14:42:59 vault1 vault[432769]:
Apr 01 14:42:59 vault1 systemd[1]: vault.service: Main process exited, code=exited, status=1/FAILURE
Apr 01 14:42:59 vault1 systemd[1]: vault.service: Failed with result 'exit-code'.
```

Checking the token from `vault-conf.hcl` explicitly:

```
$ bash
bash-5.1$ export VAULT_ADDR=https://vault-root.example.net:8200
bash-5.1$ vault login
Token (will be hidden):
Error authenticating: error looking up token: Error making API request.

URL: GET https://vault-root.example.net:8200/v1/auth/token/lookup-self
Code: 403. Errors:

* permission denied
```

It seems to me that the token was not being renewed.

First I have to fix this, by creating new suitable tokens so I can unseal vault1 and vault2.  Once I've done this, I should be able to confirm that the token is not being renewed by doing a 'lookup' on the token periodically.

**To Reproduce**
1. Install two instances of vault: vault-root and vault1
2. Follow the [transit seal migration](https://www.vaultproject.io/docs/concepts/seal#seal-migration) document so that vault1 now uses transit unseal against vault-root
3. Restart vault1, check that it auto unseals. Leave it running but idle, i.e. don't hit it with API calls.
4. Wait for the token TTL to expire
5. Restart vault1

**Expected behavior**
With `disable_renewal = "false"`, I would expect Vault to periodically contact the upstream unseal server to renew its token - even when completely idle.

**Environment:**
* Vault Server Version (retrieve with `vault status`): vault-root is running v1.9.3, vault1/vault2 are v1.9.4
* Vault CLI Version (retrieve with `vault version`): v1.9.4
* Server Operating System/Architecture: Ubuntu 20.04

Vault server configuration file(s):

For vault-root:

```
seal "gcpckms" {
  project     = "example-vault"
  region      = "global"
  key_ring    = "vault"
  crypto_key  = "unseal"
}
```

For vault1/2, see above.

**Additional context**
N/A

**Comment by candlerb** [comment]
If I login to vault-root with a root token, and then do `vault list auth/token/accessors`, I only see a single token accessor (which matches the root token's accessor).  So I think it's pretty certain that the previously-issued tokens have expired.

I created two new ones (one each for vault1 and vault2) using:

```
bash-5.1$  vault token create -policy="autounseal"
```

vault1 and vault2 have now unsealed, which is good.  I can confirm the remaining TTL of each:

```
bash-5.1$ vault token lookup -accessor 74SwtY4ZMan15WxaZfmcP5YA
Key                  Value
---                  -----
accessor             74SwtY4ZMan15WxaZfmcP5YA
creation_time        1648828641
creation_ttl         768h
display_name         token
entity_id            n/a
expire_time          2022-05-03T15:57:21.519179186Z
explicit_max_ttl     0s
id                   n/a
issue_time           2022-04-01T15:57:21.196890585Z
last_renewal         2022-04-01T15:57:55.519179364Z
last_renewal_time    1648828675
meta                 <nil>
num_uses             0
orphan               false
path                 auth/token/create
policies             [autounseal default]
renewable            true
ttl                  767h57m29s
type                 service
bash-5.1$ vault token lookup -accessor Y1SlM7L9nl0qkE41OuxvnJis
Key                  Value
---                  -----
accessor             Y1SlM7L9nl0qkE41OuxvnJis
creation_time        1648828675
creation_ttl         768h
display_name         token
entity_id            n/a
expire_time          2022-05-03T15:57:55.716397109Z
explicit_max_ttl     0s
id                   n/a
issue_time           2022-04-01T15:57:55.752239715Z
last_renewal         2022-04-01T15:58:46.716397247Z
last_renewal_time    1648828726
meta                 <nil>
num_uses             0
orphan               false
path                 auth/token/create
policies             [autounseal default]
renewable            true
ttl                  767h57m10s
type                 service
```

I'll monitor these over the next few days and see if the token gets renewed or not.

"Last renewal" suggests that the tokens were renewed when vault1/2 started and unsealed themselves.

I was expecting renewal to happen periodically while Vault continues to run.  If it doesn't, then a workaround will be to restart Vault every week via a cronjob, to force an unsealing and renewal.

**Comment by candlerb** [comment]
Perhaps this is a duplicate of #11149.  In that ticket, the OP was trying a "vault rekey", whereas here I'm just restarting vault.  However I suspect in both cases, the problem is an expired transit token.

**Comment by candlerb** [comment]
Just checked the token after about two and a half days:

```
$ vault token lookup
Key                  Value
---                  -----
accessor             74SwtY4ZMan15WxaZfmcP5YA
creation_time        1648828641
creation_ttl         768h
display_name         token
entity_id            n/a
expire_time          2022-05-03T15:57:21.519179186Z
explicit_max_ttl     0s
id                   s.AOwBHM1P0xQu6YmguEYOsoOV
issue_time           2022-04-01T15:57:21.196890585Z
last_renewal         2022-04-01T15:57:55.519179364Z
last_renewal_time    1648828675
meta                 <nil>
num_uses             0
orphan               false
path                 auth/token/create
policies             [autounseal default]
renewable            true
ttl                  704h32m29s
type                 service
```

* `last_renewal_time` is unchanged
* `ttl` is ticking down

So Vault has not renewed its transit seal token in that time - although it's unclear *when* it would do so (every day? When TTL reaches a percentage of creation_ttl? Only when Vault is restarted?).  The documentation doesn't say.

**Comment by welderpb** [comment]
@candlerb Thank you for issue explanation.. 
Same issue for me.. It is unclear how vault renew transit seal token..

**Comment by ncabatoff** [comment]
>  it's unclear when it would do so (every day? When TTL reaches a percentage of creation_ttl? Only when Vault is restarted?).

The code you're interested in lives here: https://github.com/hashicorp/go-kms-wrapping/blob/main/wrappers/transit/transit_client.go#L142

As you can see, it relies on 
https://pkg.go.dev/github.com/hashicorp/vault/api#Client.NewLifetimeWatcher

LifetimeWatcher aims to renew about 2/3 of the way through the available time before it would expire.  If that attempt fails, it should continue attempting to renew through most of the remaining time.

**Comment by candlerb** [comment]
Thanks for the pointers.  I can't see what's wrong, but clearly token renewal *should* be happening.  AFACIS it should kick in at 2/3 lease + 1/3 of (random 10-20% of lease), which makes it 70%-73.3% of lease, or in this case 22.4 - 23.5 days.

It also looks like there should have been a log message saying "shutting down token renewal" if the renewal goroutine stopped. Unfortunately I don't have any record of that: I had configured systemd to retry every 30 seconds on failure to start Vault, so if that message did appear in the journal buffer, it has long gone.

I don't know if there's supposed to be a log message saying when the transit seal renewal goroutine *starts* - I can't see one in Vault's output.  I see:

```
Apr 01 15:58:46 vault2 vault[280994]:                Log Level: info
...
Apr 01 15:58:46 vault2 vault[280994]: ==> Vault server started! Log data will stream in below:
Apr 01 15:58:46 vault2 vault[280994]: 2022-04-01T15:58:46.176Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
Apr 01 15:58:46 vault2 vault[280994]: 2022-04-01T15:58:46.808Z [INFO]  core: Initializing VersionTimestamps for core
Apr 01 15:58:46 vault2 vault[280994]: 2022-04-01T15:58:46.852Z [INFO]  core: stored unseal keys supported, attempting fetch
Apr 01 15:58:46 vault2 vault[280994]: 2022-04-01T15:58:46.970Z [INFO]  core.cluster-listener.tcp: starting listener: listener_address=[::]:8201
Apr 01 15:58:46 vault2 vault[280994]: 2022-04-01T15:58:46.970Z [INFO]  core.cluster-listener.tcp: starting listener: listener_address=[::]:18201
Apr 01 15:58:46 vault2 vault[280994]: 2022-04-01T15:58:46.971Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=[::]:8201
Apr 01 15:58:46 vault2 vault[280994]: 2022-04-01T15:58:46.971Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=[::]:18201
Apr 01 15:58:46 vault2 vault[280994]: 2022-04-01T15:58:46.972Z [INFO]  core: vault is unsealed
Apr 01 15:58:46 vault2 vault[280994]: 2022-04-01T15:58:46.972Z [INFO]  core: unsealed with stored key
Apr 01 15:58:46 vault2 vault[280994]: 2022-04-01T15:58:46.974Z [INFO]  core: entering standby mode
Apr 03 23:58:16 vault2 systemd[1]: Reloading Vault secret store.
Apr 03 23:58:16 vault2 systemd[1]: Reloaded Vault secret store.
Apr 03 23:58:16 vault2 vault[280994]: ==> Vault reload triggered
```

(Aside: that reload was triggered from a LetsEncrypt certificate renewal cronjob)

**Comment by chrishoffman** [comment]
There are two things that I notice on your setup that may be causing your token to prematurely expire.
1. The token is not an orphan token which means that the parent token could be expiring even though you keep on renewing the child token. You can read more about token hierarchies [here](https://www.vaultproject.io/docs/concepts/tokens#token-hierarchies-and-orphan-tokens).
2. You could be hitting the max ttl for the token which would cause renewals to stop. You should investigate creating [periodic tokens](https://www.vaultproject.io/docs/concepts/tokens#periodic-tokens) which can extend the life of the token past max ttl as long as the service keeps checking in.

**Comment by candlerb** [comment]
Thanks.  I went back to my notes to see how I created the very first token, and indeed I had used

```
vault token create -policy="autounseal" -orphan`.
```

The later command `vault token create -policy="autounseal"`, I took directly from the tutorial [here](https://learn.hashicorp.com/tutorials/vault/autounseal-transit?in=vault/auto-unseal#step-1-configure-auto-unseal-key-provider-vault-1).  Perhaps that should have the `-orphan` flag added for completeness?

However I don't think the orphan token is an issue here, because I used a root token as the parent (which has infinite TTL AFAIK), and I never revoked it.

As for periodic tokens, I'll need to research that further.  I still don't really understand the difference between "ttl", "max_ttl", "effective max_ttl" and "explicit_max_ttl"

**Comment by RickyGrassmuck** [comment]
I've had this issue as well and while I was aware of the existence of periodic tokens, I never considered that not having one for this was the issue (in hindsight.... lol).

For reference, in order to make a token periodic, you will need to:

1. Create the token while authenticated with a token that has sudo privileges on `auth/token/create` or using a root token (not advised!)
2. Include the `--period=<time>` parameter in your token generation command.

If you include any of the "ttl" flags in your command, you will likely not get the results you were looking for.


I'm about to deploy a new token to one of my cluster members that was generated using the command below and will be testing a restart of the server once the token has lived longer than the set period. This is just a test token and the 5 minute period is probably too short for use in a production cluster as anything that would prevent a vault server from reaching the unseal server for  more than 5 minutes would result in your token fully expiring.

```vault token create -policy="autounseal" -orphan --period=5m```

I suspect this will work as expected and if so the documentation and Learn Guide should be updated to, at the very least, present this distinction and ideally update the examples to include a sane period in the commands.

**Comment by RickyGrassmuck** [comment]
Ok, so the renewal is working as expected and looking at the token info from both the periodic and a token generated using the command provided in the docs (ie. the "broken" way), there are some key differences that look promising.

Below are some of the token details for both the periodic and standard tokens:

**New Periodic**
```
root@vault-seal-server:~# vault token lookup | grep 'ttl\|period\|time'
creation_time        1650738923
creation_ttl         5m
expire_time          2022-04-23T18:46:16.333712979Z
explicit_max_ttl     0s
issue_time           2022-04-23T18:35:23.227885303Z
last_renewal_time    1650739276
period               5m
ttl                  3m51s
```
Old Standard Token
```
root@vault-seal-server:~# vault token lookup | grep 'ttl\|period\|time'
creation_time       1650738947
creation_ttl        1h
expire_time         2022-04-23T19:35:47.873678696Z
explicit_max_ttl    0s
issue_time          2022-04-23T18:35:47.87368478Z
ttl                 50m45s
```

The periodic token contains fields related to renewals in it whereas the token generated using the command from the examples doesn't.

I'm personally pretty confident this is the root of both this issue and #11149 and IMO, the learn guide and Transit Autounseal docs should be updated to include the `--period` flag in their example commands.

A bit of a sidebar from this issue, while the [docs about token concepts](https://www.vaultproject.io/docs/concepts/tokens) does provide most the information needed for someone who's more familiar with token concepts, I don't think it's likely useful for newer/less experienced users.

I did some poking around on the Learn site and was surprised to come across this [Vault Tokens Learn Guide](https://learn.hashicorp.com/tutorials/vault/tokens#periodic-service-tokens) that goes in-depth and hands on with all types of tokens and their uses. Unfortunately, I did not find any link to, or mention of, this guide on that Tokens Concepts page. That guide looks extremely thorough and IMO deserves to explicitly featured prominently on the Tokens Concepts docs page so more users are directed to it!

**Comment by candlerb** [comment]
Many thanks for that; I have now recreated tokens with

```
vault token create -policy="autounseal" -orphan -period=768h
```

(Aside: according to the help page it should be `-period` not `--period`, but both appear to work)

I will leave this ticket open for the documentation updates you suggest. Previously the only documentation I could find about periodic tokens was [the concepts section](https://www.vaultproject.io/docs/concepts/tokens#periodic-tokens), which doesn't show what command you'd use to generate a periodic token.

-----

As a general point, I find the Vault documentation to be comprehensive but hard to navigate. Different aspects of the same topic may be covered in three or four different places; in some cases there are links to related docs and some cases not.  Having the pages _tagged_ by topic would be very helpful.

Token TTLs are a particularly complex topic.  There is TTL, max TTL, explicit max TTL, and according to this message from the CLI/API there is also "effective max TTL"

```
$ vault token renew
WARNING! The following warnings were returned from Vault:

  * TTL of "16h" exceeded the effective max_ttl of "9h2m31s"; TTL value is
  capped accordingly
```

**Comment by helicase-bzh** [comment]
Hello,
i have the same issue, i created a orphan token with a period equal at 96 hours.
after on hour the renewal does not work anymore and the token expire after 96 hours.
But if if fix periodic to 5 minutes it's work.
my token setup :
```
Key                  Value
---                  -----
accessor             xxxxx
creation_time        1660117241
creation_ttl         5m
display_name         token-token
entity_id            n/a
expire_time          2022-08-10T08:31:29.073966516Z
explicit_max_ttl     0s
id                   hvs.xxxxxxx
issue_time           2022-08-10T07:40:41.463970332Z
last_renewal         2022-08-10T08:26:29.073966636Z
last_renewal_time    1660119989
meta                 <nil>
num_uses             0
orphan               true
path                 auth/token/create
period               5m
policies             [autounseal default]
renewable            true
ttl                  4m47s
type                 service

```
A max TTL seems hiden somewhere but i don't know where ....

**Comment by helicase-bzh** [comment]
Hi,
FYI : vault 1.11.1 and above fix this issue

**Comment by candlerb** [comment]
How exactly did it change? I can't see a relevant point in the [1.11.1 changelog](https://github.com/hashicorp/vault/blob/main/CHANGELOG.md#1111).

Also, I think the documentation [here](https://learn.hashicorp.com/tutorials/vault/autounseal-transit?in=vault/auto-unseal#step-1-configure-auto-unseal-key-provider-vault-1) could still do with updating. In the last section under Step 1 it shows:

```
vault token create -policy="autounseal" -wrap-ttl=120
```

but I think something like this would be better:

```
vault token create -policy="autounseal" -wrap-ttl=120 -orphan -period=768h
```

**Comment by helicase-bzh** [comment]
i'am agree with you no relevant point in the changelog.
But i deployed 1.11.2 and the renewal token work as expected. with :
`ault token create -policy="autounseal" -orphan -period=96h`
This setup did not work with vault 1.11.0

**Comment by candlerb** [comment]
Strange, because that worked for me with 1.9.4 and 1.10.1

**Comment by ncabatoff** [comment]
I've applied the docs change suggestions found in the comments of this ticket (thanks for those).  I'm looking into how to get the tutorial updated similarly.  There doesn't seem to be anything left to do here so I'm closing this ticket.

**Comment by Skybladev2** [comment]
I'm facing the same issue when running Vault v1.14.0 - is the a regression?

I followed the updated tutorial with the command 
```bash
vault token create -orphan -policy="autounseal" \
   -wrap-ttl=120 -period=24h \
   -field=wrapping_token > wrapping-token.txt

```
but when downstream Vault is restarted after several weeks of uptime the same 403 Permission denied error appeared.
Recreating token from scratch fixes the issue, but I don't know if it will get renewed yet.

**Comment by candlerb** [comment]
AFAIK, a wrapped token can only be unwrapped once. Have you tried putting the *unwrapped* token in the Vault config file?

**Comment by Skybladev2** [comment]
@candlerb Sure, sorry fo confusion.

I unwrapped it immediately using the next instruction from the [docs](https://developer.hashicorp.com/vault/tutorials/auto-unseal/autounseal-transit?in=vault%2Fauto-unseal#step-2-configure-auto-unseal-vault-2):
```bash
vault unwrap -field=token $(cat wrapping-token.txt)
```
