### ISSUE TITLE
Enable replication enterprise feature on GCS backend

### ISSUE THREAD

**Issue by tal-ayalon** [hashicorp/vault#14862]
**Is your feature request related to a problem? Please describe.**
https://discuss.hashicorp.com/t/enable-repication-primary-on-gcs-backend/37810/6
GCS backend can't use the Vault enterprise feature of replication.
```
curl http://127.0.0.1:8200/v1/sys/replication/dr/status
{"request_id":"1234-5678-abcd-efgh-12345abcde",..."data":{"mode":"unsupported"}...}
```

**Describe the solution you'd like**
GCS backend will also be able to use the replication feature:
```
curl http://127.0.0.1:8200/v1/sys/replication/dr/status
{"request_id":"1234-5678-abcd-efgh-12345abcde",..."data":{"mode":"disabled/enabled"}...}
```

**Explain any additional use-cases**
I have a Vault cluster that uses GCS backend & I need to migrate it to Raft cluster. I thought about doing it using the replication feature to avoide downtime.
The alternative of using the DR replication feature is using `vault operator migarate` command, to copy the data from the GCS bucket to Raft.

**Additional context**
Using 1.9.3 Enterprise image.
Using GKE & Helm to deploy the Vault

**Comment by tal-ayalon** [comment]
Yes, I created a ticket

**Comment by hsimon-hashicorp** [comment]
> Yes, I created a ticket

Thanks! This repo is for the OSS version of Vault, so since you've created an Enterprise ticket, I will close this issue now. Thanks again. :)
