### ISSUE TITLE
Error initializing storage of type raft: truncate: truncate raft.db: There is not enough space on the disk.

### ISSUE THREAD

**Issue by idimov-keeper** [hashicorp/vault#14895]
**Describe the bug**
Vault server 1.10.0 fails to start on Windows 11 with error `Error initializing storage of type raft: failed to create fsm: failed to open bolt file: truncate: truncate C:\TEMP\vault\data\vault.db: There is not enough space on the disk.`
The only file created in data folder is C:\TEMP\vault\data\vault.db - 16.0 KB (16,384 bytes)
Drive C: has 46 GB free space
Drive C: file system - NTFS

**To Reproduce**
1. Run `vault server -config=vault01.hcl` (pasted in config section below)
2. See error - note: Drive C: has 46 GB free space
```
C:\TEMP\vault>vault server -config=vault01.hcl

Error initializing storage of type raft: failed to create fsm: failed to open bolt file: truncate: truncate C:\TEMP\vault\data\vault.db: There is not enough space on the disk.
2022-04-04T15:45:46.146-0500 [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""

C:\TEMP\vault>
```

**Expected behavior**
Vault server starts and is ready to accept requests

**Environment:**
* Vault Server Version (retrieve with `vault status`):  Version            1.10.0
* Vault CLI Version (retrieve with `vault version`):  Vault v1.10.0 (7738ec5d0d6f5bf94a809ee0f6ff0142cfa525a6)
* Server Operating System/Architecture: x64-based PC - Microsoft Windows 11 Pro / Version	10.0.22000 Build 22000

Vault server configuration file(s):

```hcl
# C:\TEMP\vault\vault.exe
# C:\TEMP\vault\vault01.hcl
disable_mlock = true

storage "raft" {
  path    = "C:/TEMP/vault/data"
  node_id = "node1"
}

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = "true"
}

api_addr = "http://127.0.0.1:8200"
cluster_addr = "https://127.0.0.1:8201"
ui = true
# UI doesn't show but that's a separate bug
```

**Additional context**
This was working 2-3 versions ago. Currently not working with existing raft  DB too - vault server exits with same error `There is not enough space on the disk.`

**Comment by hsimon-hashicorp** [comment]
Hi there! Can you confirm the permissions on the TEMP folder you're using for raft? I have seen sometimes a "not enough space" error be a permissions error instead.

**Comment by idimov-keeper** [comment]
The folder is created by the same user that is trying to run vault server so I assume that user has full permissions
C:\TEMP\vault\ was created by the same user starting the vault server
C:\TEMP\vault\data\ also created by same user
BTW: vault successfully created `C:\TEMP\vault\data\vault.db` file 16.0 KB (16,384 bytes)
so definitely not an access issue nor permission error

**Comment by idimov-keeper** [comment]
Note - I was getting same error on my existing raft DB that was working fine 2-3 versions ago (I switched to using dev mode and I didn't notice exact vault version that introduced the breaking change) then I tried to test with clean new install in C:\TEMP\vault\ and ...same error

**Comment by idimov-keeper** [comment]
I just checked previous version `vault 1.9.4` runs just fine with the  same setup and creates both:
vault.db 32KB
raft/raft.db 32 KB

```
C:\TEMP\vault>vault server -config=vault01.hcl
==> Vault server configuration:

             Api Address: http://127.0.0.1:8200
                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Go Version: go1.17.7
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: info
                   Mlock: supported: false, enabled: false
           Recovery Mode: false
                 Storage: raft (HA available)
                 Version: Vault v1.9.4
             Version Sha: fcbe948b2542a13ee8036ad07dd8ebf8554f56cb

==> Vault server started! Log data will stream in below:

2022-04-04T16:44:16.067-0500 [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
2022-04-04T16:44:16.117-0500 [INFO]  core: Initializing VersionTimestamps for core

```

**Comment by hsimon-hashicorp** [comment]
@idimov-keeper thank you! I'll get this looked at. I appreciate your responses! :)

**Comment by dfs-** [comment]
> just checked previous version `vault 1.9.4` runs just fine with the same setup

Thanks for the heads-up @idimov-keeper!

**Comment by hsimon-hashicorp** [comment]
@idimov-keeper We found the issue, and we'll be fixing it as soon as we can. Unfortunately, this means Windows users should wait until 1.10.1 to upgrade, and we'll see about setting a "Known Issues" note to that effect. Thank you *very* much for this detailed report!
