### ISSUE TITLE
SSH allowed_domain templating not documented

### ISSUE THREAD

**Issue by luke-clifton** [hashicorp/vault#14901]
For the SSH secrets backend, when creating a role for signing a host key, you can provide a template in the `allowed_domains` field when you set `allowed_users_template = true`.  The relevant code path is [here](https://github.com/hashicorp/vault/blob/dc086173df7ac318edf33af33f79b97f4c8e9555/builtin/logical/ssh/path_sign.go#L221)

This is useful, however, it's also [undocumented](https://www.vaultproject.io/api-docs/secret/ssh#allowed_domains), which makes me hesitant to use it.

**Comment by f4z3r** [comment]
@schultz-is just a heads-up that this issue can now be close as well I think.

**Comment by schultz-is** [comment]
Excellent, this functionality was documented by #16056. Thanks @f4z3r!
