### ISSUE TITLE
Support listing LDAP users and groups

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/vault#1491]
The `list` operation is not currently supported for user and group policies associated with the LDAP authentication backend:

```
$ vault list auth/ldap/groups
Error reading auth/ldap/groups/: Error making API request.

URL: GET http://127.0.0.1:8200/v1/auth/ldap/groups/?list=true
Code: 500. Errors:

* unsupported path
```

**Comment by shomron** [comment]
I believe this was addressed in https://github.com/hashicorp/vault/pull/1416

**Comment by mfischer-zd** [comment]
Awesome!  Closing.

**Comment by jefferai** [comment]
Too much stuff -- I completely forgot that this was implemented in `master` :-)  Thanks @shomron !
