### ISSUE TITLE
Vault CLI breaking strings containing dollar sign

### ISSUE THREAD

**Issue by theJaxon** [hashicorp/vault#14920]
**Describe the bug**
I'm using Vault v1.10.0 where I enabled KV secrets engine V2, whenever I add a secret containing dollar sign it breaks (If the dollar sign is at the beginning then the value for the secret will be empty)

**To Reproduce**
```bash
# Only puts sample and ignores the rest of the string
vault kv put kv/path username=sample$string 

# Still puts just sample
vault kv put kv/path username="sample$string"

# Works ok with single quotes
vault kv put kv/path username='sample$string' 

# Also works if dollar sign is escaped 
vault kv put kv/path username="sample\$string"
```

**Expected behavior**
I expected it to work either with single, double or no quotes at all regardless of the content of the value

**Environment:**
* Vault Server Version 1.10.0
* Vault CLI Version 1.10.0
* Server Operating System/Architecture: Alpine based [vault official Docker image](https://hub.docker.com/layers/vault/library/vault/1.10.0/images/sha256-3bb67d3fff584733849ebc9321370f836ac972e22740511f96ce00ffdc3479b0?context=explore)

Vault server configuration file(s):

```hcl
disable_mlock = true
ui            = true

# Storage Backend Configuration - Raft (Integrated Storage)
storage "raft" {}

listener "tcp" {
  address         = "[::]:8200"
  cluster_address = "[::]:8201"
  tls_client_ca_file = "path"
  tls_cert_file = "path"
  tls_key_file = "path"
}

service_registration "kubernetes" {}
```

**Comment by hghaf099** [comment]
@theJaxon Thanks for filing this issue. Just out of curiosity, are you running these commands in a shell terminal? If so, your shell is trying to replace "$string" with what you have defined "string" in your shell terminal. Here is an example:
```
$> string=DefinedInShell

$> vault kv put secret/foo username=sample$string
= Secret Path =
secret/data/foo

======= Metadata =======
Key                Value
---                -----
created_time       2022-04-06T13:48:11.05946Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            1

$> vault kv get secret/foo
= Secret Path =
secret/data/foo

======= Metadata =======
Key                Value
---                -----
created_time       2022-04-06T13:48:11.05946Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            5

====== Data ======
Key         Value
---         -----
username    sampleDefinedinShell
```

For the two examples that succeeded, it is again because shell knows when not to replace a value right after the "$"

I am going to close this ticket for now. Please reopen the ticket of open a new one if you encountered further issues.

**Comment by theJaxon** [comment]
@hghaf099 You're absolutely correct, sorry for the inconvenience and thank you for pointing that out.
