### ISSUE TITLE
Switch to using `time.Time` internally, everywhere

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#1495]
Internally we use a mix of times in seconds since epoch and `time.Time` objects. We should use all `time.Time` objects to ensure consistency if the Vault server moves between time zones.

Eventually we should standardize the API, too. Standard `time.Time` objects marshal as RFC3339 strings; we should be fine sending those over the wire.

**Comment by tanuck** [comment]
So is this replacing all the usages of `time.Unix()` and `func (t Time) Unix()` ?

**Comment by jefferai** [comment]
@tanuck it's not defined at the moment.

**Comment by jefferai** [comment]
Closed by #1607
