### ISSUE TITLE
As mentioned in #24155 , this may require a similar approach by creating a new resource type: aws_default_xray_sampling_rule

### ISSUE THREAD

**Issue by Lyndom41** [hashicorp/vault#14987]
As mentioned in #24155 , this may require a similar approach by creating a new resource type: aws_default_xray_sampling_rule

_Originally posted by @jon-armen in https://github.com/hashicorp/terraform-provider-aws/issues/23409#issuecomment-1093020486_

**Comment by hghaf099** [comment]
Thank you for submitting this issue. Would you please provide more context as what the issue is and how to reproduce it, or explain in more detailed the required feature?

**Comment by jon-armen** [comment]
@hghaf099 , I'm not sure what @Lyndom41 is requesting, or how this relates to my issue created for the provider in #23409

**Comment by hsimon-hashicorp** [comment]
Hi @Lyndom41 - can you please elaborate what your request is for us? If this issue was opened in error, that's okay too. Thanks in advance! :)
