### ISSUE TITLE
Plugin development docs are silent on concurrency / data race issues

### ISSUE THREAD

**Issue by maxb** [hashicorp/vault#14981]
As a plugin developer, writing a plugin using the Vault Go SDK, I want documentation e.g. https://www.vaultproject.io/docs/plugins/plugin-development to explain how the Vault Go SDK will use goroutines in my plugin process.

I suspect the answer is that Vault could deliver multiple concurrent requests over the GRPC interface, and the GRPC interface could execute my plugin's callbacks from multiple goroutines simultaneously - as any other architecture would be unlikely to have sufficient performance.

This matters to me, as my plugin needs to maintain cached information in memory between requests, and I need to know whether I need to diligently guard this with a mutex, to ensure correct behaviour.

(My plugin needs to log back in to Vault so it can reference other secret engines within Vault as part of its operations.)

**Comment by hsimon-hashicorp** [comment]
Thanks @maxb! We'll get this looked at as soon as we can. :)

**Comment by AnPucel** [comment]
Hi @maxb! Thank you for bringing this to our attention. You have the right idea and we're happy to update the documentation with a note about having your plugin prepared to handle multiple concurrent requests.

**Comment by AnPucel** [comment]
Hello! Thank you for bringing this issue to our attention. I was able to add a small note in the plugin developer docs that indicate that plugins should be prepared to handle multiple concurrent requests from Vault.
