### ISSUE TITLE
Support for offline mode with a remote server

### ISSUE THREAD

**Issue by varac** [hashicorp/vault#150]
It would be awesome to support syncing the vault data and have it locally cached for offline use, when using a remote server shared with a team.

**Comment by armon** [comment]
@varac This does not fit with the model of Vault as an online server based secret store. Clients can certainly read a set of secrets and cache them locally, but the system is not designed to do a full transfer of the store for offline access. That introduces a whole set of new issues and dramatically alters the architecture of the system.
