### ISSUE TITLE
TTL gets parsed on write, but still gets stored as data

### ISSUE THREAD

**Issue by bkrodgers** [hashicorp/vault#1505]
Perhaps it's debatable if this is a bug, but it seems like one to me.

If I write to vault as follows (168h = 7d):

`vault write /secret/mydb2 test=key ttl=168h`

And then read with `vault read /secret/mydb2`, I get:
```
Key           	Value
lease_duration	604800
test          	key
ttl           	168h
```

Or as json: 
```
{
	"lease_id": "",
	"lease_duration": 604800,
	"renewable": false,
	"data": {
		"test": "key",
		"ttl": "168h"
	},
	"warnings": null
}
```

It correctly parsed my TTL into 604800 seconds and returns it as expected as lease_duration.  But it still stores the string "168h" as a key called "ttl" in my data.  I would have expected Vault would discard the "ttl" field after parsing it and would not return it as a data element, since it really isn't.

Now, on the other hand, yes, this makes "ttl" a reserved word in data structures.  But since Vault will complain if you try to set anything on a key called "ttl" that it can't parse as a Go duration format, it effectively already is a reserved word.

Now the best solution is probably to change the write API so that it accepts a structure like this to separate any metadata from the actual data structure and prevent those metadata fields from being reserved words:
```
{
  ttl: "168h",
  data: {
   "test": "key"
  }
}
```
However, I understand that changing the API like this would be a breaking change.  Perhaps something to keep in mind for if/when you do a v2 API.  For now, it seems like it would make the most sense to discard the ttl from the data fields on write after parsing.

**Comment by jefferai** [comment]
Hi @bkrodgers,

ttl isn't anything special here; it's a normal field in your data. It just so happens that Vault will do something special with it, which is populate the lease duration field on read. But this is just a nicety...it is still a key/value you are setting with the write command, just like any other key/value you are setting.

**Comment by bkrodgers** [comment]
Hi @jefferai,

I disagree.  It's not a normal field in my data at all, because Vault will not let me put whatever I want in it.  I *must* put a string that corresponds to Go's duration format.  If I wanted to write "ttl" as "7d", for example, I can't.  Or if I wanted to write "ttl" as "June 8, 2016, 6:15PM", I can't do that either.  To my knowledge, there are no other character combinations that Vault reserves and applies special rules to, so it's not a normal data field.

Additionally, it's not really my "data" at all.  It's metadata.  Yes, when I write it I'm forced to add it to my data because Vault requires that, but it is not the secret data I'm trying to maintain in Vault.  It's data about that data, i.e., metadata.  Usually metadata is kept separate from actual data, as in the example I gave above where ttl would live alongside a "data" object.

Why do I care?  I noticed it in a unit test for a library I'm writing, where I wrote 3 "real" user data fields, with a TTL, and got 4 fields back on read.   Sure, I can just adjust that test so it doesn't expect the user data written to match the number of fields in the data Vault reads out.  I also am writing the library to be able to serialize to and from typed data objects, and those data objects don't have a TTL -- since they represent the user's data only.  I have a metadata object that wraps the data object for metadata. Granted, most JSON libraries probably can handle unexpected fields fine and just ignore them, though perhaps there are libraries out there that don't.

It also is redundant, since it's represented on reads as lease_duration, but obviously that little extra bit of data isn't a huge deal.  But i don't see any value in saving the field, when Vault has already parsed it  and stored and will return it separately as metadata on reads.

**Comment by jefferai** [comment]
> It's not a normal field in my data at all, because Vault will not let me put whatever I want in it. I must put a string that corresponds to Go's duration format.

That's a bug. I'll open an issue to fix it.

> Additionally, it's not really my "data" at all. It's metadata.

It's not. The generic backend does *not* issue leases and does *not* store metadata about the values you give it. The fact that it behaves this way by setting `lease_duration` is merely an extra, to allow writers to clue readers into whether a value has changed. Most users aren't even using that in favor of a last-write time embedded in the data, or simply reading the data whenever they want to use it.

> where I wrote 3 "real" user data fields, with a TTL, and got 4 fields back on read

You wrote 4 fields. The fact that you don't want to consider `ttl` to be a real data field doesn't change the fact that you gave the backend four key/value pairs.

> I also am writing the library to be able to serialize to and from typed data objects, and those data objects don't have a TTL -- since they represent the user's data only. I have a metadata object that wraps the data object for metadata.

So it seems you can either not write a TTL in, or strip it out when deserializing to your data object.

> Granted, most JSON libraries probably can handle unexpected fields fine and just ignore them, though perhaps there are libraries out there that don't.

JSON is schema-less; any values provided in input which are not used should be ignored. Some libraries can offer a schema-like mode, but this isn't a core JSON competency.
