### ISSUE TITLE
Website is missing favicon

### ISSUE THREAD

**Issue by JensRantil** [hashicorp/vault#1507]
I am running Google Chrome on MacOSX. Opening up https://www.vaultproject.io/docs/concepts/policies.html doesn't show any favicon.

**Comment by vishalnayak** [comment]
@anthonynguyen The problem still exists. I am able to see pages with no favicon, despite the fix above.

**Comment by anthonynguyen** [comment]
@vishalnayak do you mean at the link in the OP? I'm getting a favicon for that page now

**Comment by vishalnayak** [comment]
@anthonynguyen Not the one OP.
https://www.vaultproject.io/docs/index.html

**Comment by anthonynguyen** [comment]
@vishalnayak Try reloading with `Ctrl+R`

**Comment by vishalnayak** [comment]
@anthonynguyen Ah, the page was cached.
Thanks!

**Comment by Himura2la** [comment]
Vault 1.8.2 @ Firefox 93

The favicon loads form `https://vault.our.domain/ui/favicon-c02e22ca67f83a0fb6f2fd265074910a.png` and shows in tab, but the bookmark remains without icon. 

The Nomad and Consul icons are ok...

**Comment by hashishaw** [comment]
Hi @Himura2la, thanks for reporting this! We are working on a fix. Cheers!
