### ISSUE TITLE
Any CLI option for vault to pass the VAULT_TOKEN?

### ISSUE THREAD

**Issue by yxxhero** [hashicorp/vault#15109]
Any CLI option for vault to pass the VAULT_TOKEN?

**Comment by hennadii2012** [comment]
For what? You can use vault login in cli, so you need not pass token

**Comment by yxxhero** [comment]
in CI. I want to pass token by the CLI option. can you help me? Thanks very much.

**Comment by hennadii2012** [comment]
If you about ci var, then: vault login $VAULT_TOKEN

**Comment by hsimon-hashicorp** [comment]
We reserve github issues for bug reports and feature requests, which this doesn't appear to be. As such, I'm going to close this and suggest that you ask about this at [Vault](https://discuss.hashicorp.com/c/vault/30). Thanks!
