### ISSUE TITLE
Vault Write auth/jwt/role doesn't Report success or fail

### ISSUE THREAD

**Issue by mofakhar** [hashicorp/vault#15107]
**Is your feature request related to a problem? Please describe.**
When we execute the following command:

`vault write auth/jwt/role/my-role @my_config.json`

We suppose getting an output message if this success or failure. For now, it doesn't;t show anything compared to:

`vault write auth/ldap/.... @....json`

**Describe the solution you'd like**
We should get an output message for success or fail

**Describe alternatives you've considered**
For now, we have modified our GitLabCI to double check if the role was created or not by listing all the roles and grep for the new one's that we are adding.

**Explain any additional use-cases**
NA

**Additional context**
NA

**Comment by AnPucel** [comment]
Hello! Thank you for bringing this issue to our attention. I was able to reproduce the behavior you mentioned and fixed in the PR linked above.
