### ISSUE TITLE
Is 'tls_ca_cert_file' config exists in tcp listener？I can't find the relevant string in the source code！

### ISSUE THREAD

**Issue by q1979635364** [hashicorp/vault#15148]
**No Expected behavior**
Is 'tls_ca_cert_file' config exists in tcp listener？I can't find 'tls_ca_cert_file' string in the source code！But Vault works！

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```shell
$ vault status
Key                     Value
---                      -----
Seal Type               shamir
Initialized             true
Sealed                  false
Total Shares            1
Threshold               1
Version                 1.9.3
Storage Type            raft
Cluster Name            vault-cluster-072f9b4f
Cluster ID              69fbb001-2703-6e7b-110a-8cd8799c4e0a
HA Enabled              true
HA Cluster              https://vault-0.vault-internal:8201/
HA Mode                 active
Active Since            2022-04-21T10:38:58.784598108Z
Raft Committed Index    868
Raft Applied Index      868
```

* Vault CLI Version (retrieve with `vault version`):
```shell
$ vault version
Vault v1.9.3 (7dbdd57243a0d8d9d9e07cd01eb657369f8e1b8a)
```

Vault server configuration file(s):
copy from "https://learn.hashicorp.com/tutorials/vault/kubernetes-raft-deployment-guide?in=vault/kubernetes".
The most important question is, I can't find the 'tls_ca_cert_file' string in the source code and tcp listener configuration. by vault works！
Are there any errors in this document named "kubernetes-raft-deployment-guide"?

```hcl
ui = true
listener "tcp" {
  tls_disable = "false"
  address = "[::]:8200"
  cluster_address = "[::]:8201"
  tls_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
  tls_key_file = "/vault/userconfig/vault-server-tls/vault.key"
  tls_ca_cert_file = "/vault/userconfig/vault-server-tls/vault.ca"
  telemetry {
    unauthenticated_metrics_access = "true"
  }
}
telemetry {
  prometheus_retention_time = "30s"
  disable_hostname = true
}
storage "raft" {
  path = "/vault/data"
  retry_join {
    leader_api_addr = "https://vault-0.vault-internal:8200"
    leader_ca_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
  }
  retry_join {
    leader_api_addr = "https://vault-1.vault-internal:8200"
    leader_ca_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
  }
  retry_join {
    leader_api_addr = "https://vault-2.vault-internal:8200"
    leader_ca_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
  }
  retry_join {
    leader_api_addr = "https://vault-3.vault-internal:8200"
    leader_ca_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
  }
  retry_join {
    leader_api_addr = "https://vault-4.vault-internal:8200"
    leader_ca_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
  }
}
service_registration "kubernetes" {}
```

**Additional context**
I can`t find 'tls_ca_cert_file' in source code！but can find tls_client_ca_file in source code and tls listener configuration.
![image](https://user-images.githubusercontent.com/25050128/164954513-a7ef1ed6-4e99-4afc-ba24-779096a3c07f.png)
![image](https://user-images.githubusercontent.com/25050128/164954572-f3712b8d-c4f3-44cf-870d-ae3a15c0f62a.png)

**Comment by cipherboy** [comment]
@q1979635364 Thanks fort the report! I've filed an internal PR against the tutorials page to get it updated.

The parameter in the API docs is correct; `tls_ca_cert_file` isn't a parameter.

If you're attempting to add the CA of the leaf server cert served by Vault, append it to the end the file at the `tls_cert_file` config location. This file should be the full chain as mentioned in the docs.

Otherwise, if you're attempting to use client TLS cert auth, you'll need `tls_client_ca_file` as mentioned in the docs you linked.
