### ISSUE TITLE
[ui] Redirect logic doesn't work on already logged users

### ISSUE THREAD

**Issue by dacamposol** [hashicorp/vault#15177]
## Describe the bug

In our enterprise setup:

- We have a parent namespace (let's call it `root`) which has mounted the OIDC Auth Method under the `/oidc` path, there are plenty of entities with oidc aliases.
- We have a children namespace (let's call it `child`) which has a Group `oidc` with some policies to access diverse secrets. This Group has as members some entities from the `root` parent namespace with aliases for the OIDC Auth.

When I don't have an issued session, so I'm logged out, I can authenticate against the `root` namespace and then be redirected to a concrete secret within the `child` namespace. I'm using the following URL to get this behaviour:

https://vault.XXXXX/ui/vault/auth?redirect_to=%2Fvault%2Fsecrets%2Fkv%2Fshow%2Fsecret-service%2Fgithubpat%3Fnamespace%3D%252Fchild&with=oidc

This works perfect if I'm not logged in, I'm redirected to:

https://vault.XXXXX/ui/vault/secrets/kv/show/secret-service/githubpat?namespace=%2Fchild

The problem comes when I'm already logged in, since instead of being redirected to the secret, I'm just redirected to the parent namespace:

https://vault.XXXXX/ui/vault/secrets?redirect_to=%2Fvault%2Fsecrets%2Fdxp-system%2Fshow%2Fsecret-service%2Fgithubpat%3Fnamespace%3D%252Fchild

From what I see, the `redirect_to` query parameter is kept but it's being ignored.

### To Reproduce
Problem on the UI, the steps are indicated above.

## Expected behaviour
I would expect to be redirected to the secret in the specified namespace, as when I'm logged out, so the flow is consistent.

## Environment:
* Vault Server Version (retrieve with `vault status`): [Vault 1.8.6+ent](https://www.github.com/hashicorp/vault/blob/main/CHANGELOG.md#186)

### Addendum
**From Tue 26. Apr 13:25**

- I just set up a cluster in HVN to test the behaviour in **Vault 1.9.4+ent** with UserPass Auth Method, and it has the same issue.

![Kapture 2022-04-26 at 13 24 50](https://user-images.githubusercontent.com/16921751/165290240-fb3c8a99-cfc2-4bfd-96f9-3e6ddccfb80d.gif)

**From Thu 7. Jul 13:52**

- I just set up a cluster in HVN to test the behaviour in **Vault 1.10.3+ent** with UserPass Auth Method, and it has the same issue.

**Comment by andre68723** [comment]
@hsimon-hashicorp 

any update on this?  the issue is pretty annoying during daily use

Thanks!

**Comment by hashishaw** [comment]
Hi @andre68723, thanks for your patience while we look into this! I understand that this is an annoying experience. The bad news is, after some investigation we think this is actually an enhancement not a bug. The good news is, we're looking into how to best solve this issue. Stay tuned for updates!
