### ISSUE TITLE
How to debug wonky client header issues?

### ISSUE THREAD

**Issue by davedash** [hashicorp/vault#1519]
One developer I work with has been having issues talking to vault using the client.  We've upgraded his vault command and keep getting a bad request error.

I looked at his request headers he sent:

```
host:             vault.smmt.io
Connection:       close
User-Agent:       Go-http-client/1.1
X-Vault-Token:    ????
Accept-Encoding:  gzip
```

The token literally says `????` (but it might be unicode). When I checked requests I saw a legitimate looking `X-Vault-Token` value.  What would cause this?  I used `mitmproxy` and when I removed characters and resubmitted the response worked fine.

I couldn't tell exactly how the `vault auth` command works, or where/why it would submit anything for `X-Vault-Token`, so any direction here would be helpful.

**Comment by jefferai** [comment]
Hi @davedash ,

`vault auth` will get the token either from the `VAULT_TOKEN` env var or the file `~/.vault-token`. It'd be useful to know what's contained in each of those.

**Comment by davedash** [comment]
We temporarily fixed it with explicitly (un)setting the token `VAULT_TOKEN="" vault auth...` we'll see how that handles things.
