### ISSUE TITLE
SHA256SUMS Manifest file should be signed

### ISSUE THREAD

**Issue by justinburke** [hashicorp/vault#152]
The SHA256SUMS files available via the bintray download site [1] are ostensibly provided "to verify the binary is what we say it is" [2]. However, the manifest files aren't signed and thus don't support 
authentication of the file contents. HashiCorp should publish a PGP public key and sign the manifest files with that public key.

[1] https://dl.bintray.com/mitchellh/vault/
[2] https://www.vaultproject.io/docs/install/index.html

**Comment by sethvargo** [comment]
Hi @justinburke 

We just bintray for our hosted binaries, and they generate that file for us. I am not sure if they support the option to sign it, but we will investigate. Thanks!

**Comment by mitchellh** [comment]
Done, next release will be PGP signed with our official public key (linked from website over TLS)
