### ISSUE TITLE
mount-tune settings not persistent for LDAP backend

### ISSUE THREAD

**Issue by jeinwag** [hashicorp/vault#1521]
We're running vault (v0.5.2) in a HA setup and are using LDAP authentication. I'd like to reduce the TTL for tokens issued by the LDAP backend to 15 minutes:
```
vault mount-tune -default-lease-ttl=900s -max-lease-ttl=900s  auth/ldap
```
The above command works fine at first, but after restarting both vault instances, authenticating with the LDAP backend again creates tokens with a TTL of 30 days.

**Comment by jefferai** [comment]
Hi,

This is not supported for 0.5.2 but will be in 0.6.

**Comment by jeinwag** [comment]
Thanks for the quick heads up!
