### ISSUE TITLE
TTL of created tokens

### ISSUE THREAD

**Issue by counterliero** [hashicorp/vault#1526]
I am wondering if the following scenario really works as intended: when I have a valid token (a) which has a TTL of 2min and use this token to generate a token (b) with a TTL of 10min, both tokens will be revoked after 2min.

Since there is no warning when generating (b), you can easily run into the situation where both tokens can't be used anymore. Is this really the desired behaviour? What I would when doing this would be either 1) that (b) cannot be generated, 2) a TTL of 2min for (b) or 3) a warning that TTL(a) > TTL(b).

Currently, the behaviour doesn't feel right imho.

**Comment by vishalnayak** [comment]
Hi Matthias,

It is an intended behavior.

By default, when a token gets revoked, all its child tokens also gets
revoked.

After authenticating with token 'a', while the creation of token 'b', it
could be stated that token 'b', be an orphan token.
Then, revocation of token 'a' will not result in revocation of token 'b'.

Hope this helps!

Regards,
Vishal

On Tue, Jun 14, 2016 at 4:02 PM, Matthias <notifications@github.com> wrote:

> I am wondering if the following scenario really works as intended: when I
> have a valid token (a) which has a TTL of 2min and use this token to
> generate a token (b) with a TTL of 10min, both tokens will be revoked after
> 2min.
>
> Since there is no warning when generating (b), you can easily run into the
> situation where both tokens can't be used anymore. Is this really the
> desired behaviour? What I would when doing this would be either 1) that (b)
> cannot be generated, 2) a TTL of 2min for (b) or 3) a warning that TTL(a) >
> TTL(b).
>
> Currently, the behaviour doesn't feel right imho.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hashicorp/vault/issues/1526>, or mute the thread
> <https://github.com/notifications/unsubscribe/AC6YaGBzALTu4aj3MdiTlqmKeW2MHU0Fks5qLwjMgaJpZM4I1tCk>
> .
>



-- 
vn

**Comment by counterliero** [comment]
Hi Vishal,

stating that (b) is an orphan token was exaktly what was missing in my setup! Thanks a lot!

Best
Matthias
