### ISSUE TITLE
Vault registration with Consul has hard assumption for Advertise Address being Consul Agent Address

### ISSUE THREAD

**Issue by kenjones-cisco** [hashicorp/vault#1528]
When running Vault inside a Docker container, the current implementation will only work if consul (agent mode) is also installed in the same container or if you run only a single Vault instance.

The assumption at the advertiseAddr is the same as the Consul Agent creates that limitation. 

Once I scale Vault up then I get this:

```
vault_1             | ==> Vault server configuration:
vault_1             |
vault_1             |        Advertise Address: http://172.28.0.3:8200
vault_1             |                  Backend: consul (HA available)
vault_1             |               Listener 1: tcp (addr: "0.0.0.0:8200", tls: "disabled")
vault_1             |                Log Level: info
vault_1             |                    Mlock: supported: true, enabled: true
vault_1             |                  Version: Vault v0.6.0
vault_1             |
vault_1             | ==> Vault server started! Log data will stream in below:

vault_2             | ==> Vault server configuration:
vault_2             |
vault_2             |        Advertise Address: http://172.28.0.3:8200
vault_2             |                  Backend: consul (HA available)
vault_2             |               Listener 1: tcp (addr: "0.0.0.0:8200", tls: "disabled")
vault_2             |                Log Level: info
vault_2             |                    Mlock: supported: true, enabled: true
vault_2             |                  Version: Vault v0.6.0
vault_2             |
vault_2             | ==> Vault server started! Log data will stream in below:

vault_3             | ==> Vault server configuration:
vault_3             |
vault_3             |        Advertise Address: http://172.28.0.3:8200
vault_3             |                  Backend: consul (HA available)
vault_3             |               Listener 1: tcp (addr: "0.0.0.0:8200", tls: "disabled")
vault_3             |                Log Level: info
vault_3             |                    Mlock: supported: true, enabled: true
vault_3             |                  Version: Vault v0.6.0
vault_3             |
vault_3             | ==> Vault server started! Log data will stream in below:
```

Then the health of Vault in Consul will start the switch back and forth from healthy and critical depending on which instance health check was last processed.

Any reason to not leverage the same logic Consul itself leverages:

    The address that should be bound to for internal cluster communications. This is an IP address that should be reachable by all other nodes in the cluster. By default, this is "0.0.0.0", meaning Consul will use the first available private IPv4 address. If you specify "[::]", Consul will use the first available public IPv6 address. Consul uses both TCP and UDP and the same port for both. If you have any firewalls, be sure to allow both protocols.

**Comment by jefferai** [comment]
Consul is designed to allow nodes to connect from anywhere; Vault doesn't share that ideal. Setting advertise_addr in the Vault configuration should fix your problem; see https://www.vaultproject.io/docs/config/index.html#advertise_addr

**Comment by tristanmorgan** [comment]
@jefferai, I've hit the same problem, but using a container build from scratch I can not set the advertise_addr (now called [redirect_addr](https://www.vaultproject.io/docs/config/index.html#redirect_addr) in Vault 0.6.1) because it is unknown until after the container has started. I'd also like to use the same configuration across my Vault containers.

**Comment by jefferai** [comment]
@tristanmorgan I don't follow, what's the issue?

**Comment by tristanmorgan** [comment]
@jefferai When launching the Vault container, I cannot specify the IP address in the configuration because only after it has started, can I query Docker for it.

**Comment by jefferai** [comment]
That's not really a Vault issue though. You need to have your entrypoint set the env var or modify the Vault config based on the known value once the container is started.
