### ISSUE TITLE
Migrate from one backend to another

### ISSUE THREAD

**Issue by sebastiang** [hashicorp/vault#153]
Whether from a small file-based installation to a consul backend, or between two consul instances, is there a way to transfer all secrets from one backend to another?

**Comment by armon** [comment]
@sebastiang Migration is done by just copying all the data between the two backends. Between consul instances you could use consul-replicate. Moving from file <-> consul would require a script that just ensures that relative paths on disk on maintained in the Consul KV space.

Hope that helps!

**Comment by sebastiang** [comment]
I've just copied all files/folders from a file backend to an S3 backend, and when I start a vault instance pointing at the S3 bucket, I'm told 

    2015/06/18 02:46:28 [INFO] core: seal configuration missing, not initialized

and my only option is to initialize the vault, not unseal it. I've tried copying the files while the server is sealed, and while the server is unsealed. Am I looking at a bug in the S3 backend or my copying technique?

**Comment by dexterous** [comment]
How is this closed? There are so many permutations for migration. Are there instructions for each?

**Comment by jefferai** [comment]
Migration is not currently supported and not currently planned to be supported within Vault directly. Hence it is closed.

**Comment by jhmartin** [comment]
I came across https://github.com/nebtex/vault-migrator which purports to assist with this.

**Comment by ffledgling** [comment]
@jefferai Is migration across backends still unsupported officially?

**Comment by jefferai** [comment]
No, it's supported officially. See 'vault operator migrate'
