### ISSUE TITLE
Adjust APT instructions to use signed-by

### ISSUE THREAD

**Issue by joeyberkovitz** [hashicorp/vault#15300]
**Is your feature request related to a problem? Please describe.**
Download pages for all Hashicorp products, including Vault suggest using deprecated apt-key utility for installing a system-wide GPG key to trust the Hashicorp APT repo. See http://manpages.ubuntu.com/manpages/jammy/man8/apt-key.8.html for deprecation information

**Describe the solution you'd like**
Adjust download instructions to use the new `signed-by` option per (https://wiki.debian.org/DebianRepository/UseThirdParty). Example below:
```
curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor > /usr/share/keyrings/hashicorp-keyring.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/source.list.d/hashicorp.list
apt update && apt install vault
```

**Comment by hsimon-hashicorp** [comment]
Thank you for this, it's a good call-out. We have updated guidance on repo usage on our main page here: https://www.hashicorp.com/official-packaging-guide
However, our product-specific pages are out of date. We will look at getting those updated. Thanks again for bringing this to our attention!

**Comment by hsimon-hashicorp** [comment]
(Tagging @taoism4504 for further guidance)

**Comment by taoism4504** [comment]
Touched base with Kyle Penfound to gather the following information.

According to Kyle Penfound, the following page needs to be updated: https://learn.hashicorp.com/tutorials/vault/getting-started-install

Kyle mentioned that the platform-specific install instructions are built from a template that some (if not all) of the product install guides share.  Now, they have this new page which has updated instructions but as you can see, it's not from a product-specific standpoint.  https://www.hashicorp.com/official-packaging-guide

**The old instructions look like:**
`curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"`

**and the updated instructions should be:**
`sudo apt update && sudo apt install gpg
wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list`

**and then for dnf/yum:**
`sudo dnf install -y dnf-plugins-core
sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo`

**the updated instructions should be:**
`wget -O- https://rpm.releases.hashicorp.com/fedora/hashicorp.repo | sudo tee /etc/yum.repos.d/hashicorp.repo`

**Comment by yhyakuna** [comment]
The [Vault Install tutorial](https://learn.hashicorp.com/tutorials/vault/getting-started-install) has been updated as well, so I'm closing this issue. Thank you for reporting the issue.

**Comment by joeyberkovitz** [comment]
I'm a bit confused about the resolution to this issue. The instructions posted above by @taoism4504 look reasonable, but the instructions now present on both the Vault install page (https://www.vaultproject.io/downloads) and the linked tutorial (https://learn.hashicorp.com/tutorials/vault/getting-started-install) are currently different.

It looks like only the tutorial was updated, but I don't even understand the updates there since they don't seem to make much sense:

- `sudo apt update && sudo apt install gpg` - OK
- `wget -qO- https://apt.releases.hashicorp.com/gpg | sudo tee /etc/apt/trusted.gpg.d/hashicorp-archive-keyring.asc` - this seems old and just globally trusts the GPG key bypassing apt-key but doing pretty much the same thing
- `gpg -n -q --import --import-options import-show /usr/share/keyrings/hashicorp-archive-keyring.asc` - this just doesn't make any sense. At this point, there will be no file at `/usr/share/keyrings/hashicorp-archive-keyring.asc`, so this command should just fail
- `echo "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list` - this doesn't use the newer `signed-by` option, although theoretically would work with the globally trusted key from the second step
- `sudo apt update && sudo apt install vault` - OK

My proposed update - mostly the same as that posted by @taoism4504:
- `sudo apt update && sudo apt install gpg`
- `wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg >/dev/null` - this is my only change. Without the /dev/null redirect, the now binary GPG key will be echoed to the terminal, which will just create confusion or potentially put the terminal into a bad state
- `echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list`
- `sudo apt update && sudo apt install vault` - this wasn't included in the packaging guide, but is probably desired on the individual product pages

It would also probably make sense to make the same changes on all product pages, not just Vault

For reference, the signed-by option is listed on the oldest man pages hosted by both Canonical and Debian - Ubuntu 18.04 and Debian Stretch - https://manpages.ubuntu.com/manpages/bionic/en/man5/sources.list.5.html and https://manpages.debian.org/stretch/apt/sources.list.5.en.html

**Comment by yhyakuna** [comment]
The [tutorial](https://learn.hashicorp.com/tutorials/vault/getting-started-install?in=vault/getting-started) is updated, and it should now match the [packaging guide](https://www.hashicorp.com/official-packaging-guide). 

Note: The packaging guide will be updated with `>/dev/null` as well.
