### ISSUE TITLE
Permission Denied Error

### ISSUE THREAD

**Issue by hussam123-lab** [hashicorp/vault#15309]
When performing:
apk get git
I get the following error:
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
I tried performing sudo su however I got the following message:
/bin/sh: sudo: not found

**Comment by hussam123-lab** [comment]
Is there any way to get root access?

**Comment by hsimon-hashicorp** [comment]
Can you provide more details, please? Is this a Vault-specific request?

**Comment by maxb** [comment]
This question was also asked at https://discuss.hashicorp.com/t/permission-denied-error/39153 which might be a better forum for it.

**Comment by hsimon-hashicorp** [comment]
Since this issue lacks the necessary details, I'm going to go ahead and close it out now. Please feel free to open an issue for Vault with more specific information, or ask over on Discuss as linked by Max. Thanks!
