### ISSUE TITLE
OIDC - port 8250 not listening

### ISSUE THREAD

**Issue by sycured** [hashicorp/vault#15310]
**Describe the bug**
After doing the tutorial from Hashicorp, OIDC ADDR with port 8250 isn't listening on the node

**To Reproduce**
Doing your tutorial: https://learn.hashicorp.com/tutorials/vault/oidc-auth?in=vault/auth-methods

**Expected behavior**
Vault listening on port 8250 and be able to complete successfully the tutorial before putting in production

**Environment:**
* Vault Server Version: Vault v1.10.2
* Vault CLI Version: 1.10.2
* Server Operating System/Architecture: macOS Intel and Oracle Linux 8.5

**Comment by maxb** [comment]
> Vault listening on port 8250

Vault server does not use this port.

It is listened to temporarily by the Vault **CLI** , only whilst an instance of `vault login -method=oidc` is running.

**Comment by sycured** [comment]
Ah thank you

**Comment by HridoyRoy** [comment]
Hi @sycured , is this issue ok to close?
Thanks,
Roy
