### ISSUE TITLE
Allow to set permissions for Vault injected token

### ISSUE THREAD

**Issue by krzwiatrzyk** [hashicorp/vault#15313]
**Is your feature request related to a problem? Please describe.**
When main container tries to read injected token it get's `permission denied` error.

my pod's annotations:
```
        vault.hashicorp.com/agent-inject: "true"

        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/ca-cert: /run/secrets/kubernetes.io/serviceaccount/ca.crt
        vault.hashicorp.com/role: <REDACTED>
        vault.hashicorp.com/tls-skip-verify: "true"
```

```
[quarkusapp@<REDACTED> secrets]$ id
uid=1001(quarkusapp) gid=1001(quarkusapp) groups=1001(quarkusapp)
[quarkusapp@<REDACTED> secrets]$ ls -al
total 12
drwxrwxrwt. 2 root root   60 May  6 12:32 .
drwxr-xr-x. 3 root root 4096 May  6 12:32 ..
-rw-r-----. 1  100 1000   26 May  6 12:32 token
[quarkusapp@<REDACTED> secrets]$ cat token 
cat: token: Permission denied
```

**Describe the solution you'd like**
Allow to set permissions for the token, something like:
`vault.hashicorp.com/agent-inject-perms-token: "0644"`

**Describe alternatives you've considered**
None yet.

**Comment by n3ph** [comment]
Second that!

But I would like to see options for setting the owner as well, e.g. :
- `vault.hashicorp.com/agent-inject-token-uid: 1001`
- `vault.hashicorp.com/agent-inject-token-gid: 1001`

**Comment by n3ph** [comment]
Just learned about [`vault.hashicorp.com/agent-run-as-user`](https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-run-as-user) and [`vault.hashicorp.com/agent-run-as-group`](https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-run-as-group)

**Comment by VioletHynes** [comment]
Hi @krzwiatrzyk - do you think that [vault.hashicorp.com/agent-run-as-group](https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-run-as-group) would be a suitable option for you here? If the user reading the token is part of the same group as the agent, then this should just work.

**Comment by alplunge** [comment]
Depending on who is trying to read|access that token file, it can be controller over 
[vault.hashicorp.com/agent-run-as-user](https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-run-as-user) and [vault.hashicorp.com/agent-run-as-group](https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-run-as-group)

Just need to make sure that agent runs under the same user id as in application user who is trying to read|access that token file ✅

**Comment by VioletHynes** [comment]
Going to close this as we've not heard back on this in a while. As mentioned, `agent-run-as-group` should be a good solution for the problem here.
