### ISSUE TITLE
OIDC auth method with provider gsuite: fetch_groups only works if user_claim is "sub"

### ISSUE THREAD

**Issue by pieter-lautus** [hashicorp/vault#15330]
**Describe the bug**
I configured and OIDC auth provider to link Vault to our company's identities in Google G Suite. I wanted to have both a human-readable aliases (i.e. based on the users full name from G Suite), as well as a list of their G Suite groups pulled into Vault.

However, the fetch_groups feature breaks as soon as I change the role's user_claim from "sub" to something else like "name".

**To Reproduce**
First produce a working baseline of OIDC auth:
```
vault write auth/oidc/config -<<EOF
{
    "oidc_discovery_url": "https://accounts.google.com",
    "oidc_client_id": "xxxxx",
    "oidc_client_secret": "xxxxx",
    "default_role": "lautus-dot-net-gsuite-role",
    "provider_config": {
        "provider": "gsuite",
        "gsuite_service_account": "/etc/vault.d/lautus-vault-sso-2b2faa7c1414.json",
        "gsuite_admin_impersonate": "pieter@lautus.net"
    }
}
EOF
```

Then create a role similar to the following:
```
$ vault read auth/oidc/role/lautus-dot-net-gsuite-role 
Key                        Value
---                        -----
allowed_redirect_uris      [https://vault.lautus.net:8200/ui/vault/auth/oidc/oidc/callback http://localhost:8250/oidc/callback]
bound_audiences            <nil>
bound_claims               <nil>
bound_claims_type          string
bound_subject              n/a
claim_mappings             <nil>
clock_skew_leeway          0
expiration_leeway          0
groups_claim               n/a
max_age                    0
not_before_leeway          0
oidc_scopes                [openid profile]
policies                   [reader]
role_type                  oidc
token_bound_cidrs          []
token_explicit_max_ttl     0s
token_max_ttl              0s
token_no_default_policy    false
token_num_uses             0
token_period               0s
token_policies             [reader]
token_ttl                  72h
token_type                 default
ttl                        72h
user_claim                 name
verbose_oidc_logging       true
```

With the above configuration, OIDC login via the Vault Web UI works. If you click on the "person" icon top right, you see your alias has a human-readable name like "OIDC-Pieter Nagel" (in my case).

Now switch on group fetching:
```
vault write auth/oidc/config -<<EOF
{
    "oidc_discovery_url": "https://accounts.google.com",
    "oidc_client_id": "xxxxx",
    "oidc_client_secret": "xxxxx",
    "default_role": "lautus-dot-net-gsuite-role",
    "provider_config": {
        "provider": "gsuite",
        "gsuite_service_account": "/etc/vault.d/lautus-vault-sso-2b2faa7c1414.json",
        "gsuite_admin_impersonate": "pieter@lautus.net",
        "fetch_groups": true,
        "group_recurse": 5
    }
}
EOF
```

And on the role:

```
vault write auth/oidc/role/lautus-dot-net-gsuite-role groups_claim="groups"
```

Now sign out in the Web UI and then sign in again using OIDC. The following error message appears on the webpage:
```
failed to fetch groups: googleapi: Error 400: Invalid Input: memberKey, invalid
```

Now change the user claim:
```
vault write auth/oidc/role/lautus-dot-net-gsuite-role user_claim="sub"
```

Back in the Web UI, sign in again using OIDC. The signin is successful. However, if you click on the top right "person" icon, you see that your alias is an inscrutable number: "OIDC-107899439743055613325"

**Expected behavior**
I expected to be able to fetch groups and use a user_claim of my own choosing at the same time, without errors during logging in.

**Environment:**
* Vault Server Version: 1.10.2
* Vault CLI Version: ```Vault v1.10.2 (94325865b12662cb72efa3003d6aaa4f5ae57f3a)```
* Server Operating System/Architecture: ```Linux 5.13.0-1021-aws #23~20.04.2-Ubuntu SMP Thu Mar 31 11:36:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux```

Vault server configuration file(s):

```hcl
ui = true

# TODO: more frequent token re-issue
max_lease_ttl = "100d"
log_level = "debug"

storage "etcd" {
    address  = "http://localhost:2379"
    etcd_api = "v3"
    path = "/vault/"
    username = "vault-server"
    password = "xxxxx"
}

listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/opt/vault/tls/tls.crt"
  tls_key_file  = "/opt/vault/tls/tls.key"
}
```

**Comment by austingebauer** [comment]
Thanks for reporting this, @pieter-lautus. I agree that we should likely not be using the role's `user_claim` as the user key when searching for groups in G Suite. We can likely always use the `sub` claim to perform the search instead. This would allow you to set the `user_claim=name` and still fetch groups from G Suite.

**Comment by pieter-lautus** [comment]
Weirdly, if I use "email" as user claim (which requires adding email to the roles oidc_scopes), then fetching the groups works.

Since I actually prefer email over full name as alias, I'm sticking to that for now, leaving this comment here in case it helps anyone else.

**Comment by Itiho** [comment]
I'm try many configurations for resolve this problem. The configuration below works for me
```
vault write auth/oidc/config -<<EOF
{
    "oidc_discovery_url": "https://accounts.google.com",
    "oidc_client_id": "<oidc_client_id>",
    "oidc_client_secret": "<oidc_client_secret>",
    "default_role": "default_role",
    "provider_config": {
        "provider": "gsuite",
        "gsuite_service_account": "/vault/gsuite/gsuite-key.json",
        "gsuite_admin_impersonate": "admin@domain.com",
        "fetch_groups": true,
        "fetch_user_info": true,
        "groups_recurse_max_depth": 5
    }
}
EOF

vault write auth/oidc/role/default_role -<<EOF
{
    "bound_audiences": "<oidc_client_id>",
    "allowed_redirect_uris": "https://vault.domain.com/ui/vault/auth/oidc/oidc/callback",
    "oidc_scopes": [
        "email"
    ],
    "user_claim": "email",
    "groups_claim": "groups",
    "verbose_oidc_logging": "false",
    "claim_mappings": {
        "email": "email"
    }
}
EOF
```

![image](https://user-images.githubusercontent.com/7440821/172418641-3674286e-2baa-467b-9864-7aed37dba719.png)

**Comment by austingebauer** [comment]
I'm going to close this now since it has been resolved and the constraints on the `user_claim` are documented. Thanks, all!

**Comment by AlKapkone** [comment]
Hi, there

Unfortunately, I've got the google login issue.
I tried the same configuration as @Itiho but I've got an issue: `failed to fetch groups: googleapi: Error 404: Domain not found., notFound`
Any ideas ?

**Comment by ricardosilva86** [comment]
@AlKapkone did you find the solution for your issue?
