### ISSUE TITLE
Can not source the config file for injecting secrets into POD environment 

### ISSUE THREAD

**Issue by agrawalsmart7** [hashicorp/vault#15346]
Hi, this might not be a bug but I have no other option to choose.

I am trying to inject secrets inside POD environment variables from vault so I was able to get the config file from POD into /vault/secrets/.

But when I give `args: ["-c", 'source /vault/secrets/config && sleep infinity']` inside the deployment yaml file, it did not work. But when i try to run this command manually inside the POD i was able to see the secrets inside ENV variables.

Can anyone shed some light on what should I do?

**Comment by hsimon-hashicorp** [comment]
Hi there! Our [discuss](https://discuss.hashicorp.com/c/vault/30) forum may be a better venue for this question, as we use GitHub issues more for bug reports or enhancement requests. If your issue does turn out to be a bug, please feel free to re-open this issue, but for the meantime I'll go ahead and close it. Thanks!
