### ISSUE TITLE
Getting connection refused error while installing vault

### ISSUE THREAD

**Issue by ravikantsirsat** [hashicorp/vault#15367]
**Describe the bug**

I am running single node of Vault. Vault UI is visible and working fine but when I tried to run command 
ex - vault auth list, then I am getting below error
connect: connection refused

PFB :

![image](https://user-images.githubusercontent.com/83008626/167861665-11786518-91f0-41ec-aa82-73bb83c17b88.png)

**To Reproduce**
**Steps to reproduce the behavior:.**

1. Login to Vault CLI and type command vault auth list

**Expected behaviour :**

 
![image](https://user-images.githubusercontent.com/83008626/167861808-08d87469-6002-40dd-b693-ecef506fe5ef.png)

**Environment:**

•	Vault Server Version - Vault v1.10.2
•	Vault CLI Version - Vault v1.10.2
•	Server Operating System/Architecture: CentOS Linux release 7.2.1511 (Core)

**Vault server configuration file(s):**

{
   "listener":[
      {
         "tcp":{
            "address":"0.0.0.0:443",
            "cluster_address":"0.0.0.0:8201",
            "tls_disable":"true"
         }
      }
   ],
   "storage":{
      "mysql":{
         "username":"admin",
         "password":"**********",
         "database":"****vault",
         "address":"****** -1.rds.amazonaws.com",
         "ha_enabled":"false"
      }
   },
   "api_addr":"https://--IP Address--:443/",
   "max_lease_ttl":"2184h",
   "ui":"true",
   "disable_cache":"true"
}

**Additional context**

When we tried to change the address to "address":"127.0.0.1:8200" then error disappears but, Vault UI is not up. 

**Can some one help me here, to solve the error??**

**Comment by hsimon-hashicorp** [comment]
Your configuration appears to use 0.0.0.0:8201 for the cluster address, so port 8200 won't be open if I understand your config correctly. You may wish to ask over in our [Discuss forum](https://discuss.hashicorp.com/c/vault/30) as well, as GitHub issues are intended for bug reports and enhancement requests, while Discuss is intended more for question and answer.

**Comment by ravikantsirsat** [comment]
> Your configuration appears to use 0.0.0.0:8201 for the cluster address, so port 8200 won't be open if I understand your config correctly. You may wish to ask over in our [Discuss forum](https://discuss.hashicorp.com/c/vault/30) as well, as GitHub issues are intended for bug reports and enhancement requests, while Discuss is intended more for question and answer.

Thanks for comment
I have tried using 127.0.0.0:8201/8200 but again I am getting same error. After changing this I am unable to see UI.
I will paste error in Discuss forum

**Comment by hsimon-hashicorp** [comment]
Please see this documentation and let me know if it helps: https://learn.hashicorp.com/tutorials/vault/getting-started-ui?in=vault/getting-started

**Comment by hsimon-hashicorp** [comment]
Hi there - I'm going to go ahead and close this issue for now, and hope that you were able to get this working. If you continue to encounter issues, please feel free to re-open this. Thanks!
