### ISSUE TITLE
Vault allows for incorrectly configured paths in policies to be deployed successfully

### ISSUE THREAD

**Issue by DawidDlubek-TomTom** [hashicorp/vault#15368]
**Describe the bug**
We have recently discovered that some of our Vault users have been deploying incorrectly configured paths in policies, and Vault does not verify them.

Vault allows incorrectly configured paths in policies to be deployed through UI, CLI and Terraform. For example, with the below path:
```
path "path/" {
  policy = "write"
}
```
The following command is executed successfully:
```
vault policy write -namespace=test test-incorrect-policy - <<EOH
path "test/" {
  policy = "write" 
}
EOH

Success! Uploaded policy: test-incorrect-policy
```
The path contains incorrect capability and incorrect key. An error message **is** displayed if the capability is within square brackets, but there **is no** error if brackets are missing. 
**To Reproduce**
1. Login to Vault
2. Run the following command: 
```
vault policy write test-incorrect-policy - <<EOH
path "test/" {
  policy = "write" 
}
EOH
```

**Expected behavior**
I would expect vault to check for the incorrect key (**policy**) regardless of the value and display an error message.
**Environment:**
* Vault Server Version (retrieve with `vault status`): Tested in both Vault Enterprise 1.9.0+ent and 1.10.2+ent.
* Vault CLI Version (retrieve with `vault version`): Vault v1.10.2
* Server Operating System/Architecture: Hosted in AKS

**Comment by maxb** [comment]
Actually, Vault *does* perform this checking.

It's just you've discovered an undocumented historical syntax that is still supported for backwards compatibility.

```
  policy = "write"
```

is an alias for

```
  capabilities = ["create", "read", "update", "delete", "list"]
```

Try testing with other keys and values, and you will find the policy upload is blocked.

----

Also, a remark upon:

> vault policy write -namespace=test test-incorrect-policy - <<EOH
> path "test/" {

When you upload a policy to a namespace, all the paths in the policy are interpreted relative to the namespace, so practically speaking, this is permissioning the overall path `test/test/`

**Comment by maxb** [comment]
> Would that be an alias for: ` capabilities = ["read", "list"]` ?

Yes, you can find the full mapping in the Vault source code here:
https://github.com/hashicorp/vault/blob/74b1eec537394bbd9940e7e993c9c8e0ed8caf4f/vault/policy.go#L371-L385
with the referenced constants being at the top of that file.

> Are there any plans to deprecate this backwards compatibility?

I have not heard of any, but I'm a community member, not a HashiCorp employee.

My *guess* is that this is unlikely to become a development priority, as doing so would require a non-trivial amount of work, being a compatibility break which would have to be carefully managed.


> One more question. We are developing a little solution to review all the policies deployed by our users and check the capabilities and paths, and verify that users don't use sudo when it is not required. Vault allows a policy with paths similar to the below (where the opening **{** is below the path line) to be deployed:
> 
> [...]
> 
> but the parser we use (python-hcl2) highlights it as an invalid HCL syntax, so we have to do some regex checks and manipulations before we pass the policies to the parser. Is this an expected behavior? Does Vault allow some deviation from the official syntax, or is it parser specific configuration?

Vault policies are authored in HCL version 1, which has looser parsing rules in some cases than HCL version 2.

Actually, it even uses a special slightly forked version of the HCL library:
https://github.com/hashicorp/vault/blob/74b1eec537394bbd9940e7e993c9c8e0ed8caf4f/go.mod#L88

My *assumption* is that it has been left behind on HCL version 1 unlike other HashiCorp products, because upgrading would be incompatible with some customers' existing policies, and does not offer any significant benefits, for the use cases Vault currently requires of the configuration language.

**Comment by maxb** [comment]
A suggestion, regarding doing your own analysis of Vault policies: if you process the user input with `vault policy fmt`, it should transform it into a more canonical form, which you are likely to have better luck parsing with python-hcl2.

However, if you use Vault Enterprise, and the Control Groups feature, be aware the documented format used to configure them (https://www.vaultproject.io/docs/enterprise/control-groups) is not compliant with HCL 2 parsing rules.

**Comment by maxb** [comment]
You could also try https://pypi.org/project/pyhcl/ which, experimentally, seems to work OK with the subset of the language that appears in Vault policies.

**Comment by DawidDlubek-TomTom** [comment]
Hi @maxb,

> > Would that be an alias for: ` capabilities = ["read", "list"]` ?
> 
> Yes, you can find the full mapping in the Vault source code here:
> 
> https://github.com/hashicorp/vault/blob/74b1eec537394bbd9940e7e993c9c8e0ed8caf4f/vault/policy.go#L371-L385
> 
> with the referenced constants being at the top of that file.

Thanks, that will be very useful.


> A suggestion, regarding doing your own analysis of Vault policies: if you process the user input with `vault policy fmt`, it should transform it into a more canonical form, which you are likely to have better luck parsing with python-hcl2.
> 
> However, if you use Vault Enterprise, and the Control Groups feature, be aware the documented format used to configure them (https://www.vaultproject.io/docs/enterprise/control-groups) is not compliant with HCL 2 parsing rules.

> You could also try https://pypi.org/project/pyhcl/ which, experimentally, seems to work OK with the subset of the language that appears in Vault policies.


Thanks a lot for all the recommendations, I will test them to see what best suits our use case.

I am going to close this issue, since the initial problem has been resolved.
