### ISSUE TITLE
Policy for transit engine not being respected, permission denied

### ISSUE THREAD

**Issue by dkade** [hashicorp/vault#15370]
**Describe the bug**
I want different people to have access to different keys.
Followed the tutorial https://learn.hashicorp.com/tutorials/vault/eaas-transit. 
Enabled the transit engine, created a new key, create a new policy in order to give access to the key, but when trying to use the key I get a permission denied. 

Problem is with the policies, as per documentation the following policy should work:
```
path "transit/encrypt/*-sec" {
   capabilities = [ "update" ]
}

path "transit/decrypt/*-sec" {
   capabilities = [ "update" ]
}
```

But I always got permission denied. The only way for it to work is to use the following policy, but this defeats the purpose as user will have access to all keys:
`path "transit/*" {
   capabilities = [ "update" ]
}`

**To Reproduce**
This can be tested with docker vault: 
1. `docker run -d -p8200:8200 vault:1.9.0 server -dev -dev-root-token-id=toor`
2. `export VAULT_ADDR=http://127.0.0.1:8200`
3. `export VAULT_TOKEN=toor`
4. `vault secrets enable transit`
5. `vault write transit/keys/prodkey-sec type=rsa-4096`
6.
```
vault policy write security -<<EOF
path "transit/encrypt/*-sec" {
    capabilities = ["update"]
},
path "transit/decrypt/*-sec" {
    capabilities = ["update"]
}
EOF
```
8. `vault auth enable userpass`
9. `vault write auth/userpass/users/user1 \ 
    password=somepassword \
    policies=security`
10. Switch terminal and **login to vault with user1**
11. `vault write transit/encrypt/prodkey-sec plaintext=$(base64 <<< "my secret data")`
12. 
```
Error writing data to transit/encrypt/prodkey-sec: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/transit/encrypt/prodkey-sec
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

**Expected behavior**
This gives permission denied but it should return the encrypted data. If the policy is modified as explained in the beggining it works..

**Environment:**
* Vault Server Version (retrieve with `vault status`): 
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.9.0
Storage Type    inmem
Cluster Name    vault-cluster-4da6ab3e
Cluster ID      a8fc2129-5cdc-24b5-defb-9825ca5d7eca
```

* Vault CLI Version (retrieve with `vault version`): `Vault v1.10.0 ('7738ec5d0d6f5bf94a809ee0f6ff0142cfa525a6+CHANGES')`
* Server Operating System/Architecture: docker or any linux tested with vault 1.9.0

Vault server configuration file(s): Tested on default docker run, all steps above.

**Additional context**
This should be working as given by Hashicorp's tutorial

**Comment by maxb** [comment]
The tutorial is fine... The problem is that you are writing a Vault ACL policy with a `*` in the middle of the path, but this is not a feature supported by the policy language.

`*` is only valid as the last character in a policy path to indicate a prefix match, not as a generalized substring match.

**Comment by dkade** [comment]
@maxb I was going to swear that I tested with the full key name but I must have had a typo. So I retested again an it worked. 

It's good to know that `*` is only allowed as last characted. 

But for `+` this should work right? -> `transit/+/prodkey-sec`

Thank you for the support!

**Comment by dkade** [comment]
Yeah just tested, it works, answer stays here if people in the future come looking for the same issue.
