### ISSUE TITLE
gocql runs into timeouts. Possibility to extend timeouts?

### ISSUE THREAD

**Issue by mp911de** [hashicorp/vault#1538]
The Cassandra integration breaks regularly, I assume due to quite short timeouts. I'm getting quite often following response:

```
{"errors":["Error creating session: gocql: unable to create session: control: unable to connect to initial hosts: gocql: no response to connection startup within timeout"]}
```
The measured time to failure is 0.628 sec. Is it possible to raise the connection timeout to a more reasonable value?

I think it would also make sense to configure timeouts along the other configuration parameters.

See also: https://travis-ci.org/mp911de/spring-cloud-vault-config/builds/138684201

**Comment by jefferai** [comment]
Hi @mp911de ,

We're currently using `gocql`'s default, which I checked and is indeed 600ms. I think it certainly makes sense to make that configurable. We're pretty swamped for 0.6.1 but if you want to work up a PR I'd be happy to review it.

**Comment by mp911de** [comment]
Thanks for the fast response. I'll see whether I can come up with some reasonable code.
