### ISSUE TITLE
How to apply password restriction policy in Vault using CLI

### ISSUE THREAD

**Issue by ravikantsirsat** [hashicorp/vault#15431]
I want to apply below policy to restrict password for Cipher AD.

length = 14
rule "charset" {
  charset = "abcdefghijklmnopqrstuvwxyz"
  min-chars = 1
}
rule "charset" {
  charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  min-chars = 1
}
rule "charset" {
  charset = "0123456789"
  min-chars = 1
}
rule "charset" {
  charset = "#$_@"
  min-chars = 1
}

Please help me here for commands.

**Comment by hsimon-hashicorp** [comment]
Hello,

Please check out the following docs: https://www.vaultproject.io/docs/concepts/password-policies

If you have questions, please check out our [Discuss forums](https://discuss.hashicorp.com/c/vault/30)! We keep GitHub issues for reporting of bugs and enhancement requests, and the Discuss forum is more "Q&A"-style. Thanks!
