### ISSUE TITLE
Update Helm Chart to latest. As of now 1.9.2 is the latest version.

### ISSUE THREAD

**Issue by Preen** [hashicorp/vault#15433]
**Is your feature request related to a problem? Please describe.**
Unable to upgrade to 1.9.3+ in order to fix the renewal of kubernetes service account tokens.

**Describe the solution you'd like**
be able to update to a newer version

**Describe alternatives you've considered**be abl
Not using Helm.

**Comment by hsimon-hashicorp** [comment]
Hello,

A new version is coming soon, please see this PR! https://github.com/hashicorp/vault-helm/pull/727
