### ISSUE TITLE
add master changed telemetry event

### ISSUE THREAD

**Issue by skippy** [hashicorp/vault#1544]
when vault flips who the master is, it would be *super* helpful to log a telemetry event (perhaps something like `vault.core.new_leader`). 

The root issue is that I want to know immediately if Vault starts to flutter, as that is usually a strong indication that the vault cluster will, or already has become unavailable.  Now there are secondary indicators galore, such as if the HA backend (consul in my case) is fluttering.  But that isn't always a direct indicator, and neither is host network, CPU, or mem.  Having a direct metric that I can watch like a hawk would be fantastic.

**Comment by jefferai** [comment]
Good idea. I'll add this onto the 0.6.1 milestone but it's getting pretty long and may slip. If you want to put together a PR, take a look at the loop in `vault/core.go` in `runStandby()`. I think you'd want to put in a call above the comment saying "Monitor a loss of leadership".

**Comment by skippy** [comment]
hey @jefferai 
I'm sorry to be one of those people to throw an idea out and then not implement; swamped with other projects.  With that  said, I would love to submit a PR but it will probably be the end of next week at the earliest (I'm not a Go programmer, so there is a bit of extra overhead getting started that probably dwarfs adding this metric).  Thanks for showing the way.
