### ISSUE TITLE
Unable to unseal transit auto-unseal raft integrated Vault sever B after restoring the snapshot taken from another  Auto transit Unseal cluster A

### ISSUE THREAD

**Issue by alok183** [hashicorp/vault#15448]
**Describe the bug**
Unable to unseal raft integrated Vault after taking snapshot from Auto transit Unseal and restoring to Auto transit Unseal cluster.

**To Reproduce**
1. Take snapshot from vault transit auto unseal cluster A
2. Restore it in another  vault transit auto unseal cluster B
3. See error : After trying unsealing with the recovery keys.
* failed to decrypt encrypted stored keys: Error making API request.

**Expected behavior**
cluster B vault server should get unseal.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.10.0
* Vault CLI Version (retrieve with `vault version`): 1.10.0
* Server Operating System/Architecture: Linux

Vault server configuration file(s):

```hcl
**vault transit**
storage "file" {
  path    = "/vault/data"
  node_id = "node1"
}
listener "tcp" {
address = "0.0.0.0:8200"
tls_disable = true
}
disable_mlock = true

**vault server**
storage "raft" {
    path    = "/vault/data"
    node_id = "node2"
    retry_join {
        leader_api_addr   = "http://vserver1_vault:8200"
      }
    retry_join {
        leader_api_addr   = "http://vserver2_vault:8200"
      }
    retry_join {
    leader_api_addr   = "http://vserver3_vault:8200"
    }
  }
  
  listener "tcp" {
    address       = "0.0.0.0:8200"
    cluster_addr  = "0.0.0.0:8201"
    tls_disable   = 1
  }
  
  disable_mlock = true
  
  api_addr = "http://vserver2_vault:8200"
  cluster_addr = "http://vserver2_vault:8201"
  ui = true
  seal "transit" {
      address = "http://vtransit_transit:8200"
      disable_renewal = "false"
      key_name = "autounseal"
      mount_path = "transit/"
      tls_skip_verify = "true"
    }
  
```

**Additional context**
Is there any way I can deploy cluster B vault transit  using  Cluster A policy/autounseal token.

**steps : Vault transit token **
vault secrets enable transit
    vault write -f transit/keys/autounseal
    tee autounseal.hcl <<EOF
            path "transit/encrypt/autounseal" {
            capabilities = [ "update" ]
            }

            path "transit/decrypt/autounseal" {
            capabilities = [ "update" ]
            }
EOF
    vault policy write autounseal autounseal.hcl
    vault token create -policy="autounseal" -wrap-ttl=120 >/vault/data/policy-token.txt
    vault unwrap $(cat /vault/data/policy-token.txt | grep -w "wrapping_token:" | awk '{print $2}') >/vault/data/vault_token.txt

**Comment by alok183** [comment]
![image](https://user-images.githubusercontent.com/24774682/168667266-5782286e-6cff-4827-8e9b-76149570fca7.png)

**Comment by hsimon-hashicorp** [comment]
Hello,

You will need to unseal Vault on your second cluster by running `vault operator unseal <unseal key>`. Auto-unseal only works for a snapshot restore to the same cluster.

**Comment by alok183** [comment]
vault operator unseal <unseal key> doesn't work because I only have the recovery keys in main vault server.  But using the same for unseal throws error:

Error unsealing: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/unseal
Code: 500. Errors:

* failed to decrypt encrypted stored keys: Error making API request.

URL: PUT http://vtransit_transit:8200/v1/transit/decrypt/autounseal
Code: 400. Errors:

* cipher: message authentication failed

Initialization of vault server:
- Transit engine
vault operator init -key-shares 1 -key-threshold 1 >/vault/data/share-key.txt
- main vault sever (initial leader)
vault operator init -recovery-shares=5 -recovery-threshold=5 > /vault/data/recovery-key.txt

Config:
![image](https://user-images.githubusercontent.com/24774682/169227147-2133ee87-d243-40d6-9703-9ed6502dd6fd.png)

**Comment by hsimon-hashicorp** [comment]
"Recovery" keys tend to be often misunderstood, and they can't be used to unseal a Vault. There's an issue describing this here: #15490. We are looking at ways to make this more clear. Thanks for your feedback!
