### ISSUE TITLE
AWS: support list for aws/roles/

### ISSUE THREAD

**Issue by DjinnS** [hashicorp/vault#1545]
Hello,

It will be very useful to be able to read (list) the configured roles for AWS backend.

Example:

```
$ vault list aws/roles
Key
---
role1
role2
```

Without that, we need to keep tracking of configured roles, it's not very effective !

Thank you.

**Comment by fernando-villalba** [comment]
Just a quick note that the actual path that was implemented was this:

`vault list auth/aws/roles`
