### ISSUE TITLE
[Database Engine] PostgreSQL error "failed to inject secrets from vault: failed to read secret from path: postgresql/creds/database: context deadline exceeded"

### ISSUE THREAD

**Issue by ichasco-heytrade** [hashicorp/vault#15492]
I am having errores sometimes when `vault-webhook-secret` tries to get postgresql credentials.

```
failed to inject secrets from vault: failed to read secret from path: postgresql/creds/database: context deadline exceeded
```

If I restart vault, it starts working again.

Vault version: `v1.9.2`

**Comment by hsimon-hashicorp** [comment]
Hi! This can often be the result of network latency or performance issues either with your Vault instance(s) or your database instances. Are you able to do some network traces, or performance monitoring on these hosts?

**Comment by ichasco-heytrade** [comment]
We have 3 environments that are identical. Common vault and RDS per environment. I the other environments this is not happening only in one of them. We use AWS so the debug of this is a little bit messy. We will try. But the question is why when we restart vault it start working again. If it is network connection issue it would be always. isn't it? Or the TCP connection is always established?

Thanks for the answer :)

**Comment by hsimon-hashicorp** [comment]
In my experience, network issues are very rarely "always" :) But as always, your mileage may vary. If you continue to see issues that aren't easily explained by network or other performance indicators, please do let me know :)
