### ISSUE TITLE
denied_parameters only works for "create" policies, which is not reflected in documentation

### ISSUE THREAD

**Issue by cedricfeist** [hashicorp/vault#15508]
**Describe the bug**
[denied_parameters](https://www.vaultproject.io/docs/concepts/policies#denied_parameters) only works for 'create' policies which is not documented clearly. Multiple customers tried to use it to deny reading certain parameters which does not work and causes confusion/wastes time. 

**To Reproduce**
1. create policy: 
path "secret/foo" {
  capabilities = ["read"]
  denied_parameters = {
    "bar" = []
  }
}
2. Clients using above policy will still be able to read "bar" parameter.
3. Lack of documentation causes confusion. 

**Expected behavior**
denied_parameters should work on "read" policies, alternatively should be reflected in documentation as not working until changed

**Comment by hsimon-hashicorp** [comment]
@taoism4504 is this something we can address within the documentation?

**Comment by maxb** [comment]
The denied_parameters, allowed_parameters, required_parameters set of ACL modifiers all refer specifically to request parameters.

The word parameters itself, used in the context of computing, often carries an implication of input/request parameters, but apparently this implication is not universal, and needs to be documented.

There is already a (not very clear, actually, and I suspect not entirely correct) attempt to clarify exactly what they apply to in a note at the top of https://www.vaultproject.io/docs/concepts/policies#parameter-constraints - expanding this is probably the way to go here.

Request parameters are not unique to create operations - they definitely apply to update operations. I'm not sure how they interact with query-string parameters used in read/delete/list operations.

**Comment by ncabatoff** [comment]
Thanks for the suggestion @cedricfeist, and thanks for clarifying @maxb.   I've updated the docs, hopefully it should be clearer now.
