### ISSUE TITLE
Vault consistently generates expired certificates

### ISSUE THREAD

**Issue by drskalman** [hashicorp/vault#15570]
Vault has been initiated and generated root token on April 9, 2021. Now when it is asked to generate a client and server ceritficates with no expiray date on the tokens or given for the certs, it only generate certificates which has been expired on April 11, 2022.

**Describe the bug**
Root token has been initiated on April 9, 2021 with no expiration date given. I have generated fresh server and client tokens again with no expiration date given. When I run the python client to get new certificate using:

```
client = hvac.Client(url=vault_url, token=vault_token)
```

It gives me a private key with expired certificates:

```
$ openssl x509 -dates -noout -in new.crt 
notBefore=Apr 11 02:36:17 2021 GMT
notAfter=Apr 11 02:36:17 2022 GMT
```

**Expected behavior**
Vault should not generate expried certificates in anyway. If there is a reason that it is unable to generate a working cert then it should at least gives an error informing the user why they can't be given an unexpired cert.

**Environment:**
* Vault Server Version:  (retrieve with `vault status`):
```
# vault status --tls-skip-verify
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: false

#  vault version --tls-skip-verify
Vault v0.6.0

* Vault CLI Version (retrieve with `vault version`):
hvac                          0.11.2

* Server Operating System/Architecture:
Vault v0.6.0 docker image.

Vault server configuration file(s):

```
/vault/config # cat local.json
{"backend": {"file": {"path": "/vault/file"}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_cert_file": "/etc/letsencrypt/live/my-domain.com/fullchain.pem","tls_key_file":"/etc/letsencrypt/live/my-domain.com/privkey.pem"}},"default_lease_ttl": "7200h", "max_lease_ttl": "7200h"}
```

**Comment by maxb** [comment]
Vault 0.6.0 is 16 feature releases out of date and almost 6 years old. Your first priority should be to migrate to a somewhat recent version.

**Comment by hsimon-hashicorp** [comment]
> Vault 0.6.0 is 16 feature releases out of date and almost 6 years old. Your first priority should be to migrate to a somewhat recent version.

Thank you, @maxb! Good catch. Indeed, our support is for n-2 of recent versions of Vault - eg, Vault 1.8, 1.9, and 1.10 currently. Please upgrade and let me know if the problem persists.

**Comment by drskalman** [comment]
My lack of in-depth understanding of the application I was working with, misguided me to think it is the vault that issues the certificate to the client. 

Looking further into what was going on behind the scene, I noticed that vault is only serving the certificat  issued a year ago upon presenting with the appropriate secret token.

As such, behavior of the vault as secret storage and serving the expired certificate it has stored is but expected.
