### ISSUE TITLE
Please pull duo_api_golang vendor package from upstream - proxy improvements

### ISSUE THREAD

**Issue by bhinkle-work** [hashicorp/vault#1560]
The Duo MFA backend for Vault currently does not work in an environment where HTTP(S) proxies are required - this is due to a limitation in the Go net/http transport that the Duo API constructs to do certificate pinning.

I got this changed upstream in https://github.com/duosecurity/duo_api_golang/commit/60cf4266ffce4f3d8b332fb4af4558c8383dc970, but since Vault vendors all of these packages we'll need the Vault repo updated with this commit as well. Would someone be able to handle this?

This will be a huge win for all the Vault customers in enterprise environments where proxy usage is required and MFA is needed (I know it's blocking us right now, but I'm sure other companies will eventually have this problem).

Thanks!

**Comment by jefferai** [comment]
Sure...we'll be sure to update all vendored packages before 0.6.1!

**Comment by jefferai** [comment]
I'm going to close this as it's going to happen naturally :-)
