### ISSUE TITLE
root ability to lookup a token ID by display name or accessor

### ISSUE THREAD

**Issue by gandg** [hashicorp/vault#1565]
Perhaps this is on the list already, but the use case I have is.  A vault admin creates a new token based on a policy.  The token ID is revealed as part of the create and must be saved "somewhere" so as to later give the ID to a sys admin to place in a java keystore such that an App can start up, read the token ID and then use it to read its needed secrets from the vault.  Would be great if the vault admin could create tokens in one step, then later look them up (token-lookup is a big help) and actually see the original token ID.  Without this capability, the vault admin needs to manually store the token ID in a cubbyhole for later use - effectively storing it twice.  My thought is to allow the root user to lookup and see the original tokenID info altogether as part of the token-lookup output.  Maybe this could be implemented with a special -root flag.  I could be missing something here, or maybe this is being considered down the road.

**Comment by jefferai** [comment]
@gandg We're not going to add this for the same reason that admins can't list bare token IDs. It makes it very simple for an admin to spoof actions and make it look like they are the result of another user's actions. Sorry!

**Comment by gandg** [comment]
With proper logging this scenario can be mitigated, but not eliminated entirely.  Understood. Thank you for the consideration.
