### ISSUE TITLE
KV put Check-and-Set

### ISSUE THREAD

**Issue by XDjackieXD** [hashicorp/vault#15676]
**Describe the bug**
When setting a key with -cas=0 that was deleted previously, I would expect the write to succeed as the help page described it with "If set to 0 a write will only be allowed if the key doesn’t exist" (which it doesn't. It did exist in previous versions but not at the current version) but it fails with "check-and-set parameter did not match the current version".

**To Reproduce**
1. Run `vault kv put secret/test bla="foo"`
2. Run `vault kv delete secret/test`
3. Run `vault kv put -cas=0 secret/test bla="bar"`
3. See error

**Expected behavior**
As the key does not exist I would expect the write to succeed.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.7.0
* Vault CLI Version (retrieve with `vault version`): 1.10.2
* Server Operating System/Architecture: Archlinux x86_64

Vault server configuration file(s):

```hcl
storage "raft" {
	path = "/var/lib/vault/raft/"
	node_id = "raft_node_1"
}

listener "tcp" {
	address = "[::]:8200"
	cluster_address = "[::]:8201"

	tls_cert_file = "/var/lib/vault/vault.crt"
	tls_key_file = "/var/lib/vault/vault.key"
}

api_addr = "https://vault.blafoobar.org:8200"
cluster_addr = "https://vault.blafoobar.org:8201"

# We're using integrated storage where this is recommended
disable_mlock = true

plugin_directory = "/usr/lib/vault"
```

**Comment by XDjackieXD** [comment]
Thanks for the response!
The behaviour I'd expect from the "special" version 0 with cas is, that the key gets set when this key is currently not set, no matter if the key existed in the past or not (and this is also how I would interpret the help-entry for it).
Please change the help text if the current behaviour is intended to clarify that there also can't exist version history for a key even if the key does currently not exist for a cas=0 write to succeed.

**Comment by akshya96** [comment]
Thanks for the suggestion!
We have updated the documentation. We cannot allow write to a key when the key does not exist but has a version history as we need this information if we want to undo a delete for this version in the future.

**Comment by XDjackieXD** [comment]
Thank you very much for the clarification in the documentation!
