### ISSUE TITLE
Vault auth with method=cert says "missing client token"

### ISSUE THREAD

**Issue by siddharthist** [hashicorp/vault#1571]
I must be doing something wrong here:
```
[centos@lb0-control-01 ~]$ sudo vault auth --method=cert --client-key=/etc/pki/mantl/key --client-cert=/etc/pki/mantl/cert --ca-cert=/etc/pki/CA/ca.cert 
Error making API request.

URL: PUT https://lb0-control-03.node.consul:8200/v1/auth/cert/login
Code: 400. Errors:

* missing client token
```
This command is copied almost exactly from the documentation, under "via the cli": https://www.vaultproject.io/docs/auth/cert.html

This is Vault version 0.6.0. No environment variables are set.

**Comment by jefferai** [comment]
Hi @siddharthist ,

What is the output of `vault auth -methods`?

**Comment by siddharthist** [comment]
@jefferai I can't reproduce the issue I was having earlier today :four_leaf_clover: I'm back to the issue you were helping me out on the mailing list (https://groups.google.com/forum/#!searchin/vault-tool/langston/vault-tool/7t9jmIpdCEI/MP6B_zRXBAAJ) so I'll update that thread and close this. Thanks!

**Comment by jefferai** [comment]
@siddharthist So you upgraded to a recent version of Vault (say, 0.6) and still have that problem?

**Comment by siddharthist** [comment]
@jefferai Sorry, the setup has a lot of moving parts and I'm trying to figure out which issues arise where. I'll update you once I have a bit more info.
