### ISSUE TITLE
provide ETCD_ADDR for the etcd backend

### ISSUE THREAD

**Issue by xh3b4sd** [hashicorp/vault#1574]
Currently it is only possible to provide the etcd address for the etcd backend using a config file. I would like to run Vault inside of a container and inject the etcd address into it using dockers `-e` flag. Unfortunately Vault does not yet provide and environment variable for the etcd address. `ETCD_ADDR` is only used in the [etcd backend test file](https://github.com/hashicorp/vault/blob/4bb6b45aebd4f475a8b82b6e591c2c7fa6be984c/physical/etcd_test.go#L15). 

I wanted to ask how the injection of a dynamic etcd address is supposed to work right now. Maybe I am missing something. Maybe somebody can provide some feedback here.

Further I am happy to provide a pull request. The solution to solve this issue should be quite easy. I would simply add the following code between [line 91 and 92](https://github.com/hashicorp/vault/blob/4bb6b45aebd4f475a8b82b6e591c2c7fa6be984c/physical/etcd.go#L91). What do you think? 

```golang
machinesEnv := os.GetEnv("ETCD_ADDR")
if machinesEnv != "" {
  machines = machinesEnv
}
```

That way the value from the configuration file succeeds the default value and the environment value succeeds the configuration file value. 

For the pull request some documentation should be updated as well.

**Comment by jefferai** [comment]
A PR sounds great. Closing in favor of that!
