### ISSUE TITLE
Auto unseal suddenly no longer working after recovering k8s cluster from a bad state

### ISSUE THREAD

**Issue by patjones** [hashicorp/vault#15780]
**Describe the bug**
Some background, this vault deployment has existed for well over a year with auto unseal via kms working the entire time. We just recovered the k8s cluster this deployment lives on from a pretty bad state (Lots of workloads constantly getting rescheduled, lost master node and etcd member etc).

Now that our cluster is back to normal we've noticed a problem with our vault deployment. One of our nodes is failing readiness probes because it can't seem to unseal itself. 

```
$ k get pods -n vault
NAME                                    READY   STATUS    RESTARTS   AGE
vault-0                                 0/1     Running   0          83m
vault-1                                 1/1     Running   0          2d23h
vault-2                                 1/1     Running   0          6d14h
vault-agent-injector-7f5bc979b6-ckxzj   1/1     Running   0          2d20h
```
from kubectl describe on bad pod:
```
Events:
  Type     Reason                  Age                   From                     Message
  ----     ------                  ----                  ----                     -------
  Normal   Scheduled               96m                   default-scheduler        Successfully assigned vault/vault-0 to ip-10-15-244-199.us-west-2.compute.internal
  Normal   SuccessfulAttachVolume  96m                   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-0d5dc307-5f21-470e-8b60-0ee922b9843e"
  Normal   AddedInterface          96m                   multus                   Add eth0 [10.129.12.70/23] from openshift-sdn
  Normal   Pulled                  96m                   kubelet                  Container image "vault:1.6.2" already present on machine
  Normal   Created                 96m                   kubelet                  Created container vault
  Normal   Started                 96m                   kubelet                  Started container vault
  Warning  Unhealthy               91s (x1140 over 96m)  kubelet                  Readiness probe failed: Key                      Value
---                      -----
Recovery Seal Type       awskms
Initialized              false
Sealed                   true
Total Recovery Shares    0
Threshold                0
Unseal Progress          0/0
Unseal Nonce             n/a
Version                  1.6.2
Storage Type             raft
HA Enabled               true
```

from pod logs:
```
2022-06-03T14:50:40.141Z [WARN]  failed to unseal core: error="stored unseal keys are supported, but none were found"
2022-06-03T14:50:43.632Z [INFO]  core: security barrier not initialized
2022-06-03T14:50:43.632Z [INFO]  core.autoseal: seal configuration missing, but cannot check old path as core is sealed: seal_type=recovery
2022-06-03T14:50:45.141Z [INFO]  core: stored unseal keys supported, attempting fetch
```

**To Reproduce**
Unfortunately it's hard for me to speculate on how to reproduce this because we only saw this behavior after some major k8s cluster issues.

**Expected behavior**
I expect nodes to be auto unsealed on startup

**Environment:**
* Vault Server Version: 1.6.2
* Server Operating System/Architecture:
    - Openshift 4.8.21
    - vault-helm 0.9.1

Vault server configuration file(s):

```hcl
disable_mlock = true
ui = true

listener "tcp" {
  tls_disable = 1
  address = "[::]:8200"
  cluster_address = "[::]:8201"
}

seal "awskms" {
  region     = "us-west-2"
  kms_key_id = "f6227c1f-328d-45bb-815d-25be7ff2a95d"
}

storage "raft" {
  path = "/vault/data"
}

service_registration "kubernetes" {}
```
I appreciate any help looking into this.

**Comment by hsimon-hashicorp** [comment]
Hi there - with "Initialized: False" that suggests that you need to run `vault operator init`. Even when deployed with a helm chart, the Vault needs to be initialized which allows for auto-unseal subsequently. Additionally, double-check your awskms seal settings and make sure they're correct, because that will also throw a wrench into the auto-unseal works.
(As a note, 1.6.2 is an older version than we currently support. 1.10.3 was recently released, and for bug reports we support "n-2" versions, ie 1.9 and 1.8 in addition. However, that doesn't stop us from trying to provide "best-effort" help as we are able.) :)

**Comment by patjones** [comment]
Thanks @hsimon-hashicorp for the response even though this is out of support. So I successfully got our bad vault instance back into our cluster! Let me share what I did but note I do not claim to be a vault expert so proceed with caution, take a backup!

1. I first tried a `vault operator init` on our bad node (vault-0) but I now realize that I think this just split-brained the cluster and vault-0 considered itself it's own leader. (this was probably wrong and unnecessary).
2. I then removed `vault-0.vault-internal:8201` from the raft peers on our good leader.
3. I deleted the PVC for vault-0 and deleted the pod.
4. I execed into the new vault-0 container and ran `VAULT_ADDR=http://127.0.0.1:8200 vault operator raft join http://vault-2.vault-internal:8200` where vault-2 was our current leader.

**Comment by hsimon-hashicorp** [comment]
That sounds like a reasonable assumption! I'm glad you got everything back to a solid state again, and please do open any new issues for bug reports, enhancement requests, etc. There's also [the Discuss forum](https://discuss.hashicorp.com/c/vault/30) if you have more Q&A-style questions. :)
