### ISSUE TITLE
aws-ec2 quirks

### ISSUE THREAD

**Issue by skippy** [hashicorp/vault#1582]
hey folks,
first off, I'm super excited about this feature.  Thank you for the hard work.

I wanted to throw out some quirks I ran across; I'm happy to open a documentation PR if you think it is worth the hassle:

* it is unclear from the documentation that you don't need to import the aws pubic cert.  I ran into a cert issue, and the error was vague enough that I thought it was missing the cert.  Grep-ing the code showed me that was not the case, but a bit of clarity may be useful
* for the example on how to get a cert, you may want to change the example to: 
```shell
curl -X POST "http://active.vault.service.capsci:8200/v1/auth/aws-ec2/login" -d "{\"role\":\"proxy_role\",\"pkcs7\":\"$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 | tr -d '\n')\",\"nonce\":\"vault-client-nonce\"}"
```
the main issue is aws returns the pkcs7 with `\n` characters, which need to be stripped.
* I'm running vault within an alpline:3.4-based docker container.  even though I had run `apk --update add ca-certificates`, I was still receiving this error: 
```json
{"errors":["failed to verify instance ID: error fetching description for instance ID i-02e37baed9791c045: RequestError: send request failed\ncaused by: Post https://ec2.us-west-2.amazonaws.com/: x509: failed to load system roots and no roots provided\n"]}
```
My solution was to add `--volume /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt` to the docker run cmd.  Now, this is pretty specific, and is not an issue with Vault per se, but it may be worth noting that an updated ca-certificate is needed
* it isn't noted in the docs (though it is in the code!) that the instance requires IAM permissions to run `ec2:DescribeInstance`; I have very locked down instances and this was not allowed to be run.  

If this would be helpful to add to the docs, punt it my way!  Cheers

**Comment by skippy** [comment]
and I'm not sure that `-wrap-ttl` is working with this endpoint.  I've tried the curl and vault cli, but here is the vault cli output for clarity's sake:

cmd: `vault write -wrap-ttl='30' auth/aws-ec2/login role=$(curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/ | cut -c 1-) pkcs7=$(curl -s http://169.254.169.254/latest/d
ynamic/instance-identity/pkcs7 | tr -d '\n')`
```shell
$ vault write -wrap-ttl='30' auth/aws-ec2/login role=data_role pkcs7=${aws_pkcs7}
Key                        	Value
---                        	-----
token                      	42b27d2a-f2a7-9e6f-a8ef-4e4eae0ce669
token_accessor             	c68e46b8-2c00-8ef5-1dd4-16bef2a2a6f5
token_duration             	1800000
token_renewable            	true
token_policies             	[default]
token_meta_ami_id          	"ami-[REMOVED]"
token_meta_instance_id     	"i-[REMOVED]"
token_meta_region          	"us-west-2"
token_meta_role            	"data_role"
token_meta_role_tag_max_ttl	"0"
```

if I enter something invalid into -wrap-ttl, it does seem to throw the appropriate warning
```shell
$ vault write -wrap-ttl='junk' auth/aws-ec2/login role=data_role pkcs7=${aws_pkcs7}
Error writing data to auth/aws-ec2/login: Error making API request.

URL: PUT http://active.vault.service.capsci:8200/v1/auth/aws-ec2/login
Code: 400. Errors:

* error parsing X-Vault-Wrap-TTL header: strconv.ParseInt: parsing "junk": invalid syntax
```

**Comment by jefferai** [comment]
Hi @skippy,

Wrapping isn't currently supported for login endpoints. Not for any particular reason AFAIK other than it seeming a strange workflow to log in with your credentials (with identifying info recorded in audit logs) and pass the associated token to someone else.

**Comment by skippy** [comment]
thanks @jefferai.  That makes sense.  I added a minor PR (#1587) to note this... accept or reject as you see fit of course.

The `auth/aws-ec2` is interesting as it is really instance-specific while what I was doing before was process-specific (specifically using `auth/app-id`).  So I was passing the token created by a little `auth/aws-ec2` script into a separate process that doles out scoped tokens for specific docker process.  Moving the pieces around to not do this step is trivial, but from the docs I couldn't tell if this was supposed to have worked or not.

**Comment by jefferai** [comment]
I see. I may just look at adding it in for 0.6.1. :-)

**Comment by jefferai** [comment]
Hi @skippy ,

Getting back to your previous comments, if you're willing to clarify these issues in the documentation that would be fantastic. I suggest filing the CA problem as an issue with the alpine team, as it suggests that their package is just out of date. There will be an official Vault Docker image at some point so ideally it'll be fixed in an automatic sense by them updating their package.

**Comment by skippy** [comment]
thanks @jefferai ; PRs for the other documentation tweaks will be headed your way shortly!

**Comment by skippy** [comment]
closing as PRs are open for documentation tweaks.  thanks @jefferai !
