### ISSUE TITLE
Vault cannot parse intermediate, generated CA

### ISSUE THREAD

**Issue by siddharthist** [hashicorp/vault#1586]
I'm trying to use Vault's PKI backend to issue some new certificates. I've
 1. Uploaded my root CA PEM bundle into Vault
 2. Generated an intermediate CA
 3. Written some URLs
 4. Written a pki role

All of this happens in Ansible, but these are the equivalent commands: 
```bash
$ vault write pki/config/ca pem_bundle=@/tmp/ca-bundle.pem
$ vault write pki/intermediate/generate/internal common_name=test_common_name ttl=87600h
$ vault write pki/config/urls issuing_certificates=https://vault.service.consul:8200/v1/pki/ca crl_distribution_points=https://vault.service.consul:8200/v1/pki/crl
$ vault write pki/roles/cert-rotation allow_any_name=true max_ttl=8760h
```
You can find the full playbook [here](https://github.com/CiscoCloud/mantl/blob/feature/rotate-certs/playbooks/rotate-certs.yml). 

But then when I try to issue a new certificate from the PKI backend, I get a strange error message:
```bash
$ curl -1LsS -X POST \
       --cacert /etc/pki/CA/ca.cert \
       -H "X-Vault-Token: ${vault_token}" \
       -H "Content-Type: application/json" \
       -d '{"common_name":"test_server_common_name","alt_names":"...","ip_sans":"...","ttl":"8760h"}' \
       --cert /etc/pki/mantl/cert \
       --key /etc/pki/mantl/key \
       "https://vault.service.consul:8200/v1/pki/issue/cert-rotation"
{"errors":["1 error(s) occurred:\n\n* Error fetching CA certificate: stored CA information not able to be parsed"]}
```
I found issue #946, where @jefferai's commented:
> OK, so the only way I can reproduce it is if I:
>
>    Generate a root cert using the /root/generate path -- this creates a lease for the root cert
>    Use the /intermediate/generate endpoint to generate a CSR, which (as according to documentation) replaces the CA cert in the backend with the new generated private key
>    Never upload a signed cert
>    Attempt to unmount

I think what might be happening is that `/pki/intermediate/generate` _requires_ you to then use `/pki/intermediate/set-signed`. If this is the case, I have two suggestions (which we can split into separate issues):
 1. Note that in the documentation
 2. Create a new helper function `/pki/intermediate/generate-and-sign` that generates an intermediate CA that is also signed by the CA that's currently in that pki backend. 

Is my thinking correct?

Here's the cert of my self-signed root CA: [cacert.pem.zip](https://github.com/hashicorp/vault/files/346357/cacert.pem.zip)

I'm using Vault 0.6.

Thanks for your help!

**Comment by jefferai** [comment]
Each mount only supports a single CA, so when you generate the intermediate you're overwriting the first CA cert you uploaded (specifically the private key). To do what you want, you need to use separate mounts.

**Comment by siddharthist** [comment]
@jefferai So is the proper workflow the download the generated intermediate cert, sign it with the root CA, and re-upload it to vault at a separate mount?

**Comment by jefferai** [comment]
It's actually the generated intermediate CSR, but yep! This is the exact process described in the docs.

**Comment by siddharthist** [comment]
@jefferai Thanks for the help, sorry for the basic questions! :-)
