### ISSUE TITLE
Code: 500. Errors: * internal error

### ISSUE THREAD

**Issue by sksingh20** [hashicorp/vault#15932]
# systemctl status vault 

[ERROR] audit: backend failed to log request: backend=socket/ error="2 errors occurred:
011* dial tcp <<"ip address of syslog server">>:514: i/o timeout

core: failed to audit response: request_path=sys/metrics error="1 error occurred:
011* no audit backend succeeded in logging the response

pi@serlog: $ vault audit enable file file_path=/var/log/vault_audit.log
Error enabling audit device: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/audit/file
Code: 500. Errors:

* internal error
pi@serlog:

**Expected behavior**
If there is audit failure, clear error message should have given on what path it is failing

**Environment:**
Vault status show normal behaviour:
pi@serlog:/var/log $ 
pi@serlog:/var/log $ vault login
Token (will be hidden):
Error authenticating: error looking up token: Error making API request.

URL: GET http://127.0.0.1:8200/v1/auth/token/lookup-self
Code: 500. Errors:

* internal error
pi@serlog:/var/log $ vault status
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    5
Threshold                3
Version                  1.7.1
Storage Type             mysql
Cluster Name             vault-cluster-b827622c
Cluster ID               3bc07ca8-e1d3-5698-c380-cb7b99e9639e
HA Enabled               true
HA Cluster               https://192.168.2.212:8241
HA Mode                  active
Active Since             2022-06-10T17:00:42.159813541Z
pi@serlog:/var/log $

Vault server configuration file(s):

pi@serlog:/var/log $ cat /etc/vault/config.hcl
storage "mysql" {
  database = "vault"
  username = "*******"
  password = "***********"
  address = "192.168.2.212:3306"
  ha_enabled = "true"
  lock_table = "vault_lock"
  max_parallel = "5"
  max_idle_connections = "5"
  max_connection_lifetime = "80"
  plaintext_connection_allowed = "true"
}
listener "tcp" {
  address    = "127.0.0.1:8200"
  tls_disable = 1
}
listener "tcp" {
  address    = "192.168.2.212:8240"
  tls_disable = 1
}
telemetry {
  disable_hostname = true
}

seal "transit" {
  address = "http://192.168.2.215:9200"
  token   = "*************************"
  disable_renewal = "false"

  key_name = "autounseal"
  mount_path = "transit/"
  tls_skip_verify = "true"
}

api_addr = "http://192.168.2.212:8240"
ui = true

pi@serlog:/var/log $

**Additional context**
Completely stuckup and no operation happening.. production halted
This appears that audit failure causing all vault functions to fail... can't audit service disable by some method to resume business operation?

**Comment by raskchanky** [comment]
You can disable audit devices using `vault audit disable`, as documented here: https://www.vaultproject.io/docs/commands/audit/disable

**Comment by sksingh20** [comment]
Did not worked... same internal error.

pi@serlog:~ $ vault audit disable file/
Error disabling audit device: Error making API request.

URL: DELETE http://127.0.0.1:8200/v1/sys/audit/file
Code: 500. Errors:

* internal error
pi@serlog:~ $ vault audit disable socket/
Error disabling audit device: Error making API request.

URL: DELETE http://127.0.0.1:8200/v1/sys/audit/socket
Code: 500. Errors:

* internal error
pi@serlog:~ $

**Comment by maxb** [comment]
If you have existing audit methods configured, and they are all failing, you have to fix one of the existing audit methods to restore operation, before you will be able to make any changes to Vault, including to the audit configuration.

There is no "break-glass" operation to remove audit methods whilst audit is offline.

**Comment by sksingh20** [comment]
> If you have existing audit methods configured, and they are all failing, you have to fix one of the existing audit methods to restore operation, before you will be able to make any changes to Vault, including to the audit configuration.
> 
> There is no "break-glass" operation to remove audit methods whilst audit is offline.

Two things to clarify:
(1) Does this mean... vault will become irrecoverable and all vault data will be inaccessible if audit error persist...
(2) No details available on which audit method is actually configured and failing.... As error say a syslog target and sys/metrics...
How to check which target or end point of audit need to to be restored?

**Comment by maxb** [comment]
> (1) Does this mean... vault will become irrecoverable and all vault data will be inaccessible if audit error persist...

Yes



> (2) No details available on which audit method is actually configured and failing.... As error say a syslog target and sys/metrics...
> How to check which target or end point of audit need to to be restored?

This information is available in the Vault logs (not the audit log, the general informational/error logging written to stdout.

You already quoted it when you initially opened this issue:



> [ERROR] audit: backend failed to log request: backend=socket/ error="2 errors occurred:
> 011* dial tcp <<"ip address of syslog server">>:514: i/o timeout
