### ISSUE TITLE
[community edition] Vault Identity tokens - manual validation fails, namespaces?! 

### ISSUE THREAD

**Issue by n3ph** [hashicorp/vault#15988]
**Describe the bug**
When using Vault as an OIDC Identity Provider a new token contains a `namespace`:

```console
export VAULT_OIDC_TOKEN=$(vault read -field=token identity/oidc/token/k8s)
jq -R 'split(".") | .[1] | @base64d | fromjson' <<< $VAULT_OIDC_TOKEN
```
```json
{
  "aud": "k8s",
  "exp": 1655386749,
  "groups": [
    "admin"
  ],
  "iat": 1655300349,
  "iss": "https://{{FQDN}}/v1/identity/oidc",
  "namespace": "root",
  "nbf": 1655300349,
  "sub": "d1b9e4a4-20b5-33ab-8994-e2caad00b2e9"
}
```

When trying to validate the token with curl the endpoint returns an error:
```console
curl https://{{FQDN}}/v1/identity/oidc -H "Authorization: Bearer $VAULT_OIDC_TOKEN"
{"errors":["1 error occurred:\n\t* internal error\n\n"]}
```

Following error appears in the log stream:
```error
[ERROR] core: failed to lookup acl token: error="failed to look up namespace from the token: no namespace"
```

**To Reproduce**
Build OIDC Identity Provider:
```hcl
/*
  OIDC identity provider

  * environment specific FQDN used as issuer
  * will be checked on client side
*/

resource "vault_identity_oidc" "k8s" {
  issuer = format("https://%s", var.fqdn)
}


/*
  OIDC signing key

  * SHA256withECDSA
  * rotated every 24 hours
*/

resource "vault_identity_oidc_key" "k8s" {
  name             = "key"
  algorithm        = "ES256"
  rotation_period  = 24 * 3600
  verification_ttl = 24 * 3600
}


/*
  OIDC role

  * path: identity/oidc/token/k8s
  * adding attributes
    - nbf (not before)
    - group membership
*/

resource "vault_identity_oidc_role" "k8s" {
  name      = "k8s"
  client_id = "k8s"
  key       = vault_identity_oidc_key.k8s.name
  template  = <<EOF
{
  "nbf": {{time.now}},
  "groups": {{identity.entity.groups.names}}
}
EOF
}


/*
  Allow signing key to be used by our client_id of role "k8s"
*/

resource "vault_identity_oidc_key_allowed_client_id" "k8s" {
  key_name          = vault_identity_oidc_key.k8s.name
  allowed_client_id = vault_identity_oidc_role.k8s.client_id
}
```

**Expected behavior**
Validating a token should not fail because of not having the enterprise edition in use.

**Environment:**
```console
➜ vault status
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    1
Threshold                1
Version                  1.9.3
Storage Type             gcs
Cluster Name             vault-cluster-9b17b47d
Cluster ID               e2da2f9b-9206-3e33-b030-a4575a56d61e
HA Enabled               true
HA Cluster               https://ct-vault-0.ct-vault-internal:8201
HA Mode                  active
Active Since             2022-05-19T11:19:44.058593939Z

➜ vault version
Vault v1.10.1 ('e452e9b30a9c2c8adfa1611c26eb472090adc767+CHANGES')
```

**Comment by austingebauer** [comment]
Hi, @n3ph. It appears you're using Vault's [Identity Tokens](https://www.vaultproject.io/docs/secrets/identity/identity-token) feature instead of the [OIDC Identity Provider](https://www.vaultproject.io/docs/secrets/identity/oidc-provider) feature.

The token that results from the [token API](https://www.vaultproject.io/api-docs/secret/identity/tokens#generate-a-signed-id-token) is not a [Vault token](https://www.vaultproject.io/docs/concepts/tokens). It can't be used to access the Vault API as you've included in your curl example. If you can give me some general information about the problem you're trying to solve, I'd be happy to help.

Alternatively, this issue could be that you're surprised to see something related to namespace in the OSS version of Vault. Let me know if that's the case.

**Comment by n3ph** [comment]
Hi @austingebauer,

indeed I am surprised to see something related to namespaces in the OSS version of Vault. Regarding the Identity token, I was under the impression to validate the JWT token using the `v1/identity/oidc` endpoint. 

I am trying to use Vault's Identity Token for k8s authentication, which is currently not working correctly. That is the reason why I was trying to manually validate the identity token from Vault.

**Comment by n3ph** [comment]
Reading the documentation it seems I need to use the [introspect endpoint](https://www.vaultproject.io/api-docs/secret/identity/tokens#introspect-a-signed-id-token) to validate if an Identity Token is still valid, which in fact works as expected. 

I think I am mixing up OIDC Identity Provider and Identity Tokens here and could use some more insight how to properly configure EKS/GKE to authenticate user entities using Vault's OIDC Identity Provider.

**Comment by austingebauer** [comment]
@n3ph - Makes sense! You're correct that the introspect endpoint could be used to validate the identity token. You could also use the [public keys](https://www.vaultproject.io/api-docs/secret/identity/tokens#read-active-public-keys) to verify JWT signatures using a different mechanism (e.g., a JWT library). 

I would say that identity tokens are more for machine-to-machine workflows, and the OIDC identity provider is more for human-to-machine workflows (i.e., requires browser interaction by the end user). Do you think OIDC identity provider still makes the most sense for your problem?

You may also want to take a look at two alternative workflows provided by Vault:
- https://www.vaultproject.io/docs/auth/jwt/oidc_providers#kubernetes
- https://www.vaultproject.io/docs/auth/kubernetes

**Comment by austingebauer** [comment]
@Freyert - Got it, thanks! Let me know if you're able to successfully get it set up. Perhaps we could make a nice tutorial out of it.

Here is a list of references and videos showing Vault's OIDC identity provider feature:
- https://www.vaultproject.io/docs/secrets/identity/oidc-provider
  - Shows a simple configuration
- https://www.vaultproject.io/docs/concepts/oidc-provider
  - Provides a conceptual explanation
- https://learn.hashicorp.com/tutorials/vault/oidc-identity-provider?in=vault/new-release
  - Tutorial that uses Boundary as the OIDC client (I assume EKS would be the client in your case)
- https://brian-candler.medium.com/using-vault-as-an-openid-connect-identity-provider-ee0aaef2bba2
  - A nice article showing setup with various OIDC clients  
- https://youtu.be/beevSCphphc?t=1797
  - A video demo of the feature from community office hours

**Comment by Freyert** [comment]
@austingebauer I have to say I was not expecting such a great response. If we can figure it out I'm sure we'd both love to help you all make a tutorial on this.

Thank you so much for your help!

**Comment by austingebauer** [comment]
Ah, ya that does seem a bit odd that it wouldn't reach out for the public keys. Let me know if you find out what's going on 👍

**Comment by n3ph** [comment]
@austingebauer Thank you very much! We really appreciate all your help, especially listing all informational resources on Vault's OIDC Identity Provider. 

Just to note: For now I am looking forward to get OIDC Identity Tokens to work for EKS/GKE authentication. Our use case is about machine-to-machine workflows, but we will cover the user-to-machine workflows as well in the very near future. 

I've re-assured the validity of the OIDC Identity Tokens we get from Vault. And as @Freyert already mentioned, we are facing the odd situation where EKS seems not to call the JWK_URL to retrieve key information for verification purposes. So I assume there is something wrong with the OIDC provider configuration / integration in EKS. 

I've opened up a support case in AWS and hope to get things sorted out. 

That said, I would like to close this issue, as the original question about token validation is answered and we have gone far off-topic already. 😉 

Sorry for the noise, but thank you very much for all your input!

P.s.: Looking forward to collaborate on knowledge sharing and tutorials!
