### ISSUE TITLE
Permission denied challenges

### ISSUE THREAD

**Issue by mteichtahl** [hashicorp/vault#1602]
Hi All,

I have stood up a simple vault on OS X with an S3 backend.

my configuration is

disable_mlock = true

backend "s3" {
   bucket = "tXXXXXXXXXt"
   region = "ap-southeast-2"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}

though after I unseal the vault, I get the following

URL: PUT http://127.0.0.1:8200/v1/secret/password Code: 400. Errors: * permission denied

any guidance would be great !

**Comment by jefferai** [comment]
Hi @mteichtahl ,

If you're still having trouble,, please post on the mailing list https://groups.google.com/forum/#!forum/vault-tool -- thanks!
