### ISSUE TITLE
unseal failed to decrypt encrypted stored keys: cipher: message authentication failed

### ISSUE THREAD

**Issue by sjoel** [hashicorp/vault#16031]
**Describe the bug**
Hello team,

Issues unsealing the vault after upgrading the vault to 1.9.2 from 1.5.2 version

**To Reproduce**
1. Run `vault operator unseal`
2. Run `vault login....`
3. See error - failed to decrypt encrypted stored keys: cipher: message authentication failed

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.9.2
* Vault CLI Version (retrieve with `vault version`): v1.9.2
* Server Operating System/Architecture: HA vault and post upgrade to 1.9.2 only vault 0 came up and vault 2 was initialised with a new set of unseal keys and root token and it looks like the HA is broken now

**Additional context**

**Comment by raskchanky** [comment]
Hi @sjoel 

Can you post your vault config file as well as the exact list of commands you ran after Vault started up?

**Comment by maxb** [comment]
This was also posted to discuss.hashicorp.com and has received answers there: https://discuss.hashicorp.com/t/error-unsealing-error-making-api-request-failed-to-decrypt-encrypted-stored-keys/40863
