### ISSUE TITLE
"\c {{}database_name}}" doesn't work in revocation_statements  for PostgreSQL

### ISSUE THREAD

**Issue by rakibulhossain** [hashicorp/vault#16035]
Hello Vault,
Hope you are doing well. We have a scenario here and hope you'll resolve it or give us a solution.

***Switch database doesn't work in revocation_statements***

Let's say we have a database named `test` in the PostgreSQL server.
```
$ sudo -u postgres psql
[sudo] password for rakibul: 
psql (14.1 (Ubuntu 14.1-2.pgdg20.04+1))
Type "help" for help.

postgres=# create database test;
CREATE DATABASE
postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/postgres         +
           |          |          |             |             | postgres=CTc/postgres
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 test      | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
(4 rows)

postgres=# 
```
Now we want to create a role with all privileges on database `test`. So we create a role `my-role` using the following command:

```
$ vault write database/roles/my-role \
        db_name=postgres \
        creation_statements="CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}'; \
            GRANT all privileges On database test TO \"{{name}}\";" \
        revocation_statements="\c test \
    REVOKE All PRIVILEGES ON DATABASE test FROM \"{{name}}\"; \
    REASSIGN OWNED BY \"{{name}}\" TO POSTGRES; \
    DROP OWNED BY \"{{name}}\"; \
    DROP ROLE IF EXISTS \"{{name}}\";" \
        default_ttl="1h" \
        max_ttl="24h"
Success! Data written to: database/roles/my-role
```
as you can see our `creation_statements` creates a `role` with login `password` and `grant` all privileges on database `test`.
And in the `revocation_statements` we want to switch the database to `test` and clear everything owned by the role. and drop it.
So we successfully created the role and it has been assigned to the `test` database.

```
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |                       Access privileges                       
-----------+----------+----------+-------------+-------------+---------------------------------------------------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/postgres                                                 +
           |          |          |             |             | postgres=CTc/postgres
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres                                                  +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres                                                  +
           |          |          |             |             | postgres=CTc/postgres
 test      | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/postgres                                                 +
           |          |          |             |             | postgres=CTc/postgres                                        +
           |          |          |             |             | "v-root-my-role-eTqlpBWZG4K0dJlAGNKq-1655466994"=CTc/postgres
(4 rows)

(END)
```
Now we  try to login into `test` as the user and create a table `data`

```
 $ psql -U "v-root-my-role-eTqlpBWZG4K0dJlAGNKq-1655466994" test
psql (14.1 (Ubuntu 14.1-2.pgdg20.04+1))
Type "help" for help.

test=> create table data(a int);
CREATE TABLE
test=> \dt
                           List of relations
 Schema | Name | Type  |                     Owner                      
--------+------+-------+------------------------------------------------
 public | data | table | v-root-my-role-eTqlpBWZG4K0dJlAGNKq-1655466994
(1 row)

test=> 
```
as we have successfully created the table `data`, now we want to revoke the role which will apply the `revocation_statements` and wipe out everything owned by the role and drop it.

```
$ vault delete database/roles/my-role
Success! Data deleted (if it existed) at: database/roles/my-role
```
As we have successfully revoked the role from the vault, let's see what is the situation inside the PostgreSQL server

```
                                                      List of roles
                   Role name                    |                         Attributes                         | Member of 
------------------------------------------------+------------------------------------------------------------+-----------
 postgres                                       | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 rakib                                          |                                                            | {}
 v-root-my-role-eTqlpBWZG4K0dJlAGNKq-1655466994 | Password valid until 2022-06-17 18:56:39+06                | {}
```

alas! it didn't remove from the server. Because `\c test` didn't work for `revocation_statements` and it never switched and as it couldn't drop the things owned by the role inside the `test` database, so it couldn't drop the role also.

**Comment by raskchanky** [comment]
Hi @rakibulhossain 

I'm not an expert at database plugins but it looks like this is by design. The dynamic secrets functionality of Vault deals with users and passwords, which are typically independent of any given database. It looks to me from the code like the specific database is specified by the connection URL and a pool of connections is created from that, which is reused for subsequent requests. I doubt changing databases using the Postgres `\c` syntax is something that's supported, given the current design.

@hashicorp/vault-ecosystem Am I reading this correctly?

**Comment by rakibulhossain** [comment]
Hi @raskchanky 

Thanks for responding. `\c {{database_name}}` is not a query but  a command. So it may not work in revocation_statements.
But there is no other way to specify the database (I am not sure). It always login to the `postgres` database using the root `username` and `password` specified in the `secret-engine`.

**Comment by maxb** [comment]
From https://www.postgresql.org/docs/current/app-psql.html:

> Anything you enter in psql that begins with an unquoted backslash is a psql meta-command that is processed by psql itself.

Meaning that the backslash commands are unique to the `psql` command line client program and not useable elsewhere.

**Comment by rakibulhossain** [comment]
Hi @maxb,
Thanks for the reply. I know why it doesn't work. But my concern was about what if someone wants to switch `database` for cleanup before revoking the `role`, then what would he do? As now we have to do this cleanup manually from the `server` then revoke it from the `vault`. We can't do this from the vault, as it always login into the default `postgres` database. There is no option for switching.

**Comment by maxb** [comment]
> But my concern was about what if someone wants to switch `database` for cleanup before revoking the `role`, then what would he do?

Well, you can't do that, as no facility to change the current database of a connection seems to exist, as far as I can tell.

Whilst I'm not that familiar with PostgreSQL, most SQL databases let you reference databases other than the current default one in individual SQL statements, and I would not have expected PostgreSQL to be any different in this regard.

However it unfortunately seems that PostgreSQL's 'REASSIGN OWNED BY' appears to be a custom SQL extension that omits any way to specify the database to operate on... that's unfortunate.

I think in this case it would be necessary to open a bug with PostgreSQL asking them to fix 'REASSIGN OWNER BY' and indeed all other user/role management commands to support something like 'FOR DATABASE xxx' and indeed 'FOR ALL DATABASES'.

**Comment by rakibulhossain** [comment]
Okay, @maxb, thank you. It seems clear to me.
