### ISSUE TITLE
mysql user truncating

### ISSUE THREAD

**Issue by jippi** [hashicorp/vault#1605]
Hi

today when a token is created with a DisplayName the actual token DisplayName will be `token-${DisplayName}`

However, when the token are used for MySQL backend, the MySQL username created will be `token-${DisplayName}-${UUID}` - where ${DisplayName} are truncated to 10 chars - resulting in some hard-to-get usernames

```
vault token-create -display-name="frontend"
vault read mysql/creds/default
```

results in a mysql username `token--fro-3e984` which are hard to read and derive information on

I would love to be able to omit the `token-` part in the MySQL username, to allow more space for my own provided display_name` rather than `token-` which could be shortened to `t-` or allowed to be omitted entirely.

Alternatively, allow to provide a max length for usernames per mount, as MariaDB 5.x and above allow for up to 80 chars usernames ( https://mariadb.atlassian.net/browse/MDEV-4332 ) 

And Oracle MySQL support up to 32 characters since MySQL 5.7.8 ( http://dev.mysql.com/doc/refman/5.7/en/user-names.html )

Leaving 10 char as default limit seem sane, and allowing people to bump it depending on their MySQL version to allow for more readable usernames when supported.

I suggest something similar to

```
vault write mysql/config/connection \
    connection_url="root:root@tcp(192.168.33.10:3306)/"
    username_length=10
```

**Comment by jefferai** [comment]
That sounds totally reasonable. Don't suppose you'd be up for PRing it?

**Comment by jippi** [comment]
@jefferai i tired, but never written a single line of Go in my life, so kinda got stuck after copy-pasting code around a bit :) it will probably be shit what i would come up with

**Comment by jippi** [comment]
@jefferai https://github.com/hashicorp/vault/pull/1604 now seem to contain most of the code for it, minus the use of a different `DisplayName` property

**Comment by jefferai** [comment]
I believe this is closed by the now-merged 1604.

**Comment by jippi** [comment]
Yep, thanks @jefferai ! :)
