### ISSUE TITLE
Integrated certificate chain is needed in your cert files when you use curl to approach Vault over TLS

### ISSUE THREAD

**Issue by Tomato-** [hashicorp/vault#1609]
I use pki secret backend to build a CA to generate a certificate for my vault server to enable TLS, everything is ok when I issue certificate directly from the root, but i get error report as below when i issue certificate from intermediate CA (signed by another root CA from another pki backend)

```
 [root@kv111 /]#curl --cacert intermediate.pem https://vault.server/v1/auth/cert/login
 curl: (60) SSL certificate problem: self signed certificate in certificate chain
 More details here: https://curl.haxx.se/docs/sslcerts.html
```

It took me sometime to resolve this problem, so I want to share this with other people and i recommend the Vault team to adjust[ documentation ](https://www.vaultproject.io/docs/config/index.html)to specify this potential problem.

In the above command, my intermediate CA certificate file(intermediate.pem) do not contain the root CA certificate,  and my vault server certificate file configured in Vault server (vault-server.pem) assigned by intermediate CA concatenate the primary certificate and the intermediate CA certificate together, but do not contain root CA certificate too.

root CA certificate should be added at the end of both intermediate.pem and vault-server.pem to make curl work. In other words, _tls_cert_file_ option in configuration not only need to concatenate the primary certificate and the CA certificate together, but need to contain the integrated certificate chain, so does --cacert option in curl command.

**Comment by jefferai** [comment]
@Tomato- Whether or not concatenation is needed is dependent on whether or not you have installed the CA cert as a trusted system root. In fact, the recommendation from Qualsys and others is actually to *not* include the root CA in favor of ensuring that trusted CA certs have been installed into a trusted system location. Obviously both methods can work, but the recommended method is not to concatenate the full chain, in favor of using system roots.

**Comment by Tomato-** [comment]
ok, i got it, thank you jeff

There is no need to append root CA at the end of both intermediate CA and server certificate files, there are two ways to solve my problem

1. pass my root CA certificate file to --cacert option
2. append my root CA certificate to trusted system location, mine is /etc/pki/tls/certs/ca-bundle.crt 

All I want to point out is that we can not use intermediate CA but root CA passing to system to trust.
