### ISSUE TITLE
Vault server got restarted with unexpected fault address error

### ISSUE THREAD

**Issue by packageman** [hashicorp/vault#16104]
**Describe the bug**
Vault server got restarted with unexpected fault address error occurred accidentally.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
![image](https://user-images.githubusercontent.com/12949466/175000540-6e9cfc91-2609-46d6-87fe-f393a337c405.png)

* Server Operating System/Architecture:
![image](https://user-images.githubusercontent.com/12949466/175000751-a5c0ca3b-81ca-4cc7-9a40-5d07e8ba98da.png)

Vault server configuration file(s):

```hcl
extraconfig-from-values.hcl: |-
    disable_mlock = true
    ui = true

    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
    }

    storage "raft" {
      path = "/vault/data"
      retry_join {
        leader_api_addr = "http://vault-server-0.vault-server-internal:8200"
      }
      retry_join {
        leader_api_addr = "http://vault-server-1.vault-server-internal:8200"
      }
      retry_join {
        leader_api_addr = "http://vault-server-2.vault-server-internal:8200"
      }
    }

    service_registration "kubernetes" {}
```

**Additional context**
The error log is as follows:

```txt
unexpected fault address 0x7f4a99104000
fatal error: fault

goroutine 121 [running]:
runtime.sigpanic()
runtime.throw({0x4e2fcad, 0x203000})
[signal SIGBUS: bus error code=0x2 addr=0x7f4a99104000 pc=0x15d12d5]
/opt/hostedtoolcache/go/1.17.2/x64/src/runtime/signal_unix.go:732 +0x125 fp=0xc000e90c20 sp=0xc000e90bd0 pc=0x44bbe5
/opt/hostedtoolcache/go/1.17.2/x64/src/runtime/panic.go:1198 +0x71 fp=0xc000e90bd0 sp=0xc000e90ba0 pc=0x435871
/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:465 +0x55 fp=0xc000e90cd8 sp=0xc000e90c20 pc=0x15d12d5
 /home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:489 +0x73 fp=0xc000e90e80 sp=0xc000e90e28 pc=0x15d1213
go.etcd.io/bbolt.(*Tx).forEachPage(0xc0022fb500, 0xc0022fb518, 0x0, 0xc000e90de8)
 go.etcd.io/bbolt.(*Tx).checkBucket.func2({0x7f4a9906f0e0, 0xc000e90ef0, 0xc000e90ed0}, {0x15d1d51, 0x7f4a9906f000, 0x40ce54})
go.etcd.io/bbolt.(*Tx).forEachPage(0xc0022fb500, 0xc0022fb500, 0x1, 0xc000e90de8)
go.etcd.io/bbolt.(*Tx).forEachPage(0xc0022fb500, 0x0, 0x2, 0xc000e90de8)
 /home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:631 +0x107 fp=0xc000e90d58 sp=0xc000e90d18 pc=0x15d1da7
go.etcd.io/bbolt.(*Tx).checkBucket.func1(0x7f4a99104000, 0xc000e910b8)
/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:631 +0x107 fp=0xc000e90d98 sp=0xc000e90d58 pc=0x15d1da7
go.etcd.io/bbolt.(*Tx).checkBucket(0xc0022fb500, 0xc001796dc0, 0xc000e910b8, 0xc000e91088, 0xc00218b080)
/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:390 +0xa4 fp=0xc000e90ee0 sp=0xc000e90e80 pc=0x15c0924
/home/runner/go/pkg/mod/github.com/hashicorp/raft@v1.3.1/log_cache.go:54 +0x37 fp=0xc000e913d0 sp=0xc000e91378 pc=0x159fc37
 /home/runner/go/pkg/mod/github.com/hashicorp/raft@v1.3.1/raft.go:470 +0x46a fp=0xc000e91f70 sp=0xc000e91d58 pc=0x15a74ea
goroutine 1 [select, 221271 minutes]:
go.etcd.io/bbolt.(*Tx).checkBucket(0xc0022fb500, 0xc0022fb518, 0xc000e910b8, 0xc000e91088, 0xc00218b080)
github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc0005fe180, {0xc00006e0b0, 0x1, 0x1})
github.com/hashicorp/vault/command.Run(...)
/home/runner/go/pkg/mod/github.com/hashicorp/raft@v1.3.1/raft.go:1106 +0x476 fp=0xc000e91538 sp=0xc000e913d0 pc=0x15ad036
/opt/hostedtoolcache/go/1.17.2/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000e91fe8 sp=0xc000e91fe0 pc=0x4693e1
/home/runner/go/pkg/mod/github.com/hashicorp/raft-boltdb/v2@v2.0.0-20210421194847-a7e34179d62c/bolt_store.go:191 +0x23a fp=0xc000e91378 sp=0xc000e912d0 pc=0x15dcb9a
/home/runner/go/pkg/mod/github.com/hashicorp/raft@v1.3.1/state.go:144 +0x92
go.etcd.io/bbolt.(*Bucket).ForEach(0xc0022fb518, 0xc000e90f00)
github.com/hashicorp/vault/command.RunCustom({0xc00006e0a0, 0x2, 0x2}, 0xc0000001a0)
```

**Comment by raskchanky** [comment]
This looks similar to https://github.com/etcd-io/etcd/issues/13406 and it sounds like the root issue there was db corruption. It's possible that's the same issue you're experiencing. bbolt has a [CLI tool](https://github.com/etcd-io/bbolt/tree/master/cmd/bbolt) that you can compile and use to inspect your local vault.db file (Vault has to be stopped when you do this). One thing to try would be to compile `bbolt` and run the `check` and `buckets` commands against your vault.db file. This should tell us if it's corrupt or not.

**Comment by raskchanky** [comment]
Note that it would be in `raft.db` instead of `vault.db`. Probably a good idea to check both.

**Comment by packageman** [comment]
> Can you provide a little more detail on what happened to trigger this panic?

At present, there is no stable reproduction step. The vault server will exit abnormally about once a week. Since we are deploying vault server on k8s, it will automatically restart after the abnormal exit. At this time, after the manual unseal is executed, the vault server can work normally again. 

Currently, we are only use `v1/transit/decrypt`, `v1/transit/encrypt`, `v1/sys/storage/raft/snapshot`, `/auth/kubernetes/` APIs.

> One thing to try would be to compile bbolt and run the check and buckets commands against your vault.db file. This should tell us if it's corrupt or not.

I did a `bbolt check` and `bbolt buckets` on the vault.db file after the auto-restart and everything seems to be working fine. I am confused why this error occurs frequently, which has affected the stability of the system.

![image](https://user-images.githubusercontent.com/12949466/175914926-992595ad-d6aa-4d68-92b2-4340ad48ec00.png)

**Comment by raskchanky** [comment]
@packageman Can you try that same steps above on `raft.db`? I wonder if there's any difference there.

**Comment by hsimon-hashicorp** [comment]
Since we have not heard back on this issue, I'm going to go ahead and close it now. Please feel free to re-open with more information as needed. Thanks!
