### ISSUE TITLE
Getting the rules for the named policy

### ISSUE THREAD

**Issue by sergeyklay** [hashicorp/vault#1611]
Hello.

I'm working with `/sys/policy` endpoint.

Could you please explain why GET to the `/sys/policy/<name>` eg `/sys/policy/response-wrapping` returns **broken** JSON?

```
curl -X GET \
    http://127.0.0.1:8200/v1/sys/policy/response-wrapping \
    -H "Accept: application/json" \
    -H "X-Vault-Token: ea067d8f-8fdb-e799-bd46-ad7b25912cd1"

{"name":"response-wrapping","rules":"\npath \"cubbyhole/response\" {\n    capabilities = [\"create\", \"read\"]\n}\n"}
```

**Comment by sergeyklay** [comment]
Any idea how to convert `rules` from HCL to JSON?

**Comment by jefferai** [comment]
What's broken about that JSON?

**Comment by sergeyklay** [comment]
@jalateras In my opinion request with header like `Accept: application/json` (or any other approach by which I tell to the server the desired format) must return something like:
```json
{
    "name": "response-wrapping",
    "rules": {
        "path": "cubbyhole/response",
        "0": {
            "capabilities": {
                "create": "read"
            }
        }
    }
}
```

So all keys myst be in valid JSON format, not JSON with HCL mix.

**Comment by sergeyklay** [comment]
@jeffera Maybe this can be implemented using query args? For example:
* `GET  /sys/policy/response-wrapping?format=json`
* `GET  /sys/policy/response-wrapping.json`

**Comment by jefferai** [comment]
The server *is* returning valid JSON. It's not broken in the slightest.

**Comment by sergeyklay** [comment]
Ya, but value of `rules` is HCL, not JSON

**Comment by jefferai** [comment]
Actually, the value of `rules` is a JSON string -- the same exact string that was provided when creating or updating these policy. The fact that the string contains JSON-escaped HCL is irrelevant -- the actual response is valid JSON. Vault is providing the exact input you gave. If you want it to be JSON, supply your input policy as JSON -- but what comes out will still be a JSON escaped string that happens to contain serialized JSON.

**Comment by sergeyklay** [comment]
Thanks
