### ISSUE TITLE
Docker for Vault

### ISSUE THREAD

**Issue by gvenka008c** [hashicorp/vault#1612]
Does hashicorp has official docker image for vault?

Thanks,
Govind

**Comment by sergeyklay** [comment]
https://github.com/hashicorp/docker-vault

**Comment by sergeyklay** [comment]
https://github.com/docker/docker/issues/10310
https://github.com/hashicorp/vault/issues/165

**Comment by jefferai** [comment]
I think maybe you meant to link to https://github.com/docker-library/official-images/pull/1914 ?
