### ISSUE TITLE
Cannot write & in secrets

### ISSUE THREAD

**Issue by adamroddick** [hashicorp/vault#1615]
Hi All,

I'm not very active on Github so please pardon me if I'm posting this incorrectly in any way.

When typing an & into any key/value pair the command prompt see characters after the & as a new command and throws an error. Vault writes the characters before the ampersand into the key/value pair and drops the text after the & - see the screenshot below.

![vaultampersand](https://cloud.githubusercontent.com/assets/13641602/16830220/f2ddf16c-49e0-11e6-947b-57504b77e7f6.JPG)

This is just something I came across in testing. Looking at all my *real* apikeys and random generated passwords I can't see any that contain an & so maybe this is all 'known' already.

Thanks,

Adam

**Comment by jefferai** [comment]
Hi Adam,

You need to quote the value -- I don't know much about quoting semantics on
Windows, but I would guess that either " or ' would work -- try both! If
that still gives you trouble, maybe try escaping the ampersand with a
backslash (although being Windows this may require 1, 2, 4, or 8
backslashes...I always forget).

**Comment by adamroddick** [comment]
Thanks Jeff,

Rookie mistake sorry. Shows how often I work in cmd.

**Comment by tudorift** [comment]
as alternative you can use the UI to validate and to load the json
