### ISSUE TITLE
Add UUID to requests

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#1617]
We should add a UUID to each request, with the value enforced by the router.

One thing to figure out is whether we want to return that value to the user, or only display that in the audit logs.

**Comment by sergeyklay** [comment]
Do you mean request id?

**Comment by jefferai** [comment]
Yes

**Comment by vishalnayak** [comment]
The request ID (a UUID) should be attached to the request object and should be part of both request and response entries of audit logs.

Router should cache the value of ID before forwarding the request to the backends and then restore it after the request is served.

The request ID should be added to the response as well. However, it should not be displayed as part of response of the CLI commands.

**Comment by jefferai** [comment]
Also as part of this, we should analyze the existing code, and probably remove request logging by default, since the full request entry is also contained in the response. It should be toggle-able. Unsure yet if that should be in Vault config or audit mount config, but most likely it should be an audit mount property at enable time.
