### ISSUE TITLE
Vault splits PostgreSQL policies on literal semicolons, breaking block statements

### ISSUE THREAD

**Issue by erydo** [hashicorp/vault#1619]
The literal splitting on semicolons in the [SplitSQL](https://github.com/hashicorp/vault/blob/16766e272e4ede7966ce561bfb51708c3ddd7f58/builtin/logical/postgresql/util.go#L6) utility function prevents block statements in PostgreSQL role definitions.

The following role definition breaks, and Vault provides no mechanism to escape the semicolons for any kind of workaround:

```sql
DO $$
BEGIN
   IF NOT EXISTS (SELECT * FROM pg_catalog.pg_roles WHERE rolname='foo-role') THEN
      CREATE ROLE "foo-role";
      CREATE SCHEMA IF NOT EXISTS foo AUTHORIZATION "foo-role";
      ALTER ROLE "foo-role" SET search_path = foo;
      GRANT TEMPORARY ON DATABASE "postgres" TO "foo-role";
      GRANT ALL PRIVILEGES ON SCHEMA foo TO "foo-role";
      GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA foo TO "foo-role";
      GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA foo TO "foo-role";
      GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA foo TO "foo-role";
   END IF;
END
$$

CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';
GRANT "foo-role" TO "{{name}}";
ALTER ROLE "{{name}}" SET search_path = foo;
GRANT CONNECT ON DATABASE "postgres" TO "{{name}}";
```

Vault responds with an error:
```
Error testing query: pq: unterminated dollar-quoted string at or near "$$
BEGIN
   IF NOT EXISTS (SELECT * FROM pg_catalog.pg_roles WHERE rolname='foo-role') THEN
      CREATE ROLE "foo-role"\"
```
Because it simply takes reads up to each semicolon to send as an SQL statement.

The above example is for a "schema migrator" role for a particular service. I'm attempting to do roles this way because in order for a non-superuser to drop tables in PostgreSQL (for example, running a migration), that role/user must _own_ that table. Because roles created by Vault are temporary, there must exist a non-temporary role to own those tables, to which the vault-created role can be granted.

Unfortunately, PostgreSQL doesn't offer a facility like `CREATE ROLE IF NOT EXISTS` which would remove the need for block statements…but nonetheless it's surprising that literal SQL is intercepted this way by Vault.

We can create that static role definition outside of Vault but that somewhat defeats the idea of having the policies defined in Vault. (The Vault policies would just be `GRANT "foo-role" to "{{name}}"`)

**Comment by crazed** [comment]
Is there a workaround for this or we have to wait until the SplitSQL function is updated to accommodate? My use case is similar, except for providing access to the stat/replication information for a user. Example being:

```
CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';
ALTER USER "{{name}}" SET SEARCH_PATH TO sre,pg_catalog;

-- Allow the newly created user to use passwords.
GRANT passwordauth TO "{{name}}";
-- In order to gain access to useful information as a non-superuser, we have to create some functions
CREATE SCHEMA IF NOT EXISTS sre;
CREATE OR REPLACE FUNCTION sre.f_select_pg_stat_activity()
RETURNS setof pg_catalog.pg_stat_activity
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT * from pg_catalog.pg_stat_activity;
$$;

CREATE OR REPLACE FUNCTION sre.f_select_pg_stat_replication()
RETURNS setof pg_catalog.pg_stat_replication
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT * from pg_catalog.pg_stat_replication;
$$;

CREATE OR REPLACE VIEW sre.pg_stat_replication
AS
    SELECT * FROM sre.f_select_pg_stat_replication();

CREATE OR REPLACE VIEW sre.pg_stat_activity
AS
    SELECT * FROM sre.f_select_pg_stat_activity();

GRANT USAGE ON SCHEMA sre TO "{{user}}";
GRANT SELECT ON ALL TABLES IN SCHEMA sre TO "{{user}}";

```

**Comment by jefferai** [comment]
Are either of you willing to do some testing today? It will require building a branch of Vault.

**Comment by jefferai** [comment]
There's a branch `issue-1619`. Testing would be appreciated as so far only regression testing has been performed.

This lets you pass in the SQL string as a JSON document. See the [test cases](https://github.com/hashicorp/vault/pull/1686/files#diff-6d2519a9af54eea06c95ee8e545c85e8R183) for an example of how this has been tested -- simply pass in a valid marshaled JSON list as the `sql` parameter. This list can be base64-encoded if that makes escaping and such easier.

**Comment by jefferai** [comment]
I've done some testing with the value from the original post in the postgres-backend tests and it works fine, so I'm going to merge that. However, testing in your own setups would be useful! If building is a problem, it'll be in 0.6.1-rc2.

**Comment by crazed** [comment]
Thanks! Building not a problem, but probably won't get around to updating my cluster for another week. Will let you know if anything goes wrong.

**Comment by ballad89** [comment]
Hey guys, I am guessing this feature has been released .... any documentation/example how this would be used in a `vault write postgresql/roles/test sql=...` which uses block statements ?

**Comment by jefferai** [comment]
Hi @ballad89 -- see https://www.vaultproject.io/api/secret/databases/postgresql.html at the bottom, there is some info on how it can be formatted. 

@briankassouf is there a reasonable place to surface that info above the individual plugins' docs?

**Comment by ballad89** [comment]
Thanks @jefferai, I was finally able to get a working example
```json
{"sql": "[\"DO $$ BEGIN IF NOT EXISTS (SELECT * FROM pg_catalog.pg_roles WHERE rolname='foo-bar') THEN CREATE ROLE foo-bar WITH NOLOGIN; GRANT ALL PRIVILEGES ON SCHEMA public TO foo-bar; GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO foo-bar; GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO foo-bar; GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO foo-bar; ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO foo-bar; ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO foo-bar; ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO foo-bar; END IF;END $$\", \"CREATE ROLE \\\"{{name}}\\\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}' IN ROLE foo-bar\"]", "revocation_sql": "DROP ROLE IF EXISTS \"{{name}}\""}
```
