### ISSUE TITLE
Enhancement request: user info on mount points

### ISSUE THREAD

**Issue by eyal-lupu** [hashicorp/vault#1621]
I have an idea/request for an enhancement. 

Maybe the easiest would be to demonstrate it with an example – using the PKI backend I manage multiple intermediate CAs in different mount points. Those mount points should correspond to a given configuration – each has its own attribute (configuration could be the subject, TTL, crl, etc.). I would like to create a monitoring system to check if the latest configuration was applied to the mount point (so I could alert if this is not the case).

My configuration is versioned so if I could store an arbitrary ‘user value’ (e.g. config_version=”3”) on the mount point it could be easy to compare that with the given configuration. Obviously I can work around that but having such support would make life easier. 

I guess there are other scenarios in which users would find that helpful, and for sure – if added – this is correct to other providers (none PKI) as well.

Any thoughts on that?

**Comment by jefferai** [comment]
It's an interesting concept, although I'm not sure currently how this would work. In the interim, one suggestion would be to do what we do internally at HC -- codify your Vault configuration in a script and apply it regularly. That way we can do PRs against changes to the Vault configuration, and ensure that it is applied once it is merged.

**Comment by eyal-lupu** [comment]
I do exactly that : I apply the configuration regularly, the thing is that I want to if  the configuration was applied from another process. In that process I want to find an 'evidence' that the configuration was applied. 

What I did for now is that on configuration change I also change a bit the CRL location, so my configuration looks something like :
```
subject: cn=me, l=somewhere 
key:
  algo: rsa
  size: 2048
...
...
version: 1
crlDistributionPoint: 'http://somewhere/my-crl-{version}.crl'
```

When applying the configuration I replace {version} with the version value - this can than be queried out of the backend and compared with the configuration by the monitor. A kind of a tag but a 'forced' one

**Comment by eyal-lupu** [comment]
Closed by mistake ...

**Comment by jefferai** [comment]
We don't plan to add this at the moment so I'm going to close this. You could mount-tune the description field to carry this kind of information if you want though!
