### ISSUE TITLE
`vault kv get` no longer works with leading slash in path

### ISSUE THREAD

**Issue by NSenaud** [hashicorp/vault#16238]
**Environment:**

* Vault Version: `1.11.0`
* Operating System/Architecture: `x86_64 GNU/Linux`

**Expected Behavior:**

`vault kv get /secret/my/secret/key` should behave like `vault kv get secret/my/secret/key`, just like `vault kv list /secret/my/secret/`.

**Actual Behavior:**

`vault kv get /secret/my/secret/key` returns an error `403`, while `vault kv get secret/my/secret/key` returns the secret.

**Steps to Reproduce:**

Call `vault kv get` with and without leading slash in the path.

**Important Factoids:**

This bug seems to be linked to #15188, which remove completely the call to [sanitizePath function](https://github.com/hashicorp/vault/blob/dae8a00f0c1a4fd3fded1f24a16c8bdc5cddb4e8/command/base_helpers.go#L37) to [avoid calling `TrimSpace`](https://github.com/hashicorp/vault/blob/dae8a00f0c1a4fd3fded1f24a16c8bdc5cddb4e8/command/base_helpers.go#L56) in the `ensureNoLeadingSlash` and `ensureNoTrailingSlash` functions.

**References:**

#15188

Edit: add reference to `ensureNoLeadingSlash`.

**Comment by ccapurso** [comment]
Hi, @NSenaud. Thank you for bringing this to our attention! A fix has been provided in https://github.com/hashicorp/vault/pull/16443. We will backport the change and it will be made available in the next 1.11.x minor release, 1.11.2.
