### ISSUE TITLE
Consul Connect fails to renew leaf certificates after 1.10 update

### ISSUE THREAD

**Issue by t-davies** [hashicorp/vault#16237]
**Describe the bug**
Consul Connect fails to renew leaf certificates after upgrading to Vault 1.10.

```
Unexpected response code: 500 (rpc error making call: rpc error making call: error issuing cert: Error making API request.

URL: PUT https://my.vault.host:8443/v1/pki/connect/intermediate/sign/leaf-cert
Code: 500. Errors:

* 1 error occurred:
	* unknown internal error updating default values: unsupported bit length for EC key: 2048)
	* 
```

I think this is related to https://github.com/hashicorp/vault/issues/14863, maybe already fixed by the fix for that?

I was able to resolve by manually setting the key type to `"ec"` and then manually setting "Key bits" to `0` (which in turn defaulted to `256`) for Consul Connect's PKI role.

**To Reproduce**
1. Have Consul Connect configure its own PKI infrastructure in Vault - using Vault <1.10.
2. Update to Vault 1.10.
3. See error when leaf certificates attempt to renew

**Expected behavior**
Updating to Vault 1.10 should gracefully handle setting the default key bits for existing PKI roles, or warn about this as a breaking change in the documentation.

**Environment:**
* Vault Server Version (retrieve with `vault status`): `1.11.0+ent`
* Vault CLI Version (retrieve with `vault version`): n/a
* Server Operating System/Architecture: linux/amd64

**Additional context**
Traefik was the system attempting to renew leaf certificates, but unsure if this is relevant. It uses Consul Connect natively, rather than via Envoy.

**Comment by stevendpclark** [comment]
Thanks for reporting the issue @t-davies!  

The linked PR should address the reported issue and will be backported to 1.11 and 1.10 release branches.
