### ISSUE TITLE
any Vault CLI command that executes to the server crashes laptop

### ISSUE THREAD

**Issue by qhenkart** [hashicorp/vault#16256]
On a freshly installed OS (MacOS 12.4), vault completely crashes my laptop. The second I make any request whatsoever. There seems to be some endless loop that consumes all resources. Internet access stops, and the computer memory slowly degrades until I can't even turn it off without force turning it off.

I have tried reinstalling, upgrading, using the direct download, using brew. All to no avail

**To Reproduce**
1. set VAULT_ADDR
2. vault login, vault status, (or any command that executes a request)
3. No Error. Sometimes I get an i/o error before my laptop overheats and dies

**Expected behavior**
the cli tool to work and return the same results as cURL or the UI

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.5.6 (from the UI). The CLI returned: Error checking seal status: Get "https://"ouraddress"/v1/sys/seal-status": dial tcp: i/o timeout. (I had to restart after running this). 

* Vault CLI Version (retrieve with `vault version`):Vault v1.11.0 (ea296ccf58507b25051bc0597379c467046eb2f1), built 2022-06-17T15:48:44Z. ( I have also tried with CLI version 1.5.6)
* Server Operating System/Architecture: 

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
where do I find the vault config? this is just the default CLI install
```

**Additional context**
Laptop is running Intel i9 2.9GHZ with 32GB of RAM 

This used to work on a previous OS installation on this same laptop. It currently works for all of my coworkers so it seems to be an isolated issue.

Is there any way to engage a verbose mode or output log so I can see what vault is doing under the hood with these requests?

**Comment by sgmiller** [comment]
You may try using "strace" or similar to see what system calls the CLI is executing.

**Comment by sgmiller** [comment]
On MacOS try dtruss: https://stackoverflow.com/questions/31045575/how-to-trace-system-calls-of-a-program-in-mac-os-x
