### ISSUE TITLE
[Plugin Portal] Plugin Submission - vault-plugin-database-redis

### ISSUE THREAD

**Issue by fhitchen** [hashicorp/vault#16286]
Hi, I wrote this plugin before the Partner plugin was available and I have had a number of requests from github users for me to get it listed on the community page as they use it in preference to the one from REDIS Labs which they say only supports the enterprise edition of REDIS whereas this one supports any kind of opensource installation.

**Plugin Information**
Name as it would appear listed: vault-plugin-database-redis
Plugin type (secrets/auth/database): database
Repository link: https://github.com/fhitchen/vault-plugin-database-redis

**Comment by Zlaticanin** [comment]
Hello! Thank you so much for doing this. We are currently looking into this, and we would like to use this as our code base. Would you be okay with us taking the ownership of this repository? If so, I will contact our IT department to start this process.

**Comment by fhitchen** [comment]
Hello! Yes I would like this very much. I just ask that you let me do something so that I can at least appear as a contributor in the official repo.

**Comment by Zlaticanin** [comment]
Hello! I just heard back from IT, and they said that they owner of the repo should start a transfer, and an Admin will get notification and accept it. Could you please start this process? Useful doc: https://docs.github.com/en/enterprise-server@3.3/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by fhitchen** [comment]
Hi Milena,

I just tried to transfer the repository and the request was rejected
because I don't have permissions to create a public repository in
Hashicorp. This is stated in the link you sent me.


   - To transfer a repository that you own to an organization, you must
   have permission to create a repository in the target organization.

What should I do? I don't want to make it private as that is a step I can't
undo I understand.

Regards, Francis.

**Comment by Zlaticanin** [comment]
Hello Francis,

I just reached out to our IT dept again, asking them about this. They suggested that you transfer the repo ownership to me, and I can then request new public repo as org member. Would this be okay with you? We would make sure that you appear as a contributor of course.

**Comment by fhitchen** [comment]
Yes, that would be fine.

**Comment by fhitchen** [comment]
Repository has been transferred, enjoy.

**Comment by Zlaticanin** [comment]
Hi Francis, repo has been transferred: https://github.com/hashicorp/vault-plugin-database-redis

Thank you so much for your contribution!

**Comment by Zlaticanin** [comment]
@fhitchen Hello! We would like to mention you and give you a shoutout in our Release Notes for the Redis plugin. Would you be okay with that?

**Comment by fhitchen** [comment]
Hi Milena,
yes I would be fine with that.
Thanks, Francis.
