### ISSUE TITLE
UI->Tools->Lookup asks for Wrapping Token instead of Token

### ISSUE THREAD

**Issue by ausmartway** [hashicorp/vault#16295]
**Describe the bug**
The label for UI Tools->Lookup should be 'Token' instead of 'Wrapping Token'. 

**To Reproduce**
Just see this from the UI.

**Expected behavior**
The label for the input should be Token instead of Wrapping Token

**Environment:**
* Vault Server Version (retrieve with `vault status`):
vault status
Key                     Value
---                     -----
Seal Type               shamir
Initialized             true
Sealed                  false
Total Shares            1
Threshold               1
Version                 1.11.0+ent
Build Date              2022-06-17T22:49:59Z
Storage Type            raft
Cluster Name            vault-cluster-74e06c40
Cluster ID              8d671209-c4db-8301-157d-ba7010fa59cb
HA Enabled              true
HA Cluster              https://node3:8201
HA Mode                 active
Active Since            2022-07-06T20:11:53.158703793Z
Raft Committed Index    1422341
Raft Applied Index      1422341
Last WAL                6795

* Vault CLI Version (retrieve with `vault version`):
Vault v1.11.0+ent (b61eb07cb09bfd7b0cf0647a9468e94c4419ae6a), built 2022-06-17T22:49:59Z

* Server Operating System/Architecture:
Ubuntu 22.04 
Linux node3 5.15.0-22-generic #22-Ubuntu SMP Tue Feb 8 13:17:51 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

**Comment by linda9379** [comment]
This issue was fixed in this PR: https://github.com/hashicorp/vault/pull/16489 so closing the issue.
