### ISSUE TITLE
Add support for KVv2 subkeys

### ISSUE THREAD

**Issue by r3nic1e** [hashicorp/vault#16305]
**Is your feature request related to a problem? Please describe.**
There is `/secret/subkeys/:path` endpoint for KVv2 secrets mounts that can be used only via API. Even if user has access to this endpoint via policy they cannot view secrets subkeys via UI, only via API. Adding support for that would be awesome for UI users.

**Describe the solution you'd like**
On the secret view page we could keep the same `Key` column and drop completely `Value` column. For JSON view, I guess, we could replace all values with `null`, but that's not the best solution.

**Additional context**
PR for subkeys endpoint: https://github.com/hashicorp/vault-plugin-secrets-kv/pull/59

Current KVv2 secret view:
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/4354690/179169015-c0eb8e3b-1207-4d46-b871-c14c1ae26a9d.png">

**Comment by heatherezell** [comment]
This has been implemented in Vault Enterprise as of 1.18. We will continue to evaluate possible inclusion into CE, depending on customer needs and product leadership decisions. Please feel free to comment here if you are a CE user and wish for this to be included in the future. Thanks!
