### ISSUE TITLE
RFE: allow signing externally-generated CSRs

### ISSUE THREAD

**Issue by DemiMarie** [hashicorp/vault#16315]
**Is your feature request related to a problem? Please describe.**
Vault’s PKI secrets engine currently generates the private key within Vault.  This is less secure than if the private key never leaves the system on which it is generated.  It is also explicitly forbidden by the CA/Browser Forum Baseline Requirements.

**Describe the solution you'd like**
Vault’s PKI should support issuing certificates without Vault having ever seen the private key.

**Describe alternatives you've considered**
None

**Explain any additional use-cases**
This is a blocker for Vault to be used to issue publicly trusted certificates.

**Additional context**

**Comment by maxb** [comment]
This functionality already exists: https://www.vaultproject.io/api-docs/secret/pki#sign-certificate

**Comment by DemiMarie** [comment]
> This functionality already exists: https://www.vaultproject.io/api-docs/secret/pki#sign-certificate

Good point.  The API documentation makes this clear, but there was some other documentation that was less clear.  I forget which one, though.
