### ISSUE TITLE
Helm chart 0.20.x broken

### ISSUE THREAD

**Issue by andreas-p** [hashicorp/vault#16322]
When executing `helm template vault hashicorp/vault --version 0.20.1` (or 0.20.0), the following message is emitted:
`Error: parse error at (vault/templates/_helpers.tpl:38): unclosed action`

The last version that works correctly is 0.19.0, tested with helm 3.3.0 and 3.9.1.

**Comment by maxb** [comment]
From the Go 1.16 changelog - https://go.dev/doc/go1.16 :

> [text/template](https://go.dev/pkg/text/template/)
> Newlines characters are now allowed inside action delimiters, permitting actions to span multiple lines.

Only Helm built using Go 1.16 or later is able to process the syntax now used in the chart.

**Comment by andreas-p** [comment]
Ok I re-checked with helm 3.9.1, and it appears that my previous check wasn't really with 3.9.1....

I can confirm that the charts 0.20.x DO work with the latest helm.
Thanks!
