### ISSUE TITLE
automatic revokation of auth token, after X uses

### ISSUE THREAD

**Issue by dreamcat4** [hashicorp/vault#164]
I'm still struggling with concepts and possible issues how to use vault in docker.

It would be nice to generate a 'one time usage' access token for the container. So that once the image is built, the token has already been used and gets automatically revoked.

This is useful for docker, because when building an image there is no way to hide the access token to the vault. It cannot be deleted due to the way docker saves layers and metadata history.

**Comment by armon** [comment]
@dreamcat4 This is already possible! Here is an example:

```
$ vault token-create -use-limit 1
f7b9c56e-1186-bfc8-61cf-2f293b691a22

$ vault auth f7b9c56e-1186-bfc8-61cf-2f293b691a22
Successfully authenticated! The policies that are associated
with this token are listed below:

root

$ vault read secret/foo
No value found at secret/foo

 $ vault read secret/foo
Error reading secret/foo: Error making API request.

URL: GET http://127.0.0.1:8200/v1/secret/foo
Code: 400. Errors:

* permission denied
```

When you generate an auth token, you can specify the number of uses. If you specify 1, you get a "one time use" equivalent!

**Comment by dreamcat4** [comment]
@armon Awesome! Glad to hear it.

Sorry I missed that in the docs page @ https://vaultproject.io/docs/auth/token.html

**Comment by armon** [comment]
I'm going to close this, since it seems to be resolved!
