### ISSUE TITLE
Potential crash when Consul agent restarted

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#1641]

**Comment by jefferai** [comment]
Report here:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/Z-i_ewo4Bxk/5Ny-3oQJBAAJ

**Comment by jefferai** [comment]
I created a single-node Consul 0.6.4 cluster, and connected Vault 0.6 to it:

```
$ vault server -config=consul.hcl
==> Vault server configuration:

       Advertise Address: http://127.0.0.1:8200
                 Backend: consul (HA available)
              Listener 1: tcp (addr: "0.0.0.0:8200", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
                 Version: Vault v0.6.0-rc1 ('f627c01df8d7bebb403cf899ca1beb24f5fc84cd')

==> Vault server started! Log data will stream in below:

2016/07/21 12:41:40 [WARN]: consul: appending trailing forward slash to path
2016/07/21 12:41:49 [INFO] core: security barrier not initialized
2016/07/21 12:41:49 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2016/07/21 12:41:49 [INFO] core: post-unseal setup starting
2016/07/21 12:41:49 [INFO] core: mounted backend of type generic at secret/
2016/07/21 12:41:49 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/07/21 12:41:49 [INFO] core: mounted backend of type system at sys/
2016/07/21 12:41:49 [INFO] rollback: starting rollback manager
2016/07/21 12:41:49 [INFO] core: post-unseal setup complete
2016/07/21 12:41:49 [INFO] core: root token generated
2016/07/21 12:41:49 [INFO] core: pre-seal teardown starting
2016/07/21 12:41:49 [INFO] rollback: stopping rollback manager
2016/07/21 12:41:49 [INFO] core: pre-seal teardown complete
2016/07/21 12:42:09 [INFO] core: vault is unsealed
2016/07/21 12:42:09 [WARN]: consul: Concurrent sealed state change notify dropped
2016/07/21 12:42:09 [INFO] core: entering standby mode
2016/07/21 12:42:09 [INFO] core: acquired lock, enabling active operation
2016/07/21 12:42:09 [WARN]: consul: Concurrent state change notify dropped
2016/07/21 12:42:09 [INFO] core: post-unseal setup starting
2016/07/21 12:42:09 [INFO] core: mounted backend of type generic at secret/
2016/07/21 12:42:09 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/07/21 12:42:09 [INFO] core: mounted backend of type system at sys/
2016/07/21 12:42:09 [INFO] rollback: starting rollback manager
2016/07/21 12:42:09 [INFO] core: post-unseal setup complete
```
I then stopped the Consul process and restarted it, leading to the following:
```
2016/07/21 12:42:23 [WARN] core: leadership lost, stopping active operation
2016/07/21 12:42:23 [WARN]: consul: Concurrent state change notify dropped
2016/07/21 12:42:23 [ERR] core: clearing leader advertisement failed: dial tcp 127.0.0.1:8500: getsockopt: connection refused
2016/07/21 12:42:23 [INFO] core: pre-seal teardown starting
2016/07/21 12:42:23 [INFO] rollback: stopping rollback manager
2016/07/21 12:42:23 [INFO] core: pre-seal teardown complete
2016/07/21 12:42:23 [ERR] core: failed to acquire lock: failed to create session: Put http://127.0.0.1:8500/v1/session/create: dial tcp 127.0.0.1:8500: getsockopt: connection refused
2016/07/21 12:42:24 [WARN]: consul: check unable to talk with Consul backend: Put http://127.0.0.1:8500/v1/agent/check/pass/vault-sealed-check?note=Vault+Unsealed: dial tcp 127.0.0.1:8500: getsockopt: connection refused
2016/07/21 12:42:26 [WARN]: consul: check unable to talk with Consul backend: Put http://127.0.0.1:8500/v1/agent/check/pass/vault-sealed-check?note=Vault+Unsealed: dial tcp 127.0.0.1:8500: getsockopt: connection refused
2016/07/21 12:43:15 [INFO] core: acquired lock, enabling active operation
2016/07/21 12:43:15 [WARN]: consul: Concurrent state change notify dropped
2016/07/21 12:43:15 [INFO] core: post-unseal setup starting
2016/07/21 12:43:15 [INFO] core: mounted backend of type generic at secret/
2016/07/21 12:43:15 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/07/21 12:43:15 [INFO] core: mounted backend of type system at sys/
2016/07/21 12:43:15 [INFO] rollback: starting rollback manager
2016/07/21 12:43:15 [INFO] core: post-unseal setup complete
```
Vault was able to serve requests normally, and did not seal.

Next step will be to test with two Vaults in an HA setup to see if that makes a difference.

**Comment by jefferai** [comment]
I just tested with two separate Vault nodes connected to the same Consul agent/server. Same result -- after the original locks expired, one of the two Vaults gained active operation and the other began forwarding to it. The lock expiration could take a bit, but Vault did recover afterwards.

I did find a bug after calling `step-down` (which wouldn't be the normal case when the Consul agent restarts, just something in my testing) where the Vault instance that has been stepped down is not correctly forwarding requests in some cases, leading to a redirect loop. But neither of these conditions caused a seal.

Is it possible you have some kind of process monitoring going on, where if you are seeing a 500 come from Vault (or, in the case of the redirect loop, an EOF), you're automatically restarting it? There will definitely be some errors from Vault for a while until the Consul connection is back up and the existing leader lock expires so that a Vault instance can grab it, but after that things were working just fine.

**Comment by daveadams** [comment]
Hey @jefferai Thanks for jumping right onto this. I think I've found the issue, which is not Vault's fault-- our upstart scripts set the Vault server to rely on Consul, so when the Consul process is restarted with upstart, Vault was restarted as well.

Sorry for sending you on a wild goose chase! :disappointed:

**Comment by jefferai** [comment]
@daveadams It's no problem. It exposed some other issue with manual step down, so even if it's not a bug in Vault causing your issue, I get to fix a bug that would have bit someone some day.  :-D

**Comment by jefferai** [comment]
@daveadams Aw shucks, and the "problem" I'm seeing was only because I didn't realize I had an error in my testing setup, probably from something I was testing long ago on purpose. No bug exists. At least, not here...

Red herring on both ends of this!
