### ISSUE TITLE
Can't login via vault ssh to EC2 instance built from Flatcar 3227.2.0

### ISSUE THREAD

**Issue by Oleksii-Melnyk-UA** [hashicorp/vault#16423]
Hi team,

I built an image based on Flatcar 3227.2.0 using Packer.
Then via Terraform created AWS EC2 instance using this image.
When try to connect to this EC2 instance via vault ssh command, receive an error:

failed to generate credential: failed to get credentials: Error making API request.
URL: PUT https://my_vault_url/path
Code: 500. Errors:

1 error occurred:
failed to add public key to authorized_keys file in target: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
I can successfully login via vault ssh to EC2 instances built on Flatcar 3033.2.2 image.
But received the same error, when tried to connect to instance, built on Flatcar 3139.2.3.

Do you know what can be the root cause?
I noticed that in Flatcar 3139.2.0 openssh version changed to 8.8.
I have vault cluster v1.7.2, locally installed vault client 1.9.2, locally have ssh version OpenSSH_8.6p1 .

**Comment by jepio** [comment]
Hi,
I'm not familiar with Vault SSH. This might be the same issue as https://github.com/hashicorp/vault/issues/15488?
Would you see if applying the following configuration to `/etc/ssh/sshd_config` on the Flatcar server helps:
```
PubkeyAcceptedAlgorithms +ssh-rsa-cert-v01@openssh.com
```

**Comment by ccapurso** [comment]
Hi @Oleksii-Melnyk-UA, we reserve GitHub issues for bug reports and feature requests, which this doesn't appear to be. In general, we recommend discussing such issues in the [Vault Community Forum](https://discuss.hashicorp.com/c/vault/30).

As noted above, it looks like there may be a similar issue being discussed in https://github.com/hashicorp/vault/issues/15488. If you can confirm that you are facing the same issue, then we will close this in favor of consolidating discussion there.

**Comment by Oleksii-Melnyk-UA** [comment]
I added the above configuration to /etc/ssh/sshd_config on the Flatcar server image, but it didn't help.
Received same error.

`PubkeyAcceptedAlgorithms +ssh-rsa-cert-v01@openssh.com`

So, I close this ticket, will open and issue in the [Vault Community Forum](https://discuss.hashicorp.com/c/vault/30).
