### ISSUE TITLE
can I share backend for different routeEntry in router(root radix tree) ?

### ISSUE THREAD

**Issue by Nikita1821** [hashicorp/vault#16448]
can I share backend for different routeEntry in router(root radix tree) but different storageView?

re := &routeEntry{
		tainted:       mountEntry.Tainted,
		backend:       backend,
		mountEntry:    mountEntry,
		storagePrefix: storageView.Prefix(),
		storageView:   storageView,
	}

Example: kv1 and kv2 engine with one backend, but storageView for kv1 - it's subview with prefix "kv1/' and storageView for kv2 - it's subview with prefix "kv2/'

**Comment by Nikita1821** [comment]
code in vault/router.go

**Comment by Nikita1821** [comment]
you use uuid MountEntry during create view
backendBarrierPrefix + e.UUID + "/"
...
viewPath := entry.ViewPath()
view := NewBarrierView(c.barrier, viewPath)

why are you use different backend for engines that are of the same type ?

**Comment by ccapurso** [comment]
Hi @Nikita1821, storage cannot be shared between backends. Each backend will require its own storage view.
