### ISSUE TITLE
Vault documentation: misprint in OIDC Provider Concept page

### ISSUE THREAD

**Issue by Suselz** [hashicorp/vault#16449]
In the process of reading the documentation, I found an misprint in the [keys](https://www.vaultproject.io/docs/concepts/oidc-provider#keys) section of [OIDC Provider Concept page](https://www.vaultproject.io/docs/concepts/oidc-provider).
In the description of the default key, the field `rotation_period` is repeated twice.

![image](https://user-images.githubusercontent.com/95070811/180992217-27984d82-929b-4802-86c0-e2d9a8360de7.png)

In the first case, the correct field `algorithm`

**Comment by austingebauer** [comment]
Thanks for reporting this, @Suselz! I'll get the docs fixed up.

**Comment by austingebauer** [comment]
It looks like this was fixed in https://github.com/hashicorp/vault/pull/16051 but never made it to the live site. It will be published shortly. Thanks again!
