### ISSUE TITLE
Is it possible to use Mysql backend to create database?

### ISSUE THREAD

**Issue by minhdanh** [hashicorp/vault#1648]
What if I need to create a database and a user/password pair attached to that database? If that is possible, will the database be deleted once the secrets are revoked?
I can see there's a `sql` parameter but it is said to be "The SQL statements executed to create and configure the role", not very much related to creating a database.

Between, the example to create a sample role in the document (https://www.vaultproject.io/docs/secrets/mysql/index.html) grants `SELECT` privilege to ALL the databases:
```
vault write mysql/roles/readonly \
    sql="CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT SELECT ON *.* TO '{{name}}'@'%';"
```

I think it would be preferable if we can specify a database name without having to create a new role. So in order to reuse a role for some database, we can do like this:

```
vault read mysql/creds/readonly/new_database
```

If the database doesn't exist yet, it'll be created.
Just my 2 cents.

**Comment by jippi** [comment]
```
vault write mysql/roles/readonly \
    sql="CREATE DATABASE IF NOT EXISTS meh; CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT SELECT ON meh.* TO '{{name}}'@'%';"
```

?

**Comment by minhdanh** [comment]
I see. However this still tights the database name with the role.

**Comment by jippi** [comment]
Yeah, as it should be, imo :) those roles can easily be created programmatically anyway :) don't think it's the role of Vault to manage database creation.
