### ISSUE TITLE
Vault HTTP API /sys/init with Keybase

### ISSUE THREAD

**Issue by gkhasel1** [hashicorp/vault#1651]
Through the command line it is possible to pass in keybase usernames as the mechanism for encrypting master key shares when calling `vault init`. I was unable to produce the same behavior using the HTTP API on the `/sys/init` endpoint. Is it possible to add this feature to the API? Thanks!

**Comment by jefferai** [comment]
The HTTP API simply takes in the actual public key data. It doesn't know or care if they came from Keybase, PGP, GPG, or anywhere else, and we want to keep it agnostic at that point. You could pretty easily copy the logic from the CLI code to query Keybase yourself -- it's a simple `curl`/`jq` call so if you're already using the HTTP API it should be pretty trivial.

**Comment by gkhasel1** [comment]
Thanks for the quick response @jefferai
