### ISSUE TITLE
Support for TLS in ZooKeeper backend

### ISSUE THREAD

**Issue by devth** [hashicorp/vault#1652]
ZooKeeper supports TLS. [Here's the guide](https://cwiki.apache.org/confluence/display/ZOOKEEPER/ZooKeeper+SSL+User+Guide) on configuring it.

I think on the Vault / ZK client side we'd need to be able to specify `tls_ca_file`, `tls_cert_file` and `tls_key_file`, similar to the `consul` backend. I'm not sure if the golang zookeeper client supports this (I couldn't find anything).

/cc @sherzberg @kenbreeman @elupu

**Comment by kenbreeman** [comment]
Doesn't look go-zookeeper supports TLS yet, but this would be nice to have.

**Comment by reegz** [comment]
Hi,

Are there any plans to add SSL support for a Zookeeper storage backend? 

Thanks

**Comment by jefferai** [comment]
When go-zookeeper supports it and someone codes it in, we'll be happy to have it :-)

**Comment by vixns** [comment]
https://github.com/samuel/go-zookeeper/issues/161#issuecomment-299038682

**Comment by palsaurabh2005** [comment]
I have submitted a PR for this change: https://github.com/hashicorp/vault/pull/4856
The change will allow Vault to connect with Zookeeper using TLS.
