### ISSUE TITLE
Digital signature endpoint for PKI engines

### ISSUE THREAD

**Issue by rmartinez-dasnano** [hashicorp/vault#16529]
**Is your feature request related to a problem? Please describe.**
We are using Vault to deliver certificates for  mTLS in several services in a multitenant environment. For that we create a PKI engine for each tenant to avoid  interoperability between tenants.

Now we have the requirement to create digital signatures to avoid interoperability between tenants for some specific documents/data. Having a PKI for each tenant, it's quite straightforward to think about these pkis to sign the documents.

**Describe the solution you'd like**
As long as Vault implements PKI engines where we have a private key and a public key (certificacte) it would be great to offer the option to sign data with pki engines. Something similar to data encryotion.

**Describe alternatives you've considered**
New PKI engine endpoint, something similar to

| Method | Path                 | Signer                                                             |
|--------|----------------------|--------------------------------------------------------------------|
| POST   | /pki/data/sign/:name | Private key of PKI applying rules defined in role with name `name` |

##### Parameters:
name (path): the digital signature role where we define for example supported signature algorithms
data_base64 (body): data to be signed
algorithm (body): Signature algorithm to be used. Must be one of the supported algorithms defined in the role

**Explain any additional use-cases**
The alternative if we want to use these PKIs is to store private key (from CA or a child pk) as secret and retrieve it to sign data. That's not so good  from security point of view.  

**Additional context**

**Comment by cipherboy** [comment]
https://github.com/hashicorp/vault/issues/3845 is very similar conceptually and likely how we'll implement this: Vault's PKI engine is a X509 CA PKI engine, not a X509 Leaf PKI engine, and will likely never support the latter types of operations.

This data signature is something we'd like to support eventually, but its more likely to appear in Transit.
