### ISSUE TITLE
creation_time format inconsistency

### ISSUE THREAD

**Issue by compressed** [hashicorp/vault#1654]
I'm writing some logic for reading vault API responses and noticed an inconsistency with at least two endpoints for the `creation_time` field:

- `/v1/auth/token/lookup-self`: `creation_time` is in seconds since unix epoch (e.g. `1469474051`)
- `/v1/secret/x` when specifying a wrapped response (`X-Vault-Wrap-TTL`): `creation_time` is in RFC3339 format (e.g. `"wrap_info.creation_time":"2016-07-07T16:14:00.813729922Z"`)

Is this expected/desired? I would think it would be better to have all these timestamps in one consistent format.

**Comment by jefferai** [comment]
It would absolutely be better, but for backwards compatibility reasons they aren't. This is one of the items that we will fix whenever we decide to roll a `/v2/` API.

**Comment by compressed** [comment]
Ah ok, thanks. I can rely on this behavior staying the way it is then for v1 at least.

**Comment by jefferai** [comment]
Yes, you can. If this changes for some reason, it will be clearly communicated in the upgrade guide for that version (a https://www.vaultproject.io/docs/install/index.html) and in the changelog.
