### ISSUE TITLE
Vault revoke lease rabbitmq creds, befor ttl expire 

### ISSUE THREAD

**Issue by PaulLol** [hashicorp/vault#16544]
Hi. Please help!
Vault revoke lease rabbitmq creds, befor ttl expire.
Have:
“default_lease_ttl”:31536000,
“max_lease_ttl”:31536000
Revoke after 30 days.
OS: CentOS
Vault version: 1.9.1
dublicate on:
https://discuss.hashicorp.com/t/vault-revoke-lease-rabbitmq-creds-befor-ttl-expire/42718

**Comment by ccapurso** [comment]
Hi, @PaulLol. Thank you for your interest in Vault! We reserve the use of GitHub issues for bug reports and feature requests. Since you have already opened a duplicate on our discuss page, I am going to close this issue.
