### ISSUE TITLE
Fix Lease, Renew, and Revoke documentation (remove lease_id)

### ISSUE THREAD

**Issue by kmitrovic** [hashicorp/vault#1657]
Looks like there are some tasks about this page ([filtered issues](https://github.com/hashicorp/vault/issues?utf8=%E2%9C%93&q=lease%20is%3Aopen%20documentation)). However, I couldn't find any task about this.

The [issue](https://github.com/hashicorp/vault/issues/877) about this is close, but the documentation is still not fixed.

**Comment by jefferai** [comment]
@kmitrovic I honestly don't know what this issue is about, but appears to simply be an issue to discuss other issues. Please comment on the appropriate issue, or create a PR if there is a particular change you would like to propose.
