### ISSUE TITLE
Support OIDC roles when logging in through CLI

### ISSUE THREAD

**Issue by JDurstberger** [hashicorp/vault#16577]
**Is your feature request related to a problem? Please describe.**
I am unable to select which role I'd like to login with when using the CLI as it is possible when using the web GUI.
My understanding is that it currently uses the default role.

**Describe the solution you'd like**
I'd like to be able to pass an option `-role={some-role}` when using `vault login -method=oidc`

Example:
`vault login -method=oidc -role=admin` or `vault login -method=oidc -role=read-only-user`

**Comment by austingebauer** [comment]
@JDurstberger - You can select the role for CLI-based OIDC logins by removing the `-` from the beginning of the role parameter. You can see how this looks in our documentation at: https://www.vaultproject.io/docs/auth/jwt#oidc-login-cli.

**Comment by austingebauer** [comment]
I'm going to close this since the request feature works. Feel free to reopen if you disagree!

**Comment by JDurstberger** [comment]
Sorry for missing this, completely my bad.
