### ISSUE TITLE
Small spelling Error on Vault Documentation page

### ISSUE THREAD

**Issue by Ryan-Harth** [hashicorp/vault#16587]
**Describe the bug(Issue)**
Not a bug, but a small spelling error on the Vault page located at: https://www.vaultproject.io/docs/what-is-vault?_gl=1*4ijkpf*_ga*MjA3MjA2NDguMTY1NzczMDUxMA..*_ga_P7S46ZYEKW*MTY1OTYxNTMwOS4yLjEuMTY1OTYxNzYzNS4w

Under the heading "How Does Vault Work" in the second sentence, the 9th word is misspelled ("contains" should be "constrains").

Thanks for the amazing learning content!

**Comment by hsimon-hashicorp** [comment]
Hi @JediViking18a! If you're feeling up to it, you can open PRs to correct these typos as you find them. :) Otherwise, we'll get on it within the team. Thanks! :)

**Comment by Anil10Kulkarni** [comment]
I will work on this and submit a PR request later

**Comment by Anil10Kulkarni** [comment]
> **Describe the bug(Issue)** Not a bug, but a small spelling error on the Vault page located at: https://www.vaultproject.io/docs/what-is-vault?_gl=1*4ijkpf*_ga*MjA3MjA2NDguMTY1NzczMDUxMA..*_ga_P7S46ZYEKW*MTY1OTYxNTMwOS4yLjEuMTY1OTYxNzYzNS4w
> 
> Under the heading "How Does Vault Work" in the second sentence, the 9th word is misspelled ("contains" should be "constrains").
> 
> Thanks for the amazing learning content!

@Ryan-Harth - I was going through this issue and wanted to ask you this. You have mentioned as  ("contains" should be "constrains"). Should it be constrains or contains? Kindly advice.

**Comment by aphorise** [comment]
> [How does Vault work?](https://www.vaultproject.io/docs/what-is-vault?_gl=1*4ijkpf*_ga*MjA3MjA2NDguMTY1NzczMDUxMA..*_ga_P7S46ZYEKW*MTY1OTYxNTMwOS4yLjEuMTY1OTYxNzYzNS4w#how-does-vault-work)

> Vault works primarily with tokens and a token is associated to the client's policy. Each policy is path-based and policy rules **contrains** the actions and accessibility to the paths for each client. With Vault, you can create tokens manually and assign them to your clients, or the clients can log in and obtain a token. The illustration below displays Vault's core workflow.

There's simply an **`s`** missing to make it **`constrains`** as per the original intent of both this issue and the author of the article.

**Comment by aphorise** [comment]
Will be corrected & closed further to the PR above.
