### ISSUE TITLE
vault image requires internet access

### ISSUE THREAD

**Issue by jatinkumarpatel** [hashicorp/vault#16591]
**Describe the bug**
We are trying to deploy vault pods using [vault:1.11.1](https://hub.docker.com/layers/vault/library/vault/1.11.1/images/sha256-3431c4abf0626b6dcdc5e089b50f45f42b02e70c0e8e052dbfa7b286112b783c?context=explore) image in AWS EKS Cluster where worker nodes doesn't have **internet connection**.  Vault image already pushed to internal image registry. The pods keeps on restarting and goes in CrashLoopBackOff state and we are not seeing any logs when we ran `kubectl logs` command.
PostgreSQL port is open and we have tested the port connectivity. Vault is able to connect to the database.

We observed vault pods were trying to connect below IPs and didn't get any response. In netstat, connection was in `SYN_ACK` state for below IPs
```
54.239.29.25:443
54.239.21.217:443
209.54.180.124:443
209.54.180.124:443
```

**To Reproduce**
Deploy vault in worker nodes which doesn't have internet access.

Vault server configuration file(s):

```hcl
listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }
    storage "postgresql" {
      table          = "vault_kv_store"
    }
    seal "awskms" {
      region      = "ap-xxxx"
      kms_key_id  = "xxxxxxxxx"
    }
    disable_mlock = true
    disable_cache = true
    max_lease_ttl = "43800h"
```

**Other Configuration**
Database backend : AWS RDS Postgresql 14.1

**Additional context**
Connection string is passed as environment variable.
VAULT_PG_CONNECTION_URL : "postgres://username:xxxxx@xxxx.rds.amazonaws.com:6432/db_name?sslmode=disable"

**Comment by stevendpclark** [comment]
Hi @jatinkumarpatel thanks for your interest in Vault!

This is purely a guess, but as your configuration is using an `awskms` auto-unseal without an [endpoint configured](https://www.vaultproject.io/docs/configuration/seal/awskms#endpoint), that might be the issue you are facing if the pods do not have internet access. 

With that said we reserve Github issues for bug reports and feature requests, which this doesn't appear to be. As such, I'm going to close this and suggest that you ask about this in our [Vault Discuss](https://discuss.hashicorp.com/c/vault/30) if the issue persists.

**Comment by jatinkumarpatel** [comment]
I have raised same query here [Vault Discuss](https://discuss.hashicorp.com/c/vault/30), tried with VPC endpoints and it fails again, still it's trying to connect to IPs in range 54.239.xxx.xxx:443, 209.54.xxx.xxx:443

**Comment by jatinkumarpatel** [comment]
It's working now. Since it's a private cluster and we are using IAM role to access AWS KMS, we also need access to STS regional endpoints. Added below environment variables in the deployment spec.
```
- name: AWS_REGION
value: ap-south-1
    - name: AWS_STS_REGIONAL_ENDPOINTS
    value: regional
```

**Comment by stevendpclark** [comment]
Thanks for following up and glad to hear you got it working @jatinkumarpatel!
