### ISSUE TITLE
Delete service principal credential on azure/rotate-root 

### ISSUE THREAD

**Issue by susam** [hashicorp/vault#16610]
**Is your feature request related to a problem? Please describe.**

An application registration on Azure may have application password or service principal password or both. Both types of password can be used successfully as `client_secret` in the following Vault CLI command:

```sh
vault write azure/config use_microsoft_graph_api=true \
                         tenant_id="$TENANT_ID" subscription_id="$SUBSCRIPTION_ID" \
                         client_id="$CLIENT_ID" client_secret=- <<< "$SECRET"
```

In a command like this, we specify the application ID of the application object as the `client_id`. But for the `client_secret` value, we may specify either an application credential or a service principal credential. If we then perform `vault write -f azure/rotate-root`, Vault does not delete the service principal credential and instead adds a new application credential.

Note: The `vault write -f azure/rotate-root` operation works fine without any surprises if we use an application password (i.e., the password directly belongs to the application object) to configure Vault's Azure secrets engine. The behaviour described above occurs only when we use a service principal password (i.e., the password belongs to the service principal object associated with the application object) to configure the Azure secrets engine.

Here are the steps to reproduce the behaviour described above. These steps require `az` and `jq` commands to be present:

 1. Log into Azure using Azure CLI:

    ```sh
    az login
    ```

 2. Run the following shell script to create a new application named `foo-app` and its underlying service principal (SP) object along with a password each for the application object and the service principal object:

    ```sh
    set -ex
    APP_ID=$(az ad app create --display-name foo-app | jq -r .appId)
    az ad sp create --id "$APP_ID"
    az ad app credential reset --id "$APP_ID"
    az ad sp credential reset --id "$APP_ID"
    ```

    Copy the app ID, app password, and the SP password from the output and keep them handy. They will be needed in steps 4 and 7 below.

 3. Run the following commands to confirm that the `foo-app` application has an application password as well as a service principal password:

    ```sh
    set -ex
    NAME=foo-app
    APP_ID=$(az ad app list --display-name "$NAME" | jq -r '.[0].appId')
    az ad app credential list --id "$APP_ID"
    az ad sp credential list --id "$APP_ID"
    ```

 4. For good measure, double-check that indeed either application password or service principal password can be used to log into Azure with this script:

    ```sh
    set -ex
    TENANT_ID=
    APP_ID=
    APP_SECRET=
    SPN_SECRET=
    az login --service-principal --allow-no-subscriptions -t "$TENANT_ID" -u "$APP_ID" -p "$APP_SECRET"
    az login --service-principal --allow-no-subscriptions -t "$TENANT_ID" -u "$APP_ID" -p "$SPN_SECRET"
    ```

    Before running the script above, set the four variables at the top to appropriate values. The `APP_SECRET` should be set to the application password. The `SPN_SECRET` should be set to the service principal password.

 5. Go to https://portal.azure.com/ > Azure AD roles and administrators > Application Administrator > Add assignments. Then search for `foo-app`. Click the Add button. This completes the role assignment for `foo-app` needed to perform step 7 below.

 6. Start Vault server in development mode:

    ```sh
    vault server -dev
    ```

 7. Now run the following script after setting the four variables at the top with appropriate values:

    ```sh
    set -x

    TENANT_ID=
    SUBSCRIPTION_ID=
    APP_ID=
    SPN_SECRET=

    export VAULT_ADDR='http://127.0.0.1:8200'

    vault secrets enable azure

    vault write azure/config tenant_id="$TENANT_ID" subscription_id="$SUBSCRIPTION_ID" client_id="$APP_ID" client_secret=- use_microsoft_graph_api=true <<< "$SPN_SECRET"

    vault write -f azure/rotate-root
    ```

    The `SPN_SECRET` variable should be set to the service principal password (not the application password).

 8. Now wait for 2-3 minutes for Azure to attain eventual consistency w.r.t. to the credentials.

 9. Now run the script in step 3 again. The output should show that while there is a new application password now, the service principal password created in step 2 is still intact.

I believe the behaviour described above occurs because Vault only resets application credential (not service principal credential) during the `azure/rotate-root` operation.

**Describe the solution you'd like**

It would be ideal if Vault deletes the service principal password, especially, when the Vault secrets engine is configured with the service principal password. This would ensure that the root secret used to configure Vault does not keep lying around.

**Describe alternatives you've considered**

If the solution proposed in the previous section cannot be accomplished, then it would be nice to update the documentation at https://www.vaultproject.io/docs/secrets/azure to clarify that the client secret used to configure the Azure secrets engine (i.e., the root secret) must be an application credential, not a service principal credential, if we want the root secret to be deleted automatically on `azure/rotate-root`.

**Explain any additional use-cases**

N/A

**Additional context**

Azure secrets engine's `azure/rotate-root` operation seems to work without surprises only if Azure secrets engine is configured with an application password. However, it is possible in practice that a Vault admin configures the Azure secrets engine with a service principal password as the root secret.

For example, the Terraform [azuread_service_principal_password](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/service_principal_password) block creates a password that belongs to the service principal object (not the application object). A Vault administrator may end up configuring Vault's Azure secrets engine with this service principal password. Now when they perform the `azure/rotate-root` operation, they would be mistaken if they believe that the root secret (service principal password) has been deleted. Since the root secret still remains intact after `azure/rotate-root`, I believe this area needs to be taken a closer look at and either handled appropriately or clarified in the documentation.

**Comment by hsimon-hashicorp** [comment]
Hello! Does this issue persist in more recent versions of Vault? Please let me know so I can make sure to bubble it up to the engineering team again. Thanks!
