### ISSUE TITLE
Mysql backend - vault read (mysql)/roles/?list=true fails

### ISSUE THREAD

**Issue by singram** [hashicorp/vault#1663]
I'm attempting to get a list of the available roles for the mysql backend but failing

Following the [documentation](https://www.vaultproject.io/docs/secrets/mysql/index.html) yields ....

```
./vault read /roles/?list=true
Error reading roles/?list=true: Error making API request.

URL: GET http://127.0.0.1:8200/v1/roles/%!F(MISSING)list=true
Code: 400. Errors:

* no handler for route 'roles/?list=true/'
```
On the off-chance the documentation is wrong (the list URL is missing the \mysql path prefix) this call also fails.

```
$ ./vault read mysql/roles/?list=true
Error reading mysql/roles/?list=true: Error making API request.

URL: GET http://127.0.0.1:8200/v1/mysql/roles/%!F(MISSING)list=true
Code: 500. Errors:

* 1 error(s) occurred:

* unsupported path
```

**Comment by jefferai** [comment]
The command for listing is `vault list`. It doesn't use URIs...under the hood it will make that call for you.

**Comment by singram** [comment]
@jefferai Thanks!  Works great.
Is the API URL for the mysql list method correct?  I would have thought it would be prefixes with 'mysql/' in alignment with the other calls.

**Comment by jefferai** [comment]
It is correct, yes.
