### ISSUE TITLE
Agent auto-auth from token in a file

### ISSUE THREAD

**Issue by ammarzuberi** [hashicorp/vault#16637]
**Is your feature request related to a problem? Please describe.**
We auto-auth the Vault agent using a JWT in production. I want to use the Vault agent in my local development environment where we get tokens by authenticating with OIDC.

**Describe the solution you'd like**
Auto-auth should have an option that does not actually authenticate, but instead reads the token from `~/.vault-token` and/or an arbitrary file path.

**Describe alternatives you've considered**
Abusing a different type of auto-auth token, forwarding the agent port from servers that are auto-auth'd, etc.

**Comment by VioletHynes** [comment]
Hi there! Going to close this issue, as this feature has been implemented in https://github.com/hashicorp/vault/pull/18740 and will be available in Vault 1.13.

Thanks for the report. The enthusiasm for this feature helped us prioritize it!

**Comment by HomeOfTheWizard** [comment]
Hi, is there a documentation for this feature ? I couldn't fine any :(

**Comment by VioletHynes** [comment]
@HomeOfTheWizard https://developer.hashicorp.com/vault/docs/agent-and-proxy/autoauth/methods/token_file
