### ISSUE TITLE
Remove Vault secret in /vault/secrets/ with Kubernetes

### ISSUE THREAD

**Issue by khoale1605** [hashicorp/vault#16682]
After starting the application in the Kubernetes container, I want to delete the secret files is hosted in that container.

My deployment.yaml

![image](https://user-images.githubusercontent.com/57674103/184064578-78f3cc62-a9af-4faf-beaf-2fb16bb0bea8.png)

and at the argument, I add command to remove /vault/secrets/config (which file are contained all my secret). But it still there after my app is running. 

![image](https://user-images.githubusercontent.com/57674103/184065552-f0dffb9d-0766-491d-bf73-3c8e405fcbe1.png)

![image](https://user-images.githubusercontent.com/57674103/184065098-6963629a-9b49-4e08-8618-99b3d3b9c4f5.png)

It does not make sense if we have a thousand pods and each pods carry secret file without delete in deployment flows

**Comment by tvoran** [comment]
Hi @khoale1605, by default the injector adds an init and a sidecar container running vault-agent, so the sidecar is probably maintaining the secrets file in /vault/secrets/. If you add the annotation [`agent-pre-populate-only: "true"`](https://developer.hashicorp.com/vault/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-pre-populate-only) then only the init container will be injected, so your app should be free to remove the secrets file.  

Related links:

- https://developer.hashicorp.com/vault/docs/agent/template#renewals-and-updating-secrets
- https://github.com/hashicorp/vault/issues/13676#issuecomment-1015533244
