### ISSUE TITLE
Help text for the auth/app-id/login/ path not showing

### ISSUE THREAD

**Issue by centromere** [hashicorp/vault#167]
I am unable to view the help text for the `/login` endpoint of the app-id backend:

    $ ./vault help auth/app-id/login/
    Error reading help: Error making API request.
    
    URL: GET http://localhost:8200/v1/auth/app-id/login/?help=1
    Code: 500. Errors:
    
    * unsupported path

`$ ./vault help auth/app-id/` works as intended.

**Comment by armon** [comment]
Fixed in https://github.com/hashicorp/vault/commit/68a99a88065412854314ae5d3dbe502f303fb6bb and https://github.com/hashicorp/vault/commit/83dbdf16114ad5a6aaaf9df4a09b89d66637defe
