### ISSUE TITLE
Expiry for mapping in App-id

### ISSUE THREAD

**Issue by henti** [hashicorp/vault#1672]
The current implementation of app-id does not have a way to expire mappings between app-id's and user-id's. 

In the current app-id docs your use case is described as 

> An out-of-band process run by security operators map unique user IDs to these app IDs. Example: when an instance is launched, a cloud-init system tells security operators a unique ID for this machine. This process can be scripted, but the key is that it is out-of-band and out of reach of configuration management. (Path: map/user-id/)

For security reasons we'd like the mapping to be valid for a limited time only, which currently needs to be managed by the out-of-band process, or worse, a security operator. Being able to set a expiry for the mapping would massively simplify the above scenario with mapping expiry  functionality while retaining control of the mapping in vault.

**Comment by jefferai** [comment]
This is supported in the new AppRole backend in 0.6.1, which deprecates App-ID.
