### ISSUE TITLE
PKI- tidy command unable to remove revoked certs

### ISSUE THREAD

**Issue by sabarisankarj** [hashicorp/vault#16733]
**Describe the bug**
Unable to remove revoked leaf certificates using tidy command

**To Reproduce**
1. Run following commands,

```
vault secrets enable test-pki -max-lease-ttl=87600h -default-lease-ttl=24h test-pki

vault write test-pki/root/generate/internal common_name=test.com ttl=8760h

vault write test-pki/roles/example allowed_domains=test@test.com allow_bare_domains=true

vault write test-pki/issue/example common_name=test@test.com

vault write test-pki/revoke serial_number=11:22:33:12:49:75:88:36:48:6b:65:80:de:3f:d7:d5:ea:a2:c5:f6

vault write test-pki/tidy tidy_cert_store=true tidy_revoked_certs=true
```

2. Issue: Vault UI still displays the revoked certificates

**Expected behavior**
Revoked certificates should be removed after tidy operation

**Environment:**
* Vault Server Version: 1.10.4
* Vault CLI Version (retrieve with `vault version`): v1.11.0
* Server Operating System/Architecture: Ubuntu 20.04

**Additional context**
Certificate is getting revoked, just not getting removed from UI

(@cipherboy: edited for formatting)

**Comment by cipherboy** [comment]
@sabarisankarj Has the certificate expired? Tidy will only remove revoked certificates once it is safe to do so, namely, after the certificate has expired as well.

**Comment by sabarisankarj** [comment]
@cipherboy yes it is revoked and also expired.

**Comment by cipherboy** [comment]
@sabarisankarj And is outside of the default 72h `safety_buffer` (so safety_buffer + notAfter is before the current system time)? Once I modify the `safety_buffer` down to say, `1s`, I see the certs pruned:

```
$ vault write test-pki/tidy tidy_cert_store=true tidy_revoked_certs=true safety_buffer=1s
WARNING! The following warnings were returned from Vault:

  * Tidy operation successfully started. Any information from the operation
  will be printed to Vault's server logs.

$ vault list test-pki/certs
Keys
----
51:1e:ee:da:32:22:6f:ee:42:73:3a:ba:3a:a4:42:8e:93:96:07:37
```

Only the root CA remains. But if I were to leave the default `safety_buffer=72h`, the certs remain:

```
$ vault write test-pki/revoke serial_number=$(vault write -field=serial_number test-pki/issue/example common_name=test@test.com)
Key                        Value
---                        -----
revocation_time            1660661932
revocation_time_rfc3339    2022-08-16T14:58:52.765575298Z
$ vault list test-pki/certs
Keys
----
51:1e:ee:da:32:22:6f:ee:42:73:3a:ba:3a:a4:42:8e:93:96:07:37
5f:d3:6a:61:de:a9:75:30:b6:aa:b7:ef:4f:55:25:f7:79:dd:a1:14
$ vault write test-pki/tidy tidy_cert_store=true tidy_revoked_certs=true 
WARNING! The following warnings were returned from Vault:

  * Tidy operation successfully started. Any information from the operation
  will be printed to Vault's server logs.

$ vault list test-pki/certs
Keys
----
51:1e:ee:da:32:22:6f:ee:42:73:3a:ba:3a:a4:42:8e:93:96:07:37
5f:d3:6a:61:de:a9:75:30:b6:aa:b7:ef:4f:55:25:f7:79:dd:a1:14
```

**Comment by sabarisankarj** [comment]
Using safety_buffer=1s cleared all revoked certs, thanks for the support.
