### ISSUE TITLE
Vault doesn't support the correctly named tls_cipher_suites TLS_ECDHE_*_WITH_CHACHA20_POLY1305_SHA256

### ISSUE THREAD

**Issue by nathkn** [hashicorp/vault#16782]
**Describe the bug**
When specifying the TLS cipher suites `TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256` and `TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256` as specified in [RFC7905](https://www.iana.org/assignments/tls-parameters/tls-parameters.xml), Vault fails to start with an "unsupported cipher" error.

**To Reproduce**
Set the tcp listener to use the above cipher suites:

```hcl
listener "tcp" {
...
  tls_cipher_suites = "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"
...
}
```
and you will see an error such as

```
error loading configuration from /etc/vault/config.hcl: error parsing 'listener': listeners.0 invalid value for tls_cipher_suites: unsupported cipher "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
```

**Expected behavior**
Vault should start up with the above ciphers.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.11.2
* Vault CLI Version (retrieve with `vault version`): 1.11.2
* Server Operating System/Architecture: Centos 7

**Additional context**
This bug happens because Go used to incorrectly list the ciphers without the `_SHA256` suffix, which must have carried over to the library Vault uses to look up the cipher: https://github.com/hashicorp/go-secure-stdlib/blob/1b80d53b4662d4b15ea0c23754dd81e3ae21d58b/tlsutil/tlsutil.go#L27. 

The golang git issue that brought it up is here: https://github.com/golang/go/issues/32061, and it was fixed in this commit: https://github.com/golang/go/commit/e2cac315082a9267135e96249b537d0bd0703175. 

I found this since the [docs state to look at the Go code to find which cipher suites are supported](https://www.vaultproject.io/docs/configuration/listener/tcp#tls_cipher_suites), which does include the `TLS_ECDHE_*_WITH_CHACHA20_POLY1305` cipher suites: https://go.dev/src/crypto/tls/cipher_suites.go 

The workaround is to not include the `_SHA256` suffix in the `tls_cipher_suites` listener config, in which case Vault does correctly start.

**Comment by kitography** [comment]
Thanks for this report!  I think it is fixed by @cipherboy , here: https://github.com/hashicorp/go-secure-stdlib/pull/44 , so I'm closing this issue, but feel free to reopen if you think we missed something.
