### ISSUE TITLE
migration of intermediate pkis fails in upgrade to vault 1.11

### ISSUE THREAD

**Issue by juliantaylor** [hashicorp/vault#16810]
**Describe the bug**
vault intermediate pki's created where the certificate was not set via the `intermediate/set-signed` api fail to migrate when updating to 1.11
The these intermediate pki's only have the private key set in the config/ca_bundle path but the migration code assumes it contains a certificate and fails in writeCaBundle in storage_migrations.go with an invalid PEM error as the pem of the migrationsInfo.legacyBundle is empty and it fails with `Error during migration of PKI mount: unable to parse certificate: invalid PEM`

**To Reproduce**
```
# with vault 1.10.2
vault -version
Vault v1.10.2
vault secrets enable -path pkitest pki
vault secrets enable -path pkitest-intermediate pki
vault write pkitest/root/generate/internal common_name=test organization=test
d=$(vault write -format=json pkitest-intermediate/intermediate/generate/exported common_name=test | jq -r .data.csr)
echo "$d" | vault write  pkitest/root/sign-intermediate csr=- 

# (! no pkitest-intermediate/intermediate/set-signed performed)

$ vault secrets list
Path                     Type         Accessor              Description
----                     ----         --------              -----------
cubbyhole/               cubbyhole    cubbyhole_5c217491    per-token private secret storage
identity/                identity     identity_ef493ee1     identity store
pkitest-intermediate/    pki          pki_7f75cf4e          n/a
pkitest/                 pki          pki_3a5d601c          n/a
sys/                     system       system_d7a45c44       system endpoints used for control, policy and debugging


# update to vault 1.11
# start vault 1.11
$ vault -version
Vault v1.11.2
$ curl -H "X-Vault-Token: $VAULT_TOKEN" $VAULT_ADDR/v1/pkitest-intermediate/ca/pem

vault log:
2022-08-22T16:12:20.941+0200 [INFO]  secrets.pki.pki_3a5d601c: performing PKI migration to new keys/issuers layout
2022-08-22T16:12:20.998+0200 [INFO]  secrets.pki.pki_3a5d601c: Migration generated the following ids and set them as defaults: issuer id=7c54759b-20ae-0980-ea50-a86e67eb2ca2 key id=92fdea97-3729-007b-c4e6-ec7302197950
2022-08-22T16:12:20.998+0200 [INFO]  secrets.pki.pki_3a5d601c: Scheduling PKI CRL rebuild.

2022-08-22T16:12:43.164+0200 [INFO]  secrets.pki.pki_7f75cf4e: performing PKI migration to new keys/issuers layout
2022-08-22T16:12:43.196+0200 [ERROR] secrets.pki.pki_7f75cf4e: Error during migration of PKI mount: unable to parse certificate: invalid PEM
```

**Expected behavior**
vault migration does not fail for intermediate pkis

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
storage "raft" {
  path = "/tmp/data"
  node_id = "raft_node_1"
}
listener "tcp" {
    address = "localhost:8200"
    tls_disable = true
}

cluster_addr = "http://127.0.0.1:8201"
disable_mlock = true

```

**Comment by juliantaylor** [comment]
In our actual vault instance which has been upgraded for at least 5 years we additionally have rollback errors on these pki's

```
[ERROR] rollback: error rolling back: path=ui/xx/sandbox-istio-be-sandbox-iz2-bap/ error="unable to parse certificate: invalid PEM"
```

And the endpoints do not respond anymore with following error:

```
* Can not create intermediate until migration has completed
```

**Comment by juliantaylor** [comment]
Would it be safe to simply delete those intermediate pki's? or could this leave garbage lying around due to the incomplete migration?

**Comment by cipherboy** [comment]
@juliantaylor In theory, yes, it should be OK to delete these since they strictly have keys and lack any signed certificate (so they probably weren't used). But @stevendpclark has a fix up, it should make it into the next releases (1.12 and 1.11) hopefully.

**Comment by stevendpclark** [comment]
Thanks @juliantaylor for reporting the issue to us!

As mentioned by @cipherboy a fix has now been merged into the 1.11 release branch, so the fix should make it in the next minor release of Vault. Closing this issue.

**Comment by juliantaylor** [comment]
thanks for the fast fix, we will try it asap

**Comment by juliantaylor** [comment]
We have applied the patch to our local instances and the migrations now proceeded without error and the pki endpoints are functional again, thanks again.
