### ISSUE TITLE
Website Download Anchor obsolete

### ISSUE THREAD

**Issue by Kloppi313** [hashicorp/vault#16829]
**Describe the bug**
The website [download](https://www.vaultproject.io/downloads) anchor (Release Information -> Changelog) links to Version 1.9.1.

**To Reproduce**
Visit [website](https://www.vaultproject.io/downloads), click link "Changelog"
![image](https://user-images.githubusercontent.com/36038231/186142755-87f27b25-c451-49c1-b795-6c5e511bdff6.png)

**Expected behavior**
Anchor to the corresponding version or without anchor.

**Environment:**
N/A

**Comment by thiskevinwang** [comment]
Thanks for reporting this @Kloppi313! We should have a fix for this out soon.

**Comment by thiskevinwang** [comment]
Hey @Kloppi313, we've updated the changelog link to simply point at the Changelog file on `main` — https://github.com/hashicorp/vault/blob/main/CHANGELOG.md

Let us know if this is sufficient!

**Comment by Kloppi313** [comment]
Super, thanks!
