### ISSUE TITLE
Go API `client.KVv2.Get` fails with missing custom_metadata error

### ISSUE THREAD

**Issue by theory** [hashicorp/vault#16870]
**Describe the bug**

Use of `client.KVv2(path).Get(cx, secPath)` fails with `error reading custom metadata for secret at nytimes/id-identity/versioned/data/try: metadata missing expected field "custom_metadata"`, but `client.Logical().Read(path + "/data/" + secPath)` works fine.

**To Reproduce**

1. Run `vault kv put mystuff/service/versioned/try mysecret=shhhhh`

2. Run this code:

    ``` go
	path := "mystuff/service/versioned"
	secPath := "try"
        secret, err := client.KVv2(path).Get(context.Background(), secPath)
	if err != nil {
		panic(err)
	}
	fmt.Printf("%#v\n", secret.Data["data"])
    ```

3. Observe the error:

    ```
    reading custom metadata for secret at nytimes/id-identity/versioned/data/try: metadata missing expected field "custom_metadata": map[created_time:2022-08-22T22:36:04.827312512Z deletion_time:0001-01-01 00:00:00 +0000 UTC destroyed:false version:1]
    ```

2. Run this code:

    ``` go
	path := "mystuff/service/versioned"
	secPath := "try"
        secret, err := client.Logical().Read(path + "/data/" + secPath)
	if err != nil {
		panic(err)
	}
	fmt.Printf("%#v\n", secret.Data["data"])
    ```

5. See no error

**Expected behavior**

No error expected.

**Environment:**
* Vault Server Version (retrieve with `vault status`): `1.8.11+ent`
* Vault CLI Version (retrieve with `vault version`): `v1.11.2`
* Server Operating System/Architecture: centos7/amd64

Vault server configuration file(s):

```hcl
# Will ask our team for this
```

**Additional context**

None.

**Comment by theory** [comment]
This corrects the error:

``` patch
--- kv_v2.saf.go	2022-08-24 13:37:15.000000000 -0400
+++ kv_v2.go	2022-08-24 13:37:45.000000000 -0400
@@ -125,7 +125,7 @@
 
 	cm, err := extractCustomMetadata(secret)
 	if err != nil {
-		return nil, fmt.Errorf("error reading custom metadata for secret at %s: %w", pathToRead, err)
+		// return nil, fmt.Errorf("error reading custom metadata for secret at %s: %w", pathToRead, err)
 	}
 	kvSecret.CustomMetadata = cm
 
```

Perhaps the API needs to detect the older version of the server that may not return custom metadata at all?

**Comment by Stolr** [comment]
Hey ,

Same issue here.

Is there any fix planned ?

Thanks

**Comment by f0cus3d** [comment]
Getting the same error , using similar code from https://github.com/hashicorp/vault-examples/blob/main/examples/auth-methods/approle/go/example.go

```
unable to read secret: error reading custom metadata for secret at ------  metadata missing expected field "custom_metadata"
```

**Comment by f0cus3d** [comment]
https://github.com/hashicorp/vault/blob/bcc79b7f5baf830907f7a20011767a50fcc62209/api/kv_v2.go#L112

Can we make custom metadata optional on Get ? I suspect for the most part if folks want metadata there could be a separate call for that?

**Comment by f0cus3d** [comment]
https://github.com/hashicorp/vault/blob/bcc79b7f5baf830907f7a20011767a50fcc62209/api/kv_v1.go#L14

v1 Get still works with approle auth if anyone else is looking for a workaround opposite doing a logical read, just provide the mount path as `yourMountPath/data`

**Comment by digivava** [comment]
Sorry for the issue here, folks! This was an oversight on my part in not accounting for older Vault servers. We're working on resolving this ASAP.
