### ISSUE TITLE
How to configure the oidc auth

### ISSUE THREAD

**Issue by mayankmike86** [hashicorp/vault#16973]
We are able to initialize/unseal and enable the vault using bellow code.

newres, err := client.Sys().Init(&intireq)
resseal, err := client.Sys().Unseal(“xxxxxxxxxxxxxxxxxxxxx”)
fmt.Println(“resseal:”, resseal)
enableopt := vault.MountInput{}
enableopt.Type = “oidc”
client.SetToken(“xxxxxxxxxxxxxxxxxx”)

err = client.Sys().EnableAuthWithOptions(“oidc”, &enableopt)
We can see oidc enabled in UI also. Now we need to configure the oidc, which if done from UI it is using below POST api with configs id: “oidc”, oidc_discovery_url:“xxxxxx”…

https://vault.xxxxxx.com/v1/auth/oidc/config
We need to configure the same from our GO code where we are using go client vault “[github.com/hashicorp/vault/api](http://github.com/hashicorp/vault/api)”

Not able to get the method for auth configuration need help on correct method.

**Comment by hsimon-hashicorp** [comment]
Hi there! We ask folks to post their questions and requests for help on our Discuss forum, as we prefer to use GitHub for bug reports and feature requests. You can find the Vault forum here: https://discuss.hashicorp.com/c/vault/30
I'm going to go ahead and close this issue now. Thanks!
