### ISSUE TITLE
List readable secrets in generic backend

### ISSUE THREAD

**Issue by grantr** [hashicorp/vault#170]
Getting a list of readable secrets from the generic secret backend would be useful for a FUSE implementation like keywhiz-fs. I don't see a way to do that currently. Maybe it could recognize wildcards in the secret path?

**Comment by sethvargo** [comment]
Closing as a duplicate of https://github.com/hashicorp/vault/issues/111. Let's track that issue please :smile:

**Comment by grantr** [comment]
Oops didn't see that one!
