### ISSUE TITLE
Error initializing listener of type tcp: listen tcp 1x.2xx.1xx.1xx:8200: bind: cannot assign requested address

### ISSUE THREAD

**Issue by reyyzzy** [hashicorp/vault#17016]
hi,im  just learning about vault and im running my vault in AWS linux.and i get a multiple error when i try to run a command,when i try to run this command `vault server -dev -dev-listen-address="1x.2xx.1xx.1xx:8200`"

i get this errorr:
```
Error parsing listener configuration.
Error initializing listener of type tcp: listen tcp 1x.2xx.1xx.1xx:8200: bind: cannot assign requested address
2022-09-06T09:05:57.039Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
2022-09-06T09:05:57.039Z [WARN]  no `api_addr` value specified in config or in VAULT_API_ADDR; falling back to detection if possible, but this value should be manually set
2022-09-06T09:05:57.040Z [INFO]  core: Initializing version history cache for core
```
this is my vault-config.hcl :

```
{
"listener": [{
"tcp": {
"address" : "0.0.0.0:8200",
"tls_disable" : 1
}
}],
"api_addr": "http://1x.2xx.1xx.1xx:8200",
"storage": {
    "file": {
    "path" : "opt/vault/data"
    }
 },
"max_lease_ttl": "10h",
"default_lease_ttl": "10h",
"ui":true
}
```

is there anything wrong?let me know please

**Comment by aphorise** [comment]
@reyyzzy you probably want to launch with something like:

```shell
vault server -dev -config=/etc/vault.d/vault.hcl
```

And exclude ~`-dev-listen-address`~. In your CLI launch parameters you are being explicit with an IP and in the config you are being generic with `0.0.0.0` that means all and that's likely trying to rebind to the same thing.

**Comment by hsimon-hashicorp** [comment]
Thanks, @aphorise! I agree, this sounds like the address is already in use (by the command or the config) and can't bind because of that. Let us know if changing your command line helps, @reyyzzy. :)

**Comment by aphorise** [comment]
Hey @reyyzzy - how did you progress?
Are you ok to close this issue now?

**Comment by Dorra-B** [comment]
In fact, the main problem is the 127.0.0.1:8200  used by another process.
Maybe vault.service is up and running and it is using the 8200 port.
1. `sudo systemctl stop vault.service`
2. vault server -dev -dev-listen-address="1x.2xx.1xx.1xx:8200
This should work.

If there is still the same error message , you have to do the following:
1.  `netstat -a |grep 8200`
If there is a port 8200 used, you have just to kill the process using it, so vault can take advantage of it:
2. `ps aux `
This command will show all the running processes where each has its own USER identified, CPU, PID, etc
3. `ps aux |grep 8200`
This command will show the process using the port you need to set free, keep in mind the PID of the process XZY (usually in the second column from the left)
4. `kill -XZY pid`
This command will Kill the process with pid

**Comment by aphorise** [comment]
>    `$ vault  server -dev -dev-listen-address="1x.2xx.1xx.1xx:8200`

IMO - it's better to have all settings (specific or all encompassing `0.0.0.0`) only via the configuration file and using the listener stanza therein; this way changes and explicit bind values are more evident than having them set explicitly via launch (eg: systemd unit file). Anyway there may be cases where you may have want to do it in-line via `-dev-listen-address` but in this cases you should avoid using `0.0.0.0` that will otherwise overlap as I'd mentioned earlier.

**Comment by hsimon-hashicorp** [comment]
It's been some time since we've heard from you on this issue, so I'm going to go ahead and close it now. Please feel free to open a new issue if you need. Thanks!
