### ISSUE TITLE
Compilation fails on OSX

### ISSUE THREAD

**Issue by jacob-koren** [hashicorp/vault#1706]
**jacob:src jacobkoren$ make**
go generate 
CGO_ENABLED=0 VAULT_TOKEN= VAULT_ACC= go test -tags='vault' $(go list ./... | grep -v /vendor/)  -timeout=120s -parallel=4
can't load package: package _/Users/jacobkoren/IdeaProjects/vault/src: cannot find package "_/Users/jacobkoren/IdeaProjects/vault/src" in any of:
	/usr/local/go/src/_/Users/jacobkoren/IdeaProjects/vault/src (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/_/Users/jacobkoren/IdeaProjects/vault/src (from $GOPATH)
api/logical.go:7:2: cannot find package "github.com/hashicorp/vault/helper/jsonutil" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/jsonutil (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/jsonutil (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/jsonutil (from $GOPATH)
audit/audit.go:4:2: cannot find package "github.com/hashicorp/vault/helper/salt" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/salt (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/salt (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/salt (from $GOPATH)
audit/audit.go:5:2: cannot find package "github.com/hashicorp/vault/logical" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/logical (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/logical (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/logical (from $GOPATH)
builtin/audit/file/backend.go:10:2: cannot find package "github.com/hashicorp/vault/audit" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/audit (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/audit (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/audit (from $GOPATH)
builtin/credential/app-id/path_login.go:11:2: cannot find package "github.com/hashicorp/vault/helper/policyutil" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/policyutil (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/policyutil (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/policyutil (from $GOPATH)
builtin/credential/app-id/backend.go:8:2: cannot find package "github.com/hashicorp/vault/logical/framework" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/logical/framework (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/logical/framework (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/logical/framework (from $GOPATH)
builtin/credential/approle/backend.go:7:2: cannot find package "github.com/hashicorp/vault/helper/locksutil" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/locksutil (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/locksutil (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/locksutil (from $GOPATH)
builtin/credential/approle/path_role.go:12:2: cannot find package "github.com/hashicorp/vault/helper/strutil" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/strutil (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/strutil (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/strutil (from $GOPATH)
builtin/credential/aws-ec2/client.go:10:2: cannot find package "github.com/hashicorp/vault/helper/awsutil" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/awsutil (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/awsutil (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/awsutil (from $GOPATH)
builtin/credential/cert/cli.go:7:2: cannot find package "github.com/hashicorp/vault/api" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/api (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/api (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/api (from $GOPATH)
builtin/credential/cert/path_crls.go:10:2: cannot find package "github.com/hashicorp/vault/helper/certutil" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/certutil (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/certutil (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/certutil (from $GOPATH)
builtin/credential/ldap/backend.go:9:2: cannot find package "github.com/hashicorp/vault/helper/mfa" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/mfa (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/mfa (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/mfa (from $GOPATH)
builtin/credential/ldap/cli.go:9:2: cannot find package "github.com/hashicorp/vault/helper/password" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/password (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/password (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/password (from $GOPATH)
builtin/credential/ldap/path_config.go:14:2: cannot find package "github.com/hashicorp/vault/helper/tlsutil" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/tlsutil (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/tlsutil (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/tlsutil (from $GOPATH)
builtin/logical/pki/cert_util.go:19:2: cannot find package "github.com/hashicorp/vault/helper/errutil" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/errutil (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/errutil (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/errutil (from $GOPATH)
builtin/logical/transit/policy.go:17:2: cannot find package "github.com/hashicorp/vault/helper/kdf" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/kdf (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/kdf (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/kdf (from $GOPATH)
cli/commands.go:6:2: cannot find package "github.com/hashicorp/vault/builtin/audit/file" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/audit/file (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/audit/file (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/audit/file (from $GOPATH)
cli/commands.go:7:2: cannot find package "github.com/hashicorp/vault/builtin/audit/syslog" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/audit/syslog (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/audit/syslog (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/audit/syslog (from $GOPATH)
cli/commands.go:11:2: cannot find package "github.com/hashicorp/vault/builtin/credential/app-id" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/credential/app-id (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/credential/app-id (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/credential/app-id (from $GOPATH)
cli/commands.go:12:2: cannot find package "github.com/hashicorp/vault/builtin/credential/approle" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/credential/approle (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/credential/approle (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/credential/approle (from $GOPATH)
cli/commands.go:13:2: cannot find package "github.com/hashicorp/vault/builtin/credential/aws-ec2" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/credential/aws-ec2 (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/credential/aws-ec2 (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/credential/aws-ec2 (from $GOPATH)
cli/commands.go:14:2: cannot find package "github.com/hashicorp/vault/builtin/credential/cert" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/credential/cert (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/credential/cert (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/credential/cert (from $GOPATH)
cli/commands.go:15:2: cannot find package "github.com/hashicorp/vault/builtin/credential/github" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/credential/github (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/credential/github (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/credential/github (from $GOPATH)
cli/commands.go:16:2: cannot find package "github.com/hashicorp/vault/builtin/credential/ldap" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/credential/ldap (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/credential/ldap (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/credential/ldap (from $GOPATH)
cli/commands.go:17:2: cannot find package "github.com/hashicorp/vault/builtin/credential/userpass" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/credential/userpass (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/credential/userpass (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/credential/userpass (from $GOPATH)
cli/commands.go:19:2: cannot find package "github.com/hashicorp/vault/builtin/logical/aws" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/logical/aws (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/logical/aws (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/logical/aws (from $GOPATH)
cli/commands.go:20:2: cannot find package "github.com/hashicorp/vault/builtin/logical/cassandra" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/logical/cassandra (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/logical/cassandra (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/logical/cassandra (from $GOPATH)
cli/commands.go:21:2: cannot find package "github.com/hashicorp/vault/builtin/logical/consul" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/logical/consul (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/logical/consul (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/logical/consul (from $GOPATH)
cli/commands.go:22:2: cannot find package "github.com/hashicorp/vault/builtin/logical/mongodb" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/logical/mongodb (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/logical/mongodb (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/logical/mongodb (from $GOPATH)
cli/commands.go:23:2: cannot find package "github.com/hashicorp/vault/builtin/logical/mssql" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/logical/mssql (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/logical/mssql (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/logical/mssql (from $GOPATH)
cli/commands.go:24:2: cannot find package "github.com/hashicorp/vault/builtin/logical/mysql" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/logical/mysql (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/logical/mysql (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/logical/mysql (from $GOPATH)
cli/commands.go:25:2: cannot find package "github.com/hashicorp/vault/builtin/logical/pki" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/logical/pki (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/logical/pki (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/logical/pki (from $GOPATH)
cli/commands.go:26:2: cannot find package "github.com/hashicorp/vault/builtin/logical/postgresql" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/logical/postgresql (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/logical/postgresql (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/logical/postgresql (from $GOPATH)
cli/commands.go:27:2: cannot find package "github.com/hashicorp/vault/builtin/logical/rabbitmq" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/logical/rabbitmq (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/logical/rabbitmq (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/logical/rabbitmq (from $GOPATH)
cli/commands.go:28:2: cannot find package "github.com/hashicorp/vault/builtin/logical/ssh" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/logical/ssh (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/logical/ssh (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/logical/ssh (from $GOPATH)
cli/commands.go:29:2: cannot find package "github.com/hashicorp/vault/builtin/logical/transit" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/builtin/logical/transit (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/builtin/logical/transit (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/builtin/logical/transit (from $GOPATH)
cli/commands.go:32:2: cannot find package "github.com/hashicorp/vault/command" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/command (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/command (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/command (from $GOPATH)
cli/commands.go:8:2: cannot find package "github.com/hashicorp/vault/command/server" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/command/server (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/command/server (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/command/server (from $GOPATH)
cli/commands.go:34:2: cannot find package "github.com/hashicorp/vault/meta" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/meta (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/meta (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/meta (from $GOPATH)
cli/commands.go:9:2: cannot find package "github.com/hashicorp/vault/version" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/version (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/version (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/version (from $GOPATH)
command/util.go:9:2: cannot find package "github.com/hashicorp/vault/command/token" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/command/token (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/command/token (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/command/token (from $GOPATH)
command/token_create.go:8:2: cannot find package "github.com/hashicorp/vault/helper/flag-kv" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/flag-kv (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/flag-kv (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/flag-kv (from $GOPATH)
command/server.go:27:2: cannot find package "github.com/hashicorp/vault/helper/flag-slice" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/flag-slice (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/flag-slice (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/flag-slice (from $GOPATH)
command/server.go:28:2: cannot find package "github.com/hashicorp/vault/helper/gated-writer" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/gated-writer (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/gated-writer (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/gated-writer (from $GOPATH)
command/audit_enable.go:9:2: cannot find package "github.com/hashicorp/vault/helper/kv-builder" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/kv-builder (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/kv-builder (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/kv-builder (from $GOPATH)
command/server.go:29:2: cannot find package "github.com/hashicorp/vault/helper/mlock" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/mlock (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/mlock (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/mlock (from $GOPATH)
command/generate-root.go:13:2: cannot find package "github.com/hashicorp/vault/helper/pgpkeys" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/pgpkeys (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/pgpkeys (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/pgpkeys (from $GOPATH)
command/generate-root.go:14:2: cannot find package "github.com/hashicorp/vault/helper/xor" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/xor (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/xor (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/xor (from $GOPATH)
command/server.go:30:2: cannot find package "github.com/hashicorp/vault/http" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/http (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/http (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/http (from $GOPATH)
command/init.go:14:2: cannot find package "github.com/hashicorp/vault/physical" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/physical (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/physical (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/physical (from $GOPATH)
command/server.go:34:2: cannot find package "github.com/hashicorp/vault/vault" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/vault (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/vault (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/vault (from $GOPATH)
helper/jsonutil/json.go:10:2: cannot find package "github.com/hashicorp/vault/helper/compressutil" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/compressutil (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/compressutil (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/compressutil (from $GOPATH)
helper/mfa/mfa.go:16:2: cannot find package "github.com/hashicorp/vault/helper/mfa/duo" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/mfa/duo (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/mfa/duo (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/mfa/duo (from $GOPATH)
http/handler.go:12:2: cannot find package "github.com/hashicorp/vault/helper/duration" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/helper/duration (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/helper/duration (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/helper/duration (from $GOPATH)
vault/core.go:22:2: cannot find package "github.com/hashicorp/vault/shamir" in any of:
	/Users/jacobkoren/IdeaProjects/vault/src/vendor/github.com/hashicorp/vault/shamir (vendor tree)
	/usr/local/go/src/github.com/hashicorp/vault/shamir (from $GOROOT)
	/Users/jacobkoren/IdeaProjects/vault/src/github.com/hashicorp/vault/shamir (from $GOPATH)
can't load package: package vendor/gopkg.in/mgo.v2/internal/sasl: no buildable Go source files in /Users/jacobkoren/IdeaProjects/vault/src/vendor/gopkg.in/mgo.v2/internal/sasl

**Comment by jefferai** [comment]
You should not be using GOROOT, as it almost always causes problems. It's also unusual to see Vault code in a directory called src so without further context it's hard to say what else is happening. You probably also want to 'make dev', not 'make'.

**Comment by jacob-koren** [comment]
I didn't set GOROOT, only GOPATH
jacob:~ jacobkoren$ env | grep GO
GOPATH=/Users/jacobkoren/IdeaProjects/vault/

I cloned the repository according to the README file

**Comment by jefferai** [comment]
If you cloned the repository according to the README it would be in a directory `$GOPATH/src/github.com/hashicorp/vault` -- but that's clearly not the case here. Paths matter in Go.

**Comment by jacob-koren** [comment]
Right. it works.
