### ISSUE TITLE
SSH-error Certificate does not contain an authorized principal

### ISSUE THREAD

**Issue by sabarisankarj** [hashicorp/vault#17063]
**Describe the bug**
Unable use ssh secret engine, failing with error "Certificate does not contain an authorized principal".

**To Reproduce**
Server side scripts:

```
curl -o /tmp/trusted-user-ca-keys.pem https://vault-test.com/v1/test-ssh-ca/public_key
sudo cp /tmp/trusted-user-ca-keys.pem /etc/ssh/
sudo chmod 644 /etc/ssh/trusted-user-ca-keys.pem
echo "TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem"  | sudo tee -a /etc/ssh/sshd_config
sudo service sshd restart
sudo useradd -m ssh-ca -s /bin/bash
```

Client side scripts:

```
vault login
vault write -field=signed_key test-ssh-ca/sign/login public_key=@/mnt/c/Users/userid/.ssh/vaultssh/id_rsa_test.pub valid_principals=ssh-ca > /mnt/c/Users/userid/.ssh/vaultssh/id_rsa_test.signed.pub
chmod 400 /mnt/c/Users/userid/.ssh/vaultssh/id_rsa_test*
ssh -i /mnt/c/Users/userid/.ssh/vaultssh/id_rsa_test.signed.pub ssh-ca@10.xx.xx.xxx
```

**Expected behavior**
Able to ssh to the sever.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.10.4
* Vault CLI Version (retrieve with `vault version`): v1.11.2
* Server Operating System/Architecture: Ubuntu 20.04

**Additional context**
secret engine configuration

```
vault read test-ssh-ca/roles/login
Key                            Value
---                            -----
algorithm_signer               rsa-sha2-256
allow_bare_domains             false
allow_host_certificates        false
allow_subdomains               false
allow_user_certificates        true
allow_user_key_ids             false
allowed_critical_options       n/a
allowed_domains                n/a
allowed_extensions             permit-pty,permit-port-forwarding,permit-agent-forwarding,permit-user-rc,permit-X11-forwarding
allowed_user_key_lengths       map[]
allowed_users                  ssh-ca
allowed_users_template         false
default_critical_options       map[]
default_extensions             map[permit-agent-forwarding: permit-port-forwarding: permit-pty:]
default_extensions_template    false
default_user                   ssh-ca
key_bits                       0
key_id_format                  n/a
key_type                       ca
max_ttl                        0s
ttl                            1h
```

(ams: edited for formatting)

**Comment by sabarisankarj** [comment]
Problem is with the sshd config file, commenting #AuthorizedPrincipalsFile /etc/ssh/auth_principals/%u in config make it work. Thanks for the support.

**Comment by cipherboy** [comment]
@sabarisankarj Ah interesting; I was wondering if that was perhaps the case but hadn't had time to reproduce this one yet to verify.

If you want to use authorized principals, I'd perhaps remove the `%u` and set it to a single file, rather than pointing it to a directory of files based on the username -- the username must still appear in the file for it to work, at least, from how I read the man pages.
