### ISSUE TITLE
Clarify UUID usage

### ISSUE THREAD

**Issue by jdelic** [hashicorp/vault#1707]
The current [documentation on app-ids](https://www.vaultproject.io/docs/auth/app-id.html) states:

> The app ID is a unique ID that maps to a set of policies. This ID is generated by an operator and configured into the backend. The ID itself is usually a UUID, but any hard-to-guess unique value can be used.

This opens additional questions: If it is an important security consideration that app-ids are hard to guess, then UUIDs are not the way to go. Specifically, [RFC 4122](https://www.ietf.org/rfc/rfc4122.txt) states in section 6:

> Do not assume that UUIDs are hard to guess; they should not be used as security capabilities identifiers whose mere possession grants access), for example.  A predictable random number source will exacerbate the situation.

So in my opinion the docs should be clarified in two ways:
- If it is a security consideration for the app-id auth backend on how hard the app-id is to guess (as for some applications it might be), UUIDs should probably be replaced by, for example, a diceware phrase or a simple base64 encoded string of random bytes retrieved from a good cryptographic RNG. I'm not sure how many bits of entropy usually end up in a standards-conformant UUID.
- On a related note, but this might deserve its own ticket: Since the token backend uses UUIDs, it should be clarified how Vault ensures that its own generated UUIDs are hard to guess.

**Comment by jefferai** [comment]
@jdelic You're assuming that UUIDs within Vault correspond to RFC 4122. In fact, they don't -- they're a 128-bit pure random number sourced from a CSRNG.

UUID is used as the display format only.

**Comment by jdelic** [comment]
@jefferai I don't see what this has to do with anything.

> You're assuming that UUIDs within Vault correspond to RFC 4122. In fact, they don't -- they're a 128-bit pure random number sourced from a CSRNG.

I'm assuming this precisely because the documentation doesn't state it anywhere. Instead it calls "128-bit pure random number sourced from a CSRNG" in a "UUID display format" a "UUID" which is a term commonly reserved for RFC4122 conformant strings. If you read my last sentence: The docs should clarify how Vault ensures that its own UUIDs are "hard to guess". I was never assuming that Vault internally uses UUIDs.

The second part of the ticket was:

> If it is a security consideration for the app-id auth backend on how hard the app-id is to guess (as for some applications it might be), UUIDs should probably be replaced [...]

And that point also still stands. Right now the app-id auth backend documentation coerces users to use "UUIDs" which *are* commonly guessable, while also saying that it is a security consideration to use "hard to guess" UUIDs without documenting what those security considerations are or what "hard to guess" UUIDs should be.

The docs need improvement and I think this ticket is still valid.

**Comment by jefferai** [comment]
Feel free to send a PR with suggested changes!
