### ISSUE TITLE
GPG Keys declined by Vault init

### ISSUE THREAD

**Issue by eyal-lupu** [hashicorp/vault#1710]
Hi,

Trying to init vault and providing a set of GPG public keys failed with the following error:

URL: PUT https://localhost:8200/v1/sys/init
Code: 400. Errors:

* Error setting up encryption for PGP message: openpgp: invalid argument: cannot encrypt to public key of type 17

This seems to be happening with DSA ELGamal keys (RSA ones are working fine).

Is this a bug or known behaviour?

Thanks

**Comment by jefferai** [comment]
It looks like this may be a bug in the golang openpgp library.

Potentially related issues:
https://github.com/golang/go/issues/12153
https://github.com/keybase/keybase-issues/issues/2019

Question, based on my research: does this work for you with *new* dsa/elgamal keys (like, created with a modern version of gpg)?

**Comment by jefferai** [comment]
Marking as 0.6.1 but may defer to 0.6.2.

**Comment by eyal-lupu** [comment]
Tested it with a new key - regenerated one now - and it works. Key generated with 2.0.22 using the following commands:

```
[user@host ~] gpg --gen-key
gpg (GnuPG) 2.0.22; Copyright (C) 2013 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Please select what kind of key you want:
   (1) RSA and RSA (default)
   (2) DSA and Elgamal
   (3) DSA (sign only)
   (4) RSA (sign only)
Your selection? 2
DSA keys may be between 1024 and 3072 bits long.
What keysize do you want? (2048) 
Requested keysize is 2048 bits
Please specify how long the key should be valid.
         0 = key does not expire
      <n>  = key expires in n days
      <n>w = key expires in n weeks
      <n>m = key expires in n months
      <n>y = key expires in n years
Key is valid for? (0) 
Key does not expire at all
Is this correct? (y/N) y

GnuPG needs to construct a user ID to identify your key.

Real name: dsa-test
Email address: 
Comment: 
You selected this USER-ID:
    "dsa-test"

Change (N)ame, (C)omment, (E)mail or (O)kay/(Q)uit? O
You need a Passphrase to protect your secret key.
```
The generated key is 'algo 17' as the ones failed:

```
[user@host ~]$ gpg --export dsa-test | gpg --list-packets 
:public key packet:
	version 4, algo 17, created 1470838518, expires 0
....
....
....

```
It makes thing a bit better for some but doesn't help for us owning old keys ...

**Comment by jefferai** [comment]
@eyal-lupu `It makes thing a bit better for some but doesn't help for us owning old keys ...` totally hear you there. We're discussing internally whether we want to switch to Keybase's fork of the `openpgp` library which fixes this for old keys, or not. There are reasons for and against.

**Comment by DylanFrese** [comment]
@eyal-lupu As a workaround, you can generate a new, throwaway GPG key, use that, and then decrypt the shard and re-encrypt it with your actual GPG key. After that the throwaway GPG keypair can be tossed.

**Comment by jefferai** [comment]
We've switched to the keybase openpgp fork, so this should work in 0.6.1.

**Comment by eyal-lupu** [comment]
:+1: 
Thanks
