### ISSUE TITLE
Add ability to alter the max-versions attribute from an existing KV Store version 2

### ISSUE THREAD

**Issue by francogu** [hashicorp/vault#17112]
**Is your feature request related to a problem? Please describe.**
I want to change the "max versions" of an existing KV store V2 using the vault command line.

**Describe the solution you'd like**
I want to be able to read and write the metadata for the a KV Store V2 from the client like using

```
vault kv metadata put max-versions=2 my_kv_store
vault kv metadata get max-versions my_kv_store
```

**Describe alternatives you've considered**

- Alternative is to set the versions at the level of key but it has to be done for each keys.
- Alternative is to trash the KV Store and recreate it with the max-versions at creation time but all the key would be lost
- Try to use the command line but got message that this is not supported maybe to due to wrong syntax
- Tried to use `vault write my_kv_store/config max_version=2` and `vault write my_kv_store/config` that show new value. However from the Web UI and behavior, it still shows/uses the original setting from creation time (unlimited versions)

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**
Here we are using Vault with namespaces feature enabled.

**Comment by francogu** [comment]
The correct command that is working as alternative is:

`vault write my_kv_store/config max_versions=2`

Old versions, over the limit, will be purged when a new version is created.

**Comment by francogu** [comment]
Does it make sense to keep this one open as it can be managed by "vault write" alternative and not directly with "vault kv metadata" ?

**Comment by mpalmi** [comment]
As you discovered, this is a mount-wide configuration and can be set via `vault write <path to mount>/config`. Going to go ahead and close this out for now. Thanks for the report!

**Comment by foxmeyson** [comment]
@francogu Your discovery was very useful to me, thank you!
