### ISSUE TITLE
Token helper doesn't work with TOTP vault login

### ISSUE THREAD

**Issue by lgrawet** [hashicorp/vault#17111]
**Describe the bug**
Token helper doesn't work with TOTP vault login.
.vault-token is not created/filled with the VAULT_TOKEN.

**To Reproduce**
1. Enable and enforce identity/mfa/method/totp
2. Run `vault login -method userpass username=testuser`
3. Enter one time password
4. Run `vault secrets list`
5. It will fail as .vault-token is not handled during vault login.

**Expected behavior**
User is logged thanks to .vault-token

**Environment:**
* Vault Server Version (retrieve with `vault status`):
Version         1.11.0
* Vault CLI Version (retrieve with `vault version`):
Vault v1.11.3 (17250b25303c6418c283c95b1d5a9c9f16174fe8), built 2022-08-26T10:27:10Z
* Server Operating System/Architecture:
Debian 9.13 x64
Vault server configuration file(s):

```hcl
# Full configuration options can be found at https://www.vaultproject.io/docs/configuration

ui = true

#mlock = true
#disable_mlock = true

storage "file" {
  path = "/opt/vault/data"
}

#storage "consul" {
#  address = "127.0.0.1:8500"
#  path    = "vault"
#}

# HTTP listener
#listener "tcp" {
#  address = "127.0.0.1:8200"
#  tls_disable = 1
#}

# HTTPS listener
listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/opt/vault/tls/tls.crt"
  tls_key_file  = "/opt/vault/tls/tls.key"
}

# Enterprise license_path
# This will be required for enterprise as of v1.8
#license_path = "/etc/vault.d/vault.hclic"

# Example AWS KMS auto unseal
#seal "awskms" {
#  region = "us-east-1"
#  kms_key_id = "REPLACE-ME"
#}

# Example HSM auto unseal
#seal "pkcs11" {
#  lib            = "/usr/vault/lib/libCryptoki2_64.so"
#  slot           = "0"
#  pin            = "AAAA-BBBB-CCCC-DDDD"
#  key_label      = "vault-hsm-key"
#  hmac_key_label = "vault-hsm-hmac-key"
#}```

**Additional context**
None

**Comment by ncabatoff** [comment]
Hi @lgrawet,

Thanks for reporting this issue.  As it happens, it's already been reported in https://github.com/hashicorp/vault/issues/16928, so I'm going to close this one as a duplicate.

**Comment by lgrawet** [comment]
Thank you, I didn't find it before opening the issue.
