### ISSUE TITLE
Kubernetes config returns error from square/go-jose

### ISSUE THREAD

**Issue by colin-pm** [hashicorp/vault#17119]
**Describe the bug**
One of the integration tests for HVAC caught an issue introduced in Vault 1.11 (hvac/hvac#858). A POST to the configure endpoint for the Kubernetes auth method with [`token_reviewer_jwt`](https://www.vaultproject.io/api-docs/auth/kubernetes#token_reviewer_jwt) as a invalid JWT produces a different error message. Normally, errors due to screen scraping exception messages would be shrugged off and updated, but the new error message appears to be from `square/go-jose`, a library that's used by Vault.

```
1 error occurred:
        * square/go-jose: compact JWS format must have three parts
```

I'm not sure if this is expected. I've typically believed that it's bad practice to leak errors from internal libraries in API error messages, but I would also say that this error message is a little more descriptive. I'll defer to the Vault team to close this issue if this is intended behavior.

**To Reproduce**
The unit test that consistently reproduces this issue can be found with the link below:

If desired, the test could be run from the root directory of hvac, checked out to the tip of develop.
```
pytest tests/integration_tests/api/auth_methods/test_kubernetes.py
```
However, I think any other method that doesn't validate the JWT before sending the request to Vault would catch this error. The basic steps are outlined below.

1. Start up a dev Vault server
2. Enable the kubernetes auth method
3. Configure the kubernetes auth method (`POST` to `/auth/kubernetes/config`) with the following parameters
    - `kubernetes_host="https://192.168.99.100:8443"`
    - `kubernetes_ca_cert="-----BEGIN CERTIFICATE-----\\n.....\\n-----END CERTIFICATE-----"`
    - `token_reviewer_jwt="reviewer_jwt"`

Running the test on Vault <1.11 and 1.11 will produce the different error messages.

**Expected behavior**
The previous error message:
```
1 error occurred:
        * not a compact JWS
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault v1.11.3 (17250b25303c6418c283c95b1d5a9c9f16174fe8), built 2022-08-26T10:27:10Z
* Vault CLI Version (retrieve with `vault version`): None, using hvac (hvac/hvac@7b94991e7c370756f1b2e4a7a4ffc602aea958ec) which uses the REST API
* Server Operating System/Architecture: Ubuntu 20.04.4 LTS on x86_64 GNU/Linux

Vault server configuration file(s):

None - Running tests against dev version of Vault stood up for integration testing.

**Additional context**
Apologies for creating all these issues at once. The HVAC team has recently started integration testing the library against the latest versions of Vault and found a few issues. I figured it'd be good to document what I think may be unintended upstream changes for the Vault team to review.

**Comment by hsimon-hashicorp** [comment]
Hi folks! Is this still an issue in newer versions of Vault? Please let me know so I can bubble it up accordingly. Thanks!

**Comment by raskchanky** [comment]
Since it's been awhile with no response, I'm going to close this issue. Please reopen if there's more to add here.
