### ISSUE TITLE
LDAP auth with DUO doesn't seem to resolve template variables for the `username_format` field

### ISSUE THREAD

**Issue by xaque208** [hashicorp/vault#17123]
**Describe the bug**

When configuring DUO as MFA on 1.11, the selection of `username_format` doesn't appear to resolve template variables that should be available.

**To Reproduce**
1. Configure an LDAP auth method `vault write auth/ldap/config \
    url="ldaps://ldap.auth.svc.cluster.example" \
    userattr=uid \
    userdn="ou=people,dc=example" \
    groupdn="ou=group,dc=example" \
    groupfilter="(&(objectClass=groupOfUniqueNames)(uniqueMember={{.UserDN}}))" \
    groupattr="cn" \
    binddn="cn=vault,ou=services,dc=example" \
    bindpass='secret' \
    certificate=@ca.pem \
    insecure_tls=false \
    starttls=false
`
2. Configure DUO as MFA.  I couldn't work out how to do this via the CLI, and the docs were not much help, so I used the ui.
3. Set `"{{alias.name}}"` as the `username_format` field.
4. Run `vault login -method=ldap username=user`
5. See error
```
Error making API request.

URL: POST https://vault.auth.svc.cluster.example:8200/v1/sys/mfa/validate
Code: 403. Errors:

* failed to satisfy enforcement example. error: 2 errors occurred:
	* no value could be found for one of the template directives
	* login MFA validation failed for methodID: [59eeef7a-c468-4bf8-0a08-9f2121eaae63]
```

Poking around in the UI I can see the entity in question, and there is indeed an alias with a name.  I expect to be able to use this in the template string.

**Expected behavior**
I expect to receive a push notification on my phone.

**Environment:**
* Vault Server Version (retrieve with `vault status`): `1.11.0`
* Vault CLI Version (retrieve with `vault version`): `Vault v1.11.3 ('17250b25303c6418c283c95b1d5a9c9f16174fe8+CHANGES'), built 2022-08-26T10:27:10Z`
* Server Operating System/Architecture: `Linux/x86_64`

Vault server configuration file(s):

**Additional context**
If I leave the `username_format` field blank, then I do get a URL back from DUO that allows me to register the user.  If I proceed with registration, I have a new user account in DUO by the name of the entity in vault, which is not desirable.  The username in LDAP already matches a user in DUO, and so the username_format field should be able to resolve from the alias name in order to pass the correct information to DUO for user recognition.

Let me know of any further detail needed.

**Comment by kstinster** [comment]
We have the save issue with Vault Server  1.11.3

We tried the different combination of username_format

- with username_format is blank -- we got entity id as username in duo logs, and DUO urls to register new users.
- with  "{{alias.name}}" - we got the same error  "no value could be found for one of the template directives"
- with  username_format like  j.smith(real enrolled duo user) and thats works, only for one user.

it seems like a bug or we need clarification how to use  username_format

**Comment by kstinster** [comment]
looked more carefully at  doc https://www.vaultproject.io/api-docs/secret/identity/mfa/duo#username_format

make it work by setting user_format to {{identity.entity.aliases.auth_ldap_a931al1.name}}, without quotes

**Comment by xaque208** [comment]
I got a chance to test this and it worked.  Note that the `auth_ldap_a931al1` is the id of the auth mount.  Thanks for the assist.
