### ISSUE TITLE
Support for consul events on path changes

### ISSUE THREAD

**Issue by far-blue** [hashicorp/vault#1712]
As Vault doesn't have support for watching values in a path like consul does it can be hard to decide how and when to check for new values or changes. Rather than try to replicate the functionality of consul in vault, a reasonable option might be to make use of consul/serf events. It would be helpful if it was possible to configure certain paths and actions (e.g. add, update, delete on path secret/wibble/*) so they generate a serf/consul event with a specified name and value.

**Comment by magiconair** [comment]
A possible downside of this approach is that you then need to run both consul and vault to have this behavior.

**Comment by far-blue** [comment]
Yes, this is true. However, consul is the Hashicorp recommended HA storage option for vault (the others being community supported) and Vault already does extra stuff if using Consul - auto-init and service/healthcheck registration.

Maybe this suggestion could be extended to support other types of event trigger as well such as updating a counter or timestamp in a key/value store location so it can work with other K/V stores such as ZooKeeper and etcd.

**Comment by jefferai** [comment]
I think this is something we'd like to be able to support but needs a lot of thought on doing it in a correct/secure/scalable way. Marking for future!

**Comment by jefferai** [comment]
We don't have plans to support this right now in Consul events. Eventually, but not soon, we hope to have an eventing system. Closing for now as it's on our roadmap (but a bit far away).
