### ISSUE TITLE
How to get currently active leases

### ISSUE THREAD

**Issue by ethan256** [hashicorp/vault#17129]
The vault [api documentation](https://developer.hashicorp.com/vault/api-docs/system/leases#list-leases) uses the `LIST` method when getting the list of leases, but the method is not a standard HTTP method. I would like to debug that breakpoint in POSTMAN, how can I do it?

**Comment by hsimon-hashicorp** [comment]
Hi there! I'd recommend posting this question over in our Discuss forums, found here: https://discuss.hashicorp.com/c/vault/30
We like to keep the GitHub issues solely for bug reports or enhancement requests. Thanks for understanding!
