### ISSUE TITLE
List Teams in Github Auth Backend using HTTP API

### ISSUE THREAD

**Issue by gkhasel1** [hashicorp/vault#1713]
Basically I want to be able to list the teams I have configured policies for in the github auth backend. 

Lets say I POST to `auth/github/map/teams/some-team-name` and `auth/github/map/teams/some-other-team-name` I want to do a GET on `auth/github/map/teams?list=true` and get those teams back in the `data` block of the response (kind of like how aws-ec2 auth backend allows you to get roles).

fwiw, right now if I do a GET to `auth/github/map/teams` without the list=true part I get a response like 

```
{
    'warnings': None, 
    'renewable': False,
    'auth': None, 
    'lease_duration': 0, 
    'wrap_info': None, 
    'data': {}, 
    'lease_id': ''
}
```

even though doing a GET on a specific team does return the teams configuration data as expected. I want the data section in the above response to list the teams I have configured if possible.

Maybe this is already possible and I just don't know how to do it?

**Comment by gkhasel1** [comment]
I tried the cli just now and got this
```
$ vault list auth/github/map/teams
Error reading auth/github/map/teams/: Error making API request.
URL: GET http://127.0.0.1:8200/v1/auth/github/map/teams/?list=true
Code: 500. Errors:
* 1 error(s) occurred:
* unsupported path
```
im guessing this just isnt supported

**Comment by jefferai** [comment]
It's not supported at this point, no.

**Comment by ekristen** [comment]
I wouldn't be opposed to having a way of listing what mappings exist. I use GitHub auth a lot with different teams.

**Comment by xh3b4sd** [comment]
This seems to apply to listing auth backends in general as well. The HTTP API works as documented.

```
$ curl -s https://<endpoint>/v1/sys/auth -H "X-Vault-Token: <token>" | jq .
{
  "github/": {
    "description": "",
    "type": "github"
  },
  "token/": {
    "description": "token based credentials",
    "type": "token"
  }
}
```

The Vault CLI does not help to list these information, because it uses an additional HTTP query. 

```
$ vault list sys/auth
Error reading sys/auth/: Error making API request.

URL: GET https://<endpoint>/v1/sys/auth/?list=true
Code: 500. Errors:

* 1 error(s) occurred:

* unsupported path
```

```
$ curl -s https://<endpoint>/v1/sys/auth/\?list\=true -H "X-Vault-Token: token" | jq .
{
  "errors": [
    "1 error(s) occurred:\n\n* unsupported path"
  ]
}
```

Also read does nothing here, which might be anyway the wrong command.

```
$ vault read sys/auth
Key	Value
---	-----
```

**Comment by xh3b4sd** [comment]
I upgraded to `0.6.2` and for me listing auth backends seems to work now. 

```
$ vault list sys/auth
No value found at sys/auth/
```

```
$ vault read sys/auth
Key   	Value
---   	-----
token/	map[type:token config:map[default_lease_ttl:0 max_lease_ttl:0] description:token based credentials]
```

I am only confused by the fact that the `read` subcommand is used to list information and the `list` subcommand seems to not find the desired information. I think `list` should list information and read should provide detailed information about specific secrets/identities.

**Comment by jefferai** [comment]
@xh3b4sd `vault auth -methods` does what you want. Your question is separate from the OP's.

**Comment by irlevesque** [comment]
Is there _any_ way to access the mapping @jefferai? How do organizations today audit which groups have which access via the github auth backend?

**Comment by jefferai** [comment]
@irlevesque There is not currently, no. I believe most groups use code-driven configuration to ensure specific groups.

**Comment by irlevesque** [comment]
@jefferai I just noticed that https://github.com/hashicorp/vault/pull/2261 resolves https://github.com/hashicorp/vault/issues/2239 which is basically the same issue as this one. Apparently this made it to the 0.6.5 release back in February.

**Comment by jefferai** [comment]
Cool, thanks for the reminder!
