### ISSUE TITLE
master branch doesn't show auth  mounts

### ISSUE THREAD

**Issue by skippy** [hashicorp/vault#1716]
master (e57af52b41a0f94109167bc1261df72596d2c220)
```shell
$ vault auth
Token (will be hidden): 
Successfully authenticated! You are now logged in.
<SCRUBBED>
$ vault mounts
Path  Type  Default TTL  Max TTL  Description
$ vault write -format json pki/internal-services/issue/vault common_name=active.vault.service.consul ip_sans=127.0.0.1
# returns expected hash
```

rc1 behaves as expected
```shell
$ vault auth
Token (will be hidden): 
Successfully authenticated! You are now logged in.
<SCRUBBED>
$ vault mounts
Path  Type  Default TTL  Max TTL  Description
aws/                    aws        system       system     
consul/                 consul     system       system     
cubbyhole/              cubbyhole  n/a          n/a        per-token private secret storage
pki/internal-services/  pki        system       315360000  pki for internal-services
secret/                 generic    system       system     generic secret storage
sys/                    system     n/a          n/a        system endpoints used for control, policy and debugging
$ vault write -format json pki/internal-services/issue/vault common_name=active.vault.service.consul ip_sans=127.0.0.1
# returns expected hash
```

**Comment by vishalnayak** [comment]
Hi @skippy,

That's strange. Can you also post the server logs as well?
I am not able to reproduce it on the master.

Is there anything at all that you are doing differently?

**Comment by skippy** [comment]
I'll get that right over to you (the only thing I am doing behind the scenes is running TLS, and the ENV variables are set for this to work (hence why they are not being passed in on the CLI)

**Comment by skippy** [comment]
@vishalnayak I was running a 3-vault cluster, with 2 of the 3 being rc-1, including the leader... I'll roll the whole cluster over to master and see what happens

**Comment by jefferai** [comment]
'vault mounts' has never shown auth mounts. It doesn't in either of your examples...

**Comment by skippy** [comment]
yep, I wasn't expecting it to show auth mounts, just secret mounts.  I literally just flipped the binaries and saw different results

**Comment by jefferai** [comment]
@skippy Don't roll the cluster yet.

**Comment by jefferai** [comment]
@skippy Sorry, just wanted to check on something. Everything is fine. The way that the CLI parses the data returned from the server has changed in RC2. At the API level everything is the same, in terms of the JSON structures and the function signatures, but the code inside the API tracks current Vault and now relies on something we changed there -- meaning all should be fine when you upgrade your remaining nodes to RC2!

**Comment by skippy** [comment]
ah @jefferai I just did (no worries) and you're right... once the Leader was running e57af52, the mounts showed for the calling client.

it may be worth making a note in the CHANGELOG.md that an older client cannot communicate with a rc2 client.

sorry folks for the false alarm!  closing

**Comment by jefferai** [comment]
@skippy FYI I changed this so it's backwards compatible again.

**Comment by skippy** [comment]
thanks @jefferai !
