### ISSUE TITLE
Failover takes 40 seconds when killing the active node (without SIGTERM)

### ISSUE THREAD

**Issue by jacob-koren** [hashicorp/vault#1719]
I launched two vault nodes in HA mode with consul as backend.
When I send the active node SIGTERM followed by SIGKILL it's responding as expected with the standby node becomes active very quickly.
But, when I send the active node SIGKILL without SIGTERM, it takes ~40 seconds for the standby node to become active

Am I doing something wrong here? I know this is not the proper way to kill a service but sometimes it could happen.

config:

```

backend "consul" {
  address = "0.0.0.0:8500"
  path = "vault-local"
  scheme = "http"
  service = "vault-local"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}

telemetry {
  statsite_address = "statsite:10120"
  disable_hostname = true
}

disable_mlock = true
```

**Comment by jefferai** [comment]
It's pretty normal for distributed services to have a delay period when the active node dies. The way Vault works is it uses a distributed lock from the configured backend; if the active node dies uncleanly, the lock has to time out before another node can grab it.

40 seconds sounds on the high side to me, but we use Consul defaults so I'm not sure what's expected. You may want to ask on the Consul list if that sounds like a normal lock session timeout.

**Comment by jacob-koren** [comment]
Why is it not configurable?

```
const (
	// DefaultLockSessionName is the Session Name we assign if none is provided
	DefaultLockSessionName = "Consul API Lock"

	// DefaultLockSessionTTL is the default session TTL if no Session is provided
	// when creating a new Lock. This is used because we do not have another
	// other check to depend upon.
	DefaultLockSessionTTL = "15s"

	// DefaultLockWaitTime is how long we block for at a time to check if lock
	// acquisition is possible. This affects the minimum time it takes to cancel
	// a Lock acquisition.
	DefaultLockWaitTime = 15 * time.Second

	// DefaultLockRetryTime is how long we wait after a failed lock acquisition
	// before attempting to do the lock again. This is so that once a lock-delay
	// is in effect, we do not hot loop retrying the acquisition.
	DefaultLockRetryTime = 5 * time.Second

	// DefaultMonitorRetryTime is how long we wait after a failed monitor check
	// of a lock (500 response code). This allows the monitor to ride out brief
	// periods of unavailability, subject to the MonitorRetries setting in the
	// lock options which is by default set to 0, disabling this feature. This
	// affects locks and semaphores.
	DefaultMonitorRetryTime = 2 * time.Second

	// LockFlagValue is a magic flag we set to indicate a key
	// is being used for a lock. It is used to detect a potential
	// conflict with a semaphore.
	LockFlagValue = 0x2ddccbc058a50c18
) 
```

**Comment by jefferai** [comment]
Hi Jacob,

I didn't say it wasn't configurable, I said Vault uses Consul's defaults. As you can see, those defaults should mean that the timeout occurs at 15 seconds -- hence why I suggest asking the Consul devs.

**Comment by jacob-koren** [comment]
I mean why not expose all consul configuratiion to the backend section of the vault config file.

**Comment by jefferai** [comment]
Because nobody has done it or (until now) asked for it!

PRs welcome...

**Comment by jacob-koren** [comment]
If vault hasn't been tested on Mesos than it does not support docker. Mesos is one of the primary ways to run containers, not a corner case.

**Comment by skippy** [comment]
@jefferai how about at least documenting the signals?  There is an page on environment variables and perhaps one on signals would be warranted?

**Comment by jefferai** [comment]
@skippy The upgrade instructions (https://www.vaultproject.io/docs/install/upgrade.html) do say to use `SIGINT` or `SIGTERM` to properly shut down Vault.

**Comment by skippy** [comment]
Yep, I know.  I think that having a page under configuration would be good.  As an operator, I probably wouldn't look at the upgrade doc until needed, but rather at the configuration tab.  

I remember going through this exact exercise when I first started to setup Vault.  I had to grep the source code to see what signals I should be using (it is nice the docs are in the repo, as I remember the upgrade doc showing up in grep :)

**Comment by jefferai** [comment]
There's an argument to be made that signal information doesn't belong under the configuration section either, since it's not a configuration parameter. :-)

**Comment by skippy** [comment]
Signal handling is related though, as it impacts the runtime behavior of the app (granted, you can't modify the impact, which is what you can do with configuration parameters)

**Comment by merri-j** [comment]
I struggled with figuring out how to properly stop a running vault instance for awhile as well. I was updating to a TLS configuration, and needed to stop and restart. This was before the upgrade docs were written, but I do feel it is worth mentioning somewhere in the Internals or the Getting Started doc. Not everyone will be upgrading.

**Comment by slackpad** [comment]
Linking to https://github.com/hashicorp/vault/issues/2949, which is probably a duplicate.

**Comment by jefferai** [comment]
Closing in favor of #2949
