### ISSUE TITLE
Cannot start 'vault server -dev' in Windows 8.1 x64

### ISSUE THREAD

**Issue by Mattie112** [hashicorp/vault#172]
I cannot start 'vault server -dev' in Windows 8.1 x64

>C:\Windows\system32>vault version
>Vault v0.1.1-dev (074dcaadac2e0a46ae28f6d491885165b7431aae+CHANGES)
>
>C:\Windows\system32>vault server -dev
>Error initializing dev mode: Error: exit status 127
>
>sh: C:BINvault.exe: command not found
>
>
>C:\Windows\system32>

This is by running in an elevated commandprompt. Also vault is added to my system path. This is btw from the windows binary, I did not build vault myself.

**Comment by sethvargo** [comment]
Hi @Mattie112 

I believe this has been fixed in https://github.com/hashicorp/vault/pull/139 and should be available in the next release. Can you try building from master and verify? Thanks!

**Comment by mitchellh** [comment]
Let us know if it isn't but #139 should work.
