### ISSUE TITLE
Permission denied using Vault CLI in Vault raft-storage server

### ISSUE THREAD

**Issue by alok183** [hashicorp/vault#17216]
**Describe the bug**
Created the cluster following the steps https://github.com/hashicorp/learn-vault-raft/tree/main/raft-storage/local.
Not able to run the CLI commands , getting 'permission denied' error.

![image](https://user-images.githubusercontent.com/24774682/191110303-469b1cbd-de65-4b1a-8b29-29525cceef27.png)

**To Reproduce**
1. Run `vault login <token>`
2. Run `vault operator raft list-peers`

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.10.0
* Vault CLI Version (retrieve with `vault version`): 1.10.0
* Server Operating System/Architecture: Linux

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by mpalmi** [comment]
Thanks for the report!

I was able to reproduce by setting my `VAULT_TOKEN`. This effectively negates the `vault login <root_token>` and makes you an unauthenticated user. The behavior is to be expected and is the reason for that `WARNING!` right after `vault login`.

Can you try unsetting your `VAULT_TOKEN` environment variable and try again? Please let me know if the issue still persists after that!

**Comment by alok183** [comment]
Thanks, it worked.
