### ISSUE TITLE
Example in approle documentation produces error

### ISSUE THREAD

**Issue by Hosweay** [hashicorp/vault#1722]
The vault write example to generate the secret-id in the documentation, https://github.com/hashicorp/vault/blob/master/website/source/docs/auth/approle.html.md#get-a-secretid-issued-against-the-approle, produces the following error:

root@a119c56b6364:/# vault write auth/approle/role/testrole/secret-id
write expects at least two arguments
Usage: vault write [options] path [data]

This is after creating the testrole in the example.

The POST example works but the vault write example does not seem to. This is using the rc2 binary

root@a119c56b6364:/# vault version
Vault v0.6.1-rc2 ('25e45c004d95c6539d952e86c96287d585c09c46+CHANGES')

**Comment by jefferai** [comment]
Hi @Hosweay 

When using the CLI, for `vault write` commands that do not actually pass any data, use the `-f` flag: `vault write -f auth/approle/role/testrole/secret-id`. That should do it!

**Comment by mhurne** [comment]
I believe the example in question was updated to include -f in #1735

**Comment by Hosweay** [comment]
Looks like the example was corrected. Thanks.
