### ISSUE TITLE
PATCH metadata unsupported operation

### ISSUE THREAD

**Issue by hagarz** [hashicorp/vault#17221]
**Describe the bug**
Vault API and command tool returns `405` `unsupported operation` when attempting to patch secret **metadata**

**To Reproduce**
Steps to reproduce the behavior taken from [documentation](https://www.vaultproject.io/docs/secrets/kv/kv-v2)
1. Run `vault kv metadata put -mount=secret -custom-metadata=foo=abc -custom-metadata=bar=123 my-secret`
2. Run `vault kv metadata patch -mount=secret -custom-metadata=foo=def my-secret`
3. See error:

```
Error writing data to secret/metadata/my-secret: Error making API request.

URL: PATCH http://127.0.0.1:8200/v1/secret/metadata/my-secret
Code: 405. Errors:

* 1 error occurred:
	* unsupported operation
```

**Expected behavior**
Patch custom metadata

**Environment:**
* Vault Server Version (retrieve with `vault status`): **1.9.2**
* Vault CLI Version (retrieve with `vault version`): **v1.11.0**
* Server Operating System/Architecture: docker linux

**Comment by ms140569** [comment]
This issue is not vault CLI related, but happens with CURL as well:

**vault-access-example.bash:**

```
#!/usr/bin/env bash

curl -s \
     -H "X-Vault-Request: true" \
     -H "X-Vault-Namespace: ${VAULT_NAMESPACE}" \
     -H "X-Vault-Token: $(vault print token)" \
     --header "Content-Type: application/merge-patch+json" \
     --request PATCH \
     --data @vault-metadata.json \
     ${VAULT_ADDR}/v1/frumpy/metadata/cluster1/production
```


**vault-metadata.json:**

```
{
  "custom_metadata": {
    "foo": "matthias"
  }
}
```

```
$ ./vault-access-example.bash
{"errors":["1 error occurred:\n\t* unsupported operation\n\n"]}
```

**Comment by ccapurso** [comment]
According to the server information provided, you are running Vault 1.9.2. HTTP `PATCH` support for KVv2 metadata was not added until version [1.10.0](https://github.com/hashicorp/vault/blob/main/CHANGELOG.md#1100). Thus, your server must be running 1.10.0 at a minimum in order to be able to patch metadata.
