### ISSUE TITLE
[Plugin Portal] Plugin Submission - Google Apigee

### ISSUE THREAD

**Issue by bstraehle** [hashicorp/vault#17253]
Please provide details for the plugin to be listed. All fields are required for a submission to be included in the [Plugin Portal](https://www.vaultproject.io/docs/plugin-portal) page.

**Plugin Information**
Name as it would appear listed: Google Apigee
Plugin type (secrets/auth/database): secrets
Repository link: 
https://github.com/bstraehle/vault-plugin-secrets-apigee

**Comment by mpalmi** [comment]
This relates to #17249.
