### ISSUE TITLE
Documentation lacks path between 'dev' server and real server

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/vault#1729]
The documentation talks about the **-dev** server for testing and then goes onto **seal/unseal**. But there's no clear (documented) path between the two.

For example, how do you setup a 'real' server? How do you configure and 'init' it?

**Comment by jefferai** [comment]
Hi @FransUrbo ,

The link to the configuration documentation is in the left navbar along with the page with dev information. Do you have suggestions for how this should be connected better?

**Comment by FransUrbo** [comment]
There needs to be steps in between. As in, answering the (example) questions in the original post.

There is basically NO information on how to setup/configure a real (non '-dev') server. But between the **Seal/Unseal* (under the *Basic Concepts*) and **Hight Availability** there's plenty. But _nothing_ between **"Dev" server** and **Seal/Unseal**).

**Comment by jefferai** [comment]
The Basic Concepts sections address particular concepts, and do not contain detailed configuration information. The configuration information is in the section directly below the Basic Concepts section, labeled "Configuration".

**Comment by FransUrbo** [comment]
That does not contain any information on how to get things going either. The *Basic Concepts* mentions the ``vault init`` command briefly, but does not go into any detail. That seems to be the perfect information to put in a *Basic Concepts -> Initialize "Real" Server* (or similar).

**Comment by dstroot** [comment]
FWIW Some information about how to use certs for those of us who aren't cert experts would be useful.  I am able to generate them with:

`openssl req -x509 -newkey rsa:2048 -nodes -keyout cert/vault.key -out cert/vault.crt -days 730 -subj "/CN=127.0.0.1:8200"` 

and I have successfully achieved the server seeing them:
```
2016-08-24T16:59:02.105449033Z ==> Vault server configuration:
2016-08-24T16:59:02.105551362Z 
2016-08-24T16:59:02.105586412Z                  Backend: file
2016-08-24T16:59:02.105693515Z               Listener 1: tcp (addr: "127.0.0.1:8200", tls: "enabled")
2016-08-24T16:59:02.105728499Z                Log Level: info
2016-08-24T16:59:02.105762912Z                    Mlock: supported: true, enabled: true
2016-08-24T16:59:02.105800708Z                  Version: Vault v0.6.0
2016-08-24T16:59:02.105818085Z 
2016-08-24T16:59:02.105890752Z ==> Vault server started! Log data will stream in below:
```

But haven't been able to get my client to connect.  Does the client need to see the certs somehow also?  E.g. not sure how to use VAULT_CLIENT_KEY, VAULT_CLIENT_CERT...

**Comment by loghen41** [comment]
Considering this ticket is still open, I would agree with @dstroot.  As a user coming from a non-security background, I found the lack of information about TLS configuration a rather difficult hurdle to overcome. 

I will admit that the Basic Concepts page does a good job of explaining a very basic dev server initialization, and the https://www.vaultproject.io/docs/configuration/index.html page does explicitly display most of the necessary configuration options.  However, I feel it would be helpful to provide 2-3 "Advanced Concepts" pages that walk though different potential production level deployments.  

I say this with a grain of salt though, as I know that the vault team is completely swamped with requests to the code base and the documentation. (so it may not be the highest of priorities)

**Comment by jefferai** [comment]
Closing -- please feel free to submit documentation PRs with suggested changes!
