### ISSUE TITLE
Vault fails to start with the consul backend

### ISSUE THREAD

**Issue by centromere** [hashicorp/vault#173]
The [docs](https://www.vaultproject.io/docs/config/index.html#advertise_addr) say:
> For backends that support HA, this is the address to advertise to other Vault servers in the cluster for request forwarding. If this isn't specified, it'll default to the first private address on the machine running Vault.

Based on that statement, I assume that if I leave out `advertise_addr`, it should start up just fine, but it doesn't:

    # vault server -config /etc/vault.conf
    Error initializing core: missing advertisement address
    # cat /etc/vault.conf 
    backend "consul" {
    }
    
    listener "tcp" {
      tls_disable = 1
    }

**Comment by sethvargo** [comment]
Hi @centromere 

This was fixed in https://github.com/hashicorp/vault/pull/133 and will be available in the next release. Sorry for the confusion!
