### ISSUE TITLE
Documentation about secret backends incomplete

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/vault#1730]
Documentation about secret backend 'Cassandra' (and several other of the secret backends) does not contain mount and configuration option.

The AWS backend do, please make all of the documentation "look alike".

**Comment by jefferai** [comment]
PRs welcome!

**Comment by FransUrbo** [comment]
Is this how issues are treated - close them if you don't feel like doing it?

**Comment by jefferai** [comment]
The ticket is too broad in concept to address any specific unit of work, and I don't want to leave this open as a meta ticket until some unknown standard is met. Issues for specific documentation tasks are fine. Pull requests to actually address those are even better!

**Comment by FransUrbo** [comment]
If you rather me open ten-fifteen specific tickets for each backend that's missing information, I guess I can do that. However, sorting the documentation seems to be _one_ ticket.

**Comment by jefferai** [comment]
I would prefer that you open tickets with specific enhancement requests. Not simply "improve documentation for X", but actual actionable items.
