### ISSUE TITLE
Feature UI Improvement: dynamic search and filter for Secret Engines list

### ISSUE THREAD

**Issue by DGKolev** [hashicorp/vault#17325]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when scrolling up and down in the Secrets Engines list (100's of entries that we have) to find the secret i am looking for

**Describe the solution you'd like**
Please add dynamic search/filter box on top of the Secrets page (/ui/vault/secrets) so it filters the list automatically on every keystroke to narrow down the matches

**Describe alternatives you've considered**
N/A

**Explain any additional use-cases**
Have a Secrets Engines list 100+ entries long. Try looking for particular engine by scrolling. Not efficient when in hurry. Search/Filter for the Secrets Engines list will greatly improve usability.

**Additional context**

<img width="1438" alt="Screen Shot 2022-09-27 at 10 59 05 AM" src="https://user-images.githubusercontent.com/87820806/192562197-8517a3db-15e5-4b02-a86d-275e3d66caf3.png">

**Comment by draggeta** [comment]
I know the team doesn't consider this a priority (or at least, actual search, not just filtering the displayed list), but I would love for this to happen. Right now we're using this in prod, but it is a pain when using Vault for non-automation passwords.

**Comment by Monkeychip** [comment]
@DGKolev thank you for the issue, this is currently [in progress](https://github.com/hashicorp/vault/pull/20481)! Looks like we'll be aiming for the 1.14 release.
