### ISSUE TITLE
Can't start NewTestCluster

### ISSUE THREAD

**Issue by camaeel** [hashicorp/vault#17324]
**Describe the bug**
I tried to use vault.NewTestCluster method to run server to test my application against it. 

I set up Go application like in the Gist: https://gist.github.com/camaeel/36e25e577aeaa74f947b6a5d800b44ef 

When I try to run `go test` it can't be built:
```
# github.com/shirou/gopsutil/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:132:1: note: 'IOMasterPort' has been explicitly marked deprecated here
# github.com/shirou/gopsutil/host
smc_darwin.c:75:41: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
# github.com/hashicorp/vault/vault
../../../go/pkg/mod/github.com/hashicorp/vault@v1.11.3/vault/dynamic_system_view.go:231:9: cannot use c (variable of type *pluginClient) as type pluginutil.PluginClient in return statement:
        *pluginClient does not implement pluginutil.PluginClient (missing Reload method)
../../../go/pkg/mod/github.com/hashicorp/vault@v1.11.3/vault/mount_util.go:50:9: cannot use extendedSystemViewImpl{…} (value of type extendedSystemViewImpl) as type extendedSystemView in return statement:
        extendedSystemViewImpl does not implement extendedSystemView (missing ListVersionedPlugins method)
../../../go/pkg/mod/github.com/hashicorp/vault@v1.11.3/vault/plugin_catalog.go:291:54: not enough arguments in call to pluginutil.MultiplexingSupported
        have (context.Context, *grpc.ClientConn)
        want (context.Context, grpc.ClientConnInterface, string)
../../../go/pkg/mod/github.com/hashicorp/vault@v1.11.3/vault/policy_store.go:257:67: cannot use sysView (variable of type *dynamicSystemView) as type logical.SystemView in argument to NewPolicyStore:
        *dynamicSystemView does not implement logical.SystemView (missing ListVersionedPlugins method)
FAIL    dummy [build failed]
```

**To Reproduce**
1. Download code from gist https://gist.github.com/camaeel/36e25e577aeaa74f947b6a5d800b44ef 
2. `go mod download`
3. `go test -v`

**Expected behavior**
Tests should be built correctly and should finish with success. 

**Environment:**
* Vault Server Version (retrieve with `vault status`): N/A
* Vault CLI Version (retrieve with `vault version`): N/A
* Server Operating System/Architecture: MacOs 12.6/arm64

Vault server configuration file(s):
N/A

**Additional context**

**Comment by camaeel** [comment]
I suspect that this is some incompatibility between go packages. Because if I switched to:
```
github.com/hashicorp/vault@v1.11.1
github.com/hashicorp/vault/api v1.7.2 // indirect
github.com/hashicorp/vault/sdk v0.5.3 // indirect
```
all is fine.

**Comment by camaeel** [comment]
I narrowed down that changing github.com/hashicorp/vault/sdk from v0.5.3 to v0.6.0 is probably the source of the issue.

**Comment by mpalmi** [comment]
Thanks for the report!

Unfortunately we decided some time ago to stop supporting `go.mod` imports of our project. This is the last official tag that we support for this usecase: https://github.com/hashicorp/vault/releases/tag/last-go-modable

I am going to go ahead and close this issue. Hopefully this isn't too much of an inconvenience!
