### ISSUE TITLE
TOTP method MFA generate QR, that Android google authenticator does not support (cods, that it generate does not fit to vault)

### ISSUE THREAD

**Issue by hennadii2012** [hashicorp/vault#17329]
**Describe the bug**
TOTP method MFA generate QR, that Android google authenticator does not support (cods, that it generate does not fit to vault)
On IOS such problem is absent,

**To Reproduce**
1. Turn on MFA for LDAP login method (or userpassword). Encryption SHA512 or SHA256 or SHA1
1. Generate TOTP MFA QR
2. Scan it, using google authenticator (latest version) for Android 
3. Try to login (you will get error, which tall, that code is incorrect)
4. Scan the same code, using google authenticator for IOS
5. Try to login (you will not have problems)

**Expected behavior**
Login with second factor to vault, using Google Authenticator for Android

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.11.0
* Vault CLI Version (retrieve with `vault version`): 1.11.0
* Server Operating System/Architecture: docker 20.10.12 on ubuntu 20.04 x64

Vault server configuration file(s):

```hcl
storage "raft" {
  path    = "/vault/file"
  node_id = "vault1"


  retry_join {
    leader_tls_servername   = "vault1.example.com"
    leader_api_addr         = "https://vault1.example.com:8200"
    leader_ca_cert_file     = "/opt/vault/tls/vault-ca.pem"
    leader_client_cert_file = "/opt/vault/tls/vault-cert.pem"
    leader_client_key_file  = "/opt/vault/tls/vault-key.pem"
  }
  retry_join {
    leader_tls_servername   = "vault2.example.com"
    leader_api_addr         = "https://vault2.example.com:8200"
    leader_ca_cert_file     = "/opt/vault/tls/vault-ca.pem"
    leader_client_cert_file = "/opt/vault/tls/vault-cert.pem"
    leader_client_key_file  = "/opt/vault/tls/vault-key.pem"
  }
  retry_join {
    leader_tls_servername   = "vault3.example.com"
    leader_api_addr         = "https://vault3.example.com:8200"
    leader_ca_cert_file     = "/opt/vault/tls/vault-ca.pem"
    leader_client_cert_file = "/opt/vault/tls/vault-cert.pem"
    leader_client_key_file  = "/opt/vault/tls/vault-key.pem"
  }
}
listener "tcp" {
  address            = "0.0.0.0:8200"
  cluster_addr       = "0.0.0.0:8201"
  tls_cert_file      = "/opt/vault/tls/vault-cert.pem"
  tls_key_file       = "/opt/vault/tls/vault-key.pem"
  tls_client_ca_file = "/opt/vault/tls/vault-ca.pem"
  tls_cipher_suites  = "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
}
telemetry {
  prometheus_retention_time = "15m"
  disable_hostname = true
}
api_addr          = "https://vault1.example.com:8200"
cluster_addr      = "https://vault1.example.com:8201"
ui                = true
disable_mlock     = true
default_lease_ttl = "168h"
max_lease_ttl     = "720h"
log_level         = "Error"
seal "gcpckms" {
  credentials = "/opt/vault/vault.json"
  project     = "project"
  region      = "global"
  key_ring    = "keyring"
  crypto_key  = "key-ring"
}

```

**Comment by hghaf099** [comment]
Thanks for filing this issue. Would you please share your MFA configuration that caused the issue? There is a consideration to make for Android which is documented [here](https://developer.hashicorp.com/vault/docs/enterprise/mfa/mfa-totp#configuration). It basically says that Google Authenticator for Android supports only SHA1 as the value of algorithm.

**Comment by hennadii2012** [comment]
Thanks for your answer. You are absolutely right. I did not see this point in doc on vault install and did not check later. Thank you. It is really main reason of the problem. In our case we use SHA512 algorithm
