### ISSUE TITLE
vault token cli command fails when using a token helper

### ISSUE THREAD

**Issue by dr4Ke** [hashicorp/vault#17358]
**Describe the bug**
When using a token helper, as [documented](https://www.vaultproject.io/docs/commands/token-helper),
the `vault token` or any command that use the existing token is failing. The error message is:
> Error [action]: configured Vault token contains non-printable characters and cannot be used

I used the helper script that is in the documentation and a custom one (in python) with the same behavior.

If I use the very same token without the helper, everything works as expected.

**To Reproduce**
1. Configure a helper as in the [documentation](https://www.vaultproject.io/docs/commands/token-helper)
2. Run `vault login....`
3. Run `vault token lookup`
4. See the error:
> Error looking up token: configured Vault token contains non-printable characters and cannot be used

**Expected behavior**
I expect the same behavior using a token helper or not.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.11.2
* Vault CLI Version (retrieve with `vault version`): 1.11.2
* Server Operating System/Architecture: GNU/Linux x84_64

Vault server configuration file(s):
```hcl
token_helper = "/home/user/bin/vault-token-helper.ruby"
```

**Additional context**
N/A

**Comment by froque** [comment]
I had a similar problem. Check for end of line characters in the token.

**Comment by dr4Ke** [comment]
That's what I thought too. But the helper script is correctly **not** sending an end of line character, when I use it manually.

Also I'd expect the actual documentation example to be correct about that.

**Comment by hsimon-hashicorp** [comment]
Hi @dr4Ke - could you provide more information on how we can repro this? We're currently having some difficulties there. Thanks!

**Comment by nix-power** [comment]
i have the same issue using the following token-helper
`cat ~/.vault-helpers/helper.py                                                                                                                                                                                                                        06:03:51
#!/usr/local/bin/python3

import json
import os
import sys

if "VAULT_ADDR" not in os.environ:
  print("No VAULT_ADDR environment variable set. Set it and run me again!", file=sys.stderr)
  sys.exit(100)

try:
  with open(os.path.join(os.environ["HOME"], ".vault_tokens")) as f:
    tokens = json.load(f)
except IOError:
  # file doesn't exist so create a blank dictionary for it
  tokens = {}

if len(sys.argv) < 2:
  print("Error: Missing argument. Expected 'get', 'store', or 'erase'.")
  sys.exit(1)

command = sys.argv[1]

if command == "get":
  if os.environ['VAULT_ADDR'] in tokens:
    print(tokens[os.environ['VAULT_ADDR']])
  else:
    print("Error: No token found for VAULT_ADDR")
  sys.exit(0)
elif command == "store":
  tokens[os.environ['VAULT_ADDR']] = sys.stdin.read()
elif command == "erase":
  if os.environ["VAULT_ADDR"] in tokens:
    del tokens[os.environ['VAULT_ADDR']]
else:
  print("Error: Invalid command. Expected 'get', 'store', or 'erase'.")
  sys.exit(1)

with open(os.path.join(os.environ["HOME"], ".vault_tokens"), "w") as f:
  json.dump(tokens, f)`
  
This is in MacOS with GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)

**Comment by dr4Ke** [comment]
Hi.
In your script @nix-power, I guess you should add the `end=''` parameter to the `print()` call, because we're supposed to send the token alone without a newline character at the end.

@hsimon-hashicorp , trying to reproduce the issue with a local server, I realize that it's my shell environment that is producing this issue. For a reason I don't understand, the vault helper doesn't use the current VAULT_ADDR env var to store the token in the file. I suppose that's the source of my issue. I'll dig into that and come back.

**Comment by nix-power** [comment]
Adding end='' to print() function did the trick. Thank you

**Comment by dr4Ke** [comment]
In my case, it was an `echo` command in the shell initialization file. I didn't realize that vault would load a full shell to execute my helper script. It's working as expected for me now. I'll close this issue then.
