### ISSUE TITLE
Vault UI Auto-Login without Namespace

### ISSUE THREAD

**Issue by ileeds** [hashicorp/vault#17355]
**Describe the bug**
As per the recommendation [here](https://github.com/hashicorp/vault/issues/5107#issuecomment-413411072), we are using the `wrapped_token` query parameter to the `logout` endpoint in order to automatically log in. This works as expected it the client is already logged into the UI, i.e., the client is logged out of the UI, the wrapped token is unwrapped, and the client is logged into the UI with the unwrapped token.
However, this does not work if the client is **not** already logged into the UI. The token is successfully unwrapped once, but then the UI attempts to unwrap it again (with the HTTP response `{"errors":["wrapping token is not valid or does not exist"]}`), and the UI presents:
```
Error
Token unwrap failed: wrapping token is not valid or does not exist
```
Interestingly, if the `namespace` query parameter is present, the wrapped token will only be unwrapped once regardless of whether the client is logged into the UI, and the flow succeeds.

**To Reproduce**
1. If signed in, sign out of the Vault UI
2. Access the UI via `<vault_url>:8200/ui/vault/logout?wrapped_token=<wrapped_token_value>`
3. See error

**Expected behavior**
Regardless of whether the client is signed into the Vault UI, navigating to the UI via `<vault_url>:8200/ui/vault/logout?wrapped_token=<wrapped_token_value>` should result in the client logging in successfully.

**Environment:**
* Vault Server Version: 1.11.2
* Server Operating System/Architecture: docker.io/vault:1.11.2

Vault server configuration file(s):

```hcl
plugin_directory = "/usr/local/libexec/vault"
ui = true
max_lease_ttl = "8760h"
```

**Additional context**
While the `auth` endpoint does work for clients in the logged out state, it does not work for clients already logged in. We would like a single endpoint that works regardless of whether the client is signed into the Vault UI.

**Comment by zofskeez** [comment]
@ileeds thanks for reporting this. I've prepared a fix for the logout url but also discovered that the `wrapped_token` query parameter can be used on the auth url to automatically login as well. Try using `<vault_url>:8200/ui/vault/auth?wrapped_token=<wrapped_token_value>`. I tested it on 1.11.2 as well and it works for me.
