### ISSUE TITLE
Vault API Explorer does not send query param 

### ISSUE THREAD

**Issue by MinDBreaK** [hashicorp/vault#17383]
**Describe the bug**
The API Explorer does not send the query params to the server.

**To Reproduce**
1. Open Vault UI
2. Open the console
3. Type `api` then `enter`
4. Make a request to `​/sys​/metrics` with `format=prometheus`
5. The format is still JSON and the query is not sent. The generated cURL command does not include the parameter.
 
**Expected behavior**
The param is sent.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
   ```
    Key                      Value
    ---                      -----
    [...]
    Initialized              true
    Sealed                   false
    Version                  1.11.3
    Build Date               2022-08-26T10:27:10Z
    Storage Type             file
    HA Enabled               false
   ```

* Vault CLI Version (retrieve with `vault version`):
    ```
    Vault v1.11.3 (17250b25303c6418c283c95b1d5a9c9f16174fe8), built 2022-08-26T10:27:10Z
    ```
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
storage "file" {
  path = "/opt/vault"
}

listener "tcp" {
  address     = "0.0.0.0:8200"
  x_forwarded_for_authorized_addrs = "ipv4/range,[ipv6/range]"
}

seal "awskms" {
  region     = "region"
  kms_key_id = "key-arn"
}
ui=true

telemetry {
  disable_hostname = true
}
```

**Comment by zofskeez** [comment]
Thanks for the report @MinDBreaK. This was fixed in #18743.
