### ISSUE TITLE
HTTP API yaml support

### ISSUE THREAD

**Issue by philsttr** [hashicorp/vault#1739]
It would be great if the HTTP API supported input/output in yaml format.

The client should be able to specify the input format via the `Content-type` header, and the output format desired via the `Accept` header.  Defaults can be json, of course.

The use case is so that clients only have to deal with yaml, and never have to perform yaml/json transcoding.  This would be particularly helpful for infrastructure-style clients, or front-ends to vault, for which users are commonly reading/writing values (as yaml is much nicer to work with than json by humans).

I understand that clients can perform transcoding, but this feels like something that could be solved once in the vault server, rather than requiring all clients that support yaml to transcode to json.

**Comment by jefferai** [comment]
Closing as this will not be supported.
