### ISSUE TITLE
Trouble init-ing vault, with no explanation

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#174]
```
$ vault init -key-shares=5 -key-threshold=2
Error initializing Vault: Error making API request.

URL: PUT http://localhost:8200/v1/sys/init
Code: 400. Errors:

* Vault is already initialized

$ curl http://localhost:8500/v1/kv/?recurse
<nothing>
```

Vault config: 
```
backend "consul" {
    scheme = "http"
}

listener "tcp" {
    address = "0.0.0.0:8200"
    tls_disable = 1
}
```

Vault startup:
```
==> Vault server configuration:

         Log Level: info
             Mlock: supported: true, enabled: true
           Backend: consul (HA available)
 Advertise Address: http://10.88.0.1:8200
        Listener 1: tcp (addr: "0.0.0.0:8200", tls: "disabled")

==> Vault server started! Log data will stream in below:
```

**Comment by jefferai** [comment]
Actually, it gets weirder. I'm not sure what the issue is:

```
$ curl http://localhost:8500/v1/kv/?recurse
<nothing>

$ vault init -key-shares=5 -key-threshold=2
Error initializing Vault: Error making API request.

URL: PUT http://localhost:8200/v1/sys/init
Code: 400. Errors:

* Vault is already initialized
```

Vault config: 
```
backend "consul" {
    scheme = "http"
}

listener "tcp" {
    address = "0.0.0.0:8200"
    tls_disable = 1
}
```

**Comment by mitchellh** [comment]
Hm, so the way we check for this error is to check the existence of a "file" in the backend storage. But Vault does caching and its likely hitting a cache right now. This is some sort of bug but to fix this you'll likely need to restart Consul.

**Comment by mitchellh** [comment]
Sorry, restart Vault.

**Comment by jefferai** [comment]
I'll try restarting vault; I just want to mention that I've never used Consul's KV store before this, so it seems unlikely that anything is there. (And you can see from the output above that there isn't anything in the KV store.)

Update: restarting Vault fixed this. I think I know what caused the problem, because I can reproduce it: if you encounter an error when running init (in my case, using `key-threshold=1`), then Vault gets into and stays in a bad state even if you fix the error, and even with nothing in the KV store.

**Comment by mitchellh** [comment]
@jefferai Ah, great find. We'll take a look.

**Comment by jefferai** [comment]
@mitchellh So after trying this again, I am getting slightly different output: on a bad init, I am now seeing some entries in the KV store, whereas you can see from the output above that the first time I saw *no* entries in the KV store. This may have been a case of caching as you suggested; it's possible that after trying it the first time with a bad key-threshold value, I deleted the values from the KV, but then was unable to re-run init because Vault had cached the fact that the file existed.

**Comment by armon** [comment]
@jefferai I just pushed https://github.com/hashicorp/vault/commit/05ae758208cff69b71a63f1d1d9cd8d0ab6b8511 and https://github.com/hashicorp/vault/commit/eedd63a10552fce6b82e52db94b913d2d2d1cd1c which should fix this!

**Comment by jefferai** [comment]
Neat, thanks!
