### ISSUE TITLE
core: persist(Mount/Auth/Audit) function. Using two iteraiton

### ISSUE THREAD

**Issue by valli0x** [hashicorp/vault#17402]
Who do you use two iteration in function persistMount in mount.go?
https://github.com/hashicorp/vault/blob/61707d56d51b4b9454e6f47111c398d1d47bf189/vault/mount.go#L1295

https://github.com/hashicorp/vault/blob/61707d56d51b4b9454e6f47111c398d1d47bf189/vault/mount.go#L1301-L1322

What do you think about this pr?
#17220

**Comment by mpalmi** [comment]
Thanks for opening the issue @valli0x! I've been meaning to get back to the PR. Typically we try to avoid cosmetic changes. This provides an improvement in success case, but not for failures. Either way, I will get around to merging this later today or tomorrow. Thank you for your patience!

**Comment by mpalmi** [comment]
Going to go ahead and close this issue out. The [PR](https://github.com/hashicorp/vault/pull/17220) has been [merged]( https://github.com/hashicorp/vault/commit/85edc2bcc24efc1c5c28561e040b7d328eee4c92). Thanks again!
