### ISSUE TITLE
Login Enforcement: let choose between 2 MFA solution

### ISSUE THREAD

**Issue by sycured** [hashicorp/vault#17451]
**Is your feature request related to a problem? Please describe.**
Actually, when activating MFA, the login enforcement applies a logical AND when selecting multiple MFA.

From the documentation:

> If there are multiple login enforcements, each one needs to be satisfied before a login attempt succeeds. (https://www.vaultproject.io/api-docs/secret/identity/mfa/login-enforcement#create-a-login-enforcement)

**Describe the solution you'd like**
Permits to apply a logical OR

For example, when using username/password, I want to have the choice between Duo and TOTP because if I've no more battery on my smartphone, I can still have my TOTP

**Describe alternatives you've considered**
Having a crazy setup:
- userpass: user/password with TOTP
- userpassd: user/password with DUO
This is crazy also for the entity because it's not only 1 alias for userpass but 2 with possible 2 different passwords… honestly, it's really a bad solution

**Comment by hghaf099** [comment]
@sycured Thanks for reporting this issue. The logical OR is still possible. If you define one login enforcement and include two MFA method IDs in the configuration, then, you can decide which one to use. However, logical AND is enforced if for each MFA method, you define a separate login enforcement. I am going to close this issue for now. Please feel free to reopen this one or open a new one with new findings. Thanks.
