### ISSUE TITLE
Some intro/vs/kms.html wording is inconsistent and wordy

### ISSUE THREAD

**Issue by willfaught** [hashicorp/vault#1745]
>Vault and KMS differ in the scope of problems they are trying to solve. The KMS service is focused on securely storing encryption keys and supporting cryptographic operations (encrypt and decrypt) using those keys.

- Inconsistent: KMS is referred to as "KMS" in the first sentence, but "the KMS service" in the second sentence
- Redundant: "the KMS service" expands to "the Key Management Service service"

**Comment by jefferai** [comment]
Fixed, thanks!
