### ISSUE TITLE
Please enable Fedora 37 builds

### ISSUE THREAD

**Issue by dngray** [hashicorp/vault#17489]
**Describe the bug**
Please enable Fedora 37 builds for Vault, seems to be [nothing](https://rpm.releases.hashicorp.com/fedora/37/x86_64/stable/repodata/repomd.xml) in the repository right now.

**Comment by cipherboy** [comment]
Per https://communityblog.fedoraproject.org/fedora-linux-37-schedule/, Fedora 37 isn't yet out and isn't slated until later this month. I don't know that we typically enable pre-release distros, but we can check with Rel Eng and make sure it is enabled around that time.

**Comment by dngray** [comment]
Wouldn't it be good for a bit of pre-release testing?

Presently I rolled forward my ostree to 37 for a newer systemd, having to make do with static binary of vault for the moment.

**Comment by mpalmi** [comment]
@dngray I've followed up internally and it looks like we'll be adding support for Fedora 37 as soon as the GA is released (either 10/18 or the fallback date of 10/25). I'm going to go ahead and close this issue out. If you have any problems after the official release, please let us know!
