### ISSUE TITLE
Error This is a standby Vault node but can't communicate with the active node via request forwarding. Sign in at the active node to use the Vault UI.

### ISSUE THREAD

**Issue by assiakhateeb** [hashicorp/vault#17495]
Got this error when trying to login to vault.
Anyone knows reason and how to solve the error?

![Screenshot from 2022-10-11 19-29-29](https://user-images.githubusercontent.com/39053503/195148491-dd9657bf-cac5-4938-a4a3-091f2d0120a9.png)

Thanks

**Comment by hsimon-hashicorp** [comment]
Hi there! This looks like a question, which you may have better luck with on our Discuss forum, located here: https://discuss.hashicorp.com/c/vault/30
We prefer to use GitHub for bug reports and feature requests. It looks like the server you connected to for your UI is not your primary node in your HA configuration. Try connecting to your primary node in the UI, and then you should be able to log in. I'm going to go ahead and close this issue, but please do feel free to post on Discuss if you have more questions. Thanks! :)
