### ISSUE TITLE
RethinkDB backend

### ISSUE THREAD

**Issue by kureikain** [hashicorp/vault#1757]
Hi,

We are not on AWS, and we use RethinkDB as our main storage. I have look into some code for MongoDB backend and I think it wasn't too hard to do the same for RethinkDB.

I just want to raise a ticket to see if this is something the team consider a good feature that can be merged? If so, I probably work on a PR for it.

**Comment by jefferai** [comment]
Sure, a RethinkDB backend would be great!

**Comment by ekristen** [comment]
Just read that RethinkDB is shutting down. ;(

**Comment by jefferai** [comment]
Where'd you read that?

**Comment by ekristen** [comment]
I can't find the original article, but here is one from hacker news, comment from Slava (https://news.ycombinator.com/item?id=12641936) 

Looks like the commercial entity behind RethinkDB is shutting down, but they are working on continuity for the open-source project, so the project could live on.

**Comment by jefferai** [comment]
Closing because 😿

**Comment by jippi** [comment]
didn't rethinkdb just go open source? https://www.rethinkdb.com/
