### ISSUE TITLE
Unable to get a kv secret the same name as the secret engine using vault kv cli command

### ISSUE THREAD

**Issue by wxdao** [hashicorp/vault#17576]
**Describe the bug**
Unable to get a kv secret the same name as the secret engine using `vault kv` cli.

**To Reproduce**
1. Create a v2 kv secret engine and add a secret with a name same as the secret engine, e.g. `foo/data/foo`.
3. Run `vault kv get --mount=foo foo`.
4. See something like this instead of the value of the secret:
```
WARNING! The following warnings were returned from Vault:

  * Non-listing operations on the root of a K/V v2 mount are not supported.

== Secret Path ==
foo/data
```

**Expected behavior**
This should be printed by `vault kv get --mount=foo foo`:
```
== Secret Path ==
foo/data/foo

======= Metadata =======
Key                Value
---                -----
created_time       2022-10-11T09:03:35.262550394Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            1

==== Data ====
Key     Value
---     -----
data    123456
```

**Environment:**
* Vault CLI Version (retrieve with `vault version`): `Vault v1.11.4 ('b47a9e72942719f217f7750df18be36ec21dfc0e+CHANGES'), built 2022-09-23T06:01:14Z`

**Comment by ccapurso** [comment]
This has been fixed and backported to the 1.11 and 1.12 release branches. The fix will be available in versions 1.11.6 and 1.12.2.
