### ISSUE TITLE
Duo MFA fails when push_info contains a value

### ISSUE THREAD

**Issue by hawleyOSU** [hashicorp/vault#17583]
**Describe the bug**
The Duo MFA Method fails when the push_info field contains a value. The following error is returned.  
`failed to satisfy enforcement Duo_MFA. error: 2 errors occurred: * 
failed to authenticate with Duo: "Invalid request parameters" - "pushinfo" * 
login MFA validation failed for methodID: [0fa6fed5-3047-a6a6-d1c1-b7b932cc5931]
Multi-factor authentication is required, but failed. Go back and try again, or contact your administrator.`

**To Reproduce**
1. Configure Duo MFA method according to documentation, leave push_info blank.
2. MFA (Duo Push) at logon is successful
3. Edit Duo MFA method, add any string to push_info and save
4. Attempt user authentication
5. Push_info error is returned

**Expected behavior**
If Duo does not support push_info, the field should be ignored. Better yet, the filed should removed from the Duo MFA configuration page (UI) and api documentation updated to specify this field is invalid for the Duo method and must remain blank.  

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1:12:0, HA Cluster/raft
* Vault CLI Version (retrieve with `vault version`): Vault v1.12.0 (558abfa75702b5dab4c98e86b802fb9aef43b0eb), built 2022-10-10T18:14:33Z
* Server Operating System/Architecture: redhat enterprise_linux 7.9
* 

**Additional context**
Issue occurs with UI, CLI and API log on attempts.

**Comment by hghaf099** [comment]
Thanks for filing this ticket. So, according to Duo [docs](https://duo.com/docs/authapi#/auth), the `push_info` should be:
```
A set of URL-encoded key/value pairs with additional contextual information associated with this authentication attempt. The Duo Mobile app will display this information to the user.

For example: from=login%20portal&domain=example.com

The URL-encoded string's total length must be less than 20,000 bytes.
```

I just tried the above example, and Duo MFA succeeded without error. I am going to close this issue for now. Please feel free to reopen the issue or open a new one for further discussions.

**Comment by john159753** [comment]
Glad I found this! Should definitely be included in the documentation.

**Comment by hawleyOSU** [comment]
I can confirm that it is just passing those values to the Duo API, and following the Duo documentation works as expected. John, you are right, it really is just missing documentation by Hashicorp. The Duo integration as a whole is not well documented.
