### ISSUE TITLE
Missing auth information in audit messages?

### ISSUE THREAD

**Issue by jszwedko** [hashicorp/vault#176]
This is more of a question than an issue, but I was curious if the auth information should be included in the audit messages for secret requests authenticated via the `app-id` backend. Example audit log:

```
{"type":"request","auth":{"policies":null,"metadata":null},"request":{"operation":"write","path":"auth/app-id/login","data":{"app_id":"sha1:0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33","user_id":"sha1:62cdb7020ff920e5aa642c3d4066950dd1f01f4d"}}}
{"type":"response","error":"","auth":{"policies":["root"],"metadata":null},"request":{"operation":"write","path":"auth/app-id/login","data":{"app_id":"sha1:0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33","user_id":"sha1:62cdb7020ff920e5aa642c3d4066950dd1f01f4d"}},"response":{"auth":{"string":"sha1:6f924313d1e54c18071c3101d5a5c314140eacf1","policies":["root"],"metadata":null},"secret":{"lease_id":""},"data":null,"redirect":""}}
{"type":"request","auth":{"policies":["root"],"metadata":null},"request":{"operation":"read","path":"secret/foo","data":null}}
{"type":"response","error":"","auth":{"policies":["root"],"metadata":null},"request":{"operation":"read","path":"secret/foo","data":null},"response":{"auth":{"policies":null,"metadata":null},"secret":{"lease_id":"secret/foo/a33ab46d-2af1-3979-6f7a-3e5b3ece965d"},"data":{"bar":"sha1:bbe960a25ea311d21d40669e93df2003ba9b90a2"},"redirect":""}}
```

I was expecting to see more information in the `auth.metadata` section of the response -- e.g. the authentication backend the client token corresponds to as well as a hash of the user-id and app-id -- especially given that https://vaultproject.io/docs/auth/app-id.html describes setting a `display_name`. Right now the only information available is the policy.

If this would be considered an enhancement and is desired I can take a shot at implementation.

**Comment by huskercane** [comment]
I agree without auto information the information in audit log has less value.

**Comment by mitchellh** [comment]
Display name is now shown and hash of app/user id is now given

**Comment by jszwedko** [comment]
Awesome, thanks @mitchellh

**Comment by nbrownus** [comment]
`display_name` is not showing up for `response` log lines and the `request` is logged twice, although that is less interesting.

Example:

```
{"type":"request","auth":{"display_name":"token-REDACTED","policies":["root"],"metadata":null},"request":{"operation":"read","path":"REDACTED","data":null}}
{"type":"response","error":"","auth":{"display_name":"","policies":["root"],"metadata":null},"request":{"operation":"read","path":"REDACTED","data":null},"response":{"auth":{"display_name":"","policies":null,"metadata":null},"secret":{"lease_id":""},"data":null,"redirect":""}}
```

I built from this commit  3ebde4b26820ffcb27cf797cb8424d737a5cab3f
