### ISSUE TITLE
Vault 0.6.1 -- DNS resolution broken for addresses that end in .local

### ISSUE THREAD

**Issue by skevy** [hashicorp/vault#1760]
Due to this issue in Go 1.7, `netgo` does not resolve addresses ending in .local -- which is used extensively in Kubernetes clusters: https://github.com/golang/go/issues/16739

It's resolved here: https://github.com/golang/go/commit/289df4e6e65466716aaf1cf65fcfdedada2a5599

Unfortunately, Go 1.7.1 is not yet released. Would be awesome if you guys would track that release and release Vault 0.6.2 (built on go 1.7.1) ASAP, as this breaks anyone who's using Vault in a typical Kubernetes configuration.

Thanks!

**Comment by skevy** [comment]
I suppose you may also be able to go back to building with Go 1.6.x, but not sure if that's something you all want to do.

**Comment by jefferai** [comment]
We actually can't go back down to 1.6, as we are using 1.7-specific features.

We tend to build against the latest Go release, so if 1.7.1 is out by then, our next release will be against it.

**Comment by skevy** [comment]
@jefferai so no chance you'll do point release when 1.7.1 is released to fix this issue?

**Comment by jefferai** [comment]
@skevy To specifically fix this issue, probably not; it should be pretty easy to work around by just building on your own. I could send you a build if you wanted. But for an official release, we'll need to see when 1.7.1 is released and where we are at that point.

**Comment by skevy** [comment]
👍

**Comment by jefferai** [comment]
1.7.1 has been released and the code has already been updated to use it for the next release, so closing this for now. Probably 1-2 weeks.
