### ISSUE TITLE
AppRole documentation is contradictory

### ISSUE THREAD

**Issue by pforman** [hashicorp/vault#1761]
In the AppRole docs, under **Pull And Push SecretID Modes**:  (italics for emphasis)

> If the SecretID used for login is fetched from an AppRole, this is operating in Pull mode. If a "custom" SecretID is set against an AppRole by the client, it is referred to as a Push mode. _Push mode mimics the behavior of the deprecated App-ID backend; however, in most cases Pull mode is the better approach_. The reason is that Push mode requires some other system to have knowledge of the full set of client credentials (RoleID and SecretID) in order to create the entry, even if these are then distributed via different paths. However, in Pull mode, even though the RoleID must be known in order to distribute it to the client, the SecretID can be kept confidential from all parties except for the final authenticating client by using Response Wrapping.

But then the next paragraph contradicts this directly:

> _Pull mode is available for App-ID workflow compatibility, which in some specific cases is preferable, but in most cases Push mode is more secure and should be preferred._

As far as I can tell, that second paragraph is backwards regarding Push-Pull, and should probably just be removed.

**Comment by jefferai** [comment]
That's correct, Push and Pull are swapped there.

**Comment by jefferai** [comment]
Fixed on master, will update the web site soon.
