### ISSUE TITLE
0.6.1 Docker image impossible to test out of dev mode.

### ISSUE THREAD

**Issue by erydo** [hashicorp/vault#1762]
This change in [hashicorp/vault@00721af](https://github.com/hashicorp/vault/commit/00721af2c15c40d7ee5b3de2573f6bb482b33793#diff-593cd0d199cb70fe727e6b64eb150baaR77) interacts with the official Docker image's overridden defaults here [hashicorp/docker-vault](https://github.com/hashicorp/docker-vault/blob/master/0.6.1/docker-entrypoint.sh#L32) and appears to make it impossible to take the stock Docker image out of dev mode.

Attempting to run without the `-dev` flag results in the error:
> "Development address can only be specified with -dev"

As far as I can tell, the only way to run `vault:0.6.1` out of dev mode is use a custom entrypoint: neither adding `-dev-listen-address=''` nor setting `VAULT_DEV_LISTEN_ADDRESS=''` appear to work otherwise.

Is there a another workaround?

**Comment by erydo** [comment]
EDIT: The workaround is pretty simple, I must be tired: just running with `docker run --entrypoint=vault` works fine, since the `docker-entrypoint.sh` doesn't do anything essential.

**Comment by jefferai** [comment]
Hi @erydo ,

I must admit that I don't understand the problem in the first place, or how that commit changes Docker behavior. You simply define a config file and run "vault server" as normal. You don't need to modify the entrypoint.

**Comment by erydo** [comment]
@jefferai: That was the case in 0.6.0. With the 0.6.1 docker image, the following happens:
```sh
$ docker run -v "$PWD/vault-config:/config/" vault:0.6.1 server -config=/config/
Development address can only be specified with -dev
```

If a user does not provide `-dev-listen-address` or `VAULT_DEV_LISTEN_ADDRESS`, for example because they don't want to run with `-dev`, then `docker-entrypoint.sh` sets a default value in its place.

That behaviour used to be benign and the extra parameters were ignored, but that appears to have changed in the commit I referenced above. That change prevents the docker image from being run except with `-dev` or by changing the entrypoint.

I've updated my original comment with links to the specific lines causing this.

The following is a workaround, by not using the provided entrypoint:
```sh
docker run -v "$PWD/vault-config:/config/" --entrypoint=vault vault:0.6.1 server -config=/vault-config/
```

**Comment by jefferai** [comment]
Ah shucks. I'll figure out the best way to fix it and either roll a new Docker image with a fixed entrypoint or make a change in Vault and make a special Docker tag.

**Comment by dstroot** [comment]
+1000

Just spent two hours on this exact issue.  I definitely confirm it.

**Comment by dstroot** [comment]
👍  Jeff you are the fastest on the draw ever.  Thanks.

**Comment by jefferai** [comment]
Haha. The pull request on the Docker side got a LGTM so should go in soon. My guess is this will be fixed in the official container tomorrow.

I hate delivering a product that just doesn't work, so in that situation I will always fix as fast as feasible. Glad you appreciate it, and sorry it didn't work in the first place!

**Comment by jorhett** [comment]
This is still a problem with 1.1.13. You cannot run server without it prefixing `-dev` and other arguments to whatever you add
