### ISSUE TITLE
PKI: Error parsing CRL duration of '' when CRL is disabled

### ISSUE THREAD

**Issue by JNProtzman** [hashicorp/vault#17642]
**Describe the bug**
We've recently upgraded Vault from 1.10.3 -> 1.12.

When we went to create a new CA, we received a 500 error.
```
vault write pki/root/root/rotate/internal <fields>
Error writing data to pki/root/root/rotate/internal: Error making API request.
URL: PUT https://<redacted>/v1/pki/root/root/rotate/internal
Code: 500. Errors:
* 1 error occurred:
	* error building CRLs: unable to build CRL for issuer (<issuer>): error parsing CRL duration of
```

Our CRL is configured as follows:
```
vault read pki/root/config/crl
Key                          Value
---                          -----
auto_rebuild                 false
auto_rebuild_grace_period    12h
delta_rebuild_interval       n/a
disable                      true
enable_delta                 false
expiry                       n/a
ocsp_disable                 false
ocsp_expiry                  12h
```

Since the CRL is disabled, should it not be checking the expiry time? I believe that the expiry time should be be parsed below the disable check [here](https://cs.github.com/hashicorp/vault/blob/fc2bdc37bf76431c29cf4f2c1d7e7e1785ee111a/builtin/logical/pki/crl_util.go#L1251-L1256)

**To Reproduce**
We have our CRL disabled and we had the expiry unset (as seen by the above). With the expiry unset (`n/a`), attempt to rotate the credentials. We've upgraded Vault several times now, so it's possible we have a legacy config. However, if it's possible for the expiry time to be null, then this should be reproducible. 

**Expected behavior**

I expected the rotation to complete without this error, since the CRL is disabled.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.12
* Vault CLI Version (retrieve with `vault version`): 1.7.3
* Server Operating System/Architecture: 

**Additional context**

**Comment by JNProtzman** [comment]
This is a pretty simple bug, I'd be happy to open a PR to move the logic around if that's deemed appropriate.
With that being said, it is not blocking. I have updated the crl expiry, which has resolved the 500 error we received.
```
vault write pki/root/config/crl expiry="0h"
```

**Comment by cipherboy** [comment]
@JNProtzman Sure, happy to take a PR for this one. I think perhaps we should modify `getRevocationConfig` to handle the differences for us on fetch. We'll have to do this outside of the version block as some clients (like yourself) have already upgraded. I'd set it to the default value.

**Comment by cipherboy** [comment]
Thanks for the PR with the fix!
