### ISSUE TITLE
Token is exposed as plaintext in the audit backend when is passed in the URL

### ISSUE THREAD

**Issue by enudler** [hashicorp/vault#1764]
In case of accessing the auth/token/lookup api
the token is logged as plaintext (as it's in the url) to the audit backend

example of request:

Aug 23 09:31:45 ip-10-0-3-185 vault[1]: {"time":"2016-08-23T09:31:45Z","type":"request","auth":{"display_name":"root","policies":["root"],"metadata":null},"request":{"operation":"read","client_token":"hmac-sha256:1024397ba71fcde0b0d933c0b79c667d217043b14ffaea86f47b94cd6326bc59","path":"auth/token/lookup/accaadc2-7b6e-c929-d594-2d8de6d18c47","data":null,"remote_address":"10.0.6.92","wrap_ttl":0},"error":""}

**Comment by jefferai** [comment]
The request path is always plaintext. You should use the POST method instead. (We may remove the GET method at some point for exactly this reason.)
