### ISSUE TITLE
Valut ldap auth fails 

### ISSUE THREAD

**Issue by awellock** [hashicorp/vault#1767]
I am working to setup up the ldap auth backed. I have it at a point where it will work about one of every 50 tries. The rest hangs and eventual fails with **Put https://VauiltIP:8200/v1/auth/ldap/login/User@company.com: net/http: request canceled (Client.Timeout exceeded while awaiting headers).**
When I supply an invalid password I get an Invalid credential error immediately. It appears that vault can communicate with the Enterprise Directory server but can not reliably authenticate with it. 

Here is the configuration I am using. 
{
    "url": "ldaps://hpe-pro-ods-ed.infra.hpecorp.net",
    "userattr": "uid", 
    "userdn": "ou=People,o=hp.com",
    "groupdn": "ou=Groups,o=hp.com",
    "insecure_tls": true,
    "starttls": false,
    "binddn": "uid=User@Company.com,ou=People,o=hp.com",
    "bindpass": "SomePass"
}

I have also seen this error in the Vault logs

2016/08/23 14:23:16 Received unexpected message 1, false
LDAP Response: (Universal, Constructed, Sequence and Sequence of) Len=12 "<nil>"
Message ID: (Universal, Primitive, Integer) Len=1 "1"
Bind Response: (Application, Constructed, 0x01) Len=7 "<nil>"
Result Code (Success): (Universal, Primitive, Enumerated) Len=1 "0"
Matched DN: (Universal, Primitive, Octet String) Len=0 ""
Error Message: (Universal, Primitive, Octet String) Len=0 ""

Any help or pointers will be externally useful.

**Comment by jefferai** [comment]
What client are you using to talk to Vault?

If the CLI, the CLI is configured to have a timeout of 10 seconds on the TLS handshake and 60 seconds on the HTTP request. Is it possible that the LDAP authentication is taking more than 60 seconds, or that the load on the Vault server is high enough that it's taking more than 10 seconds to establish the initial connection?

**Comment by awellock** [comment]
I am using the CLI. I do not think a handshake timeout is the problem as an invalid request comes back extremely quickly and all other commands to the vault server are successful. This Vault server is not currently being used, it is still in the process of being stood up, and the load is just my self trying to test it out. Is there a way to increase the time out as a test?

**Comment by jefferai** [comment]
There isn't a way, no, without recompiling, although you could use the HTTP API directly with `curl` or so.

What's your vault config/version? Can you paste your logs?

**Comment by awellock** [comment]
I will try it with curl now. The logs are not of much help. Setting them at trace I still have nothing useful. Below are the logs generated by the auth attempt. I am using the official Docker Vault image which looks to be 0.6 and etcd for the backend. 

2016/08/23 15:58:22 [DEBUG] rollback: attempting rollback on secret/
2016/08/23 15:58:22 [DEBUG] rollback: attempting rollback on auth/token/
2016/08/23 15:58:22 [DEBUG] rollback: attempting rollback on auth/ldap/
2016/08/23 15:58:22 [DEBUG] rollback: attempting rollback on cubbyhole/
2016/08/23 15:58:22 [DEBUG] rollback: attempting rollback on sys/
2016/08/23 15:59:22 [DEBUG] rollback: attempting rollback on cubbyhole/
2016/08/23 15:59:22 [DEBUG] rollback: attempting rollback on auth/token/
2016/08/23 15:59:22 [DEBUG] rollback: attempting rollback on secret/
2016/08/23 15:59:22 [DEBUG] rollback: attempting rollback on auth/ldap/
2016/08/23 15:59:22 [DEBUG] rollback: attempting rollback on sys/
2016/08/23 16:00:22 [DEBUG] rollback: attempting rollback on auth/ldap/
2016/08/23 16:00:22 [DEBUG] rollback: attempting rollback on secret/
2016/08/23 16:00:22 [DEBUG] rollback: attempting rollback on cubbyhole/
2016/08/23 16:00:22 [DEBUG] rollback: attempting rollback on sys/
2016/08/23 16:00:22 [DEBUG] rollback: attempting rollback on auth/token/

Bellow is my config file for vault
backend "etcd" {
  address = "https://16.85.1.91:12379"
  tls_ca_file = "/opt/etcd/ssl/ca.pem"
  tls_cert_file = "/opt/etcd/ssl/cert.pem"
  tls_key_file = "/opt/etcd/ssl/key.pem"
  advertise_addr = "https://16.85.1.91:12379"
}
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file ="/opt/ssl/vault/ssl/cert.pem"
  tls_key_file = "/opt/ssl/vault/ssl/key.pem"
}
disable_mlock = true
default_lease_ttl = "1h"
max_lease_ttl = "36h"

**Comment by jefferai** [comment]
I'd suggest trying 0.6.1 outside of a Docker container right now, for three reasons: one, the LDAP code in 0.6.1 had a huge amount of work done on it so it's hard for me to correlate causes of issues in 0.6.0 with things that may be fixed by 0.6.1 or may not; two, the 0.6.1 container is broken (but should be fixed soon), three, Docker has often been a cause of network issues reaching things outside of it. If the same issue happens outside of Docker we'll know that's not contributing.

**Comment by awellock** [comment]
Thanks I will give that a go and report back.

**Comment by awellock** [comment]
I got a new error using 0.6.1. 
* cannot connect to LDAP: LDAP Result Code 200 "": tls: server selected unsupported protocol version 301
I checked the TLS version on the ldap server it is using 1.2

**Comment by jefferai** [comment]
@awellock According to the LDAP client, it isn't, or at least tried to use TLS 1.1:

> server selected unsupported protocol version 301

You can use the `tls_min_version` config option set to `tls11` to allow this on the client side.

**Comment by awellock** [comment]
I set it to tls10 I am still seeing the same error. 

Bellow is the version fo TLS the LDAP server is using. 

openssl s_client -host EDServer -port 636 | grep -i TLS
depth=1 O = hp.com, OU = IT Infrastructure, C = US, O = Hewlett-Packard Company, CN = Hewlett-Packard Private Class 2 Certification Authority
verify error:num=19:self signed certificate in certificate chain
New, TLSv1/SSLv3, Cipher is AES256-GCM-SHA384
    Protocol  : TLSv1.2
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:

**Comment by jefferai** [comment]
I'm not sure what the way forward is here. The error you're seeing is coming from this:

https://golang.org/src/crypto/tls/handshake_client.go#L173

So something in the TLS handshake is not working correctly. That mutualVersion function is quite simple: https://golang.org/src/crypto/tls/common.go#L551

After a TLS handshake, Vault (via Go) thinks that the server has only advertised TLS 1.1.

**Comment by awellock** [comment]
I did some more digging. Turns out the load balanced servers were not all running the same version. It works as expected when pointed to a server instead of DNS name. I think this can be closed. Thanks for your help @jefferai, I appreciate it!

**Comment by awellock** [comment]
When pointing at the correct IP the docker container running 0.6.0 also works. Thanks again for the help.

**Comment by jefferai** [comment]
Great!
