### ISSUE TITLE
Conflicting documentation around policy path prefixes

### ISSUE THREAD

**Issue by dpedu** [hashicorp/vault#17733]
**Describe the bug**
Conflicting documentation around policy path prefixes

**To Reproduce**

On https://developer.hashicorp.com/vault/docs/secrets/kv/kv-v2#acl-rules, the documentation mentions that policies need to be manually changed for kvv2. The example it gives is changing `secret/dev/team-1/*` to `secret/data/dev/team-1/*` and it mentions that `data/` needs to be insert somewhere in the string.

On https://developer.hashicorp.com/vault/docs/concepts/policies, the example policy given uses the path `secret/foo`, which does not contain the `data/` insert.  Which is correct?

**Expected behavior**
The documentation should be consistent.

**Environment:**
N/a

Vault server configuration file(s):
N/a

**Additional context**
N/a

**Comment by ccapurso** [comment]
Hi, @dpedu. There a few examples within the policies concepts documentation that mention that KVv1 is in use. KVv2 introduced secret versioning where metadata and data are stored separately. There are separate API endpoints (`<mount>/metadata/<key>` versus `<mount>/data/<key>`) and access can thus be provided separately within your policies. KVv1 data is obtained via paths like `<mount>/<key>`. Are you potentially referring to one of the KVv1 examples where no data sub-path is needed?

**Comment by dpedu** [comment]
Hi @ccapurso, sort of. I have a bit more clarity on this issue now. I found it confusing that the [policies page](https://developer.hashicorp.com/vault/docs/concepts/policies) immediately jumps into examples that are only relevant to kvv1 when kvv2 is the new default. For example, I was running `vault server -dev` for the purpose of testing the newest version of vault to plan my upgrade from an older one. The dev server defaults to kvv2 so I found it confusing that the very first examples on that policy page of the documentation don't work unless you specifically ask for the older kvv1. I think some alignment here would save folks, including myself, some head scratching.

**Comment by ccapurso** [comment]
@dpedu, those are valid points. It definitely seems like some improvement can be made here. Thank you for the feedback!

**Comment by ccapurso** [comment]
@dpedu I added a quick clarification. We might re-work these examples more in the future but hopefully a bit more clarification is helpful.

**Comment by dpedu** [comment]
Thank you!
