### ISSUE TITLE
Unpublished behavioral changes in LDAP TLS handling

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/vault#1773]
There are two unpublished behavioral changes with respect to the LDAP TLS client that have occurred since 0.5.3:

1) Certificates that were loaded into 0.5.3 had their line breaks stripped.  Trying to connect after a 0.6.1 upgrade resulted in the error `cannot connect to LDAP: could not append CA certificate`.   We resolved the problem by re-configuring the LDAP auth backend and re-uploading the CA certificate from the PEM file.  

You can see the difference here:

Before (failing):

```
$ vault read auth/ldap/config
Key             Value
---             -----
binddn          
bindpass        
certificate     -----BEGIN CERTIFICATE-----MIIDuzCCAqOgAwIBAgIJAODU+JMeD4Y5MA0GCSqGSIb3DQEBBQUAMIGTMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzEVMBMGA1UECgwMWmVuZGV...
```

After (working):

```
$ vault read auth/ldap/config
Key             Value
---             -----
binddn          
bindpass        
certificate     -----BEGIN CERTIFICATE-----
MIIEFTCCAv2gAwIBAgIJAN0HoUEGF0oDMA0GCSqGSIb3DQEBCwUAMIGTMQswCQYD
VQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5j
aXNjbzEVMBMGA1UECgwMWmVuZGVzayBJbmMuMRMwEQYDVQQLDApPcGVyYXRpb25z
...
```

2) Vault now requires that the LDAP server certificate by signed by a trusted issuer.  However, I'm now having trouble getting Vault to accept the certificate even though I've added the signing certificate in the CA trust store (CentOS 7.2).

**Comment by jefferai** [comment]
I'm not sure about the first one but my guess is that the second is caused by some change in the LDAP library or in Go (read: we didn't know either). Does appending the full chain in the PEM file work?

**Comment by mfischer-zd** [comment]
> Does appending the full chain in the PEM file work?

Yes, that fixes the problem.  So another thing to add to the errata. :)

**Comment by jefferai** [comment]
Potentially, although I'm not sure if this change happened in 0.6 or 0.6.1, since you upgraded directly.
