### ISSUE TITLE
vault client no longer tolerates trailing newline in .vault-token file

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/vault#1774]
I used to manually write my token into my `$HOME/.vault-token` file for various purposes.  As of 0.6.1, if the token ends with a newline (most editors will automatically add one at the end of each line), the following error is returned (and the token isn't obfuscated in the response!):

(this was a response to running `vault mounts`):

```
Error reading mounts: Get https://127.0.0.1:8200/v1/sys/mounts: net/http: invalid header field value "...43d54\n" for key X-Vault-Token

```

**Comment by jefferai** [comment]
> most editors will automatically add one at the end of each line

I've never seen an editor do this that isn't emacs :-)
