### ISSUE TITLE
The same nested namespace in http url path

### ISSUE THREAD

**Issue by valli0x** [hashicorp/vault#17754]
these three requests are equivalent in documentation: 
1. Path: ns1/ns2/secret/foo
2. Path: secret/foo, Header: X-Vault-Namespace: ns1/ns2/
3. Path: ns2/secret/foo, Header: X-Vault-Namespace: ns1/

I found this line of code: 
https://github.com/hashicorp/vault/blob/080133efce7e54deb6c2fe96c85912d5efa73815/http/logical.go#L49
Does this mean that the namespace ns1/ in header X-Vault-Namespace and the nested namespace ns1/ns1 in the path: ns1/secret/foo will not work?

expected result full path: ns1/ns1/secret/foo
result: ns1/secret/foo

**Comment by ccapurso** [comment]
Hi, @valli0x. I have attempted to reproduce the behavior. I don't believe that I've hit any issue limiting namespace usage as described but it is possible that I have missed something. Does the sequence of commands listed below match your expectation? 

```
❯ vault namespace create ns1
Key                Value
---                -----
custom_metadata    map[]
id                 1wMYV
path               ns1/

❯ VAULT_NAMESPACE=ns1 vault namespace create ns2
Key                Value
---                -----
custom_metadata    map[]
id                 OzNkK
path               ns1/ns2/

❯ VAULT_NAMESPACE=ns1/ns2 vault secrets enable -path=secret kv-v2
Success! Enabled the kv-v2 secrets engine at: secret/

❯ vault kv put ns1/ns2/secret/foo abc=123
===== Secret Path =====
ns1/ns2/secret/data/foo

======= Metadata =======
Key                Value
---                -----
created_time       2022-11-01T14:20:02.466477Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            1

❯ vault kv get ns1/ns2/secret/foo
===== Secret Path =====
ns1/ns2/secret/data/foo

======= Metadata =======
Key                Value
---                -----
created_time       2022-11-01T14:20:02.466477Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            1

=== Data ===
Key    Value
---    -----
abc    123

```

**Comment by valli0x** [comment]
Can I create a duplicate nested namespace?

**Comment by ccapurso** [comment]
Hi @valli0x, the path of a namespace will be based on the `X-Vault-Namespace` header and the request path. The namespace in the first example will be `ns1` based on the path. The namespace in the second example will be `ns1/ns1` also based on the path. The namespace in the third example will be based on both the `X-Vault-Namespace` header `ns1` and path `ns1` resulting in `ns1/ns1`. I hope this helps.
