### ISSUE TITLE
Vault Init input validation is too strict (1.12.0)

### ISSUE THREAD

**Issue by acidprime** [hashicorp/vault#17764]
**Describe the bug**
Vault 1.12.0 added support to validate operator init input. However Its breaking a community terraform module and supported server side behavior.

Refs
[Vault PR adding validation](https://github.com/hashicorp/vault/pull/16379)
[Terraform Community Module](https://registry.terraform.io/providers/rickardgranberg/vaultoperator/latest/docs/resources/init)

This is due to the fact the author relied on passing in `0` to the  `recovery_`* params and then them being ignored by vault when secrets were specified as non zero. This is confusing in the code as the error does not match the expected state as defined.

This is **NOT** inline with the vault server code https://github.com/hashicorp/vault/blob/dd891bc748f690cf90e5e5297304b4bc5f4d0902/http/sys_init.go#L154-L158

Which implicitly allows you to pass `0` currently.

**To Reproduce**
1. Using module write the following code
```terraform
 resource "vaultoperator_init" "scenario_vault_init" {
   secret_shares    = 1
   secret_threshold = 1
 
   depends_on = [
     docker_container.scenario_vault_container,
     time_sleep.wait_for_vault_startup,
   ]
 
   lifecycle {
     ignore_changes = all
   }
 }

```
3. Run `terraform apply`
```
Error: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/init
Code: 400. Errors:

* parameters recovery_shares,recovery_threshold not applicable to seal type shamir

  on ../modules/vault-transit/main.tf line 7, in resource "vaultoperator_init" "scenario_vault_init":
   7: resource "vaultoperator_init" "scenario_vault_init" {
```

**Expected behavior**
The provider specifiying `0` for recovery keys and >`0` for secret keys should pass validation. 

Based on semver this is a breaking change to the API, while I understand the need for validation I would say passing `0` to both params should negate that check given the server side code supporting that configuration. Further I think this scenario e.g.  `0` for the params was missed in the [go tests](https://github.com/hashicorp/vault/blob/0d6a42c79ef765e919db486c1cb78e527b47e010/http/sys_init_test.go#L133-L150), and if its was an expected behavior then it should be in the go tests for linked PR. Instead the PR/tests only assume a scenario where you incorrectly pass both params in with values instead of one with 0 and one with >0 value . Most importantly  its not inline with the actual server code referenced above which should be the source of truth here for validation.

**Environment:**
* Vault Server Version `1.12.0`:
* Vault CLI Version`1.12.0`:
* Server Operating System/Architecture:

[Docker](https://hub.docker.com/layers/hashicorp/vault-enterprise/1.12.0-ent/images/sha256-0e0c39f329ba3a0565a49f7fc7cecdd0648b61dc0a0774d312152e43c8854e94?context=explore) , but its not probably not relevant to this bug.

Vault server configuration file(s):

```hcl 
 disable_mlock = true
 ui = true
 
 listener "tcp" {
     tls_disable = "true"
     address = "[::]:8200"
     cluster_address = "[::]:8201"
 }
 
 storage "file" {
   path = "/tmp"
 }

```

**Additional context**
I have also filed a bug on the community provider here https://github.com/rickardgranberg/terraform-provider-vaultoperator/issues/7

However strictly speaking again, this is a breaking change in the API on invalid semver bump so I think vault should likely fix it. The validation while good, should not fail to validate something that would not produce an invalid configuration e.g. `0` for recovery keys. 

Even if you expect the provider author to fix it, it is actually not that easy to fix for the though too:

You can see the terraform vault provider code in question [here](https://github.com/rickardgranberg/terraform-provider-vaultoperator/blob/8df5a1db09ff6d60c8574b0876223c628cd551e0/internal/provider/resource_init.go#L244-L249)

This is essentially by design in the terraform provider code as calling [Get](https://pkg.go.dev/github.com/hashicorp/terraform/helper/schema#ResourceData.Get) will  implicitly return a `0` and not say `nil`, that would work here with `omitempty` if the upstream vault api module supported it. However even that won't work as vault doesn't use `omitempty` for the init request type.

From the terraform provider docs for `Get`
> If the key does exist in the schema but doesn't exist in the configuration, then the default value for that type will be returned. For strings, this is "", for numbers it is 0, etc.

https://github.com/hashicorp/vault/blob/746b089472bc231da9f536a7092ade75e10f91c1/api/sys_init.go#L58-L59

**Comment by ccapurso** [comment]
Hi, @acidprime. The Vault team is very cautious about introducing breaking changes only to major versions. Vault 1.12.0 does not strictly follow semver and thus 1.12.0 is actually considered a major version.

I dug into `terraform-provider-vaultoperator` and it appears that the recovery shares and threshold are [set](https://github.com/rickardgranberg/terraform-provider-vaultoperator/blob/8df5a1db09ff6d60c8574b0876223c628cd551e0/internal/provider/resource_init.go#L236-L242) to the secret shares and threshold if they are 0. It seems that removing those lines could resolve this issue.

**Comment by acidprime** [comment]
> Hi, @acidprime. The Vault team is very cautious about introducing breaking changes only to major versions. Admittedly, it has happened in the past. Vault does not strictly follow semver and 1.12.0 is actually considered a major version.
> 
> I dug into `terraform-provider-vaultoperator` and it appears that the recovery shares and threshold are [set](https://github.com/rickardgranberg/terraform-provider-vaultoperator/blob/8df5a1db09ff6d60c8574b0876223c628cd551e0/internal/provider/resource_init.go#L236-L242) to the secret shares and threshold if they are 0. It seems that removing those lines could resolve this issue.

Yeah that makes sense to me too

https://github.com/rickardgranberg/terraform-provider-vaultoperator/blob/main/internal/provider/resource_init.go#L236-L242

If those values are non-zero it makes sense validation would fail

**Comment by mladlow** [comment]
It seems like this might have been resolved, so I'm going to close it. If that's wrong, feel free to re-open!
