### ISSUE TITLE
HA mode not showing proper leader in CLI output

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#178]
I'm trying to use HA mode, but all nodes remain in standby. I am using a Consul backend, and all Vault instances are unsealed and have `advertise_addr` properly configured; I can curl against the various addresses successfully.

However, all three nodes report no leader and on standby:
```
$ vault status
Sealed: false
Key Shares: 5
Key Threshold: 2
Unseal Progress: 0

High-Availability Enabled: true
	Mode: standby
	Leader: <none>
```
In the logs for all three I get this:
```
2015/05/08 20:37:04 [ERR] core: failed to acquire lock: failed to acquire lock: Unexpected response code: 403 (rpc error: Permission denied)
```
This suggests one of two things, to me:

1. This RPC error originates from Consul, and Vault is not using my provided ACL token (although it is successfully using it during startup and unsealing)
2. This is an RPC error between Vault nodes, and something is required for me to grant access, but I have no idea what

My config looks like the following:
```
backend "consul" {
    scheme = "http"
    token = "[redacted]"
    advertise_addr="http://10.88.0.1:8200"
}

listener "tcp" {
    address = "0.0.0.0:8200"
    tls_disable = 1
}
```

**Comment by jefferai** [comment]
I noticed something in my Consul logs:
```
2015/05/08 21:22:10 [ERR] http: Request /v1/kv/core/lock?acquire=[redacted]&flags=3304740253564472344&token=[redacted], error: rpc error: Permission denied
```
I'm guessing this is related. This may just be a documentation bug; probably I need to adjust policy for the Vault ACL token, but it's unclear to me where/what. I have Consul's ACL policy set to deny by default, and I assumed that setting the token I gave to the vault servers to have write on vault/ would be sufficient.

**Comment by armon** [comment]
@jefferai Looks like it was a simple bug in path generation. Fixed in 790a8f8! Please confirm that its working now!

**Comment by jefferai** [comment]
Confirmed!

**Comment by jefferai** [comment]
Actually, one thing to ask before I close this:

After this patch, I now see a leader:
```
High-Availability Enabled: true
	Mode: active
	Leader: https://10.88.0.65:8200
```
However, on the other two Vault servers, they think there is no leader:
```
High-Availability Enabled: true
	Mode: standby
	Leader: <none>
```
There's nothing in the logs though suggesting any kind of ongoing problem. Is this simply what is displayed in this scenario (maybe due to a simple output bug)?

**Comment by armon** [comment]
@jefferai Good catch for the second time!
