### ISSUE TITLE
Q: self-signed certs inside Kubernetes Pod? 

### ISSUE THREAD

**Issue by dstroot** [hashicorp/vault#1786]
[Q is at bottom] I am trying to use Vault inside Kubernetes as the main storage for configuration secrets.  It's alive:

![image](https://cloud.githubusercontent.com/assets/1438457/17954585/be9d5d64-6a30-11e6-821e-08aacd963bf8.png)

It is only a deployment with one pod at the moment.  I don't want it publicly exposed outside the container.  I can access it via `kubectl port-forward vault-1245296943-xxxxx 8200:8200` where it looks to the CLI like 127.0.0.1:8200 so `export VAULT_ADDR='https://127.0.0.1:8200'` makes it available locally.

[Here's the Q: for the life of me I cannot figure out how to craft a selfie cert to make TLS work without -tls-skip-verify.  I can't even use a "real" cert because there is no external access and since I don't have a Vault "service" setup inside Kubernetes I don't believe I don't have a "vault" DNS entry inside Kubernetes.  This does *not* work: `openssl req -x509 -newkey rsa:2048 -nodes -keyout cert/vault.key -out cert/vault.crt -days 730 -subj "/CN=127.0.0.1:8200"`

Any ideas, suggestions, guides? (yup I have already read the issues in the repo I could find related to this.) Thanks in advance!

FYI: 
I can consume secrets from Vault into Kubernetes secrets with some elbow grease: 

```shell
    #!/bin/bash
    PASSWORD="$(vault read -field=value secret/password | base64)"

    # Create YAML object from stdin
    cat <<EOF | kubectl create -f -
    apiVersion: v1
    kind: Secret
    metadata:
      name: mysecret
    type: Opaque
    data:
      password: "${PASSWORD}"
    EOF
```

**Comment by jefferai** [comment]
@dstroot Assuming you can reach it via 127.0.0.1, the issue is that 127.0.0.1 needs to be in the IP Subject Alternate Names on the certificate -- not the CN, which is only matched against host names. Note that there are multiple kinds of SANs and the "normal" one is DNS...I'm not sure how you specify it in openssl, but hopefully this gives you enough of a shove in the right direction :-)

**Comment by dstroot** [comment]
@jefferai - I will pursue that and report back once I get something working.

**Comment by astrostl** [comment]
'the "normal" one is DNS'

That's what I'm running against. I'm using Puppet Server as a CA, and it doesn't have the capability to natively generate IP SANs, just DNS. Would there be any way to get Vault to ease up, and permit 127.0.0.1 if it's cited as a DNS SAN?

**Comment by jefferai** [comment]
Does it not work if `127.0.0.1` is a DNS SAN and/or the common name?

**Comment by astrostl** [comment]
It does not work if 127.0.0.1 is a DNS SAN:

```
$ /usr/local/bin/vault status
Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
```

```
$ openssl s_client -connect localhost:8200 | openssl x509 -noout -text | grep DNS:
verify return:1
                DNS:127.0.0.1, DNS:vault.mydomain.local
```

Making 127.0.0.1 the actual CN seems a bit crazy to me as a workaround :P

**Comment by jefferai** [comment]
I looked at Go's TLS stack. Go follows RFC 6125 Appendix B2:

>   In some cases, the URI is specified as an IP address rather than a
>   hostname.  In this case, the iPAddress subjectAltName must be present
>   in the certificate and must exactly match the IP in the URI.

So, no, there is no way to do this. I had thought the issue might be the OP including the port in the CN, but it seems Go follows the RFC here and as such it must be in the IP SANs.

**Comment by mudassaralvi** [comment]
Practice Test/Practice Exams
100% Money Back Pass Guarantee
Pass Any Certification Exam with https://www.certswarrior.com/
