### ISSUE TITLE
404s on website/content/docs/plugins/plugin-portal.mdx and initial "Looks like network is down..." message on some targets

### ISSUE THREAD

**Issue by johnsmartco** [hashicorp/vault#17905]
**Describe the bug**

* On [website/content/docs/plugins/plugin-portal.mdx, ](https://github.com/hashicorp/vault/blob/main/website/content/docs/plugins/plugin-portal.mdx) there appear to be a lot of links that 404.  
* Also, some links are valid (such as the DataStax Astra DB partner database link that we provided), however it appears the initial target page load returns a "Error. Looks like network is down."

**To Reproduce**

1. Go to  [website/content/docs/plugins/plugin-portal.mdx](https://github.com/hashicorp/vault/blob/main/website/content/docs/plugins/plugin-portal.mdx) 
2. Run a link checker...
3. Also click on a valid links in the Partners > Database section, such as https://github.com/hashicorp/vault/blob/main/website/content/docs/plugins/plugin-portal.mdx#database-1.  Notice that if you Refresh / Reload the opened target page, it loads properly. 

**Expected behavior**

- No 404s (maybe URLs provided by plugin partners are no longer valid, of course), and:
- Target pages that are valid URLs should open.  (Not sure if this issue is on our end - please advice - in the case of the target link for https://github.com/datastax/vault-plugin-secrets-datastax-astra ).

**Comment by ccapurso** [comment]
Hi, @johnsmartco! The link that you provided is for the source-controlled Markdown file. These files are bundled and deployed to HashiCorp's [Developer](https://developer.hashicorp.com/) site. The **Plugin Portal** docs can be found [here](https://developer.hashicorp.com/vault/docs/plugins/plugin-portal).

**Comment by johnsmartco** [comment]
@ccapurso , Chris thanks for providing the correct pointer.  Appreciated!

**Comment by ccapurso** [comment]
No problem, glad it helped!
