### ISSUE TITLE
Request forwarding mode: Wrong content-type header passed back

### ISSUE THREAD

**Issue by bkrodgers** [hashicorp/vault#1791]
With the new request forwarding mode enabled, the standby nodes do not properly pass the Content-type header through.  I put two unsealed nodes in my load balancer with the feature enabled.  Two identical requests, and one returns `Content-Type: application/json`, and the other returns `Content-Type: text/plain; charset=utf-8`.  In both cases, the response body itself is JSON.  The problem goes away when I take the standby node out of the load balancer, so it appears that it's the standby node sending the wrong response header.

This is a critical problem, as some JSON parsing libraries (notably the spray-json one many of my scala apps use) will reject deserializing a response if it comes back with the wrong type.  I can work around it for now by taking the standby nodes back out of the load balancer and turning off clustering.  I would like to take advantage of the new clustering though, so if it's possible to consider a quick 0.6.2 bug fix release for this, that would be very nice.

**Comment by jefferai** [comment]
> some JSON parsing libraries (notably the spray-json one many of my scala apps use) will reject deserializing a response if it comes back with the wrong type

Boy, that is awful. We can fix on our end, but I suggest pestering those library authors. If someone gives you something to decode, you should do what the programmer tells you, not what a potentially bug web server claims.

**Comment by bkrodgers** [comment]
Well, actually it's not quite accurate for me to have said that it's the decoding library that rejects it.  It's actually Spray's request/response pipelining.  It supports various unmarshallers, and by default, it appears to route to a given unmarshaller based on the content type.  The idea is that you can register different unmarshallers for different content types that you might get back.  The only one I have registered is a JSON one, since that's what I expect.  There probably is a mechanism to tell it to always route the response to that unmarshaller regardless of content type, but the default pipeline routes that way.  It is a powerful feature that allows for some nice generalization in your code, but yes, it does rely on accurate content type reporting from the server.  I don't think it's unreasonable to expect a rest service to respond with the proper content type.  

Obviously this is a bug and the intention is that vault will respond properly, so I wouldn't necessarily say it's a flaw in the library, or in my code that it relies on it.  But I do get your point, and it of course did bite me here.

**Comment by jefferai** [comment]
Ah, I'm not familiar with spray so now that you've explained it it totally makes sense for it to behave the way it does. In Vault we don't look at the content type; if you send it we parse it. Because, you know, there are bugs. When you described it as a parsing library I thought it was just being too pedantic :-)

Timeline on 0.6.2 is probably 2-3 weeks -- during HashiConf or right after. If you need I can send a build with this fixed... I'll probably get to fixing it tomorrow.

**Comment by bkrodgers** [comment]
Cool, if it's not a big deal to send me a build, I'd certainly welcome it.  The request forwarding mode with all nodes in the ELB appears to pretty much eliminate downtime when I have to do a rolling restart (for vault or coreOS upgrades), so I'd like to be using it.  If you don't get a chance, I can wait though.  Thanks!

**Comment by jefferai** [comment]
Hi Brian,

I believe this should fix it: https://www.dropbox.com/s/i2ee5ddex4sf603/vault-issue-1791.gz?dl=0 (it's linux/amd64).

Please note that this is applied against `master`. This shouldn't be a problem except for one possible change -- see https://github.com/hashicorp/vault/blob/master/website/source/docs/install/upgrade-to-0.6.2.html.md

If you need a build against 0.6.1, let me know!

**Comment by bkrodgers** [comment]
Thanks, this looks good!  I'm seeing application/json consistently now.  I don't think that change you linked to will cause any issues for me either.  Appreciate the hotfix!

**Comment by jefferai** [comment]
Great. Merging then!

**Comment by mfischer-zd** [comment]
> Boy, that is awful. We can fix on our end, but I suggest pestering those library authors.

FWIW, Hashicorp's own official Vault Ruby client can't tolerate the `text/plain` response header.

**Comment by grosser** [comment]
FYI monkeypatch for ruby-client is in https://github.com/hashicorp/vault-ruby/issues/88

**Comment by grosser** [comment]
will be fixed in vault 0.6.2

**Comment by jefferai** [comment]
> FWIW, Hashicorp's own official Vault Ruby client can't tolerate the text/plain response header.

Yeah, and that's terrible. :-)
