### ISSUE TITLE
Breaking with github.com/hashicorp/golang-lru version v1

### ISSUE THREAD

**Issue by verzth** [hashicorp/vault#17939]
#13 60.06 go: all: module github.com/hashicorp/golang-lru@upgrade found (v1.0.1), but does not contain package github.com/hashicorp/golang-lru
#13 60.06 go: all: module github.com/hashicorp/golang-lru@upgrade found (v1.0.1), but does not contain package github.com/hashicorp/golang-lru/simplelru
#13 60.13 make: *** [get-module] Error 1

**Comment by hsimon-hashicorp** [comment]
Can you please provide some context for this issue? What are you attempting to do in this scenario?

**Comment by verzth** [comment]
i just do go get all

**Comment by argenta-quanto** [comment]
`go get -u all`

**Comment by haraldrudell** [comment]
I find with github.com/99designs/gqlgen that wants github.com/hashicorp/golang-lru v0.5.4,
go tries to update to v1.0.1 and things fail after that.

> github.com/hashicorp/golang-lru: module github.com/hashicorp/golang-lru@latest found (v1.0.1), but does not contain package github.com/hashicorp/golang-lru


A get-around is to run `go get github.com/hashicorp/golang-lru@v0.5.4` when an update causes troubles

v0.5.4 is 2016 era
