### ISSUE TITLE
`vault login` should print MFA passphrase prompt on stderr

### ISSUE THREAD

**Issue by AdmiralNemo** [hashicorp/vault#17945]
**Describe the bug**
The `vault login` command prints the prompt for an MFA passphrase on the standard output stream.  This interferes with output redirection.  For example, without MFA, this command would store the token in the `VAULT_TOKEN` environment variable:

```sh
export VAULT_TOKEN=$(vault login -no-store -token-only -method=ldap username=…)
```

The LDAP password prompt (`Password (will be hidden): `) is printed to standard error.  The resultant token is printed to standard output.  All is well.

With MFA enabled, though, the `Enter the passphrase for methodID "…" of type "…":` prompt is printed to standard output.  It thus gets captured in the `VAULT_TOKEN` environment variable and is not visible on the screen.

**To Reproduce**
1. Enable LDAP auth and TOTP MFA
2. Run `export VAULT_TOKEN=$(vault login -no-store -token-only -method=ldap username=…)`
3. Observe that `Initiating Interactive MFA Validation` is printed to the screen, but `Enter the passphrase for method ID "…" of type "totp":` is not
4. Enter the TOTP code anyway
5. Observe that the `VAULT_TOKEN` environment variable contains the prompt string AND the token.

**Expected behavior**
The `Enter the passphrase …` prompt should be printed to standard error, making it visible to the user even if standard output is captured or redirected.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.12.1
* Vault CLI Version (retrieve with `vault version`): 1.12.1
* Server Operating System/Architecture: Linux/x86_64

**Comment by hghaf099** [comment]
Thanks for filing this ticket. For now, to get passed the issue you are observing you can simply pass in the MFA request header to the CLI command and get the result. Example: 
```
export VAULT_TOKEN=$(vault login -mfa="$mfa_method_id":"$totp_code" -no-store -token-only -method=ldap username=…) 
```
Note the added parameter in the CLI: `-mfa="$mfa_method_id":"$totp_code"`

I’ll take this feedback to product for further consideration, but in the meantime I’m going to go ahead and close this issue. Please feel free to reply again if there’s any problems with the workaround, though!”
