### ISSUE TITLE
AWS STS reports lease_renewable=true, but renew fails

### ISSUE THREAD

**Issue by sprohaska** [hashicorp/vault#1800]
AWS STS reports `lease_renewable=true`, but renew fails:

```
$ vault read aws/sts/...
Key            	Value
---            	-----
lease_id       	aws/sts/...
lease_duration 	3599
lease_renewable	true
...

$ vault renew aws/sts/...
Renew error: EOF
```

`secretAccessKeysRenew()`, see
<https://github.com/hashicorp/vault/blob/f59a69bc5237e076c9809fbb59ae96e37fcad581/builtin/logical/aws/secret_access_keys.go#L249>, states that it is a deliberate choice not to support renew for STS but return `nil` instead, which seems to cause the EOF.

I'm not sure how to fix this.

I'd expect that STS returns `lease_renewable=false`. But renewable seems to be a property of the backend.  If the backend implements `Renew()`, then all leases are renewable; see
<https://github.com/hashicorp/vault/blob/16766e272e4ede7966ce561bfb51708c3ddd7f58/logical/framework/secret.go#L39>.

Maybe the backend should implement renew for STS, but without actually extending the `lease_duration`. Renew would not fail with EOF anymore, but the behavior would be a bit unexpected, in my opinion. The renew would succeed, but it would not help the client.  The client would have to detect that the renew did not extend the duration. It would then have to create a fresh token instead.

**Comment by jefferai** [comment]
@vishalnayak maybe you can look at this this week. I'm pretty sure if a backend declares a particular Secret it's returning as not renewable it won't be renewable. Easy to test on e.g. Consul. If not we should probably change that, but pretty sure I did late last year.

**Comment by jefferai** [comment]
@sprohaska can you check your Vault logs? EOF shouldn't usually be getting returned regardless. Want to see if this the way the client is interpreting the 204 or if there's a panic happening in Vault, which would be a separate issue that needs to be fixed.

**Comment by sprohaska** [comment]
@jefferai no messages in the Vault log with the default logging settings; Vault 0.6.0.

**Comment by jefferai** [comment]
OK. Probably it's the client expecting a particular data type and seeing a 204.

**Comment by jefferai** [comment]
[vault-issue-1800.gz](https://github.com/hashicorp/vault/files/441285/vault-issue-1800.gz)

Can you give that a try? It's built on 0.6. with a patch to mark STS secrets as non-renewable.

**Comment by sprohaska** [comment]
vault-issue-1800.gz works as expected. `vault read` returns `lease_renewable=false` and `vault renew` returns '400 lease is not renewable'.

**Comment by jefferai** [comment]
Great!
