### ISSUE TITLE
Auto unseal for custom KMS services

### ISSUE THREAD

**Issue by soumyadeep-paul-ibm** [hashicorp/vault#18032]
**Is your feature request related to a problem? Please describe.**
Vault auto unseal is currently supported using the KMS services from AWS, Azure, google, Alibaba and Oracle cloud. Besides we understand we can use vault transit for auto unseal. We are currently running Vault on IBM Cloud and would like to use IBM Cloud key protect for auto unseal. 

**Describe the solution you'd like**
We would like to have a mechanism auto unseal from a generic KMS services, irrespective of the provider. I have gone through the documentation for the cloud specific unseal stanza and they are not very different from each other. 

**Describe alternatives you've considered**
A manual unseal requires to unseal the vault pod whenever there is a pod/node restart. 
We have also considered using a cross cloud KMS services but that didn't make sense. 

**Explain any additional use-cases**
There is a scope for standardisation here, and we can define the requirement for any supported KMS services. 

**Additional context**
If support for a generic KMS for auto unseal is not possible, please add support for IBM Cloud key protect
https://cloud.ibm.com/docs/key-protect/index.html

**Comment by cipherboy** [comment]
@soumyadeep-paul-ibm The generic solution I believe you're looking for here is the PKCS#11 interface.  You'd write a generic PKCS#11 library for the KMS provider, and could integrate it with any application. 

cc @acahn
