### ISSUE TITLE
Allow deleting KV v2 subkeys with patch-like command

### ISSUE THREAD

**Issue by nirvana-msu** [hashicorp/vault#18034]
`patch` command conveniently allows to add/modify existing subkey in KV v2 storage. However, there seems to be no way of deleting just a given subkey?

P.S. I'm sure this must have been raised/discussed somewhere, but I couldn't find any feature request here.

**Describe the solution you'd like**
I'd like there to be a simple patch-like CLI command that would allow removing single subkey.

**Describe alternatives you've considered**
I understand I can use `put` to overwrite the whole thing but then I need to re-create each of the other subkeys again - e.g. I could `put` one of the subkeys and then `patch` each of the remamining ones (except for the one I want deleted). It gets very tiring and error-prone though if the number of subkeys is large.

**Comment by hghaf099** [comment]
Thanks for filing this ticket. Actually, we do support removing subkeys using kv patch API. For that, the following example should work:
```
curl -v -XPATCH -H "X-Vault-Token: $VAULT_TOKEN" -H "Content-Type: application/merge-patch+json" --data '{"data": {"bar": null}}' "$VAULT_ADDR/v1/secret/data/foo"
```
Note the content type of `Content-Type: application/merge-patch+json` and also the data value which is set to `null`. 
This will remove the subkey and increase the version of the key.
However, we had not included the functionality in the CLI yet. I have opened a PR for that, and hopefully that will be merge soon. 
Thanks again for filing this ticket and looking forward to hearing more feature and enhancement requests.

**Comment by hghaf099** [comment]
The fix is merged, I am going to close this issue for now. Please feel free to reopen this issue for further discussion or open a new one with new items.
