### ISSUE TITLE
API naming consistency: role vs roles?

### ISSUE THREAD

**Issue by agperson** [hashicorp/vault#1805]
Was it a deliberate choice to in almost all cases use the plural form **roles** in URLs but in two specific cases use the singular **role**?  It is very confusing, and it seems like there is no circumstantial difference that would justify a different naming scheme.

**Pluralized paths (roles)**
- aws/roles
- cassandra/roles
- consul/roles
- mongodb/roles
- mssql/roles
- mysql/roles
- pki/roles
- postgresql/roles
- rabbitmq/roles
- ssh/roles
- auth/token/roles

**Singular paths (role)**
_Note: supports role**s** path for LIST only_
- auth/approle/role
- auth/aws-ec2/role

**Comment by jefferai** [comment]
aws-ec2 and approle are the two newest and better reflect  the preferred naming scheme going forward, since any given name reflects a singular role.

As it's a regex it'd be trivial to add support for both for any backend, if you're so inclined we might accept PRs to add that.

**Comment by vishalnayak** [comment]
The singular usage is the way to go. After discussing internally, it is decided that all the paths that have `roles` should *also* support `role` in the paths.

**Comment by vishalnayak** [comment]
There are no plans as of today to do this. Closing.
