### ISSUE TITLE
Allow agent log format to be specified

### ISSUE THREAD

**Issue by smrutimandal** [hashicorp/vault#18081]
**Is your feature request related to a problem? Please describe.**
At the moment, there isn't a way to set the log format of the vault agent to JSON.

**Describe the solution you'd like**
Vault agent config should allow setting log format.

**Describe alternatives you've considered**
At the moment, I am converting them to JSON. But it will be nicer if it can be done by the agent, just like the server log, audit log and agent injector logs are configurable.

**Additional context**
N/A

**Comment by hsimon-hashicorp** [comment]
Since this is a request for Vault Agent, I'm going to move this to the main vault repo. Thanks! :)

**Comment by hghaf099** [comment]
Thanks for filing this ticket. Would you please share your agent config? Or share the details of how did you try to set the logger format? I am asking because vault agent does indeed support setting log format to Json. You just need to set `log_format = "json"` in your agent config.

**Comment by VioletHynes** [comment]
Thanks for the report!

Closing this, as this should be fixed by #18031 (which is now merged) - afterwards, it can be configured by the `log-file` CLI option, the `log_file` HCL parameter, or the `VAULT_LOG_FORMAT` environment variable.
