### ISSUE TITLE
userpass auth returning '500: unsupported path'

### ISSUE THREAD

**Issue by bodymindarts** [hashicorp/vault#1809]
When following the [documentation](https://www.vaultproject.io/docs/auth/userpass.html) for userpass backend I am not getting the expected behaviour.

```
$ vault auth-enable userpass
Successfully enabled 'userpass' at 'userpass'!
$ vault auth -methods
Path       Type      Description
token/     token     token based credentials
userpass/  userpass
$ vault write auth/userpass/users/cf password=cf policies=default
Error writing data to auth/userpass/users/cf: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/userpass/users/cf
Code: 500. Errors:

* 1 error(s) occurred:

* unsupported path
```

Using vault v0.6.0. We have seen this behaviour both on our 3 node HA deployment (with consul backend) as well as using a dev server.

**Comment by jefferai** [comment]
Hi,

The reason for this is that the pattern defining that path is expecting three characters or more for the identifier, because the regex is allowing `-` and `.` but not as the first or last character. When using a two-character name it doesn't satisfy the regex, so the muxer can't find a path that this request can be sent to.

**Comment by bodymindarts** [comment]
Unless there is a specific reason not to support <3 char names it would be cool to merge https://github.com/hashicorp/vault/pull/1811 to fix this in the future.

```
diff --git a/logical/framework/path.go b/logical/framework/path.go
index 717afab..fa0c037 100644
--- a/logical/framework/path.go
+++ b/logical/framework/path.go
@@ -11,7 +11,7 @@ import (
 // Helper which returns a generic regex string for creating endpoint patterns
 // that are identified by the given name in the backends
 func GenericNameRegex(name string) string {
-       return fmt.Sprintf("(?P<%s>\\w[\\w-.]+\\w)", name)
+       return fmt.Sprintf("(?P<%s>\\w(([\\w-.]+)?\\w)?)", name)
 }

 // Helper which returns a regex string for optionally accepting the a field
```
