### ISSUE TITLE
Disable token login auth for web GUI

### ISSUE THREAD

**Issue by sbirl** [hashicorp/vault#18100]
**Is your feature request related to a problem? Please describe.**
Yup, as asked in [discuss.hashicorp.com](https://discuss.hashicorp.com/t/disable-token-login-auth-for-web-gui/45539)

**Describe the solution you'd like**
In a nutshell: We’re looking to disable/hide token logins at website.

**Describe alternatives you've considered**
None, but if there _are_ alternatives, please let us know. :D 

**Explain any additional use-cases**
We believe that token logins bypasses auditing measures; specifically who's using the master token instead of OIDC.

**Additional context**
I had tried to see if it was possible to send over 
```json
{
  "config": {
    "listing_visibility": "hidden"
  },
  "type": "token"
}
```
to 
`curl --header "X-Vault-Token: $VAULT_TOKEN" --request POST --data @/tmp/payload.json "${VAULT_ADDR}/v1/sys/auth/token"`
but that did not get applied.
  
----

**Comment by maxb** [comment]
As I already said over in the discuss.hashicorp.com thread:

Logging in with the token auth method isn’t really logging in - it’s really saying “I already logged in and here’s the evidence”.

You suggest here your goal is to prevent people using root tokens. The generally accepted - and documented - way to accomplish that is to revoke all root tokens as soon as the initial setup of viable auth methods has been completed.

**Comment by sbirl** [comment]
Ok ... documented where, please?

**Comment by maxb** [comment]
https://developer.hashicorp.com/vault/docs/concepts/tokens#root-tokens

**Comment by raskchanky** [comment]
What @maxb said is correct. Tokens are the fundamental unit of authentication inside Vault. If you possess a token, then you don't need to login to anything - logging in is what ultimately gives you a token, but the token itself is all Vault cares about. I'm going to close this for now, as it doesn't sound like there's anything actionable for the Vault team to do here, but I'm happy to reopen if that's not the case.
