### ISSUE TITLE
Vault interactive demo not working

### ISSUE THREAD

**Issue by zharvey-welltok** [hashicorp/vault#1813]
I went to your site and launched an [Interactive Demo](https://www.vaultproject.io/#/demo/2) and got to the screen where I need to run that `vault init -key-shares=1 -key-threshold=1` command and after 20 mins, nothing has happened:

<img width="1275" alt="screen shot 2016-08-30 at 4 27 02 pm" src="https://cloud.githubusercontent.com/assets/20440748/18105847/041f33f6-6ecf-11e6-8364-b7fe92eb2a72.png">

Is your interactive demo broke? *Das it, mang!*

**Comment by jefferai** [comment]
It's working for me. The app runs on Heroku which occasionally (at least once a day) reboots it. It's possible you got super unlucky and it got rebooted after you loaded it up, killing the connection. Try again!

**Comment by zharvey-welltok** [comment]
Well jeez, don't just close this ticket, at least give me a chance to try it out!!! Could be an issue with my browser or some other networking issue. I'm going to retry but I'll reopen this if it happens again...

**Comment by zharvey-welltok** [comment]
ok it worked :-/ moving forward with suspicion...

**Comment by jefferai** [comment]
@zharvey-welltok They're easy to re-open. :-D
