### ISSUE TITLE
How to format the output to json

### ISSUE THREAD

**Issue by puppy61** [hashicorp/vault#18132]
Hello, the output values default to map. How to format the output to json.
```
vault.hashicorp.com/agent-inject-template-app.json: >
          {{- with secret "secret/app/config" -}} postgresql://{{
          .Data.data.username }}:{{ .Data.data.password }}@postgres:5432/testapp
          {{- end -}}
```
Thank you.

**Comment by VioletHynes** [comment]
Hi there! If I understand your request properly, you can do it like this:
```
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/db-app" -}}
          {
          "postgresUsername": "{{ .Data.username }}",
          "postgresPassword": "{{ .Data.password }}"
          }
          {{- end }}
```

You can change the filename (such as to add `.json`) using the following annotation: https://developer.hashicorp.com/vault/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-inject-file

**Comment by maxb** [comment]
That approach will break if the data values contain values which disrupt the JSON formatting, though.

I would go for something like
```
{{- with secret "database/creds/db-app" -}}
{{ .Data | toUnescapedJSON }}
{{- end }}
```

**Comment by raskchanky** [comment]
Hi @puppy61. Thanks for reaching out! We use GitHub issues for bug reports and feature requests. Your question is a better fit for our [Community Forums](https://discuss.hashicorp.com/c/vault/30). If the answers that @VioletHynes and @maxb gave you are not sufficient, I invite you to post your question there. Thanks!
