### ISSUE TITLE
How do we handle single instance / multiple database credentials natively?

### ISSUE THREAD

**Issue by rossmohsenzadeh** [hashicorp/vault#18142]
**Is your feature request related to a problem? Please describe.**
We are trying to use vault as a way to create credentials in RDS and self hosted SQL Server. How do we handle single instance / multiple database credentials natively?
**Describe the solution you'd like**
Explanation on the best way to make this happen in both RDS and Self hosted SQL Server
**Describe alternatives you've considered**
Creating a single mount for all databases but this could end up being a support nightmare to maintain. 
**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by raskchanky** [comment]
Hi @rossmohsenzadeh. Thanks for reaching out! We use GitHub issues to track bugs and feature requests. Your question is better suited to our [Community Forums](https://discuss.hashicorp.com/c/vault/30). I invite you to post your question there. Thank you!
