### ISSUE TITLE
GO API - namespace list 

### ISSUE THREAD

**Issue by aram535** [hashicorp/vault#18148]
This got closed incorrectly: #18123 - recreating it

This is NOT regarding the vault client or API -- the functionality is missing from the Go client.

Describe the bug
This maybe just a lack of documentation or possibly a missing feature? I cannot find any API to list the child-namespaces in the go api. Currently the best workaround to do this is drop down to URL and do the query.

Environment:
Go 1.19.3
Vault 1.12.1
API Version: v1.8.2

**Comment by raskchanky** [comment]
I've responded in the original issue. It's unlikely that dedicated functionality will be added to the SDK to accomplish what you want, given how specific it is. It's definitely possible to do, though, as [my example](https://github.com/hashicorp/vault/issues/18123#issuecomment-1331497147) illustrates. I'm going to close this issue as a duplicate, but if there's more about this that you'd like to discuss, let's continue to do so in the original issue.
