### ISSUE TITLE
BUG: Too many arguments (expected 2, got 3)

### ISSUE THREAD

**Issue by droslean** [hashicorp/vault#18151]
```console
vault policy write read-only my-policy.hcl --address=http://localhost:8200 

Too many arguments (expected 2, got 3)
````

Following https://developer.hashicorp.com/vault/docs/commands/policy/write.

What I am doing wrong? How can I pass the `--address` flag?

**Comment by droslean** [comment]
The only workaround is to expose the address via the `VAULT_ADDR` environment variable. However, this BUG still stands.

**Comment by droslean** [comment]
@stevendpclark I tried all combinations. This is still not working

**Comment by stevendpclark** [comment]
Hi @droslean, 

I'm sorry but I'll need more information of what you are seeing,  such as version of vault (`vault version`) you are running and the error you are seeing as I can not reproduce the issue you are reporting.

```
❯ unset VAULT_ADDR
❯ vault server -dev -dev-root-token-id="devroot" -dev-listen-address=127.0.0.1:10000 &> /dev/null &
[1] 9267
❯ vault policy read --address=http://localhost:10000 read-only
No policy named: read-only
❯ vault policy write --address=http://localhost:10000 read-only my-policy.hcl
Success! Uploaded policy: read-only
❯ vault policy read --address=http://localhost:10000 read-only
path "secret/foo" {
  capabilities = ["read"]
}
```

**Comment by stevendpclark** [comment]
Hi @droslean, 

I'm not sure what to tell you, I still can not reproduce the error you are reporting. 

```
❯ unset VAULT_ADDR
❯ ~/.vvm/vault_1.7.2 server -dev -dev-root-token-id="devroot" -dev-listen-address=127.0.0.1:10000 &> /dev/null &

❯ ~/.vvm/vault_1.7.2 version
Vault v1.7.2 (db0e4245d5119b5929e611ea4d9bf66e47f3f208)

❯ ~/.vvm/vault_1.7.2 policy read --address=http://localhost:10000 read-only
No policy named: read-only

❯ ~/.vvm/vault_1.7.2 policy write --address=http://localhost:10000 read-only my-policy.hcl
Success! Uploaded policy: read-only

❯ ~/.vvm/vault_1.7.2 policy read --address=http://localhost:10000 read-only
path "secret/foo" {
  capabilities = ["read"]
}
```

You should be getting a usage output/errors for the first two in your list and the "Too many arguments" error for the 4th version listed. Only the third version in your list should actually work assuming you have setup VAULT_TOKEN properly, the `my-policy.hcl` file exists and it contains a valid policy.

**Comment by droslean** [comment]
I still get the errors. Perhaps I am using a problematic release. Let me try to replicate the issue with the latest version.

**Comment by raskchanky** [comment]
I'm also unable to replicate this using Vault 1.7.2.

![CleanShot 2022-12-01 at 15 00 24](https://user-images.githubusercontent.com/947/205177080-2a5e8cf5-967f-488c-a349-7e0f7a4d2456.png)

@droslean I suspect something specific to your environment is causing havoc here. I tried every command you listed in [this comment](https://github.com/hashicorp/vault/issues/18151#issuecomment-1333664179) and received varying results.

![CleanShot 2022-12-01 at 15 04 41](https://user-images.githubusercontent.com/947/205177661-cbe02f03-c13c-436d-b6a0-b864f24d731c.png)

![CleanShot 2022-12-01 at 15 05 10](https://user-images.githubusercontent.com/947/205177711-4bdce48e-8aac-42fe-a5c5-d8ca75ccf4b5.png)

![CleanShot 2022-12-01 at 15 05 48](https://user-images.githubusercontent.com/947/205177766-cf909232-985a-4b7d-9949-7d50fd48210b.png)

As you can see from my screenshots, I got different results every time. The 1st, 2nd, and 4th commands all failed, but I only received the error about too many arguments on the 4th command. The first 2 failed for different reasons. The third one succeeded.

If you're getting the "too many arguments" error for all 4 of those commands, it makes me think something is overriding your vault CLI command somehow. Is `vault` aliased to something? Is there something in your path named `vault` that's not the vault CLI tool?

Regardless, I don't think this is a bug with Vault.

**Comment by droslean** [comment]
@raskchanky It's not a bug. It's just how vault cli works... It seems that the global flags need to be in a specific place.
/shrug
