### ISSUE TITLE
Vault backup and migrate to another server

### ISSUE THREAD

**Issue by Niba-nazar** [hashicorp/vault#18150]
Hi,

I am new to hashicorp vault. Recently I installed a vault on one of my Linux servers. I tried adding some secrets using `vault kv put test-key/aws/s3-objects secret=xxxxxx`. 

Now I want my vault to move from the current server to another. For that, I have referred to many docs related to it. Unfortunately, I am finding those steps more complicated and unable to proceed with the migration.

Also found the below steps which I feel to try, but still facing an issue:
```
1) Seal the old vault , Stop Vault  
2) Started the new Vault Server (Didn't initialize as said)
3) Create migrate.hcl script
storage_source "file" {
path = "/vault/data/file"
}

storage_destination "consul" {
address = "consul:8500"
path = "vault/"
}
4) Run the vault operator migrate -config=migrate.hcl
5) Initialise and Unseal Vault
6) Success in migration but no secrets transferred

```
I amconfused, as I am not sure with the above steps, will I be able to move the entire vault from my server A to server B? Also I tried to take a backup first, but ended up with the error as below:
```
 consul snapshot save backup.snap
Error saving snapshot: Get "http://127.0.0.1:8500/v1/snapshot": dial tcp 127.0.0.1:8500: connect: connection refused

```

**Comment by raskchanky** [comment]
Hi @Niba-nazar. Thanks for reaching out! We try to reserve GitHub issues for bug reports and feature requests. An excellent venue for your question would be our [Community Forums](https://discuss.hashicorp.com/c/vault/30). I invite you to post your question there. Thanks!
