### ISSUE TITLE
Automatic Consul service registration fails when using Vault integrated storage

### ISSUE THREAD

**Issue by inflatador** [hashicorp/vault#18168]
### Automatic Consul service registration fails when using Vault integrated storage

1. Enable consul service registration as [described in Vault docs](https://developer.hashicorp.com/vault/docs/configuration/service-registration/consul) .
2. Restart vault service
3. See error:
```
Unexpected response code: 404 (Unknown check ID \"vault:[ip_redacted]:8200:vault-sealed-check\". Ensure that the check ID is passed, not the check name
...
"service_registration.consul: check unable to talk with Consul backend"
````
**Expected behavior**

Consul service registration works as described in Vault docs

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.12.1
* Vault CLI Version (retrieve with `vault version`): Vault v1.12.1 (e34f8a14fb7a88af4640b09f3ddbb5646b946d9c), built 2022-10-27T12:32:05Z
* Server Operating System/Architecture: Fedora 36 on x86_64

Vault server configuration file(s):

```
service_registration "consul" {
  address      = "127.0.0.1:8500"
}

```

**Additional context**
consul version: `Consul v1.14.1 Revision cac392a1 Build Date 2022-11-21T16:56:07Z`
Service registration works if I manually create a service definition HCL file for consul.

**Comment by raskchanky** [comment]
Hi @inflatador. Thanks for reaching out! Have you tried this on other versions of Consul? I'm curious if it's only a problem with 1.14.x.

**Comment by raskchanky** [comment]
I've attempted to reproduce the issue, but so far have not had any success. I built Vault from the commit SHA you specified, and am using the following config file:

```hcl
storage "raft" {
  path    = "/tmp/vault_1"
  node_id = "vault_1"
}

listener "tcp" {
  address = "127.0.0.1:8200"
  cluster_address = "127.0.0.1:8201"
  tls_disable = true

  telemetry {
    unauthenticated_metrics_access = true
  }
}

telemetry {
  prometheus_retention_time = "30s"
  disable_hostname = true
}

service_registration "consul" {
  address      = "127.0.0.1:8500"
}

disable_mlock = true
raw_storage_endpoint = true
api_addr = "http://127.0.0.1:8200"
cluster_addr = "http://127.0.0.1:8201"
log_level = "trace"
license_path = "/tmp/vault-full-featured.hclic"
```

I'm running Consul 1.14.1 in a docker container. I was able to start Vault up, init and unseal, and everything looks ok. I don't see anything abnormal in Vault's logs. In Consul's logs, I see the following, repeated every 5 seconds:

```
2022-11-30T19:40:31.259Z [DEBUG] agent: Node info in sync
2022-11-30T19:40:31.259Z [DEBUG] agent: Service in sync: service=vault:127.0.0.1:8200
2022-11-30T19:40:31.259Z [DEBUG] agent: Check in sync: check=vault:127.0.0.1:8200:vault-sealed-check
2022-11-30T19:40:31.259Z [DEBUG] agent.http: Request finished: method=PUT url="/v1/agent/check/pass/vault:127.0.0.1:8200:vault-sealed-check?note=Vault+Unsealed" from=172.17.0.1:55496 latency="569.16µs"
2022-11-30T19:40:35.894Z [DEBUG] agent: Check status updated: check=vault:127.0.0.1:8200:vault-sealed-check status=passing
```

Are there any additional details you can provide that would help me debug this further?

**Comment by inflatador** [comment]
@raskchanky  Very much appreciate the quick response! Upon further review, it looks like the issue was ACL-related. Sorry to waste your time, and have a great rest of your week!

**Comment by raskchanky** [comment]
@inflatador No worries! Thanks for the quick reply. I'm glad you were able to resolve so quickly.

**Comment by khumbal** [comment]
Thanks @raskchanky

Error: :vault-sealed-check\". Ensure that the check ID is passed, not the check name
This is because metrics are not enabled.
> ```hcl
> telemetry {
>     unauthenticated_metrics_access = true
>   }
> ```
