### ISSUE TITLE
File to Raft migration fails to unseal Vault post migration

### ISSUE THREAD

**Issue by lucasscheepers** [hashicorp/vault#18188]
I'm trying to migrate our Hashicorp Vault standalone with storage type `file` running in our RKE2 cluster to a Hashicorp Vault HA with storage type `raft`. But still getting some issues. [We're using the Helm chart version 0.22.0][1]. So these are the steps I followed:

1. Create a temporary Vault Raft running in RKE2 with 1 replica (don't initialize vault)
2. `Exec` into the old Vault container with the storage type `file`
3. Go to the `/vault/` folder and create a `raft` folder in it
4. Run the command `vault operator migrate --config migrate.hcl`
The migrate.hcl file looks like this:
```
storage_source "file" {
  path = "/vault/data/"
}

storage_destination "raft" {
  path = "/vault/raft/"
  node_id = "vault-raft-0"
}

cluster_addr="https://127.0.0.1:8201"
```
5. The migration is complete and it created a `vault.db` file into `/vault/raft/` and a `raft.db` file into `/vault/raft/raft/` including an empty folder called `snapshots`.
6. Then I copied this whole `/vault/raft/` folder to my local pc and copied it again to the temporary Vault Raft container. It has the same data storage mount path, so: `/vault/raft/`
7. After copying the files I re-deployed the temporary Vault Raft since the pvc won't be deleted and checked if it has still the copied `.db` files in it.
8. In the end I tried to unseal it, but after running the third command Iit returns the following message: `Error unsealing: context deadline exceeded`

Am I doing something completely wrong?

  [1]: https://artifacthub.io/packages/helm/hashicorp/vault

**Comment by raskchanky** [comment]
Hi @lucasscheepers. Thanks for reaching out! We generally try to keep GH issues for bug reports and feature requests. Your question is better suited to our [Community Forums](https://discuss.hashicorp.com/c/vault/30). I invite you to post it there. Including the output of the Vault server logs during the migration might also be helpful. Thanks!

**Comment by lucasscheepers** [comment]
Already did, but it's dead there. So I hoped someone of you could take a look @raskchanky

**Comment by feresberbeche** [comment]
I have the same issue, I am migrating from file to raft on k8s, I populated the /data/vault with the migrated files and I can't unseal, after the3rd key I get context deadline exceeded, the only difference is I left the node_id empty as it's an optional fields in the migrate config

**Comment by maxb** [comment]
Please follow the instructions already provided by raskchanky to post in the discuss.hashicorp.com forums, which are a more appropriate venue for seeking community support. You should start a NEW topic, and provide detailed information about **your** scenario, as no matter how similar you think your issue is to someone else's, you'll make it much harder for community volunteers to assist if you don't provide a full description of your own situation.

**Comment by feresberbeche** [comment]
for anybody finding this, 
After countless tries I figured it out, For people finding this use this migrate.hcl

>storage_source "file" {
  path = "/vault/file/"
}
storage_destination "raft" {
  path = "/vault/data/"
}
cluster_addr = "https://vault-0.vault-internal:8201"

cluster_addr should be the same as the env variable VAULT_CLUSTER_ADDR in the pod you're doing the migration
and you **should not define a node_id** as mentioned in the official documentation.
the unseal should work fine.
