### ISSUE TITLE
AWS DynamoDB region vs S3 region

### ISSUE THREAD

**Issue by JeanMertz** [hashicorp/vault#1818]
Currently both DynamoDB and S3 backends use the same `AWS_DEFAULT_REGION` environment variable.

This is problematic if:
- you want to use the first for `ha_backend` and the second for `backend`
- these tools are hosted in Europe (where DynamoDB requires the full `eu-central-1` and S3 requires simply `EU` as the region name
- you cannot set the configs using a file, but need to use environment variables.

I guess the easiest solution would be to use two different environment variables for these backends (maybe optionally?). Or perhaps this is a "wontfix", and I just can't configure the tool like this?

**Comment by jefferai** [comment]
> you cannot set the configs using a file, but need to use environment variables

Is this actually a problem? A configuration file is required for Vault anyways and these values aren't security sensitive.
