### ISSUE TITLE
Vault secrets move fails due to whitespace

### ISSUE THREAD

**Issue by maxforster1983** [hashicorp/vault#18236]
Previously we were able to successfully "rename" a users space by using the secrets move functionality by running:

vault secrets move 'Personal Secrets: user.example' 'Personal Secrets: user.newexample'

This is particularly of use in the event that users firstname.lastname is used and their last name changes as an example.

However since upgrading our Vault instance and since 1.11.4 this now returns an error:

Error moving secrets engine Personal Secrets: user.example/ to Personal Secrets: user.newexample/: Error making API request.

URL: POST http://x.x.x.x:8200/v1/sys/remount
Code: 400. Errors:

* 'from' path cannot contain whitespace

The same steps have been tested on 1.12.1 and 1.12.2 and the issue persists.

**Comment by VioletHynes** [comment]
This looks like a bug - you can create mounts with whitespace in the name and it seems like the initial intent was to disallow leading and trailing spaces, since mounts cannot have leading or trailing spaces. Thanks for the report! I'm going to look into a fix.

**Comment by VioletHynes** [comment]
This was introduced by https://github.com/hashicorp/vault/pull/14492

**Comment by VioletHynes** [comment]
Looks like this got closed with the merge of my PR.

Thanks for the report! This will be fixed in 1.14, and the next dot release for 1.11, 1.12, and 1.13.
