### ISSUE TITLE
dev-tls not working with different --dev-listen-address

### ISSUE THREAD

**Issue by kaitaklam** [hashicorp/vault#18259]
**Describe the bug**
start vault with -dev-tls, vault status given error Error checking seal status: Get "https://10.231.2.175:8200/v1/sys/seal-status": x509: certificate is valid for 127.0.0.1, not 10.231.2.175

**To Reproduce**
1. Run `vault server -dev-tls -dev-listen-address=10.231.2.175:8200 `
2. Run 'export VAULT_ADDR='https://10.231.2.175:8200'
3. Run 'export VAULT_CACERT='/tmp/vault-tls332888193/vault-ca.pem'''
4. Run 'export VAULT_TOKEN="hvs.HxWw4f20CAWzOWtcy8lrHWWC"'
5. Run `vault status`
6. See error
vault status
Error checking seal status: Get "https://10.231.2.175:8200/v1/sys/seal-status": x509: certificate is valid for 127.0.0.1, not 10.231.2.175

**Expected behavior**
status of vault

Following tutorial 'https://developer.hashicorp.com/vault/tutorials/getting-started/getting-started-dev-server' using -dev-tls
```

**Additional context**
Add any other context about the problem here.

**Comment by stevendpclark** [comment]
Hi @kaitaklam, 

Thanks for reporting the issue, you are indeed correct when specifying a listening address other than 127.0.0.1 the Vault client will not connect to the server as that parameter is not passed into the certificate generation.

**Comment by cipherboy** [comment]
I'm not sure I really like the idea of changing that, tbh. Adding another IP address makes it easy to misuse `-dev-tls` mode for non-dev purposes are my 2c here.

**Comment by raskchanky** [comment]
I agree with @cipherboy. Having TLS available only on localhost lets you test TLS specific things and having a configurable listen address lets you test things that need to interact with something other than localhost, but putting the two together I think would make it a little too easy to misuse. The extra effort required to configure TLS in a proper config file for listening on a non-localhost address is not egregious.

**Comment by cipherboy** [comment]
FWIW, Steve and I were chatting about it and the plumbing wouldn't be too hard to do. Steve raised some good points, which I do agree with, especially around aligning dev/prod safely. 

Perhaps reopening this is fine, Steve has a branch that fairly easily fixes this. But I'd like to see a discussion of how can we avoid people accidentally running dev-mode Vault in Prod and losing everything unexpectedly.

**Comment by cipherboy** [comment]
@tomhjp added this as part of #22657 so I'm going ahead and closing :-)
