### ISSUE TITLE
Custom username template for Kubernetes Secrets Engine

### ISSUE THREAD

**Issue by jbenassi** [hashicorp/vault#18293]
Several Secrets Engines support the ability to custom template usernames. It would be nice for auditing and esthetic reasons to have that same ability for the Kubernetes Secrets engine. Currently, using the GIthub Auth method in conjunction with generating Kubernetes service accounts, the format looks something like "v-github-j-admin-1670608173-ofz1spsgv8zbywvdli7we5i6" - We do get the auth method and the role name, it would be great if we could also have the ability to pull in other attributes and use them in the template. 

Thanks for creating Vault! It is an amazing platform.

**Comment by tvoran** [comment]
Hi @jbenassi, have you tried the [`name_template` role option](https://developer.hashicorp.com/vault/api-docs/secret/kubernetes#name_template)? I think it may do what you're looking for, since it uses the same templating system the other plugins use IIRC.
