### ISSUE TITLE
Does the /auth/token/accessors endpoint really exist?

### ISSUE THREAD

**Issue by k9ert** [hashicorp/vault#1830]
In the documentation, there is the above endpoint documented:
https://www.vaultproject.io/docs/auth/token.html

If i do something like this on my vault 0.6.0 installation:
curl  -X LIST -H "Content-Type: application/json" -H "X-Vault-Token: some-secret-token" $VAULT_URL/v1/auth/token/accessors

i get 

{"errors":["1 error(s) occurred:\n\n* unsupported path"]}

The blog-post doesn't mention that endpoint explicitely:
https://www.hashicorp.com/blog/vault-0.6.html#token-accessors

Searching for the functionality in the code doesn't come up with much (other than the other endpoints):
https://github.com/hashicorp/vault/search?utf8=%E2%9C%93&q=%22%2Fauth%2Ftoken%2Faccessors%22&type=Code

Is that even implemented? Or i'm doing something wrong?

**Comment by jefferai** [comment]
Hi @k9ert ,

The documentation on the website corresponds to the latest released version, which is 0.6.1. That endpoint appeared in 0.6.1.

**Comment by k9ert** [comment]
Ups, thanks for clarifying, my fault.

**Comment by aantono** [comment]
Just tried it with version 0.7.0 and it is failing for me with the same error

```
GET /v1/auth/token/accessors HTTP/1.1
> User-Agent: curl/7.40.0
> Host: <host>
> Accept: */*
> X-Vault-Token:<some token>
> 
< HTTP/1.1 404 Not Found
< Date: Fri, 21 Apr 2017 21:07:48 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host 127.0.0.1 left intact
```

I know I have tokens there, as I've just created a few prior to running this command.

**Comment by jefferai** [comment]
You're doing a read; you need to do a list. Use the LIST verb or append list=true query arg.

**Comment by aantono** [comment]
My bad... just realized I was using port 8500 (for consul) instead of 8200. Sorry for the confusion. :)
