### ISSUE TITLE
UI missing policies on Kubernetes roles

### ISSUE THREAD

**Issue by MarkRx** [hashicorp/vault#18361]
The UI does not currently provide a way to view or modify policies on a Kubernetes role. It only seems to provide a way to configure [token policies](https://developer.hashicorp.com/vault/api-docs/auth/kubernetes#token_policies). It currently must be done through either the API or the vault client.

The UI should be updated to support policies on Kubernetes roles in order to be more user friendly.

![image](https://user-images.githubusercontent.com/17504314/207421293-0b711f38-b482-4e08-a727-8285a3e0aac4.png)

**Comment by Monkeychip** [comment]
@MarkRx I'm looking into this and is the missing param on the UI form `[policies](https://developer.hashicorp.com/vault/api-docs/auth/kubernetes#policies)`? The API description is the exact same for both `policies` and `token_policies` so I want to make sure I'm looking at the correct missing param. Thanks for making the Issue.

**Comment by hsimon-hashicorp** [comment]
Hi @MarkRx - checking in with this as we're still awaiting your feedback from @Monkeychip's comment. Thanks!

**Comment by tvoran** [comment]
Oh you know what, I think `policies` is deprecated in favor of `token_policies`:

https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/530b5e913097cf7eea6ff1e2d7b977dd3dba2a16/path_role.go#L65-L69

We should probably mark it as deprecated [in the docs](https://github.com/hashicorp/vault/blob/main/website/content/partials/tokenfields.mdx) too.

**Comment by hsimon-hashicorp** [comment]
> Oh you know what, I think `policies` is deprecated in favor of `token_policies`:
> 
> [hashicorp/vault-plugin-auth-kubernetes@`530b5e9`/path_role.go#L65-L69](https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/530b5e913097cf7eea6ff1e2d7b977dd3dba2a16/path_role.go#L65-L69)
> 
> We should probably mark it as deprecated [in the docs](https://github.com/hashicorp/vault/blob/main/website/content/partials/tokenfields.mdx?rgh-link-date=2023-04-06T22%3A10%3A05Z) too.

Thank you for this note Theron! @yhyakuna I will assign this to you, if you don't mind. Thank you!

**Comment by yhyakuna** [comment]
The docs has been updated.
