### ISSUE TITLE
Need a quick help for an expired vault token

### ISSUE THREAD

**Issue by SydOps** [hashicorp/vault#1843]
How to renew the token/permission which has expired? What permission is required to create a new token?

    vault write auth/aws-ec2/role/dev-role bound_ami_id=ami-fce3c696 policies=prod,dev max_ttl=500h

refer: https://www.vaultproject.io/docs/auth/aws-ec2.html

Error is:
```

URL: POST https://vault.example.com/v1/sys/auth/aws-ec2
Code: 400. Errors:

* permission denied
```

**Comment by SydOps** [comment]
I can re-run the command successfully, but seems no differences.

```
vault auth-enable aws-ec2
vault write auth/aws-ec2/role/dev-role bound_ami_id=ami-fce3c696 policies=prod,dev max_ttl=500h
```

**Comment by jefferai** [comment]
@SydOps If your token has expired, you need to log in again. You're trying to write configuration to the aws-ec2 backend but without a valid token with access to do so, you won't be successful.

**Comment by SydOps** [comment]
@jefferai 

I have another valid token, and can login with `vault auth`, I also run below `vault write` command successfully, but still have same error:

```
vault auth
vault write auth/aws-ec2/role/dev-role bound_ami_id=ami-fce3c696 policies=prod,dev max_ttl=500h
```

So how to renew the expired token?

**Comment by SydOps** [comment]
So does it mean I need delete and write again?

**Comment by jefferai** [comment]
@SydOps you need to use the login endpoint against the role you created in the aws-ec2 backend.

**Comment by anthonyShelde** [comment]
Hi Jeff, do we also need to remove the original instance from the whitelist? so it can login again and retrieve a new token?

**Comment by jefferai** [comment]
If you are allowing reauthenticate you will need to either remove it or wait until it expires.

**Comment by anthonyShelde** [comment]
I have removed the instance from the whitelist, after attempting to re-auth,we are now facing an error below:

* Closing connection 0
{"errors":["failed to verify instance ID: error fetching description for instance ID i-07dsfsdffdsfdsfec7: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 8132ff25b-9df7b6-4a98-9194-d213223sdfsa\n"]}

I believe this is related to IAM ec2:DescribeInstance permissions issue here: (https://github.com/hashicorp/vault/issues/1582).

**Comment by anthonyShelde** [comment]
We have it working now. We just have to note that you must remove the instance-id from the vault (via delete auth/aws-ec2/identity-whitelist/$instance-ID) is required if you are to renew an expired token. 

Thanks.
