### ISSUE TITLE
Corrupted vault audit log?

### ISSUE THREAD

**Issue by 007jingtangmu** [hashicorp/vault#1844]
Hi,

I found in our vault audit log there are some "corrupted" log entry, which is very long with recursive structure, here is an example: [super long log entry](https://gist.github.com/007jingtangmu/fed74c71719d853cf76ec70b78f08bb5).
It seems to be another multithread issue to me. There are totally 15 entries in our one-month audit log. It brings a lot of trouble to our log parsing infrastructure, as if you try to parse the json, thousands of keys could be parse from one single line.

This issue happened also before I adopted the customized build for vault hanging issue. 

Regards,

**Comment by jefferai** [comment]
How is this corrupted? How is it recursive? This looks totally straightforward and normal. You just have a lot of mounts.

**Comment by 007jingtangmu** [comment]
I see. I did not expect that the details of "vault mounts" operation will be displayed in audit log. In my understanding it is not necessary.

**Comment by jefferai** [comment]
Every request and response is recorded!
