### ISSUE TITLE
Searching string in vault from the top menu

### ISSUE THREAD

**Issue by liorazroel** [hashicorp/vault#18464]
I want to search from a list of passwords in the vault specific password by key according to a string that I will give in the top menu of vault:
![Screen Shot 2022-12-19 at 17 06 10](https://user-images.githubusercontent.com/52318755/208456682-c3a35f26-c181-4c5f-bd82-0a644187e6f8.png)

**Comment by hsimon-hashicorp** [comment]
Closing as a duplicate of #17325 - please check there for updates!
