### ISSUE TITLE
Init and Unseal Documentation Unavailable When Setting up Vault

### ISSUE THREAD

**Issue by nrocine** [hashicorp/vault#185]
[ec2-user@ip-172-31-11-182 mnt]$ vault help -address="http://127.0.0.1:8200" init
    Error reading help: Error making API request.

    URL: GET http://127.0.0.1:8200/v1/init?help=1
    Code: 500. Errors:

    * Vault is sealed   

    [ec2-user@ip-172-31-11-182 mnt]$ vault help -address="http://127.0.0.1:8200" unseal
    Error reading help: Error making API request.
    
    URL: GET http://127.0.0.1:8200/v1/unseal?help=1
    Code: 500. Errors:
    
    * Vault is sealed

Maybe this is intentional, but it seems to defeat the usability of the builtin documentation if you can't confirm the necessary commands to get started. (TLS disabled on server.)

Thanks!

**Comment by armon** [comment]
The UX around this has been improved for 0.2
