### ISSUE TITLE
A new `vault patch` CLI command is needed

### ISSUE THREAD

**Issue by maxb** [hashicorp/vault#18507]
One of the more helpful things about the Vault CLI, is that it mostly provides elegant CLI syntax for performing various HTTP API calls.

However, in recent Vault versions, the HTTP `PATCH` verb has started to be used. Support for this is **missing** in the Vault CLI.

I'm not referring specifically to KV v2 `PATCH`, for which there is `vault kv patch ...`. Rather, I'm thinking about APIs such as `pki/issuer/:issuer_ref` which require the `PATCH` method to perform reconfiguration of options, without wiping everything that has already been set. There is no way to invoke this from the CLI.

I propose the existing family of "basic HTTP operation" Vault CLI commands (read, write, list, delete) should be supplemented by the addition of `vault patch`, which functions identically to `vault write`, except that it uses the `PATCH` HTTP method.

**Comment by cipherboy** [comment]
@maxb This should already be in your 1.13 `main` builds from #17650, let me know if that doesn't work :-)

**Comment by maxb** [comment]
Ah, right... I was, of course, trying to use 1.12.2 to configure 1.12.2's PKI engine when I ran into this.

It would be kind of nice to backport to 1.12 since it's the natural way to configure PKI in 1.12, but I guess that's pretty low importance in the grand scheme of things.

**Comment by cipherboy** [comment]
Yeah, since this is a new feature, we're internally hesitant to backport it... 1.13 will have it and then you can run newer CLI versions if desired :-)
