### ISSUE TITLE
PR check `Security Scan / scan (pull_request)` looks like it always fails on all PRs from the community 

### ISSUE THREAD

**Issue by maxb** [hashicorp/vault#18511]
e.g. #18510

**Comment by cipherboy** [comment]
I think this is expected as you don't have clone access to the internal HCP scanning repo, but cc @mickael-hc and @mcollao-hc just in case. 

It doesn't block merge though, so I wouldn't worry too much about it, but I do wonder if there's an easy way to run the scan internally and share the relevant results?

**Comment by maxb** [comment]
Or at least, it could detect that it can't operate, and avoid placing a "failure" status on the PRs, which usually suggests a PR needs further work.

**Comment by mcollao-hc** [comment]
It's due GitHub not sharing repo secrets with community PRs. I'll look into adding some logic to silently pass until we can open source the project.

**Comment by maxb** [comment]
Would you be able to also look at `Project triage / Add issue or PR to projects` such also seems to be failing on all community PRs for the same reason?

**Comment by VioletHynes** [comment]
Addressed in https://github.com/hashicorp/vault/pull/22351 - this now skips this job on community PRs.
