### ISSUE TITLE
mssql backend cannot write role - driver: bad connection error

### ISSUE THREAD

**Issue by rajanadar** [hashicorp/vault#1852]
Vault Version: 0.6.1
OS Version: Windows 10

**Repro Steps:**
1. have a MS SQL Server running on a default instance. (localhost)
   SQL Version is 2014
   all TCP protocols etc. opened up in Client Protocols for MS SQL Server
2. have the connection string as:

server=localhost;port=1433;user id=sa;password=raja;database=master;app name=vault;
1.  invoke the API to configure the connection: /mssql/config/connection provide connection_string and also verify_connection as true. it succeeds, which means the connection string was valid.
2. invoke the API to write the role: /mssql/roles/testrole
   with a good SQL definition. (from the Vault Documentation site. also tried 'SELECT 1')

**Observed Error:**

500 InternalServerError. driver: bad connection

it doesn't matter what SQL statement is used. it always fails on this.

weird thing being that the verify connection had succeeded. i thought writing to the roles endpoint is a vault-only thing, and shouldn't involve any actual SQL server communication.

let me know if more information is needed.

**Comment by jefferai** [comment]
The verify connection code simply does an open; the code called when setting a role does more, see https://github.com/hashicorp/vault/blob/master/builtin/logical/mssql/backend.go 

I'm guessing one of those other statements is causing the issue, or something changed between your two calls. You may want to run the equivalent logic in a CLI and see if you can reproduce.
