### ISSUE TITLE
mssql backend readconnectioninfo api returns empty connection string

### ISSUE THREAD

**Issue by rajanadar** [hashicorp/vault#1853]
Vault Version: 0.6.1
OS Version: Windows 10

Repro Steps:

have a MS SQL Server running on a default instance. (localhost)
SQL Version is 2014
all TCP protocols etc. opened up in Client Protocols for MS SQL Server

1. have the connection string as:
server=localhost;port=1433;user id=sa;password=raja;database=master;app name=vault;

2. invoke the API to configure the connection: **/mssql/config/connection** 
provide connection_string and also verify_connection as true. it succeeds, which means the connection string was valid.

3. now invoke **/mssql/config/connection** with a GET call to read the connection info back.

**observation:**

1. the returned connection string is blank. expected the original value here. (like mongodb)
2. the max connection seems to be right. which means, the data structure is being hit.

3. nit: the returned response seems to be missing the "verify_connection" field altogether.
4. nit: this read connection api is not documented in the web site.

**Comment by jefferai** [comment]
If it's not documented it's not implemented. My guess is the author didn't fully implement it so intentionally left it out.

PRs to fully implement would be great.

**Comment by rajanadar** [comment]
oh, okay. i based it off the changelog

secret/mssql,mysql,postgresql: Reading of connection settings is supported in all the sql backends [https://github.com/hashicorp/vault/pull/1515]

**Comment by rajanadar** [comment]
looking into #1157 it seems it is for mysql and postgresql, not mssql.
