### ISSUE TITLE
api field naming consistency for ttl and lease fields

### ISSUE THREAD

**Issue by rajanadar** [hashicorp/vault#1854]
Vault Version is 0.6.1
OS: Windows 10

so far, it seems 3 variations are going around for lease fields for secret backend credentials:

1. for aws secret backend, when you configure the credential's lease values: (/aws/config/lease)
the field names are: **lease and lease_max**

2. for mongodbsecret backend, when you configure the credential's lease values: (/mongodb/config/lease)

the field names are: **ttl and max_ttl**

3. for mssql secret backend, when you configure the credential's lease values: (/mssql/config/lease)
the field names are: **ttl and ttl_max**

the description and meaning for the 2 fields seems to be same across all these varied names.
it would be good to standardize them.

also, the returned values from the apis, are sometime in converted "seconds" (integers) and sometimes as "1m1s" string values.  i think the string values may not be very useful for clients.. the integer seconds might be clearer and less error prone.

**Comment by jefferai** [comment]
Consistency is a known issue. If you'd like you fix specific items, while retaining backwards compatibility, please open appropriate PRs. Otherwise we address these over time.
