### ISSUE TITLE
Issue with TLS configuration for cluster_address bind

### ISSUE THREAD

**Issue by erkexzcx** [hashicorp/vault#18580]
I am trying to setup a HashiCorp Vault in a highly available manner. I will be having 3 servers, but currently I am stuck with configuration, TLS part regarding `cluster_address` bind.

Here is my configuration:
```hcl
listener "tcp" {
   address = "127.0.0.1:8200"
   cluster_address = "127.0.0.1:8201"

   # Generated self-signed certificates for testing if Vault starts. Vault itself does not generate self-signed certificates?
   tls_cert_file = "/etc/vault.d/vault.crt"
   tls_key_file  = "/etc/vault.d/vault.key"
}

storage "raft" {  
   path = "/path/to/vault/data"
   node_id = "example1"

   retry_join {
      leader_api_addr = "https://example.com"
   }
}

cluster_name = "example"
api_addr = "https://example.com"
cluster_addr = "https://example1.com:8201"

ui = true
disable_mlock = true
```

According to documentation, in `tcp` listener block, I can either enable or disable TLS for `address`, but `cluster_address` is always enforced to HTTPS. Does HashiCorp Vault generate self-signed certificates or not? How does it work?

Welp, I got it running, `127.0.0.1:8200` seems to be working and having HTTPS as expected, but `127.0.0.1:8201` does not seem to work at all.

For example `curl`:
```
$ curl --insecure "https://127.0.0.1:8201/"
curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
```

Or `openssl`:
```
openssl s_client -showcerts -connect 127.0.0.1:8201
CONNECTED(00000003)
140319426033472:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:ssl/record/rec_layer_s3.c:1544:SSL alert number 80
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 289 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

HashiCorp Vault does not show any error or anything else related to this. Also I am unable to find any documentation on this. Can you clarify if this is expected behaviour?

```
$ vault version
Vault v1.12.2 (415e1fe3118eebd5df6cb60d13defdc01aa17b03), built 2022-11-23T12:53:46Z
```

**Comment by hsimon-hashicorp** [comment]
You can use Vault to generate the certificates: https://developer.hashicorp.com/vault/tutorials/secrets-management/pki-engine

**Comment by maxb** [comment]
For certificate generation in general, yes, but this issue is specifically about the cluster port, 8201, though.

The cluster port 8201 always uses certificates that Vault generates internally - the server administrator is neither required nor permitted to specify their own.

Port 8201 is exclusively connected to by other Vault servers, and the protocol details are an undocumented implementation detail.

It is technically HTTPS, but as connections use complex custom ALPN, you should effectively consider it to be opaque TCP, and not something you can interact with via a generic HTTP client.

(This is all information I've learnt by practical experience, inference, and reading the source code - I agree the documentation is incomplete in this area.)

**Comment by hsimon-hashicorp** [comment]
Thank you for confirming! It appears that it is in the HA documentation, under server-to-server communication: https://developer.hashicorp.com/vault/docs/concepts/ha#server-to-server-communication

> For the request forwarding method, the servers need direct communication with each other. In order to perform this securely, the active node also advertises, via the encrypted data store entry, a newly-generated private key (ECDSA-P521) and a newly-generated self-signed certificate designated for client and server authentication. Each standby uses the private key and certificate to open a mutually-authenticated TLS 1.2 connection to the active node via the advertised cluster address. When client requests come in, the requests are serialized, sent over this TLS-protected communication channel, and acted upon by the active node. The active node then returns a response to the standby, which sends the response back to the requesting client.

I will go ahead and close this issue now. Thanks!

**Comment by ebuildy** [comment]
What about when there is bad cert error:

```
{"@level":"debug","@message":"forwarding: error sending echo request to active node","@module":"core","@timestamp":"2024-04-21T17:56:20.646062Z","error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: tls: failed to verify certificate: x509: certificate is valid for fw-c662f8a7-1ff3-33e9-c4fb-28a37bcbdf43, not fw-fd671ed2-3dbe-2f7a-7433-bb1ac5d3d632\""}
```

**Comment by RachanaDhaked** [comment]
I am also facing similar kind of issue 

I have a raft cluster of 5 node vault version1.18


The **Vault nodeA** is currently in an unhealthy state within the Raft cluster despite all nodes being present and the cluster leader (node B) being active and healthy. While vault operator raft list-peers shows all nodes including nodeA as part of the cluster, nodeA is unable to properly communicate with the leader and other peers. Its logs indicate repeated failures in the Raft pre-vote and election processes, with errors such as `tls: unrecognized name, tls: internal error, and tls: no certificates configured, suggesting TLS handshake issues.` This results in the node being unable to forward requests to the active node and failing to participate correctly in leader elections, causing it to reference a stale or outdated active node internally. Attempts to restart the **nodeA** do not resolve the problem, and TLS connectivity checks with the other nodes, although seemingly successful via openssl s_client, do not reflect the errors seen by Vault itself. Overall, the node is stuck in a state where it is recognized as a cluster member but cannot maintain healthy communication with the leader, leaving it out of sync with the current cluster state.



I noticed when I view the output of `vault status` in node A 
it was referring as a standbynode but  the active leader node correct it was referring to stale leader node

Anyone please help with resolving this issue.
