### ISSUE TITLE
Potential vulnerability in wildcard processing

### ISSUE THREAD

**Issue by rommanio** [hashicorp/vault#18591]
**Describe the bug**

An asterisk (`*`) in `allowed_parameters` `policies` value may lead to privilege escalation.

**To Reproduce**
Write policy:
```hcl
path "identity" 
{
  capabilities = ["read", "list"]
}

path "identity/entity" 
{
  capabilities = ["create", "read", "update"]
  allowed_parameters = {
    "name" = ["test-service-*"]
    "policies" = ["test-approle-*"]
    "*" = []
  }
}

path "identity/entity/*"
{
  capabilities = ["read"]
}
```
Apply to some test user and login with this user credentials.
Command
```
 vault write identity/entity name="test-service-test10" policies="test-approle-empty, admin"
```
returns successfully and create identity entity with given policies.

**Expected behavior**
I want to restrict policies only to `test-approle-*`, for example, `policies="test-approle-empty, test-approle-list-read-shared-secrets"`

**Environment:**
* Vault Server Version (retrieve with `vault status`): latest stable (1.12.2)
* Vault CLI Version (retrieve with `vault version`): latest stable (1.12.2)
* Operating system/Architecture: Vault in Docker in production mode.

Vault server configuration file(s):

```hcl
listener "tcp" {
    address = "0.0.0.0:8200"
    purpose = "api"
    tls_cert_file = "/vault/tls/api/fullchain.pem"
    tls_key_file = "/vault/tls/api/privkey.pem"
}

listener "tcp" {
    address = "0.0.0.0:8201"
    purpose = "cluster"
    tls_cert_file = "/vault/tls/cluster/fullchain.pem"
    tls_key_file = "/vault/tls/cluster/privkey.pem"
}

storage "raft" {
    path = "/vault/raft"
    node_id="vault1.**sensetive**"
}

plugin_directory="/vault/plugins"
cluster_addr = "https://vault1.**sensetive**:8201"
api_addr = "https://vault.**sensetive**:8200"
ui = "true"
```

**Comment by hsimon-hashicorp** [comment]
We ask community members to please email security@hashicorp.com when reporting potential security or vulnerability issues. cc @mickael-hc

**Comment by maxb** [comment]
This one's a bit difficult to categorise ... Vault is functioning as designed, but the nature of the design is that it is easy for a user without very deep understanding of how Vault processes parameters, to write an insecure configuration without being aware of it.

I have encountered the same issue at my place of work too. The issue is that `allowed_parameters` wildcard support cannot be safely used to secure a field of type `TypeCommaStringSlice` because any use of a wildcard permits adding arbitrary extra entries following a comma.

**Comment by mickael-hc** [comment]
Hey @maxb, thanks for opening this issue and documenting in detail.

This is a known limitation of the parameter constraints when using the[ glob (*) pattern](https://www.vaultproject.io/docs/concepts/policies#policy-syntax), and documented as the last example of[ the policy docs](https://www.vaultproject.io/docs/concepts/policies#allowed_parameters).
To enforce more granular policies, we would recommend using Sentinel[ endpoint governing policy](https://learn.hashicorp.com/tutorials/vault/sentinel). A feature request to introduce further flexibility for ACL policies is tracked in[ https://github.com/hashicorp/vault/issues/8789](https://github.com/hashicorp/vault/issues/8789).

Based on your feedback I have opened https://github.com/hashicorp/vault/pull/18593 in an attempt to make this behavior more clear. I’m going to close this issue, but please feel free to directly contact [security@hashicorp.com](mailto:security@hashicorp.com) for any future security concerns with Vault or other HashiCorp products.

**Comment by maxb** [comment]
Hi @mickael-hc ,

I'm not really convinced Sentinel EGPs are a good alternative here - and I say that as someone whose employer already pays for Vault Enterprise.

First, there's the issue of them being EGPs, and therefore not linked to identity - it's difficult to give different users different access.

OK, fine, maybe use RGPs instead... that's also not ideal. First, you have to define an ACL policy that gives extremely wide access, and then hope/trust that ACL policy will only ever be used in conjunction with the Sentinel policy it is supposed to be combined with. You then have to deal with the fact that the `auth/token/create` endpoint's default behaviour is to allow users to generate tokens with a subset of policies, which can potentially remove restrictions enforced by an RGP.

Except, there's still an issue - Vault is permissive of a couple of different formats of input to be parsed by `TypeCommaStringSlice`, and replicating that parsing accurately in Sentinel is difficult-to-impossible.

#8789 looks kind of complicated but I am interested in the area. Does HashiCorp have any plans to do anything along those lines? Would a PR from the community in this area be accepted? Possibly preceded by more discussion to firm up a design first?

**Comment by hsimon-hashicorp** [comment]
Hi @maxb! As always, your enthusiasm is much appreciated. We discussed this internally, and while we'd love for this system to be overhauled, there are some barriers to doing so. A thorough design, review, and acceptance from other affected products would be required, and that would be far easier to do "in-house". As you are a Core Contributor, please know I'll be keeping this in mind in case the situation changes or if there's other areas we could use your help with. Your expertise and outside perspective are highly valued. Thanks again for your interest!
