### ISSUE TITLE
Varantfile is missing

### ISSUE THREAD

**Issue by dhawal55** [hashicorp/vault#186]
The Varantfile is missing in the repo (gitignore is ignoring it)

**Comment by armon** [comment]
This was done on purpose, I was using Vagrant locally to test the various secret backends, but its not necessary for Vault.

**Comment by dhawal55** [comment]
The documentation refers to using the Vagrantfile. Maybe, update the documentation:
"Alternatively, you can use the Vagrantfile in the root of this repo to stand up a virtual machine with the appropriate dev tooling already set up for you."
