### ISSUE TITLE
Rekey operation cannot be performed against non-leader

### ISSUE THREAD

**Issue by ianwestcott** [hashicorp/vault#1862]
I'm running Vault 0.6.1 in HA mode, with Consul as the storage backend. On a server which is not the leader, I get a 500 error when trying to run `vault rekey`:

```bash
$ vault rekey
Error reading rekey status: Error making API request.

URL: GET https://127.0.0.1:8200/v1/sys/rekey/init
Code: 500. Errors:

* Vault is in standby mode
```

On the server which is the leader, I am able to run the same command without issue.

I have found issues #311 and #499, which point to similar problems with other endpoints, but neither mentions rekey specifically.

**Comment by ianwestcott** [comment]
Update: It looks like `/sys/seal` is similarly affected.

**Comment by jefferai** [comment]
Hi @ianwestcott ,

I've put a PR in that should fix this. I'm at HashiConf so can't really work on testing until next week -- if you want to give that a try and let me know how it works for you, much appreciated. Otherwise I'll circle back around.

**Comment by ianwestcott** [comment]
@jefferai – thanks for looking into this so quickly! 

I've figured out how to build vault against the branch in your PR, and installed the binary in my test environment. (Running `vault version` now yields `Vault v0.6.2-dev ('ec09535733ced218c125e1148e9b2dba7c45639c')`). Unfortunately, now when I run `vault rekey` on a server which is not the leader, it hangs for a while, then returns the following:

```
Error reading rekey status: Get https://REDACTED/v1/sys/rekey/init: dial tcp XXX.XXX.XXX.XXX:443: i/o timeout
```

What's notable about this error is that the timeout is on port 443; while I do have TLS enabled on this cluster, the Vault service is still listening on the default port of 8200, so I'm not sure why Vault is attempting to connect on port 443 in this case. I have verified (using `telnet`) that the standby server is able to connect to the leader on port 8200, so it is not a firewall issue.

**Comment by jefferai** [comment]
What's your `VAULT_ADDR`?

**Comment by ianwestcott** [comment]
I don't have `VAULT_ADDR` set in the environment on these servers, but I do have `VAULT_TLS_SERVER_NAME` set to the FQDN of the server, e.g. `vault-host.example.com`. Note that there's no scheme or port in that value.

**Comment by jefferai** [comment]
What are the `redirect_addr` (or `advertise_addr`) values for your Vault nodes?

**Comment by ianwestcott** [comment]
Ah-ha: `VAULT_ADVERTISE_ADDR` is set to the FQDN of each instance, including the scheme but without an explicit port, e.g. `https://vault-host.example.com`. I gather that value is causing Vault to infer port 443 instead of 8200? I'll make the port explicit there and see if that helps.

**Comment by jefferai** [comment]
That would do it!

**Comment by jefferai** [comment]
Rather than have an empty port infer 8200 we are using the well-understood semantics of `https` defaults to port 443. Which I suppose aren't well-understood in this case, but... :-)

**Comment by ianwestcott** [comment]
That makes perfect sense. I had just overlooked the need to be explicit when assigning that value. 😄 

So with my settings corrected, and using that same build off the `issue-1862` branch, `vault rekey` now gets one step further on the standby server in that it allows me to enter a key share for the rekey, but then I run into a different error:

```bash
$ vault rekey
Rekey operation nonce: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Key (will be hidden):  # pasted key here
Error attempting rekey update: Error making API request.

URL: PUT https://127.0.0.1:8200/v1/sys/rekey/update
Code: 400. Errors:

* Vault is in standby mode
```

**Comment by jefferai** [comment]
Drat, missed a spot. I've updated the branch.

The good news is I'm back from HashiConf so I'll have a chance to dig in and test this myself soon. But I think it should work now...

**Comment by ianwestcott** [comment]
Cool, will test again. Out of curiosity, would `/sys/rekey/backup` need to be included in the fix as well? (as per https://www.vaultproject.io/docs/http/sys-rekey.html) I haven't implemented PGP encryption of keys in my environment, so I'm not equipped to test that part of the process.

**Comment by jefferai** [comment]
Because that's a token-authenticated endpoint it's handled by a different code path and should(!) already redirect properly.

**Comment by ianwestcott** [comment]
Okay, with a newly compiled binary (`Vault v0.6.2-dev ('8dafd3f6a33d7c55cf75ffe6fdefa55e29b4744b')` I was able to rekey my cluster from start to finish via the API of a standby node. Thanks again!

**Comment by jefferai** [comment]
Neato!

Closing this in favor of the PR.
