### ISSUE TITLE
Sudden error when trying to authenticate in Vault UI via OIDC provider

### ISSUE THREAD

**Issue by voiprodrigo** [hashicorp/vault#18648]
Hi,

I’m suddenly having a OIDC login issue in the UI after weeks of normal operation with Vault 1.12.2. 

I click on “Sign in with OIDC provider”, and almost immediately the main window shows “Error: The provider window was closed before authentication was complete. Please click Sign In to try again.”. 
Then even though authentication to the OIDC identity provider (within the pop-up window) is successful, the pop-up shows message "Error: Cannot read properties of null (reading 'postMessage')", and Vault does not follow-through with the flow.

BUT, the OIDC workflow when initiated via the CLI works just fine. I get the OIDC provider URL, load it in the browser, authenticate, get the local URL, call the URL locally with curl, get the token and login with the token in the UI just fine.

The problem surfaced suddenly, there was no changes to configuration or node restarts. The only thing I tried was to demote the active to elect another, but that didn't make any difference (unsurprisingly).

All browsers fail, tested Brave, Chrome, Firefox, Safari, using “incognito” windows, so it’s not browser specific, extension related or pop-up blocker related. Issue affects other people as well, so not specific to my computer.

Can’t see anything interesting in the logs, and I run with DEBUG level.

Seems like a bug, because I've had this configuration running for more than a year, over multiple versions of Vault, including latest. Any suggestion on things to check?

**Comment by voiprodrigo** [comment]
Traced packets between browser client system and IdP provider, and also between Vault active node and IdP provider.
No packets detected, which suggests the OIDC flow is not even being initiated past the UI in the browser.

**Comment by voiprodrigo** [comment]
Disabled OIDC (vault auth disable oidc). Re-configured. Issue persists.
Any hints?

**Comment by voiprodrigo** [comment]
Update:

Downgraded to 1.11.4, did not help.

IdP logs were checked, when using the UI, Vault does not reach IdP to request OIDC access token.

Temporarily enabled userpass auth method, created a user. 
When attempting to login via UI, browser is redirected back to the sign-in page, without any error visible or logged.
Userpass login via CLI works to create token, then token can be used in UI.

As it is, UI is unusable for logins, except via Token method. 
I'm at a loss here.

**Comment by zofskeez** [comment]
@voiprodrigo thanks for reporting this. I've been trying to recreate using the [Auth0 tutorial](https://developer.hashicorp.com/vault/tutorials/auth-methods/oidc-auth) but haven't had any luck. The error message you referenced should only display if the popup window was closed. Could you provide more information like OS and browser version that might help track this down?

**Comment by voiprodrigo** [comment]
@zofskeez I personally use MacOS and Brave is my main browser, and I wish this could be tracked down to specific combination, but the fact is that I've confirmed that this happens on both Windows or MacOS, and with Chrome, Brave, Firefox, Safari. Tested with other computers than my own as well.

**Comment by zofskeez** [comment]
@voiprodrigo are you able to test the configuration in the Auth0 tutorial to rule out anything with your specific configuration? Beyond that, a screen recording of the login attempt that shows both the main window (with dev tools opened on console tab) and the popup window may be helpful.

**Comment by voiprodrigo** [comment]
@zofskeez on it, will get back to you asap.

**Comment by voiprodrigo** [comment]
@zofskeez here's the recording, will get back to you with the Auth0 test results soon. Test done with Firefox.

https://user-images.githubusercontent.com/2421504/213835910-f1da8438-ea14-44bd-ab65-b9b7339d3f77.mp4

**Comment by voiprodrigo** [comment]
@zofskeez here's the recording, will get back to you with the Auth0 test results soon. Test done with Firefox. I already had a session open with the IdP, to avoid showing the IdP authentication screen. I also had to obfuscate a small section where the IdP URL is shown.


https://user-images.githubusercontent.com/2421504/213837538-8b4151a6-5553-44a4-a886-ecf6df8d36d6.mp4

**Comment by voiprodrigo** [comment]
@zofskeez I've tried the Auth0 test, and it worked. Restored basic OIDC configuration for my IdP, and I get the same problem again. So what could be happening between my browser and the IdP that makes Vault return that error?

**Comment by voiprodrigo** [comment]
Here's the browser initiated requests and responses, maybe it's useful.

**VAULT AUTH URL REQUEST**

```
POST https://vault-dev.xxx/v1/auth/oidc/oidc/auth_url HTTP/1.1
Host: vault-dev.xxx
Connection: keep-alive
Content-Length: 97
sec-ch-ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"
sec-ch-ua-platform: "macOS"
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
content-type: application/json; charset=UTF-8
Accept: */*
Origin: https://vault-dev.xxx
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://vault-dev.xxx/ui/vault/auth?with=oidc%2F
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8

{"role":null,"redirect_uri":"https://vault-dev.xxx/ui/vault/auth/oidc/oidc/callback"}
```

**VAULT AUTH URL RESPONSE**

```
HTTP/1.1 200 OK
Date: Sun, 22 Jan 2023 00:03:56 GMT
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Frame-Options: DENY
Cache-Control: no-store
Content-Type: application/json
Strict-Transport-Security: max-age=31536000; includeSubDomains
Content-Length: 567
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Security-Policy: default-src 'none'; font-src 'self'; script-src 'self'; connect-src 'self'; img-src data: 'self'; style-src 'unsafe-inline' 'self'; child-src 'self';
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive

{"request_id":"1668792a-475a-102d-97cf-7bdc52bfc5b1","lease_id":"","renewable":false,"lease_duration":0,"data":{"auth_url":"https://idp-provider/iam-services/0.1/oidc/authorize?client_id=vault-dev\u0026code_challenge=_pk9EPDdpnZ2PSF3dLeTkPvwv9B5NMEZ95ZG5B-X3d4\u0026code_challenge_method=S256\u0026nonce=n_8yizvUwY4IK2Fh5XgvV4\u0026redirect_uri=https%3A%2F%2Fvault-dev.xxx%2Fui%2Fvault%2Fauth%2Foidc%2Foidc%2Fcallback\u0026response_type=code\u0026scope=openid\u0026state=st_zDsc8lK1ErlPadXxle5G"},"wrap_info":null,"warnings":null,"auth":null}
```

**IDP-PROVIDER REQUEST**

```
GET https://idp-provider/iam-services/0.1/oidc/authorize?client_id=vault-dev&code_challenge=_pk9EPDdpnZ2PSF3dLeTkPvwv9B5NMEZ95ZG5B-X3d4&code_challenge_method=S256&nonce=n_8yizvUwY4IK2Fh5XgvV4&redirect_uri=https%3A%2F%2Fvault-dev.xxx%2Fui%2Fvault%2Fauth%2Foidc%2Foidc%2Fcallback&response_type=code&scope=openid&state=st_zDsc8lK1ErlPadXxle5G HTTP/1.1
Host: idp-provider
Connection: keep-alive
sec-ch-ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: https://vault-dev.xxx/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cookie: iam_service_csrf=mbjreNmSbG14SgeQvN9KcHvtQuond0Nu; iam_service_session=mxqjoy289nyzr5vezf6lhgnuwqsz55by
```

**IDP-PROVIDER RESPONSE**

```
HTTP/1.1 302 Found
Date: Sun, 22 Jan 2023 00:03:57 GMT
Server: Apache
Content-Type: text/html; charset=utf-8
Location: https://vault-dev.xxx/ui/vault/auth/oidc/oidc/callback?code=omTzNTX41sJXjbp77SB5xXtEy9ZGHw1V&state=st_zDsc8lK1ErlPadXxle5G
Content-Security-Policy: img-src 'self' data: api.yyy; default-src 'none'; script-src 'self' 'unsafe-eval'; style-src 'self' https://fonts.googleapis.com; connect-src 'self'; font-src 'self' https://fonts.gstatic.com; base-uri 'self'
X-Frame-Options: DENY
Content-Length: 0
Vary: Cookie
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin
Set-Cookie: iam_service_session=mxqjoy289nyzr5vezf6lhgnuwqsz55by; HttpOnly; Path=/; SameSite=Lax; Secure
X-XSS-Protection: 1; mode=block
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
```

**VAULT CALLBACK REQUEST**

```
GET https://vault-dev.xxx/ui/vault/auth/oidc/oidc/callback?code=omTzNTX41sJXjbp77SB5xXtEy9ZGHw1V&state=st_zDsc8lK1ErlPadXxle5G HTTP/1.1
Host: vault-dev.xxx
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
sec-ch-ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Referer: https://vault-dev.xxx/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
```

**VAULT CALLBACK RESPONSE**

```
HTTP/1.1 200 OK
Date: Sun, 22 Jan 2023 00:03:57 GMT
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Frame-Options: DENY
Accept-Ranges: bytes
Cache-Control: no-store
Content-Encoding: gzip
Content-Security-Policy: default-src 'none'; font-src 'self'; script-src 'self'; connect-src 'self'; img-src data: 'self'; style-src 'unsafe-inline' 'self'; child-src 'self';
Content-Type: text/html; charset=utf-8
Service-Worker-Allowed: /
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Transfer-Encoding: chunked

<GZIP'ED HTML CODE>
```

**Comment by voiprodrigo** [comment]
Vault OIDC config script:

```
vault write auth/oidc/config \
        oidc_discovery_url="https://iam.xxx/iam-services/0.1/oidc/" \
        oidc_client_id="$OIDC_CLIENT_ID" \
        oidc_client_secret="$OIDC_CLIENT_SECRET" \
        default_role="default_role"

vault write sys/auth/oidc/tune listing_visibility="unauth"

vault write auth/oidc/role/default_role \
      bound_audiences="$OIDC_CLIENT_ID" \
      allowed_redirect_uris="https://active.vault.service.cdc.consul-dev:8200/ui/vault/auth/oidc/oidc/callback" \
      allowed_redirect_uris="http://localhost:8250/oidc/callback" \
      allowed_redirect_uris="https://vault-dev.xxx/ui/vault/auth/oidc/oidc/callback" \
      user_claim="sub" \
      token_policies="default_role"
```

A note about the 3 callback URL's, the first first is for direct Vault access via a Consul DNS record for the active node, the second for the CLI, and the third for reverse-proxied access to Vault with a "public" FQDN (this an Apache servers with a ProxyPass to the Consul DNS record for the active node.
The HTTP requests in the previous reply where captured while accessing via the reverse proxied FQDN, "vault-dev.xxx". The Firefox screen recording was done accessing via the Consul address. The behaviour is exactly the same regardless of how it's accessed.

**Comment by voiprodrigo** [comment]
UPDATE: problem found (this was a tricky one). 

The IdP is sending this header: `Cross-Origin-Opener-Policy: same-origin`

I used an extension in Firefox to remove this header from the response, and the login happens OK.

So the problem happened all of a sudden, because the IdP code was modified to introduce this header.

**Comment by voiprodrigo** [comment]
Issue was unknowingly introduced after updating the web framework the IdP is based on, which started injecting it in the responses by default. Mitigated by selectively disabling the COOP header for the OAUTH related endpoints.

**Comment by zofskeez** [comment]
@voiprodrigo glad you were able to track it down! I will look into this further and see if at very least we can detect this situation and provide some messaging related to that header. Thanks for all the information.

**Comment by voiprodrigo** [comment]
@zofskeez of course, you're welcome. This all "unraveled" after you asked me to test Auth0 and then I started comparing headers :) 
That's a great idea, it could save a lot of pain in troubleshooting indeed, as this header becomes more mainstream. 
One thing I can add, is that after this I was wondering why GitLab instance was not suffering from the same problem, as it uses OIDC with the same IdP. And the reason is simple, the OIDC auth flow In GitLab only happens in the main window, there's no pop-up's involved. I don't know if that could be an option for Vault as well, thought I'd mention it. Cheers.

**Comment by ngotchac** [comment]
This issue is preventing authentication via Gitlab, as the COOP header was modified (on the public server) a week ago: https://gitlab.com/gitlab-org/gitlab/-/issues/425701

Is there another way Vault could do OIDC login, without opening a popup?

**Comment by dimm0** [comment]
I see the issue closed, but it's still not clear how to fix it... I see it being the problem in the latest vault release

**Comment by alkersan** [comment]
Same for me. Tried to setup OIDC access method with AWS Cognito user pool. The popup window shows up, redirects to the login portal, then redirects back to vault and ends up with `Cannot read properties of null (reading 'postMessage')`, without completing the auth flow.

https://github.com/hashicorp/vault/assets/527045/e37e97c6-2d49-4026-a073-022b685f931f

**Comment by alkersan** [comment]
I've just observed the same behavior with AWS Cognito. Tried to set it up as OIDC provider for vault - and login from web fails. Cognito hosted UI sets the same `Cross-Origin-Opener-Policy: same-origin` header, and vault popup window fails to post the state message back to origin.

**Comment by dimm0** [comment]
Any updates?

**Comment by Grey999** [comment]
Same problem since friday

**Comment by dimm0** [comment]
Latest release, still the same issue

**Comment by M0NsTeRRR** [comment]
Same issue with vault 1.18.3

**Comment by protsey** [comment]
This does not solve the main problem, but you can use a workaround for AWS Cognito:

1. Upgrade to Cognito Essentials Plan (for my use case it was free, but be careful)
2. Use the Managed login page and create a Custom domain for your User Pool
3. You can use proxy mechanisms to remove the Cross-Origin-Opener-Policy header from the Cognito response when the login page is running on a domain you control. In my case, it was convenient to use Cloudflare - response header modification rules.

Currently, this configuration works well, but not much time has passed. There may be some maintenance problem in the future.

**Comment by aphorise** [comment]
Repeating [comment from: 26596](https://github.com/hashicorp/vault/issues/26596#issuecomment-4010983198); this issue does not seem specific to Vault but rather to the OIDC IdP as well as client browsers.

Three (3) relevant areas to pursue include:

1. IdP / provider responses. Expect intermissions from upstream and do NOT assume IdP is always correct. In the context of Azure differences in response / behaviour could be observed where there were no other changes in Vault yet the same broken login started working again.

1. Multi-tenancy or multiple accounts on IdP.
   - Using Azure where there are two or more account types to select then a similar intermittency is encountered where sometimes it works and other times not.
   - Removing all accounts so that only 1 account is available and can be selected then fixes the issue entirely.
   - Adding another account for selection that's not relevant nor selected then recreates the issue

1. CORS: Chrome can be launched with: `--disable-features=CrossOriginOpenerPolicy` or otherwise a browser plugin is also a solution as last resort. Working back from a broken flow and immediately disabling CORS then results in everything working as expected.

**Comment by fsvm88** [comment]
Adding to the list of possible triggers in case you get the `, window.opener is null` part: I use Firefox with Containers and the sign-on is via Azure.

When the pop-up opens, Firefox can intercept the pop-up open action and open a *tab* for the sign-in pop-up, asking you whether you want to open the URL in X container or another one. Sign-on succeeds, but then Vault complains with `Error: Cannot read properties of null (reading 'postMessage'), window.opener is null`.

I guess the issue is that it's opening in a **tab** and not a separate **window**, so `window.opener` really is null.

Once I clicked `Always open site X in this container`, the pop-up opened properly as a separate window and the issue disappeared.
