### ISSUE TITLE
Migrating from HA to non-HA backend, 500 error

### ISSUE THREAD

**Issue by JeanMertz** [hashicorp/vault#1864]
We're migrating our backend from DynamoDB (HA) to S3 (non-HA).

I used a simple script like this to make this migration possible:

```ruby
#!/usr/bin/env ruby
require 'json'
require 's3'

file  = File.read('data/0001.json')
data  = JSON.parse(file)
items = data['Items']
  .reject { |i| i['Value']['NULL'] }
  .map { |i| [File.join(i['Path']['S'], i['Key']['S']), i['Value']['S']] }
  .to_h

s3 = S3::Service.new(access_key_id: ENV['AWS_ACCESS_KEY_ID'], secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'])

unless s3.buckets.find('vault-xxx')
  bucket = s3.buckets.build('vault-xxx')
  bucket.save(location: :eu)
end

items.each do |path, content|
  object = bucket.objects.build(path)
  object.content = content
  object.save
  nil
end
```

This was after we used [Dynamodump](https://github.com/bchew/dynamodump) to create a JSON dump of the data on DynamoDB.

In the end, all seemed okay, as we now have top level directories `core`, `logical`, and `sys`, with all the relevant directories and files (with content) below that.

However, when running a new Vault instance against this backend, it looks like it can't read the data as expected.

When doing `vault status`, the server responds with:

```
[ERR] core: failed to decode seal configuration error=invalid character 'e' looking for beginning of value
```

Given that I've read both here and on Google Groups that the format in which the data is stored is simple key/value, I'd think that moving the data over to S3 would be straight forward.

The only thing I can think of is that migrating from an HA backend, to a non-HA backend requires more work, because it doesn't have any locking mechanism or leader selection?

Is there anything I can do to solve this issue, or is this simply not possible with Vault?

I know most other issues get closed with "migration is not supported by us" or "ask Google Groups", but given the cryptic exception (and returned `500` HTTP status code), I think the devs would have the most knowledge about what could possibly be causing this problem.

**Comment by JeanMertz** [comment]
After some more digging in the code-base, I found that this is related to the `core/seal-config` file.

Looking at its content, it's base64 encoded: `eyJzZWNyZXRfc2hhcmVzIjo1LCJzZWNyZXRfdGhyZXNob2xkIjozfQ==`

Decoding it, reveals:

```
echo eyJzZWNyZXRfc2hhcmVzIjo1LCJzZWNyZXRfdGhyZXNob2xkIjozfQ== | base64 -D
{"secret_shares":5,"secret_threshold":3}
```

Given the `e` invalid character error, my initial guess would be that the DynamoDB backend stores all values base64 encoded, while the S3 backend stores them in plain text?

I'll play around with the migration script, and have it decode all the base64 encoded strings before saving to S3.

**Comment by JeanMertz** [comment]
storing the decoded `core/seal-config` on S3 makes the health check work again:

```
curl http://localhost:32776/v1/sys/health
{"initialized":true,"sealed":true,"standby":true,"server_time_utc":1473239664,"version":"Vault v0.6.1"}
```

There will probably be other files that need to be decoded, but at least I can take this one step at a time and see where the rabbit hole ends.

**Comment by JeanMertz** [comment]
Next issue seems to be unsealing the Vault.

When using the exact same credentials that work on our current Vault cluster (just tested them again), I can't seem to unseal the new Vault instance that talks to our new S3 backend.

debug logs show:

```
==> Vault server started! Log data will stream in below:

2016/09/07 09:31:35.479684 [DBG] core: cannot unseal, not enough keys keys=1 threshold=3
2016/09/07 09:31:37.972813 [DBG] core: cannot unseal, not enough keys keys=2 threshold=3
2016/09/07 09:31:41.330066 [DBG] core: cannot unseal, not enough keys keys=1 threshold=3
```

I enter three different keys, and after the third key, it circles back to being sealed and requiring the first of three keys.

**Comment by ekristen** [comment]
@JeanMertz from my experience that when it looks like that its because you are missing some critical information from the physical store so it can't do the unseal because it doesn't have the information it needs. I found this to be the case when I was doing tests on backing up and restoring the physical storage.

Side question: Personally just curious, what's the motivation to move away from HA backend vault?

**Comment by JeanMertz** [comment]
@ekristen thanks for the feedback.

Regarding the missing data. I went back to our DynamoDB store and counted the rows, which is `364` (this is our development vault instance). The S3 storage contains `325` items, but if I count the `NULL` values on the DynamoDB dump (which are basically directories, so they don't count), I get `364 - 39 = 325`, which matches exactly with what is on S3.

So I don't believe I am missing any data, the only thing that could be different is that the S3 storage stores data differently (like the `core/seal-config` file I mentioned before, which is Base64 encoded on DynamoDB, but isn't on S3). So perhaps some other files need to be decoded as well, but I haven't found any others.

Regarding moving away from HA. That's a long story, but the gist of it is that:

We are currently hosting Vault in our Kubernetes cluster, which is problematic, because pods are short-lived (especially with frequent cluster node upgrades), and having the vaults seal during an upgrade procedure means our application goes offline.

At first, we where running Consul on Kubernetes as well, but that just caused more headaches, and since we instituted a new rule to move all persistent data off of the cluster, we switched to the next best hosted HA backend solution, which is DynamoDB. Only _after_ we migrated, we noticed the small caveat: DynamoDB turned out to be only so-so HA, as deleting the Vault master pod frequently meant the lock was "corrupt", and we had to manually intervene, resulting in application-wide downtime again.

Since Vault hasn't ever crashed on us yet, we thus came to the conclusion that we would have _less_ downtime using a non-HA backend like S3, with Vault running on a CoreOS machine somewhere off-cluster in a single container, than running in HA mode.

Now, if only we can get that migration problem solved 😉

**Comment by ekristen** [comment]
I would suggest that you create a new vault against s3 and add a few of your policies, mounts and then see what the difference is between the two.

**Comment by JeanMertz** [comment]
@ekristen great minds think alike. That was precisely what solved this problem for me.

It turns out, _all_ files are stored in binary-form on  S3, _except_ for the `core/seal-config` file.

Tweaking the above script to base64 decode _all_ data stored in DynamoDB solved the unseal problem.

**Comment by ekristen** [comment]
Awesome glad that worked. FWIW if you want to get back into the HA setup, I definitely recommend consul for it.

**Comment by vishalnayak** [comment]
Marking this as closed based on all the conversation. Reopen if needed.
