### ISSUE TITLE
Logical.ReadRawWithDataWithContext cancels response body

### ISSUE THREAD

**Issue by terinjokes** [hashicorp/vault#18658]
**Describe the bug**

To fetch the public certificates of certificate authorities from the PKI plugin, I was using the Client's `RawRequestWithContext` function, which has since been deprecated. I've migrated to the Logical client's `ReadRawWithDataWithContext` function, but found it to be inconsistently failing.

To support client HTTP timeouts, both implementations call `context.WithTimeout`. However, `RawRequestWithContext` never called the cancel function.

https://github.com/hashicorp/vault/blob/c782b6678c35587849471a77fd2ad3e8b7f30870/api/client.go#L1268-L1277

The replacement `ReadRawWithDataWithContext` does call cancel, which occasionally starts causing failures reading the response body.

https://github.com/hashicorp/vault/blob/c782b6678c35587849471a77fd2ad3e8b7f30870/api/logical.go#L101-L106

(Note that this code block eventually calls the above deprecated function via `readRawWithDataWithContext`)

**To Reproduce**
Since the failure seems to depend on the precise scheduling of the Go runtime, and behavior of select cases, I've been unable to develop an example that consistently fails. However, as an partial example:

```go

func GetCertifcateForAuthority(ctx context.Context, client *vault.Client, caName string) ([]byte, error) {
	pemPath := path.Join(caName, "ca", "pem")
	resp, err := client.Logical().ReadRawWithDataWithContext(ctx, pemPath, nil)
	if err != nil {
		return nil, fmt.Errorf("fetching certificate from Vault returned error: %w", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusNoContent:
		// Vault returns 204 when CA exists, but key material hasn't been submitted or generated
		return []byte{}, nil
	case http.StatusOK:
		p, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, fmt.Errorf("reading body from Vault: %w", err)
		}

		block, _ := pem.Decode(p)
		if block == nil {
			return nil, errors.New("no PEM block returned by Vault")
		} else if block.Type != "CERTIFICATE" {
			return nil, fmt.Errorf("unknown PEM %q block returned by Vault", block.Type)
		}

		return pem.EncodeToMemory(block), nil
	default:
		return nil, fmt.Errorf("unexpected status code returned by Vault: %d", resp.StatusCode)
	}
}
```

With using a Vault client generated with `vault.DefaultConfig()`, this function will eventually unexpectedly fail with the following error: `reading body from Vault: context canceled`. After disabling the HTTP timeout in the Vault client (eg, `config.Timeout = 0`) I've been unable to reproduce this error.

**Expected behavior**
I can't see the use case for closing the body of a `ReadRaw*` request before the caller has a chance to inspect is the intended result of these APIs.

Should I open a PR to duplicate the note and behavior from Client? Or was this timeout behavior only intended on the non-raw paths?

**Comment by averche** [comment]
Actually, it appears that @cipherboy has already addressed this issue in #17750 PR from November

**Comment by terinjokes** [comment]
It looks like that PR takes the former approach of duplicating the behavior from client, which seems to be the reason it was deprecated in the first place?

**Comment by averche** [comment]
Hi @terinjokes, I've merged the PR to fix this issue (removing timeout logic altogether from `ReadRaw*` requests) and tagged it as [api/v1.8.3](https://github.com/hashicorp/vault/releases/tag/api%2Fv1.8.3). Please update to this version to pick up the latest changes.

Since `ReadRaw*` methods no longer handle timeouts, you will probably want to do it manually. In your example above, it would be something like:

```go
func GetCertifcateForAuthority(ctx context.Context, client *vault.Client, caName string) ([]byte, error) {
	ctx, cancel := context.WithTimeout(context.Background(), client.ClientTimeout())
	defer cancel()
	
	// the rest of the code is unchanged
}
```

**Comment by terinjokes** [comment]
Yes, I also did that with the workaround of disabling the ClientTimeouts. I'll upgrade and test the new release over the next few days.

**Comment by terinjokes** [comment]
@averche Do you have an estimate of when the `github.com/hashicorp/vault` module will be updated to use SDK v0.7.0? Updating api to 1.8.3 also upgrades the SDK, which causes my project to fail building:

```
/home/terin/go/pkg/mod/github.com/hashicorp/vault@v1.12.2/vault/logical_system.go:4284:9: not enough arguments in call to framework.NewOASDocument
	have ()
	want (string)
```

**Comment by averche** [comment]
@terinjokes It appears that you are importing `vault/go.mod` directly. It is not meant to be imported as a dependency in your project. Please refer to [this section](https://github.com/hashicorp/vault/blob/main/README.md#importing-vault) for more details.

I've updated vault's go.mod to SDK v0.7.0 and API v1.8.3 ([#18765](https://github.com/hashicorp/vault/pull/18765), [#18773](https://github.com/hashicorp/vault/pull/18773)) but if you are building against `vault@v1.12.2`, it will likely not be backwards compatible.

**Comment by terinjokes** [comment]
Yes, it looks like I started using the testrig in my E2E tests before some of those warnings went in?

**Comment by terinjokes** [comment]
I plan on just pulling on the binary and wiring it up to the test runner. Fortunately, I've already isolated the E2Es from the rest of the project.

Thanks, we can probably call it done here.

**Comment by heliomartins** [comment]
Hello @averche ,
Quick question, do you reckon this problem here could be related to the one I reported yesterday? https://github.com/hashicorp/vault/issues/19192

It looks to me that the symptoms might be the same. 😕
