### ISSUE TITLE
Importing a Root CA Bundle doesn't map the issuer(s) to the imported key

### ISSUE THREAD

**Issue by julienperignon** [hashicorp/vault#18660]
**Describe the bug**
Importing a Root CA Bundle doesn't map the issuer(s) to the imported key. which prevents me from configuring an intermediate CA and issuing certificates. 

I also tried using the UI and the behavior is the same (cant see the cert in the UI) but the the issuers and keys are there in vault when I pull the data from the CLI 

**To Reproduce**
1. `vault secrets enable pki`
2. `vault write pki/config/ca pem_bundle=@bundle.pem` (Notice how mappings have empty string values ) 
```
{
  "request_id": "6174fb09-fd8a-8a34-dd34-d909bf79ba50",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": {
    "imported_issuers": [
      "2d267a87-9cfa-1b41-d244-13cdc291ffb5",
      "4dee10bc-f2b8-3a11-2c66-1fc69d429dc3"
    ],
    "imported_keys": [
      "8c848553-15de-b542-e99d-3af191553c90"
    ],
    "mapping": {
      "2d267a87-9cfa-1b41-d244-13cdc291ffb5": "",
      "4dee10bc-f2b8-3a11-2c66-1fc69d429dc3": ""
    }
  },
  "wrap_info": null,
  "warnings": [
    "This mount hasn't configured any authority information access (AIA) fields; this may make it harder for systems to find missing certificates in the chain or to validate revocation status of certificates. Consider updating /config/urls or the newly generated issuer with this information."
  ],
  "auth": null
}
```

**Expected behavior**
The mapping values to have the imported key value

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.12.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.12.2 (415e1fe3118eebd5df6cb60d13defdc01aa17b03), built 2022-11-23T12:53:46Z
* Server Operating System/Architecture: docker container

**Additional context**
What I'm trying here is to set up a root CA  from a wildcard cert ( in a pfx that I then convert to PEM ) and import it as a bundle into Vault.

**Comment by cipherboy** [comment]
@julienperignon Just to state the obvious, but if the key doesn't match the given certificate, it will not be associated. Have you verified with e.g., OpenSSL that the key does indeed match the certificate?

Something like:

```
$ openssl x509 -in root.pem -text
$ openssl rsa -in server.key -text
```

**Comment by julienperignon** [comment]
@cipherboy it's a wildcard certificate generated by letsencrypt. I got the fullchain.pem and private key. I assume they match :)

**Comment by cipherboy** [comment]
@julienperignon The Vault PKI secrets engine allows operating your own X.509 CA. This requires provisioning a certificate with IsCA=True asserted in the basic constraint extension (a "CA" certificate). This allows you to issue new certificates under the CA in question.

The chain you're attempting to submit is likely:

```
ISRG Root X1 -> Let’s Encrypt R3
[Unrelated Private Key]
```

The fullchain file from Let's Encrypt likely has something like:

```
ISRG Root X1 -> Let’s Encrypt R3 -> Server Cert
[Private Key matching Server Cert]
```

Let's Encrypt, to my knowledge, _does not_ issue subordinate CAs, so while the server cert you have does match the private key, it _does not_ match one of Let's Encrypt CAs and thus will not line up with anything you imported. The Server Cert from LE is not a CA and thus would be rejected by Vault.

You'd need to create your own X509 CA externally to use this API, or use the APIs to create your own internal X509 CA. Likely it will not chain through Let's Encrypt, as I'm not aware of them extending their chain of trust in this manner.

(Unless of course, you happen to work at ISRG on LE, but I'm guessing that's not the case :-)

**Comment by julienperignon** [comment]
@cipherboy I semi-expected this could have been an issue .. thank you for confirming! 

What I ultimately want to do is to be able to issue valid certs from vault that are trusted by clients ( users browsing on our sites) without having to install any CA chain. 

Could you please tell me if this would be a valid scenario : 
1. Find a trusted vendor that is able to issue a subordinate CA cert and priv key ( with isCA=true )
2. Import the bundle onto an intermediate CA in Vault ( likely something like : `Root Vendor->Intermediate Vendor->wildcard cert (with isCA=true) ` 
3. Create a role on the intermediate CA created above
4. Issue certificates that can be trusted by clients ( because the root CA is trusted ) 

Thanks for your help

**Comment by cipherboy** [comment]
@julienperignon This will not work for two reasons:

1. Political. Trusted CAs are largely those managed by the [CA/Browser Forum](https://cabforum.org/) relationship and its [baseline requirements](https://cabforum.org/baseline-requirements-documents/). Largely all of the browsers align here, and creating subordinate CAs are highly regulated. Even getting a constrained sub-CA for a specific domain is unlikely. To comply, this subCA would end up in the public, searchable [certificate transparency logs](https://crt.sh/?q=github.com) and any leaf certs it/you issues, by virtue of chaining to a public CA, would also have to end up there. Issuing a SubCA would largely be a violation of most public CA's operating procedures and thus wouldn't be done and if done, could result in the CA getting kicked out of most browsers' trust stores.
2. Technical. Even if you got such a CA.... You're going to need a chain anyways. While the public root is trusted and widely distributed, nobody knows about your intermediate subCA. If nothing advertises a full chain (public root->your intermediate->server leaf), browsers cannot build a valid chain from just (trust store including public root + server leaf) -- most software can't infer missing intermediates (those that use AIA -- authority information access fields on the certificate -- but I'm only aware of C# and NSS with certain options). Plus, Vault doesn't support CT, so you really can't run a public CA with Vault's PKI engine. (There's also a side digression that some browsers cache trusted intermediates, so if there _was_ a number of widely-used sites which were properly configured a minority of incorrectly configured services, 

In short, I'd just create your own root, distribute that internally (so others on the internet don't have to trust it ;-) and then issue an intermediate under it and issue leaves from that intermediate.

I'm curious about your use case though, you write:

> What I ultimately want to do is to be able to issue valid certs from vault that are trusted by clients ( users browsing on our sites) without having to install any CA chain.

So end-users are browsing to your site and getting certificates. Are these client authentication certs, or server certs? If the former, nobody but your site needs to really trust these client auth certs -- so you could easily sign them from an internal root or intermediate. If they need to be trusted by other users, you could offer the root's certificate for download. 

If they're public server resources needing to be trusted by other users, I'd just direct your users to use ACME directly via LE.

**Comment by julienperignon** [comment]
@cipherboy I greatly appreciate the very detailed answer you provided. It all makes more sense to me now in this very complex world !
I think I'm gonna ditch vault for this specific use case and just use let's encrypt ! 
Thank you so much for your help on this one and for providing a such detailed explanation.
