### ISSUE TITLE
Azure Recover Services Vaults feature request

### ISSUE THREAD

**Issue by Mofato** [hashicorp/vault#18665]
**Is your feature request related to a problem? Please describe.**
No, more like a feature request.

**Describe the solution you'd like**
Currently we are deploying Recovery Services Vault with terraform on Microsoft Azure. But we cannot set the Monitoring Settings with terraform provider azurerm. The monitor settings can be set with api version 22-10-01. See the json code below.
        "monitoringSettings": {
            "azureMonitorAlertSettings": {
                "alertsForAllJobFailures": "Enabled"
            },
            "classicAlertSettings": {
                "alertsForCriticalOperations": "Disabled"
            }
        },
Second we also want to set the Public Network Access which also is available in api version 22-10-01. See the json code below. 
"publicNetworkAccess": "Disabled"

**Additional context**
![image](https://user-images.githubusercontent.com/122437855/211798928-0d534f35-3a09-4eac-aceb-af8b8c337d2b.png)
![image](https://user-images.githubusercontent.com/122437855/211799016-1017fcf3-7e3a-4c74-8f45-8736bb438de8.png)

**Comment by Mofato** [comment]
Hi Simon,

This is for Terraform Provider for AzureRM. This a feature request for the  Recovery Services Vault.
Hope this answer your question.

**Comment by Mofato** [comment]
Hi Simon, 

My fault, i created the issue for the wrong resource. It's for https://github.com/hashicorp/terraform-provider-azurerm/issues

**Comment by hsimon-hashicorp** [comment]
Unfortunately I am unable to transfer this issue to that repository. Please open a new issue there. Thanks!

**Comment by Mofato** [comment]
Hello Simon,

Thanks for your respons.

I opened a new case Azure Recover Services Vaults feature request · Issue #20080 · hashicorp/terraform-provider-azurerm (github.com)<https://github.com/hashicorp/terraform-provider-azurerm/issues/20080>.

Regards,
Mohamed

Van: Heather Simon ***@***.***>
Verzonden: Friday, 20 January 2023 22:28
Aan: hashicorp/vault ***@***.***>
CC: Fatouh, Mohamed ***@***.***>; Author ***@***.***>
Onderwerp: Re: [hashicorp/vault] Azure Recover Services Vaults feature request (Issue #18665)


Unfortunately I am unable to transfer this issue to that repository. Please open a new issue there. Thanks!
