### ISSUE TITLE
Vault Token HTTP APIs should not allow 'token' to be passed in request URL

### ISSUE THREAD

**Issue by VinayMadyalkar** [hashicorp/vault#1869]
Currently Vault Token HTTP APIs allow 'token' parameter to be part of request URL or body. 
The following are the APIs:
```
/auth/token/lookup[/token]
/auth/token/renew[/token]
/auth/token/revoke[/token]
/auth/token/revoke-orphan[/token]
```
As a best practice sensitive information like 'token' should NOT be passed in the URL. 
This is especially true if SSL is not configured(SSL tends to encrypt URL, HEADER and BODY, hence this will not be an issue if SSL is configured).
URLs are also saved in browser history which again may lead to compromise of 'token'. 
The ideal approach would be to restrict passing the 'token' in header or request body only(Currently being followed in Consul)

**Comment by jefferai** [comment]
We can't remove this capability for backwards compatibility reasons, but in 0.6.2 we return a warning if this method has been used rather than the POST/PUT request body.

It is also easy to disallow this via ACL policy.

**Comment by VinayMadyalkar** [comment]
Sounds Good. Thanks
