### ISSUE TITLE
show CNAMES when listing certs

### ISSUE THREAD

**Issue by ripienaar** [hashicorp/vault#1871]
listing certs in the pki backend gives:

```
# vault list acme_ops/certs/
Keys
01:1f:5d:55:60:c6:66:e4:71:b1:64:de:0c:1e:38:43:b2:66:f9:22
0d:b6:78:2b:d0:c9:d4:0c:a7:7d:12:1f:dd:f7:8b:a4:0e:b6:65:8e
15:32:0f:f6:7a:2d:f1:f9:82:3e:71:d1:40:82:ed:40:ed:e8:7a:22
35:a0:90:53:05:32:d8:5a:83:7d:49:7e:15:0e:7f:d7:d4:13:9f:1d
3a:12:fd:52:23:60:6c:d8:3e:eb:67:44:8b:4b:ef:b8:e5:b9:d0:3a
47:01:2e:5d:f2:f6:27:8f:10:cd:42:f8:33:18:f0:8f:e0:ce:e3:58
4f:00:ac:98:b2:4b:6c:a8:75:e4:e2:ac:07:99:cf:91:12:9b:35:6e
76:28:d7:7c:6c:2f:76:29:f5:fb:35:f6:b1:42:7a:7e:86:fb:7d:b3
```

As a way of obtaining info about signed certs to assist with revokes and such this is not particularly friendly, an additional field showing cnames would go a long way

**Comment by jefferai** [comment]
Sorry, but this is a wontfix. The main but not only reason is that the certs are stored by serial number in the database as it's the only guaranteed unique key. Listing is a single operation on the storage backend, but showing the CN for N entries would require an additional N storage operations, which could be extremely expensive (think S3). We want to have those N operations happen because an operator explicitly performs it rather than automatically.

**Comment by ripienaar** [comment]
In that case could there be a flag to explicitly enable that behaviour? As it is there appears no single way to extract a list of CNAMES in the vault

Additionally there appears (though this is no doubt user error) no way to limit CNAMES to not be dupe and none of the other existing API endpoints seem to allow you to extract the CNAME of a certificate even if you knew the key id in question.

So with this limitation it seems impossible to build a friendly UI that does not involve downloading each certificate, parsing it etc and extracting its CNAMEs which is costly all round not just to vault.

**Comment by jefferai** [comment]
> In that case could there be a flag to explicitly enable that behaviour? As it is there appears no single way to extract a list of CNAMES in the vault

It's possible we could expose it through a separate endpoint but not via a list operation.

> Additionally there appears (though this is no doubt user error) no way to limit CNAMES to not be dupe

This is on purpose! There are many, many enterprise use cases around having unique certs that can all satisfy a given set of CN/SANs.

> and none of the other existing API endpoints seem to allow you to extract the CNAME of a certificate even if you knew the key id in question.

You can fetch a certificate given its serial number, so you can parse the CN from there. Keys output from listing are always sorted, so in your use-case (building a UI) you could pretty easily compare lists of certs from Vault with a list from your DB and fetch details for anything different.

**Comment by ripienaar** [comment]
> It's possible we could expose it through a separate endpoint but not via a list operation.

Yeah the implementation choice isn't that important, it's more about the goal so however works within the larger design

> This is on purpose! There are many, many enterprise use cases around having unique certs that can all satisfy a given set of CN/SANs.

Likewise there are reasons not to. It would be handy if there could be a uniqueness constraint within a certain profile or perhaps a intermediate CA can have such a CA wide policy or something.

A sample use case is be around VPN certs for example.  It's quite common to have allow/deny lists around CNs and dupes there can really spoil your day.  Likewise in CM systems and so forth where certs are used for node identification

**Comment by jefferai** [comment]
> Likewise there are reasons not to. It would be handy if there could be a uniqueness constraint within a certain profile or perhaps a intermediate CA can have such a CA wide policy or something.

This can already be done via Vault policy combined with roles in the backend. More management but easy to automate, and I'd rather support both possibilities.
