### ISSUE TITLE
The K/V v2 API docs are ambiguous about the `cas` (check-and-set) field

### ISSUE THREAD

**Issue by busser** [hashicorp/vault#18724]
**Describe the bug**

The K/V v2 API docs for [Create/Update Secret](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#create-update-secret) and [Patch Secret](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#patch-secret) are ambiguous about the position of the `cas` field.

The [Parameters](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#parameters-2) section implies that the `options`, `cas`, and `data` fields are at the same level, with a payload that looks like this:

```json
{
  "options": {},
  "cas": 0,
  "data": {
    "foo": "bar",
    "zip": "zap"
  }
}
```

However the [Sample payload](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#sample-payload-1) section shows a payload with the `cas` field inside the `options` map:

```json
{
  "options": {
    "cas": 0
  },
  "data": {
    "foo": "bar",
    "zip": "zap"
  }
}
```

In practice, only the second payload works. The first payload gets an error response saying the check-and-set parameter is not set.

This ambiguity has lead to at least one erroneous implementation: the Terraform Vault provider, which [sends a payload with `options` and `cas` next to each other](https://github.com/hashicorp/terraform-provider-vault/issues/1727), leading to an error.

**To Reproduce**

Steps to determine which payload works:

1. Deploy a fresh Vault instance:

   ```bash
   docker run \
       --cap-add=IPC_LOCK \
       --detach \
       --publish=8200:8200 \
       --name=vault \
       hashicorp/vault:1.12.2
   ```

2. Get the root auth token from startup logs for future use:

   ```bash
   # At startup, Vault logs the following line:
   # Root Token: hvs.0123456789abcdefghijklmno
   vault_token="$(docker logs vault 2>/dev/null | awk '/Root Token:/ { print $3 }')"
   ```

3. Configure engine to require check-and-set:

   ```bash
   curl \
       --header "X-Vault-Token: $vault_token" \
       --request POST \
       --data '{ "cas_required": true }' \
       localhost:8200/v1/secret/config
   ```

4. Try to create a secret without check-and-set field:

   ```bash
   curl \
       --header "X-Vault-Token: $vault_token" \
       --request POST \
       --data '{ "data": { "my_key": "my_value" } }' \
       localhost:8200/v1/secret/data/my-secret
   ```

   **This fails as expected** with the following response body:

   ```json
   {
     "errors": ["check-and-set parameter required for this call"]
   }
   ```

5. Try to create a secret with the check-and-set field positioned according to the [Parameters](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#parameters-2) section of the docs:

   ```bash
   curl \
       --header "X-Vault-Token: $vault_token" \
       --request POST \
       --data '{ "data": { "my_key": "my_value" }, "cas": 0 }' \
       localhost:8200/v1/secret/data/my-secret
   ```

   **This fails unexpectedly**, with the following response body:

   ```json
   {
     "errors": ["check-and-set parameter required for this call"]
   }
   ```

6. Try to create a secret with the check-and-set field positioned according to the [Sample payload](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#sample-payload-1) section of the docs:

   ```bash
   curl \
       --header "X-Vault-Token: $vault_token" \
       --request POST \
       --data '{ "data": { "my_key": "my_value" }, "options": { "cas": 0 } }' \
       localhost:8200/v1/secret/data/my-secret
   ```

   **This works as expected**, with the following response body:

   ```json
   {
     "request_id": "ef28e8f6-4ebd-99f1-b9ce-acea21d812f1",
     "lease_id": "",
     "renewable": false,
     "lease_duration": 0,
     "data": {
       "created_time": "2023-01-16T13:08:53.170450886Z",
       "custom_metadata": null,
       "deletion_time": "",
       "destroyed": false,
       "version": 1
     },
     "wrap_info": null,
     "warnings": null,
     "auth": null
   }
   ```

7. Cleanup:

   ```bash
   docker rm --force vault
   ```

_**Note:** sending a PATCH request to patch a secret has the same behaviour with regards to the check-and-set parameter: the `cas` field must be in the `options` map._

**Expected behavior**

Vault behaves as expected, but the documentation can lead to erroneous implementations and lost engineering time.

**Environment:**

* Vault Server Version: 1.12.2 (also reproduced with 1.11.3)
* Vault CLI Version: irrelevent
* Server Operating System/Architecture: Linux arm64v8 (also reproduced on Linux amd64)

Vault server configuration file(s):

None.

**Additional context**

None.

**Comment by ccapurso** [comment]
Hi, @busser. Thanks for the feedback! We have fixed the documentation to ensure that `cas` is listed underneath `options` to align with the examples. You can find the changes by following the links provided in your initial description.
