### ISSUE TITLE
CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [hashicorp/vault#18759]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are [interested](https://discord.com/channels/872925471417962546/974029056070795284/1062778093875499058) in a  Hashicorp Vault Source plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it.

This will give your users the ability to sync Vault APIs/Config to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by hsimon-hashicorp** [comment]
Hi there! Our partner manager, @acahn, will be in touch with regards to this. I'm going to go ahead and close this issue, because this may not be the best venue or even the best way to integrate with Vault, and Alex can talk to you more about it. Thanks! :)

**Comment by yevgenypats** [comment]
Thank you 🙏  Looking forward to chatting!
