### ISSUE TITLE
Remove HTTP Status Codes 403 from documentation 

### ISSUE THREAD

**Issue by enudler** [hashicorp/vault#1878]
Vault is no longer returns status 403 when authentication fails, it returns 400 with "permission denied"
Can you please  update the documentation

**Comment by jefferai** [comment]
Which page/snippet/example/etc is this?

**Comment by enudler** [comment]
https://www.vaultproject.io/docs/http/index.html

**Comment by jefferai** [comment]
What call are you making? It's still showing `403` for me:
```
$ VAULT_TOKEN=foo vault read secret/foo
Error reading secret/foo: Error making API request.

URL: GET http://127.0.0.1:8200/v1/secret/foo
Code: 403. Errors:

* permission denied
```

**Comment by enudler** [comment]
Hi

Using vault 0.6
/v1/secret/foo

Status: 400 Bad Request
{
  "errors": [
    "permission denied"
  ]
}

**Comment by jefferai** [comment]
I can't replicate this on 0.6.1 or master, so it appears to be a bug that has been fixed.
