### ISSUE TITLE
Can't make vault 0.6.1 work on either Linux or Windows

### ISSUE THREAD

**Issue by andreivasiletruta** [hashicorp/vault#1880]
I downloaded latest vault version for both Linux and Windows x64

1. On Linux it always gives 503 (init and status too)
2. On Windows it gives connection error even if VAULT_ADDR has been specified properly according to documentation

PS: Seems like user miss-understanding case; still I have no solution for it :)

**Comment by jefferai** [comment]
Hi @andreivasiletruta ,

Can you provide more information? How are you starting Vault, how are you running it, what commands are you running, what are your actual vault env vars?

For question 2, does using `-address=<address>` work?

**Comment by andreivasiletruta** [comment]
I will try to focus my answer only for linux because eventually that is where I wanted to make it work.

I unzipped the .zip from the website
I am triggering `./vault init` as an example
I set the VAULT_ADDR to match htpp://myhost:8200
Once I did that I started to receive:
`root@myhost:/vault# ./vault unseal
Error checking seal status: Error making API request.

URL: GET http://myhost/v1/sys/seal-status
Code: 503. Raw Message:

<HTML><HEAD>
<TITLE>Network Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Network Error (tcp_error)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
A communication error occurred: "Connection refused"
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>`

For 2 - I will try to see.

Thank you.

**Comment by andreivasiletruta** [comment]
I read 503 might be the case of a sealed vault but it does not seem in my case because I can't init it either nor unseal it.

**Comment by jefferai** [comment]
A few things:

* I'm guessing this is just a typo in your paste above but ` htpp://myhost:8200` -- `htpp` should be `http`
* You can't unseal Vault if it's not inited, so it makes sense you would get an error
* That error message is not coming from Vault -- I have no idea what is causing it but a quick Google suggests that it's something Microsoft-specific, while you said that you were running on Linux.

**Comment by andreivasiletruta** [comment]
Thank you; I will continue to investigate. I am for sure on linux
`3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

htpp is just a typo while I tried not to expose internal stuff :)

**Comment by andreivasiletruta** [comment]
I managed to make it work in non-dev move thus using a proper config file with a proper backend and learned few things along the way about vault.

thank you again.

**Comment by jefferai** [comment]
Sure! Closing for now then.
