### ISSUE TITLE
`sys/internal/counters/activity`: Inconsistent use of returned fields

### ISSUE THREAD

**Issue by maxb** [hashicorp/vault#18810]
The activity log APIs return data to users in various contexts using this Go struct:

https://github.com/hashicorp/vault/blob/3ded1388cbd838b5a1253af40808c823d6d4336d/vault/activity_log.go#L1455-L1461

According to the docs, two of the fields are deprecated versions of two others:

https://github.com/hashicorp/vault/blob/72e36c879dc5e3257d981dcde6953567411c3d57/website/content/api-docs/system/internal-counters.mdx?plain=1#L244-L250

However, when actually using the API, they are not always set to the same values.

In some cases, only some of the fields are filled in:

https://github.com/hashicorp/vault/blob/3ded1388cbd838b5a1253af40808c823d6d4336d/vault/activity_log.go#L2466-L2470
https://github.com/hashicorp/vault/blob/3ded1388cbd838b5a1253af40808c823d6d4336d/vault/activity_log.go#L2482-L2486
https://github.com/hashicorp/vault/blob/3ded1388cbd838b5a1253af40808c823d6d4336d/vault/activity_log.go#L2521-L2525
https://github.com/hashicorp/vault/blob/3ded1388cbd838b5a1253af40808c823d6d4336d/vault/activity_log.go#L2538-L2542

Either both versions of the field should be filled in, or a different Go struct should be used so that the older fields are not included, with zero values, in the serialised JSON in these cases.

In another particularly confusing case, entirely different code is used to calculate the old and new names of the same field:

https://github.com/hashicorp/vault/blob/3ded1388cbd838b5a1253af40808c823d6d4336d/vault/activity_log.go#L1690-L1691

Either they should be made the same, or the reason for the difference should be documented.

**Comment by hsimon-hashicorp** [comment]
Hey @maxb! Thanks for this issue report. Those fields are indeed deprecated, and documented as such. While we do have plans to remove these fields and make the user experience more consistent, that work has not yet been scheduled. I'll tag @finnstech here as our Product Manager to keep it on their radar, but I'll close this issue for now. Please keep an eye out for this to be resolved. Thanks!

**Comment by finnstech** [comment]
Thanks for the tag, @hsimon-hashicorp. I've added this feedback to our observability and monitoring initiative.
