### ISSUE TITLE
vault RHEL RPM repositories broken

### ISSUE THREAD

**Issue by eliottcassidy2000** [hashicorp/vault#18820]
* Vault Version: 1.12.1 and  1.12.2, tho assume others are affected
* Operating System/Architecture: N/A

**Expected Behavior:**
should be able to install vault from https://rpm.releases.hashicorp.com/RHEL/9/x86_64/stable, or https://rpm.releases.hashicorp.com/RHEL/8/x86_64/stable, or https://rpm.releases.hashicorp.com/RHEL/7/x86_64/stable

**Actual Behavior:**
vault-1.12.2-1.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 84944852 but expected size is: 84944924

**Steps to Reproduce:**
yum install -y vault

**Important Factoids:**
The three rpm repositories listed seem to be borked. Just trying to give y'all a heads up. I've always used them to install vault. Haven't changed my dnf config at all, but within the last week these repos decided to stop being able to install the vault package. I imagine something must have changed within the repos. If you're able to find a way to install vault from these repos, lmk, thank you!!

**Comment by marianoasselborn** [comment]
Hi @eliottcassidy2000 , we recently resigned our packages with a new key, which has changed the repo metadata, and could be causing an issue if this metadata is cached locally (more details in https://status.hashicorp.com/incidents/5zxyf7fyzq91). 

Would you mind running ``yum --enablerepo=hashicorp clean metadata``  and retrying the install?

**Comment by eliottcassidy2000** [comment]
Hey @marianoasselborn tried that, and the metadata was cleaned correctly, but still got the same results  when trying to install vault :(

**Comment by eliottcassidy2000** [comment]
Actually, @marianoasselborn nevermind, got it working. We use nexus to proxy your repos. I had gone through last night and deleted/recreated our 3 nexus proxy repos in hopes that it would fix something. I guess the error hadn't been fixed yet on your end at that point tho, since I just deleted and recreated them now, and that fixed it! Thank you so much for all your help!
