### ISSUE TITLE
vault token store high memory usage causing OOM

### ISSUE THREAD

**Issue by shaj13** [hashicorp/vault#18838]
**Describe the bug**
Running a single pod vault 1.12.2 on the k8s cluster, after a day k8s restarted the pod due to OOM. 
3 pprof has been snapshotted every 7+ min,  The pprof point to the token store and expiration manager. 

For now, I don't have the correct information about how many clients trying to log in or access the vault simultaneously. 
In addition, Some of the vault clients' token life span is 5m. 

**To Reproduce**
n/a 

**Expected behavior**
Token store and expiration manager low mem usage. 

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/65346528/214583727-c217f0e6-3995-4c78-8b66-3662990ecd1e.png">

**pprof files**
[pprof.tar.gz](https://github.com/hashicorp/vault/files/10500036/pprof.tar.gz)

**Comment by ccapurso** [comment]
Hi, @shaj13. Additional information is required in order to attempt to root cause the OOM issue. It could be possible that your node does not have access to enough memory to handle the token expiration volume that you are experiencing. It would be useful to know the request and limit for your vault pod as well how many clients are trying to login and what the distribution of token TTL is.

**Comment by shaj13** [comment]
@ccapurso after looking into the audit log found one of our clients went crazy and created around 994 tokens during 100 min. 

TTL for most of the clients is 5 min, specifically, the crazy client is attached to a policy where the token TTL is 2764800. 
right now there is no limit applied to auth/cert//login. 

rate limit should calm down the mem usage and prevent any future degradation. 
In addition, the token store and expiration manager must not load all non-expiring entities into the memory, 
a sorted heap with pagination mitigates mem expanding.

Feel free to close if no intent to change the underlying data structure or design.

**Comment by ccapurso** [comment]
@shaj13, thank you for the additional information. I do not believe we have plans to change this at this time. I would agree that rate limiting applied to auth/cert/login would mitigate this situation.
