### ISSUE TITLE
Two nil values returned from ParseSecret function

### ISSUE THREAD

**Issue by andrewcameronsims** [hashicorp/vault#18836]
**Describe the bug**
This report concerns the `api` package of this repo.

My understanding of the following API is that when I call it I should get either a nil error, or a nil response, but not two nils. E.g., the following code should handle all cases:

```go
// r is an io.Reader

parsed, err := secret.ParseSecret(r)
if err != nil {
  return err
}

// do something with parsed

```

However it looks like there is a branch where two nils are returned. Which means I need to check both that the error is nil but also that the actual parsed value is **not** nil. https://github.com/hashicorp/vault/blob/b6c02b15f5672f250e509d616c2201112b22b1c1/api/secret.go#L320-L322

Note that this is not only a problem with calling `ParseSecret` directly, since this function gets called indirectly in interactions through the vault client. (That's how I came across it.)
https://github.com/hashicorp/vault/blob/b6c02b15f5672f250e509d616c2201112b22b1c1/api/logical.go#L258

I am just wondering whether this is something I should indeed be checking for in my calling code, or whether this might be an undesired behaviour or bug. I could not find an answer to this in existing issues.

Thanks a lot for the great work, and I appreciate any insight you could give me on this question!

**Comment by maxb** [comment]
This return case represents the situation of "There is no error, but neither is there an HTTP response either".

For example, a case where an operation is invoked using a POST or PUT request and it returns an HTTP 204 No Content response.

**Comment by ccapurso** [comment]
Yes, as @maxb points out, this is to handle the case of an HTTP 204 No Content response. There are various cases where Vault will respond with a 204, for example deleting a KV secret. Does this answer your question, @andrewcameronsims?

**Comment by andrewcameronsims** [comment]
Yes it does, thank you very much.
