### ISSUE TITLE
Bypassing authentication on `GET /sys/wrapping/lookup` results in `500` instead of `403`

### ISSUE THREAD

**Issue by ludovicianul** [hashicorp/vault#18852]
**Describe the bug**
Doing a `GET` on ` /sys/wrapping/lookup` without sending the authentication token results in `500`, rather than `403`. 

**To Reproduce**
```shell
curl  -X GET \
      -H "Accept: application/json" -H "Content-Type: application/json" \
      http://localhost:8200/v1/sys/wrapping/lookup
```

**Expected behavior**
A `403` response.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.12.2
* Vault CLI Version (retrieve with `vault version`): v1.12.2
* Server Operating System/Architecture: macOS Ventura 13.0.1

**Comment by ccapurso** [comment]
Hi @ludovicianul. Thank you for bringing this to our attention! I have opened https://github.com/hashicorp/vault/pull/18859 to fix this.
