### ISSUE TITLE
Feature: Allow adding metadata to userpass users

### ISSUE THREAD

**Issue by frodopwns** [hashicorp/vault#1893]
Would love to be able to store metadata about a user when i create one.

ex

```
vault write auth/userpass/users/mitchellh \
    password=foo \
    policies=admins \
    nickname=mitch \
    team=hashicorp
```

This metadata could then be added to the meta field of the tokens that are created for this user.
This would allow me to use Vault tokens for auth/authz for external services.

**Comment by jefferai** [comment]
I think this is a good idea!

**Comment by frodopwns** [comment]
I would be interested in working on this feature if you think it wouldn't take too drastic of a change.

**Comment by jefferai** [comment]
Totally happy to have you work on it. Can you propose how it should be done? I'm not sure if we should assume any arbitrary key-value pair that is passed in should be metadata, in case we decide we actually want to reserve a field later. It might be better to have a value called "metadata" that takes in a map.

What I don't remember offhand is if there is a good way to pass in such a value on the CLI (it's certainly not common if so), so doing it that way might run the risk of making this an API-only option.

**Comment by frodopwns** [comment]
Sure, will take me a bit to familiarize myself with the relevant code but I will try to formulate how it can be done.

**Comment by frodopwns** [comment]
Could we keep a blacklist of fields that are reserved and skip those fields when gathering the meta data from the input? That way if you choose to add another reserved field in the future it should just work.

Otherwise it looks like the cli options for making a nested fieldset are limited to stdin and using a json file.

```
$ echo -n '{"password":"foo", "meta": {"nickname": "mitch"}}' | vault write auth/userpass/users/mitchellh -
```

or

```
$ cat pass.json | vault write auth/userpass/users/mitchellh -
```

**Comment by SoheilMazaheri** [comment]
That would be a great feature if we could add such metadata to tokens issued by other Vault Auth methods as well, i.e. LDAP, RADIUS, etc.

We have a use case that we need to add few metadata to a token issued by LDAP or RADIUS auth methods. As of today, the only way for us to do it is to create a child of the original token to be able to specify the metadata at the creation time of the child token.

Cheers,
Soheil

**Comment by monokal** [comment]
I'd also be interested in the ability to store custom metadata attached to a specific secret.

**Comment by candlerb** [comment]
Depending on your requirements, it's already possible to add metadata to the associated [entity](https://www.vaultproject.io/api-docs/secret/identity/entity) which is created when a user logs in for the first time (or you can [pre-create it](https://learn.hashicorp.com/tutorials/vault/identity)).

```
vault write auth/userpass/users/alice password=tcpip123 policies=whatever

# Alice does this
vault login -method=userpass username=alice password=tcpip123

# Back to admin
vault list identity/entity/id
Keys
----
7d9d5f07-9515-67c7-ae6f-f48fada1d584

vault read identity/entity/id/7d9d5f07-9515-67c7-ae6f-f48fada1d584
Key                    Value
---                    -----
aliases                [map[canonical_id:7d9d5f07-9515-67c7-ae6f-f48fada1d584 creation_time:2021-02-19T16:10:17.694518019Z id:7f550923-d4a9-1c9b-a9b2-3
creation_time          2021-02-19T16:10:17.694486016Z
direct_group_ids       []
disabled               false
group_ids              []
id                     7d9d5f07-9515-67c7-ae6f-f48fada1d584
inherited_group_ids    []
last_update_time       2021-02-19T16:10:17.694486016Z
merged_entity_ids      <nil>
metadata               <nil>
name                   entity_2ab3f91d
namespace_id           root
policies               <nil>

vault write identity/entity/id/7d9d5f07-9515-67c7-ae6f-f48fada1d584 - <<"EOH"
{
  "metadata": {
    "ssh_username": "alice1"
  }
}
EOH

$ vault read identity/entity/id/7d9d5f07-9515-67c7-ae6f-f48fada1d584
Key                    Value
---                    -----
aliases                [map[canonical_id:7d9d5f07-9515-67c7-ae6f-f48fada1d584 creation_time:2021-02-19T16:10:17.694518019Z id:7f550923-d4a9-1c9b-a9b2-3501e32f01cc last_update_time:2021-02-19T16:10:17.694518019Z merged_from_canonical_ids:<nil> metadata:<nil> mount_accessor:auth_userpass_1d98d325 mount_path:auth/userpass/ mount_type:userpass name:alice]]
creation_time          2021-02-19T16:10:17.694486016Z
direct_group_ids       []
disabled               false
group_ids              []
id                     7d9d5f07-9515-67c7-ae6f-f48fada1d584
inherited_group_ids    []
last_update_time       2021-02-19T16:22:55.19339157Z
merged_entity_ids      <nil>
metadata               map[ssh_username:alice1]
name                   entity_2ab3f91d
namespace_id           root
policies               <nil>
```

I can then create an ssh role with:

```
  "allowed_users": "root,{{identity.entity.metadata.ssh_username}}",
```

and it works as expected.

The entity represents the actual "user" who may have multiple ways of authenticating.  However if you need to tag specifically the userpass credentials, e.g. date of last password change, this may not help.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
