### ISSUE TITLE
Vault stalls if audit file is full

### ISSUE THREAD

**Issue by cpboyd** [hashicorp/vault#18943]
**Describe the bug**
If the audit file fills, Vault will eventually stall preventing any access.

**To Reproduce**
1. Enable audit file: https://developer.hashicorp.com/vault/docs/audit/file
2. Allow audit file to fill
3. Attempt to authenticate and retrieve values

**Expected behavior**
Vault should continue to operate

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    1
Threshold                1
Version                  1.12.1
Build Date               2022-10-27T12:32:05Z
Storage Type             raft
Cluster Name             vault-cluster...
Cluster ID               ...
HA Enabled               true
HA Cluster               https://vault-0.vault-internal:8201
HA Mode                  active
Active Since             2023-01-30...
Raft Committed Index     ...
Raft Applied Index       ...
```
* Vault CLI Version (retrieve with `vault version`):
```
Vault v1.12.1 (e34f8a14fb7a88af4640b09f3ddbb5646b946d9c), built 2022-10-27T12:32:05Z
```
* Server Operating System/Architecture: vault-helm chart

Vault server configuration file(s):

```hcl
disable_mlock = true
ui = true

listener "tcp" {
  tls_disable = 1
  address = "[::]:8200"
  cluster_address = "[::]:8201"
}

storage "raft" {
  path = "/vault/data"
}

service_registration "kubernetes" {}
```

**Comment by remilapeyre** [comment]
Hi @cpboyd, this is on purpose as explained at https://developer.hashicorp.com/vault/docs/audit#blocked-audit-devices:

> Audit device logs are critically important and ignoring auditing failures opens an avenue for attack. Vault will not respond to requests when no enabled audit devices can record them.
>  ...
> In other words, Vault will not complete any requests until the blocked audit device can write.

You need to enable multiple audit devices if you want to avoid this. If you absolutely want to continue operations despite a blocked audit device and have no way to set up another one you can add a `file` audit device with the `file_path` argument  set to `discard` (see https://developer.hashicorp.com/vault/docs/audit/file#discard).

**Comment by cipherboy** [comment]
@remilapeyre is correct here. The discussion forum might be a more appropriate venue for this topic as we consider this by design.

**Comment by cpboyd** [comment]
@remilapeyre @cipherboy It's a valid point that a blocked audit log may represent a potential attack vector, but there's no mention of this on https://developer.hashicorp.com/vault/docs/audit/file or the example for the Vault helm chart: https://developer.hashicorp.com/vault/docs/platform/k8s/helm/examples/standalone-audit

The audit file documentation does not currently emphasize that setting up log rotation is necessary for a fully functional Vault. It might help if the guides and instructions included a simple example for setting up log rotation.

I realize that my setup may be a little unusual, as I'm migrating Airflow with un-optimized secret calls which result in the helm's default 10GB volume being filled within a day.

**Comment by cipherboy** [comment]
@cpboyd The top of that first link says:

> The device does not currently assist with any log rotation. There are very stable and feature-filled log rotation tools already, so we recommend using existing tools.

And like Remi pointed out, the main docs for audit logging do call this out explicitly, too, as it is independent of audit type (e.g., if the rsyslog server goes down and no alternative devices are available, this will also stop Vault from processing new requests).

**Comment by optiz0r** [comment]
When vault is running clustered, should a single node running out of disk space for the audit log be a trigger for an automatic failover to another node, which can then potentially continue servicing requests? Despite running vault n+4 and the other 4 nodes having plenty of disk space, we've had an outage where the unhealhty vault leader with no free space stalled on auditing rather than giving way to another instance.

**Comment by remilapeyre** [comment]
The Raft protocol protects against network failures and partitions but it does not protect against this sort of issues. When the file cannot be written to Vault does not know whether this is a global issue or a local one. For example if the file is on a network share a network issue will make it impossible to write to the file for all the nodes in the cluster.

To protect yourself against outages related to an inaccessible audit device you can configure multiple audit devices, for example with a file on another disk that gets rotated more often, if you want you could also use `/dev/null` to make sure that the file being inaccessible will not stop the service.

You should also check the metrics, some of them will show if there is issues with the audit system.

**Comment by optiz0r** [comment]
Understood, but could the audit device stalling not flag the Vault instance as unhealthy and trigger a raft failover to another node in this case? Could this be configurable? I understand that if the audit device was on a shared filesystem all nodes would be equally affected, but if the audit file is a local filesystem, the other cluster members could all continue to function. The Operator can make this distinction, even if Vault itself cannot. On an N+4 HA service, should a local environment issue on a single node really cause a total outage?
