### ISSUE TITLE
vault api `Logical()` vs. endpoint wrapper

### ISSUE THREAD

**Issue by FalcoSuessgott** [hashicorp/vault#18969]
When working with vaults API, I observed a weird behavior with certain endpoints.

Meanwhile, `client.Sys().Health()` works as expected, `client.Logical().Read("sys/health")` responds no data. On the other hand, `client.Logical().Read("sys/ha-status")` works as expected.

Are certain endpoints different in terms of returning its data? Am I missing something?

```go
package main

import (
	"log"
	"fmt"

	vault "github.com/hashicorp/vault/api"
)

func main() {
	config := vault.DefaultConfig()

	config.Address = "http://127.0.0.1:8200"

	client, err := vault.NewClient(config)
	if err != nil {
		log.Fatalf("unable to initialize Vault client: %v", err)
	}

	client.SetToken("hvs.p8ZRMQuvRFb22HrawGfdEYkr")

	fmt.Println("wrapper: ")
	fmt.Println(client.Sys().Health())

	fmt.Println("logical:")
	fmt.Println(client.Logical().Read("sys/health"))

	fmt.Println("logical ha-status")
	fmt.Println(client.Logical().Read("sys/ha-status"))
}
```

Outputs:

```bash
wrapper: 
&{true false false false disabled disabled 1675426987 1.12.1 vault-cluster-a65f6a8b f23d707e-a3cc-1c38-2846-6087efa8c3ac 0} <nil>
logical:
&{  0 false map[] [] <nil> <nil>} <nil>
logical ha-status
&{2365b3ec-45fd-2326-ce11-cb2d54cdd747  0 false map[nodes:[map[active_node:true api_address: cluster_address:https://0.0.0.0:8201 hostname:userhost last_echo:<nil> version:1.12.1]]] [] <nil> <nil>} <nil>
```

Vault Version: 1.12.1
Vault API Version: 1.8.1

**Comment by maxb** [comment]
Hi @FalcoSuessgott ,

Yes, the majority of endpoints in Vault return a specific JSON structure: https://github.com/hashicorp/vault/blob/6a8e377b725562eb6b7689f5300ba87d64fbb455/api/secret.go#L14-L40

That is what the `Logical()` API works withh.

However, some endpoints, such as `sys/health`, return simple JSON objects that don't follow this convention, and cannot be worked with, using the `Logical()` API.

**Comment by FalcoSuessgott** [comment]
Aaah I see Logical Returns `Secret()` and that is usually when working with secrets I understand.

Thank you, took me a while now :D

**Comment by FalcoSuessgott** [comment]
> However, some endpoints, such as `sys/health`, return simple JSON objects that don't follow this convention, and cannot be worked with, using the `Logical()` API.

Wouldnt it be useful in that case to return an error msg indicating that response cannot be marshalled into  ` Secret`?

**Comment by hghaf099** [comment]
Thanks for filing this ticket. One issue that I noticed is that the Vault API version that is used is pretty old in comparison the Vault server version. I do reproduce the issue with that version in the CLI running the command: `vault read sys/health`. However, upgrading to the latest Vault 1.12.x, I could query the health endpoint using the same command and get the expected response back. 

```
$>VAULT_ADDR=http://127.0.0.1:8200 vault read sys/health
Key                             Value
---                             -----
cluster_id                      55dbefab-b211-9f69-bbc0-69547c8063c7
cluster_name                    vault-cluster-bb7bc510
initialized                     true
performance_standby             false
replication_dr_mode             disabled
replication_performance_mode    disabled
sealed                          false
server_time_utc                 1683068689
standby                         false
...
```

I am closing this issue as it is not reproducible in the latest supported Vault versions. Please feel free to open a new issue or reopen this issue for further discussions.
