### ISSUE TITLE
Vault UI: support filter for auth methods by type (k8s, jwt, ...)

### ISSUE THREAD

**Issue by Ais8Ooz8** [hashicorp/vault#19001]
Why is this needed? Since we must specify a specific cluster for the **Kubernetes method** and we cannot create a nested structure and add more than one cluster (more than one CA certificate, more than one JWT, and so on), we are forced to create a separate method for each cluster (for example, you don’t need to do this in the case of the **AppRole method**, when it is enough to create one single method of this type and add as many roles as you want). As a result, there can be a lot of methods in the UI, it would be more convenient to have a **filter by method type**.

**Comment by Monkeychip** [comment]
@Ais8Ooz8 thank you for the issue. We recently added filtering to the secret engine list view. I had a moment, so I snuck the same filtering (by name and type) into the auth method list view as well. This should be added in the 1.14 release. https://github.com/hashicorp/vault/pull/20747
