### ISSUE TITLE
vault backup data is empty

### ISSUE THREAD

**Issue by SydOps** [hashicorp/vault#1900]
install consul and vault at same instance and clustered (totally 3 instances)

When run `consulate  kv backup -b -f consult.json` I got an empty file:

```
$ cat consult.json
[]
```
Then I did below test:

run `consul members` I can see them all. 

vault works fine. 

login `http://<consule_IP>:8500`, I can see the services of both `consul` and `vault` and all nodes. 

But when click `key/value`, there is no any key/value displayed. 

What should I check?

**Comment by jefferai** [comment]
I don't really know as I've never used consulate. I recommend opening an issue on their issue tracker. Sorry!
