### ISSUE TITLE
INFORMATION NEEDED: identifier for macOS signed binary artifact is CHANGED to a.out, permanently?

### ISSUE THREAD

**Issue by arubdesu** [hashicorp/vault#19030]
This is an observation more than a bug _necessarily_ as functionality is unchanged, but when it comes to trustworthiness of a signing pipeline any observed change feels worth reporting. If a value I rely on for what makes up part of a cryptographic signature needs to be updated, I'd hope it's intentional and 'permanent' instead of arbitrary and potentially unreliable.

I'm assuming the signing for vault uses something like [gon](https://github.com/mitchellh/gon), and that it is secured adequately all the way up to being posted for release/download. I don't see anything in the release notes that indicates the observation I'm reporting is a temporary or permanent change or intentionally altered configuration.
A common tool for macOS software distribution for institutions (in comparison to homebrew which manually :yolo:'s whatever a maintainer attests is The Canonical Binary™+hash for a resource) is the [autopkg](https://autopkg.github.io/autopkg/) project. It uses [code signature verification](https://github.com/autopkg/autopkg/wiki/Using-CodeSignatureVerification), which in turn relies on the codesign binary (via the --display -r- --deep -v flags with the path to the binary) on the Mac to determine if an artifacts 'designated' field matches a [recorded string](https://github.com/autopkg/hjuutilainen-recipes/blob/7c3af44674e5a1e2c256d45014c956cc5ce60345/HashiCorp/Vault.download.recipe#L60) exactly. As of the 1.12.3 darwin releases, the 'signature' doesn't match because instead of recording the cert values with the 'vault' identifier for the binary, it's instead using [a.out](https://en.wikipedia.org/wiki/A.out), ye olde 'assembler output' format/naming of yore that golang adopted as a default. I can't imagine this is cause for alarm, but the difference breaks our recipe until we (the autopkg community) update the value.

**To Reproduce**
1. curl/download the 1.12.2 and 1.12.3 darwin arm64 or amd64 releases from https://releases.hashicorp.com
2. unzip the 1.12.2 version to a distinct path or /tmp and rename output from filename 'vault' to vault1.12.2 
3. run `codesign --display -r- --deep -v /path/to/vault1.12.2`
4. note the second line in the output `Identifier=vault` and beginning of the last line `designated => identifier vault...`
5. unzip the 1.12.3 version to a distinct path or /tmp and rename output from filename 'vault' to vault1.12.3
6. run `codesign --display -r- --deep -v /path/to/vault1.12.3`
7. note `Identifier=a.out` in the output and beginning of the last line `designated => identifier "a.out"`

**Expected behavior**
The designated => field should match the `identifier vault` string prefix previously used, or confirmation this will be how the compiled binary is signed/identified in the future

**Environment:**
* Vault Server Version (retrieve with `vault status`): n/a, but I work at an Enterprise Vault customer and we're running Vault 1.10.6+ent
* Vault CLI Version (retrieve with `vault version`): $current
* Server Operating System/Architecture: n/a

Vault server configuration file(s):

```hcl
n/a
```

**Additional context**
Thank you for your time and attention! 🙇

**Comment by mdeggies** [comment]
Hey @arubdesu, thanks for sending this our way. We did some digging, and it looks like we unintentionally missed setting the binary identifier during the mass resigning effort on 1/23 that was [described here on our status page](https://status.hashicorp.com/incidents/xbbwr755y78b). We will be planning a separate maintenance window to resign and republish the affected darwin artifacts. We'll share more info soon, but just wanted to thank you again for flagging this.

**Comment by arubdesu** [comment]
I'm relieved that you responded and confirmed this was unintentional/temporary, thanks so much! I also took the good advice from the homebrew core formula and will watch the releases mailing list for updates.
I'll close this out as I can trust that even if it's the same tag/version, the next release would have a changed etag/hash and re-download, so my automation will pick up on it and be able to load the patch in for distribution. 🤜🤛

**Comment by mdeggies** [comment]
Thanks for your note! We scheduled a [maintenance window](https://status.hashicorp.com/incidents/f7bz2z28w6pv) to address this for historical artifacts on March 20 at 16:00 UTC. This will be fully resolved after that maintenance window completes.
