### ISSUE TITLE
Log information to integrate with SIEM tool

### ISSUE THREAD

**Issue by ghost** [hashicorp/vault#1907]
Hello everybody. I don't know whether this is the right place or not. If this is not the right place just feel free to close this "issue" or tell me "go away" :). 

I have got vault logs samples and I'm planning to integrate with Splunk and Alienvault but I'm a bit confused with logs structure and I was looking for documentation about it but I couldn't find anything. I don't know if I'm looking in wrong place or you can help me with that. 

I barely understand logs from consult like the "requests". I'm normally not an expert in any tool that I integrated with SIEM but I always can do something with documentation.

If you know something I would appreciate your help.

**Comment by vishalnayak** [comment]
This should be a good place to start https://www.hashicorp.com/blog/splunk-app-for-monitoring-hashicorp-vault.
