### ISSUE TITLE
audit log panic when revoking pki certificates

### ISSUE THREAD

**Issue by devopsbrett** [hashicorp/vault#1911]
Hi, I'm getting a 500 error when trying to revoke a cert generated by the pki backend, it works however there seems to be an issue with the audit log:
Server Version: 0.6.1
Client Version 0.6.1

```
vault read pki/cert/76:39:54:d0:97:b7:46:6c:2d:84:34:00:39:1a:2e:2b:97:6f:55:74
...
revocation_time	0
```

```
vault write pki/revoke serial_number="76:39:54:d0:97:b7:46:6c:2d:84:34:00:39:1a:2e:2b:97:6f:55:74"
Error writing data to vaultca/revoke: Error making API request.

URL: PUT https://...:8200/v1/pki/revoke
Code: 500. Errors:

* internal error
```

```
vault read pki/cert/76:39:54:d0:97:b7:46:6c:2d:84:34:00:39:1a:2e:2b:97:6f:55:74
...
revocation_time	1474539332
```

When looking at the system log on the server running vault I see the following:
```
Sep 22 10:15:36 ... vault[21131]: 2016/09/22 10:15:36.367332 [ERR] audit: panic during logging request_path=pki/revoke error=reflect: reflect.Value.Set using value obtained using unexported field
Sep 22 10:15:36 ... vault[21131]: 2016/09/22 10:15:36.367367 [ERR] core: failed to audit response request_path=pki/revoke error=panic generating audit log
```

**Comment by jefferai** [comment]
I'm digging into this. I know the cause -- a field that was added to the output. I don't yet know the why, however.

**Comment by jbardin** [comment]
@jefferai: simply being addressable doesn't mean a reflect.Value can be set -- i.e. it's an unexported field: https://github.com/hashicorp/vault/blob/master/audit/hashstructure.go#L231

copystructure just guards these with `CanSet()`

**Comment by jefferai** [comment]
It's not unexported. This is a value inside a map[string]interface, not a struct. The other values don't trigger an issue, and if this value is a string instead, it works fine.

**Comment by jbardin** [comment]
It's from an unexported field contained in the value in the interface. In this case you have a `*time.Location` taken from the unexported `Time.loc` field. This has a string field (also unexported) which is what makes it down to line 231.

**Comment by jefferai** [comment]
Oh, it's reaching *inside the `time.Time` struct*.

That does make sense as to what's going wrong. It seems like it should be ignoring non-exported structs and/or struct values. I would have thought it was doing that already.  :-/

**Comment by jbardin** [comment]
yeah, reflect just goes as deep as it can, and the callbacks have to check if the fields can be set.
