### ISSUE TITLE
Consul backend doesn't return list of configured roles

### ISSUE THREAD

**Issue by igormoochnick** [hashicorp/vault#1917]
For security and auditing purposes our automation validates that there is no deviation from the previously configured roles. For this purpose it tries to list all the previously configured roles for consul backend and tries to HTTP GET list of roles from the path "/consul/roles/".

I understand that, according to the documentation, it's not implemented. Any particular reason it's can't be implemented (ex: some technological limitation)?

Ex: Postgeres backend has both GET roles and LIST roles commands (https://www.vaultproject.io/docs/secrets/postgresql/index.html)

  Thank you

**Comment by jefferai** [comment]
There's no particular reason it can't be, it just hasn't been.

**Comment by igormoochnick** [comment]
I'll try to send a PR
