### ISSUE TITLE
Support Signing JSON object and providing JWKS url

### ISSUE THREAD

**Issue by UXabre** [hashicorp/vault#19209]
**Is your feature request related to a problem? Please describe.**
Google's IAM provides an out-of-the-box solution to sign JWTs which could be used for client assertion scenarios (e.g. authenticate with OIDC client instead of using a secret).
However, this is very locked in to Google and we're actually using Azure even and there this functionality is not provided at all (unless one would code it).
I think this would be a gamechanger as signing a JWT and providing JWKS URL to validate them is quite common and like I said, very useful to generate client_assertions which can be used in various other circumstances

**Describe  the solution you'd like**
A new secret provider or perhaps an additional mode on top of the transit mode? Transit mode can sign and verify anything but it can't sign a json and make it a JWT.

**Describe alternatives you've considered**
The alternative is using Azure Key Vault to sign a JSON object

**Explain any additional use-cases**
- for now my use-case is generating user-assertion JWTs
- Other more generic signed token use-cases (e.g. sign this configuration JSON so I know I can trust the originator)

**Comment by austingebauer** [comment]
Thank, @UXabre! I agree this would be a useful feature. I could see this working in a few different ways as you've mentioned. Do you know about Vault's [identity token](https://developer.hashicorp.com/vault/docs/secrets/identity/identity-token) feature? Vault can currently [generate and sign JWTs](https://developer.hashicorp.com/vault/docs/secrets/identity/identity-token#token-generation) with arbitrary claims and publishes a JWKS for client-side signature verification.

**Comment by austingebauer** [comment]
@UXabre - I'm going to close this feature request as Vault currently does support [signing JWTs](https://developer.hashicorp.com/vault/api-docs/secret/identity/tokens#generate-a-signed-id-token) and [provides a JWKS](https://developer.hashicorp.com/vault/api-docs/secret/identity/tokens#read-active-public-keys) for applications to verify JWT signatures. Feel free to open another issue if you have some specific feature request for this system.

**Comment by antonmos** [comment]
@austingebauer the current vault functionality does not support customizing claims that come from outside of vault's roles, which is necessary to create Access Tokens. The apis you link generate IDTokens which are not the same.
