### ISSUE TITLE
Improve Vault error message for no syslogd

### ISSUE THREAD

**Issue by grahamjenson** [hashicorp/vault#1923]
While dockerising and migrating vault, we hit an issue where vault would crash after unsealing with the error `Unix syslog delivery error` which is not obvious that it is because because `audit` requires `syslog` daemon. 

This took many hours to find this error and fix by adding `RUN apk add syslog-ng -f` to the Dockerfile and then executing `syslogd` before launching vault.

I think that that vault should check for a syslog daemon on startup, and if required and no syslog is found it should error with a clear error like 'no syslog dameon found'.

**Comment by jefferai** [comment]
Logging to syslog is a system facility but checking if anything is actually on the receiving end is not. I don't know of a portable way to check for this outside of essentially grepping through lists of process names) -- none of which can be guaranteed to actually be listening on the given facility/socket/IP/whatever and requiring a static list of known process names (which means things will fail if a different, "unknown" syslog daemon is being used, which isn't good).

One way around this would be to send audit logs to a file and have your syslog ingress those, or send them somewhere else on their own. This is also significantly faster.

I'm going to close this, but if you can find a way that is portable and isn't scanning through running processes to match a static list of syslog processes to detect whether a syslog is running, please ping back.

**Comment by grahamjenson** [comment]
Could you not on start up try to write to the syslog so that at least vault will fail on startup instead of on unseal, wrap it so that it would know the error that occurred?

**Comment by jefferai** [comment]
What if a syslog daemon doesn't exist? None is necessary unless the syslog audit backend requires it. Attempting to write to syslog would therefore cause an error that otherwise wouldn't be an issue.

**Comment by grahamjenson** [comment]
Is it possible to tell @ startup before unsealing vault if the audit backend requires syslog? If yes then you could throw an error early if the dependency is not met, if not then there is not much you can do other than error when unsealed.

**Comment by jefferai** [comment]
It's not possible. The mount configuration is stored in the encrypted barrier.

**Comment by grahamjenson** [comment]
Cool, then there is nothing that can be done.
