### ISSUE TITLE
Too much permissions needed by auto unseal in azure

### ISSUE THREAD

**Issue by raven-wing** [hashicorp/vault#19263]
**Describe the bug**
Too many permissions needed by auto unseal in azure.

**To Reproduce**
1. Go to instruction of autounseal on azure. [HERE](https://developer.hashicorp.com/vault/tutorials/auto-unseal/autounseal-azure-keyvault)
2. Read it until you get to point 23, check 24. Wander - why?

**Expected behavior**
Permissions should not let you do 'anything'.

**Environment:**
* Azure
* Hashicorp's tutorial

**Comment by Threpio** [comment]
These permissions are for the AzureRM terraform service principle to be created. 

Why these permissions are required can be read about here: a [Terraform AzureAD 'Configuring a User or Service Principal'](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/service_principal_configuration)

**Comment by raven-wing** [comment]
Wow! Thanks. Then this is so much misleading.:

```
Create an Azure service principal
To delegate the credential generation task to Vault, you need to give Vault privileged Azure credentials to perform the task. The following demonstrates the creation of a service principal.
```

It indicates that there are we are giving vault privileges in section. It should explicitly say that its preparing for further usage of terraform. To prove that I'm not the only one 'dummy' I just found old question [HERE](https://discuss.hashicorp.com/t/azure-auto-unseal-are-these-permissions-needed/31964)

**Comment by Threpio** [comment]
In a production environment, the same service_principle for creating resources should not be the same as the service_principle that the vault is used with/uses. 

I believe that this instruction/tutorial is a quickstart and not aimed at production scenarios but I do agree that the second line could mention that.

**Comment by hsimon-hashicorp** [comment]
Fixed in https://github.com/hashicorp/tutorials/pull/1280
