### ISSUE TITLE
APT Install - Focal release not signed

### ISSUE THREAD

**Issue by ellisroll-b** [hashicorp/vault#19292]
**Describe the bug**
Suddenly can't use APT to install Vault

**To Reproduce**
Script is used. Here is the input and output:
#13 [ 9/21] RUN echo "deb https://apt.releases.hashicorp.com/ $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
11:28:09  #13 2.133 deb https://apt.releases.hashicorp.com/ focal main
11:28:09  #13 DONE 2.2s
11:28:09  
11:28:09  #14 [10/21] RUN apt update
11:28:11  #14 2.015 
11:28:11  #14 2.015 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
11:28:11  #14 2.015 
11:28:11  #14 2.177 Get:1 https://apt.releases.hashicorp.com/ focal InRelease [18.0 kB]
11:28:11  #14 2.265 Err:1 https://apt.releases.hashicorp.com/ focal InRelease
11:28:11  #14 2.265   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DA418C88A3219F7B
11:28:11  #14 2.277 Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
11:28:11  #14 2.293 Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease
11:28:11  #14 2.377 Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
11:28:11  #14 2.460 Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease
11:28:13  #14 2.629 Reading package lists...
11:28:13  #14 3.873 W: GPG error: https://apt.releases.hashicorp.com/ focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DA418C88A3219F7B
11:28:13  #14 3.873 E: The repository 'https://apt.releases.hashicorp.com/ focal InRelease' is not signed.
11:28:13  #14 ERROR: process "/bin/bash -c apt update" did not complete successfully: exit code: 100

**Expected behavior**
apt update, apt upgrade, apt install -y vault=1.12.2-1 works as it did yesterday

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.12.2
* Vault CLI Version (retrieve with `vault version`): n/a
* Server Operating System/Architecture:  Ubuntu 20.04

Vault server configuration file(s): n/a

**Additional context**
Something changes on GPG key as noted in the error reported by apt above

**Comment by jaredallard** [comment]
Same issue here, looks like a new key was added to the GPG keyfile but the old key is still the one being used for signing...

**Comment by ellisroll-b** [comment]
Minor update: 20.04 started working for Vault again, but use of 22.04 for other Hashicorp elements remains "unsigned"

**Comment by hsimon-hashicorp** [comment]
There was an issue with builds that occurred a couple of weeks ago. Is this issue still occuring?

**Comment by ellisroll-b** [comment]
Hi,
Looks like its resolved on both.  Thanks for the official followup.
