### ISSUE TITLE
Statsd telemetry doesn't recover from statsd outage

### ISSUE THREAD

**Issue by johnrengelman** [hashicorp/vault#1932]
It appears that `go-metrics` doesn't handle a disconnect of the statsd server, particularly if the address changes.

We are running a `telegraf` agent with a statsd listener and configuring vault to send data to a linked container with a hostname. When the linked container is restarted (generally getting a new IP address), we stop receiving statsd metrics from vault.

**Comment by jefferai** [comment]
This needs to be reported against `go-metrics` since it's handling the actual statsd server communication. Thanks!

**Comment by johnrengelman** [comment]
opened: https://github.com/armon/go-metrics/issues/39
