### ISSUE TITLE
Next release for zookeeper auth on reconnect

### ISSUE THREAD

**Issue by alexkuang** [hashicorp/vault#1933]
Using 0.6.1 with zookeeper as a backend, whenever the vault server loses the connection with zookeeper the server will fail to recover with error messages saying `zk: not authenticated`.

It seems related to an issue in go-zookeeper (https://github.com/samuel/go-zookeeper/issues/133) which looks like it was fixed in https://github.com/samuel/go-zookeeper/pull/139 .

Are there any plans for a release to propagate these changes to Vault?  If not, is there a rough schedule for release cadence?

Thanks!

**Comment by jefferai** [comment]
Updated ZK library has already been in Vault master for several weeks.

**Comment by alexkuang** [comment]
OK, thanks.  I had noticed the commits but was not sure whether it was ready-to-use or not.  Sounds like the recommendation is to manually build from master, so I'll give that a shot.

**Comment by jefferai** [comment]
I don't really have a recommendation, was just noting that the next release
will have the fix included.
