### ISSUE TITLE
 Add support for Okta number challenge (#15361)

### ISSUE THREAD

**Issue by adrian-mi-romero** [hashicorp/vault#19341]
There was PR commit https://github.com/hashicorp/vault/commit/a970427b52e7009b7bd6c950e206428b66982e5a created by https://github.com/calvn which added the support for Okta number challenge in vault. According to the notes in the merge it was supposed to be included in :
 
v1.13.0-rc1  v1.12.3 v1.12.2 v1.12.1 v1.12.0 v1.12.0-rc1 v1.11.7 v1.11.6 v1.11.5 v1.11.4 v1.11.3 v1.11.2 v1.11.1 v1.11

![image](https://user-images.githubusercontent.com/72120683/221166872-9f64426e-ced7-43ac-8629-70cb2a9c6f3c.png)

However when you go the official documentation for lastet vault version v1.12.X it statest that this feature is not supported. 

https://developer.hashicorp.com/vault/docs/auth/login-mfa/faq#q-what-is-single-phase-mfa-vs-two-phase-mfa

![image](https://user-images.githubusercontent.com/72120683/221167532-de36ed2e-64a8-405a-b259-34b699642b17.png)

How can we checked that @calvn feature is in deed included in v1.12.x ? and update the documentation accordingly.

we discussed this matter wtih @calvn in https://github.com/hashicorp/vault/pull/15361#issuecomment-1442320156 and it was suggested to open up a new issue. 

Thanks.

**Comment by hsimon-hashicorp** [comment]
Fixed in #19497
