### ISSUE TITLE
Docs mismatch between Interoperability Matrix and Entropy Augmentation for AWS KMS

### ISSUE THREAD

**Issue by karras** [hashicorp/vault#19404]
**Describe the bug**

I really appreciate the recently added matrix related to the seal capabilities and providers (thanks!):

* https://developer.hashicorp.com/vault/docs/interoperability-matrix

Upon closer inspection I noticed that AWS KMS does not support entropy augmentation according to the matrix. Though on the entropy augmentation page it lists AWS KMS as a supported stanza:

* https://developer.hashicorp.com/vault/docs/configuration/entropy-augmentation

```
Entropy augmentation enables Vault to sample entropy from external
cryptographic modules. Sourcing external entropy is done by configuring a
supported Seal type which include: PKCS11 seal, AWS KMS, and Vault Transit.
Vault Enterprises's external entropy support is activated by the presence of an
entropy "seal" block in Vault's configuration file.
```

Could you clarify if it is supported or not? I'd say mainly seals exposing PKCS#11 support entropy augmentation? I'm happy to fix that in a short PR then. :)

**To Reproduce**
n/a

**Expected behavior**
n/a

**Environment:**
n/a

**Comment by acahn** [comment]
Thank you @karras for the report. Let me take a look into this.

**Comment by karras** [comment]
@acahn Any updates on this? :)

**Comment by acahn** [comment]
Hi @karras - Thank you again for reporting the discrepancy. This will be resolved as soon as https://github.com/hashicorp/vault/pull/20501 is merged.
