### ISSUE TITLE
Handle wildcards in aws-ec2 role/instance profile arns

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#1941]

**Comment by mfischer-zd** [comment]
Use case: when using CloudFormation or Terraform to create IAM roles and instance profiles, the names will usually have a known prefix but a random suffix to prevent namespace collisions.  Allow the user to specify the prefix as a basis for matching the instance's IAM profile ARN.

**Comment by jefferai** [comment]
@mfischer-zd Don't worry, the use-case is understood. This was just to track it -- @vishalnayak is already done on the code!

**Comment by mfischer-zd** [comment]
Wow!  That was fast.  A+++

I like writing up these things for the historical record.   You never know when the code archaeologists will need to investigate something.
