### ISSUE TITLE
AppRole: Secret ID logged in clear text when used for GET or DELETE

### ISSUE THREAD

**Issue by bkrodgers** [hashicorp/vault#1944]
With the AppRole backend, if I use the forms of the GET or DELETE functions that take a secret ID, the secret ID is put in the path.  That is, the form:

`/auth/approle/role/[role_name]/secret-id/<secret_id>`

This results in an entry in the audit log:

`request.path : auth/approle/role/testrole/secret-id/xxxxxxxx-2b84-882c-9099-3ff267b16492`, 

which is the actual secret ID.

This seems bad.  Vault typically hashes sensitive data in the audit log, and even though they would also need the role ID, I would still consider this quite sensitive.  I also realize that since the API is taking these as path parameters, it's probably logging them through generic code that logs the path for all requests.  

You probably don't want to add an exception case to that code here, so the better approach in my mind is to go ahead with a breaking change to the API for these two methods to take the secret ID as a body parameter and not accept it as a query parameter.  For the GET, I know that there's some ambiguity in whether you can or should use a body with GET though, so you might need to make this a POST to something like `auth/approle/role/testrole/secret-id/properties`.  

I don't have a similar concern with the ones that use the secret ID accessor, as those are already logged in plain text and are expected to be.  If you think it's better to be consistent, there's no harm in changing those too, but I think they're fine.

**Comment by jefferai** [comment]
Yeah, these should be POST. I say we just break it as AppRole is very new (weeks old) and neither of these are critical paths for most workflows.
