### ISSUE TITLE
1.12.4 tag was not pushed to Dockerhub

### ISSUE THREAD

**Issue by thiagotonon** [hashicorp/vault#19473]
Hi!

I'm trying to pull the `1.12.4` tag from Dockerhub but it is returning the following error

```
GET https://index.docker.io/v2/library/vault/manifests/1.12.4: MANIFEST_UNKNOWN: manifest unknown; unknown tag=1.12.4
```

In dockerhub it appears that the tag wasn't pushed at all https://hub.docker.com/_/vault/tags?page=1&name=1.12

**Comment by VioletHynes** [comment]
Hi there! Thanks for the report - the tags for 1.13.0, 1.12.4, 1.11.8, 1.10.11 are still in progress for being pushed to Dockerhub. In other words, this is expected for right now.

I'm going to close this as this is 'as expected' for right now. They'll be there soon!
