### ISSUE TITLE
logical/postgres: isolate revocation errors

### ISSUE THREAD

**Issue by BSick7** [hashicorp/vault#1948]
Version: 0.6.1

## Overview

We currently mount a postgresql backend for each service. Typically, `postgresql-foo` for the service called foo.  I am seeing revocation errors for postgresql secrets `postgresql-foo` when trying to revoke/unmount `postgresql-bar`.  I expect these errors to be isolated per mount so that any errors don't negatively affect all postgresql secrets.

## Reproduction

These are steps that are generally happening with us.

1. Mount `postgresql-foo` and `postgresql-bar`
2. Configure them to hit `foo` and `bar` databases. (It may be helpful to have a short revocation period for `foo`)
3. read dynamic credentials from `postgresql-foo` and create schema in `foo`.
4. read dynamic credentials from `postgresql-bar` and create schema in `bar`.
NOTE: At this point, both `foo` and `bar` dbs have objects owned by ephemeral users.
5. Reassign `bar` objects to a long-term role.
6. Wait until the TTL has elapsed for the dynamic credentials to foo
7. Unmount `postgresql-bar` (which will force `bar` revocation)

At this point, you should see an error that looks something like this:

```
failed to revoke 'postgresql-foo/creds/app/<uuid>' (1 / 2): failed to revoke entry: resp:(*logical.Response)(nil) err: could not perform all revocation statements: pg: permission denied for ...
```

**Comment by jefferai** [comment]
Hi @BSick7 

Several of us have tried to reproduce this via a simplified workflow above with no luck. Any of the machinations that happened within Postgres should have no impact on Vault, because the lease (containing the path) is internal to Vault only.

If you can provide a repeatable test case -- e.g., starting from fresh Vault and a fresh Postgres docker instance, run these commands -- that would be very useful.

**Comment by BSick7** [comment]
I'll get you a working reproduction.

**Comment by jefferai** [comment]
Great, thanks!

**Comment by BSick7** [comment]
The manifestation of this has resolved in our environment.
This could be due to a number of reasons.
Since I'm having trouble reproducing in a narrow scope, I will close this.
