### ISSUE TITLE
No documentation or example on how to use manual_chain in pki secrets engine

### ISSUE THREAD

**Issue by Wnthr** [hashicorp/vault#19510]
**Description**
The `manual_chain` parameter has a verbal explanation of what it is for in the docs, but there are no example on how to put one together.

**Additional context**
What is clear is that it is a list of strings, but containing what? When trying the following command:

`# vault write pki/issuer/default manual_chain=foo`

I receive the following error message:

`* unable to find PKI issuer for reference: foo`

I would assume that means I need to format some kind of PKI issuer reference, but the (for me) obvious attempts have been in vain, getting me back to that exact same error message. Maybe there is documentation somewhere on what that kind of reference would look like that I am just not finding?

**Comment by cipherboy** [comment]
Documentation: https://developer.hashicorp.com/vault/api-docs/secret/pki#manual_chain
Examples: https://developer.hashicorp.com/vault/docs/secrets/pki/rotation-primitives#notes-on-manual_chain

These are the same as the `issuer_ref` parameter ("issuer reference") -- either the value of the `issuer_id` or `issuer_name` field, or the value `default`.

Here, it seems like `foo` doesn't exist as a named issuer; `vault list -detailed pki/issuers` should show you all issuers' id + names in one listing.

**Comment by cipherboy** [comment]
Let me know if you think there's a need for more documentation and examples here; otherwise I'm going to go ahead and close this for now.
