### ISSUE TITLE
Deleting entries in vault/sys/expire/id/auth/aws-ec2/login/

### ISSUE THREAD

**Issue by hamstah** [hashicorp/vault#1951]
Hi

I ended up with ~50000 entries in `vault/sys/expire/id/auth/aws-ec2/login/` due to a bug.

I'm trying to delete them as they waste a bunch of space.

curl http://xxx/v1/kv/vault/sys/expire/id/auth/aws-ec2/login/?recurse

I tried a to use revoke with `-prefix=true` on the whole prefix as well as with a specific entry.
```
vault revoke -address https://xxx -prefix=true sys/expire/id/auth/aws-ec2/login
vault revoke -address https://xxx -prefix=true sys/expire/id/auth/aws-ec2/login/fffcec7a9b75ddba98ddcf6ab75475ea2393b39e
```

But I can still get them with 
```
curl http://10.30.72.209:8500/v1/kv/vault/sys/expire/id/auth/aws-ec2/login/?recurse
```

Is there a different way to revoke them?
Is there a delay between revocation and seeing the result?

Thanks

**Comment by jefferai** [comment]
`revoke` takes a lease prefix, not a storage prefix. Try it with a prefix of `auth/aws-ec2/login`.

**Comment by hamstah** [comment]
Thanks, that was the issue.

It seems like deleting that much at once is making vault unhappy though, see below.

```
$ vault revoke -address https://xxx -prefix=true auth/aws-ec2/login
Revoke error: Error making API request.

URL: PUT https://xxx/v1/sys/revoke-prefix/auth/aws-ec2/login
Code: 504. Raw Message:
```

```
$ vault revoke -address https://xxx -prefix=true auth/aws-ec2/login
Revoke error: Put https://xxx/v1/sys/revoke-prefix/auth/aws-ec2/login: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by jefferai** [comment]
Yeah, seems like you're hitting a timeout. That's okay, though -- on each call it'll delete more. Or use more granular prefixes per request, or use a different client that lets you specify (or disable) client timeouts.

**Comment by hamstah** [comment]
Cool, just wanted to make sure it was expected and not something that needed reporting.

Thanks!
