### ISSUE TITLE
Mount-tune issue with leading forward slash in path

### ISSUE THREAD

**Issue by spunon** [hashicorp/vault#1956]
Mount tune says it successfully completes with the following command:
vault mount-tune -default-lease-ttl=720h -max-lease-ttl=1440h **/auth/token**

And sometimes it does (like in my clean lab setup vault 0.6.0) - but in the case of my staging setup (also 0.6.0) I needed to remove the leading slash on the path so it read **auth/token** for it to actually tune the mount.

Jeff mitchell asked me to create an issue in the following thread:
https://groups.google.com/forum/#!topic/vault-tool/WaYHTr9Xucc

**Comment by jefferai** [comment]
I'm curious -- is there any chance that you were using disparate versions of Vault CLI/server? Was it always 0.6.0/0.6.0 and 0.6.1/0.6.1?

**Comment by spunon** [comment]
We started with vault at 0.6.0, and are still using it. Its the issue resolved in 0.6.1?

**Comment by jefferai** [comment]
Oops, I thought I remembered from your mailing list post that you saw different behavior on 0.6.1. No worries!

**Comment by jefferai** [comment]
Hi @spunon ,

I just tried both ways with 0.6.1 and cannot replicate this. Whether I tune with or without a slash when I read the mount properties it correctly reflects the tuned value.

**Comment by jefferai** [comment]
Closing due to lack of response...please request reopening if needed.
