### ISSUE TITLE
Vault Browser CLI issues

### ISSUE THREAD

**Issue by dereckson** [hashicorp/vault#19568]
The **web UI** offers a small feature called _Vault Browser CLI_, a dropdown console directly in the Web UI.

Since 1.10, and still in 1.13, it seems the Vault Browser CLI UI has two issues:

- a formatting issue where correct list output is replaced by a oneline output
- `clear` still works, Vault command always print the main help

Here the message the most often printed:

```
Usage: vault <command> [args] Commands: read Read data and retrieves secrets write Write data, configuration,
    and secrets delete Delete secrets and configuration list List data or secrets Web CLI Commands: api Navigate to the Vault
    API explorer. Use 'api [filter]' to prefilter the list. clear Clear output from the log clearall Clear output and command
    history fullscreen Toggle fullscreen display refresh Refresh the data on the current screen under the CLI window
```

Previously, each element was on its own line.

**Comment by VioletHynes** [comment]
I don't seem to get this problem at all, so I'd like to better understand your environment:
```
violet@violet-TX54KFJWXM vault % vault help
Usage: vault <command> [args]

Common commands:
    read        Read data and retrieves secrets
    write       Write data, configuration, and secrets
    delete      Delete secrets and configuration
    list        List data or secrets
    login       Authenticate locally
    agent       Start a Vault agent
    server      Start a Vault server
    status      Print seal and HA status
    unwrap      Unwrap a wrapped secret

Other commands:
    audit                Interact with audit devices
    auth                 Interact with auth methods
    debug                Runs the debug command
    kv                   Interact with Vault's Key-Value storage
    lease                Interact with leases
    license              Interact with licenses
    monitor              Stream log messages from a Vault server
    namespace            Interact with namespaces
    operator             Perform operator-specific tasks
    patch                Patch data, configuration, and secrets
    path-help            Retrieve API help for paths
    pki                  Interact with Vault's Key-Value storage
    plugin               Interact with Vault plugins and catalog
    policy               Interact with policies
    print                Prints runtime configurations
    secrets              Interact with secrets engines
    ssh                  Initiate an SSH session
    token                Interact with tokens
    transit
    version-history      Prints the version history of the target Vault server
```

I have a few questions:
- What OS are you on?
- What terminal emulator are you using?
- Have you tried with a different terminal emulator, and are you getting the same problem?

**Comment by dereckson** [comment]
Indeed. Clarified the bug description to make more clear it's the browser widget.

**Comment by dereckson** [comment]
Thanks for the style fix.

For the second point, I tested with `vault kv` and `vault pki` commands, not supported there, so I guess that's why I had the feeling no other commands worked. Your test command with `vault list` works fine.

**Comment by hellobontempo** [comment]
Ah I see, at this time the UI web console only supports  `read`, `write`, `delete` and `list`. (More context why [here](https://github.com/hashicorp/vault/issues/13131#issuecomment-967282901)) With the formatting fixed hopefully that's a little clearer!
