### ISSUE TITLE
Vault Agent renders non-existent mssql dynamic secret

### ISSUE THREAD

**Issue by Letfdsada** [hashicorp/vault#19578]
**Describe the bug**
We encountered a case where the vault agent received the credentials of a non-existent user on a sql-server (mssql).
A second later, another sql-user was created, but the vault agent did not render it.
As a result, our application tried to use credentials from a non-existent user.
This is not expected behavior, is it?

**To Reproduce**
Unfortunately or fortunately, such a case happened once.
I have not been able to reproduce it at the moment. But I will supplement the issue if this happens again.

**Expected behavior**
Vault does not give out a secret if it was not successfully generated.
Vault Agent renders all the secrets it requests and ignores none.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.9.4
* Vault CLI Version (retrieve with `vault version`): We didn't use it in our case.
* Server Operating System/Architecture: Alpine Linux v3.14, x86_64
* Vault Agent Version: 1.10.3

Vault server configuration file(s):

We are using vault in k8s. hashicorp/vault: ~v0.20.1 chart.
Please tell me where can I find its config.

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

vault-agent logs (sorry about format, this is raw logs from Loki, i can fix it if you want it):
```
{"log":"2023-03-10T18:00:51.435Z [WARN] vault.read(database/creds/my-cool-role): renewer done (maybe the lease expired)\n","stream":"stderr","time":"2023-03-10T18:00:51.435742125Z"} <------ this one should be good, but don't rendered
{"log":"* failed to renew entry: resp: (*logical.Response)(nil) err: error verifying connection: mssql: login error: Login failed for user 'vault'.\n","stream":"stderr","time":"2023-03-10T18:00:51.435735224Z"}
{"log":"\n","stream":"stderr","time":"2023-03-10T18:00:51.435728924Z"}
{"log":"Code: 400. Errors:\n","stream":"stderr","time":"2023-03-10T18:00:51.435722824Z"}
{"log":"URL: PUT https://my.vault.address/v1/sys/leases/renew\n","stream":"stderr","time":"2023-03-10T18:00:51.435716924Z"}
{"log":"\n","stream":"stderr","time":"2023-03-10T18:00:51.435710424Z"}
{"log":"2023-03-10T18:00:51.435Z [WARN] vault.read(database/creds/my-cool-role): failed to renew: Error making API request.\n","stream":"stderr","time":"2023-03-10T18:00:51.435677124Z"}
{"log":"2023-03-10T18:00:50.659Z [WARN] vault.read(database/creds/my-cool-role): renewer done (maybe the lease expired)\n","stream":"stderr","time":"2023-03-10T18:00:50.659555617Z"} <----- this one is bad
{"log":"* failed to renew entry: resp: (*logical.Response)(nil) err: error verifying connection: mssql: login error: Login failed for user 'vault'.\n","stream":"stderr","time":"2023-03-10T18:00:50.659551017Z"}
{"log":"\n","stream":"stderr","time":"2023-03-10T18:00:50.659546817Z"}
{"log":"Code: 400. Errors:\n","stream":"stderr","time":"2023-03-10T18:00:50.659542417Z"}
{"log":"URL: PUT https://my.vault.address/v1/sys/leases/renew\n","stream":"stderr","time":"2023-03-10T18:00:50.659537417Z"}
{"log":"\n","stream":"stderr","time":"2023-03-10T18:00:50.659514917Z"}
{"log":"2023-03-10T18:00:50.659Z [WARN] vault.read(database/creds/my-cool-role): failed to renew: Error making API request.\n","stream":"stderr","time":"2023-03-10T18:00:50.659482317Z"}
```

Also I see several reads of this role at this time in the audit from the agent.:

![image](https://user-images.githubusercontent.com/33781732/225593180-99b4a7ab-2281-498c-8ab1-7ce22092137e.png)

In addition, we use a username template with timestamps. Here are the usernames generated by vault.
`v-my-cool-user-u3aabQ1CoTkOoDXQvehf-1678471251` <--- this should be good, but don't rendered
`v-my-cool-user-pCAySd4QZsS14sHcrvuK-1678471250` <--- this one is bad

Our creation statements:

```
use [my-cool-database]
execute sp_executesql N'
	commit
	set LOCK_TIMEOUT 1500
	create user [orphan-owner-{{name}}] with password = ''{{password}}''
	grant control on database::[my-cool-database] to [orphan-owner-{{name}}]
	begin transaction'
alter user [orphan-owner-{{name}}] with name = [{{name}}]
```

Also, in the logs of the sql-server, it can be seen that sessions were being killed, including the session of the vault-user, which creates temporary credentials.
But I don't understand how this could trigger our case.

Next time, if I see it, I will bring server logs. This time, they are lost.

**Comment by Letfdsada** [comment]
>I'm having a little trouble understanding the problem here:

I apologize if I wrote something not clear. I did not have enough logs to understand what exactly went wrong. Therefore, I wrote it as it seemed to me and I expect some help so that the case becomes transparent.

> On the surface - with my current understanding - it sounds like Agent is acting correctly, but there was a secret generated or accessible by your secret engine that you don't think should have been?

You are right.  `v-my-cool-user-pCAySd4QZsS14sHcrvuK-1678471250` was passed to the agent, despite the fact that the creation statements did not seem to work.

**Comment by Letfdsada** [comment]
I found that sometimes agent check new secrets after just second when `ttl` and `max ttl` is 10m.
```
vault-agent-vault-agent-1  | 2023-03-21T00:01:23.897Z [INFO] (runner) rendered "/vault-agent/secrets.json.ctmpl" => "/secrets-dest/secrets.json"
vault-agent-vault-agent-1  | 2023-03-21T00:01:23.907Z [WARN] vault.read(database/creds/db-reader-pipelines): TTL of "10m" exceeded the effective max_ttl of "9m59s"; TTL value is capped accordingly
```

I don't think is that root-cause, but place in second part of my issue, where agent makes a-la retry and not get new, the actually created, secret.

**Comment by biazmoreira** [comment]
> Credentials from database engine with username: v-my-cool-user-pCAySd4QZsS14sHcrvuK-1678471250 was passed to agent, despite the fact that the creation statements did not seem to work.

Would you be able to paste the logs from the creation statement(s)?

**Comment by biazmoreira** [comment]
> We encountered a case where the volt agent received the credentials of a non-existent user on a sql-server (mssql).

Also, can you clarify what you mean by the above statement? Based on the description and logs you added, no read operation succeeds. The following error is thrown twice:
 
> err: error verifying connection: mssql: login error: Login failed for user 'vault'

**Comment by hsimon-hashicorp** [comment]
As it has been some time since we've heard from you @Letfdsada, I'm going to go ahead and close this issue now. Please feel free to re-open it if you can answer Bianca's questions, or open a new issue for a new bug report. Thanks!
