### ISSUE TITLE
ECDSA test certificate expires soon

### ISSUE THREAD

**Issue by rzimmerman** [hashicorp/vault#19576]
**Describe the bug**
The certificate at https://github.com/hashicorp/vault/blob/e9ee430f251b5e9341cfa818ed769d5e611f8cbd/vault/diagnose/test-fixtures/ecdsa.crt expires on 2023-04-07. I believe this may break unit tests at that time.

**To Reproduce**
Cert dump:
```
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            9b:a5:74:d1:ea:ff:a5:50
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: C = US, ST = CA, L = PH, O = Hashicorp, OU = Vault, CN = ecdsa.vault.com, emailAddress = roy@hashicorp.com
        Validity
            Not Before: Apr  7 14:51:10 2021 GMT
            Not After : Apr  7 14:51:10 2023 GMT
...
```

**Environment:**
On latest main branch as of fbd27ff2abcd3ef425c3d637b9970aae1d532700.

Vault server configuration file(s):
N/A

**Comment by stevendpclark** [comment]
Thanks @rzimmerman for reporting the issue, should be addressed now.

**Comment by rzimmerman** [comment]
Thank you!
