### ISSUE TITLE
<pki>/cert/ca endpoint should contain all issuer certificates

### ISSUE THREAD

**Issue by Christoph-Raab** [hashicorp/vault#19577]
Vault version 1.11.0 added the feature of having multiple root CAs under the same pki engine mount.

After adding a second CA issuer with `vault write <pki>/root/rotate/internal` the `<pki>/cert/ca` endpoint doesn't return all issuer certificates but only the default one.

One can request all issuers `<pki>/issuers` which returns the ids and iterate over them `<pki>/issuer/<id>` but in my opinion that's unnecessary boilerplate.

I'm happy to open a PR if we can agree on how the response should look like.

```bash
$ curl "$VAULT_ADDR/v1/<pki>/cert/ca" | jq -r .
{
   "request_id": "...",
   "...",
   "data": {
    ?
  }
}
```

Probably an array containing all certificates of all issuers that are capable of issuing certificates

```
"data" {
  "certificates": [
    { "certificate": "----...", revocation_time": ...},
    { "certificate": "----...", revocation_time": ...},
  ]
}
``` 

Or without breaking changes all included in one field

```
"data" {
  "certificate": "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"
}
```

**Comment by cipherboy** [comment]
Correct, this was done for backwards compatibility. To fetch all, I'd suggest the unauthenticated `LIST /pki/issuers` and fetch the cert from `/pki/issuer/:issuer_ref/json`.

If you modify the response of this field, you risk breaking backwards compatibility with earlier Vault releases. If you're a multi-issuer aware application, use the multi-issuer aware API endpoints.

**Comment by Christoph-Raab** [comment]
> If you're a multi-issuer aware application, use the multi-issuer aware API endpoints.

Hm, that sounds very developer centric.

I use vault as external pki for kubernetes and deploy certificates on the hosts with consul-template. I want a clean solution to be able to deploy all ca issuer certificates on the hosts so I can rotate the ca.

Currently I use a workaround that fetches all certificates and writes them into a new secret, like

```
$ vault kv get -field=bundle <path>
-----BEGIN CERTIFICATE-----
CERT1
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
CERT2
-----END CERTIFICATE-----
```

While this is working I still think there should be a possibility to request all ca issuer certificates from one endpoint.

I somewhat understand you don't want to introduce breaking changes, though I think that has to be done at some point, right?

How about adding a new endpoint, like `pki/cert/ca/all` that returns this information. Or should I rather open an feature request in consul-template to add the functionality for the combined certificate retrieval?
