### ISSUE TITLE
API documentation for KV is too ambiguous and needs to be clarified

### ISSUE THREAD

**Issue by mikeycarlton** [hashicorp/vault#19599]
**Describe the bug**
Referencing the documentation for LIST Secrets here (but could apply to any of the KV secrets APIs): https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#list-secrets

For example:
`LIST /secret/metadata/:path`

The documentation indicates that for KV version 2 for the list secrets api, you are supposed to prefix paths with `<vault_url>/v1/secret/metadata/:path`. However, upon lots of trial and error, and googling this issue, it appears that you are actually supposed to use `<vault_url>/v1/<secret-engine-name>/metadata/<path-to-secret>` (no colon). What is infuriating here is that as a first time user of the Vault API, I shouldn't have to make the following assumptions:

1. That "secret" in the API is actually a _secret-engine_ and not a magic API keyword named _secret_
2. That the ":" in the documented API is also just a variable identifier, and not actually real

I am aware that for 1) there is a yellow box at the top of the documentation indicating that secret is a secret-engine, but that is _not at all clear_ until after you run into this problem. I think there is a lack of consistency in the documentation. "secret" should be prefixed by a ":" to match the terminology used for ":path", and "secret" should be renamed to ":secret-engine" to clearly indicate what it actually is.

**To Reproduce**
1. Attempt to use KV v2 API documentation
2. For example, using the documentation, attempt to make an API call to /v1/secret/metadata/:path/to/secret/
3. It will fail with the unhelpful error: `{"errors":["no handler for route \"secret/metadata/:path/to/secret/\". route entry not found."]}`

**Expected behavior**
You should get back a response from the API, because you followed the documentation.
1. For example, the response would look like `{"request_id":"96013718-2244-8c8a-fa5d-47dfc209e56e","lease_id":"","renewable":false,"lease_duration":0,"data":{"keys":["orgs/"]},"wrap_info":null,"warnings":null,"auth":null}`

**Additional context**
I am sure this is obvious for anyone that is a longtime user of the Vault API, but as a new user of the API this is entirely confusing. The documentation should be clear what _is_ and _is not_ a variable, for each API listed, and the examples should reflect that.

**Comment by VioletHynes** [comment]
Hi there!

We do point this out as a note at the top of the page you linked:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/1594272/225930130-356380bc-9cfb-4bb9-8b1e-b00e04fb8a21.png">

I agree that the documentation could be a bit clearer though. I'll work to improve it to show that the secret mount path as well as the secret are parameters.

**Comment by VioletHynes** [comment]
Thanks for the report! I've updated the docs to call this parameter out explicitly.

Merged PR: https://github.com/hashicorp/vault/pull/19607
