### ISSUE TITLE
Add support for multiple github organisations in auth backend

### ISSUE THREAD

**Issue by schulzh** [hashicorp/vault#1963]
In our github enterprise installation, we have multiple "organisations" which need to access the vault, which currently does not seem possible. It would be nice to have that supported.
This must also include that the mapping contains the organisation, to uniquely identify teams.

Example:
```
vault write auth/github/config base_url=<some url> organization=OrgA,OrgB
vault write auth/github/map/teams/OrgA/teamA value=scopeA
vault write auth/github/map/teams/OrgB/teamA value=scopeB
vault write auth/github/map/teams/OrgB/teamB value=scopeC
```

**Comment by vishalnayak** [comment]
This can still be done by mounting github secret backends at multiple paths, and configuring each mount for different organizations.
