### ISSUE TITLE
can not create namespace

### ISSUE THREAD

**Issue by 13567436138** [hashicorp/vault#19668]
**Describe the bug**
```
[root@node01 policy]# vault namespace create ns1
Error creating namespace: Error making API request.

URL: PUT http://10.69.215.160:8200/v1/sys/namespaces/ns1
Code: 404. Errors:

* 1 error occurred:
        * unsupported path


```
**To Reproduce**
1. Run `vault write ...`
2. Run `vault login....`
3. See error

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* [root@node01 policy]# vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.12.1
Build Date      2022-10-27T12:32:05Z
Storage Type    file
Cluster Name    vault-cluster-4c3b22c9
Cluster ID      0e2e4ce6-98e5-ef4f-3cad-768289e8005d
HA Enabled      false
* Vault CLI Version (retrieve with `vault version`):
* [root@node01 policy]# vault version
Vault v1.12.2 (415e1fe3118eebd5df6cb60d13defdc01aa17b03), built 2022-11-23T12:53:46Z
* Server Operating System/Architecture:
cetnos 8
Vault server configuration file(s):
```
/ $ cat vault/config/extraconfig-from-values.hcl 
disable_mlock = true
ui = true

listener "tcp" {
  tls_disable = 1
  address = "[::]:8200"
  cluster_address = "[::]:8201"
  # Enable unauthenticated metrics access (necessary for Prometheus Operator)
  #telemetry {
  #  unauthenticated_metrics_access = "true"
  #}
}
storage "file" {
  path = "/vault/data"
}

# Example configuration for using auto-unseal, using Google Cloud KMS. The
# GKMS keys must already exist, and the cluster must have a service account
# that is authorized to access GCP KMS.
#seal "gcpckms" {
#   project     = "vault-helm-dev"
#   region      = "global"
#   key_ring    = "vault-helm-unseal-kr"
#   crypto_key  = "vault-helm-unseal-key"
#}

# Example configuration for enabling Prometheus metrics in your config.
#telemetry {
#  prometheus_retention_time = "30s",
#  disable_hostname = true
#}/ $ 
```
```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by stevendpclark** [comment]
Hi @13567436138, 

I believe you might be running a Vault OSS server, so the response you are receiving is expected. Creating namespaces in Vault requires the Enterprise edition of Vault. 

If I have incorrectly diagnosed the issue you are reporting please feel free to re-open this issue!
