### ISSUE TITLE
root user can not access some path

### ISSUE THREAD

**Issue by 13567436138** [hashicorp/vault#19693]
**Describe the bug**
```
[root@node01 ~]# vault kv put -mount=secret creds passcode=my-long-passcode
Error making API request.

URL: GET http://10.69.215.160:8200/v1/sys/internal/ui/mounts/secret
Code: 403. Errors:

* preflight capability check returned 403, please ensure client's policies grant access to path "secret/"
```
**To Reproduce**
1. Run `vault write ...`
2. Run `vault login....`
3. See error

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by 13567436138** [comment]
how to mount

**Comment by cipherboy** [comment]
We reserve GitHub issues for bug reports and feature requests, which this doesn't appear to be. As such, I'm going to close this and suggest that you ask about this on the Vault discussion forums at https://discuss.hashicorp.com/c/vault/30.

For more information on using Vault, check out our tutorials: https://developer.hashicorp.com/vault/tutorials
