### ISSUE TITLE
REST API v1 policy PUT/ GET (failed to read policy: decryption failed: cipher: message authentication failed)

### ISSUE THREAD

**Issue by samahub** [hashicorp/vault#1970]
Hi,

First of all:
Vault version = 0.6.1
Vault interface = REST API v1

We need to manage "secret" access policies.
As documented up here, our code (PERL) interacts with Vault's REST interface.

Our goal here is to create/modify/retrieve a policy.
We already implemented that using console and HCL, all fine.
However when we use REST API and so JSON we create a policy, the only JSON format that didn't error out was:

qq{{"rules": "{\"name\":\"hisSecret\",\"path\": { \"secret/theirSecrets/hisSecret\": {\"capabilities\": [\"create\",\"update\", \"read\", \"list\"]}, \"auth/token/lookup-self\": {\"capabilities\": [\"read\"]}}}"}}

That is including policy definition (what's typically included in HCL file) as a string value for "rules".
And so escaping back-slashes for deserialization to keep them for double-quotes escaping.
Any other format turned out as JSON parsing error.

We didn't really find an example about policies, not even API documentation:
[](https://www.vaultproject.io/docs/http/sys-policy.html)

The closer to an example was this other issue replies but none of them worked just like that:
[](https://github.com/hashicorp/vault/issues/582)

As said before that format worked (didn't errored out and we could find the new policy using console) however we cannot retrieve it vía REST API.
That is a GET against URL "https://mytestserver.net:8200/v1/sys/policy/hisSecret" returns an error JSON object like:

{"errors":["failed to read policy: decryption failed: cipher: message authentication failed"]}

Please let me know if you need any other info.

Thanks

**Comment by jefferai** [comment]
Hi @samahub ,

I'm not quite following all of that, but could use more information -- what is your Vault configuration (config file, the info printed at startup). Any error in the console logs? What happens when you use `curl` to interact rather than your Perl module?
