### ISSUE TITLE
Self-signed cert issue.

### ISSUE THREAD

**Issue by Losiara** [hashicorp/vault#1971]
Win 7 x64, latest tsable vault.
Try to setup ssl/tls with self-signed cert.
in cert.cnf added
subjectAltName         = IP:127.0.0.1
After all, started server
and than
`vault status`
Got output:
Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: x509: certificate is valid for 127.0.0.1, not 127.0.0.1

**Comment by jefferai** [comment]
Can you paste your certificate PEM? Thanks.

**Comment by Losiara** [comment]
.cer
-----BEGIN CERTIFICATE-----
MIIETTCCAzWgAwIBAgIJAJMvQNNrOF6WMA0GCSqGSIb3DQEBBQUAMHAxCzAJBgNV
BAYTAlJVMRAwDgYDVQQKDAdkZWZhdWx0MRAwDgYDVQQLDAdkZWZhdWx0MQwwCgYD
VQQLDANQS0kxDTALBgNVBAsMBEFCQ0QxIDAeBgkqhkiG9w0BCQEWEW15RW1haWxA
ZW1haWwuY29tMB4XDTE2MTAwNTE2MTc1NVoXDTE5MDcwMjE2MTc1NVowcDELMAkG
A1UEBhMCUlUxEDAOBgNVBAoMB2RlZmF1bHQxEDAOBgNVBAsMB2RlZmF1bHQxDDAK
BgNVBAsMA1BLSTENMAsGA1UECwwEQUJDRDEgMB4GCSqGSIb3DQEJARYRbXlFbWFp
bEBlbWFpbC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC247kR
6cc5qYm8pkH4jUJeQgNHs07DLg5I561/Ars1F/7Wrotofj7aIOWjPHQTclf8aHI0
AiUOxDODFm99nHYmJkIJHptG35XDXjqfNHue1HQhkWLLBgI7vJ3XVMJha8ghR/pB
2h+C2gBpEGq77Rdkw8tsgiVl8JJh4VmLK450yyhow3aAo3tauakTZFLcPePZezFK
H4H79cpEXjMhw0SdLnnbUp0pC0XruCTe0lskD+FKX+ZppZx/LER7Xpb8TawJanfV
Dgks/pFhWoLP4JDxx8da262BGdOgKd0eZ35QBt7/1POCYiElQZr/j3tp4TKVvw3Q
bA+UJV6Xo6Vwu8jzAgMBAAGjgekwgeYwHQYDVR0OBBYEFFtTQgx5YmbdFCyFoERX
KQc9mAWxMIGiBgNVHSMEgZowgZeAFFtTQgx5YmbdFCyFoERXKQc9mAWxoXSkcjBw
MQswCQYDVQQGEwJSVTEQMA4GA1UECgwHZGVmYXVsdDEQMA4GA1UECwwHZGVmYXVs
dDEMMAoGA1UECwwDUEtJMQ0wCwYDVQQLDARBQkNEMSAwHgYJKoZIhvcNAQkBFhFt
eUVtYWlsQGVtYWlsLmNvbYIJAJMvQNNrOF6WMA8GA1UdEQQIMAaHBH8AAAEwDwYD
VR0SBAgwBocEfwAAATANBgkqhkiG9w0BAQUFAAOCAQEAonXMHth4krF0FQHYieqC
oX/iQqDtZJ1XbVPA+wFgdTzgiMN2KuASkT4bqu7mqZuLFZ5lAOBcUDiDh0zc1vKM
yeKLyo92KvtasrGnDfqkjBmDmIUEM4w8Ks9Ye7ODFQe2e4FnWkqMYiwLe3q2ey7R
vHzcqjCWmoxjvZ18PTDfnold1jK7x7maAc4ijUFgWwn2H6VqhcKAEeRUkUxL3hKS
Hw+PtYm9QkS31P/KXmY7kJ0a3huiu44zzXgP+4RmWNVvosYUrjOvJSyKOzmIT81k
PvTTJux6TT0OK34axPmr/HwRpGBwMIPu8hDomi6iMP9MUyqx0yqd5MtYlLjtSVyk
gg==
-----END CERTIFICATE-----

**Comment by jefferai** [comment]
Hi @Losiara ,

I don't know offhand what the issue might be, however in examining your certificate there are a few things that strike me about it:

1. It has no common name -- only a subject alternate name. It's possible that this is confusing the client. You should try adding 127.0.0.1 -- or maybe `localhost` -- as the CN of the certificate as well.
2. It's using SHA1 for a signature -- I don't think the client will reject this but many clients at this point will, so you should have your self-signed cert be using SHA256 or better.

**Comment by Losiara** [comment]
Changing common name was helpful. Thank you!

**Comment by jefferai** [comment]
Great! Non-useful error message from the client, but I guess it was in such a bad state that it just didn't know what to do.

I'm actually surprised openssl generated a cert for you without a common name, as that's generally one of the *most* important values in the cert, but, maybe I shouldn't be :-)
