### ISSUE TITLE
unknown or unsupported field token_helper found in configuration

### ISSUE THREAD

**Issue by Tony-Sol** [hashicorp/vault#19729]
**Describe the bug**
On startup vault server with `token_helper` in hcl configuration file, receive message
```
2023-03-23T23:37:33.357+0300 [WARN]  unknown or unsupported field token_helper found in configuration at <full path to config file>/.config.hcl:23:1
```

**To Reproduce**
1. Save [my config file](https://github.com/Tony-Sol/.config/blob/master/vault/config.hcl) like
```
envsubs < config.hcl > .config.hcl
```
2. Save ["tokenator" example](https://github.com/Tony-Sol/.config/blob/master/vault/tokenator) at `token_helper` to path from `.config.hcl`
3. Run `vault server -config=.config.hcl -dev` or `VAULT_CONFIG_PATH=.config.hcl vault server -dev`

**Expected behavior**
`token_helper` in config.hcl is supported and work as described

**Environment:**
* Vault Server Version (retrieve with `vault status`): -
* Vault CLI Version (retrieve with `vault version`): 1.13.0
* Server Operating System/Architecture: macos arm64

Vault server configuration file(s):

```hcl
telemetry = {}

disable_mlock = true

ui = true

api_addr = "http://127.0.0.1:8200"

listener "tcp" {
	address     = "[::]:8200"
	tls_disable = 1
}

listener "unix" {
	address = "/Users/tony/.local/run/vault.sock"
	socket_mode = "644"
}

storage "file" {
	path = "/Users/tony/.local/share/vault/storage"
}

token_helper = "/Users/tony/.config/vault/tokenator"

plugin_directory = "/Users/tony/.local/share/vault/plugins"```
```

**Additional context**
[My LaunchAgent config file for running vault](https://github.com/Tony-Sol/.config/blob/master/LaunchAgents/homebrew.mxcl.vault.plist)

**Comment by Tony-Sol** [comment]
Doesn’t `~/.vault` mean a default config file, which can be overwritten by VAULT_CONFIG_PATH?

**Comment by maxb** [comment]
> Doesn’t `~/.vault` mean a default config file, which can be overwritten by VAULT_CONFIG_PATH?

That is the Vault **client** config file, and is completely separate to the Vault **server** config file - a totally different set of options, which should be in entirely separate files.

The file passed to `vault server -config=...` is a Vault **server** config file.

In your initial post you said:

> * Run `vault server -config=.config.hcl -dev` or `VAULT_CONFIG_PATH=.config.hcl vault server -dev`

These two commands are **NOT** equivalent. The first is specifying a server config file. The second is specifying a client config file, which is entirely redundant when executing `vault server`.

**Comment by hghaf099** [comment]
I am going to close the issue as the issue seems to be resolved.
