### ISSUE TITLE
website missing "Response Wrapping" links in sidebar

### ISSUE THREAD

**Issue by neomantra** [hashicorp/vault#1976]
This URL has "Response Wrapping" links in the sidebar:
https://www.vaultproject.io/docs/http/libraries.html

But this URL does not:
https://www.vaultproject.io/docs/http/index.html

**Comment by vishalnayak** [comment]
I am able to see them at both the links. Can you check if the index page is coming from browser's cache? Probably a `Shift + F5` should do it.

**Comment by neomantra** [comment]
Indeed that fixes it -- I was even looking at the ERB files confused how that could even happen...  apologies for the noise!

**Comment by vishalnayak** [comment]
No problem!
