### ISSUE TITLE
error initializing "gsuite" provider_config

### ISSUE THREAD

**Issue by eliteaz** [hashicorp/vault#19766]
**Describe the bug**
Try to enable **gsuit** backend for vault.

**To Reproduce**
```
Vault v1.13.0 (a4cf0dc4437de35fce4860857b64569d092a9b5a), built 2023-03-01T14:58:13Z
```
```
vault write auth/oidc/config -<<EOF
{
    "oidc_discovery_url": "https://accounts.google.com",
    "oidc_client_id": "{{ client_id }}",
    "oidc_client_secret": "{{ client_secret }}",
    "default_role": "default_role",
    "provider_config": {
        "provider": "gsuite",
        "gsuite_service_account": "/tmp/service_account.json",
        "gsuite_admin_impersonate": "admin@example.org"
        "fetch_user_info": true,
        "groups_recurse_max_depth": 5
    }
}
EOF
```
**Error**
```
Error writing data to auth/oidc/config: Error making API request.

URL: PUT https://vault.example.org/v1/auth/oidc/config
Code: 400. Errors:

* invalid provider_config: error initializing "gsuite" provider_config: error parsing service account JSON: invalid character '/' looking for beginning of value

```
Same with **relative** path also 
```
{
...
        "gsuite_service_account": "./service_account.json",
...
}

```
**Error**
```
Error writing data to auth/oidc/config: Error making API request.

URL: PUT https://vault.example.org/v1/auth/oidc/config
Code: 400. Errors:

* invalid provider_config: error initializing "gsuite" provider_config: error parsing service account JSON: invalid character '.' looking for beginning of value
```
It is valid **JSON** obtained from **G Service account**
vault is running on the same host where commands initialized
.json file is readable by all
```
[root@vault tmp]# ls -la /tmp/service_account.json 
-rw-r--r-- 1 vault root 2340 Mar 27 08:26 /tmp/service_account.json
```

What the trouble could be to  read .json?

**Comment by maxb** [comment]
> .json file is readable by all

Please don't store important credentials in a file that is world readable!



> "gsuite_service_account": "/tmp/service_account.json",

For this to work, the file would need to exist **on the Vault server**, not on the workstation where the Vault CLI command is being executed. Since it doesn't, Vault is trying to parse the file name as if it was some JSON text.

**Comment by eliteaz** [comment]
I have moved from` "/tmp/service_account.json"` to `"/etc/vault.d/service_account.json" `
and it works correctly (this info not written in documentation)
all steps above was initiated from host where  **Vault server** is running.

**Comment by maxb** [comment]
If you run Vault as a systemd service, it's probably providing an individual isolated `/tmp/` directory to the service.

**Comment by hsimon-hashicorp** [comment]
> If you run Vault as a systemd service, it's probably providing an individual isolated `/tmp/` directory to the service.

This is my guess as well. See the [systemd tmp directory documentation](https://systemd.io/TEMPORARY_DIRECTORIES/) for more.

Please let me know if this helps answer your question. Thanks!

**Comment by eliteaz** [comment]
thanks @hsimon-hashicorp - it's a good point due to systemd tmp isolate.
But I run vault binary from cli being root 
it doesn't matter what location use `/tmp` or `other` anyway error appears
only `/etc/vault.d/` is valid

**Comment by eliteaz** [comment]
seems clear for this.
I was calling vault using `root` env on the same host that systemd vault runs on `vault` env
thanks for Your answers
