### ISSUE TITLE
Vault can't to register in consul cluster as a service

### ISSUE THREAD

**Issue by melmus** [hashicorp/vault#19818]
**Describe the bug**
Hi!
I sets vault HA cluster. 
For storage i use consul cluster.
I have a problem: Vault can't to registry in consul cluster as a service

**To Reproduce**
1. Run `vault`
2. See error: 
```bash
[ERROR] service_registration.consul: error running service registration: failed to find a host:port in redirect address "": missing port in address 
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.12.4
* Consul Server Version (retrieve with `vault version`): 1.14.2
* Server Operating System/Architecture: Ubuntu 20, Vault and Consul  use in Docker

Vault server configuration file(s):

```hcl
ui = true
disable_mlock = true
api_addr = "localhost:8200"
cluster_name = "my_cluster"
log_level = "trace"
 
 
storage "consul" {
address = "localhost:8500"
path = "vault/"
token = "token_for_my_consul"
}
 
service_registration "consul" {
address = "localhost:8500"
service_address = "localhost:8200"
}
 
listener "tcp" {
address = "0.0.0.0:8200"
cluster_address = "0.0.0.0:8201
tls_disable = "true"
}


```

**Additional context**
```
/ # vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.12.4
Build Date      2023-02-28T21:39:06Z
Storage Type    consul
Cluster Name    my_cluster
Cluster ID      1c4fh19va2-0d82-8yeb-1bf3-y5wep5630p19
HA Enabled      true
HA Cluster      https:8200
HA Mode         active
Active Since    2023-03-29T09:56:28.390154105Z
```

**Comment by linuxoid69** [comment]
I have this problem too

**Comment by melmus** [comment]
@maxb Tnx, i agree with you, all work. But if i install standalone vault, i don't write scheme (http) in ```api_addr```,
```
api_addr="localhost:8200"
```

If I install HA, i write
```
api_addr="http://localhost:8200"
```
But this case didn't describe  in documentation.

**Comment by hsimon-hashicorp** [comment]
@yhyakuna Can we get this addressed in the documentation for clarity? Thanks!

**Comment by yhyakuna** [comment]
The [doc has been updated](https://developer.hashicorp.com/vault/docs/configuration) with a better example. I hope this helps.
