### ISSUE TITLE
Issue using list with userpass auth

### ISSUE THREAD

**Issue by DanHoerst** [hashicorp/vault#1984]
Hi. I'm running `Vault v0.5.2`. I'm attempting to list the users that I have in my userpass auth backend. When I do so, I get the following:

    vault list /auth/userpass/users
    Error reading auth/userpass/users/: Error making API request.

    URL: GET https://vault.mydomain.com/v1/auth/userpass/users/?list=true
    Code: 500. Errors:

    * unsupported path

However it works when reading a specific user:

    vault read /auth/userpass/users/xyz
    Key             Value
    policies        xyz_policy

It also works when listing normal secrets.

Any help would be appreciated. Thanks.

**Comment by jefferai** [comment]
This isn't supported in Vault < 0.6.
