### ISSUE TITLE
Using "allowed_parameters" on Vault policies to restrict which policies can be set on "token_policies" and/or "policies" on roles receives unexpected permission denied

### ISSUE THREAD

**Issue by bmcdonald05** [hashicorp/vault#19849]
**Describe the bug**
Creating a Vault policy that aims to restrict what "token_policies" and/or "policies" can be set on different auth method roles receives an unexpected permission denied. The permission denied error appears to be limited to when *multiple* Vault policies are specified when creating a role. 
  - Creating a role with only one (1) "token_policies" value set is successful
  - Creating a role with multiple "token_policies" values receives permission denied
  - Issue is present on *at least* AppRole and K8s auth method

**To Reproduce**
1. Create Vault policy `vault policy write auth-restricted auth-restricted.hcl` restricting permissions via "allowed_parameters"; policy below:
    ```
    ### Auth Restricted Policy ###
    # allow creating auth methods with given requirements
    path "sys/auth/*" {
      capabilities = ["create", "update", "sudo"]
      allowed_parameters = {
        "*" = []
        "type" = ["kubernetes", "approle"]
      }
    }
    # allow listing all auth method roles
    path "auth/+/role" {
      capabilities = ["list"]
    }
    # allow reading and deleting all existing auth method roles
    path "auth/+/role/*" {
      capabilities = ["read", "delete"]
    }
    # allow creating and deleting roles on all auth methods
    path "auth/+/role/*" {
      capabilities = ["create", "update"]
      allowed_parameters = {
        "*" = []
        "token_policies" = ["test1", "default"]
      }
    }
    ```

2. Create Vault policy `vault policy write test1 test1.hcl` for testing, policy below:
    ```
    # allow listing auth methods
    path "sys/auth" {
      capabilities = ["list", "read"]
    }
    ```

3. Create a token with the auth-restricted policy:
    ```
    vault token create -policy=auth-restricted -ttl=24h
    ```

4. Verify policy attached to token with `vault token lookup`
    ```
    Key                 Value
    ---                 -----
    accessor            EXIZB025A2CnROLkb9JWii4a
    creation_time       1680179729
    creation_ttl        24h
    display_name        token
    entity_id           05085de0-eb1c-89c3-7a20-c2245f3771b7
    expire_time         2023-03-31T08:35:29.760642-04:00
    explicit_max_ttl    0s
    id                  hvs.<REMOVED>
    issue_time          2023-03-30T08:35:29.76065-04:00
    meta                <nil>
    num_uses            0
    orphan              false
    path                auth/token/create
    policies            [auth-restricted default]
    renewable           true
    ttl                 23h59m49s
    type                service
    ```
    
***Run the rest of vault commands using the Vault token with restricted permissions***

5. Enabling an auth method works as expected:
    ```
    vault auth enable -path=test1 approle
    ```
6. Creating a role with only one (1) policy it works as expected:
    ```
    vault write auth/test1/role/test1 token_policies=test1

    Success! Data written to: auth/test1/role/test1
    ```
    
7. Creating a role with multiple policies will fail with permission denied:
    ```
    vault write auth/test1/role/test1 token_policies=test1 token_policies=default

    Error writing data to auth/test1/role/test1: Error making API request.

    URL: PUT https://127.0.0.1:8200/v1/auth/test1/role/test1
    Code: 403. Errors:

    * 1 error occurred:
      * permission denied
    ```

**Expected behavior**
Creating an auth role with any/all polices listed in "token_policies" under "allowed_parameters" should be successful and not receive a permission denied error.

**Environment:**
* Vault Server Version: 1.13.0+ent
* Vault CLI Version: 1.13.1
* Server Operating System/Architecture: MacOS Ventura 13.1 (also confirmed similar behavior on RHEL 8.6)

Vault server configuration file(s):
  This has been confirmed on multiple Vault server clusters on different OS platforms; not sure if relevant. 

**Additional context**

Requests also fail if written differently:
```
vault write auth/test1/role/test1 token_policies=test1,default

Error writing data to auth/test1/role/test1: Error making API request.

URL: PUT https://127.0.0.1:8200/v1/auth/test1/role/test1
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```
```
vault write auth/test1/role/test1 token_policies="test1,default"

Error writing data to auth/test1/role/test1: Error making API request.

URL: PUT https://127.0.0.1:8200/v1/auth/test1/role/test1
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

Retrieving curl/API equivalent requests and running via curl also fail:
```
vault write -output-curl-string auth/test1/role/test1 token_policies=test1 token_policies=default
```
```
vault write -output-curl-string auth/test1/role/test1 token_policies=test1,default
```

```
curl -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"token_policies":["test1","default"]}' https://127.0.0.1:8200/v1/auth/test1/role/test1

{"errors":["1 error occurred:\n\t* permission denied\n\n"]}
```

```
curl -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"token_policies":"test1,default"}' https://127.0.0.1:8200/v1/auth/test1/role/test1

{"errors":["1 error occurred:\n\t* permission denied\n\n"]}
```

Verified same behavior on K8s auth method:
```
vault write auth/test2/role/test2 \
    bound_service_account_names=myapp \
    bound_service_account_namespaces=default \
    token_policies=test1
    
Success! Data written to: auth/test2/role/test2
```
```
vault write auth/test2/role/test2 \
    bound_service_account_names=myapp \
    bound_service_account_namespaces=default \
    token_policies=test1,default

Error writing data to auth/test2/role/test2: Error making API request.

URL: PUT https://127.0.0.1:8200/v1/auth/test2/role/test2
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

We initially found this issue when using the Vault Terraform provider and thought it may be specific to that and/or the way API requests were sent to Vault, but we confirmed the same behavior when doing everything directly via CLI.

**Comment by maxb** [comment]
As you have observed, the `allowed_parameters` functionality is systematically unable to support useful restrictions on multi-value parameters.

This is because it performs a basic "Does the value match?" test at an early stage of request processing, before Vault has got anywhere near figuring out what underlying code is being called, and what type conversions need to be applied to the parameter.

As a result, none of the behaviour of allowing multi-value parameters to receive either a JSON array, or a comma-separated string has occurred yet, and the matching against allowed values is performed against the whole value as supplied in the JSON request.

An example of a policy that would allow some of your sample requests is:
```
path "auth/+/role/*" {
  capabilities = ["create", "update"]
  allowed_parameters = {
    "*" = []
    "token_policies" = [
      ["test1", "default"],
      "test1,default",
    ]
  }
}
```

This is clearly not a useful policy for real use-cases, but illustrates what would be needed to get these requests through the `allowed_parameters` functionality.

**Comment by bmcdonald05** [comment]
Thanks for that information. Now that I know that, it looks like using "denied_parameters" won't solve the use case either, because more policies could be added to the request to bypass the simple check. I tested and verified the behavior.

For example: 
denied parameters (simplified):
```
  denied_parameters = {
    "token_policies" = [
      "vault-admins"
    ]
  }
```

This command gets a permission denied, as expected:
```
vault write auth/test1/role/test1 token_policies=vault-admins
```

This command gets around the check and complete succesfully:
```
vault write auth/test1/role/test1 token_policies=vault-admins token_policies=default
```


So I guess my only remaining question would be the suggested solution to the use case of "A Vault policy that will let users create auth roles, but limit/restrict them to using only certain policies"? I have not attempted it yet, but would Sentinel be the only way to accomplish this?


For anyone curious on a workaround; you need to include every potential combination, including the the order of policies to prevent the permission denied error. Example "allowed_parameters" stanza to cover everything I have thought of and tested so far:
```
  allowed_parameters = {
    "*" = []
    "token_policies" = [
      ["test1", "default"],
      ["default", "test1"],
      ["test1"],
      ["default"],
      "test1,default",
      "default,test1",
      "test1",
      "default",
    ]
  }
```

**Comment by maxb** [comment]
There's actually another security trap for the unwary in the above, too... `token_policies` is the modern name for the setting, but some auth methods still accept the legacy parameter `policies` as an alias. Therefore with the policy above, a user could still do
```
vault write auth/test1/role/test1 policies=vault-admins
```
and gain access to the `vault-admins` policy.

And yet another trap if you use `denied_parameters` or Sentinel: the comma separated strings permit arbitrary unicode whitespace around the commas, which can be used to evade a static blocklist.

In Vault as it is today, I'm not aware of any acceptably neat way to handle delegated assignment of policies, short of writing your own ultimately trusted configuration service, which can implement custom restrictions prior to forwarding configuration to Vault.

**Comment by bmcdonald05** [comment]
Thanks for the input everyone, I guess we can close this out for now.

**Comment by tsipinakis** [comment]
Just adding a comment here to say this is still a problem for us as well. We want to delegate group creation but limit the policies that are allowed to be used.

**Comment by kejiangzoox** [comment]
in Terraform, `token_policies               = [["${local.policy_name}"], "${local.policy_name}" ]` returns 
```
│ Error: Inconsistent conditional result types
│ 
│   on ../../../modules/vault-terraform-auth/main.tf line 118, in data "vault_policy_document" "policy_document":
│  118:         for_each = contains(keys(rule.value), "allowed_parameter") ? rule.value.allowed_parameter : {}
│     ├────────────────
│     │ rule.value is object with 4 attributes
│     │ rule.value.allowed_parameter is object with 42 attributes
│ 
│ The true and false result expressions must have consistent types. The 'true' value includes object attribute "accessor", which is absent in the 'false' value.
```
....

Manually modifying the policy works
```
    "token_policies" = [
      ["policy_name"],
     "policy_name"
    ]
```

Feels like this is an oversight

**Comment by kejiangzoox** [comment]
`token_policies` from what it seems, requires a list of lists. `vault_policy_document` value does not support list of lists. This seems like an oversight.

**Comment by kejiangzoox** [comment]
A work around is to manually modify the created list but this creates a terraform drift
