### ISSUE TITLE
Key initialization UI info - Docker instance

### ISSUE THREAD

**Issue by robbjass** [hashicorp/vault#19887]
**Describe the bug**
There is lack of UI info about number of keys needed to unseal Vault after first initialization.
![image](https://user-images.githubusercontent.com/54838928/229085274-c418e3df-f286-47de-b46b-af160da0f323.png)

**To Reproduce**
1. Started test Vault container with `docker run --cap-add=IPC_LOCK -e 'VAULT_LOCAL_CONFIG={"storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}' -p 8200:8200 hashicorp/vault server`
2. Went to localhost:8200
3. Typed to create 3 keys with minimum 2 of them necessary to unlock Vault.
4. At the end information looks like on the attached ss.

**Expected behavior**
Information about how many keys are needed in the description.

**Environment:**
Vault v1.13.1 (4472e4a3fbcc984b7e3dc48f5a8283f3efe6f282), built 2023-03-23T12:51:35Z
* Server Operating System/Architecture:
Kernel Version: 5.15.0-67-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:02 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Vault server configuration file(s):
Nothing's changed from standard config for first test docker run.

**Comment by hellobontempo** [comment]
Thanks for reporting @robbjass - I appreciate the quick setup steps.

I was unable to reproduce the issue as the key number data appeared both in Chrome and Firefox 🤔. Were there any console errors or information in the Vault logs? Additionally, a screenshot of the HTML element may also provide some insight if you're able to provide one.
![Screenshot 2023-04-04 at 12 30 00 PM](https://user-images.githubusercontent.com/68122737/229885147-80538a1f-474d-40fc-9fb2-e0c4d5cbeaf8.png)

![Screenshot 2023-04-04 at 12 52 29 PM](https://user-images.githubusercontent.com/68122737/229891659-d13ed82a-3296-4f1d-82ac-232f6641b229.png)

**Comment by robbjass** [comment]
@hellobontempo Hey, thanks for checking this out. Weird, but now on my site, also everything works and I'm also unable to reproduce. So, case closed and sorry for the false alarm.
