### ISSUE TITLE
Zookeeper backend timeout and no re-auth

### ISSUE THREAD

**Issue by horsehay** [hashicorp/vault#1989]
I'm using zookeeper as my HA backend in production and have run into the following issue:

When zookeeper restarts or expires the vault client session, vault doesn't try to reauth.

```2016-10-11 00:20:36.295243 I | Authentication failed: zk: session has been expired by the server
2016/10/11 00:20:36.295456 [WRN] core: leadership lost, stopping active operation
2016-10-11 00:20:36.296029 I | Connected to xxx.xxx.xxx.xxx:2181
2016/10/11 00:20:36.298505 [INF] core: pre-seal teardown starting
2016/10/11 00:20:36.298674 [INF] core/stopClusterListener: stopping listeners
2016/10/11 00:20:36.298898 [INF] core/startClusterListener: shutting down listeners
2016-10-11 00:20:36.358971 I | Authenticated: id=1234567890, timeout=4000
2016/10/11 00:20:36.459922 [INF] core/startClusterListener: listeners successfully shut down
2016/10/11 00:20:36.459974 [INF] core/stopClusterListener: success
2016/10/11 00:20:36.460096 [INF] rollback: stopping rollback manager
2016/10/11 00:20:36.460749 [INF] core: pre-seal teardown complete
2016/10/11 00:20:36.586379 [ERR] core: failed to acquire lock error=zk: not authenticated```

You can imagine this is pretty problematic for HA.

**Comment by jefferai** [comment]
Is this 0.6.2? I seem to remember something similar to this being fixed in it.

**Comment by horsehay** [comment]
This is 0.6.1. Reviewing 0.6.2 notes now, but not seeing anything about it.

**Comment by horsehay** [comment]
Also, all of the other nodes had already timed out since they weren't getting any traffic and so I ended up with a bunch of Vault nodes that were all reporting they were in standby, but couldn't connect to Zookeeper.

**Comment by horsehay** [comment]
Just tested 0.6.2 in my sandbox and it seems that you are correct @jefferai . Thanks again.

**Comment by jefferai** [comment]
For completeness, this wasn't in the notes because it was solved via a normal upstream library sync -- see https://github.com/hashicorp/vault/issues/1933
