### ISSUE TITLE
Feature: Active/Read States

### ISSUE THREAD

**Issue by jcrowthe** [hashicorp/vault#1992]
This feature request relates to #390, but addresses the issue from an availability standpoint instead of a fail-tolerance standpoint.

Feature: Allow Vault's "standby" cluster nodes to respond to read-only requests instead of remain as dormant proxy nodes.

Reasoning: Vault is currently only as "highly available" as one machine can handle the requests (which is slated to be in the 10s of thousands of requests p/s for a recommended setup). However, in larger deployments, say at 100,000 requests per second, this one machine will fail to keep up. Even with Vault in a high availability cluster setup, the other nodes are effectively useless until the Active node dies -- and even then, the load is merely transferred to another node. This means these extra nodes make the setup highly fail-tolerant and highly available as a _cluster_, but the cluster is still left  seriously lacking in the high availability of the _data_. This feature request is to exchange this dormant state of cluster nodes for a read-only state, thus allowing the data to be highly available. The _modification_ of the data will not be highly available until a true Active/Active setup is provided. Until then, this is a big step forward. 

Implementation: Effectively, any "read" of Vault's data can be serviced by any node in a cluster. Any "write" or "update" request will continue to be redirected to the Active node.

**Comment by jefferai** [comment]
Leader/Follower cross-DC replication support is already being worked on; it will enable horizontal scaling similar to this request but with more robustness than a pure in-cluster solution.
