### ISSUE TITLE
[feature] Token lease based on policy

### ISSUE THREAD

**Issue by dropje86** [hashicorp/vault#1995]
I have searched but haven't found anything related in the issue list so far. We have a LDAP auth backend setup for some very specific requirements. I'm able to set specific `default_lease_ttl` and `max_lease_ttl` to limit the lifetime of a token provisioned through the LDAP backend but this would mean *all* tokens created through the LDAP auth endpoint will have this set.

Is it an option to extend policies with these options? How you'd deal with "conflicts" is that you would honor the max_lease_ttl of the most restrictive policy (lowest ttl set). What do you think? It would give the user the ability to hand out tokens on a much more granular base.

**Comment by vishalnayak** [comment]
Hi @dropje86, currently the `default_lease_ttl` and `max_lease_ttl` can be set in the config file (which will be the 'system' default). Then mount-tune command can be used to further set different values for each backend mount. The `config` endpoints on the backends provide even more granularity to the lifetime of tokens. All these combined together already makes reasoning with `ttl`s relatively not straightforward. Not sure if providing more granularity to lifetimes through policies is worth doing and it is not on our roadmap as well. Not ideal, but mounting the backends on different paths with different `ttl` configurations is the way to go, for now.

**Comment by jbarnett1981** [comment]
@dropje86 I'm actually trying to figure out right now how to specify the lease duration for tokens created during LDAP auth. How exactly are you doing this?

**Comment by jefferai** [comment]
It's documented extensively. See https://www.vaultproject.io/docs/concepts/tokens.html

**Comment by jbarnett1981** [comment]
Thanks @jefferai I actually did read through that link extensively before posting but couldn't find the answer I needed. First, it wasn't clear that you couldn't see the auth mounts via CLI using "vault mounts", and then from there it wasn't very clear HOW exactly do modify the ttl for a specific auth backend. It wasn't documented in the ldap specific docs either. I appreciate the docs that are there, but finding this information proved to be challenging...which is what brought me to this issue. I hope that my above comment might help others in the same position looking for answers.
