### ISSUE TITLE
Error taking the snapshot: incomplete snapshot, unable to read SHA256SUMS.sealed file

### ISSUE THREAD

**Issue by mstrdvps** [hashicorp/vault#19964]
getting thie error while taking backup, please help.

**Comment by hsimon-hashicorp** [comment]
Hello there! This is not enough information to go off of. You may wish to visit our [Discuss forum](https://discuss.hashicorp.com/c/vault/30) to ask for help from the community. For example, [there's a similar post here](https://discuss.hashicorp.com/t/error-taking-snapshot/32336). I'll go ahead and close this issue for now, but please feel free to open a new issue if you hit a bug. Please don't forget to fill out the issue template; without more information we may not be able to help. Thanks!
