### ISSUE TITLE
Cannot download the signing key for apt package

### ISSUE THREAD

**Issue by ghost** [hashicorp/vault#19974]
**Describe the bug**
Cannot download the signing key to a new keyring for Ubuntu/Debian systems

**To Reproduce**
1. Run `sudo apt update && sudo apt install gpg`
2. Run `wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg`
3. See error: 
```
--2023-04-04 00:44:46--  https://apt.releases.hashicorp.com/gpg
Resolving apt.releases.hashicorp.com (apt.releases.hashicorp.com)... 18.66.233.126, 18.66.233.82, 18.66.233.53, ...
Connecting to apt.releases.hashicorp.com (apt.releases.hashicorp.com)|18.66.233.126|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-04 00:44:46 ERROR 404: Not Found.

gpg: no valid OpenPGP data found.
```

**Expected behavior**
I should be able to follow official packaging guide at https://www.hashicorp.com/official-packaging-guide

**Environment:**
* WSL Ubuntu 22.04

**Comment by hsimon-hashicorp** [comment]
Can you check again now? This may be resolved already. Thanks!

**Comment by zbcoherent** [comment]
Still 404

**Comment by zbcoherent** [comment]
Any updates on this?

**Comment by cipherboy** [comment]
This command works for me on 22.04; closing as fixed.
