### ISSUE TITLE
[ERROR] core: failed to acquire lock: error="failed to read lock: Unexpected response code: 500"

### ISSUE THREAD

**Issue by qiangliabcd** [hashicorp/vault#20005]
**Describe the bug**

**To Reproduce**
run vault and consul in k8s cluster, there are 3 POD for vault and consul.
on vault slave POD see such log:
2023-03-28T19:56:07.161Z [ERROR] core: failed to acquire lock: error="failed to read lock: Unexpected response code: 500"
2023-03-28T11:12:37.885Z [ERROR] core: failed to acquire lock: error="failed to read lock: Unexpected response code: 500 (rpc error making call: i/o deadline reached)"

on slave consul-client ,see such log:
2023-03-22T00:14:26.839Z [ERROR] agent.client: RPC failed to server: method=KVS.Get server=172.30.59.57:8300 error="rpc error making call: i/o deadline reached"
2023-03-22T00:14:26.839Z [ERROR] agent.http: Request error: method=GET url=/v1/kv/vault/core/lock?index=25705999&wait=15000ms from=@ error="rpc error making call: i/o deadline reached"
2023-03-22T00:32:24.990Z [WARN] agent: grpc: addrConn.createTransport failed to connect to {wdc-172.30.59.57:8300 0 consul-0 }. Err :connection error: desc = "transport: Error while dialing dial tcp ->172.30.59.57:8300: operation was canceled". Reconnecting...
2023-03-22T00:34:57.805Z [ERROR] agent.client: RPC failed to server: method=KVS.Get server=172.30.95.248:8300 error="rpc error making call: i/o deadline reached"

the error only happen on vault standby POD, on vault master POD don't have such error info.

**Expected behavior**

the error info let me confuse:
1, why the slave POD report such error info ? 
2, how to hide such error info? 
 

**Environment:**
* Vault Server Version (retrieve with `vault status`):Vault v1.11.2
* consul Version : Consul v1.11.11
* Server Operating System/Architecture: xlinux

Vault server configuration file(s):

```hcl
{
	"vault.json": "{
		  \"backend\": {
		    \"consul\": {
		      \"address\": \"unix:///consul-unix-socket/consul-client.sock\",
		      \"scheme\": \"http\",
		      \"disable_registration\": \"false\"
		    }
		  },
		  \"listener\": {
		    \"tcp\": {
		      \"address\": \"0.0.0.0:8200\",
		      \"tls_cert_file\": \"/certs/tls.crt\",
		      \"tls_key_file\": \"/certs/tls.key\",
		      \"tls_min_version\": \"tls12\",
		      \"tls_cipher_suites\": \"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384\"
		    }
		  }
		}
		"
}
```

**Additional context**

consul conf:

	"client.json": "{
		  \"server\": false,
		  \"datacenter\": \"dal\",
		  \"retry_join\": [
		    \"consul-0.consul.pltfrm.svc.cluster.local\",
		    \"consul-1.consul.pltfrm.svc.cluster.local\",
		    \"consul-2.consul.pltfrm.svc.cluster.local\"
		  ],
		  \"addresses\": {
		    \"http\": \"unix:///consul-unix-socket/consul-client.sock\"
		  },
		  \"unix_sockets\": {
		    \"mode\": \"600\"
		  },
		  \"encrypt\": \"aaaaaaaaa\",
		  \"log_level\": \"INFO\",
		  \"bind_addr\": \"0.0.0.0\",
		  \"ports\": {
		    \"dns\": -1,
		    \"https\": 8700
		  },
		  \"verify_outgoing\": true,
		  \"verify_incoming\": false,
		  \"verify_server_hostname\": false,
		  \"key_file\": \"/certs/tls.key\",
		  \"cert_file\": \"/certs/tls.crt\",
		  \"ca_file\": \"/certs/ca_chain.crt\",
		  \"disable_update_check\": true,
		  \"leave_on_terminate\": true,
		  \"ui\": true,
		  \"disable_host_node_id\": true
		}
		",
	"consul.json": "{
		  \"bootstrap_expect\": 3,
		  \"server\": true,
		  \"datacenter\": \"dal\",
		  \"bind_addr\": \"0.0.0.0\",
		  \"client_addr\": \"0.0.0.0\",
		  \"retry_join\": [
		    \"consul-0.consul.pltfrm.svc.cluster.local\",
		    \"consul-1.consul.pltfrm.svc.cluster.local\",
		    \"consul-2.consul.pltfrm.svc.cluster.local\"
		  ],
		  \"encrypt\": \"aaaaaaaa\",
		  \"log_level\": \"INFO\",
		  \"ports\": {
		    \"https\": 8700,
		    \"http\": -1,
		    \"dns\": -1
		  },
		  \"verify_outgoing\": true,
		  \"verify_incoming\": false,
		  \"verify_server_hostname\": false,
		  \"key_file\": \"/certs/tls.key\",
		  \"cert_file\": \"/certs/tls.crt\",
		  \"ca_file\": \"/certs/ca_chain.crt\",
		  \"disable_update_check\": true,
		  \"leave_on_terminate\": false,
		  \"ui\": true,
		  \"disable_host_node_id\": true
		}
		"

**Comment by hsimon-hashicorp** [comment]
This seems like it might be an environmental or other issue. It's difficult to tell without more information about your exact setup. "context deadline exceeded" indicates a timeout. Can you provide more information?

**Comment by hsimon-hashicorp** [comment]
Additionally, if this is a configuration or environmental issue, as it seems to be, please try asking the [kind folks over at our Vault Discuss forum](https://discuss.hashicorp.com/c/vault/30). Thanks!

**Comment by hsimon-hashicorp** [comment]
@qiangliabcd If your standby pod is configured to attempt to connect to your primary pod and cannot, then you will see those timeout errors. Please see the [Vault High Availability With Consul guide](https://developer.hashicorp.com/vault/tutorials/day-one-consul/ha-with-consul) for best practices and recommendations for configuration.
I'm going to go ahead and close this issue now, but if you need to open a new issue to report a bug or request an enhancement, please feel free to do so!
