### ISSUE TITLE
Unable to login using a custom role_id

### ISSUE THREAD

**Issue by mgar** [hashicorp/vault#2000]
I wanted to mimic the behavior of **App ID** pushing both `role_id` and `secret_id`, so in my dev Vault I executed the following commands:

```
vault write auth/approle/role/testrole role_name=testrole
vault write /auth/approle/role/testrole/role-id role_id=testrole1
vault write /auth/approle/role/testrole/custom-secret-id secret_id=testsecret1
```

Then, when I try to login I get the following error message:

```
bash-4.3# vault write auth/approle/login role_id=testrole1 secret_id=testsecret1
Error writing data to auth/approle/login: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/approle/login
Code: 400. Errors:

* failed to validate SecretID: failed to find secondary index for role_id "testrole1"
```

I tried also doing this with the API and the result is the same. I could set up a custom `secret_id` and login with it and the `role_id` I get using  `vault read auth/approle/role/testrole/role-id` but once I set the custom secret_id there's no way to login.

**Comment by vishalnayak** [comment]
> vault write auth/approle/role/testrole role_name=testrole

@mgar There is no need to supply `role_name` parameter here. The value for `role_name` is pulled out from the path itself.
