### ISSUE TITLE
AWS IAM Auth using assumed role session identifier as EC2 instance ID

### ISSUE THREAD

**Issue by ellisroll-b** [hashicorp/vault#20021]
**Describe the bug**
I believe there is a bug in path_login.go, line 1433, where sessionInfo is passed to validate an InstanceID instead of an actual instanceID.

Our client call to login got this error:
```
URL: PUT http://<path_to_vault>/v1/auth/aws/login
Code: 400. Errors:

* failed to verify 1680789783208943468 as a valid EC2 instance in region us-east-1: error fetching description for instance ID "1680789783208943468": InvalidInstanceID.Malformed: Invalid id: "1680789783208943468"
```

**To Reproduce**
1. We setup vault, and enable AWS IAM Auth.
2. We created a role to enforce a match on AWS account number, vpcId, and use a policy to control secrets engine path access

looks like: 
```
key                               Value
---                               -----
allow_instance_migration          false
auth_type                         iam
bound_account_id                  [REDACTED]
bound_ami_id                      []
bound_ec2_instance_id             <nil>
bound_iam_instance_profile_arn    []
bound_iam_principal_arn           []
bound_iam_principal_id            []
bound_iam_role_arn                []
bound_region                      []
bound_subnet_id                   []
bound_vpc_id                      [vpc-REDACTED]
disallow_reauthentication         false
inferred_aws_region               us-east-1
inferred_entity_type              ec2_instance
policies                          [default policy_REDACTED]
resolve_aws_unique_ids            true
role_id                           6e4ac6b8-69bb-2681-b640-986d4e56835e
role_tag                          n/a
token_bound_cidrs                 []
token_explicit_max_ttl            0s
token_max_ttl                     35s
token_no_default_policy           false
token_num_uses                    0
token_period                      0s
token_policies                    [default policy_REDACTED]
token_ttl                         0s
token_type                        default
```

**Expected behavior**
The assumed role is parsed, the EC2 instance determined, and the actual EC2 instance ID is passed to AWS to validate it existence, state and VPC

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.13.1
* Server Operating System/Architecture: Ubuntu Linux 22.04

Vault server configuration file(s):
Current setup is HTTP
```
ui                                  = true
disable_mlock                       = true                    
cluster_addr                        = "http://TEMPLATE_HOST_IP:8201"  
api_addr                            = "http://TEMPLATE_HOST_IP:8200"  
enable_response_header_hostname     = "true"
enable_response_header_raft_node_id = "true"

# logging at info level, to files in the listed directory with names of /var/log/vault/vault-epoch.log, where epoch is a timestamp
# max log file of 5M, and max number of older than current at 2
log_level            = "debug"
log_file             = "/var/log/vault/"
log_format           = "json"
log_rotate_bytes     = 5242880
log_rotate_max_files = 2

storage "raft" {
  path      = "/mnt/data/vault"
  node_id   = "TEMPLATE_EC2_INST_ID"
  retry_join {
    auto_join        = "provider=aws region=TEMPLATE_AWS_REGION tag_key=REDACTED tag_value=TEMPLATE_ACCOUNT_ID-TEMPLATE_DC_NAME-vault-cluster addr_type=private_v4"
    auto_join_scheme = "http"
  }
}

# HTTP listener
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}

# AWS KMS auto unseal
seal "awskms" {
  region      = "TEMPLATE_AWS_REGION"
  kms_key_id  = "TEMPLATE_KMS_KEY_ID"
}
```

**Additional context**
Either we have missed something in configuration completely, or it looks like the validateInstance routine is being fed something other than an EC2 instance ID. Any advice is welcome.

**Comment by miagilepner** [comment]
Hi, the `sessionInfo` is the final portion of an ARN (after the last slash), and this means that Vault will parse an EC2 ARN (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-identity-roles.html#iir-arn) correctly to extract an instance ID.

I see that your role has `inferred_entity_type` set to `ec2_instance`. To confirm, is the client login call being run on an EC2 instance?

**Comment by ellisroll-b** [comment]
Yes. The client is written in go, using the Vault SDK and example from Hashicorp. It is a microservice running in a docker container as a pod, in an EKS (Kubernetes) cluster, running on a node (which is an EC2 instance).  The instance itself is not special, and fully routable.  We also tested making the client calls from a "jump host" EC2 instance in an ECS cluster (same VPC) with the same result.

In the meantime we have converted the design to an approle login, as we would prefer not to abandon Vault, but the IAM functionality would be lighter-weight than the approle model, for the client side in our deployment model.

**Comment by NateDimick** [comment]
Some additional info:

* Our microservice's pod has assumed a role via k8s serviceaccount
* When we intercept the prepared STS request the vault api/auth/aws package prepares and make it ourselves, the arn in the identity result is `arn:aws:sts::<our-account-id>:assumed-role/<our-assumed-role-name>/1680553935900647587` where our-assumed-role-name is not == `aws:ec2-instance`

This is (the relevant parts of) our client code:
``` go
import (
    "mymodule/config"
    "mymodule/log"
    
    "github.com/hashicorp/vault/api"
    "github.com/hashicorp/vault/api/auth/aws"
)

func NewClient() (*api.Client, error) {
    clientConfig := vault.DefaultConfig()
	client, err := vault.NewClient(clientConfig)
    if err != nil {
        return nil, error
    }
    return client, nil
}

func loginClient(client *api.Client) error {
	// this function is based on this example: https://github.com/hashicorp/vault-examples/blob/main/examples/auth-methods/aws/go/example.go
	log.Debug("Logging in to vault using IAM")
	awsAuth, err := aws.NewAWSAuth(
		aws.WithIAMAuth(),
		aws.WithRole(config.VaultRoleName()),
		aws.WithIAMServerIDHeader(config.VaultServerHeader()),
		aws.WithRegion(config.Region()),
	)
	if err != nil {
		log.Error("Could not initialize IAM auth method to Vault", err)
		return err
	}
	if _, err := client.Auth().Login(context.Background(), awsAuth); err != nil {
		log.Error("Failed to log in to Vault with IAM", err)
		return err
	}
	return nil
}
```

**Comment by miagilepner** [comment]
If you're assuming a role, then you will not be able to set the `inferred_entity_type` to be `ec2_instance`. This is described in the [Vault documentation](https://developer.hashicorp.com/vault/docs/auth/aws#mixing-authentication-types) about the AWS auth method, specifically:

> You configure a role with the iam auth type and further configure inferencing. You have a bound AMI ID and a bound IAM principal ARN. A client must login using the iam method; the RoleSessionName must be a valid instance ID viewable by Vault, and the instance must have come from the bound AMI ID.

Instead, you can configure your role to use the iam auth method _without_ inferencing.

**Comment by ellisroll-b** [comment]
Hmm, worth looking into, we need the assumed role for other elements of our security model.  This AWS auth was the most attractive choice. Approle is clunky in that the client needs to retrieve the 2 login elements independently, but is functional. Its unfortunate that this is not possible with the AWS auth currently (could additional metadata be passed by the client?).  Either way, I would recommend that documentation be updated, to be explicit that "assumed roles are not supported". I did read the docs (language above), but clearly didn't grok this limitation.  In the meantime, I'll go back and evaluate the IAM auth model.

Thank you for your engagement and support.

**Comment by hsimon-hashicorp** [comment]
> Hmm, worth looking into the EC2 auth, we need the assumed role for other elements of our security model. This AWS auth was the most attractive choice. Approle is clunky in that the client needs to retrieve the 2 login elements independently, but is functional.
> 
> We need to validate the account and vpc ID in the login. Its unfortunate that this is not possible with the AWS auth currently (could additional metadata be passed by the client?). Either way, I would recommend that documentation be updated, to be explicit that "assumed roles are not supported". I did read the docs (language above), but clearly didn't grok this limitation. In the meantime, I'll go back and evaluate the EC2 auth model.
> 
> Thank you for your engagement and support.

@yhyakuna is this something your team can help with?

**Comment by hsimon-hashicorp** [comment]
cc: @schavis

**Comment by schavis** [comment]
@himanshu-hashicorp I created a JIRA ticket for the update and added it to the docket for Monday.
