### ISSUE TITLE
bound_cidr_list issue

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#2002]
Needs some investigation:

https://groups.google.com/d/msg/vault-tool/vkI7Yp8Q1n8/Xnj9e8ILBAAJ

**Comment by vishalnayak** [comment]
This is not reproducible on the master branch. Waiting for the mailing-list response from the user.

**Comment by vishalnayak** [comment]
Failed to reproduce this. Did not get a reply from the reporter. Code analysis did not reveal any obvious errors. Closing this. Please reopen if any issue is found.
