### ISSUE TITLE
Development mode with TLS enabled not work

### ISSUE THREAD

**Issue by remriver** [hashicorp/vault#20038]
**Describe the bug**
In windows cmd window starting a server by typing command: "vault server  -dev-tls", then vault prompts: "At 7:47: illegal char escape", and has nothing else.

**To Reproduce**
typing command: "vault server  -dev-tls" in windows cmd program window.

**Expected behavior**
vault is started successfully in development mode with tls enabled.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.13.1_windows_amd64
* Vault CLI Version (retrieve with `vault version`): 1.13.1_windows_amd64
* Server Operating System/Architecture: windows 10

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by miagilepner** [comment]
Thanks for reporting this! This is clearly a bug, and we're working on the fix.
