### ISSUE TITLE
DynamoDB Backend - Underscore Issue

### ISSUE THREAD

**Issue by askmike1** [hashicorp/vault#20096]
**Describe the bug**
Using DynamoDB as a backend, I am unable to have a key who's name starts with an underscore. For instance, if I create secret/teams/account/_mykeyname I cannot navigate to the account folder because it sees nothing under it.

This does not appear to be an issue in consul backend.

**To Reproduce**
1. `vault write secret/teams/account/_mykeyname a=a`
2. `vault write secret/teams/account/myotherkeyname a=a`
3. `vault list secret/teams/account`
It will show just myotherkeyname, not _mykeyname (if myotherkeyname didn't exist it would say nothing found)

**Expected behavior**
It should correctly be able to list all keys including ones that start with an underscore.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.13.1
* Vault CLI Version (retrieve with `vault version`): 1.13.1
* Server Operating System/Architecture: RHEL/Linux

Vault server configuration file(s):

```hcl
cluster_addr = "https://xxx:8201"

storage "dynamodb" {
  table = "<ddb_name>"
  region     = "us-east-1"
  ha_enabled    = "false"
}

listener "tcp" {
    address = "0.0.0.0:8200"
    cluster_address = "0.0.0.0:8201"

    tls_disable = 1

    proxy_protocol_behavior = "use_always"
    x_forwarded_for_authorized_addrs = "0.0.0.0/0"
    x_forwarded_for_reject_not_present = "false"

    telemetry {
      unauthenticated_metrics_access = "true"
    }
}

max_lease_ttl = "4320h"
default_lease_ttl = "4320h"
ui = true
api_addr = "https://xxx:8200"

seal "awskms" {
  region     = "us-east-1"
  kms_key_id = "<kms>"
  endpoint   = "kms.us-east-1.amazonaws.com"
}
```

**Additional context**
Works fine in consul backend, but not DDB

**Comment by hghaf099** [comment]
Welcome to HashiCorp Vault repo, and thanks for filing this ticket. Indeed, we have documented this behaviour in the [code](https://github.com/hashicorp/vault/blob/cc749d6bbf14a8b50bd70b11b6b7abbfde8fad31/physical/dynamodb/dynamodb.go#L55-L58). The comment reads:
```
// DynamoDBLockPrefix is the prefix used to mark DynamoDB records
// as locks. This prefix causes them not to be returned by
// List operations.
DynamoDBLockPrefix = "_"
```
I am going to close this issue for now. Please feel free to reopen the issue or open a new one for further discussions.

**Comment by maxb** [comment]
But that's an internal implementation detail... surely the fact the storage backend fails to suitably escape user input which would otherwise conflict with its internal encoding scheme, should be considered a bug?

**Comment by askmike1** [comment]
Agreed, this is still something the storage backend should be able to handle (especially since kv v2 on ddb works fine with paths that start with underscore)
