### ISSUE TITLE
[question] Vault Across Data Centers

### ISSUE THREAD

**Issue by vrenjith** [hashicorp/vault#2011]
Have a basic question on how `vault` discovers the partner servers when vault servers are spread across `datacenters`. The backend is `consul` which is configured to have separate `datacenter` tags.

**Comment by jefferai** [comment]
Vault relies on having the same K/V prefix/data. Since Consul doesn't replicate K/V across datacenters I don't believe this is possible.

**Comment by vrenjith** [comment]
So in that case what is the recommendation in running vault across different data-centers and regions? Do we need a vault cluster per datacenter then?
