### ISSUE TITLE
vault ssh - Why are dynamic key secrets written to the client working directory?

### ISSUE THREAD

**Issue by stevehorsfield** [hashicorp/vault#2012]
See https://github.com/hashicorp/vault/blob/master/command/ssh.go#L165.

This seems to be an unnecessary step. Could you explain the thinking, and whether you believe this should be hardened? It's also not desirable from a purely user experience perspective, as it leaves files hanging around in client folders.

**Comment by ekristen** [comment]
@stevehorsfield Looking at the source it should be removed. https://github.com/hashicorp/vault/blob/master/command/ssh.go#L215

**Comment by stevehorsfield** [comment]
My point is that that is a risk. I have these files hanging around on my machine. The file is only deleted once the ssh session is terminated cleanly (from a client perspective) which often isn't the case. In any case, the file remains on disk in the interim.

Looking at the `ssh` command, it doesn't like reading the identity file directly from a named pipe. So, I would suggest that using a separate `ssh-agent` process:

* Spawn a new `ssh-agent` process
* Use `ssh-add` to add the identity to the agent from `stdin`
* Invoke `ssh`

```
$ /bin/cat ~/.ssh/id_rsa | ssh-add -
Identity added: (stdin) ((stdin))
$ ssh-add -l
2048 SHA256:oSjhwzdswo47uBKM/LC22aElaVaMZ/3HzRRehFRcJjw (stdin) (RSA)
```

**Comment by ekristen** [comment]
FWIW I'm just an avid user ...

> My point is that that is a risk. I have these files hanging around on my machine.

What is the risk you are seeing? If you have access to the vault secret you are authorized to have the secret in your possession?

> The file is only deleted once the ssh session is terminated cleanly (from a client perspective) which often isn't the case. In any case, the file remains on disk in the interim.

With dynamic key type, vault will revoke the key on the remote server after 5 minutes (be default), so the key hanging around after that doesn't really matter as it will no longer be valid.

As for your suggested improvements, it doesn't sound like a bad idea to me, but I don't make the decisions.

**Comment by stevehorsfield** [comment]
> What is the risk you are seeing? If you have access to the vault secret you are authorized to have the secret in your possession?

Indeed, I have a Vault lease for that secret. I'm not worried that the active user has access to the data directly. More an issue that the secret is pushed to disk and may accidentally get pushed to source control systems, as an example.

> With dynamic key type, vault will revoke the key on the remote server after 5 minutes (be default), so the key hanging around after that doesn't really matter as it will no longer be valid.

That's good to know, but it depends on the Vault server being able to decommission the key. Obviously, that should be ok, but it doesn't change the fact that the key is not itself limited. If the server is down or there's a network segmentation, the key still exists and is continuously usable.

My point is that it is an unnecessary step. In happy path there isn't really a security risk, but it's still unnecessary.

**Comment by vishalnayak** [comment]
Using temporary file to store the identity information and ensuring its deletion should do the job.

**Comment by stevehorsfield** [comment]
@vishalnayak - using a temporary file is definitely an improvement from a usability perspective. I'm not clear how you can ensure the deletion, though. I'll leave it with you to design and solve.

**Comment by vishalnayak** [comment]
@stevehorsfield A `defer` statement to remove the temporary file gets executed before the command completes, regardless of success or failure.

**Comment by stevehorsfield** [comment]
Didn't know you were doing a `defer`. Great. Sounds good.
