### ISSUE TITLE
Fix docs according to last helm template

### ISSUE THREAD

**Issue by felix-dpg** [hashicorp/vault#20167]
**Describe the bug**

https://github.com/hashicorp/vault/issues/20167

In tutorial web from using external vault, the values of the chart in the commands are deprecated:

https://developer.hashicorp.com/vault/tutorials/kubernetes/kubernetes-external-vault

Instead of --set "**injector.externalVaultAddr**=http://external-vault:8200" need to be **global.externalVaultAddr**=http://external-vault:8200"

Reference:

https://github.com/hashicorp/vault-helm/blob/main/values.yaml#L62

Thanks in advance!

Felix

**Comment by mister-ken** [comment]
Changed merged and page updated: [Link to changed text](https://developer.hashicorp.com/vault/tutorials/kubernetes/kubernetes-external-vault#:~:text=%2D%2Dset%20%22global.externalVaultAddr,the%20Kubernetes%20service)
