### ISSUE TITLE
Coding error in PKI issuer upgrade re CRL issuance

### ISSUE THREAD

**Issue by maxb** [hashicorp/vault#20189]
I believe I've spotted a coding error in #16865 (just by chance whilst perusing code, intrigued by #20137):

https://github.com/hashicorp/vault/blob/60d8bff89c490c5489c97b98b168de9a50239815/builtin/logical/pki/storage.go#L708-L713

Observe that the comment claims it is removing CRL signing usage, but the actual `ToggleUsage` call toggles OCSP signing usage instead.

Tagging @cipherboy as original author, to confirm the intended behaviour.

**Comment by cipherboy** [comment]
This looks valid @maxb. Do you want to submit a PR to fix it?

**Comment by maxb** [comment]
Sure, done: https://github.com/hashicorp/vault/pull/20220
