### ISSUE TITLE
Default and maximum TTLs on authentication backends are not readable

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/vault#2018]
As far as I can tell, it's impossible to retrieve an auth backend's maximum and default lease TTLs.  They appear to be settable, though:

```
$ vault mount-tune  -default-lease-ttl=24h auth/ldap
Successfully tuned mount 'auth/ldap'!
```

**Comment by jefferai** [comment]
See `vault auth -methods`.

**Comment by mfischer-zd** [comment]
Thanks!  Should we update the documentation to make it clear?  I couldn't find it easily.

**Comment by mfischer-zd** [comment]
Namely, https://www.vaultproject.io/docs/http/sys-auth.html

**Comment by jefferai** [comment]
Sure, that would be great.
