### ISSUE TITLE
ldap auth group mapping

### ISSUE THREAD

**Issue by mschirrmeister** [hashicorp/vault#2019]
The documentation for ldap auth and the `groupattr` mentions that `memberOf`should be used, if the `groupfilter` returns user objects. The value of a `memberOf` attribute looks usually something like this `cn=vaultCreateToken,ou=groups,dc=example,dc=com`. Which means the actual group is in `cn`.

When you map a group to a policy, you run `vault write auth/ldap/groups/vaultCreateToken policies=foo`. Does it mean the vault code is looking/extracting the group name from `cn=` from the `memberOf` attribute? Because cn is nowhere defined in the configuration.

In our directory we do not have this typical group setup with memberOf. We have our own logic which is based on **roles**. It is since always  like this and the background is for our own applications. But the concept is the same like with memberOf.

Example for comparision

```
memberOf: cn=vaultCreateToken,ou=groups,dc=example,dc=com
hasAccessRole: uniqueIdentifier=vaultCreateToken,ou=roles
```

If I now configure vault with `groupattr="hasAccessRole"` it works only if I map a policy to a **group** with the following value `uniqueIdentifier=vaultCreateToken,ou=roles`.

Complete command.
`vault write auth/ldap/groups/uniqueIdentifier=vaultCreateToken,ou=roles policies=foo`

So it works, but it looks a little strange.

Thats why I think the code looks for `cn` automaitcally when using `memberOf`. If that is the case, what do you think about the idea, if there would be an additional option like `sub-groupattr` where you can define the attribute that holds the actual value? It would allow complete flexibility of whatever people have in their directory and allows again a more human friendly group to policy mapping.
In our case `vault write auth/ldap/groups/vaultCreateToken policies=foo`

Thanks
Marco

**Comment by jefferai** [comment]
> The documentation for ldap auth and the groupattr mentions that memberOfshould be used, if the groupfilter returns user objects.

> In our directory we do not have this typical group setup with memberOf.

I don't think that advice is meant to be prescriptive, just advice for the common use-case where this is true (Active Directory).
