### ISSUE TITLE
Is ETCD version3.5 supported for HA cases with the latest version of vault

### ISSUE THREAD

**Issue by crujzo** [hashicorp/vault#20192]
**From the official documentation:** https://developer.hashicorp.com/vault/docs/configuration/storage/etcd
**This line is confusing:** the ETCD storage backend supports high availability. The v2 API has known issues with HA support and should not be used in HA scenarios.

**What does it mean :** _ETCD supports HA but should not be used in HA cases?? sounds self-contradictory to me._

Please help!

**Comment by hghaf099** [comment]
Welcome to HashiCorp Vault, and thanks for filing this issue. According to the documentation, although ETCD supports HA, V2 of the ETCD API has some issues with supporting HA and should not be used. Instead please consider using V3 of the ETCD API for HA. Note that ETCD is supported by CoreOS, and V2 API is removed from Vault in Vault 1.10. Vault has released version 1.13 already. So, please consider working with or migrating to V3 of the API. I am going to close this issue. Please feel free to open a new one for new issues or further discussions on this matter.
