### ISSUE TITLE
Make raft ha internal tla path configurable

### ISSUE THREAD

**Issue by shanmugh** [hashicorp/vault#20241]
**Is your feature request related to a problem? Please describe.**
We have a vault setup where we run multiple raft ensembles in different regions sharing a single storage backend. Since the raft internal tls certs are stored on the shared storage at a hardcoded path ([core/raft/tls](https://github.com/hashicorp/vault/blob/b4a36b4cfb8127557425f1b1124e68510e0f2bbe/vault/raft.go#L33)) it creates a race between the leaders of the different ensembles. Leading to a split-brain where the leaders of the ensembles think the that the tls cert to use is actually incorrect. Which leads to the one of the ensembles losing quorum when a node restarts and requiring multiple hours until cert rotation or operator intervention to fix the issue.

**Describe the solution you'd like**
It would be great if the raft tls path can be made configurable.

**Describe alternatives you've considered**
- Scaling down the non leader ensembles using custom scripting. Non trivial amount of operator tooling logic which is error-prone.
- Sealing the non leader ensemble to avoid TLS cert overwrites. Requires non-trivial operator tooling which is error-prone.
- Switching to a separate HA storage like MySQL. But this adds an extra dependency and adds cost.
- Use Consul for HA. We are simply moving the leader election problem from one service to another here.

**Explain any additional use-cases**
- Mainly this would allow Vault to be run in a multi-region setup and provide region failure protection.

**Additional context**
N/A

**Comment by maxb** [comment]
> We have a vault setup where we run multiple raft ensembles in different regions sharing a single storage backend.

Can you explain further what you mean by this? The word "ensemble" has no standard meaning in the Raft protocol. To be honest, it sounds a lot like you've improvised something unexpected and unsupported.

**Comment by miagilepner** [comment]
Hi @shanmugh, in addition to defining what you mean by "ensemble", can you provide more detail about how your cluster is configured? Perhaps providing the `ha_storage` and `storage` stanzas from your vault configuration would help.

**Comment by hsimon-hashicorp** [comment]
As it has been some time since we've heard from the issue reporter, I'm going to go ahead and close this issue. @shanmugh if you need to, please feel free to re-open this issue if you are able to provide the requested info. Thanks!
