### ISSUE TITLE
Generating a new encrypted root token from a root token.

### ISSUE THREAD

**Issue by MiLk** [hashicorp/vault#2025]
Is it possible to generate a new root token from an existing root token and have the new root token encrypted with PGP?

I'm using ansible to provision my Vault cluster, and it needs the unencrypted token to do the configuration. I would like to generate a new encrypted token, send it by email, then revoke the previous unencrypted token.

It seems that only `vault init` and `vault generate-root` accept a PGP key to encrypt the generated token. But both of them are using the master key shares.

Or does anyone has a better workflow to automate Vault configuration?

**Comment by vishalnayak** [comment]
PGP encryption of root token is only present during the initialization.

Will a response-wrapped token server your purpose?

**Comment by MiLk** [comment]
I'm not sure to understand how works response wrapping and how to use it.
Could you give me more details?

**Comment by jefferai** [comment]
See https://www.vaultproject.io/docs/concepts/response-wrapping.html
