### ISSUE TITLE
Update documentation for Java driver

### ISSUE THREAD

**Issue by henryx** [hashicorp/vault#20308]
According to [this](https://github.com/BetterCloud/vault-java-driver/pull/245#issuecomment-954066376), BetterCloud's implementation of the Java driver it was abandoned. For this reason, development of the library stay continued in [this fork](https://github.com/jopenlibs/vault-java-driver) instead of personal forks. So, is possible to update the [documentation](https://developer.hashicorp.com/vault/api-docs/libraries#java) that reflect new repository?

**Comment by miagilepner** [comment]
Thanks for reporting this. We'll update the docs.
