### ISSUE TITLE
Vault auto-unseal's with multiple/any KMS(CMK) key

### ISSUE THREAD

**Issue by reddy9694** [hashicorp/vault#20337]
**Describe the bug**
We have a Vault instance which is configured with postgresql as backend and we are using aws kms key to auto unseal the Vault.
Recently we have tried to bringup new Vault instance from the postgresql snapshot and used different KMS key ( This is different from the one we used earlier ). Vault was up and running, unsealed by itself.

we expected it will give the error since we are using different KMS key. Also tried to seal and unseal with the recovery keys, it is working fine. 

**To Reproduce**
1. Install Vault using postgres as backend, AWS KMS key to auto unseal and initialize.
2. Take the postgres snapshot of the above instance, create new postgres from the snapshot, bring new Vault instance and this time use a different AWS KMS key. ( We haven't run any operator commands this time to unseal vault ) 

**Expected behavior**
we expected it will give the error since we are using different KMS key. Also tried to seal and unseal with the recovery keys, it is working fine. 
a

**Comment by maxb** [comment]
Vault absolutely requires the original KMS key to unseal.

**Please note that even the recovery keys are NOT capable of unsealing Vault, if the original KMS key is inaccessible.**

However, Vault stores information about which KMS key is actually used inside the data encrypted with it - therefore my (untested) guess would be that even though you have changed the KMS information in the configuration file, Vault is actually still reachiing out to the original KMS key to perform the unseal.

I don't have a test environment suitable to verify this (I'm just a community member, I do not work for HashiCorp), but if you are able to selectively limit access to the original KMS key, you should be able to test it that way.

**Comment by miagilepner** [comment]
Vault stores key information with the encrypted value, so if the key is still available in AWS then Vault will successfully be able to decrypt. 

If you would like to perform a seal migration, you can follow the [instructions](https://developer.hashicorp.com/vault/docs/concepts/seal#seal-migration) in the documentation. However, please note that we don't support migrations from AWSKMS to AWSKMS. Instead, you will need to migrate from AWSKMS to another seal type, then migrate again to your new AWSKMS key.

**Comment by maxb** [comment]
> However, please note that we don't support migrations from AWSKMS to AWSKMS.

Is there any explanation of why that is? The documentation was changed in #15329 but no rationale is documented there.

**Comment by reddy9694** [comment]
Thank you for the reponse miagilepner.

Could you please let us know why AWSKMS to AWSKMS migration is not supported.

My understanding is, we can migrate data from one Vault instance to another by providing the source, destination details in the hcl file and then do the following  ( vault operator migrate -c migrate.hcl )

**Comment by miagilepner** [comment]
When migrating from a seal of the same type, the way we determine if the migration has completed is by trying to decrypt something using both seals and we assume that if the new seal works the migration has already been done and don't do anything. With AWS, the "new" seal will work because the AWS client library is using stored internal metadata to tell it which key to use for decryption and that metadata points to the old key. Decrypting succeeds, so Vault assumes that the migration is complete.

Changing this behavior causes other side effects and would be a large project to implement. So for now, AWSKMS -> AWSKMS is unsupported.

**Comment by reddy9694** [comment]
Thank you Miagilepner  for the details explanation.

I have tried the migration from one Vault to another, source I configured with AWS KMS key and destination is also configured with AWS KMS key ( both KMS keys are not same ). Once the migration is completed, I could access the newly migrated Vault same as the earlier( source ) one. 
To test, if the newly migrated vault is going to old KMS key( used by the source Vault ), I have disabled the KMS key used for the new Vault instance and tried to restart and it throws the error with the key id saying it is disabled and cannot unseal itself. ( I think here we can confirm the newly migrated Vault is using the different KMS key, not the one which is used by the source vault from where we migrated ). Could you please suggest.

**Comment by reddy9694** [comment]
@miagilepner - Could you please check my earlier comment.

**Comment by hsimon-hashicorp** [comment]
@reddy9694 Could you please provide more details about the test you are running, what your expected outcome is, and where it deviates from the results you're seeing? A step-by-step repro would help a lot. Thanks!

**Comment by hsimon-hashicorp** [comment]
As it has been a while since we have heard from you on this issue, I will go ahead and close it for now. Please feel free to open a new issue if you'd like to make another bug report, or visit us on [Discuss](https://discuss.hashicorp.com/c/vault/30) for general questions and community discussions. Thanks!
