### ISSUE TITLE
How do/Can I use TLS with approle auth backend?

### ISSUE THREAD

**Issue by bconner22** [hashicorp/vault#2041]
Hello, a question rather than an issue.  I've got Vault setup with an approle auth backend.  I have a couple of test secrets in the generic secret backend, and a policy applied.  I figured out how to generate a token, played around with ttl and # of uses.  I successfully used it with the api from a remote client server to access these secrets in Vault.  Great so far.

My question is, how can I enable TLS so that I can do the above over https instead of http?  I want this communication secure on the wire.  I read up on the TLS auth backend, but this is where I'm confused - is the TLS auth backend the only way to have https comms between vault and my clients?  Can I not use approle with https?  Maybe some sort of resource wrapping?  I feel like I'm missing something obvious in the model.  Thanks!

**Comment by jefferai** [comment]
Please use the mailing list for questions rather than the issue tracker, as that gets more eyes on it from more people that are able to help.

You should look at https://www.vaultproject.io/docs/config/index.html

**Comment by bconner22** [comment]
Thanks Jeff, will do!
