### ISSUE TITLE
[BUG] [vault-enterprise] Performance Replication error response unwrapping secondary token; status code is 400

### ISSUE THREAD

**Issue by Syntax3rror404** [hashicorp/vault#20421]
**Describe the bug**
As a system engineer with NPR licence, I have 2 Vault Clusters with 3 nodes. I want to use performance replication. I have successfully enabled the primary performance cluster and if i want to add the token on the secondary cluster i get the error `1 error occurred: * error response unwrapping secondary token; status code is 400, message is "400 Bad Request"`

**To Reproduce**
1. Install two Vault clusters with raft backend with helm
2. Enable repilcation performance on the first cluster
3. Get token and try to activate the secondary cluster with performance

**Expected behavior**
Working performance replication

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key                                    Value
---                                    -----
Seal Type                              shamir
Initialized                            true
Sealed                                 false
Total Shares                           3
Threshold                              2
Version                                1.13.2+ent
Build Date                             2023-04-25T19:30:45Z
Storage Type                           raft
Cluster Name                           vault-cluster-cb158f4f
Cluster ID                             bf09ce84-affe-8b84-b490-3fae37978ecd
HA Enabled                             true
HA Cluster                             https://vault-ent-1.vault-ent-internal:8201
HA Mode                                standby
Active Node Address                    http://10.42.66.101:8200
Performance Standby Node               true
Performance Standby Last Remote WAL    332
Raft Committed Index                   40524
Raft Applied Index                     40524
```
* Vault CLI Version (retrieve with `vault version`):
```
/ $ vault version
Vault v1.13.2+ent (ca5ea376af76440caa5e82e9b659b9e7c09268b4), built 2023-04-25T19:30:45Z
```
* Server Operating System/Architecture: Ubuntu 22.04 / AMD64 on Kubernetes v1.24.10+rke2r1

Vault server configuration file(s):

```hcl
ui = true
listener "tcp" {
  tls_disable = 1
  address = "[::]:8200"
  cluster_address = "[::]:8201"
}
storage "raft" {
  path = "/vault/data"
  retry_join {
    leader_api_addr = "http://vault-ent-0.vault-ent-internal.vault-ent.svc.cluster.local:8200"
  }
  retry_join {
    leader_api_addr = "http://vault-ent-1.vault-ent-internal.vault-ent.svc.cluster.local:8200"
  }
  retry_join {
    leader_api_addr = "http://vault-ent-2.vault-ent-internal.vault-ent.svc.cluster.local:8200"
  }
}
service_registration "kubernetes" {}
```

**Additional context**
We also tryed exposing vault over node port to make sure there is no problem on the ingress side. But this also ends with the error code 400. We used the official hashicorp helm chart.

Helm Chart Version: 0.24.1
Used Helm values:
```
---
global:
  openshift: false
injector:
  enabled: false
server:
  extraVolumes:
    - type: configMap
      name: ca-cert
      path: /vault
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: nfs4-csi
    accessMode: ReadWriteOnce
  enterpriseLicense:
    secretName: "vault-ent-license"
    secretKey: "license"
  image:
    pullPolicy: IfNotPresent
    repository: hashicorp/vault-enterprise
    tag: 1.13.2-ent
  ingress:
    enabled: true
    labels: {}
      # traffic: external
    pathType: Prefix
    activeService: true
    ingressClassName: nginx
    hosts:
      - host: vault.example.com
    tls:
    - hosts:
      - vault.example.com
      secretName: vault-ent-ingress-cert
  ha:
    apiAddr: null
    disruptionBudget:
      enabled: true
      maxUnavailable: null
    enabled: true
    raft:
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "http://vault-ent-0.vault-ent-internal.vault-ent.svc.cluster.local:8200"
          }
          retry_join {
            leader_api_addr = "http://vault-ent-1.vault-ent-internal.vault-ent.svc.cluster.local:8200"
          }
          retry_join {
            leader_api_addr = "http://vault-ent-2.vault-ent-internal.vault-ent.svc.cluster.local:8200"
          }
        }
        service_registration "kubernetes" {}
      enabled: true
      setNodeId: true
    replicas: 3
```

**Comment by miagilepner** [comment]
Hi, you'll be able to get quicker help by contacting [Vault support](https://support.hashicorp.com/hc/en-us/articles/115011134227-Engaging-with-HashiCorp-Support) and opening a ticket with them.

How are you getting the token to enable your second cluster as a performance replication secondary? Can you provide the commands you used?
If you search in the logs in both clusters for "core.performance-replication", do you get any log results? Please provide those logs as well.

**Comment by Syntax3rror404** [comment]
> Hi, you'll be able to get quicker help by contacting [Vault support](https://support.hashicorp.com/hc/en-us/articles/115011134227-Engaging-with-HashiCorp-Support) and opening a ticket with them.
> 
> How are you getting the token to enable your second cluster as a performance replication secondary? Can you provide the commands you used? If you search in the logs in both clusters for "core.performance-replication", do you get any log results? Please provide those logs as well.

I tryed both. UI and via commands. I followed this official guide: https://developer.hashicorp.com/vault/tutorials/enterprise/performance-replication

I can curl from the secondary to the primary cluster, so connection is not the issue. The Container shows no logs about core.performance-replication

**Comment by iGorebach** [comment]
Got similar situation  as @Syntax3rror404 described
The steps are the same, I followed the official guide
https://developer.hashicorp.com/vault/tutorials/enterprise/performance-replication

Environment - local k8s cluster
I suppose, that problem is related to incorrect primary node path definition in wrapped token.
Any update on this?

**Comment by heatherezell** [comment]
I am going to close this issue as this particular repository is for the Community Edition of Vault, and not Enterprise. Please file a support ticket and/or reach out to your SE for further help on this. Thanks in advance for your understanding!
