### ISSUE TITLE
Can't discover Vault when it is TLS and Consul is not

### ISSUE THREAD

**Issue by dtertman** [hashicorp/vault#2044]
I run a plaintext Consul with a TLS Vault.  Trying to run 
`vault init -auto -check`
fails:
`Error checking initialization status of discovered node: "http://address:port". Err: Get http://address:port/v1/sys/init: malformed HTTP response "\x15\x03\x01\x00\x02\x02"`

The reason is [here](https://github.com/hashicorp/vault/blob/master/command/init.go#L85) - the command uses the scheme of the Consul client as the scheme of the Vault service, which doesn't make much sense (to me).

My suggestion would be to publish the Vault scheme to Consul in the service definition tags.  Then we'd have it back in the catalog output.

**Comment by jefferai** [comment]
Publishing the scheme in the service definition tags seems like it would not actually fix this issue though. Probably the right thing to do would be to use the scheme used by Vault's redirect_addr.
