### ISSUE TITLE
Firefox blocks the OIDC popup

### ISSUE THREAD

**Issue by xskrasek** [hashicorp/vault#20455]
**Describe the bug**
When login in using OIDC, Firefox blocks the popup, and the login process fails. The popup needs to be whitelisted to work. 
**To Reproduce**
Steps to reproduce the behaviour:
1. Open Vault in Firefox
2. Login using OIDC
3. See the error

**Expected behaviour**
The popup does not get blocked, or there is a redirect instead of the popup.

**Comment by hsimon-hashicorp** [comment]
This is fairly standard behavior with popup blockers, where you need to whitelist the site and/or turn off popup blocking. I will close this issue now, but please feel free to open a new issue if you run across any other bugs or have other feature requests. Thanks!
