### ISSUE TITLE
How to enter the official vault docker container?

### ISSUE THREAD

**Issue by sysadmin1337** [hashicorp/vault#2050]
I want to enter the vault docker container to be able to see the current configuration at `/vault/config`, but I'm unable to with `docker exec -it vault /bin/bash`. 

The problem is `/bin/bash` can't be found inside the container, I'm guessing this is because of security reasons. Or maybe Alpine linux doesn't include it. 

Error: `rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"/bin/bash\\\": stat /bin/bash: no such file or directory\"\n"`

Docker run command: 
```
docker run --cap-add=IPC_LOCK \
           -e 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}' \
           --name vault \
           vault server
```

**Comment by jefferai** [comment]
I don't know anything about Alpine so I suggest checking their docs. Perhaps /bin/sh would work though.

**Comment by sysadmin1337** [comment]
Confirmed, `/bin/sh` or `sh` works.
