### ISSUE TITLE
Search secretss

### ISSUE THREAD

**Issue by ekulis** [hashicorp/vault#2051]
Hi,
I'd like a way to search the secrets in the vault. I'm prototyping now so not overly concerned with the roles and the access. Just proving concepts now.
Right now I see just recursively listing and descending into the fault hierarchy mimicking what Unix find would do.  Is there a better way?
Ultimately I'd have a postgresdb and search would be easier on available fields.
In the postgres scenario would I need to parse and duplicate the implicit metadata that's in the hierarchical tree into searchable fields in postgres?
Not quite sure what I'm asking hear so I need expert advice to ask the right questions.

**Comment by jefferai** [comment]
Unfortunately there are no current plans to provide search functionality.

**Comment by mariuspana** [comment]
Any plans on getting a global search features introduced? Or maybe someone could share how they search thorough thousands of secrets to narrow down a set (from cli I expect)?
