### ISSUE TITLE
Secrets Engine / Auth Method: Cryptographic Message Signing

### ISSUE THREAD

**Issue by Tylerlhess** [hashicorp/vault#20528]
**Is your feature request related to a problem? Please describe.**
I would like to have a secure way for cryptographic keys to be stored and used to sign transactions and messages.

**Describe the solution you'd like**
I want a solution to store and allow message and cryptographic transaction signing privileges to be allocated and permissioned through vault.

**Describe alternatives you've considered**
Storing cryptographic keys directly in vault but that opens the possibility for credential leakage outside of an organization.

**Explain any additional use-cases**
I have a site that uses Ravencoin private keys sign dynamic messages as a way of authenticating identity. The same is done on many Etherium blockchain based sites utilizing Metamask signing to verify ownership rights to things like NFT's. While not currently a popular solution these signature solutions could be an easy way to validate ownership of NFT's used for pseudo-anonymous subscription services and ownership.  

This would facilitate institutional STO (Security Token Offering) participation. STO's are basically blockchain stocks. My crypto mining company uses an STO for ownership records and dividend distribution on the Ravencoin Blockchain. Authentication to the company site is done through a cryptographically signed message from an address owning one of these assets. This is done with a wallet or browser plugin. 

Having this feature would open the door for institutional control of crypto tokens and ownership without the possibility of lost keys or assets from individual departures (from the company or life). It would also give permission to sign messages or use the keys without access to them.

**Comment by hsimon-hashicorp** [comment]
While Vault as a product uses cryptography and secrets to keep your data secure, this is not the same thing as what many modern folks think of as "crypto", which has become short-hand for cryptocurrency. This particular use case does not fit well with the product as it is currently designed and used by our customers, and so we are unlikely to ever add features for cryptocurrency, mining, or blockchains. Thank you for your interest in Vault!

**Comment by cipherboy** [comment]
We have asymmetric signing in the Transit engine, which currently supports RSA PSS/PKCS#1v1.5 and ECDSA (including ed25519) operations. Is there a particular operation missing from this engine? Ed448 is unlikely to happen as Go doesn't natively support it.

**Comment by Tylerlhess** [comment]
I think that might work but I will need to look into it was hoping for a more specialized and controlled process to allow nuanced permissions but we might be able to make the transit engine work however it would likely be clunky.

**Comment by hsimon-hashicorp** [comment]
> I don't see this as any different than a database authentication process or a temporary password to use access. It's literally for protecting authentication secrets while granting permissioned access to their usage. This is not an ask to support cryptocurrencies but to support cryptographic signing using asymmetric keys. This is the next wave of permissioned access. This is equivalent to granting temporary access to get a message signed using ssh keys to login to a server.
> 
> Yes the greatest use cases are of course going to be the cryptocurrency market as they will be the first to adopt such authentication as proof of identity. But this is not and will not be exclusive to them and shutting down a request for being tangental to the cryptocurrency industry is _**akin to discriminating against someone because of any protected attributes**_. Please take the submission upon the merits of the request and the positioning of your product to solve the problem and protect secrets and not based on some unfounded industry bias.
> 
> Yes my crypto mining company uses STO's but that is no different than any other stock. It just means that I cut down a lot on the administration costs and paperwork because I am using a globally distributed ledger to keep my books. Once again this is not about cryptocurrency but giving the ability for your secretary to login to the account without them having the cryptographic keys and thus access to steal the stocks.

(Emphasis mine.)

@Tylerlhess please take a moment to read the [HashiCorp Community Guidelines](https://www.hashicorp.com/community-guidelines), or re-acquaint yourself with them if you have already seen them. Comparing decisions made for the roadmap of an enterprise security product to discrimination is not appropriate, and neither is accusing the company or any of its members of "unfounded industry bias". Please consider this your first warning.

At this point, I will be locking this issue from new comments. Thank you.
