### ISSUE TITLE
Vault agent didn't reload certificate after signal HUP.

### ISSUE THREAD

**Issue by evan361425** [hashicorp/vault#20538]
**Describe the bug**
I have a process send HUP signal to Vault agent after new certificate issued but the Vault agent did not use the latest certificate and causing error.

**To Reproduce**
1. Run `vault agent -config config.hcl` using TLS connection with server but listen on TCP port([`tls_disable`](https://developer.hashicorp.com/vault/docs/configuration/listener/tcp#tls_disable)).
2. Wait until certificate expired.
3. Send `HUP` signal to Vault agent.

```
2023-05-08T02:53:32.849Z [ERROR] agent.auth.handler: error authenticating:
  error=
  | Error making API request.
  | 
  | URL: PUT https://server:8300/v1/auth/cert/login
  | Code: 500. Errors:
  | 
  | * failed to verify client's certificate: x509: certificate has expired or is not yet valid: current time 2023-05-08T02:53:32Z is after 2023-05-08T02:53:19Z
```

Here are screenshots in my testing environment:

![Screenshot 2023-05-08 at 2 35 22 PM](https://user-images.githubusercontent.com/14554683/236752839-908f57f3-4a3b-4f7e-89c0-c2f77dfdabe1.png)

First, there is a valid certificate(see the left panel) will be expired at `06:36:00` and Vault agent use it to do some normal re-authenticating actions around every 40s(see the right panel).

![Screenshot 2023-05-08 at 2 36 06 PM](https://user-images.githubusercontent.com/14554683/236753515-b752aff2-d109-4175-b692-92f4cef14df5.png)

The new certificate issued and `notAfter` changed to `06:37:48`. I send the signal `HUP` after the certificate changed (see the message: `Vault Agent config reload triggered`).

![Screenshot 2023-05-08 at 2 36 28 PM](https://user-images.githubusercontent.com/14554683/236753662-8c3c1764-f1dc-43bd-be54-07eff67c54c3.png)

Finally, when it start to authenticate, it failed on TLS handshake because of the invalid certificate:

**Expected behavior**
Reload the certificates.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.13.2
* Vault CLI Version (retrieve with `vault version`): 1.13.2
* Server Operating System/Architecture: Docker

Vault agent configuration file(s):

```hcl
vault {
  address = "https://server:8300"
  ca_cert = "/certs/client-ca.crt"
  client_cert = "/certs/client.crt"
  client_key = "/certs/client.key"
}

auto_auth {
  method "cert" {
    ca_cert = "/certs/client-ca.crt"
    client_cert = "/certs/client.crt"
    client_key = "/certs/client.key"
  }

  sink "file" {
    config {
      path = "/app/token"
    }
  }
}

listener "tcp" {
  address = "0.0.0.0:8100"
  tls_disable = true
}
```

**Additional context**
I was using Docker  for testing scenario but it can also reproduced in VM environment.

**Comment by evan361425** [comment]
Seems like it need to load cert from file when reload client in 

https://github.com/hashicorp/vault/blob/main/command/agentproxyshared/auth/cert/cert.go#L133-L137

```go
t := &api.TLSConfig{
	CACert:     c.caCert,
	ClientCert: c.clientCert,
	ClientKey:  c.clientKey,
}
```

which is triggered by https://github.com/hashicorp/vault/blob/main/command/agentproxyshared/auth/auth.go#L198

```go
clientToUse, err = am.(AuthMethodWithClient).AuthClient(ah.client)
```

**Comment by kencx** [comment]
This issue is similar to that raised in #18562 which #19002 aims to fix hopefully.

**Comment by cipherboy** [comment]
Per above; closing as fixed duplicate.
