### ISSUE TITLE
Changelog URL does not point to Changelog

### ISSUE THREAD

**Issue by Kloppi313** [hashicorp/vault#20539]
**Describe the bug**
The link in Vault UI to the changelog file does point to [hashicorp/vault/blob/main/CHANGELOG.md](https://github.com/hashicorp/vault/blob/main/CHANGELOG.md). Fortunally the vault project is very active, so that the changelog became long. But github is not able to render it. So it is usefull to point to the raw file: https://raw.githubusercontent.com/hashicorp/vault/main/CHANGELOG.md

**To Reproduce**
Click the link with the version number in vault ui

**Expected behavior**
Changelog should be readable with just one click.

**Environment:**
* vault 1.13.2 (but this should not matter)
* Chrome 112.0.5615.139 on Windows 10

Vault server configuration file(s):

```hcl
not relevant
```
![image](https://user-images.githubusercontent.com/36038231/236777188-522a489d-f846-486d-8426-5f841a3f6bbd.png)

![image](https://user-images.githubusercontent.com/36038231/236776806-bc9c178a-dd92-4262-866f-295f0dc8598e.png)

**Comment by StephenDunne97** [comment]
Hi, I can work on this. 

An alternative URL might be: https://github.com/hashicorp/vault/blob/main/CHANGELOG.md?plain=1 

This keeps the user on the Github site and is presented better.

**Comment by maxb** [comment]
I don't think either of the proposed alternative URLs are the right way to go, as they present unformatted plain text to users.

For a better user experience, it would be preferable to archive some older changelog entries to a separate file, so the main `CHANGELOG.md` can be rendered by GitHub in reasonable time.

**Comment by StephenDunne97** [comment]
Good point, that makes sense. 

The changelog goes back to the initial release from April 28, 2015. Is there a guide/best-practice for archiving that should be taken into account for this? 

If we split by major version, the first major update was on December 14th, 2018

According to this doc https://docs.github.com/en/repositories/creating-and-managing-repositories/about-repositories#text-limits, text files over 512kb will be presented as plain-text (Ours is 678 KB)

I tested locally and removing all logs from before 1.0.1 reduced the file size to 472kb.

**Comment by Kloppi313** [comment]
I dont like the idea.
Plain text should not be a harm to the user. Also the anchored link to the changelog corresponding to the installed version was removed once, which makes those more or less github specific UI features useless.
Looking for information in serveral places is a harm, also because few (I dont even know one) projects do archive older changelog information.

**Comment by maxb** [comment]
I guess someone from HashiCorp will need to decide which of our opposing points of view they prefer to go with.

**Comment by hsimon-hashicorp** [comment]
We are aware of intermittent issues with the changelog not rendering properly. Unfortunately the changes we have thus far attempted have not been successful at resolving the issue. We are aware that this is a poor user experience, and we will continue to work on the issue as time allows. I'm going to go ahead and close this issue at this time, but please know that this doesn't mean we won't continue to attempt to fix this. We appreciate your patience and understanding. :)
