### ISSUE TITLE
hvac.exceptions.VaultDown: no active Vault instance found

### ISSUE THREAD

**Issue by Wintermute1** [hashicorp/vault#2055]
I am getting the above error even though the logs seem to be normal at this time.

`2016/11/01 14:12:04 [WARN] core: stopping active operation
2016/11/01 14:12:04 [INFO] core: pre-seal teardown starting
2016/11/01 14:12:04 [INFO] rollback: stopping rollback manager
2016/11/01 14:12:04 [INFO] core: pre-seal teardown complete
2016/11/01 14:12:04 [INFO] core: vault is sealed
2016/11/01 14:12:04 [INFO] core: vault is unsealed
2016/11/01 14:12:04 [INFO] core: entering standby mode
2016/11/01 14:12:05 [INFO] core: acquired lock, enabling active operation
2016/11/01 14:12:05 [INFO] core: post-unseal setup starting
2016/11/01 14:12:05 [INFO] core: mounted backend of type generic at secret/
2016/11/01 14:12:05 [INFO] core: mounted backend of type cubbyhole at cubbyhole/
2016/11/01 14:12:05 [INFO] core: mounted backend of type system at sys/
2016/11/01 14:12:05 [INFO] rollback: starting rollback manager
2016/11/01 14:12:05 [INFO] core: post-unseal setup complete
`

**Comment by jefferai** [comment]
Please stick to the mailing list rather than here, especially as HVAC is not part of this project.
