### ISSUE TITLE
VAULT_LOCAL_CONFIG= is undocumented

### ISSUE THREAD

**Issue by sysadmin1337** [hashicorp/vault#2056]
Neither documented at [environment variables](https://www.vaultproject.io/docs/commands/environment.html) or [server configuration](https://www.vaultproject.io/docs/config/index.html). Just at the [docker hub vault](https://hub.docker.com/_/vault/) documentation.

**Comment by ekristen** [comment]
That's because the environment variable is only used in the docker version of vault. See https://github.com/hashicorp/docker-vault/blob/3d3957180d689ecddb537aa799a878171280e8a3/0.6.2/docker-entrypoint.sh#L17
