### ISSUE TITLE
pki: allowed_domains are compared case sensitive if they use glob patterns

### ISSUE THREAD

**Issue by gnugnug** [hashicorp/vault#20562]
**Steps to Reproduce:**
```
# Create a role with allow_glob_domains enabled
vault write pki/roles/foo allowed_domains="example.com, *.example.com" allow_glob_domains=true
# Issuing certificates works regardless of case
vault write pki/issue/foo common_name="example.com" #works
vault write pki/issue/foo common_name="EXAMPLE.COM" #works
# When using an allowed_domain with a glob pattern case must suddenly match
vault write pki/issue/foo common_name="sub.example.com" #works
vault write pki/issue/foo common_name="SUB.EXAMPLE.COM" #fails with
["common name SUB.EXAMPLE.COM not allowed by this role"]
```

I would expect that the last command is successful as well, so that their behaviour is consistent. The domain names in the certificate are not case sensitive.

**Comment by cipherboy** [comment]
Hmm, I'm thinking we'll have to do a `strings.ToLower(...)` on both the glob pattern and the supplied domain name. Thoughts @stevendpclark or @kitography? Is there something that I'm missing here? I think per RFC 5280, we'd expect puny-coded domains, but this doesn't apply to non-domain CNs IIRC. I don't think there's an approach using `strings.EqualFold(...)` without perhaps forking https://github.com/ryanuber/go-glob.

**Comment by kitography** [comment]
I don't see any reference to Punycode, or RFC3492 in RFC5280?

It doesn't look as easy to solve to me as "strings.ToLower()".

There is an incredibly intricate standard here for matching non-glob things: https://www.rfc-editor.org/rfc/rfc5280#section-7.1 which refers to : https://www.rfc-editor.org/rfc/rfc4518#section-2.2 which refers to: https://www.rfc-editor.org/rfc/rfc3454

As far as the RFCs go, I found very little on matching globs/wildcards, or more, I found ( https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.6 ), which effectively gives up:

```
   Finally, the semantics of subject alternative names that include
   wildcard characters (e.g., as a placeholder for a set of names) are
   not addressed by this specification.  Applications with specific
   requirements MAY use such names, but they must define the semantics.```
   
   So, the options I'm seeing are:
   * keep being a bit more strict on wildcards (which is a little weird in this example, but probably fine), or 
   * find a string prep that ignore wildcards, then use wildcards to match?  (if there's a library doing it, I'd happily upgrade. )
   * write our own half-match thing: I'm kind of concerned that toLower (in particularly on the matcher string) is going to have some weird effects on international languages here, so I'd need a lot more time to go over examples to see that work - I'd be particularly concerned about, for instance, final sigma (two lower case letters mapping to a single upper-case letter).  It looks like https://www.unicode.org/reports/tr21/tr21-5.html defines casefold separately than just matching on to lower.

**Comment by gnugnug** [comment]
Thanks for the valuable insights. My point is that Vault already case-foldes domains without a glob pattern before comparison, so I don't see why it shouldn't do the same for the _static_ part of domains with glob patterns.

**Comment by KushnerykPavel** [comment]
Hello! @cipherboy  may I pick this bug ?

**Comment by stevendpclark** [comment]
@KushnerykPavel please feel free!

**Comment by KushnerykPavel** [comment]
PR: https://github.com/hashicorp/vault/pull/22126

**Comment by cipherboy** [comment]
> unless we agree `strings.ToLower(...)` is sufficient in all cases, which I'm not (personally) convinced of.

Just for future me and others: this was merged and should be fine when `common_name` is strictly a hostname (which should be punycode ASCII per RFC 5280 IIRC).

However, when using certs for client auth with general names, this could still not work as e.g., we'd compare:

```
[E'] -> [e'] != [e][combine][']
```

we've not made it any worse, and this wouldn't have worked before, but the shortcomings are still there.
