### ISSUE TITLE
What's the preferred way to get a secret inside a docker container using the HTTP API?

### ISSUE THREAD

**Issue by sysadmin1337** [hashicorp/vault#2057]
Having trouble getting secrets extracted from the API working inside a docker container, what's the preferred way to do this? Also see this question on [SE](https://stackoverflow.com/questions/40380339/how-to-get-a-secret-from-hashicorps-vault-http-api-into-a-docker-container).

**Comment by ekristen** [comment]
As an hourly user of docker, there isn't necessarily a preferred way. There are many different methods though. 

The user who responded on SE is right, the ENV instruction is not interpreted by a shell, so you can't set it that way, nor would I suggest doing it that way. Using ENV bakes the value into the image itself, which basically negates the purpose of using vault to store the secret. Instead you should set the ENV variable at a minimum at run time.

At a minimum a few options are ... 

1. Use a script to populate the variables as environment variables in the docker run command.
2. You could use this docker volume plugin (still a WIP I think) https://github.com/ehazlett/docker-volume-libsecret

**Comment by jefferai** [comment]
Please use the mailing list for questions...this gets more eyes on it and keeps the issue tracker free to track issues.

**Comment by sysadmin1337** [comment]
@ekristen I'm now ARG'ing the vault ip/port/token in the dockerfile and fetching the secret with the vault API, works perfectly.
