### ISSUE TITLE
Can't connect to postgres using a SNI proxy

### ISSUE THREAD

**Issue by digiserg** [hashicorp/vault#20581]
**Describe the bug**
I'm trying to set up the postgres credentials database driver. My database is in Kubernetes and I use a SNI-aware proxy to connect to it. [SSL-SNI](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLSNI) is enabled by default and this works fine with `psql` client or any other (modern) client I tried. However, vault fails to connect and verify the connection. 

**To Reproduce**

```sh
vault write database/config/my-postgresql-database \
    plugin_name="postgresql-database-plugin" \
    allowed_roles="my-role" \
    connection_url="postgresql://{{username}}:{{password}}@mydb.mydomain.com:5432/database-name" \
    username="vaultuser" \
    password="vaultpass"
```

The error is 

```
context deadline exceeded
```

and I can't see in the proxy it's hitting the database. Connection using `psql` is always successful. 

**Expected behavior**

The connection should be verified and I should be able to request credentials via the engine.

**Environment:**
* Vault Server Version: 1.12.3
* Vault CLI Version: 1.12.3
* Server Operating System/Architecture: Linux

**Comment by digiserg** [comment]
I found the issue, SNI was not added until 1.10.7 and vault is using 1.10.6

https://github.com/lib/pq/blob/v1.10.7/ssl.go#L54

**Comment by raskchanky** [comment]
Hi @digiserg 

I've opened https://github.com/hashicorp/vault/pull/20594 which sounds like should solve this problem. Thanks for letting us know! 🙌

**Comment by mathewjustin** [comment]
@digiserg 

I hope you don't mind me reaching out! on this thread! 

I'm trying to set up multiple PostgreSQL instances behind a single load balancer using SNI-based routing, but I'm running into the classic PostgreSQL protocol timing issue where the SSL request comes before the TLS Client Hello with SNI information.

I noticed you mentioned that your setup "works fine with psql client or any other modern client" with your SNI-aware proxy. This is exactly what I'm trying to achieve!

Would you mind sharing some details about:
- What SNI-aware proxy solution you're using?
- How you configured it to handle the PostgreSQL SSL negotiation timing?
- Any specific configuration that made it work?

I've been exploring various approaches (Istio, custom Envoy filters) but haven't found a clean solution yet.  It will be extreamly helpful if you shed some light on how you made this proxying working..

**Comment by digiserg** [comment]
@mathewjustin I don't have access to the environment anymore, it was built for a customer but I used Traefik for this. Postgres was running in Kubernetes.

**Comment by mathewjustin** [comment]
Thanks for the response @digiserg . I found some leads with Traefik - Finally we made it working. :)
