### ISSUE TITLE
Vercel is blocking PR process

### ISSUE THREAD

**Issue by ffkaka** [hashicorp/vault#20589]
### Discussed in https://github.com/hashicorp/vault/discussions/20554

<div type='discussions-op-text'>

<sup>Originally posted by **ffkaka** May 10, 2023</sup>
I have made a [PR](https://github.com/hashicorp/vault/pull/20551) in few weeks ago. But it has stopped to get a vercel approval without any feedback. 
Could you let me know what I can do for getting approval of that vercel test(?) or if there are some processes that I had missed. 

<img width="853" alt="image" src="https://github.com/hashicorp/vault/assets/7709271/b5a96d1a-c7a7-4280-893d-b20841e83b6d">

Thanks in advance</div>

**Comment by cipherboy** [comment]
These and other tests require a reviewer at Hashicorp to take a look and approve their execution before beginning. I've gone ahead and done so, though I'm not quite sure which team owns the MySQL storage integration. 

cc: @hsimon-hashicorp

**Comment by ffkaka** [comment]
@cipherboy 
Thank you for your response. Let me wait until a proper reviewer is going to be assigned.
