### ISSUE TITLE
Feature Request: Logout function for CLI

### ISSUE THREAD

**Issue by jcrowthe** [hashicorp/vault#2059]
On the CLI, upon successfully running `vault auth`, the token is stored at ~/.vault-token. I assume this is to allow multiple terminal sessions to access vault after one login. It would make more sense to dump the token to the VAULT_TOKEN environment variable noted in the docs, but I can see some not liking this idea.

Instead, this request is for a `vault logout` function to be added to the cli. Very simply, this would effectively run `rm ~/.vault-token`.

I have mentioned these two related items here in order for others to understand the context. Either solution would function, and I would like to start a conversation regarding the two.

**Comment by jefferai** [comment]
You're correct about your assumption. It's also a pluggable mechanism; an external binary can be used so that in theory it can e.g. integrate with your system keychain via envchain or some such thing.

We're not going to add a `vault logout` command at this time however. As you noted it would be functionally equivalent to a simple `rm` and we already have enough commands that people very often get confuzzled.

**Comment by vcardillo** [comment]
Why allow the root token to be accidentally left on the machine?

**Comment by jefferai** [comment]
Note that there are now `token-only` and `no-store` flags on the CLI, either of which will cause the token to not be stored.

**Comment by TerraTech** [comment]
What I've been doing is:  _$ vault token revoke -self_
seems to work well for intended purpose.

**Comment by a-nldisr** [comment]
Advice: Do not use _vault token revoke -self_ when you are using the root token or if you have a token that has a lot of children. Because this revokes all tokens generated by this token and the tokens they created. So use instead
_vault token revoke -mode=orphan -sef_

**Comment by jefferai** [comment]
Please note that @a-nldisr 's comment above is not considered canonical advice. Revoking in orphan mode has real security implications that should be understood before using it.

**Comment by jazzdragon** [comment]
We just set `VAULT_TOKEN` before each command when using the root token to avoid saving it at all, as having it saved on the home folder is a huge security risk.

**Comment by kauedg** [comment]
`vault logout` would be very helpful to avoid revoking the token being used, specially when using the root token, during development, for example.

If the CLI has a `vault login` functionality that sets the token to be used it's only logical that `vault logout` unsets that token and clearly does not revoke it, put that there's a revoke option.

Also, it's very unprobable that someone operating vault would get "confused" with a logout option that just removes the `.vault-token` file. It's pretty well stablished what "logout" does and the file is very implementation-specific.

```
Subcommands:
    capabilities    Print capabilities of a token on a path
    create          Create a new token
    lookup          Display information about a token
    renew           Renew a token lease
    revoke          Revoke a token and its children
    logout          Unsets the token being used
```

**Comment by winkee01** [comment]
I think logout makes more sense compared to other commands.

**Comment by modbender** [comment]
If we run vault login in parallel it would use the same token, and supposedly if one of them want's to logout by deleting the token, wouldn't it unintentionally logout others using the same login? I'm talking about if we use this in a shell script and run things parallelly.

**Comment by blackswanny** [comment]
afaik, we need log out command. For instance, my user has permission to login for self of course, but when I call `vault token revoke <my-auth-toke-id>`, I get `permission denied`, because my admins forbid this operation for me. So seems illogical I can login, but I can't log out myself
