### ISSUE TITLE
Comparison to keywhiz could use an update

### ISSUE THREAD

**Issue by NathanMcCauley** [hashicorp/vault#206]
I found the comparison to keywhiz to be missing some info. Full disclosure: I helped work on keywhiz so I'm not unbiased. That said, 

* Keywhiz supports rotation through versioned secrets (its not available in kwfs, but it is supported in the API and datamodel)
* Keywhiz supports human and machine authentication
* Keywhiz has an API available, the FUSE mountpoint is just a convenience if folks want it

I have a fork [here](https://github.com/NathanMcCauley/vault/commit/47950d9efb30201c1fac46e7b468549919080d0e) that updates some of the language, if you'd like a PR issued I can send one.

**Comment by sethvargo** [comment]
Hi @NathanMcCauley 

As you might suspect, we are not experts on the other tools that exist in this same space. We tried to be as informative as possible, but if you have additional information or changes, we would gladly welcome a pull request. The documentation lives in the `website/` folder of this repository :smile:. Let me know if I can help!

**Comment by armon** [comment]
Fixed by #207
