### ISSUE TITLE
unsupported path

### ISSUE THREAD

**Issue by Jwy-jump** [hashicorp/vault#20614]
Hi, when I run with this command
 ` vault secrets enable -path=test -description="MQTT CA" -max-lease-ttl=87600h pki

Success! Enabled the pki secrets engine at: test/

vault write test/Root/generate/internal common_name="test.com" ttl=87600h key_bits=4096`

It shows the following errors:

Error writing data to test/Root/generate/internal: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/test/Root/generate/internal
Code: 404. Errors:

* 1 error occurred:
        * unsupported path

**Comment by cipherboy** [comment]
@Jwy-jump Note that paths are case sensitive. `[[[...]]]` for highlighting.

```
[cipherboy@xps15 ~]$ vault write test/[[[R]]]oot/generate/internal common_name="test.com" ttl=87600h key_bits=4096
Error writing data to test/Root/generate/internal: Error making API request.

URL: PUT http://localhost:8200/v1/test/Root/generate/internal
Code: 404. Errors:

* 1 error occurred:
	* unsupported path
```

versus a lower case `root`:

```
[cipherboy@xps15 ~]$ vault write test/[[[r]]]oot/generate/internal common_name="test.com" ttl=87600h key_bits=4096
WARNING! The following warnings were returned from Vault:

  * This mount hasn't configured any authority information access (AIA)
  fields; this may make it harder for systems to find missing certificates
  in the chain or to validate revocation status of certificates. Consider
  updating /config/urls or the newly generated issuer with this information.

Key              Value
---              -----
certificate      -----BEGIN CERTIFICATE-----
... additional output elided ...
```

**Comment by Jwy-jump** [comment]
@cipherboy Thanks,this question is solved.
