### ISSUE TITLE
GitHub Actions - deprecated warnings found - action required!

### ISSUE THREAD

**Issue by sarahethompson** [hashicorp/vault#20627]
Workflow Name: Security Scan
Branch: main
Run URL: https://github.com/hashicorp/vault/actions/runs/4963538387

save-state deprecation warnings: 0
set-output deprecation warnings: 1
node12 deprecation warnings: 1

Please review these deprecation warnings as soon as possible and merge in the necessary updates.

GitHub will be removing support for these commands and plan to fully disable them on 31st May 2023. At this time, any workflow that still utilizes these commands will fail. See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.

GitHub have not finalized a date for deprecating node12 yet but have indicated that this will be summer 2023. So it is advised to switch to node16 asap. See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

If you need any help, please reach out to us in #team-rel-eng.

**Comment by marcboudreau** [comment]
The usage of those deprecated elements appear to come from the hashicorp/security-scanner repository. I've reached out to the team overseeing this repository for confirmation.

**Comment by tbehling** [comment]
There's a proposed PR to bump the GitHub Actions versions in https://github.com/hashicorp/vault/pull/20728

cc @marcboudreau

**Comment by marcboudreau** [comment]
Thanks @tbehling , I saw that and reviewed it. I'm going to go ahead and close this issue as resolved now since I was able to confirm that the `::set-output` and `::save-state` commands are no longer being used (Ref: https://github.com/hashicorp/vault/actions/runs/5082903354 ) and those are the ones with the looming deadline.
