### ISSUE TITLE
Testing Vault - Test Core doesn't support approle

### ISSUE THREAD

**Issue by bcokert** [hashicorp/vault#2064]
I'm trying to test our system, which uses vaults go client to drive vault.

I'm making use of the vault.TestCoreUnsealed(t) helper to create a fake vault system. For the most part this works, but I've been unable to get it to use the approle auth backend. Here's how I'm constructing my test:

```
	core, _, rootToken := vault.TestCoreUnsealed(t)
	ln, address := http.TestServer(t, core)
	defer ln.Close()

	vaultClient, _ := api.NewClient(api.DefaultConfig())
	vaultClient.SetAddress(address)
	vaultClient.SetToken(rootToken)

	// Approle setup
	_, err := vaultClient.Logical().Write("sys/auth/approle", map[string]interface{}{
		"type": "appRole",
	})
	if err != nil {
		t.Fatalf("Failed to create approle backend for test: (%s)", err.Error())
	}
        ... // It fails on the above check
```

And the output of the error is:
```
client_test.go:290: Failed to create approle backend for test: (Error making API request.

URL: PUT http://127.0.0.1:50775/v1/sys/auth/approle
Code: 400. Errors:

* unknown backend type: appRole)
```

I've verified that I'm on the latest version of vault in my repo (commit ebf4318).

Edit - We are using approle in our dev environment, and using the same vaultClient to login there where things are working. It's specifically the test core that causes the issue.

**Comment by jefferai** [comment]
TestCoreUnsealed doesn't create a core with many backends and it's not flexible. It's not meant for this kind of use.

We don't officially have a test function to use in this way, so I need to warn you that things may change at any time.

That said out of what's there now you should use TestCluster at https://github.com/hashicorp/vault/blob/master/vault/testing.go#L448 -- it gives you a real three-node cluster including HTTP listener with TLS. You can pass in the backend factories you want in `base.CredentialBackends`, including the approle backend factory.
