### ISSUE TITLE
replace  command by curl

### ISSUE THREAD

**Issue by Jwy-jump** [hashicorp/vault#20672]
`vault write -format=json test/root/sign-intermediate csr=@pki_intermediate.csr \
        format=pem_bundle ttl="43800h" \
        | jq -r '.data.certificate' > intermediate.cert.pem`

If I run it with curl, how can I replace this command？right?

`curl -X POST -H "Content-Type: application/json" -H "X-Vault-Request: true" -H "X-Vault-Token: hvs.******" http://127.0.0.1:8200/v1/test/root/sign-intermediate --data @pki_intermediate.csr | jq -r '.data.certificate' | sed 's/\\n/\n/g' > certificate.crt`

**Comment by maxb** [comment]
What do you mean by "override" ?

**Comment by Jwy-jump** [comment]
@maxb  replace , not override,thanks
