### ISSUE TITLE
Cert subject field is Incomplete

### ISSUE THREAD

**Issue by Jwy-jump** [hashicorp/vault#20719]
When using vault to issue a certificate, it is found that the certificate only displays CN information and does not display other subject information. 
```
`openssl req -new   -key private.key   -out req1.csr -subj "/C=CN/ST=London/L=London/O=example/OU=Personal/CN=we/emailAddress=we.com"
vault write -format=json pki/root/sign-intermediate csr=@req1.csr  format=pem_bundle ttl="43800h" | jq -r '.data.certificate' > intermediate.cert.pem


openssl x509 -in intermediate.cert.pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            6f:80:31:ab:80:e4:a6:29:96:56:2d:0d:de:c6:3e:42:43:45:14:43
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = dc1.consul
        Validity
            Not Before: May 23 02:22:30 2023 GMT
            Not After : May 21 02:23:00 2028 GMT
        Subject: CN = we
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:ac:d5:86:22:9d:ac:3c:72:6b:26:0f:af:e3:b8:
                    0d:66:06:9c:fb:18:d1:a2:75:7f:7e:cf:4c:c5:d9:
                    b8:7f:ab:58:e4:ac:6d:95:79:a5:3b:95:a3:1d:91:
                    17:93:bb:d9:e6:eb:65:87:46:6e:50:f0:cc:da:50:
                    75:af:62:53:df:19:8c:62:6f:86:c7:22:e1:d2:ce:
                    44:64:eb:6a:f7:8e:d7:bc:09:9b:bf:82:73:af:0d:
                    b6:cb:31:e6:1d:69:b9:47:f9:e0:82:40:d3:83:93:
                    56:fb:04:09:1f:de:6a:9f:33:6c:6f:9c:17:cd:68:
                    ef:1a:2f:6c:28:46:50:21:47:0b:fb:55:e7:57:a9:
                    3a:5c:1f:62:81:f0:d5:53:fe:f0:66:f0:24:b0:3e:
                    e9:4c:55:65:78:ac:c6:23:f0:f1:ce:f4:30:03:42:
                    61:94:44:d9:cf:1f:b0:0f:5f:15:04:79:29:42:f6:
                    c7:02:c0:02:86:a0:d3:2f:60:8e:67:54:81:86:ae:
                    6e:4d:40:d7:69:cb:d0:20:29:d9:81:f5:96:c7:5d:
                    89:c3:89:24:3b:11:c6:8d:98:42:86:d3:86:55:44:
                    4a:45:8e:b5:db:a7:99:db:f1:2a:6e:9d:7b:65:10:
                    9b:f9:77:11:52:2c:9b:19:a3:49:7f:5f:cc:d7:9b:
                    a7:c5
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Key Identifier: 
                FD:D2:82:0F:95:49:29:4E:9C:39:11:84:9C:12:DE:9C:28:0C:7A:02
            X509v3 Authority Key Identifier: 
                keyid:94:57:80:7B:69:78:D4:DE:BB:0F:42:72:2C:E1:BD:44:C8:D1:08:0B

            Authority Information Access: 
                CA Issuers - URI:http://127.0.0.1:8200/v1/pki/ca

            X509v3 Subject Alternative Name: 
                DNS:we
            X509v3 CRL Distribution Points: 

                Full Name:
                  URI:http://127.0.0.1:8200/v1/pki/crl

    Signature Algorithm: sha256WithRSAEncryption
```
subject only show CN?

**Comment by cipherboy** [comment]
Ah, I see this is a new issue.

I'll copy my reply from #17313:

> `C`, `ST`, `L`, `O`, `OU` are not the common name and thus won't be copied over. `use_csr_common_name=true` strictly uses the `Subject/CN` field that you should seen should be copied over... Other than you overriding it explicitly on the CLI with `common_name` perhaps (drop that and it definitely should be).
> 
> If you want to sign CSRs as-is, including O/OU information, right now your best approach is using `sign-verbatim`, which requires pre-verification of the CSR. 
> 
> The [Hashicorp Vault Discuss](https://discuss.hashicorp.com/c/vault/30/) forum might be a better place for this discussion, tbh.

We have road map items to help this, but note that it'll require building an external integration.

**Comment by maxb** [comment]
Hi @cipherboy ,

Whilst your response makes perfect sense if it were applied to the regular `pki/sign/:role` endpoint, @Jwy-jump is asking about the `pki/root/sign-intermediate` endpoint, for which different concerns apply.

I think in this case the answer is that @Jwy-jump needs to take notice of the `use_csr_values` option for this endpoint.

**Comment by cipherboy** [comment]
@maxb Ah, my bad. The post on the other issue (which I saw first) used the `/issue` endpoint, which also wouldn't work for the reason that it ignores the `csr` endpoint:

> ```
> vault write -format=json test/issue/test_server common_name="example.com" csr=@req1.csr format=pem ttl="8660h" | jq -r '.data.certificate' > certificate.crt
> ```

I saw `sign` on this one and apparently stopped reading. :o

@Jwy-jump, yes, I think @maxb is correct here. If you're trying to create an Intermediate CA, please pass `use_csr_values=true`. If you're trying to create a leaf certificate, `sign-verbatim` is the way to go here.

**Comment by Jwy-jump** [comment]
And I  try the sign-verbatim, It also not contain C, ST, L, O, OU informations

**Comment by Jwy-jump** [comment]
@cipherboy Thanks a lot , the questions solved!
