### ISSUE TITLE
Vault does not persist data if consul and vault is shutdown and restarted

### ISSUE THREAD

**Issue by hiteshlinge** [hashicorp/vault#2071]
Hi,

I have observe few things, once I initialized my vault and add secrets to it and again if I bring it down and start again, some times it tells me to  initialize the vault again or some times the secrets which I had added is not present. So the question how can I read the data which I had added before shutting down vault.

**Comment by jippi** [comment]
are you running both in `-dev` mode or can you please provide your configuration files

**Comment by hiteshlinge** [comment]
vault config file
============================
backend "consul" {
  address = "127.0.0.1:8500"
  path = "tmp/vault/"
 // scheme defaults to "http" (suitable for loopback and UNIX sockets), but
 // should be "https" when Consul exists on a remote node (a non-standard
 // deployment).  All decryption happen within Vault so this value does not
 // change Vault's Threat Model.
  scheme = "http"
  redirect_addr = "https://127.0.0.1:8200"
  VAULT_ADDR = "https://127.0.0.1:8200"
}

listener "tcp" {
// address = "0.0.0.0:8200"
 tls_disable = "0"
 tls_cert_file = "/opt/consul/ssl/server.cer"
 tls_key_file = "/opt/consul/ssl/server.key"
}

consul config file and command which I use to start consul:
./consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul/data -config-file consul-config1.hcl 

 and consule config file
{
  "ca_file": "/opt/consul/ssl/demo-root.cer",
  "cert_file": "/opt/consul/ssl/server.cer",
  "key_file": "/opt/consul/ssl/server.key",
  "verify_incoming":true,
  "verify_outgoing":true
}

**Comment by jefferai** [comment]
Your Consul data dir is in `/tmp`. It's probably being blown away at regular intervals or startup/shutdown.
