### ISSUE TITLE
Generic documentation doesn't mention that it doesn't support leases

### ISSUE THREAD

**Issue by bironran** [hashicorp/vault#2072]
A doc bug - generic documentation doesn't mention that leases are not really supported. I've spent half a day "testing" how leases work and how recovery can be done just to find out that leases don't really function in generic.

This was mentioned off-hand here as well: https://github.com/hashicorp/vault/issues/877

**Comment by jefferai** [comment]
The documentation is pretty explicit:

```When data is returned, the lease_duration field (in the API JSON) or refresh_interval field (on the CLI) gives a hint as to how often a reader should look for a new value. This comes from the value of the default_lease_ttl set on the mount, or the system value.

There is one piece of special data handling: if a ttl key is provided, it will be treated as normal data, but on read the backend will attempt to parse it as a duration (either as a string like 1h or an integer number of seconds like 3600). If successful, the backend will use this value in place of the normal lease_duration. However, the given value will also still be returned exactly as specified, so you are free to use that key in any way that you like if it fits your input data.```

What's the disconnect here?

**Comment by bironran** [comment]
@jefferai the issue isn't about the API, but about the generic backend not actually expiring any secrets. At first I thought it was a bug or an unimplemented feature, but upon reading the issue I mentioned above, I found out this is by design.
For what I'm considering Vault, my primary use case centers around the generic backend, hence that piece of information on the generic backend doc page could have saved me a few hours of experimenting.

**Comment by ndobson** [comment]
I agree, I was under the impression that all secrets had a lease that expired per this statement in the docs

> With every secret and authentication token, Vault creates a lease: metadata containing information such as a time duration, renewability, and more.

It was confusing for me too.

**Comment by sworisbreathing** [comment]
Not only that, but the documentation at https://www.vaultproject.io/docs/concepts/lease.html still states:

> ...[C]onsumers of secrets need to check in with Vault routinely to either renew the lease (if allowed) or request a replacement secret. This makes the Vault audit logs more valuable and also makes key rolling a lot easier.

> All secrets in Vault are required to have a lease. Even if the data is meant to be valid for eternity, a lease is required to force the consumer to check in routinely.

and there's no mention of the generic backend not supporting leases on that page.

**Comment by lifeofguenter** [comment]
does that mean generic can be used as general k/v storage without expiration, correct?

**Comment by vishalnayak** [comment]
@lifeofguenter Yes, you can use it as a k/v store without expiration of the entries. You can choose to make use of `refresh_interval` which Jeff has linked above.

**Comment by jefferai** [comment]
This was updated in the docs:

> The backend never removes data on its own; the ttl key is merely advisory.
