### ISSUE TITLE
How to build the hashicorp/vault Docker Image

### ISSUE THREAD

**Issue by amouat** [hashicorp/vault#20734]
I'd like to know how the Docker images are built, so we can recreate them locally.

The [hashicorp/vault](https://hub.docker.com/r/hashicorp/vault) Docker image is presumably built from this [Dockerfile](https://github.com/hashicorp/vault/blob/main/Dockerfile). But the Dockerfile just copies the binary in - it has to be already built. Is it built with `make ci-build-ui`? Could we know the exact flags so that we can recreate it locally?

It would be helpful for provenance etc.

**Comment by ncabatoff** [comment]
Hi @amouat,

You've found the correct Dockerfile for the `hashicorp/vault` image. There's a lot of stuff going on in build.yml before build-docker gets invoked that will be hard for me to summarize, see https://github.com/hashicorp/vault/blob/main/.github/workflows/build.yml#L108 for the binary build step you're asking about.  Here's an example invocation: https://github.com/hashicorp/vault/actions/runs/5056135192/jobs/9073253848

After we do `make ci-build-ui` we run `make ci-build`, which does (in the example invocation)

```
go build -v -tags ui -ldflags '-X github.com/hashicorp/vault/version.Version=1.13.3 -X github.com/hashicorp/vault/version.GitCommit=7ef9b8cd0489de76c45f3569c2863529f1361247 -X github.com/hashicorp/vault/version.BuildDate=2023-05-23T12:23:46Z' -o dist/
```
