### ISSUE TITLE
Error renewing approle secret-id?

### ISSUE THREAD

**Issue by russroy** [hashicorp/vault#2078]
Is this a bug or a cockpit error?

I'm assuming here that secret-id's generated from the AppRole backend are the functional equivalent of other Vault auth tokens and are treated similarly when renewing.

/ # vault write auth/approle/role/testrole period=20m
Success! Data written to: auth/approle/role/testrole

/ # vault write -f auth/approle/role/testrole/secret-id

Key               Value

---               -----

secret_id         5fb77b62-6f13-6c47-71b6-0404d9374063

secret_id_accessor	dba393e5-221b-8401-28e0-e806e49b07d1

/ # vault token-renew 5fb77b62-6f13-6c47-71b6-0404d9374063

Error renewing token: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/token/renew

Code: 400. Errors:

* token not found

/ #

**Comment by DennyLoko** [comment]
Hello @russroy,

Before you use the `token-renew`, you have to generate the real auth token:
```
$ vault write auth/approle/login role_id=d3be4eb8-97b6-9aa0-3833-c586e7d078ee secret_id=4f0b0f11-4592-db25-6769-af135c135b3d
Key            	Value
---            	-----
token          	2dcb66a1-6a2b-3f95-2623-7756034c7e8f
token_accessor 	c0e6de92-d90e-fab3-4a83-913a013737a5
token_duration 	1m0s
token_renewable	true
token_policies 	[default]
```

And then, to renew use:
```
$ vault token-renew 2dcb66a1-6a2b-3f95-2623-7756034c7e8f
Key            	Value
---            	-----
token          	2dcb66a1-6a2b-3f95-2623-7756034c7e8f
token_accessor 	c0e6de92-d90e-fab3-4a83-913a013737a5
token_duration 	1m0s
token_renewable	true
token_policies 	[default]
```
