### ISSUE TITLE
CLI/HTTP inconsistency, "app-id", "user-id" vs "app_id", "user_id"

### ISSUE THREAD

**Issue by ajwm** [hashicorp/vault#208]
There's more detail in the mailing list, but basically where the CLI uses "app-id" and "user-id" to create the app and user ids,  the HTTP authentication (at least) is looking for "app_id" and "user_id" in the  JSON data (but app-id in the path).   It doesn't return an error with the wrong keys, just an invalid key and an empty policy list (and, it turns out, the sha1 sum for a null string).

This inconsistency took me a while to figure out why my app-id/user-id keys weren't working.

Might I suggest allowing the hyphen in the JSON data but perhaps also allowing underscore for backward compatibility.

Thanks.

**Comment by armon** [comment]
Fixed in https://github.com/hashicorp/vault/commit/f1683f907fe2051d7f5b1bb0864ff035776ad6cd and https://github.com/hashicorp/vault/commit/9dc38923fe1e233a692424b121bc9d0c36842052. Thanks!
