### ISSUE TITLE
Error initializing dev mode

### ISSUE THREAD

**Issue by dpnl87** [hashicorp/vault#2080]
While trying to start a dev server on OSX I get the following error:

```
==> Vault server configuration:

                 Backend: inmem
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "", tls: "disabled")
               Log Level: debug
                   Mlock: supported: true, enabled: false
                 Version: Vault v0.6.2

Error initializing dev mode: At 1:18: nested object expected: LBRACE got: ASSIGN
```

A similar issue occurs when trying to connect to a remote vault instance
```
❯ vault status
Error initializing client: At 1:18: nested object expected: LBRACE got: ASSIGN
```

Running a brew install with the latest version
```
 ❯ vault -v
Vault v0.6.2

❯ which vault
/usr/local/bin/vault
```

**Comment by BenjaminFarley** [comment]
Hi, 
What command are you running to run in dev mode?
Are you also specifying any additional configuration along with it?

**Comment by dpnl87** [comment]
@BenjaminFarley I do not specify any configuration.
```
 ❯ vault server -dev
==> Vault server configuration:

                 Backend: inmem
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
                 Version: Vault v0.6.2

Error initializing dev mode: At 1:18: nested object expected: LBRACE got: ASSIGN
```

**Comment by jefferai** [comment]
Do you get the same issue with the official binary?

**Comment by dpnl87** [comment]
Both ( the official and the Homebrew one ) give the exact same error.

**Comment by jefferai** [comment]
Do you have any VAULT related items in your env vars? I've never seen anything like this and I can't reproduce it. I wonder if it's loading some malformed config file from somewhere and you're not realizing it.

**Comment by dpnl87** [comment]
@jefferai It doen't look like it.

My env
```
 ❯ env
BROWSER=open
DISPLAY=/private/tmp/com.apple.launchd.bCE0RiIqUW/org.macosforge.xquartz:0
EDITOR=vim
HOME=/Users/dpaulus
ITERM_PROFILE=Default
ITERM_SESSION_ID=w0t0p1:902C6059-161E-4E76-9A4D-43F6445B36B1
LANG=en_US.UTF-8
LC_CTYPE=UTF-8
LESS=-F -g -i -M -R -S -w -X -z-4
LOGNAME=dpaulus
OLDPWD=/Users/dpaulus
PAGER=less
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin
PWD=/Users/dpaulus
SHELL=/bin/zsh
SHLVL=2
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.pCo05e1F2y/Listeners
TERM=screen-256color
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.0.20161103-nightly
TERM_SESSION_ID=w0t0p1:902C6059-161E-4E76-9A4D-43F6445B36B1
TMPDIR=/var/folders/yd/psjqzq5s7634n8s_ptcdd1tr0000gn/T/
TMUX=/private/tmp/tmux-501/default,87539,0
TMUX_PANE=%1
USER=dpaulus
VISUAL=vim
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_=/usr/bin/env
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
LSCOLORS=exfxcxdxbxGxDxabagacad
LS_COLORS=di=34:ln=35:so=32:pi=33:ex=31:bd=36;01:cd=33;01:su=31;40;07:sg=36;40;07:tw=32;40;07:ow=33;40;07:
GREP_COLOR=37;45
GREP_COLORS=mt=37;45
```

The `/usr/local/go/bin` in my path triggered me, but it contains only go binaries
```
❯ ls /usr/local/go/bin
go    godoc gofmt

 ❯ go version
go version go1.6.2 darwin/amd64
```

**Comment by jefferai** [comment]
I honestly don't know. I just downloaded the official binary and when I run `vault server -dev` it works as you'd expect.

Any chance this machine is running some kind of security software? We've seen really weird issues pop up with software that does things like intercept the runtime to try to run scans.

**Comment by dpnl87** [comment]
The only thing security related that runs on my machine is a virus scanner from Esset (NOD32).

I've also tried to compile my own binary only to find the same issue:
```
❯ brew install golang 
==> Summary
/usr/local/Cellar/go/1.7.3: 6,438 files, 250.6M

 ❯ go version
go version go1.7.3 darwin/amd64

❯ go get github.com/hashicorp/vault 

❯ make bootstrap
Installing github.com/mitchellh/gox

❯ make dev
go generate
==> Removing old directory...
==> Building...
Number of parallel builds: 7
-->    darwin/amd64: github.com/hashicorp/vault
==> Results:
total 97832
-rwxr-xr-x  1 dpaulus  staff    48M Nov 11 22:11 vault

 ❯ ./vault version
Vault v0.6.2

 ❯ ./vault server -dev 
==> Vault server configuration:

                 Backend: inmem
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
                 Version: Vault v0.6.2

Error initializing dev mode: At 1:18: nested object expected: LBRACE got: ASSIGN
```

**Comment by jefferai** [comment]
Unfortunately I don't currently have any ideas. I have never seen this on any platform (including OSX) and cannot reproduce it myself with either the 0.6.2 binary or self-compiled. You may want to try disabling the virus scanner (really, we've seen weird things) or trying a coworker's machine to see if it behaves the same way.

**Comment by dpnl87** [comment]
I'm currently using a Centos 7 VM with Vault which works like a charm. 

I have no idea why my dev machine has issues with running the Vault binary. For now I'll close this issue as it seems to be a issue related to my machine only. If someday I'll find out what it is I'll update this ticket.

**Comment by frodopwns** [comment]
I have this issue on my macbook...still digging in but I will report back here if I figure anything out.

```
➜  Downloads ./vault server -dev
==> Vault server configuration:

                 Backend: inmem
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
                 Version: Vault v0.6.1

Error initializing dev mode: At 3:5: expected: IDENT | STRING | ASSIGN | LBRACE got: NUMBER
```

**Comment by jbehling** [comment]
i have this same issue, OSX with official binary. Any ideas?

**Comment by jefferai** [comment]
Unfortunately, I don't. None of the OSX machines the dev team has available can reproduce this.

I'd be interested in knowing if this is reproducible with 0.6.4, just due to dependency updates. Also whether someone with a machine that has this problem is able to build dev from master, and how that behaves (note: requires Go 1.8 which is only in RC so far, but that's also a good data point).

Finally, we're all on the most recent version of OSX/macOS...do these happen to be older versions where you're seeing this error?

**Comment by jefferai** [comment]
@frodopwns @jbehling Do either of you have any security software running?

**Comment by jbehling** [comment]
i'm on OSX 10.12.1

```vault -version
Vault v0.6.4 ('f4adc7fa960ed8e828f94bc6785bcdbae8d1b263')
```
no security software running.

**Comment by jbehling** [comment]
my error is slightly different than the one posted above
```
vault server -dev
==> Vault server configuration:

                 Backend: inmem
                     Cgo: disabled
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "", tls: "disabled")
               Log Level: info
                   Mlock: supported: false, enabled: false
                 Version: Vault v0.6.4
             Version Sha: f4adc7fa960ed8e828f94bc6785bcdbae8d1b263

Error initializing dev mode: At 1:6: expected: IDENT | STRING | ASSIGN | LBRACE got: ADD
```

**Comment by jbehling** [comment]
ok, i've rebuilt this on go 1.8, same error
```bin/vault server -dev
==> Vault server configuration:

                 Backend: inmem
                     Cgo: disabled
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "", tls: "disabled")
               Log Level: info
                   Mlock: supported: false, enabled: false
                 Version: Vault v0.6.4
             Version Sha: 15993a9934b9d1d0d0ebc79b74a444b21be30cfb

Error initializing dev mode: At 1:6: expected: IDENT | STRING | ASSIGN | LBRACE got: ADD
```

**Comment by briankassouf** [comment]
@jbehling Do you have any vault specific environment variables, or do you have a file located at `~/.vault`?

**Comment by briankassouf** [comment]
I was just able to reproduce this by placing a malformed .hcl file at `~/.vault`

**Comment by jbehling** [comment]
That was it! man, it would be helpful to have a better error there. I'm not sure if it's a convention that other people use but my `.vault` file is a password key for Ansible vault.. but didn't even think of that being the issue.
