### ISSUE TITLE
Include a default built-in CA for certificates used by vault?

### ISSUE THREAD

**Issue by F21** [hashicorp/vault#2081]
I am wondering how feasible it would be for vault to have a default built-in CA. This would allow vault to start automatically with TLS enabled (without having to create a CA and generate certificates manually). Because of tight integration, vault would also be able to renew its own certificates.

This would make it much more easier to automate vault and run it in a cluster using something like kubernetes or nomad.

**Comment by jefferai** [comment]
This is kind of an ongoing discussion internally but we haven't landed one way or the other.

**Comment by raoofm** [comment]
@jefferai Is this finalized yet?

**Comment by jefferai** [comment]
No, it's not. There are a lot of potential gotchas with doing this, from a security perspective, and we didn't have any good answers at the time so discussion kind of stopped.
