### ISSUE TITLE
Add auth prefix automatically to vault auth move command

### ISSUE THREAD

**Issue by cwchristerw** [hashicorp/vault#20844]
**Is your feature request related to a problem? Please describe.**
When I tried to move authentication method from path "old-path" to "new-path", it failed because I need to add `auth/` prefix manually to both paths.

`vault auth move auth/old-path/ auth/new-path/`
`vault auth move ns1/auth/old-path/ ns1/auth/new-path/`

https://developer.hashicorp.com/vault/docs/commands/auth/move

**Describe the solution you'd like**
I want to add feature to add `auth/` prefix to path when you don't specify any namespace.

`vault auth move old-path/ new-path/`
`vault auth move ns1/old-path/ ns1/new-path/`

**Describe alternatives you've considered**
There is no need for alternative because it already exists.

**Explain any additional use-cases**
-

**Additional context**
-

**Comment by maxb** [comment]
> I want to add feature to add `auth/` prefix to path when you don't specify any namespace.

Can you elaborate on why you want this?

I can see that in some ways it would increase consistency of parameters with e.g. `vault auth disable`.

However, I can also see two big reasons that argue against this change:

1) Experience with the KVv2 secrets engine has shown that automatically inserted path segments cause significant configuration for some users.

2) If Vault Enterprise Namespaces are in use, I think there's a scenario where this UI proposal results in ambiguity!

Scenario:

* An auth method exists in the root namespace at path `auth/orange/banana/`
* A namespace exists at path `orange/`
* Within the `orange/` namespace, an auth method exists at fully qualified path `orange/auth/banana/`
* User invokes proposed new command `vault auth move orange/banana/ purple/apple/`

**Ambiguity!** Which auth method was the user attempting to move? `auth/orange/banana/` or `orange/auth/banana/` ?!

I don't work for HashiCorp, and no longer work for a company with a Vault Enterprise subscription, so I'm only working on how I remember Vault namespaces behaving, and could be wrong ... but I'm pretty sure this is a real problem that could occur.

**Comment by cwchristerw** [comment]
I agree it's confusing when using namespaces, closing issue.
