### ISSUE TITLE
log_level option through configuration file.

### ISSUE THREAD

**Issue by vijaybandari** [hashicorp/vault#2090]
It would be nice if we have this option through configuration file same as [consul](https://www.consul.io/docs/agent/options.html#log_level)

**Comment by mfischer-zd** [comment]
Is the problem that you're getting too many logs, or too few?  Have you considered connecting Vault's standard output to a log filter before writing to disk?

**Comment by vijaybandari** [comment]
We are having issues with vault & consul, and sometimes they are going down & we don't see much information on the logs to find the root cause. So we have to change our systemd service file to add a log-level command line argument, but as our servers are maintained by chef they get overridden on the next chef run. Then I found log_level configuration on consul and thought it would be nice to provide same option for vault too.

**Comment by naunga** [comment]
Would it be better to do this via the API (much like CORS) so that you could adjust the log level without having to restart the server?

**Comment by vijaybandari** [comment]
@naunga - That would be great :)

**Comment by catsby** [comment]
Hello - this is a rather old issue at this point, and Vault now offers a `log_level` configuration flag as well as live configuration reloading with `SIGHUP` signals, so I'm going to close this. Thanks!

- https://www.vaultproject.io/docs/configuration/index.html
- https://www.vaultproject.io/guides/operations/plugin-backends#setup-vault
