### ISSUE TITLE
Vault LDAP Auth Method vulnerable to account fuzzing via response.

### ISSUE THREAD

**Issue by ipaqmaster** [hashicorp/vault#20923]
**Is your feature request related to a problem? Please describe.**
```
$ curl -XPOST 'https://vault.localhost.localdomain/v1/auth/ldap/login/fakeUser' -d 'password=fakePassword'
{"errors":["ldap operation failed: failed to bind as user"]}
```
Pretty clear json error text for a failed bind to a user that doesn't exist and a fake password.

```
$ curl -XPOST 'https://vault.localhost.localdomain/v1/auth/ldap/login/realUser' -d 'password=fakePassword'
```
204 response code with a blank body for a real user account that exists, but the same fake incorrect password. Identifying a valid LDAP account.

In /ui/ you're given additional error text: `Authentication failed: TypeError: Cannot read properties of undefined (reading 'auth')`. I'm guessing the javascript for `/ui/vault/auth` doesn't like receiving the blank body 204 response.

These responses can be used to scan for valid accounts via a Vault cluster's LDAP authentication endpoint - against whichever OU a Vault cluster is scoped to for it. It's like a `VRFY` command for Vault.

**Describe the solution you'd like**

Because the auth/ endpoint typically deals with unauthenticated remotes Vault shouldn't be handing out any hints. It would be much better that when an Auth Method fails for an unauthenticated remote Vault should just throw something along the lines of `{"errors":["Access Denied"]}` as the error text value - providing no further detail and leaving it to administrators to aid a real staff member if they were actually struggling to gain access.

In relevant context, the [User Lockout](https://developer.hashicorp.com/vault/docs/concepts/user-lockout) feature exists and is enabled by default with good defaults. Upon discovering a valid user account an attacker would only have a maximum of 5 brute force attempts before the account is locked out for 15 minutes, every 15 minutes. Leaving up to only 480 attempts per day which would be useless for traditional brute force attempts but workable for a sophisticated and targeted attack.

While this is great for preventing an online compromise and the lockout doesn't impact the existing token session of a user - Being able to disclose accounts like this can be abused for a Denial of Service scenario where an attacker has successfully guessed the username formula of a company and discovered some valid (At least bindable) LDAP accounts. Such an actor would be able to actively prevent those discovered users from reauthenticating after their token expires. But at least the source would be obvious in webserver and reverse proxy logs for a swift firewall drop rule.

While this would still be possible if an attacker already knows the account names they wish to attack - It would become infeasible to build a list of valid accounts from nothing if Vault's invalid credential response is masked with a blunt "Access Denied" error even on valid username attempts.

**Describe alternatives you've considered**

Not many other thoughts. Just don't want Vault to disclose valid ldap user accounts by accident. Having vault be vague about the error reason would be a great improvement but it would also probably be a good idea to sprinkle in some micro-sleeps even for valid account attempts to help prevent attackers guessing valid/invalid users based on the time it takes Vault to respond with the error code.

**Explain any additional use-cases**

* Preventing a vault server from being enumerated for valid ldap accounts via that Auth Method - where an attacker can start brute forcing with no information
* Prevent Denial of Service attacks against staff accounts discovered via the above method

**Additional context**

Another thought - Should Vault's User Lockout feature go for the remote IP address responsible for the lockout rather than potentially locking innocent user accounts?

With reverse proxying it would become important to make sure the reverse proxy passes through the correct remote host IP for such a feature to accurately ban an attacker rather than accidentally banning the reverse proxy and locking vault out for everybody.

**Comment by mcollao-hc** [comment]
Hello -- thanks for the writeup.

We'll look into it internally to make the LDAP response more generic for API responses and in the UI to prevent enumeration attacks. Regarding your suggestion to prevent enumeration via response timing, it's a good idea but would not be a priority for us right now. 

We've been looking into IP rate limiting as well, but have no timetable on when it will be available.

**Comment by ipaqmaster** [comment]
Morning,

I appreciate the serious response and am glad it's being looked into. The response timing is a bit more of a niche and targeted issue so I can understand not taking that on immediately. I may peak into things myself and submit a pull request if I come up with anything worthwhile.

Thanks.

**Comment by mcollao-hc** [comment]
Hey @ipaqmaster, looks like this on track to be fixed in Vault 1.15. If you can, take a look at https://github.com/hashicorp/vault/pull/21282 and let me know if you have any issues with that approach.

Also, we're considering registering a CVE for this issue. Would you like to be credited in the advisory, and if so, under what name?

**Comment by ipaqmaster** [comment]
I appreciate the transparency and #21282 looks like an appropriate resolution for the UI responses.

If I appear in a CVE my full name is fine: `Jared Johnstone`

**Comment by cwchristerw** [comment]
I'm looking forward to new Vault release 1.14.x

**Comment by mcollao-hc** [comment]
Hi @ipaqmaster , the fix was included in the latest Vault release. You can read more about it here, https://discuss.hashicorp.com/t/hcsec-2023-24-vaults-ldap-auth-method-allows-for-user-enumeration/56714.
