### ISSUE TITLE
Add link to new Community Library (Haskell)

### ISSUE THREAD

**Issue by bitc** [hashicorp/vault#2095]
There is a new Vault library for Haskell (authored by yours truly). The project home is: https://hackage.haskell.org/package/vault-tool

Would be cool if it could be added to the list at: https://www.vaultproject.io/docs/http/libraries.html

**Comment by bitc** [comment]
I see that several of the libraries have an "install command". The install command for this Haskell library would be:

    cabal install vault-tool

**Comment by BenjaminFarley** [comment]
Hey, It's a quick update. So I've created a pull request for the change.
