### ISSUE TITLE
Support globs in the middle of paths for policies

### ISSUE THREAD

**Issue by F21** [hashicorp/vault#2098]
I am building a service that is only allowed to fetch `secret_id`s using the AppRole auth backend.

Currently, globe are only allowed at the end of the path, which means I can't assign a policy like the following to the service:

```hcl
path "auth/approle/role/*/secret-id" {
  policy = "create"
}
```

This means that I'll have to explicitly add each role to the policy (which has more management overhead):

```hcl
path "auth/approle/role/role1/secret-id" {
  policy = "create"
}

path "auth/approle/role/role2/secret-id" {
  policy = "create"
}

path "auth/approle/role/role3/secret-id" {
  policy = "create"
}
```

It would be nice if globs in the middle of paths are supported, so that this is possible.

**Comment by jefferai** [comment]
This has been brought up many times on the mailing list, but the short answer is that currently there are no plans to support this. We use longest prefix matching and adding in wildcards in the middle introduces a lot of extra processing overhead.

It's more likely that once we get some planned things added into Vault's core, we'll support some templating based on token parameters.
