### ISSUE TITLE
Securely Store Auth Token

### ISSUE THREAD

**Issue by bigmyx** [hashicorp/vault#210]
Hi,
Any suggestion on how to store a Vault API auth token on the client machine ?
(plain text on the file system is not an option)
Thanks !

**Comment by sethvargo** [comment]
Hi @bigmyx 

I usually recommend an environment variable. Does that work for you?

**Comment by mitchellh** [comment]
We actually built the token helper system directly for this. It is modeled exactly after Git's credential helper system (google, don't have it on hand sorry). Therefore, you can use anything that adheres to that protocol to store it wherever you want. For example with v0.2 we're going to ship a keychain store for OS X machines by default.
