### ISSUE TITLE
When utilizing the PKI secrets engine, allow for the mTLS auth method to pull in the cert details automatically for authentication

### ISSUE THREAD

**Issue by Esity** [hashicorp/vault#21023]
When a group manages their certificates via Vault PKI Engine(https://developer.hashicorp.com/vault/docs/secrets/pki)

There should be an easy options to allow for the mTLS auth method to use the certificates stored in the PKI engine for authentication. In the current state, the certificate has to be generated, and then manually moved over to the mTLS auth options. This makes it harder to automate and redundant while increasing the odds of the certificates not matching
https://developer.hashicorp.com/vault/docs/auth/cert

**Comment by cipherboy** [comment]
@Esity Sadly I'm not sure this is a feasible approach. Vault lacks an inter-plugin communication method and its unlikely we'll see such any time soon as it would be a significant investment both from a security/design perspective but also from an implementation perspective. Even with such cross-mount (and potentially, cross-cluster) mechanisms, you'd still need to indicate to cert auth which issuers it should trust/validate against, which is little different than the current mechanism (other than ensuring the value gets copied over correctly).

Cert auth method should not be used with individual leaf certificates, but instead used with root/intermediate CAs in the mount. Using something like TFVP could perhaps solve this issue, by ensuring proper construction of cert auth method from Vault PKI CAs.

n.b.: the wording here:

> the certificate has to be generated, and then manually moved over to the mTLS auth options. 

makes me think that perhaps leaf certs are being directly trusted in Cert auth method, which I'd strongly caution against as a best practice.

**Comment by hsimon-hashicorp** [comment]
With @cipherboy's notes here, I'm going to go ahead and close this issue now. Please feel free to re-open as needed. Thanks!
