### ISSUE TITLE
Authenticating via your container orchestration system proposal

### ISSUE THREAD

**Issue by flock3** [hashicorp/vault#2106]
Hi all

I'm having an issue with the AWS EC2 authentication method, as it is designed really for EC2 instances in the bare state, rather than for containers sitting on top of them.  The issue we have is that the nonce, can't really be a nonce; because during an EC2 instances life, it might have many containers put onto it, all of which require secrets; meaning we have to share the nonce if we want other containers to gather secrets from the vault.

My proposal is for an orchestration based authentication mechanism.

The vault could talk to the orchestration engine (Rancher in my case), and confirm that a containers ID is valid, and that it is either new, or has been restarted since it last attempted to collect secrets.

Roles could then be configured via the grouping of containers (think Pod's in kubernetes or "Stacks" in Rancher).

I would be fairly happy to give this a shot at an implementation (although my Go is not my strongest language); but I don't want to do that if the PR would never be accepted, either because the community believes that orchestration based authorisation would not work, or because there is some better solution that I'm not aware of.

Principles of this authentication mechanism security:

1. A container could only request an authentication token once, unless it has been started/modified by the container management system since the last time it attempted to authenticate.  
2. The policies that a container could receive, would directly relate to the groups of containers in which it lives (Stacks in Rancher, Pod's in Kubernetes) 

Let me know you're thoughts.

**Comment by jefferai** [comment]
> My proposal is for an orchestration based authentication mechanism.

Using the orchestration system is our recommended approach for container secrets. Nomad has built-in support in 0.5, Kubernetes work is ongoing via https://github.com/kelseyhightower/vault-controller and someone has written https://github.com/ChannelMeter/vault-gatekeeper-mesos for Mesos.

EC2 auth can be used to give the orchestration agent its initial token or to give a service a token that can be used for the service to write out secrets for applications (like Consul Template) but isn't designed for containers.
