### ISSUE TITLE
Support encrypt/decryption of multiple transit values at once

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#2107]
This came up in a conversation with @evanphx. Vault's transit backend is great, but it requires an HTTP request for each encrypt/decrypt operation. This is fine for small clusters, but for large data sets, even with derived keys, it would be fantastic if one could post a list of ciphertext/plaintext values and receive a list of the opposite back. This would significantly alleviate load on web applications (like vault-rails) which rely on Vault's transit backend to encrypt database rows.

By allowing a list of ciphertext/plaintext to be posted in a single request, the load on Vault is significantly reduced and the webapp itself will be more performant.

I talked with @armon and he believes this should not be technically challenging, but that we should impose some kind of artificial limit on the request size (he suggested 4MB) to prevent a massive request from taking up all of Vault's processing.

For backwards compatibility reasons, we should make new endpoints:

- `/transit/encrypt-list/<name>
- `/transit/decrypt-list/<name>

Unless you think it's possible to do this in a backwards compatible way using the existing paths.

A sample request:

```json
[
  {
    "plaintext": "abcd1234",
    "context": "defg==",
    "nonce": "123"
  },
  {
    "plaintext": "efgh5678",
    "context": "hijk==",
    "nonce": "456"
  }
]
```

A sample response:

```json
{
  "data": [
    {
      "ciphertext": "vault:v1:abcdefgh"
    },
    {
      "ciphertext": "vault:v1:dsfadfdh"
    }
  ]
}
```

One challenge I foresee is the handling of a single error. I'm open for discussion on whether an encryption/decryption error on a single key should taint the entire request or return something like:

```json
{
  "data": [
    {
      "success": true,
      "ciphertext": "vault:v1:abcdefgh"
    },
    {
      "success": false,
      "error": "not base64"
    }
  ]
}
```

/cc @jefferai @vishalnayak

**Comment by jefferai** [comment]
I don't have an issue with this, although I'm surprised at the load argument -- does ruby not support reusing connections/HTTP pipelines, or HTTP/2?

**Comment by sethvargo** [comment]
@jefferai Ruby doesn't, but we do use connection pooling (/cc @evanphx). The problem is that, for a reasonably-sized database, you are still making 100,000+ requests to Vault to decrypt a column, because each row is encrypted and there's no "bulk" import.

**Comment by jefferai** [comment]
I wonder if there's a bigger picture need here. We've had requests from users to do things like fetch multiple secrets at once from `generic`. Rather than build something like this into `transit` the right thing might be to make it generic -- pass in a set of requests and get a set of responses, to any part of Vault.

**Comment by sethvargo** [comment]
I'm game for that too 👍

**Comment by ekristen** [comment]
Looks like this is in a milestone already, but +1 from me too, this would improve some call flow in an app I've developed.

**Comment by jefferai** [comment]
As an update after some internal conversation, I think we're likely to add this support in transit first, then potentially later add multiple request support into Vault.

**Comment by ekristen** [comment]
+1 to transit support, that's all I'm in the market for right now, thanks @jefferai

**Comment by ruimarinho** [comment]
This would very welcomed in transit at least :)

> One challenge I foresee is the handling of a single error. I'm open for discussion on whether an encryption/decryption error on a single key should taint the entire request or return something like […]

I think that if a batch of *99/100* requests are encrypted/decrypted correctly, it would be a waste to throw all that work away due to a single failed request. Your proposal seems to be the most reasonable to me. For reference, this is exactly what [JSON-RPC 2.0](http://www.jsonrpc.org/specification#batch) does.

**Comment by jefferai** [comment]
BTW I do think that this could be done in a backwards compatible fashion with existing paths. Those paths only take minimal parameters, so we can decode the data into an object that both contains the array and the existing fields, and figure out what to do based on which of those (array, fields, both) are filled in.

**Comment by harshtg** [comment]
Hi,
Am trying to map multi-value for the single key using vault transit. When I tried "/transit/encrypt-list/" service with the corresponding record throws "json: cannot unmarshal array into Go value of type map[string]interface {}" this error. Could anyone please help me on this. 

Regards,
Harsh.
