### ISSUE TITLE
Trying to create a PKI role stops typing after a single character. Can be worked around with ctrl+v pasting exactly what you were going to type.

### ISSUE THREAD

**Issue by ipaqmaster** [hashicorp/vault#21097]
**Describe the bug**

Creating a PKI is fine in /ui/, but when you go to create a role and begin typing in a `Role name` you can only type out a single character

**To Reproduce**
1. Run `vault server -dev`
2. Visit [http://127.0.0.1:8200/ui/](http://127.0.0.1:8200/ui/)
3. Make a PKI with the default name
4. Go to create a role
5. Type anything for the Role name
6. Watch as you can't type more than one character.

**Expected behavior**
The ability to make pki roles of more than one character in length

**Environment:**
* Vault Server Version (retrieve with `vault status`): NA

* Vault CLI Version (retrieve with `vault version`):
1. (Windows in -dev mode) Vault v1.13.2 (b9b773f1628260423e6cc9745531fd903cae853f), built 2023-04-25T13:02:50Z
2. (Archlinux vault server) Vault v1.13.2 (cgo)
* Server Operating System/Architecture: Windows binary with -dev and Archlinux server /ui/ cluster.

Vault server configuration file(s):

NA

**Additional context**

**Comment by hellobontempo** [comment]
Hi @ipaqmaster - thanks for reporting! In 1.13 we rolled out a new PKI beta UI (the gif in PR https://github.com/hashicorp/vault/pull/18761 shows how to navigate to the new UI). Is this issue happening in the existing PKI view (with the three tabs) or the new one?

**Comment by ipaqmaster** [comment]
Apologies for not clarifying - This only seems to happen in the old one. Looks like this has already been taken care of too.
Thanks again Vault team :)
