### ISSUE TITLE
The underlying connection was closed: An unexpected error occurred on a send

### ISSUE THREAD

**Issue by waliul-cse** [hashicorp/vault#2111]
Hello guys,
After generation certificate I'm trying to make https call to get vault key but get the exception from WebResponse.
**The underlying connection was closed: An unexpected error occurred on a send**
FYI,
When I'm trying to call http mode then I got the vault key but can't get for https.

Here is my code:         
public static string HttpCall(string url, string token)
        {
            string content = string.Empty;
            try
            {
                HttpWebRequest http = (HttpWebRequest)WebRequest.Create(url);
                http.Headers["X-Vault-Token"] = token;
               // http.KeepAlive = false;
               //ServicePointManager.MaxServicePointIdleTime = 50000;
              // ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls;
               //http.ServicePoint.Expect100Continue = false;
               //http.ProtocolVersion = HttpVersion.Version11;
               //http.PreAuthenticate = true;
                WebResponse response = http.GetResponse();

                Stream stream = response.GetResponseStream();
                StreamReader sr = new StreamReader(stream);
                content = sr.ReadToEnd();
              
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return content;

Please give me any suggestions.Thanks in advance.

**Comment by waliul-cse** [comment]
Hopefully I have resolved this issue.I just share this resolution which may help someone.
Vault uses default TLS version 1.2(tls12) but my project built in .Net3.5 and that's default TLS version is V1.0 (tls10) that's make the difference.
When I'm trying to call the vault key from my code which TLS version is tls10 but vault server TLS version was  tls12 that's why the error are occurred.

 To resolve the issue we  have to  set the TLS version 1.0 in vault config or  we can update the .Net4.5 or upper versions
                          tls_min_version = "tls10"

Hope everyone enjoy it.

**Comment by jefferai** [comment]
Thanks for posting back with the solution!
