### ISSUE TITLE
Question: nested policies

### ISSUE THREAD

**Issue by schmitzhermes** [hashicorp/vault#2112]
Hey folks, 

I did not find an issue for this, nor is it mentioned in the docs; this is why I am opening this issue.

Is the following policy possible in Vault?
```
path "secret/services/*/intern/*" {
  policy = "write"
}
```

I try to achieve that everyone can access the credentials for the internal environment, but I do not want every developer to access the production credentials.

The above does not seem to work (I neither can access `intern` nor can I access `production`. The question is: is that on purpose and do I need to restructure my paths or is this in actual issue? Or is there even a better way to do it?

Thanks in advance,
Jan

**Comment by jefferai** [comment]
No, this is not possible.

**Comment by patrick-motard** [comment]
@schmitzhermes Were you able to come up with a strategy for your use case? If so, could you share it? I'm also interested in ideas for bypassing the lack of expressions in "path".

**Comment by schmitzhermes** [comment]
Hey @patrick-motard - we did not manage to create a "strategy", we just rearranged the keys in another (decreasing) order, e.g. `secret/services/intern/*/...`.
