### ISSUE TITLE
Statsite Telemetry Question

### ISSUE THREAD

**Issue by pantocrator27** [hashicorp/vault#2115]
Is there any documentation that maps the Vault telemetry information to Statsite and what the metrics mean?

**Comment by jefferai** [comment]
No.

**Comment by pantocrator27** [comment]
How can I add an enhancement request for the documentation to be created?

**Comment by jefferai** [comment]
Generally speaking we know that it would be nice to have but lack the time to work on it right now. The fastest way to get something going would be to PR the info :-)

**Comment by pantocrator27** [comment]
if I knew what the mappings were, I would not have submitted the issue otherwise this GH issue would have been rhetorical :)  i will attempt to start digging into the codebase

**Comment by jefferai** [comment]
I know -- but I also don't have any idea what they are beyond grepping through the code base, hence it's equally as fast either way :-)
