### ISSUE TITLE
Documentation output doesn't match real output

### ISSUE THREAD

**Issue by ThisIsMissEm** [hashicorp/vault#2116]
Hi! I just started playing with Vault, it looks great. Reading the documentation, I was a little confused when looking at the output of `vault read` as what in the [documentation](https://github.com/hashicorp/vault/blob/master/website/source/intro/getting-started/first-secret.html.md ) is different to the output I get (using latest 64bit binary from the downloads page)

What I get:

```
$ vault read secret/hello                                                                                                                                      
Key             	Value
---             	-----
refresh_interval	768h0m0s
excited         	yes
value           	world

$ vault read -format json secret/hello                                                                                                                         
{
	"request_id": "68315073-6658-e3ff-2da7-67939fb91bbd",
	"lease_id": "",
	"lease_duration": 2764800,
	"renewable": false,
	"data": {
		"excited": "yes",
		"value": "world"
	},
	"warnings": null
}
```

Expected:

```
$ vault read secret/hello
Key             Value
lease_duration  2764800
excited         yes
value           world

$ vault read -format=json secret/hello
{
  "lease_id": "",
  "lease_duration": 0,
  "renewable": false,
  "data": {
    "excited": "yes",
    "value": "world"
  }
}
```

I'm guessing the case here is just that the documentation is slightly out of date; If that is the case, and you'd like a PR to update it, just let me know and I'd be happy to send in PRs.

**Comment by jefferai** [comment]
It's just out of date documentation...a PR would be great!

**Comment by ThisIsMissEm** [comment]
Okay, I'll do one up!

**Comment by ThisIsMissEm** [comment]
Have created https://github.com/hashicorp/vault/pull/2117
