### ISSUE TITLE
vault docker service on Docker swarm mode 

### ISSUE THREAD

**Issue by ragunathp** [hashicorp/vault#2124]
Hi, 
Following steps to reproduce the issue:

Environment:
Docker daemon running on swarm mode.
Docker version 1.12.2
Vault v0.6.2

Steps:
1. start vault as a **docker service** i,e  "docker service create .... "   
2.  docker exec -it vault....  vault init  -address=$VAULT_ADDR
3. Do docker exec -it vault.. vault status  -address=$VAULT_ADDR - 
4. Do docker exec -it vault... vault unseal  -address=$VAULT_ADDR <key 1...> repeat this step for the given key threshold - unseal is successful at this point.
5. Now do docker exec -it vault.. vault status  -address=$VAULT_ADDR , we get an error as 
   Error checking seal status: Get http://127.0.0.1:8200/v1/sys/seal-status: net/http: request canceled     (Client.Timeout exceeded while awaiting headers)
Event "auth" fails with same error.

Note:
1. When vault is started as a container (not in swarm mode, everything works fine)
The issue occurs when vault is started as docker service . The status hangs exactly after unseal as stated in step 4 above. Note, at step 3, the status works fine. Issue occurs after unseal.

**Comment by ekristen** [comment]
Need a lot more information. A container on a docker swarm is no different than a container on a single docker daemon.

Can you provide the exact commands you are running for all your steps. 

Please also provide all the logs from the docker container as well.

**Comment by ragunathp** [comment]
Sure. Please find the steps below:

vault.hcl:
backend "consul" {
  address = "hostname.domain:8500"
  path = "vault"
  scheme="http"
}
listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = 1
}
disable_mlock = true

1. docker service create \
        --name vault\
        --replicas 1\
        --publish 8200:8200 \
        --mount type=bind,source=/home/xyz/data,destination=/config \
        --restart-condition on-failure \
        vault server -config=/config/vault.hcl
		
2. Pick the containerID and exec to vault container - docker exec -it e9d650b34a40 /bin/sh

3. # export VAULT_ADDR=http://127.0.0.1:8200
4. / # vault init > keys.txt
5. / # cat keys.txt
Unseal Key 1: +32VXHYek1+BTCAzYImqD0swC+TPN2LGOzbrZSAKlA+4B
Unseal Key 2: t1+W2M+nBRCfMh2Wf9WBi9PtATAMPJ2OIkRilyW4jpKkMC
Unseal Key 3: QPs+mVba7COVSwMzqgXRwqVRFlGxiio6BFAnS18yZJ0D
Unseal Key 4: 0y53Q9s0TZtMCMBfGBmShUrYTFPR2xRiKWwg0uKjQqsE
Unseal Key 5: f6++Hsqh9RKHg5d7LgpsCzDxkCpZpidx8axV1wjV4DHUF
Initial Root Token: dd4d016c-4070-70f8-ac8d-81fd21a9a99e

Vault initialized with 5 keys and a key threshold of 3. Please
securely distribute the above keys. When the Vault is re-sealed,
restarted, or stopped, you must provide at least 3 of these keys
to unseal it again.

Vault does not store the master key. Without at least 3 keys,
your Vault will remain permanently sealed.
6. / # vault unseal +32VXHYek1+BTCAzYImqD0swC+TPN2LGOzbrZSAKlA+4B
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 1
7. / # vault unseal t1+W2M+nBRCfMh2Wf9WBi9PtATAMPJ2OIkRilyW4jpKkMC
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 2
8. / # vault unseal QPs+mVba7COVSwMzqgXRwqVRFlGxiio6BFAnS18yZJ0D
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
 # vault status
Error checking seal status: Get http://127.0.0.1:8200/v1/sys/seal-status: net/http: request canceled (Client.Timeout exceeded while awaiting headers)		

Note: The reported issue can be simulated every time when you start as service, i,e step 1 above.
Vault works great when step 1 is replaced with "docker run -d --name vault -p 8200:8200 -v /home/xyz/registry/data:/config vault server -config=/config/vault.hcl"

I checked the /vault/logs folder , but it is empty. Let me know where to find the log files.
As indicated earlier, issue occurs when
 vault running as service (in "swarm mode"). Even "vault auth" fails with same error, so it prevents to write/read  vault.

**Comment by ekristen** [comment]
Need the logs from the docker container(s) to know what is happening with vault itself.

One problem is that you are listening on the loopback address of 127.0.0.1, while querying this inside the container should work, it'll never work outside the container even though you have the port 8200 published, you need to listen on 0.0.0.0 or the IP of the container itself.

**Comment by ragunathp** [comment]
Thanks for looking into this. If you see, I did exec into the container and executed the status command. The same vault status command works fine when executed before the unseal operations.

Please let me know where to find the log files. 
As mentioned, /vault/logs folder is empty.

**Comment by ekristen** [comment]
I understand the status command isn't working properly, that's why I need to see the vault logs. In this case you are attempting to run vault in a docker container, `docker logs` would be a place to start unless you've setup your logging a different way with your docker daemon. The `vault/logs` folder is audit logs produced by vault (if enabled).

**Comment by ragunathp** [comment]
Ok, here is is the docker logs out put

==> Vault server configuration:

                 Backend: consul (HA available)
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
        Redirect Address: http://127.0.0.1:8200
                 Version: Vault v0.6.2

2016/11/25 03:54:47.332262 [WARN ] physical/consul: appending trailing forward slash to path
==> Vault server started! Log data will stream in below:

2016/11/25 03:55:51.502781 [INFO ] core: security barrier not initialized
2016/11/25 03:55:51.535906 [INFO ] core: security barrier initialized: shares=5 threshold=3
2016/11/25 03:55:51.580172 [INFO ] core: post-unseal setup starting
2016/11/25 03:55:51.590874 [INFO ] core: successfully mounted backend: type=generic path=secret/
2016/11/25 03:55:51.590904 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2016/11/25 03:55:51.591020 [INFO ] core: successfully mounted backend: type=system path=sys/
2016/11/25 03:55:51.591095 [INFO ] rollback: starting rollback manager
2016/11/25 03:55:51.631088 [INFO ] core: post-unseal setup complete
2016/11/25 03:55:51.631296 [INFO ] core/startClusterListener: starting listener
2016/11/25 03:55:51.631353 [INFO ] core/startClusterListener: serving cluster requests: cluster_listen_address=127.0.0.1:8201
2016/11/25 03:55:51.639583 [INFO ] core: root token generated
2016/11/25 03:55:51.639596 [INFO ] core: pre-seal teardown starting
2016/11/25 03:55:51.639603 [INFO ] core/stopClusterListener: stopping listeners
2016/11/25 03:55:51.639612 [INFO ] core/startClusterListener: shutting down listeners
2016/11/25 03:55:52.131658 [INFO ] core/startClusterListener: listeners successfully shut down
2016/11/25 03:55:52.131705 [INFO ] core/stopClusterListener: success
2016/11/25 03:55:52.131734 [INFO ] rollback: stopping rollback manager
2016/11/25 03:55:52.131780 [INFO ] core: pre-seal teardown complete
2016/11/25 03:57:04.270772 [INFO ] core: vault is unsealed
2016/11/25 03:57:04.270794 [WARN ] physical/consul: Concurrent sealed state change notify dropped
2016/11/25 03:57:04.270909 [INFO ] core: entering standby mode
2016/11/25 03:57:04.284109 [INFO ] core: acquired lock, enabling active operation
2016/11/25 03:57:04.320809 [WARN ] physical/consul: Concurrent state change notify dropped
2016/11/25 03:57:04.320832 [INFO ] core: post-unseal setup starting
2016/11/25 03:57:04.322016 [INFO ] core: pre-seal teardown starting
2016/11/25 03:57:04.322030 [INFO ] core/stopClusterListener: stopping listeners

**Comment by ekristen** [comment]
Well the last entry states that it stopped its listeners, so that's why it wouldn't return a seal status.

**Comment by ragunathp** [comment]
Yes I observed it, could you give some pointers on why this is stopping and how to make this work when using docker service?

**Comment by ragunathp** [comment]
Hello Erik, Could you let me know the reasons why the listeners can potentially stop?

**Comment by ragunathp** [comment]
Let me know if this not the right forum to post the issue.

**Comment by alexw23** [comment]
I can't even start vault in swarm mode. Swarm Mode doesn't support --cap-add yet https://github.com/docker/docker/issues/25885

**Comment by bweston92** [comment]
Given the following stack:
```
version: '3.3'
services:
  api:
    image: vault
    environment:
      VAULT_LOCAL_CONFIG: "/vault.json"
    configs:
      - source: operations_vault
        target: /vault.json
    command: vault server

configs:
  operations_vault:
    external: true
```

Output:
```
[root@LION:~]# vi vault.yml 
[root@LION:~]# docker stack deploy -c vault.yml operations_vault
[root@LION:~]# docker service ps --no-trunc operations_vault_api
ID                          NAME                         IMAGE                                                                                  NODE                DESIRED STATE       CURRENT STATE            ERROR                       PORTS
fbs4foqqemlgidr04qdu7w0to   operations_vault_api.1       vault:latest@sha256:e14889b08156b89eac8f72b49c409d03800b14cf395aa7afb59b7d688361816d   BREEZE              Ready               Preparing 1 second ago                               
n1yu6j99ldju0u1d0hilazd2l    \_ operations_vault_api.1   vault:latest@sha256:e14889b08156b89eac8f72b49c409d03800b14cf395aa7afb59b7d688361816d   THAMES              Shutdown            Failed 2 seconds ago     "task: non-zero exit (1)"   
ffsasz6evyozoco3fab25j9af    \_ operations_vault_api.1   vault:latest@sha256:e14889b08156b89eac8f72b49c409d03800b14cf395aa7afb59b7d688361816d   THAMES              Shutdown            Failed 10 seconds ago    "task: non-zero exit (1)"   
8tdc7yvisy793qi9qwh18bnhn    \_ operations_vault_api.1   vault:latest@sha256:e14889b08156b89eac8f72b49c409d03800b14cf395aa7afb59b7d688361816d   THAMES              Shutdown            Failed 17 seconds ago    "task: non-zero exit (1)"   
fyiu9w4ijcgfsotokdk8hd56t    \_ operations_vault_api.1   vault:latest@sha256:e14889b08156b89eac8f72b49c409d03800b14cf395aa7afb59b7d688361816d   THAMES              Shutdown            Failed 24 seconds ago    "task: non-zero exit (1)"   
[root@LION:~]# docker service logs operations_vault_api
operations_vault_api.1.ffsasz6evyoz@THAMES    | Failed to set capabilities on file `/bin/vault' (Not supported)
operations_vault_api.1.ffsasz6evyoz@THAMES    | usage: setcap [-q] [-v] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]
operations_vault_api.1.ffsasz6evyoz@THAMES    | 
operations_vault_api.1.n1yu6j99ldju@THAMES    | Failed to set capabilities on file `/bin/vault' (Not supported)
operations_vault_api.1.n1yu6j99ldju@THAMES    | usage: setcap [-q] [-v] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]
operations_vault_api.1.ffsasz6evyoz@THAMES    |  Note <filename> must be a regular (non-symlink) file.
operations_vault_api.1.fyiu9w4ijcgf@THAMES    | Failed to set capabilities on file `/bin/vault' (Not supported)
operations_vault_api.1.fyiu9w4ijcgf@THAMES    | usage: setcap [-q] [-v] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]
operations_vault_api.1.8tdc7yvisy79@THAMES    | Failed to set capabilities on file `/bin/vault' (Not supported)
operations_vault_api.1.n1yu6j99ldju@THAMES    | 
operations_vault_api.1.8tdc7yvisy79@THAMES    | usage: setcap [-q] [-v] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]
operations_vault_api.1.n1yu6j99ldju@THAMES    |  Note <filename> must be a regular (non-symlink) file.
operations_vault_api.1.fyiu9w4ijcgf@THAMES    | 
operations_vault_api.1.8tdc7yvisy79@THAMES    | 
operations_vault_api.1.8tdc7yvisy79@THAMES    |  Note <filename> must be a regular (non-symlink) file.
operations_vault_api.1.fyiu9w4ijcgf@THAMES    |  Note <filename> must be a regular (non-symlink) file.
```

After I set the `privileged: true` to the container it isn't available.
```
[root@LION:~]# vi vault.yml 
[root@LION:~]# docker stack deploy -c vault.yml operations_vault
Ignoring unsupported options: privileged
```

**Comment by jefferai** [comment]
@bweston92 If Swarm mode doesn't support it, you can set SKIP_SETCAP to skip the setcap call (and disable mlock in your Vault configuration).

**Comment by bweston92** [comment]
Thanks that’s great!
