### ISSUE TITLE
Configure Vault with Consul Backend with ACLs Enabled - Unexpected response code: 500

### ISSUE THREAD

**Issue by akamalov** [hashicorp/vault#2125]
Greetings,

Trying to deploy Vault with Consul backend and ACLs enabled.  Here is the procedure:

**Create ACL Token**

```
[root@mmaster1 vault-ak]# curl -X PUT -d '{"name":"vault", "type":"client","rules": "key \"vault/\" {policy=\"write\"}" }'  http://consul1.sdncluster1.consul.marathon.mesos:8500/v1/acl/create?token=$TOKEN

{"ID":"fe5805c6-5950-e484-f557-09af72d1033c"}

[root@mmaster1 vault-ak]#

```
**Create** ```config.hcl``` 

```
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/vault/config/server-cert.pem"
  tls_key_file = "/vault/config/server-key.pem"
}

backend "consul" {
  path = "vault"
  address = "consul1.sdncluster1.consul.marathon.mesos:8500"
  advertise_addr = "http://vault1.sdncluster1.vault.marathon.mesos:8200"
  token = "fe5805c6-5950-e484-f557-09af72d1033c"
 }
disable_mlock = true
max_lease_ttl = "10h"
default_lease_ttl = "10h"
cluster_name = "testcluster"
```

**Deploy container:**

Deploy container with a volume map (config volume). Vault comes up, however after couple of seconds, reports:

```
[root@mslave2 config]# docker logs -f 66
Generating RSA private key, 2048 bit long modulus
..............................................................................+++
...............................................................+++
e is 65537 (0x10001)
Signature ok
subject=/CN=*
Getting Private key
==> Vault server configuration:

                 Backend: consul (HA available)
         Cluster Address: https://vault1.sdncluster1.vault.marathon.mesos:8201
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "", tls: "enabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
2016/11/23 20:06:07.096997 [WARN ] physical/consul: appending trailing forward slash to path
        Redirect Address: http://vault1.sdncluster1.vault.marathon.mesos:8200
                 Version: Vault v0.6.2

==> Vault server started! Log data will stream in below:

2016/11/23 20:06:14.075129 [WARN ] physical/consul: check unable to talk with Consul backend: error=Unexpected response code: 500 (CheckID "vault:vault1.sdncluster1.vault.marathon.mesos:8200:vault-sealed-check" does not have associated TTL)
```

What am I missing here ? I tried ```config.hcl``` both with ``` token = "fe5805c6-5950-e484-f557-09af72d1033c"``` and ```acl_token = "fe5805c6-5950-e484-f557-09af72d1033c"``` but to no avail. Any input would be tremendously appreciated!!

**Comment by jefferai** [comment]
That's a Consul and/or Mesos error. You need to solve the underlying error, then Vault should work.

**Comment by akamalov** [comment]
@jefferai, why would you say it's Mesos error? Both Consul an Vault are up, able to ping each other without a problem.

**Comment by jefferai** [comment]
> physical/consul: check unable to talk with Consul backend: error=Unexpected response code: 500 (CheckID "vault:vault1.sdncluster1.vault.marathon.mesos:8200:vault-sealed-check" does not have associated TTL)

If the check is being created by Mesos, it's a Mesos problem. If it's being created elsewhere, the problem lies elsewhere.

**Comment by akamalov** [comment]
Is there any reference documentation I can read regarding CheckID + vault-sealed-check ? Because it is coming straight from the container. As far as Marathon goes, it is up and runninng?

**Comment by jefferai** [comment]
I honestly don't know; all I know is it's not a Vault issue.
