### ISSUE TITLE
Vault is sealed wrong error?

### ISSUE THREAD

**Issue by AndreaCrotti** [hashicorp/vault#2129]
I just did 
$ http http://52.19.75.33:8200/v1/sys/init
and I got the right response, then I just had a typo, using a non existent URL and got instead back:

```
$ http http://52.19.75.33:8200/v1/sys/typo

HTTP/1.1 503 Service Unavailable
Content-Length: 31
Content-Type: application/json
Date: Fri, 25 Nov 2016 15:10:20 GMT

{
    "errors": [
        "Vault is sealed"
    ]
}
```

Not sure it's normal, the vault is definitively not sealed and 503 also is an odd return code for this.
Is that on purpose?

**Comment by AndreaCrotti** [comment]
I'm sorry I was wrong it's actually sealed, I restarted in the meanwhile.
However the first call to sys/init still worked even if it was sealed, is that desired?

**Comment by BenjaminFarley** [comment]
If the Vault server hasn't already been initialized on the mounted backend, the first call to sys/init will work, producing your Initial Root Token and your Unseal keys. Any subsequent requests to it afterwards will bring back a Vault is already Initialized error.

**Comment by AndreaCrotti** [comment]
Yes ok sure sounds good, sorry for the false alarm
