### ISSUE TITLE
HTTP API should return 503 when sealed

### ISSUE THREAD

**Issue by ianunruh** [hashicorp/vault#213]
In the API docs, it is specified that when the Vault is sealed, the API will return a 503 Service Unavailable. As of 0.1.2 however, it returns a 500 Internal Server Error with the error message `Vault is sealed`.

https://vaultproject.io/docs/http/index.html

**Comment by armon** [comment]
Tagged as bug

**Comment by ianunruh** [comment]
Fixed in #225
