### ISSUE TITLE
LDAP Secret Engine Creds Request on Web UI

### ISSUE THREAD

**Issue by Roxyrob** [hashicorp/vault#21306]
**Is your feature request related to a problem? Please describe.**
Possible critical credential exposure for inexperienced users using LDAP Secret Engine.

**Describe the solution you'd like**
Using LDAP Secret Engine to get credentials (e.g. Active Directory) is more for non-developers users, so it will be very vaulable if a user logging using Vault Web UI would be able to get LDAP credentials directly inside Vault Web UI instead of running a script making the process more secure (avoiding to move tokens around).

**Describe alternatives you've considered**
Script using vault cli and probably bash/powershell (not so user friendly).

**Explain any additional use-cases**
Enforce Administrators to use MFA using Vault TOTP. LDAP Auth with unprivileged user with LDAP Auth Method + MFA (all on Web UI already now) then request LDAP Secret Engine credentials with higher grants: this impose token copy paste and script run with possibly critical credential exposure (greater risks for critical credentials)

**Comment by emper0r-cu** [comment]
hi 
any update about it? some WIP or roadmap to added in specific version? this is very useful.

**Comment by Monkeychip** [comment]
@Roxyrob Thank you for the issue. We will be adding the LDAP Secrets Engine to the Vault UI in 1.15. And in the implementation there will be a workflow of creating a roll and generating credentials for that role. Let me know if that answers your questions.

**Comment by Roxyrob** [comment]
@Monkeychip We use automation to manage Vault so Secret engine and roles are not created and managed using UI but I know these features too are expected by the community. If you can add also the ability for the roles (also created without UI - e.g. vault cli, etc.) to request credentials of different types (Static, Dynamic and Library) it would what we asked about and very useful for sure.

**Comment by Monkeychip** [comment]
@Roxyrob Thanks for the reply. It looks like the UI LDAP engine will allow you to request creds from different role types. Basically, if you can make the request in the LDAP API we will support it in the UI.

**Comment by hashishaw** [comment]
Hey folks! I'm very happy to share that this feature request will be shipped in 1.15.0 within the new [LDAP secrets engine](https://github.com/hashicorp/vault/pull/20790) 🎉 We hope this solves your use case, and we look forward to hearing your feedback, comments, and suggestions for future improvements.
