### ISSUE TITLE
Allowing query of "latest_version" from /transit/keys/{key} but not reading the key itself

### ISSUE THREAD

**Issue by bironran** [hashicorp/vault#2138]
I'm trying to create an automated transit key rotation strategy that, at the end, would automatically advance the min_decryption_version. In order to do that, I need to read the latest_version from the key config.
However, because latest_version is a field on the key, the same client could potentially also read the keys map itself, letting it gain insight into the key components.

We should be able to query the latest_version (or other metadata such as name and type) of a key without being exposed to the key data itself (the keys map).

**Comment by jefferai** [comment]
What in the keys GET output are you concerned about?

**Comment by bironran** [comment]
> $ vault read transit/keys/foo
> Key                     Value
> type                    aes256-gcm96
> deletion_allowed        false
> derived                 false
> **keys                    map[1:1.459861712e+09]**
> latest_version          1
> min_decryption_version  1
> name                    foo
> 

As far as I understand, the numbers in the key map represent the seed for key generation, no?

**Comment by bironran** [comment]
or not, and I'm being stupid for not reading the code first (for future reference, number for AES keys is creation time, ecdsa keys will have the public key and the curve name). I'll close this.
