### ISSUE TITLE
Listing consul roles doesn't work

### ISSUE THREAD

**Issue by holtwilkins** [hashicorp/vault#2139]
Running `vault list ssh/roles/` and `vault list aws/roles/` works as expected.  Not with consul roles (this is with a root token)

```
STAG HASHI hwilkins ~ $ vault list consul/roles/
No value found at consul/roles/
STAG HASHI hwilkins ~ $ vault read consul/roles/nomad-consul-backup
Key       	Value
---       	-----
lease     	0s
policy    	a2V5ICIiIHsKICBwb2xpY3kgPSAicmVhZCIKfQo=
token_type	client
```

**Comment by jefferai** [comment]
What version of Vault?

**Comment by holtwilkins** [comment]
Sorry for not including that, `0.6.2` (client and server).

**Comment by jefferai** [comment]
Sorry, I thought this was in 0.6.2 but it turns out it's actually in master slated for 0.6.3; see https://github.com/hashicorp/vault/pull/2065
