### ISSUE TITLE
Provide better error handling from the Vault golang API (go-errors ?)

### ISSUE THREAD

**Issue by wrouesnel** [hashicorp/vault#2140]
Hashicorp already has the https://github.com/hashicorp/errwrap package, but this is used nowhere in the Vault API at present. This is particularly bad because the default error handling squashes all the HTTP errors to strings and thus loses any typed information or status codes which might be important - i.e. there's no way without doing string matching to check for a permission denied error from vault versus a 500   error.

Ideally the vault golang API would expose types allowing determination of common issues (ServerDown, ServerUnsealed, PermissionDenied).

**Comment by jefferai** [comment]
@wrouesnel Keep in mind that the Go API is just a wrapper around the HTTP API, so any errors that the Go API might see can only be parsed as strings from the JSON response.

It's possible that in the future we could make some of those typed, but at best it's string parsing.

**Comment by bernielomax** [comment]
If possible I would like to see Vault use its own concrete type for the error interface. That way we could assert the error interface back to its concrete type to access underlying struct fields. Possibly http error codes, messages, etc? That way we can wrap the responses in our own error handling?

**Comment by bernielomax** [comment]
Currently I get a long winded 403 string but without some pretty gross pattern matching I am unable to use the status code.

**Comment by alexodle** [comment]
Not sure I 100% agree with @jefferai 's comment, as the http status code is available from the response, regardless of being able to parse the json response. Opened up #6779 to reinvestigate this.
