### ISSUE TITLE
Vault 1.14.0 - GUI not visible on Safari

### ISSUE THREAD

**Issue by chrisvanmeer** [hashicorp/vault#21406]
**Describe the bug**
Since the upgrade to Vault 1.14.0-ent I cannot access the GUI from Safari anymore.  
When you visit the GUI you only quickly see the Vault product logo with "Enterprise" beneath it and then returns a white page. Visiting the GUI in Chrome does work.

**To Reproduce**
1. Open Safari
2. Visit the Vault GUI
3. See white page

**Expected behavior**
See the login page

**Environment:**
* Vault Server Version: `1.14.0+ent`
* Vault CLI Version: `v1.14.0+ent (81c88fc5890eb19dffed6cac53e09e23a3ee537e)`
* Server Operating System/Architecture: Ubuntu 22.04 LTS

**Additional context**
Reproduced this on different computers with different versions of Safari.

**Comment by hsimon-hashicorp** [comment]
Hello! As an enterprise customer, can you log a support ticket for this please? This repository is for the open-source Vault offering and as such I fear I can't provide much assistance. I'm going to go ahead and close this issue, and I appreciate your patience. Thanks! :)

**Comment by hellobontempo** [comment]
Following up here for posterity as I haven't located a corresponding support ticket internally (yet). I came across this issue locally in Safari, on OSS. If you scroll down in the browser the login form appears and after logging in the GUI renders as expected. Thanks for reporting and we're investigating a fix to resolve the styling issue.

**Comment by MB175** [comment]
Can confirm the Login-GUI in 1.14.0 is broken in Safari, it collapses on the Page bottom

**Comment by chrisvanmeer** [comment]
It has to do something with this [line](https://github.com/hashicorp/vault/blob/325233ea7dba833e987909b21af547d0933751e3/ui/app/templates/vault/cluster/auth.hbs#L27).  
  
When this is rendered in Safari, it displays the flight-icon of Vault with a specific `height` attribute of `100%`. When omitting this `height` attribute, the login form displays correctly in both Safari, Chrome and Firefox.  
  
However, I cannot find where this `height` (and `width`) attribute are being set. I thought it was because of the `@streched={{true}}` but this only leads to [this](https://github.com/hashicorp/vault/blob/325233ea7dba833e987909b21af547d0933751e3/ui/lib/core/addon/components/icon.hbs#L2).  
  
I hope this helps in solving the bug.
