### ISSUE TITLE
High memory usage on startup

### ISSUE THREAD

**Issue by sinneduy** [hashicorp/vault#2144]
I'm running vault 0.6.2 in standalone mode with DynamoDB as the backend.

```
# vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Version: 0.6.2
Cluster Name: <redacted>
Cluster ID: <redacted>

High-Availability Enabled: false
```

```
# cat config.hcl
backend "dynamodb" {
}

listener "tcp" {
 address = "0.0.0.0:443"
 tls_cert_file = <redacted>
 tls_key_file = <redacted>
}

disable_mlock = true
default_lease_ttl = "24h"
max_lease_ttl = "720h"
```

Unfortunately, we recently began to see some issues with high memory usage, especially upon startup.

Additionally, we noted a lot of the following in our logs:
```
2016/11/30 08:42:53.141432 [ERROR] expire: failed to revoke lease: lease_id=<redacted> error=failed to revoke token: cannot revoke blank token
2016/11/30 08:42:53.141500 [ERROR] expire: failed to revoke lease: lease_id=<redacted> error=failed to revoke token: cannot revoke blank token
2016/11/30 08:42:53.141619 [ERROR] expire: failed to revoke lease: lease_id=<redacted> error=failed to revoke token: cannot revoke blank token
```
 as well as
```
2016/11/30 22:30:35 Request body type has been overwritten. May cause race conditions
2016/11/30 22:30:35 Request body type has been overwritten. May cause race conditions
2016/11/30 22:30:35 Request body type has been overwritten. May cause race conditions
```

Which I believe to be a dynamoDB error.

What is most concerning though, is that in polling `free` I see very high memory usage, of which I can probably attribute (and by attribute, I mean by noting the difference in memory use before and after starting vault) ~3GB to vault during startup.

```
             total         used         free       shared      buffers
Mem:       7662548      4304016      3358532          108       232428
-/+ buffers:            4071588      3590960
Swap:            0            0            0
```

So, I have three questions here:

1) What is the expected memory usage of Vault?  It seems like its doing a significant amount of caching of the decrypted data - is it tied pretty closely with how many secrets and/or leases you have?
2) If the expected memory usage is lower than what we are seeing, then is dynamodb potentially a problem?
3) Are the errors noted above in any way related to the high memory use?

**Comment by jefferai** [comment]
Hi @sinneduy 

Answers:

1) "Not large" but as you noted is is very much tied to the number of leases (including tokens). These are stored in memory to ensure fast expiration behavior. However, these are not large. 3GB is a huge, huge, huge amount, because these are about 4KB each. Vault does have a read cache which in 0.6.2 due to a bug got tuned to quite a large amount; if you want to see if this is the culprit try setting disable_cache=true in your config. But on startup I'd not expect that to be an issue.

2) Sure. Maybe? I don't know much about Dynamo, its client, its Go SDK, etc. About all I can tell you there is that the SDK will be updated in 0.6.3 (just pulled in new versions today).

3) Maybe? The latter error (about the request body being overwritten) looks pretty bad. As you noted that's coming from DynamoDB (at least, as far as I can guess as I've never heard of that error before in Vault) so it looks potentially possible that data is getting lost to/from Dynamo and causing the other errors.

**Comment by sinneduy** [comment]
1.  In that case, it sounds like due to the failure to renew leases, an excessive amount of leases are being loaded into vault and causing the large memory use issue.
2. Interesting - any ideas around when that will be released?
3. It looks bad but it seems it is a somewhat common issue in dynamoDB https://github.com/aws/aws-sdk-go/issues/868 , and should be fixed, so I'll either hope for that 0.6.3 update or move to another backend

**Comment by jefferai** [comment]
> In that case, it sounds like due to the failure to renew leases, an excessive amount of leases are being loaded into vault and causing the large memory use issue.

That's not how it works. The same lease values remain in memory; no new ones are loaded. It will simply retry expiring those repeatedly.

It's unclear from the linked issue what the pathology of that bug in the aws sdk is, but if it's caused bad data in Dynamo you could have lingering issues. You can use the lease ID with revoke-force in that case to tell Vault to forget about it.

**Comment by sinneduy** [comment]
> That's not how it works. The same lease values remain in memory; no new ones are loaded. It will simply retry expiring those repeatedly.

Just to clarify, I meant revoke, not renew.

Are you then saying that this is likely due to having many many lease values that are currently active in memory?

**Comment by jefferai** [comment]
@sinneduy Unfortunately I have no idea how many leases we're talking about here. You'd need a *LOT* of leases to have those residing in memory be the culprit. At least hundreds of thousands.

If there's some memory leak in the revocation logic that might be a separate discussion, but the mere presence of tracking the leases should not use anywhere near that without really large numbers of leases.

I'd check with disable_cache set to see if the bug related to that in 0.6.2 is a contributing factor. You could also try with a build from fresh master to see if the updated SDK helps.

**Comment by sinneduy** [comment]
alright.  I hope to see 0.6.3 released soon
