### ISSUE TITLE
Search-field losing focus with new UI

### ISSUE THREAD

**Issue by EtienneBruines** [hashicorp/vault#21451]
**Describe the bug**
On every keystroke, the HTML `input` for filtering ACL Policies auto-submits the form, causing the `input` element to lose focus.

**To Reproduce**
1. Setup vault
2. Log in to the new UI
3. Search for ACL policies
4. Attempting to search for `hello` (by typing `h` `e` `l` `l` `o`), results in this:

![Screenshot_20230626_084214](https://github.com/hashicorp/vault/assets/3962174/79edbd45-e97c-4f01-ba84-1eab6c27cda7)

(I am then able to re-select the `input` element to type more, but sometimes I then only manage 1 or 2 characters before it loses focus again (because it starts submitting after the first character I type). )

**Expected behavior**
If the form auto-submits (which is useful), the `input` field should never lose focus. 

**Environment:**
Vault v1.14.0 (13a649f860186dffe3f3a4459814d87191efc321), built 2023-06-19T11:40:23Z
OS: Ubuntu 22.04.2 LTS on amd64

```hcl
# /etc/vault.d/vault.hcl
ui = true

# And some more unrelated settings ...
```

**Additional info:**
I suspect the whole `nav` area (which contains the `input` element) is being re-rendered upon submit (or upon loading the search results, something like that).

**Comment by snake3lake** [comment]
The same applies to the "Search engine".
