### ISSUE TITLE
Wrong redirect URI when using Amazon Cognito

### ISSUE THREAD

**Issue by JovanPetkovski** [hashicorp/vault#21467]
Hi Everyone,

When logging in using the OIDC auth method, I'm unable to authenticate and receive a callback/redirect to localhost. When I run the command to login via oidc vault login -method=oidc I receive the " Complete the login via your OIDC provider. Launching browser to: " following the provided link they authenticate to Amazon Cognito, and redirected back to localhost.

Allowed callback URLs in Amazon Cognito app client: 
`http://localhost:8250/oidc/callback
https://vault.url/ui/vault/auth/oidc/oidc/callback`
They are the same in my Role config. What can be the issue that causes this behavior. Without the localhost callback url, the vault cli just throws unable to authorize with role "role" with redirect_uri="localhost:8250/oidc/callback".

**Comment by austingebauer** [comment]
Hi @JovanPetkovski! Github issues are typically reserved for bug reports and features requests. I'm going to close this issue and suggest that you ask this question over at [Vault discuss](https://discuss.hashicorp.com/c/vault/30).

My 2c while I'm here -- Your `redirect_uri` in the last sentence doesn't look correct. It's missing the `http://` scheme.
