### ISSUE TITLE
Approle login permission denied in Vault 1.13+

### ISSUE THREAD

**Issue by rickardgranberg** [hashicorp/vault#21507]
**Describe the bug**
After upgrading from Vault 1.12.8 to 1.13+ (tested with 1.13.1, 1.13.4 and 1.14.0), approle login fails on _some_ of our app roles.

**To Reproduce**
1. Run `curl --request POST --data '{"role_id":"<redacted>","secret_id":"<redacted>"}' https://<redacted>/v1/auth/approle/login`
2. Returns `{"errors":["permission denied"]}`

We're struggling to find any more detail on this. Runing Vault with `log_level: "trace"` provides nothing.

What we've tested so far is:
1. Try to log in with role_id/secret_id created prior to upgrade -> fails on some app roles
2. Try to log in with same role_id and secret_id created after upgrade -> fails on same app roles
3. Created a new role_id/secret_id with the same configuration as one that fails -> can login successfully

One curious thing is that we also get `permission denied` when running `list auth/approle/role/:rolename/secret-id` on some app roles (all of the ones that fail to log in, but also on ones that work to log in with).
The ACL policy of the user in this case is: `path "auth/*" { capabilities = ["create", "read", "update", "delete", "list"] }`

**Expected behavior**
Expect it to return the token.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.13.1, 1.13.4 and 1.14.0
* Vault CLI Version (retrieve with `vault version`): not applicable
* Server Operating System/Architecture: Docker/Kubernetes

Vault server configuration file(s):

```hcl
 disable_mlock = true
    ui = true
    default_lease_ttl = "168h"
    max_lease_ttl = "720h"
    log_level = "info"
    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
    }
    storage "consul" {
      path = "vault"
      address = "HOST_IP:8501"
      scheme = "https"
      token = "<redacted>"
      tls_skip_verify = "true"
    }

    service_registration "consul" {
      address = "HOST_IP:8501"
      scheme = "https"
      token = "<redacted>"
      tls_skip_verify = "true"
      service_tags = "<redacted>"
    }
```

**Additional context**

**Comment by rickardgranberg** [comment]
That was the problem, thank you!

**Comment by MMquant** [comment]
This `vault read /sys/locked-users` worked for me.
