### ISSUE TITLE
Web identity broken in 1.14.0

### ISSUE THREAD

**Issue by andrejvanderzee** [hashicorp/vault#21510]
**Describe the bug**

Web identity on EKS 1.17.1 stops working on 1.14.0.

```
$ kubectl -n vault logs vault-2
Defaulted container "vault" out of: vault, cfssl-init (init)
{"@level":"info","@message":"proxy environment","@timestamp":"2023-06-29T14:43:01.945534Z","http_proxy":"","https_proxy":"","no_proxy":""}
Error parsing Seal configuration: error fetching AWS KMS wrapping key information: AccessDeniedException: User: arn:aws:sts::123456789:assumed-role/worker/i-0a62ba7ace1d8158f is not authorized to perform: kms:DescribeKey on resource: arn:aws:kms:eu-central-1:123456789:key/dd6269bb-2857-4c75-9e7b-407e1a4278c9 because no identity-based policy allows the kms:DescribeKey action
```

**To Reproduce**

Deploy statefulset or vault helm chart with version 1.13.4 on EKS  v1.27.1. Auto-unseal works as expected.

Then, upgrade to 1.14.0 and the error appears.

**Expected behavior**

Same as in 1.13.4: Vault takes web idenity instead of the EKS worker node identity and successfully auto-unseals.

**Environment:**
* Vault Server Version 1.14.0
* Vault CLI Version 1.13.2
* Server Operating System/Architecture: EKS 1.27.1

**Comment by dqsully** [comment]
Looks like the same issue I reported here https://github.com/hashicorp/vault/issues/21478

**Comment by hsimon-hashicorp** [comment]
> Looks like the same issue I reported here #21478

Agreed, I will close this as a duplicate.
