### ISSUE TITLE
incorrect template variable not validated in postgresql backend

### ISSUE THREAD

**Issue by webervin** [hashicorp/vault#2151]
given file sqlreadonly with typo in valid until variable: 
```
CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiritation}}';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "{{name}}";
```
1) invalid template gives success on create:
training@hashicorp > vault write postgresql/roles/readonly sql=@sqlreadonly
Success! Data written to: postgresql/roles/readonly

2) on asking for token HTTP 500 happens:
training@hashicorp > vault read postgresql/roles/readonly
Key	Value
---	-----
sql	CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiritation}}';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "{{name}}";

training@hashicorp > vault read postgresql/creds/readonly
Error reading postgresql/creds/readonly: Error making API request.

URL: GET http://127.0.0.1:8200/v1/postgresql/creds/readonly
Code: 500. Errors:

* 1 error(s) occurred:

Expected would be to have error out on write of config, not later on token generation.

```
training@hashicorp > vault --version
Vault v0.6.1
```

Issue was discovered during training given by @sethvargo in Riga, so environment should be reproducable.

* pq: invalid input syntax for type timestamp with time zone: "{{expiritation}}"

**Comment by jefferai** [comment]
We prepare the query using the postgres lib, so in this case the prepare command on the postgres db is not returning an error. So there's not much we can do.

**Comment by sethvargo** [comment]
Hey @jefferai 

I think @webervin is saying that the _interpolation_ should fail. He accidentally misspelled "expiritation", which caused Vault to run the query as: `VAULT UNTIL ''`, which _is valid SQL_, but `{{expiritation}}` is not a valid key to use in the SQL string.

**Comment by jefferai** [comment]
@sethvargo I understand what @webervin is saying; however, we generally want to be as agnostic to the given SQL as possible. A {{}} value that isn't a valid parameter we've defined in our template could still have some meaning in the context of the SQL.

**Comment by sethvargo** [comment]
It still seems like a bad user-experience. At the very least, I think we should drop a warning that's like "unmatched substitution parameter" or something.

**Comment by mitchellh** [comment]
I agree with @sethvargo. In TF we get away with the "you may still want that exact value" by asking the user to use escape sequences. This removes all ambiguity: you're either exactly referencing a variable, or you're escaping it to a literal sequence.

**Comment by webervin** [comment]
in context of postgresql create role is transactional - so it is possible to create user right away, test if template was SQL ok and rollback that test.

But if there is no possibility to verify on `vault write postgresql/roles/` then maybe 200 should return warning that it is end user responsibility to check if 200 is 'all will be ok in future' vs 'ok for now'.
