### ISSUE TITLE
Keyring corrupted: unseal failed, invalid key

### ISSUE THREAD

**Issue by tsaarni** [hashicorp/vault#21521]
I'm not sure if this is a bug but I'm hoping you can help us understand what is going on.

On a couple of occasions, we have seen Vault fail to unseal with the error `Unseal failed, invalid key`. The issue is permanent and the only way to recover is to restore a working backup.

The unseal keys seem to be correct because the error originates from decrypting the keyring (`core/keyring` in vault storage). That becomes after the unseal key was already successfully used to decrypt the storage root key (`core/hsm/barrier-unseal-keys` in vault storage). When running Vault under the debugger I can see the callstack is below [1]. The error message from `gcmAsm.Open()` is `cipher: message authentication failed`.

The data in the keyring seems to be OK: its length is the same as in the working backup and it begins with a valid header that Vault appends to encrypted values `{"Value":"AAAAAQ....`

We have not been able to reproduce the issue on demand, and the exact circumstances when the fault happened are not known, but we have speculated with the following scenarios

- Backup & restore scenario: Vault might have been initialized with empty storage and unsealed, then storage was restored from a backup while Vault was still running. Since Vault periodically writes the keyring it, could overwrite the one restored from the backup. The keyring would be encrypted with a different key, not matching the storage root key.
- Memory corruption: The storage root key might be corrupted in runtime memory (e.g. due to a bug) and when Vault periodically writes the keyring, it got encrypted with the corrupted key.

We are using etcd as the storage backend.

Questions:

Have you seen keyring corruption before?
Can you think of any theories on how this issue could happen?
Do you have any suggestions on how to go about troubleshooting this kind of issue and avoid it in the future?

<details><summary>[1] callstack</summary>
<pre>
# The topmost function is the most recent
#    decrypting keyring results in "cipher: message authentication failed" here:
go/src/crypto/aes/aes_gcm.go:gcmAsm.Open()    # https://cs.opensource.google/go/go/+/refs/tags/go1.20.5:src/crypto/aes/aes_gcm.go;l=182
vault/barrier_aes_gcm.go:AESGCMBarrier:decrypt()    # https://github.com/hashicorp/vault/blob/325233ea7dba833e987909b21af547d0933751e3/vault/barrier_aes_gcm.go#L1037
vault/barrier_aes_gcm.go:AESGCMBarrier.Unseal()    # https://github.com/hashicorp/vault/blob/325233ea7dba833e987909b21af547d0933751e3/vault/barrier_aes_gcm.go#L453)
</pre>
</details>

**Comment by hsimon-hashicorp** [comment]
Hi! Can you also share with us your configuration (Vault version, etc), as well as if you've seen it happening in just one version or more than one?

**Comment by hsimon-hashicorp** [comment]
Also:

> Backup & restore scenario: Vault might have been initialized with empty storage and unsealed, then storage was restored from a backup while Vault was still running. Since Vault periodically writes the keyring it, could overwrite the one restored from the backup. The keyring would be encrypted with a different key, not matching the storage root key.

This is a scenario that can cause all sorts of issues with Vault. Vault expects its storage to remain consistent while it's running, and we advise never to change the storage underneath a running instance. A backup and restore scenario should only be done with Vault not running.

**Comment by tsaarni** [comment]
Thank you @hsimon-hashicorp! The version that was deployed when the issue happened was Vault 1.11.3.

**Comment by hsimon-hashicorp** [comment]
@tsaarni without more specific repro steps, this will be hard to get in front of our engineers. If this occurs without changing the storage from underneath a running Vault instance, I'd definitely want to know more - however, that's my big suspicion, is that those underlying storage changes caused the corruption of the key. If you're willing, we can close this issue temporarily and have you re-open it when you hit it again or can gather more information - otherwise, just ping me when you see it again. Sometimes "aha!" moments don't come when we need them to. :)

**Comment by tsaarni** [comment]
Yes, let's do that. Thank you @hsimon-hashicorp for your help!
