### ISSUE TITLE
Malformed entry 1 in list file /etc/apt/sources.list.d/hashicorp.list

### ISSUE THREAD

**Issue by apetrut** [hashicorp/vault#21570]
Hi,

I have this Dockerfile and trying to build the linux image out of it:

```
FROM ubuntu

#Install wget
RUN  apt-get update && \ 
     apt-get install -y wget && \
     rm -rf /var/lib/apt/lists/*
       
#Install sudo
RUN apt-get update && \
    apt-get -y install sudo

#Install gpg
RUN apt-get update && \
    apt-get -y install gpg

#RUN sudo apt-get install ca-certificates

#Install HashiCorp Vault
RUN wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

RUN echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
RUN sudo apt update && \
    sudo apt install vault

ENTRYPOINT ["dotnet", "MyApp.dll"]
```

When I run the command: **docker build -t my-tag .** I get the error below at step 7:

![image](https://github.com/hashicorp/vault/assets/13006228/7415c610-88c2-46ef-8973-25f4cdaf1cf3)

Note: I am using the official documentation for Ubuntu installation but it doesn't seem to work:

![image](https://github.com/hashicorp/vault/assets/13006228/283c648d-1f1c-4462-b0ce-2c5d5611450a)

Does anyone have any ideas how to solve it?

Thanks.

**Comment by mpalmi** [comment]
Thanks for filing the issue @apetrut! It appears that the issue is related to a lack of `lsb_release` in the Ubuntu image. Does adding `RUN sudo apt-get install lsb-release` prior to the failing step resolve your issue?

**Comment by apetrut** [comment]
Hi @mpalmi , after I ran that sudo command I got this:

![image](https://github.com/hashicorp/vault/assets/13006228/4150e55e-188e-4a39-8090-fddf4b4051cb)

**Comment by cipherboy** [comment]
@apetrut This is because it is a non-interactive terminal; I'd suggest:

```
DEBIAN_FRONTEND=noninteractive apt-get -y install ...
```

as a general practice inside (Debian-based) containers.

**Comment by hsimon-hashicorp** [comment]
@apetrut Wanted to check in and see if you had further questions or needed additional help. Did the tips from Mike and Alex help?

**Comment by apetrut** [comment]
@cipherboy Thanks for your help. It worked with that command.
