### ISSUE TITLE
Distinguishing between permission denied due to policy vs permission denied due to token expiry

### ISSUE THREAD

**Issue by wrouesnel** [hashicorp/vault#2159]
There currently does not seem to be a way to distinguish between different types of permission denied errors, leading to awkward application recovery code.

An example is when access to a particular key is denied due to policy restrictions, versus if a vault token has expired or been revoked.

As far as I can tell, building a robust recovery around this involves a fair amount of chatter:

* Access key -> Permission Denied
* Lookup Self on Token -> Permission Denied
* Attempt to re-authenticate -> (maybe get a new token, or you've been completely revoked)

The problem is at the initial permission denied, there's no messaging for whether it's due to the token being rejected or as a policy issue. And this is a stateless problem - at *every* permission denied the application needs to run the same recovery code which leads to a lot of extra requests.

**Comment by jefferai** [comment]
I think we're going to not change this for now; token lifetimes are easy to look up and track and we don't really see this as being a pain point for most workflows, so adding extra information doesn't seem like a necessary tradeoff.
