### ISSUE TITLE
Unsealing unsealed vault

### ISSUE THREAD

**Issue by illogicalextend** [hashicorp/vault#216]
I noticed you can continue to try unsealing a vault if it is already unsealed via cli ("Sealed: false"). It could make sense to tell the user it is already unsealed rather than let them continue to enter keys. After it has already been provided with the minimum number of keys to unseal the vault, I don't even think additional keys increment anything. "Unseal progress" will remain at 0.  

"./vault unseal"

**Comment by armon** [comment]
Agreed. Tagging for enhancement.

**Comment by armon** [comment]
Fixed by #224
