### ISSUE TITLE
HA mode

### ISSUE THREAD

**Issue by illogicalextend** [hashicorp/vault#217]
One thing I noticed when trying prod mode with consul was the presence of HA being enabled. The first node I used to create and unseal a new vault put the vault in standby mode. The only page I could find with info on HA is https://vaultproject.io/docs/concepts/ha.html and it doesn't get specific or mention config options. I'm unsure if this mode can be disabled, or that it is automatic and requires multiple servers to come online to elect a leader for any mode to become active. 

./vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
High-Availability Enabled: true
	Mode: standby
	Leader: <none>

./vault mount generic
Mount error: Error making API request.
URL: POST http://127.0.0.1:8200/v1/sys/mounts/generic
Code: 500. Errors:
* Vault is in standby mode

**Comment by armon** [comment]
@illogicalextend The mode is automatic and cannot be disabled. The reason for this is to protect a user in the case when multiple Vaults are pointing to the same Consul to prevent them stomping on each other. Vault will work with even a single server on Consul, and does not require multiple instances.

**Comment by illogicalextend** [comment]
How does it work with a single? Referring to my example above.

**Comment by armon** [comment]
@illogicalextend Verify you are using 0.1.2, but it should just become the active instance and accept requests. The logs should point out if there are some other issues at play.

**Comment by illogicalextend** [comment]
Yes v0.1.2. Noticing some errors from consul. Would you mind trying to replicate this yourself? Follow the instructions at https://vaultproject.io/intro/getting-started/deploy.html


2015/05/19 01:43:19 [ERR] core: failed to acquire lock: failed to create session: Unexpected response code: 403 (<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /v1/session/create
on this server.</p>
<hr>
<address>Apache/2.2.22 (Ubuntu) Server at demo.consul.io Port 80</address>
</body></html>

**Comment by illogicalextend** [comment]
Are the memory warnings here relevant? http://demo.consul.io/

**Comment by armon** [comment]
@illogicalextend Ah this is actually a documentation issue. Our demo cluster prevents sessions from being created (hence the 403 error), which means you can't use it as a backend for Vault. You can use Consul, but our demo cluster specifically has extra protections which prevent it from working.

**Comment by illogicalextend** [comment]
Ok, well I wasn't too keen on using a third party setup anyway, so it's even less desirable to use one that doesn't allow you to manipulate things. 

I'll try and find out how to connect it to my own consul instance.

**Comment by sheldonh** [comment]
I recommend reopening this issue, because the doc bug remains a problem for newcomers (like me).

**Comment by illogicalextend** [comment]
I made a comment on the pull request. I'll reopen this so it doesn't get forgotten about.

**Comment by armon** [comment]
Fixed by #269
