### ISSUE TITLE
Provide release artifacts using tar and/or gzipped binaries

### ISSUE THREAD

**Issue by simonswine** [hashicorp/vault#2170]
Hi!

I find it really annoying  that I have to use `unzip` to get release binaries of vault. Would make things easier to provide compressed binaries and/or tar archives.

Thanks

**Comment by jefferai** [comment]
There are currently no plans to do this. It's pretty trivial on *nix systems to unzip and pretty non-trivial on Windows systems to use anything other than zip, so we are standardizing on what's easy across platforms.
