### ISSUE TITLE
Unable to unseal vault: forbidden

### ISSUE THREAD

**Issue by grobinson-blockchain** [hashicorp/vault#2175]
I have a strange issue where I'm unable to unseal the vault:

    ~$ vault seal
    Vault is now sealed.

    ~$ vault unseal
    Error checking seal status: Error making API request.

    URL: GET http://127.0.0.1:8200/v1/sys/seal-status
    Code: 500. Errors:

    * failed to check seal configuration: Unexpected response code: 403

I can't authenticate because the vault is sealed, and I can't unseal the vault because I can't authenticate:

    :~$ vault auth
    Token (will be hidden):
    vault unsealError validating token: Error making API request.

    URL: GET http://127.0.0.1:8200/v1/auth/token/lookup-self
    Code: 503. Errors:

    * Vault is sealed
    :~$ vault unseal
    Error checking seal status: Error making API request.

    URL: GET http://127.0.0.1:8200/v1/sys/seal-status
    Code: 500. Errors:

    * failed to check seal configuration: Unexpected response code: 403

**Comment by jefferai** [comment]
I'm assuming you closed this because you figured it out; I'm also assuming you figured out that the issue was with your storage backend  :-)
