### ISSUE TITLE
Question: How to add a client certificate to authenticate to mongodb

### ISSUE THREAD

**Issue by RcRonco** [hashicorp/vault#2177]
Hi, 
There is a way to authenticate to mongodb with client certificate instead of username and password in the uri string?

https://docs.mongodb.com/v3.4/core/security-x.509/#client-x-509-certificates

**Comment by vishalnayak** [comment]
@RcRonco I gave a quick glance at this. At present, the mongodb secret backend relies `mgo.DialInfo` to interact with mongo server. Probably its a good idea to follow up the support for authentication using certificates in `mgo`.

If that's done, accepting client certificates for authentication could be nice add-on to the to the Vault's secret backend's configuration as well.
