### ISSUE TITLE
export VAULT_ADDR="..." not overriding default  value from https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo fedora 28 based distro

### ISSUE THREAD

**Issue by cccsss01** [hashicorp/vault#21770]
When setting VAULT_ADDR env variable it is not overriding the default settings w/ the vault package from fedora 28.  Whoever, vault status -address .... works

**Comment by cccsss01** [comment]
It also appears I cannot use vault -address ...... write

**Comment by cipherboy** [comment]
Could you paste the full command and environment you're attempting to run? 

Note that Fedora 28 is EOL and has been since 2019-05-28.
