### ISSUE TITLE
Key-value custom_metadata is not visible in the UI 

### ISSUE THREAD

**Issue by Exidex** [hashicorp/vault#21773]
custom_metadata field was added in https://github.com/hashicorp/vault/issues/10714 but as far as I know it is only accessible via CLI and is not visible in the UI. So this is a feature request to make this field visible in the UI

**Comment by cwchristerw** [comment]
I think you are incorrect. Its available in UI in latest Vault version.
![image](https://github.com/hashicorp/vault/assets/13464896/0bc4ac2f-f852-45d5-8591-83db45bccb15)

**Comment by Exidex** [comment]
We are on version 1.10.4, which I acknowledge is not the latest, but I haven't found information in the change log just looking for `custom_metadata` so can you please provide information about in which version it was added?

**Comment by cwchristerw** [comment]
It was added in version 1.9.0

CHANGELOG.md
```
* ui: Add custom metadata to KV secret engine and metadata to config [[GH-12169](https://github.com/hashicorp/vault/pull/12169)]
```
https://github.com/hashicorp/vault/blob/main/CHANGELOG.md?plain=1#L2745

https://github.com/hashicorp/vault/pull/12169

**Comment by Exidex** [comment]
Ok, that is weird. Is these any other reason the ui (both in secret creation and view) can be hidden while the data is still accessible using CLI with the same token? for example configuration property or permission

**Comment by cwchristerw** [comment]
I'm not sure if this is helpful
https://github.com/hashicorp/vault/issues/7571

**Comment by cwchristerw** [comment]
@Exidex Can you send your policy here :smile:

**Comment by Exidex** [comment]
Sorry, I do not have access to it as I am not managing our instance of vault. I will close it because it is most likely a configuration error
