### ISSUE TITLE
Multiple vault endpoints LDAP authentication

### ISSUE THREAD

**Issue by Artiax** [hashicorp/vault#2178]
Issue:
When trying to authenticate with multiple vaults via LDAP in the same shell we get the following error:
```
* LDAP bind failed: LDAP Result Code 53 "Unwilling To Perform": unauthenticated bind (DN with no password) disallowed
```

Replication:
```
export VAULT_ADDR=https://vault_one:443
vault auth -method=ldap username=MYLDAP (which works as you get prompted for the password)
export VAULT_ADDR=https://vault_two:443
vault auth -method=ldap username=MYLDAP (fails as it skips the password prompt and gives us the above error)
```

EDIT:

If you were to run vault auth again after it errored out, it would work as expected, it's just the first attempt that's failing after setting new VAULT ADDR.

**Comment by broamski** [comment]
I would start by comparing ldap configurations in both of your vault instances to see if there are configuration differences:

`vault read -address=https://vault_one:443 auth/ldap/config`
`vault read -address=https://vault_two:443 auth/ldap/config`

**Comment by Artiax** [comment]
They're both using the same LDAP config (both vaults share the same ldap server) as it's provisioned using an automated script.

**Comment by jefferai** [comment]
Are both the same Vault version?

**Comment by Artiax** [comment]
Yes they're the same version, but I don't think it's a problem in the configuration of the different vaults, it's just that our use case requires us to switch to the other vault mid way through the script.

This same error could be replicated by simply doing a vault auth twice against the same vault.

**Comment by vishalnayak** [comment]
Hi @Artiax, I am not able to reproduce this issue. Following are the commands I used:

```
vault auth-enable ldap
vault write auth/ldap/config url="ldap://ldap.forumsys.com" userattr="uid" userdn="dc=example,dc=com" groupdn="dc=example,dc=com"
vault write auth/ldap/groups/scientists policies=foo,bar
vault write auth/ldap/groups/engineers policies=foobar
vault write auth/ldap/users/tesla groups=engineers policies=zoobar
export VAULT_ADDR='http://127.0.0.1:8200'
vault auth -method=ldap username=tesla password=password
export VAULT_ADDR='http://127.0.0.1:8200'
vault auth -method=ldap username=tesla password=password
```

Let me know if what you are doing is different than this.

**Comment by jefferai** [comment]
Cannot reproduce; please ping back if you can provide guidance here.

**Comment by Artiax** [comment]
@vishalnayak @jefferai 
You seem to be specifying the password in the command, this will work however if you omit it and make vault prompt you for it - that's when you'll see the error.

**Comment by vishalnayak** [comment]
@Artiax Sorry for the late response. It still works for me without the password in the command. My guess is that this is an IO issue in the terminal you are using since the binary is not able to read from STDIN. I unfortunately don't have a suggestion on debugging/fixing this probable `tty`/`IO` problem.
