### ISSUE TITLE
ssh/config/lease endpoint missing

### ISSUE THREAD

**Issue by vascop** [hashicorp/vault#2179]
When I create a dynamic key type with the SSH role the key comes back with a renewable 768h lease duration by default. I would expect to be able to configure this by running:
`vault write ssh/config/lease lease=1h lease_max=24h`

Like in other backends such as the postgresql one. This would then go into the machine and remove the respective authorized_keys line, which I assume is what happens at the moment after 768 hours. Are there any plans to implement this?

**Comment by jefferai** [comment]
Currently you can use mount tuning to set this -- see the `mount-tune` command or https://www.vaultproject.io/docs/http/sys-mounts.html

**Comment by vascop** [comment]
Thanks @jefferai, that worked!
