### ISSUE TITLE
Database secrets engine static password rotation no longer works

### ISSUE THREAD

**Issue by Dane903** [hashicorp/vault#21857]
After creating static database (MS SQL and Postgres are confirmed to have this issue) credential and role, and setting the rotation to 5 minutes the password rotation works. For Postgres this worked for over a week. Then after some time the error message is that the login fails. Obtaining the password and logging into the database manually (outside of vault) works fine. 

**To Reproduce**
1. Create Static Credential for Postgres Database (syntax obfuscated)
vault write database/config/vaultpoc-postgres.aws.corp.com plugin_name=postgresql-database-plugin connection_url="postgresql://{{username}}:{{password}}@vpce12345.amazonaws.com:5432/postgres" allowed_roles="role_vaultpoc-postgres_vaultpoc-postgres.aws.corp.com" username="m12345" password="fredSally49$" password_policy=vms_postgres_password_policy

2. Create static role for Postgres Database
vault write database/static-roles/role_vaultpoc.aws.corp.com db_name=vaultpoc-postgres_vaultpoc-postgres.aws.corp.com rotation_statements="ALTER USER {{username}} PASSWORD '{{password}}'" username="m12345" rotation_period="3m"

3. See error in logs
2023-07-14T07:08:03.744-0500 [ERROR] secrets.database.database_7ce08a43: unable to rotate credentials in periodic function for database name: : vaultpoc-postgres.aws.corp.com="error verifying connection: failed to connect to `host=vpce.us-east-1.vpce.amazonaws.com user=m12345 database=postgres`: server error (FATAL: password authentication failed for user \"m12345\" (SQLSTATE 28P01))"

5. Check password:
myhost:/opt/app/workload/vault $ vault read database/static-creds/role_vaultpoc-postgres_vaultpoc-postgres.aws.corp.com
Key                    Value
---                    -----
last_vault_rotation    2023-07-07T14:27:20.886318164-05:00
password               h6Dw{2_Cc555P9RFI}G58aI12345
rotation_period        3m
ttl                    0s
username               m12345

6. Logging in to postgres, password still works

**Expected behavior**
Password rotation should continue to work and rotate the password every 3 minutes

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.15.0-beta1
* Vault CLI Version (retrieve with `vault version`): v1.15.0-beta1
* Server Operating System/Architecture: Rocky Linux

Vault server configuration file(s):

```hcl
storage "raft" {
  path    = "./data"
  node_id = "devnode1"
}

listener "tcp" {
  address     = "vaultdev.corp.com:8200"
  #tls_disable = "true"
  tls_cert_file = "./tls/vaultdev-corp-com.pem"
  tls_key_file = "./tls/private.key"
  tls_disable_client_certs = "true"
}

api_addr = "http://myhost.corp.com:8200"
cluster_addr = "https://myhost.corp.com:8201"
ui = true
disable_mlock = true
plugin_directory = "./plugins"
log_level = "trace"


**Additional context**
Add any other context about the problem here.

**Comment by maxb** [comment]
You must not use the same database account for both `database/config/...` (which is the privileged account that Vault itself uses to connect to the database, to manage other accounts) and `database/static-roles/...` (which is for accounts that Vault hands out to users of the Vault API).

If you do, then as you have discovered, then Vault locks itself out of the database, because one part of Vault changes the password being used in another part of Vault to manage the database.

The `database/rotate-root/:connection_name` endpoint exists to trigger a rotation of the management password stored within `database/config/:connection_name`.

**Comment by Dane903** [comment]
That (database/rotate-root/:connection_name) listed above is for a root rotated (dynamic) password rotation. I'm using a static password rotation method. 

Here is the link I followed to create a static role for the database: [https://developer.hashicorp.com/vault/tutorials/db-credentials/database-creds-rotation]

On "Step 2: Create a static role", sub-step 2 it shows the command as: 
vault write database/static-roles/education

**Comment by maxb** [comment]
> That (database/rotate-root/:connection_name) listed above is for a root rotated (dynamic) password rotation. I'm using a static password rotation method.

I'm not sure what you mean by that.



> Here is the link I followed to create a static role for the database: [https://developer.hashicorp.com/vault/tutorials/db-credentials/database-creds-rotation]
> 
> On "Step 2: Create a static role", sub-step 2 it shows the command as: vault write database/static-roles/education

In that document, they are using different database usernames in step 1 vs step 2.

You used the same database user, and that is the problem.

**Comment by Dane903** [comment]
A static db credential implementation only has one database user. What would the other user be?

**Comment by maxb** [comment]
I already explained this above...

> You must not use the same database account for both `database/config/...` (which is the privileged account that Vault itself uses to connect to the database, to manage other accounts) and `database/static-roles/...` (which is for accounts that Vault hands out to users of the Vault API).

One privileged database user for Vault internally to use to change other users' passwords.

And one user (per static-role) whose credentials are handed out to Vault clients.

**Comment by Dane903** [comment]
I understood a static credential could be a non-root database user with lesser permissions and it could change its own password. This apparently is not the case. (at the company I work we have database IDs that are like this we wanted to reuse in Vault) What I understand now is Vault always requires a ROOT DB user that can change another users password (for static) and in the case of dynamic can create a user, grant whatever roles it needs, and drop a user. Is this correct? Thanks for the help BTW

**Comment by maxb** [comment]
Yes, that's how it works.

**Comment by Dane903** [comment]
Would adding the following parameters to the 'vault write database/config' statement essentially stop the root user password from being rotated (by over 13 years and intentionally corrupt rotate statements mean the default will not be used) and effectively create the self rotating credential I was hoping to implement?   (these were accepted by Vault when used)

rotation_period="5000d" 
root_credentials_rotate_statements='FGHJ USER {{username}} IDENTIFIED BY "{{password}}";'

**Comment by maxb** [comment]
No it would not.

`rotation_period` is not even an accepted parameter for that endpoint.

`root_credentials_rotate_statements` applies only when the `database/rotate-root/:connection_name` endpoint that I previously mentioned is called.

**Comment by Dane903** [comment]
I ran the command. It returned a success response. 

vault write database/config/dev.aws.corp.com plugin_name=vault-plugin-database-oracle connection_url="{{username}}/{{password}}@dev.aws.corp.com:1524/DEV" allowed_roles="role_dev.aws.corp.com" username="M74732" password="zwXxEkD12JlbMe" password_policy=oracle_password_policy rotation_period="5000d" root_credentials_rotate_statements='FGHJ USER {{username}} IDENTIFIED BY "{{password}}";'

**Comment by hsimon-hashicorp** [comment]
@maxb Is this something that could use a docs fix for clarification, do you think?

**Comment by hsimon-hashicorp** [comment]
> It might be helpful to augment [developer.hashicorp.com/vault/docs/secrets/databases](https://developer.hashicorp.com/vault/docs/secrets/databases) with a more specific explanation of how the database plugin uses its configured "root" account, and an explicit instruction to not attempt to configure the same account as a "root" account and also a static-role.
> 
> That said, I don't see an obvious specific flaw in the current documentation - it's simply not as detailed as it could be.
> 
> @Dane903 is proving somewhat reluctant to accept that Vault does not in fact implement the behaviour they initially assumed / hoped it did.
> 
> It is regrettable that the Vault database plugin configuration API fails to provide any feedback when the user specifies nonexistent configuration settings to them (`rotation_period` above), as this has enabled false hope to endure.

Thank you for all of your help, as always, in helping clarify these issues for us. I'll ask @yhyakuna to take a look at the docs, and our engineers to look at the CLI options. Appreciate it!

**Comment by Dane903** [comment]
Many companies have processes that need a less than root level of database access and per least privilege are not allowed to have a root credential.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by maxb** [comment]
> and our engineers to look at the CLI options.

It's not a CLI issue, but an API one. The Vault API does now issue warnings - which the CLI then renders - for invalid parameters sent to most endpoints - unfortunately the database plugin API is designed in such a way that it is impossible to provide that functionality for it, short of a revision to the interface between the database secrets engine and database plugins.
