### ISSUE TITLE
Error when tidying up PKI engine with ACME enabled

### ISSUE THREAD

**Issue by karelkryda** [hashicorp/vault#21866]
**Describe the bug**
When attempting to perform a tidy (manual or automatic) of a PKI engine with ACME tidy enabled, the error `The server experienced an internal error: unable to determine acme base folder path: /` is displayed instead of a successful tidy.

**To Reproduce**
1. Login to the Vault with root token
3. Go to the PKI engine
4. Enable and configure ACME
5. Go to the "Tidy" tab
6. Click on "Perform manual tidy"
7. Select all available options
8. Click on "Perform tidy"

**Expected behavior**
Tidy of the PKI engine should proceed without error.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.14.0
* Vault CLI Version (retrieve with `vault version`): v1.14.0
* Server Operating System/Architecture: Debian 12 Bookworm

Vault server configuration file(s):

```hcl
# Basic
ui = true
api_addr = "https://x.y.z:8200"

# Storage
storage "file" {
  path = "/opt/vault/data"
}

# HTTPS listener
listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/etc/ssl/certs/xyz.pem"
  tls_key_file  = "/etc/ssl/private/xyz.key"
}

# AWS KMS auto unseal
seal "awskms" {
  region = "xyz"
  access_key = "xyz"
  secret_key = "xyz"
  kms_key_id = "xyz"
}
```

**Additional context**
I transferred the contents of the `/opt/vault/data` folder from Vault version 1.13.1 (I migrated between servers) and then enabled the ACME server. When enabling ACME I followed the instructions [here](https://developer.hashicorp.com/vault/tutorials/secrets-management/pki-acme-caddy#enable-pki-secrets-engine). Basically I just tuned the PKI engine and set the **Cluster Config** values. I didn't create any EABs.

Command **vault read pki/config/cluster**:
```
Key      Value                                                   
aia_path https://x.y.z:8200/v1/pki
path     https://x.y.z:8200/v1/pki
```

Command **vault read pki/config/acme**:
```
Key                      Value                     
allowed_issuers          ["*"]                     
allowed_roles            ["x.y"] 
default_directory_policy role:x.y
dns_resolver                                       
eab_policy               not-required              
enabled                  true 
```

Command **vault read sys/mounts/pki/tune**:
```
Key                         Value                                             
allowed_response_headers    ["Last-Modified","Location","Replay-Nonce","Link"]
default_lease_ttl           2764800                                           
description                                                                   
force_no_cache              false                                             
max_lease_ttl               31536000                                          
passthrough_request_headers ["If-Modified-Since"]  
```

Command **vault read pki/config/urls**:
```                                                    
Key                     Value                                                            
crl_distribution_points ["https://x.y.z:8200/v1/pki/crl"] 
enable_templating       false                                                            
issuing_certificates    ["https://x.y.z:8200/v1/pki/ca"]  
ocsp_servers            ["https://x.y.z:8200/v1/pki/ocsp"]
```

I managed to trace the error message [here](https://github.com/hashicorp/vault/blob/8c7e5d7a3aa6212c4ffa7c46a5ab3dedd6b8a7b8/builtin/logical/pki/acme_wrappers.go#L298-L311). Unfortunately I was not able to find out what might have caused it. Of course, it's just possible that I've set something up wrong 🙂.

**Comment by cipherboy** [comment]
\o hey @karelkryda -- hmm that's interesting. It seems like the tests we had missed this change. I've pushed a refactoring PR, but I want some automated tests for this before I merge, hopefully I'll have them soon enough to put this in the next 1.14.1 release. :-) 

Give the PR a shot and let me know if it addresses things for you!

**Comment by karelkryda** [comment]
Hey @cipherboy, I have spun up a VM with a test environment for both the `main` and `cipherboy-fix-acme-tidy` branches and can confirm that unlike the code in the `main` branch, the error in the `cipherboy-fix-acme-tidy` branch does not appear. Good work, thanks a lot.
