### ISSUE TITLE
accessor leak

### ISSUE THREAD

**Issue by maciekm** [hashicorp/vault#2189]
Hi,

We are using a lot of short lived tokens that are generated with the response wrapping.
The problem is that Vault never deletes the accessor of the temp tokens and the number of accessors keeps growing in consul.
With time we got to around 300k accessors not accounted for. (number of accessors - number of tokens). Vault is at the brink of not being able to take over the active role when it has to read all those accessors into memory.

We see it in vault 0.6.1 and 0.6.3

### How to reproduce
* Generate wrapped token (its the same when using `sys/wrapping/wrap`)
  ```
  $ vault token-create -format=json -policy="default" -wrap-ttl 300 -orphan
  {
  	"request_id": "",
  	"lease_id": "",
  	"lease_duration": 0,
  	"renewable": false,
  	"data": null,
  	"warnings": null,
  	"wrap_info": {
  		"token": "3dfe8a33-3151-e865-dbb4-7dd32bfd2b0d",
  		"ttl": 300,
  		"creation_time": "2016-12-15T15:55:11.754551887Z",
  		"wrapped_accessor": "96f88426-a083-7e31-debd-e46780184220"
  	}
  }
  ```
  
  In consul I can see the perm and temp tokens being created with the associated accessors. The accessor list grows by 2 (`vault list auth/token/accessors | wc -l`).
  
  ```
  PUT /v1/kv/vault/sys/token/accessor/f3302d70275c55c03e4216c97c0acd3f64ed80ec 
  PUT /v1/kv/vault/sys/token/id/5bd71de229098b14af879df51448e05ecafaad15 
  PUT /v1/kv/vault/sys/token/accessor/95c17930b42fe0902e3ea4f5a750bf677446ec7a 
  PUT /v1/kv/vault/sys/token/id/bfdd2105bbbace3a68e4ccb50b4d7d39d1959efa
  ```
  The temp accessor when looked-up gives: `"policies": [ "response-wrapping" ]` as expected.

* unwrap the perm token
  ```
  $ vault unwrap -format=json 3dfe8a33-3151-e865-dbb4-7dd32bfd2b0d
  {
  	"request_id": "6b99824d-b9cd-9eba-d80a-7a897439579b",
  	"lease_id": "",
  	"lease_duration": 0,
  	"renewable": false,
  	"data": null,
  	"warnings": null,
  	"auth": {
  		"client_token": "056eaed7-b241-d70b-b1c8-f72656e645ed",
  		"accessor": "96f88426-a083-7e31-debd-e46780184220",
  		"policies": [
  			"default"
  		],
  		"metadata": null,
  		"lease_duration": 86400,
  		"renewable": true
  	}
  }
  ```
  
  In consul I can see just the temp token being deleted while its accessor is left behind.

  ```
  DELETE /v1/kv/vault/sys/token/id/bfdd2105bbbace3a68e4ccb50b4d7d39d1959efa 
  ```

  The temp accessor when looked-up gives: `1 error occurred:\n\n* permission denied`. Its there but not accessible or revokable.

**Comment by albuch** [comment]
We've ran into the same issue with short lived response wrapped tokens generated by https://hub.docker.com/r/channelmeter/vault-gatekeeper-mesos/. 
Is there a possibility to clean up the stale accessors when using the file backend?

**Comment by vishalnayak** [comment]
@albuch See https://www.vaultproject.io/docs/install/upgrade-to-0.6.4.html. A one time execution of `auth/token/tidy` might solve your problem.

**Comment by albuch** [comment]
@vishalnayak thank you, that fixed it.
