### ISSUE TITLE
Separate transit key management from raw key access

### ISSUE THREAD

**Issue by armon** [hashicorp/vault#219]
See this thread:
https://groups.google.com/forum/#!topic/vault-tool/WRp_i18EblU

Basically, we should decouple the underlying keys from the management of the named keys.
This can be done by moving the keys into a separate `transit/raw/` path that is root protected, and removing root protection on the `transit/keys/` path. Additionally, the `transit/encrypt/` path should perform an automatic upsert.

**Comment by sethvargo** [comment]
:heart:  Is it possible to do this in a backwards-compatible way?

**Comment by armon** [comment]
@sethvargo Kind of. I don't think it will affect our libraries, as we are not reading out the raw key. Those will move to a new path, and that won't be backwards compatible.

**Comment by armon** [comment]
See #355

**Comment by gunnaringe** [comment]
Great news! Will test it at once.

On Thu, Jun 18, 2015 at 3:55 AM, Armon Dadgar <notifications@github.com>
wrote:

> Closed #219 <https://github.com/hashicorp/vault/issues/219> via 9238c6d
> <https://github.com/hashicorp/vault/commit/9238c6def36195a99acf210a1b60b699a6099d92>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/vault/issues/219#event-333793926>.
>



-- 
Gunnar Inge Gjøvik Sortland
Gimsmarkvegen 79
N-7227 Gimse

# 90 65 80 23  |  gunnaringe@gmail.com
