### ISSUE TITLE
`Retry-After` HTTP header when hiting Rate Limit

### ISSUE THREAD

**Issue by ahmet2mir** [hashicorp/vault#21904]
Hello world!

**Is your feature request related to a problem? Please describe.**

We use vault to update a lot of passwords with a random sleep to avoid updating them in one shot.
In some cases we hit the rate limit with 429 which is expected.

But usually when I hit this limit, most of API set a [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) with 503 / 429 error code ([RFC](https://www.rfc-editor.org/rfc/rfc9110#section-10.2.3))

Example with [Gitlab API](https://docs.gitlab.com/ee/administration/settings/user_and_ip_rate_limits.html#response-headers)

**Describe the solution you'd like**

When hiting rate limit, it will be very helpful to have the retry-after header set telling us the time to wait before counter are reset for example so we could retry.

**Describe alternatives you've considered**

A blind "retry" from code could cover that case but we also have some protections that ban when we reach too many HTTP error code. So it could be a double pain.

Or we could increase the quota limit but it could impact other users/teams and it shouldn't.

**Comment by VioletHynes** [comment]
Hi there!

Great news: we actually already support this, it's just not very well documented (something that I'm going to be fixing shortly).

See the config option here: https://developer.hashicorp.com/vault/api-docs/system/quotas-config#enable_rate_limit_response_headers

If set to true, a `Retry-After` (and some other headers, `X-Ratelimit-Limit`, `X-Ratelimit-Remaining`, and `X-Ratelimit-Reset`) will be available to calling clients. For example, here's a verbose cURL command I used in a test environment with a toy one-request-every-fifteen-seconds quota, and sending two requests (this is the second).

```
violet@violet-TX54KFJWXM vault %  curl -v -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" http://127.0.0.1:8200/v1/auth/token/lookup-self

*   Trying 127.0.0.1:8200...
* Connected to 127.0.0.1 (127.0.0.1) port 8200 (#0)
> GET /v1/auth/token/lookup-self HTTP/1.1
> Host: 127.0.0.1:8200
> User-Agent: curl/7.88.1
> Accept: */*
> X-Vault-Request: true
> X-Vault-Token: REDACTED
>
< HTTP/1.1 429 Too Many Requests
< Cache-Control: no-store
< Content-Type: application/json
< Retry-After: 13
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Ratelimit-Limit: 1
< X-Ratelimit-Remaining: 0
< X-Ratelimit-Reset: 13
< Date: Fri, 11 Aug 2023 15:39:59 GMT
< Content-Length: 82
<
{"errors":["request path \"auth/token/lookup-self\": rate limit quota exceeded"]}
* Connection #0 to host 127.0.0.1 left intact
```

I'm going to keep this issue open until I add to the documentation here, as it's a little surprising that this isn't super well documented. I found that this was an option by digging in the code looking into adding this feature!

**Comment by VioletHynes** [comment]
Closed this as part of improving the docs around how to enable this feature. It should look like this, soon:
![image](https://github.com/hashicorp/vault/assets/1594272/63d9bc59-e058-4be3-b36e-f126fc668316)


Thanks a bunch for highlighting this!

**Comment by ahmet2mir** [comment]
@VioletHynes awesome !

To be honest I grep the code to find retry header and search retry in the doc without success. 

This is crystal clear. 

Thanks !!
