### ISSUE TITLE
Vault GUI doesn't generate PrivateKey when Issue a new Certificate

### ISSUE THREAD

**Issue by andreifer20** [hashicorp/vault#21933]
**Describe the bug**
I use Vault 1.14.0 and I want to issue a new certificate using GUI. In this version I noticed that Private Key, Issuing CA and CA chain are missed. Using VAULT cli is working as I expected. Also I followed this tutorial https://developer.hashicorp.com/vault/tutorials/secrets-management/pki-engine. 

Please let me know if this expected behaviour.

**Comment by maxb** [comment]
This sounds like #21552

**Comment by cipherboy** [comment]
I concur with @maxb; closing as duplicate; fixed in https://github.com/hashicorp/vault/pull/21635.
