### ISSUE TITLE
Create a new ACL policy - POST request transforms in GET request?

### ISSUE THREAD

**Issue by apetrut** [hashicorp/vault#21989]
Hi,
I am trying to use the REST API to create a policy for /sys/auth path.

However I get 404 NOT Found response when sending a POST request and the Request method is actually a GET.

![image](https://github.com/hashicorp/vault/assets/13006228/9756d69c-10c1-452a-aa03-14fc7d6f66ab)

Does anyone have a working sample that creates a new acl policy?

**Comment by maxb** [comment]
Your description sounds like your client-side code is malfunctioning and sending the wrong request. It doesn't sound like a problem on the Vault side.

**Comment by apetrut** [comment]
@maxb It turns out that I had to use a PUT request instead of a POST request.

**Comment by maxb** [comment]
> It turns out that I had to use a PUT request instead of a POST request.

Vault treats those as completely equivalent to each other. I am not convinced that is the answer.
