### ISSUE TITLE
Upgrade from 0.6.0 to 0.6.3 leaves invalid health checks in consul

### ISSUE THREAD

**Issue by brad-peters** [hashicorp/vault#2199]
Version 0.6.0 of vault creates the following health checks in consul
```json
[
  {
    "Node": "control-01",
    "CheckID": "vault-sealed-check",
    "Name": "Vault Sealed Status",
    "Status": "passing",
    "Notes": "Vault service is healthy when Vault is in an unsealed status and can become an active Vault server",
    "Output": "Vault Unsealed",
    "ServiceID": "vault:192.168.100.101:8200",
    "ServiceName": "vault"
  }
]
```
When I upgrade to 0.6.3 I get the following health checks in consul
```json
[
  {
    "Node": "control-01",
    "CheckID": "vault-sealed-check",
    "Name": "Vault Sealed Status",
    "Status": "critical",
    "Notes": "Vault service is healthy when Vault is in an unsealed status and can become an active Vault server",
    "Output": "TTL expired (last output before timeout follows): Vault Unsealed",
    "ServiceID": "vault:192.168.100.101:8200",
    "ServiceName": "vault"
  },
  {
    "Node": "control-01",
    "CheckID": "vault:192.168.100.101:8200:vault-sealed-check",
    "Name": "Vault Sealed Status",
    "Status": "passing",
    "Notes": "Vault service is healthy when Vault is in an unsealed status and can become an active Vault server",
    "Output": "Vault Unsealed",
    "ServiceID": "vault:192.168.100.101:8200",
    "ServiceName": "vault"
  }
]
```
Since the "old" health check continues to fail vault.service.consul dns requests are returning not found.

Stopping then restarting version 0.6.3 seems to clean up all of the checks then things work fine.  It appears that the stopping of version 0.6.0 does not remove the checks and the register process in 0.6.3 does not cleanup any preexisting checks before registering the new one.

**Comment by jefferai** [comment]
> the register process in 0.6.3 does not cleanup any preexisting checks before registering the new one
If this was the case, stopping and then starting 0.6.3 should not fix the problem, but you said it did.

**Comment by brad-peters** [comment]
Stopping 0.6.0 does not clean up consul health checks
Stopping 0.6.2 and 0.6.3 does clean up consul health checks
So a stop of 0.6.0 and start of 0.6.3 does no cleanup, but a restart (stop/start) of 0.6.3 does

**Comment by jefferai** [comment]
Closing at this point, not likely to still be a common issue.
