### ISSUE TITLE
Roles (dis)allowed_policies field sanitization is surprizing and potentially dangerous

### ISSUE THREAD

**Issue by fcantournet** [hashicorp/vault#2201]
If you create a role under `auth/token/roles/example` with the following command :

`vault write auth/token/roles/example disallowed_policies="root,infra"`

and then read the role you'll get : 
```
15:06 $ vault read auth/token/roles/example
Key                	Value
---                	-----
allowed_policies   	[]
disallowed_policies	[root]
explicit_max_ttl   	0
name               	example
```

So the `infra` policy is dropped from the `disallowed_policies` list.
This is because this list goes through a sanitization function `SanitizePolicies()` in `helper/policyutil` that is generic and if `root` is in the list it just drops everything else.

Now I have since found out that  putting root in the `disallowed_policies` list is 100% useless because `root` is already protected as a policy by a hard rule : you need a token with root policy to create another token with root policy.

Nevertheless I think people could fall into that trap easily.
This can be addressed by documentation alone I think.

**Comment by jefferai** [comment]
As OP said this isn't a dangerous issue but I think we should fix in code, not just docs.

**Comment by fcantournet** [comment]
@jefferai Actually I think it can be a bit dangerous since `disallowed_policies` acts as a blacklist, removing things from it actually extends the potentials policy this role can claim.

In my example, the `infra` policy is now accessible to the `example` role even though I do not want that.

I do agree though that this is not an expected use-case, but as we both agree an overzealous admin could very well add `root` by mistake and remove at the same time all other disallowed policies inadvertantly.

I can make a PR for fixing this in code.
What do you think about just filtering `root` out of the list of `disallowed_policies` before giving the list to the sanitization function?
The other thing I can think of is making 2 sanitization function, for blacklist and whitelist with opposite logic with regards to the `root` policy.

The problem is probably not limited to the `auth\token` backend

**Comment by fcantournet** [comment]
Ok actually it might be limited to `auth/token`. I didn't find any use of blacklisting of policies in other auth backends.

**Comment by jefferai** [comment]
We can simply update the function to take a parameter, or make some other change to ensure that the behavior changes. The right thing may be to actually remove the behavior from that function with regards to special handling of root, since it's just a cleanup. Only a few code paths can generate root tokens now so we can just ensure the code in those paths works as expected.
