### ISSUE TITLE
Vault API does not differentiate between engine mount paths that include forward slash

### ISSUE THREAD

**Issue by simeon95** [hashicorp/vault#22031]
**Describe the bug**
When I enable a secret engine at path 'test' and then try to enable the same type of secret engine at path 'test/12345' I get back an error saying the path is already in use

**To Reproduce**
1. Run a Vault locally - `vault server -dev`
2. `export VAULT_ADDR='http://127.0.0.1:8200'`
3. `vault login -method=token` and paste your root token
4. `vault secrets enable -path='test' pki
5. List secret engines with `vault secrets list`. You should see a secret engine of type pki enabled at path 'test'
6. `vault secrets enable -path='test/12345' pki`. You should see an error saying the path is already in use although the path that is in use is 'test' and not 'test/12345'

**Expected behavior**
I'm able to mount a secret engine at path 

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.13.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.13.2 ('b9b773f1628260423e6cc9745531fd903cae853f+CHANGES'), built 2023-04-25T13:02:50Z
* Server Operating System/Architecture: macOS 13.4.1, 

Vault server configuration file(s): N/A

**Additional context**
N/A

**Comment by maxb** [comment]
> **Describe the bug**
> When I enable a secret engine at path 'test' and then try to enable the same type of secret engine at path 'test/12345' I get back an error saying the path is already in use

This is not a bug - Vault is functioning as designed.

You have enabled a secrets engine at path `test`. This means all sub-paths under `test/` are now reserved for operations on that secrets engine. You cannot then mount a separate secrets engine at `test/12345` as this would collide with that.
