### ISSUE TITLE
Typo on aws-ec2 auth backend documentation

### ISSUE THREAD

**Issue by stenio123** [hashicorp/vault#2204]
In the page 

https://github.com/hashicorp/vault/blob/master/website/source/docs/auth/aws-ec2.html.md#enable-aws-ec2-authentication-in-vault-1

The code section currently says
`curl -X POST -H "x-vault-token:123" "http://127.0.0.1:8200/v1/sys/auth/aws" -d '{"type":"aws"}'`
but it should say
`curl -X POST -H "x-vault-token:123" "http://127.0.0.1:8200/v1/sys/auth/aws" -d '{"type":"aws-ec2"}'`

**Comment by jefferai** [comment]
Closed by #2211
