### ISSUE TITLE
CI summary GitHub action fails on community PRs

### ISSUE THREAD

**Issue by maxb** [hashicorp/vault#22045]
The new job meant to add comments to PRs with a summary of failing tests does not work on community PRs because it does not have write permission to the repo.

https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ is an article from GitHub that explains how actions workflows can be written to securely report CI results from untrusted forks.

**Comment by VioletHynes** [comment]
Addressed in https://github.com/hashicorp/vault/pull/22351 - this now skips this job on community PRs.

I could have probably gone for a more robust solution (thanks for the link, Max!) but frankly I just wanted to stop the failures, and I didn't want to have to spend too long on it.

I'm going to look into how we can potentially improve the Vercel check failing initially, too.
