### ISSUE TITLE
lookupBatchTokenInternal not returning err when failed to decrypt the batch token

### ISSUE THREAD

**Issue by Ajaykumarkolipaka** [hashicorp/vault#22065]
**Describe the bug**

https://github.com/hashicorp/vault/blob/main/vault/token_store.go#L1508
this method should return err when it failed to decrypt the batch token. But it's returning nil

**To Reproduce**
1. Run `vault write ...`
2. Run `vault login....`
3. See error

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by akshya96** [comment]
Thanks for raising this. It turns out that was done on purpose. We're looking into it internally.
