### ISSUE TITLE
Vault-compatible endpoint for CA from PKI

### ISSUE THREAD

**Issue by clstokes** [hashicorp/vault#2207]
The `/pki/ca(/pem)` endpoint in the PKI backend is a "bare endpoint", meaning that the Vault CLI and consul-template are unable to interact with it. This is annoying for the Vault CLI, but problematic for consul-template and Nomad's template support.

For consul-template and Nomad's template support it means I have to provide another mechanism for pulling the CA onto hosts. I'm able to work around this by using the `/pki/issue` endpoint to grab the `issuing_ca` attribute off a newly generated certificate, but this is _hacky_ to generate a cert just to get the CA.

Please add a non-bare endpoint to retrieve the CA, with PEM format available too.

My current workaround in a Nomad job:
```
job "web" {
...
      template {
        data = <<EOH
{{with secret "pki/issue/consul-service" "common_name=web.service.consul" "ttl=1s"}}{{.Data.issuing_ca}}{{end}}
EOH
        destination = "secrets/consul-service-ca.pem"
        change_mode = "restart"
      }
...
}

```

**Comment by jefferai** [comment]
Already exists. See the docs for `pki/cert`.

**Comment by clstokes** [comment]
Doh, I somehow missed that. It works great!

```
job "web" {
...
      template {
        data = <<EOH
{{with secret "pki/cert/ca"}}{{.Data.certificate}}{{end}}
EOH
        destination = "secrets/consul-service-ca.pem"
        change_mode = "restart"
      }
...
}
```
