### ISSUE TITLE
ACME http-01 validation is checking destination TLS certificate, when redirected to https

### ISSUE THREAD

**Issue by rubroboletus** [hashicorp/vault#22074]
**Describe the bug**
ACME http-01 validation is checking destination TLS certificate, when redirected to https

**To Reproduce**
1. create vault PKI ACME solver
2. create http server with redirect everything from http to https, listening on some.domain.name
3. place some temporary TLS certificate on this server valid for different domains, temporary.domain.name
4. create acme challenge for some.domain.name
5. vault will try to verify http://some.domain.name/.well-known/acme.... and is redirected to https://some.domain.name/.well-known/acme....
6. verification fails with message: "tls: failed to verify certificate: x509: certificate is valid for temporary.domain.name, not some.domain.name"

**Expected behavior**
not verify destination TLS certificate, just solve ACME challenge

**Environment:**
* Vault Server Version (retrieve with `vault status`): v1.14.1
* Vault CLI Version (retrieve with `vault version`): v1.14.1
* Server Operating System/Architecture: Bottlerocket OS 1.14.2 / amd64

Vault server configuration file(s):
```hcl
disable_mlock = true
ui = true

log_level = "trace"
disable_mlock = true

listener "tcp" {
  tls_disable = 1
  address = "[::]:8200"
  cluster_address = "[::]:8201"
}

storage "raft" {
  path = "/vault/data"
}

service_registration "kubernetes" {}

seal "awskms" {
  region = "eu-central-1"
  kms_key_id = "REDACTED"
}

```

**Comment by cipherboy** [comment]
@rubroboletus I think after some internal discussion, we're fine allowing this behavior as it matches what [Let's Encrypt](https://letsencrypt.org/docs/challenge-types/#http-01-challenge) does. While the RFC doesn't explicitly talk about allowing redirects to self-signed certificates, given you are following a redirect from an (unencrypted, unauthenticated) channel to an (encrypted, unauthenticated) channel, you're no worse off (and rather, are entirely equivalent), despite this being weaker than to an (encrypted, authenticated) channel.

Are you interested in providing a PR?

**Comment by rubroboletus** [comment]
fix submited, but for more then a month is waiting for approval and merge :-(

**Comment by stevendpclark** [comment]
Closing issue as it was addressed with @rubroboletus PR, thanks again!

The improvement should appear in the next round of Vault minor releases, 1.14.7 and 1.15.3.
