### ISSUE TITLE
[Feature Request] SSH Secrets Engine - Add allowed domains template to Web UI

### ISSUE THREAD

**Issue by cwchristerw** [hashicorp/vault#22106]
**Is your feature request related to a problem? Please describe.**
I would like to restrict allowed domains to only hostname that is specified in metadata of device identity.

**Describe the solution you'd like**
I would like new button "Allowed domains template" which would be similar to "Allowed users template". I'm using mostly UI when testing "new" features ~~but this would be also implemented in API and CLI~~.

**Describe alternatives you've considered**
I should use existing limitation options of restricting to specific domain in allowed domains.

**Explain any additional use-cases**

**Additional context**
I currently use allowed users template to restrict creating user certificate for servers to authenticate with backup server.

**Comment by maxb** [comment]
The requested feature is already documented in the API: https://developer.hashicorp.com/vault/api-docs/secret/ssh#allowed_domains_template so it appears this is just about the web UI not having been updated to add it too.

**Comment by cwchristerw** [comment]
Okay, I'll update issue title :smile:

I wasn't sure if this was existing feature when I filed Feature Request because I mostly use UI :smile:

**Comment by Monkeychip** [comment]
@cwchristerw It appears this issue was fixed in this [PR](https://github.com/hashicorp/vault/pull/23119) and that the fix was backported to 1.13.8. Can you confirm that this fixes your issue? Thank you!

**Comment by cwchristerw** [comment]
I can confirm this issue was fixed by #23119. I use 1.14.6 nowadays.
