### ISSUE TITLE
[Feature Request] Auth method roles UX simplify - Unauthenticated

### ISSUE THREAD

**Issue by ArieLevs** [hashicorp/vault#22129]
**Is your feature request related to a problem? Please describe.**
As a Vault Admin, I would like to provide better login/SSO experience to our developers.
Currently unauthenticated users cannot list OIDC roles, for large organizations, there can be many roles configured forcing the user to manually typing the role he belongs to.
for example we use Okta OIDC, when a user wants to login to Vault, he will have to explicitly type (or copy past) the role name.

![Screenshot 2023-07-30 at 12 28 38](https://github.com/hashicorp/vault/assets/34907201/b900dda6-0810-4e6d-b7b6-8969a9aa8798)

**Describe the solution you'd like**
I would like the ability to allow `unauth` tune on auth roles, similar to [auth methods](https://developer.hashicorp.com/vault/docs/commands/auth/tune#listing-visibility).
so users are able to view roles similar to secrets roles list, and just select the role name from a list instead of typing it.

![Screenshot 2023-07-30 at 12 40 20](https://github.com/hashicorp/vault/assets/34907201/e470e386-3ba4-4e98-900c-bde4935e74e1)

**Explain any additional use-cases**
simplify UX for end clients

**Comment by maxb** [comment]
(Note: I don't work for HashiCorp, I'm just sharing a reaction based on my own experience deploying Vault)

Can you explain why you have multiple roles defined in the Vault OIDC auth method?

I have always interpreted the features provided by the Vault OIDC auth method as a strong sign that for most purposes, operators should almost always define exactly one role, and set it as default, so users do not need to care about roles.

Multiple roles on OIDC auth methods have, for me, seemed to mostly just be a way to test new configurations in production, without affecting normal users.

**Comment by ArieLevs** [comment]
the way we integrate Okta and Vault is that a role is bound to a list of vault policies, and a list of Okta groups.

for example, by having many Okta groups, `group-a-developers`, `group-b-developers`, `groups-a-devops` etc, you would like to give them different permissions in vault, for example, developer from `a` should not be exposed to secrets belong to groups `b`, 
or the `group-a-developers` should not even be able to view secrets in a production path, or view secrets of other organization owned mounts.

so the motivation here is basically creating a separation of permissions based on the OIDC groups (Okta groups, GitHub teams, etc)

**Comment by maxb** [comment]
> the way we integrate Okta and Vault is that a role is bound to a list of vault policies, and a list of Okta groups.

To me, this seems like the wrong way to do it, because:

* you require the user to tell Vault which group they are, rather than just having the OIDC provider tell you
* you cannot handle users who are members of multiple groups well

Instead, I would have exactly one Vault OIDC auth method role, which specified zero policies, and handle all policy assignment via Vault's Identity system, linking Vault groups to OIDC (Okta) groups, and assigning the policies to those groups.

With this setup, when the user logs in, Vault looks at their group membership as asserted by the OIDC provider, and updates the relevant Vault groups to match.

The Vault APIs for setting this up are deeply obscure, so perhaps it's no surprise that you haven't found them - you use the `identity/group` API to create a group that has `type=external`, and then you have to also use the `identity/group-alias` API to create an "alias" which maps the Vault group to the Okta auth method, and name of the group in Okta.

You need the user's list of groups to appear in the token, which IIRC I have seen some users mentioning on forums, that Okta won't let you do with its base SKU, and charges extra for this fundamental feature?! So that might be a problem.

But, this is what I would consider a "normal" integration of Vault with OIDC to look like.

**Comment by ArieLevs** [comment]
interesting, thanks I'll try this asap, this will remove the need for this feature request.
yes you are correct, I did see some documentation and have tried before to implement a solution using the external group alias as [documented here](https://developer.hashicorp.com/vault/tutorials/cloud-ops/vault-oidc-okta#create-an-external-vault-group), after it didn't worked I have implemented [jwt auth backend bound claim](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/jwt_auth_backend_role) which successfully worked.

**Comment by maxb** [comment]
> You need the user's list of groups to appear in the token, which IIRC I have seen some users mentioning on forums, that Okta won't let you do with its base SKU, and charges extra for this fundamental feature?! So that might be a problem.

Disregard this part. I found the forum thread I was thinking of - https://discuss.hashicorp.com/t/vault-and-okta-oidc-config/48128 - and was reminded that it is possible to get a groups claim without using additional authorization servers, as per https://developer.okta.com/docs/guides/customize-tokens-groups-claim/main/#add-a-groups-claim-for-the-org-authorization-server

**Comment by maxb** [comment]
I was able to revive an old testing setup I had - here is demo config for setting up Vault to use Okta with groups:

```
    vault auth enable -path=okta oidc
    vault auth tune -listing-visibility=unauth okta

    vault write auth/okta/config \
      oidc_discovery_url=https://dev-XXXXXX.okta.com \
      oidc_client_id=XXXXXX \
      oidc_client_secret=XXXXXX \
      default_role=default

    vault write auth/okta/role/default \
      user_claim=sub \
      groups_claim=groups \
      claim_mappings="email=email" \
      oidc_scopes=email,groups \
      allowed_redirect_uris=https://vault.XXXXXX/ui/vault/auth/okta/oidc/callback,http://localhost:8250/oidc/callback

    vault write identity/group name=okta-Everyone type=external policies=okta-everyone
    vault write identity/group-alias \
      canonical_id=$(id_of identity/group/name/okta-Everyone) \
      mount_accessor=$(accessor_of okta) \
      name=Everyone
```
where the `id_of` and `accessor_of` helpers are defined as:
```
accessor_of() {
    vault auth list -format=json | jq -r ".[\"$1/\"].accessor"
}

id_of() {
    vault read "$1" -format=json | jq -r .data.id
}
```

**Comment by ArieLevs** [comment]
thanks @maxb ! it all works
I've been using [identity_group](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/identity_group) and [identity_group_alias](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/identity_group_alias), only limitation was that "[External groups can have one (and only one) alias](https://developer.hashicorp.com/vault/docs/concepts/identity#external-vs-internal-groups)".

I guess It didn't worked for me before since I tested it with the default auth server, only after Okta admin created me a custom auth server the integration started to work but I already moved to the roles based implementation.
The only thing I had to change is to stop using [bound claims](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/jwt_auth_backend_role#bound_claims), and start using [group claims](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/jwt_auth_backend_role#groups_claim).

Thanks, I guess I'll be closing this request as now I just sign in with Okta while leaving the `Role` blank :grin:
