### ISSUE TITLE
Ability to specify 'token_no_default_policy=false' when enabling an auth method

### ISSUE THREAD

**Issue by eoinoreilly30** [hashicorp/vault#22125]
**Is your feature request related to a problem? Please describe.**
We want to allow users of our vault to be able to create their own roles for auth methods, but we also want to always enforce a default policy.
Currently users can disable the default policy when creating a role for an auth method, by setting 'token_no_default_policy=true'

**Describe the solution you'd like**
We would like to be able to specify 'token_no_default_policy=false' when enabling an auth method. This would apply for all roles created under that auth method path.

In our vault we currently restrict users from enabling auth methods unless through our own API, which is where we can enforce 'token_no_default_policy=false' on enabling an auth method.

**Describe alternatives you've considered**
We have tried adding this to the default policy:
```
# Disable bypassing the default policy
path "auth/+/role/*" {
    capabilities = ["create", "read", "update", "patch", "delete", "list"]
    denied_parameters = { 
        "token_no_default_policy" = [true, "true"]
    }
}
```
The problem with this solution is that it auto grants everyone full capabilities on path `"auth/+/role/*"`

We tried narrowing this down to:
```
# Disable bypassing the default policy
path "auth/+/role/*" {
    capabilities = ["create", "update"]
    denied_parameters = { 
        "token_no_default_policy" = [true, "true"]
    }
}
```
but this denies everyone the ability to `"read", "patch", "delete", "list"` on path `"auth/+/role/*"`, unless explicitly granted again.

We also tried removing the capabilities list in the hopes that it would not enforce any capability restrictions, other than the `denied_parameters` list e.g.
```
# Disable bypassing the default policy
path "auth/+/role/*" {
    denied_parameters = { 
        "token_no_default_policy" = [true, "true"]
    }
}
```
but this denied all access to path `"auth/+/role/*"`.

**Additional context**
Another feature request could be to allow only specifying the `denied_parameters` list and not enforcing any capability restrictions e.g.
```
# Disable bypassing the default policy
path "auth/+/role/*" {
    denied_parameters = { 
        "token_no_default_policy" = [true, "true"]
    }
}
```

P.S. I would be happy to work on a PR for these features if it seems like the right way to go 🙂

**Comment by eoinoreilly30** [comment]
I would be happy to work on a PR for these features if it seems like the right way to go 🙂

**Comment by maxb** [comment]
But... if you are allowing users to configure auth roles, can't they just create ways to assign any policy they like via setting `token_policies`, and thereby are effectively able to do anything anyway?

**Comment by eoinoreilly30** [comment]
Hi @maxb, thanks for your reply.

You are right, I have misunderstood how vault policy path matching works.

To explain my problem in more detail:

We have a service at my company where we provision Vaults on behalf of users. To prevent users having full access to the **sys** path we added a deny on the **sys/*** path to the regular default policy:
```
...

# Disable access to /sys path
path "sys/*" {
  capabilities = ["deny"]
}

...
```

We thought this would cover us but we recently found out users can bypass it in two ways:
- create a new auth method with **token_no_default_policy=false**
- create a new policy with a more specific path that would take precedence over the **sys/*** glob path:
```
path "sys/auth" {
  capabilities = ["create", "update", "read", "list", "patch", "delete", "sudo"]
}
```

Do you have any recommendations on how you could deny **sys/*** for all users without exception?

**Comment by maxb** [comment]
* Once you give a user permission to make changes to ACL policies, they can escalate privileges to do literally anything, by changing policies to give themselves more permissions

* Once you give a user permission to configure auth methods, they can escalate privileges to any ACL policy that already exists, by creating a way to authenticate and have that policy assigned

In the open-source edition of Vault, this is the beginning and end of the story.

In Vault Enterprise, namespaces and Sentinel provide some additional opportunities to enforce control.

If you are attempting to provide delegated administrative rights whilst running Vault open-source, then at present you have no option but to fork the code to implement additional flexibility in restrictions.
