### ISSUE TITLE
etcd as the backend, HA is broken?

### ISSUE THREAD

**Issue by danielzhanghl** [hashicorp/vault#2214]
from the docs files, it says below.
does that mean vault HA mode wont work in this configuration(ETCD cluster with three member as the backend, two vault node) ? is there a working version for that part functionality, or is there a plan to fix it?

thanks,

-----------------
For etcd, the following options are supported:
path (optional) - The path within etcd where data will be stored. Defaults to "vault/".
...

ha_enabled (optional) - Setting this to "1", "t", or "true" will enable HA mode. **This is currently known broken.** 

-------------

**Comment by danielzhanghl** [comment]
refer to https://github.com/hashicorp/vault/issues/1184#issuecomment-232433373

it seems ETCD as the backend, HA has trouble, then it's just been set HA default off, 
and plan to fix that in 0.6.5(now it’s 0.6.4)with ETCD3, and abandon ETCD2...

**Comment by jefferai** [comment]
If someone interested wants to fix etcd2 we'd be happy to accept patches but nobody has. The etcd3 support will be maintained going forward by CoreOS so should be more reliable.
