### ISSUE TITLE
Logstash as an audit backend

### ISSUE THREAD

**Issue by timp87** [hashicorp/vault#2215]
Please, consider Logstash as an audit backend.
As far as I understand it's not a huge work due to the fact JSON is a native format for Logstash to handle.

It would be very useful if we had audit logs in ElasticSearch.

**Comment by jefferai** [comment]
What is the exact ask here? You can easily ship the audit logs to Logstash, and this prevents Vault from having to deal with soft-fail cases where a Logstash server is unreachable.

**Comment by timp87** [comment]
Exact ask here is to make Logstash an optional audit backend like file and syslog.
Make vault able to send audit logs directly to logstash.

**Comment by mterron** [comment]
@timp87 you can start a syslog listener in logstash and use the normal syslog vault config. No issues there, and the guys won't need to support anything new.

Use something like this in your logstash input config:
input {
	# SysLog (RFC 3164)
	syslog {
		port => "${SYSLOG_PORT:3164}"
		type => "RFC3164"
		tags => ["syslog"]
	}
	# SysLog (RFC 5424)
	tcp {
		port => "${RFC5424_PORT:5424}"
		type => "RFC5424"
		tags => ["syslog"]
	}
	udp {
		port => "${RFC5424_PORT:5424}"
		type => "RFC5424"
		tags => ["syslog"]
	}
}

And you'll have a syslog listener on port 3164 and 5424, use the one that matches Vault requirements and process your messages any way you want in logstash
Cheers

**Comment by timp87** [comment]
> and use the normal syslog vault config
@mterron, I don't think I can. As far as I can see vault can't use syslog via tcp or udp, only local unix socket. Or at least there is no documentation for that.

I know rsyslog for example can redirect logs via TCP in JSON format. But such case would need some additional steps like rsyslog configuration

**Comment by mterron** [comment]
@timp87 You are correct, that's why I said: "...forward your Vault's server local syslog daemon to the Logstash ip...".
It does require syslog configuration, no doubt about it, but it is a reliability concern, as if the audit backend is not available, Vault will halt. In that context, it is a reasonable trade off to just log to local file and local syslog since they are more predictable in their availability/behaviour than remote solutions.

**Comment by timp87** [comment]
I suppose this one can be closed.
New socket backend https://www.vaultproject.io/docs/audit/socket.html can be used.
