### ISSUE TITLE
test/sign defines a CreateOperation but no ExistenceCheck

### ISSUE THREAD

**Issue by haraldh** [hashicorp/vault#22173]
**Describe the bug**

changing the sdk from:
```diff
-       github.com/hashicorp/vault/sdk v0.9.2-0.20230704151349-7522ca248f90
+       github.com/hashicorp/vault/sdk v0.9.2
```

let's my plugin tests fail with:

```
2023-08-02T16:55:57.031+0200 [INFO]  core: http: panic serving 127.0.0.1:56846: Pattern managed-keys/(?P<type>\w(([\w-.]+)?\w)?)/(?P<name>\w(([\w-.]+)?\w)?)/test/sign defines a CreateOperation but no ExistenceCheck
```

introduced by commit [`00e13abf1fe79a00d4564acd634902b7634dbd47`](https://github.com/hashicorp/vault/commit/00e13abf1fe79a00d4564acd634902b7634dbd47) which adds the panic.

with
https://github.com/hashicorp/vault/blob/64f92b40fc5858e1dee68a1be6eddfda859f5698/vault/logical_system_helpers.go#L253-L253

**Comment by maxb** [comment]
The conversation at https://github.com/hashicorp/vault/discussions/22080 may be useful to you.

**Comment by maxb** [comment]
> The conversation at #22080 may be useful to you.

To expand upon this in slightly more detail now that I'm at a real keyboard...

You are combining a post-#18492 `github.com/hashicorp/vault/sdk` with a pre-#18492 `github.com/hashicorp/vault`. This is expected to fail.

Importing `github.com/hashicorp/vault` as a Go module at all is **explicitly not supported** but if you want to do it anyway, you need to be careful about managing its version in sync with the `sdk` module.

You may find this unofficial documentation I wrote helpful: https://github.com/maxb/vault-docs/blob/main/modules.md#what-about-using-githubcomhashicorpvault-itself-as-a-go-module

**Comment by haraldh** [comment]
@maxb Thank you for the explanation!

**Comment by jaredallard** [comment]
I follow the above explanation, but it seems like there may be an actual issue now?

If you attempt to import `github.com/hashicorp/vault@1.14.2` with `github.com/hashicorp/vault/sdk@v0.9.2` ([which is what `1.14.2` is using](https://github.com/hashicorp/vault/tree/v1.14.2/sdk)), the test functions don't work with the above panic.

I went ahead and created a repro here, in case it's useful: https://github.com/jaredallard/vault-issue

**Comment by maxb** [comment]
> `github.com/hashicorp/vault@1.14.2` with `github.com/hashicorp/vault/sdk@v0.9.2` (which is what `1.14.2` is using)

That's not actually the case. In fact you can see here: https://github.com/hashicorp/vault/blob/v1.14.2/go.mod#L23 that vault 1.14.2 is using the copy of sdk embedded within the same commit, which is substantially different to v0.9.2.

You may find the document I wrote about Vault's Go modules useful: https://github.com/maxb/vault-docs/blob/main/modules.md especially the final section which discusses how to select appropriate versions of vault and sdk that are compatible.

**Comment by jaredallard** [comment]
> > `github.com/hashicorp/vault@1.14.2` with `github.com/hashicorp/vault/sdk@v0.9.2` (which is what `1.14.2` is using)
> 
> That's not actually the case. In fact you can see here: [`v1.14.2`/go.mod#L23](https://github.com/hashicorp/vault/blob/v1.14.2/go.mod?rgh-link-date=2023-09-05T08%3A55%3A30Z#L23) that vault 1.14.2 is using the copy of sdk embedded within the same commit, which is substantially different to v0.9.2.
> 
> You may find the document I wrote about Vault's Go modules useful: [maxb/vault-docs@`main`/modules.md](https://github.com/maxb/vault-docs/blob/main/modules.md?rgh-link-date=2023-09-05T08%3A55%3A30Z) especially the final section which discusses how to select appropriate versions of vault and sdk that are compatible.

Hmmmm, I even followed those steps exactly and it always ends up with `go mod tidy` resetting the `/sdk` dependency to `v0.9.2`. To be clear, it's not a blocking issue for me. I had followed those steps for `v1.14.1` and it works as expected.

**Comment by maxb** [comment]
Oh.... I see what's going on here :-(

The version number of sdk listed in the Vault go.mod file is a lie (because it is overridden by the replace directive), but usually it is a lie in the direction of being **too old**.

When it is too old, there's no problem with asking `go get` or `go mod tidy` to actually bring in a newer version.

But, (for the first time ever?) in Vault v1.14.2, the version number of sdk listed there is now **too new**.

This causes `go get` or `go mod tidy` to incorrectly force the version of sdk too high, if you ever try to combine Vault and sdk in your own project.

There is no way to counteract this without using a replace directive of your own.

HashiCorp have been saying for a long time that depending on Vault itself as a Go module is not supported, but it looks like in v1.14.2 it has become newly more difficult to make use of it that way.

Why are you trying to use v1.14.2 anyway? If you have a Vault plugin that you are building use sdk v0.9.2, I'd just use whatever commit of Vault that matches sdk v0.9.2:

```
$ go get github.com/hashicorp/vault{,/sdk}@fd20c99c4a8ae3412308961b813b8dc43f399543
...
$ grep -E '/vault(/sdk)? ' go.mod 
	github.com/hashicorp/vault v1.2.1-0.20230725160220-fd20c99c4a8a
	github.com/hashicorp/vault/sdk v0.9.2
$ go run .
... it works ...
```

**Comment by jaredallard** [comment]
> Why are you trying to use v1.14.2 anyway? If you have a Vault plugin that you are building use sdk v0.9.2, I'd just use whatever commit of Vault that matches sdk v0.9.2:

I'm using it for an integration test of a vault client that we use at my company that's an alternative to the current Go SDK, so using a specific version of Vault is useful for testing compatibility. We use `vault.TestCoreUnsealedWithConfig` to spin up an in-process version of Vault.

Of course, one could say it's much safer to just spin up a docker container of Vault instead. They would be not wrong 😄 

Anyways, 1.14.1 works fine for us now, and if this continues to not function in newer versions of Vault we can just move to using a Docker container with setup/teardown before each test. NBD! Thanks for helping!

**Comment by maxb** [comment]
Yeah... You really should be running Vault as a separate process for that, in order to stick to supported interfaces. Either via Docker, or just run the Vault server binary directly - it's a single file executable with no dependencies, after all.

**Comment by maxb** [comment]
@heliobmartins This is a different issue to what was originally reported - the original issue was about people trying to import Vault itself as a Go module.

The purpose of ExistenceCheck is to allow Vault to decide whether an HTTP PUT/POST is processed as a CreateOperation or an UpdateOperation. When no ExistenceCheck is defined, Vault treats everything as an UpdateOperation. Some people don't know this, and end up implementing a CreateOperation handler even though they have not implemented ExistenceCheck. When this happens, the CreateOperation handler is redundant unreachable code, and Vault's OpenAPI generator used to end up incorrectly claiming `x-vault-createSupported` for such APIs even though they don't actually support create properly.

So I implemented an extra check that detects this incorrect code, and forces it to be corrected. 

If you have existing code that is triggering it, you can simply delete your CreateOperation implementation to resolve the problem.

https://github.com/hashicorp/vault-auth-plugin-example requires no update for this, it is already correct.

**Comment by heliobmartins** [comment]
Oh! I see what it means now @maxb , thanks so much for the help. I really appreciate it. The explanation now is very very clear.
