### ISSUE TITLE
Docker: Vaults join raft cluster as non-voters

### ISSUE THREAD

**Issue by JohannesFleischer** [hashicorp/vault#22189]
**Describe the bug**
When creating a new raft cluster with the official Docker images (1.14.1 or older), the vaults join the initialized vault as non-voters -> only the leader is a voter

**To Reproduce**
see our configs and further information [here](https://discuss.hashicorp.com/t/vault-joins-as-non-voter-in-a-raft-cluster/56644)

1. start three vault instances
2. initialize the first
3. unseal the others (with status-code 200)
4. see `[WARN]  storage.raft: heartbeat timeout reached, not part of a stable configuration or a non-voter, not triggering a leader election` in the non-leader logs and this in the ui:
![grafik](https://github.com/hashicorp/vault/assets/71658262/f1e87f54-fd49-4ae3-86f5-bea10f6d4af2)

**Expected behavior**
Vaults joining as voters

**Environment:**
- `v1/sys/health` output of the non-leaders: 
![grafik](https://github.com/hashicorp/vault/assets/71658262/b776fae7-fdd4-4815-be5c-c3503c223e9b)

- `v1/sys/health` output of the leader:
![grafik](https://github.com/hashicorp/vault/assets/71658262/17b81954-6e23-4836-b678-728b005eeb9f)

* Server Operating System/Architecture:  Ubuntu 22.04 x86_64

Vault server configuration file(s):

see [here](https://discuss.hashicorp.com/t/vault-joins-as-non-voter-in-a-raft-cluster/56644)

**Comment by raskchanky** [comment]
It's normal for standby nodes to join a cluster as non-voters. That's expected. After a stabilization period (default 10s) where each node remains healthy for the given amount of time, autopilot will promote the non-voters to voters. This prevents unhealthy nodes from destabilizing quorum. More details [here](https://developer.hashicorp.com/vault/docs/concepts/integrated-storage/autopilot).

I notice that the sys/health output from your standby nodes shows that they're sealed. They will never get promoted to voters while they're sealed. Note that even after joining nodes to an existing leader, they still need to be unsealed.

**Comment by JohannesFleischer** [comment]
@raskchanky thank you for your reply. That makes a lot of sense!
But what I still don't get is why the vault just does not get unsealed. Because unsealed it in the UI and got an HTTP/200 as a response while doing so. Also, only after I did that, the vaults got listed in the raft cluster.

I would really appreciate it if you'd take a look at the config files, maybe it really is just a stupid misconfiguration I made and that I'm just not able to find it.

**Comment by maxb** [comment]
https://discuss.hashicorp.com/t/vault-joins-as-non-voter-in-a-raft-cluster/56644/7

**Comment by raskchanky** [comment]
@JohannesFleischer The comment @maxb linked to is relevant. Try a cluster address that looks like this in your config file:

`cluster_addr = "https://hashi-vault-1.domain.tld:8201"`

**Comment by JohannesFleischer** [comment]
@raskchanky so that means that it is not possible to forward the requests through a reverse proxy?

Our current setup is, like that:

```mermaid
graph LR;
    A["request"] --> B["reverse proxy (traefik) on 443"] --> C["docker network"];
    C-->D["Vault port 8200 for requests to https://hashi-vault-1.domain.tld"];
    C-->E["Vault port 8201 for requests to https://hashi-vault-1.domain.tld/cluster"];
```

Never thought about that being a problem because the UI works just fine.

**Comment by maxb** [comment]
I already answered this in the forum thread:

> Vault’s internal cluster communication on port 8201 should go nowhere near any proxies - it is strictly from one Vault node directly to another Vault node.

**Comment by raskchanky** [comment]
> I already answered this in the forum thread:
> 
> > Vault’s internal cluster communication on port 8201 should go nowhere near any proxies - it is strictly from one Vault node directly to another Vault node.

This is correct.
