### ISSUE TITLE
Allow users to disable TLS certificate verification for testing Duo MFA method

### ISSUE THREAD

**Issue by zanecodes** [hashicorp/vault#22206]
**Is your feature request related to a problem? Please describe.**
When automating Vault configuration using Terraform, I would like to be able to deploy and test this configuration in isolated development environments. Currently I am using Docker containers for this purpose, and I am able to create and run local instances of Vault as well as its various dependencies such as LDAP, Kerberos, and AWS (using LocalStack), and I can test that my configuration behaves as expected without having to rely on shared external services, or even on a working internet connection.

Unfortunately, I can't do this for my Duo MFA configuration: there is a [mock Duo API docker image](https://hub.docker.com/r/authelia/integration-duo/), but Vault [uses the Duo golang client](https://github.com/hashicorp/vault/blob/6b31e4531734b1a4e5735381bb7efd74ef548ca1/vault/login_mfa.go#L20), which [hardcodes its root CA certificates](https://github.com/duosecurity/duo_api_golang/blob/096d3306c0297ae13d0e7cbd9f79a80a12e4acc9/duoapi.go#L152-L154), making it impossible to use a self-signed certificate with the mock Duo API. This causes `vault login` to fail with TLS verification errors:

```
Error making API request.

URL: POST http://localhost:8200/v1/sys/mfa/validate
Code: 403. Errors:

* failed to satisfy enforcement duo. error: 2 errors occurred:
        * Get "https://localhost/auth/v2/check": tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match localhost
        * login MFA validation failed for methodID: [6c7ace2d-64e2-0e8b-2683-aa7b1ac1d7c1]
```

The Duo golang client does [provide an option](https://github.com/duosecurity/duo_api_golang/blob/096d3306c0297ae13d0e7cbd9f79a80a12e4acc9/duoapi.go#L160) [to disable](https://github.com/duosecurity/duo_api_golang/blob/096d3306c0297ae13d0e7cbd9f79a80a12e4acc9/duoapi.go#L94) [tls verification](https://github.com/duosecurity/duo_api_golang/blob/096d3306c0297ae13d0e7cbd9f79a80a12e4acc9/duoapi.go#L110-L114), but [Vault does not currently expose any way to set it](https://github.com/hashicorp/vault/blob/6b31e4531734b1a4e5735381bb7efd74ef548ca1/vault/login_mfa.go#L1864-L1869).

**Describe the solution you'd like**
I would like to propose the addition of an `insecure` or `insecure_tls` field to Vault's Duo MFA configuration, explicitly only for use in integration testing scenarios. To discourage its use in non-testing scenarios, it might be sensible to omit it from the Vault UI.

I have implemented this change [in a fork](https://github.com/hashicorp/vault/compare/main...zanecodes:vault:duo-insecure), but have not yet added any tests around the functionality; I would be more than happy to add tests further down the line if this feature is accepted.

**Describe alternatives you've considered**
I was unable to find an alternative way to achieve this, and would have to either resign myself to relying on a real Duo server for development, or omit Duo MFA from our development configuration entirely, neither of which is ideal. There are also no other straightforward ways to implement a solution in Vault, short of replacing use of the Duo golang library and writing a wrapper library from scratch which does not implement certificate pinning, which doesn't seem like a good solution.

**Comment by biazmoreira** [comment]
@zanecodes Are you able to add tests to the fork and open a pull request so we can review it and decide if we're going to introduce the changes you're suggesting?

**Comment by hsimon-hashicorp** [comment]
Hello @zanecodes - as it has been some time since we've last heard from you, I'm going to go ahead and close this issue. Please feel free to re-open when you have an opportunity to complete the PR and appropriate tests. Thanks!
