### ISSUE TITLE
Custom Environment Support for Azure Auth

### ISSUE THREAD

**Issue by matt14483** [hashicorp/vault#22250]
I need to configure Azure Auth to work in a closed Azure Environment, that is not listed in the available configuration options.  Since we are adding the Metadata URL during the configuration process anyway, that could be used to configure the environment, rather than the environment parameter.  Terraform and Packer are already configured in such a manner to work in these custom Environments.

**Comment by austingebauer** [comment]
Hi @matt14483 - Would you mind opening this issue up over at https://github.com/hashicorp/vault-plugin-auth-azure? 

In addition to that, it would be helpful to include:
- Links that provide examples of how this is done in Terraform and Packer
- What value you're expecting to be able to provide

**Comment by matt14483** [comment]
Done.  Thank you.
https://github.com/hashicorp/vault-plugin-auth-azure/issues/129

**Comment by austingebauer** [comment]
Thanks! Closing this issue now.
