### ISSUE TITLE
Transit bulk key rotation

### ISSUE THREAD

**Issue by bironran** [hashicorp/vault#2228]
Would it be possible to create a transit api that would receive multiple data keys to be rotated all at once? I can imagine two versions - one that allows a batch of data keys for a single named key and another that receives a collection of pairs named_key->data_key.

This way when an optimization on rotation comes along (e.g. batch db updates) we would not have to change existing APIs.

**Comment by jefferai** [comment]
> This way when an optimization on rotation comes along (e.g. batch db updates) we would not have to change existing APIs.

Can you explain what you mean by this?

**Comment by bironran** [comment]
well, there are 2 reasons really:
1. not incur multiple roundtrip costs
2. open the path for bulk update optimization at the storage layer. If the API is there, anyone can submit the merge request to make a specific storage optimized for such cases.

The reasoning here is that I will need to rotate a few million data keys every few days. I see three limits here - my own data store to fetch the keys and update the rotated ones, app-server -> vault roundtrip costs and vault -> backend update efficiency.

**Comment by jefferai** [comment]
Why not use less keys and use key derivation? Then when you rotate the main key all derived keys are rotated too.

**Comment by bironran** [comment]
sorry - made a mess. I meant re-wrap, not rotate. I'll close this and open a new request.

**Comment by jefferai** [comment]
Oh. Haha. That makes much more sense.  :-D
