### ISSUE TITLE
Vault sealing not working as expected

### ISSUE THREAD

**Issue by ExtremeSwat** [hashicorp/vault#22294]
**Describe the bug**

**To Reproduce**
1. Run vault initialize (v1/sys/init)
2. Run vault unseal(v1/sys/unseal)
3. Create policies for user auth

```
//"vault-auth-policy"
@"path ""userpass/*"" {
                    capabilities = [""create"", ""read"", ""update"", ""delete"", ""list""]
                }"
```

this is a policy for authentication, I'm just replicating all my steps just in case
```
// "duende-secret-engine-policy"
@"path ""duende/*"" {
                    capabilities = [""create"", ""read"", ""update"", ""delete"", ""list""]
                }"
```

seal policy
```
//seal-policy
@"path ""sys/seal"" {
                        capabilities = [""update""]
                    }"
```
4. Create auth method (userpass) (sys/auth/userpass)
5. Create user with token policies ("vault-auth-policy", "duende-secret-engine-policy", "seal-policy")
6. Create secrets engine, whatever, just an optional step
7. Seal Vault

The last step is problematic, it will work with the root token I get once I initialize the Vault, but if then I authenticate with a created user that has the seal-policy update, it will not work at all ! (forbidden error)

I was able to make it work by changing the policy to this:
```
//seal-policy
@"path ""sys/seal"" {
                        capabilities = [""sudo"", "update"]
                    }"
```
Somehow, by adding the sudo capability and the update one will make it work....
The documentation specifies one of them, not both, either have root token or have the update capability..
https://developer.hashicorp.com/vault/api-docs/system/seal#seal

**Expected behavior**
Expected it to seal the vault with the newly created user account that has the vault-seal policy.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.14.0
* Vault CLI Version (retrieve with `vault version`): 1.14.0
* Server Operating System/Architecture: Ubuntu x64

**Comment by VioletHynes** [comment]
The documentation states you need sudo capabilities on the path: 
<img width="702" alt="image" src="https://github.com/hashicorp/vault/assets/1594272/e27b9a20-1109-415a-be5a-da65bc2daaa6">

So I think this is working as expected. You shouldn't be able to seal Vault with just the `update` capability.

**Comment by ExtremeSwat** [comment]
My bad for the upper bad code, I meant that initially I have added just sudo for that policy, and it didn't work for the newly created user, which wasn't enough, only after adding the update capability it has worked.

I can try to re-do the whole thing again and come back with an update, as soon as possible.

**Comment by maxb** [comment]
The sudo capability never allows anything on its own - it always needs to be combined with another normal capability - update in this case.

This is just part of how Vault sudo always works... But I can see how the highlighted text could mislead users not familiar with the concept.
