### ISSUE TITLE
Use an Interface instead of *testing.T directly in the testcluster helper

### ISSUE THREAD

**Issue by c0ffee** [hashicorp/vault#22372]
**Is your feature request related to a problem? Please describe.**
I want to use the docker test functionality in my testbed for a kubernetes operator leveraging the kubebuilder framework und ginkgo. ref https://github.com/hashicorp/vault/blob/5a60c98a464af99c44a1eb62655ede2af3c85ff5/sdk/helper/testcluster/docker/environment.go#L398
ginkgoT() provides an interface that can be used like described here:
https://[onsi.github.io/ginkgo/#third-party-integrations](https://onsi.github.io/ginkgo/#third-party-integrations)

**Describe the solution you'd like**
Changing the function parameter type of t from *testing.T to an Interface. Similiar to how it got solved in consul:
https://github.com/hashicorp/consul/pull/8647

**Describe alternatives you've considered**
Reimplementing the helpers to avoid using testing.T

**Explain any additional use-cases**
It would make the testing functionality of vault way more integratable in other testbeds.

**Additional context**
-

**Comment by ncabatoff** [comment]
Why not just use NewDockerCluster?

**Comment by biazmoreira** [comment]
@c0ffee Have you tried Nick's suggestion? Let me know in case it worked so that we can close out this issue in case it did.

**Comment by hsimon-hashicorp** [comment]
Due to the issue age and quiescence, I'm going to go ahead and close it now. Please feel free to re-open as needed!
