### ISSUE TITLE
Documentation is missing around vault write and updates (specifically partial updates)

### ISSUE THREAD

**Issue by lattwood** [hashicorp/vault#2237]
Docs at https://www.vaultproject.io/docs/commands/read-write.html are unclear as to what the final state of `generic/test` would be when running the following...

```
$ vault write generic/test key1=value1 key2=value2
$ vault write generic/test key2=newvalue2
```

does `generic/test` contain `key1` & `key2` after this, or just `key2`?

**Comment by jefferai** [comment]
Depends on the backend. https://www.vaultproject.io/docs/secrets/generic/index.html clarifies it for the generic backend.
