### ISSUE TITLE
Transit bulk key re-wrapping

### ISSUE THREAD

**Issue by bironran** [hashicorp/vault#2245]
Would it be possible to create a transit api that would receive multiple data keys to be re-wrapped all at once? I can imagine two versions - one that allows a batch of data keys for a single named key and another that receives a collection of pairs named_key->data_key.

This way when an optimization on rotation comes along (e.g. batch db updates) we would not have to change existing APIs.

There are 2 reasons here:
1. not incur multiple roundtrip costs
2. open the path for bulk update optimization at the storage layer. If the API is there, anyone can submit the merge request to make a specific storage optimized for such cases.

The reasoning here is that I will need to rotate a few million data keys every few days. I see three limits here - my own data store to fetch the keys and update the rotated ones, app-server -> vault roundtrip costs and vault -> backend update efficiency.

**Comment by bironran** [comment]
(was originally https://github.com/hashicorp/vault/issues/2228 - but I described rotation rather than re-wrapping by mistake. decided to close that one and open this one in order to avoid further confusion)

**Comment by jefferai** [comment]
I'm actually going to close this in favor of adding more scope to #2143

**Comment by bironran** [comment]
make sense. thanks
