### ISSUE TITLE
Document auth/token/revoke response code

### ISSUE THREAD

**Issue by zmb3** [hashicorp/vault#2248]
The docs for the `auth/token/revoke[/token]` endpoint show that the response code is always `204`.

The response code is indeed 204 if the token is placed in the request body, but when the token is included in the URL the response code is 200.

As written, the docs could lead API consumers to assume that any response code != 204 is an error.

**Comment by jefferai** [comment]
We should fix this to be the same in either case.

**Comment by jefferai** [comment]
Fixed. Thanks for the pointer!
