### ISSUE TITLE
GCPCKMS method starts pods in a crashloop

### ISSUE THREAD

**Issue by kenk667** [hashicorp/vault#22578]
**Describe the bug**
Similar to bug #17850, the gcpckms auto-unseal method when run from terraform deploys containers in a ```CrashLoopBackOff``` state. The logs from any of the containers will read:
```
Error parsing Seal configuration: failed to encrypt with GCP CKMS - ensure the key exists and the service account has at least roles/cloudkms.cryptoKeyEncrypterDecrypter permission: rpc error: code = PermissionDenied desc = Request had insufficient authentication scopes.
2023-08-27T06:06:23.689Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
2023-08-27T06:06:23.690Z [WARN]  storage.raft.fsm: raft FSM db file has wider permissions than needed: needed=-rw------- existing=-rw-rw----
```
I tried to deploy the vault purely from helm with a local values file with the same settings as mt terraform config. At first, there is a lack of documentation in the helm chart that there is a new required field for gcpckms; ```credentials = <value>```. I did find the documentation for the new requirement under the vault documentation: https://developer.hashicorp.com/vault/docs/configuration/seal/gcpckms#credentials

Once I entered the value with a local json key, it worked as expected and deployed vault automatically unsealed. This means that how terraform interacts with helm is flawed when it works within helm alone but not when terraform deploys vault from helm

**To Reproduce**

*Helm provider's token is set from: data.google_client_config.current.access_token

1. You will need a GKE cluster, a service account with sufficient privs (cloudkms.viewer and EncryptorDecryptor), and a KMS key and keyring. 
2. Either write the variables or replace the variables with strings
3. Terrafrom apply then look for the running pods via kubectl get pods --namespace=vault
4. If in crashloop, get logs with: kubectl logs --namespace=vault vault-0

**Expected behavior**
What I expect is the same as when deploying from helm direct, to unseal the vault pods in a good running state

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
# Paste your Vault config here.

resource "helm_release" "vault" {
  name       = "vault"
  namespace  = "vault"
  repository = "https://helm.releases.hashicorp.com"
  chart      = "vault"
  version    = "0.20.1"

  set {
    name  = "server.ha.enabled"
    value = "true"
  }
  set {
    name  = "server.ha.raft.enabled"
    value = "true"
  }
  set {
    name  = "server.ha.raft.setNodeId"
    value = "true"
  }
  set {
    name  = "server.ha.raft.config"
    value = <<EOT
ui = false

listener "tcp" {
  tls_disable = 1
  address = "[::]:8200"
  cluster_address = "[::]:8201"
}

storage "raft" {
  path    = "/vault/data"
}

service_registration "kubernetes" {}

  seal "gcpckms" {
    cerdentials = "Service-account-key.json"
    project     = "${var.project_id}"
    region      = "${var.keyring_location}"
    key_ring    = "${var.keyring_name}"
    crypto_key  = "${var.key_name}"
  }
EOT
  }
}

# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by kenk667** [comment]
@biazmoreira thank you for adding the core/seal label. Do you have insight if this is something that is actively being looked at? I can't imagine that I am the only person that has encountered this bug. Until it is resolved, my only course is to deploy Vault with helm without terraform and prefer to have terraform maintain state

**Comment by onurccn** [comment]
You have a typo in seal configuration on `cerdentials`. Also I don't see you providing any secret file to pod itself. You can provide them using kubernetes secrets as a volume. Helm chart has a support for defining custom volumes and volume mounts. https://github.com/hashicorp/vault-helm/blob/main/values.yaml#L583C12-L583C12

Also you can use default compute engine service account since you're on gke. Just give the required roles to compute engine service account (Assuming you're using default compute engine service account for your gke nodes).

**Comment by kenk667** [comment]
@onurccn great catch on the typo, fixed. I will be trying the volume mounts next, or your second suggestion

**Comment by kenk667** [comment]
@onurccn for the second half of your suggestion;

"Also you can use default compute engine service account since you're on gke (by removing credentials field altogether). Just give the required roles to compute engine service account (Assuming you're using default compute engine service account for your gke nodes)."

Are you talking about service account impersonation? I am trying not to use any service account keys and would have preferred to rely on data "google_client_config" but it seems that gcpckms needs a service account key specifically. Do you have an example of how I can accomplish this without exposing a service account key? I just tried this (https://medium.com/google-cloud/a-hitchhikers-guide-to-gcp-service-account-impersonation-in-terraform-af98853ebd37) and no go

**Comment by onurccn** [comment]
No, not the impersonation. Every gcp vm (including gke nodes) uses compute engine default service account if you don't specify any other service account particularly. https://cloud.google.com/compute/docs/access/service-accounts#compute_engine_service_account. And vault also leverages this service account by default if you don't explicitly set `credentials`. So I'm suggesting that give that default service account required role to google KMS and use that without needing to provide anything to vault helm installation.

**Comment by kenk667** [comment]
@onurccn , I Just tried and it didn't work, my TF version is updated to the latest and I have added appropriate permissions that errors as missing. Below is the error from within one of the containers;

failed to encrypt with GCP CKMS - ensure the key exists and the service account has at least roles/cloudkms.cryptoKeyEncrypterDecrypter permission: rpc error: code = PermissionDenied desc = Request had insufficient authentication scopes.

**Comment by kenk667** [comment]
I am wondering if this is a terraform issue? I am able to deploy vault with helm with the gcpckms stanza with the same info and it deploys fine with auto unseal working.

**Comment by kenk667** [comment]
figured out the solution, I posted it at https://github.com/hashicorp/terraform-provider-helm/issues/1245

**Comment by dayonet** [comment]
The fastest fix I found for this was adding an InitContrainer that manually edits the permissions. You can convert it to match whichever deployment type you're using.
``` yaml
initContainers:
  - name: fix-permissions
    image: busybox
    command: [sh, -c, chmod 600 /vault/data/vault.db]
    volumeMounts:
      - name: data
        mountPath: /vault/data

```
