### ISSUE TITLE
CERT Authentication back end not working on CLI

### ISSUE THREAD

**Issue by lcbowen3** [hashicorp/vault#226]
[root@ip-10-16-19-21 ~]# vault auth -method=cert
Unknown authentication method: cert

Please use a supported authentication method. The list of supported
authentication methods is shown below. Note that this list may not
be exhaustive: Vault may support other auth methods. For auth methods
unsupported by the CLI, please use the HTTP API.

github, userpass

CERT has been accepted into the vault, but the auth isn't working from the command line interface.

**Comment by sethvargo** [comment]
Hi @lcbowen3 

Which version of Vault are you running? Can you please try running off master? Thanks! :smile:

**Comment by lcbowen3** [comment]
Vault v0.1.1-dev (074dcaadac2e0a46ae28f6d491885165b7431aae+CHANGES)

Probably a few days old - set it up last week

Thanks,
Clay

On Tue, May 19, 2015 at 11:43 AM, Seth Vargo <notifications@github.com>
wrote:

> Hi @lcbowen3 <https://github.com/lcbowen3>
>
> Which version of Vault are you running? Can you please try running off
> master? Thanks! [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/vault/issues/226#issuecomment-103585721>.
>



-- 
--------------------------------------------------------
Entia non sunt multiplicanda praeter necessitatem
    - William of Ockham (1288 - ~1348)
--------------------------------------------------------

**Comment by lcbowen3** [comment]
Now using latest version.
[root@ip-10-16-19-21 vault]# vault -version
Vault v0.1.3-dev (1e2dc91e7911b5eb05748896dfb3796adf43457f)

Still no support for CERT:

[root@ip-10-16-19-21 vault]# vault auth -method=cert
Unknown authentication method: cert

Please use a supported authentication method. The list of supported
authentication methods is shown below. Note that this list may not
be exhaustive: Vault may support other auth methods. For auth methods
unsupported by the CLI, please use the HTTP API.

github, ldap, userpass

Thanks,
Clay


On Tue, May 19, 2015 at 12:02 PM, Clay Bowen <on.rode.the.400@gmail.com>
wrote:

> Vault v0.1.1-dev (074dcaadac2e0a46ae28f6d491885165b7431aae+CHANGES)
>
> Probably a few days old - set it up last week
>
> Thanks,
> Clay
>
> On Tue, May 19, 2015 at 11:43 AM, Seth Vargo <notifications@github.com>
> wrote:
>
>> Hi @lcbowen3 <https://github.com/lcbowen3>
>>
>> Which version of Vault are you running? Can you please try running off
>> master? Thanks! [image: :smile:]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hashicorp/vault/issues/226#issuecomment-103585721>.
>>
>
>
>
> --
> --------------------------------------------------------
> Entia non sunt multiplicanda praeter necessitatem
>     - William of Ockham (1288 - ~1348)
> --------------------------------------------------------
>
>


-- 
--------------------------------------------------------
Entia non sunt multiplicanda praeter necessitatem
    - William of Ockham (1288 - ~1348)
--------------------------------------------------------

**Comment by sethvargo** [comment]
Hey Clay,

It looks like that auth isn't currently supported by the CLI, just API right now.

**Comment by lcbowen3** [comment]
The documentation (https://www.vaultproject.io/docs/auth/cert.html) doesn't mention that CLI authentication via this method is not allowed.

My goal is to remove passwords from automation scripts by authenticating the server/user to vault, and then call vault to obtain the passwords, such as the following (to obtain AD user ids):
 
ldapsearch -LLL -E pr=1000/noprompt -x -h <LDAP host> -D <User Name> -w $(vault read secret/<secret name> | grep ^value | awk '{print $2}') -s sub -b  "DC=corp,DC=company,DC=com" samaccountname | grep sAMAccountName | awk '{print $2}' | tr '[:upper:]' '[:lower:]' | sort -u > active.AD

In order for this to work, I need to be able to authenticate the user running the script in a fairly automated way for a very short period (the script runs in cron).  To this end I need a way to authenticate WITHOUT providing a password (as it wouldn't solve anything if I have to hard-code a password in the script).  I could do this using an API call (with curl), but so far the documentation on the API calls for authentication is very sparse.

Perhaps you can provide examples of authentication using the API through curl?

Thanks,
Clay
