### ISSUE TITLE
Multi AD for LDAP Auth: Users vs Groups

### ISSUE THREAD

**Issue by tboussar** [hashicorp/vault#2260]
Hello

for our company we got multiple AD:
**AD1**.active.directory.com
**AD2**.active.directory.com

we have created two ldap providers for authent, 
for AD1 provider
```
    userdn="DC=AD1,DC=active,DC=directory,DC=com" \
    groupdn="OU=Accounts,dc=AD1,dc=active,dc=directory,dc=com" \
```

for AD2 provider
```
    userdn="DC=AD2,DC=active,DC=directory,DC=com" \
    groupdn="OU=Accounts,dc=AD2,dc=active,dc=directory,dc=com" \
```

and it works correctly

for ease of administration we tried to put users from the AD AD2 in same group as user in AD AD1

for AD2 provider
```
    userdn="DC=AD2,DC=active,DC=directory,DC=com" \
    groupdn="OU=Accounts,dc=AD1,dc=active,dc=directory,dc=com" \
```

but it seems we got authent problem and following errors when authenticated a user from AD AD2:

```
 curl $VAULT_ADDR/v1/auth/AD2/login/user02 -d '{ "password": "XXXXXXXXX" }'

{"errors":["LDAP search failed: LDAP Result Code 10 \"Referral\": 0000202B: RefErr: DSID-03100742, data 0, 1 access points\n\tref 1: 'AD1.active.directory.com'\n\u0000"]}
```

our binddn user got rights to connect on both AD

is there a way to authenticate a user in an AD but doing group mapping in another?

Thanks

**Comment by tboussar** [comment]
not sure I was very clear 
when I says "two differents AD", I wanted to say different Domain

Thanks

**Comment by rgruyters** [comment]
@tboussar, can't you use separate paths for each AD Domain?

```
$ vault auth-enable -path=domaina ldap
Successfully enabled 'ldap' at 'domaina'!
$ vault auth-enable -path=domainb ldap
Successfully enabled 'ldap' at 'domainb'!
$ vault write auth/domaina/config \
  userdn="DC=AD1,DC=active,DC=directory,DC=com" \
  groupdn="OU=Accounts,dc=AD1,dc=active,dc=directory,dc=com" \
  ..

$ vault write auth/domainb/config \
  userdn="DC=AD2,DC=active,DC=directory,DC=com" \ 
  groupdn="OU=Accounts,dc=AD2,dc=active,dc=directory,dc=com" \
  ..
```

**Comment by gunglefunk** [comment]
@tboussar Did you ever find a resolution to your issue?  I'm also getting the LDAP Code 10 "Referral" status code back and am trying to figure out if either a)Vault doesn't follow referrals or b)I'm configuring something wrong (more likely)

**Comment by jefferai** [comment]
OP's issue can be handled now with Identity in 0.9 (https://www.vaultproject.io/docs/secrets/identity/index.html). The way you'd do it is you'd assign aliases for users from each mount into the same entity, then assign those entities into a group, and set policies on the group.
