### ISSUE TITLE
Question: Consul Key/Value Backup

### ISSUE THREAD

**Issue by sstarcher** [hashicorp/vault#227]
If I use https://github.com/gmr/consulate to backup the Consul Key/Value store in case of a massive failure of consul.  Would that be sufficient to repopulate Consul and restore Vault.

**Comment by sethvargo** [comment]
Hey @sstarcher 

Thank you for opening an issue. You will need to update your Vault configuration to point to the new Consul cluster that was replicated, but it should work. You will need to unseal the Vault though when you migrate, and there is a potential for data loss depending on the last time you ran consulate.

In the future, please ask these types of questions on the [Vault mailing list](https://groups.google.com/group/vault-tool). We like to keep GitHub issues reserved for bug reports and feature requests. :smile: 

Does that answer your question?

**Comment by sstarcher** [comment]
Much appreciated @sethvargo I'll make sure to use the mailing list next time.
