### ISSUE TITLE
UI failing to copy token

### ISSUE THREAD

**Issue by EschewObfuscaton** [hashicorp/vault#22751]
**Describe the bug**
The sidebar navigation in 1.14.0 onwards allows users to copy their current token to clipboard when the sidebar is fixed.
If Vault isn’t full screen or the screen is rotated to portrait the sidebar collapses. When a user attempts to copy their current token the UI shows the copied pop up in the bottom left but nothing is copied to the clipboard. The user is left with either an empty clipboard or whatever they’d previously copied.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use any version of Vault from 1.14.0 onwards
2. Login with the UI
3. Shrink the Vault window until the sidebar collapses
4. Open the sidebar and copy the token
5. Try to paste

**Expected behaviour**
The user should be able to paste the token or the UI should show that it’s failed to copy the token.

**Environment:**
* Vault Server Version: 1.14.0, 1.14.1, 1.14.2

**Comment by tdy-jbowdre** [comment]
This also seems to be impacting the ability to interact with the Browser CLI (panel appears but the text entry doesn't become active) or switch between namespaces (on Enterprise) if the sidebar is collapsed.

**Comment by Monkeychip** [comment]
@EschewObfuscaton thank you for the issue. We have a fix for the copy token button in [this](https://github.com/hashicorp/vault/pull/23331) PR that will be backported to 1.14.5 and 1.15.1. However, the other two issues mentioned by @tdy-jbowdre will need to be addressed in a separate PR—there's a bit more consideration and problem solving that needs to be done for the namespace picker and console. Thank you both for the comments.

**Comment by tdy-jbowdre** [comment]
Thanks @Monkeychip! Should I break those into separate issues to make it easier for tracking?

**Comment by Monkeychip** [comment]
@tdy-jbowdre That's okay, but thank you for offering. We've got this issue linked to an internal ticket that is in-progress for just the namespace picker and console. I'll keep this GH issue open until it's resolved.

**Comment by Monkeychip** [comment]
@tdy-jbowdre it seems that the fix for the namespace picker and console needed to come from a fix on the HDS (Hashicorp Design Systems) package. Because we can't safely backport a package upgrade, this fix will come in 1.16.0. See PR [here](https://github.com/hashicorp/vault/pull/23580). We added a [known issue](https://github.com/hashicorp/vault/pull/23595) in the meantime.

Thank you both again for the issue and comments.
