### ISSUE TITLE
Can't sign intermediate authority when following documentation

### ISSUE THREAD

**Issue by benjamin-altays** [hashicorp/vault#22761]
**Describe the bug**
When following the documentation : https://developer.hashicorp.com/vault/tutorials/secrets-management/pki-engine on a fresh install at the step 2 : Generate intermediate CA when signing the certificate at .18 I got the error : common name example.com Intermediate Authority not allowed by this role.
I tried to add exemple.com in the domain allowed after but doesn't change anything.

**To Reproduce**
1. Install Vault 1.14.0 with helm chart 0.25.0
2. Follow the doc
3. See error

**Expected behavior**
An intermediate certificate generated.

**Environment:**
* Vault Server Version 1.14.0:
* Server Operating System/Architecture: Rancher/K3S

Vault server configuration file(s):

Default from helm chart

**Comment by cipherboy** [comment]
@benjamin-altays Can you paste the command you ran and the output?

**Comment by benjamin-altays** [comment]
I'm not using command (some doesn't work in webui terminal (it said command usage as if it's not recognized))
So i'm using web ui version of the documentation

**Comment by benjamin-altays** [comment]
In the WEBUi, adding example.com in Allowed Domains and allowing everything for this domain enable the certificate to be signed (that's not indicated in the documentation)
But the certificate isn't recognized as a CA when importing in pki_int after :/

**Comment by benjamin-altays** [comment]
Everything woth fine when following the documentation with the API/cURL

**Comment by cipherboy** [comment]
@benjamin-altays, Ahhh I see. The tutorial is incorrect; in step 14, don't click back to roles, click back to issuers->root CA->sign intermediate. 

![image](https://github.com/hashicorp/vault/assets/914030/45831ee0-b9fa-4e17-90a9-a57b616077ad)

![image](https://github.com/hashicorp/vault/assets/914030/b9b7e1ed-7cb4-40f6-abe7-536eecd89049)

![image](https://github.com/hashicorp/vault/assets/914030/3a5a2828-1d5c-44a8-9e76-63db9cc7edf1)


This version is not bound by the restrictions of the role system and allows arbitrary common names. If you proceed with the route in the tutorial, you end up with a non-CA Leaf certificate, which is not useful.

I'll talk to the tutorials team about fixing that.

**Comment by asucrews** [comment]
Unless i am doing something wrong in version 1.15.0 does not have the option to sign intermediate from the web ui

**Comment by iammathh** [comment]
> Unless i am doing something wrong in version 1.15.0 does not have the option to sign intermediate from the web ui

@asucrews make sure your user has the correct permission levels in the assigned policy, of just use the root token to follow the tutorial.

**Comment by CorentinDeBoisset** [comment]
I managed to adjust the "Generate Intermediate CA" step to work.

I did not need to create a role in the `pki` engine.
I generated the CSR in the new `pki_int` engine as specified - the only difference is that I enabled **Add Basic Constraints* and **Exclude Common Name from SANs** (because the CN is neither an email, DNS or IP).
I copied the resulting CSR.

Then, in the `pki` engine, in the **Issuers** tab:

* Click `root-2023`
* Click **Sign Intermediate**
  * Paste the CSR content
  * Enable **Use CSR Values**
  * Enable **Exclude Common Name from SANs**
  * TTL: whatever
  * Validate
  * Copy the resulting Certificate

Then I can import the certificate in the `pki_int` engine.

**Comment by bemk** [comment]
Dunno if it works in v1.14.0 but for me in v1.15.0 I have to go into the issuers of the root instead, and click "sign intermediate" to sign the intermediate instead.

Looks like a bug in the docs.

**Comment by bemk** [comment]
> Unless i am doing something wrong in version 1.15.0 does not have the option to sign intermediate from the web ui

It's under intermediates instead of roles.

**Comment by VanCannon** [comment]
The tutorial still hasn't been fixed.

**Comment by Dvergatal** [comment]
I have same issues but even worse. For me `pki_int` engine is not being configured and I'm not able to import this intermediate certificate into it. The error I'm getting is like below:
![obraz](https://github.com/hashicorp/vault/assets/72452190/852dc490-9ca7-44d1-b5a9-8d04a12a3f67)

**Comment by Dvergatal** [comment]
OK it appears that webUI is broken with CLI everything works properly...
