### ISSUE TITLE
Misleading term "Client Nonce" in aws-ec2 backend

### ISSUE THREAD

**Issue by moritzheiber** [hashicorp/vault#2278]
The term `nonce` [is closely associated with "number used only once"](https://en.wikipedia.org/wiki/Cryptographic_nonce) in (popular) cryptography.

However, with the `aws-ec2` auth backend it means exactly the opposite. It's rather [a second factor which has to be used over and over again to allow for re-authentication](https://www.vaultproject.io/docs/auth/aws-ec2.html#client-nonce).

I propose the change the terminology from `nonce` to something else (reauth_key?) to avoid confusion (especially since Vault is using the term "nonce" for its regular protocol).

**Comment by moritzheiber** [comment]
cc @fbernitt @vishalnayak @jefferai

**Comment by jefferai** [comment]
Without getting into a debate about "only used once" meaning "can be used for one transaction" vs. "unique from every other value that may be generated", we're going to leave it as is for backwards compatibility.

**Comment by connaryscott** [comment]
I hate the word "nonce" and the link to this stupid thing:  https://www.vaultproject.io/docs/auth/aws-ec2.html#client-nonce  does not exist :(

**Comment by chrishoffman** [comment]
I'll fix the link but you can find the doc here https://www.vaultproject.io/docs/auth/aws.html#client-nonce.
