### ISSUE TITLE
Feature: audit optional arbitrary metadata in every request

### ISSUE THREAD

**Issue by amiryal** [hashicorp/vault#2279]
Similar to the `meta` parameter in `/auth/token/create`, which is passed through to the audit backends, it may be useful to optionally log arbitrary metadata along with every request, to any API endpoint.

The upside: Currently, to achieve the same goal, one might create a single-use token for every operation, and record `meta` at token creation time. With this feature, the extra round trip to the server can be avoided.

The downside: Unless it can be encoded in ACL, every (potentially untrusted) token-holder will be able to inflate the logs with junk.

**Comment by jefferai** [comment]
Is there a clear use-case for this? The downside seems like a very large one.

**Comment by amiryal** [comment]
Given that our users don’t interact with Vault directly, but rather our webservers do that on their behalf, yes, we would like the audit logs to carry information about the real user who initiated any action, in addition to information about the server process that did it on the user’s behalf.

For the time being, we are content with creating a single-use token for each operation, as we can live with the server RTT delay. I put this feature suggestion on the table anyway, but if it does not gather any interest after a while, feel free to close the issue.

**Comment by jefferai** [comment]
There is another ticket about audit logging request headers. Likely we won't audit log *all* headers but would implement an allow list. That might be a better solution to this problem -- your webservers can put identifying info into the client request, and you can configure those as "allowed" headers to add to audit logs.

**Comment by amiryal** [comment]
Thanks, I believe you are referring to #1451.

**Comment by jefferai** [comment]
Closing as a dup of 1451
