### ISSUE TITLE
"OSCP Servers" - Typo at UI endpoint `/ui/vault/secrets/pki_engine_name_here/pki/configuration/edit`

### ISSUE THREAD

**Issue by ipaqmaster** [hashicorp/vault#22839]
**Describe the bug**

I believe there's a typo in the PKI configuration screen

**To Reproduce**

1. Start `vault server -dev`
2. Create a pki engine named anything
3. Click into the newly created engine and go to the Configuration tab, then click Configure on the upper right of that tab.
4. Click "Generate root" just to see the issue more quickly
5. Scroll to the bottom where the phrase `OSCP Servers` is present, but right under it in the descriptive text the correct spelling is present: "Specifies the URL values for the OCSP Servers field. Add one item per row."

**Expected behavior**

Swap the middle two letters of the incorrectly spelled 'OSCP'

**Environment:**
* Vault Server Version (retrieve with `vault status`): Seeing this on versions:
* * Vault v1.14.0 (13a649f860186dffe3f3a4459814d87191efc321), built 2023-06-19T11:40:23Z\
* * Vault v1.14.1 (cgo) (Linux cluster server)
* * Vault v1.14.0 (cgo) (Another Linux cluster server)
* Vault CLI Version (retrieve with `vault version`): As above, 1.14.0
* Server Operating System/Architecture: Linux and Windows builds share the issue.

Vault server configuration file(s): NA, -dev is enough to exhibit the issue.

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by cipherboy** [comment]
I think this was fixed in https://github.com/hashicorp/vault/pull/22586 , which should be in the next release of Vault (1.15).
