### ISSUE TITLE
Fix documentation typo: it create -> it creates

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/vault#22864]
![image](https://github.com/hashicorp/vault/assets/139780495/b0bb9a28-ec59-4f93-bd71-c86d9ff44bb7)

https://developer.hashicorp.com/vault/tutorials/vault-agent/agent-aws

**Comment by officialgupta** [comment]
I am not sure that this documentation is part of this repository

**Comment by akshya96** [comment]
The correct repository associated with this documentation is https://github.com/hashicorp/tutorials.

**Comment by yhyakuna** [comment]
@EugenKon Thank you for reporting. We'll get that fixed. 🙏

**Comment by yhyakuna** [comment]
Typo was fixed, so I'm closing this issue. Thanks.
