### ISSUE TITLE
Full Configuration Documentation

### ISSUE THREAD

**Issue by abedra** [hashicorp/vault#229]
There are quite a few ideas listed in the docs and the intro guide, but there isn't a full "Here's what you can configure and how" listing. It would be nice to better understand what is configurable from the file and what you need to configure from the cli. 

For example, I would like to enable the token and app-id auth backends when the instance is created, but it's unclear if that can be done via a configuration file or if it has to be done on the cli.

**Comment by armon** [comment]
@abedra Everything on the configuration page (https://vaultproject.io/docs/config/index.html) is the full set of configuration options. Everything besides those few settings must be done online via the API/CLI. Most of those settings are security sensitive, so we don't want somebody who can write to the Vault config file to necessarily be able to turn on/off different backends. We can make the docs more clear about this!

**Comment by abedra** [comment]
Ok thanks. That does make sense.
