### ISSUE TITLE
Eucalyptus endpoint-url

### ISSUE THREAD

**Issue by ror6ax** [hashicorp/vault#2291]
I'm looking for a way to use endpoint-url respected by go sdk
works in cli, but I can't find a way to point Vault to non-AWS endpoints
I suppose I'm not the first to use aws clones, like Eucalyptus
there is a method in Vault
```
// getClientConfig creates a aws-sdk-go config, which is used to create client
// that can interact with AWS API. This builds credentials in the following
// order of preference:
//
// * Static credentials from 'config/client'
// * Environment variables
// * Instance metadata role
```
does this mean there is a way to set endpoint\s in config file?
```
        endpoint := aws.String("")
        if config != nil {
                // Override the default endpoint with the configured endpoint.
                if config.Endpoint != "" {
                        endpoint = aws.String(config.Endpoint)
```
I've tried to set endpoint := "http://myeucalyptusurl" but it seems to have no effect.

Another question would be what kind of endpoint does Vault expect, since IAM and S3 for example have different urls in Eucalyptus.

**Comment by jefferai** [comment]
Asked on mailing list, closing.
