### ISSUE TITLE
CRL config entries cannot be saved due to large size

### ISSUE THREAD

**Issue by jbrandhorst** [hashicorp/vault#22980]
**Describe the bug**
We are running Consul Connect, with Vault in use as the Connect CA.  DynamoDB is used for Vault storage. When Consul switches leadership it does a "CA initialization" routine, which generates a new PKI issuer each time.  Over time the number of issuers grows, and eventually it reaches a point where the CA initialization fails, because the CRL rebuild step tries saving a CRL config entry so large that it exceeds the DynamoDB max record size, and Consul CA initialization does not complete on the Consul side.

This is the error that Consul reports, which includes the embedded error strings from Vault:
```
"level":"error"

"message":"Failed to initialize Connect CA","module":"connect.ca","error":"error generating intermediate cert: Error making API request.URL: PUT https://vault/v1/<pki name>/intermediate/set-signed Code: 500. 
Errors:* 1 error occurred:* Rebuilding the CRL failed. While this is indicative of a problem with the imported issuers (perhaps because of their revocation_signature_algorithm), they did import successfully and are now usable. 
It is strongly suggested to fix the CRL building errors before continuing. 
The original error is reproduced below:error building CRLs: unable to persist updated cluster-local CRL config: ValidationException: Item size has exceeded the maximum allowed size status code: 400"

"routine":"CA initialization"
```

Based on the specific error strings included in the log, the problem is occurring when an internalCRLConfigEntry is written to DynamoDB: https://github.com/hashicorp/vault/blob/2e30ad5a938de2b417fb33538f7e5378f5380101/builtin/logical/pki/storage.go#L189-L197

After analysis of the entries in the DynamoDB table, at the path `logical/<secret engine UUID>/crls` there is an item with a key `config` where this config entry is stored. When the CRL build occurs it cannot save the entry to DynamoDB because the size is now larger than DynamoDB's max field size of 400KB. 

**To Reproduce**
1. Set up Consul Connect with Vault as the CA
2. Let a number of Consul leadership transitions occur over time
3. The number of issuers in Vault under the path `/v1/<pki name>/issuer/<UUID>/` grows
4. Eventually a leadership transition in Consul occurs and the error above will occur because the CRL config cannot be saved when Consul Connect does its ca initialization.

We manually deleted a number of the issuers from DynamoDB in order to get past the condition and get Consul functioning again, as there did not seem to be any operator commands that would help (tidy did not help because the issuers were not expired yet)

**Expected behavior**
We would like to know:

1. Our CRLs are actually empty, can we simply disable CRL builds to avoid running into this problem?
2. Manually deleting issuer records from DynamoDB seems like a less-than-ideal remediation step, are there any vault operator commands that can address this type of issue?
3. We intend to modify the TTL of the Consul Connect CA intermediate cert to hopefully cut down the number of active issuers, it is currently still set as the Consul default of 1 year (8760h).  Are there any other configuration settings we should look into that can reduce the size of the CRL config entry that is stored in DynamoDB? 

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.14.1
* Vault CLI Version (retrieve with `vault version`): v1.12.4
* Server Operating System/Architecture: Alpine Linux v.3.15 (using the Vault docker image from https://hub.docker.com/layers/hashicorp/vault/1.14/images/sha256-7491542ac45b0d76b2eda4504a1b2310a4577a24cab7f7c1c34f274fcd4698f4?context=explore) 
* Consul version: 1.15.3

Vault server configuration file(s):

```hcl
(let me know what specific hcl is helpful here and I can edit the original post)
```

**Additional context**
1. It seems that when manually deleting old issuers, the amount of space freed in the CRL config entry (~78 bytes) is less than the amount of space consumed in the storage when a new issuer is added (~240 bytes). So even if you delete old issuers regularly the size of the CRL config will still continue to grow and may eventually run into this problem. 

2. When Consul Connect is unable complete it's "CA Initialization" when encountering the CRL max record size issue it tries to reinitialize repeatedly. These attempts to initialize actually generates new issuers in Vault each time, but meanwhile Consul Connect does not actually function when it encounters the error.  The repeated creation of more issuers that are unused by Consul compounds the problem, and then requires a lot more manual cleanup of the issuers that were created by Consul when Connect was in a non-functioning state.

**Comment by jkirschner-hashicorp** [comment]
Hi @jbrandhorst,

I just re-opened a related issue on the Consul repo that your post suggests was not fully closed.

For context, how many issuers were within Vault's `/v1/<pki name>` when you hit the reported error from Consul?

**Comment by jbrandhorst** [comment]
> Hi @jbrandhorst,
> 
> I just re-opened a related issue on the Consul repo that your post suggests was not fully closed.
> 
> For context, how many issuers were within Vault's `/v1/<pki name>` when you hit the reported error from Consul?

Thanks @jkirschner-hashicorp - there were 1850 issuers

**Comment by jkirschner-hashicorp** [comment]
PR in progress on the Consul side: https://github.com/hashicorp/consul/pull/18773

**Comment by ksmiley** [comment]
I noticed there's an [`EncodeJSONAndCompress`](https://github.com/hashicorp/vault/blob/a166cf67866e2ae69414da7d0f33f3239ce26034/sdk/helper/jsonutil/json.go#L34) that seems to be a drop-in replacement for for the uncompressed `EncodeJSON` that this record uses currently. Could that be used here? There's a decent amount of repetition in the CRL config JSON blob (e.g. each CRL identifier is repeated four times), so it should compress well. It's not exactly a fix, but it would at least increase the number of issuers that it takes to hit the storage limit.

**Comment by cipherboy** [comment]
\o hey @ksmiley 

Interesting thought... In general, simple managed rotation like this without cross signing is the easy case to trigger this. As the number of issues grow, the automated chain building that occurs when issuers are added will be much slower than storage limitations... I think `O(n log n)` in the average case but IIRC `O(n^3 log n)` in the worst case for issuers with lots of cliques? If Consul instead switched to cross-signing, this would also slow down chain building and likely run into context deadline exceeded errors, rather than failure to write to storage due to size limitations... So I'd probably avoid having hundres or thousands of issuers within a single mount and stick to tens or at most low hundreds of issuers anyways (also, CRL building & certificate->issuer attribution gets slower with this many issuers as well, except if there are no revocations but even that requires writing & updating empty CRLs).

So you're absolutely right that it could help with this case, but I think you might not want a thousand or more in the mount anyways :-)
