### ISSUE TITLE
List all tokens created by an AppRole role_id

### ISSUE THREAD

**Issue by kidambisrinivas** [hashicorp/vault#2301]
Is it possible to 

- list all tokens created by an AppRole role_id
- Store meta data with token like purpose or service using it for quick identification and maintainer
- Send out email notifications to maintainer when expiry date is close

**Comment by jefferai** [comment]
No, none of this is possible.

**Comment by kidambisrinivas** [comment]
Thanks for clarifying. 

Would you suggest writing a tool to augment data in vault with these housekeeping data for managing a lot of apps?

**Comment by jefferai** [comment]
I'm not sure what such a tool would look like, but you may want to look at the auth/token/list-accessors call which can allow you to iterate over token accessors; using that you could look at returned metadata from a lookup-accessor call to determine approle role ID. If you create tokens directly you can attach metadata but not when creating via approle.

**Comment by kidambisrinivas** [comment]
Oh, sure. I'll try the above workflow and try using list-accessors.

I was thinking a web service to wrap token creation in vault to take the following

- role_id
- service/token_name
- ttl
- policies
- maintainer_email

and add some metadata as secrets in the path housekeeping/role/<role_id>/<service_name>

The AppRole role_id will be given access to its own housekeeping path so a role_id can list all services for which it has created tokens. The same web service could then iterate through the housekeeping and notify the maintainer when a token is going to expire. This is to prevent downtime of services whose tokens cannot be renewed since they've exhausted system max-ttl.

**Comment by kidambisrinivas** [comment]
Oh k, sure. I'll try the following:

- Use named roles [here](https://www.vaultproject.io/docs/auth/token.html) endpoint /auth/token/roles/<role_name>
- Iterate through tokens using list accessor endpoint /auth/token/accessors?list=true

How is the named role created above different from [AppRole](https://www.vaultproject.io/docs/auth/approle.html)?

**Comment by jefferai** [comment]
> This is to prevent downtime of services whose tokens cannot be renewed since they've exhausted system max-ttl.

For long running services you should look at using periodic tokens...Then you don't have this problem!

**Comment by georgesmith2017** [comment]
There must be an internal mechanism that identifies all child tokens for a given parent token. Otherwise, it would be impossible to revoke all child tokens automatically, when the parent token is revoked. So, the only question is, why it isn't exposed via the Vault CLI or API for administrative purposes?
