### ISSUE TITLE
Documentation - Getting started - missing client token

### ISSUE THREAD

**Issue by LarsJansen-Ultraware** [hashicorp/vault#2304]
Hello, 

While doing the getting started manual, I found a mistake (or I am doing something wrong).
When I execute `vault write secret/hello value=world` on the dev-server, the output is:
```
Error writing data to secret/hello: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/secret/hello
Code: 400. Errors:

* missing client token
```

`vault status` returns this:
```
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0
Version: 0.6.4
Cluster Name: vault-cluster-f5debeed
Cluster ID: d6221ca2-e1af-2420-bf54-a5b1cfbf84e4

High-Availability Enabled: false
```

What should I do?

Kind regards,
Lars Jansen

**Comment by LarsJansen-Ultraware** [comment]
Problem solved. The server was running as root, but I was executing the command as a non-root user.

**Comment by jefferai** [comment]
Hi @LarsJansen-Ultraware ,

You don't need to run the client (or Vault) as root; however when you make a dev server it saves the token to ~/.vault-token so if you are using a different user it won't have been saved to the right user account.
