### ISSUE TITLE
Unknown backend type: etcd

### ISSUE THREAD

**Issue by joaoh82** [hashicorp/vault#2306]
I have a etcd.hcl file like this:
```
backend "etcd" {
    address = "http://127.0.0.1:2379"
    path = "vault"
}

listener "tcp" {
    address = "127.0.0.1:8200"
    tls_disable = 1
}
```
And I am starting my vault with:
vault server -config=etcd.hcl

Which starts ok... But after that I try to mount etcd and I get this error:
URL: POST http://127.0.0.1:8200/v1/sys/mounts/etcd
Code: 400. Errors:

* unknown backend type: etcd

What am I doing wrong??

**Comment by jefferai** [comment]
Hi there,

The backend in your config file is for Vault's data store, which Vault will use automatically. You don't need to mount it!

**Comment by joaoh82** [comment]
Thanks!!
