### ISSUE TITLE
Unit Test failed with "make cover" OSX ( go version go1.7.4 darwin/amd64 )

### ISSUE THREAD

**Issue by Rushit** [hashicorp/vault#2307]
`
$GOPATH/src/github.com/hashicorp/vault (master) $ make bootstrap && make dev
$GOPATH/src/github.com/hashicorp/vault (master) $ make cover
./scripts/coverage.sh --html
ok  	github.com/hashicorp/vault	0.043s	coverage: 0.0% of statements
ok  	github.com/hashicorp/vault/api	0.430s	coverage: 27.4% of statements
ok  	github.com/hashicorp/vault/audit	0.030s	coverage: 41.6% of statements
ok  	github.com/hashicorp/vault/builtin/audit/file	0.027s	coverage: 44.9% of statements
?   	github.com/hashicorp/vault/builtin/audit/syslog	[no test files]
ok  	github.com/hashicorp/vault/builtin/credential/app-id	0.096s	coverage: 70.8% of statements
ok  	github.com/hashicorp/vault/builtin/credential/approle	0.052s	coverage: 64.5% of statements
ok  	github.com/hashicorp/vault/builtin/credential/aws-ec2	0.057s	coverage: 42.3% of statements
ok  	github.com/hashicorp/vault/builtin/credential/cert	0.227s	coverage: 66.0% of statements
ok  	github.com/hashicorp/vault/builtin/credential/github	0.028s	coverage: 5.5% of statements
ok  	github.com/hashicorp/vault/builtin/credential/ldap	0.378s	coverage: 55.3% of statements
ok  	github.com/hashicorp/vault/builtin/credential/userpass	1.619s	coverage: 59.3% of statements
ok  	github.com/hashicorp/vault/builtin/logical/aws	0.029s	coverage: 10.1% of statements
ok  	github.com/hashicorp/vault/builtin/logical/cassandra	126.628s	coverage: 52.2% of statements

ok  	github.com/hashicorp/vault/builtin/logical/consul	41.722s	coverage: 73.6% of statements
ok  	github.com/hashicorp/vault/builtin/logical/mongodb	9.379s	coverage: 65.0% of statements
ok  	github.com/hashicorp/vault/builtin/logical/mssql	0.040s	coverage: 11.7% of statements
ok  	github.com/hashicorp/vault/builtin/logical/mysql	72.363s	coverage: 73.9% of statements
2017/01/26 15:25:37.630884 [TRACE] physical/cache: creating LRU cache: size=32768
2017/01/26 15:25:37.632446 [INFO ] core: security barrier not initialized
2017/01/26 15:25:37.632961 [INFO ] core: security barrier initialized: shares=1 threshold=1
2017/01/26 15:25:37.633080 [TRACE] core: cluster name not found/set, generating new
2017/01/26 15:25:37.633094 [DEBUG] core: cluster name set: name=vault-cluster-b02720f5
2017/01/26 15:25:37.633103 [TRACE] core: cluster ID not found, generating new
2017/01/26 15:25:37.633113 [DEBUG] core: cluster ID set: id=d4c9f586-75be-f0ae-c537-a9304d862deb
2017/01/26 15:25:37.633144 [INFO ] core: post-unseal setup starting
2017/01/26 15:25:37.645534 [INFO ] core: loaded wrapping token key
2017/01/26 15:25:37.645906 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:25:37.645924 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:25:37.646004 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:25:37.646063 [INFO ] rollback: starting rollback manager
2017/01/26 15:25:37.646536 [INFO ] core: post-unseal setup complete
2017/01/26 15:25:37.646636 [INFO ] core: root token generated
2017/01/26 15:25:37.646641 [INFO ] core: pre-seal teardown starting
2017/01/26 15:25:37.646669 [INFO ] rollback: stopping rollback manager
2017/01/26 15:25:37.646680 [INFO ] core: pre-seal teardown complete
2017/01/26 15:25:37.646733 [INFO ] core: vault is unsealed
2017/01/26 15:25:37.646746 [INFO ] core: post-unseal setup starting
2017/01/26 15:25:37.646766 [INFO ] core: loaded wrapping token key
2017/01/26 15:25:37.646848 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:25:37.646860 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:25:37.646914 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:25:37.646970 [INFO ] rollback: starting rollback manager
2017/01/26 15:25:37.647331 [INFO ] core: post-unseal setup complete
2017/01/26 15:25:37.649617 [INFO ] core: successful mount: path=mnt/ type=test
2017/01/26 15:25:53.426234 [TRACE] physical/cache: creating LRU cache: size=32768
2017/01/26 15:25:53.426257 [INFO ] core: security barrier not initialized
2017/01/26 15:25:53.426297 [INFO ] core: security barrier initialized: shares=1 threshold=1
2017/01/26 15:25:53.426359 [TRACE] core: cluster name not found/set, generating new
2017/01/26 15:25:53.426368 [DEBUG] core: cluster name set: name=vault-cluster-4d56aab2
2017/01/26 15:25:53.426376 [TRACE] core: cluster ID not found, generating new
2017/01/26 15:25:53.426382 [DEBUG] core: cluster ID set: id=cf75152a-d38f-efac-fdfc-656fe7f22cdf
2017/01/26 15:25:53.426396 [INFO ] core: post-unseal setup starting
2017/01/26 15:25:53.437362 [INFO ] core: loaded wrapping token key
2017/01/26 15:25:53.437826 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:25:53.437843 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:25:53.437905 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:25:53.437956 [INFO ] rollback: starting rollback manager
2017/01/26 15:25:53.438299 [INFO ] core: post-unseal setup complete
2017/01/26 15:25:53.438349 [INFO ] core: root token generated
2017/01/26 15:25:53.438364 [INFO ] core: pre-seal teardown starting
2017/01/26 15:25:53.438372 [INFO ] rollback: stopping rollback manager
2017/01/26 15:25:53.438397 [INFO ] core: pre-seal teardown complete
2017/01/26 15:25:53.438445 [INFO ] core: vault is unsealed
2017/01/26 15:25:53.438458 [INFO ] core: post-unseal setup starting
2017/01/26 15:25:53.438476 [INFO ] core: loaded wrapping token key
2017/01/26 15:25:53.438537 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:25:53.438549 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:25:53.438596 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:25:53.438644 [INFO ] rollback: starting rollback manager
2017/01/26 15:25:53.439009 [INFO ] core: post-unseal setup complete
2017/01/26 15:25:53.441315 [INFO ] core: successful mount: path=mnt/ type=test
2017/01/26 15:26:09.347421 [TRACE] physical/cache: creating LRU cache: size=32768
2017/01/26 15:26:09.347461 [INFO ] core: security barrier not initialized
2017/01/26 15:26:09.347570 [INFO ] core: security barrier initialized: shares=1 threshold=1
2017/01/26 15:26:09.347614 [TRACE] core: cluster name not found/set, generating new
2017/01/26 15:26:09.347622 [DEBUG] core: cluster name set: name=vault-cluster-484fe112
2017/01/26 15:26:09.347630 [TRACE] core: cluster ID not found, generating new
2017/01/26 15:26:09.347637 [DEBUG] core: cluster ID set: id=c6c9826a-d8b6-a69c-e65d-dbc96c7dac61
2017/01/26 15:26:09.347663 [INFO ] core: post-unseal setup starting
2017/01/26 15:26:09.358210 [INFO ] core: loaded wrapping token key
2017/01/26 15:26:09.359018 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:26:09.359057 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:26:09.359124 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:26:09.359187 [INFO ] rollback: starting rollback manager
2017/01/26 15:26:09.359564 [INFO ] core: post-unseal setup complete
2017/01/26 15:26:09.359612 [INFO ] core: root token generated
2017/01/26 15:26:09.359618 [INFO ] core: pre-seal teardown starting
2017/01/26 15:26:09.359627 [INFO ] rollback: stopping rollback manager
2017/01/26 15:26:09.359640 [INFO ] core: pre-seal teardown complete
2017/01/26 15:26:09.359697 [INFO ] core: vault is unsealed
2017/01/26 15:26:09.359719 [INFO ] core: post-unseal setup starting
2017/01/26 15:26:09.359748 [INFO ] core: loaded wrapping token key
2017/01/26 15:26:09.359911 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:26:09.359934 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:26:09.359988 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:26:09.360049 [INFO ] rollback: starting rollback manager
2017/01/26 15:26:09.360398 [INFO ] core: post-unseal setup complete
2017/01/26 15:26:09.362621 [INFO ] core: successful mount: path=mnt/ type=test
2017/01/26 15:26:09.978056 [TRACE] physical/cache: creating LRU cache: size=32768
2017/01/26 15:26:09.978104 [INFO ] core: security barrier not initialized
2017/01/26 15:26:09.978179 [INFO ] core: security barrier initialized: shares=1 threshold=1
2017/01/26 15:26:09.978251 [TRACE] core: cluster name not found/set, generating new
2017/01/26 15:26:09.978312 [DEBUG] core: cluster name set: name=vault-cluster-843f545f
2017/01/26 15:26:09.978326 [TRACE] core: cluster ID not found, generating new
2017/01/26 15:26:09.978339 [DEBUG] core: cluster ID set: id=0fbdc1f0-b9ff-a936-f262-a27216153334
2017/01/26 15:26:09.978402 [INFO ] core: post-unseal setup starting
2017/01/26 15:26:09.992917 [INFO ] core: loaded wrapping token key
2017/01/26 15:26:09.993395 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:26:09.993424 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:26:09.993493 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:26:09.993543 [INFO ] rollback: starting rollback manager
2017/01/26 15:26:09.993917 [INFO ] core: post-unseal setup complete
2017/01/26 15:26:09.993965 [INFO ] core: root token generated
2017/01/26 15:26:09.993970 [INFO ] core: pre-seal teardown starting
2017/01/26 15:26:09.993979 [INFO ] rollback: stopping rollback manager
2017/01/26 15:26:09.993987 [INFO ] core: pre-seal teardown complete
2017/01/26 15:26:09.994037 [INFO ] core: vault is unsealed
2017/01/26 15:26:09.994060 [INFO ] core: post-unseal setup starting
2017/01/26 15:26:09.994082 [INFO ] core: loaded wrapping token key
2017/01/26 15:26:09.994188 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:26:09.994202 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:26:09.994273 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:26:09.994316 [INFO ] rollback: starting rollback manager
2017/01/26 15:26:09.994692 [INFO ] core: post-unseal setup complete
2017/01/26 15:26:09.996709 [INFO ] core: successful mount: path=mnt/ type=test
2017/01/26 15:26:10.371863 [TRACE] physical/cache: creating LRU cache: size=32768
2017/01/26 15:26:10.371882 [INFO ] core: security barrier not initialized
2017/01/26 15:26:10.371941 [INFO ] core: security barrier initialized: shares=1 threshold=1
2017/01/26 15:26:10.372018 [TRACE] core: cluster name not found/set, generating new
2017/01/26 15:26:10.372026 [DEBUG] core: cluster name set: name=vault-cluster-b06aacb9
2017/01/26 15:26:10.372045 [TRACE] core: cluster ID not found, generating new
2017/01/26 15:26:10.372051 [DEBUG] core: cluster ID set: id=07e75053-c434-64b8-5c97-c7d16f47fbb7
2017/01/26 15:26:10.372088 [INFO ] core: post-unseal setup starting
2017/01/26 15:26:10.382732 [INFO ] core: loaded wrapping token key
2017/01/26 15:26:10.383618 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:26:10.383670 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:26:10.384062 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:26:10.384110 [INFO ] rollback: starting rollback manager
2017/01/26 15:26:10.384473 [INFO ] core: post-unseal setup complete
2017/01/26 15:26:10.384523 [INFO ] core: root token generated
2017/01/26 15:26:10.384528 [INFO ] core: pre-seal teardown starting
2017/01/26 15:26:10.384558 [INFO ] rollback: stopping rollback manager
2017/01/26 15:26:10.384581 [INFO ] core: pre-seal teardown complete
2017/01/26 15:26:10.384644 [INFO ] core: vault is unsealed
2017/01/26 15:26:10.384658 [INFO ] core: post-unseal setup starting
2017/01/26 15:26:10.384680 [INFO ] core: loaded wrapping token key
2017/01/26 15:26:10.384755 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:26:10.384767 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:26:10.384817 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:26:10.384874 [INFO ] rollback: starting rollback manager
2017/01/26 15:26:10.385213 [INFO ] core: post-unseal setup complete
2017/01/26 15:26:10.386907 [INFO ] core: successful mount: path=mnt/ type=test
--- FAIL: TestBackend_RSARoles (5.90s)
	backend_test.go:1428: seed under test: 1485473170369633135
	testing.go:282: Failed step 151: Error: returned certificate has OU of [bar] but [bar foo] was specified in the role.
2017/01/26 15:26:16.269218 [TRACE] physical/cache: creating LRU cache: size=32768
2017/01/26 15:26:16.269256 [INFO ] core: security barrier not initialized
2017/01/26 15:26:16.269304 [INFO ] core: security barrier initialized: shares=1 threshold=1
2017/01/26 15:26:16.269370 [TRACE] core: cluster name not found/set, generating new
2017/01/26 15:26:16.269379 [DEBUG] core: cluster name set: name=vault-cluster-f199aa67
2017/01/26 15:26:16.269387 [TRACE] core: cluster ID not found, generating new
2017/01/26 15:26:16.269402 [DEBUG] core: cluster ID set: id=0a0777b3-477e-778b-abcf-6eb8b9ce6327
2017/01/26 15:26:16.269439 [INFO ] core: post-unseal setup starting
2017/01/26 15:26:16.283716 [INFO ] core: loaded wrapping token key
2017/01/26 15:26:16.284655 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:26:16.284676 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:26:16.284772 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:26:16.284884 [INFO ] rollback: starting rollback manager
2017/01/26 15:26:16.285293 [INFO ] core: post-unseal setup complete
2017/01/26 15:26:16.285343 [INFO ] core: root token generated
2017/01/26 15:26:16.285349 [INFO ] core: pre-seal teardown starting
2017/01/26 15:26:16.285357 [INFO ] rollback: stopping rollback manager
2017/01/26 15:26:16.285366 [INFO ] core: pre-seal teardown complete
2017/01/26 15:26:16.285411 [INFO ] core: vault is unsealed
2017/01/26 15:26:16.285422 [INFO ] core: post-unseal setup starting
2017/01/26 15:26:16.285441 [INFO ] core: loaded wrapping token key
2017/01/26 15:26:16.285506 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:26:16.285517 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:26:16.285567 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:26:16.285625 [INFO ] rollback: starting rollback manager
2017/01/26 15:26:16.285960 [INFO ] core: post-unseal setup complete
2017/01/26 15:26:16.287495 [INFO ] core: successful mount: path=mnt/ type=test
--- FAIL: TestBackend_RSARoles_CSR (5.78s)
	backend_test.go:1428: seed under test: 1485473176265293821
	testing.go:282: Failed step 151: Error: returned certificate has OU of [bar] but [bar foo] was specified in the role.
2017/01/26 15:26:22.044155 [TRACE] physical/cache: creating LRU cache: size=32768
2017/01/26 15:26:22.044187 [INFO ] core: security barrier not initialized
2017/01/26 15:26:22.044240 [INFO ] core: security barrier initialized: shares=1 threshold=1
2017/01/26 15:26:22.044319 [TRACE] core: cluster name not found/set, generating new
2017/01/26 15:26:22.044338 [DEBUG] core: cluster name set: name=vault-cluster-5153992a
2017/01/26 15:26:22.044344 [TRACE] core: cluster ID not found, generating new
2017/01/26 15:26:22.044352 [DEBUG] core: cluster ID set: id=69fb30fd-6386-cf71-d415-84c44c34e765
2017/01/26 15:26:22.044367 [INFO ] core: post-unseal setup starting
2017/01/26 15:26:22.054902 [INFO ] core: loaded wrapping token key
2017/01/26 15:26:22.055427 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:26:22.055443 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:26:22.055507 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:26:22.055565 [INFO ] rollback: starting rollback manager
2017/01/26 15:26:22.055916 [INFO ] core: post-unseal setup complete
2017/01/26 15:26:22.055975 [INFO ] core: root token generated
2017/01/26 15:26:22.055991 [INFO ] core: pre-seal teardown starting
2017/01/26 15:26:22.056001 [INFO ] rollback: stopping rollback manager
2017/01/26 15:26:22.056011 [INFO ] core: pre-seal teardown complete
2017/01/26 15:26:22.056055 [INFO ] core: vault is unsealed
2017/01/26 15:26:22.056079 [INFO ] core: post-unseal setup starting
2017/01/26 15:26:22.056108 [INFO ] core: loaded wrapping token key
2017/01/26 15:26:22.056171 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:26:22.056183 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:26:22.056255 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:26:22.056304 [INFO ] rollback: starting rollback manager
2017/01/26 15:26:22.056662 [INFO ] core: post-unseal setup complete
2017/01/26 15:26:22.058611 [INFO ] core: successful mount: path=mnt/ type=test
--- FAIL: TestBackend_ECRoles (8.19s)
	backend_test.go:1428: seed under test: 1485473182041727830
	testing.go:282: Failed step 151: Error: returned certificate has OU of [bar] but [bar foo] was specified in the role.
2017/01/26 15:26:33.254770 [TRACE] physical/cache: creating LRU cache: size=32768
2017/01/26 15:26:33.254823 [INFO ] core: security barrier not initialized
2017/01/26 15:26:33.254875 [INFO ] core: security barrier initialized: shares=1 threshold=1
2017/01/26 15:26:33.254919 [TRACE] core: cluster name not found/set, generating new
2017/01/26 15:26:33.254928 [DEBUG] core: cluster name set: name=vault-cluster-1f65f28f
2017/01/26 15:26:33.254936 [TRACE] core: cluster ID not found, generating new
2017/01/26 15:26:33.254943 [DEBUG] core: cluster ID set: id=eb534f97-8b3c-57ee-c10c-21b202ef3e60
2017/01/26 15:26:33.254958 [INFO ] core: post-unseal setup starting
2017/01/26 15:26:33.264529 [INFO ] core: loaded wrapping token key
2017/01/26 15:26:33.264871 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:26:33.264899 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:26:33.264967 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:26:33.265016 [INFO ] rollback: starting rollback manager
2017/01/26 15:26:33.265367 [INFO ] core: post-unseal setup complete
2017/01/26 15:26:33.265413 [INFO ] core: root token generated
2017/01/26 15:26:33.265418 [INFO ] core: pre-seal teardown starting
2017/01/26 15:26:33.265427 [INFO ] rollback: stopping rollback manager
2017/01/26 15:26:33.265437 [INFO ] core: pre-seal teardown complete
2017/01/26 15:26:33.265482 [INFO ] core: vault is unsealed
2017/01/26 15:26:33.265506 [INFO ] core: post-unseal setup starting
2017/01/26 15:26:33.265535 [INFO ] core: loaded wrapping token key
2017/01/26 15:26:33.265627 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/01/26 15:26:33.265652 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/01/26 15:26:33.265705 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/01/26 15:26:33.265748 [INFO ] rollback: starting rollback manager
2017/01/26 15:26:33.266105 [INFO ] core: post-unseal setup complete
2017/01/26 15:26:33.268953 [INFO ] core: successful mount: path=mnt/ type=test
--- FAIL: TestBackend_ECRoles_CSR (4.17s)
	backend_test.go:1428: seed under test: 1485473190227785261
	testing.go:282: Failed step 151: Error: returned certificate has OU of [bar] but [bar foo] was specified in the role.
FAIL
coverage: 70.1% of statements
FAIL	github.com/hashicorp/vault/builtin/logical/pki	59.700s
make: *** [cover] Error 1
`

**Comment by jefferai** [comment]
See the readme...master requires Go 1.8 (currently in RC).
