### ISSUE TITLE
Reading KV from file generates `invalid key/value pair`

### ISSUE THREAD

**Issue by wiwwo** [hashicorp/vault#23106]
**Describe the bug**
Reading KV from file generates `invalid key/value pair`

**To Reproduce**

This 
1.`kubectl exec -n vault  -it vault-0 -- vault kv put meh  MEH="us um ibus orum"` 
works

This
1. `echo 'MEH="us um ibus orum"' > meh.txt`
2. `cat meh.txt`
`MEH="us um ibus orum"`
4. ``` kubectl exec -n vault  -it vault-0 -- vault kv put meh  `cat meh.txt` ```

Gives
```
Failed to parse K=V data: invalid key/value pair "um": format must be key=value
```

**Expected behavior**
Both methods should load data

**Environment:**
* Vault Server Version (retrieve with `vault status`): `1.14.0`
* Vault CLI Version (retrieve with `vault version`): `Vault v1.14.0 (13a649f860186dffe3f3a4459814d87191efc321), built 2023-06-19T11:40:23Z`
* MacOs Ventura 13.5 (22G74) on Apple M1 Pro
* Using `kind`

**Comment by maxb** [comment]
There is no Vault issue here - the issue is simply a misunderstanding of how Linux shell quoting works.

For this to work as desired, you would need to move the double quotes around:
```
echo 'MEH=us um ibus orum' > meh.txt
kubectl exec -n vault -it vault-0 -- vault kv put meh "`cat meh.txt`"
```

**Comment by wiwwo** [comment]
Uhm... Ok, but that does not really works with

`MEH=us um ibus orum MEH2=a b c d`

But I assume yes, you are right.

Thanks for the tip, sorry for the bother
