### ISSUE TITLE
Regarding Compilation of Vault source code 

### ISSUE THREAD

**Issue by naveenscs** [hashicorp/vault#2311]
I was trying to build vault binary using the source code but it is building for all the architectures:

===============================================
==> Building...
Number of parallel builds: 7

-->     openbsd/386: github.com/hashicorp/vault
-->       linux/arm: github.com/hashicorp/vault
-->    netbsd/amd64: github.com/hashicorp/vault
-->     windows/386: github.com/hashicorp/vault
-->     linux/amd64: github.com/hashicorp/vault
-->   windows/amd64: github.com/hashicorp/vault
-->     freebsd/arm: github.com/hashicorp/vault
-->      netbsd/arm: github.com/hashicorp/vault
-->      netbsd/386: github.com/hashicorp/vault
-->   solaris/amd64: github.com/hashicorp/vault
-->      darwin/386: github.com/hashicorp/vault
-->       linux/386: github.com/hashicorp/vault
-->   openbsd/amd64: github.com/hashicorp/vault
-->   freebsd/amd64: github.com/hashicorp/vault
-->    darwin/amd64: github.com/hashicorp/vault
-->     freebsd/386: github.com/hashicorp/vault
==> Packaging...
--> freebsd_arm
  adding: vault (deflated 76%)
--> linux_arm
  adding: vault (deflated 76%)
--> openbsd_386
  adding: vault (deflated 75%)
--> windows_386
  adding: vault.exe (deflated 75%)
--> linux_amd64
  adding: vault (deflated 77%)
--> netbsd_amd64
  adding: vault (deflated 77%)
--> windows_amd64
  adding: vault.exe (deflated 77%)
--> netbsd_386
  adding: vault (deflated 75%)
--> linux_386
  adding: vault (deflated 75%)
--> netbsd_arm
  adding: vault (deflated 76%)
--> darwin_386
  adding: vault (deflated 75%)
--> openbsd_amd64
  adding: vault (deflated 77%)
--> solaris_amd64
  adding: vault (deflated 77%)
--> freebsd_amd64
  adding: vault (deflated 77%)
--> freebsd_386
  adding: vault (deflated 75%)
--> darwin_amd64
  adding: vault (deflated 77%)

==> Results:
total 51M
===============================================

Is it possible to make it configurable so that I can build the source code for the required architecture only?
Reason for asking this improvement is to reduce the overall compilation time vault and other related builds.

**Comment by jefferai** [comment]
As the readme directs, use `make dev`.

**Comment by naveenscs** [comment]
Can I use vault in production if it is built in DEV mode?

**Comment by vishalnayak** [comment]
@naveenscs The `dev` mode does not mean that the binary is built for running in the dev mode. It means that it is for testing and development of the project, for those to make changes to the code and submit PRs.

We recommend that you use the released official builds for production use.

**Comment by jefferai** [comment]
@naveenscs Just to be clear, "dev" in the makefile simply means "build only for my OS and architecture". The actual binary is built the same way.

But as Vishal suggested, the nice thing about using released official builds is that we sign them with our security key, so you can verify that they are builds that were created and released by us.
