### ISSUE TITLE
Check secret-id locking

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#2314]
This is really just an issue-as-reminder to do a due diligence check regarding https://groups.google.com/forum/#!msg/vault-tool/RFfyWUxxH0s/3CRm_BEiCwAJ before release!

**Comment by vishalnayak** [comment]
I could not see any problem with the locking semantics while listing secret IDs. The only possibility that I see is that secret ID lock being same as the custom lock. In the linked PR, I have placed a check to error out when the locks are same.

I am not sure if we can do anything more than this at this point.

**Comment by vishalnayak** [comment]
The OP has responded telling that the storage backend used was Consul. There could be a possibility of `req.Storage.List()` returning items that could be `""`. Not closing this to follow up with that. Taking it off of 0.6.5 though.

**Comment by jefferai** [comment]
Wouldn't that now be handled at https://github.com/hashicorp/vault/pull/2315/files#diff-4cf028f887780c050d328bd19b0e67dbR542 ?

**Comment by vishalnayak** [comment]
Yep it will be handled. But we still need to see if `req.Storage.List()` returns undesired items.

**Comment by jefferai** [comment]
If you want to do that let's make that a separate issue rather than keep this open.
