### ISSUE TITLE
Rabbitmq TLS issue

### ISSUE THREAD

**Issue by srirammageswaran** [hashicorp/vault#2316]
Hi ,

Has any one tried using rabbitmq secret backend with selfsigned certs...?

I am getting an error Saying 

failed to validate the connection: Get https://HOSTNAME:15672/api/users/: x509: certificate signed by unknown authority

Thanks ,
Sriram Mageswaran.

**Comment by jefferai** [comment]
You'll need to ensure that the root CA cert (which could be the self-signed cert) is in your system trust store.

**Comment by Fitzsimmons** [comment]
This is pretty awkward given that we use vault itself as the CA for rabbit. Is there a way for vault to add all the CA certs from its own PKI backends to the system store?

**Comment by Fitzsimmons** [comment]
Okay, kind of figured out our own workaround for this by making a root cert that's trusted by the system store and creating all of our vault PKI backends as intermediates of that root.

**Comment by jefferai** [comment]
Or you can just add your Vault root CA to your system store.
