### ISSUE TITLE
Extend aws-ec2 authentication backend to support sts assumeRole based configuration

### ISSUE THREAD

**Issue by dekramer** [hashicorp/vault#2317]
As a user, I want to supply a role-arn to the /auth/aws-ec2/config/client endpoint instead of long-lived credentials. The backend will then AssumeRole on that role to get temporary credentials for performing the ec2:DescribeInstances action.

**Comment by dekramer** [comment]
I want to use a vault instance in "vault-account" as a broker for pki across numerous accounts ("account 1" to "account n"). To do this, I would like to:

- Deploy vault in the vault-account
- Create roles that allow "ec2:DescribeInstances" in accounts 1...n and delegate that access vault-account
- Configure aws-ec2-1 ... aws-ec2-n backends each with the corresponding roles to authenticate to AWS
- Authenticate instances in account 1 against the aws-ec2-1 backend, account 2 against aws-ec2-2 backend, etc.

**Comment by jefferai** [comment]
I believe this is the same as https://github.com/hashicorp/vault/pull/2148

Can you comment if that functionality doesn't suffice?

**Comment by dekramer** [comment]
Yes, that functionality will cover this use case. Thanks!
