### ISSUE TITLE
vault_core_leadership_lost prometheus metric giving NaN value

### ISSUE THREAD

**Issue by vineet-negi009** [hashicorp/vault#23191]
**Describe the bug**
We are having a three node vault cluster and We are ingesting the metrics of our vault cluster into prometheus. At a certain point, if i change the leader using the command "vault operator step-down", then leader will change and vault give a metric i.e vault.core.leadership_lost  with NaN value.
Also previously when we hadn't changed the leader, there was no metric named vault.core.leadership_lost.

**To Reproduce**
1. Create a 3 node vault cluster, with 
2. Change the leader of vault by running command vault operator step-down
3. Check the value of metric vault_core_leadership_lost 

**Expected behavior**
vault_core_leadership_lost metric should give "1" value, when leadership is changed.

**Environment:**
Vault Version: 1.14.1

* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
part of the config used to enable metrics 
    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
        telemetry {
          unauthenticated_metrics_access = "true"
    }
    }
    telemetry {
      prometheus_retention_time = "10m",
      disable_hostname = true
    }
    storage "raft" {
      path = "/vault/data"
    }

**Comment by hghaf099** [comment]
Thank you for filing this issue. Please refer to this [page](https://developer.hashicorp.com/vault/docs/internals/telemetry/metrics/all) in our documentation for further readings about metrics. Note that `vault.core.leadership_lost` is the total time that a high-availability cluster node last maintained leadership. However, it seems that you are looking for a counter that reports such leadership lost. You can use `vault_core_leadership_lost_count` instead to track that. `vault_core_leadership_lost_sum` is also available that reports the total number of leadership changes. I am going to close this ticket for now. Please feel free to reopen it or open a new one for further questions/issues.
