### ISSUE TITLE
Embed Vault in a Go project

### ISSUE THREAD

**Issue by mytototo** [hashicorp/vault#2320]
Hi all,

I'm new to Vault and trying a few things with it this week. So far, I like it.

I have a question though: is it possible to import / inherit or embed Vault in an existing Go project? This way, I don't have two Go servers running.

Thanks.

**Comment by jefferai** [comment]
Unfortunately, it is not.

**Comment by mytototo** [comment]
@jefferai Thanks for your quick reply. I saw we can use the Vault API, is there any docs about it?

**Comment by jefferai** [comment]
Godoc! :-)

**Comment by mytototo** [comment]
Ok ! :-)
