### ISSUE TITLE
Error 500 when submitting a request with a namespaced token (from a Vault Enterprise) to a Vault OSS

### ISSUE THREAD

**Issue by alex-ikse** [hashicorp/vault#23216]
**Describe the bug**
We use 2 Vault instances : one OSS and one Enterprise, via Terraform (on a Terraform Enterprise). Terraform Enterprise generate the VAULT_TOKEN (thanks to the Dynamic Provider Credential feature).
I have 2 vault providers in my terraform code : 
- the Enterprise one is auto-configured by environment variables
- the OSS one is configured to use a AppRole as login method (but the issue occur with any type of auth)

Since `terraform-provider-vault` take the `$VAULT_TOKEN` value even if there is a `token = ...` attribute in provider configuration (!), i can't avoid the provider to create a request to Vault OSS with a `X-Vault-Token` header.

The issue is when the `VAULT_TOKEN` contain a "namespaced" Vault Enterprise token, vault try to convert the token in the "internal token" format.
See: https://github.com/hashicorp/vault/blob/6ef2a6031453b8bdc62fe9cb9511c223323a9e66/vault/token_store.go#L1570C2-L1578C1

If the "internal token" contain a namespace suffix, we got this error :
https://github.com/hashicorp/vault/blob/main/vault/token_store.go#L1589

**To Reproduce**
Steps to reproduce the behavior (specific token provided here is important to reproduce the issue):
1. Run `vault server -dev -dev-root-token-id root`
1. Run VAULT_ADDR="http://localhost:8200" VAULT_TOKEN="root" vault auth enable approle
2. Run `VAULT_TOKEN=hvs.CAESIDut1skSHeIgyQzmqGNMFUw-_99MojI3xtqA4at4Ob02GiwKImh2cy5RbmhtcW1ZbG93c2phbDJVOFZnVkNVV3EuRWFCSEcQtuGE6gUYCg VAULT_ADDR=http://localhost:8200 vault write auth/approle/login role_id=x secret_id=y`
3. or if you prefer, use the internal form of the token : `VAULT_TOKEN=hvs.QnhmqmYlowsjal2U8VgVCUWq.EaBHG VAULT_ADDR=http://localhost:8200 vault write auth/approle/login role_id=x secret_id=y`
5. See error
```
Error writing data to auth/userpass/login: Error making API request.

URL: PUT http://localhost:8200/v1/auth/approle/login
Code: 500. Errors:

* error performing token check: failed to look up namespace from the token: no namespace
```

**Expected behavior**
With an invalid role and any VAULT_TOKEN that not match the "namespaced" token format, the error should be : 
```
Error writing data to auth/approle/login: Error making API request.

URL: PUT http://localhost:8200/v1/auth/approle/login
Code: 400. Errors:

* invalid role ID
```

And with a valid role_id/secret_id => the return must be a valid token

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.12, 1.14.3
* Vault CLI Version (retrieve with `vault version`): 1.12, 1.14.3
* Server Operating System/Architecture: OSX

**Comment by hghaf099** [comment]
Closing the issue as the fix is merged!
