### ISSUE TITLE
PKI: Allow renewal of issued certificates

### ISSUE THREAD

**Issue by ekristen** [hashicorp/vault#2322]
I could be wrong, but it doesn't seem possible to get a new or updated certificate using the same private key unless you manually generate the private key and the CSR? 

I believe that Vault should support the renewal of certificates, it could do this by create/storing a CSR each time the `pki/issue/` endpoint is called, this would allow the generation of a new certificate and keeping the same private key.

The main benefit of this is to support keeping the same private key.  This is important to anyone wanting to do certificate pinning as the pin signature is based on the the private key. So long as the private key does not change renewed certificates will have the same signature used for pinning.

Since all issued certificates get a lease id already I believe this to be a trivial change. The biggest part of this change would be storing a CSR, but if lease periods are low anyways this information can easily be expired out. 

An alternative would be to return the CSR as part of the output of the `pki/issue` command and provide an alternative endpoint or perhaps being able to use the `pki/sign` endpoint, but to me this is not as seamless, as tools like consul-template, understand secret renewals already.

**Comment by jefferai** [comment]
Other then storing CSRs, which I'm not convinced are a useful thing to do (when do you clean them up, for instance), is there some way that the current CSR signing functionality doesn't support this use case?

**Comment by ekristen** [comment]
> Other then storing CSRs, which I'm not convinced are a useful thing to do (when do you clean them up, for instance)

When the normal pruning process happens for the CRL I would image. Essentially once it expires and hasn't been renewed.

> is there some way that the current CSR signing functionality doesn't support this use case?

To my knowledge Vault cannot create CSR files? So the current CSR signing functionality while technically would work, would basically defeat the purpose of using Vault in my opinion, since it would require me to generate the CSR and private key outside of the vault workflow.

I suppose if the `pki/issue/` returns the CSR then the current CSR signing functionality would work, but still does allow for using renew functionality that makes vault's short live secrets desirable.

consul-template among a few other tools and libraries support auto-renewing secrets, would love to be able to use a lib or consul-template to request a certificate store it to disk and have it auto-renewed while keeping the private key the same.

Part of the appeal of Vault is that you don't have to do the CSR/private-key generation and do not have to wait for validation (it is event talked about in the docs)

**Comment by jefferai** [comment]
> > Other then storing CSRs, which I'm not convinced are a useful thing to do (when do you clean them up, for instance)

> When the normal pruning process happens for the CRL I would image. Essentially once it expires and hasn't been renewed.

CSRs don't expire. There is no way to do this in an automated fashion.

> To my knowledge Vault cannot create CSR files? So the current CSR signing functionality while technically would work, would basically defeat the purpose of using Vault in my opinion, since it would require me to generate the CSR and private key outside of the vault workflow.

That's the point. In many cases orgs don't want private keys ever transiting the wire, so this allows for them to generate the CSR locally rather than have Vault create a private key and send it.

> Part of the appeal of Vault is that you don't have to do the CSR/private-key generation and do not have to wait for validation (it is event talked about in the docs))

The docs are specifically talking about waiting on validation, which doesn't work well in an automated fashion.

**Comment by ekristen** [comment]
> CSRs don't expire. There is no way to do this in an automated fashion.

I am aware they do not expire,I apologize if I made it seem like I was suggesting they do. However when you request a certificate/private_key with the `pki/issue/` command a lease id is generated with a corresponding expiration time, based on my little experience with coding in vault, I would image it would be rather trivial to store a CSR against a lease id? If that lease is no longer valid remove the CSR from the backend? 

> That's the point. In many cases orgs don't want private keys ever transiting the wire, so this allows for them to generate the CSR locally rather than have Vault create a private key and send it.

I totally get and respect that, and in this case those orgs would not be using the issue endpoint anyways. Since I run vault behind a TLS connection I have zero problems with a private key transiting my VPC network.

> The docs are specifically talking about waiting on validation, which doesn't work well in an automated fashion.

Fair enough, bad argument on my point, but I still feel my request is valid and doesn't hurt the security of vault and only improves the usability of the backend.


    To my knowledge Vault cannot create CSR files? So the current CSR signing functionality while technically would work, would basically defeat the purpose of using Vault in my opinion, since it would require me to generate the CSR and private key outside of the vault workflow.

That's the point. In many cases orgs don't want private keys ever transiting the wire, so this allows for them to generate the CSR locally rather than have Vault create a private key and send it.

    Part of the appeal of Vault is that you don't have to do the CSR/private-key generation and do not have to wait for validation (it is event talked about in the docs))

The docs are specifically talking about waiting on validation, which doesn't work well in an automated fashion.

**Comment by jefferai** [comment]
I think my main hesitation is that this significantly increases complexity but I'm not sure that it isn't already solved adequately.

For instance, you talked about using C-T. C-T will, if a lease is expiring, instead fetch a new secret. This will result in a new key, but this is not usually an issue -- if you can change the certificate with a hot reload usually you can change the key too.

**Comment by joemiller** [comment]
I have been working on solving this but perhaps have come at it a slightly different way. It's not deployed in production yet.

Using a small wrapping proxy to "extend" vault's own api I have added a route `/v1/pki/renew`. The proxy requests TLS client auth. A client will submit a CSR to the /renew endpoint. If all of the important bits from the CSR and the client cert match, the proxy simply adds its token and rewrites the request to the pki backend's `/v1/pki/sign-verbatim` endpoint, returning the response from vault to the client.

The client usage looks something like this:

```
$ ls cert.*
cert.crt cert.key cert.csr

$ vault write -client-key=cert.key -client-cert=cert.crt pki/renew csr=@cert.csr
```

As long as the Subject/DN and SANs in the cert.csr match the data in the cert.crt, the vault pki will issue a "duplicate" cert with a new renewal time. The proxy also sets the renewal time to the same length as the client cert (cert.crt) so you cannot request a renewed cert with longer expiration than the cert you already have.

This does not require any storage of the CSR in vault as the client is responsible for submitting the CSR. I think this is fine as it is also easy to recreate a CSR from an existing CRT if the client didn't keep the CSR around after the initial issuance.

I would love to see this get incorporated into Vault somehow, though I think the requirement of TLS auth for the /renew endpoint might complicate things for other setups.

**Comment by jefferai** [comment]
FWIW given that I don't think that what is actually needed here is literal CSR generation and storage, but rather the ability to fetch a certificate with the same parameters and key, I think that there is a much simpler way to do it in the backend. If someone wants to actually take a shot at implementing it I'm happy to discuss.

**Comment by jefferai** [comment]
(BTW, I haven't totally thought it through so I can't promise that somewhere along the way there won't be something that makes me say "um, actually, this is a bad idea" :-) )

**Comment by ekristen** [comment]
I've been giving this some thought. I'm definitely on board with your C-T explanation @jefferai, that still nets me a new private key every time which can be problematic for people who are wanting to use certificate pinning. 

As for getting a new certificate using the same private key, I'm not that is doable without a CSR. At least I'm not familiar with a way.

I am still in favor of implementing a renew function that will handle this seamlessly.

**Comment by jefferai** [comment]
@ekristen if you're willing to do the work we can discuss at some point because I already know how it would work, possibly :-)

**Comment by AgentZombie** [comment]
One of the purposes of certificate expiration is to mitigate the unknown loss of a private key. Every CSR should refer to a key pair that has never been used in a signed certificate.

Luckily it's easy to generate a new key pair and a new CSR using the information from an existing certificate. Given an existing certificate `example.crt`:
```
openssl genrsa -out example-new.key 2048
openssl x509 -x509toreq -in example.crt -out example.csr -signkey example-new.key`
```

**Comment by gautaz** [comment]
I'm just trying to catch up with  this issue so sorry if it feels a bit annoying.

> For instance, you talked about using C-T.

@jefferai I did not spot where @ekristen referred `C-T` in the first time so just to understand what you are both talking about, is it [certificate transparency](https://www.certificate-transparency.org/)?

I am also wondering what is the current advised process for vault concerning the renewal of certificates that were initially issued through [generate-certificate](https://www.vaultproject.io/api/secret/pki/index.html#generate-certificate)?

**Comment by jefferai** [comment]
@gautaz C-T in this context is https://www.vaultproject.io/api/auth/approle/index.html

We don't generally support renewing certificates. Instead, fetch a new certificate. If you must re-use the same key, you can use a CSR.

**Comment by gautaz** [comment]
OK, thanks for clarifying.
So I guess C-T stands here for "Credentials - Token".

**Comment by jefferai** [comment]
Oops. Nope, I pasted the wrong link. https://github.com/hashicorp/consul-template

**Comment by gautaz** [comment]
OK, at last I see the link with the third post ;-).
I've totally missed this point.
Thanks !
