### ISSUE TITLE
Excessive memory usage when processing cert logins

### ISSUE THREAD

**Issue by mihkelader** [hashicorp/vault#23369]
Vault server runs out of memory when many clients try to log in with certificate.

We use client certificates for authentication and every client has a separate role. When a whole environment has been shut down and restarted after maintenance, Vault keeps running out of memory and crashes.

In our testing with ~2000 cert roles and ~500 simultaneous logins, Vault process uses some 11GB of RAM while normally the usage is ~700MB

**To Reproduce**
1. Enable cert auth:
`vault auth enable cert`
2. Add many roles
`for i in {1..1000}; do ../bin/vault write auth/cert/certs/crt$i certificate=@ca.pem; done`
3. Trigger many simultaneous logins (codesenberg/bombardier used here):
`./bombardier-linux-amd64 -k -t 120s -c 500 -n 500 --cert=crt.pem --key=key.pem -a -m POST https://127.0.0.1:8200/v1/auth/cert/login`
4. Observe sharp rise in Vault's memory usage

**Expected behavior**
Vault processes logins, maybe rejects some, but memory usage does not explode

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.15.0
* Vault CLI Version (retrieve with `vault version`): 1.15.0
* Server Operating System/Architecture: Linux/amd64

Vault server configuration file(s):
Minimal config for reproducing the problem
```hcl
listener "tcp" {
  address = "0.0.0.0:8200"
  cluster_address = "0.0.0.0:8201"
  tls_cert_file = "/tmp/server.crt.pem"
  tls_key_file = "/tmp/key.pem"
}

storage "file" {
  path = "/tmp/data"
}
```

**Additional context**
There are no problems with other API calls after clients have logged in and received tokens. Vault happily gives out secrets even with thousands of simultaneous requests coming in.

**Comment by sgmiller** [comment]
We believe we understand the issue, but one question.  After the logins does memory eventually return to normal?

**Comment by sgmiller** [comment]
Fix: https://github.com/hashicorp/vault/pull/25421
