### ISSUE TITLE
[1.15.0] Configuration details tile returns TLS Disabled, when it's enabled

### ISSUE THREAD

**Issue by z0rc** [hashicorp/vault#23371]
**Describe the bug**
Configuration tile in UI shows TLS Disabled, for instance where TLS wasn't disabled.
<img width="503" alt="Screenshot 2023-09-28 at 16 16 05" src="https://github.com/hashicorp/vault/assets/787519/28aa068b-1c8f-4514-b57b-a4564ed7bfa1">

**To Reproduce**
1. Run vault in kubernetes using official docker image. There is no config file, configuration is supplied via env var `VAULT_LOCAL_CONFIG`.
3. Open UI, see "TLS Disabled".

**Expected behavior**
TLS should be Enabled.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.15.0
* Vault CLI Version (retrieve with `vault version`): Irrelevant
* Server Operating System/Architecture: Bottlerocket 1.15.0, arm64.

Vault server configuration file(s):

```hcl
api_addr     = "https://${vault_domain}"
cluster_name = "${vault_cluster_name}"
ui           = true

log_level  = "info"
log_format = "json"

listener "tcp" {
  address                  = "[::]:${vault_port}"
  cluster_address          = "[::]:${vault_port + 1}"
  tls_cert_file            = "/etc/vault/tls/vault.crt"
  tls_key_file             = "/etc/vault/tls/vault.key"
  tls_disable_client_certs = "true"
  proxy_protocol_behavior  = "use_always"
}

seal "awskms" {
  region     = "${aws_region}"
  kms_key_id = "${kms_key_id}"
}

storage "dynamodb" {
  ha_enabled = "true"
  region     = "${aws_region}"
  table      = "${vault_dynamodb_table}"
}
```

**Additional context**
None.

**Comment by karabanov** [comment]
I confirm - I have the same behavior

**Comment by bmcdonald05** [comment]
I am seeing the same behavior on on Vault 1.15.0+ent

config snippet:
```
listener "tcp" {
 address = "0.0.0.0:8200"

 ### Enable TLS ###
 tls_cert_file = "./tls/cert.pem"
 tls_key_file = "./tls/key.pem"
 tls_client_ca_file = "./tls/ca.pem"
 tls_disable_client_certs = false
}
```
<img width="524" alt="Vault-ui-bug" src="https://github.com/hashicorp/vault/assets/16618271/ec8ab32a-822a-44ce-88ed-afb3bfc56a1d">

**Comment by lals1** [comment]
Seeing the same issue, Does anyone know the reason?
