### ISSUE TITLE
PKI: Change what is hashed in audit logs or provide more control

### ISSUE THREAD

**Issue by bhiggins** [hashicorp/vault#2338]
The use case here is with the PKI backend, specifically /pki/sign/. We want to keep detailed audit logs over what CSRs are signed.

Our view is that CSRs and associated inputs (CN, alt names), and the resulting signed certificates and chain information, are not sensitive or secret. The only secrets here are the private key (not transmitted in the /pki/sign/ case) and Vault auth information (e.g. tokens). (It's also a little funny to see "format" hashed, given its limited range of values.)

Below is an example response audit log from /pki/sign/. The only thing we would like to keep hashed is client_token / client_token_accessor, and any private key (not present here). The only workaround we know of (short of modifying Vault) is to turn on log_raw and then write a script to filter out tokens/private keys. This feels brittle and dangerous though. Are there alternatives?

BTW, thanks a lot for Vault!

```json
{
  "time": "2017-02-06T19:06:41Z",
  "type": "response",
  "error": "",
  "auth": {
    "client_token": "",
    "accessor": "",
    "display_name": "token",
    "policies": [
      "root"
    ],
    "metadata": null
  },
  "request": {
    "id": "0ccbd18b-bafc-393f-b6bc-f016780edd07",
    "operation": "update",
    "client_token": "hmac-sha256:2d4698d44e839c98c51a3554d30835c09f71a79ba5129bb3101984247b005a46",
    "client_token_accessor": "hmac-sha256:7b7ce08715a668a5837c7801cf4a4210bec04498d6afa6a9884f517abb9e3b12",
    "path": "pki/sign/test",
    "data": {
      "alt_names": "hmac-sha256:f18b7ca4e632193270cb64ad4727d985e963e7c0728ce23b2a55f9788c36a0f1",
      "common_name": "hmac-sha256:3182a2ed9ac4b10ff8b927667c3a124acbea54d075f706d5c7a8617be50abb4d",
      "csr": "hmac-sha256:61eace889ed3d2488ef93d1f789d065c79e5c7bc9a03e4815b228350d52c3585",
      "exclude_cn_from_sans": false,
      "format": "hmac-sha256:db1d20520faaffba53ece3358092d5aa5b406c2d9eafe285745e1a8f1b8deea9"
    },
    "remote_address": "127.0.0.1",
    "wrap_ttl": 0
  },
  "response": {
    "secret": {
      "lease_id": "pki/sign/test/72ecf263-bcdf-fe09-6495-1cb2aa204ea4"
    },
    "data": {
      "ca_chain": [
        "hmac-sha256:e6fbfcd3ea47b84a9a862ac404a50302cb5ee29b91f728b88254fdd7a35b5111"
      ],
      "certificate": "hmac-sha256:726deff6266fa9fbdd38faabb7378305ec4c61d7a5e62fea54e4d36c62a0b94b",
      "issuing_ca": "hmac-sha256:e6fbfcd3ea47b84a9a862ac404a50302cb5ee29b91f728b88254fdd7a35b5111",
      "serial_number": "hmac-sha256:dad17c217026ba24ed59a3f3e39cce8b344d728f9ca9f1944f126bca0dabf366"
    }
  }
}
```

**Comment by jefferai** [comment]
Closing this as it is a dup of an internal roadmap item. It's planned!
