### ISSUE TITLE
Help UI is extremely confusing

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/vault#234]
`vault <command> -h` and `vault help <path>` are two different things, but it's not intuitive to the user when to use which. 

The documentation does mention them both, but to a user, the end goal is the same.  So a user (like me) is likely to type `vault help init` with the goal of receiving help for the `init` subcommand.  Unfortunately the result will not be as expected:

```
$ ./vault help init
Error reading help: Get https://127.0.0.1:8200/v1/init?help=1: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
```

My thought here: "oh, interesting, the help document comes from HTTP.  Let's ensure the client skips TLS verification as I'm using a self-signed certificate."

```
$ ./vault help -tls-skip-verify init
Error reading help: Error making API request.

URL: GET https://127.0.0.1:8200/v1/init?help=1
Code: 500. Errors:

* Vault is sealed
```

My thought: Umm, OK.  I can't get help on a sealed vault?

```
$ ./vault help -tls-skip-verify init
Error reading help: Error making API request.

URL: GET https://127.0.0.1:8200/v1/init?help=1
Code: 500. Errors:

* no handler for route 'init/'
```

My thought here:  what?  This makes no sense to me.

Of course, the help comes by typing `vault init -h` - but the user is very frustrated at this point and thinks this newfangled unfamiliar Vault tool is already broken.

Proposed fix:
1.  Make `vault help <subcommand>` operate identically to `vault <subcommand> -h`
2.  Create a new subcommand `backend-help` to get help with backends

**Comment by sethvargo** [comment]
I kinda think `-h` and `--help` should work on everything. It's shorter to type than `help`, and it's more "unixy". What do you think?

**Comment by mfischer-zd** [comment]
Can you illustrate with some examples @sethvargo ?

**Comment by armon** [comment]
@sethvargo @mfischer-zd The problem is the overloading of the "help" word. Maybe it would be more clear to rename it to "manpage" so you can do `vault manpage sys/health` instead of `vault help sys/health`

**Comment by mfischer-zd** [comment]
Bikeshedding here, but I think `backend-help` is better than `manpage` because the context for `help` is all about backends (correct me if I'm wrong), whereas `manpage` could be about any Vault function.  So I think it makes sense to have a subject of some sort in the verb.

**Comment by armon** [comment]
Yeah it could even be `path-help` or something. I think we just need to not overload `help`

**Comment by mfischer-zd** [comment]
`path-help` sounds good to me.

**Comment by armon** [comment]
@mfischer-zd The issue there is that if the vault is sealed we actually don't know what is mounted where.  The mount table is "inside" the Vault in that sense. So there isn't really a sane response we can generate, since it depends on the mount table.
