### ISSUE TITLE
[1.15.0] kv secrets not showing in the UI

### ISSUE THREAD

**Issue by hillen** [hashicorp/vault#23463]
**Describe the bug**
After upgrading to vault version 1.15.0, kv secrets are no longer shown in the UI

**To Reproduce**
Upgrade to vault 1.15.0. After the upgrade, secrets using a kv engine are no longer shown

I believe that this is related to PR 22559

There are several secrets in the secret mount point and as seen in the screen shot the UI is not showing these secrets. There is a mismatch in the kv version between what the UI is showing and the configuration of the engine. This is a version 1 secret, not version 2.

![Screenshot from 2023-10-03 11-44-57](https://github.com/hashicorp/vault/assets/4267745/26762678-ea5d-4e1a-ab3b-490ce32e6605)

![Screenshot from 2023-10-03 11-44-35](https://github.com/hashicorp/vault/assets/4267745/ac4b6b0b-029e-4d80-a1ce-6144983601e3)

**Expected behavior**
Secrets to continue to be shown in the UI after upgrading to 1.15.0

**Environment:**
* Vault Server Version "1.15.0"
* Vault CLI Version Vault v1.15.0 (b4d07277a6c5318bb50d3b94bbd6135dccb4c601), built 2023-09-22T16:53:10Z
* Server Operating System/Architecture: Running the vault container in kubernetes using the vault:1.15.0 tag from the hashicorp/vault docker location

Vault server configuration file(s):

```hcl
seal "azurekeyvault" {
  tenant_id      = ""
  vault_name     = ""
  key_name       = ""
}
storage "mysql" {
  address                 = ""
  database                = "vault"
  table                   = "vault"
  tls_ca_file             = "/vault/userconfig/mysql-cert/mysql.crt"
  max_parallel            = "128"
  max_idle_connections    = "0"
  max_connection_lifetime = "0"
  username                = ""
  password                = ""
  ha_enabled              = "true"
  lock_table              = "vault_lock"
}
telemetry {
  prometheus_retention_time = "30s"
  disable_hostname = true
}
disable_mlock = true
ui = true
listener "tcp" {
  address = "[::]:8200"
  cluster_address = "[::]:8201"
  telemetry {
    unauthenticated_metrics_access = "true"
  }
  tls_cert_file = "/vault/userconfig/vault-tools-cert/tls.crt"
  tls_key_file  = "/vault/userconfig/vault-tools-cert/tls.key"
}

**Additional context**
None

**Comment by ed-ud** [comment]
Also seeing this problem - all of our secrets are KV v1 so the UI is now useless for us.

**Comment by tdviet** [comment]
> Potential workaround:
> 
> `% vault secrets tune -options="version=1" <mount-name>`

Thank you very much for the workaround., it works correctly for me. I had the same issue after upgrading and was going to rollback to the older version, and the workaround saved a lot of times

**Comment by jayunit100** [comment]
I also noticed this earlier , thanks for the report
