### ISSUE TITLE
[1.15.0] Number Challenge Missing for Okta Verify in Vault UI

### ISSUE THREAD

**Issue by bobby-mack** [hashicorp/vault#23465]
**Describe the bug**
Uncaught TypeError: Cannot read properties of undefined (reading 'setOktaNumberChallenge')

**To Reproduce**
1. Log in to Vault Web App via Okta auth: https://$VAULT:$PORT/ui/vault/auth?with=okta -- with Username and Password.
2. Receive an Okta MFA prompt -- _Did you just try to sign in?_ -- and select _Yes, it's me_
3. The message _Which number do you see on your other screen?_ will be shown in the next mobile app window, with 3 random numbers to choose.
4. The corresponding matching number never shows up in the Vault Web App UI sign-in screen.
5. See error below in Chrome Console: 

![image](https://github.com/hashicorp/vault/assets/72526360/ef7740ed-33c1-4dd8-b183-47286da8a271)

**Expected behavior**
In the Vault UI Web App, select the correct verification number when using the Okta authentication method with the Number Challenge for Okta Verify after providing the right credentials and acknowledging the MFA prompt.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.15.0
* Vault CLI Version (retrieve with `vault version`): 1.15.0
* Server Operating System/Architecture: Amazon Linux 2

Vault server configuration file(s):

```hcl
N/A; We have a vanilla configuration with file storage and TLS enabled. There's not much to talk about here.
```

**Additional context**
The Number Challenge for Okta Verify feature was previously working without any issues in the Vault UI Web App, and there are no material changes that would explain this new behavior beyond the bump to version 1.15.0. **Important Note**: The Vault CLI does not seem to be impacted and still works great with the Number Challenge feature for Okta Verify.

**Comment by Monkeychip** [comment]
@bobby-mack thank you for reporting the issue. We have a fix for this regression. It will be backported to 1.15.1.
