### ISSUE TITLE
Feature request: revoke tokens generated by an app-role

### ISSUE THREAD

**Issue by kbenyous** [hashicorp/vault#2355]
Hello,
It would be very nice if I could easily **revoke the tokens generated by an app-role**.

Here is the use case:
1. Some applications need accessing the Vault server for a limited (but undetermined) time
2. An administrator sets up an app-role, which provides tokens for these applications and this limited use
3. The apps log in Vault (and generate tokens)
4. The apps access the secrets they need.
5. When done, an administrator revoke (or renew) the app-role secret, and revoke the tokens generated by this app-role.

Alternative use case:
5'. Somebody steals the app role_id and role_secret, and asks vault for generating tokens
6'. An administrator revoke (or renew) the app-role secret, and revoke the tokens generated by this app-role.

There are two way for implemeting this:
1. **In the app-role definition, add a token_parent** for all the generated tokens. It would be easy then to revoke this parent and all the children tokens. The token_parent would be either optional (for generating orphan tokens) or valid (for generating a token tree).
2. **In the token lookup, expose the name of the app-role that has generated the token**. This is very similar to [Revoking access for a user removed in LDAP](https://groups.google.com/forum/#!topic/vault-tool/ohVMNa33A90), but there is no way to identfy the token generated by a specific app-role.

This feature would be very appreciated :-)

Kind regards,
K.B.

**Comment by jefferai** [comment]
You can do this right now using the `metadata` parameter to the endpoints that fetch secret-ids. Simply put whatever identifier you want -- role name, or anything else -- and then this information will show up when you look up a token via the accessor.

**Comment by kbenyous** [comment]
Thank you very much. That solves my problem.
I have just tested, and the metadata associated with a secret-id are added to the token metas.
I will write a script to iterate over all the tokens and delete the ones with the matching metas.

However it would be nicer with a simple endpoint in the api ;-)

Kind regards
K.B.
