### ISSUE TITLE
Acceptance tests fail on revocation

### ISSUE THREAD

**Issue by ianunruh** [hashicorp/vault#236]
On the Consul acceptance tests, as well as ones for a RabbitMQ backend I'm working on, I consistently experience the following issue:

```
--- FAIL: TestBackend_basic (2.01s)
	testing.go:220: [ERR] Revoke error: secret is unsupported by this backend
	testing.go:245: WARNING: Revoking the following secret failed. It may
		still exist. Please verify:

		*logical.Secret{LeaseOptions:logical.LeaseOptions{Lease:3600000000000, LeaseGracePeriod:600000000000, Renewable:true, LeaseIncrement:0, LeaseIssue:time.Time{sec:63567689150, nsec:454263987, loc:(*time.Location)(0x6d39a0)}}, InternalData:map[string]interface {}(nil), LeaseID:"mnt/creds/test/cbc763c7-fdbe-1e0e-41b5-930ab55f4c47"}
```

It seems that the internal data for the secret lost somewhere in the mix. I'm not experienced enough with the acceptance testing framework to point out where this is happening though.

**Comment by sethvargo** [comment]
Labeled as core and docs since it might just be some docs we need to update or a real bug. We will investigate more later. Thanks!

**Comment by jsok** [comment]
+1 seeing this same failure (logical consul acceptance tests) today while working on a PR

**Comment by armon** [comment]
@ianunruh @jsok There was a change in what core would expose, which broke the acceptance test framework. This should be fixed in master now!
