### ISSUE TITLE
Using a 128-bits AES key to encrypt messages

### ISSUE THREAD

**Issue by fjanicki** [hashicorp/vault#2361]
Hi,

From what I understand, the default key size for AES is set to 256 bits but due to some hardware restriction the use of a 256 bits key is not possible in our project. Our small hardware controller only supports AES-128 and we would really benefit from using Vault form a security standpoint. Would it be possible with the current version of Vault to encrypt messages using AES-128?

Thank you!

**Comment by norpol** [comment]
Hi,

I'm not involved here, just reading some of the issues - so don't take what I write for granted. What I understand is that the vault server application is written in golang and runs on some operating-system/kernel (for example on Linux).
This application stores encrypted AES-256 CBC (default) data in various backends (for example Hashicorp Consul, Postgres, Files, ...). When you access those secrets via. the HTTP(s)-REST-API, vault decrypts the data and sends it via. a traditional (encrypted) TLS connection to the client.
I don't believe your Linux/*nix host has 'hardware limitations' on the AES side.
Are you trying to access secrets via. some embedded system/mikrocontrolller? Then you're probably running into the issue of how to get TLS there, probably through [some](https://www.wolfssl.com/wolfSSL/Home.html) ... [libraries](https://tls.mbed.org/).

**Comment by fjanicki** [comment]
Well basically I want to encrypt a message using a shared key between a microcontroller and the vault instance. Our server would have a message/command to encrypt, would call the vault instance, vault would encrypt the message using AES128, returns the encrypted message to our server then our server would send it to the remote microcontroller. The microcontroller has hardware enc/dec for AES128 but not AES256, hence why we would need support for AES128 encryption in order to be able to use Vault.

**Comment by jefferai** [comment]
Vault has no support for 128 bit keys right now. What kind of throughput do you need? Would software AES really be that slow?

**Comment by jefferai** [comment]
Closing due to lack of feedback.
