### ISSUE TITLE
Header audit appears to only work if it starts with an uppercase letter and is followed by lowercase letters

### ISSUE THREAD

**Issue by bkrodgers** [hashicorp/vault#2362]
HTTP header names should be treated case-insensitively, per https://tools.ietf.org/html/rfc7230#section-3.2.  

In some testing to figure out why X-Forwarded-For wasn't coming across in my environment, I noticed both that whether or not the header is logged appears to depend on case, but also that a header that is both registered in lowercase and sent in lowercase doesn't get logged at all.

Each set of commands below is run on a fresh vault instance locally in dev mode, restarting between runs.

Registered header in lowercase, sent in matching lowercase, nothing logged:
```
vault audit-enable file file_path=~/vault_audit.log
curl -H "X-Vault-Token: $(cat ~/.vault-token)" $VAULT_ADDR/v1/sys/config/auditing/request-headers/blahblah -XPUT
curl -H "X-Vault-Token: $(cat ~/.vault-token)" $VAULT_ADDR/v1/secret/test -H "blahblah: blah" -XPUT -d '{"hi": "there"}'
tail -2 ~/vault_audit.log | jq .request.headers
Output:
{}
{}
```

Registered header with the first letter uppercase, sent in matching first letter uppercase, logged:
```
vault audit-enable file file_path=~/vault_audit.log
curl -H "X-Vault-Token: $(cat ~/.vault-token)" $VAULT_ADDR/v1/sys/config/auditing/request-headers/Blahblah -XPUT
curl -H "X-Vault-Token: $(cat ~/.vault-token)" $VAULT_ADDR/v1/secret/test -H "Blahblah: blah" -XPUT -d '{"hi": "there"}'
tail -2 ~/vault_audit.log | jq .request.headers
Output: 
{
  "Blahblah": [
    "blah"
  ]
}
{
  "Blahblah": [
    "blah"
  ]
}
```

Registered in first letter upper case, sent in non-matching lowercase, logged:
```
vault audit-enable file file_path=~/vault_audit.log
curl -H "X-Vault-Token: $(cat ~/.vault-token)" $VAULT_ADDR/v1/sys/config/auditing/request-headers/Blahblah -XPUT
curl -H "X-Vault-Token: $(cat ~/.vault-token)" $VAULT_ADDR/v1/secret/test -H "blahblah: blah" -XPUT -d '{"hi": "there"}'
tail -2 ~/vault_audit.log | jq .request.headers
Output: 
{
  "Blahblah": [
    "blah"
  ]
}
{
  "Blahblah": [
    "blah"
  ]
}
```

Registered in lower case, sent in non-matching first letter uppercase, not logged:
```
vault audit-enable file file_path=~/vault_audit.log
curl -H "X-Vault-Token: $(cat ~/.vault-token)" $VAULT_ADDR/v1/sys/config/auditing/request-headers/blahblah -XPUT
curl -H "X-Vault-Token: $(cat ~/.vault-token)" $VAULT_ADDR/v1/secret/test -H "Blahblah: blah" -XPUT -d '{"hi": "there"}'
tail -2 ~/vault_audit.log | jq .request.headers
Output: 
{}
{}
```

Registered in all uppercase case, sent in non-matching first letter uppercase, not logged:
```
vault audit-enable file file_path=~/vault_audit.log
curl -H "X-Vault-Token: $(cat ~/.vault-token)" $VAULT_ADDR/v1/sys/config/auditing/request-headers/BLAHBLAH -XPUT
curl -H "X-Vault-Token: $(cat ~/.vault-token)" $VAULT_ADDR/v1/secret/test -H "Blahblah: blah" -XPUT -d '{"hi": "there"}'
tail -2 ~/vault_audit.log | jq .request.headers
Output: 
{}
{}
```

On a side note, I think my actual issue with X-Forwarded-For was actually that the headers can't be added by the ELB when it's just doing TCP passthrough on 443, which I need it to for cert auth to work.  But in any case, I think we want this to follow the HTTP spec and be case insensitive both on how they're sent and registered.

**Comment by jefferai** [comment]
Yep, we will fix for 0.7.
