### ISSUE TITLE
Linux Mint 18.1

### ISSUE THREAD

**Issue by magnum93** [hashicorp/vault#2364]
Hi When I start the vault server -dev
Error initializing listener of type tcp: listen tcp 127.0.0.1:8200: bind: address already in use error something is also here too how do I fix? Please.

**Comment by magnum93** [comment]
Heres my ifconfig 
enp3s0    Link encap:Ethernet  HWaddr 30:5a:3a:4b:c5:28  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:3752 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3752 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:444979 (444.9 KB)  TX bytes:444979 (444.9 KB)

wlx00259c78ad83 Link encap:Ethernet  HWaddr 00:25:9c:78:ad:83  
          inet addr:192.168.178.172  Bcast:192.168.178.255  Mask:255.255.255.0
          inet6 addr: fe80::8307:d61a:5110:8d92/64 Scope:Link
          inet6 addr: 2001:7e8:dc5e:5301:45c6:df98:4070:2c3e/64 Scope:Global
          inet6 addr: 2001:7e8:dc5e:5301:3e68:a759:a3b5:5731/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:809519 errors:0 dropped:0 overruns:0 frame:0
          TX packets:475729 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:991822904 (991.8 MB)  TX bytes:44422035 (44.4 MB)

gary@server-All-Series ~ $

**Comment by magnum93** [comment]
this is the error
gary@server-All-Series ~ $ vault server -dev
Error initializing listener of type tcp: listen tcp 127.0.0.1:8200: bind: address already in use
gary@server-All-Series ~ $

**Comment by magnum93** [comment]
and this is my 
gary@server-All-Series ~ $ netstat -tulpn
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:8200          0.0.0.0:*               LISTEN      5349/vault      
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      -               
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -               
udp        0      0 0.0.0.0:47693           0.0.0.0:*                           -               
udp        0      0 127.0.1.1:53            0.0.0.0:*                           -               
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -               
udp        0      0 192.168.178.172:123     0.0.0.0:*                           -               
udp        0      0 127.0.0.1:123           0.0.0.0:*                           -               
udp        0      0 0.0.0.0:123             0.0.0.0:*                           -               
udp        0      0 0.0.0.0:631             0.0.0.0:*                           -               
udp6       0      0 :::5353                 :::*                                -               
udp6       0      0 fe80::8307:d61a:511:123 :::*                                -               
udp6       0      0 2001:7e8:dc5e:5301::123 :::*                                -               
udp6       0      0 2001:7e8:dc5e:5301::123 :::*                                -               
udp6       0      0 ::1:123                 :::*                                -               
udp6       0      0 :::123                  :::*                                -               
udp6       0      0 :::33283                :::*                                -               
gary@server-All-Series ~ $

**Comment by jefferai** [comment]
Netstat showed you exactly what you need to know. You have something listening on port 8200 already. You'll need to shut that down, or have the dev server use a different address (see output of vault server -h).
