### ISSUE TITLE
Okta auth backends issue  not releasing token and policy.  

### ISSUE THREAD

**Issue by cere23** [hashicorp/vault#2367]
Summary: once the user is authenticated neither token nor policy is released .

**My setup:** 

Vault servers v0.6.5 in HA mode
auth backend: okta 

**Step to reproduce:** 

1) Configure a user on Okta
2) assign the  user to a group called test2 
3) Enable Okta backend: 
$ vault auth-enable Okta

4) Configure connection parameter: 
$vault write auth/okta/config base_url="okta.com" \
  organization="bla-bla-aaa" \
   token="xxxxxxxxxxxxxxxxxxxx"
   Success! Data written to: auth/okta/config

5) Map policy Okta group: 
vault write auth/okta/groups/test2 policies=ssh 
Success! Data written to: auth/okta/groups/test2

When I try to authenticate: 
vault auth -method=okta username= john@XXXXX.com
Password (will be hidden):
Put https://$some_address:8200/v1/auth/okta/login/john@XXXXX.com: EOF

Okta console let me know authentication was successful. 

**Relevant logs:** 

{"time":"2017-02-13T16:27:04Z","type":"request","auth":{"client_token":"","accessor":"","display_name":"","policies":null,"metadata":null},"request":{"id":"b083464e-dbd5-59af-ff44-5f4b743c0fef","operation":"update","client_token":"hmac-sha256:89f7d7524e36e751e4196065d603cffb8d490cbccb2839a309da42a9ec200440","client_token_accessor":"","path":"auth/okta/login//john@XXXXX.com","data":{"password":"hmac-sha256:4df4d375991e63f98e7f295e7db15a874a4c2d2ce016c18a0392c5a6c3bdcd1d"},"remote_address":"10.9.1.180","wrap_ttl":0,"headers":{}},"error":""}

So nor token or policy  is released. 

**Work-around:** 
I managed to make this work, after multiple attempts, adding fake data: 

$vault write auth/okta/users/john@XXXXX.com foo=bar
Success! Data written to: auth/okta/users/john@XXXXX.com

% vault auth -method=okta username=john@XXXXX.com
Password (will be hidden):
Successfully authenticated! You are now logged in.
The token below is already saved in the session. You do not
need to "vault auth" again with the token.
token:XXXXXXXXXXXXXXXXXXXXXXX
token_duration: 2764800
token_policies: [default full]

**Comment by jefferai** [comment]
@cere23 I was able to reproduce: the problem is that there is a bug in the provider when policies are only configured against groups, not against users. I will fix this shortly; you can either pull from master in a little bit or you can use the next release.
