### ISSUE TITLE
Issues with consul backend causes vault read access extremely slow

### ISSUE THREAD

**Issue by willow2014** [hashicorp/vault#2368]
Hi, All, 

I have a consul cluster that is not very stable for some reason. 

Configuration: 3 ubuntu 14.04 LTS running on bare metal
                       3 node cluster for Consul.  
                        3 node vault cluster running on top of the consul. 

Symptoms: 

"Vault mounts" command is consistently slow response, always 2m 7s on standby nodes, but very fast on the active vault nodes. 

Consul cluster looks ok. 

I saw there are some issues with clock within the cluster. It is out of sync by about 3 minutes within the cluster. 

After digging through the syslog, I found the following occurred 7 hrs ago w.r.t. consul: 
node3: 

/var/log/syslog.1:Feb 10 03:45:53 pr-vault03 consul[1043]: raft: Failed to contact 10.135.31.1:8300 in 864.274295ms

/var/log/syslog.1:Feb 10 03:45:53 pr-vault03 consul[1043]: raft: Failed to contact 10.154.25.1:8300 in 857.781253ms

/var/log/syslog.1:Feb 10 03:45:53 pr-vault03 consul[1043]: raft: Failed to contact quorum of nodes, stepping down

Node2: 

syslog.1:Feb 10 04:48:55 pr-vault02 consul[85142]: raft: Failed to contact 10.154.25.1:8300 in 732.181887ms

syslog.1:Feb 10 04:48:55 pr-vault02 consul[85142]: raft: Failed to contact 10.138.31.1:8300 in 742.414664ms

syslog.1:Feb 10 04:48:55 pr-vault02 consul[85142]: raft: Failed to contact quorum of nodes, stepping down

Node 1: 

Feb 10 12:19:51 pr-vault01 consul[94165]: raft: Failed to contact 10.135.31.1:8300 in 801.022734ms

Feb 10 12:19:51 pr-vault01 consul[94165]: raft: Failed to contact 10.138.31.1:8300 in 800.603337ms

Feb 10 12:19:51 pr-vault01 consul[94165]: raft: Failed to contact quorum of nodes, stepping down

Feb 10 12:19:51 pr-vault01 consul[94165]: consul: failed to wait for barrier: node is not the leader

Feb 10 12:19:51 pr-vault01 consul[94165]: consul.kvs: Apply failed: node is not the leader

vault@pr-vault03:/etc/vault$ consul members

Node        Address           Status  Type    Build  Protocol  DC

pr-vault01  10.154.25.1:8301  alive   server  0.6.4  2         xx

pr-vault02  10.135.31.1:8301  alive   server  0.6.4  2         xx

pr-vault03  10.138.31.1:8301  alive   server  0.6.4  2         xx

How can I trouble shoot this issue more? How to test consul's health levels independent of the vault? How to recover? 

Thanks.

**Comment by jefferai** [comment]
Being tracked in https://groups.google.com/d/msg/vault-tool/dWvi7HIkPjY/yxOzJiCdDwAJ
