### ISSUE TITLE
Cannot install new versions from Hashicorp Repo

### ISSUE THREAD

**Issue by jeroenruytings** [hashicorp/vault#23734]
**Describe the bug**
The Vault package repository is broken, causing apt commands to fail. 

**To Reproduce**

```hcl
# curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
# apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
# apt-get update
# apt-get install -y vault='1.15.0'
```

This will produce output containing a message like so:

```hcl
# Reading package lists... Done
# Building dependency tree... Done
# Reading state information... Done
# Package vault is not available, but is referred to by another package.
# This may mean that the package is missing, has been obsoleted, or
# is only available from another source
# 
# E: Version '1.15.0' for 'vault' was not found
```

**Expected behavior**
Vault is getting downloaded and installed. It is working for some older versions (for instance 1.8.2)

**Additional context**
I've tested it both on my local pc and AWS EC2.

**Comment by ccapurso** [comment]
Hi, @jeroenruytings. correct apt package version for the 1.15.0 major release of Vault is `1.15.1-1`. I have confirmed this using `apt-cache`:

```
$ wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
$ echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
$ sudo apt update
$ sudo apt-cache showpkg vault | grep 1.15.0
1.15.0-1 -
```

I have run `sudo apt-get install -y vault='1.15.0-1'` and confirmed that `vault` installs as expected. Can you try these steps and let us know if you're able to do the same?

**Comment by ccapurso** [comment]
To add some additional context, this change was [announced](https://discuss.hashicorp.com/t/linux-packaging-debian-revision-change/42403) recently as part of our release notifications.

**Comment by jeroenruytings** [comment]
It works indeed, thanks!
