### ISSUE TITLE
web UI can not list k8s roles

### ISSUE THREAD

**Issue by kelvinatreslv** [hashicorp/vault#23800]
**Describe the bug**
Vault 1.15.0+ent.hsm Linux version,  when list kubernetes roles in non-root namespace  on web UI, get 404 error. 
It works fine when use CLI  "vault  list -namespace=application auth/kubernetes/role" or API with "X-Vault-Namespace" header.

**To Reproduce**
1. upgrade to 1.15.0+ent.hsm
2. create namespace and k8s auth and role
3. try list role on web UI.

**Expected behavior**
can list out roles on web UI.

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault 1.15.0+ent.hsm
* Vault CLI Version (retrieve with `vault version`): 
* Server Operating System/Architecture: ubuntu 22.04

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by cuevana8** [comment]
+1..[.](https://github.com/flslib/fl-studio-cracked)[@@@](https://github.com/hashicorp/vault/issues/23800#issue-1958719151)

**Comment by hashishaw** [comment]
Hey there, thanks for this detailed report! This was fixed with 1.15.1 as part of [this PR](https://github.com/hashicorp/vault/pull/23446).

**Comment by isman-usoh** [comment]
I have the same problem in versions 1.15.6+ent and 1.14.10+ent.

But this problem was not found on 1.15.5+ent and 1.14.9+ent.

**Comment by bukovjanmic** [comment]
We see the same, regression in 1.15.6+ent (not visible), it is correct in 1.15.5+ent
