### ISSUE TITLE
Inconsistent application of policies to path spec

### ISSUE THREAD

**Issue by ColinArenz** [hashicorp/vault#2385]
I've run into an issue with the Vault client which uses `GET` requests with `/?list=true` instead of `LIST` requests. This has exposed an issue in policies where adding a trailing slash requires an additional policy directive.

Here are the commands I used which illustrate the issue (this assumes the `approle` auth backend is enabled):
```
> vault policy-write temp -
{ "path": { "auth/approle/role": { "policy": "read" } } }
^D
Policy 'temp' written.

> vault token-create -ttl=10m -policy=temp
Key            	Value
---            	-----
token          	fedd7a84-8d1f-b9b5-64c1-13bfb09b1bfd
token_accessor 	b6d0aa3c-564d-6eb4-d626-b6ce7f83d0c8
token_duration 	10m0s
token_renewable	true
token_policies 	[default temp]

> vault auth fedd7a84-8d1f-b9b5-64c1-13bfb09b1bfd
Successfully authenticated! You are now logged in.
token: fedd7a84-8d1f-b9b5-64c1-13bfb09b1bfd
token_duration: 543
token_policies: [default temp]

> vault list auth/approle/role
Error reading auth/approle/role/: Error making API request.

URL: GET https://vault.inf.ai2:8200/v1/auth/approle/role/?list=true
Code: 403. Errors:

* permission denied
```
Expected:
```
> vault list auth/approle/role
Keys
----
testrole
```

Note that if I send a manually formed request without the trailing slash, the policy works:
```
> curl -X GET -H "X-Vault-Token:fedd7a84-8d1f-b9b5-64c1-13bfb09b1bfd" 'https://localhost:8200/v1/auth/approle/role?list=true'
{"request_id":"fb6ad207-1a77-ff3b-a934-c353573b2198","lease_id":"","renewable":false,"lease_duration":0,"data":{"keys":["testrole"]},"wrap_info":null,"warnings":null,"auth":null}
```

`LIST` also works, assuming no trailing slash:
```
curl -X LIST -H "X-Vault-Token:fedd7a84-8d1f-b9b5-64c1-13bfb09b1bfd" 'https://localhost:8200/v1/auth/approle/role'
```

**Comment by jefferai** [comment]
This is something we're aware of and are figuring out the best way forward. (Debating internally about canonicalizing within the ACL system based on operation, or just special-casing LIST in the HTTP API.)

**Comment by ColinArenz** [comment]
Thanks for the quick reply. Is there a related issue I can track to know when this is addressed?

**Comment by jefferai** [comment]
There isn't (publicly), but it will be changed in the 0.7 release.
