### ISSUE TITLE
 service account names and 403 errors should have a debug option that clarifies exactly what caused the 403

### ISSUE THREAD

**Issue by jayunit100** [hashicorp/vault#23896]
**Is your feature request related to a problem? Please describe.**

I think this could be a feature ... it's maybe a feature we should add that is exposed when debugging or audit logging.

**Problem**

I believe account name related 403 errors can happen in situations which are widely variant:
-  the pki or policies aren't setup properly... 
- the service account name is incorrect
- in the age of webhooks it's easy to interpret this 403 as possibly originating from the k8s apiserver instead of vault itself.

But enabling -debug and audit logs don't necessarily give you any hints as far as how to remediate a  403, and doesn't describe much about what a service account is and is not able to do.   This makes it not clear as to what policy entries needs to be updated.

**Describe the solution you'd like**
I'd like it if debug logs can be turned up to the point that they tell you what is and isn't allowed for a given 403 error. I think it would be awesome if you got these for free when running with debug option.  

**Describe alternatives you've considered**
Patching the service account parts of the codebase for one off logging in the specific code path where the 403s are returned. 

**Additional context**
I was experimenting w JWT auth to vault from certmanager in a container and found that when my svc account name wasn't able to request a cert it wasn't obvious why. I believe this wound up being due to me not setting up pki bc once i set up pki the error went away.

**Comment by ccapurso** [comment]
This could be useful when debugging Vault when running in _dev_ mode (i.e. `vault server -dev`). It is not something that we should support for Vault running in a production environment, however. The 403s are intentionally sparse since providing additional information could expose potential attack vectors. We will label this appropriately though which will us to provide additional review in the future.
