### ISSUE TITLE
UI - user can't delete secret

### ISSUE THREAD

**Issue by Tim-herbie** [hashicorp/vault#23941]
**Describe the bug**
User can create, list or delete secret versions, but can´t delete secrets permanently.

ACL:
```hcl
path "kv/+/secrets/+/project/" {
  capabilities = ["list"]
}

path "kv/+/secrets/+/project/*" {
  capabilities = ["create", "read", "update", "patch", "delete", "list"]
}
```

The path from the secret is:
```
secrets/kubernetes/project/test
```
**To Reproduce**
1. Create the ACL from above
2. Create a secret in this path: secrets/kubernetes/project/test
3. Assign the Policy to a user and try to delete the secret. It will not work

**Expected behavior**
With the above ACL Policy the user should have the permission to also delete secrets permanently

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.15.1
* Vault CLI Version (retrieve with `vault version`): /
* Server Operating System/Architecture: Kubernetes

**Comment by bastiao** [comment]
same here, I think this is a regression in recent versions.

**Comment by Tim-herbie** [comment]
Hi @ccapurso,
do you know if this behaviour is maybe expected in this version or is it a bug?

**Comment by ccapurso** [comment]
Hi, @Tim-herbie. I unfortunately do not work on the UI functionality within Vault. I will reach out internally to gain some context to provide.

**Comment by hellobontempo** [comment]
Hi there - I was unable to reproduce your issue. I'm using 1.15.1 and have logged in with the policy above, in the gif I am able to permanently delete the secret. The permanently delete functionality has moved to the `Metadata` tab in newer versions (previously the option was in a modal with the rest of the delete options).

![delete-kv](https://github.com/hashicorp/vault/assets/68122737/bca02ab9-5e68-4958-86b6-32f96b6437b8)

Do you have screenshots or the network error you are getting? Any additional information would be helpful to debug the issue!

**Comment by Tim-herbie** [comment]
HI @hellobontempo thank you for clarifying!

You are right, I can see the permanently delete button in the Metadata and it worked!

I will close the issue.
