### ISSUE TITLE
Bug in github.com/hashicorp/vault/sdk framework

### ISSUE THREAD

**Issue by ajaymohandas89** [hashicorp/vault#23963]
**Describe the bug**
I am using the package https://github.com/hashicorp/vault/blob/sdk/v0.10.2/sdk/framework/field_data.go

I believe GetOk() is just an enahancement of Get() Api,
Code reference:
https://github.com/hashicorp/vault/blob/sdk/v0.10.2/sdk/framework/field_data.go#L97

https://github.com/hashicorp/vault/blob/sdk/v0.10.2/sdk/framework/field_data.go#L142

If we drill down to the logic the if conditional logic seems to be incorrect
https://github.com/hashicorp/vault/blob/sdk/v0.10.2/sdk/framework/field_data.go#L153

It should be exact copy of https://github.com/hashicorp/vault/blob/sdk/v0.10.2/sdk/framework/field_data.go#L106

if the value is nil or ok turns out to be false we should set the default value from fieldset

**Expected behavior**
It should be exact copy of https://github.com/hashicorp/vault/blob/sdk/v0.10.2/sdk/framework/field_data.go#L106

**Comment by ccapurso** [comment]
Hi @ajaymohandas89, you are correct that `GetOk` is an enhancement of the `Get` method. `GetOk` is meant to be a safer version in that the value _must_ decode properly. This constraint is provided via the `if ok && result == nil` constraint provided by https://github.com/hashicorp/vault/blob/sdk/v0.10.2/sdk/framework/field_data.go#L153. Do you by any chance have an example the existing logic does not meet your expectations?

**Comment by ajaymohandas89** [comment]
When creating a plugin for vault I had below code

 "default_ttl": &framework.FieldSchema{
        Type: framework.TypeDurationSecond,
        Default: "8h",
        Description: "Optional default TTL to apply to keys.",
        },

v, ok := d.GetOk("default_ttl");

But when testing the plugin the default value was not being set; 0s value was set. For now I am using below API to overcome the issue


duration := time.Duration(d.Get("default_ttl").(int)) * time.Second

**Comment by ajaymohandas89** [comment]
the reason GetOk() did not work is because value of "ok" turns out to be false if not set and hence result = schema.DefaultOrZero() is not being called

**Comment by ccapurso** [comment]
Thank you for the context! I believe that `GetOk` is intended for cases where the field is expected to be present but will coerce the value to the appropriate zero-value or default, in your case `"8h"`, if it is valid for the value to be `nil`. In the case of `TypeDurationSecond`, that does not seem to be a valid case. See https://github.com/hashicorp/vault/blob/sdk/v0.10.2/sdk/framework/field_data.go#L251-L255.

I have provided a few scenarios below to outline how the field will be parsed.

```
package main

import (
	"fmt"

	"github.com/hashicorp/vault/sdk/framework"
)

func main() {
	fd := framework.FieldData{
		Schema: map[string]*framework.FieldSchema{
			"default_ttl": &framework.FieldSchema{
				Type:        framework.TypeDurationSecond,
				Default:     "8h",
				Description: "Optional default TTL to apply to keys.",
			},
		},
		Raw: map[string]interface{}{
			"default_ttl": nil,
		},
	}

	defaultTTLRaw, ok := fd.GetOk("default_ttl")
	fmt.Println(defaultTTLRaw, ok)

	fd.Raw["default_ttl"] = ""
	defaultTTLRaw, ok = fd.GetOk("default_ttl")
	fmt.Println(defaultTTLRaw, ok)

	fd.Raw["default_ttl"] = "2h"
	defaultTTLRaw, ok = fd.GetOk("default_ttl")
	fmt.Println(defaultTTLRaw, ok)
}
```

```
❯ go run main.go
<nil> false
0 true
7200 true
```

**Comment by ajaymohandas89** [comment]
Can you please provide an example when ok is true but result is nil here and then result = schema.DefaultOrZero() will be executed for GetOk()

https://github.com/hashicorp/vault/blob/sdk/v0.10.2/sdk/framework/field_data.go#L153

Shouldnt it be similar to https://github.com/hashicorp/vault/blob/sdk/v0.10.2/sdk/framework/field_data.go#L106

**Comment by ccapurso** [comment]
The original logic in the `framework` package has been around since the earliest versions of Vault. Unfortunately, it seems that whether a subsequent call to `schema.DefaultOrZero` is based on type-specific `getPrimitive` logic and potentially even how `mapstructure.WeakDecode` handles a specific value. Modifying the way that default values are handled across all types is likely a backward-incompatible change which could potentially negatively impact all Vault users. For example, submitting the same API request body may result in different results from one version to another if we were to make the proposed change.

**Comment by ajaymohandas89** [comment]
In some case of **getPrimitive** method, I trying to find where we return **ok** as true and result as nil but could not find and hence I think default values do not get set. Like in this scenario, https://github.com/hashicorp/vault/blob/sdk/v0.10.2/sdk/framework/field_data.go#L319

But yeah I understand, we would not want any negative impact on vault. I am okay to use Get() Api which has logic to set the default value. 

Thank you for looking into this ticket.

**Comment by ccapurso** [comment]
We appreciate your feedback as well!
