### ISSUE TITLE
1.15.x web ui kv icon always file, never folder

### ISSUE THREAD

**Issue by rjhornsby** [hashicorp/vault#23978]
**Describe the bug**
The web ui was overhauled in 1.15.x, and it looks like the kv folder icon has been replaced with the file icon. Now all items, regardless if they are a kv path or a secret object, are showing as the file icon.

I don't have screenshots to prove it, but I'm fairly certain prior to 1.15 these were folder icons.

**To Reproduce**
1. Open the vault web UI
2. Browse to a kv secret path - but not the secret itself, the containing path
3. The icon for the path looks like a file, not a folder
![Screenshot 2023-11-02 at 15 57 04](https://github.com/hashicorp/vault/assets/5077610/561235b2-4129-468d-8f7c-a3d396e1f29a)

**Expected behavior**
The icon should be a folder.

**Environment:**
* Vault Server Version: 1.15.1

**Additional Details:**

In a very general sense, this is not uncommon for specific parts of vault to behave as if there is no user-defined directory-like structure. I can't locate the exact details, but there have been bugs where, for example, you could only configure the approle(?) authentication at an exact, hard-coded depth because of a bug that assumed the path to the approle auth would have 3 and only 3 components. (Technically you could set up an approle at a path depth greater than 3, but things would break)

It's a separate bug that I'll file separately, but this generalized behavior is also showing up in the new UI dashboard > Quick Actions > kv > find kv secrets > secret path, where the search only recognizes top level paths. For example, if you have a secret at `chef/cookie`, the search will say "no results found" once you get past typing `chef/`

Vault absolutely (and obviously) supports path-based logic of arbitrary depth - but over time parts of vault seem to ignore or forget this.

**Comment by hsimon-hashicorp** [comment]
Hi there! Can you please confirm in the CLI that you have permissions to view `chef/cookie` as the user you're logged into the UI as? Thanks!

**Comment by rjhornsby** [comment]
If it matters I mentioned the `chef/cookie` path weirdness here as an example of more general path treatment but did file it as a separate bug #23979

> Can you please confirm in the CLI that you have permissions to view chef/cookie as the user you're logged into the UI as? Thanks!

Yep, they're the same permissions. Just to be 100% sure, I verified I could access the secret through the CLI and then took that token and used it to authenticate to the UI.

**Comment by hsimon-hashicorp** [comment]
Thanks for the clarification! :)
