### ISSUE TITLE
Add environment variables to output of CLI `-help`

### ISSUE THREAD

**Issue by amiryal** [hashicorp/vault#2401]
My feature request is to add the important bits from [docs/commands/environment.html](https://www.vaultproject.io/docs/commands/environment.html) to the CLI help output. Otherwise, one needs to refer back to the online help while working on the command line.

Thanks,
Amir

**Comment by jefferai** [comment]
I believe most of these are documented with the respective flags that they affect. If you have specific ideas/requests please feel free to send a PR!
