### ISSUE TITLE
1.15.0 illegal instruction on ARM 7 v6l

### ISSUE THREAD

**Issue by brucellino** [hashicorp/vault#24020]
**Describe the bug**
An instruction is introduced in v1.15.0 which breaks execution on Raspberry Pi Zeros -- ARMv6 compatible rev 7:

**To Reproduce**

1. Download [Vault 1.15.0 for ARM](https://releases.hashicorp.com/vault/1.15.0/vault_1.15.0_linux_arm.zip)
2. Run `vault -version`
3. Get error `illegal instruction`

**Expected behavior**
Exected command to return version with build hash

**Environment:**
* Vault Server Version: N/A
* Vault CLI Version: v1.15.0
* Server Operating System/Architecture

OS:
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

CPU:
```
lscpu 
Architecture:        armv6l
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
Vendor ID:           ARM
Model:               7
Model name:          ARM1176
Stepping:            r0p7
CPU max MHz:         1000.0000
CPU min MHz:         700.0000
BogoMIPS:            997.08
Flags:               half thumb fastmult vfp edsp java tls
```

Vault server configuration file(s):
N/A

**Additional context**

I've checked the latest patch releases from 1.11 to 1.14 to ensure that the behaviour was introduces in 1.15.0.

**Comment by ccapurso** [comment]
Thank you for bringing this to our attention, @brucellino! I have opened https://github.com/hashicorp/vault/pull/24061 to address this regression.

**Comment by brucellino** [comment]
Anytime hashihomies, glad to have been of service!

**Comment by bdkuhman** [comment]
I'm getting this while installing through apt.

Package vault_1.15.5-1_armhf.deb

Raspian bullseye on a rpi Zero W 1.1
