### ISSUE TITLE
Fix kerning between "VA" in logo

### ISSUE THREAD

**Issue by ramalho** [hashicorp/vault#2402]
The Vault project logo is beautiful, congratulations!

However, the version that is spelled out as "VAULT" needs tighter kerning between the symbol standing for the V and the A after it.

Please see the first image in the Wikipedia article on [Kerning](https://en.wikipedia.org/wiki/Kerning), where the pair of letters AV illustrates the problem.

**Comment by vishalnayak** [comment]
@captainill over to you.

**Comment by ramalho** [comment]
Thanks, @vishalnayak! BTW, when the kerning between VA is fixed, the LT will stand out and need kerning too. Otherwise it's a fine logo, I'd wear it in a t-shirt (and the product is great too).

**Comment by aassaad** [comment]
Here's two quick attempts. The "V" graphic is taken from the highest res version of the logo that reverse image search turned up, text is _Lato Thin_ which seems to be the original font, but the weight's a little off.

---
+20% letter spacing, moving the 'AUL' apart to fit the original width
<div  align="center">
    <img draggable="true" height="120" width="auto" src="https://cloud.githubusercontent.com/assets/7354608/23581655/d1b4c9f4-00e5-11e7-8c14-97bdcd52efd5.png">
</div>
<br/>
<br/>
<div align="center">
    <img draggable="true" height="auto" width="621" src="https://cloud.githubusercontent.com/assets/7354608/23581915/7479ec18-00ec-11e7-85b5-314916b18a3b.png">
</div>
Original

---

+5% spacing, moving the 'V' and 'T' inwards to match the inner letters
<div align="center">
    <img draggable="true" height="120" width="auto"  src="https://cloud.githubusercontent.com/assets/7354608/23581654/d1b495f6-00e5-11e7-9b3d-bfc7f9e15673.png">
</div>
<br/>
<br/>
<div align="center">
    <img draggable="true" height="auto" width="621" src="https://cloud.githubusercontent.com/assets/7354608/23581915/7479ec18-00ec-11e7-85b5-314916b18a3b.png">
</div>
Original

**Comment by jefferai** [comment]
Closing as this isn't our logo anymore :-)
