### ISSUE TITLE
Token With Lease

### ISSUE THREAD

**Issue by revof11** [hashicorp/vault#2404]
I'd love to see a feature that sets up temporary, one-off tokens with a lease time.  Not for accessing Vault, but instead something that just keeps a list of generated, temporary, random tokens with a date/time of eviction from the Vault.

Currently, in my implementations, I use my own Redis/memcached/etc.-based repo where I store UUIDs with an eviction policy.  I typically wrap this in a microserve that sits with my Vault access routines.

There are no exposed look-ups.  The only supported operations are "does key exist" and "get new for old".

See [this sequence diagram](https://www.websequencediagrams.com/?lz=VXNlci0-QXV0aGVudGljYXRpb24gUHJvY2VzczogYXV0aGMvYXV0aHoKAA4WLT5Vc2VyOiBzdWNjZXNzCgBKBkNvcmUgU2VydmljZXM6IGZldGNoIHF1aWNrIGEAIwUgdG9rZW4KABsNLT5WYXVsdDogZ2V0IHRlbXBvcmFyeSBkYXRhCgAVBQBHEXJlc3BvbmQKbm90ZSBsZWZ0IG9mIAA-B3tcbiAgIlRva2VuIjogInNvbWUtdXVpZCIsABQFRXhwaXIAgWkFIjogIm4gbWludXRlcyBmcm9tIG5vdyJcbn0AgQ8QAIFlBXJlbGF5AGQOAIFfD0pTT04gZG9jdW1lbnQAggoHU29tZSBPdGhlcgCCDwg6IGRvIHNvbWUgc3R1ZmYAgT4GcmlnaACBQAUAgk8GAIE5BQoAKhIAgiEJY2hlY2sAgkUHCmFsdCByZWplY3RlZAogAIICBgBjF2VuaQAfBQBHFACDSgYAglMIICAAglANAIE0FEZhaWx1cmUgUmVzdWx0CmVuZACBBgZhY2NlcABrIWFja25vd2xlZGcASEoAhTkHaW5nAIEOB3MKIACCTgUAhQkRZ2V0IG5ldwCFCAcAgWYHAIJ3D09sZACDAwcgAINdDgCFKAlyZXBsYWNlAC8XAIV-DwBDDACFOR4Agm0PAIYXB05ldwCEEwYgRGF0YQCBAhIAhRsLAIMuDwCFCx1lbmQK&s=rose) for a sample concept.

This may technically be out-of-scope, but there's no harm in the ask.

**Comment by jefferai** [comment]
Hi @revof11 ,

I'm not entirely sure I understand the ask -- it's easy to create Vault tokens that are one-time and have a TTL, but maybe a simple way for you to do this would be to use https://www.vaultproject.io/docs/http/sys-wrapping-wrap.html ?

**Comment by revof11** [comment]
That's actually perfect.

**Comment by jefferai** [comment]
Great!
