### ISSUE TITLE
Vault crashes with "fatal error: concurrent map iteration and map write"

### ISSUE THREAD

**Issue by trevop** [hashicorp/vault#24055]
**Describe the bug**
The leader crashes with the error `fatal error: concurrent map iteration and map write`. 

I have an assumption that it might be due to integration with Openshift OKD and whenever external-secret-operator tries to renew tokens Vault crashes. In addition second guess could be due to Vault trying to make a snaphost and recieves Golang exception.  

**To Reproduce**
It is hard to say how to reproduce it but generally:
1. Have a working cluster of vault with Raft storage backend (in our case it is 5 nodes) 
2. Integrate Vault with OKD with external secrets operator and wait for token to be renewed
3. Try to take a snapshot of vault OR configure automatic snapshot and wait
4. Observe the error

**Expected behavior**
Vault doesn't crash.

**Environment:**
* Vault Server Version: `1.15.1`
* Vault CLI Version: `1.15.1`
* Server Operating System/Architecture: `CentOS 8 Stream x86_64`

Vault server logs file(s):

Please see attached log file.
[vaultlogs.txt](https://github.com/hashicorp/vault/files/13293404/vaultlogs.txt)

**Comment by raskchanky** [comment]
This should be fixed by https://github.com/hashicorp/vault/pull/24027
