### ISSUE TITLE
Slow release notes process

### ISSUE THREAD

**Issue by umglurf** [hashicorp/vault#24074]
**Describe the bug**
The time from a new release is made until the release notes are updated and the changelog file updated is very long. I got a notification from Github about the Vault 1.15.2 release, but with empty release notes. It's now been 10 hours, and still the release notes and changelog has not been updated. This seems to have been the case for a long time.
The disconnect between releases and the actual release release information causes issues with automated dependency update mechanisms such as dependabot and renovate, as they will trigger an update PR when the release is made, but without any information about what has changed in the release.

**To Reproduce**
1. Get notification about a new vault release
2. See that the release notes contains no information about what is new/changed
3. Open CHANGELOG.md and see that it is empty

**Expected behavior**
Most projects creates complete releases, that is when they create a release it includes complete release notes, updated changelog if applicable and all assets. This does seem to be the case with other Hashicorp products such as for instance Terraform, so would expect it from Vault as well.

**Environment:**
* Vault Server Version (retrieve with `vault status`): N/A
* Vault CLI Version (retrieve with `vault version`): N/A
* Server Operating System/Architecture: N/A

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by ccapurso** [comment]
Thank you for the feedback, @umglurf! I agree that we could provide a better experience here. I have passed on your feedback to the appropriate teams.

**Comment by mila-rodriguez-netapp** [comment]
It's been 16 hours since the new release of Vault, and still no release notes. Has this _really_ been completed?

**Comment by Foxboron** [comment]
11 hours between the `v1.15.5` release and still no changelog.

Why was this issue closed?

**Comment by mladlow** [comment]
Hey folks,

Our current release process publishes a number of things in sequence and takes over an hour to release a full Vault version across community and enterprise editions. We release three or four new Vault versions every time we do a release, so publishing artifacts consumes approximately an entire day.

The GitHub tag availability isn't our formal release announcement. We send release announcements via email ([hashicorp-announce@googlegroups.com](mailto:hashicorp-announce@googlegroups.com), [vault-tool@googlegroups.com](mailto:vault-tool@googlegroups.com)) and via Discuss (https://discuss.hashicorp.com/c/release-notifications/57). These announcements signify that the release is available for general consumption.

The release process is a mix of automated and manual steps. The manual steps are gated on the automated publishing workflows. These include updating the release notes in GitHub, posting the aforementioned announcements, and updating the changelog. At this time please continue to expect approximately a 24-hr window between the time when the artifacts/GitHub tags are available and when the releases are formally published.

We appreciate your patience as we continually work towards a faster and more automated release process.
