### ISSUE TITLE
Normal account encounters a certificate verification failure when running vault command  in ubuntu system, but root account is ok

### ISSUE THREAD

**Issue by remriver** [hashicorp/vault#24098]
**Describe the bug**
Running command using a normal system account: `vault status`，the console output  prompt below: 
_Error checking seal status: Get "https://127.0.0.1:8200/v1/sys/seal-status": tls: failed to verify certificate: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs_
but the same command executed using root account produce normal output related to it.

**To Reproduce**
As described above

**Expected behavior**
A normal output or a informative failure prompt

**Environment:**
* Vault Server Version (retrieve with `vault status`): v1.13.2
* Vault CLI Version (retrieve with `vault version`): v1.13.2
* Server Operating System/Architecture: Ubuntu 20.04.6 LTS

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
storage "file" {
  path = "/opt/vault/data"
}
listener "tcp" {
  address = "localhost:8200"
  tls_cert_file = "/usr/security/server.cert"
  tls_key_file = "/usr/security/server.key"
}
```

**Additional context**

**Comment by sgmiller** [comment]
What are the permissions present on the cert and key files?

**Comment by remriver** [comment]
> What are the permissions present on the cert and key files?

It's a mistake of mine instead an issue of vault, because I hadn't set environment variables correctly. Sorry for that.

**Comment by remriver** [comment]
Not an issue.
