### ISSUE TITLE
Feature request: Package signing backend

### ISSUE THREAD

**Issue by Millnert** [hashicorp/vault#2409]
Not too dissimilar for the motivations for the Transit secret backend (managed by crypto teams, running in a secure/isolated environment, etc), there is a fairly good use case for integrating a package signing secret backend feature with Vault.
AFAIK both RPM and DEB package signing rely on PGP (GPG) keys.

Lemmas:

1. A large amount of organisations use RPM's and/or DEB's to manage software and data in their environments.
2. A secure environment relies on verifiable code and data, which almost always means cryptographic signatures covering the code & data in question.
3. The use of RPM's and/or DEB's is not going to go away any time soon, and regardless, a substitute methodology would still be affected by 2).
4. Securely setting up package signing is somewhat of a hassle, especially w.r.t automating the signing feature, where organisations are either reluctant to fully automate (thus, often exposing keys and key passwords), or, do fully automate and thereby expose their keys.
5. A relatively safe way of handling package signing is to use a "signing service" (potentially with signing service's key on HSM or equivalent), since it decreases the interface surface between the users of package signing, and the package signing itself.

A package signing feature within Vault would essentially address all of the above, and deliver more security to users of RPM/DEB packages. It could easily be automated by developers and integrated in package building environments. The addition of roles to keys could be valuable and allow for distinction between for example testing and production keys. Regardless of key role, the auditing infrastructure in Vault can be relied upon to identify incorrect or suspect/malicious usage of the signing feature.

Some self-criticism is for example that, of course, if the package build environment is fully automated, and becomes compromised, signed packages could come out of the environment regardless.
This is where different key roles for dev/prod comes in handy, where packages can be re-signed before promotion in the pipeline, possibly by other machines or teams.

From own experience, this functionality would indeed solve a major hassle, and I imagine that for most less-than-webscale orgs the situation is quite similar. This, obviously, would improve the utility function of Vault for many orgs, and could quite possibly provide a compelling use case for starting using Vault in environments that haven't done so yet.

**Comment by jefferai** [comment]
We wouldn't have a package signing backend, as it's too single-purpose. We've had some thoughts around a generalized PGP backend that can perform useful functions without revealing the private keys, but our main reason for wanting it -- signing Git commits -- requires some way to have Git use it for signing, which isn't possible right now with the main Git client.

Either way this isn't going to be worked on by the core team anytime soon. If you are interested in implementation, get in touch before starting so we can see if there is a featureset/API/etc. that we can agree on and that would likely get merged.

**Comment by abdennour** [comment]
Any update about this thread @jefferai  ? 
can we expect a PGP as service with Vault: 
- HTTP GET  -- mapped to `gpg2 --list-keys`
- HTTP PUT -- mapped to `gpg2 --gen-key`
- HTTP POST sign ...
- ... so on 
?
