### ISSUE TITLE
Vault 0.6.5 "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by jasonmichaelmartin** [hashicorp/vault#2415]
After installing Vault 0.6.5 on a new Consul Cluster I get  "x509: certificate signed by unknown authority"
when running `vault status`.

# /opt/vault/0.6.5/vault status
Error checking seal status: Get https://<vaullt_server>:8200/v1/sys/seal-status: x509: certificate signed by unknown authority` 

After reverting back to 0.6.2 the issue goes away.

# /opt/vault/0.6.2/vault status
Error checking seal status: Error making API request.

URL: GET https://<vault_server>:8200/v1/sys/seal-status
Code: 400. Errors:

* server is not yet initialized

**Comment by jefferai** [comment]
You haven't given any details about your environment, but likely this is due to some difference in how Go is looking up CA certificates. What platform?

**Comment by jefferai** [comment]
I am fairly certain you are hitting https://github.com/golang/go/issues/18813 -- 0.6.5 was built against go 1.8rc3 and this was fixed between then and the final release.

You have a couple of options:

1) Wait for 0.7 (a beta will go out very soon, which should fix this problem)
2) Rebuild 0.6.5 yourself against Go 1.8 final.

**Comment by jefferai** [comment]
Closing as at this point Vault 0.7 is out.

**Comment by RRAlex** [comment]
I'm hitting the same issue upgrading from 0.6.2 to 0.7.2.
Did any other configuration change?

**Comment by jefferai** [comment]
@RRAlex is your Vault server and client both 0.7.2?

**Comment by RRAlex** [comment]
@jefferai it's a single instance vault server connecting to a single consul 0.7.4 backend.

**Comment by jmccann** [comment]
I'm also running into a similar/same issue.  I'll preface this with this is my first time setting up vault/consul.

But the certificates I generated are working/verifying fine between consul nodes.  I'm using same files to have vault communicate with consul.  But get

```
2017/06/06 21:14:49.619622 [WARN ] physical/consul: reconcile unable to talk with Consul backend: error=service registration failed: Put https://127.0.0.1:9000/v1/agent/service/register: x509: certificate signed by unknown authority
```

I've also tried to use `tls_skip_verify` but still get above error.  But not sure if it's using/honoring it as docs say it's a bool but had to use a string otherwise I get the following error:

```
Error loading configuration from /vault/config: Error loading /vault/config/local.json: error parsing 'storage': storage.consul: At -: root.tls_skip_verify: unknown type for string *ast.LiteralType
```

**Comment by karl-tpio** [comment]
I am running into an almost identical issue on vault 1.1.0. `tls_skip_verify` is **not** of type `bool` as the docs say.  it must be treated as type `string` to prevent startup issues.

https://github.com/hashicorp/vault/issues/6602
