### ISSUE TITLE
Accessing UI at path /ui/vault/access/token/configuration creates unexpectedly large audit message

### ISSUE THREAD

**Issue by maxiscoding28** [hashicorp/vault#24160]
**Describe the bug**
Accessing the UI at path `/ui/vault/access/token/configuration` triggers two requests to the endpoint /v1/auth/token/?help=1 . This endpoint appears to be related to OpenAPI information related to the token authentication method. When accessing this UI view, two requests are triggered to this endpoint creating an HMAC'ed audit response of roughly 176K.

It is unclear why these requests are necessary since none of the information appears to be rendered in this UI view. If they are in fact necessary, it is unclear why the request needs to be triggered twice.

**To Reproduce**
1. Enable a file type audit device - `vault audit enable -path=audit file file_path=/home/vault/audit.log`
2. Note the size of the file - `ls -lah | grep audit`
3. Perform two requests to the endpoint `/v1/auth/token/?help=1`
- `curl -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" http://127.0.0.1:8200/v1/auth/token/?help=1`
- Alternatively, you can access the UI at `/ui/vault/access/token/configuration`
4. Check the size of the audit file again - `ls -lah | grep audit`
5. Observe that the size has increased by roughly 170k.

**Expected behavior**
Need clarification on intended behavior. The expected behavior is that these requests are not triggered at all for this UI view. If it is necessary, then an understanding of why it can't be triggered only once. 

**Environment:**
(This was tested on Vault versions 1.14.6 and 1.15.2)

**Comment by Monkeychip** [comment]
@maxiscoding28 thank you for the issue. An internal ticket has been created for this. We will update this issue when any information/progress is made.
