### ISSUE TITLE
Child token renew resets `identity_policies` on parent token

### ISSUE THREAD

**Issue by bozaro** [hashicorp/vault#24209]
**Describe the bug**
After read `auth/token/renew-self` on child token I lost `identity_policies` value on parent token.

**To Reproduce**

1. Create parent token by login to vault (`vault login --method oidc`);
2. Create child token (`VAULT_TOKEN="${CHILD_TOKEN}" vault token create`);
3. Save anywhere `auth/token/lookup-self` for parent token (`before.renew.yaml`);
4. Renew child token (`VAULT_TOKEN="${CHILD_TOKEN}" vault write auth/token/renew-self increment=1h`);
5. Save anywhere `auth/token/lookup-self` for parent token (`after.renew.yaml`);
6. Compare `identity_policies` field in outputs from step 3 and 5 (`diff -c before.renew.yaml after.renew.yaml`)

Script for reproduce: 
```sh
#!/bin/bash
# Step 1. Create parent token by login to vault
rm ~/.vault-token
vault login --method oidc

# Step 2. Create child token
CHILD_TOKEN="$(vault token create --field=token)"
VAULT_TOKEN="${CHILD_TOKEN}" vault read auth/token/lookup-self

# Step 3. Save parent token info before child token renew
vault read --format=yaml --field=data auth/token/lookup-self | tee before.renew.yaml

# Step 4. Renew child token
VAULT_TOKEN="${CHILD_TOKEN}" vault write auth/token/renew-self increment=1h

# Step 5. Save parent token info after child token renew
vault read --format=yaml --field=data auth/token/lookup-self | tee after.renew.yaml

# Step 6. Compare parent token info before and after child token renew (expected delta only on ttl field)
diff -c before.renew.yaml after.renew.yaml
```

And got delta like:
```diff
*** before.renew.yaml	2023-11-21 13:34:54.782422890 +0300
--- after.renew.yaml	2023-11-21 13:34:55.538428157 +0300
***************
*** 5,17 ****
  entity_id: 17969b1c-f48f-b03b-00d9-bb95cc2b9b3f
  expire_time: "2023-11-22T06:34:53.722324264Z"
  explicit_max_ttl: 0
- external_namespace_policies: {}
  id: hvs.CAESID-VxhAzbRQ8aKxz3trBxYa3kb6P2sU1q5ihla24oL-TGh4KHGh2cy50dWNrM0ZCcnZBU1E1dUtFVXVHVTc4OEc
- identity_policies:
- - backend.developers
- - developers
- - devops-duty-stash-writer
- - joom_dpt_infrastructure
  issue_time: "2023-11-21T10:34:53.722329127Z"
  meta:
    role: default
--- 5,11 ----
***************
*** 21,25 ****
  policies:
  - default
  renewable: true
! ttl: 71998
  type: service
--- 15,19 ----
  policies:
  - default
  renewable: true
! ttl: 71997
  type: service
```

**Expected behavior**
Expected delta on `auth/token/lookup-self` parent token value only on `ttl` field.

**Environment:**
* Vault Server Version (retrieve with `vault status`): `1.12.2`
* Vault CLI Version (retrieve with `vault version`): `Vault v1.11.2 (3a8aa12eba357ed2de3192b15c99c717afdeb2b5), built 2022-07-29T09:48:47Z`
* Server Operating System/Architecture: Ubuntu 22.04.3 LTS, x86_64

**Comment by marcboudreau** [comment]
I have tried to reproduce this issue against the stated version (`1.12.2`) as well as a recent version of Vault (`1.16.2`) and did not observe the reported issue. I created a script that setups all of the necessary resources in the Vault server referenced in the report (as I understood it). This script requires the **VAULT_ADDR** environment variable to be appropriately set. It also requires that a **root** Vault token be available either via the **VAULT_TOKEN** environment variable or in the `~/.vault-token` file.

The script setups the following resources in an idempotent manner (so it can be re-run safely):
> - Vault policy named **test** that allows reading secrets and creating a child token
> - Userpass authentication method with a user named **test**
> - Entity named **test** with an alias to the above authentication method and an identity policy of **test**

Once those resources are setup, the script uses the userpass authentitcation method to create the _parent_ Vault token. Its properties (result of `vault token lookup`) are written to a file _parent.before-child_ in the current directory. Next, a child token is created with a shorter TTL. The parent's properties are once again captured and stored in _parent.after-child_. The child token's properties are also captured and stored in _child.before-renew_. Finally, the child token is renewed and both the parent's and child's properties are once again captured in _parent.after-renew_ and _child.after-renew_ respectively.

Running diff between _parent.before-child_, _parent.after-child_, and _parent.after-renew_ shows that there are no differences, except for the occasional difference in the remaining TTL of the parent token (`6h` vs `5h59m59s`). And, running diff between _child.before-renew_ and _child.after-renew_ shows the expected differences: change in TTL, recording of the last renewal time, etc...

I'm attaching my script here as well as the diff output for the child token properties captures.
[testcase.sh.txt](https://github.com/hashicorp/vault/files/15239999/testcase.sh.txt)
[report.txt](https://github.com/hashicorp/vault/files/15239882/report.txt)
