### ISSUE TITLE
Stream large uploads to disk instead of reading everything into memory

### ISSUE THREAD

**Issue by benvanstaveren** [hashicorp/vault#24254]
**Is your feature request related to a problem? Please describe.**
When given a large snapshot to restore, it seems Vault will read the entire snapshot into memory; from observation, memory consumption will be about 4 times the snapshot size. This leads to fun times when you restore a ~30Gb snapshot on a machine with 64Gb of memory due to the vault process being OOM-killed. Adding swap space alleviates the problem but slows things down to a speed that'd bore a snail to death.

**Describe the solution you'd like**
For any upload larger than, say, a few Gb, stream the request body to a temporary file and move that into the right location once the request completes. If this is already the case (unsure since I don't read go code for breakfast) then reducing the memory consumption should be a thing. 

**Describe alternatives you've considered**
No alternatives ;)

**Explain any additional use-cases**
Snapshots, really...

**Additional context**
It's considered bad form to read a large request body into memory, most (if not all) frameworks support switching to using a temporary file on disk if a request is larger than a configured size, so unsure why this isn't already done. If it is done, unsure as to why vault will use that much memory. The actual application of the snapshot once it's uploaded takes next to no resources.

**Comment by miagilepner** [comment]
This has been fixed in 1.15.4, 1.14.8 and 1.13.12.
