### ISSUE TITLE
Unable to Retrieve STS Token using Golang SDK with Aliyun Secrets Engine

### ISSUE THREAD

**Issue by bearoz** [hashicorp/vault#24267]
Hello,

I am currently using the Aliyun Secrets Engine with Vault, and I am trying to retrieve an STS token using the Golang SDK. However, I am encountering some issues.

Here is the code snippet I am using:

```
client, err := api.NewClient(&api.Config{
   Address: "http://xxx:8200",
})

if err != nil {
    log.Fatalf("Failed to create Vault client: %v", err)
}

secret, err := client.Logical().Read("aliyun/creds/role-based")
if err != nil {
    log.Fatalf("Failed to read secret: %v", err)
}

fmt.Printf("%+v\n", secret.Data)
```

When I run this code, the secret.Data does not contain the STS token. Instead, it contains the following:

```
map[inline_policies:<nil> max_ttl:0 remote_policies:<nil> role_arn:acs:ram::xxx:role/test ttl:0]
```

However, when I use the vault command-line tool with the same path, it works perfectly:
```
vault read Demo-Server/creds/role-based
```

I am confused as to why the Golang SDK does not return the STS token. Is there something I am missing or doing wrong? Any guidance or suggestions would be greatly appreciated.

Thank you!

**Comment by miagilepner** [comment]
> When I run this code, the secret.Data does not contain the STS token. Instead, it contains the following:
>
> ```
> map[inline_policies:<nil> max_ttl:0 remote_policies:<nil> role_arn:acs:ram::xxx:role/test ttl:0]
> ```

This is the response that I would expect from running 
```go
secret, err := client.Logical().Read("aliyun/role/role-based")
```

Is it possible that this output line comes from calling that endpoint?

**Comment by bearoz** [comment]
I made a mistake with the path. The previous return was "aliyun/role/role-based", not "aliyun/creds/role-based". After correcting it, I was able to generate the STS token normally. Thank you~
