### ISSUE TITLE
Extracting secret value back to file

### ISSUE THREAD

**Issue by james-masson** [hashicorp/vault#243]
Hi,

I've written the contents of a file to Vault with the usual syntax
```
vault write secret/bitbucket-key value=@myfile
```
In my case, this is an RSA key. Now I'm trying to read it back out into a file again.

The ```vault read``` output options either give me a tabular format, or a JSON format - Neither of which are trivial to process back into the exact original text file.

I've also looked at using curl via the API directly - but that too gives me back a (slightly different) JSON format.

Right now, I'm looking at piping the command line ```vault read -format=json``` output through a few bits of Python code to extract only the value, and write that to a file. This seems a little inelegant.

Have I missed a better way to do this?

If not, I'd like to request a command line feature to...

either:
* Output only the value

or
* Write the value to a file directly

thanks!

**Comment by armon** [comment]
I think we need something like this, Potentially just a `-raw-field <Name>` which just emits the value of that particular field to stdout. That ways its easy to do:

```
$ vault read -raw-field value secret/my-pem > my-pem.pem
```

**Comment by sethvargo** [comment]
@armon how does curl handle this? Does it just treat everything as binary?

**Comment by armon** [comment]
@sethvargo I think so. I think it just dumps the raw JSON body out.
