### ISSUE TITLE
Improve debug logs to be more informative

### ISSUE THREAD

**Issue by Tim-herbie** [hashicorp/vault#24303]
**Is your feature request related to a problem? Please describe.**
We have currently the problem that one kubernetes cluster can´t authenticate against our vault-server that is hosted on another kubernetes cluster when the clusters communicate over a firewall. We don´t know the problem, but we guess that it is a network issue.

The debug logs from vault says only, that the login request ends with 403. If we change some network stuff (routing) it works directly. So it can´t be a permission problem. The audit logs didn´t provide us any useful other informations. We can only see that the connection breaks after exactly 30s.

I posted already additional informations [here](https://discuss.hashicorp.com/t/vault-kubernetes-kubernetes-authentication-permission-denied-troubleshooting/59699)

**Describe the solution you'd like**
Improve the audit logs to be more informative.

**Comment by biazmoreira** [comment]
Great to hear you were able to solve the problem! I'm closing this issue for now, but we'll keep an eye on logs improvement. Thank you!
