### ISSUE TITLE
Github Auth Backend authentication via the API

### ISSUE THREAD

**Issue by mavdi** [hashicorp/vault#2433]
I would like to do

```bash
vault auth -method=github token=<api token>
```

via the API. Passing the Github token via `X-Vault-Token` doesn't work.

```bash
curl -sS -X GET -H "X-Vault-Token:$VAULT_TOKEN" $VAULT_SERVER/v1/secret/foo
```

I couldn't find anything in the source code either. How would I go about passing the method when authentication to Github via the API?

Any help is much appreciated.

**Comment by briankassouf** [comment]
First you need to get a vault token from the auth endpoint:

```
curl $VAULT_ADDR/v1/auth/github/login \
    -d '{ "token": "your_github_personal_access_token" }'
```

More info can be found here: https://www.vaultproject.io/docs/auth/github.html#authentication

**Comment by mavdi** [comment]
Thank you, just found that as you sent the reply.
