### ISSUE TITLE
500 error if auth path has a dot

### ISSUE THREAD

**Issue by ajwm** [hashicorp/vault#244]
If I attempt to authenticate an LDAP username that has a dot in it (eg "john.doe") I get a "500 unsupported path" error.

This looks like it's specific to auth ... I get the same error trying to create a userpass entry for user john.doe, but I can happily read/write secrets with a dot in the name.

**Comment by marc-** [comment]
This is still an issue for userpass authentication:
```
vault write auth/userpass/users/test.test password=secret policies=root
Error writing data to auth/userpass/users/test.test: Error making API request.

URL: PUT https://my-vaultserver:8200/v1/auth/userpass/users/test.test
Code: 500. Errors:

* unsupported path
```

**Comment by jefferai** [comment]
GenericNameRegex doesn't allow dots either  :-)

**Comment by marc-** [comment]
@jefferai , exactly: https://github.com/hashicorp/vault/blob/master/builtin/credential/userpass/path_login.go#L14

**Comment by jefferai** [comment]
It's not that GenericNameRegex prevents usage of dots, it's that it doesn't specifically allow usage of dots. Any of the fields that were modified to use it in the past did not allow dots anyways.

In the case of LDAP, the regex was specifically modified to allow dots.

**Comment by jefferai** [comment]
I'm asking around internally to find out if there was a reason that only LDAP was changed earlier rather than modifying it more globally.

**Comment by marc-** [comment]
That's was my point. Thanks for the detailed clarification.

**Comment by jefferai** [comment]
@marc- We discussed internally and didn't see an issue with enabling a `.` in the path in more places, so I've made that change.

**Comment by marc-** [comment]
Thanks a lot.

**Comment by jefferai** [comment]
No problem!
