### ISSUE TITLE
Unable to call init API: [INFO] core: security barrier not initialized

### ISSUE THREAD

**Issue by weisinc** [hashicorp/vault#2440]
I am trying to set up Vault with consul as the backend in a k8s environment.
My config.json has the following:

backend "consul" {
  address = "consul-svc:8500"
  advertise_addr = "http://%%VAULT_IP%%:%%VAULT_HTTP_PORT%%"
  scheme = "http"
  path = "vault"
}
listener "tcp" {
  address = "0.0.0.0:%%VAULT_HTTP_PORT%%"
  tls_disable = 1
}

On the host, when I tried to curl http://localhost:8200/v1/sys/init  it came back
{"initialized":false}
and on the vault server:
[INFO ] core: security barrier not initialized

I spend many hours searching, trying different things to no progress. Appreciate it if someone can tell me what i am missing or where is the right place to look.

Thanks much.

**Comment by briankassouf** [comment]
This seems to be working as intended. The first thing you need to do once you setup vault is to initialize it. For more info see: https://www.vaultproject.io/intro/getting-started/deploy.html#initializing-the-vault

**Comment by jefferai** [comment]
@weisinc Note that `curl` defaults to GET, but to initialize Vault you need to be supplying parameters with a POST call. See https://www.vaultproject.io/docs/http/sys-init.html
