### ISSUE TITLE
sys/leader returns leader which is not active

### ISSUE THREAD

**Issue by timp87** [hashicorp/vault#2444]
I'm using vault with syslog as audit backend.
I have a couple of vault servers in a failover cluster with Consul as HA and Storage backend.

The documentation says if vault can't write to audit backend (syslog) it refuses to work.
Well, actually it refuses to become an active if unsealed. What is bad you can't understand using API that vault has problems exactly with audit backend.
Also sys/leader tells you a leader which will return you 'no active Vault instance found' if you ask it for a secret or any other data.

How to reproduce (I use CentOS 7.2 x64):
1. Setup two vault servers (Host1 and Host2) with Consul as HA and storage backend.
2. Enable syslog as audit backend.
`# vault audit-enable syslog tag="vault-audit" facility="LOCAL0"`
3. Shutdown syslog on **standby** server (Host2) and make sure there is no /dev/log socket:
`# systemctl stop rsyslog`
`# ls /dev/log`
4. Shutdown **active** vault server (Host1):
`# systemctl stop vault`
5. Standby vault server (Host2) should become a leader. Ask who is leader:
```
# curl --http1.1  -v -s 'https://Host2:8200/v1/sys/leader'
...
HTTP/1.1 200 OK
...
{"ha_enabled":true,"is_self":false,"leader_address":"https://Host2:8200"}
...
```
Ok, good, it returned Host2 as active.
But note, is_self is false. That's weird!
6. Ask the leader (Host2) for a secret:
```
# curl --http1.1  -v -s -H 'X-Vault-Token: $my-root-token' 'https://Host2:8200/v1/secret/test'
...
HTTP/1.1 503 Service Unavailable
...
{"errors":["no active Vault instance found"]}
...
```
Oops, are you a leader?

Once again the problems are:
1. sys/leader is wrong.
2. No way to understand standby server can't became an active.
3. No way to understand standby (pseudo active) server has problems what exactly with.

**Comment by timp87** [comment]
I believe it's a general problem with audit backend, i. e. this can be reproduced not only with syslog, but also if file or socket are configured as audit backend.

**Comment by timp87** [comment]
Behavior changed a bit in Vault 0.7.0:

1. sys/leader sometimes returns an empty _leader_address_
```
{"ha_enabled":true,"is_self":false,"leader_address":""}
```

2. If trying to read a secret it can return _307 Temporary Redirect_ without any data, or _500 Internal Server Error_ with data like
```
{"errors":["node not active but active node not found"]}
```

**Comment by jefferai** [comment]
What you're describing isn't really a problem, but since you're not looking at your logs you're not seeing what's happening. What's happening is that the active node is bouncing around because in each case it takes leadership, tries to set up, can't set up, then gives up leadership. Then it bounces to the next node. That's why you're seeing the value change around.

**Comment by timp87** [comment]
@jefferai, I understand I can look into logs.
But it seems me incorrect if application tells me it can became a leader, but actually can't.

**Comment by jefferai** [comment]
@timp87 it can't reasonably know if it's going to hit a post-leadership setup error until it acquires leadership.

**Comment by jefferai** [comment]
Closing as this is not an actionable issue.
