### ISSUE TITLE
make bin not building binary with a functional ui

### ISSUE THREAD

**Issue by alexdawn** [hashicorp/vault#24500]
**Describe the bug**

I'm trying to build from source, but have an issue with the ui. Note I managed to build it but I believe the fact make didn't complete ui build steps or error on failing to do so is a bug?

**To Reproduce**
1. clone the repo
2. checkout the latest release version tag `git checkout v1.15.4`
3. run  `make bin`
4. everything seems to look okay `./bin/vault --version`
5. `./bin/vault server --dev`
6. Navigate to the web ui at `http://127.0.0.1:8200`
7. There is an empty webpage with nothing but a link wit the text `.gitkeep` which links to itself, Exactly the same as described in https://github.com/hashicorp/vault/issues/19266

**Expected behavior**
I'd either expect the ui to have been built or `make bin` to have thrown a warning.

**Environment:**
* Vault Server Version (retrieve with `vault status`): `Error checking seal status: Get "https://127.0.0.1:8200/v1/sys/seal-status": http: server gave HTTP response to HTTPS client`
* Vault CLI Version (retrieve with `vault version`): `Vault v1.15.4 ('9b61934559ba31150860e618cf18e816cbddc630+CHANGES'), built 2023-12-04T17:45:28Z`
* Server Operating System/Architecture: 
```
Operating System: Ubuntu 22.04.3 LTS                     
Kernel: Linux 6.2.0-37-generic
Architecture: x86-64
```

Vault server configuration file(s): n/a

**Workaround**

Was able to complete the build by building the `./ui` manually without using make:
1. Followed the build steps as described here https://github.com/archlinux/svntogit-community/commit/fe17fc6a6a81e1d3adb7b5889f4ee3db3a3c0efa
```yarn install --ignore-optional
  npm rebuild node-sass
  yarn --verbose run build
```
2. Continue from step 3. in the reproduction

**Comment by marcboudreau** [comment]
Hi @alexdawn,

You can build the UI into the Vault binary with the following command: `make static-dist bin`.

**Comment by marcboudreau** [comment]
I will close this issue. Please feel free to open another issue if the provided workaround is inadequate.
