### ISSUE TITLE
Identifying TLS certificate on PKI mount

### ISSUE THREAD

**Issue by masterkorp** [hashicorp/vault#2450]
Hello, 

I want to manually revoke a certificate but I am having trouble identifying which certificate do I want to revoke. 

I can get the serials with ``vault list pki/certs``, but that does not display common name information. since we do not store the certificate output ourselves, I do not know which certificate I shall revoke.

Is this an intended feature of Vault, or am I missing anything?

**Comment by jefferai** [comment]
Vault only stores/indexes/lists certs by serial number. But, you can take each serial number from the list output and run a fetch on it to get back the actual certificate, then check the common name to see if it's the one you want to revoke.

**Comment by masterkorp** [comment]
Thanks for the quick reply! Can you show me what is the request I need to make? 
Having trouble finding it on the [API documentation](https://www.vaultproject.io/docs/secrets/pki/index.html)

**Comment by jefferai** [comment]
Yep! Look at `pki/cert` -- when doing a GET you pass in a serial number which is what the list output gives you.

**Comment by jefferai** [comment]
Let me know if this doesn't work for you!

**Comment by masterkorp** [comment]
Thank you, I missed it closing this issue.
