### ISSUE TITLE
Enhancement for KV Engine UI Behavior

### ISSUE THREAD

**Issue by cfreeman29** [hashicorp/vault#24504]
### **Problem Description**
Our current challenge arises from a functionality change in the KV engine. The system detects nested JSON by checking for "{}" in KV values. However, our randomly generated values occasionally include these characters, leading to unintended behavior. The UI currently reveals more secrets on the screen than necessary, posing a security risk. We aim to maintain the default UI state of "hidden/unhidden" to minimize this exposure.

### **Proposed Solution**
We suggest two potential solutions:
1. Introduce a UI setting in the KV engine configuration to control the default view state.
2. Temporarily revert to the previous UI behavior, allowing the radio button for "hidden/unhidden" state to be toggleable and not permanently greyed out.

### **Alternative Considered**
We could update our value generation process to avoid "{}" sequences, but this would require significant code modifications. As of version 1.15.4, this issue remains unresolved.

### **Additional Use-Cases**
This change is crucial for enhancing security. The current UI behavior poses a risk in scenarios where screen contents might be observed by others, such as during team demonstrations or walkthroughs. The "hide/unhide" feature in the KV engine is vital for maintaining confidentiality.

### **Context and References**
Relevant Commit: [f42d50826fb0129bc54903532192e1e96a352b8b](https://github.com/hashicorp/vault/commit/f42d50826fb0129bc54903532192e1e96a352b8b)

I'm available to assist with a Pull Request, though the original feature developer might be best suited for this task.

**Comment by hashishaw** [comment]
Hey @cfreeman29, sorry for the trouble I introduced 🙈 Working on a PR now, thanks for the report

**Comment by marcboudreau** [comment]
This issue was fixed by https://github.com/hashicorp/vault/pull/24513

**Comment by marcboudreau** [comment]
This issue was resolved by https://github.com/hashicorp/vault/pull/24513
