### ISSUE TITLE
Corrupt Token Lease Cleanup

### ISSUE THREAD

**Issue by kareed44** [hashicorp/vault#2458]
Vault Server v0.6.1
DynamoDB Backend
Generic Secret Backend

We are having the same problem discussed in a few other issues ([1790](https://github.com/hashicorp/vault/issues/1790), [2144](https://github.com/hashicorp/vault/issues/2144)) where token revoking is failing due to: **"[ERR] expire: failed to revoke lease lease_id=auth/token/create/<some id> error=failed to revoke token: cannot revoke blank token"**.

We are seeing hundreds of thousands of these messages in the log within an hour. The lease ids come from a few different paths: **/cert/login/**, **/token/create/**, and **/token/create/agent**

The solution described in 1790 detailed the deletion of the underlying data in the backend, but I dont feel entirely comfortable doing this without a better understanding of 3 things:
1. How is it getting into this state?
2. What do the following entries in the backend represent? sys/expire/id/<lease id>, sys/token/id, and sys/token/parent/<some other id>
3. Are there other workarounds for this problem?

Thanks!

**Comment by jefferai** [comment]
Please see the release notes for Vault 0.6.4.

**Comment by kareed44** [comment]
Thanks for the really quick response. Am I correct to assume you are referencing "auth/token/tidy"? Is this not just for limited use tokens because we don't use those explicitly?

In addition, using this feature would require upgrading through 3 versions. We will upgrade if we must, but I'd prefer to fix the problem and upgrade later at our leisure.

Again, thank you for the quick response.

**Comment by jefferai** [comment]
@kareed44 I believe that the `tidy` endpoint will solve your problem; limited use tokens show up in places you may not be realizing, e.g. wrapping tokens.

**Comment by kareed44** [comment]
We have upgraded to 0.6.4 and used the tidy endpoint. While it did clean up a few hundred records from the DynamoDB backend it did not cull the orphaned leases. I had to do that manually by searching for any records with a Key attribute equal to the lease ID and removing them.

**Comment by juliangamble** [comment]
I'm seeing this issue as well.

**Comment by jefferai** [comment]
Reopening to track eventually adding more things to the tidy operation.

**Comment by horsehay** [comment]
@jefferai What does this mean by blank token? I am trying to also tidy up my data due to this error message in the logs, but I'm not sure how the /sys/expire/id/ records are orphaned when I can find a corresponding /sys/token/id/ in the data.

**Comment by jefferai** [comment]
@horsehay Keep watch on https://github.com/hashicorp/vault/pull/2452 -- we're adding some bits in there to do cleanup on leases. (The final path will likely change, but if you want, you can try running those code before it's finally merged.)

**Comment by juliangamble** [comment]
Hi Jeff, 
Thanks for being so helpful. 

On startup I'm seeing approx 24000 messages saying:
2017/05/13 07:10:31.653420 [ERROR] expire: failed to revoke lease: lease_id=auth/app-id/login/6488f9f0bb248c4d8cd0fe8dcf0f2f1900e036a4 error=failed to revoke token: cannot revoke blank token

This is after upgrading to vault 0.7.2 and running the two vault tidy operations. 

As discussed I have a large number of nodes like this:

curl http://0.0.0.0:8500/v1/kv/vault/sys/expire/id/auth/app-id/login/?recurse |  jq '. | length'
6381
curl http://localhost:8500/v1/kv/vault/sys/token/id/?recurse |  jq '. | length'
6234
curl http://localhost:8500/v1/kv/vault/sys/token/accessor?recurse |  jq '. | length'
6324



Cheers
Julian

**Comment by michelvocks** [comment]
Hi all!

Since v0.6.1 we did a lot of changes to Vault's leasing system. I will close this issue for now and recommend to open a new issue if you still have problems with dangling leases after an upgrade to the newest version.

Cheers,
Michel
