### ISSUE TITLE
go mod: broken dependencies

### ISSUE THREAD

**Issue by awatterson22** [hashicorp/vault#24592]
**Describe the bug**
- The dependencies have broken versioning:
```
└─ $ go get github.com/hashicorp/vault/vault@latest
go: github.com/hashicorp/vault/vault imports
        github.com/hashicorp/vault/sdk/helper/pluginutil imports
        github.com/hashicorp/go-secure-stdlib/plugincontainer/config: cannot find module providing package github.com/hashicorp/go-secure-stdlib/plugincontainer/config
go: warning: github.com/hashicorp/go-msgpack@v1.1.5: retracted by module author: v1.1.5 merged upstream ugorji/go which breaks compatibility with previous versions.
go: to switch to the latest unretracted version, run:
        go get github.com/hashicorp/go-msgpack@latest
```

**To Reproduce**
1. Run `go get github.com/hashicorp/vault/vault@latest`
2. See error

**Expected behavior**
- Expected modules to be able to be pulled and synced

**Environment:**
```
└─ $ go version
go version go1.21.5 darwin/arm64
```

**Comment by marcboudreau** [comment]
I was able to reproduce the above error when I ran the `go get github.com/hashicorp/vault/vault@latest` from the **api** directory of the repo.

**Comment by marcboudreau** [comment]
Hi @awatterson22, importing packages from the vault repository is not supported. The repository does include two libraries that can be imported: **api** and **sdk**. Please refer to https://github.com/hashicorp/vault#importing-vault for more details.

**Comment by awatterson22** [comment]
@marcboudreau - is there a way to create a fake vault api client for testing, similar to this? https://blog.thomas.maurice.fr/posts/unit-testing-with-vault/#credits
