### ISSUE TITLE
lease not expiring

### ISSUE THREAD

**Issue by ror6ax** [hashicorp/vault#2463]
Hello there.

I'm creating standard 3600 timed users using AWS and Cassandra backends.

I'm puzzled because they never expire.
Users I've created two weeks ago are still alive and well.

What am I missing?

**Comment by jefferai** [comment]
What version of Vault, what is your configuration, when you say "standard 3600 timed users" how are you setting this?

**Comment by ror6ax** [comment]
0.6.5

Config is as follows:

{"backend": {"zookeeper": {"address":"master.mesos:2181", "redirect_addr":"http://0.0.0.0:6379" }}, "listener": {"tcp": {"address":"0.0.0.0:8200","tls_disable":1}},"disable_mlock":true}

I set users via `vault write aws/roles/deploy policy=@policy.json`, just as in the docuamntation.

vault read aws/creds/deploy gives me access key and secret key that do work. Now, there is lease duration 3600 in the reply. My question is why those credentials do not actually expire?

**Comment by jefferai** [comment]
Are the leases being renewed? If you set the log level to trace and restart, do you see any errors related to revocation after a few minutes? How are you setting Cassandra? (3600 is only the default for certain AWS secret key types, and not the default in Cassandra)

**Comment by ror6ax** [comment]
```
vault write cassandra/roles/magicrole creation_cql="CREATE USER '{{username}}' WITH PASSWORD '{{password}}' NOSUPERUSER;"

vault read cassandra/creds/magicrole
```
All as in the tutorial. Seeing 3600 lease duration in answer. No errors anywhere.

**Comment by ror6ax** [comment]
Quick question - does `vault renew my-lease-id 3600` work if lease has already expired long ago?

**Comment by jefferai** [comment]
No

**Comment by ror6ax** [comment]
So, to prevent it from expiring for good, I have to renew lease while existing is still active?

**Comment by jefferai** [comment]
That's correct.
