### ISSUE TITLE
Feature request: Renew token by its accessor

### ISSUE THREAD

**Issue by ruhkopf** [hashicorp/vault#2464]
I'm proposing a new endpoint `/auth/token/renew-accessor` or similar that allows you to renew a periodic token by its accessor (very similar to `/auth/token/revoke-accessor`). This helps, if another system (e.g. scheduler or CI) is responsible for renewing tokens and you don't want to make them visible to this system.

As Jeff mentioned [on the mailing list](https://groups.google.com/forum/#!topic/vault-tool/UIjC4jr5jZE), this adds a potential attack vector. Access to this functionality should therefore be controlled. I'm suggesting to disable this functionality by default, but allow to enable it via token roles with a special flag such as `renewable-accessor=true`.

**Comment by jefferai** [comment]
Why not just have the application perform the renewals?

**Comment by ruhkopf** [comment]
In our case the application is stateless (AWS Lambda). As of now it's not aware of when the token expires. There's no guarantee that it will be called in time before the token expires, either. That's why I thought an external system (cron, scheduler, ...) could do the job, but ideally without having access to the token itself...

_Offtopic_: Or maybe there is a better solution for using Vault with stateless functions? I saw in the release notes of 0.7.1 that the AWS IAM Authentication can be used with Lambda. Is there some documentation how to use it? Is it feasible for a lambda function to authenticate on each invocation? Or would we again have to persist the token and check for its expiration?

**Comment by jefferai** [comment]
> For example, is it feasible for a lambda function to authenticate on each invocation?

Sure, that's basically the idea. You'd want to set the token TTLs low though to prevent having huge numbers of tokens sitting around well after the lifetime of the Lambda function.

**Comment by ruhkopf** [comment]
Ok, great. We started using the IAM role authentication method. Closing this ticket, because we no longer have a need for this feature at the moment.
