### ISSUE TITLE
PKI: ca_chain not set when intermediate does not have AuthorityKeyId

### ISSUE THREAD

**Issue by bhiggins** [hashicorp/vault#2465]
I was using /pki/config/ca to set an intermediate CA cert and was surprised that the issuing cert was not returned in ca_chain when signing. After reviewing the code I believe this is because the cert did not have AuthorityKeyId set. Probably the best solution here (and the one we opted for in this case) is to make a new cert with AuthorityKeyId (and SubjectKeyId) set.

Vault could opt to not to accept certs that don't include AuthorityKeyId and SubjectKeyId so that this problem is prevented up front, preventing confusion.

Another solution would be to change GetCAChain such that, if AuthorityKeyId is not set, the cert's RawIssuer and RawSubject are compared, and the issuer included in ca_chain if they're not equal:

	// Include issuing CA in Chain, not including Root Authority
	if (len(b.Certificate.AuthorityKeyId) > 0 &&
		!bytes.Equal(b.Certificate.AuthorityKeyId, b.Certificate.SubjectKeyId)) ||
	   (len(b.Certificate.AuthorityKeyId) == 0 &&
		!bytes.Equal(b.Certificate.RawIssuer, b.Certificate.RawSubject)) {

**Comment by jefferai** [comment]
Sounds sane. Don't suppose you'd send a PR?
