### ISSUE TITLE
indirect dependency github.com/mitchellh/osext has been deleted

### ISSUE THREAD

**Issue by harbinha** [hashicorp/vault#24656]
**Describe the bug**
I cannot upgrade to the latest due to indirect dependency being deleted `https://github.com/mitchellh/osext/`. Details here https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc?permalink_comment_id=4802235#gistcomment-4802235 
```
go: downloading github.com/hashicorp/vault v1.15.4
go: github.com/hashicorp/vault@upgrade (v1.15.4) indirectly requires github.com/mitchellh/osext@v0.0.0-20151018003038-5e2d6d41470f: github.com/mitchellh/osext@v0.0.0-20151018003038-5e2d6d41470f: invalid version: git ls-remote -q origin in /Users/hharbin/go/pkg/mod/cache/vcs/...: exit status 128:
        remote: Repository not found.
        fatal: repository 'https://github.com/mitchellh/osext/' not found
```

**To Reproduce**
1. Run `go get -u github.com/hashicorp/vault`
2. See error

**Expected behavior**
No error

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture: macOS Ventura 13.5.1

**Comment by VioletHynes** [comment]
Hey there! I'm going to close this one. We don't support using `github.com/hashicorp/vault` as a dependency, so this isn't something that it makes sense to investigate and fix. I'd recommend moving away from using vault directly as a dependency, if possible. 

Please also see this section of the readme: https://github.com/hashicorp/vault?tab=readme-ov-file#importing-vault
