### ISSUE TITLE
Compile error when outside of git: `stubmaker: fatal error: error="repository does not exist"`

### ISSUE THREAD

**Issue by DrDaveD** [hashicorp/vault#24677]
**Describe the bug**
When compiling a vault 1.15.x version from a source tarball instead of from within a git repository, during the `make dev` step errors like the following occur:
```
==> Checking that build is using go version >= 1.21.4...
==> Using go version 1.21.4...
2024-01-04T17:30:28.430-0600 [ERROR] stubmaker: fatal error: error="repository does not exist"
exit status 1
command/server/config_stubs_oss.go:5: running "go": exit status 1
2024-01-04T17:30:33.415-0600 [ERROR] stubmaker: fatal error: error="repository does not exist"
exit status 1
http/handler_stubs_oss.go:12: running "go": exit status 1
2024-01-04T17:30:39.022-0600 [ERROR] stubmaker: fatal error: error="repository does not exist"
exit status 1
vault/seal_stubs_oss.go:11: running "go": exit status 1
make: *** [prep] Error 1
```
**To Reproduce**
1. Get and unpack vault source with `curl -sSL https://codeload.github.com/hashicorp/vault/tar.gz/v1.15.4 | tar xzf -`
2. Assuming a sufficiently new version of go is in your PATH, follow the instructions for compiling in [README.md](https://github.com/hashicorp/vault/README.md):
```
$ cd vault-1.15.4
$ make bootstrap
$ make dev
```
3. See error

**Expected behavior**
I expect to be able to compile outside of git.  That worked in previous releases, at least 1.13.  I didn't try 1.14.

**Environment:**
* Server Operating System/Architecture: CentOS7/x86_64

**Comment by ruspaul013** [comment]
I have the same problem as @DrDaveD, last version that worked for me was 1.14.3

**Comment by ruspaul013** [comment]
Any news about this?
