### ISSUE TITLE
Documentation suggests a local port for a server-to-server comms

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/vault#2468]
This page:

https://www.vaultproject.io/docs/config/

says:

```
cluster_address (optional) - The address to bind to for cluster server-to-server requests. This defaults to one port higher than the value of address, so with the default value of address, this would be "127.0.0.1:8201".
```

What is the point of having a server-to-server port bound to 127.0.0.1:8201 which is unreachable from another server? This makes no sense? (or have I missed something)

**Comment by vishalnayak** [comment]
@gtmtech `cluster_address` is made reachable to other servers via `cluster_addr`. It is required for "Request Forwarding". Refer https://www.vaultproject.io/docs/concepts/ha.html for details.

**Comment by gtmtech** [comment]
@vishalnayak  - this is true and not true. 

cluster_addr is the public address which is advertised to nodes so that intra-node communication can happen. Other nodes use the value of cluster_addr to try and talk to another node.

cluster_address governs how a particular node binds to the network stack. If its set to 127.0.0.1:8201 (as the docs suggest is the default), then no other node will be able to talk to it. It seems crazy to have this as a default - basically, the defaults just dont work in a cluster(!)

To get it to work, you have to set:

cluster_address = "0.0.0.0:8201"   or   "<public-ip-address>:8201"     but definitely not "127.0.0.1:8201"

**Comment by vishalnayak** [comment]
@gtmtech Note that the doc only mentions about defaulting the port number 1 higher than the port number on `address`. The `127.0.0.1` is coming in as a value implied from the `address` parameter. `cluster_address` does not have a default IP of its own.
