### ISSUE TITLE
Missing log: Reused single use tokens not logged?

### ISSUE THREAD

**Issue by magoo** [hashicorp/vault#2472]
Hi - 

Was trying to see what log forensics would look like when single use tokens from `-wrap-ttl` are used multiple times (which would imply an attack or a bug). My goal was to suggest an alert on this behavior via splunk or otherwise.

I noticed that multiple unwraps attempts don't create a log entry, which seems like a high value log to have. In that gif, the lower window is a running `tail -f audit.log | jq` on an audit log.

Environment info below. This is a dev environment and I may have some incorrect assumptions here. I'm new to using vault and am approaching this as a security response person, so I care mostly about the forensic value of logs.

```
vault audit-list
Path   Type  Description  Options
file/  file               file_path=audit.log

Linux ip-10-0-181-161 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Vault v0.6.5 ('5d8d702f33b5fd965cbe8d6d0728295de813a196')
```

**Comment by jefferai** [comment]
Vault's audit logs only log requests with valid tokens. One of the reasons for doing this is that logging improperly authenticated requests can be a DoS vector, by rapidly filling hard drives or network I/O.
