### ISSUE TITLE
UI editor stuck in json mode when a string contains a brackets

### ISSUE THREAD

**Issue by MrWazaby** [hashicorp/vault#24724]
**Describe the bug**
When you create a secret with a `{` inside it the UI is blocked in json mode. It wasn't the case previously. 

**To Reproduce**
1. Open the web UI
2. Create a secret with a { in it (eg. `"test": "test{"`)
3. The editor is now stuck in json 

**Expected behavior**
The web UI should be able to edit a secret with a { in it. 

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.15.4

**Additional context**
I think the source of this regression is here: https://github.com/hashicorp/vault/pull/24308/files#diff-2a7dbc4c7b51c6a2de3641f47e1598b8c2c7aaf59d442db2afbb5f4c36f54ba9R43

**Comment by tkuehne-deliveryhero** [comment]
Hi @MrWazaby,

I just saw this already [closed issue](https://github.com/hashicorp/vault/issues/24565#issuecomment-1862947493) - the issue will be fixed in 1.15.5 / 1.16.

**Comment by MrWazaby** [comment]
Indeed, thanks!
