### ISSUE TITLE
Vault should support a separate CA file configuration option

### ISSUE THREAD

**Issue by agy** [hashicorp/vault#2473]
While Vault supports a custom CA to be appended to the provided `tls_cert_file`, it doesn't support a separate CA file to be set.

It's certainly not a deal-breaker, but this is not what I expect given that:
 * Consul has the [`ca_file`](https://www.consul.io/docs/agent/options.html#ca_file) option
 * Nomad has the [`ca_file`](https://www.nomadproject.io/docs/agent/configuration/tls.html#ca_file) option

A separate CA file for Vault will make automated provisioning of multiple Hashicorp productions a little simpler and more consistent. And reading the config file a little more obvious.

Example:
```
# Current config with a CA appended
...
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/path/to/vault.crt"
  tls_key_file = "/path/to/vault.key"
}
...
```
```
# Proposed config
...
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_ca_file = "/path/to/ca.crt"
  tls_cert_file = "/path/to/vault.crt"
  tls_key_file = "/path/to/vault.key"
}
...
```

Feel free to put this on the wishlist.

**Comment by richard-mauri** [comment]
Agree. I noticed this too

**Comment by aphorise** [comment]
Is this not adequately supported already by [way of `vault_cacert`](https://www.vaultproject.io/docs/commands#vault_cacert) and [`vault_capath`](https://www.vaultproject.io/docs/commands#vault_capath) or their CLI equivalent `vault server -ca-cert=…` & `-ca-path=…` respectively?

**Comment by calvn** [comment]
@aphorise thanks for bubbling this up! The [`tls_client_ca_file`](https://www.vaultproject.io/docs/configuration/listener/tcp#tls_client_ca_file) should be the equivalent of Nomad's and Consul's `ca_file` parameter.
