### ISSUE TITLE
Backend "consul" cluster_addr is partly ignored

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/vault#2475]
I've setup a Consul cluster (which seems to be working, I managed to run `vault init` on one node).

But getting my three Vault nodes talking to that simultaneous seems to be more problematic.

My `vault.conf` file:
```
backend "consul" {
  address = "10.0.17.19:8500"
  redirect_addr = "http://10.0.17.19:8500"
  cluster_addr = "http://10.0.17.19:8500"

  scheme = "http"
  path = "vault/"
}

listener "tcp" {
  address = "10.0.17.17:8200"
  cluster_address = "10.0.17.17:8201"

  tls_disable = 1
}
```

The `10.0.17.19` address is one of my Consul servers and `10.0.17.17` is localhost.

When I start Vault on that node, I get:

```
root@admin-vault-17:~# ==> Vault server configuration:

                 Backend: consul (HA available)
                     Cgo: disabled
         Cluster Address: https://10.0.17.19:8500
              Listener 1: tcp (addr: "10.0.17.17:8200", cluster address: "10.0.17.17:8200", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
        Redirect Address: http://10.0.17.19:8500
                 Version: Vault v0.6.5
             Version Sha: 5d8d702f33b5fd965cbe8d6d0728295de813a196

==> Vault server started! Log data will stream in below:
```

Here, it replaced `http://` in the `cluster_addr` with `https://`! Yes, I know I should use `https` in the first place, but I'm kind'a in a hurry to get a mockup tested, so I don't want to involve SSL/TLS just yet.

No matter how I seem to configure my three Vault servers, only one seems to be responding to queries at any one time.

**Comment by vishalnayak** [comment]
@FransUrbo `redirect_addr` should be pointing to port `8200` and `cluster_addr` should be pointing to port `8201`.

**Comment by FransUrbo** [comment]
I couldn't see anything about Consul listening on 82xx ports.

My consul config:
```
{
    "datacenter": "europe-london",
    "data_dir": "/var/lib/consul",
    "ui_dir": "/var/lib/consul/ui",
    "log_level": "INFO",
    "node_name": "<%= @hostname -%>",
    "domain": "consul",
    "client_addr": "0.0.0.0",
    "ports": {
        "server": 8300,
        "serf_lan": 8301,
        "serf_wan": 8302,
        "rpc": 8400,
        "http": 8500,
        "dns": 8600
    }
}
```

**Comment by vishalnayak** [comment]
@FransUrbo The ports of `redirect_addr` and `cluster_addr` are not the ones Consul will be listening on. `8200` will be the port on which Vault will be listening to process the requests and `8201` is the port on which different nodes in a Vault cluster will interact with each other for request forwarding. See https://www.vaultproject.io/docs/concepts/ha.html for more details.

**Comment by FransUrbo** [comment]
Ah, ok! Now I get it! I've read that page several times now, and still didn't get it.

Putting *localhost* in the "backend" didn't seem to be the correct way, which is why I probably misunderstood what's documented.

Now it's working, although it's still using `https://` for the cluster address (even though I've specifically said `http://` AND disable tls.).

**Comment by vishalnayak** [comment]
@FransUrbo Communication between the cluster nodes always happens over TLS. Vault creates the certificate and the key required for this purpose, which gets advertised by the active node.

**Comment by FransUrbo** [comment]
Then `cluster_addr` shouldn't be an URL (and enforced as such), but an `IP:PORT` configuration.

**Comment by vishalnayak** [comment]
`tls_disabl` is applicable for the listener that processing regular requests, not for the cluster listeners.

**Comment by FransUrbo** [comment]
What I'm saying is, that currently `cluster_addr` is a URL/URI (which is enforced), but if Vault is ignoring the protocol anyway, it should be a `IP:PORT` value instead.

**Comment by vishalnayak** [comment]
@FransUrbo Don't know. It could be I guess, not sure, maybe it is what it is for BC reasons. But its not so bad at all, considering that its documented and it goes well in terms of consistency with `redirect_addr` thereby avoiding confusion.

I can see `Note that this will always be forced to https since only TLS connections are used between servers.` in the docs.

**Comment by FransUrbo** [comment]
> Note that this will always be forced to https since only TLS connections are used between servers. in the docs.

Yes, I saw that as well, but what it DOESN’T say is that you MUST have a scheme in there!

Which doesn’t make any sense if Vault ignores it and puts “https” there instead.

**Comment by jefferai** [comment]
There are actually two different addresses.

`cluster_address` in the `listener` section controls which IP and port Vault binds to for clustering; it is the cluster equivalent of `address` in the `listener` section.

`cluster_addr` in the `backend` (or `ha_backend`) section controls the address advertised to other nodes for clustering; this is the clustering equivalent of `redirect_addr`. This can be used to work around custom request paths (e.g. if the actual bind is on a private address so you need to give the address of a TCP-based load balancer to other nodes). This is a full address, but Vault does enforce HTTPS.

**Comment by FransUrbo** [comment]
Yes, I noticed that as well after a few hours :). That should probably also be clarified.

Could we reopen this, but tag it as `documentation`?

**Comment by jefferai** [comment]
Hi @FransUrbo , I just went through and clarified it in our docs. They'll be redeployed in a few days.
