### ISSUE TITLE
Make vault releases available via GitHub API

### ISSUE THREAD

**Issue by gchy** [hashicorp/vault#2476]
Currently Vault releases are available as (unverified) tags, but not as actual GitHub-level releases. In particular this means that the GitHub API call for a list of releases is always empty:

```
$ curl https://api.github.com/repos/hashicorp/vault/releases
[

]
```

This makes it very difficult to track Vault releases in CI systems such as Concourse.

Please consider making releases available via the GitHub API. A related discussion of the concept can be found here: https://github.com/bcit-ci/CodeIgniter/issues/3421

Thank you.

**Comment by jefferai** [comment]
HashiCorp does not use GitHub for releases, sorry.
