### ISSUE TITLE
PKI: vault cli does not handle json correctly

### ISSUE THREAD

**Issue by willbengtson** [hashicorp/vault#2479]
vault version
Vault v0.6.5 ('5d8d702f33b5fd965cbe8d6d0728295de813a196')

vault read pki/ca
Error reading pki/ca: json: cannot unmarshal number into Go value of type api.Secret

**Comment by vishalnayak** [comment]
@willbengtson It's one those endpoints that returns a *raw* response which isn't JSON encoded. See the API documentation for the endpoint here: https://www.vaultproject.io/docs/secrets/pki/index.html. `pki/ca` returns a raw DER encoded certificate. `pki/ca/pem` returns a raw PEM encoded certificate.

**Comment by willbengtson** [comment]
Thanks! I couldn't remember if it did or not.  Much appreciated the quick response
