### ISSUE TITLE
Anonymous ACL policy

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/vault#2482]
Vault 0.6.5

I would like to be able to have a vault anonymous policy. From my reading of the default policy, it seems that this assumes a token already exists(?) 

I would like users for example to be able to run `vault auth -methods` - to see which methods of authentication are available to them as this may change over time - however currently I cant find a way of doing this without the user being logged in first, which kind of defeats the point. 

Is there an anonymous policy at the moment? Is this possible?

**Comment by vishalnayak** [comment]
@gtmtech Sorry, I am not understanding how having another policy would address this. It would be just another policy and users would still need a token with this new policy.

The only way I am able to reason about this ask is that, this is about users being able to query the list of authentication methods *without* a token.

`vault auth -methods` might be a sensitive operation for many and it can't be made unauthenticated. Requiring a token doesn't defeat any point because this operation is largely required for operators who are setting up Vault and not for clients to are consuming its services. Clients being aware beforehand about the authentication method available, usually is sufficient.

**Comment by gtmtech** [comment]
I am not asking for vault auth -methods to be made unauthenticated, I am asking for there to be an anonymous policy, so that operators have the flexibility to set up vault auth -methods (and other operations) to be unauthenticated if they wish to do so.

I am not mandating anything for anybody, I am asking for the flexibility to allow operators to run vault in ways which perhaps the vault authors cannot appreciate but work for them.

**Comment by vishalnayak** [comment]
If you don't want to make it unauthenticated, you could update the `default` policy to allow access to `sys/auth` then. Wouldn't it work for you?

**Comment by jefferai** [comment]
@gtmtech I think the issue here is that `policy` is inextricably tied to tokens in Vault land. So any policy, at all, requires a token.

So either what you want is a non-policy method to declare that certain endpoints should be unauthenticated, or if you really do mean a `policy`, you need to set up a way to get tokens with a well-known set of credentials (say `userpass` with `anon`:`anon`) with a policy that then allows access to these endpoints.

**Comment by gtmtech** [comment]
You're probably right and I should not have attempted to head into implementation land (ie policies) but have phrased it as a typical story. 

As an operator I want the facility to be able to allow unauthenticated access to API endpoints of my choosing in full knowledge of the risks of doing so, so that I can:

* provide discoverability of the API, 
* provide useful vault functionality in cases where in my view authentication is not required.
* provide useful vault functionality in cases where authentication is not possible or meaningless

(Anyway, I can see it's not going to happen, I'll give up)

**Comment by jefferai** [comment]
> (Anyway, I can see it's not going to happen, I'll give up)

What's the genesis of this comment?

**Comment by gtmtech** [comment]
Just that the issue was closed down straight away. I take that as meaning there is no interest in making it happen

**Comment by vishalnayak** [comment]
@gtmtech Closing an issue right away might mean many other things too. Not comprehensive but some of the reasons could be:
- If the ask is fundamentally against the design and goals of the project.
- If the issue reported isn't an issue but a case of users being new and/or not knowing the specifics of how things work, and how things are the way they are.
- If the solution proposed doesn't actually solve the problem or if it creates other issues.
- If its a question or a discussion topic which are meant to be on the mailing list.
etc.

We do discuss before closing issues. It goes case-by-case though and its difficult to be consistent in this. We also tend to keep the issue count down to keep it manageable. Closing issues early also avoids dangling open issues with unfinished conversations. If we fail to notice any detail or the message being communicated by the submitter, an issue can always be reopened!

Please feel free to comment on closed issues if you happen to disagree and we shall discuss.

**Comment by jefferai** [comment]
@gmtech  The issue was closed because the ask could not be satisfied; there cannot be an anonymous policy that works the way you describe.

I think it's fine to ask for the methods call to be unauthenticated; we'd have to discuss internally but there are certainly pros. At this point I suggest opening a new issue with that request so we can track that result rather than have to read way down in this issue for context.

**Comment by gtmtech** [comment]
Cool thanks for clarifying.

**Comment by sgleske-ias** [comment]
A workaround for this could be using approle and abusing the CIDR `0.0.0.0/32` to allow all IP addresses to anonymously obtain a restricted vault token.

# Use case

Can't really think of one honestly... maybe allowing an anonymous user to unwrap a secured value... however, this can still be abused so probably not a good idea.  I **strongly caution** against this anonymous usage.

# anonymous policy

    vault policy write anonymous anonymous.hcl

<details><summary>anonymous.hcl (click to expand)</summary>

---

Started from `default` policy and removed things that I thought wouldn't make sense for an anonymous user.

```hcl
# This is a policy designed to only be associated with an anonymous user
# app-role.

# Allow tokens to look up their own properties
path "auth/token/lookup-self" {
    capabilities = ["read"]
}

# Allow tokens to renew themselves
path "auth/token/renew-self" {
    capabilities = ["update"]
}

# Allow tokens to revoke themselves
path "auth/token/revoke-self" {
    capabilities = ["update"]
}

# Allow a token to wrap arbitrary values in a response-wrapping token
path "sys/wrapping/wrap" {
    capabilities = ["update"]
}

# Allow a token to look up the creation time and TTL of a given
# response-wrapping token
path "sys/wrapping/lookup" {
    capabilities = ["update"]
}

# Allow a token to unwrap a response-wrapping token. This is a convenience to
# avoid client token swapping since this is also part of the response wrapping
# policy.
path "sys/wrapping/unwrap" {
    capabilities = ["update"]
}

# Allow general purpose tools
path "sys/tools/hash" {
    capabilities = ["update"]
}
path "sys/tools/hash/*" {
    capabilities = ["update"]
}
```

</details>

---

# Enable approle for anonymous users

Enable approle

    vault auth enable approle

Enable anonymous users to authenticate using the `role_id` anonymous.  This will grant the `anonymous` Vault policy to tokens granted to these anonymous users.

# Log in as anonymous

Go to any machine with a vault client and connectivity access to vault.  Run the following command to get a token.

    vault write auth/approle/login role_id=anonymous

**Comment by samrocketman** [comment]
A workaround for this could be using approle and abusing the CIDR `0.0.0.0/32` to allow all IP addresses to anonymously obtain a restricted vault token.

# Use case

Can't really think of one honestly... maybe allowing an anonymous user to unwrap a secured value... however, this can still be abused so probably not a good idea.  I **strongly caution** against this anonymous usage.

# anonymous policy

    vault policy write anonymous anonymous.hcl

<details><summary>anonymous.hcl (click to expand)</summary>

---

Started from `default` policy and removed things that I thought wouldn't make sense for an anonymous user.

```hcl
# This is a policy designed to only be associated with an anonymous user
# app-role.

# Allow tokens to look up their own properties
path "auth/token/lookup-self" {
    capabilities = ["read"]
}

# Allow tokens to renew themselves
path "auth/token/renew-self" {
    capabilities = ["update"]
}

# Allow tokens to revoke themselves
path "auth/token/revoke-self" {
    capabilities = ["update"]
}

# Allow a token to wrap arbitrary values in a response-wrapping token
path "sys/wrapping/wrap" {
    capabilities = ["update"]
}

# Allow a token to look up the creation time and TTL of a given
# response-wrapping token
path "sys/wrapping/lookup" {
    capabilities = ["update"]
}

# Allow a token to unwrap a response-wrapping token. This is a convenience to
# avoid client token swapping since this is also part of the response wrapping
# policy.
path "sys/wrapping/unwrap" {
    capabilities = ["update"]
}

# Allow general purpose tools
path "sys/tools/hash" {
    capabilities = ["update"]
}
path "sys/tools/hash/*" {
    capabilities = ["update"]
}
```

</details>

---

# Enable approle for anonymous users

Enable approle

    vault auth enable approle

Enable anonymous users to authenticate using the `role_id` anonymous.  This will grant the `anonymous` Vault policy to tokens granted to these anonymous users.

```bash
vault write auth/approle/role/anonymous \
    role_id=anonymous \
    bind_secret_id=false \
    token_bound_cidrs=0.0.0.0/32 \
    token_no_default_policy=true \
    token_policies=anonymous
```

# Log in as anonymous

Go to any machine with a vault client and connectivity access to vault.  Run the following command to get a token.

    vault write auth/approle/login role_id=anonymous

Login with scripting...

```bash
approle_login() {
    vault write auth/approle/login role_id=anonymous | \
    awk '$1 == "token" { print $2; exit }'
}

VAULT_TOKEN="`approle_login`"
export VAULT_TOKEN
vault token lookup
vault token revoke -self
```

**Comment by epopisces** [comment]
Thanks @samrocketman, your suggestion ended up being quite helpful for our use case!

## Use case - Reading Certificate Chain when using the PKI Secrets Engine 

If using the 'pki' secrets engine with Vault acting as a Issuing Certificate Authority, ephemeral VMs (scale sets) and containers need to trust certificates signed by our internal certificate authority.  Though generally including the cert chain in the image's trust store is preferred, this offered an alternative means of using a cloudinit or similar mechanism to retrieve the chain.  So our 'anonymous' policy looks like:

```
path "pki/ca_chain" {
    capabilities = ["read"]
}
```

**Comment by candlerb** [comment]
The requested use case of being able to see available auth methods is also handled by `vault auth tune`, e.g.

```
vault auth tune -listing-visibility=unauth userpass/
```

They can then be seen using

```
vault read sys/internal/ui/mounts
```

or

```
curl https://..../v1/sys/internal/ui/mounts
```

This is an "internal" API for the web UI, so technically is not guaranteed to remain stable over time.  But if people are logging in via the web UI, this *does* make these methods available there.

**Comment by samrocketman** [comment]
@epopisces that is a good use case of anonymous policy.  Thanks for sharing.

**Comment by The-Judge** [comment]
I tried @samrocketman 's solution, but unfortunately, I don't succeed.

First, I enabled the `approle` auth method:
```
❯ vault auth enable approle
Success! Enabled approle auth method at: approle/
```

Next, I created a policy called `anonymous_access_to_sops_encrypt`:
```
# See https://github.com/hashicorp/vault/issues/2482#issuecomment-633748925

# This is a policy designed to only be associated with an anonymous user
# app-role.

# Allow tokens to look up their own properties
path "auth/token/lookup-self" {
    capabilities = ["read"]
}

# Allow tokens to renew themselves
path "auth/token/renew-self" {
    capabilities = ["update"]
}

# Allow tokens to revoke themselves
path "auth/token/revoke-self" {
    capabilities = ["update"]
}

# Allow a token to unwrap a response-wrapping token. This is a convenience to
# avoid client token swapping since this is also part of the response wrapping
# policy.
path "sys/wrapping/unwrap" {
    capabilities = ["update"]
}

# Allow general purpose tools
path "sys/tools/hash" {
    capabilities = ["update"]
}
path "sys/tools/hash/*" {
    capabilities = ["update"]
}

# Grant Read Access to "sops/encrypt"
path "sops/encrypt/*" {
    capabilities = ["read"]
}
```

Finally, I created the `anonymous` approle:
```
❯ vault write auth/approle/role/anonymous \
    role_id=anonymous \
    bind_secret_id=false \
    token_bound_cidrs=0.0.0.0/32 \
    token_no_default_policy=true \
    token_policies=anonymous_access_to_sops_encrypt
Success! Data written to: auth/approle/role/anonymous
```

Unfortunately, this is the result:
```
❯ vault write auth/approle/login role_id=anonymous
Key                     Value
---                     -----
token                   hvs.CAESIIClI2TD...
token_accessor          hHI4ZGd89...
token_duration          768h
token_renewable         true
token_policies          ["anonymous_access_to_sops_encrypt"]
identity_policies       []
policies                ["anonymous_access_to_sops_encrypt"]
token_meta_role_name    anonymous
❯ export VAULT_TOKEN="hvs.CAESIIClI2TD..."
❯ vault token lookup
Error looking up token: Error making API request.

URL: GET https://my-vault:8200/v1/auth/token/lookup-self
Code: 403. Errors:

* permission denied
```

What am I missing?

**Comment by fredt34** [comment]
@The-Judge : I had the same issue, then realized that `token_bound_cidrs=0.0.0.0/32` is a _very_ restricted address... `token_bound_cidrs=0.0.0.0/0` is muuuuch more larger, and did the trick for me - now I can read my secret both with the client and curl.

**Comment by samrocketman** [comment]
There was a time /32 worked because it still means all IPs.  But I guess vault changed something so maybe it no longer works?  Either way good workaround thanks for listing.  I haven’t verified it since I operate an older version currently.
