### ISSUE TITLE
Unseal operation unseals vault even though the provided master key was altered from the original one

### ISSUE THREAD

**Issue by andreivasiletruta** [hashicorp/vault#2484]
I am having vault version": "Vault v0.6.1"
I triggered API to unseal.
I used one key like below and unseal went fine.

> f819b63452e1302d70fa84cb610a8214019de0d1172c8bb12a78**4**29992b5870705

I altered the key and used it again to unseal. the progress turned from 1 to 2 and unseal returned success.

> f819b63452e1302d70fa84cb610a8214019de0d1172c8bb12a78**5**29992b5870705

Expected result: Something similar to 

> {"errors":["failed to compute master key: duplicate part detected"]}

should appear.

**Comment by vishalnayak** [comment]
@andreivasiletruta The error messages would appear *after* the threshold number of key shares are supplied during unseal. It is only when there is an attempt to combine the key shares that the errors like these show up.

**Comment by andreivasiletruta** [comment]
Maybe I am missing something.
When I init vault I get several master keys.

When I unseal vault, I can take one master key - alter it with some of my own numbers and the unseal process says: ok. fine with us. process started.... and this is ok as a behavior?

thank you @vishalnayak

**Comment by vishalnayak** [comment]
@andreivasiletruta The keys you see as output of init are not master keys. They are the shards that combine into the master key through the process of unseal (https://www.vaultproject.io/docs/internals/architecture.html). As you provide pieces required to recreate master key, Vault will have all the unseal key shards in-memory. When the `threshold` number of key shards are supplied, they are all combined together using Shamir's secret sharing algorithm. If the key shards supplied were wrong, it is only during the combining act that we'll know. So yes, process started, is an okay behavior. Hope this helps!

**Comment by andreivasiletruta** [comment]
@vishalnayak thank you again! It is clear. Now I know :).
