### ISSUE TITLE
Mysql physical storage

### ISSUE THREAD

**Issue by infintesoftware** [hashicorp/vault#2485]
I've got a problem with mysql physical storage. When I init vault with vault init I got response:

[INFO ] core: security barrier not initialized

Second call to vault init:
Vault is already initialized

But my unseal keys and root token are not displayed on cli.
Vault v0.6.5

**Comment by jefferai** [comment]
Can you change the log level to trace and then provide the entire log?

**Comment by infintesoftware** [comment]
2017/03/14 13:36:51.926602 [TRACE] physical/cache: creating LRU cache: size=32768
2017/03/14 13:36:51.941626 [TRACE] cluster listener addresses synthesized: cluster_addresses=[127.0.0.1:8201]
2017/03/14 13:37:12.595619 [INFO ] core: security barrier not initialized
2017/03/14 13:37:12.626617 [INFO ] core: security barrier initialized: shares=5 threshold=3
2017/03/14 13:37:12.632619 [ERROR] core: failed to unseal barrier: error=Unseal failed, invalid key

**Comment by jefferai** [comment]
Does this behavior persist in the 0.7 beta?
