### ISSUE TITLE
OIDC Provider does not publish code_challenge_methods_supported in openid metadata

### ISSUE THREAD

**Issue by starcraft66** [hashicorp/vault#24854]
**Describe the bug**
The vault documentation states that PKCE is **required** for public OIDC clients, however, no `code_challenge_methods_supported`s are published in the `.well-known/openid-configuration` which leads client applications to think that PKCE is not supported by vault and causing the login process to fail.

More info here: https://github.com/int128/kubelogin/issues/858

**To Reproduce**
1. Start vault server
2. Navigate to `/v1/identity/oidc/provider/default/.well-known/openid-configuration`
3. See no `code_challenge_methods_supported` present

**Expected behavior**
I expect vault's OpenID metatdata to contain at least `"code_challenge_methods_supported":["plain","S256"]`

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.15.0
* Vault CLI Version (retrieve with `vault version`): 1.14.7
* Server Operating System/Architecture: NixOS 23.11

**Comment by austingebauer** [comment]
Thanks for opening this issue, @starcraft66!
