### ISSUE TITLE
GUI: Resultant ACL check failed error displayed

### ISSUE THREAD

**Issue by ptrovatelli** [hashicorp/vault#24866]
**Describe the bug**
After upgrading from 1.14.0+ent to 1.15.4, when switching namespace in the GUI, getting this error message: 
```
Resultant ACL check failed
You do not have access to resources in this namespace.
Log into <mynamespace> namespace
```

Despite the error message, I seem to have the correct permissions on the `mynamespace` namespace (I can see secrets for example)
I cannot log into the `mynamespace` namespace because my authentication backend is in the root namespace (and provides permissions for all other namespaces)

I was able to fix the error by adding the below permission in the admin policy. 
```
path "+/sys/internal/ui/resultant-acl" {
  capabilities =  [ "read" ]
}
``` 
Not sure it's the best way to go. Should it be added into the default policy? 

**To Reproduce**
1. Create `mynamespace` namespace
2. Create an admin policy in the root namespace giving permission to all namespaces. Eg: 
```
path "+/kv/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "patch", "sudo"]
}
```

3. Create auth backend in the root namespace. 
Terraform: 
```

resource "vault_jwt_auth_backend" "keycloak" {
...
  type               = "oidc"
  default_role       = "default-keycloak"
}


resource "vault_jwt_auth_backend_role" "default_keycloak" {
...
  token_policies = ["default"]
  role_type             = "oidc"
...
}
```

4. Login to vault using keycloak :
- namespace: (Root)
- method: oidc
- Role (Default)

5. Switch to mynamespace namespace

**Expected behavior**
No error message should be displayed

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.15.4+ent
* Vault CLI Version (retrieve with `vault version`): 1.14.0
* Server Operating System/Architecture:

**Additional context**
With the CLI, I can see that I have access to Resultant ACL in the root namespace (the namespace against which I authenticate), : 
```
vault login -method oidc
vault read sys/internal/ui/resultant-acl --format=json | jq -r .data
```

But i cannot see resultant ACL in other namespaces:
```
vault read mynamespace/sys/internal/ui/resultant-acl --format=json | jq -r .data
Error reading mynamespace/sys/internal/ui/resultant-acl: Error making API request.

URL: GET https://xxx/v1/mynamespace/sys/internal/ui/resultant-acl?--format=json
Code: 403. Errors:

* 1 error occurred:
        * permission denied
```

when switching namespace, the below log is generated in vault_audit log file: 
```
{
    "time": "2024-01-15T14:51:11.191976805Z",
    "type": "request",
    "auth":
    {
        "client_token": "xxx",
        "accessor": "xxx",
        "display_name": "xxx",
        "policies": ["default", "vault-admins"],
        "token_policies": ["default"],
        "identity_policies": ["vault-admins"],
        "policy_results":
        {
            "allowed": false
        },
        "metadata":
        {
            "role": "default-keycloak-current"
        },
        "entity_id": "xxx",
        "token_type": "service",
        "token_ttl": xxx,
        "token_issue_time": "2024-01-15T15:50:57+01:00"
    },
    "request":
    {
        "id": "xxx",
        "client_id": "xxx",
        "operation": "read",
        "mount_point": "mynamespace/sys/",
        "mount_type": "ns_system",
        "mount_running_version": "v1.15.4+builtin.vault",
        "mount_class": "secret",
        "client_token": "xxx",
        "client_token_accessor": "xxx",
        "namespace":
        {
            "id": "xxx",
            "path": "mynamespace/"
        },
        "path": "sys/internal/ui/resultant-acl",
        "remote_address": "xxx",
        "remote_port": xxx
    },
    "error": "1 error occurred:\n\t* permission denied\n\n"
}
{
    "time": "2024-01-15T14:51:11.192284707Z",
    "type": "response",
    "auth":
    {
        "client_token": "xxx",
        "accessor": "xxx",
        "display_name": "xxx",
        "policies": ["default", "vault-admins"],
        "token_policies": ["default"],
        "identity_policies": ["vault-admins"],
        "policy_results":
        {
            "allowed": false
        },
        "metadata":
        {
            "role": "default-keycloak-current"
        },
        "entity_id": "xxx",
        "token_type": "service",
        "token_ttl": xxx,
        "token_issue_time": "2024-01-15T15:50:57+01:00"
    },
    "request":
    {
        "id": "xxx",
        "client_id": "xxx",
        "operation": "read",
        "mount_point": "mynamespace/sys/",
        "mount_type": "ns_system",
        "mount_running_version": "v1.15.4+builtin.vault",
        "mount_class": "secret",
        "client_token": "xxx",
        "client_token_accessor": "xxx",
        "namespace":
        {
            "id": "xxx",
            "path": "mynamespace/"
        },
        "path": "sys/internal/ui/resultant-acl",
        "remote_address": "xxx",
        "remote_port": xxx
    },
    "response":
    {
        "mount_point": "mynamespace/sys/",
        "mount_type": "ns_system",
        "mount_running_plugin_version": "v1.15.4+builtin.vault",
        "mount_class": "secret",
        "data":
        {
            "error": "xxx"
        }
    },
    "error": "1 error occurred:\n\t* permission denied\n\n"
}

**Comment by xueshanf** [comment]
According to https://github.com/hashicorp/vault/pull/23503, this should be included in the default policy, but not? I don't see it with **vault policy read default** command.

**Comment by hashishaw** [comment]
Hello, thanks for the report. This issue was fixed in #25766 which got shipped in 1.15.8. Your workaround is correct for versions between 1.15.1 and 1.15.8. 

I've created [this gist](https://gist.github.com/hashishaw/6bdb00f9db2976a77e29516ddec89b5a) to outline the changes that have been made around this experience -- it has evolved a lot thanks to feedback from folks like you 😄 

@xueshanf i see this entry from `vault policy read default` command -- is it possible your default has been modified? 
```
# Allow a token to look up its resultant ACL from all policies. This is useful
# for UIs. It is an internal path because the format may change at any time
# based on how the internal ACL features and capabilities change.
path "sys/internal/ui/resultant-acl" {
    capabilities = ["read"]
}
```

**Comment by Garagoth** [comment]
1.16.2 also should be fixed if I read correctly, and 1.15.8 is enterprise only.
However, since default policy is NOT updated during Vault update, which is stated explicitly in documentation (https://developer.hashicorp.com/vault/docs/concepts/policies#default-policy) it is required to manually obtain new default policy from somewhere and update it, again manually, on target server (that was just updated, or just prior to the update maybe).

So, updating Vault does not fix the issue unless default policy is updated manually as an extra step.

Correct?

**Comment by hashishaw** [comment]
@Garagoth no, after the fix #25766 (which is also in 1.16.2 as you stated) there are no updates needed for the default policy, as the UI was updated to always call the resultant-acl endpoint in the user's relative root namespace, where they should already have the default policy applied.

**Comment by Garagoth** [comment]
I had 1.14.x, no errors. Updated to 1.15.6 and this error appeared.
My default policy did not have anything regarding resultant-acl.

Then I updated to 1.16.3. Error message still appears, and default policy does not have anything regarding resultant-acl.

Documentation states that default policy is never updated by Vault by itself, only created once at cluster bootstrap and never touched again.

**Comment by hashishaw** [comment]
@Garagoth the resultant-acl block in the default policy was [added in 1.10](https://github.com/hashicorp/vault/pull/4386). If you started using Vault at a version earlier than that it is certainly possible that it is now missing. 

The [docs you linked](https://developer.hashicorp.com/vault/docs/concepts/policies#default-policy) encourage updating the default policy to suit your needs, so I would encourage you to update according to that documentation. Or, simply add the following block to the default policy to remove the banner: 

```
# Allow a token to look up its resultant ACL from all policies. This is useful
# for UIs. It is an internal path because the format may change at any time
# based on how the internal ACL features and capabilities change.
path "sys/internal/ui/resultant-acl" {
    capabilities = ["read"]
}
```

Adding the block or updating to the latest default will have the added benefit of allowing the UI to work better, only showing nav links to things that the logged in user has access to.
