### ISSUE TITLE
vault agent high cpu usage

### ISSUE THREAD

**Issue by bovy89** [hashicorp/vault#24900]
HI, we are facing some strange CPUThrottlingHigh alarms on vault agents (k8s).

Vault agent is injected on pod (no CSI) and agent default are set-up quite low:

```
agentDefaults: 
    cpuLimit: "50m"
    cpuRequest: "25m"
    memLimit: "64Mi"
    memRequest: "32Mi"
```

These values has been working fine, but now, after upgrading vault (and vault agent) to 1.15.x randomly appears a CPUThrottlingHigh alarm. Below vault agent metrics

<img width="1583" alt="image" src="https://github.com/hashicorp/vault/assets/697408/611e4e65-7528-4831-a53d-fc7f6d10dc51">

<img width="1770" alt="image" src="https://github.com/hashicorp/vault/assets/697408/a2e7f5d0-9fc3-4312-b479-182e2a8d76b1">

<img width="760" alt="image" src="https://github.com/hashicorp/vault/assets/697408/61f4d2af-5ed7-4472-8f78-1d78dc1cdd0a">

<img width="754" alt="image" src="https://github.com/hashicorp/vault/assets/697408/ccde2737-4bc2-47e0-bb53-7a7404076c78">

A simple pod restart temporary fix it, but it keeps reappearing

**Comment by VioletHynes** [comment]
Hey there! I'd love to understand more about what's going on here. Does anything change in Agent's behaviour when this happens? Do the logs change, or indicate something special is happening?

Off the top of my head, I can't think of anything we added in recent versions that might be a cause of this, so I'd love to understand more.

**Comment by bovy89** [comment]
nothing except a lot of messages like these:

```
2024-01-21T15:56:08.234Z [INFO]  agent.apiproxy: received request: method=GET path=/v1/secret/data/xxxx-backend/test
2024-01-21T15:56:09.332Z [INFO]  agent.apiproxy: forwarding request to Vault: method=GET path=/v1/secret/data/xxxx-backend/test
```

and sometimes `2024-01-21T14:01:27.876Z [INFO]  agent.auth.handler: renewed auth toke`

**Comment by VioletHynes** [comment]
Those look to me like normal logs for when using the API proxy to proxy requests to Vault, so it sounds to me like this is expected -- resource usage goes up under load (when receiving requests to proxy) compared to idle (when not receiving requests to proxy).

**Comment by bovy89** [comment]
increasing limits resolved the problem
