### ISSUE TITLE
Support DogStatsD for telemetry

### ISSUE THREAD

**Issue by justinwalz** [hashicorp/vault#2490]
It would be nice to have this feature implemented for vault as well https://www.consul.io/docs/agent/options.html#telemetry-dogstatsd_addr

It sends similar metrics to the already implemented `statsd_address`, but adds tagging and support for other datadog features.

**Comment by justinwalz** [comment]
Here's the relevant PR for consul, seems like it's already implemented in go-metrics: https://github.com/hashicorp/consul/pull/1293/files

**Comment by Kahn** [comment]
This would be awesome huge +1. I was surprised to see it missing from Vault telemetry since I had just created Consul config.

We use https://github.com/atlassian/gostatsd and need to use tagged metrics for our deployment which the native statsd telemetry doesn't seem to support.
