### ISSUE TITLE
postgresql backend's lease endpoint does not work like the documentation states

### ISSUE THREAD

**Issue by pieterbreed** [hashicorp/vault#2491]
`lease=1h` is not a valid value for the lease.

```
$ vault -version
Vault v0.6.5 ('5d8d702f33b5fd965cbe8d6d0728295de813a196')

$ vault write postgresql/config/lease lease=1h max_lease=1h
Error writing data to postgresql/config/lease: Error making API request.

URL: PUT http://10.200.10.1:8200/v1/postgresql/config/lease
Code: 400. Errors:

* Invalid lease: time: invalid duration 
```

**Comment by vishalnayak** [comment]
@pieterbreed You are noticing this because `max_lease` is incorrect. It should actually be `lease_max`. The error is due to `lease_max` defaulting to `""`.

**Comment by pieterbreed** [comment]
OK thank you. I assumed the parameters were optional (I encountered it first just using `vault write postgresql/config/lease lease=1h` and the error did not point me in this direction. Much appreciated.
