### ISSUE TITLE
Add self-revoke cli command

### ISSUE THREAD

**Issue by cblecker** [hashicorp/vault#2493]
I'd like to request a top-level command in the vault CLI to hit the /v1/auth/token/revoke-self API endpoint and revoke the current token.

Thank you!

**Comment by michaelansel** [comment]
Having `vault token-revoke` without an argument "do the right thing" like `vault token-lookup` would be awesome (albeit maybe a little risky). If you need a workaround, you can always `vault write -f token/revoke-self`.

**Comment by jefferai** [comment]
We specifically do not want `vault token-revoke` to "do the right thing" because it's too easy for that to be "oops, I hit Enter too early".

If someone wants to implement a `-self` flag I'd be fine with that. Send a PR if interested.
