### ISSUE TITLE
MSSQL Secret Backend error

### ISSUE THREAD

**Issue by HelloDBA** [hashicorp/vault#2496]
[root@Vault ~]# vault write mssql/test/config/connection connection_string="server=192.168.1.105;port=2433;User ID=sa;Password=sasa;database=xrm;app name=vault;"
Error writing data to mssql/test/config/connection: Error making API request.

URL: PUT http://192.168.1.106:8200/v1/mssql/test/config/connection
Code: 400. Errors:

* Error validating connection info: Login error: read tcp 192.168.1.106:33663->192.168.1.105:2433: read: connection reset by peer

**Comment by jefferai** [comment]
Not much we can tell you other than the error you see above. Likely a firewall issue.
