### ISSUE TITLE
support sending stdout/stderror to a file

### ISSUE THREAD

**Issue by dch** [hashicorp/vault#2497]
It would be *really* nice to tell vault to send all its output to a boring logfile, or syslog. This crops up when running vault as a daemon, and not using docker etc. Currently I am doing `vault 2>&1 | logger -t vault` which is kludgy.

This cropped up when, after a restart, vault was unable to start up correctly due to missing file permissions, and there were no logs for operators to refer to, just the service unavailability.

**Comment by jefferai** [comment]
> Currently I am doing vault 2>&1 | logger -t vault which is kludgy.

Usually your init system does this for you.

> This cropped up when, after a restart, vault was unable to start up correctly due to missing file permissions, and there were no logs for operators to refer to, just the service unavailability.

Why were there no logs?

**Comment by dch** [comment]
On Thu, 16 Mar 2017, at 11:48, Jeff Mitchell wrote:
> > Currently I am doing vault 2>&1 | logger -t vault which is kludgy.
> 
> Usually your init system does this for you.

Not on non-linux systems such as BSDs.

> > This cropped up when, after a restart, vault was unable to start up correctly due to missing file permissions, and there were no logs for operators to refer to, just the service unavailability.
> 
> Why were there no logs?

Because initially stdout/stderr weren't being captured, so we couldn't
see the failed startup message. Hence the ugly pipe to capture stdio.

**Comment by jefferai** [comment]
> Not on non-linux systems such as BSDs

BSD sysvinit scripts very often do this regardless of which platform they're run on. Other systems such as supervisord and runit are OS independent. BSDs have many, many options for this.
