### ISSUE TITLE
Add allowed_common_names list as configuration option

### ISSUE THREAD

**Issue by jannickk** [hashicorp/vault#24971]
**Describe the solution you'd like**
I want users to be able to generate their own certificates with very specific parameters. The "vault_pki_secret_backend_role" resource allows to configure a lot of properties of the certificates that users of the role are allowed to generate. However, I do not want the users of a role to be able to generate certificates just for any hostname of a domain. In fact, certain roles should only be able to generate certificates for very specific common names.
Currently, only a restriction on a domain can be configured. 
A restriction to a certain set of very specific common names could be realized if a configuration option was available to specify a list of allowed_common_names in a certain role.

**Comment by sgmiller** [comment]
If I understand your ask, this is satisfied by `allow_domains`, which while is _domains, actually applies to CNs in general, and will be quite specific so long as the other options such as allow_glob_domains are false.

**Comment by stevendpclark** [comment]
Hi @jannickk, 

I'm going to close this request out as I believe sgmiller provided the correct answer. If we've misinterpreted the request, please feel free to re-open up with an explanation why the `allow_domains` field doesn't address your request.
