### ISSUE TITLE
% sign causes access denied when using mysql backend

### ISSUE THREAD

**Issue by jaxxstorm** [hashicorp/vault#2499]
I feel like this might be something I'm doing wrong, but I can't figure it out.

I'm using the MySQL secret backend, and configuring it exactly as the [docs](https://www.vaultproject.io/docs/secrets/mysql/) suggest.

```
vault mount mysql
vault write mysql/config/connection connection_url="vault:super_secret_password@tcp(hostname:3306)/"
vault write mysql/roles/readonly sql="GRANT SELECT ON *.* TO '{{name}}'@'%';"
```

However, when I go to read a credential, I get the following error:

```
vault read mysql/creds/readonly                                                                                                                                                           
Error reading mysql/creds/readonly: Error making API request.
URL: GET http://localhost:8200/v1/mysql/creds/readonly
Code: 500. Errors:

* 1 error occurred:

* Error 1045: Access denied for user 'vault'@'%!'(MISSING) (using password: YES)
```

It looks as though the `%` sign is being interpreted by the app, rather than being parsed?

If I change the sql to remove the `GRANT` statement, so like this..

```
vault write mysql/roles/readonly sql="CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';"
Success! Data written to: mysql/roles/readonly
```

it works normally:

```
vault read mysql/creds/readonly                                                                                                                                                           
Key            	Value
---            	-----
lease_id       	mysql/creds/readonly/eceb8e71-19cb-b115-37cd-f6a400f5553b
lease_duration 	768h0m0s
lease_renewable	true
password       	<redacted>
username       	read-root-7d6b0e
```

The weird thing is, with the "broken" command, I can see the user being created in the mysql, so the action of creating the user is being completed:

```
mysql> select user from mysql.user WHERE user LIKE '%read-root%';
+------------------+
| user             |
+------------------+
| read-root-853d41 |
+------------------+
1 row in set (0.00 sec)
```

**Comment by jaxxstorm** [comment]
I'm an idiot. The % sign was a red herring.

The issue was I hadn't allowed the vault user to have the grant option :)

```
GRANT GRANT OPTION ON *.* to 'vault'@'%';
```

Fixed it :)

**Comment by jefferai** [comment]
Does this happen to be some old version of Vault? Our integration tests use the exact same values and we...........and you just closed this. :-)

**Comment by jaxxstorm** [comment]
@jefferai yes I am stupid :)

What would be nice however would be something like "Access denied performing $query" or maybe "Access denied performing `GRANT`" so poor schmucks like me don't get confused :)

**Comment by cbi-kraghunath** [comment]
@jaxxstorm I'm running into this same issue on my Aurora dev server. What permissions did you put on your vault user in MySQL?

**Comment by cbi-kraghunath** [comment]
I'm sure this will happen to someone else out there, so I'll add this here. When you're adding the GRANT permissions and modifying them, it helps to refresh your database/config/my-database entry.

**Comment by jurgenweber** [comment]
I got the same error/problem. I found my users second grant statement had a syntax issue. So more than one reason to run into this.
