### ISSUE TITLE
Feature request: API route for seal status that returns an error code if sealed

### ISSUE THREAD

**Issue by sheldonkwok** [hashicorp/vault#2501]
There's currently a route for seal status in /sys/seal-status but it would be nice if there was a route that returned a different status code for load balancer health checks.

**Comment by briankassouf** [comment]
I think what you might be looking for is the https://www.vaultproject.io/docs/http/sys-health.html endpoint. It has a way to configure the status codes returned for various states. 

Closing for now, but let me know if this isn't what you had in mind!
