### ISSUE TITLE
 Wrap secret option is not wrapping the secret

### ISSUE THREAD

**Issue by imdmahajankanika** [hashicorp/vault#25027]
**Describe the bug**
Hello,

Inside the secret engine, when I click on Wrap secret option from drop-down list, I get the message "Secret successfully wrapped", but it doesn't wrap it.

![image](https://github.com/hashicorp/vault/assets/48632517/e4948378-51a2-4b71-ac4d-4a50c6720f5f)

Vault version:- Vault 1.15.2
Helm Chart version:- vault-0.27.0

**To Reproduce**
1. Login to vault web UI
2. Go to secret engine KV and create a secret
3. Click on "Wrap secret" from drop down (shown in screenshot above)

**Expected behavior**
It should wrap the secret

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault 1.15.2
* Vault CLI Version (retrieve with `vault version`):  Vault v1.15.2 (cf1b5cafa047bc8e4a3f93444fcb4011593b92cb), built 2023-11-06T11:33:28Z
* Server Operating System/Architecture: Installed with helm chart on OKD (openshift)

**Comment by Monkeychip** [comment]
@imdmahajankanika thank you for reporting this issue. I tested on 1.15.6 (the most recent minor version of 1.15) and cannot reproduce. 

I would recommend:
-trying the latest minor version of 1.15.x or if possible upgrading to 1.16.x

If you can't upgrade, a couple of questions:
-when you click "wrap secret" is that followed by the this view in the dropdown? And if it is, when you click the eye icon, can you view the secret?
![image](https://github.com/hashicorp/vault/assets/6618863/c092eafe-221a-4cdd-a477-3eeae8b92c56)
- Are there any console errors when you click "wrap secret"? If so, can you send a screenshot of them?
