### ISSUE TITLE
AppRole tokens not using max_ttl

### ISSUE THREAD

**Issue by ngunia** [hashicorp/vault#2502]
When creating AppRole tokens, it seems the max_ttl does not get used.  If I create a role (as an example) like so:

```
vault write auth/approle/role/my_role policies=my_policy secret_id_ttl=10m token_ttl=1m token_max_ttl=30m secret_id_num_uses=5
```

Then obtain a token:
```
vault write auth/approle/login role_id=<my_role_id> secret_id=<my_secret_id>
```

In this case, unless I'm misinterpreting the documentation for [POST /auth/approle/role/role_name](https://www.vaultproject.io/docs/auth/approle.html), I would expect a token to be generated and valid for a 1m ttl, and be renewable for 30m, the max_ttl.  In reality, the token exists for 1m and then disappears, and is not found if I try to renew it or look it up.

Is this the expected behavior, or am I encountering a bug?  If I'm just misinterpreting, I would appreciate a clarification on what the purpose of setting a max_ttl is. Thanks!

Vault Version: Vault v0.7.0-beta1 ('c2bd662386bcb54ebc9378ad5b2567d919e91a9f')

**Comment by jefferai** [comment]
You closed this without comment but my guess from your text is that you weren't renewing it before the one minute is up.
