### ISSUE TITLE
Confusing behavior when using key with space

### ISSUE THREAD

**Issue by michalmedvecky** [hashicorp/vault#2503]
When using space in front of key name:

```
root@e43601fb3286:~# vault write /secret/test/verysecret " test"=123
Success! Data written to: secret/test/verysecret
root@e43601fb3286:~# vault read /secret/test/verysecret
Key             	Value
---             	-----
refresh_interval	768h0m0s
test            	123
```
(please note that "key" should be `<space>test` instead of `test`.

```
root@e43601fb3286:~# vault read -field=test /secret/test/verysecret
Field test not present in secret
root@e43601fb3286:~# vault read -field=\ test /secret/test/verysecret
123
```

So Vault either incorrectly trims Keys when printing out or allows users to have space in front of key name.

Vault 0.6.5.

**Comment by jefferai** [comment]
@michalmedvecky This is actually just a limitation of the command line shell and Vault CLI interacting. Remember though that the CLI is just an API client; you can do this by directly writing JSON values to Vault's, e.g. by using API libraries or `curl`.
