### ISSUE TITLE
with pkiCert write one file

### ISSUE THREAD

**Issue by dispancergit** [hashicorp/vault#25113]
**Is your feature request related to a problem? Please describe.**
When requesting a certificate, I receive one file, instead of two, as I believe this is what the commentary says?
I would also like to receive the ROOT CA that signed my INT (hereinafter in context .CA = INT)

**Describe the solution you'd like**
Receiving each file separately, not glued together

**Describe alternatives you've considered**
Write the generated certificate data to KV and use secret anatomy

**Explain any additional use-cases**
Very convenient - if there are more opportunities to record several files separately (for example, keys)

**Additional context**
Name:             red-84bd8775ff-fgf66
Namespace:        red
Priority:         0
Service Account:  red
Node:             n1/192.168.137.3
Start Time:       Mon, 29 Jan 2024 10:20:06 +0300
Labels:           app.kubernetes.io/instance=red
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=red
                  app.kubernetes.io/version=1.16.0
                  helm.sh/chart=nginx-0.1.0
                  pod-template-hash=84bd8775ff
                  security.istio.io/tlsMode=istio
                  service.istio.io/canonical-name=red
                  service.istio.io/canonical-revision=1.16.0
Annotations:      istio.io/rev: default
                  kubectl.kubernetes.io/default-container: nginx
                  kubectl.kubernetes.io/default-logs-container: nginx
                  prometheus.io/path: /stats/prometheus
                  prometheus.io/port: 15020
                  prometheus.io/scrape: true
                  sidecar.istio.io/status:
                    {"initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["workload-socket","credential-socket","workload-certs","istio-env...
                  **vault.hashicorp.com/agent-init-first: true
                  vault.hashicorp.com/agent-inject: true
                  vault.hashicorp.com/agent-inject-secret-certs: eggs/issue/peer_policy
                  vault.hashicorp.com/agent-inject-status: injected
                  vault.hashicorp.com/agent-inject-template-certs:
                    {{- with pkiCert "eggs/issue/peer_policy" "common_name=red.net.local" "ttl=24h" -}}
                    {{ .Cert }}{{ .CA }}{{ .Key }}
                    {{ .Key | writeToFile "/home/vault/ssl/cert.key" "vault" "vault" "0644" }}
                    {{ .CA | writeToFile "/home/vault/ssl/cert.pem" "vault" "vault" "0644" }}
                    {{ .Cert | writeToFile "/home/vault/ssl/cert.pem" "vault" "vault" "0644" "append" }}
                    {{- end -}}
                  vault.hashicorp.com/role: red**
Status:           Running
IP:               10.244.0.128
IPs:
  IP:           10.244.0.128
Controlled By:  ReplicaSet/red-84bd8775ff
Init Containers:
  vault-agent-init:
    Container ID:  containerd://564a8e9356ac97a1c16d5d0e0abef5eb615d546829cf381cd72ce742697160c8
    Image:         hashicorp/vault:1.15.2
    Image ID:      docker.io/hashicorp/vault@sha256:6b4e5dadf082cb3587930ced09b52851c5ae9f8d1c7df31ed39f0085a3029f63
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -ec
    Args:
      echo ${VAULT_CONFIG?} | base64 -d > /home/vault/config.json && vault agent -config=/home/vault/config.json
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 29 Jan 2024 10:20:07 +0300
      Finished:     Mon, 29 Jan 2024 10:20:07 +0300
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:     250m
      memory:  64Mi
    Environment:
      NAMESPACE:         red (v1:metadata.namespace)
      HOST_IP:            (v1:status.hostIP)
      POD_IP:             (v1:status.podIP)
      VAULT_LOG_LEVEL:   info
      VAULT_LOG_FORMAT:  standard
      VAULT_CONFIG:      eyJhdXRvX2F1dGgiOnsibWV0aG9kIjp7InR5cGUiOiJrdWJlcm5ldGVzIiwibW91bnRfcGF0aCI6ImF1dGgva3ViZXJuZXRlcyIsImNvbmZpZyI6eyJyb2xlIjoicmVkIiwidG9rZW5fcGF0aCI6Ii92YXIvcnVuL3NlY3JldHMva3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC90b2tlbiJ9fSwic2luayI6W3sidHlwZSI6ImZpbGUiLCJjb25maWciOnsicGF0aCI6Ii9ob21lL3ZhdWx0Ly52YXVsdC10b2tlbiJ9fV19LCJleGl0X2FmdGVyX2F1dGgiOnRydWUsInBpZF9maWxlIjoiL2hvbWUvdmF1bHQvLnBpZCIsInZhdWx0Ijp7ImFkZHJlc3MiOiJodHRwOi8vdmF1bHQudmF1bHQuc3ZjOjgyMDAifSwidGVtcGxhdGUiOlt7ImRlc3RpbmF0aW9uIjoiL3ZhdWx0L3NlY3JldHMvY2VydHMiLCJjb250ZW50cyI6Int7LSB3aXRoIHBraUNlcnQgXCJlZ2dzL2lzc3VlL3BlZXJfcG9saWN5XCIgXCJjb21tb25fbmFtZT1yZWQubmV0LmxvY2FsXCIgXCJ0dGw9MjRoXCIgLX19XG57eyAuQ2VydCB9fXt7IC5DQSB9fXt7IC5LZXkgfX1cbnt7IC5LZXkgfCB3cml0ZVRvRmlsZSBcIi9ob21lL3ZhdWx0L3NzbC9jZXJ0LmtleVwiIFwidmF1bHRcIiBcInZhdWx0XCIgXCIwNjQ0XCIgfX1cbnt7IC5DQSB8IHdyaXRlVG9GaWxlIFwiL2hvbWUvdmF1bHQvc3NsL2NlcnQucGVtXCIgXCJ2YXVsdFwiIFwidmF1bHRcIiBcIjA2NDRcIiB9fVxue3sgLkNlcnQgfCB3cml0ZVRvRmlsZSBcIi9ob21lL3ZhdWx0L3NzbC9jZXJ0LnBlbVwiIFwidmF1bHRcIiBcInZhdWx0XCIgXCIwNjQ0XCIgXCJhcHBlbmRcIiB9fVxue3stIGVuZCAtfX1cbiIsImxlZnRfZGVsaW1pdGVyIjoie3siLCJyaWdodF9kZWxpbWl0ZXIiOiJ9fSJ9XSwidGVtcGxhdGVfY29uZmlnIjp7ImV4aXRfb25fcmV0cnlfZmFpbHVyZSI6dHJ1ZX19
    Mounts:
      /home/vault from home-init (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fj69z (ro)
      /vault/secrets from vault-secrets (rw)
  istio-init:
    Container ID:  containerd://ac24a1426c0f9c85a02732a6af26c0b2f05efb112fd8a4d5c8d86b78a34776a4
    Image:         docker.io/istio/proxyv2:1.20.0
    Image ID:      docker.io/istio/proxyv2@sha256:19e8ca96e4f46733a3377fa962cb88cad13a35afddb9139ff795e36237327137
    Port:          <none>
    Host Port:     <none>
    Args:
      istio-iptables
      -p
      15001
      -z
      15006
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x
      -b
      *
      -d
      15090,15021,15020
      --log_output_level=default:info
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 29 Jan 2024 10:20:07 +0300
      Finished:     Mon, 29 Jan 2024 10:20:07 +0300
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:        100m
      memory:     128Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fj69z (ro)
      /vault/secrets from vault-secrets (rw)
Containers:
  nginx:
    Container ID:   containerd://f1db4d7382d6e5f91d664575836d4aad00ad4499606c1e0102e3f4f56d26c9cc
    Image:          benhall/nginx-with-curl:latest
    Image ID:       docker.io/benhall/nginx-with-curl@sha256:7ea22129ab17b7d36b4acaf9c0118eeb6a79dff0365b60d01990e072e2e6ca66
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 29 Jan 2024 10:20:08 +0300
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:15020/app-health/nginx/livez delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:15020/app-health/nginx/readyz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /ssl from ssl (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fj69z (ro)
      /vault/secrets from vault-secrets (rw)
  istio-proxy:
    Container ID:  containerd://72e846bfd4c17c5f92a833463935eac947955aaf19221e64df44688ba8ea398c
    Image:         docker.io/istio/proxyv2:1.20.0
    Image ID:      docker.io/istio/proxyv2@sha256:19e8ca96e4f46733a3377fa962cb88cad13a35afddb9139ff795e36237327137
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --proxyLogLevel=warning
      --proxyComponentLogLevel=misc:error
      --log_output_level=default:info
    State:          Running
      Started:      Mon, 29 Jan 2024 10:20:08 +0300
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15021/healthz/ready delay=0s timeout=3s period=15s #success=1 #failure=4
    Startup:    http-get http://:15021/healthz/ready delay=0s timeout=3s period=1s #success=1 #failure=600
    Environment:
      JWT_POLICY:                    third-party-jwt
      PILOT_CERT_PROVIDER:           istiod
      CA_ADDR:                       istiod.istio-system.svc:15012
      POD_NAME:                      red-84bd8775ff-fgf66 (v1:metadata.name)
      POD_NAMESPACE:                 red (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      SERVICE_ACCOUNT:                (v1:spec.serviceAccountName)
      HOST_IP:                        (v1:status.hostIP)
      ISTIO_CPU_LIMIT:               2 (limits.cpu)
      PROXY_CONFIG:                  {}
      ISTIO_META_POD_PORTS:          [
                                         {"name":"http","containerPort":80,"protocol":"TCP"}
                                     ]
      ISTIO_META_APP_CONTAINERS:     nginx
      GOMEMLIMIT:                    1073741824 (limits.memory)
      GOMAXPROCS:                    2 (limits.cpu)
      ISTIO_META_CLUSTER_ID:         Kubernetes
      ISTIO_META_NODE_NAME:           (v1:spec.nodeName)
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_META_WORKLOAD_NAME:      red
      ISTIO_META_OWNER:              kubernetes://apis/apps/v1/namespaces/red/deployments/red
      ISTIO_META_MESH_ID:            cluster.local
      TRUST_DOMAIN:                  cluster.local
      ISTIO_KUBE_APP_PROBERS:        {"/app-health/nginx/livez":{"httpGet":{"path":"/","port":80,"scheme":"HTTP"},"timeoutSeconds":1},"/app-health/nginx/readyz":{"httpGet":{"path":"/","port":80,"scheme":"HTTP"},"timeoutSeconds":1}}
    Mounts:
      /etc/istio/pod from istio-podinfo (rw)
      /etc/istio/proxy from istio-envoy (rw)
      /var/lib/istio/data from istio-data (rw)
      /var/run/secrets/credential-uds from credential-socket (rw)
      /var/run/secrets/istio from istiod-ca-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fj69z (ro)
      /var/run/secrets/tokens from istio-token (rw)
      /var/run/secrets/workload-spiffe-credentials from workload-certs (rw)
      /var/run/secrets/workload-spiffe-uds from workload-socket (rw)
      /vault/secrets from vault-secrets (rw)
  vault-agent:
    Container ID:  containerd://73519091cb46b858b599e489f4aa17de8c046ea3ce6f981b7d43489bf6f15826
    Image:         hashicorp/vault:1.15.2
    Image ID:      docker.io/hashicorp/vault@sha256:6b4e5dadf082cb3587930ced09b52851c5ae9f8d1c7df31ed39f0085a3029f63
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -ec
    Args:
      echo ${VAULT_CONFIG?} | base64 -d > /home/vault/config.json && vault agent -config=/home/vault/config.json
    State:          Running
      Started:      Mon, 29 Jan 2024 10:20:08 +0300
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:     250m
      memory:  64Mi
    Environment:
      NAMESPACE:         red (v1:metadata.namespace)
      HOST_IP:            (v1:status.hostIP)
      POD_IP:             (v1:status.podIP)
      VAULT_LOG_LEVEL:   info
      VAULT_LOG_FORMAT:  standard
      VAULT_CONFIG:      eyJhdXRvX2F1dGgiOnsibWV0aG9kIjp7InR5cGUiOiJrdWJlcm5ldGVzIiwibW91bnRfcGF0aCI6ImF1dGgva3ViZXJuZXRlcyIsImNvbmZpZyI6eyJyb2xlIjoicmVkIiwidG9rZW5fcGF0aCI6Ii92YXIvcnVuL3NlY3JldHMva3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC90b2tlbiJ9fSwic2luayI6W3sidHlwZSI6ImZpbGUiLCJjb25maWciOnsicGF0aCI6Ii9ob21lL3ZhdWx0Ly52YXVsdC10b2tlbiJ9fV19LCJleGl0X2FmdGVyX2F1dGgiOmZhbHNlLCJwaWRfZmlsZSI6Ii9ob21lL3ZhdWx0Ly5waWQiLCJ2YXVsdCI6eyJhZGRyZXNzIjoiaHR0cDovL3ZhdWx0LnZhdWx0LnN2Yzo4MjAwIn0sInRlbXBsYXRlIjpbeyJkZXN0aW5hdGlvbiI6Ii92YXVsdC9zZWNyZXRzL2NlcnRzIiwiY29udGVudHMiOiJ7ey0gd2l0aCBwa2lDZXJ0IFwiZWdncy9pc3N1ZS9wZWVyX3BvbGljeVwiIFwiY29tbW9uX25hbWU9cmVkLm5ldC5sb2NhbFwiIFwidHRsPTI0aFwiIC19fVxue3sgLkNlcnQgfX17eyAuQ0EgfX17eyAuS2V5IH19XG57eyAuS2V5IHwgd3JpdGVUb0ZpbGUgXCIvaG9tZS92YXVsdC9zc2wvY2VydC5rZXlcIiBcInZhdWx0XCIgXCJ2YXVsdFwiIFwiMDY0NFwiIH19XG57eyAuQ0EgfCB3cml0ZVRvRmlsZSBcIi9ob21lL3ZhdWx0L3NzbC9jZXJ0LnBlbVwiIFwidmF1bHRcIiBcInZhdWx0XCIgXCIwNjQ0XCIgfX1cbnt7IC5DZXJ0IHwgd3JpdGVUb0ZpbGUgXCIvaG9tZS92YXVsdC9zc2wvY2VydC5wZW1cIiBcInZhdWx0XCIgXCJ2YXVsdFwiIFwiMDY0NFwiIFwiYXBwZW5kXCIgfX1cbnt7LSBlbmQgLX19XG4iLCJsZWZ0X2RlbGltaXRlciI6Int7IiwicmlnaHRfZGVsaW1pdGVyIjoifX0ifV0sInRlbXBsYXRlX2NvbmZpZyI6eyJleGl0X29uX3JldHJ5X2ZhaWx1cmUiOnRydWV9fQ==
    Mounts:
      /home/vault from home-sidecar (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fj69z (ro)
      /vault/secrets from vault-secrets (rw)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       True 
  ContainersReady             True 
  PodScheduled                True 
Volumes:
  workload-socket:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  credential-socket:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  workload-certs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  istio-podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
  istio-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  43200
  istiod-ca-cert:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio-ca-root-cert
    Optional:  false
  ssl:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-fj69z:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
  home-init:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  home-sidecar:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  vault-secrets:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      Memory
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>

One file - certs:
chile@omega:~/ansible$ kubectl -n red exec -it red-84bd8775ff-fgf66 -c nginx -- cat vault/secrets/certs | grep BEGIN
-----BEGIN CERTIFICATE-----
-----BEGIN CERTIFICATE-----
-----BEGIN RSA PRIVATE KEY-----

In this example:
https://developer.hashicorp.com/vault/docs/platform/k8s/injector/examples
one for the certificate and CA (cert.pem) and one for the key (cert.key) generated , but generated one file

**Comment by celesteking** [comment]
[see pkiCert function](https://github.com/hashicorp/consul-template/blob/main/docs/templating-language.md#pkicert) spec, the example part with `writeToFile` usage.

**Comment by stevendpclark** [comment]
@dispancergit I believe that @celesteking has properly answered the question you had, thanks @celesteking!

I'll close out this issue, but if I'm incorrect please feel free to re-open this issue with further details.
