### ISSUE TITLE
[documentation] ec2 backend sts 

### ISSUE THREAD

**Issue by baptiste-ls** [hashicorp/vault#2512]
hey there's an error in the documentation:

https://www.vaultproject.io/docs/auth/aws-ec2.html#auth-aws-ec2-config-sts-

we have the POST url 
```
/auth/aws-ec2/config/certificate/<account_id>
```

but it should be:
```
/auth/aws-ec2/config/sts/<account_id>
```

best

**Comment by jefferai** [comment]
Fixed, thanks!
