### ISSUE TITLE
Update github.com/cloudflare/circl to address GHSA

### ISSUE THREAD

**Issue by jsermersheim-hv** [hashicorp/vault#25131]
**Describe the bug**
There is a vulnerability in the version of the github.com/cloudflare/circl used in Vault (1.3.3).

https://github.com/advisories/GHSA-9763-4f94-gfch

**Comment by jsermersheim-hv** [comment]
Looks like this was bumped in main and has a backport target of 1.14 and 1.15:

https://github.com/hashicorp/vault/pull/24708

Any chance this being backported to 1.13 as well?

**Comment by hghaf099** [comment]
@jsermersheim-hv Thanks for opening this issue and welcome to the Vault community. Note that our next release is going to be 1.16, after which we are not going to release 1.13.x anymore. So, that is why that have not backported that fix into 1.13. I am going to close this issue for now.
