### ISSUE TITLE
Metric “vault_core_unsealed” shows 1 all the time

### ISSUE THREAD

**Issue by diegoballen** [hashicorp/vault#25214]
**Describe the bug**
Dear Ladies and Gentlement,

we are currently testing Hashicorp Vault v1.15.2 in our test AKS cluster (2 Vault Pods for HA). Working on the monitoring in Grafana we realized, that the metric vault_core_unsealed shows the value 1 (unsealed) all the time. Even when the Vault is sealed (through the command “vault operator seal”). The metric never shows the value 0.

I followed the instructions in this post ([Post Link](https://discuss.hashicorp.com/t/monitoring-vault-seal-status/46413/4)), but unfortunately this did not solved the issue.

**To Reproduce**
1. Add the vault_core_unsealed  to a Grafana Dashboard.
2. Seal the Vault
3. Wait for some time.
4. Unseal the Vault

**Expected behavior**
The metric should show the value 0 for the time the Vault was sealed and then return to 1 when unsealed. 

**Environment:**
* Vault Server Version (retrieve with `vault status`): Helm Chart v0.27.0
* Vault CLI Version (retrieve with `vault version`): Vault Version v1.15.2
* Server Operating System/Architecture: Azure AKS

**Comment by hghaf099** [comment]
@diegoballen Thanks for filing this issue and welcome to the Vault community. I am wondering how did you setup Grafana, as that metric is [set to zero](https://github.com/hashicorp/vault/blob/003ee1c8560b4b374a86dfb91ac2b4cfb02e47a8/vault/core_metrics.go#L71-L75) when Vault is sealed. I did test that with a Grafana dashboard and I do see the drop from 1 to 0 after I sealed Vault. [Here](https://github.com/hashicorp/vault/blob/003ee1c8560b4b374a86dfb91ac2b4cfb02e47a8/vault/core_metrics.go#L71-L75) is also our list of metrics with the explanation for the unsealed one. This [tutorial](https://developer.hashicorp.com/vault/tutorials/monitoring/monitor-telemetry-grafana-prometheus) is also a great reference for how to setup different metrics in Grafana. I am going to close this issue for now. Please do let us know if you have further questions.
