### ISSUE TITLE
Error() call not returning the curl string as expected

### ISSUE THREAD

**Issue by sanjan** [hashicorp/vault#25213]
https://github.com/hashicorp/vault/blob/79ed357954ef41718b2899ab9ac7b6e880f16004/api/output_string.go#L37

This call always returns the constant value: "output a string, please"

**Comment by hghaf099** [comment]
Thank you for filing this issue and welcome to the Vault community. Would you please elaborate the issue a bit more with a clear reproducing steps? Note that to see the equivalent API call to perform the same operation as the CLI command, you can use the `-output-curl-string` flag after the subcommand as pointed out [here](https://developer.hashicorp.com/vault/docs/commands#print-curl-command). I hope this helps!

**Comment by sanjan** [comment]
@hghaf099  there is no return call for the variable: finalCurlString , so calling Error() method always returns the constant string: ErrOutputStringRequest

**Comment by raskchanky** [comment]
Hi @sanjan! Thanks for reaching out. You've uncovered an interesting area of the code that's quite confusing. I confess that before reading this issue, I didn't fully understand how `-output-curl-string` actually worked. The tl;dr is that although it's confusing, it's correct the way it is. I've opened https://github.com/hashicorp/vault/pull/28576 which contains some additional comments that explains in more detail why it is the way it is. Thanks for bringing this area of confusion to our attention!
