### ISSUE TITLE
Make issue, new

### ISSUE THREAD

**Issue by lcbowen3** [hashicorp/vault#253]
Did a pull from the master branch today (just "git pull" in the vault directory).  

The "make" command works fine (no errors in the tests), but "make dev" now fails:

[root@ip-10-16-19-21 vault]# make dev
go generate ./...
==> Getting dependencies...
# github.com/hashicorp/vault/physical
physical/s3.go:104: undefined: aws.Error
make: *** [dev] Error 2

Thanks,
Clay

**Comment by certifiedloud** [comment]
Looks like fallout from this issue: https://github.com/hashicorp/vault/issues/120

**Comment by lcbowen3** [comment]
And apparently it skips the tests if the ENV variables aren't present, so it doesn't even complain until the attempt to compile.  Nice.

**Comment by lcbowen3** [comment]
Still doesn't work, even thought the test passes with the ENV present:

?       github.com/hashicorp/vault/helper/password      [no test files]
ok      github.com/hashicorp/vault/http 0.227s
ok      github.com/hashicorp/vault/logical      0.015s
ok      github.com/hashicorp/vault/logical/framework    0.033s
ok      github.com/hashicorp/vault/logical/testing      0.091s
ok      github.com/hashicorp/vault/physical     1.301s
ok      github.com/hashicorp/vault/shamir       0.014s
ok      github.com/hashicorp/vault/vault        0.630s
[root@ip-10-16-19-21 vault]# make dev
go generate ./...
==> Getting dependencies...
# github.com/hashicorp/vault/physical
physical/s3.go:104: undefined: aws.Error
make: *** [dev] Error 2


Thanks,
Clay

**Comment by armon** [comment]
@icebourg Please try to update your upstreams:
```
$ cd $VAULT_DIR
$ go get -u ./...
```

**Comment by armon** [comment]
This is a duplicate of #249

**Comment by armon** [comment]
@lcbowen3 Should be fixed by #256

**Comment by lcbowen3** [comment]
Perfect, thank you.

Clay

On Fri, May 22, 2015 at 1:15 PM, Armon Dadgar <notifications@github.com>
wrote:

> Closed #253 <https://github.com/hashicorp/vault/issues/253>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/vault/issues/253#event-311944407>.
>



-- 
--------------------------------------------------------
Entia non sunt multiplicanda praeter necessitatem
    - William of Ockham (1288 - ~1348)
--------------------------------------------------------
