### ISSUE TITLE
Mysql (file key management plugin) with vault

### ISSUE THREAD

**Issue by uzairali37** [hashicorp/vault#2530]
To encrypt Mysql data at rest using vault with file key management plugin. Its possible or not? i am having difficulties to connect vault with file key management plugin. can someone please comment ?

**Comment by jefferai** [comment]
@uzairali37 Unfortunately I think you'll need to talk to the authors of MySQL's file key management plugin, as we don't have experience with it here. However, I should mention that many users make use of Vault's transit backend to encrypt values prior to being written to any particular database and decrypt them on the way out. The benefit of doing this out-of-band is that if you want to switch database layers or send the data to other locations the encryption is not tied purely to the database and the value can safely be sent from one entity to another in ciphertext.
