### ISSUE TITLE
Proxied requests not being sent

### ISSUE THREAD

**Issue by SuperMatt** [hashicorp/vault#2532]
Hi,

I have a vault cluster, and I am sporadically seeing issues where I perform an API request against a slave, and eventually the connection times out. The vault logs on the slave essentially read like the following:

`2017/03/27 08:30:11.453070 [ERROR] http/handleRequestForwarding: error forwarding request: error=read tcp 10.x.x.x:37054->10.y.y.y:8201: read: connection timed out`

However, running a tcpdump on the master server shows no inbound connections to the host.

During this period, I can still perform run `nc -v 10.y.y.y 8201` and create a connection, so it looks like the problem is within the vault client itself, not even beginning to establish the connection.

If you need any more diagnostics, please let me know.

**Comment by SuperMatt** [comment]
Please be aware that this affects versions 0.6.5 and 0.7.0.

**Comment by jefferai** [comment]
What are your Vault configuration files, and when you start Vault and it prints some info, what are those values?

**Comment by SuperMatt** [comment]
Please see the below, which contains redacted information:

```
==> Vault server configuration:

                 Backend: consul (HA available)
                     Cgo: disabled
         Cluster Address: https://vault01.domain.example.com:8201
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "", tls: "enabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
        Redirect Address: https://vault01.domain.example.com:8200
                 Version: Vault v0.6.5
             Version Sha: 5d8d702f33b5fd965cbe8d6d0728295de813a196

==> Vault server started! Log data will stream in below:
```

```
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/var/vault/vault.crt"
  tls_key_file = "/var/vault/vault.key"
}

disable_mlock = true


backend "consul" {
    address = "consul.domain.example.com:8080"
    path = "vault/"
    token = "xxxxxxxx"
    advertise_addr = "https://vault01.domain.example.com:8200"
    scheme = "https"
    tls_ca_file = "/var/vault/ca.pem"
}
```

**Comment by jefferai** [comment]
Does adding a `cluster_address` help? https://www.vaultproject.io/docs/configuration/listener/tcp.html

Generally though if the issue was with listening on the right port you'd expect it to never work. As you're describing this as sporadic it suggests something else is going on -- either some kind of network blip causing the forwarding connection to be lost, or something else in Vault.

**Comment by SuperMatt** [comment]
My guess would be that it's an issue within vault itself, because all the while connections are timing out, I am able to make TCP connections to the port. TCP dump also suggests that there is no sign of the traffic coming in from the slave nodes.

I can try adding cluster_address, but it may have to be at a later date, naturally because this is a production cluster.

Is there any debugging information that I can provide?

**Comment by jefferai** [comment]
Are you making those TCP connections to Vault from the standby server to the active server?

I don't have any specific ideas, however, usually when we've seen this it's ended up being a firewall or some kind of security product between the nodes that's causing issues -- in some cases only between the nodes, not between clients and each node (hence my earlier question).

**Comment by SuperMatt** [comment]
Yes, the connections are being made from the standby server to the active server. For now I will close the issue, but I will reopen it if I come across any more information.
