### ISSUE TITLE
[Deadlock] Hanging when reading a transit key

### ISSUE THREAD

**Issue by mju** [hashicorp/vault#25325]
**Describe the bug**
Earlier today, we noticed that out of 10s of transit key, we couldn't read one.  The symptom was a time out.
I am using `broken_transit_key` in place of the real key name.

```
$ vault read -format=json transit/keys/broken_transit_key
Error reading transit/keys/broken_transit_key: context deadline exceeded
```

Our set-up has five nodes in a raft cluster.  In this case, a non-leader node received the requests
and tried to forward them to the leader.  The non-leader node always logged the following error
when serving this request.  When we tried to read other good transit keys, the same node didn't
log such an error.

```
Feb  8 21:10:31 ip-xx-xx-xx-xx xxx[xxxx]: 2024-02-08T21:10:31.125Z [ERROR] core: error during forwarded RPC request: error="rpc error: code = Canceled desc = context canceled"
Feb  8 21:10:31 ip-xx-xx-xx-xx xxx[xxxx]: 2024-02-08T21:10:31.125Z [ERROR] core: forward request error: error="error during forwarding RPC request"
```

The graph showed that the leader had been accumulating in-flight requests since the start of the problem.

![Screenshot from 2024-02-08 15-27-12](https://github.com/hashicorp/vault/assets/1553860/4704d3d3-a71d-4fee-b72b-4ea6156b5eec)

We enabled debug and trace log globally and saw 0 log entries related to this transit key or the transit
secret engine in general.

We deeply regret that we didn't grab a thread dump with the following command.
For anyone who runs into this problem, get a thread dump!!!

```
sudo kill -SIGUSR2 $(pidof vault)
```

**To Reproduce**

We do not know how to reproduce the problem.  Our engineer said they did the following
repeatedly with the key.  They used a python script via its http library.  The commands below
are for demonstration purpose.  Note that we haven't confirmed that this directly led to the
problem.

1. read the public key
```
vault read -format=json transit/keys/broken_transit_key
```

2. sign something
```
vault write transit/sign/broken_transit_key/none input=aGVsbG8gd29ybGQuCg== prehashed=true signature_algorithm=pkcs1v15
```

This might or might not be a red-herring, but we recently started using [none](https://developer.hashicorp.com/vault/api-docs/secret/transit#none).

**Expected behavior**
Reading a transit key should not be blocked this way.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.15.1 (OSS)
* Vault CLI Version (retrieve with `vault version`): 1.15.1 (OSS)
* Server Operating System/Architecture: Ubuntu 18.04

**Additional context**
We suspect that there is a deadlock somewhere
in the transit secret engine code.  This reminds me of https://github.com/hashicorp/vault/issues/22393.

Eventually, we tried to step down the leader with

```
vault operator step-down
```
The leader hung there so eventually we killed the instance and the cluster recovered.
At that point, the cluster was able to serve the secret again.

**Comment by mju** [comment]
In https://github.com/hashicorp/vault/blob/5a1339571712cc8832f83504d0cd944ed7047c15/builtin/logical/transit/path_sign_verify.go#L377, it seems before every return statement after the policy is created, we need to Unlock().  Should the code be

```
	if hashAlgorithm == keysutil.HashTypeNone && p.Type != keysutil.KeyType_MANAGED_KEY {
		if !prehashed || sigAlgorithm != "pkcs1v15" {
                        p.Unlock()     <---------------------------------------------is this required?
			return logical.ErrorResponse("hash_algorithm=none requires both prehashed=true and signature_algorithm=pkcs1v15"), logical.ErrInvalidRequest
		}
	}
```

**Comment by mju** [comment]
@stevendpclark please help take a look at this as https://github.com/hashicorp/vault/pull/23676 added the code that returns without calling Unlock().  Thanks a ton.

**Comment by mju** [comment]
I was thinking if I created a key and got into the block, I would be able to cause deadlock on the key.  It didn't work.  Some other conditions are required.  I did

```
vault secrets enable transit
vault write transit/keys/thekey type=rsa-4096
vault write transit/sign/thekey/none input=aGVsbG8gd29ybGQuCg== prehashed=true
Error writing data to transit/sign/thekey/none: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/transit/sign/thekey/none
Code: 400. Errors:

* hash_algorithm=none requires both prehashed=true and signature_algorithm=pkcs1v15

vault read transit/keys/thekey
Key                       Value
---                       -----
allow_plaintext_backup    false
...
```

**Comment by stevendpclark** [comment]
@mju Yup agreed, clearly the spot that you pointed out is missing an Unlock but as you've specified I haven't been able to reproduce this directly either. Still investigating, but thanks for bringing it to our attention.

**Comment by mju** [comment]
I reproduced the deadlock for the missing Unlock() I reported.  I noticed that the caching is enabled by default.  When cache size is 0, a sync.Map will be used.  This is done by reading the code.  Now, to reproduce it, I just needed a transit engine with cache disabled.  And that was it.

```
$ vault secrets enable -force-no-cache=true -path=transit2 transit
Success! Enabled the transit secrets engine at: transit2/
$ vault write transit2/keys/thekey type=rsa-4096
Key                       Value
---                       -----
allow_plaintext_backup    false
auto_rotate_period        0s
deletion_allowed          false
derived                   false
exportable                false
imported_key              false
keys                      map[1:map[certificate_chain: creation_time:2024-02-09T09:29:40.250654205-08:00 name:rsa-4096 public_key:-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAolqVDhGf7mnl9gp+hEYM
fCJ1zloaDj4VKXJZjCagoHCQIViHmT6nUTxQwhdihv/YkA+bOKyA2ymSNPWngwhp
H/mRKB+KJm1w6gLd1uE+/4uAU8ScIup5Kp03xVQcnhjqkScz56vEHMBltZkbK+FV
0viDr1K+TOzTFQ72eA9fx2nMWtOpQbjuSryClCRv3htKcIx2+JnZ3ewvTgCL3WuE
HkoZU2SvDf25TTGgb92JkXc8Al83+KMc0I26DInfio4sFAXLO0qSkwytR5Mg2cLI
MqcEkkEALM57iGMqMxqY/OBBsx2yqIPaXnscQnd+Z54LY16Vrx5iIdAf+DcLbHvU
stAsM/MhPfcciKJjKm+eR58ewBBaX6Jj1WipQpKgNoPM3wk0QABCPyoT3OL52Zdh
RZyvf//GnJdMWmbnWjUQiVE/tt4AS+b2gfCsC9ebBA/CDi/iKWtuDzQg8pZr/gFw
dFhAwoVqivxPejCjVyGopViiXLUEGmyqmUBdc0DB4uurIlpvqaCjYFdR3DWaGmaM
Sv3YZV3UX6UQp9tsR9r8cYIcVoRhTuL5zKZOF77LSRNXMijL49jswesVyzAri4FJ
gLOJLOHdZWQG9E4b/PXWeJdH4Dswyq9tWNHnnPMfhl90tQg1cL1Ryl0YHC5/Ppti
Kr6mKa7BsC2FI0fREK2XqIcCAwEAAQ==
-----END PUBLIC KEY-----
]]
latest_version            1
min_available_version     0
min_decryption_version    1
min_encryption_version    0
name                      thekey
supports_decryption       true
supports_derivation       false
supports_encryption       true
supports_signing          true
type                      rsa-4096

$ vault write transit2/sign/thekey/none input=aGVsbG8gd29ybGQuCg== prehashed=true
Error writing data to transit2/sign/thekey/none: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/transit2/sign/thekey/none
Code: 400. Errors:

* hash_algorithm=none requires both prehashed=true and signature_algorithm=pkcs1v15



$ vault read transit2/keys/thekey     <----------------------------hanging
```

**Comment by stevendpclark** [comment]
Technically you can also reproduce this with a configuration update with caching enabled as well, just attempt to update the configuration of the key in question after the error. 

```shell
$ vault secrets enable transit
$ vault write transit/keys/broken_transit_key type=rsa-2048
$ vault write transit/sign/broken_transit_key input=aGVsbG8gd29ybGQuCg== prehashed=false  hash_algorithm=none
$ vault write transit/keys/broken_transit_key/config auto_rotate_period=1h 
```

**Comment by stevendpclark** [comment]
@mju Thanks again for reporting the issue, the fix should appear in the next round of minor Vault releases. 1.15.6, 1.14.10 and 1.13.14

**Comment by mju** [comment]
> ```shell
> vault write transit/keys/broken_transit_key/config auto_rotate_period=1h
> ```

This is a very interesting sequence.  Basically, when caching is off, the code actually holds a read lock.
When trying to change the config, thread number 2 will attempt to acquire a write lock, which prevents future acquisition
of any read locks.  This thread will hang here forever.  We leak a read lock and a goroutine at this point.
Now, when thread 3 comes along wanting to read the key, a read lock is required but can never be obtained.
This thread is leaked by deadlocking.

Our problem shares the same pattern but was caused by a different access pattern/sequence.  The best way
to reproduce our problem is the following.  First a local dev server is required (`vault server -dev`).

```
vault secrets enable transit
vault write transit/keys/broken_transit_key type=rsa-2048   <------ has to be rsa-2048.
vault write transit/sign/broken_transit_key input=aGVsbG8gd29ybGQuCg== prehashed=false  hash_algorithm=none
vault read transit/keys/broken_transit_key     <---- hangs when called after 3-5 minutes since the above commands
```

Shocking huh?  I tried it many times and it locked every time.  Somehow if I use an rsa-4096 key, the problem
doesn't occur after 3-5 minutes.  There is some inner working I don't fully understand.  I grabbed a thread dump
at that moment by running `sudo kill -SIGUSR2 $(pidof vault)`.  And there are only two threads that were locked up.
One is the key-reading thread.  No surprise here.

```
goroutine 1693 [sync.RWMutex.RLock]:
sync.runtime_SemacquireRWMutexR(0x9dd2c00?, 0x1?, 0x0?)
        /opt/hostedtoolcache/go/1.21.3/x64/src/runtime/sema.go:82 +0x25
sync.(*RWMutex).RLock(...)
        /opt/hostedtoolcache/go/1.21.3/x64/src/sync/rwmutex.go:71
github.com/hashicorp/vault/sdk/helper/keysutil.(*Policy).Lock(0xb8c8630?, 0xc0?)
        /home/runner/work/vault/vault/sdk/helper/keysutil/policy.go:478 +0x32
github.com/hashicorp/vault/builtin/logical/transit.(*backend).pathPolicyRead(0xc002be1420, {0xb8c78d8, 0xc002787d10}, 0xc004168000, 0xffffffffffffffff?)
        /home/runner/work/vault/vault/builtin/logical/transit/path_keys.go:293 +0x20c
github.com/hashicorp/vault/sdk/framework.(*Backend).HandleRequest(0xc0033054a0, {0xb8c78d8, 0xc002787d10}, 0xc004168000)
```

The other one was for auto-rotate.  The same stack trance showed up in our production vault's thread dump.
We took one earlier today when it locked up again.  So auto-rotate will go over all the keys, acquire a write
lock for them before rotating them if required.  See https://github.com/hashicorp/vault/blob/28d81ed8326d2c7d93e2d1707c778dab1e3d02c3/builtin/logical/transit/backend.go#L263.  Right there the auto-rotate thread is blocked because there was a read lock leaked already.
When a thread comes along wanting to read the key, the write lock will prevent it from getting a read lock.
As a result, the thread will block forever.

```
goroutine 843 [sync.RWMutex.Lock, 5 minutes]:
sync.runtime_SemacquireRWMutex(0xc003b56994?, 0x20?, 0xc00477a120?)
        /opt/hostedtoolcache/go/1.21.3/x64/src/runtime/sema.go:87 +0x25
sync.(*RWMutex).Lock(0x32ae73f?)
        /opt/hostedtoolcache/go/1.21.3/x64/src/sync/rwmutex.go:152 +0x6a
github.com/hashicorp/vault/sdk/helper/keysutil.(*Policy).Lock(0xc002df4480, 0xc0?)
        /home/runner/work/vault/vault/sdk/helper/keysutil/policy.go:475 +0x45
github.com/hashicorp/vault/builtin/logical/transit.(*backend).rotateIfRequired(0xc002be1420, {0xb8c7980, 0xc004884000}, 0xc002d74c40, {0xc003b56994, 0x12}, 0xc002df4480)
        /home/runner/work/vault/vault/builtin/logical/transit/backend.go:263 +0x9e
github.com/hashicorp/vault/builtin/logical/transit.(*backend).autoRotateKeys(0xc002be1420, {0xb8c7980, 0xc004884000}, 0xc002d74c40)
        /home/runner/work/vault/vault/builtin/logical/transit/backend.go:251 +0x353
github.com/hashicorp/vault/builtin/logical/transit.(*backend).periodicFunc.func1()
        /home/runner/work/vault/vault/builtin/logical/transit/backend.go:198 +0x35
sync.(*Once).doSlow(0xc0038074b8?, 0x410645?)
        /opt/hostedtoolcache/go/1.21.3/x64/src/sync/once.go:74 +0xbf
sync.(*Once).Do(...)
        /opt/hostedtoolcache/go/1.21.3/x64/src/sync/once.go:65
github.com/hashicorp/vault/builtin/logical/transit.(*backend).periodicFunc(0xc002be1420, {0xb8c7980?, 0xc004884000?}, 0x1?)
        /home/runner/work/vault/vault/builtin/logical/transit/backend.go:201 +0x93
github.com/hashicorp/vault/sdk/framework.(*Backend).handleRollback(0xc0033054a0, {0xb8c7980, 0xc004884000}, 0x0?)
        /home/runner/work/vault/vault/sdk/framework/backend.go:650 +0x5e
github.com/hashicorp/vault/sdk/framework.(*Backend).HandleRequest(0xc0033054a0, {0xb8c7980, 0xc004884000}, 0xc002d74c40)
        /home/runner/work/vault/vault/sdk/framework/backend.go:219 +0x105
github.com/hashicorp/vault/builtin/plugin/v5.(*backend).HandleRequest(0xc003fc2100, {0xb8c7980, 0xc004884000}, 0xc002d74c40)
        /home/runner/work/vault/vault/builtin/plugin/v5/backend.go:95 +0xc6
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc0031ffda0, {0xb8c7980, 0xc004884000}, 0xc002d74c40, 0x0)
        /home/runner/work/vault/vault/vault/router.go:784 +0x1686
github.com/hashicorp/vault/vault.(*Router).Route(...)
        /home/runner/work/vault/vault/vault/router.go:553
github.com/hashicorp/vault/vault.(*RollbackManager).attemptRollback(0xc002eb5680, {0xb8c78d8, 0xc004776330}, {0xc003b0f020, 0x8}, 0xc00477e0f0, 0x1)
        /home/runner/work/vault/vault/vault/rollback.go:309 +0x7b7
github.com/hashicorp/vault/vault.(*RollbackManager).startOrLookupRollback.func1()
        /home/runner/work/vault/vault/vault/rollback.go:228 +0x35
```

This confirms that the fix will fix our problem.  I am attaching a full thread dump from my local reproduction where
auto-rotate was involved.
[dump_stuck_rsa2048.txt](https://github.com/hashicorp/vault/files/14228375/dump_stuck_rsa2048.txt)

What's confusing is the memory addresses of the locks in involved stack traces are not the same.
I think the addresses must be those of the references to the underlying lock.  The address of the backend
object is the same.  I got enough confidence only after a simple local reproduction where it's very easy to
know which threads weren't there to start with.  Also when testing with an rsa-4096 key, there was not
a stack trace in the thread dump where a lock object was involved at all.

**Comment by mju** [comment]
In fact, I also just reproduced this with an rsa-4096 key.  So as soon as I started a local vault server, I started a stop watch.  It locks up right after almost exactly a minute.  After tracing the code for auto-rotate, I found the following default.

```
        c.rollbackPeriod = conf.RollbackPeriod
        if c.rollbackPeriod <= 0 {
                // Default to 1 minute
                c.rollbackPeriod = 1 * time.Minute
        }
```

https://github.com/hashicorp/vault/blob/914482535610c8b087f9e5223a69076f8b0f56f2/vault/core.go#L1233 is the source.

I think in our prod vault and the case where I couldn't reproduce this with an rsa-4096 key, it was because I was too slow or
missed the time.  After an auto-rotate event, we need to wait for an hour.

```
        // Only check for autorotation once an hour to avoid unnecessarily iterating
        // over all keys too frequently.
        if time.Now().Before(b.checkAutoRotateAfter) {
                return nil
        }
        b.checkAutoRotateAfter = time.Now().Add(1 * time.Hour)
```

source: https://github.com/hashicorp/vault/blob/914482535610c8b087f9e5223a69076f8b0f56f2/builtin/logical/transit/backend.go#L218
