### ISSUE TITLE
what does attempting rollback means to the end user

### ISSUE THREAD

**Issue by raoofm** [hashicorp/vault#2533]
v0.7.0 with etcd v3

After init and unseal operations the logs are flooded with below continously

2017/03/27 16:19:48.600377 [TRACE] rollback: attempting rollback: path=auth/token/
2017/03/27 16:19:48.600817 [TRACE] rollback: attempting rollback: path=secret/
2017/03/27 16:19:48.600877 [TRACE] rollback: attempting rollback: path=sys/
2017/03/27 16:19:48.601398 [TRACE] rollback: attempting rollback: path=cubbyhole/

**Comment by jefferai** [comment]
Nothing. But they do mean something to us if we're trying to help debug. That's why they're trace level :-D

**Comment by raoofm** [comment]
@jefferai thanks

**Comment by vikrantymca** [comment]
I am getting these logs on one of the Vault Server. Also I am unable to open its UI. However, another HA vault server gives UI fine.

vault[995]: 2018-09-27T18:15:44.662+0530 [DEBUG] rollback: attempting rollback: path=cubbyhole/
vault[995]: 2018-09-27T18:15:44.662+0530 [DEBUG] rollback: attempting rollback: path=test/
vault[995]: 2018-09-27T18:16:44.662+0530 [DEBUG] rollback: attempting rollback: path=auth/token/
vault[995]: 2018-09-27T18:16:44.662+0530 [DEBUG] rollback: attempting rollback: path=sys/
vault[995]: 2018-09-27T18:16:44.662+0530 [DEBUG] rollback: attempting rollback: path=identity/
vault[995]: 2018-09-27T18:16:44.662+0530 [DEBUG] rollback: attempting rollback: path=consul/
vault[995]: 2018-09-27T18:16:44.662+0530 [DEBUG] rollback: attempting rollback: path=vault/
vault[995]: 2018-09-27T18:16:44.662+0530 [DEBUG] rollback: attempting rollback: path=totp/
vault[995]: 2018-09-27T18:16:44.662+0530 [DEBUG] rollback: attempting rollback: path=cubbyhole/
vault[995]: 2018-09-27T18:16:44.662+0530 [DEBUG] rollback: attempting rollback: path=test/

Logs from the second Vault Server:. Its URL is working fine.
vault[994]: 2018-09-27T16:28:00.281+0530 [DEBUG] core: cannot unseal, not enough keys: keys=1 threshold=3 nonce=**********
vault[994]: 2018-09-27T16:28:16.259+0530 [DEBUG] core: cannot unseal, not enough keys: keys=2 threshold=3 nonce=***********
vault[994]: 2018-09-27T16:28:23.662+0530 [INFO ] core: vault is unsealed
vault[994]: 2018-09-27T16:28:23.662+0530 [INFO ] core: entering standby mode
vault[994]: 2018-09-27T16:28:23.670+0530 [DEBUG] core: parsing information for new active node: active_cluster_addr=https://<IP>:8201 active_redirect_addr=https://<IP>:8200
vault[994]: 2018-09-27T16:28:23.670+0530 [DEBUG] core: refreshing forwarding connection
vault[994]: 2018-09-27T16:28:23.670+0530 [DEBUG] core: clearing forwarding clients
vault[994]: 2018-09-27T16:28:23.670+0530 [DEBUG] core: done clearing forwarding clients
vault[994]: 2018-09-27T16:28:23.670+0530 [DEBUG] core: done refreshing forwarding connection

Please help me with this.

**Comment by v6** [comment]
// , These comments explain what `rollback` means in Vault parlance: 

https://github.com/hashicorp/vault/blob/master/vault/rollback.go#L22-L29

**Comment by raoofm** [comment]
thanks @v6
