### ISSUE TITLE
refresh_interval is not working, always 768h0m0s

### ISSUE THREAD

**Issue by anthonyGuo** [hashicorp/vault#2535]
When write/read from vault, the refesh_interval is always 768h0m0s.
Should this interval reduced as time pass by?

**Comment by anthonyGuo** [comment]
example:
[root@cbam go]# vault read secret/age
Key                     Value
---                     -----
refresh_interval        **768h0m0s**
value                   35

**Comment by jefferai** [comment]
This is explained at https://www.vaultproject.io/docs/secrets/generic/index.html -- it's not a countdown, it's a hint to the client.

**Comment by ahmadalli** [comment]
@jefferai I don't see any info on the docs page about refresh interval
