### ISSUE TITLE
Unable to unseal Vault after Consul backend restarted

### ISSUE THREAD

**Issue by weisinc** [hashicorp/vault#2537]
Vault has been set up with Consul as the backend.
Vault version: 0.6.5
Consul: 0.7.4
Both Vault and Cosul were running fine until Consul was restarted (unintentionally). From that point on, I am not able to unseal Vault again.  No matter the permutation of keys I use, I am only able to unseal with 2 keys. The third key (any one of the reminders) will throw an invalid key error.
After that, I bring down the Vault container, then bring up the Consul server, and then bring up Vault again. By then, vault status is showing vault is not initialized. I basically lost everything, even though Consul has data persisted. Any idea?

Vault log shows the errors below. 

2017/03/27 20:48:41.021349 [ERROR] core: key rotation periodic upgrade check failed: error=Unexpected response code: 500
2017/03/27 20:48:44.323627 [ERROR] core: failed to acquire lock: error=failed to create session: Unexpected response code: 500 (No cluster leader)
2017/03/27 20:49:01.687355 [ERROR] core: failed to acquire lock: error=failed to create session: Unexpected response code: 500 (No cluster leader)
2017/03/27 20:49:02.966140 [WARN ] physical/consul: check unable to talk with Consul backend: error=Unexpected response code: 500 (CheckID "vault:10.0.30.134:8200:vault-sealed-check" does not have associated TTL)
2017/03/27 20:49:03.966713 [WARN ] physical/consul: check unable to talk with Consul backend: error=Unexpected response code: 500 (CheckID "vault:10.0.30.134:8200:vault-sealed-check" does not have associated TTL)
2017/03/27 20:49:04.967488 [WARN ] physical/consul: check unable to talk with Consul backend: error=Unexpected response code: 500 (CheckID "vault:10.0.30.134:8200:vault-sealed-check" does not have associated TTL)
2017/03/27 20:49:05.968109 [WARN ] physical/consul: check unable to talk with Consul backend: error=Unexpected response code: 500 (CheckID "vault:10.0.30.134:8200:vault-sealed-check" does not have associated TTL)
2017/03/27 20:49:06.976409 [WARN ] physical/consul: check unable to talk with Consul backend: error=Unexpected response code: 500 (CheckID "vault:10.0.30.134:8200:vault-sealed-check" does not have associated TTL)
2017/03/27 20:49:14.075977 [ERROR] core: barrier init check failed: error=failed to check for initialization: Unexpected response code: 500
2017/03/27 20:49:17.764727 [INFO ] core: acquired lock, enabling active operation
2017/03/27 20:49:17.766058 [TRACE] core: cluster name not found/set, generating new
2017/03/27 20:49:17.766075 [DEBUG] core: cluster name set: name=vault-cluster-9a26920b
2017/03/27 20:49:17.766082 [TRACE] core: cluster ID not found, generating new
2017/03/27 20:49:17.766089 [DEBUG] core: cluster ID set: id=623769dd-7e3b-4d55-9170-8307e232673e
2017/03/27 20:49:17.766096 [TRACE] core: generating cluster private key
2017/03/27 20:49:17.853988 [TRACE] core: generating local cluster certificate
2017/03/27 20:49:18.100878 [WARN ] physical/consul: Concurrent state change notify dropped
2017/03/27 20:49:18.100897 [INFO ] core: post-unseal setup starting
2017/03/27 20:49:18.147351 [INFO ] core: pre-seal teardown starting
2017/03/27 20:49:18.147367 [INFO ] core/stopClusterListener: listeners not running
2017/03/27 20:49:18.147376 [INFO ] core: pre-seal teardown complete
2017/03/27 20:49:18.147389 [ERROR] core: post-unseal setup failed: error=keyring unexpectedly missing
2017/03/27 20:49:18.303433 [INFO ] core: acquired lock, enabling active operation
2017/03/27 20:49:18.314287 [TRACE] core: generating cluster private key
2017/03/27 20:49:18.366149 [TRACE] core: generating local cluster certificate
2017/03/27 20:49:18.658714 [WARN ] physical/consul: Concurrent state change notify dropped
2017/03/27 20:49:18.658743 [INFO ] core: post-unseal setup starting
2017/03/27 20:49:18.662595 [INFO ] core: pre-seal teardown starting
2017/03/27 20:49:18.662614 [INFO ] core/stopClusterListener: listeners not running
2017/03/27 20:49:18.662629 [INFO ] core: pre-seal teardown complete
2017/03/27 20:49:18.662644 [ERROR] core: post-unseal setup failed: error=keyring unexpectedly missing
2017/03/27 20:49:18.679316 [INFO ] core: acquired lock, enabling active operation
2017/03/27 20:49:18.679873 [TRACE] core: generating cluster private key
2017/03/27 20:49:18.856196 [TRACE] core: generating local cluster certificate
2017/03/27 20:49:19.073356 [WARN ] physical/consul: Concurrent state change notify dropped
2017/03/27 20:49:19.073373 [INFO ] core: post-unseal setup starting
2017/03/27 20:49:19.074383 [INFO ] core: pre-seal teardown starting
2017/03/27 20:49:19.074392 [INFO ] core/stopClusterListener: listeners not running

**Comment by jefferai** [comment]
This seems to be the problem:

2017/03/27 20:49:01.687355 [ERROR] core: failed to acquire lock: error=failed to create session: Unexpected response code: 500 (No cluster leader)

You don't have a Consul cluster leader, so the data is not available. You need to resolve the Consul outage before Vault can access its data.

**Comment by weisinc** [comment]
The Consul cluster outage was a human mistake. It was brought down for an upgrade and the impacted parties were not informed.
I can understand Vault "failed to acquire lock: error=failed to create session" during the outage, but when Consul was brought back up, Vault still was not able to connect to the Consul backend. Worse, when I restarted Vault after that, vault status came back with Vault was not initialized. At that point, it appears all the data was lost... Consul does has persisted storage.

**Comment by jefferai** [comment]
@weisinc I think you're not quite following what I'm saying. The error that Vault is giving is saying that Consul is in a bad state. Not that it's currently down from a network perspective, but that it has no quorum so cannot service requests. If you fix your Consul cluster Vault should work again, depending on what's wrong (e.g. if you have a split brain because you have an even number of Consul nodes then there's a possibility of bad things).

**Comment by weisinc** [comment]
ok. i got it. I will dig further into the Consul cluster issue. THanks!

**Comment by emirhosseini** [comment]
@weisinc Did you get a resolution?
