### ISSUE TITLE
Searching for Solutions for Vault's Auto-Unseal Transit without Using Third-Party Cloud Services

### ISSUE THREAD

**Issue by Haythem42** [hashicorp/vault#25380]
Hello everyone,

I am currently working on implementing a central Vault server within a Kubernetes cluster, intended to serve as a key provider to automate the unseal process for other Vault instances deployed in the same cluster. My goal is to simplify this process by making it fully automatic, thus eliminating the need for manual intervention to unlock Vault instances.

As part of this project, I followed the tutorial available at: [Vault Auto-Unseal Using Transit Secret Engine on Kubernetes](https://luafanti.medium.com/vault-auto-unseal-using-transit-secret-engine-on-kubernetes) to install and configure the central Vault server via Helm. This guide was invaluable for the initial setup but fell short of achieving complete process automation for unseal. In an attempt to go further, I explored the use of the postStart function based on [Vault's official GitHub](https://github.com/hashicorp/vault-helm/blob/50f7439fb298d98a223d2fdf58ece2bad2d816bc/values.yaml#L572) documentation, without achieving a functional solution.

Beyond these attempts, I am looking to see if other community members have successfully set up a similar system without resorting to third-party services like Google KMS or AWS KMS, preferring a self-hosted approach for the key manager.

Moreover, I am interested in exploring the use of tools such as GitLab for CI/CD and [Flux](https://fluxcd.io/flux/guides/sealed-secrets/) for GitOps, aiming to further automate the Vault installation and unseal process. I wonder if anyone has integrated these tools into a similar automation strategy or could offer advice on how to effectively use them in this context.

Here are the specific points on which I am seeking feedback and advice:
1. Experiences and examples of setting up an internal or self-hosted auto-unseal mechanism for Vault, without depending on third-party cloud services.
2. Advice on using GitLab or Flux to automate the installation and unseal process of Vault in a Kubernetes environment.
3. Documentation, guides, or any other resources that could assist in implementing a custom and secure auto-unseal solution for Vault.

I am open to any suggestions, advice, or caution based on your personal experiences. My goal is to build a robust and secure solution that respects our constraints and our desire for independence from third-party cloud service providers.

Thank you in advance for your time and valuable assistance.

Best regards

**Comment by ccapurso** [comment]
Hi, @Haythem42. Thank you for your interest in Vault! We reserve GitHub issues for bug reports and feature requests, which this doesn't appear to be. As such, I'm going to close this but suggest that you ask about this on the [Vault Discuss](https://discuss.hashicorp.com/c/vault/30) page as you might be able to receive feedback there.
