### ISSUE TITLE
Vault Backend add reference

### ISSUE THREAD

**Issue by FinalDes** [hashicorp/vault#2538]
I don't recognize some of backend product vault support.
May you guys add the reference on vault backend support?

Thx

**Comment by vishalnayak** [comment]
@FinalDes Sorry, I don't understand your question properly. Do you mean which storage backends are supported by Vault? If yes, they can be found here: https://www.vaultproject.io/docs/configuration/storage/index.html.

**Comment by FinalDes** [comment]
I mean secret backends.
In secret backends don't have reference link to the supported product.
I don't recognize product like Transit and cubbyhole

**Comment by jefferai** [comment]
@FinalDes Those aren't products. Those are capabilities within Vault itself. Vault does a lot...

**Comment by FinalDes** [comment]
I see @jefferai

**Comment by jefferai** [comment]
That's what the help pages are there for. They describe what the capability does and how to use it.

**Comment by FinalDes** [comment]
@jefferai in help page don't explain much about Transit and cubbyhole

**Comment by jefferai** [comment]
@FinalDes If you have specific questions, please ask them on the mailing list.
