### ISSUE TITLE
Different results with golang API , curl and CLI

### ISSUE THREAD

**Issue by nlamirault** [hashicorp/vault#2539]
Hi,
i try to retrieve secret Data using golang API : 

ns is like : "secret/app/cuid"

```go
secret, err := vs.Client.Logical().Read(ns)
if err != nil {
	return nil, grpc.Errorf(codes.Unauthenticated, err.Error())
}
glog.V(2).Infof("Vault data: %s", secret.Data)
```

Result : 

```
Vault data: map[apikey:0b685a13-14c7-43fe-808a-32df376e7dab]
```

With *curl* : 

```bash
$ curl -k -X GET https://vault:8200/v1/secret/app/XXXXXXXX -H "X-Vault-Token: e7ad58da-a958-c9e7-0289-760e12aabb09"  
{"request_id":"7b79794f-c107-77f4-c983-74e0bb8efb85","lease_id":"","renewable":false,"lease_duration":28800,"data":{"apikey":"e219242c-307d-4b2c-b890-a9456dcc2cac","cuid":"xxxxxxxxx","name":"xxxxxxxxxxxxxxxx"},"wrap_info":null,"warnings":null,"auth":null}

```

With the CLI : 

```bash
$ vault read -tls-skip-verify secret/app/XXXXXXXX
Key                     Value
---                     -----
refresh_interval        8h0m0s
apikey                  e219242c-307d-4b2c-b890-a9456dcc2cac
cuid                    xxxxxxx
name                    xxxxxxxxxxxxx
```

Where is my error using the golang API ?
Any idea ?
Thanks.

**Comment by jefferai** [comment]
My *guess* is that it's not that you aren't getting all of the data back, it's that something in your printing function isn't displaying it. What if you use `%#v` instead of `%s`?

**Comment by nlamirault** [comment]
Using  
```go
glog.V(2).Infof("Vault data: %#v", secret.Data)
```

```
Vault data: map[string]interface {}{"apikey":"0b685a13-14c7-43fe-808a-32df376e7dab"}
```

**Comment by jefferai** [comment]
I'm honestly not sure, but I do want to point out that the Vault CLI is just a consumer of the client, and the `read` command is doing what you are: https://github.com/hashicorp/vault/blob/master/command/read.go#L50

Is there any chance that your API client is using a different vault address or something? Or `ns` is not the path you think it is?

**Comment by nlamirault** [comment]
OK. I will check that. This must come from a namespace problem.
