### ISSUE TITLE
ha mode - etcd v3 - standby never becomes active when the active goes down

### ISSUE THREAD

**Issue by raoofm** [hashicorp/vault#2540]
vault 0.7.0
etcd 3.1.3

when /v1/sys/step-down is called on the active node then the standby replaces it as active but if you actually kill the active node then the standby nodes never takes over.

Expected behavior is 
If you kill Vault without letting it release the lock, a standby node will not be able to take over until the lock's timeout period has expired. This is backend-specific but could be ten seconds or more.

I checked etcdv3 backend and it shows 15s but it doesn't seem to work.

In a real world scenario, HA mode is used for sudden loss of a server and not for planned step-down (used only during upgrades).

**Comment by raoofm** [comment]
@jefferai @xiang90 ?

**Comment by jefferai** [comment]
This should be fixed by https://github.com/hashicorp/vault/pull/2526

**Comment by raoofm** [comment]
great, thanks
