### ISSUE TITLE
can tls be disabled if vault cluster is behind a kubernetes service

### ISSUE THREAD

**Issue by raoofm** [hashicorp/vault#2543]
The idea is to have a vault HA cluster deployed using kubernetes and expose it using an aws elb on ssl. It will use etcd v3 backend. etcd is using ssl, so vault will talk to etcd on ssl but i think it is safe to disable tls for vault when we are not exposing the actual containers. Apps will talk to vault via elb and HA will work based on forwarding (not redirection, and will not get into a loop)

@jefferai thoughts?

**Comment by jefferai** [comment]
@raoofm To be honest I'm not entirely sure what the question is. What you're proposing should be decided based on your organizational security policy (e.g. whether end-to-end encryption is required, including whether it's allowable for an ELB to decrypt sessions), which may in turn be based on industry requirements (PCI3, SOX, etc.).

**Comment by raoofm** [comment]
@jefferai thanks for your feedback.

Yes, we will be going e2e ssl, with certs at elb and self signed at pods.

**Comment by jefferai** [comment]
@raoofm You realize that's not e2e right?

**Comment by raoofm** [comment]
@jefferai why not? because elb is decrypting and re-encrypting

**Comment by raoofm** [comment]
is there a better option?

**Comment by raoofm** [comment]
@jefferai I did the way end-to-end explained here
http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/using-elb-listenerconfig-quickref.html

**Comment by jefferai** [comment]
TCP proxying is the only way to have true E2E encryption if you are required to have that between client and service.

**Comment by raoofm** [comment]
@jefferai agree, but to get a cert from a trusted ca at deployment time is difficult considering that we are deploying using kubernetes and the ip/hostname are unknown. So we are getting a cert for elb from a trusted ca and are having self signed for the instances.

**Comment by jefferai** [comment]
Just wanted you to be aware of it in case it's a regulation you need to comply with!

**Comment by raoofm** [comment]
@jefferai agree :+1:
