### ISSUE TITLE
Vault CLI KV2 undelete still fails for multi-level paths

### ISSUE THREAD

**Issue by loicgreffier** [hashicorp/vault#25506]
**Describe the bug**
Vault CLI still fails to properly handle KV-V2 undelete commands when the KV-V2 backend is mounted under a path that has multiple levels (e.g., /secrets/demo)

The following issue has been raised and merged https://github.com/hashicorp/vault/issues/19810. However, the bug seems still here in Vault CLI v1.15.5. 

**To Reproduce**
```bash
vault kv put -mount=apps/kv mySecret username=myUsername
vault kv delete -mount=apps/kv mySecret
vault kv undelete -mount=apps/kv/ -versions=1 mySecret

Error writing data to kv/undelete/mySecret: Error making API request.

URL: PUT https://vault.domain.com/v1/kv/undelete/mySecret
Code: 404. Errors:

* no handler for route "kv/undelete/mySecret". route entry not found.
```

The mount path has been truncated.

**Expected behavior**
Vault CLI should properly handle the undelete operation.

The operation ends properly when not using the `-mount` option

```bash
vault kv undelete -versions=1 /apps/kv/mySecret
Success! Data written to: apps/kv/undelete/mySecret
```

**Environment:**
* Vault Server Version (retrieve with `vault status`):

```
Key                      Value
---                      -----
Seal Type                azurekeyvault
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    5
Threshold                3
Version                  1.15.5
Build Date               2024-01-26T14:53:40Z
Storage Type             raft
Cluster Name             ***
Cluster ID               ***
HA Enabled               true
HA Cluster               ***
HA Mode                  active
Active Since             2024-02-15T08:33:37.222546289Z
Raft Committed Index     228038
Raft Applied Index       228038
```

* Vault CLI Version (retrieve with `vault version`):

```
Vault v1.15.5 (0d8b67ef63815f20421c11fe9152d435af3403e6), built 2024-01-26T14:53:40Z
```

* Server Operating System/Architecture:

```
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
```

**Additional context**

https://github.com/hashicorp/vault/issues/19810 has been merged on `main` but I cannot find it in any release note. Do I miss anything ?

**Comment by peteski22** [comment]
Hi @loicgreffier thanks for the report, the repro steps and linked issue made it easy to follow.

https://github.com/hashicorp/vault/pull/19811 fixes the [issue you mentioned](https://github.com/hashicorp/vault/issues/19810), you are right that it has merged to `main` but isn't being backported to previous versions of Vault, it will be present in the next upcoming major release (`1.16.0`).

I hope this helps 😄
