### ISSUE TITLE
SSH CA: key_cert_check_authority: invalid certificate

### ISSUE THREAD

**Issue by rgruyters** [hashicorp/vault#2551]
I'm trying to setup SSH CA in my testenvironment. I have two servers both running Ubuntu latest LTS release, 16.04, and Vault 0.7 running on one of the servers.
ubuntu-01 in my is the remote server and ubuntu-02 is the client server.

I have generated with Vault the host CA key and added to both servers in the `/etc/ssh/ssh_known_hosts` with `@cert-authority *.local` in front of it. Then signed the host public rsa key, https://www.vaultproject.io/docs/secrets/ssh/index.html#sign-the-host-key, from ubuntu-01 and added `HostCertificate /etc/ssh/ssh_host_rsa-signed.pub`.
Tested if the host CA works and that is fine. No prompt to validate the host key.

Then I have generated with Vault the client CA key and added it to a file `/etc/ssh/ssh_trusted_keys.pub` on ubuntu-01. Then I have updated the `/etc/ssh/sshd_config` to add `TrustedUserCAKeys /etc/ssh/ssh_trusted_keys.pub` on ubuntu-01.

Last but not I have signed my own public key by following the step, https://www.vaultproject.io/docs/secrets/ssh/index.html#sign-the-client-key.

When I try to SSH to ubuntu-01 it prompts for password:
```
$ ssh -i .ssh/id_rsa-cert.pub ubuntu-01.local
robin@ubuntu-01.local's password:
```
If I check the `/var/log/auth.log` I see the following message:
```
Mar 31 16:25:31 ubuntu-01 sshd[31673]: error: key_cert_check_authority: invalid certificate
Mar 31 16:25:31 ubuntu-01 sshd[31673]: error: Certificate lacks principal list
```

Here is an example output from my client signed certificate:
```
/home/robin/.ssh/id_rsa-cert.pub:
        Type: ssh-rsa-cert-v01@openssh.com user certificate
        Public key: RSA-CERT SHA256:9VVqnVfawhep3fRvIGqYo3xzfDRBSM6lc8YSdo7AAFg
        Signing CA: RSA SHA256:ztCKB9ABd3q8jkg/pYuzODUPiSb90jUWyZ336fX8yRA
        Key ID: "vault-token-f5556a9d57dac217a9ddf46f206a98a37c737c344148cea573c612768ec00058"
        Serial: 11944418524940432690
        Valid: from 2017-03-31T16:24:56 to 2017-03-31T16:30:26
        Principals: (none)
        Critical Options: (none)
        Extensions: (none)
```

**Comment by jefferai** [comment]
Can you list the Vault API calls and/or command line calls you're making? Indeed the certificate has no principals but it should be getting them from args -- but possibly you're not supplying them and there's a check missing that should ensure that one or more have actually been supplied.

**Comment by rgruyters** [comment]
I have installed two clean testservers to make sure that nothing came from other installations.

```
robin@ubuntu:~/vault$ vault mount -path ssh-host-signer ssh
Successfully mounted 'ssh' at 'ssh-host-signer'!
robin@ubuntu:~/vault$ vault mount -path ssh-client-signer ssh
Successfully mounted 'ssh' at 'ssh-client-signer'!
robin@ubuntu:~/vault$ vault write -f -field=public_key ssh-host-signer/config/ca | sudo tee /etc/ssh/ssh_known_hosts
robin@ubuntu:~/vault$ vault write -f -field=public_key ssh-client-signer/config/ca > users_ca.pub
```

Copied the `users_ca.pub` to remote host in `/etc/ssh/users_ca.pub`.

```
robin@ubuntu:~/vault$ vault mount-tune -max-lease-ttl=87600h ssh-host-signer
Successfully tuned mount 'ssh-host-signer'!
robin@ubuntu:~/vault$ vault write ssh-host-signer/roles/hostrole ttl=87600h allow_host_certificates=true key_type=ca
Success! Data written to: ssh-host-signer/roles/hostrole
robin@ubuntu:~/vault$ vault write ssh-client-signer/roles/clientrole allow_user_certificates=true ttl=5m key_type=ca
Success! Data written to: ssh-client-signer/roles/clientrole
```

Copied the `ssh_host_rsa_key.pub` from the other host and:
```
robin@ubuntu:~/vault$ cat ssh_host_rsa_key.pub | vault write -field=signed_key ssh-host-signer/sign/hostrole public_key=- cert_type=host > ssh_host_rsa_key-cert.pub
```
Copied the output file back to remote host to `/etc/ssh/ssh_host_rsa_key-cert.pub` and added to entries to the `/etc/ssh/sshd_config` on the remote host:
```
TrustedUserCAKeys /etc/ssh/users_ca.pub
HostCertificate /etc/ssh/ssh_host_rsa_key-cert.pub
```
Restarted the sshd process.
Last but not leased:
```
robin@ubuntu:~/vault$ ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/home/robin/.ssh/id_rsa): 
Created directory '/home/robin/.ssh'.
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /home/robin/.ssh/id_rsa.
Your public key has been saved in /home/robin/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:cFp7yXdJ1DKaIdGm/pIP8vNFuS0LsFBWojwah7lODL4 robin@ubuntu
The key's randomart image is:
+---[RSA 2048]----+
|          oo. .. |
|       + ..o+.o .|
|    . = B o+ +.o |
|   . o X *..o. o |
|    . * S.= . =  |
|     +   o.+ o o |
|    E . . oo. + .|
|         o+..o o |
|          .=o .  |
+----[SHA256]-----+
robin@ubuntu:~/vault$ cat ~/.ssh/id_rsa.pub | vault write -field=signed_key ssh-client-signer/sign/clientrole public_key=- > ~/.ssh/id_rsa-cert.pub
```
robin@ubuntu:~/vault$ ssh -i ~/.ssh/id_rsa-cert.pub ubuntu-01.local
robin@ubuntu-01.local's password: 
```

**Comment by jefferai** [comment]
@rgruyters Your output got truncated, probably due to mismatched formatting? ^

**Comment by rgruyters** [comment]
@jefferai what do you mean? the above output looks fine to me. As in I can read all the commands and output perfectly.

**Comment by rgruyters** [comment]
@jefferai you said:
> Indeed the certificate has no principals but it should be getting them from args

Which args do I need to supply to fill in the correct principals? The Vault documentation doesn't explain this:
https://www.vaultproject.io/docs/secrets/ssh/index.html#sign-the-client-key

**Comment by rgruyters** [comment]
There is the option `valid_principals` for signing, but then I get:
```
robin@ubuntu:~/vault$ cat ~/.ssh/id_rsa.pub | vault write -field=signed_key ssh-client-signer/sign/clientrole public_key=- valid_principals=robin > ~/.ssh/id_rsa-cert.pub
Error writing data to ssh-client-signer/sign/clientrole: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/ssh-client-signer/sign/clientrole
Code: 400. Errors:

* role is not configured to allow any principles
```

**Comment by rgruyters** [comment]
Last but not least, I also tried to update the clientrole to allow a specific user.
```
robin@ubuntu:~/vault$ vault write ssh-client-signer/roles/clientrole allow_user_certificates=true ttl=5m key_type=ca allowed_users=robin
Success! Data written to: ssh-client-signer/roles/clientrole
```

Then add a `valid_principals=robin` when signing a public key from the user. This looks more promising, although still not able to login remotely without user password.
```
robin@ubuntu:~/vault$ ssh -i ~/.ssh/id_rsa-cert.pub ubuntu-01.local
Enter passphrase for key '/home/robin/.ssh/id_rsa-cert.pub': 
robin@ubuntu-01.local's password: 
Permission denied, please try again.
robin@ubuntu-01.local's password: 
Permission denied, please try again.
robin@ubuntu-01.local's password: 
Permission denied (publickey,password).
robin@ubuntu:~/vault$ 
```

**Comment by dwannamaker-onr** [comment]
I know this is no help, but I can at least confirm the same problem with my setup.  By adding the default_user and allowed_users to my clientrole, I no longer get the Certificate lacks principal list error.  However, I still get prompted for a password.  Also I now additionally get prompted for the certificate passphrase.

- I have the /etc/ssh/ssh_known_hosts file on both the client and remote side with the Host CA key prepended with @cert-authority * ssh-rsa AAAAblahblah.

- I have copied the host's ssh_host_rsa_key.pub from the remote system back to my Vault client system and signed it with the host signer and put the signed ssh_host_rsa_key-cert.pub back on the remote system and referenced it with the HostCertificate directive.  

- And also the Client CA is referenced with the TrustedUserCAKeys directive.

**Comment by jefferai** [comment]
I'm making some minor headway on this. I think there are two problems here:

1) The documentation for the CA bits is misleading in several places
2) There is a bug in OpenSSH 7.2-7.4 that makes it really hard to actually get valid things working properly, which was not in OpenSSH 7.1 and earlier, so whether this works is going to be partly dependent on the OS. See https://bugzilla.mindrot.org/show_bug.cgi?id=2617

At this point I may try doing this on a distro with 7.1 or 7.5 to not have to figure out whether what's going wrong is that bug or not, because I do seem to be hitting that bug in multiple combinations.

**Comment by jefferai** [comment]
Hi, I've extensively updated the SSH CA docs; they will be live on the website in a few minutes. I think this should help quite a lot with the confusion here. Please respond back if there are still problems!

**Comment by dwannamaker-onr** [comment]
The updated docs did the trick!  I am able to authenticate into the host system now using the CA type.   Nice work.  Thanks!

**Comment by jefferai** [comment]
No problem! Glad it helped.

**Comment by rgruyters** [comment]
Yes, it is working for me. Thanks!! It makes more sense now.
