### ISSUE TITLE
Non-portable cert file names for pki backend (colon characters in CIFS mount)

### ISSUE THREAD

**Issue by saikatguha** [hashicorp/vault#2552]
I have the data folder mounted using CIFS. 
unix filename translation is not supported in my environment. 
The PKI backend attempts to write the cert to file: `logical/<guid>/certs/_33:d2:80:....`
Due to colon characters in the name, the file creation fails, and the PKI backend doesn't work.

It should be possible to use characters that are portable across platforms.

**Comment by jefferai** [comment]
Related to https://github.com/hashicorp/vault/pull/2203
