### ISSUE TITLE
vault healthchecks going haywire with consul backend

### ISSUE THREAD

**Issue by jeroenjacobs1205** [hashicorp/vault#2556]
I have a Consul cluster consisting of 3 servers: consul01, consul02, consul03. This cluster is working fine.

I decided to install Vault on the same machines, using the Consul backend. This is my config file:

```
storage "consul" {
  address = "consul.service.consul:8500"
  path = "vault"
}

listener "tcp" {
 address = "0.0.0.0:8200"
 tls_disable = 1
}
```

However, the vault healthchecks are completely messed up after I unsealed the Vault for the first time:

```
NODES

consul01 192.168.60.17 1 failing
Serf Health Status serfHealth passing
Vault Sealed Status vault:192.168.60.17:8200:vault-sealed-check critical

consul02 192.168.60.18 2 passing
Serf Health Status serfHealth passing
Vault Sealed Status vault:192.168.60.17:8200:vault-sealed-check passing

consul02 192.168.60.18 1 failing
Serf Health Status serfHealth passing
Vault Sealed Status vault:192.168.60.18:8200:vault-sealed-check critical

consul03 192.168.60.19 1 failing
Serf Health Status serfHealth passing
Vault Sealed Status vault:192.168.60.19:8200:vault-sealed-check
```

Note how consul02 is suddenly listed twice, also it lists a healthcheck for a different server?

The Vault was unsealed on consul01. There it reports that the Vault is indeed unsealed when I check it on the server directly:

```
[jeroen@consul01 vault]$ ./vault status -address=http://localhost:8200
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0
Unseal Nonce: 
Version: 0.7.0
Cluster Name: vault-cluster-c2967ff1
Cluster ID: 649d3bda-9077-93bf-c4f1-f8ac84f2b79d

High-Availability Enabled: true
        Mode: active
        Leader: http://192.168.60.17:8200

```

**Comment by jefferai** [comment]
Health checks are local to an agent. By pointing Vault directly at the Consul servers if it transitions which service address it resolves to the new agent will get the same health check (note how the IP addresses are different). You should remove those checks and point Vault to the local agent, e.g. 127.0.0.1:8500, and that should fix it.

**Comment by jeroenjacobs1205** [comment]
Pointing to the local agent worked. Thanks! :-)
