### ISSUE TITLE
Token renew is not working with Periodic option.

### ISSUE THREAD

**Issue by shantanudas37** [hashicorp/vault#2560]
Hi Team,

I'm Authenticating against AppRole configured with period as 6m. Please find the below steps.

Creating AppRole:
vault write auth/approle/role/testrole period=6m

testrole.hcl:
# Allow creating tokens under "nomad-cluster" token role. The token role name
# should be updated if "nomad-cluster" is not used.
path "auth/token/create/testrole" {
  capabilities = ["update"]
}

# Allow looking up "nomad-cluster" token role. The token role name should be
# updated if "nomad-cluster" is not used.
path "auth/token/roles/testrole" {
  capabilities = ["read"]
}

# Allow looking up the token passed to Nomad to validate # the token has the
# proper capabilities. This is provided by the "default" policy.
path "auth/token/lookup-self" {
  capabilities = ["read"]
}

# Allow looking up incoming tokens to validate they have permissions to access
# the tokens they are requesting. This is only required if
# `allow_unauthenticated` is set to false.
path "auth/token/lookup" {
  capabilities = ["update"]
}

# Allow revoking tokens that should no longer exist. This allows revoking
# tokens for dead tasks.
path "auth/token/revoke-accessor" {
  capabilities = ["update"]
}

# Allow checking the capabilities of our own token. This is used to validate the
# token upon startup.
path "sys/capabilities-self" {
  capabilities = ["update"]
}

# Allow our own token to be renewed.
path "auth/token/renew-self" {
#  policy = "write"
  capabilities = ["update"]
}

After 6m token renewal is not happening and getting below error

-bash-4.1$ vault auth $VAULT_TOKEN
==> WARNING: VAULT_TOKEN environment variable set!

  The environment variable takes precedence over the value
  set by the auth command. Either update the value of the
  environment variable or unset it to use the new token.

Error validating token: Error making API request.

URL: GET http://**.**.**.**:8200/v1/auth/token/lookup-self
Code: 403. Errors:

* permission denied

Please let me know where i have missed.

Thanks,
shantanu

**Comment by vishalnayak** [comment]
@shantanudas37 Renewal should be done *before* 6m and not after.

**Comment by jefferai** [comment]
Working as designed; if the period runs out the token is revoked as expected. As @vishalnayak said, you must renew before then, not after.

**Comment by shantanudas37** [comment]
Thanks for the update.

By using period option whether the token renewed automatically or manually the renewal command "vault write -f /auth/token/renew-self" should be executed before 6m.

Please confirm once and let me know your commands.

**Comment by vishalnayak** [comment]
@shantanudas37 Tokens are not renewed automatically. Clients need to renew them. The command you are using should do it if you are authenticated with the token that needs renewal. If not, you could use this API `/auth/token/renew</token>`. Please see https://www.vaultproject.io/docs/auth/token.html for more details.

**Comment by vishalnayak** [comment]
Also, if you use the API `/auth/token/renew[/token]`, be sure to put the token in the request body and not the URL.

**Comment by shantanudas37** [comment]
HI vishalnayak,
Thanks for the above information.
Could please give provide the information on below question.

Is any option to renew the token automatically before it expires?

Thanks,
Bala

**Comment by vishalnayak** [comment]
@shantanudas37 No and it is by design. Renewals should be done client side.
