### ISSUE TITLE
Vault and Nomad Integration with a Consul backend

### ISSUE THREAD

**Issue by ptarpan** [hashicorp/vault#2563]
Hello,
I have read through the Vault Integration doc (https://www.nomadproject.io/docs/vault-integration/) but am still unclear on the required setup to integrate Vault with Nomad and a Consul backend.  

FYI, we already have the following set up: 
```
- Consul (3-node cluster) 
- Nomad (3 x master and 3 x worker node clusters) 
- Vault (server) running on two out of the three Consul nodes  
- Vault root token
```
I am struggling to find where to go next. The end goal is to submit Nomad jobs that accepts Vault policies either at the Job, Group, or Task level which then reads/writes from/to Consul. Could you point me to some documentation on how to move forward with this setup?

**Comment by jefferai** [comment]
Hi @ptarpan ,

Please contact the Nomad team for help with the integration -- we make Vault, but don't really have as deep understanding of the setup they're using on top.
