### ISSUE TITLE
Provide upsert capabilities for key/value pairs

### ISSUE THREAD

**Issue by VinayMadyalkar** [hashicorp/vault#2564]
`$ vault write secret/test x=1`
This puts the key-value pair x=1 in 'test' namespace.

Then I want to upsert(update if available , insert if missing)
`$ vault write secret/test y=2`
We will lose the x=1 key-value pair and it will be overwritten with y=2.
It would be great if it vault provided 'upsert' kind of capability.
As a workaround for this, we can read the value in the namespace and check if the 'key' exists, if yes; update, else insert. But this is a 2 step process, which is not 'atomic' in nature.

Thoughts?

**Comment by jefferai** [comment]
This has been discussed a number of times over the years but for now we are not planning to implement this, sorry.
