### ISSUE TITLE
SSH Map Fields

### ISSUE THREAD

**Issue by jamestutton** [hashicorp/vault#2569]
Hopefully this is a simple lack of understanding but read every doc I can find and seem to be missing something fundamental or there is a bug so either way hopefully asking a stupid question will help someone else in future making the same mistake.

Im trying to ultimately create a ssh user signed key with the permit-pty extention.  But i'm failing to understand how you pass a map string.

The closest i have got is:
vault write ssh-client-signer/roles/clientrole @data.json

data.json
`{
		"allow_bare_domains": false,
		"allow_host_certificates": false,
		"allow_subdomains": false,
		"allow_user_certificates": true,
		"allow_user_key_ids": false,
		"allowed_critical_options": "",
		"allowed_domains": "",
		"allowed_extensions": "",
		"allowed_users": "*",
		"default_critical_options": {},
		"default_extensions": [{
      "permit-pty":""
    }],
		"default_user": "",
		"key_type": "ca",
		"max_ttl": "768h0m0s",
		"ttl": "5m0s"
	}`

which seems to work 
(Not quite happy with the the fact i have to pass KEY :"" to something that never holds a value but maybe there is a better way.)

but is there a way to pass map values in via the cli without resorting to external json.

`vault write ssh-client-signer/roles/clientrole allow_user_certificates=true ttl=5m key_type=ca default_extensions=[{"permit-X11-forwarding":""}]`

I get back * Error converting input [{"permit-X11-forwarding":""}] for field default_extensions: '' expected a map, got 'string'

Escaping the " in various ways seems to make no difference.

What am i missing as can find no examples in any of the docs to parsing map values via the CLI.  Or is it just not possible?

Also is the above structure correct.  My experience tells me it should be of the form below but that errors and im new to go and no json expert.

["permit-pty","permit-X11-forwarding","...."]

**Comment by jefferai** [comment]
> (Not quite happy with the the fact i have to pass KEY :"" to something that never holds a value but maybe there is a better way.)

I don't understand what you're saying here?

> but is there a way to pass map values in via the cli without resorting to external json.

No, there is not.

**Comment by jamestutton** [comment]
Thanks jefferai the main one was fighting to pass them via the CLI as assumed there must have been a way.  

As for the  KEY :"" bit.  The ssh extensions as far as I could tell from ssh docs online for CA's  were all basic string values eg:

    permit-X11-forwarding
    permit-agent-forwarding
    permit-port-forwarding
    permit-pty
    permit-user-rc

rather than key value pairs. hence could see the need for the value part.  Have since found this doc

[https://www.ietf.org/mail-archive/web/secsh/current/msg00327.html]

which has the source address field so now understand the reason for it being a key,value pair not just a value list.

But hopefully me asking the question will help other in the future.  And a note somewhere about map values and not working from cli may help as well.

**Comment by cmcniel** [comment]
I am also working on this as we are building an application and I would like to be able to pass in the extensions/critical options with a JSON payload during ssh key signing.  I can get a signed key but using ssh-keygen -L -f <mykey> I get the following in various forms depending on how I attempt to pass in the extension.

        Extensions:
                no-pty UNKNOWN OPTION (len 0)
                no-user-rc UNKNOWN OPTION (len 0)
An example payload for signing and/or creating the defaults would be a huge help.

Thanks

**Comment by jamestutton** [comment]
Hi Cmcniel,

I dont think there is such a value in the ssh spec.  from the doc i linked previously:

> permit-pty              empty         Flag indicating that PTY allocation
>                                                    should be permitted. In the absence of
>                                                    this constraint PTY allocation will be
>                                                    disabled.

so the default is in effect no pty and you have to explicitly allow it.

As for the json format the one below now works for me.  If still having issues and get time will do a full step by step have it working to a point now.

`cat role.json
{
        "allow_bare_domains": false,
        "allow_host_certificates": false,
        "allow_subdomains": false,
        "allow_user_certificates": true,
        "allow_user_key_ids": false,
        "allowed_critical_options": "",
        "allowed_domains": "",
        "allowed_extensions": "",
        "allowed_users": "*",
        "default_critical_options": {},
        "default_extensions": [{
              "permit-agent-forwarding":"",
              "permit-port-forwarding":"",
              "permit-pty":"",
              "permit-user-rc":""
         }],
        "default_user": "",
        "key_type": "ca",
        "max_ttl": "768h0m0s",
        "ttl": "24h"
        }
`

**Comment by jefferai** [comment]
Hi, I've extensively updated the SSH CA docs; they will be live on the website in a few minutes. I think this should help quite a lot with the confusion here. Please respond back if there are still problems!

**Comment by jamestutton** [comment]
Updates look good only one I would suggest adding for completeness of all being in one place and for people new to ssh singed keys is the use of 

`ssh-keygen -Lf id_rsa-cert.pub` 

as it will show the extensions have works the time validity of the cert etc. Helps in debugging

**Comment by jefferai** [comment]
Added!

**Comment by FernandoMiguel** [comment]
@jamestutton so i'm guessing you never found a way to pass permit-pty via CLI and instead created a json for the all thing?

**Comment by ixe013** [comment]
@FernandoMiguel you can use a "here file" like this : 

```bash
vault write ssh-client-signer/roles/clientrole - << "EOF"
{
  "default_extensions": [
    {
      "permit-pty": ""
    }
  ],
  "key_type": "ca",
  "ttl": "30m",
  "zzzdefault_user": "ubuntu",
  "allow_user_certificates": true,
  "allowed_users": "*"
}
EOF
```

Beware that the EOF ends the line with no trailing spaces.
