### ISSUE TITLE
Need to revoke all tokens but root token for cleanup...

### ISSUE THREAD

**Issue by Kbooth-rms** [hashicorp/vault#2576]
We have an issue where our vault clients were requesting tokens at a massive rate, and they have a long TTL.  Vault seems to be randomly crashing and we think that it's because of the large number of tokens.

Also, when the vault service restarts, it takes about 30 mins as it iterates through the tokens before it becomes responsive.

Is there any way to just blanket revoke all tokens *but* the root token in a situation like this?  We *really* want to avoid starting over.

Thanks!

**Comment by jefferai** [comment]
See https://www.vaultproject.io/docs/auth/token.html#auth-token-accessors -- iterating over those is how to do it.

You can also just revoke all tokens and then generate a new root token.

**Comment by richard-mauri** [comment]
I am using token-revoke CLI in a loop iterating over the accessors. This is slow (many minutes)when you have a bunch to do. My tokens come from APPID auth and there is no parent that I could revoke that would clear the lot. It would be great to be able to revoke a list of accessors!
