### ISSUE TITLE
tls_require_and_verify_client_cert documentation question

### ISSUE THREAD

**Issue by pantocrator27** [hashicorp/vault#2577]
In the TCP listener documentation, it appears as if `tls_require_and_verify_client_cert` is set to `false` by default.  However there is a caution that indicates:

```
Use caution with this option; disabling it requires modifying Vault's configuration rather than an ACL'd Vault API call, so it's best used in a defense-in-depth fashion.
```

The question is that since it is disabled by default, does the caution apply?

**Comment by jefferai** [comment]
This is just a bit confusing wording -- it means, if you've turned it on, it can be turned off via the config file, which doesn't have any Vault-provided authn/authz checking.

I'll update the docs!
