### ISSUE TITLE
SSH Secrets Engine: Identity templating for `default_extensions`

### ISSUE THREAD

**Issue by radek-sprta** [hashicorp/vault#25783]
**Is your feature request related to a problem? Please describe.**
I want to use SSH Secrets Engine to provision ephemeral SSH certs for accessing Github.com. Github.com uses the `login@github.com` extension to indicate the Github user. Just adding `login@github.com` to `allowed_extensions` would let user impersonate anyone from the organization.

**Describe the solution you'd like**
Enable identity templates in `default_extensions` field, so we could use something along the lines of:
```
"default_extensions": {
  "login@github.com": "{{ identity.entity.aliases.<mount_accessor>.name }}"
}
```

**Describe alternatives you've considered**
- Using identity templates for `allowed_parameters` in policy: not supported either
- Use terraform templates to generate a role for each user: impractical due to the number of users

**Comment by radek-sprta** [comment]
Looking at the code, it actually seems supported. Looks like you need to enable the undocumented `default_extensions_template` option.

**Comment by ccapurso** [comment]
The documentation has been updated within https://github.com/hashicorp/vault/pull/26028. Thank you again for the contribution @radek-sprta!
