### ISSUE TITLE
Documentation about AES-GCM tag verification is possibly misleading

### ISSUE THREAD

**Issue by Toinews** [hashicorp/vault#2578]
Hi, 

In the documentation (vault/website/source/docs/internals/security.html.md) I read something dealing with the verification of the GCM tag before decrypting : 

> The nonce is randomly generated for every encrypted object. When data is read from the security barrier the GCM authentication tag is verified prior to decryption to detect any tampering.

From what I understand of the GCM mechanisms I can't see how this is possible. Isn't this a little mistake in the documentation ? 

I also had a look at the crypto/aes import of Go (https://golang.org/src/crypto/aes/aes_gcm.go) just to double check before posting issue and they are actually checking the tag at the end of the decryption process.

Thanks,
Regards,

**Comment by jefferai** [comment]
@Toinews it should probably read "is verified as part of the decryption process". I'll update it.
