### ISSUE TITLE
1.15.6 - UI: Kubernetes Auth Backend missing roles

### ISSUE THREAD

**Issue by tdgeery** [hashicorp/vault#25789]
**Describe the bug**

In the most recent release (1.15.6) Vault UI no longer displays the Kubernetes Auth Backend Roles. In previous releases (1.15.5) and earlier you could see the roles:

<img width="861" alt="Screenshot 2024-03-05 at 3 29 53 PM" src="https://github.com/hashicorp/vault/assets/7515592/03a28e81-4b7b-438d-a7c7-0ceb0e9c9615">

and with 1.15.6:

<img width="542" alt="Screenshot 2024-03-05 at 3 27 05 PM" src="https://github.com/hashicorp/vault/assets/7515592/f2cbdc8b-6b7a-41d3-b431-55c9bf38b30f">

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.15.6
* Vault CLI Version (retrieve with `vault version`): N/A

**Comment by kirby0025** [comment]
Hello,
Bug is no longer present in 1.16.1.

**Comment by Monkeychip** [comment]
@tdgeery thank you for reporting the bug. This was fixed by this [PR](https://github.com/hashicorp/vault/pull/25999). Upgrading to >= 1.16.0 will fix the issue.
