### ISSUE TITLE
Documentation for `allow_token_displayname` in PKI secret backend documentation does not indicate feature is non-functional

### ISSUE THREAD

**Issue by drakedevel** [hashicorp/vault#2580]
The documentation for the PKI secret backend makes reference to an `allow_token_displayname` option on roles which I attempted to make use of. After spending a while trying to figure out why my writes to that setting were being silently ignored, I discovered that `pathRoleCreate` didn't have the code to populate that field. Upon further digging the option and its documentation were removed in commit 703a0d65c035e2cb86659c6b7e9184cd48b2e2bd. The documentation was re-added per issue #2488 in commit 688104e69a34f883e0c047474902aaf97ded6549 but the replaced documentation does not indicate that the parameter isn't actually implemented at this point.

The documentation should probably be removed or updated -- my suggestion is to remove it, and either document in the code that the feature is dead or remove it from the code altogether.

**Comment by jefferai** [comment]
Interesting. All of the code to handle this is still in there *except* the actual code to populate that bool. This feels like a bug that nobody has run into rather than a documentation error.

So the question at this point is -- add that flag back in, or remove the rest of the code that handles this and the associated documentation.

What's the use-case you're running into?

**Comment by drakedevel** [comment]
My goal is for an EC2 instance named `fooserver100` to have access to a token associated with that name, and a SSL client certificate for `fooserver100.my.domain`.

My first instinct was to try to use EC2 auth -- unfortunately I couldn't find a way to restrict permitted SSL certificate hostnames based on the resulting token metadata. The best approximation I could come up with involved making a unique policy for every instance and using a role tag to permit that policy. This means launching an instance requires a root-equivalent token -- hardly an ideal solution.

My next thought was to issue a periodic token named `fooserver100.my.domain` to the EC2 instance at launch time, and then use `allow_token_displayname` to permit that token to issue the SSL client certificate as needed. In addition to the issue this bug covers, I just learned that the `handleCreateCommon` function in the token creation path sanitizes token display names to `token-fooserver100-my-domain` which renders the feature largely useless even if re-enabled. 

The workaround for my use-case is pretty trivial -- since I only need one SSL client certificate (for Puppet) at this point, and I don't mind if it has a long lifetime, I just issue that at the same time as the periodic token.

Given the aggressive sanitization on token display names, it seems like the right thing to do is to fully remove `allow_token_displayname` and investigate supporting PKI issuance policy based on other token metadata.

**Comment by jefferai** [comment]
> In addition to the issue this bug covers, I just learned that the handleCreateCommon function in the token creation path sanitizes token display names to token-fooserver100-my-domain which renders the feature largely useless even if re-enabled.

Actually, that's exactly why the `allow_token_displayname` feature was dropped in the first place!

But the question remains the same. The stripped out code can trivially be added back in, or the remaining code can be stripped out. The question is which way to go.

**Comment by jefferai** [comment]
Probably I'll just remove it entirely.

**Comment by jefferai** [comment]
Fixed, site is being rebuilt now.
