### ISSUE TITLE
Vault HA issue

### ISSUE THREAD

**Issue by Rameshera** [hashicorp/vault#2582]
I have 3 nodes and running vault and backend consul.

Below are the hcl file and vault status output.

Can you please help me to find out what is wrong here.  Appreciated for your quick response

Server 1

backend "consul" {
       address = "localhost:8500"
       path = "vault"
       check_timeout = "30s"
       max_parallel = 128
}
disable_cache = true
listener "tcp" {
       address = "localhost:8200"
       tls_disable = 0
       tls_cert_file = "/var/lib/vault/ssl/vault.crt"
       tls_key_file = "/var/lib/vault/ssl/vault.key"
       cluster_address = "10.xx.xx.28:8201"
}

vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Version: 0.6.4
Cluster Name: vault-cluster-4403c0d7
Cluster ID: 95a8ffb6-bca1-ec06-9d71-eac094662fc3High-Availability Enabled: true
       Mode: standby
       Leader: https://10.xx.xx.29:8200

Server 2

backend "consul" {
       address = "localhost:8500"
       path = "vault"
       check_timeout = "30s"
       max_parallel = 128
}
disable_cache = true
listener "tcp" {
       address = "localhost:8200"
       tls_disable = 0
       tls_cert_file = "/var/lib/vault/ssl/vault.crt"
       tls_key_file = "/var/lib/vault/ssl/vault.key"
       cluster_address = "10.xx.xx.29:8201"
}

vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Version: 0.6.4
Cluster Name: vault-cluster-4403c0d7
Cluster ID: 95a8ffb6-bca1-ec06-9d71-eac094662fc3High-Availability Enabled: true
       Mode: active
       Leader: https://10.xx.xx.29:8200

Server 3

backend "consul" {
       address = "localhost:8500"
       path = "vault"
       check_timeout = "30s"
       max_parallel = 128
}
disable_cache = true
listener "tcp" {
       address = "localhost:8200"
       tls_disable = 0
       tls_cert_file = "/var/lib/vault/ssl/vault.crt"
       tls_key_file = "/var/lib/vault/ssl/vault.key"
       cluster_address = "10.xx.xx.30:8201"
}

vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Version: 0.6.4
Cluster Name: vault-cluster-4403c0d7
Cluster ID: 95a8ffb6-bca1-ec06-9d71-eac094662fc3High-Availability Enabled: true
       Mode: standby
       Leader: https://10.xx.xx.29:8200

Thanks,
Ramesh

**Comment by shubhamitc** [comment]
storage "consul" {
  address = "<consulserver>:8500"
  path    = "vault"
  service = "vault"
  cluster_addr = "https://<vaultadverties address>:8200/"
  redirect_addr  = "https://<machineip>:8200"
}


#ha_storage "consul"

listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = 0
  tls_cert_file = "/opt/vault/selfsigned.crt",
  tls_key_file = "/opt/vault/selfsigned.key"
}

#telemetry {
#  statsite_address = "127.0.0.1:8125"
#  disable_hostname = true
#}

Try this file

**Comment by Rameshera** [comment]
I have updated as below. I just want to know what is tls_disable = 0. Will it effect if i stop vault in one node and update as below


backend "consul" {
       address = "127.0.0.1:8500"
       path = "vault"
       service = "vault"
       cluster_addr = "https://127.0.0.1:8200"
       redirect_addr = "https://127.0.0.1:8200"
       check_timeout = "30s"
       max_parallel = 128
}
disable_cache = true
listener "tcp" {
       address = "127.0.0.1:8200"
       tls_disable = 0
       tls_cert_file = "/var/lib/vault/ssl/vault.crt"
       tls_key_file = "/var/lib/vault/ssl/vault.key"
       cluster_address = "10.24.96.28:8201"
}#telemetry {
       statsite_address = "127.0.0.1:8125"
       disable_hostname = "true"
#}

**Comment by Rameshera** [comment]
Getting connection refused error when i start with recommended configuration.


2017/04/11 12:08:43.457018 [WARN ] physical/consul: appending trailing forward slash to path
2017-04-11 12:08:48.457572 I | [ERR] Error connecting to statsite! Err: dial tcp 127.0.0.1:8125: getsockopt: connection refused

**Comment by chrishoffman** [comment]
It looks like you addressed your original issue.  The latest error is related to connecting to statsite.  If you are not running statsite, delete out the entire telemetry block and see if that resolves your issue.

**Comment by Rameshera** [comment]
yes. I deleted elemetry block and working.

**Comment by Rameshera** [comment]
i tested with my original configuration and it is working HA fail over without any issues. Thank you all your support :)
