### ISSUE TITLE
Respect TTL in DNS ZK resolver

### ISSUE THREAD

**Issue by devth** [hashicorp/vault#2586]
This might be an issue for `go-zookeeper` but wanted to check here first. According to [the source](https://github.com/hashicorp/vault/blob/master/vendor/github.com/samuel/go-zookeeper/zk/dnshostprovider.go#L13) the DNS resolution is cached indefinitely. This doesn't work well in environments where the underlying IPs can change periodically (Kubernetes in my case). Should this respect TTL?

Original source [here](https://github.com/samuel/go-zookeeper/blob/master/zk/dnshostprovider.go) for go-zookeeper.

**Comment by jefferai** [comment]
Given that the source is in go-zookeeper I think you need to bring this up with the maintainers of that lib. Once they've made any changes feel free to comment back and we can update deps.

**Comment by devth** [comment]
The lib doesn't appear to be maintained but I'll see what I can do.

**Comment by jefferai** [comment]
Hi @devth,

A number of patches have been put into go-zookeeper by interested Vault users so while I agree it appears to not be super active you may have luck.

@talbright and @kenbreeman may have more insight; I think one of them may have been working on a fork as well.

**Comment by talbright** [comment]
I tried hard to help the author by triaging PRs, nudging him to merge fixes that were left dormant for months, etc. I also asked the original author for commit rights to help maintain it. I was ignored, and work very similar to what I did in my fork popped in upstream with no attributions. It was a bit frustrating. 

To be fair, despite the multiple month gaps in activity, some things do eventually get merged in.

**Comment by devth** [comment]
Maybe time to fork? There are many open issues and PRs with 0 responses going back to 2013, but mostly 2015 and 2016.

**Comment by talbright** [comment]
Easier said then done. I basically forked, but couldn't really get any outside momentum. Unless larger users like hashicorp or say for example the libkv project from the docker folks adopt it, its going to be hard to get traction. And they don't want to adopt it unless your fork has traction. It all makes sense from both sides, but in the end it means nothing is going to change.

**Comment by jefferai** [comment]
@talbright Wait, I said I wouldn't adopt it? :-)

**Comment by talbright** [comment]
@devth I'm not sure if this would help you (it might since you are already running etcd via your use of kubernetes), but it is interesting: 

https://github.com/coreos/zetcd

I heard it mentioned in a talk by https://github.com/coreos today at my employer...

**Comment by devth** [comment]
@talbright I'm on GKE so the underlying etcd is not accessible to consumers. I'd have to run a separate etcd to take advantage. Interesting option though. Thanks!

**Comment by talbright** [comment]
@jefferai I thought you said something to the affect of "fork it, and if they come...". But it has been awhile so maybe I misunderstood what you meant.

**Comment by jefferai** [comment]
@talbright The ZK backend is community-supported; if there appears to be quorum in the community of ZK-backend-using Vault users that a particular fork should be used instead of the original library, I'm happy to switch it.
