### ISSUE TITLE
Vault client does not respect address's with path prefixes

### ISSUE THREAD

**Issue by leeavital** [hashicorp/vault#2589]
We have vault sitting behind nginx. We've put it under the location `/vault/` in order to avoid URL conflicts with other services.

we have code which talks to that URL, but the vault client seems to be dropping the `/vault` from the address I use to configure the client. I tried fixing this here: https://github.com/hashicorp/vault/pull/2588

**Comment by briankassouf** [comment]
Fixed by #2588
