### ISSUE TITLE
Vault not honoring TTL's in Github Auth

### ISSUE THREAD

**Issue by nocode99** [hashicorp/vault#2590]
Version `0.7.0`

```
$ vault read auth/github/config
Key             Value
---             -----
base_url    
max_ttl         86400 # 24hrs
organization    my_organization
ttl             43200  # 12hrs
```

I authenticate once by `vault auth -method-github token=$MY_TOKEN` and my token is stored in `~/.vault-token`.  However, the next subsequent days, I can continue running `vault` commands without having to reauthenticate and verified that my `~/.vault-token` has not been modified.

**Comment by chrishoffman** [comment]
I have not been able to recreate this locally.  I set this up with a very short ttl and the token expired correctly.  If the configuration changed after the lease was issued, it would still have the values when the token was created.

You could also run `vault token-lookup <token>` to see the values set for this token.

**Comment by nocode99** [comment]
Ah - seems I did add it later.  I had written a script to initialize and configure vault on the initial deploy but must've added the lease later on.  Using the `token-lookup`, I can see it has set correctly.

Thanks!
