### ISSUE TITLE
disable vault mount failed

### ISSUE THREAD

**Issue by zoezhangmattr** [hashicorp/vault#25944]
**Describe the bug**
try to disable a vault mount called test/secret as admin, full permission scope
by running, `vault secrets disable test/secret` or even tried with `VAULT_CLIENT_TIMEOUT=3600s vault secrets disable test/secret` 
failed with 
Error disabling secrets engine at dcc/secret/: Error making API request.

URL: DELETE https://127.0.0.1:8200/v1/sys/mounts/test/secret
Code: 400. Errors:

* timeout: context canceled

the logs shows
"error":"1 error occurred:\n\t* unsupported path\n\n"

**To Reproduce**
1. Run `vault write ...`
2. Run `vault login....`
3. See error

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.13.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.14.0 (13a649f860186dffe3f3a4459814d87191efc321), built 2023-06-19T11:40:23Z
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by ccapurso** [comment]
Hi, @zoezhangmattr! I am unfortunately not able to reproduce the issue. I used the following steps as an attempt:

```
❯ vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.13.2
Build Date      2023-04-25T13:02:50Z
Storage Type    inmem
Cluster Name    vault-cluster-16768c12
Cluster ID      7839e6a8-c850-dfd5-6111-2a1524ba948e
HA Enabled      false

❯ vault secrets enable -path=test/secret kv-v2
Success! Enabled the kv-v2 secrets engine at: test/secret/

❯ vault secrets list
Path            Type         Accessor              Description
----            ----         --------              -----------
cubbyhole/      cubbyhole    cubbyhole_129987c5    per-token private secret storage
identity/       identity     identity_280838a8     identity store
secret/         kv           kv_b63d62aa           key/value secret storage
sys/            system       system_f16ae476       system endpoints used for control, policy and debugging
test/secret/    kv           kv_1e1a84bf           n/a

❯ vault secrets disable test/secret
Success! Disabled the secrets engine (if it existed) at: test/secret/
```

These reproduction steps are admittedly very basic in that the secrets backend does not contain any underlying secrets. Would you be able to provide additional insight into your existing setup or expand on the reproduction steps for further diagnosis?
