### ISSUE TITLE
Please document that error 404 could also mean an empty list.

### ISSUE THREAD

**Issue by stormshield-gt** [hashicorp/vault#25969]
When using a list endpoint, if there is no item to list, the API returns an error 404.

As explain [here](https://github.com/hashicorp/vault/issues/20740#issuecomment-1563404557), this unusual behavior is kept for backward compatibility. The original rational can be found here https://github.com/hashicorp/vault/issues/1365 

This has been a painful point for users since a long time, as we can see by the number of related issues
https://github.com/hashicorp/vault/issues/20740 https://github.com/hashicorp/vault/issues/13043 https://github.com/hashicorp/vault/issues/24964 https://github.com/hashicorp/vault/issues/1958 https://github.com/hashicorp/vault/issues/5861  https://github.com/hashicorp/vault/issues/8833 https://github.com/hvac/hvac/issues/928

I think this will keep hurting users, again and again, if the behavior continues to be undocumented.

I suggest updating the documentation about the [error codes returned by the API](https://developer.hashicorp.com/vault/api-docs#http-status-codes) to mention that 404 could also mean an empty list.

**Comment by ccapurso** [comment]
Hi, @stormshield-gt. Thank you for the feedback! The documentation has been updated to reflect this behavior.
