### ISSUE TITLE
identity engine returns `nil` to mean empty list `[]`

### ISSUE THREAD

**Issue by rjhornsby** [hashicorp/vault#25997]
**Describe the bug**

Vault's identity engine returns `nil` instead of `[]` when a value is an empty list. This is true of, at minimum, the fields `member_group_ids` and `parent_group_ids`. This possibly also affects `member_entity_ids` and `policies`

This behavior seems inappropriate because the wrong (unexpected) value type is being sent back to the client. As best I can tell, this behavior is confusing Terraform, which in turn causes the Vault TF provider resource `vault_identity_group_member_group_ids` to [silently fail](https://github.com/hashicorp/terraform-provider-vault/issues/2195).

The more I dug into it, the more this looks like a Vault proper issue, rather than a bug in TF or the vault provider. (Though if type coercion were somehow possible in the provider before the type comparison happens, that might be a work-around.)

**To Reproduce**
1. Run `vault read identity/group/id/be50c371-178b-8f45-70df-xxxxx`
2. See result
```
Key                  Value
---                  -----
alias                (redacted)
creation_time        2021-07-12T17:20:37.150135989Z
id                   be50c371-178b-8f45-xxx
last_update_time     2024-03-15T17:43:36.044116519Z
member_entity_ids    [2c5899c5-a7a4-6ad9-xxx 36dd8aec-fa70-2642-51d3-xxx]
member_group_ids     <nil>
metadata             <nil>
modify_index         64
name                 client-1234-vault-users
namespace_id         root
parent_group_ids     <nil>
policies             [client-1234-vault-users]
type                 external
```

**Expected behavior**
The identity engine should return an empty list/set `[]` where appropriate, rathe than `nil`

**Environment:**
* Vault Server Version: 1.15.6
* Vault CLI Version: 1.15.6
* Server Operating System/Architecture: RHEL9/x64

**Comment by ccapurso** [comment]
Hi @rjhornsby, we reserve GitHub issues for bug reports and feature requests, which this doesn't appear to be. As such, I'm going to close this and suggest that you ask about this on the [Vault Discuss](https://discuss.hashicorp.com/c/vault/30) page.

**Comment by rjhornsby** [comment]
@ccapurso can you help me understand please why this isn't a bug? `nil` and `[]` are not just different values, they're separate variable types. Consumers like Terraform expecting a list, empty or otherwise, do not reasonably expect to get type `nil` instead. I created a bug report because the current behavior is unexpected and undesirable.

Alternatively, is Terraform wrong, and should it (or the Vault provider) be coercing the type?

**Comment by fairclothjm** [comment]
@rjhornsby Hello! This is something we will need to handle in the Terraform Vault Provider. It is very common for TFVP to coerce the type. We just missed it in this case.
