### ISSUE TITLE
Any way to export secrets and restore them into another vault instance by http APIs?

### ISSUE THREAD

**Issue by haoruiqian** [hashicorp/vault#2601]
I'm trying to find APIs for exporting and restoring, I have some secrets stored in one vault instance, and I want to export them then import into another vault instance.

I know for file backend, we can just copy the files, but what if I cannot access the backend? For example, the vault is running as a CloudFoundry service. I only have the keys and token (or sometimes just have the token), how can I achieve this?

Is it possible that we can export the secrets into a file with some kinds of encryption(using nonce, key, or token, etc.), and import the file to another vault instance, then that instance decrypt them with the nonce/key/token?

**Comment by jefferai** [comment]
This is not currently possible, no; however, if it's just secrets that you have access to, you could iterate through the system using list/get on one and then store them in the other.
