### ISSUE TITLE
Request forwarding port issue

### ISSUE THREAD

**Issue by CSharpRU** [hashicorp/vault#2602]
Greetings,

I'm experiencing issues with request forwarding:
`http/handleRequestForwarding: error forwarding request: error=dial tcp :443: getsockopt: connection refused`

Why it's trying to open connection to 443 port instead of 8201?

**Comment by jefferai** [comment]
What's your config? What is the information in the lines your Vault servers print out when you start them?

**Comment by CSharpRU** [comment]
**Config:**
```
listener "tcp" {
  address = "ip:8200"

  cluster_address = "ip:8201"

  tls_disable = "false"
  tls_cert_file = "/etc/vault/cert.pem"
  tls_key_file = "/etc/vault/key.pem"
}

storage "etcd" {
  address = "https://localhost:2379"
  etcd_api = "v3"

  ha_enabled = "true"

  tls_ca_file = "/etc/ssl/ca.pem"
  tls_cert_file = "/etc/ssl/cert.pem"
  tls_key_file = "/etc/ssl/key.pem"

  cluster_addr = "hostname:8201"
  disable_clustering = "false"
  redirect_addr = "https://hostname:8200"
}
```

**Startup message:**
```
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https:8201
              Listener 1: tcp (addr: "ip:8200", cluster address: "ip:8201", tls: "enabled")
               Log Level: err
                   Mlock: supported: true, enabled: true
        Redirect Address: https://hostname:8200
                 Storage: etcd (HA available)
                 Version: Vault v0.7.0
             Version Sha: sha

==> Vault server started! Log data will stream in below:

```

**Comment by jefferai** [comment]
That's on both (or all) nodes? Assuming things like `https:8201` are just overzealous simplification, it looks like it should be fine.

You may want to try having your `cluster_addr` start with `https://hostname:8201`; it will always force https but I think it does require a full URL.

**Comment by CSharpRU** [comment]
Yep, that's on all nodes. And I've tried a full URL.

**Comment by jefferai** [comment]
Can you provide log output from the startup of each node until you get that error? If you need a private address to send it to let me know.

**Comment by CSharpRU** [comment]
Log of the error in the first post.

To reproduce, just setup HA config and exec `vault read secret/something`. Before that logs are empty.

**Comment by jefferai** [comment]
Did you mean to attach a log?

**Comment by jefferai** [comment]
Oh -- I need log level trace, not err. Err won't show you much of anything.

**Comment by CSharpRU** [comment]
Okay, I'll try to make it today.

**Comment by CSharpRU** [comment]
Here is log with trace level:
```
2017/04/18 14:03:13.410544 [TRACE] physical/cache: creating LRU cache: size=32768
2017/04/18 14:03:13.416555 [TRACE] cluster listener addresses synthesized: cluster_addresses=[ip:8201]
2017/04/18 14:03:33.006100 [DEBUG] core: cannot unseal, not enough keys: keys=1 threshold=3 nonce=nonce
2017/04/18 14:03:36.240642 [DEBUG] core: cannot unseal, not enough keys: keys=2 threshold=3 nonce=nonce
2017/04/18 14:03:39.436669 [INFO ] core: vault is unsealed
2017/04/18 14:03:39.436785 [INFO ] core: entering standby mode
2017/04/18 14:03:39.436816 [TRACE] core: clearing forwarding clients
2017/04/18 14:03:39.436822 [TRACE] core: done clearing forwarding clients
2017/04/18 14:03:41.496643 [TRACE] core: found new active node information, refreshing
2017/04/18 14:03:41.499088 [TRACE] core: parsing information for new active node: active_cluster_addr=https:8201 active_redirect_addr=https://hostname:8200
2017/04/18 14:03:41.499201 [TRACE] core: refreshing forwarding connection
2017/04/18 14:03:41.499207 [TRACE] core: clearing forwarding clients
2017/04/18 14:03:41.499211 [TRACE] core: done clearing forwarding clients
2017/04/18 14:03:41.499224 [TRACE] core: done refreshing forwarding connection
2017/04/18 14:03:41.499706 [ERROR] http/handleRequestForwarding: error forwarding request: error=dial tcp :443: getsockopt: connection refused
```

**Comment by jefferai** [comment]
> 2017/04/18 14:03:41.499088 [TRACE] core: parsing information for new active node: active_cluster_addr=https:8201 active_redirect_addr=https://hostname:8200

I'm confused -- are you not actually putting a host name for your cluster address? Or are you just eliding it from the logs?

**Comment by CSharpRU** [comment]
Nope, I've just removed real hostname from `active_redirect_addr`. `active_cluster_addr` isn't touched.

**Comment by jefferai** [comment]
So your cluster address is literally 'https:8201'?

**Comment by CSharpRU** [comment]
Yep, as Vault says. But I was expecting that it'll be https://hostname:8201

**Comment by jefferai** [comment]
That's not what's in your config file though...

**Comment by CSharpRU** [comment]
Okay, anyway it should be something like hostname:8201, not https:8201

**Comment by jefferai** [comment]
As the documentation for the parameter states, "This is a full URL". You're not giving it a URL and it's getting confused.

**Comment by CSharpRU** [comment]
Okay, I'll try a full URL again.

**Comment by CSharpRU** [comment]
Indeed, with a full URL it works :)

Thanks for helping.
