### ISSUE TITLE
vault 0.7.0 is not forwarding in HA setup with etcd v3.1.5, it is redirecting

### ISSUE THREAD

**Issue by raoofm** [hashicorp/vault#2605]
When I checked the logs

Active
2017/04/17 19:51:08 http: TLS handshake error from 10.7.2.17:54098: remote error: tls: bad certificate

Standby
2017/04/17 19:51:08.587288 [ERROR] http/handleRequestForwarding: error forwarding request: error=x509: certificate is valid for 10.7.2.16, not fw-fe02ce25-74c7-4316-ce47-ec960212ad7c

**Comment by jefferai** [comment]
What are your configs and logs?

**Comment by raoofm** [comment]
For standby
storage "etcd" {
  address           = "https://node-01.example.com:2379,https://node-02.example.com:2379,https://node-03.example.com:2379"
  etcd_api          = "v3"
  ha_enabled        = "true"
  path              = "vault/dev/"
  sync              = "true"
  username          = "root"
  password          = "password"
  tls_ca_file       = "/home/rm/cfssl/ca.pem"
  cluster_addr      = "https://vaultnode-03.example.com:8200"
  redirect_addr     = "https://vaultnode-03.example.com:8200"
}

listener "tcp" {
  address           = "vaultnode-03.example.com:8200"
  cluster_address   = "vaultnode-03.example.com:8201"
  tls_disable       = "false"
  tls_cert_file     = "/home/rm/vault.crt"
  tls_key_file      = "/home/rm/vault.key"
  tls_min_version   = "tls12"
}

cluster_name        = "vault-cluster-dev"
disable_cache       = false
cache_size          = "32768"
disable_mlock       = false

default_lease_ttl   = "30"
max_lease_ttl       = "60"

**Comment by raoofm** [comment]
similar with just vaultnode-01 instead of vaultnode-03

**Comment by jefferai** [comment]
Your cluster address is set to port 8200, but that's your API address.

**Comment by jefferai** [comment]
cluster_addr that is

**Comment by raoofm** [comment]
sorry, didn't get, what you mean

**Comment by raoofm** [comment]
i have cluster_address in both storage and listener

**Comment by raoofm** [comment]
oh the etcd one
should be 8201

**Comment by raoofm** [comment]
@jefferai is that what you mean that the cluster_addr in storage should be 8201?

**Comment by jefferai** [comment]
Yes. 8200 is your API address, not your cluster address. Fix that and you should be set.
