### ISSUE TITLE
[UI] Able to delete the secret even after not providing the delete policy 

### ISSUE THREAD

**Issue by swathida-byte** [hashicorp/vault#26070]
**Describe the bug**
I have a policy which does not have a delete option included in the policy but I'm still able to delete it from the UI and when I run the same thing in CLI I'm not able to delete the secret.
the policy looks something like this 
```
path "abc/*"
{
  capabilities = ["create", "read", "update", "list", "delete" , "sudo", "patch"]
}
path "abc/data/def/*"
{
  capabilities = ["create", "read", "update", "list", "patch"]
}
```
From UI I'm able to delete the secret from abc/data/def/ path but when tried from CLI 
```
vault delete abc/data/def
Error deleting abc/data/def: Error making API request.


URL: DELETE <vault-url>/v1/abc/data/def
Code: 403. Errors:


* 1 error occurred:
	* permission denied 
```
which is expected behaviour from UI as well disable the delete option 

**Expected behavior**
Disable the delete option and not be able to delete the secret when the delete option is not added to the policy

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.10.3
* Vault CLI Version (retrieve with `vault version`):  v1.14.4
* Server Operating System/Architecture: 

Vault server configuration file(s):

```hcl
path "abc/*"
{
  capabilities = ["create", "read", "update", "list", "delete" , "sudo", "patch"]
}
path "abc/data/def/*"
{
  capabilities = ["create", "read", "update", "list", "patch"]
}
```

**Comment by Monkeychip** [comment]
@swathida-byte are you able to provide a screenshot of the delete button you're using in the UI? And/or also the network request when you hit that delete button? If I had to guess, I would say you're deleting on metadata, see API endpoint [here](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#delete-metadata-and-all-versions). There are a lot of delete permissions and types on KV. 
1. delete on the data endpoint.
2. delete on the metdadata endpoint.
3. destroy on the destroy endpoint
4. delete on delete endpoint

**Comment by Monkeychip** [comment]
@swathida-byte I'm going to go ahead and close this per the message before this one. If you are still having issues after confirming your policy is correct, please ping here and we'll reopen.
