### ISSUE TITLE
Very minor Shamir split count leakage

### ISSUE THREAD

**Issue by grocid** [hashicorp/vault#2608]
In Vault, a set of _n_ splits of a byte is generated as `X = {1, 2, 3, ..., n}` and `Y = {p(1), p(2), p(3), ... , p(n)}`, where the _x_ coordinate is appended to the end of each split. Observing a split `0xAB05` gives a lower bound on how many splits being generated (_n_ ≥ 5), which might leak some information about the infrastructure in which Vault is deployed, depending on the scenario. A very simple fix is to generate a random set of _x_ coordinates instead of sequential coordinates.

Although this is by no means a significant leakage, it can be mitigated very easily, and leaking information is never a good thing :-)

**Comment by v6** [comment]
// , Can you give an example of the kind of info. this might leak, or of one of the scenarios?
