### ISSUE TITLE
The latest vault uses vulnerable version of alpine:3.18 instead of fixed 3.19.1

### ISSUE THREAD

**Issue by OlgasAcc** [hashicorp/vault#26151]
Hello,
There are 2 issues related to the Dockerfile:

1. We pull the latest version (v1.15.6) of the image within the project. However, the Aqua security scanner has flagged vulnerabilities due to the utilization of an outdated Alpine version, specifically versions 3.18 and 3.18.6.
To address these security concerns, updating to Alpine version 3.19.1 resolves these issues. 

<img width="1728" alt="image" src="https://github.com/hashicorp/vault/assets/55320727/f78e8a63-e193-4cdd-b83b-bcab99d43473">

2. There is security issue marked as "High" by Aqua scanner: 
<img width="1728" alt="image" src="https://github.com/hashicorp/vault/assets/55320727/04434e77-d13c-4350-8b7f-b7d34b409bb9">

I assume it's related to the docker version you use for image building: 
"COPY .release/docker/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]" 

**Would it be feasible for you to upgrade the image accordingly (to alpine:3.19.1 and docker v26.0.0)?**

Thanks,
Olga

**Comment by hsimon-hashicorp** [comment]
Please email security@hashicorp.com for all vulnerability reports. Thank you! :)

**Comment by mickael-hc** [comment]
Hi @OlgasAcc thanks for opening this issue. We take a risk-based approach to adopting dependency updates including security fixes as part of our ongoing product development lifecycle. You'll see these addressed in the next release of Vault.

I'll close this issue for now, but feel free to reach out to `security@hashicorp.com` if you see any issues with these dependencies in the next release series of Vault (1.16.0, 1.15.7, and 1.14.11)
