### ISSUE TITLE
missing entity alias attribute value with

### ISSUE THREAD

**Issue by trutled3** [hashicorp/vault#26171]
**Describe the bug**

After upgrading Vault to v1.16.0 from v1.15.1 we are seeing an error when signing in through the ldap auth method stating, `Authentication failed: missing entity alias attribute value`. I am using active directory.

![Screenshot 2024-03-26 at 4 58 29 PM](https://github.com/hashicorp/vault/assets/89163186/86849d33-917e-43f8-ac08-2d8344738691)

**To Reproduce**
1. Enable ldap auth method with config similar to:
```
  url="<REDACTED>" \
  userattr="sAMAccountName" \
  userdn="<REDACTED>" \
  binddn="<REDACTED>" \
  bindpass="<REDACTED>" \
  groupdn="<REDACTED>" \
  certificate=@ldap_cert.pem \
  insecure_tls=true \
  case_sensitive_names=false \
  starttls=true
```
2. Attempt to sign in to Vault with ldap auth method.

**Expected behavior**
Expected behavior is for ldap auth method behavior to remain the same between v1.15.1 and v1.16.0 with no changes to ldap auth method configuration.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.16.0
* Vault CLI Version (retrieve with `vault version`): N/A
* Server Operating System/Architecture: Ubuntu

Vault server configuration file(s):

```
  url="<REDACTED>" \
  userattr="sAMAccountName" \
  userdn="<REDACTED>" \
  binddn="<REDACTED>" \
  bindpass="<REDACTED>" \
  groupdn="<REDACTED>" \
  certificate=@ldap_cert.pem \
  insecure_tls=true \
  case_sensitive_names=false \
  starttls=true
```

**Comment by hsimon-hashicorp** [comment]
Hi @trutled3 - thanks for this report! Is this on 1.16.0 GA or one of the RCs? It'll help our investigation. Thanks much! :)

**Comment by trutled3** [comment]
Hi there!

This was v1.16.0 GA that was released today.

**Comment by hsimon-hashicorp** [comment]
> Hi there!
> 
> This was v1.16.0 GA that was released today.

Thank you so much! I'll pass this along. That release was pulled, and I'll make sure this issue gets addressed as well.

**Comment by trutled3** [comment]
Oh, okay. Thanks!

**Comment by usernamemikem** [comment]
I have the exact same issue. Upgraded just minutes ago.

**Comment by Joffrey54** [comment]
Are you using Active Directory ? I have the same issue

**Comment by trutled3** [comment]
@Joffrey54 - I am using active directory, yes! I did not include that information in my original issue post. I updated to include that information as well.

**Comment by usernamemikem** [comment]
> I have the exact same issue. Upgraded just minutes ago.

@Joffrey54 - Same here, using Active Directory.

**Comment by Joffrey54** [comment]
Perhaps the bug come from the "user attribute" that is forced in lowercase:
![image](https://github.com/hashicorp/vault/assets/3739340/30a41e47-416b-491d-8773-8f57d780e788)

In Windows, this attribute is "sAMAccountName"

But, as I said, this option solved the error for me:
![image](https://github.com/hashicorp/vault/assets/3739340/d35f8772-bfad-4d7b-b952-870f7ead4f7e)

**Comment by trutled3** [comment]
I can confirm checking the username as alias box resolves the error for me as well.

**Comment by fairclothjm** [comment]
Thanks everyone, we are working on a fix for this now.

The workaround mentioned above should be used with caution since the user attribute is customizable.
