### ISSUE TITLE
GET /sys/mounts/:path is presenting unexpected errors

### ISSUE THREAD

**Issue by jalbarracinklar** [hashicorp/vault#26180]
We are facing issues while trying to use some of the Hashicorp Vault endpoints.
We need to use GET /v1/sys/mounts/<mount> endpoint with our root token but all we get is 405 unsupported operation. We tried this with every mount we have.
Following the documentation https://developer.hashicorp.com/vault/api-docs/system/mounts we saw we could try requesting GET /v1/sys/mounts/<mount>/tune to see if the mount existed and it's working correctly.
We have Vault v1.9.2.

Do you know what could be happening?

**Comment by hsimon-hashicorp** [comment]
Hi folks! Is this still an issue in newer versions of Vault? Please let me know so I can bubble it up accordingly. Thanks!

**Comment by arybach** [comment]
if you try to deploy this repo:
https://github.com/fmeringdal/do-hashicorp-cluster
you'll hit that 405 error as well. Easy to reproduce. Just need digital ocean token

**Comment by kx-aj** [comment]
I have started receiving this issue in vault 1.6.3

**Comment by jalbarracinklar** [comment]
we're not using digital ocean. We are deploying this on a k8s cluster in our AWS account

**Comment by kx-aj** [comment]
@jalbarracinklar Are you configuring vault with Terraform?

In my very specific circumstance, we hadn't set a version constraint on the vault provider for terraform, and with the version 4 provider release the paths to getting mount details has changed from `/v1/sys/mounts/:path/tune` to `/v1/sys/mounts/:path` which resulted in the 405 from my vault instance.

**Comment by jalbarracinklar** [comment]
Yes, we configured it using Terraform. So you don't set a version there? I'll try that

**Comment by kx-aj** [comment]
> @kx-aj Yes, we configured it using Terraform. So you don't set a version there? I'll try that

We **didn't** set a version, and that's how we ended up getting this error. Once we'd set a terraform provider version constraint of < 4.0, the error went away.
