### ISSUE TITLE
MySQL Secret Backend Stuck In Limbo

### ISSUE THREAD

**Issue by blarghmatey** [hashicorp/vault#2618]
I have a MySQL secret backend mounted and have generated a list of role definitions for it, with a few credentials being issued. I am trying to remove and recreate the backend, but while trying to call `DELETE` on the mount I am receiving the following error message:
```
InvalidRequest: failed to revoke 'mysql-mitx-qa/creds/xqueue-next-residential-live/07cbbade-764c-61f8-af4b-87c7dadd8448' (1 / 558): failed to revoke entry: resp:(*logical.Response)(nil) err:Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF EXISTS 'xque-aws--694009'@'%'' at line 1
```
The revocation SQL looks like: `"DROP USER IF EXISTS '{{name}}'@'%';"`

Now if I try to perform any operation on the backend it says that there is no handler for that route, but if I list the `v1/sys/mounts` route then the backend shows as still being mounted. Is there any way to either re-enable the backend or force removal of it without first completing the revocation of existing leases?

**Comment by briankassouf** [comment]
Hi @blarghmatey,

This appears to be behaving as expected. Vault tries to clean up any leases associated with a mount before removing it.

It looks like that revoke statement is invalid mysql syntax. The `IF EXISTS` clause was added in MySQL version 5.7.8. Perhaps you're running a lower version than this? 

If you truly need to force revoke these leases take a look at: https://www.vaultproject.io/api/system/revoke-force.html. But please read the documentation carefully, it's a potentially dangerous call and requires you to make sure the credentials that were not able to be revoked are cleaned up manually.
