### ISSUE TITLE
Feature request: Okta auth with MFA

### ISSUE THREAD

**Issue by ruhkopf** [hashicorp/vault#2620]
Currently the Okta authentication backend asks for a username and password. It would be nice if it would also consider MFA.

Here's an example (in Java) of how such a MFA challenge could look like 
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/src/main/java/com/okta/tools/awscli.java#L789

**Comment by joaquinrinaudo-olx** [comment]
+1

**Comment by steve-jansen** [comment]
This issue can be closed thanks to #3653

**Comment by jefferai** [comment]
Will do.
