### ISSUE TITLE
Vault v0.7.0 with Certs having multiple SANs fails to forward client request

### ISSUE THREAD

**Issue by dforsber-p** [hashicorp/vault#2622]
Vault v0.7.0 (compiled with Go v1.8.1) with Certs having multiple SANs fails to forward client request. 5 node Vault cluster with Consul backend.
```
2017/04/20 08:53:08.520518 [ERROR] http/handleRequestForwarding: error forwarding request: error=expected only a single acceptable CA
```

API client gets `Connection refused (Connection refused)` error.

**Comment by jefferai** [comment]
Vault's forwarding doesn't use your certificates. You likely have a configuration issue. What is your configuration?

**Comment by dforsber-p** [comment]
It works fine with v0.6.5 and without changing any configuration. I think we wait for v0.7.1 and then test again and dig deeper if needed :).

**Comment by dforsber-p** [comment]
I was assuming Vault uses the TLS cert as client certificate when connecting to other Vaults. At least that is how we have set it up.

**Comment by jefferai** [comment]
No, this is not how it works. Please provide your configuration information if you want assistance.

**Comment by brianmulder** [comment]
Hi hi

We're also observing this after upgrading one standby member of the cluster to 0.7.0.
Writes do still function, i.e. requests are forwarded, unless it is opaquely falling back to client redirection.

Is the error perhaps an undocumented side effect of updating one node at a time?

Config:
```
{
  "backend": {
    "etcd": {
      "address": "https://<host>:2379,https://<host>:2379,https://<host>:2379",
      "ha_enabled": "false",
      "path": "vault/",
      "tls_ca_file": "/run/vault/config/etcd.client.ca.crt",
      "tls_cert_file": "/run/vault/config/etcd.client.cert.crt",
      "tls_key_file": "/run/vault/config/etcd.client.key.pem"
    }
  },
  "cluster_name": "<name>",
  "default_lease_ttl": "31536000s",
  "ha_backend": {
    "zookeeper": {
      "address": "127.0.0.1:21181,127.0.0.1:21182,127.0.0.1:21183",
      "cluster_addr": "https://<this-host>:8201",
      "ha_enabled": "true",
      "path": "vault/",
      "redirect_addr": "https://<this-host>:8200"
    }
  },
  "listener": [
    {
      "tcp": {
        "address": "0.0.0.0:8200",
        "cluster_address": "0.0.0.0:8201",
        "tls_cert_file": "/run/vault/config/tls.cert",
        "tls_disable": "false",
        "tls_key_file": "/run/vault/config/tls.key"
      }
    }
  ],
  "max_lease_ttl": "94608000s"
}
```

**Comment by brianmulder** [comment]
Vault CLI version used to issue a write to test with for this note: v0.6.2

**Comment by brianmulder** [comment]
Confirmed. Reads (and presumably writes), using `curl -L` against the updated standby member on port 8200, are being client side redirected.

**Comment by jefferai** [comment]
What version of the Vault server are you coming from?

**Comment by jefferai** [comment]
To address each of you concerns separately:

@dforsber-p didn't respond with any details of versions or configuration, so I'll work on the assumption that it was during an upgrade like @brianmulder 

@brianmulder If I assume you're coming from 0.6.2 on the server as well, while I cannot offhand think of a change that was made that would cause this, that doesn't mean there wasn't one. However, please note that you're not intended to upgrade Vault clusters one node at a time over any kind of lengthy period of time. Vault does not guarantee backwards compatibility of its data store, and if you have a cluster with a single 0.7 node and it takes over from 0.6.X, and then that node loses active status back to a 0.6.X node, you *will* encounter problems. (I can modify our upgrade instructions to mention that the procedure outlined there is not meant to be performed over a long term.)

**Comment by brianmulder** [comment]
Thanks @jefferai.
Confirmed, we were upgrading from 0.6.2 and the errors in the logs stopped after the remainder of the cluster was upgraded.

As you expected, the single upgraded node was alone @ version 0.7.0 for a while.
