### ISSUE TITLE
missing EOF at 'GRANT'

### ISSUE THREAD

**Issue by ror6ax** [hashicorp/vault#2628]
When using this creation_cql - `CREATE USER '{{username}}' WITH PASSWORD '{{password}}' NOSUPERUSER; GRANT SELECT ON ALL KEYSPACES TO {{username}};`

with Cassnadra 3 I get error ` line 1:61 missing EOF at 'GRANT'` 

Works fine if I remove grant cql.
Vault 0.6.5

**Comment by jefferai** [comment]
@ror6ax Probably Cassandra 3 wants a different line; if you figure out what the equivalent Cassandra 3 command is, please submit a PR against the docs! (Can just edit them directly from GitHub, it's pretty easy.)
