### ISSUE TITLE
DynamoDB backend documentation does not describe required AWS permissions

### ISSUE THREAD

**Issue by alertedsnake** [hashicorp/vault#2629]
I noticed that on the [DynamoDB backend docs page](https://www.vaultproject.io/docs/configuration/storage/dynamodb.html) there is no mention of what permissions in AWS are required.  Obviously creating a user with the `AmazonDynamoDBFullAccess` policy works, but that's not really a best practice.

Can we have the minimum required permissions/policies explained on the documentation page?

**Comment by vishalnayak** [comment]
@alertedsnake Sure, we could add it to the docs, although I don't know the permissions list off-hand. If you figure out the necessary permission sets, please let us know, or submit a PR for that.

**Comment by jefferai** [comment]
Since the Dyanmo backend is community supported and the Vault team doesn't have any state here I'm going to close this in favor of an interested community member submitting a PR.

**Comment by mhmdio** [comment]
This worked with me
        {
          "Action": [
              "dynamodb:CreateTable",
              "dynamodb:BatchWriteItem",
              "dynamodb:UpdateItem",
              "dynamodb:BatchGetItem",
              "dynamodb:DescribeTable",
              "dynamodb:GetItem",
              "dynamodb:ListTables",
              "dynamodb:Query",
              "dynamodb:Scan",
              "dynamodb:DescribeReservedCapacity",
              "dynamodb:DescribeReservedCapacityOfferings",
              "dynamodb:ListTagsOfResource",
              "dynamodb:DescribeTimeToLive",
              "dynamodb:DescribeLimits"
          ],
          "Effect": "Allow",
          "Resource": "arn:aws:dynamodb:*:*:table/vault-dynamodb-backend"
      }

the table name will always be the same if you let Vault to create it for you.
