### ISSUE TITLE
Rotate of CMK operation is failed with 500 error

### ISSUE THREAD

**Issue by SwatiBaffle** [hashicorp/vault#26309]
Server returned  the error as below.This error thrown  using hash sdk apis

 Server returned HTTP response code: 500 for URL: https://<hashi ip address>:8200/v1/baffle/sdk-team/transit/keys/<trasitekey name>/rotate

Postman apis throw an error as below
 https://<hashi ip address>:8200/v1/baffle/sdk-team/transit/keys/<trasitekey name>/rotate

{
    "errors": [
        "1 error occurred:\n\t* put failed due to value being too large; got 1048749 bytes, max: 1048576 bytes\n\n"
    ]
}

how can this error be fixed?

is there way to delete specific  version of transit keys

**Comment by stevendpclark** [comment]
Hi @SwatiBaffle, I'm guessing that you have many key versions for the same key and have hit the limitation of the storage backend. 

You can use the [trim key](https://developer.hashicorp.com/vault/api-docs/secret/transit#trim-key) operation to delete older Transit key versions. Make sure they aren't being used (no data is encrypted with those key versions), that or that you have a proper backup of the keys first.

As we reserve GitHub issues for bug reports and feature requests, which this doesn't appear to be. As such, I'm going to close this and suggest that you ask about this on [Hashicorp Vault Discuss](https://discuss.hashicorp.com/c/vault/30) if you have any further questions.
