### ISSUE TITLE
Login page UI broken on Safari

### ISSUE THREAD

**Issue by Aransh** [hashicorp/vault#26311]
**Describe the bug**
The vault login page UI appears broken and squashed when using Safari (looks fine on Chrome for example), happens every time

**To Reproduce**
1. Open vault login page on Safari
2. behold:
![image](https://github.com/hashicorp/vault/assets/11724502/98c6f4a1-9d88-44f8-8f07-32ade0897742)
Can also scroll up a bit and see the vault logo is on the middle
![image](https://github.com/hashicorp/vault/assets/11724502/4d6eb663-c7d4-476d-b878-6eb8903c13b7)
And as I mentioned, all good on Chrome
![image](https://github.com/hashicorp/vault/assets/11724502/7b3e6555-4b26-4123-a906-d7544241f79d)

**Expected behavior**
Expect the UI to appear properly and consistently across browsers.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.14.0
* Vault CLI Version (retrieve with `vault version`): 1.15.6
* Server Operating System/Architecture: k8s 1.27 on LKE (Linode)

Vault server configuration file(s):

```hcl
ui = true
listener "tcp" {
   tls_disable = 0
   address = "[::]:8200"
   cluster_address = "[::]:8201"
   tls_cert_file = "/vault/vault-ha-tls/vault.crt"
   tls_key_file  = "/vault/vault-ha-tls/vault.key"
   tls_client_ca_file = "/vault/vault-ha-tls/vault.ca"
   telemetry {
      unauthenticated_metrics_access = "true"
   }
}
storage "raft" {
   path = "/vault/data"
}
disable_mlock = true
service_registration "kubernetes" {}
telemetry {
   prometheus_retention_time = "30s"
   disable_hostname = true
}
```

**Additional context**
Was not happening on previous versions of Vault, not sure which one this started on though

**Comment by Monkeychip** [comment]
@Aransh thank you for the issue, there was a fix for this that was backported to 1.14.1. See PR [here](https://github.com/hashicorp/vault/pull/21582).
