### ISSUE TITLE
Cassandra backend failure when host name can't be resolved

### ISSUE THREAD

**Issue by enudler** [hashicorp/vault#2635]
While configuring the cassandra backend connection via /v1/cassandra/config/connection
and at least one of the nodes can't be resolved an error occurs and vault won't try resolve other dns records.

Same behavior occurs also when the backend is configured and in use for getting cassandra credentials.

for example:

Request:

curl -X POST 
http://localhost:8200/v1/cassandra/config/connection 
-H 'content-type: application/json' 
-H 'x-vault-token: *' 
-d '{
"hosts": "127.0.0.1:9042,cant.resolve:9042",
"username": "cassandra",
"password": "cassandra",
"protocol_version": "3"
}'

Response:

{
"errors": [
"Error creating session: gocql: unable to create session: lookup cant.resolve on 8.8.8.8:53: no such host"
]
}

**Comment by jefferai** [comment]
Hi,

This behavior is from gocql; we simply pass it the list of hosts. If you want it to behave a different way please file an issue with them -- https://github.com/gocql/gocql . Thanks!
