### ISSUE TITLE
Can the page titles for all the backends be normalized?

### ISSUE THREAD

**Issue by ebekker** [hashicorp/vault#2636]
Can the page title format for all the backends (Auth, Audit, Secrets and Storage) be normalized?  Some of this was already cleaned up for the Secret backends in https://github.com/hashicorp/vault/commit/0fe2e84e3a559e68a25bbe6f622a37ec0ae47209 and Storage backends already seem to follow this nicer convention, but it would be nice to clean this up for all the remaining backends.

When looking at a few backends opened up in browser tabs, I think it would be helpful to have the name appear first so that it's quick to decipher what the page is about and then quickly identify which backend category it falls into.  Here's how they currently appear across the different categories:

<img width="575" alt="vault-backends-doctitles" src="https://cloud.githubusercontent.com/assets/3308726/25340385/96382c34-28d3-11e7-971f-430bc2eaf6d1.PNG">

**Comment by catsby** [comment]
Closing this because the follow-up PR was also closed https://github.com/hashicorp/vault/pull/2637#issuecomment-423574985
