### ISSUE TITLE
Add storage backend support for mongodb

### ISSUE THREAD

**Issue by ghazninattarshah** [hashicorp/vault#2639]

**Comment by ghazninattarshah** [comment]
Any reason why this is closed?

**Comment by jefferai** [comment]
It's not clear what is being asked here, given that there is no issue content -- is it a request for one, a mistaken PR that was filed as an issue but will add one, what. Either way, such a storage backend would be community-provided, so having an open issue for it does not cause any meaningful action; only via a community member submitting a PR will this get fulfilled, so there is no reason to leave an issue open against the project.

**Comment by ghazninattarshah** [comment]
I was asking to add secret backend support for mongodb, but I understood it's something that you expect from the community. Thanks for the reply @jefferai

**Comment by jefferai** [comment]
You're issue subject says storage, not secret... There's already a mongo secret backend!

**Comment by ghazninattarshah** [comment]
Sorry I was asking storage backend.
