### ISSUE TITLE
Repeated query on non-HA backend

### ISSUE THREAD

**Issue by horsehay** [hashicorp/vault#2640]
Upgraded from 0.6.4 to 0.6.5 today and now the postgresql backend is getting hit hard with the following queries over and over again:

```2017-04-24 22:28:53 UTC [29268-58/527192-9562] vault-rw@vault_sandbox LOG:  execute <unnamed>: SELECT value FROM "vault_kv_store" WHERE path = $1 AND key = $2
2017-04-24 22:28:53 UTC [29268-58/527192-9563] vault-rw@vault_sandbox DETAIL:  parameters: $1 = '/core/', $2 = 'keyring'
2017-04-24 22:28:53 UTC [29211-3/268350-9425] vault-rw@vault_sandbox LOG:  execute <unnamed>: SELECT value FROM "vault_kv_store" WHERE path = $1 AND key = $2
2017-04-24 22:28:53 UTC [29211-3/268350-9426] vault-rw@vault_sandbox DETAIL:  parameters: $1 = '/core/cluster/local/', $2 = 'info'
```

Also these errors when upgrading to 0.7.0 and then doing step-down from 0.6.5:

```
2017/04/24 17:21:56.437141 [INFO ] core: acquired lock, enabling active operation
2017/04/24 17:21:56.488203 [INFO ] core: post-unseal setup starting
2017/04/24 17:21:56.490462 [INFO ] core: loaded wrapping token key
2017/04/24 17:21:56.494690 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/04/24 17:21:56.494999 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/04/24 17:21:56.495214 [INFO ] core: successfully mounted backend: type=transit path=transit/
2017/04/24 17:21:56.495324 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/04/24 17:21:56.495516 [ERROR] core: failed to mount entry: path=cubbyhole/ error=cannot mount under existing mount 'cubbyhole/'
2017/04/24 17:21:56.495584 [INFO ] core: pre-seal teardown starting
2017/04/24 17:21:56.495607 [INFO ] core: cluster listeners not running
2017/04/24 17:21:56.495782 [INFO ] core: pre-seal teardown complete
2017/04/24 17:21:56.495829 [ERROR] core: post-unseal setup failed: error=failed to setup mount table
```

The vault cluster is running Zookeeper for HA backend, but Postgresql for storage backend. Looking at diffs, I can't see what is causing this to get queried over and over on the storage backend.

This issue is preventing me from upgrading to 0.7.0. Every time I do a step-down on the active node, the standbys do a bunch of database updates, but never become leader. Then the old leader picks up again where it left off.

I am wondering if the storage backend is still being checked for HA values even though it should not be.

**Comment by horsehay** [comment]
Or maybe related to the cubbyhole issue?

**Comment by jefferai** [comment]
Downgrading is not supported generally and definitely not from 0.7. You can delete core/local-mounts if you step down but will lose any data you had in cubbyhole. Please see our upgrade guide at https://www.vaultproject.io/docs/guides/upgrading/index.html for general and version specific information.

**Comment by horsehay** [comment]
Unfortunately, I never successfully upgraded. I saw the upgrade procedure for HA Installations. Rather than stopping vault on the active node, I used the step-down command. Would that cause any issues over actually terminating the process?

**Comment by jefferai** [comment]
It could, yes, because if the standby nodes fail to take over for some reason and active leadership flips back to 0.7, if the standby nodes were able to run some upgrade code, you have just downgraded -- which is exactly what you described, and will cause the duplicate cubbyhole issue.

**Comment by horsehay** [comment]
Thanks. I deleted the cubbyhole entry and shut down the active vault node to do proper upgrade and it took.
