### ISSUE TITLE
TSL whit Let's encrypt fail (bad certificate)  0.7

### ISSUE THREAD

**Issue by eivbsmed** [hashicorp/vault#2641]
Whit this config created from following this tutorial https://monterail.com/blog/2017/lets-encrypt-vault-free-ssl-tls-certificate
```
storage "file" {
  path = "vault"
}
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/etc/letsencrypt/live/domain.com/cert.pem"
  tls_key_file = "/etc/letsencrypt/live/domain.com/fullchain.pem"
}
disable_mlock = true
```
Starting vault give following error:
```
Error initializing listener of type tcp: error loading TLS cert: tls: failed to find PEM block with type ending in 
"PRIVATE KEY" in key input after skipping PEM blocks of the following types: [CERTIFICATE CERTIFICATE]
```

Then afther changing fullchain.pem to private.key vault starts but trying to connect the client whit ip or domain name fails in the following ways (Fist one is because i can't add the IP).

`Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: x509: cannot validate certificate for 12
7.0.0.1 because it doesn't contain any IP SANs` 

and whit using the domain 

`Error checking seal status: Get https://domain.com:8200/v1/sys/seal-status: x509: certificate signed by u
nknown authority`

The logs from vault is:
`2017/04/25 06:02:44 http: TLS handshake error from 127.0.0.1:43858: remote error: tls: bad certificate`
`2017/04/25 06:03:27 http: TLS handshake error from a.b.c.d:58520: remote error: tls: bad certificate`

Vault 0.7.0
Ubuntu 16.10

Posting this issue even if way it working could be a mistake on my side

**Comment by eivbsmed** [comment]
Tutorial was wrong. fullchain.pem should be given as  tls_cert_file and tls_key_file should be privkey.pem

**Comment by jefferai** [comment]
Please report that upstream to the blog author!
