### ISSUE TITLE
Unsupported path for sys health endpoint

### ISSUE THREAD

**Issue by dkyanakiev** [hashicorp/vault#26458]
**Describe the bug**
Hi,
I started encountering this bug and unfortunately I wasn't able to track when it was introduced.
I have a cli/tui that interacts with vault, however it started failing doing a health check to get version to do the initial setup.
The idea is to check if the vault instance is enterprise one and do a setup depending on it

The code block is straight forward:
```
         cfg := api.DefaultConfig()
	cfg.Address = vaultyCfg.VaultAddr

	tlsCfg := &api.TLSConfig{}

	if vaultyCfg.VaultCaCert != "" {
		tlsCfg.CACert = vaultyCfg.VaultCaCert
	}

	if vaultyCfg.VaultClientCert != "" {
		tlsCfg.ClientCert = vaultyCfg.VaultClientCert
	}

	if vaultyCfg.VaultClientKey != "" {
		tlsCfg.ClientKey = vaultyCfg.VaultClientKey
	}

	err := cfg.ConfigureTLS(tlsCfg)
	if err != nil {
		log.Error().Err(err).Msgf("Failed to configure TLS: %v", err)
		return err
	}

	client, err := api.NewClient(cfg)
	if err != nil {
		log.Error().Err(err).Msg("Failed to create Vault client")
		return err
	}

	client.SetToken(vaultyCfg.VaultToken)

	// Check if the client is successfully created by making a request to Vault

	health, err := client.Sys().Health()
	if err != nil {
		log.Error().Err(err).Msg("Failed to do healthcheck with Vault")
		return err
	}
```
However this is currently resulting in:
```
Failed to start Vault client: Error making API request.

Namespace: myns/
URL: GET https://<myURL>/v1/sys/health?drsecondarycode=299&performancestandbycode=299&sealedcode=299&standbycode=299&uninitcode=299
Code: 404. Errors:

* unsupported path
exit status 1
```

I've tried against a HCP Vault instance and a local dev server - no issue. 
However the moment I try against a the vault instances we have configured I run into this issue. Is there something that 

**To Reproduce**
Code block is above. Try to access the `/v1/sys/health` endpoint

**Expected behavior**
To receive a [HealthResponse](https://github.com/hashicorp/vault/blob/api/v1.12.2/api/sys_health.go#L40C6-L40C20) correctly 

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.15.4+ent
* Vault API Version : github.com/hashicorp/vault/api v1.12.2
* Server Operating System/Architecture: macOS Sonoma 14.1.1

**Comment by hsimon-hashicorp** [comment]
As you are running an enterprise version, are you able to open a support ticket for this? You may receive a faster response that way.
Thanks!
https://support.hashicorp.com/hc/en-us/requests/new

**Comment by arightious** [comment]
@dkyanakiev the issue here is that `sys/health` can only be called from the root namespace. In your example, you are trying to call the endpoint from the `myns/` namespace.

```
curl -H "X-Vault-Token: $(vault print token)" -H "X-Vault-Request: true" -H "X-Vault-Namespace: ns1/" http://127.0.0.1:8200/v1/sys/health
{"errors":["unsupported path"]}
```

Change the request to root and you should be good to go.

`curl -H "X-Vault-Token: $(vault print token)" -H "X-Vault-Request: true" http://127.0.0.1:8200/v1/sys/health`

```
{"initialized":true,"sealed":false,"standby":false,"performance_standby":false,"replication_performance_mode":"primary","replication_dr_mode":"disabled","server_time_utc":1724341014,"version":"1.16.2+ent","enterprise":true,"cluster_name":"vault-main","cluster_id":"a7006434-1bb1-21d4-02a2-35f54867d421","last_wal":541,"license":{"state":"autoloaded","expiry_time":"9999-12-31T00:00:00Z","terminated":false},"echo_duration_ms":0,"clock_skew_ms":0}
```

**Comment by heatherezell** [comment]
Thank you @arightious! Given that, I'll go ahead and close this issue now. Thanks!
