### ISSUE TITLE
Feature request: Update mount description

### ISSUE THREAD

**Issue by djenriquez** [hashicorp/vault#2645]
Currently we don't have a way to update the description of a mount. If we forget to set it, or don't have an accurate description, we're SOL.

**Comment by gw4thanize** [comment]
Same thing with auth backend description as well. We need to be able to add a description after auth backend & mount are created.

**Comment by Midacts** [comment]
Can you provide an example of how to update the description of a mount?

**Comment by jefferai** [comment]
You can do it via a POST; see https://www.vaultproject.io/api/system/mounts.html#tune-mount-configuration
