### ISSUE TITLE
Vault v0.7 /pki/sign doesn't work

### ISSUE THREAD

**Issue by dhawal55** [hashicorp/vault#2648]
Enable to generate certs using csr in v0.7.

Here's my csr:
`{"csr":"-----BEGIN CERTIFICATE REQUEST-----\nMIIEoTCCAokCAQAwMzExMC8GA1UEAwwoa3ViZWxldC5pbmZyYS5wbGF0Zm9ybS5y\nNTMubm9yZHN0cm9tLm5ldDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB\nAMZaz2LHtEHJXt2rg/bHF47/0IQpD/0e1FYTbLKTqYa8e2T++Z6/L0IAfJGsuKLx\nLP8iV2+dQ2956W65khXUx3zmxjUfmW8Fv6mWUZeNEz5NPwVvHW1Bkz3JrD7pw0pf\nwaYT2024nd1MOMCS7IKEJ5UueWWuBXO3QKjMkyvFNPEa4jKpaGSqn1uCTSJzDZVM\nTWcFb6De5qds4fWJig6zaX5YY8THzaRPZ9zQ9mIP7vw+f13kVvp/f/hJ4bM35yKA\nlUBEve8bBlTX50e6GJqixBIl+pWUagWUsxvmgQVF/CMcyxb8QSgwSUE893697HHB\n52/Kll8AdStoC28szDreOs5OOuVXmY3b+KvyEbrdYM+CHTjFen3dw+wmSV9Mbw5d\nOWZi+Y44tZx8ot0GJWo90z9JJS+xufBqmEUkFfeUjDUxR3v18nN8oajQP/Rq3dpR\nyS4tJrXoazO5r9z4YO1XVBSEfSgPUfVuNx29jo+LOxnNna/Ls4p5MlnFC7src6cd\n78HdprVxIUa3hyWTJlp91vrmkIHCRQxRgC/It0w1JmtSAn/aO8id6txnXDPnIPw1\n4h/1IR4nlzzbxnutxC1++AbQ9GVXmWdir0efE6dmkQGFHLmhUGi/E1YiH3Qqtq6U\nEYCQGmr3yDY0zENeGQE0TitRNTLXON2QWbGdofhBXcYZAgMBAAGgKTAnBgkqhkiG\n9w0BCQ4xGjAYMAkGA1UdEwQCMAAwCwYDVR0PBAQDAgXgMA0GCSqGSIb3DQEBBQUA\nA4ICAQAO1Gli+JC+5lvCDWglXWrunzRHzmlx0zlUFgA7SFAoW82N1ulFhDI0K8po\nTHt1zrrLdEN24zIHMDKF/TzteTtOR/N7A3WYq25WsW5PvVo9c1CbvYGenc5sCoaD\naa2oLAgwUG714NaY1y1dUnjfejwaO4/YkaqWfWT8jI+A4iR9iosMjwrkxtjJclZc\n+bJ9SObQiljlBdYmFpXiPb57tnreu7SnG4xNUs2mX00nSN/DvIy0XhnPDOQZIC5B\nCeoKvWbAaEu1itWZ7oNqfVWa1hxCWj0mc9OLjDKDjPLiiQfkNd1a08FdRMhykKWy\nF+LbtVtTRE/A+QzBDokDbYrHGkf0nRe1vY7CSf/Y5m8QRk1cs+fwM0TJD/vUGRv0\n+3NRXcRjkvQ8iA0kk2I2s1vxd6zNgExingF0MoItnTD/dSQbQfSetT+iPJvqtOfn\n3DAzA5D+r8c9JnGNEkzAVNY9Kw6F8cmn1w2qLpaJn+YXOYnzDik2cRdfC4Bf7qA1\nkFaC61MgYKgDP49GlU0RJrO7GmYUfXrhya2PnRMhPJIDuTzevo9wo/zqEiZgkEQ8\nIZb24wfmkwpg8/+p3XVrtg3JIBNk7vBAcOa/uaqjF/BJXi/UkHgXf1FRdVIpT4i7\nWeUcbUrZ4cSZTOwHymxRhi9Q4Gy45K6AzP2P5Vmm9IWjWMzeSQ==\n-----END CERTIFICATE REQUEST-----","common_name":"kubelet.infra.platform.r53.nordstrom.net","exclude_cn_from_sans":true}
`

Response:
{"errors":["\"csr\" is empty"]}

**Comment by jefferai** [comment]
Hi @dhawal55 ,

You didn't provide any information about how you are supplying this string, but PEM encoding is sensitive to new lines. If you are providing that string as you've displayed here into e.g. the Vault CLI when it encodes the JSON you'll end up with double-escaped newlines and that will make the PEM decoding unhappy.

You can work around this either by providing it to Vault's API as your own JSON, e.g. this works:
```
curl -X PUT -H "X-Vault-Token: root" http://127.0.0.1:8200/v1/pki/sign/test -d '{"csr":"-----BEGIN CERTIFICATE REQUEST-----\nMIIEoTCCAokCAQAwMzExMC8GA1UEAwwoa3ViZWxldC5pbmZyYS5wbGF0Zm9ybS5y\nNTMubm9yZHN0cm9tLm5ldDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB\nAMZaz2LHtEHJXt2rg/bHF47/0IQpD/0e1FYTbLKTqYa8e2T++Z6/L0IAfJGsuKLx\nLP8iV2+dQ2956W65khXUx3zmxjUfmW8Fv6mWUZeNEz5NPwVvHW1Bkz3JrD7pw0pf\nwaYT2024nd1MOMCS7IKEJ5UueWWuBXO3QKjMkyvFNPEa4jKpaGSqn1uCTSJzDZVM\nTWcFb6De5qds4fWJig6zaX5YY8THzaRPZ9zQ9mIP7vw+f13kVvp/f/hJ4bM35yKA\nlUBEve8bBlTX50e6GJqixBIl+pWUagWUsxvmgQVF/CMcyxb8QSgwSUE893697HHB\n52/Kll8AdStoC28szDreOs5OOuVXmY3b+KvyEbrdYM+CHTjFen3dw+wmSV9Mbw5d\nOWZi+Y44tZx8ot0GJWo90z9JJS+xufBqmEUkFfeUjDUxR3v18nN8oajQP/Rq3dpR\nyS4tJrXoazO5r9z4YO1XVBSEfSgPUfVuNx29jo+LOxnNna/Ls4p5MlnFC7src6cd\n78HdprVxIUa3hyWTJlp91vrmkIHCRQxRgC/It0w1JmtSAn/aO8id6txnXDPnIPw1\n4h/1IR4nlzzbxnutxC1++AbQ9GVXmWdir0efE6dmkQGFHLmhUGi/E1YiH3Qqtq6U\nEYCQGmr3yDY0zENeGQE0TitRNTLXON2QWbGdofhBXcYZAgMBAAGgKTAnBgkqhkiG\n9w0BCQ4xGjAYMAkGA1UdEwQCMAAwCwYDVR0PBAQDAgXgMA0GCSqGSIb3DQEBBQUA\nA4ICAQAO1Gli+JC+5lvCDWglXWrunzRHzmlx0zlUFgA7SFAoW82N1ulFhDI0K8po\nTHt1zrrLdEN24zIHMDKF/TzteTtOR/N7A3WYq25WsW5PvVo9c1CbvYGenc5sCoaD\naa2oLAgwUG714NaY1y1dUnjfejwaO4/YkaqWfWT8jI+A4iR9iosMjwrkxtjJclZc\n+bJ9SObQiljlBdYmFpXiPb57tnreu7SnG4xNUs2mX00nSN/DvIy0XhnPDOQZIC5B\nCeoKvWbAaEu1itWZ7oNqfVWa1hxCWj0mc9OLjDKDjPLiiQfkNd1a08FdRMhykKWy\nF+LbtVtTRE/A+QzBDokDbYrHGkf0nRe1vY7CSf/Y5m8QRk1cs+fwM0TJD/vUGRv0\n+3NRXcRjkvQ8iA0kk2I2s1vxd6zNgExingF0MoItnTD/dSQbQfSetT+iPJvqtOfn\n3DAzA5D+r8c9JnGNEkzAVNY9Kw6F8cmn1w2qLpaJn+YXOYnzDik2cRdfC4Bf7qA1\nkFaC61MgYKgDP49GlU0RJrO7GmYUfXrhya2PnRMhPJIDuTzevo9wo/zqEiZgkEQ8\nIZb24wfmkwpg8/+p3XVrtg3JIBNk7vBAcOa/uaqjF/BJXi/UkHgXf1FRdVIpT4i7\nWeUcbUrZ4cSZTOwHymxRhi9Q4Gy45K6AzP2P5Vmm9IWjWMzeSQ==\n-----END CERTIFICATE REQUEST-----","common_name":"kubelet.infra.platform.r53.nordstrom.net","exclude_cn_from_sans":true}'
```
or if you want to use the vault CLI, you'll need to keep newline formatting in place, either via using @ syntax to load the formatting (e.g. `vault write pki/sign/test csr=@mycert.csr`) or simply keeping them intact directly:
```
vault write pki/sign/test common_name=example.com csr="-----BEGIN CERTIFICATE REQUEST-----
> MIIEoTCCAokCAQAwMzExMC8GA1UEAwwoa3ViZWxldC5pbmZyYS5wbGF0Zm9ybS5y
> NTMubm9yZHN0cm9tLm5ldDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
> AMZaz2LHtEHJXt2rg/bHF47/0IQpD/0e1FYTbLKTqYa8e2T++Z6/L0IAfJGsuKLx
> LP8iV2+dQ2956W65khXUx3zmxjUfmW8Fv6mWUZeNEz5NPwVvHW1Bkz3JrD7pw0pf
> waYT2024nd1MOMCS7IKEJ5UueWWuBXO3QKjMkyvFNPEa4jKpaGSqn1uCTSJzDZVM
> TWcFb6De5qds4fWJig6zaX5YY8THzaRPZ9zQ9mIP7vw+f13kVvp/f/hJ4bM35yKA
> lUBEve8bBlTX50e6GJqixBIl+pWUagWUsxvmgQVF/CMcyxb8QSgwSUE893697HHB
> 52/Kll8AdStoC28szDreOs5OOuVXmY3b+KvyEbrdYM+CHTjFen3dw+wmSV9Mbw5d
> OWZi+Y44tZx8ot0GJWo90z9JJS+xufBqmEUkFfeUjDUxR3v18nN8oajQP/Rq3dpR
> yS4tJrXoazO5r9z4YO1XVBSEfSgPUfVuNx29jo+LOxnNna/Ls4p5MlnFC7src6cd
> 78HdprVxIUa3hyWTJlp91vrmkIHCRQxRgC/It0w1JmtSAn/aO8id6txnXDPnIPw1
> 4h/1IR4nlzzbxnutxC1++AbQ9GVXmWdir0efE6dmkQGFHLmhUGi/E1YiH3Qqtq6U
> EYCQGmr3yDY0zENeGQE0TitRNTLXON2QWbGdofhBXcYZAgMBAAGgKTAnBgkqhkiG
> 9w0BCQ4xGjAYMAkGA1UdEwQCMAAwCwYDVR0PBAQDAgXgMA0GCSqGSIb3DQEBBQUA
> A4ICAQAO1Gli+JC+5lvCDWglXWrunzRHzmlx0zlUFgA7SFAoW82N1ulFhDI0K8po
> THt1zrrLdEN24zIHMDKF/TzteTtOR/N7A3WYq25WsW5PvVo9c1CbvYGenc5sCoaD
> aa2oLAgwUG714NaY1y1dUnjfejwaO4/YkaqWfWT8jI+A4iR9iosMjwrkxtjJclZc
> +bJ9SObQiljlBdYmFpXiPb57tnreu7SnG4xNUs2mX00nSN/DvIy0XhnPDOQZIC5B
> CeoKvWbAaEu1itWZ7oNqfVWa1hxCWj0mc9OLjDKDjPLiiQfkNd1a08FdRMhykKWy
> F+LbtVtTRE/A+QzBDokDbYrHGkf0nRe1vY7CSf/Y5m8QRk1cs+fwM0TJD/vUGRv0
> +3NRXcRjkvQ8iA0kk2I2s1vxd6zNgExingF0MoItnTD/dSQbQfSetT+iPJvqtOfn
> 3DAzA5D+r8c9JnGNEkzAVNY9Kw6F8cmn1w2qLpaJn+YXOYnzDik2cRdfC4Bf7qA1
> kFaC61MgYKgDP49GlU0RJrO7GmYUfXrhya2PnRMhPJIDuTzevo9wo/zqEiZgkEQ8
> IZb24wfmkwpg8/+p3XVrtg3JIBNk7vBAcOa/uaqjF/BJXi/UkHgXf1FRdVIpT4i7
> WeUcbUrZ4cSZTOwHymxRhi9Q4Gy45K6AzP2P5Vmm9IWjWMzeSQ==
> -----END CERTIFICATE REQUEST-----"
```
Both will work!
