### ISSUE TITLE
Vault Crash with Okta if can't find the hostname

### ISSUE THREAD

**Issue by guerremdq** [hashicorp/vault#2649]
Hi i was configuring Okta authentication in Vault and i make mistake in the okta base url when i try to log in Vault crash.

```
2017/04/27 11:14:42.282839 [INFO ] rollback: starting rollback manager
2017/04/27 11:14:42.283098 [INFO ] core: post-unseal setup complete
2017/04/27 11:15:33.514027 [INFO ] core: enabled credential backend: path=okta/ type=okta
2017/04/27 11:18:25 Post Xxxxxxx.oktax.com/api/v1/authn: dial tcp: lookup XXXxx.Xxxxxx on 10.5.0.2:53: no such host
root@ip-10-5-3-75:~#
root@ip-10-5-3-75:~# vault --version
Vault v0.7.0 ('614deacfca3f3b7162bbf30a36d6fc7362cd47f0')
```

**Comment by jefferai** [comment]
Hi @guerremdq ,

If Vault crashed you should have gotten a traceback -- can you look for it and provide it?

**Comment by guerremdq** [comment]
@jefferai There is not traceback.

To reproduce it 
```
export VAULT_ADDR='http://127.0.0.1:8200'
vault auth-enable okta
vault write auth/okta/config base_url="crash-vault.idontexiste.net" organization=Vaul-test token='XXXXXXXXX'
vault auth -method=okta username=guerremdq
```

<img width="1665" alt="screen shot 2017-04-27 at 15 36 52" src="https://cloud.githubusercontent.com/assets/476513/25485855/a059516e-2b5f-11e7-9980-b3904bdc7668.png">

**Comment by jefferai** [comment]
I can reproduce this and it's _seriously_ weird. Will dig in...

**Comment by jefferai** [comment]
Here's a cool story: a library that calls `Fatal` on error -- https://github.com/sstarcher/go-okta/blob/master/api.go#L98

Not sure what the right path forward is but will either need to get the author to fix this or fork the library.

**Comment by jefferai** [comment]
Ref: https://github.com/sstarcher/go-okta/pull/2

**Comment by sean-** [comment]
Which path are you inclined to take? Fix the panic in the vendored version of the lib or wrap calls to Okla in recover() in the interim (and splat a big nasty warning to the world)?

--
Sean Chittenden
seanc@joyent.com

**Comment by jefferai** [comment]
@sean- It's not a panic, it's a `log.Fatal` call so `recover()` doesn't do anything. I've already submitted a PR to the library author (see previous comment).
