### ISSUE TITLE
Cannot copy data using UI

### ISSUE THREAD

**Issue by esesyn01** [hashicorp/vault#26492]
**Describe the bug**
After update to 1.16.1 from 1.15.2, any secret (from kv, user token etc.) cannot be copied using the Copy to clipboard button, Although, the user has permissions to this secrets and they can be copied using Ctrl-c on unmasked value.

![image](https://github.com/hashicorp/vault/assets/81929485/69326d3c-f551-4506-9351-682efee5bce1)

**To Reproduce**
1. Login to vault
2. Navigate to any secret
3. Click "Copy to clipboard" button

**Expected behavior**
Data present in clipboard

**Environment:**
* Vault Community Edition Docker 1.16.1
* Google Chrome version 124.0.6367.61 (latest by this time)

Vault server configuration file(s):

```hcl
ui = true
disable_mlock = true

storage "raft" {
  path    = "./some/path"
  node_id = "node3"
}

listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = "true"
}

api_addr = "http://127.0.0.1:8200"
cluster_addr = "https://127.0.0.1:8201"

```

Policy:
```
path "secrets/path/*" {
  capabilities = ["create", "read", "update", "patch", "delete", "list"]
}
```

**Comment by zijiwork** [comment]
Have you tried accessing the vault using https?

**Comment by marcboudreau** [comment]
@esesyn01 I'm trying to reproduce this issue. Can you help me by clarifying the following point? Is the KV secrets engine in question using version 1 or version 2 of the API? The version appears next to the mount path in the UI as shown here:
![image](https://github.com/hashicorp/vault/assets/5696632/05c418cc-6c84-4326-959c-d3b9fdaf8cbf)
or
![image](https://github.com/hashicorp/vault/assets/5696632/40f8f76e-9cd9-48ff-8f71-1f043e43893a)

**Comment by zijiwork** [comment]
<img width="679" alt="image" src="https://github.com/hashicorp/vault/assets/24753365/789522a0-cfba-44ea-b97d-5e9f7b178cc4">


<img width="1134" alt="image" src="https://github.com/hashicorp/vault/assets/24753365/0cff43a5-09e4-46b7-84be-02831fdbbf68">

<img width="1337" alt="image" src="https://github.com/hashicorp/vault/assets/24753365/e176b322-d0a8-4dff-b757-e127e339a051">

**Comment by esesyn01** [comment]
> Have you tried accessing the vault using https?

I'm connecting through http, I will try the https instead

**Comment by esesyn01** [comment]
> @esesyn01 I'm trying to reproduce this issue. Can you help me by clarifying the following point? Is the KV secrets engine in question using version 1 or version 2 of the API? The version appears next to the mount path in the UI as shown here: ![image](https://private-user-images.githubusercontent.com/5696632/326565377-05c418cc-6c84-4326-959c-d3b9fdaf8cbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjU2OTgsIm5iZiI6MTcxNDQ2NTM5OCwicGF0aCI6Ii81Njk2NjMyLzMyNjU2NTM3Ny0wNWM0MThjYy02Yzg0LTQzMjYtOTU5Yy1kM2I5ZmRhZjhjYmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MzBUMDgyMzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzc2NTdkNGI5MWMzYzM2NjNhYjg5YjNlZWQ5YTAzZTYxZmViNzcwZmE0NTliYjU3NzUzMzg0ODNjMjhhZDg1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pqlMK8gbD8iQtvGL3_zObJ0zp8h8BPRIATp-eEZRsZg) or ![image](https://private-user-images.githubusercontent.com/5696632/326565425-40f8f76e-9cd9-48ff-8f71-1f043e43893a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjU2OTgsIm5iZiI6MTcxNDQ2NTM5OCwicGF0aCI6Ii81Njk2NjMyLzMyNjU2NTQyNS00MGY4Zjc2ZS05Y2Q5LTQ4ZmYtOGY3MS0xZjA0M2U0Mzg5M2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MzBUMDgyMzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzA5MWJkZWVmMGEwYWUyMDQ0N2RjMzNkMjQ5MzYyYTA2MDczNmY5NWI0OWJiYzU1ZWQwZWM5ZDAzODczMTM5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.C8EDS0ZR8303qPFRIR5VvLyp8RtzJwAsc9WIhGDO2RQ)

It's version 2 @marcboudreau

**Comment by marcboudreau** [comment]
Something that struck me is that the you included in the issue description is not valid as is. If your KV secrets engine is mounted at `secrets/`, this minimalistic policy will allow copying from `secrets` > `folder1` > `secret`:
```
path "secrets/data/folder1/secret" {
  capabilities = ["read"]
}
```

This policy won't allow you to navigate to the secret by typing, but if prompted for a secret path, you can enter `secrets/folder1/secret` and the obfuscated secret details will be shown. You can click the copy to clipboard icon next to a key and its value will be copied.

The above policy can be augmented to allow navigation to any key within the KV secrets engine mounted at `secrets/` as follows:
```
path "secrets/data/folder1/secret" {
  capabilities = ["read"]
}

path "secrets/metadata/*" {
  capabilities = ["list"]
}
```

**Comment by Monkeychip** [comment]
We have updated the language on the flash message to mention that the CopyClipboard api requires a secure context, e.g. https vs http—PR [here](https://github.com/hashicorp/vault/pull/27045). I'm going to go ahead and close this ticket.
