### ISSUE TITLE
Vault client SSH CA sing return '\n' in JSON

### ISSUE THREAD

**Issue by guerremdq** [hashicorp/vault#2653]
Hi Guys,

I'm using the SSH CA to sing users key if the output format is JSON i get a **\n** in the last part of the signed_key. 

```
cat .ssh/id_rsa.pub | vault write -format=json ssh-client-signer/sign/clientrole public_key=-

{
    "data": {
        "serial_number": "fcae73846c602854",
        "signed_key": "ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAgYIxrh66bb2Iwen8BB0csD7DKMu4b9lwoO25/D9VHwq4AAAADAQABAAABAQDBnlLnCtFUZPdYMmd0FYdbCKXxXBsZMBl1LurzDm2J9zoHHfqlxYWWCaZkHPOs1JKjLSXIb2THBqLdv7jlHHOWR6PWvUFC0PsDKGiwNppJSxVGqa2djJSe//nhb/uJWQP/OHRQ5iS/tCj+KYdS6iAkstok2vNC7Y66UVMB6pxVRK5uD1hKRxgJecb7qYBpt6cOlWu1AdzwjvrG9M4p5fsoCdXl6kRvRtINZ5qPgrT3f/G8227mEMhZq5IPRlTnq4l4vAENEF7G9FeBtf3rGNAHi7cZ6Tr+r69SQetk1HfsgEjVVW9MOo1fcLhb4MGZXKyfksyfbl0rghDjj3tnwAvX/K5zhGxgKFQAAAABAAAAZHZhdWx0LW9rdGEtZmFjdW5kby5ndWVycmVyb0BvbHguY29tLWI0NDVkMzU0YTk1MDhlZmZkOGVmOGZhM2IxODQyODJmZGM2MTA2ZjkxNzRkN2VjODZhZDQzOGUxMDdiZjgyZWUAAAAKAAAABnVidW50dQAAAABZAvkTAAAAAFkDADkAAAAAAAAAEgAAAApwZXJtaXQtcHR5AAAAAAAAAAAAAAIXAAAAB3NzaC1yc2EAAAADAQABAAACAQDGOTQrryP+YdORaXbmwH9qk18UGVr9V9bYgAjndXdrHU2T+CrrTv1nzEAwbDrZPmfJtaAwi5ZXnZtaAAXTK2JiMnhPclXu5bJZ60kOwjcaTN4hJzg14fqIZq5m0d6BBcMHFc8wFFxapHhgsXZG4ztxjfiQcCr290U2RHIx3PIeUiDhCOiZCGhAZ8SIUkMK7Ra7IX+fQnqs+WGmii9BXmULWA62PSuWJoVG/uFU6iV/5vD79Zlsh4hspDj25J9Uzrygtcl2cxGvc4sd9UdrIQZj9O7X6TbHUiDkEIIz6ZxSvozfwWKVC1yuEBuw8iwvtgyzmM47l+MvMt8Nw3YrJe885k8iUd9Xore6WZt2uchLqVLs5fy+D13zDNCkMeseNfGGPBXNXdWfXxb6dSQN75loIrQhwomB3gJaWE+a1J/B5VbjR3qBKLBpdURB7wbVRQU2mUog+jX/X1x72P5Qdso5CVFpe3j/80ASVeWYdrqM8RXbVRXKR7CNDE2/q0ftSrQq0FWqo23WwdXhOSvRs1iukajvDMkXrofL3j8vJDIqdJI7FwGMWJnBFQMwzsW9Dj9k1/z2QKx0kgwtcjkFo0Ze7Hn+DrO/29ILCgZaKiWc5cQ+2xAqgAcRqpHnjriaD/LpYiuHwzTFdoQs7/pMYnEzsYnnLNUY/qpNhUC/fzR1+QAAAg8AAAAHc3NoLXJzYQAAAgCCdO6VagNNf11/NAySYRCvrQnte6wvrh9aR5lZhKBLUyl0KHQxtWvCwAyqWMqA07dTYB0TaAcxF7EaYrRPocohAdffMLWjkga+lgBiHVZcldh1R5A1rkkzpGfJ48mCpfov1FsLqGtX8QHeSE20tAEu/5+0PbJ0msD3o/LKcnMYZPIXtKgB6L22NjeYKQO01tqLNWsQzDNogKjqpBe2SlgjO0MSAcGgLW4fGZegHzVsuogLfnPj2Je3eNau1iDefLIlkmx7eUZ3MPKbSjyOMbqf++Htx7bYuq9wWoNP5bruRsukTQG/A0u2oJmPA3C80NuE3/revAZ99xCSgKtZn4O6avhRpWHR/KvZNBuu9X5dJmufLBflK5qMP72GB1kzggGgDdhOay8IT6M6T6DoYNYHLuxdg81enMDpLPVrIE4yFZjAAmMXuAbXXxceX6K1tpRJ5vyl5yCWstl6k/ad/+AopceYiyF3z7+NYDkGD9y1K5b1Ocqe9LS4i8b+wuHR4E8KhqbqN+y4ECeCR+KVM2fJ6RTXx8M9zwZCH+7QyN0ruZEjot/kzme3q++iRUwrn7bfyxAUuG+tI5WHRZdREYpM6k+Yoya2DLL6gPsBzNKj4fYEt8Wxc1rToIRwzyRYvgjAwKXes8f8hzRuc6i5r27NW1lZUM1X2o5GFSJQZYJdVw==\n"
    },
    "lease_duration": 0,
    "lease_id": "",
    "renewable": false,
    "request_id": "02834374-ed03-7eb4-e35d-dde0e3045974",
    "warnings": null
}
```

**Comment by vishalnayak** [comment]
@guerremdq The command you are using should *not* include the `\n`. The response you are getting from the API does not include the `\n`. If you are using a response formatting tool like `jq`, that could add it, which can be resolved by using options on those tools to avoid `\n`s.

**Comment by guerremdq** [comment]
@vishalnayak I'm not using any tool to format the json is the output of the vault client

**Comment by vishalnayak** [comment]
@guerremdq Oh, I see. Had not noticed the `-format=json` there. It is from the integrated CLI JSON formatter, which indents the output. Let me check if that can be fixed.

**Comment by jefferai** [comment]
@guerremdq As a workaround, if instead you use `-field=signed_key` does that work for you?

**Comment by vishalnayak** [comment]
@guerremdq Unfortunately, it can't be fixed. Jeff's recommendation should help you as a workaround. He also had suggested that we add the unparsed response in the `api.Secret` struct so people can parse it the way they want, in a way that avoids the `\n`. I've made that change in #2662. Hoping that it resolves this issue.

**Comment by vishalnayak** [comment]
@guerremdq Apparently, we can't fix provide `raw` in `api.Secret` too. Closing this issue for now, assuming that `-field` is a fine workaround.

**Comment by tannerjonj** [comment]
Just wondering how you would code the equivalent -field=signed_key if I'm using the http api (rest api)?  I have verified that using the -field=signed_key in the CLI fixes my issue but I need to make the call to vault via rest api in order to pass the request across the network.  

Here is my.json file for the http api call
{
  "ttl": "1h",
  "valid_principals": "ansible",
  "public_key": "ssh-rsa ...."
}

curl -H "X-Vault-Token: xxx-xxxx-xxxx-xxxx" --request POST --data @my.json http://10.20.30.40:8300/v1/ssh-client-signer/sign/clientrole

**Comment by jefferai** [comment]
@tannerjonj You have to massage the JSON yourself. The CLI is simply parsing the JSON for you and extracting a single field.
