### ISSUE TITLE
Makefile Error: Gox called incorrectly in make

### ISSUE THREAD

**Issue by aakarshit-batchu** [hashicorp/vault#2654]
_I am using go1.7 I've just cloned the repo into the appropriate place in my GOPATH. Did Run make bootstrap and Running make gives an error that looks like it's calling gox with an unsupported flag or similar:_

root@ip-***-**-*-**:~/gowork/src/github.com/hashicorp/vault# make
go generate
==> Removing old directory...
==> Building...
flag provided but not defined: -tags
Usage: gox [options] [packages]

  Gox cross-compiles Go applications in parallel.

  If no specific operating systes or architectures are specified, Gox
  will build for all pairs supported by your version of Go.

Options:

  -arch=""            Space-separated list of architectures to build for
  -build-toolchain    Build cross-compilation toolchain
  -ldflags=""         Additional '-ldflags' value to pass to go build
  -os=""              Space-separated list of operating systems to build for
  -osarch=""          Space-separated list of os/arch pairs to build for
  -output="foo"       Output path template. See below for more info
  -parallel=-1        Amount of parallelism, defaults to number of CPUs
  -verbose            Verbose mode

Output path template:

  The output path for the compiled binaries is specified with the
  "-output" flag. The value is a string that is a Go text template.
  The default value is "{{.Dir}}_{{.OS}}_{{.Arch}}". The variables and
  their values should be self-explanatory.

Platforms (OS/Arch):

  The operating systems and architectures to cross-compile for may be
  specified with the "-arch" and "-os" flags. These are space separated lists
  of valid GOOS/GOARCH values to build for, respectively. You may prefix an
  OS or Arch with "!" to negate and not build for that platform. If the list
  is made up of only negations, then the negations will come from the default
  list.

  Additionally, the "-osarch" flag may be used to specify complete os/arch
  pairs that should be built or ignored. The syntax for this is what you would
  expect: "darwin/amd64" would be a valid osarch value. Multiple can be space
  separated. An os/arch pair can begin with "!" to not build for that platform.

  The "-osarch" flag has the highest precedent when determing whether to
  build for a platform. If it is included in the "-osarch" list, it will be
  built even if the specific os and arch is negated in "-os" and "-arch",
  respectively.

Makefile:19: recipe for target 'dev' failed
make: *** [dev] Error 2

**Comment by jefferai** [comment]
I don't know if this is the specific reason for the error, bit Go 1.8 is required for Vault. I suggest updating to that and seeing if that fixes the problem. You may also want to ensure that you have an updated version of gox... If you had a previous version I'm not sure if the makefile runs an update or not.

**Comment by aakarshit-batchu** [comment]
Thanks @jefferai for quick reply.
As you have suggested tried with Go 1.8 and also updated version of gox. Yet i am facing the same issue. Can you please help me with that?

And also i want to know whether there is plugin support to develop new Secret Backends for Vault. We want to use OrientDB as Secret Backend. So is there any plugin support or guide to develop a Secret Backend?

**Comment by jefferai** [comment]
@aakarshit-batchu do you have a `BUILD_TAGS` env var defined? That could cause the problem you're seeing (not sure what else could, though). Does it work if you use `make dev` instead of `make`?

New secret backends can be created; we are migrating to a plugin-based approach for databases, see #2200

**Comment by aakarshit-batchu** [comment]
@jefferai  the BUILD_TAGS env var has been assigned with value "vault" in Makefile. And yeah I have tried with make dev also. It throws same error.

So is there any guide or documentation on creating new secret backends using that plugin-based approach for databases? Any Steps on how to develop and add new secret backend for vault will help.

I went through your documentation in the official site and found this. Mentioned "Vault doesn't currently support the creation of custom secret backends".

https://www.vaultproject.io/docs/secrets/custom.html

**Comment by jefferai** [comment]
> You may also want to ensure that you have an updated version of gox... If you had a previous version I'm not sure if the makefile runs an update or not.

I am fairly certain you did not actually update your version of `gox` and that is the root of this issue.

**Comment by jefferai** [comment]
Here's the output I get from gox -h:
```
$ gox -h
Usage: gox [options] [packages]

  Gox cross-compiles Go applications in parallel.

  If no specific operating systems or architectures are specified, Gox
  will build for all pairs supported by your version of Go.

Options:

  -arch=""            Space-separated list of architectures to build for
  -build-toolchain    Build cross-compilation toolchain
  -cgo                Sets CGO_ENABLED=1, requires proper C toolchain (advanced)
  -gcflags=""         Additional '-gcflags' value to pass to go build
  -ldflags=""         Additional '-ldflags' value to pass to go build
  -tags=""            Additional '-tags' value to pass to go build
  -os=""              Space-separated list of operating systems to build for
  -osarch=""          Space-separated list of os/arch pairs to build for
  -osarch-list        List supported os/arch pairs for your Go version
  -output="foo"       Output path template. See below for more info
  -parallel=-1        Amount of parallelism, defaults to number of CPUs
  -gocmd="go"         Build command, defaults to Go
  -rebuild            Force rebuilding of package that were up to date
  -verbose            Verbose mode
```
Note that mine indicates `-tags` as supported but the output you showed above does not.

**Comment by aakarshit-batchu** [comment]
@jefferai which version of gox are you using?
I am working on Ubuntu 16.04.1 LTS.
I did apt-get update and apt-get install gox.
The output I get from gox -h:
```
Usage: gox [options] [packages]

  Gox cross-compiles Go applications in parallel.

  If no specific operating systes or architectures are specified, Gox
  will build for all pairs supported by your version of Go.

Options:

  -arch=""            Space-separated list of architectures to build for
  -build-toolchain    Build cross-compilation toolchain
  -ldflags=""         Additional '-ldflags' value to pass to go build
  -os=""              Space-separated list of operating systems to build for
  -osarch=""          Space-separated list of os/arch pairs to build for
  -output="foo"       Output path template. See below for more info
  -parallel=-1        Amount of parallelism, defaults to number of CPUs
  -verbose            Verbose mode

Output path template:

  The output path for the compiled binaries is specified with the
  "-output" flag. The value is a string that is a Go text template.
  The default value is "{{.Dir}}_{{.OS}}_{{.Arch}}". The variables and
  their values should be self-explanatory.

Platforms (OS/Arch):

  The operating systems and architectures to cross-compile for may be
  specified with the "-arch" and "-os" flags. These are space separated lists
  of valid GOOS/GOARCH values to build for, respectively. You may prefix an
  OS or Arch with "!" to negate and not build for that platform. If the list
  is made up of only negations, then the negations will come from the default
  list.

  Additionally, the "-osarch" flag may be used to specify complete os/arch
  pairs that should be built or ignored. The syntax for this is what you would
  expect: "darwin/amd64" would be a valid osarch value. Multiple can be space
  separated. An os/arch pair can begin with "!" to not build for that platform.

  The "-osarch" flag has the highest precedent when determing whether to
  build for a platform. If it is included in the "-osarch" list, it will be
  built even if the specific os and arch is negated in "-os" and "-arch",
  respectively.

```

**-tags** is missing

Can you tell me which version of gox to use in specific?

**Comment by jefferai** [comment]
Like many Go packages it does not do official releases. Generally speaking using a package manager's packages for Go libs and tools is a bad idea, similar to Python or Ruby. You should get familiar with using 'go get'. In this case 'go get -u github.com/mitchellh/gox'.

**Comment by aakarshit-batchu** [comment]
Thank you @jefferai
