### ISSUE TITLE
Associating an App-ID, via the REST API, with a Policy No Longer Working

### ISSUE THREAD

**Issue by jymbo** [hashicorp/vault#2659]
I installed vault 0.7.0 and am using the App-ID authentication. I know this is deprecated, but it is the only method supported in streamsets at the moment. This was working just fine in 0.6.5, but is not working in the latest version. To reproduce:

**Enable App-ID Auth**
curl -X POST -H "X-Vault-Token:<$MyToken>" -d '{"type":"app-id"}'http://127.0.0.1:8200/v1/sys/auth/app-id

2017/04/28 11:35:13.422237 [INFO ] core: enabled credential backend: path=app-id/ type=app-id

**Create Policy**
curl \
 -X PUT \
 -H "X-Vault-Token:<$MyToken>" \
 -H "Content-Type: application/json" \
 -d '{"rules": "{\"path\":{\"secret/*\": {\"policy\": \"read\"}}"}' \
   http://127.0.0.1:8200/v1/sys/policy/secret-policy

**Map App-ID to Policy**
curl -X POST -H "X-Vault-Token:<$MyToken>" –d '{"value":"secret-policy", "display":"streamsets"}' \
http://127.0.0.1:8200/v1/auth/app-id/map/app-id/streamsetsuser

Which gives this error:

curl: (6) Could not resolve host: xn--d-5gn; Unknown error

[1/2]: "value":"secret-policy" --> <stdout>
--_curl_--"value":"secret-policy"
curl: (6) Could not resolve host: "value"; Unknown error

[2/2]:  "display":"streamsets" --> <stdout>
--_curl_-- "display":"streamsets"
curl: (6) Could not resolve host:  "display"; Unknown error

**Comment by jefferai** [comment]
This has nothing to do with Vault, it's `curl` failing to resolve hosts because it thinks that everything after the `--d` is a host. It looks like something is wonky with your `–d`, the hyphen does not look the same as the previous curl call that works.

**Comment by jymbo** [comment]
You're right. Sorry for wasting your time.
