### ISSUE TITLE
Add new endpoints to batch Identity Entity retrieval

### ISSUE THREAD

**Issue by HenriBlacksmith** [hashicorp/vault#26617]
**Is your feature request related to a problem? Please describe.**

In my Vault implementation I am using Vault API to configure OIDC authentication (in Vault enterprise namespaces).
Especially, I need to query Identity entities by name for many entities to check if they already exist in Vault, this requires many calls to the existing https://developer.hashicorp.com/vault/api-docs/secret/identity/entity#read-entity-by-name endpoint.

I would like to be able to perform this query in a batch as it exists for deleting entities by ID: https://developer.hashicorp.com/vault/api-docs/secret/identity/entity#batch-delete-entities

**Describe the solution you'd like**
I would like to have the **Read entities by names** and **Read entities by IDs** endpoint to query many entities in a single call, the body of the queries could be:

```json
{
  "entity_ids": [
    "02fe5a88-912b-6794-62ed-db873ef86a95",
    "3bf81bc9-44df-8138-57f9-724a9ae36d04",
    "627fba68-98c9-c012-71ba-bfb349585ce1",
    "6c4c805b-b384-3d0e-4d51-44d349887b96",
    "70a72feb-35d1-c775-0813-8efaa8b4b9b5",
    "f1092a67-ce34-48fd-161d-c13a367bc1cd",
    "faedd89a-0d82-c197-c8f9-93a3e6cf0cd0"
  ]
}
```

```json
{
  "entity_names": [
    "testentityname",
    "testentityname2",
  ]
}
```

**Describe alternatives you've considered**

The current alternatives is to loop over the existing endpoints:
- https://developer.hashicorp.com/vault/api-docs/secret/identity/entity#read-entity-by-id
- https://developer.hashicorp.com/vault/api-docs/secret/identity/entity#read-entity-by-name
but this is not performant and taking a lot of time.

**Explain any additional use-cases**
N/A

**Additional context**
I am using Vault Enterprise and providing namespaces to my users which are pre-configured with OIDC authentication

**Comment by divyaac** [comment]
Hi @HenriBlacksmith thank you so much for your request. There is some level nuance to why we cannot easily implement this. Templated policies can be created on paths such as `identity/entity/id/{{identity.entity.id}}` that defines access control to Read/list/delete endpoint. Allowing the user to specify multiple id's or names would essentially allow a user to circumvent these policies and delete/list/read and entity id or name that they are disallowed from accessing. 

See policy docs: https://developer.hashicorp.com/vault/docs/concepts/policies#parameters

**Comment by HenriBlacksmith** [comment]
Could there be a query endpoint instead which would provide more capabilities than this one: https://developer.hashicorp.com/vault/api-docs/secret/identity/entity#list-entities-by-id

It could be POST `identity/entity/query?filter=...&select=name,id`

I am not sure about the filtering/sorting mechanisms already used in Vault API but this would allow better query options than the current ones.

Having a new path would probably fix the issue with templated policies (as it works for the `LIST identity/entity/id` endpoint)

**Comment by HenriBlacksmith** [comment]
Actually, re-checking the docs there is a lookup endpoint but it is just for a single entity: https://developer.hashicorp.com/vault/api-docs/secret/identity/lookup#lookup-an-entity

Having the same endpoint but to query multiple entities would answer our needs?

Should I open another issue?

It could be:

`POST /identity/lookup/entities`
