### ISSUE TITLE
Vault 1.16.1 missed PR: UI: Fix KV v2 json editor #24224

### ISSUE THREAD

**Issue by timonych** [hashicorp/vault#26634]
**Describe the bug**
Try to add new line in kv2 json and the pointer goes to start.

**To Reproduce**
1. Open any kv2 json.
2. Click on Create New Version
3. Put the pointer in some place in json
4. Press Enter to add new line and the pointer goes to start
 
**Expected behavior**
New line successfully added.

**Additional context**
I think that  PR which is fixed behavior in 1.15 is missed in 1.16.1
https://github.com/hashicorp/vault/pull/24224

**Comment by marcboudreau** [comment]
I can confirm the reported behaviour is occurring in Vault 1.16.1. Here's a more descriptive explanation of the problem, @timonych let me know if I didn't get it right.

Given this secret,
![image](https://github.com/hashicorp/vault/assets/5696632/f8f1299b-2dcf-4332-a91d-9fe0e6ede3a0)

If I place the cursor at the end of line 3 (to the right of the closing double quote character) and press ENTER, the cursor jumps to the beginning of line 1 and no newline character is inserted. However, if I first insert a comma and then press ENTER, the editor works as expected.
![image](https://github.com/hashicorp/vault/assets/5696632/3ef5c6bf-190d-4b5a-a106-94e2033506aa)

**Comment by timonych** [comment]
@marcboudreau Yes. You are clearily described the problem. thx!

**Comment by Monkeychip** [comment]
Thank you for the issue! The linked PRs above address this issue. The fix should come out in 1.17.0, and 1.16.3

**Comment by timonych** [comment]
Updated vault to 1.17.0, but the bug is still reproduced

**Comment by karabanov** [comment]
I confirm in Vault 1.17.0 the bug still reproduced

**Comment by xo4yecTb** [comment]
version 1.17.0, the bug is reproduced too
