### ISSUE TITLE
Fedora 40: Download/install of Vault is unavailable

### ISSUE THREAD

**Issue by ScriptAutomate** [hashicorp/vault#26643]
**Describe the bug**

Fedora 40 was released this week.

When trying to install `vault` on Fedora 40, following the [Fedora directions for installation](https://developer.hashicorp.com/vault/tutorials/getting-started/getting-started-install), the following output occurs when running `dnf -y install vault`:

```bash
Hashicorp Stable - x86_64                                                                                    1.7 kB/s | 314  B     00:00    
Errors during downloading metadata for repository 'hashicorp':
  - Status code: 404 for https://rpm.releases.hashicorp.com/fedora/40/x86_64/stable/repodata/repomd.xml
Error: Failed to download metadata for repo 'hashicorp': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: hashicorp
Last metadata expiration check: 0:00:15 ago on Thu Apr 25 02:18:41 2024.
No match for argument: vault
Error: Unable to find a match: vault
```

**To Reproduce**

```bash
# Fedora 40 container
# docker run --rm -it fedora:40

dnf install -y dnf-plugins-core
dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
dnf -y install vault
```

**Expected behavior**

Fedora 40 should be supported.

**Additional Information**

Is similar to when Fedora 39 needed support after it was released:
- https://github.com/hashicorp/vault/issues/24107

**Comment by stevendpclark** [comment]
Hi @ScriptAutomate, 

Thanks for filing the issue, an internal ticket has been opened to add support for Fedora 40 along with Ubuntu 24.04 LTS. I'll post back confirmation here once the work has been completed.

**Comment by stevendpclark** [comment]
The Fedora 40 repo should be available now for Vault.
