### ISSUE TITLE
Rate Limiting on /ui

### ISSUE THREAD

**Issue by bgaillard** [hashicorp/vault#26644]
**Is your feature request related to a problem? Please describe.**

We implemented several [Resource quotas](https://developer.hashicorp.com/vault/docs/concepts/resource-quotas) to protect our Vault cluster the best as we can.

In parallel we created several metrics to follow rate limit events in our Vault Audit logs. 

Our setup configures a "very strict" rate limit global threshold and then we have several customized rate limit rules on our Auth Methods and Secret Engines. 

Our setup is good but it appears that since recent Vault versions (I do not know which one) we encounter several Rate Limit events on the `/ui` path in our Vault Audit Logs.

Here is a sample.

![image](https://github.com/hashicorp/vault/assets/1327782/a53607b3-4d67-424c-8d47-8bdc42c0b2e5)

 I read the source code of the 
[queryQuota](https://github.com/hashicorp/vault/blob/a65d9133a1900acc43b8c1cdfc241f5d6c9bad59/vault/quotas/quotas.go#L534) function to understand how it works internally and it seems to me that the code could provide a quota for `/ui`.

But, when we try to create a quota for `/ui` it seems not possible.

```bash
vault write /sys/quotas/rate-limit/ui block_interval=60 interval=60 path=ui/ rate=60
Error writing data to sys/quotas/rate-limit/ui: Error making API request.

URL: PUT https://vault-sit-infra.secret.sit-infra.cloud.mymoneybank.fr/v1/sys/quotas/rate-limit/ui
Code: 400. Errors:

* invalid mount path "ui/"
```

**Describe the solution you'd like**

Be able to create Resource Quotas on the `/ui` path.

**Describe alternatives you've considered**

Increase our global Resource Quota rule but in our opinion this is not ideal because it forces us to have a too high global rate limiting threshold.

**Comment by divyaac** [comment]
Hi @bgaillard thank you for raising this issue! What is likely occurring here, is that there is a global quota and any request to the path `ui/` is causing this global rate limit quota to be exceeded. As of now, the reason we can't create a rate limit on a path like `ui/` is that ui is not a mount. If we were to enable rate limits on paths other than just mounts, customers might run into problems where they rate limit entire api paths, causing them to be inaccessible.
