### ISSUE TITLE
Add support for Ubuntu 24.04 "noble" in HashiCorp Apt Repository

### ISSUE THREAD

**Issue by gfk** [hashicorp/vault#26667]
**Issue Description**
I attempted to add the HashiCorp Apt repository on Ubuntu 24.04 "noble" using the recommended installation command, but encountered an error due to the absence of a release file for this distribution.

**Steps to Reproduce**

1. Install Ubuntu 24.04 "noble".
2. Run the recommended command to add the HashiCorp repository:

```
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
```

3. Run `sudo apt update` and observe the error related to the missing Release file.

**Expected Behavior**

The HashiCorp repository should support Ubuntu 24.04 "noble", allowing the successful addition of the repository and subsequent installation of HashiCorp packages.

**Actual Behavior**

The attempt to update the package list from the repository fails with the following error:
```
Ign:5 https://apt.releases.hashicorp.com noble InRelease
Err:6 https://apt.releases.hashicorp.com noble Release
  404  Not Found [IP: 2600:9000:223d:e800:18:566b:ecc0:93a1 443]
Reading package lists... Done
E: The repository 'https://apt.releases.hashicorp.com noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

***Additional Context***
Ubuntu 24.04 "noble" was released on April 25th, and it's [not officially supported](https://www.hashicorp.com/official-packaging-guide) in repository support. I am opening this issue to inquire about and track the progress of adding "noble" support to the HashiCorp repository.

**Comment by stevendpclark** [comment]
Hello @gfk, 

Thanks for filing the issue, an internal ticket was opened to add support for Fedora 40 along with Ubuntu 24.04 LTS. I'll post back confirmation here once the work has been completed.

**Comment by raza707mirza** [comment]
Hi @stevendpclark, 

Any Updates on this issue?

Thanks

**Comment by stevendpclark** [comment]
Hello everyone, 

The Ubuntu 24.04 apt repository is now available for use.
