### ISSUE TITLE
Setting to disable "Reveal values" or set default value

### ISSUE THREAD

**Issue by RuneAlexanderTrachsel** [hashicorp/vault#26732]
**Is your feature request related to a problem? Please describe.**
I'm frustrated about the new reveal values toggle, we don't need this feature. It adds an extra click each time we want to see the vault configurations.

**Describe the solution you'd like**
Either an option to disable this feature or an option in settings to add an default value.

**Additional context**
![image](https://github.com/hashicorp/vault/assets/22022025/843afd0b-aea1-4bb9-b7f0-ee247022731b)

**Comment by trezum** [comment]
I am having this issue too.
