### ISSUE TITLE
feature: support trivial sse for s3 backend

### ISSUE THREAD

**Issue by automaticgiant** [hashicorp/vault#2673]
i'd like to add (or have added!) the option to enable sse on the s3 backend.
it should be one line in `Put` and one in the struct, and a couple to extract the config.

not sure what test coverage should look like. need input here. i wouldn't even be able run a put test with sse turned off (corp policy). but since turning on sse probably doesn't break anyone, maybe i can add a put with sse test, but not a put without sse?

i'll test, but i think the sufficient functionality can be implemented with the addition of a `ServerSideEncryption *string `location:"header" locationName:"x-amz-server-side-encryption" type:"string" enum:"ServerSideEncryption"` field to the `PutObjectInput`.

for my use case, we don't need to do anything fancy other than turn it on.
thoughts?

**Comment by jefferai** [comment]
You may want to look at https://github.com/hashicorp/vault/pull/2026 which adds part of this, but the key needs to be able to be specified.

**Comment by automaticgiant** [comment]
well, i think i'll end up closing this as a duplicate (i'm not sure i'll work on this in the next week), but i do want to clear up the key thing first.

now i know that if i want to `aws s3 cp blah s3://bucket/key` i can't, but i can add a `--sse` or whatever the option is and it's good to go. is that because there is something set in my environment(account) to specify a default key or something?

my understanding is that just enabling sse gets you "SSE with Amazon S3 Key Management (SSE-S3)", meaning this can be trivial, but some users would want to specify a key. https://aws.amazon.com/s3/details/

so i guess it's largely academic, but a learning opportunity. i suppose it's not much more work to add specifying a key, is it.

**Comment by jefferai** [comment]
Honestly, not sure about the `--sse` thing. It's possible that AWS' libraries will automatically be able to use an encryption key if it's in your aws config file (we use their official client).

**Comment by automaticgiant** [comment]
i never set it up in the config...

**Comment by joelthompson** [comment]
There are two flavors AWS S3 SSE. The first is to have S3 use an S3-specific key, and it's completely transparent to you. The second flavor is to have S3 use a KMS-managed key. The benefit of the latter is you can now set KMS key policies and grants to further restrict who can read the data.

When you just pass in the `--sse` flag, it defaults to the value of `AES256` which is the first type of encryption. If you specify `--sse aws:kms` then it uses the KMS key, and you have to specify the KMS key ID. (Honestly, this is one area where AWS could improve their documentation.)
