### ISSUE TITLE
flag provided but not defined: -listing_visibility when trying to tune auth

### ISSUE THREAD

**Issue by ilsaloving** [hashicorp/vault#26765]
**Describe the bug**

**To Reproduce**
1. Set up vault server
2. configure ldap
3. Try to configure visibility via 'vault auth tune -listing_visibility=unauth ldap'
4. Get error

**Expected behavior**
I expect it to work.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.16.2
* Vault CLI Version (retrieve with `vault version`): 1.16.2
* Server Operating System/Architecture:

Vault server configuration file(s):

```json
{
	"listener": [
		{
			"tcp": {
				"address": "0.0.0.0:443",
				"tls_cert_file": "/opt/vault/ssl/vault.crt",
				"tls_key_file": "/opt/vault/ssl/vault.key",
				"tls_disable": "false"
			}
		}
	],
	"storage": {"file": {"path": "/opt/vault/data"}},
	"max_lease_ttl": "10h",
	"default_lease_ttl": "10h",
	"ui": true,
	"plugin_directory": "/opt/vault/plugins",
	"api_addr": "https://127.0.0.1:443"
}
```

**Additional context**
I am trying to hide all the unconfigured authentication types.

Also, if I type `vault read /sys/auth/ldap`, `listing_visibility` does not appear in the config at all.  Has it been removed?
```
Key                        Value
---                        -----
accessor                   auth_ldap_04b96c5e
config                     map[default_lease_ttl:0 force_no_cache:false max_lease_ttl:0 token_type:default-service]
deprecation_status         supported
description                n/a
external_entropy_access    false
local                      false
options                    <nil>
plugin_version             n/a
running_plugin_version     v1.16.2+builtin.vault
running_sha256             n/a
seal_wrap                  false
type                       ldap
uuid                       bd05ee91-3b55-0864-a0a2-a8de62631360
```

**Comment by stevendpclark** [comment]
Hi @ilsaloving,

The feature is still present, I believe you have used the api/configuration spelling on the CLI, underscore is the [API version](https://developer.hashicorp.com/vault/api-docs/system/auth#listing_visibility) and the [CLI argument](https://developer.hashicorp.com/vault/docs/commands/auth/tune#listing-visibility) uses a dash. 

`vault auth tune -listing-visibility=unauth ldap` should work. 

Let me know if this resolves your issue.

**Comment by stevendpclark** [comment]
> Yes, that solved it. 

Great!

> But I have to ask... why? This is needless confusion.

Sorry I don't know the history/reasoning for the difference.
