### ISSUE TITLE
Enhancement: MySQL backend - allow lease information to be tied to a role

### ISSUE THREAD

**Issue by rjbez17** [hashicorp/vault#2678]
Currently leases are defined globally to the connection. Its be very helpful to set the lease information based on roles (or even at time of requesting credentials). We have a use case to allow some roles to have extended leases. We currently temporarily change the lease, generate the credentials, then change it back. This is an obvious race condition.

**Comment by briankassouf** [comment]
Hi @rjbez17,

In the next release #2200 will ship, and it has this feature!

**Comment by rjbez17** [comment]
Great, before I create another one, will the new version also allow for multiple connection to mysql (different database servers)?

**Comment by briankassouf** [comment]
Yes! The same mounted backend can configure multiple connections, even of different database types (mysql, postgres, etc.)

**Comment by rjbez17** [comment]
Awesome! You saved me soooo much work!

**Comment by jefferai** [comment]
Closing in favor of #2200 which will land...................................................very soon. And 0.7.1 which will land................................................almost as soon.
