### ISSUE TITLE
Feature request: Clone mount

### ISSUE THREAD

**Issue by bernielomax** [hashicorp/vault#2679]
It would be great if you could clone from one mount to another. That way you could do some cool things with secret versioning, history, etc.

**Comment by bernielomax** [comment]
The other thing that would be really is would be the ability to create aliases for mounts. Similar to that of a symlink.

**Comment by jefferai** [comment]
We now have KV v2 which allows for secret versioning, and have no plans to implement direct cloning since most backends wouldn't work anyways.
