### ISSUE TITLE
key last modified time

### ISSUE THREAD

**Issue by maksimlikharev** [hashicorp/vault#2683]
I think there is no way to get vault data last modification time, at least I wasn't able to see one.
It would be nice to have key modification timestamp, so client can detect, process updates and potentially refresh changes efficiently.

**Comment by chrishoffman** [comment]
There is no last modified time for data in vault.  For the generic secret backend, the `ttl` parameter will return a hint in `refresh_interval` on when you should refresh this data.

**Comment by maksimlikharev** [comment]
I need a way to check when data was updated, refresh_interval does give me that option

**Comment by jefferai** [comment]
Currently your only option is audit logs. Sorry...

**Comment by jefferai** [comment]
Versioned K/V store coming in 0.10 will have this capability.
