### ISSUE TITLE
Audit broken in 0.7.1

### ISSUE THREAD

**Issue by tehmaze** [hashicorp/vault#2687]
Since the upgrade from 0.7.0 to 0.7.1 we ran into the following issue:

    client$ VAULT_TOKEN=<redacted> vault token-lookup
    error looking up token: Error making API request.
    
    URL: GET https://vault.example.com:8200/v1/auth/token/lookup-self
    Code: 500. Errors:
    
    * internal error

The Vault daemon reports:

    May 08 15:26:30 vault-101.example.com vault[53455]: 2017/05/08 15:26:30.836345 [ERROR] audit: panic during logging: request_path=auth/token/lookup-self error="reflect: reflect.Value.Set using value obtained using unexported field"
    May 08 15:26:30 vault-101.example.com vault[53455]: 2017/05/08 15:26:30.836397 [ERROR] core: failed to audit response: request_path=auth/token/lookup-self error=panic generating audit log

Using the root token still works:

    server# vault token-lookup | grep '^path'
    path            	auth/token/root

Enabled audit backend:

    server# vault audit-list
    Path   Type  Description  Replication Behavior  Options
file/  file               replicated            file_path=/var/log/vault/audit.log

If we disable audit logging, the 500 for the client disappears:

    server# vault audit-disable file
    Successfully disabled audit backend 'file' if it was enabled
    client$ VAULT_TOKEN=<redacted> vault token-lookup | grep '^path'
    path            	auth/token/create

Also when we enable the syslog backend, the client receives a 500 and the same error is reported by the Vault daemon.

**Comment by jefferai** [comment]
Hi @tehmaze ,

We've confirmed this. We're going to fix it and roll a new release. Thanks for the report!
