### ISSUE TITLE
tls_max_version is ignored in Vault 1.16.2

### ISSUE THREAD

**Issue by mughetti** [hashicorp/vault#26894]
After having updated from 1.15.x to 1.16.2 TLS version has been updated from 1.2 to 1.3. 
I cannot use TLS 1.3 right now so I tried to set tls_max_version = "tls12" in the listener configuration but nothing changed.
I see that the handshake is still using TLS1.3
**To Reproduce**
1. add tls_max_version = "tls12" to the listener stanza
2. Check TLS version used in hasdshake for example with Firefox Web Developer tool

**Expected behavior**
I would expect that TLS handshake is done with TLS1.2
**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.16.2
* Vault CLI Version (retrieve with `vault version`): 1.16.2
* Server Operating System/Architecture: Amazon Linux 2

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
listener "tcp" {
    address = "0.0.0.0:8200"
    cluster_address = "0.0.0.0:8201"
    tls_disable = false
    tls_max_version = "tls12"
    tls_cert_file   = "/opt/vault/tls/vault.crt.pem"
    tls_key_file    = "/opt/vault/tls/vault.key.pem"
    tls_client_ca_file    = "/opt/vault/tls/vault.ca.pem"

  }

**Additional context**
Also terraform vault provider fails with TLS1.3

**Comment by stevendpclark** [comment]
Hi @mughetti,

I'm unable to reproduce what you are seeing with Vault version 1.16.2 on Mac and Linux platforms. 
Both `openssl s_client -connect localhost:8200` and the Firefox web dev console are negotiating at TLSv1.2 when the configuration is in place and Vault is restarted.

Could there be something else doing the TLS termination between your browser and Vault?

**Comment by mughetti** [comment]
Hi, 
yes I have an AWS ALB and I thought I changed the security policy to use TLS1.2 but I was wrong. I've just changed it now and  I see Vault using TLS1.2. 
Apologies. I close the issue
