### ISSUE TITLE
 /vault/secrets/server.key: key value mismatch error when using pkiCert with postgres container ssl = on

### ISSUE THREAD

**Issue by jayboy-mabushi** [hashicorp/vault#27006]
**Environment:**

* Vault Version:
* 1.161* 
* Operating System/Architecture:
docker-desktop on mac
**Vault Config File:**

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Startup Log Output:**

```text
# Paste your log output here
```

**Expected Behavior:**
<!The agent should inject the keys into postgres container and the container should start in ssl mode on
--annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "issuer"
        vault.hashicorp.com/agent-inject-secret-server.key: "pki/issue/example-dot-com"
        vault.hashicorp.com/agent-run-as-user: "999"
        vault.hashicorp.com/agent-inject-perms-server.key: "600"
        vault.hashicorp.com/agent-inject-template-server.key: |
          {{- with pkiCert "pki/issue/example-dot-com" "common_name=postgres.com" -}}
          {{ .Key }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-server.crt: "pki/issue/example-dot-com"
        vault.hashicorp.com/agent-run-as-user:999
        vault.hashicorp.com/agent-inject-perms-server.crt:600
        vault.hashicorp.com/agent-inject-template-server.crt: |
          {{- with pkiCert "pki/issue/example-dot-com" "common_name=postgres.com" -}}
          {{ .Cert }}
          {{- end }}  -->

**Actual Behavior:**

**Steps to Reproduce:**

**Important Factoids:**

**References:**

**Comment by biazmoreira** [comment]
@jayboy-mabushi Thanks for creating the issue. Could you please provide more details in the description? This will help us assist you more effectively.

**Comment by hsimon-hashicorp** [comment]
@jayboy-mabushi Hi! Please use the issue template and provide as much information as you can for easier troubleshooting and issue reproducing. I'm going to go ahead and close this issue for now. Please feel free to re-open it if you can provide all of the information requested in the issue template.
