### ISSUE TITLE
Failed to download metadata for repo 'hashicorp': Yum repo downloading error

### ISSUE THREAD

**Issue by kourosh-forti-hands** [hashicorp/vault#27029]
**Describe the bug**

```
  [hashicorp]
  name=Hashicorp Stable - $basearch
  baseurl=https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
  enabled=1
  gpgcheck=1
  gpgkey=https://rpm.releases.hashicorp.com/gpg
  
  [hashicorp-test]
  name=Hashicorp Test - $basearch
  baseurl=https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/test
  enabled=0
  gpgcheck=1
  gpgkey=https://rpm.releases.hashicorp.com/gpg
```

**To Reproduce**
1. Run `sudo dnf install vault-enterprise`
3. See error
4. 

```
  Errors during downloading metadata for repository 'hashicorp':
    - Status code: 404 for https://rpm.releases.hashicorp.com/RHEL/8.8/x86_64/stable/repodata/repomd.xml (IP: 99.84.66.57)
  Error: Failed to download metadata for repo 'hashicorp': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

Environment:
RHEL 8.8

**Comment by kourosh-forti-hands** [comment]
similar issue i found https://github.com/hashicorp/vault/issues/16864

**Comment by kourosh-forti-hands** [comment]
adding this fixed it `sed -i 's/$releasever/8/' /etc/yum.repos.d/hashicorp.repo`

it appears that $releasever is pulling the minor version of RHEL8 causing issues `baseurl=https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable`

**Comment by biazmoreira** [comment]
Hi @kourosh-forti-hands, thank you for creating the issue. 

You mentioned in the description that you are using `RHEL/8.8`, however, we do not support minor versions of RHEL, only major versions as announced in the following blogpost: https://www.hashicorp.com/blog/announcing-the-linux-package-archive-site last year. If you scroll down, you'll see there's a FAQ at the bottom that outlines that: 

> Anyone currently changing their repo configs to reference RHEL minor versions will need to revert to major versions. This applies only to HashiCorp repositories, users can continue targeting minor versions for other repos if that suits them.

If you have more questions regarding packaging, please refer to https://www.hashicorp.com/official-packaging-guide. 

If there's anything else we can assist you with, please let me know.
