### ISSUE TITLE
Feature: Fetch only 'latest' transit key

### ISSUE THREAD

**Issue by stampycode** [hashicorp/vault#2704]
Currently my only option for fetching a specific version of a Transit key from Vault is to either know beforehand what versions of the key exist, or request all of them.

I want to be able to run this:
```
$ curl \
    --header "X-Vault-Token: ${VAULT_TOKEN}" \
    https://vault.rocks/v1/transit/export/encryption-key/my-key/latest
```

Where `latest` is currently required to be a numeric value representing the key version I require.

The reason for this request is so I can implement a rotating-key system, whereby only the latest key is valid, and is rotated on a timed-basis, and previous keys remain valid for a limited time period.
Old (expired) keys will be removed using the [`min_decryption_version`](https://www.vaultproject.io/api/secret/transit/index.html#min_decryption_version) config option.

**Comment by chrishoffman** [comment]
Using `latest` as your version is already supported!  I checked the docs and it looks like it is not documented (which we will update).
