### ISSUE TITLE
Feature request: GCP Auth backend

### ISSUE THREAD

**Issue by devth** [hashicorp/vault#2711]
Similar to the [AWS Auth Backend](https://www.vaultproject.io/docs/auth/aws.html)

**Comment by emilymye** [comment]
I'm going to be supporting this. I created a proposal for an auth BE for GCP IAM service accounts at #2813. If you don't mind me asking, what authenticating entities and use cases are you most interested in? e.g. AWS supports both IAM entity and EC2 instance auth and uses IAM policy ARNs or AMI IDs to restrict roles to authenticate against.

**Comment by devth** [comment]
I'm interested in IAM for GCP service accounts and users. I'm not super familiar with AWS' IAM.

**Comment by emilymye** [comment]
Closing - see #2813
