### ISSUE TITLE
inappropriate warning message from "vault status"

### ISSUE THREAD

**Issue by rwv37** [hashicorp/vault#27135]
**Describe the bug**
`vault status` gives a warning message saying "WARNING! VAULT_ADDR and -address unset. Defaulting to `https://127.0.0.1:8200`.", despite `-address` being set, and despite the command otherwise working correctly (i.e. it correctly gets the status of the vault at the specified address).

I'm guessing the but is probably not just limited to `vault status`, but that's all I've tried it for.

**To Reproduce**
1. Set up a vault server instance somewhere (for example, `http://example.com:12345`).
2. On a machine that has no vault server on port 8200, and without `VAULT_ADDR` being set, run `vault status -address=http://example.com:12345`

**Expected behavior**
The status of the vault server at `http://example.com:12345` is displayed.

Actual behavior is that the status is displayed, but also the inappropriate warning message occurs.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.14.1
* Vault CLI Version (retrieve with `vault version`): 1.16.2
* Server Operating System/Architecture: FreeBSD
* CLI OS: Windows 11

Vault server configuration file(s):

```hcl
ui = true
api_addr = <redacted>
cluster_addr = <redacted>
disable_mlock = true

listener "tcp" {
   address = <redacted>
   tls_disable = "true"
}

storage "mysql" {
   username = <redacted>
   password = <redacted>
   database = <redacted>
}
```

**Additional context**
Nope.

**Comment by VioletHynes** [comment]
Hey there! I managed to reproduce this and I think I have a fix for it. Thanks for the report!

I did some digging internally and this has also been reported at https://github.com/hashicorp/vault/issues/26294 -- I'll make sure to link and close both when merging the fix.
