### ISSUE TITLE
Document token format

### ISSUE THREAD

**Issue by nobe4** [hashicorp/vault#27151]
**Is your feature request related to a problem? Please describe.**

I worked on https://github.com/github/redacting-logger/pull/48 and didn't find an easy answer to "what is the format used for tokens?"

**Describe the solution you'd like**

I would like this to be written in the doc. Something as simple as:

---

Vault tokens are comprised of a prefix and a body.

- The prefix indicates the token's type:

  Token Type | Vault 1.9.x or earlier | Vault 1.10 and later
  -- | -- | --
  Service tokens | s. | hvs.
  Batch tokens | b. | hvb.
  Recovery tokens | r. | hvr.

- The body is a randomly-generated 24 characters [Base62](https://en.wikipedia.org/wiki/Base62) string.

Token are expected to match the following regexp: `(hv)?[sbr]\.[a-zA-Z0-9]{24}`

---

Obviously, not all the info is required, but would ease the understanding.

**Explain any additional use-cases**

When writing a regex or a tool to detect vault tokens, an official source would be appreciated.

**Additional context**

cc https://github.com/github/redacting-logger/pull/48

**Comment by robmonte** [comment]
Hi @nobe4 this sounds like a reasonable request. Thanks for the suggestion!

As a reader do you have a specific page in mind you'd consider "here's the first place I'd look" for this information? I have a guess for the best spot but I'd like to consider other ideas if you happen to have an alternative. You can either let me know or consider opening a PR for even quicker feedback.

**Comment by nobe4** [comment]
Duckduckgo and Google point to the same 2 pages for the query `vault token`:

- https://developer.hashicorp.com/vault/tutorials/tokens/tokens
- https://developer.hashicorp.com/vault/docs/concepts/tokens

At first glance, the `concepts/tokens` would seem like the reasonable place where this should be. It turns out that the token prefixes are discussed in `tutorials/tokens/tokens`. (this is a tad confusing, but OK).


In light of this, I would put the `Token Format` just between [what are tokens](https://developer.hashicorp.com/vault/tutorials/tokens/tokens#what-are-tokens) and [token-types](https://developer.hashicorp.com/vault/tutorials/tokens/tokens#token-types) on the tutorial page.

The copy could be simplified like:

---

Vault tokens are comprised of a prefix and a body.

- The prefix indicates the token's type, see [token-prefix](https://developer.hashicorp.com/vault/tutorials/tokens/tokens#token-prefix).
- The body is a randomly-generated 24 characters [Base62](https://en.wikipedia.org/wiki/Base62) string.

Token are expected to match the following regexp: `(hv)?[sbr]\.[a-zA-Z0-9]{24}`

---

Maybe putting a couple of examples would also be nice.

**Comment by robmonte** [comment]
Thanks for the information. It is interesting that the tutorial explains it but not the token documentation. `concept/tokens` is exactly where I was thinking as well.

The website docs are actually here in the Vault repo as well, that particular page is located here: https://github.com/hashicorp/vault/blob/main/website/content/docs/concepts/tokens.mdx. I will be happy to review your PR once submitted.

**Comment by nobe4** [comment]
Thanks @robmonte 🙏 

I opened https://github.com/hashicorp/vault/pull/27522 and closed it quickly after.
https://github.com/hashicorp/vault/pull/27522#issuecomment-2174449065 gives my reasons.

Feel free to make the change directly, it will be less legal hoops to jump.
