### ISSUE TITLE
LDAP auth not working with Audit backend: File enabled

### ISSUE THREAD

**Issue by hummerpaskaa** [hashicorp/vault#2717]
In my setup, LDAP authentication works just fine, until I enable audit to a file. All logging works as it should, but when I try to auth via LDAP it fails with:

[ERROR] audit: panic during logging: request_path=auth/token/lookup-self error="reflect: reflect.Value.Set using value obtained using unexported field"

**Comment by briankassouf** [comment]
HI @hummerpaskaa,

What version of vault are you running?

**Comment by hummerpaskaa** [comment]
hi @briankassouf 
I am running Vault v0.7.1 ('1767ced3a336aee9dbce7f4f0ad652ff44e8ddab')

**Comment by jefferai** [comment]
Hi @hummerpaskaa 

See
https://groups.google.com/d/msg/vault-tool/f5DQtd0TEwE/W8W471DcBwAJ

**Comment by hummerpaskaa** [comment]
@jefferai aha great, Thank you.

**Comment by hummerpaskaa** [comment]
Verified that it works just fine in 0.7.2. My bad for not noticing there was a never version. Thank you for the quick answer

**Comment by jefferai** [comment]
Yeah, that's literally the reason we spun 0.72 was that bug :-/
