### ISSUE TITLE
Unable to synchronize app secrets between Vault secrets and Github actions

### ISSUE THREAD

**Issue by IliyanKostov9** [hashicorp/vault#27182]
**Describe the bug**
Recently, I have been experiencing a problem when adding a new sync integration between Vault secrets and Github secrets.
The message is as follows:
![image](https://github.com/hashicorp/vault/assets/59366790/12d12538-1da5-412e-8bed-bde59f9687ac)

**To Reproduce**
1. Go to Vault Secrets > Apps > Click on app name > integrations > Add Github Actions > Select any repo
2. The error appears

**Expected behavior**
The secret sync process should have been successful.

**Environment:**
* Status: Operational

**Additional context**
The HCP Vault Secrets app is already installed under my github profile and has been configured to request access for the following permissions:
- Read access to metadata
- Read and write access to secrets

**Comment by hsimon-hashicorp** [comment]
Hi there! This is the repo for the self-managed Community Edition of Vault. For questions about HCP Vault Secrets, please check out the ? icon next to your profile picture in the top-left of the dashboard. I'm going to go ahead and close this issue now - thanks for your understanding!
