### ISSUE TITLE
UI: redirect of URL change for KV v2 secrets engine does not consider type generic

### ISSUE THREAD

**Issue by luanaBanana** [hashicorp/vault#27221]
**Describe the bug**
[This ](https://github.com/hashicorp/vault/pull/24339/files) bug fix fixed the problem for secret engines of type `kv` and version 2 but does not consider secret engines of type `generic` and version 2. 

**To Reproduce**
1. Select secret engine of type `generic` and version 2
2. ` No secrets in this backend `

**Expected behavior**
Secrets should be shown.

**Environment:**
* Vault Server Version:  1.16.2
* Vault CLI Version (retrieve with `vault version`): -
* Server Operating System/Architecture: RedHat 8.8

Vault server configuration file(s):

**Additional context**

the above mentioned fix introduces this condition: 

``` if (secretEngine.type === 'kv' && secretEngine.version === 2) ``` 
which does not include `secretEngine.type === 'generic' `

**Comment by Monkeychip** [comment]
@luanaBanana thank you for the detailed issue. I believe this bug was solved last week in PR #27019, which was backported to 1.16.3. Let me know if that does indeed solve the problem and I'll close this issue.

**Comment by luanaBanana** [comment]
> @luanaBanana thank you for the detailed issue. I believe this bug was solved last week in PR #27019, which was backported to 1.16.3. Let me know if that does indeed solve the problem and I'll close this issue.

It indeed fixed the bug. I didn't catch that one. Thanks for letting me know
