### ISSUE TITLE
sudden TTL errors

### ISSUE THREAD

**Issue by jeroenjacobs1205** [hashicorp/vault#2726]
I have had a working Vault setup, but suddenly it's not working anymore and I'm seeing this in the Consul healthcheck UI:

`TTL expired`

This is my Vault config file, I'm using Consul as backend:

```
storage "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
}

listener "tcp" {
 address = "0.0.0.0:8200"
 tls_disable = 1
}
```

I'm unable to unseal my Vault now (seems Vault is not listening on 8200 anymore either). What should I do to fix this? Is this a Vault issue, or Consul issue? The error is not clear at all. Please improve this.

Consul version used: 0.7.5
Vault version used: 0.7.0

**Comment by chrishoffman** [comment]
It sounds to me your vault is currently not running for some reason.    The ttl checks failing means Vault is not checking in which is confirmed by not being able to access it.    What do your Vault server logs look like?    
  
  
  
  
  

  
  
>

**Comment by jefferai** [comment]
Closing due to lack of response.
