### ISSUE TITLE
Feature request: Using DNS hostname verification as a constrain for AppRole 

### ISSUE THREAD

**Issue by bigmyx** [hashicorp/vault#2732]
Hello,
It would be nice to have a mechanism which verifies the DNS name and IP address of the client with an internal DNS server (much like the SSL host verification against CA) and grants the client access upon that along with a Role ID.
Please let me know if that makes sense.
Thanks!

**Comment by jefferai** [comment]
We don't know the DNS name of a client, only the IP address, and you can already constrain against CIDR in AppRole.
