### ISSUE TITLE
JWT authentication checks bound_audiences despite bound_claims is defined in v1.16.3

### ISSUE THREAD

**Issue by loicgreffier** [hashicorp/vault#27343]
**Describe the bug**

When authenticating to Vault using JWT auth method and a JWT role, the `bound_audiences` is checked even if `bound_claims` is defined in the role.

When the `bound_audiences` of the JWT role is empty, it results in the following error: `Authentication failed: audience claim found in JWT but no audiences bound to the role`, even if the provided JWT meets the required bound claims

**To Reproduce**

1. Configure a JWT Back-End

2. Configure a JWT role for this Back-End

```console
vault write auth/jwt/role/my-role - <<EOF
{
   "role_type": "jwt",
   "user_claim": "user_email",
   "policies": "my-policy",
   "ttl": "1h",
   "bound_claims": { "project_id": ["123"] }
}
EOF
```

The JWT role should define a `bound_claims`. I have used `project_id` as I have used GitLab as a JWT auth Back-End.

3. Log in Vault through the UI by selecting the JWT auth method and using the configured JWT role `my-role`.

4. It should display `audience claim found in JWT but no audiences bound to the role`.

**Expected behavior**

As `bound_claims` is defined in the role, `bound_audiences` should not be checked when authenticating.

**Environment:**
* Vault Server Version (retrieve with `vault status`):

```console
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.16.3
Build Date      2024-05-29T14:28:42Z
Storage Type    file
Cluster Name    ***
Cluster ID      ***
HA Enabled      false
```

* Vault CLI Version (retrieve with `vault version`):

```console
Vault v1.16.3 (e92d9a57018f43360e2e3717b3b6a7f650c88f4c), built 2024-05-29T14:28:42Z
```

* Server Operating System/Architecture:

Running on Windows

Vault server configuration file(s):

```hcl
storage "file" {
  path = "C:/Program Files/Vault/1.16.3/file"
}

listener "tcp" {
  address = "[::]:8200"
  cluster_address = "[::]:8201"
  tls_disable = 1
}

ui = true
plugin_directory = "C:/Program Files/Vault/1.16.3/plugins"
```

**Additional context**

The issue does not occur in v1.16.2.
It looks to be a regression on Vault v1.16.3.

**Comment by dmpe** [comment]
Yes, we can confirm this as well. Yesterday I have updated our version from 1.16.2 to 1.16.3 and gitlab CICD JWT integration has stopped working too. 

Our solution, thanks to @loicgreffier, is to add this in TF:

```
resource "vault_jwt_auth_backend_role" "myrole" {
  role_name              = "gitlab-...."
  bound_audiences        = ["https://gitlab.firm.com"]
.....
```

**Comment by peikk0** [comment]
Same here in GitLab CI, the audience is set with the ID token used to auth via JWT, but we don't set it in the role and we are getting the same error.

**Comment by ochnerd** [comment]
We can also confirm this Problem with 1.16.3

**Comment by nstrange0000** [comment]
We have been able to reproduce this.

**Comment by thyton** [comment]
@loicgreffier Sorry about the experience. Thank you for sharing the reproduce details. Could you post the redacted JWT you experienced the issue? This could help our investigation and triage.

I also wonder if @dmpe's [approach of setting bound_audiences](https://github.com/hashicorp/vault/issues/27343#issuecomment-2149146429) is a reasonable workaround for you while we're investigating the issue.

**Comment by loicgreffier** [comment]
@thyton I can provide all the requirements to reproduce the issue. It's quite easy using https://gitlab.com.

1. JWT auth Back-End based on https://gitlab.com: 

```console
vault read auth/jwt/config
Key                       Value
---                       -----
bound_issuer              https://gitlab.com
default_role              n/a
jwks_ca_pem               n/a
jwks_pairs                []
jwks_url                  https://gitlab.com/oauth/discovery/keys
jwt_supported_algs        []
jwt_validation_pubkeys    []
namespace_in_state        true
oidc_client_id            n/a
oidc_discovery_ca_pem     n/a
oidc_discovery_url        n/a
oidc_response_mode        n/a
oidc_response_types       []
provider_config           map[]
```

2. Set up a role with no `bound_audiences` (authentication will fail)

```console
vault write -tls-skip-verify auth/jwt/role/my-role - <<EOF
{
   "role_type": "jwt",
   "user_claim": "user_email",
   "policies": "gitlab",
   "ttl": "1h",
   "bound_claims": { "project_id": ["58630269"] }
}
EOF
```

> Update the `project_id` accordingly

3. Set up a role with `bound_audiences` (authentication will success)

```console
vault write -tls-skip-verify auth/jwt/role/my-role-aud - <<EOF
{
   "role_type": "jwt",
   "user_claim": "user_email",
   "policies": "gitlab",
   "ttl": "1h",
   "bound_audiences": ["https://first.service.com"],
   "bound_claims": { "project_id": ["58630269"] }
}
EOF
```

> Update the `project_id` accordingly

4. Set up GitLab CI to get a signed JWT:

```yaml
stages:
  - 🚩 token

generate:
  stage: 🚩 token
  image: alpine
  script: 
    - echo $VAULT_ID_TOKEN >> token.txt
  artifacts:
    paths: 
      - token.txt
  id_tokens:
    VAULT_ID_TOKEN:
      aud: https://first.service.com
```

5. Get the JWT from GitLab CI artifacts, and try to authenticate with both roles. JWT looks like this:

```yml
{
  "project_id": "58630269",
  ...
  "iss": "https://gitlab.com",
  "iat": 1717774028,
  "nbf": 1717774023,
  "exp": 1717777628,
  "sub": "project_path:loicgreffier/vault-27343:ref_type:branch:ref:main",
  "aud": "https://first.service.com"
}
```

We've postponed the upgrade to v1.16.3 waiting for a conclusion to this issue, as we're deploying Vault at scale, thus having a lot of roles to update.

Reading what @fairclothjm linked:
-  The behaviour described in this issue is not a bug, but expected?
- `bound_audiences` is required in Vault v1.16.3 JWT roles, no matter if the `aud` claims is present in the JWT?

**Comment by loicgreffier** [comment]
@fairclothjm Understood, the issue can be closed I guess

https://github.com/hashicorp/vault/issues/25791 looks to be related, but on a different version

**Comment by peikk0** [comment]
> The role bound_audiences is required if the aud claim is set on the JTW.

This is a breaking change which should not be happening in a patch release, it needs to be reverted in a new patch release and moved to v1.17.0 instead.

**Comment by mhmtsvr** [comment]
I just ran into this issue after upgrading Vault from 1.15.2 to 1.16.3. Prior to that, there were no issues.

```
vault write auth/jwt/role/github - <<EOF
{
  "role_type": "jwt",
  "user_claim": "actor",
  "bound_claims": {
    "repository": ["X/Y", "X/Z"]
  },
  "policies": ["github"],
  "ttl": "60m"
}
EOF
```

JWT Config:

```
vault write auth/jwt/config \
  bound_issuer="https://token.actions.githubusercontent.com" \
  oidc_discovery_url="https://token.actions.githubusercontent.com"
  ```

**Comment by BornToBeRoot** [comment]
We have upgraded our dev cluster from 1.16.2 to 1.16.3 and am facing the same/similar issue.

I get the following error:

```
Error writing data to auth/gitlab/login: Error making API request.
URL: PUT https://vault.<DOMAIN>/v1/auth/gitlab/login
Code: 400. Errors:
* error validating token: error verifying token signature: fetching keys oidc: get keys failed: 404 Not Found <!DOCTYPE html>
<html>
<head>
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <title>The page you're looking for could not be found (404)</title>
  <style>
...
<div class="container">
    <h3>The page could not be found or you don't have permission to view it.</h3>
    <hr />
    <p>The resource that you are attempting to access does not exist or you don't have the necessary permissions to view it.</p>
    <p>Make sure the address is correct and that the page hasn't moved.</p>
    <p>Please contact your GitLab administrator if you think this is a mistake.</p>
    <a href="javascript:history.back()" class="js-go-back go-back">Go back</a>
  </div>
...
```

The `bound_audiences` is already set for the identites...

```terraform
resource "vault_jwt_auth_backend_role" "identities" {
  for_each = {
    for k, v in var.identities : k => v
    if v.gitlab_jwt_auth_enabled
  }

  backend = vault_jwt_auth_backend.gitlab.path

  # GitLab JWT auth role like "<ENV>-<IDENTITY>" ("-unprotected" for ro)
  role_name = each.value.gitlab_jwt_auth_params.role_name
  role_type = "jwt"

  # Token config
  token_type              = "service"
  token_no_default_policy = true
  token_ttl               = each.value.gitlab_jwt_auth_params.default_ttl
  token_max_ttl           = each.value.gitlab_jwt_auth_params.max_ttl
  token_explicit_max_ttl  = each.value.gitlab_jwt_auth_params.explicit_max_ttl

  # The audience ("/aud/0") is set in the Pipeline
  # See https://docs.gitlab.com/ee/ci/secrets/id_token_authentication.html
  #
  #   id_tokens:
  #     CI_JOB_VAULT_JWT:
  #       aud:
  #         - "${CI_ENV}-${CI_PROJECT_NAME}${VAULT_CI_MODE}"
  #
  # The user_claim and bound_audiences will look like "<ENV>-<IDENTITY>" ("-unprotected" for ro)
  user_claim              = "/aud/0"
  user_claim_json_pointer = true
  bound_audiences         = [each.value.gitlab_jwt_auth_params.role_name]
  bound_claims_type       = "glob"
  bound_claims = {
    project_id    = each.value.gitlab_jwt_auth_params.project_id
    ref           = each.value.gitlab_jwt_auth_params.auth_claims.ref
    ref_type      = each.value.gitlab_jwt_auth_params.auth_claims.ref_type
    ref_protected = each.value.gitlab_jwt_auth_params.auth_claims.ref_protected
  }
  claim_mappings = local.jwt_claims_mapping
}
```

**Comment by loicgreffier** [comment]
@BornToBeRoot 

Setting `jwks_url` to `https://gitlab.com/oauth/discovery/keys` instead of `/-/jwks` looks to do the trick as well (not sure this is recommended tho)

**Comment by fairclothjm** [comment]
@loicgreffier @peikk0 

Update: We have reverted the behavior change for auth jwt roles. This will be reflected in Vault 1.16.5 and 1.15.11.

However, 1.17 and later will maintain the requirement that the `bound_audiences` parameter of “jwt” roles is required if the `aud` claim is set on the JWT. If the `aud` claim on the JWT is empty, then the `bound_audiences` is not required on the role.

https://developer.hashicorp.com/vault/api-docs/auth/jwt#bound_audiences

**Comment by ricardosilva86** [comment]
> @loicgreffier Thanks for the details. Your token has an `aud` claim that is a single string which is what we expected caused this issue. If you changed the JWT's `aud` claim to be an array ` "aud": ["https://first.service.com"]` then you would get the same error in 1.16.2.
> ...

hi @fairclothjm ... how exactly should I make this `aud` an array? can I control the JWT output format?

**Comment by ricardosilva86** [comment]
Context:
at the moment, I have ` bound_audiences` set, but I still the the same error:
```
resource "vault_policy" "gitlab_pipeline_secrets_generic" {
  name   = "team-pipeline-general"
  policy = <<EOT
path "team_pipelines/*" {
  capabilities = ["read"]
}
EOT
}

resource "vault_jwt_auth_backend_role" "gitlab_pipeline_readonly" {
  backend           = "gitlab" # already configured as gitlab jwt pipeline
  role_type         = "jwt"
  role_name         = "team-pipeline-general"
  token_policies    = ["team-pipeline-general"]
  bound_audiences   = ["https://gitlab-prod.<mycompany>.com"]
  user_claim        = "user_email"
  bound_claims_type = "glob"
  token_ttl         = 600
  bound_claims = {
    project_path = "team/*"
  }
}
```

**Comment by ricardosilva86** [comment]
> @ricardosilva86 Hello, what version of Vault are you running?
👋 
1.17.2

**Comment by fairclothjm** [comment]
@ricardosilva86 Thanks, and what is the `aud` claim on your jwt?

**Comment by ricardosilva86** [comment]
> `"aud": "https://gitlab-prod.<mycompany>.com"`

**Comment by xcompass** [comment]
@ricardosilva86 i had the same issue. In my case, the issue was my role name did not match the one in Vault.
