### ISSUE TITLE
feature: secret_id/lookup should return last_used_time

### ISSUE THREAD

**Issue by stampycode** [hashicorp/vault#2734]
I would like to be able to manually or scriptedly remove old secrets that would otherwise have a very long expiry time, but I can't determine which secrets are still in active use without repeatedly checking the `secret_id_num_uses` field and comparing them over time.

The [/auth/approle/role/[role_name]/secret-id/lookup](https://www.vaultproject.io/docs/auth/approle.html#auth-approle-role-role_name-secret-id-lookup) endpoint outputs these fields:
```
{
  "data": {
    "creation_time": "2016-09-28T21:00:46.760570318-04:00",
    "expiration_time": "0001-01-01T00:00:00Z",
    "last_updated_time": "2016-09-28T21:00:46.760570318-04:00",
    "secret_id_num_uses": 10,
    ...
  }
  ...
}
```

So we know that the `secret_id_num_uses` field records the number of times the secret has been used, but we don't know when the last time it was used - can we please add this field?

Suggest `last_used_time` ?

**Comment by vishalnayak** [comment]
@stampycode There is already a `last_updated_time` which does get updated every time `secret_id_num_uses` is decremented.

**Comment by stampycode** [comment]
Then I suggest both the documentation description and the example code be updated to reflect that, because the example shown currently says that the token`last_updated_time` is exactly the same as the `creation_time` and yet the `secret_id_num_uses` value is 10.

This suggests the secret was used 10 times in under .000000001 seconds.

**Comment by vishalnayak** [comment]
@stampycode Initially `last_updated_time` will be equal to `creation_time`. If you lookup the secret_id _after_ using it few times, you should see a different value. The documentation example is of a result of lookup before using the secret_id.

**Comment by stampycode** [comment]
Oh, so `secret_id_num_uses` is actually a countdown?
And by using the secret it triggers an 'update' of the secret. 🤔

I still think the documentation needs updating... 😉

**Comment by stampycode** [comment]
@vishalnayak if the `secret_id_num_uses` is set to zero by policy, then the secret is _not_ updated each time the secret is used. The `last_updated_time` is therefor also not updated.

It would be better to output a separate `last_used_time` field anyway; the `last_updated_time` field serves a different purpose. For this reason I also recommend not simply updating the `last_updated_time` field to show when a secret was last used - this makes the field confusing, as technically nothing else in the object has changed except this field, which makes the field self-referencing, which is just madness.

Please re-open this ticket 😉

**Comment by jefferai** [comment]
Can you please explain the use case? I've reread your original post and it's not clear what this would be useful for.

**Comment by stampycode** [comment]
@jefferai yup - I have a secret that I issue to each instance of a containerised app, and I might spin up multiple instances of that app - I'm expecting this secret to be used every hour to fetch a new token from Vault for making requests, and each token will be used many times per second.

If I see that a secret has not been used for 4 hours, I can make the assumption that it is no longer attached to a live container, and should be removed, but currently there is no way for me to see via Vault when the secret was last used.

Essentially it would be a very useful field for garbage-collecting unused secrets.

**Comment by jefferai** [comment]
How are you providing the secret to you containers? What's the provisioning workflow?

**Comment by stampycode** [comment]
@jefferai Not sure why that's relevant; if I have secrets in Vault that have no `secret_id_num_uses` (maybe that other developers have manually created), then I need to be able to see when they were last used, so I can clean them up... Currently I have no way to tell if a secret created 12 months ago is used every minute, or hasn't been used since the day it was created.

It would be trivial for Vault to store this information.

**Comment by jefferai** [comment]
It's relevant because it's entirely possible that what you're doing now is not the ideal method for your needs.

**Comment by stampycode** [comment]
Our design decisions aren't up for discussion - we have a paid license for Vault. 😉

I'm asking for a very simple new feature, not design advice. 😁

**Comment by bheiskell-datto** [comment]
@jefferai 

I bumped into this while trying to determine which of an AppRole's secret-ids were active. Only one should have existed. It's easy enough to fix be re-provisioning the secret-id and destroying the others, but it would be handy to not need to do that.
