### ISSUE TITLE
revoke with aws prefix fails with large number of leases

### ISSUE THREAD

**Issue by pieterbreed** [hashicorp/vault#2735]
Due to a configuration mistake(s) we created 5000 IAM credentials using vault and the expiry on those leases are still far into the future. I want to revoke all of those tokens.

I am using `vault revoke -prefix aws/creds/name` and that command fails after a few 10's of revocations:

```
$ vault revoke -prefix aws/creds/name
Revoke error: Error making API request.

URL: PUT http://localhost:8200/v1/sys/revoke-prefix/aws/creds/name
Code: 400. Errors:

* failed to revoke 'aws/creds/name/060dce0e-6d6a-96c7-9028-c935c7748765' (1 / 4879): failed to revoke entry: resp:(*logical.Response)(nil) err:NoSuchEntity: The user with name name-447ecbab-f6d7-f714-e883-cb6259879aae1494643761-7978 cannot be found.
	status code: 404, request id: 28e77869-3a37-11e7-a21d-3d0ace72e7d2
```

After seeing that error a few times I tried to add `-force`: 

```
$ vault revoke -force -prefix aws/creds/name
Revoke error: Put http://localhost:8200/v1/sys/revoke-force/aws/creds/name: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

By looking at the AWS IAM console I can see that the tokens are slowly being reduced. After restarting the revoke command ~13 times, I've cleared up ~500 tokens.

**Comment by jefferai** [comment]
Hi there,

Using force is correct in this circumstance; my guess about the speed is that you are being throttled on the AWS API so eventually the client times out. You could create a custom client if you wanted that has longer timeout values.

**Comment by pieterbreed** [comment]
Thanks for the quick reply.

I don't really mind the speed at which the revocations are happening. By my reckoning it's going to take about an hour to delete all 5000 accounts.

My bug report is more concerned about the fact that vault errors out, regardless of whether `-force` is used or not.

In my terminal window, I have this running:

```
$ while true; do vault revoke -force ...; done
```

There are _many_ lines like this:

```
Revoke error: Put http://localhost:8200/v1/sys/revoke-force/aws/creds/name: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

and I am refreshing the IAM console to see how far I'm getting.

**Comment by jefferai** [comment]
That's exactly what my reply was about...

**Comment by otakup0pe** [comment]
We stumbled across this as well. Do we think this is rate limit related? In our case, it might have been due to the underlying IAM users disappearing. Would a PR to cover _both_ of these cases be welcome? A quick glance did not uncover one in flight....

**Comment by jefferai** [comment]
@otakup0pe sure, but what do you think such a PR would do?

**Comment by otakup0pe** [comment]
I think this would be two separate fixes. One to address rate limits (add some exponential backoff) and another to just throw warnings when IAM users are missing.

**Comment by jefferai** [comment]
It seems like both of these are already things that can be done.

The client can adjust its timeout; revoke-force can clean up in the case of errors without making assumptions that this is the right thing to do.

**Comment by michelvocks** [comment]
Hi there!

I will close this issue due to inactivity and due to the fact, that a solution is already in place which Jeff mentioned. Feel free to reopen a new issue if the described solution doesn't work for you.

Cheers,
Michel
