### ISSUE TITLE
Generating multiple dynamic policies and tokens

### ISSUE THREAD

**Issue by henrymollman** [hashicorp/vault#2736]
I need to create restricted policies to read specific paths, and limit that policy to only that path. I am able to create the policies dynamically but cannot generate tokens for those policies using a role with permission to write to auth/token/create. When I attempt to generate a policy, I get the error * "child policies must be subset of parent". I understand that the token generated must have a subset of the parents allowed policies, but this becomes difficult when I need to generate the policy for a certain sub-path that is dynamic. 

The only way to do what I intend seems to be using the root token, but I hope to avoid exposing this token as much as possible. For reference, here are the policies:

Policy creation, in which I tried using a blob as well as the create path:

```
path "auth/token/create/*" {
  capabilities = ["create", "update"]
}
path "sys/policy/*" {
  capabilities = ["create", "update"]
}
path "auth/token/create" {
  capabilities = ["create", "update"]
}
```
Dynamically created policy:
```
path "secret/organization/{{generated-id}}" {
  policy = "read"
}
```

If I have to add this generated policy to the token-generating policy each time, so that it can include a subset of the parent, is this appendable?

**Comment by vishalnayak** [comment]
@henrymollman You can use [token roles](https://www.vaultproject.io/docs/auth/token.html#auth-token-roles-role_name-) to achieve this. There are 2 fields on the token store role that are of interest; `allowed_policies` and `disallowed_policies`. Allowed policies acts as a whitelist (allows creation of tokens for policies listed). Disallowed policies acts as a blacklist (allows creation of tokens for policies that are *not* listed).

If you are aware of all the names of the dynamic policies that you are going to generate, then creating a token role with all of those policy names as `allowed_policies` seems one way to do it.

**Comment by cpacejo** [comment]
I'm not sure why this was closed?  @vishalnayak's answer doesn't seem to satisfy @henrymollman's use case.  (The primary reason to dynamically generate policies is that you *can't* enumerate them all in advance.)

I think I'm looking for exactly the same solution as the OP.  I really need a way to say "X is allowed to create tokens which have a subset of X's *permissions*".  (Use case: user gives various machines permission to do something which is a function of each machine's name.)  Because Vault insists that the *policies* be a subset, I can see no way to do this short of root/sudo permissions, not even through fancy use of the policy system.

If Vault supported a way to create a token/role which is permitted the *intersection* of sets of policies (and enforced only that each of the caller's intersected policy sets need be a subset of one of the intersected policy sets of the new token/role), that would suffice.  But I don't think that's supported.

Help would be greatly appreciated, or a response that my use case is not supported by Vault and I should look elsewhere.

**Comment by jefferai** [comment]
It was closed because the OP's described ask is something that can be achieved with token store roles, as Vishal explained. See https://www.vaultproject.io/api/auth/token/index.html#create-update-token-role

**Comment by cpacejo** [comment]
As I mentioned in my comment, I fail to see how token roles fulfill the dynamic policy use case.  (And yes, I've read the documentation.)

As I see it, using token roles, one must either:

A: Know the policy names *a priori*, and enumerate them in the `allowed_policies` field.  This is not possible when e.g. policies are a function of hostnames, which may be dynamically allocated.

B: Generate the roles *and* policies dynamically, with the generated policy in the `allowed_policies` field.  Naively, this would require root/sudo privileges, which for obvious reasons is a no-go.  We could get clever and say, well, the `allowed_policies` field must point to a policy with a name following a given pattern, and that the generating user is allowed to create policies with names matching that pattern only if they fulfill certain requirements.  But I don't believe the policy language is rich enough to usefully (and precisely) restrict the policy documents a user is allowed to create.  (I could be wrong here, but my understanding is that the policy language at its richest supports only simple string matching.  If writing a policy to restrict policy documents is even possible, doing so will certainly be error-prone.)

C: Generate the policies dynamically, and use a static role with `disallowed_policies` set to the intersection of all policies *except* the dynamic ones.  Beside being extremely brittle (as blacklists are), this breaks as soon as there are two such families of dynamic policies.

Is there a fourth possibility using roles which I'm missing?  Or am I misunderstanding the limitations I've outlined above?

**Comment by jefferai** [comment]
@cpacejo You asked why the ticket was closed. We answered the OP's set of requirements and they did not respond with any indication that the answer was not sufficient, so we reasonably assumed that it was and closed the ticket. You appear to have a different set of requirements.

**Comment by cpacejo** [comment]
Thanks, that's a very helpful answer.
