### ISSUE TITLE
must use allow_any_name to create a cert with PKI.

### ISSUE THREAD

**Issue by st33v** [hashicorp/vault#2738]
I'm pretty sure this is user error or something I'm doing wrong. If someone could lend some clarity, I'd be ever so grateful.

I'm creating a PKI like this:
`[centos@consul-2 ~]$ vault write pki/roles/servers enforce_hostnames=false allow_localhost=true allow_bare_domains=true allowed_domains="$DOMAIN" 
Success! Data written to: pki/roles/servers`

but creating a cert fails like this:
`[centos@consul-2 ~]$ vault write -format=json pki/issue/servers common_name="foo.$DOMAIN" ttl="43830h"  ip_sans="127.0.0.1" > response.json
Error writing data to pki/issue/servers: Error making API request.
URL: PUT http://127.0.0.1:8200/v1/pki/issue/servers
Code: 400. Errors:
* common name foo.foo.com not allowed by this role`

it works if I set allow_any_name=true which seems like treating dandruff with decapitation.

I'm using:
`[centos@consul-2 ~]$ vault -v
Vault v0.7.2 ('d28dd5a018294562dbc9a18c95554d52b5d12390')`

what am I doing wrong?

**Comment by st33v** [comment]
there's the whole role:
`[centos@consul-2 ~]$ vault read pki/roles/servers
Key                    	Value
---                    	-----
allow_any_name         	true
allow_bare_domains     	true
allow_base_domain      	false
allow_glob_domains     	false
allow_ip_sans          	true
allow_localhost        	true
allow_subdomains       	false
allow_token_displayname	false
allowed_domains        	foo.com
client_flag            	true
code_signing_flag      	false
email_protection_flag  	false
enforce_hostnames      	false
generate_lease         	false
key_bits               	2048
key_type               	rsa
key_usage              	DigitalSignature,KeyAgreement,KeyEncipherment
max_ttl                	87600h0m0s
no_store               	false
organization           	
ou                     	
server_flag            	true
ttl                    	768h0m0s
use_csr_common_name    	true
use_csr_sans           	true
`

**Comment by chrishoffman** [comment]
Your configuration will only allow you to issue certificates for the bare domain (`$DOMAIN`).  You need to add the parameter `allow_subdomains` to be issue certificates for `$SUBDOMAIN.$DOMAIN`. See https://www.vaultproject.io/api/secret/pki/index.html#allow_subdomains.
