### ISSUE TITLE
Getting "strconv.ParseInt" errors when using non-interpolated variables in Vault config

### ISSUE THREAD

**Issue by gaballard** [hashicorp/vault#2739]
I'm trying the most basic of configurations and getting the following errors:

`Error loading configuration from /vault/config: Error loading /vault/config/vault-config.hcl: strconv.ParseInt: parsing [string]: invalid syntax`

We're using Vault v0.7.0 through the official Docker image. We're starting the server via `docker run [image ID] server`.

vault-config.hcl is as follows:

```
storage "gcs" {
  bucket           = "[bucket]"
  credentials_file = "/tmp/credentials.json"
}

cluster_name       = "[name]"

listener "tcp" {
  address          = "127.0.0.1:8200"
}

cache_size         = "32k"

default_lease_ttl  = "7d"
max_lease_ttl      = "31d"
```

We tried the following:

- With `cache_size` set to `"32k"`, `default_lease_ttl` set to `"7d"`, and `max_lease_ttl` set to `"31d"`, it throws the following error:

`Error loading configuration from /vault/config: Error loading /vault/config/vault-config.hcl: strconv.ParseInt: parsing "32k": invalid syntax`

- With `cache_size` set to `"32"` (the `k` having been removed), `default_lease_ttl` set to `"7d"`, and `max_lease_ttl` set to `"31d"`, it throws the following error:

`Error loading configuration from /vault/config: Error loading /vault/config/vault-config.hcl: strconv.ParseInt: parsing "31d": invalid syntax`

Curiously, it does not throw an error on the `default_lease_ttl` option at this point.

- With `cache_size` set to `"32"` (sans the `k`), `default_lease_ttl` set to `"7d"`, and `max_lease_ttl` set to `"31"` (sans the `d`), it throws the following error:

`Error loading configuration from /vault/config: Error loading /vault/config/vault-config.hcl: strconv.ParseInt: parsing "7d": invalid syntax`

Removing all the suffixes from the values (`32k` > `32`, `7d` > `7`, `31d` > `31`) causes the server to start without issue; however, without them, how does Vault know if "31" refers to 31 seconds, hours, or days?

**Comment by vishalnayak** [comment]
@gaballard Part of the problem you are noticing is due to a documentation bug.

The value of `cache_size` config should be number of entries in cache, example 32000. It does not understand `32k`. Fixed the doc in d2aa8c1f1252138e2a12eb63acd9af3754de6c81.

Regarding `max_lease_ttl` and `default_lease_ttl`, they can understand `h`, `m` and `s`, but not `d`. You are not seeing error for `default_lease_ttl` because `max_lease_ttl` errors out first regardless of the order in which it is supplied in the config file.
