### ISSUE TITLE
Doc

### ISSUE THREAD

**Issue by Aliendie** [hashicorp/vault#27403]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by hsimon-hashicorp** [comment]
Closing this issue - please open a new one if you would like to report a bug or request an enhancement. Thank you!
