### ISSUE TITLE
Vault as a service

### ISSUE THREAD

**Issue by StyleT** [hashicorp/vault#2740]
I think about providing Vault as secrets manager service inside my organization. And the biggest issue I see here that it's impossible to provide full access only to the limited part of the Vault. 

For example I have 2 teams: A & B. So I want to create policy which grants full access to every path that starts from `teams/A/*`, allows to mount any secret backend inside `teams/A/*`& create policies which works only inside `teams/A/*` so leader of team A can't grant access to the team's B resources.

Also administrator of the Vault should be able to set some global policies which limits some security options. For example team members can't mount MySQL secret backend with `max_lease > 10 days`.

I think as a first step policies can be represented as a tree structure rather than flat list so evaluation will go from the root to the leaves.

**Comment by StyleT** [comment]
@jefferai Hi! Can we expect any updates here?

**Comment by StyleT** [comment]
Can such experience at least be achieved with Sentinel + Vault Enterprise?

**Comment by jefferai** [comment]
You can't do this directly now -- some of it is achievable with Sentinel -- but we have some plans to address this kind of use case in the next 6 months.

**Comment by StyleT** [comment]
@jefferai thank you for the feedback! Looking forward for the updates :)

**Comment by jefferai** [comment]
@StyleT I'm going to close this purely to keep open issues lower. Addressing this kind of need is a major item on our roadmap within the next 2-3 minor releases and everything you listed above should be possible...keeping this open as a reminder isn't necessary, I promise :-)
