### ISSUE TITLE
Audit entries on permission denied

### ISSUE THREAD

**Issue by bkrodgers** [hashicorp/vault#2741]
If someone who is authenticated to Vault tries to read something they do not have access to, I'm seeing the following in the audit log:
```
{
  "time": "2017-05-17T22:21:38Z",
  "type": "request",
  "auth": {
    "client_token": "",
    "accessor": "",
    "display_name": "",
    "policies": null,
    "metadata": null
  },
  "request": {
    "id": "<req-id>",
    "operation": "read",
    "client_token": "hmac-sha256:<token>",
    "client_token_accessor": "<token>",
    "path": "<path>",
    "data": null,
    "remote_address": "<ip>",
    "wrap_ttl": 0,
    "headers": {}
  },
  "error": "permission denied"
}
{
  "time": "2017-05-17T22:21:38Z",
  "type": "response",
  "auth": {
    "client_token": "",
    "accessor": "",
    "display_name": "",
    "policies": null,
    "metadata": null
  },
  "request": {
    "id": "<id>",
    "operation": "read",
    "client_token": "hmac-sha256:<token>",
    "client_token_accessor": "<token>",
    "path": "<path>",
    "data": null,
    "remote_address": "<ip>",
    "wrap_ttl": 0,
    "headers": {}
  },
  "response": {
    "data": {
      "error": "hmac-sha256:<hmac>"
    }
  },
  "error": "1 error occurred:\n\n* permission denied"
}
```

Two questions/requests:

1. Why isn't it logging the auth info?  The user is authenticated and presented the token, they were just denied by policy.
2. Can it log errors with a status code (either the HTTP response code or a custom set of codes you'd make up) so that my alerting doesn't have to do a string search for "permission denied" to filter failed reads in/out of a query against my audit data?

**Comment by jefferai** [comment]
@bkrodgers the auth block, similar to in `api.Secret`, is populated when authentication information is *returned*. The values you're looking for are already in the audit entry under the `request` block -- `client_token` and `client_token_accessor`.

**Comment by bkrodgers** [comment]
So are you saying that because they didn't pass through the ACL check for that path, the `auth` block doesn't get returned in the audit entry?  Is it possible that could be changed so that it does? I know I can lookup the token with the accessor while it's still an active token, but it doesn't look like I can once the token has expired.  I get `invalid accessor` from `auth/token/lookup-accessor`.  Even if I could, having the `display-name` for the token in the audit data directly would be very useful.

My use case is that I have paths that have credentials that should only be used in exceptional circumstances, so we want to alert when they're read.  I have something setup to scan the audit logs in ELK and send slack messages.  For the time being we're interested in failed attempts too.  Obviously if someone tries to access it who isn't using a valid token at all there's no auth data to present.  But if somebody presents a valid token but just doesn't have access by policy, we know who they are, and I'd like to include the token's display name so we can talk to them about what they're trying to do.

**Comment by jefferai** [comment]
No, but I don't know how else to put it. Just like in normal vault responses, values in the auth block correspond to new tokens being generated in the response to that client request. Tokens used as part of the request itself are in the request block in client_token and client_token_accessor. Those already exist in the examples you posted above.

**Comment by bkrodgers** [comment]
These aren't requests for new tokens at all though.  These are just `read` requests on the `secret` backend.  If the user had access to do the read, the auth data is populated, even though no new token is being generated.

**Comment by bkrodgers** [comment]
I think the technical reason it doesn't log what I'm expecting is that in core.go, if the ACL check denies access, `checkToken` returns a nil `auth` object along with a `logical.ErrPermissionDenied` error.  (specifically line 662-668).  But the code that calls this in `request_handling.go` is looking at whether `ctErr` is nil or not, and not relying on whether `auth` is nil.  

I haven't dug deeper to look for any side effects, but it looks like if `checkToken` still returned the `auth` object for a token that is valid but failed ACL check, it would log the auth info the way I'm expecting.

**Comment by jefferai** [comment]
Any chance you can send a PR?

**Comment by bkrodgers** [comment]
Yeah, testing it to make sure I've got it right.

**Comment by bkrodgers** [comment]
PR submitted and linked.  Hopefully at the very least it helps illustrate what I'm talking about.  I think it fixes it with no side effects, but take a look and let me know what you think.

**Comment by bkrodgers** [comment]
One other thing I noticed is that for both the request and response audit logs, under `auth` the `client_token` and `accessor` fields will always be blank.  The code to populate them is missing.  I've got a fix for that ready to push onto the same PR if you want, but i wanted to hold off and ask you, as these fields are redundant to the same fields in the `request` object of both a request and response entry.  Personally I think it makes more sense for it to be under `auth`, but of course we wouldn't want to immediately break anyone expecting those tokens to be where they are today.

I'd vote for adding them into  the `auth` object, leaving them in `request` for now but deprecating them.  If you disagree and want to leave them where they are, I'd suggest removing them from the `auth` object then.  As it stands right now, they'll be blank, every time, guaranteed.

**Comment by jefferai** [comment]
Generally speaking many things could be removed from most entries and it's easy via omitempty, I think there was a fear that unknown JSON parsing lib X could choke if it were suddenly removed (even if it shouldn't). I'm not sure how valid that is given I don't know every lib out there.

Properly auth shouldn't even exist at the top level but backwards compatibility. If we end up breaking one thing we should just break everything at once but other than annoyance I don't​ see a compelling reason to break so leave the values in the request for now.
