### ISSUE TITLE
Backing up and restoring vault in a HA scenario

### ISSUE THREAD

**Issue by osadalakmal** [hashicorp/vault#2743]
I have read through the available documentation but cant find any info on an official guide to how backups and restores are to be done. I did see some users using consul snapshot ability to implement a backup strategy (with come caveats) . But they don't seem to be officially supported.

**Comment by StyleT** [comment]
Same issue here

**Comment by chrishoffman** [comment]
This ends up being highly dependent on the storage backend you choose and the data recovery requirements for your organization.  My suggestion would be to use the backend that you are most comfortable with and see what methods are available for that backend.  As with any backup/restore strategy, make sure you test it often to make sure it is suitable for your needs.

**Comment by StyleT** [comment]
@chrishoffman Hi! Maybe it would be reasonable to add your words to the official documentation? Maybe even with some sample solutions in future.

**Comment by osadalakmal** [comment]
Yeah, if we can add even that disclaimer to the documentation it would be
great. We are going ahead with using consul snapshots for backup and
restore.
