### ISSUE TITLE
Documentation for beginners

### ISSUE THREAD

**Issue by DockerAsura** [hashicorp/vault#2748]
Hi Team,
I am new to this tools(vault). can someone send URL's for webnair session or understandable documentation for beginners.

little confused  with official documents, because that document is high level.

Thanks
DockerAsura

**Comment by vishalnayak** [comment]
@DockerAsura Some of the HashiCorp webinars are on YouTube (https://www.youtube.com/watch?v=FGbzS6ripXA&list=PL81sUbsFNc5aHvC3tAJRr7GlaMcS19zSO). 

The official documentation (https://www.vaultproject.io/) are for both beginners and for those who wants to understand the workings on a technical level. Let us know what in specific do you need that is not covered by the docs.
