### ISSUE TITLE
Github Auth hcl configuration

### ISSUE THREAD

**Issue by chavezom** [hashicorp/vault#2750]
I am trying to setup Github auth using vault docker image, but there are no examples of this anywhere

**Comment by calvn** [comment]
The docs in https://www.vaultproject.io/docs/auth/github.html#configuration should get you started on a basic setup.

**Comment by chavezom** [comment]
I already tested them with the cli. But I need to automate the configuration using docker and there is no documentation on how to do it. What I need is a json or hcl file to configure it thru Docker.

**Comment by calvn** [comment]
There are many ways to go about this, including wrapping the necessary commands inside a bash script, and executing it once vault server is up and running. [This repository](https://github.com/Caiyeon/goldfish/tree/master/docker) provides a more concrete example of how the author sets up his vault server. Similarly, you can execute a script that runs those commands via your preferred deployment stack.

**Comment by chavezom** [comment]
Thanks for your response @calvn, I assume this means that there is no way to configure it with a hcl file placed in /vault/config/ folder.

**Comment by miqui** [comment]
@calvn - thanks,  what @chavezom (and myself, i have the same use case) is to configure github auth via either a json or hcl file.  Based on your feedback then i take it can only be done via the vault CLI?

**Comment by calvn** [comment]
That's correct, the backend cannot be configured via JSON or HCL. The available options are either interacting with the CLI, or through the HTTP API as depicted in the [example docs](https://www.vaultproject.io/docs/auth/github.html).

**Comment by chavezom** [comment]
Thanks for your confirmation @calvn
