### ISSUE TITLE
vault command completion

### ISSUE THREAD

**Issue by albenstein** [hashicorp/vault#2751]
Hi,
If there is vault command completion by default, it will be useful.
For example,
$ vault list secret/[tab] => will show list options for available files/folders
$ vault read secret/[tab] => will show read options for available files/folders
(and for others commands = vault {write,delete} etc.

**Comment by vishalnayak** [comment]
@albenstein It introduces considerable expense in terms of API calls and with not much value add since Vault commands usually get scripted and is not overly inclined towards human interaction. This is unlikely to get on the roadmap. Sorry.

**Comment by jefferai** [comment]
@albenstein If you're up for creating bashcomp/zshcomp/whatever files we'd be happy to host them in the Vault repo. Interested packagers could then create packages for installation!

**Comment by albenstein** [comment]
@jefferai thanks for your answer. I have just started to write bash-completion script for vault. When I finish to write it, I will share with you.
