### ISSUE TITLE
Fix #26634 not work in Vault 1.17.0

### ISSUE THREAD

**Issue by karabanov** [hashicorp/vault#27524]
**Describe the bug**
Try to add new line in kv2 json editor and the pointer goes to start.

**To Reproduce**
1. Open any kv2 json.
2. Click on Create New Version
3. Put the pointer in some place in json
4. Press Enter to add new line and the pointer goes to start

**Expected behavior**
New line successfully added.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.17.0
* Vault CLI Version (retrieve with `vault version`): 1.17.0
* Server Operating System/Architecture: Official Docker image with Vault

**Additional context**
This bug was fixed in #26634, but it is still reproducible.

**Comment by karabanov** [comment]
Added new issue #27524 about this bug

**Comment by hashishaw** [comment]
This issue should now be fully fixed with this PR: https://github.com/hashicorp/vault/pull/27569 

Thanks!

**Comment by karabanov** [comment]
The bug no longer appears. I confirm.
Thank you.
