### ISSUE TITLE
Subscribe to events notifications does not work on secondary nodes

### ISSUE THREAD

**Issue by radup123** [hashicorp/vault#27551]
**Describe the bug**
Subscribe to events notifications does not work on secondary nodes.
**To Reproduce**
1. Create a cluster with at least 3 nodes
2. Create a namespace
3. Under the namespace, create a mount point
4. Try to subscribe to events for the created mount point under the namespace by sending a request to a secondary node
5. Note the error: https://<cluster_address>v1/<namespace>/sys/events/subscribe/kv-v2/%2A?json=true isn't a valid URI: scheme isn't ws or wss

**Expected behavior**
Subscribe should work.
**Environment:**
* Vault Server Version 1.16.3
* Vault CLI Version: Not used, REST API used instead

Vault server configuration file(s):

```
The test cluster is a 3 node enterprise cluster.
```

**Additional context**
-

**Comment by miagilepner** [comment]
Hi, you'll need to use a websocket URI in order to subscribe to events, such as `wss://<cluster_address>v1/sys/events/subscribe/kv-v2?json=true`. Please try that and let us know if you're still having issues.

**Comment by radup123** [comment]
Yes, I am using a websocket URI. The error i showed you is what I get from Vault when doing thee request to a secondary node. When hitting the primary node, it works.

**Comment by miagilepner** [comment]
Unfortunately I can't seem to reproduce this issue. The error you received appears to be from the python websockets library, and I tested subscribing to a performance standby node and a regular standby node with the following script. In both cases, I was able to receive the event stream.

```python
#!/usr/bin/env python

from websockets.legacy.client import connect
import asyncio
import ssl

async def get_event():
    ctx = ssl.create_default_context(cafile="/Users/mia.epner/scratch/events/certs/vault-ca.pem")

    async with connect("wss://<my vault address>/v1/sys/events/subscribe/*", ssl=ctx, extra_headers={"X-VAULT-TOKEN":"<my vault token>"}) as websocket:
        message = await websocket.recv()
        print(f"Received: {message}")

asyncio.get_event_loop().run_until_complete(get_event())
```

If you have a minimal example that I can use to reproduce your issue, then I'd be happy to continue investigating.

**Comment by radup123** [comment]
If you replace <my vault address> with the address of a secondary node, you will be able to reproduce the bug.

**Comment by miagilepner** [comment]
The address is a Vault standby node. As mentioned, I have also tried with a performance standby. Both succeed.

**Comment by miagilepner** [comment]
When adding the X-VAULT-NAMESPACE header I do see the server returning a 500, and the server log 
```
Could not accept as websocket: error="failed to accept WebSocket connection: WebSocket protocol violation: handshake request must be at least HTTP/1.1
```

This appears to be a real bug, though I can't reproduce the exact error that you're seeing. Thanks for finding this!
