### ISSUE TITLE
Add a guide on rekeying the Vault

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#2757]
We already have a guide on root token generation, but I realized we don't have a short guide on rekeying the Vault.

**Comment by jkdihenkar** [comment]
I was having the same difficulty when learning about rekeying.
I have added commands: https://github.com/jkdihenkar/vault_learning/tree/master/others/rekey_cmds **and** a py based rekeying implementation: 
https://github.com/jkdihenkar/vault_learning/blob/master/pyconsumables/hello_vault_t2_rekey_test.py

Hope this helps.
