### ISSUE TITLE
Policies attached to the user should override group ones in LDAP auth backend

### ISSUE THREAD

**Issue by StyleT** [hashicorp/vault#2759]
Currently it's impossible to grant additional permissions to the user in LDAP auth backend.

Example:
User's policy:
```hcl
path "*" {
  policy = "sudo"
}
```

Group policy:
```hcl
path "secret/*" {
  policy = "read"
}
```

As result user will be able only to read secrets from `secret/*` path.

**Comment by chrishoffman** [comment]
Vault uses the most specific policy when matching policies.  In your case, the group policy for `secret/*` is more specific than `*` so it is the one that is matched for any path under `secret/`.  My recommendation would be to put your admins in only an admin group.  

See https://www.vaultproject.io/docs/concepts/policies.html for more information.

**Comment by StyleT** [comment]
@chrishoffman Hi! I know that currently Vault uses this simple logic only. Unfortunately when you're working with corporate LDAP you can't control groups in all cases. Also you always have the following simple use case: Someone who already have one/multiple LDAP groups should have additional personal grants. And with current implementation Vault is useless here :(

I have never had such issue with AWS IAM policies as they are applying the most "powerful" rule from all policies you have & if you want to lower grants of some user you can use "deny" rule. See http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html

I can rewrite this issue but It's definitely shouldn't be closed as it's a feature request, not a bug.

**Comment by vishalnayak** [comment]
@StyleT The issue description is quoting facts and not describing what the feature request is. Internally, there are initiatives that will improve handling of groups across all the authentication backends (not only LDAP). Stay tuned for it. In this respect, we'll leave the issue closed.

**Comment by StyleT** [comment]
@vishalnayak ok, thank you for update!
