### ISSUE TITLE
Add the jq package/binary to the container image

### ISSUE THREAD

**Issue by jsalatiel** [hashicorp/vault#27606]
**Is your feature request related to a problem? Please describe.**
There are so many examples in the documentation that refers to using some cli command and pipe the output to jq that it should be nice to have the jq binary inside the container image.

**Describe the solution you'd like**
I know I can download the vault client and connect to the remote server, but for small tests it would be a lot better just having the jq binary in the container.

**Comment by miagilepner** [comment]
Hi, thanks for submitting your request! Because we would like to keep the container image as minimal and focused as possible, we don't want to add jq or other non-required dependencies. You can always use the vault docker image as a base image, and then download jq on top of that.
