### ISSUE TITLE
Policy creation api call not correctly associating rules

### ISSUE THREAD

**Issue by max-abramowitz-reif-ck** [hashicorp/vault#2763]
v0.6.3
When hitting the API endpoint for creating a policy at /sys/policy/<policy_name> via a PUT, the json encoded rules I am passing through in the payload are not being correctly associated. I don't believe this is an issue with the json itself, as creating the same policy through the cli associates them correctly.

I'm calling the api locally as such:
`curl -kv -X PUT  -H "X-Vault-Token: TOKEN" --data "{ \"path\": { \"auth/token/create\": { \"policy\": \"write\"}}}" http://127.0.0.1:8200/v1/sys/policy/test_pol`

The call returns a 204 and successfully creates the policy, but without the attached rules. The same behavior happens whether passing the rules data through a file w/o escaping or on the command line. However, the same file submitted to `vault policy-write` produces the correct policy rules. 

Any tips on what I might be doing wrong?

**Comment by vishalnayak** [comment]
@max-abramowitz-reif-ck The `sys/policy/<policy_name>` API expects a `rules` field, which the CLI internally populates before invoking the API. 

The body should look like the following:
`--data '{"rules":"{\"path\": {\"auth/token/create\": { \"policy\": \"write\"}}}"}'`

**Comment by max-abramowitz-reif-ck** [comment]
That worked, thanks for the help @vishalnayak! However, if the rules data is received by the vault server in a malformed state, shouldn't it give some sort of an error response instead of silently throwing away that data?
