### ISSUE TITLE
Unable to unmount postgres and database is being spammed with user creations

### ISSUE THREAD

**Issue by sheldonkwok** [hashicorp/vault#2764]
Vault version 0.6.5 with postgres mount

Our current setup uses consul-template and the postgresql creds secret to pull configuration. We launched hundreds of parallel workers which overwhelmed our database with connection requests. This unfortunately spiraled out of control since the workers were unable to start and rebooted which then initiated another request for credentials. Now, the database is very sluggish and we are unable to vault unmount. The Postgres logs report that users have been continuously made by vault for the past 6 hours even though the workers have been stopped for 5 hours.

Is there any way to forcibly stop the vault postgres mount?

**Comment by jefferai** [comment]
When you say "we are unable to vault unmount" what error are you seeing?

**Comment by sheldonkwok** [comment]
`net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**Comment by jefferai** [comment]
Can you try it with `curl` with `-max-time` and/or `--connect-timeout` set?
