### ISSUE TITLE
Latest vault/api release includes security vulnerability

### ISSUE THREAD

**Issue by luiscleto** [hashicorp/vault#27688]
**Describe the bug**
Not really a bug but the latest `vault/api` library release still includes a vulnerability:
```
Vulnerability #3: GO-2024-2947
    Leak of sensitive information to log files in
    github.com/hashicorp/go-retryablehttp
  More info: https://pkg.go.dev/vuln/GO-2024-2947
  Module: github.com/hashicorp/go-retryablehttp
    Found in: github.com/hashicorp/go-retryablehttp@v0.7.4
    Fixed in: github.com/hashicorp/go-retryablehttp@v0.7.7
    Example traces found:
```
Would be nice if we could have a new release as it appears to actually have been fixed already

**To Reproduce**
Import and use the vault/api library and use a logical method like `api.Logical.Delete`. Vulnerability check will detect the issue (golang.org/x/vuln/cmd/govulncheck)

**Expected behavior**
Latest release should include available vulnerability fixes

**Environment:**
N/A

Vault server configuration file(s):
N/A

**Additional context**
Seems to already be included in latest vault release, but missing the API & SDK releases

**Comment by miagilepner** [comment]
Hi, thanks for reporting this! A fix for this has already been [merged](https://github.com/hashicorp/vault/commit/037d82130ce4ddcf4dd932afcf56cc9570958701) and will be included in the next API release. Because this fix has been merged, I'm going to close this issue.
