### ISSUE TITLE
Full debug mode when debug logging is enabled?

### ISSUE THREAD

**Issue by samc-6ft** [hashicorp/vault#2768]
I just noticed this behavior while I was experimenting with LDAP authentication.  I had to enable debug logging on my test instance to figure out a problem, but when I did I observed that all policies were ignored.  No matter what user I used to log in, or what policies were associated with that user, the user had full unrestricted access to the vault.  They were root.

Restarting my test instance without -log-level=debug directive fixed this problem.  I would expect that running with the -log-level=debug would only elevate the logging level not enable a full debug mode on the vault.

**Comment by vishalnayak** [comment]
@samc-6ft That sounds very weird. I tried to authenticate with a test LDAP server with -log-level=debug but couldn't reproduce the problem you are mentioning. Which version of Vault are you using and if possible can you share steps to reproduce? It might also be good if you can show the policies tied to users and the policies tied to authenticated tokens with and without debug enabled.

**Comment by samc-6ft** [comment]
@vishalnayak I've been trying to repro this today and I'm not seeing the same behavior.  Apparently I must have had a token with admin access that persisted after authenticating with a different user.  That's just a guess, as I haven't been able to reproduce this at all.  I also don't have any logs from that test instance as it was destroyed overnight.  Go ahead and close this ticket, and I'm sorry for wasting some time.  I will work on reproducing this over the weekend to see if I can get anything to happen.  If I do I'll get all the info I can and post it here.
