### ISSUE TITLE
No checkpoint URL is available for vault

### ISSUE THREAD

**Issue by woohgit** [hashicorp/vault#2769]
Other hashicorp products have checkpoint URLs like:

- https://checkpoint-api.hashicorp.com/v1/check/terraform
- https://checkpoint-api.hashicorp.com/v1/check/packer
- https://checkpoint-api.hashicorp.com/v1/check/consul

According to the website: https://checkpoint.hashicorp.com vault should be there too.

Can you please add it to the checkpoint service? I'm usually doing automated installs/upgrades using the checkpoint service and vault is an exception in this case.

**Comment by jefferai** [comment]
I'm not sure why the text says Vault is known, but I think that is a mistake. We have not built checkpoint into Vault since the vast majority of our users never want their security product reaching out on its own.

**Comment by woohgit** [comment]
@jefferai and what about a vault client on my laptop? That's not a server but a client and I'd love to get notified when it has a newer version.

**Comment by jefferai** [comment]
I didn't say there aren't use cases. Just that we haven't seen enough demand to work through doing it securely and building it.

**Comment by karlkfi** [comment]
In case anyone needs to find the latest version...
```
curl -sL "https://releases.hashicorp.com/vault/" \
    | grep 'href="/vault' \
    | sed 's|.*<a href="/vault/\([-.0-9a-zA-Z]*\)/">.*|\1|' \
    | sort -Vr \
    | head -1
```
OR
```
curl -fsS https://api.github.com/repos/hashicorp/vault/tags \
    | jq -re '.[].name' \
    | sed 's/^v\(.*\)$/\1/g' \
    | sort -Vr \
    | head -1
```

Unfortunately, parsing out pre-releases is more work. If github releases were used you could use the releases API:
```
curl -fsS https://api.github.com/repos/hashicorp/vault/releases \
    | jq -re '.[] | select(.prerelease != true) | .tag_name' \
    | sed 's/^v\(.*\)$/\1/g' \
    | sort -V \
    | tail -1
```

**Comment by catsby** [comment]
Hello - I'm going to close this old issue for now

**Comment by kellyhair** [comment]
Would be good for consistency to have the most recent vault version available on the Checkpoint API site.
