### ISSUE TITLE
Incorrect lease duration - aws secret mount

### ISSUE THREAD

**Issue by r8474** [hashicorp/vault#27691]
**Describe the bug**
We have two AWS secret mounts - `aws-dev` and `aws-prod`. Both have the same lease config:

```
~ vault read sys/mounts/aws-dev/tune  
Key                  Value
---                  -----
default_lease_ttl    2h
description          n/a
force_no_cache       false
max_lease_ttl        1008h
```

```
~ vault read sys/mounts/aws-prod/tune 
Key                  Value
---                  -----
default_lease_ttl    2h
description          n/a
force_no_cache       false
max_lease_ttl        1008h
```

When generating credentials through these mounts using the same authentication method the TTL for `aws-prod` is not 2h as it should be:

```
~ vault read aws-dev/creds/service
Key                Value
---                -----
...
lease_duration     2h
lease_renewable    true
...
```

```
~ vault read aws-prod/creds/service
Key                Value
---                -----
...
lease_duration     5m
lease_renewable    true
...
```

**Expected behavior**
The lease duration for credentials generated through secret mounts with the same default lease TTL when using the same authentication method should be the same.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.16.1
* Vault CLI Version (retrieve with `vault version`): 1.17.1
* Server Operating System/Architecture: AL2

**Comment by stevendpclark** [comment]
Hello @r8474, 

Could you make sure the AWS secrets mount doesn't have an override for the mount's default lease TTL values using the [read lease](https://developer.hashicorp.com/vault/api-docs/secret/aws#read-lease) API?

```sh
$ vault read aws-dev/config/lease
$ vault read aws-prod/config/lease
```

**Comment by r8474** [comment]
Thank you @stevendpclark, it appears that that has been set to 5m for `aws-prod`. Is that something which should show on the Vault UI under the "leases" tab for a secret mount? If I try to view it I just get a blank page.

**Comment by stevendpclark** [comment]
Great! Glad to hear it was just a config issue. As for the leases tab that does seem like a bug in the version of Vault UI you are currently running. 

The leases tab within the AWS secrets engine UI seems to work properly on the 1.17.0 version of Vault, I believe https://github.com/hashicorp/vault/pull/26656 addressed the issue. 

With that, I'll close out this issue, please feel free to re-open if you disagree with my assessment that the issues have been resolved!
