### ISSUE TITLE
Vault PKI `pki/sign/role` seems to ignore all specified keys

### ISSUE THREAD

**Issue by simonswine** [hashicorp/vault#2770]
After upgrading to 0.7.2 (from 0.6.5). Both on clients and servers, I am no longer able to use other parameters than `csr=`. (see here)

```
vault write -format=json pki/sign/role csr=@yourdomain.csr cn=test alt_names=myname1.com ip_sans=1.2.3.4
```

The resulting certificate has the CN name of the csr (and not `test`), alt_names and ip_sans are completely ignored

With 0.6.5 I can override CNs and add alt_names and ip_sans

**Comment by jefferai** [comment]
What is your role definition?

**Comment by simonswine** [comment]
```
vault write "pki/sign/role" \
 allow_localhost=true \
 allow_any_name=true \
 allow_ip_sans=true \
 server_flag=true \
 client_flag=true \
 max_ttl="720h"
```

**Comment by jefferai** [comment]
That's not the endpoint where role definitions are saved; that's at `pki/roles/:name`.

**Comment by jefferai** [comment]
Also note that `use_csr_common_name` defaults to true, as does `use_csr_sans`. You'll want to disable those in your role definition if you want to specify names at the time of the call.

**Comment by simonswine** [comment]
Thanks I was not aware of that. With disabling use_csr_common_name and use_csr_sans, it works as it's supposed to. It would be great if this could be a bit more transparent to the user. Maybe a warning if you specify one in the case of use_* is set?
