### ISSUE TITLE
Informe de error

### ISSUE THREAD

**Issue by generalsunion** [hashicorp/vault#27707]
**Describe the bug**

**To Reproduce**
1. Run `vault write ...`
2. Run `vault login....`
3. See error

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by generalsunion** [comment]
# Paste your Vault config here.
# Be sure to scrub any sensitive values

**Comment by miagilepner** [comment]
Hi, no bug is reported here so I'm going to close this issue. Please feel free to make a new one or re-open this one if you do find a bug you'd like to report.

**Comment by generalsunion** [comment]
# Paste your Vault config here.
# Be sure to scrub any sensitive values

**Comment by generalsunion** [comment]
https://github.com/hashicorp/vault/issues/27707
