### ISSUE TITLE
ssh API endpoints - no handler for route

### ISSUE THREAD

**Issue by TEDECKERMAN** [hashicorp/vault#2774]
Will all of the ssh endpoints I'm getting a "no handler for route" response:

{"errors":["no handler for route 'ssh/keys//'"]}
{"errors":["no handler for route 'ssh/roles//'"]}

**Comment by TEDECKERMAN** [comment]
I think I have the above api issue figured out.  Another question, would each user who is requesting to have their key signed first need a role created?  The docs don't seem to go into detail on this.

**Comment by vishalnayak** [comment]
Addressed in mailing list: https://groups.google.com/forum/#!topic/vault-tool/hXOQnmfgLSw.

**Comment by shrek19937** [comment]
@sevarry. What was your original problem of no handler for route?

**Comment by v6** [comment]
// , I wrote a quick script that produces the following errors: 

```
{"errors":["existing mount at mariadb/"]}
{"errors":["no handler for route 'database/config/mariadb'"]}
```

How is it able to make a database secrets engine mount at mariadb, but not configure a database secrets engine named `mariadb`?

**Comment by shrek19937** [comment]
For my problem, it is a case of incorrectly documented end point.
