### ISSUE TITLE
make ember-dist fails

### ISSUE THREAD

**Issue by ruspaul013** [hashicorp/vault#27768]
**Describe the bug**
I tried to build latest version of `vault` but when I run `make ember-dist` I receive an error. 
```
➤ YN0007: │ core-js@npm:3.37.1 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
➤ YN0007: │ ember-a11y-refocus@npm:4.1.0 must be built because it never has been before or the last one failed
➤ YN0009: │ ember-a11y-refocus@npm:4.1.0 couldn't be built successfully (exit code 127, logs can be found here: /tmp/xfs-3ddba7ce/build.log)
➤ YN0000: └ Completed in 15s 280ms
➤ YN0000: Failed with errors in 1m 30s
make: *** [Makefile:189: install-ui-dependencies] Error 1
```
looking in the file from tmp I see 
```
[root@container-build vault-1.17.2]# cat  /tmp/xfs-bf4dd2e6/build.log
# This file contains the result of Yarn building a package (ember-a11y-refocus@npm:4.1.0)
# Script name: preinstall

command not found: npx
```
after installing npx using `npm -g install npx' I receive the following error when running again the make command
```
[root@container-build vault-1.17.2]# cat /tmp/xfs-e9c26c4f/build.log
# This file contains the result of Yarn building a package (ember-a11y-refocus@npm:4.1.0)
# Script name: preinstall

npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-07-12T07_18_22_368Z-debug.log
Install for [ 'only-allow@latest' ] failed with code 1
```

I also saw this issue on ember-a11y-refocus repo [link](https://github.com/ember-a11y/ember-a11y-refocus/issues/376). 

Changing @hashicorp/design-system-components version to 4.4.1 solved the issue for the moment.

**To Reproduce**
1. Download tar.gz archive and unarchive
2. Run `go mod tidy`
3. Run `make ember-dist`

**Expected behavior**
Running with no errors.

**Environment:**
* Server Operating System/Architecture:  AlmaLinux 8/x86_64

Thanks.

**Comment by ruspaul013** [comment]
it seems that a new version of ember-a11y-refocus appeared - https://github.com/ember-a11y/ember-a11y-refocus/releases/tag/v4.1.1

**Comment by borjaOrtizLlamas** [comment]
with this PR should be ok

**Comment by ruspaul013** [comment]
Hello @hellobontempo! 
Internally we use `make ember-dist`, but looking in the make file it seems that `static-dist` and `ember-dist` are the same [link](https://github.com/hashicorp/vault/blob/main/Makefile#L216), right?

**Comment by hellobontempo** [comment]
Thank you again for reporting this @ruspaul013 and opening the PR to fix as well. The next patch release of 1.17.x is slated for the first week of August which will include this update.
