### ISSUE TITLE
Transit Secret Backend: Encrypt with old key versions

### ISSUE THREAD

**Issue by Mehdihaitami** [hashicorp/vault#2777]
Hi,
at my company we would like to replace a custom key server by the Vault Transit Backend, mainly in order to be able to rotate and revoke keys. 
In our specific use case we would need to be able to encrypt (not only decrypt) with the old key versions after rotating these keys, while a job is re-wrapping the cipher-texts with new key version. The reason for that is that we use a pair (keyName, cipherText) for search, meaning that given an input (sensitive plain text), we derive the key name from it, we get two cipher texts (with old and new key versions) and use them to search for an entry in the DB.
I would be very grateful for any reply.

**Comment by jefferai** [comment]
How would you be searching for the entry in the DB? Are you using convergent encryption?

**Comment by Mehdihaitami** [comment]
Hi, thank you for your answer.
Yes, we would need to use convergent encryption.

**Comment by Mehdihaitami** [comment]
Great, thank you!

**Comment by jefferai** [comment]
This was added in #2821
