### ISSUE TITLE
Wrong policy reported for sealing

### ISSUE THREAD

**Issue by Flamefire** [hashicorp/vault#27814]
I wanted to test the seal/unseal process using an "admin" token derived from the initial "root" token. I.e. a policy "admin" is created and a token associated with it.

Then I want to seal the vault:
```
$ vault operator seal
Error sealing: Error making API request.

URL: PUT https://...:8200/v1/sys/seal
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

But everything should be correct:
```
$ vault token lookup | grep policies
policies            [admin default]
$ vault policy read admin | grep -FA 2 seal
path "sys/seal" {
  capabilities = ["create", "update"]
}
```

I.e. the policy contains the supposedly required permissions:
```
$ vault operator seal -output-policy
path "sys/seal" {
  capabilities = ["create", "update"]
}
```

Why am I not able to seal the vault? I don't want to have the root token easily accessible but still be able to seal the vault.

Vault Version         1.17.0

```

**Comment by jeffsanicola** [comment]
You need to add the `sudo` capability to your policy per https://developer.hashicorp.com/vault/api-docs/system/seal

**Comment by hsimon-hashicorp** [comment]
Thank you @jeffsanicola! This is correct. I'm going to go ahead and close this issue now, as we reserve GitHub issues for bug reports and enhancement requests. Please feel free to look at [our Discuss forums](https://discuss.hashicorp.com/c/vault/30); you chat with other members of our community for how-to questions and usage. Thanks!

**Comment by Flamefire** [comment]
@hsimon-hashicorp If it is correct that "sudo" is required then this is a bug as reported: The policy printed by vault is (at least) incomplete. I suppose only "sudo" should be there, shouldn't it?
