### ISSUE TITLE
Provide clear guidance in the docs for redirect_addr with Consul service discovery

### ISSUE THREAD

**Issue by slackpad** [hashicorp/vault#2783]
Users are sometimes trying to configure their `redirect_addr` to "vault.service.consul", which causes redirect loops (see https://github.com/hashicorp/consul/issues/2795). We are putting a fix in Consul to avoid the loop, but the documentation should be clear for what users should do when they are using Consul service discovery. Do they need to set `redirect_addr` at all?

**Comment by jefferai** [comment]
It's documented quite extensively, with examples: https://www.vaultproject.io/docs/concepts/ha.html

**Comment by slackpad** [comment]
It's clear what to do with a load balancer or no load balancer but not
super clear what to do with consul specifically.

**Comment by slackpad** [comment]
Could we add a consul specific example to that page? I'd write it but I'm not totally sure what what we should set. I think ideally for the consul case we wouldn't set this at all and have the service address left empty when vault registers but I think that requires you to be using internal request forwarding.

**Comment by jefferai** [comment]
We can't because there's nothing specific to Consul.

That said, we already attempt to discover the address that should be used for Consul, by querying Consul for it. But that doesn't always work, in which case they need to override it manually.

**Comment by jefferai** [comment]
Or rather, what might be specific to Consul would be using Consul node names instead of DNS names, but I don't see why you'd want to do this anyways.

**Comment by slackpad** [comment]
> That said, we already attempt to discover the address that should be used for Consul, by querying Consul for it. But that doesn't always work, in which case they need to override it manually.

For that case can you not supply `redirect_addr` at all? It looks like it's required from the docs.

**Comment by jefferai** [comment]
It's required if Vault can't discover it on its own.

**Comment by sakateka** [comment]
Hi!
It seems to me that here https://www.vaultproject.io/docs/configuration/storage/consul.html#redirect_addr (and for all  #redirect_addr sections) need а link to this one  https://www.vaultproject.io/docs/concepts/ha.html#client-redirection
Аnd it will be clear for readers

**Comment by weaseal** [comment]
Documentation for `redirect_addr` seems to have been removed from @jefferai 's link to HA documentation above.  @jefferai please update this ticket as it is the top hit on Google for `vault redirect_addr` and the answer is now clear as mud...

**Comment by mafrosis** [comment]
The `redirect_addr` option doesn't exist. It's now an overload of the `api_addr` option:

https://www.vaultproject.io/docs/configuration/index.html#api_addr

> Specifies the address (full URL) to advertise to other Vault servers in the cluster for client redirection

**Comment by scaarup** [comment]
If I set "api_addr" - consul is serving a CNAME when dns-query'ing for my vault service. Not really what I want. On the other hand - if I don't specify "api_addr", vault will sometimes redirect to an IP-address URL, which will cause certificate-trust errors with clients...

**Comment by jefferai** [comment]
You should always set `api_addr` for that exact reason -- the self-discovery may not get it right.

I think Consul returning CNAME is normal Consul behavior? You'd have to talk to Consul about that one.

**Comment by scaarup** [comment]
Okay, but if I set api_addr, a standby vault will always respond with 307, forcing the client to make a new http request. During load testing I have found this as a major performance penalty. 

If I don’t set api_addr and query a standby vault, it will internally query the active. Which is much faster. Can I force this behavior?

**Comment by jefferai** [comment]
Standby Vaults do request forwarding (https://www.vaultproject.io/docs/concepts/ha.html#request-forwarding), 307 is only a fallback if your cluster isn't setup right.

**Comment by scaarup** [comment]
Aha I see. So if I set api_addr, my cluster becomes incorrectly setup :). It certainly triggers the redirecting - but I guess it must be a combination of things ...

**Comment by scaarup** [comment]
I have captured the error now:

`Oct 10 20:43:49 ssp-vault102 vault[96504]: 2018-10-10T20:43:49.441+0200 [ERROR] core: error during forwarded RPC request: error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing x509: certificate is valid for ssp-vault100.dibs.network, ssp-vault101.dibs.network, ssp-vault102.dibs.network, ssp-vault103.dibs.network, vault.service.hel.consul, not fw-4318af7c-336d-02d2-91a6-feec37e85e4f""`

Wondering what fw-4318af7c-336d-02d2-91a6-feec37e85e4f is and where it's coming from. Active's: api_addr = "https://ssp-vault102.dibs.network:8200"

**Comment by maxb** [comment]
@pascalrobert I agree, but you'd have more chance of triggering a useful reaction if you open a new issue, rather than tagging on to the end of a closed one.
