### ISSUE TITLE
Enhanced policy path pattern matching

### ISSUE THREAD

**Issue by bernielomax** [hashicorp/vault#2784]
It would be great if you could have a more powerful pattern matcher for the policy path. Even allowing multiple wildcards would be great improvement. Especially if you want to allow for a common pattern across multiple mounts. I.e.

mount1/test/password
mount2/test/password
mount2/prod/password

It would be great if you could allow test users "\*/test/\*"

Obviously using a pattern matcher like regex would be way more powerful.

**Comment by jefferai** [comment]
This is something that may come eventually but is not currently on our roadmap.
