### ISSUE TITLE
Vault randomly becomes unresponsive

### ISSUE THREAD

**Issue by ryanshelc** [hashicorp/vault#2786]
After upgrading to the latest version of Vault I started noticing that incoming requests (via CLI and API) will randomly start to hang.  When it's not responding and I try to run 'vault policies' via the CLI, it eventually times out with the following error.

net/http: request canceled (Client.Timeout exceeded while awaiting headers)

I have TRACE turned on in consul and vault and the only thing that gets logged from a standby after running the 'vault policies' command is:

2017/05/31 10:55:09.776509 [ERROR] http/handleRequestForwarding: error forwarding request: error=read tcp <internal.ip>:50264-><internal.ip>:8201: read: connection timed out

I have 4 Vault servers all on the same subnet with consul as the backend. Even when Vault is in the hung state, I can use nc and connect to 8201 via UDP to the active node, so it's not a firewall issue or port blocking and everything works a majority of the time. Below is the configuration and output from when Vault starts.

This isn't production yet, so there is barley any traffic, so it's not a load issue. 

==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://192.168.1.1:8201
              Listener 1: tcp (addr: "192.168.1.1:443", cluster address: "192.168.1.1:8201", tls: "enabled")
               Log Level: trace
                   Mlock: supported: true, enabled: true
        Redirect Address: https://<dns.roundrobin.vault.name>:443
                 Storage: consul (HA available)
                 Version: Vault v0.7.2
             Version Sha: d28dd5a018294562dbc9a18c95554d52b5d12390

==> Vault server started! Log data will stream in below:

2017/05/31 14:16:01.817649 [DEBUG] physical/consul: config path set: path=vault/
2017/05/31 14:16:01.817687 [DEBUG] physical/consul: config disable_registration set: disable_registration=false
2017/05/31 14:16:01.817694 [DEBUG] physical/consul: config service set: service=vault
2017/05/31 14:16:01.817698 [DEBUG] physical/consul: config service_tags set: service_tags=
2017/05/31 14:16:01.817709 [DEBUG] physical/consul: config address set: address=<internal.domain.name>:8080
2017/05/31 14:16:01.817712 [DEBUG] physical/consul: config scheme set: scheme=https
2017/05/31 14:16:01.818336 [DEBUG] physical/consul: configured TLS
2017/05/31 14:16:01.818366 [TRACE] physical/cache: creating LRU cache: size=32768
2017/05/31 14:16:01.823667 [TRACE] cluster listener addresses synthesized: cluster_addresses=[192.168.1.1:8201]

storage "consul" {
  scheme = "https"
  tls_ca_file = "path_to_cert/cert.crt"
  tls_cert_file = "path_to_cert/cert.crt"
  tls_key_file = "path_to_key/key.key"
  address = "<internal_server.domain.name>:8080"
  redirect_addr = "https://<dns.roundrobin.vault.name>:443"
  cluster_addr = "https://192.168.1.1:8201"
  tls_min_version = "tls12"
}

listener "tcp" {
  tls_cert_file = "path_to_different_cert/dns.roundrobin.vault.name.crt"
  tls_key_file = "path_to_different_key/dns.roundrobin.vault.name.key"
  address = "192.168.1.1:443"
  cluster_address = "192.168.1.1:8201"
  tls_min_version = "tls12"
}

**Comment by jefferai** [comment]
> Even when Vault is in the hung state, I can use nc and connect to 8201 via UDP to the active node

Vault doesn't use UDP so this isn't really a useful test.

Can you post more detailed logs of when this is actually happening? It seems like either the active node is blocked for some reason, or the network connection between the active and standby node is interrupted.

**Comment by jefferai** [comment]
Closing due to lack of response.
