### ISSUE TITLE
Getting vault to connect to the new consul master

### ISSUE THREAD

**Issue by osadalakmal** [hashicorp/vault#2787]
When the consul server node a vault cluster is connected to dies, is there a way to get the vault cluster to connect to the newly elected master of the consul cluster? As of now, there doesnt seem to be a way.

**Comment by jefferai** [comment]
The best way to do this (and the best way overall to use Vault with Consul) is to have Vault connect to a machine's local Consul agent. Then this happens automatically. It's also the only way for automatic health checks to work reliably.

**Comment by osadalakmal** [comment]
Thanks!
