### ISSUE TITLE
Vault cli: No route for DELETE identity/oidc/role

### ISSUE THREAD

**Issue by gummigudm** [hashicorp/vault#27890]
When trying to use the cli to delete a role i get the error described below.
Using curl against the api works without issue. Seems to be a cli mapping that is needed.

```
vault delete indentity/oidc/role/myrole
Error deleting indentity/oidc/role/myrole: Error making API request.

URL: DELETE https://127.0.0.1:8200/v1/indentity/oidc/role/myrole
Code: 404. Errors:

* no handler for route "indentity/oidc/role/myrole". route entry not found.
```

**To Reproduce**
1. Create a key `vault write identity/oidc/key/mykey rotation_period="24h" verification_ttl="24h" allowed_client_ids="*"`
2. Create a role `vault write identity/oidc/role/myrole key="mykey" ttl="24h"`
3. Try to delete the role `vault delete indentity/oidc/role/myrole`

**Expected behavior**
The role to be successfully removed.

**Environment:**
* Vault Server Version: 1.17.2
* Vault CLI Version: 1.17.2
* Server Operating System/Architecture: Running in Docker on MacOS arm

**Comment by hsimon-hashicorp** [comment]
Hi there - it looks like there's a discrepancy between your create and your delete commands, specifically the **indentity** in the name. Can you clarify your repro steps for us? Thanks in advance!

**Comment by gummigudm** [comment]
Hi, thank you for your quick reply 😄 
I was following this doc: [Tokens](https://developer.hashicorp.com/vault/api-docs/secret/identity/tokens), to create an oidc role for identity token generation. 

But using the cli instead of curling the api.
As per doc, i created a named key `vault write identity/oidc/key/mykey`.  
I then created a role `vault write identity/oidc/role/myrole`  
I then tried to delete the role i just created `vault delete identity/oidc/role/myrole`  
That caused the `* no handler for route "indentity/oidc/role/myrole"` error.

Seeing the error it gave was `no handler`, I figured the DELETE handler in the cli for identity/oidc/role might be broken. Tried DELETE through curl, and i successfully deleted the role. So the error speaks for itself, the cli has no handler to handle the DELETE operation on the `indentity/oidc/role` path.

This operation does not seem to have a corresponding gui, and these keys and roles that pertain to the identity tokens cannot be viewed and edited in the web interface. I don't know if this feature is still experimental. Using the API, all calls i tried succeeded though, so I have my use case working. Just wanted to let you know that the cli was giving errors.

If you cannot reproduce the issue, i will gladly investigate further, to see if the issue might be on my end.

**Comment by hsimon-hashicorp** [comment]
I apologize if I wasn't clear - in one part of your issue report, **identity** is used and in your delete, **indentity** (sic) is used. Does the behavior still happen when the path name does not have a typo in it? Thanks!

**Comment by gummigudm** [comment]
You know what, I have read this over 10 times and have up to this point failed to see what discrepancy you were talking about. Grade-A "lysdexia" at its finest🙂
I have verified that the command indeed works when you pass it the correct path hehe.

Lets close this one, error was most definitely on my end. Thank you!

**Comment by hsimon-hashicorp** [comment]
Awesome! Thanks for responding so quickly. :) Glad you got it working!
