### ISSUE TITLE
Proposal: Server-side secrets generation

### ISSUE THREAD

**Issue by joshlf** [hashicorp/vault#2792]
# Motivating Example

This proposal is best motivated with an example. I work on a service that performs automatic code analysis. In order to do this, it needs access to an SSH key that it can use to authenticate to our Git servers and pull Git repositories.

When this key needs to be created or updated, we face a problem. Right now, a developer has to generate a new SSH key pair, store the key in Vault, and configure the Git servers with the public key so that they will know to allow requests from that key pair.

This approach has one critical drawback: it relies on the developer - using the developer's machine - to generate and upload the key. If the developer's machine is compromised, the key can be stolen. If the developer makes a mistake in generating the key, it could be generated with insecure parameters. The developer could also accidentally upload the wrong file, or make any number of other mistakes in a manual process.

# The Proposal

**NOTE**: Let me say right off the bat that this is not a precise proposal, but rather a general idea whose details ought to be hammered out in discussion. I'm very open to suggestions for how things out to be done differently.

The proposal is to give Vault the ability to generate secrets, store them in the generic backend, and then expose some part of that secret to the caller. For example, it might support generating the following types of secrets:

| Secret Type              | Component Returned to Caller |
| -------------------- | ------------------------------ |
| SSH key                    | public key                                   |
| random byte string  | entire byte string                        |

With respect to the permissions model, the operation would be considered a [create](https://www.vaultproject.io/docs/concepts/policies.html#create) or [update](https://www.vaultproject.io/docs/concepts/policies.html#update) as depending on whether an existing secret was getting over written. In other words, the permissions model would be the same as it would be if the secret were provided by the user like it is done today.

## Extras

The following features could be supported as well:

* The client might want to override the default choice of what is returned. They might want the private component of a key pair returned as well as the public component. They might want nothing returned at all.
* Instead of having the data returned in plaintext, the client could submit a public key (e.g., PGP) for it to be encrypted with. This would allow a low-trust service or a developer on their machine to generate a high-sensitivity secret and place it on a production box with the credentials necessary to decrypt the ciphertext without the low-trust service or developer's machine being exposed to the high-sensitivity secret.
* Combined with the previous feature, it might not even be necessary for Vault to store the secret. Vault might be capable of operating in a generate-only mode, acting as a secret generation oracle.

---

Inspiration for this idea came from @lziest.

**Comment by meirish** [comment]
Thanks for filing! I don't think this is something we'll get to soon, but Vault now has a plugin system so you could develop it externally. Let us know if you do!  Here's more on the Plugin System: https://www.vaultproject.io/docs/internals/plugins.html
