### ISSUE TITLE
is PUT idempotent?

### ISSUE THREAD

**Issue by connaryscott** [hashicorp/vault#2799]
I was wondering about PUT vs POST regarding my attempt to switch  a role's authentication strategy from bound_account_id to bound_iam_role_arn using the following rest call:

```
 curl -X PUT -H "X-vault-token: ${VAULT_ROOT_TOKEN}" -d "{\"policies\":\"base,mypolicy\", \"bound_iam_role_arn\": \"arn:aws:iam::0123456789:role/myrole\"}" "${VAULT_ENDPOINT}/v1/auth/aws-ec2/role/myrole"
```

I was using POST earlier but did not get the result I hoped.  After using PUT, the same result occurred.

After executing this, I found that both bound_iam_role_arn and bound_account_id  were set. 

I was hoping that only bound_iam_role_arn would be set as thsi shows

```
[centos@ip-10-147-148-102 ~]$ vault read  /auth/aws-ec2/role/myrole
Key                           	Value
---                           	-----
allow_instance_migration      	false
bound_account_id              	0123456789
bound_ami_id                  	
bound_iam_instance_profile_arn	
bound_iam_role_arn            	arn:aws:iam::0123456789:role/myrole
disallow_reauthentication     	false
max_ttl                       	0
policies                      	[base default mypolicy]
role_tag                      	
ttl                           	0
```

I can use DELETE and then POST/PUT but was hoping there might be  a way to do this in one call? 

Thanks

Chuck

**Comment by jefferai** [comment]
Vault treats PUT/POST as the same. In the docs for this endpoint (https://www.vaultproject.io/api/secret/aws/index.html#create-update-role) you'll see that it does use an update methodology for this endpoint. You can either delete the role and recreate, or simply set the parameter you want to clear out to an empty string.
