### ISSUE TITLE
UI: Stretch text field to fit content in JSON editor

### ISSUE THREAD

**Issue by karabanov** [hashicorp/vault#28053]
**Is your feature request related to a problem? Please describe.**
Sometimes a large number of nested variables are kept secret, but you can only view/edit such variables by switching to JSON editing mode.
Such nested variables are difficult to find on the page and we have to resort to the browser's "search on page" tool.

In JSON mode, the text field is very small and if you try to find the desired variable using the browser's "search in page" tool (`Ctrl+f`), nothing will work if it is outside the text field, since it does not yet exist for the browser, it is not rendered.

To find the desired variable, you have to scroll the contents of the text field a little and press the `F3` key to repeat the search - and so on until the desired variable is highlighted by the browser.

Also, the keys are sorted in an unnatural order (this is normal, expected and does not raise questions), so it is very difficult to search for the desired variable by eye, and searching on the page is the most reliable option to find the desired variable.

**Describe the solution you'd like**
In my opinion, it will be convenient if at the moment of switching to the JSON mode the text field is stretched to the size of the content - it is more convenient to scroll the entire page than to scroll the text in a small text field, in addition, the "search on page" (`Ctrl+f`) will work correctly

**Describe alternatives you've considered**
Maybe you can make it so that the content is rendered outside the small text box, then "search on page" (`Ctrl+f`)  will also work, and when you press `F3` and the scrolling of the page is done automatically

**Explain any additional use-cases**
Due to the fact that the text has to be scrolled and the search repeated, you can accidentally scroll more than necessary and miss the variable you are looking for. I encountered this several times and had to repeat everything from the beginning, but scroll very slowly, literally one line at a time, so as not to make a mistake and be sure that the required variable will be found or make sure that it is missing.

**Additional context**
In this video I keep pressing `F3` and scrolling the contents of a small text field back and forth. You can see that only when I scroll to the desired variable does the browser see it and highlight it, but if I scroll further the browser doesn't see it again.

[test_find_scroll.webm](https://github.com/user-attachments/assets/9b28751e-d054-47e4-8eec-446618baf71d)

**Comment by dvk1302dvk** [comment]
Hi, I have the same  issue. Thank you Bro for opening it. I home it will resolve in near time.
