### ISSUE TITLE
Proposal: CLI verbose mode with restAPI URLs

### ISSUE THREAD

**Issue by geek65535** [hashicorp/vault#2816]
Certain invalid operations provide the actual URL that was called. 
```
root@kms-vault01:~# vault mount garbage
Mount error: Error making API request.

URL: POST https://kms-vault01.dev.example.com:8200/v1/sys/mounts/garbage
Code: 400. Errors:

* unknown backend type: garbage
```

It would be extremely helpful if the cli had a verbose/learning/showme mode in which the entire API call (URL, GET/POST/PUT/DELETE, headers, payload) would be returned for any operation, not just certain invalid ones. Spitting it out in the form of a curl command or similar would be very useful.

```
root@kms-vault01:~# vault --verbose read secret/pma
Key                     Value
---                     -----
refresh_interval        768h0m0s
this                    that
who                     me

API call:
curl --header "X-Vault-Token: 7cbf1019-7743-8034-7db7-1ae508c8eccf" --request GET --data '' https://kms-vault01.dev.example.com:8200/v1/secret/pma
```

**Comment by geek65535** [comment]
I was thinking something like this. I haven't tested it, as I'm having trouble compiling vault.
It would need a check for a 'verbose' (or similar) flag.
api/response.go
31,36c31
<     var outBody bytes.Buffer
<     outBody.WriteString(fmt.Sprintf(
<       "API request:\n\n"+
<         "URL: %s %s\n",
<       r.Request.Method, r.Request.URL.String()))
<     return fmt.Errorf(outBody.String())
---
>               return nil

**Comment by geek65535** [comment]
ping?

**Comment by jefferai** [comment]
pong!

**Comment by rezahashemi** [comment]
ping?

**Comment by jefferai** [comment]
pong!

**Comment by chrishoffman** [comment]
I am going to close this since this is something that is unlikely to be pursued.  Vault users work in many different environments and use different tools for interacting with the API.  Additionally, some CLI calls perform multiple calls under the hood.  I don't think there is any generic way we can handle this that will satisfy all use cases.

**Comment by reza** [comment]
@chrishoffman It is not that much complicated, a verbose or debug mode, or a log file of all the requests sent to server will be helpful. I have faced with cases where vault cli works but a well crafted API call directly (using postman, curl, etc) does not work and you wonder what else has been sent.

**Comment by geek65535** [comment]
@chrishoffman 
When you say that people use different tools for interacting, it sounds like you are nixing the idea of spitting out a curl command. I suggested curl because it is most commonly used in examples for APIs, including in HashiCorp docs.
And if a CLI command generates multiple calls, then couldn't all those calls be shown?

The whole point of this is to give users an easy way to see how to go from CLI to API. Or if a user is already using the API, then they can do something new in the CLI (or even the GUI, perhaps), and the system would show them the underlying API calls.
It seems like it would be fairly easy to implement. Any time an API call is performed, if the verbose flag is present, also print the parameters and data from the API call.

I am joining the Vault support team. I will try to implement this myself as a side project as part of learning Vault more deeply. Would you please reopen this so I have a place to track my progress with it?

**Comment by krish7919** [comment]
This would have been extremely useful to translate the CLI to API calls, or to debug CLI commands.

**Comment by ncabatoff** [comment]
See #2173.

**Comment by abh** [comment]
See https://github.com/hashicorp/vault/pull/6113 (tl;dr: `vault write -output-curl-string ...` will show a curl command to do the request instead of doing the request).

**Comment by abdennour** [comment]
@abh  Thanks so much! that work 

i.e.
```sh
vault kv get  -output-curl-string -field=PROMETHEUS_API_TOKEN secret/k8s/cluster002/monitoring

curl -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" http://localhost:8200/v1/secret/data/k8s/cluster002/monitoring
```
