### ISSUE TITLE
Docker Hub 1.17 tag has not been updated

### ISSUE THREAD

**Issue by PMExtra** [hashicorp/vault#28188]
https://hub.docker.com/r/hashicorp/vault/tags

![image](https://github.com/user-attachments/assets/a91fd45f-9dfc-4aef-849a-093ca0e7e78c)

`hashicorp/vault:1.17` still points to `1.17.1`, I think it should be updated to the latest `1.17.x` (`1.17.3` for now).

As a control, `1.16` points to `1.16.3` as expected.

![image](https://github.com/user-attachments/assets/9f3b81ff-f076-442d-addb-94a9e3f51893)

**Comment by heatherezell** [comment]
Thanks for the report! This has now been corrected and the release process has been verified so it shouldn't happen again. Please feel free to open a new issue if needed. Thanks again!
