### ISSUE TITLE
How to add new nodes existing vault cluster

### ISSUE THREAD

**Issue by Rameshera** [hashicorp/vault#2818]
Hello,
Currenly i am having 3 nodes in the vault and consul cluster. i want to add 3 more nodes in the vault cluster but root certificates contain only old servers. Can I add new servers in to vault cluster without any down time 
Appreciate your help!!!
Thanks,
Ramesh

**Comment by jefferai** [comment]
You can add new nodes to a Vault cluster at any time. I'd add the new nodes with the new root certs, have one of them take over active status, then fix up the existing ones.

**Comment by Rameshera** [comment]
Thank you Jeff for your quick response.
Can you please share any document how to do proceed with it.

Thanks,
Ramesh

**Comment by sasiarivukalanjiam** [comment]
@jefferai if you could share how its done it would be much helpful

**Comment by jefferai** [comment]
See https://www.vaultproject.io/guides/upgrading/index.html for instructions.
