### ISSUE TITLE
Database backend: MySQL credential lease duration being overruled?

### ISSUE THREAD

**Issue by rjbez17** [hashicorp/vault#2822]
We are using the new Database backend with version version 0.7.2 (although we were originally running 0.6.5). We've created a role with a `default_ttl` of 11h. Getting the role shows the duration to be 11h, however, when we request credentials we always get 10h TTLs. If we set the `default_ttl` to anything under 10h it works as expected. 

```
curl --header "X-Vault-Token:***" http://vault:8200/v1/database/roles/mydb_readwrite

{
    "auth": null,
    "data": {
        "creation_statements": "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, CREATE TEMPORARY TABLES, ALTER, CREATE VIEW, SHOW VIEW ON *.* TO '{{name}}'@'%' IDENTIFIED BY '{{password}}'",
        "db_name": "mydb",
        "default_ttl": 39600,
        "max_ttl": 31536000,
        "renew_statements": "",
        "revocation_statements": "REVOKE SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, CREATE TEMPORARY TABLES, ALTER, CREATE VIEW, SHOW VIEW ON *.* FROM '{{name}}'@'%'",
        "rollback_statements": ""
    },
    "lease_duration": 0,
    "lease_id": "",
    "renewable": false,
    "request_id": "c74873df-072c-a83b-4d7d-644bea617ae3",
    "warnings": null,
    "wrap_info": null
}


curl --header "X-Vault-Token:***" http://vault:8200/v1/database/creds/mydb_readwrite


{
    "auth": null,
    "data": {
        "password": "******",
        "username": "******"
    },
    "lease_duration": 36000,
    "lease_id": "database/creds/mydb_readwrite/e94a1bd7-1b80-35e6-cf5e-08c9ee501619",
    "renewable": true,
    "request_id": "2ccf377e-7956-95a5-97b5-ba54111e4df4",
    "warnings": null,
    "wrap_info": null
}
```

Is there a hidden setting somewhere that is overriding our TTLs?

We are using etcd as our store.

**Comment by jefferai** [comment]
What's the output of `vault mounts`?

**Comment by briankassouf** [comment]
Hi @rjbez17,

Both the vault config file as well as the default output of `vault mounts` have the ability to overwrite the default ttl, are either of these being set?

**Comment by rjbez17** [comment]
Welp, looks like someone did add that to the dockerfile. Cheers!

**Comment by jefferai** [comment]
:-D

**Comment by rjbez17** [comment]
Also, the documentation is incorrect. The `max_ttl` docs say it defaults to, not is overruled by:

```max_ttl (string/int: 0) - Specifies the maximum TTL for the leases associated with this role. Accepts time suffixed strings ("1h") or an integer number of seconds. Defaults to system/backend default TTL time.```

**Comment by jefferai** [comment]
They're both correct and not correct. See https://www.vaultproject.io/docs/concepts/tokens.html#token-time-to-live-periodic-tokens-and-explicit-max-ttls for the full scoop.
