### ISSUE TITLE
dev server fails to start when hostname has a space (macos)

### ISSUE THREAD

**Issue by ewan-chalmers** [hashicorp/vault#28388]
**Describe the bug**
Starting vault server on macos in dev mode fails where Mac hostname has a space in it.

**To Reproduce**
1. Install vault on macos with brew per 
2. Run `vault server -dev`
3. Run `vault server -dev -dev-listen-address=127.0.0.1:8200`
3. Run `VAULT_API_ADDR=http://127.0.0.1:8200  vault server -dev`

In all cases, the error below is displayed and the server does not start:
```
Error initializing core: parse "vault://MyName's MacBook Pro 2021": invalid character " " in host name
```

**Expected behavior**
Server starts in dev mode, listening on localhost:8200

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`): Vault v1.17.5 (4d0c53e84094b8017d32b6e5b7f8142035c8837f), built 2024-08-30T15:54:57Z
* Server Operating System/Architecture: macos

Vault server configuration file(s):

N/A

**Additional context**

**Comment by heatherezell** [comment]
Vault will expect to be able to use a DNS RFC-compliant hostname for its startup and communication. I would recommend considering using dashes in your hostname instead of spaces. See the RFC document for more information.
https://www.rfc-editor.org/rfc/rfc952
 I'm going to go ahead and close this issue now, but please feel free to open a new one if you need. Thanks!

**Comment by ewan-chalmers** [comment]
This is a vexing one for dev mode. Doesn't it impact loads of dev mode users?

MacOS sets `<name>'s MacBook` as hostname

**Comment by ewan-chalmers** [comment]
What worked for me is to set hostname via terminal (not in Settings app) specifically like this:

```
scutil --set HostName <name-without-spaces>
```

This updates what is returned by the `hostname` command.

Changing the name in the Settings app changes what is reported by
- `scutil --get ComputerName`
- `scutil --get LocalHostName`

... but not by
- `scutil --get HostName`
- `hostname` command

After applying this change, I am able to start the vault server in dev mode
