### ISSUE TITLE
Unable to enable auth backend

### ISSUE THREAD

**Issue by pivotalphoenix** [hashicorp/vault#2843]
`vault auth-enable userpass` throws error `Error: Post https://127.0.0.1:8200/v1/sys/auth/userpass: http: server gave HTTP response to HTTPS client`.

I am using `vault server -dev` to start server

Any idea ? Please help.

**Comment by joelthompson** [comment]
Hi @pivotalphoenix -- you need to run `export VAULT_ADDR='http://127.0.0.1:8200'` before `vault auth-enable userpass`

Vault server in dev mode runs over HTTP (because there's no TLS certs), while the vault client defaults to HTTPS for security, hence the error you're seeing.

**Comment by kanian** [comment]
Also, "export VAULT_ADDR='http://127.0.0.1:8200'" does not permanently save the VAULT_ADDR variable. From another shell, for example,  it will not be set.

**Comment by jefferai** [comment]
You can set it in that shell, or use a .profile or similar to set it across shells automatically.
