### ISSUE TITLE
`-output-policy` does not work for audit command

### ISSUE THREAD

**Issue by Flamefire** [hashicorp/vault#28440]
**Describe the bug**

For `vault audit` it is not possible to output the required policy

**To Reproduce**

```
$ vault audit -output-policy enable file file_path=/var/log/audit.log
Usage: vault audit <subcommand> [options] [args]
<...>
Unable to generate policy from command

$ vault audit enable file file_path=/var/log/audit.log -output-policy
Failed to parse K=V data: invalid key/value pair "-output-policy": format must be key=value
Unable to generate policy from command

$ vault audit enable file file_path=/var/log/audit.log -output-policy=1
Error enabling audit device: Error making API request.

URL: PUT <...>
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.17.0
* Vault CLI Version (retrieve with `vault version`): 1.17.5
* Server Operating System/Architecture: Linux

**Comment by heatherezell** [comment]
Hi there! We are aware of some usage limitations around the CLI, as you've run into here. Vault is pretty specific about what order the flags need to be in. If you try using `-output-policy` immediately after the `enable`, it should work for you:
`vault audit enable -output-policy file `
I'll go ahead and close this issue now, but please feel free to re-open it if you're still having problems. Thanks!
