### ISSUE TITLE
failed to revoke lease errors for PKI backend

### ISSUE THREAD

**Issue by shayangz** [hashicorp/vault#2844]
We are seeing a large number of these errors in our logs

```
Jun 11 23:27:55 vault-i-0e31568b75a36d336 vault[27029]: 2017/06/11 23:27:55.146126 [ERROR] expire: failed to revoke lease: lease_id=auth/aws/login/f43d8e9641a32363b1f945229f570d289639b9b9 error=failed to revoke token: failed to revoke entry: failed to revoke 'pki/issue/role/052c77f9-364d-3818-fc57-bf1de10c6d00' (1 / 3454): failed to revoke entry: resp:(*logical.Response)(nil) err:Error encountered during CRL building: Error storing CRL: Unexpected response code: 413 (Value exceeds 524288 byte limit)
```

It was happening on `0.7.2` and it's still happening on `0.7.3` after upgrade. We are running with a Consul backend (version `0.8.3`). 

As the log suggests, the certificates were issued using a token generate from `aws auth` using the iam auth method.

any ideas on what's causing these errors?

**Comment by vishalnayak** [comment]
@shayangz It looks like the CRL grew big enough to exceed the k/v size limitations on Consul (512 KB). Trying to reduce the size of the CRL is one way to go about it (https://www.vaultproject.io/docs/secrets/pki/index.html#keep-certificate-lifetimes-short-for-crl-39-s-sake).

**Comment by vishalnayak** [comment]
@shayangz There is an endpoint to cleanup expired certificates from the CRL (https://www.vaultproject.io/api/secret/pki/index.html#tidy). You might also want to look at `no_store` option on the role to reduce the storage burden (https://www.vaultproject.io/api/secret/pki/index.html#create-update-role).

**Comment by shayangz** [comment]
Thanks. Will try these recommendations.
