### ISSUE TITLE
Google Cloud Audit Logging audit backend

### ISSUE THREAD

**Issue by mayakacz** [hashicorp/vault#2848]
Hi all,
Is there interest for a new audit backend to easily consume Vault logs into Google Cloud Platform's Cloud Audit Logging.
This could be something like ingesting a file audit backend (https://www.vaultproject.io/docs/audit/file.html) from Vault into Google Cloud Audit Logging (https://cloud.google.com/logging/docs/audit/) by writing  (https://cloud.google.com/logging/docs/api/tasks/creating-logs#writing_log_entries).

@emilymye and I work for Google and we're trying to get a better idea of the demand of this FR, so please thumbs up if this is something you're interested in.

**Comment by jefferai** [comment]
Please do *not* add +1 or thumbs ups to this issue. It has no effect on roadmap and simply creates notification noise. Thank you.
