### ISSUE TITLE
Vault Signed SSH certificates integrate with PKI(certificates)

### ISSUE THREAD

**Issue by MorganReid** [hashicorp/vault#28485]
According to the [document](https://developer.hashicorp.com/vault/docs/secrets/ssh/signed-ssh-certificates), the Client key signing was implemented.
The step of configuring CA uses v`ault writes ssh-client-signer/config/ca generate_signing_key=true.`
For the final certificate, use `ssh-keygen -Lf `to view the message information and find that the `Signing CA` in it should be generated by itself.
![image](https://github.com/user-attachments/assets/d3af1472-d719-4213-9fd1-2c4d947a6171)

I want to know how to obtain the `Signing CA` certificate information?
Vault also has PKI (certificates) function. Can the CA configured here be used as SSH CA? 
Are the two related? Can they be integrated?

**Comment by heatherezell** [comment]
We ask that questions and discussions about using Vault be handled over on our [Vault Discuss forum](https://discuss.hashicorp.com/c/vault/30). GitHub is more for bug reports and enhancement requests, which this doesn't appear to be. I'll go ahead and close this issue now, but please feel to open a new one if you need for any bugs you may encounter. Thanks!
