### ISSUE TITLE
Community Vault image on Google Compute Engine

### ISSUE THREAD

**Issue by mayakacz** [hashicorp/vault#2849]
Hi all,
Is there interest in offering a community-supported image on Google Compute Engine (https://cloud.google.com/compute/docs/images#community_supported_images) with the latest release of Vault, for easy deployment and patching.

@emilymye and I work for Google and we're trying to get a better idea of the demand of this FR, so please thumbs up if this is something you'd be interested in.

**Comment by jefferai** [comment]
Please do *not* add +1 or thumbs ups to this issue. It has no effect on roadmap and simply creates notification noise. Thank you.

**Comment by jefferai** [comment]
Sorry Maya, going to close this at this point!
