### ISSUE TITLE
Script to convert etcd storage data from api v2 to api v3

### ISSUE THREAD

**Issue by trunet** [hashicorp/vault#2862]
I don't know how do you want to document this, but here's a quick and dirty script to convert the data from etcd api v2 to v3. etcdctl migrate doesn't work as etcd2 is base64 encoded and the keys have a point on the filename.

    #!/bin/bash
    PREFIX="/vault"
    for KEY in $(etcdctl ls ${PREFIX} -recursive -p)
    do
         if ! [[ "${KEY}" == */ ]]
         then
                 # key on etcd2 is base64 encoded and has a point on the "filename"
                 NEW_KEY=$(echo ${KEY} | sed 's/\/\./\//')
                 etcdctl get ${KEY} | base64 --decode | ETCDCTL_API=3 etcdctl put ${NEW_KEY}
         fi
    done

**Comment by jefferai** [comment]
@trunet I'm going to close this so as to not just have this sitting open, but feel free to send a PR against the etcdv3 docs for users to reference.
