### ISSUE TITLE
Consul location on command line

### ISSUE THREAD

**Issue by jhmartin** [hashicorp/vault#2868]
Consider adding a flag to set the consul address on the command line, to allow setting arbitrary DNS names (potentially sourced from an environmental variable) without having to rewrite a configuration file. This might apply for example where I want to deploy vault to two different locations, and Consul is accessible via different ELBs. Since ELBs have dynamic IPs it is not sufficient to use Docker's --add-host option.

**Comment by jefferai** [comment]
Hi @jhmartin ,

If you leave the address in the config file blank you should be able to set it via the normal CONSUL_HTTP_ADDR environment variable.

**Comment by jhmartin** [comment]
Ah. Should that be added to https://www.vaultproject.io/docs/commands/environment.html then?

**Comment by jefferai** [comment]
Probably not specifically, although it probably wouldn't hurt to add a note that the backend will respect Consul env vars if not set in the config file.
