### ISSUE TITLE
VAULT_CA_CERT documentation error

### ISSUE THREAD

**Issue by evdtempel** [hashicorp/vault#28725]
The documentation incorrectly specifies `VAULT_CA_CERT` can be used as an ENV-var to configure a specific CA, in two documentation files: 
- https://github.com/hashicorp/vault/blob/f2041b00e52e4503ed9f23a65142154b6c841ae3/website/content/partials/cli/standard-settings/both/ca-cert.mdx#L3
- https://github.com/hashicorp/vault/blob/f2041b00e52e4503ed9f23a65142154b6c841ae3/website/content/partials/cli/standard-settings/both/ca-cert.mdx#L11
- https://github.com/hashicorp/vault/blob/f2041b00e52e4503ed9f23a65142154b6c841ae3/website/content/docs/platform/github-actions.mdx?plain=1#L28
- https://github.com/hashicorp/vault/blob/f2041b00e52e4503ed9f23a65142154b6c841ae3/website/content/docs/platform/github-actions.mdx#L36

However, the actual ENV-var that needs to be used is `VAULT_CACERT`: https://github.com/hashicorp/vault/blob/f2041b00e52e4503ed9f23a65142154b6c841ae3/api/client.go#L39

**Comment by miagilepner** [comment]
Thanks for reporting this! I agree that the top two examples should be changed, and I'll get that updated.

The bottom two examples reference the vault github action and they explain that `secrets.VAULT_CA_CERT` is a github secret in these examples and gets passed as the `caCertificates` parameter in the action. This secret can be named whatever value you like.

**Comment by evdtempel** [comment]
> The bottom two examples reference the vault github action and they explain that `secrets.VAULT_CA_CERT` is a github secret in these examples and gets passed as the `caCertificates` parameter in the action. This secret can be named whatever value you like.

I realize that; I've included it in this issue as to remove any confusion as to what the ENV-var is supposed to be. Having that example mismatch can still nudge someone into a false direction, leading to very unneccessary time loss and frustration.
