### ISSUE TITLE
Unable to start vault agent (version 1.18.0) in Windows

### ISSUE THREAD

**Issue by esenmarti** [hashicorp/vault#28734]
**Describe the bug**
Creating a vault agent in Windows with the new 1.18.0 version fails with `error creating file sink: error during write check: error changing ownership of XXX: chown XXX: not supported by windows`

**To Reproduce**
vault.exe agent -config="config.hcl"

**Expected behavior**
The vault agent starts (this is what we see in the same env when using 1.17.6)

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.15.4
* Vault CLI Version (retrieve with `vault version`): Vault v1.18.0 (77f26ba561a4b6b1ccd5071b8624cefef7a72e84), built 2024-10-08T09:12:52Z
* Server Operating System/Architecture: Windows

Vault server configuration file(s):

```hcl
exit_after_auth = true
pid_file = "/vault/pidfile"

vault {
  address = "xxx"
  retry {
    num_retries = 5
  }
}

auto_auth {
  method "gcp" {
    exit_on_err = true
    mount_path = "auth/xxx"
    config = {
      role = "xxx"
      type = "xx"

    }
  }

  sink "file" {
    config = {
      path = "/a/path/"
    }
  }
}
```

**Additional context**
It might have been introduced in https://github.com/hashicorp/vault/pull/27123

**Comment by miagilepner** [comment]
Thank you for reporting this! I've reproduced the issue and am working on the fix now.
