### ISSUE TITLE
vault-enterprise:1.17.6 docker image does not contain ca-certificates apk package

### ISSUE THREAD

**Issue by conman2305** [hashicorp/vault#28789]
**Is your feature request related to a problem? Please describe.**
We recently upgraded from the `hashicorp/vault-enterprise:1.15.6` docker image to `hashicorp/vault-enterprise:1.17.6` and along with the upgrade to Alpine 3.20, it looks like the `ca-certificates` package is no longer installed. 

We call `update-ca-certificates` as an extra init container in our Helm chart to load internal CA certs into the trusted CA bundle for the main application container as a shared volume mount

**Describe the solution you'd like**
Install the `ca-certificates` package as part of the vault image.

**Describe alternatives you've considered**
We reverted back to the 1.15.6 image as the source init container for building the trusted cert bundle for now, but it would be nice to keep the init container we use to build the trusted cert bundle the same version as the main application container

**Comment by dukhat2259** [comment]
FWIW, I wrestled with this yesterday and I caved in with
```
services:
  vault:
    volumes:
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem:ro
```

**Comment by phuhung273** [comment]
Can reproduce in 1.18.2
```console
docker run --rm -it hashicorp/vault-enterprise:1.18.2-ent /bin/sh
/ # apk add ca-certificates
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86/APKINDEX.tar.gz
(1/1) Installing ca-certificates (20240705-r0)
Executing busybox-1.36.1-r29.trigger
Executing ca-certificates-20240705-r0.trigger
OK: 9 MiB in 23 packages
```

**Comment by heatherezell** [comment]
As this is for Vault Enterprise, please escalate this issue to your support and sales teams. The public Vault repo is intended for issues and bugs to be reported against the Community Edition. Thanks!
