### ISSUE TITLE
how to upgrade from etcd2 to etcd3 api

### ISSUE THREAD

**Issue by shsjshentao** [hashicorp/vault#2879]
single node
upgrade from 0.6.2 to 0.7.3
logs showed  "Unseal failed, invalid key"
However, it upgraded well from 0.6.2 to 0.7.0.
I'm sure i input correct key by manual and scripts.

I found that the data is stored from etcd v2 api to v3 api. 
Once i stored data used etcd 2.2 version with api 2, vault 0.6.2 with etcd api 2. 
Now i upgraded etcd to 3.1.9 version with api 3 and have migrated the data.
But i cannot use vault 0.7.3 with etcd api 3 to unseal these data.
Any solutions to deal with it?

**Comment by shsjshentao** [comment]
@xiang90

**Comment by xiang90** [comment]
I do not maintain v2 store and I am not the owner of that. I guess you can recreate your vault or migrate the data somehow. But I have no bandwidth to help with the migration.

**Comment by trunet** [comment]
please, see https://github.com/hashicorp/vault/issues/2862

**Comment by jsok** [comment]
I've written an `etcdctl` migration transformer to help, the code is available at: https://github.com/jsok/etcd-vault-transformer

**Comment by briankassouf** [comment]
Going to close this since there are some solutions linked in the ticket and a more general purpose backend migrator is on our radar
