### ISSUE TITLE
TLS handshake errors between vault servers every 2 minutes

### ISSUE THREAD

**Issue by shayangz** [hashicorp/vault#2882]
We see errors like this every 2 minutes on our vault servers (both active and standby)

```
Jun 16 16:52:05 vault-i-XXX vault[4238]: 2017/06/16 16:52:05 http: TLS handshake error from $ip:38434: EOF
```

`$ip` in the logs for each server is the IP the server itself is bound to.

This is on Vault `0.7.3` but we have observed the same thing on `0.7.2`.

The `tls_cert_file` contains the full chain all the way to our internal CA (3 certificates total: server, intermediate, and root ca)

What's odd is that servers seem to be in good state in terms of HA when we look at the status response

```
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Unseal Nonce:
Version: 0.7.3
Cluster Name: <name>
Cluster ID: <guid>

High-Availability Enabled: true
	Mode: active
	Leader: https://$ip:8200
```

and all clients are able to communicate with the servers over TLS just fine.

Not sure what this error means and why it's occurring.

Any help is appreciated.

**Comment by joelthompson** [comment]
Do you have some sort of health check process on the machine checking that there's something listening on port 8200 every 2 minutes?

**Comment by shayangz** [comment]
Not really. There is the consul agent for the service vault registers but that shows success for health check.

I suspect it's vault itself because the timing of the 2-minute check changes only when I `reload` vault.

**Comment by jefferai** [comment]
Vault doesn't connect to itself.

**Comment by jefferai** [comment]
Are you sure it's *that server*'s IP? It's not one of your other HA members' IPs?

**Comment by shayangz** [comment]
I have doubled checked. The IP in the log belongs to the server doing the logging:

```
$ ifconfig
eth0      Link encap:Ethernet  HWaddr 0a:36:17:3d:97:fc
          inet addr:10.42.41.19  Bcast:10.42.41.255  Mask:255.255.255.0
          inet6 addr: fe80::836:17ff:fe3d:97fc/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:13008492 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10904968 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:15007711065 (15.0 GB)  TX bytes:6222055942 (6.2 GB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:8725953 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8725953 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:18130811512 (18.1 GB)  TX bytes:18130811512 (18.1 GB)
```

logs:

```
Jun 16 20:34:05 vault-i- vault[8520]: 2017/06/16 20:34:05 http: TLS handshake error from 10.42.41.19:39290: EOF
Jun 16 20:36:05 vault-i- vault[8520]: 2017/06/16 20:36:05 http: TLS handshake error from 10.42.41.19:39318: EOF
Jun 16 20:38:05 vault-i- vault[8520]: 2017/06/16 20:38:05 http: TLS handshake error from 10.42.41.19:39346: EOF
Jun 16 20:40:05 vault-i- vault[8520]: 2017/06/16 20:40:05 http: TLS handshake error from 10.42.41.19:39376: EOF
Jun 16 20:42:05 vault-i- vault[8520]: 2017/06/16 20:42:05 http: TLS handshake error from 10.42.41.19:39410: EOF
Jun 16 20:44:05 vault-i- vault[8520]: 2017/06/16 20:44:05 http: TLS handshake error from 10.42.41.19:39434: EOF
Jun 16 20:46:05 vault-i- vault[8520]: 2017/06/16 20:46:05 http: TLS handshake error from 10.42.41.19:39466: EOF
Jun 16 20:48:05 vault-i- vault[8520]: 2017/06/16 20:48:05 http: TLS handshake error from 10.42.41.19:39494: EOF
Jun 16 20:50:05 vault-i- vault[8520]: 2017/06/16 20:50:05 http: TLS handshake error from 10.42.41.19:39524: EOF
Jun 16 20:52:05 vault-i- vault[8520]: 2017/06/16 20:52:05 http: TLS handshake error from 10.42.41.19:39552: EOF
```

and the vault config:

```
$ sudo cat /etc/vault/vault.json
{
  "disable_mlock": false,
  "listener": {
    "tcp": {
      "address": "10.42.41.19:8200",
      "tls_cert_file": "/etc/vault/ssl/certs/vault.crt",
      "tls_key_file": "/etc/vault/ssl/private/vault.key",
      "tls_disable": "false"
    }
  },
  "backend": {
    "consul": {
      "token": "XXX",
      "address": "127.0.0.1:8500"
    }
  }
}
```

all of this is on the same box.

What is the frequency of the health check that Vault registers with Consul?

**Comment by jefferai** [comment]
The default is 5 seconds unless overridden (which your config isn't doing).

**Comment by den-is** [comment]
@jefferai okay, you made me to look on problem lil bit closer. lol :D
And I solved it, thanks to this guys comment https://github.com/hashicorp/vault/issues/1194#issuecomment-256635483
I was using TCP health-check instead of HTTPS.
now when I started using `HTTPS:8200/v1/sys/health` everything works.

**Comment by shayangz** [comment]
We finally found the source for this. As suggested, this was an external check 🤦‍♂️ (sensu port check in this instance)

**Comment by deepanvermag3** [comment]
@shayangz How did you solve this issue?

**Comment by shayangz** [comment]
@ deepanvermag3, we were not properly passing the internal CA to our external health check. Correctly that issue removed these logs.
