### ISSUE TITLE
HA with Consul backend

### ISSUE THREAD

**Issue by dbabb-charter** [hashicorp/vault#2885]
I've got 2 vault servers running...well 1 right now but we'll get to that.

If I have both vaults running in an HA config, and hit the end point I have setup every other hit I get a vault sealed. When I hit the afflicted box to try to unseal it, I get that the vault is already unsealed.

I'm running these in AWS on ubuntu 16, they're both behind a classic ELB looking at port 8200 with a tcp health check to the same port.

```
storage "consul" {
	ha_enabled = "true"
	default_lease_ttl = "1d"
    max_lease_ttl = "30d"
    address = "127.0.0.1:8500"
}

listener "tcp" {
    address         =   "0.0.0.0:8200"
    tls_cert_file   =   "/etc/letsencrypt/live/certpath/cert.pem"
    tls_key_file    =   "/etc/letsencrypt/live/keypath/privkey.pem"
}

cluster_name        =   “cluster”
disable_cache       =   "true"
```

**Comment by jefferai** [comment]
> When I hit the afflicted box

How are you "hitting" it?

**Comment by dbabb-charter** [comment]
Using the vault binary after setting the server and token variables. 

vault mounts gives me this behavior for example.

**Comment by jefferai** [comment]
But you're not setting the address to the *specific* instance's address, rather than the load balancer?

**Comment by dbabb-charter** [comment]
Correct. So
VAULT_ADDR="https://<url>"

I was under the impression that non primary vault instances would forward to the primary and that pointing at the URL shouldn't matter.

**Comment by jefferai** [comment]
If the load balancer is round robin-ing, which it seems like, then when you try to unseal your standby you're likely to just get pointed to the active node, which is already unsealed.

**Comment by dbabb-charter** [comment]
That I expected, what I didn't expect is clients getting the error message that the vault is sealed. At the moment, I have one just turned off to keep it from happening anymore. Am I missing something in my config to make the experience seemless while having _n_ number of vault instances?

**Comment by jefferai** [comment]
If your standby node is sealed, and your load balancer is sending clients to it, what is the behavior you expect?

**Comment by jefferai** [comment]
If a client hits a sealed instance, what *are* you expecting? It seems like an error to the client telling them it's sealed is about the only thing we can do. I guess we could just drop the connection silently, but I'd rather not go down that path.

**Comment by jefferai** [comment]
Oh, hah. Sorry about the double post. I switched computers and this issue hadn't updated, and I forgot I'd responded.

**Comment by joelthompson** [comment]
> I was under the impression that non primary vault instances would forward to the primary and that pointing at the URL shouldn't matter.

@dbabb-charter -- it sounds like you're mixing up sealing/unsealing with being an active/standby. You need to unseal _all_ nodes individually. When a node gets unsealed, it'll check to see if it should become the active one and, if not, it will drop into being a standby. Then the standbys will forward requests to the leader. But that can only happen once they've been unsealed.

**Comment by dbabb-charter** [comment]
That's fair, I was under the impression that using consul as storage eliminated the need to unseal everything individually. I've got them unsealed but now they appear to hang half the time. I've set my redirect_addr as per the documents and half of my vault commands just..hang.

Reading the docs it reads like the standby instance should automatically forward the request to the leader yet it's not doing that for me. It just times out.

**Comment by dbabb-charter** [comment]
Ignore all of that, I had my ELB configured to do simple TCP 8200 check. Did a little digging found this:
```
https://vault.url/v1/sys/health 
```
endpoint which instead of a 200 returns 429 if the vault is unsealed AND standby. Adjusted my ELB for that health check and the vault instance is no longer taking traffic. Did a fail over test and after cranking my checks down as far as interval, that fixed my issue.

https://www.vaultproject.io/api/system/health.html

Closing this.
