### ISSUE TITLE
Inconsistent documentation for config options

### ISSUE THREAD

**Issue by BookOfGreg** [hashicorp/vault#2894]
Hi Vault team,

I'm having trouble configuring my first Vault running without -dev. This is due to the following two pages on the vault project site:

This page specifies the key for storage to be "Storage"
https://www.vaultproject.io/docs/configuration/index.html
This page specifies the key for storage to be "Backend"
https://www.vaultproject.io/intro/getting-started/deploy.html

And I'm finding a lot of trouble finding working example configuration that would allow me to decide which is correct.

Is there an example running project (possibly docker) with a working vault + consul/mysql/file backend?
And which is the correct config option?

**Comment by BookOfGreg** [comment]
Additionally:
I'm getting syntax invalid with the following config options in my vault-config.hcl file:

https://www.vaultproject.io/docs/configuration/index.html#max_lease_ttl
https://www.vaultproject.io/docs/configuration/index.html#telemetry

```hcl
listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = 1
}

storage "mysql" {
  username = "vault"
  password = "vault"
  database = "vault"
  address = "127.0.0.1:3306"
  table = "vault"
  max_parallel = "128"
}
telemetry = nil
max_lease_ttl = "32d"
default_lease_ttl = "14d"
```

I was under the impression, providing nil to telemetry and "32d" to max_lease_ttl was OK but max_lease_ttl only takes "32h" and telemetry must be unspecified.

**Comment by jefferai** [comment]
What version of Vault? And simply don't set telemetry rather than configuring to nil.

**Comment by BookOfGreg** [comment]
I'm running Vault 0.7.3 at the moment.
Yep, just seemed unusual the docs had `telemetry = nil` when that is not something that is possible.

**Comment by jefferai** [comment]
The maximum valid time unit is "h" for hour, if the docs have 32 days this is incorrect. The default *is* 32 days but probably not as a string.

**Comment by jefferai** [comment]
The docs for telemetry are simply indicating that by default there is no configuration, not a "nil" construct.

**Comment by BookOfGreg** [comment]
Thank you for the doc update, I find that much clearer.

Can I ask if `backend` and `storage` are interchangeable in the config as they appear on two separate pages?

**Comment by jefferai** [comment]
They're interchangeable.
