### ISSUE TITLE
docs: minor typo in aws secrets engine documentation

### ISSUE THREAD

**Issue by kevin-loehfelm** [hashicorp/vault#28954]
**Describe the bug**
Minor documentation update. In Vault 1.16, the AWS secrets engine added a fourth type of credential that can be retrieved but the documentation still says three:

https://developer.hashicorp.com/vault/docs/v1.16.x/secrets/aws

**To Reproduce**
N/A

**Expected behavior**
Documentation should be updated to 'four'

**Comment by kevin-loehfelm** [comment]
I've submitted PR https://github.com/hashicorp/vault/pull/28930 to address this

**Comment by kubawi** [comment]
Thanks, Kevin! The PR is merged in, so I am closing this issue.
