### ISSUE TITLE
Document CLI does not support map to describe 'meta' for tokens

### ISSUE THREAD

**Issue by timp87** [hashicorp/vault#2896]
Hello. Please, document CLI does not support map to describe **meta** for token creation.
https://www.vaultproject.io/docs/auth/token.html tells us about **meta** optional parameter. But doesn't say you can't set it using CLI. Instead you spend hours getting this:

> 'meta' expected a map, got 'string'

I found very similar ticket https://github.com/hashicorp/vault/issues/2569 where documentation for SSH was fixed https://www.vaultproject.io/docs/secrets/ssh/index.html
Please, describe the same way how to pass JSON to create a map for token creation!

**Comment by jefferai** [comment]
You can use `-metadata` multiple times from the CLI to specify keys/values you want.

**Comment by timp87** [comment]
@jefferai, sorry, but I couldn't find a place where it's documented on the web-site. Also bare 
`vault write`
or
`vault path-help auth/token/create`
commands don't tell me about this option.

Finally this simply doesn't work. I tried several variants. It eats my input, but **meta** is still \<nil\>. Where can I find an example? . I'm using 0.7.2

**Comment by jefferai** [comment]
@timp87 `vault token-create -h` will give you the info you want.

**Comment by timp87** [comment]
@jefferai Thanks a lot!

**Comment by chkp-syoffe** [comment]
how do i create a token role
