### ISSUE TITLE
Failed to authenticate using azure auth

### ISSUE THREAD

**Issue by tonicmuroq** [hashicorp/vault#28965]
Our enterprise vault was upgraded from 1.16.10 to 1.18.1, then azure authentication was broken. The log says

```
invalid vm name "aks-agentpool-xxx-vmss_0"
```

then I checked the node names, they should be `aks-agentpool-xxx-vmss000000`, then I checked the result from azure metadata API, the field `compute.name` is `aks-agentpool-xxx-vmss_0`, but `compute.osProfile.computerName` is `aks-agentpool-xxx-vmss000000`, I'm not sure what happened here, maybe azure / vault changed the way to authenticate?

Tried to upgrade vault lib to the latest version, and didn't work.

I forked a repo and did tiny changes then everything works well, check https://github.com/tonicmuroq/vault/commit/587e9615ef3146c57ceb85e776f2c4742cb16a99 , not sure if this is the correct way. How could I fix this issue gracefully?

**Comment by neodejack** [comment]
seems like the name validation regex is fixed in the underlying dependency [vault-plugin-auth-azure](https://github.com/hashicorp/vault-plugin-auth-azure) v0.19.2: https://github.com/hashicorp/vault-plugin-auth-azure/pull/172

**Comment by stevendpclark** [comment]
Hi @tonicmuroq, 

I believe that @neodejack is correct, the plugin version v0.19.2 was updated within Vault in https://github.com/hashicorp/vault/pull/28848, so it should be out in the next minor release of Vault coming shortly. 

With that I'll close out this issue, please feel free to re-open it if Vault 1.18.2 doesn't resolve the issue when it is released.
