### ISSUE TITLE
sirupsen/logrus case-insensitive import collision

### ISSUE THREAD

**Issue by AkdM** [hashicorp/vault#2900]
Hi,

We are getting the following message with `go get` due to [@sirupsen's Logrus recent changes on the repo](https://github.com/sirupsen/logrus/commit/acfabf31db8f45a9174f54a0d48ea4d15627af4d):
> case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"

This broke a lot of things. Can you fix it?

**Comment by jefferai** [comment]
Vault doesn't use logrus.

**Comment by jefferai** [comment]
I also can't reproduce:

`go get -u github.com/hashicorp/vault/api` returns with no error.

**Comment by AkdM** [comment]
That's right, my bad. But vendors on Vault do use logrus and they still use the old `github.com/Sirupsen/logrus` instead of `github.com/sirupsen/logrus`.

The reason I am getting this error is because some of our dependencies use the package with a `s` lowercase, but others with the old `S` uppercase.

**Comment by jefferai** [comment]
@AkdM I'm sorry but I still don't understand the problem. I just tried vendoring the API package and govendor reports no errors.

**Comment by sunanxiang** [comment]
@AkdM  I also have this problem, do you resolve this problem?

**Comment by AkdM** [comment]
@sunanxing the problem was that the dependences I was using was still using the old naming (without the uppercase S). You will need to wait those dependencies to change the import, or fork it and change yourself (then make a PR).

**Comment by jefferai** [comment]
@sunanxiang You shouldn't have this problem anymore as of sometime yesterday (so, today).

**Comment by sunanxiang** [comment]
@jefferai Yeah, I don't have any problems.
