### ISSUE TITLE
Request to consider vault image availability on quay.io

### ISSUE THREAD

**Issue by bandak2** [hashicorp/vault#29027]
**Is your feature request related to a problem? Please describe.**
Vault image is not available on quay.io. With Docker limits, there are certain times where getting vault image from docker gets challenging.

**Describe the solution you'd like**
Having the vault images to be made available in quay.io, if possible.

**Describe alternatives you've considered**
N/A

**Explain any additional use-cases**
We'd like to see the vault image available on quay.io where there are no restrictions on pull limits. It would be ideal for most users.

**Additional context**
N/A

**Comment by bosouza** [comment]
Hey, you can find the full list of release channels [here](https://www.hashicorp.com/official-release-channels), which includes [ECR](https://gallery.ecr.aws/hashicorp/vault) and [Red Hat Container Registry](https://catalog.redhat.com/software/containers/hashicorp/vault/5fda55bd2937386820429e0c). Hopefully those already address your rate limit concerns. I checked with the release engineering team and there are no plans of adding vanilla quay.io.
