### ISSUE TITLE
Error validating token: Error making API request

### ISSUE THREAD

**Issue by safdaram** [hashicorp/vault#2903]
Hi
I am new user implementing VAULT.  Please help!  
While executing the following:
[root@RAC1 ~]# vault auth root
Error validating token: Error making API request.

URL: GET http://127.0.0.1:8200/v1/auth/token/lookup-self
Code: 403. Errors:

As per some posts, the fix is as follows:
[root@RAC1 ~]# curl -X POST http://127.0.0.1:8200/v1/auth/token/tidy -H 'X-VAULT-TOKEN:<>'
{"errors":["permission denied"]}

Thanks Amer.

**Comment by jefferai** [comment]
It would appear that `root` is not a valid token for your Vault.

**Comment by safdaram** [comment]
Thank you for your response.  I was able to resolve the issue, pasting the output:
[root@RAC1 ~]# export VAULT_TOKEN=51b279db-9553-7d8d-c0ef-08b23ccb3431
[root@RAC1 ~]# vault auth root
==> WARNING: VAULT_TOKEN environment variable set!

  The environment variable takes precedence over the value
  set by the auth command. Either update the value of the
  environment variable or unset it to use the new token.

Successfully authenticated! You are now logged in.
token: 51b279db-9553-7d8d-c0ef-08b23ccb3431
token_duration: 0
token_policies: [root]

[root@RAC1 ~]# curl -X POST http://127.0.0.1:8200/v1/auth/token/tidy -H 'X-VAULT-TOKEN:51b279db-9553-7d8d-c0ef-08b23ccb3431'

**Comment by safdaram** [comment]
What does the tidy command do?

**Comment by jefferai** [comment]
@safdaram See https://www.vaultproject.io/docs/auth/token.html#auth-token-tidy
