### ISSUE TITLE
Alpine package missing

### ISSUE THREAD

**Issue by MeikelLP** [hashicorp/vault#29054]
**Describe the bug**

The `vault` package was available on [alpine 3.18](https://pkgs.alpinelinux.org/package/v3.18/community/x86/vault) but is no [longer available](https://pkgs.alpinelinux.org/packages?name=vault&branch=edge&repo=&arch=&origin=&flagged=&maintainer=)

**To Reproduce**

```Dockerfile
FROM alpine

RUN apk add --no-cache vault
```

```
ERROR: unable to select packages:
  vault (no such package):
     required by: world[vault]
```

**Expected behavior**
Vault should be installable on Alpine Linux. Especially since official Vault Alpine images are available too (?)

**Environment:** Windows 10 / Docker
* Vault Server Version (retrieve with `vault status`): -
* Vault CLI Version (retrieve with `vault version`): -
* Server Operating System/Architecture: x64

Vault server configuration file(s): -

**Additional context**
We are depending on an Alpine based Docker images for our pipelines. We can't swap everything to a debian based image easily.

**Comment by stevendpclark** [comment]
Hello @MeikelLP, 

Sadly this is outside of our control. I can refer you to Alpine's 3.19 [release notes](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.19.0) where they decided to pull Vault from the Alpine package system. 

So the only options would be to download Vault manually from https://releases.hashicorp.com/vault/ during your setup of your docker image or use our docker image (https://hub.docker.com/r/hashicorp/vault/) as the base of yours, as you noted, our docker image is Alpine based.

**Comment by Letme** [comment]
@stevendpclark Would it be possible to get the apk repository established? Because it is a bit clumsy that you need to switch between the arches manually when building multi-arch image.

**Comment by stevendpclark** [comment]
Please see our [official packaging guide](https://www.hashicorp.com/en/official-packaging-guide) for a list of our officially-supported packages and distributions.

**Comment by Letme** [comment]
yes, I realize, but it is missing Alpine Linux and recently that has become quite popular with Docker containers and size.

**Comment by srzewuskiCF** [comment]
guys... bring the "vault" back - make life easier not harder
