### ISSUE TITLE
go client api: logical read does not return an error when reading non-existent path

### ISSUE THREAD

**Issue by mattcotton-justgiving** [hashicorp/vault#2907]
I'm using the GO client library. My code is like this:
```go
vaultsecret, err := client.Logical().Read(path)
```
but when the path does not exist I don't receive an err. The only indication that something is wrong is the vaultsecret is a null pointer.

Surely it would be better to indicate a non-existent path more explicitly? Either return an error or, if not considered exceptional, have the returned *Secret contain and empty Data map and maybe include a Warning.

Currently I have to check both err and vaultsecret for nil, and in the case of vaultsecret being nil I've not idea why.

**Comment by jefferai** [comment]
You should always be checking both the error and return value for nil! 

Lots of responses in Vault will return nil if there is no data, e.g. if you get a 204. In the case of read, a 404 means no data, so we skip having you check for a not found error.

**Comment by mattcotton-justgiving** [comment]
Thanks for info. But if I'm using the GO client library how do I know what the HTTP status was? I have no useful information from the Read.

**Comment by mattcotton-justgiving** [comment]
Or are you saying the *Secret will only ever be nil if there is no data?

**Comment by jefferai** [comment]
If data was returned it would be parsed into a `*Secret`. No error and no secret means no data.
