### ISSUE TITLE
Cannot configure working HTTPS Vault installation? Vault program broken (vs. lack of documentation)?

### ISSUE THREAD

**Issue by jonmdev** [hashicorp/vault#29099]
**Describe the bug**

Cannot create a working HTTPS installation following all available instructions online.

**To Reproduce**

## 1) Start with raw Ubuntu EC2, install Vault:

```
wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

sudo apt update && sudo apt install vault
```

## 2) Init the Vault

```
vault operator init
vault operator unseal <key1>
vault operator unseal <key2>
vault operator unseal <key3>
vault login <root_token>
```
## 3) Create Vault Service
`sudo nano /etc/systemd/system/vault.service`

```
[Unit]
Description=HashiCorp Vault - A tool for secrets management
Documentation=https://www.vaultproject.io/docs/
After=network.target

[Service]
User=vault
Group=vault
ExecStart=/usr/bin/vault server -config=/etc/vault.d/vault.hcl
Restart=on-failure
LimitNOFILE=65536
StandardOutput=journal
StandardError=journal
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
KillSignal=SIGINT
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
```

`
sudo systemctl enable vault`
`sudo reboot`

## 3) Set VAULT_ADDR environmental variable

`sudo nano /etc/environment`

`VAULT_ADDR="http://127.0.0.1:8200"`

## 4) Set AWS auto-unseal:
Make AWS key and policy for the EC2:

```
{
	"Version": "2012-10-17",
	"Statement": [
		 {
          "Effect": "Allow",
          "Action": [
            "kms:Decrypt",
            "kms:Encrypt",
            "kms:GenerateDataKey",
            "kms:DescribeKey"
          ],
          "Resource": "arn:aws:kms:us-east-1:THE_ARN_OF_THE_KEY"
        }
	]
} 
```

Add the HTTP listener and key to vault.hcl:

`sudo nano /etc/vault.d/vault.hcl`

```
# HTTP listener
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}

seal "awskms" {
  region     = "us-east-1"          # Specify the region where your CMK is located
  kms_key_id = "arn:aws:kms:us-east-1:THE_ARN_OF_THE_KEY"  # The ARN of your KMS key
}
```
`sudo reboot`
`vault operator unseal -migrate` x3 times
`sudo reboot`

At this point everything will still work properly. `vault status` will show an unsealed vault which is running correctly. http://ip:8200 will take you to the Vault login page.

## 5) Switch to HTTPS

Here is where everything goes wrong.

`sudo nano /etc/vault.d/vault.hcl`

```
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

# Full configuration options can be found at https://developer.hashicorp.com/vault/docs/configuration

ui = true

#mlock = true
#disable_mlock = true

storage "file" {
  path = "/opt/vault/data"
}

#storage "consul" {
#  address = "127.0.0.1:8500"
#  path    = "vault"
#}

# HTTP listener
#listener "tcp" {
#  address = "0.0.0.0:8200"
#  tls_disable = 1
#}

# HTTPS listener
listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/opt/vault/tls/tls.crt"
  tls_key_file  = "/opt/vault/tls/tls.key"
  tls_disable_client_certs = "true"
  tls_disable = 0
}

# Enterprise license_path
# This will be required for enterprise as of v1.8
#license_path = "/etc/vault.d/vault.hclic"

# Example AWS KMS auto unseal
seal "awskms" {
  region = "us-east-1"
  kms_key_id = "arn:aws:kms:key_information
}

# Default unseal method
#seal "shamir" {
#  secret_shares = 5
#  secret_threshold = 3
#}

# Example HSM auto unseal
#seal "pkcs11" {
#  lib            = "/usr/vault/lib/libCryptoki2_64.so"
#  slot           = "0"
#  pin            = "AAAA-BBBB-CCCC-DDDD"
#  key_label      = "vault-hsm-key"
#  hmac_key_label = "vault-hsm-hmac-key"
#}
```
Update environmental address to https:

`sudo nano /etc/environment`

`VAULT_ADDR="https://127.0.0.1:8200"`

Set permissions for tls cert/locations so can add certificates/key:
```
sudo chown -R ubuntu:ubuntu /opt/vault/tls
sudo chmod -R u+w /opt/vault/tls
sudo chmod u+w /opt/vault/tls/tls.crt 
sudo chmod u+w /opt/vault/tls/tls.key 
```
Copy certificates (as main cert + any bundle or CA concatenated in that order in one file) to file path in vault.hcl, and private key also as other file. Confirm these are correct and located there:

`cat "/opt/vault/tls/tls.crt"`
`cat "/opt/vault/tls/tls.key"`

`sudo systemctl restart vault`
`sudo reboot`

## 6) Result: System is now broken

At this point, nothing will run anymore. Cannot restart Vault. No meaningful error output by any logs. Cannot run `vault status` or anything.

**Expected behavior**

Based on all available documentation I believe these are the correct steps to run to make this work. However, after following these steps, I get nothing meaningful anymore:

### `vault status`:

```
Error checking seal status: Get "https://127.0.0.1:8200/v1/sys/seal-status": dial tcp 127.0.0.1:8200: connect: connection refused
```

### `vault operator unseal`

```
Error unsealing: Put "https://127.0.0.1:8200/v1/sys/unseal": dial tcp 127.0.0.1:8200: connect: connection refused
```
### `sudo journalctl -u vault -f | more`

```
Dec 05 02:39:38 ip-172-31-19-38 vault[1358]: 2024-12-05T02:39:38.756Z [INFO]  incrementing seal generation: generation=1
Dec 05 02:39:38 ip-172-31-19-38 vault[1358]: 2024-12-05T02:39:38.756Z [WARN]  no `api_addr` value specified in config or in VAULT
_API_ADDR; falling back to detection if possible, but this value should be manually set
Dec 05 02:39:38 ip-172-31-19-38 vault[1358]: 2024-12-05T02:39:38.804Z [INFO]  core: Initializing version history cache for core
Dec 05 02:39:38 ip-172-31-19-38 vault[1358]: 2024-12-05T02:39:38.804Z [INFO]  events: Starting event system
Dec 05 02:39:38 ip-172-31-19-38 systemd[1]: vault.service: Main process exited, code=exited, status=1/FAILURE
Dec 05 02:39:38 ip-172-31-19-38 systemd[1]: vault.service: Failed with result 'exit-code'.
Dec 05 02:39:39 ip-172-31-19-38 systemd[1]: vault.service: Scheduled restart job, restart counter is at 5.
Dec 05 02:39:39 ip-172-31-19-38 systemd[1]: vault.service: Start request repeated too quickly.
Dec 05 02:39:39 ip-172-31-19-38 systemd[1]: vault.service: Failed with result 'exit-code'.
Dec 05 02:39:39 ip-172-31-19-38 systemd[1]: Failed to start vault.service - HashiCorp Vault - A tool for secrets management.
```

Thus nothing is working anymore and I cannot obtain any meaningful explanation or output for why.

Furthermore (as a bonus issue), if I go back to http and try to remove the AWS unseal in this condition (to see if will help), I can again no longer startup. In this case (back to http and remove aws seal) I get from `sudo journalctl -u vault -f | more`:

```
Error initializing core: cannot seal migrate from "awskms" to Shamir, no disabled seal in configuration
```

So it appears we additionally can not remove the aws unseal once placed?

**Environment:**
* Vault Server Version (retrieve with `vault status`):
Version                  1.18.2

* Vault CLI Version (retrieve with `vault version`):
Vault v1.18.2 (e36bac59ddb8e10e8912c0ddb44416c850939855), built 2024-11-20T11:24:56Z

* Server Operating System/Architecture:
Ubuntu 22 standard EC2

**Additional context**

If this is a working system, and it is user error on my part, is there any documentation anywhere that explains the problem?

I have been reading Hashi website and querying ChatGPT for days now trying to get this running and I am no closer to success. I find no information to explain what the issue might be. I can obtain no helpful output from my system to tell me what the problem is.

I would hope for any of the following:

1) The bug (if any) is fixed
2) There can be clear errors debugged out from Vault to tell the user the configuration problem or solution if there is one
3) Clear documentation explaining how to configure this if it does in fact work (for example, to extend from [this](https://developer.hashicorp.com/vault/tutorials/getting-started/getting-started-deploy))

Thanks for any help.

**Comment by stevendpclark** [comment]
Just a guess, but in step 3 you listed within your service file that Vault is to be run as the `vault` user

```
[Service]
User=vault
Group=vault
...
```

but in step 5, the ownership assigned to the TLS keys is to the `ubuntu` user

```
sudo chown -R ubuntu:ubuntu /opt/vault/tls
...
```

> Furthermore (as a bonus issue), if I go back to http and try to remove the AWS unseal in this condition

I'm not exactly sure why you are trying to go back to http and removing the AWS unseal in one go, keeping the AWS seal in place and going back to just http should have worked, which is what you had at the end of step 4? 

To remove the AWS seal that you migrated to from Shamir in step 4, you would need to perform a similar migration from AWS seal back to Shamir by adding back the AWS seal configuration and adding `disabled = true` within the section. Upon startup you'd then need to call `vault operator unseal -migrate` providing the original shamir keys to migrate back to a shamir system.

**Comment by jonmdev** [comment]
> Just a guess, but in step 3 you listed within your service file that Vault is to be run as the `vault` user
> 
> ```
> [Service]
> User=vault
> Group=vault
> ...
> ```
> 
> but in step 5, the ownership assigned to the TLS keys is to the `ubuntu` user
> 
> ```
> sudo chown -R ubuntu:ubuntu /opt/vault/tls
> ...
> ```
> 
> > Furthermore (as a bonus issue), if I go back to http and try to remove the AWS unseal in this condition
> 
> I'm not exactly sure why you are trying to go back to http and removing the AWS unseal in one go, keeping the AWS seal in place and going back to just http should have worked, which is what you had at the end of step 4?
> 
> To remove the AWS seal that you migrated to from Shamir in step 4, you would need to perform a similar migration from AWS seal back to Shamir by adding back the AWS seal configuration and adding `disabled = true` within the section. Upon startup you'd then need to call `vault operator unseal -migrate` providing the original shamir keys to migrate back to a shamir system.


Oh my gosh Steve thank you so much! You know I had the same idea about the ownership last night when I was posting which is why I added those steps. I am not that good with Ubuntu and file ownership or groups. 

### Need for changing ownership of certs

I had to change the ownership to ubuntu or I couldn't `scp` the key and cert to the server (permission denied). 

### `vault` vs. `ubuntu` user/group
I made the vault run on its own group as in the service based on I believe ChatGPT's suggestion (as I had to go to it to figure out some steps. Currently it says:

>Security Best Practice: The vault user and group are typically created during the installation of HashiCorp Vault, and it's considered a best practice to run Vault as its own dedicated, non-privileged user (vault). This ensures that Vault has limited access to system resources, minimizing the attack surface in case of a compromise.

Is that true?

### Fix 1
I was able to get it running with two changes. The first was to run:

```
sudo chown -R vault:vault /opt/vault/tls
```
So if it is correct that my general ubuntu user is doing the scp (I do all my server maintenance this way) to copy the certs, I will have to switch the ownership back and forth each time (to ubuntu to write, to vault after to let it read).

### Fix 2
When using the https configuration, you must set `EXPORT VAULT_ADDR="https://certdomain.com"` or it says:

>Error checking seal status: Get "https://127.0.0.1:8200/v1/sys/seal-status": tls: failed to verify certificate: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs

At least that error gave a clue to the issue. When the permissions were not set correctly, we were getting no error out at all. Just "Vault has exited" Catching and sharing the permissions error would have been nice.

>To remove the AWS seal that you migrated to from Shamir in step 4, you would need to perform a similar migration from AWS seal back to Shamir by adding back the AWS seal configuration and adding disabled = true within the section. Upon startup you'd then need to call vault operator unseal -migrate providing the original shamir keys to migrate back to a shamir system.

Thank you as well. I forgot that I had even done that step. I could not find any good documentation on the migration 

Summarized also here:
https://support.hashicorp.com/hc/en-us/articles/22624157966355-Auto-unseal-migration-from-Transit-to-AWS-KMS

Based on my personal experience, if the approach I have described is then otherwise correct at all steps, I suggest if you guys are open to it (you have a lot of documentation but this seems to be a hole):

- Add an article explaining how to configure https similar to this: https://developer.hashicorp.com/vault/tutorials/getting-started/getting-started-deploy
- If Vault is exiting FOR ANY REASON, please print or debug or echo or log somewhere the reason. In this case, an echo or log action should be taken if there is a permissions failure on the certificates, as otherwise we have no evidence for the problem and it would have otherwise been an obvious fix (even for someone like me with limited Ubuntu expertise) had it stated "permissions error accessing keys" or something to that effect.

Thanks again.

**Comment by stevendpclark** [comment]
> Is that true? Ie. I would not want the vault running on ubuntu:ubuntu and vault:vault is already created by the system, right?

Yes I believe it is common practice is to have distinct users, mainly to avoid blast radius of say the ubuntu account being compromised. There are different ways to approach the TLS permission problem such as a common group between the vault and ubuntu user and associating read permissions to the TLS key under that group and ownership being the ubuntu user. Many ways to tackle it, but it all depends on what threats/issues you want to protect against.

> Just "Vault has exited" Catching and sharing the permissions error would have been nice

Agreed, this should have appeared in the logs. I'll need to take a look further as to why that didn't happen

> Add an article explaining how to configure https similar to ...

Further documentation on configuring TLS might be appropriate but in the context of overall system integration, especially when it comes to required ip/domain SANS along with proper key and dedicated CA management would be quite a lengthy article to write. 

With all that I'll close out this issue as we reserve Github issues for bug reports and feature requests. I'll file a dedicated internal ticket to look into the logging issue you encountered.

**Comment by jonmdev** [comment]
Thanks. Re: a guide on HTTPS, all I would suggest is instructions somewhere that following the HTTP guide you:

1) set VAULT_ADDR=https://domain.com:8200 (as now must access by name in certs
2) Add listener as:

```

# HTTPS listener
listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/opt/vault/tls/tls.crt"
  tls_key_file  = "/opt/vault/tls/tls.key"
  tls_disable_client_certs = "true"
  tls_disable = 0
}
```
3) Ensure certs are copied there, with main cert concatenated with bundle/ca certs as one file (main cert first), and private key as other
4) Ensure ownership of cert and key are set back to `vault:vault` if using default configuration once done.

Simple enough but was painful for me to figure out what the system wanted and despite the copious articles on the site I couldn't find a good one on that. ie. "Basic HTTPS Configuration" or something of that nature.

**Comment by jonmdev** [comment]
I should also mention now on further testing: It seems Vault is EXTREMELY SPECIFIC about the rules for the permissions on the key and certs. This should be documented as well presumably (or as a debugged out error message explaining for permission problems) as I am not sure how we could guess it.

# 1) NOT WORKING PERMISSIONS
For example, if I run:

```
         tmp_cmd=$(cat <<EOF
sudo chown -R vault:vault /opt/vault/tls
sudo chmod -R 664 /opt/vault/tls
sudo chmod 664 /opt/vault/tls/tls.crt
sudo chmod 664 /opt/vault/tls/tls.key
sudo chmod -R o+rw /opt/vault/tls
sudo chmod -R o+x /opt/vault/tls
sudo chmod o+rw /opt/vault/tls/tls.crt 
sudo chmod o+x /opt/vault/tls/tls.crt 
sudo chmod o+rw /opt/vault/tls/tls.key
sudo chmod o+x /opt/vault/tls/tls.key
EOF
)
        ssh -i "$pem" "$user@$url" "${tmp_cmd}"
```
before my scp from user `ubuntu:ubuntu` and afterwards:

```
        tmp_cmd=$(cat <<EOF
sudo chown -R vault:vault /opt/vault/tls
EOF
)
        ssh -i "$pem" "$user@$url" "${tmp_cmd}"
```
The copy works but the vault will silently fail again and not say why. I think this should work as vault still owns the file, but it doesn't.

# 2) WORKING PERMISSIONS
However, if I do this before my scp:

```
        tmp_cmd=$(cat <<EOF
sudo chown -R ubuntu:ubuntu /opt/vault/tls
sudo chown ubuntu:ubuntu /opt/vault/tls/tls.crt
sudo chown ubuntu:ubuntu /opt/vault/tls/tls.key
sudo chmod -R u+x /opt/vault/tls
sudo chmod -R u+rw /opt/vault/tls
sudo chmod u+rw /opt/vault/tls/tls.crt 
sudo chmod u+rw /opt/vault/tls/tls.key 
EOF
)
        ssh -i "$pem" "$user@$url" "${tmp_cmd}"
```
And after:
```
        tmp_cmd=$(cat <<EOF
sudo chown -R vault:vault /opt/vault/tls
EOF
)
        ssh -i "$pem" "$user@$url" "${tmp_cmd}"
```

This does work. Why does one work and the other doesn't?

Seems Vault wants to own the key files and directory and not have any read/write/execute permission allowed to anyone else or it fails.

Which is fine if so but we need clear rules in documentation or error messages to explain it. This is just by trial and error at this point. Just FYI @stevendpclark if you are looking into documenting this or giving a useful and specific error to explain the issue.

**Comment by stevendpclark** [comment]
Hi @jonmdev, 

There's only so much we can document, for example removing the execution bit from a directory in Linux forbids users from listing/reading it's contents. So yes the /opt/vault/tls/ needs at a minimum u+x permissions from the `vault` user to read files within it. And you probably don't want to give the Vault user read and write permissions to those TLS keys, read should be sufficient unless you want Vault itself to be able to update them.

You might want to look into the `vault operator diagnose -config=/etc/vault/config.hcl` which does have a lot of these checks and reporting built into it.
