### ISSUE TITLE
Unexpected WARN's in vault log

### ISSUE THREAD

**Issue by ghost** [hashicorp/vault#2912]
I have Vault HA with Consul backend installed in Docker and [WARN] message spammed to stdout every second:
`2017/06/23 16:18:05.178785 [WARN ] physical/consul: check unable to talk with Consul backend: error=Unexpected response code: 500 (CheckID does not have associated TTL)`

Putting request manually I got same result:
`curl -XPUT http://consul:8500/v1/agent/check/pass/vault:vault:8200:vault-sealed-check?note=Vault+Unsealed
CheckID does not have associated TTL`

Problem appears after restarting and unsealing Vault.
Current status of vault:
`Sealed: false
Key Shares: 4
Key Threshold: 2
Unseal Progress: 0
Version: 0.6.4
Cluster Name: <name>
Cluster ID: <id>

High-Availability Enabled: true
        Mode: standby
        Leader: http://172.18.0.13:8200`

Actually I havent any checks to Vault registered in consul:
`http://10.0.0.203:8500/v1/health/checks/service/vault
[]`

Apart from this log message I havent any issues with availability of Vault/Consul.
So is there any way to fix this [WARN]?
Thank you.

**Comment by jefferai** [comment]
@taras-stotsky There have been a lot of updates to the vault/consul integration code since 0.6.4 and as a result I need to ask you to upgrade before going any further. You may want to, at upgrade time, ensure that you remove any registered services with Consul.

**Comment by iamShantanu101** [comment]
@jefferai I am seeing the same error message in the logs except that I have vault and consul both running on a kubernetes cluster. The error is something like:

```
    2019/01/22 13:04:36 [ERR] http: Request PUT /v1/agent/check/pass/vault:10.42.5.19:8200:vault-sealed-check?note=Vault+Unsealed, error: CheckID "vault:10.42.5.19:8200:vault-sealed-check" does not have associated TTL from=10.42.1.22:56478
```

However, this error is only for two consul replicas out of three. That means, one consul replica is working fine.

**Comment by bernardogza** [comment]
I am getting the same error

> @jefferai I am seeing the same error message in the logs except that I have vault and consul both running on a kubernetes cluster. The error is something like:
> 
> ```
>     2019/01/22 13:04:36 [ERR] http: Request PUT /v1/agent/check/pass/vault:10.42.5.19:8200:vault-sealed-check?note=Vault+Unsealed, error: CheckID "vault:10.42.5.19:8200:vault-sealed-check" does not have associated TTL from=10.42.1.22:56478
> ```
> 
> However, this error is only for two consul replicas out of three. That means, one consul replica is working fine.

I am having the same error on a kubernetes cluster. Only on one replica out of three:
[ERR] http: Request PUT /v1/agent/check/pass/vault:10.244.0.9:8200:vault-sealed-check?note=Vault+Unsealed, error: CheckID "vault:10.244.0.9:8200:vault-sealed-check" does not have associated TTL from=10.244.1.8:54692

Did you find the solution ?

**Comment by Aracki** [comment]
This is still an issue..
