### ISSUE TITLE
Add `vault plugin-catalog` CLI command

### ISSUE THREAD

**Issue by calvn** [hashicorp/vault#2923]
Add a `vault plugin-calalog` CLI command that lists and pretty-prints the available plugins and their info. This should be equivalent to `vault list /sys/plugins/catalog` and `vault read /sys/plugins/catalog/:plugin_name`, but provides a nicer output format (similar to `vault mounts` or `vault auth -methods`).

**Comment by jefferai** [comment]
Unsure about this. It's pretty advanced functionality and generally I worry about adding more commands to what is already an overly complex CLI. Ideally we'll completely redo the CLI at some point but not sure how feasible that is.
