### ISSUE TITLE
Efficiently lookup multiple key values from consul

### ISSUE THREAD

**Issue by shoenig** [hashicorp/vault#2926]
Using the consul backend, we're finding vault has trouble looking up values from consul when we make ~100 kv lookups in a row. If we were just using consul as the backend, we would be able to use the `?recurse` parameter to efficiently retrieve the data from a particular namespace. However this feature does not seem to exist in vault. As a work around, we're having to literally call `sleep` in between lookups from vault to mitigate these failures. I imagine `?recurse` is not available in vault for security reasons. Would it though be otherwise possible to have a key/value lookup endpoint where you specify the keys for which the values you want to lookup? That way vault would be able to make a single request to consul instead of spamming it with requests. 
```
2017/06/26 17:37:15.218378 [ERROR] core: failed to lookup token: error=failed to read entry: Get http://127.0.0.1:8500/v1/kv/vault/sys/token/id/<token>: dial tcp 127.0.0.1:8500: connect: cannot assign requested address
2017/06/26 17:37:15.222191 [ERROR] core: failed to lookup token: error=failed to read entry: Get http://127.0.0.1:8500/v1/kv/vault/sys/token/id/<token>: dial tcp 127.0.0.1:8500: connect: cannot assign requested address
2017/06/26 17:37:15.494854 [ERROR] core: failed to lookup token: error=failed to read entry: Get http://127.0.0.1:8500/v1/kv/vault/sys/token/id/<token>: dial tcp 127.0.0.1:8500: connect: cannot assign requested address
2017/06/26 17:37:15.537594 [ERROR] core: failed to lookup token: error=failed to read entry: Get http://127.0.0.1:8500/v1/kv/vault/sys/token/id/<token>: dial tcp 127.0.0.1:8500: connect: cannot assign requested address
(and many more)
```

**Comment by jefferai** [comment]
What versions of Vault and Consul? That error is coming from the local Consul agent endpoint, and we use the official Consul Go lib, and that uses a connection pool with HTTP2 (at least in current versions).

There are many installations running thousands of reads per second with no issue as well as our own integration testing...I suspect something local.

**Comment by catsby** [comment]
Hello - this issue is quite stale with no follow-up, so I'm going to close for now. If you're still having this issue and have more information, please let us know!
