### ISSUE TITLE
vault, consul integration with a new servers

### ISSUE THREAD

**Issue by aravind4444** [hashicorp/vault#2928]
Hi, 
 
We are trying to add more servers into the consul and vault cluster. Currently we have 2 servers which was setup sometime back with the vault and consul integration. 
 
We have commissioned another server and would like to bring the new server into cluster so it becomes 3. 
 
What we have done is - we have generated vault certificate on the new server with all 3 servers in the subjectAltName and trying to import it into to once server at a time that are currently in service, we are getting certificate specific issues and the microservices running on that pspecific server is not starting up. 
 
Any help on how to successfully get all 3 servers into one cluster without service interuption? 

Is there a best way to achieve this?

**Comment by jefferai** [comment]
@aravind4444 Without any sort of understanding of what your issues are/what errors you're seeing there isn't much I can say other than Vault will reload certs with a SIGHUP.

We try to reserve the GH issue tracker for bugs/issues/feature requests so if you have a follow up please use the ML at https://groups.google.com/forum/#!forum/vault-tool

Thanks!

**Comment by aravind4444** [comment]
@jefferai - thanks for writting on this thread. We have setup a 2 cluster server with vault and consul where the vault keys and certificates are generated by having those two servers.

Now we generated the vault and consul keys on the new server with all 2 +1 servers.

As suggested by you in a seperate thread, we brough one active vault to standby and copied the certificates across from 3rd server to 1st server [standby node]. When we were trying to restart the applications running on the 1st server, it is not starting up due to certificate specific issue and also we are not able to unseal the vault in 1st box with the new keys generated in 3rd server.

All what i'm looking for is a step by step implementation to bring up new servers in to vault/consul cluster with no dowtime of the application.
