### ISSUE TITLE
Provide locking for S3 storage backend using DynamoDB

### ISSUE THREAD

**Issue by deverton** [hashicorp/vault#2929]
Similar to how Terraform provides state file locking, the Vault S3 backend could use DynamoDB to provide HA locking.

**Comment by jefferai** [comment]
You can already do this via `storage_ha`.

**Comment by deverton** [comment]
Oh... huh. Yeah of course we already do this with Consul+S3.

For those wondering what that looks like, in your Vault configuration have something like this:

```
ha_storage "dynamodb" {
  ha_enabled = "true"
  region     = "$REGION"
  table      = "vault-lock"
}

storage "s3" {
  bucket = "$S3_BUCKET"
  region = "$REGION"
}
```

Sorry for the noise.
