### ISSUE TITLE
Error initializing client: error reading environment: Error loading CA File: Couldn't parse PEM in

### ISSUE THREAD

**Issue by 13Amand** [hashicorp/vault#2930]
Hi,

I tried creating .pem file using SSL and updating it to the 
export VAULT_CACERT=/home/ec2-user/ca-key.pem
After that I ran this command
export VAULT_ADDR=https://********:8200

Now when I am trying to see the vault status. It is throwing following error

Error initializing client: error reading environment: Error loading CA File: Couldn't parse PEM in: /home/ec2-user/ca-key.pem

**Comment by jefferai** [comment]
What are the contents of the PEM file?

**Comment by 13Amand** [comment]
I realized I was using the wrong file and have resolved this issues. 

Now I am facing another issue in which when I am running commands like vault mounts. It is throwing following error

Error reading mounts: Error making API request.

URL: GET https://*******:8200/v1/sys/mounts
Code: 400. Errors:

* missing client token

**Comment by jefferai** [comment]
`vault auth` or set `VAULT_TOKEN`.

If you need further help with usage, please use the mailing list at https://groups.google.com/forum/#!forum/vault-tool

Thanks!
