### ISSUE TITLE
AppRole secret storage

### ISSUE THREAD

**Issue by nikoncode** [hashicorp/vault#2933]
Hey guys. 

I have more question than issue. I have a java application and it tie to approle model.

I have only one question, approle requires roleId and secretId (if enabled) how to store secretId or authenticate safe? Cause as I understand loosing roleId and secretId absolutely equivalent of loosing all data available with this pair.

Thanks a lot.

**Comment by jefferai** [comment]
Hi @nikoncode ,

Please use the Vault mailing list (https://groups.google.com/forum/#!forum/vault-tool) for questions; we try to keep the issue tracker reserved for bugs/issues/feature requests/PRs.

There are a lot of knowledgeable people on the list that have tackled this problem in various ways in different setups/environments and posting there will get more eyes on the question.

Thanks!
