### ISSUE TITLE
Add option for setting name constraints on TLS CA certs (pki backend)

### ISSUE THREAD

**Issue by benjumanji** [hashicorp/vault#2939]
It would be truly rad if https://tools.ietf.org/html/rfc5280#section-4.2.1.10 was supported. Use case: we want to have a subca for generating certificates for our private openstack cloud which sits on a subdomain. It would be great if we could get an intermediate only valid for that subdomain.

**Comment by chrishoffman** [comment]
Do you want to generate a CA cert to be used outside of Vault or generate your certs within Vault?  There are already quite a few options to restrict domains/subdomains within the certificate roles.  Will this suffice?

https://www.vaultproject.io/api/secret/pki/index.html#allowed_domains

**Comment by benjumanji** [comment]
This is more about attesting to the signer of the CSR that we will not be doing anything naughty. Yes, as it stands I can make a role that only issues certs for the subdomain, add we have tested this successfully. It would make the ops team in the larger org happy if they could  make sure that even in the presence of extreme operator stupidity the intermediate can't be used to issue certs outside of its scope. Of course, we can do all this stuff ourselves then load the certs into vault and shred them, so this isn't a game breaker, it would just be neat if vault could do that for us.

**Comment by jefferai** [comment]
@benjumanji I think this would be nice and we'll schedule it for a near-term (likely will fall off the next release) version. If you're interested in working on a PR it would expedite things :-)

**Comment by jefferai** [comment]
This came out in 0.8.1!

**Comment by benjumanji** [comment]
Yaaaasssss!

**Comment by jpillora** [comment]
FYI, it appears this option is https://www.vaultproject.io/api-docs/secret/pki#permitted_dns_domains
