### ISSUE TITLE
s/-addr/-address

### ISSUE THREAD

**Issue by whit537** [hashicorp/vault#294]
Follow-on from #281 ...

> I think the issue is the ordering of arguments here.

I did try it with different ordering, turns out I wasn't seeing the more relevant error (I lost it in the help text):

```
$ vault write -addr=http://127.0.0.1:8200 secret/foo bar=baz   
flag provided but not defined: -addr
[...]
```

The help mentions `-address`, and indeed, that works:

```
$ vault write -address=http://127.0.0.1:8200 secret/foo bar=baz   
Success! Data written to: secret/foo
```

:dancer:

**Comment by sethvargo** [comment]
Hi @whit537 

This was fixed in master https://github.com/hashicorp/vault/commit/f0520916d6c8b83483fb20f343621966da945411#diff-5b4f052d557bcd66021311759582f972. Thanks!

**Comment by whit537** [comment]
You're doing good work, @sethvargo! :-)
