### ISSUE TITLE
Both the deprecated as well as the new MySQL database plugin seem to have a problem with wildcards

### ISSUE THREAD

**Issue by siepkes** [hashicorp/vault#2940]
When creating a role with a wildcard in its grant statement I can't retrieve DB credentials from Vault. For example I can't obtain credentials from Vault for the following role:

```
vault write database/roles/phabricator \
      db_name=mysql-misc \
      creation_statements="CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}'; GRANT ALL ON phabricator%.* TO '{{name}}'@'%';" \
      default_ttl="1h" \
      max_ttl="24h"
```

The above role will produce the following error when I try to obtain credentials via Consul Template: 

```
017/06/29 13:32:46.792100 [WARN] (view) vault.read(database/creds/phabricator): Error making API request.

URL: GET https://active.vault.service.nl1.consul.foo.bar:8200/v1/database/creds/phabricator
Code: 500. Errors:

* 1 error occurred:

* Error 1046: No database selected (retry attempt 4 after "2s")
```
Manually trying to obtain credentials with curl gives the same result:
```
# curl --header "X-Vault-Token: ${VAULT_TOKEN}"  http://127.0.0.1:8200/v1/database/creds/phabricator
{"errors":["1 error occurred:\n\n* Error 1046: No database selected"]}
```

The deprecated MySQL version would immediately fail. The new MySQL plugin allows you to create the role but gives the same error when retrieving the credentials.

When I remove the wildcard from the grant Vault (so `GRANT ALL ON phabricator.* TO '{{name}}'@'%';`) I can obtain credentials without any problems.

**Comment by jefferai** [comment]
Hi there,

I think you might be running into some shell interpolation issues. This is why we added the ability to pass in the creation statements in alternate ways:

`Specifies the database statements executed to create and configure a user. Must be a semicolon-separated string, a base64-encoded semicolon-separated string, a serialized JSON string array, or a base64-encoded serialized JSON string array. The '{{name}}' and '{{password}}' values will be substituted.`

Try putting your statements in a file, base64-encoding the file, and submitting the result as the creation sql.

**Comment by siepkes** [comment]
I'll give that a shot and report back!

**Comment by siepkes** [comment]
After some troubleshooting I figured out what the problem was. In order to create a query like this you need to enclose it with ticks. The [MySQL docs](https://dev.mysql.com/doc/refman/5.6/en/grant.html) don't explicitly say this but it is visible in the example (see the last line): 

> The _ and % wildcards are permitted when specifying database names in GRANT statements that grant privileges at the database level. This means, for example, that if you want to use a _ character as part of a database name, you should specify it as \_ in the GRANT statement, to prevent the user from being able to access additional databases matching the wildcard pattern; for example, GRANT ... ON \`foo\_bar\`.* TO ....

Now this leads to the next problem that Bash won't be happy when using this command:

```
vault write database/roles/phabricator \
      db_name=mysql-misc \
      creation_statements="CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}'; GRANT ALL ON `phabricator\_%`.* TO '{{name}}'@'%';" \
      default_ttl="1h" \
      max_ttl="24h"
```

Bash will try to execute the part between the ticks and die with:
```
-bash: phabricator_%: command not found
```

Encoding it as a Base64 string solved my problem.

I think this might be worth mentioning in the MySQL plugin docs to prevent other unwary travelers from falling in this pit ;-)

**Comment by siepkes** [comment]
BTW let me know if you want to add it to the docs (for example here: https://www.vaultproject.io/docs/secrets/databases/mysql-maria.html ) and i'll make a pull request.

**Comment by jefferai** [comment]
Sure, adding some clarification would be great!

**Comment by jefferai** [comment]
Closing this for now, will look forward to a PR with your suggested clarifications.
