### ISSUE TITLE
Mount command failing

### ISSUE THREAD

**Issue by safdaram** [hashicorp/vault#2943]
hi
I am using the following command to mount but am failing to mount if I use local, but it mounts if I use generic.
I could not find any documentation for this.  Could you point me to the documentaion. 
Thanks Amer.

vault mount -path=/tmp/asafdar generic

[root@RAC1 tmp]# vault mount -path=/tmp/asafdar generic
Successfully mounted 'generic' at '/tmp/asafdar'!
[root@RAC1 tmp]# vault mounts
Path          Type       Default TTL  Max TTL  Force No Cache  Replication Behavior  Description
tmp/asafdar/  generic    system       system   false           replicated

**Comment by jefferai** [comment]
This looks like it is behaving normally. What error are you seeing, from what command?

**Comment by safdaram** [comment]
Its lists out the long output, with the usage
and then at the end
"mount expects one argument: the type to mount."

How can I mount it as type local

**Comment by jefferai** [comment]
Local isn't a type, it's a flag. Are you a Vault Enterprise user?

**Comment by safdaram** [comment]
Yes I am

**Comment by safdaram** [comment]
But a new user, could u please also point me to the documentation besides getting stared guide.
Thanks Amer.

**Comment by jefferai** [comment]
Hi, you can use the `-local` flag to the `vault mount` command. See `vault mount -h` for help.

I asked about VE because local has no purpose in the OSS version.
