### ISSUE TITLE
Unable to start vault server

### ISSUE THREAD

**Issue by safdaram** [hashicorp/vault#2944]
I am unable to start vault server with out the -dev switch:
vault server -dev
This will start the server in -dev mode
But if I try the following it fails:
vault init -key-shares=5 -key-threshold=5
with error
Error initializing Vault: Put http://127.0.0.1:8200/v1/sys/init: dial tcp 127.0.0.1:8200: getsockopt: connection refused
I do export the " export VAULT_ADDR='http://127.0.0.1:8200' "
But that does not helps!!!

Thanks Amer.

**Comment by mlakewood** [comment]
1. Can you paste your vault configuration file.
2. does vault status return anything different?

**Comment by joelthompson** [comment]
Also, can you paste the output from `vault server -dev`?

But, I'm confused as to why you're trying to do this. You shouldn't need to do `vault init` when you do a `vault server -dev` -- the `-dev` mode implies an init with -key-shares=1 and -key-threshold=1

Can you explain your use case a bit more?

**Comment by safdaram** [comment]
I am pasting the output of the command:
[root@RAC1 ~]# vault server -dev
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
        Redirect Address: http://127.0.0.1:8200
                 Storage: inmem
                 Version: Vault v0.7.3
             Version Sha: 0b20ae0b9b7a748d607082b1add3663a28e31b68

==> WARNING: Dev mode is enabled!

In this mode, Vault is completely in-memory and unsealed.
Vault is configured to only have a single unseal key. The root
token has already been authenticated with the CLI, so you can
immediately begin using the Vault CLI.

My objective is to have five key shares?  
How can I achieve that.
Thanks Amer.

**Comment by jefferai** [comment]
You need to start the server without the dev flag, so that it is in normal operation.

**Comment by safdaram** [comment]
The following command fails:
[root@RAC1 ~]# vault init -key-shares=5 -key-threshold=5
Error initializing Vault: Put https://127.0.0.1:8200/v1/sys/init: dial tcp 127.0.0.1:8200: getsockopt: connection refused

**Comment by jefferai** [comment]
Vault appears to not be running. Vault does not daemonize, ensure you are not closing it after starting it.

**Comment by safdaram** [comment]
I get the following error with the config file which I am using, is it a must to use a consul backend?

[root@RAC1 ~]# vault server -config=/tmp/server_config.hcl
Error detecting redirect address: Get http://127.0.0.1:8500/v1/agent/self: dial tcp 127.0.0.1:8500: getsockopt: connection refused
Error initializing core: missing redirect address

Content of my config file:
[root@RAC1 tmp]# cat server_config.hcl
storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault"
}

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = 1
}

**Comment by chrishoffman** [comment]
No, you can use any storage backend that vault supports.  See https://www.vaultproject.io/docs/configuration/storage/index.html. 

If you just want to use in-memory like in dev mode, you can replace your consul storage block with:

```
storage inmem {}
```

**Comment by chrishoffman** [comment]
I mean `storage "inmem" {}`.

**Comment by safdaram** [comment]
Hi Chris,
Is there any document or url, which I can follow?  which would be a lot more efficient.  
I am a new user and trying to set it up for the first time.
Thanks Amer.

**Comment by chrishoffman** [comment]
There is an interactive tutorial available on https://www.vaultproject.io/ <https://www.vaultproject.io/> and I would recommend going through the getting started guides here https://www.vaultproject.io/intro/getting-started/install.html <https://www.vaultproject.io/intro/getting-started/install.html>.  Also, the mailing list is a great place to ask or get answers to questions along the way.

**Comment by safdaram** [comment]
Chris,
Which mailing list are you referring to, for posting questions.
Thanks Amer.

**Comment by chrishoffman** [comment]
Here is a link to the vault mailing list.
https://groups.google.com/group/vault-tool <https://groups.google.com/group/vault-tool>

**Comment by JosifKovacevic** [comment]
Again same error:
Error initializing: Put http://127.0.0.1:8200/v1/sys/init: dial tcp 127.0.0.1:8200: connect: connection refused
In my case all prerequisites are in place: vault started, exported VAULT_ADDR variable,... but "vault operator init" and "vault status" both produce the same error "connection refused"

**Comment by yeukhon** [comment]
@JosifKovacevic you are not the only one. I am so sighed most of the docker images of popular OSS seem broken...

**Comment by jefferai** [comment]
@yeukhon The image isn't broken

**Comment by tigerrabbit** [comment]
I was able to recreate the error above by starting the dev server using sudo, but trying to add secrets as my regular user.  To avoid the problem I started the dev server with my regular account and the problem disappeared.
