### ISSUE TITLE
vault read aws/creds error

### ISSUE THREAD

**Issue by safdaram** [hashicorp/vault#2947]
Hi,  I am getting an error while reading from aws/creds/amer_developer.  How can I resolve this read error?

[root@RAC1 tmp]# vault write aws/config/root access_key=amer_aws_user secret_key=amer_aws_user region=us-west-2
Success! Data written to: aws/config/root
[root@RAC1 tmp]# vault write aws/config/lease lease=5m lease_max=24h
Success! Data written to: aws/config/lease
[root@RAC1 tmp]# vi policy.json
[root@RAC1 tmp]# vault write aws/roles/amer_developer policy=@policy.json
Success! Data written to: aws/roles/amer_developer
[root@RAC1 tmp]# vault read aws/creds/amer_developer
Error reading aws/creds/amer_developer: Get http://127.0.0.1:8200/v1/aws/creds/amer_developer: net/http: request canceled (Client.Timeout exceeded while awaiting headers

**Comment by jefferai** [comment]
Likely the issue is one of two things: one, the call to the AWS API itself is taking a very long time, to the point where the client timeout is exceeded; two, Vault is throwing an error but only in its logs, so that would be a good place to look.

**Comment by jefferai** [comment]
Closing due to lack of response.
