### ISSUE TITLE
Use STS for AWS

### ISSUE THREAD

**Issue by benmccann** [hashicorp/vault#295]
One the announcement thread on HN, there was a good question, which wasn't answered and I'm curious about myself

>[Any reason why AWS dynamic credentials use IAM users instead of STS and role assumption? That seems to be a somewhat more widely accepted way to do dynamic credentials / role proxying.](https://news.ycombinator.com/item?id=9453953)

**Comment by armon** [comment]
@benmccann When we started the AWS secret backend, there was much broader client support for using native access keys instead of STS tokens. We plan on supporting STS eventually, but almost any client that supports STS supports tokens, but not the inverse.

**Comment by moofish32** [comment]
With STS the revocation ability is slightly different and if you need to revoke immediately you actually have to destroy the user that is currently assuming role. If Vault transitions to assume role usage, are people willing to accept that modification? 

Has anyone had a conversation with Amazon about increasing the IAM user limits?

**Comment by jefferai** [comment]
STS is now supported via #927.
