### ISSUE TITLE
Self-signed certificate with HA not able to communicate

### ISSUE THREAD

**Issue by mlakewood** [hashicorp/vault#2951]
Hi,

Im attempting to setup vault with a HA configuration with a consul backend. At the moment Im using self-signed keys. Im using vault 0.7.3 and consul 0.8.0. All code can be found here -> https://github.com/mlakewood/tempest/tree/master/tests/data

I have added the self-signed root cert to the system certs and this gets the cli working, both from my dev machine and between the primary and standby see:

```
bash-4.3# export VAULT_ADDR=https://10.0.0.30:8200
bash-4.3# vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Unseal Nonce:
Version: 0.7.3
Cluster Name: vault-cluster-4689b93b
Cluster ID: 654d63a9-ea54-f579-d1f9-abebe83acae3

High-Availability Enabled: true
	Mode: active
	Leader: https://10.0.0.6:8200
bash-4.3# ^C
bash-4.3# exit
Marks-MacBook-Pro-3:tls underplank$ docker exec -it vault_vault_1_1 /bin/bash
bash-4.3# export VAULT_ADDR=https://10.0.0.31:8200
bash-4.3# vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Unseal Nonce:
Version: 0.7.3
Cluster Name: vault-cluster-4689b93b
Cluster ID: 654d63a9-ea54-f579-d1f9-abebe83acae3

High-Availability Enabled: true
	Mode: standby
	Leader: https://10.0.0.6:8200
```

However when I query the standby for a key using the cli I get the following in the logs.

```
vault_1_1         | 2017/06/30 21:37:25 http: TLS handshake error from 10.0.0.31:49824: remote error: tls: bad certificate
vault_1_1         | 2017/06/30 21:39:46 http: TLS handshake error from 10.0.0.31:49890: remote error: tls: bad certificate
vault_2_1         | 2017/06/30 21:39:46.754814 [WARN ] grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing x509: certificate signed by unknown authority"; Reconnecting to {vault_vault_1_1:8200 <nil>}
```

where `vault_1_1` is the primary and `vault_2_1` is the standby.

As the cli is working from both of these hosts the system contains the correct root cert. But it seems like the grpc communication between the primary and the standby is not working?

Any hints on where it gets its certificate chains from?

Thanks

Mark

**Comment by mlakewood** [comment]
The commands I specifically after an unseal are

```
Marks-MacBook-Pro-3:data underplank$ export VAULT_ADDR=https://127.0.0.1:1234
Marks-MacBook-Pro-3:data underplank$ ./vault write secret/hello value=foo
Success! Data written to: secret/hello
Marks-MacBook-Pro-3:data underplank$ ./vault read secret/hello
Key             	Value
---             	-----
refresh_interval	768h0m0s
value           	foo

Marks-MacBook-Pro-3:data underplank$ export VAULT_ADDR=https://127.0.0.1:1235
Marks-MacBook-Pro-3:data underplank$ ./vault read secret/hello
Error reading secret/hello: Get https://10.0.0.5:8200/v1/secret/hello: dial tcp 10.0.0.5:8200: i/o timeout
Marks-MacBook-Pro-3:data underplank$
```

and the log output is
```
vault_1_1         | 2017/06/30 22:10:25 http: TLS handshake error from 10.0.0.31:50946: remote error: tls: bad certificate
vault_2_1         | 2017/06/30 22:10:25.718232 [WARN ] grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing x509: certificate signed by unknown authority"; Reconnecting to {vault_vault_1_1:8200 <nil>}
vault_2_1         | 2017/06/30 22:11:26.390461 [ERROR] core: error during forwarded RPC request: error=rpc error: code = Unavailable desc = grpc: the connection is unavailable
vault_2_1         | 2017/06/30 22:11:26.390881 [ERROR] http/handleRequestForwarding: error forwarding request: error=error during forwarding RPC request
vault_1_1         | 2017/06/30 22:11:36 http: TLS handshake error from 10.0.0.31:50986: remote error: tls: bad certificate
vault_2_1         | 2017/06/30 22:11:36.944631 [WARN ] grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing x509: certificate signed by unknown authority"; Reconnecting to {vault_vault_1_1:8200 <nil>}
```

everything you need to reproduce is in the repo linked above.

**Comment by jefferai** [comment]
Can you post your configuration from each node and the output Vault prints when first starting from each node?

**Comment by mlakewood** [comment]
@jefferai All configuration is in this repo -> https://github.com/mlakewood/tempest/tree/master/tests/data

for vault configuration the files are https://github.com/mlakewood/tempest/blob/master/tests/data/config/vault-1/config.hcl and https://github.com/mlakewood/tempest/blob/master/tests/data/config/vault-2/config.hcl respectively.

If you have docker you can just do a `docker-compose -f tests/data/docker-compose.yml up` to recreate. Below is the log output from the two vault services.

primary:
```
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://vault_vault_1_1:8200
              Listener 1: tcp (addr: "vault_vault_1_1:8200", cluster address: "10.0.0.30:8201", tls: "enabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
        Redirect Address: https://10.0.0.5:8200
                 Storage: consul (HA available)
                 Version: Vault v0.7.3
             Version Sha: 0b20ae0b9b7a748d607082b1add3663a28e31b68

==> Vault server started! Log data will stream in below:

2017/06/30 22:32:09.476229 [WARN ] physical/consul: appending trailing forward slash to path
```

secondary

```
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://vault_vault_2_1:8200
              Listener 1: tcp (addr: "vault_vault_2_1:8200", cluster address: "10.0.0.31:8201", tls: "enabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
        Redirect Address: https://10.0.0.6:8200
                 Storage: consul (HA available)
                 Version: Vault v0.7.3
             Version Sha: 0b20ae0b9b7a748d607082b1add3663a28e31b68

==> Vault server started! Log data will stream in below:

2017/06/30 22:32:10.486894 [WARN ] physical/consul: appending trailing forward slash to path
```

Thanks.

Mark

**Comment by jefferai** [comment]
Your cluster addresses that you are specifying are on the wrong port; it should be port 8201. That should fix your issue.

It's also curious that your redirect address and cluster address are so different. You may want to set them specifically. Note the difference between address/cluster_address in the listener block (which set the actual listener addresses, see https://www.vaultproject.io/docs/configuration/listener/tcp.html#cluster_address) and the values in the storage block which set what the nodes advertise to each other, which can actually be a different path if you want to e.g. have them go through a load balancer (https://www.vaultproject.io/docs/configuration/storage/consul.html#cluster_addr)

**Comment by mlakewood** [comment]
Fixing the port seems to have fixed the issue. 

The redirect Address is a bit wierd. Im not sure where its getting that from as I havent set it anywhere? How does that get populated?

**Comment by jefferai** [comment]
Depending on which storage backend is being used it can try to autodetect. When Consul is in use, because the local Consul agent has knowledge of the system's IP address and/or an accessible name for the host, it tries to construct it from Consul's information. It doesn't always get it right though.

**Comment by mlakewood** [comment]
Ahh that would make sense. Because of <reasons> I have the local consul agent running in a different container, with a different IP address, so it was using that instead of the IP address of the vault instance. All makes sense now. Thanks for your help.
