### ISSUE TITLE
Support Casbin as the authorization module

### ISSUE THREAD

**Issue by hsluoyz** [hashicorp/vault#2959]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security than the current ACL. I can make PR if needed. Let me know if there's any question:) Thanks.

**Comment by jefferai** [comment]
Hi @hsluoyz ,

At this time we don't want to add another authz system into Vault. Thanks though!
