### ISSUE TITLE
etcd HA

### ISSUE THREAD

**Issue by benmccann** [hashicorp/vault#296]
I'd love to see HA for the etcd backend. My understanding is that etcd provides leader election and as a result it should be possible to make it HA. I'm curious what needs to be done for this.

**Comment by sethvargo** [comment]
Hi @benmccann 

The original etcd backend was contributed by the community (see https://github.com/hashicorp/vault/pull/259). The original author expressed interest in extending this to support HA eventually.

Tagged as enhancement.

**Comment by benmccann** [comment]
Looks like there's a PR for this here: https://github.com/hashicorp/vault/pull/297
