### ISSUE TITLE
List mounts as user

### ISSUE THREAD

**Issue by DaspawnW** [hashicorp/vault#2961]
Is it possible to list all mounts I have access to, as normal user?
As root it is possible to read mounts with `vault mounts`, but what about a simple user without root access.
Is there a policy to get rights to do so?

Thanks, Cheers,
Björn

**Comment by calvn** [comment]
That's correct. You would need "read" policy on the `sys/mounts` path.

```hcl
path "sys/mounts" {
    policy = "read"
}
```
