### ISSUE TITLE
Recommended practice for storing data

### ISSUE THREAD

**Issue by mukgupta** [hashicorp/vault#2968]
Hi,

I want to understand what is the best/recommended way to store the database information inside the vault among the following options.

a) Store db username, password, dbname, host, port.   
 **Pros**: All info accessible at one path, easy to share. 
 **Cons**: Since vault api doesn't have patch support, you need to pass multiple values(host/port) even if you want to change just password. 

b) Store only username, password inside DB.
**Pros**: Easy to update since only username/password needs to be passed.
**Cons**: Maintain separate data sources for secret and non-secret info.

**Comment by jefferai** [comment]
Hi @mukgupta ,

GitHub is meant to be used for issues/bugs, pull requests, and other dev activity. Please use the mailing list (https://groups.google.com/forum/#!forum/vault-tool) for questions.

Thanks!
