### ISSUE TITLE
Vault + Consul in AWS behind ELB: TLS handshake errors

### ISSUE THREAD

**Issue by den-is** [hashicorp/vault#2981]
I'm trying to setup vault cluster behind LoadBalancer in my vpc.
This VPC is already running Consul cluster behind LoadBalancer. TLS only, plain HTTP is disabled.

consul config
```json
{
    "acl_agent_token": null,
    "acl_datacenter": "aws-east",
    "acl_default_policy": "deny",
    "acl_down_policy": "extend-cache",
    "acl_master_token": "asjkfhskvbksbnvwk",
    "acl_replication_token": null,
    "acl_token": "fsjkhfklashfljks",
    "bootstrap_expect": 3,
    "ca_file": "/etc/pki/consul/ca.pem",
    "cert_file": "/etc/pki/consul/cert.pem",
    "client_addr": "0.0.0.0",
    "data_dir": "/var/lib/consul",
    "datacenter": "aws-east",
    "disable_remote_exec": true,
    "encrypt": "encryptstring",
    "key_file": "/etc/pki/consul/key.pem",
    "log_level": "INFO",
    "ports": {
        "http": -1,
        "https": 8500
    },
    "retry_join_ec2": {
        "tag_key": "consul",
        "tag_value": "prod-cluster"
    },
    "server": true,
    "statsd_addr": "127.0.0.1:8125",
    "ui": true,
    "verify_incoming": false,
    "verify_incoming_rpc": true,
    "verify_outgoing": true
}
```

vault config:
```json
{
  "backend": {
    "consul": {
      "address": "consul.aws.domain.com",
      "path": "vault/",
      "scheme": "https",
      "redirect_addr" : "https://vault.aws.domain.com"
      "tls_ca_file": "/etc/pki/vault/ca.pem",
      "tls_cert_file": "/etc/pki/vault/cert.pem",
      "tls_key_file": "/etc/pki/vault/key.pem",
      "token": "3254783t8uy89hgfihgs"
    }
  },
  "disable_mlock": false,
  "listener": {
    "tcp": {
      "address": "0.0.0.0:8200",
      "tls_cert_file": "/etc/pki/vault/cert.pem",
      "tls_key_file": "/etc/pki/vault/key.pem"
    }
  }
}
```
both cert.pem are different certificates signed by same CA.

These are errors I'm getting:
```
Jul 06 16:17:59 ip-10-70-124-169 systemd[1]: Starting Vault server...
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: ==> Vault server configuration:
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: Cgo: disabled
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: Cluster Address: https://vault.aws.domain.com:444
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "enabled")
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: Log Level: trace
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: Mlock: supported: true, enabled: true
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: Redirect Address: https://vault.aws.domain.com
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: Storage: consul (HA available)
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: Version: Vault v0.7.3
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: Version Sha: 0b20ae0b9b7a748d607082b1add3663a28e31b68
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: ==> Vault server started! Log data will stream in below:
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: 2017/07/06 16:17:59.389922 [DEBUG] physical/consul: config path set: path=vault/
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: 2017/07/06 16:17:59.389995 [DEBUG] physical/consul: config disable_registration set: disable_registration=false
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: 2017/07/06 16:17:59.390003 [DEBUG] physical/consul: config service set: service=vault
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: 2017/07/06 16:17:59.390007 [DEBUG] physical/consul: config service_tags set: service_tags=
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: 2017/07/06 16:17:59.390015 [DEBUG] physical/consul: config address set: address=consul.aws.domain.com
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: 2017/07/06 16:17:59.390020 [DEBUG] physical/consul: config scheme set: scheme=https
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: 2017/07/06 16:17:59.390023 [DEBUG] physical/consul: config token set
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: 2017/07/06 16:17:59.390520 [DEBUG] physical/consul: configured TLS
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: 2017/07/06 16:17:59.390563 [TRACE] physical/cache: creating LRU cache: size=32768
Jul 06 16:17:59 ip-10-70-124-169 vault[25432]: 2017/07/06 16:17:59.396680 [TRACE] cluster listener addresses synthesized: cluster_addresses=[0.0.0.0:8201]
Jul 06 16:18:04 ip-10-70-124-169 vault[25432]: 2017/07/06 16:18:04.222656 [WARN ] physical/consul: check unable to talk with Consul backend: error=Unexpected response code: 500 (Unknown check "vault::443:vault-sealed-check")
Jul 06 16:18:07 ip-10-70-124-169 vault[25432]: 2017/07/06 16:18:07 http: TLS handshake error from 10.70.124.146:5274: EOF
Jul 06 16:18:08 ip-10-70-124-169 vault[25432]: 2017/07/06 16:18:08.922965 [WARN ] physical/consul: check unable to talk with Consul backend: error=Unexpected response code: 500 (Unknown check "vault::443:vault-sealed-check")
Jul 06 16:18:12 ip-10-70-124-169 vault[25432]: 2017/07/06 16:18:12 http: TLS handshake error from 10.70.125.15:48776: EOF
Jul 06 16:18:13 ip-10-70-124-169 vault[25432]: 2017/07/06 16:18:13.670024 [WARN ] physical/consul: check unable to talk with Consul backend: error=Unexpected response code: 500 (Unknown check "vault::443:vault-sealed-check")
```
And I don't understand well which part fails which certificates to check.
log-level TRACE
certificate has CN=vault.aws.domain.com 

UPD 
Okay, for test purposes I've removed LoadBalancer from my topology and figured out that maybe I had to run vault init. No more TLS handshake errors.
```
Error initializing Vault: Put https://127.0.0.1:8200/v1/sys/init: x509: certificate is valid for 10.70.124.169, not 127.0.0.1
```
So here is the question: certificate has to include every IP of vault node and LoadBalancer for successful intercommunication ? 
10.20.12[4,5].0/24 are two dynamic AWS subnets dedicated for vault setup.
10.70.124.169 - is vault server.
other 10.70.124 and 10.70.125 are dynamic IPs assigned to LoadBalancer of this subnet.
TLS hasndshake errors in very first error output above, are comming from loadbalncer - this means that certificate has to include IP addresses of loadbalancer ? Also what type of communication is trying to occur so loadbalancer can't authorize request against specific vault server?

**Comment by jefferai** [comment]
The 500 errors you're seeing are likely because you're pointing your Vaults at your Consul servers. They're meant to be pointed at your local Consul agents, because health checks are per-node.

**Comment by den-is** [comment]
OMG!!! Thank you, that helped!
But documentation is not stating about this clearly.

What about errors which I see when i want to setup vault behind dynamic aws ELB.

```
Jul 07 16:06:47 ip-10-70-124-169 vault[3450]: 2017/07/07 16:06:47 http: TLS handshake error from 10.70.125.182:38278: EOF
Jul 07 16:06:58 ip-10-70-124-169 vault[3450]: 2017/07/07 16:06:58 http: TLS handshake error from 10.70.124.205:44320: EOF
Jul 07 16:07:02 ip-10-70-124-169 vault[3450]: 2017/07/07 16:07:02 http: TLS handshake error from 10.70.125.182:38290: EOF
```

Vault works only if IPs are in SAN of cert ?

**Comment by viralpoetry** [comment]
@den-is 
You are correct. Vault TLS cert must contain correct SAN value. Not sure about aws ELB, but for HAProxy, I had to do raw TCP proxy for Vault HTTPS traffic. Otherwise, the overall system security is downgraded to the LB interception.

**Comment by den-is** [comment]
Yeah, AWS' ELB is not much suitable for Vault service.
As Vaults HA mostly depends on underlying storage and not vault instance itself - I've left only one vault instance running for now.
Closing the issue.

**Comment by jefferai** [comment]
@den-is ELB is used by many people with Vault without issues. If your ELB is forwarding to IP addresses then you do need the IP addresses in your certs, but most people use host names.

**Comment by den-is** [comment]
@jefferai I don't like this approach much. AWS environment is dynamic. One day I will have to reinstall machine, and then will have to regenerate cert with new hostname cert.
And yes there are options like `preserve_hostname` which I will review - but in general I prefer not to use such "hax". HAproxy solution maybe lil bit more flexible compared to ELB.
Or again, I'm missing something and overcomplicating.

**Comment by jefferai** [comment]
If you're using ELB in TCP mode, the underlying TLS connection is not modified (which is also the more secure way to use ELB). So if your certificate has a common name across all the Vault servers then any of them can handle the connection.

Not sure what preserve_hostname is but my guess is that it keeps the SNI header when using non TCP mode. I wouldn't consider that a hack at all, personally.

**Comment by den-is** [comment]
@jefferai okay, you made me to look on problem lil bit closer. lol :D
And I solved it, thanks to this guys comment https://github.com/hashicorp/vault/issues/1194#issuecomment-256635483
I was using TCP health-check instead of HTTPS.
now when I started using HTTPS:8200/v1/sys/health everything works.
