### ISSUE TITLE
hashicorp/vault make error on AWS linux server 

### ISSUE THREAD

**Issue by jssul01** [hashicorp/vault#2988]
I am trying to compile the new source code onto my aws linux server. After installing Go and setting up the go env variables (GOPATH, GOROOT and PATH). I cloned the vault repo into $GOPATH/src/github.com/hashicorp/vault.
1.make bootstrap - was successful and I checked the bin folder to verify if godep was installed.
2.make - failed 

Here is the output,

[root@ip-172-31-10-43 vault]# make dev
==> Checking that code complies with gofmt requirements...
go generate
==> Removing old directory...
==> Building...
Number of parallel builds: 1

-->     linux/amd64: github.com/hashicorp/vault

1 errors occurred:
--> linux/amd64 error: exit status 2
Stderr: # github.com/hashicorp/vault/vendor/github.com/coreos/etcd/pkg/transport
vendor/github.com/coreos/etcd/pkg/transport/listener.go:180: cfg.GetClientCertificate undefined (type *tls.Config has no field or method GetClientCertificate)
vendor/github.com/coreos/etcd/pkg/transport/listener.go:180: undefined: tls.CertificateRequestInfo
vendor/github.com/coreos/etcd/pkg/transport/listener_tls.go:151: undefined: net.DefaultResolver in net.DefaultResolver.LookupHost

make: *** [dev] Error 1

Any idea why this is happening ?

**Comment by jefferai** [comment]
Go 1.8 is required to build Vault.

**Comment by jssul01** [comment]
I'm trying to the build and make for the vault but i get the same resulted 

_### [root@ip-172-31-10-43 vault]# go build github.com/hashicorp/vault
# github.com/hashicorp/vault/vendor/github.com/coreos/etcd/pkg/transport
vendor/github.com/coreos/etcd/pkg/transport/listener.go:180: cfg.GetClientCertificate undefined (type *tls.Config has no field or method GetClientCertificate)
vendor/github.com/coreos/etcd/pkg/transport/listener.go:180: undefined: tls.CertificateRequestInfo
vendor/github.com/coreos/etcd/pkg/transport/listener_tls.go:151: undefined: net.DefaultResolver in net.DefaultResolver.LookupHost
[root@ip-172-31-10-43 vault]# make
==> Checking that code complies with gofmt requirements...
go generate
==> Removing old directory...
==> Building...
Number of parallel builds: 1

-->     linux/amd64: github.com/hashicorp/vault

1 errors occurred:
--> linux/amd64 error: exit status 2
Stderr: # github.com/hashicorp/vault/vendor/github.com/coreos/etcd/pkg/transport
vendor/github.com/coreos/etcd/pkg/transport/listener.go:180: cfg.GetClientCertificate undefined (type *tls.Config has no field or method GetClientCertificate)
vendor/github.com/coreos/etcd/pkg/transport/listener.go:180: undefined: tls.CertificateRequestInfo
vendor/github.com/coreos/etcd/pkg/transport/listener_tls.go:151: undefined: net.DefaultResolver in net.DefaultResolver.LookupHost

make: *** [dev] Error 1_

Please advice to me, any idea ... 
Thanks..

**Comment by jefferai** [comment]
What is the output of 'go version'?

**Comment by jssul01** [comment]
[root@ip-172-31-10-43 vault]# go version
go version go1.7.5 linux/amd64

**Comment by jefferai** [comment]
See https://github.com/hashicorp/vault/issues/2988#issuecomment-313850974

**Comment by jefferai** [comment]
Go 1.8 is required to build Vault.
