### ISSUE TITLE
how to connect to an HA vault using zookeeper as backend?

### ISSUE THREAD

**Issue by amugit2013** [hashicorp/vault#2989]
I deployed vault with HA mode using zookeeper as backend. Did vault register itself to zookeeper to show it's available? how can I find a healthy node to access when some node is down?

here is configuration of one node:
```
backend "zookeeper" {
  # zk server
  address = "10.0.0.1:2181,10.0.0.2:2181"
  redirect_addr = "http://10.0.1.1:8200"
  # zk path
  path = "vault/"
}

listener "tcp" {
  address = "10.0.1.1:8200"
  tls_disable = 1
}

disable_mlock = true
```

**Comment by raoofm** [comment]
@amugit2013 
You can do that using vault's leader API

$ curl http://10.0.1.2:8200/v1/sys/leader
response will be something like
{
  "ha_enabled": true,
  "is_self": false,
  "leader_address": "http://10.0.1.1:8200/"
}

**or**

$ curl http://10.0.1.1:8200/v1/sys/leader
response will be something like
{
  "ha_enabled": true,
  "is_self": true,
  "leader_address": "http://10.0.1.1:8200/"
}

**Comment by amugit2013** [comment]
@raoofm 
Thanks for reply. 

I don't care which on is leader when 10.0.1.1 and 10.0.1.2 are both ok, because when I access one of then, vault will do redirect or forward and return the right response.

What I want to is get a healthy vault node to access even if  one of then is down without testing each node to get one available. 

vault write redirect_addr(zk backend config) to zookeeper, could I just get available node from zk(service discovery)?
