### ISSUE TITLE
Support for Freeipa - question

### ISSUE THREAD

**Issue by milan-koudelka** [hashicorp/vault#300]
Hi,
do you plan any support for freeipa integration. So every user/service/host can authorize itself by kerberos ticket ?

Thx.
Milan Koudelka

**Comment by neoice** [comment]
Kerberos as an Auth Backend would be amazing

**Comment by sethvargo** [comment]
Hi @milan-koudelka 

Thank you for opening an issue. We do not have plans to implement freeipa or kerberos support at this time. I have created #306 to track the kerberos authentication and would love your thoughts there. We will likely look to the community for such an implementation :smile:.
