### ISSUE TITLE
v0.6.0 -  x509: certificate signed by unknown authority when system CA is updated

### ISSUE THREAD

**Issue by brad-peters** [hashicorp/vault#3000]
Installing on RHEL 7.3 we have the following situation:
1. Create a CA key/cert using openssl
2. Using that CA generate tls key/cert for consul and vault to use
3. Place CA pem file in /etc/pki/ca-trust/source/anchors
4. Run ```update-ca-trust```
5. Configure consul and vault to use the generated tls key/cert
6. Everything works fine
7. Repeat steps 1-5 on the same machine with a new CA key/cert and tls key/cert
8. All calls using vault client return " x509: certificate signed by unknown authority"

We verified (using openssl verify) that the generated tls cert is valid for the CA cert and for the cabundle.crt on the system.  We also verified that the tls cert and key are a matched pair.

It appears (we are collected logs to confirm) that the vault server is some how "holding on" to the previous version of the tls cert.  When using consul backend, is that stored in consul anywhere?

We have tried everything we could think of to resolve this issue.  We copied a set of "bad" certs to working box and could not reproduce the issue.  Any help would be appreciated.

**Comment by jefferai** [comment]
Did you send a SIGHUP to Vault to have it re-read the PEM files for its TLS listeners?

Also, just a due diligence note: you should really upgrade from 0.6.0 as soon as you can. There have been several security fixes since then, both in Vault and the underlying Go libraries, plus a plethora of bug fixes.

**Comment by brad-peters** [comment]
Is the SIGHUP required if you do a restart?
We have upgraded to the latest version, but have past systems we are supporting.

**Comment by jefferai** [comment]
No, not if you do a restart.

**Comment by brad-peters** [comment]
Thanks for the help guys.  We determined we had some issues in our provisioner that was under some circumstances not updating the certs on the box or not reloading vault.
