### ISSUE TITLE
database backend with multiple mysql databases

### ISSUE THREAD

**Issue by hgschmie** [hashicorp/vault#3002]
We consider using vault for managing access to a set of mysql hosts with multiple databases. I am trying to figure out what the best way to configure the vault backend is. This is our scenario:

```
dbserver-west
 - mysql
 - prod_db_1
 - prod_db_2

dbserver-east
 - mysql
 - prod_db_3
 - prod_db_4
```

currently we have eight sets of credentials: 

- dbserver-west / db1 / db1_secret
- dbserver-west / db2 / db2_secret
- dbserver-east / db3 / db3_secret
- dbserver-east / db4 / db4_secret
- dbserver-west / db1ro / db1_secret_ro
- dbserver-west / db2ro / db2_secret_ro
- dbserver-east / db3ro / db3_secret_ro
- dbserver-east / db4ro / db4_secret_ro

my current thinking is:

```
% vault mount database
% vault write /database/config/dbserver-west plugin_name=mysql-database-plugin 'allowed_roles=*' 'connection_url=<admin_creds>@tcp(database-west:3306)/'
% vault write /database/config/dbserver-west plugin_name=mysql-database-plugin 'allowed_roles=*' 'connection_url=<admin_creds>@tcp(database-east:3306)/'
% vault write /database/roles/db1 db_name=dbserver-west "creation_statements=CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT ALL ON db1.* TO '{{name}}'@'%';"
% vault write /database/roles/db1-ro db_name=dbserver-west "creation_statements=CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT SELECT ON db1.* TO '{{name}}'@'%';"
% vault write /database/roles/db2 db_name=dbserver-west "creation_statements=CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT ALL ON db12* TO '{{name}}'@'%';"
% vault write /database/roles/db2-ro db_name=dbserver-west "creation_statements=CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT SELECT ON db2.* TO '{{name}}'@'%';"
% vault write /database/roles/db3 db_name=dbserver-east "creation_statements=CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT ALL ON db3.* TO '{{name}}'@'%';"
% vault write /database/roles/db3-ro db_name=dbserver-east "creation_statements=CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT SELECT ON db3.* TO '{{name}}'@'%';"
% vault write /database/roles/db4 db_name=dbserver-east "creation_statements=CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT ALL ON db4.* TO '{{name}}'@'%';"
% vault write /database/roles/db4-ro db_name=dbserver-east "creation_statements=CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT SELECT ON db4.* TO '{{name}}'@'%';"
```

but that feels pretty uneven. I have now mixed the roles (rw and ro) with the databases themselves.  Also, I need to give "allowed_roles=*" instead of e.g. "rw,ro".

I am trying to shoehorn a three level (database host / database / role) structure into a two level (`database/config/<xxx>` and `database/roles/<yyy>`) structure. This seems to be less than ideal. 

is there a better way to do this besides (ab)using the roles to select a specific database? All of the examples in the documentation use `GRANT <xxx> on *.*` for creation_statements which opens up access to all the databases on the database host, not just the one that I want to give access to.

**Comment by hgschmie** [comment]
Scenarios that we also thought through: 

- mount the database backend for each server: /database-east and /database-west instead of /database. Still mixes roles and databases themselves (as each database server has multiple databases)
- mount the database backend for each database: /db1, /db2 and so on. This seems feasible but somewhat cumbersome. Also, I have not found how many possible mounts a vault instance supports (this is the smallest example; the actual real world scenario has more servers and databases) or whether having many mounted backends (let's say high hundreds to low thousands) will be a problem for vault.

**Comment by jefferai** [comment]
We try to reserve GitHub for issues and PRs, and use the mailing list (https://groups.google.com/forum/#!forum/vault-tool) for questions. Please use that in the future -- as a side effect, other users that have experience with working with Vault and databases are more likely to respond there.

I'm not entirely sure I follow the issue here; when you say in your example that you have mixed the roles with the databases themselves I don't see where you're doing that, and when you say that you re required to use `allowed_roles=*` I don't see what's requiring you to do that either.

Regardless, mounting the database backend for each server seems like a fine approach to your issue.

**Comment by hgschmie** [comment]
ok, reposted to ml
