### ISSUE TITLE
iam_server_id_header_value not persisted after updating AWS client config

### ISSUE THREAD

**Issue by mp911de** [hashicorp/vault#3004]
AWS client config value `iam_server_id_header_value` is not persisted when updating the AWS client config. 

Vault version: Vault v0.7.3 ('0b20ae0b9b7a748d607082b1add3663a28e31b68')

```
$ vault write auth/aws/config/client iam_server_id_header_value=foo secret_key=… access_key=…
Success! Data written to: auth/aws/config/client

$ vault read auth/aws/config/client 
Key                       	Value
---                       	-----
access_key                	…
endpoint                  	
iam_endpoint              
iam_server_id_header_value	
secret_key                	…
sts_endpoint     
```

The `iam_server_id_header_value` value gets updates as soon as `iam_endpoint` gets included:

```
$ vault write auth/aws/config/client iam_server_id_header_value=foo secret_key=… access_key=… iam_endpoint=bar
Success! Data written to: auth/aws/config/client

$ vault read auth/aws/config/client 
Key                       	Value
---                       	-----
access_key                	…
endpoint                  	
iam_endpoint              	bar
iam_server_id_header_value	foo
secret_key                	…
sts_endpoint 
```

**Comment by jefferai** [comment]
I looked at the code and it's actually if (almost) any other value is set that value will be saved as well. But there's a note in the code saying that this is specifically the intended behavior (https://github.com/hashicorp/vault/blob/master/builtin/credential/aws/path_config_client.go#L214)

I'll need to reach out and figure out what the intention is there; maybe it's something we can issue a warning about.

**Comment by jefferai** [comment]
@joelthompson Looks like that block is your code, can you provide some insight?

**Comment by joelthompson** [comment]
Yeah, saw this earlier, will submit a PR tonight to fix.

Basically, in this case, we don't want to flush the cached AWS clients, but we do want to write the updated value back to the underlying storage. The existing code has a flag whose meaning is overloaded to both "flush the cached AWS clients" and "write the updated value back to the underlying storage." I was trying to avoid unnecessarily flushing the cached clients, but missed the part where that would also prevent it from getting written to the storage, and hence this bug.

**Comment by jefferai** [comment]
Gotcha. I guess it just means un-overloading the flag, either splitting it into a bit field or into two vars?

**Comment by joelthompson** [comment]
Yeah, I think that's pretty much it.
