### ISSUE TITLE
TLS Certificate Authentication Broken Behind NGINX

### ISSUE THREAD

**Issue by kareed44** [hashicorp/vault#3006]
I have a Vault instance that has "cert" authentication enabled. I injected a cert and can authenticate with it, no problem. However, when I put an Nginx instance in front of it for url rewrites, Nginx appears to terminate the client certificate, causing an error.

**Authentication call**
```
vault auth -address=https://test.ezesoft.net -method=cert -ca-cert="ca.crt" -client-cert="server.pem"  -client-key="server.key" name=testing
```

**Error**
```
Error making API request.

URL: PUT https://test.ezesoft.net/v1/auth/cert/login
Code: 400. Errors:

* client certificate must be supplied
```

I want HTTPS to HTTPS to decrypt SSL at the Nginx level and the Vault level but I cant figure out how to get Nginx to pass along the client certificate that was supplied by the original client auth request. Most people suggest using Nginx as a TCP reverse proxy so the SSL is not decrypted but I lose the ability to rewrite the url based on the incoming url pattern.

Has anyone had luck using cert auth with Nginx and Vault?

**Comment by jefferai** [comment]
Hi @kareed44 ,

You're better off asking the Vault mailing list (https://groups.google.com/forum/#!forum/vault-tool) for advice from others and that's preferable for questions (as opposed to issues/PRs).

I'm going to close this as I don't have the requisite nginx experience and this is better suited to the ML.
