### ISSUE TITLE
curl upload binary data file

### ISSUE THREAD

**Issue by goldworth** [hashicorp/vault#3007]
Hello!

I am trying to upload binary file, to vault, using curl command. I am unable to successfully upload either using -F parameter or by setting content-type, i see HTTP API always expects json format.

base64 SecretFile|curl -H "X-Vault-Token: $VAULT_TOKEN"  -XPOST -d "@-" https://vault.url/v1/secret/test

base64 SecretFile|curl -H "X-Vault-Token: $VAULT_TOKEN"  -XPOST -F "file=@-" https://vault.url/v1/secret/test

error is always something along the lines of failed to parse JSON input.

{"errors":["failed to parse JSON input: invalid character 'Ú' in literal null (expecting 'u')"]}

**Comment by jefferai** [comment]
As you said, JSON input is expected. You need to set the file to a key in a JSON dict; something like this should work:

`base64 SecretFile|curl -H "X-Vault-Token: $VAULT_TOKEN" -XPOST -F "{\"file\"=\"@-\"}" `

**Comment by goldworth** [comment]
Thank you so much @jefferai for such a quick response!
