### ISSUE TITLE
Can't delete team mapping in github backend

### ISSUE THREAD

**Issue by sebastiang** [hashicorp/vault#301]
$ vault delete auth/github/map/teams/Owners
    Error deleting 'auth/github/map/teams/Owners': Error making API request.
    
    URL: DELETE https://vault.example.com:8200/v1/auth/github/map/teams/Owners
    Code: 500. Errors:
    
    * unsupported operation

I can't set an empty value either, e.g. with `vault write auth/github/map/teams/Owners value=`. Seems like either something I'm missing in the github backend documentation, or a shortcoming in the `vault write` program that can't unset a value? I can set the `value` to a nonsense value (e.g. `0`) in this case and an `Owners` group member will get a policy that doesn't exist, but it's a funny workaround.

**Comment by armon** [comment]
@sebastiang Can you try with a build from master? I think this was recently fixed
