### ISSUE TITLE
Telemetry Statsd Prefix

### ISSUE THREAD

**Issue by joshw123** [hashicorp/vault#3018]
Hello, 

We are using Hosted Graphite as our main statsd collection. One downside to this is I have to provide a api id prefix to any stats that are sent to the endpoint. 

Is there any way that I can provide a prefix to the Telemetry config? I cannot find much in the docs. 

Massive Thank You.

**Comment by jefferai** [comment]
Hi @joshw123 ,

I don't believe this is currently supported. If you wanted it to be, the right place to file an issue would be against go-metrics to put it in the Config struct (https://godoc.org/github.com/armon/go-metrics#Config) so that Vault could then be configured with a prefix to pass in.
