### ISSUE TITLE
After a PR is merged, how long does it take for changes to take effect?

### ISSUE THREAD

**Issue by boncheff** [hashicorp/vault#302]
Apologies for opening a new issue for such a simple question but for example if a doc update PR is merged how long does it take before everything gets built and changes are reflected over at https://www.vaultproject.io/docs/index.html ?

**Comment by armon** [comment]
@boncheff The next time we cut a release (0.2.0). Otherwise the documentation of new features would go out before the release.

**Comment by boncheff** [comment]
Thank you @armon
