### ISSUE TITLE
Vault not obeying Signature Algorithm in CSR when signing intermediate

### ISSUE THREAD

**Issue by msvechla** [hashicorp/vault#3020]
Hello, 

I have a root CA mounted in vault, and want to generate a new intermediate, which should be signed by this root CA. Everything works, but the "Signature Algorithm" of the newly created CA does not match what was requested in the CSR.

In the CSR it says:
```Signature Algorithm: sha256WithRSAEncryption```

But looking at the newly generated CA certificate it says:
```Signature Algorithm: ecdsa-with-SHA256``` 

How can I enforce that during signing the request, the signature algorithm specified in the CSR is obeyed? I already tried using the use_csr_values flag, but that also did not help (https://www.vaultproject.io/api/secret/pki/index.html#use_csr_values)

Do you have any suggestions?

**Comment by jefferai** [comment]
Hi,

You can't have Vault sign with a different key type than the CA's key. If you need RSA signatures, you need to recreate the CA with an RSA key instead of ECDSA.
