### ISSUE TITLE
Question: auth backend mounts

### ISSUE THREAD

**Issue by andrewsav-datacom** [hashicorp/vault#3024]
[This page](https://www.vaultproject.io/docs/auth/index.html) states:

>When enabled, auth backends are similar to secret backends: they are mounted within the Vault mount table and can be accessed and configured using the standard read/write API. The only difference is that all auth backends are mounted underneath the auth/ prefix.

>By default, auth backends are mounted to auth/<type>. For example, if you enable "github", then you can interact with it at auth/github. However, this path is customizable, allowing users with advanced use cases to mount a single auth backend multiple times.

When issuing `vault mounts` auth backends are not returned at all. This makes me question whether what the documentation says is true. If they are mounted same way as secret backends, why `vault mounts` does not display them?

What about audit backends?

`vault list auth` yields `No value found at auth/` although `vault read sys/auth` shows mounted auth backends.

I'm trying to develop a sane set of policies to use within an organization, and it is important for me to understand all possible top level path prefixes, such as sys, cubbyhole,secret,auth, etc. But I cannot find a single command that can give me that. 

Is there one? Is there a set of several commands that can be used to list *all* existing prefixes / mounts?

Thank you in advance!

**Comment by jefferai** [comment]
@andrewsav-datacom You can use `vault auth -methods` and `vault audit-list` (or associated API calls) to get the information you seek.

In the future please pose questions on the mailing list (https://groups.google.com/forum/#!forum/vault-tool) -- we use GitHub for issues and PRs.
