### ISSUE TITLE
Vault security issue : root user can do anything on Vault server

### ISSUE THREAD

**Issue by talktosaswat** [hashicorp/vault#3025]
Hi ,
We are installing Vault using salt master and salt master to minion is running on root user as per salt standard. Once Vault is installed and unsealed , root user on Vault server can perform any operation without any extra layer of security from Vault application. For example if user "test" is a non-root user and part of sudo group where it can execute commands with root privilege then "test" user can execute below commands without any extra layer of security from Vault.
 
vault read 
vault write
vault revoke

Also from salt master we can simply execute : salt 'vault-server-name' cmd.run 'vault revoke'   and other Vault commands without login to Vault server directly. As salt master to minion ( Vault server ) authentication is happening using root user , salt command output just display Vault command result directly as Salt command output which included credential details. Which is a security issue as we may restrict Vault server root access by sudo or other options but from salt master or any other configuration management tool anyone can execute a remote Vault command and create , read and revoke Vault entries without any separate authentication. Which make Vault to be completely open to "root" user. If someone just get into Vault server with "root" user , then he can create , read, revoke and get root token just using simple Vault commands.

**Is there any solution available from Vault where , we can have extra layer of security and if someone login to Vault server locally or execute commands remotely ( using salt , puppet , ansible , ssh )  then it should have one more layer of security and only "root" user authentication will not enough to execute any Vault commands ?**

**Comment by jefferai** [comment]
The first line of Vault's README is:
```
Please note: We take Vault's security and our users' trust very seriously. If you believe you have found a security issue in Vault, please responsibly disclose by contacting us at security@hashicorp.com.
```
Next time that you think you have found a security issue, please follow that request.

As for your issue here, please read https://www.vaultproject.io/docs/concepts/tokens.html#root-tokens

**Comment by talktosaswat** [comment]
Example : 

salt 'vault-server' cmd.run '/opt/vault/vault read -address=http://127.0.0.1:8200 secret/Linux/testlinuxvm.abc2adm'

output 👍 
Key                 Value
    ---                 -----
    refresh_interval    768h0m0s
    testlinuxvm.abc2adm abcd10010

Here , I just executed salt command from Salt master to minion ( Vault server ) and we can see the credential. Also I can revoke it without any extra layer of security from Vault.

**Comment by jefferai** [comment]
@talktosaswat I don't understand your problem. Root tokens can do anything, a fact of which you are well aware. Since this is unacceptable to you, stop using root tokens.

**Comment by talktosaswat** [comment]
@jefferai : I was going through other solution from Vault using different token but how it will help ? Is there a better way to make Vault more secure or add extra layer of security even I do not use root token. I am new to Vault and need some suggestion to make it usable on production setup.

**Comment by talktosaswat** [comment]
@jefferai : I am just looking for a solution where a root user can't get Vault credentials directly from Vault server. If Vault server is compromised and someone manage to login as "root" then he can get all credentials from Vault server .  Even if I can configure Vault with different user still intruder can switch to other "user" from "root".  Please correct me if my understanding is wrong.

**Comment by jefferai** [comment]
A non-root user cannot become root, and it is nearly impossible to "log in as root" in normal circumstances. Please see the documentation I linked above, which explains this.
