### ISSUE TITLE
Cannot specify password requirements

### ISSUE THREAD

**Issue by RongoDog** [hashicorp/vault#3036]
Password generation does not account for services which require certain number of uppercase and special characters. For example, creating credentials for MySQL databases with password strength configurations of HIGH or MEDIUM will fail.

**Comment by calvn** [comment]
According to https://dev.mysql.com/doc/refman/5.7/en/validate-password-plugin.html, the MEDIUM or STRONG policies require the following: 1 numeric character, 1 lowercase character, 1 uppercase character, and 1 special (nonalphanumeric) character. The current password generation mechanism satisfies all but the last condition. We can include a change to add that requirement.

**Comment by jefferai** [comment]
Adding such characters unilaterally may break other DBs.

**Comment by calvn** [comment]
@jefferai The old password generation mechanism used to have a "-" from the UUID generation. I was thinking of using that as the special character, so `reqStr = "A1a-"`

**Comment by jefferai** [comment]
Some DBs can't handle that, but, in each of those cases I think they're already set up to replace - with _ so probably it's fine 🤗
