### ISSUE TITLE
Read secret from command line with garbage token works

### ISSUE THREAD

**Issue by lcbowen3** [hashicorp/vault#304]
SSHing to a remote server as a user that has already established credentials with Vault will return secrets based on that user's token even if the token provided is garbage:

```
[ec2-user@ip-10-16-43-125 ~]$ ssh -qt root@10.16.19.21 "export VAULT_ADDR=http://10.16.19.21:8000; vault read secret/policy/scripts/names bstoken233"
Key             Value
lease_id        secret/policy/scripts/names/19f89bfc-db08-1fc7-8b2f-d4d073e89901
lease_duration  2592000
lease_renewable false
value           joe,bob,briggs
policy          scripts
```

**Comment by armon** [comment]
Vault does not use the last argument there, I'm not sure if that is mistakenly documented somewhere. That "bstoken233" value is just being ignored completely, which is by design.

**Comment by sethvargo** [comment]
Hi @lcbowen3 

Thank you for opening an issue. Is there a place in the docs or guides that we can improve to clarify this?

@armon should Vault error on a read with extra args like here?

**Comment by lcbowen3** [comment]
So, it's by design that I can log into a machine as a user who, in another
session, has established credentials and access that others secrets without
logging into vault?  This bypasses vault security (for instance, joe has
credentials to access the accounting system via a secret in vault.  If I
can get on the server and get to root, I can sudo to joe's account and
obtain the accounting system password by accessing the vault even though I
don't know joe's password as long as joe has already authenticated to vault
at some point during the day).

Seems like a huge hole to me.

Thanks,
Clay

On Tue, Jun 2, 2015 at 3:52 PM, Armon Dadgar <notifications@github.com>
wrote:

> Vault does not use the last argument there, I'm not sure if that is
> mistakenly documented somewhere. That "bstoken233" value is just being
> ignored completely, which is by design.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/vault/issues/304#issuecomment-108095798>.
>



-- 
--------------------------------------------------------
Entia non sunt multiplicanda praeter necessitatem
    - William of Ockham (1288 - ~1348)
--------------------------------------------------------

**Comment by mitchellh** [comment]
Clay, I think you're misunderstanding. 

@armon is saying that the last argument is ignored. It just simply isn't an argument we use.

It looks like given your example you ran `vault auth` before on the machine you SSH'd into. `vault auth` is stateful: it saves your auth token onto the local disk. There is another issue tracking to make this more secure, but we followed the Git cred helper model here, so in the future you'll have options for storing it in a daemon, in keychain, etc. For now, it is on disk chmod 0600 to your current user. 

Given that the `vault read` worked, I'm guessing you ran `vault auth` earlier and it is just using that saved token. You should be able to unauth to fix this.

**Comment by lcbowen3** [comment]
Is there a way to limit the lease time on a CLI auth (perhaps with a system wide variable)?  If the exposure is limited to a couple of minutes or even an hour it would be far more acceptable.  Also, it would really be great if the auth is session based - maybe encode the process ID of the shell into the auth file?
