### ISSUE TITLE
grpc: addrConn.resetTransport failed to create client transport

### ISSUE THREAD

**Issue by prabhjot018** [hashicorp/vault#3040]
Hi,

I am running vault enterprise with version 7.0.3, on three nodes with vault configuration as:-
**storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault"
  redirect_addr = "http://private-ip:8200"
  cluster_addr = "http://private-ip:8200"
}

disable_mlock = true

listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = 1
}

telemetry {
  statsite_address = "127.0.0.1:8125"
  disable_hostname = true
}**

Vault status is as:-
**Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Unseal Nonce: 
Version: 0.7.3+ent
Cluster Name: vault-cluster-2e06deba
Cluster ID: d721bf34-4a14-b1a7-5726-6af234e20cfb

High-Availability Enabled: true
	Mode: standby
	Leader: http://10.1.37.210:8200**

When i am trying the command to enable-audit on standy node using curl command as:-
curl     --header "X-Vault-Token: <vault-token>"     --request PUT     --data @payload.json     http://127.0.0.1:8200/v1/sys/audit/example-audit
payload looks like:-
{
  "type": "file",
  "options": {
    "path": "/var/log/vault/log"
  }
}

I am getting error on server as:-
  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing tls: oversized record received with length 20527"; Reconnecting to {10.1.37.210:8200 <nil>}

**Comment by prabhjot018** [comment]
Just tested the same scenario with community vault version, it is working fine

**Comment by jefferai** [comment]
Your cluster_addr is the same as your redirect_addr which is causing this problem. You should leave cluster_addr alone and it will automatically use the address of redirect_addr plus with one port higher.
