### ISSUE TITLE
authentication backends cannot create root tokens

### ISSUE THREAD

**Issue by 472827074** [hashicorp/vault#3048]
when I execute command for "./vault write auth/app-id/login/my-spring-boot-app user_id=my-static-userid" in command line ,it's response "authentication backends cannot create root tokens" for me,can you tell me hao to solve this problem ? thank you very much.

**Comment by jefferai** [comment]
This is a feature, not a bug. See https://www.vaultproject.io/docs/concepts/tokens.html#root-tokens
