### ISSUE TITLE
Consider less information in Vault mounts

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#3050]
The new output for `vault mounts` is very verbose and it doesn't fit on the screen unless the terminal is full-width. I would like to suggest supplying less information (maybe just path, type, description) by default. Then, have an additional flag like `-detailed` that prints the full information like accessor, ttls, and replication behavior. Thoughts?

**Comment by meirish** [comment]
You did this in the CLI rework 🎉 - thanks!
