### ISSUE TITLE
How work certificate=@./cert.pem to used in TLS Certificates Auth Backend

### ISSUE THREAD

**Issue by shaohk** [hashicorp/vault#3051]
HI:
 eg:
 vault write auth/cert/certs/web display_name=web policies=test certificate=@./cert.pem ttl=400000
 How work of the "certificate"?

 I used open-ssl create the first client-cert=cert.pem and client-key=key.pem, and I upload the cert.pem to the vault auth by "vault write auth/cert/certs/web display_name=web policies=test certificate=@./cert.pem ttl=400000".

But when I create a new client-cert=cert2.pem and client-key=key2.pem, didn't upload the cert2.pem to vault.

When I exec "vault auth -method=cert -ca-cert=ca.pem -client-cert=cert.pem -client-key=key.pem name=web" and exec "vault auth -method=cert -ca-cert=ca.pem -client-cert=cert2.pem -client-key=key2.pem name=web" both work, and the result is same.

How the effect of the "certificate=@./cert.pem" in "vault write auth..."?

Thanks!!!

**Comment by jefferai** [comment]
Can you please provide a test case against a dev server (`vault server -dev`) and include the various PEM files? It's hard to say without seeing your commands and the actual certs what might be going on.

**Comment by shaohk** [comment]
Thank U!
I catch sight of the "allowed_name" at the "/auth/cert/certs/<name>" document,
URL
/auth/cert/certs/<name>
Parameters
certificate required The PEM-format CA certificate.
allowed_names optional Constrain the Common and Alternative Names in the client certificate with a globbed pattern. Value is a comma-separated list of patterns. Authentication requires at least one Name matching at least one pattern. If not set, defaults to allowing all names.
policies optional A comma-separated list of policies to set on tokens issued when authenticating against this CA certificate.
display_name optional The display_name to set on tokens issued when authenticating against this CA certificate. If not set, defaults to the name of the role.
ttl optional The TTL period of the token, provided as a number of seconds. If not provided, the token is valid for the the mount or system default TTL time, in that order.

And I set allowed_names to match PEM's Common,It is working.

I want to ask that how to determine the PEM(client auth used) and the PEM(vault auth/cert/certs/<name> seted) are lawful and match.

Thanks!
