### ISSUE TITLE
Vault CLI auth error on Windows with mapped network drive for home dir

### ISSUE THREAD

**Issue by bkrodgers** [hashicorp/vault#3052]
I've got a Windows user (poor guy) whose home directory is set by group policy to `Z:\`, which is a mapped drive to his network share.  When he tries to use Vault, he gets the error below.

```
vault auth -method=userpass username=<user>
Password (will be hidden):
Error storing token: open Z:\/.vault-token: The system cannot find the path specified.
```

Would you consider that a bug, or would you say that mapped network drives as home dir just aren't supported?

Either way, is there a good workaround in the short term?  I thought about using the new -no-store option, but the usefulness of that is limited by (as far as I can tell) the fact the auth command doesn't support either the `format` flag to output json or the `field` flag to have it output just the token.  I'd have to parse the multiline text output to capture it and set the VAULT_TOKEN env var.  Doable, but it gets ugly.

We'll also look into whether we can get his home dir changed to a local path, but I do know quite a few users are setup this way here.

**Comment by chrishoffman** [comment]
You can set the `HOME` environment variable or the combination of `HOMEDRIVE` and `HOMEPATH` to an alternate location which will be used instead of `USERPROFILE`.

**Comment by bkrodgers** [comment]
Apparently the group policy isn't letting him set those.

**Comment by chrishoffman** [comment]
Are you able to set local variables in scripts?  Maybe the answer is to wrap your vault executable with something that sets the variable locally.  I don't have a Windows machine to test right this right now but it should be something simple like this.

```batch
@ECHO OFF
SET HOME="C:\Temp"
vault.exe %*
```

**Comment by jefferai** [comment]
You can use -token-only to only output the token.

**Comment by bkrodgers** [comment]
Cool, I take it that's new in 0.8 or 0.8.1?  I hadn't seen that option before.  

That would let me code a better workaround, but is there anything that can be done to make it work more seamlessly for users who have their home directory set to a mapped network drive?

**Comment by jefferai** [comment]
Yeah, it's relatively new, I think in 0.8.

I don't really know what the issue is in the first place, so I'm not sure how to advise on a better workaround. I guess the SMB/CIFS protocol doesn't allow files beginning with a dot, even if the underlying filesystm does? (Although that doesn't match my memory of those protocols.) Or maybe they're just not allowed to write to the root of the shared drive?

**Comment by michelvocks** [comment]
Hi @bkrodgers!

Is this still an issue for you? I think using the `-token-only` option is the best option here.

Cheers,
Michel

**Comment by catsby** [comment]
Hello - we haven't heard back in some time, so we're going to close this issue for now. If you have more information please let us know by opening a new issue, and optionally referencing this one. Thanks!
