### ISSUE TITLE
High Availability by other storage

### ISSUE THREAD

**Issue by koalalorenzo** [hashicorp/vault#3057]
Hello!
The page that describes the [high availability in the documentation](https://www.vaultproject.io/docs/internals/high-availability.html) is talking about using _Certain storage backends_ but it is referring only to Consul.

What are the other storage backends that I can use to set up HA? How can I set up (Is there any practical guide to follow?). 
Can I use HA with cloud storage solutions like the one on Azure or AWS?

**Comment by jefferai** [comment]
The configuration page for each storage type lists whether or not it supports HA. See https://www.vaultproject.io/docs/configuration/storage/index.html
