### ISSUE TITLE
Permission denied 403

### ISSUE THREAD

**Issue by kaosmonk** [hashicorp/vault#3058]
Hi guys,

Need your assistance with vault (am not even sure if it's vault or consul) as I'm quite a novice with setting it up.

So I've set vault with consul as a backend. Have created tokens on the consul side, ACLs and everything and have instructed vault using the tokenID of the ACL I've created in consul (am exporting VAULT_TOKEN with that tokenID value).

Everything stopped working as of today - I am not able to `vault read` nor `vault write` anymore and all I'm getting is permission denied error:
```
~ # vault read secret/production/databases/pg-01
Error reading secret/production/databases/pg-01: Error making API request.

URL: GET http://127.0.0.1:8200/v1/secret/production/databases/pg-01
Code: 403. Errors:

* permission denied
```

and audit log doesn't say much imo:

```
{"time":"2017-07-26T11:51:02Z","type":"request","auth":{"client_token":"","accessor":"","display_name":"","policies":null,"metadata":null},"request":{"id":"20ee4805-cd8a-e383-bba5-c96aed59228a","operation":"read","client_token":"hmac-sha256:2f329e78fce69b3ac7c44284ee55ad6216c13dc5d15b3ae7ecd1b63c98b110b4","client_token_accessor":"","path":"secret/production/databases/pg-01","data":null,"remote_address":"127.0.0.1","wrap_ttl":0,"headers":{}},"error":"permission denied"}
{"time":"2017-07-26T11:51:02Z","type":"response","auth":{"client_token":"","accessor":"","display_name":"","policies":null,"metadata":null},"request":{"id":"20ee4805-cd8a-e383-bba5-c96aed59228a","operation":"read","client_token":"hmac-sha256:2f329e78fce69b3ac7c44284ee55ad6216c13dc5d15b3ae7ecd1b63c98b110b4","client_token_accessor":"","path":"secret/production/databases/pg-01","data":null,"remote_address":"127.0.0.1","wrap_ttl":0,"headers":{}},"response":{"data":{"error":"hmac-sha256:cb162f3d9ff8c9a8fea075e3cfd017ecd494b1f1837851cbfa786d5ad21d63e7"}},"error":"1 error occurred:\n\n* permission denied"}
```

If I for example export VAULT_TOKEN with the value of vault's root token (!) I can do whatever I want. But I'd like to be able to use the token I've generated in consul while creating specified ACL.

Any ideas what's going on? Is it TTL? Did my token expire? How to confirm that? I can't even perform `lookup-self` with this token as all I'm getting is permission denied all the time. Any hints are more than appreciated!

Thanks!

**Comment by jefferai** [comment]
The default policy normally allows a token to look itself up, so as you noted, if you can't look up the token has likely expired.

**Comment by kaosmonk** [comment]
Here's another thing: I've cloned the problematic token in Consul and set VAULT_TOKEN to new tokenID and still get the same error? If my previous token has expired then the new one should work? Or am I mixing apples and oranges here?

**Comment by kaosmonk** [comment]
@jefferai Thanks for a quick response! Vault version is 0.7.3 for the reference.

How can I confirm that my token has expired? Because nothing indicates that tbh. Like I said I might not getting it correctly, but I've ben using ACL ID as a value for VAULT_TOKEN and everything was working as expected.

Which means that I haven't created any additional tokens in Vault but rather used the ACL ID from Consul. And I have specified policies for that ACL ID/tokenID what it can access and how. 

So I'm not quite sure it's the token that expired. If I have cloned ACL in Consul and set new ACL ID as VAULT_TOKEN, then it should work, right?

**Comment by jefferai** [comment]
Honestly I'm not following what you're doing with Consul ACLs, but Consul and Vault tokens have absolutely nothing to do with each other.

**Comment by kaosmonk** [comment]
Ok, like I've said I might have done something completely wrong here. So here's what I did:
- I've creted ACL in Consul and have added some rules
- That ACL has it's own ID eg `de1ee14a-323e-5163-d2d6-7823f72331d2`
- I've used that ID to configure Vault backend like this
```
backend "consul" {
  address = "10.0.60.4:8500"
  check_timeout = "5s"
  path = "vault/"
  token = "de1ee14a-323e-5163-d2d6-7823f72331d2"
  scheme = "http"
}
```
- I've also used the same ID as a value for when exporting VAULT_TOKEN (this was the only way for me to be able to read and write with vault)

So this has been working for me for a month or so and today it just stopped. Did my setup make any sense to you?

**Comment by kaosmonk** [comment]
Btw, the only token I see in Vault is the root one. No other tokens in there.

**Comment by jefferai** [comment]
Hi @kaosmonk ,

Consul tokens are not valid Vault tokens. I don't really know how things have been working for you up to now but my guess is that you weren't actually exporting your Consul token before, you were exporting your initial root token.

**Comment by kaosmonk** [comment]
Thanks for the input, I appreciate it. By checking my history I can only see the ACL ID being exported as VAULT_TOKEN so I'm not sure how this has been working for me.

In the meantime I did quite extensive reading on Vault tokens and TTL, renewals etc so I've created aVault policy that grants certain perms on `/secret/` and then I've created a token with that policy attached and it seems to be working.

So couple of questions left and this thread can and should be closed for good:
- the best way for creating periodic tokens? Docs are specifying 3 approaches
```
1. By having sudo capability or a root token with the auth/token/create endpoint
2. By using token store roles
3. By using an authentication backend that supports issuing these, such as AppRole
```
I'd like to go with the first one, but am not sure how? I do have `sudo` on Vault instance and I do have Vault root token, but am not sure I know what it really means?
- in vault config file I've specified above, that's the real use case for the `token` directive in the `backend` block? Is it needed? Can it be removed? I've set it to the Consul ACL ID but now I'm not sure that it needs to be there since that's not the token Vault should be using at all (as per your comment)

Thanks once again!

**Comment by jefferai** [comment]
You probably *shouldn't* go with the first option as it's the least secure overall -- anyone with sudo or root access to `auth/token/create` can basically issue whatever they want. It's safer to use token store roles.

`sudo` is a capability that you can give to users on certain paths -- see https://www.vaultproject.io/docs/concepts/policies.html -- so either a root token (which can do anything) or a token with `sudo` on `auth/token/create` can generate periodic tokens.

Whether you need the Consul ACL token in the block depends on whether or not you have Consul ACLs enabled. It sounds like you do, so you probably need to keep it.
