### ISSUE TITLE
Allow updating of userpass TTL's

### ISSUE THREAD

**Issue by Feld0** [hashicorp/vault#3068]
The `ttl` and `max_ttl` settings associated with the `userpass` authentication backend are currently set when a user is created but cannot be updated afterward without resetting the user's password.

This is problematic because the [`POST /auth/userpass/users/[username]`](https://www.vaultproject.io/docs/auth/userpass.html#auth-userpass-users-username-) API endpoint requires the password to be specified. In a deployment where this backend is used to give a team access to Vault, an admin who wishes to adjust the TTL of user logins _shouldn't_ have everyone's passwords on hand.

#909 addressed this issue in the context of updating a user's policy - it would be lovely to have a similar solution for the TTL settings (maybe the username field as well, since it's the only one that would then remain un-changeable).

**Comment by chrishoffman** [comment]
I just tested it out and I was able to change the TTL values without setting a password.  Password is only required when initially creating the user, not when updating the user.  

```
% vault auth-enable userpass
Successfully enabled 'userpass' at 'userpass'!

% vault write auth/userpass/users/test password=test
Success! Data written to: auth/userpass/users/test

% vault read auth/userpass/users/test
Key     	Value
---     	-----
max_ttl 	0
policies
ttl     	0

% vault write auth/userpass/login/test password=test
Key                	Value
---                	-----
token              	d742ac92-1b00-2e53-3d95-6ac3310791a8
token_accessor     	6e3322d8-e335-1759-5108-5c5f78c3c359
token_duration     	768h0m0s
token_renewable    	true
token_policies     	[default]
token_meta_username	"test"

% vault write auth/userpass/users/test ttl=100s max_ttl=200s
Success! Data written to: auth/userpass/users/test

% vault read auth/userpass/users/test
Key     	Value
---     	-----
max_ttl 	200
policies
ttl     	100

% vault write auth/userpass/login/test password=test
Key                	Value
---                	-----
token              	bbad62c6-e266-54ed-64e0-9ecb97eeefc5
token_accessor     	afbcbf12-baf3-8e0d-3c94-c1b7895b03ae
token_duration     	1m40s
token_renewable    	true
token_policies     	[default]
token_meta_username	"test"
```

**Comment by Feld0** [comment]
Oh, thanks! I opened the issue because the documentation states, or at least suggests, that the password is always required. :smiley:
