### ISSUE TITLE
Errors using LDAP auth backend

### ISSUE THREAD

**Issue by Ardun21** [hashicorp/vault#3070]
I'm new to Vault and am trying to get the LDAP authentication backend configured against our AD domain. I have the authentication backend enabled:

    Path       Type      Default TTL  Max TTL  Replication Behavior  Description
    ldap/      ldap      system       system   replicated
    token/     token     system       system   replicated            token based credentials
    userpass/  userpass  system       system   replicated

And I have the backend configured:

    Key             Value
    ---             -----
    binddn          CN=mybindusr,OU=Users,DC=company,DC=test
    bindpass        ********
    certificate
    deny_null_bind  true
    discoverdn      false
    groupattr       memberOf
    groupdn         OU=Groups,DC=company,DC=test
    groupfilter     (&(objectClass=group)(member:1.2.840.113556.1.4.1941:={{.UserDN}}))
    insecure_tls    true
    starttls        false
    tls_max_version tls12
    tls_min_version tls12
    upndomain
    url             ldaps://test.ad.int:636
    userattr        samaccountname
    userdn          OU=Users,DC=company,DC=test

However, when I go to authenticate using this backend, I am getting the following error message:

    Code: 400. Errors:
    
    * user is not a member of any authorized group

I am not really sure 
A) Which user is being referred to here (the ID being authenticated or the bind DN) 
B) If AD or Vault is the source of this error
C) Which groups are currently deemed to be "authorized"

I've been trying to find some troubleshooting documentation for the LDAP auth backend, but haven't found much other than the few issues opened already here.

**Comment by Ardun21** [comment]
Update: I found my way through to the solution here. The problem was that I had not setup any policies for any LDAP groups. After setting up an LDAP group with a policy, I was able to authenticate and get a token.

Closing this issue.

**Comment by tplive** [comment]
@Ardun21 I have the opposite problem - even if my user is not a member of an "authorized group", (that is - a group that has a policy assigned to it), I'm granted login and assigned the default policy. I don't want any users that don't belong to a Vault-mapped group to be able to log in. How is this accomplished?
