### ISSUE TITLE
Vault can't initialized after reinstalled on the VM. Not generating any unseal keys and root token

### ISSUE THREAD

**Issue by talktosaswat** [hashicorp/vault#3077]
Hi ,
We are installing vault and consul with version on **Centos 6**. Installation is working fine if we install on a fresh VM.   it is generating no keys . It should generate 5 unseal keys and root token. But in out case it is NULL. Though second installation is successful but initialization is failed as it generate no unseal keys and no root token .
We are using : 64 bit version
**consul_0.8.4_linux_amd64.zip
vault_0.7.3_linux_amd64.zip**

How we remove vault and consul 👍
1- stop vaultd and consuld service .
2- grep for any running processes 
3- remove /opt/vault  and /opt/consul  directories manually as we are installing vault and consul to /opt
5- delete the  /root/.vault-token  hidden file . we are testing it on test VM and so we still keep .vault-token just for installation and after that we remove it.
6- find for  vault and consul directory and file under /  just to verify if vault or consult has some configuration or cache file.
7- Also we rebooted the VM and tried the installation but still we are getting same issue 

Is there an official guide to uninstall vault and consul which is running on the same VM ?

What will be the steps and command to make clean uninstall Vault and Consul ? May be some uninstall script. 

This is a serious problem as if we install vault and remove it and try to install again it fails. The only solution is to re image the VM .  

Please advice.

Thanks
Sas

**Comment by chrishoffman** [comment]
What storage backend are you using?  If vault was previously initialized and the storage was not cleared, you will not be able to initialize it again until you point it to a new backend or clear the storage.

Can you provide the config file and startup log for your vault instance?

**Comment by talktosaswat** [comment]
The backend is consul on the same VM as Vault. How to clear the storage ? Is there any official guide or script ?

/opt/vault/vault-config.hcl 👍 
more vault-config.hcl
backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
}

listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = 1
}


Here is the configuration 
backend "consul" {
  address = "$CONSUL_IP:8500"
  path = "vault"
}

listener "tcp" {
  address = "$VAULT_IP:8200"
  tls_disable = 1
}


vaultd.log 👍 

==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
        Redirect Address: http://127.0.0.1:8200
                 Storage: consul (HA available)
                 Version: Vault v0.7.3
             Version Sha: 0b20ae0b9b7a748d607082b1add3663a28e31b68

==> Vault server started! Log data will stream in below:

2017/07/28 11:36:17.307708 [WARN ] physical/consul: appending trailing forward slash to path
2017/07/28 11:36:22.020936 [WARN ] physical/consul: check unable to talk with Consul backend: error=Unexpected response code: 500 (CheckID "vault:127.0.0.1:8200:vault-sealed-check" does not have associated TTL)

**Comment by talktosaswat** [comment]
Here is the consul log:

==> WARNING: BootstrapExpect Mode is specified as 1; this is the same as Bootstrap mode.
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> Starting Consul agent...
==> Consul agent running!
           Version: 'v0.8.4'
           Node ID: 'd4c53d49-210a-54df-1e9a-7e5ae74d2694'
         Node name: 'OrchestrationVM-Ten1'
        Datacenter: 'dc1'
            Server: true (bootstrap: true)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600)
      Cluster Addr: 10.193.251.4 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false

==> Log data will now stream in as it occurs:

    2017/07/28 11:36:16 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:10.193.251.4:8300 Address:10.193.251.4:8300}]
    2017/07/28 11:36:16 [INFO] raft: Node at 10.193.251.4:8300 [Follower] entering Follower state (Leader: "")
    2017/07/28 11:36:16 [INFO] serf: EventMemberJoin: OrchestrationVM-Ten1 10.193.251.4
    2017/07/28 11:36:16 [WARN] serf: Failed to re-join any previously known node
    2017/07/28 11:36:16 [INFO] consul: Adding LAN server OrchestrationVM-Ten1 (Addr: tcp/10.193.251.4:8300) (DC: dc1)
    2017/07/28 11:36:16 [INFO] serf: EventMemberJoin: OrchestrationVM-Ten1.dc1 10.193.251.4
    2017/07/28 11:36:16 [INFO] agent: Started DNS server 127.0.0.1:8600 (udp)
    2017/07/28 11:36:16 [INFO] consul: Handled member-join event for server "OrchestrationVM-Ten1.dc1" in area "wan"
    2017/07/28 11:36:16 [WARN] serf: Failed to re-join any previously known node
    2017/07/28 11:36:16 [INFO] agent: Started DNS server 127.0.0.1:8600 (tcp)
    2017/07/28 11:36:16 [INFO] agent: Started HTTP server on 127.0.0.1:8500
    2017/07/28 11:36:22 [ERR] http: Request PUT /v1/agent/check/fail/vault:127.0.0.1:8200:vault-sealed-check?note=Vault+Sealed, error: CheckID "vault:127.0.0.1:8200:vault-sealed-check" does not have associated TTL from=127.0.0.1:33664
    2017/07/28 11:36:22 [WARN] raft: Heartbeat timeout from "" reached, starting election
    2017/07/28 11:36:22 [INFO] raft: Node at 10.193.251.4:8300 [Candidate] entering Candidate state in term 6
    2017/07/28 11:36:22 [INFO] raft: Election won. Tally: 1
    2017/07/28 11:36:22 [INFO] raft: Node at 10.193.251.4:8300 [Leader] entering Leader state
    2017/07/28 11:36:22 [INFO] consul: cluster leadership acquired
    2017/07/28 11:36:22 [INFO] consul: New leader elected: OrchestrationVM-Ten1
    2017/07/28 11:36:22 [INFO] agent: Synced service 'consul'
    2017/07/28 11:36:22 [INFO] agent: Synced service 'vault:127.0.0.1:8200'
    2017/07/28 11:36:22 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 11:36:22 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
==> Newer Consul version available: 0.9.0 (currently running: 0.8.4)
    2017/07/28 11:38:20 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 11:40:08 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 11:41:50 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 11:43:00 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 11:44:55 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 11:46:53 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 11:48:25 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 11:49:32 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 11:50:45 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 11:52:45 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 11:54:26 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 11:56:26 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 11:58:15 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 11:59:36 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 12:01:15 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 12:03:01 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 12:04:38 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 12:06:11 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/07/28 12:08:10 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'

**Comment by talktosaswat** [comment]
ps aux|grep consul  :  consul output 
root      8956  0.0  0.0 110496  1212 pts/0    S    11:36   0:00 /bin/bash /etc/init.d/consuld start
root      8960  0.0  0.0 110228  1416 pts/0    S    11:36   0:00 /bin/bash -c ulimit -S -c 0 >/dev/null 2>&1 ; /opt/consul/consul agent -server -bootstrap-expect 1 -data-dir -bind
root      8961  0.4  0.2  39472 20192 pts/0    Sl   11:36   0:08 /opt/consul/consul agent -server -bootstrap-expect 1 -data-dir -bind
root      9272  0.0  0.0 105372   892 pts/0    S+   12:10   0:00 grep consul

**Comment by talktosaswat** [comment]
Found a solution to clean all consul entry and reinstall vault again.

We just need to execute two curl commands and then stop consul and vault service. Delete the directories and trigger Vault installation.  I test many times and it worked fine without reinstalling VM.
 
Command 1: Check Vault values inside Consul
curl http://127.0.0.1:8500/v1/kv/?recurse | jq .
 
Command 2: Delete all Consul values for /Vault . Which makes Vault clean for next installation
curl -X DELETE 'http://localhost:8500/v1/kv/vault?recurse'



But I just want to understand where is the consul mount point in vault . 
If I type Vault mounts command I do not see any consul mounts. But vault create some consul mounts by itself for storing its internal stuff to consul during installation.

If we want to use other credentials to store to consul the can we use same KV from consul where vault stores it internal ? 

Or how can we specify a new mount from consul which can be used to application specific credentials and we can see that mount using vault mounts command . 

It seems we are just using secret/ which is coming from local file system rather than consul. 

vault mounts
Path        Type       Default TTL  Max TTL  Force No Cache  Replication Behavior  Description
cubbyhole/  cubbyhole  n/a          n/a      false      local                 per-token private secret storage
secret/     generic    system       system   false  replicated            generic secret storage           ( NOT SAFE TO STORE CREDENTIALS )
sys/        system     n/a          n/a      false           replicated            system endpoints used for control, policy and debugging

**Comment by chrishoffman** [comment]
That is correct, if you recursively delete the `vault` key in Consul, you will reset the state of your cluster.  I think you are confusing the secret backend for consul with the physical storage of vault.  

The location where your vault data is stored is located in your config file under the path directory. 

```
backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
}
```

**Comment by talktosaswat** [comment]
Could you please confirm if we use backend as Consul then Vault only stores its internal stuff to consul but not credentials which we store to generic backend secret/ 

If I just store credentials to generic backend secret/ and my vault configuration still have backend as Consul parameter then can I restore secrets from consul incase there is a VM crash but I have Consul backup ? 


My 3rd question is what is the best production configuration to use generic backend secret/ for storing credentials for a single node Vault running with Consul with above configuration.  

How to take point in time backup for Vault generic backend secret/ from file system level incase there is VM crash or file system corruption ?  Can we just restore VM disk from backup or VM snapshot and Vault start working fine ? After Vault installation we never used  Vault mount Consul command to integrate Vault with consul as storage backend . 
$ vault mount consul : Never used in our installation case

**Comment by chrishoffman** [comment]
I think the best place to answer these questions is the Vault mailing list (https://groups.google.com/forum/#!forum/vault-tool).  We try to keep the issue tracker reserved for bugs/issues/feature requests/PRs.

There are a lot of knowledgeable people on the list that have tackled this problem in various ways in different setups/environments and posting there will get more eyes on the question.

Thanks!
