### ISSUE TITLE
Licensing Issues : For go-okta   OSS  license information must be used for Vault

### ISSUE THREAD

**Issue by talktosaswat** [hashicorp/vault#3079]
As per https://github.com/sstarcher/go-okta/ no LICENSE file is available in the repo. 
It should have license information which can be used as open source product. Without license information we find it difficult to use. 

Please include license file with information as part of  https://github.com/sstarcher/go-okta/  which can be used as OSS . 

Thanks
Sas

**Comment by jefferai** [comment]
You should file an issue with that repository, not Vault.

**Comment by mohans35** [comment]
Hi Jeff , I can see you are one of the contributor for this package. I already created an issue to add license and sent e-mail to Shane . If you are actively own this package . Please upload the license file.

**Comment by talktosaswat** [comment]
Shane replied and he will add license file next week. Closing this issue .

**Comment by sstarcher** [comment]
Merged - https://github.com/sstarcher/go-okta/pull/3
