### ISSUE TITLE
api: sys.health should decode the response body even when the status code is not 200.

### ISSUE THREAD

**Issue by xiang90** [hashicorp/vault#3085]
According to https://www.vaultproject.io/api/system/health.html, the health api will return meaningful response body in JSON format even if the status code is non-200 (for example 429).

But the vault client implementation returns too early when it thinks there is an error only by examining the status code. The expected behavior is to continue to decode the body and return 

```
{
  "cluster_id": "c9abceea-4f46-4dab-a688-5ce55f89e228",
  "cluster_name": "vault-cluster-5515c810",
  "version": "0.6.2",
  "server_time_utc": 1469555798,
  "standby": false,
  "sealed": false,
  "initialized": true
}
```

**Comment by jefferai** [comment]
What's the actual error you're seeing? Because 429s should not cause an issue here.

**Comment by xiang90** [comment]
@jefferai 

The client returns here: https://github.com/hashicorp/vault/blob/master/api/sys_health.go#L6 since the status code is not in the range of https://github.com/hashicorp/vault/blob/master/api/response.go#L28-L32.

429 is a bad example I guess. Let's say 501 when vault is not inited :P.

**Comment by jefferai** [comment]
Does that PR work for you?

**Comment by xiang90** [comment]
@jefferai commented in that pr.
