### ISSUE TITLE
Build fail on ppc64le: Error in vendor code SAP/go-hdb/internal/protocol 

### ISSUE THREAD

**Issue by vaibhavsood** [hashicorp/vault#3089]
**Environment:**

* Vault Version: master (top-of-tree)
* Operating System/Architecture: Ubuntu 16.04.1 LTS ppc64le

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

Build passes

**Actual Behavior:**

Build fails with following error snippet:

go generate
==> Removing old directory...
==> Building...
Number of parallel builds: 15

-->   linux/ppc64le: github.com/hashicorp/vault

1 errors occurred:
**--> linux/ppc64le error: exit status 2
Stderr: # github.com/hashicorp/vault/vendor/github.com/SAP/go-hdb/internal/protocol
vendor/github.com/SAP/go-hdb/internal/protocol/session.go:787: undefined: archEndian**

Makefile:21: recipe for target 'dev' failed
make: *** [dev] Error 1

**Steps to Reproduce:**

>> cd "vault-src"
>> make

**Important Factoids:**

Issue specific to ppc64le

**References:**

**Comment by chrishoffman** [comment]
This is an issue with an upstream library.  Once that library is updated we can review updating Vault with the new library.  Closing this issue for now.

**Comment by jefferai** [comment]
@Caiyeon for visibility

**Comment by Caiyeon** [comment]
I see the problem. I'll see if there's something I can do on my end

**Comment by jefferai** [comment]
@Caiyeon see https://github.com/hashicorp/vault/pull/3090
