### ISSUE TITLE
Setcap Issue

### ISSUE THREAD

**Issue by RavindraSinghKhichi** [hashicorp/vault#3092]
Hi There,

my vault configuration is this 

**storage "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
}

listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
}
disable_mlock = true**

when I use this I get this following issue 

**Error initializing Vault: Put https://127.0.0.1:8200/v1/sys/init: http: server gave HTTP response to HTTPS client**

and when I use 

**setcap cap_ipc_lock=+ep $(readlink -f $(which vault))**

I start getting 
**bash: /usr/bin/vault: Operation not permitted**

on any vault command, I fire whether it be vault init or any even vault help too.

**Comment by jefferai** [comment]
Your error is because you are using an `https` address but have TLS disabled. You need to switch your URL to use `http`.
