### ISSUE TITLE
Getting Errors running go get github.com/hashicorp/vault/api

### ISSUE THREAD

**Issue by weisinc** [hashicorp/vault#3102]
I have not had any errors get/install the package below up until ~3pm this afternoon. Was something committed that caused it? How can i fix it?  Thanks!

Command:
go get github.com/hashicorp/vault/api

Error (I am using go (1.7.3-r0):
Step 7/13 : RUN go get github.com/hashicorp/vault/api
 ---> Running in 5fb1aa19f464
# github.com/hashicorp/vault/api
/go/src/github.com/hashicorp/vault/api/client.go:365: c.addr.Port undefined (type *url.URL has no field or method Port)
/go/src/github.com/hashicorp/vault/api/client.go:367: c.addr.Hostname undefined (type *url.URL has no field or method Hostname)
The command '/bin/sh -c go get github.com/hashicorp/vault/api' returned a non-zero code: 2

**Comment by weisinc** [comment]
I took care of it. checked out v0.7.3 instead and don't see the errors anymore.

**Comment by shnr33** [comment]
This fails on systems with Go version less than 1.8 due to a recent commit - 52a18a1236 which is using a method 'Port()' declared in v1.8 and is unavailable in older versions.

**Comment by jefferai** [comment]
Go 1.8 is documented as required in our readme.
