### ISSUE TITLE
Failing when I build my repo in docker, which is using vault

### ISSUE THREAD

**Issue by pontiyaraja** [hashicorp/vault#3103]
**Environment:** Docker, go go1.7.5 linux/amd64, vault

* Vault Version:  0.7.3
* Operating System/Architecture: macOS Sierra version 10.12.6
![screen shot 2017-08-03 at 12 04 37 pm](https://user-images.githubusercontent.com/1989030/28908967-056fee60-7844-11e7-9f8f-3faab5c49c4a.png)

**Vault Config File:** consul

**Startup Log Output:** `# github.com/hashicorp/vault/api
/go/src/github.com/hashicorp/vault/api/client.go:365: c.addr.Port undefined (type *url.URL has no field or method Port)
/go/src/github.com/hashicorp/vault/api/client.go:367: c.addr.Hostname undefined (type *url.URL has no field or method Hostname)
github.com/gorilla/websocket
github.com/fzzy/radix/redis/resp
gopkg.in/mgo.v2/internal/json
github.com/fzzy/radix/redis
github.com/fzzy/radix/extra/pool
gopkg.in/mgo.v2/internal/scram
golang.org/x/sys/unix
gopkg.in/mgo.v2/bson
github.com/fsnotify/fsnotify
github.com/hashicorp/hcl/hcl/strconv
github.com/hashicorp/hcl/hcl/token
gopkg.in/mgo.v2
github.com/hashicorp/hcl/hcl/ast
github.com/hashicorp/hcl/hcl/scanner
github.com/hashicorp/hcl/hcl/parser
github.com/hashicorp/hcl/json/token
github.com/hashicorp/hcl/json/scanner
github.com/hashicorp/hcl/json/parser
github.com/hashicorp/hcl
github.com/magiconair/properties
github.com/mitchellh/mapstructure
github.com/pelletier/go-toml
github.com/spf13/afero/mem
golang.org/x/text/transform
golang.org/x/text/unicode/norm
github.com/spf13/cast
github.com/spf13/jwalterweatherman
github.com/spf13/afero
github.com/spf13/pflag
gopkg.in/yaml.v2
github.com/felixge/httpsnoop
github.com/gorilla/context
github.com/gorilla/handlers
github.com/gorilla/mux
github.com/twinj/uuid
github.com/spf13/viper
github.com/unrolled/render
bitbucket.org/tekion/tenums/constants
bitbucket.org/tekion/tmodel/common
bitbucket.org/tekion/tbaas/util
bitbucket.org/tekion/tbaas/redisHelper
github.com/pkg/errors
`

**Expected Behavior:** Docker build have to be success, when I build my repo which is importing and using vault

**Actual Behavior:** Docker build failed

**Steps to Reproduce:** Build your repo in docker, which is importing and using vault

**Important Factoids:** `type Client struct {
	addr               *url.URL
	config             *Config
	token              string
	wrappingLookupFunc WrappingLookupFunc
}

*url.URL has no field or method Port

*url.URL has no field or method Hostname`

**References:** Follow vault doc to and docker doc to setup and build your  @brenix @hornbeck @ctennis @mitchellh @abedra 
![screen shot 2017-08-03 at 12 01 14 pm](https://user-images.githubusercontent.com/1989030/28908852-81d3b3b6-7843-11e7-969d-ec908f24045c.png)

**Comment by pontiyaraja** [comment]
Its working fine in go version >= 1.8, 
below functions are newly added in go version >= 1.8
`func (u *URL) Hostname() string {
	return stripPort(u.Host)
}

func (u *URL) Port() string {
	return portOnly(u.Host)
}`

If its not fixed then 

> vault will not work in go version < 1.8

**Comment by jefferai** [comment]
Vault requires Go 1.8.
