### ISSUE TITLE
Using test helpers in Go app adds ~26 MB of dependencies to vendor directory

### ISSUE THREAD

**Issue by joeshaw** [hashicorp/vault#3105]
This is with Vault 0.7.3.  I recently switched my Go application from relying on an externally run Vault instance for testing purposes to using the built-in helpers.  @mitchellh talked about this during his GopherCon keynote and I was so happy to see that I could run an in-memory Vault for tests.

To do so, I added this to the top of my test:
```go
core, _, token := vault.TestCoreUnsealed(t)
l, addr := http.TestServer(t, core)
```

This pulls in the `github.com/hashicorp/vault/http` and `github.com/hashicorp/vault/vault` packages into my project.  Previously I was using only the `github.com/hashicorp/vault/api` package.

As a result, after running `dep ensure` to bring in the additional dependencies, I was surprised to find it pulling in 26 MB of additional packages (2253 files and nearly 800,000 lines of code), including: Azure, Google Cloud and AWS client packages; etcd, Consul, Zookeeper and Serf clients; MySQL, Postgres and MongoDB drivers; and many other support packages.  In retrospect several of these make sense, but it's still a pretty large burden to add to any app that is simply a Vault consumer.

So, the purpose of this issue is to bring it to your attention and ask that you consider if it's possible to decouple many of the dependencies from the `vault` and `http` packages, or at least from the test helpers to run a stripped-down but still functional in-memory Vault instance.

**Comment by jefferai** [comment]
Apps that are simply Vault consumers only need the api package. You are moving from being a consumer to a developer pulling in core Vault code. That comes with extra burdens.

We may slim things down at some point but this is not considered a priority, as the testing code in that package is designed specifically for Vault development. We also make no guarantees about the API of anything in there.

Also, generally you will want to look at NewTestCluster instead.
