### ISSUE TITLE
`vault mounts` against a non leader fails

### ISSUE THREAD

**Issue by nbrownus** [hashicorp/vault#311]
This was eluded to in #217.

```
$ vault mounts
Error reading mounts: Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/mounts
Code: 500. Errors:

* Vault is in standby mode
```

Should this command not proxy over to the leader? Same problem with `unmounts` and `mount`

**Comment by armon** [comment]
Hmm weird that this doesn't do the redirect, thanks for the report.

**Comment by consultantRR** [comment]
Same for `auth`:

```
# vault auth -methods
Error reading auth table: Error making API request.

URL: GET https://vault.service.testdc.soa.ebi:8200/v1/sys/auth
Code: 500. Errors:

* Vault is in standby mode
```

**Comment by ekristen** [comment]
This is getting to be a big problem for me, when using the SSH backend, just about everytime the key is unable to be revoked because it returns 'standby mode' 

Do we know what the exact cause of this is? I would really like to try and help fix this. Thanks!

**Comment by jefferai** [comment]
This should actually have been fixed yesterday by 2920cddc9; can you make sure that your build is current on all of your nodes?

**Comment by ekristen** [comment]
@jefferai seeing the problem on `revoke` too, I just built from master this morning.

Seems like policies and mounts work right now though! :)

**Comment by jefferai** [comment]
Yes, all of the /sys mounts need to be fixed. I am hoping they all will be
for 0.3.

**Comment by jefferai** [comment]
This should have been fixed a while back, but this was never closed. Closing now!
