### ISSUE TITLE
POST /v1/transit/verify: unclear what "format" parameter does

### ISSUE THREAD

**Issue by kevinburke** [hashicorp/vault#3116]
The documentation here: https://www.vaultproject.io/api/secret/transit/index.html#verify-signed-data

has a "format" parameter:

> format (string: "hex") – Specifies the output encoding. This can be either hex or base64.

However, the "Sample Response" contains only a single boolean value:

```
{
  "data": {
    "valid": true
  }
}
```

It's unclear how the formatting would change based on the provided input.

**Comment by jefferai** [comment]
Clearly a docs mistake, a PR to fix would be welcomed!

**Comment by jefferai** [comment]
Fixed by #3152
