### ISSUE TITLE
POST /v1/transit/create: 204 on second attempt to create the same key

### ISSUE THREAD

**Issue by kevinburke** [hashicorp/vault#3117]
If I create a key by making a POST request to /v1/transit/create/my-key with no `type`, and then attempt to make a second request to the same endpoint with a specified key `type`, I get a 204 Created.

However, the key does not change or is not regenerated to match the new type. I would expect the second create attempt to error with a "key already exists" message.

**Comment by kevinburke** [comment]
I'm running the in-memory Vault mode, `Vault v0.7.3 ('0b20ae0b9b7a748d607082b1add3663a28e31b68')`

**Comment by jefferai** [comment]
It actually acts idempotently on purpose to make is easier to write scripts! Not all Vault behaves this way but we try to strive for idempotentcy.

**Comment by kevinburke** [comment]
OK - I guess the problem is that the second Create attempt has different parameters than the first. I'm not trying to create the same thing. In this case, I expected a 204 to mean "we updated the key to match the new type" but instead it means "we silently ignored your request"

**Comment by jefferai** [comment]
I guess we could check parameters and return an error if there is a mismatch. I don't feel strongly about it. If you want to put together a PR I'd be happy to look.
