### ISSUE TITLE
[FEATURE REQUEST] Docker auth backend

### ISSUE THREAD

**Issue by nasskach** [hashicorp/vault#3118]
**Feature Request:**
Hi,

I wanted to suggest the idea of a docker auth backend for Vault that could use the labeling mechanism implemented by Docker to automatically assign policies to the various containers.

Vault could run in a specific container with access to the docker socket, that would allow it to use the Docker API to retrieve the necessary information (labels and container IDs).

The basic idea is that when the client try to authenticate, it will send his container ID and the Vault server will use that ID with the docker API to lookup a specific label (let's say vault.policy) and assign the policy in value.

This could be compatible with Docker and Docker Swarm Mode.

What is your opinion on this?

Thank you.

**Comment by jefferai** [comment]
I think this is great functionality but better implemented by the orchestration system managing the container lifecycle. Many can already integrate with Vault, so adding support for labels is something they can easily add.

Thanks for the idea though!
