### ISSUE TITLE
HTTP API docs for auth backends

### ISSUE THREAD

**Issue by nevir** [hashicorp/vault#312]
I'm not sure if they should be blueprinted in [`SPEC.md`](https://github.com/hashicorp/vault/blob/master/api/SPEC.md), or a separate blueprint - but it'd be nice to document the actions each auth backend supports, as well.  (For instance, `/auth/token/create`, etc)

**Comment by nevir** [comment]
Actually, they *are* there on doc pages: https://www.vaultproject.io/docs/auth/token.html

Maybe just some links in the main API docs section?

**Comment by armon** [comment]
I'm not sure where we else could link to it, since we do link to it from the `Auth` section already

**Comment by nevir** [comment]
Hmm, that link's broken on the deployed docs: https://www.vaultproject.io/docs/http/index.html

**Comment by nevir** [comment]
Hmm, well, the token backend is the only one that provides [in depth API docs coverage](https://www.vaultproject.io/docs/auth/token.html)

I think it'd be valuable to have similar docs for the other auth backends. Most of them just have a generic "The endpoin is `/login`." w/o much more explanation, currently

**Comment by jszwedko** [comment]
Yeah, I had the same experience trying to determine the API for the `app-id` backend. Only the `token` backend seems to have documentation.

**Comment by orclev** [comment]
I still haven't worked out the API for app-id. I was actually looking through here because I was considering opening an issue about it.

**Comment by phylake** [comment]
@nevir Do you have a `curl` command that works for you?

After following [the instructions](http://vaultproject.io/docs/auth/app-id.html) I've pieced together variations of `curl -iX POST -d app_id=my_app_id -d user_id=some_user "$VAULT_ADDR/v1/auth/app-id/login"` but get a 400 with `{"errors":["invalid character 'a' looking for beginning of value"]}`

Time to go spelunking too I suppose.

**Comment by sethvargo** [comment]
Does this help? https://github.com/hashicorp/vault/blob/master/website/source/intro/getting-started/apis.html.md

**Comment by phylake** [comment]
It does, thanks. Looks like `POST`, `PUT`, and `GET` all work for that API, btw.

**Comment by masonoise** [comment]
I'm glad to see this re-opened recently, because I also found that there's no detailed API documentation for the auth back-ends. As an example, I see that on the app-id back-end page (https://www.vaultproject.io/docs/auth/app-id.html) it shows the CLI with the `cidr-block` option for mapping a user-id, but I cannot find any API documentation that describes whether that's available in the `/app-id/map/user-id` endpoint. I'll just have to experiment or look through the source. Really, there's no documentation anywhere for the auth APIs. I just took the examples in the getting started section and hacked on them. Please add these API docs.

**Comment by jefferai** [comment]
@masonoise `cert`, `userpass`, and `token` have API docs, but the others have not been updated with them. PRs welcome!

**Comment by aantono** [comment]
Specific question about `app-id` `cidr-block` configuration - Does it take a comma-separated list of CIDR values, or is it only supporting a single block?

**Comment by vishalnayak** [comment]
Hi Alex,

App-ID backend only supports a single block.

You might be interested in looking at
https://github.com/hashicorp/vault/pull/1426, which could do all that
App-ID does, plus more. This supports CIDR list as opposed to CIDR blocks.

Regards,
Vishal

On Fri, Jul 8, 2016 at 12:09 PM, Alex Antonov <notifications@github.com>
wrote:

> Specific question about app-id cidr-block configuration - Does it take a
> comma-separated list of CIDR values, or is it only supporting a single
> block?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hashicorp/vault/issues/312#issuecomment-231401424>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC6YaPdxp-wwV2ZN9e_XTp5nknArq5vRks5qTnZAgaJpZM4E25Nz>
> .
>



-- 
vn

**Comment by richard-mauri** [comment]
I'm looking for how to work the http api to set non default TTL for tokens creating by logging in with APPID. It's tough to find the recipe.
