### ISSUE TITLE
Plugin sample repo

### ISSUE THREAD

**Issue by ror6ax** [hashicorp/vault#3128]
Hi, is there an sample vault database plugin repo somewhere?

I'm experiencing problems, following the official guide. Also, do you plan to keep track of the plugins out there? I'd like to make my work as aligned with your vision as possible.

Thanks.

**Comment by calvn** [comment]
Hi there! Please use the [Vault Mailing List](https://groups.google.com/forum/#!forum/vault-tool) for these kinds of questions. There is already an [answered thread](https://groups.google.com/forum/#!topic/vault-tool/36EXV4BaJfo) with respect to this specific question.
