### ISSUE TITLE
Root-is-not-God Policy?

### ISSUE THREAD

**Issue by kristofer** [hashicorp/vault#314]
Any chance you guys have thought about build a way to config this so that Root is not God?
In your model, root has acess to everything. 

But there are useful configs where root can configure a backend on behalf of a client, but does not have access to anything the client puts into the backend. Root could revoke/destroy or freeze/unfreeze a backend on behalf of some kind of real world authority, but only a subset of vault system identities would have read/write access to that backend...and the server admin would not be one of them.

I could store secrets on behalf of a customer, but my root-admin would not be able to "see" those secrets.

Cool stuff, and in Golang no less!

**Comment by armon** [comment]
@kristofer Yes! Specifically, the ACL language supports setting a policy to "sudo" to give a non-root user permission to do something. There is no way to have a root user that is not god, but there IS a way to have a non-root user perform a root action.

As an example the `sys/seal` endpoint is root privileged. But you could make a policy "sealers" like:

```
path "sys/seal" {
   policy = "sudo"
}
```

This would allow any client with the "sealers" policy to invoke `sys/seal` as if they were root. Hope that helps!

**Comment by kristofer** [comment]
I see the sudo capabilities. But that's not the issue here. The reason that Snowden could do what he did is because of the overriding model of Unix is having a root user that can "see" everything. The issue is that we could be building systems like vault with a slightly different premise. Just like your model can use, but not trust, a storage subsystem, we should be thinking about building something that might not trust its administrators to have a "root" access to all aspects of a system. Several real world authorities do this, there are law enforcement agencies that do not allow an tech admin access to certain aspects of a system (like what's stored in it) even tho those same admins can revoke or "break glass" a system's capabilities under orders from a senior authority to restrict or shut it down.

If there was a system that allowed an admin to create a secure secret storage that they could then delegate to a sub-admin, or even a mere user as client, who has the only read/write authority? (I am assuming that the root user in a vault system does in fact have a way of reading any secret stored in any Secret Backend?)

You have a model of sealing/unsealing a vault, and of a Barrier - maybe the system could act more like a safe-deposit box system, where, the vault unsealing then allows a client or a sub-admin to bring there they own unsealing keys to open, only to the client, the secrets inside the smaller, enclosed sub-vault. So perhaps, it's a Vault of Vaults? In production, an admin starts and unseals the Outer Vault, and its associated Secret Backends, but then clients can come along, unseal their sub Vault and do their stuff and seal it again as needed??

Imagine an app that holds your secrets, and 

- uses encryption keys to protect those secrets, 
- generated for you by a "vault service" backend, 
- stored by a company's vault-service, 
- but the vault-service company cannot see your keys, not even in an "escrow" sense. 

Cheers!

**Comment by armon** [comment]
@kristofer It is totally possible to use Vault like this. There is no need to use the "root" level policy for users at all. You need something that is equivalent to root or "system" level privilege at the beginning to configure the system itself, but for day-to-day you can make finer grained policies and never give out root access to operators.

**Comment by AaronTorgerson** [comment]
@armon Is there a resource where best practices for a "least-privileged" admin policy are spelled out? For example, there are many paths under 'sys' that configure various aspects of the system. Which actions on these are "safe" for a least-privileged admin policy to have? In order to avoid having root tokens lying around and to avoid resorting to generating new ones on a regular basis, it seems that an ideal setup would allow for admins to make certain types of changes and to be able to read certain values without opening up attack vectors unnecessarily. Or would you say that it's best not to have admin policies at all, and that root token generation/revocation is the preferred way to go? 

Thanks in advance for any guidance.

**Comment by armon** [comment]
@AaronTorgerson The ideal "least-privileged" admin policy is the one that gives access _only_ to the operations an administrator needs to perform. Any additional capabilities that are unused is a potential security risk. This means that it really depends on your organizations use of Vault and what operations an admin needs to perform. For example, if only the `generic` backend is used an admin has no need to mount/unmount backends and it should not be granted. Some organizations create a backend per-tenant, and so it's a relatively common operation that is essential.

Does that help at all? Sorry that we cannot give a specific policy, as it is extremely use case dependent.

**Comment by AaronTorgerson** [comment]
Yes, thanks a lot. I think the answer for me is that I need to understand what each path under 'sys/' is for and what each action does for that path.
