### ISSUE TITLE
Unseal vault failing

### ISSUE THREAD

**Issue by ssubramanian123** [hashicorp/vault#3140]
Hi,

We are having issue with unseal vault. When we try to unseal with the keys getting below error... any reason..

```URL: PUT https://vault.vault:8200/v1/sys/unseal
Code: 500. Errors:
 * expiration state restore failed: failed to read lease entry: decryption failed: cipher: message authentication failed
```

**Comment by ssubramanian123** [comment]
@jefferai We deployed vault with backedn as mysql... it was working fine for the last couple of days... we took backup of vault-secret-config. 

Due to other issue, our nodes went down.. so we deleted vault completely and re-deployed with same mysql.. and vault-secret-config.. now we are not able to unseal vault.. it is throwing below exception.. Can you please help us what is going on here?

```
Code: 500. Errors:
 * expiration state restore failed: failed to read lease entry: decryption failed: cipher: message authentication failed```

**Comment by jefferai** [comment]
I'm taking shots in the dark here but my guess is that when you said you deleted Vault completely and redeployed with the same mysql, you also then attempted to use the same underlying data in some way?

**Comment by ssubramanian123** [comment]
@jefferai  yes, mysql had old data with role ID generated for applications. We took backup of vault-secret-config and loaded again.

**Comment by jefferai** [comment]
When you init vault fresh the keyring changes...you can't then decrypt old data.

**Comment by ssubramanian123** [comment]
@jefferai thanks for your time. During vault init, we are checking whether vault is already initialized in mysql mode if we re-use the table then it always come as initialized. In this case, we are not re-creating the root token, unseal keys. Instead re-using it from the backup. It works in most of the time. 

During unseal process, will it validate application role IDs ? During vault unseal process what lease ID it tries to refer ?

**Comment by jefferai** [comment]
If you have been using Vault, then you restore your keychain from a backup, any data written after that backup was taken will not be readable to Vault if in the interim time you rotated the keychain..

**Comment by ssubramanian123** [comment]
Thanks @jefferai on what basis key rotated? We have 5 unseal keys, not sure on which sequence it is used to unsealing process. Can we configure the rotate interval anywhere?

**Comment by jefferai** [comment]
It's run when you call "vault rotate" (or the equivalent HTTP API call).

**Comment by ssubramanian123** [comment]
Thanks @jefferai  I will close this issue, because we found some issue in token handling and your information really helped to understand the flows.. Thanks again for your support.

**Comment by jefferai** [comment]
No problem!
