### ISSUE TITLE
Request: better policy documentation.

### ISSUE THREAD

**Issue by james-lawrence** [hashicorp/vault#3144]
trying to learn how to setup policies for administration of vault, but the documentation is extremely slim beyond the basic 'here are the permission types and a few examples on how to use them'.

In particular I was looking for how to allow someone to enable a new authentication backend without a root token.

Things I found to be missing:
How do I discover what the paths are? path-help?
if path-help is the way to discover these paths how do I list all the root paths?

**Comment by peterchoo** [comment]
Bumping this:

Am currently testing out Vault for internal use, the [policy documentation here](https://www.vaultproject.io/docs/commands/policy.html) incorrectly lists the commands:

- `vault policy list`
- `vault policy write my-policy ./my-policy.hcl`
- `vault policy delete my-policy`

Where as in the CLI help output they are (at least in v0.9.1, but didn't see anything in the change log to suggest they had changed)

- `vault policies`
- `vault policy-write ...`
- `vault policy-delete`

**Comment by jefferai** [comment]
@peterchoo the documentation always corresponds to the latest released version; in 0.9.2 Vault gained a new CLI.

**Comment by peterchoo** [comment]
@jefferai Thanks, any chance the 0.9.1 documentation is available anywhere?

**Comment by jefferai** [comment]
It's in our git repo; check the Makefile in the website folder.

**Comment by peterchoo** [comment]
Thanks, I'll take a look!

**Comment by raskchanky** [comment]
The `vault policy` CLI help looks correct now and in sync with the [policy documentation](https://www.vaultproject.io/docs/commands/policy.html). I'm going to close this for now, but feel free to reopen if there's more to do here.
