### ISSUE TITLE
API Inconsistencies make writing idempotent tooling difficult

### ISSUE THREAD

**Issue by CVTJNII** [hashicorp/vault#3146]
Good day:

I'm deploying Vault in an enterprise environment and in order to support it I need an idempotent configuration management tool.  Due to an absence of such tools I'm working on my own but finding it difficult due to different backends using different paths for CRUD steps, and backends which don't return the data in the same format as the input, making diffing the current state difficult.

For CRUD being inconsistent, compare /sys/auth to /sys/policy:

|CRUD Operation|/sys/auth path|/sys/policy path|
|-----------------------|------------------|---------------------|
|Create|/sys/auth/:path|/sys/policy/:name|
|Read|/sys/auth|/sys/policy/:name|
|Update|[None: Delete and recreate]|/sys/policy/:name|
|Delete|/sys/auth/:path|/sys/policy/:name|

/sys/policy allows all CRUD operations against /sys/policy/:name, whereas /sys/auth requires different paths for the supported operation.  This is requiring me to maintain a table of backends in my code and call different methods depending on the backend to ensure the operation works.

The issue with inconsistent data formatting, however, is a larger nuisance and can be shown with the /auth/approle/role endpoint.  When creating an approle at /auth/approle/role/:role_name the policies are a comma separated list, of the form 'policy1,policy2'.  However, when reading from the endpoint policies are returned as a JSON array, in the form ["policy1", "policy2"].  This is leading to impotence problems where the approle is updated every run as the differing formats cause equality conditionals to fail.  I consider this a larger problem, as while a table of backends can be begrudgingly maintained, maintaining rules for every field of every backend is not practical.

I would like to ask that in the next API version the CRUD operations be made consistent:

- All supported CRUD operations are available on a single path, multiple paths for CRUD operations on a single, logical entity should be depricated
- The API output format should match the input format.

I believe these changes will make writing and supporting tooling around Vault much easier, and improve long term supportability of vault tooling.  Thank you.

Reference:
- /sys/auth: https://www.vaultproject.io/api/system/auth.html
- /sys/policy: https://www.vaultproject.io/api/system/policy.html
- auth/approle/role: https://www.vaultproject.io/api/auth/approle/index.html

**Comment by jefferai** [comment]
It's much more useful for us if you can split things that are giving you trouble into specific issues. We know that there are inconsistencies, and we'd like to fix them over time, but a meta-ticket saying "please don't be inconsistent" doesn't give us much guidance as we don't know what specifically is troublesome for people. For instance, we could easily add a sys/auth/:path read endpoint, but nobody has ever asked for it.

I'm going to close this as no action will come as a result. If you are running into specific blockers, please detail those individually.

**Comment by CVTJNII** [comment]
#3147 opened for approle inconsistency

**Comment by CVTJNII** [comment]
#3148, #3149, #3150, and #3151 opened for the inconsistent CRUD paths I've found thus far.
