### ISSUE TITLE
/auth/approle/role/:role_name input and output formats inconsistent

### ISSUE THREAD

**Issue by CVTJNII** [hashicorp/vault#3147]
Good day:

Currently the input and output formatting of the /auth/approle/role/:role_name endpoint is inconsistent.  When creating an approle at /auth/approle/role/:role_name the policies are a comma separated list, of the form 'policy1,policy2'. However, when reading from the endpoint policies are returned as a JSON array, in the form ["policy1", "policy2"].  This is troublesome as configuration tooling needs to handle the different formatting when comparing desired state to state in Vault to know if changes are required.

Please modify the /auth/approle/role/:role_name endpoint to use the same input and output formats.  Thanks.

**Comment by CVTJNII** [comment]
I had originally requested this as a API v2 improvement in #3146 as I'm not sure how to do this in a backwards compatible manner.  A format flag perhaps?

**Comment by jefferai** [comment]
It's actually supportable now, the field just has to have its type modified to enable it. (TypeString->TypeCommaStringSlice on line 116 of path_role.go).
