### ISSUE TITLE
/sys/audit/:path endpoint requires reading the parent endpoint for read operations

### ISSUE THREAD

**Issue by CVTJNII** [hashicorp/vault#3150]
Please create a read operation for /sys/audit/:path. Currently to read the settings of an audit backend a library must read /sys/audit and select the :path/ key in the returned hash. Implementing a data model where all CRUD operations are on the same path will make client implementations more consistent and easier to maintain.  Thank you.

**Comment by catsby** [comment]
Closing as a duplicate of https://github.com/hashicorp/vault/issues/3148
