### ISSUE TITLE
Force release/revoke leases

### ISSUE THREAD

**Issue by freman** [hashicorp/vault#3154]
**Feature Request:**
Hi.

We're using Aurora and using Vault to manage the credentials for Aurora, but we've run into a situation more than once that AWS has moved (or dropped) our Aurora host. Which leaves us with 30+ leases in Vault that it can't revoke, it seems to tie up all it's threads trying to revoke before 'giving up' until next restart. The only way we've been able to fix this is to shut down Vault and delete data from Consul.

We've also had our AWS leases fail to revoke for various reasons which has to be resolved the same way.

We're still in development, so it's ok, and probably not something we'd expect to happen in production but so annoying.

I know it's probably anti-security, but it'd be sweet if we could get the ability to force revoke the lease (ie. make Vault revoke the credentials in it's stores even if it can't do it in the remote). Perhaps limited to a root or super user token.

Something like

`PUT /sys/leases/revoke {lease_id: 123, force: 1} `

or if sticking with the path based security policies (so you can have a policy on /sys/leases/force/revoke)

`PUT /sys/leases/force/revoke {lease_id: 123}`

**Comment by jefferai** [comment]
You can already do this! See https://www.vaultproject.io/api/system/leases.html#revoke-force

**Comment by freman** [comment]
Sorry @jefferai I didn't see that, neither did the other person I was working with. I feel so blind now.

Thanks

**Comment by koenfaro90** [comment]
This hardly works - trying to revoke 100k (RabbitMQ) leases still attempts to query the backend for every one and takes forever.

**Comment by jefferai** [comment]
Force revoke doesn't skip trying to revoke, it simply says to ignore an error that comes back.

If you don't want any leases from a particular mount, you could shut down Vault, delete the corresponding entries from storage under sys/expire given your rabbit mount path, and start Vault back up.
