### ISSUE TITLE
Transit's datakey endpoint should allow upserting of keys

### ISSUE THREAD

**Issue by BRMatt** [hashicorp/vault#3155]
**Feature Request:** If I call the transit backend's `encrypt` endpoint with the name of a key that does not exist it'll automatically create the key if my token has permission to create keys.

It would be nice if transit's `datakey` endpoint also behaved like this. At the moment calling the endpoint when the key does not exist causes the operation to fail.

**Comment by jefferai** [comment]
Currently I am not in favor of this idea. It adds a lot of extra complexity to the datakey endpoint which is relatively simple otherwise. Datakey is itself just a helper to read some random bytes and call encrypt, so it's also very easy if this behavior is desired to simply do that instead.
