### ISSUE TITLE
Vault PKI With ADFS

### ISSUE THREAD

**Issue by joshw123** [hashicorp/vault#3169]
Hello All, 

I am currently trying to use Vault to Generate Certificates to work with a ADFS Host for SAML. 

When i am creating the certificates the adfs host is showing 

An error occurred during an attempt to build the certificate chain for the relying party trust,certificate identified by thumbprint '4CE1E4C8BFB7CE591B6081B3CC7AC953F9F1A3D2'. Possible causes are that the certificate has been revoked, the certificate chain could not be verified as specified by the relying party trust's signing certificate revocation settings or certificate is not within its validity period.

Has anyone ever had any experience with anything like this before? 

Many Thanks

Josh

**Comment by jefferai** [comment]
Hi Josh,

Please use the mailing list (https://groups.google.com/forum/#!forum/vault-tool) for general questions. We try to keep the issue tracker reserved for bug reports and pull requests.

Thanks!
