### ISSUE TITLE
PKI should honor HTTP If-Modified-Since for ./ca and ./crl requests

### ISSUE THREAD

**Issue by jasonmf** [hashicorp/vault#3190]
**Feature Request:**

When making HTTP requests to vault to fetch `/v1/pki/ca` and `/v1/pki/crl`, the server does not honor the `If-Modified-Since` HTTP header. This results in those data sets being downloaded redundantly when the client already has the newest version.

**Environment:**

* Vault Version:
Vault v0.7.3+ent.hsm ('c977e7cb4beb56273a9e65f2e2380b2646f4a627') (cgo)

* Operating System/Architecture:
CentOS 6.6

**Expected Behavior:**
When all of these are true:
-   requesting either `/v1/pki/crl` or `/v1/pki/ca`
-   An HTTP `If-Modified-Since` header is supplied
-   The date specified in `If-Modified-Since` is more recent than any changes to the CA or CRL data sets
The server should return a 304 without any body; the Last-Modified header will contain the date of last modification.

**Actual Behavior:**
The server returns a 200 with the full contents of the files, causing the data to be downloaded redundantly.

```
[foo@foo-research ~]$ rm crl
[foo@foo-research ~]$ wget ${VAULT_ADDR}v1${HTTPSCAPATH}/crl --no-check-certificate --debug -N
Setting --timestamping (timestamping) to 1
DEBUG output created by Wget 1.18 on linux-gnu.

Reading HSTS entries from /home/foo/.wget-hsts
URI encoding = ‘UTF-8’
Converted file name 'crl' (UTF-8) -> 'crl' (UTF-8)
--2017-08-16 20:51:18--  https://vault.bar.example.com:8200/v1/ca/bar-https/crl
Resolving vault.bar.example.com (vault.bar.example.com)... 10.201.49.97, 10.201.50.32
Caching vault.bar.example.com => 10.201.49.97 10.201.50.32
Connecting to vault.bar.example.com (vault.bar.example.com)|10.201.49.97|:8200... connected.
Created socket 3.
Releasing 0x0000000000e60580 (new refcount 1).
Initiating SSL handshake.
Handshake successful; connected socket 3 to SSL handle 0x0000000000e75080
certificate:
  ...

---request begin---
GET /v1/ca/bar-https/crl HTTP/1.1
User-Agent: Wget/1.18 (linux-gnu)
Accept: */*
Accept-Encoding: identity
Host: vault.bar.example.com:8200
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 200 OK
Cache-Control: no-store
Content-Type: application/pkix-crl
Date: Wed, 16 Aug 2017 20:49:09 GMT
Content-Length: 445

---response end---
200 OK
Registered socket 3 for persistent reuse.
Length: 445 [application/pkix-crl]
Saving to: ‘crl’

crl                                                100%[================================================================================================================>]     445  --.-KB/s    in 0s      

Last-modified header missing -- time-stamps turned off.
2017-08-16 20:51:18 (109 MB/s) - ‘crl’ saved [445/445]
[foo@foo-research ~]$ wget ${VAULT_ADDR}v1${HTTPSCAPATH}/crl --no-check-certificate --debug -N
Setting --timestamping (timestamping) to 1
DEBUG output created by Wget 1.18 on linux-gnu.

Reading HSTS entries from /home/foo/.wget-hsts
URI encoding = ‘UTF-8’
Converted file name 'crl' (UTF-8) -> 'crl' (UTF-8)
--2017-08-16 20:51:53--  https://vault.bar.example.com:8200/v1/ca/bar-https/crl
Resolving vault.bar.example.com (vault.bar.example.com)... 10.201.50.32, 10.201.49.97
Caching vault.bar.example.com => 10.201.50.32 10.201.49.97
Connecting to vault.bar.example.com (vault.bar.example.com)|10.201.50.32|:8200... connected.
Created socket 3.
Releasing 0x0000000000e0d590 (new refcount 1).
Initiating SSL handshake.
Handshake successful; connected socket 3 to SSL handle 0x0000000000e220b0
certificate:
  ...

---request begin---
GET /v1/ca/bar-https/crl HTTP/1.1
If-Modified-Since: Wed, 16 Aug 2017 20:51:18 GMT
User-Agent: Wget/1.18 (linux-gnu)
Accept: */*
Accept-Encoding: identity
Host: vault.bar.example.com:8200
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 200 OK
Cache-Control: no-store
Cache-Control: no-store
Content-Type: application/pkix-crl
Date: Wed, 16 Aug 2017 20:49:44 GMT
Content-Length: 445

---response end---
200 OK
Registered socket 3 for persistent reuse.
Length: 445 [application/pkix-crl]
Saving to: ‘crl’

crl                                                100%[================================================================================================================>]     445  --.-KB/s    in 0s      

Last-modified header missing -- time-stamps turned off.
2017-08-16 20:51:53 (115 MB/s) - ‘crl’ saved [445/445]
```

**Steps to Reproduce:**

1. Establish a PKI mount
1. Configure the PKI mount's URLs
1. Request the contents of those URLs without making changes

**Important Factoids:**
My specific intent is to provide that data via a dedicated web server. I'd like to pull the data periodically and not have to download it repeatedly when it hasn't changed.

**References:**
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since

**Comment by jefferai** [comment]
An update to this: you can now enable headers to be passed to mounts, so while this isn't yet supported in its entirety, it's now possible to add this just with some code in the PKI backend.

**Comment by cipherboy** [comment]
@jasonmf \o Thanks to @Gabrielopesantos, support for this has just merged into Vault! Feel free to give it a try and let us know what you think. Note that you'll have to tune the mount (to add `If-Modified-Since` to `passthrough_request_headers`) before using it.

**Comment by Gabrielopesantos** [comment]
> @jasonmf \o Thanks to @Gabrielopesantos, support for this has just merged into Vault! Feel free to give it a try and let us know what you think. Note that you'll have to tune the mount (to add `If-Modified-Since` to `passthrough_request_headers`) before using it.


Given Jasonmf's request, isn't also necessary to add `Last-Modified` to `allowed-response-headers`?

**Comment by cipherboy** [comment]
Ahh, no, you've got a point there. :-) I should add that to the docs, thank you!
