### ISSUE TITLE
Feature request: Support custom CA cert in Database secret backend config

### ISSUE THREAD

**Issue by vreon** [hashicorp/vault#3191]
**Feature Request:**

When configuring the `database` secret backend to connect to a MySQL database, you can specify `?tls=true`, `false`, or `skip-verify` in the `connection_url` DSN, but there's no mechanism for providing a custom CA certificate (e.g. for a private CA).

`go-sql-driver/mysql` supports a `?tls=<name>` option, but `<name>` must first be registered with [`mysql.RegisterTLSConfig`](https://godoc.org/github.com/go-sql-driver/mysql#RegisterTLSConfig). (For example, the [MySQL storage backend](https://github.com/hashicorp/vault/blob/0ac531d3f400818af2ad80ee59c8bcfdaca705a6/physical/mysql/mysql.go#L84-L92) uses this to implement the `tls_ca_file` setting.)

**References:**

Mailing list discussion: https://groups.google.com/d/msg/vault-tool/QEQ-07CLNpo/zORnEe3yCAAJ

**Comment by martinssipenko** [comment]
It looks to me that this was implemented by #9181?

cc @jefferai @vreon

**Comment by Andor** [comment]
@martinssipenko Close enough, but not all mysql features are supported. For instance, there are no client authorisation with certificates. (which also could be signed by Vault CA).

**Comment by martinssipenko** [comment]
What do you mean @Andor? Isn’t `tls_certificate_key` exactly for specifying a TLS cert for mutual TLS (client auth with certs).

**Comment by vreon** [comment]
Thanks for the heads up, @martinssipenko! Closing this as fixed.

**Comment by Andor** [comment]
@martinssipenko Oh, yeah, you are right!
