### ISSUE TITLE
proxy_protocol_behavior problem using AppRole

### ISSUE THREAD

**Issue by antimack** [hashicorp/vault#3196]
Hi guys, 

Maybe some of you can help me realize what I'm doing wrong. I have recently updated our Vault to the latest 0.8.1 version. I have Nginx server running in front of Vault which is configured as reverse proxy with upstream pointing to Vault locally at 127.0.0.1:8200, both Vault and Nginx are running in Docker containers with "host" network on ec2(AWS) instance, Nginx is configured to pass headers and I can see real IP address in the logs when querying Nginx with curl. We are using AppRoles for our applications and from the beginning, I wanted to secure them with "bound_cidr_list" which wasn't possible since the PROXY protocol wasn't supported. I tried now, have played with different settings for "proxy_protocol_behavior" and "proxy_protocol_authorized_addrs" but all the time I'm trying to login using role-id and secret-id I have "* failed to validate SecretID: source address "127.0.0.1" unauthorized through CIDR restrictions on the role", if I add  "bound_cidr_list=127.0.0.1" it works but I can't make Vault to check real IP address. In audit file, I can see always that "remote_address":"127.0.0.1" but headers are ""headers":{"x-forwarded-for":["94.X.X.X, 94.X.X.X"],"x-real-ip":["94.X.X.X"]}}".

* Vault Version:
Server: 0.8.1
Client: 0.8.0

**Expected Behavior:**
Vault and AppRole should see real IP address from headers as a source IP with proxy protocol enabled
**Actual Behavior:**
Vault and AppRole always seeing "127.0.0.1" as a source IP

**Comment by jefferai** [comment]
Proxy protocol refers to https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt -- Vault does not work with X-Forwarded-For or X-Real-IP at the moment.

**Comment by nuriel77** [comment]
Would be great to have this supported. Facing the same issue. Thanks.
