### ISSUE TITLE
default config for cli?

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/vault#320]
Is there a default config file that I could create for making cli calls to vault? I was thinking of similar to the way aws cli commands work where I could have a `[default]` or N number of alternate profiles. This would be nice for me because we only have 1 vault server (will be HA later but still a single domain name) and it is a pain to have to always type the `-address FQDN` when I'm trying to interact with the vault server from my desktop.

Thanks, Mike

**Comment by sethvargo** [comment]
Hi @mtougeron 

You can set the `VAULT_ADDR` environment variable :smile:

**Comment by mtougeron** [comment]
Cool, that'll help. Is there a place I can look to find what environment variables are supported? I tried looking in the docs but I may have missed it.

It'd still be really nice to have a config option too.

**Comment by nelsonenzo** [comment]
came across this and thought it might help you @sethvargo https://github.com/hashicorp/vault/pull/508/files

**Comment by brianshumate** [comment]
Supported environment variables are documented here:

https://www.vaultproject.io/docs/commands/environment.html

With that, I'm going to close this issue as it's quite dated.

**Comment by mtougeron** [comment]
@brianshumate yeah, this is definitely out of date :) thanks.
