### ISSUE TITLE
Sometimes client requests fail with "no cached connection was available"

### ISSUE THREAD

**Issue by jdeppe-pivotal** [hashicorp/vault#3203]
**Feature Request:**

The vault client library is being used in Concourse (http://concourse.ci - http://github.com/concourse/concourse). Occasionally the client code emits errors like this:
```
Finding variable 'docker-username': Get https://vault01.foo.com:8200/v1/concourse/main/docker-username: http2: no cached connection was available
```
This appears to be related here: https://github.com/golang/go/issues/16582 (an issue fixed in go 1.8)

This request is to update your use of http2 (`golang.org/x/net/http2`) to that included with 1.8 (I guess by implication that means only supporting golang >= 1.8).

Thanks.

**Comment by vito** [comment]
Is this fixed or something?

**Comment by jefferai** [comment]
@vito It's unclear this was ever a problem since multiple recent Vault versions have been built against Go 1.8. I think that's why the OP closed it.

**Comment by EugenMayer** [comment]
its not fixed for me, i am using vault 0.9.0. , i have this pretty often right now. Means, every 30 minutes. It seems it is not based on a single request - all requests made in that timeframe are getting those 

`Finding variable 'docker.password': Get https://vault:8200/v1/secret/concourse/infra/docker_base/docker: http2: no cached connection was available`

Looking at the vault logs, nothing logged at all. Coming from the same background as vito here, using concourse.

Could that be a connection pooling issue on the client side (implementation) ?

**Comment by jefferai** [comment]
Depending on the concourse version you may have one that is built with a Go version where this is not fixed. Remember, this is a client issue, not a server issue. The OP probably needs to provide any further advice as I don't know much about concourse, and they closed it themselves.

**Comment by EugenMayer** [comment]
@jefferai using the newest concourse stable, 3.6.0 - i would expect 1.9, but i am not sure.

**Comment by jefferai** [comment]
Unfortunately I think you need to file this as a bug against concourse. I can honestly say I've no memory of hearing of this issue anywhere else and they seem to think it's resolved.

**Comment by MayaKhan12** [comment]
any method to close the connection forcefully.
var microsoftSqlConnectionInfo = new MicrosoftSqlConnectionInfo
{
    ConnectionString = "server=localhost\sqlexpress;port=1433;user id=sa;password=****;database=master;app name=vault",
    MaximumOpenConnections = 5,
    VerifyConnection = true
};
await vaultClient.MicrosoftSqlConfigureConnectionAsync(microsoftSqlConnectionInfo, mountPoint);
as on last line application throw following exception "System.Exception: '400 BadRequest. {"errors":["Error validating connection info: failed to send SQL Batch: write tcp [::1]:9468-\u003e[::1]:1433: wsasend: An existing connection was forcibly closed by the remote host."]}"
