### ISSUE TITLE
Accept HTTP GET method on endpoints that currently allow LIST only

### ISSUE THREAD

**Issue by alvaroaleman** [hashicorp/vault#3216]
Hello,

Playing around with the API a little, I found there are some endpoints that only supports LIST as http method, e.G. the one for getting approles: https://www.vaultproject.io/api/auth/approle/index.html#list-roles

This is somewhat inconvenient because popular language bindings don't support it, e.g.

* [Golang net/http](https://golang.org/pkg/net/http/#Client)
* [Python requests](http://docs.python-requests.org/en/master/user/advanced/#http-verbs)

The missing support may be a result of LIST not being part of [RFC 7231 which defines HTTP/1.1 ](https://tools.ietf.org/html/rfc7231#page-24).

Would it be possible to make the endpoints that currently support LIST only accept GET as well instead of returning a 405?

Regards

**Comment by jefferai** [comment]
You can use `list=true` as a query parameter with GET; see https://www.vaultproject.io/api/index.html

It's also entirely possible to use a LIST verb with most libraries, including Golang and Python -- the RFC doesn't define an exhaustive list, just basic requirements.

Golang: set your Request method to LIST (https://golang.org/pkg/net/http/#Request), which can also be done in NewRequest directly.

Python: http://docs.python-requests.org/en/master/user/advanced/#custom-verbs

**Comment by ethanhs** [comment]
When I try to do the following I get a 400:

```python
from urllib.request import Request, urlopen
urlopen(Request(url='https://server/v1/mount/metadata/folder', headers={'X-Vault-Token': 'my-token'}, method='LIST'))
```

I get a 400 Bad Request error.

Currently I am working around it with using the query parameter/GET workaround:
```python
from urllib.request import Request, urlopen
urlopen(Request(url='https://server/v1/mount/metadata/folder?list=true', headers={'X-Vault-Token': 'my-token'}, method='GET'))
```

but this seems less than ideal.
