### ISSUE TITLE
Panic when attempting to login using CERT

### ISSUE THREAD

**Issue by lcbowen3** [hashicorp/vault#322]
When attempting to auth using cert backend:

[root@ip-10-16-43-125 ~]# curl -v -X PUT --cert "./scripts.crt" --key "./scripts.key" https://10.16.19.21:8000/v1/auth/cert/login
*   Trying 10.16.19.21...
* Connected to 10.16.19.21 (10.16.19.21) port 8000 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS: client certificate from file
*       subject: CN=Scripts,OU=dept,O=company,L=city,ST=state,C=US
*       start date: Jun 04 15:32:01 2015 GMT
*       expire date: Jul 04 15:32:01 2015 GMT
*       common name: Scripts
*       issuer: CN=Scripts,OU=dept,O=company,L=city,ST=state,C=US
* SSL connection using TLS_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
*       subject: CN=*,O=company,L=city,ST=state,C=US
*       start date: Jun 04 20:11:19 2015 GMT
*       expire date: Oct 19 20:11:19 2042 GMT
*       common name: *
*       issuer: CN=*,O=company,L=city,ST=state,C=US
> PUT /v1/auth/cert/login HTTP/1.1
> User-Agent: curl/7.40.0
> Host: 10.16.19.21:8000
> Accept: */*
>
* Empty reply from server
* Connection #0 to host 10.16.19.21 left intact
curl: (52) Empty reply from server

I get a panic in the Vault Server log:

```
2015/06/05 16:29:41 http: panic serving 10.16.43.125:33055: unsupported type: ptr
goroutine 36 [running]:
net/http.func·011()
 /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/mitchellh/reflectwalk.walk(0x8edde0, 0xc20864f3f0, 0x16, 0xaf76a0, 0xc2086ba1c0, 0x0, 0x0)
 /root/go-code/src/github.com/mitchellh/reflectwalk/reflectwalk.go:139 +0x420
github.com/mitchellh/reflectwalk.walkStruct(0xb0a420, 0xc208040480, 0xd9, 0xaf76a0, 0xc2086ba1c0, 0x0, 0x0)
 /root/go-code/src/github.com/mitchellh/reflectwalk/reflectwalk.go:274 +0x44a
github.com/mitchellh/reflectwalk.walk(0xb0a420, 0xc208040480, 0xd9, 0xaf76a0, 0xc2086ba1c0, 0x0, 0x0)
 /root/go-code/src/github.com/mitchellh/reflectwalk/reflectwalk.go:136 +0x516
github.com/mitchellh/reflectwalk.walkSlice(0x910760, 0xc208685330, 0xd7, 0xaf76a0, 0xc2086ba1c0, 0x0, 0x0)
 /root/go-code/src/github.com/mitchellh/reflectwalk/reflectwalk.go:228 +0x346
github.com/mitchellh/reflectwalk.walk(0x910760, 0xc208685330, 0xd7, 0xaf76a0, 0xc2086ba1c0, 0x0, 0x0)
 /root/go-code/src/github.com/mitchellh/reflectwalk/reflectwalk.go:133 +0x4bd
github.com/mitchellh/reflectwalk.walkStruct(0xad6880, 0xc208685300, 0xd9, 0xaf76a0, 0xc2086ba1c0, 0x0, 0x0)
 /root/go-code/src/github.com/mitchellh/reflectwalk/reflectwalk.go:274 +0x44a
github.com/mitchellh/reflectwalk.walk(0xad6880, 0xc208685300, 0xd9, 0xaf76a0, 0xc2086ba1c0, 0x0, 0x0)
 /root/go-code/src/github.com/mitchellh/reflectwalk/reflectwalk.go:136 +0x516
github.com/mitchellh/reflectwalk.walkStruct(0xa69500, 0xc2086b81c0, 0xd9, 0xaf76a0, 0xc2086ba1c0, 0x0, 0x0)
 /root/go-code/src/github.com/mitchellh/reflectwalk/reflectwalk.go:274 +0x44a
github.com/mitchellh/reflectwalk.walk(0xa69500, 0xc2086b81c0, 0xd9, 0xaf76a0, 0xc2086ba1c0, 0x0, 0x0)
 /root/go-code/src/github.com/mitchellh/reflectwalk/reflectwalk.go:136 +0x516
github.com/mitchellh/reflectwalk.walkStruct(0xad7760, 0xc208685380, 0xd9, 0xaf76a0, 0xc2086ba1c0, 0x0, 0x0)
 /root/go-code/src/github.com/mitchellh/reflectwalk/reflectwalk.go:274 +0x44a
github.com/mitchellh/reflectwalk.walk(0xad7760, 0xc208685380, 0xd9, 0xaf76a0, 0xc2086ba1c0, 0x0, 0x0)
 /root/go-code/src/github.com/mitchellh/reflectwalk/reflectwalk.go:136 +0x516
github.com/mitchellh/reflectwalk.Walk(0xa8f740, 0xc208685380, 0xaf76a0, 0xc2086ba1c0, 0x0, 0x0)
 /root/go-code/src/github.com/mitchellh/reflectwalk/reflectwalk.go:70 +0x137
github.com/mitchellh/copystructure.Copy(0xa8f740, 0xc208685380, 0x0, 0x0, 0x0, 0x0)
 /root/go-code/src/github.com/mitchellh/copystructure/copystructure.go:12 +0xa5
github.com/hashicorp/vault/builtin/audit/syslog.(*Backend).LogRequest(0xc2083b1c60, 0x0, 0xc208685380, 0x0, 0x0)
 /root/go-code/src/github.com/hashicorp/vault/builtin/audit/syslog/backend.go:64 +0x11c
github.com/hashicorp/vault/vault.(*AuditBroker).LogRequest(0xc2083afad0, 0x0, 0xc208685380, 0x0, 0x0)
 /root/go-code/src/github.com/hashicorp/vault/vault/audit.go:273 +0x272
github.com/hashicorp/vault/vault.(*Core).handleLoginRequest(0xc20808e000, 0xc208685380, 0x0, 0x0, 0x0)
 /root/go-code/src/github.com/hashicorp/vault/vault/core.go:460 +0x151
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc20808e000, 0xc208685380, 0x0, 0x0, 0x0)
 /root/go-code/src/github.com/hashicorp/vault/vault/core.go:343 +0x173
github.com/hashicorp/vault/http.request(0xc20808e000, 0x7fa84411b4a8, 0xc20867b400, 0xc2083b5040, 0xc208685380, 0x5, 0x0)
 /root/go-code/src/github.com/hashicorp/vault/http/handler.go:78 +0x32
github.com/hashicorp/vault/http.func·002(0x7fa84411b4a8, 0xc20867b400, 0xc2083b5040)
 /root/go-code/src/github.com/hashicorp/vault/http/logical.go:75 +0x62b
net/http.HandlerFunc.ServeHTTP(0xc208055780, 0x7fa84411b4a8, 0xc20867b400, 0xc2083b5040)
 /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc2082b0c00, 0x7fa84411b4a8, 0xc20867b400, 0xc2083b5040)
 /usr/local/go/src/net/http/server.go:1541 +0x17d
github.com/hashicorp/vault/http.func·001(0x7fa84411b4a8, 0xc20867b400, 0xc2083b5040)
 /root/go-code/src/github.com/hashicorp/vault/http/help.go:18 +0x128
net/http.HandlerFunc.ServeHTTP(0xc2082b3840, 0x7fa84411b4a8, 0xc20867b400, 0xc2083b5040)
 /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc2082aa420, 0x7fa84411b4a8, 0xc20867b400, 0xc2083b5040)
 /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208065180)
 /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
 /usr/local/go/src/net/http/server.go:1751 +0x35e
```

Latest version (today), but had the same issue yesterday with an earlier version of 0.1.3.
[root@ip-10-16-19-21 vault]# vault --version
Vault v0.1.3-dev (a0ad309d1f72aebe13dadf1f327ecefa9f45eef8)

Thanks

**Comment by lcbowen3** [comment]
Based on a conversation with Armon, I disabled the audit backend and the cert verification works -- here's the output of the curl command with all audit backends disabled.  The panic happens if any audit backend is enabled - I've tried both file and syslog.  The contents of the audit file are below (after the cert message).

[root@ip-10-16-43-125 ~]# curl -v -X PUT --cert "./scripts.crt" --key "./scripts.key" https://10.16.19.21:8000/v1/auth/cert/login
*   Trying 10.16.19.21...
* Connected to 10.16.19.21 (10.16.19.21) port 8000 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS: client certificate from file
*       subject: CN=Scripts,OU=Development,O=company,L=city,ST=state,C=US
*       start date: Jun 04 15:32:01 2015 GMT
*       expire date: Jul 04 15:32:01 2015 GMT
*       common name: Scripts
*       issuer: CN=Scripts,OU=Development,O=company,L=city,ST=state,C=US
* SSL connection using TLS_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
*       subject: CN=*,O=company,L=city,ST=state,C=US
*       start date: Jun 04 20:11:19 2015 GMT
*       expire date: Oct 19 20:11:19 2042 GMT
*       common name: *
*       issuer: CN=*,O=company,L=city,ST=state,C=US
> PUT /v1/auth/cert/login HTTP/1.1
> User-Agent: curl/7.40.0
> Host: 10.16.19.21:8000
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Set-Cookie: token=b19af615-2870-76f0-f0a8-49e7e218f21a; Path=/; Expires=Tue, 07 Jun 2016 13:49:43 UTC
< Date: Mon, 08 Jun 2015 13:49:43 GMT
< Content-Length: 233
<
{"lease_id":"","renewable":false,"lease_duration":0,"data":null,"auth":{"client_token":"b19af615-2870-76f0-f0a8-49e7e218f21a","policies":["users","scripts"],"metadata":{"cert_name":"scripts"},"lease_duration":3600,"renewable":true}}
* Connection #0 to host 10.16.19.21 left intact

When I tried to switch the audit backend to file I got an initial audit message (see below) but then the above curl command fails with the same panic:

{"type":"response","error":"","auth":{"display_name":"","policies":["root"],"metadata":{"username":"devprod"}},"request":{"operation":"write","path":"sys/audit/file","data":{"description":"sha1:da39a3ee5e6b4b0d3255bfef95601890afd80709","options":{"path":"sha1:5dc89e52044bb74bbacaddd008a47d214d0b5782"},"type":"sha1:971c419dd609331343dee105fffd0f4608dc0bf2"}},"response":{"auth":{"display_name":"","policies":null,"metadata":null},"secret":{"lease_id":""},"data":null,"redirect":""}}

**Comment by mitchellh** [comment]
@armon If you can get repro steps and Printf `%#v` the exact structure that is causing the panic, I can debug further, but I can't debug reflection without the exact structure causing it.
