### ISSUE TITLE
Standby nodes issue after restoring consul (HA backend) from backup.

### ISSUE THREAD

**Issue by jacob-koren** [hashicorp/vault#3226]
Cluster:
======
I have three vault nodes, one active, two standbys. Consul serves as HA backend.

Scenario:
=======
1. Consul KV store was restored from an old backup. 
2. /core/leader shows outdated information.
3. The standby nodes are now pointing to the old leader from /core/leader.
4. The active node still has the lock and is unaffected.

Current solution:
============
1. Delete the information in /core/leader and force the active node to step down.
2. A new active node will acquire the lock, and the /core/leader information will be renewed.

Problem:
=======
The solution involves downtime. And despite what the docs say, The downtime is not a few milliseconds but rather a whole minute or even more.

Question:
=======
Is there a way to force the active node to **re-write** it's IP back into /core/leader and avoid the new leader election?

**Comment by jacob-koren** [comment]
Downtime was minimized by invalidating the vault lock from consul.

**Comment by jefferai** [comment]
If you load a backup of the KV store you must delete `core/lock` -- not `core/leader` -- or no other Vault node will be able to acquire a lock. Please also note that loading a backup while Vault is running is unsupported.

I'm not sure what to make of the comment about this involving downtime -- this isn't any sort of normal HA operation.

Sounds like you have it sorted though, so closing.
