### ISSUE TITLE
Cubbyhole secret backend per user identity

### ISSUE THREAD

**Issue by brettcave** [hashicorp/vault#3229]
**Feature Request:**

The `cubbyhole` secret backend works great for storing secrets within the context of a token. However, in the case of using an authentication backend such as LDAP, an authentication token may expire and a user will re-authenticate receiving a new token. The new token does not have access to items under the old token's cubbyhole, even though the user identity that owns both tokens is the same. 

A secret backend isolated in context of a user identity, regardless of token, would be useful if this use-case is widely used.

**Steps to Reproduce:**

1. authenticate via ldap
2. store a value in cubbyhole (and validate it is there)
3. re-authenticate via ldap (new token issued)
4. old cubbyhole item is not accessible

```
$ vault auth -method=ldap username=brett
Password (will be hidden): 
Successfully authenticated! You are now logged in.
token: token-a-redacted-xxx
token_policies: [redacted]
$ vault write cubbyhole/mycubby secret=thisismysecret
Success! Data written to: cubbyhole/mycubby
$ vault read cubbyhole/mycubby 
Key     Value
---     -----
secret  thisismysecret

$ vault auth -method=ldap username=brett
Password (will be hidden): 
Successfully authenticated! You are now logged in.
token: token-b-redacted-yyy
token_policies: [redacted]
$ vault read cubbyhole/mycubby 
No value found at cubbyhole/mycubby
```

**Comment by jefferai** [comment]
I'm closing this simply because it's on our internal roadmap but is waiting on some things to happen first. It's going to come though!

**Comment by brettcave** [comment]
Great to hear @jefferai , looking forward to it.

**Comment by overmike** [comment]
I am looking forward to it, is there any target date? Early 2018?

**Comment by jefferai** [comment]
No target date currently.

**Comment by hgwood** [comment]
Hello, I've published an article on this feature [here](https://github.com/hgwood/blog/blob/master/personal-secrets-in-vault/personal-secrets-in-vault.md). I hope it makes sense and can help some of you.

**Comment by Radecxter** [comment]
Hi guys, 
Any update on this feature?

**Comment by jefferai** [comment]
See the previous two comments -- use Identity path templating with a normal KV mount.

**Comment by devhopsde** [comment]
is there any future functionality, in which it is not possible to access a users personalized credential with a root token? (just like it is in cubbyhole). For security reasons or audits, this is a huge issue.

**Comment by burkhat** [comment]
We've the same problem, we need a private secret store for LDAP User which aren't available through the root token and it should be permanent saved for the LDAP User. 
Are there any plans in the future or next version to implement this function?
At the moment we use KeePass for a private secret store but it would be nice if could do this also in Vault so we need only one tool.

**Comment by ncabatoff** [comment]
I think there may be some confusion here.  It's true that you can't access cubbyholes using a root token.  However, in any Vault system I've seen, the only people with access to a root token also have access to the unseal keys and the ability to modify Vault's configuration.  If you can modify Vault's config, you can enable sys/raw, and then all bets are off - you can read anything, including cubbyholes.

I don't see any practical way for Vault to prevent admins from reading data stored in Vault, which is I think what people are really asking for here.

**Comment by jboero** [comment]
This actually seems like a simple fork of ./vault/logical_cubbyhole.go
@jefferai, @ncabatoff, we're looking at a user with 500,000+ entity aliases so each can have their own KV.  This is a much simpler option.  Worth a revisit?  I was looking at a `vault-plugin-secret-my` but this actually seems even easier.
```
index 4f869747c4..6fb9925093 100644
--- a/vault/logical_cubbyhole.go
+++ b/vault/logical_cubbyhole.go
@@ -118,7 +118,7 @@ func (b *CubbyholeBackend) handleRead(ctx context.Context, req *logical.Request,
        }
 
        // Read the path
-       out, err := req.Storage.Get(ctx, req.ClientToken+"/"+path)
+       out, err := req.Storage.Get(ctx, req.ClientID+"/"+path)
        if err != nil {
                return nil, fmt.Errorf("read failed: %w", err)
```

**Comment by jefferai** [comment]
@jboero Why not use a KV mount with path templating?

**Comment by jboero** [comment]
This is kind of simple and elegant with no need for any policy, no need to have a unique path per user, and no way to access other identity's secrets.  I'll see if I can code this up properly as a plugin when I can find some time.

**Comment by jdsatava127** [comment]
We would also benefit from this feature. We are looking for a personal secrets engine that is autogenerate and tied to LDAP logins instead of tokens. We would want this to be a permanent engine as opposed to one that expires with the token like cubbyhole.

**Comment by jboero** [comment]
Sadly I implemented this but it was never merged.
https://github.com/jboero/vault/pull/1

**Comment by jboero** [comment]
@solvingj yes that is exactly the feature I coded and it was never merged. Maybe OpenBao would like to merge it and skip HashiCorp altogether.

**Comment by jboero** [comment]
Update on this. OpenBao is planning to merge this in a future release.

**Comment by solvingj** [comment]
That's nice. I work in enterprise which uses vault so have to wait for it here.
