### ISSUE TITLE
Feature Request: use GCP "Application Default Credentials" for authenticating to GCS storage backend

### ISSUE THREAD

**Issue by stephansnyt** [hashicorp/vault#3242]
**Feature Request:**
When using the GCS storage backend within GCP, in some cases it should be possible to use "application default credentials...to get authorization credentials for use in calling Google APIs." This means that a `credentials_file` does not actually need to be required in all cases.

This feature request is to support using "application default credentials" (henceforth called ADC) when Vault is running on a google cloud compute instance.

I propose to make `credentials_file` parameter not required, and refactor [`NewGCSBackend`](https://github.com/hashicorp/vault/blob/master/physical/gcs/gcs.go#L35) so that if they are not provided, Vault will attempt to get ADC before returning error

`env var GOOGLE_APPLICATION_CREDENTIALS or configuration parameter 'credentials_file' not set and failed to get application default credentials`.

The meaning of the error message might not be very obvious, so it could be enhanced, or an alternative implementation would be to add a new parameter `use_gcp_application_default_credentials` (bool: false). If true, Vault would try to fetch the ADC and error if failed. If false, it would basically run the current version of `NewGCSBackend`.

**References:** 
- https://developers.google.com/identity/protocols/application-default-credentials#callinggo
- https://github.com/GoogleCloudPlatform/google-cloud-go#authorization

**Comment by stephansnyt** [comment]
I implemented a version using the new parameter `use_gcp_application_default_credentials` here

https://github.com/stephansnyt/vault/pull/2

It doesn't have tests or docs yet

**Comment by jefferai** [comment]
Hi there,

Issues and requests with this plugin should go to https://github.com/hashicorp/vault-plugin-auth-gcp

Thanks!

**Comment by stephansnyt** [comment]
This is for the GCS physical storage backend not the GCP auth backend.

**Comment by stephansnyt** [comment]
Also I've basically implemented the feature already (it's pretty trivial), but I'm not quite sure what the etiquette is for contribution, so this issue would be a place to track everything needed for me to open a good PR. The contribution doc in the repo is kind of light when it comes to style guide, code quality requirements, etc. I also thought that maybe the requirements for style and quality might be different considering this is a "community supported" storage backend, e.g. you would have more stringent requirements contributing to vault core or "hashicorp supported" backends.

**Comment by jefferai** [comment]
Just open a PR when you're ready for an initial look!
