### ISSUE TITLE
add environment file format to read.

### ISSUE THREAD

**Issue by james-lawrence** [hashicorp/vault#3243]
**Feature Request:**
given a secret path with multiple key=value pairs, it'd be nice to be able to export it as an environment file.

currently using envconsul but it shouldn't be necessary.

example:
`vault read -format=env secret/example`
```
HELLO=WORLD
```

**Comment by james-lawrence** [comment]
now that i've used vault a little bit more I'm going to close this issue and open a new one with the feature request slgihtly adjusted.

**Comment by jefferai** [comment]
We do not currently have plans to implement this.
