### ISSUE TITLE
Large token accessor lookup fails due to syslog write

### ISSUE THREAD

**Issue by sgmiller** [hashicorp/vault#3246]
* Vault Version: 0.8.0
* Operating System/Architecture: Linux AMD64

**Expected Behavior:**
Even with large numbers of tokens issued, vault list auth/token/accessors should return.  

**Actual Behavior:**
When the request should complete, it returns 500 due to not being able to write the audit line to syslog.  Disabling that audit backend was the only way to get results:

Aug 28 16:59:00 production-vault-i-0107cbdca81fc9e3e vault[30401]: 2017/08/28 16:59:00.595534 [ERROR] audit: back
end failed to log response: backend=syslog/ error=write unixgram @->/run/systemd/journal/dev-log: write: message 
too long
Aug 28 16:59:00 production-vault-i-0107cbdca81fc9e3e vault[30401]: 2017/08/28 16:59:00.595580 [ERROR] core: faile
d to audit response: request_path=auth/token/accessors/ error=1 error occurred:
Aug 28 16:59:00 production-vault-i-0107cbdca81fc9e3e vault[30401]: * no audit backend succeeded in logging the re
sponse

**Steps to Reproduce:**
Enable the syslog audit backend.
Get very many Vault tokens issued (300k in our case due to a bug).
vault list auth/token/accessors 
Observe HTTP 500 response and corresponding logs.

**Comment by jefferai** [comment]
We don't have any control over the maximum size that can be written to syslog, so it's unclear what Vault can do here. You may want to look at increasing that in systemd. Your other option would be to mount an additional audit backend that will allow this (e.g. file) and merge logs from the two. We don't currently have any plans to support pagination.
