### ISSUE TITLE
Error reading secret/password: Get http://consul_ip:8200/v1/secret/password: dial tcp consul_ip:8200: getsockopt: connection refused

### ISSUE THREAD

**Issue by santosh373** [hashicorp/vault#3249]
**Environment:**

* Vault Version:
* Operating System/Architecture:

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

**Actual Behavior:**

**Steps to Reproduce:**

**Important Factoids:**

**References:**

**Comment by santosh373** [comment]
when I run read or write command of vault it shows me an error

**Comment by jefferai** [comment]
Please fill out the requested information
