### ISSUE TITLE
Deep copying in audit backends?

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#325]
In the backend API is the following:
```go
type Backend interface {
    // LogRequest is used to syncronously log a request. This is done after the
    // request is authorized but before the request is executed. The arguments
    // MUST not be modified in anyway. They should be deep copied if this is
    // a possibility.
    LogRequest(*logical.Auth, *logical.Request) error

    // LogResponse is used to syncronously log a response. This is done after
    // the request is processed but before the response is sent. The arguments
    // MUST not be modified in anyway. They should be deep copied if this is
    // a possibility.
    LogResponse(*logical.Auth, *logical.Request, *logical.Response, error) error
}
```
In the `file` and `syslog` backends, the values are deep copied. However, I don't understand the reasoning behind this: after the values are deep copied they are simply used to marshal into JSON. It seems unnecessary and wasteful, as the JSON marshalling operation does not modify the values.

Is this an overabundance of caution, or can the JSON marshalling process modify the original structs and I'm simply unaware of this?

**Comment by mitchellh** [comment]
The hashing modifies the values in-place, so we have to deep copy.

**Comment by jefferai** [comment]
Ah! Fun how when someone points out what's right in front of your face it becomes clear. I'm so used to hashing functions returning the value that I didn't notice that only an error was being returned.

Thanks!
