### ISSUE TITLE
Support remote Syslog for audit log

### ISSUE THREAD

**Issue by jhmartin** [hashicorp/vault#3250]
The Vault syslog audit log is only able to log locally to a unix socket (such as /dev/log).  This is inconvenient when running Vault in a container as it requires running multiple processes per container and a supervisor to keep them properly running.

Please consider adding remote syslog support via a remote configurable UDP socket. This allows for consuming the logs via a remote logstash or syslog daemon that can be run as a machine service or in a linked container.

**Comment by jefferai** [comment]
Does the socket backend not address this use case?

**Comment by santosh373** [comment]
Hi Jeff,

Thanks for your reply, I am not running vault as a container, I do have 3
servers for vault in backend connected to consul, 2 of them have the same
issue and one is running good,

here is my configuration


disable_mlock = false
default_lease_ttl = "720h"
max_lease_ttl = "720h"

listener "tcp" {
  address = "10.243.3.161:8200"
  tls_disable = 1
}

backend "consul" {
  path = "vault/"
  address="10.243.3.141:8500"

  tls_skip_verify = 0
}

Thank you,
Santosh

**Comment by Constantin07** [comment]
+1

**Comment by rpsiv** [comment]
FYI The socket backend logs to syslog just fine.  I chose to use TCP over UDP since we likely do not want lost packets.

Update your rsyslog config
```
<..>
# Provides TCP syslog reception
$ModLoad imtcp
$InputTCPServerRun 514
<..>
```

By default syslog is on port 514

Enable your Vault socket Auth backend.  The IP should be that of your remote rsyslog server
`# vault audit-enable socket address="1.2.3.4:514" socket_type="tcp"`

```

**Comment by jefferai** [comment]
@rpsiv Thanks for the comment! I'm actually going to close this since as far as I can tell with the socket backend being merged a long while back this is supported (and your own experience bears this out).
