### ISSUE TITLE
core: seal configuration missing, not initialized

### ISSUE THREAD

**Issue by alfer71** [hashicorp/vault#3252]
Hi,
Can you please help I have the issue with Vault in **Linux** the command that I performed are locally, so when I try to connect to check the status of the vault server **`vault status`** 

it display: 
```
Code: 400. Errors:

* server is not yet initialized
```

**Environment:**

* Vault Version:  **Vault v0.8.1**
* Operating System/Architecture:  **Ubuntu 16.04.3 LTS**     `x86_64`

**Vault Config File:**
```
$ cat vault.hcl
storage "file" {
  path = "/home/vault/data"
}

listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
```

**Startup Log Output:**
```
==> Vault server configuration:

                     Cgo: disabled
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
                 Storage: file
                 Version: Vault v0.8.1
             Version Sha: 8d76a41854608c547a233f2e6292ae5355154695

==> Vault server started! Log data will stream in below:
```

**Expected Behavior:**

**Actual Behavior:**

**Steps to Reproduce:**

**Important Factoids:**

**References:**

**_That I am missing something?_**
Regards.

**Comment by gobins** [comment]
@alfer71 Looks like you are working on empty data. If this is the first time you are starting the server, you will have to initialize it.
https://www.vaultproject.io/intro/getting-started/deploy.html#initializing-the-vault

**Comment by alfer71** [comment]
Hi @gobins 
is not the first time, but I tried to initialize and display the following:
```
$ ./vault init
Error initializing Vault: Put https://127.0.0.1:8200/v1/sys/init: dial tcp 127.0.0.1:8200: getsockopt: connection refused
```
Any other advice that I can perform?
Thanks for your reply

**Comment by calvn** [comment]
You have vault set up to listen on HTTP (`tls_disable = 1`) but you are hitting an HTTPS endpoint. Try `export VAULT_ADDR=http://127.0.0.1:8200` followed by `vault init`.

**Comment by alfer71** [comment]
Great!!!! Awesome!!!
Thanks for your advice @calvn , now my vault is working.
Also thanks for you post @gobins.
Have a nice day!
Regards.

**Comment by sure17490** [comment]
Error initializing Vault: Put http://127.0.0.1:8200/v1/sys/init: dial tcp 127.0.0.1:8200: getsockopt: connection refused

**Comment by satheeshCharles** [comment]
@sure17490 how you solved this problem ? I'm getting the same error

**Comment by asyd** [comment]
Same issue when I try to run vault using file storage with data coming from a previous instance using s3

**Comment by satheeshCharles** [comment]
Share your config file.

**Comment by satheeshCharles** [comment]
@chrishoffman never mind. I have fixed my problem, long back. I was trying to help @asyd .
