### ISSUE TITLE
invalid key: invalid format

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/vault#3259]
**Environment:**
ubuntu 17 
One is the ssh server and the other is ssh client
macbook pro macos 10.12.6 running vault server

* Vault Version:
Vault v0.8.1 ('8d76a41854608c547a233f2e6292ae5355154695')

**Vault Config File:**
storage "file" {
  path = "/Users/fernando/vault/data"
}

listener "tcp" {
 address = "0.0.0.0:8200"
 tls_disable = 1
}

**Startup Log Output:**
2017/08/30 17:55:31.956709 [INFO ] core: vault is unsealed
2017/08/30 17:55:31.956798 [INFO ] core: post-unseal setup starting
2017/08/30 17:55:31.956940 [INFO ] core: loaded wrapping token key
2017/08/30 17:55:31.957272 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/08/30 17:55:31.957456 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/08/30 17:55:31.957477 [INFO ] core: successfully mounted backend: type=generic path=generic/
2017/08/30 17:55:31.957510 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/08/30 17:55:31.957570 [INFO ] rollback: starting rollback manager
2017/08/30 17:55:31.958411 [INFO ] expiration: restoring leases
2017/08/30 17:55:31.958998 [INFO ] core: post-unseal setup complete
2017/08/30 18:05:42.964181 [INFO ] core: successful mount: path=ssh-client-signer/ type=ssh

**Expected Behavior:**
to received a valid signed key

**Actual Behavior:**
key is invalid and when trying to ssh it fails

**Steps to Reproduce:**
$./vault write ssh-client-signer/sign/my-role public_key=@/home/ubuntu/.ssh/id_rsa.pub  > /home/ubuntu/.ssh/id_rsa.vault.pub

$ ssh-keygen -Lf id_rsa.vault.pub
id_rsa.vault.pub:1: invalid key: invalid format
id_rsa.vault.pub:2: invalid key: invalid format
id_rsa.vault.pub:3: invalid key: invalid format
id_rsa.vault.pub:4: invalid key: invalid format
id_rsa.vault.pub:5: invalid key: invalid format

$ ssh 192.168.68.103 -i id_rsa.vault.pub -i id_rsa
Load key "id_rsa.vault.pub": invalid format
ubuntu@192.168.68.103's password:

**Comment by jefferai** [comment]
The key is returned in a Vault response structure. You can use the `-field` flag to `vault write` to have just the key be output, or use something like `jq` with `-format=json` to do the slicing and dicing externally.

**Comment by FernandoMiguel** [comment]
@jefferai 
can the docs be updated to mention that
https://www.vaultproject.io/docs/secrets/ssh/signed-ssh-certificates.html

and use something like
`vault write -field=signed_key ssh-client-signer/sign/my-role public_key=@$HOME/.ssh/id_rsa.pub > $HOME/.ssh/id_rsa.vault.pub`

thanks
