### ISSUE TITLE
PostgreSQL secret backend generating usernames that exceed postgresql length limits

### ISSUE THREAD

**Issue by nevir** [hashicorp/vault#326]
It's generating a username like `vault-token-10-10-37-59--myservice-api-production-1433870093-6159`, which PostgreSQL internally truncates to 63 characters. Most clients don't seem to handle truncating this, so it tends to result in connection errors

Also, because the unique bits are on the end, truncation might lead to conflicting PostgreSQL roles.

**Comment by nevir** [comment]
(I can work around it for now by making a shorter display name for my policies)

**Comment by armon** [comment]
@nevir Thanks for reporting! Should be an easy enough fix!

**Comment by armon** [comment]
Fixed in https://github.com/hashicorp/vault/commit/05fa4a4a48362f815060d442596e2d5bbe0f4769
