### ISSUE TITLE
Wildcard Support in Vault Policy Path

### ISSUE THREAD

**Issue by Mohd-gslab** [hashicorp/vault#3264]
As per Vault Documentation 
(https://www.vaultproject.io/docs/concepts/policies.html)
"
The glob character is only supported as the last character of the path, and is not a regular expression!
"
<B> Do we have plan to support glob character between the path ? </B> 
For Example:
path secret/*/*/foo {
 capabilities = ["read"]  
}
Now as per policy user would have read permission on foo , 
He can read 
secret/test1/t1/foo
secret/test1/t2/foo
secret/test1/t3/foo

**Comment by Mohd-gslab** [comment]
The corrected path is 
<b> secret/\*/\*/foo </b>

**Comment by jefferai** [comment]
There are currently no plans to support this.
