### ISSUE TITLE
Feature Request: vault read -data-only option.

### ISSUE THREAD

**Issue by james-lawrence** [hashicorp/vault#3273]
**Feature Request:**
currently vault read outputs all the KV pairs plus additional information, often I don't care about the additional information and am only interested in the actual KV pairs. having a data only option would make this use case easier.

example table output)
`vault read -format=table secret/example`
```
Key                        Value
---                          ---
refresh_interval     8h 
HELLO                  WORLD
```
`vault read -format=table -data-only secret/example`
```
HELLO                  WORLD
```

example yaml output)
`vault read -format=yaml secret/example`
```
data:
  HELLO: WORLD
lease_duration: 2764800
lease_id: ""
renewable: false
request_id: be418c8c-8bb4-9d0d-0c03-eedce5a76e45
warnings: null
```
`vault read -format=yaml -data-only secret/example`
```
HELLO: WORLD
```

example json output)
`vault read -format=json secret/example`
```
{
	"request_id": "0e6b5971-609a-e553-5420-91dfd568e5fe",
	"lease_id": "",
	"lease_duration": 2764800,
	"renewable": false,
	"data": {
		"HELLO": "WORLD"
	},
	"warnings": null
}

```
`vault read -format=json -data-only secret/example`
```
"HELLO": "WORLD"
```

**Comment by jefferai** [comment]
Any reason to not just use `jq` or so?

**Comment by james-lawrence** [comment]
beyond requiring another tool for a basic usecase? no.

**Comment by james-lawrence** [comment]
TBH when first using vault I surprised to see the additional fields that had nothing to do with the values actually inserted in the output.

CLI is for human consumption and scripting adding additional steps because the tool does the unexpected is kind of annoying.

**Comment by jefferai** [comment]
As you said, the CLI is for human consumption. It's easily scripted (the number of lines to remove up top is constant), and the JSON/YAML outputs are easily scripted as well.

**Comment by jefferai** [comment]
BTW, if you want to implement a format=env in a PR we're happy to take a look. There is simply no interest/time within the Vault team to work on this.

**Comment by james-lawrence** [comment]
I don't disagree with any of your points, most of the issues I've filed are just general issues I've run into trying to actually use vault and the annoyances I've run into. These issues are about improving the user experience.

And I'd be happy to implement the features I'm requesting at somepoint if thats an available path.

By closing the issues you're basically implying that vault won't have these features ever.

**Comment by jefferai** [comment]
A PR is a separate ticket; this is filed as a feature request. Since we won't be implementing this feature request I closed it, but as I said, feel free to send a PR.
