### ISSUE TITLE
Could not build vault with golang 1.8.3

### ISSUE THREAD

**Issue by tatsuhiro-t** [hashicorp/vault#3277]
**Environment:**

* Vault Version:
* Operating System/Architecture:

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

go get -u github.com/hashicorp/vault should work without error.

**Actual Behavior:**

```
# go get -u -t github.com/hashicorp/vault
# github.com/hashicorp/vault/vault
src/github.com/hashicorp/vault/vault/testing.go:594: t.Helper undefined (type "github.com/hashicorp/vault/vendor/github.com/mitchellh/go-testing-interface".T has no field or method Helper)
src/github.com/hashicorp/vault/vault/testing.go:638: t.Helper undefined (type "github.com/hashicorp/vault/vendor/github.com/mitchellh/go-testing-interface".T has no field or method Helper)
```

It looks like #3255 causes this.

**Steps to Reproduce:**

**Important Factoids:**

**References:**

**Comment by jefferai** [comment]
Vault master (and upcoming releases) require Go 1.9.
