### ISSUE TITLE
Allow for consul service registration without having to use Consul as storage backend

### ISSUE THREAD

**Issue by Gufran** [hashicorp/vault#3279]
**Feature Request:**
At the moment service discovery feature is only available if vault is configured to use Consul KV as storage backend. When using other storage backends such as DynamoDB one has to go out of their way to ensure that vault service is correctly reflected in catalog. There is no simple configuration.

For an example lets say I wish to use DynamoDB storage and also register `active.vault.service.consul` and `standby.vault.service.consul`, I'll need to add two service definitions in local consul agent with same name and different tag. At any given point in time only one of those two services is bound to be healthy depending on the status of Vault agent.
Furthermore, the catalog will wrongly report half of the vault services as unhealthy and that sets off all kind of godforsaken alerts.

Other option is to write some sort of script which would register and deregister vault service in catalog with appropriate tags, but reliability is a big concern.

**Comment by mjarmy** [comment]
The associated PR for this issue, #7887, has been merged, and will be present in the 1.4 release of Vault.

**Comment by Skaronator** [comment]
Looks like Christmas came early, thanks!

**Comment by briankassouf** [comment]
Closing since #7887 is merged
