### ISSUE TITLE
Does not compile on OSX (go-testing-interface issue)

### ISSUE THREAD

**Issue by asaf** [hashicorp/vault#3282]
Hey,

Code does not compile on OSX and fails with:

```bash
==> Removing old directory...
==> Building...
Number of parallel builds: 7

-->    darwin/amd64: github.com/hashicorp/vault

1 errors occurred:
--> darwin/amd64 error: exit status 2
Stderr: # github.com/hashicorp/vault/vault
vault/testing.go:594: t.Helper undefined (type "github.com/hashicorp/vault/vendor/github.com/mitchellh/go-testing-interface".T has no field or method Helper)
vault/testing.go:638: t.Helper undefined (type "github.com/hashicorp/vault/vendor/github.com/mitchellh/go-testing-interface".T has no field or method Helper)
```

Thanks.

**Comment by joelthompson** [comment]
Hi @asaf -- you need to use Go 1.9 to build Vault. That error occurs when you're using Go 1.8.

**Comment by jefferai** [comment]
Joel s correct, closing.

**Comment by asaf** [comment]
wow, this project moves fast, it was out few days ago :)
thanks folks.

**Comment by jefferai** [comment]
It's true, but we've been waiting on sync.Map for a while :-)

**Comment by asaf** [comment]
@jefferai heh yea, it's called ConcurrentHashMap and it's there since 2004 :P (I love Golang though)

Thanks for answering folks!

**Comment by jefferai** [comment]
@asaf Just removes a bunch of boilerplate structs for locking and unlocking a map. :-)
