### ISSUE TITLE
Allow policies to restrict which keys can be accessed when reading

### ISSUE THREAD

**Issue by F21** [hashicorp/vault#3286]
**Feature Request:**
There is the `allowed_parameters` policy option to restrict the allowed keys when creating a secret using the secret backend. It would be nice if something similar is available to restrict which keys can be read using the secret backend depending on the policy available to the token.

**Environment:**
* Vault Version: Vault v0.8.1 ('8d76a41854608c547a233f2e6292ae5355154695')
* Operating System/Architecture: Windows 10 64-bit

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**
Reading a secret from the generic backend should restrict the returned keys to the ones defined in the policy for the token.

**Actual Behavior:**
Reading from the generic backend currently ignores the `allowed_parameters` option defined in the token's policy and returns all keys.

**Steps to Reproduce:**

**Important Factoids:**

**References:**

**Comment by jefferai** [comment]
There are no plans to implement this. As a workaround, I suggest writing different combinations of keys targeted to different users at different paths, or, split the keys into separate paths and combine access using path policy statements.

**Comment by ReeceBlack123** [comment]
@jefferai do you know if there are any plans in doing this?
