### ISSUE TITLE
Failed to check for initialization

### ISSUE THREAD

**Issue by boncheff** [hashicorp/vault#329]
I am running Vault and Consul in two separate docker containers:
https://registry.hub.docker.com/u/progrium/consul/ and
https://registry.hub.docker.com/u/sjourdan/vault/

I am running consul container with the following command:
`docker run -p 8400:8400 -p 8500:8500 -p 8600:53/udp --hostname consul --name consul progrium/consul -server -bootstrap -ui-dir /ui`

and vault container with the following command:
`docker run -t -i --cap-add IPC_LOCK -p 8300:8300 --hostname vault --name vault --link consul:consul --volume $PWD/consul:/consul sjourdan/vault -config=/consul/config.hcl`

with the following config:

```
backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
  advertise_addr = "http://127.0.0.1"
}

listener "tcp" {
 address = "0.0.0.0:8200"
 tls_disable = 1
}
```
and `export VAULT_ADDR='http://172.x.x.x:8200'` (which is the vault container's IP)

however when I run vault status (or any vault command) i get this:

```
vault status
Error checking seal status: Error making API request.

URL: GET http://172.x.x.x:8200/v1/sys/seal-status
Code: 500. Errors:

* failed to check seal configuration: Get http://127.0.0.1:8500/v1/kv/vault/core/seal-config: dial tcp 127.0.0.1:8500: connection refused
```

and the error from Vault log is:
`2015/06/10 11:16:04 [ERR] core: failed to read seal configuration: Get http://127.0.0.1:8500/v1/kv/vault/core/seal-config: dial tcp 127.0.0.1:8500: connection refused`

Is this due to a Vault error or have I messed up the configuration?

**Comment by sherzberg** [comment]
@boncheff should 
```
backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
  advertise_addr = "http://127.0.0.1"
}
```
be
```
backend "consul" {
  address = "consul:8500"
  path = "vault"
  advertise_addr = "http://127.0.0.1"
}
```

based on your docker links?

**Comment by boncheff** [comment]
@sherzberg I shall try it now and see if it works - thank you for your reply

**Comment by boncheff** [comment]
@sherzberg it seems to be behaving! thanks a lot one more time

**Comment by gvenka008c** [comment]
@sherzberg Sorry for writing in the closed thread. I am seeing the error as below

```
# vault status
Error checking seal status: Error making API request.

URL: GET http://xx.xxx.xxx.xxx:8200/v1/sys/seal-status
Code: 500. Errors:

* failed to decode seal configuration: invalid character 'e' looking for beginning of value
```
Thoughts?

**Comment by sherzberg** [comment]
@gvenka008c I'm not sure if your error is related to this issue, but can you post your vault configs?

**Comment by jefferai** [comment]
The error is definitely not related.
