### ISSUE TITLE
Does Vault support Mongodb as a storage backend ?? 

### ISSUE THREAD

**Issue by saivamsi75** [hashicorp/vault#3298]
**Environment:**

* Vault Version:Vault v0.8.1 ('2e39d2b2d43d65bfb1e54ffc8996c2ca0f82a367')
* Operating System/Architecture: CentOS 7

**Vault Config File:**

<<<example.hcl>>>
storage "mongodb" {
  address = "127.0.0.1:27017"
  path = "vault"
}

listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
}

**Startup Log Output:**

Unknown storage type mongodb

**Expected Behavior:**

Running Vault and Mongodb on the same host and verified that Mongodb is listening on all interfaces.
ss -l | grep tcp
tcp    LISTEN     0      128     *:**27017**                 *:*  **Actual Behavior:**

Vault complained that it couldn't find the Mongodb as backend storage.

**Steps to Reproduce:**

vault server -config=example.hcl
Contents at 'Vault Config File' are  in 'example.hcl'

**Important Factoids:**

I am evaluating Vault whether mongodb can be used  as a storage to store the certificates and tokens issued by vault.
In[ commands.go](https://github.com/hashicorp/vault/blob/27c2386f4a33709c08e37fbb13ce21856a9b3997/cli/commands.go) file , I didn't see the mongodb related code snippets, so I am not sure whether Vault supports mongodb as a storage backend.

**References:**

https://www.vaultproject.io/intro/getting-started/deploy.html
https://www.vaultproject.io/docs/secrets/databases/mongodb.html

**Comment by jefferai** [comment]
MongoDB is not supported.

See https://www.vaultproject.io/docs/configuration/storage/index.html for available storage backends.

The mongodb docs you linked to are for a secret backend that generates MongoDB credentials, not for storage.

**Comment by saivamsi75** [comment]
Thanks for the response.
Few more queries from my side,

A) I am trying to validate my understanding with your statement, 'Vault don't support Mongodb as a storage., my applications running in the cloud are using Mongodb for their storage, and if I want to use Vault as Internal Certificate authority then  should I have to deal with one more database ??

B)Any particular reason, why Vault don't support Mongodb db as a storage ? Does Mongodb has some limitations  or due to licensing reasons ? Do paid versions like Enterprise or Premium support  Mongodb as a storage ?

C)My requirements are simple 
  

1. Need to create separate root certificate for each Enterprise customer and issue SSL certificates using that root certificate.  
2. Need tokens to authenticate .
3. I don't want to create a separate Vault instance for each enterprise customer, I will be  replicating the Vault instance based on the load,  i.e. two customers seeking for certificates may land on the same Vault instance or subsequent requests from the same customers  may land on a different Vault instance.

   Is Vault a right choice  to satisfy my requirements ? Any recommendations on the DB storage for the Vault that scale like Mongodb ?  

D) Vault  
    
1. is stateless  (if  any state information  needed  across the restarts then it is persisted in the DB) 
2.  can scale horizontally 
3.  restart is  seamless .

  
  Is my understanding correct about Vault ?

**Comment by jefferai** [comment]
Responses:

A/B) Many people in your situation choose to write and submit their own storage backend. Mongo could be supported, but nobody has performed that work yet. We only officially support inmem/file/consul, all of the other storage backends have been written by community members.

C) This is all possible, you can simple mount a different PKI backend for each customer.

D) Stateless is not usually defined as you have defined it here. Stateless usually means that the server does not store any information or state outside of the context of each client request. In Vault's case, it is not stateless. However, all information Vault needs is indeed persisted to its storage. Vault can scale horizontally with Enterprise Premium functionality.

**Comment by MazokuMaxy** [comment]
> Mongo could be supported, but nobody has performed that work yet. 
What about [#1847](https://github.com/hashicorp/vault/pull/1847)?
