### ISSUE TITLE
Vault Compile Failure from fresh Git Clone (Latest - 0.8.2)

### ISSUE THREAD

**Issue by samc-6ft** [hashicorp/vault#3307]
**Environment:**

* Vault Version: 0.8.2
* Operating System/Architecture: Ubuntu 16.04

**Vault Config File:**

N/A

**Startup Log Output:**

N/A

**Expected Behavior:**

The vault source code should compile when readme instructions are followed.

**Actual Behavior:**

                  1 errors occurred:
                  --> linux/amd64 error: exit status 2
                  Stderr: # github.com/hashicorp/vault/vault
                  vault/expiration.go:70: undefined: sync.Map
                  
                  make: *** [dev] Error 1
              stdout:
                  ==> Checking that code complies with gofmt requirements...
                  go generate 
                  cp .hooks/* .git/hooks/
                  ==> Removing old directory...
                  ==> Building...
                  Number of parallel builds: 1
                  
                  -->     linux/amd64: github.com/hashicorp/vault
                  Makefile:21: recipe for target 'dev' failed

**Steps to Reproduce:**

Create fresh Ubuntu 16.04 VM
Running as root (for simplicity)
$ apt-get install Go 1.8.3 linux/amd64
$ apt-get install git
$ export GOPATH=/etc/vault/go_code
$ mkdir -p $GOPATH/src/github.com/hashicorp
$ cd $GOPATH/src/github.com/hashicorp
$ git clone https://github.com/hashicorp/vault.git
$ cd vault
$ make bootstrap
$ make dev

Results in Error Output seen above.  

If I check out revision 7c6e18d (Vault 0.8.1) the compile finishes cleanly and everything works as expected.  The referenced error points to a change from 3 days ago.  Since 0.8.1 works and 0.8.2 does not I believe the error is in fact in expiration.go

**Important Factoids:**

**References:**

https://github.com/hashicorp/vault/pull/3260  <- I think this is the source of the problem

**Comment by chrishoffman** [comment]
Go 1.9 is required to build vault.  We started to use some new language features in the latest release.

**Comment by samc-6ft** [comment]
Thanks! I'll give it a shot.  However, the documentation should be updated to indicate the required version of Go.  The current documentation does not have any reference to a minimum version.

**Comment by chrishoffman** [comment]
It does mention it in the "Developing Vault" section in the README (https://github.com/hashicorp/vault#developing-vault).  I'm not sure if there is a better place to put it but am open to suggestions.  Thanks!

**Comment by joelthompson** [comment]
It might be useful to check the version of go in the Makefile and complain loudly (and explicitly) if it's using an unsupported version of go; it'd probably head off these issues.

**Comment by samc-6ft** [comment]
Confirmed to work with Go 1.9.
https://www.vaultproject.io/docs/install/index.html is the quick start doc for building from source.  This is what I was following.  I think @joelthompson suggestion is spot on.

**Comment by joelthompson** [comment]
I opened #3309 to add that explicit check.
