### ISSUE TITLE
Security issue - ACL policy path matching is greedy

### ISSUE THREAD

**Issue by roycrowder** [hashicorp/vault#331]
```javascript
path "sys" {
  policy = "deny"
}

path "secret" {
  policy = "deny"
}

path "secret/foo" {
  policy = "write"
}
```

```text
[root@vault-001 ~]# vault policy-write test test.hcl
Policy 'test' written.
```

```text
[root@vault-001 ~]# vault token-create -policy=test
<redacted>
```

```text
[root@vault-001 ~]# vault auth <redacted>
Successfully authenticated! The policies that are associated
with this token are listed below:

test
```

```text
[root@vault-001 ~]# vault write secret/foo000/weird test=test
Success! Data written to: secret/foo000/weird
```

```text
[root@vault-001 ~]# vault read secret/foo000/weird
Key            	Value
lease_id       	secret/foo000/weird/7b3684de-9359-76e4-eead-15dc02b1364a
lease_duration 	2592000
lease_renewable	false
test           	test
```

**Comment by roycrowder** [comment]
I see how this could be intentional as well.

path "secret/foo/" {}  will limit the greediness of the match.

If this was intentional, you may want to update the documentation to describe the matching in detail so that operators don't unintentionally open up a policy to greedy matching.

**Comment by roycrowder** [comment]
Could I get some Hashicorp comment on this as to whether it's actually a vulnerability or not?

Thanks!

**Comment by armon** [comment]
@roycrowder The policy language uses a longest prefix match, so the behavior is expected. Because everything is default deny, you use paths to allow access to given sub-trees.

**Comment by roycrowder** [comment]
Thanks guys! Really appreciate it!
