### ISSUE TITLE
Raspberry Pi: Segmentation fault when running server

### ISSUE THREAD

**Issue by phlipse** [hashicorp/vault#3310]
**Environment:**

* Vault Version: Vault v0.8.2 ('9afe7330e06e486ee326621624f2077d88bc9511')
* Operating System/Architecture: Raspberry Pi 2 and 3 with Raspbian Stretch, Linux 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux

**Vault Config File:**
none, ./vault server -dev

**Startup Log Output:**
./vault server -dev
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
        Redirect Address: http://127.0.0.1:8200
                 Storage: inmem
                 Version: Vault v0.8.2
             Version Sha: 9afe7330e06e486ee326621624f2077d88bc9511

panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x11540]

goroutine 37 [running]:
sync/atomic.storeUint64(0x1238017c, 0x0, 0x0)
	/goroot/src/sync/atomic/64bit_arm.go:20 +0x3c
github.com/hashicorp/vault/vault.(*ExpirationManager).Restore.func1(0x12380140, 0x12872fe8, 0x125c1500)
	/gopath/src/github.com/hashicorp/vault/vault/expiration.go:279 +0x34
panic(0x10b8978, 0x1e0bee8)
	/goroot/src/runtime/panic.go:491 +0x204
sync/atomic.storeUint64(0x1238017c, 0x0, 0x0)
	/goroot/src/sync/atomic/64bit_arm.go:20 +0x3c
github.com/hashicorp/vault/vault.(*ExpirationManager).Restore(0x12380140, 0x125c1500, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/vault/expiration.go:394 +0x4f0
created by github.com/hashicorp/vault/vault.(*Core).setupExpiration
	/gopath/src/github.com/hashicorp/vault/vault/expiration.go:122 +0x214

**Expected Behavior:**
running dev server

**Actual Behavior:**
segmentation fault

**Steps to Reproduce:**
download latest arm binary and start dev server: ./vault server -dev

**Important Factoids:**

**References:**

**Comment by jefferai** [comment]
That appears to either be a bug in Go or something not implemented for your platform in Go. We're passing a stack-allocated integer into the function, so there's no chance of a nil pointer dereference coming from our code. Any chance the 32-bit binary works right?

I don't have a 64-bit arm box available to me (much less the chipset specifically in the raspberry pi), but if you could run the Go test suite natively on the Pi it'd be instructive.

**Comment by phlipse** [comment]
This was the 32-bit binary. The 64-bit binary doesn't work on Pi 3 (64-bit hardware) as well.
I will run the test suite tomorrow and update this comment.

**Comment by jefferai** [comment]
Note that this will likely be in 0.8.4 next week, not 0.8.3 this week.
