### ISSUE TITLE
Extend HSM integration to support key generation for use cases other than master key

### ISSUE THREAD

**Issue by yohanliyanage** [hashicorp/vault#3312]
**Feature Request:**
Current HSM support in Vault is strictly for transiting the master key in the HSM and enabling automatic unsealing. However, when a HSM is present, it would be useful if Vault can use the HSM for other key generation activities as well. 

For example, the PKI backend could use the HSM for the key generation process instead of storing the keys in the storage backend. This would be quite useful in certain sensitive scenarios where hardware level security is desired for key storage.

**Comment by jefferai** [comment]
This is an item on our internal roadmap so I'm going to close it here. Thanks for suggesting though!

**Comment by igoraj** [comment]
@jefferai since this was a while back i was wondering if it is still on your roadmap? can you share some timeline when this might be available?
