### ISSUE TITLE
API docs for auth login endpoints list X-Vault-Token in sample

### ISSUE THREAD

**Issue by bkrodgers** [hashicorp/vault#3319]
It looks like most, if not all, of the API docs show "X-Vault-Token" as a parameter to the /login endpoint for that backend.  This should be removed, as the login endpoints do not require an X-Vault-Token.

Didn't check all the backends, but here are a few:
https://www.vaultproject.io/api/auth/approle/index.html#sample-request-13
https://www.vaultproject.io/api/auth/github/index.html#sample-request-2

**Comment by chrishoffman** [comment]
Thanks for the report!  I scanned through all the auth endpoints and cleaned up the ones I found.
