### ISSUE TITLE
Cannot write to consul - client token missing

### ISSUE THREAD

**Issue by boncheff** [hashicorp/vault#332]
I am trying to save some data into consul but whenever I try to write I get the following error:
`missing client token`
This is the cURL command I am using:

```
curl -H "X-Vault-Token: xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx" -H "Content-Type: application/json" -X POST -d '{"value":"bar"}' http://172.xx.x.x:8200/v1/secret/aws/testcustomer
```

(@sethvargo edit: removed vault token)

The token I am using is the initial root token - I have also tried creating a new token and still no luck

I even got a colleague to double check in case I am being mega stupid and have missed something but still no luck

Not sure what I am missing - we have read the docs and seem to follow exactly what they say. Anyone aware of any bugs that could cause this?

**Comment by sethvargo** [comment]
Hi @boncheff 

Are you running Vault master? I do not think the X-Vault-Token is available in a released version yet.

**Comment by ianunruh** [comment]
`X-Vault-Token` was [added in 0.1.2](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#012-may-11-2015)

**Comment by boncheff** [comment]
What are you referring to when you say Vault master?

On Thursday, June 11, 2015, Seth Vargo <notifications@github.com> wrote:

> Hi @boncheff <https://github.com/boncheff>
>
> Are you running Vault master? I do not think the X-Vault-Token is
> available in a released version yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/vault/issues/332#issuecomment-111188954>.
>


-- 
*There are 10 kinds of people - Those who understand Binary and those
who don't.*

**Comment by armon** [comment]
@boncheff I think he means did you build your own Vault binary from source, or are you using a released version?

**Comment by boncheff** [comment]
I am using a released version from the website. Downloaded the Linux 64bit
binary

What could be causing this issue?

On Friday, June 12, 2015, Armon Dadgar <notifications@github.com> wrote:

> @boncheff <https://github.com/boncheff> I think he means did you build
> your own Vault binary from source, or are you using a released version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/vault/issues/332#issuecomment-111305463>.
>


-- 
*There are 10 kinds of people - Those who understand Binary and those
who don't.*

**Comment by boncheff** [comment]
My setup (using containers) is explained here: #329 - not sure if it makes a difference that it is running inside containers

**Comment by boncheff** [comment]
Fixed - the Vault version used in this container (https://registry.hub.docker.com/u/sjourdan/vault/) was 0.1.1 not 0.1.2 and this was the issue. It is working now. Thanks for everyone's advice
