### ISSUE TITLE
Writing roles with policy arrays fails

### ISSUE THREAD

**Issue by hrzbrg** [hashicorp/vault#3323]
Hi, I am experiencing an issue with creating new roles in the AWS backend. Even if I go strictly by the docs https://www.vaultproject.io/api/auth/aws/index.html#sample-payload-5 it does not work as expected.
**Environment:**

* Vault Version: 0.8.2
* Operating System/Architecture: macOS 10.12.6

**Expected Behavior:**

```
curl -X POST -H "X-Vault-Token:$VAULT_TOKEN" --data @sample.json https://vault.mgmt.acmecorp.com/v1/auth/aws/role/sample
```
Above curl should successfully create the sample role.

**Actual Behavior:**

```
{"errors":["Error converting input [default dev prod] for field policies: '' expected type 'string', got unconvertible type '[]interface {}'"]}
```
Expected behavior can be achieved when putting the policies as comma separated values `policies: "default, dev, prod"`

**Steps to Reproduce:**

See steps in Expected Behavior

**Odd Things:**
Reading a role via `vault read -format=json auth/aws/role/:role` returns a json where the policies are in square brackets as described in https://www.vaultproject.io/api/auth/aws/index.html#read-role.

**Comment by jefferai** [comment]
I think the documentation got a bit ahead of itself. I'll fix the type.
