### ISSUE TITLE
Cannot unseal new servers in consul-backed cluster

### ISSUE THREAD

**Issue by nevir** [hashicorp/vault#333]
I have a cluster of 3 vault servers backed by consul. The VMs that host the vault servers are also configured to be the consul masters for my fleet. I'm deploying all this via Terraform

I've been happily making changes to those VM's, and replacing them (spinning up new vault/consul masters before terminating the old ones - e.g. Terraform's `create_before_destroy`). It's been working great for a while now; several dozen host refreshes.

However, my fleet is now in a strange state, and I'm unsure how to debug it:

* Spin up a new Vault/Consul master.
* Wait for that host to join the consul cluster (yup! it shows up as a member from its own status and that of all other nodes)
* I then try to unseal the host, and things get weird:
```
> curl -X PUT -d '{"key": "keyfrag1", "secret_shares": 5}' https://10.10.22.227:8200/v1/sys/unseal
{"sealed":true,"t":3,"n":5,"progress":1}
> curl -X PUT -d '{"key": "keyfrag2", "secret_shares": 5}' https://10.10.22.227:8200/v1/sys/unseal
{"sealed":true,"t":3,"n":5,"progress":2}
> curl -X PUT -d '{"key": "keyfrag3", "secret_shares": 5}' https://10.10.22.227:8200/v1/sys/unseal
{"errors":["Vault is not initialized"]}
```

Note that the pre-existing Vault servers in the fleet *are* initialized; and respond to queries just fine.

Does this mean the new Vault servers somehow reconstructed the correct key via the unseal process, but cannot read the rest of the state that's stored in consul?

**Comment by armon** [comment]
@nevir Are you running a mix of versions? The current master is changing around how some things work that could cause issues

**Comment by nevir** [comment]
Son of a... Yup! I was playing around with a build of master, and messed up my revert of it

**Comment by nevir** [comment]
That I can fix - rolling my stuff back to 0.1.2 :)

**Comment by armon** [comment]
@nevir If you accidentally ran master it may have forwarded upgraded the key structure so that 0.1.2 may not understand it. If so, you should be able to run the master build on all of them.

**Comment by nevir** [comment]
no worries - there's nothing critical in my fleet yet; it's pretty painless to start fresh, and it's a good excuse for me to make sure I've got everything documented
