### ISSUE TITLE
how to access a vault + consul cluster by one ip ?

### ISSUE THREAD

**Issue by Silence2012** [hashicorp/vault#3334]
I have set up a vault + consul cluster.
I want to access this cluster by one ip, how should I do this ?
for example:
10.10.10.2:8200 for vault server 1  High-Availability Enabled: true
10.10.10.3:8200 for vault server 2  High-Availability Enabled: true
10.10.10.4:8200 for vault server 3  High-Availability Enabled: true

Is there any vault  mechanism to let us use one ip to access this cluster. So that even vault server 2 or vault server3 down, this cluster also worked well. Or the only way is to use ohter software like nginx as load balance

**Comment by jefferai** [comment]
You can use a load balancer, or you can use a service discovery mechanism like Consul. There is nothing built into Vault, however.

**Comment by Silence2012** [comment]
@jefferai thanks for your comments. Can you provide me a sample configure file how should I use a consul cluster as one vault instance's backend. For example, consul node1 10.10.10.2, consul node2 10.10.10.3, consul node 3 10.10.10.4.  So how should I use this consul cluster as one vault instance's backend in the configure file.

**Comment by jefferai** [comment]
Vault should always point to a local Consul agent that is on the same node as itself.
