### ISSUE TITLE
Register Vault service using its own IP address

### ISSUE THREAD

**Issue by fieryvova** [hashicorp/vault#3338]
**Feature Request:**
Register Vault service using its own IP address instead of Consul agent's IP when using Consul storage backend.

* Vault Version: v0.8.2 ('9afe7330e06e486ee326621624f2077d88bc9511')
* Operating System/Architecture: Alpine Linux 3.6 / x86_64

**Vault Config File:**
```
listener "tcp" {
  address         = "0.0.0.0:8200"
  cluster_address = "0.0.0.0:8201"
  tls_disable     = "true"
}

storage "consul" {
  path    = "vault"
}

disable_mlock = true
```

**Expected Behavior:**
Vault service should resolve into its own IP address when queried via Consul DNS.

**Actual Behavior:**
vault.service.consul resolves into Consul agent's IP address.

**Important Factoids:**
 I'm running Vault _cluster_ in Docker containers in sandbox environment. Consul agent's IP address is set in $CONSUL_HTTP_ADDR variable that's available in Vault container. I'd like to have Consul agent in a separate container. If it's in a separate container, Vault service resolves into Consul agent's IP address.

**Comment by jefferai** [comment]
You should be able to use https://www.vaultproject.io/docs/configuration/index.html#api_addr (on 0.9) to control this; the address registered with Consul should be the one set in this parameter/env var.
