### ISSUE TITLE
Using multiple tokens to read data

### ISSUE THREAD

**Issue by devabuse** [hashicorp/vault#3339]
Our PCI expert mentioned that it would be better if we could use two tokens instead of one to read or write data to vault. Is this currently possible or perhaps planned for a future release?

Thanks!

**Comment by jefferai** [comment]
It is not currently possible, but something along those lines is on the internal roadmap. If it doesn't shift, I'd guess 3-6 months.

**Comment by brycesteinhoff** [comment]
Does anybody know if Vault has this functionality yet?

**Comment by jefferai** [comment]
This exists in the form of Control Groups (Enterprise only).
