### ISSUE TITLE
Space in path causes issues in the secret backends

### ISSUE THREAD

**Issue by armon** [hashicorp/vault#334]
If a request is made with a space in it like `/v1/auth/ldap/login/armon dadgar` the space is not properly parsed and handed to the backend, causing potential issues.

**Comment by annanay25** [comment]
I have identified the module which requires a change to check for the space parsing, but I wanted to know what steps need to be taken if a space is found. Should the space simply be removed and the remaining query passed? Or should the core log an error and wait for another request?

**Comment by armon** [comment]
Closing in favor of #347
