### ISSUE TITLE
App role auth failures should log as an error

### ISSUE THREAD

**Issue by sgmiller** [hashicorp/vault#3340]
**Feature Request:**

I'm attempting to set up automated alerting on Vault security violations.  Rigging up an alert when a request is denied due to permissions is straightforward, as the error field contains "permission denied".

However, we use app role authentication, and while the Vault client produces an error message:

* failed to validate SecretID: failed to find secondary index for role_id "bb6dc7cd-61fe-4ab7-a8c0-0e477b622530"

The audit entry (syslog) neither looks like an error, or has any field that might indicate a failed attempt at authenticating:

`Sep 15 19:14:39 dev-vault-i-0a042bd6d302e754c vault[17447]: {"time":"2017-09-15T19:14:39Z","type":"response","auth":{"client_token":"","accessor":"","display_name":"","policies":null,"metadata":null},"request":{"id":"d3fa1512-787d-2575-9a39-797e710e79e7","operation":"update","client_token":"hmac-sha256:fa2d7fdf8bcb8053b8b6dcf42356d8a9f88417a40b8d475118ff0c2587a86bf7","client_token_accessor":"hmac-sha256:6959c9ef00ccf1f546bbdbf899813ecc82efa3d7df1b00db8b04f226c72a9d52","path":"auth/approle/login","data":{"role_id":"hmac-sha256:536d17ee28d8c55a84ef6fd617c46264e6def789498c7c759700164bb5e1ec6a","secret_id":"hmac-sha256:f39bb497bd3189a334a5b1dadeca422a0c1e340ccb66cfa4ca259914ea400071"},"remote_address":"10.0.3.102","wrap_ttl":0,"headers":{}},"response":{"data":{"error":"hmac-sha256:ee6b069f05d3468432c701dbb376a36701cb3cba6363460e9c6ad3b7f142a2fa"}},"error":""}
`

It would be nice if the audit entry was in some way recognizable as an error.

**Comment by jefferai** [comment]
The "response" dict's data has a non-empty "error" key, so you can tell it was an error from that.
