### ISSUE TITLE
DB Plugin password generate special characters

### ISSUE THREAD

**Issue by srmysqldba** [hashicorp/vault#3346]
**Feature Request:**
Would like to see the addition to specify special characters to use along with the A1a standards for DB password creations. Also the ability to specify password length larger than default 20 characters. 

**Environment**
* Vault Version: 0.8.2
* Operating System/Architecture: CENTOS 7

**Expected Behavior:**
Generate DB passwords with specific special characters and specify more than 20 character limit while using A1a.

**Actual Behavior:**
Generates 20 character password following the A1a rule standards.

**Important Factoids:**
This helps to ensure random password complexity that will provide tightened security.

**Comment by jefferai** [comment]
It'd be nice to add some more tuning knobs above and beyond the different pre-defined plugin types.

**Comment by aphorise** [comment]
[**password-policies**](https://learn.hashicorp.com/tutorials/vault/password-policies?in=vault/policies) have now been introduced in 1.5.0 - though not yet with support for DB engines.

**Comment by vishalnayak** [comment]
https://learn.hashicorp.com/tutorials/vault/password-policies?in=vault/policies should solve most use cases.
