### ISSUE TITLE
AWS auth backend docs for policies, array vs string

### ISSUE THREAD

**Issue by jhmartin** [hashicorp/vault#3347]
The documentation for the policies block of a AWS auth role definition shows an array but only accepts a string.

**Environment:**

* Vault Version: Vault v0.8.2 ('9afe7330e06e486ee326621624f2077d88bc9511')
* Operating System/Architecture: Linux e1be6d98e302 4.9.31-moby #1 SMP Sat Jun 24 06:29:23 UTC 2017 x86_64 Linux (docker) 

**Expected Behavior:**
AWS auth role created

**Actual Behavior:**
Role failed due to incorrect datatype:
```
{"errors":["Error converting input [default dev] for field policies: '' expected type 'string', got unconvertible type '[]interface {}'"]}
```

**Steps to Reproduce:**
Mount the AWS authentcation backend.
Create a role in form:

```json
{
  "bound_iam_principal_arn" : "arn:aws:iam::x:role/x",  
   "role_tag": "",
  "policies": ["default", "dev"],
  "max_ttl": 1800000
}
```
Attempt to load it:
```curl -kvis https://localhost:8200/v1/auth/aws/role/testrole -H "X-Vault-Token: $ROOTTOKEN" -XPOST -d @/tmp/b
```
Request fails.

Retry with policies as a string:
```json
{
  "bound_iam_principal_arn" : "arn:aws:iam::x:role/x",  
  "role_tag": "",
  "policies": "default,dev",
  "max_ttl": 1800000
}
```

returns a complaint about the number binds.

**References:**
https://www.vaultproject.io/api/auth/aws/index.html#sample-payload-5 shows the policies an array.

**Comment by jefferai** [comment]
This should be fixed in the upcoming 0.8.3.

**Comment by taemon1337** [comment]
This same issue is also present in the '/auth/token/roles/:role_name' endpoint with at least the 'allowed_policies' field.  

I have not checked any other fields but the api docs state the field is a List [], but it fails stating its expecting a 'string', same as this issue.

**Comment by jefferai** [comment]
@taemon1337 we will address that in 0.9.1.
