### ISSUE TITLE
ACL issues

### ISSUE THREAD

**Issue by nbrownus** [hashicorp/vault#335]
Consider the following policies

```
name = "parent-policy"

path "auth/token/create" {
    policy = "write"
}

path "dev/"
    policy = "deny"
}
```

```
name = "child-policy"

path "dev"
    policy = "read"
}
```

If I have a parent token `t1` that has both policies it will not be allowed to access the path `dev/`. `t1` can mint a child token `t2` and give it only the `child-policy` policy. `t2` can access the path `dev` which is the goal but since paths are greedy (#331) I would prefer to include the trailing slash making it `dev/`.

Couple of ideas on how to solve it:
- weights for paths or policies
- a no-op character for paths, maybe `.`?

**Comment by armon** [comment]
I wonder if because Vault is default deny, that any explicit "deny" should take precedence?

**Comment by nbrownus** [comment]
That would be my preference but I though it may be backwards incompatible.
