### ISSUE TITLE
Vault UI - Backends still visible after unmounting via CLI

### ISSUE THREAD

**Issue by censored** [hashicorp/vault#3352]
**Environment:**
* Vault Version: Vault v0.8.2+pro ('f6153a5487af04f3e05f4f2f4f00ea1f4e564412+CHANGES')
* Operating System/Architecture: Ubuntu Xenial 16.04.1 LST x86_64

**Vault Config File:**
N/A

**Startup Log Output:**
N/A

**Expected Behavior:**
Unmounting secret backend should remove it from the list of secrets in the UI. 

**Actual Behavior:**
The secret backend continues to be displayed until you fully reload the page and re-authenticate (testing via root token auth at the moment). It also browsing into it, displays no records, but lets you attempt to create secrets in it (which does successfully fail with '`no handler for route 'secret/a`')

**Steps to Reproduce:**

1. Log into the UI
2. Create a new generic backend
3. Add a key/value pair
4. Unmount the backend via the CLI 
5. Browse to the backend in the browser

**Important Factoids:**
If you create a new backend via the CLI, then click away from the Secrets page and back, it refreshes with the new backends. If you remove them via the CLI, click away from the Secrets page and back, it does not reflect you unmounted them. So, adding via CLI does make them visible, but umounting via CLI does not remove them.

**Comment by meirish** [comment]
It turns out that the framework we use is pretty aggressive about caching on the front end - we've changed this so that navigating away and back to the list should show the proper backends. In the future we may add polling so that the list will just update on an interval - for now though the list will be correct when loading that screen.

**Comment by meirish** [comment]
Oh forgot to say, this is in 0.8.3 ent as well!
