### ISSUE TITLE
Vault audit format

### ISSUE THREAD

**Issue by ror6ax** [hashicorp/vault#3356]
Setting up audit to write to Logstash here. 

Can you please provide the format audit follows?

I think having the logstash grok pattern in public here would be useful for a lot of people.

**Comment by Constantin07** [comment]
Hi,
I would like to push the logs to Elasticsearch and it would be good to have a description of `schema` used for JSON audit records. Any help with this would be much appreciated.

**Comment by Constantin07** [comment]
What's the purpose of `"headers": {}` in the audit logs ?
Tried to make an API request with some custom HTTP headers attached but they don't appear in the  logs.

**Comment by vishalnayak** [comment]
There is no JSON schema per-se for the audit log entries. The Go struct will be marshaled as a JSON string and is output. There has been timely modifications to the items that get audit logged. The only thing I can think of is to point you to the struct that gets translated into log entries. https://github.com/hashicorp/vault/blob/539cb262f13be3511bbcb59d9edc917d7120e5fa/audit/format.go#L353, https://github.com/hashicorp/vault/blob/539cb262f13be3511bbcb59d9edc917d7120e5fa/audit/format.go#L362.

Hope this helps!

**Comment by vishalnayak** [comment]
> What's the purpose of "headers": {} in the audit logs ?
Tried to make an API request with some custom HTTP headers attached but they don't appear in the logs.

@Constantin07 You'd have to use https://www.vaultproject.io/api/system/config-auditing.html#create-update-audit-request-header for the headers to show up.

**Comment by Constantin07** [comment]
@vishalnayak Thank you, already figured it out.

**Comment by catsby** [comment]
Hello - I'm going to close this issue now. The format is specified in the documentation:

- https://www.vaultproject.io/docs/audit/index.html#format
