### ISSUE TITLE
Database secret backend config error

### ISSUE THREAD

**Issue by ssubramanian123** [hashicorp/vault#3359]
Hi,

I am trying to configure database secret backend with cassandra DB and getting below error. 

Steps followed:

Step 1
````
$ vault mount database
Successfully mounted 'database' at 'database'!
````
Step 2
````
vault write database/config/cassandra \
    plugin_name=cassandra-database-plugin \
    allowed_roles="readonly" \
    hosts=<<mycassandrahost>> \
    username=cassandrauser \
    password=cassandrapwd

Error writing data to database/config/cassandra: Error making API request.

URL: PUT https://vault.vault:8200/v1/database/config/cassandra
Code: 400. Errors:

* error creating database object: error verifying connection: error creating session: gocql: unable to create session: control: unable to connect to initial hosts: Invalid or unsupported protocol version (2); supported versions are (3/v3, 4/v4, 5/v5-beta)
````

We are using cassandra cluster version Cassandra 3.10.

Can you please check and confirm what is missing here?

Thanks,
Sakthi

CC: @jefferai

**Comment by briankassouf** [comment]
Hi  @ssubramanian123,

Try also setting `protocol_version=3`, this defaults to `2` so it seems the protocol versions are not matched up.

**Comment by ssubramanian123** [comment]
Thank you very much @briankassouf.

It worked.

````
vault write database/config/cassandra \
>     plugin_name=cassandra-database-plugin \
>     allowed_roles="readonly" \
>     protocol_version=3 \
>     hosts=<<my localhost>>\
>     username=cassandrauser \
>     password=cassandrapwd


The following warnings were returned from the Vault server:
* Read access to this endpoint should be controlled via ACLs as it will return the connection details as is, including passwords, if any.

````

**Comment by ssubramanian123** [comment]
@briankassouf I completed setup for database backend, but I have a basic question now. 

From our java application how to configure connection string to DB. Usually, in code we have connection string consist of host/usr/pwd. But now we get dynamic secrets... how to consume it.. Bit confused... 

Any sample document which shows how to consume dynamic secrets in code...
