### ISSUE TITLE
Vault UI Feature Request  - Customize Authentication Provider in Dropdown

### ISSUE THREAD

**Issue by censored** [hashicorp/vault#3365]
**Feature Request:**
Option to change Authentication Provider ordering in the UI

**Environment:**

* Vault Version: Vault v0.8.2+pro ('f6153a5487af04f3e05f4f2f4f00ea1f4e564412+CHANGES')
* Operating System/Architecture: Ubuntu Xenial 16.04.1 LST x86_64

**Important Factoids:**

I apologize if this is opened in error, I have done some searching around but I didn't find any options or other requests/discussions for this.

I'd like to be able to change the authentication provider ordering in the Vault UI. In our case, people will 99% of the time be logging in with LDAP, and I'd prefer to present that option to them primarily.

Thanks!

**Comment by jefferai** [comment]
@censored As the UI is currently in Enterprise only, please go through Enterprise support channels to log this request. Thanks!
