### ISSUE TITLE
Remove symbols from vault binary.

### ISSUE THREAD

**Issue by BharathB23** [hashicorp/vault#3367]
**Feature Request:**
Provide an optional Makefile target rule to remove symbols from vault binary to make it secure.

**Environment:**

* Vault Version: 
Vault v0.7.3 ('c872b18436d21fa2c440bb947589e0eee1f09aae+CHANGES') (cgo)
* Operating System/Architecture:
Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

Vault binary shouldn't have symbols.

**Actual Behavior:**

Vault binary contains symbols.

**Steps to Reproduce:**

nm vault

**Important Factoids:**

**References:**

I have tested with below changes and it seems to be working for me, please have a look.

1. Below new addition in github.com/hashicorp/vault/Makefile file
dev-secure: fmtcheck generate
       @CGO_ENABLED=1 BUILD_TAGS='$(BUILD_TAGS)' VAULT_DEV_BUILD=1 VAULT_DEVSECURE_BUILD=1 sh -c "'$(CURDIR)/scripts/build.sh'"

2. Below changes in github.com/hashicorp/vault/scripts/build.sh file
LD_FLAGS="-X github.com/hashicorp/vault/version.GitCommit='${GIT_COMMIT}${GIT_DIRTY}'"
if [[ "${VAULT_DEVSECURE_BUILD}x" != "x" ]]; then
    LD_FLAGS="-s -w -X github.com/hashicorp/vault/version.GitCommit='${GIT_COMMIT}${GIT_DIRTY}'"
fi

echo "==> Building..."
gox \
     -osarch="${XC_OSARCH}" \
    -ldflags="${LD_FLAGS}" \
     -output "pkg/{{.OS}}_{{.Arch}}/vault" \
     -tags="${BUILD_TAGS}" \

Regards,
Bharath B

**Comment by jefferai** [comment]
If you send a PR I will take a look. In such a PR please do not duplicate the entire LD flags line, and rather than add a target just key off of VAULT_STRIP_BINARIES.
