### ISSUE TITLE
The `token-create` CLI should return lease information along with the token

### ISSUE THREAD

**Issue by armon** [hashicorp/vault#337]
The `token-create` command currently only provides the token but omits the lease information. That is useful to know as a UX hint that tokens have leases as well.

**Comment by sethvargo** [comment]
@armon I think it would also be helpful to have text in english like:

```text
This token will expire in XXX unless renewed. A token can be renewed via the HTTP API or via the command line, for example:

    $ vault renew ...
```

This way users have a very clear indication of "I need to do something".
