### ISSUE TITLE
go1.7.3 fail

### ISSUE THREAD

**Issue by jettero** [hashicorp/vault#3371]
I'm not very good with golang yet, so it took me a while to figure out that my builds were failing because of a golang version problem. I was getting two screenfulls of errors that started with something like:

```
vendor/github.com/posener/complete/cmd/install/install.go:75: undefined: os.Executable
# github.com/hashicorp/vault/vendor/github.com/cockroachdb/cockroach-go/crdb
vendor/github.com/cockroachdb/cockroach-go/crdb/tx.go:46: undefined: sql.TxOptions
vendor/github.com/cockroachdb/cockroach-go/crdb/tx.go:48: db.BeginTx undefined (type *sql.DB has no field or method Beg
# github.com/hashicorp/vault/vendor/github.com/coreos/etcd/pkg/transport
vendor/github.com/coreos/etcd/pkg/transport/listener.go:182: cfg.GetClientCertificate undefined (type *tls.Config has n
```

Everything builds fine when I upgrade to go1.9.x (and forum comments in other projects suggest go1.8.x would wrok too).

Is there a way for the build tools to notice a version of golang too old?

**Comment by chrishoffman** [comment]
It is currently documented that Go 1.9 is required and there is a PR in review to improve the build tooling around Go versions.

See #3309.

**Comment by jettero** [comment]
I missed both despite looking. Sorry about that.
