### ISSUE TITLE
Vault Cassandra Config error

### ISSUE THREAD

**Issue by heyitsaakash** [hashicorp/vault#3374]
for cassandra 3.11 getting error
Hi,
When trying to mount and connect cassandra for secrets i am getting error below - 

vault write database/config/cassandra plugin_name=cassandra-database-plugin  allowed_roles="readonly" hosts=localhost username=cassandra password=cassandra 
Error writing data to database/config/cassandra: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/cassandra
Code: 400. Errors:

* error creating database object: error verifying connection: error creating session: gocql: unable to create session: control: unable to connect to initial hosts: dial tcp [::1]:9042: getsockopt: connection refused

**Comment by jefferai** [comment]
Duplicate of #3370

**Comment by ror6ax** [comment]
@heyitsaakash - how did you run into this?

**Comment by heyitsaakash** [comment]
I ran the following commands
1 . vault mount database
2. vault write database/config/cassandra plugin_name=cassandra-database-plugin  allowed_roles="readonly" hosts=localhost username=cassandra password=cassandra

at backend cassandra is runnning. I am running vault in dev mode. I have not made any other configuration changes so far such as setting storage backed etc.

**Comment by RohanKurane** [comment]
@heyitsaakash were you able to resolve this ?
