### ISSUE TITLE
feature request: ssh certificate revocation list

### ISSUE THREAD

**Issue by OferE** [hashicorp/vault#3377]
**Feature Request:**
Please add support for generating revocation list for SSH certificates.
Currently I need to manually keep track of all the certificates I signed using vault and generate a revocation list manually. Would be great if this can be supported by vault itself.
Thanks!

**Comment by jefferai** [comment]
We generally recommend making certificate lifetimes useful for only a single connection. As a result CRLs are unnecessary. This workflow can be made easier using `vault ssh`.

**Comment by OferE** [comment]
This is too strict for development accounts. The bureaucracy of creating new certificate every time is too much. 
(BTW I opended a ticket in terraform for not supporting connections with certificates).

For production accounts it's reasonable.

**Comment by jefferai** [comment]
Isn't it the same workflow?

**Comment by OferE** [comment]
I'm not sure what you mean by workflow.
We use ssh certifictaes to grant permissions to real human users not for automation/services.

Our product is in development mode and still not in production.
For development clusters I prefer to work with long living certificates. For production we will issue short living certificates.

**Comment by jefferai** [comment]
What I mean is, if you use `vault ssh` to connect (or a custom script that does essentially the same thing), whether the certificates are short lived or long lived makes very little difference.

**Comment by johndistasio** [comment]
That workflow is predicated on the Vault cluster being available and reachable for `vault ssh`, no? . If I'm using certificates for SSH, there is probably a good chance I'm doing it to avoid a dependency on some separate authentication infrastructure during an emergency.

It would be nice to distribute a CRL with Consul Template or similar.

+1 for this feature request.

**Comment by kogent** [comment]
I would agree that there are some use cases where longer ttls is appropriate.  Being able to revoke those would be very welcome.

**Comment by kenrestivo-stem** [comment]
We have a use case where we need:

1. Long-lived connections and keys
2. Only SSH from the client, no connection to vault
3. Ability to revoke keys on a key-by-key basis

I don't see a way to do this with Vault CA (which isn't really a CA as there's no CRL and the host doesn't check) or OTP (which requires that the client be able to reach Vault in order to fetch its OTP, nor do I see a way to revoke its access on a client-by-client basis either)

**Comment by tq05** [comment]
Any update on this. 
Seems like quite a fundamental functionality to have if you start supporting ssh ca and play in this world as well.

Makes a hard sell against other technologies otherwise

**Comment by nafpliot-ibm** [comment]
I also find this a really nice to have feature. If revocation cannot be done, we should at least have a way to list all the certificates that are signed. It's easy to lose track if you work with long living certificates...

**Comment by adambaumeister** [comment]
+1. The idea of short-lived certificates makes good sense but pkey auth is widely used for many other applications where it's not applicable. 

Revocation or at least an index of signed certificates would be a great feature to be built into the workflow.

**Comment by jefferai** [comment]
> The idea of short-lived certificates makes good sense but pkey auth is widely used for many other applications where it's not applicable.

Can you give us examples of these applications/use-cases? It seems like you're better off in the end making some wrapping around those to use short-lived certificates than using long-lived ones.

Storing lists of issued certificates in Vault is relatively expensive, especially when they're very short term, causing a lot of storage churn. I should note however that you don't need Vault specifically to generate a KRL for you. KRLs are unsigned (AFAICT) so anyone can generate one at any time.

**Comment by adambaumeister** [comment]
@jefferai 

Can be summarized as any case where: 
- The vault server is not reachable from the client 
- Wrapper code or binaries are undesirable 

A practical example would be the classic (and ubiquitous) SSH proxy server, another would be standalone cloud deployments where the password vault is on-prem. 

It's a chicken and egg thing with the KRL as well, without any storage on the Vault side I don't have the pkeys to build the list. 

A simple solution might be an option somewhere to not hash the pkey when sent to the audit plugin.

**Comment by jefferai** [comment]
You can already not hash values sent to audit. See https://www.vaultproject.io/api/system/mounts.html#audit_non_hmac_response_keys-1

**Comment by jefferai** [comment]
Although I'd opt out of hashing the serial number rather than the private key.

**Comment by adambaumeister** [comment]
As far as I know there is no method to route individual secrets backends to a specific audit method which means youd be turning of hashing within auditing altogether, which wouldn't be so good. I could be wrong?

**Comment by jefferai** [comment]
Setting that would turn off hashing the serial number for that particular mount for all audit methods, yes. But serial numbers are not generally sensitive anyways.

**Comment by darrylweaver** [comment]
Such a shame, we would also have adopted Vault for SSH key management, except that this feature is not available and the only answer given is that your use case is not a valid one and it has been left for 2 years.  

But the PKI secrets backend has an automatically generated CRL for that use case and the same mechanism for SSH would have allowed us to adopt it.

**Comment by pescobar** [comment]
After reading the comments in this issue I guess the answer is NO but I will ask just in case....is there any way to implement something like this using hashicorp vault? or any plan to add this feature?

https://github.com/nsheridan/cashier#revoking-certificates

**Comment by jefferai** [comment]
@pescobar it's not currently on the internal roadmap to add this but it might at some point. An interested community member could maybe work with someone on the Vault team to implement this. However I don't think that this backend currently stores issued certs. If not we don't have any current way of knowing any cert details.

One really key thing here is that for an X509 certificate a crl must be signed. That's not the case for SSH certificates. So vault creating a file for you is convenient but by no means a requirement because you don't need access to the private key to generate it.

**Comment by kaizen1** [comment]
> I'm not sure what do you mean by workflow.
> We use ssh certifictaes to grant permissions to real human users not for automation/services.
> 
> Our product is in development mode and still not in production.
> For development clusters I prefer to work with long living certificates. For production we will issue short living certificates.

+1 for this. This is how de

> I also find this a really nice to have feature. If revocation cannot be done, we should at least have a way to list all the certificates that are signed. It's easy to lose track if you work with long living certificates...

Seems like the whole point is to be able to revoke, regardless of TTL. People go rogue in milliseconds, not minutes or hours. Seems like a gaping hole.

**Comment by jefferai** [comment]
You can't revoke access with Vault, because unlike the internet PKI, SSH KRLs have no distribution mechanism -- there's nothing like CRL Distribution Points. Given that you must perform all distribution yourself _and_ that no signature is used for KRLs there's little for Vault to do here.

Listing issued certificates could maybe be added although it's not a super trivial lift. I'm going to close this ticket though as it's about CRLs and there isn't a clear path forward that leverages Vault.

If you want to have Vault store cert information for later listing please open a ticket for that.

Otherwise my suggestion is to simply not use long lived certificates. Vault can handle issuing a certificate per connection, so making certificates very short is a good way to limit later connections without current authorization.

**Comment by kquinsland** [comment]
> > I also find this a really nice to have feature. If revocation cannot be done, we should at least have a way to list all the certificates that are signed. It's easy to lose track if you work with long living certificates...
> 
> Exactly. The whole point of centralized management is to be able to revoke access, regardless of TTL. People go rogue in milliseconds, not minutes or hours. It's a gaping hole.

This is _precisely_ the scenario that I'm most curious about:

For reasons that are not relevant here, I need a SSH key to be valid for at least 12h, ideally up to 36h. A human will be using this ssh key and will likely have long-running connections. Think `tail -f /var/log/....` kinda thing.

If this hypothetical human is let go 24h after their certificate is issued, i would _really_ like to void out the last 12h that the cert is good for ASAP.


A related situation:

A routine process requires SSH between nodes to function. E.G.: `routine_process.sh` running on `node00` will ssh into `node01` and `node02` ... etc to run some commands.  The commands could finish in as little as 15 min or could be running for literal _days_.  If Im understanding this thread correctly, I would have to assume that each SSH connection will take days and so I should allocate a SSH certificate that's good for several days. I have no way to revoke that certificate early if the process only took a few hours.

**Comment by Fuco1** [comment]
So many platforms completely ignore the CRL and revocation with certificates that I wonder if anyone actually uses any of this in production.  I got burned with traefik before and now with vault again.  Any sort of certificate scheme is completely **unusable** without revocation.  Expiration is not a mitigation strategy.

Of course you can always rotate all your CA certs... basically revoking everyone's access all at once. /shrug

**Comment by selurvedu** [comment]
@kquinsland the validity is only checked when the connection is being estaished. E.g. you can have a CA signature that's valid for 30 seconds but use it for a long-running session. That's what Vault does by default.

**Comment by kquinsland** [comment]
@selurvedu I was able to confirm that during some testing... and then discovered that uber created a PAM module to solve exactly that problem.

My point about being able to immediately revoke a certificate that has yet to expire still sands though.  I am contemplating w/ doing just that; a root CA re-issue, but there are some users / internal tools that may have disrupted workflows.

**Comment by Celant** [comment]
@jefferai Would adding the ability for Vault to sign a provided KRL be an option? As you mention KRLs don't actually need to be signed, and it would take a reasonable amount of work for the Vault SSH engine to generate its own revocation list. I feel like having the ability for Vault to sign a KRL that is provided by the user might be a fair compromise.

**Comment by cipherboy** [comment]
As noted above by Jeff, besides the distribution mechanism...

Certificates are a OpenSSH-specific solution; KRLs are thus the same. Notably, the [OpenSSH spec](https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.krl#L147-L171) states that KRLs need not be signed if they're transmitted over a secured distribution mechanism. This means that, if a signature is warranted, you have the same key distribution problem as using a CA in the first place (the CA root _needs_ to be securely transmitted and thus the KRL could be transmitted via the same path); my read of the TrustedUserCAKeys parameter is that it only applies to CA Cert validations. From the OpenSSH code (https://github.com/openssh/openssh-portable/blob/5f76286a126721fa005de6edf3d1c7a265555f19/sshd_config.5#L332 and https://github.com/openssh/openssh-portable/blob/e7606919180661edc7f698e6a1b4ef2cfb363ebf/krl.c#L1343-L1344 plus https://github.com/openssh/openssh-portable/search?q=ssh_krl_from_blob), my read is that the signature on the KRL isn't even verified by OpenSSH, so any validation would need to be done by the admin prior to installing the KRL but after fetching it.

The net of this is that an external `ssh-keygen` invocation without access to Vault's private key material is more or less equivalent to a Vault signed and maintained KRL, assuming a secured distribution mechanism. Thus, from a Vault perspective, there is no real benefit to having a signed KRL mechanism.

Lastly, note that the Go [`x/crypto/ssh` package](https://pkg.go.dev/golang.org/x/crypto/ssh) lacks support for KRL building and signing; this is a required precursor to Vault support as we heavily rely on that package for SSH stuff. We're unlikely to contribute such support, so unless support lands via a third-party, its unlikely Vault's SSH engine will include KRL support.
