### ISSUE TITLE
Permission Issue when using cassandra as Storage backend

### ISSUE THREAD

**Issue by heyitsaakash** [hashicorp/vault#3378]
I am using windows. I was earlier running vault in inmem mode and it was working fine to store and retrieve secrets.
But, i want to move more towards stable production mode and wish to use cassandra as backend.
here is my configuration file vault.conf

storage "cassandra" {
  hosts            = "192.168.33.10"
  consistency      = "LOCAL_QUORUM"
  protocol_version = 3
  username	= "cassandra"
  password = "cassandra"
}

listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
}

I start the vault using . vault server and then unseal it. However, when i try to write any secrets (as i was doing in inmem mode) it flags an error.
vault write secret/hello value=world
URL: PUT http://127.0.0.1:8200/v1/secret/hello
Code: 403. Errors:
* permission denied

While trying to mount 
URL: POST http://127.0.0.1:8200/v1/sys/mounts/database
Code: 403. Errors:

I get the same error too.

I am also confused that whether using Cassandra as Storage means that I also configure cassandra as secret backend too. How will i retrieve the token similar to the root token i get when i start the server in dev mode. Does it automatically imply the auth backend needs to be configured too to cassandra now. Please throw some light. Will it work fine for windows or i need unix only.

**Comment by jefferai** [comment]
Hi there,

The errors you're getting are not related to cassandra storage, they're because the Vault token you're using does not have permission to access those resources.
