### ISSUE TITLE
Vault does not properly fail if it cant access EC2 metadata

### ISSUE THREAD

**Issue by robotmayo** [hashicorp/vault#3383]
We are running Vault 0.8.2

We are using vault IAM auth for our ECS tasks. We were originally using AWS Linux AMIs then switched over to a custom non amazon linux image. While testing we received this error: 

```
URL: PUT https://vault.internal/v1/auth/aws/login
Code: 400. Errors:
* error making upstream request: received error code %!!(MISSING)s(int=403) from STS: <ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
<Error>
<Type>Sender</Type>
<Code>MissingAuthenticationToken</Code>
<Message>Request is missing Authentication Token</Message>
</Error>
<RequestId>[removed]</RequestId>
</ErrorResponse>
```

After spending quite some time tracking down what was wrong we soon figured out it was because the vault cli inside our container could not connect to the ECS/EC2 metadata to get the IAM information it needed, as we had not properly set up the network to allow for that. Vault should have communicated that it couldn't connect instead of trying to send nothing to STS and printing a irrelevant error.

**Comment by vishalnayak** [comment]
We probably might need to check that the `body` and `headers` are not empty. @joelthompson does it seem like that could fix this?

**Comment by joelthompson** [comment]
@vishalnayak -- I'm not sure, but I don't think so. I want to do a few tests first to just understand some of this behavior (I should be able to get to this in the next couple days).

**Comment by joelthompson** [comment]
Sorry it took me longer than anticipated to get to this; I think the right solution is in #3465
