### ISSUE TITLE
Vault UI Pro - DR Doesn't allow enabling Secondary

### ISSUE THREAD

**Issue by censored** [hashicorp/vault#3384]
**Environment:**
* Vault Version: Vault v0.8.3+pro ('a0ce18244b6ef266f7b967d5fa204dcaff675c0d+CHANGES')
* Operating System/Architecture: Ubuntu Xenial 16.04.1 LST x86_64

**Expected Behavior:**
Setting up primary/secondary DR Replication between two sites in the UI works properly

**Actual Behavior:**
You can enable DR on the primary, however as soon as you attempt to enable vault as a secondary in the UI, you get the message

```
When running as a DR secondary Vault is read only. For this reason, we don't allow other replication modes to operate at the same time. This cluster is also currently operating as a Performance . In order to demote this cluster, you will first need to disable Performance Replication.
```
Performance Replication is not an option in the Pro version.

Enabling DR secondary via the API commands works properly.

**Steps to Reproduce:**
* Start up Vault Pro, init, unseal
* Log into the Vault UI
* Choose Replication
* Change the Replication cluster mode to secondary. You will get the above mentioned error.

Work around: Enable the replication via API
```
steph@purgatory:~$ curl --header "X-Vault-Token: xxxx" --request POST --data @payload.json  https://vault.ash.xx.com/v1/sys/replication/dr/secondary/enable 

{"request_id":"98a56b4e-f894-0c9a-3854-f5b4bd9fff47","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Vault has succesfully found secondary information; it may take a while to perform setup tasks. Vault will be unavailable until these tasks and initial sync complete."],"auth":null}
```
(also, successfully is spelled wrong in the above output)

```steph@purgatory:~$ curl https://vault.ash.xx.com:8443/v1/sys/replication/dr/status -k
{"mode":"dr-secondary","secondary_id":"ASH","last_remote_wal":0,"known_primary_cluster_addrs":["https://vault.sea.xx.com:8444/","https://vault.sea.xx.com:8444/"],"last_wal":33,"cluster_id":"cca331
```
etc etc.

**Comment by micheldlebeau** [comment]
I can confirm that this is an issue, using Vault 0.8.3+pro, and that using the CLI works.

It seems like the performance flag is enabled on the primary out of the box, but because it is the pro version then it blocks the DR replication from happening?

**Comment by jefferai** [comment]
I apologize, but this needs to go through the Enterprise support channels. GitHub is for issues with the open source version only. Sorry!

**Comment by micheldlebeau** [comment]
That makes sense, however having a public log of the current issues would be extremely useful, as this post saved me some troubleshooting and a support ticket :)

**Comment by jefferai** [comment]
Please bring up that request via Enterprise support channels :-D
