### ISSUE TITLE
AllowTokenDisplayName appears to be dead code in builtin/logical/pki

### ISSUE THREAD

**Issue by cgaspar-deshaw** [hashicorp/vault#3389]
Is there any reason not to remove it from builtin/logical/pki/cert_util.go and builtin/logical/pki/path_roles.go? If not, I'll create a PR.

**Comment by jefferai** [comment]
We haven't decided whether or not to support it again.

**Comment by jefferai** [comment]
Also for roles created a long long time ago that are still relying on this behavior we like to keep things working.

**Comment by michelvocks** [comment]
I'm going to close this issue since a decision has been made to keep this code part.
