### ISSUE TITLE
Unsealing Terraform-provisioned vault

### ISSUE THREAD

**Issue by sheldonh** [hashicorp/vault#339]
I've had a look at the Terraform module provided at https://github.com/hashicorp/vault/tree/master/terraform/aws .

Looks like a great starting point, but it's not clear to me

* how to unseal the Vault, and
* how to purge the unseal keys from the instances to protect against later theft.

Any guidance would be appreciated.

**Comment by sheldonh** [comment]
Ah, I see. It's up to me to `vault init` in whatever environment I feel safe in.

**Comment by yanpozka** [comment]
Hi @sheldonh were you able to deploy vault using this configuration https://github.com/hashicorp/vault/tree/master/terraform/aws ?? thanks in advance

**Comment by sheldonh** [comment]
I wasn't, but I'm afraid it's too long ago to tell you what impeded us.

We ended up using Ansible to provision and maintain our vault+consul
cluster.
