### ISSUE TITLE
Vault Linux(glibc) binary compatible with Alpine (musl) ?

### ISSUE THREAD

**Issue by Constantin07** [hashicorp/vault#3396]
Hi,

Does anyone know if the supplied linux download binary for Linux is compatible with Alpine Linux which uses musl library instead of glibc ?

PS: I have no idea how it' currently build ...

Regards,
Constantin

**Comment by chrishoffman** [comment]
Our current docket image uses Alpine Linux and just uses the regular Linux amd64 build.

See https://github.com/hashicorp/docker-vault.

**Comment by Constantin07** [comment]
@chrishoffman Thanks.
