### ISSUE TITLE
API import causes golang's testing to be imported into the binary

### ISSUE THREAD

**Issue by AgentZombie** [hashicorp/vault#3403]
Importing `"github.com/hashicorp/vault/builtin/credential/aws"` causes the Go standard library's 
`testing` package to be imported as well, adding all that packages `-test*` flags to the command line.

**Expected Behavior:**
Compiling a non-test binary that imports packages other than `testing` shouldn't cause `testing` to be imported.

**Actual Behavior:**
`testing` gets imported.

**Steps to Reproduce:**
blarg.go:
```
package main

import (
        "flag"

        _ "github.com/hashicorp/vault/builtin/credential/aws"
)

func main() {
        flag.Parse()
}
```
Then:
```
$ go run blarg.go -h
Usage of /tmp/go-build585082743/command-line-arguments/_obj/exe/blarg:
  -test.bench regexp
        run only benchmarks matching regexp
  -test.benchmem
        print memory allocations for benchmarks
  -test.benchtime d
        run each benchmark for duration d (default 1s)
...
```

**Important Factoids:**
Files that import `testing` should be named `*_test.go` causing them to only be compiled when running `go test`. Possible culprits:
```
[user@foo go/src/github.com/hashicorp/vault]$ grep -R '"testing"' * | grep -v _test.go | grep \\.go:
command/token/testing.go:       "testing"
http/testing.go:        "testing"
logical/testing.go:     "testing"
logical/framework/testing.go:   "testing"
logical/testing/testing.go:     "testing"
physical/testing.go:    "testing"
vault/seal_testing.go:  "testing"
```

**Comment by jefferai** [comment]
We have code that that uses the test library in some public files on purpose so that they can be accessed from other packages.

**Comment by theckman** [comment]
@jefferai this doesn't seem like an ideal way to write the software, from a package consumer experience perspective. The decision to do so means that anyone consuming the package, while using the built-in flags package, is going to have the testing flags show up in their help output. That's not an extremely great user experience. 

I was curious what problems are being solved by exposing the testing package as part of the API, and digging in to some of the examples, specifically `logical/framework/testing.go`, I don't see anything consuming the function it exports.

* https://github.com/hashicorp/vault/blob/c44f1c9817955d4c7cd5822a19fb492e1c2d0c54/logical/framework/testing.go#L9-L15

Here is the only consumer I could find:

* https://github.com/hashicorp/vault/blob/c44f1c9817955d4c7cd5822a19fb492e1c2d0c54/logical/framework/testing.go#L9-L15

Are you able to provide some examples of its usage?

**Comment by fortytw2** [comment]
I think this is exactly the problem https://github.com/mitchellh/go-testing-interface aims to solve, just swap imports around and bam, no testing flags registered.

**Comment by jefferai** [comment]
There seems to be an assumption that this is a package meant for external consumption. It's not. It's unclear to me why you are sourcing it but if there is a use case for something in there you need chances are it should be refactored out elsewhere.

If you want to send a PR to address this for your needs, feel free, but given that it's an internal package the Vault team won't be spending time on this.

**Comment by AgentZombie** [comment]
In my case:
```
import (
...
"github.com/hashicorp/vault/builtin/credential/aws"
...
)

...
        clih := &awsauth.CLIHandler{}
        authStuff := map[string]string{
                "mount": v.Mount,
                "role":  v.Role,
        }
        sec, err := clih.Auth(v.apiClient, authStuff)
        if err != nil {
                return errors.Wrap(err, "authenticating to vault using AWS")
        }
...
```

Is much, much easier and more reliable than replicating all the code that the Vault CLI has for `IAM` authentication.

**Comment by jefferai** [comment]
The right thing to do here would probably be to move that logic into the helper/awsutil package.
