### ISSUE TITLE
redirect_addr is translated to IP Address

### ISSUE THREAD

**Issue by kplimack** [hashicorp/vault#3404]
Vault v0.7.3 ('0b20ae0b9b7a748d607082b1add3663a28e31b68')
* Operating System/Architecture:
CentOS Linux release 7.2.1511 (Core) , x86_64

**Vault Config File:**
```
{
  "listener": {
    "tcp": {
      "address": "0.0.0.0:8200",
      "tls_cert_file": "/etc/vault/ssl/certs/derp.crt",
      "tls_key_file": "/etc/vault/ssl/certs/derp.key"
    }
  },
  "storage": {
    "consul": {
      "address": "127.0.0.1:8500",
      "path": "vault"
    }
  },
  "backend": {
    "redirect_addr": "https://hashivault0002.myorg.tld:8200"
  }
}
```

**Expected Behavior:**
vault status return the redirect addr as `https://hashivault0002.myorg.tld:8200`

**Actual Behavior:**
```
$ vault status
[snip]
	Leader: https://172.16.6.87:8200
```

**Comment by jefferai** [comment]
redirect_addr is a Consul config argument (https://www.vaultproject.io/docs/configuration/storage/consul.html#redirect_addr) and so must be in the `consul` block.
