### ISSUE TITLE
Windows OS vault cli unable to handle spaces in path names? (using git bash)

### ISSUE THREAD

**Issue by AllenFromMinneapolis** [hashicorp/vault#3408]
**Environment:**

Vault v0.8.3 ('6b29fb2b7f70ed538ee2b3c057335d706b6d4e36')

* Vault Version:
* Operating System/Architecture:
Windows 7

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

**Actual Behavior:**

**Steps to Reproduce:**

**Important Factoids:**

**References:**

Using windows when I try to write or read from our vault on windows I get the following. Don't worry about the 403 I can vault status etc. just fine, look at just before that where it tries to show c:/program files see where it says MISSING? I can't seem to work around this. So I had someone on a MAC write my secret out for me. I can't read or write from windows however.
$ vault read /secret/icesampleappalmc/api/hello-world
Error reading C:/Program Files/Git/secret/icesampleappalmc/api/hello-world: Error making API request.

URL: GET https://vault-proxy.us-central1.tgt-pe-test.gcp.cloud.target.internal:8200/v1/C:/Program%!F(MISSING)iles/Git/secret/icesampleappalmc/api/hello-world
Code: 403. Errors:

* permission denied

**Comment by briankassouf** [comment]
Hi @AllenFromMinneapolis 

Could you post the storage backend configuration you're using in the config file (with secret data redacted)? Is the vault server running on Windows or just the client?

**Comment by AllenFromMinneapolis** [comment]
I'm using just the client

**Comment by AllenFromMinneapolis** [comment]
hitting a vault server in our cloud provider google

**Comment by jefferai** [comment]
It's seriously strange that the flag handling is treating this as a local file path instead of an argument to send to the API. FWIW, I can't replicate this in PowerShell:
```
PS C:\Users\Jeff\Downloads> $env:VAULT_ADDR="http://127.0.0.1:8200"
PS C:\Users\Jeff\Downloads> .\vault.exe read /secret/foo
No value found at secret/foo
```
Note how it's not interpolating the path as being a filesystem path.

**Comment by jefferai** [comment]
Hi @AllenFromMinneapolis ,

I just downloaded Git Bash and tried it out. It looks like it automatically converts any path starting with a slash into a local filesystem path, because reasons?

Vault paths don't start with a forward slash, so simply dropping that would be a suitable workaround. Unfortunately we can't handle this internally because by the time it comes into the Vault executable it's already been mangled by git bash.

Alternately, you can use a native shell like PowerShell.
