### ISSUE TITLE
Vault hungs for ~10 minutes after unseal

### ISSUE THREAD

**Issue by jozuenoon** [hashicorp/vault#3410]
**Environment:**

* Vault Version: Vault v0.7.2 ('d28dd5a018294562dbc9a18c95554d52b5d12390')
* Operating System/Architecture: Linux

**Expected Behavior:**
Vault works immediately after unseal.

**Actual Behavior:**
Vault loops over non existing PostgreSQL leases and choke itself so none requests are processed meanwhile. This could take up to several minutes. Example output:
```
2017/10/03 15:05:15.730520 [ERROR] expiration: failed to revoke lease: lease_id=database/creds/aaa/xxx1 error=failed to revoke entry: resp:(*logical.Response)(nil) err:pq: role "v-approle-xxx1" does not exist
2017/10/03 15:05:15.760242 [ERROR] expiration: failed to revoke lease: lease_id=database/creds/aaa/xxx2 error=failed to revoke entry: resp:(*logical.Response)(nil) err:pq: role "v-approle-xxx2" does not exist
```

Mentioned roles are not existing really in PSQL database, I found no way to remove them
from Vault storage. Vault is configured with 2 replicas on S3 storage living in K8S cluster.

**Steps to Reproduce:**
1. Create PostgreSQL lease,
2. Remove created user from PostgreSQL database,
3. Try to revoke lease from Vault.

**Comment by jefferai** [comment]
Hi @jozuenoon ,

You can use the revoke-force API (https://www.vaultproject.io/api/system/leases.html#revoke-force) to tell Vault to forget about these leases.

If you upgrade to Vault 0.8.3 startup should be significantly faster as we now lazy-load leases on startup.

**Comment by sprutner** [comment]
We are also experiencing this issue, although the vault process just crashes and restarts before it can successfully do this. Upgrade to 0.8.3 did not resolve the issue, but I will look into revoke-force.

**Comment by atheiman** [comment]
@jefferai We're seeing this too, is there a number of tries vault will make to delete the database user before it gives up and forgets about the user in the database?
