### ISSUE TITLE
[Feature Request] Any plans for a swift client?

### ISSUE THREAD

**Issue by gperdomor** [hashicorp/vault#3415]
Do you have plans for a Swift client?

**Comment by swizzlr** [comment]
@gperdomor I’m working on one right now, actually, though it’s somewhat pre-release (so shhh!). https://Github.com/bermudadigitalstudio/Cerberus

**Comment by jefferai** [comment]
Closing -- such a client won't come from the Vault team, but once it's ready we're happy to add it to the list!
