### ISSUE TITLE
Plugin binaries link to nonexisting libs on Alpine

### ISSUE THREAD

**Issue by ror6ax** [hashicorp/vault#3417]
* Vault Version:
0.8.3
* Operating System/Architecture:
x64

**Expected Behavior:**
Using plugins in Docker container based off Alpine Linux

**Actual Behavior:**
/vault/vault_plugins # sh ./pluginbinary
./pluginbinary: line 1: ELF&#x2;&#x1;&#x1;&#x2;: not found
./pluginbinary: line 2: syntax error: unexpected word (expecting ")")

/vault/vault_plugins # ldd ./pluginbinary 
    /lib64/ld-linux-x86-64.so.2 (0x7f2a6b3b3000)
    libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f2a6b3b3000)
    libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f2a6b3b300

**Steps to Reproduce:**
Execute plugin binary on Alpine.

**Comment by jefferai** [comment]
Which plugin is this?

**Comment by ror6ax** [comment]
My own build. The build command usual `go build . `

**Comment by jefferai** [comment]
If you don't want the plugin dynamically linked you'll need to force it to statically link. Usually it is sufficient to pass CGO_ENABLED=0 at build time, which is how we build vault and our official plugin builds.
