### ISSUE TITLE
vault create secret error with argument too long 

### ISSUE THREAD

**Issue by ssubramanian123** [hashicorp/vault#3428]
vault create secret error with argument too long 

Hi,

I am trying to store application config as secret in vault. It works perfect, but 2 configs files are very big in size (around 2K and 5K lines) for those files getting argument too long error. Do we have any limit in size of secret? If need to increase the size, how to increase it? Please help.
````
cat test.config | base64 -w 0 > base64.txt
export B64=$(cat base64.txt )
vault write secret/config-test/$(basename test.config) vaule="$B64"
bash: /usr/bin/basename: Argument list too long
bash: /usr/local/bin/vault: Argument list too long
````

````
cat test1700.config | base64 -w 0 > base64.txt
export B64=$(cat base64.txt )
vault write secret/config-test/$(basename test1700.config) vaule="$B64"
Success! Data written to: secret/config-test/test1700.config
````

**Comment by ssubramanian123** [comment]
@jefferai looks database column has enough size might be issue in vault code base.. Can you please review and confirm.

````
MySQL [k8svault_dev]> DESCRIBE vault;
+-------------+----------------+------+-----+---------+-------+
| Field       | Type           | Null | Key | Default | Extra |
+-------------+----------------+------+-----+---------+-------+
| vault_key   | varbinary(512) | NO   | PRI |         |       |
| vault_value | mediumblob     | YES  |     | NULL    |       |
+-------------+----------------+------+-----+---------+-------+
````

**Comment by joelthompson** [comment]
@ssubramanian123 -- the error you're getting is coming from bash, not Vault. The bash shell can't handle all that data on the command line. For that size data, you should either [use stdin or a file](https://www.vaultproject.io/docs/commands/read-write.html#stdin).

**Comment by ssubramanian123** [comment]
@joelthompson Thank you very much.. let me try stdin or file and update here..

**Comment by ssubramanian123** [comment]
@joelthompson it works fine with file.
