### ISSUE TITLE
HashiCorp Vault vs. Azure Key Vault

### ISSUE THREAD

**Issue by FCC-User01** [hashicorp/vault#3429]
Could you do a comparison between Hashicorp Vault and Azure Key Vault.

**Environment:**

* Vault Version:
* Operating System/Architecture:

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

**Actual Behavior:**

**Steps to Reproduce:**

**Important Factoids:**

**References:**

**Comment by sylus** [comment]
I would be interested in this as well.

**Comment by naikajah** [comment]
+1

**Comment by berndgoetz** [comment]
+1

**Comment by v6** [comment]
// , Perhaps some of you could chime in here if you have any more specific questions to ask about this: 

https://groups.google.com/forum/#!topic/vault-tool/c28dV82BJ3U

**Comment by Abmun** [comment]
Here is a post which has great comparison points-

https://www.techmanyu.com/microservices-secrets-management-comparison-of-vault-solutions/

**Comment by jefferai** [comment]
We have decided to remove that section, see https://github.com/hashicorp/vault/pull/8538
