### ISSUE TITLE
Issue creating a logical.Backend interface for plugin

### ISSUE THREAD

**Issue by bernielomax** [hashicorp/vault#3431]
I am trying to write my own vault plugin and I am getting the following error when trying to setup my own logical.Backend interface

```
/main.go:23: cannot convert Backend literal (type *Backend) to type logical.Backend:
        *Backend does not implement logical.Backend (wrong type for Logger method)
                have Logger() "github.com/mgutz/logxi/v1".Logger
                want Logger() "github.com/hashicorp/vault/vendor/github.com/mgutz/logxi/v1".Logger
```

The package import is:

```
import (
	"crypto/tls"
	"github.com/hashicorp/vault/logical"
	"github.com/hashicorp/vault/logical/plugin"
	"github.com/mgutz/logxi/v1"
)
```

The offending interface function declaration looks like:

```
func (b *Backend) Logger() log.Logger {
	return log.New("my-vault-plugin")
}
```

It seems that having `github.com/mgutz/logxi` under `vendor` is preventing me from creating the interface. Is it possible to you to exclude this package from vendor we can just use latest? Other people have recommended just deleting the vendor package but I would prefer not to mess with the official Hashicorp vault package.

**Comment by calvn** [comment]
You shouldn't need to implement the `logical.Backend` interface from scratch. You simply need to wrap your Backend implementation around `*framework.Backend`. See https://github.com/hashicorp/vault-plugin-auth-gcp/blob/master/plugin/backend.go#L21 for an example.

**Comment by bernielomax** [comment]
That was fast! Thanks @calvn I will check it out.

**Comment by calvn** [comment]
No problem, closing this then!
