### ISSUE TITLE
Cassandra DB plugin List Users errors for DC failures 

### ISSUE THREAD

**Issue by navinanandaraj** [hashicorp/vault#3438]
List Users in Cassandra appears to use Quorum and ignores the consistency level specified during connection creation. This causes the connection validation to fail when Quorum is not met. Replacing List Users with Select role,is_superuser from system_auth.roles will resolve the issue as the select query would use the consistency level specified during connection config.

**Comment by navinanandaraj** [comment]
Yes I agree and we reached out to our Cassandra vendor but apparently some DDL like statements intentionally use Quorum and it was their suggestion to use Select if we need to leverage consistency

**Comment by jefferai** [comment]
Anything you can forward our way? I don't know much about Cassandra so I'd want to be sure that `select role,is_superuser from system_auth.roles` is actually equivalent to a `list users`.

**Comment by navinanandaraj** [comment]
Actually I'm reading that it may not be the same Select across C* versions. I see that the query works on cqlsh 3.0 but need to see if it works on lower versions. Let me get back to you.

**Comment by navinanandaraj** [comment]
Thinking about it a little more, do we need to do a list users or a equivalent. Think the purpose here is to validate if the C* session is good and wouldn't any Select cql be good ?

**Comment by kk-thd** [comment]
If you are just doing connectivity test by using created credentials, it's worth to go route of generic CQL query test.. I can easily share CQL which can work in both versions, let me know please.

**Comment by navinanandaraj** [comment]
Jeff,
List Users appears to be deprecated in Cassandra 3.0 and higher. Its replaced by List Roles which does not work for 2.x. Both mandates to Quorum consistency level no matter what we specify.

https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlListUsers.html

We found that 'List ALL' appears to work across all versions. It provides the list of users and also appears to use the consistency level we specify. We are confirming with our vendor if List ALL will most definitely work across all versions

**Comment by navinanandaraj** [comment]
Just got a confirmation from our vendor that List ALL works on all versions and lists all the users.

**Comment by jefferai** [comment]
So what is the appropriate CQL?

**Comment by navinanandaraj** [comment]
List ALL

**Comment by jefferai** [comment]
The capitalization on that makes me think that's not the real CQL. Can you submit a PR?

**Comment by navinanandaraj** [comment]
Jeff,
The case doesn't matter. List all, list all, LIST ALL they all work. I'll submit a PR

**Comment by navinanandaraj** [comment]
Jeff,
Created below PR
https://github.com/hashicorp/vault/pull/3469

**Comment by jefferai** [comment]
Closed by #3469

**Comment by navinanandaraj** [comment]
Thanks Jeff. Do we have an ETA for 0.8.4 ?

**Comment by jefferai** [comment]
Early November.
