### ISSUE TITLE
Lease duration renewal and overflow

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#345]
This may just be a display bug, but there are currently two things we've discussed that are concerning regarding lease renewals.

1. **A lease renewal (with or without an increment) is cumulative instead of reset on each call.**

    When renewing the least on an auth, each call to renew seems to increment the lease duration by its interval. For example, if the lease is 24 and I make an API call to renew the lease 3x, the new "lease expiration" is 72h. This seems like a bug or at least a very unexpected API. @mitchellh and I discussed this today and he has some ideas I think he will share in a comment. 

    Instead, I think the expected API is that on renewal, the "clock starts fresh". So on a auth token renewal, I would always expected the lease duration to be less than or equal to the initial lease duration provided no increment was given. This means, in the example above, the lease duration should never exceed 24h. I think this is what a user would expect as an API.

2. **Lease duration overflow.**

    Given the above and my limited testing, I think it is possible to overflow the integer storing the lease duration (possible relating to or causing https://github.com/hashicorp/vault/issues/328). This could be a fairly serious bug. We recommend that users renew on `lease_duration/2`. Combined with the first issue above, this means that you could, over time, overflow the integer storing that time.

/cc @armon

**Comment by armon** [comment]
Fixed by #354
