### ISSUE TITLE
Vault mount using curl

### ISSUE THREAD

**Issue by Lechucico** [hashicorp/vault#3450]
Hello, 

I would like to know how to execute the following sentence via curl `vault mount database`.

I did not see any example on how to mount database generic storage using curl.

**Comment by chrishoffman** [comment]
Please use the mailing list (https://groups.google.com/forum/#!forum/vault-tool) for general questions. We try to keep the issue tracker reserved for bug reports and pull requests.

See the API documentation for more information on mounting backends.  Setting the type to "database" and the URL path suffix to "database" will work to mount the database.
https://www.vaultproject.io/api/system/mounts.html#sample-request-1
