### ISSUE TITLE
incorrect documentation for Generate Data Key

### ISSUE THREAD

**Issue by vineet-garg** [hashicorp/vault#3454]
**Environment:**

* Vault Version:
* Operating System/Architecture:

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

**Actual Behavior:**
https://www.vaultproject.io/api/secret/transit/index.html#generate-data-key
The description of "name" field is incorrect. perhaps it has been copy pasted from
  https://www.vaultproject.io/api/secret/transit/index.html#rewrap-data

**Steps to Reproduce:**
https://www.vaultproject.io/api/secret/transit/index.html#generate-data-key

**Important Factoids:**

**References:**

**Comment by vineet-garg** [comment]
In the example 
{
  "data": {
    "plaintext": "dGhlIHF1aWNrIGJyb3duIGZveAo=",
    "ciphertext": "vault:v1:abcdefgh"
  }
}
It is not clear which key was used to encrypt the plaintext key? How was that key specified?

**Comment by vineet-garg** [comment]
after trying out the example, I understand that the "name" filed is used to identify which key to be used for encrypting data key. 
Description of "name" filed should be corrected as I mentioned in "actual behavior" section

**Comment by jefferai** [comment]
Thanks!
