### ISSUE TITLE
/sys/auth response documentation?

### ISSUE THREAD

**Issue by rgl** [hashicorp/vault#3456]
I'm issuing this http request:

```bash
wget -d -qO- --header "X-Vault-Token: $(cat ~/.vault-token)" $VAULT_ADDR/v1/sys/auth | jq
```

And it returns:

```json
{
  "token/": {
    "accessor": "auth_token_3cd81336",
    "config": {
      "default_lease_ttl": 0,
      "max_lease_ttl": 0
    },
    "description": "token based credentials",
    "local": false,
    "type": "token"
  },
  "request_id": "a45f04b5-5d41-f2c3-db28-36a818c7e351",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": {
    "token/": {
      "accessor": "auth_token_3cd81336",
      "config": {
        "default_lease_ttl": 0,
        "max_lease_ttl": 0
      },
      "description": "token based credentials",
      "local": false,
      "type": "token"
    }
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}
```

Of those what are the ones that are really a auth backend? the ones that are at the response object root and end with a forward-slash (`token/`)?

The [List Auth Backends documentation](https://www.vaultproject.io/api/system/auth.html) does not really explain what those field are. Can you explain them? For example, its seems, for some reason, it returns duplicated information, as the object at the `token/` and `data.token/` properties are the same. Also, what are the other properties (`request_id`, `lease_id`, `renewable`. `lease_duration`, `wrap_info`, `warnings` and `auth`)? Is there a swagger with all of the api definition/documentation?

BTW, is it called a `Auth Backend` (as show by the documentation) or a `Auth Provider` (as show by `vault -h`)?

**Comment by joelthompson** [comment]
Hey @rgl -- you want what's inside the `data` key. The same data are injected into the top-level as well, but looking inside `data` is probably easiest.

**Comment by jefferai** [comment]
To add to what @joelthompson said, for legacy reasons for many of the `sys/` calls data appears at both the top level and in the `data` member. Generally it's easiest to just look inside the data member.
