### ISSUE TITLE
Missing documentation for root-protected

### ISSUE THREAD

**Issue by Lechucico** [hashicorp/vault#3458]
Hello,

I'm trying to figure out what paths on vault are `root-protected`. There is no place on documentation that shows what paths are `root-protected`.

The only way to interact with those `root-protected` paths is having a token with sudo permisions? A token with sudo permisions can perform anything on vault?

My scenario is the following:

Vault configures itself with `database backend` and some `policies`. MongoDB on install, has to retrieve a token from vault and configure his Mongo Secret Backend, but default tokens doesn't have permision to `mount backends`.

Thanks.

**Comment by jefferai** [comment]
Paths that require sudo permissions are generally documented in the documentation for that path. If you find somewhere that requires sudo permissions that isn't documented, please let us know (or send a PR!).

**Comment by v6** [comment]
// , Here's a list as of the paths in `sys` that need sudo as of 2018: 

## sys/step-down

https://www.vaultproject.io/api/system/step-down.html

> Requires a token with root policy or sudo capability on the path.

## sys/auth/*

Everything other than listing the auth methods requires `sudo`.

https://www.vaultproject.io/api/system/auth.html

> sudo required – This endpoint requires sudo capability in addition to any path-specific capabilities.

Strangely, the docs for `generate root` don't mention `sudo`: https://www.vaultproject.io/api/system/generate-root.html
Nor does /sys/key-status.

## sys/config-ui

https://www.vaultproject.io/api/system/config-ui.html

> sudo required – All UI endpoints require sudo capability in addition to any path-specific capabilities.


## sys/leases

https://www.vaultproject.io/api/system/leases.html#list-leases
https://www.vaultproject.io/api/system/leases.html#revoke-force
https://www.vaultproject.io/api/system/leases.html#revoke-prefix

> This endpoint requires 'sudo' capability.

## sys/plugins/catalog/:name

https://www.vaultproject.io/api/system/plugins-catalog.html#register-plugin
https://www.vaultproject.io/api/system/plugins-catalog.html#read-plugin
https://www.vaultproject.io/api/system/plugins-catalog.html#remove-plugin-from-catalog

> sudo required – This endpoint requires sudo capability in addition to any path-specific capabilities.

## sys/raw

https://www.vaultproject.io/api/system/raw.html#list-raw

> This endpoint requires 'sudo' capability.

## sys/replication/reindex

https://www.vaultproject.io/api/system/replication.html#reindex-replication
https://www.vaultproject.io/api/system/replication-performance.html#generate-performance-secondary-token
https://www.vaultproject.io/api/system/replication-dr.html#generate-dr-secondary-token

> This endpoint requires 'sudo' capability.

## sys/rotate

https://www.vaultproject.io/api/system/rotate.html

> This path requires sudo capability in addition to update.

## sys/seal

https://www.vaultproject.io/api/system/seal.html

> Requires a token with root policy or sudo capability on the path.

## auth/token

https://www.vaultproject.io/api/auth/token/index.html#list-accessors

> This requires sudo capability, and access to it should be tightly controlled as the accessors can be used to revoke very large numbers of tokens and their associated leases at once.

https://www.vaultproject.io/api/auth/token/index.html#period

> Requires a root/sudo token to use.

**Comment by v6** [comment]
An alternative way to discover this would be to set up a test. 

Create a policy that gives every permission except `sudo`, everywhere. 

Run operations against every single endpoint. 

See which ones give a `permission denied` error, and which just give a generic error.

**Comment by mtcolman** [comment]
This was a useful issue to be able to reference. I've found a few more, so adding a table of all those I've found here for the benefit of others.

| Path                                        | Webpage                                                                                                                                                            | Additional Comments                                           |
| ------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------- |
| /auth/token                                 | [https://www.vaultproject.io/api/auth/token/index.html](https://www.vaultproject.io/api/auth/token/index.html)                                                     |                                                               |
| /secret/pki                                 | [https://www.vaultproject.io/api-docs/secret/pki](https://www.vaultproject.io/api-docs/secret/pki)                                                                 | POST /pki/root/sign-self-issued<br>DELETE /pki/root           |
| /system/audit                               | [https://www.vaultproject.io/api-docs/system/audit](https://www.vaultproject.io/api-docs/system/audit)                                                             |                                                               |
| /system/auth                                | [https://www.vaultproject.io/api/system/auth.html](https://www.vaultproject.io/api/system/auth.html)                                                               | Everything other than listing the auth methods requires sudo. |
| /system/config-auditing                     | [https://www.vaultproject.io/api-docs/system/config-auditing](https://www.vaultproject.io/api-docs/system/config-auditing)                                         |                                                               |
| /system/config-cors                         | [https://www.vaultproject.io/api-docs/system/config-cors](https://www.vaultproject.io/api-docs/system/config-cors)                                                 |                                                               |
| /system/config-ui                           | [https://www.vaultproject.io/api/system/config-ui.html](https://www.vaultproject.io/api/system/config-ui.html)                                                     |                                                               |
| /system/leases                              | [https://www.vaultproject.io/api/system/leases.html](https://www.vaultproject.io/api/system/leases.html)                                                           | /sys/leases/revoke-force<br>/sys/leases/lookup                |
| /system/plugins-catalog                     | [https://www.vaultproject.io/api/system/plugins-catalog.html](https://www.vaultproject.io/api/system/plugins-catalog.html)                                         |                                                               |
| /system/raw                                 | [https://www.vaultproject.io/api/system/raw.html](https://www.vaultproject.io/api/system/raw.html)                                                                 |                                                               |
| /system/remount                             | [https://www.vaultproject.io/api-docs/system/remount](https://www.vaultproject.io/api-docs/system/remount)                                                         |                                                               |
| /system/rotate                              | [https://www.vaultproject.io/api/system/rotate.html](https://www.vaultproject.io/api/system/rotate.html)                                                           |                                                               |
| /system/seal                                | [https://www.vaultproject.io/api/system/seal.html](https://www.vaultproject.io/api/system/seal.html)                                                               |                                                               |
| /system/step-down                           | [https://www.vaultproject.io/api/system/step-down.html](https://www.vaultproject.io/api/system/step-down.html)                                                     |                                                               |
| /system/storage/raftautosnapshots           | [https://www.vaultproject.io/api-docs/system/storage/raftautosnapshots](https://www.vaultproject.io/api-docs/system/storage/raftautosnapshots)                     |                                                               |
| /system/replication/index                   | [https://www.vaultproject.io/api/system/replication.html](https://www.vaultproject.io/api/system/replication.html)                                                 |                                                               |
| /system/replication/replication-dr          | [https://www.vaultproject.io/api-docs/system/replication/replication-dr](https://www.vaultproject.io/api-docs/system/replication/replication-dr)                   | POST /sys/replication/dr/primary/secondary-token              |
| /system/replication/replication-performance | [https://www.vaultproject.io/api-docs/system/replication/replication-performance](https://www.vaultproject.io/api-docs/system/replication/replication-performance) | POST /sys/replication/performance/primary/secondary-token     |
