### ISSUE TITLE
https VAULT_ADDR seems to always force port 443

### ISSUE THREAD

**Issue by ctennis** [hashicorp/vault#3463]
**Environment:**

* Vault Version: 0.7.3
* Operating System/Architecture: Linux and Mac

**Expected Behavior:**
When setting VAULT_ADDR to "https://domain.com:8210" I'd expect it would still try to connect to port 8000 via https

**Actual Behavior:**
It forced port 443:

$ export VAULT_ADDR="http://vault.domain.com:8210"  
$ vault list secret/
Error reading secret/: Get http://vault.domain.com:8210/v1/secret?list=true: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

$ export VAULT_ADDR="https://vault.domain.com:8210"
$ vault list secret/

Error reading secret/: Get https://vault.domain.com/v1/secret?list=true: dial tcp [ipaddress]:443: i/o timeout

**Steps to Reproduce:**
Try to connect via https to a port other than 443

**Comment by jefferai** [comment]
Cannot reproduce. Are you sure that `export` is correct here for your shell?

**Comment by jefferai** [comment]
```
$ export VAULT_ADDR="https://127.0.0.1:1234"
$ vault read secret/foo
Error reading secret/foo: Get https://127.0.0.1:1234/v1/secret/foo: dial tcp 127.0.0.1:1234: getsockopt: connection refused
```

**Comment by ctennis** [comment]
you're right, it's behaving now after restarting things.  Not sure what happened there, sorry for the noise.

**Comment by jefferai** [comment]
No problem!
