### ISSUE TITLE
Can't unmount "database" 

### ISSUE THREAD

**Issue by mflococodev** [hashicorp/vault#3464]
Hello. I followed the documentation here https://www.vaultproject.io/docs/secrets/databases/index.html and was able to get this running with my AWS RDS mysql instance. I was even able to read from the database/creds/admin and got creds. I wanted to start from scratch and so I ran an unmount database command but I got this error:

vault unmount database
Unmount error: Error making API request.

URL: DELETE https://vault/v1/sys/mounts/database
Code: 400. Errors:

* failed to revoke 'database/creds/admin/9c11b632-d73c-1701-d9c3-9970c6aee4d5' (1 / 1): failed to revoke entry: resp:(*logical.Response)(nil) err:error during revoke: could not find role with name admin

**Environment:**
Vault v0.8.1

* Vault Version:
* Operating System/Architecture:

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

vault should've revoked all secrets and unmounted the backend

**Actual Behavior:**

Code: 400. Errors:

* failed to revoke 'database/creds/admin/9c11b632-d73c-1701-d9c3-9970c6aee4d5' (1 / 1): failed to revoke entry: resp:(*logical.Response)(nil) err:error during revoke: could not find role with name admin

**Steps to Reproduce:**

Follow directions here https://www.vaultproject.io/docs/secrets/databases/index.html
vault read database/creds/admin
vault delete database/roles/admin
vault unmount database

**Important Factoids:**

**References:**

**Comment by jefferai** [comment]
It looks like you deleted the 'admin' role prior to the unmount?

**Comment by mflococodev** [comment]
@jefferai Yes I did.

**Comment by jefferai** [comment]
As a result, when it's trying to revoke the user(s) you created, it is trying to look up the role information to use in the revocation commands, and the role no longer exists. Vault will not, by itself, forget about leases -- that's part of its contract when managing credential lifetime.

If you want to force Vault to ignore these, you can revoke-force (https://www.vaultproject.io/api/system/leases.html#revoke-force). Then it will unmount.
