### ISSUE TITLE
Make LDAP paths more permissive

### ISSUE THREAD

**Issue by armon** [hashicorp/vault#347]
Currently the regex validation for LDAP paths is too aggressive and does not permit usernames or groups containing hyphens or spaces. We should broaden the validation to include all valid LDAP characters.

**Comment by bluecmd** [comment]
You want me to do a PR for this?
As I see it these are the things to do with regards to supporting RFC 4514
1) Update the regexp to support supported characters in both group and login
2) Re-write the DN parsing in backend.go to handle all supported DNs

Does the storage backend support arbitrary strings? I see that the groupdn mapping is stored in "req.Storage" prefixed with "group/", hence the question.

**Comment by armon** [comment]
@bluecmd If you can submit a PR that would be great otherwise we will attempt to triage as time allows

**Comment by bluecmd** [comment]
Opened a PR with go-ldap for DN parsing that will help this effort:
https://github.com/go-ldap/ldap/pull/19

**Comment by bluecmd** [comment]
PR https://github.com/hashicorp/vault/pull/367 is ready for review at your convenience.

**Comment by bluecmd** [comment]
Ping @armon

**Comment by armon** [comment]
Fixed by #367
