### ISSUE TITLE
MSSQL database documentation incorrect

### ISSUE THREAD

**Issue by sixfeetover** [hashicorp/vault#3470]
**Environment:**
Vault v0.8.3 ('6b29fb2b7f70ed538ee2b3c057335d706b6d4e36')
macOS 10.13

**Vault Config File:**
Vault is running in dev mode on my machine for this test, `vault server -dev`.

**Expected Behavior:**
I am attempting to create an mssql database connection using the format for the `connection_url` as described in [the documentation](https://www.vaultproject.io/docs/secrets/databases/mssql.html#quick-start). Expected behavior is that the mssql config is successfully created.

**Actual Behavior:**

The connection string is incorrectly parsed (here, interpreting the password as a port). 

```
Error writing data to database/config/mssql: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/mssql/config/test
Code: 400. Errors:

* error creating database object: error verifying connection: Invalid tcp port 'password': strconv.ParseUint: parsing "password": invalid syntax
```

**Steps to Reproduce:**

Running the commands below yield the error above:

```
$ vault mount database
$ vault write database/config/mssql \
    plugin_name=mssql-database-plugin \
    connection_url='sqlserver://sa:password@localhost:1433' \
    allowed_roles="*"
```

I am able to work around this by instead passing the connection string syntax specified in the [deprecated mssql documentation](https://www.vaultproject.io/docs/secrets/mssql/index.html), like so:

```
$ vault write database/config/mssql \
    plugin_name=mssql-database-plugin \
    connection_url='server=localhost;port=1433;user id=sa;password=Password!;app name=vault;' \
    allowed_roles="*"
```

This is surprising for a few reasons, namely:

* It differs from the provided documentation, and 
* It works by passing a connection _string_ in the connection _url_ parameter.

It's unclear if it's the documentation or the code that is incorrect, or if it some kind of user error on my part.

**Comment by sixfeetover** [comment]
I should say as well that I do not have [`MSSQL_URL`](https://github.com/hashicorp/vault/blob/master/plugins/database/mssql/mssql_test.go#L24) defined in my environment.

**Comment by chrishoffman** [comment]
Thanks for the report.  When we migrated the mssql backend to the shared database backend the documentation was not correctly migrated.

**Comment by Ardun21** [comment]
I know this is an old issue, but the [MSSQL documentation](https://www.vaultproject.io/docs/secrets/databases/mssql.html) for the shared database backend still states that a URL string should be passed in when configuring the MSSQL plugin. However, I get a "connection url cannot be parsed" error on Vault 1.0.2 with this command:

```
vault write database/config/my-mssql-db \
    plugin_name=mssql-database-plugin \
    connection_url='sqlserver://{{username}}:{{password}}@server-name.test:1234' \
    allowed_roles="my-role" \
    username="hashicorp_user" \
    password="XXXXXXXX"
Error writing to: database/config/my-mssql-db.
URL: /v1/database/config/my-mssql-db
Code: 400
Errors:
  error creating database object: unable to parse connection url
```

Changing the format to a connection string resolves the problem. It seems to me that either the MSSQL section of the shared database backend documentation should be updated, or the parsing logic needs to be updated to accept the URL-formatted argument.
