### ISSUE TITLE
policy doesn't apply to default values

### ISSUE THREAD

**Issue by stampycode** [hashicorp/vault#3475]
It doesn't appear to be possible to override the default parameters of an endpoint by policy, nor apply the policy to default parameters.
Is it possible to create a token with permission to only create tokens with *fewer* than the current token's policies?

** Reproduction Steps: **

If my token has roles:

    ["AAA", "BBB", "CCC"]

And it has a policy:

    path "/auth/token/create" {
      capabilities = ["create", "update"],
      allowed_parameters = { "policies" = [] },
      denied_parameters = { "policies" = ["CC*"] }
    }

Then hit the `/auth/token/create` endpoint with no parameters

** Actual Result: **

A new token that has the "CCC" policy.

** Expected Result: **

    {"errors":["permission denied"]}

** Vault Version: **

Version: 0.8.3

**Comment by stampycode** [comment]
Guess the most logical way to enforce this would be to have a `required_parameters` policy option - where a request _must_ specify the named parameters, forcing them to be subject to the policy.

**Comment by jefferai** [comment]
It is not possible to override the default parameters of an endpoint by policy. It is also not possible to apply policies to default parameters. `allowed_parameters` and `denied_parameters` apply to request data only.
