### ISSUE TITLE
Document recommended Go client integration

### ISSUE THREAD

**Issue by thedirtycolumbia** [hashicorp/vault#348]
I have been searching for documentation for the best way to use Vault in a Go project.

Currently I am doing this:

    import vaultapi "github.com/hashicorp/vault/api"

    client, err := vaultapi.NewClient(vaultapi.DefaultConfig())

    client.SetToken(token)
    c := client.Logical()

    _, err = c.Write("path/to/secret",
        map[string]interface{}{
            "cert":  cert,
            "lease": lease,
        })

Am I on the right path? Is there a more elegant or idiomatic way to be using Vault in Go?

**Comment by armon** [comment]
@thedirtycolumbia This LGTM!

**Comment by sethvargo** [comment]
@thedirtycolumbia here is how [Consul Template does it](https://github.com/hashicorp/consul-template/blob/master/dependency/vault_secret.go#L41-L96) which might help :smile:

**Comment by thedirtycolumbia** [comment]
@armon @sethvargo thanks for the feedback!
