### ISSUE TITLE
vault is prompting for a client certificate when it's not configured to do so

### ISSUE THREAD

**Issue by mflococodev** [hashicorp/vault#3492]
Connections to vault work from the Vault.exe CLI, and from Powershell using Invoke-WebRequest (once TLS 1.2 is enabled). Curl also works however, connections do not work from WinHttp.WinHttpRequest or Msxml2.ServerXMLHTTP (via OLE/COM) despite explicitly activating TLS 1.2 and setting every "ignore error" setting available. In every case, the error "A certificate is required to complete client authentication" is returned when trying to send the POST data.

Unfortunately, Powershell, Vault.exe and curl are not available in the environment (running in a SQL Server database stored procedure) where we need to be able to store secrets into Vault. (OLE/COM objects are available)

Also, when testing by loading the same url via Internet Explorer and Chrome, each browser automatically opens a "Select a certificate" window so you can provide a client identification certificate, which is essentially the same result received from the OLE/COM objects.

vault requesting a client cert also presents itself when trying to access my vault server from a browser (chrome, i.e. etc) - https://vaultserver

From what I've read https://www.vaultproject.io/docs/configuration/listener/tcp.html#tls_require_and_verify_client_cert this behavior should be disabled by default but doesn't appear to be. I also tried explicitly adding the 

tls_require_and_verify_client_cert = false
tls_require_and_verify_client_cert = "false"
tls_require_and_verify_client_cert = 0

To the vault server config and restarting but without success. Appreciate your help.

**Environment:**

* Vault Version: Vault v0.8.3 ('6b29fb2b7f70ed538ee2b3c057335d706b6d4e36')
* Operating System/Architecture: 

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

**Vault Config File:**
backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
}

listener "tcp" {
  address = "0.0.0.0:443"
  tls_cert_file = "/etc/vault/vault-cert.pem"
  tls_key_file = "/etc/vault/vault-cert.key"
  tls_require_and_verify_client_cert = 0
}

**Startup Log Output:**

**Expected Behavior:**
Unless explicitly configured to do so, vault should not prompt for a client certificate. 

**Actual Behavior:**
over a browser like chrome or through other means like WinHttp.WinHttpRequest or Msxml2.ServerXMLHTTP (via OLE/COM) we are being prompted to present a client certificate

**Steps to Reproduce:**

**Important Factoids:**

**References:**

**Comment by chrishoffman** [comment]
I believe this behavior happens when the HTTP stack provides a certificate and Vault is just trying to verify it.  This is often hard to disable because it is enforced by corporate policy.  In the forthcoming release of Vault, an option was added to disable this behavior at the server level.

See #3373
