### ISSUE TITLE
not able to  read a path.. getting 403 errors

### ISSUE THREAD

**Issue by ssinhas** [hashicorp/vault#3494]
**Environment:**

* Vault Version: Vault v0.8.3 ('6b29fb2b7f70ed538ee2b3c057335d706b6d4e36')
* Operating System/Architecture: Mac

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

should get  the secret back

**Actual Behavior:**

didn't get database secret instead getting permission denied

**Steps to Reproduce:**

curl -kv http://127.0.0.1:8200/v1/secret/backend/database -H 'X-VAULT-TOKEN:996d0a7e-2dfa-27a1-ca73-dc98a97b4902'

token is associated with policy kubernetes-vault

and policy has read access 
name 	kubernetes-vault
rules	path "auth/approle/role/ms-templates/secret-id" {
  capabilities = ["update"]
}

path "secret/backend/* " {
  capabilities = ["read"]
}

path "intermediate-ca/issue/kubernetes-vault" {
  capabilities = ["update"]
}

path "auth/token/roles/kubernetes-vault" {
  capabilities = ["read"]
}

path "auth/approle/role/sample-app/secret-id" {
  capabilities = ["update"]
}

**Important Factoids:**

**References:**

**Comment by ssinhas** [comment]
more info on token 

token: 996d0a7e-2dfa-27a1-ca73-dc98a97b4902
token_duration: 2763629
token_policies: [default kubernetes-vault]

**Comment by jefferai** [comment]
http://127.0.0.1:8200/v1/secret/backend/database isn't a path that should be associated with any credential fetching. In addition, in your policy, the first path should not start with `rules`.

**Comment by ssinhas** [comment]
"rules"  is just the output from vault read sys/policy/policy-name

actual url
 curl -kv http://127.0.0.1:8200/v1/secret/backend/database -H 'X-VAULT-TOKEN:token'

it works if I login as a root and generate a token. But  if I use token which is associated with policy kubernetes-vault,  it doesn't work.  I get 403 permission error.

But policy clearly say .. 
path "secret/backend/* " {
capabilities = ["read"]
}

what am I missing?

**Comment by chrishoffman** [comment]
It looks like there is a space in your path definition for `secret/backend/*` and the star glob is only supported as the last character.

**Comment by ssinhas** [comment]
yup  ..  you are right... That fixed the problem... 

sorry  to ask  another question here.. (I am very  new to vault)..
I am trying to  create a approle with  policy attached..

vault write auth/approle/role/testrole secret_id_ttl=10m token_num_uses=10 token_ttl=20m token_max_ttl=30m secret_id_num_uses=40 policy=kubernetes-vault
but policy comes as default

bind_secret_id    	true
bound_cidr_list
period            	0
policies          	[default]
secret_id_num_uses	40
secret_id_ttl     	600
token_max_ttl     	1800
token_num_uses    	10
token_ttl         	1200


I can always post  and set  token.. Is there any  way  i can create approlle and attach a policy in one command..

**Comment by chrishoffman** [comment]
It looks like you are using the `policy` parameter instead of `policies`.  
https://www.vaultproject.io/api/auth/approle/index.html#policies

Please use the Vault mailing list (https://groups.google.com/forum/#!forum/vault-tool) for questions; we try to keep the issue tracker reserved for bugs/issues/feature requests/PRs.

There are a lot of knowledgeable people on the list that have tackled this problem in various ways in different setups/environments and posting there will get more eyes on the question.
