### ISSUE TITLE
Cannot build from source with Golang 1.9.2

### ISSUE THREAD

**Issue by fmunteanu** [hashicorp/vault#3498]
Hi,

I cannot compile from source on a CentOS 7.4 4.9.49-moby x86_64 GNU/Linux server with Golang 1.9.2 installed:
```
$ go version
go version go1.9.2 linux/amd64

$ export GOPATH=/home/floren/rpm/BUILD/vault-0.8.3
$ pushd src/github.com/hashicorp/vault
$ /usr/bin/make -j2 bootstrap
$ /usr/bin/make -j2
cp: cannot create regular file '.git/hooks/': No such file or directory
make: *** [prep] Error 1
```
I'm packaging vault as rpm, from your documentation I see I can run either `make` or `make dev`. I looked at the `Makefile` to see what options you have in there and the default is `dev`.

I can compile fine the `mysql-database-plugin`:
```
$ export GOPATH=/home/floren/rpm/BUILD/vault-0.8.3
$ pushd src/github.com/hashicorp/vault
$ /usr/bin/make -j2 bootstrap
$ /usr/bin/make -j2 mysql-database-plugin
$ popd

$ ls -lah /home/floren/rpm/BUILD/vault-0.8.3/bin/mysql-database-plugin
-rwxr-xr-x 1 floren floren 14M Oct 27 16:37 /home/floren/rpm/BUILD/vault-0.8.3/bin/mysql-database-plugin
```

**Comment by jefferai** [comment]
You need permissions to write to the `.git/hooks` directory from the repository checkout.

**Comment by fmunteanu** [comment]
@jefferai where is created that `.git`? I do have all permissions, is an rpm build.

**Comment by jefferai** [comment]
You don't need it anymore, see my commit above.

**Comment by fmunteanu** [comment]
@jefferai I applied the patch, now i get a different error:
```
/usr/bin/make -j2
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by fmunteanu** [comment]
As a workaround, I compiled successfully all binaries with:
```
/usr/bin/make -j2 bootstrap
gox -osarch="$(go env GOOS)/$(go env GOARCH)" -output=bin/vault .
/usr/bin/make -j2 cassandra-database-plugin
/usr/bin/make -j2 mysql-database-plugin
/usr/bin/make -j2 mongodb-database-plugin
/usr/bin/make -j2 postgresql-database-plugin
```

**Comment by fmunteanu** [comment]
@jefferai let me know if is satisfactory the naming convention for the database plugins. In a RHEL environment, you will notice this structure: `[name]-plugin-[plugin name]`:
```
$ sudo yum --enablerepo=axivo -q list vault*
Available Packages
vault.x86_64                             0.8.3-1.el7           axivo
vault-plugin-cassandra.x86_64            0.8.3-1.el7           axivo
vault-plugin-mongodb.x86_64              0.8.3-1.el7           axivo
vault-plugin-mysql.x86_64                0.8.3-1.el7           axivo
vault-plugin-postgresql.x86_64           0.8.3-1.el7           axivo
```

**Comment by jefferai** [comment]
@fmunteanu for the plugins, because some services can exist in multiple capacities (e.g. aws), it's better to put the type:
vault-plugin-database-cassandra
vault-plugin-database-mongodb
etc.

That will also have them match plugin names sourced from outside the Vault repo, e.g. vault-plugin-database-oracle.

**Comment by fmunteanu** [comment]
@jefferai sure thing, can you please give me an example what other plugin types beside `database` we could provide? IMO, the `plugin name (i.e. cassandra)` should "signal" the category. When you have a chance, please help me understand better your logic related to multiple capacities. If we are dealing with AWS, I would expect a `vault-plugin-aurora` plugin, which will let me know it is specifically designed for a DBCluster, not a DBInstance.

Regards,

Floren

**Comment by jefferai** [comment]
The plugin category signals the category:

vault-plugin-auth-X
vault-plugin-database-Y

That's the nomenclature we use for plugins; it'd be nice if the packages followed it.

Is there any reason you're building the database plugins separately? They're built into Vault for a reason, and having separate ones doesn't really help if they're the same code (e.g. without custom modifications).

**Comment by fmunteanu** [comment]
@jefferai you mean not including the binary with vault package? If you try to install `vault-plugin-database-mysql`, it will automatically install `vault` also. But not the other way around, there might be instances where you install `vault`, run it as a service and you don't need any plugins installed. For example:
```
$ sudo yum -q list vault*
Available Packages
vault.x86_64                                   0.8.3-1.el7         axivo
vault-plugin-database-cassandra.x86_64         0.8.3-1.el7         axivo
vault-plugin-database-mongodb.x86_64           0.8.3-1.el7         axivo
vault-plugin-database-mysql.x86_64             0.8.3-1.el7         axivo
vault-plugin-database-postgresql.x86_64        0.8.3-1.el7         axivo

$ sudo yum -q install vault-plugin-database-mysql

========================================================================
 Package                        Arch      Version        Repository
                                                                   Size
========================================================================
Installing:
 vault-plugin-database-mysql    x86_64    0.8.3-1.el7    axivo    2.7 M
Installing for dependencies:
 vault                          x86_64    0.8.3-1.el7    axivo     10 M

Transaction Summary
========================================================================
Install  1 Package (+1 Dependent package)

Is this ok [y/d/N]:
```
All tests passed successfully on a CentOS 7 x86_64 environment, can you please give it a spin and let me know if everything is OK?
```
$ sudo yum install -y vault
$ sudo systemctl enable vault
$ sudo systemctl start vault
$ sudo cat /var/log/vault/vault.log
Oct 27 22:46:35 ip-10-38-78-92 vault: ==> Vault server configuration:
Oct 27 22:46:35 ip-10-38-78-92 vault: Cgo: enabled
Oct 27 22:46:35 ip-10-38-78-92 vault: Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
Oct 27 22:46:35 ip-10-38-78-92 vault: Log Level: info
Oct 27 22:46:35 ip-10-38-78-92 vault: Mlock: supported: true, enabled: true
Oct 27 22:46:35 ip-10-38-78-92 vault: Storage: file
Oct 27 22:46:35 ip-10-38-78-92 vault: Version: Vault (version unknown)
Oct 27 22:46:35 ip-10-38-78-92 vault: ==> Vault server started! Log data will stream in below:
```
Why do I get a `version unknown`, because I don't have a tag defined for that? Also, I was expecting to see some initial storage data into /var/lib/vault, since I defined this path:
```
$ sudo cat /etc/vault.hcl
/*
 * Vault Configuration
 * See: https://vaultproject.io/docs/config/
 */

backend "file" {
	path = "/var/lib/vault"
}

listener "tcp" {
	tls_disable = 1
}
```

**Comment by jefferai** [comment]
> you mean not including the binary with vault package? If you try to install vault-plugin-database-mysql, it will automatically install vault also.

No, what I mean is -- those database plugins are included with Vault and they are *meant* to be included with Vault. They satisfy the plugin interface so that people can easily customize them if needed. But users expect them to be built-in, because they are included in normal installations of Vault (e.g. in our official binaries), and crucially, when they are included in a normal build of Vault they are both more performant and more secure, because the code doesn't run in a separate process.

You should not split them out for the base Vault package. The fact that they can be used as a plugin is an implementation detail. They are compiled into Vault normally for good reasons.

**Comment by fmunteanu** [comment]
@jefferai, thank you for letting me know, I had no idea they are already built-in into actual `vault` binary. I was looking at the `Makefile` and saw the build options, so I thought they are definitely optional binaries that I wanted to offer them to users. Let me know if I got this right? Or are yoy referring to still build them and include them side by side with the `vault` binary into main package?

**Comment by jefferai** [comment]
They are already built in. The only plugin not built in is the Oracle database plugin. All of the rest are included, as of now.

**Comment by fmunteanu** [comment]
@jefferai I removed the plugins. I have a question about the API: https://github.com/hashicorp/vault/blob/master/api/SPEC.md Is this also part of the `vault` binary? If I have a Vault server running, I want a client installed on other servers to communicate and get the secrets. I would like to build that client separately, so I don't install the hole server package.

**Comment by jefferai** [comment]
We do not separate out client/server. It's a single binary.
