### ISSUE TITLE
Docker couldn't start up Vault Service when running testing on Semaphoreci

### ISSUE THREAD

**Issue by han2015** [hashicorp/vault#3503]
ENV: 
  ` docker+ vault + Semaphoreci`
Error: 
`  Get http://127.0.0.1:8200/v1/sys/mounts: dial tcp 127.0.0.1:8200: getsockopt: connection refused
`
Description:
   

- I can go well and pass testing on local. but I checked the docker containers by `docker ps` on CI platform, and didn't find vault container.
-    docker could download and install vault image, but couldn't start up the Vault service whether use docker command or docker-compose config. 

`docker run --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=mytoken' -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200' -p 8200:8200 -d vault`

thanks.

**Comment by jefferai** [comment]
Please file at https://github.com/hashicorp/docker-vault for Docker issues. Thanks!
