### ISSUE TITLE
Ability to lookup secrets from plugin configs, or other vault locations.  

### ISSUE THREAD

**Issue by tfhartmann** [hashicorp/vault#3514]
**Feature Request:**

It would be useful to be able reference a secret in the KV  (or other source) from say, a plugin config.  For example when configuring the database backend, when defining the connection string,  if you  could reference a secret stored in the KV, rather then having to write it out?  For example, in the example config in the [Quick Start](https://www.vaultproject.io/docs/secrets/databases/index.html) to be able to set the connection url  to something like `connection_url=“root:{{/secret/mysqlpw}}@tcp(127.0.0.1:3306)/“`

**Comment by stevenscg** [comment]
This sounds like an interesting enhancement to the workflow.

I would think that we are like most teams in that we have to reference the vault user's database password from an external secret store during changes to the mounts or roles. 

I also think this might encourage more policy as code adoption (roles as code, too) as the secrets can be loaded by a privileged admin one time or in advance.

**Comment by jefferai** [comment]
Thanks for the suggestion!

Unfortunately, this is very specifically not allowed by our model. Mounts are purposefully in silos to ensure that they can be properly ACL'd. Adding cross-mount references brings up a host of very difficult questions around when those references should and shouldn't be valid based on privileges of the current user, and there are a number of technical questions in addition to the security ones (including making writing backends significantly more complex for all authors).

There are ways to do this from clients; most users write simple scripts as needed.

**Comment by tfhartmann** [comment]
Thanks @jefferai !
