### ISSUE TITLE
Can I use the HTTP API to write and read secrets?

### ISSUE THREAD

**Issue by nopara73** [hashicorp/vault#352]
Hey guys!
  
You state in the documentation that every aspect of the vault can be controlled by the HTTP API.  
  
I am new to web development, so there might be a chance that I misunderstand something.  
I cannot find in the documentation how could I do it, or I can only do it with the CLI?

**Comment by sethvargo** [comment]
Hi @nopara73 

You can do anything with the HTTP API. In fact, the CLI usually calls out using the HTTP API :smile: (for most things). You can have a look at the `api` package in the vault repo or a community tool like vault-ruby to see how the API calls work.

**Comment by nopara73** [comment]
Thanks you.
