### ISSUE TITLE
Token does not actually renew

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#353]
Using Vault master (0239e3b1bd8620e28afafeb0ba582ad8b3769432), but I was able to reproduce on the released version of Vault as well (0.1.2).

1. Start a Vault server. I'm using dev mode, but I replicated with non-dev as well:

  ```shell
  $ vault server -dev
  ```

2. Generate a token with an expiration:

  ```shell
  $ vault token-create -policy=basic -lease=1m
  ```

  The "basic" policy contains:

  ```javascript
  # Allow renewal of leases for secrets
  path "sys/renew/" {
      policy = "write"
  }

  # Allow renewal of token leases
  path "auth/token/renew/" {
      policy = "write"
  }
  ```

3. Run with watch, renewing the token every half second:

  ```shell
  $ watch -e vault write auth/token/renew/cad27273-7bc4-498f-d544-cc03e777c92f increment=0 && sleep 0.5s
  ```

  This will fail after exactly one minute:

  ```text
  Error writing data to auth/token/renew/9ccce4c9-0956-d21d-947d-b0a246b3151d: Error making API request.

  URL: PUT http://127.0.0.1:8200/v1/auth/token/renew/9ccce4c9-0956-d21d-947d-b0a246b3151d
  Code: 400. Errors:

  * token not found
  ```

4. This can also be reproduced using `curl`:

  ```shell
  $ watch -e curl -X PUT --cookie "token=cad27273-7bc4-498f-d544-cc03e777c92f" http://127.0.0.1:8200/v1/auth/token/renew/cad27273-7bc4-498f-d544-cc03e777c92f
  ```

  This will eventually fail with:

  ```javasript
  {"errors":["permission denied"]}
  ```

  It is also worth noting that the lease_duration value becomes negative during renewal:

  ```javascript
  {"lease_id":"","renewable":false,"lease_duration":0,"data":null,"auth":{"client_token":"","policies":["basic"],"metada
ta":null,"lease_duration":-15,"renewable":true}}
  ```

  And then immediately after this response, we get the "permission denied" error.

/cc @armon @mitchellh

**Comment by armon** [comment]
Fixed by #354
