### ISSUE TITLE
Cryptographic Implementations 

### ISSUE THREAD

**Issue by SCKelemen** [hashicorp/vault#3542]
I am evaluating the Vault for Key Management, but I am constrained to FIPS 140-2 validated implementations of cryptography, which are not present in Go's standard libraries. I am, however, aware of a branch of Go that uses Boring Crypto's implementation of cryptographic algorithms. Is Vault built against the Boring Crypto branch of Go, or does Vault use the standard Crypto library, or alternatively another set of implementations all together?

See: https://github.com/golang/go/issues/21734

According to the code, it appears it's just using the standard library. Can anyone confirm? 
https://github.com/hashicorp/vault/blob/master/vault/core.go

**Comment by jefferai** [comment]
The next release will have some information about FIPS capabilities within Vault.
