### ISSUE TITLE
x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by Lechucico** [hashicorp/vault#3545]
I'm currently trying to use a self signed certificate for tls.

This is how I generate the certificate:

`openssl req -x509 -newkey rsa:4096 -keyout vault.key -out vault.pem -days 365 -nodes`

This errors appears when I try to `vault init`:

`Error initializing Vault: Put https://127.0.0.1:8200/v1/sys/init: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs`

**Comment by jefferai** [comment]
This isn't a Vault error. If you want to use 127.0.0.1 you need to modify your OpenSSL configuration to include that IP address as an IP SAN in your generated certificate.
