### ISSUE TITLE
DynamoDB storage example incorrect on website

### ISSUE THREAD

**Issue by ttacon** [hashicorp/vault#3547]
The DynamoDB storage example on the top of the configuration page is incorrect. It shows an example storage config of:

```hcl
storage "dynamodb" {
  ha_enabled = "true"
  region     = "us-west-2"
  table      = "vault-data"
}
```

However, if `ha_enabled = "true"` then `redirect_address` is required. This is documented near the bottom of the page, but the top level example should either include `redirect_address` or shouldn't include `ha_nabled`

**References:**

[Documentation page](https://www.vaultproject.io/docs/configuration/storage/dynamodb.html)
[Redirect documentation link](https://www.vaultproject.io/docs/configuration/storage/dynamodb.html#redirect_addr)

**Comment by jefferai** [comment]
Feel free to send a PR if you like, but often the redirect address is sent into Vault via an environment variable so that the same configuration can be used across nodes.
