### ISSUE TITLE
Information disclosure for unauthenticated users

### ISSUE THREAD

**Issue by 2knarf** [hashicorp/vault#3554]
Hello,

An unauthenticated user can get information such as unseal status and amount of keys total, and amount of keys needed to unseal a vault cluster.

Is it possible to not disclose this information?

# vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Unseal Nonce: 
Version: 0.8.3
Cluster Name: vault-cluster-8bedf7bf
Cluster ID: d78eb8a8-4ad2-6519-60aa-cc5c5987fd7c

High-Availability Enabled: false

**Comment by jefferai** [comment]
Hi there,

We do not currently have an ability to limit which information is shown at this endpoint, although we have some vague thoughts in that direction.

**Comment by catsby** [comment]
Hello - I'm going to close this issue/question for now.
