### ISSUE TITLE
Telemetry documentation issue

### ISSUE THREAD

**Issue by vineet-garg** [hashicorp/vault#3557]
**Environment:**

* Vault Version:
* Operating System/Architecture:

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**
https://www.vaultproject.io/docs/internals/telemetry.html
The information is not accurate
**Actual Behavior:**
https://www.vaultproject.io/docs/internals/telemetry.html

**Steps to Reproduce:**
https://www.vaultproject.io/docs/internals/telemetry.html

**Important Factoids:**

**References:**

**Comment by vineet-garg** [comment]
1. The metric "vault.audit.log_request_failure" is not mentioned in the list.
2. Description of  vault.token.create is incorrect
It says: This measures the number of token create operations
From the code it should be: Time taken to create a token
Code: https://github.com/hashicorp/vault/blob/07b97c57444de9ffb3e32ed6a929d86313519660/vault/token_store.go#L759

**Comment by jefferai** [comment]
Thanks for reporting this! Any chance you can send a PR?
