### ISSUE TITLE
Can't migrate to S3 backend from file

### ISSUE THREAD

**Issue by sebastiang** [hashicorp/vault#356]
I've just copied all files/folders from a file backend to an S3 backend, and when I start a vault instance pointing at the S3 bucket, I'm told

    2015/06/18 02:46:28 [INFO] core: seal configuration missing, not initialized

and my only option is to initialize the vault, not unseal it. I've tried copying the files while the server is sealed, and while the server is unsealed. Am I looking at a bug in the S3 backend or my copying technique? I've confirmed the files copied over in the same directory structure. (I just used `aws s3 cp --recursive`)

**Comment by sebastiang** [comment]
I can confirm there is a file `core/seal-config` in both places, with identical contents of the form

    {"Key":"core/seal-config","Value":"..................."}

Is there another piece of hidden state somewhere that needs to be migrated?

**Comment by armon** [comment]
@sebastiang Maybe something is funky with the S3 backend. It is just going to look for that "core/seal-config" value to generate that error message. Did you update the bucket / prefix correctly?

**Comment by sebastiang** [comment]
I've just been looking at the source code to grok the config possibilities. I don't see an option to update the prefix.

        bucket, ok := conf["bucket"]
	if !ok {
		return nil, fmt.Errorf("'bucket' must be set")
	}

	access_key, ok := conf["access_key"]
	if !ok {
		access_key = ""
	}
	secret_key, ok := conf["secret_key"]
	if !ok {
		secret_key = ""
	}
	region, ok := conf["region"]
	if !ok {
		region = os.Getenv("AWS_DEFAULT_REGION")
		if region == "" {
			region = "us-east-1"
		}
	}

**Comment by sebastiang** [comment]
(and i've confirmed that pointing it at an empty bucket and initializing the vault will result in a running vault with files in the expected places)

**Comment by armon** [comment]
@sebastiang I guess that backend does not support a prefix and uses the entire bucket. I didn't write the S3 backend, so not sure what assumptions it makes.

**Comment by armon** [comment]
@sebastiang I just realized it may be a permissions issue. I believe S3 returns "not found" on permission failure, which then looks like nothing is there to Vault

**Comment by sebastiang** [comment]
perhaps. But the same permissions allow vault to initialize a new vault.

On Thursday, June 18, 2015, Armon Dadgar <notifications@github.com> wrote:

> @sebastiang <https://github.com/sebastiang> I just realized it may be a
> permissions issue. I believe S3 returns "not found" on permission failure,
> which then looks like nothing is there to Vault
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/vault/issues/356#issuecomment-113315755>.
>


-- 
*Sebastian Good*

**Comment by jstremick** [comment]
Hi @sebastiang, I implemented the S3 backend and can confirm that it doesn't use a prefix. It assumes that Vault will be the only thing using the bucket and just places objects in its root. My thought was that Vault data shouldn't mingle with other data and it would be easier to grant permissions on a whole bucket than by object prefix. Sorry this is causing you trouble!

**Comment by sebastiang** [comment]
Thanks! It’s got to be a permissions issue, but so far so confused. I’m going to hack again on this in a few weeks.
On June 26, 2015 at 3:24:26 PM, James Stremick (notifications@github.com) wrote:

Hi @sebastiang, I implemented the S3 backend and can confirm that it doesn't use a prefix. It assumes that Vault will be the only thing using the bucket and just places objects in its root. My thought was that Vault data shouldn't mingle with other data and it would be easier to grant permissions on a whole bucket than by object prefix. Sorry this is causing you trouble!

**Comment by armon** [comment]
@sebastiang I'm going to close this as it doesn't appear to be a bug (at least not immediately). Please re-open if you discover a Vault bug!
