### ISSUE TITLE
Writing requires a value, but only in the CLI

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#357]
In the Cassandra backend, all arguments are optional when writing a role due to common/sane defaults. Given CRUD semantics, it is correct to write the role to configure it (since Vault treats PUT/POST the same, touching an endpoint with a role name would be the correct way to write it even if there were nothing to configure). However, the Vault CLI requires that at least one value be provided. This is only a limitation in the CLI, not a limitation in the API.

It would be nice if this limitation were removed.

**Comment by armon** [comment]
Yeah this has bit me a few times as well.
