### ISSUE TITLE
[feature requests] Force Cloud Storage to return a different signed url for the same path

### ISSUE THREAD

**Issue by AaronZhouQian** [hashicorp/vault#3574]
**Feature Request:**

When the content of a Cloud Storage file changed, getSignedURL still returns the same url when called with the same set of options. I wasn't able to find anything here https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/1.2.0/storage/file?method=getSignedUrl that shows how to force to return a different url.

**Comment by jefferai** [comment]
I believe you meant to file this against a different repository!
