### ISSUE TITLE
Support generating a new root token based on unseal keys

### ISSUE THREAD

**Issue by armon** [hashicorp/vault#359]
In the event of a disaster where the root keys are all lost or accidentally revoked, a quorum of the key holders should be able to generate a new root token. This provides a mechanism to at least get a single root token which can be used to restore the system into a good state.

**Comment by PainterAndHacker** [comment]
@armon, thanks for pointing this out to me on the Google Group. If no one is working on this currently, I might implement it. I haven't used Go before, but I think I'm going to be using Vault, and so I'd like to familiarize myself with the codebase and contribute to the project.

Do you think it would be worthwhile to have there be a stateful way to do this, like with unsealing? I would say that it's rare enough of a use case that it might be best to simply have an endpoint where the sufficient number of key shards are passed together to Vault in one request for a new root token.

**Comment by armon** [comment]
@PainterAndHacker I think it should be implemented like "rekey". Once the process is started it is stageful and should support cancelation.

**Comment by chris-martin** [comment]
I found myself looking for this feature within 15 minutes of using Vault, as I initialized the vault before reading about tokens, didn't notice the initial root token, and therefore didn't save the token anywhere. Not a big deal at this stage because I just wiped the database and started over, but annoying. Anyway, I wouldn't call this a rare use case :)

**Comment by jefferai** [comment]
@chris-martin Yeah, I think this will come eventually, it's just not super-high on the radar. There are some improvements going into 0.5 that will make this a safer operation for when it is eventually supported.

**Comment by DanyC97** [comment]
@jefferai when is .5 expected to land? asking roughly not hard date, thanks

**Comment by lylex** [comment]
So, may I ask is this issue resolved in 0.5.2?

**Comment by jefferai** [comment]
It was resolved in 0.5!   :-)
