### ISSUE TITLE
The vault command cannot talk to a -dev server

### ISSUE THREAD

**Issue by thiderman** [hashicorp/vault#3591]
**Environment:**
`Vault v0.9.0 ('09740f8525aa39a5e38cfd33dd27bbe0aeda255c')`

* Vault Version: 0.9.0
* Operating System/Architecture: Arch Linux, updated this week.

**Vault Config File:**
N/A

**Startup Log Output:**
```
~/s/g/hashicorp/vault/vault:master λ vault server -dev
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
        Redirect Address: http://127.0.0.1:8200
                 Storage: inmem
                 Version: Vault v0.9.0
             Version Sha: 09740f8525aa39a5e38cfd33dd27bbe0aeda255c

==> WARNING: Dev mode is enabled!

In this mode, Vault is completely in-memory and unsealed.
Vault is configured to only have a single unseal key. The root
token has already been authenticated with the CLI, so you can
immediately begin using the Vault CLI.

The only step you need to take is to set the following
environment variables:

    export VAULT_ADDR='http://127.0.0.1:8200'

The unseal key and root token are reproduced below in case you
want to seal/unseal the Vault or play with authentication.

Unseal Key: vc4CDqZ0QD2ml61hw3VL9IQgywy52lwwJwd6e8TOoZ0=
Root Token: 427764e3-2280-f53d-a351-c590a89f3fa7

==> Vault server started! Log data will stream in below:

2017/11/17 13:09:30.363273 [INFO ] core: security barrier not initialized
2017/11/17 13:09:30.363400 [INFO ] core: security barrier initialized: shares=1 threshold=1
2017/11/17 13:09:30.363532 [INFO ] core: post-unseal setup starting
2017/11/17 13:09:30.377675 [INFO ] core: loaded wrapping token key
2017/11/17 13:09:30.377688 [INFO ] core: successfully setup plugin catalog: plugin-directory=
2017/11/17 13:09:30.380238 [INFO ] core: successfully mounted backend: type=kv path=secret/
2017/11/17 13:09:30.380278 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/11/17 13:09:30.380504 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/11/17 13:09:30.380925 [INFO ] core: successfully mounted backend: type=identity path=identity/
2017/11/17 13:09:30.382454 [INFO ] expiration: restoring leases
2017/11/17 13:09:30.382795 [INFO ] rollback: starting rollback manager
2017/11/17 13:09:30.382925 [INFO ] identity: entities restored
2017/11/17 13:09:30.382939 [INFO ] identity: groups restored
2017/11/17 13:09:30.382951 [INFO ] core: post-unseal setup complete
2017/11/17 13:09:30.383122 [INFO ] core: root token generated
2017/11/17 13:09:30.383126 [INFO ] core: pre-seal teardown starting
2017/11/17 13:09:30.383128 [INFO ] core: cluster listeners not running
2017/11/17 13:09:30.383176 [INFO ] expiration: lease restore complete
2017/11/17 13:09:30.393235 [INFO ] rollback: stopping rollback manager
2017/11/17 13:09:30.393301 [INFO ] core: pre-seal teardown complete
2017/11/17 13:09:30.393411 [INFO ] core: vault is unsealed
2017/11/17 13:09:30.393429 [INFO ] core: post-unseal setup starting
2017/11/17 13:09:30.393491 [INFO ] core: loaded wrapping token key
2017/11/17 13:09:30.393494 [INFO ] core: successfully setup plugin catalog: plugin-directory=
2017/11/17 13:09:30.393692 [INFO ] core: successfully mounted backend: type=kv path=secret/
2017/11/17 13:09:30.393804 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/11/17 13:09:30.393982 [INFO ] core: successfully mounted backend: type=identity path=identity/
2017/11/17 13:09:30.393992 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/11/17 13:09:30.394653 [INFO ] expiration: restoring leases
2017/11/17 13:09:30.394711 [INFO ] rollback: starting rollback manager
2017/11/17 13:09:30.394850 [INFO ] identity: entities restored
2017/11/17 13:09:30.394861 [INFO ] identity: groups restored
2017/11/17 13:09:30.394875 [INFO ] core: post-unseal setup complete
2017/11/17 13:09:30.394895 [INFO ] expiration: lease restore complete
==> Vault shutdown triggered
2017/11/17 13:26:53.914542 [INFO ] core: pre-seal teardown starting
2017/11/17 13:26:53.914587 [INFO ] core: cluster listeners not running
2017/11/17 13:26:53.914616 [INFO ] rollback: stopping rollback manager
2017/11/17 13:26:53.914701 [INFO ] core: pre-seal teardown complete
2017/11/17 13:26:53.914729 [INFO ] core: vault is sealed
```

**Expected Behavior:**
The `vault` commands should work.

**Actual Behavior:**
```
~/s/g/hashicorp/vault/vault:master λ vault status
Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: http: server gave HTTP response to HTTPS client
```

It seems that when running the dev mode (which I've done both when compiled from source and from Docker's `latest`) the `vault` tool still requests with `https` and the `http` package gets angry.
It should be noted that a `curl` to the `http://` the commands work. I initially thought that maybe I could add `-dev` (as in `vault status -dev`) but to no avail. I also had a thought that maybe the command is not supposed to be used, but I couldn't find any note about anything like that in the docs.

**Steps to Reproduce:**
Any of the `vault` commands that would talk to the API has this behavior.

**Important Factoids:**
Er, I run Arch Linux, which has the tendency to be the culprit. However, I tested on a colleagues Macbook and the same thing happened.

I did a dig through the code and the latest commits but couldn't grok anything that could be relevant.

**References:**
N/A

**Comment by calvn** [comment]
Did you `export VAULT_ADDR='http://127.0.0.1:8200'`?

**Comment by thiderman** [comment]
I did not, and it works with it. Was this somewhere in the documentation, because I felt like I looked thorugh it quite well. 

I had a feeling this would be PEBCAK, hehe. 😅

**Comment by calvn** [comment]
It's printed out when Vault is starting up in dev mode:

```
In this mode, Vault is completely in-memory and unsealed.
Vault is configured to only have a single unseal key. The root
token has already been authenticated with the CLI, so you can
immediately begin using the Vault CLI.

The only step you need to take is to set the following
environment variables:

    export VAULT_ADDR='http://127.0.0.1:8200'
```

**Comment by thiderman** [comment]
Ugh, I feel bad now. I'll close this then.

Sorry for the noise!

**Comment by thiderman** [comment]
Hm, maybe there could be an extra message when this happens? We know which error this is, so if that one is gotten while running the `vault` command, maybe a hint about the export could be printed?

**Comment by rm-rf-etc** [comment]
The docs has the instructions in backwards order, `VAULT_ADDR` should be mentioned before run `vault status`.
> Verify the server is running by running the `vault status` command. This should succeed and exit with exit code 0. If you see an error about opening a connection, make sure you copied and executed the export `VAULT_ADDR`... command from above properly.

**Comment by mlushpenko** [comment]
Just in case you working with fish, doing `set VAULT_ADDR http://127.0.0.1:8200` doesn't work, but using shell interpreter works like `bass export VAULT_ADDR=http://127.0.0.1:8200`

**Comment by zsmuller** [comment]
I had a similiar issue/symptom, but the cause turned out to be a bad example/tutorial on the net.

I'm using Vault with Docker and got the following instructions somewhere:
1. Start the Vault server:
```
docker run -e SKIP_SETCAP=1 --name vault-dev -p 8200:8200 vault
```
2. Use the following commands for setting up a "vault" alias:
```
alias vault='docker exec -it vault-dev vault "$@"'
export VAULT_ADDR=http://127.0.0.1:8200
```
3. Issue Vault commands via the alias:
```
vault status
```

The problem is that simply exporting the VAULT_ADDR shell environment variable won't make it available to the vault command started via Docker. For that you'll have to specify the variable's name on the Docker commandline:
```
alias vault='docker exec -it -e VAULT_ADDR vault-dev vault "$@"'
```

This is pretty much version independent (it was a Docker problem and not a Vault problem), but for the sake of reproducibility, I used v1.1.2 (this was the "latest" Docker image at the time I tried it).

**Comment by john77eipe** [comment]
I have vault server running on my base Mac and vault client in a docker instance. 

But unable to access the server from the client that's in the docker instance.
 
`# ./vault status -address="https://127.0.0.1:8200"
Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: dial tcp 127.0.0.1:8200: connect: connection refused`

**Comment by allister-db** [comment]
> Just in case you working with fish, doing `set VAULT_ADDR http://127.0.0.1:8200` doesn't work, but using shell interpreter works like `bass export VAULT_ADDR=http://127.0.0.1:8200`

In Fish I had to use the `-x` flag to export the value to subprocesses: `set -x VAULT_ADDR http://127.0.0.1:8200`

**Comment by dewandemo** [comment]
I had the same issue when I suddenly switched from terminal to iTerm and did a `vault status`. Good reminder to `export VAULT_ADDR='http://127.0.0.1:8200'`
