### ISSUE TITLE
Vault and external multi-customer HSMs

### ISSUE THREAD

**Issue by bironran** [hashicorp/vault#3594]
**Feature Request:**

I would like to integrate Vault into our (multi-customer SaaS) product. However, we have customers that require that the root of the encryption resides in their own HSM, external to our product.
Our setup is such that we have a key and the customer has a key. We keep our key encrypted-at-rest using the customer key. In order to access customer data, we have to request that our key is decrypted using their key (an unwrap request to the customer external HSM). Once we obtain a plaintext version of the key, we can use it (encrypt data in transit, decrypt and encrypt data keys, etc).
When the customer rotates their external HSM key, we need to simply re-wrap our key (as opposed to our data keys).

I want to move to Vault /transit - our key to be a "named key", Vault to generate data keys for us and help us with the key rotation and re-wrapping data keys.
However, I can't see a way to integrate external HSM with that setup.
(note that I don't want "access protection", i.e. encrypt access details).

So the feature request: please add another level of encryption to /transit - allow providing an external key during /transit key generation and have the /transit key wrapped using that external key. Allow providing an external key during any kind of access to the /transit key so it can be unwrapped. Create an API to rotate the /transit key (not provision a new one - re-wrap all existing versions) - but maintain access to the previously warpped version until revoked (so concurrent access from nodes that have not seen the new external key yet could be maintained).

**Comment by bironran** [comment]
note - I can't use the trick listed here https://github.com/hashicorp/vault/issues/70 as my application is multi-customer. I can't have one customer control the vault master keys. Also, I don't want to restart Vault every time a customer rotates their keys.

**Comment by jefferai** [comment]
I'm not sure I totally understand the constraints you have, but AFAICT you can already do this by using derived keys. The context parameter could be the secret that is wrapped by each customer's key. So to get the correct context for the data, you first need to decrypt the context value against the customer HSM, then provide that for each encryption and decryption operation against a named key. If you are using the named key with multiple customers there is an non-zero chance of overlap, but with sufficiently random context it's very very close to zero, as the context value goes through HKDF to generate a new 256-bit key off of the base key, so it's essentially a (more complex) salted SHA256 function...the chance of collisions with different contexts is practically nonexistent.

**Comment by jefferai** [comment]
Closing, but do comment back if that doesn't address your needs!

**Comment by bironran** [comment]
@jefferai looks like that would work well. I didn't think about using context for that purpose. Thanks.

**Comment by jefferai** [comment]
Great!

Also note that in Vault 0.9, if you are an Enterprise customer, you can mount a transit backend with Seal Wrap turned on (https://www.vaultproject.io/docs/enterprise/sealwrap/index.html) if you are using AWS/GCP/HSM for auto-unseal -- this will ensure that, at rest, your transit keys are protected by whatever guarantees they offer, including FIPS KeyStorage support if that's available via your HSM vendor or cloud vendor.

**Comment by bironran** [comment]
thanks - but that's a different guarantee than the one I'm looking for. I want my customers to be able to control their keys, or at least some element that doesn't allow me to access the keys if they don't allow me to.

**Comment by jefferai** [comment]
We don't have anything like that currently, but it sounds like the context suggestion might work for you!
