### ISSUE TITLE
Add Azure AAD Auth Backend

### ISSUE THREAD

**Issue by marstr** [hashicorp/vault#3598]
**Feature Request:**
Add Azure AAD as an authentication backend. Ideally, this would be configurable and allow for a few separate authentication workflows (service principal, device, CLI token, etc) and allow for flexibility in AAD endpoints. Doing this work would not be an alternative to #2525.

**Comment by draggeta** [comment]
I would really love this. I understand that AWS and GCP seem to have more priority, but AAD for an auth backend would be great. So many organizations have Office 365 and as such have Azure AD available that it would make sense to create this auth backend.

**Comment by ephur** [comment]
A lot of people are building products spanning aws, gcp, and azure. This would allow more parity across people managing deployments across all the clouds. Would love this!

**Comment by gabinante** [comment]
It seems like an integration with Azure AD Managed Service Identity would give parity to AWS IAM role authentication:
https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/overview

**Comment by chrishoffman** [comment]
An Azure AD auth backend using Managed Service Identity is being added in Vault 0.10 which is in RC right now and will be released soon!

**Comment by nellurihanuman** [comment]
Hi,
I'm on vault v0.10.3 and when i try to enable secret engine azure "vault secrets enable azure", it is throwing an error as "unknown backend type : azure", I see in HashiCorp documentation says it supports azure secrets engine, am I missing something here, any suggestions would be appricated.

**Comment by kalafut** [comment]
Azure Secrets is different than Azure Auth. The secrets engine was introduced in v0.11.
