### ISSUE TITLE
Update Guide should indicate need to re-run setcap to enable mlock

### ISSUE THREAD

**Issue by rberlind** [hashicorp/vault#3605]
The Upgrade Guide at https://www.vaultproject.io/guides/upgrading/index.html should indicate that the command `sudo setcap cap_ipc_lock=+ep $(readlink -f $(which vault))` needs to be re-run against the new binary on platforms that support mlock.

This particular command is documented at https://www.vaultproject.io/docs/configuration/#disable_mlock.

What is not obvious is that the command targets the actual binary file itself rather than the path the binary lives at.  So, when you replace one version of the vault binary with a newer version, you need to re-run that command.

The command could be run from the command line.  Alternatively, if systemd is being used, the equivalent cold be entered in the systemd vault.service file as "ExecStartPre=/sbin/setcap 'cap_ipc_lock=+ep' /usr/local/bin/vault" (assuming that the vault binary is installed in /usr/local/bin).

**Comment by rberlind** [comment]
Hi @jefferai and @brianshumate: One more note on this.  I discovered on Friday that if you do add "ExecStartPre=/sbin/setcap 'cap_ipc_lock=+ep' /usr/local/bin/vault" to a systemd service file like vault.service, you also need to add "PermissionsStartOnly=true" or the attempt to invoke setcap will fail and prevent startup of the Vault service.  See https://github.com/hashicorp/vault-guides/blob/master/shared/vault/init/systemd/vault.service for example of this.

You'll need to add that to your addition.  Sorry for not reporting sooner.

**Comment by jen20** [comment]
I just opened #3704 before spotting this, but a better way with a modern systemd is to add the following to the systemd unit:

```
LimitMEMLOCK=infinity
```
