### ISSUE TITLE
Vault PKI Backend doc improvements

### ISSUE THREAD

**Issue by rberlind** [hashicorp/vault#3606]
The Vault PKI Backend doc at https://www.vaultproject.io/docs/secrets/pki/index.html needs the following 2 improvements:

1) The output for vault write pki/issue /<role> at https://www.vaultproject.io/docs/secrets/pki/index.html#generate-credentials shows output that is inconsistent with Vault's current default behavior in Vault 0.9.  In particular, the output does not include lease_id, lease_duration, or lease_renewable.  That is because since Vault 0.7.0 (https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#070-march-21th-2017), the Vault PKI Backend defaults to unleased certificates.  I suggest the output of the vault write pki/issue/example-dot-com command in  https://www.vaultproject.io/docs/secrets/pki/index.html#generate-credentials be updated to reflect that current behavior.

2) The doc should also provide an example of revoking a certificate generated with the PKI backend.  It is probably worth noting that `vault revoke <serial_number>` where \<serial_number\> is the serial_number returned by the `vault write pki/issue/<role>` command is NOT valid. While the results from doing that will look like it worked giving something like "Success! Revoked the secret with ID '2e:c4:bf:f1:26:2f:78:40:cb:ec:42:4a:9c:66:32:03:bf:79:29:d5', if it existed.", the certificate is not actually revoked. Instead, one has to use the v1/pki/revoke API endpoint, doing something like `curl --header "X-Vault-Token: ..." --request POST --data @serial.json https://localhost:8200/v1/pki/revoke` where serial.json looks like

```
{
  "serial_number": "2e:c4:bf:f1:26:2f:78:40:cb:ec:42:4a:9c:66:32:03:bf:79:29:d5"
}
```

Note that the doc does indicate that the serial_number can be used to revoke the certificate:  "If a certificate must truly be revoked, the normal Vault revocation function can be used; alternately a root token can be used to revoke the certificate using the certificate's serial number."  I had overlooked this before posting this originally. But an example would be better.

If we don't want to give an example of actually revoking the certificate in this doc, perhaps we can at least refer to https://www.vaultproject.io/api/secret/pki/index.html#revoke-certificate ?

**Comment by brianshumate** [comment]
I opened #3628 to update the pki/issue example output which should resolve this, as the current documentation already [calls out that the pki/revoke API should be used to revoke](https://www.vaultproject.io/docs/secrets/pki/index.html#token-lifetimes-and-revocation).

**Comment by rberlind** [comment]
Thanks @brianshumate

**Comment by rberlind** [comment]
Hi @brianshumate.  I have 1 more recommendation for this doc page.  I don't think it is good that the example for setting the URL configuration uses 127.0.0.1.  I think that would cause problems if PKI certificates generated by Vault were used on other servers as is likely to be the case.  I think we should be giving a fully qualified DNS name or IP address of the Vault server.  Of course, the doc does not use any specific DNS or IP for the Vault server on which the PKI quick start steps are being performed, so we would either have to use a fake IP or DNS (such as vault.rocks as on the API pages).  Or we could use 127.0.0.1 but add a note saying that users should actually use the actual public IP or DNS or the Vault server.

**Comment by brianshumate** [comment]
URL configuration examples set to RFC 2606 compliant `vault.example.com` instead of `127.0.0.1`.
