### ISSUE TITLE
Selectively hashing values in audit logs

### ISSUE THREAD

**Issue by carlskii** [hashicorp/vault#3607]
Hi,

Quick question, If I enable "log_raw="true" when I mount an audit backend, obviously it does not hash my sensitive data. Is there a way to selectively hash specific values only in the audit logs? 

Carl

**Comment by jefferai** [comment]
Not yet, but it's on the roadmap. It will likely appear in 0.9.1 or 0.9.2.

**Comment by carlskii** [comment]
OK thanks - in the short term is it possible to create a custom audit plugin?

**Comment by jefferai** [comment]
Not via the plugin system, but you can modify the source.

**Comment by jefferai** [comment]
In 0.9.6 (or 0.10) will be the capability to selectively not HMAC values, which should satisfy this.

**Comment by fernando-villalba** [comment]
And where is the documentation for this? 

All I can see is this: https://www.vaultproject.io/docs/commands/secrets/tune#audit-non-hmac-request-keys

But the lack of examples makes this very difficult to use.
