### ISSUE TITLE
Vault docs and CLI output for revoke command need expansion for serial_number of  PKI certs

### ISSUE THREAD

**Issue by rberlind** [hashicorp/vault#3608]
The Vault documentation about revoking secrets and the revoke command need to be expanded to include cases like the PKI backend for which revocation is done against a serial_number rather than against a lease_id.  Changes are also needed in the information provided by `vault revoke`.

If you create credentials with the PKI backend using `vault write pki/issue/<role>` since Vault 0.7, no lease_id is generated by default.  (See https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#070-march-21th-2017 and https://github.com/hashicorp/vault/issues/3606).  This means that the only way to revoke the certificate is by using a command like `vault revoke <serial_number>` using the \<serial_number\> returned buy the `vault write pki/issue/<role>` command.

But our documentation about `vault revoke` does not mention the possibility of revoking secrets based on serial_number.

I think we should update the following to do that:
1) https://www.vaultproject.io/docs/concepts/lease.html
2) The out put of `vault revoke` help to indicate that a serial_number should be used instead of a lease_id if revoking certificates generated by the PKI backend.

**Comment by jefferai** [comment]
The ability to revoke by serial number is a special function of the PKI backend that has nothing to do with Vault's lease system. The revoke command works only against the lease system, and `vault revoke` cannot be used to invoke the special endpoint in the PKI backend.

**Comment by rberlind** [comment]
Hi @jefferai.  I had thought I had been able to use `vault revoke` against a serial_number returned by `vault pki/issue/role`.  Given the fact that the Vault CLI tends to give responses like "Revoked the secret with ID xxxx, if it existed.", it was hard for me to know if the certificate was really invoked or not.  I tried again, this time first revoking with the CLI and then with the API.  Given the fact that the API revoke succeeded and showed the current time, I conclude that the CLI had not really invoked the certificate. Sorry for misunderstanding what had happened the first time.

Here is output from what I did which just extended the quick start in https://www.vaultproject.io/docs/secrets/pki/index.html#quick-start.

```
$ vault write pki/issue/example-dot-com common_name=blah.example.com
Key             	Value
---             	-----
certificate     	-----BEGIN CERTIFICATE-----
MIIDvzCCAqegAwIBAgIULsS/8SYveEDL7EJKnGYyA795KdUwDQYJKoZIhvcNAQEL

(certificates left out here)

-----END RSA PRIVATE KEY-----
private_key_type	rsa
serial_number   	2e:c4:bf:f1:26:2f:78:40:cb:ec:42:4a:9c:66:32:03:bf:79:29:d5

$ vault revoke 2e:c4:bf:f1:26:2f:78:40:cb:ec:42:4a:9c:66:32:03:bf:79:29:d5
Success! Revoked the secret with ID '2e:c4:bf:f1:26:2f:78:40:cb:ec:42:4a:9c:66:32:03:bf:79:29:d5', if it existed.

$ curl --header "X-Vault-Token: decfb81f-42c1-1a37-5489-faf81d461f79" --request POST --data @serial.json http://localhost:8200/v1/pki/revoke
{"request_id":"a26e182b-7106-7ae8-f293-900e93878a47","lease_id":"","renewable":false,"lease_duration":0,"data":{"revocation_time":1511795012,"revocation_time_rfc3339":"2017-11-27T15:03:32.676430149Z"},"wrap_info":null,"warnings":null,"auth":null}
```
