### ISSUE TITLE
token-create has a policy bug

### ISSUE THREAD

**Issue by shsjshentao** [hashicorp/vault#3611]
**Environment:**

* Vault Version: vault-0.9.0
* Operating System/Architecture: centos 7.2

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

token_policies  [a b c default]

**Actual Behavior:**

Key             Value
---             -----
token           7e01ac6e-374e-d299-79c8-4302d06f9009
token_accessor  83835af9-e646-0e93-c705-bffb3a414239
token_duration  768h0m0s
token_renewable true
token_policies  [a,b,c default]

**Steps to Reproduce:**

vault token-create -tls-skip-verify -policy=a,b,c

**Important Factoids:**

**References:**

**Comment by jefferai** [comment]
Can you explain what you think is a bug? This looks correct to me.

**Comment by shsjshentao** [comment]
Will it split to a, b and c three policies? And in fact it seems to one policy

**Comment by jefferai** [comment]
The token has four policies on it -- a, b, c, and default.

**Comment by shsjshentao** [comment]
I think the correct format is "token_policies [a b c default]" instead of "token_policies [a,b,c default]"

**Comment by jefferai** [comment]
Oh. It's two policies. I forgot, the token create command doesn't work the same as a simple write to the endpoint. If you want to use token-create with multiple policies, pass the policy flag multiple times.

**Comment by shsjshentao** [comment]
Ok, so the description is incorrect
https://www.vaultproject.io/docs/concepts/policies.html
At the bottom, vault token-create -policy=dev-readonly,logs
