### ISSUE TITLE
MongoDB Dynamic Backend Integration

### ISSUE THREAD

**Issue by camspilly** [hashicorp/vault#362]
Have MySQL, let's get some NoRel DB's in here

**Comment by sethvargo** [comment]
Hi @camspilly 

I think this is something we would gladly accept a Pull Request for. Thanks!

**Comment by camspilly** [comment]
No problem! At my workplace we use a variety of these tools, including Mongo, Zookeeper, Kafka, Rabbit, Redshift and MySQL, and we plan on adding Vault to that list.

**Comment by camspilly** [comment]
@sethvargo do you mean you would make a pull request, or an outside contributor would?

**Comment by sethvargo** [comment]
Hi @camspilly 

I mean we would likely rely on the community for this functionality since we do not use MongoDB internally :smile:

**Comment by camspilly** [comment]
Sweet.  Okay.  How can I start controvitong? Fork and then pull req?

**Comment by sethvargo** [comment]
@camspilly yup! :smile:

**Comment by mhurne** [comment]
No promises, but I'm taking a stab at implementing a secret backend for MongoDB. I think it's coming together nicely. I'll submit a pull request when I think it's ready for review.

**Comment by mhurne** [comment]
It works, but there's an unfortunate restriction in role assignment due to https://github.com/go-mgo/mgo/issues/236 and some boilerplate due to https://github.com/go-mgo/mgo/issues/84 that I'd like to clean up.

**Comment by mhurne** [comment]
I am still working on this... :-)

**Comment by mhurne** [comment]
I believe this issue can be closed now, unless this issue is about a storage backend rather than a secret backend.

**Comment by jefferai** [comment]
Yep!
