### ISSUE TITLE
mongodb secret backend hungs forever when DB is down

### ISSUE THREAD

**Issue by svenvarkel** [hashicorp/vault#3627]
**Environment:** 
AWS EC2 t2.micro machine

* Vault Version:
Vault v0.9.0 ('bdac1854478538052ba5b7ec9a9ec688d35a3335')
* Operating System/Architecture:
Ubuntu 16.04

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**
Vault's mongodb-database-plugin should timeout and close sockets towards a database that is down and reopen connections when the database is back online.
Ideally a secret backend should have a configurable timeout and vault should return a meaningful error code when a secret backend is down. 

Now when I'm writing this I came to an idea to try to configure mongodb socket timeout via mongodb connection string options connectTimeoutMS and socketTimeoutMS. Unfortunately the golang mongodb driver seems to lack support for these.

**Actual Behavior:**
Currently mongodb-database-plugin hungs forever when user tries to read from database/creds/A_DATABASE_THAT_IS_DOWN
Vault/the plugin would close sockets and start working again after it's restarted and unsealed. It would revoke expires leases from mongodb etc, everything will turn to normal. 

**Steps to Reproduce:**
Configure a mongodb secret backend.
Try to retrieve mongodb credentials with working database.
Shut down the mongodb database.
Try to retrieve the credentials with stopped database <- should not work.
Start mongodb database.
Try to retrieve mongodb credentials with working database <- should work

**Important Factoids:**

**References:**

**Comment by burdandrei** [comment]
i think we're affected by this too.
Mongodb plugin is just stucks
