### ISSUE TITLE
Vault server hanging due to too many opened socket

### ISSUE THREAD

**Issue by MrArtichaut** [hashicorp/vault#3633]
**Environment:**
Vault: 0.8.2
HA Backend: Zookeeper-3.4.6-2.x86_64
OS: CentOS 7

**Description**
We discovered that one of our Vault instance was hanging. It's wasn't responding to any request any more. This happened twice (in two different environments)

The Vault's logs was a flood of: 

`2017/11/30 16:06:06 http: Accept error: accept tcp4 0.0.0.0:8200: accept4: too many open files; retrying in 1s`

After investigation it seems that Vault reach the maximum number of opened sockets per process (1024). An `lsof` give us more than 1000 opened TCP sockets: 

`vault 21317 vault 1023u sock 0,7 0t0 71413016 protocol: TCP`

A `netstat` revealed about one hundred opened TCP connection with our monitoring tool (Nagios) in a `CLOSE_WAIT` state. Nagios is configured to request `/sys/health` periodically.

It looks to me that Vault isn't closing/releasing some TCP connection. I've seen this another issue (https://github.com/hashicorp/vault/issues/1793) with the same symptoms but it seems to be related to MySQL and was affecting a much older version of Vault.

Any ideas?

Thanks

**Comment by jefferai** [comment]
What port are the hung open sockets on? 8200 or 8201?

**Comment by MrArtichaut** [comment]
I don't have the data anymore but I'm pretty sure it was 8200.

**Comment by jefferai** [comment]
Unfortunately without the data there's not much I can do to help. This is not something we see generally and could easily have been caused by Nagios if it was failing to terminate its connections properly.

I do suggest increasing the open file descriptor limit; 1024 is unfortunately the default on older Ubuntu systems but is really quite small for a server process.

**Comment by jefferai** [comment]
I should say "on older Ubuntu systems and some other systems" -- forgot you're on CentOS. Same answer though :-)
