### ISSUE TITLE
PKI endpoint returns invalid JSON

### ISSUE THREAD

**Issue by ror6ax** [hashicorp/vault#3645]
I am experiencing problems with PKI backend. CSR is returning string containing double escaped newlines. Ansible json parser chokes on them. Is there a way to get CSR as a single string, not data.csr json structure?

**Comment by jefferai** [comment]
You can get the raw CRL in DER or PEM form from https://www.vaultproject.io/api/secret/pki/index.html#read-crl

**Comment by ror6ax** [comment]
I mean CSR certificate in response to `intermediate/generate/internal`,not CRL as in revocation list.

**Comment by ror6ax** [comment]
My reply look like 

\" {\"request_id\":\"e58b0613-2bac-f65e-5964-05c958a5749e\",\"lease_id\":\"\",\"renewable\":false,\"lease_duration\":0,\"data\":{\"csr\":\"-----BEGIN CERTIFICATE REQUEST-----\\nMIICaTCCAVECAQAwJDEiMCAGA1UEAxMZTm9raWEgQVZBIGludGVybWVkaWF0ZSBD\\nQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMqx5/cumST7hfnmj7sk\\nO79lqCOSM5ymsAcDmPx8b6aHYtBEdjgbrczX83eaE53srrKz+dASAPqcyelBplVH\\n43rwN6r16ofeyvYKQnhTKrsVelltTg+jVyv518UIhkRI+mK7m0Q40kIpCeiv4AU0\\nl/Coalmu9m5e71j+xswC5m5ezvxha7SbcLvZEUE+RihUPcipchn7/EkP5ThO3mpN\\nmenRDR5jIuBq31k62hShM9TsVry0zEmQoWBw4/88UDYZYffV133aGKXBrFXSwsGi\\nmZfqpxDP8wMvxsGIISy03oWvagCD52RJXs7VGuPe2T3VnT7v/zw9brEY+z/n97eR\\n3c0CAwEAAaAAMA0GCSqGSIb3DQEBCwUAA4IBAQAMYJ1bExNJJvttjcintC3GIn1+\\nB/tkofY5Jwcw48rplVjzzvY4B29G65EOgB9Ko84sopevQuoNiWgZapDNvDYS2MrD\\n1I3eZkeEZwCtfdEysDzxCpL2ngDfQ5BkAFHXeCwi42vdc0yvvnMigSupclZnLI93\\nNqGYU7K/174TadfhQymV5tqFMkFDT1CmzYMMEYXXy+kLwo+G8m+LhsP4Mb0xW4vL\\nAGx+SE9O/6mjBWJtX+dN/HVVxOzasH1lFT8VKDSI2D9afiFw5TxD4ceFupMI0b51\\nMzTzBRFHigWszccBTo3lItRyIlHhJblH5APZ5QIUJT/viXYAGH6f9H2zgexm\\n-----END CERTIFICATE REQUEST-----\"},\"wrap_info\":null,\"warnings\":null,\"auth\":null}\n\" } "

\\n is apparently illegal in JSON, so my only option is to cut CSR out in string form, which is highly hacky thing to do.

**Comment by jefferai** [comment]
@ror6ax I'm not sure how you're getting that output. Here is an example of me running the same command with `curl` -- no newlines or extra braces:

> $ curl -X POST -H "x-vault-token: root" -d '{"common_name": "example.com"}' http://127.0.0.1:8200/v1/pki/intermediate/generate/internal
> {"request_id":"70c37467-3d77-35b1-e7e7-8e50aa256ba9","lease_id":"","renewable":false,"lease_duration":0,"data":{"csr":"-----BEGIN CERTIFICATE REQUEST-----\nMIIChDCCAWwCAQAwFjEUMBIGA1UEAxMLZXhhbXBsZS5jb20wggEiMA0GCSqGSIb3\nDQEBAQUAA4IBDwAwggEKAoIBAQC2XX8usm/kx4pWr+VYKiU36Avz9Xw9mQuvz1LU\nWF/clkjxNs7P8byCj0rtRP36s37fY/VSh8RuTPqps3iJQCTNs0nlDLhNZ4TaFAX7\nkrEfTL7ztwSc3Pprg8+K7+kMlU7HJ8M8C5hA+ScMwvYTwjpd9h9h68jKrmXroPLd\nt4eAbRb4R4ZknaVC6ZkWolh2l/geUW8kNNUBcNhGUlbpikukK5vb3OQDzyccW1DA\niquq3mm2qvFTU4SMiIU71gVdIQGxL6Tp2bWtPhILzrzv2wtGzZCaSrtHrDq3jcbe\nAMz6VOWUqlaXj48Qc+bAPoQ9/C2UAQbx4hXZxfm2bynAIvOXAgMBAAGgKTAnBgkq\nhkiG9w0BCQ4xGjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMA0GCSqGSIb3DQEB\nCwUAA4IBAQALkdibyTqNbnQe9Xxd/30blST1TpWhCnq18P9T2p88Ci3RmQhDlTlg\nubirmU5qrNdLleod47z3Cnt5seakBlMIQQ2ztqhPKH4QE2Y4Co7bkObE72zOIIOr\n+HDoevc+Zu8wEhNTvBUjE4xOHDL7Cno9NJfP1gzVe/5LIm+IJVtgdzN/MYhcWWI6\nsmmBI4USjcOXY14CEWreh0VisfQAneko/oaK0ttOJDKxxRaLfrilEaU3/iIriDF9\ni16OaYh6tMYfOMWeLczzwASs14glUe3nZB6HirYQKYQaj5CLPFDCBp2DJVGtyliI\nScfd8VlBYGyGki4RvgmbFfzPf5naXfBQ\n-----END CERTIFICATE REQUEST-----"},"wrap_info":null,"warnings":null,"auth":null}
