### ISSUE TITLE
Write: diff content changes to a file

### ISSUE THREAD

**Issue by marwan-at-work** [hashicorp/vault#3650]
**Feature Request:**

Say a project/repository, has a secret file that it stores on the vault server. Say this code base is being worked on by multiple people. Those two facts make it difficult to synchronize secret updates/accidental-overwrites between the team members.

Imagine you update a secret and forget to tell the team to download the secret, then another team member updates that secret causing your updates to be overwritten. 

There are a couple of approaches to dealing with this:
1. Versioning secret files, aka never deleting a secret and always creating a new one in the vault server. This is fine, but there's a chance that someone forgets to build a new version of a secret based on the latest version of that same secret. It's also a bit manual in that you always need to see what is the latest version of a secret before creating a new one, and that you need to constantly update your CI/CD to get a different secret path. 

2. Having the CLI command show you a diff before overriding a secret, to see what you're about to modify in the file. Then it prompts if you're okay with those changes. This approach adds a verification step as well as a safety net so that you don't overwrite somebody else's addition to that secret file by mistake. 

I've written a little script internally to do that and it's been personally helpful within the team. However, I was wondering if this is something the vault team is interested in adding. Something like `vault write /path/to/my/secret key=@file -diff` which will fetch the upstream `path` first and compare it with the local file and show you a diff of what will change.

I'd be happy to send a PR, but before I did so, I just wanted to see if vault has another approach to solving this problem.

Thanks!

**Comment by jefferai** [comment]
I don't think we'd accept a `-diff` command because it's a bit too single-purpose. But, we do have plans for a revamp of the K/V backend and I think this kind of use case will be addressed in it!
