### ISSUE TITLE
PKI domain.com not allowed by this role

### ISSUE THREAD

**Issue by ror6ax** [hashicorp/vault#3655]
Hi guys.

Literally doing one-to-one with the manual:

POST to `v1/my_pki/roles/webserver` - `"allow_any_name": "true", "allowed_domains":"mydomain.com", "allow_subdomains": true,"allow_bare_domains":true, "max_ttl":"72h" `

POST to `v1/my_pki/issue/webserver` with `common_name=mydomain.com` -> `"common name mydomain.com not allowed by this role"`

What am I doing wrong?

**Comment by vishalnayak** [comment]
@ror6ax Which manual are you following? I don't see "mydomain.com" anywhere in the documentation.

I ran the on the latest version and its working.
https://gist.github.com/vishalnayak/a9b514cfa186fc46dc4bf879a1318119
