### ISSUE TITLE
Location of users and groups info for LDAP

### ISSUE THREAD

**Issue by samthegolden** [hashicorp/vault#3660]
Would like to make configurations persistent in a dockerized service of vault, as it happens with the secrets. Where are they stored?

* Vault Version:
vault 0.8.3,  alpine:3.5

**Expected Behavior:**
Add users and groups, bind to policies. The service is teared down and when restarts everything remains set.

**Actual Behavior:**
When the service is restarted, the configurations of users and groups don't exist anymore, instead of secrets, that are persistent.

**References:**
https://www.vaultproject.io/docs/auth/ldap.html

**Comment by jefferai** [comment]
@samthegolden All data by Vault is stored in its configured data store. There is no difference from a Vault perspective between KV secrest and LDAP. Sounds like Docker is rolling back your changes.

**Comment by samthegolden** [comment]
that's really weird. Secrets remain when I update the service, but users and groups don't... I have a volume on /data ...

**Comment by samthegolden** [comment]
thank you. Not when tearing down, but when restarting, yes I do unmount it. I'd never be aware of it without your say. Sorry for wasting your time and congs for the work.

**Comment by jefferai** [comment]
No problem! Yeah -- unmount in Vault destroys the underlying mount's data. If you want to leave it in there, simply shut down without using an unmount!

**Comment by samthegolden** [comment]
When I say unmount, i say i disable auth for ldap, that deletes all the configuration set for it... it works like an unmount...

**Comment by vishalnayak** [comment]
@samthegolden Yes. `auth-disable` is to auth backends what `unmount` is for secret backends.
