### ISSUE TITLE
Vault deployment issue

### ISSUE THREAD

**Issue by iyngaran** [hashicorp/vault#3667]
I have done the installation and deployment as it is this document - https://www.vaultproject.io/intro/getting-started/deploy.html

And also I was able to write and read Secret with Key/Value Secret Backend. Everything is working without any problem.

But the issue is : when I restart the server, I am unable to get the stored data back. Also, I am using Username & Password Auth Backend, those use accounts also disappear when I restart the server. 

Can you please let me know, is that the way, the vault is working ? I am unable to find the details regarding this issue in your website.

**Comment by vishalnayak** [comment]
@iyngaran Which storage backend are you using?

**Comment by iyngaran** [comment]
The secret backend.On 08-Dec-2017, at 8:14 PM, Vishal Nayak <notifications@github.com> wrote:@iyngaran Which storage backend are you using?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by iyngaran** [comment]
Key/Value Secret Backend

**Comment by chrishoffman** [comment]
What does the startup of your vault server look like?  What @vishalnayak is referring to is the storage backend as referred to here https://www.vaultproject.io/docs/configuration/storage/index.html.  You will need to pick a durable storage backend to have your data persisted between restarts.

As you can see from the following startup output, this vault server is running in in-memory mode.
```
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: false, enabled: false
        Redirect Address: http://127.0.0.1:8200
                 Storage: inmem
                 Version: Vault v0.9.0
             Version Sha: bdac1854478538052ba5b7ec9a9ec688d35a3335
```

**Comment by iyngaran** [comment]
Here is my configuration. 
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: false, enabled: false
        Redirect Address: http://127.0.0.1:8200
                 Storage: consul (HA available)
                 Version: Vault v0.8.3
             Version Sha: 6b29fb2b7f70ed538ee2b3c057335d706b6d4e36

==> Vault server started! Log data will stream in below:

OK i will try with the document... Thanks for your comment

**Comment by jefferai** [comment]
How are you starting and stopping Vault?

(Also, if this is a new deployment, I recommend starting with 0.9.0 instead of 0.8.3.)

**Comment by iyngaran** [comment]
@jefferai 

Thank you for your comment.

I start the Vault like this - vault server -config=config.hcl and I have done all these steps - https://www.vaultproject.io/intro/getting-started/deploy.html

**Comment by iyngaran** [comment]
@chrishoffman

Why when I start the server with this command - vault server -config=config.hcl, It is starting in in-memory mode ? 

Seems that is the way to start the server - https://www.vaultproject.io/intro/getting-started/deploy.html

Is there are any other way to start the server ?

**Comment by calvn** [comment]
Vault will start with whatever storage you declare to use on your config.hcl file. From your latest set of Vault logs, it seems that Vault was using Consul as the storage, which is one of the available types of persistent storage. The data should persist between Vault restarts unless you delete Consul data.

**Comment by iyngaran** [comment]
@calvn 
Thank you (y)

**Comment by iyngaran** [comment]
Seems I had some issues with consul storage. I changed that to file. Now all the issues are fixed.

Thank you guys for your valuable time and help

**Comment by jefferai** [comment]
Sounds good!
