### ISSUE TITLE
Token lease duration

### ISSUE THREAD

**Issue by PankajAmbekar** [hashicorp/vault#3668]
I am using userpass authentication with 0 TTL. Still for every token I create, I get a field in response called "lease_duration": 2764800. Would the token expire after the mentioned period? Also, is there any way by which I can use one token for infinite amount of time?

**Comment by vishalnayak** [comment]
@PankajAmbekar A TTL of 0 does not indicate that the expiration is immediate. Setting a `0` is equivalent to not setting it and the default TTL gets applied to the token. The default value depends on the system default TTL, the TTL set on the mount and the TTL set on the backend (whichever is least).

The token you created will expire. Other than the initial root token, the only way to create a token that can be renewed forever (and hence can live for infinite amount of time), is to create periodic tokens. Token concepts are detailed here: https://www.vaultproject.io/docs/concepts/tokens.html.
