### ISSUE TITLE
Stderr: main.go:6:2: cannot find package "github.com/hashicorp/vault/cli"

### ISSUE THREAD

**Issue by iyngaran** [hashicorp/vault#3675]
Unable to install vault from source. When i run **make dev**, It says 

==> Checking that code complies with gofmt requirements...
==> Checking that build is using go version >= 1.9.1...
go generate 
==> Removing old directory...
==> Building...
Number of parallel builds: 1

-->     linux/amd64: _/usr/share/vault

1 errors occurred:
--> linux/amd64 error: exit status 1
Stderr: main.go:6:2: cannot find package "github.com/hashicorp/vault/cli" in any of:
	/usr/local/go/src/github.com/hashicorp/vault/cli (from $GOROOT)
	/root/go/src/github.com/hashicorp/vault/cli (from $GOPATH)

make: *** [dev] Error 1

**Comment by chrishoffman** [comment]
It looks like you may have checked out vault's source into the incorrect location in your $GOPATH or you are running `make dev` using `sudo` and it is changing the $GOPATH to being in root's home directory.

What directory did you check out vault's source under and what is the value of your GOPATH environment variable?

**Comment by bob0009** [comment]
> It looks like you may have checked out vault's source into the incorrect location in your $GOPATH or you are running `make dev` using `sudo` and it is changing the $GOPATH to being in root's home directory.
> 
> What directory did you check out vault's source under and what is the value of your GOPATH environment variable?

I had the same problem , but i don't know how to solve it , would you please help me out?
I've been learning how to use vault by hashicorp recently,The attached document is the screenshot of the problem
[screenshots for problem.docx](https://github.com/hashicorp/vault/files/2871960/screenshots.for.problem.docx)
