### ISSUE TITLE
changing order of policies on 'vault write' changes behavior

### ISSUE THREAD

**Issue by donfranio** [hashicorp/vault#3676]
**Environment:**

* Vault Version: Vault v0.9.0 ('2931148d0955f49a90cd9e8f4b83b1e23e5fa6bf')
* Operating System/Architecture: debian stretch amd64

**Vault Config File:**
none, just
```vault server -dev```

**Startup Log Output:**

**Expected Behavior:**

When writing an approle with the policy-flag you expect that the order of the policices does not matter, e.g. 
```
Success! Data written to: auth/approle/role/name
Success! Data written to: auth/approle/role/name
```
or two similar errors.

**Actual Behavior:**
```
+ vault write auth/approle/role/name policies=policy1,test-policy
Success! Data written to: auth/approle/role/name
+ vault write auth/approle/role/name policies=test-policy,policy1
Error writing data to auth/approle/role/name: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/approle/role/name
Code: 403. Errors:

* permission denied
```
switched order of policies

**Steps to Reproduce:**
```
#!/bin/bash
set -x
cat <<EOF > testcase.hcl
path "auth/approle/" {
    capabilities = [ "list" ]
}

path "auth/approle/*" {
    capabilities = [ "create", "read", "update", "delete", "list" ]
    allowed_parameters = {
        "policies" = ["policy*", "test-policy"]
        "*" = []
    }
}
EOF

vault auth-enable approle
vault policy-write approle-policy testcase.hcl
vault policy-write policy1 testcase.hcl
vault policy-write test-policy testcase.hcl
vault token-create -policy="approle-policy"
echo "vault auth <returned-token>"
read token
vault auth $token
vault write auth/approle/role/name policies=policy1,test-policy
vault write auth/approle/role/name policies=test-policy,policy1
```
on the read-step you can copy-n-paste the auth-token.

**Comment by jefferai** [comment]
This is expected behavior; "policy1,test-policy" is matched by `policy*` but not `test-policy`; "test-policy,policy1` is matched by neither `test-policy` nor `policy*`.

Unfortunately, due to limitations with expressing things in HCL/JSON, `allowed_parameters` and its ilk are not super flexible. The only alternative right now (which is *very* flexible) is Sentinel.

**Comment by juliantaylor** [comment]
Then the documentation is wrong? https://www.vaultproject.io/docs/concepts/policies.html
This says:

... the key "secret/restricted" can only contain "foo" (any value) and "bar" (**one  of** "zip" or "zap").

```
  allowed_parameters = {
    "foo" = []
    "bar" = ["zip", "zap"]
  }
```

The testcase does not work even if you replace the wildcard with the existing policy names.
