### ISSUE TITLE
Send policy via HTTP API

### ISSUE THREAD

**Issue by samthegolden** [hashicorp/vault#3678]
I'm trying to send the following to Vault:

`curl -k --header "X-Vault-Token: $VAULT_TOKEN" --request POST -d '{"rules":"path \"secret/*\" { capabilities = [\"read\", \"create\", \"update\", \"list\", \"delete\"]}", "path \"sys/*\" { capabilities = [\"read\", \"create\"]}"}' http://$SERVER:8200/v1/sys/policy/cic_root_policy`

I can send:

`curl -k --header "X-Vault-Token: $VAULT_TOKEN" --request POST -d '{"rules":"path \"secret/*\" { capabilities = [\"read\", \"create\", \"update\", \"list\", \"delete\"]}"}' http://$SERVER:8200/v1/sys/policy/cic_root_policy`

but when I add a second path (first command) vault returns:

`{"errors":["failed to parse JSON input: invalid character '}' after object key"]}`

I've tried many ways, and I haven't found an example in documentation for this. How can Ĩ send multiple path rules for Vault via HTTP API? Thanks

**Comment by jefferai** [comment]
In the first example instead of a newline you are terminating the `rules` value and then trying to specify another value. `rules` is a string, not an array. The following works:
```
curl -k --header "X-Vault-Token: root" --request POST -d '{"rules":"path \"secret/*\" { capabilities = [\"read\", \"create\", \"update\", \"list\", \"delete\"]}\npath \"sys/*\" { capabilities = [\"read\", \"create\"]}"}' http://127.0.0.1:8200/v1/sys/policy/cic_root_policy

$ vault policies cic_root_policy
path "secret/*" { capabilities = ["read", "create", "update", "list", "delete"]}
path "sys/*" { capabilities = ["read", "create"]}
```
