### ISSUE TITLE
Slashes allowed in policy name's but not token-role names

### ISSUE THREAD

**Issue by wrouesnel** [hashicorp/vault#3682]
**Environment:**
* Vault Version: Vault v0.9.0 ('bdac1854478538052ba5b7ec9a9ec688d35a3335')
* Operating System/Architecture: Linux x86_64

**Expected Behavior:**
```
vault write "auth/token/roles/some/role/name" allowed_policies="some/policy/name"
```
Should succeed.

**Actual Behavior:**
```
vault write "auth/token/roles/some/role/name" allowed_policies="some/policy/name"
Error writing data to auth/token/roles/some/role/name: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/token/roles/some/role/name
Code: 404. Errors:

* 1 error occurred:

* unsupported path
```

**Steps to Reproduce:**
Initialize a Vault dev server. Run the command above.

**Important Factoids:**
The motivation here is to create roles which allow a user to gain a specific policy (controlled via a wildcard policy on the security principal which should have access). i.e. we'd like to write a policy for a user like:
```
path "auth/token/create/environment/team/*" {
     capabilities = ["create"]
}
```
and also have some other approle with a more general ability to elevate rolls:
```
path "auth/token/create/environment/*" {
     capabilities = ["create"]
}
```

**Comment by jefferai** [comment]
Not a bug; please use a different delimiter.

**Comment by jsok** [comment]
@jefferai is there a reason slash delimiters are allowed for AppRole names and not token role?

**Comment by jefferai** [comment]
I'm unsure at the moment, sorry.

**Comment by jefferai** [comment]
@jsok slashes are not allowed in approle names either:

```
$ vault write auth/approle/role/some/role/name asdf=asdf
Error writing data to auth/approle/role/some/role/name: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/approle/role/some/role/name
Code: 404. Errors:

* 1 error occurred:

* unsupported path
```

**Comment by wrouesnel** [comment]
@jefferai but they are allowed in token-role names, which is an odd incongruity?
