### ISSUE TITLE
Add a 'sealed-status' gauge to telemetry

### ISSUE THREAD

**Issue by TimJones** [hashicorp/vault#3689]
**Feature Request:**
Add a telemetry option to report current sealed status of the Vault instance.

I am running a Vault HA deployment in Kubernetes. Using a [statsd_exporter](https://github.com/prometheus/statsd_exporter) side-car to collect metrics from each instance and expose them to Prometheus for monitoring.

With the `vault.core.seal` and `vault.core.unseal` metrics, I can perform calculations to get the vault status, until a vault instance restarts (since this is a 'seal' operation without a metric).

A new telemetry point that can just give the current sealed\unsealed status as a gauge at `vault.core.unsealed_status` can be `0` when sealed (set at start-up and with any `seal` operation) and `1` after a successful `unseal` operation.

**Comment by TimJones** [comment]
Or thinking about it another way, maybe on start-up a vault instance should emit the telemetry for `seal` operations and `unseal` operations at 0...

**Comment by seanjfellows** [comment]
+1 to this, related having a leadership status gauge would be similarly useful. Today I don't see a way to determine if the vault cluster has exactly 1 leader.

**Comment by richard-mauri** [comment]
+1 on adding sealed and leader info added to vault telemetry

**Comment by anthosz** [comment]
+1

**Comment by vishalnayak** [comment]
Already added. Refer https://www.vaultproject.io/docs/internals/telemetry.
