### ISSUE TITLE
Vault Auth - Authentication Problems

### ISSUE THREAD

**Issue by akamalov** [hashicorp/vault#369]
Deployed Vault in a container environment. Authentication using ```vault auth``` from within container works fine:

```
/ # vault auth -address=http://127.0.0.1:8200 8a88925f-c1b4-76ea-3c04-567720f789c3
Successfully authenticated! The policies that are associated
with this token are listed below:

root
/ # 
```

Now, we'll try to do the same thing from outside the container. Container port ```:8200``` is mapped to a host port ```:8200```.

Authentication fails with <b> Invalid Token </b>
```
root@wwserver108:~# vault auth -address=http://10.9.9.65:8200 '8a88925f-c1b4-76ea-3c04-567720f789c3'

Error: Invalid token
```

How is that possible ?

I can use '``curl``' to query vault status:

```
root@wwserver108:~# curl -H "X-Vault-Token: 8a88925f-c1b4-76ea-3c04-567720f789c3" -H "Content-Type: application/json" http://10.9.9.65:8200/v1/sys/health
{"initialized":true,"sealed":false,"standby":false}
```

**Comment by sethvargo** [comment]
Hi @akamalov 

Could you please share your container setup (Dockerfile) and the version of Vault you are using? Thanks!

**Comment by akamalov** [comment]
Vault Version:

```
/ # vault -version
Vault v0.1.2
/ # 
```

Vault Config:

```
backend "consul" {
  address = "10.9.9.65:8500"
  path = "vault"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}
```

Container Build - Dockerfile:

```
FROM voxxit/base:alpine

RUN  wget http://dl.bintray.com/mitchellh/vault/vault_0.1.2_linux_amd64.zip \
  && unzip vault_0.1.2_linux_amd64.zip \
  && mv vault /usr/local/bin/ \
  && rm -f vault_0.1.2_linux_amd64.zip

EXPOSE 8200

ENTRYPOINT [ "vault" ]
CMD [ "server", "-config=/etc/vault/vault.json" ]
```

**Comment by armon** [comment]
@akamalov check that you do not have a VAULT_TOKEN environment variable set. That can cause issues. The next release provides a warning if set.

**Comment by akamalov** [comment]
Thanks Armon. I will verify it.

**Comment by akamalov** [comment]
Yep, just verified it. Works when I export VAULT_TOKEN. Thanks a ton, Armon.
