### ISSUE TITLE
Build issue - AllowPlaintextBackup missing in PolicyRequest struct

### ISSUE THREAD

**Issue by steveoc64** [hashicorp/vault#3693]
Patch to fix: 

--------------------------------------- cut -----------------------------
commit e84f380568b8cf2aec5458a97d9f5a51938c8e17
Author: SteveOC <steve64@gmail.com>
Date:   Fri Dec 15 13:53:55 2017 +1000

    add missing item from struct

diff --git a/helper/keysutil/lock_manager.go b/helper/keysutil/lock_manager.go
index 1672404..a6f48ec 100644
--- a/helper/keysutil/lock_manager.go
+++ b/helper/keysutil/lock_manager.go
@@ -43,6 +43,9 @@ type PolicyRequest struct {
 
 	// Whether to upsert
 	Upsert bool
+
+	// Allow Plaintext Backup
+	AllowPlaintextBackup bool
 }
 
 type LockManager struct {
-------------- paste ---------------------------------

Added this, builds OK, and seems to work.
thx :)

**Comment by jefferai** [comment]
This is already fixed in `master`.
