### ISSUE TITLE
Allow PKI certificate fields to be specified as an array

### ISSUE THREAD

**Issue by sidewinder12s** [hashicorp/vault#3698]
**Feature Request:**
Allow certificate fields to be specified as an array.

Currently if you try to use a comma in a certificates Organization or OU field it will split the content on the comma with no way to escape the comma.

**Environment:**
* Vault Version: 0.9.0
* Operating System/Architecture: Ubuntu 16.04

**References:**
Originally brought up here: https://groups.google.com/d/msg/vault-tool/P0DVffjaglY/Cp_fG6fjCQAJ

**Comment by jefferai** [comment]
Putting into 0.9.1 milestone but as previously communicated will probably slip.

**Comment by jefferai** [comment]
We should do this with OU as well.

**Comment by jefferai** [comment]
Note to Vault team: we have to be careful on upgrade here; we can't do it transparently on read since certs are issued cluster-locally.
