### ISSUE TITLE
A bad audit backend can make Vault unusable

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#37]
If I enable an audit backend for `file`, for example, but I specify a path I do not have write permissions to, Vault becomes unusable. All requests will fail because the audit fails to write, but I cannot disable the audit without killing the server.

```text
2015/04/24 14:57:02 [ERR] audit: backend 'audit/' failed to log request: open testing: no such file or directory
2015/04/24 14:57:02 [ERR] core: failed to audit request (*logical.Request{Operation:"delete", Path:"sys/audit/testing", Data:map[string]interface {}(nil), Storage:logical.Storage(nil), Secret:<nil>, Auth:<nil>, Connection:(*logical.Connection)(nil), ClientToken:"...", DisplayName:"root"}): no audit backend succeeded in logging the request
```

**Comment by jefferai** [comment]
```
We talked about this in chat a bit, and Armon thinks there might be a vulnerability where a very skilled attacker to perform actions by putting an audit into a bad state.
```
Note that an attacker that can put audit into a bad state can therefore DoS clients relying on Vault for the secrets necessary for operation. This is commonly thought of as a vulnerability as well, although it is certainly better to deny requests than to give up secrets given a choice between the two.

**Comment by abedra** [comment]
What happens if one of n audit log targets becomes unavailable? Does the same thing happen?

**Comment by mitchellh** [comment]
@abedra As long as one backend is available, the other audit logs are dropped.
