### ISSUE TITLE
Vault Transit to have multi value

### ISSUE THREAD

**Issue by harshtg** [hashicorp/vault#3705]
Am trying to map **multi-value for the single key** using vault transit. When I tried "/transit/encrypt-list/" service with the corresponding request body throws "json: cannot unmarshal array into Go value of type map[string]interface {}" this error. Could anyone please help me on this.

**Comment by jefferai** [comment]
Please fill out the appropriate fields from the issue template. There isn't enough information here to provide help.

**Comment by catsby** [comment]
Hello - I'm going to close this issue for now, as we never heard back. If you have more information to share please let us know and we can take a look. Thanks!
