### ISSUE TITLE
no matching WALs available

### ISSUE THREAD

**Issue by PVK012** [hashicorp/vault#3723]
Hello All,

Below messages were continuous writing in /var/log/messages. In our cluster we have 2 vault and 3 consul servers, Services are up and running on all the servers. 

[INFO ] replication: no matching WALs available
[INFO] replication: requesting WAL stream: guard=********
[INFO ] core: non-matching guard, exiting

Could someone help me to understand why this messages are writing  continuously. let me know if my question is not clear I can elaborate.

**Comment by jefferai** [comment]
I'm sorry, but you need to go through Enterprise support.
