### ISSUE TITLE
Is there any differences hashicorp_vault and ansible-vault?

### ISSUE THREAD

**Issue by DockerAsura** [hashicorp/vault#3726]
Is there any differences hashicorp_vault and ansible-vault? Planning to implement vault in my ENV, But same confusion about  hashicorp_vault and ansible-vault......
Can someone help me the same.. 
Thanks in advance :)

Thanks
Asura

**Comment by stenio123** [comment]
The official page has a comparison chart between Vault and other technologies, Ansible would fit with Chef and Puppet:
https://www.vaultproject.io/intro/vs/index.html
