### ISSUE TITLE
[AWS Secret Backend] - STS revocation not working/documented

### ISSUE THREAD

**Issue by mvisonneau** [hashicorp/vault#3736]
When you use an AWS secret backend and generate an STS credentials set, you have to wait until the end of the STS lease duration before it becomes revoked. This is due to an AWS limitation onto STS tokens management but it would be nice to either document it or make those leases non revocable in Vault. Another possibility would be to leverage the revocation at the role level : http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_revoke-sessions.html

**Comment by willglynn** [comment]
Seconded: Vault says ["The access keys can be revoked by using the lease ID"](https://github.com/hashicorp/vault/blob/v0.9.1/builtin/logical/aws/path_sts.go#L90-L91), but revoking STS-generated credentials [is a no-op](https://github.com/hashicorp/vault/blob/v0.9.1/builtin/logical/aws/secret_access_keys.go#L278-L290).
