### ISSUE TITLE
Why "vault read" and "curl ..." get absolutely different results?

### ISSUE THREAD

**Issue by pashinin** [hashicorp/vault#3743]
* Vault Version: Vault v0.9.0
* Operating System/Architecture: Ubuntu 16.04

**Vault Config File:**
```
storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}

cluster_name = "testcluster"
```

**Expected Behavior:**

```
vault read secret/test
```

should be the same as

`curl ... /v1/secret/test`

**Actual Behavior:**

`vault write/read` actually writes/reads somewhere else. I can use python hvac to write and read. And then I can `curl` it. But `vault write/read` does it somewhere else.

**Steps to Reproduce:**

`vault write secret/test key=value`

Then `curl -H "X-Vault-Token: " -X GET http://127.0.0.1:8200/secret/test` it.

See there is nothing.

**Comment by calvn** [comment]
You should be hitting http://127.0.0.1:8200/v1/secret/test with curl instead. You also need to provide a token with proper access level to the secret path (e.g. the initial root token). The Vault client is simply a thin wrapper around the HTTP API, so the responses are the same. If you want JSON responses from the CLI, include `-format=json` as part of your commands.

**Comment by pashinin** [comment]
Sorry, it was a mistake. Of course I just missed "v1" here. I used the correct url. 

The problem is I can write "key=value" in CLI and using hvac (python). And then I can read `/v1/secret/test` with curl and with CLI. And the key-value pairs are different. I don't understand how it is possible.

Looks like I'm writing and reading using different paths in both cases. But I tripple checked it.

**Comment by pashinin** [comment]
Ok, it was actually url problem, but in different place. Thanks.
