### ISSUE TITLE
command: `testing` dependency is polluting `flag` options

### ISSUE THREAD

**Issue by orirawlings** [hashicorp/vault#3745]
**Environment:**

* Vault Version: Vault v0.9.1 ('87b6919dea55da61d7cd444b2442cabb8ede8ab1')
* Operating System/Architecture: go version go1.9.2 darwin/amd64

**Vault Config File:**

N/A

**Startup Log Output:**

N/A

**Expected Behavior:**

I frequently create CLI tools with Go that interact with Vault. I want these varioius CLI tools to honor the same environment variable configurations that the standard `vault` CLI tool honors, including support for `VAULT_CONFIG` and the ability to load a vault token from `~/.vault_token` or to respect custom token helpers. To do this implementation of the tools look something like the following:

```
package main

import (
  "flag"

  "github.com/hashicorp/vault/api"
  "github.com/hashicorp/vault/command"
)

// Client creates a new client for Vault which loads configuration
// settings from the environment and potentially looks up a token
// in ~/.vault_token for authentication.
func client() (*api.Client, error) {
  c, err := api.NewClient(nil)
  if err != nil {
    return nil, err
  }
  if c.Token() == "" {
    th, err := command.DefaultTokenHelper()
    if err != nil {
      return nil, err
    }
    t, err := th.Get()
    if err != nil {
      return nil, err
    }
    c.SetToken(t)
  }
  return c, nil
}

func main() {
  var f bool
  flag.BoolVar(&f, "f", false, "my flag")
  flag.Parse()

  client()
  // use the client for something useful
}
```

The great thing about this approach is that users can use the standard `vault auth` command to authenticate with the Vault server and store a vault token, and then my custom CLI tools will be able to load that token since both tools can leverage the same token helper.

I typically use the `flag` package from the Go SDK because it is sufficient and doesn't require 3rd party dependencies.

Unfortunately this code exhibits some undesirable behavior when my users invoke the custom tool with the standard `--help|-h` option, a bunch of additional options are listed in the output:

```
$ go run main.go --help
Usage of /var/folders/__/1bnpyd4d7t31wkxd9vmk2sz9985fpv/T/go-build463432799/command-line-arguments/_obj/exe/main:
  -f    my flag
  -hdb.protocol.trace
        enabling hdb protocol trace
  -hdb.sqlTrace
        enabling hdb sql trace
  -test.bench regexp
        run only benchmarks matching regexp
  -test.benchmem
        print memory allocations for benchmarks
  -test.benchtime d
        run each benchmark for duration d (default 1s)
  -test.blockprofile file
        write a goroutine blocking profile to file
  -test.blockprofilerate rate
        set blocking profile rate (see runtime.SetBlockProfileRate) (default 1)
  -test.count n
        run tests and benchmarks n times (default 1)
  -test.coverprofile file
        write a coverage profile to file
  -test.cpu list
        comma-separated list of cpu counts to run each test with
  -test.cpuprofile file
        write a cpu profile to file
  -test.list regexp
        list tests, examples, and benchmarch maching regexp then exit
  -test.memprofile file
        write a memory profile to file
  -test.memprofilerate rate
        set memory profiling rate (see runtime.MemProfileRate)
  -test.mutexprofile string
        write a mutex contention profile to the named file after execution
  -test.mutexprofilefraction int
        if >= 0, calls runtime.SetMutexProfileFraction() (default 1)
  -test.outputdir dir
        write profiles to dir
  -test.parallel n
        run at most n tests in parallel (default 8)
  -test.run regexp
        run only tests and examples matching regexp
  -test.short
        run smaller test suite to save time
  -test.timeout d
        panic test binary after duration d (0 means unlimited)
  -test.trace file
        write an execution trace to file
  -test.v
        verbose: print additional output
exit status 2
```

My expectation here would be that only the `-f` option that was declared in CLI tool would be printed. Instead, we see a number of additional flags that are declared by the `testing` package.

These additional options are registered with `flag` when the `testing` package is initialized. I think that typically `testing` should only be imported from test code, but because the CLI tool imports `github.com/hashicorp/vault/command` we find that there are a handful of transitive dependencies that pull it in to the program. The dependencies which directly import `testing`:

```
$ for dep in $(go list -f '{{join .Deps "\n"}}' .); do go list -f '{{join .Imports "\n"}}' ${dep} | grep -q '^testing$' && echo ${dep}; done
github.com/hashicorp/vault/command/token
github.com/hashicorp/vault/http
github.com/hashicorp/vault/logical
github.com/hashicorp/vault/logical/framework
github.com/hashicorp/vault/physical
```

I'm curious if there are recommendations on how to deal with this. 

Obviously if we want to avoid importing `testing` in the above packages it would require some backward-incompatible changes. I'm happy to work on a patch, but would like to understand if it is something the project is amenable to.

If there is another approach I should take with the implementation of my tools, I'm open to recommendations.

**Actual Behavior:**

See above

**Steps to Reproduce:**

See above

**Important Factoids:**

**References:**

**Comment by jefferai** [comment]
Hi Ori,

Can you explain why your CLI tools are importing the command package? This is not a package meant to be imported by external tools so I'd like to understand the use-case.

Additionally, are you finding uses of the "testing" package in code that is not in a `_test.go` file?

**Comment by orirawlings** [comment]
Hey @jefferai,

To clarify, the import of the `github.com/hashicorp/vault/command` package is necessary so that I can use the [`command.DefaultTokenHelper`](https://godoc.org/github.com/hashicorp/vault/command#DefaultTokenHelper) which is basically responsible for reading the `VAULT_CONFIG` environment variable, detecting the currently configured token helper (defaulting to loading tokens from `~/.vault_token`).

I find it extremely beneficial to reuse this code and otherwise avoid the need to reimplement token helper integration myself. Frequent usage of the CLI tools might look something like this:

```
$ vault auth -method=ldap  # uses currently configured token helper to store token
$ my-tool                  # uses same token helper to load token before interacting with Vault API
```

We manage several different vault servers across different environments so we tend to use custom token helpers to manage multiple credentials simultaneously for the various environments.

We find token helpers to be an immensely useful, reusable, concept present in the project beyond just the normal `github.com/hashicorp/vault/api` package.

The `testing` package is indeed imported outside of `_test.go` files in the packages I listed:
```
github.com/hashicorp/vault/command/token
github.com/hashicorp/vault/http
github.com/hashicorp/vault/logical
github.com/hashicorp/vault/logical/framework
github.com/hashicorp/vault/physical
```

Specifically `testing` appears to be imported by the following files:
```
github.com/hashicorp/vault/command/token/testing.go
github.com/hashicorp/vault/http/testing.go
github.com/hashicorp/vault/logical/testing.go
github.com/hashicorp/vault/logical/framework/testing.go
github.com/hashicorp/vault/physical/testing.go
```

These files all seem to be declaring reusable testing utilities that are sometimes used in the tests of other packages (although sometimes only within the current package).

**Comment by jefferai** [comment]
Do you see the same behavior if you compile the binary and execute it directly rather than running through `go run`?

An easy way to fix this would be to make the package for `testing.go` in the `command/testing` package be `token_test`. If you want to make that change (and associated changes to tests) and submit a PR I'd be happy to merge it.

**Comment by orirawlings** [comment]
So I dug in to see how to refactor these files to avoid a transitive dependency on `testing` from  `github.com/hashicorp/vault/command`. It is getting pretty hairy, and tricky to avoid introducing circular dependencies. I end up having to modified lots of test files throughout the entire project. The patch is looking like it would be quite substantial in size, so maybe not worth it.

A workaround for this issue that seems to work, is to use a `flag.FlagSet` in the program. The code I posted before would change to something like this:
```
package main

import (
	"flag"
	"os"

	"github.com/hashicorp/vault/api"
	"github.com/hashicorp/vault/command"
)

// Client creates a new client for Vault which loads configuration
// settings from the environment and potentially looks up a token
// in ~/.vault_token for authentication.
func client() (*api.Client, error) {
	c, err := api.NewClient(nil)
	if err != nil {
		return nil, err
	}
	if c.Token() == "" {
		th, err := command.DefaultTokenHelper()
		if err != nil {
			return nil, err
		}
		t, err := th.Get()
		if err != nil {
			return nil, err
		}
		c.SetToken(t)
	}
	return c, nil
}

var flags = flag.NewFlagSet(os.Args[0], flag.ExitOnError)

func main() {
	var f bool
	flags.BoolVar(&f, "f", false, "my flag")
	flags.Parse(os.Args[1:])

	client()
	// use the client for something useful
}
```

**Comment by jefferai** [comment]
I think using a FlagSet is the way to go. Having exported testing functions is done throughout Vault and I don't see a good way to refactor these, so an easy workaround on your end seems like the right approach.
