### ISSUE TITLE
Feature Request - AWS Secret Backend: Policy support to STS

### ISSUE THREAD

**Issue by flyinbutrs** [hashicorp/vault#3751]
**Feature Request:**

The AWS Secret Backend supports STS for cross account privileges. However, if you try to provide both an ARN and a Policy when defining a role, it does not accept it, returning the error "Only one of policy or arn should be provided". The STS API supports overlay policies for restricting access to cross account roles. This provides for the ability to give least privileges credentials to multiple accounts without having to create a role in each account for each permission.

[Documentation of inputs in SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/sts/#AssumeRoleInput)

**Comment by joelthompson** [comment]
Hey @flyinbutrs -- I have a PR in #4360 that should support this use case (with an RFC in #4229 that should explain the desired behavior without having to read through the code). I'd love feedback on the approach!
