### ISSUE TITLE
TLS certificate auth allowed_names breaks if client presents cert chain

### ISSUE THREAD

**Issue by thardie** [hashicorp/vault#3758]
**Environment:**

* Vault Version: Vault v0.9.1
* Operating System/Architecture: Linux/amd64/Ubuntu 16.04

**Expected Behavior:**

Authenticate to vault (/auth/cert/login) presenting client cert with full chain (client cert, intermediate and root) and allowed_names matches the CN of the first certificate in the list.

**Actual Behavior:**
vault auth -method=cert -ca-cert=<ca cert file> -client-cert=<client cert only> -client-key=<client key>

works fine. This is because the vault client only sends the specified certificate. 

If you use other implementations to connect to vault, such as openssl s_client or python's requests library, they will send the client cert along with any intermediate and root certs for the client's certificate. In this case, the vault server allowed_names doesn't match the CN of the first certificate in the list.

Both openssl s_client and python's requests library do not give you control of sending the whole chain and cannot be configured to send only the client cert.

**Steps to Reproduce:**
- Configure a CA certificate auth role (/auth/cert/certs/:name) with an allowed_names set to a name that you will use in a client certificate
- Build a client certificate with a name listed in the allowed_names
- Construct local client cert file with full chain in 1 file (IE, client cert, followed by intermediate, followed by root cert)
- Execute: vault auth -method=cert -ca-cert=<ca cert file> -client-cert=<client cert file with full chain> -client-key=<client key>
- Vault fails to match configured CA auth.

**Comment by jefferai** [comment]
I don't see anything immediately obvious. The RFC (https://tools.ietf.org/html/rfc5246#section-7.4.2) specifies that the certificate to be validated must be the first certificate present in the certificates sent to the server. That's the certificate that we look at and we treat any others in the message as a validating certificate in the chain. This matches the Go verification logic. So appending more certificates to the chain should have no effect here.

How are you generating the client cert? Any chance you can send me the specific chain, including key, for analysis and testing?

**Comment by thardie** [comment]
I'm using Vault to generate the cert. I reached this conclusion by comparing TCP dumps of a successful case with a failed case, and the only difference I observed was that the vault client sent only the cert, whereas other clients sent the full chain.

In my setup, I have a self-signed root cert (not publically trusted). I issued a CSR from vault, and signed it with my root cert, and loaded that back into vault. I'm using that cert in vault to sign my client certs, so my chains are 3 certs long (root->vault intermediate CA->client).

I think for you to reproduce my fault, you'd need my intermediate and it's key. Let me see if I can simplify the setup to reproduce where I can send you all the keys and certs. I'll plan to get back to you today.

**Comment by jefferai** [comment]
`root->vault intermediate CA->client`
But in the PEM file it's in opposite order, right? (It should be.)

**Comment by thardie** [comment]
Absolutely! :D

**Comment by thardie** [comment]
Also, for my python client and openssl, I can't stop it sending the chain. I give it my client cert, and l need to give it the intermediate and root to validate the vault server's identity, and it decides to send the chain for the client cert on its own. If I could disable that behavior, I could work around the bug

**Comment by jefferai** [comment]
Totally understood. I just can't see anything obvious as to why this wouldn't work and I'm quite slammed right now so getting me certs/commands I can easily test with would definitely help :-)

**Comment by thardie** [comment]
No problem. I'll build you a complete cert set and example python code to demonstrate

**Comment by jefferai** [comment]
@thardie is this still an issue?

**Comment by thardie** [comment]
It is. We just haven't had time to reproduce this in an isolated system. We were either going to put together a set of keys and certs to demonstrate the issue, or just troubleshoot it in our current environment, fix it and put forward a patch.

**Comment by jefferai** [comment]
OK -- will slot onto the next milestone then.

**Comment by jefferai** [comment]
Please poke us to reopen if you can come up with a reproducible test case.

**Comment by thardie** [comment]
I'll abandon this issue. I wasn't able to reproduce it in a controlled environment.

I was able to work around this requirement with something I think would be far more useful. Please see my pull request #4157 which will enable the functionality I need.
