### ISSUE TITLE
Everytime i restart the linux server, all my secrets in IDM Vault are wiped out.  Basically curl http://127.0.0.1:8200/v1/sys/init return initialized as false. any advice on this ?

### ISSUE THREAD

**Issue by ap61687** [hashicorp/vault#3775]
**Environment:**

* Vault Version: Vault v0.9.1 ('87b6919dea55da61d7cd444b2442cabb8ede8ab1')
* Operating System/Architecture:  Fedora 26 Server edition

**Vault Config File:**
storage "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
}

listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
}

**Startup Log Output:**
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: 
                   Mlock: supported: true, enabled: true
        Redirect Address: http://127.0.0.1:8200
                 Storage: consul (HA available)
                 Version: Vault v0.9.1
             Version Sha: 87b6919dea55da61d7cd444b2442cabb8ede8ab1

==> Vault server started! Log data will stream in below:

2018/01/11 14:19:21.843083 [WARN ] physical/consul: appending trailing forward slash to path
2018/01/11 14:19:47.862017 [INFO ] core: security barrier not initialized

**Expected Behavior:**
I store few encryption keys and after Linux server restart, I expect them to be accessible 

**Actual Behavior:**
curl http://127.0.0.1:8200/v1/sys/init returns initialized as false

**Steps to Reproduce:**
1. initialize vault
2. unseal valut
3.store the secrets
4.restart linux box
5.reading the secret keys fails

**Important Factoids:**

**References:**

**Comment by ap61687** [comment]
I use Vault v0.9.1 version

**Comment by chrishoffman** [comment]
Can you please fill out the issue form with the requested information? It would specifically be helpful to know the contents of your vault config file, startup logs, and the command to run vault to help diagnose the issue you are facing.

**Comment by chrishoffman** [comment]
Thanks for the info.  How are you running consul?  It seems to me your consul server may be running in an in-memory mode and when you restart are getting a fresh datastore.  Have you tried any other storage backend?  Maybe try the file storage backend and see if you get the same results.

**Comment by ap61687** [comment]
I'm using the below command to start consul:
consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul -bind 127.0.0.1

**Comment by chrishoffman** [comment]
It depends on the Linux distribution (I am not sure about Fedora) but /tmp often gets cleared on boot.  Try moving your Consul data directory to another location.

**Comment by ap61687** [comment]
Thanks a lot for the help! It works fine once I change consul data path.

**Comment by chrishoffman** [comment]
Great! Glad to help.
