### ISSUE TITLE
Plugin Catalog doesn't round trip, therefore doesn't work with terraform.

### ISSUE THREAD

**Issue by tomwilkie** [hashicorp/vault#3776]
If I put some plugin JSON into the catalog, then read it back out, the JSON has been modified:
- The vault plugin dir has been prepended to the path.
- The sha256 has been base64 encoded
- Args have been broken out from command into a list.
- `"builtin": false` is added.

Eg:
```
$ cat plugin.json 
{
  "command": "google-auth-vault-plugin --ca-cert=/etc/vault/ca.pem --client-cert=/etc/vault/cert.pem --client-key=/etc/vault/key.pem",
  "name": "google-auth-vault-plugin",
  "sha256": "989845e5a0171d9e1b1c6d9ca13393dd031fd9068c200c52ec723737ed450d4d"
}
$ vault write sys/plugins/catalog/google-auth-vault-plugin @plugin.json
Success! Data written to: sys/plugins/catalog/google-auth-vault-plugin
$  vault read -format=json sys/plugins/catalog/google-auth-vault-plugin 
{
	"request_id": "d83dcd72-48a6-0c37-f9f8-13128d62e086",
	"lease_id": "",
	"lease_duration": 0,
	"renewable": false,
	"data": {
		"args": [
			"--ca-cert=/etc/vault/ca.pem",
			"--client-cert=/etc/vault/cert.pem",
			"--client-key=/etc/vault/key.pem"
		],
		"builtin": false,
		"command": "/etc/vault-plugins/google-auth-vault-plugin",
		"name": "google-auth-vault-plugin",
		"sha256": "mJhF5aAXHZ4bHG2coTOT3QMf2QaMIAxS7HI3N+1FDU0="
	},
	"warnings": null
}
```

The makes it super hard to manage plugins with terraform, as it needs to read back the JSON and compare it to see if it needs updating:

```
* vault_generic_secret.google_plugin_sha: error writing to Vault: Error making API request.

URL: PUT https://vault.uswest-cluster.aws.grapeshot.co.uk:8200/v1/sys/plugins/catalog/google-auth-vault-plugin
Code: 500. Errors:

* 1 error occurred:

* error while validating the command path: lstat /etc/vault-plugins/etc: no such file or directory
```

Suggestions:
- We don't leak the vault plugin dir when we read back
- We don't base64 encode the sha in the result
- We optionally accept arguments as an args list.

Thoughts?  I'm going to start a PR for this.

**Comment by tomwilkie** [comment]
Looks like the path issue was fixed in https://github.com/hashicorp/vault/pull/2200, but I'm still seeing it in 0.9.1...  weird.

**Comment by tomwilkie** [comment]
Ah I see, its being added back in in `PluginCatalog.Get`: https://github.com/hashicorp/vault/commit/17bea6540bfb800a91463bbaaf992bf402521645

**Comment by paolodr** [comment]
Hi I see this problem closed, but I have a similar situation with version 1.3

After changing the server configuration from HTTP to HTTPS I'm not able to install the plugin.

**[root@vault1 ~]# vault write sys/plugins/catalog/secrets-gen \
>     sha_256="${SHA256}" \
>     command="vault-secrets-gen"
Error writing data to sys/plugins/catalog/secrets-gen: Error making API request.

URL: PUT https://<HOSTNAME>:8200/v1/sys/plugins/catalog/secrets-gen
Code: 500. Errors:

* 1 error occurred:

* error while validating the command path: lstat /etc/vault/plugins/vault-secrets-gen: no such file or directory**


It was installed with no problem when it was HTTP

Note that I'm running on RH7

1.  **ls -la /etc/vault/plugins/vault-secrets-gen**
-rwxrwxrwx 1 vault vault 10792960 Sep 17 15:06 /etc/vault/plugins/vault-secrets-gen

2. **lstat /etc/vault/plugins/vault-secrets-gen**
-bash: lstat: command not found

3. **stat /etc/vault/plugins/vault-secrets-gen**
  File: ‘/etc/vault/plugins/vault-secrets-gen’
  Size: 10792960  	Blocks: 21080      IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 135358957   Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (  996/   vault)   Gid: (  992/   vault)
Access: 2019-12-17 16:47:59.648753680 -0500
Modify: 2019-09-17 15:06:05.114094711 -0400
Change: 2019-12-17 16:24:39.357357684 -0500

Current VAULT config

listener "tcp" {
   address          = "0.0.0.0:8200"
   cluster_address  = "<IP ADDRESS>5:8201"
   tls_disable      = 0
   tls_cert_file    = "/etc/vault/ssl/certificate.pem"
   tls_key_file     =  "/etc/vault/ssl/certificate.key"
   tls_disable_client_certs = true
}

api_addr         = "https://<HOSTNAME>:8200"
cluster_address  = "https://<HOSTNAME>:8201"
plugin_directory = "/etc/vault/plugins/"
cluster_name         = "vault"
raw_storage_endpoint     = true
disable_sealwrap     = true
disable_printable_check = true
