### ISSUE TITLE
Allow setting Country, State and Locality in PKI Roles

### ISSUE THREAD

**Issue by mparaz** [hashicorp/vault#3777]
Some organisations would like to have the C= ST= L= in the subject for the issued certificates.

Thanks!

**Comment by benjumanji** [comment]
You can do this today if you are willing to generate the csr yourself and use the sign-verbatim endpoint. I'd agree that in general better support for various flavours of X.500 names in the pki backend would be much appreciated.

**Comment by jefferai** [comment]
This is supported now via #3992
