### ISSUE TITLE
Having PKI enabled leads to endless cycle of unseal retries.

### ISSUE THREAD

**Issue by ror6ax** [hashicorp/vault#3780]
Hi guys!

Having PKI set up and some certs being generated.
After sealing, and attempt of unseal I see this in the log:

```
2017/12/28 10:40:15.510833 [INFO ] core: pre-seal teardown complete
2017/12/28 10:40:15.510878 [ERROR] core: post-unseal setup failed: error=failed to setup mount table
```

We've verified that if PKI entries are purged before sealing prevents this from happening.

Tried with Vault `v0.8.3` and `v0.9.3`
Storage back-end is Zookeeper.

**Comment by jippi** [comment]
I assume 0.9.3 was Consul not Vault ;)
