### ISSUE TITLE
using vault on web server

### ISSUE THREAD

**Issue by 7c** [hashicorp/vault#3784]
I am running and testing v0.9.1. I like it so far but i want to have an expert opinion how to deploy vault inside web scripts.

We do have php based REST API and as you know php is launched per request. So if i use php-sdk this would require to hit my remotely hosted vault on every request. I think to hit the vault on every web request is not the optimal way.

Do i really have only 2 options now?

- Upgrade to Enterprise in order to have local copy of the vault 
- Implement my own caching around php-sdk

Any comments are appreciated.

**Comment by taskinosman** [comment]
Just to have it here for other people, i am testing nginx response caching solution with this snippet:

```
proxy_cache_path  /tmp/cache keys_zone=one:10m;
server {
	listen 81 default_server;
	listen [::]:81 default_server;

	root /var/www/html;

	server_name _;

	proxy_cache one;

	location /v1/secret/ {
		proxy_cache one;
		proxy_cache_key $scheme$proxy_host$uri/$http_x_vault_token/$is_args$args/$http_user_agent;
		proxy_pass https://vault.com:8200/v1/secret/;
	   	proxy_cache_use_stale updating;
	    	proxy_cache_valid 200 2m;
	    	proxy_cache_valid 404 1m;
		proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
	}


        location / {
                proxy_pass https://vault.com:8200/;
        }

}
```

This snippet is there to cache responses to vault.com:8200 where i do have another nginx proxy which is ssl terminating reverse proxy. I am still experimenting but this snippet does cache all /secret requests for 2minutes and 404 1 minute. This snippet is still too experimental. proxy_cache_key also contains the x-vault-token and user-agent. 

After starting this i am setting VAULT_ADDR="http://127.0.0.1:81" and do work with vault as normal. Of course this cache is always behind the updates but if one does not expect too many updates, this might be a good solution.

**Comment by catsby** [comment]
Hello - 

I would imagine that only php files that directly interact with Vault would then reach out to vault on request. Depending on how you structure your application of course...

I apologize that it's been so long before you received any reply. If this is still something you're interested in figuring out, or perhaps you have and would like to share, then I encourage you to do so on our community site:

- https://discuss.hashicorp.com/c/vault

I'm going to close this for now, as it's not an issue with Vault itself. Thanks!
