### ISSUE TITLE
v0.9.1: In AWS auth role for periodic token sets explicit max ttl 

### ISSUE THREAD

**Issue by shayangz** [hashicorp/vault#3786]
**Environment:**

* Vault Version: 0.9.1
* Operating System/Architecture: Ubuntu 16.04

**Expected Behavior:**
Create a role with AWS Auth backend to issue periodic tokens that never expire as long as they are renewed within the `period` time.

**Actual Behavior:**
In version 0.8.2 this was working properly. Once we upgraded to 0.9.1, we noticed that tokens expire even when they are being renewed.

**Steps to Reproduce:**
Digging in a bit more, it looks like in 0.9.1, a `max_ttl` is set to `86400` even when no such value is provided creating the role.

* 0.9.1 *
```
$vault write auth/aws/role/test-role auth_type=iam inferred_entity_type=ec2_instance inferred_aws_region=us-west-2 bound_iam_instance_profile_arn=arn:aws:iam::XXX:instance-profile/XXX policies=XXX bound_vpc_id=vpc-XXX period=6h
Success! Data written to: auth/aws/role/test-role

$vault read auth/aws/role/test-role
Key                           	Value
---                           	-----
allow_instance_migration      	false
auth_type                     	iam
bound_account_id
bound_ami_id
bound_iam_instance_profile_arn	arn:aws:iam::XXX:instance-profile/XXX
bound_iam_principal_arn
bound_iam_principal_id
bound_iam_role_arn
bound_region
bound_subnet_id
bound_vpc_id                  	vpc-XXX
disallow_reauthentication     	false
inferred_aws_region           	us-west-2
inferred_entity_type          	ec2_instance

max_ttl                       	86400

period                        	21600
policies                      	[XXX]
resolve_aws_unique_ids        	false
role_tag
ttl                           	0
```

* 0.8.2 *
```
$vault write auth/aws/role/test-role auth_type=iam inferred_entity_type=ec2_instance inferred_aws_region=us-west-2 bound_iam_instance_profile_arn=arn:aws:iam::XXX:instance-profile/XXX policies=XXX bound_vpc_id=vpc-XXX period=6h
Success! Data written to: auth/aws/role/test-role

$vault read auth/aws/role/test-role
Key                           	Value
---                           	-----
allow_instance_migration      	false
auth_type                     	iam
bound_account_id
bound_ami_id
bound_iam_instance_profile_arn	arn:aws:iam::XXX:instance-profile/XXX
bound_iam_principal_arn
bound_iam_principal_id
bound_iam_role_arn
bound_region
bound_subnet_id
bound_vpc_id                  	vpc-XXX
disallow_reauthentication     	false
inferred_aws_region           	us-west-2
inferred_entity_type          	ec2_instance

max_ttl                       	0

period                        	21600
policies                      	[XXX]
resolve_aws_unique_ids        	true
role_tag
ttl                           	0
```

**Comment by shayangz** [comment]
looks like inconsistent data through an upgrade. not all roles show this symptom. will try explicitly setting the value to 0 on the ones who do and see if it solves the problem.

**Comment by jefferai** [comment]
I don't see this max_ttl behavior on a dev instance (it reads back as zero), so maybe you are indeed hitting an old bug. Note that it will only update the existing value if it's set, so if you add max_ttl=0 to your role write command it should replace what's there.

I don't see anywhere in the code it wouldn't be honoring the period though. Have you tested this out, is the period correctly working?

cc'ing @calvn

**Comment by shayangz** [comment]
@jefferai that's exactly what I did. Rewrote the roles with `max_ttl=0` and seems to have worked fine. Not sure where the `86400` came from either.

**Comment by jefferai** [comment]
Great!
