### ISSUE TITLE
error when generating key pair of postgresql

### ISSUE THREAD

**Issue by iris-h-wen** [hashicorp/vault#3789]
I try to generate key pair base on the url 
https://www.vaultproject.io/docs/secrets/databases/postgresql.html 

when I run "vault read database/creds/readonly" , I got below error:

Error reading database/creds/readonly: Error making API request.

URL: GET http://127.0.0.1:8200/v1/database/creds/readonly
Code: 500. Errors:

* 1 error occurred:

* pq: syntax error at or near "'v-root-readonly-v031vtw39px18076xq5t-1516004845'"

Could you all help on this ? what is happened on this ?

****below is my commands*******
$> vault write database/config/postgresql plugin_name=postgresql-database-plugin  allowed_roles="readonly" connection_url="postgres://postgres:pwd@localhost:5432/db_name?sslmode=disable"
$> vault write database/roles/readonly db_name=postgresql creation_statements="CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT SELECT ON *.* TO '{{name}}'@'%';" default_ttl="1h"  max_ttl="24h"

$> vault read database/creds/readonly

**Comment by jefferai** [comment]
Hi there,

You are using MySQL creation statements with PostgreSQL. You will need to use appropriate Postgres creation statements; see https://www.vaultproject.io/docs/secrets/databases/postgresql.html for some examples.

**Comment by iris-h-wen** [comment]
Thanks jefferai , it worked.
