### ISSUE TITLE
[improvement] Add prefix_filter option for telemetry

### ISSUE THREAD

**Issue by stevenscg** [hashicorp/vault#3792]
Consul has the "prefix_filter" option to allow filtering of the telemetry, which is great for controlling costs and noise.

We use a hosted metrics provider that bills on the number of unique metrics streams submitted.

There are some telemetry items like `vault.route.*` that we don't use right now and it would be ideal to not have to pay for those until or unless we need them.

**Comment by pmmukh** [comment]
This change has been added in https://github.com/hashicorp/vault/pull/12025
