### ISSUE TITLE
Please review node-vault

### ISSUE THREAD

**Issue by DaniGuardiola** [hashicorp/vault#3794]
I recently refactored `node-vault`. I would appreciate a review by the vault team. Any input is appreciated, feature suggestions, code review, anything :)

I am gonna keep working and maintaining this module in the future, after the refactor, so feel free to add long-term or complex ideas for consideration.

[The branch with the latest changes](https://github.com/DaniGuardiola/node-vault/tree/refactor)
[Pull request](https://github.com/kr1sp1n/node-vault/pull/78)
[Issue with relevant discussion around the modernization of the module](https://github.com/kr1sp1n/node-vault/issues/76)
[AWS EC2 auth integration](https://github.com/kr1sp1n/node-vault/issues/57) - [issue where it was initially discussed](https://github.com/kr1sp1n/node-vault/issues/57)

Thanks in advance!! ^^

**Comment by catsby** [comment]
Hey @DaniGuardiola  - I apologize for the very, _very_, late reply. Unfortunately reviewing external repositories is not something we have the bandwidth to lend at this time. We do appreciate the work you've done to maintain an external client for interacting with Vault, and apologize again for not getting back to you sooner. 

Cheers!
