### ISSUE TITLE
CRL Next Update Time Not Being Updated

### ISSUE THREAD

**Issue by ekristen** [hashicorp/vault#3827]
It seems that Vault doesn't actually update the CRL next update date if you haven't actually revoked a certificate, which leads to clients failing to validate issued certificates against the CRL because it's expired.

* Vault Version: 0.8.0
* Operating System/Architecture: Ubuntu 16.04

**Expected Behavior:**
Expect Next Update Date on the CRL to be updated so it stays valid.

**Actual Behavior:**
The CRL is not being updated with a new date, so verification now fails because the next update has passed. Expect that the CRL is updated periodically.

Recommend: CRL expiry time / 2 as the update interval.

**Steps to Reproduce:**
(working on this)

**Comment by jefferai** [comment]
See https://www.vaultproject.io/api/secret/pki/index.html#rotate-crls -- this endpoint is here specifically for this purpose. You can rotate on any interval you like via e.g. a cron job. A token for this job can be limited in scope specifically to this endpoint.

**Comment by frankfarmer** [comment]
Is vault's implementation potentially out of spec here?

https://www.ietf.org/rfc/rfc3280.txt

    5.1.2.5  Next Update

       This field indicates the date by which the next CRL will be issued.
       The next CRL could be issued before the indicated date, but it will
       not be issued any later than the indicated date.  CRL issuers SHOULD
       issue CRLs with a nextUpdate time equal to or later than all previous
       CRLs.  nextUpdate may be encoded as UTCTime or GeneralizedTime.

> The next CRL... will not be issued any later than the indicated date

**Comment by jefferai** [comment]
It's SHOULD, not MUST.

Vault only issues new CRLs when it would result in a different CRL, as in, the serial numbers have changed.

**Comment by frankfarmer** [comment]
I'm more curious about the "will not" than the "SHOULD".

The trouble is, many implementations (like openvpn) refuse to operate with an expired CRL.  So while a newly-issued CRL might have the same content, an expired CRL is completely worthless to many CRL consumers.

**Comment by jefferai** [comment]
You can rotate it any time you wish via `crl/rotate`, which will create a new CRL with an expiry configured via `config/crl`, defaulting to 72 hours.
