### ISSUE TITLE
Support for secp256k1

### ISSUE THREAD

**Issue by benjumanji** [hashicorp/vault#3846]
**Feature Request:**

How realistic is it that we could see the k1 curve make it into vault? Basically I would love to use vault as a backend for cryptocurrency wallets, but they almost all use the k1 curve, not the r1 curve. I would be happy to take a crack at it, but I am not an expert and so I doubt that kind of thing would get accepted, and if it were it might end up making net more effort for person reviewing it than if they wrote it themselves.

**Comment by jefferai** [comment]
The main issue I see with this at the moment is finding a library to do these operations that doesn't rely on cgo. I have no philosophical reasons to not support it (and would like to) otherwise.

**Comment by benjumanji** [comment]
Ok, that's encouraging! I'll keep looking around.

**Comment by jefferai** [comment]
I'm going to close this for now. Usage of secp256k1 outside Bitcoin seems limited (and generally not recommended) and without suitable libraries it's a moot point anyways.
