### ISSUE TITLE
is there any timeout associated between the keys when Vault is unsealed using unsealed keys. Since Vault requires atleast 3 keys to unseal, is there any time window we need to consider to enter 2nd unseal and subsequently 3rd key. if yes, what is the default time out period. 

### ISSUE THREAD

**Issue by ap61687** [hashicorp/vault#3853]
**Environment:**

* Vault Version:
* Operating System/Architecture:

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

**Actual Behavior:**

**Steps to Reproduce:**

**Important Factoids:**

**References:**

**Comment by jefferai** [comment]
No.

**Comment by ap61687** [comment]
is it possible to configure a time out period between the keys.

**Comment by jefferai** [comment]
No.
