### ISSUE TITLE
Support using --field parameter after location

### ISSUE THREAD

**Issue by alvaroaleman** [hashicorp/vault#3857]
**Feature Request:**

Right now it is only possible to use the `--field` parameter before specifying the secret location, e.G. `vault read --field=password secret/myaccount`.

It would be awesome if it would be possible to do it the other way round, e.G. `vault read secret/myaccount --field=password`. The most awesomeness would be if the vault cli was able to complete the value of the field parameter in such a situation.

Thanks btw for the great work in improving the CLI in 0.9.2!

**Environment:**

```
vault version
Vault v0.9.2 ('3bf8733cd69bb0ac14da9aaa6135bcb7f710cc5f')
```

**Comment by jefferai** [comment]
Sorry, but this will not be implemented. It is also not possible to auto complete these fields since the CLI doesn't know what engine it's talking to or the paths.
