### ISSUE TITLE
nomad backend type unknow in vault 0.9.2

### ISSUE THREAD

**Issue by groggemans** [hashicorp/vault#3858]
**Environment:**

* Vault Version: 0.9.2
* Operating System/Architecture: linux x86_64

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

Vault should be able to add a nomad secrets engine (which was introduced in 0.9.1) to manage nomad tokens.

**Actual Behavior:**

Vault won't come up when updating from 0.9.1 (high cpu + constant errors after unsealing) when there was a nomad secrets engine enabled. It's also not possible to add a nomad secrets engine if there was none mounted/enabled.

**Steps to Reproduce:**

Install vault 0.9.2 (I'm running the docker image) and try to add the nomad secrets engine.

```
user@computer:  vault status
Key             Value
---             -----
...         ...
Version         0.9.2
...         ...
user@computer:  vault secrets enable nomad
Error enabling: Error making API request.

URL: POST http://vault:8200/v1/sys/mounts/nomad
Code: 400. Errors:

* unknown backend type: nomad
```

**Important Factoids:**

**References:**

**Comment by jefferai** [comment]
Going to issue 0.9.3 today to address this.
