### ISSUE TITLE
Vault is killed when trying to restore leases at startup

### ISSUE THREAD

**Issue by weisinc** [hashicorp/vault#3860]
I am facing an issue where the Vault process keeps getting killed as soon as I unsealed it. Below are the logs. Seems like it is trying to restore the releases and before it is done. the process is killed. I say that because I restarted Vault and unsealed it a number of times and each time the # of restored_lease_count is the same. I don't see anything else in the logs.  Any idea why this is happening?

Vault 0.8.1
Backend is Consul 0.8.4

2018/01/29 06:15:00.711804 [INFO ] core: vault is unsealed
2018/01/29 06:15:00.711985 [INFO ] core: entering standby mode
2018/01/29 06:15:00.733008 [INFO ] core: acquired lock, enabling active operation
2018/01/29 06:15:00.779952 [INFO ] core: post-unseal setup starting
2018/01/29 06:15:00.781741 [INFO ] core: loaded wrapping token key
2018/01/29 06:15:00.785580 [INFO ] core: successfully mounted backend: type=generic path=secret/
2018/01/29 06:15:00.785794 [INFO ] core: successfully mounted backend: type=system path=sys/
2018/01/29 06:15:00.785904 [INFO ] core: successfully mounted backend: type=transit path=transit/
2018/01/29 06:15:00.786060 [INFO ] core: successfully mounted backend: type=database path=mariadb_tier1/
2018/01/29 06:15:00.786093 [INFO ] core: successfully mounted backend: type=consul path=consul/
2018/01/29 06:15:00.786140 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2018/01/29 06:15:00.786228 [INFO ] rollback: starting rollback manager
2018/01/29 06:15:00.794944 [INFO ] expiration: restoring leases
2018/01/29 06:15:21.337631 [INFO ] expire: leases restored: restored_lease_count=61862
Killed

**Comment by chrishoffman** [comment]
I notice that in your mail list post that you are also running this under Kubernetes. The "Killed" message is not coming from vault. Do you see anything in your Kubernetes or Docker logs?  While leases are being loaded, Vault is unable to serve requests while loading leases and depending on your health checks it may think that Vault is dead. 

I would recommend updating to the latest version of vault which includes many fixes that could help this issue, most significantly lazy lease loading.

**Comment by weisinc** [comment]
It turns out to be a resource problem. I bumped up the resources (Cores and Memory) for the container and it started running again.

Thanks, Chris for getting back. I look forward to upgrading to the 0.9.x
