### ISSUE TITLE
Can't revoke lease 403 permission denied

### ISSUE THREAD

**Issue by samirshamsi100** [hashicorp/vault#3864]
Version: Vault v0.9.3

I am using kubernetes authentication and postgres backend as follows:

The kubenetes token generates a lease on the postgres backend  and credentials.

In the spring vault integration startup is fine and the DB is accessible using the credentials (i.e. table and data are created at startup).

But when spring tries to revoke/renew the lease it get s the below error: (I am new to vault)

PUT request for "https://vault.vault.svc.cluster.local:8200/v1/sys/revoke/database/creds/pg-readwrite/dca71686-0fba-ea26-a837-22a908c4edc3 " resulted in 403 (Forbidden); invoking error handler
2018-01-29 20:41:41.314 WARN 1 --- [ Thread-5] LeaseEventPublisher$LoggingErrorListener : [RequestedSecret [path='database/creds/pg-readwrite', mode=RENEW]] Lease [leaseId='database/creds/pg-readwrite/dca71686-0fba-ea26-a837-22a908c4edc3', leaseDuration=2592000, renewable=true] Status 403: permission denied

**Comment by chrishoffman** [comment]
I don't know much about the spring integration but what are the policies associated with the token? Does the token have permissions to write to `sys/revoke/database/creds/pg-readwrite/*`?

**Comment by sebastianortizsantacruz** [comment]
I have the same issue with spring cloud vault integration, IAM authentication and mongodb. Initially works fine but when it need a renew, the follow error appears: 

2018-05-08 14:15:30.537  WARN 1 --- [g-Cloud-Vault-1] LeaseEventPublisher$LoggingErrorListener : [RequestedSecret [path='database/creds/mongodb-eservices-role', mode=RENEW]] Lease [leaseId='database/creds/mongodb/TOKEN', leaseDuration=3600, renewable=true] Status 403: permission denied

org.springframework.vault.VaultException: Status 403: permission denied ....

My policies defined on my IAM role are:
* vault
path \"database/*\" {capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\"]}
* database
path \"secret/*\" {capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\"]} "}
* default

Any ideas?

**Comment by samirshamsi100** [comment]
The did this project a few months ago. But was able to solve my problem by creating the db schema with a different user than than the user used for the token. Since postgres in my case did not allow the user to be deleted since there were dependent tables which could not be deleted.

**Comment by michelvocks** [comment]
Hi there!

I will close this issue since it appears to me that problem has been solved. Feel free to open a new issue if this is still a problem for you.

Cheers,
Michel

**Comment by mootezbessifi** [comment]
@samirshamsi100 @sebastianortizsantacruz please any fix since i am facing the same error ?

**Comment by shaolinrabbi** [comment]
@mootezbessifi, in my case it happened on shutdown. I assume it was because the application tried to revoke the lease. To allow the application apply such action you need to give it permission to sys/leases/revoke with update capability. This doesn't appear in the default policy.

```
path "sys/leases/revoke" {
  capabilities = ["update"]
}
```
