### ISSUE TITLE
Vault does not advertise address properly to consul

### ISSUE THREAD

**Issue by samrocketman** [hashicorp/vault#3866]
# Bug details

**BUG encountered:**

If vault doesn't know what to advertise to consul, then the service registration of the consul DNS returns the consul host instead of the actual vault server.

**Bugfix/Feature Request:**

Have vault advertise the proper IP address of the default route to consul.  When I log into the environment `ifconfig` and `ip addr` returns a proper IP address.

**Other related issues found:**

* https://github.com/hashicorp/vault/issues/1528

# Environment

<details><summary>Click to expand environment details</summary>

Docker Compose with a custom network defined for proper connectivity.

Source code: https://gist.github.com/samrocketman/a0f24301f6de59a3d4159f2477f65dce

```
docker-compose up -d
#or alternatively HA vault
docker-compose up --scale vault=3 -d
```

* Vault Version: `Vault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')`
* Operating System/Architecture: Docker for Mac

```
Docker 17.12.0-ce
Docker compose 1.18.0
Docker Machine 0.13.0
Linux Kernel 4.9.60
```

**Vault Config File:**

Refer to my gist under the `vault` service key:

```
 VAULT_LOCAL_CONFIG: '{"backend": {"consul": {"address": "consul:8500", "path":"vault", "scheme": "http"}}, "listener": {"tcp":{"address": "0.0.0.0:8200","tls_disable":"1"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h", "disable_mlock": "true"}'
```

</details>

# Startup Log Output

<details><summary>Click to expand startup log output</summary>

```
Couldn't start vault with IPC_LOCK. Disabling IPC_LOCK, please use --privileged or --cap-add IPC_LOCK
[0;0m==> Vault server configuration:
[0m
[0;0m                     Cgo: disabled[0m
[0;0m         Cluster Address: https://172.16.238.3:8201[0m
[0;0m              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "disabled")[0m
[0;0m               Log Level: info[0m
[0;0m                   Mlock: supported: true, enabled: false[0m
[0;0m        Redirect Address: http://172.16.238.3:8200[0m
[0;0m                 Storage: consul (HA available)[0m
[0;0m                 Version: Vault v0.9.3[0m
[0;0m             Version Sha: 5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d[0m
[0;0m[0m
[0;0m==> Vault server started! Log data will stream in below:
2018/01/30 09:21:01.155444 [WARN ] physical/consul: appending trailing forward slash to path
[0m
2018/01/30 09:21:05.835837 [WARN ] physical/consul: check unable to talk with Consul backend: error=Unexpected response code: 500 (CheckID "vault:172.16.238.3:8200:vault-sealed-check" does not have associated TTL)
2018/01/30 09:21:52.188954 [INFO ] core: security barrier not initialized
2018/01/30 09:21:52.214381 [INFO ] core: security barrier initialized: shares=5 threshold=3
2018/01/30 09:21:52.264871 [INFO ] core: post-unseal setup starting
2018/01/30 09:21:52.285278 [INFO ] core: loaded wrapping token key
2018/01/30 09:21:52.285328 [INFO ] core: successfully setup plugin catalog: plugin-directory=
2018/01/30 09:21:52.300275 [INFO ] core: successfully mounted backend: type=kv path=secret/
2018/01/30 09:21:52.300329 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2018/01/30 09:21:52.300452 [INFO ] core: successfully mounted backend: type=system path=sys/
2018/01/30 09:21:52.300678 [INFO ] core: successfully mounted backend: type=identity path=identity/
2018/01/30 09:21:52.331594 [INFO ] expiration: restoring leases
2018/01/30 09:21:52.331867 [INFO ] rollback: starting rollback manager
2018/01/30 09:21:52.332639 [INFO ] expiration: lease restore complete
2018/01/30 09:21:52.343132 [INFO ] identity: entities restored
2018/01/30 09:21:52.343769 [INFO ] identity: groups restored
2018/01/30 09:21:52.344352 [INFO ] core: post-unseal setup complete
2018/01/30 09:21:52.344421 [INFO ] core/startClusterListener: starting listener: listener_address=0.0.0.0:8201
2018/01/30 09:21:52.344818 [INFO ] core/startClusterListener: serving cluster requests: cluster_listen_address=[::]:8201
2018/01/30 09:21:52.360794 [INFO ] core: root token generated
2018/01/30 09:21:52.360832 [INFO ] core: pre-seal teardown starting
2018/01/30 09:21:52.360847 [INFO ] core: stopping cluster listeners
2018/01/30 09:21:52.360858 [INFO ] core: shutting down forwarding rpc listeners
2018/01/30 09:21:52.360898 [INFO ] core: forwarding rpc listeners stopped
2018/01/30 09:21:52.845717 [INFO ] core: rpc listeners successfully shut down
2018/01/30 09:21:52.845821 [INFO ] core: cluster listeners successfully shut down
2018/01/30 09:21:52.845889 [INFO ] rollback: stopping rollback manager
2018/01/30 09:21:52.845995 [INFO ] core: pre-seal teardown complete
2018/01/30 09:22:10.807322 [INFO ] core: vault is unsealed
2018/01/30 09:22:10.807492 [INFO ] core: entering standby mode
2018/01/30 09:22:10.833456 [INFO ] core: acquired lock, enabling active operation
2018/01/30 09:22:10.876589 [INFO ] core: post-unseal setup starting
2018/01/30 09:22:10.877655 [INFO ] core: loaded wrapping token key
2018/01/30 09:22:10.877782 [INFO ] core: successfully setup plugin catalog: plugin-directory=
2018/01/30 09:22:10.881436 [INFO ] core: successfully mounted backend: type=kv path=secret/
2018/01/30 09:22:10.882199 [INFO ] core: successfully mounted backend: type=system path=sys/
2018/01/30 09:22:10.882777 [INFO ] core: successfully mounted backend: type=identity path=identity/
2018/01/30 09:22:10.882835 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2018/01/30 09:22:10.892004 [INFO ] expiration: restoring leases
2018/01/30 09:22:10.892371 [INFO ] rollback: starting rollback manager
2018/01/30 09:22:10.896761 [INFO ] expiration: lease restore complete
2018/01/30 09:22:10.897374 [INFO ] identity: entities restored
2018/01/30 09:22:10.898445 [INFO ] identity: groups restored
2018/01/30 09:22:10.899716 [INFO ] core: post-unseal setup complete
2018/01/30 09:22:10.899816 [INFO ] core/startClusterListener: starting listener: listener_address=0.0.0.0:8201
2018/01/30 09:22:10.900022 [INFO ] core/startClusterListener: serving cluster requests: cluster_listen_address=[::]:8201
```

</details>

# Behavior

<details><summary>Click to expand behavior details</summary>

**Expected Behavior:**

```
# setup
docker pull joffotron/docker-net-tools
docker run -it --dns 172.16.238.2 --network vaultconsului_internal joffotron/docker-net-tools
#look up consul DNS
dig +short consul.service.consul
dig +short active.vault.service.consul
```

`active.vault.service.consul` should return its own address which differs from `consul.service.consul`.  It returns the IP `172.16.238.3` which is the consul leader IP (not the vault client IP).

**Actual Behavior:**

`active.vault.service.consul` unfortunately returns the same IP as `consul.service.consul`.  So services using service discovery is searching for vault on port 8200 of the consul frontend.

</details>

# Reproduce

<details><summary>Click to expand reproduce details</summary>

### Prerequisites

* Install docker for mac.
* Ensure the following ports are free on your host: 8000, 8400, 8500, 8600, 9000.  Otherwise, docker-compose will fail to start the services which expose ports externally.

### Initialize the environment

```
mkdir vault-consul-ui
cd vault-consul-ui/
curl -sLO https://gist.githubusercontent.com/samrocketman/a0f24301f6de59a3d4159f2477f65dce/raw/e77dcff11f5f707350bdbe682d5303c40eca872d/docker-compose.yml

docker-compose up -d
```

When all of the services have started log into vault and initialize it.

```bash
docker exec -it vaultconsului_vault_1 sh
vault operator init
# enter keys to unseal vault
vault operator unseal
vault operator unseal
vault operator unseal
```

Visit http://localhost:8500/ui/ and see `vault` registered as a service.  It should be green.

<img width="1375" alt="screen shot 2018-01-30 at 2 25 17 am" src="https://user-images.githubusercontent.com/875669/35561374-f1e59aee-0564-11e8-9e87-1525bdae5604.png">

Now, pull down an image with nettools pre-installed and perform a DNS lookup.

```
docker pull joffotron/docker-net-tools
docker run -it --dns 172.16.238.2 --network vaultconsului_internal joffotron/docker-net-tools
```

Inside the nettools container, you'll see the following (incorrect) response from dig:

```bash
# dig +short active.vault.service.consul
172.16.238.3
```

</details>

**Comment by samrocketman** [comment]
Okay, I've finished updating the description.  Please note, I'm aware that I could set static IPs for vault in the `networks` key.  However, I want to maintain the flexibility of creating a HA Vault via:

```
docker-compose up --scale vault=3 -d
```

**Comment by jefferai** [comment]
This can be specifies with https://www.vaultproject.io/docs/configuration/index.html#api_addr

**Comment by samrocketman** [comment]
Actually, api_addr can't be when you're using scale.  Why immediately close without considering the implication of the issue?  @jefferai Please reopen this issue.  It's a legitimate bug for vault not to advertise the default route.

**Comment by samrocketman** [comment]
@jefferai I have figured out a workaround for this bug.  See https://github.com/samrocketman/docker-compose-ha-consul-vault-ui/commit/c6c88f67311b3a81ca7deca46fbfbc101d4dab38

However, I think you should reconsider opening this issue.  It's something which is easily resolved via normal networking APIs in the kernel.  I imagine this bug affects non-containerized environments as well.

**Comment by oliverjanik** [comment]
I've been trying to set up Vault for a few days with auto-scaling on and I have to say the stubbornness of the maintainers, especially @jefferai, really puts me off.

It seems maintainers have hard time understanding that not everyone wants to have a hand rolled n node vault cluster and m node consul cluster and babysit every individual node.

In my case I'd like auto-scaled setup in AWS ECS fargate backed by a managed database I don't have to think about such as DynamoDB.

The active vault clustering is incredibly complex and makes it a nightmare to get right. A good example is lackluster support for load-balancers.

**Comment by jefferai** [comment]
Hi there,

I haven't been a day to day maintainer of Vault for several years not, so I'm not sure what I've specifically done to frustrate you, but I am sorry you're frustrated.

If you're referring simply to the earlier comments on this issue, it is entirely likely that I simply did not see the reply asking for it to be reopened after I'd thought I'd given an answer that would help the OP. At that point in time the Vault team was very small and I was trawling through hundreds of emails and GitHub notifications per week, and sometimes per day.

If you're having some troubles, I encourage you to file an issue with your specific issues and someone on the Vault team can help you out!
