### ISSUE TITLE
Backends that no longer exist cannot be unmounted and the vault cannot be unsealed

### ISSUE THREAD

**Issue by nrhall-deshaw** [hashicorp/vault#3867]
**Environment:**

* Vault Version: 0.9.1
* Operating System/Architecture: linux/amd64

**Vault Config File:**

cluster_name = "qa"

listener "tcp" {
  address = "xxxxxx:8200"
  tls_cert_file = "/etc/vault/tls/xxxxxx-vault.crt"
  tls_key_file  = "/etc/vault/tls/xxxxxx-vault.key"
}

storage "file" {
  path = "/path/to/vault/data"
}

disable_mlock = true
plugin_directory = "/path/to/vault/plugins"
api_addr = "https://xxxxxx:8200"

**Startup Log Output:**

==> Vault server configuration:
Cgo: disabled
Cluster Address: https://xxxxxx:8201
Listener 1: tcp (addr: "xxxxxx:8200", cluster address: "xxxxxx:8201", tls: "enabled")
Log Level: debug
Mlock: supported: true, enabled: false
Redirect Address: https://xxxxxx:8200
Storage: file
Version: Vault v0.9.1
Version Sha: 96420367a5a2f43b6093d1d936af07905a7ff238+CHANGES

==> Vault server started! Log data will stream in below:

2018/01/30 06:07:17.431706 [INFO ] core: vault is unsealed
2018/01/30 06:07:17.433121 [INFO ] core: post-unseal setup starting
2018/01/30 06:07:17.434695 [INFO ] core: loaded wrapping token key
2018/01/30 06:07:17.434721 [INFO ] core: successfully setup plugin catalog: plugin-directory=/path/to/vault/plugins
2018/01/30 06:07:17.437731 [INFO ] core: successfully mounted backend: type=generic path=secret/
2018/01/30 06:07:17.437889 [INFO ] core: successfully mounted backend: type=system path=sys/
2018/01/30 06:07:17.438107 [INFO ] core: successfully mounted backend: type=identity path=identity/
2018/01/30 06:07:17.438124 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
**2018/01/30 06:07:17.448925 [ERROR] core: failed to create credential entry: path=kerberos/ error=unknown backend type: kerberos**
2018/01/30 06:07:17.448941 [INFO ] core: pre-seal teardown starting
2018/01/30 06:07:17.448945 [INFO ] core: cluster listeners not running
2018/01/30 06:07:17.448975 [INFO ] core: pre-seal teardown complete
**2018/01/30 06:07:17.448985 [ERROR] core: post-unseal setup failed: error=failed to setup auth table**
2018/01/30 06:07:17.448992 [WARN ] core: vault is sealed

**Expected Behavior:**

Vault should have allowed vault to start up with a backend that no longer exists, although this is perhaps tricky.  Perhaps the vault could unseal but disable the failed auth backends, and then allow auth-disable for non-existent auth-backends - or perhaps allow backends to be unmounted even if sealed.

**Actual Behavior:**

The unseal failed because the 'kerberos' plugin no longer exists as a built-in.

**Steps to Reproduce:**

Remove a built-in auth backend from the code and convert it to a plugin, then start the new version of vault against an existing storage setup.

**Important Factoids:**

This was a non-vanilla Vault build with the Kerberos plugin compiled in (see other pull request below); I removed this from the code and reverted to an (almost) vanilla 0.9.1 build, but I wasn't able to unmount and remount the kerberos auth backend.  As a workaround, I started the old version, unmounted, then started the new version and remounted it as a plugin.

**References:**

https://github.com/hashicorp/vault/pull/3005

**Comment by michelvocks** [comment]
I'm closing this issue since it has been fixed with Vault 1.1.0.
