### ISSUE TITLE
Golang API renewer custom increment

### ISSUE THREAD

**Issue by grobinson-blockchain** [hashicorp/vault#3870]
I would like to use the Golang client to renew a token based on it's TTL:

    func NewRenewerFromToken(client *vault.Client, token string) (*vault.Renewer, error) {
        secret, err := client.Auth().Token().Lookup(token)
        if err != nil {
            return nil, err
        }
        var renewable bool
        if v, ok := secret.Data["renewable"]; ok {
            renewable, _ = v.(bool)
        }
        var increment int64
        if v, ok := secret.Data["ttl"]; ok {
            if n, ok := v.(json.Number); ok {
                increment, _ = n.Int64()
            }
        }
        return client.NewRenewer(&vault.RenewerInput{
            Secret: &vault.Secret{
                Auth: &vault.SecretAuth{
                    ClientToken: token,
                    Renewable:   renewable,
                },
            },
            Increment: int(increment),
        })
    }

However the renewer passes 0 as the increment: https://github.com/hashicorp/vault/blob/b80af5a993ec5b4e3b9b43070e8aed275d7871a2/api/renewer.go#L198

rather than the value set in Increment:
https://github.com/hashicorp/vault/blob/b80af5a993ec5b4e3b9b43070e8aed275d7871a2/api/renewer.go#L132

is this something that the API can support or should I write a custom renewer?

**Comment by jefferai** [comment]
The increment var got added after the renewer was written by a contributor. I think it's just purely an oversight that the value is respected in the secrets renewal path but not the auth renewal path.

**Comment by chrishoffman** [comment]
Another option is to check out are periodic tokens which will reset to configured period value on each renewal.  That being said we will get that value supported.

https://www.vaultproject.io/docs/concepts/tokens.html#periodic-tokens
