### ISSUE TITLE
LDAP Handshake only via SSL?

### ISSUE THREAD

**Issue by Kloppi313** [hashicorp/vault#3884]
**Environment:**

* Vault Version: Vault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')
* Operating System/Architecture: Ubuntu 18.04 (yes, it's still a beta)

**Vault Config File:**
```
listener "tcp" {
  address = "my.adress:8200"
  tls_disable = 0
  tls_cert_file = "/etc/vault/cert/my.adress.pem"
  tls_key_file = "/etc/vault/cert/my.adress.key"
  tls_min_version = "tls12"
}

storage "file" {
  path = "/data/vault"
}
```
**Expected Behavior:**
Encrypted authentication via LDAP should work also if the LDAP-server does not accept SSL Handshakes.

**Actual Behavior:**
No authentication is possible as long as encryption is configured.

**Steps to Reproduce:**
Setup Vault with the provided config file, activate the LDAP Backend and configure it as follows:

`vault write auth/ldap/config url="ldaps://ldap-server.adress" userdn="ou=User,dc=my,dc=adress" groupdn="CN=Group,OU=Groups,DC=my,DC=adress" groupattr="cn" upndomain="my.adress" insecure_tls=true starttls=true tls_min_version=tls10 tls_max_version=tls12 certificate=@CAChain.pem`

Start tcpdump:
`tcpdump -ni eth0 -s0 -w /tmp/dump port 636`

Try to authenticate:
```
vault login -method=ldap username=LDAPUser
-> Password (will be hidden):***
```

=> 
```
Error authenticating: Error making API request.

URL: PUT https://my.adress:8200/v1/auth/ldap/login/LDAPUser
Code: 400. Errors:

* 1 error occurred:

* error connecting to host "ldaps://ldap-server.adress": LDAP Result Code 200 "Network Error": read tcp 123.234.456.678:47408->234.346.567.876:636: read: connection reset by peer
```
With wireshark /tmp/dump you will see the "Client Hello" is SSL instead of TLS

**Important Factoids:**
The LDAP-Server must not accept SSL Handshakes, just TLS to get the vault request failed.

Without encryption (ldap:// as protocol and starttls=false):

`vault write auth/ldap/config url="ldap://ldap-server.adress" userdn="ou=User,dc=my,dc=adress" groupdn="CN=Group,OU=Groups,DC=my,DC=adress" groupattr="cn" upndomain="my.adress" insecure_tls=true starttls=false tls_min_version=tls10 tls_max_version=tls12 certificate=@CAChain.pem`

everything works as expected:
```
Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

Key                    Value
---                    -----
token                  54321
token_accessor         12345
token_duration         768h
token_renewable        true
token_policies         [default policy1]
token_meta_username    LDAPUser

```

`ldapsearch -H ldaps://ldap-server.adress:636 -D LDAPUser@my.adress -W -b DC=my,DC=adress sAMAccountName=LDAPUser`
works as expected. With wireshark you can see that the handshake step is done via TLS1.2.

**References:**
None

**Comment by jefferai** [comment]
Can you try it with an ldap:// URL instead of ldaps://? That's the normal way to specify TLS connections with ldap using STARTTLS.

**Comment by Kloppi313** [comment]
I try to answer asap. I have to check some configurations and hope to answer till friday.

**Comment by Kloppi313** [comment]
I have some new information for you.

I tested the following on SLES 12 SP3, because on Ubuntu 18.04 ldapsearch has the same behaviour like vault.

If you want to proof the TLS handshake of the LDAP server use:
`ldapsearch -ZZ -H ldap://LDAPSERVER:389 -D ACCOUNT@DOMAIN.TLD -W -b DC=DOMAIN,DC=TLD sAMAccountName=ACCOUNT`
This works on SLES but in my case not on Ubuntu (I think because of the gnutls lib used by ldapsearch on Ubuntu, SLES uses libssl).
With wireshark you will see, that the TLS protocol is used.
![ldapsearch](https://user-images.githubusercontent.com/36038231/36024332-bf9c7ae8-0d8f-11e8-92e9-a945cc099528.png)


I now also installed vault on the same SLES system and configured it as mentioned by jefferai. I also tcpdumped the connection between Vault and the LDAP server and Vault uses the SSL handshakeprotocol which the LDAP Server refuses.
![vault](https://user-images.githubusercontent.com/36038231/36024362-d5361814-0d8f-11e8-9abb-a5456e2623c7.png)

I used SLES because I wanted to show you, that vault in this case with a not allowed SSL handshake
isnt able to connect to the LDAP server. This is not an issue of Ubuntu but maybe because of the used libs and the used handshake protocol SSL instead of TLS.

**Comment by jefferai** [comment]
What's the output of a read on auth/ldap/config?

**Comment by Kloppi313** [comment]
```
Key                Value
---                -----
binddn             n/a
bindpass           n/a
certificate        -----BEGIN CERTIFICATE-----
MIII...
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MII...
-----END CERTIFICATE-----
deny_null_bind     true
discoverdn         false
groupattr          cn
groupdn            CN=1,OU=2,OU=3,DC=domain,DC=tld
groupfilter        (|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}}))
insecure_tls       true
starttls           true
tls_max_version    tls12
tls_min_version    tls10
upndomain          domain.tld
url                ldap://LDAPSERVER.domain.tld
userattr           cn
userdn             ou=X,ou=Y,ou=Z,dc=domain,dc=tld
```

**Comment by jefferai** [comment]
If you look at the second screenshot you attached you'll see that a STARTTLS is being sent from Vault to the server, but then it falls back. I've seen cases in the past where only certain clients (IP address, user-agent, etc.) were configured on the LDAP server to be allowed to upgrade to a TLS connection. Is there anything on the LDAP side in logs that might provide a clue?

**Comment by Kloppi313** [comment]
There are no clients, agents or so denied or blocked by the LDAP Server. Unfortunally I don't have access to the server logs.
But I tried to figure out, that it does not accept the SSL handshake protocol but only the TLS handshake protocol. For me it looks like vault only uses SSL to talk to the server and tries to negotiate a TLS Cipher via a ChangeCipherSpec protocol message but this step fails as the server does not accept SSL in the very first step. This is what I see in the tcpdumps. I don't see that there is fall back in the second screenshot.

In other words: Please take a look at https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_handshake
I assume that vault fails to connect in the negotiation phase on the first step, because it uses SSL. I think it would switch to TLS after the ChangeCipherSpec step (this is the part where admins often compare and rate their cipher lists and which gets the most attention).

Because gnutls-cli does not have an option to only use SSL in the handshake, I used openssl on port 636 (gnutls has support for StartTLS, OpenSSL doesn't):
```
openssl s_client -connect LDAPServer:636 -no_tls1 -no_tls1_2 -no_tls1_1
CONNECTED(00000003)
140141764269504:error:141640BF:SSL routines:tls_construct_client_hello:no protocols available:../ssl/statem/statem_clnt.c:694:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
---
```
Depending on the version you are using it might also be -ssl3 instead of -no_tls1x to request ssl3 only handshake.

With accepted TLS:
```
openssl s_client -connect LDAPServer:636
.
.
.
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA384
    Session-ID: 8F2900003C72AE0F73FD7274A7C3FEE273F81D7B2D9F4F6FFA61A219DD3CBF79
    Session-ID-ctx: 
    Master-Key: FAF489514B1F722716DB19439B246674A0E62D46B8DA159F126B87525142EDD33E80EDDFFB7E5F3D5A39797CFC7F79D7
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1518426585
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---
```

So I think it would be best to also implement TLS as handshake protocol in vault and not only SSL.

**Comment by jefferai** [comment]
I honestly don't see how the behavior you're describing can happen. With an `ldap` URL (not `ldaps`), we will hit this switch case: https://github.com/hashicorp/vault/blob/master/builtin/credential/ldap/path_config.go#L381 ...From there it does a straight TCP dial. Once the connection is established, we call StartTLS on the established TCP connection.

The behavior you're describing sounds more like the ldaps case at https://github.com/hashicorp/vault/blob/master/builtin/credential/ldap/path_config.go#L400 where the original connection is established by using TLS, which is also the code path used in your original post. However, even in that case there is no provision for connecting via SSL. The underlying call to the LDAP library is then using https://golang.org/pkg/crypto/tls/#Dial which is always TLS and will be configured with the minimum/maximum TLS settings you have set.

**Comment by joelthompson** [comment]
@kloppi313 are you saying Vault is using SSL instead of TLS just based on Wireshark displaying SSL as the protocol instead of TLS? Are you sure it's not just how Wireshark is displaying it (e.g., it won't know what version of SSL/TLS is being used until it completes the handshake, so it's probably just saying SSL as a default because it can't determine a more specific version). My hunch is that it's failing out due to incompatible cipher suites. Can you show the details of both Client Hello packets as well as the Server Hello packet on the successful connection attempt?

**Comment by jefferai** [comment]
Ooh I like that theory.

**Comment by Kloppi313** [comment]
@joelthompson not only because of the interpretation of wireshark, but also because I can reproduce the behaviour with OpenSSL (which only works on Port 636) and GnuTLS which does not support SSL Handshake and is able to connect as well.

```
sslscan LDAPServer:636
Preferred TLSv1.2  256 bits    0xC028 ECDHE-RSA-AES256-SHA384       Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits    0xC027 ECDHE-RSA-AES128-SHA256       Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits    0xC014 ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits    0xC013 ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits      0x9F DHE-RSA-AES256-GCM-SHA384     DHE 1024 bits
Accepted  TLSv1.2  128 bits      0x9E DHE-RSA-AES128-GCM-SHA256     DHE 1024 bits
Accepted  TLSv1.2  256 bits      0x39 DHE-RSA-AES256-SHA            DHE 1024 bits
Accepted  TLSv1.2  128 bits      0x33 DHE-RSA-AES128-SHA            DHE 1024 bits
Accepted  TLSv1.2  256 bits      0x9D AES256-GCM-SHA384            
Accepted  TLSv1.2  128 bits      0x9C AES128-GCM-SHA256            
Accepted  TLSv1.2  256 bits      0x3D AES256-SHA256                
Accepted  TLSv1.2  128 bits      0x3C AES128-SHA256                
Accepted  TLSv1.2  256 bits      0x35 AES256-SHA                   
Accepted  TLSv1.2  128 bits      0x2F AES128-SHA                   
Preferred TLSv1.1  256 bits    0xC014 ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Accepted  TLSv1.1  128 bits    0xC013 ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.1  256 bits      0x39 DHE-RSA-AES256-SHA            DHE 1024 bits
Accepted  TLSv1.1  128 bits      0x33 DHE-RSA-AES128-SHA            DHE 1024 bits
Accepted  TLSv1.1  256 bits      0x35 AES256-SHA                   
Accepted  TLSv1.1  128 bits      0x2F AES128-SHA                   
Preferred TLSv1.0  256 bits    0xC014 ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Accepted  TLSv1.0  128 bits    0xC013 ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.0  256 bits      0x39 DHE-RSA-AES256-SHA            DHE 1024 bits
Accepted  TLSv1.0  128 bits      0x33 DHE-RSA-AES128-SHA            DHE 1024 bits
Accepted  TLSv1.0  256 bits      0x35 AES256-SHA                   
Accepted  TLSv1.0  128 bits      0x2F AES128-SHA    
```

And the Client Hello contains
```
Cipher Suites (16 suites)
                Cipher Suite: TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)
                Cipher Suite: TLS_RSA_WITH_AES_128_GCM_SHA256 (0x009c)
                Cipher Suite: TLS_RSA_WITH_AES_256_GCM_SHA384 (0x009d)
                Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
                Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
                Cipher Suite: TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (0xc012)
                Cipher Suite: TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a)
```

So it should be compatible with at least
- 0x2F
- 0x35
- 0x9C
- 0x9D
- 0xC013
- 0xC014
but it does not work.

I got the reason why wireshark tells it is SSL: In newer versions (I use the one shipped with Ubuntu 16.04 - 2.2.6) but with 2.4.4 it shows TLSv1. If the server answers without a FIN after the Client Hello, it will be corrected to TLSv1.2 so my guess of wrong handshake protocol was wrong. You can reproduce 

Until I examined the problem a bit more I have a workaround: socat. Vault connects local to socat (but with SSL) which decrypts the connection and than encrypts it compatible with the LDAP server:
`socat OPENSSL-LISTEN:636,pf=ip4,fork,cert=/etc/vault/cert/vault.adress.tld.pem,key=/etc/vault/cert/vault.adress.tld.key,verify=0 OPENSSL:LDAP.server.tld:636,verify=1`

I try to the examination done until this friday, otherwise this issue can be closed. Thank you for your help!

**Comment by jefferai** [comment]
I don't know what's going on with your setup, but something is very strange.

You solved this by listening on port 636 with socat. But your config: `ldap://LDAPSERVER.domain.tld` -- is using `ldap` protocol. 

There is an extremely straightforward switch at https://github.com/hashicorp/vault/blob/master/builtin/credential/ldap/path_config.go#L381

You can see that if you provide the `ldap` protocol and no port, it will use port 389.

The fact that your Vault is reaching out on 636 suggests that something is very wonky, or that the config value you gave us does not actually match your real config. This is important because the behavior you're seeing *is* the expected behavior for an `ldaps` protocol, which will by default use, you guessed it, port 636.

**Comment by Kloppi313** [comment]
No, I use ldaps to localhost now, did I write ldap anywhere (sorry, it's late over here)?

**Comment by jefferai** [comment]
Yes: https://github.com/hashicorp/vault/issues/3884#issuecomment-364427463

And using the ldaps protocol is likely the root of your problems since that will cause a TLS *connection* instead of starting with a non-TLS connection and then performing a TLS upgrade.

**Comment by joelthompson** [comment]
I don't think that's it. If you look at the wireshark screenshot, it's clear that Vault is connecting to LDAP and then requesting a TLS upgrade, which the server respects, then Vault tries the TLS handshake, and it's getting an error. The server also looks like it supports implicit TLS over port 636.

The fact that the server is sending a TCP RST instead of a graceful exit (e.g., it's not even sending a FIN, it's sending a RST) indicates that the server thinks there's something really wrong with the handshake. This is where server logs would come in handy. I _still_ think this has to do with cipher suites. My best guess is that the LDAP server doesn't like the ChaCha20-Poly1305 suites. Those weren't part of the original TLS1.2 spec but were added later, and it [looks like](https://golang.org/src/crypto/tls/cipher_suites.go#L81) golang only sends them with TLS 1.2. So, a quick-and-dirty test would be to set `tls_max_version` to `tls11` and retry the connection. (Which reminds me of https://github.com/hashicorp/vault/pull/2060#issuecomment-257986538 -- does your server have a SHA512 certificate?)

Yes, I realize that servers _should_ just ignore any cipher suites they don't understand. There's a lot servers _should_ do in these types of circumstances, but they don't. See, e.g., Adam Langley's [post on crypto agilit](https://www.imperialviolet.org/2016/05/16/agility.html)y talking about the version negotiation: "This is about as simple as an extensibility mechanism could be, and yet lots of implementations get it wrong. It's a common mistake for implementations to return an error when the client offers a version number that they don't understand.... It's taken about 15 years to get to the point where web browsers don't have to work around broken version negotiation in TLS and that's mostly because we only have three active versions of TLS. When we try to add a fourth (TLS 1.3) in the next year, we'll have to add back the workaround, no doubt." And, sure enough, those problems reared their heads again when TLS1.3 was being deployed, as [CloudFlare describes](https://blog.cloudflare.com/why-tls-1-3-isnt-in-browsers-yet/).

p.s. golang supports 3DES by default? Ick.

**Comment by jefferai** [comment]
@joelthompson I think there are likely _multiple_ problems here, but the fact that socat on port 636 works means that something is not as described in the configuration output above.

**Comment by Kloppi313** [comment]
Well we solved the problem! Thanks guys!

@joelthompson was right. The LDAP Server presents a certificate which was signed by a root CA with a SHA512 certificate. After disabling TLS1.2 in vault the connection works.

For the record: the LDAP Server as a standard Windows AD.

**Comment by joelthompson** [comment]
BTW, it looks like Go 1.10 will fix this issue (see https://github.com/golang/go/commit/96cd66b266a24d8ed1f66dfa10ddb86d88b50fca), so once that's released and Vault is released with Go 1.10, you should be able to remove the `tls_max_version`.

**Comment by jefferai** [comment]
Lulz, I didn't see @joelthompson 's comment and I just came on here to say that the next release with 1.10 should probably fix this.

**Comment by Kloppi313** [comment]
I just deployed vault 0.10 and everything is fine now!
Thank you!
