### ISSUE TITLE
Client timeout error on long running server processes

### ISSUE THREAD

**Issue by brianshumate** [hashicorp/vault#3898]
**Environment:**

* Vault Version: Vault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')
* Operating System/Architecture: Alpine Linux/x86_64

**Expected Behavior:**

No client error when there's a deferred response condition whereby the server is working on a long running task (such as DisableAuth against an auth method with a number of leases for example).

It would be awesome if the client could even provide a status sub-command on operations for inspecting the progress of long running operations which the server is handling, for example `vault auth disable status` and some means to cleanly exit the CLI when encountering these types of operations instead of timing out.

**Actual Behavior:**

AppRole auth method currently has ~5k leases; when I use the Vault CLI to disable it:

```
$ time vault auth disable approle/
Error disabling auth method at approle/: Delete http://localhost:8200/v1/sys/auth/approle: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
vault auth disable approle/  0.06s user 0.03s system 0% cpu 1:00.21 total
```

it reliably times out at the one minute mark each time there is any non-trivial number of leases present in my auth method, leading me to think that perhaps the entire operation has failed.

It has not actually failed and in fact, I can observe e.g., with `watch -n 5 "consul kv get -recurse -keys vault/sys/expire/id/auth/approle/login/ | wc -l"` that the lease count is decrementing and does indeed eventually reach zero and the auth method is no longer present:

```
$ vault auth list
Path         Type        Description
----         ----        -----------
ldap/        ldap        n/a
token/       token       token based credentials
userpass/    userpass    n/a
```

Unfortunately, the client/CLI errors long before the server can complete the `DisableAuth` which represents a bit of an operator UX dilemma.

**Steps to Reproduce:**

1. Enable AppRole auth method
2. Create a role and generate 5000 tokens from it
2. Disable the auth method with `vault` CLI:

```
$ vault auth disable approle/
Error disabling auth method at approle/: Delete http://localhost:8200/v1/sys/auth/approle: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Important Factoids:**

Calling the API directly works as expected and can be used instead of the CLI as necessary:

```
$ curl \
    --header "X-Vault-Token: $VAULT_TOKEN" \
    --request DELETE \
    $VAULT_ADDR/v1/sys/auth/approle
```

**Comment by burdandrei** [comment]
received the same with lease  revoke prefix

**Comment by jefferai** [comment]
You can control this via https://www.vaultproject.io/docs/commands/index.html#vault_client_timeout if you like.

**Comment by burdandrei** [comment]
this is great, the problem is when nomad throws this exception and all my production goes bananas

**Comment by jefferai** [comment]
That's an issue you need to file with the Nomad team then.

**Comment by burdandrei** [comment]
we received yesterday vault cluster throwing timeouts to  ```vault status``` so outage was on Vault side.
If i understand this right there was an issue with one of Mongodb mounts, that made vault crazy.
I managed to heal it only with ```vault lease revoke -force -prefix $(mount)```
before that it was answering path not found when i tried to read database config

**Comment by jefferai** [comment]
Without logs I can't say much. Please file a new issue and include the requested information.

**Comment by burdandrei** [comment]
sure, sorry for buzz

**Comment by captain-kark** [comment]
Pardon the necroposting. 

If you're using vault in k8s, check your namespace range limits. I had them tuned way down, and for things like mounting large plugins, you could easily need a couple hundered Mi memory, as well as a couple hundred millicpu to avoid these timeouts.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.
   
Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
