### ISSUE TITLE
Add active/active capability

### ISSUE THREAD

**Issue by bkrodgers** [hashicorp/vault#390]
Per https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/px3M0fg3d7g/2se9LpEg2DYJ --

While I understand the complexities mentioned in the thread above, I'd like to see the ability to have multiple active nodes for HA reasons, even if scalability is not a concern.  The current Active/Standby mode means there's a full outage if the active node goes down or needs to be rebooted, between the time it dies and when Vault notices and elects a new leader.  I also think it would be better to be able to scale out.

**Comment by kenbreeman** [comment]
++

**Comment by ryanking** [comment]
To deal with planned reboots of the active, a command to demote that process would be useful (can't it if it exists).

**Comment by jefferai** [comment]
@ryanking You can use `vault seal` to cause the active leader to give up serving client requests and force a transition. You can also just stop Vault normally as that will first seal, causing the same transition. Either of those is preferable to simply SIGKILLing the Vault process.

**Comment by seeder** [comment]
there is also ```step-down``` option on vault command to force it to drop leadership

**Comment by jefferai** [comment]
Closing for now as there are no near or long term plans for active/active.

**Comment by reverendtimm** [comment]
I think the unhappy faces on the closing comment are appropriate, to say the least. 

I don't see what the issue would be with active/active? 

If you're using something like DynamoDB (as in our deployment) with proper locking, why would active/active be a cause for concern. Running Vault in docker in AWS is, quite frankly, a nighmare without active/active, and you're thusly required to run it in EC2.

HA on vault seems to be quite poorly thought out. When mentioning the active/passive architecture in vault to anyone, their first response is "but why?".

**Comment by hping2** [comment]
With the vault with backend in DynamoDB, for the case that trying to spin another k8s cluster (e.g, to upgrading cluster), we want to have active(old cluster)/active(new cluster) running at the same time for some time till the old one shuts down, without active/active, it is totally blocked.
