### ISSUE TITLE
Log warnings when too many leases are active

### ISSUE THREAD

**Issue by armon** [hashicorp/vault#3903]
**Feature Request:**

We should issue a warning in the log message when too many leases are active in the system. This is usually an indication that the rate in (new leases) does not match rate out (expiration / revocation) and will eventually lead to cluster degradation or failure.

Conservatively, we could use a high warning threshold like 256K leases, which is unlikely to ever be a reasonable steady state. This could potentially be made a tunable knob if necessary.

This is where the metric is currently emitted, might be good to restrict logging to once every N interval to avoid flooding.
https://github.com/hashicorp/vault/blob/8142b42d951119a73ce46daa3331921b5e21cdee/vault/expiration.go#L1271

**Comment by jefferai** [comment]
Closed by #3957
