### ISSUE TITLE
Unable to enable aws auth backend

### ISSUE THREAD

**Issue by jdavisp3** [hashicorp/vault#3905]
I am having trouble enabling the `aws` authentication backend.

```
vault auth enable aws
Error validating token: Error making API request.

URL: GET https://vault-dev.counsyl.com/v1/auth/token/lookup-self
Code: 403. Errors:

* permission denied
```

This is using a root token. I can otherwise use the token to list secrets, etc.

**Environment:**
```
Vault v0.9.1 ('87b6919dea55da61d7cd444b2442cabb8ede8ab1+CHANGES') (cgo)
```

* Vault Version: 0.9.1
* Operating System/Architecture: Ubuntu 14

**Actual Behavior:**
```
vault auth enable aws
Error validating token: Error making API request.

URL: GET https://vault-dev.counsyl.com/v1/auth/token/lookup-self
Code: 403. Errors:

* permission denied
```

**Steps to Reproduce:**
1. Login to vault with a root token (which succeeds).
2. Run the auth command.

**Important Factoids:**
None that I am aware of. I am using the Consul backend.

**Comment by jdavisp3** [comment]
Oh, I guess the command is actually:

```
vault auth-enable aws
```

I think the docs here may need to be updated: https://www.vaultproject.io/docs/auth/aws.html

**Comment by jdavisp3** [comment]
This also seems to be the case for `audit` backends. The command is `audit-enable` so possibly the docs here are out of date? https://www.vaultproject.io/docs/audit/syslog.html

**Comment by chrishoffman** [comment]
The CLI was revamped in 0.9.2 and the docs reflect the current version of vault. Currently the only way to view the older versions of the docs is to browse back in the source code.

**Comment by jdavisp3** [comment]
Oh, I see, thank you!
