### ISSUE TITLE
Allowing array for creation_statements instead of single string

### ISSUE THREAD

**Issue by tevert** [hashicorp/vault#3911]
Currently the `creation_statements` parameter for the database secret engine is a single string, and all your user creation and role assignment must go in a semi-colon separated string. This can get to be long and hard-to-read, especially if you store it in a json file (which can't have newlines). 

A quality-of-life improvement there would be to optionally accept an array of strings for creation_statements - something like: 
```json
{
    "db_name": "mydb",
    "creation_statements":  [
        "USE [master]; CREATE LOGIN [{{name}}] WITH PASSWORD = '{{password}}', DEFAULT_DATABASE=[mydb]",
        "CREATE USER [{{name}}] FOR LOGIN [{{name}}]",
        "GRANT SELECT ON [dbo.myschema] TO [{{name}}]",
        "GRANT INSERT ON [dbo.myschema] TO [{{name}}]",
        "GRANT DELETE ON [dbo.myschema] TO [{{name}}]",
        "GRANT UPDATE ON [dbo.myschema] TO [{{name}}];"
    ],
    "revocation_statements":"USE [master]; DROP USER IF EXISTS [{{name}}]",
    "default_ttl": "1h",
    "max_ttl": "24h"
}
```

The only existing alternatives I'm aware of:
1) Store the policy as YAML (does support newlines) or something, and do some pre-processing into JSON before POSTing. 
2) Configure and CI predefined SQL roles somewhere else, and then vault's policy is a simple 1-1 mapping.

I'm not particularly fond of either of these, so I thought I'd raise the question and see if this is something anyone else is interested in.

**Comment by jefferai** [comment]
Hi @tevert,

This is already supported! See https://www.vaultproject.io/api/secret/databases/postgresql.html#creation_statements

**Comment by tevert** [comment]
Sorry, I should've specified I'm using the MSSQL plugin, not Postgres. Looks like it doesn't work for MSSQL, based on the documentation. When I try, I get:
```
{"errors":["1 error occurred:\n\n* Error converting input [CREATE USER [{{name}}] WITH PASSWORD = '{{password}}'; GRANT SELECT ON [dbo] TO [{{name}}]; GRANT INSERT ON [dbo] TO [{{name}}]; GRANT DELETE ON [dbo] TO [{{name}}]; GRANT UPDATE ON [dbo] TO [{{name}}];] for field creation_statements: '' expected type 'string', got unconvertible type '[]interface {}'"]}
```

**Comment by chrishoffman** [comment]
Currently you must provide serialize the JSON to a string or base64 encode it to work. You cannot provide a native JSON list of statements.
