### ISSUE TITLE
Orphan token not created when I try v1/auth/token/create/:role with no_parent is set.

### ISSUE THREAD

**Issue by lovesh-ap** [hashicorp/vault#3917]
**Environment:**

* Vault Version: v0.8.2
* Operating System/Architecture: Mac

**Vault Config File:**

storage "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
}

listener "tcp" {
 address = "0.0.0.0:8200"
 tls_disable = 1
}

max_lease_ttl = "2557920h"

disable_mlock = true

**Startup Log Output:**

==> WARNING: BootstrapExpect Mode is specified as 1; this is the same as Bootstrap mode.
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> Starting Consul agent...
==> Consul agent running!
           Version: 'v0.9.3'
           Node ID: 'da3dbc56-232d-a120-31e7-303ceeb17cb1'
         Node name: 'MacBook-Pro-2.local'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: true)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600)
      Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false

==> Log data will now stream in as it occurs:

    2017/11/20 13:13:01 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:127.0.0.1:8300 Address:127.0.0.1:8300}]
    2017/11/20 13:13:01 [INFO] raft: Node at 127.0.0.1:8300 [Follower] entering Follower state (Leader: "")
    2017/11/20 13:13:01 [INFO] serf: EventMemberJoin: MacBook-Pro-2.local.dc1 127.0.0.1
    2017/11/20 13:13:01 [WARN] serf: Failed to re-join any previously known node
    2017/11/20 13:13:01 [INFO] serf: EventMemberJoin: MacBook-Pro-2.local 127.0.0.1
    2017/11/20 13:13:01 [WARN] serf: Failed to re-join any previously known node
    2017/11/20 13:13:01 [INFO] consul: Adding LAN server MacBook-Pro-2.local (Addr: tcp/127.0.0.1:8300) (DC: dc1)
    2017/11/20 13:13:01 [INFO] consul: Handled member-join event for server "MacBook-Pro-2.local.dc1" in area "wan"
    2017/11/20 13:13:01 [INFO] agent: Started DNS server 127.0.0.1:8600 (udp)
    2017/11/20 13:13:01 [INFO] agent: Started DNS server 127.0.0.1:8600 (tcp)
    2017/11/20 13:13:01 [INFO] agent: Started HTTP server on 127.0.0.1:8500
==> Newer Consul version available: 1.0.0 (currently running: 0.9.3)
    2017/11/20 13:13:06 [WARN] agent: Check 'vault:127.0.0.1:8200:vault-sealed-check' missed TTL, is now critical
    2017/11/20 13:13:07 [WARN] raft: Heartbeat timeout from "" reached, starting election
    2017/11/20 13:13:07 [INFO] raft: Node at 127.0.0.1:8300 [Candidate] entering Candidate state in term 3
    2017/11/20 13:13:07 [INFO] raft: Election won. Tally: 1
    2017/11/20 13:13:07 [INFO] raft: Node at 127.0.0.1:8300 [Leader] entering Leader state
    2017/11/20 13:13:07 [INFO] consul: cluster leadership acquired
    2017/11/20 13:13:07 [INFO] consul: New leader elected: MacBook-Pro-2.local
    2017/11/20 13:13:08 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/11/20 13:13:44 [INFO] agent: Synced service 'vault:127.0.0.1:8200'
    2017/11/20 13:13:44 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
    2017/11/20 13:13:50 [INFO] agent: Deregistered service 'vault:127.0.0.1:8200'
    2017/11/20 13:13:50 [INFO] agent: Deregistered check 'vault:127.0.0.1:8200:vault-sealed-check'
==> WARNING: mlock not supported on this system!

  An `mlockall(2)`-like syscall to prevent memory from being
  swapped to disk is not supported on this system. Running
  Vault on an mlockall(2) enabled system is much more secure.

==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: false, enabled: false
        Redirect Address: http://127.0.0.1:8200
                 Storage: consul (HA available)
                 Version: Vault v0.8.2
             Version Sha: 9afe7330e06e486ee326621624f2077d88bc9511

==> Vault server started! Log data will stream in below:

2017/11/20 13:13:57.870438 [WARN ] physical/consul: appending trailing forward slash to path
    2017/11/20 13:13:57 [INFO] agent: Synced service 'vault:127.0.0.1:8200'
    2017/11/20 13:13:57 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'
2017/11/20 13:14:18.375811 [INFO ] core: vault is unsealed
2017/11/20 13:14:18.376233 [INFO ] core: entering standby mode
    2017/11/20 13:14:18 [INFO] agent: Synced check 'vault:127.0.0.1:8200:vault-sealed-check'

**Expected Behavior:**

On creating a role token the no parent should set to true i.e. while lookup token orphan should be set.

Sample CURL:

curl -X POST \
  http://127.0.0.1:8200/v1/auth/token/create/some_role \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'x-vault-token: VAULT_TOKEN' \
  -d '{
  "no_default_policy":true,
  "ttl": "438000h",
  "renewable": true,
  "no_parent": true
}'

Lookup token: 
curl -X POST \
  http://127.0.0.1:8200/v1/auth/token/lookup \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'x-vault-token: VAULT_TOKEN' \
  -d '{
  "token": "client_token"
}'

Response:
{
    "request_id": "12bd470d-11b0-1adf-ed8b-77ccf6404aef",
    "lease_id": "",
    "renewable": false,
    "lease_duration": 0,
    "data": {
        "accessor": "TOKEN_ACCESSOR",
        "creation_time": 1517911147,
        "creation_ttl": 1576800000,
        "display_name": "token",
        "expire_time": "2068-01-25T15:29:07.678260527+05:30",
        "explicit_max_ttl": 0,
        "id": "dd0e8c02-0d8a-025e-6962-40f74f0c9c3a",
        "issue_time": "2018-02-06T15:29:07.678260328+05:30",
        "meta": null,
        "num_uses": 0,
        "orphan": true,
        "path": "auth/token/create/some_role",
        "policies": [
            "x_policy"
        ],
        "renewable": true,
        "role": "some_role",
        "ttl": 1576799987
    },
    "wrap_info": null,
    "warnings": null,
    "auth": null
}

**Actual Behavior:**

Lookup token: 
curl -X POST \
  http://127.0.0.1:8200/v1/auth/token/lookup \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'x-vault-token: VAULT_TOKEN' \
  -d '{
  "token": "client_token"
}'

Response:
{
    "request_id": "12bd470d-11b0-1adf-ed8b-77ccf6404aef",
    "lease_id": "",
    "renewable": false,
    "lease_duration": 0,
    "data": {
        "accessor": "TOKEN_ACCESSOR",
        "creation_time": 1517911147,
        "creation_ttl": 1576800000,
        "display_name": "token",
        "expire_time": "2068-01-25T15:29:07.678260527+05:30",
        "explicit_max_ttl": 0,
        "id": "dd0e8c02-0d8a-025e-6962-40f74f0c9c3a",
        "issue_time": "2018-02-06T15:29:07.678260328+05:30",
        "meta": null,
        "num_uses": 0,
        "orphan": false,
        "path": "auth/token/create/some_role",
        "policies": [
            "x_policy"
        ],
        "renewable": true,
        "role": "some_role",
        "ttl": 1576799987
    },
    "wrap_info": null,
    "warnings": null,
    "auth": null
}

**Steps to Reproduce:**

1. Create a role for any policy
2. Create the token using API: https://www.vaultproject.io/api/auth/token/index.html#create-token
sample curl mentioned above.
3. Lookup token and check the orphan field in the response.

**Comment by chrishoffman** [comment]
As the docs state, when using a token role the role options will override the options in the call.  Since a root/sudo token is required anyway to use the no_parent options, the regular token create endpoint should be used.
