### ISSUE TITLE
duplicate POST to sys/auth/app-id gives 500

### ISSUE THREAD

**Issue by benschw** [hashicorp/vault#392]
Not sure if this is desired or not, but it seems like a `409 Conflict` (or something else in the 400s) would be more appropriate than a `500`. Below are steps to illustrate the behavior:

    $ curl -i -X POST http://172.20.20.11:8200/v1/sys/auth/app-id -H "X-Vault-Token: `cat root_token`" -d '{"type":"app-id"}'
    HTTP/1.1 204 No Content 
    Content-Type: application/json
    Date: Fri, 03 Jul 2015 23:58:49 GMT

    $ curl -i -X POST http://172.20.20.11:8200/v1/sys/auth/app-id -H "X-Vault-Token: `cat root_token`" -d '{"type":"app-id"}'
    HTTP/1.1 500 Internal Server Error
    Content-Type: application/json
    Date: Fri, 03 Jul 2015 23:58:51 GMT
    Content-Length: 31

    {"errors":["invalid request"]}
    $ curl -i -X DELETE http://172.20.20.11:8200/v1/sys/auth/app-id -H "X-Vault-Token: `cat root_token`"                                           
    HTTP/1.1 204 No Content
    Content-Type: application/json
    Date: Fri, 03 Jul 2015 23:58:54 GMT

    $ curl -i -X POST http://172.20.20.11:8200/v1/sys/auth/app-id -H "X-Vault-Token: `cat root_token`" -d '{"type":"app-id"}'
    HTTP/1.1 204 No Content
    Content-Type: application/json
    Date: Fri, 03 Jul 2015 23:58:56 GMT

**Comment by armon** [comment]
Yeah the error message needs to be improved. There is an annoying issue of the core providing a nice error, but it is being masked higher up the chain in the HTTP layer which requires a significant rework to expose.
