### ISSUE TITLE
Policy updates are racey

### ISSUE THREAD

**Issue by cgaspar-deshaw** [hashicorp/vault#3928]
There is no mechanism I can see for avoiding (by preventing or detecting) a last-writer-wins scenario for policies (and probably other data types, but policies involve humans and text editors, so they stick out). I see 2 obvious solutions, but I'm sure there are others I haven't thought of:
- Create a write lock on a path, perhaps by an exclusive time-limited lease that expires on write. Involves locks, blech.
- Return a version ID with a path, and accept an optional version ID on write, failing the write if the version ID does not match the current version ID. Requires an atomic test-and-set, less awful than a lock.

**Comment by jefferai** [comment]
We've thought over time about the second option, and maybe some day we'll implement it, but really our general advice is to store your policies as code. See https://www.hashicorp.com/blog/codifying-vault-policies-and-configuration for some information about this. This has a lot of benefits -- using a DVCS to help with merges to policies changed by multiple people, ensuring that all policies can be updated from an atomic snapshot of the code (the repo revision), and so on.
