### ISSUE TITLE
Build instructions fail on Windows

### ISSUE THREAD

**Issue by ixe013** [hashicorp/vault#3930]
**Environment:**

* Vault Version: Would build 0.9.3
* Operating System/Architecture: Windows only (tested on Windows 7 and Windows 10)

**Vault Config File:**
(Not applicable)

**Startup Log Output:**
(Not applicable)

**Expected Behavior:**
I expect to be able to build Vault on Windows by following the instructions.

**Actual Behavior:**
The bootstrap target is not supported:

```
make bootstrap
usage: make [target]

target is in {bin,dev,generate,test,testacc,testrace,vet}.
target defaults to test if none is provided.
```

The `dev` target returns a findstr error that affects compilation:

```
make dev
FINDSTR: Write error
```
And finally, `link.exe` argument sent to `gox` are not properly formatted.

```
go\pkg\tool\windows_amd64\link.exe: -X flag requires argument of the form importpath.name=value
```

**Steps to Reproduce:**
Follow Vault build instructions, namely:
```
make bootstrap
make dev
```

**References:**
I am following the build instructions here : https://github.com/hashicorp/vault#developing-vault

**Comment by ixe013** [comment]
I have a fix, will send a pull request in a few minutes...

**Comment by calvn** [comment]
Closing since #3931 is now merged.
