### ISSUE TITLE
Typo in documentation 

### ISSUE THREAD

**Issue by ntroncos** [hashicorp/vault#3933]
There is a typo in the online documentation. It's simple but it had me chasing my tail for a bit. 
https://www.vaultproject.io/docs/auth/okta.html

<img width="1830" alt="screen shot 2018-02-07 at 10 46 33 am" src="https://user-images.githubusercontent.com/2539601/35935378-24d41dea-0bf5-11e8-8c71-2e55820da9b8.png">

**Comment by jefferai** [comment]
The website corresponds to the latest released version of Vault, which contained a revamped CLI. If you need to use an older version, the website/ folder contains the full history of the website and can be launched locally with "make website" from the Makefile in that folder. You can also use the newer CLI with older versions of Vault server!

**Comment by ntroncos** [comment]
I was using 0.9. in what version did that change?

**Comment by jefferai** [comment]
0.9.2.
