### ISSUE TITLE
Update Vault documentation to reflect changes in postgresql-database-plugin

### ISSUE THREAD

**Issue by michaelsdunn1** [hashicorp/vault#3938]
Version: v0.9.3
OS: Ubuntu

The current documentation shows the following documentation for the `postgresql-database-plugin`:

```
Configure Vault with the proper plugin and connection information:

$ vault write database/config/my-postgresql-database \
    plugin_name=postgresql-database-plugin \
    allowed_roles="my-role" \
    connection_url="postgresql://root:root@localhost:5432/"
```

The correct path for database configs is `database/config/connection`.

```
Configure a role that maps a name in Vault to an SQL statement to execute to create the database credential:

$ vault write database/roles/my-role \
    db_name=my-postgresql-database \
    creation_statements="CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}'; \
        GRANT SELECT ON ALL TABLES IN SCHEMA public TO \"{{name}}\";" \
    default_ttl="1h" \
    max_ttl="24h"
Success! Data written to: database/roles/my-role
```

In reality, the `creation_statements` key-value is deprecated, and it seems that the structure for the `postgresql-database-plugin` roles are now:

```
vault read /database/roles/admin
Key               Value
---               -----
revocation_sql    n/a
sql               n/a
```

Please let me know if there is a misunderstanding here, or I'm looking in the wrong place. Just don't want someone to fumble through the same mistakes I did.

Thanks!

**Comment by jefferai** [comment]
Hi there,

I think you are using the deprecated postgres backend while looking at the documentation for the combined database backend (which has type `database` instead of `postgresql`). So if you just mount `postgresql` you'll get the deprecated one.

**Comment by michaelsdunn1** [comment]
@jefferai 

Yeah, you're absolutely right. I had to the postgres backend mounted. I changed it. Thanks for the help.
