### ISSUE TITLE
Vault AWS Auth Method hitting the AWS API limit, RequestLimitExceeded

### ISSUE THREAD

**Issue by mohsen0** [hashicorp/vault#3942]
Vault is running in Highly available mode, across two data centres, when a number of instances bootup, they want to retrieve their secrets from the vault server. each might do a number of calls to vault for the different types of secrets. for some of them this is the response:
```
Feb 07 09:05:40 <servicename> gen_ssl_certs[1305]: 2018/02/07 09:05:40 AWS EC2 logon failedError making API request.
Feb 07 09:05:40 <servicename> gen_ssl_certs[1305]: URL: PUT https://secrets.cloud.local:443/v1/auth/aws/login
Feb 07 09:05:40 <servicename> gen_ssl_certs[1305]: Code: 400. Errors:
Feb 07 09:05:40 <servicename> gen_ssl_certs[1305]: * failed to verify instance ID: error fetching description for instance ID "i-07b6213469d66d50b": "RequestLimitExceeded: Request limit exceeded.\n\tstatus code: 503, request id: 3e28fa48-8a52-4c0f-9255-2725aee47a60"
``` 

**Environment:**
* Vault Version:
```bash
vault version
Vault v0.9.0 ('bdac1854478538052ba5b7ec9a9ec688d35a3335')
```
* Operating System/Architecture:
```bash
[centos@secrets-i0189db5c9605a13a7 ~]$ uname -a
Linux secrets-i0189db5c9605a13a7 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Startup Log Output:**
No exceptions or errors shown in the daemon logs

**Expected Behavior:**
Retrieve the secret, Manage the load of requests.

**Actual Behavior:**

Returns a 400 HTTP response code

**Steps to Reproduce:**

Against a vault server, initiate a number of requests and try to reach the AWS API limits.

**References:**
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html

**Comment by jefferai** [comment]
There's not much we can do about it, you're just starting enough instances at once that you're exceeding the request limit, which is imposed by AWS. You could see if using the IAM method works better... In most cases it's our recommended method as well.

**Comment by mohsen0** [comment]
RequestLimitExceeded is a throttle code 
FYI, https://github.com/aws/aws-sdk-go/blob/07a12acf062c74aacf99ed8a6a4ee1bc52ab1627/aws/request/retryer.go#L35

and AWS SDK  has the functionality to retry the request if it is throttle code response.
https://github.com/aws/aws-sdk-go/blob/4bd6f8bc55ec7eaf68efb9ec72983fbc0b79aba2/aws/client/default_retryer.go#L40

Can vault retry at least and then reject the request?
That would be a nice enhancement.

**Comment by jefferai** [comment]
We use the standard AWS SDK. Happy to accept a PR if you want to add this!
