### ISSUE TITLE
Inconsistencies in auth usage

### ISSUE THREAD

**Issue by myoung34** [hashicorp/vault#3948]
Some are plural, some not.
Drives me bonkers. Hard to automate.

```
$ vault read auth/ldap/group/data
No value found at auth/ldap/group/data

$ vault read auth/ldap/groups/data
Key             Value
---             -----
policies        data,default

$ vault read auth/aws/roles/stratabot
No value found at auth/aws/roles/stratabot

$ vault read auth/aws/role/stratabot
Key                             Value
```

**Comment by jefferai** [comment]
We're aware it's inconsistent, but generally for backwards compatibility reasons we can't change it, sorry.

**Comment by masteinhauser** [comment]
@jefferai I am confused, as does this not directly conflate what was just approved in the recent command re-architecture? https://github.com/hashicorp/vault/pull/3287 and https://github.com/hashicorp/vault/pull/3868
