### ISSUE TITLE
sys/raw does not correctly encode compressed data

### ISSUE THREAD

**Issue by kpaulisse** [hashicorp/vault#3952]
**Environment:**

* Vault Version: `Vault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')`
* Operating System/Architecture: MacOS

**Vault Config File:**

None (reproducible in dev mode)

**Startup Log Output:**

```
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: false, enabled: false
        Redirect Address: http://127.0.0.1:8200
                 Storage: inmem
                 Version: Vault v0.9.3
             Version Sha: 3d62f7679670a03271e53d23a4bf39e09f320b26+CHANGES
```

**Expected Behavior:**

When retrieving `/v1/sys/raw/core/mounts` (or any other gzip compressed value) I would expect that the content of the `value` in the JSON should be a "G" followed by the gzipped data.

**Actual Behavior:**

Unfortunately this is not the case because the binary data is corrupted in transit:

```
{"request_id":"af79d24b-6cc9-9313-d2d4-6b43db848b25","lease_id":"","renewable":false,"lease_duration":0,"data":{"value":"G\u001f\ufffd\u0008\u0000\u0000\u0000\u0000\u0000\u0002\ufffd\ufffd\ufffdώ\ufffd0\u0010\u0006\ufffd;O\u0011\ufffd\ufffd\ufffd\ufffd_\ufffd\u0026\ufffd\ufffdP4\u001e\ufffd\ufffd\u0016\ufffd\u001d\ufffd\ufffdBT\ufffd\ufffd...<snip>..."},"wrap_info":null,"warnings":null,"auth":null}
```

I confirmed that this is only a problem over HTTP by hacking in writing that value to a file, and that worked fine - here's what was written to the file:

```
G\u001F\x8B\b\u0000\u0000\u0000\u0000\u0000\u0002\xFF\xCC\xD2ώ\xD30\u0010\u0006\xF0;O\u0011...<snip>...
```

So only the "G" and the first character of the binary blob actually made it over HTTP before corruption started.

**Steps to Reproduce:**

```
vault server -dev -dev-root-token-id="kittens" &
curl -k --header "X-Vault-Token: kittens" http://localhost:8200/v1/sys/raw/core/mounts
```

As per [rfc 1952](https://tools.ietf.org/html/rfc1952) the first 2 characters of a gzip file are ID1 = 31 (0x1f, \037), ID2 = 139 (0x8b, \213) so you can readily see if there's corruption.

I also tried with `vault read -format=json sys/raw/core/mounts` and it's the same problem.

**Suggestion:**

Uncompressing this data on the server side would be wonderful, and since that would just be plain JSON, you wouldn't run into these sorts of encoding problems.

**Comment by jefferai** [comment]
Just adding something for posterity in case something like this comes up again: the data is not actually corrupted, it's just that what Vault stores isn't pure gzip. We prepend a letter to the data to know what *type* of compression was used -- elsewhere we use snappy for instance -- so the G is from Vault, and indeed the next two octets are the expected values for gzip.
