### ISSUE TITLE
vault doesn't renew etcd auth token periodically.

### ISSUE THREAD

**Issue by raoofm** [hashicorp/vault#3966]
**Environment:**
* Vault Version: Vault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')
* Operating System/Architecture: macOS 64

**Vault Config File:**
`
storage "etcd" {
  address           = "https://node01.dev.etcd.net:2379"
  etcd_api          = "v3"
  ha_enabled        = "true"
  path              = "vault/dev/3"
  sync              = "true"
  username          = "user"
  password          = "password"
  cluster_addr      = "http://127.0.0.1:8201"
  redirect_addr     = "http://127.0.0.1:8200"
  tls_ca_file       = "/usr/local/etc/openssl/cert.pem"
}

listener "tcp" {
  address           = "127.0.0.1:8200"
  cluster_address   = "127.0.0.1:8201"
  tls_disable       = "true"
  tls_cert_file     = "/vault/ssl/vault.crt"
  tls_key_file      = "/vault/ssl/vault.key"
  tls_min_version   = "tls12"
}

cluster_name        = "vault-cluster-dev"
disable_cache       = false
cache_size          = "32768"
disable_mlock       = true

default_lease_ttl   = "30"
max_lease_ttl       = "60"
`

**Startup Log Output:**
$ vault server -config=vault_config.hcl -log-level=info
WARNING! mlock is not supported on this system! An mlockall(2)-like syscall to
prevent memory from being swapped to disk is not supported on this system. For
better security, only run Vault on systems where this call is supported. If
you are running Vault in a Docker container, provide the IPC_LOCK cap to the
container.
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: false, enabled: false
        Redirect Address: http://127.0.0.1:8200
                 Storage: etcd (HA available)
                 Version: Vault v0.9.3
             Version Sha: 5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d

==> Vault server started! Log data will stream in below:

2018/02/13 12:21:10.101367 [INFO ] core: vault is unsealed
2018/02/13 12:21:10.101424 [INFO ] core: entering standby mode
2018/02/13 12:21:10.138280 [INFO ] core: acquired lock, enabling active operation
2018/02/13 12:21:10.202648 [INFO ] core: post-unseal setup starting
2018/02/13 12:21:10.209841 [INFO ] core: loaded wrapping token key
2018/02/13 12:21:10.209893 [INFO ] core: successfully setup plugin catalog: plugin-directory=
2018/02/13 12:21:10.223161 [INFO ] core: successfully mounted backend: type=kv path=secret/
2018/02/13 12:21:10.223502 [INFO ] core: successfully mounted backend: type=system path=sys/
2018/02/13 12:21:10.224032 [INFO ] core: successfully mounted backend: type=identity path=identity/
2018/02/13 12:21:10.224073 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2018/02/13 12:21:10.263482 [INFO ] rollback: starting rollback manager
2018/02/13 12:21:10.263497 [INFO ] expiration: restoring leases
2018/02/13 12:21:10.272023 [INFO ] expiration: lease restore complete
2018/02/13 12:21:10.281076 [INFO ] identity: entities restored
2018/02/13 12:21:10.285762 [INFO ] identity: groups restored
2018/02/13 12:21:10.290619 [INFO ] core: post-unseal setup complete
2018/02/13 12:21:10.290647 [INFO ] core/startClusterListener: starting listener: listener_address=127.0.0.1:8201
2018/02/13 12:21:10.290869 [INFO ] core/startClusterListener: serving cluster requests: cluster_listen_address=127.0.0.1:8201

2018/02/13 13:55:46.012634 [WARN ] core: leadership lost, stopping active operation
2018/02/13 13:55:51.013106 [ERROR] core: clearing leader advertisement failed: error=etcdserver: invalid auth token
2018/02/13 13:55:51.013143 [INFO ] core: pre-seal teardown starting
2018/02/13 13:55:51.013150 [INFO ] core: stopping cluster listeners
2018/02/13 13:55:51.013161 [INFO ] core: shutting down forwarding rpc listeners
2018/02/13 13:55:51.013186 [INFO ] core: forwarding rpc listeners stopped
2018/02/13 13:55:51.512998 [INFO ] core: rpc listeners successfully shut down
2018/02/13 13:55:51.513055 [INFO ] core: cluster listeners successfully shut down
2018/02/13 13:55:51.513168 [INFO ] rollback: stopping rollback manager
2018/02/13 13:55:51.513381 [INFO ] core: pre-seal teardown complete
2018/02/13 13:56:06.968193 [ERROR] core: key rotation periodic upgrade check failed: error=etcdserver: invalid auth token
2018/02/13 13:56:16.693170 [INFO ] core: acquired lock, enabling active operation
2018/02/13 13:56:16.794342 [INFO ] core: post-unseal setup starting
2018/02/13 13:56:16.800200 [INFO ] core: loaded wrapping token key
2018/02/13 13:56:16.800230 [INFO ] core: successfully setup plugin catalog: plugin-directory=
2018/02/13 13:56:16.815947 [INFO ] core: successfully mounted backend: type=kv path=secret/
2018/02/13 13:56:16.816204 [INFO ] core: successfully mounted backend: type=system path=sys/
2018/02/13 13:56:16.819282 [INFO ] core: successfully mounted backend: type=identity path=identity/
2018/02/13 13:56:16.819358 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2018/02/13 13:56:16.863297 [INFO ] expiration: restoring leases
2018/02/13 13:56:16.863301 [INFO ] rollback: starting rollback manager
2018/02/13 13:56:16.872291 [INFO ] expiration: lease restore complete
2018/02/13 13:56:16.883522 [INFO ] identity: entities restored
2018/02/13 13:56:16.892008 [INFO ] identity: groups restored
2018/02/13 13:56:16.899811 [INFO ] core: post-unseal setup complete
2018/02/13 13:56:16.899820 [INFO ] core/startClusterListener: starting listener: listener_address=127.0.0.1:8201
2018/02/13 13:56:16.899971 [INFO ] core/startClusterListener: serving cluster requests: cluster_listen_address=127.0.0.1:8201

2018/02/13 14:07:41.213161 [ERROR] core: barrier init check failed: error=failed to check for initialization: etcdserver: invalid auth token
2018/02/13 14:07:41.213216 [ERROR] error checking health: error=failed to check for initialization: etcdserver: invalid auth token
2018/02/13 14:07:50.049561 [ERROR] core: barrier init check failed: error=failed to check for initialization: etcdserver: invalid auth token
2018/02/13 14:07:50.049612 [ERROR] error checking health: error=failed to check for initialization: etcdserver: invalid auth token
2018/02/13 14:07:59.476221 [ERROR] core: barrier init check failed: error=failed to check for initialization: etcdserver: invalid auth token

2018/02/13 14:12:48.832240 [ERROR] core: barrier init check failed: error=failed to check for initialization: etcdserver: invalid auth token
2018/02/13 14:13:08.378431 [ERROR] core: barrier init check failed: error=failed to check for initialization: etcdserver: invalid auth token
2018/02/13 14:13:08.378498 [ERROR] error checking health: error=failed to check for initialization: etcdserver: invalid auth token
2018/02/13 14:13:26.119694 [ERROR] core: failed to read seal configuration: error=etcdserver: invalid auth token

**Expected Behavior:**
shouldn't vault keep renewing token, I didn't see this behavior when i was using vault 0.7.2

**Actual Behavior:**
Fails with invalid auth token

**Comment by raoofm** [comment]
$ curl http://127.0.0.1:8200/v1/sys/init
{"errors":["failed to check for initialization: etcdserver: invalid auth token"]}
$ curl http://127.0.0.1:8200/v1/sys/health
{"errors":[]}
$ curl http://127.0.0.1:8200/v1/sys/seal-status
{"errors":["failed to check seal configuration: etcdserver: invalid auth token"]}

I got expected responses from these curl commands when I started the server, but after some time the token is not refreshed.

**Comment by raoofm** [comment]
@jefferai @xiang90

**Comment by jefferai** [comment]
I'm closing this as it's very old and it's up to the community to address if it's still an issue.

**Comment by raoofm** [comment]
@hexfusion @gyuho fyi
