### ISSUE TITLE
Wrong advertise address guess when consul is on another node

### ISSUE THREAD

**Issue by benschw** [hashicorp/vault#397]
When configuring vault to use consul as its backend, and specifying an address for consul and the listener in the config file, it seems to guess the consul address to use as the advertise address rather than a private ip on the vault server node. 

Running `vault status` also reports the consul address as the leader.

**Comment by armon** [comment]
@benschw The advertise address is a heuristic at best. We use the consul node to discover it, but if the heuristic is not applicable you can specify it explicitly. Hope that helps!

**Comment by benschw** [comment]
cool, that's kinda what I figured. 
thanks!
