### ISSUE TITLE
SIGHUP Reload uses stale config values

### ISSUE THREAD

**Issue by tniswong** [hashicorp/vault#3990]
**Environment:**

* Vault Version: 0.8.0+
* Operating System/Architecture: linux_amd64

**Vault Config File:**

```json
{
  "max_lease_ttl": "1008h",
  "listener": {
    "tcp": {
      "address": "0.0.0.0:8200",
      "cluster_address": "0.0.0.0:8201",
      "tls_cert_file": "/usr/local/share/ca-certificates/localhost.crt",
      "tls_key_file": "/etc/localhost.key",
      "tls_min_version": "tls12"
    }
  },
  "storage": {
    "consul": {
      "scheme": "http",
      "address": "127.0.0.1:8500"
    }
  }
}
```

**Startup Log Output:**

**Expected Behavior:**

When I send a SIGHUP to vault, I expect it to read the values from the config file specified at startup, and update the server with the values from that config file. (Specifically, the tcp listener tls configs https://www.vaultproject.io/docs/configuration/listener/tcp.html)

**Actual Behavior:**

When I send a SIGHUP to vault, new values are NOT read. Instead, the old values are simply reloaded.

**Steps to Reproduce:**

1. Have two sets of self-signed certs/keys available. Take note of the serial numbers or fingerprints so you can identify them.
1. Initialize vault using a configuration similar to above taking note as to which certificate you are using
1. `echo | openssl s_client -connect vault:8200 | openssl x509 -text -noout` verify that vault is using the certificate you told it to.
1. Modify listener.tcp.tls_cert_file and listener.tcp.tls_key_file to point to the other keypair
1. Send a SIGHUP to vault
1. `echo | openssl s_client -connect vault:8200 | openssl x509 -text -noout` vault will still be using the first certificate. This basically confirm that Vault won't read the new config values.
1. Next, we can confirm that Vault does, in fact, reload the OLD config values.
1. `mv /path/to/old.crt /path/to/new.crt && mv /path/to/old.key /path/to/new.key`
1. Send a SIGHUP to vault
1. `echo | openssl s_client -connect vault:8200 | openssl x509 -text -noout` verify that vault is now using the NEW certificate, but only because you overwrote the old one, not because you updated the config.

**Important Factoids:**

This worked correctly in versions <0.8.0
I believe the cause is located in or around https://github.com/hashicorp/vault/blob/master/helper/reload/reload.go

Seems that the Reload() func on CertificateGetter ignores reloaded config values in favor with those it already has.

**References:**

**Comment by jefferai** [comment]
Not a bug; this is by design. Often server key files are extremely locked down and protected, while configuration files are not, or are deployed in much more automated ways; this prevents someone from being able to modify the configuration file to point to an untrusted certificate -- for instance, one where they have access to the key. They would have to actually be able to overwrite the server's cert instead.

**Comment by tniswong** [comment]
Fair enough, can we have a call-out in the docs then? It's pretty misleading.

**Comment by jefferai** [comment]
Sure! ^
