### ISSUE TITLE
Space containing policies render confusingly

### ISSUE THREAD

**Issue by ezyang** [hashicorp/vault#3993]
**Environment:**
```
dhcp-172-30-123-57:~ ezyang$ vault version
Vault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')
```

* Vault Version: Vault v0.9.3
* Operating System/Architecture: Mac OS X 10.13.3

**Vault Config File:** n/a

**Startup Log Output:** n/a

**Expected Behavior:**
I attempted to associate two policies with a user using the following commands:

```
dhcp-172-30-123-57:~ ezyang$ vault write auth/aws/role/ezyang policies="prod jenkins"
Success! Data written to: auth/aws/role/ezyang
dhcp-172-30-123-57:~ ezyang$ vault read auth/aws/role/ezyang 
Key                               Value
---                               -----
allow_instance_migration          false
auth_type                         iam
bound_account_id                  n/a
bound_ami_id                      n/a
bound_iam_instance_profile_arn    n/a
bound_iam_principal_arn           [redacted]
bound_iam_principal_id            [redacted]
bound_iam_role_arn                n/a
bound_region                      n/a
bound_subnet_id                   n/a
bound_vpc_id                      n/a
disallow_reauthentication         false
inferred_aws_region               n/a
inferred_entity_type              n/a
max_ttl                           1800000
period                            0
policies                          [prod jenkins]
resolve_aws_unique_ids            true
role_tag                          n/a
ttl                               0

```

Notice that policies renders as:

```
policies                          [prod jenkins]
```

I expected this to work.

**Actual Behavior:**
It does not work, I don't have permissions. The problem is "prod jenkins" is a policy itself, not the individual policies "prod" and "jenkins".

I don't know if Vault intentionally allows policies with spaces in them, but if it does it should render differently than normal policies.  For reference here is how the correct version renders:

```
dhcp-172-30-123-57:~ ezyang$ vault write auth/aws/role/ezyang policies="prod,jenkins"
Success! Data written to: auth/aws/role/ezyang
dhcp-172-30-123-57:~ ezyang$ vault read auth/aws/role/ezyang 
[snip]
policies                          [jenkins prod]
```

**Comment by jefferai** [comment]
The CLI can't really know the format of data for arbitrary commands, so it defaults to Go's default. Any kind of separator, like commas, that could be used here can also be used in policies since we don't constrain their names. You may want to look at `-format=json` or `-format=yml` as these will be unambiguous.

**Comment by ezyang** [comment]
@jefferai How would I specify reference policy foo,bar that is interpreted as a single policy "foo,bar"? `vault write auth/aws/role/ezyang policies="prod,jenkins"` won't work because it will be interpreted as referencing two policies.

**Comment by jefferai** [comment]
You'll need to specify it as a json away with each policy being an element. This can be done via curl or most API clients, or with the CLI client using @ syntax to specify the input as coming from a json file.
