### ISSUE TITLE
Auth plugins don't have the connection set anymore after grpc plugin

### ISSUE THREAD

**Issue by jhorwit2** [hashicorp/vault#3996]
**Environment:**

* Vault Version: 0.9.3
* Operating System/Architecture: OL7 & Ubuntu 16.04

**Expected Behavior:**

The `Connection` should be set on the `logical.Request` for auth backends which enables the backend to validate the source IP. 

**Actual Behavior:**

The `Connection` is always nil after upgrading to the grpc based plugins. 

**Steps to Reproduce:**

Using a GRPC based auth plugin try to get the `RemoteAddr` of the `Connection` from the request to the plugin.

**Comment by briankassouf** [comment]
@jhorwit2 Thanks for the report, this should be fixed in 0.9.4.

**Comment by jhorwit2** [comment]
Thanks @briankassouf 

Any idea when this and the other plugin related fixes are going to go out in 0.9.4? This is causing a lot of problems for us since it broke a lot of functionality.

**Comment by jefferai** [comment]
It'll be soon.
