### ISSUE TITLE
Database storage credentials are less secure than the credentials stored in the database

### ISSUE THREAD

**Issue by tsprlng** [hashicorp/vault#4004]
When using a database storage backend (e.g. Postgres), credentials for accessing that database must be configured as part of the connection string (if, for example, using a managed database, or in any other situation where alternative access control options are limited).

Unfortunately, those same credentials could be used by a malicious actor (or coerced operator) to access the database directly and corrupt the stored secrets.

Has an implementation been considered where?:

- Read-only credentials are specified in config for a Vault instance to bootstrap itself;

- The instance retrieves write-capable credentials for its own storage from itself once unsealed.

I'd be happy to explore the necessary work but as a still-fairly-naive user, am mainly wondering what pitfalls may be lurking and/or whether a similar idea has already been considered and rejected.

Thanks for reading, for working on Vault, and for any advice!

(Apologies for the probably poor choice of issue title, please feel free to change it to something more succinct and descriptive (I couldn't think of anything)).

**Comment by jefferai** [comment]
This is on the roadmap, with a "soon" timeframe :-)
