### ISSUE TITLE
Outdated Documentation: Secrets Backend

### ISSUE THREAD

**Issue by McSlow** [hashicorp/vault#4008]
This is not about vault itself but the Website/online documentation. If there's a better place to report issues for this kind of topic please close&advise.

Currently the documentation at https://www.vaultproject.io/docs/secrets/pki/index.html
 talks about enabling and using the secrets backend with ```vault secrets enable/tune/..``` throughout the document.

Actually this cli endpoint does not exist (anymore?), at least not in 0.9.1. 
I guess ```vault mount pki``` etc. is meant. 

I guess documentation needs a bit of maintenance here.

regards,
Bjoern

**Comment by jefferai** [comment]
Vault's website tracks the latest released version; the command you reference appeared in 0.9.3. If you need an older copy of docs you can browse Vault's source tree and easily run a copy of the website, see the Makefile in the website/ folder.
