### ISSUE TITLE
LDAP tree not searchable below 2 organizational units.

### ISSUE THREAD

**Issue by planchao** [hashicorp/vault#4015]
Just ran in a flexibility problem with vault. I was trying to use the LDAP auth backend with an existing LDAP tree which contained user CN below 2 organizational units. The depth of the search scope is hardcoded here: https://github.com/hashicorp/vault/blob/f83f41436d0f3f391adabc80c513abe49664c5e2/builtin/credential/ldap/backend.go#L300

It might be sensible to put the search scope into the configuration options of the LDAP auth backend.

**Comment by vishalnayak** [comment]
Per RFC 4511 Section 4.5.1, a `scope` of 2 refers to `wholeSubtree` search. It doesn't seem to mean the depth of the subtree being searched. Did you actually encounter any problems while searching in the subtree?

**Comment by planchao** [comment]
Wow, thanks @vishalnayak. I clearly overread that.
