### ISSUE TITLE
JSON secrets not behaving same in recent versions

### ISSUE THREAD

**Issue by myoung34** [hashicorp/vault#4020]
```
$ docker run -it --entrypoint /bin/sh vault:0.8.1 
/ # echo $'{"a": "b"}' >a
/ # vault write -format=json secret/wut data=@a
/ # vault read -field=data secret/wut
{"a": "b"}
/ # vault read -field=data -format=json secret/wut
{"a": "b"}
```

```
$ docker run -it --entrypoint /bin/sh vault:0.9.4
/ # echo $'{"a": "b"}' >a
/ # vault write -format=json secret/wut data=@a
/ # vault read -field=data secret/wut
{"a": "b"}
/ # vault read -field=data -format=json secret/wut
"{\"a\": \"b\"}\n"
```

**Comment by jefferai** [comment]
Prior versions of Vault did not correctly format data as JSON when reading a field. 0.9.4 correctly formats the output as JSON. Since the value that is in your "data" field is a string, what comes out is a JSON escaped string. If this is not what you want, drop `-format=json` from your CLI command.

**Comment by myoung34** [comment]
Didnt realize it had been fixed. 
@jefferai Is this in the changelog?

**Comment by jefferai** [comment]
I'm not sure. If you don't see it, feel free to send a PR to add it.
