### ISSUE TITLE
Multiple bugs missing from changelog

### ISSUE THREAD

**Issue by myoung34** [hashicorp/vault#4021]
This could be solved easily by singular pull requests, but it speaks more to the process involved internally of how hashicorp generates (or writes) changelogs.

So far client-facing bugfixes missing which directly affected myself (and others by virtue)

 * https://github.com/hashicorp/vault/pull/3987
 * https://github.com/hashicorp/vault/pull/4005

As a customer and consumer its extremely hard to come up with a non-breaking upgrade path if I cant determine what's changed without having to read an entire git diff between releases.

**Comment by jefferai** [comment]
> This could be solved easily by singular pull requests, but it speaks more to the process involved internally of how hashicorp generates (or writes) changelogs.

Changelog bugs are bugs like any other. Things sometimes get missed.

These have now been added.
