### ISSUE TITLE
Unseal operation is returning success, but vault remains sealed

### ISSUE THREAD

**Issue by max-abramowitz-reif-ck** [hashicorp/vault#4023]
We're having an issue on vault unseal where the api call to unseal vault returns success and that vault is unsealed, but logs present an error and vault immediately reseals. We started encountering this issue after upgrading consul, which is our vault backend, from 0.6.4 to 0.9.3.

After turning on trace logging, the errors we get from the unseal operation are:
```
2018/02/21 16:04:00.920710 [INFO ] core: vault is unsealed
2018/02/21 16:04:00.920744 [INFO ] core: entering standby mode
2018/02/21 16:04:00.991144 [INFO ] core: acquired lock, enabling active operation
2018/02/21 16:04:00.992996 [ERROR] core: error performing key upgrades: error=error reloading keyring: Unseal failed, invalid key
2018/02/21 16:04:00.993104 [DEBUG] core: marked as sealed
2018/02/21 16:04:00.993130 [TRACE] core: clearing forwarding clients
2018/02/21 16:04:00.993135 [TRACE] core: done clearing forwarding clients
2018/02/21 16:04:01.025900 [DEBUG] core: sealing barrier
2018/02/21 16:04:01.025917 [INFO ] core: vault is sealed
```
This is despite a successful unseal message being returned from the api call.

One suspected issue is that we are using consul replicate to replicate pertinent vault k/v values to this datacenter, which we have never had a problem with that in the past. The unseal keys we are using were generated at our source datacenter, and then replicated to this one. These keys were working at the problem datacenter before upgrading consul.

**Environment:**
* Vault Version: 0.8.3, consul version 0.9.3
* Operating System/Architecture: CentOS 6.8

**Startup Log Output:**
```==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://10.0.0.0:8201
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "enabled")
               Log Level: trace
                   Mlock: supported: true, enabled: true
        Redirect Address: https://10.0.0.0:8200
                 Storage: consul (HA available)
                 Version: Vault v0.8.3
             Version Sha: 6b29fb2b7f70ed538ee2b3c057335d706b6d4e36

==> Vault server started! Log data will stream in below:

2018/02/21 15:58:31.484490 [DEBUG] physical/consul: config path set: path=vault
2018/02/21 15:58:31.484544 [WARN ] physical/consul: appending trailing forward slash to path
2018/02/21 15:58:31.484550 [DEBUG] physical/consul: config disable_registration set: disable_registration=false
2018/02/21 15:58:31.484555 [DEBUG] physical/consul: config service set: service=vault
2018/02/21 15:58:31.484560 [DEBUG] physical/consul: config service_tags set: service_tags=
2018/02/21 15:58:31.484569 [DEBUG] physical/consul: config address set: address=127.0.0.1:8500
2018/02/21 15:58:31.508641 [TRACE] cluster listener addresses synthesized: cluster_addresses=[0.0.0.0:8201]
```

**Expected Behavior:**
Expected vault server to be unsealed
**Actual Behavior:**
unseal api endpoint gave success message, vault did not unseal

**Important Factoids:**
consul replicate is replicating the unseal k/v info from a source datacenter

**Comment by jefferai** [comment]
Keyring reloading happens right after unsealing and uses the same path as the initial unseal, but the difference is that the key used for decryption comes from the stored value inside the keyring itself. If this isn't working it suggests your keyring is corrupt. It is very possible that this is a result of using consul-replicate, which is not a safe way to replicate vault data, but I couldn't say for sure since it means there's not really any way for me to understand what state your data is in. You indicated this is only happening on the downstream vault, so it does seem to suggest that your usage of consul-replicate is the issue.
