### ISSUE TITLE
Feature Request:  Add GET database/config to return list of configuration keys.

### ISSUE THREAD

**Issue by ja391045** [hashicorp/vault#4026]
**Feature Request:**

Allow config/database to return a list of configuration keys.

I'm writing a puppet module to interface with vault and setup database configurations as part of our automation system.   For things like sys/policies or database/roles I can query a list of available keys under each path, and then query each key individually.    This is important to puppet, because the vault module can build a set of Puppet::Type resources for each key.  That way, if roles or policies are modified outside of a puppet operation, the next puppet run can "see" those changes and take them into account.  This is useful, for instance, to allow Puppet to modify a configuration which was originally set up outside of Puppet.

Since I can't query a list of database configurations from this endpoint, I'll have to keep a list of configurations that Puppet has created inside a scratch file on the host, or within a Puppet::Fact.  That means future runs of puppet will only "see" those specific database configurations a particular puppet agent has created.   If they are changed outside of puppet, or multiple puppet agents create configurations, a specific agent will not see those changes.

**Environment:**

* Vault Version:  0.9.3
* Operating System/Architecture: CentOS 7/x86_64

**Expected Behavior:**
```
curl -X GET -k --header "X-Vault-Token=`cat /root/.vault-token`" \
  http://localhost:8200/v1/database/config
{ "keys": ["my-db-config-one", "my-db-config-two"] }
```
**Actual Behavior:**
```
curl -X GET -k --header "X-Vault-Token=`cat /root/.vault-token`" \
  http://localhost:8200/v1/database/config
{"errors":["1 error occurred:\n\n* unsupported operation"]}
```
**Steps to Reproduce:**
Run the curl commands.

**Comment by ja391045** [comment]
Also to note, for the purposes of the current Puppet Provider model I'm working on, the vault CLI client should be able to retrieve this list of keys as well:

```
vault read database/config
{ "keys": ["my-db-config-one", "my-db-config-two"]}
```

**Comment by chrishoffman** [comment]
You can use the LIST custom HTTP verb or add the parameter ?list=true to the GET request.  It looks like it is missing in the documentation.  I'll add it shortly.

**Comment by chrishoffman** [comment]
Additionally, from the CLI, you can issue the following command:

```
vault list database/config
```

**Comment by ja391045** [comment]
Outstanding!  That works like a champ.  Thanks!
