### ISSUE TITLE
PKI doc has wrong commands

### ISSUE THREAD

**Issue by medyagh** [hashicorp/vault#4029]
The PKI  docs has a command that when you run it says the command is not there.

`
vault secrets enable pki
`

https://github.com/hashicorp/vault/blame/166db9275e5e97daaadba6b24a08ae62d85cb73a/website/source/docs/secrets/pki/index.html.md#L37

**Comment by jefferai** [comment]
The documentation corresponds to the latest released version of Vault. The CLI commands changed in 0.9.2 (but with backwards compatibility). You can easily make an older version of the website from source by using the `make website` command from the `website` folder with any checkout you like.
