### ISSUE TITLE
Vault Neo4j database plugin for secret engine

### ISSUE THREAD

**Issue by peterclemenko** [hashicorp/vault#4046]
**Feature Request:**
A Vault plugin for allowing connection to a Neo4J database would help with using Vault to authenticate with Neo4j.

**Comment by pocorschi** [comment]
I'm guessing there's still no plugin available for neo4j correct @aoighost ?

**Comment by leandrohmvieira** [comment]
Any updates on this?

**Comment by jamesdhope** [comment]
any update please?

**Comment by hsimon-hashicorp** [comment]
Hi folks! I don't have any update for you, I apologize about that. This might be an opportunity to have a community-supported secrets engine / storage backend in the meantime. I'll keep tracking this request as well, and provide feedback to the team. Thanks!

**Comment by eh-steve** [comment]
Hey all, I've opened this PR as an initial implementation: https://github.com/hashicorp/vault/pull/16020

**Comment by aphorise** [comment]
@peterclemenko @leandrohmvieira @pocorschi @jamesdhope - Hey I'm curious if you folks have tried the plugin that's been done by @eh-steve (👍) & if you're okay to close this issue.

**Comment by hsimon-hashicorp** [comment]
Closing due to available workaround and issue age

**Comment by laocoon2525** [comment]
I have implemented a V5 plugin compatible version for Neo4j. The code is still beta:
https://github.com/HomaiLabs/neo4j-vault-database-plugin
I would appropriate any feedback/review.
