### ISSUE TITLE
Go builds with Travis are using unpatched releases

### ISSUE THREAD

**Issue by philpennock** [hashicorp/vault#4047]
* Vault Version: 0.9.5

**Important Factoids:**

Commit b84984ca1 edited `.travis.yml`, dropping the specifier for the version of Go from `"1.10"` to `"1.9"`; before the bump upwards, it had been on `"1.9.1"`.  Go releases versions without a patch number, thus `1.9` is an actual release, not a series.  Thus anything built with Travis has gone backwards further than expected.

To get "the latest stable release with security fixes", you want the `.x` suffix, which is handled by Travis in internal mapping tables, and so using `"1.9.x"` will become `"1.9.4"`

See https://golang.org/doc/devel/release.html#go1.9 for the changes in the patch-level updates.

**Comment by catsby** [comment]
Hello - I apologize for the very, _very_ late reply. I'm going to close this issue however, as we no longer use TravisCI with this repository. Thanks!
