### ISSUE TITLE
Vault fails with `missing advertisement address` using zookeeper

### ISSUE THREAD

**Issue by victorcampos** [hashicorp/vault#405]
I built vault from src, based on the master branch today (07/07/2015), when I try to start it with this configuration:
```
backend "zookeeper" {
  address = "<LIST OF MY ZOOKEEPER SERVERS>"
  path = "vault"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}
```
It fails to initialize and gives me `Error initializing core: missing advertisement address` as output.

Is Zookeeper a HA backend now?

**Comment by armon** [comment]
@victorcampos Yep! ZK supports HA mode, but does not implement a heuristic for detecting the advertise address.

**Comment by F21** [comment]
Seeing this too. Are there any plans to get ZK to detect the advertise address?

**Comment by armon** [comment]
Eventually. It is low priority since it can be specified.

**Comment by jefferai** [comment]
ZK was contributed by the community; patches to implement this from the community are welcome. I'm going to close this in favor of a pull request implementing this behavior.
