### ISSUE TITLE
Vault binary in interactive tutorial is out of date

### ISSUE THREAD

**Issue by BRMatt** [hashicorp/vault#4050]
**Expected Behavior:**
The interactive tutorial referenced on Vault's homepage should be using a reasonably recent version of vault.

**Actual Behavior:**
The site is running 0.5.2, which is almost 2 years out of date.

**Steps to Reproduce:**
Open the interactive tutorial referenced on the homepage and enter `vault version`.

**Important Factoids:**
The fact that folks who're looking at vault for the first time can jump straight into a terminal and play around with it is incredible. It'd be nice if they could experience the latest version.

**Comment by jefferai** [comment]
This has been updated!
