### ISSUE TITLE
api request to pki engine to update/create roles fails on allowed_domains field

### ISSUE THREAD

**Issue by pete911** [hashicorp/vault#4057]
request to create/update role:
```
curl -v -X POST -H 'X-Vault-Token: <token>' -d '{... ,"allowed_domains":["some_domain"], ...}' https://<vault_host>/v1/<pki>/roles/oidc
```
produces error:
```
{"errors":["1 error occurred:\n\n* Error converting input [some_domain] for field allowed_domains: '' expected type 'string', got unconvertible type '[]interface {}'"]}
```

API documentation for [create/update role](https://www.vaultproject.io/api/secret/pki/index.html#create-update-role) states that the field should be list of strings. It is in the API example as well.

**Environment:**
* Vault Version: 0.7.2
* Operating System/Architecture:

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

**Actual Behavior:**

**Steps to Reproduce:**

**Important Factoids:**

**References:**

**Comment by jefferai** [comment]
You didn't fill out the version... What version is this?

**Comment by pete911** [comment]
sorry, updated ("version":"0.7.2")

**Comment by jefferai** [comment]
The ability to use an array for that option appeared in 0.9.1. The documentation always corresponds to the latest released version...you can browse github at the appropriate tag if you want to see earlier docs.
