### ISSUE TITLE
Vault policy conflict

### ISSUE THREAD

**Issue by Gabology** [hashicorp/vault#4061]
I am having an issue with two conflicting policies, the first policy allows access to the parent path but denies all items listed under a specific subpath, the second policy allows access to this specific subpath. However when attaching both policies to a token the token is still unable to access any secrets under this specific subpath. In this case it seems like the deny directive takes precedence over the allow directive and this seems to be documented but in that case I am not sure how to model the ACL to fit this use case where we want to allow access to all subpaths of a secret EXCEPT for some specific ones, essentially a blacklist system.

**Environment:**
* Vault Version: v0.9.5

**Expected Behavior:**
Should be able to access the specific child path.

**Actual Behavior:**
Getting permission denied for the specific child path.

**Steps to Reproduce:**
Create a policy 'foo' like so:

```hcl
# Allow access to all subpaths under secret/foo
path "secret/foo/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

# Except for secret/foo/bar/*
path "secret/foo/bar/*" {
  capabilities = ["deny"]
}
```

Create another policy 'bar' like so

```hcl
# allow access to secret/foo/bar/*
path "secret/foo/bar/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
```

Create a token and attach both policies.

**Comment by joelthompson** [comment]
I believe you can do this by just specifying an empty list on the capabilities in foo, i.e.,

```hcl
# Allow access to all subpaths under secret/foo
path "secret/foo/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

# Except for secret/foo/bar/*
path "secret/foo/bar/*" {
  capabilities = []
}
```

If you do that, then the `foo` policy grants no access to the `secret/foo/bar/*` section:

```bash
$ vault policy write foo <(echo '# Allow access to all subpaths under secret/foo)
path "secret/foo/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

# Except for secret/foo/bar/*
path "secret/foo/bar/*" {
  capabilities = []
}')
Success! Uploaded policy: foo
$ vault token create -policy=foo
Key                Value
---                -----
token              ec70e6c4-7157-fdb5-7fde-f13bc8d520c4
token_accessor     44cdbe27-d1c3-541e-e278-16d8312ddcb4
token_duration     768h
token_renewable    true
token_policies     [default foo]
$ VAULT_TOKEN=ec70e6c4-7157-fdb5-7fde-f13bc8d520c4 vault write secret/foo/asdf bar=baz
Success! Data written to: secret/foo/asdf
$ VAULT_TOKEN=ec70e6c4-7157-fdb5-7fde-f13bc8d520c4 vault write secret/foo/bar bar=baz
Success! Data written to: secret/foo/bar
$ VAULT_TOKEN=ec70e6c4-7157-fdb5-7fde-f13bc8d520c4 vault write secret/foo/bar/baz bar=baz
Error writing data to secret/foo/bar/baz: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/secret/foo/bar/baz
Code: 403. Errors:

* permission denied
```

Then, you should be able to attach another policy (e.g., your `bar`) which does grant some explicit access without it being overridden.

**Comment by jefferai** [comment]
Joel is correct. An explicit `deny` will override any other grants, but since Vault is no-access by default, simply starting with an empty set (providing no access) and then adding more capabilities is the way to go!
