### ISSUE TITLE
Make default lease duration configurable.

### ISSUE THREAD

**Issue by rtkwgray** [hashicorp/vault#407]
It would be nice if one could configure the default lease duration via the configuration file. We'd like a way to specify a default lease duration of shorter than 30 days because we have services that read from Vault  but also throw away their lease IDs when they're restarted, so there's no way to renew. This results in a large number of leases being created that won't expire for 30 days.

**Comment by armon** [comment]
Tagged as enhancement, I agree we should allow shortening at the least. Extending past 30d would make me uncomfortable.
