### ISSUE TITLE
ENABLE_VIRTUAL_TERMINAL_PROCESSING to output properly ANSI color on Windows 10 Fall creator Update

### ISSUE THREAD

**Issue by tebeco** [hashicorp/vault#4070]
**Feature Request:**
When targeting Win10 x64, please set `ENABLE_VIRTUAL_TERMINAL_PROCESSING`
I thought i miss configured my console, see details here :
https://github.com/Microsoft/console/issues/123

**Environment:**
Win 10 Fall Creator Update

* Vault Version:
```
>vault -v
[0;0mVault v0.9.5 ('36edb4d42380d89a897e7f633046423240b710d9')[0m
```
* Operating System/Architecture: 
Win 10 Fall Creator Update
x64
10.0.17110.1000

**Comment by tebeco** [comment]
@jefferai Thx a lot ;)

**Comment by tebeco** [comment]
It feel that what's required to do will look like this in go :

https://github.com/hashicorp/vault/blob/c44f1c9817955d4c7cd5822a19fb492e1c2d0c54/vendor/github.com/bgentry/speakeasy/speakeasy_windows.go
This existing code use ENABLE_ECHO_INPUT so this is just a base to use as a sample

I have no idea (not yet) how to read / write / build / test anything in GO ^^

MSDN info are here :
https://docs.microsoft.com/en-us/windows/console/getconsolemode

and it will probably require both :
ENABLE_VIRTUAL_TERMINAL_INPUT = 0x0200
ENABLE_VIRTUAL_TERMINAL_PROCESSING = 0x0004

**Comment by jefferai** [comment]
@tebeco this really needs to get fixed via the CLI library we use...I plan to address it through there at some point soon. In the meantime if this is tripping you up you can set VAULT_CLI_NO_COLOR to some value to turn off color.

**Comment by johnradke** [comment]
This is also an issue in Windows 7 on x64.

```
>vault -version
←[0;0mVault v0.9.5 ('36edb4d42380d89a897e7f633046423240b710d9')←[0m

>ver

Microsoft Windows [Version 6.1.7601]
```

**Comment by tebeco** [comment]
is there a way to get the executable from the 0.10.x RC so that i can test it ?
or do i have to wait for a release ?
