### ISSUE TITLE
plugin.vault-plugin-database-oracle: plugin tls init: error="error during token unwrap request: secret is nil

### ISSUE THREAD

**Issue by bajju31** [hashicorp/vault#4072]
**Environment:**
0.9.5

* Vault Version:
* Operating System/Architecture:
Ubuntu 16_04 

**Vault Config File:**

* plugin directory under vault home */
plugin_directory = "/opt/vault/plugin"
api_addr = "https://127.0.0.1:8300"
# also tried API address with only http
# also tried api address with 0.0.0.0

max_lease_ttl = "10h"
default_lease_ttl = "4h"

storage "inmem" {
  path = "/opt/vault/data"
}

listener "tcp" {
    address = "0.0.0.0:8210"
    tls_disable = "false"
    // decrypted certificate key
    tls_cert_file = "tls/vault.server.pem"
    // decrypted private key
    tls_key_file  = "tls/localhost.decrypted.key.pem"
    tls_require_and_verify_client_cert = "false"
    tls_client_ca_file = "tls/vault.server.pem"
}

disable_mlock = true /* for dev, mlock is not available on WSL */
**Startup Log Output:**

vault server -dev -config config/d.hcl
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8301
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
              Listener 2: tcp (addr: "0.0.0.0:8210", cluster address: "0.0.0.0:8211", tls: "enabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
        Redirect Address: https://127.0.0.1:8300
                 Storage: inmem
                 Version: Vault v0.9.5
             Version Sha: 36edb4d42380d89a897e7f633046423240b710d9

WARNING! dev mode is enabled! In this mode, Vault runs entirely in-memory
and starts unsealed with a single unseal key. The root token is already
authenticated to the CLI, so you can immediately begin using Vault.

You may need to set the following environment variable:

    $ export VAULT_ADDR='http://127.0.0.1:8200'

The unseal key and root token are displayed below in case you want to
seal/unseal the Vault or re-authenticate.

Unseal Key: 20Uy70tsNc4aHQWMqPLDrSg8GYl7Z1CQnFsU8Y2e7WI=
Root Token: 755aa7de-c507-c88d-b915-cc23cacaf258

Development mode should NOT be used in production installations!

**Expected Behavior:**

Plugin keeps on failing, when trying to register it with below  

vault write database/config/HSHCRPDB plugin_name=vault-plugin-database-oracle connection_url=hshcrp/hashicorp@//localhost:1521/HSHCRPDB 'allowed_roles=[admin, readWrite, readOnly]'

plugin is downloaded and available on the plugins directory. 
Instant client is installed and folder on LD_LIBRARY_PATH 

**Actual Behavior:**

Errors below 

2018/03/04 04:23:17.288587 [INFO ] core: successful mount: path=database/ type=database
2018/03/04 04:23:22.036030 [ERROR] plugin.vault-plugin-database-oracle: plugin tls init: error="error during token unwrap request: secret is nil"
**Steps to Reproduce:**

Use 
vault 0.9.5
latest version of oracle plugin 
config file as above, running in dev mode (without dev mode also same issue) 

**Important Factoids:**

**References:**

**Comment by jefferai** [comment]
This is likely due to the mismatch on the port between your api_addr and your listener address. Can you fix the api_addr and try again?

**Comment by bajju31** [comment]
I tried different api_address from 8210 to 8300..., still same result . see my config attached. 
tried with tls enable/ disable...
in dev mode or no ... 
with ip address, as 0.0.0.0 ...
with localhost as hostname...

Baffling thing is it was working about 10 days back. Don't know what I messed up.. 

There ought to be a better message/way to troubleshoot this issue, than this very cryptic message. 

[d.txt](https://github.com/hashicorp/vault/files/1778550/d.txt)

**Comment by jefferai** [comment]
What changed in the last 10 days? Did you change config? Did you change the version of the plugin or Vault?

**Comment by sapdbajaj** [comment]
I went back to older versions (vault 0.9.3 still same issue), still the same thing. Do not know, how to troubleshoot. Really struggling for past 14 hours straight with this :( 

very simple config, trying to use dev server and get the plugin to work with it. 
and hence used following config 
`plugin_directory = "."
api_addr = "https://localhost:8300"

max_lease_ttl = "10h"
default_lease_ttl = "4h"
pid_file = "data/pidfile"

listener "tcp" {
    address = "0.0.0.0:8400"
    tls_disable = "false"
    // decrypted certificate key
    tls_cert_file = "vault.crt.pem"
    // decrypted private key
    tls_key_file  = "vault.key.pem"
    tls_require_and_verify_client_cert = "false"
    tls_client_ca_file = "vault.crt.pem"
}

storage "inmem" {
  path = "./data"
}

disable_mlock = true `
Am pretty sure, it previously worked with 0.9.3 and oracle plugin. 

I see following message on console, after error message 
`expiration: revoked lease: lease_id=sys/wrapping/wrap/35d3bfbc9cd3359091d36ce80d40bd3cda7e948f`

My client env is setup as below 
`set VAULT_ADDR=http://127.0.0.1:8200
# also tried setting it to https://127.0.0.1:8400 

set VAULT_TOKEN=7e7b3303-8142-e863-8e17-846b38b1ae97
set VAULT_CACERT=C:\utils\vault\vault.crt.pem
set VAULT_TLS_SERVER_NAME=vault.analyzeaws.com

```
vault secrets enable database

vault write sys/plugins/catalog/vault-plugin-database-oracle  sha_256=086c50770b4ed89e768f7864c310baa2871986fb2cef7f781a7ec826d9ff0a50  command="vault-plugin-database-oracle"

vault write database/config/HSHCRPDB plugin_name=vault-plugin-database-oracle  connection_url="hshcrp/hashicorp@//localhost:1521/HSHCRPDB"`

```
Last line gives the error persistently 

> [ERROR] plugin.vault-plugin-database-oracle: plugin tls init: error="error during token unwrap request: secret is nil"
and about a minute later I see the error message 
`expiration: revoked lease: lease_id=sys/wrapping/wrap/35d3bfbc9cd3359091d36ce80d40bd3cda7e948f`

Use the prebuilt binary for oracle plugin for Linux. 

The certs are attached as txt files. 
[ca.crt.txt](https://github.com/hashicorp/vault/files/1778782/ca.crt.txt)
[vault.crt.pem.txt](https://github.com/hashicorp/vault/files/1778783/vault.crt.pem.txt)
[vault.key.pem.txt](https://github.com/hashicorp/vault/files/1778784/vault.key.pem.txt)

Could I request **please** you to kindly share example config file and client env configuration which would work with oracle plugin.

**Comment by jefferai** [comment]
Can you please provide trace logs of startup though trying to get a secret? Also can you fully specify your plugin directory with an absolute path?

**Comment by sapdbajaj** [comment]
Also tried running vault as root or user "vault", same effect. 
Vault is installed in `/opt/vault` with user as `"vault:vault"` , vault has oracle as secondary group. 
Oracle instant client is installed in` /opt/oracle` with user as "`oracle:oracle`" 

Put the oracle plugin in same directory as vault. 
```
echo $LD_LIBRARY_PATH
:/opt/oracle/instantclient_12_2
```

**Comment by jefferai** [comment]
plugin_directory = "."
api_addr = "https://localhost:8300"

I mean that plugin directory. And your api_addr is definitely wrong and that will definitely cause a problem spinning up the plugin, even if it's not the only problem.

I still need logs to get a better idea, and I still think that something changed in the last 10 days on the system, or with Vault. Things don't normally just stop working suddenly.

**Comment by sapdbajaj** [comment]
updated per your guidance. 
I know, there is something I mucked up, can not figure out what anymore :( 

have changed all paths to be absolute. 
all the information is in attached zip 

*Brief Summary* 
(1) vault server is 0.9.5 on Ubuntu 16_04
(2) client is on same server 
(3) server /etc/hosts is changed to alias 127.0.0.1 as vault.analyzeaws.com 
(4) certs are self signed, for vault.analyzeaws.com 

[junk.zip](https://github.com/hashicorp/vault/files/1778844/junk.zip)

appreciate your help and it would be great if you could share a working sample for config on localhost.

**Comment by sapdbajaj** [comment]
Jeff,
Appreciate your help. I am a bit confused when you say api_addr is incorrect. Could you kindly suggest what it could be instead ? 
I tried to keep the port separate for apI_address and listener address. they are on two different ports.

**Comment by sapdbajaj** [comment]
Am confused from the doc completly, for database plugin, 
(1) do we need to define api_addr or
(2) we do not need to define api_addr 

For plugin system it indicates api_addr is needed, but for database backend, it does not indicate that. 

Appreciate your guidance on above.

**Comment by sapdbajaj** [comment]
if I remove api_addr completely then I receive different error message as below 

2018/03/04 18:04:50.159031 [DEBUG] plugin: starting plugin: path=/opt/vault/plugin/vault-plugin-database-oracle args=[/opt/vault/plugin/vault-plugin-database-oracle]
2018/03/04 18:04:50.175289 [DEBUG] plugin: waiting for RPC address: path=/opt/vault/plugin/vault-plugin-database-oracle
2018/03/04 18:04:50.304665 [DEBUG] plugin.vault-plugin-database-oracle: plugin address: address=/tmp/plugin595016113 network=unix
2018/03/04 18:04:50.358071 [TRACE] database: operation=Initialize status=started type=oci8 transport=gRPC
2018/03/04 18:04:50.494925 [TRACE] database: operation=Initialize status=finished type=oci8 transport=gRPC verify=true err=rpc error: code = Unknown desc = error verifying connection: ping failed took=136.841ms
2018/03/04 18:04:50.496855 [TRACE] database: operation=Close status=started type=oci8 transport=gRPC

**Comment by jefferai** [comment]
Whether api_addr is necessary depends on your setup but it never hurts to define it. It should be the address used to reach your Vault server's API, just as from the CLI. So this will almost always be port 8200 unless you change it to something else like 8210.

**Comment by sapdbajaj** [comment]
ok got it, then it has got nothing to with the rpc comms between server and plugin. 
Presume this rpc comms between server and plugin is then not needing any configuration. 

So my the documentation which alludes to set, api_addr for plugin communications is kind of misleading. 

Still baffled though, why it just wont work. Obviously I am doing something stupid, not able to determine what yet.

**Comment by sapdbajaj** [comment]
I think I found the reason. 
I see following trace message in sqlnet.log 
(DESCRIPTION=(CONNECT_DATA=(SERVICE_NAME=HSHCRPDB)(CID=(PROGRAM=vault-plugin-database-oracle)(HOST=deepakXPS)(USER=vault)))(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521)))

Looks like `vault-plugin-database-oracle` plugin is picking up the local OS username (`"vault"`, and not the username from the connect string, when connecting/doing a ping to the oracle instance. 

Connect string as specified is as below 
`"hshcrp/hashicorp@//127.0.0.1:1521/HSHCRPDB"`

Complete vault command being 
`vault write database/config/hshcrpdb plugin_name=vault-plugin-database-oracle  connection_url="hshcrp/hashicorp@//127.0.0.1:1521/HSHCRPDB" allowed_roles="[readOnly, readWrite, admin]"`

Based on this, i would have imagined the plugin to use `hshcrp` instead of `vault `as username for ping to the database. 

This is plugin version 0.1.13 (latest version)

**Comment by sapdbajaj** [comment]
Found the issue, it was in the connection url, I had switched to using local instance of oracle, which is setup using SID instead of service name. 

The plugin work with the oracle instance configured using service name but not with service id. 

Still, it is baffling that setting up the API_ADDR makes the plugin to not work at all. 

so in end, for oracle plugin to work, following is the working formula
(1) do not use API_ADDR
(2) do not use SID in the connection url, use SERVICE_NAME only. 

Thanks 
Deepak

**Comment by mjtice** [comment]
I'm also having this problem.   When I try to write config to the backend via:
`vault write snow_oracle/config/vwshp plugin_name=vault-plugin-database-oracle connection_url="deploy_usr/[redacted]@//lgdssshpdb01:1521/vwshp" allowed_roles="vwshp"`

I get the error:
> Error writing data to snow_oracle/config/vwshp: Error making API request.
> 
> URL: PUT http://10.20.18.40:8200/v1/snow_oracle/config/vwshp
> Code: 400. Errors:
> 
> * error creating database object: rpc error: code = Unknown desc = error verifying connection: ping failed

The message on the database-side listener log shows a connection being made - but the USER is not the user specified in the `connection_url`:

> <msg time='2018-03-09T06:37:54.152-07:00' org_id='oracle' comp_id='tnslsnr'
>  type='UNKNOWN' level='16' host_id='lgdssshpdb01'
>  host_addr='10.4.7.79'>
>  <txt>09-MAR-2018 06:37:54 * (CONNECT_DATA=(SERVICE_NAME=vwshp)(CID=(PROGRAM=vault-plugin-database-oracle)(HOST=hashi01)(USER=vault))) * (ADDRESS=(PROTOCOL=tcp)(HOST=10.20.18.40)(PORT=56883)) * establish * vwshp * 0
> </msg>

Logging on the vault server shows:

> Mar  9 06:41:22 hashi01 vault: 2018/03/09 06:41:22.454965 [DEBUG] plugin.vault-plugin-database-oracle: plugin address: address=/tmp/plugin960322467 network=unix
> Mar  9 06:41:22 hashi01 vault: 2018/03/09 06:41:22.527970 [TRACE] database: operation=Initialize status=started type=oci8 transport=gRPC
> Mar  9 06:41:22 hashi01 vault: 2018/03/09 06:41:22.589469 [TRACE] database: operation=Initialize status=finished type=oci8 transport=gRPC verify=true err=rpc error: code = Unknown desc = error verifying connection: ping failed took=61.499132ms
> Mar  9 06:41:22 hashi01 vault: 2018/03/09 06:41:22.589555 [TRACE] database: operation=Close status=started type=oci8 transport=gRPC
> Mar  9 06:41:22 hashi01 vault: 2018/03/09 06:41:22.867698 [DEBUG] plugin: plugin process exited: path=/etc/vault.d/plugins/vault-plugin-database-oracle
> Mar  9 06:41:22 hashi01 vault: 2018/03/09 06:41:22.867785 [TRACE] database: operation=Close status=finished type=oci8 transport=gRPC err=<nil> took=278.228868ms

Vault version:
`# vault -versionVault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')`

Plugin version:
`# sha256sum plugins/vault-plugin-database-oracle
086c50770b4ed89e768f7864c310baa2871986fb2cef7f781a7ec826d9ff0a50  plugins/vault-plugin-database-oracle`

OS:
`CentOS Linux release 7.2.1511 (Core)
kernel 3.10.0-327.el7.x86_64`

Oracle Instant Client:
`oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64`

Configuration:
```
cluster_name = "pc1"
max_lease_ttl = "768h"
default_lease_ttl = "768h"

listener "tcp" {
  address = "10.20.18.40:8200"
  tls_disable = "true"
}

backend "consul" {
  address = "127.0.0.1:8500"
  datacenter = "pc1"
  path = "vault"
  service = "vault"
  cluster_addr = "http://10.20.18.40:8201"
  redirect_addr = "http://10.20.18.40:8200"
  disable_clustering = "False"
  }

plugin_directory = "/etc/vault.d/plugins"
api_addr = "http://10.20.18.40:8200"
```

**Comment by sapdbajaj** [comment]
remove api_addr from config, it shuld work then.

Sincerely
Deepak Bajaj
+1.5184962532
________________________________

**Comment by mjtice** [comment]
Nope.  I commented out the line and restarted the cluster.  Same problem.

**Comment by bajju31** [comment]
Are you using SID or service name for the oracle ?
It does not work with oracle SID, if you are wanting to use the SID, do one of below

  1.  Query the configured oracle database, to determine the service name

select value from v$parameter where name like '%service_name%';

Use the service name as returned

OR

  1.  Change the connection url, to have :SID as suffix, instead of /SID, in your example I see you are using

deploy_usr/[redacted]@//lgdssshpdb01:1521/vwshp

I would suggest you confirm that oracle service name is define as “vwshp”

It is likely you are using the oracle SID, I did (1) above to query the service name for the SID and put that into the connection url.



Hope this helps.

Deepak

**Comment by mjtice** [comment]
I verified that `vwshp` is in fact a service_name
```>show parameter service

NAME				     TYPE					  VALUE
------------------------------------ -------------------------------------------- ------------------------------
service_names			     string					  vwshp

**Comment by sapdbajaj** [comment]
Ok
I would suggest try
To do a TNSPing to the oracle server, after login as “vault” user, this would help establish if actually the connection url is culprit or is there something else which is blocking the ping.

I also noticed that rpc agent in oracle is creating a temp file on /tmp, and would suggest to ensure and check your umask is correct, try setting it to be 000, see if that works – to rule it out.

Check, the plugin folder you have, under /etc, is “+x” for vault user. I would again suggest momentarily to put the plugin folder in same dir as vault user – again to rule that out.

Lastly, I would suggest, that you have followed the instant client install correctly for centOS.
Follow http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html
I would confirm, there is only ORACLE_HOME in the path, and your LD_LIBRARY_PATH is setup correctly.

Try and hopefully this resolves and/or provides you hints to remediate.

Regards,
Deepak

**Comment by mjtice** [comment]
It shouldn't be trying to log in as `vault`, it should be using the user I specified in the `connection_url`: `deploy_usr`.  `/tmp` is chmod 777.  The permissions on `/etc/vault.d/plugins` are: 
```
# stat plugins/
  File: ‘plugins/’
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 801h/2049d	Inode: 269994      Links: 2
Access: (0755/drwxr-xr-x)  Uid: (  992/   vault)   Gid: (    1/     bin)
```
The plugin has the same perms (minus the dir flag):
```
# stat plugins/vault-plugin-database-oracle
  File: ‘plugins/vault-plugin-database-oracle’
  Size: 16084304  	Blocks: 31416      IO Block: 4096   regular file
Device: 801h/2049d	Inode: 270106      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (  992/   vault)   Gid: (    1/     bin)
```

**Comment by sapdbajaj** [comment]
i know, it takes os user, rather than the user specified in connection url.
but having said that, all it is doing is trying to do a tnsping, so user should not matter.

i agree though it should not be using “user” at all in the ping.

Sincerely
Deepak Bajaj
+1.5184962532
________________________________

**Comment by mjtice** [comment]
Thanks for the pointer, Deepak.  I installed sqlPlus binary via `oracle-instantclient12.2-sqlplus-12.2.0.1.0-1.x86_64.rpm` and tested it out.

```
# ./sqlplus deploy_usr/[redacted]@lgdssshpdb01:1521/vwshp

SQL*Plus: Release 12.2.0.1.0 Production on Mon Mar 12 10:26:03 2018

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

ERROR:
ORA-24454: client host name is not set
```

I remember this error is related to a misconfigured `/etc/hosts` file.  So I appended the hostname and fqdn of the host to the `127.0.0.1` line and that did the trick.

**Comment by sapdbajaj** [comment]
glad it worked out

Sincerely
Deepak Bajaj
+1.5184962532
________________________________

**Comment by mjtice** [comment]
Just wanted to leave another update on this.  I encountered this issue again on a test host.  The `/etc/hosts` file was updated (per my previous comment) - but I was still getting the same error.  After installing the sqlplus rpm (and updating my LD_LIBRARY_PATH) I saw that the user I was trying to connect with had no access:

```
./sqlplus c##stackstorm/password@//clouddb01/pdb2

SQL*Plus: Release 12.1.0.2.0 Production on Tue Jun 26 13:26:24 2018

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

ERROR:
ORA-01045: user C##STACKSTORM lacks CREATE SESSION privilege; logon denied

```

After I adjusted the permissions on the database I was able to write my config to vault.

**Comment by sanjay302** [comment]
Hi, I am not able to go configure plugin for oracle. getting the following errors.


[root@ip-10-159-8-7 ~]# vault write sys/plugins/catalog/oracle-database-plugin sha256="69a3db19c83d5e7c5887d93955949e05b040788d0512f07a40df4dd5614f3f98"  command=vault-plugin-database-oracl
Error writing data to sys/plugins/catalog/oracle-database-plugin: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/plugins/catalog/oracle-database-plugin
Code: 500. Errors:

* 1 error occurred:

* could not set plugin, plugin directory is not configured
