### ISSUE TITLE
Vault keeps getting sealed

### ISSUE THREAD

**Issue by vamsi-vz** [hashicorp/vault#4079]
**Environment:**
Vault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')

* Vault Version:
* Operating System/Architecture:
Red Hat Enterprise Linux Server release 7.4 (Maipo)

**Vault Config File:**
storage "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
}

listener "tcp" {
 address = "0.0.0.0:8200"
 tls_disable = 1
}
**Startup Log Output:**
Mar 05 19:10:12 mds7.sdn-vz.net vault[15416]: 2018/03/05 19:10:12.552527 [ERROR] expiration: error restoring leases: error=failed to read lease entry: Unexpected response code: 500
Mar 05 19:10:12 mds7.sdn-vz.net vault[15416]: 2018/03/05 19:10:12.552601 [ERROR] expiration: shutting down
Mar 05 19:10:12 mds7.sdn-vz.net vault[15416]: 2018/03/05 19:10:12.552634 [WARN ] core: stopping active operation
Mar 05 19:10:13 mds7.sdn-vz.net vault[15416]: 2018/03/05 19:10:13.692021 [INFO ] core: pre-seal teardown starting
Mar 05 19:10:13 mds7.sdn-vz.net vault[15416]: 2018/03/05 19:10:13.692053 [INFO ] core: stopping cluster listeners
Mar 05 19:10:13 mds7.sdn-vz.net vault[15416]: 2018/03/05 19:10:13.692062 [INFO ] core: shutting down forwarding rpc listeners
Mar 05 19:10:13 mds7.sdn-vz.net vault[15416]: 2018/03/05 19:10:13.692117 [INFO ] core: forwarding rpc listeners stopped
Mar 05 19:10:14 mds7.sdn-vz.net vault[15416]: 2018/03/05 19:10:14.106982 [INFO ] core: rpc listeners successfully shut down
Mar 05 19:10:14 mds7.sdn-vz.net vault[15416]: 2018/03/05 19:10:14.107030 [INFO ] core: cluster listeners successfully shut down
Mar 05 19:10:14 mds7.sdn-vz.net vault[15416]: 2018/03/05 19:10:14.211707 [INFO ] rollback: stopping rollback manager

**Expected Behavior:**

**Actual Behavior:**

**Steps to Reproduce:**

**Important Factoids:**
Vault Server is run on 3 VMs with 1 Active, and 2 Standby. Consul is the backend, run as a 3 node cluster.
Vault is run as a systemctl service, with the following configuration:

**References:**

[logs.tar.gz](https://github.com/hashicorp/vault/files/1782443/logs.tar.gz)

**Comment by vamsi-vz** [comment]
Consul logs indicate some connectivity issue that is causing one of the nodes to be unreachable to the other 2 Consul instances, and the subsequent raft leader election is failing ? Can you please help debug further, and if this analysis is correct ?

[consul_logs.tar.gz](https://github.com/hashicorp/vault/files/1782797/consul_logs.tar.gz)

**Comment by jefferai** [comment]
@vamsi-vz You are correct that Consul instability would be a cause of this Vault issue, but you'll need to contact the Consul team for specific help...they're the experts!

**Comment by vamsi-vz** [comment]
@jefferai , there seems to be a flood of requests from Vault to Consul. Not sure if that is hogging up resources on Consul, causing it to become unstable.

In Consul Monitor logs on the Vault's leader node, there are a HUGE amount of these logs (**more than 300,000 in a minute**): 

2018/03/07 00:19:45 [DEBUG] http: Request GET /v1/kv/vault/sys/expire/id/auth/approle/login/34b7e39e3b5e3d0ff5d04a26c852c9649efc0d16 (3.514687ms) from=127.0.0.1:50444

2018/03/07 00:19:45 [DEBUG] http: Request GET /v1/kv/vault/sys/expire/id/auth/approle/login/34bb4e527a079066c48afe268d8b0fc6660facaf (1.424694ms) from=127.0.0.1:50368

2018/03/07 00:19:45 [DEBUG] http: Request GET /v1/kv/vault/sys/expire/id/auth/approle/login/34aac62e946d4538c2e6ec885150601541670c11 (3.503726ms) from=127.0.0.1:50418

2018/03/07 00:19:45 [DEBUG] http: Request GET /v1/kv/vault/sys/expire/id/auth/approle/login/34b31b117c2ec08293fc091a8d2a0a87b74f1e0c (3.510721ms) from=127.0.0.1:50420

2018/03/07 00:19:45 [DEBUG] http: Request GET /v1/kv/vault/sys/expire/id/auth/approle/login/34b6d3c54fecfe6df842a16b572a1677a3444ec7 (3.272824ms) from=127.0.0.1:50416

2018/03/07 00:19:45 [DEBUG] http: Request GET /v1/kv/vault/sys/expire/id/auth/approle/login/34b73ec7a5da30bc3bc1b4d4c3d4ffef5d054320 (3.627896ms) from=127.0.0.1:50356

2018/03/07 00:19:45 [DEBUG] http: Request GET /v1/kv/vault/sys/expire/id/auth/approle/login/34b735b33025cf15557761f14928918117adeba1 (3.62088ms) from=127.0.0.1:50336

2018/03/07 00:19:45 [DEBUG] http: Request GET /v1/kv/vault/sys/expire/id/auth/approle/login/34b43c55f04d4e5015fd8340ac5e8f7b7e8b4c8b (3.535553ms) from=127.0.0.1:50344

2018/03/07 00:19:45 [DEBUG] http: Request GET /v1/kv/vault/sys/expire/id/auth/approle/login/34bade4b419d039aeb2388f959e98ef6756ab012 (3.429746ms) from=127.0.0.1:50412

2018/03/07 00:19:45 [DEBUG] http: Request GET /v1/kv/vault/sys/expire/id/auth/approle/login/34bb0512ca88043f672fe77d122b3aa437ada845 (3.608483ms) from=127.0.0.1:50390

**Comment by jefferai** [comment]
If Vault is causing the instability then it looks like it's because you have a huge number of leases for tokens (things that have logged in via AppRole); when Vault starts it lazy loads these all in; every time it fails and a new node takes over it'll start again. You may want to look at modifying https://www.vaultproject.io/docs/configuration/storage/consul.html#max_parallel to a lower value to limit the request rate, if that's actually what's causing Consul errors.

I'd also suggest looking at why you have so many tokens. Generally AppRole tokens should be pretty closely tied to service lifetimes (e.g. by (ideally) using periodic tokens or keeping them short). If you have a lot sitting idle waiting to expire that aren't actually in use, they're just going to clog up storage more and more.

**Comment by vamsi-vz** [comment]
@jefferai , that explanation makes a lot of sense to my current setup. While there are few AppRole roles, the application requests for a fresh token each time, creating a new lease. 

This has create a very large number of leases that I can see using the /sys/leases list.

Can you please suggest a way for me to clear all the leases efficiently ? Vault goes down very quickly while I am running the following curl command:

curl -X PUT -H "X-Vault-Token:$VAULT_TOKEN" http://127.0.0.1:8200/v1/sys/leases/revoke-force/auth/approle/login

Are leases stored in data files that I can directly access and delete ? This is not a production environment.

**Comment by jefferai** [comment]
You can clear out leases from sys/expire, check the paths out and you should be able to see it pretty easily.

**Comment by vamsi-vz** [comment]
Can you please provide a link to the API/ command ? I see that the path is empty:

[nethiva@cos-mds6 ~]$ vault list /sys/expire
No value found at sys/expire/
