### ISSUE TITLE
HTTP 403 when enabling user/password auth

### ISSUE THREAD

**Issue by grobinson-blockchain** [hashicorp/vault#4082]
**Environment:**

* Vault Version: Vault v0.9.1 ('87b6919dea55da61d7cd444b2442cabb8ede8ab1')

**Vault Config File:**

    {
      "backend": {
        "consul": {
          "address": "127.0.0.1:8500",
          "path": "vault",
          "token": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        }
      },
      "listener": {
        "tcp": {
          "address": "0.0.0.0:8200",
          "tls_disable": 1
        }
      },
      "telemetry": {
        "disable_hostname": true,
        "statsd_address": "127.0.0.1:8125"
      }
    }

**Expected Behavior:**
    $ vault auth enable userpass

**Actual Behavior:**

    vault auth enable userpass
    Error validating token: Error making API request.

    URL: GET http://127.0.0.1:8200/v1/auth/token/lookup-self
    Code: 403. Errors:

    * permission denied

using a root token:

    Key                 Value
    ---                 -----
    accessor            xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    creation_time       xxxxxxxxxx
    creation_ttl        0
    display_name        root
    entity_id
    expire_time         <nil>
    explicit_max_ttl    0
    id                  xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    meta                <nil>
    num_uses            0
    orphan              true
    path                auth/token/root
    policies            [root]
    ttl                 0

and using cURL:

     curl -H "X-Vault-Token: $(echo cat .vault-token)" http://127.0.0.1:8200/v1/auth/token/lookup-self

where `.vault_token` is the root token above.

**Steps to Reproduce:**
I think this is reproducible when generating a new root token as per https://www.vaultproject.io/guides/operations/generate-root.html.

**Important Factoids:**

**References:**

**Comment by calvn** [comment]
Vault v0.9.1 uses `auth-enable` as the subcommand: https://github.com/hashicorp/vault/blob/v0.9.1/website/source/docs/auth/userpass.html.md

**Comment by grobinson-blockchain** [comment]
Thanks! We upgraded to 0.9.5 👍
