### ISSUE TITLE
Write command requires 2 parameters but documentation says only 1 is

### ISSUE THREAD

**Issue by BRMatt** [hashicorp/vault#409]
The documentation states that you can generate a transit key using the following command:

```
$ vault write transit/keys/foo test=1
Success! Data written to: transit/keys/foo
```

I assumed the `test=1` snippet was there because it was important to the specific example the documentation was giving. When I was playing around with vault I tried running the command without it and the command errored out:

```
$ vault write "transit/keys/foo"
write expects at least two arguments
Usage: vault write [options] path [data]

  Write data (secrets or configuration) into Vault.

....
```

What's especially confusing is that the usage for the command implies that `[data]` is optional. Is the value supposed to be optional, or is the documentation wrong?

I'm running `Vault v0.2.0-dev (8968c4cfbdd6d7d2d398b60d0dad40249c93c93d+CHANGES)`

**Comment by armon** [comment]
@BRMatt With the latest version you can use the "-f" flag to write to make it ignore that there are no data fields. By default it complains if you do a no value write.

**Comment by BRMatt** [comment]
Great, I was going to submit a docs PR but it seems this is also already documented in the master branch. :)
