### ISSUE TITLE
vault not installing command completions for fish

### ISSUE THREAD

**Issue by walterdolce** [hashicorp/vault#4094]
**Environment:**
```Vault v0.9.5 ('36edb4d42380d89a897e7f633046423240b710d9')```

* Vault Version: please see above.
* Operating System/Architecture: macOS High Sierra 10.13.3

**Vault Config File:**
N/A

**Startup Log Output:**
N/A

**Expected Behavior:**
Vault to do what the documentation says [here](https://www.vaultproject.io/intro/getting-started/install.html):
> This will automatically install the helpers in your ~/.bashrc or ~/.zshrc, or to ~/.config/fish/completions/vault.fish for Fish users. Then restart your terminal or reload your shell: sh $ exec $SHELL

**Actual Behavior:**
```
vault -autocomplete-install                                                                                                                                                                                                      131ms
Error executing CLI: 1 error occurred:

* open {{path_to_my_home_folder}}/.config/fish/completions/vault.fish: no such file or directory
```
Note: `{{path_to_my_home_folder}}` has been placed instead of the actual system user's home path.

**Steps to Reproduce:**
- Install `vault` with Homebrew (`brew install vault`)
- Ensure `vault` works as advised on the documentation (Just issue `vault` on the CLI)
- Issue `vault -autocomplete-install`

**Important Factoids:**
Not sure whether it's an important factoid, but my Fish shell version is `fish, version 2.7.1`

**References:**

**Comment by walterdolce** [comment]
Looks like the issue is in here -
 https://github.com/hashicorp/vault/blob/master/vendor/github.com/posener/complete/cmd/install/utils.go#L40

If any of the directories leading to the file do not exist, the command will fail as the relevant code does not act as an equivalent of `mkdir -p`. I guess then https://golang.org/pkg/os/#MkdirAll should be used before `os.Create`.

**Comment by jefferai** [comment]
Please file a bug against posener/complete instead -- what you're seeing is just a vendored copy of that project. Once it's fixed it'll get pulled in the next time we update deps!

**Comment by walterdolce** [comment]
Indeed @jefferai. Done. Thanks!

**Comment by posener** [comment]
Fixed in complete, you can update the vendored complete to v1.1.1
