### ISSUE TITLE
Minor security issue: Vault auth outputs token on CLI

### ISSUE THREAD

**Issue by sgleske-ias** [hashicorp/vault#4099]
**Bug**:

`vault auth` hides user input for the token... and then echoes the token for all to see.

```
$ export VAULT_ADDR='https://vault.example.com/'

$ vault auth
Token (will be hidden):
Successfully authenticated! You are now logged in.
token: REDACTED-I_SHOULD_NOT_BE_HERE
token_duration: 2564835
token_policies: [default]
```

**Environment:**

* Vault Version: Vault v0.8.3 ('6b29fb2b7f70ed538ee2b3c057335d706b6d4e36')
* Operating System/Architecture: Mac OS X

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

```
$ vault auth
Token (will be hidden):
Successfully authenticated! You are now logged in.
token_duration: 2564835
token_policies: [default]
```

**Actual Behavior:**

**Steps to Reproduce:**

**Important Factoids:**

**References:**

**Comment by jefferai** [comment]
This is normal and expected behavior for that command. `vault auth` is used to authenticate, and the output of that is a token. If you're authenticating with a token, the output of that is...still a token. Usage of `vault auth` is not required; especially when you already have a token it's sufficient to simply e.g. set `VAULT_TOKEN` to it.

**Comment by sgleske-ias** [comment]
Why bother hiding user input if you're going to output it @jefferai ?  I would expect it not to output to the user at all and tell them the token can be viewed in `~/.vault-token`.  This is a poor security choice.  Please reopen.

**Comment by jefferai** [comment]
The output is common code across auth methods where the point is to get back a token. The input comes from different CLI helpers; the one for token can either accept a token on the command line or have it input at the prompt.

The output does not necessarily have to be displayed back in the shell, but can be sent anywhere you like via normal shell means, in conjunction with `-format` and `-token-only` and so on. There are plenty of use cases where you can submit it via hidden input and not have the output shown back to you.

**Comment by sgleske-ias** [comment]
I guess I'll stick to setting the environment variable from now on.
