### ISSUE TITLE
HTTP 403 for PUT to auth/token/roles

### ISSUE THREAD

**Issue by grobinson-blockchain** [hashicorp/vault#4101]
**Environment:**

* Vault Version: 0.9.5

**Expected Behavior:**

Suppose I have a token whose policies have the following permissions:

    path "auth/token/roles/*" {
        capabilities = ["read","update","delete","list","sudo"]
    }

should I be able to do:

      vault write auth/token/roles/foo allowed_policies=bar

or do I need a root token? I can't find a reference to this in the docs.

**Actual Behavior:**

    vault write auth/token/roles/bar ttl=5m
    Error writing data to auth/token/roles/bar: Error making API request.

    URL: PUT http://127.0.0.1:8200/v1/auth/token/roles/bar
    Code: 403. Errors:

    * permission denied

**Comment by grobinson-blockchain** [comment]
Note, with the above capabilities it is possible to delete an existing token role (created with a root token):

    vault delete auth/token/roles/bar
    Success! Data deleted (if it existed) at: auth/token/roles/bar

**Comment by jefferai** [comment]
You're missing `"write"` in your capabilities list. That endpoint honors a write/update distinction, so if it's not already created you can't with just `update`.

**Comment by grobinson-blockchain** [comment]
wait @jefferai before we close the issue, `write` isn't in the documentation:

https://www.vaultproject.io/docs/concepts/policies.html#capabilities

Would you like me to start a PR to add this?

**Comment by grobinson-blockchain** [comment]
also, I got this error:

    Error uploading policy: Error making API request.

    URL: PUT http://127.0.0.1:8200/v1/sys/policy/foo
    Code: 400. Errors:

    * Failed to parse policy: path "auth/token/roles/*": invalid capability 'write'
