### ISSUE TITLE
When vault restarts, it sometimes forgets that it's been init'ed

### ISSUE THREAD

**Issue by swsnider** [hashicorp/vault#411]
My vault server restarted in the pursuit of #410. At least one of the times, I got this (vault init was run, and I use a 3-node zookeeper cluster as the storage backend). I'm running v0.2.0.rc1:

```
==> Vault server configuration:

         Log Level: info
             Mlock: supported: true, enabled: true
           Backend: zookeeper (HA available)
 Advertise Address: http://HOSTNAME:8200
        Listener 1: tcp (addr: "0.0.0.0:8200", tls: "enabled")

==> Vault server started! Log data will stream in below:

2015/07/10 04:04:36 [INFO] core: seal configuration missing, not initialized
```

**Comment by swsnider** [comment]
I now see this at least 50% of the time after #410 causes a restart.

**Comment by armon** [comment]
@swsnider This is a really terrible bug. I have never seen this on the other backends, can you reproduce this with the Consul backend or file backend? Or can you check the data in ZK? Would you be able to list the keys in `core/` in ZK?

**Comment by armon** [comment]
Do you also have multiple ZK instances configured? Are they replicating properly?

**Comment by swsnider** [comment]
I have three ZK instances configured. They are replicating properly (and zookeeper can't replicate such that it's in an inconsistent state). The list of keys in core/ is:

```
(CONNECTED) /> ls cpvault/core
audit
auth
keyring
leader
lock
master
mounts
seal-config
```

I can't try with consul -- I don't have approval to use that technology. I could try with the file backend, but this failure is pretty time-consuming to exercise (have to restart the service, unseal it, log in with ldap, see if it failed this time...), so it might be a while before I can get around to it.

**Comment by sethvargo** [comment]
Hi @swsnider 

I believe this was fixed as part of https://github.com/hashicorp/vault/commit/fce7c43b9851e23cb0d6466413565018d873856e. Can you please take a look?

**Comment by swsnider** [comment]
I no longer see this bug in my setup. Thanks!
