### ISSUE TITLE
Dev server shouldn't print information about clustering, because there isn't any clustering

### ISSUE THREAD

**Issue by bonifaido** [hashicorp/vault#4120]
**Feature Request:**
Dev server shouldn't print information about clustering, because there isn't any clustering.

**Environment:**
Vault v0.9.5 ('36edb4d42380d89a897e7f633046423240b710d9')

* Vault Version:
* Operating System/Architecture:
OSX 10.13.3

**Vault Config File:**
`vault server -dev`

**Startup Log Output:**
```
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: false, enabled: false
        Redirect Address: http://127.0.0.1:8200
                 Storage: inmem
                 Version: Vault v0.9.5
             Version Sha: 36edb4d42380d89a897e7f633046423240b710d9
```
**Expected Behavior:**
A single node dev server should start up, without clustering.

**Actual Behavior:**
Cluster Address is printed, however this is a single node dev server, and actually nothing is listening on that address.

**Steps to Reproduce:**
`vault server -dev`

**Comment by jefferai** [comment]
Whether or not you use it there is still a configured cluster address. Printing it can be useful in troubleshooting situations when you want to know what the auto detected address is.
