### ISSUE TITLE
Consul backend - service_address issues

### ISSUE THREAD

**Issue by FlorinAsavoaie** [hashicorp/vault#4137]
**Environment:**

* Vault Version: 0.9.5
* Operating System/Architecture: Ubuntu 16.04

**Vault Config File:**
```
storage "consul" {
  address = "unix:///alloc/consul.sock"
  path    = "vault"
  service_address = "vault"
}
```

**Expected Behavior:**

I think that vault should resolve the service_address to an IP and return that, if a name is being used. That's the point of Consul DNS service.

**Actual Behavior:**

The string config is sent as-is and not resolved.

**Important Factoids:**

I am running Vault in a container orchestrated by Nomad. It ends up actually advertising (and thus redirecting to) the IP of the host where the Consul agent is running. I'd expect to be able to advertise the IP address of the container. However, when the Vault configuration is generated, there's no way to know the IP address as it is generated before the container starts. As such, I expect that putting the hostname of the container as service_address would do the trick (using this for multiple other services and works like a charm).

If this is confirmed to be the expected the expect behavior, I can make a PR.

**Comment by jefferai** [comment]
I'm not really following the issue -- sounds like maybe a Nomad bug? -- but I don't think Vault should be changing the service address that you configure. If in your situation you need to resolve that prior to starting Vault, I suggest making your configuration file a template and doing the resolution first.

**Comment by FlorinAsavoaie** [comment]
I think you don't understand your problem. Consul expects service_address to be an IP so it can create A records for it. If I put a hostname on the listen fields, you make the listen calls to the OS with the hostname or you resolve them first? What's the difference here?

**Comment by FlorinAsavoaie** [comment]
Ok, I will make a PR for this and we'll see how it goes, I guess.

**Comment by jefferai** [comment]
If Consul expects a service address to be an IP, shouldn't it be responsible for resolving to an IP, not Vault? Either way you slice it I don't see this as being Vault's responsibility -- either Consul should do the resolution as an act of input sanitizing, or the user should submit a proper IP to Vault. I don't see why it's not Vault's responsibility here to pass through the data as given.

**Comment by FlorinAsavoaie** [comment]
Consul does service discovery. By definition, service discovery means to tell others where stuff is, and generate records for it. Consul PROVIDES the DNS. If you don't give Consul an IP, how can it know where your service is located?

**Comment by jefferai** [comment]
If Vault resolves it, it either uses Consul -- which already knows the IP in that case -- or it's using a non-Consul resolver, in which case Consul can use that same non-Consul resolver (recurse).

**Comment by FlorinAsavoaie** [comment]
Or it uses the hosts file... To which consul might not have access if it is not on the same host.

**Comment by jefferai** [comment]
In which case it's trivial to resolve the value before passing it to Vault.

**Comment by FlorinAsavoaie** [comment]
So if I put a hostname as listen address for a Vault endpoint, it will be send to the bind() syscall as-is, not resolved, right?

**Comment by FlorinAsavoaie** [comment]
Look, this is a best practice. When you have machines or containers with dynamic IP addresses, you use their hostname in configuration files to avoid needing to "look it up" all the time. You can do this in Apache HTTPD, Nginx, Stunnel, Tomcat, JBoss, you name it. It's just how things work. If you don't like to follow best practices just close this and reject the PR, you're the owner after all, what do I know.

**Comment by jefferai** [comment]
Nginx uses hostname for listeners to tell it _what to respond to_ in a default scenario; you can also use bare ports or IPs and have separate stanzas to configure this. Stunnel does not use hostnames for listeners, only ports and/or IP addresses. I won't go on.

Having Vault resolve the address means Vault has to be responsible for what to do when that resolution returns multiple IPs, or needs to be SRV instead of A, or can be IPv4 vs IPv6, and so on. It's not just a simple DNS query, it introduces ambiguity, and this is not something that we like with a security product. Conversely, it's super easy to just tell Vault what you want -- even in a container -- by using a templated configuration file or a simple `sed` command. I'd rather you are declarative than Vault has to make guesses at what the right behavior is.
