### ISSUE TITLE
Vendoring issue since update to helper/keysutil

### ISSUE THREAD

**Issue by usererror** [hashicorp/vault#4142]
I added a package (`github.com/hashicorp/vault-plugin-auth-gcp/plugin`) to my project which requires `github.com/hashicorp/vault` on the master branch. After updating my Gopkg.toml and running `dep ensure` I can no longer successfully build my Go application. 

I tried to list as many details below as possible. Please let me know if there is anything else that would be helpful or if there is something I am missing.

**Expected Behavior:**
I expected that after running `dep ensure` I would be able to build with the new package added.

**Actual Behavior:**
```
$ go install
vendor/github.com/golang/go/src/math/big/arith_amd64.go:9:8: use of internal package not allowed
```

**Steps to Reproduce:**
It seems like having `github.com/hashicorp/vault` as a dependency pointing at `master` will reproduce the issue.

**Important Factoids:**
I tracked down the code that is importing `github.com/golang/go/math/big`. I think that somewhere along the way `goimports` may have picked up the wrong import and is using said package instead of regular `math/big`.

**References:**
The file containing the import causing the issue (this was updated in the past week): https://github.com/hashicorp/vault/blob/master/helper/keysutil/encrypted_key_storage.go

The `math/big` package: https://golang.org/pkg/math/big/

**Comment by jefferai** [comment]
Using that package was very much on purpose; we've seen this internally and are trying to track down why Vault builds just fine with that imported vendored package but other things importing Vault libs do not.

**Comment by usererror** [comment]
Good deal, thanks for the quick response Jeff!

For anyone else who comes across this and is curious, upon further digging it looks like `github.com/golang/go/math/big` has built in support for x86 [ADX](https://en.wikipedia.org/wiki/Intel_ADX) and [BMI2](https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets) while regular `math/big` seems not to. I assume these make crypto operations much faster if they're available to the processor which is why we'd want to use them.

**Comment by jefferai** [comment]
Actually that has nothing to do with this :-) The reason we wanted the Go 1.10 package has to do with its ability to format values in base62. Anyways, you should be all set now.

**Comment by usererror** [comment]
Ahh okay :) I learned three cool things for the price of one vendor bug I'll call it a win! 

Everything is looking good on my end again thanks for the help! Going to close this out.
