### ISSUE TITLE
Writing first secret as shown on the documentation doesn't actually work

### ISSUE THREAD

**Issue by walterdolce** [hashicorp/vault#4145]
By following the steps as shown in the Getting Started guide leads to nothing but an error when trying to write the first secret.

The error is the following:
```
$ vault write secret/hello value=world
Error writing data to secret/hello: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/secret/hello
Code: 400. Errors:

* missing client token
```

To reproduce just follow the documentation from the beginning to when a first secret has to be written.

Vault version:
```
Vault v0.9.5 ('36edb4d42380d89a897e7f633046423240b710d9')
```

System is macOS High Sierra, 10.13.3. Vault installed via Homebrew.

**Comment by walterdolce** [comment]
Looks like the following command is required to unblock the situation:
```
vault auth {{root_token}}
```

But gives a deprecation warning:
```
vault auth (cat root_token)                                                                                  2788ms
WARNING! The "vault auth ARG" command is deprecated and is now a subcommand
for interacting with auth methods. To authenticate locally to Vault, use
"vault login" instead. This backwards compatability will be removed in Vault
0.11 (or later).

Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

...
```

I'll try to update the documentation with the latest information.

**Comment by jefferai** [comment]
How did you start Vault? Doing `vault server -dev` works just fine for me.

**Comment by walterdolce** [comment]
@jefferai I started Vault as stated in the documentation: `vault server -dev`

**Comment by walterdolce** [comment]
Errr @jefferai .. NVM.. this is a manifestation of PEBKAC... everything is fine. Therefore closing this.

![](https://media.giphy.com/media/4pMX5rJ4PYAEM/giphy.gif)
