### ISSUE TITLE
Documentation / Website: easily view documentation for different versions on website

### ISSUE THREAD

**Issue by c3st7n** [hashicorp/vault#4153]
Apologies if this has already been request, I did do a search to check if it had and didn't find anything. I can see it has been requested on Terraform and is a common issue for Hashicorp projects as a whole.

**Feature Request:**
It would be very useful to be able to select a different Vault version on the docs part of the website. At the moment, if I want to look at the docs I have to manually scour the git repo at a specific tag to find the information.

A good example of this functionality is [Django](https://docs.djangoproject.com/en/2.0/).

**Comment by jefferai** [comment]
We definitely want to do but haven't been able to get going. We know it's a pain point and hope to fix this some day. I'm going to close this but only for keeping-open-issue-count-sane reasons, it's definitely on our minds!
