### ISSUE TITLE
Setting up MSSQL as secrets engine impossible - dial tcp 127.0.0.1:1433: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by ed-zalando** [hashicorp/vault#4167]
**Environment:**
Vault v0.9.3

* Vault Version: Vault v0.9.3
* Operating System/Architecture: Windows Server 2016 Standard

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

**Actual Behavior:**
We are trying to setup MSSQL as a secrets engine. MSSQL is installed on another host lets say "myServer". The needed network ports are open and I can connect on the default MSSQL port 1433 from the vault server to this MSSQL server.

1. We enabled the database backend in Vault by "vault secrets enable database". 
2. We are trying to configure Vault with the plugin and connection information by following the documentation:
vault write database/config/myName plugin_name=mssql-database-plugin connection_url='myServer.myDomain://myUser:MyPassword@myServer:1433' allowed_roles="myRole"

No madder what I provide for the server name "myServer" or which user I choose, Vault seems to try to connect to localhost [127.0.0.1] and I get the error:

Error writing data to database/config/myName: Error making API request.

URL: PUT http://127.0.0.1:8115/v1/database/config/MyName
Code: 400. Errors:

* error creating database object: error verifying connection: Unable to open tcp connection with host 'localhost:1433': dial tcp 127.0.0.1:1433: connectex: No connection could be made because the target machine actively refused it.

**Steps to Reproduce:**
see above

**Important Factoids:**

**References:**

**Comment by chrishoffman** [comment]
Can you try and provide the connection_url in the following format:

```
sqlserver://myUser:MyPassword@myServer:1433
```

The library we are using for connections has various formats that it supports but the one above is the recommended one.  It looks like you may not be putting the URL scheme at the beginning which may be triggering it to use the wrong format.

**Comment by chrishoffman** [comment]
Just checking in to see if this resolved your issue.

**Comment by ed-zalando** [comment]
Sorry, for the late response (I was sick) and thank you for your quick answer! The pattern "sqlserver" in front confused us. We thought the MSSQL server host name had to be provided there, but with your URL it worked. Thank you!

**Comment by stevenvandorpe** [comment]
Hi

I run into the same error on Windows 10.

```
C:\Users\steven\Downloads\vault_1.4.0_windows_amd64>vault write -address http://127.0.0.1:8200/ database/config/database^
More?     plugin_name=mssql-database-plugin ^
More?     connection_url='sqlserver://{{username}}:{{password}}@xx.xxx.xx.xxx:1433' ^
More?     allowed_roles="my-role" ^
More?     username="DOCKER" ^
More?     password="my-pass"
```

_Error writing data to database/config/database: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/database
Code: 400. Errors:

* error creating database object: error verifying connection: Unable to open tcp connection with host 'localhost:1433': dial tcp [::1]:1433: connectex: No connection could be made because the target machine actively refused it._

**Version info:**
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.4.0
Cluster Name    vault-cluster-b1c9de07
Cluster ID      0c7946da-5d80-ab3d-2d31-f7148fee5057
HA Enabled      false
```

**Comment by DanielBoulerice** [comment]
I have the same problem.

1. installed SQL Server Express 2019 on my local computer (Windows 10) to test Vault dynamic accounts.
2. I installed Vault 19.0 on the same computer.
3. I run the following BAT file to enable the SQL Engine on Vault.  (I tested that SQL Authetication is enabled, and that sa/yourStrong log me in correctly the database using SSDS.)

```
vault secrets enable database
Set UID=sa
Set PWD=yourStrong
vault write database/config/my-mssql-database "plugin_name=mssql-database-plugin" "connection_url='sqlserver://{{username}}:{{password}}@localhost:1433'" "allowed_roles=my-role" "username=%UID%" "password=%PWD%"
Set UID=
Set PWD=
```
And I get the same error:
```
Error writing data to database/config/my-mssql-database: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/my-mssql-database
Code: 400. Errors:

 * error creating database object: error verifying connection: unable to open tcp connection with host 'localhost:1433': dial tcp 127.0.0.1:1433: connectex: No connection could be made because the target machine actively refused it.
```
I also tested parameter separation in Windows, because CMD splits on the equal sign (=) meaning that without the double quotes, password=%PWD% would yield two parameters.

Any ideas?

**Comment by hsimon-hashicorp** [comment]
Are you able to telnet to localhost:1433? "Connection refused" to my mind means the port may not be open, or if there's a local firewall rule set to disallow traffic on port 1433, that might also be an issue.

**Comment by DanielBoulerice** [comment]
No, you're right!  I can't connect to 1433 using TelNet.  I'll investigate that.  Thanks.
