### ISSUE TITLE
Add support for key rotation in the transit backend

### ISSUE THREAD

**Issue by lcabancla** [hashicorp/vault#417]
Allow encryption keys in the transit backend to be rotated. A new endpoint like 'transit/rotate/{my-key}' can be created to replace the existing encryption key but still allow data encrypted by old keys to be decrypted to minimize impact on clients.

**Comment by rupskygill** [comment]
+1. This will be a very useful feature. I am considering using Vault transit for KEK management which i would like to rotate periodically.

**Comment by armon** [comment]
@rupskygill Just a FYI we are planning on adding a backend specifically for KEK support. It would be great to share your use cases with me and @jefferai and @vishalnayak

**Comment by rupskygill** [comment]
Hi @armon @jefferai and @vishalnayak essentially my use-case is encryption-decryption service which holds a number of named symmetric keys used for application data and private key protection. Clients of the service send a data blob and key_name to the service to get encryption/decryption performed.  

The service should manage entire lifecycle of these keys  - creation,  deletion, revocation and rotation etc. Key rotation is supported such that each key_name represents a key chain of current and rotated keys - where only current key is used for encrypting but data encrypted with old keys can be decrypted.

**Comment by Srinivas11789** [comment]
Is the issue still open to contribution? I would like to give it a try

**Comment by jefferai** [comment]
Wow, this issue is still open! It's been in Vault for about two years now. Closing!
