### ISSUE TITLE
Include severity field in JSON output of audit log 

### ISSUE THREAD

**Issue by kenrestivo-stem** [hashicorp/vault#4174]
**Feature Request:**
Please include severity field in JSON output  of audit log.

**Environment:**
Linux ubuntu 16.04 AWS

* Vault Version:

0.9.1
* Operating System/Architecture:
Linux Ubuntu 16.04

**Vault Config File:**
Not applicable.

**Startup Log Output:**
Not applicable

**Expected Behavior:**
Logs passed via JSON to Elasticsearch have a "level" or "severity" key which has fields like "info", "debug", "warning", "error"

**Actual Behavior:**
Logs show up with three top-level keys:  auth, error, and request. When these are forwarded to Elasticsearch, there's no easy way to search by log severity.

**Steps to Reproduce:**
Set up audit log with JSON format. Look at the logs.

**Important Factoids:**
 Audit log is
```
stdout/  file               replicated            file_path=stdout
```
But same behavior observed with socket backend

**References:**

**Comment by jefferai** [comment]
Audit logs do not have severity. (Or, conversely, they all have the same severity). They are simply an audit trail, no entry is higher or lower than the other.
