### ISSUE TITLE
Dynamic policy mapping

### ISSUE THREAD

**Issue by riuvshin** [hashicorp/vault#4189]
hello! can someone please point me to the docs or examples how can I create dynamic policy with LDAP, my goal is to provide each LDAP user personal space in `secret/{ldap_user}/*` 
each new user in LDAP should automatically have its own policy after first login for example

Because when I apply some policy to whole LDAP group each user may read the secrets of another user.

**Comment by jefferai** [comment]
Sorry, but Vault does not currently support this.
