### ISSUE TITLE
Approle doesn't obey token_max_ttl 

### ISSUE THREAD

**Issue by mikebell90** [hashicorp/vault#4196]
**Environment:**

* Vault Version: 0.9.6
* Operating System/Architecture:
Mac high sierra, vault dev server

**Vault Config File:**
None - used dev

**Expected Behavior:**
I created an approle with an token_max_ttl of 35s. It's a periodic token period=30s.
I expected I could renew within the 35s , but after that I would hard stop,
since docs say even periodic tokens are subject to max ttl

**Actual Behavior:**
Token continued to be renewable and expiration time continued to advance

**Steps to Reproduce:**
(in another tab ./vault server --dev --dev-root-token-id root)
(now open another tab, login in as root and ....)

# mount the approle
./vault auth enable approle
Success! Enabled approle auth method at: approle/

# set up role named 'myrole' that issues periodic tokens, and a max_ttl
./vault write auth/approle/role/myrole period=30s token_max_ttl=35s

# verify settings were accepted
 ./vault read auth/approle/role/myrole 
Key                   Value
---                   -----
bind_secret_id        true
bound_cidr_list       []
period                30
policies              [default]
secret_id_num_uses    0
secret_id_ttl         0
token_max_ttl         35
token_num_uses        0
token_ttl             0

# generate role-id
 ./vault read auth/approle/role/myrole/role-id
Key        Value
---        -----
role_id    1a61b63b-2dc3-9f46-06b4-09888e9765a9

# generate secret-id
 ./vault write -force auth/approle/role/myrole/secret-id
Key                   Value
---                   -----
secret_id             94cec21b-46d3-15d1-1e1c-6e31c8a5b2d6
secret_id_accessor    f5896fe8-9e4f-6319-b983-efdf30b65a6e

# generate token
 ./vault write auth/approle/login role_id=1a61b63b-2dc3-9f46-06b4-09888e9765a9  secret_id=94cec21b-46d3-15d1-1e1c-6e31c8a5b2d6
Key                     Value
---                     -----
token                   c948b1db-e3df-6a56-6940-337f1856ee8d
token_accessor          c64ab905-2d0e-52fd-1ffa-53a531c1b60f
token_duration          30s
token_renewable         true
token_policies          [default]
token_meta_role_name    myrole

# renew once
 ./vault token renew c948b1db-e3df-6a56-6940-337f1856ee8d
Key                     Value
---                     -----
token                   c948b1db-e3df-6a56-6940-337f1856ee8d
token_accessor          c64ab905-2d0e-52fd-1ffa-53a531c1b60f
token_duration          30s
token_renewable         true
token_policies          [default]
token_meta_role_name    myrole

# repeat cycle of sleep 15, renew token for about 2 minutes
# now do a lookup
./vault token lookup c948b1db-e3df-6a56-6940-337f1856ee8d
Key                  Value
---                  -----
accessor             c64ab905-2d0e-52fd-1ffa-53a531c1b60f
creation_time        1522032629
creation_ttl         30
display_name         approle
entity_id            1a0e4974-68c5-6994-711e-cb70a627889d
*expire_time          2018-03-25T19:53:01.860955-07:00*
*explicit_max_ttl     0*
id                   c948b1db-e3df-6a56-6940-337f1856ee8d
*issue_time           2018-03-25T19:50:29.488731-07:00*
*last_renewal         2018-03-25T19:52:31.860956-07:00*
last_renewal_time    1522032751
meta                 map[role_name:myrole]
num_uses             0
orphan               true
path                 auth/approle/login
policies             [default]
renewable            true
ttl                  25

Note: Logging in explicitly as token and using self-renew and self-lookup produced same results

**Comment by mikebell90** [comment]
docs
--
(approle api)
token_max_ttl (string: "") - Duration in either an integer number of seconds (3600) or an integer time unit (60m) after which the issued token can no longer be renewed.

(general token concepts)
 There are a few important things to know when using periodic tokens:
A token with both a period and an explicit max TTL will act like a periodic token *but will be revoked when the explicit max TTL is reached*

**Comment by mikebell90** [comment]
With "regular tokens"
./vault token create -explicit-max-ttl=35s -period=30s

things act "as expected".

**Comment by jefferai** [comment]
`token_max_ttl` is not an explicit max ttl, it simply controls the normal max ttl behavior for renewals and is akin to something like `ttl` and `max_ttl` in most other auth types. See https://www.vaultproject.io/docs/concepts/tokens.html#token-time-to-live-periodic-tokens-and-explicit-max-ttls

AppRole does not currently support explicit max ttls.

**Comment by mikebell90** [comment]
I cited the docs myself. So you didn’t didn’t to link to the same text. Either the docs are wrong or the code is. Choose

@jefferai

**Comment by jefferai** [comment]
Nothing you cited is incorrect with respect to the behavior you're seeing. I don't see any discrepancy.

**Comment by mikebell90** [comment]
1. The docs (applrole( say you can’t renew beyond this.
2. The docs (token concepts) day the concept of max ttl applies to both periodic and non periodic tokens l.
3. The behavior using auth token create works according to expectation and applied token create does not @jefferai

**Comment by jefferai** [comment]
> The docs (token concepts) day the concept of max ttl applies to both periodic and non periodic tokens.

The docs say that periodic tokens are *not* bound by max ttl, which is used for normal renewal behavior.  Not being bound by them is the primary reason to use periodic tokens in the first place. They are bound by explicit max ttl, which is not currently supported by AppRole.

**Comment by mikebell90** [comment]
I agree the docs say an implicit max ttl doesn’t apply. They say an explicit max ttl does and what is more explicit in this case than token max ttl ? I think what you are saying is token max ttl for approle applies only to non periodic tokens unlike max ttl applies when creating a token directly ? That is inconsistent with the docs and the docs need to be corrected. 

Again we are getting caught up in terminology: is token max ttl supposed to be an implicit nax ttl and how is that clear from the doxst

**Comment by jefferai** [comment]
"explicit max ttl" is a term of art in Vault world, as described on that concepts page. If something isn't labeled as such, it follows normal behavior.
