### ISSUE TITLE
openldap groups not found....

### ISSUE THREAD

**Issue by flynn1973** [hashicorp/vault#4197]
root@aixmgmtlx:/root>vault read auth/ldap/config
WARNING! The following warnings were returned from Vault:

  * Read access to this endpoint should be controlled via ACLs as it will
  return the configuration information as-is, including any passwords.

Key                Value
---                -----
binddn             cn=roots,dc=sozialversicherung,dc=at
bindpass           ******
certificate        -----BEGIN CERTIFICATE-----
***
-----END CERTIFICATE-----
deny_null_bind     true
discoverdn         false
groupattr          cn
groupdn            ou=groups,ou=aix,ou=apps,dc=sozialversicherung,dc=at
groupfilter        (|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}}))
insecure_tls       true
starttls           false
tls_max_version    tls10
tls_min_version    tls10
upndomain          n/a
url                ldaps://ldap.sozvers.at:636
userattr           uid
userdn             ou=users,ou=aix,ou=apps,dc=sozialversicherung,dc=at

root@aixmgmtlx:/root>vault login -method=ldap username=tremch
Password (will be hidden):
Error authenticating: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/ldap/login/tremch
Code: 400. Errors:

* user is not a member of any authorized group; additionally, no LDAP groups found in groupDN 'ou=groups,ou=aix,ou=apps,dc=sozialversicherung,dc=at'; only policies from locally-defined groups available

ldapsearch  -h ldaps://ldap.sozvers.at -p 636 -x -W -D 'cn=roots,dc=sozialversicherung,dc=at' -b 'ou=groups,ou=aix,ou=apps,dc=sozialversicherung,dc=at' cn memberUid

# smadmin, groups, aix, apps, sozialversicherung.at
dn: cn=smadmin,ou=groups,ou=aix,ou=apps,dc=sozialversicherung,dc=at
cn: smadmin
memberUid: uid=tremch,ou=users,ou=aix,ou=apps,dc=sozialversicherung,dc=at

**Comment by jefferai** [comment]
Looks like you are using different bind DNs between the ldapsearch command and Vault.

**Comment by flynn1973** [comment]
works...

root@lpgaixmgmtlx01:/root>vault login -method=ldap username=tremch
Password (will be hidden):
Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

Key                    Value
---                    -----
token                  595468d5-2da7-70e8-b2c8-e4e88256c155
token_accessor         19fb192d-ddeb-6716-7f24-780384b3ad1a
token_duration         768h
token_renewable        true
token_policies         [default systems]
token_meta_username    tremch

**Comment by jefferai** [comment]
Great!
