### ISSUE TITLE
vault API return !(NOVERB)

### ISSUE THREAD

**Issue by shsjshentao** [hashicorp/vault#4204]
[root@**** bin]# vault read -tls-skip-verify -field=value ******
TEST%
[root@**** bin]# echo `vault read -tls-skip-verify -field=value ******`
TEST%!(NOVERB)
[root@**** bin]# vault read -tls-skip-verify -format=json ******  | jq -r .data.value
TEST%
[root@**** bin]# echo `vault read -tls-skip-verify -format=json ******   | jq -r .data.value`
TEST%

only use "-field" and then use shell will cause this problem

**Comment by jefferai** [comment]
Please provide more context here. I don't understand what you're trying to show. Understanding the data that was stored and being read would help.

**Comment by joelthompson** [comment]
What version of Vault are you using? This looks to be a duplicate of #4005 which was fixed in, I believe, 0.9.4.

**Comment by shsjshentao** [comment]
v0.9.3
