### ISSUE TITLE
Vault 0.9.6 version not updated in vault_0.9.6_linux_amd64.zip 

### ISSUE THREAD

**Issue by moisesguimaraes** [hashicorp/vault#4205]
**Environment:**

* Vault Version: 0.9.6?
* Operating System/Architecture: Linux 64-bit

**Vault Config File:**

**Startup Log Output:**

**Expected Behavior:**

$ vault -v
Vault v0.9.6 ('...')

**Actual Behavior:**

$ vault -v
Vault v0.9.5 ('36edb4d42380d89a897e7f633046423240b710d9')

**Steps to Reproduce:**

- Download https://releases.hashicorp.com/vault/0.9.6/vault_0.9.6_linux_amd64.zip
- Unzip
- Run vault -v

**Important Factoids:**

**References:**

**Comment by jefferai** [comment]
Cannot reproduce:

```
$ unzip vault_0.9.6_linux_amd64.zip 
Archive:  vault_0.9.6_linux_amd64.zip
replace vault? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: vault                   

$ ./vault -v
Vault v0.9.6 ('7e1fbde40afee241f81ef08700e7987d86fc7242')
```
My guess is that you have some other Vault binary in your PATH that is taking precedence.

**Comment by moisesguimaraes** [comment]
Hi @jefferai,

yep, you're right:

```
$ which vault
~/workspaces/go/bin/vault
$ pwd
~/workspaces/go/bin
$ ./vault -v
Vault v0.9.6 ('7e1fbde40afee241f81ef08700e7987d86fc7242')
$ vault -v
Vault v0.9.5 ('36edb4d42380d89a897e7f633046423240b710d9')
```
That was weird though, gotta find that other vault binary now. Thanks!
