### ISSUE TITLE
Sometimes Token TTL will be 0

### ISSUE THREAD

**Issue by shsjshentao** [hashicorp/vault#4209]
I think in usual time "token lookup" will return bad token instead of ttl=0 if token is expired.
But sometimes is not.
I used vault v0.9.3

#kubectl logs kubernetes-vault-rj764 -n core 
time="2018-03-27T05:45:50Z" level=debug msg="Discovered 3 nodes: [172.16.4.15 172.16.27.2 172.16.85.6]" 
time="2018-03-27T05:45:50Z" level=fatal msg="Could not create the vault client: error parsing supplied token: 2 errors occurred:\n\n* vault token is not renewable\n* token TTL is zero" 

#vault token-lookup -tls-skip-verify fea914a1-70b8-1834-85b8-7a6a755ed803                                                                                        Key                     Value 
---                     ----- 
accessor                e5a56719-7db8-2de5-f3bd-e572157f6e74 
creation_time           1520484224 
creation_ttl            21600 
display_name            token 
entity_id 
expire_time             <nil> 
explicit_max_ttl        0 
id                      fea914a1-70b8-1834-85b8-7a6a755ed803 
meta                    <nil> 
num_uses                0 
orphan                  false 
path                    auth/token/create/kubernetes-vault 
policies                [default kubernetes-vault] 
role                    kubernetes-vault 
ttl                     0

**Comment by jefferai** [comment]
That is not an error message being supplied by Vault. What is the client? How was the token created? What version of Vault? Please provide the information that was requested in the template.

**Comment by shsjshentao** [comment]
vault is  0.9.3
token is created by "vault token-create"
My meaning is if a token is expired, it will show this message
Error looking up token: Error making API request.

URL: POST https://127.0.0.1:8200/v1/auth/token/lookup
Code: 403. Errors:

* bad token

Sometimes in fact, it shows normal but ttl=0

**Comment by jefferai** [comment]
What is the role configuration?

**Comment by shsjshentao** [comment]
vault write -tls-skip-verify auth/token/roles/kubernetes-vault allowed_policies=kubernetes-vault period=6h

no special configuration

**Comment by jefferai** [comment]
If the token is in fact expired, having a TTL of zero is what it will display. Generally you shouldn't be able to look it up anymore, but it's possible that there is some issue revoking it -- trace logs would help.

**Comment by shsjshentao** [comment]
Does this PR "Offline token revocation fix" fix this issue? @jefferai

**Comment by michelvocks** [comment]
Hi @shsjshentao!

I will close this issue for now since we fixed several bugs since the release of Vault 0.9.3 regarding expired tokens which were not removed by Vault. Feel free to open a new issue if this bug still occurs with the current latest Vault version.

Cheers,
Michel
