### ISSUE TITLE
PostgreSQL backend hanging

### ISSUE THREAD

**Issue by nevir** [hashicorp/vault#421]
When reading credentials via `consul-template` (https://github.com/hashicorp/consul-template/issues/336) as well as `vault read postgres/creds/role`, we're running into a situation where it hangs indefinitely. The database is an RDS instance

The vault master logs nothing related to this (even on `-log-level debug`; all we see are revocations, and nothing else), as well :(

I'm curious if you have any tips for diagnosing this?

**Comment by armon** [comment]
@nevir You may want to enable the audit logging on Vault, which will give you request/response information. I think we also need to expose more details in consul-template at higher log levels (ping @sethvargo). My guess is no secret is being returned for that path, and that CT is blocking.

**Comment by nevir** [comment]
Hmm, with no configuration change, bouncing (and unsealing) the vault
process fixes this

**Comment by nevir** [comment]
(Even when that particular host becomes master again)

**Comment by armon** [comment]
Hmm, can you provide a repro case for this? Hard to diagnose otherwise

**Comment by sethvargo** [comment]
Hi @nevir 

Have you had any luck putting together a repro case?

**Comment by joshuata** [comment]
We saw very similar behavior caused by runaway connections  ( See #554 ).
Sealing and unsealing vault causes it to drop all open connections, which would explain why that fixes the problem.

**Comment by jefferai** [comment]
I agree with @joshuata , this sounds like the same problem. Please move discussion to #554.
