### ISSUE TITLE
Vault cluster does not establish connection between its instances

### ISSUE THREAD

**Issue by Milad-Irani** [hashicorp/vault#4210]
Hi.

I am using the following network policies in my Vault cluster:

Direction Ether Type IP Protocol Port Range Remote Source
egress IPv4 tcp 8300-8303 IP: 0.0.0.0/0
ingress IPv4 tcp 8200-8201 IP: 0.0.0.0/0
ingress IPv4 tcp 8300-8303 IP: 0.0.0.0/0
ingress IPv4 tcp 8500 IP: 0.0.0.0/0
ingress IPv4 udp 8300-8303 IP: 0.0.0.0/0

Using the above policies lets the vault cluster to build itself and vote for the leader. Using _$ vault status_ I see that some vault instances are in standby mode and one is active.
However, if I try to run the below command or any similar on any of standby vault nodes, I get timeout error:
$ vault list secret
Error listing secret/: Get http://leader-ip:8200/v1/secret?list=true: dial tcp leader-ip:8200: i/o timeout

As soon as I allow traffic on all ports, everything works fine. I am wondering which other ports have to be open other than the above ones. Based on documentation, vault uses the above ports.

**Environment:**
Vault v0.9.5 

* Vault Version:
Ubuntu 5.4.0-6ubuntu1~16.04.5

**Vault Config File:**
{
    "storage": {
        "consul": {
            "address": "127.0.0.1:8500",
            "redirect_addr": "http://self-ip:8200",
            "path": "vault",
            "service": "vault"
        }
    },
    "listener": {
        "tcp": {
            "address": "0.0.0.0:8200",
            "tls_disable": 0
        }
    }
}

**Actual Behavior:**
Error listing secret/: Get http://leader-ip:8200/v1/secret?list=true: dial tcp leader-ip:8200: i/o timeout

**Comment by chrishoffman** [comment]
The standby nodes do not handle requests and forward the requests to the leader on the cluster port which is 8201 by default.  I believe you are missing an egress rule for 8201.
