### ISSUE TITLE
Docs referring to deprecated commands

### ISSUE THREAD

**Issue by targetdrone** [hashicorp/vault#4213]
The documentation consistently says to use deprecated commands, such as "vault init", "vault unseal", etc.  These commands have been superseded by the "vault operator" command.  When used, the vault tool puts up a scary warning to the operator that they are deprecated and will be removed.  The correct commands the documents and usage prompts should present now are "vault operator init"; "vault operator unseal"; etc.

Documentation issues can be found in the following files: 
"vault init"
website/source/docs/concepts/pgp-gpg-keybase.html.md
website/source/docs/concepts/tokens.html.md
website/source/intro/getting-started/deploy.html.md
command/server.go
command/operator_init.go

"vault unseal"
website/source/docs/concepts/dev-server.html.md
website/source/docs/concepts/seal.html.md
website/source/docs/concepts/pgp-gpg-keybase.html.md
website/source/intro/getting-started/deploy.html.md
command/server.go

"vault generate-root"
website/source/guides/operations/generate-root.html.md
website/source/docs/concepts/tokens.html.md
command/operator_generate_root.go

"vault rekey"
website/source/docs/enterprise/hsm/behavior.html.md
command/operator_rekey.go
website/source/intro/getting-started/deploy.html.md
command/operator_init.go

"vault rotate"
command/rotate.go
website/source/guides/operations/rekeying-and-rotating.html.md

"vault seal"
command/operator_seal.go
website/source/intro/getting-started/deploy.html.md

**Comment by jefferai** [comment]
They'll be migrated eventually. We're sort of in a weird spot where in places where the updated commands are used people complain about the command not working (due to using old versions) and when we leave them people with the new versions get annoyed at the deprecation warnings.
