### ISSUE TITLE
Every logged in ldap user gets assigned all defined policies

### ISSUE THREAD

**Issue by zelentsovl** [hashicorp/vault#4215]
**Environment:**
* Vault Version:  v0.9.1
* Operating System/Architecture: Docker container on CentOS 7.3

**Vault Config File:**
storage "file" {   
  path = "/vault/file" 
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 0
  tls_key_file = "/etc/pki/tls/private/private.key"
  tls_cert_file = "/etc/pki/tls/certs/certificate.pem"
}

max_lease_ttl = "2304h"
default_lease_ttl = "2304h"

**Vault ldap config**  
`vault read auth/ldap/config`

binddn             cn=vault,ou=Admin,ou=Users,ou=City,dc=company,dc=local
bindpass           *********
certificate        -----BEGIN CERTIFICATE-----
**.........certificate body...........**
-----END CERTIFICATE-----
deny_null_bind     true
discoverdn         false
groupattr          samaccountname
groupdn            OU=SecurityGroups,OU=Groups,DC=company,DC=local
groupfilter        (objectClass=group)
insecure_tls       false
starttls           true
tls_max_version    tls12
tls_min_version    tls12
upndomain          company.local
url                ldaps://dc1.company.local:636
userattr           samaccountname
userdn             dc=company,dc=local

**Vault policies**  
`vault list sys/policy`

default
root
sd-dev-cms-modify-policy
sd-dev-cms-read-policy
sd-modify-policy
sd-qa-cms-modify-policy
sd-qa-cms-read-policy
sd-read-policy
secret-root-policy
so-deny-policy
so-modify-policy
so-read-policy

**Vault defined groups**
`vault list auth/ldap/groups`

VaultDevCMSUsers
VaultDevSDUsers
VaultDevSOUsers

**Expected Behavior:**
Every logged in LDAP user gets assigned only default policy.

**Actual Behavior:**
Every logged in LDAP user gets assigned all created policies even if he is not a member of any group.

**Steps to Reproduce:**
`vault -method=ldap username=user1`

token                  ****************************************
token_accessor         ******************************************
token_duration         2304h
token_renewable        true
token_policies         [default sd-dev-cms-modify-policy sd-modify-policy sd-qa-cms-modify-policy secret-root-policy so-deny-policy so-modify-policy]
token_meta_username    user1

**Comment by jefferai** [comment]
What are the policies assigned to the vault defined groups?

**Comment by pldmgg** [comment]
I'm having a similar problem.

Here's my LDAP (Active Directory) config:

```
/ # vault read auth/ldap/config
WARNING! The following warnings were returned from Vault:

  * Read access to this endpoint should be controlled via ACLs as it will
  return the configuration information as-is, including any passwords.

Key                Value
---                -----
binddn             cn=vault,ou=OrgUsers,dc=zero,dc=lab
bindpass           *************
certificate        -----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
deny_null_bind     true
discoverdn         true
groupattr          samaccountname
groupdn            ou=Groups,dc=zero,dc=lab
groupfilter        (objectClass=group)
insecure_tls       false
starttls           true
tls_max_version    tls12
tls_min_version    tls12
upndomain          zero.lab
url                ldaps://zerodc01.zero.lab:636
userattr           samaccountname
userdn             ou=OrgUsers,dc=zero,dc=lab
```

Things to note - there's a user "zero4admin" under "OU=OrgUsers" and there's a group called "VaultUsers" under "OU=Groups".

Then, on the vault server (i.e. docker container)...

```
PS C:\Users\pdadmin> docker exec -it --env "VAULT_ADDR=http://0.0.0.0:8200" --env "VAULT_TOKEN=myroot" dev-vault /bin/ash
/ # vault list secret
Keys
----
hello
thing
/ # vault read secret/hello
Key                 Value
---                 -----
refresh_interval    768h
value               world
/ # vault list sys/policy
Keys
----
default
hello-policy
root
/ # vault read sys/policy/hello-policy
Key      Value
---      -----
name     hello-policy
rules    path "secret/hello" {capabilities = ["create", "read", "update", "list"]}
/ # vault write auth/ldap/groups/VaultUsers policies=hello-policy
```

If I'm understanding the documentation properly, the above "hello-policy" should prevent a user in the "VaultUsers" Vault Group (which purely coincidentally has the same name as the Group in AD) from deleting `secret/hello` because `capabilties` does not include `delete`.. Unfortunately, it doesn't. Here's what I do next to test the policy...

```
/ # vault read auth/ldap/groups/VaultUsers
Key         Value
---         -----
policies    [hello-policy]
/ # vault login -method=ldap username=zero4admin
Password (will be hidden):
WARNING! The VAULT_TOKEN environment variable is set! This takes precedence
over the value set by this command. To use the value set by this command,
unset the VAULT_TOKEN environment variable or set it to the token displayed
below.

Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

Key                    Value
---                    -----
token                  fb23edd2-bfff-dcbc-f402-a731d98ad8f4
token_accessor         d5bb4acc-a4be-5d62-b7d5-1e78d4802aa9
token_duration         768h
token_renewable        true
token_policies         [default hello-policy]
token_meta_username    zero4admin
/ # vault read secret/hello
Key                 Value
---                 -----
refresh_interval    768h
value               world
/ # vault delete secret/hello
Success! Data deleted (if it existed) at: secret/hello
/ # vault read secret/hello
No value found at secret/hello
```

**Comment by jefferai** [comment]
@pldmgg Different issue, can you please open a new ticket?

**Comment by pldmgg** [comment]
No problem - just created #4283. Thanks for looking at this!

**Comment by dan-evolvere** [comment]
Am also seeing this in 1.0.0
This is a pretty major issue as it means we cant assign security policy based on LDAP/AD

Looking in the audit log both the policies and token policies are set to all mapped LDAP group entries, no matter what group the user is a member of.

**Comment by dan-evolvere** [comment]
Ok, further info, this specifically applies to LDAP config, if you are using active directory and select the tick box for Use Token Groups policy assignment works as expected, but without it, all policies are assigned to any user no matter what their group membership is.
Apologies if this is a misunderstanding on my part, but this doesn't seem right to me

**Comment by jeffWelling** [comment]
I thought I was hitting this problem, but it turned out to be that my LDAP user was simply in more LDAP groups than I had expected it to be in. 

After a careful cross examination, there are vault policies that are created which don't get assigned to my user, and all of the policies that do get assigned can be traced back to an LDAP group that I'm a member of which grants that policy. 

Just food for thought, is it possible that your users are members of more LDAP groups than expected?

**Comment by michelvocks** [comment]
Hi there!

I'm going to close this issue due to inactivity from the original issue owner. Feel free to open a new issue if you experience the same issue.

Cheers,
Michel
