### ISSUE TITLE
Add a `delete` acl role?

### ISSUE THREAD

**Issue by nbrownus** [hashicorp/vault#423]
I have a scenario in which a policy should only be allowed to delete something within a path however I do not want the policy to be able to write in that path. Thoughts on supporting a `delete`?

**Comment by armon** [comment]
@nbrownus Agreed as well. I think we need to figure out the backwards compatibly story. I think "write" is really a bucket of "read,write,delete" currently, but we need a way to unbundle it.

**Comment by jefferai** [comment]
This was implemented in 0.5 with `capabilities`.
