### ISSUE TITLE
Feature Request: Open API 2.0 / Swagger Spec (i.e. create swagger.json for this project)

### ISSUE THREAD

**Issue by pldmgg** [hashicorp/vault#4233]
I'm pretty new to Vault, and I've been slowly making my way through all of the documentation while trying to setup host and client signed ssh certificates. But what would be really amazing for API discoverability, is if you guys could publish a Swagger Spec (i.e. swagger.json) outlining how the API works. Example here:

https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger

**Comment by jefferai** [comment]
This will be happening over the next 9 months or so.

**Comment by LeenaSinghal0801** [comment]
Do we have any early release on this or a branch created with work in progress?

**Comment by jefferai** [comment]
Nothing currently, sorry.

**Comment by fbertetto** [comment]
Any progress related to swagger documentation ?

**Comment by kalafut** [comment]
OpenAPI has been available for some time:  https://www.vaultproject.io/api/system/internal-specs-openapi.html

The 1.2 beta release also leverages this in the new API Explorer. Type `api` in the web CLI type to get a Swagger UI view of all mounted endpoints.

**Comment by fbertetto** [comment]
awesome thanks !
