### ISSUE TITLE
Ability to delete all tokens issued for a given app-id

### ISSUE THREAD

**Issue by nbrownus** [hashicorp/vault#424]
I do not see a way to revoke all tokens for a specific app-id. I can `delete` the a specific app-id to ensure no further tokens are issued though.

Should the path of an app-id issued token include the app-id?

**Comment by armon** [comment]
@nbrownus That is an interesting point. I agree, that makes sense.

**Comment by ewoutp** [comment]
In addition I also would like to remove all user-id mappings to an app-id when the app-id is removed.

**Comment by jefferai** [comment]
Unfortunately the way that the `app-id` backend is coded precludes easily revoking via path. However, in 0.5.2, there will be accessors that allow revoking a token value without knowing the token ID. Combined with the SHA of the app-id contained in audit logs, which will be the same for each app-id, you can easily script something to go through the logs and revoke all tokens issued via a particular app-id.
