### ISSUE TITLE
vault unwrap command is broken

### ISSUE THREAD

**Issue by Milad-Irani** [hashicorp/vault#4245]
Hi,

When I try to unwrap a wrapped token using `vault unwrap <w-token>` the below error appears:

URL: **PUT** http://0.0.0.0:8200/v1/sys/wrapping/unwrap
Code: 400. Errors:

* wrapping token is not valid or does not exist

For me, PUT method seems suspicious, since Vault needs to use POST method to unwrap a token. I tried the above command both on Vault client and server and the behaviour is the same. However, if I send a POST request to /sys/wrapping/unwrap endpoint using postman, it returns the unwrapped token successfully.

**Environment:**
Vault v0.9.5 ('36edb4d42380d89a897e7f633046423240b710d9')

* Vault Version:
Linux Ubuntu 16.4

**Vault Config File:**
{
    "storage": {
        "consul": {
            "address": "127.0.0.1:8500",
            "redirect_addr": "http://10.180.0.100:8200",
            "path": "vault",
            "service": "vault"
        }
    },
    "listener": {
        "tcp": {
            "address": "0.0.0.0:8200",
            "tls_disable": 1
        }
    }
}

**Expected Behavior:**
unwrapped token

**Actual Behavior:**
URL: **PUT** http://0.0.0.0:8200/v1/sys/wrapping/unwrap
Code: 400. Errors:

Cheers,
Milad

**Comment by jefferai** [comment]
Cannot reproduce:
```
$ vault token create -policy=default -wrap-ttl=60
Key                              Value
---                              -----
wrapping_token:                  e32204fa-e21e-dfbc-3314-9d341defc400
wrapping_accessor:               0f0f88a9-40dd-b383-781d-66466c77aa0d
wrapping_token_ttl:              1m
wrapping_token_creation_time:    2018-04-03 10:05:50.186462726 -0400 EDT
wrapping_token_creation_path:    auth/token/create
wrapped_accessor:                43033491-ecdd-f64d-e2a2-aa30f229b5ad

$ vault unwrap e32204fa-e21e-dfbc-3314-9d341defc400
Key                Value
---                -----
token              12f08208-34a2-207e-f912-b0efb6bbe1b7
token_accessor     43033491-ecdd-f64d-e2a2-aa30f229b5ad
token_duration     768h
token_renewable    true
token_policies     [default]
```
Note that Vault treats PUT/POST interchangeably.

**Comment by Milad-Irani** [comment]
Sounds interesting. I also cannot reproduce it anymore! If we assume that unwrap command works fine, then normally if a w-token is not valid or is already unwrapped, this error raises. right?
Since I tried to generated and unwrap a w-token locally, no body could be able to unwrap it before me. Is there any chance that the w-token generator has been generating invalid tokens sometimes? :P

**Comment by jefferai** [comment]
It's entirely possible that it had already expired by the time you tried to use it. It could also have been an accidental client configuration error that you didn't repeat.
