### ISSUE TITLE
Type issue with allow_localhost in PKI role

### ISSUE THREAD

**Issue by brianshumate** [hashicorp/vault#4250]
**Environment:**

* Vault Version: Vault v0.10.0-beta1 ('7563d8fea0593ebe06ef9efa707000354eb15942')
* Operating System/Architecture: Linux/AMD64

**Vault Config File:**

N/A

**Startup Log Output:**

N/A

**Expected Behavior:**

```
$ vault write vaultron-int-pki/roles/vaultron-int \
    allow_localhost=true \
    allow_subdomains=true \
    allowed_domains=tacotown.consul \
    allow_bare_domains=true \
    allow_glob_domains=true \
    allow_ip_sans=true \
    allow_localhost=true \
    generate_lease=true \
    organization="Vaultron Lab" \
    max_ttl=42000h \
    ttl=42000h
Success! Data written to: vaultron-int-pki/roles/vaultron-int
```

**Actual Behavior:**
```
$ vault write vaultron_int_pki/roles/vaultron-int \
    allow_localhost=true \
    allow_subdomains=true \
    allowed_domains=tacotown.consul \
    allow_bare_domains=true \
    allow_glob_domains=true \
    allow_ip_sans=true \
    allow_localhost=true \
    generate_lease=true \
    organization="Vaultron Lab" \
    max_ttl=42000h \
    ttl=42000h

Error writing data to vaultron-int-pki/roles/vaultron-int: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/vaultron-int-pki/roles/vaultron-int
Code: 500. Errors:

* 1 error occurred:

* Error converting input [true true] for field allow_localhost: '' expected type 'bool', got unconvertible type '[]interface {}'
```
**Steps to Reproduce:**

1. Install and start latest Vault release or beta
2. Enable PKI secrets engine
3. Define a role that specifies a boolean value for `allow_localhost`

**Important Factoids:**

- Also tried on v0.9.6 with same results
- Passing `true` as quoted string does not work either
- API role creation does not exhibit this issue

**Comment by lindleywhite** [comment]
I ran into this same problem, the issue was that I have the same keys twice. In your example you have the same. "allow_localhost=true" is defined twice, hence the array of values.

**Comment by jefferai** [comment]
Thanks for the tip!
