### ISSUE TITLE
Binary file read and write

### ISSUE THREAD

**Issue by syuta** [hashicorp/vault#426]
Vault version :  0.2.1-dev  

I want to manage binary file(image file or pdf or Provisioning Profile etc..)  
1.entry binary file (pdf) 
```
% vault write secret/binaryfile binfile=@test.pdf
```

2.read binary file  
```
% vault read -format=binary -field=binfile secret/binaryfile > output.pdf
```
outout.pdf is generated. but the file can not open.  
(This is the same result even in the case of the image file)

Is this a correct?

**Comment by mterron** [comment]
You need to base64 encode the file first syuta.

**Comment by syuta** [comment]
I could get/set a binary file.
Thank you very much.
