### ISSUE TITLE
Allow a configuration option to drop to TLS1.1

### ISSUE THREAD

**Issue by lcbowen3** [hashicorp/vault#427]
The current implementation of Vault only allows connections via TLS1.2.  Many current Linux versions, such as CentOS 6.6 and RedHat 6.6, will not support connected via CURL due to the supported versions of curl and openssl/nss (and glibc 2.12 means that upgrading these tools is not trivial).  Allowing an administrator to select TLS1.1 will allow a much wider range of adoption.

**Comment by lcbowen3** [comment]
Actually, this needs to drop to TLS1.0 in order to support the older clients.  I've tested the code once the minimum was dropped and the older clients (linux 6 clients) can access Vault once it's dropped to TLS10.

**Comment by certifiedloud** [comment]
@lcbowen3 Why would you want to allow the use of an insecure protocol on a utility that is all about security?

**Comment by lcbowen3** [comment]
Let me start by addressing some of your assertions and then I'll respond to what (I think) is your question.
1) TLS 1 is not an "insecure" protocol.  Yes, there are better protocols, but I've never seen a paper or example showing TLS to be comprimised.  I'll admit I'm not a fan of some of the default ciphers available, but those can be constrained (and again, I've not found any evidence of them being comprimised)
2) "Security" is a very broad term.  Vault would fall under the category of a "security" app, but so would Bitdefender and HideMyAss - both very different in terms of their function and their interface.  Vault is intended to securely store data, providing it only to authorized users.  Yes, Vault provides transport layer encryption, but that's not it's core purpose - I could decide to access the Vault server via a highly encrypted VPN, or it could be a totally internal system only accessible to a very limited network and therefore transport security isn't something I'd need.

To address the question I think you're asking, security is all about balance.  We don't use 32 digit bank PIN numbers, even though they'd be far more secure because people have to be able to use them.  If Vault is secured so tightly that it cannot be used by the largest body of systems in use because the protocols in use are unavailable on those systems, it defeats the purpose of the software.  This patch, if implemented, will simply allow the administrator of the system to choose whether to slightly diminish the transport security in order to allow greater implementation.  It's a trade off, but one that, in my opinion, should be made by the administrators.

**Comment by certifiedloud** [comment]
TLS 1.0 has been known to have vulnerabilities [for a while].(https://isc.sans.edu/diary/TLS+Man-in-the-middle+on+renegotiation+vulnerability+made+public/7534)

In any case, if this is implemented strictly as an opt-in feature, then I have no issue with it. Every admin should have the ability to make these decisions on their own.

**Comment by armon** [comment]
Marking as enhancement, thanks!
