### ISSUE TITLE
documentation for advertise_addr has disappeared.  

### ISSUE THREAD

**Issue by dansteen** [hashicorp/vault#4279]
Hi!

It looks like the documentation for the consul backend `advertise_addr` has disappeared.  I didn't see any reference to this in the changelog, and it looks like the tests are still in for this, so I think this is a bug?

```
backend "consul" {
    # we use the defaults
    address = "127.0.0.1:8500"
    path = "vault"
    advertise_addr= "https://vault.prod.awse.xxxx.com:8200"
}
```

References:
https://www.vaultproject.io/docs/configuration/storage/consul.html

**Comment by jefferai** [comment]
advertise_addr long ago changed to api_addr, which is what is documented now.

**Comment by dansteen** [comment]
@jefferai cool.  didn't see it anywhere in the changelog.  thanks!

**Comment by jefferai** [comment]
It was a long time ago...for a long while it was actually changed to redirect_addr and the change to api_addr was more recent. So you're actually moving up two generations of naming :-)
