### ISSUE TITLE
POST transit/sign/:keyname no longer validates algorithm in Vault 0.10.0-rc1

### ISSUE THREAD

**Issue by mp911de** [hashicorp/vault#4282]
Attempting to create a signature with `ecdsa-p256` keys specifying an invalid algorithm succeeds. `algorithm` was verified in earlier versions.

Vault version: 0.10.0-rc1
 
Key creation:

```
{"derived":false,"exportable":false,"type":"ecdsa-p256","convergent_encryption":false}
```

Sign Request:

```
POST /v1/transit/sign/ecdsa-key HTTP/1.1
{"input":"aGVsbG8td29ybGQ=","algorithm":"blah-512"}"
```

Sign Response:

```
HTTP/1.1 200 OK
{"request_id":"20db6a2e-0e73-95bd-17bc-c5df8706d6d0","lease_id":"","renewable":false,"lease_duration":0,"data":{"signature":"vault:v1:MEUCIBra/EYSnb02PvzP7E32xSEAtj2oW0WNPrt4+EQN8OhqAiEAw8HQeiZx+qjuaFqtR/y1iX/p0NeS+iH9V7zC3dYeN84="},"wrap_info":null,"warnings":null,"auth":null}
```

**Comment by mp911de** [comment]
Signature verification seems also to not honor the `algorithm`.

**Comment by jefferai** [comment]
Signature algorithm is currently only applicable to RSA keys.  https://www.vaultproject.io/api/secret/transit/index.html#signature_algorithm
