### ISSUE TITLE
Suggestion: CFSSL Backend

### ISSUE THREAD

**Issue by ekristen** [hashicorp/vault#429]
I see that work has already been done to introduce a PKI backend, however there is another really awesome tool out there called CFSSL that does a lot of PKI stuff real easily already. Even letsencrypt.org is going to be using it. 

I'd be very interested in seeing a backend for CFSSL (local or remote) implementation.

**Comment by armon** [comment]
Agreed, this would be great to pull in for some of the PKI features.

**Comment by gdiazlo** [comment]
I was going to propose a letsencrypt backend to support certificate request , adquisition and renewal using letsencrypt. I guess supporting it through cfssl would be more a general approach :-? should i propose another issue/enhacenment here?

**Comment by jefferai** [comment]
@gdiazlo letsencrypt is a CA but solving a very particular problem - authn/authz on the public Internet without identity verification. Vault has built-in authn/authz and is intended for those wishing to run their own CA.

In 0.4 the PKI backend capabilities are highly expanded, including generating root and intermediate CAs and handing CSRs.

As to the OP, I believe at this point Vault can handle any common CA task. I don't really see a value in providing a separate CFSSL backend; if there are needs that the existing backend cannot support where CFSSL can be of help, CFSSL can just be used as a library.

**Comment by gdiazlo** [comment]
My point is not use letsencrypt as a pki backend of vault, is that vault can be a letsecrypt client and manage the private keys of the certificates letsencrypt sign. This way we have those keys and public certificates secured in vault. I think the point of CFSSL is the same, being able to use vault as an intermediary to some CAs (public probably) letting vault manage the secrets, instead of using a letsencrypt client and then upload the files to a generic vault.

**Comment by flyinprogrammer** [comment]
@jefferai Just thought you should know that with this PR: https://github.com/docker/swarmkit/pull/969 it would appear Vault could become a favorable external ca for docker swarm if it adopted the [CFSSL signing endpoint](https://github.com/cloudflare/cfssl/blob/master/doc/api/endpoint_sign.txt).

**Comment by jefferai** [comment]
@flyinprogrammer Thanks for the heads-up -- I've commented there. I don't think the right move is for Vault to adopt the CFSSL signing endpoint just for SwarmKit, but rather for SwarmKit to not make assumptions about the lack of other API-driven CAs. It ought to be pluggable.
