### ISSUE TITLE
Unable to compile 0.10.0-rc1 with OSS UI

### ISSUE THREAD

**Issue by fia5000** [hashicorp/vault#4295]
* Vault Version: 0.10.0-rc1
* Operating System/Architecture: linux/amd64

**Expected Behavior:**

Vault compiles with OSS UI

**Actual Behavior:**

```
root@gaily1:~/src/github.com/hashicorp/vault# make dev-ui
==> Checking that code complies with gofmt requirements...
==> Checking that build is using go version >= 1.10...
go generate
==> Removing old directory...
==> Building...
Number of parallel builds: 1

-->     linux/amd64: github.com/hashicorp/vault

1 errors occurred:
--> linux/amd64 error: exit status 2
Stderr: # github.com/hashicorp/vault/http
http/handler.go:92:123: undefined: assetFS```
```
**Steps to Reproduce:**
- Go version 1.10.1
- GOPATH set
- Vault release 0.10.0-rc1 checked out 
- ran `make bootstrap`
- ran `make dev-ui`

**Comment by chrishoffman** [comment]
We are still working through the exact build process and should have the resolved shortly.  In the meantime, you can run `make static-assets` before `make dev-ui`.

**Comment by fia5000** [comment]
@chrishoffman  Thanks.

Appears the folder structure `pkg/web_ui` also has to be created prior to running `static-assets`

**Comment by jefferai** [comment]
@fia5000 if you want you can build the docker container in scripts/cross and use that to build. I'm going to close this for now as this is something we know we need to do but haven't gotten to yet since it's *just* out.

**Comment by snh** [comment]
I too encountered this issue today and found that running `make static-dist` instead of `make static-assets` before the `make dev-ui` resulted in a usable binary.

For reference, `static-dist` includes the  `ember-dist` and `static-assets` targets.

To summarise the commands that I used against 5ddb2c3cb4608e7dd952a995d035703c50986944:

```shell
mkdir -p pkg/web_ui
make static-dist dev-ui
```
