### ISSUE TITLE
Feature Request: Add auth and audit-sections to vault configuration file

### ISSUE THREAD

**Issue by johanot** [hashicorp/vault#4296]
**Feature Request:**
I am constantly working towards scaling up the group of tools that I can configure in a declarative fashion. We routinely shut down and reinstall servers in order to ensure that our declarative system specs are up to date and no custom state is left behind unmanaged.

When we perform this re-install drill on our Vault cluster, we current have to exec the following manually from the CLI after Vault startup and unseal:

`vault auth enable approle`
`vault auth enable ldap`
`vault write auth/ldap/config ...`
`vault audit enable syslog`

.. except for maybe the ldap config above, there is nothing secret about the above statements.

I think it is sad, that I cannot configure this in the vault.hcl to ensure that Vault is configured the way I want it to at startup.

**Environment:**

* Vault Version:
Vault v0.9.6 ('7e1fbde40afee241f81ef08700e7987d86fc7242')

* Operating System/Architecture:
Linux jot-t470p 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jefferai** [comment]
We're not going to have this configuration in files. The path and the fact it's mounted may not be security sensitive but some of the parameters can be. And, we put as much config as possible behind Vault's barrier so that all such config is authn/authz'd by Vault and, even more importantly, can be audit logged.

I'd be open to thinking about having an attempt to mount the same backend type at the same path return a 200 with a warning if it already exists.

**Comment by johanot** [comment]
@jefferai I reconsidered my request, and I see your point. In that; you should _not_ necessarily be allowed to enable new auth backends, just because you have access to modify the vault config file. Sorry for my ignorance. 

But yes, a 2xx response to an existing backend mount could be nice.

For our automation project, I ended up with this:

```golang
if !authAppRole {
	err := vc.Sys().EnableAuthWithOptions("approle", &vault.EnableAuthOptions{
		Type:        "approle",
		Description: "Enable auth approle",
	})
	if err != nil && !strings.Contains(err.Error(), "already in use") {
		return err
	}
}

if !auditSysLog {
	err := vc.Sys().EnableAuditWithOptions("syslog", &vault.EnableAuditOptions{
		Type:        "syslog",
		Description: "Enable audit syslog",
	})
	if err != nil && !strings.Contains(err.Error(), "already in use") {
		return err
	}
}
```
.. which is not very nice, but works.

My API tests revealed another thing:

The **/auth** endpoint responds: _path **is** already in use_ 
whereas the **/audit** endpoint responds: _path already in use_ 
:slightly_smiling_face:

**Comment by jefferai** [comment]
We actually often have subtle differences in errors for a specific reason: when trying to debug with a user/customer, it can be hard without a stacktrace to understand precisely where an error is coming from if it has the same message in multiple places.

**Comment by adamtulinius** [comment]
> We actually often have subtle differences in errors for a specific reason: when trying to debug with a user/customer, it can be hard without a stacktrace to understand precisely where an error is coming from if it has the same message in multiple places.

Maybe you could include the endpoint name in the error message. That would be easier instead of remembering which endpoint contains "is" and which doesn't.
