### ISSUE TITLE
Vault UI Feature Request: Don't Show all login methods in Vault UI Login Page

### ISSUE THREAD

**Issue by fia5000** [hashicorp/vault#4307]
**Feature Request:**

Let Vault Administrators choose/select which login methods get displayed on the Vault UI login page. At the moment, the login page displays token, _userpass, LDAP, okta, github_ auth methods...most people will _never_ need all of those. 

For human operators, having **all**  of these options displayed by default, even if the authentication backend for any/all of these has not been configured by Vault administrators, creates confusion and furthermore, clutters the login form.

<img width="644" alt="image 2018-04-07 at 6 18 19 pm" src="https://user-images.githubusercontent.com/14826481/38460839-26550ab6-3a90-11e8-8e80-e3ef32a28b58.png">

**Comment by meirish** [comment]
Yeah, right now it’s a chicken or the egg problem because you have to be authenticated to read the auth mounts, so these are hard coded (that’s also why you have to specify the mount path). We do have plans for this, but ui support for it will come after the 0.10 release.  I’ll keep this open for now and keep you up to date when it ships.

**Comment by sidewinder12s** [comment]
Maybe just expose a subkey in the Vault config of what Auth methods to enable.

**Comment by jefferai** [comment]
It's already there: https://www.vaultproject.io/api/system/mounts.html#listing_visibility-1

**Comment by jefferai** [comment]
@meirish marked this as UI for tracking since it also isn't milestoned, I don't think there's anything left to do here but want confirmation before closing.

**Comment by sidewinder12s** [comment]
Weird, on the cluster I just upgraded to 0.10.2 it has Okta and GitHub listed on login which we don't even have mounted.

**Comment by jefferai** [comment]
I think if we cannot get a specific list we just offer all of them.

**Comment by Hosweay** [comment]
Can the list simply be made configurable? I don't need the UI to dynamically detect the enabled auth mechanisms, which creates the chicken and egg thing. I am fine if the default is all of them but having something customizable in the configuration would be my preference.

Even though we have Token auth enabled for applications, I may not want Token auth enabled for the UI. I may want my human users to use another form of auth than Token and having it configurable would be nice.

**Comment by monokal** [comment]
+1 - Having a whole bunch of irrelevant auth methods which are irrelevant to our users often causes confusion.

**Comment by devlounge** [comment]
when can we hope this to be implemented?
