### ISSUE TITLE
Problem with certificate of ldap on authentication

### ISSUE THREAD

**Issue by laerus** [hashicorp/vault#4327]
**Environment:**

* Vault Version: v0.9.6
* Operating System/Architecture: Debian 9 stretch 4.9.0-6-amd64

**Vault Config File:**

```hcl
storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault"
}
listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = true
}
```

**Startup Log Output:**

**Expected Behavior:**
Authentication with ldap

**Actual Behavior:**

```
Error authenticating: Error making API request.
URL: PUT http://127.0.0.1:8200/v1/auth/ldap/login/kon
Code: 400. Errors:
* 1 error occurred:
* error connecting to host "ldaps://ldap-server:636": LDAP Result Code 200 "Network Error": x509: certificate is not valid for any names, but wanted to match ldap-server
```

**Steps to Reproduce:**

**Important Factoids:**
Have been using this self signed certificate for everything else without ever having a problem, 
so the certificate is not the problem.

**References:**

**Comment by joelthompson** [comment]
Are you trying to use an invalid TLS certificate on your LDAP server? If so, the [`insecure_tls`](https://www.vaultproject.io/api/auth/ldap/index.html#insecure_tls) parameter is what you would need to configure. (And the usual disclaimer that doing so is not recommended as it reduces security.) You could also try configuring the [`certificate`](https://www.vaultproject.io/api/auth/ldap/index.html#certificate) parameter instead with your self-signed certificate.

**Comment by laerus** [comment]
I am using a valid self signed certificate on LDAP and have configured  the `certificate` parameter to point to my self signed CA certificate.

**Comment by jefferai** [comment]
The certificate may be valid in a signing sense, but the error is indicating that it doesn't have a proper DNS name configured on it. Can you paste your certificate PEM?

**Comment by laerus** [comment]
The problem probably is this SAN entry with an email address only:
```
  X509v3 Subject Alternative Name:
                email:laerusk@gmail.com
```
removing this part makes this work, even though the CN in the Subject is correct and works with any other service i've used, apparently vault doesn't look that up if there is any entry in SAN (even no DNS).

**Comment by jefferai** [comment]
I believe the Go verification logic follows RFC 6125 recommendations, section 6.4.4 (https://tools.ietf.org/html/rfc6125#section-6.4.4):
```
   As noted, a client MUST NOT seek a match for a reference identifier
   of CN-ID if the presented identifiers include a DNS-ID, SRV-ID,
   URI-ID, or any application-specific identifier types supported by the
   client.

   Therefore, if and only if the presented identifiers do not include a
   DNS-ID, SRV-ID, URI-ID, or any application-specific identifier types
   supported by the client, then the client MAY as a last resort check
   for a string whose form matches that of a fully qualified DNS domain
   name in a Common Name field of the subject field (i.e., a CN-ID).
```
Since you have SANs in the cert (any is sufficient to trigger this behavior), it does not look in the CN for a verifiable name.

**Comment by laerus** [comment]
i see, thanks for the clarification!
