### ISSUE TITLE
KV2 returns creation time in different format

### ISSUE THREAD

**Issue by mikebell90** [hashicorp/vault#4334]
For example, for token lookups, we get:
- "expire_time": "2018-04-27T13:52:37.227149435-07:00",

With kv2, creation_time looks like

created_time": "2018-04-11T04:50:04.906092335Z",

I'm pretty sure this change will break many time parsers. Yes, they are both ISO8601. However, many formatters (such as Java) require a specific formatting string. You can parse both, but you need to know the format.

Was this deliberate or inadvertant?

**Comment by jefferai** [comment]
It's the same format. Both are RFC3339.

**Comment by mikebell90** [comment]
But you changed the representation. That is beyond dispute. Why?

**Comment by jefferai** [comment]
I don't understand. What do you mean by "changed the representation"? Those two examples are the same time format.

**Comment by mikebell90** [comment]
In java at least you have to submit a datetimefornatter to parse iso dates.There are about 4 different variants. If it fails to parse it throws an exception.

The created format uses the default iso formatter. Expires and the other token metadata uses  another I believe it is called isodatetimewithoffset. 

Your change (which seems to have no specific benefit although I prefer the “new” one) means that java programs can no longer use a generic time deserializer. Instead they must either know which format, use a specific formatted for specific fields OR try each until one succeeds OR write their own custom parser.

None of that seems worth it offhand since if hashicorp just used a consistent representation ( either a utc instant or a offset instant) it would simply work with h one choice. I suspect that other language libraries will also break but that is just bias

**Comment by mikebell90** [comment]
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

**Comment by mikebell90** [comment]
That being said I will run a few tests today. Saw most of this reading and playing last night

**Comment by jefferai** [comment]
Again, neither is ISO. Both are RFC3339, which is similar to ISO8601 but not exactly the same.

For what it's worth, here is RFC3339Nano constant formatting string in go:

`RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"`

If what is tripping you up is the time zones, note that with the exception of audit logs which we always convert to UTC time, we use the local time on the server when storing values. In general this means that values that come back via user requests come back in a time zone most friendly to human users while still being easily parseable by any valid RFC3339 parser. (And, from my very minimal dive into ISO8601 on Wikipedia just now, both of those time zone offsets ought to be parseable via ISO8601 parsers as well).

**Comment by jefferai** [comment]
(For clarity on the above: according to Wikipedia, 
> The offset from UTC is appended to the time in the same way that 'Z' was above, in the form ±[hh]:[mm], ±[hh][mm], or ±[hh]. So if the time being described is one hour ahead of UTC (such as the time in Berlin during the winter), the zone designator would be "+01:00", "+0100", or simply "+01". To represent a time behind UTC the offset is negative. For example, the time in New York during standard (not daylight saving) hours is UTC−05:00. For other time offsets see List of UTC time offsets. To represent a negative offset, ISO 8601 specifies using either a hyphen–minus or a minus sign character. If the interchange character set is limited and does not have a minus sign character, then the hyphen–minus should be used. ASCII does not have a minus sign, so its hyphen–minus character (code is 45 decimal or 2D hexadecimal) would be used. If the character set has a minus sign, then that character should be used. Unicode has a minus sign, and its character code is U+2212 (2212 hexadecimal); the HTML character entity invocation is &minus;.

The only thing I can imagine tripping up your parser would be if you are passing the string in as UTF-8 and it's choking on the hyphen vs. minus sign, which it shouldn't, but could, so in that case simply pass it in as ASCII.)
