### ISSUE TITLE
Passing token via stdin inconsistent between providers

### ISSUE THREAD

**Issue by sebastiang** [hashicorp/vault#434]
$ vault auth d1a2148e-9ea0-8237-979d-01554f2cbd3c
    Successfully authenticated! The policies that are associated
    with this token are listed below:
    
    test
    $ echo "d1a2148e-9ea0-8237-979d-01554f2cbd3c" | vault auth token=-
    Error: Invalid token

What am I missing?

**Comment by armon** [comment]
@sebastiang I think it is just:

    $ echo token | vault auth -

**Comment by sebastiang** [comment]
I see now it's a provider-specific thing. That was confusing.

    $ vault auth method=github - < $FILE_WITH_TOKEN
    Invalid key/value pair '9039fd...39cb1: format must be key=value
    $ vault auth method=github token=- < $FILE_WITH_TOKEN
    Successfully authenticated! ...
    $ vault auth - < $FILE_WITH_TOKEN
    Successfully authenticated! ...
    $ vault auth token=- < $FILE_WITH_TOKEN
    Error: Invalid token

**Comment by jefferai** [comment]
The issue here is that "token" means different things to different auth backends. As there is documentation for the various auth backends to help, I'm going to close this.
