### ISSUE TITLE
UI doesn't correctly handle K/V version 2 paths when checking user capabilities

### ISSUE THREAD

**Issue by jcheng31** [hashicorp/vault#4348]
**Environment:**

* Vault Version: v0.10.0

**Expected Behavior:**

The Vault UI allows secrets to be created/edited/deleted when the user token has a policy supporting K/V version 2 paths.

**Actual Behavior:**

The Vault UI does not allow users to create/edit/delete secrets.

**Steps to Reproduce:**

Using a new Vault set-up with the version 2 KV store mounted at `secret`, I have the following structure for secrets:

`secret/<teamName>/<environment>/<secrets or services>`

(A concrete example: `secret/backend/production/myService`)

Following the [documentation for KV version 2](https://www.vaultproject.io/docs/secrets/kv/kv-v2.html), I have the following policy in place (please correct me if the comments are incorrect!):

```hcl
# Show available secret engines.
path "sys/mounts" {
  capabilities = ["list", "read"]
}

# Show the root folder in the secrets hierarchy (needed so the team folder appears in the UI)
path "secret/metadata/" {
  capabilities = ["list"]
}

# Show the team's environment folders.
path "secret/metadata/backend/" {
  capabilities = ["list"]
}

# Create/read/update/soft delete the latest version of secrets.
path "secret/data/backend/production/*" {
  capabilities = ["create", "read", "update", "delete"]
}

# Undelete previous versions of secrets.
path "secret/undelete/backend/production/*" {
  capabilities = ["update"]
}

# List versions and delete metadata.
path "secret/metadata/backend/production/*" {
  capabilities = ["read", "delete", "list"]
}

# Destroy any version of secrets.
path "secret/destroy/backend/production/*" {
  capabilities = ["update"]
}
```

If I use a token with this policy attached to it, I am able to use the CLI to create/read/delete/destroy (etc.) secrets under `secret/backend/production` as expected. However, I am only able to read secrets in the UI, and cannot create new ones or edit/delete existing ones.

I noticed in the browser dev tools that the UI seems to be making a call to check for the current user's capabilities, but it uses the version 1 path (`secret/backend/production`) instead of the version 2 one (`secret/data/backend/production`) - the response given is `deny`, as the path doesn't have a rule associated with it. Adding that path to the policy allows the UI to function as expected:

```hcl
path "secret/backend/production/*" {
  capabilities = ["create", "read", "update", "delete"]
}
```

(I realise the UI does point out that it doesn't support v2 fully - guessing that'll come in the future - though I figured I'd raise this in case it wasn't already caught, or if anyone else ran into the same issue.)

**Comment by jefferai** [comment]
Closing in favor of #4343
