### ISSUE TITLE
Self Signed Certificates

### ISSUE THREAD

**Issue by certifiedloud** [hashicorp/vault#438]
Is there any way to allow the use of self signed certificates when using the http api?
I currently get this response when trying to run "vault status": 

certificate signed by unknown authority

For my private organization a self signed certificate is sufficient and just as secure as
one signed by an actual authority.  It would be nice to be able to interact with the vault server regardless of signing authority.

**Comment by sethvargo** [comment]
Hi @certifiedloud 

If you do not want to add the self-signed cert to your local system, you can skip TLS verification. However, this reduces security. I would recommend installing the cert onto your system instead.

**Comment by certifiedloud** [comment]
Works for me, thanks!

**Comment by armon** [comment]
@certifiedloud You can also use the `-ca-cert` flag for most CLI commands!

**Comment by certifiedloud** [comment]
Ah! Good to know. Thanks.

**Comment by daxroc** [comment]
Adding the Certificate on RHEL

update-ca-trust enable
cp /etc/vault/ssl/certs/vault.crt /etc/pki/ca-trust/source/anchors/
update-ca-trust extract
vault status

**Comment by sprutner** [comment]
On Ubuntu 16.04

Assuming you have the certificate in your home directory:
```
mv ~/vault.crt /usr/share/ca-certificates/vault/vault.crt
echo "vault/vault-ca.crt" >> /etc/ca-certificates.conf
update-ca-certificates
vault status
```

**Comment by dfumagalli** [comment]
The above instructions (for example, @sprutner 's) should really make into the official documentation.

**Comment by pluc** [comment]
Four years later and I had to find this here because it still isn't in the official documentation. Neither is the source of the "vault-ca.crt" file mentioned anywhere.
