### ISSUE TITLE
How to access UI using TLS

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/vault#4381]
How can I access the web UI if using a self-signed TLS certificate?

Currently starting Vault server with:

```
vault server -config /opt/vault/config -log-level=info
```

And a config of:

```
storage "gcs" {
  bucket = "myproject-dev-vault-data"
  credentials_file = ""
}

listener "tcp" {
  address         = "0.0.0.0:8200"
  cluster_address = "0.0.0.0:8201"
  tls_cert_file   = "/opt/vault/tls/vault.crt.pem"
  tls_key_file    = "/opt/vault/tls/vault.key.pem"
}
```

When I hit `https://server-ip-here:8200/ui` I am getting:

```
404 page not found
```

**Comment by nodesocket** [comment]
Nevermind. Found out that you have to provide a flag into the config:

```
ui = true
```

The guide https://www.hashicorp.com/resources/vault-oss-ui-introduction does not mention that make that clear.

**Comment by meirish** [comment]
We'll get the guide updated - thanks for pointing that out!

**Comment by dexterac** [comment]
I dont see the details on the guide :)
Changed again ?
