### ISSUE TITLE
'Address "<address>" used for both API and cluster addresses' in Vault 0.10

### ISSUE THREAD

**Issue by boldandbusted** [hashicorp/vault#4383]
Howdy. I'm just kicking the tires on 0.10, and got bit by this error when I tried out 0.10 on my test VPC in AWS:

```
ubuntu@ip-10-50-1-45:~$ sudo /opt/vault/bin/vault server -config /opt/vault/config -log-level=info
Address "https://10.50.1.45:8201" used for both API and cluster addresses
ubuntu@ip-10-50-1-45:~$
```

Of course, I'll revert to 0.9.X, but this seemed to be the default expected by projects like this: https://github.com/hashicorp/terraform-aws-vault If you are using private subnets (in AWS, at least), what is the risk avoided here? Of course, maybe those projects are also being updated as I type this. ;)

FWIW, the Vault configuration file, as generated by the above Terraform module set, that I have on one of the Vault ASG cluster members, is included below.

Thanks for Vault! Cheers! :)

**Environment:**

```
ubuntu@ip-10-50-1-45:~$ vault -version
Vault v0.10.0 ('5dd7f25f5c4b541f2da62d70075b6f82771a650d')
ubuntu@ip-10-50-1-45:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
ubuntu@ip-10-50-1-45:~$ 
```

**Vault Config File:**

```hcl
listener "tcp" {
  address         = "0.0.0.0:8200"
  cluster_address = "0.0.0.0:8201"
  tls_cert_file   = "/opt/vault/tls/vault.crt.pem"
  tls_key_file    = "/opt/vault/tls/vault.key.pem"
}

storage "s3" {
  bucket = "pre-dev-vault"
  region = "us-west-2"
}

ha_storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault/"
  scheme  = "http"
  service = "vault"

  # HA settings
  cluster_addr  = "https://10.50.1.45:8201"
  redirect_addr = "https://10.50.1.45:8201"
}
```

**Startup Log Output:**

```text
ubuntu@ip-10-50-1-45:~$ cat /opt/vault/log/vault-stdout.log 
Address "https://10.50.1.45:8201" used for both API and cluster addresses
Address "https://10.50.1.45:8201" used for both API and cluster addresses
Address "https://10.50.1.45:8201" used for both API and cluster addresses
Address "https://10.50.1.45:8201" used for both API and cluster addresses
Address "https://10.50.1.45:8201" used for both API and cluster addresses
ubuntu@ip-10-50-1-45:~$ 
```

**Expected Behavior:**
Vault starts

**Actual Behavior:**
Vault did not start

**Steps to Reproduce:**
* Install Vault 0.10
* Install the configuration file above.
* 'sudo /opt/vault/bin/vault server -config /opt/vault/config -log-level=info'
* Notice error, and Vault refusing to start
* ???
* Profit

**Important Factoids:**

**References:**
This looks like it stems from this PR: https://github.com/hashicorp/vault/pull/4272 . I don't know why this is actually a "mistake" in all cases, but welcome some docs that state this.

**Comment by boldandbusted** [comment]
P.S. FWIW, I see no mention of this in the Vault release notes.

**Comment by jefferai** [comment]
This has always been an error, it's just that now we catch it at startup time instead of Vault failing later.
