### ISSUE TITLE
/auth/token/revoke-accessors broken

### ISSUE THREAD

**Issue by reverendtimm** [hashicorp/vault#4391]
Trying to remove old tokens that have gone past TTL, however vault doesn't seem to be able to. 

We're using vault in AWS using DynamoDB.

**Environment:**
Docker / ECS / DynamoDB

* Vault Version:
```/ # vault version
Vault v0.9.5 ('36edb4d42380d89a897e7f633046423240b710d9')
```

**Vault Config File:**
```disable_mlock = true

api_addr = "http://vault.xxx.com"

listener "tcp" {
        address = "0.0.0.0:8200"
        tls_disable = 1
}

storage "dynamodb" {
  ha_enabled = "true"
  region     = "eu-west-1"
  table      = "xxx-vault-ldn"
  endpoint   = "dynamodb.eu-west-1.amazonaws.com"
}
```

**Expected Behavior:**
Vault should remove the token

**Actual Behavior:**
Vault doesn't remove the token

**Steps to Reproduce:**
Unsure - This happened when DynamoDB throttled read/writes, and now vault can no longer remove the keys. We increased the read/write cap and gave it some time to recover, but still broken.

**Important Factoids:**
It seems like the response vault is giving is "yes this is done" as it responds with a 204. However, when listing the accessors again, it isn't removed.

**Curl requrests showing the issue**
```---------------------------------------------------------------------------------------

root@debian:~# curl  https://vault.xxxx.com/v1/auth/token/accessors -X LIST --header "X-Vault-Token: xxxxxxxxxxxxxxxxxxxxxxxxx" 
{
	"request_id":"af3b9516-14b7-6a30-963f-bef57d7c5322",
	"lease_id":"",
	"renewable":false,
	"lease_duration":0,
	"data":{
		"keys":[
			"add20904-33ac-6b71-7b35-99316031a420",
			"945ad090-98d5-77d5-95b1-dd5f33d857fa",
			...
			
---------------------------------------------------------------------------------------

root@debian:~# curl https://vault.xxx.com/v1/auth/token/revoke-accessor -X POST -d '{"accessor": "add20904-33ac-6b71-7b35-99316031a420"}' --header "X-Vault-Token: xxxxxxxxxxxxxxxxxxxxxxxxx" -v
...
< HTTP/1.1 204 No Content
< Cache-Control: no-store
< Content-Type: application/json
...

---------------------------------------------------------------------------------------

root@debian:~# curl  https://vault.xxx.com/v1/auth/token/accessors -X LIST --header "X-Vault-Token: xxxxxxxxxxxxxxxxxxxxxxxxx" 
{
	"request_id":"9c655600-0c3b-c2ec-aa1e-e3f3a9ddbe61",
	"lease_id":"",
	"renewable":false,
	"lease_duration":0,
	"data":{
		"keys":[
			"add20904-33ac-6b71-7b35-99316031a420",
			"945ad090-98d5-77d5-95b1-dd5f33d857fa",
			...

---------------------------------------------------------------------------------------
```

**Command on the CLI**

```
/ # vault token revoke -accessor 945ad090-98d5-77d5-95b1-dd5f33d857fa
Success! Revoked token (if it existed)
```
This token still displays in the Accessor list via the API.

Just tried a force revoke on the CLI. This appears to be successful, but still no revocations. 
```
/ # vault lease revoke -force -prefix /auth/userpass
Warning! Force-removing leases can cause Vault to become out of sync with
secret engines!
Success! Force revoked any leases with prefix: /auth/userpass
```

**Comment by jefferai** [comment]
I believe in this case you need to use auth/token/tidy.

**Comment by reverendtimm** [comment]
We already tried that. It cleaned up entries with no valid data. i.e. it was just a token with no additoinal attributes, however the tidy still left the data there. It said something similar to "removing nil token" when removing the malformed ones.

We have ended up nuking the dynamoDB table and recreating it, however I thought I'd raise it as there seems to be no way of actually removing the tokens.

**Comment by jefferai** [comment]
Unfortunately if you've nuked the data we won't be able to make test builds for you to try. So it's not clear whether you are looking at e.g. actual tokens that are left or just the accessories index entries.

**Comment by reverendtimm** [comment]
Yeah - I was thinmking the same thing. Unfortunatley it's just entered production state, so there wasn't really much time to dick around.

I'll reopen if it happens again though.

**Comment by jefferai** [comment]
Sounds good!
