### ISSUE TITLE
Vault CLI does not honour 308 redirects.

### ISSUE THREAD

**Issue by bpinske** [hashicorp/vault#4401]
**Environment:**
* Vault Version: Vault v0.10.0 ('5dd7f25f5c4b541f2da62d70075b6f82771a650d')
* Operating System/Architecture: Ubuntu

**Vault Config File:**
```hcl
{"listener":{"tcp":{"address":"[::]:8200","tls_disable":true}},"storage":{"consul":{"address":"consul-consul-0.consul-consul.consul.svc.cluster.local:8500","path":"vault/"}}}
```

**Startup Log Output:**
```text
==> Vault server configuration:

                     Cgo: disabled
         Cluster Address: https://10.233.82.19:8201
              Listener 1: tcp (addr: "[::]:8200", cluster address: "[::]:8201", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
        Redirect Address: http://10.233.82.19:8200
                 Storage: consul (HA available)
                 Version: Vault v0.9.0
             Version Sha: bdac1854478538052ba5b7ec9a9ec688d35a3335

==> Vault server started! Log data will stream in below:

2018/04/19 22:52:39.997679 [INFO ] core: vault is unsealed
2018/04/19 22:52:39.998009 [INFO ] core: entering standby mode
2018/04/19 22:52:40.022677 [INFO ] core: acquired lock, enabling active operation
2018/04/19 22:52:40.104266 [INFO ] core: post-unseal setup starting
2018/04/19 22:52:40.105214 [INFO ] core: loaded wrapping token key
2018/04/19 22:52:40.105245 [INFO ] core: successfully setup plugin catalog: plugin-directory=
2018/04/19 22:52:40.106797 [INFO ] core: successfully mounted backend: type=kv path=secret/
2018/04/19 22:52:40.107124 [INFO ] core: successfully mounted backend: type=system path=sys/
2018/04/19 22:52:40.107548 [INFO ] core: successfully mounted backend: type=identity path=identity/
2018/04/19 22:52:40.107595 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2018/04/19 22:52:40.112134 [INFO ] expiration: restoring leases
2018/04/19 22:52:40.112214 [INFO ] rollback: starting rollback manager
2018/04/19 22:52:40.112846 [INFO ] expiration: lease restore complete
2018/04/19 22:52:40.113791 [INFO ] identity: entities restored
2018/04/19 22:52:40.114279 [INFO ] identity: groups restored
2018/04/19 22:52:40.114777 [INFO ] core: post-unseal setup complete
2018/04/19 22:52:40.114789 [INFO ] core/startClusterListener: starting listener: listener_address=[::]:8201
2018/04/19 22:52:40.115044 [INFO ] core/startClusterListener: serving cluster requests: cluster_listen_address=[::]:8201
```

**Expected Behavior:**
The vault CLI should be able to speak to the server through a reverse proxy. As in, follow a 308 redirect.

**Actual Behavior:**
```console
curl http://vault.me.com/v1/sys/init
<html>
<head><title>308 Permanent Redirect</title></head>
<body bgcolor="white">
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx/1.13.8</center>
</body>
</html>
```

```console
curl -L http://vault.me.com/v1/sys/init
{"initialized":true}
```

```console
vault read kv/airplane
Error reading kv/airplane: invalid character '<' looking for beginning of value
```

Vault is getting the html body of the 308 response and not knowing what to do with it. How can I have vault's CLI honor redirects?

The closest thing is a line for configuring the UI, but that isn't what I want.
https://www.vaultproject.io/docs/configuration/#ui

**Steps to Reproduce:**
Install the vault Helm chart and configure the ingress point and attempt to access vault through the reverse proxy.

**Important Factoids:**
Running on top of Kubernetes, via the official Helm chart.
https://github.com/kubernetes/charts/tree/master/incubator/vault

**Comment by jefferai** [comment]
Currently 308s are not supported. I've also never seen a reverse proxy returning a 308; normally they should be transparent, so it's not clear to me that it *should* be supported. What is being redirected from/to (it's not clear from the above example what the old/new URIs are)? Can't you simply configure the reverse proxy to be transparent?

**Comment by jefferai** [comment]
Also, the example from the page you linked to appears to have no issues, so I wonder what is different in your setup.

Finally, the CLI *does* honor 307s, but only one. This is designed for Vault's HA redirection (as a backup to request forwarding), so if you can configure your proxy to issue 307s instead that would also work.
