### ISSUE TITLE
losing tokens

### ISSUE THREAD

**Issue by taskinosman** [hashicorp/vault#4402]
Hi, we are slowly migrating our system to vault but i have seen a strange behaviour since weeks. I do use 'node-vault' and a deploy script to create the credentials. this is the only input to vault which changes the data. All other operations are read from clients. 

I am creating json data,tokens and corresponding policies. Once i create them all works well then after a random while vault starts responding permission denied. I am using a third party UI to see the data. The data is there, policies are there but few or the tokens are simply not there.

The fact that it works 3-10 days and then simply few of the 20 tokens are GONE which leads to permission denied and stops the services.

I have tried Vault 0.9.5 and 0.9.3. both have the same problem. Is there anything i can help to sort out this issue?

Thanks

**Comment by jefferai** [comment]
You didn't provide much of the requested details, so my best guess based on what you did provide is that they are simply expiring. It would be helpful to know:

Your configuration
How the tokens are being created, using what method and with what parameters
Representative output of a token lookup
Information on how you are renewing them, and when

**Comment by calvn** [comment]
Are the tokens that are being created periodic tokens? Aside from root tokens without expirations, all other tokens will expire once they have reached their maximum allowed TTL. The other exception to this are [periodic tokens](https://www.vaultproject.io/docs/concepts/tokens.html#periodic-tokens), which can have its TTL renewed many times over as long as you do so before its expiry.

**Comment by taskinosman** [comment]
Hi,
i am using this code to create the tokens

```
function deployToken(t) {
    if (t.policies.length==0) {
        log("the token you want to create as",t.id,"has empty 'policies', this means it will create a root token. this is not allowed for now");
        process.exit(0);
    }
    return new Promise((resolve,reject)=>{
        vault.tokenLookup({token:t.id}).then(r=>{
            // remove token
            if (t.remove===true) {
                vault.tokenRevoke({token:t.id}).then(()=>{
                    log(chalk.green("removed token",t.id));
                    resolve(true);
                }).catch(e=>{
                    log(chalk.red("error by removing token",t.id,e));
                    reject(e);
                });
                return;
            }
            // token exists
            // lets compare the entities
            var redeploy=false;
            if (r.data) {
                if (r.data.display_name!=="token-"+t.display_name) redeploy=true;
                if (JSON.stringify(_.sortBy(t.policies))!==JSON.stringify(_.sortBy(r.data.policies))) redeploy=true;
                if (redeploy) {
                    log("Redeploying token",t.id);
                    log("Policies:",JSON.stringify(_.sortBy(t.policies)),JSON.stringify(_.sortBy(r.data.policies)));
                    log("Displayname:",t.display_name,r.data.display_name);
                    vault.tokenRevoke({token:t.id}).then(r=>{
                        // now time to re-create the ticket
                        log("token revoked, re-creating the token");
                        vault.tokenCreate(t).then((r)=>{
                            log("token",t.id,"created successfully");
                            resolve(r);
                        }).catch(e=>{
                            log("token",t.id,"could not be created",e);
                            reject(e);
                        })
                    }).catch(e=>{
                        log("Error by revoking token",t.id,e);
                        reject(e);
                    })
                } else {
                    log(chalk.gray("token",t.id,"(",t.display_name,") is still valid"));
                    resolve(true);
                }
            } else 
            {
                log(chalk.red("invalid token response from",t.id,r));
                reject("invalid token response");
            }
        }).catch(e=>{
            if (t.remove) {
                log(chalk.gray("token",t.id,`(${t.display_name})`,"was already removed"));
                resolve(true);
                return;
            }
            if (e.toString().search(/bad token/)>-1) {
                vault.tokenCreate(t).then((r)=>{
                    log(chalk.green("token",t.id,"created successfully"));
                    resolve(r);
                }).catch(e=>{
                    log(chalk.red("token",t.id,"could not be created",e));
                    reject(e);
                })
                return;
                // token does not exit
            }
            log("Error by looking up token",t.id);            
            reject(e);
        });
    })
}
```

I do run vault 0.9.5 and use `"node-vault": "^0.7.1"` at my deploy script. I am using file as storage. I am deploying using root token yes and indeed i must have missed that all tokens have TTL. I assumed because i have not defined any parameter they would not expire. I just read from the documentation about `default_lease_ttl (string: "768h") – Specifies the default lease duration for tokens and secrets. This is specified using a label suffix like "30s" or "1h". This value cannot be larger than max_lease_ttl.`. This default time is 32 days.

The configuration i am using is default:

```
listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = 0
  tls_cert_file = "/etc/letsencrypt/live/xxx.com/fullchain.pem"
  tls_key_file = "/etc/letsencrypt/live/xxx.com/privkey.pem"
}

api_addr ="https://xxx.com:8200/"

storage "file" {
  path = "/root/vault.data"
}
```

But i know several cases there the token has expired within less than 1 week period. I have looked up 1 of the recenly "expired" token:

```
Key                 Value
---                 -----
accessor            6051ade4-bdb4-4327-f9a7-ad48b811a1fc
creation_time       1524196510
creation_ttl        2764800
display_name        token-banhunter
entity_id           n/a
expire_time         2018-05-22T03:55:10.729175002Z
explicit_max_ttl    0
id                  47f320c4-eb2f-44de-a634-d559358a1abf
issue_time          2018-04-20T03:55:10.729174526Z
meta                <nil>
num_uses            0
orphan              false
path                auth/token/create
policies            [banhunter default]
renewable           true
ttl                 2761710
```

indeed it looks like it has a ttl of 32days. I`ll be watching this from ttl perspective. I really appreciate your product and effords

**Comment by jefferai** [comment]
Because the tokens you are creating are not orphan, they will be revoked when the parent that created them is revoked/expired. That's the likely reason that you are seeing them become unusable prior to 32 days.

**Comment by krish7919** [comment]
I am hitting a similar issue, although the parent token and all child tokens have the same TTL here.

We use Kubernetes auth and are trying to issue dynamic credentials for the database secrets engines.

For some reason, even though the expiry is 1 week, I get issued a single use token; back to back calls using the same token isn't possible.

Might that be related to this issue?
