### ISSUE TITLE
Connect to Vault server running in Docker container

### ISSUE THREAD

**Issue by alexei-led** [hashicorp/vault#441]
I'm trying to connect to Vault server running in Docker container (on OS X with Boot2Docker). I've build my own image (based on Alpine), but any public image out there also does not work for me. Does not matter if I use `vault init -address=http://<Docker Host IP>:8200` or HTTP API, always get a "connection refused" error.

**Comment by sethvargo** [comment]
Hi @alexei-led 

Have you disabled TLS? Vault runs with TLS enabled by default.

**Comment by alexei-led** [comment]
event `server -dev` mode?
I also tried with etcd backend and disable TLS for tcp listener 
```
listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = 1
}
```

**Comment by sethvargo** [comment]
Vault will bind to 127.0.0.1. I think (I'm not a Docker expert) - you need to bind to the IP or 0.0.0.0 to allow external connections.

**Comment by alexei-led** [comment]
Here is my configuration file for etcd backend. Note: `__ETCD_ADDR__` is replaced with etcd URL before vault is started.

```
backend "etcd" {
  address = "__ETCD_ADDR__"
  path = "vault"
  advertise_addr = "http://127.0.0.1"
}

listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = 1
}

disable_mlock = true
```

**Comment by alexei-led** [comment]
It seems that I need to put `0.0.0.0:8200` into `tcp.address` to allow connection from remote host. Closing issue.

**Comment by sholavanalli** [comment]
Why is this not documented?

**Comment by jefferai** [comment]
@sholavanalli why is what not documented?
