### ISSUE TITLE
Question about safety of transit provider when used concurrently

### ISSUE THREAD

**Issue by BRMatt** [hashicorp/vault#442]
Context: We're hoping to use vault to encrypt similar kinds of data with different keys. The key that the app will use will be determined by the source of the data. While derived keys would be a great fit for this, we can't use them in this situation as we want to limit the services that can decrypt data. e.g. a service should be able to decrypt data from source x and y, but not z.

Looking through the code it seems that vault will attempt to [create an encryption key if one does not exist](https://github.com/hashicorp/vault/blob/fccc27894e705ae3619eb2fc44660ef7854aed0a/builtin/logical/transit/path_encrypt.go#L74-L81), but we're concerned that concurrent requests to encrypt data with a key that does not exist could cause encryption keys to be lost. This is all hypothetical - we haven't experienced this race condition first hand, we've just been reading the code.

For example, if two requests to encrypt data with the same key come in, and they both identify that the key does not exist they'll [both try to create it](https://github.com/hashicorp/vault/blob/master/builtin/logical/transit/path_encrypt.go#L74-L81). It seems that the storage [API uses upsert semantics](https://github.com/hashicorp/vault/blob/fccc27894e705ae3619eb2fc44660ef7854aed0a/physical/mysql.go#L80-L81), so whichever request comes first would have its encryption key overwritten.

Does this seem possible, or is there a lock somewhere in vault that would prevent this scenario from happening?

**Comment by armon** [comment]
@BRMatt This is definitely a possible race. Currently if that is a risk, we recommend just making the named key before using it to avoid the upsert. Still, tagged as bug.

**Comment by jefferai** [comment]
Hi @BRMatt ,

In 0.5 the `transit` backend was enhanced to prevent data races. You can take another look through the code and you'll find that there is locking all throughout. In addition, our acceptance tests do a bunch of fuzz testing to verify correct behavior as multiple clients hammer the backend.

**Comment by BRMatt** [comment]
Cheers Jeff!
