### ISSUE TITLE
Vault UI and a way to obfuscate the secrets

### ISSUE THREAD

**Issue by mateibarbu-sphs** [hashicorp/vault#4422]
Hi everybody,
We have just started working with Vault, with the File backend, but i've ran into a situation in which i need to hide/obfuscate secrets when i enter in a key. Like another button just to show me the password.
Is there a way to do this with Vault UI? 

Best regards,
Matei

**Feature Request:**
--> Obfuscation

Vault v0.10.0
* Operating System/Architecture: Linux

**Comment by meirish** [comment]
Hi! We've discussed adding something like this (/cc @joshuaogle) - but the UI doesn't currently support this.

**Comment by meirish** [comment]
Hi @mateibarbu-sphs - could you share more about your use case for this? We're trying to better understand the need for it. Thanks!

**Comment by mateibarbu-sphs** [comment]
Hi Meirish, well i was talking to my colleagues about the new GDPR rules and there are some issues working in open spaces and the fact that people could see some sensitive information.

So a good way to further add a thin layer of security for social hacking would be have this obfuscation so that after we open a key we have the obfuscation feature to not show the passwords ( values of the keys ), so you would be required to press this button for it to show your values. Google Chrome, Firefox have this implemented when you want to see the saved passwords.

Best regards,
Matei

**Comment by soner89** [comment]
Hi,

we are looking into using Vault, too but noticed that the password-fields are shown in clear text in the UI. We would love to have this feature!

Best regards,
Soner
