### ISSUE TITLE
Can't create token for role

### ISSUE THREAD

**Issue by tino** [hashicorp/vault#4423]
**Environment:**

* Vault Version: Vault v0.10.0 ('5dd7f25f5c4b541f2da62d70075b6f82771a650d')
* Operating System/Architecture: Mac OS

**Vault Config File:**
`vault server -dev`

**Expected Behavior:**
Create a token

**Actual Behavior:**
Errors with "unkown role"

**Steps to Reproduce:**
(Logged in as root)
```
⌘ vault write auth/approle/role/app \
      secret_id_ttl=168h \
      token_ttl=10m \
      token_max_ttl=30m \ 
      policies=default
Success! Data written to: auth/approle/role/app

⌘ vault list auth/approle/role
Keys
----
app

⌘ vault token create -role=app
Error creating token: Error making API request.

URL: POST http://127.0.0.1:8200/v1/auth/token/create/app
Code: 400. Errors:

* unknown role app

# role id? Neither
⌘ vault read auth/approle/role/app/role-id
Key        Value
---        -----
role_id    b866617d-73bd-ed36-5680-5010fafaedbc
⌘ vault token create -role=b866617d-73bd-ed36-5680-5010fafaedbc
Error creating token: Error making API request.

URL: POST http://127.0.0.1:8200/v1/auth/token/create/b866617d-73bd-ed36-5680-5010fafaedbc
Code: 400. Errors:

* unknown role b866617d-73bd-ed36-5680-5010fafaedbc

```

**References**
Documentation of `role_name` param for create token: https://www.vaultproject.io/api/auth/token/index.html#role_name

**Comment by chrishoffman** [comment]
The role_name parameter references a token role and not an app role.  To create a token role, see https://www.vaultproject.io/api/auth/token/index.html#create-update-token-role.
