### ISSUE TITLE
Allow the RFC 5280 "Name Constraints" setting on vault CA certs.

### ISSUE THREAD

**Issue by dansteen** [hashicorp/vault#4441]
**Feature Request:**
We use vault generated certificates for our services, and in general it is truly fantastic.   One disadvantage however, is that users must import our vault CA certificate to their machines.  This is not a huge deal, however, some users have expressed concerns that, in the event of a compromise of the CA certificate key, a bad actor could launch MitM attacks against them for any site on the internet (including their banks etc).

A simple (from a users perspective 😀  ) solution to this would be to implement RFC 5280 Name Constraints on the CA certificates generated by vault (see here: https://tools.ietf.org/html/rfc5280#section-4.2.1.10 ).  That would allow us to restrict the allowed certificates to just a few names and resolve the concerns of our users.   

I realize this is similar to the "allowed_domains" family of configuration that can be set on a role, but that only prevents the vault server from generating those certificates.   This would allow the client to reject certificates that are not included in the list on their own. 

Thanks!

**Comment by jefferai** [comment]
This is already supported: https://www.vaultproject.io/api/secret/pki/index.html#permitted_dns_domains
