### ISSUE TITLE
vault CLI 0.10 "kv put" appending /data

### ISSUE THREAD

**Issue by fewknow** [hashicorp/vault#4443]
* Vault Version:
* Operating System/Architecture:
sflint@mac017 vault (master)$ vault --version
Vault v0.10.0 ('5dd7f25f5c4b541f2da62d70075b6f82771a650d')

```text
sflint@mac017 vault (master)$ vault kv put secret/practitioner-national-provider npf.datasource.username=postgres npf.datasource.password=testing networks.datasource.username=postgres networks.datasource.password=testing
Success! Data written to: secret/data/practitioner-national-provider


```

**Expected Behavior:**

Should have written key `secret/practitioner-national-provider`
**Actual Behavior:**

Success! Data written to: secret/data/practitioner-national-provider

**Important Factoids:**

With the old way of using `vault write` this works. 

sflint@mac017 vault (master)*$ vault write secret/practitioner-national-provider npf.datasource.username=postgres npf.datasource.password=testing networks.datasource.username=postgres networks.datasource.password=testing
Success! Data written to: secret/practitioner-national-provider

**Comment by jefferai** [comment]
This is expected because the `vault kv` command is a helper to make using KV v2 easier, and paths in KV v2 mounts have data at `data/`.

**Comment by fewknow** [comment]
@jefferai Thanks for the clarification.

**Comment by manikawnth** [comment]
I see this is even affecting the policies. 
Now I've explicitly update the policy to the path `secret/data/foo` . Is there any backwards compatibility for the policies while using V2 KV?
