### ISSUE TITLE
Unable to compile vault source - make dev

### ISSUE THREAD

**Issue by pavankumar2203** [hashicorp/vault#445]
I followed the steps to install GO and update GOPATHs and everything. Also got the latest vault repo and put it in GOPATH directory. When I do 'make dev' , I get the following error:

username@vauhs001A:~/go/src/github.com/hashicorp/vault$ make dev
go generate ./...
==> Getting dependencies...
../../gocql/gocql/compressor.go:4:2: no buildable Go source files in /home/username/go/src/github.com/golang/snappy/snappy
make: *** [dev] Error 1

Can someone please help ? Is there anything I am doing wrong ? or has the source of snappy changed ?

**Comment by BRMatt** [comment]
Try the patch in #404, it might help.

**Comment by pavankumar2203** [comment]
Awesome. I replaced the srcipts/build.sh with https://github.com/BRMatt/vault/blob/e477ff2f9471852ad51da659520665ced04c6d47/scripts/build.sh
and it worked. Thanks.
