### ISSUE TITLE
Option to display current token in Vault UI

### ISSUE THREAD

**Issue by khicks** [hashicorp/vault#4453]
Hello!

I'm loving the newly open sourced UI for Vault! However, I've noticed it's lacking the ability to display the current authentication token to the user. I sometimes need to log into the UI with userpass and use the token I'm issued to do some other API work.

Alternatives would be to either install the Vault CLI on my local machine and do `vault login -method=userpass ...`, or monitor the web browser's requests and grab the token from HTTP headers.

I hope this is a small and simple change that will add a ton of convenience to the Vault UI.

Thanks for your consideration!

**Comment by mjacksonw** [comment]
We had this issue too, and for now, we're using a bookmarklet like this to expose the token:

```
javascript:alert(JSON.parse(localStorage.getItem(localStorage.key(0))).token)
```
