### ISSUE TITLE
Unable to enable TLS: x509: certificate signed by unknown authority for certificates using SHA2-384 as a hash algorithm 

### ISSUE THREAD

**Issue by JustinLaRose** [hashicorp/vault#448]
Certificate provided by my CA (Comodo) is using SHA2-384 as a hash algorithm. When I install the certificate into Vault it results in the following error:

"x509: certificate signed by unknown authority"

This appears to be a known issue. A solution being offered on different threads was:
"import crypto/sha512" which will register sha384/512 algorithms

Source:
http://bridge.grumpy-troll.org/2014/05/golang-tls-comodo/

**Comment by scrothers** [comment]
So, what was the fix here? Since nobody actually seemed to give any information, just close the ticket blankly. I'm experiencing the same issue here.

**Comment by jefferai** [comment]
It was fixed in code. You can run a version from master, or wait for the next release... both will solve the problem.
