### ISSUE TITLE
Vault write fails on 0.10.1 but succeeds on 0.9.3

### ISSUE THREAD

**Issue by raul1991** [hashicorp/vault#4486]
**Environment:**

* Vault Version: 0.10.1
* Operating System/Architecture: mac os / el caplan

**Vault Config File:**

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Startup Log Output:**

```text
# Paste your log output here
```

**Expected Behavior:**
SUCCESS/200

**Actual Behavior:**
NOT_FOUND/400

**Steps to Reproduce:**
1. Install vault
2. start vault -> vault server -dev
3. export VAULT_ADDR="http://127.0.0.1"
4. export VAULT_TOKEN=<TOKEN>
5. do a write to secret

`vault write secret/foo value=bar`

**Important Factoids:**

**References:**

**Comment by jefferai** [comment]
Dev servers start a v2 kv backend on 0.10+. Use 'vault kv' instead.

**Comment by raul1991** [comment]
Can you point where I can read more about it. I could not locate it.

**Comment by jefferai** [comment]
Sure, you can see version 1 and 2 docs at https://www.vaultproject.io/docs/secrets/kv/index.html
