### ISSUE TITLE
Unable to delete a transit key

### ISSUE THREAD

**Issue by Nicofuma** [hashicorp/vault#4490]
**Environment:**

* Vault Version: 0.10.0
* Operating System/Architecture: docker image vault:0.10.0

**Expected Behavior:**

It should be possible to delete a transit key.

**Actual Behavior:**

We have a 400 status code: 
```
URL: DELETE http://127.0.0.1:8201/v1/transit/keys/my-keys
Code: 400. Errors:

* error deleting policy my-keys: deletion is not allowed for this policy
```

**Steps to Reproduce:**

```
echo 'listener "tcp" {
  address = "0.0.0.0:8201"
  tls_disable = 1
}' > /tmp/vault-delete-transit.hcl

docker run -e VAULT_ADDR=http://127.0.0.1:8201 -v /tmp/vault-delete-transit.hcl:/tmp/vault-delete-transit.hcl -d --rm --name=vault-delete-transit vault:0.10.0 vault server -dev -dev-root-token-id=root -config=/tmp/vault-delete-transit.hcl
sleep 3
docker exec vault-delete-transit sh -c 'vault login root && vault secrets enable transit && vault write -f transit/keys/my-keys type=rsa-2048 && vault delete transit/keys/my-keys'
docker stop vault-delete-transit
```

**Comment by bruno** [comment]
As you can see in the [vault transit key API docs](https://www.vaultproject.io/api/secret/transit/index.html#delete-key) the `delete key` method states:

> Because this is a potentially catastrophic operation, the deletion_allowed tunable must be set in the key's /config endpoint.

by default, when you create a new key, you can't delete it immediately, first you need to update the `deletion_allowed` boolean, as [documented in the API docs](https://www.vaultproject.io/api/secret/transit/index.html#update-key-configuration) to permit it being deleted.

**Comment by Nicofuma** [comment]
indeed I missed it in the doc, thanks for your response.

Maybe it is possible to improve the documentation in order to give more visibility to this "warning", anyway I'll close this issue.

**Comment by jeffWelling** [comment]
Could I ask that this gotcha be noted on the Transit page as well as the API page, I just hit this same problem and Google lead me here. Thanks kindly!

https://www.vaultproject.io/docs/secrets/transit/index.html

**Comment by karvind007** [comment]
[Nicofuma](https://github.com/Nicofuma), were you able to set the deletion_allowed flag via cli? I can't do in my dev setup neither from cli nor from API.

The meta info is not changing at all

```bash
vault read transit/keys/cosign
Key                       Value
---                       -----
allow_plaintext_backup    false
auto_rotate_period        24h
deletion_allowed          false
derived                   false
exportable                true
keys                      map[1:1654688052]
latest_version            1
min_available_version     0
min_decryption_version    1
min_encryption_version    0
name                      cosign
supports_decryption       true
supports_derivation       true
supports_encryption       true
supports_signing          false
type                      aes256-gcm96

```
```bash
vault write -f  transit/keys/cosign deletion_allowed=true auto_rotate_period=48h
Success! Data written to: transit/keys/cosign
```
```bash
vault read transit/keys/cosign
Key                       Value
---                       -----
allow_plaintext_backup    false
auto_rotate_period        24h
deletion_allowed          false
derived                   false
exportable                true
keys                      map[1:1654688052]
latest_version            1
min_available_version     0
min_decryption_version    1
min_encryption_version    0
name                      cosign
supports_decryption       true
supports_derivation       true
supports_encryption       true
supports_signing          false
type                      aes256-gcm96

```

**Comment by kreisys** [comment]
Same issue. Can't change via cli, being forced into web-ui for this. Blocks my automation attempts.

**Comment by mitchellmaler** [comment]
For reference to update the configuration of an existing transit key you have to update it on its /config endpoint
example from above: `vault write  transit/keys/cosign/config deletion_allowed=true auto_rotate_period=48h`

Can read more about updating keys here in the API documentation: https://www.vaultproject.io/api-docs/secret/transit#update-key-configuration

**Comment by dayonet** [comment]
I had the same problem and was unable to change `deletion_allowed=true` from the CLI.
Changing it through the API directly worked:
`curl --header "X-Vault-Token: $VAULT_TOKEN" \
     --request POST \
     --data '{"deletion_allowed": true}' \
     $VAULT_ADDR/v1/transit/keys/<key-name>/config`
