### ISSUE TITLE
RFE for PKI in UI, store and display Common Name instead of just Serial

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/vault#4494]
**Feature Request:**

**Environment:**
* Vault Version: Vault v0.10.1+prem ('063c2bf570cbb7f903a567009cf34f9959d3f2c7')
* Operating System/Architecture: RHEL 7.4

**Expected Behavior:**
PKI certs generated by vault should display the common name, not the serialized ID

**Actual Behavior:**
PKI certs generated by vault display an ID. EX: 
21-68-6a-57-1a-0a-b3-e2-33-b0-cd-86-22-a7-06-fa-hg-66-1d-59

**Comment by jefferai** [comment]
Unlikely to happen, see https://groups.google.com/d/msgid/vault-tool/9e96e7f8-07b4-493f-8f6a-cad76681ca5b%40googlegroups.com?utm_medium=email&utm_source=footer
