### ISSUE TITLE
Support custom key usages in PKI

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#4500]
See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/k9Cxogg_Lg8/iy3j7Sn-AwAJ

**Comment by alexionescu** [comment]
FYI I will have a PR to implement this as far as the backend is concerned, once I get a bit more time I'll try and look at the frontend UI to see if I can tackle that part as well.

**Comment by jefferai** [comment]
Neat!

**Comment by jefferai** [comment]
Fixed by #4667
