### ISSUE TITLE
`vault secrets tune` should emit existing configuration

### ISSUE THREAD

**Issue by stevenschlansker** [hashicorp/vault#4507]
**Feature Request:** Currently, `vault secrets` supports `tune`ing an existing mount, but does not seem to have any capability to print the current configuration.

```
% vault secrets list
Path                   Type         Description
----                   ----         -----------
ci-sf/dbca/test-db/    pki          n/a

% vault secrets tune ci-sf/dbca/test-db
Success! Tuned the secrets engine at: ci-sf/dbca/test-db/
```

You have to make a magic incantation:
```
% vault read sys/mounts/ci-sf/dbca/test-db/tune  
Key                  Value
---                  -----
default_lease_ttl    2764800
force_no_cache       false
max_lease_ttl        2764800
```
This is documented, but it's far from obvious, and pretty bad UI.

I think `vault secrets tune` with no supplied tuning parameters should print the current tuning configuration.  Otherwise, there should be an additional verb such as `read-tuning` or `read-config` under `secrets` and probably all other mount types like `auth` too.  Thanks for considering.

**Comment by jwarnier** [comment]
Aren't you looking for the following?

> vault secrets list -detailed

**Comment by catsby** [comment]
Hello! I apologize for the delay in response here. I'm going to close this issue however, as it was pointed out that the `-detailed` flag will show this information. 

Thanks!
