### ISSUE TITLE
PKI Backend, `allow_any_name` Disallows Certain Characters?

### ISSUE THREAD

**Issue by theonewolf** [hashicorp/vault#451]
This policy option for PKI certificate issuing implies more than what the implementation delivers:

> `allow_any_name` optional If set, clients can request any CN.

Most notably, I can not have certain characters (trial-and-error right now) such as spaces or @ signs in my Common Name string.

What if we also want to issue certificates for people (converting them into the handy PKCS12 format)?  Are we supposed to use an entirely separate system from Vault?

For example, I might want to generate a certificate with the Common Name: 'Wolfgang Richter (wolf@cs.cmu.edu)'.

**Comment by theonewolf** [comment]
I think this check should be moved up before regex matching for hostname validation:

https://github.com/hashicorp/vault/blob/01592c0744b0eed613c3c940e295c61381a00e44/builtin/logical/pki/cert_util.go#L123

**Comment by theonewolf** [comment]
@armon I don't have time to make a pull request right now.  If you want me to I can.  Would new test cases need to be generated?

**Comment by armon** [comment]
@theonewolf Are those valid CN's in that case? I don't think those are valid. Paging @jefferai

**Comment by theonewolf** [comment]
By x509 standards you can put practically anything into a CN I think.  Need to check RFC to be sure (but this seems to imply almost anything can go: http://security.stackexchange.com/questions/40026/openssl-x509-whats-the-significance-of-cn-common-name).

For general servers/HTTPS we have the convention of putting something like a FQDN there.

My use case was personal certificates not just for machines (or for HTTPS where it does need to be a host name).

**Comment by jefferai** [comment]
I guess the docs are a bit too broad. The point is to allow any valid FQDN in the CN, since for server certificates this is what will be validated against the server's DNS host name, and for client certificates when performing TLS mutual auth you will often want the same (the client's DNS host name) in order to allow/deny. This is because the backend was created with machines in mind, as user certificates are generally going to be more long-lived, since the process of swapping out user certificates is often much more manual.

On the one hand, I can understand the point of simply allowing truly any valid (according to RFC) common name. On the other hand, I can't think of any use cases where you'd want this where Vault is the right solution in the first place, given its limits on lease lifetimes. So I'm going to punt this to both of you:

@theonewolf Can you describe the use-case you are thinking of, where Vault's limited lifetime certificates make sense for what appears to be user authentication? I realize you can keep generating new certificates but I've never encountered an organization that wanted user certificates to rotate that often due to the overhead of e.g. getting them into users' keychains and browsers. But perhaps that's just my own experience.

@armon Do you have any thoughts here (perhaps after @theonewolf explains his use-case)?

**Comment by kgutwin** [comment]
I can think of a use case: Docker mutual TLS authentication between users and a remote daemon or Swarm manager. The user certs are typically not stored in a keychain or browser but instead are in the user's home directory. Issuing a long-lived certificate to the user has risks if the certificate gets stolen or the user leaves and there is no way to revoke the certificate. Instead, a script could easily be written that:

* Authenticates to Vault as the named user (via LDAP, github, etc.)
* Issues a short-lived certificate (such as 12 hours) to the user
* Stores the certificates in the ~/.docker/certs directory

The 12 hour certificate lifetime means that the user is expected to re-authenticate to the system roughly once every working day. Given that everything is wrapped up in a script, this isn't too much burden on the user.

I am piloting a Docker Swarm configuration that does something similar, but using the Globus project's [MyProxy](http://grid.ncsa.illinois.edu/myproxy/) tool instead. I could imagine, though, if Vault acceptance takes off within our organization, we could switch to the configuration I mentioned above.

*For what it's worth, this use case doesn't actually require the common name to have any particular value, so this issue would not impede this use case. But I can imagine other applications, or changes to Docker Swarm's authentication framework, that would cause this issue to be relevant.*

**Comment by theonewolf** [comment]
@jefferai I completely agree with you on the lifetimes of _human_ certificates which identify a person as opposed to machine certificates which identify a machine.

But, even for machines, I might want something not quite FQDN-like for representing individual processes.  True x509 spec leaves the use cases wide open here to implement PKI for practically anything you want.

My use case is as described: I want a single solution to manage PKI for machines *and* humans.  Why have a "machine Vault" and a "human Vault"?

Humans are really machines with very different senses of time.  So we set long timeouts on their certs---but, of course, they do timeout (maybe on a yearly basis).

To some of your points:

> This is because the backend was created with machines in mind, as user certificates are generally going to be more long-lived, since the process of swapping out user certificates is often much more manual.

Yes, of course the user certificates will be more long-lived.

So does _Vault's_ certificate as well, because Vault does not support live reloading of TLS certificates.  You have to _unseal_ it if you refresh those certs.  So I've already set Vault's certificates to live for at least 1 year.

I don't know how HA works with Vault yet, so maybe downtime is avoidable with multiple Vault servers.  But unsealing is a huge pain, making me want to do this rarely (like roll Vault certificates once a year, or once every five years with the intermediate CA).

So we already have "classes" of machines or processes which work on longer time scales. I'm arguing for opening up the CN validation to allow for different namespaces other than machine hostnames.

> On the one hand, I can understand the point of simply allowing truly any valid (according to RFC) common name. On the other hand, I can't think of any use cases where you'd want this where Vault is the right solution in the first place, given its limits on lease lifetimes.

Vault doesn't restrict the lease lifetimes to a hard maximum.  I don't see why I can't issue user certificates, tracked by Vault, with timeouts on the order of 1 year.

Treat humans as just a special class of machine, with long timeouts, and a different CN-namespace.

In the end, I'm arguing for you to expand the business of Vault.  The suggestion of finding another solution for people certificates creates a bigger headache for me, and also takes away business from Vault :laughing:

**Comment by armon** [comment]
I'm not opposed to adding a flag that would allow an arbitrary CN, I now see that there may be some interesting use cases for having that. I think the FQDN validation is a sane default since the majority of cases will be an FQDN.

However, Vault does in fact enforce a maximum lease lifetime. By default it is 30 days, at which point it will issue a revoke. This is done on purpose to avoid clients who set a multi year lease period so that they can effectively treat the lease as infinite and break the leasing model. In fact, 30 days is almost too long and really should be shorter since clients can still almost treat it as infinite.

**Comment by theonewolf** [comment]
Oih.  I must have missed the 30 days hard coded limit.

This is from an x509 certificate issued by Vault:

```
        Validity
            Not Before: Jul 23 18:07:32 2015 GMT
            Not After : Jul 22 18:07:32 2016 GMT
```

So, even if you expire this in your Vault DB you're issuing certificates with validity time periods greater than 30 days.

And here's a PKI role I created which seems to imply a lease validity > 30 days:

```
vault read pki/roles/long-node
Key                     Value
allowed_base_domain     node
client_flag             true
code_signing_flag       false
key_bits                2048
key_type                rsa
lease                   8760h
allow_any_name          false
allow_token_displayname false
lease_max               8760h
allow_subdomains        true
server_flag             true
allow_ip_sans           true
allow_localhost         true
```

**Comment by theonewolf** [comment]
Oh I see, you'll revoke the cert and add it to the CRL.  Then I think this role should not have been creatable in the first place.

**Comment by armon** [comment]
Yeah we probably should verify that we never give issue a certificate with validity longer longer than `MaxLeaseDuration`, otherwise the Vault revocation will bite it down the line.

**Comment by theonewolf** [comment]
So this is a Vault internal not exposed to operators?  My search of the source seems like it is.

**Comment by armon** [comment]
It's not a tunable knob currently. It's just hard coded to 30 days.

**Comment by theonewolf** [comment]
Should I file a separate issue for that?  I really think that should be tunable by the organization/group deploying Vault.

This might also make my Vault need unsealing every 30 days :cry: because I was trying to use Vault to manage its own certificates (like a compiler compiling itself).  That would make Vault almost unusable for us.

**Comment by armon** [comment]
@theonewolf I think there is an open issue for it. I don't see why it affects unsealing the Vault itself? This is just the lease duration for secrets it provides.

**Comment by theonewolf** [comment]
If I wanted Vault to manage its own certificate, and it revokes its own cert every 30 days, then I need to refresh that, restart Vault, and unseal it?

I really want Vault to manage almost every certificate possible :smile: except for my Root CA!

**Comment by armon** [comment]
Oh interesting... Managing its own certificate is odd. I wonder how that could work...

**Comment by jefferai** [comment]
The historical reason for it allowing beyond MaxLeaseTime is that originally the idea was to allow Vault to issue intermediate CAs and those might want to be valid for longer.

However at this point there are various workflows identified that avoid the problematic intermediate CA generation, so at this point honoring MaxLeaseTime is a bug. However. What will likely happen instead is that the backend will ignore MaxLeaseTime *if* the operation is a CSR signing request *and* it is requested to have the IsCA flag set.

The 30 day limit is why I was mentioning earlier that it would probably be onerous for user certs; however I agree with Armon that a separate tunable to allow non FQDNs might be a good way forward. Coupled with a theoretical way to tune the MaxLeaseTime (at least without a custom build) will make this be more useful for user auth certs as opposed to just machine to machine auth.

If there is consensus to simply allow this particular backend to continue to ignore MaxLeaseTime (which I'm not against, considering the many use cases for automatically generated but longer lived certificates), then that's fine too: but the warnings in the documentation about CRL sizes should be heeded, and if you run into issues as a result there may not be support for it.

**Comment by jefferai** [comment]
*...so at this point _not_ honoring MaxLeaseTime is probably a bug
Sorry, phone keyboard :-)

**Comment by theonewolf** [comment]
@armon shouldn't it be able to work?  Like a compiler compiling itself :wink:.  It's just another TLS server talking machine-to-machine for the most part.

The point of Vault to me is to minimize my special casing surrounding certificates.  Therefore, I want Vault to manage its own TLS certificates and human certificates.  I just keep the root out of Vault's reach as a final control.

@jefferai yeah, a non-FQDN flag on a PKI role (or change how `allow_any_name` is implemented) coupled with tunable `MaxLeaseDuration` really widens the use cases for PKI-based stuff.

**Comment by theonewolf** [comment]
@armon also, by "manage its own certificate" I didn't mean Vault literally has that functionality built coded in.  I'm using external scripts to rotate my Vault server certificates, but I'd like that rotate timeline to be on the order of a year and not 30 days (12 unsealing events even if planned is painful).

**Comment by databus23** [comment]
I just started to look into vault as pki solution and the upper limit of 30 days for certificates seems impractical to me for anything but short lived client processes making tis connections.
As most server (or long running client) software does not support on the fly reloading of tls configuration this means I need to restart all components monthly to roll all certificates.

One of my use case also involves mobile clients that might be offline for more than a month so by the time they come back online its current certificate might already be revoked and couldn't be used as a source of authentication for issuing a new certificate for the client.

I'm a missing something here? How is this supposed to be used?

**Comment by armon** [comment]
@databus23 I think this should be a conversation for another ticket, moving to #470

**Comment by theonewolf** [comment]
@armon, @jefferai 

You guys still think that a separate flag is needed to truly allow "any" CN?

Or should we just make the documentation true:

> `allow_any_name` optional If set, clients can request any CN.

I guess your worry is legacy which expects FQDN checking even with this option set?

**Comment by armon** [comment]
I think maybe we could split to `allow_any_fqdn` and `allow_any_name` to help clarify the distinction. I think most cases should be guarding on FQDN sanity.

**Comment by jefferai** [comment]
A few updates, although no promises on timeline:

1) We will split into either `allow_any_fqdn` and `allow_any_name`, or, simply have `allow_any_name` and a separate `enforce_fqdn` boolean. They work out to the same end, but the latter allows us to do some interesting things; for instance, whether `allow_token_displayname` is limited to FQDNs or not can be managed by that flag.

2) This was somewhat of a diversion from the original post, but FYI: there is now a global tunable for max lease time (see #469). There will be an update to this backend (#470) to have this backend follow that configured max lease time as an upper limit. Eventually all backends will be able to be locally configured with a max lease time.

**Comment by theonewolf** [comment]
Thanks to both of your @jefferai and @armon.  If I had more time right now I would have probably coded this actually into a pull request for you guys.
