### ISSUE TITLE
Missing font on vaultproject.io

### ISSUE THREAD

**Issue by kolorafa** [hashicorp/vault#4510]
https://www.vaultproject.io/intro/getting-started/install.html

font-family: "Fira Mono", monospace;
OS: Arch
Firefox 59

![screenshot-2018-5-4 install vault - getting started - vault by hashicorp](https://user-images.githubusercontent.com/921517/39620614-0e7b259a-4f8c-11e8-8bfe-aff34e3bdaba.png)

It would be nice to add third default font just in case :)

**Comment by jescalan** [comment]
Hey there @kolorafa -- so this is a tough issue -- `monospace` is a default fallback that all systems are able to render. Additionally, if none of the font fallbacks specified in the CSS are found, the browser will render it as the default font in the browser - under no circumstance will empty space be rendered.

This in addition to the fact that [the font stack has been this way for more than a year](https://github.com/hashicorp/vault/commit/43923bc7851f52121927c8f8cf3948fee0e4f0d8) and this is the first time we have seen this issue leads me to believe that there's something weird going on with your specific setup. My suspicion is that you do actually have `Fira Mono` installed, but something went wrong with the installation such that it is rendering empty characters for everything.

Could you do me a favor and test out this theory to see if it holds any water? You can do this quickly by heading over to [MDN's font-family docs](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family), where they have an interactive CSS rendering section at the top. If you change the font stack to just `monospace`, I'm expecting that you will get the text to render correctly. But if it's changed to `Fira Mono`, I'm guessing you will see blank space. If this is the case, uninstalling your local copy of `Fira Mono` should resolve this issue. If not, let me know how it looked, and we can investigate further.

**Quick Demo:**

![](https://cl.ly/rQIO/Screen%20Recording%202018-05-07%20at%2001.09%20PM.gif)
