### ISSUE TITLE
kv V2 issue - Backward compatibility in policies

### ISSUE THREAD

**Issue by manikawnth** [hashicorp/vault#4516]
Due to kv v2, all the policies now need to be updated to add **data** in the path.
path `secret/foo` now becomes `secret/data/foo` .

Is there any way that is taken care of automatically as appending the data is not quite transparent to the operator, as all the kv operations like `put` do not need to append the data in their path while issuing from  the api.

**Comment by jefferai** [comment]
There is not, sorry.
