### ISSUE TITLE
TLS Certificate Refresh: Is it Possible without Restarting Vault?

### ISSUE THREAD

**Issue by theonewolf** [hashicorp/vault#452]
How do we refresh Vault state when we want to rotate TLS certificates for its HTTPS endpoint?

SIGHUP (kill -1) appears to take down the entire Vault!

**Comment by sethvargo** [comment]
Looks like a duplicate of https://github.com/hashicorp/vault/issues/415. What do you think @theonewolf ?

**Comment by theonewolf** [comment]
Yes duplicate. Closing.
