### ISSUE TITLE
Vault Guides documentation link correction?

### ISSUE THREAD

**Issue by boldandbusted** [hashicorp/vault#4535]
On https://www.hashicorp.com/resources/approle-pull-authentication-vault, the last section has a "Next" link section that refers to the currently loaded page, not the next page. :)

> Next steps
> 
> In this guide, you learned how to write policies based on given policy requirements. Next, AppRole Pull Authentication guide demonstrates how to associate policies to a role.

I tried to send this problem report to support@hashicorp.com, but was rebuffed, and told to report to the community resources. Cheers.

**Comment by boldandbusted** [comment]
P.S. I also tried to report in #vault-tool on Freenode, but there's no one from Hashicorp active there.

**Comment by jefferai** [comment]
I've escalated internally, thanks!
