### ISSUE TITLE
Question: Can we have a `@file` path in vault configuration?

### ISSUE THREAD

**Issue by krish7919** [hashicorp/vault#4541]
Can we have a vault configuration with an `@/path/to/file` and expect vault server to read a local file?

I am trying to use terraform to configure vault to read a certificate file on the server?

This method will avoid the maintenance for the users to copy the same certificate locally and maintain it in version control.

**Comment by jefferai** [comment]
Which configuration file are you talking about? Vault's configuration already reads from files when appropriate.

**Comment by krish7919** [comment]
Assume a situation where I run a command like:

```
vault write auth/kubernetes/config \
    kubernetes_host="https://api.kubernetes.com:443" \
    kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
    token_reviewer_jwt="XXXX"
```

This CLI/API client would read and add the data from the file to the vault server.

But if I want to include a file which is already present on the server, the above configuration would not work. In such cases, we want the client to forward the `@/path/to/file` to the server and to have the server read its local file.

This is something I hit when I used the `terraform-provider-vault` which tries to read the certificate file locally, whereas the cert is already present on the server.

**Comment by jefferai** [comment]
I don't think we'll ever support this. It's generally not a great idea for a client to be able to specify arbitrary files for the server to load and parse. Instead the client should provide it. Sorry!
