### ISSUE TITLE
Commands for KV version 2 not working

### ISSUE THREAD

**Issue by seandilda** [hashicorp/vault#4542]
**Environment:**

* Vault Version:  Vault v0.10.1 ('756fdc4587350daf1c65b93647b2cc31a6f119cd')
* Operating System/Architecture Client:  Fedora 27 / x86_64
* Operating System/Architecture Server:  CentOS 7 / x86_64

**Vault Config File:**

```hcl
ui = true
disable_mlock=false
cluster_name="automation"
storage "consul" {
  address = "127.0.0.1:8500"
  token   = "redacted_token"
  path    = "vault/"
  service = "vault"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/vault/config/vault.crt"
  tls_key_file  = "/vault/config/vault.key"
}

telemetry {
  statsite_address = "telemetry-addy:8125"
}

default_lease_ttl = "24h"
max_lease_ttl = "768h"
```

**Expected Behavior:**

I expect commands to work as documented on https://www.vaultproject.io/docs/secrets/kv/kv-v2.html
ie:

```
$ vault kv put secret/my-secret my-value=s3cr3t
Key              Value
---              -----
created_time     2018-03-30T22:11:48.589157362Z
deletion_time    n/a
destroyed        false
version          1
```

**Actual Behavior:**

```
$ ./vault kv put secret/my-secret my-value=s3cr3t
Error writing data to secret/my-secret: Error making API request.

URL: PUT https://XXX/v1/secret/my-secret
Code: 404. Errors:


WARNING! The following warnings were returned from Vault:

  * Invalid path for a versioned K/V secrets engine. See the API docs for the
  appropriate API endpoints to use. If using the Vault CLI, use 'vault kv put'
  for this operation.

$ 
```

**Important Factoids:**

The secrets engine was upgraded from kv1 to kv2

```
$ ./vault read sys/mounts | grep ^secret
secret/               map[seal_wrap:false type:kv accessor:kv_106640ba config:map[default_lease_ttl:0 force_no_cache:false max_lease_ttl:0 plugin_name:] description:key/value secret storage local:false options:map[version:2]]
$ 
```

When creating data with the API, I find the vault command will read the data if I put ```/data``` in the path, however I am have trouble getting the other specified commands to work, even with modifying the paths.

**Comment by seandilda** [comment]
I downgraded my client to 0.10.0 and the documented commands started working.

**Comment by jefferai** [comment]
Both your server and CLI need to be 0.10.1 due to some changes. My guess is your client was 0.10.1 but server was 0.10.0.

**Comment by seandilda** [comment]
@jefferai,   good call.  I was using a 0.10.1 client against server 0.10.0.

Since the 0.10.1 client doesn't work against 0.10.0, does this mean there were changes to the KV version 2 API between 0.10.0 and 0.10.1 ?

**Comment by jefferai** [comment]
No API changes to the KV mounts, no, however, the logic that helps the `vault kv` command figure out whether it's talking to a v1/v2 mount did change, and in a way that is not backwards compatible.

**Comment by seandilda** [comment]
Thanks for the clarification.
