### ISSUE TITLE
Question: Can we implement a `PATCH` method?

### ISSUE THREAD

**Issue by WingT** [hashicorp/vault#4543]
vault 0.10.1 CLI provides a kv patch utility, however, this logic is implemented on client side, what if user doesn't have permission to read but he has to update kv?

**Comment by jefferai** [comment]
Then you can't use `kv patch`, sorry.

**Comment by atomd** [comment]
Implementing patch on the client side is not very reliable and convincing.

**Comment by jefferai** [comment]
It is quite reliable due to check-and-set. But, this question has been discussed quite a lot before and the answer won't change. See https://github.com/hashicorp/vault/issues/182#issuecomment-383400854
