### ISSUE TITLE
ACL for Single Token Renewal?

### ISSUE THREAD

**Issue by theonewolf** [hashicorp/vault#455]
I can't figure out a way of expressing via the HCL for my policies a nice method of allowing renewal of _only_ my token.  In order to renew I seem to need to grant `*`, which doesn't seem like the right thing to do:

```
path "auth/token/renew/*" {
    policy = "write"
}
```

Without the `*` I can't renew my own token.  I also don't want to specify the token in the HCL or have a per-token policy defined.

**Comment by armon** [comment]
@theonewolf I don't think there is a good way to express that with the current endpoint. I think we need a new endpoint that is `auth/token/renew-self` similar to `lookup-self`

**Comment by theonewolf** [comment]
Agreed, this would be great for security purposes.   I know that it's unlikely for tokens to be "guessed," but I still like knowing that a token can only renew itself.  It feels  "right" bounding it that way.
