### ISSUE TITLE
MySQL root rotation uses wrong syntax for MySQL 5.6

### ISSUE THREAD

**Issue by rwiggins** [hashicorp/vault#4567]
The SQL used to change the current user's password is only valid in MySQL 5.7+, not including 5.6 (which is not EOL yet—supported until Feb 2021). 

Current SQL used: https://github.com/hashicorp/vault/blob/f23b14a8c2010a42fabbf965d9e4db0f77ab3aef/plugins/database/mysql/mysql.go#L28

Compare [ALTER USER syntax for 5.6](https://github.com/hashicorp/vault/blob/f23b14a8c2010a42fabbf965d9e4db0f77ab3aef/plugins/database/mysql/mysql.go#L28) with [ALTER USER syntax for 5.7](https://dev.mysql.com/doc/refman/5.7/en/alter-user.html). (In 5.6, it's only used to expire passwords.)

Unfortunately, passwords are messy across MySQL versions, at least from my understanding:

- [5.6's SET PASSWORD syntax](https://dev.mysql.com/doc/refman/5.6/en/set-password.html) wants you to either explicitly use `PASSWORD()` (to let the MySQL server hash it) _or_ provide an already-hashed password if not using `PASSWORD()`
- [5.7's SET PASSWORD syntax](https://dev.mysql.com/doc/refman/5.7/en/set-password.html) takes a non-hashed password in either case and hashes it itself, deprecates the `PASSWORD()` syntax, and recommends the `ALTER USER` syntax currently in use
- [8.0's SET PASSWORD syntax](https://dev.mysql.com/doc/refman/8.0/en/set-password.html) does not have the `PASSWORD()` syntax at all anymore and recommends the `ALTER USER` syntax

I see there's a "MySQL legacy" plugin in the tree, so maybe that could be extended to use `SET PASSWORD = PASSWORD(...)` instead of `ALTER USER` while keeping `ALTER USER` for 5.7/8.0+?

* Vault Version: v0.10.1 ('756fdc4587350daf1c65b93647b2cc31a6f119cd')
* Operating System/Architecture: Ubuntu 18.04

**Expected Behavior:**

When making the [rotate root credentials API call](https://www.vaultproject.io/api/secret/databases/index.html#rotate-root-credentials), the root credentials will be rotated (and the server will respond with a 204). Alternately, if we're not willing to support 5.6 root rotation, it'd be nice to have a note in the docs to that effect.

**Actual Behavior:**

The server responds with a 500 returning the error

```
* Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'A1a-39st67z4s3ytw602'' at line 1
```

**Steps to Reproduce:**

Set up the MySQL database plugin pointing to a MySQL 5.6 database, then make the rotate root credentials call:

```
vault write -force database/rotate-root/my-database
```

**Important Factoids:**

I'm using the "mysql-aurora-database-plugin" option.

**Comment by jefferai** [comment]
We provide defaults based on, mostly, the latest supported versions, but you can actually specify your own rotation statements -- see https://www.vaultproject.io/api/secret/databases/index.html#root_rotation_statements

**Comment by rwiggins** [comment]
Thanks! I don't know how I missed that. I submitted a PR adding a note to the docs.
