### ISSUE TITLE
Deletion of secret's after lease time

### ISSUE THREAD

**Issue by vikas17a** [hashicorp/vault#457]
Even after lease time i was able to read the data from secret back-end. I don't know if this should happen ideally or not, but if not then what lease_duration is meant for i.e If consumer is still able to read the data from secret back-end after the lease duration what is the role of lease here? Is there a feature to delete the secret after a particular expiration time set for it or to disable consumer access from the secret after lease_duration.

**Comment by armon** [comment]
@vikas17a The lease time controls the validity of the data returned to the client, not the time-to-live of the data itself. The data does not expire, but the client should only continue to depend on it's value for the lease duration.

As an example:
1) Set secret/mysql = {user: foo, password: bar, lease: 1h}
2) Client reads secret/mysql at time t0, lease expires at t3600
3) Set secret/mysql = {user: baz, password: zi, lease: 1h} at time t1800
4) At time t1800+3600 we know that all clients (if they are well behaved) have read the updated value, so we can now do a "DROP USER 'foo'".

The explicit lease behavior gives operators an assurance that they can safely do key rolling or updating of credentials in a timely manner. It is not used to control the lifespan of a secret itself.

**Comment by vikas17a** [comment]
@armon thanks for replying. Is there any other backend in vault which supports time-to-live kind of behavior for secrets stored in vault ?

**Comment by armon** [comment]
@vikas17a There isn't any that support that behavior currently

**Comment by vikas17a** [comment]
@armon  Is there a way i can associate a user name with each token i generate ?

**Comment by armon** [comment]
Yep, it's a "display name". Take a look at the docs.

**Comment by sethvargo** [comment]
Hi there,

I'm going to close this since it looks like everything has been answered. If you have further questions, please feel free to ask here or open another issue. Thanks! :smile:

**Comment by gudlyf** [comment]
Sorry to be dense on this, but what would be an example of automating deletion of users once it's been determined that it's no longer needed? It's easy to see how to setup the command for user creation (as with the examples), but how to match the created user to one that should be deleted after lease-time is expired (or +t3600)?

**Comment by jefferai** [comment]
@gudlyf Backends can store information internally in Vault (as in, not returned to the user) that is returned to them during a revoke or renew action. So a backend creating a user and tying it to a lease can look up which user was created as part of the revocation process.
