### ISSUE TITLE
Trying to set RabbitMQ role fails with `failed to unmarshal vhosts` on windows

### ISSUE THREAD

**Issue by pvandervelde** [hashicorp/vault#4574]
**Environment:**
* Vault Version: Vault v0.10.1 ('756fdc4587350daf1c65b93647b2cc31a6f119cd')
* Operating System/Architecture: Windows 10 x64

**Command line:**
Executing the following command line from the CMD window:

    vault.exe write -address=http://172.17.35.46:8200 -tls-skip-verify rabbitmq/roles/configure.vhost.testmessages vhosts='{"vhost.testmessages":{"configure":".*"}}'

**Expected Behavior:**
I expected vault to write the rabbitmq role. The same command works from a Linux box but not from a windows box.

The output from the same command on a linux box:

    Success! Data written to: rabbitmq/roles/configure.vhost.testmessages

**Actual Behavior:**
The command returns the following result:

    Error writing data to rabbitmq/roles/configure.vhost.testmessages: Error making API request.

    URL: PUT http://172.17.35.46:8200/v1/rabbitmq/roles/configure.vhost.testmessages
    Code: 400. Errors:

    * failed to unmarshal vhosts: invalid character '\'' looking for beginning of value

The failure occurs both from a CMD command line and a powershell command line.

**Steps to Reproduce:**
* Configure a Vault instance
* Configure a RabbitMQ instance
* Follow the [instructions](https://www.vaultproject.io/docs/secrets/rabbitmq/index.html) to configure Vault so that it can create credentials for RabbitMQ
* Execute the above command from a windows box

**Comment by jefferai** [comment]
You need to properly escape for each shell. For PowerShell the following works: 

`rabbitmq/roles/configure.vhost.testmessages vhosts='{\"vhost.testmessages\":{\"configure\":\".*\"}}'`

Alternately you scan specify pure JSON which should work the same on each platform.

**Comment by pvandervelde** [comment]
Doh my bad
