### ISSUE TITLE
[Feature Request] Support HA for S3 and Azure storage backends

### ISSUE THREAD

**Issue by tamalsaha** [hashicorp/vault#4576]
We would like to use S3 and Azure storage backends in HA mode like it is supported for GCS here: https://github.com/hashicorp/vault/pull/4226 .

Thanks.

**Comment by jefferai** [comment]
You'd need appropriate primitives to build locks; GCS has those, I don't believe S3 does, I'm not sure about Azure. We don't maintain those so I'm going to close this -- such support would need to come from a community PR.
