### ISSUE TITLE
Allow vault client to call a server mounted on a sub resource URI

### ISSUE THREAD

**Issue by tdi** [hashicorp/vault#458]
This is a wishlist issue. 

I would like to mount my vault HTTP API in a sub resource using HTTP proxy like nginx. 
e.g. `https://$VAULT_ADDR/vault/` instead  `https://$VAULT_ADDR/`. 
Setting `VAULT_ADDR=https://example.com/vault` does not work, the client call `https://example.com/` anyway. 

Please add $VAULT_PREFIX or similar option to allow to call full URI address of a vault server.

**Comment by armon** [comment]
Marked as enhancement

**Comment by ntmggr** [comment]
+1

**Comment by jefferai** [comment]
No plans to add this, but the CLI is simply an HTTP client so you can easily use e.g. curl.
