### ISSUE TITLE
Strip forward slashes in "create secret" form

### ISSUE THREAD

**Issue by lrstanley** [hashicorp/vault#4581]
**Environment:**
* Vault Version: Vault v0.10.1 ('756fdc4587350daf1c65b93647b2cc31a6f119cd')
* Operating System/Architecture: linux/64

**Expected Behavior:**
In the UI, after clicking on a mount, clicking "Create secret", and entering the following:
![](https://i.imgur.com/gSYWdsw.png)

And hitting "Save", it should save the KV under "/secrets/test/abc".

**Actual Behavior:**
Hitting save, nothing happens. This is due to the forward slash in the path (the end result in this case would be `/secrets/test/abc`). The UI expects me to enter only `test/abc` but this is not clear. In addition, there was no visual error message or similar telling me the API threw a 404 (this happened via the console).

JS makes the following request:
```
POST https://vault.myhost.com:8200/v1/secrets//test/abc
```

Which throws a 301, and redirects to the following, which 404's:
```
https://vault.myhost.com:8200/v1/secrets/test/abc
```

It's also worth noting that "/secrets/test" doesn't already exist. Only the mount "/secrets".

Solution would likely be to strip any forward slashes at the front of the path form value. Also potentially ensure that even for things like 404's or similar errors, that there is a visual identifier telling me it failed.

**Comment by meirish** [comment]
Hi @lrstanley !  I was unable to recreate this locally - when posting to `//secrets/test/abc`, the Vault server 200s, and then we can read the secret back out - this leads to a minor glitch in the UI (so we will strip the leading slash) where you have an empty breadcrumb, but the result is still values persisted at `/secrets/tests/abc`. I'm wondering if there's something else in your infrastructure that's causing the 301 before getting to the vault server. Any chance you could take a look? Thanks!

**Comment by lrstanley** [comment]
I see you mentioned `//secrets/test/abc`, not `/secrets//test/abc` like I mentioned in my issue (which is what the UI does), even before the redirect occurs. If the steps are followed specifically in the UI, you should see where it keeps the specified `/`, and propagates it to the request.

For the sake of clarity anyway, this is the direct request, to replicate what the browser does:

```
$ curl -i -k \
    -H "X-Vault-Token: <truncated>" \
    -H "Content-Type: application/json" \
    -X POST -d '{"value":"bar"}' https://myhost.com:8200/v1/secrets//test/abc

HTTP/1.1 301 Moved Permanently
Cache-Control: no-store
Location: /v1/secrets/test/abc           <-- notice this.
Date: Tue, 29 May 2018 14:53:19 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

There is no medium (proxy, firewall, etc) between this request and Vault.

It's also worth noting that it doesn't write it to Vault either, because POST data isn't re-sent between 301/302 redirects.

**Comment by meirish** [comment]
Sorry that was a typo on my part, I'm inputting via the UI just as you were. Also ironically it was a networking setup on my end that lead to what I was seeing - sorry about that! (in dev we run a server that proxies back to the vault api so that we can rebuild the UI without having to bundle it in the binary). We'll try to get this in soon!
