### ISSUE TITLE
Documentation auth/aws: resolve_aws_unique_id does not default to false

### ISSUE THREAD

**Issue by AgentZombie** [hashicorp/vault#4583]
* Vault Version: 0.9.5+prem.hsm
* Operating System/Architecture: Linux AMD64

**Expected Behavior:**
Sending a role creation for an IAM role that does not exist without specifying `resolve_aws_unique_ids` should succeed because the documentation indicates that the default for that value is `false`.

**Actual Behavior:**
It fails trying to resolve the ID.

**Important Factoids:**
https://www.vaultproject.io/api/auth/aws/index.html#resolve_aws_unique_ids

disagrees with:

https://github.com/hashicorp/vault/blob/e2bb2ec3b93a242a167f763684f93df867bb253d/builtin/credential/aws/path_role.go#L85

**Comment by jefferai** [comment]
As the docs indicate it's false for existing roles but true for new ones -- but it's confusing. I'll change the docs.
