### ISSUE TITLE
[S3] Default Bucket Encryption (KMS)

### ISSUE THREAD

**Issue by mikeblum** [hashicorp/vault#4591]
Enabling default S3 bucket encryption appears to break the `S3` backend.

**Environment:**

* Vault Version: Vault v0.10.1 ('756fdc4587350daf1c65b93647b2cc31a6f119cd')
* Operating System/Architecture: Ubuntu 16.04

**Vault Config File:**

```hcl
storage "s3" {
  access_key = "******"
  secret_key = "******"
  bucket     = "bucket"
  region     = "us-west-2"
}
```

**Startup Log Output:**

```text
2018-05-18T12:50:47.369-0500 [INFO ] core: seal configuration missing, not initialized
2018-05-18T12:50:47.451-0500 [INFO ] core: security barrier not initialized
```

**Expected Behavior:**
`vault operator init` should correctly initialize a vault using the S3 backend.

**Actual Behavior:**
```
Error initializing: Error making API request.

URL: PUT http://localhost:8200/v1/sys/init
Code: 400. Errors:

* failed to initialize barrier: failed to persist keyring: AccessDenied: Access Denied
	status code: 403, request id: 420CCB5D91CED2F9, host id: VTdTk5anihXcX2jh2QFph725s0MDYxRl3VD6ymbrVz4K2A9Fm2ROgxwRYqrmzoWlKXzVuSR1PK4=
```

**Steps to Reproduce:**
1. Create an S3 bucket with default KMS encryption
2. Start vault server 
3. `vault operator init`

Removing the KMS encryption from the S3 bucket results in the correct output without error (unseal keys and root token).

**Important Factoids:**
1. Ensure that the KMS key is in the same region as the bucket
2. Ensure the AWS credentials used have read/write access to the bucket

**References:**

[Issue #2673](https://github.com/hashicorp/vault/issues/2673)

**Comment by mikeblum** [comment]
I read that KMS authentication is only available for Vault Enterprise. Is this issue between community vs enterprise?

**Comment by chrishoffman** [comment]
It looks like this is a permission issue on the AWS side since you are receiving an AWS error.  I believe your AWS access key needs to not only perform S3 operation but also have access to the KMS key.

The enterprise offering of Vault provides additional features such as auto-unseal and seal wrapping.  S3 bucket encryption is transparent to how Vault interacts with S3.

**Comment by mikeblum** [comment]
Thanks @chrishoffman - the issue was I had the vault role assigned to the KMS key and not the vault user. Apparently KMS keys don't transitively look at a user's roles and it has to be explicitly declared.
