### ISSUE TITLE
Document the KV2 Mount API for creation

### ISSUE THREAD

**Issue by mikebell90** [hashicorp/vault#4601]
As far as I can see there's no where it's specifically said how to create a kv2 mount EXCEPT with cli.

I found the magic recipe was to add a separate map called options (not config) to sys/mounts POST

```
{
	"type" : "kv",
	"options" : {
		"version" : 2
	}	
}
```

is a simple example.

**Comment by mikebell90** [comment]
https://www.vaultproject.io/api/system/mounts.html doesn't list the options dictionary nor the value.

**Comment by maciejqantas** [comment]
@chrishoffman on https://www.vaultproject.io/api/system/mounts.html#options, `options` is nested under `config`, making it look like `options` is a key in the `config` map, whereas it's a separate fields, as we can see here: https://github.com/hashicorp/vault/blob/master/api/sys_mounts.go#L137.

That does lead to confusion - Vault creates V1 mountpoints and silently ignores the `options` field of `config`.

Can we reuse this issue or should a new one be created?
