### ISSUE TITLE
Nomad secret backend ignores role's TTL settings when constructing lease config

### ISSUE THREAD

**Issue by ole-lukoe** [hashicorp/vault#4613]
**Describe the bug**
Nomad Secret Backend HTTP API documentation in Create/Update Role endpoint description says there is a "lease" parameter allowed.
But as I can see in sources, "pathRoles" backend method doesn't contain "lease" field.

Is this a feature or a bug?

**Comment by chrishoffman** [comment]
This was just some incorrect documentation which I fixed with https://github.com/hashicorp/vault/commit/c42adad873d7a57d9ddb8e58f3c2cc3b4f204969.  You can configure the ttl for the leases with the `config/lease` endpoint.
