### ISSUE TITLE
An error occurred while writing a role to mongodb via vailt-cli

### ISSUE THREAD

**Issue by sadpirit** [hashicorp/vault#4615]
**Describe the bug**
Attempting to write a role mongodb via vault-cli
```
vault write mongodb/roles/readonly db=foo roles='[ "readWrite", { "role": "read", "db": "bar" } ]'
Failed to parse K=V data: invalid key/value pair "\"readWrite\",": format must be key=value
```

**To Reproduce**
Use the documentation https://www.vaultproject.io/docs/secrets/mongodb/index.html
1. `vault secrets enable mongodb`
2. `vault write mongodb/config/connection uri="mongodb://admin:Password!@mongodb.acme.com:27017/admin?ssl=true"` (you need to use a real database and password
 )
3. `vault write mongodb/roles/readonly db=foo roles='[ "readWrite", { "role": "read", "db": "bar" } ]'`
3. See error `Failed to parse K=V data: invalid key/value pair "\"readWrite\",": format must be key=value
`

**Environment:**
* Vault Server Version : 0.10.0
* Vault CLI Version : 0.10.1 (x64 ubuntu 16.04 lts)

**Comment by chrishoffman** [comment]
You cannot use policy HCL for your roles and must create a database backend role that specifies policies.  Additionally, the mongodb backend is now deprecated and the combined database backend should be used with mongodb.  

See https://www.vaultproject.io/docs/secrets/databases/index.html and https://www.vaultproject.io/guides/secret-mgmt/dynamic-secrets.html.
