### ISSUE TITLE
Getting Error when starting vault server

### ISSUE THREAD

**Issue by nkv16786** [hashicorp/vault#4616]
I want to disable by default sealing process . Here is my configuration file,

```
disable_sealwrap = true
storage "file" {
  path = "/tmp"
}

listener "tcp" {
 address     = "xx.xx.xx.xx:8200"
 tls_disable = 1
}
```

But i am getting the following error:-

$ vault server --config=/home/devuser/config.hcl
**invalid key 'disable_sealwrap'**

vault version :- Vault v0.10.1

**Comment by chrishoffman** [comment]
The unseal process is required to reconstruct the master key for encryption/decryption operations. See https://www.vaultproject.io/docs/concepts/seal.html.  Seal Wrap and Auth Unseal are Enterprise features and only available in the enterprise version of Vault.
