### ISSUE TITLE
Vault Users Have No CI Testing Visibility

### ISSUE THREAD

**Issue by compensator** [hashicorp/vault#462]
As potential users of the Vault product for critical security capabilities, we would like to have visibility into the quality of the product by seeing the level of code coverage and test metrics.

**Comment by armon** [comment]
We run the tests automatically on Travis here: https://travis-ci.org/hashicorp/vault
We don't publish code coverage, and I'm not a believer that they really expose much of interest. We have a very thorough testing process, and we use external security auditors as well.

**Comment by compensator** [comment]
I work on a contract for a customer who is very interested in the code coverage level as a measure of the quality of open source products, so having that insight might help your cause.  Without that insight, the customer may as well select a proprietary product and blackbox it.

**Comment by compensator** [comment]
Wow.  Okay.

**Comment by jsok** [comment]
Go has some decent coverage tooling as part of the buildchain. @compensator maybe you could work on a PR to add the necessary `go cover` steps to the Travis job?

**Comment by compensator** [comment]
We are merely in product evaluation phase for a customer.  I would only get involved if the product were selected as the final solution.

**Comment by armon** [comment]
@compensator Sorry, we unfortunately have a limited team and look after many different products which means we have to prioritize work aggressively. If the only evaluation criteria between the proprietary solution and Vault is code coverage, that is a metric that can be easily gamed and likely we'd lose as we do not focus on optimizing it, in favor of other things.

**Comment by benzenwen** [comment]
@compensator Can you email me ben at hashicorp dot com? Happy to help with your final product selection criteria.  Thank you!

**Comment by compensator** [comment]
Sure.

**Comment by compensator** [comment]
@armon Thanks for providing feedback.  It is not the only evaluation criteria.  It is merely one that this particular customer emphasizes.  We can examine the test code and the continuous integration server for execution on open source products in many cases.  It doesn't mean that the product is eliminated from consideration by the customer.  It merely adjusts the risk matrix in the evaluation.

Thanks, again for responding.  I like where your product is headed.
