### ISSUE TITLE
SHA256SUMS file should be linked from https://vaultproject.io/docs/install/index.html

### ISSUE THREAD

**Issue by oskarpearson** [hashicorp/vault#463]
Hi

Further to https://github.com/hashicorp/vault/issues/152 - the https://vaultproject.io/docs/install/index.html page says that SHA256 sums are supplied, but no links are provided on the page. The download link is a cloudfront link, which means guessing the SHA256 sum and PGP files are problematic.

IMHO, the install page should be updated to include the steps required for verification of the binary, as well as how to validate the PGP key.

Additionally, might I suggest that using a "bintray.com" domain and what appears to be a user's home directory for https://dl.bintray.com/mitchellh/vault/ makes the source appear less than reliable... I found references to that url elsewhere on the net, and thought they were simply copies to someone's home directory.

Thanks!

**Comment by oskarpearson** [comment]
Another thing to note - I can't find any external reference to the key ID 348FFC4C that was used to sign the packages, with the exception of https://github.com/hashicorp/vault/blob/master/scripts/dist.sh

**Comment by armon** [comment]
@oskarpearson The downloads page (https://vaultproject.io/downloads.html) has links to both the SHA256 and the PGP public key. We use BinTray to host our binaries and we don't control their download URLs.

I agree the documentation can be further improved to show how verification can be done, marking as a doc enhancement.

**Comment by jesseendahl** [comment]
I have a bash script I made to download and verify the binary. It assumes:

- You have GPG installed.
- You've previously downloaded the Hashicorp public GPG key to the directory you're running the script in.

Needed improvements:
- Check if Hashicorp GPG public key has already been previously imported.
- Don't re-download files if they already exist in dir.

```
#!/bin/bash
set -e

VAULT_VERSION=0.2.0

# SHA256SUMS FILE
curl -L --progress-bar https://dl.bintray.com/mitchellh/vault/vault_${VAULT_VERSION}_SHA256SUMS?direct -o tmp/vault_${VAULT_VERSION}_SHA256SUMS

# SHA256SUMS SIGNATURES FILE
curl -L --progress-bar https://dl.bintray.com/mitchellh/vault/vault_${VAULT_VERSION}_SHA256SUMS.sig?direct -o tmp/vault_${VAULT_VERSION}_SHA256SUMS.sig

# VAULT BINARY
curl -L --progress-bar https://dl.bintray.com/mitchellh/vault/vault_${VAULT_VERSION}_linux_amd64.zip -o tmp/vault_${VAULT_VERSION}_linux_amd64.zip

# YOU NEED TO DOWNLOAD THE PUBLIC KEY ON YOUR OWN FROM HERE: https://hashicorp.com/security.html

gpg --import hashicorp.pub
gpg --verify tmp/vault_${VAULT_VERSION}_SHA256SUMS.sig tmp/vault_${VAULT_VERSION}_SHA256SUMS

SHA256_FROM_FILE=`grep vault_${VAULT_VERSION}_linux_amd64.zip tmp/vault_${VAULT_VERSION}_SHA256SUMS | cut -d" " -f 1`
SHA256_FROM_OPENSSL=`openssl dgst -sha256 tmp/vault_${VAULT_VERSION}_linux_amd64.zip | cut -d" " -f 2`

echo "SHA256_FROM_FILE = $SHA256_FROM_FILE"
echo "SHA256_FROM_OPENSSL = $SHA256_FROM_OPENSSL"

if [ "$SHA256_FROM_FILE" = "$SHA256_FROM_OPENSSL" ]
    then echo "SHA256 HASH MATCHES. PROCEED!"
else echo "SHA256 HASH DOES NOT MATCH. DO NOT CONTINUE!"
fi
```

**Comment by jefferai** [comment]
Closing -- @jesseendahl 's script is pretty nice!
