### ISSUE TITLE
OpenID Connect auth backend

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/vault#465]
It'd be useful for Vault to have an auth backend that can use an OpenID Connect provider such as Google to authenticate and authorize users.

In particular I'd love it if an administrator could map OpenIDC claims (https://openid.net/specs/openid-connect-basic-1_0.html#StandardClaims) to policies when configuring the backend.

**Comment by mfischer-zd** [comment]
Implementing this may impossible if Vault cannot communicate with a browser for the purpose of authenticating the user -- I'm not aware of any OpenIDC clients that are not browser-based.  This request can be reopened if the situation ever changes.

**Comment by jessechahal** [comment]
OpenID connect 1.0 does support workflows that do not require a browser. As long as the client can make HTTP requests there are at least 3 workflows that do not require browser. One is direct access grants (sending client id, client secret, username, and password to OpenID server), another would be refresh_token (already got token on behalf of user in advance), and the finally service accounts (authenticate only as a client). Any company who use their own OpenID providers such as Auth0, ping identity, wso2, etc... would benefit from having at least some support for OpenID connect. 

I saw that there was an open PR for supporting google using openID connect. https://github.com/hashicorp/vault/pull/1219 Wouldn't it be better if vault implemented generic support for OpenID and added other vendor implementations ontop of them? The implementations built ontop of base would only need to state a few url endpoints and which grant_type they wish to use. This would solve all current and future requests for support of specific openID providers.
i.e. https://github.com/hashicorp/vault/issues/1203

**Comment by jefferai** [comment]
@jessechahal The specificity of the google one is a concern of mine as well.

**Comment by grunzwei** [comment]
@jessechahal @jefferai i would have liked to implement #1219  as a layer over something generic, but unfortunately could not find a way to do so.
google supports a non-standard "code" that you can get manually via the browser and pass to the cli in a secure fashion, and can later be used to retrieve renewable tokens by the software.
i'm not aware of any other oauth providers having any similar feature... :(

**Comment by mbatista39** [comment]
Hi there! there is any news regarding this? I agree with jessechahal, if Vault supports OpenId connect it would be useful for everybody since most of the Authentication serves support it.
For instance if you could authenticate on Vault throught KeyCloak (supports OpenId connect protocol) you can also then Configure Keycloak to be a broker to other ID providers like Google or Facebook, etc.

Right now i need to use Keycloak with my LDAP but make usage of Vault for secrets management.

Is there a way?

thanks.

**Comment by bitglue** [comment]
OpenID Connect is indeed possible, I've implemented it here: https://github.com/hashicorp/vault/issues/5305
