### ISSUE TITLE
Policy Definition Globbing Only Works On One Level

### ISSUE THREAD

**Issue by kaelumania** [hashicorp/vault#467]
I spent the last hours to find out that policy globbing only works for one level of indirection. 

For example,

```
path "sys/*" { policy="sudo" }
```

allows to read `sys/policy` but does **NOT** allow to read `sys/policy/XXX`

You have to set up further rules like 

```
path "sys/policy/*" { policy="sudo" }
```

to be able to read the details of a policy.

In my opinion this is not a very convenient behaviour. Imagine you have a deeply nested hierarchy in your `secret` backend and you want to get complete access with one policy. With the current implementation thats not possible.

----- UPDATE

It works for `auth/*` and `secret/*`, seems that there a problem with `sys`.

**Comment by armon** [comment]
@kaelumania Can you provide more details where you are running into this? Maybe a repro case? The policy globing is the same for all paths, so there should not be anything special about `sys/`. There are certainly some edges with some of those endpoints however, so that can help us narrow it down.

**Comment by kaelumania** [comment]
@armon after setting up a dedicated vault environment to test this behaviour, I think I found the reason.

I had a policy with `sys/*` *sudo* and `sys/policy/*` *write*. Thus due to longest prefix matching the second rule is being used and due to https://github.com/hashicorp/vault/blob/199155b41bb4593c97af6bf8482b88905c087b7d/vault/logical_system.go#L26 only *sudo* is allowed.

What if someone only wants to read the policy rules (thus gets read access to `auth/policy/*`)? In my opinion this is a valid requirement because someone might be interested in the policies assigned to him.

**Comment by armon** [comment]
@kaelumania I agree, we need more fine grained ACL rules. For now really the rules are buckets of permissions, similar to canned ACLs. We need to allow really fine grained "read to root path" for that, but it's not possible in our policy language currently.

**Comment by jefferai** [comment]
As Armon indicated this isn't currently possible with the ACL language and does not look like it will be implemented given that we don't have plans to change the language.
