### ISSUE TITLE
Red

### ISSUE THREAD

**Issue by JaceTSM** [hashicorp/vault#4678]
<removed>

**Comment by jefferai** [comment]
As a reminder, listed in the template for every bug report, at the top of our Readme, and in every release, if you believe you have found a security vuln, you should responsibly disclose it directly to us via security@hashicorp.com.

I've removed the content above, but simply creating a ticket emails the info to hundreds of people.

**Comment by jefferai** [comment]
@JaceTSM Please feel free to reach out to us via security@hashicorp.com for further discussion.

**Comment by jefferai** [comment]
I'm closing the issue for now as I cannot reproduce it, but if it turns into any actionable item upon further discussion with @JaceTSM it will be resolved in 0.10.2.
