### ISSUE TITLE
Sudo rights required in order to read auth backend certificate information

### ISSUE THREAD

**Issue by kaelumania** [hashicorp/vault#468]
In order to read `auth/cert/certs/#{name}` one needs `sudo` rights for `auth/*`. Is that intended behavior? Is there a list of paths where you need `sudo`? I would prefer when `read` rights should be enough for reading certificate information.

**Comment by kaelumania** [comment]
I think I found the reason (see https://github.com/hashicorp/vault/blob/6a9dc00e57eb423ad32d4b97a5b3d829f22c5d49/builtin/credential/cert/backend.go#L17). The question is why this is desireable, my I am logged as _XXX_ in with my certificate then I should be able to read my certificate information at `auth/cert/certs/XXX`.

**Comment by armon** [comment]
@jefferai Any reason to require root to read a cert?

**Comment by jefferai** [comment]
Probably not, but I don't have insight into the design of the TLS auth backend, so not sure why it is that way right now. I would imagine it should be safe to pull up certs on demand, since it's the private keys that need to remain secret.

**Comment by jefferai** [comment]
I'm going to remove both `certs/` and `crls/` from needing root paths in favor of using normal ACL mechanisms.
