### ISSUE TITLE
multiple Secret path inheritance or association

### ISSUE THREAD

**Issue by hmlingesh** [hashicorp/vault#4697]
Hello Team,

Just want to know, do you have any features like secret inheritance or association available with multiple secret paths?

For Example, 

**PATH 1 :** secret/common ==> {"foo":"bar"} 
**PATH 2 :** secret/test ==> {"test": "test"}

so when I read from **secret/test** which should fetch parent properties ("secret/common") and current path ("secret/test) both. So this case I should have the option to create inheritance relationship between both.

Final result should be {"foo":"bar", "test":"test"}

Please share your thoughts?

Regards
Lingesh M

**Comment by jefferai** [comment]
We do not, sorry.

**Comment by hmlingesh** [comment]
thanks, Jefferai.
