### ISSUE TITLE
Support crypto.Decrypter for TLS Authentiation (allowing better support of TPM, yubikey, ...)

### ISSUE THREAD

**Issue by trevex** [hashicorp/vault#4708]
**Is your feature request related to a problem? Please describe.**
We have bare-metal servers with TPMs and yubikeys and use them for PKI.
These can then be used to talk with matchbox behind a TLS proxy.
As the amount of application-specific secret data grows it would be nice to use vault for more fine grained access control and secret management. It is not possible to interact with the client without specifying a path to the private key.

**Describe the solution you'd like**
It would be nice if [`api.TLSConfig`](https://godoc.org/github.com/hashicorp/vault/api#TLSConfig) supported the golang [`crypto.Decrypter`](https://golang.org/pkg/crypto/#Decrypter) interface similar to the inbuilt [`tls.Certificate`](https://golang.org/pkg/crypto/tls/#Certificate). 

**Describe alternatives you've considered**
Well an alternative would be AppRole, but storing the secret in plain text is undesired, if TPMs or yubikeys are available.

**Explain any additional use-cases**
Supporting the `crypto.Decrypter` interface would allow to support the whole range of hardware available. 

**Additional context**
In golang the interface is usually used as follows:
```
var decrypter crypto.Decrypter
decrypter = <implement this>

cert := &tls.Certificate{}
cert.<other fields>
cert.PrivateKey = decrypter

conn, err := tls.Dial("tcp", "127.0.0.1:443", &tls.Config{
	Certificates: []{cert},
})
```

**Comment by jefferai** [comment]
You can actually do this already by specifying the `*http.Client` in the `*api.Config` given to `NewClient`. Set the client TLS options on the transport and you're golden.

**Comment by trevex** [comment]
Perfect, I didn't know that. Thank you very much. This issue is a non-issue then.
