### ISSUE TITLE
Audit log files incompatible with log rotation

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/vault#472]
Vault appears not to do any sort of checking of its audit log file to see whether it's been renamed by an external log rotator, and so it'll continue to write to the original file even after a rename.

Two options are available, possibly more:

1. Vault can stat the file periodically and if its inode has changed, reopen the log file.  This is probably not compatible with Windows, and will result in a dramatic increase in syscalls.
2. Vault can reopen its audit log files upon receiving a signal (I recommend SIGUSR2, since SIGUSR1 causes Vault to print statistics to stdout).

**Comment by mfischer-zd** [comment]
A temporary workaround is to disable and then immediately re-enable the audit log file backend after rotation:

```
$ vault audit-disable file
$ vault audit-enable file path=...
```

However, this requires an authentication token with a root policy association to be provided to the log rotator.

**Comment by ekristen** [comment]
+1

**Comment by rboyer** [comment]
If you are using `logrotate` there's an option `copytruncate` that can be used to rotate files written like this.

**Comment by jefferai** [comment]
I think option number 2 mentioned in the OP is not a bad idea, but in the meantime there are other good workarounds, such as @rboyer's suggestion. I've used that with other software that doesn't re-open log files quite successfully.

**Comment by otterley** [comment]
`copytruncate` technically works but has some undesired side-effects, like thrashing your buffer caches and creating a lot of otherwise-unnecessary I/O.

**Comment by jefferai** [comment]
There's also the `syslog` backend, which makes things much more flexible (if you are running in an environment with a syslog daemon, or where one could be added).

**Comment by enudler** [comment]
is there any plan to add build in support for log file rotation?

**Comment by jefferai** [comment]
No, there are no current plans for this.

**Comment by mfischer-zd** [comment]
Looks like you can send a SIGHUP now to make Vault reopen audit log files: #1953

**Comment by jaydipdave** [comment]
If we send SIGHUP signal to the Vault process running in docker (as the entrypoint), will cause the container crash!

**Comment by soloradish** [comment]
This my logrotate  settings.
https://gist.github.com/soloradish/e9a2f2188d147bfa3e73fe63bbdf890a

**Comment by yermulnik** [comment]
For those who came here looking for logrotate config for vault audit log: do not blindly copy&paste vault logrotate config from the previous comment (link to gist.github.com) — it has some, erm, mistakes (e.g. missing the character separating log name from the extension). But the main issue is that it doesn't fit your needs when vault is configured to relay logs by means of syslog — hence syslog daemon doesn't get notified on log rotation thus continues to write logs to renamed file (basically the root topic of this issue but related to another app).

**Comment by esseti** [comment]
Can someone (maybe would be good in the official guide) provide the logrotate when auditlogs are written to a file?

**Comment by andytsnowden** [comment]
> 
> 
> Can someone (maybe would be good in the official guide) provide the logrotate when auditlogs are written to a file?

This is what I'm using, adjust the retention and path to systemctl (or your proc manager).  

```bash
/opt/vault/log/vault_audit.log {
  daily
  rotate 7
  notifempty
  missingok
  compress
  delaycompress
  postrotate
    /bin/systemctl reload vault 2> /dev/null || true
  endscript
  create 0644 vault vault
}
```

Since the audit log is rather verbose we only keep a few days local, rest is exported to S3 via Fluentd

**Comment by KbLev** [comment]
I have a bog-standard vault install on RHEL7 and reloading vault in the postrotate script doesn't seem to be working, it keeps writing to the old logfile,  /var/log/vault/vault.log.1
