### ISSUE TITLE
vault 0.10.x: active node won't shut down cleanly

### ISSUE THREAD

**Issue by jeinwag** [hashicorp/vault#4737]
**Describe the bug**
We're running vault in a HA setup with consul 0.7.5 as the storage backend. Starting with 0.10.0, we're unable to stop vault in a clean way.

**To Reproduce**
1. Run `systemctl stop vault` on the active node.
2. There's the following output in the log, and then nothing until vault is killed by SIGKILL:

```
Jun 11 11:07:43 vault-int-01 vault[2407]: ==> Vault shutdown triggered
Jun 11 11:07:43 vault-int-01 vault[2407]: 2018-06-11T11:07:43.898+0200 [INFO ] storage.consul: shutting down consul backend
```
I've attached a full log of the vault process incluing is a trace  retrieved by sending SIGQUIT.
[vault-log.txt](https://github.com/hashicorp/vault/files/2089336/vault-log.txt)

**Expected behavior**
I expect vault to shut down.

**Environment:**
* Vault Server Version 0.10.1
* Vault CLI Version 0.10.1
* Server Operating System/Architecture: Ubuntu 16.04/x86_64

Vault server configuration file(s):

```hcl
ui = true
backend "consul" {
        address = "localhost:8500"
        path = "vault"
        token = "<token>"
        advertise_addr = "https://172.16.100.66:8200"
}

listener "tcp" {
         address = "127.0.0.1:8200"
         tls_disable = 1
}

listener "tcp" {
        address = "172.16.100.66:8200"
        tls_disable = 0
        tls_cert_file = "/etc/vault/vault.crt"
        tls_key_file = "/etc/vault/vault.key"
}
```

**Comment by jefferai** [comment]
When you say nothing -- how long are you waiting? The logs show that Vault is waiting on K/V operations on Consul due to trying to revoke expired leases. There are a number of these going on concurrently, all waiting on Consul to return from List operations and in 0.10.1 this call isn't preemptible. One reason this might take a long time is if you have very large token hierarchies -- lots of children from one parent. You can see if 0.10.2 helps, or when 0.10.3 is out (later this week ideally) it will have a patch to pass context to Consul calls to hopefully allow preemption.

**Comment by jeinwag** [comment]
I've tried waiting a couple of minutes.

But I think something is messed up in our integration cluster - both Vault and Consul use a large amount of CPU time. There are tons (hundreds per second) of GET-requests like the following from vault to Consul:
``
GET v1/kv/vault/sys/token/parent/6d4525d7e97a2db72fd5b7da79902b23aa7c1805/?keys=&separator=%2F
``
Most of these result in a 404 reply. I guess these are the list operations you are talking about?

Currently, I have no idea what's causing this.

**Comment by jefferai** [comment]
Yes. You should upgrade to 0.10.2 as we've done a lot of work around fixing that.

**Comment by jefferai** [comment]
Also once you upgrade to 0.10.2 you may want to run https://www.vaultproject.io/api/auth/token/index.html#tidy-tokens

**Comment by jeinwag** [comment]
Thanks a lot - I running tidy-tokens after the uprade to 0.10.2 fixed the issue for us

**Comment by jefferai** [comment]
Great! Also you may want to reexamine how you are using tokens -- usually large token hierarchies are not needed. If you can describe some workflows I can give some pointers.
