### ISSUE TITLE
Vault UI shows an empty list of secrets for KV v2 store after upgrade to 0.10.2

### ISSUE THREAD

**Issue by alexandersusha** [hashicorp/vault#4740]
**Describe the bug**
I enabled versioning (KV v2) for a KV secret store on Vault v.0.10.0 and I was able to get a list of secrets and to read them in Vault UI and in CLI. 
After upgrade to v.0.10.2 I lost ability to get access to secrets in UI. Vault UI shows an empty list of secrets for secret/. If I use Vault CLI all secrets are in place.
After downgrade to Vault v.0.10.0  Vault UI works as expected and shows all secrets in secret/ (KV v2)

**To Reproduce**
1. Install Vault  v0.10.2
2. Enable versioning KV secret backend
3. Try to list secrets in secret/ on Vault UI

**Expected behavior**
I should see a list of secrets for KV v2 store in UI.

**Environment:**
* Vault Server Version 0.10.2
* Vault CLI Version 0.10.2
* Server Operating System/Architecture: Debian 8.7 in a Docker container

**Additional context**
Request log from UI for v0.10.0:
`{"time":"2018-06-11T13:34:59.633531278Z","type":"request","auth":{"client_token":"hmac-sha256:6a8aaf0335dca1238babe3808838416a363b07e1873ca09c9dfd80cff5a86c1a","accessor":"hmac-sha256:06ac7cb74b72b9afabad2561feb0beb5f43ad5ad9794084732376f66ab7d8304","display_name":"ldap-alexander.susha","policies":["admin-policy","default"],"metadata":{"username":"alexander.susha"},"entity_id":"1daa44a9-bb29-7fdd-50ad-c99939c7e0ba"},"request":{"id":"2b9e01c6-2a55-8254-10f1-12290c0d4278","operation":"list","client_token":"hmac-sha256:6a8aaf0335dca1238babe3808838416a363b07e1873ca09c9dfd80cff5a86c1a","client_token_accessor":"hmac-sha256:06ac7cb74b72b9afabad2561feb0beb5f43ad5ad9794084732376f66ab7d8304","path":"secret/metadata/","data":null,"policy_override":false,"remote_address":"x.x.x.x","wrap_ttl":0,"headers":{}},"error":""}`

Request log from UI for v0.10.2:
`{"time":"2018-06-11T13:24:05.756343265Z","type":"response","auth":{"client_token":"hmac-sha256:6a8aaf0335dca1238babe3808838416a363b07e1873ca09c9dfd80cff5a86c1a","accessor":"hmac-sha256:06ac7cb74b72b9afabad2561feb0beb5f43ad5ad9794084732376f66ab7d8304","display_name":"ldap-alexander.susha","policies":["admin-policy","default"],"metadata":{"username":"alexander.susha"},"entity_id":"1daa44a9-bb29-7fdd-50ad-c99939c7e0ba"},"request":{"id":"c95aa284-d31b-c9d0-f32d-6f0aae54c719","operation":"list","client_token":"hmac-sha256:6a8aaf0335dca1238babe3808838416a363b07e1873ca09c9dfd80cff5a86c1a","client_token_accessor":"hmac-sha256:06ac7cb74b72b9afabad2561feb0beb5f43ad5ad9794084732376f66ab7d8304","path":"secret/","data":null,"policy_override":false,"remote_address":"x.x.x.x","wrap_ttl":0,"headers":{}},"response":{"data":{"http_content_type":"hmac-sha256:b3cc9b71699bc2de0aed0cc59e3573dcffc52717849c6d69496c4d64f12ad9a3","http_raw_body":"hmac-sha256:1e2d1cb06efd93980c833b532e144cbd52b3d91b23af041d0df92a2b4447cb8f","http_status_code":404}},"error":""}
`

**Comment by alexandersusha** [comment]
Hi @meirish! Thank you for the response! The additional details are below:

1. Our storage backend: Consul 1.0.1
2. Vault secret engine list:
Before migration to KV v2
`"secret/": {
    "type": "generic",
    "description": "generic secret storage",
    "accessor": "generic_48699b26",
    "config": {
      "default_lease_ttl": 0,
      "max_lease_ttl": 0,
      "force_no_cache": false
    },
    "options": null,
    "local": false,
    "seal_wrap": false
  },
`
After migration to KV v2 (vault kv enable-versioning secret/)
`  "secret/": {
    "type": "generic",
    "description": "generic secret storage",
    "accessor": "generic_48699b26",
    "config": {
      "default_lease_ttl": 0,
      "max_lease_ttl": 0,
      "force_no_cache": false
    },
    "options": {
      "version": "2"
    },
    "local": false,
    "seal_wrap": false
  },
`
All other details are attached as screenshots
![secret_configuration_0_10_2_ui](https://user-images.githubusercontent.com/17471309/41283209-a6d3f800-6e3e-11e8-8299-013228ddfe53.PNG)
![secret_list_0_10_0_headers](https://user-images.githubusercontent.com/17471309/41283210-a7013d42-6e3e-11e8-9b39-4e0616427cfe.PNG)
![secret_list_0_10_0_preview](https://user-images.githubusercontent.com/17471309/41283211-a72d218c-6e3e-11e8-9a50-e30fd8359b4c.PNG)
![secret_list_0_10_0_response](https://user-images.githubusercontent.com/17471309/41283212-a759a9e6-6e3e-11e8-8883-5790037f1005.PNG)
![secret_list_0_10_0_ui](https://user-images.githubusercontent.com/17471309/41283213-a784a07e-6e3e-11e8-8c4e-975c5ca9a85a.PNG)
![secret_list_0_10_2_cli](https://user-images.githubusercontent.com/17471309/41283214-a7bc5d48-6e3e-11e8-8cd9-b2399a7bfbf6.PNG)
![secret_list_0_10_2_headers](https://user-images.githubusercontent.com/17471309/41283215-a7e7b1dc-6e3e-11e8-9d0b-5bdd6307e19d.PNG)
![secret_list_0_10_2_preview](https://user-images.githubusercontent.com/17471309/41283216-a8213254-6e3e-11e8-9a97-891703d68dc1.PNG)
![secret_list_0_10_2_response1](https://user-images.githubusercontent.com/17471309/41283219-a85a58b8-6e3e-11e8-9e0e-55eaee0705ec.PNG)
![secret_list_0_10_2_response2](https://user-images.githubusercontent.com/17471309/41283220-a88c6a6a-6e3e-11e8-97d9-0c6dee09d2e1.PNG)
![secret_list_0_10_2_ui](https://user-images.githubusercontent.com/17471309/41283223-a8e0d2ee-6e3e-11e8-9379-a3b635ab340c.PNG)
![secrets_after migration_to_kv_v2](https://user-images.githubusercontent.com/17471309/41283224-a916ba12-6e3e-11e8-9cda-88ec651b3779.PNG)
![secrets_before migration_to_kv_v2](https://user-images.githubusercontent.com/17471309/41283225-a9637cb2-6e3e-11e8-99eb-1a2945d9716f.PNG)

**Comment by meirish** [comment]
Ok! I think I see the issue- I’m guessing we changed something in the UI to detect the new kv v2 and only took into account type “kv” and not also the legacy type “generic”. I’ll look more into this later today. Thanks again for submitting this!
