### ISSUE TITLE
Root rotation for MSSQL not working

### ISSUE THREAD

**Issue by bardagadvergur** [hashicorp/vault#4745]
When trying to rotate the root credentials on MSSQL using either the CLI or the API I get the following error:

> Error writing data to database/rotate-root/mssql: Error making API request.
> URL: PUT http://0.0.0.0:8200/v1/database/rotate-root/mssql Code: 500. Errors:
>1 error occurred:
>mssql: Cannot alter the login '%!s(MISSING)', because it does not exist or you do not have permission.

I am using Hashicorp Vault 0.10.2 on docker. To reproduce: 

- spin up the docker image (and a sql image perhaps) in dev mode and authenticate with the root token.
- Enable the database plugin for SQL 
- Create a user on the SQL server. User: vaultrolecreator, pass: UnSafePass with the sysadmin role + alter any login + alter any credentials
- vault write database/config/mssql plugin_name="mssql-database-plugin" connection_url="sqlserver://{{username}}:{{password}}@sql:1433" allowed_roles="*,imagine" username="vaultrolecreator" password="UnSafePass"

When trying to do `vault write -force database/rotate-root/mssql` the error will be thrown.

Additional info. The problem does not seem to be on the SQL permissions. If I change the password on SQL with SSMS, trying to rotate through HashiCorp still gives the same error.

**Comment by chrishoffman** [comment]
Good catch!  It looks like this is a copy and paste error with how other parts of this plugin work.  I will work on a fix.

**Comment by chrishoffman** [comment]
As a workaround, you can provide custom SQL in the backend config.  Try setting your root rotation statements to the following:

```
ALTER LOGIN [{{username}}] WITH PASSWORD = '{{password}}'
```

See https://www.vaultproject.io/api/secret/databases/index.html#root_rotation_statements.

**Comment by bardagadvergur** [comment]
Great. My DBA is super stoked about this feature.
