### ISSUE TITLE
Provide a way to enumerate tokens

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/vault#475]
Per a comment in #111, it should be possible to enumerate authentication tokens issued by Vault, and to show the details of such tokens.  It'd be especially useful if they could be shown hierarchically.  We'd like to be able to:
- Perform garbage collection (mitigate risk of token stealing)
- Show tokens improperly parented by the root token
- Show tokens improperly given an infinite lease
- Show the remaining use count for a token
- Show the remaining lease time for a token

**Comment by wwalker** [comment]
+1

Need to be able to see what tokens have been created by a specific token, in case it has been compromised.

This would allow notifying those persons whose tokens we are about to revoke (Assuming we added metadata for email address...)

**Comment by theonewolf** [comment]
:+1:

**Comment by wwalker** [comment]
GET /v1/secret/asdf is valid.  GET /v1/secret/asdf/ is currently invalid

Can we just make a GET with a trailing slash (/) on the path be a request to enumerate the elements available in the path?

**Comment by wwalker** [comment]
When this feature is added, there is the question of whether it adds a role to policy.

I think that it does.  We currently have write, and read; I think we should have read_keys.

The use case for read_keys is a developer needs to know what properties/secrets are available to his application in productions without the ability to see those secrets.  Given a app, BitCoinMiner, policies would be:

Ops - write
BitCoinMiner - read
BitCoinMinderDeveloper - read_keys

**Comment by jefferai** [comment]
Closing; tokens can be enumerated via listing accessors.
