### ISSUE TITLE
MSSQL Database Secrets Engine does not close connections

### ISSUE THREAD

**Issue by pascal-enz** [hashicorp/vault#4752]
When Vault connects to a SQL Server database (using the MSSQL Database Secrets Engine) to perform operations like managing users, it does not properly disconnect from the database afterwards. This can be verified by using the "EXEC sp_who" command.

This causes various problems, in particular it prevents other users from performing any kind of administrative operation which requires single user access, including changing database settings or deleting a database. For example the following command can never be executed by another user (even a sa user) because of the persistent Vault connection.

ALTER DATABASE [MyDatabase] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
-- change a database setting

Vault should always close database connections after performing an operation to prevent this problem from occurring.

**Comment by chrishoffman** [comment]
The MSSQL driver uses a connection pool to efficiently handle database connections.  You can control how long a connection is reused for with the `max_connection_lifetime` parameter on the database configuration.

See https://www.vaultproject.io/api/secret/databases/mssql.html#max_connection_lifetime.

**Comment by pascal-enz** [comment]
Thank you for the link Chris. I set _max_idle_connections_ = -1 and now it seems to work fine.
