### ISSUE TITLE
Limit list policy to specific entries

### ISSUE THREAD

**Issue by onitake** [hashicorp/vault#4755]
**Is your feature request related to a problem? Please describe.**
Giving users full list access to elements of a path can be a security issue, but it's currently the only way to support browsing to specific credentials. Denying list access will provide a worse user experience in UI clients, as no subpaths will be listed and the full path needs to be known in advance.

**Describe the solution you'd like**
Add new `allowed_list`/`denied_list` key to the path policy definitions.
Specifying this key should limit the results returned by a list command on this path.

**Describe alternatives you've considered**
None

**Explain any additional use-cases**
None

**Additional context**
None

**Comment by jefferai** [comment]
Sorry, but we will not be adding this. ACLs operate only on requests and are not invoked for responses.

Additionally, you should not be using secret names as part of K/V paths, in particular since with K/V v1 these paths are stored in plaintext.
