### ISSUE TITLE
Vault Cluster - Status details not syncronized to other instances - Rekey bug

### ISSUE THREAD

**Issue by ncastrocosta** [hashicorp/vault#4758]
Hi people!

**Describe the bug**

I have a cluster of 3 Vault instances: one is sealed, another is active, another in standby.

I'm learning the rekeying process. What happened was that I connected to the active instance and executed the rekey init command. In this process, I changed the number of shared keys and the threshold.

Take note: I had key-shares=3 and key-threshold=2; and I changed to key-shares=1 and key-threshold=1.

After that, when I checked the status of each instance, I noticed the sealed and standby instances still had old status information about the number of keys and threshold.

First question: should I run some command to update the status? or is it a bug?

Continuing... even with this outdated information, I decided to unseal that instance which was sealed. However, I was not able to unseal the instance, because it was still waiting 2 keys!

Second question: did I do something wrong? Am I expecting for something that will/should not happen?

So, I decided to reset the unseal process and tried to unseal using 2 old keys.

The first old key was accepted (strange, isn't it?), but after entering the second old key, the result was:

```
#
# Instance 1
#
Key (will be hidden):
Error: Error making API request.

URL: PUT Instance 1/v1/sys/unseal
Code: 400. Errors:

* Unseal failed, invalid key
```

Take note: I have 3 old keys and threshold of 2. It doesn't matter which key I enter first. The second key always produced the same error above.

I concluded I was locked out.

Of course, I must ask you to believe in me when I say I used the right keys in the right way - other collegues of mine also tried and failed.

Third question: did I really lose that instance?

No! I restarted the instance machine and the status was updated! Then, I ran the unseal process again and it worked as expected.

Fourth question: do I really need to restart each other Vault machine every time in a scenario like that?

**To Reproduce**

Below, I have the outputs of the process.

First, the status os each machine before unseal process.

```
#
# Instance 1 - The sealed one
#
Sealed: true
Key Shares: 3
Key Threshold: 2
Unseal Progress: 0
Unseal Nonce:
Version: 0.8.2

High-Availability Enabled: true
        Mode: sealed
#
# Instance 2 - The active one
#
Sealed: false
Key Shares: 3
Key Threshold: 2
Unseal Progress: 0
Unseal Nonce:
Version: 0.8.2
Cluster Name: vault-cluster-2afecb17
Cluster ID: 23bc5c97-fc14-9a3a-ca22-fe121c3089c5

High-Availability Enabled: true
        Mode: active
        Leader Cluster Address: Instance 2
#
# Instance 3 - The one in standby
#
Sealed: false
Key Shares: 3
Key Threshold: 2
Unseal Progress: 0
Unseal Nonce:
Version: 0.8.2
Cluster Name: vault-cluster-2afecb17
Cluster ID: 23bc5c97-fc14-9a3a-ca22-fe121c3089c5

High-Availability Enabled: true
        Mode: standby
        Leader Cluster Address: Instance 2
```

Then, I started the rekeying process on the active instance

```
$ vault rekey -init -key-shares=1 -key-threshold=1

Nonce: f21114fa-fcbe-ef39-8b4b-3f587b4cd9d9
Started: true
Key Shares: 5
Key Threshold: 3
Rekey Progress: 0
Required Keys: 2
```

Proceeded with rekey operation entering the 2 keys required.

The status of each instance. Note instances 1 and 3 with different status than 2.

```
#
# Instance 1
#
Sealed: true
Key Shares: 3
Key Threshold: 2
Unseal Progress: 0
Unseal Nonce:
Version: 0.8.2

High-Availability Enabled: true
        Mode: sealed
#
# Instance 2
#
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0
Unseal Nonce:
Version: 0.8.2
Cluster Name: vault-cluster-2afecb17
Cluster ID: 23bc5c97-fc14-9a3a-ca22-fe121c3089c5

High-Availability Enabled: true
        Mode: active
        Leader Cluster Address: Instance 2
#
# Instance 3
#
Sealed: false
Key Shares: 3
Key Threshold: 2
Unseal Progress: 0
Unseal Nonce:
Version: 0.8.2
Cluster Name: vault-cluster-2afecb17
Cluster ID: 23bc5c97-fc14-9a3a-ca22-fe121c3089c5

High-Availability Enabled: true
        Mode: standby
        Leader Cluster Address: Instance 2
```

Tried to unseal Instance 1

```
#
# Instance 1
#
$ vault unseal
```

After first old key entered.

```
#
# Instance 1
#
Key (will be hidden):
Sealed: true
Key Shares: 3
Key Threshold: 2
Unseal Progress: 1
Unseal Nonce: 63aec087-6a6c-edef-339c-5d2d08d27047
```

After second old key entered.

```
#
# Instance 1
#
Key (will be hidden):
Error: Error making API request.

URL: PUT Instance 1/v1/sys/unseal
Code: 400. Errors:

* Unseal failed, invalid key
```
It doesn't matter which key I enter first. The second key always produced the same error above.

**Expected behavior**

I was expecting, after rekey operation, the status to be updated among all instances; and no problems when unsealing that instance. 

**Environment:**
* Vault Server Version 0.8.2
* Vault CLI Version 0.8.3
* Server Operating System/Architecture: CentOS 7 / Docker Alpine / Kubernetes; 3 Vault instances and 5 Consul instances.

Vault server configuration file(s):

```hcl
backend "consul" {
  address = "127.0.0.1:8500"
  path    = "vault/"
  token   = "__CONSUL_MATER_TOKEN__"
}

listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_cert_file = "/etc/vault.d/certs/server.crt"
  tls_key_file  = "/etc/vault.d/certs/server.key"
}

telemetry { 
  statsd_address = "localhost:9125"
}
```

**Comment by jefferai** [comment]
There is a process that runs periodically (either every 30 seconds or every 60 seconds) that has the standby nodes analyze the data to look for any seal changes. This would have happened on its own, you just didn't give it enough time :-)

**Comment by ncastrocosta** [comment]
Hi @jefferai,

Unfortunately, that's not what happened. The instances were up for hours and nothing updated their status.
