### ISSUE TITLE
API request sometimes hang for 5 seconds and return 500 error response.

### ISSUE THREAD

**Issue by atomd** [hashicorp/vault#4781]
I've encountered the following issue：

When Initiating an login **api** request on a 3-node Vault cluster, sometimes the operation freezes for 5 seconds and return 500 error response. 

- These failed requests（more than 5 seconds）are sent to the standby node,  error messages are `context deadline exceeded`.
- I alse noticed that some error messages are `rpc error: code = Canceled desc = grpc: the client connection is closing'`，these requests took less than 5 seconds.

**Environment:**
Vault Server Version: 0.10.1
MySQL Storage Backend
Consul HA Backend

How can I avoid this problem?

**Comment by jefferai** [comment]
Upgrade to 0.10.2 and set VAULT_MAX_RETRIES=0 on your client machine.

**Comment by atomd** [comment]
@jefferai Hi,
This method may not apply to me.
I use HTTP API on my client machine, not Vault CLI.

**Comment by jefferai** [comment]
Can you provide configuration and logs for both the active node and the standby?

**Comment by jefferai** [comment]
I don't see anything obviously wrong in your config (other than that you don't need `redirect_addr` and `api_addr`, they're the same thing, and both `api_addr` and `cluster_addr` should live at the top level, not within `ha_storage`) but there is also no real logs there to look at.

**Comment by atomd** [comment]
There will be a small amount of this error：`InternalServerError('rpc error: code = Canceled desc = grpc: the client connection is closing')` . This type of request also takes `3-4` seconds. 
What may be the cause of the error?  Do you have any suggestions to troubleshoot it?

**Comment by jefferai** [comment]
Yes, the client request wasn't satisfied within its context deadline. How long do logins usually take against the active node?

Honestly, I can't help you more without full logs. There's nothing immediately apparent in the config. Vault prints out useful debug information to stdout when it starts up, and then prints more into stderr as it runs. Without those logs I'm just shooting in the dark. Please run in debug or trace mode using `-log-level=trace`, capture logs from startup, and provide them.

**Comment by atomd** [comment]
@jefferai Hi, I confirmed this problem because of the instability of the etcd peer connection. tls configuration may have error, which will trigger the election of the master frequently.

The weird thing is that vault's logs have no more information about it, but vault response of a small number request contains some error messages.

**Comment by briankassouf** [comment]
Sounds like the issue was narrowed down to an etcd network issue. Closing for now, if you are still experiencing issues let us know
