### ISSUE TITLE
error while writing the basic policy for aws 

### ISSUE THREAD

**Issue by kodati9** [hashicorp/vault#4795]
**Environment:**

* Vault Version:
* Operating System/Architecture:

**Vault Config File:**
>vault write aws/roles/my-role policy=EmptyFile.json
Error writing data to aws/roles/my-role: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/aws/roles/my-role
Code: 400. Errors:

* Error compacting policy: invalid character 'E' looking for beginning of value

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Startup Log Output:**

```text
# Paste your log output here
```

**Expected Behavior:**

**Actual Behavior:**

**Steps to Reproduce:**

**Important Factoids:**

References:**

**Comment by calvn** [comment]
If you want the [CLI to read from a file](https://www.vaultproject.io/docs/commands/index.html#files), you'll need to add an `@` to the beginning of the path, like so:

```
$ vault write aws/roles/my-role policy=@EmptyFile.json
```

**Comment by kodati9** [comment]
even if i insert @ i am getting the same error.

Thanks,
regards,
Rahul K.

**Comment by calvn** [comment]
Can you post the output that you got from the terminal as well as the contents of EmptyFile.json?

**Comment by calvn** [comment]
I can't seem to reproduce the issue:

```
$ cat /tmp/sample.json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "ec2:*",
      "Resource": "*"
    }
  ]
}

$ vault write aws/roles/my-role policy=@/tmp/sample.json
Success! Data written to: aws/roles/my-role
```

**Comment by kodati9** [comment]
contents of my file :
 "Version": "2012-10-17",
 "Statement": [
    {
      "Sid": "Stmt1426528957000",
      "Effect": "Allow",
      "Action": [
        "ec2:*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]

**Comment by calvn** [comment]
You are missing encompassing brackets around the body of your content (The first and last brackets in my sample policy).

**Comment by kodati9** [comment]
thankyou resolved the issue

**Comment by kodati9** [comment]
Hi Huang,

Iam trying to setup username and password in windows environment and the
command doesnt work


C:\Users\U14251\Downloads\vault_0.10.2_windows_amd64>vault login
-method=userpass username=foo password=bar
Error authenticating: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/userpass/login/foo
Code: 404. Errors:

* no handler for route 'auth/userpass/login/foo'

C:\Users\U14251\Downloads\vault_0.10.2_windows_amd64>


Could you please help me

Thanks,

Rahul K.

**Comment by chrishoffman** [comment]
@kodati9 It appears you have not mounted or configured the userpass auth method. See https://www.vaultproject.io/docs/auth/userpass.html#configuration.
