### ISSUE TITLE
Configure certificates used for Consul and Nomad Secrets Backend

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/vault#4800]
Currently, if we have TLS enabled for Nomad and Consul, the Nomad and Consul secrets engine will fail with `x509: certificate signed by unknown authority` unless we install the CA used to sign the certificates for Nomad/Consul to the system bundle. This can be a little messy if Vault itself was used as the CA to generate the certificates for Nomad/Consul (using the PKI backend).

It would be great if Nomad/Consul secrets backend allows us to configure the CA used to interact with Nomad/Consul. 

In addition, if Nomad and Consul both have client certificates enabled, this will also fail. 

Example error message:

```
Error revoking lease nomad/creds/readonly/xxx: Error making API request.

URL: PUT https://vault.xxx.xxx/v1/sys/leases/revoke/nomad/creds/readonly/xxx
Code: 400. Errors:

* failed to revoke entry: resp: (*logical.Response)(nil) err: Delete https://nomad.service.consul:4646/v1/acl/token/xxx: x509: certificate signed by unknown authority

```

**Comment by jefferai** [comment]
Wouldn't you want to install it as part of the CA bundle on your systems anyways? I would assume other clients of Nomad and Consul would need it.

**Comment by lawliet89** [comment]
That's a possibility yes.

 It would be nice to not have to install it of course. Also that would not solve the case where Vault needs to present a client certificate.

**Comment by ac-astuartkregor** [comment]
Hi folks, I've run into this issue as well. I have configured consul to require client certificates for HTTPS communication, but I am unable to specify a certificate & key in the backend config. It'd be great if this functionality could be made available.

**Comment by jsmilani** [comment]
I am encountering the "x509: certificate signed by unknown authority" when using the Consul Secrets Engine with SSL on my local docker dev setup. Ironically, Vault generated the CA cert that Consul is trying to use, but Vault doesn't seem to trust its own certs.

I am using a docker image for vault so it is actually really hard to add a CA certificate at runtime. I am happy to add the '-tls-skip-verify' option in my dev env vault arguments (which I have), but that vault option doesn't seem to apply to the Server Consul Secrets Engine.

If you are going to add CA cert info to the Consul Secret's engine configs then you might as well add a tls_skip_verify option as well. Another solution for me would to add a way for Vault to trust its own CA certificates.

**Comment by jsynowiec** [comment]
@jefferai I have the self signed CA installed on the system (I can use curl just fine) but Vault still refuses to validate the Consul certificate when I'm trying to use Consul Secrets Engine. As a backend, Consul works.

```
$ curl https://127.0.0.1:8200/v1/acl/token
{"errors":["missing client token"]}

$ vault read consul/creds/service-ro
Error reading consul/creds/service-ro: Error making API request.

URL: GET https://127.0.0.1:8200/v1/consul/creds/service-ro
Code: 400. Errors:

* Put https://127.0.0.1:8501/v1/acl/token: x509: certificate signed by unknown authority
```

Shouldn't Vault use the system CA bundle?

**Comment by filintod** [comment]
I have not tested but looking at https://github.com/hashicorp/vault/blob/278bdd1f4e3ca4653f4a11d8591ecebeafb196bd/builtin/logical/consul/client.go and with previous experiences with consul I have found that setting the CONSUL_CACERT, CONSUL_CLIENT_CERT and CONSUL_CLIENT_KEY is enough to so when the NewClient method is called these values are use as default.  Nomad has similar vars NOMAD_CACERT, NOMAD_CLIENT_CERT and NOMAD_CLIENT_KEY.  But it would be nice if those were added to the vault consul config https://github.com/hashicorp/vault/blob/278bdd1f4e3ca4653f4a11d8591ecebeafb196bd/builtin/logical/consul/path_config.go and the other files on that folder

**Comment by michelvocks** [comment]
https://github.com/hashicorp/vault/pull/8253 & https://github.com/hashicorp/vault/pull/8083 were merged. This allows you to define TLS options per secret backend configuration.
