### ISSUE TITLE
Initialize vault with user provided keys

### ISSUE THREAD

**Issue by raoofm** [hashicorp/vault#4805]
**Is your feature request related to a problem? Please describe.**
I was wondering why there is no option to provide your own keys to initialize vault. It helps in simplifying the task of distributing keys and auto unseal multiple clusters containing replicated data. Also to switch over if a data store is unavailable.

**Describe the solution you'd like**
An option to provide set of keys, similar to a way we provide pgp for vault init.

**Comment by rotorcowboy** [comment]
Vault derives its key shares with [Shamir's Secret Sharing algorithm](https://en.wikipedia.org/wiki/Shamir%27s_Secret_Sharing). They aren't sets of random bytes, but instead can be used in parts to reconstruct a single master key. If you wanted to provide your own keys, they would have to be generated in this way.

To each their own, but I would recommend against using the same set of keys for multiple Vault instances, as it increases the operational burden of [rekeying](https://www.vaultproject.io/guides/operations/rekeying-and-rotating.html) your vaults. If you absolutely must have the same set of keys, though, I _think_ you could initialize a single empty storage backend, then copy the whole thing for use with other instances.

**Comment by jefferai** [comment]
It's not possible -- as @rotorcowboy said, we derive unseal keys using Shamir's Secret Sharing against a mster key -- and it's pretty against the whole security model of Vault to specify your own master key, so we don't plan to support it.
