### ISSUE TITLE
vault dev server doesn't return secret via HTTP API

### ISSUE THREAD

**Issue by max7z** [hashicorp/vault#4808]
**Describe the bug**

Can't get secret/foo via curl

**To Reproduce**
1. run dev server
```
vault server -dev

You may need to set the following environment variable:

    $ export VAULT_ADDR='http://127.0.0.1:8200'

The unseal key and root token are displayed below in case you want to
seal/unseal the Vault or re-authenticate.

Unseal Key: a5jBIQOi9hPcujXaSUqIYA2602csRh0uOJ3z856dh4s=
Root Token: b84fad72-ff02-a9c6-96c9-31b9cee50dbf

```

2. get secret/foo via curl
`curl -H "X-Vault-Token: b84fad72-ff02-a9c6-96c9-31b9cee50dbf" -X GET http://127.0.0.1:8200/v1/secret/foo`

3. See error
`{"request_id":"d0e71aea-29e1-9460-877e-860a04b9f220","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv get' for this operation."],"auth":null}
`

**Expected behavior**
But it works fine via vault cli
```
vault kv get secret/foo
====== Metadata ======
Key              Value
---              -----
created_time     2018-06-21T07:53:28.52592663Z
deletion_time    n/a
destroyed        false
version          1

=== Data ===
Key    Value
---    -----
bar    baz
```

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key             Value
---             -----
Seal Type       shamir
Sealed          false
Total Shares    1
Threshold       1
Version         0.10.3
Cluster Name    vault-cluster-2926fc70
Cluster ID      a5ca402b-c52a-4894-952b-d59cfd2ddab7
HA Enabled      false

```* Vault CLI Version (retrieve with `vault version`):

`Vault v0.10.3 ('533003e27840d9646cb4e7d23b3a113895da1dd0')`
* Server Operating System/Architecture:
macOS 10.13.5

**Comment by briankassouf** [comment]
The API path for a v2 kv mount is actually `/v1/secret/data/foo` 

API docs: https://www.vaultproject.io/api/secret/kv/kv-v2.html#read-secret-version

**Comment by anirvan-majumdar** [comment]
It would _really_ help if the point about having to use `data` in the path is mentioned in a callout. Just spent an hour trying to debug this issue across the CLI/Python client/Web UI.

**Comment by jefferai** [comment]
It's an entire section: https://www.vaultproject.io/docs/secrets/kv/kv-v2.html#acl-rules

**Comment by anirvan-majumdar** [comment]
Agreed — I only meant to highlight that the small detail of including `data` in the path is something that can easily get missed, when someone goes through the Tutorial's (non-advanced) section. A simple callout in the KV (v2) doc pointing out that `data` is expected in the path would be helpful IMO.

**Comment by vaddisrinivas** [comment]
Although i was trying to hit the /secret/data/mysecret it was returning me {errors:[]} any suggestions/help?

thanks in advance

**Comment by troyfolger** [comment]
@vaddisrinivas you are probably using v2 instead of v1 in your query
