### ISSUE TITLE
ui: copy to clipboard feature

### ISSUE THREAD

**Issue by lrstanley** [hashicorp/vault#4814]
Right now in the web UI, copying credentials out isn't great. There are no box-boundaries around field variables, so you can't easily double-click things to select the value. Password managers, amongst one of the comparable types of utilities, generally have a way of copying to clipboard without exposing the original variable.

One of the primary benefits I think the web UI could see, is the ability to 'copy to clipboard' for all field keys and values. This, in combination with the most recent addition of obfuscated-by-default in 0.10.3 (haven't tried yet!), allows someone to copy credentials without seeing them, or potentially exposing them to people around them visually. You'd additionally want some toast notification letting the user know it was successfully copied to the clipboard.

This seems like a defacto solution, across many password managers, and I think would be a useful adoption to Vault.

One other note.. I've seen this in KeePass, however with one additional feature. KeePass will wipe the clipboard after something was copied to it, after a specified duration. E.g. after 10 seconds, the clipboard is blanked out assuming the clipboard contents is still the same as what was copied. Unfortunately, most browsers don't support (and for good reason) reading from the clipboard (which is needed, to know if the clipboard still has the content, or has other copied content). The benefit if this were possible, is that it prevents credentials from accidentally being pasted into other windows/prompts/chats/etc. This could still be possible by sending blank text to the clipboard, but it could become irritating if the user copied something else, within those e.g. 10 seconds.

**Comment by meirish** [comment]
We noticed that we didn't cover everyone's use case in the "obfuscate" ticket and are planning on adding copy buttons to those as well!

**Comment by DawerRafi** [comment]
+1

**Comment by derBroBro** [comment]
The feature would be also quite handy for us. Specialiy if vault gets use as a password manager this prevents sloppy leaking of credentials (in webex etc.).

**Comment by Garath620** [comment]
+1

**Comment by meirish** [comment]
fixed in https://github.com/hashicorp/vault/pull/5627 and https://github.com/hashicorp/vault/pull/5657 !
