### ISSUE TITLE
Contradicting statements in replication guide regarding tokens

### ISSUE THREAD

**Issue by raoofm** [hashicorp/vault#4815]
[Here](https://www.vaultproject.io/docs/enterprise/replication/index.html) it mentions that
> In performance replication, secondaries keep track of their own tokens and leases but share the underlying configuration, policies, and supporting secrets (K/V values, encryption keys for transit, etc).

But below it in the capabilities comparison table between DR and Perf on the same page it mentions
> Mirrors the tokens and leases for applications and users interacting with the primary cluster
DR - Yes
Perf - No. Secondaries use the primary as the source of truth and pass token requests to the primary. When the secondary is promoted, applications must re-auth tokens and obtain new leases from the newly-promoted primary.

**Comment by chrishoffman** [comment]
Thanks for the report, fixed in 41ec5bc61d4e97673f09b3f2d33e69936ee8e837.
