### ISSUE TITLE
ldap case sensitivity

### ISSUE THREAD

**Issue by lrstanley** [hashicorp/vault#4820]
LDAP logins, both within the web UI and via the CLI, are checked against the internal mapping without being converted to lower case first. Most LDAP implementations will lowercase compare the value to the internal mapping, as case sensitivity generally doesn't matter to most LDAP/AD backends from my understanding.

**To Reproduce**
Store user policy info in e.g. `auth/ldap/users/somelowercaseusername`. Attempt to login with `SomeLowercaseUsername` as the username.

**Expected behavior**
Username is lowercased (normalized) automatically when saving to `auth/ldap/users/<user>` and the user is lowercased (normalized) when checking for the username in `auth/ldap/users/`.

**Environment:**
* Vault Server Version: 0.10.2
* Vault CLI Version: 0.10.2
* Server Operating System/Architecture: linux amd64

**Additional context**
In environments where AD is used, and LDAP is the protocol at which AD is contacted, it's common Windows behavior to have capital letters in the username. E.g. LStanley vs lstanley like you'd see in linux. So most users who only usually use Windows, don't think to try lowercase. In this instance, they'd be told they have no policy access, when they in fact do.

**Comment by jefferai** [comment]
Does https://www.vaultproject.io/api/auth/ldap/index.html#case_sensitive_names do what you need? Or is there a place where you want it to be case insensitive but it isn't?

Note that if you've been using Vault for a while, when we added that option we grandfathered in existing implementations so it might be set for you without you realizing it.

**Comment by lrstanley** [comment]
Ah, I didn't see that parameter. I believe that should resolve the issues, given we applied the LDAP configuration just before we upgraded to 0.10.x. Will test it out and re-open if I still notice issues. Thanks!
