### ISSUE TITLE
Unsorted list of secrets in UI for Generic V2

### ISSUE THREAD

**Issue by alexandersusha** [hashicorp/vault#4826]
**Describe the bug**
Vault UI displays an unsorted list of secrets for Generic V2 secret store.
![unsorted_secret_list_0_10_3_ui](https://user-images.githubusercontent.com/17471309/41850564-a9efc88a-788d-11e8-89cc-367885bc0339.PNG)

**Expected behavior**
The list of secret should be sorted alphabetically.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.3

**Comment by briankassouf** [comment]
fixed via #4845
