### ISSUE TITLE
KV2 Read Secret Version returns latest only?

### ISSUE THREAD

**Issue by Dogers** [hashicorp/vault#4830]
**Describe the bug**
I'm trying to get Read Secret Version working, following https://www.vaultproject.io/api/secret/kv/kv-v2.html#read-secret-version, however it appears to be ignoring the "version" statement I'm sending it, requesting an older version?

**To Reproduce**
(this is summarised, so apologies if I miss something out, but the root token is being provided in the header)

Secret has three versions: 

```
GET /v1/secret/metadata/mysecret HTTP/1.1
{
	"request_id": "3270633c-095c-91c0-c07c-c49dbfd8ca9c",
	"lease_id": "",
	"renewable": false,
	"lease_duration": 0,
	"data": {
		"cas_required": false,
		"created_time": "2018-06-25T15:30:33.880883029Z",
		"current_version": 3,
		"max_versions": 0,
		"oldest_version": 0,
		"updated_time": "2018-06-25T15:41:06.145555048Z",
		"versions": {
			"1": {
				"created_time": "2018-06-25T15:30:33.880883029Z",
				"deletion_time": "",
				"destroyed": false
			},
			"2": {
				"created_time": "2018-06-25T15:35:55.116946252Z",
				"deletion_time": "",
				"destroyed": false
			},
			"3": {
				"created_time": "2018-06-25T15:41:06.145555048Z",
				"deletion_time": "",
				"destroyed": false
			}
		}
	},
	"wrap_info": null,
	"warnings": null,
	"auth": null
}
```
Request version 1, v3 returned:
```
GET /v1/secret/data/mysecret HTTP/1.1
{
	"version": 1
}
--
{
	"request_id": "99e030dd-723c-ef19-641a-da90a272e4e7",
	"lease_id": "",
	"renewable": false,
	"lease_duration": 0,
	"data": {
		"data": {
			"foo": "coo",
			"zip": "bop"
		},
		"metadata": {
			"created_time": "2018-06-25T15:41:06.145555048Z",
			"deletion_time": "",
			"destroyed": false,
			"version": 3
		}
	},
	"wrap_info": null,
	"warnings": null,
	"auth": null
}
```

**Expected behavior**
v1 of the secret should be returned. I'm unable to check via CLI as there's no example and I've been unable to guess the format thus far in case there is one!

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.3
* Vault CLI Version (retrieve with `vault version`): 0.10.3
* Server Operating System/Architecture: CentOS 7 x64

**Comment by Dogers** [comment]
Okay, it works on the CLI, just found the command! Just the web that's an issue?
```
vault kv get -version=1 secret/mysecret
====== Metadata ======
Key              Value
---              -----
created_time     2018-06-25T15:30:33.880883029Z
deletion_time    n/a
destroyed        false
version          1

=== Data ===
Key    Value
---    -----
foo    bar
zip    zap
```

**Comment by briankassouf** [comment]
@Dogers the version parameter should be a query parameter.

Try `GET /v1/secret/data/mysecret?version=1`

**Comment by Dogers** [comment]
@briankassouf woops, you're absolutely right, I probably should have tried/guess that! Can a small clarification be added to the docs to show this is what you're meant to do? This is the first API call I've come across that needs a query parameter..

Method | Path | Produces
-- | -- | --
GET | /secret/data/:path?version=x | 200 application/json
