### ISSUE TITLE
HAproxy as Load Balancing Using External Load Balancer 

### ISSUE THREAD

**Issue by Alexvianet** [hashicorp/vault#4833]
https://www.vaultproject.io/guides/operations/reference-architecture.html#load-balancing 
include Example Consul Template for the above HAProxy block that is not working.

my HAProxy(101.233.170.42) configuration:
```
global
user vcap
group vcap
maxconn 64000
stats socket /var/vcap/sys/run/haproxy/stats.sock
defaults
log global
retries 3
option redispatch
maxconn 4096
timeout connect 5000
timeout client 10000
timeout server 10000

listen vault
bind 101.233.170.42:8200
balance roundrobin
option httpchk GET /v1/sys/health
server node0 101.233.168.55:8200 check
server node1 101.233.168.56:8200 check
server node2 101.233.168.57:8200 check
```
also https tested,
```
listen vault
bind 101.233.170.42:8200 ssl cert /path 
balance roundrobin
option httpchk GET /v1/sys/health
server node0 101.233.168.55:8200 check
server node1 101.233.168.56:8200 check
server node2 101.233.168.57:8200 check
```

and recive:

[root@sol-usgp2bosh01-d ~]# curl   https://101.233.170.42:8200/v1/sys/health -k
curl: (35) Encountered end of file
[root@sol-usgp2bosh01-d ~]# vault status
Error checking seal status: Get https://101.233.170.42:8200/v1/sys/seal-status: EOF

**Comment by chrishoffman** [comment]
What do your vault server logs say? Also, is the service showing up as healthy from HAProxy?

**Comment by Alexvianet** [comment]
@chrishoffman if U have forking haproxy configuration please provide it for example, i have made only tcp working but i need `option httpchk GET /v1/sys/health`

**Comment by Alexvianet** [comment]
my fault I have found a solution please add it to documentation that, to make it work needs to add ssl to each backend:
```
listen vault
bind 101.233.170.42:8200 ssl cert /path 
balance roundrobin
option httpchk GET /v1/sys/health
server node0 101.233.168.55:8200 check ssl verify
server node1 101.233.168.56:8200 check ssl verify
server node2 101.233.168.57:8200 check ssl verify
```

![screenshot from 2018-06-27 16-47-41](https://user-images.githubusercontent.com/17483589/41978358-5b20b4e6-7a2a-11e8-80dc-5f29e69e27f2.png)

**Comment by SEJeff** [comment]
Just adding to this comment as I wanted to have haproxy load balance vault while also having vault terminate its own tls for obvious security reasons:

```
    # Vault has a http health endpoint on /v1/sys/health that returns different http codes
    # depending on the status of the running vault instance.
    #
    # See: https://www.vaultproject.io/api/system/health.html#read-health-information
    #
    #    * 200 if initialized, unsealed, and active
    #    * 429 if unsealed and standby
    #    * 472 if data recovery mode replication secondary and active
    #    * 473 if performance standby
    #    * 501 if not initialized
    #    * 503 if sealed

    # Redirect http --> https
    frontend vault_http
      mode http
      # bind to the ip you want to give clients
      bind 1.2.3.6:80
      redirect scheme https code 301 if !{ ssl_fc }

    # Primary https listener
    frontend vault_https
      mode tcp
      log global
      timeout client 30000
      # bind to the ip you give to clients
      bind 1.2.3.6:443
      description Vault over https
      default_backend vault_https
      option tcplog

    backend vault_https
      mode tcp
      timeout check 5000
      timeout server 30000
      timeout connect 5000
      option httpchk GET /v1/sys/health
      server vault-server1 1.2.3.4:8200 check check-ssl verify none inter 5000
      server vault-server2 1.2.3.5:8200 check check-ssl verify none inter 5000
      server vault-server3 1.2.3.6:8200 check check-ssl verify none inter 5000
```

It will likely help the next person who is googling and finds this.

**Comment by robert-gomes** [comment]
@SEJeff with this config are you able to see the client's IP in the audit log?

**Comment by Slapper** [comment]
Hello,

Based on @SEJeff  haproxy config i am using this extra line bellow on the backend section : 

```
 http-check expect rstatus (200|429)
```
With this line you will have all the nodes on healthy status  based on this status code : 

> The default status codes are:
> 
> 200 if initialized, unsealed, and active
> 429 if unsealed and standby
> 472 if disaster recovery mode replication secondary and active
> 473 if performance standby
> 501 if not initialized
> 503 if sealed

More info here : https://www.vaultproject.io/api-docs/system/health
