### ISSUE TITLE
GCP Secrets Engine API: add expiration date to the Generate OAuth2 Access Token endpoint

### ISSUE THREAD

**Issue by medzin** [hashicorp/vault#4848]
`lease_duration` field in Vault response its not very useful, because it shows only for which duration the token was issued (which is relative). I believe that API should return the absolute expiry date of the token. Now you can not tell when it expires without storing information when the Vault's API was called.

```json
{
  "request_id":"<uuid>",
  "lease_id":"gcp/token/my-token-roleset/<uuid>",
  "renewable":false,
  "lease_duration":3599,
  "data": {
    "token":"ya29.c.Elp5Be3ga87..."
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}
```

Adding a `expiration_date` would make the API response more usable.

**Comment by chrishoffman** [comment]
The expiration time can easily be calculated by using the current time + lease duration. Additionally, information about the lease including when it was created, last renewed, and expiration can all be viewed using the lease lookup endpoints https://www.vaultproject.io/api/system/leases.html#read-lease.
