### ISSUE TITLE
Feature request (app-id): support for one user-id to many app-ids mapping

### ISSUE THREAD

**Issue by consultantRR** [hashicorp/vault#485]
It would be really great if `auth/app-id/map/user-id/foo` (for example) could hold multiple app-id values and the app-id auth backend would consider any one of them to be valid for login with that user-id.

So, essentially, in this example, the app-id values "bar", "baz", and "boo" could all me mapped to the "foo" user-id simultaneously, and any of the following three user-id/app-id pairs would return a valid auth token (with whichever policy the app-id that was used had been mapped to):

`{"app_id": "foo", "user_id": "bar"}`
`{"app_id": "foo", "user_id": "baz"}`
`{"app_id": "foo", "user_id": "boo"}`

I can think of a number of use cases here, one of which is a Docker environment, in which a Docker host is hosting multiple containers of different application types. In this scenario, I'd like each container to be able to auth to Vault using the app-id method by providing an app-id (unique to each container type) and a derivable user-id (common to the host on which all the containers are running).

Essentially, it would be like saying, "this container is authorized to auth to Vault when running on this host, using an app-id that it knows, and a user-id that it doesn't know on its own, but that the host knows."

Perhaps `auth/app-id/map/user-id/*` paths could be enhanced to store an array of values, and the app-id auth method could be enhanced to support mappings of a user-id to all app-ids in the array?

**Comment by consultantRR** [comment]
Wow, it actually appears this already works, exactly as desired, simply by providing comma-separated app-ids in the value when writing to the `auth/app-id/map/user-id/*` path:

```
# vault write auth/app-id/map/app-id/my-app-id-1 value=policy-1
Success! Data written to: auth/app-id/map/app-id/my-app-id-1

# vault write auth/app-id/map/app-id/my-app-id-2 value=policy-2
Success! Data written to: auth/app-id/map/app-id/my-app-id-2

# vault write auth/app-id/map/app-id/my-app-id-3 value=policy-3
Success! Data written to: auth/app-id/map/app-id/my-app-id-3

# vault write auth/app-id/map/app-id/my-app-id-4 value=policy-4
Success! Data written to: auth/app-id/map/app-id/my-app-id-4

# vault write auth/app-id/map/user-id/my-user-id-1 value=my-app-id-1,my-app-id-2,my-app-id-3
Success! Data written to: auth/app-id/map/user-id/my-user-id-1

# curl -X PUT -d '{ "app_id": "my-app-id-1", "user_id": "my-user-id-1" }' http://localhost:8200/v1/auth/app-id/login
{"lease_id":"","renewable":false,"lease_duration":0,"data":null,"auth":{"client_token":"e413d0f9-ef15-38e4-2b29-ba0cc14be10f","policies":["policy-1"],"metadata":{"app-id":"sha1:6542803bc17ed64f39f983e1bbfaa4b595924cac","user-id":"sha1:dc8d20435d87f02418991eb69e53b2b5b087dfee"},"lease_duration":2592000,"renewable":false}}

# curl -X PUT -d '{ "app_id": "my-app-id-2", "user_id": "my-user-id-1" }' http://localhost:8200/v1/auth/app-id/login
{"lease_id":"","renewable":false,"lease_duration":0,"data":null,"auth":{"client_token":"233b2e47-6153-b475-3d63-fb2b94a39fa3","policies":["policy-2"],"metadata":{"app-id":"sha1:da58784962247a5bf79d1fba0d53a2cfdd45d86d","user-id":"sha1:dc8d20435d87f02418991eb69e53b2b5b087dfee"},"lease_duration":2592000,"renewable":false}}

# curl -X PUT -d '{ "app_id": "my-app-id-3", "user_id": "my-user-id-1" }' http://localhost:8200/v1/auth/app-id/login
{"lease_id":"","renewable":false,"lease_duration":0,"data":null,"auth":{"client_token":"b15051ad-cc11-a9d8-e724-9acd074e3bfa","policies":["policy-3"],"metadata":{"app-id":"sha1:7abe416b7e62343bf05c8c154347e66f05062ac7","user-id":"sha1:dc8d20435d87f02418991eb69e53b2b5b087dfee"},"lease_duration":2592000,"renewable":false}}
 
# curl -X PUT -d '{ "app_id": "my-app-id-4", "user_id": "my-user-id-1" }' http://localhost:8200/v1/auth/app-id/login
{"errors":["invalid user ID or app ID"]}

# curl -X PUT -d '{ "app_id": "my-app-id-1,my-app-id-2,my-app-id-3", "user_id": "my-user-id-1" }' http://localhost:8200/v1/auth/app-id/login
{"errors":["invalid user ID or app ID"]}
```

Fantastic. Maybe I will submit a documentation enhancement PR so that this is clear.

**Comment by consultantRR** [comment]
Submitted PR #486

**Comment by l8nite** [comment]
I think this story can be closed.

**Comment by jefferai** [comment]
thanks!

**Comment by consultantRR** [comment]
Actually, before this fades into the ether, I want to mention a related use case which I wish was possible in Vault in a one user-id to many app-ids mapping scenario:

The ability to implement different policies for a single app-id based on the user-id it is paired with.

I can elaborate if helpful, or perhaps it would be best to open a separate issue, although it is actually a nuance of the topic in this Issue.

**Comment by jefferai** [comment]
I think opening a separate issue would be best.
