### ISSUE TITLE
Improve Lease Loading

### ISSUE THREAD

**Issue by michaeljs1990** [hashicorp/vault#4857]
Currently when starting a vault server with lots of leases it rapidly requests all the keys from the backend. It looks like this is happening inside of the following function currently. Additionally it looks like this also fires once every minute. In my current metrics I see huge spikes every minute where it requests the number of active leases.

```
func (m *ExpirationManager) loadEntryInternal(leaseID string, restoreMode bool, checkRestored bool) (*leaseEntry, error)
```

Many backends support transactional/bulk fetches which could greatly reduce the load on backends when starting and as well when operation. I see that a Transactional backend already exists but it doesn't look like it's used for anything outside of the seal un wrapper. It would be nice to reduce the performance needed since we could have a very large number of tokens in our system.

It looks like this is also somewhat mentioned here #4803. I would be willing to work on this once I finish up with the current MySQL HA changes.

**Comment by vishalnayak** [comment]
There has been significant changes to loading of leases since this issue was filed. Please try using latest Vault and let us know your thoughts!
