### ISSUE TITLE
Config option to change HTML <title> string in vault ui

### ISSUE THREAD

**Issue by bitc** [hashicorp/vault#4858]
Hi, it would be cool if there were a way to change the "title" of the HTML vault ui.

Right now it always says "Vault". I would like to change it to include the name of the organization

**Comment by meirish** [comment]
Hi! sorry I realize this was opened a while ago - but there's quite a few things we'd need to account for when doing this:

We want to change the title of the page as you navigate through the UI as well, but in addition to that - where do we store that string? Currently there's the cluster name which you can configure in your Vault config, and we could use that, but on the enterprise side there's also namespaces which may make sense to include there as well.

**Comment by aphorise** [comment]
What the status of this request - are there any related customisation that are planned for at all?

Also I'm wondering why a custom build can not be done already by operators without any text change that they may be after?

**Comment by bitc** [comment]
I don't use vault anymore so I don't know if this is still a relevant issue or not

**Comment by aphorise** [comment]
Thank you for the update @bitc - I'll close this request as it's no longer relevant for you and there are already approaches to achieving this.

PS - Seems relevant to #6584
