### ISSUE TITLE
localhost listener causes consul DNS to point to localhost only

### ISSUE THREAD

**Issue by cbednarski** [hashicorp/vault#4859]
I'm using 0.10.1 but I have not seen any relevant changes in 0.10.3

I have configured multiple listeners for vault:

```
listener "tcp" {
    address     = "127.0.0.1:8200"
    tls_disable = 1
}

listener "tcp" {
    address     = "10.8.0.5:8200"
    tls_disable = 1
}
```

Whenever the `127.0.0.1` listener is used, Consul DNS returns `127.0.0.1` for `vault.service.consul`, thus rendering it useless. If I remove the localhost listener the expected `10.8.0.5` IP is returned from Consul DNS instead.

The reason I am using both listeners is so the vault instance is available via the shell without having to specify the host IP (e.g. in bash scripts).

I have only glanced at the relevant code so I don't know if this is feasible, but I propose that the consul check registration prefer a non-loopback address if more than one listener is configured. I can make the change if this works for you. Cheers!

**Comment by briankassouf** [comment]
Does configuring the [api_addr](https://www.vaultproject.io/docs/configuration/index.html#api_addr) and [cluster_addr](https://www.vaultproject.io/docs/configuration/index.html#cluster_addr) solve this?

**Comment by cbednarski** [comment]
Hi Brian, it does. Thanks! I'll make a PR for the docs.
