### ISSUE TITLE
Vault 10.3 with storage backend ETCD 3.2.18 TLS handshake timeout on startup

### ISSUE THREAD

**Issue by philippwiesner** [hashicorp/vault#4861]
**Describe the bug**
I have setup an ETCD Cluster with version 3.2.18 which uses TSL/SSL encrypted communication. Accessing the cluster via etcdctl works without problems, however, when trying to start the Vault server with the ETCD as storage backend defined i just get:

```
[root@etcd3 vault]# vault server -config /etc/hashi_vault/config.hcl 
Error initializing storage of type etcd: failed to get etcd API version: client: etcd cluster is unavailable or misconfigured; error #0: net/http: TLS handshake timeout
; error #1: net/http: TLS handshake timeout
; error #2: net/http: TLS handshake timeout
```

For the ETCD authentication is enabled and the client certificate admin.pem uses the same DN as the user configured in etcd:
```
[root@etcd3 hashi_vault]# ETCDCTL_API=3 etcdctl --cert=admin.pem --key=admin.key --endpoints=[etcd1.devops.com:2379,etcd2.devops.com:2379,etcd3.devops.com:2379] member list -w table
+------------------+---------+------------------+-------------------------------+-------------------------------+
|        ID        | STATUS  |       NAME       |          PEER ADDRS           |         CLIENT ADDRS          |
+------------------+---------+------------------+-------------------------------+-------------------------------+
| 24e209e7120d721c | started | etcd2.devops.com | https://etcd2.devops.com:2380 | https://etcd2.devops.com:2379 |
| a7c0a6d3ae90c4bb | started | etcd1.devops.com | https://etcd1.devops.com:2380 | https://etcd1.devops.com:2379 |
| b34a4f4e123561c4 | started | etcd3.devops.com | https://etcd3.devops.com:2380 | https://etcd3.devops.com:2379 |
+------------------+---------+------------------+-------------------------------+-------------------------------+
```

When i'm trying to change the ETCD endpoints to their dns names, vault already failes with the message Bad Gateway on all endpoints. The same goes when using the DNS Discovery SRV domain entry. Which works perfectly fine for etcd itself.

**Expected behavior**
Vault server should at least start.

**Environment:**
* Vault v0.10.3 ('c69ae68faf2bf7fc1d78e3ec62655696a07454c7')
* Vault v0.10.3 ('048295c54ade5a6a1c46e96a9b94119c0ab673c3')
* CentOS Linux release 7.5.1804 (Core) 
* ETCD 3.2.18 from Centos Repository

Vault server configuration file(s):

```hcl
listener "tcp" {
        address = "192.168.50.13:8200"
        tls_disable = "true"
}

storage "etcd" {
        address = "https://192.168.50.11:2379,https://192.168.50.12:2379,https://192.168.50.13:2379"
        ha_enabled = "true"
        path = "vault/prod"
        etcd_api = "v3"
        sync = "false"
        redirect_addr = "http://etcd3.devops.com:8200"
        cluster_addr = "http://etcd3.devops.com:8200"
        tls_ca_file = "/etc/pki/tls/certs/ca.pem"
        tls_cert_file = "/etc/hashi_vault/admin.pem"
        tls_key_file = "/etc/hashi_vault/admin.key"
}
```

**Additional context**

**Comment by philippwiesner** [comment]
I have solved the issue, the problem was that the cluster is currently running on local vagrant machines which are behind a proxy.

Looking through the strace output showed that vault tried to connect to etcd via the proxy which cannot work. Adding the instances to no_proxy solved the issue.

**Comment by briankassouf** [comment]
Glad you solved it!
