### ISSUE TITLE
Vault on ppc64le Platform

### ISSUE THREAD

**Issue by AnitaNayak** [hashicorp/vault#4864]
I tried to build Vault on ppc64le. I just modified the build script to add platform ppc64le and tried building. It built successfully. In Make test few TCs failed with consul. Then I tried to create the Docker Image. Later when I am trying to deploy vault image with ibmcom/consul-ppc64le:0.9.0 version, I am getting error "ERR_CONNECT_FAIL". I am not getting any clue why it failing.  Does anyone have successfully tested vault on ppc64le plat after build. 

Thanks

**Comment by jefferai** [comment]
Unfortunately this is not a platform we test on. If you want to gather any community feedback, please use the mailing list. Thanks!

**Comment by AnitaNayak** [comment]
Could you please share the mailing list id?
