### ISSUE TITLE
How do I list all users previously created under auth/userpass/users?

### ISSUE THREAD

**Issue by juliohm1978** [hashicorp/vault#4866]
Can't seem to find this anywhere.

I can create users with

```
vault write auth/userpass/users/myuser password=***
```

But, once they are created, they disappear into a void and I am unable to query the API to list me all users. By common sense, these usernames and passwords eventually accumulate. With time, the need to review and revoke seems ovious. How can I find users that were previously created?

**Comment by chrishoffman** [comment]
You can make a LIST request on `auth/userpass/users`. See https://www.vaultproject.io/api/auth/userpass/index.html#list-users.
