### ISSUE TITLE
Cannot use api/client/logical to write onto v2 K/V

### ISSUE THREAD

**Issue by mvisonneau** [hashicorp/vault#4867]
I am trying to get my `golang` app compliant with the v2 of the K/V store. According to the documentation it only supports POST requests in order to write new secrets. So far I was using the logical client in order to make the requests, however it looks like it hardcodes a PUT request : 

https://github.com/hashicorp/vault/blob/master/api/logical.go#L106

Is there any thing/alternative I am missing here ?

**Comment by chrishoffman** [comment]
POST and PUT are both accepted and are treated as synonymous in Vault's API. 

See documentation here https://www.vaultproject.io/api/index.html#reading-writing-and-listing-secrets:
> Vault currently considers PUT and POST to be synonyms. Rather than trust a client's stated intentions, Vault backends can implement an existence check to discover whether an operation is actually a create or update operation based on the data already stored within Vault.

**Comment by mvisonneau** [comment]
Indeed 🤦‍♂️
