### ISSUE TITLE
NewClient no longer lets you specify a configuration

### ISSUE THREAD

**Issue by joshrendek** [hashicorp/vault#4869]
**Describe the bug**

When using the go client API, `NewClient` doesn't let you specify a config without `DefaultConfig` being called first. This prevents you from making a client for local dev work if you don't have a client key/cert. 

This change happened in https://github.com/hashicorp/vault/pull/3508/files#diff-5b4f052d557bcd66021311759582f972R289

**To Reproduce**

```
	config := &vault.Config{Address: os.Getenv("VAULT_ADDR")}
	client, err := vault.NewClient(config)
	if err != nil {
		fmt.Println(err)
	}
```

Error: `error encountered setting up default configuration: both client cert and client key must be provided`

**Expected behavior**

The ability to specify my own configuration without having to use `DefaultConfig`

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault v0.10.3 ('533003e27840d9646cb4e7d23b3a113895da1dd0')
* Vault CLI Version (retrieve with `vault version`): Vault v0.10.3 ('533003e27840d9646cb4e7d23b3a113895da1dd0')
* Server Operating System/Architecture: OSX (local)

Vault server configuration file(s):

```hcl
vault server -dev -dev-root-token-id=root
```

**Additional Context**

I can provide the fix for this just wanted to verify that the old behavior is the correct one (checking for a nil config and only then using `DefaultConfig`)

**Comment by joshrendek** [comment]
@jefferai which line of code in the reproduction steps is setting that?

**Comment by jefferai** [comment]
My guess is that you have an environment variable set.

**Comment by jefferai** [comment]
```
$ cat vaulttest.go 
package main

import (
        "fmt"
        "os"

        vault "github.com/hashicorp/vault/api"
)

func main() {
        config := &vault.Config{Address: os.Getenv("VAULT_ADDR")}
        _, err := vault.NewClient(config)
        if err != nil {
                fmt.Println(err)
        }
}
$ go run vaulttest.go 
$ 
```

**Comment by joshrendek** [comment]
@jefferai is your go get at 52a6ea393 ?

**Comment by joshrendek** [comment]
PEBKAC :( Sorry about this, was a old variable from testing still in ENV like you said
