### ISSUE TITLE
Multi - Level Certificate

### ISSUE THREAD

**Issue by YangTianning** [hashicorp/vault#487]
My init step works just well with the certificate signed by root certificate. However, when trying the one signed by intermediate certificate, there is an error saying "init: x509: certificate signed by unknown authority. I did verify the certificate chain and trusted my root cert and trusted the chain certificate.

**Comment by sethvargo** [comment]
Hi there,

This looks like a duplicate of https://github.com/hashicorp/vault/issues/388. Can you please confirm

**Comment by jefferai** [comment]
@YangTianning When you say "my init step", can you give more details? Vault init, or init of one of the backends?

**Comment by YangTianning** [comment]
Thank you for replying. The problem has been solved when I do it on another platform. Anyway, I meant “vault init” by then.

Tina

**Comment by jefferai** [comment]
Solved per user.
