### ISSUE TITLE
Vault HashiCorp 0.10.3 dependencies fail

### ISSUE THREAD

**Issue by andrejvanderzee** [hashicorp/vault#4872]
Hi,

We have some dependency troubles with HashiCorp vault 0.10.3:

Vault 0.10.3 imports:

```
andrej:~/go/src/github.com/vault$ cat command/commands.go | grep plugin
	ad "github.com/hashicorp/vault-plugin-secrets-ad/plugin"
	gcp "github.com/hashicorp/vault-plugin-secrets-gcp/plugin"
	kv "github.com/hashicorp/vault-plugin-secrets-kv"
```

Some of these plugins use Go dep:

https://github.com/hashicorp/vault-plugin-secrets-gcp/blob/master/Gopkg.toml#L52:

```
[[constraint]]
  name = "github.com/hashicorp/vault"
  branch = "master"
```

This breaks our upgrades of our vault client from 0.10.1 to 0.10.3:

```
andrej:~/go/src/lovebird-dev.eu/infra/vault-helper$  dep ensure
Solving failure: No versions of github.com/hashicorp/vault-plugin-secrets-ad met constraints:
	master: Could not introduce github.com/hashicorp/vault-plugin-secrets-ad@master, as it has a dependency on github.com/hashicorp/vault with constraint master, which has no overlap with existing constraint ^0.10.3 from (root)
```

These HashiCorp plugins should pin on some `vault` SemVer (and visa versa), or Vault should never import these dependencies (importing dependencies with only master branch and no SemVer tags is dubious). 

Thanks, 
Andrej

**Comment by jefferai** [comment]
Pinning isn't the problem; it's a problem in depth itself. See https://github.com/golang/dep/issues/1131

Once vgo becomes stable we plan to switch, which will hopefully help with this kind of problem. In the mean time using govendor might help, which is what we still use in Vault for this exact reason.

**Comment by andrejvanderzee** [comment]
You mean that once vgo comes out in next beta all problems will go away just like that? I doubt.

These imports in `github.com/vault/command/commands.go`:
```
	ad "github.com/hashicorp/vault-plugin-secrets-ad/plugin"
	gcp "github.com/hashicorp/vault-plugin-secrets-gcp/plugin"
	kv "github.com/hashicorp/vault-plugin-secrets-kv"
```

These imports have _no_ SemVer tags at all. Vgo is all about pinning dependencies on SemVer.

Moreover, these projects _should_ pin on their cyclic `vault` dependency SemVer (and _not_ use `master` for `vault` in Godep.toml). 

I dont think this will be solved once vgo comes out, its just a lack of tagging and pinning in the plugins.

**Comment by jefferai** [comment]
Dep cannot solve this, tagging or no tagging. The author has confirmed this. Vgo will require refactoring but does actually have the possibility of being a workable solution once such refactoring is performed.

**Comment by andrejvanderzee** [comment]
Hmmm yeah after reading https://github.com/golang/dep/issues/1131 more closely it looks like we have to go back to govendor.

Thanks for your patience!

**Comment by sdboyer** [comment]
(just noting - we will actually have a solution to this in the successor to dep, too 😄)

**Comment by jefferai** [comment]
Yep! We at HashiCorp are all quite in anticipation.

**Comment by andrejvanderzee** [comment]
At Yolt we are now using `vendor` (for all HashiCorp vault projects like plugins and such) and `dep` for all other projects, so we are looking forward to standardizing on one tool some day too :-) 

@sdboyer What do you exactly mean by the successor to `dep`? `vgo`?

**Comment by sdboyer** [comment]
@andrejvanderzee nope, definitely not vgo. while I do not begrudge anyone just wanting to use vgo and get their work done, I believe the design is fundamentally harmful to the community, so we're working on an alternative. 

still figuring out the exact shape, though. more on that in the coming weeks.

**Comment by jefferai** [comment]
Oh, I also thought you meant `vgo`. Just curious, what about it do you think is fundamentally harmful?

**Comment by sdboyer** [comment]
shortest possible version: it does nothing to help with a problem that it acknowledges exists (incompatibility), and for which there are reasonable steps we could take, because it can't do so while retaining the MVS algorithm. instead, it pushes work onto maintainers that amounts to an obligation to update, which even if we can agree that it's ideal, is (IMO) unethical to elevate to a requirement in the context of scarce OSS labor.

it may not not adversely affect HashiCorp folks overmuch, as your OSS labor is also your day job. but, such is the design of the system that that increases the pressure on the rest of us.

I've published two blog posts (of a larger planned series) that are a much deeper exploration of this: https://sdboyer.io/vgo. 

that's 18k words already, though. I gave a tl;dr at GoSF last week, but the video borked. I'm rerecording it as a screencast as soon as I finish up the next dep release (today).

**Comment by andrejvanderzee** [comment]
The Vault code-base as it is now will not work with `vgo` either cause some of its dependencies / plugins (like described above) don't use any SemVer, but I believe @jefferai pointed they will fix this when the time comes. So yeah, I think you definitely have a point that some responsibilities are pushed to the community.

**Comment by jefferai** [comment]
@sdboyer Cool, thanks for the insight.
