### ISSUE TITLE
When using DynamoDB as a backend, Vault is unhealthy when the standby instance is going down

### ISSUE THREAD

**Issue by odedpriva** [hashicorp/vault#4876]
**Describe the bug**
When using DynamoDB as a backend, Vault is unhealthy when the standby instance is going down  

**To Reproduce**
1. Start an HA mode vault using DynamoDB as a backend
2. Stop the standby instance. 
3. The active vault instance is returning 429 and vault is unavailable till an instance grabs the lock.

This cluster is running on AWS with ELB to run health checks and point traffic to the active instance using v1/sys/health route. 

We had downtime with vault when the standby vault ec2 instance had networking issues. 

**Expected behavior**
standby instances health should not affect the healthiness of the cluster. 

**Environment:**
```
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0
Unseal Nonce:
Version: 0.8.0
Cluster Name: ****
Cluster ID: 0792fc39-3392-79b5-43b7-c288405a0932

High-Availability Enabled: true
	Mode: active
	Leader Cluster Address: https://***.:8201
  ```

* Vault CLI Version (retrieve with `vault version`):
```

vault version
Vault v0.8.0 ('af63d879130d2ee292f09257571d371100a513eb')

```
* Server Operating System/Architecture:

                          +-------------+         +------------------+
                          | VAULT 0.8.0 +---------+                  |
                          +------+------+         |                  |
                                |                |                  |
      +-----------+       +------+-------+        |                  |
      |           |       | VAULT 0.8.0  +------- |     DynamoDB     |
      |  AWS ELB  ++      +------+-------+        |                  |
      |           ||             |                |                  |
      +------------+     +-------+--------+       |                  |
                  +-+--^+  VAULT 0.8.0  |--------+                  |
                    |   +----------------+       +------------------+
                    |
        +------------+----------------+
        |   Ping Target	              |
        |   HTTP:8200/v1/sys/health   |
        |   Timeout	3 seconds         |
        |   Interval	5 seconds       |
        |   Unhealthy threshold	2     |
        |   Healthy threshold	2       |
        +-----------------------------+

Vault server configuration file(s):

```hcl
storage "dynamodb" {
  ha_enabled = "true"
  region     = "eu-west-1"
  table      = "staging-vault-application"
  redirect_addr = "http://vault.*.com.:8200"
  api_addr = "http://vault.*.com.:8200"
  cluster_addr = "http://vault-internal.*com.:8201"
}


listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = 1
}

telemetry {
  statsd_address = "statsd.*.com:8125"
}
```

**Comment by jhmartin** [comment]
Possibly related to #5828 ?

**Comment by michelvocks** [comment]
Closing this since #6512 has been merged to fix this.
