### ISSUE TITLE
PKI tidy appears to noop

### ISSUE THREAD

**Issue by dmicanzerofox** [hashicorp/vault#4877]
Greetings, we are running into a critical production issue where we are trying to tidy the CRL and it doesn't appear to be doing anything.  In our investigation, we also noticed that the raw consul value of the CRL is over the consul limit of 512kB.

```
# vault version
Vault v0.10.2 ('3ee0802ed08cb7f4046c2151ec4671a076b76166')
```

```
# consul version
Consul v1.0.6
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

### Unable to parse the CRL using openssl

we were able to pull down the pem initially.
```
curl --header "X-Vault-Token: $VAULT_TOKEN" https://X.X.X.X:8200/v1/pki/aws-us-west-2/crl/pem -k > vault-crls.pem

$ openssl crl -inform PEM -in vault-crls.pem
    unable to load CRL
    139994909750936:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:701:Expecting: X509 CRL    
```

But after the tidy we are now unable to pull it down at all

```
$ curl --header "X-Vault-Token: XX” https://X.X.X.X:8200/v1/pki/aws-us-west-2/crl
 {"errors":["internal error"]}
```

### Unable to rotate
```
$ AULT_CLIENT_TIMEOUT=600 vault read pki/aws-us-west-2/crl/rotate
Error reading pki/aws-us-west-2/crl/rotate: Error making API request.
URL: GET https://X.X.X.X:8200/v1/pki/aws-us-west-2/crl/rotate
Code: 500. Errors:
* 1 error occurred:
* error encountered during CRL building: error storing CRL: Unexpected response code: 413 (Value exceeds 524288 byte limit)
```

### Unable to reiissue intermediary
```
vault write pki/aws-us-west-2/intermediate/set-signed \
     certificate="-----BEGIN CERTIFICATE-----
MIIDFzCCAp6gAwIBAgIUSO9c8KtwNzQovitzqwDHV3HvC+cwCgYIKoZIzj0EAwIw
HTEbMBkGA1UEAxMSWmVyb0ZveCBSb290IENBIFFBMB4XDTE4MDcwOTEzMDkyOFoX
DTE4MDkwNzEzMDk1OFowJzElMCMGA1UEAxMcWmVyb0ZveCBJQ0EgUUEgYXdzLXVz
LXdlc3QtMjB2MBAGByqGSM49AgEGBSuBBAAiA2IABBPHwFpV9TkvJ7Xi4lWjI0NK
c9mKOQ5GsVvRGZF2VfPZ5Xceqzqs8V2F8ncy3QsBk3f7N4PYjWMIpko9KiDBg5dn
ubR9BBcdf2/EaCSJxhSfSH/n/Q1yWKiVPnz6Pc7viaOCAZMwggGPMA4GA1UdDwEB
/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBRTxycb92bgKOyq
6SBMxWrNJUcw4zAfBgNVHSMEGDAWgBTKK8N8DgvdjFDmCnQVq3XmuKAOJTCBmgYI
KwYBBQUHAQEEgY0wgYowSgYIKwYBBQUHMAKGPmh0dHBzOi8vdmF1bHQuc2Vydmlj
ZS5hd3MtdXMtd2VzdC0yLmNvbnN1bDo4MjAwL3YxL3BraS9yb290L2NhMDwGCCsG
AQUFBzAChjBodHRwczovL3ZhdWx0LnNlcnZpY2UuY29uc3VsOjgyMDAvdjEvcGtp
L3Jvb3QvY2EwgYsGA1UdHwSBgzCBgDBFoEOgQYY/aHR0cHM6Ly92YXVsdC5zZXJ2
aWNlLmF3cy11cy13ZXN0LTIuY29uc3VsOjgyMDAvdjEvcGtpL3Jvb3QvY3JsMDeg
NaAzhjFodHRwczovL3ZhdWx0LnNlcnZpY2UuY29uc3VsOjgyMDAvdjEvcGtpL3Jv
b3QvY3JsMAoGCCqGSM49BAMCA2cAMGQCMGbG0QGEz8B/ITNs/IApRki26cwnGF8s
83ZnEK41xKAwSffSsPTcJ+VQCQrEa7f03QIwQB8Hzb5QLy98iKdsokkm9ChFsnM4
lxbL9uupG6K3DtMkh/WnJzG0HPwAlVJlP8FL
-----END CERTIFICATE-----"
Error writing data to pki/aws-us-west-2/intermediate/set-signed: Error making API request.
URL: PUT https://X.X.X.X:8200/v1/pki/aws-us-west-2/intermediate/set-signed
Code: 500. Errors:
* 1 error occurred:
* error storing CRL: Unexpected response code: 413 (Value exceeds 524288 byte limit)
```

### Dumping consul backend:

We dumped the vault consul tree in order to see the size of the key. We loaded the json values in python in order to get the length of the value associated with the crl:

`key': 'vault/logical/06515fe5-b2a2-ee9a-5cc3-fb54d0bf68a1/crl',`

```
In [12]: len(crls[0]['value'])
Out[12]: 699036
```

### CRL TIDY
We've executed tidy last week and multiple times today.

```
$ VAULT_CLIENT_TIMEOUT=600 vault write pki/aws-us-west-2/tidy tidy_revocation_list=true
Success! Data written to: pki/aws-us-west-2/tidy
```

After issuing this command we observed vault doing work, but the CRL is still the same size in consul.

```
$ consul monitor -log-level=TRACE
```

### Resources
- Consul/vault CPU and IOPS look healthy

I'm hoping that you could help us:
- How might this CRL value be larger than the maximum allowed by consul?
- What would you do in this situation in order to reissue the intermediary?

We appreciate your time and are able to get any other information that may be helpful.
Thank you

**Comment by jefferai** [comment]
> How might this CRL value be larger than the maximum allowed by consul?

Because you have a lot of entries on it, and Consul has a maximum per-key storage size.

> What would you do in this situation in order to reissue the intermediary?

Set the buffer for tidy to something smaller so that it clears out more entries. You should also then look at why so many entries are showing up on the CRL. In general if you even use CRLs at all you want the size of it to be as small as possible.

**Comment by dmicanzerofox** [comment]
SoMuchToGrok and I really appreciate your quick response.  The strategy we ended up taking was similar to your second suggestion.
