### ISSUE TITLE
sys/wrapping/unwrap does not accept token in request body

### ISSUE THREAD

**Issue by ramiamar** [hashicorp/vault#4887]
**Description**
When trying to unwrap a token, calling /v1/sys/wrapping/unwrap with a token within the POST requests's body, fails with the following error: "missing client token". According to the [docs](https://www.vaultproject.io/api/system/wrapping-unwrap.html) it should work

**To Reproduce**

Generate a token (or perhaps any wrapped secret), and then follow these python lines:
```python
In [2]: import requests
In [3]: token = '69648fd8-xxxx-xxxx-xxxx-abc1a90941a0'  # wrapped token
In [4]: res = requests.post(vault_addr + '/v1/sys/wrapping/unwrap', json={'token': token})
In [5]: res.status_code
Out[5]: 400
In [6]: res.content
Out[6]: b'{"errors":["missing client token"]}\n'
In [7]: res = requests.post(vault_addr + '/v1/sys/wrapping/unwrap', headers={'X-Vault-Token': token})
In [8]: res.json()
Out[8]: 
{'request_id': '4ac1811e-xxxx-b8a7-748d-5d2f6b8d2fc6',
 'lease_id': '',
 'renewable': False,
 'lease_duration': 0,
 'data': None,
 'wrap_info': None,
 'warnings': [],
 'auth': {'client_token': '7df8bffd-xxxx-xxxx-xxxx-71985791197c',
  'accessor': 'ea0b23c5-xxxx-xxxx-xxxx-5dcf5e01d3fc',
  'policies': ['a', 'default', 'd'],
  'metadata': None,
  'lease_duration': 21600,
  'renewable': False,
  'entity_id': '0c52278c-xxxx-xxxx-xxxx-d8afcfcb898c'}}

In [9]: token = '4ffb125e-xxxx-xxxx-xxxx-83ab4e08f754'
In [10]: res = requests.post(vault_addr + '/v1/sys/wrapping/unwrap', headers={'X-Vault-Token': token}, json={'token': token})  # trying to pass the token in header and in body
In [11]: res.status_code
Out[11]: 500
In [12]: res.content
Out[12]: b'{"errors":["1 error occurred:\\n\\n* error decrementing wrapping token\'s use-count: invalid token entry provided for use count decrementing"]}\n'
```

**Expected behavior**
the token should be unwrapped and returned

**Environment:**

- The above was reproduced on versions 0.9.5, 0.9.6, 0.10.0, 0.10.2
- operating system: ubuntu 16.04

Vault server configuration file(s):

```json
{
            "backend": {"inmem": {}},
            "listener": {
                "tcp": {
                    "address": "127.0.0.1:8200",
                    "tls_disable": 1
                }
            },
            "disable_mlock": true
 }
```

**Comment by jefferai** [comment]
It seems like when you are putting the token in the request body you're not setting a token on the client (in the header), hence the error.

**Comment by ramiamar** [comment]
just making sure i understand correctly (as the documentation and deprecated cubbyhole endpoint are somewhat confusing):

1. one can pass a wrapping token in the header, and that will be ok
2. one can also pass a wrapping token in the body, but must include a valid client token in the header (an authentication mechanism which does not seem to be needed in case 1.. ?)

if this is the case, i'll open a bug at the hvac repo, as [this line](https://github.com/ianunruh/hvac/blob/master/hvac/v1/__init__.py#L82) should not work

**Comment by jefferai** [comment]
In case 1 the wrapping token itself is the client token. In case 2 you still need some way to have your request be authorized.

In practice you almost always want to use case 1. Case 2 exists for special purposes, like an orchestration system unwrapping lots of tokens, so that it doesn't have to keep switching its client token on every call.

**Comment by ramiamar** [comment]
i see. thanks for clarifying, and apologies for the trouble. closing the issue
