### ISSUE TITLE
Documentation of "write" command uses "kv put"

### ISSUE THREAD

**Issue by JamesUoM** [hashicorp/vault#4890]
**Describe the bug**
Documentation issue. First thing you want to do with the CLI is add a secret but "write" doesn't work and the documentation the starts talking about "kv put":

https://github.com/hashicorp/vault/blob/master/website/source/docs/commands/index.html.md#writing-data 

Similarly "read" examples use "kv get"

**Expected behavior**
A clear explanation of how the most basic operation works.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.1
* Vault CLI Version (retrieve with `vault version`): 0.10.1
* Server Operating System/Architecture: Ubunty 16.04

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by kalafut** [comment]
Docs were just updated. Thanks for noting this issue!
