### ISSUE TITLE
Vault Plugin for Couchbase

### ISSUE THREAD

**Issue by subba7032** [hashicorp/vault#4897]
Hello, I am trying to enable couchbase secrets engine, but it doesn't come built in plugin.
Any ideas on how to solve it, thanks.

**Comment by jefferai** [comment]
We do not currently have a couchbase engine, sorry.

**Comment by rfults** [comment]
There is a free to use community edition of the platform that has all of the api's exposed.  I'm sure someone on the Couchbase team would happily work with you to develop this as well.
