### ISSUE TITLE
Idea: Allow for Role Configured Leases

### ISSUE THREAD

**Issue by ekristen** [hashicorp/vault#490]
I'll be more than willing to submit the PR for this if everyone agrees. I think it would be nice to be able to set the default lease for a role instead of globally for a mounted AWS backend.

I have use cases where some roles that provide AWS creds I'd want to be a couple of days vs 1 hour and visa versa, but I don't necessarily want to have to mount the AWS backend at different locations manage the config for each mount point.

Thoughts?

**Comment by armon** [comment]
@ekristen Agreed. I think you should be able to do a per-role override, but inherit the backend default.

**Comment by jasonarewhy** [comment]
+1 to this as we have a variety of mysql connection types we'd like to handle with Vault and setting lease time per role is a requirement to handle all of them.

**Comment by eli007** [comment]
+1

**Comment by jefferai** [comment]
Closing due to time. The OP suggested being willing to submit the necessary PR so that would be a next step.
