### ISSUE TITLE
Active directory secret backend: 404 when reading creds with root token

### ISSUE THREAD

**Issue by madjam002** [hashicorp/vault#4902]
**Describe the bug**
When trying the active directory secret backend, I get a 404 when attempting to read a password via curl or a `No value found at ad/creds/my.application` when using `vault read ad/creds/my.application`.

**To Reproduce**

```
$ vault secrets enable ad

$ read USERNAME && read PASSWORD && \
  vault write ad/config \
  binddn=$USERNAME \
  bindpass=$PASSWORD \
  url=ldap://dc1.example.net \
  userdn='dc=example,dc=net' \
  insecure_tls=true

$ vault write ad/roles/my.application \
     service_account_name="my.application@example.net"

  Success! Data written to: ad/roles/my.application

$ vault read ad/creds/my.application

  No value found at ad/creds/my.application

```

It's worth noting that if I try and use `vault write ad/roles/foobar`, I get an error saying that the user doesn't exist in AD, so the LDAP connection is working.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.3
* Vault CLI Version (retrieve with `vault version`): 0.10.2
* Server Operating System/Architecture: Raspberry Pi 3 Linux vault1 4.14.50-v7+ 1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux

Vault server configuration file(s):

```hcl
storage "file" {
  path = "....../vault/data"
}

listener "tcp" {
  address = "0.0.0.0:443"
  tls_cert_file = "....../cert.pem"
  tls_key_file = "....../key.pem"
  tls_disable_client_certs = true
}

ui = true
```

**Comment by jefferai** [comment]
> No value found at ad/creds/my-application when using vault read ad/creds/my-application.

In your example it's my.application, with a period, not a hyphen. Are you sure you're using the same value?

**Comment by madjam002** [comment]
@jefferai Sorry it's because I mangled the original values which use periods instead of hyphens but forgot to update the output! The usernames in my AD use periods.

I've updated the issue.

**Comment by tyrannosaurus-becks** [comment]
Thanks for posting this @madjam002! I've been away for a couple of days and am now working on reproducing the issue to follow up with more....

**Comment by tyrannosaurus-becks** [comment]
@madjam002 it may be that the url you're using starts with `ldap://` rather than `ldaps://`. When I use that kind of URL, when the creds call is executed the Microsoft API returns a "WILL NOT PERFORM" but that error doesn't get propagated back to the CLI. I'll need to add a fix for that and update the docs, but first, can you give it a try and see if that fixes it for you?

**Comment by madjam002** [comment]
@tyrannosaurus-becks Yeah I’m using ldap://, I won’t be able to have a look until tomorrow but I’ll definitely give it a try! Thanks

**Comment by tyrannosaurus-becks** [comment]
@madjam002 FWIW, I also found why it wasn't returning a debuggable err and [merged a fix](https://github.com/hashicorp/vault-plugin-secrets-ad/pull/23). It will be released with Vault 0.11, but if you'd like to use it early as a plugin, you could by following the steps in [the README](https://github.com/hashicorp/vault-plugin-secrets-ad). That would give you an error to look at, at least, to decide what next step to take. But it's likely that it needs `ldaps://`.

**Comment by coryplastek** [comment]
@madjam002 @tyrannosaurus-becks When the ad secrets engine is called to retrieve the password, does Vault attempt to set a new password at that time (I'm new to Vault, but I'm guessing this is the case)? If so, then a TLS session (if using LDAP) is required by Active Directory when a password reset is attempted:

https://support.microsoft.com/en-us/help/269190/how-to-change-a-windows-active-directory-and-lds-user-password-through

**Comment by madjam002** [comment]
@coryplastek Still haven't got round to sorting this out yet, haven't been working on the Windows side much lately, but I'm very eager to give LDAPS a try soon to see if that fixes it!

**Comment by OperationalDev** [comment]
I can confirm that when switching to LDAPS, the root token no longer returns 404s. Thanks @tyrannosaurus-becks for recommending using LDAPS.

**Comment by tyrannosaurus-becks** [comment]
That's great news! I'll update the docs.

**Comment by tyrannosaurus-becks** [comment]
https://github.com/hashicorp/vault/pull/5180 is the doc update, FWIW.
