### ISSUE TITLE
VAULT_ADDR by default should be http://localhost:8200/

### ISSUE THREAD

**Issue by Lasering** [hashicorp/vault#4903]
The default value of VAULT_ADDR should be http://localhost:8200.

This way Vault installations on IPv6 only or IPv4 only would work out of the box. More precisely executing vault commands would work out of the box.

**Comment by jefferai** [comment]
It's https on purpose to ensure that users that are skipping TLS-based security are doing so in knowing fashion, and to reduce the possibility of a super easy MITM attack.

**Comment by Lasering** [comment]
@jefferai The important part is `localhost` instead of `127.0.0.1`. I forgot about the https part because I was copying this from the equivalent issue I opened for Consul.

**Comment by jefferai** [comment]
Using 127.0.0.1 protects against host file attacks.

It's pretty easy to just change the value in your environment, e.g. bashrc.

**Comment by burdandrei** [comment]
@jefferai this is really smart!
But there are always crazy solutions => https://github.com/hashicorp/consul/pull/4382#issuecomment-405553572

**Comment by jefferai** [comment]
Consul is a different product with different security characteristics. Vault will not be changing this.
