### ISSUE TITLE
Time-delayed revocation

### ISSUE THREAD

**Issue by far-blue** [hashicorp/vault#4914]
I'd like to request the ability to revoke a lease or token at some point in the future or, alternatively, an option to reduce the ttl or max-ttl on a lease or token rather than only extend it.

To be honest, my use case is quite an edge case but here's the situation:

In a production environment where there's a worry Vault might 'go away' a longer lease on dynamically generated database credentials would allow for live systems to keep working until Vault is available again. However, it would still be good to regularly generate new tokens and db credentials when Vault is available (so the buffer window stays long in case of Vault being unavailable). This results in lots of sets of active credentials. To keep things tidy and minimise active secrets, it seems sensible to revoke old tokens when new ones are generated.

In a production environment with multiple worker processes for an application (e.g. PHP) and with "no shared state" between page requests, the only option is to cache credentials - otherwise every page request generates new db credentials. When new db credentials are generated and cached, there's no way to know whether the previous credentials are still in use so you can't immediately revoke them. If the lease duration was short, you could just leave the tokens and db credentials to expire but if, as outlined above, longer lease times are used to provide a buffer in case vault goes away then some form of active revocation after a time delay that allows existing worker processes to finish using the old credentials and pick up the new ones from the cache is needed.

Without support from Vault, the delayed revocation needs to be done in the PHP code by caching the old token accessors and revoking them after a set period of time after the token was replaced. This in turn impacts page latency and code complexity and also relies on there being a page request to trigger the cleanup.

As suggested at the start, as an alternative to delayed revocation, the ability to reset the max-ttl to a short time after the present would achieve the same goal.

**Comment by jefferai** [comment]
You can already reduce the TTL by using the `increment` value during a renewal operation. Most plugins will honor this value, and you can specify a value that is less than the current TTL.

To be honest, I don't think I'm really understanding the larger problem. TTLs *are* delayed revocation; that's the entire point. Otherwise you'd just revoke immediately after a single use of each token.

**Comment by far-blue** [comment]
If it is possible to reduce the lease duration on a lease or token then I think that work prob. be good enough :) Of course, during that reduced time it would be possible to renew again and extend the lease duration back up so it's not guaranteed a bad actor couldn't delay the token or lease expiring. 

This was one of the alternative options I mentioned in the first sentence of the original issue but the documentation suggests that when a token is renewed the increment is added to the existing lease duration rather than replacing it - so if I had a token with a remaining lease of 4 hours and I renew it with an increment of 5mins then the token would have a lease of 4 hours and 5 mins, not just 5 mins.

If that's not the case then a renewable, non-periodic token with original lease duration and explicit max ttl both set to the same value which I could then renew with an increment of '10s' to cause it to expire earlier than it's original lease would work for me :)

**Comment by far-blue** [comment]
Having had a chance to really test this out I can confirm that it works fine :) I am using appRoles so if you specify a ttl and a max_ttl for the tokens in the appRole configuration (and you can make them the same value if you want) then you can later renew the token's lease using renew_self and provide a small time duration such as '30' and the token will expire after this new, shorter lease time.

Just noting it here for anyone else wanting to achieve the same.
