### ISSUE TITLE
Anyway to specific auth method and token (ie github) via env vars?

### ISSUE THREAD

**Issue by ekristen** [hashicorp/vault#492]
Is there anyway to provide an auth token via env var for the github auth method? Or is this limited to only the built in token auth system?

**Comment by sethvargo** [comment]
@ekristen I do this internally:

```
$ vault auth -method=github token=$GITHUB_TOKEN
```

But there's no "preset" environment variable and I'm not sure that's necessary.

**Comment by ekristen** [comment]
I'd like to not have to run auth each time I open a new terminal. Being able to a set the equivalent of VAULT_TOKEN would be great.

**Comment by sethvargo** [comment]
@ekristen when you auth, the token is stored locally on disk, so you wouldn't have to auth again

**Comment by ekristen** [comment]
Gotcha, thanks.
