### ISSUE TITLE
Error initializing Vault: Error making API request.

### ISSUE THREAD

**Issue by mvkkreddi** [hashicorp/vault#4921]
We are having issue with initializing vault keys, When we try to vault init getting below error... any reason... 
Error initializing Vault: Error making API request.
URL: PUT http://127.0.0.1:8200/v1/sys/init
Code: 500. Raw Message:

**Comment by jefferai** [comment]
Please fill out all of the information that was in the template.

**Comment by mvkkreddi** [comment]
We are using : 64 bit version
vault_0.9.1_linux_amd64.zip

**vault-config.hcl**

disable_mlock = true

storage "file" {
  path = "/home/keymanager/Keymanager_vault/vault_data"
}

listener "tcp" {
 address     = "10.64.253.171:8200"
 tls_disable = true
}


**vault.log**

==> Vault server configuration:

                     Cgo: disabled
              Listener 1: tcp (addr: "vault-server-ip:8200", cluster address: "vault-server-ip:8201", tls: "disabled")
               Log Level:
                   Mlock: supported: true, enabled: false
                 Storage: file
                 Version: Vault v0.9.1
             Version Sha: 87b6919dea55da61d7cd444b2442cabb8ede8ab1

==> Vault server started! Log data will stream in below:

**Comment by jefferai** [comment]
What is in your logs?

**Comment by mvkkreddi** [comment]
Below info was in vault log file

Cgo: disabled
          Listener 1: tcp (addr: "vault-server-ip:8200", cluster address: "vault-server-ip:8201", tls: "disabled")
           Log Level:
               Mlock: supported: true, enabled: false
             Storage: file
             Version: Vault v0.9.1
         Version Sha: 87b6919dea55da61d7cd444b2442cabb8ede8ab1

**Comment by mvkkreddi** [comment]
Can anyone provide the solution for above vault issue
