### ISSUE TITLE
Incomplete Signature

### ISSUE THREAD

**Issue by rayana45tulasiram** [hashicorp/vault#4939]
Please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues.

With over 1700 subscribers, the mailing list gets a _lot_ more eyes on any particular question. You'll get an answer faster, not slower, by taking advantage of the suggestions and answers provided by the wealth of experience that long-time users and devs bring to the list.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!

Team i am facing this issue below. when i ran this command 
"vault login -method=aws header_value=vault.example.com role=dev-role-iam aws_access_key_id=xxxx aws_secret_access_key=xxxx"
my motive is to login ec2 instance from vault is it possible ?
 
Error authenticating: Error making API request.

URL: PUT https://127.0.0.1:8200/v1/auth/aws/login
Code: 400. Errors:

* error making upstream request: received error code 400 from STS: <ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <Error>
    <Type>Sender</Type>
    <Code>IncompleteSignature</Code>
    <Message>Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got 'asWer9styuop/S6g3/nLOI49/20180717/us-east-1/sts/aws4_request'</Message>
  </Error>
  <RequestId>a470716b-89ad-11e8-ae25-edc9179a9b37</RequestId>
</ErrorResponse>

**Comment by joelthompson** [comment]
@rayana45tulasiram -- it looks like you entered an invalid access key ID. Specifically, it looks like you entered an access key of `asWer9styuop/S6g3/nLOI49` which is invalid. Access keys for users should generally start with `AKIA` in my experience.

**Comment by rayana45tulasiram** [comment]
Thanks !! @joelthompson Yes Issue was resolved
