### ISSUE TITLE
Feature Request: Support HA storage via Kubernetes leader election

### ISSUE THREAD

**Issue by tamalsaha** [hashicorp/vault#4951]
We want to run Vault on Kubernetes. Kubernetes provided leader election support in their client-go library via Kubernetes apiserver. https://github.com/kubernetes/client-go/tree/master/tools/leaderelection

Do you think a [ha_storage](https://www.vaultproject.io/docs/configuration/index.html#ha_storage) backend can be supported for Kubernetes clusters?

We will be interested in contributing this feature if acceptable.

**Comment by jefferai** [comment]
Probably. You'd have to see if what they provide maps to the interfaces we need. A quick look suggests yes.

**Comment by tamalsaha** [comment]
Thanks @jefferai . Will you merge a pr for such? I can look into adding that. This will mean anyone of a Kubernetes cluster will be able to HA mode for any storage.

**Comment by jefferai** [comment]
It'd fit into the community-maintained bucket but sure, I don't see why we wouldn't.
