### ISSUE TITLE
Plugin returns "received message larger than max" error when sending payloads greater than 4194304 bytes

### ISSUE THREAD

**Issue by broamski** [hashicorp/vault#4957]
**Describe the bug**
When using a custom vault plugin and sending a payload greater than 4194304 bytes, the operation ends in failure due to the grpc default max receive message size of `1024 * 1024 * 4`. This option does not appear to be configurable, so servicing larger requests is not possible. 

**To Reproduce**
1. Write payload to plugin `vault write customplugin/action @large_28mb_payload`
2. See error: `[ERROR] core: failed to run existence check: error="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (28793489 vs. 4194304)"`

**Expected behavior**
In `plugin.Server`, set the max receive size to a value similar to or the same as the max send size, which would align to the changes made for #4843.

Alternately, allow both the send and receive values to be configurable via `plugin.ServeOpts`.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.3
* Vault CLI Version (retrieve with `vault version`): Vault v0.10.3 ('c69ae68faf2bf7fc1d78e3ec62655696a07454c7')
* Server Operating System/Architecture: darwin, linux

Vault server configuration file(s): Running in `-dev` mode.

**Additional context**
This impacts the ability to perform cryptographic operations (similar to that of transit engine) on larger binary files.

grpc declares these constant values as:
```
defaultServerMaxReceiveMessageSize = 1024 * 1024 * 4
defaultServerMaxSendMessageSize    = math.MaxInt32
```

**Comment by jefferai** [comment]
Would be super cool if you can test https://github.com/hashicorp/vault/pull/4959

**Comment by jefferai** [comment]
I mean, #4958

**Comment by broamski** [comment]
Sure thing! I'll test this first thing tomorrow!

**Comment by broamski** [comment]
Also, thanks for the fast response!

**Comment by broamski** [comment]
I can confirm that this change does indeed allow payload sizes greater than 4194304 bytes to be successfully processed by a plugin. Thanks!

**Comment by jefferai** [comment]
Great!
