### ISSUE TITLE
Proposal: Allow leases to be disabled on generic secret backend

### ISSUE THREAD

**Issue by ekristen** [hashicorp/vault#496]
I'm proposing there is a way to disable leases with the generic secret backend.

I'd really like to be able to store passwords, key files and other important information that can't be dynamically created indefinitely in the vault and control access to them.

I'm write the PR myself, but don't want to write it if it isn't going to get included.

**Comment by armon** [comment]
@ekristen I don't see why you need to disable leases for this? The generic backend can already handle that use case. The lease does not control the life of the value in Vault itself, only the duration that the client should consider the result valid. The data will not delete out of Vault automatically.

**Comment by ekristen** [comment]
Thanks @armon I assumed like the other backends (aws, mysql, postgres) that secrets would expire and be removed from the store. I just re-read the documentation for the generic secret backend I'll submit a PR when I get a chance to highlight that the data does not get erased. Thanks!
