### ISSUE TITLE
Standby's Do Not Always Forward to Active

### ISSUE THREAD

**Issue by ekristen** [hashicorp/vault#499]
I have a single DNS record with all 3 of my vaults in it, and for some reason it seems that when I get the IP of a standby it doesn't always forward the request to the active as I get the message "Vault is in standby mode"

My understanding was the standby's forward requests to the active?

**Comment by ekristen** [comment]
Are there certain commands like `auth-enable` that do not get forwarded?

**Comment by armon** [comment]
@ekristen Yes, there is an open ticket for this. Some paths do not get properly forwarded due to some issues in the HTTP handler code. The core is generating the proper redirect and it is not being exposed correctly through the HTTP layer.

**Comment by ekristen** [comment]
Do you know the ticket? I'd like to follow it and I can close this out in favor of it too. Thanks

**Comment by armon** [comment]
This ticket alludes to it: https://github.com/hashicorp/vault/issues/311
However, it's all the same problem. Fixing it requires quite a bit of refactoring in the http package, but they all stem from the same architecture problem.

**Comment by ekristen** [comment]
Thanks and understood.

**Comment by jefferai** [comment]
FYI, some work towards this is in 2920cddc9; more paths will be fixed in later commits.
