### ISSUE TITLE
Change HTTP Method LIST to GET as support for this isn't supported too well.

### ISSUE THREAD

**Issue by dashc** [hashicorp/vault#4991]
Using custom http methods isn't support very well with apps like postman app etc. Even with a header:
`X-HTTP-Method-Override: LIST`
It doesn't work.

Personally, I don't see any issue just using a GET request.

**Comment by chrishoffman** [comment]
Both the LIST verb and GET with the query parameter list=true are supported. See https://www.vaultproject.io/api/index.html#reading-writing-and-listing-secrets.

**Comment by dashc** [comment]
Thanks. I didn't see this. Maybe add this to all the LIST method api docs if possible.
