### ISSUE TITLE
docs: agent: Client writes private key to file?

### ISSUE THREAD

**Issue by JayH5** [hashicorp/vault#4996]
**Describe the bug**
In the docs for the new Vault Agent feature, under the Auto-Auth function, in the first paragraph for [Encrypting tokens](https://www.vaultproject.io/docs/agent/autoauth/index.html#encrypting-tokens), it says:

_[...] In this mechanism, the client receiving the token writes a generated **private key** [emphasis mine] to a file. The sink responsible for writing the token to that client looks for this public key and uses it to compute a shared secret key, [...]_

Should it rather be _"the client receiving the token writes a generated **public key** to a file."_?

For posterity, [link to line in commit](https://github.com/hashicorp/vault/commit/903ab7c4858085e4ef8c4cb05d071bd5f3bdbe10#diff-0ae4a171d6e4312f895082c8ee67f092R65).

Thank you for the great tool that is Vault 🙏

**Comment by jefferai** [comment]
Yes, it should be public key. Will fix.
