### ISSUE TITLE
Vault UI: Can't write kv path containing certain combinations of ad*

### ISSUE THREAD

**Issue by BSHDST** [hashicorp/vault#4998]
**Describe the bug**
Can't write into kv path containing certain combinations of ad*

**To Reproduce**
- vault server -dev
- browse to vault webui
- log in via root token
- click on "secret/"
- click on "Create secret"
- Enter "Path for this secret": DST/service/ad/foobar
- Provide some random key and value (I used "some" and "value" for my tests)
- hit save

-> Error message appears: "Error [object Object]"

Interestingly enough, the same error can be caused by using "DST/service/ads/foobar" instead of only "DST/service/ad/foobar" (ad replaced by ads), but NOT by using something like ada. Some ad* combinations work, some others won't.

**Expected behavior**
Expected path to be usable.

**Environment:**
* Vault Server Version 0.10.4 (Issue was already present in 0.10.2)
* Vault CLI Version 0.10.4
* Tested on multiple Systems, Debian 9 & Arch

**Vault server configuration file(s):**
Doesn't matter since it can be reproduced by using vault server -dev

**Comment by meirish** [comment]
Hi @BSHDST ! I'm having trouble recreating this - could you provide some more details?

What browser/OS combos did you try this in? (I tried on macOS in Firefox, Safari, and Chrome) are you using? 
Are you accessing the dev server locally or over the network? 
Do you see an error in the dev tool console? If so could you paste it or screenshot it here?

Thanks!

**Comment by BSHDST** [comment]
Hi @meirish,

you talking about different browsers made just realize something. What did all the machines I've tested this with so far have in common?

Chrome. Chrome and Adblock. Adblock. The path I was trying to use has "ad" in it. 
Oh boy.

Turning off Adblock (I'm using https://getadblock.com/) solves the issue.

That's pretty embarrassing, not gonna lie.... I apologize for accusing the VaultUI for causing this problem, it was entirely on our end.

Regards,
Benjamin

**Comment by BSHDST** [comment]
Disable Adblock. Not a VaultUI issue.

**Comment by jefferai** [comment]
I recommend reading https://medium.com/@trybravery/please-stop-using-adblock-but-not-why-you-think-13280e76c8e7

There are some good alternatives, like uBlock Origin
