### ISSUE TITLE
Sending back a HTTP/1.1 401 Unauthorized with custom header from auth plugin

### ISSUE THREAD

**Issue by ah-** [hashicorp/vault#5031]
Hi,

I'm just trying to improve https://github.com/wintoncode/vault-plugin-auth-kerberos and add support for standard SPNEGO auth.

SPNEGO looks something like this:
```
C: POST v1/auth/kerberos/login

S: HTTP/1.1 401 Unauthorized
S: WWW-Authenticate: Negotiate

C: POST v1/auth/kerberos/login
C: Authorization: Negotiate a87421000492aa874209af8bc028
```

Right now we support only the last bit, so if a client includes a valid Authorization header directly in the first request we return a vault token.

This is easy to implement in some languages that let you control the kerberos process enough, but hard in others that expect the full handshake.

The bit I'm missing is a way to send back the 401 with header WWW-Authenticate: Negotiate for the first request. Would it be possible to add support for this in vault?

See also https://github.com/wintoncode/vault-plugin-auth-kerberos/issues/13.

**Comment by jefferai** [comment]
I'm adding to the next milestone but that's mainly for internal discussion, it's very likely to slip to 0.11.1 or so.

**Comment by jefferai** [comment]
FYI, this is implemented in https://github.com/hashicorp/vault/pull/6115

If you have a chance to try it out and validate that it's working for you that would be great!

**Comment by ah-** [comment]
Just gave it an initial test, allowed-response-headers works as expected, branch here: https://github.com/wintoncode/vault-plugin-auth-kerberos/tree/www-authenticate

However I'm having issues with passthrough of the Authorization header now, https://github.com/hashicorp/vault/blob/master/http/handler.go#L639 complains as it now expects "Bearer <token>", but SPNEGO uses "Negotiate <token>". Even after just patching that check out it doesn't seem to forward the Authorization header to the plugin anymore.

**Comment by ah-** [comment]
I patched out the `deniedPassthroughRequestHeaders` as well, and with some hacking on the client side I managed to get it to send back the 401 with the correct header, and made it run through a basic SPNEGO flow, and if mutual auth is disabled even got a token back :)

So that PR looks good to me, the response header passthrough works.

**Comment by jefferai** [comment]
Can you tell us what those steps were that you needed? I would expect just patching out the denied passthrough headers check?

**Comment by jefferai** [comment]
Okay. I have an idea for how to fix this that keeps the spirit of why it got denied but allow this. I can't get a fix in for a bit but I will reply here when I've pushed to the branch.

**Comment by jefferai** [comment]
OK -- pushed. Hopefully you should need no Vault modifications now.

**Comment by ah-** [comment]
Just tried, works perfectly with no modifications!

**Comment by sambott** [comment]
Thanks all, this has now made it into the latest release of https://github.com/wintoncode/vault-plugin-auth-kerberos
