### ISSUE TITLE
Can i use a static value (key-value) as username for cassandra plugin?

### ISSUE THREAD

**Issue by subba7032** [hashicorp/vault#5036]
Hello team,

I have a need to create ONLY dynamic password through vault cassandra plugin.

I can store static db username as a key value in vault, not sure how to make use of the username to generate only password for cassandra.

Any ideas on how to do that, thanks.

**Comment by kalafut** [comment]
Hi @subba7032,

The database credentials are always (with the exception of root) generated as a random username/password set, and there is no provision of a fixed username. Can you describe your use case and why you need a static username?

**Comment by subba7032** [comment]
Hi @kalafut 

My DB team have few concerns about generating dynamic credentials and access level on the DB.
Instead they want to create the userID's with customized access level and they want vault to generate ONLY passwords for their static userID's.

Is there any way to sort this out, thanks!

**Comment by kalafut** [comment]
You may want to have them take a look at how roles are specified in the [Cassandra plugin docs](https://www.vaultproject.io/docs/secrets/databases/cassandra.html). They're in complete control of how a user is created and, therefore, what the access will be. Furthermore, the Vault [authentication](https://www.vaultproject.io/docs/concepts/auth.html)  and [policies](https://www.vaultproject.io/docs/concepts/policies.html) mechanisms will control who can even make the request for credentials against the various roles.

If they want to just create users/passwords and own changing them in the DB, Vault can certainly help managing the storage/access to such a secrets (see [KV Secrets](https://www.vaultproject.io/docs/secrets/kv/index.html)). But that's a very different solution than dynamic secrets that Vault is controlling.

**Comment by subba7032** [comment]
Thank you @kalafut
