### ISSUE TITLE
gcp login configuration parsing error

### ISSUE THREAD

**Issue by madsonic** [hashicorp/vault#5037]
**Describe the bug**
> Error authenticating: could not parse jwt_exp '15m' into integer value

**To Reproduce**
```
vault login -method=gcp \
    role="test-role" \
    jwt_exp="15m" \
    credentials=@path/to/token \
    project="test-project" \
    service_account="my-service-account@test-project.iam.gserviceaccount.com"
```
**Expected behavior**
Should not have parse error. The docs for authentication used `15m` [here](https://www.vaultproject.io/docs/auth/gcp.html#via-the-cli)

**Environment:**
* Vault Server Version (retrieve with `vault status`): v0.10.4
* Vault CLI Version (retrieve with `vault version`): v0.10.4
* Server Operating System/Architecture: macOS 10.13 High Sierra

Vault server configuration file(s): running dev server

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by kalafut** [comment]
@emilymye Looks like https://github.com/hashicorp/vault-plugin-auth-gcp/blob/master/plugin/cli.go#L50 should be
parseutil.ParseDurationSecond()?
