### ISSUE TITLE
The beginner's question

### ISSUE THREAD

**Issue by sosiska** [hashicorp/vault#5038]
Hello, guys! I'm new to open source, and looking for my 1st contribute in Golang project. (Actually it is my first issue on GitHub) Your repository has a file https://github.com/hashicorp/vault/blob/master/api/sys_stepdown.go that seems to me, contains an no Golang-style instruction. As i know, we dont need close resp.Body, if we got err in HTTP response and defer makes low overhead. Therefore, is it not better to do so:
```
if err != nil {
	return err
}
resp.Body.Close()
return nil
```
or so:

```
if err != nil {
	return err
}
defer resp.Body.Close()
return nil
```

at the end of this file? This change, in fact, does not change anything. So, what do you think of it? Can i make my 1st Golang pull request to you?

**Comment by kalafut** [comment]
Hi @sosiska,

Thanks for your interest in contributing to Vault. The style in your second option (`defer` Close() as soon as we know we have a valid request) is very common throughout Vault. Feel free to submit a PR.
