### ISSUE TITLE
When leadership is lost while leases are being restored make sure we don't shutdown

### ISSUE THREAD

**Issue by briankassouf** [hashicorp/vault#5046]
For some reason this check isn't working

https://github.com/hashicorp/vault/blob/bb180b8661908d979490ad99d3f9732b5eff4383/vault/expiration.go#L308-L323

Continuation of #4915

**Comment by jefferai** [comment]
> Contains checks if the given error contains an error with the message msg. If err is not a wrapped error, this will always return false unless the error itself happens to match this msg.

Probably the error message is not actually matching -- either there isn't a wrapped error matching that, or the error itself isn't. Those should probably be strings.Contains.

**Comment by jefferai** [comment]
Well, or figure out what the error actually is, make sure it's not matching, and then figure out why it's not matching :-)
