### ISSUE TITLE
Cert auth API doesn't allow to list CA roles

### ISSUE THREAD

**Issue by Fauth** [hashicorp/vault#5056]
**Describe the bug**
When using the API, I get 404 errors when trying to LIST at `/auth/cert/certs/` with a TLS auth backend enabled at `cert`. It should work according to [the doc](https://www.vaultproject.io/api/auth/cert/index.html#list-certificate-roles).

**To Reproduce**
1. Enable a vault TLS auth backend, for example at `/auth/cert`
2. Use the following command to call the API: `curl -k -L --header "X-Vault-token: <root-token>" --request LIST https://localhost:8200/v1/auth/cert/certs/ -v`
3. Get a 404 error.

**Expected behavior**
We expect to get a  list of configured certificate names.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.4 (official docker image)
* Vault CLI Version (retrieve with `vault version`): 0.10.4
* Server Operating System/Architecture: Official docker image on Debian 9.

**Additional context**
All other API paths I used are working. Vault is unsealed.

**Comment by briankassouf** [comment]
When there are no certs configured the endpoint will return a 404, was able to get values after configuring a certificate:
```
$ vault list auth/cert/certs/
No value found at auth/cert/certs/

$ vault write auth/cert/certs/web     display_name=web     policies=web,prod     certificate=@web-cert.pem     ttl=3600
Success! Data written to: auth/cert/certs/web

$ vault list auth/cert/certs/
Keys
----
web
```

**Comment by Fauth** [comment]
Wouldn't it be more logical to return an empty list when no cert is configured?
