### ISSUE TITLE
Go API - KV version 2 not working for Delete

### ISSUE THREAD

**Issue by RoValentim** [hashicorp/vault#5057]
KV version 2 changed request from DELETE to POST and versions number are now required.

Changing that worked for me, but lost the KV version 1 compatibility.

Would be nice to have a second parameter as interface, if that is nil, use version 1, if not, use version 2.

**Comment by briankassouf** [comment]
Deleting a specific version changed to a POST, but deleting the latest version of the key is still a DELETE:

https://www.vaultproject.io/api/secret/kv/kv-v2.html#delete-latest-version-of-secret

**Comment by RoValentim** [comment]
That's what I said in my issue...

Look the code at https://github.com/hashicorp/vault/blob/master/api/logical.go in line 145.

Is that wright to work in KV version 2?

**Comment by jefferai** [comment]
What is your actual code including paths?

**Comment by jefferai** [comment]
Specifically are you actually using /data/ in your paths?
