### ISSUE TITLE
Dead vault nodes remain as vault services in the consul catalog

### ISSUE THREAD

**Issue by rvaidya** [hashicorp/vault#5060]
**Describe the bug**

Dead vault nodes remain as vault services in the consul catalog.  This becomes problematic when I run a `terraform apply` that recreates machines.  Other machines may get the vault server's old IP addresses, and they retain the vault service definition.

I now have 4 vault "nodes" in my catalog that aren't actually vault nodes.  This includes 3 consul servers, which I really don't want to force-leave from the cluster (if that would even fix it - doesn't seem to do anything for the other misrepresented node).

None of these machines has their own service definition.

**To Reproduce**
1. Add a vault node and some other machines to an infrastructure orchestrator like terraform
2. `terraform apply`
3. Change config that forces the recreation of all machines and `terraform apply`
4. If another machine gets the vault server's old IP address, it is still considered a vault node in the service catalog.

**Expected behavior**
The only vault services that should appear in the catalog are actual Vault nodes.

**Related issues**

https://github.com/hashicorp/consul/issues/4499

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.4
* Vault CLI Version (retrieve with `vault version`):  0.10.4
* Server Operating System/Architecture: Ubuntu 16.04

Vault server configuration file(s):

```hcl
storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault/"
}

listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = 1
}

ui = true
```

**Additional context**

**Comment by rvaidya** [comment]
Related screenshots:

![vault_issue1](https://user-images.githubusercontent.com/128848/43799325-126b0e08-9a42-11e8-928e-a9b5658e204f.PNG)

![vault_issue2](https://user-images.githubusercontent.com/128848/43799334-1bb11318-9a42-11e8-83f1-5fbbd3fc8bd3.PNG)

I have no idea why consul-cluster-rs1g is green for Vault status - Vault is not running on this machine (agent or server).

**Comment by jefferai** [comment]
I think this is a consul issue? By definition if a Vault node is dead it can't do cleanup of its service.

If Vault _shutting down cleanly_ is leaving service definitions, that's probably a Vault issue (assuming that isn't desired behavior, which I'm not sure of at the moment).
