### ISSUE TITLE
Go API - KV version 2 still not working for Delete

### ISSUE THREAD

**Issue by RoValentim** [hashicorp/vault#5067]
Not duplicated with #5057, since it was closed without analysis.

KV version 2 changed request from DELETE to POST and versions number are now required.

The code at https://github.com/hashicorp/vault/blob/master/api/logical.go in line 145 support only KV version 1.

I suggest to change it from:
```
func (c *Logical) Delete(path string) (*Secret, error) {
    r := c.c.NewRequest("DELETE", "/v1/"+path)

```

To:
```
func (c *Logical) Delete(path string, versions ...map[string]interface{}) (*Secret, error) {
    var r *Request

    if versions == nil {
        r = c.c.NewRequest("DELETE", "/v1/"+path)
    } else {
        r = c.c.NewRequest("POST", "/v1/"+path)
        if err := r.SetJSONBody(versions[0); err != nil {
                return nil, err
        }
    }

```

That worked for my initial tests, but I think it needs more test.

**Comment by jefferai** [comment]
As documented, delete is not the correct http verb to use for this operation. See comment in #5068 if you are interested in coding some helper functions up.
