### ISSUE TITLE
Vault AWS ELB

### ISSUE THREAD

**Issue by rayana45tulasiram** [hashicorp/vault#5076]
**Is your feature request related to a problem? Please describe.**
I need a documentation how can i point two vault servers hosted in AWS  ( standby/active ) to AWS ELB to perform automatic load balancing

**Describe the solution you'd like**
I need a documentation how can i point two vault servers hosted in AWS  ( standby/active ) to AWS ELB to perform automatic load balancing

**Describe alternatives you've considered**
Other Load balancing can also be considered 

**Explain any additional use-cases**
My vault public URL should be available online all the time and on backend i should provide vault A & vault B attached to it 

**Additional context**

**Comment by jefferai** [comment]
See https://github.com/hashicorp/vault/issues/new?template=ask-a-question.md
