### ISSUE TITLE
Client cert/key issue when do postgresql database engine config 

### ISSUE THREAD

**Issue by devops2seedlink** [hashicorp/vault#5082]
**Describe the bug**
When trying to config a postgresql database engine, it reports following error.
<pre>
vault write database/config/bug-reproduce plugin_name=postgresql-database-plugin allowed_roles="test" connection_url="postgresql://{{username}}:{{password}}@db_host:5432/postgres" username="root-user" password="root-passwd"
Error writing data to database/config/bug-reproduce: Error making API request.

URL: PUT https://localhost:8200/v1/database/config/bug-reproduce
Code: 400. Errors:

* error creating database object: error verifying connection: stat /root/.postgresql/postgresql.crt: permission denied
</pre>

While my vault is running by "vault" user in server
<pre>
ps -ef | grep vault
vault     xxxx  xxxx  0 Aug09 ?        00:01:20 /usr/local/bin/vault server --config /etc/vault/vault.conf
</pre>

From https://github.com/lib/pq/blob/master/ssl.go#L75, it should require client cert from "\<user home\>/.postgresql".
<pre>
// sslClientCertificates adds the certificate specified in the "sslcert" and
// "sslkey" settings, or if they aren't set, from the .postgresql directory
// in the user's home directory. The configured files must exist and have
// the correct permissions.
func sslClientCertificates(tlsConf *tls.Config, o values) error {
	// user.Current() might fail when cross-compiling. We have to ignore the
	// error and continue without home directory defaults, since we wouldn't
	// know from where to load them.
	user, _ := user.Current()

	// In libpq, the client certificate is only loaded if the setting is not blank.
	//
	// https://github.com/postgres/postgres/blob/REL9_6_2/src/interfaces/libpq/fe-secure-openssl.c#L1036-L1037
	sslcert := o["sslcert"]
	if len(sslcert) == 0 && user != nil {
		sslcert = filepath.Join(user.HomeDir, ".postgresql", "postgresql.crt")
	}
	// https://github.com/postgres/postgres/blob/REL9_6_2/src/interfaces/libpq/fe-secure-openssl.c#L1045
	if len(sslcert) == 0 {
		return nil
	}
	// https://github.com/postgres/postgres/blob/REL9_6_2/src/interfaces/libpq/fe-secure-openssl.c#L1050:L1054
	if _, err := os.Stat(sslcert); os.IsNotExist(err) {
		return nil
	} else if err != nil {
		return err
	}
...
</pre>

Why it try to loads client cert from root home?

**To Reproduce**
1. Login
2. Run `vault secrets enable database` 
3. Run `vault write database/config/bug-reproduce plugin_name=postgresql-database-plugin allowed_roles="test" connection_url="postgresql://{{username}}:{{password}}@<db host>:5432/postgres" username="root-user" password="root-passwd"`

**Expected behavior**
Should not report error.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
<pre>
vault status
Key             Value
---             -----
Seal Type       shamir
Sealed          false
Total Shares    5
Threshold       3
Version         0.10.4
Cluster Name    vault-cluster-xxxxx
Cluster ID      xxxxxxx
HA Enabled      true
HA Cluster      https://10.x.x.x:8201
HA Mode         active
</pre>
* Vault CLI Version (retrieve with `vault version`):
<pre>
vault version
Vault v0.10.4 ('e21712a687889de1125e0a12a980420b1a4f72d3')
</pre>
* Server Operating System/Architecture:
<pre>
uname -a
Linux xxxx 4.4.0-93-generic #116~14.04.1-Ubuntu SMP Mon Aug 14 16:07:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
</pre>

Vault server configuration file(s):

```hcl
storage "etcd" {
  address  = "http://localhost:2379"
  etcd_api = "v3"
  ha_enabled = "true"
  disable_mlock = "1"
  redirect_addr = "http://10.x.x.x:8200"
}

listener "tcp" {
  address = "127.0.0.1:8200"
  tls_key_file = "<path>/vault_local.key"
  tls_cert_file = "<path>/vault_local.pem"
}
```

**Comment by jefferai** [comment]
Based on the comment in that function, it looks like it's trying to load it from your home directory because you're not passing `sslcert` and `sslkey` values in your postgres url.

**Comment by jefferai** [comment]
Closing, please ping if you are still having troubles.
