### ISSUE TITLE
Force tokens to be created under an specific policy

### ISSUE THREAD

**Issue by gcaracuel** [hashicorp/vault#5089]
Using token auth, I would like to allow token that belongs to a policy to be able to create another tokens (orphan or not), but I will only allow those new tokens to be generated assigned to an specific policy, of course this policy must be also applied to the 'parent', so that the rule that created tokens policies are a subset of parent token.

From using policies 'allowed_parameters' directive setting policies to allow only the desired policy or policies set, but it does seems to now work. To me it looks like the right way to do this feature is implemented.

Use case explanation: Provide a token to users/applications that can only create token under that closed policy so they can provide it to anyone else, and for example use those tokens as TTL cubbyholes for example. I have the option to use Approle Auth here but I would like to manage the parent tokens on my own by using token auth.

More context at: https://stackoverflow.com/questions/51479459/vault-how-to-force-tokens-to-be-created-under-an-specific-policy

Couldn't find a similar feature request opened and non results at the related stackoverflow question but please let me now how to contribute to any other open feature request that might be related to this one.

**Comment by jefferai** [comment]
See https://www.vaultproject.io/api/auth/token/index.html#create-update-token-role

**Comment by jefferai** [comment]
Closing, please ping if anything more is needed.
