### ISSUE TITLE
Please consider adding context.Context as a first argument to client's API methods

### ISSUE THREAD

**Issue by danilvpetrov** [hashicorp/vault#5090]
Currently API client methods (accessible via `Sys()`, `Auth()`, `Logical()`, etc.) do not have a way for a user to pass `context.Context` to the HTTP request. Could you please consider adding the context as the first argument to all client's methods that perform HTTP call? 

For example, adding context to the `client.Sys().Seal()` call could be as follows:
```
func (c *Sys) Seal(ctx context.Context) error {
	r := c.c.NewRequest("PUT", "/v1/sys/seal")

	ctx, cancelFunc := context.WithCancel(ctx)
	defer cancelFunc()
	resp, err := c.c.RawRequestWithContext(ctx, r)
	if err == nil {
		defer resp.Body.Close()
	}
	return err
}
```
I understand that it would be a breaking change, but IMHO it would provide a user with a bit more flexible control over a HTTP call.

Thank you.

**Comment by jefferai** [comment]
We won't be doing this with the current API due to it breaking every call, but we hope (and have some coding towards) offering more automatically generated API libraries going forward, which would then incorporate this. So "it's on the way" but I can't give a timeline.

**Comment by danilvpetrov** [comment]
Thanks for you reply. It's good to know you are considering this.

**Comment by jefferai** [comment]
Yep. If you want to use context right now, you can use RawRequestWithContext directly, but we don't want to break the API in such a massive way until we can do a whole refresh of the library. When we do this will definitely be included!

**Comment by bmoylan** [comment]
I've proposed a non-breaking way to do this in #5760
