### ISSUE TITLE
Forget to copy the Root token and unseal token

### ISSUE THREAD

**Issue by vaibhavbhanawat01** [hashicorp/vault#5095]
Hi, I forget to note the Root token and unseal token. Is there is any way i can retrive this Token

**Comment by jefferai** [comment]
No, sorry. If there were Vault wouldn't be secure :-D

**Comment by vaibhavbhanawat01** [comment]
So how can i reterive the Root Token and unseal key again and also my .vault-token file is also deleted accidently

**Comment by vaibhavbhanawat01** [comment]
is there is any way i can restart the vault server again ?

**Comment by jefferai** [comment]
No. And please stop posting the same question all over the place or I will be forced to report you to GitHub for abuse. Every time you post on an old issue -- after already having your question answered here -- you are causing notifications to go out to all of the subscribers of those old issues, for something totally unrelated to them.
