### ISSUE TITLE
jwt auth method

### ISSUE THREAD

**Issue by rexysihombing** [hashicorp/vault#5098]
Halo guys, I have error when I log into vault.
The command like this:
`curl --request POST --data '{"jwt": "'"$KUBE_TOKEN"'", "role": "postgres"}' http://torpid-kangaroo-vault:8200/v1/auth/kubernetes/login`

And the error messages like this:
`{"errors":["missing client token"]}`

**How to solve this problem???**

**Comment by jefferai** [comment]
What is the output of `vault mounts`?

**Comment by jefferai** [comment]
Sorry, I should have said `vault auth list`

**Comment by jefferai** [comment]
And you're also generally better off using ${KUBE_TOKEN}
