### ISSUE TITLE
HTTP API for getting secrets?

### ISSUE THREAD

**Issue by bkeroackdsc** [hashicorp/vault#511]
Perhaps I'm being dense, but even after looking through the docs and the interactive tutorial, it seems that the [API docs](https://vaultproject.io/docs/http/index.html) contain everything _except_ how to simply read/write secrets!

After unsealing/authing, how can a client application actually begin reading/writing secrets?

**Comment by sethvargo** [comment]
Hi @bkeroackdsc 

Everything is done via the HTTP API and the paths and methods are documented on each page. For example: https://vaultproject.io/docs/secrets/aws/index.html (scroll down to API). Each page should have API documentation like this that details the HTTP endpoints.

You might also be interested in looking at the embedded Vault go library or the vault-ruby client which use the HTTP API to make requests to Vault. Thanks!

Does that answer your question?

**Comment by mfischer-zd** [comment]
@sethvargo, the generic secrets backend doesn't have HTTP API documentation for the generic secrets backend (/secrets/).  I think it's worth re-titling the issue so that it can be addressed.

**Comment by sethvargo** [comment]
@mfischer-zd please open another issue for that. I'd like to see what @bkeroackdsc thinks since his question is more high-level :smile:. We can definitely open individual issues as you see them to improve the docs. Thanks!

**Comment by bkeroackdsc** [comment]
@sethvargo What I meant is that there isn't a section/page which describes how to read/write secrets. After looking more closely, the info is [here](https://vaultproject.io/docs/http/index.html) ("Reading and Writing Secrets".

I've skimmed through the HTTP API docs a bunch of times and never noticed it. I think it needs to be moved to a new section linked to in the sidebar, in order to be easily found.
