### ISSUE TITLE
Mysql backend table creation error using InnoDB and utf8 charset

### ISSUE THREAD

**Issue by drampelt** [hashicorp/vault#512]
When using a mysql database with the utf8 charset and InnoDB engine, vault fails to create the table:
```
Error initializing backend of type mysql: failed to create mysql table: Error 1071: Specified key was too long; max key length is 767 bytes
```

After [some research](https://stackoverflow.com/a/16474039), I discovered that this is due to the 767 byte limit of InnoDB prefixes. So the issue is that the primary key (vault_key) is a varchar with length 512, exceeding the 767 byte limit as mysql use 3 bytes per character in utf8.

I tried creating the table manually with a smaller length (255) that would fit in this limit, but unfortunately mysql still validates the size even when using `CREATE TABLE IF NOT EXISTS` and the table does already exist.

**Comment by armon** [comment]
@drampelt Can you try changing the type to `varbinary`? I don't think we actually need to care about the UTF encoding and that will save us some bytes. Go only works in UTF internally anyways.

**Comment by drampelt** [comment]
Thanks for the suggestion, the table creates fine with `varbinary(512)`. I'm not sure if vault works with it however as I haven't been able to get it compiling locally yet.

**Comment by drampelt** [comment]
Ok got vault working locally and as far as I can tell everything is working great with the primary key being `varbinary(512)`

**Comment by drampelt** [comment]
Created pull request #522 to solve this

**Comment by dle-fr** [comment]
Still happening when using HA with Mysql Backend:

`Error initializing storage of type mysql: failed to create mysql table: Error 1071: Specified key was too long; max key length is 767 bytes`

The vault table exists, but does HA mode try to create another table to store HA lock or something? (I didn't dig into the code)

To reproduce, in conf file, just add `ha_enabled = "true"` in `storage "mysql"` section.

**Comment by jefferai** [comment]
I would suggest filing a new bug about this and then linking to it from the PR that added MySQL HA support.
