### ISSUE TITLE
Inconsistency in documentation for read/write from CRUD operations

### ISSUE THREAD

**Issue by anarwal27** [hashicorp/vault#5124]
While using APIs in order to Read/write secrets using API, do we need to use "secret/hello" or should I be using "secret/data/hello" to perform any CRUD operation?

Documentation here: https://www.vaultproject.io/api/index.html#reading-writing-and-listing-secrets 

vs here: https://www.vaultproject.io/api/secret/kv/kv-v2.html#read-secret-version

 is inconsistent and causing an issue.

**Comment by anarwal27** [comment]
Additional update, I believe it has to do with latest vault installation. It picks v2 by default for performing API operation, documentation does not talk anywhere on how to use v1.

**Comment by chrishoffman** [comment]
Right now vault only uses KVv2 for the default dev server mount.  Although this documentation refers to the kv backend, it is more about the general interaction with the vault api and how to read and write data.  I will update that doc explicitly specify the v1 api.  

Additionally, we do have docs describing both APIs. 
See https://www.vaultproject.io/docs/secrets/kv/index.html and https://www.vaultproject.io/api/secret/kv/index.html.
