### ISSUE TITLE
Improve documentation on lease lifespan and data lifespan

### ISSUE THREAD

**Issue by armon** [hashicorp/vault#513]
The documentation is not clear enough on the lifecycle of a lease and how that relates to data in Vault.

See this thread for more context: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/XChqN9kwTHk/Hs2hZwsFBwAJ

**Comment by wwalker** [comment]
Additionally, a note along the lines of "for mount paths that are of type "secret", lease information is advisory only, no revocation is enforced by vault itself for this path type" would be welcome.

I know that this is specified in the path-help, but before you get to the path help, you are given an expectation that anything with a lease is automatically revoked upon expiry.

**Comment by jefferai** [comment]
This has been enhanced significantly over the years.
