### ISSUE TITLE
Cannot connect to dev server

### ISSUE THREAD

**Issue by eduardonunesp** [hashicorp/vault#5131]
Command `status` failed to connect to `vault server -dev`

1. Run `vault server -dev`
2. On a second terminal run `vault status`
3. See the error on `vault status` output 

```Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: http: server gave HTTP response to HTTPS client```

Should return the vault status information

**Environment:**
* Vault Server `Vault v0.10.4 ('e21712a687889de1125e0a12a980420b1a4f72d3')`
* Vault CLI Version `Vault v0.10.4 ('e21712a687889de1125e0a12a980420b1a4f72d3')`
* Server Operating System/Architecture: `macOS 10.13.6` 

**Extra info**

```
$ lsof -i -n -P | grep -i 8200
vault     45703 computer2    5u  IPv4 0x5e7bed993054e4d1      0t0  TCP 127.0.0.1:8200 (LISTEN)
```

```
$ curl 127.0.0.1:8200
<a href="/ui/">Temporary Redirect</a>.
```

```
$ curl https://127.0.0.1:8200
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

**Comment by joelthompson** [comment]
If you look at the output of running `vault server -dev` you'll see this:

```
The only step you need to take is to set the following
environment variables:

    export VAULT_ADDR='http://127.0.0.1:8200'
```
You need to do that in your second terminal.

**Comment by chrishoffman** [comment]
The dev server uses HTTP and not HTTPS but the CLI uses HTTPS by default.  You can set this value by setting the `VAULT_ADDR` environment variable or use the `-address` CLI parameter.

**Comment by eduardonunesp** [comment]
Oh sorry for not added this on the bug report, actually I did `export VAULT_ADDR='http://127.0.0.1:8200'`. It's on the [docs](https://www.vaultproject.io/intro/getting-started/dev-server.html)

**Comment by chrishoffman** [comment]
These are general guidelines and do not work in all setups depending on environment and security settings. Try running `env | grep VAULT` in the terminal where you are running the CLI commands and see what the values are set to.

**Comment by eduardonunesp** [comment]
Ok, I'll try on a different environment next week, thanks
