### ISSUE TITLE
Generic secrets backend HTTP API documentation missing

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/vault#514]
The generic secrets backend (/secrets/) doesn't have HTTP API documentation like the AWS and other backends do.

https://vaultproject.io/docs/secrets/generic/index.html

**Comment by sethvargo** [comment]
Thanks :smile:

**Comment by mp911de** [comment]
As of today, the documentation is present but the docs reveal an asymmetric API. It's quite surprising to post `{key: value, ...}` on `PUT` and the `GET` request returns `{lease_duration: ..., data: {key:value}}`.

**Comment by jefferai** [comment]
Other than some `/sys` endpoints, Vault's response format is the same regardless of endpoint. The behavior of `lease_duration` with respect to the `generic` backend is documented and serves a specific purpose.
