### ISSUE TITLE
Unsorted list of secrets in UI for Generic/KV version 1

### ISSUE THREAD

**Issue by Garath620** [hashicorp/vault#5141]
**Describe the bug**
 Vault UI displays an unsorted list of secrets for Generic/KV V1 secret store.

**Expected behavior**
 The list of secret should be sorted alphabetically like in KV V2 secret store.

**Environment:**
* Vault Server Version 0.10.4

**Comment by jefferai** [comment]
Just to be clear, "sorted correctly" implies that there is a sorting order. There's not. It just so happens that most storage implementations, when listing, will return a sorted set of strings.

At this point, it's unclear whether you're describing a desired improvement to the file storage engine, or if you are raising some kind of issue with the UI. I don't know of any reason that V1/V2 would behave differently.

**Comment by Garath620** [comment]
Hello @jefferai 

I create a kv secrets engine v1 and an other in v2.
`vault secrets enable -path=testsort -version=1 kv`
`vault secrets enable -path=testsort2 -version=2 kv`
I put same data into and in UI I see this :
![sortkv1](https://user-images.githubusercontent.com/28151179/44462674-a6eeec00-a615-11e8-915e-33f6e1af9ef1.png)
![sortkv2](https://user-images.githubusercontent.com/28151179/44462677-ace4cd00-a615-11e8-9299-f6a461d577df.png)

**Comment by Garath620** [comment]
Thank you!
