### ISSUE TITLE
Escaping LDAP group characters - possible bug

### ISSUE THREAD

**Issue by margiki** [hashicorp/vault#5146]
Hey! This is a possible bug, or I wrongly escaped the characters.

Writing the policies for an LDAP group that contains both space `" "` and das `"-"`, Vault writes it without error.  But when logging in, it does **not map** the policy to the users which are part of that group:
`vault write auth/ldap/groups/"My LDAP group - USA" policies=engineer`

I tried and they didn't work as well:
`vault write auth/ldap/groups/"My%20LDAP%20group%20-%20USA" policies=engineer`
`vault write auth/ldap/groups/"My\ LDAP\ group\ -\ USA" policies=engineer`
`vault write auth/ldap/groups/"My LDAP group \- USA" policies=engineer`

However, if the groups contains only space `" "` or dash `" "` it works well.
ex: `vault write auth/ldap/groups/"My LDAP group" policies=engineer`

Is this a bug?

Vault CLI: v0.10.4
Vault on server: 0.10.1

**Comment by margiki** [comment]
Are there any more details I missed?

**Comment by jefferai** [comment]
No, I think it's just that nobody has any ideas at the moment...

**Comment by michelvocks** [comment]
Hi @margiki!

I tried to reproduce the behavior you have mentioned but I'm unable to do so with Vault 1.3.0.
I can see that the groups-command is correctly transformed:

```
vault write -output-curl-string auth/ldap/groups/"My LDAP group - USA" policies=admin
curl -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"policies":"admin"}' http://127.0.0.1:8200/v1/auth/ldap/groups/My%20LDAP%20group%20-%20USA
```

And if I login I get the correct policy attached to my token:
```
Key                    Value
---                    -----
token                  s.t38KeQpdgDY6DtrqZuEkUgtw
token_accessor         dkHNsOmMBsUEIK88CvPWzcLE
token_duration         768h
token_renewable        true
token_policies         ["admin" "default"]
identity_policies      []
policies               ["admin" "default"]
token_meta_username    adam
```

I'm closing this issue for now but feel free to open a new issue if this is still a problem for you with Vault 1.3.0.

Cheers,
Michel
