### ISSUE TITLE
questions about root_token

### ISSUE THREAD

**Issue by lindalovemusic** [hashicorp/vault#5148]
Hello Vault Team! I have a question about the root token. I would like to know is the root token must exist? In other word, is it true to say that, if I want to use vault, I have to have a root token? Thanks for the help!!

**Comment by briankassouf** [comment]
The root token can be revoked once you are done using it. `vault token revoke <root token>` will delete it. Check out https://www.vaultproject.io/docs/concepts/tokens.html#root-tokens for more information about root tokens

**Comment by lindalovemusic** [comment]
Thank you Brian! I have one more question... like if I want to use jwt auth method and I have to create roles, but I don't want to use the root token, so could I create a token and the token can only create roles for jwt and cannot do anything else... I don't want use the root token when I am using the API... so I wondering that could I create a token to do that instead... Thanks a lot!!

**Comment by lindalovemusic** [comment]
and since every other token is derived from vault token, if I revoked root token, every other token are also gonna be invalid... so can I revoke the root token?

**Comment by jefferai** [comment]
Yes, you can create a token that can only create JWT roles; just specify the right paths and operations.

Tokens generated from auth backends are orphan tokens (without a parent) and tracked separately. Revoking the root token will have no impact. You can also use the `-orphan` flag with `vault token create` to generate an orphan token if you have appropriate privileges (which a root token will, by definition).
