### ISSUE TITLE
Renewable Secrets Question

### ISSUE THREAD

**Issue by ekristen** [hashicorp/vault#515]
How do I get systems to monitor and renew their leases? 

For example if I have consul that needs a SSL certificate to from the PKI backend, how to request, install, start consul, monitor and renew before it expires and subsequently install the new cert and restart, etc?

**Comment by sethvargo** [comment]
Hi there,

Just a friendly reminder that you don't need to tag us in issues :smile:. We'll get a notification for each issue opened.

The generally recommended pattern is to renew at `leaseDuration/2.0`. This is the approach [Consul Template](https://github.com/hashicorp/consul-template/blob/a8e96a0fa031ae461a6e91367881702a9f170f17/dependency/vault_secret.go#L44) takes when it renews secrets.

It sounds like you want Consul Template, since it can handle that "install + restart" cycle.

**Comment by ekristen** [comment]
Ok. 

I suppose I can run consul-template out of band of my docker containers to control their configs.

I was thinking it would be nice to have consul-template as the entry process and that consul template calls another process after it generates the config file. If something changes it kills and restarts the process again. I looked through all docs, but didn't see this as a viable option.

**Comment by armon** [comment]
@ekristen As Seth said, really either the app is "Vault aware" and is able to do that automatically, or it is completely unaware and must be wrapped in something like CT to handle that.

**Comment by sethvargo** [comment]
We have a number of client libraries (official and unofficial) that can be used to make an application Vault-aware, or Consul Template is fully vault-aware and handles most of this for you.

Does that answer your question?

**Comment by ekristen** [comment]
Makes sense ... however I have one more question/scenario.

In the case of Consul, where a SSL certs and private key are required on startup, how do you recommend delivering those out of vault? Starting consul as a service, and then just running consul-template and telling the service to restart when the file is updated? Or is there another method I'm missing?

AFAIK consul template isn't designed to start and keep a process running, it is more designed to call things like `service nginx restart`

**Comment by sethvargo** [comment]
Consul Template just runs whatever bash command you give it. So I would recommend having CT call out to start Consul after it writes the file. Whether you're sending a signal to something like upstart or running `kill` doesn't really matter to CT - it'll just fire an arbitrary script for you.

**Comment by jefferai** [comment]
Please re-open if you need more help!
