### ISSUE TITLE
Unable to restore existing Transit key atomically

### ISSUE THREAD

**Issue by stampycode** [hashicorp/vault#5156]
As per [Transit Restore-Key](https://www.vaultproject.io/api/secret/transit/index.html#restore-key) documentation, I wish to restore a transit endpoint that I had backed up, but I am not able to do so unless the existing endpoint deleted.

Vault requires the key to be deleted first, so it can be restored.

Unfortunately the delete-key/restore-key process is not atomic (as it's 2 separate requests), so any requests to the endpoint between the key deletion and the key being restored, cause application errors.

It is not documented that the Transit Restore-Key endpoint should fail if attempting to restore an endpoint that exists. In fact, I would _expect_ this endpoint to exist in many scenarios.

**Solution**
Add a flag to the Transit Restore-Key POST request to allow replacing an existing endpoint, so the process of restoring from a backup can be atomic.
*Or* just allow the Transit Restore-Key endpoint to replace an existing endpoint by default.

👍

**Comment by jefferai** [comment]
It's not meant to be atomic. It's a two-step process on purpose, because it ensures that you cannot accidentally overwrite data, and it's much easier to ACL on paths than parameters.

We'll fix the documentation issue.

**Comment by stampycode** [comment]
Atomicity and accident-prevention aren't mutually exclusive.
You're basically claiming that it's impossible to accidentally overwrite data.

The current method just means I have to make two calls to Vault in my script instead of one - a call to delete the endpoint, and another call to restore it.
This leaves a gap between the two calls, where incoming requests get a "404" error where there would normally be a 20x.
This also means there is a higher risk if the "restore" endpoint fails, because you've deleted the existing endpoint, so I'm now left with no endpoint at all, and possibly a broken backup or a restore endpoint that I don't have permission to use.

The solution to add a flag to "overwrite" in an atomic sense would provide much more security and "accident prevention" than the current solution.

Please reconsider.

**Comment by stampycode** [comment]
> users will blindly always set the overwrite flag on every restore call to not bother with it possibly failing because they forgot to set it
So the call should fail if that flag is set and the endpoint is empty, no?

> If your keys are out of whack to the point where you need to restore from a backup, isn't a 404 preferable to using bad keys?
This is assuming that the only reason to use the restore endpoint is that the existing endpoint is not working as expected. Indeed I'm using the restore endpoint to restore Vault keys from another instance, a sort of scripted copy from one Vault to another - the endpoint isn't broken, but it needs to be updated, but I'm not currently able to do this without causing some 404'd requests.
