### ISSUE TITLE
vault agent auth-auth certificate method

### ISSUE THREAD

**Issue by toomasp** [hashicorp/vault#5166]
**Is your feature request related to a problem? Please describe.**

https://www.vaultproject.io/docs/agent/autoauth/methods/index.html currently lists: 

1. AWS
2. Azure
3. GCP
4. JWT
5. Kubernetes

Would you please add support for certificate authentication?

**Describe the solution you'd like**

Specify cert to use for auth, everything else works as usual.

**Comment by fuero** [comment]
Would be great for Puppet shops - using the puppet CA trust to provision tokens is a no-brainer.

**Comment by mgaffney** [comment]
Closed by #6652
