### ISSUE TITLE
tls_client_ca_file not recognized in 0.10.4

### ISSUE THREAD

**Issue by snesbittsea** [hashicorp/vault#5168]
Vault does not appear to use tls_client_cert_file settings to validate tls certificates.

Vault is not recognizing/validating root authority certificate provided to Vault via tls_client_cert_file. If same certificate is installed as part of the system certificate step, then things work and server certificate is

**To Reproduce**
See: https://gist.github.com/snesbittsea/104411874c94f25637c6ed8c0b87bd77 for configuration and data in question

**Expected behavior**
Setting tls_client_cert_file to a root certifcate should allow TLS without requiring Root_CA in system.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key                Value
---                -----
Seal Type          shamir
Sealed             true
Total Shares       5
Threshold          3
Unseal Progress    0/3
Unseal Nonce       n/a
Version            0.10.4
HA Enabled         true
```
* Vault CLI Version (retrieve with `vault version`): Vault v0.10.4 ('e21712a687889de1125e0a12a980420b1a4f72d3')
* Server Operating System/Architecture: Linux/Ubuntu Bioic 64

Vault server configuration file(s): See referenced Gist
cat
```

**Additional context**
Add any other context about the problem here.

**Comment by jefferai** [comment]
`tls_client_cert_file` is not a directive that exists either on the command line or in configuration. Did you mean to set `-ca-cert` on the CLI?

**Comment by snesbittsea** [comment]
Hmm,  the documentation for the tcp listener lists it. Reference:
 https://www.vaultproject.io/docs/configuration/listener/tcp.html

**Comment by snesbittsea** [comment]
A bit more info...

Given the following listener configuration:
`listener "tcp" {
  address = "127.0.0.1:8200"
  tls_cert_file = "/etc/vault/tls/vault.crt"
  tls_key_file = "/etc/vault/tls/vault.key"
  tls_client_ca="/etc/vault/tls/CA_cert.crt"
  tls_min_version  = "tls12"
  tls_cipher_suites = "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA"
  tls_prefer_server_cipher_suites = "false"
  tls_disable = "false"
}`

Invoking `vault status -ca-cert /etc/vault/tls/CA_cert.crt` succeeds without error

Invoking `vault status` fails with `Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "AussiesWithTails Root CA")`

It seems more and more likely to me that there is a vault issue, or a complete misunderstanding on my part, in the parsing of the tls_client_ca listener configuration parameter.

**Comment by jefferai** [comment]
The error is coming not from the server but from the Vault CLI. It doesn't trust the server's CA file. When you use `-ca-cert` you're telling it what CA cert to trust, and thus it succeeds. Without it, it only has the system roots to look at, which you've said does not have this CA cert in it.

The `tls_client_ca` parameter is only important when you've turned on https://www.vaultproject.io/docs/configuration/listener/tcp.html#tls_require_and_verify_client_cert -- it's the CA that will be used (if not part of the system roots) when requiring client TLS connections to be verified. By default, that's not turned on.

**Comment by snesbittsea** [comment]
Ok - that makes sense.

I'm still trying to figure out best practices for securing vault - should tls_require_and_verify_client_cert be enabled or is it overkill?

Thx for the help!

**Comment by jefferai** [comment]
Honestly, that's up to you :-)

**Comment by snesbittsea** [comment]
Thanks again for the help!

**Comment by kamalmost** [comment]
mmmm, way too much for bidirectional auth. i think its overkill. but, its there if you need it.

**Comment by kamalmost** [comment]
@snesbittsea , BTW, you need to concat the primary cert and the CA. check that link [https://www.vaultproject.io/docs/configuration/listener/tcp.html#tls_cert_file]
