### ISSUE TITLE
GCP Auth - "Could not find service account key or Google Oauth cert with given 'kid' id"

### ISSUE THREAD

**Issue by GNewbury1** [hashicorp/vault#5174]
**Describe the bug**

Vault is unable to verify the authenticity JWT Token, due to the `kid` field in the JWT header using the incorrect service account key. 

The key I'm using is created from a Google Service account, and the JSON file is referenced in the authentication (ie, it is used in `vault write auth/gcp/config credentials=@/google/key.json`), and this key which we're getting credentials from.

However, from research, Google Cloud Platform Service Accounts have a hidden key created which GCP and Google services itself uses. This key doesn't have a corresponding JSON file, and cannot be used by anything other than GCP/Google. It is this key which is being used to sign the JWT token.

There is no way to change which key is used. There is no way to delete the default key. There is no way to use the default key in the initial backend setup. As such, there is no way I can currently make use of the GCP auth backend because of this.

**To Reproduce**
1. Follow steps [here](https://cloud.google.com/solutions/using-vault-for-secret-management#authenticating_to_vault_using_cloud_iam) until step 3
2. Run `vault write -field=token auth/gcp/login role=dev-role jwt=${JWT_TOKEN} > ~/.vault-token`
3. See the follow response:
```
Error authenticating: Error making API request.

URL: PUT https://127.0.0.1:8200/v1/auth/gcp/login
Code: 400. Errors:

* could not find service account key or Google Oauth cert with given 'kid' id
```

**Expected behavior**
Authentication using GCP

**Environment:**
* Vault Server Version: `0.10.4`
* Vault CLI Version: `0.10.4`
* Server Operating System/Architecture: Ubuntu 18.04.1 Minimal VM

Vault server configuration file(s):

```hcl
ha_storage "consul" {
  address = "127.0.0.1:8500"
  path 	  = "vault/"
}

storage "consul"{
  address = "127.0.0.1:8500"
  path = "vault/"
}


listener "tcp" {
  address 	    = "0.0.0.0:8200"
  cluster_address = "10.0.0.15:8201"
  tls_cert_file = "/etc/vault/ssl/cert.pem"
  tls_key_file = "/etc/vault/ssl/key.pem"
  tls_disable = 0
}

api_addr = "http://10.0.0.15:8200"
cluster_addr = "https://10.0.0.15:8201"

```

**Comment by jefferai** [comment]
Please file at https://github.com/hashicorp/vault-plugin-auth-gcp so that the maintainer will see it. Thanks!

**Comment by GNewbury1** [comment]
Ah, my apologies! Will do
