### ISSUE TITLE
Token creation approach

### ISSUE THREAD

**Issue by rustyforeal** [hashicorp/vault#5207]
I have created multiple policies - sample below:

```
policyDataRW = "path \"secret/*\" {\ncapabilities = [\"create\",\"update\",\"read\"]\n}"
policyDataRO = "path \"secret/*\" {\ncapabilities = [\"read\"]\n}"
policyDataADM = "path \"secret/*\" {\ncapabilities = [\"create\",\"update\",\"read\",\"delete\",\"list\"]\n}"
policyTokenADM = "path \"auth/token/*\" {\ncapabilities = [\"create\",\"update\",\"read\",\"delete\",\"list\"]\n}"
```
and created a corresponding token attached to each of the above policies using the **root** token and made sure I set the below during creation of these tokens

```
postData = {
        "policies": policyName,
        "no_parent": True,
        "no_default_policy": True,
        "renewable": True,
        "ttl": "768h",
        "display_name": displayName
    }
```

Now, when I try and create new tokens using the token attached to policy `policyTokenADM` - i get the below

`[(400, u'{"errors":["child policies must be subset of parent"]}\n')](url)`

What am i doing wrong? I want to have a dedicated token which can do CRUD operations on /auth/token path ONLY and I have created a token already for this(policyname `policyTokenADM`) - but I am unable to do the same.
TIA

**Comment by rustyforeal** [comment]
by adding `sudo` to `policyTokenADM` - does that imply that any token provisioned under the policy `policyTokenADM` will be like a `root` token? if yes - the whole purpose of me creating tokens attached to `policyTokenADM` is defeated!

**Comment by jefferai** [comment]
`sudo` is a per-path capability that enables administrative functionality on specific endpoints that are documented. It does mean you can generate basically any token you want (except a root token) from that endpoint, which seems like what you want. You may also want to look into token roles as a safer way of doing this, though (e.g. https://www.vaultproject.io/api/auth/token/index.html#create-update-token-role)
