### ISSUE TITLE
Policy parsing bug in 0.11.0

### ISSUE THREAD

**Issue by Garath620** [hashicorp/vault#5219]
**Describe the bug**
Policy syntax is not accepted anymore by the latest version.

**To Reproduce**
Create new policy with this content :
`{"path":{"secret/*":{"capabilities":["read"]}}}`
Return :
"Error failed to validate policy templating: unbalanced templating characters"

To be accepted I must use this syntax :
`{"path":{"secret/*":{"capabilities":["read"]} } }`

**Expected behavior**
Accept valid json regardless of space character like 0.10.4 version

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.11.0

**Additional context**
```
KO: {"path":{"secret/*":{"capabilities":["read"]}}}
OK: {"path":{"secret/*":{"capabilities":["read"]} } }
```

**Comment by alitheg** [comment]
I also found this when I restarted my docker-based install and it upgraded. Pushed back the tag to 0.10.4 until it's fixed!

**Comment by gowthamsubbu** [comment]
@chrishoffman @jefferai Is the fix available in 0.11.0 image ? Or will be it in 0.11.1 ? We are still getting "Error failed to validate policy templating: unbalanced templating characters" exception when posting base64 encoded ACL policy.

{"path":{"secret/*":{"capabilities":["read"]}}}
{"path":{"secret/*":{"capabilities":["read"]} } }

**Comment by chrishoffman** [comment]
There will be a 0.11.1 shortly to address this issue.  You can also build from master right now to see if it addresses the issue.

**Comment by gowthamsubbu** [comment]
@chrishoffman Thanks for the update. I couldn't find the master tag in the Vault docker hub.

<img width="1403" alt="screen shot 2018-09-06 at 10 11 25 am" src="https://user-images.githubusercontent.com/34745306/45163087-7d10fa00-b1bd-11e8-8abc-8fc4ee3acb5b.png">

**Comment by alitheg** [comment]
@gowthamsubbu That's exactly my issue - using docker means we're reliant on a build being produced and pushed to Docker Hub. I'm content to know it's fixed and incoming. Thanks for the update @chrishoffman!

**Comment by chrishoffman** [comment]
I meant from source.  We don't publish master docker images.

**Comment by alexwwang** [comment]
I have to use HCL format to compose my policy strings instead of json format to bypass this bug in vault 0.11.
