### ISSUE TITLE
vault read pki/roles/<role> max_ttl type

### ISSUE THREAD

**Issue by bozho** [hashicorp/vault#5222]
**Describe the bug**
max_ttl value for a PKI role is different for different output formats.

Running `vault read pki/roles/<role>` returns max_ttl value as it was submitted (e.g. "87600h"). Running the same command with output format set to json or yaml returns an integer of seconds (e.g. 315360000)

**To Reproduce**
1. Run `vault read pki/roles/<role>` for an existing role.
2. Run `vault read -format=json pki/roles/<role>` for an existing role.
3. max_ttl values will be different.

**Expected behavior**
Preferably the original value as it was submitted in JSON/YAML output, or at least consistent value across output types.

**Environment:**
* Vault Server Version: 0.11.0
* Vault CLI Version: 0.11.0
* Server Operating System/Architecture: Debian 9 (server), Windows 10 (both native and WSL) client

**Additional context**
Using Ansible to configure Vault, including PKI roles. The bug complicates comparing PKI roles defined in the configuration against the existing ones.

Thank you!

**Comment by jefferai** [comment]
The CLI, being a human-oriented data display, tries to make TTLs more human-friendly. The underlying data is the same, and printing just that field should print seconds.

**Comment by jefferai** [comment]
BTW, this should be no problem with Ansible, since Ansible should be using the JSON or YAML output formats.

**Comment by bozho** [comment]
It's not a problem for Ansible reading the Vault configuration, it's a bit of a problem for humans writing the Ansible configuration :-)

To avoid re-applying the configuration on each run, the configuration I'm working on reads the existing Vault configuration and compares it with values in the Ansible configuration to decide whether there are any changes to apply.

This means that if `max_ttl` is written as `10h` in the Ansible configuration, it will always be different from `36000` seconds returned by Vault in JSON data. Hence, Ansible configuration needs to have `max_ttl` defined in seconds to avoid the problem (or do some parsing and time arithmetics, which I don't intend to do for a single setting :)

As I said, it's not a huge problem (only slightly decreases readability of the Ansible configuration), and if it works as intended, it's all good.

Thank you.
