### ISSUE TITLE
Support same metrics endpoints as nomad and consul

### ISSUE THREAD

**Issue by uepoch** [hashicorp/vault#5223]
**Is your feature request related to a problem? Please describe.**
Support for pulled metrics has been added in other Hashi's products
Having to log in the machine to SIGUSR in order to have human readable metrics available is painful
There's no friendly way to display metrics right now
with statsd protocol, there's no control from the monitoring software side about the frequency/precision/aggregation of time series 

**Describe the solution you'd like**
Support a v1/sys/metrics (unauth or auth, not sure what is best)
That either dumps the metrics from inMemSink in JSON or support format=prometheus in query params
(Exact same behavior as nomad and consul)

**Describe alternatives you've considered**
The only valid option is to use statsd right now, as circonus is not part of the monitoring team stack

**Explain any additional use-cases**
Consul had support added for Prometheus in late April
Prometheus is a quite standard solution today and supports labeling
This would allow users to quickly check metrics about a vault server running in dev environments

**Additional context

We are using statsd now, and (probably because of misconfigured things) ended up with graphite vs statsd not being synchronised thus producing empty chunks of time series quite often.
Used it for consul before our PR https://github.com/hashicorp/consul/issues/4014 was merged

After reading #2937 #1230 and #1415, I was wondering if Hashi changed its mind about adding metrics handler as you now support it on other projects.
Dumping text from the prom registry does not seem big and could fit in a 30 lines function given the use of expfmt if the networking code is a problem

What do you think ?

**Comment by jefferai** [comment]
No minds have been changed, the issue with Prometheus is specific to the way they require building in a listener to Vault just to run their own custom code.

This sounds totally fine, PR would be even more welcome :-D

**Comment by uepoch** [comment]
Ok, I will start working on it then !

**Comment by catsby** [comment]
Hello! I'm going to close this issue now as #5308 was merged. Thank you!
