### ISSUE TITLE
Vault sometimes doesn't report JWT mount in mount list

### ISSUE THREAD

**Issue by stefan-improbable** [hashicorp/vault#5224]
**Describe the bug**
I'm using JWT vault auth method https://www.vaultproject.io/docs/auth/jwt.html . If I want to map my OIDC groups to vault policies, I need to use identity groups and identity group aliases. In order to create a new identity group alias, I have to know mount_accessor (given path `jwt/`).

I wanted to use curl/vault command line utility to get them, but it sometimes doesn't give me any info for jwt/ mount point.

**To Reproduce**
`curl  --header "X-Vault-Token: $VAULT_TOKEN" --request GET ${VAULT_ADDR}/v1/sys/mounts` and `vault read -format json sys/mounts` sometimes does and sometimes doesn't return any information about JWT mount point.

**Expected behavior**
vault always returns correct info about mounts (including mount_accessor)

**Environment:**
* Vault Server Version: 0.10.4
* Vault CLI Version: curl
* Server Operating System/Architecture: Alpine Linux 3.8 (on vault server)

Vault server configuration file(s):

```hcl
storage "gcs" {
  bucket = "improbable-vault-alpha"
  credentials_file = "/var/run/secrets/gcloud/creds.json"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/tls/tls.crt"
  tls_key_file = "/tls/tls.key"
}

telemetry {
  statsd_address = "..."
}

ui = "true"
max_lease_ttl = ...
```

**Comment by chrishoffman** [comment]
Auth methods are not stored in the secret mount table but stored in the auth mount table.

Try `vault auth list` and `curl --header "X-Vault-Token: $VAULT_TOKEN" --request GET ${VAULT_ADDR}/v1/sys/auth`.
