### ISSUE TITLE
API /sys/generate-root

### ISSUE THREAD

**Issue by devabuse** [hashicorp/vault#5236]
Hi,

I'm trying to generate a new root token using the API. This works but returns an encoded_token. I am using an otp to call the /sys/generate/root/attempt.

The CLI interface provides a method to decode the root roken with the otp, but how do I do this using the rest API?

Thanks.

Regards,
Mike

**Comment by chrishoffman** [comment]
There is not one currently but may add one in the future.  The process of decoding the token is a relatively simple XOR of the bytes of the OTP against the bytes of the token.

See https://github.com/hashicorp/vault/blob/master/command/operator_generate_root.go#L338-L348.

**Comment by devabuse** [comment]
Thank you. I will figure this out on my end.

**Comment by devabuse** [comment]
I made a simplified version of the code you're using here: https://play.golang.org/p/9jkFl28Op2w with the idea to match the results in a PHP script. All of printed values match in both languages, so I should be on the right track.

The end result unfortunately is binary data. What am I missing? Does vault do something else with this binary result?

**Comment by raskchanky** [comment]
I'm going to close this for now, since it looks like there's not much here for us to do. Feel free to reopen if you want to discuss further.

**Comment by PayalSasmal10** [comment]
Hi , could anyone know how to decode this encoded_root_token, i am unable to do this.

**Comment by PayalSasmal10** [comment]
> Thank you. I will figure this out on my end.

Hi @devabuse , Did you figure it out how to decode this  using API?

**Comment by mrioqueiroz** [comment]
> Hi , could anyone know how to decode this encoded_root_token, i am unable to do this.

This [Node.js module](https://github.com/itslenny/base64-xor/blob/master/index.js) may help.
