### ISSUE TITLE
Kubernetes auth method

### ISSUE THREAD

**Issue by redi-vinogradov** [hashicorp/vault#5238]
**Describe the bug**
Cannot read secret using kubernetes auth:
$ export KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
$ curl --request POST --data '{"jwt": "'"${KUBE_TOKEN}"'", "role": "confd"}' http://vault-vault:8200/v1/auth/kubernetes/login
{"errors":["invalid character '\u003c' looking for beginning of value"]}

**To Reproduce**
1. Setup vault using incubator/vault helm chart in dev mode
2. Enable kubernetes auth
3. Use curl to login in the Vault using kubernetes jwt

**Expected behavior**
Successfull authentication should happen

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.1
* Vault CLI Version (retrieve with `vault version`): v0.10.1 
* Server Operating System/Architecture: CentOS 7.5

**Additional context**
$ vault auth list
```
Path           Type          Description
----           ----          -----------
kubernetes/    kubernetes    n/a
token/         token         token based credentials
```

Tried without env variable with the same result:
payload.json
```json
{
  "role": "confd",
  "jwt": "eyJhbGciOiJSUzI1NiIsIn..."
}
```
curl --request POST --data @payload.json http://vault-vault:8200/v1/auth/kubernetes/login
{"errors":["invalid character '\u003c' looking for beginning of value"]}

**Comment by jefferai** [comment]
Please file a bug against https://github.com/hashicorp/vault-plugin-auth-kubernetes

Thanks!

**Comment by sethvargo** [comment]
`\u003c` is `<`, hinting that the thing you're providing as a payload is not JSON but rather HTML. Alternatively, the response coming back from `/v1/auth/kubernetes/login` is HTML not JSON, and Vault is failing to parse that response. Please make sure you're running the latest version of Kubernetes and the latest version of Vault. You can find a working example of this auth method at https://github.com/sethvargo/vault-kubernetes-workshop.

**Comment by redi-vinogradov** [comment]
That was my mistake by using vault address as 'kubernetes_host' in kubernetes auth configuration. Apologies for the false report.
