### ISSUE TITLE
vault status prints local info rather than server

### ISSUE THREAD

**Issue by Quiark** [hashicorp/vault#5255]
**Describe the bug**
`vault status` shows version of local tool rather than server

**To Reproduce**
1. Run vault 0.11.0 on https://vault.example.com
2. `export VAULT_ADDR=https://vault.example.com` on home machine
3. Run `vault status` on home machine where the vault binary is 0.10.4

**Actual wrong behaviour**
The output says `Version         0.10.4`

**Expected behavior**
The output says `Version: 0.11.0`

**Environment:**
* Vault Server Version `0.11.0`
* Vault CLI Version `Vault v0.10.4 ('e21712a687889de1125e0a12a980420b1a4f72d3')`
* Server Operating System/Architecture: Amazon Linux 2

**Comment by jefferai** [comment]
I cannot replicate this. Ir prints 0.11.0 for me, using 0.11.0 server and 0.10.4 binary. Are you sure the server you're talking to is 0.11.0? If you upgraded, did you restart the binary after replacing it? If an HA cluster, did you upgrade all of the binaries?

**Comment by Quiark** [comment]
Yeah after an hour of debugging I found it was a local DNS cache redirecting me to development deployment :x
