### ISSUE TITLE
bug: transit key backup/restore loses "exportable" property

### ISSUE THREAD

**Issue by stampycode** [hashicorp/vault#5257]
Exporting, Deleting and Restoring a Transit key in quick succession occasionally results in the key no longer having the "exportable" property set to `true`.

I've seen this happen more than once recently, but haven't been able to reproduce it since.

Version: 0.10.1+prem

**Comment by jefferai** [comment]
Transit locking was completely rewritten in 0.10.3, please re-open if you can reproduce after then.
