### ISSUE TITLE
Misleading vault error on failed policy write

### ISSUE THREAD

**Issue by stefan-improbable** [hashicorp/vault#5259]
**Describe the bug**
When the policy write is unsuccessful, vault logs "invalid request" and throws away the real error. Also "invalid request" message is incorrect because the problem is in storage. Example log entry:
```
{"time":"2018-09-04T15:42:39.323574244Z","type":"response","auth":{"client_token":"hmac-sha256:ccd4169d7ebb5f5ee06ff8f8f1b4a8203c2ae8cab39a79a98fb202b3c8251cb1","accessor":"hmac-sha256:17acb58b99645b785c62619f1795049a67c3f21de95c25d3945df60b416022c4","display_name":"root","policies":["root"],"token_policies":["root"],"metadata":null,"entity_id":""},"request":{"id":"0de205a3-3854-b9d6-0703-4456a109e5a2","operation":"update","client_token":"hmac-sha256:ccd4169d7ebb5f5ee06ff8f8f1b4a8203c2ae8cab39a79a98fb202b3c8251cb1","client_token_accessor":"hmac-sha256:17acb58b99645b785c62619f1795049a67c3f21de95c25d3945df60b416022c4","path":"sys/policy/testsecretpolicy","data":{"policy":"hmac-sha256:49c58b363cc9b1ecda6514ea11141660431b88a19eadd409f76104039f333675"},"policy_override":false,"remote_address":"...","wrap_ttl":0,"headers":{}},"response":{"data":{"error":"hmac-sha256:5b1c04ceb1e9ae2d2d108a8bff2c615a9991238ac9ac38cc9262b1a3555d6078"}},"error":"1 error occurred:\n\n* invalid request"}
```

**To Reproduce**
1. Run vault with GCS storage support
2. Write until GCS returns "Error 503: Backend Error", which happens quite often

**Expected behavior**
vault logs "Error 503: Backend Error" instead of "invalid request"

**Environment:**
* Vault Server Version: built from master
* Vault CLI Version: used curl
* Server Operating System/Architecture: Ubuntu 16.04

Vault server configuration file(s):

```hcl
    storage "gcs" {
      bucket = "..."
      credentials_file = "/var/run/secrets/gcloud/creds.json"
    }

    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_cert_file = "/tls/tls.crt"
      tls_key_file = "/tls/tls.key"
    }

    telemetry {
      statsd_address = "..."
    }

    ui = "true"
    max_lease_ttl = "..."
```

**Comment by jefferai** [comment]
@sethvargo preferred method of handling this? If the 503 is due to throttling, we're standardizing on 502. If it's not, is there any type of retry mechanism in gcs? Either way probably the error should be wrapped and returned to the user.

**Comment by sethvargo** [comment]
Hey @stefan-improbable 

Thanks for opening an issue. 

The library automatically retries any retryable error. A 503 is [considered retryable](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/8007d2620d6fbc9f7eeb0a0ee571fe802b866353/storage/go110.go#L26), so it should be retrying. 503 _can_ be returned due to throttling, but we usually return a 429. 

Here's the expanded audit log entry:

```json
{
  "time":"2018-09-04T15:42:39.323574244Z",
  "type":"response",
  "auth":{
    "client_token":"hmac-sha256:ccd4169d7ebb5f5ee06ff8f8f1b4a8203c2ae8cab39a79a98fb202b3c8251cb1",
    "accessor":"hmac-sha256:17acb58b99645b785c62619f1795049a67c3f21de95c25d3945df60b416022c4",
    "display_name":"root",
    "policies":[
      "root"
    ],
    "token_policies":[
      "root"
    ],
    "metadata":null,
    "entity_id":""
  },
  "request":{
    "id":"0de205a3-3854-b9d6-0703-4456a109e5a2",
    "operation":"update",
    "client_token":"hmac-sha256:ccd4169d7ebb5f5ee06ff8f8f1b4a8203c2ae8cab39a79a98fb202b3c8251cb1",
    "client_token_accessor":"hmac-sha256:17acb58b99645b785c62619f1795049a67c3f21de95c25d3945df60b416022c4",
    "path":"sys/policy/testsecretpolicy",
    "data":{
      "policy":"hmac-sha256:49c58b363cc9b1ecda6514ea11141660431b88a19eadd409f76104039f333675"
    },
    "policy_override":false,
    "remote_address":"...",
    "wrap_ttl":0,
    "headers":{

    }
  },
  "response":{
    "data":{
      "error":"hmac-sha256:5b1c04ceb1e9ae2d2d108a8bff2c615a9991238ac9ac38cc9262b1a3555d6078"
    }
  },
  "error":"1 error occurred:\n\n* invalid request"
}
```

I'm curious @stefan-improbable - do you see that same error from curl? I see two errors in the output - one is hmac-ed and the other is "invalid request". 

@jefferai all the APIs for GCS are errwrapped. I just ran through Put:

https://github.com/hashicorp/vault/blob/abf336eec844c364f54dbe1d5aed235c6a4230ff/physical/gcs/gcs.go#L169-L191

There's no place where an error _isn't_ wrapped, so I don't know where "invalid request" is coming from unless Vault is somehow doing that when a storage backend returns an error.

**Comment by sethvargo** [comment]
@jefferai to put it another way - I think this is just confusion because there are two "error" fields in audit logs

**Comment by stefan-improbable** [comment]
@sethvargo the client was giving me error `error closing connection: googleapi: Error 503: Backend Error, backendError`, it's just that audit log message was confusing. I think response in `handlePoliciesSet` was populated correctly, just the error that was logged to audit log was set to `ErrInvalidRequest`.
By the way are you retrying closing connection (which I suppose is flushing)?

**Comment by sethvargo** [comment]
@jefferai as I suspected, this isn't related to GCS specifically, but rather the two `error` fields in the audit log. 

@stefan-improbable the `response.data.error` field (`hmac-sha256:5b1c04...`) _is_ the value you saw from the client, but it's hashed for security reasons. If you turn off hashing temporarily on development, you'll see the raw text. 

> By the way are you retrying closing connection (which I suppose is flushing)?

You mean the call to `.Close()` on a write operation? [I'm not sure](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/8c9fc24c2b85cbc71e8f1dbb6b7ac70a20bfe1c2/storage/writer.go#L194-L210). We are using the official client library calls, so any issues you see should be reported over in the [client library](https://github.com/GoogleCloudPlatform/google-cloud-go)

**Comment by stefan-improbable** [comment]
@sethvargo when I write to `auth/jwt/config` unsuccessfully I can see `"error":"1 error occurred:\n\n* error closing connection: googleapi: Error 503: Backend Error, backendError"` in audit log. Does it mean that this is sensitive information and should have been hashed?

As for the `.Close()`, it's failing with transient error so it's probably not a client library issue. You said that you are retrying GCS operations so I wanted to clarify whether you are retrying `Close` as well.

**Comment by stefan-improbable** [comment]
@sethvargo the full log message is
```
{
  "time": "2018-09-04T15:52:04.222803075Z",
  "type": "response",
  "auth": {
    "client_token": "hmac-sha256:ccd4169d7ebb5f5ee06ff8f8f1b4a8203c2ae8cab39a79a98fb202b3c8251cb1",
    "accessor": "hmac-sha256:17acb58b99645b785c62619f1795049a67c3f21de95c25d3945df60b416022c4",
    "display_name": "root",
    "policies": [
      "root"
    ],
    "token_policies": [
      "root"
    ],
    "metadata": null,
    "entity_id": ""
  },
  "request": {
    "id": "2ea12d37-30dd-e587-43bb-4264092ecbee",
    "operation": "update",
    "client_token": "hmac-sha256:ccd4169d7ebb5f5ee06ff8f8f1b4a8203c2ae8cab39a79a98fb202b3c8251cb1",
    "client_token_accessor": "hmac-sha256:17acb58b99645b785c62619f1795049a67c3f21de95c25d3945df60b416022c4",
    "path": "auth/jwt/config",
    "data": {
      "oidc_discovery_url": "hmac-sha256:51e1b7459e325c738c707b3ee827c257af4de420ce082f8b6c394c3ec8b4ff51"
    },
    "policy_override": false,
    "remote_address": "...",
    "wrap_ttl": 0,
    "headers": {}
  },
  "response": {},
  "error": "1 error occurred:\n\n* error closing connection: googleapi: Error 503: Backend Error, backendError"
}
```

**Comment by sethvargo** [comment]
Hmm - yea that's very weird, especially since the `response` in that entry is empty. I'm going to wait for @jefferai to chime in, but my guess is that storage backend errors aren't propagated the same way secrets engine errors are in audit logs.

**Comment by raskchanky** [comment]
@stefan-improbable It's been awhile since we've heard from you. Is this still an issue? I'm going to close this issue for now but feel free to reopen if this is still a problem, or if there's more to do here.
