### ISSUE TITLE
MariaDB compatibility in HA mode is broken

### ISSUE THREAD

**Issue by pavel-usov** [hashicorp/vault#5266]
It is not possible to run Vault 0.11.0 in HA mode with MariaDB backend. Login into Vault fails with following error message.

core: failed to acquire lock: error="mysql: lock already held"

In sources I found the cause of this.
physical/mysql/mysql.go, line 623:

rows, err := i.in.Query("SELECT GET_LOCK(?, -1), IS_USED_LOCK(?)", i.key, i.key)

Vault tries to get an infinite lock here, but MariaDB doesn't support this feature. Only positive numbers are allowed as second parameter in GET_LOCK.

As a solution I would suggest to use a very big number as a timeout to be considered as "infinite"

**Comment by pavel-usov** [comment]
I've submitted a pull request which shoud fix the issue
#5343

**Comment by briankassouf** [comment]
Closed by #5343
