### ISSUE TITLE
Secret lease is really a TTL; rename accordingly.

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/vault#528]
Per our discussion at https://groups.google.com/forum/#!topic/vault-tool/XChqN9kwTHk, it has come to light that the behavior of what's known as a "lease" in Vault terminology for secrets is in fact what is known as a "TTL" (time to live) among most operators.

Unlike a true lease, where the value associated with it can be guaranteed valid throughout the lease period (compare with a DHCP server's ability to guarantee the IP address assignment for a given MAC address, or Vault's ability to guarantee the validity of a token issued by its token auth backend), Vault has no way to enforce a secret value's validity for the entirety of the lease period.

The expectation of the authors regarding secret leases has been clarified through discussions on the mailing list: lessees should refresh the value if the "lease interval" has passed since the previous request.  This is exactly how DNS informs intermediate caches how long to retain a result, and is well known as a TTL among operations practitioners.

Consequently, because I think comprehension would be improved greatly, I think that any reference to "leases" relating to secrets should be changed to the more common "TTL" - both in the code and documentation - while we're still in the 0.x phase of development, before it's too late to resolve the confusion.

**Comment by wwalker** [comment]
+1

**Comment by jefferai** [comment]
The discussion in the mailing list thread is restricted to the generic backend; here it seems like the ask is for all leases within Vault to be renamed. That's not going to happen; a lease is a collection of properties, including a duration and ID, and it's the terminology that Vault has chosen.

However, the generic backend is definitely confusing, because `lease` is a parameter that has a name conflict with the overarching lease of which it is a property. Having a lease with a nested `lease` value is indeed bad UX. So for 0.3 I'm going to add `ttl` as a synonym and switch the documentation to using it, and in the release notes the `lease` parameter will be deprecated. In 0.4 `lease` will be removed and `ttl` will be the proper way to specify a duration.

**Comment by mfischer-zd** [comment]
To clarify, I agree that things that are leases in fact should still be called leases, such as those associated with access tokens.  Vault can guarantee that an access token will be valid through its lease period, absent a manual revocation by an authorized user.

For those things that are not actual leases -- i.e., where the validity of their values cannot be guaranteed through the end of the lease period - I think `ttl` is a more accurate property name.  Secrets stored in the generic backend definitely qualify, so it's great that you agree about that -- but I would go a bit further to cover any value that Vault cannot guarantee the validity of through the expiration date.

**Comment by jefferai** [comment]
@mfischer-zd the generic backend is IIRC the only place where "lease" is being used in a user-facing sense to mean a duration, so changing it there should take care of all current cases.

**Comment by mfischer-zd** [comment]
Alright, we'll cross any future bridges as we see them.

**Comment by mfischer-zd** [comment]
Hmm, with this change, the `lease_duration` remains, but I'm puzzled as to why.  Does Vault actually do anything after the expiration of the "lease" that remains associated with it?

**Comment by jefferai** [comment]
Copying from the merge request: "No, it's a hint to clients of the maximum expected data validity period. If the lease is given to them as an hour, they should be checking for new data at least once an hour. Vault is simply passing this information along."

I'm closing this in favor of the MR.
