### ISSUE TITLE
vault read mysql/config/lease should work

### ISSUE THREAD

**Issue by wwalker** [hashicorp/vault#529]
We should be able to see what the current mysql lease settings are:

    wwalker@hatter:~$ vault read mysql/config/lease                                                                                                          
    Error reading mysql/config/lease: Error making API request.

    URL: GET http://127.0.0.1:8200/v1/mysql/config/lease
    Code: 500. Errors:

    * unsupported operation

**Comment by ctennis** [comment]
This is fixed with the above commits which have been merged.
