### ISSUE TITLE
Vault-UI requires update permission to read AWS creds

### ISSUE THREAD

**Issue by FraaJad** [hashicorp/vault#5291]
**Describe the bug**
In 0.11.0 generating AWS credentials from the UI ie https://host/ui/vault/secrets/aws/credentials/role reverted to requiring update permission in addition to the normal read permission.

**To Reproduce**
1. Create aws secret engine
2. Add a aws role
3. Create a policy with read permission to `aws/creds/role`
3. Log into UI with that policy active and try to generate aws credentials.
4. Receive error `Error 1 error occurred: * permission denied`

It will work if the update permission is added to `aws/creds/role`

**Expected behavior**
AWS Credentials are generated.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.11.0 
* Vault CLI Version (retrieve with `vault version`): 0.11.0 
* Server Operating System/Architecture: Centos 7 / AMD64

Vault server configuration file(s):

```hcl
listener "tcp" {
  address         = "0.0.0.0:8200"
  cluster_address = "0.0.0.0:8201"
  tls_cert_file   = "/opt/vault/tls/vault.crt.pem"
  tls_key_file    = "/opt/vault/tls/vault.key.pem"
}
storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault/"
  scheme  = "http"
  service = "vault"

  # HA settings
  cluster_addr  = "https://10.64.10.55:8201"
  api_addr      = "https://10.64.10.55:8201"
}
ui = true
```

**Comment by meirish** [comment]
Thanks for the report - working on fixing this now! As a work around the Web CLI should still work with `read aws/creds/role`.
