### ISSUE TITLE
/v1/sys/auth trailing slash

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/vault#5313]
**Describe the bug**

the endpoint /v1/sys/auth matters if you include a trailing slash. Since you are allowed to delve down into individual auth backend tune endpoints using this, the slash should be supported as it will otherwise confuse users. 

This differs to the rest of the vault API, in which there is no difference between no trailing slash an a trailing slash for "container" api endpoints. 

e.g.:

```
+ curl --insecure --location --silent -i -H 'X-Vault-Token: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' https://vault.example.com/v1/sys/auth
HTTP/1.1 200 OK
Cache-Control: no-store
Content-Type: application/json
Date: Tue, 11 Sep 2018 13:01:57 GMT
Content-Length: 1011
Connection: keep-alive

{"token/" ..... }

+ curl --insecure --location --silent -i -H 'X-Vault-Token: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' https://vault.example.com/v1/sys/auth/
HTTP/1.1 404 Not Found
Cache-Control: no-store
Content-Type: application/json
Date: Tue, 11 Sep 2018 13:02:03 GMT
Content-Length: 55
Connection: keep-alive

{"errors":["1 error occurred:\n\n* unsupported path"]}
```

**Expected behavior**
I expect them to return the same results, similar to other vault api endpoints

**Environment:**
All vault versions

**Comment by vishalnayak** [comment]
When a trailing slash is present, Vault expects the mount path after the slash. A path without the slash is supported, a path with slash and with the mount path is supported. A path with just the ending slash isn't, for the GET operation.
