### ISSUE TITLE
Documentation: Wrong response for create/update secrets with KV v2 secrets engine

### ISSUE THREAD

**Issue by vfauth** [hashicorp/vault#5331]
**Describe the bug**
In the [doc](https://www.vaultproject.io/api/secret/kv/kv-v2.html#create-update-secret), with a KV v2 secrets engine, we should get a 204 with some data returned, but I get a 200 with no data returned. The secret is successfully created/updated though.

**To Reproduce**
1. Mount a KV v2 secrets engine at `secret/data`
2. Do a POST request at `/secret/data/key` with payload `{"data": {"foo": "bar"}}`
3. Get a 204

**Expected behavior**
According to the doc, we should get a 200 and the following response:
```json
{
  "options": {
      "cas": 0
  },
  "data": {
      "foo": "bar"
    }
}
```

**Environment:**
* Vault Server Version: 0.11.0

**Comment by jefferai** [comment]
What command are you using to mount?

**Comment by vfauth** [comment]
Ok, I found the issue. I think you guessed it, due to an error with a variable name, it was a KV v1 secrets engine. Both API are quite similar, so the configuration worked fine.

Sorry for the inconvenience :)
