### ISSUE TITLE
etcd storage backends ignores address scheme

### ISSUE THREAD

**Issue by Saloshp** [hashicorp/vault#5341]
**Describe the bug**
The *etcd* storage backends tries to create *https* connection regardless of the address specified ,
to make things even more interesting, it appears that access is performed from other nodes as well, not using the loopback address that was specified, my guess is that it queries *etcd* for the client url and then uses it, is that correct ?

**To Reproduce**
```bash
vault operator init
```

**Expected behavior**
I expected *Vault* to perform a clear *http* connection, rather than *https*

Vault server configuration file(s):

```hcl
cluster_name = "munio.io"
plugin_directory = "/etc/vault.d"

storage "etcd" {
  address  = "http://127.0.0.1:2379"
}

listener "tcp" {
  address       = "172.16.0.1:8200"
  tls_disable   = 0
  tls_cert_file = "/etc/vault/vault.crt"
  tls_key_file  = "/etc/vault/vault.key"
  tls_client_ca_file = "/etc/vault/ca-chain.crt"
}
```
**Actual behaviour**
> ...
> Sep 15 18:14:23 localhost etcd[1292]: rejected connection from "172.16.0.2:36536" (error "tls: first record does not look like a TLS handshake", ServerName "")
> Sep 15 18:14:23 localhost etcd[1292]: rejected connection from "172.16.0.2:36548" (error "tls: first record does not look like a TLS handshake", ServerName "")
> Sep 15 18:14:23 localhost etcd[1292]: rejected connection from "172.16.0.2:36554" (error "tls: first record does not look like a TLS handshake", ServerName "")
> Sep 15 18:14:23 localhost etcd[1292]: rejected connection from "172.16.0.2:36560" (error "tls: first record does not look like a TLS handshake", ServerName "")
> ...

---
```bash
[root@localhost munio.io]# uname -a
Linux infra01 4.18.6-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 5 11:54:09 UTC 2018 x86_64 GNU/Linux
```
```bash  
[root@localhost munio.io]# sha256sum vault_0.10.3_linux_amd64.zip 
ffec1c201f819f47581f54c08653a8d17ec0a6699854ebd7f6625babb9e290ed vault_0.10.3_linux_amd64.zip
```

**Comment by jefferai** [comment]
Those logs are coming from your etcd server. Your etcd server is rejetcting the connection because _it_ is configured to require HTTPS, but the Vault client is using HTTP. In other words, Vault is behaving exactly as you want, it's the other end that isn't. :-)

**Comment by Saloshp** [comment]
:man_facepalming: 
Thx

**Comment by Saloshp** [comment]
For future reference:
Even if *etcd* is configured to use a *http* client listener using *listen-client-urls*, Vault would use the ones that are specified in *advertise-client-urls*
