### ISSUE TITLE
server -dev startup should not emit shell prompt

### ISSUE THREAD

**Issue by frankwaltz** [hashicorp/vault#5344]
Tiny, tiny bug. When starting the server in dev mode, it prints:

```
You may need to set the following environment variable:

    $ export VAULT_ADDR='http://127.0.0.1:8200'
```

It should not print the '$' shell prompt. Besides assuming a  ksh-styled prompt (eg zsh and csh default is %), it makes it hard to copy/paste. Instead of having to annoyingly swipe only the command portion, if the '$' prompt weren't there I could just triple-click the line.

**Comment by catsby** [comment]
Hello - https://github.com/hashicorp/vault/pull/5556 was opened to address this but was decided against. Please see [this comment](https://github.com/hashicorp/vault/pull/5556#issuecomment-431633047) for rationale. I'm going to close this for now.
