### ISSUE TITLE
Submenu item for each type of secrets engines in UI

### ISSUE THREAD

**Issue by Garath620** [hashicorp/vault#5347]
Hello,

**Is your feature request related to a problem? Please describe.**
In the UI, when there are a lot of *secrets engines*, the *ui/vault/secrets* page becomes too long and confusing

**Describe the solution you'd like**
It would be nice to have a submenu item for each type of *secrets engines*
For example, in consul UI there are different menus for *Key/Value* and *Services* and it's great.

**Describe alternatives you've considered**
A filter box for the list of *secrets engines* could help too.

**Comment by lucymhdavies** [comment]
As someone who manages a Vault instance with almost 150 secret engines mounted, this would be a very useful feature.

**Comment by meirish** [comment]
We'll probably end up adding filter inputs like we have on the rest of the list pages for this.

**Comment by Monkeychip** [comment]
@Garath620 Apologies for the late reply here. But we have added a filter by name and type on both the secret engines list and auth methods list pages. It was released in 1.14 See PR #20481  and #20747. Hopefully, this helps navigation in these views.
