### ISSUE TITLE
how to revoker old user when i create new user for vault database backend

### ISSUE THREAD

**Issue by viveksaiaws** [hashicorp/vault#5349]
i am using vault database backend for generating creds for cassandra at deployment time 
for every deployment it creates user using `creation_statement `
for testing we may deploy application for every change, i want to delete previous user and create new user(working now) 
can you help me how to revoke user when i create new user 
How to use `revoke_statement` for that 
i dont see any docs for that 

Thnaks

**Comment by kalafut** [comment]
Hi. I've replied to your question on the newsgroup, which is the preferred forum for this type of question.
