### ISSUE TITLE
Replace hardcoded VAULT_ADDR environment variable string

### ISSUE THREAD

**Issue by kenbrubaker** [hashicorp/vault#537]
I'm busily copying your cli code for my first go app. I found a hardcoded string you probably want to replace and figured I record it here.

You want to replace "VAULT_ADDR" in [client.go](https://github.com/hashicorp/vault/blob/6d05df15962b9da1228d3199c93f9baa11bdda30/api/client.go#L47) with command.[EnvVaultAddress](https://github.com/hashicorp/vault/blob/6d05df15962b9da1228d3199c93f9baa11bdda30/command/meta.go#L26) (using permalinks)

You may want to think about putting the envars somewhere other than meta.go, though I don't know what would be the correct idiomatic place.

**Comment by jefferai** [comment]
Hi @kenbrubaker,

This is on purpose. Package `api` has no actual dependency on any of the rest of the Vault packages. It is intended to be standalone, even though it currently lives in the same tree.

I agree moving it to a higher scoped var might be good if it's ever repeated elsewhere in the code -- right now it isn't except in the test.

Thanks for the report!
