### ISSUE TITLE
[UI] allow to DELETE / UPDATE secrets on ui without READ permissions.

### ISSUE THREAD

**Issue by riuvshin** [hashicorp/vault#5373]
With CLI you can `update` and `delete` secret if you don't have `read` permissions so UI looks inconsistent from that perspective. I understand that `update` would be tricky without `read` but `delete` can be performed without opening secret.

**Comment by meirish** [comment]
Hi @riuvshin ! We plan on adding context menus to the list views that will allow for this. For now you should be able to do this in the UI via the Web CLI.
