### ISSUE TITLE
Auth.ExplicitMaxTTL not serialized by gRPC between plugin and core

### ISSUE THREAD

**Issue by andrejvanderzee** [hashicorp/vault#5376]
Vault version 0.11.1

In `logical/plugin/pb/backend.proto`, there is no field `explicit_max_ttl` in  `message Auth`. This causes the `logical.Auth.ExplicitMaxTTL` value _never_ to be serialized between my plugin and the vault's core. Hence, we can never use explicit max TTL in our plugins.

I am not very familiar with gRPC, but adding the value to `message Auth`  in `logical/plugin/pb/backend.proto` and running `make -f Makefile -C ../../.. proto` does give me lots of changes in `logical/plugin/pb/backend.pb.go`, but ExplicitMaxTTL is somehow _not_ added to the Go struct. 

Some instruction on howto run `protoc` would be appreciated, so we can move on with our plugins.

**Comment by andrejvanderzee** [comment]
Figured it out eventually. 

Filed a PR: https://github.com/hashicorp/vault/pull/5379.

**Comment by jefferai** [comment]
This was never added because nobody had requested it. Thanks for the PR!
