### ISSUE TITLE
app-id has no lease configuration and can not renew tokens

### ISSUE THREAD

**Issue by nbrownus** [hashicorp/vault#539]
It would be nice if either these tokens could optionally be renewed or the lease duration able to be set. I could have a cron that just re-auths the machine prior to the lease expiry but I would want to shorten the lease duration for that app-id so I don't have thousands of unused tokens within a 30 day span. Alternatively, the ability to renew a lease would also solve this problem.

**Comment by jefferai** [comment]
We're planning to add renew capability in 0.5.1.
