### ISSUE TITLE
Kubernetes Auth Multiple Hosts instead of a single one (HA Control Plane)

### ISSUE THREAD

**Issue by mitchellmaler** [hashicorp/vault#5408]
**Is your feature request related to a problem? Please describe.**

Would it be possible to provide more than one kubernetes host to the kubernetes auth host value? We currently run kubernetes with 3 master nodes and would like the auth to try to use the api on one of those which would direct to the master anyways.

**Describe the solution you'd like**
Allow providing more than one host in the hosts variable and the engine try each one before failing if the connection is refused or has issues.

**Describe alternatives you've considered**

The alternative for me is to setup a load balancer just for vault in front of the api servers which we currently use rancher to manage our clusters, auth, and load balancing/proxying requests to the api servers. Currently, rancher does not support jwt passthrough so my option is to expose the api servers but lock it down to only rancher server and vault.

**Comment by catsby** [comment]
Hey @mitchellmaler ! Could you give me some more information here? I'm have some questions:

- I'm a bit unfamiliar with multiple master nodes in Kubernetes, do they each serve requests or are some simply reserved for failover? (Sounds like just failover from your description)
- Assuming that's the case, the idea behind having multiple is such that if a/the "master" goes down, we'll try the others. Reason being that a new "master" may be elected and we don't want users to have to re-configure the kubernetes auth configuration with the new primary to get it working?
- "try to use the api on one of those which would direct to the master anyways." > do you mean client side redirect here (302, et. al), or do these other masters do this forwarding/redirecting internally (unbeknownst to Vault)?
- "try each one before failing if the connection is refused or has issues" > are you imaging those attempts only being made if the prior attempt is a 302 or 5xx type error, or would you expect a retry if one server returned an unauthorized response?

Hopefully those are coherent questions 😄 if you could let me know, I'd greatly appreciate it!

**Comment by shubb30** [comment]
+1 for this.  This is essential if you plan to use Vault Kubernetes Auth with a production Kubernetes cluster.

**Comment by raoofm** [comment]
@mitchellmaler isn't this normally achieved via a service/LB in front of n nodes in the cluster?

**Comment by codayblue** [comment]
I currently am interested in this functionality as well. I can attempt implementing it my self if some one could give me a little direction on where I should start looking and working.

**Comment by m1kola** [comment]
While I understand the need for a HA control plane support, I believe that adding support for multiple hosts into Vault is not the way to solve the HA challenge.

HA control plane requires having a load balancer in front of API server. Without a load balancer you will have to implement a client-side load balancing on each API server consumer and you will have to keep the list of hosts updated for each consumer (Vault, Kubernetes compoents and basically anything that uses Kubernetes API).

I think the solution here is:

* Put a TCP load balancer in front of an API server;
* Provide Vault with an URL which is pointing to a load balancer.

[This doc](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ha-topology/) describes options for HA topology. It's a good starting point, but details will depend on your setup/needs.

@catsby with high degree of confidence I think that there is no action required from Vault's side and the issue can be resolved, but could you please do a sanity check (I'm new to Vault)?

**Comment by mitchellmaler** [comment]
I agree with this. When I logged the issue it was for Rancher clusters which automatically did the control plane balancing without the need to put one in front but you couldn’t point vault to that. Now they have support for pass through support and also I could have created my own LB in front as well. If you agree we can go ahead and close this.

**Comment by catsby** [comment]
I agree as well, thank you for the detailed write up @m1kola and thank you @mitchellmaler for following up! I'm going to close this for now. Cheers

**Comment by tarekabouzeid** [comment]
Hi,

I tried configuring kubernetes auth in vault where the URL, is the Rancher URL which acts as a load balancer for a 3 kube api servers, and I provided the cert for Rancher URL also, but that did not work, even though the Rancher server URL works fine with kubectl for example, it only works if i provide only 1 kube api server in format "https://IP:PORT" and cert, is it mandatory to provide the kube api server in format https://host:port or https://ip:port ? 

Thanks
