### ISSUE TITLE
Policy templates

### ISSUE THREAD

**Issue by kohend** [hashicorp/vault#5417]
**Is your feature request related to a problem? Please describe.**
We'd like to have a non-root token create policies in the system, but we'd like to liit it so it can't be used for privilege escalation or unauthorized access.

**Describe the solution you'd like**
Policy template support, to have policies with placeholders to be replaced with parameters, somewhat similar to the database role definitions or the token roles.

**Describe alternatives you've considered**
I thought of finer grained control within policies or better wildcard support, but both seem inadequate, less secure and more complex to implement.

**Explain any additional use-cases**
A service that uses it's own pki mount and has access to it without needing to define a policy for each service or instance, preventing the service in charge of generating secrets from accessing them on a day to day basis, while letting the service that uses the secrets to access them.

**Comment by issacg** [comment]
+1

I've been wanting this, too, too issue certs with the PKI that are tied to a given user's CN.  I also recently saw an ask on the mailing list (https://groups.google.com/forum/#!searchin/vault-tool/template$20pki%7Csort:date/vault-tool/88CRNUIEG8Y/aGkcz-onAgAJ) for the same.  For now, I have an administrative script that creates roles in the PKI every time I need to add an entity, which is a huge and needless PITA.  I'm happy to limit this to the ID and not name for my specific use-case if there's concern about names being too mutable in this context...

**Comment by jefferai** [comment]
I'm going to close this as we already have policy templating at this point so the original ask is satisfied. Plugins have access to identity information about the current request, so interested parties could help activate the ability to do templating within their desired plugin, or the team will get to those as we have time. If you're interested in doing this implementation, please be sure to talk to us first about design!
