### ISSUE TITLE
Add possibility to specify user:group when starting the server

### ISSUE THREAD

**Issue by dol** [hashicorp/vault#542]
Running a service under root privileges is not [recommended](https://www.debian.org/doc/manuals/securing-debian-howto/ch9.en.html).
Running vault under non-privileged user has some limitations. The problem arouses from the TLS support. The configuration option 'tls_key_file' specifies a SSL key.
On a Debian system SSL private keys in the /etc/ssl/private/ are only readable by root and the members of the ssl-cert group.

![Debian folder of ssl keys](http://i.imgur.com/vekIcBo.png)

This problem could be solved by adding a user/group options to the vault startup or config. Internally it would look like the folling:
  1. Start vault as root `vault -config=/etc/vault/vault.hcl`
 ```
  backend "file" {
    path = "/var/lib/vault"
  }

  listener "tcp" {
    address = "127.0.0.1:8200"
    tls_key_file = "/etc/ssl/private/ssl-cert-snakeoil.key"
    tls_cert_file = "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    user = "vault"
    group = "vault"
  }
```
  2. Check if system [user and group exists](https://golang.org/pkg/os/user/#Lookup) and store uid/gid
  3. Load key and cert under root privilege -> tls.LoadX509KeyPair
  4. Drop privilege to uid/gid with [Setuid](https://golang.org/pkg/syscall/#Setuid)/[Setgid](https://golang.org/pkg/syscall/#Setgid)
  5. Start listener

There are some things to take care of. If the port is lower than 1024 the root privilege has to be dropped after the port binding.

At the moment I disabled TLS support in vault running on localhost. For TLS termination I used stunnel4. This way it's possible to run vault as a non-privileged user.

I think it's important to encrypt the traffic to the vault server.
I see some additional improvements that can be made. (I might open a new issue for this improvements) E.g.:
  - Add option to define ciphers
  - Add option to define supported curves

**Comment by BRMatt** [comment]
I'm not sure if vault should require root privileges it to access private keys during boot. Couldn't you run it under a specific vault user which is part of the `ssl-cert` group?

**Comment by dol** [comment]
The same concern applies to Apache, nginx, mysql, Postgresql, stunnel, ...
They all start as root and then drop privileges.
Here is the [nginx example](http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/trusty/nginx/trusty-updates/view/head:/debian/nginx-common.nginx.init#L52)

**Comment by BRMatt** [comment]
For sure, but in that situation is a little different - they need root to bind to one of lower port numbers, which is something that is common to all environments. I'm just trying to say that there may be ways to get the certificate without having to start the vault service as the root user.

Also if at some point in the future vault supports reloading of config without a hard restart (#415), requiring root privileges to load config would complicate things as the service would need to reacquire root privileges, and I'm not sure that's possible?

**Comment by jefferai** [comment]
A simple workaround is to put the cert information somewhere else -- daemons all require full paths, that directory is simply a Debian default. Then it can be given appropriate file and directory permissions to be readable by the Vault user and no other user/service.

**Comment by jefferai** [comment]
I'm going to close this. Obviously nothing prevents someone from starting Vault as root, but I don't think it should be encouraged. The other daemons launch as root not to read certificates but to bind to privileged ports, which Vault doesn't do. There are very easy workarounds to accessing the certs, such as making the Vault user part of the `ssl-cert` group, or simply moving the Vault certs elsewhere on the filesystem.
