### ISSUE TITLE
revoking cassandra leases does not work

### ISSUE THREAD

**Issue by bkw** [hashicorp/vault#543]
I cannot seem to revoke any leases issued by the cassandra secret backend. Here is what I did (against an empty `vault -dev` and a single cassandra-2.2.0 instance with authentication enabled):

```shell
$ ./vault -version
Vault v0.2.0
$ ./vault mount cassandra
Successfully mounted 'cassandra' at 'cassandra'!
$ ./vault write cassandra/config/connection hosts=localhost username=cassandra password=cassandra
Success! Data written to: cassandra/config/connection
$ ./vault write cassandra/roles/readonly \
  creation_cql="CREATE USER '{{username}}' WITH PASSWORD '{{password}}' NOSUPERUSER; \
  GRANT SELECT ON KEYSPACE api_auth TO \"{{username}}\";"
Success! Data written to: cassandra/roles/readonly
$ ./vault read cassandra/creds/readonly
Key             Value
lease_id        cassandra/creds/readonly/e5156e49-07ed-7f9b-927a-79cae73b7c95
lease_duration  14400
lease_renewable true
password        6ec445d7-899a-b690-cd83-c67c04a91d52
username        vault-readonly-root-94e77aad-86a5-a438-23e6-c60e8ff0e988-1439905957
$ ./vault revoke cassandra/creds/readonly/e5156e49-07ed-7f9b-927a-79cae73b7c95
Revoke error: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/revoke/cassandra/creds/readonly/e5156e49-07ed-7f9b-927a-79cae73b7c95
Code: 400. Errors:

* invalid request
```

I can see the new user being created in cassandra. After the failed revoke it is still there.
Any suggestion of what I might be doing wrong or where to look for further clues?

**Comment by bkw** [comment]
I also tried -prefix, but the result is the same:
```shell
$ ./vault revoke -prefix cassandra/
Revoke error: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/revoke-prefix/cassandra
Code: 400. Errors:

* invalid request
```

**Comment by bkw** [comment]
I suspect https://github.com/hashicorp/vault/commit/1faaf20b922c4cfe5c91e6cc034c779ebd9b5e6a#diff-a072ba822f5da46aad322c33647de5a8R74 . Pasting the line into cqlsh gives me an error, while exchanging the single quotes around the username into doubles makes it work. (See also #541 )

Do we need to to revoke the privileges at all? The `drop user` later should take of everything, don't you think? /CC @jefferai

**Comment by jefferai** [comment]
@bkw revoking a lease doesn't use the full path; Vault figures it out automatically. Try `vault revoke e5156e49-07ed-7f9b-927a-79cae73b7c95`.

**Comment by bkw** [comment]
I did. The call succeeds, but the user is not deleted. I can revoke anything and the call will succeed but not do anything. When I use a full lease path or a prefix that actually matches a lease, the Error occurs.
In any case, no user is ever deleted.

**Comment by jefferai** [comment]
Sorry, brain-fart. You do actually need the full path when revoking.

In my original testing single quotes were required, but as you found, in cqlsh it needs double quotes. A difference in interfaces, I think.

Are you comfortable building Vault yourself? I'd be interested in knowing if you take out the DROP PRIVILEGES command whether the DROP USER call after that succeeds. The priv call was mainly to ensure cleanup but I agree that dropping the user ought to automatically revoke any privileges.

**Comment by bkw** [comment]
I created #545 and can confirm that removing the DROP PRIVILEGES part fixes the revocation process.

**Comment by bkw** [comment]
closing this in favour of #545.
