### ISSUE TITLE
UI: {"errors":[]}

### ISSUE THREAD

**Issue by housseinabdo** [hashicorp/vault#5467]
I run Vault in dev mode and can not access the UI.

I get {"errors":[]} when I type 127.0.0.1:8200/ui in my browser  

FYI, older .exe of vault works fine

**Comment by meirish** [comment]
You can go to 127.0.0.1:8200 which will redirect you, or to 127.0.0.1:8200/ui/ (note the trailing slash). Let us know if that doesn't work for you, and we can reopen!

**Comment by housseinabdo** [comment]
Thanks sir for your reply. It works fine after I added the / :). Am I have another question if you can answer. I have added some modifications to the source code to enable the 128-bit aes encryption. But the Vault UI is not available since it is not the official release. May you provide some help here? I am running the Vault server on windows. 

Thanks in advance

**Comment by mrexodia** [comment]
This solved the issue for me. Would it be possible to also redirect `/ui` to `/ui/` or is there something in the design that prevents this?
