### ISSUE TITLE
Limit number of credentials issued by Vault

### ISSUE THREAD

**Issue by krish7919** [hashicorp/vault#5475]
**Is your feature request related to a problem? Please describe.**
I have observed an issue with one of our services crashing and restarting. Since the service was valid, it authenticated to Vault, and requested credentials all over the weekend. In the end the postgres secret backend had about 84k credentials. A high number of credentials were also seen in AWS secrets backend.

**Describe the solution you'd like**
A way to configure Vault to issue a maximum number of credentials but no more so that a runaway script or service cannot DDoS postgres or AWS server.

**Describe alternatives you've considered**
Code this in as a function that gets executed in the postgres case. But this will only work for postgres, and not for AWS, etc.

I cannot find any issue or documentation that mentions that this has been already implemented.

**Comment by kohend** [comment]
I think a better option is to revoke credentials when the parent token expires (not the case currently from what I saw) and use periodic tokens, this way if a service crashes, it's credentials don't stay live for long.
What do you think?

**Comment by krish7919** [comment]
> I think a better option is to revoke credentials when the parent token expires (not the case currently from what I saw) and use periodic tokens, this way if a service crashes, it's credentials don't stay live for long.

I do not understand this fully.
I thought tokens have a separate ttl to the credentials managed by secrets engines.

And there is not hook/callback when token expire; unlike database secret engine where we have a `revocation_statement` that is called.

**Comment by kohend** [comment]
Sorry, I am not familiar with the internals of the token store and assumed it does revoke the credentials when the token expires, I think that adding a hook to the token storage to allow for revocation of credentials made by revoked tokens is a good idea.
I'd expect no dangling credentials when a token is revoked.

**Comment by krish7919** [comment]
I think that will be an incorrect workflow; we have TTLs for tokens and for credentials to deal with dangling credentials.

A revoked token would result in _only_ the token getting revoked.

I am just proposing a limit added to Vault to limit it to issue only X number of credentials. That should be a simple check to do. If this interests the community, I can work on a PR for this.

**Comment by kohend** [comment]
From the answer I received on my ticket (#5504), it turns out that revoked tokens already revoke credentials made by them.

**Comment by krish7919** [comment]
That is indeed weird, because that defeats the purpose of using a different TTL for tokens and secrets engine. Also wondering how the one time or limited use tokens work in this case.

**Comment by kohend** [comment]
I've read a lot of this code on the weekend, it seems that all leases related to a token are revoked when it is revoked, so a one-time token will not be useful for database credentials.
However, periodic tokens that are renewed in a timely fashion, keep their leases up to the TTL of the lease (or max TTL of the lease, if the lease is renewed as well).

**Comment by krish7919** [comment]
Is there a way to limit the credentials issued except expiring the tokens?

Basically I want to achieve this:

> A way to configure Vault to issue a maximum number of credentials but no more so that a runaway script or service cannot DDoS postgres or AWS server.

**Comment by cvuillemez** [comment]
+1.
I had some crazy apps, requesting ~10 tokens / sec, without setting TTL (default is 32 days on my hosts).
Consequently, Vault stored 3 millions leases... and invoked OOM killer. Consul backend consume lots of space on disk too.
Adding a limit on number of credentials would be very helpful.

**Comment by vishalnayak** [comment]
https://www.vaultproject.io/docs/concepts/client-count is a good place to start.

**Comment by kalafut** [comment]
https://www.vaultproject.io/docs/concepts/resource-quotas may also help
