### ISSUE TITLE
[Feature] Add the possibility to map claims to metadata in JWT auth backend

### ISSUE THREAD

**Issue by uepoch** [hashicorp/vault#5477]
**Is your feature request related to a problem? Please describe.**
We are heavy users of JWT authentication in our company, and this would allow to attach more contextual infos to aliases

**Describe the solution you'd like**
Having the possibility to add a map[string]string in JWT's role configuration that takes a claim's key as key and the target metadata key as value.
If it matches, it gets mapped.

**Describe alternatives you've considered**
Mapping by default all non-standard claims to metadata, but maybe people don't want to store useless data / have really big tokens

**Comment by jefferai** [comment]
Closing in favor of the PR on the plugin linked above
