### ISSUE TITLE
Extending lease period

### ISSUE THREAD

**Issue by narayan8291** [hashicorp/vault#548]
I setup vault and created few secrets. I would like to have the lease period extended more than 30 days. When I try setting it to more that 2592000 seconds which is 30 days, it goes back to 30 days again. 

Is there any way I could achieve this ? (say 100 days)

**Comment by sethvargo** [comment]
Hi @narayan8291 

Thank you for opening an issue. At this time, the only way to create a token with more than a 30 day lease is to create a root token (which has no expiration). 

Could you explain your use case a bit more?

**Comment by narayan8291** [comment]
My use case is, 

I am the Vault admin. I have a root token and I am creating a token associated with a policy so that a user within my organization can use curl to get the secret. This token that I am creating for the user has to be valid for 6 months (max). I am not able to do this since the max limit is 30 days.

**Comment by sethvargo** [comment]
Hi @narayan8291 

Leases are actually more like TTLs, so even if the lease expires in 30 days, if it is renewed for that time, it will automatically extend the lease. The secret doesn't automatically disappear unless no renewal takes place. Does that make sense?

**Comment by narayan8291** [comment]
Hi Seth,

It makes sense. But in my case I am making use of Vault to remove hard-coded passwords in the application code written by developers. Hence, the curl requests would be made from the code and if the tokens created have a short lease period of 30 days then the developers or the Vault admin has to track the token renewal. 

I have a use case where I would like to revoke the token only when it has been misused.

**Comment by sethvargo** [comment]
Hi @narayan8291 

The application should renew the vault token at lease duration / 2. It should also renew the secrets at least duration / 2.

**Comment by narayan8291** [comment]
I don't understand the logic. Are you saying, the application has to have the code which renews the token and secret periodically. In this case, every 30days.

**Comment by narayan8291** [comment]
Is there any way way to implement this ?

**Comment by jefferai** [comment]
@narayan8291 See #469 which allows a configurable global max lease time rather than a hardcoded default. I believe this addresses your use case and will be in the 0.3 release. Eventually this will be further tunable per-backend.

**Comment by narayan8291** [comment]
Is there a release date for version 0.3

**Comment by jefferai** [comment]
Yes, leases are treated the same for tokens and anything else.

There is currently no set release date for 0.3, and there are a number of things we want to get in. My guess would be the second half of September, but I can't make any specific promises.

**Comment by narayan8291** [comment]
@jefferai 
Thanks. I appreciate it. So in the current version, the maximum lease duration possible is only 30 days and the only way I can achieve a lease period more than 30 days in version 0.2 is to download the code, modify it and build it again. Right?

**Comment by jefferai** [comment]
That's correct.
