### ISSUE TITLE
support UDS (unix domain sockets) as listeners

### ISSUE THREAD

**Issue by dch** [hashicorp/vault#5491]
**Feature Request:**

Currently vault's only listener is via TCP. Operationally, it would sometimes be far simpler to expose a unix domain socket, with standard filesystem permissions, and therefore prevent most programs from directly accessing vault.

I have a number of containers where there is no network access at all, and requiring vault to listen on a given IP subnet exposes that app, and vault, to all network-enabled containers on this system. While it can be controlled and restricted with firewall rules and vault ACLs, then *any* process can connect to vault directly, and this is not desirable in my situation - many processes are simply far too untrusted to be allowed to probe vault directly, and yet I do require some forms of access to vault.

Currently I am working around this using combinations of spiped and the insecure listener and haproxy but while haproxy is software I trust but would prefer not to see all vault data going through reverse proxies, and use filesystem permissions instead.

**Vault Config File:**

```hcl
# not currently supported
listener "unix" {
  path = "/some/socket"
}

# undesirable work-around
listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = 1
}

# typical external interface
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_min_version = "tls12"
  tls_key_file = "/usr/local/etc/vault/vault.key"
  tls_cert_file = "/usr/local/etc/vault/vault.crt"
}
```

the golang listener appears to support this already https://golang.org/pkg/net/#Listen

- https://anna.elde.codes/blog/golang-unix-socket-setup/#go-using-unix-sockets
- https://github.com/orisano/uds

**Comment by asteven** [comment]
I would also love this feature. Consul is able to do this since ages. 
Is there any specific reason why vault not?

**Comment by asteven** [comment]
Searching the code base it seems this is on the way with #6397.

**Comment by raskchanky** [comment]
https://github.com/hashicorp/vault/pull/6397 has been merged, and a quick scan of the code in that PR indicates that unix domain sockets should now be allowed as listeners. I'm going to close this issue for now, as I think it's resolved, but feel free to reopen if I'm wrong.

**Comment by ncabatoff** [comment]
@raskchanky #6397 refers to unix domain sockets for Vault Agent, this one is about adding support for them to Vault server.

**Comment by shaj13** [comment]
@raskchanky I was curious what's the status of it, I'd also love this feature, and will be happy to raise PR.

**Comment by raskchanky** [comment]
@shaj13 This issue is not currently being worked on, but if you'd like to work on it, please feel free.
