### ISSUE TITLE
Documentation issue with policies guide

### ISSUE THREAD

**Issue by aaronmell** [hashicorp/vault#5497]
https://github.com/hashicorp/vault/blob/master/website/source/guides/identity/policies.html.md

The documentation states

# List, create, update, and delete auth methods
path "sys/auth/*"
{
  capabilities = ["create", "read", "update", "delete", "sudo"]
}

list is missing from that list, it shouldn't be correct?
Also I had to modify the path to sys/auth to get it to work. Is that correct? Happy to submit a PR to fix if my changes are the right ones.

**Comment by yhyakuna** [comment]
Hi @aaronmell   You're totally correct.  It should've been:

```
...
# To create & manage auth methods
path "sys/auth/*"
{
  capabilities = ["create", "read", "update", "delete", "sudo"]
}

# List the enabled auth methods
path "sys/auth"
{
  capabilities = ["read"]
}
...
```

I may have more of those in other guides as well, so I'll go through them and make necessary updates. 

Thank you for reporting this!

**Comment by yhyakuna** [comment]
It's fixed now.  Please see the updated [guide](https://www.vaultproject.io/guides/identity/policies.html).

Thank you for finding this.
