### ISSUE TITLE
Vault reports decryption failed: cipher: message authentication failed (Error 500)

### ISSUE THREAD

**Issue by migounette** [hashicorp/vault#5498]
Vaul is put in unstable state during a Reset procedure

**Steps to reproduce the behavior:**
- Vault uses Consul as backend
- Reset Vault via Consul operations
http://localhost:8500/v1/kv/vault?recurse
- Initialize Vault ['/v1/sys/init']
- Unseal Vault ['/v1/sys/unseal']
This operation leads to: 
decryption failed: cipher: message authentication failed

Problem: Vault is dead, next operations leads to Error 500
Solution: Restart Vault

Solution to the sequence: Put a sleep time between Consul Reset and Initialize of Vault

**Vault server configuration file(s):**

```json
{
    "ui": false,
    "listener": {
        "tcp": {
            "address": "<myip>:8200",
            "tls_cert_file": "<mypath>/vault-cert.pem",
            "tls_key_file": "<mypath>/vault-key.pem",
            "tls_require_and_verify_client_cert": false
        }
    },
    "storage": {
        "consul": {}
    },
    "disable_mlock": true,
    "telemetry": {
        "dogstatsd_addr": "127.0.0.1:8125"
    }
}
```

**Expected behavior**
Vault to be initialized and can be unsealed.

**Additional context**
Extreme case but needed when you want to flush your entries and useful with Ansible and idempotency

**Comment by jefferai** [comment]
Vault is not stateless and does not support having its data store wiped from underneath it. You need to adjust your Ansible scripts to stop and start the process.
