### ISSUE TITLE
Inappropriate HTTP Status Code 403 Response on Invalid Parameter Values

### ISSUE THREAD

**Issue by trmz** [hashicorp/vault#5499]
**Environment:**
* Vault Version: Vault v0.11.2 ('2b1a4304374712953ff606c6a925bbe90a4e85dd')
* Operating System/Architecture: Debian GNU/Linux 8.11 (jessie)

**Vault Config File:**
```hcl
storage "file" {
  path    = "/vault/storage"
}

listener "tcp" {
  address     = "127.0.2.1:8200"
}
```

**Startup Log Output:**
```text
N/A
```

**Expected Behavior:**
Vault should return 422, 400, etc. 

**Actual Behavior:**
Vault returned 403 Permission Denied.

**Steps to Reproduce:**
Create any policy with a whitelist of allowed values in "allowed_parameters", then issue a request with any parameter that violates the policy. 
For example : 
``` hcl
path "secret/*"
{ 
  capabilities = ["create"]
  allowed_parameters = {
    "foo" = ["1", "2"]
  }
}
```

Then : 
```
$ vault write secret/10 foo=test
Error writing data to secret/10: Error making API request.

URL: PUT https://vault.vianet.ca:8200/v1/secret/10
Code: 403. Errors:

* 1 error occurred:

* permission denied

$ vault write secret/10 foo=2
Success! Data written to: secret/10
```
Would expect a more appropriate status code, like 422 (seems more correct) or 400. See References. 

**Important Factoids:**
403 Permission Denied is not an intuitive HTTP response code, for when passed values violate a policy's allowed_parameters whitelist of acceptable values. 

**References:**
https://stackoverflow.com/a/42171674/2304437

**Comment by jefferai** [comment]
Since this is part of the authorization flow, 403 is correct. If it passes the authorization check and the backed thinks it's invalid for some reason, it would return a 400.

**Comment by trmz** [comment]
@jefferai Hello ! I don't know the code at all, but that seems strange to me ? Why would data validation fall within the scope of authorization ? Those're conceptually separate concerns. 
I would expect Vault to authenticate, authorize (compare a token against allowed path+capabilities), then check that values to passed args are valid ...

**Comment by jefferai** [comment]
That's the point, they're separate concerns. The ACL check is performing an authorization check against the value with no understanding of context. Afterwards it passes the data to the plugin which actually examines whether the values are appropriate or not.

Put simply, any failure of the ACL check is an authorization failure.
