### ISSUE TITLE
Token storage hooks

### ISSUE THREAD

**Issue by kohend** [hashicorp/vault#5504]
**Is your feature request related to a problem? Please describe.**
Somewhat related to #5475.

**Describe the solution you'd like**
To have an option for plugin credentials to be revoked with the parent token, by the plugin registering a hook on the creating token.

**Describe alternatives you've considered**
Currently we match the ttl of tokens with the credentials created by them and our flow gets credentials when the token is created.

**Explain any additional use-cases**
For example, dynamic Cassandra credentials for a process using a periodic token, once the token expires the credentials should too, and replacing the credentials every periodic refresh is a pain.

**Additional context**
I may be able to write this feature (not sure regarding priorities though), I wanted to see if that's something that makes sense.

**Comment by jefferai** [comment]
Plugin credentials are already revoked when the token that created them expires. Their lifetimes are otherwise totally independent; you don't need to replace your Cassandra credentials every time you refresh your token.
