### ISSUE TITLE
Mount command does not forward from standby nodes

### ISSUE THREAD

**Issue by phinze** [hashicorp/vault#551]
### Steps to reproduce:

 * Bootstrap two vault servers
 * Run a mount command, e.g. `vault mount transit` on the standby.

```
$ vault mount transit
Mount error: Error making API request.

URL: POST https://127.0.0.1:8200/v1/sys/mounts/transit
Code: 500. Errors:

* Vault is in standby mode
```

### Expected behavior:

Request is forwarded to the leader and completes successfully.

**Comment by jefferai** [comment]
Should be fixed in 2920cddc.
