### ISSUE TITLE
Users (entities) won't show up until they login once

### ISSUE THREAD

**Issue by alexandernst** [hashicorp/vault#5511]
**Describe the bug**

If I create a user (`vault write auth/userpass/users/...`), the user doesn't show up in the list of Entities until he/she logins at least once.

**To Reproduce**
1. Run `vault vault write auth/userpass/users/foo password=bar`
2. Go to Access -> Entities (in the Web UI)
3. See error

**Expected behavior**
I'd expect to be able to see all entities, no matter if they have or haven't logged in at least once.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.11.3
* Vault CLI Version (retrieve with `vault version`): 0.11.3 ('fb601237bfbe4bc16ff679f642248ee8a86e627b')
* Server Operating System/Architecture: Debian GNU/Linux 9 (stretch)

**Comment by amahfouz** [comment]
Is this by design or should I look into it? 
Anybody?

**Comment by vishalnayak** [comment]
@alexandernst @amahfouz This is by design. Entities have to be explicitly created in identity store. When a user logs in, if the entity is not already created for the logged in user, Vault creates one.
