### ISSUE TITLE
policy logic flaw: need wildcard support

### ISSUE THREAD

**Issue by stampycode** [hashicorp/vault#5514]
**Problem Statement**

I have > 100 AppRoles.

I need a policy that allows one specific AppRole to list all secret-id-accessors for all other AppRoles, without granting the ability to generate a SecretID for other apps. The purpose of this is to monitor the lifetime/TTLs/Num_Uses of issued SecretID tokens, so Admins can be forewarned when AppRole SecretIDs are being used too frequently, or when there are stale SecretIDs that should be revoked.

The app needs to have a generic policy that doesn't need to be updated whenever I add a new app to Vault.

At the current time I can't see a way to make this work safely.

This is the policy my AppRole needs:

    path "auth/approle/role/my-*/secret-id/" { capabilities = ["list"] }
    path "auth/approle/role/my-*/secret-id-accessor/lookup" { capabilities = ["update"] }

Currently this policy is the only way to grant my app all the permissions it needs:

    path "auth/approle/role/my-*" { capabilities = ["list", "update"] }

However, this gives my AppRole more permissions that it should have, including the ability to generate SecretID values for any other application, thereby enabling privilege escalation.
The path below requires no parameters, so I don't think it can be blocked by a `denied_parameters` or `allowed_parameters` lists.

    POST /v1/auth/approle/role/my-other-app/secret-id

**How this could be solved**

Mid-path wildcard support for policies would solve this cleanly.
If a substring `*` would be interpreted as regex `[a-zA-Z0-9_-]+` this would be safe.

    path "auth/approle/role/my-*/secret-id/" { capabilities = ["list"] }
    path "auth/approle/role/my-*/secret-id-accessor/lookup" { capabilities = ["update"] }

*Alternatively*, another path structure could implemented for `v2`, where AppRole names appear at the end of the path. Eg.

    path "auth/approle/role/secret-id/my-*" { capabilities = ["list"] }
    path "auth/approle/role/secret-id-accessor/lookup/my-*" { capabilities = ["update"] }

*Alternatively* listing every single app twice in the policy. But this breaks one of the rules mentioned above, that the policy for my app would have to be updated when a new AppRole is created.

    path "auth/approle/role/my-app-1/secret-id/" { capabilities = ["list"] }
    path "auth/approle/role/my-app-1/secret-id-accessor/lookup" { capabilities = ["update"] }
    path "auth/approle/role/my-app-2/secret-id/" { capabilities = ["list"] }
    path "auth/approle/role/my-app-2/secret-id-accessor/lookup" { capabilities = ["update"] }
    path "auth/approle/role/my-app-3/secret-id/" { capabilities = ["list"] }
    path "auth/approle/role/my-app-3/secret-id-accessor/lookup" { capabilities = ["update"] }
    # ... ad absurdum

**Alternatives I've considered**

I've tried creating policies that use `allowed_parameters` and `denied_parameters` options to allow only the actions that the "vault status app" needs, but there's no way I can see to prevent the app using `POST /v1/auth/approle/role/my-other-app/secret-id`, because it has no required parameters.

Also it feels fudgy.

Currently using Vault `v0.10.1+prem`.

**Comment by jefferai** [comment]
Sorry, but you need to go through Enterprise support channels. (Also, you can do this with Sentinel.)
