### ISSUE TITLE
Improve documentation regarding required Vault DynamoDB table features for backend storage

### ISSUE THREAD

**Issue by kbuchsicf** [hashicorp/vault#5515]
**Is your feature request related to a problem? Please describe.**
The storage backend for DynamoDB can be used either with or without a separately created table pre-existing. If wants to create a table separately, like with Terraform, you need to know what are the required hash/sort keys are. If one created the table without paying attention to these features, then it will just fail with a somewhat hard-to-follow message about a schema mismatch. 

**Describe the solution you'd like**
Documentation should indicate that you need a DynamoDB table with:
1) Primary partition key: "Path", a string
2) Primary sort key: "Key", a string

**Describe alternatives you've considered**
You have to let the storage backend create the table and observe what it has created.

**Additional context**
Terraform configuration:
```terraform
resource "aws_dynamodb_table" "dynamodb-table" {
  name           = "${var.dynamoTable}"
  read_capacity  = 1
  write_capacity = 1
	hash_key       = "Path"
	range_key      = "Key"
	attribute [
		{
			name = "Path"
			type = "S"
		},
		{
			name = "Key"
			type = "S"
		}
	]
  tags {
    Name        = "vault-dynamodb-table"
    Environment = "prod"
  }
}
```

**Comment by jefferai** [comment]
Hi there,

We don't use or support the DynamoDB storage method. It would be fantastic if you could send a PR with the updates you recommend!
