### ISSUE TITLE
REST API should either deal with application/x-www-form-urlencoded or give a better error

### ISSUE THREAD

**Issue by mdagit** [hashicorp/vault#553]
It is certainly conceivable there are nested data structures for requests, but most of the time not --
it seems it should be pretty easy to accept plain old application/x-www-form-urlencoded
REST requests for a single level of scalar values. That would be my preference. But failing that, it should at least give a better error.

As it is, if someone uses curl -d value=var the server doesn't even notice the request content type,
tries to parse the body as json and spits out the obscure response:

{"errors":["invalid character 'i' looking for beginning of value"]}

**Comment by mdagit** [comment]
Well, IMHO you should also look at the request content-type and if it is application/x-www-form-urlencoded you should also give a particular error for that, if in fact all you are going to support is json.

**Comment by jefferai** [comment]
Taking your argument to its logical conclusion, if the `Content-Type` is anything other than `application/json` we could ignore it.

However, right now we actually are purposefully doing the opposite: as all of our APIs are documented and consistently using JSON, we ignore the `Content-Type` header to allow for problematic or dumb clients to still use the API (as the `Content-Type` header is informational-only, this doesn't open up any additional attack surface). Notably, this makes it easy for people to use `curl` to interact with Vault without having to remember to use extra arguments.

**Comment by mdagit** [comment]
hmmm, if you wanted to make curl easy to use (not to mention dumb js libraries),
you would just support application/x-www-form-urlencoded  :)

i understand there are theoretical issues with nested data structures but for the vast majority of the api, that doesn't happen.

in general it seems like a bad precedent to pay no attention to content-type -- not for security reasons so much as for
leaving open the possibility of other request entity types.

anyway, i'm happy with just an improved error message, and i realize there other much higher priority issues in the queue....

-mda
