### ISSUE TITLE
Spring database back-end integration creates, but doesn't renew, credentials.

### ISSUE THREAD

**Issue by stuio** [hashicorp/vault#5531]
**Describe the bug**

**To Reproduce**
1. Follow example in [docs](https://www.vaultproject.io/docs/secrets/databases/mysql-maria.html) to set up a DB config and role. We used the mysql-legacy plugin for shorter usernames.
2. Create Spring Boot application with `spring.cloud.vault.database.config` integration (version 2.0.1.RELEASE)
3. Bootstrap the application to hit the `database/creds/our-role` endpoint
4. Interact with DB via application to show credential creation at startup is working
5. When TTL approaches tail logs, watch 403 forbidden response to lease renewal request

**Expected behavior**

For the lease to be renewed

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.4
* Vault CLI Version (retrieve with `vault version`): 0.10.3
* Server Operating System/Architecture: RHEL 7.4 x64

Vault server configuration file(s):

```hcl
storage "file" {
  path = "/mnt/vault/data"
}

listener "tcp" {
 address = "xxx.xxx.xxx.xxx:8200"
 tls_cert_file = "cert.crt"
 tls_key_file = "key.key"
}

```
**Extra Information:**

We _can_ renew the lease using the same VAULT TOKEN as for the application if we use the client:

`vault lease renew  database/creds/<our-role>/<lease-id>`

We can also renew the lease via curl, hitting the same endpoint as is failing through the application, if we use a _root_ token:

```bash
curl -H "X-Vault-Token:$VAULT_TOKEN" --request PUT https:/<our-vault-host>:8200/v1/sys/renew/database/creds/<our-role>/<lease-id>
```

Which suggests the problem is related to the unprivileged token's policy, which is:
```hcl
{
  "path": {
    "database/creds/<our-role>": {
      "capabilities": [
        "read",
        "list",
        "create",
        "delete",
        "update"
      ]
    }
  }
  "path": {
    "sys/*": {
      "capabilities": [
        "read",
        "list",
        "create",
        "delete",
        "update"
      ]
    }
  }
}
```

The `/sys/*` path is deliberately broad for testing.

**Comment by chrishoffman** [comment]
This seems to be a problem with the Spring Boot integration.  We do not maintain this integration so I would file an issue with them.
