### ISSUE TITLE
Support a literal dash character as a KV value using vault cli

### ISSUE THREAD

**Issue by aarro** [hashicorp/vault#5532]
**Feature Request:**
Support a literal, single dash as a KV value, similar to how #2996 was implemented for an \@.

**Expected Behavior:**
Running

`vault kv put secrets/test dash="\-"`

I would expect that it would insert a single dash as the value

**Actual Behavior:**
```
vault kv put safetest/test dash="\-"
Success! Data written to: safetest/test
vault kv get safetest/test
==== Data ====
Key     Value
---     -----
dash    \-
```

**Steps to Reproduce:**
See above

**Important Factoids:**
The backslash as an escape char works as expected for the \@ symbol.
```
vault kv put safetest/test dash="\@"
Success! Data written to: safetest/test
vault kv get safetest/test
==== Data ====
Key     Value
---     -----
dash    @
```

**References:**
#2996

**Comment by aphorise** [comment]
@aarro - hey I suspect that this is in place working as you're expecting & using the examples on `vault kv put --help` exemplified it (as I've show below) - obviously providing proper json escaped string via `@value.json` is probably best. I think this issue might **not be applicable any longer?**

```bash
vault secrets enable -version=2 kv ;
  # Success! Enabled the kv secrets engine at: kv/

echo '-' | vault kv put kv/test dash=-
  # Key              Value
  # ---              -----
  # created_time     2020-08-09T21:01:29.640546928Z
  # deletion_time    n/a
  # destroyed        false
  # version          1

vault kv get kv/test ;
  # ………
  # Key     Value
  # ---     -----
  # dash    -

# // also if you dont need the field value you can use '-' directly such as:
vault kv put kv/test -=

vault kv get kv/test ;
  # Key    Value
  # ---    -----
  # -      n/a

vault kv get -format=json kv/test | jq -r '.data.data | keys[]'
  # -
```

**Comment by raskchanky** [comment]
I'm able to repro the solution here using @aphorise 's steps, so I think this is ok? I'm going to close this issue for now but feel free to reopen if there's more to discuss here.
