### ISSUE TITLE
Vault storage grow too quickly

### ISSUE THREAD

**Issue by zjxpsetp** [hashicorp/vault#5541]
Strange, the storage of our consul backend  grow from 7.5G to 11G **in about 1 minute**, which make our vault cluster not very stable.

Following is out vault log output during that time with command `cat nohup.out | grep  2018\/10\/17 |  grep -v INFO | grep -v TransientFailure | grep -v forwarding`. Anyone here know the reason why the consul backend storage grow too quickly??

2018/10/17 17:56:55.820266 [WARN ] expiration: lease count exceeds warning lease threshold
2018/10/17 17:57:56.826575 [WARN ] expiration: lease count exceeds warning lease threshold
2018/10/17 17:58:57.831589 [WARN ] expiration: lease count exceeds warning lease threshold
2018/10/17 17:59:58.837443 [WARN ] expiration: lease count exceeds warning lease threshold
2018/10/17 18:00:59.842540 [WARN ] expiration: lease count exceeds warning lease threshold
2018/10/17 18:02:00.855545 [WARN ] expiration: lease count exceeds warning lease threshold
2018/10/17 18:03:01.861274 [WARN ] expiration: lease count exceeds warning lease threshold
2018/10/17 18:04:02.885312 [WARN ] expiration: lease count exceeds warning lease threshold
2018/10/17 18:05:03.890441 [WARN ] expiration: lease count exceeds warning lease threshold
2018/10/17 18:06:05.453306 [WARN ] expiration: lease count exceeds warning lease threshold
2018/10/17 18:06:09.352818 [WARN ] core: leadership lost, stopping active operation
2018/10/17 18:06:13.611010 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/53eb28fc0aad2c9ef23cb0e64e6eb4373d53a461
2018/10/17 18:06:13.611050 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/bf3cef93a805443071b11c0740d63a9a87a97606
2018/10/17 18:06:13.611067 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/e2eaed2e0629a867fc302cafbd74fcb127a15c57
2018/10/17 18:06:13.611081 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/01f27566ba86da6f90dc29b3fa287c9baeeb6747
2018/10/17 18:06:13.611095 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/f571c7b6967a95ed88d18bf32be008c142546963
2018/10/17 18:06:13.611110 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/95905bba1e0ee1dee56e6a93374df217aace6ed3
2018/10/17 18:06:13.611125 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/c10347da7078341fc4e1f1bc2642d553209405da
2018/10/17 18:06:13.611139 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/10e1353d41b93ca4b7854d52ebaec19fb106bcf8
2018/10/17 18:06:13.611154 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/40af8363f0abe97f8cbaec61aae3032affeeb42a
2018/10/17 18:06:13.611168 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/d989160ff8e1dfdc3a826016e5f9b0b442ad6423
2018/10/17 18:06:13.611182 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/8b23e8fe942d439e98fb5e20f9c701e254505949
2018/10/17 18:06:13.611197 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/74b656bee45547c7e8796e248587e229645d4b6f
2018/10/17 18:06:13.611211 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/96e6408816b476c597a6af8ca7f47d04b6ca6829
2018/10/17 18:06:13.611225 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/bbda93ed58897ebe51fabf32c9fcd48532bcbe91
2018/10/17 18:06:13.611239 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/09e8ee4c44c9ff3f233afcbe4de35de30e1c21b7
2018/10/17 18:06:13.611253 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/57cb6043c43d846ecb66b67103f15b97a62f11cb
2018/10/17 18:06:13.611279 [ERROR] expiration: shutting down, not attempting further revocation of lease: lease_id=auth/approle/login/026008d455b1b1b7f60f4d6d690c9192d29bd9ae

**Comment by chrishoffman** [comment]
It seems that you have misconfigured application that is logging in at an extraordinary rate.  I would check how many keys are found in `sys/expire/auth/approle/login` in consul to give you an idea of how many logins are happening.  Also, what version of vault are you running?

**Comment by zjxpsetp** [comment]
@chrishoffman  we use vault 0.9.6
we have about 14,000,000 keys in vault. But many of them seems can not be cleanup by vault. We try to use tidy API, which make our consul cluster totally down.

**Comment by jefferai** [comment]
How do you know those keys are dirty data? If you've been creating tokens with very long lifetimes they may still be valid. We have also fixed a number of bugs in this area (as well as improved tidy) so being on such an old version you could still be hitting them.

The fact that your storage jumped so much in one minute suggests that many of those tokens and accessors were created then and if so they likely are still within their valid lifetime.

The most brute force thing you can do is shut down vault and manually delete those keys (requiring all your applications to reauthenticate) but this will also mean that lease tracking will no longer be tied to the lifetime of those tokens.

**Comment by zjxpsetp** [comment]
@jefferai Do you the the which key in consul means token?

**Comment by zjxpsetp** [comment]
@jefferai And for the revoke action, vault will delete "token" from vault immediately？

**Comment by zjxpsetp** [comment]
@chrishoffman do we have a api to fetch all token id or accessor as root?

**Comment by zjxpsetp** [comment]
@chrishoffman  We have about 6M accessors and about 6M /sys/token/id/xxxxx, which mean we have generate about 6M tokens, right?

**Comment by raskchanky** [comment]
It's been a long time since this issue has had any activity and Vault has advanced many versions in that time period. If there was a bug in this area, it has likely been fixed. I'm going to close this issue for now, but feel free to reopen if there's more to discuss here.
