### ISSUE TITLE
Check cluster sync status

### ISSUE THREAD

**Issue by hryamzik** [hashicorp/vault#5565]
How can I check if node is in sync?

Here's what I have at `/v1/sys/replication/status`:
```json
{
    "request_id": "***",
    "lease_id": "",
    "renewable": false,
    "lease_duration": 0,
    "data": {
        "dr": {
            "cluster_id": "***",
            "known_secondaries": [],
            "last_wal": 100500,
            "merkle_root": "***",
            "mode": "primary",
            "primary_cluster_addr": ""
        },
        "performance": {
            "mode": "disabled"
        }
    },
    "wrap_info": null,
    "warnings": null,
    "auth": null
}
```

`data.dr.last_wal` looks like a good key to check but it doesn't seem to be documented.

**Comment by chrishoffman** [comment]
The best way would be to look at the merkle_root which is the hash of the merkle tree.  Also, questions like this should be directed to the mailing list which has a lot more eyes than the issue tracker.
