### ISSUE TITLE
Small font size on code samples in new website

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#5569]
The new website (vaultproject.io) has a font-size of 0.875em for code, making it significantly smaller than the remainder of the text. Please increase it to 0.9em or 0.95em so it's legible. Thanks!

/cc @jescalan 

<img width="583" alt="screen shot 2018-10-19 at 9 36 37 pm" src="https://user-images.githubusercontent.com/408570/47249860-12232780-d3e7-11e8-973c-26006029c7d2.png">

**Comment by jescalan** [comment]
Great catch, we pushed a fix for this one!
