### ISSUE TITLE
Background color and padding should not be shown inside notes/callouts

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#5570]
The additional padding around monospace code font inside a note/callout pushes the line-height down too much.

<img width="586" alt="screen shot 2018-10-19 at 9 50 41 pm" src="https://user-images.githubusercontent.com/408570/47249993-21a37000-d3e9-11e8-89aa-e2629e512d76.png">

/cc @jescalan

**Comment by sethvargo** [comment]
Similarly, `tt` and `code` font shouldn't have a background inside a table:

<img width="609" alt="screen shot 2018-10-19 at 10 12 50 pm" src="https://user-images.githubusercontent.com/408570/47250235-42b99000-d3ec-11e8-8d81-4e080b86888f.png">

**Comment by jescalan** [comment]
Hey, thank you for pointing this out! I brought this issue up with the design team, and after a discussion they decided that it was an intentional design choice and they would like to leave it like this.
