### ISSUE TITLE
Website is missing clickable header anchor links

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#5572]
The new website is missing the ability to get an anchor link for a particular header. This is very important on the API docs pages which tend to be very long. People like to link directly to an item. Previously this was accomplished by hovering over the element and clicking on the `>>` next to it to add the anchor hash to the URL.

Existing anchors still work (i.e. links aren't broken) because the headers retained their IDs, but it's now very difficult to link to a specific section in the documentation without inspecting the HTML or guessing the header name.

Please restore the old behavior.

<img width="388" alt="screen_shot_2018-10-19_at_10_00_12_pm" src="https://user-images.githubusercontent.com/408570/47250104-6da2e480-d3ea-11e8-9acd-d8220541baf7.png">

/cc @dadgar because he originally requested this feature in the Nomad docs
/cc @jescalan

**Comment by jescalan** [comment]
Thanks for pointing this out, we shipped out a fix for this 😁
