### ISSUE TITLE
Website randomly indents first character of multi-line code samples

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#5573]
The new website indents the first line of all multi-line codeblocks/snippets by one character. This seems to affect all pages and it appears to be CSS (there isn't actually a character pushing it over in the HTML)

<img width="356" alt="screen_shot_2018-10-19_at_10_04_41_pm" src="https://user-images.githubusercontent.com/408570/47250175-44368880-d3eb-11e8-8ac9-75f4c6c5f38d.png">
<img width="112" alt="screen_shot_2018-10-19_at_10_06_27_pm" src="https://user-images.githubusercontent.com/408570/47250178-5ca6a300-d3eb-11e8-9165-c8ee24362be2.png">

/cc @jescalan

**Comment by jescalan** [comment]
This one is now resolved, thanks again for the catch!
