### ISSUE TITLE
Website can't be started locally

### ISSUE THREAD

**Issue by marcosnils** [hashicorp/vault#5589]
**Describe the bug**
Error starting vault site.

**To Reproduce**
1. Clone the repo
2. cd website && make website

**Expected behavior**
Website to start?

**Environment:**
Linux <host> 4.15.0-36-generic #39-debian SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
It'd be also nice if docker the used docker image (netlify:build) doesn't take too much space. 3.8 gb to start a website seems too much.

Log output:

```
Digest: sha256:5ffe665bf281e6ef428d8fa96d3e7d4853411b6f72ff62356c652175ab8ff416
Status: Downloaded newer image for netlify/build:latest
mkdir: cannot create directory ‘/opt/buildhome/cache/node_version’: Permission denied
mkdir: cannot create directory ‘/opt/buildhome/cache/ruby_version’: Permission denied
mkdir: cannot create directory ‘/opt/buildhome/cache/node_modules’: Permission denied
mkdir: cannot create directory ‘/opt/buildhome/cache/.bundle’: Permission denied
mkdir: cannot create directory ‘/opt/buildhome/cache/bower_components’: Permission denied
mkdir: cannot create directory ‘/opt/buildhome/cache/.venv’: Permission denied
mkdir: cannot create directory ‘/opt/buildhome/cache/.yarn_cache’: Permission denied
mkdir: cannot create directory ‘/opt/buildhome/cache/.cache’: Permission denied
mkdir: cannot create directory ‘/opt/buildhome/cache/.cask’: Permission denied
mkdir: cannot create directory ‘/opt/buildhome/cache/.emacs.d’: Permission denied
mkdir: cannot create directory ‘/opt/buildhome/cache/.m2’: Permission denied
mkdir: cannot create directory ‘/opt/buildhome/cache/.boot’: Permission denied
mkdir: cannot create directory ‘/opt/buildhome/cache/.composer’: Permission denied
mkdir: cannot create directory ‘/opt/buildhome/cache/.gimme_cache’: Permission denied
mkdir: cannot create directory ‘/opt/buildhome/cache/.gimme_cache’: Permission denied
Installing dependencies
ls: cannot access /opt/buildhome/cache/node_version/: No such file or directory
Downloading and installing node v8.12.0...
Downloading https://nodejs.org/dist/v8.12.0/node-v8.12.0-linux-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v8.12.0 (npm v6.4.1)
Attempting ruby version 2.3.6, read from environment
Using ruby version 2.3.6
Using PHP version 5.6
Installing gem bundle
There was an error while trying to write to `/opt/buildhome/repo/.bundle/config`. It is likely that you need to grant
write permissions for that path.
Error during gem install
Makefile:17: recipe for target 'website' failed
make: *** [website] Error 1
```

**Comment by chrishoffman** [comment]
Thanks for the report!  This is a new website process and we are aware that things have slowed down significantly.  Over the coming weeks we are going to work to improve the development experience and hopefully have a process that is more similar to the old experience.

**Comment by nwbt** [comment]
same same ... keep up the awesome work!

**Comment by tyrannosaurus-becks** [comment]
This appears to be related to https://github.com/netlify/build-image/issues/177.

**Comment by tyrannosaurus-becks** [comment]
The issue here is that when our `make website` script attempts to mount the volumes, at `/opt/buildhome/repo` and `/opt/buildhome/cache`, the resulting folders have a group of "1000" instead of "nogroup", and they have an owner of "1000" instead of "buildbot". The rest of the script within the "build" command attempts to run as buildbot and doesn't have permission to make the directories needed for the dependencies.

I haven't found a great way around this yet. If I do I'll PR.

**Comment by marcosnils** [comment]
Thx for the update @tyrannosaurus-becks . I'm wondering what's the purpose of the makefile and that target if it fails for everyone that's trying to run it :confused:

**Comment by marcosnils** [comment]
@tyrannosaurus-becks I've fixed it here https://github.com/hashicorp/vault/compare/master...marcosnils:patch-1. As stated in the commit, it took a lot of time for me to download dependencies and start the site in the container. I feel like this could be drastically improved.

**Comment by tyrannosaurus-becks** [comment]
@marcosnils it's a step in the right direction! Thank you! I will test that PR today, and I'm going to recruit a colleague with a Mac to make sure it still works for them (I assume it would but a test never hurts), and assuming all is well we'll get it merged.
