### ISSUE TITLE
Vault is sealed randomly. 

### ISSUE THREAD

**Issue by Kareny** [hashicorp/vault#5593]
**Describe the bug**
The vault service randomly seals itself with the following error:

```
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.633785 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.637308 [INFO ] expiration: restoring leases
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.637363 [INFO ] rollback: starting rollback manager
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.637381 [DEBUG] expiration: collecting leases
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.638427 [DEBUG] expiration: leases collected: num_existing=0
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.638659 [INFO ] expiration: lease restore complete
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.638996 [DEBUG] identity: loading entities
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.639444 [DEBUG] identity: entities collected: num_existing=0
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.639699 [INFO ] identity: entities restored
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.639716 [DEBUG] identity loading groups
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.640213 [DEBUG] identity: groups collected: num_existing=0
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.640255 [INFO ] identity: groups restored
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.670256 [INFO ] core: post-unseal setup complete
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.671465 [INFO ] core/startClusterListener: starting listener: listener_address=0.0.0.0:8201
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.672310 [INFO ] core/startClusterListener: serving cluster requests: cluster_listen_address=[::]:8201
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.695158 [DEBUG] core: sealing barrier
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.695328 [INFO ] core: vault is sealed
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.695610 [ERROR] core: failed to lookup token: error=failed to read entry: Vault is sealed
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.696743 [ERROR] core: failed to lookup token: error=failed to read entry: Vault is sealed
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.722374 [ERROR] core: failed to lookup token: error=failed to read entry: Vault is sealed
Oct 20 07:45:00 EASTSECDL01 docker[20633]: 2018/10/20 07:45:00.724452 [ERROR] core: failed to lookup token: error=failed to read entry: Vault is sealed
```

Even with the debug log turned on, there's no much information about why vault seals itself. I tried manually unseal vault with unseal key, but vault is unable to unseal with status code of 503. 
The workaround for this issue now is to restart vault service. But the issue will occur again once every 5-7 days. 

**To Reproduce**
1. Start vault service
2. Start the dependent service which is retrieving secrete from vault every 5 minutes
3. After couple days, vault seals itself

**Expected behavior**
Vault should not seals itself randomly.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.9.1
* Vault CLI Version (retrieve with `vault version`): Vault v0.9.1 ('87b6919dea55da61d7cd444b2442cabb8ede8ab1')
* Server Operating System/Architecture: Centos 7

Vault server configuration file(s):

```hcl
disable_mlock = true
storage "consul" {
  address = "HOST_IP:8080"
  scheme = "https"
  tls_key_file = "/opt/vault/etc/ssl/vault-key.pem"
  tls_cert_file = "/opt/vault/etc/ssl/vault-cert.pem"
  tls_ca_file = "/opt/vault/etc/ssl/ca.pem"
}
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_key_file = "/opt/vault/etc/ssl/vault-key.pem"
  tls_cert_file = "/opt/vault/etc/ssl/vault-cert.pem"
  tls_client_ca_file = "/opt/vault/etc/ssl/ca.pem"
}
```

**Additional context**
There's a program (multi-thread) that is retrieving secretes from vault on a schedule basis like every 5 minutes. The program will do the following things:
- unseal vault
- vault read ..
- seal vault

We use consul as recommended as the storage backend for vault. But there's no error log from consul log and consul is running when vault seals itself.

**Comment by chrishoffman** [comment]
According to your additional context, your workflow appears to be unsealing, reading, and then sealing again.  Why are you doing this instead of just leaving vault unsealed?  Likely something is going wrong here because the only time I've seen issues with sealing like this would be connectivity issues with the storage backend but that would show up in the logs.

**Comment by Kareny** [comment]
@chrishoffman The reason to seal vault is because the program is fetching the secrets from vault on schedule which is configurable. We thought it's better to keep vault sealed between the reading actions. Will frequently unsealing/sealing vault trigger issues for storage backend connectivities?

**Comment by chrishoffman** [comment]
No, but there is a bunch of startup and shutdown tasks that need to run on every seal/unseal and it this is not a normal workflow we see, so you could be hitting some bug but my guess is there is some race in your unseal/read/seal workflow that is causing this issue.
