### ISSUE TITLE
Telemetry should include sizes of internal lists

### ISSUE THREAD

**Issue by maf23** [hashicorp/vault#5598]
**Is your feature request related to a problem? Please describe.**
Our vault server crashed when the number of stored identities got too large. We might have seen this before if we had a metric listing the number of identities in the database.

**Describe the solution you'd like**
My suggestion is that vault would log the size of some useful internal databases (number of identities, leases tokens etc) among the other telemetry information when that is configured.

**Describe alternatives you've considered**
I could list the identities and leases and count the number of returned entries. But if those lists are big it creates an unnecessary strain on the system.

**Explain any additional use-cases**
This would be good for all sorts of monitoring and would make it easier to see how much you use vault.

**Comment by ncabatoff** [comment]
Hi @maf23,

This was a great idea, and over the last year or two we've added metrics to cover this and more: https://www.vaultproject.io/docs/internals/telemetry.  Sorry it took so long!
