### ISSUE TITLE
Provide a way to query or export a metric containing the current number of root tokens

### ISSUE THREAD

**Issue by cpick** [hashicorp/vault#5609]
**Is your feature request related to a problem? Please describe.**
We occasionally generate root tokens to perform `vault` maintenance/reconfigurations.  It would be nice to be able to easily determine whether they've been properly revoked after the maintenance is over. 

**Describe the solution you'd like**
It would be great if the number of root tokens was included in `vault`s telemetry so we could pipe it into our monitoring/alerting systems (even just a Boolean indicating whether any root tokens exist would suit us well). 

**Describe alternatives you've considered**
`vault list auth/token/accessors` plus a series of `vault token lookup -accessor ...` queries can be used to see if there are any root tokens, but this is a pretty powerful set of commands.  We would like to get this information with much lower (no?) privileges.

**Comment by jefferai** [comment]
Vault can't do this internally any faster than the exact workflow you're performing, so doing this in an automatic way outside of a specific intended user request flow could cause a significant amount of load on the Vault server and IOPS in cloud environments.

**Comment by cpick** [comment]
That's understandable.  Our use case would be well-served with an explicit/periodic request.

**Comment by cpick** [comment]
@chrishoffman I think that requiring a manual process is sensible, but automation is not the main thing we were hoping to achieve with this feature request. 
The main shortcoming with the current situation is that trying to find out if there are any root tokens requires listing "auth/token/accessors" which itself is a very powerful request (ie it allows the requester to revoke all active tokens).

We were hoping to find a much safer way to determine if there are any existing root tokens.
