### ISSUE TITLE
GPG public keys as -key-shares for init?

### ISSUE THREAD

**Issue by yawn** [hashicorp/vault#562]
With GPG support being available in Golang I'd like to start a discussion about the following feature request for `vault init`

* as an alternative to `-key-shares=n` the option `-gpg-shares=keyfile1.pub,keyfile2.pub,keyfile3.pub` can be specified
* the resulting unseal key shards are never available in plain text - instead vault will write encrypted shards to disk (or possibly output them ascii-armored)

As an alternative to building this in I'd propose a `format=json` for `init` (unless the current ASCII output is considered "stable"). Combined with a script this could automate the process of feeding this data into GPG (with the additional possible benefit of an associated keychain).

If there is some interest in this I can probably provide a first PR.

**Comment by ekristen** [comment]
+1

**Comment by sethvargo** [comment]
Closely related with https://github.com/hashicorp/vault/issues/72

**Comment by jefferai** [comment]
It's somewhat related with the ask for AMS KMS/IAM integration, which itself should probably be a separate issue from #72. (Although rather than Vault reaching out I'd probably rather have people pull the value in a script and send it to Vault's API).

This is more about helping to secure the manual unsealing process (since presumably you're not going to put the password to the private key in a script). This is probably one of the better approaches.

**Comment by yawn** [comment]
Exactly (the latter). I never actually see key shards when `init`ializing a vault using `-gpg-shares` which seems like a reasonable way of doing that.

**Comment by jefferai** [comment]
Oops, apologize for whatever happened in the picker. This needs some discussion internally.

**Comment by jefferai** [comment]
@yawn Take a look in the branch if you like. Once this gets reviewed I'll merge it in.

**Comment by yawn** [comment]
I'll have a look at it this afternoon and comment - different timezones!

**Comment by yawn** [comment]
Ok, couple of remarks:

The output format of `init` is not explicitly documented as stable which makes it difficult to build tooling around the current `Key n: <hexdump>`-style output. Since the keys do not contain sensitive material anymore I'd strongly advise to write them to disc, using a filename convention. Example: using `yawn.pub` for sealing would result in `yawn.shard`. If you dislike that I would suggest to:

1. create a stable output format in JSON instead of hexdumping to stdout (an additional option could be a format suitable for piping into `mail`)
* use ASCII-Armor (which unfortunately has to be newline-escaped in JSON) or base64 encoding (to differentiate it from plaintext hexencoded keys) instead of hexdumping binary
* In both cases it would be convenient to include the email address from the public key metadata (if present) to make it even easier to further automate the process - if we keep the outputs in the same order the keys were supplied in this should not create matching problems  

Another thing is the actual payload of the encryption: currently the key is encrypted as binary payload. I would advise to encode it as hexencoded; sure it's twice the size it could be but that should not matter at all in this context and avoids another round of encoding to the (expected) hexdump format.

Other things that might be put into the payload (switching to JSON):

* E-Mail and/or Key-IDs of the other key shares
* Vault version

Possible variant for an output JSON:

```
{
  "InitialRootToken": "43acb23d-9008-4b6e-8fa4-aa8f5a9d2bb6",
  "Keys": [
    {
      "Type": "PGP",
      "Metadata": {
          "EMail": "yawn@example.com",
          "ID": "4096R/58ACD84F"
      },
      "Value": "-----BEGIN PGP MESSAGE-----\\nCharset: ISO-8859-1\\nVersion: GnuPG v1.5.0 (GNU/Hurd)\\n\\neM3IyLmXvKp7zVTTwEU6Sbws0mUqvi4XwqNTuBwcn/aNQe6lTj+u26Bd7+kmEH02\\nLj0tgPsP6+4A5b7Rzbf/I08z12LUJjyVXw4M/rSzJkrcpLN24iB/IcT0g1+HdLJF\\n[...]\\nnGqQbYRqMi64GCZ+4m0cSvQaIF9WOhSQDXR4KndYSc8/jiV2D+Ru5JH8j8Zgih9R\\nfha90PPvd01OPhfrRs/Awt61AvOV9stlO9ZTqO/dozl33FMW\\n=xP1s\\n-----END PGP MESSAGE-----"
  },
  {
    "Type": "PGP",
    "Metadata": {
        "EMail": "yawn2@example.com",
        "ID": "4096R/DEADBEEF"
    },
    "Value": "-----BEGIN PGP MESSAGE-----\\nCharset: ISO-8859-1\\nVersion: GnuPG v1.5.0 (GNU/Hurd)\\n\\neM3IyLmXvKp7zVTTwEU6Sbws0mUqvi4XwqNTuBwcn/aNQe6lTj+u26Bd7+kmEH02\\nLj0tgPsP6+4A5b7Rzbf/I08z12LUJjyVXw4M/rSzJkrcpLN24iB/IcT0g1+HdLJF\\n[...]\\nnGqQbYRqMi64GCZ+4m0cSvQaIF9WOhSQDXR4KndYSc8/jiV2D+Ru5JH8j8Zgih9R\\nfha90PPvd01OPhfrRs/Awt61AvOV9stlO9ZTqO/dozl33FMW\\n=xP1s\\n-----END PGP MESSAGE-----"
    }
  ]
}
```

**Comment by jefferai** [comment]
> The output format of init is not explicitly documented as stable which makes it difficult to build tooling around the current Key n: <hexdump>-style output. Since the keys do not contain sensitive material anymore I'd strongly advise to write them to disc, using a filename convention. Example: using yawn.pub for sealing would result in yawn.shard

A problem there is if the keys cannot be written (for instance, directory permissions permit reading but not writing). Then you have an initialized Vault but no unseal keys.

> create a stable output format in JSON instead of hexdumping to stdout (an additional option could be a format suitable for piping into mail)

Many Vault commands already support output in JSON. These don't, but I think that is a reasonable future request. I would probably still prefer the output to be a hexdump, though, to keep parity with the console output.

> In both cases it would be convenient to include the email address from the public key metadata (if present) to make it even easier to further automate the process - if we keep the outputs in the same order the keys were supplied in this should not create matching problems

Email addresses are optional, not required. If they exist they could be put into JSON as a nicety, but since ordering is kept I don't think this is really much of a benefit so far as automatic tooling goes...why do a lookup on email address when you can simply iterate over the list of keys you just submitted?

> Another thing is the actual payload of the encryption: currently the key is encrypted as binary payload. I would advise to encode it as hexencoded; sure it's twice the size it could be but that should not matter at all in this context and avoids another round of encoding to the (expected) hexdump format.

That's a good idea; I'll make that change shortly.

**Comment by jefferai** [comment]
Oh, I forgot to mention something obvious: the whole HTTP API (which is all that the CLI is a helper for) is JSON-oriented. So it's not as rich output as you want, but you can certainly use that for tooling.

**Comment by yawn** [comment]
> Email addresses are optional, not required. If they exist they could be put into JSON as a nicety, but since ordering is kept I don't think this is really much of a benefit so far as automatic tooling goes...why do a lookup on email address when you can simply iterate over the list of keys you just submitted?

Much easier to automate the process of actually *sending* those keys to their recipients this way!

It might also be very useful to include the email addresses / key IDs of the *other* keys used when sealing the vault (this would require changing the payload of the encrypted file to JSON, containing the actual hexencoded key + metadata). It seems to be a good idea to keep this knowledge as close as possible to the key itself.

**Comment by jefferai** [comment]
> Much easier to automate the process of actually sending those keys to their recipients this way!

Perhaps, but initializing Vault is mostly seen as a manual process. If you have a use case that requires doing this over and over again it might be useful to you, but adding the things you'd like to your own wrapper scripts would be pretty trivial. In the mean time, there may be other encryption methodologies eventually supported with their own metadata needs, and the more structured information returned now, the higher a risk of needing to make a breaking change in the future.

At this point, I'd prefer not to make large changes to the signature of /v1/sys/init or /v1/sys/rekey unless there is a truly compelling reason to do so.

**Comment by yawn** [comment]
:+1:
