### ISSUE TITLE
etcd v3 storage: Context deadline exceeded

### ISSUE THREAD

**Issue by vfauth** [hashicorp/vault#5620]
**Describe the bug**
We have been using Vault for a few months with an etcd v3 backend. Recently, it stopped working: Vault doesn't seem to successfully contact etcd anymore. Any request to Vault returns a 500 error code, and the logs contain only these lines:
```
[ERROR] core: barrier init check failed: error="failed to check for initialization: context deadline exceeded"
[ERROR] core: error checking health: error="failed to check for initialization: context deadline exceeded"
```

On etcd, the logs do not have anything. Using tcpdump, we found out that etcd receives the grpc requests, authentication is successful, but the returned data does not seem to be valid for Vault. Otherwise, etcd is working perfectly. Disabling HA, etcd authentication or TLS did not change anything, but reverting to the v2 etcd keystore solves this issue.

Does anyone have any idea of the cause of that issue ?

Versions (it does not seem to matter):
- etcd (official Docker images): 3.3.9 or 3.3.10
- vault (official Docker images): 0.10.0, 0.11.0, 0.11.3, 0.11.4 or 1.0.0-beta1

Thanks!

**To Reproduce**
1. Install a etcd cluster
2. Install a Vault instance, set it to use etcd v3 as a storage backend
3. Initialize Vault, unseal it, then try to use it.

**Environment:**
* Vault Server Version (retrieve with `vault status`): Official Docker images for 0.10.0, 0.11.0, 0.11.3, 0.11.4 or 1.0.0-beta1
* Server Operating System/Architecture: Docker on Debian 9

Vault server configuration file(s):

```hcl
storage "etcd" {
  address       = https://XXX
  etcd_api      = "v3"
  ha_enabled    = "true"
  path          = "/vault/"
  sync          = "false"
  tls_ca_file   = XXX
  tls_cert_file = XXX
  tls_key_file  = X
}

listener "tcp" {
  address                              = "0.0.0.0:9300"
  cluster_address                      = "0.0.0.0:9301"
  tls_disable                          = "false"
  tls_client_ca_file                   = XXX
  tls_cert_file                        = XXX
  tls_key_file                         = XXX
}

disable_mlock = true

ui = true

log_level = "info"

api_addr     = XXX
cluster_addr = XXX

default_lease_ttl = "1h"
max_lease_ttl     = "43800h"
```

**Comment by krwrang** [comment]
Did you find answers to this? I'm seeing similar issues on a 5-node Vault deployment after the cluster has been running for a few weeks.

**Comment by vfauth** [comment]
Well, I am not sure. It may be related to #4349. If it is not, it is probably due to the load balencer we used between Vault and etcd. It has been working well since we removed that LB and fixed the certificate issue.

**Comment by bheiskell-datto** [comment]
Just note, we've seen this without a load balancer in front of etcd. Etcd version 3.3.13 and Vault 1.1.1.

**Comment by petersutty** [comment]
seeing similar issue:
Nov 29 10:36:57 spvault03 vault[926]: {"level":"warn","ts":"2019-11-29T10:36:57.589Z","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-433306e2-8dbe-4400-b6eb-4cd13b6f4507/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Nov 29 10:36:57 spvault03 vault[926]: 2019-11-29T10:36:57.589Z [ERROR] core: writing request counters to barrier: err="failed to save request counters: context deadline exceeded"

etcd --version
etcd Version: 3.4.3
Git SHA: 3cf2f69b5
Go Version: go1.12.12
Go OS/Arch: linux/amd64

vault -v
Vault v1.3.0

it seems it got fixed itself

the only related log I see are this one:
Nov 29 10:36:22 spvault03 etcd[490]: start to snapshot (applied: 934633, lastsnap: 934631)
Nov 29 10:36:22 spvault03 etcd[490]: saved snapshot at index 934633
Nov 29 10:36:22 spvault03 etcd[490]: compacted raft log at 929633
Nov 29 10:36:25 spvault03 etcd[490]: purged file /var/etcd/data/member/snap/0000000000002620-00000000000e4221.snap successfully
Nov 29 10:36:58 spvault03 etcd[490]: **sync duration of 6.173165445s, expected less than 1s**
Nov 29 10:36:59 spvault03 etcd[490]: start to snapshot (applied: 934635, lastsnap: 934633)
Nov 29 10:36:59 spvault03 etcd[490]: saved snapshot at index 934635
Nov 29 10:36:59 spvault03 etcd[490]: compacted raft log at 929635
