### ISSUE TITLE
Homebrew installs no longer support --with-dynamic

### ISSUE THREAD

**Issue by tglawless** [hashicorp/vault#5633]
**Describe the bug**
My team uses Vault behind a firewall which requires VPN.  Up until recently we have been able to install Vault using `brew install vault --with-dynamic` to enable cgo which results in successful private DNS lookups when connected using a VPN.  It appears this flag is no longer supported by the Vault formula.

**To Reproduce**
1. Run `brew install vault --with-dynamic`
2. See warning `Warning: vault: this formula has no --with-dynamic option so it will be ignored!`
3. Run `brew options vault`
4. No formula options are provided

**Expected behavior**
Vault can be install using Homebrew on MacOS with cgo enabled so connections can be made to vault servers using VPN connections.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.4
* Vault CLI Version (retrieve with `vault version`): 0.11.4
* Server Operating System/Architecture: Linux (Server) / MacOS (Client)

**Comment by chrishoffman** [comment]
The homebrew package is not maintained by this project.  Please open an issue with the homebrew repository.
