### ISSUE TITLE
UI doesn't allow JSON edits for KV v2

### ISSUE THREAD

**Issue by MartinLeedotOrg** [hashicorp/vault#5635]
**Describe the bug**
New versions of the secret created through the Vault UI with the JSON toggle appear to create a version identical to the previous version.

**To Reproduce**
1. In Vault UI, click `Create new version` for a kv v2 secret.
2. Toggle JSON on.
3. Change some feature of the secret.
4. Click Save
5. Observe the new version is identical to the old version.

**Expected behavior**
`Create new version` should work the same if JSON is toggled on or off

**Environment:**
Vault 1.0.0-beta1 and 0.11.4

<img width="821" alt="image" src="https://user-images.githubusercontent.com/633668/47666864-8787b880-db9c-11e8-93d8-a07f5daafe91.png">
<img width="817" alt="image" src="https://user-images.githubusercontent.com/633668/47666879-8eaec680-db9c-11e8-88e1-123fd27a0be4.png">
<img width="830" alt="image" src="https://user-images.githubusercontent.com/633668/47666894-94a4a780-db9c-11e8-9d1f-cedfe0984d36.png">

**Comment by azuretek** [comment]
I'm experiencing the same problem on kv v1 as well as kv v2.

**Comment by meirish** [comment]
Fixed by https://github.com/hashicorp/vault/pull/5660
