### ISSUE TITLE
Vault doesn't check existence of policies

### ISSUE THREAD

**Issue by sokoow** [hashicorp/vault#5644]
**Describe the bug**
When a typo or a wrong name of policy occurs on a role, vault doesn't log any errors and or check policy's existence. 

**To Reproduce**
1. Let's say I'm creating a policy like this:

```hcl
path "secret/supersecret/*" {
  policy = "write"
}
```

I'll name it **mypolicy**

2. then we create an approle that uses it, but with a little twist
```bash 
$ vault auth enable approle
$ / #  vault write auth/approle/role/my-role policies=\'mypolicy\'
Success! Data written to: auth/approle/role/my-role
```

3. Let's read approles policies, to see what's there:
```bash
$  vault read auth/approle/role/my-role
Key                   Value
---                   -----
bind_secret_id        true
bound_cidr_list       []
local_secret_ids      false
period                0
policies              ['mypolicy']
secret_id_num_uses    0
secret_id_ttl         0
token_max_ttl         0
token_num_uses        0
token_ttl             0
```

And ... it is there, in a form of 'mypolicy', not mypolicy - exactly like we wanted to skew it.

**Problem here**: it's pretty easy to create these escaped names of policies, unintentionally - that causes vault to 403 on all seemingly affected kv paths -  and we've just spent couple of hours trying to figure out what was going on... (using https://github.com/hvac/hvac here)

**Expected behavior**
Vault should be checking existence of a policy name that is attached to a role - or log anything to the main log in case it can't resolve policy name

**Environment:**
All vault versions

**Comment by jefferai** [comment]
A policy that "doesn't exist" is simply empty. Since policies can be modified at any time, it's not uncommon for people to deploy with policies that have yet to be defined.

Vault will warn when authenticating if a policy is empty.
