### ISSUE TITLE
Support long-lived policy-constrainted tokens

### ISSUE THREAD

**Issue by sheldonh** [hashicorp/vault#565]
I understand why Vault enforces a maximum time to live for policy-constrained tokens.

However, I would love a configuration option to relax this, to ease transition. We're pushing hard for our developers to move away bad practices (secrets in git repos and secrets on filesystems that are lost forever when the host dies). I appreciate that long-lived tokens are also a bad practice, but they're less bad, and we want developers to get on board before we invest in the provisioning infrastructure required to support short-lived policy-constrained tokens.

Pretty please?

**Comment by jefferai** [comment]
This is already done - see #469. :smile:

**Comment by sheldonh** [comment]
Oops, sorry. And thanks. :-)
