### ISSUE TITLE
unable to ssh to target server using Vault ssh management 

### ISSUE THREAD

**Issue by nileshpadwal456** [hashicorp/vault#5673]
**Describe the bug**

I am trying archive Signed SSH Certificates using vault. I have non expired signing key too but still prompting for password

ssh-keygen -Lf $HOME/.ssh/cert-signed.pub
/root/.ssh/cert-signed.pub:
        Type: ssh-rsa-cert-v01@openssh.com user certificate
        Public key: RSA-CERT SHA256:nEPnetqmHkB2vVtu8VR1gM86Ng4JPfnWE4d8CsatkIE
        Signing CA: RSA SHA256:63YWn/Wz3YsRzv+2EI7goh/jraX3+cDefvrJL2oSI8s
        Key ID: "plain-withoutroot"
        Serial: 15545213441613126839
        Valid: from 2018-11-02T09:04:22 to 2018-11-02T10:04:52
        Principals: 
                websphere
        Critical Options: (none)
        Extensions: 
                permit-pty
root@Developer-Server:~# ssh -i $HOME/.ssh/id_rsa -i $HOME/.ssh/cert-signed.pub websphere@xxxx 
websphere@xxxxxxxxxxx's password: 

**Configuration**
**Vault Server**
Enable SSH-Client 
vault secrets enable -path=ssh-client ssh
Generate signing key
vault write -field=public_key ssh-client/config/ca   generate_signing_key=true | sudo tee /etc/ssh/trusted-user-ca-keys.pem

Create Roles

cat > regular-user-role.hcl <<EOF
{
    "allow_user_certificates": true,
    "allowed_users": "websphere,nginx,aem-auther,aem-dispatcher,aem-publisher,sathish",
    "default_user": "aem-auther",
    "allow_user_key_ids": "true",
    "default_extensions": [
        {
          "permit-pty": ""
        }
    ],
    "key_type": "ca",
    "ttl": "60m0s",
    "allow_user_key_ids": "false",
    "key_id_format": "{{token_display_name}}"
}
EOF
 
cat regular-user-role.hcl | vault write ssh-client/roles/regular –

Create Policies
 
cat > regular-user-role-policy.hcl <<EOF
path "ssh-client/sign/regular" {    
capabilities = ["create","update"]
}
EOF

 vault policy write ssh-regular-user regular-user-role-policy.hcl

 Enable USERPASS 
  vault auth enable -path=plain userpass

Create usergroup and assign policies to that

vault write auth/plain/users/withoutroot   password="withoutroot"   policies="ssh-regular-user"

vault write auth/plain/users/withroot   password="withroot"   policies="ssh-regular-user,ssh-root-user"

**Developer Server** 

vault login -path=plain -method=userpass username=withoutroot password=withoutroot
vault write -field=signed_key ssh-client/sign/regular valid_principals="websphere" public_key=@$HOME/.ssh/id_rsa.pub > $HOME/.ssh/cert-signed.pub
ssh -i $HOME/.ssh/id_rsa -i $HOME/.ssh/cert-signed.pub websphere@xxxxx

**New Target VM**
curl -o /etc/ssh/trusted-user-ca-keys.pem http://xxxxxx:8200/v1/ssh-client-signer/public_key

vim /etc/ssh/sshd_config
TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem

**Comment by christophetd** [comment]
Posting here the last few lines of `/var/log/auth.log` could help to determine why the connection fails

**Comment by nileshpadwal456** [comment]
Made mistake while retrieving public key.
curl -o /etc/ssh/trusted-user-ca-keys.pem http://xxxxxx:8200/v1/ssh-client-signer/public_key
Issue resoled.

**Comment by Fastersush** [comment]
Hi , 
can anyone help me with step by step configuration of ssh ca 
what shud i configure on vault server and what  would be the configuration  on target vm(machine on which need to ssh)
i tried multiple solutions but now m confused, what shud be the perfect configuration
your help is really appreciated

**Comment by Fastersush** [comment]
Hi Nilesh,
Can u please let me know if vault server and Developer server u referring are the same.
Your quick response is really appreciated , i am stuck since last couple of day on this setup

Thanks in advance
