### ISSUE TITLE
TokenMetadata method on Secret does not handle values that are not strings

### ISSUE THREAD

**Issue by jcmturner** [hashicorp/vault#5680]
**Describe the bug**
Using the Go API, the Secret [TokenMetadata](https://github.com/hashicorp/vault/blob/5269abb64c878aabbf91d0e54befb314630fae12/api/secret.go#L195) method errors when the metadata has values that are either boolean or integers. For example, this affects the metadata that comes back when reading a secret from the KV Secrets Engine V2. See example response: https://www.vaultproject.io/api/secret/kv/kv-v2.html#sample-response

**To Reproduce**
Steps to reproduce the behaviour:
(In Go)
1. Read a secret from a location using the KV Secret Engine V2
2. On the secret object returned call the TokenMetadata() method
3. The error value returned from this call will error with either:
``unable to convert metadata value false to string``
or
``unable to convert metadata value 1 to string``

**Expected behaviour**
Should not error. Integers or booleans should be converted to a string form and returned in the map[string]string response.

**Environment:**
* Git commit: git rev-parse HEAD
ba57e14ae8fd18d4131a488134ba50bb3b076910

**Additional context**
I believe the issue comes from this line that assumes all metadata values are strings:
https://github.com/hashicorp/vault/blob/5269abb64c878aabbf91d0e54befb314630fae12/api/secret.go#L218

**Comment by jefferai** [comment]
TokenMetadata, as the documentation for the call indicates, is only for fetching metadata from tokens. The value you are reading from kv is not a token. You need to decode the secret.Data map into an appropriate object yourself (or access its values directly).
