### ISSUE TITLE
Website broke old links without redirects

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault#5681]
https://github.com/kelseyhightower/vault-on-google-kubernetes-engine/pull/10

`/intro/index.html` should redirect to something

**Comment by catsby** [comment]
I opened #5726 for this

**Comment by catsby** [comment]
https://github.com/kelseyhightower/vault-on-google-kubernetes-engine/pull/10 has been resolved so I'm going to close this. Thanks for bringing it to our attention! We'll patch it up in #5728
