### ISSUE TITLE
Add Metadata Field to AppRole Role

### ISSUE THREAD

**Issue by sidewinder12s** [hashicorp/vault#5697]
**Is your feature request related to a problem? Please describe.**
It is difficult to add any kind of ownership information to AppRoles without a metadata field like `secret-id's` have. One use case I had was if we needed to contact all AppRole owners for some reason it'd be much easier if we can just lookup the metadata field of all AppRoles for a contact field. 

**Describe the solution you'd like**
Add a `metadata` field to AppRole Role. 

**Describe alternatives you've considered**
I can add stuff to the policies I attach to each AppRole but this isn't very scalable since policies can be assigned to any token.

**Comment by v6** [comment]
// , You could always set up your own metadata system, with a hash appended to the AppRole name and a lookup table. 

Someone I know might be doing something like that. Ahem.

**Comment by chrishoffman** [comment]
I suggest you look into the identity system where you can attach metadata to the entity that is aliased the AppRole role_id.  See https://www.vaultproject.io/docs/secrets/identity/index.html.

**Comment by sidewinder12s** [comment]
@chrishoffman I'd find it extremely valuable to have more "real" examples of Identity like some of the AppRole consumption examples in the new docs. I hadn't thought of attaching AppRoles to Identity because generally they are machine credentials, only tied to groups if anything. Would I then create an entity for each AppRole, since Operators generally have way more permissions than our AppRoles have.
