### ISSUE TITLE
Renew Self: increment field is not an increment

### ISSUE THREAD

**Issue by Smbc1** [hashicorp/vault#5701]
**Describe the bug**
If you try to `/auth/token/renew-self` with some `increment` value, it will replace actual `ttl`, no increase happens. It's totally unexpected behaviour, not just because of docs, but because of API method signature (`increment` parameter name).

**To Reproduce**
1. Call `/auth/token/lookup-self`, remember `ttl` value
2. Call `/auth/token/renew-self` with `increase = 10`
3. Call `/auth/token/lookup-self`, `ttl = 10`

**Expected behavior**
`increase` value added to original `ttl` value

**Environment:**
* Vault Server Version 0.11.4, latest docker image (06.11.2018)
* Host OS: Ubuntu 14.04 LTS

Vault server configuration file(s): just ran docker container from image

**Comment by jefferai** [comment]
It's the increment from the current time. I'll add a note to documentation to make this more clear.
