### ISSUE TITLE
Support Custom Github api endpoint for Github auth method

### ISSUE THREAD

**Issue by parabuzzle** [hashicorp/vault#572]
I would like to override the Github api endpoint for the Github auth method. There seems to be no way to override it from `api.github.com`.

**Comment by jefferai** [comment]
@parabuzzle You mentioned you have a branch with this -- any chance you're interested in turning this into a PR? It'd be pretty simple to add.

**Comment by parabuzzle** [comment]
I have a branch for vault-ruby to auth against github... I don't have a branch for changing the end point in vault itself. :)

**Comment by parabuzzle** [comment]
also, I'm no good at go yet... so you probably don't want me making this change :)

**Comment by jefferai** [comment]
I'm lodging this as a 0.3 milestone but I can't promise it will stay there.

**Comment by parabuzzle** [comment]
Any idea when this will be released?

**Comment by jefferai** [comment]
We don't announce release dates ahead of time, but the current plan is a couple of weeks or so.
