### ISSUE TITLE
'Symbol' is undefined IE 11

### ISSUE THREAD

**Issue by Skons** [hashicorp/vault#5732]
**Describe the bug**
Vault UI in IE 11 shows 'Symbol' is undefined

![image](https://user-images.githubusercontent.com/13225002/48201689-2661a100-e363-11e8-82e9-56f7bbb62252.png)

![image](https://user-images.githubusercontent.com/13225002/48201752-59a43000-e363-11e8-86ea-55da538f40dc.png)

**To Reproduce**
Go to http://127.0.0.1:8200/ui/vault and the error shows immediately

**Expected behavior**
I would expect a login window

**Environment:**
* Vault Server Version (retrieve with vault status): 0.11.4 (0.11.3 showed the same error)
* Vault CLI Version (retrieve with vault version): 0.11.4 
* erver Operating System/Architecture: Windows 2016

**Comment by meirish** [comment]
This was fixed https://github.com/hashicorp/vault/pull/5714
