### ISSUE TITLE
Client Certificate must be supplied Error when authenticating to vault

### ISSUE THREAD

**Issue by ewatski3** [hashicorp/vault#5745]
Hi Need help!

What is the difference between this two curl command when trying to login in vault (vault that is running on docker container)

**--This curl command returns "{"errors":["client certificate must be supplied"]}"**
curl -k -X POST https://vault:8200/v1/auth/cert/login -d '{"cacert":"certs/vault-tls.crts", "cert":"certs/vault-tls.crt","key":"certs/vault-tls.key"}' 

**--This curl command connect successfully to the vault.**
curl -k -X POST https://vault:8200/v1/auth/cert/login --cacert certs/vault-tls.crt --cert certs/vault-tls.crt --key certs/vault-tls.key 

I'm trying to do a vault authentication using certificate in java  using AbstractVaultConfiguration and ClientCertificateAuthentication for ClientAuthentication. Thanks

**Comment by vishalnayak** [comment]
@ewatski3 

In the first command, the data after `-d` is consumed as the input for the `auth/cert/login` API. It will not be recognized as fields for the `curl` command and hence won't be part of the TLS handshake.

In the second command, the `--cacert`, `--cert` and `--key` are flags *on* the `curl` command. These are used to perform TLS handshake with the Vault server. The connection information from the handshake will be received by Vault and that connection data will have the certificate which gets validated by Vault's backend before a successful login.

**Comment by ewatski3** [comment]
I already resolve this issue. I just created a new JKS file from vault-tls.crt and vault-tls.key and used this JKS file on SSL Configuration.

**Comment by avnban1988** [comment]
@ewatski3 I am getting same issue. Can you please post me detailed  steps you took to resolve this issue
