### ISSUE TITLE
 Enter passphrase for: panic: runtime error: invalid memory address 

### ISSUE THREAD

**Issue by subodhcjoshi82** [hashicorp/vault#5754]
I am trying to run Vault in **MoboXTerm v10.9 build 3656**
`[subod.LAPTOP-G6LR72HL] ➤ vault server -config vault-test.hcl -log-level=info`
and here is my **vault-test.hcl**
```
storage "file" {
   path    = "C:/Software/vault_0.11.4_windows_amd64"
}
ui = true
listener "tcp" {
  address = "0.0.0.0:8200"
  cluster_address = "0.0.0.0:8201"
  tls_cert_file = "C:/Software/openssl_localhost/localhost.crt"
  tls_key_file = "C:/Software/openssl_localhost/localhost.key"
}
```
and above command end with the following error

> [subod.LAPTOP-G6LR72HL] ➤ vault server -config vault-test.hcl -log-level=info
> WARNING! mlock is not supported on this system! An mlockall(2)-like syscall to
> prevent memory from being swapped to disk is not supported on this system. For
> better security, only run Vault on systems where this call is supported. If
> you are running Vault in a Docker container, provide the IPC_LOCK cap to the
> container.
> Enter passphrase for C:/Software/openssl_localhost/vault.key: panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x18 pc=0x5487de]
> 
> goroutine 68 [running]:
> bufio.(*Reader).fill(0xc0005cdf58)
>         /goroot/src/bufio/bufio.go:100 +0xde
> bufio.(*Reader).ReadSlice(0xc0005cdf58, 0x40b80a, 0x6b90e40, 0x0, 0x0, 0xc000048058, 0x57)
>         /goroot/src/bufio/bufio.go:341 +0x3d
> bufio.(*Reader).ReadBytes(0xc0005cdf58, 0x20a, 0xc0005cde84, 0xc0005cde90, 0x440ede, 0x1000, 0x23476a0)
>         /goroot/src/bufio/bufio.go:419 +0x77
> bufio.(*Reader).ReadString(0xc0005cdf58, 0x100a, 0x1000, 0xc0005de000, 0x1000, 0x1000)
>         /goroot/src/bufio/bufio.go:459 +0x3f
> github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*BasicUi).ask.func1(0xc000406901, 0xc0004dbbc0, 0xc000406960, 0xc0004069c0)
>         /gopath/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/ui.go:83 +0xe3
> created by github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*BasicUi).ask
>         /gopath/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/ui.go:76 +0x258
> 
 And version of Vault
 

> Vault v0.11.4 ('612120e76de651ef669c9af5e77b27a749b0dba3')

**Comment by ncabatoff** [comment]
Hi @subodhcjoshi82, thank you for the bug report.  I've been unable to reproduce your issue, using a passphrase protected key with Vault v0.11.4 and Windows 10 in a regular Cmd shell.  I can't see why your use of MoboXTerm would break things, but I suggest you try eliminating that from the equation.  Unfortunately we can't support arbitrary user environments.
