### ISSUE TITLE
Add IAM session name in the display_name of the vault token

### ISSUE THREAD

**Issue by forty** [hashicorp/vault#5761]
**Is your feature request related to a problem? Please describe.**
We use AWS IAM roles with ADFS to authenticate to vault. When we do this, the `display_name` or the token is `aws-<role_name>`. The token `display_name` is then used int the SSH `key id` when we generate SSH certificate. This `key id` is what sshd prints in auth.log.
In the current form, it's not very useful as using auth.log, we have not idea (we have a workaround, see bellow) of who logged in to the machine, as it only tell us the AWS role used.

**Describe the solution you'd like**
When assuming role with ADFS, AWS can be configured to have the ADFS login set in the assume role session name (the session ARN looks like `arn:aws:sts::xxxxxx:assumed-role/<ADFS role>/<login@example.com>`). Ideally, we would be able to add the last part of the ARN (the session name) to the token `display_name`. This would result of the ssh `key id` to look like `vault-aws-<role>-<login>` and auth.log being much more useful 

**Describe alternatives you've considered**
In auth.log, we actually also have the serial number of the certificate, which we can match against the serial number in the vault logs. This is quite impractical as:
- sshd display the serial number in decimal while vault autit log have it in hexadecimal
- the serial number is HMACed in vault audit log so it's annoying to do the match
- it would be really convenient to just have the login of the user in auth.log

Let me know what you think. I'm willing to help coding this, but I have never done any go coding and I'm not sure where to start

**Comment by forty** [comment]
okay, that looks perfect as well, I can try and see if I manage to do that (It looks like I already have the `client_arn` in the `meta` map, so extracting the session name should not be an issue. Thanks

**Comment by forty** [comment]
@jefferai I started writing some code (see commits above), the first one seems to work fine, however I'm struggling a bit to make this one work https://github.com/forty/vault/commit/b53f8f5db0a0c4f58bb8daa74d7444d8624f4662
Any idea why req.Auth seems to be null? I expected to find the authentication information of the request, and it seems it could contain the Metadata as well so that seemed ideal :)

**Comment by forty** [comment]
Apparently I can also get the token info with `req.TokenEntry()`, but it seems `req.tokenEntry` is set to nil before calling the path handler, I don't know why, but I suspect it's for a good reason...

**Comment by forty** [comment]
@jefferai We managed to make it work by removing this commit https://github.com/hashicorp/vault/commit/6ec09a09f4ecec652fa0c3c12eb934943b77622a 
I think this is done to avoid transmitting sensitive information to the backend. Do you have suggestion on how I should transmit the token meta data to the ssh backend ?
Thanks

**Comment by jefferai** [comment]
Why are you looking up the token?

**Comment by jefferai** [comment]
Use EntityInfo from https://godoc.org/github.com/hashicorp/vault/logical#SystemView

**Comment by forty** [comment]
@jefferai Thanks a lot for you help, I'm making progress, I have something that doesn't crash now, but it does not seem to work, do you see anything obviously wrong? https://github.com/forty/vault/commit/82b3f161742d3c230152e646d7afa535f0a85702
I'm having a hard time debugging, because in unit tests things are mocked, and when I try in a real environment on AWS I just see that it does not work, but I'm a bit clueless as of why.
Sorry if my questions are dumb

**Comment by hsimon-hashicorp** [comment]
Hello! As this issue is quite old, I'm going to go ahead and close it now. Please feel free to open a new bug report if needed, or if you have questions you can get help from the community at [our Discuss forums](https://discuss.hashicorp.com/c/vault/30). Thanks!
