### ISSUE TITLE
Add 'datacenter' option to consul backend

### ISSUE THREAD

**Issue by annmuor** [hashicorp/vault#5763]
**Is your feature request related to a problem? Please describe.**
I were trying to setup vault on multi-dc consul cluster ( federation ). I had had to use https consul server api instead of local agent because I can't specify what DC to use in vault configuration file.

**Describe the solution you'd like**
Add 'datacenter' config to consul backend to allow to specify dc in federated consul clusters

**Comment by jefferai** [comment]
If you are connecting to the local agent, Vault will use the local agent's configured datacenter. Isn't this the right thing to do?

**Comment by jefferai** [comment]
I'm still not following.

If you have multiple Vault services, each in their own datacenter, wouldn't you *want* to be connecting to the local datacenter that the local consul agent is tied to?

**Comment by annmuor** [comment]
I have multiple vault services that must provide _the same_ secrets to customers but must be located in _different_ datacenters to reduce outage risks.

**Comment by annmuor** [comment]
On federated consul it’s not true. KV is not synced between datacenters so there will be multiple _different_ vault kvs with same names.

**Comment by jefferai** [comment]
I don't follow the issue. You should *always* point to a local Consul agent. If you want a different Consul datacenter than the "normal" one for the box, run a second Consul agent against the other datacenter.

Or, connect directly to the appropriate Consul servers but ensure that service registration is turned off.

If you want replication we offer it in Enterprise. We don't support any other method, sorry.
