### ISSUE TITLE
Add Configuration option to disable default KV v1 secret/ mount

### ISSUE THREAD

**Issue by cvbarros** [hashicorp/vault#5780]
**Is your feature request related to a problem? Please describe.**
Due to deprecation in the future, we want to completely disable the KVv1 `secret/` mount for our Vault deployments. We automate the provisioning of the server, and currently we have to manually or put in scripts to disable that mount after unsealing.

**Describe the solution you'd like**
A configuration parameter on the server, such as `disableDefaultKv` to allow tuning this behaviour.

**Describe alternatives you've considered**
We now manually (or scripted) disable the default mount KV v1 at `secret/`, so we can enable the KV v2 at `secret` path.

**Explain any additional use-cases**
None I can think of.

**Additional context**
I'm putting together some PR to make this possible. However, it may need some tweaking since it's a first time contribution to Vault.

**Comment by jefferai** [comment]
We actually are going to remove this in 1.1 for everyone, not with a config flag, so I'm going to close this for now.
