### ISSUE TITLE
Remove default KV mount for non-dev

### ISSUE THREAD

**Issue by jefferai** [hashicorp/vault#5783]
Migrating this to GH from our internal roadmap for visibility due to #5780.

**Comment by sidewinder12s** [comment]
Does this mean that in 1.1 (or a future version) KV V1 is being removed completely from Vault?

**Comment by tyrannosaurus-becks** [comment]
@meirish do you happen to know whether it should only be mounted for `-dev`, or for the other dev flags too?

**Comment by jefferai** [comment]
Should be any time you're in dev mode. Some flags turn on dev mode implicitly.

**Comment by tyrannosaurus-becks** [comment]
FWIW, #6109
