### ISSUE TITLE
cannot get secrets back as lost unseal keys

### ISSUE THREAD

**Issue by freidenker** [hashicorp/vault#5795]
any one could help me with that?

**Comment by freidenker** [comment]
i just lost all three the unseal keys, when vault service was down, i can NOT get it back. Because i want to keep the backend data included my secrets, so i need to restart vault with old backend data. Besides, i have the root token.

**Comment by jefferai** [comment]
If you lose your unseal keys, you can't unseal Vault. That's a feature. Sorry that you can't get to your data, but at least nobody else can either...
