### ISSUE TITLE
Logical() doesn't return token on client.Logical().Write("auth/approle/login", data) with custom approle mount name

### ISSUE THREAD

**Issue by bartwalczak1** [hashicorp/vault#5796]
**Describe the bug**
I've created approle auth mount with custom name. Next I am getting secret id and role id from Logical().
Next I am trying to login and get token but response is empty (apart from request id).

Same action via curl works.

```
rootKey = "redacted"
	client.SetToken(rootKey)

	//fmt.Println(sys.ListAuth())

	data := map[string]interface{}{
		"policies": "default",
	}
	//create role
	//	_, err = client.Logical().Write("auth/bartmount/role/bartrole", data)

	// get role id
	resp, err := client.Logical().Read("auth/bartmount/role/bartrole/role-id")
	roleID := resp.Data["role_id"]
	//fmt.Println("resp: ", roleID)

	// get secret id
	data = map[string]interface{}{}
	resp, err = client.Logical().Write("auth/bartmount/role/bartrole/secret-id", data)
	secretID := resp.Data["secret_id"]

	// login via approle

	data = map[string]interface{}{
		"role_id":   roleID,
		"secret_id": secretID,
	}
	fmt.Println("roleid: ", roleID)
	fmt.Println("secretId", secretID)
	fmt.Println(data)
	resp, err = client.Logical().Write("auth/bartmount/login", data)

	fmt.Println(resp.Data)
```
<img width="852" alt="screen shot 2018-11-15 at 10 21 49" src="https://user-images.githubusercontent.com/13851484/48546996-8efbd100-e8c1-11e8-9c2a-27a0ad5d5c15.png">

via curl:
<img width="1640" alt="screen shot 2018-11-15 at 10 23 26" src="https://user-images.githubusercontent.com/13851484/48547009-94591b80-e8c1-11e8-98f9-33d8bb930115.png">

**Expected behavior**
returned token id for given role id

**Environment:**
* Vault Server Version (retrieve with `vault status`):
Vault v0.11.4 ('612120e76de651ef669c9af5e77b27a749b0dba3')
* Vault CLI Version (retrieve with `vault version`):
"version":"0.11.4"
* Server Operating System/Architecture:
docker container

**Comment by vishalnayak** [comment]
Login data will be present in the `auth` field in the response. The output of the `curl` command illustrates this.
