### ISSUE TITLE
vault operator migrate does not honor storage TLS settings

### ISSUE THREAD

**Issue by jsok** [hashicorp/vault#5805]
**Describe the bug**

`vault operator migrate` appears to not use the TLS settings of the storage configuration(s).

**To Reproduce**

1. Start 2 vault instances - one backed by `etcd_api=v2`, another with `etcd_api=v3`
1. Init and unseal both instances, write some data to the `v2` instance
1. Create a `migrate.hcl` file like:

    ```hcl
    storage_source "etcd" {
        address = "https://192.168.100.2:2379"
        etcd_api = "v2"
        ha_enabled = "true"
        path = "/vault"
        tls_ca_file = "source.ca.pem"
        tls_cert_file = "source.client.pem"
        tls_key_file = "source.client-key.pem"
    }

    storage_destination "etcd" {
        address = "https://192.168.200.2:2379"
        etcd_api = "v3"
        ha_enabled = "true"
        path = "/vault"
        tls_ca_file = "destination.ca.pem"
        tls_cert_file = "destination.pem"
        tls_key_file = "destination.client-key.pem"
    }
    ```
1. Run `vault operator migrate -config migrate.hcl`

**Expected behavior**

The migration should run.

**Actual behavior**

```
> vault operator migrate -config migrate.hcl
Error migrating: error checking migration status
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.11.5
* Vault CLI Version (retrieve with `vault version`): 0.11.5
* Server Operating System/Architecture: Linux

Vault server configuration file(s):

Instance 1:

```hcl
cluster_name = "source"
api_addr = "https://192.168.100.3:8200"

listener "tcp" {
  address = "192.168.100.3:8200"
  cluster_address = "192.168.100.3:8201"
  tls_cert_file = "/etc/vault/vault.pem"
  tls_key_file = "/etc/vault/vault-key.pem"
}

storage "etcd" {
  address = "https://192.168.100.2:2379"
  etcd_api = "v2"
  ha_enabled = "true"
  path = "/vault"
  tls_ca_file = "/etc/vault/etcd.ca.pem"
  tls_cert_file = "/etc/vault/etcd.client.pem"
  tls_key_file = "/etc/vault/etcd.client-key.pem"
}
```

Instance 2:

```hcl
cluster_name = "destination"
api_addr = "https://192.168.200.3:8200"

listener "tcp" {
  address = "192.168.200.3:8200"
  cluster_address = "192.168.200.3:8201"
  tls_cert_file = "/etc/vault/vault.pem"
  tls_key_file = "/etc/vault/vault-key.pem"
}

storage "etcd" {
  address = "https://192.168.200.2:2379"
  etcd_api = "v3"
  ha_enabled = "true"
  path = "/vault"
  tls_ca_file = "/etc/vault/etcd.ca.pem"
  tls_cert_file = "/etc/vault/etcd.client.pem"
  tls_key_file = "/etc/vault/etcd.client-key.pem"
}
```

**Additional context**

N/A

**Comment by jefferai** [comment]
What is the evidence it's not honoring TLS settings? You haven't pasted any log information.

**Comment by jsok** [comment]
Sorry! I wrote it then somehow removed it while editing the report.

The linux client seems to give less verbose errors, but the darwin one gives a bit more of a hint and only when using the `reset` option:

```
> vault operator migrate -config migrate-local.hcl -reset                  
Error migrating: error mounting 'storage_source': failed to get etcd API version: client: etcd cluster is unavailable or misconfigured; error #0: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "fake source CA")
```

On the linux client it just gives:
```
Error migrating: error reseting migration lock: x509: certificate signed by unknown authority
```

I've poked around in the source etcd v2:

```
> etcdctl ls /vault/core/migration
Error:  100: Key not found (/vault/core/migration) [186]
```

**Comment by jsok** [comment]
Ah I believe I've found my issue! Thanks for you patience.

I was running each etcd instance on a separate docker network but both had `ETCD_NAME=etcd`.
The migrate command was running in a container attached to both networks. So when the etcdclient in vault got a members list (successfully as indicated by the etcd debug logs) it would try to resolve `etcd` and get the same result (whichever docker's DNS returned first) for both the source and destination etcdclient - therefore one of them would always fail the CA verification.

Setting `ETCD_NAME=etcd.{source,destination}` and some docker network aliases has resolved this problem.

**Comment by kalafut** [comment]
@jsok Glad you figured it out. In your initial report you mentioned that you had inited and unsealed the second instance. Just to be clear, the migration operation is intended to be an offline operation, and the destination needn't be inited in any way, just writable. The result will be a verbatim clone of your source data.

As an aside, I'm glad you happened to find the detailed error with `-reset`. It should have also been shown during your original migrate attempt, and a PR is up to fix this.

Thanks.
