### ISSUE TITLE
advertise_addr environment variable or command line flag

### ISSUE THREAD

**Issue by JeanMertz** [hashicorp/vault#581]
Our vault config looks like this (for starters):

```hcl
backend "consul" {
  address = "consul"
  path = "vault"
}

listener "tcp" {
 address = "0.0.0.0:8200"
 tls_disable = 1
}
```

We're running consul + vault on top of Kubernetes. Unfortunately, the pod that runs Vault isn't running a Consul agent (for now), so auto-ip detection is not possible.

I can't know the local container IP beforehand, so I can't define it in the config file. I *do* know it when the command is started, so I could set it through a command line flag or environment variable, but both aren't possible (without writing some bootstrap script that updates the config file).

Could this be added as an option?

**Comment by l8nite** [comment]
Ever figure this out @JeanMertz ?

**Comment by jefferai** [comment]
I'll get this in soon. There is a PR that will conflict, so once that is merged I'll implement this.

**Comment by skevy** [comment]
@JeanMertz were you able to resolve this on Kubernetes using the new environment var?

**Comment by luigiberrettini** [comment]
@JeanMertz  in what sense the container IP is known when the command is started?
When you execute docker run you do not know the container IP.
Do you refer to knowing the container IP from within the container when e.g. an entrypoint script is called?
