### ISSUE TITLE
ui: Dropdown in web ui is shown empty

### ISSUE THREAD

**Issue by tomschlenkhoff** [hashicorp/vault#5817]
**Describe the bug**
In the latest beta2 (as well as in beta1) the web ui does show an empty dropdown menu in the "list"-action.

**Environment**
Latest Chrome  (72) and Firefox 63.0.3 with latest beta2 of vault on Ubuntu 18.04.1 LTS.

**Expected behavior**
Either do not show the "more points" (...) or show the contents of the dropdown menu (<nav class="menu">).

<img width="666" alt="screen shot 2018-11-19 at 17 33 10" src="https://user-images.githubusercontent.com/941842/48721339-feefbb80-ec21-11e8-9d56-d3b1c583e529.png">

**Comment by meirish** [comment]
Hi @tomschlenkhoff ! Thanks for the report - what secret engine are you using in the screenshot?

**Comment by tomschlenkhoff** [comment]
Sorry, different time zone :) But this is the correct engine. Thanks!
