### ISSUE TITLE
Transit support for ED25519 encryption / decryption (similar to RSA)

### ISSUE THREAD

**Issue by KrishnaPG** [hashicorp/vault#5832]
**Is your feature request related to a problem? Please describe.**
It is not possible to create an ed25519 key or ecdsa key that supports Encryption / Decryption. Currently they only have signing capability. 

**Describe the solution you'd like**
Please enable support for ed25519 and Ecdsa token to have encryption / decryption ability. Similar to how RSA has support

Bidirectional (two-party, two-way) encryption need to be able to done with the ed25519 keys, just by exchanging the public-keys, through transit functions, without ever anyone (or caller app) knowing the private keys.

**Comment by jefferai** [comment]
ED25519 is a public-key signature system, not an encryption system.

**Comment by KrishnaPG** [comment]
How, then, do you propose should one implement cryptobox functionality on top of transit?

Are you saying nacl's cyrptobox is incorrect and they dont' know what they are doing?

**Comment by KrishnaPG** [comment]
How to arrive at such functionality on Transit? Specifically `Public-key authenticated encryption`, not just signing. Two-parties need to exchange data, without the app having to know their private keys.

**Comment by jefferai** [comment]
Please open a new ticket for a new request.

**Comment by KrishnaPG** [comment]
Thanks. Created https://github.com/hashicorp/vault/issues/5835
