### ISSUE TITLE
AWS auth backend assume role

### ISSUE THREAD

**Issue by martinssipenko** [hashicorp/vault#5838]
When configuring AWS Auth Method client it is possible to configure aws key and secret. Without setting these values Vault relies on the AWS SDK functionality to pick up values from environment, profile, instance metadata and so on (I use ec2 instance metadata).

So when Vault is running it uses EC2s instance role to make AWS API calls.

I'd like to be able to configure (using `/auth/aws/config/client`) a custom role that Vaults AWS client would assume. This would allow me to create a custom IAM role in AWS that would be assumed by Vault AWS Auth client.

The reasoning for such request is that I'm in multi-account AWS setup, and the instance from which I try to login (vault client) and vault server are located in different AWS accounts. When using AWS IAM Auth method (`vault login -method=aws header_value=vault.example.com role=dev-role-iam`) vault client generates request values and sends them to vault server. Vault server then makes a call to STS api to `GetCallerIndentity`. In multi account setup STS config is required to map account with STS role, that vault server will assume in order perform `GetRole` (required to resolve aws unique id). Right now Vault uses the EC2 instances profile role to make the STS `AssumeRole` operation.

Now given that this is multi-account setup, in order to allow Vault to assume role in different account I need to configure the to be assumed role to trust Vaults role (using trust policy), and given I want to explicitly define trusted role (without using wildcards, so that AWS maps to unique IDs) I would like to create a "service role" for Vault ahead of time, and manage instances roles separately.

I've tried using `/auth/aws/config/sts/:account_id` to achieve this, but with no luck.

Perhaps a completely different solution would be to configure AWS Auth client with AWS keypair and to implement the keypair rotation within Vault [(similar to how this is done in AWS Secrets backend)](https://www.vaultproject.io/api/secret/aws/index.html#rotate-root-iam-credentials), but for such feature a new issue should be created.

**Comment by joelthompson** [comment]
Hi @martinssipenko, this should already be supported. Can you post more details of your setup and exact error messages you're getting?

**Comment by martinssipenko** [comment]
@joelthompson What makes you think this should be support? Can you point out to any docs or parts of code that does this? I've looked through both and could not find anything.

Here is the command and error:
```vault write auth/aws/role/iam-role auth_type=iam bound_iam_principal_arn=arn:aws:iam::000000000000:role/aws-iam-role policies=dev
Error writing data to auth/aws/role/iam-role: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/aws/role/diam-role
Code: 400. Errors:

* unable to resolve ARN "arn:aws:iam::000000000000:role/aws-iam-role" to internal ID: AccessDenied: Access denied
    status code: 403, request id: 2b7d7207-11e8ef29-ae38-acf8-41a157095c9e
```

When I configured my ec2 instance profile role to allow assume the sts role configured using `/auth/aws/config/sts/:account_id` then it worked (also configured the trust policy on the other end).

I tested everything manually using aws cli and i'm sure my IAM setup was correct.

**Comment by joelthompson** [comment]
Hi @martinssipenko,

I'm a bit confused. At first you wrote:

> I've tried using `/auth/aws/config/sts/:account_id` to achieve this, but with no luck.

which is what should be supported. Then, you said:

> When I configured my ec2 instance profile role to allow assume the sts role configured using `/auth/aws/config/sts/:account_id` then it worked (also configured the trust policy on the other end).

That's exactly what I would expect and is the intended feature to solve your use case. Is there some reason that won't work for you?

**Comment by joelthompson** [comment]
So you want to chain roles? In other words, use the instance role to assume one role (let's call it the "intermediate role") and then use that to assume a different role (let's call it the "final role") in the target account?

Can you elaborate on your use case a bit more? E.g., why don't you just want Vault to directly assume the final role? And would you want Vault to assume this intermediate role for ALL operations or just for assuming the the final role for operations in that account? And I'm assuming you still want Vault to use its instance credentials to assume the intermediate role?

**Comment by martinssipenko** [comment]
Yes essentially I want to be able to chain roles.

Right now I am allowing ec2 instance role to assume the "intermediate role", which a you pointed out, does not add much benefit. However, if I pass aws keypair to Vault, and given I'm able to tell Vault to assume "intermediate role" I would not have to use ec2 instance role. In such case I would store AWS credentials in Vault which in turn means that if someone gains access to instance, he/she can't assume the role that is used for Vault (the "intermediate role").

I would expect that if such role is passed to Vault it is used for all aws operations that are performed by given auth backend.

Vault should keep its current logic for picking up aws credentials.

The use case is simple, I don't want to give my vault ec2 instance the ability to assume roles in other accounts directly. Additionally, if multiple AWS Auth backends are used on single Vault instance, then by using "intermediate roles" one could split one massive instance role into several smaller "intermediate" ones.

**Comment by martinssipenko** [comment]
I think same results could be achieved by using a dedicated IAM user and passing the users keypair to aws auth client config. And then allow that iam user to assume the configured sts role in another account (and trust the iam user from the other account).

While I think this would work I would be reluctant to implement such solution without the ability of Vault rotating the users keys by itself. I believe having long living keypairs lingering around is a bad approach.

**Comment by martinssipenko** [comment]
About keypairs - yes you can pass them today, I have not tried but I assume they work.

To be specific, Vault would use whatever credentials are supplied, not specifically instance credentials. By this I mean the aws creds could come from vault config, metadata, environment and so on.

Yes,  it would still allow people who can access the instance credentials to access the roles in the other AWS accounts.

I agree with what you say, and I think will shift to using IAM user and try to focus on keypair rotation rather than this feature. However, given the aws nature and that literally almost any tool allows you to assume different role I would suggest considering this feature.

**Comment by joelthompson** [comment]
I'm not trying to say this feature should or shouldn't be included. I'm just trying to understand why this feature is needed so it can be built to solve real needs without adding undue complexity, and I'm just not seeing the need for it above and beyond Vault already provides. "Literally almost any tool allows you to assume different role" doesn't mean much because the different tools have different use cases. I'm sympathetic to the general pattern, having used these features in many other tools, but these other tools often do cross-account access in a bit of a different way than Vault does it.
