### ISSUE TITLE
Add operationId to OpenAPI spec

### ISSUE THREAD

**Issue by carlodicelico** [hashicorp/vault#5842]
**Is your feature request related to a problem? Please describe.**
Current generated OpenAPI spec cannot be used with GCP Cloud Endpoints. `operationId` is not required by the OpenAPI specification, but _is_ [required by GCP's Cloud Endpoints](https://cloud.google.com/endpoints/docs/openapi/configure-endpoints), which uses this field internally. 

**Describe the solution you'd like**
Consider adding this field to the generated `openapi.json` output for v1.0.

**Describe alternatives you've considered**
Adding this field to the generated spec myself, which isn't terrible.

**Additional context**
This is specific (as far as I know) to GCP Cloud Endpoints and v1.0.x of Vault.

**Comment by jefferai** [comment]
Does it matter if the operation id changes from one generation of the spec to another? The spec doesn't say.

What is gcp cloud endpoints used for?

**Comment by carlodicelico** [comment]
@jefferai They're used as unique IDs internally by GCP, so I'm not sure, but I imagine they wouldn't necessarily need to be unique across deployments. Endpoints provides global load balancing, secure access, monitoring, etc. for OpenAPI 2.0 compliant APIs: https://cloud.google.com/endpoints/

FWIW, I was able to convert the OpenAPI 3.0 JSON produced by `gen_openapi.sh` to 2.0 with https://www.apimatic.io/transformer, which automatically created the `operationId` for each operation, although I still needed to do a _bit_ of fiddling to get it to work, it's not that bad. With that approach available, this might not be worth the trouble, particularly with higher priority issues open?

**Comment by jefferai** [comment]
I don't see why we shouldn't do it, and it's not difficult. I just want to make sure it's done right.

Seems like endpoints is gcp running nginx for you?

**Comment by carlodicelico** [comment]
This actually explains it better than I ever could: https://cloud.google.com/endpoints/docs/openapi/architecture-overview
