### ISSUE TITLE
Pagination Bug on Policies page

### ISSUE THREAD

**Issue by Garath620** [hashicorp/vault#5845]
**Describe the bug**
On 1.0.0-rc1 release, pagination of policies page in UI doesn't work correctly.

**To Reproduce**
1. Run `vault_1.0.0-rc1 server -dev`
2. Run `for i in {0..100}; do vault policy write ${i}-test-policy policy.hcl ; done`
3. See error
![pagination_bug](https://user-images.githubusercontent.com/28151179/49006020-6baa0f00-f168-11e8-8f8a-17e5f8744c15.png)

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.0-rc1
* Server Operating System/Architecture: debian 9

**Comment by briankassouf** [comment]
You mention "See error" but i don't see error text anywhere in the screenshot. Are you talking about the sort order there?

**Comment by v6** [comment]
// , @briankassouf , it would be easier to see the error if he had posted the non-error situation for comparison. 

But there shouldn't be 5 different **Next > ** buttons: 

![image](https://user-images.githubusercontent.com/5750764/49043874-11697800-f181-11e8-90df-29cbea79480a.png)


If I delete some of these policies, the Vault UI looks like this: 

![image](https://user-images.githubusercontent.com/5750764/49043955-4b3a7e80-f181-11e8-83cc-ccd228ee03da.png)

**Comment by Garath620** [comment]
Thank you @v6 for additional information
