### ISSUE TITLE
Add documentation for uninstalling vault

### ISSUE THREAD

**Issue by DreamFlasher** [hashicorp/vault#5848]
**Describe the bug**
Vault uses 1GB of RAM on my server this is why I want to uninstall/remove it. Unfortunately, there is no guide how to remove the software.

**To Reproduce**
1. Go to https://github.com/hashicorp/vault/

**Expected behavior**
See a documentation on how to uninstall vault

**Comment by v6** [comment]
// , I mean, look at the Installation Guide: https://www.vaultproject.io/docs/install/

Do you see anything complex in there to warrant uninstall documentation or a script?

**Comment by chrishoffman** [comment]
Installation is OS specific so there are no specific uninstallation docs.  The previous comment is correct that it is a single binary that just needs to be removed.  Are you sure you have the right `vault` project since it is a pretty generic name and an unused vault instance will not likely take up a GB of RAM.

**Comment by DreamFlasher** [comment]
You're right the installation is OS specific, sorry for not providing these information. I am on Ubuntu and I used this documentation for installation: https://www.digitalocean.com/community/tutorials/how-to-securely-manage-secrets-with-hashicorp-vault-on-ubuntu-16-04 -- I'll try to somehow undo the steps there.

**Comment by v6** [comment]
// , Sounds like something inherited. 

It's dangerous to go alone. 

Take this:

[`lsof`](https://en.wikipedia.org/wiki/Lsof)

Good luck.

**Comment by saddlebear** [comment]
I agree with dreamflasher, there needs to be a documented uninstall procedure (and/or script) to mirror the installation procedure.   If I run a -dev mode server, is everything cleaned up when it quits so I can safely install a production version on the same machine?   If I uninstall a production server I want all the keys and such removed as well.  Yes, yes, I know some of the installation is manually done but I still want a guide to make sure nothing is forgotten and a script (even if it currently would just delete the executable) to clean up whatever vault may have done.  If at a later date vault does to configuration on installation, the uninstall script needs to be there.

**Comment by advra** [comment]
At a minimum Id expect a section for uninstall to ensure no artifacts are left behind..
