### ISSUE TITLE
Possible conflict between gRPC and Vault API

### ISSUE THREAD

**Issue by bene-pn** [hashicorp/vault#5849]
I have a golang application using gRPC and Vault API. For other reasons, it ended up having in the vendor folder the golang.org/x/net/trace module. The same is true for Vault project and it leads to an application with two instances of net/trace module, which panics at its initialization: https://github.com/hashicorp/vault/blob/master/vendor/golang.org/x/net/trace/trace.go#L117

My dirty workaround for it was to remove manually net/trace module from Vault's project vendor folder but clearly, it is not a solution.

Any idea on how to solve this conflict?

Thanks in advance.

**Comment by briankassouf** [comment]
Sounds like you might be vendoring the trace package twice, you might want to make sure whatever dependency manager you are using is handling the imports properly.

Going to close as I don't think this is an issue with vault's code. We can reopen if deemed otherwise

**Comment by bene-pn** [comment]
I'm not arguing it is a vault's code problem per se but having Golang's Vault API module as part of the main Vault repo exposes developers to these kinds of problems, IMHO.

I'm not sure how to manage dependencies like that on a "global" fashion to make sure there would be only one instance of each module across all components of a Golang application with the current dependency tools feature set.
