### ISSUE TITLE
Support batch_input in the Transit HMAC endpoint

### ISSUE THREAD

**Issue by martinwaite** [hashicorp/vault#5850]
**Is your feature request related to a problem? Please describe.**

I have an application that needs to generate an HMAC for each line of large data files.  The large number of messages passed between the application and vault takes up a large proportion of the application's run time. In another application, I achieved a 20-fold improvement in performance by using the batch_input feature of the transit encrypt endpoint.  A batch_input feature for the transit HMAC should achieve a similar improvement.

**Describe the solution you'd like**

The Generate HMAC endpoint of the transit engine should support a batch_input parameter in the same way as the encrypt, decrypt and rewrap endpoints.

The batch_input parameter should take a list of input values in this format:

```
[
  { "input":  "adba32==" },
  { "input":  "dGVzdDE="},
  ...
]
```

Response:
```
[
  { "hmac":  "dGhlIHF1aWNrIGJyb3duIGZveAo=" },
  { "hmac":  "IFIExBWlkgRE9HJ1MgQkFDSw=="},
]
```

**Describe alternatives you've considered**
A workaround is to perform the HMAC generation within my application.  The key could be stored in Vault or stored locally and encrypted with vault, and then used to generate HMAC values.  However, I would prefer to delegate all handling of secrets to vault.

Another possible performance improvement could come from re-using SSL sessions. 

**Explain any additional use-cases**

N/A

**Additional context**

I have looked at how batch_input has been implemented in transit encrypt and I am confident that I can use a similar approach for the HMAC endpoint.

**Comment by kalafut** [comment]
Closed by https://github.com/hashicorp/vault/pull/5875
