### ISSUE TITLE
vault list /identity/group/{id,name} returns 404 if no groups exist

### ISSUE THREAD

**Issue by Yajo** [hashicorp/vault#5861]
**Describe the bug**
If no groups exist, instead of returning an empty list, the API returns a `404` error.

**To Reproduce**
1. Run `vault list /identity/group/id` or `vault list /identity/group/name` when no groups exist.

**Expected behavior**
It should return `200` with an empty list.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.11.5
* Vault CLI Version (retrieve with `vault version`): Vault v0.11.5 ('a59ffa4a0f09bbf198241fe6793a96722789b639')
* Server Operating System/Architecture: Docker image.

Vault server configuration file(s):

```yaml
  backend:
    file:
      path: /vault/file
  ui: true
```

**Additional context:**
The docs say 404 is not an expected return:

- https://www.vaultproject.io/api/secret/identity/group.html#list-groups-by-id
- https://www.vaultproject.io/api/secret/identity/group.html#list-groups-by-name

**Comment by ncabatoff** [comment]
This appears to be a documentation bug, based on #1365.

**Comment by jefferai** [comment]
We're thinking over lists and whether they generally be 404 or 204. I'm closing this since we're thinking about it for more than just this specific instance.
