### ISSUE TITLE
Allow users to list the key names of KV 'files', not just KV 'folders'

### ISSUE THREAD

**Issue by nathkn** [hashicorp/vault#5873]
**Is your feature request related to a problem? Please describe.**
[Currently it is only possible to list key names of KV 'folders', not the key names of KV 'files':](https://www.vaultproject.io/api/secret/kv/kv-v2.html#list-secrets)
```
$ vault kv put secret/my-app foo=bar
Key              Value
---              -----
created_time     2018-11-29T15:50:44.6244313Z
deletion_time    n/a
destroyed        false
version          1

$ vault kv list secret/my-app
No value found at secret/metadata/my-app
```

For security reasons, I would like to allow developers/admins to be able to create and update KV secrets, however not have the ability to read the actual secrets values. In order for them to know the correct format of the secret key/value pair, they need to know what keys they should update or parse from the response.

For example, did the developer before me use 

`vault kv put secret/my-app username=dan` 

or 

`vault kv put secret/my-app user=dan`?

**Describe the solution you'd like**
I would like to be able to list the keys of a KV value like so:
```
$ vault kv put secret/my-app foo=bar
Key              Value
---              -----
created_time     2018-11-29T15:50:44.6244313Z
deletion_time    n/a
destroyed        false
version          1

$ vault kv list secret/my-app
Keys
----
foo
```
**Describe alternatives you've considered**
Our current workarounds are to require developers to either:
1) continually look to source code to see what the schema of the KV secrets are based on how they are being accessed in production
2) maintain up-to-date documentation/metadata about what the keys are, and hope they don't stray or make typos
3) have read access to secrets

**Explain any additional use-cases**
We would also like this functionality in the UI, where I can easily look up what the keys to a secret value are, without being able to read the values in the browser.

**Comment by chrishoffman** [comment]
It is not entirely accurate to say only the folders are available in LIST.  What is shown is all available folders and keys with each key having a data payload of key value pairs.  Considering that everything in the data payload is considered secret, we would likely never provide a way to inspect it without full access to the data.  

I think you can easily model what you are saying by breaking up your "folders" into separate keys.  Using your example, you could do something like this:

```
$ vault kv put secret/my-app/username value=dan
$ vault kv put secret/my-app/password value=supersecretpassword
```

**Comment by nathkn** [comment]
That's a pretty disappointing response. There is no reason why the keys of the value pairs ought to be considered solely part of the data payload, and couldn't be part of the metadata payload, since the keys shouldn't be considered secret in the first place.

The workaround you propose still means:
1 - You can't easily update values via the UI, because the only way you can hit the 'Edit Secret' switch is if you can read the secret.
2 - Assumes no one makes a typo on the command line, since there's no way to debug/inspect the key after you set a value if you don't have read access
3 - is unenforcable, since there's no policy that you can set that requires the key of a secret to be 'value' - meaning there will be inevitable configuration drift
4 - arbritarily means you can't use multiple key value pairs

All of which means that teams are more likely to forgo the least-privilege model and go for read access they don't really need.
