### ISSUE TITLE
proposed secret backend:  generic-api

### ISSUE THREAD

**Issue by ProbablyRusty** [hashicorp/vault#588]
I am an envisioning the possibility of a new generic API secret backend which could potentially allow many custom external integrations for Vault to be implemented without the need for a specialized secret backend to be written into Vault for each one of them.

The backend config could potentially support the following config values:

`create_endpoint`
`revoke_endpoint`
`endpoint_token`

For example,

```
vault write generic_api/config/create_endpoint value="https://my.great.api/v1/create"
vault write generic_api/config/revoke_endpoint value="https://my.great.api/v1/revoke"
vault write generic_api/config/endpoint_token value="apisecret"
```

A Vault user would read from the example path `generic_api/foo` as follows:

```
vault write generic_api/foo color=blue flavor=vanilla
```

Vault would subsequently call an external API, ie:

```
curl -H "Auth: apisecret" -X PUT '{ "foo": { "color": "blue", "flavor": "vanilla" } }' 'https://my.great.api/v1/create'
```

...perhaps receiving this response back from the API:

```
{ "username": "foo", "password": "12345", "other_secret" : "xyz" }
```

...which Vault would return to the user as follows:

```
Key             Value
lease_id        generic_api/foo/f65cabb6-6434-8fc1-560b-45d5c683b0c2
lease_duration  1200
lease_renewable false
username        foo
password        12345
other_secret    xyz
```

I suppose a future plugin architecture for Vault secret backends would cover some of the use cases for the above, though even then, I think a backend like this could be extremely flexible and useful, and additionally, might be able to be fleshed out sooner than any eventual plugin support.

**Comment by jefferai** [comment]
I think this is a pretty interesting idea, although probably a lot of thought would have to go into the details. For instance, probably only JSON APIs could be supported, there would be a lot of questions around things like error handling, redirect handling, and so on.

Thanks for the suggestion!

**Comment by jefferai** [comment]
We have no current plans for a built-in backend to do this, but with our plugin capabilities this can now be easily created by an interested third-party!
