### ISSUE TITLE
Azure secret backend gives InvalidApiVersionParameter error

### ISSUE THREAD

**Issue by ambakshi** [hashicorp/vault#5883]
**Describe the bug**
Attempting to fetch credentials from configured role azure/creds/developer, gives this error:

Error reading azure/creds/developer: Error making API request.

URL: GET https://vault.service.consul:8200/v1/azure/creds/developer
Code: 500. Errors:

* 1 error occurred:
	* error while assigning roles: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2018-01-01-preview' is invalid. The supported versions are '2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."

**To Reproduce**
1. Mount azure secrets engine and wrte azure/config with SP role having permissions as described on this page: https://www.vaultproject.io/docs/secrets/azure/index.html#authentication
2. Configure a developer role giving Contributor role to your subscription 

vault write azure/roles/developer ttl=3600 max_ttl=24h azure_roles=-<<EOF
[
  {
    "role_id": "/subscriptions/{subsId}/providers/Microsoft.Authorization/roleDefinitions/xxx",
    "scope": "/subscriptions/{subsId}/resourceGroups"
  }
]
EOF

3. Read some generated creds back 

vault read azure/creds/developer
Error reading azure/creds/developer: Error making API request.

URL: GET https://vault.service.consul:8200/v1/azure/creds/developer
Code: 500. Errors:

* 1 error occurred:
	* error while assigning roles: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2018-01-01-preview' is invalid. The supported versions are '2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."

 
**Expected behavior**
Expected to get credentials back
**Environment:**
* Vault Server Version (retrieve with `vault status`):
0.11.5
* Vault CLI Version (retrieve with `vault version`):
0.11.5
* Server Operating System/Architecture:
linux/amd64
Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```
ui = true
default_lease_ttl = "720h"
storage "consul" {
    address = "127.0.0.1:8500"
    path    = "vaultx/"
}
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 0
  tls_cert_file = "/etc/vault.d/vault.crt"
  tls_key_file = "/etc/vault.d/vault.key"
}

api_addr = "https://10.10.10.10:8200"
cluster_addr = "https://10.10.10.10:8201"

**Additional context**

**Comment by kalafut** [comment]
Thanks for reporting this. What Azure region are you running in?

**Comment by ambakshi** [comment]
I'm trying to generate temporary access credentials. Are those tied to a region? The Vault server and client are not running on Azure.

**Comment by ambakshi** [comment]
Hi, thanks for the quick response. Indeed, the issue was the scope. Once I removed the resourceGroups or added a specific resourceGroup, it worked. Thanks!
