### ISSUE TITLE
Web UI: revoke is shown in dropdown even if certificate is already revoked (low prio)

### ISSUE THREAD

**Issue by tomschlenkhoff** [hashicorp/vault#5885]
**Describe the bug**
When using the web UI one can access the "revoke" menu even when the certificate is already revoked.

**Expected behavior**
Do not show "revoke" in dropdown when cert is already revoked.

**Environment:**
1.0.0 Beta 2 on Linux

**Additional context**
![screen shot 2018-12-03 at 09 48 28](https://user-images.githubusercontent.com/941842/49363314-a02a4780-f6e1-11e8-85ac-842b298e50fd.png)
![screen shot 2018-12-03 at 09 52 39](https://user-images.githubusercontent.com/941842/49363326-a7515580-f6e1-11e8-8340-8e56ef62508b.png)

**Comment by Monkeychip** [comment]
@tomschlenkhoff apologies for the very late reply to this issue. The PKI UI has been completely redone and this problem solved in [1.13.0](https://github.com/hashicorp/vault/releases/tag/v1.13.0-rc1). (In 1.13.0 it was an option to use the new PKI engine so you wont see it in the changelog, by 1.14.0 the old PKI engine was replaced completely).
