### ISSUE TITLE
deb/rpm packages

### ISSUE THREAD

**Issue by benmccann** [hashicorp/vault#589]
I wanted to put in a feature request for a deb package, which would slightly simplify our production deployment process since everything we deploy right now is packaged that way.

I see you're using Bintray for hosting right now. It can host both deb and rpm packages.
http://blog.bintray.com/2014/12/16/hosting-debian-packages-on-bintray-rocks/

**Comment by BRMatt** [comment]
In the absence of an official apt repo [we configured our ci server to build a package using fpm and publish it to our internal repository](http://cl.ly/3T082T2u3X1z). It's made it pretty straightforward for us to run patched versions of vault without waiting for an upstream release. You might find it useful.

**Comment by indykish** [comment]
@BRMatt   What is the CI server you use to build your packages ? 

We have to solve the same problem to kick off builds out of our fpmrecipes stored in https://github.com/megamsys/packager

**Comment by timp87** [comment]
Just in case, I've created rpmbuild for vault
https://github.com/timp87/vault-rpm

**Comment by jefferai** [comment]
Many distros now have Vault packaged; if desired for any particular distro, please ask them!
