### ISSUE TITLE
Transit support for format preserving encryption / decryption

### ISSUE THREAD

**Issue by martinwaite** [hashicorp/vault#5894]
**Is your feature request related to a problem? Please describe.**

NIST has published recommendations for format preserving encryption:
https://nvlpubs.nist.gov/nistpubs/specialpublications/nist.sp.800-38g.pdf

I need to implement this in my application, but given the number of AES encryption operations involved in this mode, it is probably going to rule out using the Vault transit engine to perform the encryption.

A better solution would be to implement FFX encryption modes within Vault. 

**Describe the solution you'd like**

Vault would provide an FF1 encryption mode for the Transit engine.  

The code on the client-side would convert text into a sequence of 16-bit uint indices marking points in an arbitrary alphabet of up to 65536 characters. The sequence of indices would then be mime-encoded for passing to vault for encryption.  Vault would return a mime-encoded string that decodes to the sequence of indices that the client would then use to look-up character entries from the same alphabet.
Decryption follows a similar process, but calls a decrypt end-point in vault.

The api would need to support 4 parameters:

1. the "tweak" (aka the context in other vault endpoints)
2. the mime-encoded sequence of 16-bit uints
3. the radix of the alphabet (ie. how many entries in the alphabet)
4. the key to be used for encryption / decryption

Note that Vault does not need to see the actual alphabet.

**Describe alternatives you've considered**

I am probably going to implement this locally but using a key held in Vault.  We use Ruby, so possibly using something like the ffxcodec gem to perform the encryption.

**Explain any additional use-cases**

The NIST paper outlines motivations including integrating encryption with legacy systems that have strict input format requirements.  Typically these are database applications that place strict constraints on the formats of fields such as credit-card numbers.

**Additional context**

The NIST approved algorithm is covered by a patent issued to Voltage Inc.  Voltage was acquired by HP Enterprise in 2014, and then sold to MicroFocus.  Voltage posted an assurance with NIST that licences to use the algorithm would be granted on application for a "reasonable" fee.  Perhaps this rules out an open-source implementation in Vault.

There is a Go implementation at https://github.com/capitalone/fpe .

**Comment by vishalnayak** [comment]
See https://www.vaultproject.io/docs/secrets/transform
