### ISSUE TITLE
Running vault in dev mode does not work

### ISSUE THREAD

**Issue by myspotontheweb** [hashicorp/vault#59]
Following the [tutorial][1] and fell at the first fence :-(

    $ uname -a
    Linux myhost 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
    
    $ vault version
    Vault v0.1.0-dev (e9b3ad035308f73889dca383c8c423bb5939c4fc+CHANGES)

    $ vault server -dev
    Error initializing core: failed to lock memory: cannot allocate memory

[1]: https://vaultproject.io/intro/getting-started/dev-server.html

**Comment by mitchellh** [comment]
This means it couldn't execute the `mlock` syscall. We don't have a flag to disable this exposed yet (though it is internally). We'll add a flag, but Vault is much more secure if you can figure out why that syscall doesn't work!

**Comment by bracki** [comment]
I have a similar problem on OS X 10.10.3.
```
➜ ./vault server -dev
Error initializing dev mode: Error: exit status 127

sh: vault: command not found```

**Comment by mitchellh** [comment]
@bracki That is a different issue... can you open that separately?

**Comment by bracki** [comment]
@mitchellh Sure, https://github.com/hashicorp/vault/issues/60.

**Comment by myspotontheweb** [comment]
Could this be an inadequate sizing of the "max locked memory" parameter?

    $ ulimit -l
    64

**Comment by bbirkinbine** [comment]
When building, I got the "failed to lock memory: cannot allocate memory" message as well.

I bumped the memlock value up (ie. on CentOS 7, this is in /etc/security/limits.conf  or can place new value for memlock in /etc/security/limits.d/ in a new file.)

Verify new value by checking ulimit -l value

**Comment by ShadowApex** [comment]
I also got this same error on Ubuntu 15.04 Vivid x84_64. Running as root appears to work, however.

**Comment by mitchellh** [comment]
Added a flag to master `disable_mlock` (in the config file) to disable this. And dev mode no longer does it at all. I'm going to improve the error message on this more and then close this out.

**Comment by dontrebootme** [comment]
I got this when trying things in a docker container as well. Per @mitchellh's mention of mlock, I passed --cap-add IPC_LOCK to the docker run and got the server started.

**Comment by mitchellh** [comment]
Fixed
