### ISSUE TITLE
1.0.0 Web UI cli fullscreen not working

### ISSUE THREAD

**Issue by yura-shutkin** [hashicorp/vault#5901]
**Describe the bug**
Web UI cli full screen not working. Cli disapears after command fullscreen. Tested on both Chrome Version 70.0.3538.110 (Official Build) (64-bit) and FireFox 63.0.3 (64-bit)

**To Reproduce**
1. Login to vault
2. Open web UI cli
3. write `fullscreen`
3. See error

**Expected behavior**
Web UI cli shoud fill whole web page.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.0.0
Cluster Name    vault-cluster-f74a4390
Cluster ID      c34424f6-72eb-14d2-2c52-b4071cb65ba2
HA Enabled      true
HA Cluster      https://vault-client-1:8201
HA Mode         active
```
* Vault CLI Version (retrieve with `vault version`):
```
Vault v1.0.0 ('c19cef14891751a23eaa9b41fd456d1f99e7e856')
```
* Server Operating System/Architecture:
```
ubuntu 16.04 x64
```

Vault server configuration file(s):

```hcl
storage "consul" {
  address = "127.0.0.1:8500"
  path = "vault/"
  scheme = "http"
  token = "d565f7b1-a1ac-f91a-eaa5-820ca3f03124"
  service_tags = "vault-dev"
  service_address = "vault-client-1"
}

listener "tcp" {
  address     = "192.168.4.6:8200"
  tls_disable = "true"
  cluster_address = "192.168.4.6:8201"
  proxy_protocol_behavior = "allow_authorized"
  proxy_protocol_authorized_addrs = "192.168.4.5"
  x_forwarded_for_authorized_addrs = "192.168.4.5/32"
  x_forwarded_for_reject_not_authorized = "true"
  x_forwarded_for_reject_not_present = "true"
}

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = "true"
}

telemetry {
  statsite_address = "statsd-exporter:9125"
  disable_hostname = true
}

ui = "true"

api_addr = "http://vault-client-1:8200"
cluster_addr = "https://vault-client-1:8201"
```

**Additional context**
On local single node with -dev at docker all works fine, but ha with consul storage have this issue.
You can see docker-compose file at https://github.com/yura-shutkin/docker-lab/tree/master/vault-cluster

**Comment by yura-shutkin** [comment]
* On local dev instance at docker all works fine, but ha with consul storage have this issue.  Single node not ha. Just docker run -d --name=vault-dev vault:1.0.0

**Comment by meirish** [comment]
Hi - thanks for filling an issue!

What error are you seeing? On https://demo.vaultproject.io I do see that there's a rendering issue - the whole cli moves off the top of the viewport - is that what you're seeing? I'm working to get that fixed, but I want to make sure we get everything and I'm not seeing other errors. Could you screenshot them or paste the text of errors you're seeing?

Thanks!

**Comment by yura-shutkin** [comment]
![screenshot from 2018-12-06 03-46-58](https://user-images.githubusercontent.com/8489762/49549211-e19d3b80-f909-11e8-9864-f96ba7d52feb.png)
Nothing at console log and no failed queries at network tab

Yes, cli moves off the top

**Comment by meirish** [comment]
@yura-shutkin great - the linked PR fixes this then. Sorry we missed that!
