### ISSUE TITLE
Blog link to upgrade to 1.0 is broken

### ISSUE THREAD

**Issue by caipivara** [hashicorp/vault#5902]
In https://www.hashicorp.com/blog/vault-1-0 you show:
 
![image](https://user-images.githubusercontent.com/76348/49522181-0f847080-f875-11e8-8624-c6be16039595.png)

It points to https://www.vaultproject.io/guides/upgrading/upgrade-to-1.0.html

Which says error 404.

**Comment by chrishoffman** [comment]
Thanks for the report.  I am working on a fix now.

**Comment by chrishoffman** [comment]
This is now fixed.  Thanks!
