### ISSUE TITLE
Influxdb database secret plugin missing

### ISSUE THREAD

**Issue by gitirabassi** [hashicorp/vault#5912]
**Is your feature request related to a problem? Please describe.**
I would like to manage influxdb servers authorization with vault like I do with mysql/cassandra/ecc

**Describe the solution you'd like**
I already have a working solution for this, I wanted to ask if it would make sense to add to the built-in registry of available database plugin when shipping vault.
In case you agree I can send a PR in a couple of days

**Comment by chrishoffman** [comment]
A PR would be great!
