### ISSUE TITLE
ACL policy deletion from web UI fails if it contains dots

### ISSUE THREAD

**Issue by diegosainz** [hashicorp/vault#5915]
**Describe the bug**
Cannot delete policies with dots (".") in their names from the web interface (tested in latest Chrome and Firefox versions)

**To Reproduce**
1. Create a policy called "some.policy" with any content
2. Try to delete it (from the web UI)
3. See error in console:
```
vendor-9e6bb7bde315fb2e3f4c03b643b80ad9.js:3086 Uncaught r {stack: "Error: Property set failed: object in path "should…ndor-9e6bb7bde315fb2e3f4c03b643b80ad9.js:3734:15)", description: undefined, fileName: undefined, lineNumber: undefined, message: "Property set failed: object in path "shouldDelete-some" could not be found.", …}
```

**Expected behavior**
A confirmation dialog should appear asking for the policy deletion

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.0
* Vault CLI Version (retrieve with `vault version`): 1.0.0
* Server Operating System/Architecture: Ubuntu 18.04

**Comment by meirish** [comment]
As a work around, you should still be able to delete the policy from the edit page (or the web CLI) until we land a fix for this.

**Comment by diegosainz** [comment]
Thank you, @meirish - yes, we were deleting those keys from the cli without any problems.

**Comment by meirish** [comment]
@diegosainz great! l just wanted to clarify that if you click through to policy, then click edit - there is a delete button in the lower right - this should still work. The bug you posted about here is related to the hiding and showing of the context menu, not the actual deletion.

**Comment by diegosainz** [comment]
Oh! OK! I misread your comment the first time - it is useful to know. Thank you!
