### ISSUE TITLE
Concatenate tls and CA

### ISSUE THREAD

**Issue by satheeshCharles** [hashicorp/vault#5917]
I refer vault official doc https://www.vaultproject.io/docs/configuration/listener/tcp.html#tls_cert_file 

`tls_cert_file (string: <required-if-enabled>, reloads-on-SIGHUP) – Specifies the path to the certificate for TLS. To configure the listener to use a CA certificate, concatenate the primary certificate and the CA certificate together. The primary certificate should appear first in the combined file.`

in the vault configuration, if I start vault with the only tls_cert, vault started successfully, however everytime I have to add the -ca-cert=<certFile> in the command line to authorise it.  So, I try add the CA cert in the configuration file as mentioned by Vault I'm concatenating the certs, I open the editor and copied the primary cert in the first then pasted the CA. When I add the new file in the config I don't see the vault working as expected. I mean still, it demands me to add -ca-cert=<certFile> for every action. Do you have any idea something went wrong terrible?

**Comment by 2994186010** [comment]
@satheeshCharles , do you solve the problem?

**Comment by catsby** [comment]
Hello - we haven't heard anything for a few weeks, so I'm going to close this for now. I realize this issue went unaddressed for quite some time, and for that I sincerely apologize. If you have more information for us to help reproduce this, please let us know! For example, if you had steps that reproduce this reliably on the current version of vault (1.3.1) , we can take another look. 

For future questions or discussion such as this, please checkout https://discuss.hashicorp.com/c/vault

Thanks!
