### ISSUE TITLE
High CPU usage spikes killing vault: Vault on Kubernetes with Cassandra credentials

### ISSUE THREAD

**Issue by chrisfelix82** [hashicorp/vault#5921]
**Describe the bug**
We noticed that Vault was throwing many errors related to ` [ERROR] expiration: failed to revoke lease: lease_id=database/creds/...` with our Cassandra backend.  We tracked this down to missing roles, and then added those missing roles back so that the creds could be revoked properly.  We also needed to update the revocation_statements to be ["DROP ROLE '{{username}} IF EXISTS;"].  This has calmed the logs, but we are still getting periodic CPU spikes that bring down Vault.  

**To Reproduce**
1. Run vault on Kubernetes with consul in cluster as the backend. 
2. Enable cassandra database secrets backend https://www.vaultproject.io/docs/secrets/databases/cassandra.html
3. Runs for about 4 hours OK and then CPU spikes to double and Vault crashes beyond its resource limit on k8s.  What should be the limit if we are generating alot of roles and credentials?  100's of credentials due to creating credentials for a keyspace per git branch deploy.

**Expected behavior**
Vault can handle many credentials being created and revoked at the same time.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.11.5
* Vault CLI Version (retrieve with `vault version`): Using the REST API.
* Server Operating System/Architecture: k8s

Vault server configuration file(s):

```hcl
backend "consul" {
  address       = "%%CONSUL_SERVICE_HOST%%"
  token         = "%%CONSUL_SERVICE_TOKEN%%"
  scheme        = "https"
  tls_ca_file   = "/etc/tls/ca.crt"
  tls_cert_file = "/etc/tls/consul.crt"
  tls_key_file  = "/etc/tls/consul.key"
}

listener "tcp" {
  address       = "%%VAULT_SERVICE_HOST%%"
  tls_key_file  = "/etc/vault/ssl/vault.key"
  tls_cert_file = "/etc/vault/ssl/vault.crt"
}

disable_mlock = true

ui = true

```

**Additional context**

**Comment by chrishoffman** [comment]
It seems that you may just be undersized for your workload.  Vault can handle very large workloads and I'm not seeing anything here that tells me there is a problem with Vault since Kubernetes is killing it due to it's resource limits.
