### ISSUE TITLE
403 with okta auth during MFA token verification

### ISSUE THREAD

**Issue by lancehudson** [hashicorp/vault#5922]
**Describe the bug**
I've been testing using a read only administrative api token to pull group memberships. Vault configures the Okta client with an api token when it creates it. The client sends the api token (authorization header) with every request.

If you use a read only admin api token to call

>POST https://dev-bbb-admin.oktapreview.com/api/v1/authn/factors/xxx/verify
>Authorization: SSWS xxxxyyyyzzzz
>
>{
>"stateToken": "XXXXYYYYZZZZ"
>}

it fails with

>HTTP 403
>{
>"errorCode": "E0000006",
>"errorSummary": "You do not have permission to perform the requested action",
>"errorLink": "E0000006",
>"errorId": "XXXXXXXX",
>"errorCauses": []
>}

but it succeeds if the authorization header is not sent.

I have filed a bug in the underlying provider to track if this is addressed on their end. https://github.com/chrismalek/oktasdk-go/issues/7

Otherwise I have asked Okta to treat this as s bug. If neither of those gain any traction can Vault make it possible to use a read only api token?

**To Reproduce**
1. Run setup an okta backend with a read only admin token. Setup a user with Okta push setup.
2. Login via the ui with Okta auth
3. See error

> Authentication failed: Okta auth failed: HTTP Method: POST - URL: https://XXX.okta.com/api/v1/authn/factors/YYY/verify: - HTTP Status Code: 403, OKTA Error Code: E0000006, OKTA Error Summary: You do not have permission to perform the requested action, OKTA Error Causes: []

**Expected behavior**
Successful Login

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.0
* Vault CLI Version (retrieve with `vault version`): 0.11.5
* Server Operating System/Architecture: 1.0.0 docker hub image

Vault server configuration file(s):

```hcl
resource "vault_okta_auth_backend" "okta_dev" {
  path = "okta-dev"
  description = "Okta auth with Dev"
  organization = "dev-XXXX"
  base_url = "oktapreview.com"
  token = "YYYYY"
}
```

**Comment by nmavor** [comment]
i just hit the same issues

**Comment by lancehudson** [comment]
After talking to Okta, this is expected behavior on their end. A read only administrator token does not have the ability to authenticate users.

It works with a Help Desk Administrator token. My organization is unwilling to grant the additional privileges without creating compensating controls. So that leaves me either managing group memberships myself inside vault, or not using Okta authentication.

**Comment by michelvocks** [comment]
Apparently, this issue is not related to Vault. I will close this for now but feel free to open a new issue if this is still a problem.
