### ISSUE TITLE
Vault 1.0.0 doesn't seem to handle GCP GCE auth well

### ISSUE THREAD

**Issue by MartinLeedotOrg** [hashicorp/vault#5927]
**Describe the bug**
After upgrading Vault from 0.11.5, GCE auth failed, with the following error returned from Vault:
```
{"errors":["could not find service account \"[redacted]\" in project \"\": googleapi: Error 400: The name should be in the form \"projects/{project_id}/serviceAccounts/{account}\"., badRequest"]}
```

After rolling back to 0.11.5, the `project_id` Key of my roles at /auth/gcp/role/foo was missing. I wrote them again and this resolved that problem.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
Vault 1.0.0

**Comment by jefferai** [comment]
This plugin is actually maintained by Google; please file an issue at https://github.com/hashicorp/vault-plugin-auth-gcp

Thanks!
