### ISSUE TITLE
Configurable Subject Alternative Names

### ISSUE THREAD

**Issue by theonewolf** [hashicorp/vault#593]
I'd like to comply with x509 specification better by allowing other types of Subject Alternative Name.

Currently the design in Vault is hard-coded to only let in DNS names *I think*.

I'm using the subject name as a form of node identifier (could be DNS based), and the alternative names as listing service and group identifiers (not necessarily each one having its own DNS name).

In my actual use case, the common name is a UUID as are all the alternative names.  In this manner I can use these PKI certificates to identify arbitrary entities not necessarily having DNS names labeling them.  For example, many processes on a host can be identified with a unique certificate without requiring every process to also have a unique DNS record.

**Comment by jefferai** [comment]
In 0.3 there is a role flag to control whether hostnames are required, so you can easily control this behavior. This is true for CN, and should be true for SANs, although I will check to make sure that is true (and fix if not).

**Comment by jefferai** [comment]
BTW this is already in master if you want to give it a try.

**Comment by theonewolf** [comment]
Just need an upgrade.  Best kind of issue :smile:

**Comment by jefferai** [comment]
Just looked at the code -- you will want to turn off enforcement of hostnames and turn on allowing any name. Most of the code is geared towards flexible domain/subdomain handling, so if you're other things, you'll simply want to allow any name to be accepted. But, note that enforcement of hostnames is separate from allowing any name (so you can do "allow any hostnames"), hence needing to turn that off as well.

**Comment by theonewolf** [comment]
Yeah, that's fine.  I'm just happy to have a centralized, PKI tool that I enjoy working with.

**Comment by jefferai** [comment]
Glad you're enjoying it. There are some significant enhancements for that
backend on the roadmap, so I think you'll be even happier :-)
