### ISSUE TITLE
Github authentication method not working in UI

### ISSUE THREAD

**Issue by rarguelloF** [hashicorp/vault#5932]
**Describe the bug**
The Github authentication method in the UI always shows the following error:

```
Error
Authentication failed: error performing token check: the Authorization header provided is wrongly formatted. Please use "Bearer <token>"
```

**To Reproduce**
Try to login in the UI using a valid or not valid token with the Github Auth method.

**Expected behavior**
The Github auth method should work. 

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.0

**Comment by meirish** [comment]
Hi @rarguelloF - I was unable to reproduce this error (and could successfully log in). Could you provide all of the commands you ran to set up the config for the GH auth method as well?

thanks!

**Comment by rarguelloF** [comment]
Hello @meirish, thanks for your help!

First I would like to mention that we actually started facing this error when upgrading from version `0.10.3` to version `0.11.5`.

When calling `/v1/sys/auth`, the config for the `github` auth method is the following:

```
"github/": {
      "accessor": "auth_github_0e75d201",
      "config": {
        "default_lease_ttl": 0,
        "force_no_cache": false,
        "max_lease_ttl": 0,
        "token_type": "default"
      },
      "description": "",
      "local": false,
      "options": null,
      "seal_wrap": false,
      "type": "github"
    },
```

The CLI still works fine (`vault login -method=github`), only thing not working is the UI, and only the github auth method (token auth method in the UI works).

If I open the JS console in the UI, the api call which is failing is the following:

```
GET /v1/sys/internal/ui/mounts 400

{"errors":["error performing token check: the Authorization header provided is wrongly formatted. Please use \"Bearer \u003ctoken\u003e\""]}
```

**Comment by rarguelloF** [comment]
Hello again @meirish

I just discovered the issue, we are using [oauth2_proxy](https://github.com/bitly/oauth2_proxy) in front of the vault UI, and seems like oauth2_proxy is injecting an Authorization header to the upstream request (vault in this case), and now Vault is complaining about this.

Will try to look into `oauth2_proxy` config and see if I can remove that header from the upstream request.
