### ISSUE TITLE
Better Dynamic Database Allowed Role Error Message

### ISSUE THREAD

**Issue by sidewinder12s** [hashicorp/vault#5939]
**Describe the bug**
If a Dynamic Database Role is not allowed on a database connection, there is no useful error message or indication of the issue in the Vault server logs, audit logs, or to the end user; Just a permission denied error.

**To Reproduce**
1. Create a database mount
2. Create a database connection restricted by role
3. Create a database role does not match one of the allowed roles
4. Try to use that role.

**Expected behavior**
An error message to the requesting user or within Vault's logging that the role either isn't allowed on that database or the database configuration doesn't allow that role.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.2
* Vault CLI Version (retrieve with `vault version`): 1.0
* Server Operating System/Architecture: Docker/Ubuntu

I ran into this multiple times in our production environment that matches the versions above but I believe I also ran into it while testing locally with 1.0.

**Comment by tyrannosaurus-becks** [comment]
Hi @sidewinder12s , thanks for reporting this! Is this a valid reproduction of the issue?

1. Create a database mount
```
$ vault secrets enable database
```
2. Create a database connection restricted by role
```
$ vault write database/config/my-database \
    plugin_name="postgresql-database-plugin" \
    connection_url="postgresql://{{username}}:{{password}}@localhost:5432/" \
    allowed_roles="foo" \
    username="root" \
    password="root"
```
3. Create a database role does not match one of the allowed roles
```
$ vault write database/roles/my-role \
    db_name=my-postgresql-database \
    creation_statements="CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}'; \
        GRANT SELECT ON ALL TABLES IN SCHEMA public TO \"{{name}}\";" \
    default_ttl="1h" \
    max_ttl="24h"
```
4. Try to use that role.
```
$ vault read database/creds/my-role
Error reading database/creds/my-role: Error making API request.

URL: GET http://127.0.0.1:8200/v1/database/creds/my-role
Code: 500. Errors:

* 1 error occurred:
	* failed to find entry for connection with name: "my-postgresql-database"
```

**Comment by tyrannosaurus-becks** [comment]
I haven't been able to reproduce this locally yet, but I wanted to note that I bet this is where the error is coming from: https://github.com/hashicorp/vault/blob/master/builtin/logical/database/path_creds_create.go#L51-L55

**Comment by sidewinder12s** [comment]
@tyrannosaurus-becks I'll see if I can get some time to fully reproduce locally again. We had run into a couple issues with the Dynamic Database engine when I submitted this so some things might have gotten smashed together in my head.

Can you try changing your role configuration from using a db_name of `my-postgresql-database` (which doesn't exist) to `my-database` (which should exist according to your step 2)?

I think the issue was specifically when you create a DB connection config, don't whitelist `my-role` for said database and then configure `my-role` against the database, which just throws a permission denied rather than something that tells you it might be misconfigured.

**Comment by tyrannosaurus-becks** [comment]
@sidewinder12s yep, that made it so I could reproduce it! Fix PR'd above.

**Comment by excalq** [comment]
Unfortunately the role's parameter `db_name` is a bit misleading. The value needs to match a `database/config/` entry, not an actual database name per se. The GRANT statement itself is where the database name is relevant, the db_name is just a reference to the config name, which may or may not match the database name. (In my case, the configs have other data such as environment prefixing the DB name.)
