### ISSUE TITLE
Vault Crash / Database Lags Caused By Too Many Leases

### ISSUE THREAD

**Issue by jmleapline** [hashicorp/vault#594]
We are experimenting with Vault and using this to store encryption keys within a MySQL backend. We have non-expiring tokens. The problem comes that every time the Vault service is queried for the key, it generates two new rows in the database.

sys/expire/id/secret/...
sys/expire/token/…

The secret lease is set to default at the 30 days expiration, and I cannot see what the token expiration is but I'm assuming that is the same case. Because of how active our service is, it is generating millions of hits against the database and our backend is getting filled up. This then causes significant delays in querying the backend, and showing the following error message.

```
2015/09/06 13:18:06 http: panic serving 127.0.0.1:56735: runtime error: invalid memory address or nil pointer dereference
goroutine 21 [running]:
net/http.func·011()
	/Users/armon/go/src/net/http/server.go:1130 +0xbb
database/sql.(*Rows).Next(0x0, 0xc20838d128)
	/Users/armon/go/src/database/sql/sql.go:1586 +0x25
github.com/hashicorp/vault/physical.(*MySQLBackend).List(0xc2080a2640, 0xc2083358a0, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/physical/mysql.go:156 +0x309
github.com/hashicorp/vault/physical.(*Cache).List(0xc2080a2000, 0xc2083358a0, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/physical/cache.go:83 +0x8a
github.com/hashicorp/vault/vault.(*AESGCMBarrier).List(0xc2080560c0, 0xc2083358a0, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/vault/barrier_aes_gcm.go:654 +0x20f
github.com/hashicorp/vault/vault.(*BarrierView).List(0xc20801fc00, 0xc2080fd64e, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/vault/barrier_view.go:44 +0x195
github.com/hashicorp/vault/vault.ScanView(0xc20801fc00, 0xc20838d4f0, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/vault/barrier_view.go:114 +0x110
github.com/hashicorp/vault/vault.CollectKeys(0xc20801fc00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/vault/barrier_view.go:141 +0xa2
github.com/hashicorp/vault/vault.(*ExpirationManager).Restore(0xc2080fd500, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/vault/expiration.go:116 +0xc9
github.com/hashicorp/vault/vault.(*Core).setupExpiration(0xc20800c280, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/vault/expiration.go:91 +0x116
github.com/hashicorp/vault/vault.(*Core).postUnseal(0xc20800c280, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/vault/core.go:1242 +0x51a
github.com/hashicorp/vault/vault.(*Core).Unseal(0xc20800c280, 0xc20801ee60, 0x20, 0x20, 0x0, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/vault/core.go:916 +0xc55
github.com/hashicorp/vault/http.func·023(0x7fb830b11350, 0xc2080c7220, 0xc20838e750)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/http/sys_seal.go:64 +0x40c
net/http.HandlerFunc.ServeHTTP(0xc20805ac40, 0x7fb830b11350, 0xc2080c7220, 0xc20838e750)
	/Users/armon/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20840c3f0, 0x7fb830b11350, 0xc2080c7220, 0xc20838e750)
	/Users/armon/go/src/net/http/server.go:1541 +0x17d
github.com/hashicorp/vault/http.func·001(0x7fb830b11350, 0xc2080c7220, 0xc20838e750)
	/Users/armon/projects/go/src/github.com/hashicorp/vault/http/help.go:18 +0x128
net/http.HandlerFunc.ServeHTTP(0xc208410880, 0x7fb830b11350, 0xc2080c7220, 0xc20838e750)
	/Users/armon/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc2084013e0, 0x7fb830b11350, 0xc2080c7220, 0xc20838e750)
	/Users/armon/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208388320)
	/Users/armon/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/Users/armon/go/src/net/http/server.go:1751 +0x35e
```

What I don't understand is if there are no associated leases with properties, why is Vault generating records in the database for them? Seems to me like there should be logic to know whether leases are being used or not, and write to the database only if leases are active (or renewable, etc).

Any insight would greatly be appreciated!

**Comment by jefferai** [comment]
All backends currently generate expiring leases (although in the future backends that do not actually expire/revoke values at the end of a lease, such as the generic backend, may simply skip generation).

Based on your description I'm guessing that you are using the generic backend. The duration that is returned by a lease from the generic backend is meant to be an administratively-set value that is a hint as to how often a service should check for a new value; the service should cache the value until then. If you are constantly reading the same value over and over, it will indeed generate new leases. You could reduce the length of time of the lease duration, which may help (0.3 will contain the ability to set your own default/max duration globally as well as per-backend).

I'm not currently sure what causes your eventual crash, and whether it is an issue in the Vault code or higher up in the SQL driver. The MySQL physical code was community-contributed; if you have the inclination to dig into it, we'd welcome a fix.

**Comment by jefferai** [comment]
This was likely due to the generic backend creating leases and eventually filling things up, which changed in 0.3. I'm going to close this now, please re-open if you're still having issues.
