### ISSUE TITLE
Vault Agent Auto-Auth AppRole Documentation Missing

### ISSUE THREAD

**Issue by arusso** [hashicorp/vault#5948]
**Describe the bug**

The documentation for the AppRole Auto-Auth Method for Vault Agent does not appear in the navigation panel on the left hand side of the website among the other methods.

I see there's documentation written [here](https://github.com/hashicorp/vault/blob/stable-website/website/source/docs/agent/autoauth/methods/approle.html.md) and I was able to navigate directly to the [method's docs](https://www.vaultproject.io/docs/agent/autoauth/methods/approle.html) so it's being rendered and deployed, but the navigation menu isn't being update it seems.
 
**To Reproduce**
- Visit https://www.vaultproject.io/docs/agent 
- Notice the missing entry for AppRole in the Auto-Auth Methods section on the sidebar

**Expected behavior**
- AppRole documentation is easily accessible via the vault website

**Environment:**

N/A

**Comment by jefferai** [comment]
Fixed; site being redeployed.
