### ISSUE TITLE
Unable to add LDAP user to non LDAP group

### ISSUE THREAD

**Issue by shashanksinha1989** [hashicorp/vault#596]
I am trying to use my existing LDAP user with a group created internally on vault. 

================================
 vault write auth/ldap/users/tesla groups=engineers

vault write auth/ldap/users/shashank groups=AD_TEST
Error writing data to auth/ldap/users/shashank: Error making API request.

URL: PUT http://10.157.137.175:8200/v1/auth/ldap/users/shashank
Code: 500. Errors:

* unsupported path

**Comment by jefferai** [comment]
Do you have any output from the Vault console when this happens? Most 500 errors will generate more descriptive output on the console.

**Comment by jefferai** [comment]
Also, when you say "a group created internally on Vault", what exactly do you mean here -- how did you create this group? Vault doesn't support a notion of user groups.

**Comment by shashanksinha1989** [comment]
This is the output from console from one terminal.

==================================================
# vault server -config config.json -log-level=debug
==> Vault server configuration:

         Log Level: debug
             Mlock: supported: true, enabled: true
           Backend: file
        Listener 1: tcp (addr: "10.157.137.175:8200", tls: "disabled")

==> Vault server started! Log data will stream in below:

2015/09/11 06:10:09 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/09/11 06:10:09 [INFO] core: post-unseal setup starting
2015/09/11 06:10:09 [INFO] core: post-unseal setup complete
2015/09/11 06:10:09 [INFO] core: root token generated
2015/09/11 06:10:09 [INFO] core: pre-seal teardown starting
2015/09/11 06:10:09 [INFO] rollback: starting rollback manager
2015/09/11 06:10:09 [INFO] rollback: stopping rollback manager
2015/09/11 06:10:09 [INFO] core: pre-seal teardown complete
2015/09/11 06:10:22 [INFO] core: vault is unsealed
2015/09/11 06:10:22 [INFO] core: post-unseal setup starting
2015/09/11 06:10:22 [INFO] core: post-unseal setup complete
2015/09/11 06:10:22 [INFO] rollback: starting rollback manager
2015/09/11 06:10:59 [INFO] core: enabled credential backend 'ldap/' type: ldap

**Comment by shashanksinha1989** [comment]
vault server -config config.json -log-level=debug
==> Vault server configuration:

         Log Level: debug
             Mlock: supported: true, enabled: true
           Backend: file
        Listener 1: tcp (addr: "10.157.137.175:8200", tls: "disabled")

==> Vault server started! Log data will stream in below:

2015/09/11 06:10:09 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/09/11 06:10:09 [INFO] core: post-unseal setup starting
2015/09/11 06:10:09 [INFO] core: post-unseal setup complete
2015/09/11 06:10:09 [INFO] core: root token generated
2015/09/11 06:10:09 [INFO] core: pre-seal teardown starting
2015/09/11 06:10:09 [INFO] rollback: starting rollback manager
2015/09/11 06:10:09 [INFO] rollback: stopping rollback manager
2015/09/11 06:10:09 [INFO] core: pre-seal teardown complete
2015/09/11 06:10:22 [INFO] core: vault is unsealed
2015/09/11 06:10:22 [INFO] core: post-unseal setup starting
2015/09/11 06:10:22 [INFO] core: post-unseal setup complete
2015/09/11 06:10:22 [INFO] rollback: starting rollback manager
2015/09/11 06:10:59 [INFO] core: enabled credential backend 'ldap/' type: ldap

**Comment by shashanksinha1989** [comment]
On other terminal I am ruuning these commands :--

$ vault auth-enable ldap
Successfully enabled 'ldap' at 'ldap'!

$ vault write auth/ldap/groups/engineer policies=root
Success! Data written to: auth/ldap/groups/engineer

$ vault write auth/ldap/users/E058800 groups=engineer
Error writing data to auth/ldap/users/E058800: Error making API request.

URL: PUT http://10.157.137.175:8200/v1/auth/ldap/users/E058800
Code: 500. Errors:

* unsupported path

**Comment by shashanksinha1989** [comment]
On console output I was not able to see any of this.

**Comment by jefferai** [comment]
Unfortunately I'm not sure what's going on here, as I can't replicate the problem:
```
jeff@snicketysnack:~ > vault auth-enable ldap
Successfully enabled 'ldap' at 'ldap'!
jeff@snicketysnack:~ > vault write auth/ldap/groups/engineer policies=root
Success! Data written to: auth/ldap/groups/engineer
jeff@snicketysnack:~ > vault write auth/ldap/users/E058800 groups=engineer
Success! Data written to: auth/ldap/users/E058800
```
Are you on Vault 0.2? Any chance you can try building from master and see if this is a problem that is since fixed?

**Comment by shashanksinha1989** [comment]
yes I am on Vault v0.2.0. Is this issue related to this issue?

**Comment by shashanksinha1989** [comment]
Can you try this after binding vault to your network interface? 
[root@vault_test apps_data_01]# cat config.json

backend "file"{
path = "/apps_data_01/store"
}
listener "tcp" {
address = "10.157.137.175:8200"
tls_disable = 1
}


[root@vault_test apps_data_01]# vault server -config config.json &
[1] 111429
[root@vault_test apps_data_01]# ==> Vault server configuration:

         Log Level: info
             Mlock: supported: true, enabled: true
           Backend: file
        Listener 1: tcp (addr: "10.157.137.175:8200", tls: "disabled")

==> Vault server started! Log data will stream in below:


[root@vault_test apps_data_01]# vault init -key-shares=1 -key-threshold=1
2015/09/15 00:01:48 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/09/15 00:01:48 [INFO] core: post-unseal setup starting
2015/09/15 00:01:48 [INFO] core: post-unseal setup complete
2015/09/15 00:01:48 [INFO] core: root token generated
2015/09/15 00:01:48 [INFO] core: pre-seal teardown starting
2015/09/15 00:01:48 [INFO] rollback: starting rollback manager
2015/09/15 00:01:48 [INFO] rollback: stopping rollback manager
2015/09/15 00:01:48 [INFO] core: pre-seal teardown complete


[root@vault_test apps_data_01]# export VAULT_ADDR='http://10.157.137.175:8200'
[root@vault_test apps_data_01]# vault unseal
Key (will be hidden):
2015/09/15 00:02:50 [INFO] core: vault is unsealed
2015/09/15 00:02:50 [INFO] core: post-unseal setup starting
2015/09/15 00:02:50 [INFO] core: post-unseal setup complete
2015/09/15 00:02:50 [INFO] rollback: starting rollback manager
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0
[root@vault_test apps_data_01]# vault auth
Token (will be hidden):
Successfully authenticated! The policies that are associated
with this token are listed below:

root

[root@vault_test apps_data_01]# vault auth-enable ldap
2015/09/15 00:03:25 [INFO] core: enabled credential backend 'ldap/' type: ldap
Successfully enabled 'ldap' at 'ldap'!

[root@vault_test apps_data_01]# vault write  auth/ldap/groups/engineer policies=root
Success! Data written to: auth/ldap/groups/engineer

[root@vault_test apps_data_01]# vault write auth/ldap/users/E058800 groups=engineer
Error writing data to auth/ldap/users/E058800: Error making API request.

URL: PUT http://10.157.137.175:8200/v1/auth/ldap/users/E058800
Code: 500. Errors:

* unsupported path

**Comment by Poohblah** [comment]
I'm having this issue as well.  I'm trying to add the user `aa729` to the policy `root` in the following example.

The user exists on my server:

```
irb(main):025:0> ldap_client.search(base: '', filter: 'uid=aa729')
=> [#<Net::LDAP::Entry:0x0000000297a188 @myhash={:dn=>["uid=aa729,ou=people,dc=example,dc=org"], :mail=>["alexandra@example.org"], :givenname=>["Alexandra"], :sn=>["Adams"], :cn=>["Alexandra Adams"], :objectclass=>["top", "person", "organizationalPerson", "inetOrgPerson"], :userpassword=>["{SHA}pGlmZX1VOEdHHb30HZezeVNFxGM="], :uid=>["aa729"]}>]
```

And my vault server is configured correctly:

```
[vagrant@ldap-centos-71 ~]$ vault read auth/ldap/config
Key         	Value
groupdn     	
insecure_tls	false
starttls    	false
url         	ldap://localhost:3897
userattr    	uid
userdn      	ou=people,dc=example,dc=org
certificate
```

And I can attempt to auth as the user - but vault complains about no groups assigned to user:
```
[vagrant@ldap-centos-71 ~]$ vault auth -method=ldap username=aa729
Password (will be hidden): 
Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/ldap/login/aa729
Code: 400. Errors:

* user is not member of any authorized group
```

So I create a group with policy `root`:
```
[vagrant@ldap-centos-71 ~]$ vault write auth/ldap/groups/foo policies=root
Success! Data written to: auth/ldap/groups/foo
[vagrant@ldap-centos-71 ~]$ vault read auth/ldap/groups/foo
Key     	Value
policies	root
```

But I can't add `aa729` to the group:
```
[vagrant@ldap-centos-71 ~]$ vault write auth/ldap/users/aa729 groups=foo
Error writing data to auth/ldap/users/aa729: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/ldap/users/aa729
Code: 500. Errors:

* unsupported path
```

In fact, I can't even read information about this user or any other user:
```
[vagrant@ldap-centos-71 ~]$ vault read auth/ldap/users/aa729
Error reading auth/ldap/users/aa729: Error making API request.

URL: GET http://127.0.0.1:8200/v1/auth/ldap/users/aa729
Code: 500. Errors:

* unsupported path
[vagrant@ldap-centos-71 ~]$ vault read auth/ldap/users
Error reading auth/ldap/users: Error making API request.

URL: GET http://127.0.0.1:8200/v1/auth/ldap/users
Code: 500. Errors:

* unsupported path
```

This behavior does not match the API documentation.

Also:
```
[vagrant@ldap-centos-71 ~]$ vault --version
Vault v0.2.0
```

**Comment by shashanksinha1989** [comment]
Issue is resolved by new version of vault.
