### ISSUE TITLE
AD Secret Engine - rotate password AFTER access/ttl, not at time of access

### ISSUE THREAD

**Issue by erickufrin** [hashicorp/vault#5969]
We would like to use the AD secret backend but it does not meet our use-case requirements.

Our use case is "admin account password checkout". Time based access to an admin password, where the password forcibly resets at a prescribed maximum-time (or "checkin") to effectively offboard access to the credential, requiring the admin to return to Vault and retrieve the current day's password.

Rotating the password only upon access+ttl does not ensure that the password is actually rotated after use and does not prevent the user from writing it down somewhere.

It would be great to have a flag on this secret engine that allowed this alternate mode of operation. Giving us the flexibility to choose the point in the processes where actual password rotation occurs.

We are using a competing product for this today and want to retire said product...

**Comment by jefferai** [comment]
We plan to do this at some point (I don't know if it's specifically on the roadmap yet). If you're interested in working on it we could guide you through it.

**Comment by erickufrin** [comment]
We are glad to hear that this is planned to do at some point. Unfortunately I dont think we have the ability to develop this ourselves even with your guidance. We are hopeful that Hashicorp will take this up within it's near-term product roadmap or other community members who are better equipped to co-develop this will step up...

**Comment by michelvocks** [comment]
Closing this since https://github.com/hashicorp/vault/pull/7617 has been merged and will be released with Vault 1.3.
