### ISSUE TITLE
timezone issue with postgresql

### ISSUE THREAD

**Issue by lassizci** [hashicorp/vault#597]
Vault seems to use UTC for expiration times. However, with at least postgresql backend there's an issue if the database backend is something else than UTC.

I'm on UTC+3 and if I create one hour lease, the password is already expired. The workaround is to "SET time zone 'utc'" in the role creation template, but that doesn't work for renew lease.

I've created a lease (lease=3h, lease_max=240h) and postgresql says: "Password valid until 2015-09-08 15:58:33+03". Then I renew the lease by adding 3600 as increment and after that the password expires sooner: "Password valid until 2015-09-08 11:01:40+03".

**Comment by jefferai** [comment]
Thanks for the report!
