### ISSUE TITLE
MSSQL storage does not allow for specification of port

### ISSUE THREAD

**Issue by arkitekt78** [hashicorp/vault#5977]
**Describe the bug**
When using MSSQL as the backend storage for vault, there is no way to specify the port number as an option if instance is not specified.

**To Reproduce**
1. Attempt to configure vault to use MSSQL as backend storage
2. Build configuration file
3. Specify server without instance
4. "port" is not an option in config file, and when attempting to start vault, it tries to find databases using default port of 1433

**Expected behavior**
Configuration file include "port" property

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.0
* Vault CLI Version (retrieve with `vault version`): v1.0.0
* Server Operating System/Architecture: Ubuntu 18.04

**Comment by chrishoffman** [comment]
I believe it can be specified in the following combinations:

`host:port`
`host\\instance`

**Comment by arkitekt78** [comment]
I understand the host\\instance - but in situations where that is problematic, a port is needed.  I tried the host:port as well as host,port, which are both common methods for including the port number in connection strings, but neither work.  The system is assuming the :port or ,port is part of the host name, which of course it cannot find...  

However, while I have had very limited experience with go, a brief cursory search on SQL server connection strings in go, it uses a separate property in the connection string for port numbers...

**Comment by bardagadvergur** [comment]
@arkitekt78 Did you manage to define a port for the SQL server?

**Comment by briankassouf** [comment]
fixed by #6145
