### ISSUE TITLE
Waiting for SSH to become available -- Linux guest os

### ISSUE THREAD

**Issue by ghpradeep** [hashicorp/vault#5984]
Hello Team,

I am using windows packer tool to build Redhat custome image. I have installed Virtual Box on My Windows 7 laptop.  I have created json file and ks.cfg file to build custom image.  however, packer commands lunch virtual box and start building an image.  OS installation completed successfully. I can log in to Linux box using username and password. 

But packer command output stuck at below msg. if I do Control+c then it deletes created VM.

PS C:\Users\pradeep\Downloads\packer_1.3.3_windows_amd64> .\packer.exe build .\example.json
virtualbox-iso output will be in this color.

==> virtualbox-iso: Retrieving Guest additions
    virtualbox-iso: Using file in-place: file:///C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Retrieving ISO
    virtualbox-iso: Using file in-place: file:///C:/Users/a630508/Downloads/packer_1.3.3_windows_amd64/rhel-server-7.5-x
86_64-dvd.iso
==> virtualbox-iso: Starting HTTP server on port 8441
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 3028)
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Waiting 10s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Using ssh communicator to connect: 127.0.0.1
==> virtualbox-iso: Waiting for SSH to become available...

any idea how to resolve this issue.

**Comment by ncabatoff** [comment]
This doesn't seem related to the vault project.  If you look at the Packer [community page](https://www.packer.io/community.html) they request that you ask questions for general help on their [mailing list](https://groups.google.com/group/packer-tool); I suggest you take your question there.
