### ISSUE TITLE
Vault PKI ignores otherName field in CSR

### ISSUE THREAD

**Issue by chadparry** [hashicorp/vault#5989]
**Describe the bug**
Clients can currently submit a CSR where various fields are specified in either the CSR blob or in the JSON payload. However, the `otherName` field is inconsistent. If there is an `otherName` value in the CSR blob, it gets ignored. Clients are relegated to only using the JSON blob.

**To Reproduce**
These commands show two certificate signing requests, one that works and one that fails.
```
# Input the Vault root token
read -p "Vault root token: " -s VAULT_TOKEN
export VAULT_TOKEN
# Identify the Vault server
export VAULT_ADDR="http://127.0.0.1:8200"
# Set a SAN
OTHER_NAME="1.3.6.1.2.1.27.1.1.2;UTF8:bar"
# Generate a CSR
CSR="$(openssl req -new -newkey rsa:2048 -nodes -config <(<<END cat
[req]
prompt = no
distinguished_name = req_dn
req_extensions = req_ext
[req_dn]
commonName = "foo"
[req_ext]
subjectAltName = @san
[san]
otherName = "$OTHER_NAME"
END
) -keyout "foo.key")"
# Sign the app certificate, repeating the otherName in the JSON payload (which will work)
curl -s --header "X-Vault-Token: $VAULT_TOKEN" --data "$(jq -n --arg CSR "$CSR" --arg OTHER_NAME "$OTHER_NAME" '{ "csr": $CSR, "other_sans": $OTHER_NAME }')" "$VAULT_ADDR/v1/pki/sign/test-role" | jq -r '.data.certificate' | openssl x509 -text | tee "foo-1.crt"
# Sign the app certificate, only specifying the otherName in the CSR (which will create an incorrect certificate with no otherName)
curl -s --header "X-Vault-Token: $VAULT_TOKEN" --data "$(jq -n --arg CSR "$CSR" '{ "csr": $CSR }')" "$VAULT_ADDR/v1/pki/sign/test-role" | jq -r '.data.certificate' | openssl x509 -text | tee "foo-2.crt"
```

**Expected behavior**
Both certificates should contain an `otherName` field.

**Environment:**
* Vault Server Version: 0.11.5
* Vault CLI Version: v0.11.5
* Server Operating System/Architecture: Ubuntu 16.04.5 LTS

**Comment by jefferai** [comment]
Ignoring the CSR values is expected behavior; if you want to trust CSR values you need to use the sign-verbatim endpoint or set the role parameter that tells Vault to use CSR SANs
 However I think that particular role value may not currently apply to other sans, which is an enhancement we could make.

**Comment by chadparry** [comment]
> Ignoring the CSR values is expected behavior

My experience is that the CSR is not ignored for the `common_name` and `ip_sans` and `uri_sans`. Only the `other_sans` is ignored by the `pki/sign/:name` endpoint. That seems inconsistent.

Here is an example CSR:
```
CSR="$(openssl req -new -newkey rsa:2048 -nodes -config <(<<END cat
[req]
prompt = no
distinguished_name = req_dn
req_extensions = req_ext
[req_dn]
commonName = "foo"
[req_ext]
subjectAltName = @san
[san]
IP = "10.0.0.2"
URI = "spiffe://example.com/foo"
otherName = "1.3.6.1.2.1.27.1.1.2;UTF8:bar"
END
) -keyout "foo.key")"
curl -s --header "X-Vault-Token: $VAULT_TOKEN" --data "$(jq -n --arg CSR "$CSR" '{ "csr": $CSR }')" "$VAULT_ADDR/v1/pki/sign/test-role" | jq -r '.data.certificate' | openssl x509 -text | tee "foo-3.crt"
```

The certificate I get back contains all the CSR fields except that one `otherName`:
```
Certificate:
…
        Subject: CN=foo
…
            X509v3 Subject Alternative Name: 
                DNS:foo, IP Address:10.0.0.2, URI:spiffe://example.com/foo

```

**Comment by jefferai** [comment]
Again, it depends on the role values, but if the role value is set to use CSR SANs that currently doesn't apply to other names, which is why I flagged this as something that needs enhancement.

**Comment by jefferai** [comment]
See https://www.vaultproject.io/api/secret/pki/index.html#use_csr_sans for the role parameter I'm talking about.
