### ISSUE TITLE
Dev mode not working on Mac OS X 10.10.3

### ISSUE THREAD

**Issue by bracki** [hashicorp/vault#60]
Got a fresh download from [here](https://dl.bintray.com/mitchellh/vault/vault_0.1.0_darwin_amd64.zip).
Unzip and run:
```
➜  ./vault server -dev -log-level=debug
Error initializing dev mode: Error: exit status 127

sh: vault: command not found
```

**Comment by sethvargo** [comment]
Hi @bracki 

I am sorry you are having issues. Unfortunately I am unable to reproduce your issue. Here is what I did:

```shell
$ wget -O vault.zip -q https://dl.bintray.com/mitchellh/vault/vault_0.1.0_linux_amd64.zip
$ unzip vault.zip
$ vault server -dev -log-level debug
```

Can you provide any additional debugging information please?

**Comment by bracki** [comment]
Not really. Just built from source and it works.

**Comment by phinze** [comment]
I've reproduced this - we'll get it fixed, but in the meantime you can work around it by ensuring the `vault` executable is in your `$PATH`.

**Comment by mitchellh** [comment]
Fixed
