### ISSUE TITLE
vault agent retry maximum

### ISSUE THREAD

**Issue by tonglil** [hashicorp/vault#6001]
**Is your feature request related to a problem? Please describe.**
It would be great if vault agent would have a retry maximum like consul-template.

Currently using it in an init container, and when vault is unavailable, this blocks the entire container from starting up.

**Describe the solution you'd like**
Configurable maximum retry or once-attempt like consul-template, configurable in config file or cli.

**Describe alternatives you've considered**
Currently sleeping + killing via pidfile, which is not very graceful.

**Comment by mikegreen** [comment]
Supporting all Consul retry params would be great - enabled, attempts, backoff, max_backoff (from https://github.com/hashicorp/consul-template#templating-language)

**Comment by devlounge** [comment]
Any update on this issue?

**Comment by petems** [comment]
This PR also seems related: https://github.com/hashicorp/vault/pull/10644

**Comment by aphorise** [comment]
The related [parameters of `min_backoff`](https://www.vaultproject.io/docs/agent/autoauth#min_backoff) &`max_backoff` have been introduced since this issue was raised.

@tonglil - have you retested or is this issue is still relevant for you?

**Comment by tonglil** [comment]
No longer relevant, though the changes seem like they _should_ work..
