### ISSUE TITLE
Unable to write to hashicorp vault using ansible playbook from a remote machine

### ISSUE THREAD

**Issue by chetanchatrath** [hashicorp/vault#6005]
I have deployed a vault in a machine and trying to write something in the vault using ansible playbook from a remote machine. 
Have used the below commands on the remote machine which has ansible installed:
1. export VAULT_ADDR="http://<Private IP of the machine which has vault>:8200"
2. export VAULT_API_ADDR="http://<Private IP of the machine which has vault>:8200"
3. Vault login <token ID>
4. I am trying to run the following ansible playbook:
- hosts: ubuntu
  tasks:
    - name: Insert json into vault
      shell: vault kv put secret/abc/new data=@trial.json
5. After running the ansible-playbook vaultwrite.yml --ask-pass command I get the below errorFAILED! => {"changed": true, "cmd": "vault kv put secret/abc/new 'data=@trial.json'", "delta": "0:00:00.027821", "end": "2019-01-07 21:16:18.107637", "msg": "non-zero return code", "rc": 1, "start": "2019-01-07 21:16:18.079816", "stderr": "Failed to parse K=V data: invalid key/value pair \"data=@trial.json\": error reading file: open trial.json: no such file or directory", "stderr_lines": ["Failed to parse K=V data: invalid key/value pair \"data=@trial.json\": error reading file: open trial.json: no such file or directory"], "stdout": "", "stdout_lines": []}

On running the same command directly using CLI it works.

**Comment by jiangytcn** [comment]
seems related to the playbook, not the vault, you may try provide full path of the file

**Comment by briankassouf** [comment]
I believe you have extra quotes around the key/value 'data=@trial.json' -> data=@trial.json

Closing since this isn't a Vault issue
