### ISSUE TITLE
Error loading configuration from /etc/vault.d/vault.json: error parsing 'storage': storage.storage: At -: root.consul: unknown type for string *ast.ObjectType

### ISSUE THREAD

**Issue by marcuschaney** [hashicorp/vault#6011]
Hello All,

I'm currently attempting to deploy Vault in our Dev environment, but I'm running into an issue when attempting to start the service. 

Error below:

**_"Error loading configuration from /etc/vault.d/vault.json: error parsing 'storage': storage.storage: At -: root.consul: unknown type for string *ast.ObjectType"_**

Config below:
{
  "listener": [
    {
      "tcp": [
        {
          "address": "0.0.0.0:443",
          "tls_cert_file": "/opt/vault/ssl/priv.pem",
          "tls_key_file": "/opt/vault/ssl/cert.pem"
        }
      ]
    },
    {
      "tcp": [
        {
          "address": "0.0.0.0:8200",
          "tls_disable": 1
        }
      ]
    }
  ],
  "storage": [
    {
      "consul": [
        {
          "address": "10.11.x.x:8500",
          "advertise_addr": "http://10.11.x.x:8200",
          "path": "vault"
        }
      ]
    }
  ],
  "ui":true,
  "cluster_name": "dev-test-vault",
  "log_level": "",
  "raw_storage_endpoint":true,
  "max_lease_ttl": "10h",
  "default_lease_ttl": "10h"
}

Any ideas on how I can get past this? I have the consul agent installed and running on the box.

**Comment by devster31** [comment]
I believe you used a converter to change the config from `hcl` to `json`.
the mistake should be an additional square bracket for storage:
```json
{
  "listener":[
    {
      "tcp":[
        {
          "address":"0.0.0.0:443",
          "tls_cert_file":"/opt/vault/ssl/priv.pem",
          "tls_key_file":"/opt/vault/ssl/cert.pem"
        }
      ]
    },
    {
      "tcp":[
        {
          "address":"0.0.0.0:8200",
          "tls_disable":1
        }
      ]
    }
  ],
  "storage": {
    "consul": {
      "address":"10.11.x.x:8500",
      "advertise_addr":"http://10.11.x.x:8200",
      "path":"vault"
    }
  },
  "ui":true,
  "cluster_name":"dev-test-vault",
  "log_level":"",
  "raw_storage_endpoint":true,
  "max_lease_ttl":"10h",
  "default_lease_ttl":"10h"
}
```
