### ISSUE TITLE
No online docs for the KV CLI command yet

### ISSUE THREAD

**Issue by lucymhdavies** [hashicorp/vault#6029]
The CLI's helptext is already pretty good, i.e. `vault kv --help`

However, it's useful to be able to point newcomers to some online documentation, and having all CLI documentation in the same place has been helpful.

https://www.vaultproject.io/docs/commands/ does already list a lot of vault cli subcommands, but it's missing a section for the kv subcommand.

I'm aware that there is already some really good documentation on `vault kv` in the Secrets section of the documentation.
i.e. https://www.vaultproject.io/docs/secrets/kv/kv-v1.html and https://www.vaultproject.io/docs/secrets/kv/kv-v2.html

There's also this section of the CLI overview:
https://www.vaultproject.io/docs/commands/#reading-and-writing-data
Though this only covers the basic functionality such as `kv get` and `kv put`

**Comment by nwright-nz** [comment]
Hi @lucymhdavies - I've taken a stab at this (trying to get more involved with this project!) - Happy to modify if you feel I haven't covered this off sufficiently.
Thanks!

**Comment by tyrannosaurus-becks** [comment]
Closing, as this appears to have been addressed in #6033.
