### ISSUE TITLE
unable to renew token lease

### ISSUE THREAD

**Issue by warroyo** [hashicorp/vault#604]
I have created a user in vault "read-user" when I auth with this user using `auth/userpass/login` i recieve a `client_token`. I am able to use this token just fine for api calls, however it looks like renewable is always set to false when I auth. 

using a root user when I run renew-token I get the following error:

`Code: 400. Errors: * lease is not renewable`

is there a way to make these tokens generated by user password auth renewable?

**Comment by jefferai** [comment]
Hi Will,

Please see this discussion on the mailing list:

https://groups.google.com/d/msgid/vault-tool/39992b4e-744f-49b6-8952-44892a73de5b%40googlegroups.com

I believe you may be having the same issue. Can you see if the solution
there works for you?

Thanks!

**Comment by warroyo** [comment]
thank you for the quick response!

That does help wiht some of my confusion, however that only works when using the token auth backend. wehn using this command:

`vault write auth/userpass/users/read-user password='blah' policies=secrets-read lease=720h`

I am still unable to renew the lease on the generated token.


for example I use this rest call:

`v1/auth/userpass/login/read-user`

I then get a client_token, that token is unabel to be renewed.

**Comment by jefferai** [comment]
Thanks for clarifying. The `userpass` backend unfortunately does not currently (in 0.2) support renewing tokens.

There are plans for the next release to have all backends support renewable leases (except for those that actually can't, such as `pki` and `ssh`).

**Comment by warroyo** [comment]
oh ok thank you!
