### ISSUE TITLE
InternalTokenHelper's Store() may be losing token writes when invoked via official Docker image

### ISSUE THREAD

**Issue by StephenWithPH** [hashicorp/vault#6048]
**Describe the bug**
When using tag `1.0.1` (currently, the highest semver tag) of  [the official Vault Docker image](https://hub.docker.com/_/vault), users can use the container to retrieve a client token. If the user takes advantage of the container's documented ability to...
>look for Vault subcommands and run vault with that subcommand

... *and* the user [bind mounts](https://docs.docker.com/storage/bind-mounts/) a file from their host to `/root/.vault-token`, the container's writes to that file can be lost when the container exits before the write syncs to disk.

Note that Docker is likely exacerbating this bug, but it is not the root cause.

**To Reproduce**
1. Run `touch foo && docker run --rm -it --mount type=bind,source=$PWD/foo,destination=/root/.vault-token -e SKIP_SETCAP=true vault:1.0.1 login -address=<a valid Vault server> -method <the method and args necessary>`
2. Complete the steps to login dependent on the method (e.g., enter one's Okta password)
3. See the container exit `0` as expected. Observe that the `foo` file is unchanged and still empty.

**Expected behavior**
The client token written by the container to `/root/.vault-token` is reflected in the bind-mounted file `foo`.

**Environment:**
* Vault Server Version: `0.7.3` (but I don't believe this matters for the bug)
* Vault CLI Version: `Vault v1.0.1 ('08df121c8b9adcc2b8fd55fc8506c3f9714c7e61')`
* Docker *host* machine is Ubuntu 18.04.

**Additional context**
* Take note that the host system Is Ubuntu, so [Docker OSX consistency](https://docs.docker.com/docker-for-mac/osxfs-caching/) is not at play here.

I believe the write happens at https://github.com/hashicorp/vault/blob/master/command/token/helper_internal.go#L65. Take note of the deferred file close https://github.com/hashicorp/vault/blob/master/command/token/helper_internal.go#L62. I believe an explicit call to [f.Sync()](https://golang.org/pkg/os/#File.Sync) would greatly reduce this problem.

By invoking the container with a subcommand, the [container's entrypoint](https://github.com/hashicorp/docker-vault/blob/master/0.X/docker-entrypoint.sh#L95) `exec`'s (or `su-exec`'s) that Vault command. As soon as it exits, the entire container exits. The write may not yet have flushed.

To exercise this theory:
1. Run `touch foo && docker run --rm -it --mount type=bind,source=$PWD/foo,destination=/root/.vault-token -e SKIP_SETCAP=true --entrypoint sh vault:1.0.1`
2. Inside the container, run `vault login -address=<a valid Vault server> -method <the method and args necessary>`
3. Complete the steps to login dependent on the method (e.g., enter one's Okta password)
4. Run `cat /root/.vault-token` to see that the successful login wrote the token as expected
5. `exit` the container
6. Run `cat ./foo` from your machine, and see that the token value was written to the file on the host as well since it was bind mounted.

The only difference (as far as I can figure out) between these steps and the reproduction steps above is time. The container is alive for longer before it exits, so the OS flushes to disk.

See the "Update 2" paragraph at https://www.joeshaw.org/dont-defer-close-on-writable-files/ for details on `Close()` and `Sync()` in go.

**Comment by vishalnayak** [comment]
Issues that are not reproducible and/or have not had any interaction for a long time are stale issues. Sometimes even the valid issues remain stale lacking traction either by the maintainers or the community. In order to provide faster responses and better engagement with the community, we strive to keep the issue tracker clean and the issue count low. In this regard, our current policy is to close stale issues after 30 days. If a feature request is being closed, it means that it is not on the product roadmap. Closed issues will still be indexed and available for future viewers. If users feel that the issue is still relevant but is wrongly closed, we encourage reopening them.

Please refer to our [contributing guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md) for details on issue lifecycle.
