### ISSUE TITLE
ACL roles

### ISSUE THREAD

**Issue by benmccann** [hashicorp/vault#605]
You can associate a policy with an identity directly. However, typically when doing authorization you want to assign privileges to a role and then assign the role to identities. Otherwise if becomes very difficult to manage. E.g. if you have a secret which you want all engineers to have access to you will have to add it to each identity individually vs. just adding it to the engineering group.

**Comment by jefferai** [comment]
Hi Ben,

Can you explain what you are looking for in more detail? Right now you can set a number of policies that control access to various resources. This is very similar to assigning a set of permissions to a role. When a token is issued, it can then be associated with one or more policies -- similar to assigning one or more roles to a user.

Thanks,
Jeff

**Comment by benmccann** [comment]
Ahh, thanks for the clarification. I'm afraid I didn't catch that a policy was essentially a role the first time around reading the docs

**Comment by jefferai** [comment]
No problem! Glad to help.
