### ISSUE TITLE
MSSQL plugin revoke users issue

### ISSUE THREAD

**Issue by bardagadvergur** [hashicorp/vault#6060]
There is an issue with revoking users in the MSSQL plugin. The error I get is this:

`[ERROR] expiration: failed to revoke lease: lease_id=database/creds/test/1oeia5hGjyneURHkpBeC9IZo error="failed to revoke entry: resp: (*logical.Response)(nil) err: sql: Scan error on column index 1, name "DBName": unsupported Scan, storing driver.Value type <nil> into type *string"`

The core of the issue is that the stored procedure `sp_msloginmappings` will always return a row, even if the login has no users / db's associated with it.

The issue comes into play when the first attempt to revoke fails at any stage AFTER the users associated with the logins are removed from all databases. On the next attempt to revoke, the stored procedure `sp_msloginmappings` returns NULL in the column DBName and the revoke attempt fails. This results in all the logins created to remain on the server as disabled and the leases build up within HashiCorp. 

A check here for DBName = null should do it: https://github.com/hashicorp/vault/blob/6e99c837e5eac025db729285e7d93566d43aa620/plugins/database/mssql/mssql.go#L269

**Comment by bardagadvergur** [comment]
@chrishoffman maybe something you can take a look at?

**Comment by tyrannosaurus-becks** [comment]
Thanks for reporting this, @bardagadvergur ! I was able to reproduce this locally by manually adding a faux err after running the revocation statements, then running it again.

I found that there was no way to tell in advance that `Scan` would err on the following line. However, converting to null strings eliminated the err and got it all functioning properly. PR linked to solve it.
