### ISSUE TITLE
[Feature Request] specify deregister_critical_service_after for consul service

### ISSUE THREAD

**Issue by eedwards-sk** [hashicorp/vault#6065]
**Is your feature request related to a problem? Please describe.**
I'm very frustrated trying to use vault, consul, and terraform together.

Vault registers health checks in consul automatically, great, except that when a vault server dies (like in an ASG), it leaves the service registration in the catalog, which requires manual cleanup.

This screws you big time if you, like me, use terraform to get the vault addresses from the catalog, since terraform doesn't support retrieving only "healthy" addresses.

A huge improvement here would be to support `deregister_critical_service_after` so that I can inform the services to automatically deregister themselves.

At this point, my only other solution would be to wire up the consul checks myself, which makes no sense especially considering some of the [known issues](https://github.com/hashicorp/vault/issues/3279) there.

**Describe the solution you'd like**
Support specifying `deregister_critical_service_after` for the consul services that vault registers.

**Describe alternatives you've considered**
Create the checks myself. This would be duplicating a bunch of work that's already been done. Why?

**Explain any additional use-cases**
See above description with how it intersects with terraform. I need to quickly evict old vault services once they go unhealthy.

**Comment by jefferai** [comment]
As I asked on the mailing list, please go through Consul support first. These should be cleaned up when the session expires. If they're not, it seems like a Consul issue.

**Comment by eedwards-sk** [comment]
@jefferai 

No offense, but considering how quickly you closed this, did you even read the feature request?

How does the mailing list help me add a new feature?

The issue I described is a consul issue, yes, thus I described a feature request to help alleviate it (support `deregister_critical_service_after`).

The consul issue is the fact that services don't get de-registered when a node dies.

**Comment by jefferai** [comment]
I did. But I'm not sure that that's the right thing to do. On my reply on the ML I asked you to follow up with Consul and if they recommended we make that change I'd be happy to do it.
