### ISSUE TITLE
Vault Write/reads not working

### ISSUE THREAD

**Issue by pandugathrinath** [hashicorp/vault#6066]
Vault writes/reads not working

I'm using the enterprise version of vault and running it in dev mode

test.json 
{ "value1": "bGktzwatc", "value2": "AGktzwatB" }

**1. vault write gcp/config credentials=@test.json**
Success! Data written to: gcp/config

read doesn't read my values
**2. vault read gcp/config**
Key        Value
---        -----
max_ttl    0s
ttl        0s
     ( or )
**vault read gcp/config @credentials.json**
Key        Value
---        -----
max_ttl    0s
ttl        0s
       (or )
**vault read gcp/config credentials=@credentials.json**
Key        Value
---        -----
max_ttl    0s
ttl        0s

one more of the same kind 
**vault write kv/airplane type=boeing class=787**
Error writing data to kv/airplane: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/kv/airplane
Code: 404. Errors:

WARNING! The following warnings were returned from Vault:

  * Invalid path for a versioned K/V secrets engine. See the API docs for the
  appropriate API endpoints to use. If using the Vault CLI, use 'vault kv put'
  for this operation.

I have tried this right from the documentation : https://www.hashicorp.com/resources/getting-vault-enterprise-installed-running

**Comment by gitirabassi** [comment]
Hi
1. https://www.vaultproject.io/api/secret/gcp/index.html#read-config
Credentials can only be written and not be read for security concerns as in most secret/auth engines
2. This kind of error is mostly due to the fact that the key/value store is of version=2 for which you should use `vault kv put` and `vault kv get`

**Comment by chrishoffman** [comment]
The answer above is correct, sensitive values are not returned for security reasons.  Additionally, KVv2 has a different API and the `vault kv` subcommand should be used.  See https://www.vaultproject.io/docs/secrets/kv/index.html.
