### ISSUE TITLE
Templating policy with the `identity.entity.aliases` var not working

### ISSUE THREAD

**Issue by viralpoetry** [hashicorp/vault#6071]
**Describe the bug**
Vault user authenticated by using LDAP Auth method does not have assigned templated policy.

**To Reproduce**
1. Configure Vault LDAP Auth backend

2. Find out Accessor
```
vault auth list
Path         Type        Accessor                  Description
----         ----        --------                  -----------
ldap/        ldap        auth_ldap_ea1bef30        n/a
token/       token       auth_token_00bca39d       token based credentials
userpass/    userpass    auth_userpass_a6eb1313    n/a
```

2. Write appropriate policy using admin token
```
vault policy write users_metadata users_metadata.hcl

# check written policy
vault policy read users_metadata
path "secrets/users/{{identity.entity.aliases.auth_ldap_ea1bef30.name}}/*" {
    capabilities = [ "create", "update", "read", "delete", "list" ]
}
```

3. Run `vault login -method=ldap username=t811110`
```
$ vault login -method=ldap username=t811110
Password (will be hidden): 

Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

WARNING! The following warnings were returned from Vault:

  * no LDAP groups found in groupDN ''; only policies from locally-defined
  groups available

Key                    Value
---                    -----
token                  XXXXXXXXXXXXXXXXXXXXX
token_accessor         YYYYYYYYYYYYYYYYYYYYY
token_duration         768h
token_renewable        true
token_policies         ["default" "vault-admin"]
identity_policies      ["safes_abcd" "safes_topsecret"]
policies               ["default" "vault-admin"]
token_meta_username    t811110
```

**Expected behavior**
User should have `users_metadata` policy assigned.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.11.6
* Vault CLI Version (retrieve with `vault version`): 0.11.6
* Server Operating System/Architecture: Ubuntu 18.04

Vault server configuration file(s):

```hcl
{
    "api_addr": "https://vault-g01.EXAMPLE.eu:443", 
    "listener": [
        {
            "tcp": {
                "address": "0.0.0.0:443", 
                "cluster_address": "0.0.0.0:444", 
                "tls_cert_file": "/etc/letsencrypt/live/vault-g01.EXAMPLE.eu/fullchain.pem", 
                "tls_disable": false, 
                "tls_key_file": "/etc/letsencrypt/live/vault-g01.EXAMPLE.eu/privkey.pem", 
                "tls_min_version": "tls12"
            }
        }
    ], 
    "storage": [
        {
            "consul": {
                "address": "127.0.0.1:8500", 
                "path": "/vault", 
                "token": "DEADBEEF"
            }
        }
    ]
}
```

**Additional context**

```
vault token lookup
Key                            Value
---                            -----
accessor                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
creation_time                  1547821300
creation_ttl                   768h
display_name                   ldap-t811110
entity_id                      45a78964-2c06-4e60-68c8-d300fc21c593
expire_time                    2019-02-19T15:21:40.195127428+01:00
explicit_max_ttl               0s
external_namespace_policies    map[]
id                             3rknkJJgWL0FKoEz9MBMflin
identity_policies              [safes_abcd safes_topsecret]
issue_time                     2019-01-18T15:21:40.195126982+01:00
meta                           map[username:t811110]
num_uses                       0
orphan                         true
path                           auth/ldap/login/t811110
policies                       [default vault-admin]
renewable                      true
ttl                            767h23m19s
```

```
vault read identity/entity/id/45a78964-2c06-4e60-68c8-d300fc21c593
Key                    Value
---                    -----
aliases                [map[id:4e491bb2-a259-f642-b1bc-b76a953a0936 merged_from_canonical_ids:<nil> mount_accessor:auth_ldap_ea1bef30 mount_path:auth/ldap/ mount_type:ldap name:t811110 canonical_id:45a78964-2c06-4e60-68c8-d300fc21c593 creation_time:2019-01-16T09:11:28.582466921Z last_update_time:2019-01-16T09:11:28.582466921Z metadata:<nil>]]
creation_time          2019-01-16T09:11:28.582461333Z
direct_group_ids       [6e087c92-242b-0419-a5ce-4aec297f873b 9ac8bf6c-8a8c-2b37-39f2-41538ddf6a08 d7f00072-725b-2690-56a5-c1a8d07ef8b6]
disabled               false
group_ids              [6e087c92-242b-0419-a5ce-4aec297f873b 9ac8bf6c-8a8c-2b37-39f2-41538ddf6a08 d7f00072-725b-2690-56a5-c1a8d07ef8b6]
id                     45a78964-2c06-4e60-68c8-d300fc21c593
inherited_group_ids    []
last_update_time       2019-01-17T15:19:57.135328382Z
merged_entity_ids      <nil>
metadata               map[]
name                   safes_t811110
policies               [
```

```
vault read identity/entity-alias/id/4e491bb2-a259-f642-b1bc-b76a953a0936
Key                          Value
---                          -----
canonical_id                 45a78964-2c06-4e60-68c8-d300fc21c593
creation_time                2019-01-16T09:11:28.582466921Z
id                           4e491bb2-a259-f642-b1bc-b76a953a0936
last_update_time             2019-01-16T09:11:28.582466921Z
merged_from_canonical_ids    <nil>
metadata                     <nil>
mount_accessor               auth_ldap_ea1bef30
mount_path                   auth/ldap/
mount_type                   ldap
name                         t811110
```

Thank you!

**Comment by chrishoffman** [comment]
Templated policies will not assign the policy based on the match.  You still need to attach the policy through normal LDAP backend configuration and then they will get access to the secret path.

**Comment by shallquist** [comment]
What is the point of the template if it doesn't work with ldap?  For instance, I have the following template added to the default policy, but it doesn't allow an authenticated user to create a path at secret/<user name>

path "secret/{{identity.entity.aliases.auth_ldap_6620c8c0.name}}" {
  capabilities = ["create", "update", "read", "delete", "list"]
}

**Comment by viralpoetry** [comment]
@shallquist not sure if this is the case, but try to create it as another policy and set up your ldap backend to assign that policy as default after authentication.

**Comment by shallquist** [comment]
Do you have documentation on setting up your ldap backend to assign policies after auth?

    On Thursday, July 2, 2020, 10:22:02 AM EDT, Peter Gasper <notifications@github.com> wrote:  
 
 


@shallquist not sure if this is the case, but try to create it as another policy and set up your ldap backend to assign that policy as default after authentication.

**Comment by viralpoetry** [comment]
@shallquist 
You have to map ldap group (or multiple) to a role in LDAP auth backend:
https://www.vaultproject.io/docs/auth/ldap#ldap-group-policy-mapping

**Comment by shallquist** [comment]
That is exactly what I did and it did not work.  I know that my policy to ldap group mapping is correct, since a user who log's in with that ldap group assigned is able to see secrets in the path I assigned in the policy.  Without that policy assigned they cannot.  

However,  if I make a policy that looks like this:
path "secret/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "secret/super-secret" {
  capabilities = ["deny"]
}

the user assigned to the group has access to all paths starting with "secret/" AND to the path "secret/super-secret"!

   
 On Friday, July 3, 2020, 5:51:47 AM EDT, Peter Gasper <notifications@github.com> wrote:  
 
 


@shallquist
You have to map ldap group (or multiple) to a role in LDAP auth backend:
https://www.vaultproject.io/docs/auth/ldap#ldap-group-policy-mapping

**Comment by toteva** [comment]
Most probably, not relevant anymore, but the ones who ended up here: https://developer.hashicorp.com/vault/api-docs/auth/ldap#**token_policies**

Also, in the LDAP configuration **userattr** has to be set the desired field from LDAP for the user and **username_as_alias** should be set to true.
