### ISSUE TITLE
Best method of authentication while using Hashicorp with Ansible

### ISSUE THREAD

**Issue by chetanchatrath** [hashicorp/vault#6079]
I am looking for the best authentication method while using Hashicorp with Ansible.
I am trying to use Approle for authentication. Now that I have the Role_ID and Secret_id, how can my ansible script read the Token_id and write it in an environment variable so that the playbook can read the token and login into the vault to write data.

Please post questions on the mailing list (https://groups.google.com/forum/#!forum/vault-tool) rather than in GitHub issues.

With over 1700 subscribers, the mailing list gets a _lot_ more eyes on any particular question. You'll get an answer faster, not slower, by taking advantage of the suggestions and answers provided by the wealth of experience that long-time users and devs bring to the list.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!

**Comment by chrishoffman** [comment]
The question would be better answered on the mailing list since there are many users with many different use cases that may be able to help.
