### ISSUE TITLE
probable special character parsing in  databasemiddleware.go

### ISSUE THREAD

**Issue by av82** [hashicorp/vault#6092]
**Describe the bug**

Create a postgres database with username: vaulttest, password: containing special characters '{' or '}' for example 
Vault version: Vault v0.11.0+pro ('3dbec90cdd36c7328690494be876c00fba805f16')

Vault throws an error "error creating database object: unable to parse connection url"
when username or password has special character '{' or '}'

https://github.com/hashicorp/vault/blob/df18871704fe869e9be45b542a6b1eb2fe46c293/builtin/logical/database/dbplugin/databasemiddleware.go#L264

**To Reproduce**
1. Run `vault namespace create dev/`
2. Run `export NS=dev`
3. Run `vault secrets enable \
  -namespace=$NS \
  -path=dynamicsecrets/database/postgres/test \
  database`
3. Run `vault write \
  -namespace=$NS \
  dynamicsecrets/database/postgres/test/config/postgres \
  plugin_name=postgresql-database-plugin \
  allowed_roles="my-role" \
  connection_url="postgresql://{{username}}:{{password}}@YOUR_URL:5432/postgres" \
  username="vaulttest" \
  password="6abMc*{DE*f1YPNyU"

**Expected behavior**
setup postgres plugin at the mount path that was setup

**Environment:**
* Version         0.11.0+pro:
* Vault v0.11.0+pro ('3dbec90cdd36c7328690494be876c00fba805f16'):
* Ubuntu:

**Additional context**

**Comment by jefferai** [comment]
Apologies, but we need to ask you to reach out to HashiCorp Support -- all support requests for enterprise customers need to start there.

**Comment by av82** [comment]
thanks @jefferai

**Comment by jurgenweber** [comment]
I have this problem but with a '^' in the password, how do you resolve it?

**Comment by mrWinston** [comment]
Hey @jurgenweber 
What escaping did you try? We've had the same problem with curly braces `}{` in the password field and vault version 1.1.3. 
What did the trick was to urlencode the password.

**Comment by jurgenweber** [comment]
I don't recall now, it was a long time ago. :\
I must of resolved it somehow since I moved on.
