### ISSUE TITLE
Can we use YAML file to write in the Hashicorp vault

### ISSUE THREAD

**Issue by chetanchatrath** [hashicorp/vault#6093]
Hi All,
I wanted to check if Hashicorp vault has started supporting YAML files for input using Vault CLI. It was mentioned in the below link that it would not be supported but wanted to confirm if this feature has been added and if we can use vault cli to pass YAML file.

https://github.com/hashicorp/vault/issues/1738 

Please post questions on the mailing list (https://groups.google.com/forum/#!forum/vault-tool) rather than in GitHub issues.

With over 1700 subscribers, the mailing list gets a _lot_ more eyes on any particular question. You'll get an answer faster, not slower, by taking advantage of the suggestions and answers provided by the wealth of experience that long-time users and devs bring to the list.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!

**Comment by jefferai** [comment]
As the text says, please use the mailing list for questions.
