### ISSUE TITLE
No value found at transit/backup/KEY

### ISSUE THREAD

**Issue by shebanian** [hashicorp/vault#6097]
**Describe the bug**
We have a transit key in our current vault and we can't make a backup of the key.
We wanted to make a backup in our current vault and restore it to a new version of vault running on another cluster.

We connect to the vault and set the parameters of our key $KEYNAME
```
vault write transit/keys/$KEYNAME/config allow_plaintext_backup=true
```
AND
```
vault write transit/keys/$KEYNAME/config exportable=true
```
Then we read the key
```
vault read --format=json transit/keys/$KEYNAME
```
We get the response we suspected
```
Handling connection for 8200
{
  "request_id": "4e71d970-4920-b6ca-f278-3442b1a5ea56",
  "lease_id": "",
  "lease_duration": 0,
  "renewable": false,
  "data": {
    "deletion_allowed": false,
    "derived": false,
    "exportable": true,
    "keys": {
      "1": ************
    },
    "latest_version": 1,
    "min_decryption_version": 1,
    "min_encryption_version": 0,
    "name": "$KEYNAME",
    "supports_decryption": true,
    "supports_derivation": true,
    "supports_encryption": true,
    "supports_signing": false,
    "type": "aes256-gcm96"
  },
  "warnings": null
}

```

Than we call the backup endpoint
```
vault read --format=json transit/backup/$KEYNAME
```
Response
```
No value found at transit/backup/$KEYNAME
```

**Expected behavior**
A json format dump of the key which we can send to a restore endpoint.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
Version         0.8.3
* Vault CLI Version (retrieve with `vault version`):
Vault v1.0.1 (cgo)
* Server Operating System/Architecture:
EC2 instance at AWS

**Comment by chrishoffman** [comment]
Transit backup/restore was added in Vault 0.9.1 and is not available in the version you are running.  It is always recommended to upgrade to get the latest security and bug fixes.
