### ISSUE TITLE
Vault splits PostgreSQL policies on literal semicolons, breaking block statement

### ISSUE THREAD

**Issue by noidic** [hashicorp/vault#6098]
This is propably a regression, a similar issue was already fixed: #1619

I have the following json document to define a PostgreSQL database role:

```{
  "db_name": "${DBNAME}",
  "creation_statements": ["CREATE USER \"{{name}}\" WITH ENCRYPTED PASSWORD '{{password}}'",
                          "GRANT ALL PRIVILEGES ON DATABASE ${DBNAME} TO \"{{name}}\"",
                          "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO \"{{name}}\"",
                          "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA PUBLIC TO \"{{name}}\"",
                          "GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA PUBLIC TO \"{{name}}\"",
                          "DO \$\$BEGIN
                               FOR r IN
                               select 'ALTER TABLE \"' || table_schema || '\".\"' || table_name || '\" OWNER TO ' ||  \"{{name}}\" || ';' as a from information_schema.tables where table_schema = \"public\"
                               union all
                               select 'ALTER TABLE \"' || sequence_schema || '\".\"' || sequence_name || '\" OWNER TO ' ||  \"{{name}}\" || ';' as a from information_schema.sequences where sequence_schema = \"public\"
                               union all
                               select 'ALTER TABLE \"' || table_schema || '\".\"' || table_name || '\" OWNER TO ' ||  \"{{name}}\" || ';' as a from information_schema.views where table_schema = \"public\"
                               union all
                               select 'ALTER FUNCTION \"'||nsp.nspname||'\".\"'||p.proname||'\"('||pg_get_function_identity_arguments(p.oid)||') OWNER TO ' ||  \"{{name}}\" || ';' as a from pg_proc p join pg_namespace nsp ON p.pronamespace = nsp.oid where nsp.nspname = \"public\"
                               union all
                               select 'ALTER SCHEMA \"' || \"public\" || '\" OWNER TO ' ||  \"{{name}}\" union all select 'ALTER DATABASE \"' || ${DBNAME} || '\" OWNER TO ' ||  \"{{name}}\";
                               LOOP EXECUTE
                                    r.a;
                               END LOOP;
                           END\$\$;"],
  "default_ttl": "24h",
  "max_ttl": "24h"
}
```

The role is created, upon usage the database throws the following error:

unterminated dollar-quoted string at or near "$$BEGIN                               FOR r IN                               select 'ALTER TABLE "' || table_schema || '"."' || table_name || '" OWNER TO ' ||  "v-kubernet-keycloak-3E77ZGEvrwP01jtttfMj-1548335922" || '" at character 4

Seems as if vault splits the block statement into several statements on each semicolon, which is not good for block statements obviously.

The same behaviour was mentioned in #1619 and presumably fixed, but as far as i know that was the PostgreSQL module back then while I'm working with the database module (using vault 1.0)

**Comment by jefferai** [comment]
You can use one of the other methods of providing the statements to provide an encoded value; see https://www.vaultproject.io/api/secret/databases/postgresql.html#parameters-1

**Comment by noidic** [comment]
I can't get it to work. I've tried encoding all the statements or just the block statement with base64, then nothing gets decoded and PostgreSQL tries to execute the encoded string as sql statement (which of course fails). Putting it all in one string also fails (statements get seperated at the semicolons again). Maybe I'm just to dumb to understand it right.

Can maybe someone provide me with a more elaborate description what to do here to get these statements to work?

Thanks!

**Comment by jefferai** [comment]
You didn't give an example of what you're doing, but I'd try putting each statement into an entry in a json array and passing that.

**Comment by jefferai** [comment]
Note that it says character 4 is where it has the issue. In the example you linked to in #1619 the `$$` isn't escaped, and that would correspond to `DO \$` -- the backslash would be char 4. Can you try not escaping the `$$`?

**Comment by noidic** [comment]
Yes, it mentions character 4 whicht is the $$. The escaping is resolved in script execution, if I omit the backslashes the $$ ist taken as input parameter and weird things happen. The text send to PostgreSQL is correct for that matter.
The error is located there because it's the beginning of the dollar quoted statement for which no terminating $$ is found (because of the splits). I verfified this with a single statement inside a dollar quotetd statement escaped like in the example and it works.

**Comment by noidic** [comment]
Maybe someone has a solution to the underlying task without using a block statement to work around this problem.
What I need to archive is to change ownership of the database and all tables, sequences and functions in this database to the new user. That is because the application using this database is doing some operations requiring ownership and I'm not in control of the application.
Besides from that, the objects in the database are created by the application on it's first start, so the first user it gets from vault can never be deleted by vault unless ownership is changed.

**Comment by adamhosier** [comment]
i'm having a similar issue. i create a role & the creation statements get parsed correctly
```bash
» vault read --format json database/roles/foo
{
  "request_id": "5977ed1f-aac3-21ab-34bd-a07c6f1a1833",
  "lease_id": "",
  "lease_duration": 0,
  "renewable": false,
  "data": {
    "creation_statements": [
      "DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname='my_role') THEN CREATE ROLE my_role; END IF; END $$",
      "CREATE USER '{{name}}' IDENTIFIED BY '{{password}}' VALID UNTIL '{{expiration}}'",
      "GRANT my_role TO '{{name}}'"
    ],
    "db_name": "my_db",
    "default_ttl": 0,
    "max_ttl": 0,
    "renew_statements": [],
    "revocation_statements": [],
    "rollback_statements": []
  },
  "warnings": null
}
```

then when i attempt to create credentials for this role i get:
```bash
» vault read database/creds/foo
Error reading database/creds/foo: Error making API request.

URL: GET https://my-vault-instance.com/v1/database/creds/foo
Code: 500. Errors:

* 1 error occurred:
	* pq: unterminated dollar-quoted string at or near "$$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname='my_role') THEN CREATE ROLE my_role"
```

seems like the statements are parsed a second time in the postgresql plugin: https://github.com/hashicorp/vault/blob/master/plugins/database/postgresql/postgresql.go#L137

**Comment by mrburrito** [comment]
I'm having this exact same problem trying to define a trigger function to change ownership of database objects on create. This is insanely frustrating. How soon will a fix be released?

**Comment by ncabatoff** [comment]
@mrburrito Is a stored procedure a possible workaround for you?

**Comment by mrburrito** [comment]
No. I have no simple way of creating the stored procedure right now due to access restrictions in the database and how terraform, vault, and RDS are all interacting. Trying some of the other workarounds suggested on this ticket.

**Comment by mrburrito** [comment]
I'm trying to use the terraform_vault_provider's [vault_database_secret_backend_role](https://www.terraform.io/docs/providers/vault/r/database_secret_backend_role.html) resource to configure this role in vault. How do I pass a JSON array in for `creation_statements`?

If I try to pass an array in terraform, it complains it has to be a string value. If I use `jsonencode` to encode the array as a JSON string, `creation_statements` ends up being an array containing the serialized array rather than deserializing the JSON string.

`vault read -format json postgres/roles/myrole`
```json
{
  "...": "...",
  "data": {
    "creation_statements": [
      "[\"RESET ROLE;\",\"GRANT \\\"myrole\\\" TO \\\"rds_master_user\\\";\",...]"
    ]
  }
}
```

Expected:
```json
{
  "...": "...",
  "data": {
    "creation_statements": [
      "RESET ROLE;",
      "GRANT \"myrole\" TO \"rds_master_user\";",
      "..."
    ]
  }
}
```

**Comment by mrburrito** [comment]
Ok. Figured out a solution that works in this scenario...

A base64 encoded JSON array passed from the terraform provider to vault will behave correctly and vault executes the function creation block statement with no problems!

##### terraform
```hcl
locals {
  create_statements = [
      "RESET ROLE;",
      "GRANT \"myrole\" TO \"rds_master_user\";",
      "CREATE OR REPLACE FUNCTION myfunc AS $$$$ BEGIN ... END; $$$$ LANGUAGE pgplsql;",
      "..."
  ]
}

resource "vault_database_secret_backend_role" "myrole" {
  backend = "postgres"
  name = "myrole"
  db_name = "mydatabase"
  default_ttl = "3600"
  max_ttl = "3600"
  creation_statements = "${base64encode(jsonencode(local.create_statements))}"
}
```

**Comment by jefferai** [comment]
Yep! We support that for exactly this reason -- you can actually pass in statements in four different ways, see https://www.vaultproject.io/api/secret/databases/postgresql.html#creation_statements

**Comment by mrburrito** [comment]
Yep. I think my issue is more with the lack of intuitive configuration and/or documentation in the terraform provider. Once I figured that out, vault worked perfectly.

**Comment by JasonIamAUnixAdmin** [comment]
hey @mrburrito I'm trying to use your workaround (thank you for that btw) but I can't get terraform to see it as valid. I keep getting:
```
Inappropriate value for attribute "creation_statements": list of string
required.
```
TF is 0.12.12
AWS provider is 2.40.0
Vault provider is 2.6.0

**Comment by mrburrito** [comment]
@JasonIamAUnixAdmin were still using 0.11 so I’m not sure if the same thing works with 0.12. Might be a better way now?

**Comment by JasonIamAUnixAdmin** [comment]
> @JasonIamAUnixAdmin were still using 0.11 so I’m not sure if the same thing works with 0.12. Might be a better way now?

Sadly not that I see. We actually had this working in 0.11 world and part of a 0.12 upgrade I'm in the middle of broke it. Seems that it is even more stringent now.

**Comment by catsby** [comment]
Hello! Terraform v0.12 was a major update, there are likely some additional steps or changes needed to configuration files. Specifically, an updated version of the HCL language is used in v0.12. See the blog and upgrade guide links below:

- https://www.hashicorp.com/blog/terraform-0-1-2-preview/
- https://www.terraform.io/upgrade-guides/0-12.html

Please let us know if that helps!

**Comment by JasonIamAUnixAdmin** [comment]
> Hello! Terraform v0.12 was a major update, there are likely some additional steps or changes needed to configuration files. Specifically, an updated version of the HCL language is used in v0.12. See the blog and upgrade guide links below:
> 
> * https://www.hashicorp.com/blog/terraform-0-1-2-preview/
> * https://www.terraform.io/upgrade-guides/0-12.html
> 
> Please let us know if that helps!

Sadly no. There is no mixing of escapes that makes it pass and post correctly.

**Comment by mattlord** [comment]
> Yep. I think my issue is more with the lack of intuitive configuration and/or documentation in the terraform provider. Once I figured that out, vault worked perfectly.

Too bad that I cannot +1000000 this :)

**Comment by kenske** [comment]
@JasonIamAUnixAdmin Were you ever able to figure this out? Currently running into this same issue.

**Comment by JasonIamAUnixAdmin** [comment]
> @JasonIamAUnixAdmin Were you ever able to figure this out? Currently running into this same issue.

I'm sorry I've not thought about this for 3 years. We ripped Vault out not long after thanks to not wanting to fight this and our cloud provider secrets meeting out needs. 

If you aren't yet on the 1.x series of TF do that and you can use newer providers which often fix grief.
