### ISSUE TITLE
Error revoke approle mysql  credentials

### ISSUE THREAD

**Issue by kevinvirs** [hashicorp/vault#6100]
**Describe the bug**
When manual delete approle entity, mysql lease  don't revoke and has negative ttl

**To Reproduce**
1. Login with approle
2. Get credentials for mysql
3. Delete approle entity from ui
4. Revoke/force revoke prefix manually has error:

* Error
There was an error attempting to revoke the prefix: mysql/. failed to revoke "mysql/creds/readonly/7IFRESvMrAQCeVXZ13u8hCJf" (1 / 1): failed to revoke entry: resp: (*logical.Response)(nil) err: Error 1269: Can't revoke all privileges for one or more of the requested users. 

**Expected behavior**

/leases/mysql/creds/readonly/7IFRESvMrAQCeVXZ13u8hCJf

Leases
Issue time
Jan 24, 2019 05:32:30 PM
2019-01-24T17:32:30.519941788+07:00
Expiration time
Jan 24, 2019 06:05:23 PM
2019-01-24T18:05:23.761137135+07:00
Expires in
about 22 hours
TTL
-77540

**Environment:**
* vault status:
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.0.2
Cluster Name    vault-cluster-52de12da
Cluster ID      21a04114-0394-9135-8a0b-1ef0ac69def2
HA Enabled      true
HA Cluster      https://ip:8201
HA Mode         active

* vault version:
Vault v1.0.2 ('37a1dc9c477c1c68c022d2084550f25bf20cac33')
* Server Operating System/Architecture:
4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux

Vault server configuration file(s):

```hcl
storage "consul" {
    address = "127.0.0.1:8501"
    datacenter = "dc"
    path = "vault"
    scheme = "https"
    tls-skip-verify  = "true"
    token = "_token_"
    tls_cert_file = "/etc/ssl/service.cert"
    tls_key_file = "/etc/ssl/service.key"
    tls_ca_file = "/etc/ssl/ca.cert"
    }

ui = true

listener "tcp" {
    address = "0.0.0.0:8200"
    cluster_address = "0.0.0.0:8201"
    tls_cert_file = "/etc/ssl/service.cert"
    tls_key_file = "/etc/ssl/service.key"
    tls_disable = 0
    }
```

**Additional context**
mysql> select * from user;
 %             | v-read-a8MhRLr8o | *B462B112E1633D5E854CBAA5ADFAEAD2003741AF

**Comment by jefferai** [comment]
> Error 1269: Can't revoke all privileges for one or more of the requested users

This error is coming from MySQL, not Vault. You may need to check your configured revocation statements.

**Comment by jefferai** [comment]
See https://www.vaultproject.io/api/system/leases.html#revoke-force

**Comment by kevinvirs** [comment]
Not working :) see first post
    Revoke/force revoke prefix manually has error:
    Error
    There was an error attempting to revoke the prefix: mysql/. failed to revoke "mysql/creds/readonly/7IFRESvMrAQCeVXZ13u8hCJf" (1 / 1): failed to revoke entry: resp: (*logical.Response)(nil) err: Error 1269: Can't revoke all privileges for one or more of the requested users.

**Comment by jefferai** [comment]
What is the exact command you are using?

**Comment by kevinvirs** [comment]
![scr](https://user-images.githubusercontent.com/47024525/51814266-2a131d00-22ed-11e9-8cae-eeb9495d9e9b.png)

**Comment by jefferai** [comment]
Try from the CLI please, in case it's a UI bug

**Comment by kevinvirs** [comment]
Now i don't have invalid leases. I'm will wrote later, when it will be affected again.
