### ISSUE TITLE
LDAP rebind after authenticating does not allow listing groups with Google Cloud Identity

### ISSUE THREAD

**Issue by ajholyoake** [hashicorp/vault#6111]
**Describe the bug**
Groups information can not be retrieved form the google secure ldap service 

**To Reproduce**
1. Set up an stunnel to the google ldap instance
config:
```
[ ldap_vault ]
accept = 1636
cert = /usr/local/etc/stunnel/tls/ldap_vault.crt
ciphers = EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:+CAMELLIA256:+AES256:+CAMELLIA128:+AES128:+SSLv3:!aNULL!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!ECDSA
client = yes
connect = ldap.google.com:636
key = /usr/local/etc/stunnel/tls/ldap_vault.key
options = cipher_server_preference
sslVersion = all
verifyChain = no
verifyPeer = no
``` 

2.  Set up the vault ldap auth backend
```
vault auth enable ldap
vault write auth/ldap/config \
    url="ldap://localhost:1636" \
    binddn='USERNAME'\
    bindpass='PASSWORD'\
    userdn="ou=Users,dc=domain,dc=com" \
    groupdn="ou=Groups,dc=domian,dc=com"\
    groupfilter="(memberUid={{.Username}})"\
    userattr="uid"
vault write auth/ldap/groups/sre policies=operators
vault login -method=ldap username=aholyoake

```

2. Enter password
3. No groups are found.
```
2019-01-26T10:59:47.393Z [DEBUG] auth.ldap.auth_ldap_58ff7e6a: searching: groupdn=ou=Groups,dc=domain,dc=com rendered_query=(memberUid=aholyoake)
2019-01-26T10:59:47.949Z [DEBUG] auth.ldap.auth_ldap_58ff7e6a: groups fetched from server: num_server_groups=0 server_groups=[]
```

**Expected behavior**
Appropriate groups should be returned

**Environment:**
* Vault Server Version 1.0.2
* Vault CLI Version latest master and 0.9.5
* Server Operating System/Architecture:
Debian x86/64 and MacOS (and combinations thereof)

Vault server configuration file(s):
running a dev server off master

**Additional context**
All appropriate ldapsearch commands work.

I managed to get this to work by closing the connection after user authentication has happened and reopening it before the rebind using the binddn and bindpass  in vault/builtin/credential/ldap/backend.go line 117	
```
        c.Close()
	c, err = ldapClient.DialLDAP(cfg)
	defer c.Close()
```

This is affecting more than one person:
https://groups.google.com/forum/#!searchin/vault-tool/ldap%7Csort:date/vault-tool/ZXrXwIu0FUM/atTz8NL4FgAJ

**Comment by agershman** [comment]
I've thought about this too, and have to think this may lean more on a difference with this single connection double bind against Google's implementation. I say this because the same semantics appear to work fine with something like Active Directory. We've noticed a bug on the Google side with respect to the enabling of groups read privileges. Assuming the nothing out of the ordinary is happening in the Vault LDAP client implementation, I'm thinking this is something that either Google needs to consider supporting or Vault note that Google secure LDAP is not supported.

**Comment by tdgeery** [comment]
I am also running into this issue now.

**Comment by igoratencompass** [comment]
Crossposting here from issue #4359 

Based on what I can see in the OpenLDAP server logs the issue, at least in my case, is that the group membership query is performed with bind as the user trying to login instead of the `binddn` user from the config. The error is legit and the search really returns object not found (err=32):
```
Jul 18 16:50:41 server slapd[3272]: conn=3410195 op=2 SRCH attr=cn
Jul 18 16:50:41 server slapd[3272]: conn=3410195 op=2 SEARCH RESULT tag=101 err=32 nentries=0 text=
```
This is exactly the error that OpenLDAP returns when I try to query for group membership as the `user` instead of the `binddn` user:
```
Enter LDAP Password: 
No such object (32)
```

**Comment by stephenrjohnson** [comment]
Is there an update/workaround for this?

**Comment by igoratencompass** [comment]
FWIW this worked for me after explicitly setting up `discoverdn=false` in the config.

**Comment by yannrouillard** [comment]
I am also hit it by this bug.
Weirdly on the Google LDAP side I see this in the logs (from more recent to oldest):


|                                Event Description                                 |    Event Name     |   User    |
| :------------------------------------------------------------------------------: | :---------------: | :-------: |
| LDAP search with (&(objectClass=inetOrgPerson)(uid=_TEST_USER_UID_)) successful. | Search successful | Test User |
|                       LDAP bind with _BIND_DN_ successful.                       |  Bind successful  | Test User |
|    LDAP bind with uid=_TEST_USER_UID_,ou=Users,dc=_DOMAIN_  successful. | Bind successful  |  Test User |

The User is always displayed as being my Test User even when the second bind was done as the BIND_DN user, so I wonder if there is something wrong on Google side.
(The initial successful bind as _BIND_DN_ doesn't show any user in the User field)

**Comment by yannrouillard** [comment]
FYI, I was also able to workaround the bug using the solution given by @ajholyoake
https://github.com/yannrouillard/vault/commit/a51690dfceb3493a95f635f0b2e3da08b03ef3c3

**Comment by rodrigorato** [comment]
Is there a status progress on this? 😢

**Comment by michelvocks** [comment]
Hi @rodrigorato!

Please see https://github.com/hashicorp/vault/pull/7578. We are currently waiting for the PR owner to address the required feedback.

Cheers,
Michel

**Comment by tyrannosaurus-becks** [comment]
This is closed by https://github.com/hashicorp/vault/pull/8365 and will go out with Vault 1.4.0 GA.
