### ISSUE TITLE
LDAP Search Alias Dereferencing

### ISSUE THREAD

**Issue by hExPY** [hashicorp/vault#6128]
**Is your feature request related to a problem? Please describe.**
We're running a LDAP structure which consists of an OU with aliases pointing to a different OU with CN groups as child. When Vault is doing a group lookup it's not dereferencing aliases.
As an example we need dereferencing 'always' or 'search'

**Describe the solution you'd like**
I'd like to configure the dereferencing behavior in the backend configuration. 

**Describe alternatives you've considered**
I don't know an alternative yet.

**Explain any additional use-cases**
It may be useful if someone would like to configure it very precisely which groups should be returned by LDAP.

**Additional context**
I found the plugin and file where this option may be passed to the client.
https://github.com/hashicorp/vault/blob/master/vendor/github.com/go-ldap/ldap/search.go#L82-L95
Sadly I'm not GO experienced enough to create a merge request including this specific configuration parameter. I also wasn't able to find this option in the documentation. Maybe it's already configurable but not listed yet. https://www.vaultproject.io/docs/auth/ldap.html#group-membership-resolution

**Comment by hsimon-hashicorp** [comment]
Closing as implemented in #18230
