### ISSUE TITLE
LDAP Auth ARM

### ISSUE THREAD

**Issue by phillebaba** [hashicorp/vault#6135]
**Describe the bug**
There seems to be an issue with LDAP authentication that will only occur when running Vault on an ARM platform. When authenticating the following will be logged in the Vault server.
```
ldap: recovered panic in processMessages: runtime error: invalid memory address or nil pointer dereference
auth.ldap.auth_ldap_45025234: error getting user bind DN: error="LDAP bind (service) failed: LDAP Result Code 200 "Network Error": ldap: response channel closed"
```

I have verified that this issue is related to the architecture as I have followed the same setup steps on an x86 machine using the same LDAP server, without any issue.

Looking around it seems like the issue may come from the [go-ldap](https://github.com/go-ldap/ldap) dependency, can it have something to do with [this  issue](https://github.com/go-ldap/ldap/issues/195)?

**To Reproduce**
1. Start Vault Container `docker run --cap-add=IPC_LOCK -d --name=dev-vault vault`
2. Enable LDAP Auth `vault auth-enable ldap`
3. Configure LDAP
```
vault write auth/ldap/config     
  url="ldaps://<ldap_url>"
  binddn="cn=admin,dc=example,dc=com"
  bindpass="password"
  userdn="ou=users,dc=example,dc=com"
  userattr="cn"
  groupdn="ou=groups,dc=example,dc=com"
  groupattr="cn"
  insecure_tls=true
```
4. Authenticate with Vault `vault login  -method=ldap`

**Expected behavior**
User should authenticate and receive a successful response.

**Environment:**
* Vault Server Version: 1.0.1
* Vault CLI Version: Vault v1.0.2 ('37a1dc9c477c1c68c022d2084550f25bf20cac33')
* Server Operating System/Architecture: Linux (ARM)

**Comment by nlarzon** [comment]
+1

**Comment by jefferai** [comment]
Adding this as a 1.0.3 item to update the LDAP dep.
