### ISSUE TITLE
aws iam auth is failing to verify the EC2 region 

### ISSUE THREAD

**Issue by playersons** [hashicorp/vault#6139]
**Describe the bug**
When configuring an auth/aws role with auth_type=IAM, inferred_entity_type=ec2_instance and inferred_aws_region=eu-central-1, auth requsts from ec2 instances are failing with the error

`failed to verify i-03be12eb257f2e456 as a valid EC2 instance in region eu-central-1
` 

**To Reproduce**
1. Run `vault write auth/aws/role/some-role inferred_entity_type=ec2_instance inferred_aws_region=eu-central-1`
2. Run `vault login -method=aws header_value=FQDN_of_vault_server role=some-role`
3. See error

**Expected behavior**
The usual response delivering the client_token, as is perfectly working when using IAM without infering EC2 instances.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.2
* Vault CLI Version (retrieve with `vault version`): 1.0.2
* Server Operating System/Architecture: CentOS Linux release 7.6.1810 x86_64

Vault server configuration file(s):

```hcl
storage "file" {
  path = "/opt/vault/data"
}

listener "tcp" {
 address = "FQDN_vault_server:8200"
 tls_cert_file = "/path/to_chain_bundle_with_cert"
 tls_key_file = "/path/to/privkey.pem"
}
```

aws auth role configuration:

```
vault read auth/aws/role/salting-role
Key                               Value
---                               -----
allow_instance_migration          false
auth_type                         iam
bound_account_id                  []
bound_ami_id                      []
bound_ec2_instance_id             [i-03be12eb257f2e456]
bound_iam_instance_profile_arn    [arn:aws:iam::031234567851:instance-profile/airflow-instance-profile-staging]
bound_iam_principal_arn           [arn:aws:iam::031234567851:role/airflow_s3_ro_access_staging_role]
bound_iam_principal_id            [AR1234567890123456E7I]
bound_iam_role_arn                []
bound_region                      []
bound_subnet_id                   []
bound_vpc_id                      []
disallow_reauthentication         false
inferred_aws_region               eu-central-1
inferred_entity_type              ec2_instance
max_ttl                           1h
period                            0s
policies                          [default salt]
resolve_aws_unique_ids            true
role_tag                          n/a
ttl                               0s
```

**Comment by rob-orr** [comment]
I'm running Vault server and CLI `1.2.2` and am experiencing the same issue as described above.  I'm running an Ubuntu instance in `us-east-1` (but in a different subnet than Vault), and am seeing the same error as above.

**Comment by tyrannosaurus-becks** [comment]
Hi @playersons ! Question, what would happen if you tried `vault login -method=aws header_value=FQDN_of_vault_server role=some-role region=eu-central-1`? Am I right in assuming that the client machine is also located in that region, or is it elsewhere?

**Comment by spangenberg** [comment]
Hello! We haven't heard back regarding this issue in over 30 days. In an effort to try and keep our GitHub issues current, we'll be closing this issue in approximately 7 days if we do not hear back regarding this issue. Please let us know if you can still reproduce this issue, and if there is any more information you could share, otherwise we'll be closing this issue around February 4th, 2020

**Comment by spangenberg** [comment]
Closing for now. Feel free to comment on this issue or to open a new one.
