### ISSUE TITLE
Architecture question

### ISSUE THREAD

**Issue by Losiara** [hashicorp/vault#614]
Created "hello world" with getting started article. And misunderstood something. After init of  backend ("file" in my case) there are created files with some keys in "core" and "sys" dirs. They are saved as plain text. Is it ok to keep them in untrusted storage? Are they like public keys?

**Comment by jefferai** [comment]
I'm not sure which files you're talking about, specifically, but any secrets stored by Vault are encrypted before storage. You can list which files you're talking about, if you like, but they're likely administrative files that Vault needs for information relevant to the unsealing process.

For instance, Vault's master key is stored in the backing store, but it's encrypted with the keys output during the initialization process. The actual plaintext key is never written to disk.

**Comment by Losiara** [comment]
I was confused by these files:
path2mystorage/core/_audit (_keyring, _master, _mounts etc)
path2mystorage/sys/_salt
path2mystorage/sys/_id/_blabla......bla
They seemed to be not encrypted or I am wrong?

**Comment by jefferai** [comment]
They are encrypted.

**Comment by Losiara** [comment]
Thank you!
