### ISSUE TITLE
logical/framework: OptionalParamRegex is no longer optional if preceded by GenericNameRegex

### ISSUE THREAD

**Issue by syadav2015** [hashicorp/vault#6160]
**Describe the bug**
OptionalParamRegex by definition should be an optional named parameter from the URL however the parameter becomes mandatory if preceded by framework.GenericNameRegex().

Sample pattern: "a/b/" + GenericNameRegex("val") + OptionalParamRegex("val2")

**To Reproduce**
Added the following test case to logical/framework/path_test.go
```
diff --git a/logical/framework/path_test.go b/logical/framework/path_test.go
index c3ccb2a56..8e5cf0b6f 100644
--- a/logical/framework/path_test.go
+++ b/logical/framework/path_test.go
@@ -55,6 +55,12 @@ func TestPath_Regex(t *testing.T) {
                        pathMatch: true,
                        captures:  map[string]string{"val": "foo"},
                },
+               {
+                       pattern:   "a/b/" + GenericNameRegex("val") + OptionalParamRegex("val2"),
+                       input:     "a/b/foo",
+                       pathMatch: true,
+                       captures:  map[string]string{"val": "foo"},
+               },
                {
                        pattern:   "foo/" + MatchAllRegex("val"),
                        input:     "foos/ball",
```
Running the tests for the package results in a failure:
```
bash-3.2$ go test ./...
--- FAIL: TestPath_Regex (0.00s)
    path_test.go:100: [map[val2]:  != <does not have key>]
FAIL
FAIL	github.com/hashicorp/vault/logical/framework	0.111s
```

**Expected behavior**
The test should pass since according to [another existing test case](https://github.com/hashicorp/vault/blob/master/logical/framework/path_test.go#L47) in the same test file, path should match if OptionalParamRegex is not present in the URL. Similarly `a/b/foo` should also have matched the pattern `"a/b/" + GenericNameRegex("val") + OptionalParamRegex("val2")` with val capturing foo.

**Environment:**
Reproducible using the latest release of logical/framework accessible using go get as well as the master branch of git repo for vault as well (last commit 0377c83).

I'm happy to clarify any questions regarding this issue.

**Comment by jefferai** [comment]
I think you need a slash between them.

**Comment by syadav2015** [comment]
> I think you need a slash between them.

I don't think that's correct. The [code for framework.OptionalParamRegex](https://github.com/hashicorp/vault/blob/master/logical/framework/path.go#L29) indicates / is already included in the regex. Furthermore, [one of the other test cases in the same file](https://github.com/hashicorp/vault/blob/master/logical/framework/path_test.go#L47) does not have a / between the prefix and framework.OptionalParamRegex.

**Comment by jefferai** [comment]
The test is correct. The named capture exists whether it's filled in with anything or not. The final line should be `captures:  map[string]string{"val": "foo", "val2": ""},`

**Comment by syadav2015** [comment]
It seems like the test works fine with the suggestion. But in the test plugin, after setting up the path in the following method, my plugin still returns an `error occurred: * unsupported path "` for LIST, GET and POST calls against the API endpoint `/testapi/foo`, however `/testapi/foo/bar` works fine and the correct methods get called. Am I missing something here?

```
func pathAPI(b *backend) *framework.Path {
        return &framework.Path{
                Pattern: "testapi/" + framework.GenericNameRegex("val1") + framework.OptionalParamRegex("val2"),
                Fields: map[string]*framework.FieldSchema{
                        "val1": {
                                Type:        framework.TypeString,
                                Description: "val1.",
                        },
                        "val2": {
                                Type:        framework.TypeString,
                                Description: "val2.",
                        },
               },
                Operations: map[logical.Operation]framework.OperationHandler{
                        logical.ReadOperation: &framework.PathOperation{
                                Callback: b.Read,
                        },
                        logical.UpdateOperation: &framework.PathOperation{
                                Callback: b.Write,
                        },
                        logical.ListOperation: &framework.PathOperation{
                                Callback: b.List,
                        },
                },
                HelpSynopsis:    helpSummary,
                HelpDescription: helpDesc,
        }
}
```

**Comment by jefferai** [comment]
List paths by definition end in / -- it's forced in the http handler code -- so using GenericNameRegex, which doesn't require a `/` at the end, will not register a pattern that works. (This is the reason that most backends have separate paths registered for listing.) You'll need to figure out some other way to handle that, likely by modifying the regexes (remember, those calls just return plain strings that are regexes, they're nothing special).
