### ISSUE TITLE
Implement default policies for authentication backends

### ISSUE THREAD

**Issue by viralpoetry** [hashicorp/vault#6166]
I am using LDAP auth backend to authenticate user in Vault, but I do not send any LDAP groups back, so once the user is authenticated, I cannot assign some dafault policy only related to the users authenticated with a given auth method.

Alternative I currently use is to modify default policy for the whole vault, but as I am using multiple auth methods, this does not scale.

It would be nice to have ability to set some default auth backend policy that will be assigned to every user successfully authenticated with the given backend.

Thanks,
Peter

**Comment by jefferai** [comment]
This is coming, currently planned for 1.1.

**Comment by zx8** [comment]
Discovered this issue after asking the same question on Gitter. ([link](https://gitter.im/hashicorp-vault/Lobby?at=5cb44c29759abc043cc4bd23))

@jefferai Did this land in 1.1 in the end? Can't seem to find anything in the changelog/docs to indicate that it did.

**Comment by jefferai** [comment]
It did not.

**Comment by raoofm** [comment]
this would be a very good feature

**Comment by jefferai** [comment]
This landed in 1.2.
