### ISSUE TITLE
init format JSON lacking

### ISSUE THREAD

**Issue by holybit** [hashicorp/vault#6168]
The JSON dump from an init using Keybase is not consumable by any downstream tools for unseal automation.

Imagine an `init` as follows:

```shell
$ /usr/local/bin/vault operator init -key-threshold=3 \
                                   -key-shares=3 \
                                   -pgp-keys="keybase:user1,keybase:user2,keybase:user3" \
                                   -format=json
```

JSON output:

```json
{
  "unseal_keys_b64": [
    "wcFMAzJ7Hy...",
    "wcFMA6KVQY...",
    "wcFMAxgWZk..."
  ],
  "unseal_keys_hex": [
    "c1c14c0332...",
    "c1c14c03a2...",
    "c1c14c0318..."
  ],
  "unseal_shares": 3,
  "unseal_threshold": 3,
  "recovery_keys_b64": [],
  "recovery_keys_hex": [],
  "recovery_keys_shares": 5,
  "recovery_keys_threshold": 3,
  "root_token": "foobar"
}
```

Now, save that JSON to 1Password or some other password manager (i.e., it can't go in Vault as that would be a chicken and egg game). The operations team has a simple shell script which hits 1Password and retrieves the JSON to be run by three users on ops team to unseal. How to know which unseal key is for user1? Of course you can't tell. And in the case of Keybase PGP the user will have to authenticate with the Keybase application twice to get the unencrypted unseal key anyways. Is there some security advantage I am missing here?

Would the JSON dump not be more useful if it looked as such:

```json
  "unseal_keys_b64": [
    {
      "user": "user1",
      "key": "wcFMAzJ7Hy..."
    },
    {
      "user": "user2",
      "key": "wcFMA6KVQY...."
    },
    {
      "user": "user2",
      "key": "wcFMA6KVQY...."
    }
  ]
```

**Comment by jefferai** [comment]
Keybase is a nicety done entirely in the CLI. Vault server knows nothing about it, only keys.

The unseal keys come back in the same order as the PGP keys were specified at init time. Generally the keys are then distributed to the various users and they each put it in their password manager. If you want to store them all together, I would suggest adding some metadata in 1PW indicating the order in which the keys were specified (simply copying and pasting the CLI init command should be sufficient).
