### ISSUE TITLE
Okta Authentication Continually Tries to Auto-renew Token

### ISSUE THREAD

**Issue by ecliptik** [hashicorp/vault#6170]
**Describe the bug**
When [Okta Authentication](https://www.vaultproject.io/docs/auth/okta.html) is enabled with MFA and a user it logged into the Vault UI, it continually sends MFA pushes to the [Okta Verify App](https://help.okta.com/en/prod/Content/Topics/Mobile/Okta_Verify_Using.htm) in an attempt to renew the token.

**To Reproduce**
1. Enable Okta authentication per instructions https://www.vaultproject.io/docs/auth/okta.html
2. Require MFA in Okta for user/groups
3. Log into Vault UI with Okta with `username` or `username@domain.com` and approve MFA push to Okta Verify app 
4. Wait a period of time and try to browse Vault UI - Okta Verify app will pop up a message requesting approval, and will continue to do so.

Okta Verify App notifications building up:
![image](https://user-images.githubusercontent.com/1261742/52307139-9e356c80-294e-11e9-99cd-a8882fdedbdf.png)

Vault UI Message that appears even though it seems like it's attempting to auto-renew the token:
![image](https://user-images.githubusercontent.com/1261742/52307178-bad1a480-294e-11e9-8620-44b628c9f2a8.png)

**Expected behavior**
Log into Vault UI using Okta and Okta Verify app - token should stay valid for it's TTL and then request renewal and Okta Verify MFA prompt.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.0.2
Cluster Name    vault-cluster
Cluster ID      cluster-id
HA Enabled      false
```

* Vault CLI Version (retrieve with `vault version`):
```vault version
Vault v1.0.2 ('37a1dc9c477c1c68c022d2084550f25bf20cac33')
```

* Server Operating System/Architecture:
Ubuntu 16.04

Vault server configuration file(s):

```hcl
storage "s3" {
  access_key = "KEY"
  secret_key = "KEY"
  bucket     = "BUCKET"
  region     = "REGION"
}

listener "tcp" {
 address = "0.0.0.0:8200"
 tls_disable = 1
}

ui = true
```

Okta Config:
```
vault read auth/okta/config
Key                Value
---                -----
base_url           okta.com
bypass_okta_mfa    false
max_ttl            24h
org_name           org_name
organization       org_name
ttl                24h
```

**Additional context**
Same issue was happening with Vault v0.11.6.

**Comment by Nklya** [comment]
The same for v1.2.2

**Comment by austingebauer** [comment]
@ecliptik - This issue will be resolved by https://github.com/hashicorp/vault/pull/13950. The token renewal from the Vault UI that's causing the MFA push will now take into account the token's TTL. See the PR for more details.
