### ISSUE TITLE
documentation consul storage backend doc, omission of trailing slash in the path example

### ISSUE THREAD

**Issue by dp-h** [hashicorp/vault#6171]
Missing trailing slash in the `path = vault` configuration block example near the beginning of the Consul Storage Backend documentation: https://www.vaultproject.io/docs/configuration/storage/consul.html

The correct trailing slash(`path = vault/`) is present later one the same documentation page here: 
https://www.vaultproject.io/docs/configuration/storage/consul.html#path

**Comment by briankassouf** [comment]
Feel free to open a PR for this change!

**Comment by tyrannosaurus-becks** [comment]
Closed by https://github.com/hashicorp/vault/pull/6224
