### ISSUE TITLE
consul-template    | 2019/02/05 18:18:50.091425 [WARN] (view) vault.read(logical): vault.read(logical): Get http://127.0.0.1:8200/v1/logical: dial tcp 127.0.0.1:8200: connect: connection refused (retry attempt 1 after "250ms")

### ISSUE THREAD

**Issue by shashankimanage** [hashicorp/vault#6178]
Unable to get the vault from consul template i always get this error 
consul-template    | 2019/02/05 18:18:50.091425 [WARN] (view) vault.read(logical): vault.read(logical): Get http://127.0.0.1:8200/v1/logical: dial tcp 127.0.0.1:8200: connect: connection refused (retry attempt 1 after "250ms")

please help

**Comment by ncabatoff** [comment]
This is being addressed on the mailing list, which is the right place for such questions.
