### ISSUE TITLE
Missing HA information in CLI when using format json/yaml

### ISSUE THREAD

**Issue by parberge** [hashicorp/vault#6179]
**Describe the bug**
HA information missing for `vault status --format=json (or yaml)`

**To Reproduce**
1. Run `vault status --format=json (or yaml)`
2. The HA information is missing from the output
```
$ vault status --format=json
{
  "type": "shamir",
  "initialized": true,
  "sealed": false,
  "t": 3,
  "n": 5,
  "progress": 0,
  "nonce": "",
  "version": "1.0.2",
  "migration": false,
  "cluster_name": "vault-cluster-xxxx",
  "cluster_id": "xxxx",
  "recovery_seal": false
}
```

With default format:
```
$ vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.0.2
Cluster Name    vault-cluster-xxxx
Cluster ID      xxxx
HA Enabled      true
HA Cluster      https://x.x.x.x:xxxx
HA Mode         active
``` 

**Expected behavior**
Expected the same values in the output when using `-format=json` vs `format=table`

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.0.2 ('37a1dc9c477c1c68c022d2084550f25bf20cac33')
* Server Operating System/Architecture: Ubuntu

Vault server configuration file(s):

```hcl
ui = true
storage "consul" {
  address = "127.0.0.1:8500"
  path = "vault/test"
  service = "vault"
}
listener "tcp" {
 address = "0.0.0.0:8200"
 tls_disable = 0
 tls_cert_file = "/etc/pki/tls/vault/cert.pem"
 tls_key_file = "/etc/pki/tls/vault/key.pem"
}
```

**Comment by akshya96** [comment]
Hi @parberge, This issue is fixed and the fix is available from vault versions 1.6 and above.
