### ISSUE TITLE
api should support the same VAULT_* env vars as the vault command

### ISSUE THREAD

**Issue by wwalker** [hashicorp/vault#618]
I would like to build some CLI commands in Go using the Vault API.

The "vault" command understands many VAULT_* env vars, yet the vault/api does not.  e.g.:

Supported by API:

    VAULT_ADDR
    VAULT_TOKEN

Supported by CLI ("vault"):

    VAULT_ADDR
    VAULT_TOKEN
    VAULT_CACERT
    VAULT_CAPATH
    VAULT_CLIENT_CERT
    VAULT_CLIENT_KEY
    VAULT_CONFIG_PATH
    VAULT_DEV
    VAULT_FLAGS
    VAULT_PKG_DIRS
    VAULT_SKIP_VERIFY
    VAULT_VERBOSE_PKITESTS
    VAULT_VERSION

I would think we should at least add API support for (in priority order):

    VAULT_SKIP_VERIFY
    VAULT_CONFIG_PATH
    VAULT_CAPATH
    VAULT_CACERT
    VAULT_CLIENT_CERT
    VAULT_CLIENT_KEY

**Comment by jefferai** [comment]
This should be doable...thanks for the report!

**Comment by jefferai** [comment]
Adding to 0.3 but I fear it may get slipped.

**Comment by wwalker** [comment]
What kind of timeline is 0.3.0?  I might be able to do this.

**Comment by jefferai** [comment]
It's... soon. This will probably slip, unfortunately.
