### ISSUE TITLE
refresh_interval does not display when using cli

### ISSUE THREAD

**Issue by eedwards-sk** [hashicorp/vault#6181]
**Describe the bug**
the `refresh_interval` is not displayed in the CLI output, even though it should be according to https://www.vaultproject.io/docs/secrets/kv/kv-v1.html

**To Reproduce**
1. Write a kv secret to a v1 kv store with a key of `ttl` and a duration value (e.g. `60m`)
2. Read the kv secret using the CLI `vault kv get my-secret-backend/my-secret`

**Expected behavior**
Expected `refresh_interval` to appear in the CLI output.

**Actual behavior**
`refresh_interval` is missing from the CLI output.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.2
* Vault CLI Version (retrieve with `vault version`): 1.0.2
* Server Operating System/Architecture: ubuntu 18.04 x64

**Additional context**
I confirmed that the `lease_duration` is present in the API response, and lease_id is empty, as expected, by curling it directly:

```
{
  "request_id": "e20a3637-6a3a-edc7-2f20-25b80025275f",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 3600,
  "data": {
    "ttl": "1h",
    <other scrubbed keys>
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}
```

Output still does not contain `refresh_interval`:

```
ubuntu@ip-172-31-70-1:~$ sudo -Eu vault vault kv get <scrubbed path to kv1 store>
============ Data ============
Key                      Value
---                      -----
ttl                      1h
<other scrubbed keys>
```

**Comment by jefferai** [comment]
The `vault kv` command doesn't support this. Only `vault read` does. However, it's simply a copy of the `ttl` value; you can use the `ttl` value with either command.

**Comment by eedwards-sk** [comment]
Thanks for the quick response @jefferai but given your explanation isn't this still a valid bug as documentation errata?

The docs clearly show the 'vault kv get' command being demonstrated as supporting it.

**Comment by jefferai** [comment]
I'll get the docs fixed. Thanks for pointing it out!
