### ISSUE TITLE
 how to get all tokens related to an auth backends role like approle/kubernetes?

### ISSUE THREAD

**Issue by raoofm** [hashicorp/vault#6187]
Actually wanted to revoke all tokens for an approle or a kubernetes role and tried to get all tokens first and couldn't find a way.

**Comment by briankassouf** [comment]
You can't get all the tokens but you can revoke all the leases which will revoke all the tokens. The revoke prefix API makes it easy to remove all the tokens for a single mount https://www.vaultproject.io/api/system/leases.html#revoke-prefix where the prefix is `auth/<mount path>/`

**Comment by briankassouf** [comment]
Additionally you can lookup all the token accessors or lookup all the leases. But the revoke prefix is the easiest way to do what you are asking.

**Comment by raoofm** [comment]
@briankassouf thanks.

so its not just on the type of auth but actually we could use 
```/sys/leases/revoke-prefix/auth/approle/role/app1```

**Comment by briankassouf** [comment]
yep!

**Comment by raoofm** [comment]
@briankassouf what could be the issue here, shows unauthroized, got similar for deleting approle secret accessor

```
curl -H "X-Vault-Token: s.wdHI0oAvXWMWWN9M6QtsyeNy" -XPUT https://vault.net/v1/sys/leases/revoke-prefix/auth
{"errors":["failed to revoke \"auth/kubernetes/login/h075744a1ae2df1f581cbeb15b0aa3a9fdc58ee7c1d24fb53cec0e4e84974ef69\" (1 / 73): failed to revoke token: failed to revoke entry: failed to delete lease entry: AccessDenied: Access Denied\n\tstatus code: 403, request id: 0CDD159F58EF7D18, host id: oDB6XcKQ+SFml0sD6WxHtxwsOmU2z+CzFonIXcKcrxrnayX8fhVewbW7UIy2wW1W7zOd4ZRXzIw="]}
```

**Comment by raoofm** [comment]
```
2019-02-08T18:49:07.064Z [ERROR] auth.approle.auth_approle_0113a480.tidy: error tidying global secret IDs: error="failed to delete secret ID accessor entry: failed to delete accessor storage entry: AccessDenied: Access Denied
	status code: 403, request id: BDBE89BA2BBDB63A, host id: tBDJksveXJniMp4hKdGBYknLIBnguZYtFbDf+14IPlmMBZVR4067hOsdRhmk8GE1dVHKOew5mMI="
2019-02-08T18:49:16.359Z [ERROR] expiration: maximum revoke attempts reached: lease_id=auth/approle/role/dev-intrado/secret-id/h882cae994ea9f4736c1a0a01fad4716d7c19fbc83826dc4a87ed2d180afcda1a
```

**Comment by jefferai** [comment]
That 403 is coming from your storage backend, and isn't related to Vault per se. Looks like you have some issue with your access token for whatever your storage backend is.

**Comment by raoofm** [comment]
@jefferai Thanks. yeah i think I don't have proper permissions on the bucket
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": "arn:aws:s3:::vault-data"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::vault-data/*"
        }
    ]
}
```

**Comment by raoofm** [comment]
just to track here I will need s3:DeleteObject
