### ISSUE TITLE
Document Auth <-> Identity alias mappings for each auth method

### ISSUE THREAD

**Issue by meirish** [hashicorp/vault#6189]
I recently saw the following slide in a presentation, and thought an expanded version of it would be a _great_ addition to the docs:

![screen shot 2019-02-07 at 11 22 29 am](https://user-images.githubusercontent.com/39469/52436614-5f342200-2ada-11e9-92b4-5a50cfb23ec4.png)

Basically it would be 💯 to have a list of what entity alias and group aliases in the identity secret engine get created (if any) for each auth method.

**Comment by meirish** [comment]
Looks like this was added in https://github.com/hashicorp/vault/pull/10908 - thanks @mgritter !

**Comment by mgritter** [comment]
Hm, I didn't think that we should cover group aliases too.
