### ISSUE TITLE
Cannot make AJAX calls to HTTP API with Token Header

### ISSUE THREAD

**Issue by joeelizondo** [hashicorp/vault#619]
Running an angular instance on a dev env at localhost:8000 I'm hitting a vault ec2 instance with a consul backend also hosted on ec2, both on their default ports 8200 and 8500 respectively. The problem comes when my app tries a simple read operation using a valid token.

```
$http.get("http://XXXXXX.us-east-1.elb.amazonaws.com:8200/v1/secret" + key_path,
                      {
                          headers: {'X-Vault-Token': token}
                      })
                      .then(function(response) {
                          $scope.data.value = response.data.value;
                      }, onError);
```

Instead of a GET request an OPTIONS request is being initiated and the vault server returns a 405. I've googled around and everyone seems to think this is CORS related, however I'm sending a request from my local host to a ec2 instance and having this problem. So it doesn't seem like CORS to me. It seems more like the problem is the custom 'X-Vault-Token' header that needs to be passed. The browser is sending a preflight request trying to determine if that is a valid header and perhaps its not? Is there some way to modify configuration of vault to allow for the OPTIONS verb as well as modify the allowed headers to include that 'X-Vault-Token' header as acceptable?

**Comment by jefferai** [comment]
`405 Method Not Allowed` is correct -- Vault uses HTTP verbs to know what operation is desired, and OPTIONS is not a supported verb. As you said, you're asking for a GET, but you're sending an OPTIONS.

Probably your client is attempting to find out CORS information, which is done via OPTIONS. There should be a way to turn that behavior off in your client.

**Comment by joeelizondo** [comment]
Ok, it's a bare bones angular request. Does that mean angularjs and probably other javascript libraries that make AJAX calls are not supported by the API?

**Comment by jefferai** [comment]
No, it means that OPTIONS requests are not currently supported by the API. You need to disable this. If you can't directly adjust that in your client, you need to work around it. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests

One way is to set the content-type header to `text/plain`. Vault doesn't currently care or look at the content-type header. Another option would be to put Vault behind a reverse proxy that intercepts OPTIONS requests and returns CORS information.

**Comment by adamdecaf** [comment]
Wouldn't it also work to proxy your web app and vault through a load balancer? That way you aren't exposing vault on the open internet directly (nor dealing with CORS).

**Comment by jefferai** [comment]
@adamdecaf You can do that; keep in mind that if you are decrypting in the LB and then re-encrypting you have a transitive trust issue (if that is a concern in your security policy).

**Comment by adamdecaf** [comment]
@jefferai I wouldn't think that the LB should do any decryption. It can just serve as a proxy.

**Comment by jefferai** [comment]
@adamdecaf It depends which LB you use (and what mode you are using it in). If it supports TCP proxying it doesn't need to do decryption. Not all do; those have to decrypt the stream and then reencrypt it going to the backend.
