### ISSUE TITLE
Feature Request: Failover escrow

### ISSUE THREAD

**Issue by johnnybubonic** [hashicorp/vault#6192]
It'd be great if a token/user/etc. **Alice** could grant their permissions to **Bob** if **Alice** has not performed any (successful) auth attempts in _n_ number of time units (hours, days, weeks, etc.). Obviously this would have to be explicitly enabled by a user with root policy (and, ideally, enforced internally so that Alice couldn't change it), but it allows for an advantage in two key situations:

1.) Granting posthumous access to credentials (useful for domestic situations, e.g. banking credentials)[0]
2.) Preventing disgruntled employee lockout[0][1]

Now, one can (rightfully) point out that a root token could just be used, but this means it requires at least one root token remain unrevoked for situation 2 (which explicitly goes against the suggestions [in the docs](https://www.vaultproject.io/docs/concepts/tokens.html#root-tokens) to revoke root tokens when they are no longer immediately needed), and that it be shared ahead of time for situation 1 (which defeats the purpose of escrow).

Thoughts?

[0] Assuming the vault has not yet been sealed.

[1] There may be the contingency that said bad-actor employee would also seal the vault as well, which is a tough chicken/egg problem to solve for this particular example other than being extremely meticulous with policies - e.g. an operator would have access to nigh everything except the seal path. It also assumes he/she doesn't have shell access to the vault instance's host. But nonetheless.

**Comment by jefferai** [comment]
I don't think you need to keep a root token unrevoked. Just use a higher threshold for the shares.

**Comment by johnnybubonic** [comment]
Sure, and to be clear this is all entirely in the theoretical; I don't have a need for this personally, but I could see the utility for such a thing since currently the only real way to do a complete digital escrow is with e.g. an attorney. Vault's structure seems like it'd be a good foundation for this.

Raising the threshold does solve the malicious sealing problem, but it's my understanding that unseal keys can't be used to generate a new root token, correct? If all root tokens are then revoked by a bad actor and restrictive policies are applied (or all other auths are revoked) by this actor, that vault is toast. Or the vault could be held hostage if the bad actor retained a single root token in their possession. Correct?

**Comment by michelvocks** [comment]
> Raising the threshold does solve the malicious sealing problem, but it's my understanding that unseal keys can't be used to generate a new root token, correct?

They can: https://www.vaultproject.io/docs/commands/operator/generate-root.html

**Comment by johnnybubonic** [comment]
OH. I didn't make that connection. Closing
