### ISSUE TITLE
Display giant warning when running without mlock

### ISSUE THREAD

**Issue by jtdowney** [hashicorp/vault#62]
When running vault on a system that doesn't offer `mlock`, there should be a giant warning, similar to what GPG does. The docs should clearly describe this situation and explain the danger of swapping secret data to disk.

```
gpg: Warning: using insecure memory!
```

I'm happy to make a pull request if you're interested.

**Comment by mitchellh** [comment]
Great idea.

**Comment by mitchellh** [comment]
Fixed with #73, will be in 0.1.1.
