### ISSUE TITLE
add ability to expire auth backend generated tokens

### ISSUE THREAD

**Issue by jplabit** [hashicorp/vault#620]
There are quite a few issues opened about the ability to renew a token that is issued by an auth backend (userpass, app-id, etc) and also the ability to set lease durations for those tokens that are issued (backend specific). It seems there should also be a way to revoke/expire those tokens as a cleanup step.

I'm not sure revoking is the right way and would probably be difficult to implement, though the ability to expire it would be just as useful. If the client can renew their token, they should be able to expire it as well.

**Comment by jefferai** [comment]
I'm closing this in favor of the various other issues that you mentioned. Fixing this behavior is already planned, so please follow those issues for updates.

**Comment by jplabit** [comment]
With the other solutions, once the token is created, you can do nothing with it other than renew up to a maximum. If I "own" the token, I should be able to clear it somehow. Those other issues/planned updates don't address that.

**Comment by jefferai** [comment]
I guess I'm not understanding the issue then.

>  If I "own" the token, I should be able to clear it somehow.

Is there some reason revocation doesn't fit this bill for you?

**Comment by jplabit** [comment]
Because it doesn't appear that I can revoke my own token without given that user access to the revoke endpoint.

Example:

Authenticate with app-id. Get the token. Try to revoke it.

curl -X PUT ${VAULT_ADDR}/v1/auth/app-id/login -d '{"app_id": "app", "user_id": "user"}'

Assuming token below is returned...

curl -X POST -H "X-Vault-Token: f30bd793-bac5-d341-3f42-93fb0e35f005" ${VAULT_ADDR}/v1/auth/token/revoke/f30bd793-bac5-d341-3f42-93fb0e35f005
{"errors":["permission denied"]}

I don't want to give that user/token the ability to revoke all tokens, just its own. If there is another way to do this, then I agree this can stay closed. If the ability to revoke/expire/release becomes a part of the ability to renew, then I'm good with that as well, but I didn't see it listed in there.

**Comment by jefferai** [comment]
You can now give tokens access to /auth/token/revoke-self, and they can perform their own revocations.

**Comment by jplabit** [comment]
Excellent! I'l check it out. Thanks!
