### ISSUE TITLE
could not write key on kv v2 store

### ISSUE THREAD

**Issue by maxadamo** [hashicorp/vault#6200]
I have the following code, which eventually works with KV V1 store (after having changed the path in the proper way), but it doesn't work on a KV V2 store:
```
secret := make(map[string]interface{})
secret["value"] = pass
log.Println(secret)
HostpathArg := fmt.Sprintf("/%v/data/%v/%v", patharg, host, vaultkeyname)
_, err = vault.Write(HostpathArg, secret)
```
this is the error that I am getting: 

```
2019/02/09 01:15:37 Error making API request.

URL: PUT https://vault.blahblah.org/v1/test/data/test-psui-ubuntu01.blahblah.org/vault_root_password
Code: 400. Errors:

* no data provided
```

It is absolutely not clear to me how to create the map. 
The map that I create, has the following random value: `map[value:7yU4129dpK]`

**Comment by briankassouf** [comment]
KV version 2 expects the values to be in a Data map: https://www.vaultproject.io/api/secret/kv/kv-v2.html#data 

So try: 
```
secret["data"] = map[string]interface{}{
    "value": pass,
}
```

**Comment by maxadamo** [comment]
Thank you! You have no idea how bad I am at Go Programming. I was writing:
```
secret["data"]["value"] = pass
``` 
which wasn't working :) Thanks again.
