### ISSUE TITLE
Error on plugin installation: unable to determine plugin type

### ISSUE THREAD

**Issue by mygithubthrowaway** [hashicorp/vault#6203]
Hi all, 
i already posted this problem on plugin page but no luck.
situation: vault server and vault client on the same machine: i tried different configuration but when i try to install the plugin i get the same error:

```
vault write sys/plugins/catalog/oracle-database-plugin sha256=7f7653bb546ad7df9b21204517597234a0b3151aeb9ce3bb8a9103c12f9627e6 command=vault-plugin-database-oracle
Error writing data to sys/plugins/catalog/oracle-database-plugin: Error making API request.

URL: PUT http://127.0.0.1:8050/v1/sys/plugins/catalog/oracle-database-plugin
Code: 500. Errors:

* 1 error occurred:
	* unable to determine plugin type
```

my config:

```
{
"listener": [{
"tcp": {
"address" : "0.0.0.0:8050",
"tls_disable" : 1
}
}],
"api_addr": "http://0.0.0.0:8050",
"storage": {
    "file": {
    "path" : "/vault-data"
    }
 },
"max_lease_ttl": "10h",
"default_lease_ttl": "10h",
"disable_mlock": "True",
"ui":true,
"plugin_directory":"/etc/vault/plugins"
}
```
`export VAULT_ADDR=http://127.0.0.1:8050`

Oracle plugins `version: 0.1.4`
Vault Version: `Vault v1.0.2 ('37a1dc9c477c1c68c022d2084550f25bf20cac33')`

Thanks

**Comment by chrishoffman** [comment]
The API changed slightly recently.  Can you try registering it with `sys/plugin/catalog/database/oracle-database-plugin` instead?

See https://www.vaultproject.io/api/system/plugins-catalog.html#register-plugin

**Comment by briankassouf** [comment]
Also if there are any errors in the Vault server logs that would be helpful to see

**Comment by mygithubthrowaway** [comment]
> The API changed slightly recently. Can you try registering it with `sys/plugin/catalog/database/oracle-database-plugin` instead?
> 
> See https://www.vaultproject.io/api/system/plugins-catalog.html#register-plugin

Worked! thanks for the tip and the api link.
Btw here: https://www.vaultproject.io/docs/secrets/databases/oracle.html still point to wrong api path (without plugin:type)

**Comment by oakville** [comment]
i got the same err of "* unable to determine plugin type" as the mygithubthrowaway, then followed mygithubthrowaway suggestion to change the api registration path, got hit a new err as "unsupported path", anyone have any thoughts can share with? thanks a lot

i used the latest vault plugin for oracle and vault Version 1.0.3

much appreciate all comment, thanks

0a6efb92ea6541e57"     command=vault-plugin-database-oracleb614a1b9343775146d4710
base-plugin \zdbora13 vault_plugins]# vault write sys/plugin/catalog/oracle-data
\     sha256="40a3577301aeb4507a0ff195feb614a1b9343775146d4710a6efb92ea6541e57"
>     command=vault-plugin-database-oracle
Error writing data to sys/plugin/catalog/oracle-database-plugin: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/plugin/catalog/oracle-database-plugin
Code: 404. Errors:

* 1 error occurred:
        * unsupported path
