### ISSUE TITLE
UI: Display "created_time" for kv v2

### ISSUE THREAD

**Issue by bor-tso** [hashicorp/vault#6215]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Showing "created_time" somewhere in the UI, either in the secret page itself or next to the secret in the secrets list.
Im just relating to KV pairs, because we're not using anything else.

**Describe alternatives you've considered**
storing creation time in a kv pair in the secret

**Explain any additional use-cases**
We do store ssl private keys in kv pairs and we would like to see when they have been created.

**Additional context**
None

**Comment by aphorise** [comment]
@bor-tso - I'm going to close this request as this feature has since been delivered (as of 1.10.x I think) outside of the original PR I'd raised.

![image](https://user-images.githubusercontent.com/974854/187551553-4554837c-8005-4fa5-9a5b-e763b261d758.png)
