### ISSUE TITLE
Mount a secret engine inside the path of an already mount kv secret engine

### ISSUE THREAD

**Issue by Lasering** [hashicorp/vault#6216]
**Is your feature request related to a problem? Please describe.**
My deployment of Vault manages the secrets of multiple deployment/environments for each service I have.

For example - for the service "service discovery" I have a single deployment called Técnico (one of my organizations) and at least two environments for that deployment: staging and production. So I mount a kv secret engine at "service-discovery/", then I save secrets with the following layout: "service-discovery/$DEPLOYMENT/$ENVIRONMENT" or to make things explicit:

```
service-discovery/
↳tecnico/
   ↳staging/
      ↳encrypt-secret-key
   ↳prodution/
      ↳encrypt-secret-key
```
I'm just showing the layout for the "service discovery" service but imagine there are more services, each on with its own kv secret engine.

In order for other services to talk to "service discovery" service they need a client X509 certificate. So it is usefull to enable the PKI secrets engine, however I would like to do so for each $DEPLOYMENT/$ENVIRONMENT. So the ideal place would be to enable the pki secret engine at the path "service-discovery/tecnico/staging/pki" and "service-discovery/tecnico/production/pki". However vault complains that "existing mount at service-discovery/".

**Describe the solution you'd like**
Allow mounting secrets engines inside the paths of an already mounted key/value secret engine. That  would allow for a much more flexible "layout" of secrets inside Vault.

**Describe alternatives you've considered**
The path where the secret engines are mounted includes the "package/namespace" of the deployment.
Continuing with the example I would mount a pki at "service-discovery-tecnico-staging-pki" and at "service-discovery-tecnico-production-pki".

**Comment by briankassouf** [comment]
We intentionally do not allow mounting secret engines at a suffix of an existing mount. This would cause all types of conflicts with API paths and make ACL'ing much more complicated. We have a [namespaces](https://www.vaultproject.io/docs/enterprise/namespaces/index.html) feature in our enterprise offering.

Alternatively you can mount secret engines with common prefixes: `service-discovery/kv` and `service-discovery/pki` could both be mounted (assuming no mount at `service-discovery/`) and ACL'ing can use a common prefix.

**Comment by Lasering** [comment]
Awesome. Thanks for responding.

**Comment by Lasering** [comment]
Mounting secret engines with common prefixes works, however the UI does not display them in a hiearchical fashion but in a flat fashion. It does solve the ACL'ing problem,
