### ISSUE TITLE
In reference to removal of returned secret information change in 0.10.0.  Idea to still provide that functionality in a secure way

### ISSUE THREAD

**Issue by fortman** [hashicorp/vault#6231]
I'm upgraded vault from the 0.9.1 to the latest and noticed the following release note.
https://www.vaultproject.io/docs/upgrading/upgrade-to-0.10.0.html#removal-of-returned-secret-information

**Is your feature request related to a problem? Please describe.**
Not really a problem but a deprecated feature from the release note linked above.

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**
We were using the functionality to get the previous secret information to determine if the state changed, and if it did to re-upload the configuration.  We are doing this from a chef cookbook using the official vault ruby gem.  Removing this functionality does not allow us to see if an update needs to happen.

**Describe the solution you'd like**
Instead of returning the secret data, can you just return a hash of the data?  This will allow us to compare the configuration in vault with the configuration we would like to apply to see if it changed.  This would be achieved by comparing the hashes instead of the actual data.  This should be secure, in that vault is only returning a hash of the data.   It would allow us however, to still be able to check for changes in secure configs.  All the security you wanted, but continuing to have the functionality that was dropped.

**Describe alternatives you've considered**
No alternatives.  We can not check for changes if vault returns no data.

**Explain any additional use-cases**
Any configuration management tool, terraform for instance, could take advantage of this.

**Additional context**
none, can provide more details if needed.

**Comment by aphorise** [comment]
This is referring to Vault 0.10.0 that's a very old version that I've only ever tried on a few rare occasions 😃  - I also suspect that it's also no longer supported?

Hey @fortman Is this request still relevant or should it be closed?

**Comment by aphorise** [comment]
Closing due to no follow-up. Please re-open if still relevant.
