### ISSUE TITLE
Debian packaging - keeping sane dependencies

### ISSUE THREAD

**Issue by chuxau** [hashicorp/vault#625]
Hi,

I am making my first steps at packaging vault for debian, for use in an internal network .. 

So far, using the debian dh-make-golang helper utility to create a baseline package, I get a dependency list that reads like so:

Build-Depends: 

>                debhelper (>= 9),
               dh-golang,
               golang-go,
               golang-github-armon-go-metrics-dev,
               golang-github-armon-go-radix-dev,
               golang-github-aws-aws-sdk-go-dev,
               golang-github-coreos-go-etcd-dev,
               golang-github-dgrijalva-jwt-go-dev,
               golang-github-duosecurity-duo_api_golang-dev,
               golang-github-fatih-structs-dev,
               golang-github-go-ldap-ldap-dev,
               golang-github-go-sql-driver-mysql-dev,
               golang-github-gocql-gocql-dev,
               golang-github-google-go-github-dev,
               golang-github-hashicorp-consul-dev,
               golang-github-hashicorp-errwrap-dev,
               golang-github-hashicorp-go-multierror-dev,
               golang-github-hashicorp-go-syslog-dev,
               golang-github-hashicorp-golang-lru-dev,
               golang-github-hashicorp-hcl-dev,
               golang-github-hashicorp-logutils-dev,
               golang-github-kardianos-osext-dev,
               golang-github-lib-pq-dev,
               golang-github-mitchellh-cli-dev,
               golang-github-mitchellh-copystructure-dev,
               golang-github-mitchellh-go-homedir-dev,
               golang-github-mitchellh-mapstructure-dev,
               golang-github-mitchellh-reflectwalk-dev,
               golang-github-ryanuber-columnize-dev,
               golang-github-samuel-go-zookeeper-dev,
               golang-golang-x-crypto-dev,
               golang-golang-x-oauth2-dev

The implication of the build-deps is that I would also need to build these packages listed .. 

My questions are:
* What are the base level dependencies for standard internal network use? (I have no need/use in my build for coreos, aws, zookeeper, and most others listed as build-deps)
* Are you aware of anyone else that has successfully packaged vault for debian ?

Thanks in advance for info/comments/suggestions ..

**Comment by jefferai** [comment]
There isn't any such thing as "base level dependencies"; you could patch out things you don't need and thus get rid of the dependencies that way.

Since this is for internal use, my question would be why you don't make use of the Makefile that comes with Vault to simply build it along with supported dependencies for that version, and simply package the resulting file.

**Comment by chuxau** [comment]
Thanks for responding, jefferai

What I meant by base-level dependencies is libraries/packages that are absolute requirements even with a minimal install of vault , but I understand what you are saying .. thanks for the feedback.

I did look in greater detail at debian upstream golang packages, and many of the deps I listed are actually already satisfied by the debian upstream .. 

So, yes, I will consider deb-packaging the missing but required dependencies .. or consider your suggestion of building with the makefile, and then packaging just the binary .. 

Thanks again

**Comment by jefferai** [comment]
Yeah - the problem is that Vault's build (like most Go programs) isn't modular. One of the joys of a statically compiled language -- you can't just link to plugins at runtime. So it's all compiled in, even if you don't use half of it.

Good luck!
