### ISSUE TITLE
LIST unsupported operation

### ISSUE THREAD

**Issue by thomasnal** [hashicorp/vault#6254]
**Describe the bug**

Vault API returns unsupported operation on LIST command.

See below the trace log from consul-template calling vault api on a template command {{ secrets "<PATH>" }}
```
2019/02/18 15:08:56.834611 [TRACE] (view) vault.list(secret/data/myapp/config) starting fetch
2019/02/18 15:08:56.834646 [TRACE] vault.list(secret/data/myapp/config): LIST /v1/secret/data/myapp/config?stale=true&wait=1m0s
2019/02/18 15:08:56.835736 [WARN] (view) vault.list(secret/data/myapp/config): Error making API request.

URL: GET http://100.69.176.202:8200/v1/secret/data/myapp/config?list=true
Code: 405. Errors:

* 1 error occurred:
	* unsupported operation
```

**Expected behavior**
List of secret keys

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.1
* Server Operating System/Architecture: docker  image: vault

**Comment by jefferai** [comment]
Listing against kvv2 is done against /metadata/ paths, not /data/ paths; see https://www.vaultproject.io/api/secret/kv/kv-v2.html#list-secrets

**Comment by iusergii** [comment]
@jefferai I've tried the example from docs and it fails for me. Filed: https://github.com/hashicorp/vault/issues/9874

**Comment by dondrich** [comment]
@jefferai Thanks for this!!
