### ISSUE TITLE
Entity ID api internal error with syslog audit enabled.

### ISSUE THREAD

**Issue by knlambert** [hashicorp/vault#6255]
**Describe the bug**
We have a lot of entities in our Vault : 4 pages in the user interface. We also enabled the syslog audit system.
Today, by connecting to the interface, I've discovered a 500 error when going
into the entities menu, coming from the REST api : 

![image](https://user-images.githubusercontent.com/16439060/52979430-8ecd0f00-33a3-11e9-95e8-deed7d6e7b3a.png)

I've checked the Vault logs to see if something more specific was there : 
Here the log corresponding to the request : 

```
2019-02-18T22:36:21.290Z [ERROR] audit: backend failed to log response: backend=syslog/ error="write unixgram @->/dev/log: write: message too long"
2019-02-18T22:36:21.291Z [ERROR] core: failed to audit response: request_path=identity/entity/id/ error="1 error occurred:
        * no audit backend succeeded in logging the response
```

So I've disabled the syslog audit : 
`vault audit disable syslog`

No more issues.

**To Reproduce**
1. Create a lot of entities in vault. (at Least 120).
2. Enable the syslog auditing.
3. See the error coming from the /v1/identity/entity/id?list=true API endpoint.

**Expected behavior**
The API should not fail, I suspect it is because the request result is not paginated, so the syslog size increases with time, making the API fail as well.

**Environment:**
* Vault Server Version: 1.0.2 community.
* Vault CLI Version:  Vault v0.11.1 ('8575f8fedcf8f5a6eb2b4701cb527b99574b5286') (not relevant).
* Server Operating System/Architecture: alpine-linux from the standard [Vault Docker image.](https://github.com/hashicorp/docker-vault)

Vault server configuration file(s):

```hcl
"backend" "gcs" {
  "bucket" = ""****""
  "ha_enabled" = "true"
}

"cluster_addr" = "https://svc-vault.vault.svc.cluster.local"
"default_lease_ttl" = "168h"
"disable_mlock" = true

"listener" "tcp" {
  "address" = "0.0.0.0:8200"
  "tls_cert_file" = "/var/run/secrets/kubernetes.io/certs/tls.crt"
  "tls_disable" = "0"
  "tls_key_file" = "/var/run/secrets/kubernetes.io/certs/tls.key"
}
"max_lease_ttl" = "720h"
"seal" "gcpckms" {
  "crypto_key" = "****"
  "key_ring" = "****"
  "project" = "****"
  "region" = "****"
}
"ui" = true
```

Vault is running in a Kubernetes cluster.

**Comment by jefferai** [comment]
This is known and explicitly warned about in the syslog audit documentation (https://www.vaultproject.io/docs/audit/syslog.html). Please see there for possible workarounds.
