### ISSUE TITLE
ssh ca with hashicorp vault  complete step by step configuration with server and client header

### ISSUE THREAD

**Issue by Fastersush** [hashicorp/vault#6265]
Please post questions on the mailing list (https://groups.google.com/forum/#!forum/vault-tool) rather than in GitHub issues.

With over 1700 subscribers, the mailing list gets a _lot_ more eyes on any particular question. You'll get an answer faster, not slower, by taking advantage of the suggestions and answers provided by the wealth of experience that long-time users and devs bring to the list.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!

**Comment by Fastersush** [comment]
Hi , can anyone help me to configure the  hashicorp vault setup for ssh ca 
i tried multiple soultions but no success.
it would be great if anyone can help with details steps to follow on vault server on target machine with config files

**Comment by michelvocks** [comment]
Hi @Fastersush,

please try to avoid asking questions in the issue tracker.
Questions should be posted at https://groups.google.com/forum/#!forum/vault-tool

A step by step guide can be found in the documentation: https://www.vaultproject.io/docs/secrets/ssh/signed-ssh-certificates.html
Feel free to ask additional questions via the google groups in case something is unclear. 

Cheers,
Michel

**Comment by Fastersush** [comment]
Hi Michael,

i already tried with those steps but still no luck.
and regarding raising issue on forum, i dont have right for the same.
can you please help here

**Comment by michelvocks** [comment]
Hi @Fastersush,

you need a valid Google account. You can create one [here.](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwiwh6XXwsrgAhXG16QKHb1cBYgQFjAAegQICRAB&url=https%3A%2F%2Faccounts.google.com%2Fsignup%3Fhl%3Den-GB&usg=AOvVaw1MGP_piqmNWr2xy8MU5oIH)

Cheers,
Michel
