### ISSUE TITLE
Better documentation for configuration via environment variables

### ISSUE THREAD

**Issue by bkeroackdsc** [hashicorp/vault#628]
[Apparently](https://github.com/hashicorp/vault/commit/3a05fb70a7eaa01371a84656c18ebd5697f5e14a) it's possible to configure vault via environment variables, which is good. However you would have no way of knowing it from [the docs](https://vaultproject.io/docs/config/index.html).

Documentation should be added that you don't necessarily need to use a static configuration file.

**Comment by jefferai** [comment]
This is already in master and will be in 0.3.
