### ISSUE TITLE
web UI fails to list secrets when the path contains a #*+[(\ character

### ISSUE THREAD

**Issue by dupainaulevain** [hashicorp/vault#6282]
#### Describe the bug

the web UI fails to list secrets when a component of the path contains a #*+[(\ character

* **#some** is not properly escaped and is a URL fragment
* ***some** empty list, no secret displayed
* **+some** empty list, no secret displayed
* **[some** empty list, no secret displayed
* **(some** empty list, no secret displayed
* **\\some** is incorrectly translated into /some

#### To Reproduce

Steps to reproduce the behavior, using a live Vault server (not the -dev because the workaround will redirect to the page asking for the token) and the open parenthesis. 
   
* vault kv put 'secret/(some/2' 3=4
* visit http://vaultserver:8200//ui/vault/secrets/secret

![1](https://user-images.githubusercontent.com/46968996/53228666-25d6e700-3682-11e9-9e6d-c976a82309cc.png)

* click on the link to **(some**

![2](https://user-images.githubusercontent.com/46968996/53228704-4141f200-3682-11e9-90b5-e31994a805a1.png)

* the secret (2) is not displayed

#### Expected behavior

The secret is displayed

#### Workaround

* manually replace ( with %28 in the URL

![3](https://user-images.githubusercontent.com/46968996/53228725-51f26800-3682-11e9-8031-ba34089ed9b8.png)

* the secret is displayed (notice the %28 in the page)

![4](https://user-images.githubusercontent.com/46968996/53228791-9120b900-3682-11e9-8bc0-a56cd5414b12.png)

#### Environment:

    Vault Server Version Vault v1.0.2
    Vault CLI Version Vault v1.0.2 ('37a1dc9c477c1c68c022d2084550f25bf20cac33')
    Server Operating System/Architecture: Debian GNU/Linux stretch amd64

**Comment by singuliere** [comment]
I'm not sure why it would only create a problem with the open parenthesis. There probably is a range of character that trigger the same bug.

**Comment by singuliere** [comment]
```
for c in \! \" \# \$ \& \' \* \+ \, \@ \`  \{ \| \} \~ ; do vault kv put "secret/${c}some/2" 3=4 ; done
```
and trying each link shows:

* **#some** is not properly escaped and is a URL fragment
* ***some** empty list, no secret displayed
* **+some** empty list, no secret displayed

**Comment by singuliere** [comment]
@meirish is this considered a bug? I'm not familiar with how labels are assigned :-)

**Comment by meirish** [comment]
@singuliere Yep, the linked PR (
https://github.com/hashicorp/vault/pull/6294) fixes it - just got around to checking it out yesterday. @dupainaulevain thanks for the report - I think we've also fixed it in a few other places in the UI as well.

**Comment by singuliere** [comment]
@meirish excellent,thanks!

**Comment by dupainaulevain** [comment]
@meirish do you think [vault kv list fails when a path component has a trailing white space](https://github.com/hashicorp/vault/issues/6213) has the same root cause as this issue?

**Comment by meirish** [comment]
@dupainaulevain no they are separate, it looks like there's a PR with some discussion linked on that issue, I believe that behavior is intentional (and the UI mimics it in the web CLI)
