### ISSUE TITLE
Failed to look up namespace from the token: no namespace

### ISSUE THREAD

**Issue by akamalov** [hashicorp/vault#6287]
**Environment:**

```vault 1.0.2```

**Problem:**

Trying to issue sample API call to list ```auth/azure/roles```, but getting an error:

```
$ curl --header "X-Vault-Token: $token" --request LIST http://127.0.0.1:8200/v1/auth/azure/roles
{"errors":["1 error occurred:\n\t* internal error\n\n"]}
$
```

Looking through logs I found the following:

```
Feb 24 14:48:03 consul1 vault[20402]: 2019-02-24T14:48:03.672Z [ERROR] core: failed to lookup token: error="failed to look up namespace from the token: no namespace"
Feb 24 14:48:25 consul1 vault[20402]: 2019-02-24T14:48:25.152Z [ERROR] core: failed to lookup token: error="failed to look up namespace from the token: no namespace"
Feb 24 14:49:01 consul1 CRON[2075]: (root) CMD ([ -f /etc/krb5.keytab ] && [ \( ! -f /etc/opt/omi/creds/omi.keytab \) -o \( /etc/krb5.keytab -nt /etc/opt/omi/creds/omi.keytab \) ] && /opt/omi/bin/support/ktstrip /etc/krb5.keytab /etc/opt/omi/creds/omi.keytab >/dev/null 2>&1 || true)
Feb 24 14:49:22 consul1 vault[20402]: 2019-02-24T14:49:22.982Z [ERROR] core: failed to lookup token: error="failed to look up namespace from the token: no namespace"
root@consul1:~#
```

List namespaces:

```
root@consul1:~# vault namespace list
No namespaces found
root@consul1:~#
```
List Vault auths configured:
```
$ vault auth list
Path      Type     Accessor               Description
----      ----     --------               -----------
token/    token    auth_token_8dafff47    token based credentials
$
```
Create a sample namespace:

```
root@consul1:~# vault namespace create -namespace=education training
Error creating namespace: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/namespaces/training
Code: 404. Errors:

* 1 error occurred:
        * unsupported path


root@consul1:~#
```

At this point I am not sure where the problem is?

**Comment by jefferai** [comment]
Likely the token you are trying to pass in is malformed. Obviously I can't tell you more unless you want to paste in the token value.

**Comment by akamalov** [comment]
Thanks for quick reply. For security reasons I cannot based unredacted  copy of token, but the token looks valid to me:

![image](https://user-images.githubusercontent.com/7885257/53301692-0c6da080-3824-11e9-9ead-43d64f62a73f.png)

**Comment by Teay1985** [comment]
issue

**Comment by jefferai** [comment]
That's a JWT for something else, not a Vault token...

**Comment by jefferai** [comment]
Closing as the token being passed is not a Vault token.

**Comment by TommyStarK** [comment]
Hi,

Sorry to post on a close issue but i'm facing the exact same issue but with a vault token instead 😄  

**Environment**

`Vault v1.0.3 ('85909e3373aa743c34a6a0ab59131f61fd9e8e43')`

**Problem**
Trying to mount a pki engine and retrieving the following error:

`"error performing token check: failed to look up namespace from the token: no namespace"`

**what i do**

```
pki_engine_config()
{
cat <<EOF
{
    "type":"pki", 
    "config": { 
        "max_lease_ttl":"87600h" 
    }
}
EOF
}

curl --header "X-Vault-Token: $ROOT_TOKEN" \
    --request POST  \
    --data "$(pki_engine_config)" \
    http://127.0.0.1:8201/v1/sys/mounts/pki | jq
```

When I replace the variable `$ROOT_TOKEN` by the token value itself it works perfectly, so I'm wondering if it is a bash related problem but as I don't see it I rather ask you first!

**Credentials**
```
{
  "keys": [
    "b908da7c7cedf1457867b7565a8c005df7d0c628539e502a522e0e2a949040a583",
    "c789d2ce7e637c108eac036ce6b6e8a78773eff2f5bd0acb5779b1655aa94d1b41",
    "cfc0c1d30b141d06bd6f11160e1bf5692da23285180c93cf9f98395568109abccb",
    "8dfad0c0a73cddfc7ad8749f641fa93313afb8de1354b550a9ace9732a16f726ea",
    "74096f431483b460973d13941e0bf366d592fe9e08d721abc367edddcce9ac28bc"
  ],
  "keys_base64": [
    "uQjafHzt8UV4Z7dWWowAXffQxihTnlAqUi4OKpSQQKWD",
    "x4nSzn5jfBCOrANs5rbop4dz7/L1vQrLV3mxZVqpTRtB",
    "z8DB0wsUHQa9bxEWDhv1aS2iMoUYDJPPn5g5VWgQmrzL",
    "jfrQwKc83fx62HSfZB+pMxOvuN4TVLVQqazpcyoW9ybq",
    "dAlvQxSDtGCXPROUHgvzZtWS/p4I1yGrw2ft3czprCi8"
  ],
  "root_token": "s.zjU1qtojo9ALM4khy5mkXODt"
}
```

Those credentials have been generated for demo purposes only.

Thank you very much for your help 😄

**Comment by DI-DaveGoodine** [comment]
In my case, I got this error when I had a ~/.vault-token set that was valid on a different vault server.

**Comment by stanislavtrubachev** [comment]
The namespaces feature requires Vault Enterprise Platform.

**Comment by ipleten** [comment]
Error might happen if you have quotes in token. Jenkins added quotes to token in my case.

**Comment by chance2021** [comment]
> Error might happen if you have quotes in token. Jenkins added quotes to token in my case.

Removing "quote" in the token works for me! Thanks!
```
TOKEN=$(echo $TOKEN|tr -d '"')
```
