### ISSUE TITLE
Can't see link to policies in UI although rights are granted

### ISSUE THREAD

**Issue by der-eismann** [hashicorp/vault#6292]
**Describe the bug**
I created an _admin_ policy with rights to access and edit policies and attached it to a group. Everyone in this group can access policies via CLI, but the menu is hidden in the UI.

**To Reproduce**
1. Create admin policy from [guide](https://learn.hashicorp.com/vault/identity-access-management/iam-policies#policy-requirements)
2. Create user
3. Add user to group
4. Attach admin policy to group

**Expected behavior**
Users in the admin group can see and edit policies in the UI.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.3
* Vault CLI Version (retrieve with `vault version`): 1.0.3
* Server Operating System/Architecture: CoreOS / kubernetes

Vault server configuration file(s):

```hcl
    ui = true
    max_lease_ttl = "12h"
    default_lease_ttl = "12h"
    cluster_name = ""

    seal "awskms" {
      region     = "eu-west-1"
      access_key = ""
      secret_key = ""
      kms_key_id = ""
    }

    storage "dynamodb" {
      ha_enabled     = "true"
      region         = "eu-west-1"
      table          = "vault-data"
      access_key     = ""
      secret_key     = ""
    }

    listener "tcp" {
      address          = "0.0.0.0:8200"
      cluster_address  = "0.0.0.0:8201"
      tls_disable      = 1
    }
```

User can see policies when the URL is accessed directly, but links on the top and on the left are missing:
![vault_screenshot](https://user-images.githubusercontent.com/10406217/53421137-71202b00-39dd-11e9-8def-cdac3d349238.png)

**Comment by der-eismann** [comment]
Great, thanks for the quick fix!

**Comment by acthpa** [comment]
I am encountering that exact same bug on v1.1.1 on Ubuntu. What is the policy? Shall I create a different entry?
