### ISSUE TITLE
Support deniable encryption

### ISSUE THREAD

**Issue by Raj2032** [hashicorp/vault#6297]
While it is good to encrypt sensitive data, what if the user was forced to give up their password just to unlock the data and view the person's personal information? We should try and support deniable encryption where we have an outer and inner container, like VeraCrypt.

The outer container has fake sensitive files while the inner container contains your real sensitive files, so if we were forced to give up the password, we can give the outer container password that unlocks the outer container.

**Comment by jefferai** [comment]
I think this might be a nice idea for a community plugin, but it's rather special purpose and complex to push straight into baseline Vault. If you write such a plugin be sure to tell people about it on the mailing list!

**Comment by Raj2032** [comment]
I am not a developer so I have no idea how to write a plugin. Is it possible to take my suggestion to write as a plugin cause like I believe this is a really good idea, think about it if the user was forced to give up their password, especially by authorities, then whats the point of encrypting the data, that is why we need deniable encryption

**Comment by jefferai** [comment]
I don't think Vault is the right layer here. Probably you'd use VeraCrypt to encrypt the drive storing Vault's data to achieve this.

**Comment by Raj2032** [comment]
The problem is that VeraCrypt forces you to set a size limit to the file,
Vault doesn't.
