### ISSUE TITLE
Vault agent authentication in China not working using IAM method (AWS)

### ISSUE THREAD

**Issue by Nandito4** [hashicorp/vault#6326]
**Describe the issue**
We have already a fully working infrastructure using Vault agent to authenticate EC2 instances accessing Vault using IAM method in AWS. However for China AWS we still authenticate EC2 instances without the agent because we cannot get it to communicate with the China AWS STS API endpoint. Note that the servers on the China AWS have been using EC2 auth method without any issue for 1 year and now we are trying to switch to the IAM method while using Vault agent.

**To Reproduce**
1. Set up Vault server in China AWS
2. Create an EC2 instance and assign an IAM role to it
3. Create a Vault role to be used by the EC2 instance
4. Configure Vault agent on the EC2 instance
5. Try to authenticate the EC2 instance using vault agent IAM method

**Actual behavior**

```
Mar 04 06:14:03 bastion001-0bb2 vault[46639]: 2019-03-04T06:14:03.943Z [INFO]  auth.handler: authenticating
Mar 04 06:14:03 bastion001-0bb2 vault[46639]: 2019-03-04T06:14:03.959Z [ERROR] auth.handler: error authenticating: error="Error making API request.
Mar 04 06:14:03 bastion001-0bb2 vault[46639]: URL: PUT {VAULT_SERVER}/v1/auth/aws/login
Mar 04 06:14:03 bastion001-0bb2 vault[46639]: Code: 400. Errors:
Mar 04 06:14:03 bastion001-0bb2 vault[46639]: * error making upstream request: received error code 403 from STS: <ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
Mar 04 06:14:03 bastion001-0bb2 vault[46639]:   <Error>
Mar 04 06:14:03 bastion001-0bb2 vault[46639]:     <Type>Sender</Type>
Mar 04 06:14:03 bastion001-0bb2 vault[46639]:     <Code>SignatureDoesNotMatch</Code>
Mar 04 06:14:03 bastion001-0bb2 vault[46639]:     <Message>Credential should be scoped to a valid region, not 'us-east-1'. </Message>
Mar 04 06:14:03 bastion001-0bb2 vault[46639]:   </Error>
Mar 04 06:14:03 bastion001-0bb2 vault[46639]:   <RequestId>b5c1682e-3e44-11e9-8cbe-f5d0e1ea09c4</RequestId>
Mar 04 06:14:03 bastion001-0bb2 vault[46639]: </ErrorResponse>
Mar 04 06:14:03 bastion001-0bb2 vault[46639]: " backoff=2.513765551
```

**Expected behaviour**
Requests are going to the China AWS STS API but the scope of the credentials is not valid. It may be caused because the requests are probably signed by de SDK with the key for us-east-1 instead of cn-northwest-1. The expected behaviour would be it to use the scope of the region.

**Environment:**
* Vault version (retrieve with `vault status`): 1.0.0
* Server Operating System/Architecture: Ubuntu Xenial 16.04 amd64

Ansible configuration file(s):

```yaml
vault_auth_aws_endpoints:
  ec2: https://ec2.cn-northwest-1.amazonaws.com.cn
  iam: https://iam.cn-north-1.amazonaws.com.cn
  sts: https://sts.cn-northwest-1.amazonaws.com.cn
```

```yaml
- name: 'Enable aws auth backend'
  uri:
    url: '{{ vault_api_url }}/v1/sys/auth/aws'
    method: POST
    body_format: json
    body:
      type: aws
    headers:
      X-Vault-Token: '{{ vault_root_token }}'
    status_code: 204
  changed_when: yes
  when: vault_auth_backends.json.data['aws/'] is not defined
  run_once: yes
```

```yaml
vault_auth_aws_roles:
  - role: nsscache
    inferred_entity_type: ec2_instance
    inferred_aws_region: cn-northwest-1
    policies:
      - nsscache
    bound_iam_principal_arn:
      - 'arn:aws-cn:iam::X:role/*'
    ttl: 1h
    max_ttl: 6h
```

STS endpoint needs to be configured as it is hardcoded as the non-china AWS STS API.
```yaml
name: 'Configure the STS endpoint'
uri:
  url: '{{ vault_api_url}}/v1/auth/aws/config/client'
  method: POST
  body_format: json
  body:
    endpoint: '{{ vault_auth_aws_endpoints.ec2 }}'
    iam_endpoint: '{{ vault_auth_aws_endpoints.iam }}'
    sts_endpoint: '{{ vault_auth_aws_endpoints.sts }}'
  headers:
    X-Vault-Token: '{{ vault_root_token }}'
  status_code: 204
changed_when: yes
run_once: yes
when: vault_auth_aws_endpoints is defined
```

**Comment by tyrannosaurus-becks** [comment]
Thanks for opening this ticket, @Nandito4! 

I'm thinking we'll need to add some region-parsing code to [here](https://github.com/hashicorp/vault/blob/master/command/agent/auth/aws/aws.go), after [this](https://github.com/hashicorp/vault/pull/6268) PR has been merged.

**Comment by hiscal2015** [comment]
@Nandito4 @tyrannosaurus-becks I have the same issue, is this addressed and what’s the solution? Thanks.

**Comment by hiscal2015** [comment]
anyone knows what is the progress for this issue?

**Comment by danlsgiga** [comment]
Just hit this same issue in a hard way. Any plans of a fix soon? Any workarounds?

**Comment by danlsgiga** [comment]
Just for context... I hit this issue once I tried to upgrade our Vault Agents from 1.1.2 to 1.2.3

**Comment by tyrannosaurus-becks** [comment]
We just merged a fix into master for this, and it's pending release in Vault's next patch release. #7674 , #7632 , #7622 .

**Comment by Jagadt** [comment]
Hi All,

Is it supported to install Hashicorp Vault (open source) server (consul client, server) in EC2 instance(s) on China AWS Cloud and to store S3 bucket keys within the Hashicorp Vault server?

The reason for this question is that based on https://www.hashicorp.com/terms-of-evaluation  it says the following.

Terms of Evaluation for HashiCorp Software
Before you download and/or use our enterprise software for evaluation purposes, you will need to agree to a special set of terms (“Agreement”), which will be applicable for your use of the HashiCorp, Inc.’s (“HashiCorp”, “we”, or “us”) enterprise software.
PLEASE NOTE THAT THE SOFTWARE MAY NOT BE USED, DEPLOYED OR INSTALLED IN THE PEOPLE’S REPUBLIC OF CHINA.


Regards,
Jagadeesh
