### ISSUE TITLE
Unable to SSH to target server from Windows OpenSSH

### ISSUE THREAD

**Issue by getelevated** [hashicorp/vault#6336]
**Describe the bug**
Unable to ssh from a Windows 10 client with CA mode

**To Reproduce**
In Windows 10/2019 with OpenSSH, set the TOKEN and ADDR variable, run the command:
vault ssh -mount-point=path -mode=ca -role=default admin@serveraddress I receive the error "Load key "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\vault_ssh_ca_admin_address.248391766335": invalid format".  ssh-keygen -L -f on that file shows it as valid.

This same setup works fine from a Mac

**Expected behavior**
SSH connection to the target server.

**Environment:**
1.0.3
1.0.3
Windows 2019/10 version 1809 Build 17763.316

SSH verbose logs
vault ssh -mount-point=bastion-ssh -mode=ca -role=default admin@address -v
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Connecting to address [address] port 22.
debug1: Connection established.
debug1: identity file C:\\Users\\Administrator\\.ssh\\id_rsa type 0
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\Administrator\\.ssh\\id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\vault_ssh_ca_admin_ address.248756529363 type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\vault_ssh_ca_admin_ address.248756529363-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4p1 Debian-10+deb9u3
debug1: match: OpenSSH_7.4p1 Debian-10+deb9u3 pat OpenSSH* compat 0x04000000
debug1: Authenticating to address:22 as 'admin'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:OkpUaYBH06V2HkUDBQMvF1VkbFtiRt+NqJqeOpAzic8
debug1: Host 'address' is known and matches the ECDSA host key.
debug1: Found key in C:\\Users\\Administrator/.ssh/known_hosts:2
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:vu26GvZfhhdw9CjPrtcN6I5LoVnoXiWn8/rtJn9y9EA C:\\Users\\Administrator\\.ssh\\id_rsa
debug1: Authentications that can continue: publickey
debug1: Trying private key: C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\vault_ssh_ca_admin_ address.248756529363
Load key "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\vault_ssh_ca_admin_address.248756529363": invalid format
debug1: No more authentication methods to try.
admin@ address: Permission denied (publickey).
failed to run ssh command: exit status 255

**Comment by tidalf** [comment]
Not sure it's related but I run that:  
$PSDefaultParameterValues['Out-File:Encoding'] = 'utf8' 
before using the write command on windows. (the default term encoding is utf16)

**Comment by jefferai** [comment]
Any chance your OpenSSH is configured to use PuTTY/Plink key file format?

**Comment by getelevated** [comment]
@tidalf nailed it.  I set the utf using that PS command and it worked great.  Thank you!  This can be closed.

**Comment by getelevated** [comment]
I was actually misinformed that this was solved.  It turns out I had left a file in place that helps fix the issue.  When I run vault ssh, there is a temp cert that is downloaded to C:\Users\ADMINI1\AppData\Local\Temp\2\.  If I take that file, copy it to the .ssh folder, and rename it id_rsa-cert.pub the vault ssh command works.  If I leave the temp file in place, I continue to get the invalid format error.

**Comment by getelevated** [comment]
> Any chance your OpenSSH is configured to use PuTTY/Plink key file format?

This issue occurs on a fresh install of Windows 2019, so I haven't modified anything.

**Comment by philband** [comment]
I can confirm this issue on Windows 10 (1809).

Command run:
```cmd
vault.exe ssh -mode=ca -role=admin -mount-point=ssh-client -private-key-path=~/.ssh/id_ed25519 -public-key-path=~/.ssh/id_ed25519.pub root@host -vvv
```

I tried to debug the issue a litte more and to me it looks like some kind of race condition/file locking issue:

Exempt from the log:
```
debug2: key: C:\\Users\\Administrator\\.ssh\\id_ed25519 (00000225CD6E1110), explicit
debug2: key: C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\vault_ssh_ca_root_host.698651587 (0000000000000000), explicit
```
The all-zeroes part I would assume to be the fingerprint or hash of the certificate - being all zero I started to wonder.
I added some pause after the writing routines for the certificate in the ssh authentication process, printed the command and tried executing ssh manually while the vault CLI was paused - with the same error.

After I let the vault CLI exit, I can execute the exact same ssh command without issues:
```cmd
ssh -i "C:\Users\Administrator\.ssh\id_ed25519" -i C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\vault_ssh_ca_root_host.698651587 root@host -vvv
```
```
debug2: key: C:\\Users\\Administrator\\.ssh\\id_ed25519 (0000019DB5843570), explicit
debug2: key: C:\\\\Users\\\\ADMINI~1\\\\AppData\\\\Local\\\\Temp\\\\vault_ssh_ca_root_host.698651587 (0000019DB5843260), explicit
```

Full log:
https://gist.github.com/philband/058157b71caffd445f1bc94814f1fa96
