### ISSUE TITLE
I am getting security token <nil>

### ISSUE THREAD

**Issue by illectronic** [hashicorp/vault#6341]
vault write aws/creds/developers  credential_type=federation_token policy=@federation.json

federation.json

{
  "Versios": "2012-10-17",
  "Statement": {
    "Effect": "Allow",
    "Action": [
      "iam:*",
      "sts:*"
    ],
    "Resource": "*"
  }
}

result:

Key                Value
---                -----
lease_id           aws/creds/developers/bTemMbgGnebrSbEP0941NMxQ
lease_duration     10h
lease_renewable    true
access_key         <key is here>
secret_key         <secret is here>
security_token     <no security token>

I need a security token for assume role. Thanks

**Comment by illectronic** [comment]
I was able to get a token doing this:vault write aws/roles/developers role_arns=arn:aws:iam::294109425352:role/role_developers credential_type=assumed_role

But I can not assume a role I get the same error

**Comment by michelvocks** [comment]
Hi @illectronic!

> But I can not assume a role I get the same error

Would you mind to share the error message you mentioned? 

Cheers,
Michel

**Comment by catsby** [comment]
Hello - we haven't heard anything for a few weeks, so I'm going to close this for now. For future questions or discussion such as this, please checkout https://discuss.hashicorp.com/c/vault

Thanks!
