### ISSUE TITLE
[S3 backend] vault operator migrate gets stuck in infinite loop if key with empty name exists

### ISSUE THREAD

**Issue by jtcressy** [hashicorp/vault#6369]
**Describe the bug**
Somehow, there was a file with an empty name in some key in S3.
For example:
```
user@ubuntu:~$ aws s3 ls s3://myvaultbucket/logical/<some_uuid_key>/ 
2019-02-04 19:42:03 40 
2019-02-04 19:45:13 159 appd 
2019-02-15 20:21:33 103 aws
```
And during `vault operator migrate` it had attempted to run List() on this prefix.
I added a simple fmt.Println of what prefix it was listing inside the List() function in physical/s3/s3.go and when it reached this key it looped forever. 

This 40-byte file halted our migration operation for more than a week while we were on support with HashiCorp trying to figure out why our migrate command stopped in its tracks without any helpful output.

**To Reproduce**
1. Try to put an empty key in S3, maybe using `aws s3 cp somefile.txt s3://myvaultbucket/test//`
1a. It sounds like some people have been able to accidentally do this with the aws java api. [here](https://stackoverflow.com/questions/33753269/how-to-delete-a-file-with-an-empty-name-from-s3)
2. Run `vault operator migrate` with this bucket as the storage source. 
3. Command hangs on the previously successful key and prints no output as to what the command is actually doing.

**Expected behavior**
Catch the empty (or otherwise non-printable) key in the list returned by List() and print a descriptive error to stdout and move on to the next key.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.2+pro
* Vault CLI Version (retrieve with `vault version`): 1.0.2+pro
* Server Operating System/Architecture: linux/amd64

**Comment by briankassouf** [comment]
Likely do to #5596 which was fixed by hashicorp/vault-plugin-secrets-kv#18 and the migrate command loop was fixed by #6371
