### ISSUE TITLE
confusing UX: key-shares and key-threshold not respected when using auto unseal

### ISSUE THREAD

**Issue by StephenWithPH** [hashicorp/vault#6370]
**Describe the bug**
When following the tutorial https://learn.hashicorp.com/vault/operations/autounseal-gcp-kms#step-2-test-the-auto-unseal-feature, users are told to enter `$ vault operator init -key-shares=1 -key-threshold=1`:

![screenshot from 2019-03-07 11-20-37](https://user-images.githubusercontent.com/2990492/53982968-0ea8e800-40cb-11e9-8fb0-f4bb04d79ca7.png)

In my experience, those values are ignored. Vault initializes with 5 key shares and a key threshold of 3. *Note that auto-unseal is still working; this appears to be only bad UX.*

**To Reproduce**
1. Provision a Vault cluster on GCP using KMS per the linked tutorial.
1. SSH into one of the Vault nodes to perform the initial unseal.
1. `# vault operator init -address=http://localhost:8200 -key-shares=1 -key-threshold=1`
1. Observe that this succeeds, but Vault reports `Recovery key initialized with 5 key shares and a key threshold of 3.`

**Expected behavior**
**Either** Vault honors the params and uses 1 key share and with a key threshold of 1...
**or** Vault reports that `key-shares` and `key-threshold` are ignored when configured to auto unseal (see `Additional Context` below)

**Environment:**
* Vault Server Version: `Version 1.0.3`
* Vault CLI Version: `Vault v1.0.3 ('85909e3373aa743c34a6a0ab59131f61fd9e8e43')`
* Server Operating System/Architecture: Docker...

| REPOSITORY |TAG | IMAGE ID |
|-------------------|-------|--------------|
|vault               |1.0.3|9bc9659cccae|

Vault server configuration file(s):

```hcl
api_addr     = "<redacted>"
cluster_name = "dev"
log_level    = "warn"
listener "tcp" {
  address         = "0.0.0.0:8200"
  cluster_address = "0.0.0.0:8201"
  tls_disable     = "true"
}
seal "gcpckms" {
  project     = "<redacted>"
  region      = "us-west1"
  key_ring    = "<redacted>"
  crypto_key  = "<redacted>"
}
storage "gcs" {
  bucket     = "<redacted>"
  ha_enabled = "true"
}

```

**Additional context**
It seems this behavior is by design. https://www.vaultproject.io/docs/concepts/seal.html#auto-unseal states:
>When using a Auto Unseal, there are certain operations in Vault that still require a quorum of users to perform an operation such as generating a root token. During the initialization process, a set of Shamir keys are generated that are called Recovery Keys and are used for these operations.

Perhaps the docs need to be better tied together, or there needs to be clearer feedback that `key-shares` and `key-threshold` are not relevant for auto unseal.

Meanwhile, https://www.vaultproject.io/docs/commands/operator/init.html#hsm-and-kms-options includes `recovery-shares` and `recovery-threshold` options. I suspect this is what users *should* be directed to use.

**Comment by jefferai** [comment]
We don't know until after the fact that they were ignored, but we could display a warning after initialization if those were provided.

**Comment by StephenWithPH** [comment]
@michelvocks ... thank you very much! Looks great.

**Comment by danlsgiga** [comment]
@jefferai sorry commenting in a closed issue. Just a quick question... after migrating from shamir with 5 key shares and 3 as threshold to auto unseal I noticed Vault has only 1 for key share and threshold... is that expected?
