### ISSUE TITLE
RabbitMQ certificate signed by unknown authority (vault certificate)

### ISSUE THREAD

**Issue by koalalorenzo** [hashicorp/vault#6372]
I have configured RabbitMQ to use HTTPS certificate generated by Vault
When run RabbitMQ configuration:
```
vault write rabbitmq/config/connection connection_uri="https://123.45.67.89:15471" username="username" password="password"
```

I always get
```
Get https://123.45.67.89:15471/api/users/: x509: certificate signed by unknown authority
```

This is very similar to https://github.com/hashicorp/vault/issues/2316 with the exception that I have added the root CA certificate to `/etc/ssl/certs` and correctly run `update-ca-certificates`. I wish that Vault was smart enough to consider its own certificates valid.  To validate that, I ran a simple curl command from the machine running Vault as a daemon: curl is not failing but vault is.

How can I make sure that Vault knows that its certificates are working fine?

**Comment by koalalorenzo** [comment]
As a reference I am generating the certificates like this:

```
vault write pki/roles/rabbit \
    allowed_domains=123.45.67.89 \
    max_ttl=8928h \
    require_cn=false
```

**Comment by jefferai** [comment]
> that I have added the root CA certificate to /etc/ssl/certs and correctly run update-ca-certificates

On which host did you add this -- your client or the Vault server host? Did you restart Vault after? (I'm not sure whether or not Go picks up changes to the system cert store in the middle of running, but it can't hurt).

Is the Rabbit server presenting the intermediate CA cert to the client?

**Comment by koalalorenzo** [comment]
@jefferai all the hosts have the CA that I got using:

```
curl https://123.45.67.89/v1/pki/ca/pem > /etc/ssl/certs/vault.crt
```

They always have 0644 as permissions.

It would be nice to have Vault understanding this out of the box.

**Comment by jefferai** [comment]
You can have many different PKI mounts, each with their own CA, that may be used for any purpose, including extremely restrictive ones. There is no guarantee that Vault will then be the consumer of such certificates; most users would consider this a serious security issue if Vault were to just automatically trust any CA cert in any of its mounts.

Have you tried restarting Vault? Maybe it (meaning the underlying Go libraries) caches roots from the system on startup.

**Comment by ncabatoff** [comment]
> Have you tried restarting Vault? Maybe it (meaning the underlying Go libraries) caches roots from the system on startup.

That has been my experience.

**Comment by koalalorenzo** [comment]
Gotcha, rebooting seems to have fixed the issue.

@jefferai any plan to have an option to enable a behaviour so that Vault will consider its own certificates valid automatically? Something that you can disable?

**Comment by jefferai** [comment]
There is no such thing as "its own certificates"; any particular mount can be used for any particular purpose. From the perspective of Vault, it's not issuing certificates; a plugin is returning some data that it is returning to the client. To Vault's core that data is opaque, and not something it would ever share with a different plugin.

**Comment by koalalorenzo** [comment]
Consider this as a use case where it would ease a lot the whole configuration and securing our system, without having to do extra steps to ensure that Vault understand that the certificates that he has generated are valid.

Consider it as an idea, an option.

Just think about it.

**Comment by jefferai** [comment]
We have considered it in the past; you're not the only person to ask about this. There are no current plans to do so because it breaks Vault's operational model where data from plugins are silo'd from each other and opaque to Vault.
