### ISSUE TITLE
OTP Base32 Key Should Get Uppercased Before Validation

### ISSUE THREAD

**Issue by farvour** [hashicorp/vault#6396]
**Describe the bug**
When vault attempts to pre-validate the key secret, it passes the decode operation along to the golang `base32.StdEncoding.DecodeString()` method. This method is strict, and requires all base32 values to be upper cased apparently. Vault fails and refuses to set the secret key.

**To Reproduce**
1. Enable the vault TOTP secret backend `vault secret enable totp`
1. Attempt to write a key with a secret/key value that is already in base32, but lower case.

**Expected behavior**
Vault should validate the string store it, and then it'll get passed along to the totplib unmodified.

**Environment:**
* Vault version 1.0.2

**Additional context**
Vault doesn't try to upper-case the input payload before failing.

https://github.com/hashicorp/vault/blob/9a222b0faffe9c0b22eddde15dd32f55bbd6f7f9/builtin/logical/totp/path_keys.go#L378-L382

There is a known issue with Google (and other providers) issuing TOTPs with lower cased base32 values which was 'addressed' in the parent otp library vault is using: 
https://github.com/pquerna/otp/issues/24

**Comment by jefferai** [comment]
It seems like this isn't actually a problem, since the OTP library already does it? I'm not quite clear on the ask here.

**Comment by jefferai** [comment]
Oh, OK, got it. The issue isn't that you want us to uppercase as another check before sending it to OTP, the issue is that the Go base32 lib won't accept it.

**Comment by farvour** [comment]
Correct!

Thank you!
