### ISSUE TITLE
Docs encourage a default behaviour of entering secrets via the command line

### ISSUE THREAD

**Issue by harry-wheildon** [hashicorp/vault#64]
Hi all - first up, I really like the idea of Vault and appreciate the work Hashicorp are doing to make a free software password manager, of which it's been really hard to find a good quality option.

What I don't like is the fact that for writing data, the docs encourage you to enter secrets through the command line, which could expose secrets through shell history or the process table.

If this is fixed I will strongly consider you as a replacement for our current solution (http://www.passwordstore.org, note that they throw the user into an editor before writing data, which may provide inspiration for an alternative).

I'm aware that there is the option to write data from a file, but this isn't default and there's the possibility of the file being accidentally left behind. I think a purely editor-based solution would be best?

**Comment by sethvargo** [comment]
@harry-wheildon you can also read passwords from stdin too :smile:

**Comment by mitchellh** [comment]
@harry-wheildon I think we can do better about making a note on the website that there are other methods of entry. For a getting started guide I think CLI is best: the goal of a getting started guide is to show people what software can do and get them to a moment of achievement as quickly as possible. It isn't to make them operational experts.

But I think highlighting that other options exist in the getting started guide is worth it. I'll do so. Thanks for the feedback!

For the remainder of the docs, the CLI remains a convenient (though I agree with you less secure) method of showcasing how things work. We expect that actual users of the software should understand the behavior of their systems to know if their shell will maintain the history or not.

**Comment by mitchellh** [comment]
Done here: https://github.com/hashicorp/vault/commit/991097acc5a81e1790ca098231043811471b6767

**Comment by mitchellh** [comment]
I know the best solution would be to remove CLI-based entry completely. Likewise, you can even unseal via the CLI (but we don't document that). Unfortunately, we make a tradeoff here between having a feature exist at all and user experience. The existence of the feature allows users to potentially shoot themselves in the foot, but it doesn't architecturally compromise Vault itself. Good documentation and operational best practices and this issue doesn't exist.

Having CLI-based entry for secrets and unseal are an important part of making our interactive tutorial work as well as making experimenting with Vault as frictionless as possible. And this is important for mindshare and adoption. 

All of the above is important for a tool to succeed, and we balance tradeoffs accordingly. But again I'll reiterate we wouldn't compromise the core architecture of Vault's security.
