### ISSUE TITLE
Vault error configure MSSQL

### ISSUE THREAD

**Issue by leonardosmartins** [hashicorp/vault#6416]
I am getting the following error when trying to write a configuration for a MSSQL database.

error creating database object: error verifying connection: lookup u1t on 127.0.0.1:53: no such host

**Steps to reproduce the behavior:**
Start the vault server.
Enable the database secret engine.
Run the command:
vault write database/config/teste-mssql plugin_name=mssql-database-plugin connection_url='sqlserver://{{username}}:{{password}}@mymssql.com.br:1433' allowed_roles="*" username="vault" password="mypassword@123"

**Expected behavior:**
Write the database configuration without throwing the error

**Environment:**
Vault Server Version: 1.0.3
Vault CLI Version: 1.0.3
Server Operating System/Architecture: Ubuntu

**Comment by tyrannosaurus-becks** [comment]
Hi @leonardosmartins, thanks for opening this issue. I can duplicate that error when I don't start MSSQL or when there's no MSSQL running at the given address. Can you troubleshoot your MSSQL connection parameters to see if you can use them _outside_ of Vault to connect to MSSQL from the instance on which Vault is running? Are you able to verify that MSSQL is reachable using those parameters?

**Comment by leonardosmartins** [comment]
I tested and found that the problem was in the '@' character in the password.
