### ISSUE TITLE
Unable to revoke PKI Leases

### ISSUE THREAD

**Issue by dacohen** [hashicorp/vault#6417]
**Describe the bug**
We have approximately 600k active leases in vault, the majority of which are from the PKI backend. Many of these leases have large negative TTLs, indicating they expired several weeks ago. When we attempt to revoke any of these leases, whether by calling the sys/leases/revoke endpoint, or the sys/leases/tidy endpoint, the request hangs indefinitely. Calling revoke on leases created by other auth backends works correctly. The periodic expiration process also fails to clean up these leases. No logs are produced by these failures, even at the trace level. It is also possible to list and read these leases.

We attempted to verify this wasn't caused by resource exhaustion, giving the instance 60 GB of RAM, and 8 CPU cores, double our previous allocation. This had no effect.

In addition, we've been using vault since the 0.7 release, and have gradually upgraded, keeping the same data, to v1.0.0.

**To Reproduce**
Since we've been using the same data since an earlier release, it's difficult to fully describe the current state of the instance. The primary factor seems to be number of leases, since we've successfully revoked PKI leases on another vault instance with same configuration, but a much smaller number of leases.

**Expected behavior**
We expect a call to sys/leases/revoke to succeed, instead of hanging.

**Environment:**
* Vault Server Version: v1.0.0
* Vault CLI Version: v.1.0.0
* Server Operating System/Architecture: Vault Docker Image on Kubernetes (Debian jessie/Kernel 4.4.121-k8s/Docker 17.3.2/Kubernetes v1.10.11)

Vault server configuration file(s):

```hcl
storage "s3" {
      bucket = "AN_S3_BUCKET"
      region = "us-east-1"
}

listener "tcp" {
      address = "0.0.0.0:8200"
      tls_cert_file = "PATH_TO_CERTIFICATE"
      tls_key_file = "PATH_TO_KEY"
}

telemetry {
      statsd_address = "STATSD_ADDRESS"
}

default_lease_ttl = "168h"
max_lease_ttl = "720h"
ui = true
```

**Comment by jefferai** [comment]
I think you got into this state from some old bugs, so apologies for that.

Deletion can be rather slow depending on the underlying storage; for instance in Consul it's quite slow. Are you sure that when this call appears to be hanging that deletion isn't actually happening, just slowly? We haven't seen deadlocks there in the past so I'd be surprised if in this case you are hitting a deadlock; it feels more like it's just taking a very long time.

If you want, you can also clean out those leases manually from your underlying storage, which can be faster if you can do a prefixed deletion (on Consul at least).

**Comment by dacohen** [comment]
Thanks for your response. Last week we managed to get a debugger attached to Vault, and were able to isolate the issue to the CRL build process. It seems that every time a new certificate is revoked, Vault iterates over every certificate in the CRL in order to compute the hash of the new CRL, which with our volume of certificates, was simply taking a while to run.

We solved the issue by disabling the CRL with the pki/config/crl endpoint, since we weren't using it anyway, and after a restart, noticed certificates start to get revoked.

However, we still had a very large number of old leases that weren't being revoked by the expiration manager. Looking through the code, we found an undocumented endpoint, sys/leases/tidy, which we invoked, and which seemed to clean up all of the stale leases with invalid/empty tokens. Is there a reason this isn't mentioned in the Vault API documentation?

**Comment by mdgreenfield** [comment]
FWIW, we ran into the same issue here. We're running 1.3.1 and saw about 85k PKI leases (all but 65 of which had negative TTL values). These leases were all created 2 days ago while on 1.3.1.

As described above, I was able to disable the CRL and then watch the tidy operation clean up all the negative TTL leases.
