### ISSUE TITLE
api/client doesn't honor VAULT_NAMESPACE like other env vars

### ISSUE THREAD

**Issue by AgentZombie** [hashicorp/vault#6438]
**Describe the bug**
This is similar to #618.

When using `api/client` it will honor env vars like `VAULT_ADDR` and `VAULT_TOKEN` but not `VAULT_NAMESPACE`. This must be set manually with the `Client.SetNamespace(string)` call.

**To Reproduce**
1. Given any code using namespaces, setting or clearing exported `VAULT_NAMESPACE` has no effect.
2. Using `Client.SetNamespace(string)` has the desired effect.

**Expected behavior**
If `VAULT_NAMESPACE` is available to the running command it should be used without the need to call `Client.SetNamespace(string)`.

**Comment by tyrannosaurus-becks** [comment]
That's interesting. The namespace that's set using that variable does appear to be used [here](https://github.com/hashicorp/vault/blob/master/command/base.go#L146). What version of Vault are you using?

**Comment by ncabatoff** [comment]
> That's interesting. The namespace that's set using that variable does appear to be used [here](https://github.com/hashicorp/vault/blob/master/command/base.go#L146). What version of Vault are you using?

That's code used by the vault binary.  This bug is reporting that the API called from standalone Go code, i.e. api.NewClient(), doesn't read the variable, which is true from what I can see.
