### ISSUE TITLE
Cannot remember password in Firefox

### ISSUE THREAD

**Issue by Yajo** [hashicorp/vault#6441]
**Describe the bug**
Currently, there's no way to remember the login password in Vault's web UI. At least in Firefox.

**To Reproduce**
1. Open vault UI
2. Log in via userpass
3. Firefox does not ask to save password

**Expected behavior**
I should have that option, like happens with most sites I visit.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.3
* Vault CLI Version (retrieve with `vault version`): Vault v1.0.3 ('85909e3373aa743c34a6a0ab59131f61fd9e8e43')
* Server Operating System/Architecture: Official Docker image.

**Comment by kalafut** [comment]
Have you double checked that you've not marked the domain/site as "Never Save"?  The latest FF (on Mac) prompts me to save for both Vault 1.0.3 and 1.1.

**Comment by Yajo** [comment]
With FF 66 it seems to work again. Thanks!
