### ISSUE TITLE
hundreds of thousands of vault/sys/expire/token/<long_hex>/<long_hex> entries

### ISSUE THREAD

**Issue by wwalker** [hashicorp/vault#645]
hundreds of thousands of vault/sys/expire/token/<long_hex>/<long_hex> entries in consul.
Using Consul 0.5.2, Vault 0.2.0.
They seem to have stopped being created.
What do they mean?  How can I safely clean them up?

apparently for 4 different tokens:

    wwalker@hatter:~$ jq .[].Key kv-tst-mexec1.json | grep vault/sys/expire/token | sed -e 's#/[^/]*$##' | sort | uniq -c | sort -n
        878 "vault/sys/expire/token/2d8a9812ff1f756475d147b9da7ba0a9d9ace912
      15318 "vault/sys/expire/token/84a701933fc5cf475caa48f93de3169b41177a08
      52731 "vault/sys/expire/token/aff6a25ef9399a046cb6638a31fb7dd96e725b05
     309211 "vault/sys/expire/token/bc6dd88c1fae219b8115a5a91d1335b5e40b1403

**Comment by jefferai** [comment]
You're probably reading from the generic backend extremely often so creating leases, rather than using the TTL to determine whether you need to read again.

In 0.3 this behavior will change. In the meantime, they will expire over time.

**Comment by wwalker** [comment]
Thank you.  You were correct.

**Comment by wwalker** [comment]
You say the behavior will change in the 0.3.0 release (from this morning :-) )  I dont' see any documentation on how the creation of leases for every read will change.  Where is that in the docs?

**Comment by jefferai** [comment]
It's discussed in one of the sections on the announcement blog post ("Performance Improvements for Generic"). https://hashicorp.com/blog/vault-0.3.html

It's not in the Vault docs because leases in the generic backend were always a noop. The functionality hasn't changed, as TTLs are still returned.

**Comment by wwalker** [comment]
How can one force the expiry of these?  consul currently takes 7 CPU minutes (about 8 wall clock minutes) to start because of this.  Then, after that, Vault takes 4 minutes to start.

**Comment by jefferai** [comment]
Use `revoke-prefix`: https://vaultproject.io/docs/http/sys-revoke-prefix.html
