### ISSUE TITLE
Unable to migrate seal in V1.1.0

### ISSUE THREAD

**Issue by rashmisinghgaurav** [hashicorp/vault#6455]
**Environment:**

* Vault Version: 1.1.0
* Operating System/Architecture: Linux

**Vault Config File:**

```hcl
storage "consul" {
address = "127.0.0.1:8500"
tls_skip_verify = "false"
scheme = "http"
redirect_addr = "https://vault1.**.com.:8200"
disable_clustering = "false"
}

ui = true
listener "tcp" {
address = "0.0.0.0:8200"
cluster_address = "vault1.**.com.:8201"

tls_cert_file = ""
tls_key_file = ""

tls_min_version = "tls10"
}
telemetry {
statsd_address = "localhost:8125"
disable_hostname = true
}

seal "awskms" {
disabled = "true"
region = "us-east-1"
kms_key_id = "abc"
}
```

**Startup Log Output:**

```
Error:
Could not create barrier seal! Most likely proper Seal configuration information was not set, but no error was generated.
```

**Expected Behavior:**
Migrate seal configuration from AWSKMS to Shamir

**Actual Behavior:**

**Steps to Reproduce:**

**Important Factoids:**

**References:**

I am trying to migrate the seal configuration from KMS to Shamir in Vault 1.1.0.. However, I am getting the error mentioned above.
Steps:
1. Stop running vault server
2. Update vault seal config by adding disabled flag to true
3. Start Vault server
4. Unseal vault with -migrate flag

**Comment by jefferai** [comment]
This will be fixed in 1.1.1; in the meantime you can get past this by putting 
```
seal "shamir" {
}
```
in your config.
