### ISSUE TITLE
vault-1.1.0 UI - cant configure LDAP's URL, TLS and a  number of other fields

### ISSUE THREAD

**Issue by hmalphettes** [hashicorp/vault#6465]
In the UI of Vault-1.1.0 the input for the LDAP's configure URL is not present anymore

![vault-1 1 0-ldap-configure](https://user-images.githubusercontent.com/55289/54898289-9cc40180-4f06-11e9-930e-ccd7cef731e3.PNG)

Here is how it looked in 1.0.2:

![vault-1 0 2-ldap-configure](https://user-images.githubusercontent.com/55289/54898294-a8afc380-4f06-11e9-8728-1c0a03e504c2.PNG)

**Comment by hmalphettes** [comment]
It looks like the issue is similar to the one fixed for jwt auth config here: https://github.com/hashicorp/vault/pull/6410

**Comment by meirish** [comment]
@hmalphettes thanks for filing this! We moved several of the models to generate their fields from the new OpenAPI endpoints. I'm having trouble recreating this though - are there any errors in the dev tools console?

**Comment by meirish** [comment]
@hmalphettes got a repro - looks like it's a minification issue - we'll get this fixed up!
