### ISSUE TITLE
[UI] Diffs in Vault UI editor

### ISSUE THREAD

**Issue by aditya-konarde** [hashicorp/vault#6466]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to create a new version of a secret via vault UI. I don't directly edit in the vault editor, because I need to validate the changes locally. 

My current workflow looks like this:
- Click on Create new version
- Copy the value of the old version to a local editor
- Make and Test the changes locally
- Copy paste it back to the Vault UI

At this point, I need to blindly apply the new version, which may result in some indentation errors or unintended changes. 

**Describe the solution you'd like**
I'd love to have a git-style diff preview of the changes made between versions before saving them. 

This would let mew review the changes before I `commit` them to vault. 

**Describe alternatives you've considered**
Perhaps you can add the secret to version control, and change the secret in version control to have a CI job apply it to vault. But the whole point of vault is to not store secrets in version control :)

**Explain any additional use-cases**
None that I can think of at the moment. 

**Additional context**
Happy to provide this as requested.

**Comment by Monkeychip** [comment]
@ditya-konarde The diff view will be coming to 1.10. Hopefully, it will help with your workflow. The only thing this doesn't do is show before you have saved a version. See PR here: https://github.com/pulls?q=is%3Apr+author%3AMonkeychip+archived%3Afalse+
