### ISSUE TITLE
Consul Secret Engine is not respecting the defined TTLs for ACL Token leases

### ISSUE THREAD

**Issue by danlsgiga** [hashicorp/vault#6467]
**Describe the bug**
After implementing Vault's Consul Secret Engine in our environment we noticed Vault is revoking Consul ACL Tokens leases way before the lease expires and even when it is being renewed constantly.

**To Reproduce**
1. Setup a Consul node / cluster with ACLs enabled / configured
2. Setup a Vault node / cluster with a Consul Secret Engine enabled and configured to create Consul ACL tokens
3. Create simple Vault Role mapping to Consul ACL Policies name `my-role`.
4. Tune Vault's Consul Secret Engine mountpoint with `-default-lease-ttl=48h` and `-max-lease-ttl=72h`
5. Confirm the new settings were applied via `vault secrets list -detailed`. My output was:
```
Path             Plugin       Accessor              Default TTL    Max TTL    Force No Cache    Replication    Seal Wrap    Options           Description
----             ------       --------              -----------    -------    --------------    -----------    ---------    -------           -----------
consul/          consul       consul_22b38e40       172800         259200     false             replicated     false        map[]             n/a
```
6. Issue a new Consul ACL token via Vault: `vault read consul/creds/my-role` and capture the `lease_id` output
7. Setup a cron job to renew the `lease_id` lease every 15 minutes running `vault lease renew consul/creds/my-role/vMHlCTdVWU6PeAFhk6cXwnX9`
8. Verify in Vault that the lease is being successfully renewed.
8. In less then 2 hours (randomly), the lease will be revoked and the Consul ACL token will be removed from Consul.

**Expected behavior**
Vault to respect the configured TTL values, the lease renewals and revoke leases only after the TTLs expire.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    5
Threshold                3
Version                  1.1.0
Cluster Name             us-east-1
Cluster ID               cluster-id
HA Enabled               true
HA Cluster               https://x.x.x.x:8201
HA Mode                  active
Active Node Address      https://x.x.x.x:8200
```
* Vault CLI Version (retrieve with `vault version`):
```
Vault v1.1.0 ('36aa8c8dd1936e10ebd7a4c1d412ae0e6f7900bd')
```

* Server Operating System/Architecture:
CentOS Linux release 7.6.1810 (Core)
x86_64

Vault server configuration file(s):

```hcl
cluster_name = "mycluster"
ui = true
api_addr = "https://x.x.x.x:8200"

storage "consul" {
  address = "127.0.0.1:8500"
  path = "vault/"
  token="x-x-x-x-x"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/vault/cert.crt.pem"
  tls_key_file = "/vault/cert.key.pem"
  tls_require_and_verify_client_cert = "false"
  tls_min_version = "tls12"
  tls_prefer_server_cipher_suites = "true"
  tls_cipher_suites = "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
}

telemetry {
  dogstatsd_addr = "127.0.0.1:8125"
}

seal "awskms" {
  kms_key_id = "alias/kms-seal"
}
```

**Additional context**
We started seeing this problem while using the new Vault Agent but we were able to confirm the same behaviour even without using Vault Agent.

Moreover, we are running Consul 1.4.3 in the same nodes as Vault

For now we had to disable ACLs in our Consul Cluster since Vault was revoking agents tokens constantly and causing disruptions.

**Comment by ncabatoff** [comment]
Hi @danlsgiga,

Thank for the detailed bug report.  I have so far been unable to reproduce your problem, though it's only been 2.5hrs so far since I created the token.  The script I've been using is [here](https://github.com/ncabatoff/vault-experiments/blob/master/bin/vault-consul-engine.sh); I think it faithfully duplicates your reproduction steps, but let me know if you see any discrepancies.

```bash
vagrant@jessie:/vagrant/consul$ CONSUL_HTTP_ADDR=http://127.0.0.1:8585 CONSUL_HTTP_TOKEN=`jq -r .data.token < /tmp/consulcDIQOW/consultoken.json ` consul members
Node    Address         Status  Type    Build  Protocol  DC   Segment
jessie  10.0.2.15:8303  alive   server  1.4.4  2         dc1  <all>
vagrant@jessie:/vagrant/consul$ CONSUL_HTTP_ADDR=http://127.0.0.1:8585 consul members
vagrant@jessie:/vagrant/consul$ curl -s --header X-Vault-Token:\ $VAULT_ROOT_TOKEN --request PUT --data '{"lease_id": "consul/creds/my-role/D2phHvYxbo2pB8WV6UF9fRuN"}' $VAULT_ADDR/v1/sys/leases/lookup |jq .data
{
  "expire_time": "2019-03-28T22:45:07.828284524Z",
  "id": "consul/creds/my-role/D2phHvYxbo2pB8WV6UF9fRuN",
  "issue_time": "2019-03-26T20:15:06.750005893Z",
  "last_renewal": "2019-03-26T22:45:07.828284604Z",
  "renewable": true,
  "ttl": 172746
}
```

**Comment by ncabatoff** [comment]
I left it running overnight, still no reproduction:

```
vagrant@jessie:/vagrant/consul$ curl -s --header X-Vault-Token:\ $VAULT_ROOT_TOKEN --request PUT --data '{"lease_id": "consul/creds/my-role/D2phHvYxbo2pB8WV6UF9fRuN"}' $VAULT_ADDR/v1/sys/leases/lookup |jq .data
{
  "expire_time": "2019-03-29T11:45:14.238930699Z",
  "id": "consul/creds/my-role/D2phHvYxbo2pB8WV6UF9fRuN",
  "issue_time": "2019-03-26T20:15:06.750005893Z",
  "last_renewal": "2019-03-27T11:45:14.238930775Z",
  "renewable": true,
  "ttl": 171928
}
```

**Comment by danlsgiga** [comment]
Hi @ncabatoff,

Thanks for trying to reproduce this issue.

So, I just realized I mentioned using Vault Agent and that would be failing even without Vault Agent... but what I meant there was to say, even not using Vault Agent *Caching*, the issue was still happening.

So, I'm using the Vault Agent running locally on port 8100 and targeting it for all my Vault requests.

Here is my Vault Agent config.

```hcl
exit_after_auth = false

vault {
  address = "https://vault.service.consul:8200"
}

auto_auth {
  method "aws" {
    mount_path = "auth/aws"
    config = {
      type = "iam"
      role = "my-role"
    }
  }

  sink "file" {
    config = {
      path = "/dev/shm/.vault-token"
    }
  }
}

cache {
  use_auto_auth_token = true
}

listener "tcp" {
  address = "127.0.0.1:8100"
  tls_disable = true
}
```

I'm not sure if Vault Agent would be capable of revoking leases on behalf of Vault.

**Comment by ncabatoff** [comment]
Ok, interesting.  I've modified my script to go through agent and we'll see what happens over the next few hours.

I don't believe Vault Agent ever revokes leases, though with cacheing enabled it should take care of doing the renewing for you, for secrets generated using the auto-auth token.

Does your cronjob that renews leases go through the agent or hit Vault directly?

**Comment by briankassouf** [comment]
@danlsgiga What is the configured TTL for the aws auth method you're using? Perhaps the token is being expired and therefore all the leases created by that token are being revoked?

**Comment by danlsgiga** [comment]
@briankassouf crap, you seem to have nailed it! My AWS auth method TTL is set to 15 minutes and max to 1 hour. Which explains Vault revoking all the leases. Is that the expected behaviour?

@ncabatoff The lease renewals are being called through the Vault Agent as well and it seems to work fine, since I can see the renewalTime being updated in the lease.

**Comment by ncabatoff** [comment]
> In that case, the Vault Agent should be renewing my AWS Auth token before it expires, shouldn't it?

It is renewing it regularly, before the 15m TTL expires.  However it can't do anything once the max TTL is reached.  At that point it has to re-authenticate and get a new token.

> Is that the expected behaviour? 

Yes, although it's not as well documented as it could be.  See the [token concepts](https://www.vaultproject.io/docs/concepts/tokens.html#token-hierarchies-and-orphan-tokens) doc where it says "When a parent token is revoked, all of its child tokens -- and all of their leases -- are revoked as well. "

**Comment by danlsgiga** [comment]
Ok, this all makes sense to me now. I just had the idea that while a token is being renewed before its default TTL, it would be valid.

In this case, what is the best solution you could suggest in order for us to have the Vault Agent renewing the aws auth tokens indefinitely?

We are looking for a mechanism to keep Consul ACLs being provided via API at startup and we have some things in place using systemd to create a Consul ACL Token via Vault every time consul is started/restarted or  the vault-agent is started/restarted. But we don't have any ways of providing Consul a new ACL token everytime a new AWS auth token is created.

**Comment by ncabatoff** [comment]
I don't know about *best*, but the simplest option for now is to set your max TTL to a very high value.  I will ask around and see if there are better alternatives.

**Comment by calvn** [comment]
If you set a non-zero `period` value on the role, you can generate a token that can be renewed indefinitely as long as renewal takes place before the `period`'s expiry value.

See: https://www.vaultproject.io/api/auth/aws/index.html#period

**Comment by danlsgiga** [comment]
@calvn that seems to be a reasonable solution. So, by using `period` on the role I'm effectively overriding either `ttl` or `max_ttl`? Do I need to set my `max_ttl` to 0?

**Comment by calvn** [comment]
By providing a `period` value, the token effectively becomes a [periodic token](https://www.vaultproject.io/docs/concepts/tokens.html#periodic-tokens). If the existing role already has a `max_ttl` value try unsetting/overriding it by setting it to 0.

**Comment by briankassouf** [comment]
Going to close since this is working as expected and #6489 was made to improve the documentation

**Comment by danlsgiga** [comment]
Commenting here just to confirm the suggestions offered here worked like a charm. After changing my AWS auth roles to use `period` and setting `max_ttl` to 0 everything is working as expected... I can see the Vault Agent renewing not only the AWS Auth Token leases but also the Consul ACK token leases.

Thanks a lot!!!
