### ISSUE TITLE
Require api_addr when starting Vault

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [hashicorp/vault#6487]
In the Vault configuration, `api_addr` is required when enabling clusters or plugins. If it's not provided, plugins will fail _much_ later. They'll be successfully added to the plugin directory, successfully enabled, but when you try to address them through their API endpoints, they'll fail with no output regarding `api_addr` needing to be set. This leads to fairly common issues where people are attempting to mount plugins but they don't work, and it's not obvious that `api_addr` needs to be set.

It would be nice to make this more obvious. Probably would be good to require it at startup. This would break backwards compatibility to some degree, however it would inform the person starting Vault that it was needed right away when it's easy to correct. Alternatively, we could fail more loudly when attempting to cluster or add a plugin, but the person attempting to do that _may not_ be a person with the ability to update the Vault config and restart the instance.

**Comment by tyrannosaurus-becks** [comment]
Here's just one example of an issue posted that was this: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/CWaRlTnIwSQ/dTDKCbr1BAAJ

**Comment by mikegreen** [comment]
Have had 2 customers hit this recently, I believe its when you're familiar w/ OSS and move to Enterprise. 
I think at the min we need to call this out better in the doc here:
https://www.vaultproject.io/docs/configuration/

To state it is required. But I really really agree we should log or even fail if not set.

**Comment by aphorise** [comment]
I'll close this request as there's likely been several improvements and call outs for the **`api_addr`** parameter - as per the screenshot below.

I also believe in the most recent version (1.11.x at the time of writhing) that parameter as well as `cluster_addr` default to the first available bind bind address as per the tcp listener stanza.

Hopefully more suggestion and PR will arise as required if any further clarity is still required. Thank you everyone!

![image](https://user-images.githubusercontent.com/974854/187995353-746e18db-d049-4b25-9955-da0a28828a08.png)
