### ISSUE TITLE
Unwrap failures are not logged

### ISSUE THREAD

**Issue by nvx** [hashicorp/vault#6491]
**Describe the bug**
Attempting to unwrap an invalid wrapping token, or unwrapping an already unwrapped wrapping token does not result in any log message appearing in the audit log. This is surprising to me as even requests to the metrics endpoints always generates log messages.

**To Reproduce**
1. Configure vault with at least one audit device (I used file)
2. Tail audit log and observe other actions are producing audit log entries
3. Run `vault unwrap invalid-token`
4. See error returned from server `* wrapping token is not valid or does not exist`
5. Observe nothing added to the audit log

**Expected behavior**
I expect every request to Vault to appear in the audit log.

**Environment:**
* Vault Server Version: 1.1.0
* Vault CLI Version: 1.1.0
* Server Operating System/Architecture: Linux x64

**Comment by jefferai** [comment]
Hi there,

We do validation checks on wrapping tokens before they hit the main request flow, which is why they don't hit audit. That said, if we're auditing normal invalid tokens, we should audit this too, so we'll get that added!
