### ISSUE TITLE
Vault 1.1.0: Creating pki role(s) fails

### ISSUE THREAD

**Issue by reiterbenjamin** [hashicorp/vault#6499]
Hey there,

**Description**
Since the new version 1.1.0, I'm not able to create pki roles anymore (I tried via curl, cli and gui).
In the gui under "details", everything is empty. I'm also not able to edit the role, because no fields are visible.

**To Reproduce**
1. Open GUI (or try via CLI or API)
2. Create pki secrets engine
3. Try to create a pki role
4. No fields are visible (e.g. key bits, ttl, ou, allowed domains, server flag, ...)

The API returns "204". The CLI says "Success! Data written to: pki/roles/test".

**Expected behavior**
Role parameters are present and editable

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.1.0
* Vault CLI Version (retrieve with `vault version`): 1.1.0
* Server Operating System/Architecture: CentOS 7.6.1810

Vault server configuration file(s):

```hcl
ui = true

storage "consul" {
  address = "127.0.0.1:8500"
  path = "vaulttest/"
  token = "XXX"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  cluster_address = "XXX:8201"
  tls_disable = 1
  #tls_cert_file = "/etc/ssl/certs/XXX_test_intern.crt"
  #tls_key_file = "/etc/ssl/certs/XXX_test_intern.key"
}

api_addr = "http://XXX:8200"
cluster_addr = "https://XXX:8201"
```

With version 1.0.3 everything works fine!

**Comment by jefferai** [comment]
Note for UI team -- I wasn't able to reproduce any issue on the CLI, but -- any known issues on the UI side in 1.1?

**Comment by meirish** [comment]
Yes, this was fixed in https://github.com/hashicorp/vault/pull/6474 and will be out in 1.1.1.
