### ISSUE TITLE
Deprecated 'Initialize()' method still in database plugin interface

### ISSUE THREAD

**Issue by niekbosch** [hashicorp/vault#6508]
**Describe the bug**
There is still a deprecated 'Initialize()' method in the database plugin interface:
https://github.com/hashicorp/vault/blob/26db100e0165cef6b2c6af45a883b2f3373b3a7b/builtin/logical/database/dbplugin/plugin.go#L29

(Link is to a specific commit, which is the latest commit in `master` at this moment)

Unless I don't understand Vault version numbers, we are already way past v0.13 and thus, this method should be removed. And, maybe more important, as the method is not mentioned in the documentation, this is a bit confusing:

https://www.vaultproject.io/docs/secrets/databases/custom.html#plugin-interface

**To Reproduce**
n/a

**Expected behavior**
Either an updated documentation, or, preferably, to have the deprecated function removed from code.

**Environment:**
* Vault Server Version (retrieve with `vault status`): n/a
* Vault CLI Version (retrieve with `vault version`): n/a
* Server Operating System/Architecture: n/a

Vault server configuration file(s): n/a

**Additional context**
If, while developing a database plugin, I am importing the wrong package. Then apparently this is not clear from the documentation either. I am new to Go though, so excuse me if I am making an obvious rookie mistake.

**Comment by tyrannosaurus-becks** [comment]
@niekbosch I came across the same thing last week! You're totally correct, `Initialize` is still there though it's marked deprecated and was intended to be stripped in an earlier version of Vault. 

Until it's actually stripped, you should be fine just calling `Init` inside it [like this](https://github.com/hashicorp/vault/blob/master/plugins/database/mongodb/connection_producer.go#L41-L44).

**Comment by briankassouf** [comment]
We haven't removed it yet due to the fact that it will break backwards compatibility for already compiled plugins. We use a plugin versioning system and we cannot safely remove the function until we bump that version, which generally doesn't happen very often. Likely we will remove it during a future plugin bump (that comment is out of date, and I will update it) As @tyrannosaurus-becks said the existing solution is to just call Init from inside that function.

**Comment by niekbosch** [comment]
Thanks for the replies. I do call `Init` indeed as tyrannosaurus suggests. Good to have confirmation that this solution is a good one.
