### ISSUE TITLE
Vault getting sealed frequently

### ISSUE THREAD

**Issue by infa-svijayak** [hashicorp/vault#6509]
We are running vault in a container based environment and we have setup a monitoring for checking the sealed status. Multiple times a day we get the response code as 429 which we figured out that it is in stand by mode after unsealing. Here are the logs from our container

2019/03/13 17:02:34.778593 [WARN ] core: leadership lost, stopping active operation
2019/03/13 17:02:34.784756 [INFO ] core: pre-seal teardown starting
2019/03/13 17:02:34.784778 [INFO ] core: stopping cluster listeners
2019/03/13 17:02:34.784791 [INFO ] core: shutting down forwarding rpc listeners
2019/03/13 17:02:34.784821 [INFO ] core: forwarding rpc listeners stopped
2019/03/13 17:02:34.894471 [INFO ] core: rpc listeners successfully shut down
2019/03/13 17:02:34.894512 [INFO ] core: cluster listeners successfully shut down
2019/03/13 17:02:34.894542 [INFO ] rollback: stopping rollback manager
2019/03/13 17:02:34.894610 [INFO ] core: pre-seal teardown complete
2019/03/13 17:02:34.920053 [INFO ] core: acquired lock, enabling active operation
2019/03/13 17:02:34.959278 [INFO ] core: post-unseal setup starting
2019/03/13 17:02:34.960832 [INFO ] core: loaded wrapping token key
2019/03/13 17:02:34.965465 [INFO ] core: successfully mounted backend: type=generic path=secret/
2019/03/13 17:02:34.965589 [INFO ] core: successfully mounted backend: type=system path=sys/
2019/03/13 17:02:34.965623 [INFO ] core: successfully mounted backend: type=consul path=*********/
2019/03/13 17:02:34.965649 [INFO ] core: successfully mounted backend: type=consul path=*************
2019/03/13 17:02:34.965672 [INFO ] core: successfully mounted backend: type=consul path=**************
2019/03/13 17:02:34.965694 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2019/03/13 17:02:34.965810 [INFO ] rollback: starting rollback manager
2019/03/13 17:02:34.976516 [INFO ] expiration: restoring leases
2019/03/13 17:02:34.985921 [INFO ] expire: leases restored: restored_lease_count=1
2019/03/13 17:02:34.991747 [INFO ] core: post-unseal setup complete
2019/03/13 17:02:34.991896 [INFO ] core/startClusterListener: starting listener: listener_address=0.0.0.0:8201
2019/03/13 17:02:34.992157 [INFO ] core/startClusterListener: serving cluster requests: cluster_listen_address=[::]:8201
2019/03/13 17:02:37 http: TLS handshake error from ****.***.***.**:36340: EOF

Is it normal for vault to get sealed many times (I am talking on a hourly basis here) on a everyday basis and is it expected behaviour to go to stand by mode each and everytime when a unseal process takes place.

**Comment by ncabatoff** [comment]
It is not normal.  It sounds like your storage backend is behaving badly.

**Comment by jefferai** [comment]
Hi there,

Your logs above don't indicate that vault is being sealed, just that a node went to standby and then active again. A 429 code isn't a problem unless all nodes are showing it with no actual active node.

If the 429 is the only problem it sounds like leadership transitions are taking place, so you may want to look into why that's happening. If vault is actually sealing and requires unseal keys to be provided that's another issue but the logs above don't contain any clues.

**Comment by infa-svijayak** [comment]
Hi Jefferai,
The problem here is we actually run vault in a single node and use consul as its backend. For now we have a service which feeds the vault with unseal keys if its sealed. And by that 429 error code means we will be having a problem right since it is a single node server. We are planning for a upgrade but any advice on this will be appreciated.

**Comment by calvn** [comment]
You might bump into `core: leadership lost, stopping active operation` (and through the teardown and post-unseal process) even if you're running a single node cluster if the Vault node loses connectivity with Consul. There is potentially intermittent connectivity issues which is triggering this.

**Comment by infa-svijayak** [comment]
@calvn Any suggestions on how do I monitor that.

**Comment by calvn** [comment]
I'd first suggest looking at the consul logs to see if there's any indication of the process/service acting flaky. If that's not the case, then it might be an actual network connection issue (more likely if they are running on separate instances) so I'd suggest looking into setting up monitoring against your network/connection.

**Comment by michelvocks** [comment]
I will close this issue for now due to inactivity. @infa-svijayak Feel free to open a new issue if this problem still occurs for you.
