### ISSUE TITLE
[UI]: LDAP config check boxes missing

### ISSUE THREAD

**Issue by tristanmorgan** [hashicorp/vault#6513]
**Describe the bug**
The check boxes on the LDAP configuration page are missing.

**To Reproduce**
1. Run `vault server --dev`
2. login via a browser with the *cough* root token
3. enable LDAP auth method and click "enable method"
4. click the "LDAP Options"
5. the check boxes are missing

**Expected behavior**
The check boxes should be shown.

**Environment:**
tested with Vault 1.1.0 (oss and Premium) on Linux and Darwin
Tested with Safari, Firefox and Chrome on MacOS and Windows (except Safari)

Vault server configuration file(s):
(N/A dev mode too)

**Additional context**
![ldap broken](https://user-images.githubusercontent.com/6336384/55365524-91895b00-5530-11e9-8c41-ab4d89607e2e.png)

**Comment by meirish** [comment]
Hi! thanks for reporting this - this was fixed by https://github.com/hashicorp/vault/pull/6474 and will be released soon in 1.1.1

**Comment by tristanmorgan** [comment]
thanks.
