### ISSUE TITLE
Error Authenticating of multiple kubernetes clusters with one vault cluster.

### ISSUE THREAD

**Issue by tsahoo** [hashicorp/vault#6514]
Hi,
Greetings..
As per the vault documentation https://www.vaultproject.io/docs/auth/kubernetes.html#configuration   I am able to authenticate  vault cluster to one kubernetes cluster. (And it enables with default path "auth/kubernetes")

But whenever I am trying to authenticate with multiple kubernetes cluster with different path.

I enabled kubernetes with a different path (qa/k8s) for another kubernetes cluster.  

vault auth enable -path=/qa/k8s kubernetes

Its throwing below error while doing the vault write :

Error writing data to qa/k8s/config: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/qa/k8s/config
Code: 404. Errors:

* no handler for route 'qa/k8s/config'

Here one small query,How can we authenticate multiple kubernetes cluster with one vault cluster? If it is possible how can we achieve this?

**Comment by ncabatoff** [comment]
Hi @tsahoo,

I think you've got the right idea, but you're missing the leading 'auth' in your write path.  Try instead

```
vault write auth/qa/k8s/config ...
```

**Comment by tsahoo** [comment]
Thanks @ncabatoff .It worked for me.
