### ISSUE TITLE
Vault PKI doesn't seem to like common_names with commas

### ISSUE THREAD

**Issue by seafoodbuffet** [hashicorp/vault#6534]
**Describe the bug**
We're using vault to generate client authentication certificates where clients are identified by a Distinguished Name-style common name (e.g. CN=foo,ou=bar,dc=com). Vault seems to reject such names even when allow_any_name is set to true. Is this intended? If so, is there a best-practice for CN's in client certs? Just use domain-names?

**To Reproduce**
Setup a Vault PKI role for client authentication:
`vault write my-int-ca/roles/client allow_server=false allow_client=true allow_any_name=true allow_bare_domains=true max_ttl=1440h`

Issue a barename cert works fine
`vault write my-int-ca/issue/client common_name=foo`

Issuing a cert with a comma in the name fails
`vault write my-int-ca/issue/client common_name=foo,`

The error message is
```
Error writing data to my-int-ca/issue/client: Error making API request.

URL: PUT http://localhost:8200/v1/my-int-ca/issue/client
Code: 400. Errors:

* common name foo, not allowed by this role
```

This also fails if you provide a valid DN (e.g. `CN=foo,dc=example,dc=com`)

**Expected behavior**
We get a certificate with `TLS Web Client Authentication` extended usage with a CN value of `CN=foo,`

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.3
* Vault CLI Version (retrieve with `vault version`): 1.0.3
* Server Operating System/Architecture: Docker on Linux

**Comment by michelvocks** [comment]
Hi there,

Vault validates automatically the CNs, DNS SANs, and the host part of email addresses by default.
You can turn off this behavior with the `enforce_hostnames` parameter: https://www.vaultproject.io/api/secret/pki/index.html#enforce_hostnames

```
vault write my-int-ca/roles/client allow_server=false enforce_hostnames=false allow_client=true allow_any_name=true allow_bare_domains=true max_ttl=1440h
```

Closing this now since it does not look like a bug. Please feel free to reopen this issue if you have any further questions.

Cheers,
Michel
