### ISSUE TITLE
UI Returns Error when trying to generate SSH OTP

### ISSUE THREAD

**Issue by jrdemasi** [hashicorp/vault#6539]
When installing Vault and running the dev server (I have seen this same behavior in prod, but wanted to know if it was the same with the dev server to reproduce easily for filing a bug report) generating OTP for SSH produces an error in the UI.  To reproduce this with vault-1.1.0:

1. Start the vault dev server
2. Enable the SSH secrets engine at ssh/
3. Create a new role with any default name/username and for cidr list 0.0.0.0/0
4. Attempt to generate credentials using this new role in the Web UI, you will see an error: "n.factoryFor is not a function"

The functionality works completely fine and returns a valid key if using the API or vault commands.  Happy to provide anymore info that may be useful.

**Comment by jrdemasi** [comment]
Thank you :-)

**Comment by meirish** [comment]
No problem! Thank you for reporting it!
