### ISSUE TITLE
Audit log suddenly stopped

### ISSUE THREAD

**Issue by meklon** [hashicorp/vault#6552]
### Bug description
We've deployed several Vault servers with a Consul cluster as a backend. I've activated audit to file:
`vault audit enable file file_path=/var/log/vault_audit.log`

Everything was good, the log updated as expected. But, after several server reboots, we've noticed that the vault_audit.log was not updating anymore.
### Fix attempts and additional information
1. I've tried to disable/enable audit again, write it to another file path.
2. I checked the free HDD space - it is ok.  
3. Checked that current node is a master:
```
[root@********** log]# curl http://127.0.0.1:8200/v1/sys/leader
{"ha_enabled":true,"is_self":true,"leader_address":"http://10.***.***.***:8200","leader_cluster_address":"https://10.***.***.***:8201","performance_standby":false,"performance_standby_last_remote_wal":0}
```
4. Audit status:
```
[root@********* ~]# /data/vault/vault audit list --detailed
Path     Type    Description    Replication    Options
----     ----    -----------    -----------    -------
file/    file    n/a            replicated     file_path=/var/log/vault_audit.log

```
### Expected behavior
Audit should work as expected.

### Environment:
* Vault Server Version (retrieve with `vault status`):
```
[root@************ ~]# /data/vault/vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    3
Threshold       2
Version         1.0.2
Cluster Name    vault-cluster-10fa2090
Cluster ID      daaf4ec2-8994-e00c-8dcd-877e9b69138e
HA Enabled      true
HA Cluster      https://10.***.***.***:8201
HA Mode         active
```
* Vault CLI Version (retrieve with `vault version`):
Vault v1.0.2 ('37a1dc9c477c1c68c022d2084550f25bf20cac33')

* Server Operating System/Architecture:
RHEL 7

Vault server configuration file(s):

```hcl
  storage "consul" {
      address = "127.0.0.1:8500"
      path = "test-vault/"
#      "advertise_addr": "https://***************:8200"
      consistency_mode = "default"
      service = "test-vault"
      service-tags = "vault"
    }

#  storage "file" {
#    path = "/data/vault/data"
#  }

  listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = "true"
  }


  api_addr = "http://10.***.***.211:8200"
  cluster_addr = "https://10.***.***.211:8201"
  disable_mlock = "true"
  ui = "true"
  log_level =  "debug"
```

**Comment by sivanag1974** [comment]
This is happening to me too. Suddenly audit-logging stopped working for me. Any updated/pointers to trouble-shoot this?

**Comment by meklon** [comment]
> 
> 
> This is happening to me too. Suddenly audit-logging stopped working for me. Any updated/pointers to troubleshoot this? My vault configuration is very much similar to the above one.

I've realized, that only the current master-node is writing the log. So, everything was OK. The reason of the problem was in leadership change.
