### ISSUE TITLE
Vault UI 1.1.0 does not surface permission errors on KV backend

### ISSUE THREAD

**Issue by nickwales** [hashicorp/vault#6554]
When attempting to write secrets to a location that is not permitted by my policies I get no error message. 

Via the CLI I get a very obvious error:

```
Error writing data to secret/data/multipaas/test/app1: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/secret/data/multipaas/test/app1
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

However when attempting to store keys via the UI the save button is available but there is no response when it is clicked making this a confusing experience.

**Comment by hsimon-hashicorp** [comment]
Due to the length of time that this has been open, I'm going to go ahead and close this issue. Please try again on Vault 1.11 and let me know if it still occurs. Thanks!
