### ISSUE TITLE
Vault should not create duplicate SAN entries

### ISSUE THREAD

**Issue by gnugnug** [hashicorp/vault#6571]
We use Vault so sign CSRs and issue certificates and have a small feature request:

Problem description: Assume the following PKI role to sign server certificates:
`vault write pki/roles/example allowed_domains=example.com allow_subdomains=true client_flag=false`

A typical CSR which for example should cover two domains looks like this:

> Certificate Request:
>     Data:
>         Version: 0 (0x0)
>         Subject: O=Foobar, CN=one.example.com
>         Subject Public Key Info:
>             Public Key Algorithm: rsaEncryption
>                 Public-Key: (2048 bit)
>                 Modulus:
>                     00:[...]
>                 Exponent: 65537 (0x10001)
>         Attributes:
>         Requested Extensions:
>             X509v3 Subject Alternative Name:
>                 DNS:one.example.com, DNS:two.example.com
>     Signature Algorithm: sha256WithRSAEncryption

When this CSR is submitted to Vault via "vault write pki/sign/example csr=@...csr" we receive the following certificate back:

> Certificate:
>     Data:
>         Version: 3 (0x2)
>         Serial Number:
>             1f:e2:09:f2:81:e1:b9:46:e1:9d:30:b7:fb:46:07:5d:2c:02:bb:eb
>     Signature Algorithm: sha256WithRSAEncryption
>         Issuer: CN=My Root CA
>         Validity
>             Not Before: Apr 11 16:35:36 2019 GMT
>             Not After : Apr 11 16:44:06 2019 GMT
>         Subject: CN=one.example.com
>         Subject Public Key Info:
>             Public Key Algorithm: rsaEncryption
>                 Public-Key: (2048 bit)
>                 Modulus:
>                     00:[...]
>                 Exponent: 65537 (0x10001)
>         X509v3 extensions:
>             X509v3 Key Usage: critical
>                 Digital Signature, Key Encipherment, Key Agreement
>             X509v3 Extended Key Usage:
>                 TLS Web Server Authentication
>             X509v3 Subject Key Identifier:
>                 EC:E5:E7:61:26:4C:A5:E3:E7:DF:83:37:BB:E0:4F:3A:3F:E9:5A:D7
>             X509v3 Authority Key Identifier:
>                 keyid:18:5B:DB:70:29:43:75:E2:D8:80:8D:3A:CC:C0:62:CD:EF:37:5F:F4
>             X509v3 Subject Alternative Name:
>                 **DNS:one.example.com, DNS:two.example.com, DNS:one.example.com**
>     Signature Algorithm: sha256WithRSAEncryption

The certificate now contains "DNS:one.example.com" two times in the SAN extension. This is not a huge problem, but makes the certificate unnecessarily larger and the domain name list harder to read.

I know that the client could avoid this by specifying "exclude_cn_from_sans=true" in his request, but most clients are lazy and unconditonally setting exclude_cn_from_sans=true for every request leads again to other problems for CSRs which cover only one domain name and do not include a SAN extension at all.

 

Since I'm not aware of any use case of duplicated SAN entries, I suggest that before copying the CN into the SAN extension, Vault should check if the exact same entry already exists. If yes, the CN will not be copied.

**Comment by wgoulet** [comment]
+1 to this issue; we are using Vault in production as a backend for certificate issuance with our application and have observed the same behavior. It is problematic as it increases certificate size (by an admittedly small number) and could potentially confuse relying party software.

**Comment by tr1ck3r** [comment]
I also agree, it is not desirable for the CA to issue certificates having duplicate SANs.  Automatically adding the CN as a DNS SAN is a good feature because it ensures the certificate valid for current day usage, but it shouldn't do it blindly... it should be checking to see if the value of the CN is already present in the array of DNS SANs, and only add when it is not.  

With the current implementation you're penalizing people for generating proper CSRs and effectively encouraging them to adopt a poor practice to workaround it.
