### ISSUE TITLE
Support num_uses in auth/token/roles/role

### ISSUE THREAD

**Issue by jberkenbilt** [hashicorp/vault#6582]
**Is your feature request related to a problem? Please describe.**
We make heavy use of roles in the token auth backend. When specifying a role with auth/token/roles/role, it is possible to constrain the tokens created by auth/token/create/role with `explicit_max_ttl` but not with `num_uses`. It would be great if you could create a token auth role that enforces generation of tokens with no more than a specified `num_uses`.

**Describe the solution you'd like**
Support a `max_num_uses` parameter to auth/token/roles/role_name

**Describe alternatives you've considered**
This seems like an obvious solution. I have not considered other solutions. We can use the `num_uses` parameter when creating a token, but without the constraint, we can also not use it. There may be some reason to call it other than `max_num_uses`, but that also seems like the obvious choice. One could imagine a `default_num_uses` parameter as well, or perhaps a `num_uses` parameter for the default and a `max_num_uses` for the maximum.

**Explain any additional use-cases**
We like to alert on an attempt to use a token after is maximum uses. Since our standard flow is requesting a token for a token auth backend role and injecting that token into something, being able to enforce `max_num_uses` would make it easier for us to detect an intentional or unintentional misuse of a token that was intended to be used only one time.

**Additional context**
No additional context. I found the relevant code in `vault/token_store.go` and may attempt a pull request.

**Comment by tyrannosaurus-becks** [comment]
Looks like this has been recently added as part of the token helper. I was going to take this on but found the code [here](https://github.com/hashicorp/vault/blob/master/vault/token_store.go#L415).

**Comment by jberkenbilt** [comment]
I don't think this is what we're looking for. I'm looking for something server side that will limit the number of uses on any token created using auth/token/create/role. This looks like something a specific user can do to manage their own tokens.

**Comment by jberkenbilt** [comment]
@tyrannosaurus-becks Can this be reopened? I don't seem to be able to reopen it.

**Comment by tyrannosaurus-becks** [comment]
@jberkenbilt ah, I see! I thought that code was for the roles but I see it's not. I tested this and it didn't work:
```
vault write /auth/token/roles/test-role \
    num_uses=1
```
And of course I received this when reading it back:
```
$ vault read /auth/token/roles/test-role
Key                       Value
---                       -----
allowed_entity_aliases    <nil>
allowed_policies          []
disallowed_policies       []
explicit_max_ttl          0s
name                      test-role
orphan                    false
path_suffix               n/a
period                    0s
renewable                 true
token_explicit_max_ttl    0s
token_period              0s
token_type                default-service
```
I will actually take this on and link the PR when it's ready.

**Comment by tyrannosaurus-becks** [comment]
@jberkenbilt actually, it looks like this _is_ currently possible. My syntax was slightly off. It was just added, though, possibly even after your request. I will add docs.

Here's how it can be done:
```
$ vault write /auth/token/roles/test-role token_num_uses=1
Success! Data written to: auth/token/roles/test-role

$ vault read /auth/token/roles/test-role
Key                       Value
---                       -----
allowed_entity_aliases    <nil>
allowed_policies          []
disallowed_policies       []
explicit_max_ttl          0s
name                      test-role
orphan                    false
path_suffix               n/a
period                    0s
renewable                 true
token_explicit_max_ttl    0s
token_num_uses            1
token_period              0s
token_type                default-service

$ vault write /auth/token/create/test-role policies=root
Key                  Value
---                  -----
token                s.WdSWn6d80jzbme5j6QoXEioR
token_accessor       RaKhG5gI4ME4Z5Vm8krf7sNF
token_duration       ∞
token_renewable      false
token_policies       ["root"]
identity_policies    []
policies             ["root"]
```
Then when I switch over to a separate terminal pointing at the same ephemeral test instance of Vault:
```
$ export VAULT_TOKEN='s.WdSWn6d80jzbme5j6QoXEioR'
$ vault read /sys/auth
Key       Value
---       -----
token/    map[accessor:auth_token_1d92ae99 config:map[default_lease_ttl:0 force_no_cache:false max_lease_ttl:0 token_type:default-service] description:token based credentials local:false options:<nil> seal_wrap:false type:token uuid:de87fd9c-0c66-2324-2b22-37d524f9d843]

$ vault read /sys/auth
Error reading sys/auth: Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/auth
Code: 403. Errors:

* permission denied
```
So it did indeed enforce the limit of using the token only once.

Does that fully solve the request? Other than us needing to add docs, of course.

**Comment by jefferai** [comment]
Yep, it's token_num_uses.

**Comment by jberkenbilt** [comment]
@tyrannosaurus-becks @jefferai Great, thanks! And thanks for the doc update. :-)
