### ISSUE TITLE
Hashicorp vault vs. Passbolt

### ISSUE THREAD

**Issue by afranke** [hashicorp/vault#6589]
The [vs section of the docs](https://www.vaultproject.io/docs/vs/) could benefit from the addition of a comparison against [Passbolt](https://www.passbolt.com/).

**Comment by raoofm** [comment]
also a comparison with aws secrets manager

**Comment by julioc98** [comment]
https://github.com/hashicorp/vault/issues/6589#issuecomment-483703352
@raoofm 
See:https://www.vaultproject.io/docs/vs/kms.html

**Comment by jefferai** [comment]
We have decided to remove that section, see https://github.com/hashicorp/vault/pull/8538
