### ISSUE TITLE
POST /transit/verify hash_algorithm documented, but algorithm expected by server v1.1.1

### ISSUE THREAD

**Issue by kkleidal** [hashicorp/vault#6599]
I think I may have found an inconsistency between the server implementation (v1.1.1) and the documentation. The documentation [here](https://www.vaultproject.io/api/secret/transit/index.html#hash_algorithm-1) says that there is a parameter, `hash_algorithm`, for `POST /transit/verify` but from what I can tell, the server expects the algorithm to be specified in the `algorithm` key, similar to `POST /transit/hmac`.

**Comment by michelvocks** [comment]
Hi @kkleidal,

for backwards compatibility, we currently support three ways to define the algorithm.
The first possible way is via the URL (at the end of the path), the second is via `hash_algorithm` and the third is via `algorithm`.

Cheers,
Michel
