### ISSUE TITLE
s3 physical backend configuration

### ISSUE THREAD

**Issue by carldanley** [hashicorp/vault#660]
Hello, I tried looking through existing issues/documentation, etc to find a configuration example for the physical s3 backend. Can someone provide an example of how they've hooked up their s3 backend?

If I understand this correctly, vault will use s3 for storing secrets instead of your local filesystem right?

**Comment by carldanley** [comment]
cc: @tkellen, @mattsurabian

**Comment by jefferai** [comment]
You should pose this question on the mailing list, not here. You'll get far more eyes on it, including people that are actually using the S3 backend.
