### ISSUE TITLE
Migrate PKI storage to another instance

### ISSUE THREAD

**Issue by CiraciNicolo** [hashicorp/vault#6608]
There is a way to migrate PKI data from a Vault instance to another? How this should be done?

**Comment by briankassouf** [comment]
Hi, if you want to move all keys, including the unseal keys, to the new instance you can use the migrate command. Otherwise you could try using the [sys/raw](https://www.vaultproject.io/api/system/raw.html) API to read out the raw bytes on the first node and write them in on the second.

**Comment by CiraciNicolo** [comment]
I'm using consul as the storage backend, is it possibile to export the kv storage via consul and import the result on another node? Or vault store some data somewhere else?
