### ISSUE TITLE
Be more inteligent when checking whitelisted EC2 instances IDs 

### ISSUE THREAD

**Issue by alexandernst** [hashicorp/vault#6619]
**Is your feature request related to a problem? Please describe.**
As per what I have discovered in #6617 , the tidy process kicks once every hour, which means that if I have a safety buffer of 10s and my tokens TTL is 10s, there could be a time gap of 59min 40s  during which a request from my instance for a new token could be denied.

The problem is that Vault will just check if the ID is already whitelisted.

**Describe the solution you'd like**
A better strategy, when a request for a new token is received, would be to check if the ID is whitelisted and if that ID should have been removed by the tidy process. 

**Describe alternatives you've considered**
A simple alternative would be implementing #6617 and letting the Vault operator to run that command in a cron as often as he/she wants.

**Explain any additional use-cases**
The only use case here is being able to remove EC2 instance IDs quicker, so those machines can request new tokens.

**Additional context**
This bug is a derivate from #6617 and https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/xlukrGX0buE/svQMtQwqBQAJ

**Comment by jefferai** [comment]
Closing in favor of #6617

**Comment by alexandernst** [comment]
@jefferai Note that #6617 is about a different thing. Both issues are related, but not the same.

**Comment by alexandernst** [comment]
@jefferai Ping. Can you please reopen this? (as discussed in #6617)
