### ISSUE TITLE
permission denied during auth when using the secret policy from "Getting Started"

### ISSUE THREAD

**Issue by sramakr** [hashicorp/vault#662]
Followed the instructions for creating authorization policy.
Always fails with Permission denied on API call lookup_self

But works if I use the root policy.

path "secret/*" {
  policy = "write"
}
path "secret/foo" {
  policy = "read"
}
path "secret/super-secret" {
  policy = "deny"
}

vault token-create -policy="secret"
vault auth token-from-above
permission denied
curl -XGET http://127.0.0.1:8200/v1/auth/token/lookup-self --header "X-Vault-Token: 9dbc73fb-67e2-ef52-5975-6874e457cf9e"
{"errors":["permission denied"]}

Not familiar with go , with looks like it's failing somewhere on handleLookup in token_store.go. 

Appreciate any help.

**Comment by sramakr** [comment]
BTW. Tried using both Consul and MySQL Backend , it's the same issue.

vault -version
Vault v0.3.0

**Comment by jefferai** [comment]
It's a docs bug, someone is going to submit a PR for it. See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/1celGgCDfrU/QIpLFMDRBgAJ
