### ISSUE TITLE
api documentation for userpass read user inaccurate

### ISSUE THREAD

**Issue by jmls** [hashicorp/vault#6632]
The documentation for the userpass read method (https://www.vaultproject.io/api/auth/userpass/index.html) does not match the actual output from the api.

**To Reproduce**
the api states that the typical response from this api is 

```
{
  "request_id": "812229d7-a82e-0b20-c35b-81ce8c1b9fa6",
  "lease_id": "",
  "lease_duration": 0,
  "renewable": false,
  "data": {
    "max_ttl": 0,
    "policies": "default,dev",
    "ttl": 0
  },
  "warnings": null
}
```
whereas the actual output is

```
{
    "request_id": "fc75e289-d6fa-ec6c-b8b0-56b8d4a6ddb2",
    "lease_id": "",
    "renewable": false,
    "lease_duration": 0,
    "data": {
        "bound_cidrs": [],
        "max_ttl": 0,
        "policies": ["admin"],
        "ttl": 0
    },
    "wrap_info": null,
    "warnings": null,
    "auth": null
}

```

The actual difference is in the "policies" key. In the documentation it is specfied as a comma separated string, the actual output is an array

**Expected behavior**
the api documentation to match the api ouput

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.1.1
* Vault CLI Version (retrieve with `vault version`): Vault v1.1.1 ('a3dcd63451cf6da1d04928b601bbe9748d53842e')

**Comment by jmls** [comment]
actually, there seems to be several areas where the documentation does not match - I want to check that I'm not missing something obvious ;)

For example, under "_List Mounted Secrets Engines_" we have this documentation :

```
{
  "aws": {
    "type": "aws",
    "description": "AWS keys",
    "config": {
      "default_lease_ttl": 0,
      "max_lease_ttl": 0,
      "force_no_cache": false,
      "seal_wrap": false
    }
  },
  "sys": {
    "type": "system",
    "description": "system endpoint",
    "config": {
      "default_lease_ttl": 0,
      "max_lease_ttl": 0,
      "force_no_cache": false,
      "seal_wrap": false
    }
  }
}```

whereas the actual response is

```
{
    "sys/": {
        "accessor": "system_233c21f3",
        "config": {
            "default_lease_ttl": 0,
            "force_no_cache": false,
            "max_lease_ttl": 0,
            "passthrough_request_headers": ["Accept"]
        },
        "description": "system endpoints used for control, policy and debugging",
        "local": false,
        "options": null,
        "seal_wrap": false,
        "type": "system"
    },
    "aws/": {
        "accessor": "aws_e62e314c",
        "config": {
            "default_lease_ttl": 0,
            "force_no_cache": false,
            "max_lease_ttl": 0
        },
        "description": "",
        "local": false,
        "options": null,
        "seal_wrap": false,
        "type": "aws"
    },
    "request_id": "e6756ec7-81d4-5112-a650-53ac2807af5a",
    "lease_id": "",
    "renewable": false,
    "lease_duration": 0,
    "data": {
        "aws/": {
            "accessor": "aws_e62e314c",
            "config": {
                "default_lease_ttl": 0,
                "force_no_cache": false,
                "max_lease_ttl": 0
            },
            "description": "",
            "local": false,
            "options": null,
            "seal_wrap": false,
            "type": "aws"
        },
        "sys/": {
            "accessor": "system_233c21f3",
            "config": {
                "default_lease_ttl": 0,
                "force_no_cache": false,
                "max_lease_ttl": 0,
                "passthrough_request_headers": ["Accept"]
            },
            "description": "system endpoints used for control, policy and debugging",
            "local": false,
            "options": null,
            "seal_wrap": false,
            "type": "system"
        }
    },
    "wrap_info": null,
    "warnings": null,
    "auth": null
}
```
specifically, the endpoint keys are "aws/" not "aws" , there are extra properties (like wrap_info) and a huge property "data" which seems to be a duplicate of all the mount keys

I have come across several examples of the extra "data" property and am curious to know the purpose of this

thanks

**Comment by evitalis** [comment]
@jmls I am also seeing the documentation for listing group names is also invalid and results in path errors from the API. As soon as I get some example output I am going to open an issue on that as well.

**Comment by jefferai** [comment]
Even better, open a PR :-).

**Comment by evitalis** [comment]
@jefferai Sure we can do a PR but it would also be helpful for Hashicorp to validate the other documentation as there are other noted gaps and/or missing information for some topics, see #6762 for one more example.

**Comment by mpetka** [comment]
Were the PRs ever created?

**Comment by kalafut** [comment]
The first couple of examples were just updated in https://github.com/hashicorp/vault/pull/6963. The  "data" property is the primary response data location, but we sometime re-add items to the top level for backwards compatibility reasons.

**Comment by kalafut** [comment]
Closing this issue since the specific examples have been fixed.
