### ISSUE TITLE
Faulty release of `github.com/hashicorp/vault@v1.1.2`

### ISSUE THREAD

**Issue by syndbg** [hashicorp/vault#6634]
**Describe the bug**

As a consumer (using `go.mod`), currently it's not possible for go mod to resolve dependencies when someone is using both:

* github.com/hashicorp/vault@v1.1.2
* github.com/hashicorp/vault/api@v1.0.1

The reason why is that for some reason `/github.com/hashicorp/vault@v.1.12` does not contain the `api/go.{mod,sum}` files and golang does not properly treat it as a go module.

In long, it's explained at https://medium.com/@syndbg/resolving-dependencies-as-consumer-of-golang-dependencies-and-mono-repos-a-practical-look-at-7461a1fc2778?source=friends_link&sk=2ac2ebbff0173d7999a240186d8e1fde

**Additional context**

The solution is to create a new git tag and github release from https://github.com/hashicorp/vault/commit/6ec1bcfb20c2efcd9769cfb2816943bcec135010 .

It's the closest (in terms of least code changes/side effects) compared to the original faulty release at https://github.com/hashicorp/vault/releases/tag/v1.1.2

Imo, both:

* `v1.1.3`
* `api/v1.1.3`

must be created to keep symmetry of what is released.

**Unfortunately `github.com/hashicorp/consul` and `github.com/hashicorp/consul/api` are also having the same issue**

**For anyone stumbling on this issue:**

Adding to your `go.mod` the following solves the problem, but it's very hacky:

```
replace github.com/hashicorp/vault/api => github.com/syndbg/vault/api v0.0.0-20190418224949-6ec1bcfb20c2

replace github.com/hashicorp/vault => github.com/syndbg/vault v0.0.0-20190418224949-6ec1bcfb20c2

replace github.com/hashicorp/consul/api => github.com/hashicorp/consul/api v1.0.1

replace github.com/hashicorp/consul/sdk => github.com/hashicorp/consul/sdk v0.1.0

replace github.com/hashicorp/consul => github.com/hashicorp/consul v1.4.5-0.20190327125456-4243c3ae42cf
```

**Who to mention?**

Sorry if this is not the right person, but @jefferai you might be interested in this.

**Comment by jefferai** [comment]
This is not a bug; 1.1.2 was a minor patch on 1.1.1 which was before the go mod conversion.

Eventually this will fix itself, but in the mean time you can track down the dependencies pulling in the full Vault repo. Everything needed by any plugins and clients that we know of are in `api/` or `sdk/` and as such shouldn't need the full Vault repo any longer.

**Comment by eliben** [comment]
@jefferai do you have an ETA on when this will fix itself? It affects us in https://github.com/google/go-cloud/

**Comment by malkhamis** [comment]
@syndbg I tried the hack you suggested and that led to dependency issues with k8s.. Anyway, seems like I can get around it with:
```
$ rm -rf /.../go/pkg/mod/github.com/hashicorp/vault@v0.10.0/api
```
but not sure if this is a good solution at all 🤔

**Comment by jefferai** [comment]
@eliben There's no fix because nothing is broken. We were not using go modules at the time, so you trying to mix and match go module API tags with non-go-module repo tags will not work. You need to either migrate your code to use newer Vault paths or revert to older API before go modules.
