### ISSUE TITLE
Vault leader thrashing when backed by DynamoDB

### ISSUE THREAD

**Issue by EdwinRobbins** [hashicorp/vault#6636]
**Describe the bug**
When running Vault in HA with 3 nodes using DynamoDB as the leader election store, it is possible to enter a state where leadership will continuously rotate across all three Vault nodes. This behavior continues until manual action is taken to disrupt the loop.

Rotation is consistently ordered across the nodes A → C → B → A → C…

**To Reproduce**
1. Go to the AWS DynamoDB console and delete the leadership entry
2. Keep refreshing to see that they key is being deleted and recreated by different vaults
3. Tail logs from the Vault instances to observe the leadership exchange 

**Expected behavior**
Graceful step down from old leader to a stable new one. 

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.11.4
* Vault CLI Version (retrieve with `vault version`): Vault v0.11.4 ('612120e76de651ef669c9af5e77b27a749b0dba3')
* Server Operating System/Architecture:Ubuntu 18.04.2 LTS x86_64

**Additional context**
Immediately preceding this incident we observed 2 update failures in the AWS CloudWatch logs  
![DynamoDB_errors](https://user-images.githubusercontent.com/47191885/56696752-9d84ba80-66a1-11e9-923b-56f62ae59870.png)

Leader churn then begins. Hosts cycle continuously from B → A → C  and then back around. Maximal time in this condition for a new leader assert was 17s but could be be almost instantaneous. Manual action was taken at 2019-04-15 01:24 to kill an existing Vault host after which a single leader held for 10 minutes until the the new host replacement came up and took leadership and caused loop to reoccur. Manual action was taken again at 2019-04-15 01:52 after which long term stable leader was elected.

![Churn_Redacted](https://user-images.githubusercontent.com/47191885/56696907-171ca880-66a2-11e9-86c1-5ebc059977e6.png)

Looking at the conditional failures rate on the DynamoDB table shows that steady state has 120 conditional check failures per minute. During the unstable operation this drops to 60. These failures are expected as this conditional check is present in the DynamoDB update logic and prevents a Vault from updating the leader key in DynamoDB if there is a valid lock held by another Vault instance.

Values that are material to reading the following graph for using DynamoDB and how the incident relates:

* Standby Vaults will attempt to take leadership key every 1s
* Vault leaders will update/refresh the leadership lock every 5s
* The leadership key TTL is set at 15s

![ConditionalErrors](https://user-images.githubusercontent.com/47191885/56696993-59de8080-66a2-11e9-8db6-21dc4c8c5ea6.png)

With HA running three nodes, with  one active leader, and two standby the 120/min failed conditional checks reflect that every second both standbys are trying to update the lock to take ownership but failing because the current lock TTL is still valid. 

During leader churn the drop to 60/min failed conditional checks reflect that normal operation is not occurring and instead of two standby nodes there is only one and this is a result of the other Vault standby taking ownership instead.

We can see that this is not because the conditional check is passing when it shouldn't but rather because a new key is being written instead. During the incident we can see that DyanmoDB shows instead of purely update operations there are write events indicating that the churn is linked to the leader lock entries being created; Vault using DynamoDB does its deletes also as a batch write operation so they cannot be distinguished in these metrics.

![DynamoDB_ops](https://user-images.githubusercontent.com/47191885/56697089-a88c1a80-66a2-11e9-9a10-86f2dbfe6501.png)

We can see from our DataDog vault.dyanamodb.delete.count metrics that the Vault nodes are doing delete operations. If lock entries are being deleted this would allow the creation of new leadership locks.

![Delete_Redacted](https://user-images.githubusercontent.com/47191885/56697190-d40f0500-66a2-11e9-8bb3-e57e49d28d90.png)

Moreover we observe that the delete events time align with loss of leadership.
![LeadershipLost_Redacted](https://user-images.githubusercontent.com/47191885/56697248-f739b480-66a2-11e9-888d-8d3f21495658.png)

**Comment by EdwinRobbins** [comment]
Based on my investigation the root cause is:
The chain of events that lead to the Vault leadership thrashing observed:

* Two updates to the DynamoDB table failed causing original Vault instance (B) to have its key TTL expire
    * The leader will refresh every 5s; with a leader lock key TTL of 15s, two successive failure presents a long enough window for the key to expire due to this
* A next leader (A) sees the key has expired and updates the key value such that it is the leader now
* The original leader (B) goroutine sees the leadership entry has changed under it and signals with the leaderLossCh (https://github.com/hashicorp/vault/blob/master/vault/ha.go#L536) that it should halt acting as leader.
    *  As part of this it clears its HA lock, but because the new leader stepped up and took possession of the key the entry no longer belongs to this Vault but it deletes it anyway as the dynamodb.go delete call for Unlock does not validate they key being deleted matches what it believes it does
* The third node (C) observes that the leadership key now no longer exists and creates it with itself as the leader
* Former new leader (A) steps down and deletes its key, putting us in the looping condition as (B) will now be in position to see this and recreate the key to assume leadership
    * [There's no chance of escape because the leader will no longer recreate the leadership key if it was deleted from under it ](https://github.com/hashicorp/vault/commit/98079d81a1497ac19a3d2d06bd44138327e93a11). So only a new host can create the entry and will force the old leader to step down when it does so.

**Comment by EdwinRobbins** [comment]
Looking at leadership loop in the Vault when using DynamoDB as the leader election store we can observe two causal issues

* Vault will Unlock() on loss of leadership (https://github.com/hashicorp/vault/blob/master/vault/ha.go#L579) and DynamoDB backed Vault Unlock call will delete the key from the DynamoDB table (https://github.com/hashicorp/vault/blob/master/physical/dynamodb/dynamodb.go#L566)
* Deletion does not have an conditional check which prevents unintentional delete of a key with value differing from expected (https://github.com/hashicorp/vault/blob/master/physical/dynamodb/dynamodb.go#L318)

There are a couple changes which can be made, either of which in isolation is sufficient to prevent this condition

* Vault DynamoDB logic should support conditional delete to ensure the deleted path is consistent with what is believed to be deleted
* A leader stepping down should not release an HA lock that it does not have; instances where there is already a new leader for instance

**Comment by EdwinRobbins** [comment]
I've tested a fork of Vault with the additional logging which implements the former and observe that this prevents this issue from occurring; it also confirmed that the old leader was deleting the new leader's lock.

I believe the latter should also be implemented from a correctness standpoint, but cannot say that this is true for all potential leadership backing stores besides DynamoDB

**Comment by kalafut** [comment]
@EdwinRobbins Thanks for the in-depth report. Are you able to share a branch of your test fixes? Needn’t be PR-ready... just for analysis.

**Comment by EdwinRobbins** [comment]
https://github.com/hashicorp/vault/pull/6637

**Comment by kalafut** [comment]
Closed by #6637
