### ISSUE TITLE
Error initializing storage of type postgresql for PostgreSQL 11.2

### ISSUE THREAD

**Issue by schall8** [hashicorp/vault#6638]
**Describe the bug**
Upgrading to latest PosgreSQL version 11.2 we are now receiving the following error trying to start the vault server.

**To Reproduce**
**found prev issue but with diff version, although prev issue is closed as fixed with vault 0.9.4
vault server -config=config.hcl
Error initializing storage of type postgresql: failed to check for native upsert: dial tcp ip_addr:5444: connect: connection refused

**Testing from information on bug#3949
vault=# SELECT string_to_array(setting, '.')::int[]  FROM pg_settings WHERE name = 'server_version';
 string_to_array 
-----------------
 {11,2}
(1 row)

vault=# SELECT string_to_array(setting, '.')::int[] < '{9,5}' FROM pg_settings WHERE name = 'server_version';
 ?column? 
----------
 f
(1 row)

vault=# select '{11,2}' < '{9,5}' FROM pg_settings WHERE name = 'server_version';
 ?column? 
----------
 t
(1 row)

vault=# SELECT ((string_to_array(setting, '.')::int[]) < '{9,5}') FROM pg_settings WHERE name = 'server_version';
 ?column? 
----------
 f
(1 row)

**Expected behavior**
it appears to be a bug with postgres, would be nice to have an option to turn verify off to bypass check

**Environment:**
* Vault Server Version 1.1.1
* Vault CLI Version (retrieve with `vault version`):
Vault v1.1.1 ('a3dcd63451cf6da1d04928b601bbe9748d53842e')
* Server Operating System/Architecture:
RedHat 7.5
Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```contents of our config.hcl
cat config.hcl
listener "tcp" {
        address         = "server.fqdn:8200"
        tls_disable     = "false"
        tls_cert_file   = "/opt/vsm/vault/certs/vault_bundle.crt"
        tls_key_file    = "/opt/vsm/vault/certs/vault-itg.houston.hpecorp.net.key"
        tls_min_version = "tls12"
}

storage "postgresql" {
        connection_url = "postgres://user:password@server.fqdn:5444/vault?sslmode=disable"
        table          = "vault_kv_store"
        max_parallel   = "128"
}

**Additional context**
Add any other context about the problem here.

**Comment by ncabatoff** [comment]
Hi @schall8,

You're getting a connection refused, not a problem evaluating the version.  It sounds like your Vault can't talk to your Postgres.  Can you try logging in to the host running vault and connecting to server.fqdn:5444?

**Comment by schall8** [comment]
issue was a config issue in postgresql.conf file added the vip to listen ip's.  closing issue.

**Comment by lokeish** [comment]
> issue was a config issue in postgresql.conf file added the vip to listen ip's. closing issue.

may i know how and where you added the vip to listen ip's.
