### ISSUE TITLE
Unable to get consul acl token using consul secrets backend in Vault

### ISSUE THREAD

**Issue by ashwinkupatkar** [hashicorp/vault#6646]
Error reading consul/creds/my-role: Error making API request.

URL: GET https://[fqdn]:[port_no]/v1/consul/creds/my-role
Code: 400. Errors:

* Put http://0.0.0.0:[port_no]/v1/acl/create: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

Can someone help here ??

**Comment by ashwinkupatkar** [comment]
I can configure the vault with consul secrets backed.

But on executing the vault read consul/creds/my-role 

I get below errors:

Error reading consul/creds/my-role: Error making API request.

URL: GET https://<FQDN>:<portno>/v1/consul/creds/my-role
Code: 400. Errors:

* Put http://0.0.0.0:<portno>/v1/acl/create: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

**Comment by ncabatoff** [comment]
Hi @ashwinkupatkar ,

It looks like you're trying to speak HTTP to an HTTPS server.  Is it possible that you configured your Consul secret engine with an http:// URL that points to a Consul HTTPS port?

**Comment by ashwinkupatkar** [comment]
Hi,

We are not using https for connecting to consul.   The consul port is http.

So basically m executing the steps like this:

Cosnul secrets backend is already configured. 

1)  Configure vault with consul cluster to generate a token that manages ACL token that will be geenrated. 

>>> curl -k --header "X-Consul-token: [consul-bootstrap-token]" --request PUT --data '{"Name": "sample", "Type": "management"}' http://[hostname-short].`hostname -d`:[consul-http-port]/v1/acl/create

We get a token on executing above command,  say   [consul-configure-token]

2) export vault token value

export VAULT_TOKEN=[Vault-root-token]

3) Configure consul access in vault using above generated token

>>> vault write consul/config/access address=[vault-address-mentioned-in-.hcl-file]:[vault-port] token=[consul-configure-token] 

Success! Data written to: consul/config/access

4) Create a policy

>>> vault write consul/roles/my-role policy=$(base64 <<< 'key "" { policy = "read" }')

Success! Data written to: consul/roles/my-role

5)  Try to read the token 

>>> vault read consul/creds/my-role

Error reading consul/creds/my-role: Error making API request.

URL: GET https://[Vault-fqdn]:[vault-port]/v1/consul/creds/my-role
Code: 400. Errors:

* Put http://[vault-address-mentioned-in-.hcl-file]:[vault-port]/v1/acl/create: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"


What m i missing here ????

**Comment by ncabatoff** [comment]
Sorry, but that malformed HTTP response looks exactly like what happens when speaking HTTP to a server that's configured for HTTPS.  What does 

```
curl -v $(vault read -field=address consul/config/access)/v1/health/node/my-node
```

return?

**Comment by ashwinkupatkar** [comment]
it returns:

* Could not resolve host: [vault-address-mentioned-in-.hcl-file]:[vault-port]; Unknown error
* Closing connection 0
curl: (6) Could not resolve host: [vault-address-mentioned-in-.hcl-file]:[vault-port]; Unknown error

**Comment by ncabatoff** [comment]
Ok, maybe your shell doesn't like $().  Let's do it as two steps instead.

1. ```vault read -field=address consul/config/access```
2. Take the output from (1) and use it in this command: ```curl -v OUTPUT_FROM_1/v1/health/node/my-node```

**Comment by ashwinkupatkar** [comment]
I exactly did the same as you have mentioned above. 

2 step

**Comment by ncabatoff** [comment]
If (1) is returning "could not resolve host", how were any of your other vault commands from your previous comments working?  It sounds like you have a DNS problem at this point, or you're not running the commands in the right environment.

**Comment by ashwinkupatkar** [comment]
executing command 1 returns the address (along with port)that is configured in vault.hcl file

but 2nd step gives me the above error

**Comment by ncabatoff** [comment]
Step 1 should not be returning anything configured in vault.hcl.  It should be returning the address for your Consul server that you configured when you setup the Consul secrets engine using something like

```
vault write consul/config/access \
  address=$CONSUL_HTTP_ADDR \
  token=$CONSUL_MASTER_TOKEN
```

**Comment by ashwinkupatkar** [comment]
Correct I meant say that only.

It returns the address configured in vault.hcl

**Comment by ncabatoff** [comment]
I'm not sure what you mean, but it sounds like your consul secret engine is misconfigured to point to the wrong Consul address.  You can fix it by using a command like the one in my previous comment.

**Comment by ashwinkupatkar** [comment]
I think i got this fixed ... I was providing vault address in the consul/config access.

but now the issue is with 

* Unexpected response code: 401 (ACL support disabled)
