### ISSUE TITLE
Vault logging authentication tokens, and secrets, to stdout/stderr

### ISSUE THREAD

**Issue by wwalker** [hashicorp/vault#665]
We capture stdout/stderr to a log.  I found Client Authentication Tokens (changed here to REDACTED-BUT-REALLY-IN-THE-LOGFILE) and secrets (asdfqwerzxcv in this case) in the capture file:

**Comment by wwalker** [comment]
2015/09/30 14:18:46 [ERR] core: failed to register lease (request: *logical.Request{Operation:"read", Path:"secret/ops/configs/properties/product_groups/foo/my.pass", Data:map[string]interface {}(nil), Storage:logical.Storage(nil), Secret:<nil>, Auth:<nil>, Connection:(*logical.Connection)(0xc209c24300), ClientToken:"REDACTED-BUT-REALLY-IN-THE-LOGFILE", DisplayName:"token-DevOps-Product-Group-ReadOnly", MountPoint:""}, response: &logical.Response{Secret:*logical.Secret{LeaseOptions:logical.LeaseOptions{Lease:30000000000, LeaseGracePeriod:0, Renewable:true, LeaseIncrement:0, LeaseIssue:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, InternalData:map[string]interface {}{"secret_type":"generic"}, LeaseID:""}, Auth:<nil>, Data:map[string]interface {}{"lease":"30s", "value":"asdfqwerzxcv"}, Redirect:""}): failed to persist lease entry: Unexpected response code: 500 (rpc error: write tcp 127.0.0.1:8300: broken pipe)

**Comment by jefferai** [comment]
The ClientToken value is not a real value; it is hashed and used by backends to identify a specific real token for tracking state. It is different per teal token per backend. So its presence in the log isn't nice but isn't a problem.

The secret in the log is, however. That should be removed.

**Comment by wwalker** [comment]
97  2015-10-02 19:15:05 export VAULT_ADDR=https://127.0.0.1:8200                                                                       
   98  2015-10-02 19:15:07 export VAULT_TOKEN=REDACTED-VALUE-BUT-STRAIGHT-OUT-OF-THE-LOG
   99  2015-10-02 19:15:15 vault read secret/ops/configs/properties/product_groups/acme/mysql.pass

That returned me the actual secret.  It is the real authentication token.  I verified that it was being used by rerunning the export command with one letter off the end, and then I get permission denied.

**Comment by jefferai** [comment]
Ah, you're right: this is coming from core before hitting a backend, so it has the real value.
