### ISSUE TITLE
openapi endpoint does not specify x-vault-unauthenticated for getSysSealStatus

### ISSUE THREAD

**Issue by jmls** [hashicorp/vault#6651]
the definition of the `getSysSealStatus` in the openapi endpoint (`/v1/sys/internal/specs/openapi`) is incorrect.

the returned response is
```
        "/sys/seal-status": {
            "description": "Returns the seal status of the Vault.",
            "get": {
                "summary": "Check the seal status of a Vault.",
                "operationId": "getSysSealStatus",
                "tags": ["system"],
                "responses": { "200": { "description": "OK" } }
            }
        },
```
however, the GET on the `/sys/seal-status` does not need a vault-token, and this option is missing from the response

**Expected behavior**

`"x-vault-unauthenticated": true` to be returned as part of the response on this operationId

**Environment:**
* Vault Server Version 1.1.1
* Vault CLI Version (retrieve with `vault version`): Vault v1.1.1 ('a3dcd63451cf6da1d04928b601bbe9748d53842e')
* Server Operating System/Architecture: ubuntu 19.04 64 bit

**Comment by kalafut** [comment]
Good fine and we'll take a look. I think there may be a few of these that we missed when rolling out OpenAPI.
