### ISSUE TITLE
Display secret version creation datetime in UI

### ISSUE THREAD

**Issue by Yajo** [hashicorp/vault#6656]
**Is your feature request related to a problem? Please describe.**
If I rotate secrets regularly for i.e. encrypt a backup, and then later I need to restore an old backup, I need to know the old password for such backup, so I need to know the creation time of each secret to be able to know which one applies.

**Describe the solution you'd like**
When reading secret history via API, I can see the `created_time` field, but I cannot see it through the UI.

**Describe alternatives you've considered**
I store an additional key for each autogenerated secret version that indicates the creation time, to be able to see it in the UI. It's unnecesary though, since that is also stored as metadata by vault automatically.

**Comment by michelvocks** [comment]
Closing this in favor of #6215
