### ISSUE TITLE
acme CA backend support?

### ISSUE THREAD

**Issue by ringods** [hashicorp/vault#668]
I don't know if it fits the Vault case, but would backend support to a certificate authoritiy via the (evolving) acme protocol fit?

https://letsencrypt.org/
https://github.com/letsencrypt/acme-spec

**Comment by jefferai** [comment]
Vault already has a `pki` backend to act as a CA; this will be greatly enhanced in the soon-to-be-released 1.3.1. 

I doubt Vault will ever support the acme protocol. It's a totally different use-case; acme is mostly about a methodology to allow unknown and mostly untrusted parties to prove identity and get certificates. Vault has other authentication and authorization methods, and in return has a far simpler CA API that is also very well-suited to short-lived certificate lifetimes.
