### ISSUE TITLE
Policy definition in the config file?

### ISSUE THREAD

**Issue by BentCoder** [hashicorp/vault#6683]
Hi,

Just trying to find out if we can define a policy in config file or not? I haven't seen anything in the doc unless I missed.

Thanks

Looking for something like below.

```json
{
  "storage": {
    "file": {
      "path": "vault/file"
    }
  },
  "listener": {
    "tcp": {
      "address": "0.0.0.0:8200",
      "tls_disable": true
    }
  },
  "policy": {
    ....
}

```

**Comment by ncabatoff** [comment]
Hi @BentCoder ,

You haven't missed anything, this isn't possible.  There are a variety of projects out there for doing automatic post-unseal provisioning of Vault, along the lines of this blog post: https://www.hashicorp.com/blog/codifying-vault-policies-and-configuration.html
