### ISSUE TITLE
Incorrect examples in documentation of OIDC API

### ISSUE THREAD

**Issue by jleben** [hashicorp/vault#6684]
Documentation for [OIDC Authorization URL Request](https://www.vaultproject.io/api/auth/jwt/index.html#oidc-authorization-url-request) has wrong examples:
- The [sample payload](https://www.vaultproject.io/api/auth/jwt/index.html#sample-payload-2) should have redirect URI fixed to: `https://vault.myco.com:8200/ui/vault/auth/jwt/oidc/callback` (position of `ui` and `vault` should be swapped)
- The [sample request](https://www.vaultproject.io/api/auth/jwt/index.html#sample-request-6) should have endpoint fixed to: `https://127.0.0.1:8200/v1/auth/jwt/oidc/auth_url` (missing `jwt`)
- The [sample response](https://www.vaultproject.io/api/auth/jwt/index.html#sample-response-3) contains a "localhost" redirect URI which does not match the URI shown in the sample payload.

**Comment by kalafut** [comment]
Thanks!

**Comment by jmls** [comment]
don't know if I should raise a new issue, but the actual path specified in the docs (`v1/auth/jwt/oidc/auth_url`) is wrong ...

```
 vault login -method=oidc -output-curl-string  role=reader
```
gives the path of 

```
http://127.0.0.1:8200/v1/auth/oidc/oidc/auth_url
```

ie `oidc/oidc`

**Comment by kalafut** [comment]
@jmls I’ll take a look

**Comment by jleben** [comment]
@jmls The path depends on where the OIDC/JWT plugin is mounted. The top of the documentation page says "This documentation assumes the plugin method is mounted at the `/auth/jwt path` in Vault". You may simply have the plugin mounted at `auth/oidc` instead.

**Comment by jmls** [comment]
Damn don't I feel stupid now 🤣 thanks
