### ISSUE TITLE
Vault OIDC/JWT bound_claims does not match claims if claim value is a list

### ISSUE THREAD

**Issue by AnandJillawar** [hashicorp/vault#6685]
* Vault Version: Vault v1.1.0

I am using vault OIDC/JWT authentication mechanism.
I am having some custom claims in my oidc/jwt token.
I need to validate those claims in vault before successful login.
To do same I have used bound_claims property of vault.
But it seems that if expected claim value is list then vault does not match any of the claim.

Below is the my custom claim in oidc/jwt token :
**"permission_sets": [
    "Permission1",
    "Permission2"
  ]**

To validate above custom claim I have used bound_claims while configuring role for oidc/jwt authentication as :
**bound_claims={"permission_sets":"Permission1","permission_sets":"Permission2"}
or
bound_claims={"permission_sets":["Permission1","Permission2"]}**

**Expected Behavior:**
Vault OIDC/JWT bound_claims should match any of the claim, if expected claim value is list 

**Actual Behavior:**
Vault OIDC/JWT bound_claims does not match claims if expected claim value is list

**Comment by kalafut** [comment]
Hi,

Assuming your goal is to authorize if the "permission_sets" claim is either "Permission1" **or** "Permission2", then `bound_claims={"permission_sets":["Permission1","Permission2"]}` is the correct syntax. But support for this "match any" style validation appeared in Vault 1.1.1, so you may want to try upgrading and see if things work as expected.

**Comment by AnandJillawar** [comment]
Hi,
Thank you for quick response !!

I have one more issue.

I have one custom claim (just key value) in my jwt/oidc token as:
 **"accessright":"true"**

To validate above custom claim I have used bound_claims while configuring role for oidc/jwt authentication as :
bound_claims={"accessright":"true"}

This works only for **JWT** authentication but fails for **OIDC** authentication even though my oidc token contains  **accessright** claim.

I get below error on Vault UI:
**Error: Ember Data Request GET /v1/auth/oidc/oidc/callback returned a 400 Payload (Empty Content-Type) [object Object]**

After successful authentication with my authentication provider in callback request (viewed in browser in network tab in response I get below error)
**{"errors":["error validating claims: claim \"accessright\" is missing"]}**

Even though my oidc token contains accessright claim.

**Comment by kalafut** [comment]
Do you have a sample of the token the OIDC provider is returning, with sensitive data elided? The handling of bound_claims is very similar whether JWT or OIDC is used, so I'm wondering if the claim isn't at the top level of the token in the OIDC response?

**Comment by AnandJillawar** [comment]
It is also working for oidc now.
It was error from my identityprovider.
Thank you!

But still I am unable to perform "match any" style validation even after upgrading vault to Vault 1.1.1
I am still getting same error:

Expected Behavior:
Vault OIDC/JWT bound_claims should match any of the claim, if expected claim value is list

Actual Behavior:
Vault OIDC/JWT bound_claims does not match claims if expected claim value is list

**Comment by kalafut** [comment]
Are you defining all of the bound_claims in one JSON block?  (You should)

**Comment by AnandJillawar** [comment]
I am defining like this 
bound_claims={"permission_sets":["Permission1","Permission2"]}

**Comment by kalafut** [comment]
@AnandJillawar That's the correct syntax You mentioned another bound claim (accessright), so just to be clear you should be configuring *one* `bound_claims` parameter with all elements, like:

`bound_claims={"permission_sets":["Permission1","Permission2"], "accessright":"true"}`

But if the claim itself is a list, then the issue @chrissphinx raise may well why things aren't working. The bound claims test is basically: does the _single_ value at the specified location match the one of the expected values (or the single expected value).  There is no handling at this time for something like, "does [a,b,c] match [b,c,e]". I see the potential use, but the semantics aren't obvious (any intersection, strict subset, etc.?) and it seems like something that could get complicated to configure.

A couple of options. In the case where the claim is definitely a list, you _can_ select individual elements via JSONPointer syntax like "permission_sets/0" (first element). This probably isn't a generally useful pattern, but depending on the situation it may help.

@chrissphinx For groups in particular, one possibility is to not try to block authentication based on group, but rather let group policies drive what the token can access using "groups_claim". i.e. configure things so all access is granted through group membership.

**Comment by AnandJillawar** [comment]
@kalafut 

Thanks for your response and comments.

We are now thinking to configure our IdentityProvider to add a dedicated claim called **vault_access_right**: with value **true/false** when generating token.

We will set **bound_claims:{vault_access_right:true}** when configuring role for jwt/oidc authentication in Vault.

Now, I am facing issue in setting policy for jwt/oidc authentication.
I am using API call that is CURL for setting up jwt/oidc authentication.
I am setting policy like this:

First storing locally created json format policy in vault:
curl --header "X-Vault-Token:****************************" --request PUT 
--data @C:\**\**\VaultPolicy\SecretPolicy.json http://localhost:8200/v1/sys/policy/SecretPolicy

Applying above stored policy while configuring role:
--request POST --data {"""policies""":["""SecretPolicy"""]} http://localhost:8200/v1/auth/jwt/role/VaultRole

Above commands execute successfully, but on VaultUI I can see that above created policy **has not been applied**.
I can see only cubbyhole/ secret engine means only **default** policy is applied.

Here is my **SecretPolicy.json** file content:
{
"policy": "{\"path\":{\"auth/*\":{\"capabilities\":[\"create\",\"read\",\"list\",\"update\",\"delete\",\"sudo\"]}}},{\"path\":{\"sys/auth/*\":{\"capabilities\":[\"create\",\"read\",\"list\",\"update\",\"delete\",\"sudo\"]}}},{\"path\":{\"sys/auth\":{\"capabilities\":[\"read\",\"list\"]}}},{\"path\":{\"identity/*\":{\"capabilities\":[\"create\",\"read\",\"list\",\"update\",\"delete\"]}}},{\"path\":{\"sys/policies/*\":{\"capabilities\":[\"create\",\"read\",\"list\",\"update\",\"delete\"]}}},{\"path\":{\"sys/policies/acl/*\":{\"capabilities\":[\"create\",\"read\",\"list\",\"update\",\"delete\"]}}},{\"path\":{\"secret/*\":{\"capabilities\":[\"create\",\"read\",\"list\",\"update\",\"delete\"]}}},{\"path\":{\"ABC/*\":{\"capabilities\":[\"create\",\"read\",\"list\",\"update\",\"delete\"]}}},{\"path\":{\"sys/mounts/*\":{\"capabilities\":[\"create\",\"read\",\"list\",\"update\",\"delete\"]}}}"
}

**Issues:**
1. Above .json policy file get stored as .hcl file in VaultUI. Why?
2. If I split above json file into separate json file for each policy then it works. And file get stored as .json in vaultui. Why single json policy file is not working?

**Comment by ncabatoff** [comment]
Hi @AnandJillawar,

1. I don't know for sure, but I'm guessing it's because HCL is our default.  It's not uncommon for programs to accept inputs in multiple formats and convert them into a single preferred format for storage.

2. I think the issue you're facing is the same as described in #582, and the solution is to either escape your quotes or base64-encode your JSON.

**Comment by kalafut** [comment]
We agree that handling a received claim that's a list is a useful improvement. I'm going to close this issue and we'll centralized discussion at https://github.com/hashicorp/vault-plugin-auth-jwt/issues/46 where there is also an open community PR against this issue.

**Comment by kalafut** [comment]
Duplicates https://github.com/hashicorp/vault-plugin-auth-jwt/issues/46
