### ISSUE TITLE
Remove compulsory declaration of `secret/*` for new policies

### ISSUE THREAD

**Issue by BentCoder** [hashicorp/vault#6687]
Hi,

I hope I am doing things wrong but this is what I gathered so far.

**Is your feature request related to a problem? Please describe.**
It is a kind of problem but more like user experience problem. If I create a new policy I have to allow, at least, "list" access to `secret/*` path otherwise new policy cannot navigate to its own path `secret/staging` at all. All I would see is "Not Authorized. You don't have access to secret/.". To solve such issue, I have to use policy below.

```json
{
  "path": {
    "secret/*": {
      "capabilities": ["list"]
    }
  },
  "path": {
    "secret/staging/*": {
      "capabilities": ["create", "read", "update", "delete", "list"]
    }
  }
}
```

Although this solves the issue, my new policy can now list everything under `secret` path. It has many more paths and secret names. I can currently see paths below and the secrets inside:
- secret/staging (_only this is relevant to me and I don't want to see the ones below_)
- secret/production
- secret/test

**Describe the solution you'd like**
New policy should not be forced to declare `path:secret/*:capabilities` block.

**Comment by BentCoder** [comment]
Moved to https://github.com/hashicorp/docker-vault/issues/151

**Comment by BentCoder** [comment]
As per [suggestion](https://github.com/hashicorp/docker-vault/issues/151) I am reopening this issue here.

**Comment by calvn** [comment]
@BentCoder do you intend to give list access to `secret/` for that policy (i.e. policy holders are allowed to list paths under `secret/`), so are they only allowed to do operations strictly under `secret/staging/`? If it's the former, you can grant `"list"` capability under `secret/`. If it's the latter, you can simply remove the `secret/*` policy in your example. You should not be required to give `secret/*` capabilities in either case.

```
› vault policy read staging-admin
path "secret/staging/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

› vault token create -policy=staging-admin
Key                  Value
---                  -----
token                s.BHP01JkehXpYJ7KpLl02U8qD
token_accessor       DeYJSGJnxVoezNPyaVppNq3e
token_duration       768h
token_renewable      true
token_policies       ["default" "staging-admin"]
identity_policies    []
policies             ["default" "staging-admin"]

› VAULT_TOKEN=s.BHP01JkehXpYJ7KpLl02U8qD vault list secret/
Error listing secret/: Error making API request.

URL: GET http://127.0.0.1:8200/v1/secret?list=true
Code: 403. Errors:

* 1 error occurred:
        * permission denied

› VAULT_TOKEN=s.BHP01JkehXpYJ7KpLl02U8qD vault list secret/staging/
Keys
----
foo
```

**Comment by BentCoder** [comment]
Thank you @calvn Sadly either way permission is denied when it comes to UI listing. See tests below please.

Note: Never mind the `my-vault` path in the directory structure. I used it for this test case only.

<img width="976" alt="1" src="https://user-images.githubusercontent.com/8837278/60465439-fdbb4e00-9c48-11e9-8ade-58b87dc6e9dc.png">

```json
{
  "path": {
    "secret/staging/*": {
      "capabilities": ["create", "read", "update", "delete", "list"]
    }
  }
}
```
------------

<img width="1047" alt="2" src="https://user-images.githubusercontent.com/8837278/60465445-03189880-9c49-11e9-9f0d-eb3e23d95bf7.png">

```json
{
  "path": {
    "secret/": {
      "capabilities": ["list"]
    }
  },
  "path": {
    "secret/staging/*": {
      "capabilities": ["create", "read", "update", "delete", "list"]
    }
  }
}
```
------------
This is the only working one but `prod` folder should not be visible to `my-vault-stag` policy. The variable values inside are not visible which is ok but the whole folder shouldn't be visible to `my-vault-stag` at all because it is only relevant to `root`.

<img width="419" alt="Screen Shot 2019-07-01 at 21 34 20" src="https://user-images.githubusercontent.com/8837278/60465466-0d3a9700-9c49-11e9-9f93-f660a3e077c6.png">


```json
{
  "path": {
    "secret/*": {
      "capabilities": ["list"]
    }
  },
  "path": {
    "secret/staging/*": {
      "capabilities": ["create", "read", "update", "delete", "list"]
    }
  }
}
```

**Comment by calvn** [comment]
I see -- I didn't realize you were trying to list via the UI. Unfortunately, you currently cannot do list unless:
1. You also provide list capabilities to `secret/*` as you've done if you want to navigate in the UI from the root directory.
2) Go directly to the directory via the URL if you want tighter restrictions on the policy, like so: `https://<vault_address>/ui/vault/secrets/secret/list/staging/`.

As you mentioned, giving list access to `secret/*` wouldn't give read access to the keys itself in other directories, but it would indeed be able to list out the directory structure.

**Comment by jefferai** [comment]
You don't need to declare `secret/*`. In your case `secret/` and `secret/staging/` would be sufficient.

**Comment by calvn** [comment]
I am mistaken -- I was unable to reproduce the "not authorized" issue when I gave it another try. I was able to list directories under `secret/` by simply having permissions under the `secret/` and `secret/staging/` policy paths as described by Jeff.

**Comment by calvn** [comment]
For the second example case you shared, is that the exact ACL policy you're using? You're trying to access `secret/my-vault/` according to the screenshot, but your policy path is for `"secret/"`. Can you try using `"secret/my-vault/"`?

**Comment by BentCoder** [comment]
Just to avoid misunderstanding I'll test the whole flow from scratch one more time again and post it here if it doesn't work as expected. I'll ping you once done. Thanks both.

**Comment by BentCoder** [comment]
**While I am logged in as `root` policy**

1. I am creating a secret under `prod` path so that it is **only** visible to `root` policy.

```bash
# vault kv put secret/clients/prod/DB_PASS DB_PASS=123123
```

2. I am adding a new policy called `clients-stag` which should **only** be able to see secrets under `secret/clients/stag` path.

```json
# vi vault/file/sys/policy/_clients-stag.json

{
  "path": {
    "secret/": {
      "capabilities": ["list"]
    }
  },
  "path": {
    "secret/clients/": {
      "capabilities": ["list"]
    }
  },
  "path": {
    "secret/clients/stag/*": {
      "capabilities": ["create", "read", "update", "delete", "list"]
    }
  }
}
```

*Note:* If I omit `*` in last "path" the step 3 below will produce `permission denied` so it is necessary to have. If I remove one or both (first two paths), the `clients-stag` policy won't be able to navigate in UI - not authorized.

```bash
# vault policy write clients-stag vault/file/sys/policy/_clients-stag.json
```

```bash
# vault token create -policy=clients-stag
```

**While I am logged in as `clients-stag` policy**

3. Create a new variable.

```bash
# vault kv put secret/clients/stag/DB_PASS DB_PASS=321321
```

4. Login to UI as `clients-stag` and the result is below :( Now it is aware of the existence of `secret/clients/prod/` path.

![1111](https://user-images.githubusercontent.com/8837278/60547635-20686800-9d18-11e9-8732-1f47a092f0bb.png)

**Comment by calvn** [comment]
This is working as intended. The fact that the policy has list capabilities for `secret/clients/` means that it's able to see `prod/` since it's under that path. Even though the token is able to see that directory, it's not able to access anything below it.

If you don't want tokens with that policy to be able to see 'prod/' at all, you will have to remove that second policy path. From the UI, you would still be able to access `secret/clients/staging/` by going to the URL directly.

**Comment by BentCoder** [comment]
The fact is for the sake of good user experience I want to use UI to navigate properly rather than hiting the URL directly. If I have 100 secrets I will have to remember all URLs.

As I mentioned above removing either first or secomd or both paths prevents me seeing paths all together.

This is more like user experience thing. Hitting URL directly is like teleportating yourself from USA to UK without going through the ocean. What I am doing is like signing a contract after seeing others' contracts.

**Comment by meirish** [comment]
Hello @BentCoder, thanks for opening this issue! I wanted to give some more background on this. Both the UI and the CLI are backed by making calls to Vault's API, and `LIST` calls in the API specifically do not filter keys in their response https://www.vaultproject.io/docs/concepts/policies.html#list . If you were to list via the CLI, the result would be the same because of this.

We know that the user experience of this is difficult because in a UI the expectation is that you'd be able to navigate around and discover items you have access to, but the way `LIST` works breaks this expectation in a surprising way.

That's the current state of the things, but! we have been working on a way to mitigate the issue and make `LIST` operate in the way you're describing via a new API. We ran into some technical issues getting it to work properly in all cases, but there's been good progress and we're hoping to pick it back up in the next dev cycle. I'll be sure to update this issue when we've got something closer to shipping.

**Comment by BentCoder** [comment]
Hi @meirish. Thanks for the explanation. Basend on the acknowledgement I am happy to move on knowing that it will be somehow addressed in future.

**Comment by wjohnston-sfdc** [comment]
> That's the current state of the things, but! we have been working on a way to mitigate the issue and make `LIST` operate in the way you're describing via a new API. We ran into some technical issues getting it to work properly in all cases, but there's been good progress and we're hoping to pick it back up in the next dev cycle. I'll be sure to update this issue when we've got something closer to shipping

Is there an update on this? Using LIST on a path to view the keys while hiding the values is huge for us (CLI or Web)

**Comment by HarryKodden** [comment]
I have same request as @bentcoder please provide update

**Comment by lmacka** [comment]
I also have this same query.  Looking forward to and update in the future.
