### ISSUE TITLE
Auth: Unable to use self-signed certificate

### ISSUE THREAD

**Issue by shashanksinha1989** [hashicorp/vault#670]
I am unable to use self-signed certificate for cert auth method. Below is my configuration

$ cat config.json
backend "file"{
path = "/apps_data_01/store"
}
listener "tcp" {
address = "10.157.137.175:8200"
tls_disable = 1
}

$ vault server -config config.json &

$ vault init -key-shares=1 -key-threshold=1

After unsealing and authenticating for first time, I enabled cert auth

$ vault auth-enable cert

$ openssl req -x509 -days 365 -nodes -newkey rsa:1024  -keyout key.pem -out web-cert.pem

$ vault write auth/cert/certs/web display_name=web policies=web,prod certificate=@web-cert.pem

Upto this it was successful. After this issue occured

$  vault auth -method=cert -client-cert=web-cert.pem -client-key=key.pem -tls-skip-verify
Error making API request.

URL: PUT http://10.157.137.175:8200/v1/auth/cert/login
Code: 400. Errors:

* tls connection required

**Comment by shashanksinha1989** [comment]
Do I have to create web,prod policies before authenticating ?

**Comment by jefferai** [comment]
Your URL starts with "http". It needs to be "https".

**Comment by shashanksinha1989** [comment]
Is there is a way to do it through CLI instead of API? Also I have disabled the TLS while starting vault and skipped during authentication as well. Do I still need that ?

**Comment by jefferai** [comment]
Every `vault` CLI command supports the `-address` flag to specify the address. You can also set the `VAULT_ADDR` environment variable.

**Comment by shashanksinha1989** [comment]
Issue is resolve after upgrading vault to version 0.3.1
