### ISSUE TITLE
Support Permission Boundaries for AWS IAM User Secrets

### ISSUE THREAD

**Issue by christek91** [hashicorp/vault#6700]
**Is your feature request related to a problem? Please describe.**
I have a use case where I (an AWS Account Admin) would like to use Vault to generate IAM User credentials for some End Users. 

However, I also would like to limit the amount of permissions I have to delegate to Vault to least privilege so as to limit damage in the event of a compromise. 

Today, for Vault to create and manage IAM users and credentials it needs to have a subset of `iam:*` permissions (https://www.vaultproject.io/docs/secrets/aws/index.html#example-iam-policy-for-vault). 

But granting that amount of perms effectively makes Vault a Super Admin in the account, since it will be authorized to create new IAM users that can do anything in the AWS account. The permissions linkd to above don't grant much power to Vault on their own (just a few iam actions), but they can be used to privilege escalate by creating new IAM users that *do* have more power in the account.

If a malicious actor gains the ability to 'Create' new secrets using this backend, they could use it to create a IAM User secrets with arbitrary permissions in the AWS account.

**Describe the solution you'd like**
To prevent this kind of thing, AWS has the notion of a 'Permissions Boundary' for IAM Users and Roles. (https://www.vaultproject.io/docs/secrets/aws/index.html#example-iam-policy-for-vault). 

As an AWS Admin, let's say I want to use Vault to generate IAM User credentials. But I want to restrict the maximum IAM permissions that Vault can dole out to just `ec2:*` (arn:aws:iam::aws:policy/AmazonEC2FullAccess). I'd like to:

1. Create an IAM user for Vault to use as a secret backend. This 'Vault-Backend' IAM user would have the same IAM permissions mentioned in the docs, *but with an extra condition that requires that only Allows IAM User or User Policy creations, if the user being created it has its permissions boundary set to `arn:aws:iam::aws:policy/AmazonEC2FullAccess`*
2. I would create a new Secret Backend in Vault, using this IAM user's creds.
3. I would create an `iam_user` Secret entry in Vault, using this `Vault Backend` and some policy (probably a subset of `arn:aws:iam::aws:policy/AmazonEC2FullAccess`). 
4. Finally, end users would read from the Secret entry, and Vault would generate a new IAM user with a permissions boundary set to `arn:aws:iam::aws:policy/AmazonEC2FullAccess`

This means that from an AWS admin perspective, I can be sure that even if Vault were compromised, someone using its AWS creds would only be able to stamp out IAM users with `arn:aws:iam::aws:policy/AmazonEC2FullAccess` or lesser perms. 

For Vault to support this, it would need:

-  to take an extra input when creating an AWS Secrets Backend: the ARN of an IAM Policy to use as the Permissions Boundary for any IAM Users created with this backend.
- to pass that permissions boundary ARN to the `create-user` IAM API call when Vault actually generates Secrets using that backend.

**Describe alternatives you've considered**
It seems that the only alternative right now is to give Vault permissions that would authorize it to create IAM users that could then have arbitrary authority in the AWS account, and assume that nobody malicious will get access to Vault and create IAM User secrets with that AWS backend.

**Explain any additional use-cases**
I can't think of many others. This is kind of 3 party (AWS Admin, Vault, End User) IAM delegation is exactly what Permissions Boundaries are for. 

**Additional context**
In my use case I am the AWS Admin, and a separate group owns the Vault Instance. Thus this request comes from my desire not to give out `iam:*` perms to my account to third parties, but rather just limit the maximum permissions they could grant to least privilege.

**Comment by joelthompson** [comment]
Hi @christek91 -- I opened #6786 that should address this, but with a slight difference. Rather than a permissions boundary per mount, I decided on a permissions boundary per Vault role. The reason for this was a combination of simplicity (there wasn't really a good place already existing to store a per-mount permissions boundary) as well as flexibility (you might have a policy that requires Vault to attach one of a handful of permissions boundaries and want to vary the one that is attached based on the role, and while currently Vault only supports creating IAM users in one account per mount, that might change and so with it the need to have different permissions boundaries per role).

Let me know what you think of this solution!

**Comment by christek91** [comment]
@joelthompson this change looks perfect to me! I think that making the permissions boundary an attribute of the Vault Role is fine for my use case, and probably for most others' too. 

I'm not sure why that PR is failing CI, but I really appreciate that you've put it together. 👏 💯 🎉
