### ISSUE TITLE
identity: support time-limited group membership or policy attachment

### ISSUE THREAD

**Issue by mberhault** [hashicorp/vault#6719]
**Is your feature request related to a problem? Please describe.**
We are using [entities and group](https://www.vaultproject.io/docs/secrets/identity/index.html) to define various groups that have specific policies attached as well as operators who are members of those groups.

This works very well for established teams with fixed permissions (eg: the operators of a service will have access to credentials to access the service).
However, we would also like to grant temporary access when needed. Specifically for support or troubleshooting, when we need to pull in individuals from other teams who can help.
We can build our own tooling to remove group members or detach policies after some amount of time, but native support in Vault would make this much more robust.

**Describe the solution you'd like**
Specify an optional "lifetime" (or timestamp) to policy attachments (on entities or group) and group memberships. Once the lifetime has passed, Vault automatically detaches the policy or removes the group membership.

The mapping of metadata to attachment would be rather unwieldy in the current API. Instead, a higher-level `attach-policy` or `add-member` would make this much cleaner, with the additional benefit of supporting multiple writers (currently, I need to perform my own locking to ensure I don't overwrite another writer's changes).

**Describe alternatives you've considered**
We could currently implement this using the existing `metadata` fields on entities and groups, with our own tooling adding the proper metadata and removing the policies/memberships when needed. This tooling also need to properly synchronize changes to make sure that two instances do not overwrite each other's changes.

**Explain any additional use-cases**
I briefly mentioned the problem of synchronization. While this is not the main request in this issue, it is a concern that could be partially addressed by the proposed change.

**Additional context**
I have not put any thought into whether lifetimes could be applicable to other objects in Vault. It is likely that this feature request would be but the small part of a much wider set of changes.

**Comment by hsimon-hashicorp** [comment]
As it has been going on two years since we've heard back on this issue, I'm going to go ahead and close it. Please feel free to re-open or open a new issue as needed. Thanks!
