### ISSUE TITLE
package vault/helper/certutil is missing

### ISSUE THREAD

**Issue by jsirianni** [hashicorp/vault#6726]
**Is your feature request related to a problem? Please describe.**
The package `certutil` appears to have been removed, and I have been using `certutil.ParsePEMBundle()`

**Describe the solution you'd like**
I would like an alternative package or the `certutil` package be reimplemented

**Describe alternatives you've considered**
I have already retrieved the source code from release 1.1.1, however, I would prefer to import code maintained by Hashicorp. 

**Explain any additional use-cases**
I have a command line utility that uses this function. 

**Additional context**
If this package was never intended to be used by other projects, I can find a different solution.

**Comment by jefferai** [comment]
It's moved to sdk/helper/certutil.
