### ISSUE TITLE
Proxy protocol deny_unauthorized, http server stops listening after a request from a non-whitelisted ip

### ISSUE THREAD

**Issue by ciiqr** [hashicorp/vault#6731]
**Describe the bug**
When using `proxy_protocol_behavior = "deny_unauthorized"`, after vault receives a request from a non-whitelisted ip, the http server dies and it no longer accepts http requests even from whitelisted ips. Though vault continues running, and no logs are produced.

**To Reproduce**
1. start vault with:
```
listener "tcp" {
  ...
  proxy_protocol_behavior = "deny_unauthorized"
  proxy_protocol_authorized_addrs = "..."
}
```

2. make any http request to vault from a whitelisted ip, ie. `curl http://vault/v1/sys/health`
3. make any http request to vault from a non-whitelisted ip, ie. `curl http://vault/v1/sys/health --max-time 5`
4. make any http request to vault from a whitelisted ip, ie. `curl http://vault/v1/sys/health --max-time 5` (it will fail)

**Expected behavior**
After receiving a request from a non-whitelisted ip, vault should continue accepting http requests from whitelisted ips.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.1.2
Cluster Name    vault-cluster-0a8a25d4
Cluster ID      e3e096b8-6f27-9871-0fef-133b5fb98732
HA Enabled      false
```
* Vault CLI Version (retrieve with `vault version`):
`Vault v1.1.2 ('0082501623c0b704b87b1fbc84c2d725994bac54')`
* Server Operating System/Architecture:
alpine 3.8 (I'm using the official vault docker image: https://hub.docker.com/_/vault/)

Vault server configuration file(s):

```hcl
api_addr     = "http://..."

log_level = "trace"

listener "tcp" {
  address       = "..."
  tls_disable = "true"

  proxy_protocol_behavior = "deny_unauthorized"
  proxy_protocol_authorized_addrs = "..."
}
```

**Additional context**
- I've written a docker compose file and specific instructions that reproduce the issue here: https://gist.github.com/ciiqr/cd06d360a2b345319f8811448552d563

**Comment by aphorise** [comment]
@ciiqr - hey have you tried this in the more recent editions - eg 1.7.x or most recent 1.8.0? - can you confirm if it's resolved for you?

**Comment by ciiqr** [comment]
@aphorise just tested this on 1.8.1, this appears to be working as expected now. Cheers!
