### ISSUE TITLE
Support structured logging

### ISSUE THREAD

**Issue by eigengrau** [hashicorp/vault#6733]
It would be convenient if Vault could be configured to log in JSON format. This would alleviate the need for costly or potentially brittle parsing when shipping logs to a centralized database.

**Comment by jefferai** [comment]
It can -- set the `VAULT_LOG_FORMAT` env var to `json`

**Comment by eigengrau** [comment]
Awesome, many thanks! Is this missing from the logs, by any chance? I could have just overlooked it, but a Google search only turns up references to the Vault source code.

**Comment by jefferai** [comment]
For reasons that are mostly historical at this point we didn't want to expose this publicly when we first added this support. Now that we're using an HC-wide logging library with a given format we can probably expose this more publicly.
