### ISSUE TITLE
/v1/consul/creds/role_name fails with max_ttl must be greater than 0

### ISSUE THREAD

**Issue by adragoset** [hashicorp/vault#6742]
**Describe the bug**
When using the consul secrets engine back end issuing a token fails with a 500 error max ttl must be greater than zero

https://localhost:8200/v1/consul/creds/portworx

Role info from consul secret backend
```{\"request_id\":\"c27f85f8-9764-27a4-ac86-0955c5963e52\",\"lease_id\":\"\",\"renewable\":false,\"lease_duration\":0,\"data\":{\"lease\":3600,\"local\":false,\"max_ttl\":3600,\"policies\":[\"portworx\"],\"token_type\":\"client\",\"ttl\":3600},\"wrap_info\":null,\"warnings\":null,\"auth\":null}```

**To Reproduce**
1. Add a policy to consul
2. Add a role to the consul secrets engine that uses the consul policy
3. do get request to https://localhost:8200/v1/consul/creds/role_name
4. get request fails with 500 error and message about max ttl must be greater than 0

**Expected behavior**
Expect to be issued a token

**Environment:**
Vault 1.0.2
Consul 1.4.4

**Comment by catsby** [comment]
Hey @adragoset  - are you still able to reproduce this issues? I've tried the latest version of both Vault and Consul, as well as the versions you provide, and I'm not having any issue generating credentials. Is there any other output you could share?

**Comment by catsby** [comment]
Hello - we haven't heard back and I wasn't able to reproduce this, so I'm going to close this for now. Please let us know if you have any more information. Thanks!
