### ISSUE TITLE
"make proto" doesn't work

### ISSUE THREAD

**Issue by mgritter** [hashicorp/vault#6749]
I encountered problems with import paths running "make proto" as part of the StoragePacker v2 work:

```
...
protoc helper/identity/types.proto --go_out=plugins=grpc,paths=source_relative:.
google/protobuf/timestamp.proto: File not found.
helper/identity/types.proto: Import "google/protobuf/timestamp.proto" was not found or had errors.
```

I had to change the path to "vendor/github.com/golang/protobuf/ptypes/any/any.proto" in the storagepacker/types.proto file, but that doesn't seem like the right solution. Maybe the Makefile should be specifying a search path? Or is this fallout from conversion to Go modules?

**Comment by jefferai** [comment]
This is something specific to the version of protocol buffers you're using. Please ask in chat...
