### ISSUE TITLE
Certificate not revoking

### ISSUE THREAD

**Issue by Marusyk** [hashicorp/vault#6754]
I follow [this docs](https://www.vaultproject.io/api/secret/pki/index.html#revoke-certificate) and trying to revoke existing certificate by API. 

Expected result: certificate revoked and response with revocation_time
Actual: empty response with 204 status code

The same result in UI: Are you sure you want to revoke 22-46-55-d5-da-01-b0-da-ac-19-a4-2e-9e-26-fe-40-0c-1b-5a-23? Press Revoke and nothing.

How that behavior is not documented? Why certificate don't revoke? Why I didn't get any errors or messages what's going on? Thanks
Version: Latest docker images with vault.

**Comment by michelvocks** [comment]
Hi @Marusyk,

I double checked your issue and when I revoke the certificate, the response looks like this:
```json
< HTTP/1.1 200 OK
"data":{"revocation_time":1558345152,"revocation_time_rfc3339":"2019-05-20T09:39:12.895856Z"}
```

What Vault version do you use and could you provide an example script which helps us to reproduce your issue?

Cheers,
Michel

**Comment by Marusyk** [comment]
Yeah, in most cases it works well and returns response like you described

```
< HTTP/1.1 200 OK
"data":{"revocation_time":1558345152,"revocation_time_rfc3339":"2019-05-20T09:39:12.895856Z"}
```
but it is actually is the problem, that for some certificates it just return 204 without response body. 

I'm using[ the latest docker container 1.1.2](https://hub.docker.com/_/vault/)
I didn't know how to reproduce that, I've just generate intermediate certificate from[ this post](https://learn.hashicorp.com/vault/secrets-management/sm-pki-engine) and sometimes when I revoke it happens

**Comment by michelvocks** [comment]
It would be great to have a script which contains the steps you did to reproduce this issue.
When I follow the mentioned learning guide and revoke the generated certificates it works for me.

**Comment by jefferai** [comment]
My guess is that the certificate is already expired; or, the certificate was issued with a role that has storage turned off, so we can't revoke it.

**Comment by Marusyk** [comment]
Thanks @jefferai , you're right. The certificate was expired! I didn't notice it. So, it would be great to extend the documentation.
