### ISSUE TITLE
Uninstall procedures/documentation

### ISSUE THREAD

**Issue by saddlebear** [hashicorp/vault#6757]
There needs to be a documented uninstall procedure (and/or script) to mirror the installation procedure.  If I run a -dev mode server, I want to be sure everything is cleaned up when it quits so I can safely install a production version afterwards.   If I uninstall a production server I want to be sure everything is cleaned up as well (keys, configs, etc.). Yes, yes, I know some of the installation is manually done but I still want a guide to make sure nothing is forgotten and a script (even if it currently would just delete the executable) to clean up whatever vault may have done or may do in the future.   Even if the documentation just says, "delete the executable", uninstall procedures need to be documented for completeness.

**Comment by jefferai** [comment]
Uninstallation depends on how you installed it, so we can't really provide a document on uninstalling given we don't provide installers. If you installed via a package manager, uninstall via the package manager; if you downloaded the binary and put it somewhere, delete that binary.

When you run in dev mode, the warning states:

> WARNING! dev mode is enabled! In this mode, Vault runs entirely in-memory

As a result, no cleanup is necessary when you shut down the dev server.

**Comment by evitalis** [comment]
@jefferai I think he is asking for if he following the provided instructions and does not use dev mode. There are a lot of gaps in the documentation and this is something that would be helpful. I know I am using non-dev mode and want to reset my instance but cannot find information on.

**Comment by jefferai** [comment]
Simply delete the vault data from your data store.

**Comment by evitalis** [comment]
@jefferai What about if someone is using a production setup with a real backend like consul like I noted in my last comment? Consul docs don't explain how to do this either.
