### ISSUE TITLE
Duplicated pki mount entries, vault unable to start

### ISSUE THREAD

**Issue by tstoermer** [hashicorp/vault#6769]
**Describe the bug**
This is the concise bug description after a lot of investigation - see additional context for detailed story.
Special cases can cause a duplication of PKI mounts at same path. The PKI secret engine is used by clients with active certs and leases. The secret engine will be deleted with terraform destroy. The destroy takes up to 1 min for cleanup tasks and succeeds. Afterwards, the PKI secret engine is recreated with terraform apply. A vault server restart will now fail with error for duplicated mount:
```
2019-05-16T14:37:07.721Z [ERROR] core: failed to mount entry: path=pki-tsc-max-kube/ error="cannot mount under existing mount "pki-tsc-max-kube/""
```
This is a dangerous bug, because the problem is not discovered during runtime. Only a vault restart discovers the issue. The delayed occurrence of the error can cause massive data loss, because a backup is required before the duplicated mount has been created.

**To Reproduce**
1. Create a PKI secret engine and role definition with terraform.
2. Run clients creating several active certs/keys with leases (~1,000)
3. Delete the PKI secret engine with terraform destroy. The destroy operation will take up to 1 minute cleaning up all leases etc. Terraform destroy will succeed, but vault server shows error message like:
```
05.04.19, 10:24:15.373  10.52.187.109   vault           ERROR   secrets.system.system_ca91d9d4: unmount failed: path=pki-tsc-max-kube/ error="Delete https://127.0.0.1:8500/v1/kv/vault/logical/3c99d546-1b6a-437e-b5fe-b1e77f02bba7/revoked/58-e4-fb-ca-a8-98-59-8a-9d-9a-18-9c-25-27-9f-0c-15-45-45-12: context canceled"
05.04.19, 10:24:15.372  10.52.187.109   vault           ERROR   core: failed to clear view for path being unmounted: error="Delete https://127.0.0.1:8500/v1/kv/vault/logical/3c99d546-1b6a-437e-b5fe-b1e77f02bba7/revoked/58-e4-fb-ca-a8-98-59-8a-9d-9a-18-9c-25-27-9f-0c-15-45-45-12: context canceled" path=pki-tsc-max-kube/
```
4. Recreate the PKI secret engine with terraform apply. The create will succeed.
5. Restart the vault server and startup will fail with error:
```
2019-05-16T14:37:07.721Z [ERROR] core: failed to mount entry: path=pki-tsc-max-kube/ error="cannot mount under existing mount "pki-tsc-max-kube/""
```

**Expected behavior**
1. Vault must always fail creation of duplicated secret engine mounts at same path. Even if the secret engine delete operation failed and is leaving inconsistent mount points.
2. Terraform PKI  secret engine destroy must fail if vault delete operation is not successful (this could also be a bug in the terraform vault provider).

**Environment:**
* Vault Server Version: 1.1.2 (docker container)
* Consul Server Version: 1.4.2 (docker container)
* Terraform v0.11.14 + provider.vault v1.8.0

Vault server configuration file(s):

```hcl
backend "consul" {
  address = "######"
  scheme = "https"
  path = "vault/"
  token = "###########"
  tls_cert_file = "/#####/####.pem"
  tls_key_file = "/#####/####.pem"
  tls_ca_file = "/#####/####.pem"
}

ui = "true"

seal "awskms" {
  region = "#############"
  kms_key_id = "###########"
}

listener "tcp" {
  address = "######"
  cluster_address = "######"
  tls_cert_file = "/#####/####.pem"
  tls_key_file = "/#####/####.pem"
}

telemetry {
  prometheus_retention_time = "24h",
  disable_hostname = true
}

api_addr = "https://#####"
```

**Additional context**
The error occurred during a vault upgrade from version 1.0.2 to 1.1.2. The vault server start failed with error:
```
2019-05-16T14:37:07.721Z [ERROR] core: failed to mount entry: path=pki-tsc-max-kube/ error="cannot mount under existing mount "pki-tsc-max-kube/""
```
First attempt was to restore a backup before the update started and using old vault server version. But the error still occurred. In the next steps older backups have been tried until **a 1 month old one** worked. Consequently, the issue must not be related to the vault upgrade.
Based on the error we assumed a PKI mount delete and create operation must have caused the problem. We analyzed vault audit log and found related mount operations. Based on this, we tested the expected last working and first failing backup, that proved our thesis. 
Now I reproduced the issue with assumption, heavy cleanup of certs and leases must cause the problem during delete.

**Comment by tstoermer** [comment]
Just one hint for other affected users I found while reproducing the issue:
If you got the vault server error message during PKI mount delete, you can restart the vault primary server. Then you will see the secret mount listed again, which cannot be used anymore. But now you can cleanup this invalid mount with CLI - e.g.:
```
vault secrets disable my-pki-name
```
During my tests, it seemed to work for cleanup.
**Of cause this will not be possible, if you already recreated the mount - then you will run into the described vault start issue.**

**Comment by DrMagPie** [comment]
Hello, I have faced same issue but with kv backend in Vault version 1.2.2
here are log messages
```
2019-09-10T13:05:36.293Z [INFO]  core: successfully mounted backend: type=kv path=test-kv/
2019-09-10T13:05:36.293Z [INFO]  core: successfully mounted backend: type=kv path=secret/
2019-09-10T13:05:36.293Z [INFO]  core: successfully mounted backend: type=system path=sys/
2019-09-10T13:05:36.294Z [INFO]  core: successfully mounted backend: type=identity path=identity/
2019-09-10T13:05:36.294Z [ERROR] core: failed to mount entry: path=test-kv/ error="cannot mount under existing mount "test-kv/""
```

When this issue occurred Vault started to elect leaded and was failing to do so.
Only thing that helped to restore cluster to operating status was restoring older consul snapshot.

**Comment by DrMagPie** [comment]
@jefferai Could you please look into it?
Or should I create new issue?

**Comment by avoidik** [comment]
@DrMagPie no new issue is required, since the original issue related to all mounts except auth-N
