### ISSUE TITLE
Oracle roles: empty database name attribute with v1.1.2

### ISSUE THREAD

**Issue by mygithubthrowaway** [hashicorp/vault#6774]
**Describe the bug**
Creation of roles with oracle-plugin needs database name, with previous Vault version (v1.0.2) works without it. 
With new version (v1.1.2) the role is not valid for all my database configured under database/config/*

**To Reproduce**
With version v1.0.2:

`vault write database/roles/role-dba  creation_statements='CREATE USER {{name}} IDENTIFIED BY {{password}}; GRANT connect TO {{name}}; GRANT create session TO {{name}};  ALTER USER system GRANT CONNECT THROUGH {{name}}; grant select_catalog_role to {{name}}; audit create session by {{name}}; audit all by {{name}}; audit insert table,update table,delete table by {{name}}; audit select table by  {{name}}; '     default_ttl="1h"     max_ttl="1h";`

result:

```
Success! Data written to: database/roles/role-dba
```

with version  v1.1.2:

`vault write database/roles/role-dba  creation_statements='CREATE USER {{name}} IDENTIFIED BY {{password}}; GRANT connect TO {{name}}; GRANT create session TO {{name}};  ALTER USER system GRANT CONNECT THROUGH {{name}}; grant select_catalog_role to {{name}}; audit create session by {{name}}; audit all by {{name}}; audit insert table,update table,delete table by {{name}}; audit select table by  {{name}}; '     default_ttl="1h"     max_ttl="1h"; `

result:

```
Error writing data to database/roles/role-dba: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/roles/role-dba
Code: 400. Errors:

* empty database name attribute
```

**Expected behavior**
Roles can be definied universally and assigned to all database or selected database after role creation statement and previus  the database creation statement 

**Environment:**
* vault version
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.1.2
Cluster Name    xxxxx
Cluster ID     3932392xxxx3923993xxx
HA Enabled      false
```
* Server Operating System/Architecture:

Centos7, 3.10.0-957.12.1.el7.x86_64

Vault server configuration file(s):

```hcl
ui = true
cluster_name = "xxxxx"

listener "tcp" {
   address          = "0.0.0.0:8200"
   tls_disable      = 1 }

storage "mysql" {
  database = "xxxxxx"
  table    = "xxxxx"
  username = "xxxxxxx"
  password = "xxxxxxxxx" }

api_addr         = "http://0.0.0.0:8200"
max_lease_ttl         = "24h"
default_lease_ttl    = "12h"

plugin_directory= "/opt/vault/plugins"

```

Thanks in advance

**Comment by mygithubthrowaway** [comment]
Hi guys, sorry for bother you, can i have a statement on "a database name must be specify on role creation"? 

because we need to design our infrastructure and we still no sure if Vault is the product for our needs.

Thanks again

**Comment by jefferai** [comment]
You are missing this required parameter: https://www.vaultproject.io/api/secret/databases/index.html#db_name

**Comment by mygithubthrowaway** [comment]
> You are missing this required parameter: https://www.vaultproject.io/api/secret/databases/index.html#db_name

Thanks for you kind reply, why the db-name with version 1.0.x wasn't required?

**Comment by jefferai** [comment]
I'm not sure what you mean, the db name has been required since the plugin first came out in 0.7 or so.

**Comment by michelvocks** [comment]
Closing this now due to inactivity. @mygithubthrowaway Feel free to open a new issue if the issue is still present.
