### ISSUE TITLE
The curl command for vault CLI kv patch is not correct. 

### ISSUE THREAD

**Issue by zak905** [hashicorp/vault#6783]
**Describe the bug** 
The curl command for `vault kv patch -output-curl-string` is not correct. 

**To Reproduce**
- create some secret `vault kv put secret/test test=test `
- attempt to generate a curl request output for a patch `vault kv patch -output-curl-string secret/test test=newValue` result:

`curl -X GET -H "X-Vault-Token: $(vault print token)" http://127.0.0.1:8200/v1/secret/data/test`

**Expected behavior**
according to the API docs https://www.vaultproject.io/api/secret/kv/kv-v1.html, there is no way to update just a value, so maybe vault performs two requests when calling the vault kv patch, one for reading and one for updating.. anyways the generated command 

**Environment:**
* Vault v1.0.3
* Ubuntu 16.04

**Comment by chrishoffman** [comment]
You are correct that 2 commands are called when doing a patch and we really don't support this with the curl string.  It may just make sense to not allow the output string for patch.

**Comment by jefferai** [comment]
We could potentially only output the second of the two commands, where we write the new value with the CAS value set. This provides a hint as to what the CAS value should be, but makes it incumbent on the caller to deal with the data modifications. Throwing a non-zero error code with an error message can work too though.

**Comment by zak905** [comment]
Outputting the last command seems like a reasonable solution. I could eventually submit a PR, but please expect some time.

**Comment by mjarmy** [comment]
This is fixed via #6848.  We only output the second of the two commands, where we write the new value with the CAS value set. This provides a hint as to what the CAS value should be, but makes it incumbent on the caller to deal with the data modifications.
