### ISSUE TITLE
azure auth list roles error

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/vault#6785]
looks like the docs are wrong or the function name neglected the 's' in source https://www.vaultproject.io/api/auth/azure/index.html#list-roles
says `auth/azure/roles` but should be `auth/azure/role`

with `roles`

`{"errors":["1 error occurred:\n\t* unsupported path\n\n"]}`

with `role`

```
{
  "data": {
    "keys": [
      "dev-role",
      "prod-role"
    ]
  },
  ...
}
```

**Comment by drewmullen** [comment]
@kalafut while youre making this change you may as well do https://github.com/hashicorp/vault/issues/6793

i should have combined them... originally i thought the behavior was a bug then i realized its just another doc error

**Comment by kalafut** [comment]
@drewmullen Thanks. I’ll be going through a number of docs fixes soon.

**Comment by kalafut** [comment]
@drewmullen Thanks for filing these, and sorry they fell off the radar! We're working towards more automated API docs generation which should help avoid these sort of docs errors.
