### ISSUE TITLE
excessive vault/core/leader entries

### ISSUE THREAD

**Issue by wwalker** [hashicorp/vault#679]
I reinstalled vault (0.3.1) last night from scratch.  Consul (0.5.2) backend.

I already have 1,730 entries in vault/core/leader in Consul.

I just reinstalled from scratch because I had 2.8M leases from the 0.2.0 behavior of creating a lease for every read of any generic secret, so I'm a bit wary...

**Comment by jefferai** [comment]
Hi @wwalker ,

Just so you know, changes were pushed to `master` today which will ensure that values created in 0.2 in `generic` properly expire (this was a bug from all of the massive changes in the core going in 0.3).

Other than entries, are you seeing anything odd? Items in the log in either Consul or Vault?

**Comment by wwalker** [comment]
Entire log (minus TLS warnings):

    ==> Vault server configuration:

             Log Level: info
                 Mlock: supported: true, enabled: true
               Backend: consul (HA available)
     Advertise Address: https://10.10.10.83:8200
            Listener 1: tcp (addr: "0.0.0.0:8200", tls: "enabled")

    ==> Vault server started! Log data will stream in below:

    2015/10/06 19:02:24 [INFO] core: vault is unsealed
    2015/10/06 19:02:24 [INFO] core: entering standby mode
    2015/10/06 19:02:24 [INFO] core: acquired lock, enabling active operation
    2015/10/06 19:02:24 [INFO] core: post-unseal setup starting
    2015/10/06 19:02:24 [INFO] core: mounted backend of type generic at logical/570496ed-30a2-15cd-38e5-ed3d0f7dc78a/
    2015/10/06 19:02:24 [INFO] core: mounted backend of type cubbyhole at logical/5999a0bf-0e7a-368f-dafc-2710193ed3dd/
    2015/10/06 19:02:24 [INFO] core: mounted backend of type system at sys/
    2015/10/06 19:02:24 [INFO] rollback: starting rollback manager
    2015/10/06 19:02:24 [INFO] core: post-unseal setup complete
    2015/10/07 13:40:48 [WARN] core: leadership lost, stopping active operation
    2015/10/07 13:40:49 [INFO] core: pre-seal teardown starting
    2015/10/07 13:40:49 [INFO] rollback: stopping rollback manager
    2015/10/07 13:40:49 [INFO] core: pre-seal teardown complete
    2015/10/07 13:40:49 [INFO] core: pre-seal teardown starting
    2015/10/07 13:40:49 [INFO] core: pre-seal teardown complete
    2015/10/07 13:43:54 [ERR] core: failed to acquire lock: failed to read lock: Unexpected response code: 500
    2015/10/07 13:43:54 [ERR] core: key rotation periodic upgrade check failed: Unexpected response code: 500
    2015/10/07 13:44:59 [INFO] core: acquired lock, enabling active operation
    2015/10/07 13:45:01 [INFO] core: post-unseal setup starting
    2015/10/07 13:45:01 [INFO] core: mounted backend of type generic at logical/570496ed-30a2-15cd-38e5-ed3d0f7dc78a/
    2015/10/07 13:45:01 [INFO] core: mounted backend of type cubbyhole at logical/5999a0bf-0e7a-368f-dafc-2710193ed3dd/
    2015/10/07 13:45:01 [INFO] core: mounted backend of type system at sys/
    2015/10/07 13:45:01 [INFO] rollback: starting rollback manager
    2015/10/07 13:45:01 [INFO] expire: restored 2 leases
    2015/10/07 13:45:01 [INFO] core: post-unseal setup complete
    2015/10/07 13:50:36 [WARN] core: leadership lost, stopping active operation
    2015/10/07 13:50:40 [INFO] core: pre-seal teardown starting
    2015/10/07 13:50:40 [INFO] rollback: stopping rollback manager
    2015/10/07 13:50:40 [INFO] core: pre-seal teardown complete
    2015/10/07 13:50:44 [INFO] core: pre-seal teardown starting
    2015/10/07 13:50:44 [INFO] core: pre-seal teardown complete
    2015/10/07 13:52:11 [ERR] core: failed to acquire lock: failed to read lock: Unexpected response code: 500
    2015/10/07 13:55:48 http: TLS handshake error from 127.0.0.1:52905: EOF

**Comment by wwalker** [comment]
Interestingly, it is still 1730 entries in vault/core/leader , so it looks safe.

**Comment by jefferai** [comment]
Hi Wayne,

As you can see in the log, Vault leadership was flapping, which is why there are so many entries -- it probably stopped ramping up because leadership stabilized. I notice near the end there a 500 reported on the read lock; this is coming from Consul. Consul servers being unhappy could definitely cause this kind of behavior in Vault. Any chance you have the relevant Consul logs?

**Comment by nbrownus** [comment]
My cluster has been running for a few months and I've recently been inspecting `consul` and noticed that I have ~80k keys under `vault/core/leader`. Does `vault` ever clean these up?

**Comment by jefferai** [comment]
Hi Nathan,

It's supposed to. If you have logs from that time, do you have any entries that look like:
```
[ERR] core: clearing leader advertisement failed
```
If you do, I'd be interested in knowing what the appended errors say. If not, that's something useful to know as well.

@wwalker ^ that would also be super useful information to get from you, if you have the logs.

**Comment by nbrownus** [comment]
I haven't inspected all the occurences of that log line but the ones I did look at are related to #673 

```
[ERR] core: clearing leader advertisement failed: dial tcp 127.0.0.1:8500: connect: cannot assign requested address
[ERR] core: clearing leader advertisement failed: EOF
[ERR] core: clearing leader advertisement failed: Unexpected response code: 500 (rpc error: connection is shut down)
[ERR] core: clearing leader advertisement failed: Unexpected response code: 500 (No cluster leader)
```

**Comment by jefferai** [comment]
That's unfortunate, but makes sense.

I believe if all Vault instances are shut down, it should be safe to delete all entries under that prefix.

**Comment by nbrownus** [comment]
Is it possible that when `clearLeader` is called, instead of removing only the known `uuid` it just drops the prefix?

```
func (c *Core) clearLeader(uuid string) error {
	return c.barrier.Delete(coreLeaderPrefix)
}
```

I haven't given this any thought but it seems like it may work

**Comment by jefferai** [comment]
The danger there is a race condition between the new leader writing its entry and the old leader removing its entry.

**Comment by jefferai** [comment]
I think we're going to have the leader perform a periodic sweep of old entries.

**Comment by wwalker** [comment]
@jefferai no lines matching "clearing leader advertisement failed" in any of th logs

**Comment by wwalker** [comment]
There are network problems causing consul to flap.  the 1,730 entry count hasn't changed, neither up nor down.  Looks like the flapping cause the creation of the entries.

**Comment by wwalker** [comment]
@nbrownus if you decide to delete a large number of keys, first refer to:

https://github.com/hashicorp/consul/issues/1278

I tried to drop the keys that a different vault bug/behavior had created.  It ran for 40 hours and never finished.

**Comment by jefferai** [comment]
I would try letting the fix do its thing. It waits 200ms between each delete request to give any given backend time to breathe.

**Comment by msabramo** [comment]
@slackpad suspects that I may be running into this.

How do I check how many keys I have under `/vault/core/leader`?

Whenever I try to do a query like `curl 'http://consul01:8500/v1/kv/vault/core/leader?recurse'`, it times out and causes the Consul server to crash with a `fatal error: runtime: out of memory` error.

```
❯ GOMAXPROCS=8 consul info
WARNING: It is highly recommended to set GOMAXPROCS higher than 1

agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 9a9cc934
	version = 0.5.2
consul:
	known_servers = 0
	server = false
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 32
	max_procs = 1
	os = darwin
	version = go1.4.2
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 2183
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 1332
	members = 1
	query_queue = 0
	query_time = 1
```

**Comment by jefferai** [comment]
Unfortunately, that's a Consul question -- I simply don't know, other than to tell you to run the exact `curl` command you ran.

If this is indeed the problem, upgrading to Vault `master` will fix it -- it slowly (once every few hundred msec) removes entries. There will also be a 0.4rc out very soon.

**Comment by msabramo** [comment]
It's sounding like a better and better idea to run the development versions of Vault.

**Comment by msabramo** [comment]
How do I do the above? Do I do `make dev` and then copy the resulting binary to my servers? Or does `make dev` create a binary with development logging and stuff that I might not want?

**Comment by jefferai** [comment]
@msabramo It won't always be a better idea. In this case there is just a specific bug that hasn't been addressed in a released version yet.

`make dev` is a fine way to create a binary, however: Go will default to building a dynamic binary unless you explicitly tell it to build a static binary. If you're running this in an Alpine-based container, it may cause problems.

**Comment by slackpad** [comment]
Hi @msabramo if there are too many KVs for Consul to list without timing out you can check the number by looking through your latest snapshot:

```
cd <consul data dir>/raft/snapshots/<latest>
strings state.bin | grep vault/core/leader | wc -l
```

That should output the number of keys under that prefix.

**Comment by msabramo** [comment]
@slackpad: Thanks! Here's what I get:

```
CORP\marca@consul01:~$ cd /opt/consul/data/raft/snapshots

CORP\marca@consul01:/opt/consul/data/raft/snapshots$ ls -l
total 8
drwxr-xr-x 2 consul consul 4096 Nov 15 21:01 212674-44864309-1447650070566
drwxr-xr-x 2 consul consul 4096 Nov 15 21:39 212679-44873368-1447652351319

CORP\marca@consul01:/opt/consul/data/raft/snapshots$ cd 212679-44873368-1447652351319/

CORP\marca@consul01:/opt/consul/data/raft/snapshots/212679-44873368-1447652351319$ ls -l
total 568572
-rw-r--r-- 1 consul consul       199 Nov 15 21:41 meta.json
-rw-r--r-- 1 consul consul 582207599 Nov 15 21:41 state.bin

CORP\marca@consul01:/opt/consul/data/raft/snapshots/212679-44873368-1447652351319$ strings state.bin | grep vault/core/leader | wc -l
2789858
```

I'm going to guess that something is wrong here, since there's more than 2.7 million keys in Consul and my state file is 556 MB, even though we are only storing 10 keys in Vault.

```
CORP\marca@consul01:/opt/consul/data/raft/snapshots/212679-44873368-1447652351319$ du -sh state.bin
556M	state.bin
```

**Comment by msabramo** [comment]
I have now upgraded my 3 nodes to the latest version of Vault master and it doesn't seem to be getting any better. In fact, the number of Consul keys seems to have *increased*:

```
CORP\marca@consul01:/opt/consul/data/raft/snapshots$ while true; do strings $(ls -1t | grep -v '.tmp' | head -n 1)/state.bin | grep vault/core/leader | wc -l; sleep 30; done
2801445
2801445
2801445
2801445
2801445
2801445
2801445
```

I'm going to bed now and will let it run overnight, but I'm not terribly helpful that I will have significantly less keys in the morning.

**Comment by jefferai** [comment]
Hi Marc,

What's going on in the Vault logs? Is leadership flapping constantly? If no node is staying leader long enough to actually start the process, it won't clear anything.

**Comment by jefferai** [comment]
Also, it should be fine to shut down your Vault nodes and simply delete all of the leader entries. @slackpad is it possible to do this without Consul listing the keys internally since that seems to be an issue?

**Comment by msabramo** [comment]
Looks like I was right in my suspicion that it would not be better in the morning. I had it print hourly snapshots:

```
CORP\marca@consul01:/opt/consul/data/raft/snapshots$ while true; do date; strings $(ls -1t | grep -v '.tmp' | head -n 1)/state.bin | grep vault/core/leader | wc -l; sleep 3600;
 done
Sun Nov 15 23:38:41 PST 2015
2805322
Mon Nov 16 00:38:55 PST 2015
2828898
Mon Nov 16 01:39:12 PST 2015
2848734
Mon Nov 16 02:39:35 PST 2015
2861804
Mon Nov 16 03:39:51 PST 2015
2875542
Mon Nov 16 04:40:09 PST 2015
2897244
Mon Nov 16 05:41:45 PST 2015
2917834
```

**Comment by msabramo** [comment]
@jefferai The Vault logs are dominated by this:

```
2015/11/16 06:00:02 http: TLS handshake error from 10.128.40.8:59546: EOF
2015/11/16 06:00:04 http: TLS handshake error from 10.128.40.9:36917: EOF
2015/11/16 06:00:07 http: TLS handshake error from 10.128.40.8:59997: EOF
2015/11/16 06:00:09 http: TLS handshake error from 10.128.40.9:37356: EOF
2015/11/16 06:00:12 http: TLS handshake error from 10.128.40.8:60446: EOF
2015/11/16 06:00:14 http: TLS handshake error from 10.128.40.9:37824: EOF
2015/11/16 06:00:17 http: TLS handshake error from 10.128.40.8:60899: EOF
2015/11/16 06:00:19 http: TLS handshake error from 10.128.40.9:38268: EOF
2015/11/16 06:00:22 http: TLS handshake error from 10.128.40.8:33127: EOF
2015/11/16 06:00:24 http: TLS handshake error from 10.128.40.9:38726: EOF
2015/11/16 06:00:27 http: TLS handshake error from 10.128.40.8:33575: EOF
2015/11/16 06:00:29 http: TLS handshake error from 10.128.40.9:39173: EOF
```

I actually am having trouble finding out what `10.128.40.[8-9]` are. They are not in our DNS; nor have I have found them in our OpenStack inventory even though the `10.128.40` subnet strongly suggests that they are OpenStack VMs.

Should I dig more into finding out what those hosts are? Or is that a red herring as far as this issue is concerned?

**Comment by msabramo** [comment]
And those errors are pretty much all that is happening in the Vault logs. If I exclude them:

```
CORP\marca@consul01:~$ grep -v 'TLS handshake error' /var/log/vault.log
==> Vault server configuration:

         Log Level: info
             Mlock: supported: true, enabled: false
           Backend: consul (HA available)
 Advertise Address: https://consul01.mycompany.com:8200
        Listener 1: tcp (addr: "0.0.0.0:8200", tls: "enabled")
           Version: Vault v0.4.0-dev (b2d2a11cb2341c70425883473075dfa2d16b5512)

==> Vault server started! Log data will stream in below:
```

**Comment by msabramo** [comment]
Hmmm, I just realized I never unsealed the vault instances -- could that be it?

**Comment by msabramo** [comment]
Ah, in the *Consul* logs there is some leader flapping going on:

```
    2015/11/16 06:18:32 [WARN] raft: Heartbeat timeout reached, starting election
    2015/11/16 06:18:32 [INFO] raft: Node at 10.128.40.126:8300 [Candidate] entering Candidate state
    2015/11/16 06:18:32 [ERR] http: Request /v1/kv/vault/core/lock?index=45722512&wait=15000ms, error: No cluster leader
    2015/11/16 06:18:32 [ERR] http: Request /v1/session/destroy/76e82ee8-b1a4-87a8-4853-928e3e4bf595, error: No cluster leader
    2015/11/16 06:18:32 [ERR] http: Request /v1/kv/vault/core/leader/000d1e01-d92d-d2f6-fac1-2092b3ce6b74, error: rpc error: leadership lost while committing log
    2015/11/16 06:18:32 [ERR] http: Request /v1/kv/vault/core/leader/000d1f4d-2954-ca4b-4ff6-4d0e1a7645b5, error: No cluster leader
    2015/11/16 06:18:33 [ERR] http: Request /v1/kv/vault/core/leader/000d2dec-6ff4-1551-d72e-02368f9f5094, error: No cluster leader
    2015/11/16 06:18:33 [ERR] http: Request /v1/kv/vault/core/leader/000d30d6-9aa0-4cd9-f76e-7599408c173c, error: No cluster leader
    2015/11/16 06:18:33 [ERR] http: Request /v1/kv/vault/core/leader/000d3abc-fffc-455b-3e0d-39fc48b56e5c, error: No cluster leader
    2015/11/16 06:18:33 [ERR] http: Request /v1/kv/vault/core/leader/000d40e9-88f9-1959-dc19-412f6ac99e31, error: No cluster leader
    2015/11/16 06:18:33 [INFO] raft: Duplicate RequestVote for same term: 212895
    2015/11/16 06:18:33 [ERR] http: Request /v1/kv/vault/core/leader/000d4d2f-06ae-66cb-0fde-9044fe543ac9, error: No cluster leader
    2015/11/16 06:18:34 [ERR] http: Request /v1/kv/vault/core/leader/000d5cda-ceb4-26f4-4d19-ece0f9d23c66, error: No cluster leader
    2015/11/16 06:18:34 [ERR] http: Request /v1/kv/vault/core/leader/000d6712-2d84-6bec-fe19-2ac44692cda0, error: No cluster leader
    2015/11/16 06:18:34 [WARN] raft: Election timeout reached, restarting election
    2015/11/16 06:18:34 [INFO] raft: Node at 10.128.40.126:8300 [Candidate] entering Candidate state
    2015/11/16 06:18:34 [ERR] http: Request /v1/kv/vault/core/leader/000d69a3-77dc-99da-70f4-bb080d066928, error: No cluster leader
    2015/11/16 06:18:34 [ERR] http: Request /v1/kv/vault/core/leader/000d76b6-ffb8-5c76-dae7-14dc406355f1, error: No cluster leader
    2015/11/16 06:18:34 [ERR] http: Request /v1/session/renew/e47972d0-ceb0-4c66-1d00-452b2ecd34a7, error: No cluster leader
    2015/11/16 06:18:34 [ERR] http: Request /v1/kv/vault/core/leader/000d7b5c-7af0-3f6e-eff1-80d8c5ed9f00, error: No cluster leader
    2015/11/16 06:18:35 [ERR] http: Request /v1/kv/vault/core/leader/000d8c00-f06a-3390-f4ca-942307def354, error: No cluster leader
    2015/11/16 06:18:35 [ERR] http: Request /v1/kv/vault/core/leader/000d8f5f-be9f-1781-590a-1788b130e1bf, error: No cluster leader
    2015/11/16 06:18:35 [ERR] http: Request /v1/kv/vault/core/leader/000d9b16-8825-34e4-c790-9bfb0080741e, error: No cluster leader
    2015/11/16 06:18:35 [WARN] raft: Election timeout reached, restarting election
    2015/11/16 06:18:35 [INFO] raft: Node at 10.128.40.126:8300 [Candidate] entering Candidate state
    2015/11/16 06:18:35 [ERR] http: Request /v1/kv/vault/core/leader/000d9b38-c600-aeb6-8884-ebc0a2e68487, error: No cluster leader
    2015/11/16 06:18:35 [INFO] raft: Node at 10.128.40.126:8300 [Follower] entering Follower state
    2015/11/16 06:18:35 [WARN] raft: Failed to get previous log: 45726075 log not found (last: 45726070)
    2015/11/16 06:18:36 [INFO] consul: New leader elected: consul02.mycompany.com
```

**Comment by jefferai** [comment]
@msabramo So a few things related to those entries:

* The advertisement happens when one node becomes leader
* The cleanup performs a list, then iterates through the list and deletes entries not matching the current advertised leader

Because it performs a list, perhaps that operation is never actually running successfully.

In addition, Vault tries to do the right think if its storage backend becomes unavailable, but generally Consul-dependent things will become unhappy when Consul itself can't get a leader.

I think your best bet at this point, since listing is failing, is to simply wipe the entries directly in Consul. Here's my suggestion:

1. Stop all Vault nodes
2. Use the Consul API to run a recursive delete on `vault/core/leader`
3. Make sure that Consul is happy
4. Start one Vault node, verify that it can unseal properly
5. Start other Vault nodes

**Comment by msabramo** [comment]
```
CORP\marca@consul01:/opt/consul/data/raft/snapshots$ sudo stop vault
vault stop/waiting
CORP\marca@consul01:/opt/consul/data/raft/snapshots$ curl -X DELETE 'http://localhost:8500/v1/kv/vault/core/leader?recurse'
^C
CORP\marca@consul01:/opt/consul/data/raft/snapshots$ date
Mon Nov 16 06:40:00 PST 2015
CORP\marca@consul01:/opt/consul/data/raft/snapshots$ curl -X DELETE 'http://localhost:8500/v1/kv/vault/core/leader?recurse'
rpc error: timed out enqueuing operation
```

**Comment by jefferai** [comment]
Marc, what is your tolerance for taking Consul down? Maybe if you have all but one server leave, since the Raft data won't have to trip through other nodes, it won't time out. But I'm not sure. Or maybe the time out is toggleable and can be set higher.

@slackpad Can you provide some assistance here?

**Comment by msabramo** [comment]
I'm willing to take Consul down, since we're only using Consul experimentally now.

I'll wait for @slackpad to chime in before I mess around too much though.

**Comment by slackpad** [comment]
Unfortunately there's no good way to delete this many keys with this version of Consul, see https://github.com/hashicorp/consul/issues/1278 which was an offshoot of this one. If it's possible for you to reestablish the cluster that's probably the cleanest way to go (take all the servers down, remove the data-dir, and then restart everything and manually restore your state).

It's hard to see from the logs why the leaders are flapping - what kind of machines are these running on and how many nodes are in your cluster?

**Comment by jefferai** [comment]
@slackpad Any chance they're flapping simply because of how many entries? The elected leader can't cope with something or other?

Also, do you think that things might work better if he brings his cluster size down to one, since it won't have to coordinate with other servers?

**Comment by slackpad** [comment]
@jefferai I don't think there should be any impact in the steady state due to having so many entries - only if they are being churned (rapidly adding more, trying to list them all, or deleting them) would it affect the timing and possibly leader elections. This will still be super slow even with one server since it all has to go through the Raft log, tombstones get created, and there's a bunch of GC. It's generally just a super bad operation for Consul to try an delete millions of keys in a single transaction.

**Comment by slackpad** [comment]
Since the delete might be a huge ongoing transaction that is probably blocking all other write ops.

**Comment by msabramo** [comment]
It might be possible to come to this conclusion by piecing together a bunch of the comments, but let me state it simply here so anyone who finds this can find it easily and clearly in one place:

It appears to be very bad to attempt to do a DELETE of a very large number of keys. In my case, before the attempted delete, some Consul operations were slow and timed out, but others worked fine. In attempting to delete the 2.8 million `/vault/core/leader` keys that accumulated, this seems to have made things worse, as that DELETE never finished and appears to be blocking all other operations in Consul. In other words, attempting a DELETE of a large number of keys could mess up your cluster so think twice before doing that.

**Comment by msabramo** [comment]
OK, now I'm scratching my hat again.

I just reinitialized my Consul cluster. I did this by doing the following on the 3 Consul nodes:

- Stop vault and consul
- `sudo rm -rf /opt/consul/data /var/log/consul /var/log/vault*`
- In `/etc/consul.conf`, set `bootstrap_expect` to 3
- Start consul (decided to wait on Vault)

The 3 consul nodes seem to have elected a leader and joined up and everything looks pretty good.

But...

I go to the Consul UI and look at KVs and I was very surprised to see a bunch of `vault/core/leader` keys:

<img width="573" alt="screen shot 2015-11-18 at 11 00 22 pm" src="https://cloud.githubusercontent.com/assets/305268/11264435/48717400-8e48-11e5-8597-5952e6574641.png">

Even more disturbingly, the number of keys seems to be growing:

```
CORP\marca@consul02:/opt/consul/data/raft/snapshots$ while true; do date; strings $(ls -1t | grep -v '.tmp' | head -n 1)/state.bin | grep vault/core/leader | wc -l; sleep 60; d
one
Wed Nov 18 22:49:48 PST 2015
6940
Wed Nov 18 22:50:48 PST 2015
6940
Wed Nov 18 22:51:48 PST 2015
6940
Wed Nov 18 22:52:49 PST 2015
13276
Wed Nov 18 22:53:49 PST 2015
13276
Wed Nov 18 22:54:49 PST 2015
13276
Wed Nov 18 22:55:49 PST 2015
13276
Wed Nov 18 22:56:49 PST 2015
19923
Wed Nov 18 22:57:49 PST 2015
19923
Wed Nov 18 22:58:49 PST 2015
23523
...
Wed Nov 18 23:02:50 PST 2015
30141
Wed Nov 18 23:03:50 PST 2015
30141
Wed Nov 18 23:04:50 PST 2015
34910
Wed Nov 18 23:05:51 PST 2015
34910
```

Now the really strange thing is that **vault is not running on any of the 3 servers!**

```
$ for x in 01 02 03; do echo "=== consul$x ==="; ssh consul$x pgrep -fl vault | wc -l; done
=== consul01 ===
       0
=== consul02 ===
       0
=== consul03 ===
       0
```

My best guess is that somewhere else there is a node in my company that is running Vault, that I have forgotten about or don't know about; possibly even spun up by someone other than me.

Which begs the question, do Vault servers record their identity somewhere in Consul so that I can figure out if there is some rogue Vault server running somewhere?

If it's recorded in the Consul KV store, then I guess I need to find it really quick, before the number of keys grows to a point that I can no longer query it anymore :frowning: 

Cc: @sudarkoff

**Comment by slackpad** [comment]
Since the level of traffic is pretty high I'd probably use tcpdump to figure out which agent is making the calls to the KV store. Depending on how Vault is configured you should see that traffic coming in to your Consul servers on tcp/8300 or tcp/8500. You'll need to check this on each of your servers because Vault (or the Consul agent on its machine if it's set up that way) can talk to any of the servers and then they will forward traffic to the leader for writes, so Vault won't necessarily be connecting directly to the leader.

**Comment by msabramo** [comment]
I found one rogue server with nmap and nuked it.

Going to see if that makes the `vault/core/leader` keys go away. Crossing my fingers...

Do you think it makes sense for Vault servers to write to the KV store with their IP address so that it's a little bit easier to see who all the Vault servers are?

**Comment by slackpad** [comment]
I'd probably set up Consul's ACLs to protect `/vault` and give your Vault servers a token they can use to write to that path. That way only an authorized Vault server would ever be able to create entries there.

**Comment by jefferai** [comment]
@wwalker Any progress?

**Comment by wwalker** [comment]
Yes, down to only 13 entries now.
@msabramo Is yours down now?

**Comment by wwalker** [comment]
Spoke too soon, back up to 1.6 million entries.

Something went haywire of the weekend.

**Comment by wwalker** [comment]
consul is crashing constantly.  running out of memory on the boxes.

If I :
1. stop vault
2. externally sort the vault/core/leader entries by ModifyIndex,
3.  Can I delete them via consul a few at a time as long as I don't delete say the last 100?

**Comment by jefferai** [comment]
@wwalker Do you have logs from the weekend? I'll have to defer to @slackpad regarding deleting entries from Consul.

**Comment by wwalker** [comment]
Pretty sure there is already a fix for this in 0.4.0.  I'm still on vault 0.3.1.

2016/01/02 00:49:42 [WARN] core: leadership lost, stopping active operation
2016/01/02 00:49:55 [INFO] core: pre-seal teardown starting
2016/01/02 00:49:55 [INFO] rollback: stopping rollback manager
2016/01/02 00:49:55 [INFO] core: pre-seal teardown complete
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x94b267]

goroutine 2144223 [running]:
github.com/hashicorp/vault/vault.(*ExpirationManager).emitMetrics(0x0)
        /gopath/src/github.com/hashicorp/vault/vault/expiration.go:613 +0xf7
github.com/hashicorp/vault/vault.(*Core).emitMetrics(0xc82036e000, 0xc8210f8840)
        /gopath/src/github.com/hashicorp/vault/vault/core.go:1624 +0xa8
created by github.com/hashicorp/vault/vault.(*Core).postUnseal
        /gopath/src/github.com/hashicorp/vault/vault/core.go:1380 +0x961

**Comment by jefferai** [comment]
@wwalker Yes -- there is a fix for that in 0.4. Probably you were hitting that bug, and so no Vault was ever able to keep leadership. So you transitioned leadership 1.6 million times over the weekend...  :-/

**Comment by slackpad** [comment]
@wwalker Vault doesn't use Raft in any way so it won't re-create them. If you can shut down Vault and somehow delete these entries from Consul then you should be good. Unfortunately there's not a great way to do huge bulk deletes, especially if you are tight on memory.

**Comment by wwalker** [comment]
Thank you both!

**Comment by wwalker** [comment]
Today, I have 3 servers in standby.  Their logs are all filled with lines like this:

2016/01/05 09:04:56 [ERR] core: failed to acquire lock: failed to create session: Unexpected response code: 500 (timed out enqueuing operation)

Is there some way to change the timeout ?  I'm assuming that consul is so slow (due to still around 1 Million vault/core-leader entries) that it is causing this.

I'm currently on 0.3.1.  While waiting on a response here, I will be planning our 0.4.0 upgrade....

**Comment by jefferai** [comment]
@wwalker That error is coming from the Raft implementation underlying Consul, so I'm guessing the answer is that it can't be changed without manually tweaking code and rebuilding. @slackpad may have a better idea.

**Comment by slackpad** [comment]
@wwalker is your delete ongoing? That will unfortunately take a write lock that will block Consul updates to the data store until the big delete is done.

**Comment by jefferai** [comment]
Closing for now as it's been about two months -- let us know if you're still having issues.
