### ISSUE TITLE
Getting to High Availability

### ISSUE THREAD

**Issue by rifaterdemsahin** [hashicorp/vault#6794]
What are the syntax changes that need to happen for HA in Vault?

What should I consider to do ?

**Comment by bartdzkan** [comment]
Picking a HA storage backend ex. Consul
https://www.vaultproject.io/docs/configuration/storage/index.html

Plus your architecture. 

https://www.vaultproject.io/docs/internals/high-availability.html

**Comment by michelvocks** [comment]
Hi @rifaterdemsahin!

I will close this since this doesn't seem to be an issue for Vault itself but more a question around Vault's High Availability mode. Please use the [Discussion Forum](https://discuss.hashicorp.com/c/vault) for further questions. 

Cheers,
Michel
