### ISSUE TITLE
Lastpass as a backend storage mechanism.

### ISSUE THREAD

**Issue by adamdecaf** [hashicorp/vault#68]
What do people think of adding support for lastpass vaults to be used as backend storage for credentials? There's a master password on a lastpass vault but you could namespace certain configs into folders.

It could also allow for the import into vault from a lastpass vault. I know that I have some shared passwords in lastpass that would be great to be able to "import" into vault. Perhaps that should be more of a manual process though?

I can see the syncing of the remote lastpass vault state and the local vault state as potentially being an issue.

**Comment by mitchellh** [comment]
This sounds like a good idea! Its not one I think we'll pursue directly but if there was a PR we'd definitely be interested in merging it.

**Comment by nozpheratu** [comment]
+1
I think having vault only sync to a designated lastpass folder or list of folders would be the best approach. Just thinking out loud, but maybe having some kind of digest or time stamp on the note name a la rails assets would help with the syncing.
