### ISSUE TITLE
Prometheus /sys/metrics invalid

### ISSUE THREAD

**Issue by williamlord** [hashicorp/vault#6800]
**Describe the bug**
The metrics endpoint using Prometheus format produces invalid metrics.

**To Reproduce**
1. Copy the sample response from https://www.vaultproject.io/api/system/metrics.html#format into a file.
2. cat file | promtool check metrics
3. see error
```
vault_audit_log_request_failure counter metrics should have "_total" suffix
vault_audit_log_response_failure counter metrics should have "_total" suffix
```

Using promtool, version 2.10.0 (branch: non-git, revision: non-git).

From a running instance there are two more as well.
```
vault_audit_log_request_failure counter metrics should have "_total" suffix
vault_audit_log_response_failure counter metrics should have "_total" suffix
vault_runtime_free_count non-histogram and non-summary metrics should not have "_count" suffix
vault_runtime_malloc_count non-histogram and non-summary metrics should not have "_count" suffix
```

**Expected behavior**
Expect there to be no errors.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.1.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.1.2 ('0082501623c0b704b87b1fbc84c2d725994bac54')

**Comment by ncabatoff** [comment]
Hi @williamlord,

Failure to follow the naming convention doesn't make the metrics invalid, just unconventional.  I agree they ideally ought to be renamed, but bear in mind that we emit metrics for many different systems besides Prometheus, and that the other systems predate our support for Prometheus.  Renaming these metrics to make promtool happy would likely break many existing dashboards/alerts.  So I'm not sure if it will happen.

**Comment by williamlord** [comment]
Changing them will also break backwards compatibility if others depend on them.

That being said, is `?format=prometheus` usable at in the current state? I'm not very familiar with Prometheus, is there a workaround to skip invalid metrics?

**Comment by ncabatoff** [comment]
Yes, it's quite usable.  And again, the metrics aren't invalid, they just don't follow the recommended naming conventions.  Prometheus works just fine with them, so there's no need to skip them.

**Comment by williamlord** [comment]
OK cool, moved beyond the "no token found" Prometheus warning, had the scrape misconfigured.

Minimal reproduction of working scrape.

`vault server -dev -config vault.hcl`

vault.hcl
```
listener "tcp" {
  address = ":8200"
  tls_disable = true
}
```

prometheus.yml
```
scrape_configs:
  - job_name: 'vault'
    metrics_path: '/v1/sys/metrics'
    params:
      format: [prometheus]
    bearer_token: 'example'
    static_configs:
    - targets: ['localhost:8200']
```
