### ISSUE TITLE
Inconsistent behaviour when Listing folders in KV

### ISSUE THREAD

**Issue by Obito93** [hashicorp/vault#6804]
**Describe the bug**

vault does not give a consistent answer if a folder does or does not exist

**To Reproduce**
Consider the following structure in the KV2 Secret Engine:

kv/Application/App1/Secret
kv/Application/App2/Secret
kv/Application/App3/
kv/Application/App4/Secret
kv/Application/test

Where App3/ is an empty folder.

Executing a list via the HTTP API on kv/Application/ returns the following answer with the HTTP status code 200:

{
    "request_id": "13a80f8d-b7b8-5543-f0c6-2c3e284c8b2f",
    "lease_id": "",
    "renewable": false,
    "lease_duration": 0,
    "data": {
        "keys": [
            "App1/",
            "App2/",
            "App3/",
            "App4/",
            "test"
        ]
    },
    "wrap_info": null,
    "warnings": null,
    "auth": null
}

According to this answer, the Folder kv/Application/App3/ should exist.

Executing a list via the HTTP API on kv/Application/App3/ returns the following answer with the HTTP status code 404:
{
    "errors": []
}

According to this answer, the Folder kv/Application/App3/ should not exist.

**Expected behavior**
Either Vault should delete empty folders so they won't get listed beforehand or executing the list command on an empty folder should give an empty answer, stating that there is no item in it.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.1.1
Cluster Name    vault-cluster-ceed1c1b
Cluster ID      e5435a20-c94d-14ce-6f66-b90a5ba92ab3
HA Enabled      false
* Vault CLI Version (retrieve with `vault version`):
Vault v1.1.1 ('a3dcd63451cf6da1d04928b601bbe9748d53842e')
* Server Operating System/Architecture:
Windows 10
Vault server configuration file(s):

```hcl
storage "file" {
  path    = "C:/vault/data"
}


listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = 0
  tls_min_version = "tls12"
  tls_cert_file = "vault.crt"
  tls_key_file = "vault.key"
  
}

api_addr = "https://127.0.0.1:8200"
ui = true

log_level = "Trace"
```

**Additional context**

**Comment by Obito93** [comment]
@aphorise sadly, I am no longer associated with the project, because I was an intern at that moment, which has ended. So I am no longer  
able to give you any infornation on this.

Best regards, 
Obito

**Comment by aphorise** [comment]
@michelvocks I suspect this issue may be closed as I could not recreate it nor see an issue here.

**Comment by raskchanky** [comment]
@aphorise Sounds good, I'll close this issue for now, but feel free to reopen later if needed.
