### ISSUE TITLE
"invalid ciphertext: wrong number of fields" when listing secret in a folder

### ISSUE THREAD

**Issue by chris-ng-scmp** [hashicorp/vault#6805]
After created a secret for a specific pattern of the secret path, the parent folder can't be able to list secret anymore and show the following error.

```
1 error occurred: * invalid ciphertext: wrong number of fields
```

**Describe the bug**
![image](https://user-images.githubusercontent.com/2509212/58697814-a1a4a600-83cc-11e9-9f90-83c46a0938e8.png)

**To Reproduce**
- Step 1 - Create a secret with any one of the following patterns:
>tes2/1234567890/1234567890/1234567890/123456785/123456
>test/1234567890/1234567890/1234567890/123456785/123456 
>tes2/1234567890/1234567890/1234567890/123456786/123456

- Step 2 - Secret created, and able to show the secret page

- Step 3 - Go back to the parent folder to list the secret

**Expected behavior**
Should not getting the error, instead of, should list the created secret name. 

**Environment:**
* Vault Server Version
```
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    1
Threshold                1
Version                  1.1.2
Cluster Name             vault-cluster-90e78b1f
Cluster ID               3a25297f-4520-3a01-784e-d64bed9911c3
HA Enabled               true
HA Cluster               https://vault.kube-tools.svc.cluster.local:8201
HA Mode                  standby
Active Node Address      http://vault.kube-tools.svc.cluster.local:8200
```
* Vault CLI Version (retrieve with `vault version`):
```
Vault v1.1.1 ('a3dcd63451cf6da1d04928b601bbe9748d53842e')
```
* Server Operating System/Architecture:
VAULT_SEAL_TYPE: alicloudkms
MySQL backend with HA enabled

**Comment by chris-ng-scmp** [comment]
Finally, we found the issue is caused by MySQL default schema length for vault_key field is 512 and MySQL server parementer `innodb_strict_mode` was set to `off`, so when the encrypted secret path is longer than 512 will be truncated.

here is the solution:

- Set MySQL parameter `innodb_large_prefix` to `on`
- Make sure MySQL parameter `innodb_strict_mode` is `on`, just in case the encrypted key won't be truncated.
- Change the field length to longer
```
mysql> describe vault;
+-------------+----------------+------+-----+---------+-------+
| Field       | Type           | Null | Key | Default | Extra |
+-------------+----------------+------+-----+---------+-------+
| vault_key   | varbinary(512) | NO   | PRI | NULL    |       |
| vault_value | mediumblob     | YES  |     | NULL    |       |
+-------------+----------------+------+-----+---------+-------+
2 rows in set (0.04 sec)

mysql> ALTER TABLE vault modify vault_key varbinary(1024);
Query OK, 0 rows affected (0.23 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> describe vault;
+-------------+-----------------+------+-----+---------+-------+
| Field       | Type            | Null | Key | Default | Extra |
+-------------+-----------------+------+-----+---------+-------+
| vault_key   | varbinary(1024) | NO   | PRI | NULL    |       |
| vault_value | mediumblob      | YES  |     | NULL    |       |
+-------------+-----------------+------+-----+---------+-------+
2 rows in set (0.00 sec)
```

**Comment by jefferai** [comment]
Glad you found the issue!

**Comment by RogueOverride** [comment]
I too am running into this issue. 

Vault 1.5.4
MySQL 8.0
KV Secret Engine Version 2.

I altered the table for vault_key length to be 1024, but now I get this wrong number of fields error. And because the database is encrypted, it's hard to tell which record I need to delete because the Vault binary won't delete it for me.
