### ISSUE TITLE
Vault should maintain docker-volume-libsecret

### ISSUE THREAD

**Issue by kallisti5** [hashicorp/vault#6807]
**Describe the solution you'd like**
docker-volume-libsecret offers a compelling story around providing secret access to containers in a non-offensive way.  However, this docker volume plugin is:

  * Unofficial  (risky)
  * Seemingly unmaintained since 2015

Since this volume plugin represents an *awesome* migration path to vault (without natively supporting using vault for secrets), it is a core essential to a new vault environment... yet it's unmaintained.

Hashicorp should fork the code, and maintain a "more official" copy.  Even if hashicorp doesn't continue its development.

**Comment by kallisti5** [comment]
https://github.com/ehazlett/docker-volume-libsecret

**Comment by chrishoffman** [comment]
Thanks for the suggestion.  At this time, we are not looking to support this type of integration.

**Comment by kallisti5** [comment]
Ok... does Hasicorp support *any* integration with docker for secrets?  I mean.. that's kind of the point of Vault.

**Comment by Shogun8** [comment]
+1 for this suggestion. Otherwise how does one utilize Hashicorp Vault with docker-compose?
