### ISSUE TITLE
PKI role disrespects TTL?

### ISSUE THREAD

**Issue by avoidik** [hashicorp/vault#6811]
Hi,

Kindly asking for advice, I was able to issue a certificate with TTL beyond `ttl` and `max_ttl` parameters being set on a PKI role. Not sure what is that, perhaps I didn't get the concept right. Here is the steps to reproduce it.

Enable PKI backend

```
vault secrets enable -path=pki/test-backend pki
```

Configure PKI backend

```
vault write pki/test-backend/config/ca pem_bundle=@bundle.pem
```

Configure role for PKI backend

```
vault write pki/test-backend/roles/test-role \
  allowed_domains="anyhost.dev" \
  allow_subdomains=true \
  ttl=168h
```

Now generate certificate with valid TTL  -> success; which is fine

```
vault write pki/test-backend/issue/test-role \
    common_name="test.anyhost.dev" \
    ttl=168h
```

Check it

```
$ vault read pki/test-backend/roles/test-role | grep ttl
max_ttl                               0s
ttl                                   168h
```

Now generate certificate with invalid TTL -> success (**why?**)

```
vault write pki/test-backend/issue/test-role \
    common_name="test.anyhost.dev" \
    ttl=169h
```

Let's set `ttl` and `max_ttl` altogether

```
vault write pki/test-backend/roles/test-role \
  allowed_domains="anyhost.dev" \
  allow_subdomains=true \
  ttl=168h \
  max_ttl=168h
```

Check them

```
$ vault read pki/test-backend/roles/test-role | grep ttl
max_ttl                               168h
ttl                                   168h
```

Issue certificate once again -> success (**why?**)

```
vault write pki/test-backend/issue/test-role \
    common_name="test.anyhost.dev" \
    ttl=1690h
```

Omitting ttl at all -> success (**why?**)

```
vault write pki/test-backend/issue/test-role \
    common_name="test.anyhost.dev"
```

```
Vault v1.1.2 ('0082501623c0b704b87b1fbc84c2d725994bac54')
```

Snake-oil bundle is at
https://gist.github.com/avoidik/a3f43e0d23883b6839c2ff26e9a89dc7

**Comment by avoidik** [comment]
Description for `ttl` parameter

```
The requested Time To Live for the certificate;
sets the expiration date. If not specified
the role default, backend default, or system
default TTL is used, in that order. Cannot
be larger than the role max TTL
```

**Comment by avoidik** [comment]
Not sure why NotBefore/NotAfter is quietly capped to TTLs, at least with AWS secrets it shows a warning message when "value is capped accordingly"

**Comment by jakubdyszkiewicz** [comment]
Just stumbled upon this and I was also confused.

I feel this should be an error. If not then it's probably worth to change docs from 
```
Cannot be larger than the role max TTL
```
to
```
Should not be larger than the role max TTL (value that exceeds the limit is capped to max TTL)
```
or something like this.
