### ISSUE TITLE
Hashicorp vault doesn't support 0..0 as vault name

### ISSUE THREAD

**Issue by bsrinivbh** [hashicorp/vault#6815]
**Describe the bug**
Vault name with 0..0/1..3 gives error 
URL: PUT https://10.0.0.111:8200/v1/secret/blue/services/k8s-secrets-svc/certs/bundles/1..1.3
Code: 500. Errors:

**To Reproduce**
1. Run `vault write ...`
2. Run `vault login....`
3. See error

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by bsrinivbh** [comment]
{"error":"Error making API request.\n\nURL: PUT https://10.0.0.190:8200/v1/secret/blue/services/k8s-secrets-svc/certs/bundles/0..0\nCode: 500. Errors:\n\n* 1 error occurred:\n\t* internal error\n\n","code":13}

**Comment by ncabatoff** [comment]
Hi @bsrinivbh,

I suspect that the problem may not be related to the name.  If this is a KV mountpoint (as I'm guessing based on the name "secret"), that should be a valid key name.  And a 500 return code usually indicates an internal error.  Does the same write work with a different name, e.g. secret/blue/services/k8s-secrets-svc/certs/bundles/113?

Is there anything in your logs from when this occurs?  Can you confirm this mountpoint is KV?  What does your configuration look like, in particular, what storage engine are you using?

**Comment by bsrinivbh** [comment]
Storage engine - Etcd... We are using KV(key value) mount point. 


![image](https://user-images.githubusercontent.com/50633510/59128331-fee9ab80-8926-11e9-96a3-29bcf1a893d9.png)

and I tried using   secret/blue/services/k8s-secrets-svc/certs/bundles/113 with same data it works perfectly fine as expected.

**Comment by bsrinivbh** [comment]
Same as above issue https://github.com/hashicorp/vault/issues/3162... It is existing issue... not supported by vault I guess
