### ISSUE TITLE
Database and userpass configuration not available in web UI

### ISSUE THREAD

**Issue by ghost** [hashicorp/vault#6821]
**Describe the bug**
After enabling the Database secrets engine, or userpass auth engine they are greyed out in the web UI. You have to drop back to the CLI to manage users or configure a connection for a specific database plugin.

I am sure other options are missing but these were the two most obvious issues.

**To Reproduce**
1. With the web UI enabled turn on userpass or database engines
2. Observe they are greyed out and unusable via the web

**Expected behavior**
The full configuration options should be available via the web interface similar to the CLI for users who prefer that or want to learn the product easier.

**Environment:**
* Vault Server Version (retrieve with `vault status`): newest
* Vault CLI Version (retrieve with `vault version`): newest
* Server Operating System/Architecture: not relevant

Vault server configuration file(s):

config not relevant here

**Additional context**
Can the documentation also be clarified about any other limitations of the web UI?

**Comment by daveadams** [comment]
Looks like this is a specific case of the feature request in #6067

**Comment by nesl247** [comment]
Just ran into this as well. It would also make it a lot easier if users could request their credentials from the UI rather than having to install the CLI.

**Comment by ademariag** [comment]
Also run into this. It was my main reason to install vault. Hope someone can work on this soon

**Comment by forestoden** [comment]
Any update on this?

**Comment by surfd4wg** [comment]
Having the same issue. Is there an update ? 
Vault 1.5.0

**Comment by ademariag** [comment]
> I suspect that the wider issue is the number of 'database' back-ends that are supported by default as well as the fact that each are with their own configuration-view and validation that are not common among the [listed eleven (11) on `secret/databases`](https://www.vaultproject.io/api-docs/secret/databases) not to mention [other custom database plugin](https://www.vaultproject.io/docs/secrets/databases/custom).

I think it would also be very valuable to get started to just enable fetching the credentials (which should be the same across all backends) rather than aim to configure the plugins, as I suggested in https://github.com/hashicorp/vault/issues/8013

**Comment by aphorise** [comment]
@ademariag @surfd4wg @forestoden @nesl247 the original requestor of this issue has closed their account and I'd like your inputs if you agree that this request should now be closed?

In the most recent versions of Vault (I believe 1.10.x & higher) there are options avaible for most DB's (see screenshot below).

![image](https://user-images.githubusercontent.com/974854/187546750-955378cd-c5b0-44d5-8864-fa75ce83f12f.png)

**Comment by nesl247** [comment]
@aphorise I no longer use vault as I left the company where I made the request, but based on the screenshot alone, that looks good enough to me.

**Comment by aphorise** [comment]
Hey @nesl247 appreciate the feedback. I'll proceed to close this request as I do believe the UI is already developed to the intent of this request.
