### ISSUE TITLE
Client Agent transit/datakey local processing

### ISSUE THREAD

**Issue by richard-mauri** [hashicorp/vault#6830]
**Is your feature request related to a problem? Please describe.**
This is a new feature request to vault client to perform encrypt/decrypt operations in support of transit/datakey approach to working with large BLOBS locally.

As described in https://learn.hashicorp.com/vault/developer/eaas-transit#step-6-generate-data-key , this can be used to support the problem of encrypting/decrypting large documents locally without having to send the large data payload over the network and tuning to avoid the 32MB default http request size.

Certainly, each vault customer can  roll their own local client crypto facility, but this is a common problem and vault has all the bits to do it as a standard feature.

**Describe the solution you'd like**
Something like a request to a vault client agent that would:

1. Accept for decryption: a token + data key ciphertext + encrypted data and make the server request to validate token/policy, unwrap and ultimately return to vsault agent the plain text; then perform the decryption using the same algorithm as what was used to form the transit datakey for  encryption.

2. Accept for encryption: a token + transit/datakey path + raw data and pass to server; back at agent take the plaintext data key and encrypt the raw data and return the data key ciphertext and encrypted data. The caller would be responsible for persisting the returned components.

**Describe alternatives you've considered**
Implementing this ourselves leveraging opensource primitives and supplying in our own thick client.

**Explain any additional use-cases**
We have large number of large documents to secure at rest, but this is not really unique in the enterprise space.

**Comment by aphorise** [comment]
@richard-mauri - hey I'm wondering why these large transits type operations are not already possible in recent (1.11.x) editions [with any required tuning](https://www.vaultproject.io/api-docs/secret/transit#sample-payload-4)? - can you kindly detail how relevant for you still.

**Comment by aphorise** [comment]
Closing as there's been follow-up / response.
