### ISSUE TITLE
no backed-up keys found after rekey with -backup option

### ISSUE THREAD

**Issue by SkySonR** [hashicorp/vault#6835]
**Describe the bug**
During rekey procedure with backup option I met unexpected behavior. After "vault operator rekey -target=recovery"  command I got output like:
 

> The encrypted unseal keys are backed up to "**core/unseal-keys-backup**"in the
> storage backend. 

The path core/unseal-keys-backup does not exist after that. I am using S3 backend. 
When I have used command to restore keys from backup I got:

> Error retrieving rekey stored keys: Error making API request.

> URL: GET https://127.0.0.1:8200/v1/sys/rekey/backup
> Code: 400. Errors:
> 
> * no backed-up keys found
> 

Actually the core/recovery-keys-backup path exists in S3 bucket. I suppose path inconsistencies appear.
Operation nonce: 
**To Reproduce**
1. Run `vault operator rekey -init -pgp-keys="./key1" -backup -tls-skip-verify -key-shares=1  -key-threshold=1 -target=recovery.`
2. Complete rekey process
3. Run `vault operator rekey -backup-retrieve -pgp-keys="./key1"`

**Expected behavior**
Unseal keys retrieved from backup

**Environment:**
* Vault Server Version: Docker image: vault:1.1.1
* Vault CLI Version 1.1.1
* Server Operating System/Architecture: Centos 7 / Official Docker Image

Vault server configuration file(s):

```hcl
ui = true

listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_cert_file = "/vault/certs/.crt"
  tls_key_file = "/vault/certs/.key"
}

storage "s3" {
  region = "us-gov-west-1"
  bucket     = "vault"
  kms_key_id = "alias/aws/s3"
  endpoint   = "https://s3.dualstack.us-gov-west-1.amazonaws.com"
  s3_force_path_style = "true"
}

seal "awskms" {
  region     = "us-gov-west-1"
  kms_key_id = "AAAAAAA-AAAAA-AAAA-AAAA-AAAAAAAAAA"
  endpoint   = "https://kms-fips.us-gov-west-1.amazonaws.com"
}

```

**Additional context**

**Comment by michelvocks** [comment]
Hi @SkySonR,

could you try to add the `-target=recovery` parameter to the key retrieval command? e.g.
```
vault operator rekey -backup-retrieve -pgp-keys="./key1" -target=recovery
```

This should change the API endpoint and return the correct key.

Cheers,
Michel

**Comment by SkySonR** [comment]
Hi @michelvocks 
I just tried: 

> ~ # vault operator rekey -backup-retrieve -pgp-keys="./key1" -tls-skip-verify -target=recovery
> Error retrieving rekey stored keys: Error making API request.
> 
> URL: GET https://127.0.0.1:8200/v1/sys/rekey/recovery-backup
> Code: 404. Errors:
> 
> * 1 error occurred:
> 	* unsupported path

**Comment by michelvocks** [comment]
Thanks for reporting this bug, @SkySonR.
I've opened a PR that should fix the wrong API call in the Vault CLI.

For now, you can work around this issue by "manually" calling the API:
```
curl \
    --header "X-Vault-Token: <your-vault-token>" \
    https://127.0.0.1:8200/v1/sys/rekey/recovery-key-backup
```

**Comment by SkySonR** [comment]
Thanks for work around and quick response. 
Maybe the message: "The encrypted unseal keys are backed up to "core/unseal-keys-backup" in the storage backend" should be changed to point at correct path? In my case, this is core/recovery-key-backup

**Comment by michelvocks** [comment]
@SkySonR Yes, right. I've updated my PR.

**Comment by SkySonR** [comment]
@michelvocks Thanks a lot
