### ISSUE TITLE
Vault Agent should retry renewing leases on some errors

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/vault#6837]
**Is your feature request related to a problem? Please describe.**
Vault agent gives up renewing secrets the moment it encounters a possible transient error like a network error.

For example, our application uses Google PubSub with service account keys renewal "outsourced" to Vault Agent after the application reads from the agent once during its startup.

Sometimes, I get an error like:

```
E  2019-06-05T09:17:55.111Z [ERROR] cache.leasecache: failed to renew secret: error="Put https://vault.service.consul:8200/v1/sys/leases/renew: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
 
E  2019-06-05T09:17:55.111Z [DEBUG] cache.leasecache: evicting index from cache: id=89559fe4d4f0b69ed8b11321d14869aa69c685da075bd9ae4af8040fdde61ec8 path=/v1/gcp/key/pubsub method=GET
```

The log entries after these two entries indicate that Vault is still up and running and that the timeout was a transient one.

**Describe the solution you'd like**

Vault Agent should retry renewing leases up to a certain maximum attempts with possible exponential backoffs when encountering network issues or other transient issues.

I am not sure if the Auto-Auth feature also has the same behaviour, but it would be great if this is also added for that too.

**Describe alternatives you've considered**

- Have the application restart on an authentication error and force it to get new keys

**Explain any additional use-cases**

This would allow the agent renewal behaviour to be more resilient to possible transient network issues.

**Comment by HakShak** [comment]
This makes it impossible to use periodic tokens supplied by an agent where an application is using long live connection credentials. The agent will have a network failure on the renewal and then throw away the old token in favor of a new one which orphans the long lived connection credentials that then eventually expire.

(Still trying to collect debug logs from agents in the wild)

**Comment by schmurfy** [comment]
Was there anything done to solve this ?
I just got this twice, for some reason there is a dns resolution error and instead of trying to renew the token again the agent immediately gave up and created a new secret (gcp json key in that case) invalidating the old one.

**Comment by ncabatoff** [comment]
@schmurfy: Yes I believe https://github.com/hashicorp/vault/pull/11445 solves this in 1.7.2.  This bug report appears to be a dup of https://github.com/hashicorp/vault/issues/10918.  As such I'm closing it.
