### ISSUE TITLE
Missing Lease ID

### ISSUE THREAD

**Issue by narayan8291** [hashicorp/vault#685]
I am currently using Vault version 0.3 in the dev mode. I created a secret called hello with a value world. 
=>vault write secret/hello value=world
When I try to read it using, 
=>vault read secret/hello
Output:
Key           	Value
lease_duration	2592000
value         	world

I just get the lease duration and the value but the lease id is missing. Due to this I am not able to renew or revoke the secret. I am expecting something like this https://vaultproject.io/intro/getting-started/first-secret.html

Am I missing something ?

**Comment by jefferai** [comment]
Hi,

`generic` no longer creates leases. -- see the section "Performance Improvement for Generic" at https://hashicorp.com/blog/vault-0.3.html for more information.

This should be updated in the documentation though.

**Comment by narayan8291** [comment]
@jefferai Thanks. 
So what about renewal and revocation of the secret. It has been stated that the lease-id has to be used to renew or revoke a particular secret. 

My understanding for this is that, to increase the performance of VAULT secrets can be revoked by revoking the token which has been issued to read these secrets. Am I right ? Say token A has been issued to read secrets x and y. To make sure clients they are NOT readable I need to revoke the token A.

**Comment by jefferai** [comment]
Leases on the generic backend were always noop... they were purely informational. Only token policies controlled access. As such, revoking a token is the right way to remove access for that token for secrets in the generic backend.

**Comment by narayan8291** [comment]
Sure. Thanks.

**Comment by jefferai** [comment]
Fixed in 9299ab2593c33c61ff9302e58126d7cd32e74b31.
