### ISSUE TITLE
Vault v1.1.3 Breaks Compatibility for Consul Storage Config

### ISSUE THREAD

**Issue by Xtigyro** [hashicorp/vault#6854]
**Describe the bug**
```
    storage "consul" {
      address = "unix:///consul-unix-socket/consul-client.sock"
      scheme = "http"
      disable_registration = "{{default "false" .Values.Vault.DisableConsulRegistration}}"
    }
```
Leads to:
`Error initializing storage of type consul: address should be host[:port], not URL`

That config has perfectly worked up until now (including in Vault v.1.1.2).

**Comment by mgritter** [comment]
This is a regression I introduced; I can't find a quick workaround.  Altering the address so that it passes the check I added means it won't work with other components; for example, unix:/tmp/consul-client.sock isn't parsed by the client library.

**Comment by Xtigyro** [comment]
@mgritter Thank you!!!

**Comment by Anashaikh** [comment]
same error occurs on consul:1.6.0-beta1 as well

$ kubectl logs vault-65b9f68df7-7qpjx -n vault -c vault
Error initializing storage of type consul: address should be host[:port], not URL
