### ISSUE TITLE
Documentation Request.

### ISSUE THREAD

**Issue by eedgar** [hashicorp/vault#686]
Is there a way to create a key or token of some sort that can only encrypt a file and cannot decrypt it.  I would use a different token to restore the file.

My use case is this.  I want a token on my server that can create an encrypted one way backup.  I do not want this token to be able to decrypt the file again.  In a recovery scenario I would use the recovery token which is a separate token.  I am not sure the best way to set this up.

**Comment by jefferai** [comment]
Vault doesn't have an asymmetric key capability right now. You'd do this by using symmetric keys via `transit` and restricting access to the decryption function.

**Comment by jefferai** [comment]
Alternately you could use the `pki` backend to make certificates, and use those for encryption/decryption. I'm not sure what the requirements are for doing that via, say, a command line. But certs have public keys, and when issued you get the private key, so it's asymmetric.
