### ISSUE TITLE
Go modules conflict between github.com/hashicorp/vault/api and github.com/hashicorp/vault

### ISSUE THREAD

**Issue by gitirabassi** [hashicorp/vault#6863]
I have used and greatly enjoy the `/api` and `/sdk` module releases. 

The problem comes when I have to import something else that is not in neither of those like `github.com/hashicorp/vault/builtin/credential/aws` the the infamous error "ambigous import" comes. 

This could be fixed by using the `/api` and `/sdk` module release for vault reases instead of using the "replaced" onces.

One other solution is to release all other possible dependency libraries but that would make things very messy.

I understand there are some differences between the `/api` (similar to master) that is released separatly and the one released with vault. This stuff breaks things

**Comment by jefferai** [comment]
Anything not in `api/` or `sdk/` isn't meant for public consumption. We don't support people importing and using them downstream.

**Comment by gitirabassi** [comment]
Are there any plans to add more "helpers" in the `/api`? I wish to help if that was the case. 
I don't know what you think about the idea of having types for each secret backend. 

Is it crazy to wanting a function like 
`func (c *Client) GetV2Secret(backend, version string) (map[string]interface{}, error)`
or 
`func (c *Client) GetCertificate(backend string, conf CertificateConfigInput) (Certificate, error)`?

I feel this is going to happen anyways, either in the official sdk or "yet another wrapper" and we know how those things go

**Comment by jefferai** [comment]
Long term we hope to leverage our openapi to generate clients for each plugin type.

**Comment by gitirabassi** [comment]
Is this effort already started? How far would you say are we from this?

**Comment by jefferai** [comment]
No timeline at the moment. Going to close this as it's not something we're directly going to address.
