### ISSUE TITLE
Set encoding explicitly on URLs such as https://learn.hashicorp.com/js/main.js

### ISSUE THREAD

**Issue by mcbridem** [hashicorp/vault#6869]
On pages such as <https://learn.hashicorp.com/vault/getting-started/deploy>, there is an encoding issue:

```
token_duration       â
```

The underlying Markdown file (<https://github.com/hashicorp/vault/blob/485b4d173e543aa52d93bb8df973101699d2369c/website/source/intro/getting-started/deploy.html.md>) is fine and the HTML output is fine:

```
$ curl -s "https://learn.hashicorp.com/vault/getting-started/deploy" | grep "token_duration"
token_duration       ∞
```

The issue does not appear when JavaScript has been disabled, which points to <https://learn.hashicorp.com/js/main.js>. Web browsers such as Google Chrome are selecting the `windows-1252` encoding instead of using `utf-8`. This can likely be fixed by adjusting the Web server's behavior.

```
$ curl -s -IXGET "https://learn.hashicorp.com/js/main.js" | grep "Content-Type"
Content-Type: application/javascript
```

This should be `Content-Type: application/javascript; charset=utf-8` or similar instead.

**Comment by michelvocks** [comment]
@yhyakuna If I remember correctly, this has been already fixed. Would be great to get your input here. 😄

**Comment by yhyakuna** [comment]
It shows up fine now, so I'm closing this.
![](https://education-yh.s3-us-west-2.amazonaws.com/GH/GettingStarted.png)
