### ISSUE TITLE
How the client sdk renew token lease with k8s auth?

### ISSUE THREAD

**Issue by JoeyLuffa** [hashicorp/vault#6875]
I am using the go client SDK and in order to get the token, I make request to `auth/kubernetes/login` to fetch the token. However, this token has a lease duration. Once it's expired, should the SDK manually talk to `auth/kubernetes/login` again to renew the token? If yes, wouldn't it be so much over loaded to the client side? Is there any workaround on this? (Like the SDK will auto renew the token if it's expired?)

**Comment by gitirabassi** [comment]
I asked the same question couple of months ago: it exist a `api.Renewer` type with a very clear example https://godoc.org/github.com/hashicorp/vault/api#Renewer

**Comment by jefferai** [comment]
This may also be of help: https://learn.hashicorp.com/vault/identity-access-management/vault-agent-k8s#step-4-leverage-vault-agent-auto-auth

**Comment by JoeyLuffa** [comment]
@gitirabassi Thanks! I checked the API and looks like we need to manually start this `api.Renewer` go routine to periodically refresh the client token. Are there any APIs that can do this work automatically for us? Thanks.
