### ISSUE TITLE
AWS auth login fails after switching to GovCloud STS URL. 

### ISSUE THREAD

**Issue by spstratis** [hashicorp/vault#6902]
**Describe the bug**
When changing the AWS `sts_endpoint`  to the GovCloud url `sts.us-gov-west-1.amazonaws.com` in Vault using the API calls outlined in the docs [here](https://www.vaultproject.io/api/auth/aws/index.html#configure-client). Requests to the `/v1/auth/aws/login` endpoint fail with the below error. 

```"errors":["error making upstream request: error making request: Post sts.us-gov-west-1.amazonaws.com//: unsupported protocol scheme \"\"```

Based on the error it appears as though when Vault is calling out to AWS it is using a malformed STS URL. 

The changing of the STS url to GovCloud, is based on info from [this bug](https://github.com/hashicorp/vault/issues/6631). Prior to changing the URL I was getting a similar issue as the creator of the defect `error making upstream request: received error code 403 from STS` when I was calling out to `/v1/auth/aws/login`. 

Below are the steps I followed in order to change the url. 

***request.json***
```
{    
    "sts_endpoint":"sts.us-gov-west-1.amazonaws.com", 
}
```
***config request***
```
curl --request POST --data @request.json -k --cacert admin.ca.pem --key admin.key.pem --cert admin.cert.pem --header "X-Vault-Token:<root-token>" https://foo.vault.my-domain.com:8200/v1/auth/aws/config/client
```

***Response from checking the config through the API***
```
{"request_id":"29761be6-6966-70eb-a09b-e9d1debf0d9f","lease_id":"","renewable":false,"lease_duration":0,"data":{"access_key":"","endpoint":"","iam_endpoint":"","iam_server_id_header_value":"","max_retries":-1,"sts_endpoint":"sts.us-gov-west-1.amazonaws.com"},"wrap_info":null,"warnings":null,"auth":null}
````

Is there another method for changing the configuration that I'm skipping over? The roles/policies that I've set should all be using the GovCloud `arn` which I have set to `aws-us-gov`. I've attempted changing the `iam_endpoint` and `endpoint` params in the config as well but that made no difference.  

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.1.0
* Vault CLI Version (retrieve with `vault version`): Vault v1.1.1
* Server Operating System/Architecture: Ubuntu 18.04

**Comment by cch0** [comment]
Is there a resolution available?

**Comment by lueranewera** [comment]
Not yet but yes I understand the bug that was applied by misplaced info. Due to lack of proper variables. As well as a out dated version of the GovCloud. In steps of applying coding to in order to establish a clean header for the client. To ensure STS for AWS and the j.son to patch in the path so that it may redirect to proper endpoint with a successful API. Recall and recap on "," .com
