### ISSUE TITLE
vault's high memory usage and most of it is cache

### ISSUE THREAD

**Issue by raoofm** [hashicorp/vault#6914]
```
Using eth0 for VAULT_CLUSTER_ADDR: https://100.x.x.x:8201
telemetry.disable_hostname has been set to false. Recommended setting is true for Prometheus to avoid poorly named metrics.
==> Vault server configuration:
               HA Storage: dynamodb
             Api Address: https://vault.ctnr.dev.net
                     Cgo: disabled
         Cluster Address: https://100.x.x.x:8201
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "enabled", x_forwarded_for_authorized_addrs: "[100.x.x.x/11]", x_forwarded_for_hop_skips: "0", x_forwarded_for_reject_not_authorized: "true", x_forwarded_for_reject_not_present: "false")
              Listener 2: tcp (addr: "0.0.0.0:8300", cluster address: "0.0.0.0:8301", max_request_duration: "1m30s", max_request_size: "33554432", tls: "enabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
                 Storage: s3
                 Version: Vault v1.1.2
             Version Sha: 0082501623c0b704b87b1fbc84c2d725994bac54
 ==> Vault server started! Log data will stream in below:
```

This is a 3 node cluster with request forwarding.

![image](https://user-images.githubusercontent.com/12846989/59711235-bceb2000-91d8-11e9-9b76-a9aa443955d4.png)

**Comment by raoofm** [comment]
There are a couple of clients using it so no load as such nor a lot of leases. The only unusual thing that I can see is one of the clients gets a token via kubernetes backend with a ttl of 12h and maxttl of 24h but it has a health check built in that queries /v1/auth/token/lookup-self every 3s. I noticed this as I saw audit log bombarding messages.

**Comment by raoofm** [comment]
anything that you want me to check to get more details for investigation. This high memory consumption is same in 3 environments with similar set up.

**Comment by raoofm** [comment]
same with v1.1.3

**Comment by aphorise** [comment]
No further feedback or reproduction since 1.5.2 or latest 1.6.0. I suspect that there's no issue here and this may be closed.

**Comment by raoofm** [comment]
@aphorise not a problem anymore with 1.5.4
