### ISSUE TITLE
Make Vault>Tools>Random available via API 

### ISSUE THREAD

**Issue by r3dback** [hashicorp/vault#6944]
**Is your feature request related to a problem? Please describe.**
Would like to use Vault to generate Base64 keys via a Vault API

**Describe the solution you'd like**
New module for Tools-Random, including an Ansible Modue, ie:
**hashivault_random:
   format:
   size**

returns_random_string: { }
  

**Describe alternatives you've considered**
A command line 

**Explain any additional use-cases**
in a service provider context and random string generator is quite useful

**Additional context**
n/a

**Comment by kalafut** [comment]
This is already available:  https://www.vaultproject.io/api/system/tools.html#generate-random-bytes
