### ISSUE TITLE
Make it impossible for a user to add permissions that are higher than his own to a policy

### ISSUE THREAD

**Issue by sedadas** [hashicorp/vault#6945]
**Is your feature request related to a problem? Please describe.**
Consider the following scenario:
* A shop has two Vault policies: admin and developer
* The developer policy permits only reading and writing to the secret engines
* The admin policy permits adding other engines, adding login methods and changing policies
* The admin policy denies sealing the Vault, mapping policies to entities and editing own policy (an admin user cannot edit the admin policy)
* A user has both the developer and the admin policy assigned (as a result of LDAP login and group - policy mapping, for example)
* The forementioned user can then edit the developer policy and add a rule like:
```
path "*" {
  capabilities = ["read", "update", "create", "list", "delete", "sudo"]
}
```
* As a result, the user ends up with escalated privileges that he/she should not have

**Describe the solution you'd like**
Just like when assigning groups to a policy, Vault should check whether or not the user has the permissions that he/she is trying to add to a policy.

**Describe alternatives you've considered**
I have tried using the `allowed_parameters` and `denied_parameters` constraints like so:
```
path "sys/policies/*" {
    capabilities = ["read", "update", "create", "list"]
    denied_parameters = {
        "capabilities" = ["sudo"]
    }
}
```
But since the capabilities key is nested, it didn't work. Allowing nesting or wildcards in the constraints would also fix the issue.

**Comment by bartdzkan** [comment]
There is a solution to this and it is using a different path for the policy.  Only allowing the developer to create policies under that path but not change the default one set by the Vault admin. 


```
#Create and manage ACL policies via API & UI
path "sys/policies/acl/*"
{
capabilities = [ "list"]
}
# Create and manage ACL policies for your account
path "sys/policies/acl/developer/*"
{
capabilities = [ "read", "create", "update", "list"]
}
 # Can only view and list default policy
path "sys/policies/acl/developer/default"
{
capabilities = [ "read", "list"]
}
# List policies under developer path
path "sys/policies/acl/developer"
{
capabilities = [ "list"]
}
```

`

**Comment by catsby** [comment]
Hello - we haven't heard anything for a few weeks, so I'm going to close this for now. 
If you believe the current behavior you describe is a bug, please feel free to comment on the issue and we can reevaluate. Until then, I would suggest trying the suggestion from `bartdzkan` above. 

For future questions or discussion such as this, please checkout https://discuss.hashicorp.com/c/vault

Thanks!
