### ISSUE TITLE
Unable to reset the unsealing process

### ISSUE THREAD

**Issue by frntn** [hashicorp/vault#695]
*(of course all keys and token listed below are no longer valid by the time I submit this issue)*

### What I do

```bash
# init the vault

$ vault init
Key 1: abb6eec8e4824c71f6a5810a818bca0ed56e2eb1bf7144471cff5672a776575801
Key 2: 2564fdd535a572658b2a0fd69d979c10d3910f51f1a8579c95a215c1c8668d9a02
Key 3: 46d1bdec8be1ec28dc9786275e56098285a47bd728590a9e6853435573a8460003
Key 4: a59569faa481a3afd32b3edcf4e02765fe623224abb978b56b02f8f87d60f8b504
Key 5: c62029c31ac53de28496b72d3721b2f7a85746a2724825b796f3ae6cc6ae332f05
Initial Root Token: a8175703-b409-0f15-8fb7-5ce42f5bc40e

# start unsealing the vault

$ vault unseal
Key (will be hidden): 
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 1

# reset the unsealing process

$ vault unseal -reset
```

### What I get

The option is ignored and the process continue (increment unseal progress if new share is given)

```bash
$ vault unseal -reset
Key (will be hidden): 
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 2
```

### What I expected

I expected what the help stated 
```bash
Unseal Options:

  -reset                  Reset the unsealing process by throwing away
                          prior keys in process to unseal the vault.
```

And may be an output with something like the following :
```bash
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
```

I can give you additional informations if needed

---
version: Vault v0.3.1 (binary download)
platform: linux 64bits (ubuntu 14.04.3 LTS)

**Comment by jefferai** [comment]
Hi @frntn 

Unfortunately this appears to have been an idea that never got implemented. It's a good idea though, so I'll slot it in for the 0.4 milestone.
