### ISSUE TITLE
vault operator init returns error that vault is initialized while status shows otherwise

### ISSUE THREAD

**Issue by horpek** [hashicorp/vault#6959]
I tried to start up a hashicorp vault using Azure key vault to auto-unseal.  Upon start up, I got this error 

[user12@bastion001 hvtest]$ vault server -config=/home/user12/hvtest/testvault
==> Vault server configuration:

       Azure Environment: AzurePublicCloud
          Azure Key Name: generated-key
        Azure Vault Name: testhvsealkeys
               Seal Type: azurekeyvault
                     Cgo: disabled
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
                 Storage: file
                 Version: Vault v1.1.0
             Version Sha: 36aa8c8dd1936e10ebd7a4c1d412ae0e6f7900bd

==> Vault server started! Log data will stream in below:

2019-06-24T16:59:51.660+0800 [WARN]  no `api_addr` value specified in config or in VAULT_API_ADDR; falling back to detection if possible, but this value should be manually set
2019-06-24T16:59:51.661+0800 [INFO]  core: stored unseal keys supported, attempting fetch
2019-06-24T16:59:51.661+0800 [WARN]  failed to unseal core: error="stored unseal keys are supported, but none were found"
2019-06-24T16:59:56.662+0800 [INFO]  core: stored unseal keys supported, attempting fetch
2019-06-24T16:59:56.662+0800 [WARN]  failed to unseal core: error="stored unseal keys are supported, but none were found"

I read some posts mentioned this is ok as the vault is not initialized yet and it is shown so in "vault status".  But when I issue "vault operator init", it returns "* Vault is already initialized"

[user12@bastion001 prod]$ vault status

Key                      Value
---                      -----
Recovery Seal Type       azurekeyvault
Initialized              false
Sealed                   true
Total Recovery Shares    0
Threshold                0
Unseal Progress          0/0
Unseal Nonce             n/a
Version                  n/a
HA Enabled               false
[user12@bastion001 prod]$ vault operator init
Error initializing: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/init
Code: 400. Errors:

* Vault is already initialized

Any idea what which part I did wrong?

**Comment by calvn** [comment]
Did you start off (i.e. initialize) the cluster with Azure Key Vault seal, or was it initialized with Shamir? If it's the latter and you added the [seal stanza](https://www.vaultproject.io/docs/configuration/seal/index.html) in the config afterwards, you will have to perform [seal migration](https://www.vaultproject.io/docs/concepts/seal.html#seal-migration) in order for the cluster to properly migrate and use Azure Key Vault to auto-unseal.

**Comment by horpek** [comment]
I believe I use Azure Key Vault auto-unseal directly.  This is the simple config I use:

storage "file" {
  path = "/home/user12/hvstorage"
}

ui = true
disable_mlock = true

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = 1
}

seal "azurekeyvault" {
  tenant_id      = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
  client_id      = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  client_secret  = "xxxxxxxxxxxxxxxxxxxx"
  vault_name     = "testhvsealkeys"
  key_name       = "generated-key"
}

**Comment by horpek** [comment]
We have this issue resolved.  It is an Azure Key Vault access policy permission "wrapkey" that we missed out.  As we reproduce the issue, we can see it complained that but only for the first "vault operation init" command.  

[user12@bastion001 hvstorage]$ vault status
Key                      Value
---                      -----
Recovery Seal Type       azurekeyvault
Initialized              false
Sealed                   true
Total Recovery Shares    0
Threshold                0
Unseal Progress          0/0
Unseal Nonce             n/a
Version                  n/a
HA Enabled               false
[user12@bastion001 hvstorage]$ vault operator init
Error initializing: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/init
Code: 400. Errors:

* failed to store keys: failed to encrypt keys for storage: keyvault.BaseClient#WrapKey: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"wrapKey\" is not allowed by vault policy" InnerError={"code":"ForbiddenByPolicy"}
[user12@bastion001 hvstorage]$ vault operator init
Error initializing: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/init
Code: 400. Errors:

* Vault is already initialized


If you are like me, create the Azure Key Vault from portal just to test the auto-unseal, beware that the default access policy does not have the "wrapKey" permission granted and be sure to check it.

**Comment by fazlearefin** [comment]
@horpek Thank you so much for posting the solution. I had the exact same problem and in key permissions I had to check "wrap"
