### ISSUE TITLE
Reads/Writes KO from standby instances for `secrets` 

### ISSUE THREAD

**Issue by frntn** [hashicorp/vault#698]
### Context

From my active instance : 
```bash
$ vault status
vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
        Mode: active
        Leader: https://127.0.0.1:8200
```

With *storage backend* setup :
```bash
$ cat /data/etc/vault/config.hcl 
backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
}

listener "tcp" {
  address = "127.0.0.1:8200"
  tls_cert_file = "/etc/pki/tls/certs/vault.pem"
  tls_key_file = "/etc/pki/tls/certs/vault.pem"
}
```

I can `write` to various *secret backends* like `secret` or `pki`...
```bash
$ vault write secret/readissue from=active
Success! Data written to: secret/readissue

$ vault write pki/issue/preprod common_name=kibana.preprod.example.com
Key                     Value
lease_id                pki/issue/preprod/96260503-ece0-79b4-53ca-21ee99ebea47
lease_duration          259200
lease_renewable         false
private_key             -----BEGIN RSA PRIVATE KEY-----...
private_key_type        rsa
serial_number           32:c5:10:8f:7a:f1:28:9f:21:25:d2:f6:f6:16:fa:4b:ed:3c:03:25
certificate             -----BEGIN CERTIFICATE-----...
issuing_ca              -----BEGIN CERTIFICATE-----...
```

...and I can `read` from these same *secret backends*
```bash
$ vault read secret/readissue
Key             Value
lease_duration  2592000
from            active

$ vault read pki/cert/32:c5:10:8f:7a:f1:28:9f:21:25:d2:f6:f6:16:fa:4b:ed:3c:03:25
Key             Value
certificate     -----BEGIN CERTIFICATE-----...

# read ouputs truncated for readability
```

### What I do

Now, from any of my standby instances
```bash
$ vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
        Mode: standby
        Leader: https://127.0.0.1:8200
```

With same *storage backend* setup
```bash
$ cat /data/etc/vault/config.hcl 
backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
}

listener "tcp" {
  address = "127.0.0.1:8200"
  tls_cert_file = "/etc/pki/tls/certs/vault.pem"
  tls_key_file = "/etc/pki/tls/certs/vault.pem"
}
```

I try to `read`/`write` from these standby instances.....

### What I get

It *seems that* I can `write` to various *secret backends* like `secret` or `pki` but with some differences :
```bash
$ vault write secret/readissue from=standby
Success! Data written to: secret/readissue
# ^ Same output compared to 'active' instance...

$ vault write pki/issue/preprod common_name=grafana.preprod.example.com
Success! Data written to: pki/issue/preprod
# ^ NOT the same output compared to 'active' instance...
```

And I cannot read any data from these secrets :
```bash
$ vault read secret/readissue
Error reading secret/readissue: http: read on closed response body

$ vault read pki/cert/74:40:a1:ac:ee:d7:6a:32:ec:84:b7:5b:84:0c:9d:36:d9:ef:6c:ca                                                                             
Error reading pki/cert/74:40:a1:ac:ee:d7:6a:32:ec:84:b7:5b:84:0c:9d:36:d9:ef:6c:ca: http: read on closed response body
```

Digging a bit further, it turns out that **write request are not processed at all** : 
```bash
# SET value from ACTIVE
$ vault write secret/readissue from=active
Success! Data written to: secret/readissue

# GET value from ACTIVE
$ vault read secret/readissue
Key             Value
lease_duration  2592000
from            active

# SET value from STANDBY
$ vault write secret/readissue from=standby      # <-- try to update the value
Success! Data written to: secret/readissue       # <-- seems it has been processed...

# GET value from ACTIVE
$ vault read secret/readissue
Key             Value
lease_duration  2592000
from            active                           # <-- ...but not !

```

### What I expected

I was expecting for the standby vaults to behave *like* an active vault (even if requests are actually forwarded under the hood).

---
versions: Vault v0.3.1 + Consul v0.5.2
platform: linux 64bits (ubuntu 14.04.3 LTS)

**Comment by jefferai** [comment]
Hi @frntn ,

Sorry to hear you're having trouble. I think what's happening is that the localhost addresses in use across the servers are causing the redirects to fail. When in HA mode, information about the leader is stored in a known location in the physical backend. When a redirect needs to happen, this address is sent to the client. In this case, the client would connect to 127.0.0.1:8200, then be told to redirect to 127.0.0.1:8200.

Try setting https://vaultproject.io/docs/config/index.html#advertise_addr -- this should be a value that is accessible by clients as a target for redirection. For instance, if Server A and Server B have 1.2.3.4 and 5.6.7.8 as their addresses respectively, they should each use that public address, plus port (rather than 127.0.0.1) as the value of `advertise_addr`. Note that this can also be an `http`/`https` string.

If you are running behind a load balancer that is configured to always point to the active instance, you can use this address as the `advertise_addr` across all of your nodes.

Let me know if that helps -- if not, can you post some more details about your setup -- the distinct machines you have, the consul configuration for each, and so on?

Thanks,
Jeff

**Comment by frntn** [comment]
Thanks @jefferai it works ! :)

For the record (if other have similar issue setting up the HA) :
* I first tried to only add `backend->advertise_addr` with x.x.x.x value in the backend config, but it won't work because the vault was still binded to 127.0.0.1
* Then I binded both `backend->advertise_addr` and `listener->address` to the x.x.x.x ip address of each the server, but now I have to specify the `VAULT_ADDR` (not blocking) and got an error message `x509: certificate is valid for 127.0.0.1, not x.x.x.x` (blocking)
* Finally I ended up advertising on the x.x.x.x ip address on the backend (ip accessible from other vault instances), binding on 0.0.0.0 (so I don't have to setup the `VAULT_ADDR`), and regenerate the certificate with IP SAN on 127.0.0.1 and x.x.x.x

**Comment by jefferai** [comment]
Glad it's fixed!

**Comment by frntn** [comment]
@jefferai I think the issue should be reopen because I got "success" while the write requests are not processed at all, while it should raised an error.

**Comment by jefferai** [comment]
@frntn Can you give me more details? Earlier you said it was working -- did it stop working? Is it a different path that isn't working?

Can you post some more details about your setup -- the distinct machines you have, the consul configuration for each, and so on?

**Comment by frntn** [comment]
No it is working great now ! Thank you
My point is when it wasn't I didn't get relevant error messages. Indeed, I used to got success messages.
