### ISSUE TITLE
Vault agent should have a "namespace" option in the "vault" stanza

### ISSUE THREAD

**Issue by mbeiter** [hashicorp/vault#6981]
Vault `agent` allows specifying the address of the target server in the `vault` stanza like so:

```
vault {
   address = "https://my.vault.instance.com:12345"
}
```
Until introduction of this option, the address was specified e.g. through the `VAULT_ADDR` [environment variable](https://github.com/hashicorp/vault/issues/6439).

**Describe the solution you'd like**

It would be helpful if the target namespace could be specified in the vault stanza of the config file, like so:

```
vault {
   address = "https://my.vault.instance.com:12345"
   namespace = "my-namespace" 
}
```

This would make the config file the single source of truth for `vault agent`.

The suggested pattern also aligns with Consul Template, where this config option is [already available](https://github.com/hashicorp/consul-template#configuration-file-format).

**Describe alternatives you've considered**

It is currently possible to specify the target namespace via the `VAULT_NAMESPACE` environment variable. 

However, this fragment the `vault agent` configuration, and no longer retains the config file as the single source of truth for the behavior of `vault agent`.

**Comment by michelvocks** [comment]
Hi @mbeiter,

we discussed this feature request (see #6988 for further information) and decided to not implement this feature for now due to the fact that the Vault Agent and its use-case is different from Consul Template. 

Could you please elaborate a bit more on your specific use-case?
In my opinion, supporting the `VAULT_NAMESPACE` environment variable is wrong for the Vault Agent and should not be supported at all. CC @calvn

**Comment by mbeiter** [comment]
I read the thread on the PR, and I do not think the argument is sound: If we argue along these lines, then including the `address` parameter in the stanza should have been declined with the same reasoning.

I will comment in the PR-thread with more details.

**Comment by jacobm3** [comment]
> @michelvocks I read the thread on the PR, and I do not think the argument is sound: If we argue along these lines, then including the `address` parameter in the stanza should have been declined with the same reasoning.
> 
> I will comment in the PR-thread with more details with respect to use case and why it should be supported.
> 
> This is shocking:
> 
> > In my opinion, supporting the VAULT_NAMESPACE environment variable is wrong for the Vault Agent and should not be supported at all. CC @calvn
> 

@mbeiter Your logic seems sound to me. I don't understand why we would support 'address' but not 'namespace'. Splitting the Vault agent configuration this way forces enterprise users to provide essential agent configuration in 2 separate places. That's unclean for configuring and creates an extra step for admins to understand what Vault Agent is doing when they inherit installations setup by someone else. I plan to set VAULT_ADDR and VAULT_NAMESPACE outside the config and avoid the 'address' config parameter altogether.

**Comment by mikegreen** [comment]
For those finding this later, https://www.vaultproject.io/docs/agent/autoauth#namespace is implemented for auto-auth
