### ISSUE TITLE
Vautl CLI write command Deletes Existing Policy When adding New Policy

### ISSUE THREAD

**Issue by YoussefKaib** [hashicorp/vault#6986]
**Is your feature request related to a problem? Please describe.**
When adding new policy `vault write` command deletes existing policies associated with LDAP group 
`vault write vault write auth/ldap/groups/foo-bar-ldap policies=new-foo-bar-policy` 
**Describe the solution you'd like**
I suggest `vault update auth/ldap/groups/foo-bar-ldap policies=new-foo-bar-policy` & API `PUT` request where you can add new policy without overwriting existing policies

**Describe alternatives you've considered**
N/A
_workaround_:
- list all policies associated with `foo-bar-ldap` every time and them write them again when adding another policy
`write vault write auth/ldap/groups/foo-bar-ldap policies=old-foo-bar-policy policies=another-old-foo-bar-policy policies=new-foo-bar-policy`

**Comment by jefferai** [comment]
I'm going to close this as it's not a specific issue to LDAP and the overall problem is already in other issues. For a v2 API, whenever that might come, we are thinking about whether we can enable more patch-like behaviors for places like this where it's harder to keep track of a list. The best approach for now though is to codify the desired configuration such that you can simply make a change to the data being used for the API commands and run a script or other tool to execute the commands.
