### ISSUE TITLE
Add support for AWS KMS (backend storage)

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vault#70]
http://docs.aws.amazon.com/kms/latest/APIReference/Welcome.html

https://vaultproject.io/docs/config/index.html#backend

**Comment by armon** [comment]
@radeksimko I don't actually think this is possible. KMS does not support storage of data, only of encryption keys. We could pair KMS with something else, but on it's own its not a suitable backend.

**Comment by sethvargo** [comment]
You may also be interested in the guide we just published: https://www.vaultproject.io/intro/vs/kms.html

**Comment by radeksimko** [comment]
@armon You're probably right, I admit I was just skimming through the KMS docs and did not realise this.

**Comment by armon** [comment]
Closing this based on discussion.

**Comment by ledjon** [comment]
I know this is a closed ticket, but still a valid conversation.  You say we could use KMS to store keys -- is there any way to get this on the roadmap? What would this actually look like? How would this work in with another backend to make a complete cloud-based HSM solution? The huge upside of KMS is that it does use hardware based key management.

**Comment by jefferai** [comment]
@ledjon It's unclear what you're asking here. What keys are you wanting Vault to store in KMS?

**Comment by ledjon** [comment]
Well, I'm not a vault user (yet) so forgive me of I misunderstand the workflow and/or terms.

But data in vault is encrypted with some sort of key at some point in time, and that key has to be stored somewhere.  Amazon KMS seems like the perfect place to "manage that key"

Perhaps this is even the root key or something like that -- again I'm not 100% sure on the vault terms.

Basically I work for a health care organization, and I want us to be able to say that we use HSM (via KMS) to do our key management and rotating in the even of an audit.  I fear that vault by itself wont get an instant-pass by auditors.

**Comment by jefferai** [comment]
The problem with storing the actual key in KMS is that the key then leaves Vault. Part of Vault's security model is that its key is never exported. The encrypted key could be exported, however.

HSM support is on our radar, although I'm not currently sure if that includes HSM-as-a-service offerings like KMS.

**Comment by ledjon** [comment]
Sounds good.  Thanks.

**Comment by st33v** [comment]
Hey Ledjon... would it satisfy your PCI requirements if the unseal keys were stored in KMS? That way, the encrypt key stays in vault but you'd still be managing key 0 with the HSM. I'm not a PCI expert but I've been thinking about how you'd autoscale something like vault in AWS and HSMs were discussed. It would be great if that also made it PCI-compliant.

**Comment by jefferai** [comment]
@st33v Reading your comment, I realize that I didn't actually make that explicit in my earlier comment. Storing the actual *unencrypted* master key in KMS is a problem for the reasons mentioned; but you are of course perfectly free to store the unseal keys wherever you like -- including an HSM-backed KMS store, printed out and put in a "real" bank vault, etc. :-)

@ledjon Sorry I didn't mention that explicitly before. Props to @st33v!
