### ISSUE TITLE
Azure client_secret is missing from keys

### ISSUE THREAD

**Issue by Ivasan7** [hashicorp/vault#7002]
**Describe the bug**
I am using the Azure Secrets Engine, just following the basic example provided on the website, however after writing the configuration (and getting successful feedback) the client_secret field is not available: 

```
vault read -field=client_secret azure/config 
Field "client_secret" not present in secret
```

**To Reproduce**
1. Run `vault secrets enable azure`
2. Run `vault write azure/config subscription_id=$AZURE_SUBSCRIPTION_ID tenant_id=$AZURE_TENANT_ID client_id=$AZURE_CLIENT_ID client_secret=$AZURE_CLIENT_SECRET`
3. `vault read -field=client_secret azure/config`
4. Error Field "client_secret" not present in secret

**Expected behavior**
I think the client_secret should be able to be retrieved.

**Environment:**
* Vault Server Version (retrieve with `vault status`):1.1.3
* Vault CLI Version (retrieve with `vault version`):1.1.3
* Server Operating System/Architecture: Ubuntu 18:04 x86_64

Vault server configuration file(s):

```hcl
storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault/"
}

listener "tcp" {
 address     = "127.0.0.1:8200"
 tls_disable = 1
}
```

**Additional context**

**Comment by kalafut** [comment]
Hi. This is expected behavior. Sensitive configuration information such as the root user password or access key is typically not returned as part of a read request.

**Comment by Ivasan7** [comment]
@kalafut ok! Understandable, but then how can I retrieve it or use it? 
My use case is that I want to deploy my application, and to do so I need to have a client_secret. I want to retrieve it from the vault and not hard code it. For now I have defined my own engine, there it allows me to store all the 4 together.

**Comment by kalafut** [comment]
Hi. This is a dynamic secrets engine, and the client_id/secret set here in the configuration is a root account that Vault will use to create/revoke _other_ Azure accounts (e.g. https://www.vaultproject.io/docs/secrets/azure/index.html#usage). There is a larger example of [dynamic secrets](https://learn.hashicorp.com/vault/getting-started/dynamic-secrets) that's for AWS, but the concepts are the same.

If you're just trying to store and retrieve data, not dynamically create accounts, you probably want to use the KV engine:  https://www.vaultproject.io/docs/secrets/kv/kv-v2.html

**Comment by Ivasan7** [comment]
Ok! Clear , I am fairly new to Vault so this was not clear to me. Thanks for the prompt reply
