### ISSUE TITLE
Add support of TLS configuration in Consul Secrets Engine Configure Access API (/consul/config/access)

### ISSUE THREAD

**Issue by vasilij-icabbi** [hashicorp/vault#7004]
https://www.vaultproject.io/api/secret/consul/index.html#configure-access

Currently there is no way to add TLS when configure access for Consul Secrets Engine to create tokens. Also official documentation does not provide any alternatives.

The issue was pointed long time ago but never got labeled as feature request here: https://github.com/hashicorp/vault/issues/944

**Comment by michelvocks** [comment]
Since we are about to re-label all existing issues I will close this in favor of #944
