### ISSUE TITLE
`vault policy fmt` appends a redundant blank line at the end

### ISSUE THREAD

**Issue by nikolay** [hashicorp/vault#7009]
It causes issues as Terraform Vault provider always sees a policy change. It happens for blank policy files at least.

**Comment by tyrannosaurus-becks** [comment]
To me, it looks like, `vault policy fmt` is functioning the way we'd like. Here are a few series of commands.
```
$ cat test-pol.txt 
path "secret/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
path "secret/super-secret" {
  capabilities = ["deny"]
}
path "secret/restricted" {
  capabilities = ["create"]

  allowed_parameters = {
    "foo" = []
    "bar" = ["zip", "zap"]
  }}
$ vault policy fmt test-pol.txt 
Success! Formatted policy: test-pol.txt
$ cat test-pol.txt 
path "secret/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "secret/super-secret" {
  capabilities = ["deny"]
}

path "secret/restricted" {
  capabilities = ["create"]

  allowed_parameters = {
    "foo" = []
    "bar" = ["zip", "zap"]
  }
}
```
Above, the last line was made pretty like we'd want.
```
$ cat test-pol.txt 
path "secret/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "secret/super-secret" {
  capabilities = ["deny"]
}

path "secret/restricted" {
  capabilities = ["create"]

  allowed_parameters = {
    "foo" = []
    "bar" = ["zip", "zap"]
  }
}






$ vault policy fmt test-pol.txt 
Success! Formatted policy: test-pol.txt
$ cat test-pol.txt 
path "secret/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "secret/super-secret" {
  capabilities = ["deny"]
}

path "secret/restricted" {
  capabilities = ["create"]

  allowed_parameters = {
    "foo" = []
    "bar" = ["zip", "zap"]
  }
}
```
Above, spare newlines were removed.

```
$ cat test-pol.txt 
$ vault policy fmt test-pol.txt 
Success! Formatted policy: test-pol.txt
$ cat test-pol.txt 

```
In the last example, a newline was added, but whatever it does or doesn't do, when a file is empty, running format isn't going to result in a well-formatted policy. It'll just be empty and still not usable. I actually think it would be _more_ correct if, when a policy can't be formatted into a valid one, the process exits unsuccessfully. That might be the way we go with it in the future.

I think this issue needs to be addressed in the Terraform Vault Provider, perhaps by suppressing the diff when the file is empty. If you decide to open it there, it would be great to hear your use case for empty policy files as well. 

Thanks!

**Comment by jefferai** [comment]
> It'll just be empty and still not usable. I actually think it would be more correct if, when a policy can't be formatted into a valid one, the process exits unsuccessfully.

Except for the blank case -- because that's actually a totally valid policy that happens to contain no path statements. :-)
