### ISSUE TITLE
Proper Linux OS packages (RPM, DEB, etc)

### ISSUE THREAD

**Issue by evitalis** [hashicorp/vault#7021]
**Is your feature request related to a problem? Please describe.**
Managing Vault versions is cumbersome for environments that require signed packages for installed applications.

**Describe the solution you'd like**
Hashicorp team to provide Linux OS packages alongside the standalone binaries for easier management. It would be helpful also to include a small sample or default configuration so the service can be started right after installation for testing.

**Describe alternatives you've considered**
I attempted to make an RPM for Vault myself but I am not really clear on how to package Go applications.

**Explain any additional use-cases**
Normal end users will be able to get up and running much quicker as well using a package that includes a small default or example configuration file. This will help foster adoption, and save frustration while users wait on documentation to be updated.

**Additional context**
n/a

**Comment by Jamesits** [comment]
As a quick and dirty workaround, [fpm](https://fpm.readthedocs.io/en/latest/) can be used to generate various type of packages. 

Quickstart:

Generate a directory structure like this:
```
usr
└── bin
    └── vault
```

Then run `fpm -s dir -t rpm -n vault -v 1.1.3 ./usr` and you are ready to go.

**Comment by astorath** [comment]
@Jamesits, can fpm register systemd unit?

**Comment by Jamesits** [comment]
AFAIK the master branch of fpm only supports auto-register system scripts for debs, but not rpms. You can either just install the `.service` file only and `systemctl enable --now` it manually, or just add a post-install script to do this for you. 

There is a [pull request for rpm systemd unit auto registration](https://github.com/jordansissel/fpm/pull/1405) but it is somehow not merged. I'm not familiar with the rpm world so I'd rather not comment on it. 

One example of installing systemd units: https://github.com/Jamesits/pve-fake-subscription/blob/master/package.sh#L15 (`--deb-systemd` switch only causes the unit to be started/enabled upon installation; anyway the file will be installed.)

**Comment by evitalis** [comment]
fpm is a workaround yes but it would be nice to see official packages with proper example configurations and documentation like other packages. Just the binary isn't enough from an ops perspective.

**Comment by evan-chaney** [comment]
I opened #7638 for RPM builds with a systemd file.

**Comment by evitalis** [comment]
Looks like the associated PR was closed without clear reason. @chrishoffman can you share some more info on this issue please?

**Comment by ndobbs** [comment]
This issue can most likely be closed: https://www.hashicorp.com/blog/announcing-the-hashicorp-linux-repository

**Comment by ncabatoff** [comment]
Agreed, thanks for pointing that out @ndobbs .
