### ISSUE TITLE
Implement systemd notification

### ISSUE THREAD

**Issue by astorath** [hashicorp/vault#7028]
**Is your feature request related to a problem? Please describe.**
Using vault binary as a systemd unit have some control problem:
- vault does not have daemon mode
- vault does not support systemd notification system

So when service starts unsuccessfully (due to config error for instance), systemctl can't report the problem right away and systemd keeps restarting failing unit forever.

**Describe the solution you'd like**
I think the best solution is to implement systemd notification when vault (or vault agent) is ready to accept requests.

Example from consul: [agent.go](https://github.com/hashicorp/consul/blob/33a7df333018c79087f1be092297402a312c571d/agent/agent.go#L1763)

**Describe alternatives you've considered**
I've implemented a simple bash wrapper to check for active port after vault startup. This is a dirty solution:
- it makes startup take longer
- checking port availability is not the same as checking service is ready
- requires some unnecessary intermediate script

**Explain any additional use-cases**
You can implement [WATCHDOG](https://www.freedesktop.org/software/systemd/man/sd_notify.html#WATCHDOG=1) notification to make systemd monitor unit health.

**Additional context**
I see that `github.com/coreos/go-systemd` module is in https://github.com/hashicorp/vault/blob/ceb4aeadcb793a2355208feb5fce6fd06aa92dbe/vendor/modules.txt#L185 and https://github.com/hashicorp/vault/blob/0a58f3077b455dc7eb71fecc6a999c4959b61a4f/go.sum#L104, maybe there were some attempts to implement it already?

**Comment by aphorise** [comment]
Should be implemented in above PR (make a note for my own reference).

**Comment by sgmiller** [comment]
Implemented using a cleaner dep, and also notifying on shutdown/config reload: https://github.com/hashicorp/vault/pull/11517

**Comment by aphorise** [comment]
@astorath can you confirm if the merged changes already accommodate for what you were after within the latest 1.7.x or higher releases?

**Comment by ncabatoff** [comment]
This was fixed in #11517 and should've been closed then.  Closing.
