### ISSUE TITLE
AWS CLI Configure using Vault Dynamic Credentials

### ISSUE THREAD

**Issue by MichaelSmyth0184** [hashicorp/vault#7033]
Hi,
I am new to using Vault and wondering how I actually can deploy to my AWS Account programmatically using Dynamic Secret credentials stored in my vault backend.

I can retrieve the whole secret contents by doing a Curl.

`curl --header "X-Vault-Token: ..."        --request GET        http://$VAULT_ADDR:8200/v1/main/creds/admin-role | jq`

Problem is how do I automate the use of these credentials to deploy to my AWS account using the Curl command above? I was thinking of writing the output to a text file and exporting Access and Secret key as environment variables and setting them via aws configure. 

`aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY`

 Any help would be greatly appreciated, must be an easier way to do this?

**Comment by cuspofaries** [comment]
Hi,

did you find a solution for this ?

**Comment by hsimon-hashicorp** [comment]
Due to the issue age and quiescence, I'm going to go ahead and close it now. Please feel free to re-open as needed, or visit our [Discuss forums](https://discuss.hashicorp.com/c/vault/30) for community support.
