### ISSUE TITLE
Vault does not allow hyphen-prefix/suffix for keys

### ISSUE THREAD

**Issue by dekelund** [hashicorp/vault#7040]
**Describe the bug**
Vault does not allow dash/hyphen as first and/or last character in key.

According to documentation it allows a string:

https://www.vaultproject.io/api/secret/transit/index.html

**To Reproduce**
Steps to reproduce the behaviour:

1. Start up vault
2. Post a request to 127.0.0.1:8200/v1/transit/keys/123
3. Verify that you receive "204 No content"
4. Post a request to 127.0.0.1:8200/v1/transit/keys/123-
5. Now you receives "404 Not Found" with following body

```json
{
    "errors": [
        "1 error occurred:\n\t* unsupported path\n\n"
    ]
}
``` 

This indicates that dash in the end of the key fails.
It's also possible to reproduce the exact same problem with dash in the beginning of the key.

**Expected behaviour**
Vault should return "204 No content" when providing a dash in the end of the key.

**Environment:**
* Vault Server Version: Vault v1.2.0-beta1
* Vault CLI Version: N/A
* Server Operating System/Architecture: Mac OS X/amd64

Vault server configuration file(s):

```hcl
# using default values, running as go run main.go server -dev
```

**Related code**
In `builtin/logical/transit/path_keys.go` following function `pathKeys` make use of framework.GenericNameRegex as pattern for the Path. That function will return a regular expression requiring a word in the beginning and end of the string.

Look at GenericNameRegex in `sdk/framework/path.go` which contains following regular expression: `"(?P<%s>\\w(([\\w-.]+)?\\w)?)"`.

**Comment by jefferai** [comment]
Not a bug; we don't allow it..

**Comment by dekelund** [comment]
@jefferai ok thanks for the rapid feedback. IMHO then it's undocumented, it would be nice to know the pattern without opening the source code. Once more thanks for the feedback.

**Comment by zishanj** [comment]
It also does not accept email address due to @ symbol. `TOTP` keys does accept @ symbol also. Any possibility or config option to allow @ symbol in `Transit` also?

**Comment by akashpearsystem** [comment]
URL: PUT http://9.128.134.150:8200/v1/vault/secrets/aws-vault-admin
 Code: 404. Errors:
  * no handler for route 'vault/secrets/aws-vault-admin'










How to handle this error in vault using terraform??
