### ISSUE TITLE
API call "read entities by name" failes for entities with spaces

### ISSUE THREAD

**Issue by JanoschDeurer** [hashicorp/vault#7054]
**Describe the bug**
When using the [read entities by name](https://www.vaultproject.io/api/secret/identity/entity.html#read-entity-by-name) api call for an entity that has as space in the name I get a 404 with he following payload
`{"errors":["1 error occurred:\\n\\t* unsupported path\\n\\n"]}\n`

**To Reproduce**
1. Create a vault user with a space in the name
2. Run `curl \
    --header "X-Vault-Token: ..." \
    http://127.0.0.1:8200/v1/identity/entity/name/testentity%20name`

**Expected behavior**
API call should return the entity

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.1.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.1.2 ('0082501623c0b704b87b1fbc84c2d725994bac54')

* Server Operating System/Architecture: Docker on Linux

**Comment by jefferai** [comment]
Fixed, thanks!

**Comment by JanoschDeurer** [comment]
Wow that was fast, thank you! :)
