### ISSUE TITLE
Config file merging issue

### ISSUE THREAD

**Issue by justintime** [hashicorp/vault#706]
I've come across what I think is a bug in config file merging in vault.

My use case is that I'm using a chef community cookbook, and it manages /etc/vault.hcl for me.  Rather than try to push changes upstream, I figured I could just create a /etc/vault.hcl.d directory, and stick my config changes in there.

According to help, it sounds like I can do this:
```
 -config=<path>      Path to the configuration file or directory. This can be
                      specified multiple times. If it is a directory, all
                      files with a ".hcl" or ".json" suffix will be loaded.
```

Here's my server command line:
```/usr/local/bin/vault server -config=/etc/vault.hcl -config=/etc/vault.hcl.d -log-level=info```

And here's what I have in the .d directory:
```
[root@vault1 log#] cat /etc/vault.hcl.d/cache.hcl
disable_cache = true
```

However, the read cache is not getting disabled when I start vault.  If I move the disable_cache statement to /etc/vault.hcl and restart, I get the desired behavior.

Am I doing something wrong?  Thanks!

**Comment by jefferai** [comment]
I don't think you are, no. I'll dig into this.

**Comment by jefferai** [comment]
@justintime Is there any chance you can share your configs? I can't replicate this.

I have the following config.hcl:
```
backend "file" {
  path = "/home/jeff/706-test/filetest"
}

disable_mlock = true

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}
```
and a `config` directory with one file:
```
disable_cache=true
```
I put in a panic and print statements to print out the seen paths and the final config, here's what I see:
```
config paths:
[]string{"config.hcl", "config"}
config:
server.Config{Listeners:[]*server.Listener{*server.Listener{Type:"tcp", Config:map[string]string{"address":"0.0.0.0:8200", "tls_disable":"1"}}}, Backend:*server.Backend{Type:"file", AdvertiseAddr:"", Config:map[string]string{"path":"/home/jeff/706-test/filetest"}}, DisableCache:true, DisableMlock:true, Telemetry:<nil>, MaxLeaseTTL:0, MaxLeaseTTLRaw:"", DefaultLeaseTTL:0, DefaultLeaseTTLRaw:""}
```
You can see `DisableCache:true` in the output. Unfortunately, without being able to replicate it I'm not sure what's wrong -- I took a look at the code and the merging logic for DisableCache looks fine.

**Comment by justintime** [comment]
*Sigh* I found my problem.  Closing this and reopening the other issue.

**Comment by jefferai** [comment]
Reopening the other? Wuh oh. What's going wrong?
