### ISSUE TITLE
Catch performKeyUpgrades context canceled errors 

### ISSUE THREAD

**Issue by briankassouf** [hashicorp/vault#7065]
Standbys that fail to perform key upgrades shut themselves down, this is because they no longer have the latest keyring or master key and would be unable to perform certain decryptions. However if `performKeyUpgrades` fails due to a context canceled error we should not shutdown since this likely just means we are changing state.

**Comment by jefferai** [comment]
Adding to beta as it's a functional change so would be good to get out in case it causes issues for anyone testing.
