### ISSUE TITLE
unable to go get vault api in module mode

### ISSUE THREAD

**Issue by jaloren** [hashicorp/vault#7073]
**Describe the bug**
I want to use the vault api in a go program that I am writing. I am using go modules. When I attempt to use go get in module it fails with two exceptions.

The first is with autorest:

```
build github.com/hashicorp/vault: cannot load github.com/Azure/go-autorest/autorest: ambiguous import: found github.com/Azure/go-autorest/autorest in multiple modules:
	github.com/Azure/go-auto
```
This can be fixed by updating go.mod in vault repo to v12.2.0. I manually go get with  github.com/Azure/go-autorest@v12.2.0 and I got the past that  error. 

However, the next error i am not sure how to get past. I suspect the issue has to do with doing multiple go modules in the same repo where depending on what git revision a go.mod may exist for the parent module but not the sub module. Though that's just a guess.

```
jlorenzini@jlorenzini-mb operator$ go get github.com/hashicorp/vault@v1.1.3
build github.com/hashicorp/vault: cannot load github.com/hashicorp/vault/api: ambiguous import: found github.com/hashicorp/vault/api in multiple modules:
	github.com/hashicorp/vault v1.1.3 (/Volumes/Repositories/go/pkg/mod/github.com/hashicorp/vault@v1.1.3/api)
	github.com/hashicorp/vault/api v1.0.2 (/Volumes/Repositories/go/pkg/mod/github.com/hashicorp/vault/api@v1.0.2
```

**To Reproduce**
1. cd into an empty directory
2. execute `go mod init example.com`
3. execute `go get github.com/hashicorp/vault@v1.1.3`

**Expected behavior**
go get successfully retrieves the vault go module 

**Additional Context**

Issue also reproduces if i go get the api module by itself:

```
jlorenzini@jlorenzini-mb operator$ go get github.com/hashicorp/vault/api
package github.com/hashicorp/vault/api: unknown import path "github.com/hashicorp/vault/api": ambiguous import: found github.com/hashicorp/vault/api in multiple modules:
	github.com/hashicorp/vault v1.0.0 (/Volumes/Repositories/go/pkg/mod/github.com/hashicorp/vault@v1.0.0/api)
	github.com/hashicorp/vault/api v1.0.2 (/Volumes/Repositories/go/pkg/mod/github.com/hashicorp/vault/api@v1.0.2)

```

**Comment by ncabatoff** [comment]
Hi @jaloren,

You should be using the modules `sdk` and `api` instead of the Vault repo, e.g.

```
go get github.com/hashicorp/vault/api
go get github.com/hashicorp/vault/sdk
```

**Comment by jaloren** [comment]
@ncabatoff  issues reproduces if i do api directly.

```
jlorenzini@jlorenzini-mb operator$ go get github.com/hashicorp/vault/api
package github.com/hashicorp/vault/api: unknown import path "github.com/hashicorp/vault/api": ambiguous import: found github.com/hashicorp/vault/api in multiple modules:
	github.com/hashicorp/vault v1.0.0 (/Volumes/Repositories/go/pkg/mod/github.com/hashicorp/vault@v1.0.0/api)
	github.com/hashicorp/vault/api v1.0.2 (/Volumes/Repositories/go/pkg/mod/github.com/hashicorp/vault/api@v1.0.2)
```

**Comment by ncabatoff** [comment]
Can you try starting fresh, from an empty `go.mod`?  I suspect that error derives from your earlier go get of vault without suffix.

**Comment by jaloren** [comment]
@ncabatoff yep that did the trick. That's a pretty big foot gun with non-obvious fix. It might be helpful to document that somewhere prominent.

**Comment by chrishoffman** [comment]
I think `go mod tidy` would have also done the trick.

**Comment by jaloren** [comment]
@chrishoffman  I think the problem was is that we have a much older package that relies on v0.9.0 of vault. I incorrectly assumes pre 1.0 would be treated as a different module then 1.0 post but in  fact 0.9.0 and 1.X are treated the same. So i deleted the legacy package and go mod tidy and then everything was happy.
