### ISSUE TITLE
Templates and paths for e.g. kv engines

### ISSUE THREAD

**Issue by Bitsky** [hashicorp/vault#7078]
**Is your feature request related to a problem? Please describe.**
We would like to use Vault for managing various passwords. Most employees are not too tech-savvy, so we would like to keep the UI interaction simple. Currently it would be like this:
1. access UI, access kv engine named e.g. "Passwords"
2. click "Create Secret" and enter path e.g. "Banking/Paypal"
3. add three keys (Username, Password, URL) and fill in the values
4. save

**Describe the solution you'd like**
1. to make adding secrets simpler, it would be great to be able to pre-create a path hierarchy (Passwords/Banking/, /Passwords/Shops/, /Passwords/Accounting, ...). Currently that seems impossible because Vault-UI says "The secret path may not end in /".
2. creating required keys manually is error-prone, so being able to enforce templates per path would be nice; e.g.: every secret in "Passwords" always has the keys "Username", "Password", "URL" automatically.

**Describe alternatives you've considered**
1. Dummy-secrets (Passwords/Banking/dummy) to build the hierarchy. But that seems confusing.
2. Building an extra UI that acts as some sort of proxy. But that would be lots of work.

**Comment by aphorise** [comment]
Hey @Bitsky is this still relevant for you?

Also what about have each prefix / path hierarchy as a separate mount in itself? - this would then allow for managing per mount easier as well and cleaner in terms of deleting than trying to structure or recall deep or nested paths where everything may be together.

**Comment by Monkeychip** [comment]
I'm going to go ahead and close this ticket due to lack of response. Please comment if you'd like it reopened.
