### ISSUE TITLE
vault 1.1.1 has no secret/ path enabled

### ISSUE THREAD

**Issue by shashankimanage** [hashicorp/vault#7081]
**Describe the bug**
I am using vault 1.1.1 in server mode and when I do "vault secret list"
I don't see the secret path enabled by default.

when I run the same version on dev mode I can see the secret path.

**To Reproduce**
1. Run `vault server -dev &`
and run "vault secrets list" 
2. Run `vault server -dev -config=/vault/config/config.hcl`
and run "vault secrets list" 
there is secrets path enabled

**Expected behavior**
secrets path should be enabled by default 
**Environment:**
* Vault Server Version : 1.1.1
* Vault CLI Version: 1.1.1
 Server Operating System/Architecture: linux

Vault server configuration file(s):

backend "consul" {
  address = "x.x.x.:8500"
  advertise_addr = "http://127.0.0.1:8200"
  path = "vault/"
  scheme = "http"

}
listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = 1
}

disable_mlock = true
ui = true

**Comment by MartinLeedotOrg** [comment]
This behaviour was changed in Vault 1.1.0:

https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#110-march-18th-2019

```
core: Vault no longer automatically mounts a K/V backend at the "secret/" path when initializing Vault
```

**Comment by shashankimanage** [comment]
@MartinLeedotOrg  - btw it automatically mounts when the vault ran in -dev mode. 
is that excepted behaviour?

**Comment by MartinLeedotOrg** [comment]
I believe it is. I've opened a PR with some documentation that will hopefully help avoid this confusion in the future.
