### ISSUE TITLE
Any CLI/HTTP API call involving secrets/tokens should return remaining ttl

### ISSUE THREAD

**Issue by jesseendahl** [hashicorp/vault#709]
Right now it seems impossible to tell how long a given auth token or secret will remain valid. The current response only includes total duration, but does not tell you how far into the duration you are/when it runs out.

The feature request here is to return remaining ttl as either an absolute time/date value, or relative time remaining from time of response.

So for example, the current response for `vault token-renew` returns:

```
Key                Value
token              7a293827-8782-bb47-156e-d342a9de2d5a
token_duration     3600
token_renewable    true
token_policies     [nginx]
```

After the addition of this feature request, using a relative value in seconds for `remaining_ttl`, it would look like this:

```
Key                 Value
token               7a293827-8782-bb47-156e-d342a9de2d5a
token_duration      3600
token_remaining_ttl 126
token_renewable     true
token_policies      [nginx]
```

**Comment by jefferai** [comment]
Hi @jesseendahl,

When you perform a renew operation on a token, the value of `token_duration` that comes back contains the remaining TTL. It's not clear to me where the value of 126 is coming from, but in the output you are showing, the `token_duration` value of 3600 means that the remaining TTL is 3600 from when the call was made.

**Comment by CpuID** [comment]
I would love something similar, but advertising the remaining time from reaching the Max TTL so the client can prior to unconditional revocation (once max TTL is reached) perform a new 'read' and get a new set of credentials for a given resource.

This then allows doing things such as in the database backend, having a revocation statement on a role that kills active processes in addition to dropping a user, to enforce a credential is no longer usable. Currently, a revoke would execute a drop user on the backend, but leave existing connections established until they are closed, which IMO feels in a break glass event like it only achieves a partial outcome.

**Comment by jefferai** [comment]
@CpuID I don't really follow how the first paragraph relates to the second :-/ but, can't you already do what Titanium described in the second paragraph if the database supports it?

**Comment by CpuID** [comment]
@jefferai The second paragraph is mostly to provide motive for why the extra feature in the first paragraph would be nice :) If the client knows how long is left before a renewal will be denied, a new lease can be requested before expiration.

**Comment by jefferai** [comment]
The client can easily avoid this. When a renewal is denied the TTL simply doesn't go up. A client can simply have a threshold from the original lease time past which it always fetches a new credential.

**Comment by CpuID** [comment]
@jefferai ah fair call, thats good to know.

I also filed a similar issue in consul-template [here](https://github.com/hashicorp/consul-template/issues/949) to discuss workarounds. @sethvargo has added a workable [solution](https://github.com/hashicorp/consul-template/pull/962) to avoid the issue of potential downtime during the short window of credential unavailability, involving grace periods when the TTL remaining gets too low.

The consul-template solution is a potential reference case for others looking for a way to solve this in Vault clients.
