### ISSUE TITLE
OIDC groups not working

### ISSUE THREAD

**Issue by c35sys** [hashicorp/vault#7100]
**Describe the bug**
I followed this documentation https://learn.hashicorp.com/vault/operations/oidc-auth and the user is not getting correct policies.
I tried with vault versions 1.1.0 and 1.1.3 without success and used Auth0 as an OIDC provider.

**To Reproduce**
1. Run `vault login -method=oidc role="kv-mgr"`
2. I get this:
```
policies             ["default" "reader"]
```
**Expected behavior**
The policies should be as following
```
policies             ["default" "manager" "reader"]
```
Note that vault is running in debug mode so I have this entry when I log in:
`2019-07-10T09:37:55.191+0200 [DEBUG] identity: refreshing external group memberships: entity_id=f6c003d2-b95f-3dc7-950b-efbaaff7052d group_aliases=["mount_accessor:"auth_oidc_39b93989" name:"manager" "]
`

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.1.3
Cluster Name    vault-cluster-37b3df15
Cluster ID      817ff788-0f40-4631-aae9-3abcc52016aa
HA Enabled      false
```
* Vault CLI Version (retrieve with `vault version`):
```
Vault v1.1.3 ('9bc820f700f83a7c4bcab54c5323735a581b34eb')
```
* Server Operating System/Architecture:
Linux Ubuntu 18.04/x86_64

Vault server configuration file(s):

```hcl
backend "file" {
  path = "/home/vagrant/Documents/vault-server/data"
}
 
listener "tcp" {
  address = "0.0.0.0:8200"
  #tls_cert_file = "/etc/vault/vault.pem"
  #tls_key_file = "/etc/vault/vault.key"
  tls_disable = 1
}

disable_mlock = true
ui = true

api_addr = "http://127.0.0.1:8200/"
```

**Additional context**
I tried to do the same first with Keycloak as an OIDC provider, and I also see groups in debug mode but group mapping is not working either.
```
Jul  9 14:34:52 myserver vault[8032]: 2019-07-09T14:34:52.551+0200 [DEBUG] identity: refreshing external group memberships: entity_id=25f802c4-2d4f-335a-a0c5-ede485ba7b89 group_aliases=["mount_accessor:"auth_oidc_5f0e7508" name:"edited-group1" ", "mount_accessor:"auth_oidc_5f0e7508" name:"edited-group2" ", "mount_accessor:"auth_oidc_5f0e7508" name:"edited-group3" ", "mount_accessor:"auth_oidc_5f0e7508" name:"manager" "]
```

**Comment by kalafut** [comment]
@c35sys I'm seeing this issue as well and will investigate.

**Comment by kalafut** [comment]
@c35sys It's a subtle error in the tutorial. The role name set up in auth0 is "manager" and needs to match the group alias name. But the instructions for the group alias are:

```
$ vault write identity/group-alias name="kv-mgr" \
        mount_accessor=$(cat accessor.txt) \
        canonical_id="$GROUP_ID"
```

If you change the name parameter from "kv-mgr" to "manager" it should work fine (or change the auth0 side). I'll get a PR in to have this corrected.  Thanks for flagging it!

**Comment by c35sys** [comment]
Thanks a lot @kalafut it is now working as expected !

Also, I don't need to provide the role when login, ie: `vault login -method=oidc role="manager"` to get the correct policies as long as I am in the correct group. All I need to do is:
```
vault login -method=oidc
```
Another note, you don't need to provide policies when you create an OIDC role as you provide it to the group entry. 
Here is what I did, using keycloak:
```
vault write auth/oidc/role/myrole \
    bound_audiences="vault" \
    allowed_redirect_uris="https://xxx:8200/ui/vault/auth/oidc/oidc/callback" \
    allowed_redirect_uris="http://localhost:8250/oidc/callback" \
    user_claim="preferred_username" \
    groups_claim="groups"
```

**Comment by kalafut** [comment]
@c35sys Glad it's working for you now. I've referenced your additional feedback for the tutorial page update as well.  Thanks!

**Comment by niclan** [comment]
@kalafut - can you please get policies-assigned-by-group-claim included in the OIDC tutorial at https://learn.hashicorp.com/vault/operations/oidc-auth
