### ISSUE TITLE
Move framework.OASDocument into sdk

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [hashicorp/vault#7103]
To easily parse the OpenAPI doc produced by Vault, it's convenient to use the `framework.OASDocument`. Since it's currently located in `/logical/framework/`, it has some extra dependency drag. It would be nice to move it into its own package in the Vault sdk to minimize dependencies.

**Comment by kalafut** [comment]
It was originally in its own package, but was then moved into `framework` for... reasons I don't totally recall 😀. But that was all before Go modules so it makes sense to review this.

**Comment by michelvocks** [comment]
Closing this since it appears to me that the openapi package has been moved into the SDK package.
