### ISSUE TITLE
DEBUG rollback: attempting rollback: path=secret

### ISSUE THREAD

**Issue by sandipdivekar1** [hashicorp/vault#7133]
I have deployed vault in docker container with version 0.11.4. Vault dont have backend storage such consul. I am storing data in file system. We are not gettting any error or failure while communicating with vault service. We can get data via api's, but when I am checking at docker logs  I am seeing lot of debug rollback logs, how can I stop them.

> continuent_vault.1.j7usnelciwfp@worker-4    | 2019-07-17T09:11:36.074Z [DEBUG] rollback: attempting rollback: path=auth/token/
continuent_vault.1.j7usnelciwfp@worker-4    | 2019-07-17T09:11:36.074Z [DEBUG] rollback: attempting rollback: path=sys/
continuent_vault.1.j7usnelciwfp@worker-4    | 2019-07-17T09:11:36.074Z [DEBUG] rollback: attempting rollback: path=secret/
continuent_vault.1.j7usnelciwfp@worker-4    | 2019-07-17T09:11:36.074Z [DEBUG] rollback: attempting rollback: path=identity/
continuent_vault.1.j7usnelciwfp@worker-4    | 2019-07-17T09:11:36.074Z [DEBUG] rollback: attempting rollback: path=cubbyhole/
continuent_vault.1.j7usnelciwfp@worker-4    | 2019-07-17T09:12:36.074Z [DEBUG] rollback: attempting rollback: path=auth/token/
continuent_vault.1.j7usnelciwfp@worker-4    | 2019-07-17T09:12:36.074Z [DEBUG] rollback: attempting rollback: path=sys/
continuent_vault.1.j7usnelciwfp@worker-4    | 2019-07-17T09:12:36.074Z [DEBUG] rollback: attempting rollback: path=secret/
continuent_vault.1.j7usnelciwfp@worker-4    | 2019-07-17T09:12:36.074Z [DEBUG] rollback: attempting rollback: path=identity/
continuent_vault.1.j7usnelciwfp@worker-4    | 2019-07-17T09:12:36.074Z [DEBUG] rollback: attempting rollback: path=cubbyhole/
continuent_vault.1.j7usnelciwfp@worker-4    | 2019-07-17T09:13:36.074Z [DEBUG] rollback: attempting rollback: path=auth/token/

**Comment by chrishoffman** [comment]
These are debug logs for a background function in each backend.  If you want to remove them, you can change your log level to info.
