### ISSUE TITLE
Unable to read the secrets(dynamic secrets) generated under the database secret engine

### ISSUE THREAD

**Issue by Raghavendarlokineni** [hashicorp/vault#7134]
**To Reproduce**

**Unable to read the secrets(dynamic secrets) generated under the database secret engine for helloworld**
```
$ vault list database/config/helloworld
No value found at database/config/helloworld/
```

```
$ vault read database/config/helloworld
Key                                   Value
---                                   -----
allowed_roles                         [msread-role helloworld admin-role readonly-role]
connection_details                    map[connection_url:server=****;port=1433;user id=****;password=****;]
plugin_name                           mssql-database-plugin
root_credentials_rotate_statements    []
```

Listing the list of secrets here:
```
$ vault list database/config/
Keys
----
helloworld
***-***-service
****-svc
```

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       2
Version         1.1.0
Cluster Name    vault-cluster-7d4f8354
Cluster ID      76c510d4-4010-a1f7-7292-234f90c76259
HA Enabled      false

```

* Vault CLI Version (retrieve with `vault version`):
```
$ vault version
Vault v1.1.0 ('36aa8c8dd1936e10ebd7a4c1d412ae0e6f7900bd')
```

Vault server configuration file(s):

```hcl
disable_mlock = true
  
storage "file" {
  path = "*****"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}

ui = true
max_lease_ttl = "7200h"
default_lease_ttl = "7200h"
api_addr = "http://127.0.0.1:8200"
```

**Comment by ncabatoff** [comment]
Hi @Raghavendarlokineni,

The vault CLI generally mirrors the vault API.  The [Database API](https://www.vaultproject.io/api/secret/databases/index.html) allows for listing of configurations, roles, and static-roles.  It does not allow listing the individual leases. 

Why do you want this functionality?  What would you do with that list if you could get it?

**Comment by Raghavendarlokineni** [comment]
Hi @ncabatoff, we are trying to integrate our spring apps with database secret engine to create secrets dynamically. In order to check the new creds in UI which are generated using `spring-cloud-vault`. So thought, viewing this which might help us.

Generally, we do create the creds using this way

```
$ vault read database/creds/helloworld

Output:
Key                Value
---                -----
lease_id           database/creds/helloworld/******************
lease_duration     1h
lease_renewable    true
password           **********************
username           v-root-helloworld-******************************
```

**Comment by chrishoffman** [comment]
Dynamic secrets are not meant to be read after initial creation but created with short leases so that don't live forever.  If you need to retrieve credential, you just request a new set of static credential.  You can list/view lease data using the `sys/leases` endpoints but there is no way to read back the credentials.
