### ISSUE TITLE
Consul Secret Backend - support for management tokens

### ISSUE THREAD

**Issue by jantman** [hashicorp/vault#714]
According to the current documentation on the [Consul secret backend](https://vaultproject.io/docs/secrets/consul/index.html), roles created in Consul can only have an ACL policy/rule set specified. As a result, it's not possible to use Vault to generate management tokens for Consul. We very much need this functionality.

Use case:
We're implementing Vault and Consul not only for dynamic secrets (mainly AWS), but also as a unified secret storage system. Since we're also using the "generic" Consul backend to store non-dynamic secrets (i.e. third-party API keys, and other manually-entered secrets), we need to be able to back up the Consul KV store as part of our DR plan (as well as part of our test plan). However, only a management-level Consul token can read all KV and ACL data. So, our scheduled backup job (running in Jenkins) needs management creds for Consul.

Without Vault being able to lease management-level tokens for Consul, we end up back in exactly the position that Vault is being implemented to avoid, namely privileged credentials hard-coded somewhere in configuration management.

**Comment by jefferai** [comment]
This sounds like a good enhancement. It would probably be enough to add a role parameter specifying which type of token to create, and not requiring a policy if it's a management token.

**Comment by jantman** [comment]
Yeah, that's how I'd envision it working. Thanks!

**Comment by jefferai** [comment]
@jantman I'm putting this on the 0.4 roadmap but there's already a ton there, so I can't promise it'll make it in. That'll make sure this doesn't accidentally get forgotten about, though.

**Comment by jantman** [comment]
Ok, thanks so much.

**Comment by sandstrom** [comment]
Great! :boat:
