### ISSUE TITLE
Feature Request: provide description while requesting database credentials

### ISSUE THREAD

**Issue by bhvishal9** [hashicorp/vault#7149]
**Is your feature request related to a problem? Please describe.**
We want to use hashicorp vault for providing database access to developers. For auditing reasons, we'd like to know why a developer requested database access. Currently, they use 'vault read <db-path>' but there is no option to provide a description.

**Describe the solution you'd like**
I'd like to provide a description message with the vault read command, pretty much like providing git commit message. This is pretty useful for auditing purposes.

**Describe alternatives you've considered**
Adding a wrapper around the command but that will not really help as we will be using the auditing logs generated by vault.

**Explain any additional use-cases**
Auditing, access control

**Additional context**
N/A

**Comment by chrishoffman** [comment]
Thanks for the suggestion.  I think what you are suggesting here is outside of the scope of Vault.  Vault is meant to managed secret data and provides auditing functionality for all access but this additional workflow you are suggesting is rather complicated to implement and likely pretty specific to your use case.

You may be able to accomplish what you are suggesting with a wrapper and using a header that is audited.  See https://www.vaultproject.io/api/system/config-auditing.html#create-update-audit-request-header for more information.
