### ISSUE TITLE
OIDC CLI login redirecting to localhost (with Azure AD)

### ISSUE THREAD

**Issue by killerdonkeykong** [hashicorp/vault#7151]
**Describe the bug**
When logging in using the OIDC auth method, using the UI is fine and works as intended, however logging in through the CLI, the client is unable to authenticate and receives a callback/redirect to localhost, this is obviously not good, as the client is not the intended redirect. Performing a login as a client, they receive the "_Complete the login via your OIDC provider. Launching browser to:_" following the provided link they authenticate to Azure AD, and are redirected back to localhost. The intended behavior is that they are redirected to the Vault server.

**To Reproduce**
_auth/oidc/config_:
```
Key                       Value
---                       -----
bound_issuer              n/a
default_role              reader
jwt_supported_algs        []
jwt_validation_pubkeys    []
oidc_client_id            <app id>
oidc_discovery_ca_pem     n/a
oidc_discovery_url        https://login.microsoftonline.com/<tenant id>/v2.0


```

_auth/oidc/role/reader_
```
allowed_redirect_uris    [https://<vault ip>:8200/ui/vault/auth/oidc/oidc/callback https://<vault ip>:8200/oidc/callback http://localhost:8200/oidc/callback]
bound_audiences          [<app id>]
bound_cidrs              <nil>
bound_claims             <nil>
bound_subject            n/a
claim_mappings           <nil>
groups_claim             groups
max_ttl                  0s
num_uses                 0
oidc_scopes              []
period                   0s
policies                 [default]
role_type                oidc
ttl                      0s
user_claim               email
```

Azure AD Callbacks
```
http://localhost:8200/oidc/callback
https://<vault ip>:8200/oidc/callback
https://<vault ip>:8200/ui/vault/auth/oidc/oidc/callback
```

Command issue to login
```
[user@host~]$ vault login -method="oidc" role="reader" port=8200
Complete the login via your OIDC provider. Launching browser to:

https://login.microsoftonline.com/<tenant id>/oauth2/v2.0/authorize?client_id=<client id>&nonce=*&redirect_uri=http%3A%2F%2Flocalhost%3A8200%2Foidc%2Fcallback&response_type=code&scope=openid&state=*

```

**Expected behavior**
The above redirect_uri should reference the remote server `<vault ip>` , the intended behavior is that the browser is redirected back to Vault, not localhost.

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault 1.1.3
* Vault CLI Version (retrieve with `vault version`): Vault v1.1.3 ('9bc820f700f83a7c4bcab54c5323735a581b34eb')
* Server Operating System/Architecture: RHEL 7.6

Vault server configuration file(s):

```hcl
listener "tcp" {
  address          = "0.0.0.0:8200"
  cluster_address  = "<vault ip>:8201"
  tls_cert_file    = "/data01/certs/cert.pem"
  tls_key_file     = "/data01/certs/key.ins.pem"
  tls_disable_client_certs = "true"
  tls_require_and_verify_client_cert = "false"
}

storage "consul" {
  address = "127.0.0.1:8500"
  path    = "/data01/vault"
}

api_addr = "https://<vault ip>:8200"
cluster_addr = "https://<vault ip>:8201"
ui = "true"

```

**Comment by kalafut** [comment]
The intent of the OIDC CLI flow is to start on the CLI and return there with a new Vault token. Since this is OIDC we necessarily involve the browser, but the CLI has actually started a listener that the browser redirects to, and then the CLI helper completes the login with the Vault server.

Are you running into issues? After the redirect back to localhost, you should be receiving a success message along with the new token.

**Comment by killerdonkeykong** [comment]
Thanks, this can be closed under user error.

**Comment by Akanksha-P97** [comment]
I'm also facing the same issue. And my configurations are also same as above.

Any help would be appreciated.

**Comment by hsimon-hashicorp** [comment]
@killerdonkeykong would you be willing to share what part was user error? It will help other users. Thanks in advance!
