### ISSUE TITLE
Vault KVV2 requires policy paths to include "data" but vault kv put to exclude it

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [hashicorp/vault#7161]
This issue originated [here](https://discuss.hashicorp.com/t/vault-policy-not-working-with-and-in-the-one-path/2082).

It appears that per our docs [here](https://www.vaultproject.io/docs/concepts/policies.html), this should work. Specifically, we state:
```
# Permit reading everything prefixed with "zip-". An attached token could read
# "secret/zip-zap" or "secret/zip-zap/zong", but not "secret/zip/zap
path "secret/zip-*" {
  capabilities = ["read"]
}
```
## Steps to Reproduce
```
$ cat test-pol.hcl 
path "secret/+/toto*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
```
```
$ vault policy write test-policy test-pol.hcl
Success! Uploaded policy: test-policy
```
```
// This is for an ephemeral instance that's already gone so I'm not concerned about leaking the token
$ vault token create -policy=test-policy
Key                  Value
---                  -----
token                s.ui40mu6G4eOe0QcvZBImegnj
token_accessor       tKjIMte8oGbvSKuiIZqXYclz
token_duration       768h
token_renewable      true
token_policies       ["default" "test-policy"]
identity_policies    []
policies             ["default" "test-policy"]
```
```
$ export VAULT_TOKEN=s.ui40mu6G4eOe0QcvZBImegnj
```
```
$ vault kv put secret/mypath/toto1 foo=world
Error writing data to secret/data/mypath/toto1: Error making API request.

URL: PUT http://localhost:8200/v1/secret/data/mypath/toto1
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

**Comment by tyrannosaurus-becks** [comment]
This is presently on master, FWIW.

**Comment by tyrannosaurus-becks** [comment]
I am finding this true for KVV2 when I use the following steps to reproduce:
```
$ export VAULT_TOKEN=root
```
```
$ cat test-pol.hcl 
path "secret/data/+/toto*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
```
```
$ vault policy write test-policy test-pol.hcl
Success! Uploaded policy: test-policy
```
```
$ vault secrets enable -version=2 kv
Success! Enabled the kv secrets engine at: kv/
```
```
$ vault kv put secret/data/mypath/toto1 foo=world
Key              Value
---              -----
created_time     2019-07-22T16:47:28.958141461Z
deletion_time    n/a
destroyed        false
version          1
```
```
$ vault token create -policy=test-policy
Key                  Value
---                  -----
token                s.hTalk0SG3XMpsP0vKDf1BIQL
token_accessor       G9MNltNgM7NZZTfmKY5WnpUo
token_duration       768h
token_renewable      true
token_policies       ["default" "test-policy"]
identity_policies    []
policies             ["default" "test-policy"]
```
```
$ export VAULT_TOKEN=s.hTalk0SG3XMpsP0vKDf1BIQL
```
```
$ vault kv put secret/data/mypath/toto1 foo=world
Error writing data to secret/data/data/mypath/toto1: Error making API request.

URL: PUT http://localhost:8200/v1/secret/data/data/mypath/toto1
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

**Comment by tyrannosaurus-becks** [comment]
Actually! I interestingly just learned that this _does_ work if I keep `data` in the policy path, but _don't_ include it when reading and writing the secret. This is documented [here](https://www.vaultproject.io/docs/secrets/kv/kv-v2.html#acl-rules).

**Comment by tyrannosaurus-becks** [comment]
I found that this does work properly with KVV1 too. 

For me, this means that if I'd paid closer attention to the KVV2 docs, I wouldn't have encountered this. Might be nice to someday have the CLI handle this, so I'm going to edit this to become a feature request for the CLI.

**Comment by tyrannosaurus-becks** [comment]
I am leaving this open for the moment in case there's anything we could do to improve the UX. Might be worth re-looking at. Feel free to close this though if we want to stick with it as it is.

**Comment by tyrannosaurus-becks** [comment]
It appears there are other examples of this happening, [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/6nac2U9crCA/XaRozQGtBQAJ) for instance.

**Comment by tyrannosaurus-becks** [comment]
[Another example.](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/bKi8C5xzNK4/jcqR8OXIBQAJ)

**Comment by fernando-villalba** [comment]
Adding a note from an issue a filed previously if it helps any resolving this issue:

When using kv2 this policy path works:

kv/+/directory/*
The first plus sign would correspond to the data,delete,metadata etc that's needed to use kv2.

However if I do this with multiple plus signs:

kv/+/+/+/+/directory/*
This policy does not work, and if I do this:

kv/+/+/+/+/directory/+
That works.

Even though the last line fulfils my particular purpose, if I wanted to give permission to create indeterminate amount of subdirectories after the last path I would not be able to with that last policy.

**Comment by slessardjr** [comment]
Any update on this?  Our policies are getting more error prone because we have to list a path multiple times in policies.

**Comment by voiprodrigo** [comment]
Hi. Just spent 4 hours trying to understand what was going on, it was driving me crazy. Because I did not put data in the policy path, kv put was denied. But token capabilities command without data in the path always listed create and update! Granted, I missed this point in the docs about needing data in the policy path. But still, very unintuitive.

**Comment by bbros-dev** [comment]
Just to clarify, and identify a use case.

The docs give this example (which did not work for us):

```json
# This section grants all access on "secret/*". Further restrictions can be
# applied to this broad policy, as shown below.
path "secret/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

```

After some hair loss, this worked for us:

```json
# This section grants all access on "secret/+/*". Further restrictions can be
# applied to this broad policy, as shown below.
path "secret/+/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
```

We could use `secret/data/*` but feel `secret/+/*` is likely to be more robust to future changes - we grant the read capability for this general path, and use `secretn` to delimit/categorize domains.

**Comment by slessardjr** [comment]
> Just to clarify, and identify a use case.
> 
> The docs give this example (which did not work for us):
> 
> ```json
> # This section grants all access on "secret/*". Further restrictions can be
> # applied to this broad policy, as shown below.
> path "secret/*" {
>   capabilities = ["create", "read", "update", "delete", "list"]
> }
> ```
> 
> After some hair loss, this worked for us:
> 
> ```json
> # This section grants all access on "secret/+/*". Further restrictions can be
> # applied to this broad policy, as shown below.
> path "secret/+/*" {
>   capabilities = ["create", "read", "update", "delete", "list"]
> }
> ```
> 
> We could use `secret/data/*` but feel `secret/+/*` is likely to be more robust to future changes - we grant the read capability for this general path, and use `secretn` to delimit/categorize domains.

The point is that what you did works, but if you add any static path in-between the + and the * that you get policies that don't work.  So if I wanted to give Developers complete access to the dev path but restrict the prod path, I have to write several line of policy because the wildcard operators are not working properly.

**Comment by bbros-dev** [comment]
> The point is that what you did works...

Correct, and we have a specific setup, outside of that setup it wont work.  We just wanted to register out use case because it seemed sufficiently different.

> So if I wanted to give Developers complete access to the dev path but restrict the prod path, I have to write several line of policy because the wildcard operators are not working properly

Agreed.  I our setup we have `secrets/+/*` for production
For dev and test environments we have `secrets-test/+/*` and  `secrets-dev/+/*` but this is only on the bootstrap Vault server.
We are have separate servers/infra for dev and test which use the production syntax.

Our bootstrap Vault server has a narrow scope of only those secrets used to bootstrap infrastructure, and it is in this bootstrap server we have encounter this issue.  This means that policies for prod dev and test environments (post-bootstrap) are identical, and we are liberal with secret stores.

**Comment by piotrkochan** [comment]
Is there any resolution to these issues? It is for a long time and still present.

**Comment by ncabatoff** [comment]
> Is there any resolution to these issues? It was reported long time ago and still present.

I agree that the status quo is confusing and error-prone.  But all the solutions I've seen proposed do one or more of:
* break backward compatibility
* require the ACL code to understand details of how individual secrets engines work
* add excessive complexity to the policy syntax 

I'm happy to review docs PRs that aim to improve our documentation, e.g. by pointing out more prominently when a policy example is specific to KVv1 and won't work with KVv2.  I'm also open to discussing concrete suggestions for code changes to reduce the pain here.  I'm going to close this issue though, please open a new one if you'd like to pursue one of these options.
