### ISSUE TITLE
TTL without a time suffix is accepted, but breaks on read

### ISSUE THREAD

**Issue by bkrodgers** [hashicorp/vault#718]
If I write a TTL on a generic secret as "3600", it allows it.  However, when I read that secret, I get "failed to parse TTL for entry".  I would suggest that it should allow specifying ttls without a suffix as it does, and the read should default that to "s" (or write can add it in as a default if that's more efficient).

```
bkrodg-mac2:~ bkrodg$ vault write secret/test/bkrodg ttl=3600 test=hi
Success! Data written to: secret/test/bkrodg
bkrodg-mac2:~ bkrodg$ vault read  secret/test/bkrodg
Error reading secret/test/bkrodg: Error making API request.

URL: GET https://<vault-server>/v1/secret/test/bkrodg
Code: 400. Errors:

* failed to parse ttl for entry
```

**Comment by jefferai** [comment]
@bkrodgers I'm working on this now, but wanted to leave a note: we're currently thinking about some API changes as we think about how to make backends more similar and consistent, so I'm going to defer the "default if no suffix" question until then. For the moment I will make it behave as it does most other places. But that is a good thought for a later revamp.
