### ISSUE TITLE
go mod amiguous import dependency github.com/hashicorp/vault/api v1.0.4 vs 1.1.4

### ISSUE THREAD

**Issue by weitzj** [hashicorp/vault#7205]
# Problem

- If I use the vault/api go module using `go get github.com/hashicorp/vault/api` I get version `v1.0.4`
- If I use the vault go module using `go get github.com/hashicorp/vault` I get version `v1.1.4` 

# Solution

Since the main hasicorp go module uses 

[`replace github.com/hashicorp/vault/api => ./api`](https://github.com/hashicorp/vault/blob/master/go.mod#L5)

I would assume we are fine by:

- add tag `api/v1.1.4` alongside the `v1.1.4` tag.

**Comment by jefferai** [comment]
The main Vault repo is not designed to be imported into other projects. Additionally 1.1.4 is pre-go mod. The first version where the main repo will have go mod support will be 1.2.0.

**Comment by weitzj** [comment]
Thanks. I have figured it out.

To use go modules in the meantime ensure `go.mod` contains:

`github.com/hashicorp/vault v1.2.0-rc1`

**Comment by wuduozhi** [comment]
> Thanks. I have figured it out.
> 
> To use go modules in the meantime ensure `go.mod` contains:
> 
> `github.com/hashicorp/vault v1.2.0-rc1`

I also sulve my problem by this way,but I don't  know why it could work. Can you tell me please?
