### ISSUE TITLE
Vault make error - CentOS 

### ISSUE THREAD

**Issue by narayan8291** [hashicorp/vault#721]
I am trying to compile the new source code onto my centos server. After installing Go and setting up the go env variables (GOPATH, GOROOT and PATH). I cloned the vault repo into $GOPATH/src/github.com/hashicorp/vault. 

1. make bootstrap - was successful and I checked the bin folder to verify if godep was installed. 
2. make - Successful.
3. make dev - Fails

Here is the output,

[ngowraj@inw-1320 vault]$ make dev
go generate ./...
==> Removing old directory...
==> Building...
Number of parallel builds: 1

-->     linux/amd64: github.com/hashicorp/vault

1 errors occurred:
--> linux/amd64 error: exit status 1
Stderr: # github.com/hashicorp/vault
link: warning: option -X github.com/hashicorp/vault/cli.GitCommit 43cfa275af5fecc60cabf3bbddaf6f4ba1992b46 may not work in future releases; use -X github.com/hashicorp/vault/cli.GitCommit=43cfa275af5fecc60cabf3bbddaf6f4ba1992b46
go install github.com/hashicorp/vault: mkdir /home/ngowraj/go/src/github.com/hashicorp/vault/pkg: permission denied

make: *** [dev] Error 1

I tried sudo too,

[ngowraj@inw-1320 vault]$ sudo make dev
go generate ./...
==> Removing old directory...
==> Building...
Number of parallel builds: 1

-->     linux/amd64: _/home/ngowraj/go/src/github.com/hashicorp/vault

1 errors occurred:
--> linux/amd64 error: exit status 1
Stderr: main.go:6:2: cannot find package "github.com/hashicorp/vault/cli" in any of:
	/usr/local/go/src/github.com/hashicorp/vault/cli (from $GOROOT)
	($GOPATH not set)

make: *** [dev] Error 1
[ngowraj@inw-1320 vault]$  

Any idea why this is happening ?

**Comment by jefferai** [comment]
The first error appears to be a permission denied error -- check permissions on the specified path.

The second error is because your `sudo` isn't preserving GOPATH. Like the error says, GOPATH isn't set.

In the future, please use the mailing list for general questions like this, as there are many more people available to help -- you can sign up at https://groups.google.com/forum/#!forum/vault-tool
