### ISSUE TITLE
Dual stack delays

### ISSUE THREAD

**Issue by draggeta** [hashicorp/vault#7213]
**Describe the bug**
We currently authenticate to vault via LDAP on AD Domain Controllers. This works, but with a high delay. This is due to the fact that out network is dual stack, but for various reasons the Vault server can only reach the DC's via IPv4.

From what we see, Vault always tries to connect with IPv6 first before switching to IPv4 for LDAP.

**To Reproduce**
1. Run `vault login -method ldap username=draggeta`
2. enter password
3. wait 10+ seconds
4. logged in

**Expected behavior**

Fast login via LDAP instead of the usual 10+ seconds.

**Environment:**
* Vault Server Version (retrieve with `vault status`):
1.1.1
* Vault CLI Version (retrieve with `vault version`):
Vault v1.1.1 ('a3dcd63451cf6da1d04928b601bbe9748d53842e')
* Server Operating System/Architecture:
Debian 8 x64

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
listener "tcp" {
  address = "[::1]:8200"
  address = "127.0.0.1:8200"
  tls_disable = true
}

storage "azure" {
  accountName = "storageaccount01"
  accountKey = "RandomString"
  container = "vault-data"
}
```

**Additional context**

**Comment by hsimon-hashicorp** [comment]
Hi folks! Is this still an issue in newer versions of Vault? Please let me know so I can bubble it up accordingly. Thanks!

**Comment by raskchanky** [comment]
Since it's been awhile with no response, I'm going to close this issue. Please reopen if there's more to add here.
