### ISSUE TITLE
time.Time value in a non map key cannot be hashed for audits

### ISSUE THREAD

**Issue by jmariondev** [hashicorp/vault#7228]
**Describe the bug**
Attempting to hit the `/sys/internal/counters/requests` endpoint with audit logging enabled results in a 500 response, and the following error being logged:

```
[ERROR] audit: backend failed to log response: backend=file/ error="time.Time value in a non map key cannot be hashed for audits"
[ERROR] audit: backend failed to log response: backend=syslog/ error="time.Time value in a non map key cannot be hashed for audits"
[ERROR] core: failed to audit response: request_path=sys/internal/counters/requests error="1 error occurred:
* no audit backend succeeded in logging the response
"
```

**To Reproduce**
1. Enable an audit log device
2. Attempt to read the problem endpoint: `vault read /sys/internal/counters/requests`

**Expected behavior**
The endpoint should return counter data, instead it returns 500 because the request can't be audited.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.1.3+prem
* Vault CLI Version (retrieve with `vault version`): v1.1.3+prem ('af0b27edfd5bcd9123b6ac69e90c6e6dfa3654f7')
* Server Operating System/Architecture: CentOS 7 amd64

**Additional context**
See related #3916.

**Comment by jefferai** [comment]
Hi there,

This is fixed in https://github.com/hashicorp/vault/pull/6767 in Vault 1.2.

**Comment by jmariondev** [comment]
Oh excellent, thanks! I haven't upgraded to 1.2 yet but I'll take your word for it until then!
