### ISSUE TITLE
Unable to use Postgresql 11.4 as a backend vault 1.2.0

### ISSUE THREAD

**Issue by schall8** [hashicorp/vault#7239]
Vault fails to initialize giving error 
vault server -log-level=info -config=/opt/vsm/vault/config.hcl
Error initializing storage of type postgresql: failed to check for native upsert

**To Reproduce**
Attemp to start vault as a service using postgresql as a backend.

**Expected behavior**
Service startup

**Environment:**
* Vault Server Version (retrieve with `vault status`):
1.2.0
* Vault CLI Version (retrieve with `vault version`):
1.2.0
* Server Operating System/Architecture:
RedHat 7.6
*Postgresql 11.4

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
listener "tcp" {
        address           = "<server>:8200"
        tls_disable       = "false"
        tls_cert_file     = "/opt/vsm/certs/vault_bundle.pem"
        tls_key_file      = "/opt/vsm/certs/vault.key"
        tls_min_version   = "tls12"
        tls_cipher_suites = "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA"
}

storage "postgresql" {
        connection_url = "postgres://vault:**password**@<server>:<port>/vault?sslmode=disable"
}


**Additional context**
logged into psql as vault user to the vault database, ran the following commands.
psql -d vault -U vault -p 5444
Password for user vault: 
psql (11.4)
Type "help" for help.

vault=> SELECT current_setting('server_version_num')::int < 90500;
 ?column? 
----------
 f
(1 row)

vault=> SELECT current_setting('server_version_num');
 current_setting 
-----------------
 110004
(1 row)

**Comment by ncabatoff** [comment]
Hi @schall8,

Is there not more to the error?  The code line in question is

```go
return nil, errwrap.Wrapf("failed to check for native upsert: {{err}}", err)
```

so I'd expect to see the cause of the error after a colon.

**Comment by schall8** [comment]
That is all there is, i changed the startup to debug with no changes in output.
# /opt/vsm/vault/vault server -log-level=debug -config=/opt/vsm/vault/config.hcl
Error initializing storage of type postgresql: failed to check for native upsert: dial tcp 15.140.0.94:5444: connect: connection refused

**Comment by ncabatoff** [comment]
Ok, there we go, that's the error I was looking for.  It looks like `15.140.0.94:5444` is not accessible from the Vault server.  Try connecting to the host where Vault is running and you should be able to demonstrate that.  So either the IP is wrong, or there's a routing or firewall issue, or equivalent.

**Comment by schall8** [comment]
my bad i noticed the error 'connection refused' and double checked the config.hcl i had ssl=enable that is not supported, switched to require.

[root@z4t0489 vault]# /opt/vsm/vault/vault server -log-level=info -config=/opt/vsm/vault/config.hcl

WARNING! Unable to read storage migration status.
2019-08-01T21:29:49.728Z [WARN]  storage migration check error: error="pq: relation "vault_kv_store" does not exist"
2019-08-01T21:29:51.728Z [WARN]  storage migration check error: error="pq: relation "vault_kv_store" does not exist"
2019-08-01T21:29:53.729Z [WARN]  storage migration check error: error="pq: relation "vault_kv_store" does not exist"
2019-08-01T21:29:55.730Z [WARN]  storage migration check error: error="pq: relation "vault_kv_store" does not exist"

Vault is still not starting but now i have an error i can work with.

**Comment by schall8** [comment]
closing issue, user error

**Comment by 13567436138** [comment]
how to solve I facing the same error

**Comment by isaacchristian** [comment]
I'm going through the same error and can't figure out how to get past it. How were you able to bypass this error?
