### ISSUE TITLE
Administrative functions need to specify administrative tokens and permissions separately

### ISSUE THREAD

**Issue by emk** [hashicorp/vault#724]
I'm trying to mirror certain, limited portions of a vault configuration to another vault server. This requires being able to:

1. List all policy names.
2. Copy all policies beginning with a particular string.

It turns our that there is no way to specify "this user can read certain vault policies, but can't change them." Every set of ACLs I try to write either fails to provide read access, or allows write access:

```
# Allow listing all available policies, so we can decide which policies to
# sync. sudo is _probably_ harmless here, but we'd really prefer `read`.
path "sys/policy" {
  policy = "sudo"
}

# Allow reading the details of development policies, so we can copy them
# down verbatim.
path "sys/policy/development-*" {
  # This is wrong, because it allows changing policies.
  #policy = "sudo"
  # This won't work, because you can't read without sudo permissions:
  #policy = "read"
}
```

**Comment by jefferai** [comment]
Hi @emk ,

There are plans to expand the permissions/ACL system in the future, which I think will address some of these concerns, but not all.

The first bit in your snippet above would potentially be addressed as one of the new permissions is likely to be "list". So you could list the policies, probably by name, without necessarily having read access to them.

The problem with addressing it is that both of those endpoints require root access. `sudo` is just a way to let a non-root token act as a root token on a path, but root tokens can do anything, as you know.

What you really need here is to have those endpoints not require a root token. That requires a whole rethink of when and where certain endpoints are designated root-only. Mostly this is to prevent policy mistakes where someone puts something like "sys/*" with read and doesn't realize that they've just exposed a lot of very sensitive data to any token with that policy.

A possible way to handle this would be to separate "sudo" into "admin" plus "read/write/list". That way the path cannot simply be added accidentally via a glob in the policy path; it also requires explicit admin access.

This is certainly something to think about when we work on the ACL revamp. I'm going to modify the subject of this to make it match the underlying issue.

**Comment by jefferai** [comment]
I'm also putting this in the 0.5 milestone, although this is mostly to ensure that this doesn't fall off anyone's radar...please understand that this is not a hard promise and will really move to whenever we land the ACL revamp.

**Comment by emk** [comment]
OK, cool. All of our policies are loaded via a script, so we can just load a second copy into the `secret/` backend, and fetch that. This will make a reasonable workaround for now.

But the "`sudo` is needed to read some sensitive secrets but it **always** grants write access" seemed like it was worth filing a bug against, because that's an unfortunate security temptation in admin scripts.

So far, I'm really happy with vault, by the way—it's sort of like an organization-wide security policy toolkit in a box.

**Comment by jefferai** [comment]
Yeah, you can see the Unix model in the initial ACL system design, but extended attributes exist for a reason, right? :-)

Glad you're happy with Vault so far, and I hope you'll continue to like where it goes. There are major overhauls planned for the 0.5+ releases to provide a lot of enhancements (like the ones in this ticket) and I think it will become an even more flexible toolkit.
