### ISSUE TITLE
Make it possible to disable the VAULT_API_ADDR empty warning

### ISSUE THREAD

**Issue by EugenMayer** [hashicorp/vault#7246]
**Feature request**
Please make it possible to supress the VAULT_API_ADDR is empty warning. In usual full-self contained docker-stacks VAULT_API_ADDR cannot be determined statically, that is why it is always empty ( auto detect on the eth addr ) - this is perfectly fine there.

Please make it possible to supress this warning by e.g. making the value an `""` and not null - null check means -> show warning, empty string means -> by intention, no warning

**Comment by aphorise** [comment]
@EugenMayer - did you actually [have: `api_addr`](https://www.vaultproject.io/docs/concepts/ha.html) defined in your config? - I believe where neither that is set nor the environment variable `VAULT_API_ADDR` then that warning message rightly appears.

Is this issue still applicable? - if so can you share outputs of what you're looking at - the Vault version & your configuration file would also help.

**Comment by EugenMayer** [comment]
@aphorise i cannot set those variable because in a full self contained docker stack, the ip does change. Consul starts as a part of the stack, about 20 services, and the ip of the consul server can change as the stack gets upgraded ( docker-compose down/up ) during and update / liekwise

**Comment by aphorise** [comment]
Is you're issue some reoccurring warning message? - can you share what you're looking at? - I'm also curious if some sort of external filter may be an option.

**Comment by aphorise** [comment]
Hey @EugenMayer we've not heard back from you and I'm curious if this is still releavnt and an issue for you?

**Comment by aphorise** [comment]
Closing due to no follow-up. Please reopen with retest of more recent version (1.11.3) as well as screenshot / output of the warning message.
