### ISSUE TITLE
PostgreSQL multiple hosts configuration and database cluster failover

### ISSUE THREAD

**Issue by lenaing** [hashicorp/vault#7247]
The current library used for the physical PostgresSQL backend is [lib/pq](https://github.com/lib/pq).
However, this library does not :
* Handle multiple hosts in connection string : https://github.com/lib/pq/issues/683
* Handle failover options : https://github.com/lib/pq/issues/800

### To reproduce :

1. Configure vault to use postgresql as backend and use multiple hosts in connection string, and enable _target_session_attrs_ parameter (Cf [C libpq parameters keywords](https://www.postgresql.org/docs/devel/libpq-connect.html#LIBPQ-PARAMKEYWORDS))
2. Start Vault
3. Vault does not start, see error.

#### Vault Config excerpt :
```
...
"postgresql": {
      "connection_url": "postgresql://user:password@host1.example.com:5432,host2.example.com:5432/vault_database?sslmode=disable&target_session_attrs=read-write",
      "table": "vault_kv_store",
      "ha_enabled": "true"
}
...
```

#### Results :
```
Error initializing storage of type postgresql: failed to check for native upsert: dial tcp: lookup host1.example.com:5432,host2.example.com:5432: no such host
Error initializing storage of type postgresql: failed to check for native upsert: pq: unrecognized configuration parameter "target_session_attrs"
```

A stale PR has been opened to solve these issues but it seems it won't be merged on this project : https://github.com/lib/pq/pull/714

The [pgx ](https://github.com/jackc/pgx) project seems to have merged this kind of handling here : https://github.com/jackc/pgx/pull/545

### Expected behavior :
It would be nice to support multiple hosts in connection string and target session attributes so that on connection lost Vault would reconnect automatically, enable one to have a database cluster that can failover.

### Environment :
* Vault version : 1.2.0
* Operating System / Architecture :
  * CentOS Servers / PostgresSQL 10 Cluster

Regards,

**Comment by innovationhub-asia** [comment]
Any plan to resolve this? Otherwise it's hard to use Postgres as a backend in production environments.

**Comment by cpoule23** [comment]
Hello, +1. Today, the switch of postgres database need to cut the service, time to allow write access on the failover DB.

**Comment by KaymeKaydex** [comment]
> Any plan to resolve this? Otherwise it's hard to use Postgres as a backend in production environments.

lets use pgx

**Comment by caniko** [comment]
It makes more sense to implement [multiple hosts support](http://paquier.xyz/postgresql-2/postgres-10-multi-host-connstr/) and [RW/RO connection selector](http://paquier.xyz/postgresql-2/postgres-10-libpq-read-write/) support rather than what is proposed by the OP (limited to failover).

**Comment by fairclothjm** [comment]
As of Vault 1.11 we are using pgx. See https://github.com/hashicorp/vault/pull/15343

@lenaing Can you confirm that this resolves this issue for you?

**Comment by lenaing** [comment]
Hi, sorry for the delay.

I do not have two databases anymore to test this, but I believe that we can close the issue as _pgx_ does handle multiple hosts configuration and target selection.

Thanks !
