### ISSUE TITLE
Provide Public-key encrtyption via the transit endpoints

### ISSUE THREAD

**Issue by cHolzberger** [hashicorp/vault#7256]
**Is your feature request related to a problem? Please describe.**
encrypting a message for a known recipient when only the public key is known.

**Describe the solution you'd like**
just load pubkeys into vault and encrypt using the usual workflow. versioning and uploading multiple versions of one key would be nice.

**Describe alternatives you've considered**
writing own code to encrypt the messages.

**Explain any additional use-cases**
builds base of trust between two systems, ssl handshares could be made obsolete (to bring it to the boil ;)). could form the base of two vault instances which are not active replicating partners...

**Comment by Gabrielopesantos** [comment]
Hello,

I started doing some exploring on this issue/enchantment and I would like to implement it. Here’s an initial design proposal:
From what I have gathered from the issue creator’s message, they are asking for the possibility to import public-keys (and update) and use them to encrypt data. Endpoints for each of these operations already exist:
`/transit/keys/:name/import` - Import key
`/transit/keys/:name/import_version` - Import key version
`/transit/encrypt/:name` - Encrypt data

Currently, “import key” and “import key version” support the import/update of the private keys of asymmetric type encryption and secret keys in symmetric type encryption. To enable the optional import or update of public keys, a new field public_key could be added where the plaintext/PEM key would be provided. With this, the ciphertext field would not be a required field anymore, and a user could simply use the endpoints to import a public-key or both (even though it would not be needed and some additional checks would be required). To import a key at least one of the fields would have to be set.

This would allow cases where a user simply wants to import a public-key and later on import its private counterpart. As said above, some validations would be required, checking if provided key matches its counterpart.

There are certainly some cases and questions that I have not thought of, but some feedback would be appreciated. Thanks

**Comment by schultz-is** [comment]
Howdy, @Gabrielopesantos! That'd be a welcome contribution for sure. It sounds like you've put some good thought into the functionality. Here are a few things to consider when implementing:

- Transit currently doesn't support public-only keys, so support of public key import will also entail support for keys without a private component. Shouldn't be too difficult, but it's worth calling out.
- It'd be most efficient and least confusing to accept only one of the `public_key` or `ciphertext` fields per import to avoid the necessity of checking for a matched key pair as you've mentioned.
- In the case where the public component of a key is imported prior to the private component of the same key, it would probably make sense not to increment the key version unless explicitly specified by the user.

Thanks for looking into this! Looking forward to your contribution!

**Comment by Gabrielopesantos** [comment]
Hello @schultz-is @cipherboy,

I have started the implementation and ran into some things that I didn't consider before. I leave some thoughts here and, if possible, would like to hear with you think.

I started with the assumption that once we have a private key, its public counterpart isn't needed and will not be used anymore so no further actions related to it are allowed (insert it with an update or update it if was inserted before the private key). This leads to the following possible cases:

- Key starts with public key import
   - Public key can be upserted - allowed
   - Private key is added (if key pair is valid)
      - Public key can be updated - not allowed
      - Private key can be upserted - allowed (public key is ignored, however, should it be removed?)
- Key starts with private key
  - Public key can be added - not allowed
  - Private key can be updated - allowed

My other doubt was related to the `allow_rotation`, `derived`, `exportable`, `allow_plaintext_backup`  and `auto_rotate_period` parameters on the `import` endpoint that will require additional checks or taken into account if only public key has been imported. If not addressed, unexpected side effects might appear.

**Comment by cipherboy** [comment]
Do we perhaps have to break these down by case? E.g. for:

> Public key can be updated - not allowed

if the public matches the existing private, then its a no-op and doesn't really matter.

But if its a new public key, I don't see why we can't roll to a new version and allow all operations on the old version? 

The same I think holds for the other scenarios.

I'll defer to Matt/others on the parameters though. RSA keys can't be derivable, nor can ECDSA, but Ed25519 are which is weird.

Exportable I don't think matters w.r.t. public key/private key import, nor does `allow_plaintext_backup`. The `allow_rotation`/`auto_rotate_period` is another question entirely though... 

I think looking at https://github.com/hashicorp/vault/blob/main/sdk/helper/keysutil/policy.go#L331-L332 might start to help -- its complex, but the key type is specified once, but old keys have both public and private available..

https://github.com/hashicorp/vault/blob/aa94835a45ceb36e331de9d81605aa0e19d45fc1/sdk/helper/keysutil/policy.go#L827-L834

https://github.com/hashicorp/vault/blob/aa94835a45ceb36e331de9d81605aa0e19d45fc1/sdk/helper/keysutil/policy.go#L255

https://github.com/hashicorp/vault/blob/aa94835a45ceb36e331de9d81605aa0e19d45fc1/sdk/helper/keysutil/policy.go#L196-L223

So you'd probably just set `FormattedPublicKey` and not set `RSAKey` and `EC_*` members and handle that appropriately ~everywhere.

Perhaps that gets you started?

**Comment by cipherboy** [comment]
This will be in the upcoming Vault 1.14 release. Congratulations on another great feature, @Gabrielopesantos! 

For anyone following this thread, give it a shot and let us know your thoughts! :-)
