### ISSUE TITLE
Acces to errors from vault HTTP API response in Secret structure?

### ISSUE THREAD

**Issue by loredo** [hashicorp/vault#727]
I want to transmit further errors from vault when performing a call to HTTP API.

Could be added in api.Secret structure an element for this?

e.g. Errors []string `json:"errors"`

Thank you,

Loredana

**Comment by jefferai** [comment]
In `master` there is a warnings structure and API for response objects that can be used to send warnings back. It's intended to be used to send warnings when a command is successful, but you could piggyback on this for your own purposes.

What is the use case for returning multiple errors? As soon as an error is encountered, any call to the API returns. It's unusual for an API to support returning multiple errors at once.

**Comment by loredo** [comment]
I couldn't find warnings structure. I found only Warnings []string `json:"warnings"`. 
In my vault client I  do not return multiple errors but want to catch specific errors and treat them.  

So I wanted to catch errors from Vault http response like: {"errors":["missing 'app_id' or 'user_id'"]} when wrong appid or userid was provided.
In this case, I could create an errors structure and unmarshall on it errors json,  if no data caught.

In other cases when secret name is wrongly provided, it returns errors as empty array: {"errors":[]}
No consistent errors, so I couldn't count on them. 
I will treat different error cases internally in my vault client.

**Comment by jefferai** [comment]
Sorry, I mis-typed: I meant that there is a warnings array, not a warnings object. 

I'm still not clear what you're looking for. If an operation is unsuccessful, if an error is returned, it will be in the errors array, but it is up to individual backends to actually return a descriptive error string.

At other times, status codes are the method used. This is especially true if the error is a sensitive or internal-only error, where there may be a status code of 500 but no error returned to the client; in these cases there should be an error logged in the server's output.

The error structure is consistent, but it is simply not always populated.
