### ISSUE TITLE
Vault 1.2.0 & 1.2.1 UI goes to the wrong location when trying to change ldap settings through ui

### ISSUE THREAD

**Issue by villChurch** [hashicorp/vault#7287]
**Describe the bug**
On vault 1.2.0 and 1.2.1 when I either create a new ldap auth method, or have an existing one, and then try to click on that auth method, from the Access tab, to edit the users and groups using the new UI features, vault returns a 404 Not Found with the following message

 "Sorry, we were unable to find any content at /v1/auth/ldap//groups/example?help=true.
Double check the url or go back home ."

It looks like there is a double '/' after ldap where it should be a single '/'?

Reproduce**

1. Create a vault running either version 1.2.0 or 1.2.1.
2. Create a LDAP auth method.
3. Go to the Access tab on the UI and then click on your new ldap auth method

**Expected behavior**
I expected that clicking on the LDAP auth method would let me configure users and groups for that LDAP auth like it did in the 1.2.0 beta release.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.2.0 or 1.2.1
* Vault CLI Version (retrieve with `vault version`): Vault v1.2.0 or Vault v1.2.1
* Server Operating System/Architecture: Vault is running inside a docker container which sits on a RHEL 7 image.

Vault server configuration file(s):

{
        "backend": {
                "file": {
                        "path": "..."
                }
        },
        "listener": {
                "tcp": {
                        "address": "0.0.0.0:443",
                        "tls_cert_file":"...",
                        "tls_key_file":"...",
                        "tls_min_version":"tls10",
                        "tls_disable_client_certs":true
                }
        },
        "api_addr": "...",
        "ui": true,
        "allowed_origins": "*",
        "log_level": "DEBUG"
}

**Additional context**
I can replicate the issue on Vault 1.2.0 and Vault 1.2.1.

**Comment by meirish** [comment]
Fixed by https://github.com/hashicorp/vault/pull/7299

**Comment by villChurch** [comment]
Nice one. Thanks all looks to be all working in 1.2.2 😃
