### ISSUE TITLE
configured Vault token contains non-printable characters and cannot be used

### ISSUE THREAD

**Issue by tormath1** [hashicorp/vault#7288]
**Describe the bug**
Hi, I am trying to use a Vault token stored in a tmp file: 
```shell
configured Vault token contains non-printable characters and cannot be used
```

**To Reproduce**
1. echo "my-token" >> `/tmp/my-token`
2. use ioutil.Readfile to get content of `/tmp/token`
3. use `SetToken` to set the token
4. perform a request to Vault

**Expected behavior**
Get my request result

**Environment:**
`github.com/hashicorp/vault/api v1.0.4 // indirect`

**Additional context**

In the source, we run this kind of test:
https://github.com/hashicorp/vault/blob/18aaf01fbe49e865ed3f1932609110e7b5475758/api/client.go#L755-L761

It could be nice to check if the last character is a `\n` and replace it by an empty character?

**Comment by catsby** [comment]
Hello there! Would it be possible to trim the trailing characters in your code before attempting to use the token? Something like `token = strings.TrimSuffix(token, "\n")`? 

On the surface, it's really simple to add that to Vault's code and do it for you. At the same time, I'm hesitant to introduce code that modifies a users Token input in an attempt to the token valid. I would prefer Vault not modify the supplied token value at all.

**Comment by jefferai** [comment]
Additionally using "echo -n" would work around this in the first place.

**Comment by tormath1** [comment]
Hi there, 

Yes it totally makes sense to not "modify" the token. However, we could add a more explicit error message ?
The user should not need to lookup in the source code to find out this error trigger :/

**Comment by michelvocks** [comment]
Hi @tormath1!

What error message would you expect to see? I personally think the current error message explicitly defines the problem, doesn't it?

Cheers,
Michel

**Comment by avinson** [comment]
fyi, this is also an issue with the example token helper script posted on official vault docs: https://www.vaultproject.io/docs/commands/token-helper/#example-token-helper

**Comment by catsby** [comment]
Hello - we haven't heard back in some time, so we're going to close this issue for now. If you have more information please let us know by opening a new issue, and optionally referencing this one. Thanks!

**Comment by stephmafole** [comment]
@catsby ... your [idea](https://github.com/hashicorp/vault/issues/7288#issuecomment-555743757) was the ultimate solution to my problem.

Thank you very much.

I've trimmed the token before authenticating my Go app on Vault, and it worked like a charm !!!
