### ISSUE TITLE
Vault token from ~/.vault-token not picked up by SDK, only CLI

### ISSUE THREAD

**Issue by gitirabassi** [hashicorp/vault#7289]
The normal behavior in the `vault` cli is to use the `~/.vault-token` (which is written during the `vault login` phase. ) if the `VAULT_TOKEN` is not found

https://github.com/hashicorp/vault/blob/master/command/base.go#L122

I'm suggesting that we can move this behaviour to the `api.NewClient(...)` function 

I should be able to do it in no time if this gets approved

**Comment by chrishoffman** [comment]
It makes sense that an api client has no understanding of the local system and this is why it is the CLI's responsibility to understand the local system and reference local resources.  In addition, the token helper system is pluggable which means that custom implementations can be added to lookup from other locations or systems.  I don't think it makes sense to add this functionality to the API client.
