### ISSUE TITLE
Provide option to use OpenSSL already installed instead of inbuilt TLS lib

### ISSUE THREAD

**Issue by SunilAgrawal** [hashicorp/vault#7292]
**Is your feature request related to a problem? Please describe.**
Will like Vault to use the OpenSSL present on the platform. The reason is OpenSSL is FIPS certified and we want all our software to use it, instead of having to go through FIPS compliance of different crypto modules.

Maybe a way that can be supported is through a environment variable or build time options, so that majority of the users who don't have the requirement get a smooth experience, but a select few customers like us who want to use platform's OpenSSL can use the custom build/runtime option.

**Describe alternatives you've considered**
We can fork the Vault code and change all occurrences of inbuilt TLS/crypto to OpenSSL. But then we have to maintain the fork, which isn't ideal.

**Comment by joelthompson** [comment]
Have you considered using a TLS-terminating reverse proxy in front of Vault on the same machine and having that reverse proxy use the FIPS-validated OpenSSL libs?

**Comment by SunilAgrawal** [comment]
That's an interesting suggestion, however, we'd prefer doing it natively
within Vault and not introduce other components, due to the complexity and
additional CPU/memory consumption.

**Comment by cipherboy** [comment]
The [FIPS 140-2 Inside](https://www.vaultproject.io/docs/enterprise/fips/fips1402) version of Vault Enterprise now features a variant with an internal, certified cryptographic module (based on BoringSSL). As such, while selection of an external arbitrary cryptographic module isn't possible, this does satisfy the use case of a certified TLS implementation. An updated Letter of Attestation should be published [to the Hashicorp website](https://www.hashicorp.com/vault-compliance) soon.
