### ISSUE TITLE
Vault Agent requires auto_auth config options despite documentation stating it is optional.

### ISSUE THREAD

**Issue by Tyler-R** [hashicorp/vault#7293]
**Describe the bug**
The [documentation](https://www.vaultproject.io/docs/agent/index.html) for the Vault Agent states that `auto_auth` is an optional configuration option, but when running the vault CLI application I go the error message `Error loading configuration from config.hcl: error parsing 'auto_auth': one and only one "auto_auth" block is required`. Specifically this line gives the impression that that `auto_auth` config option is optional:

- auto-auth (auto-auth: \<optional\>) - Specifies the method and other options used for Auto-Auth functionality.

**To Reproduce**
1. Run `vault server -dev`
2. Run `export VAULT_ADDR="http://127.0.0.1:8200"`
2. Create a file called `config.hcl` with the contents:
```hcl
pid_file = "./pidfile"

vault {
	address = "https://127.0.0.1:8200"
}

listener "tcp" {
	address = "127.0.0.1:8100"
	tls_disable = true
}
```
3. Run the vault agent with `vault agent -config=config.hcl` 
4. See error: `Error loading configuration from config.hcl: error parsing 'auto_auth': one and only one "auto_auth" block is required`

**Expected behavior**
Either the vault CLI command should run the agent without the `auto_auth` option being provided, or the documentation should state that the `auto_auth` option is not optional.

**Environment:**
* Vault Server Version: 0.11.5
* Vault CLI Version: Vault v0.11.5
* Server Operating System/Architecture: Mac High Sierra Version 10.13.6

**Comment by calvn** [comment]
Hi @Tyler-R, apologies for the confusion. The documentation on the site always applies to the latest version of Vault (1.2.1 as of this writing).

The `auto_auth` block was made optional on Vault 1.1.0 through [this PR](https://github.com/hashicorp/vault/pull/6421).
