### ISSUE TITLE
Permission denied when renewing a lease with a root token

### ISSUE THREAD

**Issue by Lasering** [hashicorp/vault#7297]
**Describe the bug**
When invoking sys/leases/renew with a root token I'm getting a permission denied.

**To Reproduce**
1. `docker run --cap-add IPC_LOCK -d --name=dev-vault -p 8200:8200 vault`
Get the root token and export it to VAULT_TOKEN.
2. `vault write auth/token/create ttl="120s" explicit_max_ttl="240s"`
3. `export KEY=$(vault list sys/leases/lookup/auth/token/create | tail -n 1)`
4. `vault write sys/leases/renew lease_id="auth/token/create/$KEY"`
You will receive a permission denied.

**Expected behavior**
The renew should work.

**Comment by ncabatoff** [comment]
Hi @Lasering,

It works fine if you use the auth/token/renew endpoint.  Looking at the code there are different codepaths invoked for renewing a secret vs renewing a token.  I believe it's working as intended.

**Comment by Lasering** [comment]
Renewing a token is different from renewing a lease. In order to renew a token I need to have the token, which means I can perform any operation that the token allows me. In contrast to leases which only allow me to renew or revoke them.

I created a auth token just as an example, but I could have created a PKI certificate with an associated lease and then try to renew that lease.

A root token is supposed to have **all** the permissions in Vault, so it does not make sense to get a permission denied. At most a bad request.

If the `sys/leases/renew` endpoint handles auth token leases differently then other leases then at least that should be mentioned in the API documentation.

**Comment by Lasering** [comment]
`auth/token/renew` is not equivalent to `sys/leases/renew`. The former renews the token directly (which as a consequence also renews its associated lease), the later renews the lease.

In other to renew a token, I must have the token. Whereas to renew a lease I only need the lease. The implication is that I can have a system/person renew leases without having access to the secrets the lease represents/points to. By preventing a lease of a token from being renewed, most of its value is removed for tokens, so why have leases for tokens?

**Comment by ncabatoff** [comment]
I'm not sure why you want to do this, can you elaborate on your use case please?  Normally only the token owner should be renewing their token.  If you want to delegate renewing, check out Vault Agent.

**Comment by Lasering** [comment]
I'm using Vault Agent. I don't see how can I use it to **delegate** renewing the token.

My use case is: I have an application that bootstraps new projects in my organization, among other things it mounts a AppRole and a PKI just for that application. Those engines/methods are mounted with a token that only the systems administrators of that projects have access. However they are mounted with a relatively short TTL, or more specifically its the token TTL that is short, about 6 months. Because the tokens are created via a token role I can easily list all of their leases (but not the tokens themselves). Thus by renewing their leases I can keep the AppRole and PKI mounted and alive (aka prevent them from being revoked), and I can do so in just one place without ever needing to grant access to the AppRole nor the PKI just the lease of the token that mounted them.

**Comment by ncabatoff** [comment]
Six months is not short.  And if you have something other than the token owner doing the renewing, aren't you defeating the purpose of having TTLs in the first place?

If you don't want your application to have to manage renewals itself, you could deploy a Vault Agent alongside it, which is configured with both auto_auth+caching enabled.  Then point your application at the Agent listener.  Tokens and dynamic secrets obtained via the Agent will be auto-renewed by the agent.  The only catch is that when the Agent exits it will forget about everything in its cache, and thus these secrets will eventually expire.

**Comment by Lasering** [comment]
Six months for a PKI is short. I have the Vault Agent with both auto_auth+caching, that is why I mount a AppRole dedicated for the application. Unfortunately the auto_auth does not work with tokens, so I cant have it renew the token that was used to mount the AppRole.

Besides the AppRole is used by every environment of that application, which one should do the renewing?

**Comment by ncabatoff** [comment]
> or more specifically its the token TTL that is short, about 6 months

The above is why I thought you were talking about 6 month token TTLs, not certificate TTLs.

> Unfortunately the auto_auth does not work with tokens

I'm not sure why you would want to use auto_auth with token inputs, as the point of auto_auth is to obtain tokens.  

>  so I cant have it renew the token that was used to mount the AppRole.

I find this very confusing.  "Mount the approle", to me, means "vault auth enable approle".  This is an operation that would be done once, with a highly privileged token, and the lifecycle of that token should have nothing to do with any of the rest of this.  In fact none of the setup of an approle - from enabling the auth plugin, to creating the role, or fetching the roleid and secretid - should rely on tokens that relate to the tokens that will be produced via that approle.

Based on the little I understand of your requirements, here's what I would do:

- deploy an agent instance for each application, configure the agent to use approle to authenticate
- configure the application to fetch secrets via its agent's listener, without providing a token
- allow the agent to worry about leases and tokens, the application remains completely ignorant of them
- couple the agent and application so that when the agent restarts, the application is either signalled or restarted, such that it re-requests whatever secrets it relies on

**Comment by Lasering** [comment]
I'm doing all of those points for the application. For that part I have no problems.

My problem is with:

> operation that would be done once, with a highly privileged token, and the lifecycle of that token should have nothing to do with any of the rest of this.

1. I create a new root token using the generate root token endpoints.
2. With that root token I create a new token role allowing orphan, periodic tokens, and with a policy allowing create,read,delete on `/sys/auth/serviceA-approle`
3. I create new token using that token role, lets call it `TokenA`
4. I revoke the root token.
5. I mount an AppRole at `serviceA-approle` using `TokenA`.

My problem is what should be the TTL of `TokenA` and what should renew `TokenA`?

I thought I had a solution:

-  Set the TTL to a relatively short value like 6 months. Image that serviceA might be operational for 5 years.
- Have a cron/service/etc list all the leases for a given path (remember the token has created via a token role). And renew all those leases. The path would be chosen in order to facilitate this.

But I cannot renew a lease of a token, I can only renew the token directly. The only way around that problem would be to save all the `TokenX`s in vault and then renew them directly.

In my approach I'm abiding to the principle of least power, that is the cron/service/etc that renews `TokenX` leases only has access to list leases of a given path and to renew a lease. But not to revoke a lease.

If I have to save the tokens in Vault, and somehow the cron/service is compromised, The attacker will be able to alter or delete the AppRole at `serviceA-approle` which surmounts to crashing production (and all the other environments) of serviceA.

**Comment by calvn** [comment]
Hi @Lasering,

It looks like `TokenA` in this case is used solely for enabling the AppRole auth method and nothing else. Is there a particular reason you need to keep the `TokenA` around? The auth mount is not disabled (nor its tokens removed) once `TokenA` gets revoked.

**Comment by Lasering** [comment]
It that also true for a secret engine? I also enable a PKI using `TokenA`.

**Comment by calvn** [comment]
That's correct, the token used to enable a secret engine is not tied to any of the credentials that gets generated by that mount afterwards.

**Comment by Lasering** [comment]
That means my setup is very complicated for no good reason.

I still think not being able to renew a token lease diminishes the utility and concept of a lease, at least concerning tokens. Having said that, and given the resistance to that idea I guess this issue can be closed.

**Comment by ncabatoff** [comment]
One last thought: you may be able to further simplify things by consolidating your one-approle-mount-per-application setup to use a single approle mount, with one role per application.

**Comment by Lasering** [comment]
That I cannot do. I have a role per deployment of the application.
