### ISSUE TITLE
Cannot connect to Vault from Debian: Buster and Stretch via HTTPv2.

### ISSUE THREAD

**Issue by robgolebiowski** [hashicorp/vault#7320]
**Describe the bug**
When trying to run command:
curl -v -L -H “X-Vault-Token: *******” --cacert vault_ca.crt --data ‘{“type”:“generic”}’ --request POST https://******/v1/sys/mounts/cicd/7c255bb1-a99c-11e9-b4e6-0800278dc04d_1
on Debian Buster or Stretch the call hangs. The same command passes without problems on: centos6,centos7,xenial,cosmic,Red Hat 8,disco,bionic.
The call does not hang if I enforce HTTP1.1 with --http1.1

**To Reproduce**
Run:
curl -v -L -H “X-Vault-Token: *******” --cacert vault_ca.crt --data ‘{“type”:“generic”}’ --request POST https://******/v1/sys/mounts/cicd/7c255bb1-a99c-11e9-b4e6-0800278dc04d_1
on Debian Buster or Stretch

**Expected behavior**
The call should be successful and does not hang.

**Environment:**
* Vault Server Version: 0.7.3
* Using Curl ver. 7.52.1
* Server Operating System/Architecture:
Debian Buster or Stretch

**Comment by jefferai** [comment]
This is almost certainly a curl version and/or build issue, not a Vault issue. Considering it's statically linked, if the same version of Vault passes with those other distributions it's likely the client at fault.

**Comment by michelvocks** [comment]
Closing since this doesn't seem to be a bug in Vault itself. @robgolebiowski feel free to open a new issue if this is still a thing.
