### ISSUE TITLE
Visual feedback when clicking "copy" in the UI

### ISSUE THREAD

**Issue by jrdemasi** [hashicorp/vault#7321]
**Feature Request:**

**Environment:**

* Vault Version: 1.2.1
* Operating System/Architecture: CentOS 7 

This is really a feature request for the UI - it would be nice to know if when you clicked the copy button if the copy was actually successful.  A tiny little JS popup that just said "Successfully copied" or something of the like would suffice.  If you're trying to grab a password in a hurry and that's the only means you have to access vault at the time, not having to wait until you paste the PW in to know you actually didn't click the button, or for some reason it didn't copy, would be a time saver.  I know this is a really minor thing, but it's also a fairly quick-to-implement thing if it's decided it should be accepted. 

Thanks for your consideration!

**Comment by aphorise** [comment]
@jrdemasi - are there particular places where it's still missing? - I see a visual cue now (info modal) indicating that a copy action was performed. Is this issue still applicable?

**Comment by jrdemasi** [comment]
Hi @aphorise!  Not sure what you're referring to with an info modal?  I just tested on 1.4.2 and there is no visual feedback when I click on copy next to a secret in the web UI.  Is it something specific to your browser/OS?

**Comment by aphorise** [comment]
@jraddington ok I see - you're referring to the copy button in the secrets view - such as in KV as show below. The only issue I'd see with adding it in (which I think may be possible) is that the typical success model that shows would only occur once for the last action (see Tools>unwrap for example) - give me a few days I'll look into it - I think I may be able to do it for the KV secrets view at least (not sure about all other engines).

<img width="814" alt="Screenshot 2020-08-24 at 18 16 15" src="https://user-images.githubusercontent.com/974854/91070306-dc7ca480-e636-11ea-86cc-62b2e7e6698b.png">

Example of success modal in unwrap section:
![Screenshot 2020-08-24 at 18 24 22](https://user-images.githubusercontent.com/974854/91070680-5b71dd00-e637-11ea-885c-38542efda68e.png)

**Comment by jrdemasi** [comment]
Ah yup - sorry for any confusion!  The same modal would be exactly what I'm talking about.  Appreciate your time!

**Comment by aphorise** [comment]
It was actually a lot easier than I thought. if there are no issues or conflicts elsewhere (that I may have overlooked) then I imagine the PR will be merged in the forthcoming releases.

![ui_copy-message-on-secrets](https://user-images.githubusercontent.com/974854/91080456-dfcb5c80-e645-11ea-8f13-deb4c1707c45.gif)
