### ISSUE TITLE
Getting a vault warning when connecting to mysql server

### ISSUE THREAD

**Issue by sahilmohile15** [hashicorp/vault#7332]
I am getting a warning when connecting with MySQL server on vault. the SQL server is not on the same system. 

```
WARNING! The following warnings were returned from Vault:

  * Read access to this endpoint should be controlled via ACLs as it will return the connection URL as it is, including passwords, if any.

```

for this process, I am using the command from the official documentation.
`vault write mysql/config/connection     connection_url="root:mypassword@tcp(Server's ip:3306)/"`

It would be really great if you can help me understand this warning and bypass the same.

**Comment by jefferai** [comment]
Hi,

It means that if someone reads the configuration you just wrote, the full URL will be returned, which will include passwords. So be careful who you grant read access to.

**Comment by sahilmohile15** [comment]
> Hi,
> 
> It means that if someone reads the configuration you just wrote, the full URL will be returned, which will include passwords. So be careful who you grant read access to.

Then What measures need to be taken to not to reveal. 
Also anyway I can bypass this warning.

**Comment by jefferai** [comment]
Simply don't give someone access. Vault is default-deny so unless you give someone access to read the config they don't have it.

**Comment by sahilmohile15** [comment]
Yes, I have not given access to anyone except those who require it. But does this mean data has been written? So no further procedure to connect is required. right?

**Comment by sahilmohile15** [comment]
Can you tell me how do I get to pass the warning? I get that I shouldn't give anyone access. But without connection settings like URL MySQL won't connect with the vault. How do I connect it without getting a warning.
