### ISSUE TITLE
blank page after Renew Token with OIDC auth. renew-self responds policies: null

### ISSUE THREAD

**Issue by pgassmann** [hashicorp/vault#7349]
**Describe the bug**

Token renewal with OIDC auth does not work properly in WebUI. After Token renewal, page reload returns blank page because of invalid data in Browser Local Storage.

**To Reproduce**
1. Login to Vault using OIDC
2. In User Menu click "Renew Token"
3. Reload Page
4. See white blank page

**Expected behavior**

Token renewal should work without side effects.

**Environment:**
* Vault Server Version: 1.2.2
* Vault CLI Version : no cli
* Server Operating System/Architecture: OIDC configured with Keycloak ad IdP

**Additional context**

* Problem not existing with other auth methods (local, ldap, token from ldap)

**Details**
Renew Token creates POST to `/v1/auth/token/renew-self` 
The Response contains auth data with `policies: null`
This policy is saved to the local Storage Key: `vault-token☃1`

REQUEST:

```json
fetch("https://vault.my-domain.ch/v1/auth/token/renew-self", {
    "credentials": "omit",
    "headers": {
        "accept": "*/*",
        "accept-language": "en,de-CH;q=0.9,de;q=0.8,de-DE;q=0.7,en-US;q=0.6,it;q=0.5",
        "cache-control": "no-cache",
        "pragma": "no-cache",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "x-vault-token": "s.REDACTED"
    },
    "referrer": "https://vault.my-domain.ch/ui/vault/secrets",
    "referrerPolicy": "no-referrer-when-downgrade",
    "body": null,
    "method": "POST",
    "mode": "cors"
});
```

RESPONSE

```json
{
    "request_id": "REDACTED",
    "lease_id": "",
    "renewable": false,
    "lease_duration": 0,
    "data": null,
    "wrap_info": null,
    "warnings": [
        "TTL of \"768h0m0s\" exceeded the effective max_ttl of \"767h59m50s\"; TTL value is capped accordingly"
    ],
    "auth": {
        "client_token": "s.REDACTED",
        "accessor": "REDACTED",
        "policies": null,
        "token_policies": [
            "default"
        ],
        "metadata": {
            "role": "puzzle"
        },
        "lease_duration": 2764790,
        "renewable": true,
        "entity_id": "REDACTED",
        "token_type": "service",
        "orphan": true
    }
}

```
LOCAL STORAGE DATA:

directly after login: Key: 'vault-token☃1'
```json
{
    "userRootNamespace": "",
    "displayName": "oidc-pgassmann",
    "backend": {
        "type": "token",
        "typeDisplay": "Token",
        "description": "Token authentication.",
        "tokenPath": "id",
        "displayNamePath": "display_name",
        "formAttributes": [
            "token"
        ]
    },
    "token": "s.REDACTED",
    "policies": [
        "default"
    ],
    "renewable": true,
    "entity_id": "REDACTED",
    "ttl": 2764799,
    "tokenExpirationEpoch": 1569251522720
}
```

After "Renew Token"

Key: 'vault-token☃1'
```json
{
    "userRootNamespace": "",
    "displayName": "oidc-pgassmann",
    "backend": {
        "type": "token",
        "typeDisplay": "Token",
        "description": "Token authentication.",
        "tokenPath": "id",
        "displayNamePath": "display_name",
        "formAttributes": [
            "token"
        ]
    },
    "token": "s.REDACTED",
    "policies": null,
    "renewable": true,
    "entity_id": "REDACTED",
    "ttl": 2764681,
    "tokenExpirationEpoch": 1569251523286
}
```

Local Storage with ldap login:

vault-ldap☃1
```json
{
    "userRootNamespace": "",
    "displayName": "pgassmann",
    "backend": {
        "type": "ldap",
        "typeDisplay": "LDAP",
        "description": "LDAP authentication.",
        "tokenPath": "client_token",
        "displayNamePath": "metadata.username",
        "formAttributes": [
            "username",
            "password"
        ]
    },
    "token": "s.REDACTED",
    "policies": [
        "admin",
        "base_admin",
        "base_secret_list",
        "default"
    ],
    "renewable": true,
    "entity_id": "REDACTED",
    "ttl": 2764800,
    "tokenExpirationEpoch": 1569251787173
}
```

Login with Token copied in LDAP Login 

after "Renew Token": 

Response Code is 204 (No Content)

'vault-token☃1':
```
{
    "userRootNamespace": "",
    "displayName": "ldap-pgassmann",
    "backend": {
        "type": "token",
        "typeDisplay": "Token",
        "description": "Token authentication.",
        "tokenPath": "id",
        "displayNamePath": "display_name",
        "formAttributes": [
            "token"
        ]
    },
    "token": "s.REDACTED",
    "policies": [
        "default"
    ],
    "renewable": true,
    "entity_id": "REDACTED",
    "ttl": 2764775,
    "tokenExpirationEpoch": 1569251786578
}
```

**Comment by pgassmann** [comment]
@kalafut You responded on other OIDC issues. Can you provide insight here? Is this a configuration issue of our OIDC or can you reproduce this issue with other OIDC installations?

**Comment by kalafut** [comment]
I’ve been chatting with @meirish and it looks like this affects more than OIDC. We’re still digging into.

**Comment by pgassmann** [comment]
@kalafut @meirish did you find something more specific? You wrote, that it also affects more than OIDC. What else? Is there a workaround that we can apply? Can we help somehow by providing more information or try something?

**Comment by yuanmwang-wf** [comment]
We hit the same issue in our set up. We discovered the issue was because after users are logged in via oidc, their self renew token requests were getting `policy:null` back and the UI is having a hard time when checking if the user is root.

Example response from vault server:
```
{
  "request_id": "514f599d-fa45-597c-02eb-afca45fd8f79",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": null,
  "wrap_info": null,
  "warnings": null,
  "auth": {
    "client_token": "TOKEN",
    "accessor": "2Lca2ejtHTCfXdRxQsVMjXtt",
    "policies": null,
    "token_policies": [
      "default"
    ],
    "metadata": {
      "role": "user"
    },
    "lease_duration": 14400,
    "renewable": true,
    "entity_id": "e4f506c5-22d8-ea66-1edd-ecb5f8f92786",
    "token_type": "service",
    "orphan": true
  }
}
```

In our setup we don't pass any token_policies to the oidc auth backend role, all users' policies were added through external identity group. We were able to work around this issue by adding a placeholder policy to token_policies of the oidc auth backend role (I checked this policy doesn't even have to exist in vault), after this the renewal requests are getting the right policy name so the UI can keep functioning.

**Comment by grantslape** [comment]
> In our setup we don't pass any token_policies to the oidc auth backend role, all users' policies were added through external identity group. We were able to work around this issue by adding a placeholder policy to token_policies of the oidc auth backend role (I checked this policy doesn't even have to exist in vault), after this the renewal requests are getting the right policy name so the UI can keep functioning.

We experienced this bug as well using the builtin `userpass` auth backend, (there is an entity for each user accessing the Vault Web UI).  We attach our policies to groups and then associate entities to those groups.  No entities accessing the Web UI have policies directly attached.

We worked around the issue by attaching a placeholder policy to each entity using the Web UI as follows.  Thus on token renewal, `token_policies` is no longer null:

```shell
vault write auth/userpass/users/firstname.lastname policies="dummy"
```

**Comment by eqrx** [comment]
I would like to confirm the reports. Since we explicitly do not want to assign policies directly to users we currently just purge to browsers local cache (which is tedious but oh well). Would be very nice if this could get fixed somehow. If I can help with that in any way, please do not hesitate to ask :)

**Comment by aosavitski** [comment]
> we currently just purge to browsers local cache 
it is easier to open a window in incognito mode:)

**Comment by peikk0** [comment]
Attaching an empty policy to all users does the trick, no need to purge the local cache every time.

**Comment by joshk0** [comment]
@peikk0 , could you be specific about what that means? My understanding is that every token should have the `default` policy. Does your suggestion mean that every token should be granted an extra blank policy in addition to the default one? And my guess is I would do this in the jwt auth provider using [token_policies](https://www.vaultproject.io/api/auth/jwt/index.html#inlinecode-token_policies-11) ?

Thanks!

**Comment by peikk0** [comment]
@joshk0 yes that's exactly that, I'm setting `token_policies` to a blank policy in the JWT/OIDC role:
```
❯ vault read auth/oidc/role/user | grep token_policies
token_policies             [user]
❯ vault policy read user
# Empty policy
```

**Comment by grantslape** [comment]
With `userpass` we get around this by attaching a non-existent policy to each entity that uses the Web UI:

```shell
vault write auth/userpass/users/firstname.lastname policies=dummy
```
