### ISSUE TITLE
vault operator migrate does not work with s3 storage source

### ISSUE THREAD

**Issue by vroy** [hashicorp/vault#7362]
**Describe the bug**

When running `vault operator migrate` with a s3 source, no keys are actually copied.

```
storage_source "s3" {
  bucket = "<source-bucket>"
  region = "us-east-1"
}

storage_destination "postgresql" {
  connection_url = "postgres://postgres:dev@127.0.0.1/postgres?sslmode=disable"
}
```

**To Reproduce**

1. Initialize Vault with S3 backend
2. Run `vault operator migrate` from s3 source to another backend

**Expected behavior**

I expected the keys to be copied to the destination backend.

**Environment:**

* Vault CLI Version (retrieve with `vault version`): 1.2.2
* Server Operating System/Architecture: Mac and Linux

**Additional context**

This works with Vault 1.1.4.

I think I've narrowed it down to this pull request / code block: https://github.com/hashicorp/vault/pull/7157/files#diff-114a477785f71145d9fc9bbdce32378bR269-R272

Some quick testing with python/boto3 demonstrates that setting Prefix to "/" returns nothing:

```
import boto3

s3 = boto3.client("s3", region_name="us-east-1")

response = s3.list_objects_v2(
    Bucket="<my-vault-bucket>",
    Prefix="/",
    Delimiter="/",
)
print(response["KeyCount"]) #=> 0

response = s3.list_objects_v2(
    Bucket="<my-vault-bucket>",
    Prefix="",
    Delimiter="/",
)
print(response["KeyCount"]) #=> 3
```

**Comment by ilatvala** [comment]
Confirm this same bug with vault 1.3 and CEPH S3 storage backend. Used vault 1.1.3 to migrate, since that works ok.
