### ISSUE TITLE
Container Storage Interface (CSI) plugin

### ISSUE THREAD

**Issue by jweissig** [hashicorp/vault#7365]
The Container Storage Interface (CSI) plugin could expose secrets on a volume within a pod. This will enable the injection of secrets into a running pod using a CSI plugin.

We are seeking community feedback on this thread.

**Comment by mayakacz** [comment]
cc @immutableT

**Comment by AndreasLudviksen** [comment]
What is the status of this ?
And what is the relation between this initiative and the KubeVault CSI Plugin?

In order to support rolling readonly keys in linux pods with Hashicorp Vault - what is your recommended approach ?

**Comment by malnick** [comment]
@AndreasLudviksen - Thanks for reaching out. If CSI is a preferred route, please take a look at the project being spearheaded by @ritazh and our provider for it: https://github.com/kubernetes-sigs/secrets-store-csi-driver

Our recommended approach for your use case is our Vault agent side-car injector: https://www.vaultproject.io/docs/platform/k8s/injector

The injector can work with a Vault running inside your K8s cluster, or externally. It will inject secrets into your pod into a in-memory volume, mimicking the same UX native K8s secrets have. Take a look at the docs and let me know if you have any questions.

**Comment by tamalsaha** [comment]
@AndreasLudviksen - KubeVault project is a community project maintained by https://appscode.com and it provides an end to end management experience for vault using CRDs. You can find some details here:

- https://kubevault.com/docs/v0.3.0/welcome/
- https://kubevault.com/docs/v0.3.0/concepts/what-is-kubevault/

**Comment by tomhjp** [comment]
I think the original question in this issue is answered. Any further questions, feel free to open an issue in https://github.com/hashicorp/secrets-store-csi-driver-provider-vault.
