### ISSUE TITLE
Support for consul style configurable statsd > metrics_prefix 

### ISSUE THREAD

**Issue by rajas2018** [hashicorp/vault#7370]
**Is your feature request related to a problem? Please describe.**
Need support for overriding metric name with metrics_prefix for vault monitoring, similar to Consul

**Describe the solution you'd like**
Adding configuration such as the following should result in statsd metrics being emitted with the prefix instead of default 'vault.*'

"telemetry": {
      "statsd_address": "<ADDRESS:PORT>",
      "disable_hostname": true,
      "metrics_prefix": "<Custom_vault_Prefix>"
    }

**Describe alternatives you've considered**
None

**Explain any additional use-cases**
This will enable us to capture metrics for team specific vault deployments

**Additional context**

**Comment by ncabatoff** [comment]
Fixed in #8340.
