### ISSUE TITLE
vault operator step-down timeout problems

### ISSUE THREAD

**Issue by andrejvanderzee** [hashicorp/vault#7373]
Hi,

When we issue `vault operator step-down`, Vault seems to revoke leases one-by-one sequentially (at least per auth mount). We share one vault for 15+ k8s clusters (mounted on 15+ paths)  that can be down at any moment. When we do ` vault operator step-down` when multiple k8s clusters are simply not running to save AWS cost,  vault step-down really tries to revoke leases _one-by-one_ like below in the logs, failing cause of timeout adding up for every revoke. During this step-down process, Vault from a load-balancer client  is simply down (timeouts waiting for headers) for half an hour until all revokes failed, even though we have 3 instances behind an AWS load-balancer. 

Would it be possible to revoke leases upon step-down per mount-path concurrently, instead of subsequently? 

Aug 27 22:48:48 ip-172-23-22-4 vault[889]: 2019-08-27T22:48:48.786Z [WARN]  core: stepping down from active operation to standby
Aug 27 22:49:32 ip-172-23-22-4 vault[889]: 2019-08-27T22:49:32.689Z [INFO]  expiration: revoked lease: lease_id=team10/k8s/pods/default/pki/issue/users/rXrONgeRo1uX3awa2TxpRIs0
Aug 27 22:50:19 ip-172-23-22-4 vault[889]: 2019-08-27T22:50:19.120Z [INFO]  expiration: revoked lease: lease_id=performance/k8s/pods/default/pki/issue/yolt-assistance-portal/23aZdNGizXztNZRJVMDKfQLd
Aug 27 22:50:49 ip-172-23-22-4 vault[889]: 2019-08-27T22:50:49.360Z [INFO]  expiration: revoked lease: lease_id=team9/k8s/pods/default/pki/issue/stubs/jmRIVGN4UFdG0tBM1yUAW4l8
Aug 27 22:50:49 ip-172-23-22-4 vault[889]: 2019-08-27T22:50:49.833Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/security-tst/k8s/cluster0/pods/cloudhsm/login/h58e5116c6878b24c0a8dc811543bfa17075415557099b83aee1dcb57127916c2
Aug 27 22:51:22 ip-172-23-22-4 vault[889]: 2019-08-27T22:51:22.675Z [INFO]  expiration: revoked lease: lease_id=integration/k8s/pods/default/pki/issue/yolt-app-bff/bLQZ72PGE1siBuIKpCayOImp
Aug 27 22:51:50 ip-172-23-22-4 vault[889]: 2019-08-27T22:51:50.855Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster1/pods/default/login/hc491fac50416b707f52e3315ed5032260139a15e75f0b2443aa2329e35be6408
Aug 27 22:51:54 ip-172-23-22-4 vault[889]: 2019-08-27T22:51:54.742Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster0/pods/default/login/h3947c4d5ef6b324ac8623fae7eed7a3cdc5e4ec8ae878b89c080afed5f39d673
Aug 27 22:52:00 ip-172-23-22-4 vault[889]: 2019-08-27T22:52:00.168Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster0/pods/default/login/h054822d566088e3596044554457f0fcf0a6c57e54d402393b00e878a2514dc44
Aug 27 22:52:06 ip-172-23-22-4 vault[889]: 2019-08-27T22:52:06.088Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=aws/sts/security-tst-cloudhsm-ssh/ZhT5sJlvPzPIHlT7GGhxAFZj
Aug 27 22:52:09 ip-172-23-22-4 vault[889]: 2019-08-27T22:52:09.893Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster1/pods/default/login/h4425620dab51afeda26e8dcac7e8456b934331f733fb005f15a0c040a7a94f22
Aug 27 22:52:24 ip-172-23-22-4 vault[889]: 2019-08-27T22:52:24.794Z [INFO]  expiration: revoked lease: lease_id=integration/k8s/pods/ycs/pki/issue/site-management/Phal7q6K28sJyJEwDo3nKKlV
Aug 27 22:52:25 ip-172-23-22-4 vault[889]: 2019-08-27T22:52:25.023Z [INFO]  expiration: revoked lease: lease_id=team8/k8s/pods/default/pki/issue/savings/FCp1XiY51BZOsJgar3JSVeFl
Aug 27 22:52:25 ip-172-23-22-4 vault[889]: 2019-08-27T22:52:25.679Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster1/pods/default/login/ha6c3da2dc143178580246b0be87eaeff6b7053257b50bb02ce20db76c0d25f16
Aug 27 22:52:35 ip-172-23-22-4 vault[889]: 2019-08-27T22:52:35.360Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster0/pods/default/login/hada6a7d1bbf3677b6d729ef7a85d63d68b96f04ea9c1b28cacaf5e2170972ee8
Aug 27 22:52:39 ip-172-23-22-4 vault[889]: 2019-08-27T22:52:39.266Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster0/pods/default/login/h19fe885204b8ce12ee296c439870d99c89b034b4173607c76cd34a2b6ea86922
Aug 27 22:52:44 ip-172-23-22-4 vault[889]: 2019-08-27T22:52:44.743Z [INFO]  expiration: revoked lease: lease_id=team1/k8s/pods/default/pki/issue/questionnaires/d78gmwatYUoyZcD7JpS1oFtR
Aug 27 22:52:52 ip-172-23-22-4 vault[889]: 2019-08-27T22:52:52.074Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/security-dta/k8s/cluster0/pods/cloudhsm/login/hb744108539f0e9c24afc50148db668f80db3f78f3fb67445e7f97a15b2631092
Aug 27 22:52:58 ip-172-23-22-4 vault[889]: 2019-08-27T22:52:58.429Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/integration/k8s/cluster0/pods/default/login/h4c3a5bccd1a141672401c05c7cf07261760c58d6ec0863a9e353121991b45158
Aug 27 22:52:59 ip-172-23-22-4 vault[889]: 2019-08-27T22:52:59.049Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/integration/k8s/cluster0/pods/ycs/login/h8e8d96d6c39be73d638826d4c904f947ba9ceec66539c513a5dbcc1e96fa7111
Aug 27 22:53:07 ip-172-23-22-4 vault[889]: 2019-08-27T22:53:07.517Z [INFO]  expiration: revoked lease: lease_id=team2/k8s/pods/default/pki/issue/gdpr/SVm5wUNSFbt3h5Z4G4Q6XwQt
Aug 27 22:53:53 ip-172-23-22-4 vault[889]: 2019-08-27T22:53:53.328Z [INFO]  expiration: revoked lease: lease_id=performance/k8s/pods/ycs/pki/issue/aggregation/CKZMzUx2CArzyp0Bk2mEBfQb
Aug 27 22:53:55 ip-172-23-22-4 vault[889]: 2019-08-27T22:53:55.949Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster0/pods/default/login/h64602da1b877f698c8893e75b5a66833d75d140b6c87c177e6a7ab541d3b03d4
Aug 27 22:53:59 ip-172-23-22-4 vault[889]: 2019-08-27T22:53:59.166Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster1/pods/default/login/h0bc43ebd42fd59c692e8d75751d9b1983fd875fb173140a9d4febdd8132b6da2
Aug 27 22:54:11 ip-172-23-22-4 vault[889]: 2019-08-27T22:54:11.359Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/integration/k8s/cluster1/pods/default/login/hf56300d792beee4f69dd0b470e37c90a74f5de5b1a882dc7dc6e35da673aa643
Aug 27 22:54:12 ip-172-23-22-4 vault[889]: 2019-08-27T22:54:12.089Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/integration/k8s/cluster1/pods/ycs/login/ha3cb3f8533466b79f4f335a50c898579ca7468a4e8ae5c77cae33400d69ee8d3
Aug 27 22:55:25 ip-172-23-22-4 vault[889]: 2019-08-27T22:55:25.871Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster1/pods/default/login/hb5d2d50b663c2f30ceefba2bd350a9db40b1193f9fc43258e11e85167191e156
Aug 27 22:55:50 ip-172-23-22-4 vault[889]: 2019-08-27T22:55:50.649Z [INFO]  expiration: revoked lease: lease_id=team7/k8s/pods/default/pki/issue/push/OBx0lhKyBv0rZGv3ULDfUkEJ
Aug 27 22:55:52 ip-172-23-22-4 vault[889]: 2019-08-27T22:55:52.733Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/security-tst/k8s/cluster0/pods/cloudhsm/login/h6fb36f7a9661bfce624c892a09bd5acce10de46eac89ba89a62fbdc2824b1866
Aug 27 22:56:19 ip-172-23-22-4 vault[889]: 2019-08-27T22:56:19.621Z [INFO]  expiration: revoked lease: lease_id=team6/k8s/pods/default/pki/issue/waiting-list/1r5GpyRKnNTZkUabU27wtDb7
Aug 27 22:56:47 ip-172-23-22-4 vault[889]: 2019-08-27T22:56:47.250Z [INFO]  expiration: revoked lease: lease_id=team5/k8s/pods/default/pki/issue/transaction-cycles/jpoU2f4pwql8IYJzNTFZOcfR
Aug 27 22:56:57 ip-172-23-22-4 vault[889]: 2019-08-27T22:56:57.406Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster1/pods/default/login/h46dd38d554a40da432cf5f715b4fe853aae7cf1e4d203645220a8d01b6bd8d97
Aug 27 22:57:10 ip-172-23-22-4 vault[889]: 2019-08-27T22:57:10.626Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster0/pods/default/login/h937116c4656e8f7d13c7ce1a9a3fb9e11efe3fc2249f23e3c7e28d353aa3a380
Aug 27 22:57:17 ip-172-23-22-4 vault[889]: 2019-08-27T22:57:17.049Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=aws/sts/security-tst-cloudhsm-ssh/MjsmEGfO9mKQPFFpPEbOXoFa
Aug 27 22:57:18 ip-172-23-22-4 vault[889]: 2019-08-27T22:57:18.586Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster0/pods/default/login/hbc26c606cfe7594cf7875a9888302d1b1b9c391cdfdbe55c01d114901128f6f3
Aug 27 22:57:24 ip-172-23-22-4 vault[889]: 2019-08-27T22:57:24.466Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster1/pods/default/login/h6d116d5505d478d7c028f71ddbe77d218eee289dde3aced8eb4cfbba488ee4cb
Aug 27 22:57:36 ip-172-23-22-4 vault[889]: 2019-08-27T22:57:36.579Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster1/pods/default/login/h549ab28c28cf731492196527597e31fddd7e139fd05b971de2846adca54ba834
Aug 27 22:57:48 ip-172-23-22-4 vault[889]: 2019-08-27T22:57:48.781Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster0/pods/default/login/h6a8b70d13121bb1e666a5fbccbc891a6b9c6a6f366cd5a8878176018448d20eb
Aug 27 22:57:52 ip-172-23-22-4 vault[889]: 2019-08-27T22:57:52.987Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/security-dta/k8s/cluster0/pods/cloudhsm/login/hd0ed98505909375059361b5df676d4d4431dca8e8a657cb65218b7ac086a5a08
Aug 27 22:57:55 ip-172-23-22-4 vault[889]: 2019-08-27T22:57:55.792Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=auth/performance/k8s/cluster0/pods/default/login/hde5b43b850bd14a666089f50fb717015d913cf840233dbda20577ddf78758a59
Aug 27 22:57:58 ip-172-23-22-4 vault[889]: 2019-08-27T22:57:58.000Z [ERROR] expiration: core context canceled, not attempting further revocation of lease: lease_id=aws/sts/performance-sre/qH4W72SMV279Kb1jqP03RtlF

**Comment by aphorise** [comment]
I believe this is no longer relevant from the time that you'd reported it - especially with improvements in the revocation logic introduced in 1.7.x and higher. It now strives to revoke in a more scheduled and graceful manner rather than in bulk or all at once.

@andrejvanderzee - can you kindly state if you've had a chance to reset since open this issue and if so do you agree it's not longer applicable?

**Comment by aphorise** [comment]
Closing due to no response / inactivity.
