### ISSUE TITLE
Agent auto auth JSON configuration

### ISSUE THREAD

**Issue by hamishforbes** [hashicorp/vault#7380]
The JSON configuration format for `auth_auth` in the Vault Agent is very confusing, initially doesn't appear to match the HCL syntax or the documentation.
Additionally there are no JSON examples available to help users figure out the correct JSON format.

Ideally config parsing in Vault Agent would be improved to support a more obvious JSON structure.
There should at least be JSON examples to the documentation.

The main issues are
 * Method is documented as an Object but is actually an Array with exactly 1 object within it
 * Sinks are documented as an Array of Objects ([`sink` Objects](https://www.vaultproject.io/docs/agent/autoauth/index.html#configuration-sinks-) is the implication here) but is actually an Array of Objects with only 1 key (`sink`) and the sink configuration is under that key.
* The error messages can be a bit cryptic, if you don't nest the sink configuration under the sink key in another object you just get a message saying that a sink of type "" is invalid. If you don't put the method inside an array you get told "one and only one "method" block is required"

Using the example HCL configuration from the Agent docs page

```
auto_auth {
        method "aws" {
                mount_path = "auth/aws-subaccount"
                config = {
                        type = "iam"
                        role = "foobar"
                }
        }

        sink "file" {
                config = {
                        path = "/tmp/file-foo"
                }
        }

        sink "file" {
                wrap_ttl = "5m" 
                aad_env_var = "TEST_AAD_ENV"
                dh_type = "curve25519"
                dh_path = "/tmp/file-foo-dhpath2"
                config = {
                        path = "/tmp/file-bar"
                }
        }
}
```

I would expect the JSON equivalent of this to be

```
"auto_auth": {
    "method": {
        "type": "aws",
        "mount_path": "auth/aws-subaccount",
        "config": {
            "type": "iam",
            "role": "foobar"
        }
    },
    "sinks": [
        {
            "type": "file",
            "config": {
                "path": "/tmp/file-foo"
            }
        },
        {
            "type": "file",
            "wrap_ttl": "5m",
            "aad_env_var": "TEST_AAD_ENV",
            "dh_type": "curve25519",
            "dh_path": "/tmp/file-foo-dhpath2",
            "config": {
                "path": "/tmp/file-bar"
            }
        }
    ]
}
```

but it's not, it's actually

```
"auto_auth": {
    "method": [
        {
            "type": "aws",
            "mount_path": "auth/aws-subaccount",
            "config": {
                "type": "iam",
                "role": "foobar"
            }
        }
    ],
    "sinks": [
        {
            "sink": {
                "type": "file",
                "config": {
                    "path": "/tmp/file-foo"
                }
            }
        },
        {
            "sink": {
                "type": "file",
                "wrap_ttl": "5m",
                "aad_env_var": "TEST_AAD_ENV",
                "dh_type": "curve25519",
                "dh_path": "/tmp/file-foo-dhpath2",
                "config": {
                    "path": "/tmp/file-bar"
                }
            }
        }
    ]
}
```

See mailing list thread here: https://groups.google.com/forum/?fromgroups=#!topic/vault-tool/lOHI8c4LBW4

Current docs: https://www.vaultproject.io/docs/agent/autoauth/index.html#configuration

**Comment by aphorise** [comment]
Hey @hamishforbes can you kindly confirm if this is still relevant?

**Comment by eikenb** [comment]
I just ran into a similar issue. I was generating a JSON config for vault agent and could only get it to complain about multiple auto-auth blocks. Translating the working HCL version manually and with various hcl2json scripts floating around and never got it working until I was pointed to this bug (thanks @VioletHynes). The issue for me was the required additional `sinks` block in the JSON version that isn't documented anywhere I could find.

Note that I didn't have the problem that the OP had with needing the extra `[]` around the method block.

HCL version..
```hcl
auto_auth {
    method {
        type = "approle"
        wrap_ttl = "4m"
        config = {
            role_id_file_path = "_role-id"
            secret_id_file_path = "_secret-id"
        }
    }
    sink {
        type = "sink"
        config = {
            path = "./vatoken.wrapped"
        }
    }
}
```

Final working JSON version...
```json
{
    "auto_auth" : {
        "method" : {
            "type" : "approle",
            "wrap_ttl" : "5m",
            "config" : {
                "role_id_file_path" : "_role_id",
                "secret_id_file_path" : "_secret_id"
            }
        },
        "sinks" : [
            {
                "sink" : {
                    "type" : "file",
                    "config" : {
                        "path" : "./vatoken.wrapped"
                    }
                }
            }
        ]
    }
}
```

**Comment by aphorise** [comment]
Hey @eikenb thanks for confirming.

My understanding is that the **`sinks`** array and that's expecting `sink` objects can be better detailed particularly for JSON; at the present it read reads:

> [sinks](https://www.vaultproject.io/docs/agent/autoauth#sinks) (array of objects: optional) - Configuration for the sinks

The singular case of **sink** in both HCL & JSON are properly parsed it seems - further to @rbjorklin confirmation.

#### OLD WAY

```json
"sink": [
  {
    "type": "file",
    "config": {
      "path": "/tmp/vault-token-via-agent"
    }
  }
]
```
Is the same as:
```HCL
sink "file" {
    config = {
        path = "/tmp/vault-token-via-agent"
    }
}
```

#### VS new way

```
"sinks" : [
  {
    "sink" : {
      "type" : "file",
      "config" : {
        "path" : "./vatoken.wrapped"
      }
    }
  }
]
```

```HCL
# // NO EXAMPLE OF `sinks` IN DOCS
```

I believe a documentation update is required here removing the `sink` in the 
current example all together and placing a `sinks` version as well as possibly
a JSON version? (maybe no json is needed if the HCL examples are clear)

WDYT Folks?

**Comment by mpalmi** [comment]
@aphorise I've gone ahead and updated the docs with some tweaks to show the different configurations for HCL and JSON. Please let me know if this seems sufficient, and I will go ahead and close the issue out if we're happy.

Thanks for all of the great discussion, everyone!

**Comment by eikenb** [comment]
Those changes look great to me. Thanks!
