### ISSUE TITLE
adding the -audit flag for pre mounted engines and secrets or audit device

### ISSUE THREAD

**Issue by FatnLazy** [hashicorp/vault#7387]
**Is your feature request related to a problem? Please describe.**
it frustrating that i can not know what group was created when/ what kind of policy was added to the group with what capabilities and it can be a pain when you have lots of groups (in my environments i have more then 50 group and around 100 policies) 

**Describe the solution you'd like**
i would like to be able to tune the pre-mounted secrets and engines with the -audit-non-hmac flag to see spesific fields that are associated with those engines/secrets as clear text and not in an encrypted mode 
 
**Describe alternatives you've considered**
an alternative solution can be to add the audit device the capability to receive this flag and decrypt all the requested fields without depending on a specific secret/engine  
best regards,
Alex.

**Comment by Cry0k** [comment]
hi team,
any updates regarding this issue?

**Comment by aphorise** [comment]
I feel that this is already possible by using for example [the file audit parameter: `log_raw`](https://www.vaultproject.io/docs/audit/file#log_raw). 

Hey @FatnLazy Alex - can you confirm if you agree and if so can you kindly consider marking this request as resolved?

**Comment by aphorise** [comment]
Closing due to no response. If relevant please re-open.
