### ISSUE TITLE
Vault and Okta OIDC configuration

### ISSUE THREAD

**Issue by brucedominguez** [hashicorp/vault#7389]
**Environment:**

* Vault Version: 1.2.2
* Operating System/Architecture: Ubuntu/AWS

Is there any documentation on integrating Okta OIDC with Vault. The only documentation available either relates to Okta auth (user/password) or Auth0 OIDC.

I am configuring the server via terraform with Okta terraform provider.

Below is a sandbox environment I am using to test the solution.
Main.tf
```
provider "okta" {
  org_name  = var.okta_org
  api_token = var.okta_api_key
  base_url  = var.okta_url
}

resource "okta_idp_oidc" "oidc" {
  name                  = "Vault-OIDC"
  acs_type              = "INSTANCE"
  acs_binding           = "HTTP-POST"
  authorization_url     = "${var.okta_org_url}/oauth2/v1/authorize"
  authorization_binding = "HTTP-REDIRECT"
  token_url             = "${var.okta_org_url}/oauth2/default/v1/token"
  token_binding         = "HTTP-POST"
  user_info_url         = "${var.okta_org_url}/oauth2/default/v1/userinfo"
  user_info_binding     = "HTTP-REDIRECT"
  jwks_url              = "${var.okta_org_url}/oauth2/default/v1/keys"
  jwks_binding          = "HTTP-REDIRECT"
  scopes                = ["openid"]
  client_id             = okta_app_oauth.my_app.client_id
  client_secret         = okta_app_oauth.my_app.client_secret
  issuer_url            = var.okta_org_url
  username_template     = "idpuser.email"
}


resource "okta_app_oauth" "my_app" {
  label = "Vault"
  type  = "web"
  grant_types = ["authorization_code", "refresh_token","implicit"]
  response_types = ["id_token", "code"]
  redirect_uris             = [
  "http://<VAULTADDRESS>:8250/oidc/callback",
  "http://<VAULTADDRESS>/ui/vault/auth/oidc/oidc/callback"
  ]
  post_logout_redirect_uris = [http://http://54.196.80.191:8200"]
  login_uri                 = "http://http://54.196.80.191:8200"
  groups                    = [okta_group.dev.id, okta_group.admin.id]
}

resource okta_user "User1" {
  first_name = "person"
  last_name  = "lastname"
  login      = "someone@email.com"
  email      = "someone@email.com"

  group_memberships = [okta_group.dev.id]
}

resource "okta_group" "dev" {
  name        = "Developer"
  description = "Developer Team"
}

resource "okta_group" "admin" {
  name        = "Vault Admins"
  description = "Vault Admins Team"
}

resource "okta_app_bookmark" "vault-app" {
  label  = "Vault"
  url    = http://http://54.196.80.191:8200
  groups = [okta_group.dev.id, okta_group.admin.id]
}

resource "vault_jwt_auth_backend" "oidc" {
  path               = "oidc"
  type               = "oidc"
  oidc_discovery_url = var.okta_org_url
  oidc_client_id     = okta_app_oauth.my_app.client_id
  oidc_client_secret = okta_app_oauth.my_app.client_secret
  bound_issuer       = "${var.okta_org_url}/oauth2/default"
}

resource "vault_jwt_auth_backend_role" "this" {
  backend               = vault_jwt_auth_backend.oidc.path
  role_type             = "oidc"
  role_name             = "Developer"
  bound_audiences       = [okta_app_oauth.my_app.client_id]
  user_claim            = "sub"
  oidc_scopes           = ["profile", "email", "openid"]
  token_policies        = ["default", vault_policy.admin.id, vault_policy.dev.id, vault_policy.dev-aws.id]
  allowed_redirect_uris = ["http://localhost:8250/oidc/callback", 
  http://http://54.196.80.191:8200/ui/vault/auth/oidc/oidc/callback"]
  token_ttl                   = 86400
  token_max_ttl               = 86400
  claim_mappings = {
    email = "email"
  }
}

## Vault Polices
data "vault_policy_document" "admin" {
  rule {
      path  = "*"
      capabilities = ["create", "read", "update", "delete", "list", "sudo"]
      description = "allow all for vault admins"
  }
}

resource "vault_policy" "admin" {
  name   = "example_policy"
  policy = data.vault_policy_document.admin.hcl
}

data "vault_policy_document" "dev-aws" {
  rule {
      path  = "aws/creds/dev-role"
      capabilities = ["read"]
      description = "allow dev aws access"
  }
}

data "vault_policy_document" "dev" {
  rule {
      path  = "/secret/*"
      capabilities = ["read", "list"]
      description = "allow dev secrets access"
  }
}
resource "vault_policy" "dev" {
  name   = "example_policy"
  policy = data.vault_policy_document.dev.hcl
}
```
When I attempt to log in I get a 404 error from Okta. I know it will be a configuration on the App side (maybe) but I am stuck trying to find resources to help.

Thanks in advance!

**Comment by kalafut** [comment]
Hi. Have you reviewed the (admittedly brief) Okta setup notes for the JWT/OIDC auth method at: https://www.vaultproject.io/docs/auth/jwt_oidc_providers.html#okta

Okta defintely works with the JWT auth method, but I've never configured it as part of a full Terraform setup. You may want to try setting up Vault+OIDC Auth directly with some known-good Okta creds/settings, verify that works, and then pull in more of the Terraform configuration.

There are some more advanced OIDC troubleshooting steps, but if you're getting a 404, that sounds like an `oidc_discovery_url` for your org being incorrectly determined/populated.

**Comment by brucedominguez** [comment]
Thanks I will try and set it up manually and pull the config from there.

**Comment by ethindp** [comment]
Going to bring this issue back briefly to ask exactly how I would go about setting up OIDC. I've set the discovery URL to my okta domain (which was tricky to find since its listed nowhere). I set my client secret and client ID, and then my default role. But OIDC still doesn't work (most likely because the OIDC provider instructions were completely useless). After I save the client secret and Id... what do I do after that? If I am indeed required to create roles, how do I even create that role? What parameters should I set up?
I'm asking these questions because I should not have to diagnose and debug these problems without any kind of assistance and it is appalling that there is literally zero documentation for Okta in particular but there is for most of the other providers.

**Comment by janmasarik** [comment]
@brucedominguez were you successful in implementing Okta through OIDC? 😅

**Comment by brucedominguez** [comment]
No luck so far. I had to park the project.

**Comment by kalafut** [comment]
The "Issuer URI" is shown in the main list of "Authorization Servers" in Okta and is what you'd use for the `oidc_discovery_url`.  On the Vault side you'll need to set up some other parameters. I'd refer to the main [OIDC docs](https://www.vaultproject.io/docs/auth/jwt.html) and [tutorial](https://learn.hashicorp.com/vault/identity-access-management/oidc-auth) (which uses Auth0, but many concepts are the same) for more background on this.

The providers instruction page is community supported and assumes general familiarity with Vault, the provider, and OIDC. But OIDC setup is often complex, and sometimes highlighting an essential setting can help people get started. Okta's setup doesn't have too many settings you need to worry about just to get going.

Besides the 404, are there other errors?

**Comment by ethindp** [comment]
I can't even get it to work. I set up the issuer and creds, then try
to log in. The vault immediately denies me claiming that an OIDC role
is not allowed. When I try without a role and without a default role,
it complains that no default role is available.

On 10/17/19, Jim Kalafut <notifications@github.com> wrote:
> The "Issuer URI" is shown in the main list of "Authorization Servers" in
> Okta and is what you'd use for the `oidc_discovery_url`.  On the Vault side
> you'll need to set up some other parameters. I'd refer to the main [OIDC
> docs](https://www.vaultproject.io/docs/auth/jwt.html) and
> [tutorial](https://learn.hashicorp.com/vault/identity-access-management/oidc-auth)
> (which uses Auth0, but many concepts are the same) for more background on
> this.
>
> The providers instruction page is community supported and assumes general
> familiarity with Vault, the provider, and OIDC. But OIDC setup is often
> complex, and sometimes highlighting an essential setting can help people get
> started. Okta's setup doesn't have too many settings you need to worry about
> just to get going.
>
> Besides the 404, are there other errors?
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/hashicorp/vault/issues/7389#issuecomment-543405397


-- 
Signed,
Ethin D. Probst

**Comment by kalafut** [comment]
Are you setting up a Vault role, similar to: https://learn.hashicorp.com/vault/identity-access-management/oidc-auth#cli-command-1 (step 3)? Also, it would be helpful if you'd paste commands and error messages.

**Comment by jeremie0** [comment]
@brucedominguez not sure if you've fixed this part of your config yet, but you have double http:// in  your url, allowed_redirect_uris, post_logout_redirect_uris,   login_uri etc.   

You also need to setup the claim on the okta side to include the groups.  That can be done with okta_auth_server_claim at the auth server level (See https://github.com/articulate/terraform-provider-okta/blob/master/website/docs/r/auth_server_claim.html.markdown and  https://github.com/articulate/terraform-provider-okta/blob/f10ddb1fc5f41460e8b201e19e41cfc0f2615597/examples/okta_auth_server_claim/basic_updated.tf  ) or at the okta_app_oauth level with the profile element, see https://github.com/articulate/terraform-provider-okta/blob/master/examples/okta_app_oauth/group_for_groups_claim.tf.

**Comment by catsby** [comment]
Hello - we haven't heard anything for a few weeks, so I'm going to close this for now. For future questions or discussion such as this, please checkout https://discuss.hashicorp.com/c/vault

Thanks!

**Comment by gh-kgangineni** [comment]
Hi There - 
I was able to setup Okta OIDC app and integrate with Vault. I followed Auth0 example given in the vault docs. The second part of the doc talks about passing group information . What value should I pass in the **groups_claim** , when I create an oids role 
Below is the example from the doc with Auth0 as example
vault write auth/oidc/role/kv-mgr \
        bound_audiences="$AUTH0_CLIENT_ID" \
        allowed_redirect_uris="http://127.0.0.1:8200/ui/vault/auth/oidc/oidc/callback" \
        allowed_redirect_uris="http://localhost:8250/oidc/callback" \
        user_claim="sub" \
        policies="reader" \
        groups_claim="https://example.com/roles"
