### ISSUE TITLE
No "Success" output after running "vault kv put" for a json file secret upload

### ISSUE THREAD

**Issue by econn9** [hashicorp/vault#7392]
The problem related to this is that I found that for one certain type of kv put call, no output at all was offered onSuccess. I found out by checking the web UI that it was in fact successful. 

A message in terminal that says my data was successfully written, so i dont have to wonder if it failed and have to go check the web UI. 

Only alternative is checking the web page after each command ... if this double check has to happen, it should wait maybe til the end when all commands have been run in a session at the least. 

**Additional context**
the command i ran looked like:
`vault kv put -format=json secret/my-path/example @s.json`

**Comment by jefferai** [comment]
You're asking it for json formatted output but the call results in a 204 so there is no output. Outputting some success string would not be valid json, and the vault CLI won't override the response when using json formatting.
