### ISSUE TITLE
Vault CLI: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by chrisghill** [hashicorp/vault#7400]
**Describe the bug**
I posted this in the Google group but didn't get any responses. I'm just trying to run a simple vault status command, but I keep getting:

```
$ vault status
Error checking seal status: Get https://vault.our.internal.domain.io/v1/sys/seal-status: x509: certificate signed by unknown authority
```

**To Reproduce**
I've followed these guides:
https://testdriven.io/blog/running-vault-and-consul-on-kubernetes/
https://github.com/sethvargo/vault-kubernetes-workshop
https://github.com/kelseyhightower/vault-on-google-kubernetes-engine

That is, I've run exactly these commands (pulled from my history):
```
cfssl gencert -initca config/ca-csr.json | cfssljson -bare ca
cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=config/ca-config.json -profile=default config/consul-csr.json | cfssljson -bare consul
cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=config/ca-config.json -profile=default config/vault-csr.json | cfssljson -bare vault
```

I've also created a "combined" or "full chain"(???) file by running:
```
cat vault.pem ca.pem > vault-combined.pem
```
(This was in Kelsey Hightowers guide)

Additionally, I've used openssl to verify my vault certificates:
```
$ openssl verify -verbose -CAfile certs/ca.pem certs/vault.pem
certs/vault.pem: OK
$ openssl verify -verbose -CAfile certs/ca.pem certs/vault-combined.pem
certs/vault-combined.pem: OK
```

For my vault configuration, the listener looks like so:
```
      "listener": [{
        "tcp":{
          "address":"[::]:8200",
          "cluster_address":"[::]:8201",
          "tls_cert_file": "/etc/vault/tls/vault-combined.pem",
          "tls_key_file": "/etc/vault/tls/vault-key.pem",
        },
      }]
```
Note that for tls_cert_file I've tried both vault.pem and vault-combined.pem.  Both of them cause the "signed by unknown authority" error.

For my local environment, I've set:
```
export VAULT_ADDR="https://vault.our.internal.domain.io"
export VAULT_CACERT="/path/to/certs/ca.pem"
#export VAULT_CLIENT_CERT="/path/to/certs/vault.pem"
#export VAULT_CLIENT_KEY="/path/to/certs/vault-key.pem"
export VAULT_TOKEN=<redacted>
```
Note that I've tried commenting/uncommenting those VAULT_CLIENT_CERT/KEY values and both fail.

**Expected behavior**
Vault CLI commands to work without certificate signing errors.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.2.2
* Vault CLI Version (retrieve with `vault version`): 1.2.2
* Server Operating System/Architecture: Kubernetes (Kops Debian)

Vault server configuration file(s):

```hcl
{
      "listener": [{
        "tcp":{
          "address":"[::]:8200",
          "cluster_address":"[::]:8201",
          "tls_cert_file": "/etc/vault/tls/vault-combined.pem",
          "tls_key_file": "/etc/vault/tls/vault-key.pem",
        },
      }],

      "seal": {
        "awskms": {
          "region": "us-west-2",
          "kms_key_id": "12345678-1234-1234-1234-1234567890ab"
        }
      },

      "storage": {
        "consul": {
          "address": "localhost:8500",
          "path": "vault/",
          "disable_registration": "true",
          "ha_enabled": "true"
        }
      }
    }
```
Also ENV values:
```
        - name: VAULT_API_ADDR
          value: "https://$(POD_IP):8200"
        - name: VAULT_CLUSTER_ADDR
          value: "https://$(POD_IP):8201"
        - name: VAULT_LOG_LEVEL
          value: "debug"
        - name: VAULT_UI
          value: "true"
```

**Additional context**
If I add `VAULT_SKIP_VERIFY` to my local ENV then it passes just fine.  However, Vaults own documentation says not to do this as it [voids vaults security model](https://www.vaultproject.io/docs/commands/#vault_skip_verify)

I'm at a loss here. I've followed multiple guides exactly, I've regenerated certs, I've tried every combination of settings I can think of. I'm not a TLS cert expert by a long shot, so I'm hoping its not just something simple. Any help would be appreciated.

**Comment by chrisghill** [comment]
I got a response on my Google groups topic.  The issue had nothing to do w/ Vault, and had to do w/ my service definition in front of the Vault statefulset.  Here is the updated and working service.yaml:

```
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
    external-dns.alpha.kubernetes.io/hostname: vault.our.internal.domain.io
spec:
  type: LoadBalancer
  ports:
    - name: api
      port: 443
      targetPort: api
    - name: cluster
      port: 8201
      targetPort: cluster
  selector:
    app: vault
```

The important line is: `service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl`
Before I had set that to "https" thinking that it meant the AWS load balancer "pass through" the TLS session and allow Vault to terminate.  But according to the docs (https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#load-balancers):

> "If http (default) or https, an HTTPS listener that terminates the connection and parses headers is created. If set to ssl or tcp, a “raw” SSL listener is used"

What I was really looking for was "ssl".  I updated the service definition and now certificates are working fine.  Google groups topic is here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/vault-tool/NuSnzyiFTM0

Since this issue is resolved, I'll close it.

**Comment by neelshah1617** [comment]
```
[root@vault-dal13-01 ~]# vault status
Error checking seal status: Get https://xx.x.x.xx:8200/v1/sys/seal-status: x509: certificate signed by unknown authority
```

Order is important while writing combined certificate, last issuing Intermediate cert comes first (LIFO) and then root cert. Solution references: # https://knowledge.digicert.com/solution/SO12792.html

```
[root@vault ~]# cat intermediate.cert.pem  CA_cert.crt > Combined_CA.crt

[root@vault ~]# openssl verify -verbose -CAfile Combined_CA.crt  /path/to/your/cert/vault.certificate.pem
/path/to/your/cert/vault.certificate.pem: OK

[root@vault ~]# cp Combined_CA.crt /etc/pki/ca-trust/source/anchors/
[root@vault anchors]# update-ca-trust

```
