### ISSUE TITLE
Vault not working with go version go1.10.4 linux/amd64 Ubuntu 18.04

### ISSUE THREAD

**Issue by saydulk** [hashicorp/vault#7402]
Hello, i was trying to install Vault into Ubuntu 18.04 with go version go1.10.4 linux/amd64 using https://learn.hashicorp.com/vault/getting-started/install but i fail.

**Comment by chrishoffman** [comment]
Vault requires go 1.12 or later.  This documentation refers to using the binary version of Vault instead of trying to compile it yourself.
