### ISSUE TITLE
How to create an token that can revoke credential for an lease?

### ISSUE THREAD

**Issue by 2994186010** [hashicorp/vault#7406]
I can revoke a lease by http api. However,  the X-Vault-Token need to be set to root token. I think that it is unsafe to distribute the root token. So I want to create an policy for the path "sys/leases", the policy is as following.

`path "sys/leases"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}`

According to the policy, I create a token. However, using this token, I can not revoke lease, the response is as following.

`{"errors":["1 error occurred:\n\t* permission denied\n\n"]}`

**Comment by michelvocks** [comment]
Hi @2994186010!

To revoke a lease, the API endpoint `sys/leases/revoke` should be used. Your described ACL policy only provides access to `sys/leases` but not `sys/leases/revoke`. It should work when you change your policy to the following:

```
path "sys/leases/revoke" { 
  capabilities = ["create", "read", "update", "list"] 
}
```

You can also replace `revoke` with an asterisk `*` to allow all API endpoints below `sys/leases`.

Cheers,
Michel
