### ISSUE TITLE
policies set to accept, but the users are denied

### ISSUE THREAD

**Issue by TheImmortalOne** [hashicorp/vault#7417]
I am having issues trying to setup a cubbyhole for each of the users - a place for them to store secrets that just wont expire.

After a ton of tinkering with the policies, I saved this overzealous one:
```
# Grant permissions on user specific path
path "private/data/poltest/*" {

    capabilities = [ "create", "update", "read", "delete", "list" ]
}
# Grant permissions on user specific path
path "private/data/poltest" {

    capabilities = [ "create", "update", "read", "delete", "list" ]
}
# For Web UI usage
path "private/metadata" {
  capabilities = ["list"]
}
# For Web UI usage
path "private/metadata/poltest" {
  capabilities = ["list"]
}
```

Then i saved a secret in a subpath, one that seemingly I can't access (!):
```
± vault kv put private/poltest/folder1/folder2/secret secret=buhuhu
Key              Value
---              -----
created_time     2019-09-04T09:06:58.968528593Z
deletion_time    n/a
destroyed        false
± vault kv list private/poltest/
Keys
----
folder1/
gigicu
± vault kv list private/poltest/folder1
Error listing private/metadata/poltest/folder1: Error making API request.
URL: GET https://URLHERE:8200/v1/private/metadata/poltest/folder1?list=true

Code: 403. Errors:
* 1 error occurred:
	* permission denied
```

But then again:
```
# vault token capabilities private/data/poltest
create, delete, list, read, update
# vault token capabilities private/data/poltest/folder1
create, delete, list, read, update
# vault token capabilities private/data/poltest/folder1/folder2
create, delete, list, read, update
```

For Vault-UI, the error is the classis 'no permissions' one:
`You don't have access to private/poltest/folder1/. If you think you've reached this page in error, please contact your administrator.`

**Comment by ncabatoff** [comment]
Hi @TheImmortalOne,

You've almost got it.  Note that the `metadata` policy paths relate to `list` and the `data` paths relate to all the other capabilities.  So the fact that you have permission to list `/private/data/poltest/folder1` is irrelevant, what you need is permission to list `/private/metadata/poltest/folder1`.  If you add a rule

```
path "private/metadata/poltest/*" {
  capabilities = ["list"]
}
```

your `vault kv list private/poltest/folder1` command should work.

**Comment by TheImmortalOne** [comment]
i could've sworn i've done that already. And it works in Vault-UI too! Yoy, i feel like an idiot.


Now I need to get it to work with entities :D Appreciate the help!

**Comment by TheImmortalOne** [comment]
Thanks to @ncabatoff's comment, I've gotten to a point where I can pin each created user to an entity with its name, and then this policy gives them access to 'the personal cubbyhole':

```
## Allow access to the personal space under the 'personal/' path:
path "personal/data/{{identity.entity.name}}/*" {
  capabilities = ["create", "update", "read", "delete"]
}

#For WebUI
path "personal/metadata/{{identity.entity.name}}/*" {
  capabilities = ["list"]
}

path "personal/metadata" {
  capabilities = ["list"]
}
```

The issue now, however, is that user is not allow for users to delete the secrets or their versions - what am I doing wrong? A somewhat similar behavior seems to happen for other kv2 paths, where users can delete from the cli, but not from WebUI, even though they have access to list the metadata.

**Comment by ncabatoff** [comment]
As per the [kv-v2 docs](https://www.vaultproject.io/docs/secrets/kv/kv-v2.html), it should be:

To grant a policy the permissions to delete the latest version of a key:
```
path "personal/data/{{identity.entity.name}}/*" {
  capabilities = ["delete"]
}
```

To allow the policy to delete any version of a key:
```
path "personal/delete/{{identity.entity.name}}/*" {
  capabilities = ["update"]
}
```

To allow a policy to permanently remove all versions and metadata for a key:
```
path "personal/metadata/{{identity.entity.name}}/*" {
  capabilities = ["delete"]
}
```

**Comment by catsby** [comment]
Hello - we haven't heard anything for a few weeks, so I'm going to close this for now. For future questions such as this, please checkout https://discuss.hashicorp.com/c/vault

Thanks!
