### ISSUE TITLE
LDAP Group and User policies accept undocument lists

### ISSUE THREAD

**Issue by luke-clifton** [hashicorp/vault#7426]
Doc: https://www.vaultproject.io/api/auth/ldap/index.html#policies

Docs claim that a string type, containing comma separated policies is required, observations seem to suggest that a JSON list works as well.

Is this supported, if so, can it be documented.

Is the same true for `groups` in the LDAP user request?

**Comment by jefferai** [comment]
In most places you can use a JSON list in place of comma separated strings. As we build more documentation automatically we hope to surface this in more places as right now it requires manually updating every single API document. If you want it updated here feel free to submit a PR!

**Comment by luke-clifton** [comment]
Is there a list of places that it is accepted somewhere? It doesn't seem to work with groups.
