### ISSUE TITLE
More intuitive tls_disable

### ISSUE THREAD

**Issue by njsaunders** [hashicorp/vault#743]
Setting tls_disable to 0 or false currently disables TLS (As per the documentation), but this isn't particularly intuitive - Either the directive should take no arguments and be a statement, but if you can assign a value to it we should do the right thing - I've just spent 20 minutes figuring out why tls_disable=0 doesn't enable TLS.....

**Comment by jefferai** [comment]
The documentation is pretty clear on this point:

> tls_disable (optional) - If non-empty, then TLS will be disabled.

This isn't described as a boolean field. As it says, setting it to `0` or `false` means that it is not empty. If you do not want TLS disabled, simply do not set this option.
