### ISSUE TITLE
Patch without read access

### ISSUE THREAD

**Issue by fortman** [hashicorp/vault#7437]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
We want to be able to have certain groups in our company to have write access to a vault path, but not read access.  This is currently possible, but a write action to that path overwrites the entire json blob.  I would be nice to have the cli patch functionality work with only update/create.  Right now I think it needs read access.  It would be nice to have this same functionality in the gui.

**Describe alternatives you've considered**
Thought about storing each individual secret in it's own path, but that is very heavy and doesn't work with certain vault clients (springboot for example)

**Explain any additional use-cases**
A 'secrets maintainer' in our company can write new values to an existing json blob at a path in vault, and not erase the values that are already there.  The value would be added/updated in the json blob, and the other values in the json would still be there.  All of this while only have update/create policy permissions to that path.

**Additional context**

**Comment by ncabatoff** [comment]
Hi @fortman ,

This feature has been requested several times but for various reasons I don't think we're going to implement it, sorry.  There's some discussion about why in #182 and #1468 if you're interested.
