### ISSUE TITLE
vault kv get does not work on approle ids

### ISSUE THREAD

**Issue by juliantaylor** [hashicorp/vault#7440]
Using vault kv get on an approle id gets denied in the preflight check on sys/internal/ui/mounts
vault read does work and the token has an appropriate read policy.

While kv get should probably not be used on approles it is still relevant as the `sys/internal/ui/mounts` can be used by vault api users to determine if one needs the kv version 1 or version 2 api.
So having the `sys/internal/ui/mounts` path working for approles would simplify writing api clients.

**To Reproduce**
1. vault auth enable approle
2. vault write auth/approle/role/my-role secret_id_ttl=10m
3. create policy
```
$ cat policy.hcl 
path "auth/approle/role/my-role/role-id" {
    capabilities = [
        "read",
    ]
}
vault policy write testpolicy policy.hcl
```

3. create token vault token create -policy=testpolicy
4. read with kv get and that token

```
$ vault token lookup
Key                 Value
---                 -----
accessor            xTwvyLdXoCtPK8Wjx3F2KMwM
creation_time       1567770185
creation_ttl        768h
display_name        token
entity_id           n/a
expire_time         2019-10-08T13:43:05.08440166+02:00
explicit_max_ttl    0s
id                  s.cM2MmeYbYOPMsoBJcjsB5Idx
issue_time          2019-09-06T13:43:05.084401515+02:00
meta                <nil>
num_uses            0
orphan              false
path                auth/token/create
policies            [default testpolicy]
renewable           true
ttl                 767h57m51s
type                service

$ vault kv get auth/approle/role/my-role/role-id
Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/internal/ui/mounts/auth/approle/role/my-role/role-id
Code: 403. Errors:

* preflight capability check returned 403, please ensure client's policies grant access to path "auth/approle/role/my-role/role-id/"
```

vault read works:

```
$ vault read auth/approle/role/my-role/role-id
Key        Value
---        -----
role_id    c54c7a1a-bbc5-ef66-7ae2-e79e70d71d94
```

**Expected behavior**
vault read and vault kv get works on approle ids
This effectively translates to reads on `sys/internal/ui/mounts/auth/approle/role/my-role/role-id` working with a policy that gives access to that path.

**Environment:**
* Vault Server Version (retrieve with `vault status`): v1.2.2
* Vault CLI Version (retrieve with `vault version`): v1.2.2
* Server Operating System/Architecture: ubuntu 18.04

**Comment by jefferai** [comment]
Approle isn't a KV backend, so `vault kv <anything>` won't work. It's _specific_ to KV mounts, of either version 1 or 2.

**Comment by juliantaylor** [comment]
sure but if `sys/internal/ui/mounts` works on auth paths it would simplify writing api clients and also make kv get work on the auth paths so you don't need to always check which command you need for which path.
