### ISSUE TITLE
How to configure vault to talk to multiple k8s clusters

### ISSUE THREAD

**Issue by sidheshdivekar29** [hashicorp/vault#7460]
https://learn.hashicorp.com/vault/identity-access-management/vault-agent-k8s
The link below show how to configure one k8s host so that vault can talk to it.

$ vault write auth/kubernetes/config \
        token_reviewer_jwt="$SA_JWT_TOKEN" \
        kubernetes_host="https://$K8S_HOST:8443" \
        kubernetes_ca_cert="$SA_CA_CRT"

We have multiple k8s cluster to whom vault needs to talk.
If I use the "vault write auth/kubernetes/config" above for each of them it just overwrites to old one. Using any other path like "vault write auth/kubernetes/config/k8s1" does not work.

How to configure more that one k8s cluster in vault so that vault can reach back to them.

Thanks!

**Comment by pkrolikowski** [comment]
You need to set `auth` backend per k8s cluster. In order to do that set `-path=<string>` parameter per cluster.

**Comment by sidheshdivekar29** [comment]
Cool that made the tricks. Putting down the commands here so that others can have then handy.

  vault auth enable -path=k8s1 kubernetes (enable auth backend for cluster 1)
  vault  auth enable -path=k8s2 kubernetes (enable auth backend for cluster 2) 

Configure Vault to talk to Kubernetes cluster k8s1
vault write auth/k8s1/config token_reviewer_jwt="$_JWT_TOKEN"   \    kubernetes_host="https://$K8S_HOST:8444" kubernetes_ca_cert="$SA_CA_CRT"

Configure Vault to talk to Kubernetes cluster k8s2
vault write auth/k8s2/config token_reviewer_jwt="$_JWT_TOKEN"   \    kubernetes_host="https://$K8S_HOST:8444" kubernetes_ca_cert="$SA_CA_CRT
