### ISSUE TITLE
Vault Agent Cache Auto-Auth SSRF Protection

### ISSUE THREAD

**Issue by briandbecker** [hashicorp/vault#7463]
**Is your feature request related to a problem? Please describe.**
When Vault Agent is used for [local cache](https://www.vaultproject.io/docs/agent/caching/index.html) with Auto-Auth Token this opens up the potential for exposure to SSRF vulnerabilities in the parent application.

**Describe the solution you'd like**
Parameter to require a request header to be set when interacting with Vault cache service that could be checked in the cache handler.  This would **not** be considered a secret, rather indicates that the request was made with the intention of retrieving vault values.  While it doesn't eliminate the problem entirely it does add a layer of protection against SSRF.

This solution is similar in nature to what [Azure](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service) and [GCP](https://cloud.google.com/compute/docs/storing-retrieving-metadata) do for their metadata access.

**Describe alternatives you've considered**
None

**Explain any additional use-cases**

**Additional context**
AWS does not do this request header validation and it appears from the publicly released information to have been a contributing factor in the Capital One breach.

**Comment by briankassouf** [comment]
Hi @briandbecker thanks for the report, this is a good idea. We will try and get it in for the 1.3 release.

**Comment by mjarmy** [comment]
I've created a PR that addresses this issue: #7627

**Comment by mjarmy** [comment]
@briandbecker The PR was approved.  I'll close this issue soon since I believe it will be addressed in 1.3

**Comment by briandbecker** [comment]
@mjarmy looks great! Thanks for the amazing work... :shipit:
