### ISSUE TITLE
AWS Auth Client/Server inconsistency in region configuration

### ISSUE THREAD

**Issue by hamishforbes** [hashicorp/vault#7466]
When using AWS authentication the Vault CLI, with no additional configuration, looks up your local region from environment/metadata and signs the login request with that region.
The Vault server however uses `us-east-1` by default to verify these login requests, regardless of the region the server is located in.

Out of the box without any specific region configuration, any client outside of `us-east-1` has to specify `us-east-1` as the region when logging in, which is super confusing given you may not have any resources in `us-east-1`!

Given IAM objects are global in AWS as a user my expectation is that I shouldn't need to configure any regional parameters at all and it should just work.
The reality is that STS requests are regional, but as a user it would be nice not to have to worry about that!

Defaulting the client to `us-east-1` unless the region parameter is explicitly set (as opposed to falling back to environment/metadata) in the CLI would at least solve the out of the box experience, but would still require the CLI to specify a region if the server has been configured to use a different region.

Another possible solution from @joelthompson 
> One could imagine a helper to read the server-side STS signing region first before doing the client-side signing, but that configuration would need to be anonymously readable, because you need to sign a request to authenticate to Vault in the first place, and I'm not sure that's a great idea.

Related #7418

**Comment by joelthompson** [comment]
Hey @tyrannosaurus-becks -- I've been mulling this over for the past couple days, and I think the best way to handle this is to just remove the "OrDefault" from the CLI so that it won't pick up the AWS signing region from its ambient configurations. It didn't seem to be a big issue for people before this change, and we've seen a number of questions popping up on the mailing list and in GH issues, so I think the best way to solve this for now is to just have the CLI return to the old default behavior.

Thoughts?

**Comment by tyrannosaurus-becks** [comment]
@joelthompson I'm open to that approach. I don't see how it would work in practicality, though, can you expand? I'm looking at the code [here](https://github.com/hashicorp/vault/blob/master/helper/awsutil/region.go#L40) and I'm wondering, would it be an edit there? If so, it would also effect the agent's behavior. And, if it's not falling back to "us-east-1", how does it handle error cases?

Another option might be to simply strip out all our region-guessing and just use the AWS SDK's default behavior. I do see they have [some tickets](https://github.com/aws/aws-sdk-go/search?q=region&type=Issues) open where users are encountering similar issues, and some of them like [#1103](https://github.com/aws/aws-sdk-go/issues/1103) hold interesting commentary from the developers regarding the behavior around regions. Should we get out of the region-hunting business and instead make PRs to their SDK directly?

I'm open either way, just thought I'd surface that thought as well.

**Comment by kalafut** [comment]
Fixed in #7622 and #7632
