### ISSUE TITLE
Vault agent - regular INFO logs sent to stderr instead of stdout

### ISSUE THREAD

**Issue by Constantin07** [hashicorp/vault#7477]
**Describe the bug**

When running vault in agent mode - the informational log messages are sent to `stderr` stream instead of `stdout`. Then shipping these logs from vault containers into SumoLogic creates a mess when trying to filter/capture errors of vault agent and other services in a Pod.

I don't understand why informational logs are sent to stderr.
[INFO] - is not an error.
 
**To Reproduce**

1. Run `vault agent -config /etc/vault/agent.hcl`
2. The output pushed to `stderr` is:
```
==> Vault server started! Log data will stream in below:

==> Vault agent configuration:

           Api Address 1: http://127.0.0.1:8200
                     Cgo: disabled
               Log Level: info
                 Version: Vault v1.1.5
             Version Sha: f08b88029d959e1318746b188fecaad54468230b

2019-09-16T11:09:30.949Z [INFO]  auth.handler: starting auth handler
2019-09-16T11:09:30.949Z [INFO]  auth.handler: authenticating
2019-09-16T11:09:30.949Z [INFO]  sink.server: starting sink server
2019-09-16T11:09:31.083Z [INFO]  auth.handler: authentication successful, sending token to sinks
2019-09-16T11:09:31.083Z [INFO]  auth.handler: starting renewal process
2019-09-16T11:09:31.103Z [INFO]  auth.handler: renewed auth token
2019-09-16T11:09:31.223Z [INFO]  cache: received request: method=GET path=/
2019-09-16T11:09:31.228Z [INFO]  cache.apiproxy: forwarding request: method=GET path=/
...
```

**Expected behavior**

[INFO] log messages should be sent to `stdout` and not `stderr`.

**Environment:**

* Vault CLI Version (retrieve with `vault version`):
```Vault v1.1.5 ('f08b88029d959e1318746b188fecaad54468230b')```
* Server Operating System/Architecture:
MacOS, Ubuntu Linux 18.04

Vault agent configuration file(s):

/etc/vault/agent.hcl:
```hcl
    pid_file = "/vault/vault_agent.pid"

    vault {
        address = "127.0.0.1"
    }

    auto_auth {
        method "kubernetes" {
            config {
                role = "some_role_name"
            }
        }
    }

    cache {
        use_auto_auth_token = true
    }

    listener "tcp" {
        address = "127.0.0.1:8200"
        tls_disable = true
    }
```

**Additional context**
None.

**Comment by n17h31sm** [comment]
@Constantin07 From what I see this is the intended behaviour. It is due to the structure that is used now for logging, for the agent command the logger is initialised like that:

```
        c.logGate = &gatedwriter.Writer{Writer: os.Stderr}
	c.logWriter = c.logGate
	if c.flagCombineLogs {
		c.logWriter = os.Stdout
	}
```

[full source here](https://github.com/hashicorp/vault/blob/v1.1.5/command/agent.go)
So it is either everything is going to the Stderr, or to the Stdout, if you have applied the flag. 
Then you apply the log level that you want to see, but nonetheless it is still written to the Stderr, because further on in the source you can see that the `logger` is initialised using the `c.logWriter` which is set to write out to Stderr, and you just pass the level string. 
```
	if c.logger == nil {
		c.logger = logging.NewVaultLoggerWithWriter(c.logWriter, level)
	}
```
And then this logger is passed to the child threads. 

I believe that this is a good enhancement to the logging capabilities of Vault, and I +1 it. 
However I think it will require some deep rethinking of the logging functionality, as to not affect other parts of the code.

**First Look Technical Proposition:**
On first look this enhancement will require 2 logging "channels", with different `io.Writers` one to stdout and one to stderr, and whenever a log is written based on the label to determine if it should go to stdout or stderr.

**Comment by jefferai** [comment]
Like Vault server, Vault agent log messages have always been sent to stderr.

**Comment by Constantin07** [comment]
@jefferai The point I'm trying to make is that it's against UNIX philosophy. Sending informational(regular) logs into `stderr` makes life more difficult - e.g. I want to have an alert, triggered when some error/exceptions happen and thus they are written to `stderr`. At the moment that would be difficult to do because they would be messed with pure informational messages.

**Comment by ncabatoff** [comment]
The UNIX philosophy is rarely clearcut or universally agreed on.  It's true that regular command-line tools generally write normal output to stdout and errors to stderr.  When it comes to daemons there's less consensus - some write to stdout, some to stderr, but it's pretty standard to write all log messages to a single output stream.  I don't think it's likely we'll change that.

**Comment by jefferai** [comment]
Right -- we include log levels in the output (text, or JSON key) so that you can easily alert/sort. As @ncabatoff said there's not a lot of agreement, e.g. would warnings be stderr or stdout?

**Comment by catsby** [comment]
Hello - we haven't heard anything for a few weeks, so I'm going to close this for now. For future questions or discussion such as this, please checkout https://discuss.hashicorp.com/c/vault

Thanks!

**Comment by brettcurtis** [comment]
I agree with @barbarity, this is tough to generate any sort of useful notification based on log levels. We too are on Google (GKE).

**Comment by brettcurtis** [comment]
Is there any potential for this to be reconsidered?  I'll open a ticket with Google but let's be honest I'm not sure they are not going to do anything (they are going to tell me to talk to you guys). I agree with the OP and @barbarity - Regardless of opinions here, I'm simply not able to go to production with the two vendors in disagreement unless I find a WA. Like I said I'll see if Google can provide a WA in the meantime does anyone else have a WA?

**Comment by brettcurtis** [comment]
Our reps mentioned that internally Hashicorp hit a no-go in changing their decision around this, as unfortunate as this is I think we will need to figure out our own solutions... Maybe someone else has some more pull.
