### ISSUE TITLE
Github Auth `token_policies` missing from the issued token.

### ISSUE THREAD

**Issue by j-martin** [hashicorp/vault#7479]
**Describe the bug**
It seems that `token_policies` on the [GitHub team mapping](https://www.vaultproject.io/docs/auth/github.html) is not working. The issued token only have the default policy. If the GitHub team to policy mapping is done with the deprecated `policy` instead it works fine and the issued token has the right policies.

**To Reproduce**
1. Enable GitHub auth and assign policies to a GitHub team. [As per the docs.](https://www.vaultproject.io/docs/auth/github.html)
  Assign policies with `token_policies` instead of `policy` (deprecated in 1.2.0)
2. Run `vault login -method github`
3. The token should only have the default policy attached.

**Expected behavior**
The new token should have the policies attached.

The workaround is to assign `policy`instead of `token_policy` and ignore the deprecation warning.

**Environment:**
* Vault Server Version 1.2.3
* Vault CLI Version 1.2.3
* Server Operating System/Architecture:
Official Vault docker image on GKE

Vault server configuration file(s):

```hcl
api_addr     = "https://vault"
cluster_addr = "https://$(POD_IP_ADDR):8201"

log_level = "warn"

ui = true

seal "gcpckms" {
  project    = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  region     = "us-central1"
  key_ring   = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  crypto_key = "xxxxxxxxxxxxxxxxx"
}

storage "gcs" {
  bucket     = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  ha_enabled = "true"
}

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = "true"
}

listener "tcp" {
  address       = "$(POD_IP_ADDR):8200"
  tls_cert_file = "/etc/vault/tls/vault.crt"
  tls_key_file  = "/etc/vault/tls/vault.key"

  tls_disable_client_certs = true
}
```

**Comment by kalafut** [comment]
Are you using the Vault Terraform Provider? (ref: https://github.com/terraform-providers/terraform-provider-vault/issues/502)

**Comment by jefferai** [comment]
Note that the API flag is `token_policies`, not `token_policy`.

**Comment by jefferai** [comment]
Also there is no `policy` API flag. It would help a lot if you gave the exact configuration inputs/outputs you are using/seeing.

**Comment by j-martin** [comment]
@kalafut I think this is exactly the issue. I'll close this issue.

For correctness sake, I updated the issue without the misspelled `token_policies` as per @jefferai .
