### ISSUE TITLE
ExpirationManager Revoke doesn't delete secondary index

### ISSUE THREAD

**Issue by rsyabuta** [hashicorp/vault#749]
https://github.com/hashicorp/vault/blob/master/vault/expiration.go#L198

I set a low TTL of 3 minutes for my auth/app-id backend, but noticed that the secondary indices created in sys/expire/token/ weren't being deleted even though leases were expiring as expected.

I think this should be `removeIndexByToken` rather than `indexByToken`

**Comment by jefferai** [comment]
Marking this to look at before 0.4 hits.
