### ISSUE TITLE
Enabling https on hashicorp vault

### ISSUE THREAD

**Issue by wggit** [hashicorp/vault#7500]
Hello,

I have a instance of vault running on a single node. I have server certificate from cert authority. Want to make sure my configuration is correct.  

 cat config.json
{
"listener": [{
"tcp": {
"address" : "0.0.0.0:7051",
"tls_disable" : 0,
"tls_cert_file" : "/etc/vault/hostname.crt",
"tls_key_file" : "/etc/vault/hostname.key"
}
}],
"api_addr": "https://hostname:7051",
"storage": {
    "file": {
    "path" : "path/vault/vault-data"
    }
 },
"max_lease_ttl": "10h",
"default_lease_ttl": "10h",
"ui":true,
}

I can load https://hostname:7051/ui

I this configuration correct?

Thank you.

**Comment by ncabatoff** [comment]
Hi @wggit,

If you can load that URL (https://hostname:7051/ui) without your browser complaining, then yes, your listener configuration is correct.
