### ISSUE TITLE
static-roles error - The first serveral times for using the following commands work perfectly. However, starting from the forth time, the output becomes something does not expected.

### ISSUE THREAD

**Issue by wongkafai** [hashicorp/vault#7501]
The first serveral times for using the following commands work perfectly. However, starting from the forth time, the output becomes something does not expected.

https://learn.hashicorp.com/vault/secrets-management/db-creds-rotation

[root@VAULTM01 ~]# vault secrets enable database
Success! Enabled the database secrets engine at: database/

[root@VAULTM01 ~]# vault write database/config/postgresql \
plugin_name=postgresql-database-plugin \
allowed_roles="*" \
connection_url=postgresql://{{username}}:{{password}}@172.31.18.141:5432/postgres?sslmode=disable \
username="root" \
password="rootpassword"

[root@VAULTM01 ~]# vault write database/static-roles/education \
db_name=postgresql \
rotation_statements="ALTER USER \"{{name}}\" WITH PASSWORD '{{password}}';" \
username="vault-edu" \
rotation_period=200
Success! Data written to: database/static-roles/education

[root@VAULTM01 ~]# vault write database/static-roles/education \
db_name=postgresql \
rotation_statements="ALTER USER \"{{name}}\" WITH PASSWORD '{{password}}';" \
username="vault-edu" \
rotation_period=200
Error writing data to database/static-roles/education: Put https://172.31.18.141:8200/v1/database/static-roles/education: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

As there is a bug making the timeout, the password cannot be changed even ttl is 0.

**Comment by ncabatoff** [comment]
Hi @wongkafai,

Is there anything in your vault log that might explain the timeout?

**Comment by catsby** [comment]
Related https://github.com/hashicorp/vault/issues/7467

**Comment by wongkafai** [comment]
[messages.txt](https://github.com/hashicorp/vault/files/3645233/messages.txt)

**Comment by wongkafai** [comment]
"error":"1 error occurred:\n\t* invalid request\n\n"....

**Comment by wongkafai** [comment]
[messages.txt](https://github.com/hashicorp/vault/files/3651938/messages.txt)

**Comment by wongkafai** [comment]
[vault_audit.log](https://github.com/hashicorp/vault/files/3655482/vault_audit.log)
![service](https://user-images.githubusercontent.com/8857387/65651801-22ee0b80-e042-11e9-8950-9afc20870c9c.PNG)
[Syslog.txt](https://github.com/hashicorp/vault/files/3655484/Syslog.txt)

**Comment by wongkafai** [comment]
No log for timeout

**Comment by ncabatoff** [comment]
Fixed in #7518.
