### ISSUE TITLE
Delegation of token renewal

### ISSUE THREAD

**Issue by Lasering** [hashicorp/vault#7507]
**Is your feature request related to a problem? Please describe.**
I have a Terraform recipe that launches a VM and then provisions it with Chef. The terraform apply is being run in a CI. <sup>[1](#machine-image)</sup>

In Terraform time, before provisioning the VM, I want to write secrets to the kv secret engine so that the chef recipe can read them. To do this I need to give a token to Terraform. <sup>[2](#cant-use-approle)</sup>

The [Chef provisioner secret_key](https://www.terraform.io/docs/provisioners/chef.html#secret_key-string-) is set to a value containing a role-id and a secret-id. The recipe being run uses that secret_key to configure Vault agent with auto-auth + caching. Then the rest of the recipe and the application being provisioned can simply read secrets (kv, pki, etc) via the vault agent.

So in my CI I need to configure a secret variable with a Vault token capable of:

- Reading the role-id and secret-id of the AppRole role of my application.
- Writing secrets to the kv secret engine in just the paths of the application I'm deploying.

This token will eventually expire. I could create a new one and replace the CI secret variable with the new one. Or I could renew it. Either of these options isn't very attractive: its a manual step; its very easy to be forgotten. What I would like is to have the token be renewed automatically. Since I have many applications I could create a micro service whose only job would be to renew these tokens. However I can only renew a token if I have the token, which means my micro-service will have access to every application I deploy. Unless I have some king of mechanism which would allow me to delegate the token renewal without ever needing access to the token. Something akin to token accessors or leases which allow me to revoke the token without access to it, but for renewals.

#### Notes
<a name="machine-image">1</a> - The image my VM is using is a generic CentOS image. That image is also shared by many other applications I deploy. Its not feasible to create a custom image for each application as that makes the deployment process way slower.
<a name="cant-use-approle">2</a> - Using AppRole in Terraform time isn't supported, because to do an [AppRole login](https://www.terraform.io/docs/providers/vault/r/approle_auth_backend_login.html) we need to have the Vault provisioner already configured.

**Describe the solution you'd like**
One of:

1. Token accessors also allow renewing the corresponding token.
2. Leases also allow renewing the corresponding secret (in this case a token).
3. A new thing that allows renewing a token without having access to the token, and by extension the secrets to which the token grants access.

**Describe alternatives you've considered**
Renewing the token via its lease, but [apparently its impossible](https://github.com/hashicorp/vault/issues/7297).

**Comment by jefferai** [comment]
I don't think I follow the whole problem, but why not use Vault Agent to perform the authentication and keep the token renewed, and reauth when necessary?

**Comment by jefferai** [comment]
(Note: removing the labels as for years we have decided not to do this, so it is unlikely we will change that opinion now. But we may.)

**Comment by Lasering** [comment]
> why not use Vault Agent to perform the authentication and keep the token renewed, and reauth when necessary?

1. These are regular tokens created using the [create token api](https://www.vaultproject.io/api/auth/token/index.html#create-token). Vault agent does not support renewing these tokens because 1) they were not created via the agent 2) the agent auto-auth does not support regular tokens.
2. I want to renew **multiple tokens**. If vault agent supported auto-auth using tokens I would need multiple agents, which is wierd.
3. These tokens are like top tokens (in the hierarchy) for a given application. You could see and change every production secret of every application.
4. The authentication using the token will happen in a CI, a different CI for each token. Running a daemon like vault agent in a CI does not make sense.

> as for years we have decided not to do this

Is there any document/issue/PR/gitter/google forum/etc where the reasoning for not doing "delegation of token renewal" is explained? It does not need to be a full explanation.

**Comment by catsby** [comment]
Hello - I believe this was implemented in https://github.com/hashicorp/vault/pull/7817 "Add ability to renew by accessor". I'm going to close this issue for now, but if you feel it's not addressed by #7817 please let us know. Thanks!

**Comment by Lasering** [comment]
@jefferai I cannot thank you enough for implementing this feature. :tada: :+1: :1st_place_medal: :clap:
