### ISSUE TITLE
Adding intermediate CA cert to vault config

### ISSUE THREAD

**Issue by wggit** [hashicorp/vault#7523]
Vault 1.0.2

Hello,
I am trying to configure SSL with vault.  config.json has these 2 entries.

"tls_cert_file" : "/etc/vault/hostname.crt",
"tls_key_file" : "/etc/vault/hostname.key"

however openssl on vault port gives error of missing intermediate CA cert.

openssl s_client -connect hostname:7771 -showcerts
Verify return code: 21 (unable to verify the first certificate)
for intermediate CA cert.

How do I configure that?

I have java keystore which has all certificates imported. 

Appreciate your help. Thank you.

**Comment by wggit** [comment]
appended intermediate cert to /etc/vault/hostname.crt and that worked.

**Comment by benbendemo** [comment]
Could you please tell me which value should I assign to `VAULT_CACERT`, `VAULT_CLIENT_CERT`, `VAULT_CLIENT_KEY` on my macOS? I have Vault macOS version installed, can't found out how to setup these parameters.
