### ISSUE TITLE
etcd store integration should default to 2379, not 4001

### ISSUE THREAD

**Issue by odigity** [hashicorp/vault#753]
The docs for using etcd as a store say Vault defaults to using port 4001 to talk to etcd, which is was the default port back in etcd v0.4.7.  However, they have since switched to 2379.

The doc:

https://vaultproject.io/docs/config/

I'm new to etcd, but from what I've read recently, I bet more people are using v2 than v0.4.x.  (0.4 was unstable)

**Comment by jefferai** [comment]
Thanks for the report -- fixed!
