### ISSUE TITLE
Vault for generating credentials and using for resource creation in Azure

### ISSUE THREAD

**Issue by bincysjames** [hashicorp/vault#7530]
Hi Team 

I am trying to create resources in Azure using terraform and vault is configured to generate credentials.

my provider.tf

provider "vault" {
  address = "${var.address}"
  token =  "${var.token}"
}
provider "azurerm" {
subscription_id =  "${var.subsciption_id}"
tenant_id = "${var.tenant_id}"
client_secret = "${data.vault_generic_secret.azure_jwt.data["client_secret"]}"
client_id = "${data.vault_generic_secret.azure_jwt.data["client_id"]}"
}

my main.tf testing
It needs to contact vault and generate credentials and the same needs to be used for azure resource creation.It is working as expected some times and other times it is getting error as below 
data "vault_generic_secret" "azure_jwt" {
path = "${var.resource_group_name}/creds/${var.resource_group_name}-admin-role"
}
resource "azurerm_network_security_group" "sg1" {
  name                = "test"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
}

Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/4xxxxxxxxxxxxxxxxxxxbefa/providers?api-version=2016-02-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier '9d579e-2b7e-5' was not found in the directory 'bb-569'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.

is there any way to add delay after data block, if I add provisioner block in data I am getting below error .please suggest

data "vault_generic_secret" "azure_jwt":
   provisioner "local-exec" {
Blocks of type "provisioner" are not expected here.

**Comment by michelvocks** [comment]
Hi @bincysjames!

I can see that this issue is related to the [terraform-vault provider](https://github.com/terraform-providers/terraform-provider-vault) which has its own GitHub repository. Would you mind to re-open this issue over there?

I will close this issue for now since it seems to be not related to Vault itself. 

Cheers,
Michel
