### ISSUE TITLE
core.Shutdown() should cause the server command to exit

### ISSUE THREAD

**Issue by jdollard** [hashicorp/vault#7535]
**Describe the bug**
I'm running vault server with vault configured in HA mode.  If core.performKeyUpgrades() returns a non-nil error after vault obtains leadership, then vault seals itself but the vault server continues to run.  I'd hope/expect that in this case the vault server command would exit with an error instead.

Note that If core.performKeyUpgrades does return an error then core.Shutdown() is called.  The API docs for this function describe that it should be used to gracefully quit, which seems consistent with my above expectation.

**To Reproduce**
1. Configure vault to run in HA mode.  
2. Run 'vault server' ....
3. On the machine that obtains leadership, trigger performKeyUpgrades to return an error

**Expected behavior**
The 'vault server' command exits with a non-zero exit code.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.2.3
* Vault CLI Version (retrieve with `vault version`): 1.2.3

**Additional context**

**Comment by jefferai** [comment]
> The API docs for this function describe that it should be used to gracefully quit, which seems consistent with my above expectation.

To be clear, it gracefully quits the Vault core, but the core is being run by something else (the server command).

There actually isn't a right answer here, and we've had requests the other way too, where they don't want Vault to exit because that will mean that it will be auto-restarted and go back into the available pool of potential active nodes, whereas with it sealed then LBs will route around it to other nodes and it won't try to grab active status again until it's unsealed.

**Comment by jdollard** [comment]
> There actually isn't a right answer here, and we've had requests the other way too, where they don't want Vault to exit because that will mean that it will be auto-restarted and go back into the available pool of potential active nodes, whereas with it sealed then LBs will route around it to other nodes and it won't try to grab active status again until it's unsealed.

Given this would a reasonable approach be to add another command line option for vault server to control this behavior?   Something along the lines of "-exit-on-core-shutdown"?

**Comment by jdollard** [comment]
I've created a PR that includes the fix I described

**Comment by briankassouf** [comment]
#7561 is now merged
