### ISSUE TITLE
SSH secret engine generates postdated certificates

### ISSUE THREAD

**Issue by LordBurrito** [hashicorp/vault#7538]
**Describe the bug**
The SSH secret engine generates postdated certificates from both API and web UI from 1 hour after the date system.

example:
```
ubuntu@vault:~$ date
Tue 01 Oct 2019 11:40:36 AM BST
ubuntu@vault:~$ ssh-keygen -Lf signed-cert.pub
signed-cert.pub:
        Type: ssh-rsa-cert-v01@openssh.com user certificate
        Public key: ****
        Signing CA: ****
        Key ID: "****"
        Serial: ****
        Valid: from 2019-10-01T12:39:22 to 2019-10-01T13:39:52
        Principals: 
                ubuntu
        Critical Options: (none)
        Extensions: 
                permit-X11-forwarding
                permit-agent-forwarding
                permit-port-forwarding
                permit-pty
                permit-user-rc
```
JSON from the audit log:
```json
{
	"time": "2019-10-01T11:39:52.083314675Z",
	"type": "response",
	"auth": {
		"client_token": "***",
		"accessor": "***",
		"display_name": "root",
		"policies": [
			"root"
		],
		"token_policies": [
			"root"
		],
		"token_type": "service"
	},
	"request": {
		"id": "***",
		"operation": "update",
		"client_token": "***",
		"client_token_accessor": "***",
		"namespace": {
			"id": "root"
		},
		"path": "ssh-canonical/sign/canonical-user",
		"data": {
			"cert_type": "***",
			"critical_options": {},
			"extension": {},
			"public_key": "***"
		},
		"remote_address": "***"
	},
	"response": {
		"data": {
			"serial_number": "***",
			"signed_key": "***"
		}
	}
}
```

**To Reproduce**
Just sign any certificate with SSH vault secret engine. 

**Expected behavior**
Have a valid signed certificates starting from the current system date

**Environment:**
* Vault Server Version:
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       2
Version         1.2.2
Cluster Name    vault-cluster-ac44c8dc
Cluster ID      dcea2170-28ad-e9bd-ceb7-c937213a2eba
HA Enabled      true
HA Cluster      https://192.168.6.148:8201
HA Mode         active
```
* Vault CLI Version:
`Vault v1.2.3`

* Server Operating System/Architecture:
`Ubuntu 18.04.3 LTS `

* Vault server configuration file(s):
```hcl
ui = true
  
listener "tcp" {
  address          = "0.0.0.0:8200"
  tls_disable      = "true"
}
storage "consul" {
  path    = "vault/"
}
api_addr = "https://192.168.6.148:8200"
```
* Consul Version:
`Consul v1.6.1`

* Consul Server Config:

```json
{
    "advertise_addr": "192.168.6.148",
    "bind_addr": "192.168.6.148",
    "bootstrap: true,
    "client_addr": "0.0.0.0",
    "data_dir": "/opt/consul",
    "datacenter": "DC1",
    "dns_config": {
        "enable_truncate": true,
        "only_passing": true
    },
    "domain": "consul",
    "enable_script_checks": true,
    "enable_syslog": true,
    "log_level": "INFO",
    "node_name": "consul",
    "server": true,
    "ui": true
}
```
**Additional context**
I've setted up the Vault environment as I've already done before: same config, same users, same policies.
I've just downloaded the latest Consul and Vault bin from the website.
**update**
I don't have any issue using "file" as storage; so I think it has to be something related to Consul.

**Comment by michelvocks** [comment]
Hi @LordBurrito!

The reason why the validation times in your certificate are different is that the [Unix time](https://en.wikipedia.org/wiki/Unix_time) is defined using the UTC timezone.
The [OpenSSH certificate specification](https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.certkeys#L184) defines how certificates should look like and that does also include the `ValidBefore` and `ValidAfter` parameters.

Since your local system uses the BST timezone which is one hour ahead of UTC, `ssh-keygen` automatically converts the Unix time from UTC to BST which results in a different time output.

Cheers,
Michel

**Comment by michelvocks** [comment]
> If ssh-keygen automatically converts the Unix time in BTS I should be able to log in anyway because 13 UTC = 14 BTS.

Yes, you are right. My _assumption_ is that `ssh-keygen` is not aware of DST (daylight saving time) which would result in a wrong conversion.

However, I cannot find any prove for that. Would you mind to share some more information about your setup e.g. SSH role configuration, is Vault running in a docker container? any specific time/date cron jobs are running on the host system?

It is also weird that your system uses the BST time zone but apparently Vault uses the UTC time zone. 

Cheers,
Michel

**Comment by LordBurrito** [comment]
Hi Michel, 

I'm running Vault and Consul on the same VM hosted on VMware.
that's the SSH role:
```
{
  "allow_bare_domains": false,
  "allow_host_certificates": false,
  "allow_subdomains": false,
  "allow_user_certificates": true,
  "allow_user_key_ids": false,
  "allowed_critical_options": "",
  "allowed_domains": "",
  "allowed_extensions": "",
  "allowed_users": "ubuntu",
  "default_critical_options": {},
  "default_extensions": {
    "permit-X11-forwarding": "",
    "permit-agent-forwarding": "",
    "permit-port-forwarding": "",
    "permit-pty": "",
    "permit-user-rc": ""
  },
  "default_user": "ubuntu",
  "key_id_format": "",
  "key_type": "ca",
  "max_ttl": "1h0m0s",
  "ttl": "1h0m0s"
}
```
I've tried to set the system date to UTC over all the machines I was using for my lab and even if I can see the correct time in UTC and via `ssh-keygen` I still get the same error:
`Oct  2 08:40:13 ubuntu-target sshd[1576]: error: Certificate invalid: not yet valid`

I've tried to downgrade both vault and consul bin but still had the issue.

I solved the problem updating the time with the ntp service over all the machines.
Now I can have the BTS time and I'm able to connect even though the `ssh-keygen` shows the UTC time.

I don't really know what happened since I've never had this issue with my previous vault installation.
I'm still confused because using "file" as storage I was able to generate the correct certificates and connect through the target machines.

Thank you for your help
