### ISSUE TITLE
OAS Spec not accurately reflecting vault object definitions 

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/vault#7560]
**Describe the bug**
I'm one of the maintainers of the [HVAC](https://github.com/hvac/hvac) python client for vault. We're experimenting with rewriting the app based on the OAS spec recently released by Hashi. I've been having some trouble getting (any) proper returns from the auto generated client (swagger-codegen). After a while of troubleshooting, I believe the issue may have to do with the spec. 

i see a couple problems:
1. the models defined by the spec [arent being named correctly](https://github.com/drewmullen/HAC/tree/master/hashicorp_vault_client/hashicorp_vault_client/models). I believe this is because the [definitions section](https://github.com/swagger-api/swagger-codegen/blob/3a8874b2a30c464bd35a7014470ad0b48c5eff6e/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L826) is missing from the [OAS spec](https://github.com/drewmullen/HAC/blob/master/vault_api_jq.json)
```
cat vault_api_jq.json| jq '.definitions'
null
```
2. paths defined by the spec dont have relevant schemas associated with them and therefore cannot get any output. here is an example from /sys/health. we should see a `schema` definition in this `resources` block
https://github.com/drewmullen/HAC/blob/fb185804fd244366f8f8d01df22835b3d96e7512/vault_api_jq.json#L4080

**Additional context**
Admittedly, this spec was NOT produced by https://github.com/hashicorp/vault/blob/master/scripts/gen_openapi.sh because i didnt find that till recently but AFAIK this only provides all the other endpoints. for my testing, we only needed a subset.

if you attempt to play with my auto generated client, checkout the 2 open issues for small changes that need to be made in order to properly execute a GET on `/sys/health`

**Comment by jefferai** [comment]
@kalafut

**Comment by kalafut** [comment]
Hi @drewmullen. To start with, is the generated OAS being correctly interpreted as OpenAPI 3?  Your link to the definitions section was for a 2.0 document, and that is an element that changed from 2 to 3. I'd like to confirm this aspect of the tooling first because there are significant changes between the spec versions.

I checked the output in https://editor.swagger.io just now and it didn't flag any errors, and it has generally been quite strict. So at least what's currently there seems correct (albeit there are many optional items we're not using right now).

**Comment by drewmullen** [comment]
hi @kalafut thanks for taking a look at this with me. i generated the client via OAS 3.0 spec. thanks for pointing out that the petstore.json blob was 2.0! I looked at [petstore.json 3.0](https://raw.githubusercontent.com/swagger-api/swagger-codegen/3.0.0/modules/swagger-codegen/src/test/resources/3_0_0/petstore.json) and that **does not** have a `definitions` section as you mentioned. 

TBH Swagger is very new to me. So instead of inferring the problem myself, let me get into a specific example on why I suspect the spec itself. if we look at `/sys/health` as an example: 


## generated client output
after generating a client off the spec, when hitting `/sys/health`
```
import hashicorp_vault_client

conf = hashicorp_vault_client.Configuration()
conf.host = 'http://127.0.0.1:8205'
client = hashicorp_vault_client.ApiClient(conf)
api = hashicorp_vault_client.SystemApi(client)
print(api.get_sys_health())
```
Output: `None`

Now, if we enable debugging, we can see the output is coming back:
```
>>> conf.debug=True
>>> client = myvault.ApiClient(conf)
>>> api = myvault.SystemApi(client)
>>> print(api.get_sys_health())
2019-10-04 08:09:06,691 DEBUG Starting new HTTP connection (1): 127.0.0.1:8205
send: b'GET /v1/sys/health HTTP/1.1\r\nHost: 127.0.0.1:8205\r\nAccept-Encoding: identity\r\nUser-Agent: Swagger-Codegen/0.0.1/python\r\nContent-Type: application/json\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Cache-Control: no-store
header: Content-Type: application/json
header: Date: Fri, 04 Oct 2019 12:09:06 GMT
header: Content-Length: 294
2019-10-04 08:09:06,694 DEBUG http://127.0.0.1:8205 "GET /v1/sys/health HTTP/1.1" 200 294
2019-10-04 08:09:06,694 DEBUG response body: {"initialized":true,"sealed":false,"standby":false,"performance_standby":false,"replication_performance_mode":"disabled","replication_dr_mode":"disabled","server_time_utc":1570190946,"version":"1.1.3","cluster_name":"vault-cluster-b374c203","cluster_id":"87cd9fc3-0359-6cc2-628f-0bcb5c00d4ea"}
```

health can also be retrieved via: `print(client.call_api('/v1/sys/health', 'GET', response_type = 'str'))`

## what this might mean
so... add all that together, my most suspicious parameter is `response_type`. which is not an overridable parameter at the `get_sys_health` function level:
https://github.com/drewmullen/HAC/blob/e979878d0ef5c72bd848df83871b4c748f844a35/hashicorp_vault_client/hashicorp_vault_client/api/system_api.py#L3202

so now i'm trying to figure out why the param is explicitly set to pass `None`. One idea I had is that because the spec path does not dictate a `resource.schema`, the generated code doesnt know to expect an output (considers it a void function)

## spec examples with schema vs vault spec
While fumbling around looking at `petstore.json` i noticed a few differences in their objects. example: `/pet/findByStatus`
https://github.com/swagger-api/swagger-codegen/blob/28fd786879023009b849a4855a70664163d766d9/modules/swagger-codegen/src/test/resources/3_0_0/petstore.json#L102-L164

vault_spec.json except:
https://github.com/drewmullen/HAC/blob/fb185804fd244366f8f8d01df22835b3d96e7512/vault_api_jq.json#L4072-L4096-L4098

**Comment by kalafut** [comment]
@drewmullen While the inputs (parameters and requestBody) are well specified in the generated spec since we can determine them programmatically, the outputs are not, which is why you don't see any output schema definitions. And that health output is sort of an outlier with its multiple response codes.

I'm unfamiliar with the code generators out there so I can't really provide much insight into what they're looking for. If it is something minor, e.g. adding a placeholder schema, then your code could probably preprocess the generated spec. I'd probably start with one small endpoint and try adjusting the input manually along with digging into the codegen code to figure out what its expecting.

**Comment by drewmullen** [comment]
so it seems like y'all arent looking to support this use case, which is fine. i may continue to plug away at it myself and reopen if i run into something that seems spec specific. 

thanks for the info
