### ISSUE TITLE
VAULT_TLS_SKIP_VERIFY should be VAULT_SKIP_VERIFY

### ISSUE THREAD

**Issue by Quuxplusone** [hashicorp/vault#7570]
[Line 90 in `docs/configuration/seal/transit.html.md`](https://github.com/hashicorp/vault/blame/51787e4bd40130ee20afdaae4bb757a848a79d44/website/source/docs/configuration/seal/transit.html.md#L90) refers to env var `VAULT_TLS_SKIP_VERIFY`, but the actually respected spelling of this env var seems to be just `VAULT_SKIP_VERIFY`. (Verified by setting each of these variables in my environment and seeing which one Vault pays attention to.)

**Comment by kalafut** [comment]
Thanks for the report!
