### ISSUE TITLE
Typo in Build Your Own Certificate Authority (CA) guide in Learn

### ISSUE THREAD

**Issue by pangyikhei** [hashicorp/vault#7574]
**Describe the bug**
There is a typo in the Learn site for the Vault guide Build Your Own Certificate Authority (CA).
https://learn.hashicorp.com/vault/security/sm-pki-engine#web-ui-1

In Step 15, it says:
> Paste in the CSR you just **copiked** into the Certificate Signing Request (CSR) field.

**Comment by kalafut** [comment]
@yhyakuna

**Comment by yhyakuna** [comment]
@pangyikhei  Thanks for catching this!  Fixed.
