### ISSUE TITLE
Allow '@' in aws secrets engine path regex

### ISSUE THREAD

**Issue by will-quan-bird** [hashicorp/vault#7581]
**Is your feature request related to a problem? Please describe.**
The regex doesn't allow '@' (at sign) for email within the vault aws secrets engine path as it is nice to place full emails there.

**Describe the solution you'd like**
The PR has passed all checks and is ready for merging https://github.com/hashicorp/vault/pull/7553/files

**Comment by michelvocks** [comment]
https://github.com/hashicorp/vault/pull/7553 has been merged.
