### ISSUE TITLE
Add a feature to support disable wildcard subdomains

### ISSUE THREAD

**Issue by venky999** [hashicorp/vault#7592]
**Is your feature request related to a problem? Please describe.**
At the moment

VAULT PKI supports wild card subdomains to generated.

like `*.myorg.com` or `*.finance.myorg.com`

Is it possible to add an option to explicitly disable this feature
so that I need to use a specific subdomain when generating cert

like 

`test.myorg.com` or `test.finance.myorg.com`

This is useful when using intermediate CA created for different namespaces from root CA and I want to Intermediate not to issue wildcard subdomains

**Comment by jefferai** [comment]
If the user can pile on 200 subdomains in a single request, what's the logical difference between supporting * and supporting those 200 subdomains?

Just trying to understand the use case.

**Comment by timarenz** [comment]
As I just worked on the same requirement for a customer this can be solved today using a Sentinel policy. However, this is a Vault Enterprise feature but could solve what you want to accomplish. 

Here is an example on how to do this:
[https://gist.github.com/timarenz/15a3b134e37af827c15304e196412b29](url)

**Comment by venky999** [comment]
> If the user can pile on 200 subdomains in a single request, what's the logical difference between supporting * and supporting those 200 subdomains?
> 
> Just trying to understand the use case.

So that the PKI cannot issue subdomains that are not in the explicit list

**Comment by arctiqtim** [comment]
So many large organizations' security teams have a policy against wildcard cert use.  Specifically Vault fits this use case to allow programmatic, policy-controlled user generated certificates.  The PKI secrets engine's biggest use case IMO is to provide a clean way to issue per-app per-service certificates that are finer grained, and very short TTLs.  An option in Vault to disable the creation of wildcard certs would allow admins to better enforce the idea of app-specific certs vs creation of wildcard certs.

Sentinel is a way to solve it for sure but I don't think it should be required.

**Comment by AkashGuptaHC** [comment]
> As I just worked on the same requirement for a customer this can be solved today using a Sentinel policy. However, this is a Vault Enterprise feature but could solve what you want to accomplish.
> 
> Here is an example on how to do this: [https://gist.github.com/timarenz/15a3b134e37af827c15304e196412b29](url)

**Comment by AkashGuptaHC** [comment]
> As I just worked on the same requirement for a customer this can be solved today using a Sentinel policy. However, this is a Vault Enterprise feature but could solve what you want to accomplish.
> 
> Here is an example on how to do this: [https://gist.github.com/timarenz/15a3b134e37af827c15304e196412b29](url)

The link isn't working, can you check, i am looking for this sentinel policy.

**Comment by timarenz** [comment]
Sorry, this seems to have been lost in my last purge. Below you will find the example EGP policy.

```
# EGP policy meant for path pki/issue/

wildcard_check = func() {
  if (request.data.common_name contains "*" or request.data.alt_names contains "*") {
      print("Wildcard certificate not allowed!")
      return false
  } 
  
  return true
}

main = rule {
	wildcard_check()
}
```

**Comment by drawks** [comment]
> So many large organizations' security teams have a policy against wildcard cert use. Specifically Vault fits this use case to allow programmatic, policy-controlled user generated certificates. The PKI secrets engine's biggest use case IMO is to provide a clean way to issue per-app per-service certificates that are finer grained, and very short TTLs. An option in Vault to disable the creation of wildcard certs would allow admins to better enforce the idea of app-specific certs vs creation of wildcard certs.
> 
> Sentinel is a way to solve it for sure but I don't think it should be required.

To add to this point, functionally a wildcard may be the same as allowing arbitrary subdomains, however from an audit standpoint the two are very different. Disallowing wildcard while allowing arbitrary subdomains means that every single subdomain requested creates an explicit audit event detailing exactly what SANS the certificate claims, however a single audit event for a wildcard gives absolutely zero insight as to how the end service may be using the certificate.
