### ISSUE TITLE
Mix of http and https URLs in pki-engine.html.md

### ISSUE THREAD

**Issue by jdinel** [hashicorp/vault#7594]
Hi, in the `pki-engine.html.md` file, a `-dev` server is started but the documentation switches randomly between `http` and `https` URLs for the remaining examples. All links in this document should be plain `http` as the dev server doesn't start a `https` service.

**Comment by yhyakuna** [comment]
[Fixed](https://learn.hashicorp.com/vault/secrets-management/sm-pki-engine) now!
