### ISSUE TITLE
Add OPVault secret backend for interop with 1Password

### ISSUE THREAD

**Issue by roderickm** [hashicorp/vault#761]
Reading secrets from a [1Password OPVault](https://support.1password.com/opvault-overview/) would allow our puppet-managed servers (via [hiera-vault](https://github.com/jsok/hiera-vault)) to access the secrets in our team 1Password system. Even a read-only opvault backend would be very useful.

Vault appears to have extensible plumbing for additional secret vaults, and a [Go package for reading the 1Password OPVault format](https://github.com/miquella/opvault) is available, but [Vault doesn't currently support the creation of custom secret backends](https://vaultproject.io/docs/secrets/custom.html).

Leaving this enhancement idea here for now: until I learn Go, or someone else finds this sufficiently interesting.

**Comment by jefferai** [comment]
We have no current plans for a built-in backend to do this, but with our plugin capabilities this can now be easily created by an interested third-party!

**Comment by roderickm** [comment]
Relevant enough to warrant a mention here: https://github.com/1Password/vault-plugin-secrets-onepassword
