### ISSUE TITLE
how to store unseal keys and root token in production

### ISSUE THREAD

**Issue by antasesha** [hashicorp/vault#7615]
Hi
I am trying to use hashivault to store some keys .I have below queries
1) Once the vault is started, how do i store the root token and the unseal keys?
2)Also if i lose the unseal keys, how do i unseal the vault for further usage.
3) Also once the keys are put inside, what if i log out, and log again after say 3 days,will my keys still be there in the path i created ? if so,how do i see it?
4) the exampke given in the website example.cpp does not compile for me and it gives a lot of link error when using VS 2017 compiler. Any suggestions on how to use vault with c++ programatically to put and get keys from my c++ application?
Thanks

**Comment by bbaassssiiee** [comment]
1.You typically distribute the unseal keys over trusted operators (one each). Together they can unseal the vault, but they/you should not be able to do that alone. Therefore encrypt these unseal keys in initializing vault. After you set up authentication you typically destroy the root token. 
2. You don't put the unseal keys in vault. You all need to unseal Vault when the machine reboots.

**Comment by yura-shutkin** [comment]
Good day,
You can use public part of you PGP key for generating encrypted unseal keys which you can store at VCS, like git.
And as @bbaassssiiee already told. You should not use root token it production. You can create service account with minimal and only necessary rights for managing vault configurations like auth backends, users, secret engines, etc

**Comment by catsby** [comment]
Hello - we haven't heard anything for a few weeks, so I'm going to close this for now. For future operation questions please checkout https://discuss.hashicorp.com/c/vault

Thanks!
