### ISSUE TITLE
I forget to note the Root Token and Unseal Key, they are lost, how I can use vault again? 

### ISSUE THREAD

**Issue by hushanxue** [hashicorp/vault#7640]
I forget to note the Root Token and Unseal Key, they are lost, how I can use vault again?   I remove some data on disk?

**Comment by yura-shutkin** [comment]
Good day, sir.
I'm not a member of HashiCorp, but I can bet that you can ask this question at https://discuss.hashicorp.com/c/vault

Btw. It is not possible to unseal vault if you lost required count of unseal keys. It's builtin feature of vault called barrier.

I lost 2 previous instances of vault and now I have vault auto-unseal. You can generate PGP key and use it's public part for generating unseal keys on keys creation or rotation. After generating new keys you can store PGP encrypted keys into Version Control System, like git, for future decryption and vault unseal.

**Comment by hushanxue** [comment]
Hi, yura-shutkin.
Thanks a lot for your advice. I feel grateful.
