### ISSUE TITLE
Undefined: consts.RequestHeaderName

### ISSUE THREAD

**Issue by plinski** [hashicorp/vault#7641]
**Describe the bug**
I get the following error when I try to use `"github.com/hashicorp/vault/api"` in my project:
`# github.com/hashicorp/vault/api
../../github.com/hashicorp/vault/api/client.go:436:17: undefined: consts.RequestHeaderName`.
I can see that the client.go file was changed two days ago. It used to work last Friday.

**To Reproduce**
Import  `"github.com/hashicorp/vault/api"` to your project.

**Comment by poolski** [comment]
✋Same thing happening here. It looks like something broke in a recent release, since there were no issues a couple of weeks ago when pulling the same code. 

Running `go get -u github.com/hashicorp/vault/api` vs `go get github.com/hashicorp/vault/api` broke my local environment.

**Comment by allthingsclowd** [comment]
✋ Same error here on the Travis-CI platform with previously working deployments -
``` bash
...
github.com/hashicorp/vault/api
# github.com/hashicorp/vault/api
../../hashicorp/vault/api/client.go:436:17: undefined: consts.RequestHeaderName
The command "eval go get -v -t ./... " failed. Retrying, 2 of 3.
```

I noticed that this header was added in this PR - https://github.com/hashicorp/vault/pull/7627 

On my mac when I enable go modules it appears to download correctly? I tried this on Travis-CI with no joy.

``` bash
vagrant@godev01:/vagrant$ clear
vagrant@godev01:/vagrant$ export GO111MODULE=off
vagrant@godev01:/vagrant$ go get github.com/hashicorp/vault/api
# github.com/hashicorp/vault/api
/home/vagrant/go/src/github.com/hashicorp/vault/api/client.go:436:17: undefined: consts.RequestHeaderName
vagrant@godev01:/vagrant$ export GO111MODULE=on
vagrant@godev01:/vagrant$ go get github.com/hashicorp/vault/api
vagrant@godev01:/vagrant$
```

**Comment by mjarmy** [comment]
Fixed!  Sorry about that -- we needed a `go mod vender'

**Comment by dnascimento** [comment]
@mjarmy when will Hashicorp release a new version of the SDK with this issue addressed?
