### ISSUE TITLE
Vault UI shows all versions as deleted if `delete_version_after` is configured

### ISSUE THREAD

**Issue by agathver** [hashicorp/vault#7644]
In a kv2 storage backend, Vault UI shows all versions to be deleted if `delete_version_after` is configured.

**To Reproduce**

1. Configure `delete_version_after`. Run `vault kv metadata put -delete-version-after=300s secret/test`
2. Add some new versions of the secret. Run `vault kv put secret/test message="data1"`
3. Open the secret in the UI

**Expected behavior**
Latest version of the secret should be visible

**Actual behavior**
Version is shown to be deleted

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault v1.2.3
* Vault CLI Version (retrieve with `vault version`): Vault v1.2.3
* Server Operating System/Architecture: MacOS 10.15 Catalina

The same error is also present in Vault compiled from master

**Comment by con-f-use** [comment]
There seems to be a regression. I'm on Vault v1.15.4, I set `delete_version_after=1s` in the UI, secret doesn't get deleted. Or am I missing some extra prerequisites or configuration I have to make?

-----

![image](https://github.com/user-attachments/assets/60364e91-c9fb-44b0-8a39-f0502ffc29a2)
![image](https://github.com/user-attachments/assets/ce9f0562-3058-4277-a249-582e0dc880e4)
![image](https://github.com/user-attachments/assets/b3e14bbc-7a4d-4645-bd4c-fbc94c413d4e)
