### ISSUE TITLE
Azure Documentation - Create Role missing policies?

### ISSUE THREAD

**Issue by llamasoft** [hashicorp/vault#7648]
In the Azure authentication documentation, the [Create Role](https://www.vaultproject.io/api/auth/azure/index.html#create-role) sample payload includes a "policies" key, but no parameter by that name exists.  Is it supposed to be "token_policies"? Is "policies" is allowed as a convenience?  If so, it may be worth noting that.

**Comment by kalafut** [comment]
@llamasoft `policies` is the pre-1.2 parameter which has been deprecated. Thanks for highlighting this. We'll get the docs updated.
