### ISSUE TITLE
When restoring a key in transit engine, path is not correctly validated

### ISSUE THREAD

**Issue by byo** [hashicorp/vault#7663]
1. `vault write /transit/keys/test-key type=rsa-2048 exportable=true allow_plaintext_backup=true`
2. `vault read --field=backup /transit/backup/test-key | vault write /transit/restore/sub/path/test-key2 backup=-`
3. A key with incorrect path has been created, `sub` is listed as a sub-path in `/transit/keys/` but one can not list that sub-path nor do any operation related to the key

**Expected behavior**
When doing restore, vault should fail if the name of the key is incorrect.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.2.3
* Vault CLI Version (retrieve with `vault version`): v1.2.2
* Server Operating System/Architecture: Debian/amd64

Transit ACLs used:

```hcl
path "transit/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
```

**Comment by catsby** [comment]
I've opened https://github.com/hashicorp/vault/pull/7998 to address this, hopefully it gets approved and merged 😄

**Comment by catsby** [comment]
#7998 was merged, thanks again for reporting this!
