### ISSUE TITLE
sys/mfa/method/okta/my_okta --- unsupported path

### ISSUE THREAD

**Issue by avinashgundlapally** [hashicorp/vault#7671]
root@ip-xxxxxx:/home/ubuntu/config# vault write sys/mfa/method/okta/my_okta mount_accessor=auth_userpass_xxxx org_name="dev-xxxxx" api_token="007.......rXlnl2x"
Error writing data to sys/mfa/method/okta/my_okta: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/mfa/method/okta/my_okta
Code: 404. Errors:

* 1 error occurred:
        * unsupported path

I have launched vault dev server and when I am trying to configure okta MFA am getting above error. could you please help.

**Comment by calvn** [comment]
The `sys/mfa/*` endpoints are only available in Vault Enterprise. Is that the type of binary that you're using?

**Comment by catsby** [comment]
Hello - we haven't heard anything for a few weeks, so I'm going to close this for now. For future operation questions please checkout https://discuss.hashicorp.com/c/vault 

Thanks!
