### ISSUE TITLE
Some hyperlinks in Reference architecture document are broken

### ISSUE THREAD

**Issue by volenbovsky** [hashicorp/vault#7687]
**Describe the bug**
In 'table of contents on page https://learn.hashicorp.com/vault/operations/ops-reference-architecture
The broken hyperlinks end with hyphen (-) and they are 'second level' hyperlinks
For example https://learn.hashicorp.com/vault/operations/ops-reference-architecture#single-region-deployment-enterprise-
instead of https://learn.hashicorp.com/vault/operations/ops-reference-architecture#single-region-deployment-enterprise
The list of broken ones below:
Single Region Deployment (Enterprise)
Multiple Region Deployment (Enterprise)
...
Deployment of Vault in one Availability Zone (all)
Deployment of Vault in two Availability Zones (OSS)
Deployment of Vault in two Availability Zones (Enterprise)
Deployment of Vault in three Availability Zones (OSS)
Vault Replication (Enterprise Only)

**To Reproduce**
Try to use any of hyperlinks from list above
**Expected behavior**
The page should 'move down' to respective chapter
**Environment:**
N/A
Vault server configuration file(s):
N/A

**Additional context**
N/A

**Comment by yhyakuna** [comment]
Thank you for reporting this.  I fixed those last week, so the links should work now.
