### ISSUE TITLE
Use pre-existing policies for AWS users

### ISSUE THREAD

**Issue by lcbowen3** [hashicorp/vault#770]
Please add the capability to define an AWS user to use pre-existing AWS IAM policies

vault write aws/roles/<user> policy=AmazonEC@FullAccess

Of course, if the policy doesn't exist when a read is called, an error would be generated.

This would allow AWS policies to be controlled by a different group (the AWS administrators could define the policies / alter the policies as needed without having to notify/update the vault administrators).

**Comment by DanyC97** [comment]
+1

**Comment by OWSM** [comment]
I see this PR was merged. Did this go into 0.5, or will it wait for 0.6?

**Comment by jefferai** [comment]
It will be in 0.5!

**Comment by OWSM** [comment]
Thanks @jefferai !
