### ISSUE TITLE
rotate-root in mongodb

### ISSUE THREAD

**Issue by wongkafai** [hashicorp/vault#7708]
Does the feature of rotate-root support mongodb
Is there an example?
Use version 1.2.3

**Comment by wongkafai** [comment]
![rotate-root in mongodb](https://user-images.githubusercontent.com/8857387/67266672-55751200-f4e3-11e9-827e-ae4dba025155.PNG)

**Comment by conor-mccullough** [comment]
Just closing this out to tidy things up as this was addressed in #23240
