### ISSUE TITLE
vault temporary account in mysql

### ISSUE THREAD

**Issue by meadowhuhu** [hashicorp/vault#7722]
I have a problem about vault account .
Each call to the vault will generate three temporary account in mysql user table.With the operation,the account will become more and more.
I wonder if there are some ways to block the temporary account or delete those account by modifying the configuration file.
![image](https://user-images.githubusercontent.com/39788833/67449618-575ae480-f64d-11e9-99ba-01e1ae77e2ee.png)

Thanks

**Comment by chrishoffman** [comment]
Vault will not generate 3 accounts for each operation and only creates one.  I would check the calling application to see if there is a problem there that is not being handled correctly.

**Comment by meadowhuhu** [comment]
> Vault will not generate 3 accounts for each operation and only creates one.  I would check the calling application to see if there is a problem there that is not being handled correctly.

Thank you very much, you are right,Vault only creates one. I add another two VaultOperations.read() in my  init process,I feel very sorry to disturb you
