### ISSUE TITLE
OIDC auth method should support setting the entity name to something recognisable

### ISSUE THREAD

**Issue by stevegore** [hashicorp/vault#7723]
**Is your feature request related to a problem? Please describe.**
Having just set up using OIDC Auth with Google, the newly recreated entities are shown as a list of number. There's no way of knowing which entity relates to which user.

**Describe the solution you'd like**
Ideally the entity name would could be taken from a configurable field. Perhaps the email address by default.

**Describe alternatives you've considered**
The GitHub auth method provides an alias that matches the GitHub username, so I can see which entity relates to which GitHub user. That could work.

**Explain any additional use-cases**
None

**Additional context**
None

**Comment by kalafut** [comment]
Hi. You can configure which claim (e.g. `"email"`) is used for the alias name with the [user_claim](https://www.vaultproject.io/api/auth/jwt/index.html#user_claim) parameter.

**Comment by stevegore** [comment]
Thanks so much!
For future readers, I also had to ensure I add the `profile` OIDC scope to get that information. Settled on `name` claim in the end.

```
vault write auth/oidc/config \
    oidc_discovery_url="https://accounts.google.com" \
    oidc_client_id="xxx.apps.googleusercontent.com" \
    oidc_client_secret="xxx" \
    default_role="default"

vault write auth/oidc/role/default \
    user_claim="name" \
    bound_audiences="xxx.apps.googleusercontent.com" \
    allowed_redirect_uris="https://xxx/ui/vault/auth/oidc/oidc/callback" \
    role_type="oidc" \
    oidc_scopes="openid,profile" \
    policies=default \
    ttl=4h
```

**Comment by kalafut** [comment]
Glad you got it working!

**Comment by ccakes** [comment]
@kalafut apologies for resurrecting an old issue here

The docs for `user_claim` says that it's for uniquely identifying the user, an email can't really do that. For OIDC-type authentication the `sub` claim really should be used here.

Maybe a specific metadata key could be shown if populated on the entity list for administrators/UI users? I'd also like something like this

**Comment by kalafut** [comment]
@ccakes So I'm clear, are you referring to a UI change for special handling of certain metadata keys in general (e.g. hoisting them to the entity list page), and not something that is specifically OIDC related?

**Comment by ccakes** [comment]
@kalafut Yeah, pretty much. It’d be super nice to have something human readable there and it’s already possible to map arbitrary claims into the entity metadata.

Email addresses aren’t great as a unique ID as they can often change in the underlying IdP (people change their name due to marriage or other reasons etc)

**Comment by kalafut** [comment]
@ccakes Got it. Would you mind opening a new issue for this UI enhancement, linking back to this issue? It will be easier to manage that way.

**Comment by saurabh896** [comment]
Any idea how to do this on Okta?
