### ISSUE TITLE
Unable to revoke database credentials using MSSQL 

### ISSUE THREAD

**Issue by bardagadvergur** [hashicorp/vault#7725]
With only a handful of database credentials, vault is unable to revoke them if they should be revoked at the same time. The first few will go through with:
`2019-10-24T12:45:45.090Z [INFO]  expiration: revoked lease: lease_id=database/creds/Tenant_9/BcJXZkijxH7eesX5d00KCA83`

followed by a mix of:
`2019-10-24T12:45:47.548Z [ERROR] expiration: failed to revoke lease: lease_id=database/creds/Tenant_9/2SmAnSscydre5tBwFyYQAdP7 error="failed to revoke entry: resp: (*logical.Response)(nil) err: context deadline exceeded"`

and

` 2019-10-24T12:47:37.634Z [ERROR] expiration: failed to revoke lease: lease_id=database/creds/Tenant_9/7rCXRRgCecD3LRdO6U5Rme4d error="failed to revoke entry: resp: (*logical.Response)(nil) err: could not perform all sql statements: sql: database is closed"`

**To Reproduce**
Create a few credentials using a script. I've been using only 200 credentials which is enough to make it fall over:
`x=1; while [ $x -le 200 ]; do vault read database/creds/Tenant_99; x=$(( $x + 1 )); done;`

**Expected behavior**
I'd expect all credentials to be revoked but maximum revoke attempts will be reached leaving plenty of dangling SQL users and vault leases

**Environment:**
I was using 1.0.3 but upgraded to the latest 1.2.3 with no change to the behaviour
* Vault CLI Version: 1.2.3
Running a docker image on kubernetes

Vault server configuration file(s):

```hcl
    config:
        listener:
            tcp:
                address: '[::]:8200'
                cluster_address: '[::]:8201'
                tls_disable: true
                tls_prefer_server_cipher_suites: true
                tls_cipher_suites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WI$
        storage:
            mssql:
                server: xxxxxxxxxxx
                database: Hashicorp
                table: vault
                username: xxxxxxxxxxx
                password: xxxxxxxxxxx
        seal:
            awskms:
                region: us-east-2
                access_key: xxxxxxxxxxx
                secret_key: xxxxxxxxxxx
                kms_key_id: xxxxxxxxxxx

```

**Additional context**
This seems to be a similar problem that was reported here although that has to do with the mysql plugin:
https://github.com/hashicorp/vault/issues/5968

I´ve tried different settings for the max_parallel parameter but it does not seem to have any affect. Not even sure it is used by the plugin

**Comment by bardagadvergur** [comment]
My SQL deadlock shows me that the user revocation is deadlocking with it self. Hashicorp basically tries to revoke too many users at the same time.

**Comment by michelvocks** [comment]
Hi @bardagadvergur!

Sorry for the late reply. 
I've tried to reproduce your issue but was unable to do so.
Have you tried to play a bit with the maximum number of open connections from the MSSQL database plugin? https://www.vaultproject.io/api/secret/databases/mssql.html#max_open_connections
I noticed that you also use an MSSQL database as your Vault storage backend. Is this the same physical database?

Cheers,
Michel

**Comment by bardagadvergur** [comment]
Hi @michelvocks ... I haven't seen this parameter before, I did try every possible setting for the max_parallel parameter though. Do you have a recomended setting for the max_open_connections?

Vault has it's own physical database but resides on the same SQL server.

Cheers,
Gulli

**Comment by bardagadvergur** [comment]
I've tried a few settings. Right now it's like this:
`connection_details - map[connection_url:sqlserver://{{username}}:{{password}}@sql max_open_connections:1 max_parallel:2 username:user]
`

The errors are still rampant (see attachment)
![image](https://user-images.githubusercontent.com/16955820/71974448-693e3380-3209-11ea-8086-71f6ece47c7b.png)

**Comment by michelvocks** [comment]
Hi @bardagadvergur!

Thanks for the feedback. I think I have an idea where the problem could be. 
I try to reproduce this via a test.

Cheers,
Michel

**Comment by bardagadvergur** [comment]
That sounds promising. Any more info on what it could potentially be?

**Comment by spangenberg** [comment]
Hi @bardagadvergur,

I also tried to reproduce this locally with a SQL Server container, but it worked flawlessly.

Since you have AWS KMS unsealing in your config, I am curious if you might be using RDS as your SQL Server.
If this is the case could you please post your [creation](https://www.vaultproject.io/api/secret/databases/mssql.html#creation_statements) and [revocation](https://www.vaultproject.io/api/secret/databases/mssql.html#revocation_statements) statements.
RDS behaves quite a bit different when it comes to user management as mentioned here: https://www.vaultproject.io/docs/secrets/databases/mssql.html#amazon-rds
It might have something to do with that, I want to make sure we're not missing anything crucial.

Best,
Daniel

**Comment by bardagadvergur** [comment]
Hi @spangenberg ...

We are not using RDS but a SQL server running in our datacenter (not in a container).
Version info: 

Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64)   Sep 13 2019 15:49:57   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by spangenberg** [comment]
Hi @bardagadvergur,

I just tried to validate this with the SQL server version you reported and the example statements from the docs. I can't reproduce the behavior you have.

Please report the creation and revocation statements:

`vault read -field creation_statements database/roles/Tenant_99`
`vault read -field revocation_statements database/roles/Tenant_99`

Best,
Daniel

**Comment by bardagadvergur** [comment]
Hey @spangenberg. Here it is:


```
vault read -field creation_statements database/roles/Tenant_99
[CREATE LOGIN [{{name}}] WITH PASSWORD = '{{password}}';USE [Tenant_99];CREATE USER [{{name}}] FOR LOGIN [{{name}}];ALTER ROLE [db_owner] ADD MEMBER [{{name}}];]

vault read -field revocation_statements database/roles/Tenant_99
[]

```

**Comment by bardagadvergur** [comment]
Hi I again. Trying to troubleshoot this. It's as if the max_open_connections & max_parallel are not being used. When I restart the service all conections are closed but shortly afterwards I have more then 300 connections to my SQL server.

**Comment by spangenberg** [comment]
Hi @bardagadvergur,

Thanks for sharing, I was now able to reproduce the problem you described.
I'll post an update as soon as I know more about it.

**Comment by spangenberg** [comment]
I looked through the whole stack and tried to see if Vault is doing anything wrong with the connection pooling or similar, but I did not find anything that led to a problem that we can address.
In my test setup, I was able to mitigate the problem by increasing the ulimit on the Vault server as well as sequentialize the SQL statements by only allowing one open connection at a time.
I was also able to run my benchmark for multiple hours with other parameters.
Please check your ulimit max open files if this could be a bottleneck for you.
It is important to note, even when "sql: database is closed" occurred in my test setup, Vault resumed shortly afterward with the revocations as soon as it was able to connect again and revoked everything. I never ended up with any dangling leases.

Sidenote, you mentioned `max_parallel` this works for consul but not with SQLServer as storage backend, you can use those parameters with their defaults:
max_open_connections=4 max_idle_connections=0 max_connection_lifetime=0

**Comment by bardagadvergur** [comment]
Hi, I can again play with different parameters and see if I can mitigate the issue. Your comment on the error:

> It is important to note, even when "sql: database is closed" occurred in my test setup, Vault resumed shortly afterward with the revocations as soon as it was able to connect again and revoked everything. I never ended up with any dangling leases.

That does not really work in a production environment. We are monitoring our log stack and this is logged as an error. If it's not (as you are suggesting) it should be an informational message. 

Also, how did you conduct your test? In a production environment the cycle of issues & revokes are endless. I don't know how you performed your testing but perhaps you only issued creds in the beginning of the process.

**Comment by spangenberg** [comment]
I stress tested my test setup for multiple hours, here you can take a look:
https://gist.github.com/spangenberg/6e4da1624d87da9fbbfafaeab532ea95

I constantly created and revoked multiple thousands a minute and only provoked this every now and then. And after just a few seconds it recovered.

When the database can't be accessed it is obviously an error and not just info.
I'm not suggesting you should ignore it, I just state that it is not an error we can mitigate on our side.

Without more than a couple of lines of logs, I can't help you much further.
Try checking the ulimit and also run the server in log trace mode if you can.

**Comment by bardagadvergur** [comment]
Thank you for you reply and the information, much appreciated. I will see if the ulimit will help.

**Comment by spangenberg** [comment]
If that doesn't help, you can also send me your full logs per email, that I can have a look at.
Preferably with log level trace.
My email is: dspangenberg@hashicorp.com

**Comment by spangenberg** [comment]
The problem was solved offline, and I'll post the result to document the behavior.

If the **revocation_statement** is not set vault executes a default revocation procedure which executes the `master.dbo.sp_msloginmappings` stored procedure.
In a server that has multiple databases, this execution might take multiple seconds and blocks depending on the number of open connections.
The result, in this case, was that the deletion of hundreds of leases resulted in a backoff that was so large, that the go context deadline exceeded.

The solution for this specific case was to create a revocation statement with this command:
```bash
$ vault write database/roles/Tenant_99 revocation_statements="\
   USE Tenant_99; \
   IF EXISTS (SELECT name FROM sys.database_principals WHERE name = N'{{name}}') DROP USER [{{name}}] \
   IF EXISTS (SELECT name FROM master.sys.server_principals WHERE name = N'{{name}}') DROP LOGIN [{{name}}]"
```

Just as a pointer, the creation statement is the following:
```bash
$ vault read -field creation_statements database/roles/Tenant_99
[CREATE LOGIN [{{name}}] WITH PASSWORD = '{{password}}';USE [Tenant_99];CREATE USER [{{name}}] FOR LOGIN [{{name}}];ALTER ROLE [db_owner] ADD MEMBER [{{name}}];]
```
