### ISSUE TITLE
how to login on the website?

### ISSUE THREAD

**Issue by 13567436138** [hashicorp/vault#7735]
![image](https://user-images.githubusercontent.com/31508490/67546949-37502180-f730-11e9-94b9-d6da404e9f27.png)
where to find the username and password?

**Comment by chrishoffman** [comment]
Whoever is the administrator for your Vault cluster will give you the methods to how to log in.  Vault provides multiple, pluggable auth methods to accomplish logins but this is up to how your administrator configured your instance.
