### ISSUE TITLE
Unable to configure Vault with the proper plugin and connection information

### ISSUE THREAD

**Issue by Osamakhamaiseh** [hashicorp/vault#7744]
**Describe the bug**
When writing to vault's database engine the plugin exists with code 400.

**To Reproduce**
When following the Oracle Database Secrets Engine found [here](https://www.vaultproject.io/docs/secrets/databases/oracle.html), I get the following error log:
```
Error writing data to database/config/my-oracle: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/my-oracle
Code: 400. Errors:

* error creating database object: plugin exited before we could connect
```

This error appears after running the following command: 
`vault write database/config/my-oracle \                           
plugin_name=oracle-database-plugin \
connection_url="******/******@10.***.**.**:1521/EE" \
allowed_roles="vault-demo-role"
`

**Expected behavior**
I expect the data to be written to vault and I get a Success message.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.1.1
* Vault CLI Version (retrieve with `vault version`): Vault v1.1.1 (cgo)                                                                                                                                      
* Server Operating System/Architecture: Ubuntu 19.04
* Oracle plugin version : 0.1.5 linux_amd64
* Oracle instant client (basic , devel and sqlplus) packages: 12.1.0.2.0

Vault server configuration file(s):

```hcl
ui = true

listener "tcp" {
tls_disable = 1
address = "[::]:8200"
cluster_address = "[::]:8201"
}
storage "file" {
path = "/****/****/vault/data"
}
plugin_directory = "/****/****/vault/plugins"
api_addr="http://127.0.0.1:8200"
disable_mlock = true
```

**Comment by michelvocks** [comment]
Hi @Osamakhamaiseh!

It would be helpful to see the Vault log messages from your Vault instance when you create the database role since they should indicate why Vault was unable to start the plugin.

Cheers,
Michel

**Comment by Osamakhamaiseh** [comment]
Turned out to be an issue with the oracle instant client installation.
Thanks!
