### ISSUE TITLE
Azure Storage Backend caveat

### ISSUE THREAD

**Issue by ausfestivus** [hashicorp/vault#7750]
**Describe the bug**

The documentation for the [Azure Storage Backend](https://www.vaultproject.io/docs/configuration/storage/azure.html) should make it clear that the Storage Account (SA) that the Storage Container is created in must use the `Standard` performance tier.

`Premium` performance tier SAs will not work with the Azure Storage Backend. When you do your `vault operator init` it will reply with:

```shell
Error initializing: Error making API request.

URL: PUT https://127.0.0.1:8200/v1/sys/init
Code: 400. Errors:

* failed to initialize barrier: failed to persist keyring: storage: service returned error: StatusCode=400, ErrorCode=BlobTypeNotSupported, ErrorMessage=Block blobs are not supported.
RequestId:c4427571-201c-004f-0ae5-8d6a56000000
Time:2019-10-28T23:11:24.2398985Z, RequestInitiated=Mon, 28 Oct 2019 23:11:23 GMT, RequestId=c4427571-201c-004f-0ae5-8d6a56000000, API Version=2016-05-31, QueryParameterName=, QueryParameterValue=
```

**To Reproduce**

1. Create an Azure SA that uses the `Premium` Performance setting.
1. Configure Vault to use the Azure Storage Backend.
1. Run a `vault operator init`
1. Observe above error.

**Expected behavior**

Make the constraint obvious in the [Azure Storage Backend](https://www.vaultproject.io/docs/configuration/storage/azure.html) documentation. It is not currently mentioned.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.2.3
* Vault CLI Version (retrieve with `vault version`): 1.2.3
* Server Operating System/Architecture: Ubuntu 16.04 on Azure

Vault server configuration file(s):

NA

**Additional context**

Putting this here because I had to sink a fair bit of time into diagnosing the issue. If I had known upfront of the SA constraint from the doco it would have saved me a lot of time.

**Comment by ausfestivus** [comment]
Or you know, support the Performance backend as well? :-p

**Comment by kalafut** [comment]
@ausfestivus Thanks for highlighting this. The docs will definitely be updated in some way, though I do want to review the current state of Azure storage offerings and the storage backend's API usage.

**Comment by kalafut** [comment]
@ausfestivus Though General Purpose V2 accounts don't work with premium performance, BlockBlobStorage accounts do (https://azure.microsoft.com/en-us/blog/azure-premium-block-blob-storage-is-now-generally-available/ , and I tried it).
