### ISSUE TITLE
Hashicorp vault PKI with global external CA or signed global certificate

### ISSUE THREAD

**Issue by sithuyeaung** [hashicorp/vault#7753]
Hello, 
Self signed certificate rotation is very nice using hashicorp with consul-template . But may I know few thing . 
Possible uses for vault:
1. External global Root CA or Signed certificate (Let'encrypted or Godaddy) import to vault PKI ? 
2. How to rotate Signed global certificate (Let'encrypted or Godaddy certificate ) using Hashicrop PKI?

**Comment by HoffiMuc** [comment]
I am also (still) searching for a "how to import your own rootca to vault's pki engine ... anybody a pointer for me?

**Comment by hsimon-hashicorp** [comment]
Hi there! I wanted to let folks know that we have some documentation for the API that will answer these questions: https://www.vaultproject.io/api/secret/pki#config

I'll close this issue now, but please feel free to open a new one if you have a bug report or an enhancement request. You can also come visit the Discuss forum for easier question/answer formats: https://discuss.hashicorp.com/c/vault/30

Thanks!

**Comment by sebinjohn** [comment]
I think https://www.vaultproject.io/api/secret/pki#submit-ca-information section covers your requirement.

**Comment by cristovao-trevisan** [comment]
You're correct. Missed that line when checking the docs, thks for the correction.
