### ISSUE TITLE
does vault use initialization vector?

### ISSUE THREAD

**Issue by thecaddy** [hashicorp/vault#776]
I read through most the docs and maybe I'm missing something but I couldn't find anything on the cypher algorithm or what is used to encrypt the data.  More importantly is an initialization vector used?

**Comment by jefferai** [comment]
Hi,

AES-256-GCM-128 is used with a nonce length of 12 bytes. Every entry has an individual nonce, and as of 0.3 the path to the entry is used in the GCM tag to detect modification of the underlying data.

If you need more information, please feel free to ask!

**Comment by thecaddy** [comment]
great, thanks for the quick reply!
