### ISSUE TITLE
AppRole role creation API field `token_policies` actually called `policies`.

### ISSUE THREAD

**Issue by s3lph** [hashicorp/vault#7764]
**Describe the bug**

When creating a new AppRole role through the [`POST /auth/approle/role/:role_name`][api] endpoint, the resulting token policies list is always `["default"]`, no matter what policies are actually submitted to the creation request.

When using `"policies": [...]` instead of [`"token_policies": [...]`][field], the request works as intended, though.

**To Reproduce**
1. `curl -H 'X-Vault-Token: ...' https://vault:8200/v1/auth/approle/role/myrole -XPOST -d '{"token_ttl":"10m","token_max_ttl":"15m",`**`"token_policies":["mypolicy"]`**`,"period":0,"bind_secret_id":true,"token_num_uses":42}'`
2. `curl -H 'X-Vault-Token: ...' https://vault:8200/v1/auth/approle/role/myrole`
3. See `... "policies":["default"] ...`

When using `"policies"` instad of `"token_policies"` in step 1, it works as espected.

**Expected behavior**
See `... "policies":["mypolicy"] ...`

**Environment:**
* Vault Server Version (retrieve with `vault status`): **1.1.2**
* Vault CLI Version (retrieve with `vault version`): **1.1.2**
* Server Operating System/Architecture: **CentOS Linux 7**

Vault server configuration file(s):

```hcl
cluster_name = "dc1"
max_lease_ttl = "768h"
default_lease_ttl = "768h"

disable_clustering = "False"
cluster_addr = "https://10.0.0.10:8201"
api_addr = "https://10.0.0.10:8200"

# This directory is empty
plugin_directory = "/usr/local/lib/vault/plugins"

listener "tcp" {
  address = "vault:8200"
  cluster_address = "10.0.20.10:8201"
  tls_cert_file = "/etc/vault/tls/vault.crt"
  tls_key_file = "/etc/vault/tls/vault.key"
  tls_client_ca_file="/etc/vault/tls/ca.crt"
  tls_min_version  = "tls12"
  tls_prefer_server_cipher_suites = "false"
  tls_disable = "false"
}

backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
  service = "vault"
  scheme = "http"
}

ui = true
```

[api]: https://www.vaultproject.io/api/auth/approle/index.html#create-update-approle
[field]: https://www.vaultproject.io/api/auth/approle/index.html#token_policies

**Comment by calvn** [comment]
The change to have `policies` and `period` include the `token_` prefix was introduced in Vault 1.2.0 ([changelog](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#120-july-30th-2019)), which is why you're seeing the behavior of `token_policies` being ignored if provided but not with `policies`. Similarly, the `token_no_default_policy` parameter was also introduced in 1.2.0.

The documentation on the website always reflects the latest release of Vault, apologies for the confusion!

**Comment by s3lph** [comment]
Thanks for the clarification.
