### ISSUE TITLE
TLS Certificate & Key not reloaded on SIGHUP

### ISSUE THREAD

**Issue by s3lph** [hashicorp/vault#7765]
Vault 1.1.2 does not reload TLS certificate and key on `SIGHUP`. The new certificate is only presented after a restart.

**To Reproduce**
1. Replace Vault TLS certificate and key
2. `pkill -HUP vault`
3. See `==> Vault reload triggered` in the log
4. `curl -v https://vault:8200/v1/sys/init`, look at the certificate information
5. See that the old certificate is still presented
6. Restart Vault, new certificate is presented

**Expected behavior**
Vault should present the new certificate after a `SIGHUP` reload, as specified in the documentation regarding the [tls_cert_file and tls_key_file options][doc].

**Environment:**
* Vault Server Version (retrieve with `vault status`): **1.1.2**
* Vault CLI Version (retrieve with `vault version`): **1.1.2**
* Server Operating System/Architecture: **CentOS Linux 7**

Vault server configuration file(s):

```hcl
cluster_name = "dc1"
max_lease_ttl = "768h"
default_lease_ttl = "768h"

disable_clustering = "False"
cluster_addr = "https://10.0.0.10:8201"
api_addr = "https://10.0.0.10:8200"

# This directory is empty
plugin_directory = "/usr/local/lib/vault/plugins"

listener "tcp" {
  address = "vault:8200"
  cluster_address = "10.0.20.10:8201"
  tls_cert_file = "/etc/vault/tls/vault.crt"
  tls_key_file = "/etc/vault/tls/vault.key"
  tls_client_ca_file="/etc/vault/tls/ca.crt"
  tls_min_version  = "tls12"
  tls_prefer_server_cipher_suites = "false"
  tls_disable = "false"
}

backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
  service = "vault"
  scheme = "http"
}

ui = true
```

**Additional context**
This is not the first time an issue about TLS certificate reloading is opened, see #5442 for example.

[doc]: https://www.vaultproject.io/docs/configuration/listener/tcp.html#tls_cert_file

**Comment by s3lph** [comment]
The issue was caused by wrongly created TLS certificates. With the proper certificates, reloading works.

**Comment by nathan-march** [comment]
@s3lph Do you recall what the issue was with your cert? I'm running into the same thing here but can't figure out what it is.
