### ISSUE TITLE
Please release source tarballs with JS code pre-generated and bundled in

### ISSUE THREAD

**Issue by Conan-Kudo** [hashicorp/vault#7770]
**Is your feature request related to a problem? Please describe.**
I'm trying to package Vault for [Fedora](https://getfedora.org/) and CentOS, and one of the challenges with doing so is that the JavaScript dependencies aren't vendored in the source tree like the Go dependencies are. It is especially challenging, given the special tools used to integrate the JS with the Go code for the UI.

**Describe the solution you'd like**
I'd love for signed source tarballs to be uploaded to GitHub that have all the JavaScript preparation steps done already (and perhaps even the Git commit information already burned in) so that the Vault code can be built in Fedora with just `go build`.

**Describe alternatives you've considered**
The only real alternatives are:
* Not building the web UI. This is unappealing because people generally _want_ to use Vault with the web UI.
* Running the steps to prepare the tarball myself and use that. This has been tricky for me because I can't seem to get my environment right for all the steps to work properly.

**Explain any additional use-cases**
This would be useful for anyone else trying to build Vault from source and ship it in distributions or part of greater solutions. It's also useful for people trying to do completely offline builds as distributions do (internet access is not available in distro package build environments).

**Additional context**
N/A

**Comment by michelvocks** [comment]
Closing this duplicate in favor of https://github.com/hashicorp/vault/issues/7350
