### ISSUE TITLE
Secret contains tab character (%09) and cannot be deleted

### ISSUE THREAD

**Issue by csolo65** [hashicorp/vault#7779]
**Describe the bug**
Somehow we have a secret path that contains a tab (%09) character.  I have no idea how or when this particular secret was created, but it is there and causing some errors.

Listing the area shows:

vault kv list secret/MYPATH/
\-\-\-\-
Keys
10.125.127.143	/                <\-\-\-\-  Tab character is on this line before the /
Keys

The item is visible in the UI and hovering over it shows the %09 character in the URL.

However clicking on the "10.125.127.143 /" entry results in this error:
Ember Data Request GET /v1/secret/MYPATH/10.125.127.143%09/ returned a 400 Payload (Empty Content-Type) Bad Request [object Object]

Any attempt to delete the secret at any level via CLI or HTTP API just does nothing.

I've enabled trace for the server, but don't see anything when navigating to the item or attempting to delete it.

**To Reproduce**
I don't know how the secret got created in the first place.

**Expected behavior**
I'd like to be able to delete this entry somehow.

**Environment:**
* Vault Server Version 1.2.3
* Vault CLI Version 1.2.3
* Server Operating System/Architecture: Red Hat Enterprise Linux Server release 7.6 (Maipo)

Vault server configuration file(s):

```hcl
backend "file" {
  path = "/usr/local/bin/storage"
}

ui = true

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/etc/pki/tls/vault.crt"
  tls_key_file = "/etc/pki/tls/vault_ssl.key"
}

log_level = "trace"

```

**Additional context**
None

**Comment by kalafut** [comment]
If you just want to delete it, you can remove it from storage directly. In Vault's storage location it will be under `logical/<uuid of kv mount>/<your path>/...`. The name of the secret isn't encrypted. The secret isn't indexed or referenced in other structures and can simply be deleted.

**Comment by csolo65** [comment]
Thanks you.  I did not realize I could do that. Issue solved for me.
