### ISSUE TITLE
Problem with associating token and policy - HTTP APIs with Authentication

### ISSUE THREAD

**Issue by elberth90** [hashicorp/vault#779]
Hi,

I have a problem with associating generated UUID to policy. I follow steps from `http://vaultproject.io/intro/getting-started/apis.html` and when i send request:
```
curl \
    -X POST \
    -H "X-Vault-Token:$VAULT_TOKEN" \
    -d '{"value":"152AEA38-85FB-47A8-9CBD-612D645BFACA"}' \
    http://localhost:8200/v1/auth/app-id/map/user-id/5ADF8218-D7FB-4089-9E38-287465DBF37E
```

I get "Operation timed out". I have checked this for two backends: file, and consul. Also I have run it on local machine and on docker. Result is the same.
What is interesting, associating works, using CLI.

**Comment by jefferai** [comment]
Hi @elberth90 ,

Can you post your log output? Also, on some machines "localhost" is not actually `127.0.01` but instead something like `127.0.1.1`. Does it work if you try using the IP address instead of the host name?

**Comment by elberth90** [comment]
Hi, thanks for quick response,

what is surprising, I send request one more time using curl and it works, don't now how, because i did nothing more to debug the problem. What is even more interesting for me, this same request sent using postman gets timeout. Answering your question, I use IPs all the time.
Maybe it was some weird behaviour of docker or OS X, but it works right now, so there's no problem...
One more time, thanks for response and sorry for the confusion.

**Comment by jefferai** [comment]
No problem!
