### ISSUE TITLE
Support Auto Unseal through AWS KMS by assuming an AWS EC2 instance role

### ISSUE THREAD

**Issue by rafaelfonte** [hashicorp/vault#7807]
**Is your feature request related to a problem? Please describe.**
AWS user access keys should be using sparingly as those can be revoked/rotated every so often due to security policies, incurring in changes everywhere where they are used. Today, Vault only supports auto unseal in AWS by defining AWS access keys in its configuration file.

**Describe the solution you'd like**
It would be interesting to be able to rely on the AWS EC2 instance role instead to gain access on AWS KMS to retrieve the unseal key as part of the auto unseal feature. This would provide a more robust setup for the server in the long run, as access keys are more ephemeral by nature.

**Describe alternatives you've considered**
I haven't considered alternatives yet.

**Comment by jefferai** [comment]
Defining access keys is only if you want to use static keys. We use the normal AWS credential chain so if no static keys are defined we fall back to env var, credential file, instance creds.

**Comment by rafaelfonte** [comment]
@jefferai is this defined in the documentation?
