### ISSUE TITLE
new vault auth tokens don't work

### ISSUE THREAD

**Issue by wwalker** [hashicorp/vault#781]
We create 2 policies (pg_devops_secret_{ro,rw} with these hcl files:

::::::::::::::
ro.hcl
::::::::::::::

    path "sys/*" {
      policy = "deny"
    }

    path "secret/ops/configs/properties/product_groups/*" {
      policy = "read"
    }

    # Allow renewal of token leases
    path "auth/token/renew/" {
        policy = "write"
    }

::::::::::::::
rw.hcl
::::::::::::::

    path "sys/*" {
      policy = "deny"
    }

    path "secret/ops/configs/properties/product_groups/*" {
      policy = "write"
    }

    # Allow renewal of token leases
    path "auth/token/renew/" {
        policy = "write"
    }

We create the policies, then the users with these commands:

    vault policy-write pg_devops_secret_ro ro.hcl
    vault policy-write pg_devops_secret_rw rw.hcl

    vault token-create -display-name="DevOps Product Group Write" -lease=720h -policy pg_devops_secret_rw > pg_secret_rw.token
    vault token-create -display-name="DevOps Product Group ReadOnly" -lease=720h -policy pg_devops_secret_ro > pg_secret_ro.token

On my test server, this works fine.  On our QA and Staging servers, vault auth fails:

    [wwalker@stg-mcontrol1 ~]$ curl --tlsv1.2 -X GET -H "X-Vault-Token: $VAULT_TOKEN" https://stg-mcontrol1:8200/v1/auth/token/lookup/REDACTED_TOKEN
    {"lease_id":"","renewable":false,"lease_duration":0,"data":{"creation_time":1447716540,"display_name":"token-DevOps-Product-Group-ReadWrite","id":"REDACTED_TOKEN","meta":null,"num_uses":0,"path":"auth/token/create","policies":["pg_devops_secret_rw"],"ttl":2592000},"auth":null}
    [wwalker@stg-mcontrol1 ~]$ unset VAULT_TOKEN
    [wwalker@stg-mcontrol1 ~]$ vault auth REDACTED_TOKEN
    Error validating token: Error making API request.

    URL: GET https://127.0.0.1:8200/v1/auth/token/lookup-self
    Code: 403. Errors:

    * permission denied
    [wwalker@stg-mcontrol1 ~]$

**Comment by wwalker** [comment]
Both the QA and STAGE clusters were working until recently.  We assumed that the token had expired (forgot to renew them), so we recreated the users in both vault clusters.  Now, neither of the clusters will let us auth at all with the new user (we've revoked and recreated both the policies and the auth tokens multiple times).

**Comment by jefferai** [comment]
You are seeing this because your tokens do not have a policy associated that grants them access to `https://127.0.0.1:8200/v1/auth/token/lookup-self`. In 0.3 this became an authenticated endpoint.

You can either specify read access to `auth/token/lookup-self`, use the `no-verify` argument to `vault auth`, or in 0.4, the default policy that will be applied to all tokens (unless opted out, and changeable) will include access to this endpoint, as well as the `renew-self` and `revoke-self` endpoints.

**Comment by wwalker** [comment]
Thank you!

**Comment by supersaeyan** [comment]
@jefferai just curious, wouldn't it be great if the error response contained the required permissions that were missing from the resultant ACL?

Is this behaviour created in order to make things ambiguous in case of a malicious user?

**Comment by jefferai** [comment]
I'm not sure if there was a particular reason not to include that information 5.5 years ago :-D but in general Vault tries not to expose information when requests are denied.

**Comment by rashminair90** [comment]
@jefferai I am getting the same 403 error when trying to access vault DNS from another server https://vault.dummyURL.com/v1/auth/token/lookup-self
