### ISSUE TITLE
First time setting up Vault Service restarting too often and failing eventually

### ISSUE THREAD

**Issue by jeiman** [hashicorp/vault#7849]
Hi there,

I am trying to setup the Vault service on a simple DigitalOcean droplet.

I have followed the steps here: [DigitalOcean Docs](https://www.digitalocean.com/community/tutorials/how-to-securely-manage-secrets-with-hashicorp-vault-on-ubuntu-16-04) while also updating the system init file with the latest configuration from HashiCorp Vault's documentation here: [Vault Docs](https://learn.hashicorp.com/vault/operations/ops-deployment-guide#step-3-configure-systemd)

I then used the following to reload unit configuration.

`systemctl daemon-reload`

However, when I try to start the service using:
 
`sudo systemctl start vault`

It shows the following output:

```
 sudo systemctl status vault
● vault.service - "HashiCorp Vault - A tool for managing secrets"
   Loaded: loaded (/etc/systemd/system/vault.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2019-11-09 08:16:47 UTC; 4s ago
     Docs: https://www.vaultproject.io/docs/
  Process: 16942 ExecStart=/usr/local/bin/vault server -config=/etc/vault.hcl (code=exited, status=1/FAILURE)
 Main PID: 16942 (code=exited, status=1/FAILURE)
```

and then eventually it fails with the following output:

```
● vault.service - "HashiCorp Vault - A tool for managing secrets"
   Loaded: loaded (/etc/systemd/system/vault.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-11-09 08:16:52 UTC; 13s ago
     Docs: https://www.vaultproject.io/docs/
  Process: 16942 ExecStart=/usr/local/bin/vault server -config=/etc/vault.hcl (code=exited, status=1/FAILURE)
 Main PID: 16942 (code=exited, status=1/FAILURE)

Nov 09 08:16:47 ubuntu-1gb-vault systemd[1]: vault.service: Main process exited, code=exited, status=1/FAILURE
Nov 09 08:16:47 ubuntu-1gb-vault systemd[1]: vault.service: Failed with result 'exit-code'.
Nov 09 08:16:52 ubuntu-1gb-vault systemd[1]: vault.service: Service hold-off time over, scheduling restart.
Nov 09 08:16:52 ubuntu-1gb-vault systemd[1]: vault.service: Scheduled restart job, restart counter is at 3.
Nov 09 08:16:52 ubuntu-1gb-vault systemd[1]: Stopped "HashiCorp Vault - A tool for managing secrets".
Nov 09 08:16:52 ubuntu-1gb-vault systemd[1]: vault.service: Start request repeated too quickly.
Nov 09 08:16:52 ubuntu-1gb-vault systemd[1]: vault.service: Failed with result 'exit-code'.
Nov 09 08:16:52 ubuntu-1gb-vault systemd[1]: Failed to start "HashiCorp Vault - A tool for managing secrets".
```

My unit configuration:
```
[Unit]
Description="HashiCorp Vault - A tool for managing secrets"
Documentation=https://www.vaultproject.io/docs/
Requires=network-online.target
After=network-online.target
ConditionFileNotEmpty=/etc/vault/config.hcl
StartLimitIntervalSec=60
StartLimitBurst=3

[Service]
User=vault
Group=vault
ProtectSystem=full
ProtectHome=read-only
PrivateTmp=yes
PrivateDevices=yes
SecureBits=keep-caps
AmbientCapabilities=CAP_IPC_LOCK
Capabilities=CAP_IPC_LOCK+ep
CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK
NoNewPrivileges=yes
ExecStart=/usr/local/bin/vault server -config=/etc/vault/config.hcl
ExecReload=/bin/kill --signal HUP $MAINPID
KillMode=process
KillSignal=SIGINT
Restart=on-failure
RestartSec=5
TimeoutStopSec=30
StartLimitInterval=60
StartLimitIntervalSec=60
StartLimitBurst=3
LimitNOFILE=65536
LimitMEMLOCK=infinity

[Install]
WantedBy=multi-user.target
```

My Vault config:

```
listener "tcp" {
   address          = "0.0.0.0:8200"
   tls_disable      = "false"
   tls_cert_file = "/etc/letsencrypt/live/domain.com/fullchain.pem"
   tls_key_file = "/etc/letsencrypt/live/domain.com/privkey.pem"
}

storage "file" {
   path  = "/var/lib/vault/data"
 }

api_addr         = "http://0.0.0.0:8200"
```

Do I need to whitelist the `domain.com` that I am using to `/etc/hosts` as explained by DigitalOcean:

> By default, Vault will only listen for requests from the loopback interface (`lo`, or address `127.0.0.1`). This is to ensure that the service is not exposed to the public internet before it has been properly secured. You can update this later, but for now, this configuration change will let us use the `vault` command and correctly resolve the HTTPS-secured domain name.

I have followed all steps from both the Official Documentation of HashiCorp and DigitalOcean to set this up right. But for some reason, it keeps restarting and eventually not starting at all.

Kindly advise how I can fix this.

**Vault Version: 1.2.3**

Thank you.

**Comment by jeiman** [comment]
Update: When I run vault command: `vault server -config=/etc/vault.hcl`, the server works.
```
==> Vault server configuration:

             Api Address: http://0.0.0.0:8200
                     Cgo: disabled
         Cluster Address: https://0.0.0.0:8201
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "enabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
                 Storage: file
                 Version: Vault v1.2.3

==> Vault server started! Log data will stream in below:
```

Something must be wrong with the system unit configuration I suppose.

**Comment by jeiman** [comment]
Update: I have fixed this by using an unorthodox, hacky step. 
1. I modified the system unit configuration syntax, particularly `Restart=on-failure` to `Restart=on-abnormal` to see if there are any error messages being thrown.
2. It turns out to be a Permissions issue with Vault reading the SSL PEM files that LetsEncrypt had generated for me.
3. Fixed the issue and reverted back the changes to `Restart=on-failure`.

Upon fixing all of that, I did some Googling and found a command called `journalctl` that allows you to check the `systemd` logs. I simply ran the command and now I have a faster way of checking the service logs: `journalctl -u vault`.

I'm going to create a PR for this to update the documentation to let other users know that you can check the logs using such command.

**Comment by bexruzdiv** [comment]
how you did fix the issue. with how permission
