### ISSUE TITLE
vault does not build on OpenBSD... (and i was sleepy everything is fine :))

### ISSUE THREAD

**Issue by eau-u4f** [hashicorp/vault#787]
After following installation instruction, typing 'make' start the process but never succeed,
any idea why it does not build?

Logs:
...
--- FAIL: TestSysUnmount (0.01s)
        http_test.go:75: err: dial tcp 127.0.0.1:25966: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/ad18bd82-8459-d2e1-6497-2c9e1f98a163/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/6e77bc35-bc6d-fe5f-54f0-e9a3d59592d1/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
2015/11/19 02:55:24 [INFO] core: vault is unsealed
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/ad18bd82-8459-d2e1-6497-2c9e1f98a163/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/6e77bc35-bc6d-fe5f-54f0-e9a3d59592d1/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
--- FAIL: TestSysTuneMount (0.00s)
        testing.go:50: error authenticating: Get http://127.0.0.1:19454/_test/auth?token=534b118d-9160-eb98-c679-01918f62ea76: dial tcp 127.0.0.1:19454: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/37a525d5-1381-aa6a-ccf9-e7a67e25308b/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/ccc63be6-5dd6-d352-0d40-b3bc944a38e1/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
2015/11/19 02:55:24 [INFO] core: vault is unsealed
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/37a525d5-1381-aa6a-ccf9-e7a67e25308b/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/ccc63be6-5dd6-d352-0d40-b3bc944a38e1/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
--- FAIL: TestSysPolicies (0.02s)
        testing.go:50: error authenticating: Get http://127.0.0.1:18536/_test/auth?token=f575a6fd-98b7-128b-c2bf-41e96636aac8: dial tcp 127.0.0.1:18536: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/be6fd104-2100-8477-45cf-2ad30d9f3e49/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/a189c0d0-cb69-6ba6-c84e-9c7ec5bcacaa/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
2015/11/19 02:55:24 [INFO] core: vault is unsealed
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/be6fd104-2100-8477-45cf-2ad30d9f3e49/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/a189c0d0-cb69-6ba6-c84e-9c7ec5bcacaa/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
--- FAIL: TestSysReadPolicy (0.01s)
        testing.go:50: error authenticating: Get http://127.0.0.1:42263/_test/auth?token=4e8eec09-71b0-ff65-4908-cf2fe0b61e88: dial tcp 127.0.0.1:42263: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/74fec664-46cb-4981-1df1-342759a6f347/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/e40cf39d-a1fa-bbf1-1342-e49a4718cf69/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
2015/11/19 02:55:24 [INFO] core: vault is unsealed
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/74fec664-46cb-4981-1df1-342759a6f347/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/e40cf39d-a1fa-bbf1-1342-e49a4718cf69/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
--- FAIL: TestSysWritePolicy (0.01s)
        testing.go:50: error authenticating: Get http://127.0.0.1:44129/_test/auth?token=fde1f2eb-5f9e-48e2-f8bd-af234797148d: dial tcp 127.0.0.1:44129: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/b0bd6987-9e2f-a6b3-bcaf-2c3fd5dd5158/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/ea89caa3-7861-d31d-e59e-377ebd2732c4/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
2015/11/19 02:55:24 [INFO] core: vault is unsealed
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/b0bd6987-9e2f-a6b3-bcaf-2c3fd5dd5158/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/ea89caa3-7861-d31d-e59e-377ebd2732c4/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
--- FAIL: TestSysDeletePolicy (0.01s)
        testing.go:50: error authenticating: Get http://127.0.0.1:31659/_test/auth?token=00ceb2b5-8a7f-4d95-e844-550f779eea6f: dial tcp 127.0.0.1:31659: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/a17bfa63-4ae9-6d0d-2aa7-e3cdb85edcde/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/0752a830-15c9-a10d-9014-9bf962abb053/
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
2015/11/19 02:55:24 [INFO] core: vault is unsealed
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/a17bfa63-4ae9-6d0d-2aa7-e3cdb85edcde/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/0752a830-15c9-a10d-9014-9bf962abb053/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
--- FAIL: TestSysRekeyInit_Status (0.01s)
        testing.go:50: error authenticating: Get http://127.0.0.1:25613/_test/auth?token=4c16c11e-4724-cbfa-5d93-1b364e1643cb: dial tcp 127.0.0.1:25613: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/dd812995-b531-5f8f-4990-48618e02d6f1/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/190a439c-e124-e957-9c9e-547c0daf3cd3/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
2015/11/19 02:55:24 [INFO] core: vault is unsealed
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/dd812995-b531-5f8f-4990-48618e02d6f1/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/190a439c-e124-e957-9c9e-547c0daf3cd3/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
--- FAIL: TestSysRekeyInit_Setup (0.01s)
        testing.go:50: error authenticating: Get http://127.0.0.1:41277/_test/auth?token=f39a1881-ceca-00b6-9a60-5a20859ccf6b: dial tcp 127.0.0.1:41277: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/8b78a9c4-c9ea-ef13-8466-298fc8adf81b/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/ac07c5ec-8f86-a551-c9a7-00bf1b26d1ca/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
2015/11/19 02:55:24 [INFO] core: vault is unsealed
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/8b78a9c4-c9ea-ef13-8466-298fc8adf81b/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/ac07c5ec-8f86-a551-c9a7-00bf1b26d1ca/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
--- FAIL: TestSysRekeyInit_Cancel (0.05s)
        testing.go:50: error authenticating: Get http://127.0.0.1:40723/_test/auth?token=f6f90870-ed3a-3bc9-db25-46079f0e98c8: dial tcp 127.0.0.1:40723: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/3a668dfa-e361-27d0-b9d1-47ac692add1c/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/221e0068-8aba-2394-17d5-fd124d4332eb/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
2015/11/19 02:55:24 [INFO] core: vault is unsealed
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/3a668dfa-e361-27d0-b9d1-47ac692add1c/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/221e0068-8aba-2394-17d5-fd124d4332eb/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
--- FAIL: TestSysRekey_badKey (0.00s)
        testing.go:50: error authenticating: Get http://127.0.0.1:33869/_test/auth?token=815f7085-148d-61d8-2ddb-3e9ac385504c: dial tcp 127.0.0.1:33869: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/d5ac6096-8ace-6713-8b3e-dfbe8dca4fb0/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/e4749706-e2fd-856d-a7c9-d582f72fbf47/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
2015/11/19 02:55:24 [INFO] core: vault is unsealed
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/d5ac6096-8ace-6713-8b3e-dfbe8dca4fb0/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/e4749706-e2fd-856d-a7c9-d582f72fbf47/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
--- FAIL: TestSysRekey_Update (0.00s)
        testing.go:50: error authenticating: Get http://127.0.0.1:17209/_test/auth?token=5ede0d07-f41c-ae75-542f-83d999d5ad57: dial tcp 127.0.0.1:17209: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/63218649-acc4-5965-e2aa-294c44ed0fc7/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/3589df59-0813-108a-0fee-ff5c831bd9ff/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
2015/11/19 02:55:24 [INFO] core: vault is unsealed
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/63218649-acc4-5965-e2aa-294c44ed0fc7/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/3589df59-0813-108a-0fee-ff5c831bd9ff/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
--- FAIL: TestSysRotate (0.00s)
        testing.go:50: error authenticating: Get http://127.0.0.1:19518/_test/auth?token=f6186cb8-26d8-4351-f9c3-efb7ea08db40: dial tcp 127.0.0.1:19518: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/80aefaf7-281d-837e-ad9d-a3927bbde8f5/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/be1b21dd-b967-a9f2-8c42-a8b66f224e3f/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
--- FAIL: TestSysSealStatus (0.00s)
        sys_seal_test.go:20: err: Get http://127.0.0.1:38822/v1/sys/seal-status: dial tcp 127.0.0.1:38822: socket: too many open files
--- FAIL: TestSysSealStatus_uninit (0.00s)
        sys_seal_test.go:44: err: Get http://127.0.0.1:37953/v1/sys/seal-status: dial tcp 127.0.0.1:37953: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/d5c15bb5-e6d6-2755-da94-afe17e966859/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/31ca9060-6ea1-d006-3c1d-08fa6ca9169e/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
2015/11/19 02:55:24 [INFO] core: vault is unsealed
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/d5c15bb5-e6d6-2755-da94-afe17e966859/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/31ca9060-6ea1-d006-3c1d-08fa6ca9169e/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
--- FAIL: TestSysSeal (0.00s)
        testing.go:50: error authenticating: Get http://127.0.0.1:47818/_test/auth?token=9a07a5aa-7328-7fe2-8189-cebec4debe1a: dial tcp 127.0.0.1:47818: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/b059a4b8-1e79-0b5d-b1e4-d5679b9cbec8/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/ca82f0db-4257-7c4f-8c20-e9fbdec72cdb/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
2015/11/19 02:55:24 [INFO] core: vault is unsealed
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/b059a4b8-1e79-0b5d-b1e4-d5679b9cbec8/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/ca82f0db-4257-7c4f-8c20-e9fbdec72cdb/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
--- FAIL: TestSysSeal_unsealed (0.00s)
        testing.go:50: error authenticating: Get http://127.0.0.1:36834/_test/auth?token=8b1601ff-d33f-c2fe-c349-21ec91b6f1af: dial tcp 127.0.0.1:36834: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/fd42a0dc-f591-db93-25e3-77178e3e7713/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/a26e66d9-7dc0-eeba-a0c0-9d85352acdb3/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
--- FAIL: TestSysUnseal (0.00s)
        http_test.go:75: err: Put http://127.0.0.1:16996/v1/sys/unseal: dial tcp 127.0.0.1:16996: socket: too many open files
2015/11/19 02:55:24 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/11/19 02:55:24 [INFO] core: post-unseal setup starting
2015/11/19 02:55:24 [INFO] core: mounted backend of type generic at logical/1e987a5f-a739-25d6-bde4-e8ccfe7df1f6/
2015/11/19 02:55:24 [INFO] core: mounted backend of type cubbyhole at logical/5addc277-6ddc-b3d9-f0fc-a52846931457/
2015/11/19 02:55:24 [INFO] core: mounted backend of type system at sys/
2015/11/19 02:55:24 [INFO] core: post-unseal setup complete
2015/11/19 02:55:24 [INFO] core: root token generated
2015/11/19 02:55:24 [INFO] core: pre-seal teardown starting
2015/11/19 02:55:24 [INFO] rollback: starting rollback manager
2015/11/19 02:55:24 [INFO] rollback: stopping rollback manager
2015/11/19 02:55:24 [INFO] core: pre-seal teardown complete
--- FAIL: TestSysUnseal_badKey (0.00s)
        http_test.go:75: err: Put http://127.0.0.1:20938/v1/sys/unseal: dial tcp 127.0.0.1:20938: socket: too many open files
--- FAIL: TestSysUnseal_Reset (0.00s)
        http_test.go:75: err: Put http://127.0.0.1:11803/v1/sys/init: dial tcp 127.0.0.1:11803: socket: too many open files
FAIL
FAIL    github.com/hashicorp/vault/http 0.637s
ok      github.com/hashicorp/vault/logical      0.021s
ok      github.com/hashicorp/vault/logical/framework    0.085s
ok      github.com/hashicorp/vault/logical/testing      0.078s
ok      github.com/hashicorp/vault/physical     0.144s
ok      github.com/hashicorp/vault/shamir       0.031s
ok      github.com/hashicorp/vault/vault        5.462s
?       github.com/hashicorp/vault/version      [no test files]
godep: go exit status 1
*** Error 1 in /home/eau/dev/go/src/github.com/hashicorp/vault (Makefile:22 'test')

**Comment by jefferai** [comment]
Hi @eau-u4f 

It looks like what is failing is a basic function in the Go standard library, when trying to make a network connection. Some Googling around may help...I found this pretty quickly: https://measureofchaos.wordpress.com/2011/07/27/openbsd-file-descriptor-limits/

**Comment by eau-u4f** [comment]
Damn I can't believe i asked this... sorry for bothering with such  trivial question I don't know why I did not see it.. it was probably too late at night and did not read/think... thx
