### ISSUE TITLE
Send json policy using API

### ISSUE THREAD

**Issue by elberth90** [hashicorp/vault#789]
HI,

I have a problem with sending json policy through API, I send it int this way:
```
curl -X PUT -H "X-Vault-Token: XXX" -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW" -H "Cache-Control: no-cache" -F "rules=@acl.json" 'http://IP_ADDR/v1/sys/policy/aaa'
```

Json inside file:
```
{
    "path": {
        "secret/*": {
            "policy": "write"
        },
        "auth/token/lookup-self": {
            "policy": "read"
        }
  }
}
```

I get `{"errors":["Failed to parse JSON input: invalid character '-' in numeric literal"]}` error. Guys what I'm doing wrong?

**Comment by jefferai** [comment]
Hi @elberth90 ,

The immediate thing that I can see is that you are attempting to send the JSON file as a form parameter, but Vault is expecting an actual JSON object with a "rules" key containing a value that is the (escaped) JSON policy. You can see an example of such a policy being used with curl's `-d` parameter here:

https://groups.google.com/d/msg/vault-tool/wq2qF_RBRv0/zvDFZMfdAAAJ

**Comment by elberth90** [comment]
Thanks @jefferai, it works!

I was looking on https://github.com/hashicorp/vault/issues/582 and there was no info about that and also https://www.vaultproject.io/docs/http/sys-policy.html is a little bit confusing, especially this part `rules required The policy document.`, because it suggest that you need to send a form-data with key: rules and file as a value.

Thanks one more time for quick answer

**Comment by jefferai** [comment]
Glad it's fixed!

**Comment by thalesfsp** [comment]
@jefferai I'm trying to create a policy via REST, without success :(

Code:

```
// Revoke aws credentials

request
  .post('http://localhost:8200/v1/sys/policy/qwe')
  .send({
  "rules": "path \"secret/configurations/environments/global\" {\n  policy = \"read\"\n}\npath \"secret/configurations/environments/development\" {\n  policy = \"read\"\n}\npath \"secret/configurations/applications/hhh/global\" {\n  policy = \"read\"\n}\npath \"secret/configurations/applications/hhh/development\" {\n  policy = \"read\"\n}\npath \"aws/creds/hhh-development\" {\n  policy = \"read\"\n}\npath \"sys/revoke/aws/creds/hhh-development/*\" {\n  policy = \"write\"\n  capabilities = [\"update\"]\n}"
})
  .set('X-Vault-Token', 'YYY)
  .set('Content-Type', 'application/json; charset=utf-8')
  .redirects(0)
  .end(function(err, res){
    if (err || !res.ok) {
      console.log('Oh no! error');
    } else {
      console.log('yay got ' + JSON.stringify(res.body));
    }
  });
```

Can you help? I'm using NodeJS superagent library.

Cheers!

**Comment by jefferai** [comment]
Hi @thalesfsp ,

I recommend first creating a JSON file containing the policy and using the CLI policy-write command to upload it. That way you can better understand whether an issue is with your rules/JSON or with how it's being escaped or put into the library.

**Comment by thalesfsp** [comment]
@jefferai I did, and this is what we have been using. We want to use the REST interface, not the CLI. Also, in the API docs, there's no example, it just says...: `rules required The policy document.
`. Can you help, please? Thanks

**Comment by jefferai** [comment]
Unfortunately I'm not sure I can. If your JSON policy is working just fine through the CLI, the CLI is simply an API client and nothing more. So this leads me to believe that the error is somewhere in your code. You haven't said what isn't working, what error messages you get, what you see in the Vault log, or anything else, so I have no further idea what the issue might be.
