### ISSUE TITLE
Vault UI - Some secret are displayed as blank when clicking on the icon to reveal

### ISSUE THREAD

**Issue by Lebvanih** [hashicorp/vault#7895]
**Describe the bug**
Using the vault UI of Vault 1.3.0, if a key in a secret (kv2) contains a ".", the "copy" button doesn't work, and the "show" button show a blank value. Using the "json" toogle, allow to display properly the secret in json format and workaround the issue.

**To Reproduce**
Create a secret in KV2 with a "." in the key (such as root.password) and any value. Save then try to display the newly created field. It will appear as blank

**Expected behavior**
We expect to be able to see and copy the value.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.0
* Vault CLI Version (retrieve with `vault version`): 1.3.0
* Server Operating System/Architecture: Debian 10.1. Using 3 servers for consul backend and 3 other server for vault.

Vault server configuration file(s):

```listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/etc/vault.d/server.pem"
  tls_key_file = "/etc/vault.d/server-key.pem"
  tls_disable_client_certs= "true"

}

ui=true
storage "consul" {
  scheme        = "https"
  tls_ca_file   = "/etc/vault.d/consul-ca.pem"
  tls_cert_file = "/etc/vault.d/client.pem"
  tls_key_file  = "/etc/vault.d/client-key.pem"
  token = "<token>"
}
```

**Comment by noelledaley** [comment]
Hey there! Thanks for catching this bug. I've added it to our queue. Stay tuned for a fix!

**Comment by noelledaley** [comment]
Fixed! This will be included in our next release. Thanks again for bringing this to our attention!
