### ISSUE TITLE
Feedback on the UI in Vault when a sentinel policy rejects it.

### ISSUE THREAD

**Issue by dunkelbunt1** [hashicorp/vault#7914]
Let's assume that I currently have a Vault server set up and a sentinel policy configured ,which restricts certain values  i.e. 
if a key is named password the value needs to match minimum 3 out of 5 criterias.
If I now login via the UI and try to save the secret which does not match the criterias, I don't get any feedback on the UI. In order to see why it didn't let me safe the password I have to either do it via the CLI or by enabling the debugging mode on my browser on go through the body of that request to see the reason.

**Comment by catsby** [comment]
Hello @dunkelbunt1  - Support for enterprise customers needs to go through our enterprise support portal. Reporting through our enterprise support portal ensures that we can comply with contractually obligated SLAs around customer support requests, and that a support engineer or technical account manager can track the issue from report to resolution. As you mention using Sentinel policies I assume you're using Enterprise, and issues for enterprise are typically tracked separately. 

I'm going to close this for now. Please let us know if you feel this is an issue that is not specific to enterprise though, and we can re-evaluate. Thanks!
