### ISSUE TITLE
API Explorer is removing "\n" in Curl Output Field

### ISSUE THREAD

**Issue by devhopsde** [hashicorp/vault#7925]
**Describe the bug**
When using the api-explorer, "\n" get deleted in the Curl output field. Because of this it is not possible to copy the content of the curl field and rerun it in any shell. 

**To Reproduce**
- generate a pki secret engine
- open api explorer in ui
- go to "[POST] <your pki secret engine>/sign/{role}"
- use a request body like this: (\n is used between BEGIN CERTIFICATE REQUEST and END CERTIFICATE REQUEST)
`{
 "csr": "-----BEGIN CERTIFICATE REQUEST-----\nMIIEsDCCApgCAQAwazELMAkGA1UEBhMCWFgxFTATBgNVBAcMDERlZmF1bHQgQ2l0eTEcMBoGA1UECgwTRGVmYXVsdCBDb21wYW55IEx0ZDEnMCUGA1UEAwwedmx0MDA5ODkuYWRtLmNsb3VkLml0emxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxA==\n-----END CERTIFICATE REQUEST-----",
"format": "pem"
}`

**Expected behavior**
The Output Field returns the complete curl command with "\n" within the csr field, so i can copy the complete command and rerun it anywhere else.

**Environment:**
* Vault Server Version 1.3.0
* RedHat/CentOS

**Comment by cipherboy** [comment]
I no longer see this bug:

```bash
curl -X 'POST' \
  'http://localhost:8200/v1/pki/sign/admin' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -H 'X-Vault-Token: devroot' \
  -d '{
  "alt_names": "string",
  "common_name": "string",
  "csr": "-----BEGIN CERTIFICATE REQUEST-----\nMIIEsDCCApgCAQAwazELMAkGA1UEBhMCWFgxFTATBgNVBAcMDERlZmF1bHQgQ2l0eTEcMBoGA1UECgwTRGVmYXVsdCBDb21wYW55IEx0ZDEnMCUGA1UEAwwedmx0MDA5ODkuYWRtLmNsb3VkLml0emxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxA==\n-----END CERTIFICATE REQUEST-----",
  "exclude_cn_from_sans": false,
  "format": "pem",
  "ip_sans": [
    "string"
  ],
  "issuer_ref": "default",
  "not_after": "string",
  "other_sans": [
    "string"
  ],
  "private_key_format": "der",
  "serial_number": "string",
  "ttl": 0,
  "uri_sans": [
    "string"
  ]
}'
```

Looks like this might've been a bug in an old version of API Explorer; closing.
