### ISSUE TITLE
Correct the name and labels when report metrics to stackdriver

### ISSUE THREAD

**Issue by hixichen** [hashicorp/vault#7928]
**Current issue**
vault 1.3 has the feature to report metrics directly to stackdriver. 

But it has issue with current code implementation. 

Right now, it created a metrics descriptor every time when send the metrics data,  without set the labels. And, the metric on stackdriver looks as below:
```
 metric.type="custom.googleapis.com/go-metrics/vault.core.handle_login_request"
```

Note:  https://cloud.google.com/monitoring/quotas
```
Limit of custom metric descriptors per project is 500.
And,  This limit is imposed by Stackdriver Monitoring. Other services might impose lower limits.
```
With current code,  vault can easily have more than 500 metric descriptors.

**what shoult it looks like**

Use limit number of metric descriptors while using label to mark the metric.

For example:
```
metric.type="custom.googleapis.com/go-metrics/vault"
metric.label."metric"="vault.core.handle_login_request"
```

please refer: [opencensus](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/master/stats.go) to check how they are using go-metrics-stackdriver.

**Comment by hixichen** [comment]
**what if you already using it?**
Rollback your vault deployment, stop send new metrics data.
And, use my script to delete them all.

./delete.sh myprojectid

```
#!/bin/bash

project_id=$1
bearer_token=$(gcloud auth application-default print-access-token)

curl -k \
 -H "Authorization: Bearer $bearer_token"  \
 -H "Content-Type: application/json" \
 -X GET https://monitoring.googleapis.com/v3/projects/"$project_id"/metricDescriptors  | jq ".metricDescriptors | .[].name" | grep "go-metrics" > .metricDescriptors


input="./.metricDescriptors"
while IFS= read -r line
do
  name=$(echo "$line" | tr -d '"')
  curl -k \
  -H "Authorization: Bearer $bearer_token"  \
  -H "Content-Type: application/json" \
  -X DELETE https://monitoring.googleapis.com/v3/"$name"
done < "$input"


rm .metricDescriptors
```

**Comment by jefferai** [comment]
@tam7t of interest to you probably

**Comment by tam7t** [comment]
Ack I'll take a look.

**Comment by tam7t** [comment]
The opencensus exporter has a [1:1 mapping](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/59d068f8d8ff5b653916aa30cdc4e13c7f15d56e/stats.go#L559-L564) between a 'view' and a stackdriver `MetricDescriptor`. This is similar to go-metric's `key`, so I'm not sure that moving more parameters to labels (which go-metric supports but is an open issue here #5326).

I'm curious how vault pushed you over 500 limit though. My instance (just the KV secret engine, GCS backend) only at 64:

```
$ curl -H "Authorization: Bearer $(gcloud auth print-access-token)" \
  -H "Content-Type: application/json" \
  https://monitoring.googleapis.com/v3/projects/$PROJECT_ID/metricDescriptors | \
  jq .metricDescriptors[].name | grep custom.googleapis.com | wc -l
```

Do you use a lot of the `database` secret engines? It [looks like](https://www.vaultproject.io/docs/internals/telemetry.html) those include parameters in the metric name which could increase cardinality.

Also if you did not include `disable_hostname = true` in your config then you could end up with hostnames as part of your `MetricDescriptor`. That (especially when running vault on k8s) could also lead to this issue.

**Comment by hixichen** [comment]
- disable_hostname was set to true. 
- we are not running in k8s.


Assume: Our Vault had **X**  namespace, each namespace had 4 KV mounts, the identity mount, the cubbyhole mount, and 2 Auth mounts = 8 mounts.

X * 8 =  8X  mounts.

Each mount tried to create the following custom metric descriptors.
```
vault.route.create.<mount>
vault.route.list.<mount>
vault.route.read.<mount>
vault.route.rollback.<mount>
vault.rollback.attempt.<mount>
````

That is **40X** custom metric descriptors.

what if X is larger than 15? or 20?

**Comment by tam7t** [comment]
Ah, it looks like the request router also include the [mount name in the metric name](https://github.com/hashicorp/vault/blob/b2aeb52d111cd82a73ce6698508f3365402abdbe/vault/router.go#L507-L508), so I could see that also resulting in ~10 metrics per mount.

**Comment by shwuandwing** [comment]
It is very desirable if the number of metric descriptors does not have a linear relationship with the number of mounts or namespaces.

**Comment by tam7t** [comment]
I've created https://github.com/google/go-metrics-stackdriver/pull/3 as one strategy to address this by adding an interface to allow for extracting labels from metric names and a function to do metric mapping for the current metrics in vault specifically.

**Comment by michelvocks** [comment]
Closing this because #8073 has been merged.
