### ISSUE TITLE
debian package?

### ISSUE THREAD

**Issue by thecaddy** [hashicorp/vault#793]
Is there a debian or ubuntu vault package?  I can't seem to be able to find one.  I'd like to avoid managing my own install scripts if possible.

**Comment by jefferai** [comment]
I honestly do not know which distributions do or do not package Vault. We do not ourselves produce such a package at this time.

**Comment by msabramo** [comment]
Haven't found one for Vault, but found one for Consul:

https://github.com/bcandrea/consul-deb

Perhaps that could be adapted for Vault (and ideally shared on GitHub as well).

**Comment by msabramo** [comment]
Oh, just found this:

https://github.com/Buzer/vault-deb

**Comment by elopio** [comment]
There is a [vault snap](https://github.com/snapcrafters/vault) in the store.

**Comment by nyetwurk** [comment]
Snap is not acceptable.
