### ISSUE TITLE
Question:  LDAP backend user password storage

### ISSUE THREAD

**Issue by azenk** [hashicorp/vault#794]
It looks like the LDAP auth backend stores the user password to facilitate renewal.  Is this indeed the case?  If so, how is it stored?  Would it be feasible to disable this if only non-renewable tokens were issued?

**Comment by jefferai** [comment]
It looks like it does do this. It stores it internally in Vault storage, so it's AES-GCM encrypted at rest like the rest of Vault's store. Renewability is not something that can be turned off on the backend right now, so storing the password cannot currently be disabled.

**Comment by azenk** [comment]
Got it.  Would it be feasible to allow renewability to be disabled in the future re-write of the LDAP auth backend?

**Comment by jefferai** [comment]
We're actually planning on making that a settable option across all backends, although they will need rewrites to support it -- the LDAP is one of the first on that list though. So this will happen eventually!

**Comment by azenk** [comment]
Awesome!  Thanks for the info.

**Comment by jefferai** [comment]
Sure. I'm going to close this for now as it's going to get solved eventually in the natural course of things (1-2 releases after 0.4 in the current plan), but feel free to ping back on it if you want status.
