### ISSUE TITLE
Bug Vault UI - can't choose sign in method from Safari

### ISSUE THREAD

**Issue by gabyfulchic** [hashicorp/vault#7942]
**Describe the bug**
The bug is a 400 bad request when reaching "method" on the vault sign-in page.
But only when using Safari.

**To Reproduce**
1. Go to vault url
2. Go to sign in "methods" 
3. And see in the console the "400 bad request"

**Expected behavior**
Normally you can choose to sign in by token, ldap, github etc ...

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.1.3
* Vault CLI Version (retrieve with `vault version`): 1.1.3
* Server Operating System/Architecture: Debian 9

Can you reproduce it yourself ? ;) 

Warmly,
FULCHIC gaby.

**Comment by noelledaley** [comment]
Hey there! Thanks for filing this issue. Could you share a screenshot or additional steps to reproduce? Which auth method are you selecting from the dropdown? Let me know and we can dig more into it. Thanks!

**Comment by gabyfulchic** [comment]
Hello @noelledaley,

Yeah sure, that's it : 

![Screen Recording 2019-12-04 at 10 28 21 AM](https://user-images.githubusercontent.com/22600727/70131442-9afc3180-1682-11ea-9eb1-eec8ce372820.gif)

You're welcome! 
And thanks for responding that fast !

**Comment by noelledaley** [comment]
Hi @gabyfulchic, thanks for the screenshot! What version of safari are you using? I still haven't been able to reproduce this unfortunately. :/

**Comment by gabyfulchic** [comment]
Hey @noelledaley,

I’m using safari 13.0.1 
(14608.2.11.1.11)

Can i give you More informations or is it ok now ?😁

Best Regards,

**Comment by noelledaley** [comment]
Hi @gabyfulchic, thanks for the information. We still haven't been able to reproduce this, which is strange. Could disabling your browser extensions or opening the page in a private window? Thanks!

**Comment by gabyfulchic** [comment]
We've tried without extensions and in a private window, it's the same thing. A strange shape is appearing and safari went in not responding and we have to force quit it !
As you can see on the .gif above. 😁

**Comment by noelledaley** [comment]
A-ha! I think we found the culprit. Sounds like this is an issue with Safari on Mojave. We had the [same problem](https://github.com/hashicorp/atlas/pull/8149) in Terraform Cloud. Thanks for bringing this to our attention -- I'm working on a fix! 🔧

**Comment by gabyfulchic** [comment]
Thank you for your time @noelledaley and good luck !

**Comment by noelledaley** [comment]
Thanks @gabyfulchic! This is fixed and will be included in our 1.3.1 release. :)
