### ISSUE TITLE
Vault API explorer is returning as Failed to load API definition error message

### ISSUE THREAD

**Issue by Nagarajuwas** [hashicorp/vault#7946]
while opening vault API explorer on vault UI it is returning the below error message. I am not using the root permissions and I am using custom role. So kindly suggest me any policy needs to be added to the custom role.

Error message:
Errors
Hide
 
Fetch errorundefined /v1/sys/internal/specs/openapi

**Comment by jefferai** [comment]
What version of Vault?

**Comment by Nagarajuwas** [comment]
Vault version is  1.3.0. If I log in with root token I am able to use API explore. But if I log in with custom admin role it is showing the above error messages.

**Comment by noelledaley** [comment]
Hey there! Thanks for pointing this out. Can you share the policies attached to your custom role? If the role has the default ACL policy it should have access to the API explorer.

**Comment by Nagarajuwas** [comment]
i have found the issue on my test server. this issue is occurred due to syslog audit is enabled on my environment.So after disabling the syslog api explorer is working as expected.

this is the erro message we have got and this issue is related to same request number.

 [ERROR] audit: backend failed to log response:  backend=syslog/ error=write unixgram ->/var/run/log: write: message too long             
[ERROR] core: failed to audit response: request_path=sys/mounts error=1 error occurred:                 

* no audit backend succeeded in logging the response             
 [INFO ] expiration: revoked lease: lease_id=auth/token/create/f5ea536db741dbc60410fc51e9c7daca70a2dd43

https://github.com/hashicorp/vault/issues/3617

**Comment by jefferai** [comment]
There is a known issue about syslog, see the box in the device page: https://www.vaultproject.io/docs/audit/syslog.html

**Comment by noelledaley** [comment]
@Nagarajuwas Oh good, glad you were able to locate the problem. Thanks for updating us!
