### ISSUE TITLE
Missing documentation for sys/internal/counters

### ISSUE THREAD

**Issue by jweissig** [hashicorp/vault#7947]
**Describe the bug**
PR #7541 added new endpoints `sys/internal/counters/tokens` and `sys/internal/counters/entities` under `sys/internal/counters` but the corresponding documentation is missing from the [System Backend](https://www.vaultproject.io/api/system/index.html) area. This went live with Vault 1.3.

**To Reproduce**
1. Visit the [System Backend](https://www.vaultproject.io/api/system/index.html)
2. Look for `sys/internal/counters`, `sys/internal/counters/tokens`, or `sys/internal/counters/entities`
3. See they are missing

**Expected behavior**
Find the documentation.

I'll likely submit a PR for this but wanted to track it before I forgot.

**Comment by jefferai** [comment]
We don't usually document internal endpoints as we don't want others to use/rely on them. I'm not sure why two of them are documented.

**Comment by jweissig** [comment]
Cool, thanks Jeff. I'll just close this then. Thank for the heads up.
