### ISSUE TITLE
Importing and exporting vault data

### ISSUE THREAD

**Issue by pandrew** [hashicorp/vault#797]
Running consul i tried to backup local directory where vault keeps its data. After moving to a new consul vault wants to initiate a new database in consul and not use the one i "imported". It would be great if there was a way to export/import or backup the database in some way if fore instance you wound want to move the vault data to another machine.

**Comment by jefferai** [comment]
Some people are using consul-replicate (https://github.com/hashicorp/consul-replicate) for this purpose. If you want to move the data to another machine, I would shut down the Vault servers, use consul-replicate to migrate the Consul data, and then start up the Vault servers against the other Consul instance(s).
