### ISSUE TITLE
vault server -dev runs into a panic

### ISSUE THREAD

**Issue by shibumi** [hashicorp/vault#7978]
**Describe the bug**
We are desperately trying to build vault for Arch Linux. The build works fine, but we our binary runs into this issue when invoking: `vault server -dev`:
```
❯ vault server -dev
==> Vault server configuration:

             Api Address: http://127.0.0.1:8200
                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
           Recovery Mode: false
                 Storage: inmem
                 Version: Vault v1.3.0
             Version Sha: 0f5c835d1cf91c00d01cb29a0048732d91357afa+CHANGES

panic: unreachable

goroutine 1 [running]:
github.com/hashicorp/vault/http.assetFS(0xc000226730)
	/build/vault/src/src/github.com/hashicorp/vault/http/bindata_assetfs.go:223 +0x133
github.com/hashicorp/vault/http.Handler(0xc0003893b0, 0xc0003893b0, 0x1)
	/build/vault/src/src/github.com/hashicorp/vault/http/handler.go:150 +0x7ff
github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc000735040, 0xc0000b6080, 0x1, 0x1, 0x0)
	/build/vault/src/src/github.com/hashicorp/vault/command/server.go:1432 +0x449b
github.com/mitchellh/cli.(*CLI).Run(0xc00043c3c0, 0xc00043c3c0, 0xc000530360, 0xc000530260)
	/build/vault/src/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1dc
github.com/hashicorp/vault/command.RunCustom(0xc0000b6070, 0x2, 0x2, 0xc00053c190, 0xc0000b0058)
	/build/vault/src/src/github.com/hashicorp/vault/command/main.go:180 +0x85a
github.com/hashicorp/vault/command.Run(...)
	/build/vault/src/src/github.com/hashicorp/vault/command/main.go:88
main.main()
	/build/vault/src/src/github.com/hashicorp/vault/main.go:10 +0x73
```

**To Reproduce**
We use the following packages to build vault:
* Go 1.13.4 (with PIE enabled)
* git 2.24.0
* yarn 1.21.0
* python 3.8.0
* bower 1.8.8
* nodejs 10.17
* npm 6.12.1
* zip 3.0.
* patch 2.7.6

We apply the following patches to solve various issues (this fixes the UI build in a fresh repo and is tracked as #7865:
```diff
From 73547d8f7410b04621184cf1b9bd0b3cdd7ca8b6 Mon Sep 17 00:00:00 2001
From: Steve Wills <steve@mouf.net>
Date: Tue, 12 Nov 2019 08:28:50 -0500
Subject: [PATCH] Fix UI build in fresh repo

Fixes #7863
---
 Makefile | 7 +++++--
 1 file changed, 5 insertions(+), 2 deletions(-)

diff --git a/Makefile b/Makefile
index 2e80db5241..b6fc2ec6a3 100644
--- a/Makefile
+++ b/Makefile
@@ -17,7 +17,7 @@ EXTERNAL_TOOLS=\
 	github.com/kardianos/govendor \
 	github.com/client9/misspell/cmd/misspell \
 	github.com/golangci/golangci-lint/cmd/golangci-lint
-GOFMT_FILES?=$$(find . -name '*.go' | grep -v pb.go | grep -v vendor)
+GOFMT_FILES?=$$(find . -name '*.go' | grep -v pb.go | grep -v vendor | grep -v testdata)
 
 GO_VERSION_MIN=1.12.7
 CGO_ENABLED?=0
@@ -136,7 +136,10 @@ bootstrap:
 update-plugins:
 	grep vault-plugin- vendor/vendor.json | cut -d '"' -f 4 | xargs govendor fetch
 
-static-assets:
+static-assets-dir:
+	@mkdir -p ./pkg/web_ui
+
+static-assets: static-assets-dir
 	@echo "--> Generating static assets"
 	@go-bindata-assetfs -o bindata_assetfs.go -pkg http -prefix pkg -modtime 1480000000 -tags ui ./pkg/web_ui/...
 	@mv bindata_assetfs.go http
```
As well as fixing thrift:
```diff
diff --git a/go.mod b/go.mod
index f10a14f5f..a1b4f8ddc 100644
--- a/go.mod
+++ b/go.mod
@@ -2,8 +2,6 @@ module github.com/hashicorp/vault

 go 1.12

-replace git.apache.org/thrift.git => github.com/apache/thrift v0.12.0
-
 replace github.com/hashicorp/vault/api => ./api
```

We apply both patches on a fresh hashicorp/vault clone
then we do:

```bash
XC_OSARCH='linux/amd64' make bootstrap static-assets static-dist bin
```

**Expected behavior**

Vault binary should work as expected and it should be easier to build vault by source, for easier distribution.

```hcl
/*
 * Vault configuration. See: https://vaultproject.io/docs/config/
 */

backend "file" {
	path = "/var/lib/vault"
}

listener "tcp" {
	/*
	 * By default Vault listens on localhost only.
	 * Make sure to enable TLS support otherwise.
	 *
	 * Note that VAULT_ADDR=http://127.0.0.1:8200 must
	 * be set in the environment in order for the client
	 * to work because it uses HTTPS by default.
	 */
	tls_disable = 1
}
```

CC: @anthraxx

**Comment by briankassouf** [comment]
Closing for now since #7865 was merged. Please let us know if this is still an issue for you and we can re-open!

**Comment by anthraxx** [comment]
The comment states #7865 was applied before building, don't see how it would solve an issue that is still present when it already was applied.

**Comment by jefferai** [comment]
The Vault 1.3 branch uses Go 1.12 (1.4 will be standardized on Go 1.13). Go 1.12 has different behavior with respect to that Apache thrift replace directive. If you are going to build with Go 1.13 you will need to patch it yourself.

**Comment by shibumi** [comment]
@jefferai We *did* patch it ourselves. The build worked, I have a binary. But `vault server -dev` fails with the error above. I don't think this has anything to do with the Apache thrift replace directive.

**Comment by amitnjha** [comment]
I am having this error in Vault v1.4.0 on ARM build.
I am trying to bring up the server without `dev` mode but with `ui=true`.
If I set `ui=false` it starts without any issue.

**Comment by shibumi** [comment]
@amitnjha how do you build vault? It should work with vault 1.4.1 and the following build line:
`XC_OSARCH='linux/arm' make static-dist bin`

**Comment by amitnjha** [comment]
> @amitnjha how do you build vault? It should work with vault 1.4.1 and the following build line:
> `XC_OSARCH='linux/arm' make static-dist bin`

I did `make static-dist dev-ui` . I will try suggested option as well. I though ui is needed for ui build.

**Comment by amitnjha** [comment]
> > @amitnjha how do you build vault? It should work with vault 1.4.1 and the following build line:
> > `XC_OSARCH='linux/arm' make static-dist bin`
> 
> I did `make static-dist dev-ui` . I will try suggested option as well. I thought `-ui` is needed for ui build.

Ok. I tried that and ran into JS Heap issues (its a raspberry pi). I upgraded nodejs hoping it will help, but then vault seems incompatible with node > 11.

**Comment by ncabatoff** [comment]
@amitnjha Is there a reason you're not just downloading the arm64 binary from our downloads page?

**Comment by amitnjha** [comment]
> @amitnjha Is there a reason you're not just downloading the arm64 binary from our downloads page?

I dint know there is an arm based option to download until you mentioned. It's working for me. Thanks!

**Comment by aphorise** [comment]
Folks how releavnt is this still - @shibumi can you kindly update in light of recent [avaible versions on the releases page](releases.hashicorp.com/vault) and if no longer applicable close?

**Comment by aphorise** [comment]
I believe this request is not longer relveant and may be closed.

**Comment by shibumi** [comment]
This can be closed, correct.
