### ISSUE TITLE
Policy Templates

### ISSUE THREAD

**Issue by jgillich** [hashicorp/vault#798]
As we discussed on the mailing list, I'm proposing support of templates in policies. The idea is to use values from the auth backend in paths, for example:

```
path "secret/{{username}}/*" {
  policy = "write"
}
```

This would allow each user to access their own path, without having to create a policy for each user.

**Comment by jsuchenia** [comment]
This could be useful to create tokens with policy and param - we don't need to maintain policy per app, just one policy and generate a valid token per app
Additionally it could be useful to use pre-defined variables like username, hostname, ip - for example to limit values for SSL/PKI backends

**Comment by jefferai** [comment]
We have some plans to implement this in 0.11, if they don't get pushed back, so hopefully this will appear soon!
