### ISSUE TITLE
Wrong error message with a tls client CA encrypted private key

### ISSUE THREAD

**Issue by MrLuje** [hashicorp/vault#7989]
**Describe the bug**
Vault incorrectly states "tls: bad certificate" when using an encrypted private key

**To Reproduce**
1. Vault is secured behind a reverse-proxy with tls client CA required
2. Run `Vault status -address=https://your_vault_address` -client-cert=... -client-key=...
3. See error : Error checking seal status: Get https://your_vault_address/v1/sys/seal-status: remote error: tls: bad certificate

**Expected behavior**
vault cli should state that the passphrase is needed to use the private key
Using the same command as 2. with an unencrypted private key works without any issue : 
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.3.0
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.0
* Vault CLI Version (retrieve with `vault version`): v1.3.0
* Server Operating System/Architecture: Windows 10.0.18363.476 from WSL shell :
Linux 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

Vault server configuration file(s):

```json
{
  "ui": true,
  "backend": {"file": {"path": "/vault/file"}},
  "listener": {
          "tcp": {
                  "address": "0.0.0.0:8200",
                  "tls_disable": true
          }
  },
  "default_lease_ttl": "168h",
  "max_lease_ttl": "720h"
}
```

**Additional context**
As stated in repro steps, the Vault is sitting behind a reverse proxy with tls client CA required for connection (Traefik 1.7.4 with entryPoints.https.tls.ClientCA)

**Comment by spangenberg** [comment]
Hi @MrLuje,

You [explicitly disabled TLS](https://www.vaultproject.io/docs/configuration/listener/tcp.html#tls_disable) in your Vault server config.
Vault is not using either of your private keys at all in this case.
What you might be seeing is that Traefik is not supporting encrypted private keys yet, here is a feature request in their repository: https://github.com/containous/traefik/issues/1262
If this is the case, Vault CLI is just relaying the error message from Traefik.
I hope I was able to clarify.

Best,
Daniel

**Comment by spangenberg** [comment]
I've tested it myself:

```
$ vault status -client-cert=./cert.pem -client-key=./key.pem
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.3.0
Cluster Name    vault-cluster-f81a427c
Cluster ID      d6babf93-5957-f337-d4bf-7fa0d72202dc
HA Enabled      false

$ vault status -client-cert=./cert.pem -client-key=./encrypted-key.pem
failed to setup TLS config: tls: failed to find any PEM data in key input
```

With an encrypted private key, it fails but with a different message: `failed to find any PEM data in key input`

**Comment by MrLuje** [comment]
I disabled TLS on Vault because Traefik 1.7 didn't support TLS passthrough per host and since I had already TLS auth enabled, I tried to use vault cli with TLS termination on traefik

> What you might be seeing is that Traefik is not supporting encrypted private keys yet, here is a feature request in their repository: containous/traefik#1262

No, sending a curl with the encrypted private key is working fine

My assumption was that Vault CLI would need the passphrase to locally initiate the ssl context, hence it would know if the private key is encrypted or not.

BTW, since Traefik 2.0+ support TLS passthrough I'll give tls-enabled vault a try :)

**Comment by spangenberg** [comment]
Some commands use STDIN for specific actions, which makes it impossible to use across for encrypted client certs, for example.
The other option would be as an arg, but then the password would go into shell history.

**Comment by spangenberg** [comment]
We haven't heard back regarding this issue in over 7 days. To try and keep our GitHub issues current, we'll be closing this issue in approximately seven days if we do not hear back regarding this issue. Please let us know if you can still reproduce this issue, and if there is any more information you could share, otherwise we'll be closing this issue.

**Comment by spangenberg** [comment]
Closing for now. Let us know if you have any more information!
