### ISSUE TITLE
Renewing a token with explict 'increment' value is ignored if only the 'default' policy is associated

### ISSUE THREAD

**Issue by kbatesrga** [hashicorp/vault#7992]
**Describe the bug**
If I login to vault with an LDAP account for which there are no additional policies besides 'default' associated, requests to renew my token beyond my default duration of 1h are ignored.

If however, I login to vault with an LDAP account for which there are at least one additional policy associated, my renewal works, and the new duration value and usual renewal response data is returned.

**To Reproduce**
1. Run `vault login -method=ldap username=user_a`  This user should only get the 'default' policy.
2. Run `vault renew -increment=4h` returns nothing.  
3. Run `vault token lookup` shows the original duration (minus its age, at this point)

**Expected behavior**
Run `vault login -method=ldap username=user_b`  This user should be associated with more than just the 'default' policy.

Run `vault renew -increment=4h` for example:
 A working example returns a payload similar to:

Key                    Value
---                    -----
token                  <token>
token_accessor         MxCMU24iXp1Ny8DgaXRUO8Za
token_duration         4h
token_renewable        true
token_policies         ["default second_policy"]
identity_policies      []
policies               ["default second_policy"]
token_meta_username    user_b

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.2.4
* Vault CLI Version (retrieve with `vault version`): 1.2.4
* Server Operating System/Architecture: RHEL 7

Vault server configuration file(s):

```hcl
listener "tcp" {
  address = "0.0.0.0:8201"
  tls_cert_file = "ca1.pem"
  tls_key_file = "key1.pem"

}

storage "consul" {
  address = "localhost:8501"
  check_timeout = "3s"
  path = "vault/"
  scheme = "https"
  service = "vault"
  token = "<a token>"
  tls_ca_file = "ca2.pem"
  tls_cert_file = "cert2.pem"
  tls_key_file = "key2.pem"
}
# Prometheus Configuration

telemetry {
  prometheus_retention_time = "30s",
  disable_hostname = true
}


log_level = "Info"
log_format = "standard"
default_lease_ttl = "1h"
max_lease_ttl = "768h"
ui = true
api_addr = "https:/somehost:8201"
cluster_addr = "anotherhost:8202"
```

**Additional context**

**Comment by kbatesrga** [comment]
One update - If I EXPLICILTY map the 'default' policy to a user like:

`vault write auth/ldap/users/user_a policies=default`

My subsequent renewal works.  It's imply the implicit association to 'default' that is broken?

**Comment by catsby** [comment]
Hello - 

Could you try running `vault login -format=json -method=ldap username=user_a` and inspect the output? I'm curious if the `renewable` field is `false` there.

Ultimately I don't believe this is a bug, but instead behaving as intended. LDAP renewal has behaved this way since it was added to Vault in https://github.com/hashicorp/vault/pull/151 ; if there are no policies, we simply return without attempt to renew. Note too that the `increment` option is not enforced and a given backend can choose to completely ignore it:

> The requested increment is completely advisory. The backend in charge of the secret can choose to completely ignore it. For most secrets, the backend does its best to respect the increment, but often limits it to ensure renewals every so often.
> 
> As a result, the return value of renewals should be carefully inspected to determine what the new lease is.

Source: https://www.vaultproject.io/docs/concepts/lease.html#lease-durations-and-renewal:

https://github.com/hashicorp/vault/blob/4887172605a3cac9f3d6621b6dbb50cbc435ab6b/builtin/credential/ldap/path_login.go#L135-L138

**Comment by ncabatoff** [comment]
This looks like a dup of #8002, which has a PR opened to fix.  Let's move the discussion there.  Feel free to re-open if you disagree it's a duplicate.
