### ISSUE TITLE
Vault UI does not reveal the value if the secret key contains a "."

### ISSUE THREAD

**Issue by macplady** [hashicorp/vault#8005]
**Describe the bug**
In the Vault UI, when you want to reveal the value of a key in the key/value secrets, it does not display any value if the key has a "." in it. The value stays blank, although there is a value for the key if you switch to json view.

**To Reproduce**
1. Log in to Vault UI
2. Navigate to a secret (or create a new one)
3. Press "Edit secret"
4. Enter a key with a "." like: my.key
5. Enter any value for the key like: myValue
6. Click Add and Save
7. Press on the eye-icon next to the newly created key.
8. The dots next to the eye-icon disapear, but no value gets displayed

**Expected behavior**
I expect to see the value for the key. From the example above, that would be "myValue".

**Environment:**
* Vault Server Version: 1.3.0
* Server Operating System/Architecture: RedHat OpenShift Container Platform 3.11

Vault server configuration file(s):

```hcl
api_addr = "https://vault:8200" 

storage "consul" {
  address = "127.0.0.1:8500"
  token   = "xxxxxxxx"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = "false"
  tls_cert_file = "/opt/vault/config/vault.cer"
  tls_key_file = "/opt/vault/config/vault.key"
}

telemetry {
  disable_hostname = true
  statsd_address = "localhost:9125"
}

disable_mlock = true

ui = true

log_level = "info"
```

**Additional context**
![image](https://user-images.githubusercontent.com/29653100/70628598-b76f0f80-1c28-11ea-82ea-1b7e24f3b1bd.png)

**Comment by michelvocks** [comment]
Hi @macplady!

Thank you for your bug report!
This bug is known and has been fixed with #7926. It should be included in the next version. 

Thanks again!

Cheers,
Michel
