### ISSUE TITLE
Fetch database user credentials in the UI

### ISSUE THREAD

**Issue by ademariag** [hashicorp/vault#8013]
**Is your feature request related to a problem? Please describe.**
I would like to give access to the UI to our users(developers) so that they can self-service their own database username/password credentials within the policies associated to them.

While this is possible from the command line, it is not possible from the UI 
(database backend is grayed out)

**Describe the solution you'd like**
I would like it Vault UI could be issuing database credentials to users.

Basically the equivalent of:
```
vault read database/creds/cloudsqlsuperuser
Key                Value
---                -----
lease_id           database/creds/cloudsqlsuperuser/RIp68wCeYnUcxoubUNFmxJAI
lease_duration     1h
lease_renewable    true
password           A1a-cFSk5WLU9n90Dwnz
username           v-root-cloudsql-TuOBclAKwrdtOJUtLQ3p-1576151409
```

**Describe alternatives you've considered**
Wrapper script that simplifies fetching the credentials, and potentially simplifying the DB client configuration

**Explain any additional use-cases**
Vault is the only solution I know that easily solves the credential generation workflow for developers and support users. While the CLI usage is great, the UI support would be a great feature.

**Comment by michelvocks** [comment]
Hi @ademariag!

Thank you for your feature-request. 
I will close this issue in favor of #6821 but let me know if you think this issue should stay open. 

Cheers,
Michel

**Comment by ademariag** [comment]
hi @michelvocks ,

I did see #6821 but there the requirement seems to be more on allowing *configuration* of the database backend.

This feature I am asking is about *using* the backend, which I would imagine it being much quicker to implement, and also honestly deliver a much better value.

Feel free to keep it close, but as it stand #6821 has a slightly different objective.

**Comment by michelvocks** [comment]
Hi @ademariag!

> This feature I am asking is about using the backend, which I would imagine it being much quicker to implement, and also honestly deliver a much better value.

That is exactly what has been asked in #6821 even tho the issue title does not reflect that.
I also think that both functionalities will be shipped together even if they are not really related to each other.

Cheers,
Michel

**Comment by ademariag** [comment]
Thank you @michelvocks . Do you have any ETA on #6821 or at least an idea if somebody is going to work on it?

**Comment by michelvocks** [comment]
Hi @ademariag!

Someone will for sure work on that but I can't give an ETA yet. 

Cheers,
Michel
