### ISSUE TITLE
Vault with consul on large implementations 

### ISSUE THREAD

**Issue by mo-mughrabi** [hashicorp/vault#804]
Hello, 

Recently we decided to give consul+vault a try to be implemented across our infrastructure. At the moment, we are trying to spin up a test site with consul+vault but am having number of issues that are not clear in the documentation. 

Currently, in the test site, we have 3 consul servers and X number of instances as clients, we use an orchestrator to launch the instances and configure consul.

Here is how server configuration looks like
```
{
    "acl_datacenter": "gce10",
    "acl_default_policy": "deny",
    "acl_master_token": "master-token",
    "bind_addr": "0.0.0.0",
    "bootstrap_expect": 2,
    "client_addr": "0.0.0.0",
    "data_dir": "/var/consul",
    "datacenter": "gce1",
    "dns_config": {
        "allow_stale": true
    },
    "domain": "consul",
    "enable_debug": true,
    "encrypt": "encryption-key",
    "log_level": "info",
    "retry_interval": "30s",
    "retry_join": [
        "ip-address-consul-1",
        "ip-address-consul-2",
        "ip-address-consul-3"
    ],
    "server": true,
    "ui_dir": "/usr/local/share/consul/ui"
}
```

As for the client, this is a sample of how the service.json and config.json looks like

`config.json`

```
{
    "acl_datacenter": "gce10",
    "acl_default_policy": "deny",
    "acl_token": "client-token",
    "bind_addr": "0.0.0.0",
    "data_dir": "/var/consul",
    "datacenter": "gce1",
    "enable_debug": false,
    "encrypt": "encryption-key",
    "log_level": "info",
    "retry_interval": "30s",
    "retry_join": [
        "ip-address-consul-1",
        "ip-address-consul-2",
        "ip-address-consul-3"
    ],
    "server": false,
    "ui_dir": "/usr/local/share/consul/ui"
}
```

`service.json`

```
{
  "services": [{"name": "api", "port": 80}]
}
```

Am able to see all servers and services using `consul members` they all visible, am also using `dnsmasq` to resolve dns for each of the services. 

We also using `consul-template` in most services to render configuration using consul key/value and its working fine so far, and we are using the orchestrator layer to spin up services using `consul-template` to retrieve service information.

Now our next step is to add vault to the mix, in order to secure some keys, for that we setup one vault server and registered the vault server as a service on consul. This is the vault server configuration 

config.hcl

```
backend "consul" {
  address = "127.0.0.1:8500"
  advertise_addr = "http://internal-network-ip-address:8500"
  path = "vault"
}

listener "tcp" {
 address = "internal-network-ip-address:8200"
 tls_disable = 0
}
```

Then, once consul is running on vault server and we launched vault in the above configuration. We tried to init vault, load consul backend and load an allow policy. 

```
vault init
vault unseal
vault mount consul
vault write consul/config/access \
    address=127.0.0.1:8500 \
    token=client-token

```

<img width="548" alt="screen shot 2015-11-29 at 4 37 59 pm" src="https://cloud.githubusercontent.com/assets/772251/11457357/92ad1eda-96b7-11e5-8e29-dc8236b7087d.png">

Which generates the vault folder on consul.

From the vault server, am able to write new keys, view vault status 

```
vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: active
	Leader: http://internal-network-ip-address:8500

vault read secret/database/password
Key           	Value
lease_duration	2592000
value         	dude
```

Now that I've setup vault server, I installed vault on other nodes to run as standby, using same vault config as the leader (above).

I tried to create ACL in consul for the new node "api" which needs to read vault when running `consul-template`.
<img width="643" alt="screen shot 2015-11-29 at 4 44 15 pm" src="https://cloud.githubusercontent.com/assets/772251/11457399/bad83c72-96b8-11e5-8827-e368ba01c411.png">

I used the newly created ACL token to and updated the node's consul config `acl_token=using-token-id-from-screenshot-above`

but when I try to run consul-template, it asks me to unseal the vault, after unsealing and running consul-template am getting following error 

```
consul-template -template settings.ctmpl:/opt/docker.env -once -retry 30s -token=423cea63-e546-c7f6-804f-898bd7afddfb 
2015/11/29 13:28:06 [ERR] (view) "vault(secret/database)" no secret exists at path "\"vault(secret/database)\""
2015/11/29 13:28:06 [ERR] (runner) watcher reported error: no secret exists at path "\"vault(secret/database)\""
Consul Template returned errors:
no secret exists at path "\"vault(secret/database)\""
```

Honestly, some parts of the configuration were not documented and found some clues here and there on mailing lists. I couldn't find a solid documentation on how to setup consul+vault on multi nodes..

I also have a question if anyone can help me understand more

Once secrets are loaded in vault with consul backend, can i compile consul-template templates with secrets without unsealing vault? Does it mean, I have to unseal vault on all nodes to be able to compile settings?

regards

**Comment by armon** [comment]
Hey @mo-mughrabi,

I think the primary confusion here is that Vault is not deployed in the same model as Consul. With Consul, you have an agent running on every machine, and 3 or 5 servers. With Vault, you only typically run 2 instances total. One is the active server, and the other is the standby, no need to run on many nodes. The requirement of unsealing a Vault also makes it fairly unpractical to run on many nodes.

Secondly, the ACL systems of Vault and Consul are completely distinct. E.g. the "secret/*" path in Vault is not related to the "secret/*" path in Consul. The Vault servers need to write level access to the "vault/" path in Consul, but no other clients need access to that. Clients instead speak to the Vault servers, and are subject to Vault's ACLs.

To clarify:

Vault Client - (reads secret/foo) -> Vault - (reads vault/logical/UUID/foo) -> Consul

Does this help?

**Comment by mo-mughrabi** [comment]
@armon very much, very helpful now that I understand how vault should play along the infrastructure. 

Another question please, 

1) what is the best practice on using vault on large farms? I mean, if I will have one or two vault servers, the rest of the farm will need to render environment variables using `consul-template` do I need to point consul-template to the lead vault server? 

2) Do I need to unseal the vault every am making new deployments? is there a recommended approach to make secret available to different services?

**Comment by jefferai** [comment]
@mo-mughrabi 

1) Generally if you are using Vault and Consul, you should set up health checks so that Consul will track the state of the Vault servers; using Vault's status endpoint will automatically return the HTTP status codes that Consul expects for healthy/warning to track active/standby Vault instances. Then you just point `consul-template` to the Vault service.

2) Vault must be unsealed every time it's started. It's not designed to run in e.g. an elastic scaling group.

**Comment by mo-mughrabi** [comment]
Thank you @jefferai this really helps
