### ISSUE TITLE
When I request the password of account in active directory from vault, the password is rotated continuously.

### ISSUE THREAD

**Issue by 2994186010** [hashicorp/vault#8053]
My version of vault is v1.3.0. The rotation mechanism in ad secret engine is that passwords are rotated "lazily". Now the passwords will be rotated even though they are not over their TTL. The rotation behavior in vault v1.3.0 is not same as the rotation behavior in vault v1.1.3.

**Comment by tyrannosaurus-becks** [comment]
Hi! Happy to take a look at this. Can you provide the following information so we can attempt to reproduce it?

- `$ vault read ad/config`
- `$ vault read ad/roles/my-application` (for a role that's being used for login and is experiencing this issue)
- `$ vault read ad/creds/my-application` (please don't include valuable service account names or passwords, I just want to see the rest of what it says)

That should help! Thanks!

**Comment by 2994186010** [comment]
**$ vault read ad/config**
Key                             Value
---                             -----
binddn                          Administrator@nwdc.dc
certificate                     -----BEGIN CERTIFICATE-----
MIIGBDCCBOygAwIBAgITGgAAAAILvoNGMz3b9QAAAAAAAjANBgkqhkiG9w0BAQsF
ADBMMRIwEAYKCZImiZPyLGQBGRYCZGMxFDASBgoJkiaJk/IsZAEZFgRud2RjMSAw
HgYDVQQDExdud2RjLVdJTi1ETzgwVVJWRElPMi1DQTAeFw0xOTA4MjUxMTQ3MjJa
Fw0yMDA4MjQxMTQ3MjJaMCIxIDAeBgNVBAMTF1dJTi1ETzgwVVJWRElPMi5ud2Rj
LmRjMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApN+Bx1sQh2/nsMqb
CJCEGQsit7DoukTsCmlpt/83jGWAKFSUJ1sYr6M8Bk6HOHYfWKQbzb35QAQQT1Mf
x7czz0YciQOz0jgecyvJa9mDlCHptrpP0stxQ6rPFkiwUwff3+ta8n+S8zrDY7YP
XLPSLib1b0r7RNHjFUmWmFMoy9uUb3a1NOh4wsmLvnXK2nMyjcX76J95xpAnmEQV
HPKRg+63mMevAixZocpWxeV5bmCz6TXR+Gn9Nvvx0i4NdgudHRZk6eaZtyBsWtvU
1rzjXDmq0vg1xNWz5ewRCVCfdMp4Ksd0rB0ssCOZPCczHi3CbNY2Rm3e+Oy32+Pj
DSuTDwIDAQABo4IDBzCCAwMwLwYJKwYBBAGCNxQCBCIeIABEAG8AbQBhAGkAbgBD
AG8AbgB0AHIAbwBsAGwAZQByMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
ATAOBgNVHQ8BAf8EBAMCBaAweAYJKoZIhvcNAQkPBGswaTAOBggqhkiG9w0DAgIC
AIAwDgYIKoZIhvcNAwQCAgCAMAsGCWCGSAFlAwQBKjALBglghkgBZQMEAS0wCwYJ
YIZIAWUDBAECMAsGCWCGSAFlAwQBBTAHBgUrDgMCBzAKBggqhkiG9w0DBzAdBgNV
HQ4EFgQUmGIoyMpfQFWFhpKPgZynTtB1EnAwHwYDVR0jBBgwFoAU1NTxarWnl6vY
21CsLIPcmjIjHFEwgdkGA1UdHwSB0TCBzjCBy6CByKCBxYaBwmxkYXA6Ly8vQ049
bndkYy1XSU4tRE84MFVSVkRJTzItQ0EsQ049V0lOLURPODBVUlZESU8yLENOPUNE
UCxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25m
aWd1cmF0aW9uLERDPW53ZGMsREM9ZGM/Y2VydGlmaWNhdGVSZXZvY2F0aW9uTGlz
dD9iYXNlP29iamVjdENsYXNzPWNSTERpc3RyaWJ1dGlvblBvaW50MIHFBggrBgEF
BQcBAQSBuDCBtTCBsgYIKwYBBQUHMAKGgaVsZGFwOi8vL0NOPW53ZGMtV0lOLURP
ODBVUlZESU8yLUNBLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxD
Tj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPW53ZGMsREM9ZGM/Y0FDZXJ0
aWZpY2F0ZT9iYXNlP29iamVjdENsYXNzPWNlcnRpZmljYXRpb25BdXRob3JpdHkw
QwYDVR0RBDwwOqAfBgkrBgEEAYI3GQGgEgQQL/A4M1KMbky7x97ues8fA4IXV0lO
LURPODBVUlZESU8yLm53ZGMuZGMwDQYJKoZIhvcNAQELBQADggEBAGBCcWI0yYeS
OrjivP6mLOWCFoQkEvNyjoYHMkoUqCwVGBf+plkN9G28Ht/olKSB41HkPfkehJda
AVDhvvW5hvue6XssudhPpwuOYeRNMFcetZ3x2VBM6/UsV9th9IWN44sesnrvf61Z
EofdfC1v/A0NW+UlQyKuaBYErUuScLL5WiaopHVKSTUVd0L86eiZRXD6k5Ben4zi
DRyAZmTjU/aPPXH7uwlI7axM4xxt8XOcL+i6eNUOXwegw8lnqOntbMcgt8jR8I+G
pRwWsSzHnTPLJSwDf7KLn8jtYeQxw7SlCr7BHKpPIZ4Ycj4tfq0MeODsMQ4lM2WX
eYbadEiZ3jg=
-----END CERTIFICATE-----
formatter                       n/a
insecure_tls                    false
last_rotation_tolerance         5
length                          64
max_ttl                         768h
starttls                        false
tls_max_version                 tls12
tls_min_version                 tls12
ttl                             768h
upndomain                       n/a
url                             ldaps://win-do80urvdio2.nwdc.dc
use_pre111_group_cn_behavior    false
userdn                          dc=nwdc,dc=dc

**$ vault read ad/roles/zhangsan**
Key                     Value
---                     -----
last_vault_rotation     2019-12-19T12:43:36.297706856Z
password_last_set       2019-12-22T03:24:37.8572406Z
service_account_name    zhangsan@nwdc.dc
ttl                     1h

**$ vault read ad/creds/my-application**
Key                 Value
---                 -----
current_password    ?@09AZUhM9xfbXV2beZdbR7k4DXg7Wjc+FEXeBSTPcWOeIQFGRHenVq7ihW8945R
username            zhangsan

**Comment by tyrannosaurus-becks** [comment]
Hi! Thanks for providing that information, it's very helpful. 

I spun up our server and did an identical test on version 1.3 of Vault. With the same configuration, if I wait 10 seconds between requesting the credentials, I still get the same password as expected. So, I'm unable to duplicate it.

This means there's a difference in our test environments. The most likely issues are:

- Your Active Directory cluster may take more than 5 seconds to fully propagate new passwords. If so, boosting your last_rotation_tolerance to 10 or 15 seconds may resolve the issue.
- There may be clock drift between your server and the Active Directory server. To check for this, read some new credentials, then read the role you just received them for. Check whether the password_last_set and last_vault_rotation agree with each other about what time it is currenlty.
- Something else may also be rotating the password you're seeking. If so, Vault must re-rotate it to "know" it again and return it to you.

Another helpful thing might be to look at your logs. When a password is rotated, [this](https://github.com/hashicorp/vault-plugin-secrets-ad/blob/master/plugin/path_creds.go#L134-L136) line is outputted explaining the cause for the rotation. 

If, after that, you still believe this is a bug, please post additional steps to reproduce it. Thanks!
