### ISSUE TITLE
Could not renew certificate

### ISSUE THREAD

**Issue by usmansiddiqui1** [hashicorp/vault#8055]
Our vault enterprise which is running version 1.1.2+pro and running on OpenShift version 3.11 using boostport project as can be seen in below GitHub link, became unavailable and started giving certificate and token expiry errors on Friday. We had to renew the cert manually to make it working again. The intermediate cert which was there and expired, had validity of 5 years and was not expiring before 2024. We want to find out the root cause because this is our production environment and has big impact when it breaks.
https://github.com/Boostport/kubernetes-vault/blob/master/deployments/quick-start/README.md
raw time="2019-12-15T21:03:54Z" level=error msg="Could not renew auth token: could not complete renewal operation: error renewing vault token: Error making API request.\n\nURL: PUT http://infra-vault.kube-system:8200/v1/auth/token/renew-self\nCode: 403. Errors:\n\n* permission denied" time="2019-12-15T21:03:32Z" level=error msg="Could not renew certificate: could not complete renewal operation: error issuing certificate: Error making API request.\n\nURL: PUT http://infra-vault.kube-system:8200/v1/intermediate-ca/issue/kubernetes-vault\nCode: 403. Errors:\n\n* permission denied" time="2019-12-15T21:01:56Z" level=error msg="Could not renew auth token: could not complete renewal operation: error renewing vault token: Error making API request.\n\nURL: PUT http://infra-vault.kube-system:8200/v1/auth/token/renew-self\nCode: 403. Errors:\n\n* permission denied" time="2019-12-15T21:01:28Z" level=error msg="Could not renew certificate: could not complete renewal operation: error issuing certificate: Error making API request.\n\nURL: PUT http://infra-vault.kube-system:8200/v1/intermediate-ca/issue/kubernetes-vault\nCode: 403. Errors:\n\n* permission denied" time="2019-12-15T21:00:00Z" level=error msg="Could not renew auth token: could not complete renewal operation: error renewing vault token: Error making API request.\n\nURL: PUT http://infra-vault.kube-system:8200/v1/auth/token/renew-self\nCode: 403. Errors:\n\n* permission denied"

**Comment by catsby** [comment]
Hello - Apologies, but support for enterprise customers needs to go through our enterprise support portal. Reporting through our enterprise support portal ensures that we can comply with contractually obligated SLAs around customer support requests, and that a support engineer or technical account manager can track the issue from report to resolution.

I see too that this issue has been reported on the mailing list, with some feedback there:

- https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/TYi327YONeg/RS6AufjcBQAJ

At this time I do not believe this is an issue with Vault itself. If you do feel this is an issue with Vault please be sure to follow up in the support issue in our enterprise support portal. I'm going to close this issue for now.
