### ISSUE TITLE
Write-only policy?

### ISSUE THREAD

**Issue by waynerobinson** [hashicorp/vault#806]
The `write` policy seems to also include the `read` permission.

Our use case requires data to come from one application with and the reads to occur from another. The application that writes data has a much larger attack surface to the one that reads data and never needs to read it back, only overwrite it if necessary.

Is there are write-only policy implemented somewhere?

**Comment by jefferai** [comment]
There isn't currently, but we have thought of this exact use-case and expanded ACL support, including separation of read/write, is already on the roadmap. It should appear in 0.5 or 0.6!
