### ISSUE TITLE
Custom message alert on Vault UI during maintenance time

### ISSUE THREAD

**Issue by Nagarajuwas** [hashicorp/vault#8061]
**Is your feature request related to a problem? Please describe.**
During vault server rebuild or maintenance time we don't have any options to set banner message to our consumers on Vault UI console

**Describe the solution you'd like**
Is there  any solution or option to display banner message on Vault UI console during maintenance time. we have this option on jenkin servers and we can set any custom message during  maintenance  time.

**Comment by Monkeychip** [comment]
@Nagarajuwas stay tuned. This feature is likely to roll out soon. We will update this ticket when that happens.

**Comment by Monkeychip** [comment]
I'm going to go ahead and close this request. Custom messages as banners and/or modals before and/or after login was added to Enterprise licenses in 1.16.x.
