### ISSUE TITLE
Customizing Usernames in Database Dynamic Credentials

### ISSUE THREAD

**Issue by excalq** [hashicorp/vault#8063]
**Is your feature request related to a problem? Please describe.**
We're starting to use Vault's excellent Dynamic Credentials capability for managing database users and supplying temporary login credentials. A stakeholder has requested that the usernames include the LDAP username which is used by Vault to authenticate, so that database audit logs display a username that can be mapped back to an individual, without the added work of correlating database logs with Vault logs. 

**Describe the solution you'd like**
The ability to source a created username from an LDAP username, or prefix/suffix the generated username with such metadata.

**Describe alternatives you've considered**
We've evaluated static roles, however this reintroduces operation burden in provisioning and offboarding users. It seems each static roles still needs an external database user to be created in advance. Dynamic roles are appealing, as we only have to add a user to an LDAP group allowed by the Vault Database policy.

**Comment by zarko-a** [comment]
We were wondering about the same thing. We are using OIDC authentication and were looking for some correlation between the authenticated user and dynamically created username. 

As far as I can see username already contains part of the display name. For example v-**oidc-goo**-db-admin-XXXXX. Where bolded part is trimmed down version of `OIDC-GOOGLE-APPS|USERNAME@DOMAIN.COM`
It seems to be cut off at 8 characters. 

I'm not proficient in Go, but it appears that is specified somewhere [here ](https://github.com/hashicorp/vault/blob/ca83be21b401b0ff35f41ae5b75f4650e5319770/plugins/database/postgresql/postgresql.go) 
Maybe a quick solution would be allowing longer Display Name during the username generation.

**Comment by fernando-villalba** [comment]
This is not a bad idea, and it would help a lot identifying who is creating what user, see this issue: https://groups.google.com/forum/#!topic/vault-tool/mlyGWfsbrUQ

**Comment by amanhigh** [comment]
We also have a very similar requirement where we want to have custom name for user or atleast a custom prefix.

Currently name is being derived from role name. I think we can take name prefix in input map and use that if its supplied or fallback to role name with random prefix.

Any particular reason this is not desirable or its just not implemented.

**Comment by pcman312** [comment]
Hi @excalq, @zarko-a, @fernando-villalba, & @amanhigh ! I wanted to give an update on this. We've had a number of requests revolving around the idea of giving users the ability to customize how dynamic usernames are generated. In Vault 1.7 (coming soon) we are introducing the idea of `username_template` to some* of our secret engines. This will give the ability to fully customize how a username is generated prior to passing that username to the appropriate statements run in the database. Each engine will default to the current behavior, but this will allow for customization if that default does not suit their needs.

There will be docs available through https://www.vaultproject.io once 1.7 is released will describe this in more detail but I wanted to give you a heads up for this new feature coming soon!

<sub>* - engines supported in 1.7: PostgreSQL, MSSQL, MySQL, MongoDB (not MongoDB Atlas), Cassandra, Oracle, and OpenLDAP</sub>
