### ISSUE TITLE
Add username_length and rolename_length back into database secrets engine

### ISSUE THREAD

**Issue by mjtice** [hashicorp/vault#8066]
**Is your feature request related to a problem? Please describe.**
The problem I'm having is similar to https://github.com/hashicorp/vault/issues/1605.

**Describe the solution you'd like**
https://github.com/hashicorp/vault/pull/1604 addressed the problem in issue 1605 - however, that was for the legacy mysql engine and it doesn't appear that the enhancement was moved to the newer database secrets engine.

**Describe alternatives you've considered**
NA

**Explain any additional use-cases**
If possible, have it apply to the database secrets engine in general (not just a specific database).

**Additional context**
NA

**Comment by tyrannosaurus-becks** [comment]
Note for whoever ends up working on this, I found that the lengths are hard-coded [here](https://github.com/hashicorp/vault/blob/ca83be21b401b0ff35f41ae5b75f4650e5319770/plugins/database/mysql/mysql.go#L86-L90).

**Comment by pcman312** [comment]
Hi @mjtice ! I'm copy pasting my response to https://github.com/hashicorp/vault-plugin-database-oracle/issues/36 here as the same feature applies to MySQL:

I wanted to give an update on this. We've had a number of requests revolving around the idea of giving users the ability to customize how dynamic usernames are generated. In Vault 1.7 (coming soon) we are introducing the idea of `username_template` to some* of our secret engines. This will give the ability to fully customize how a username is generated prior to passing that username to the appropriate statements run in the database. Each engine will default to the current behavior, but this will allow for customization if that default does not suit their needs.

There will be docs available through https://www.vaultproject.io once 1.7 is released will describe this in more detail but I wanted to give you a heads up for this new feature coming soon!

<sub>* - engines supported in 1.7: PostgreSQL, MSSQL, MySQL, MongoDB (not MongoDB Atlas), Cassandra, Oracle, and OpenLDAP</sub>
