### ISSUE TITLE
are 'renewable' and 'lease_id' reserved or not? 

### ISSUE THREAD

**Issue by feliksik** [hashicorp/vault#807]
We can write secrets with keys "lease_id", "lease_duration" and "renewable" in a way that may lead to confusing or ambiguous behavior. 

Let's try to write some secrets with the unfortunately chosen 'renewable' key: 
```
vagrant@dev-node-1:~$ vault write generic/test-reserved-keywords secret=p4ssw0rd renewable=true
Success! Data written to: generic/test-reserved-keywords
```

Ok, that's fine. Let's read in table format: 
```
vagrant@dev-node-1:~$ vault read generic/test-reserved-keywords
Key           	Value
lease_duration	2592000
renewable     	true
secret        	p4ssw0rd
```
It looks like we set the renewable value to true. But not the one we would expect: 
```
vagrant@dev-node-1:~$ vault read -format=json  generic/test-reserved-keywords
{
	"lease_id": "",
	"lease_duration": 2592000,
	"renewable": false,
	"data": {
		"renewable": "true",
		"secret": "p4ssw0rd"
	}
}
```

I think this is not the desired or intended behavior, as this may lead to confusion? It would be possible to reserve some words, or to print both 'internal' fields and that 'data' fields separately, in table format.

**Comment by jefferai** [comment]
Hi there,

The `generic` backend acts as a key-value store. So when you set a value "renewable" to "true", you are literally setting that key and value at the path you are giving it -- note the difference between the types of the two `renewable` keys. The other `renewable` key is set by Vault as necessary, defaulting to `false` as that's the empty value of a `bool` in Go, and the `generic` backend does not issue leases (hence the `lease_id` value is empty).

Hope that helps!

**Comment by feliksik** [comment]
Thanks for your response, @jefferai . 

I understand what is happining, and I understand the type difference. The point is that the output of ` `vault read -format=table` is ambiguous, because it does *not* understand the type difference. 

So the output of the table format is misleading.

**Comment by jefferai** [comment]
It is...it's kind of an unfortunate part of stuffing typed data into a bare table. :-)
