### ISSUE TITLE
Error in blog on HashiCorp main site leads to error using external ca bundle

### ISSUE THREAD

**Issue by obourdon** [hashicorp/vault#8070]
**Describe the bug**
On  [https://www.hashicorp.com/blog/certificate-management-with-vault/](https://www.hashicorp.com/blog/certificate-management-with-vault/) it is stated 

`vault write pki/config/ca pem_bundle=@pem_bundle.json ` 

but this corresponds to the curl version of the command. 

The pem_bundle.json parameter should be replaced by pem_bundle.pem which is a strict concatenation of cert+privatekey and not a json file

**Comment by aphorise** [comment]
Hey @obourdon thanks for spotting this that's been corrected. You have great eyes ;-)
![image](https://user-images.githubusercontent.com/974854/187782138-4b5efd9e-6ebb-4bb7-8cae-e442ec1f8604.png)
