### ISSUE TITLE
Error initializing storage of type raft: failed to create fsm: timeout

### ISSUE THREAD

**Issue by tsarna** [hashicorp/vault#8078]
**Describe the bug**
I've been playing with the raft storage in 1.3.1. In a 3 node cluster, after restarting the original node (to which the other two were joined), it started logging:

Error initializing storage of type raft: failed to create fsm: timeout

All nodes seem functional however, and in "vault operator raft configuration" doesn't show anything different about this node.

**To Reproduce**
create 3 nodes master01[abc], with vault 1.3.1. These are running alpine linux with the vault package from the "edge" repo.

Initialize and configure master01a -- various auth mechanism, secrets engines, policies, etc -- I can detail it all if needed but I have no reason to believe the details are relevant.

TLS is disabled. 

Join master01b and master01c to master01a.

Some time later, I restarted master01a, then the leader, and it began loging the message. However, it appears to be functional. `vault operator raft configuration` says:

```Key       Value
---       -----
config    map[index:14343 servers:[map[address:192.168.16.4:8201 leader:false node_id:master01a protocol_version:3 voter:true] map[address:192.168.18.4:8201 leader:true node_id:master01c protocol_version:3 voter:true] map[address:192.168.17.4:8201 leader:false node_id:master01b protocol_version:3 voter:true]]]
```

**Expected behavior**
No scary error messages are logged after a restart.

If there are error messages, they should provide more detail to understand what to do to fix them, or should be documented in this regard. I could find nothing useful in searches.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.1
* Vault CLI Version (retrieve with `vault version`): Vault v1.3.1
* Server Operating System/Architecture: Alpine Linux 3.11.0, x86_64, on AWS t3a.nano instances

Vault server configuration file(s):

```hcl
storage "raft" {
  path = "/data/vault/db"
  node_id = "master01a"
}

listener "tcp" {
  address = "192.168.16.4:8200"
  tls_disable = true
}

listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = true
}

seal "awskms" {
  region     = "us-east-1"
  kms_key_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}

api_addr = "http://192.168.16.4:8200"
cluster_addr = "http://192.168.16.4:8201"
pid_file = "/data/vault/vault.pid"       
```

01b and 01c are the same but in 192.168.17 and 192.168.18 respectively.

**Additional context**

**Comment by tsarna** [comment]
After restarting more recently, I can no longer reproduce this. I'm not sure what changed.

Still, it would be nice if the message and/or documentation added some guidance on what the problem was and anything that could be done to fix it or debug the issue further.

**Comment by marco69** [comment]
I am having the same issue Error initializing storage of type raft: failed to create fsm: failed to open bolt file: open /vault/data/vault.db: permission denied.

I have installed a 3 microk8s and I am  trying to configure the  helmchart with the RAFT backend storage .. the configuration of the helm is the folowing:

 ha:
    enabled: true
    replicas: 3

    # Set the api_addr configuration for Vault HA
    # See https://www.vaultproject.io/docs/configuration#api_addr
    # If set to null, this will be set to the Pod IP Address
    apiAddr: null

    # Enables Vault's integrated Raft storage.  Unlike the typical HA modes where
    # Vault's persistence is external (such as Consul), enabling Raft mode will create
    # persistent volumes for Vault to store data according to the configuration under server.dataStorage.
    # The Vault cluster will coordinate leader elections and failovers internally.
    raft:

      # Enables Raft integrated storage
      enabled: true
      # Set the Node Raft ID to the name of the pod
      setNodeId: true

      # Note: Configuration files are stored in ConfigMaps so sensitive data
      # such as passwords should be either mounted through extraSecretEnvironmentVars
      # or through a Kube secret.  For more information see:
      # https://www.vaultproject.io/docs/platform/k8s/helm/run#protecting-sensitive-vault-configurations
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"
          #node_id = "vault-0"
        }

        service_registration "kubernetes" {}


I also have teh section datastorage to provide a PV enabled 

dataStorage:
    enabled: true
    # Size of the PVC created
    size: 2Gi
    # Location where the PVC will be mounted.
    mountPath: "/vault/data"
    # Name of the storage class to use.  If null it will use the
    # configured default Storage Class.
    storageClass: ""
    # Access Mode of the storage device being used for the PVC
    accessMode: ReadWriteOnce
    # Annotations to apply to the PVC
    annotations: {} 

What I am doing wrong here?
Thank you for the help

**Comment by ncabatoff** [comment]
The original bug report involved what is now a very old Vault version. I would ask them further details but their followup indicates that they could no longer reproduce it, which makes it hard to figure out how to improve the operator feedback when the problem occurs.

The more recent followup looks like a permissions error and I think the feedback there is already clear.  I recommend asking questions like this at https://discuss.hashicorp.com/c/vault/30 instead, as we prefer to reserve github issues for bug reports and feature requests.
