### ISSUE TITLE
Addition of `nvmrc` for node version

### ISSUE THREAD

**Issue by yashLadha** [hashicorp/vault#8079]
**Is your feature request related to a problem? Please describe.**
When setting up the project, I faced the error with the node version for building the static assets. I am using `nvm` as my version manager for node. So to implicitly pick the node version that is needed by the project, having an `nvmrc` helps.

**Describe the solution you'd like**
Adding a `.nvmrc` for nvm, so that it automatically picks the node version that is needed.

**Describe alternatives you've considered**
As this is related to the errors while doing the initial setup, I can think of adding this in README, but still automatically using the version without the user involvement is always awesome.

**Explain any additional use-cases**
No, as of now.

**Additional context**
![image](https://user-images.githubusercontent.com/18033231/71621560-0b509100-2bf6-11ea-9273-b51a18c1d37c.png)

**Comment by yashLadha** [comment]
Adding a symlink from `UI` directory to root, will make it possible to detect the nvm in project root itself for the make commands. @michelvocks @chrishoffman your views?

**Comment by chrishoffman** [comment]
Our website uses some node too and those version can diverge so I don't think putting it in the root is the right solution.

**Comment by yashLadha** [comment]
Okay, got it. However, adding this detail in readme can be done to guide. What do you think?

**Comment by hellobontempo** [comment]
Hi there, sorry for the delayed response on this. Thanks for filing this issue! We've added the node version to our package.json file [here](https://github.com/hashicorp/vault/blob/7f3aab719954dd688c95bc1bffa68cb31159697e/ui/package.json#L229)
