### ISSUE TITLE
Handling of external plugins causes undesirable warnings to be logged

### ISSUE THREAD

**Issue by tr1ck3r** [hashicorp/vault#8090]
**Is your feature request related to a problem? Please describe.**
We (Venafi) have developed 2 secrets engine plugins for Vault (https://github.com/Venafi/vault-pki-backend-venafi and https://github.com/Venafi/vault-pki-monitor-venafi).  Both are working properly in terms of their functionality but we're seeing warnings like the following being logged repeatedly which is concern both to us and our mutual customers:

```
2020-01-02T21:27:06.607Z [WARN]  secrets.pki-backend-venafi.pki-backend-venafi_4459c816.pki-backend-venafi: error closing client during Kill: metadata=true err="rpc error: code = Canceled desc = grpc: the client connection is closing"
2020-01-02T21:27:06.607Z [WARN]  secrets.pki-backend-venafi.pki-backend-venafi_4459c816.pki-backend-venafi: plugin failed to exit gracefully: metadata=true
```

The same warnings appear when I load other secrets engine plugins I found (https://github.com/hashicorp/vault-plugin-secrets-gcp and https://github.com/sethvargo/vault-secrets-gen) suggesting this is very likely not related to anything in our implementation. 

**Describe the solution you'd like**
No warnings to be logged when external plugins like ours are loaded/used (unless, of course, they are valid issues that can be remediated).

**Additional context**
I first posed this as a question in the [Vault mailing list](https://groups.google.com/d/msg/vault-tool/z6iaU_B159A/ag7OJaeECQAJ).  @ncabatoff confirmed it is a known issue related to how external plugins are loaded by Vault and recommended opening this issue so the undesirable behavior can be addressed in a future release of Vault.

**Comment by aphorise** [comment]
Hey @tr1ck3r is still applicable for you guys and does it not suffice to adjust `log_level="INFO"` for example?

@ncabatoff - I was also curious if have any recollection or know of any changes since.

**Comment by hsimon-hashicorp** [comment]
Closing due to issue age / responses, please feel free to re-open if needed
