### ISSUE TITLE
Unclear failure when trying to init dev vault with invalid token ('s.' prefix)

### ISSUE THREAD

**Issue by fullkomnun** [hashicorp/vault#8092]
**Describe the bug**
Trying to initialise vault server in DEV mode with a user provided token formatted like the ones vault generates results in a generic error. Apparently, custom (user defined) vault tokens cannot have a 's.' prefix (e.g. 's.6w3CpXn5vChbnpLtBlCJCUxs'). The error is not-so-helpful and i haven't seen this mentioned in the official documentation. 

**To Reproduce**
1. Run `vault server -dev -dev-root-token-id="s.6w3CpXn5vChbnpLtBlCJCUxs"`
2. See generic (not-so-helpful) error:
Error initializing Dev mode: failed to create root token with ID "s.6w3CpXn5vChbnpLtBlCJCUxs": 1 error occurred:
	* invalid request

**Expected behavior**
Have a more specific error message that clarifies why the token is invalid and/or mention this more clearly in the documentation.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.0
* Vault CLI Version (retrieve with `vault version`): 1.3.0
* Server Operating System/Architecture: alpine(vault container) and mac osx 64-bit

Vault server configuration file(s):

**Additional context**
Ran into this issue while trying to run a vault test container and submitted a PR to fail-fast while configuring the vault container ([https://github.com/testcontainers/testcontainers-java/pull/2228](url)).

**Comment by vvelikodny** [comment]
@fullkomnun real issue generated here

https://github.com/hashicorp/vault/blob/master/vault/token_store.go#L821

> custom token ID cannot have the 's.' prefix

errors mostly suppressed for the command-line output with common `invalid request` error
