### ISSUE TITLE
How can I connect to mysql database with GoLang

### ISSUE THREAD

**Issue by memrekaraaslan** [hashicorp/vault#8093]
Hello guys.

I am new in golang and i try to write secret in mysql database with go language. But I don't know where to start. I think this source code is the wrapper for mysql : https://github.com/hashicorp/vault/tree/master/plugins/database/mysql

And I guess I should use to methods of mysql.go
How should I follow a road map. I couldn't find any examples and I'm stuck here. I would be glad if you help.

Thanks!

**Comment by michelvocks** [comment]
Hi @memrekaraaslan!

It would be great if you could elaborate a bit more on your use case. 
With secret do you mean you want to write a password (for example) via Vault into your MySQL storage engine? 
The MySQL secret engine you've linked is mainly used to automatically generate a set of database credentials for your applications via Vault or to rotate credentials for a static account in your database.

Cheers,
Michel

**Comment by memrekaraaslan** [comment]
Hello @michelvocks 

I guess I didn't make the necessary explanations. In summary, I want to keep the text file with an encrypted way in the mysql database (for username: root password: xxx) and read it when needed. In general, I want to keep secrets in the database. So far I have connected to the database with my root credentials and used the following method. And a password with a username returned. I think I will be able to write or read to the db using these credentials. But I haven't figured out how to do it yet:

`func MySQL_CreateUser() (username string, password string) {

	connectionDetails := map[string]interface{}{
		"connection_url" : 	"root:XXX@tcp(127.0.0.1:3306)/Vault",
	}

	db := new(mysql.MetadataLen, mysql.MetadataLen, mysql.UsernameLen)

	_, err := db.Init(context.Background(), connectionDetails, true)
	if err != nil {
		fmt.Printf("err: %s", err)
	}
	usernameConfig := dbplugin.UsernameConfig{
		DisplayName: "robust-long-displayname",
		RoleName:    "robust-long-rolename",
	}

	statements := dbplugin.Statements{
		Creation: []string{testMySQLRoleWildCard},
	}

	username, password, err = db.CreateUser(context.Background(), statements, usernameConfig, time.Now().Add(time.Minute))
	if err != nil {
		fmt.Printf("err: %s", err)
		return "",""
	}

	fmt.Println(username, password)
	return username, password
}`

Output:
Username: v-robust-lon-robust-lon-NdJScAUh 
Password: A1a-R5rVo3fbyvkBvEQH

Each time I run the code, it generates a different credential.

Thanks.

**Comment by michelvocks** [comment]
Hi @memrekaraaslan!

Sorry but I still have the feeling that I don't understand the full context here.

The first question I have is why do you use internal Vault code to generate a new set of credentials instead of using Vault? See https://learn.hashicorp.com/vault/secrets-management/sm-dynamic-secrets

> I think I will be able to write or read to the db using these credentials. But I haven't figured out how to do it yet

What is the exact problem here?

> Each time I run the code, it generates a different credential.

That is the idea of dynamic secrets. Instead of using the same credentials over and over again, Vault aims to provide a way to always generate a new set of credentials for a specific amount of time. Afterward, Vault automatically revokes these credentials.

Cheers,
Michel

**Comment by memrekaraaslan** [comment]
#The first question I have is why do you use internal Vault code to generate a new set of credentials instead of using Vault?

Actually, that's what I'm trying to figure out. All I want to do is write a text file to the mysql database via Vault and read it and observe if the text is encrypted. I can't figure out which methods to use to write to the database. I'd appreciate it if you could just tell me the way to go about it. Because I think what I'm doing is just creating a dynamic role.

**Comment by michelvocks** [comment]
> Actually, that's what I'm trying to figure out. All I want to do is write a text file to the mysql database via Vault and read it and observe if the text is encrypted. I can't figure out which methods to use to write to the database. I'd appreciate it if you could just tell me the way to go about it. Because I think what I'm doing is just creating a dynamic role.

Vault does not support this work-flow directly. You can use Vault's Transit secret engine (https://learn.hashicorp.com/vault/encryption-as-a-service/eaas-transit) to encrypt your text file and then manually store the returned encrypted message in your MySQL database.

Another option would be to use your MySQL database as storage backend (https://www.vaultproject.io/docs/configuration/storage/mysql.html) for Vault. You could then use the Key/Value secret engine (https://www.vaultproject.io/docs/secrets/kv/kv-v2.html) to store and read your secrets. Vault internally encrypts/decrypts the secrets and stores them safely in your MySQL database.

**Comment by memrekaraaslan** [comment]
> Another option would be to use your MySQL database as storage backend (https://www.vaultproject.io/docs/configuration/storage/mysql.html) for Vault. You could then use the Key/Value secret engine (https://www.vaultproject.io/docs/secrets/kv/kv-v2.html) to store and read your secrets. Vault internally encrypts/decrypts the secrets and stores them safely in your MySQL database.

This is what makes the most sense. I think I can solve the work I'm trying to do (write a text file (exp: .pem file) in encrypted form to the mysql database). I will use MySQL as a storage backend and use the KV secrets engine to write to the database in Go code.
Thank you, I will rewrite where I hang.

**Comment by michelvocks** [comment]
No problem. Would you mind asking the following questions via our [Discussion Forum](https://discuss.hashicorp.com/c/vault) since the issue tracker is usually reserved for bugs and feature requests? Closing this for now.
