### ISSUE TITLE
Link to changelog broken

### ISSUE THREAD

**Issue by martinssipenko** [hashicorp/vault#8094]
**Describe the bug**
On Vault website, the download page points to outdated Changelog. Even tho the website uses correct tag (latest) when I open the link I get outdated changelog.md.

**To Reproduce**
1. Go to https://www.vaultproject.io/downloads.html
2. Open chengelog https://github.com/hashicorp/vault/blob/v1.3.1/CHANGELOG.md
3. See that link is for 1.3.1 but changelog is pre 1.3.

**Expected behavior**
Link should open changelog for corresponding version.

**Comment by vvelikodny** [comment]
According to the commits, the team supports actual `CHANGELOG.md` in the `master` branch, not version ones. a912eb5f02e8f1683bb507e3f5cab834b10b237d So link on the site should be always to the to the https://github.com/hashicorp/vault/edit/master/CHANGELOG.md

**Comment by mladlow** [comment]
The site has been updated, and the link works now, as do our processes for updating it, so I'm going to close this, but thanks for flagging it @martinssipenko!
