### ISSUE TITLE
Vault server - failed to read lease entry

### ISSUE THREAD

**Issue by CharlieStokes** [hashicorp/vault#8099]
Issue
We are running a clustered vault environment consisting of 2 AWS EC2 instances connecting to an RDS database. Periodically the vault servers are sealing themselves, prompting me to enter key to unseal - upon unsealing they often immediately reseal. 

Reviewing /var/log/messages show the following trace:

Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.209Z [INFO]  core.cluster-listener: starting listener: listener_address=[::]:8201
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.209Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=[::]:8201
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.209Z [INFO]  core: vault is unsealed
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.210Z [INFO]  core: entering standby mode
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.242Z [INFO]  core: acquired lock, enabling active operation
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.283Z [INFO]  core: post-unseal setup starting
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.284Z [INFO]  core: loaded wrapping token key
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.284Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.286Z [INFO]  core: successfully mounted backend: type=kv path=secret/
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.287Z [INFO]  core: successfully mounted backend: type=system path=sys/
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.287Z [INFO]  core: successfully mounted backend: type=identity path=identity/
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.287Z [INFO]  core: successfully mounted backend: type=pki path=db_ca/
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.287Z [INFO]  core: successfully mounted backend: type=pki path=root_db/
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.287Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.297Z [INFO]  core: successfully enabled credential backend: type=token path=token/
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.297Z [INFO]  core: successfully enabled credential backend: type=ldap path=ldap/
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.297Z [INFO]  core: successfully enabled credential backend: type=approle path=approle/
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.297Z [INFO]  core: restoring leases
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.297Z [INFO]  rollback: starting rollback manager
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.308Z [ERROR] expiration: error restoring leases: error="failed to read lease entry auth/approle/login/h78aca6603bcc9b2e410d42249097de24294468e090ea3f211404b0650a4b1a79: Error 1040: Too many connec
tions"
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.308Z [ERROR] core: shutting down
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.308Z [INFO]  core: marked as sealed
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.308Z [INFO]  core: pre-seal teardown starting
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.308Z [INFO]  rollback: stopping rollback manager
Jan  6 10:31:51 sec vault: 2020-01-06T10:31:51.333Z [INFO]  core: pre-seal teardown complet

Other occurrences of this error show a different lease vault in the error. I've read other similar issues that the lease data is corrupted and needs to be removed. I'm not overly familiar with vault, so I haven't found a good explanation on this yet.

Steps to reproduce the behaviour:
Over the last 30 days we have had about 10 occurrences of this problem, happening at seemingly random points during the day.

Environment
Vault Server Version (1.2.3):
Vault CLI Version (Vault v1.2.3):
Server Operating System/Architecture: Centos Centos 3.10.0-1062

Vault server configuration file(s):

{
  "storage": {
    "mysql": {
      "ha_enabled": "true",
      "username": "sec_master",
      "password": "password",
      "database": "vault",
      "address": "rds-hostname:3306"
    }
  },
  "listener": {
    "tcp": {
      "address": "0.0.0.0:8200",
      "tls_cert_file": "/etc/pki/tls/certs/cert.pem",
      "tls_key_file": "/etc/pki/tls/certs/cert.pem"
    }
  },
  "disable_mlock": false,
  "ui": true,
  "api_addr": "https://instance-name",
  "cluster_addr": "https://instance-name:444"
}

**Comment by catsby** [comment]
Hey @CharlieStokes  - this looks like you're consuming all the available connections to your RDS database. The default is `128`, you may want to adjust by changing the `max_parallel` setting here:

- https://www.vaultproject.io/docs/configuration/storage/mysql.html#max_parallel

The number of open connections depends on the side of your RDS instance, and you'd want to check with RDS to find out for sure how many you have available. Here's a post about default connection sizes, but it's from 2017 so it may be out of date:

- https://serverfault.com/questions/862387/aws-rds-connection-limits/862418#862418

**Comment by CharlieStokes** [comment]
Hi

Sorry for the late reply, on further investigation I found the the default RDS parameter group was not applied correctly to our cluster. This mean that the default Max Connections setting as not being overridden correctly and was set to 90 instead of 600. 

I applied the change and haven't had any further issues. Thanks for all the help!

**Comment by catsby** [comment]
Thank you for the followup! I'm happy to hear you were able to resolve things.

**Comment by catsby** [comment]
Thanks for the follow up! I closed #8099
