### ISSUE TITLE
Should token-create policy flag accept comma separated policy names?

### ISSUE THREAD

**Issue by jveiga** [hashicorp/vault#810]
I was using tokens auth backend and found that passing multiple policies like in
```bash
vault token-create -policy=user,user2 
 ```
will create a policy 
```json
{
  "auth": null,
  "data": {
    "ttl": 2592000,
    "policies": [
      "user,user2"
    ],
    "path": "auth/token/create",
    "num_uses": 0,
    "meta": null,
    "id": "9e05a294-d5e8-c7f2-3a43-e2315bdf905f",
    "display_name": "token-joao2",
    "creation_time": 1448972709
  },
  "lease_duration": 0,
  "renewable": false,
  "lease_id": ""
}
```
I was expecting policies to be ["user", "user2"] is it the correct behaviour?
Using vault 0.3.1

**Comment by jefferai** [comment]
Hi there @jveiga 

This is correct behavior. You can use the `-policy` flag multiple times to specify multiple policies.

**Comment by jveiga** [comment]
OK didn't get that. Thanks
