### ISSUE TITLE
Add approle metadata to identity alias

### ISSUE THREAD

**Issue by lcgkm** [hashicorp/vault#8128]
Could we allows for writing identity token templates that include attribute:[role_name]?
(And including this attribute in path templates)
If Vault can add AppRole's role name to entity alias metadata, and then we can reference Entity metadata in our ACL templates directly.

Reference:
https://github.com/hashicorp/vault/pull/7985
https://github.com/hashicorp/vault/pull/2985
https://github.com/hashicorp/vault/issues/5916

**Comment by cfarrend** [comment]
We have worked around this by going to the entity associated with the alias after creating the AppRole and using the metadata from there

![image](https://user-images.githubusercontent.com/12799795/74892689-73457b80-53de-11ea-9106-f76f9345c457.png)

Then we can apply the policy
```
path "secret/data/github/deploy-keys/write/{{identity.entity.metadata.repo_name}}" {
  capabilities = ["read"]
}
```

Not sure if this is related to your issue @lcgkm ?

**Comment by lcgkm** [comment]
Hi @cfarrend ,
Please check this: https://github.com/hashicorp/vault/pull/7985
I don't want to add approle metadata to identity alias manually.

**Comment by cfarrend** [comment]
@lcgkm completely agree, we don't want to do it either.

We still need some method of automating this process for the time being as we are pursuing this path for policies that grant access to secrets based on an AppRole name.

The solution we are currently using is as follows:

For **new** AppRoles (using the CLI):
1. Create the AppRole
2. Get the `role_id` by using `vault read -field=role_id auth/approle/role/<role_name>/role-id`
3. Get the `secret_id` by using `vault write -field=secret_id -f auth/approle/role/<role_name>/secret-id`
4. Use vault login for the AppRole ID and Secret ID (this step creates the entity - required)
5. Get the `entity_id` by using `vault write -field=id identity/lookup/entity alias_name=<role_id> alias_mount_accessor=<>` where `alias_mount_accessor` is the ID of your AppRole authentication method (from the Auth Methods section in Vault)
6. Write the metadata to the entity by using `vault write identity/entity/id/<entity_id>/ metadata=approle_name=<role_name>` - you can now use a policy similar to the one described above

For **existing** AppRoles:
Do steps 5 & 6

**Comment by lcgkm** [comment]
@cfarrend Agree!
The step 4 is very important. It split the whole provisioning workflow.
