### ISSUE TITLE
getting Unsuppoted protocal in Hashicorp vault

### ISSUE THREAD

**Issue by chethan-msj** [hashicorp/vault#8129]
please advice to fix this issue 

2020-01-10T11:32:53.427+0530 [WARN]  core.cluster-listener: no TLS config found for ALPN: ALPN=[]
2020-01-10T11:32:53.428+0530 [DEBUG] core.cluster-listener: error handshaking cluster connection: error="unsupported protocol"
2020-01-10T11:32:53.798+0530 [WARN]  core.cluster-listener: no TLS config found for ALPN: ALPN=[]
2020-01-10T11:32:53.798+0530 [DEBUG] core.cluster-listener: error handshaking cluster connection: error="unsupported protocol"

i am generating the certificate in client side ,by using below code 

     KeyStore ks = KeyStore.getInstance(KeyStore.getDefaultType());
            ks.load(in, passphrase);
            in.close();

            SSLContext context = SSLContext.getInstance("TLS");

            socketFactory = new SSLSocketFactory("TLSv1.2",trustStore, passwd, trustStore,null, SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);

Thanks!

**Comment by ncabatoff** [comment]
My hunch is that you're connecting to the wrong port, e.g. 8201 instead of 8200.  Can you post your listener config and how you're connecting to vault?

**Comment by chethan-msj** [comment]
@michelvocks  ya ..you are right ..i changed port to 8200,and able to connect thanks for your suggetion

**Comment by anoncam** [comment]
I'm glad to see that the Protocal is now Suppoted

**Comment by hsimon-hashicorp** [comment]
Hello @anoncam, did you have anything constructive that you wished to add? Please also familiarize yourself with the HashiCorp community guidelines, as well: https://www.hashicorp.com/community-guidelines
Thanks!

**Comment by anoncam** [comment]
Hi @hsimon-hashicorp the spirit of what I said still remains.  This was helpful.  The only confusing part of this documentation artifact is the spelling is incorrect.  So in the format of the issue, I altered my spelling the best I could.

**Comment by hsimon-hashicorp** [comment]
Hi @anoncam - as I said previously, please familiarize yourself with the HashiCorp community guidelines.
To wit:

> Be conscious of the words and phrases that you choose when communicating with others. Be kind. Do not insult or put down others. Sexist, racist, or other prejudicial or exclusionary comments are never welcome in the HashiCorp community. If you think your conversation is making another community member uncomfortable, try to make amends and move forward. Avoid using colloquialisms or words and phrases that may have subjective connotations. Be aware that your first language may not be the first language of who you are communicating with.

There is no need to make a response in the manner in which you did, when a simple "thanks, this helped" would have sufficed. Thank you for your understanding.

**Comment by anoncam** [comment]
> Hi @anoncam - as I said previously, please familiarize yourself with the HashiCorp community guidelines.
> 
> To wit:
> 
> 
> 
> > Be conscious of the words and phrases that you choose when communicating with others. Be kind. Do not insult or put down others. Sexist, racist, or other prejudicial or exclusionary comments are never welcome in the HashiCorp community. If you think your conversation is making another community member uncomfortable, try to make amends and move forward. Avoid using colloquialisms or words and phrases that may have subjective connotations. Be aware that your first language may not be the first language of who you are communicating with.
> 
> 
> 
> There is no need to make a response in the manner in which you did, when a simple "thanks, this helped" would have sufficed. Thank you for your understanding.

My deepest apologies, this was
not my intention, and I will be mindful in the future.
