### ISSUE TITLE
Pass Context to http requests

### ISSUE THREAD

**Issue by arminm** [hashicorp/vault#8134]
I'm having a hard time using APM with OpenTracing with this client, because there's no way for me to pass a context (e.g. HTTP requests' `req.Context()`) to the functions that make an HTTP call (i.e. the `Logical` module which does `Read`, `ReadWithData`, `List`, etc with HTTP calls to the backend).

I would like to ask for allowing for context to be passed to the Logical client's functions so people can do fine grained tracing, as well as cancel a Vault request if the original request has been cancelled or times out.

**Comment by iusergii** [comment]
Is anything changed since [Opentracing support](https://github.com/hashicorp/vault/issues/3505) ?
