### ISSUE TITLE
How to use iam_role in "vault write aws/config/root"

### ISSUE THREAD

**Issue by anemptyair** [hashicorp/vault#8139]
Currentlly i config with below command:

-  vault write aws/config/root \     
-        access_key=******\
-        secret_key=****** \
-        region=us-east-1

Does it support aws iam_role?

**Comment by joelthompson** [comment]
Hi @anemptyair -- currently, the AWS secret engine does not support assuming an IAM role before issuing AWS requests. However, if you run it on an EC2 instance that has an IAM instance profile attached to it, Vault will recognize those credentials automatically.

Can you describe your use case in a bit more detail?

**Comment by anemptyair** [comment]
@joelthompson  i want to get aws credentials with "vault read aws/creds/my-role", so firstly i need to add root credentials by "vault write aws/config/root" , but i don't want to add "access_key" and "secret_key",can i just add a field named "iam_role"?

**Comment by joelthompson** [comment]
Hi @anemptyair -- you don't need to enter access key and secret key if your Vault server is running on an EC2 instance that has an instance profile associated with it.

If we did add an `iam_role` field that indicated the ARN of an IAM role for Vault to assume before making other API calls, then Vault would need credentials to call AssumeRole to get credentials for that IAM role, and now you're back to configuring an access key and secret key or just using the ambient credentials.

**Comment by anemptyair** [comment]
Got it , thank u very much.
