### ISSUE TITLE
Vault AWS without root credentials fails v4 signing

### ISSUE THREAD

**Issue by moofish32** [hashicorp/vault#814]
I have been playing with vault from my private AWS account and I wanted to pilot from my work account. This account follows best practices and removes the root credentials. Based on the aws [docs](https://www.vaultproject.io/docs/secrets/aws/index.html) I thought I could use a standard IAM user with the following policy 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:CreateAccessKey",
                "iam:CreateUser",
                "iam:PutUserPolicy",
                "iam:ListGroupsForUser",
                "iam:ListUserPolicies",
                "iam:ListAccessKeys",
                "iam:DeleteAccessKey",
                "iam:DeleteUserPolicy",
                "iam:RemoveUserFromGroup",
                "iam:DeleteUser"
            ],
            "Resource": [
                "arn:aws:iam::redacted-account-number:user/vault-*"
            ]
        }
    ]
}
```

However when I create a user associate that policy (wait a few minutes just in case policy association takes some time ... ) then run through the quick start with AWS.  When I do this command:

```
vault read aws/creds/deploy
```

The response is:

```
Error reading aws/creds/deploy: Error making API request.

URL: GET http://127.0.0.1:8200/v1/aws/creds/deploy
Code: 400. Errors:

* Error creating IAM user: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/

host:iam.amazonaws.com
x-amz-date:20151203T164746Z

host;x-amz-date
*redacted string*

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20151203T164746Z
20151203/us-east-1/iam/aws4_request
*redacted string*

        status code: 403, request id: *redacted string*
```

However if the root config is provided root credentials this error does not occur.

Vault was brew installed 

```
[~/code/vault_experiments] vault version
Vault v0.3.1
```

**Comment by jefferai** [comment]
I suggest posting this on the vault-tool mailing list (https://groups.google.com/forum/#!forum/vault-tool) -- lots of people there are using Vault with AWS, and I don't think they're all using root users (or they are, but it's a security-sensitive bunch and they generally follow best-practice). They may be able to spot something in your config/policy that is causing this.

You may also want to try the 0.4.0 RC2 release that just came out two days ago. It has an updated AWS SDK -- they just hit 1.0 -- and the behavior could be different.

**Comment by moofish32** [comment]
for those following along at home: https://groups.google.com/forum/#!topic/vault-tool/SAQVyWb0v2c
