### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by tomferreira** [hashicorp/vault#817]
Is there any interest in developing a Web UI for Vault?

I think it is a very nice feature to manage secrets and facilitate the adoption of the tool by non-developers users, such as infra staff.

Thanks!

**Comment by jefferai** [comment]
We'd love to see a web UI for Vault, but it is not currently on our internal roadmap. Too many other things to do!

**Comment by AMeng** [comment]
I've created a basic web interface here: https://github.com/AMeng/vault-web

**Comment by jefferai** [comment]
Sorry about the reopen. Thanks for posting about the UI!

**Comment by sstarcher** [comment]
my co-workers and I did this a while back
https://github.com/nyxcharon/vault-ui

**Comment by pizzaops** [comment]
Kinda unfortunate. I'm trying to sell customers on using vault instead of hardcoding variables into places like hiera (or databags if you're a chef user I guess?) but most of the more "corporate" types balk at the lack of any interface for non-developers. Just my $0.02.

**Comment by jefferai** [comment]
@pizzaops A UI is part of Vault Enterprise and is currently planned to ship this quarter.

**Comment by pizzaops** [comment]
@jefferai ❤️ exactly what we needed, thank you!

**Comment by briandeheus** [comment]
@jefferai > UI is part of Vault Enterprise and is currently planned to ship this quarter.

For Vault Enterprise only? Or will this be included in Vault by default similar to Consul?

**Comment by vishalnayak** [comment]
@briandeheus Yes, the UI will only be in the Vault Enterprise binary.

**Comment by briandeheus** [comment]
Thanks for the quick response!

**Comment by jippi** [comment]
If anyone want to put the work in, Vault support is planned for Hashi-UI; I support Consul and Nomad today, and having Vault support would make it a perfect combo tool ! :) 

https://github.com/jippi/hashi-ui
