### ISSUE TITLE
There is a problem with displaying passwords in default ui mode

### ISSUE THREAD

**Issue by alireza95jalili** [hashicorp/vault#8188]
hi there is a bug that  i cant see password in vault default ui mode, but when i switch to json mode, password will show up.

checkout  this screenShots:
https://www.dropbox.com/s/7iep98ql08p9alx/Screenshot_2020-01-18_09-05-02.png?dl=0
https://www.dropbox.com/s/p08tyg0y03evmvg/Screenshot_2020-01-18_09-05-27.png?dl=0
https://www.dropbox.com/s/p08tyg0y03evmvg/Screenshot_2020-01-18_09-05-27.png?dl=0

```
**Environment:**
Key                    Value
Seal Type          shamir
Initialized           true
Sealed               false
Total Shares      5
Threshold          3
Version              1.3.0
Cluster Name    vault-cluster-e7*****4
Cluster ID      228e33a3**********0f0edd0bbc4d
HA Enabled      false
```

**Comment by michelvocks** [comment]
Hi @alireza95jalili!

Thank you for opening this issue. This issue has been already resolved with https://github.com/hashicorp/vault/pull/7926 and should be available with Vault 1.3.1 onwards.

Cheers,
Michel
