### ISSUE TITLE
mysql backend HA lock handling is unsafe

### ISSUE THREAD

**Issue by drawks** [hashicorp/vault#8203]
**Describe the bug**
When using vault with the mysql backend in HA mode if connectivity to the db is lost between a standby node it will cause a panic/crash.

**To Reproduce**
1. Configure 2 vault instances in HA with mysql storage backend
Instance 1 vault1.conf:
```
storage "mysql" {
    username    = "vault"
    password    = "[redacted]"
    address     = "127.0.0.1"
    database    = "vault"
    table       = "vault"
    lock_table  = "vault_lock"
    ha_enabled  = "true"
    max_connection_lifetime = "14400" # 4 hours to stay under the db's max 12 hours
}

listener "tcp" {
    address = "127.0.0.1:8200"
    tls_disable = 1
}

api_addr="https://127.0.0.1:8200"
```
Instance 2: vault2.conf
```
storage "mysql" {
    username    = "vault"
    password    = "[redacted]"
    address     = "127.0.0.1"
    database    = "vault"
    table       = "vault"
    lock_table  = "vault_lock"
    ha_enabled  = "true"
    max_connection_lifetime = "14400" # 4 hours to stay under the db's max 12 hours
}

listener "tcp" {
    address = "127.0.0.2:8200"
    tls_disable = 1
}

api_addr="https://127.0.0.2:8200"
```

2. Start Vault instance 1
`vault server -config=/vault1.conf`
3. Initialize and unseal instance 1
```
$ VAULT_ADDR=http://127.0.0.1:8200 vault operator init
<redacted>
$ VAULT_ADDR=http://127.0.0.1:8200 vault operator unseal
<redacted>
$ VAULT_ADDR=http://127.0.0.1:8200 vault operator unseal
<redacted>
$ VAULT_ADDR=http://127.0.0.1:8200 vault operator unseal
<redacted>
```
4. Confirm Vault is operational with HA enabled and instance 1 as active node
```hcl
$ VAULT_ADDR=http://127.0.0.1:8200 ./vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.2.3
Cluster Name    vault-cluster-e0ab86e5
Cluster ID      b81d3263-7a26-5069-ed97-284e937b37a7
HA Enabled      true
HA Cluster      https://127.0.0.1:8201
HA Mode         active
```
5. Start Vault instance 2
`vault server -config=/vault2.conf`
6. Unseal instance 2
```
$ VAULT_ADDR=http://127.0.0.2:8200 vault operator unseal
<redacted>
$ VAULT_ADDR=http://127.0.0.2:8200 vault operator unseal
<redacted>
$ VAULT_ADDR=http://127.0.0.2:8200 vault operator unseal
<redacted>
```
7. Confirm Vault is operational on Instance 2
```hcl
$ VAULT_ADDR=http://127.0.0.2:8200 ./vault statusKey                    Value
---                    -----
Seal Type              shamir
Initialized            true
Sealed                 false
Total Shares           5
Threshold              3
Version                1.2.3
Cluster Name           vault-cluster-e0ab86e5
Cluster ID             b81d3263-7a26-5069-ed97-284e937b37a7
HA Enabled             true
HA Cluster             https://127.0.0.1:8201
HA Mode                standby
Active Node Address    https://127.0.0.1:8200
```
8. Stop mysql
`$ sudo /etc/init.d/mysql stop`
9. Observe that whichever instance was in standby segfaults
```
2020-01-21T17:55:56.925Z [INFO]  core.cluster-listener: starting listener: listener_address=127.0.0.2:8201
2020-01-21T17:55:56.926Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=127.0.0.2:8201
2020-01-21T17:55:56.926Z [INFO]  core: vault is unsealed
2020-01-21T17:55:56.926Z [INFO]  core: entering standby mode
2020-01-21T17:56:32.790Z [ERROR] core: failed to acquire lock: error="mysql: lock already held"
2020-01-21T17:56:36.935Z [ERROR] core: key rotation periodic upgrade check failed: error="dial tcp 127.0.0.1:3306: connect: connection refused"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2146ec9]

goroutine 88 [running]:
github.com/hashicorp/vault/physical/mysql.(*MySQLLock).Lock(0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/vault/physical/mysql/mysql.go:626 +0xe9
github.com/hashicorp/vault/physical/mysql.(*MySQLHALock).attemptLock(0xc00035f1a0, 0x324ba9b, 0x9, 0xc000059500, 0x24, 0xc0000954a0, 0xc00008b2c0, 0xc000434af0)
	/gopath/src/github.com/hashicorp/vault/physical/mysql/mysql.go:452 +0xcc
created by github.com/hashicorp/vault/physical/mysql.(*MySQLHALock).Lock
	/gopath/src/github.com/hashicorp/vault/physical/mysql/mysql.go:418 +0x22c
```

**Expected behavior**
I believe it is expected that all vault nodes will stay up and unsealed when the storage backend has become unavailable. Requests to vault which require interaction with the backend should return a 500 response to the client.
**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.2.3
* Vault CLI Version (retrieve with `vault version`): 1.2.3
* Server Operating System/Architecture: CentOS 6.x

Vault server configuration file(s):

see above

**Comment by catsby** [comment]
Hello! Thanks for reporting this. I've opened #8229 that should fix this

**Comment by sksingh20** [comment]
Mysql Hashicorp Vault in HA leaving multiple sleep connections with Mysql from standby node.
@drawks did you faced this problem?

Standby node leaving all connection with mysql as established while trying to acquire lock

pi@serlog:~ $ sudo netstat | grep mysql |grep -i serlog|grep -i established
tcp 0 0 serlog:mysql 192.168.0.213:58760 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58762 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58834 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58818 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58822 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58694 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58728 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58790 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58736 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58668 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58688 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58750 ESTABLISHED
tcp 0 0 serlog:57480 serlog:mysql ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58714 ESTABLISHED
tcp 0 0 serlog:57482 serlog:mysql ESTABLISHED
tcp 0 0 serlog:mysql serlog:46002 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58800 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58734 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58784 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58708 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58842 ESTABLISHED
tcp 0 0 serlog:mysql serlog:57482 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58840 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58686 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58792 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58812 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58810 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58700 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58774 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58742 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58756 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58768 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58744 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58780 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58680 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58766 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58832 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58816 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58786 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58806 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58838 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58682 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58716 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58828 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58676 ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58722 ESTABLISHED
tcp 0 0 serlog:46002 serlog:mysql ESTABLISHED
tcp 0 0 serlog:mysql 192.168.0.213:58710 ESTABLISHED
tcp 0 0 serlog:mysql serlog:57480 ESTABLISHED
pi@serlog:~ $

On standby vault node I have following output when I trace a connection

pi@vaultf2:~ $ sudo lsof -i tcp:59860
COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
vault 9180 root 78u IPv4 63158 0t0 TCP 192.168.0.213:59860->192.168.0.212:mysql (ESTABLISHED)
pi@vaultf2:~ $

pi@vaultf2:~ $ ps -ef|grep -i 9180
root 9180 1 2 18:27 ? 00:00:38 /usr/bin/vault server -config=/etc/vault/config.hcl
pi 10527 664 0 18:52 pts/0 00:00:00 grep --color=auto -i 9180
pi@vaultf2:~ $

**Comment by sksingh20** [comment]
@catsby Who can help?
