### ISSUE TITLE
Make it possible to set TTL for SSH Dynamic Key Secret

### ISSUE THREAD

**Issue by cvle** [hashicorp/vault#821]
Currently creating credentials using the SSH Dynamic Key Type uses the system's default TTL. 
It would be a great security enhancement to be able to provide a custom TTL.
Something like this:

```
vault write ssh/creds/dynamic_key_role ip=x.x.x.x ttl=600
```

**Comment by jefferai** [comment]
I believe it honors the backend default/max for this reason, which can be set with the mount-tune command

**Comment by wikiwi** [comment]
I didn't know we can set individual defaults for the mounts. This helps. Still wouldn't it make sense to allow individual TTLs? I imagine handing out a key for a contractor who works for 7 days on a project on the server. Just one example.

**Comment by jefferai** [comment]
@wikiwi It makes some sense, and it will eventually appear in the SSH backend, but at a role/mount level (as opposed to the current behavior of just mount level). At least for setting default/max.

Right now it's up to backends to handle TTL parameters, and we'll be moving towards standardizing how roles are set up, including role-based TTLs. Then you could just create a new role for the contractor.

In the meantime, it's not as nice, but you could create a second backend mount for the contractor.

**Comment by wikiwi** [comment]
The role/mount approach sounds great!

**Comment by jefferai** [comment]
Should already be implemented, and dynamic keys are deprecated now too.
