### ISSUE TITLE
Vault pki certificate tidy cannot delete certificate?

### ISSUE THREAD

**Issue by wongkafai** [hashicorp/vault#8210]
Vault pki certificate tidy cannot delete certificate?

https://www.vaultproject.io/api/secret/pki/index.html#tidy
1.safety_buffer defaults to 72h??
2.cannot setup tidy

![Capture](https://user-images.githubusercontent.com/8857387/72861175-12098a00-3d04-11ea-9ac5-a7a77739dce1.PNG)

**Comment by catsby** [comment]
Hello - 

The `tidy` endpoint will remove certificates that are expired and past the `safety_buffer` according to the local clock of the server that the command is ran on. The `tidy` endpoint does not return any information on which certificates are being removed, if any, instead that information can be found in the Vault's logs as mentioned. 

I'm not sure that this represents any kind of bug. If you have other questions or could clarify any information here, we'll be happy to look into them.

**Comment by catsby** [comment]
Hello - we haven't heard back in some time, so we're going to close this issue for now. If you have more information please let us know by opening a new issue, and optionally referencing this one. Thanks!
