### ISSUE TITLE
Remove Plain Text LDAP User Passwords from Audit Logs

### ISSUE THREAD

**Issue by eternalyperplxed** [hashicorp/vault#8212]
**Is your feature request related to a problem? Please describe.**
Audit logs contain plain text user password when doing LDAP authentications

**Describe the solution you'd like**
Obfuscated or complete removal of this field from the logs

**Describe alternatives you've considered**
None

**Explain any additional use-cases**
None

**Comment by ncabatoff** [comment]
Hi @eternalyperplxed,

Could you provide a (redacted) example please?

**Comment by eternalyperplxed** [comment]
Sure, to provide some additional context, we have Vault running in k8s on AWS EKS with logging set for STDOUT.  The following redacted logs are examples....

`{"time":"2020-01-22T14:40:29.355824172Z","type":"request","auth":{"token_type":"default"},"request":{"id":"f2c2805b-73e4-7f37-36b7-74978a15bcd3","operation":"update","namespace":{"id":"root"},"path":"auth/ldap/login/redacted-user","data":{"password":"PLAIN TEXT PASSWORD"},"remote_address":"X.X.X.X"}}`

`{"time":"2020-01-22T14:41:29.357042063Z","type":"response","auth":{"token_type":"default"},"request":{"id":"f2c2805b-73e4-7f37-36b7-74978a15bcd3","operation":"update","namespace":{"id":"root"},"path":"auth/ldap/login/redacted-user","data":{"password":"PLAIN TEXT PASSWORD"},"remote_address":"X.X.X.X"},"response":{"data":{"error":"1 error occurred:\n\t* error connecting to host \"ldaps://SERVERNAME\": LDAP Result Code 200 \"Network Error\": dial tcp X.X.X.X:636: i/o timeout\n\n"}}}`

Kindly ignore the error part of the second log as that is unrelated to this issue.

**Comment by ncabatoff** [comment]
Is it possible that you've set `log_raw=true` on the audit device?  I would've expected the `error` field to also be HMAC'd.

**Comment by eternalyperplxed** [comment]
Just checked the audit settings and it looks like log_raw is set to true.  I'll update the settings and verify that fixes it.

**Comment by eternalyperplxed** [comment]
looks like that fixed it! Thanks for the pointer.
