### ISSUE TITLE
Website / CSS: Ready to get started buttons look buggy

### ISSUE THREAD

**Issue by doertedev** [hashicorp/vault#8232]
**Describe the bug**
Two buttons just above the footer of the Vaultproject.io page look a bit odd. I've attached a screenshot from https://www.vaultproject.io/ taken on 2020-01-24: 
![image](https://user-images.githubusercontent.com/1579335/73058042-144e1e80-3e93-11ea-9f3b-c11cd374c454.png)
latest chrome + macos.

**Comment by h3xar0n** [comment]
I remember seeing that, but it seems it's no longer in the footer of  https://www.vaultproject.io/ as of 2020-01-30.

**Comment by h3xar0n** [comment]
Found it at the bottom of https://www.vaultproject.io/use-cases/identity-based-access/ on 2/8/20

<img width="1640" alt="Screen Shot 2020-02-08 at 5 31 58 PM" src="https://user-images.githubusercontent.com/21048592/74094621-1b7f4a00-4a99-11ea-9154-8b19df9ed6b5.png">

**Comment by cipherboy** [comment]
Looks like this was already resolved as discussed in #8320. Thanks!
