### ISSUE TITLE
Allow encryption of tls_key_file

### ISSUE THREAD

**Issue by davidsalvador** [hashicorp/vault#824]
Currently the private key for the certificate to use on TLS connections can only be stored in clear text.
I think it would be great to store that key encrypted and prompt the user for the passphrase.

Maybe something like that:

```
$ vault server -config=/opt/vault/some.config
Enter certificate's private key passphrase:
Certificate's private key successfully decrypted
==> Vault server configuration:
...
```

**Comment by jefferai** [comment]
Thanks for the suggestion!

**Comment by mterron** [comment]
Or even store the passphrase for the cert in Vault the first time it runs and from then on automatically unseal the cert. That would be great and operationally simpler.

**Comment by jefferai** [comment]
@mterron I really like that idea, *but*, the TLS cert is used for the unseal operation. There isn't a protected way to store it until Vault is unsealed.

**Comment by pkhamre** [comment]
+1

**Comment by pkellychnct** [comment]
Any movement on this? Has anyone found any workarounds?

**Comment by JoostvdB94** [comment]
@davidsalvador I can't even find a way to set this password in clear text. Could you please help me find this setting?

**Comment by davidsalvador** [comment]
@JoostvdB94 you can find the documentation [here](https://www.vaultproject.io/docs/configuration/listener/tcp.html). See the tcp listener parameter "tls_key_file".
