### ISSUE TITLE
Writing new policies over control group  with cli and api gives diffrent results

### ISSUE THREAD

**Issue by bireckim** [hashicorp/vault#8242]
**Describe the bug**
While control group is added to policies on path:
```
path "/sys/policies/acl/*"
{
  capabilities = ["create","update","delete"]
  control_group = {
		factor "authorizer" {
			identity {
				group_names = [ "cg_accept" ]
				approvals = 1
			}
		}
	}
}
```
There is diffrence behaviour when trying to add new policy with CLI or API call.
With CLI command is always returning Success
With API command is returning wrrapping token and accessor.

**To Reproduce**
1. Login with token where control group is added on sys/policies/acl for creating,updating and deletion
2. Run `vault policy write test test.hcl`
Output:
`Success! Uploaded policy: test`

3. Same call to API. This command was created from  `vault policy write -output-curl-string test test.hcl`  
`curl -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"policy":"path \"/some/data/path\" {\n  capabilities = [ \"read\" ]\n} \n"}' http://localhost:8200/v1/sys/policies/acl/test`

Output
`{"request_id":"","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":{"token":"s.","accessor":"aaaa","ttl":86400,"creation_time":"2020-01-27T06:57:17Z","creation_path":"sys/policies/acl/test"},"warnings":null,"auth":null}`

**Expected behavior**
While running command where control group is added, we should get token and accessor.
CLI command should return proper output when working with control groups.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.0
* Vault CLI Version (retrieve with `vault version`): 1.3.0
* Server Operating System/Architecture: RHEL 7.7

**Comment by ncabatoff** [comment]
Hi bireckim,

Apologies, but support for enterprise customers needs to go through our
enterprise support portal. Reporting through our enterprise support portal
ensures that we can comply with contractually obligated SLAs around
customer support requests, and that a support engineer or technical account
manager can track the issue from report to resolution.

Best regards,
Nick
