### ISSUE TITLE
Inconsistent HTTP response code for 'missing data fields'

### ISSUE THREAD

**Issue by mhaji** [hashicorp/vault#825]
vault -version
    Vault v0.3.1

Missing out the client token results in a 400 Bad Request:

    curl -v -X POST -d "{\"foo\":\"bar\"}" http://localhost:8200/v1/secret/10e435ab-722b-4747-aaa3-43a6e50d43bb
    * Connected to localhost (127.0.0.1) port 8200 (#0)
    > POST /v1/secret/10e435ab-722b-4747-aaa3-43a6e50d43bb HTTP/1.1
    > User-Agent: curl/7.37.1
    > Host: localhost:8200
    > Accept: */*
    > Content-Length: 13
    > Content-Type: application/x-www-form-urlencoded
    >
    * upload completely sent off: 13 out of 13 bytes
    < HTTP/1.1 400 Bad Request
    < Content-Type: application/json
    < Date: Wed, 09 Dec 2015 14:36:14 GMT
    < Content-Length: 36
    <
    {"errors":["missing client token"]}
    * Connection #0 to host localhost left intact

However, sending a request that is missing a body results in a 500 Internal Server Error:

    curl -v -X POST -H "X-Vault-Token:$VAULT_TOKEN" http://localhost:8200/v1/secret/10e435ab-722b-4747-aaa3-43a6e50d43bb
    * Connected to localhost (127.0.0.1) port 8200 (#0)
    > POST /v1/secret/10e435ab-722b-4747-aaa3-43a6e50d43bb HTTP/1.1
    > User-Agent: curl/7.37.1
    > Host: localhost:8200
    > Accept: */*
    > X-Vault-Token:0e0ff950-a63b-7f8f-9ff7-0574cf62fe8b
    >
    < HTTP/1.1 500 Internal Server Error
    < Content-Type: application/json
    < Date: Wed, 09 Dec 2015 14:40:23 GMT
    < Content-Length: 35
    <
    {"errors":["missing data fields"]}
    * Connection #0 to host localhost left intact

Do you agree that the latter request should also return a 400?

**Comment by mhaji** [comment]
To add, this was running in dev mode.

**Comment by jefferai** [comment]
Yep, agreed...and fixed!
