### ISSUE TITLE
Support Curve25519 and Curve448 in the pki backend

### ISSUE THREAD

**Issue by rgl** [hashicorp/vault#8252]
Currently the pki backend [only supports the NIST P-* curves](https://github.com/hashicorp/vault/blob/1d13290b361314466f76e251826f60c92aa67bb7/sdk/helper/certutil/helpers.go#L196) but since those curves are not [considered safe](https://safecurves.cr.yp.to/) I would like to have [Curve25519/Curve448](https://tools.ietf.org/html/rfc7748) available in the pki backend.

Maybe it could be triggered with `key_type` set to `ec-curve25519`.

Please note that [Curve448 is not yet available in go x/crypto or tls library](https://github.com/golang/go/issues/29390).

**Comment by annerajb** [comment]
Considering ed448 is not available yet in go.

Would it be possible to split this issue into two separate ones ?

That way work on ed25519 could be done without waiting for ed448?

**Comment by cipherboy** [comment]
As contributed by @annerajb (thanks!) there is support for X25519 in the PKI secrets engine. Go Crypto team has declined to add support for X448; as such, we'll have to decline X448 support until such time as Go includes it.

Seeing such, I'm going ahead and closing. Feel free to re-open if Go's stance changes and support lands there.
