### ISSUE TITLE
AliCloud write policy

### ISSUE THREAD

**Issue by MikeVL** [hashicorp/vault#8256]
**Describe the bug**
Unable write single policy to AliCloud secrets

**To Reproduce**
1. Run `vault write alicloud/role/policy-based remote_policies='name:AliyunOSSReadOnlyAccess,type:System'`
2. See error
```
Error writing data to alicloud/role/policy-based: Error making API request.

URL: PUT http://active.vault.service.consul:8200/v1/alicloud/role/policy-based
Code: 500. Errors:

* 1 error occurred:
	* policy type is required in name:AliyunOSSReadOnlyAccess
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.2
* Vault CLI Version (retrieve with `vault version`): 1.3.2

**Additional context**
This command works fine:
```
vault write alicloud/role/policy-based \
    remote_policies='name:AliyunOSSReadOnlyAccess,type:System' \
    remote_policies='name:AliyunRDSReadOnlyAccess,type:System'
```
Result:
```
Success! Data written to: alicloud/role/policy-based
```

**Comment by tyrannosaurus-becks** [comment]
Thanks, @MikeVL , for bringing this to our attention. I was able to duplicate it and have the fix linked.
