### ISSUE TITLE
TrimSpace secret engine path

### ISSUE THREAD

**Issue by Wouter0100** [hashicorp/vault#8268]
**Is your feature request related to a problem? Please describe.**
I created a secret engine, and was unable to access it afterwards through most tools (CLI, Ansible lookup module). After debugging it for an hour, I came across the space in the beginning of my secret path. I accidentally entered a space before the path.

**Describe the solution you'd like**
When I create a new Secrets Engine, it would be awesome that the path will be trimmed - just in case. I don't see any reason why a space would be useful in this place.

**Describe alternatives you've considered**
I haven't really considered any other solutions. Maybe trimming in the Vault UI or showing a notification ("You have a space in front of the path, are you sure?") would also suffice. 

**Explain any additional use-cases**
n/a

**Additional context**
n/a

**Comment by catsby** [comment]
Hey @Wouter0100 - just to be clear, the extra space was added when you enabled the secret with `vault secrets enable -path=` correct? As opposed to when the plugin was registered to the catalog as in https://www.vaultproject.io/docs/internals/plugins/#plugin-catalog

**Comment by Wouter0100** [comment]
Thanks for your reply! No, I created the secret engine through the UI.
