### ISSUE TITLE
Vault UI via iframes

### ISSUE THREAD

**Issue by michalgm** [hashicorp/vault#8281]
**Is your feature request related to a problem? Please describe.**
We have built a internal web app that provides a streamlined view into the various components of our cloud architecture. The app primarily acts as glue around a series of iframes to app-specific UIs.
We have been using the 3rd-party hashi-ui for our view into nomad jobs, but would like to switch to your much-improved native nomad ui (great work, btw!). However, currently we are unable to do this, as the ui returns a restrictive content-security-policy header that disallows it being used in an iframe:
content-security-policy: default-src 'none'; connect-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline' 'self'; form-action 'none'; frame-ancestors 'none'

**Describe the solution you'd like**
Is there any possibility the frame-ancestors 'none' could be removed from the policy? Or the policy could be made configurable?

**Describe alternatives you've considered**
We *could* serve the ui through a proxy that removes/modifies the header in question, but that seems a little messy.

(note i've filed a similar feature request for nomad UI: https://github.com/hashicorp/nomad/issues/7056

**Comment by chrishoffman** [comment]
You can update the headers served by the UI using the `/sys/config/ui` endpoint.  See docs here https://www.vaultproject.io/api-docs/system/config-ui/.
