### ISSUE TITLE
identity/oidc: well-known endpoint returns different sets of keys

### ISSUE THREAD

**Issue by neeki-hushyar** [hashicorp/vault#8284]
**Describe the bug**
On a 3-instance HA Vault environment, a GET request to the same well-known keys endpoint, returns 1 of 3 different sets of keys, seemingly at random.

**To Reproduce**

1. Create token endpoint:
 vault write identity/oidc/key/\<name\> allowed_client_ids="*"

2. Link endpoint to role:
vault write identity/oidc/role/\<name\> key=\<name\>
 
3. Send GET request to well-known endpoint:
 **curl https://\<vault address\>:/v1/\<namespace\>/identity/oidc/.well-known/keys** 

**Example Response**

The output reflects 3 curl requests to the well-known endpoint, made within the span of 5 seconds. You'll notice the first and third requests returned the same sets of keyids, but the second request is different.

curl -s https:///\<vault address\>:/v1/\<namespace\>/identity/oidc/.well-known/keys | jq '.keys[] .kid'
"11b3f3c9-4c0c-25ba-0103-22742571074a"
"40532087-2cd1-731a-21b4-f85jka31fa25"
"320e3584-5578-2a9a-33c1-7awc005ff1cc"
"98234479-1cf1-6243-b741-2504d8ed4fd6"
"c2e1aea7-4572-fa01-7947-e7f770384d6b"
"c5b5ddfd-6f44-8070-c2dd-d7fbf8e8qw3c"
"ce1014io-2119-fb26-b4d1-20fe52b4kcd2"
"da1c5f0b-b4d6-5cf6-1308-5c8de6dcd79c"

curl -s https:///\<vault address\>:/v1/\<namespace\>/identity/oidc/.well-known/keys | jq '.keys[] .kid'
"032rt6ea-a699-97a8-cab5-18d3bdcb22fc"
"0fd31aef-da1a-5f21-627a-a16fca804980"
"1349942f-51d6-9215-f260-e2155723df32"
"41af1056-c862-e6e5-647a-2b0f1f2452d7"
"77898216-dac1-245d-85e8-30bb51c156e6"
"9947ee73-b7d7-3197-akd3-f6734b0fcbae"
"d850ab68-5f4f-04e1-013d-82qp7c62cb54"
"f6328350-d526-1c11-964e-9e91e1c17a09"

curl -s https:///\<vault address\>:/v1/\<namespace\>/identity/oidc/.well-known/keys | jq '.keys[] .kid'
"11b3f3c9-4c0c-25ba-0103-22742571074a"
"40532087-2cd1-731a-21b4-f85jka31fa25"
"320e3584-5578-2a9a-33c1-7awc005ff1cc"
"98234479-1cf1-6243-b741-2504d8ed4fd6"
"c2e1aea7-4572-fa01-7947-e7f770384d6b"
"c5b5ddfd-6f44-8070-c2dd-d7fbf8e8qw3c"
"ce1014io-2119-fb26-b4d1-20fe52b4kcd2"
"da1c5f0b-b4d6-5cf6-1308-5c8de6dcd79c"

**Expected behavior**
Querrying the well-known endpoint should return the same key[s] every time

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.2.4
* Backend database is consul

**Comment by neeki-hushyar** [comment]
I can't imagine this is the expected behavior but please correct me if I'm wrong.

Any update would be great, this is blocking our use of oidc identity

**Comment by kalafut** [comment]
Hi. Thanks for the issue report. This isn’t expected behavior and we’re looking into it.

**Comment by kalafut** [comment]
@neeki-hushyar Are you using [performance standbys](https://www.vaultproject.io/docs/enterprise/performance-standby/)?
