### ISSUE TITLE
[Documentation] HTTP api gives 403 but this is documented as 401

### ISSUE THREAD

**Issue by feliksik** [hashicorp/vault#831]
My policy doesn't allow writing on a certain path and gives a 403 error:
{"errors":["permission denied"]}

This is documented as 401 at  https://vaultproject.io/docs/http/ ..

Running vault 0.3.1

**Comment by mlafeldt** [comment]
I think this is a bug in the documentation.

There's no `http.StatusUnauthorized` (401) in the entire codebase. Also, [this code] returns `http.StatusForbidden` (403).

[this code]: https://github.com/hashicorp/vault/blob/c1151dd3c3187f6cf5014fd358ce1d9158081989/http/handler.go#L182-L183

**Comment by mlafeldt** [comment]
On the other hand, maybe it's a bug in the code, which should actually return `http.StatusUnauthorized`. :)

I can't tell.

**Comment by jefferai** [comment]
I'm not sure why 401/403 was originally chosen, but I've changed the docs to use 403. Thanks for the report!
