### ISSUE TITLE
GCP Auth Documentation Issue

### ISSUE THREAD

**Issue by sidewinder12s** [hashicorp/vault#8328]
**Describe the bug**
GCP Auth Doc issue

It appears that the GCP Auth Method required permissions are wrong (the specific list of permissions).

https://www.vaultproject.io/docs/auth/gcp/#required-gcp-permissions

```
iam.serviceAccounts.get
iam.serviceAccountKeys.get
compute.instances.get
compute.instanceGroups.list
compute.instanceGroups.listInstances
```

`compute.instanceGroups.listInstances` is not a valid permission in GCP. 

```
Error: Error creating the custom project role projects/PROJECT/roles/vault.gcp.auth: googleapi: Error 400: Permission compute.instanceGroups.listInstances is not valid., badRequest
```

It appears that just removing this permission still works.

**Comment by kalafut** [comment]
@emilymye Can you confirm the recommended permission set?

**Comment by emilymye** [comment]
Sounds fine to me!

**Comment by kalafut** [comment]
Thanks!
