### ISSUE TITLE
Policy with num_uses not applicable for command-line use

### ISSUE THREAD

**Issue by soner89** [hashicorp/vault#8331]
**Describe the bug**
When writing a Vault Policy with the "allowed_parameter" option including the "num_uses" parameter, it is not possible to create a token via the command line at all. The error message is always "Permission denied". This is most probably due to an internal cast error in Vault.

**To Reproduce**
1. Log in to Vault with the root token: `vault login`
2. Save the following contents to a file on your local filesystem called "createtoken.hcl"
```
path "sys/auth" {
  capabilities = [ "read" ]
}

path "sys/auth/token/tune" {
  capabilities = [ "read", "sudo" ]
}

path "auth/token/*" {
  capabilities = [ "create", "read", "update", "delete", "list", "sudo" ]
  allowed_parameters = {
    "ttl" = ["2m0s"]
    "*" = []
    "policies" = [["createtoken"]]
    "num_uses" = ["1"]
  }
  
}

```
3. Run `vault policy write createtoken createtoken.hcl` 
4. Create a Token with this policy: `vault token create -policy=createtoken`
5. Copy the token and log in with it: `vault login`
4. Create a Token with this policy: `vault token create -policy=createtoken -ttl=120 -use-limit=1`
5. You will receive the following error:
```
Error creating token: Error making API request.

URL: POST http://127.0.0.1:8200/v1/auth/token/create
Code: 403. Errors:

* 1 error occurred:
        * permission denied
```

**Expected behavior**
The expected behaviour is that I can create a Token with the given parameters. These parameters as set in the policy previously. 

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.2
* Vault CLI Version (retrieve with `vault version`): `Vault v1.3.2 ('d433f38172a75f69ab0f40158936f9ac7c24f0ee+CHANGES')`
* Server Operating System/Architecture: Latest Docker Image on Dockerhub (https://hub.docker.com/_/vault)

Vault server configuration file(s):

```hcl
<empty>
```

**Additional context**
vault started with `docker run --cap-add=IPC_LOCK -p 127.0.0.1:8200:8200/tcp -e VAULT_DEV_ROOT_TOKEN_ID=secret -e VAULT_DEV_LISTEN_ADDRESS=
0.0.0.0:8200 -e VAULT_LOG_LEVEL=debug vault`

**Comment by briankassouf** [comment]
@soner89 allowed_parameters are known to be a little restrictive. But you can accomplish the same thing by using a [token role](https://www.vaultproject.io/api-docs/auth/token/#createupdate-token-role). Token roles can enforce all those rules via a single API call. Then you can add the role's API path to the `createtoken` policy:
```
path "auth/token/create/<put role name here>" {
  capabilities = [ "create" ]
}
```

**Comment by catsby** [comment]
Hello - in addition to what @briankassouf points out above, it should be pointed out that using the token that was created in step `#4` above to login in step `#5` above counts as a use of the token. If the token only has 1 use available, it's used in the login and can no longer be used after that. You can see this by increasing the number of uses on the token (ex. `2`), using it to login, then doing a token lookup and you'll find the number of remaining uses decremented.
