### ISSUE TITLE
Enable the new Security Tab in GitHub

### ISSUE THREAD

**Issue by KrisTC** [hashicorp/vault#8334]
As a security product. It seems very important that this product has security analysis done on it.
I know it is on to https://www.openhub.net/p/vaultproject but I noticed that GitHub now has similar functionality with "Insights" tab and the new "Security" tab: https://www.zdnet.com/article/github-launches-security-lab-to-help-secure-open-source-ecosystem/

Thanks

**Comment by catsby** [comment]
Hello! Thanks for writing in. The Vault codebase does go through regular audits by 3rd parties, however the results are only available to HashiCorp and its customers who have completed a non disclosure agreement. For what it's worth too, we do have the Security tab available on this repository. Cheers!
