### ISSUE TITLE
Missing "Request body" for KV v1 POST request in api-explorer

### ISSUE THREAD

**Issue by kulkarniamit** [hashicorp/vault#8337]
**Environment:**

* Vault Version: Vault v1.3.2
* Operating System/Architecture: Ubuntu 16.04/x64

**Expected Behavior:**
We should have a "Request Body" option in http://localhost:8200/ui/vault/api-explorer for creating new secrets in kv v1 POST requests

**Actual Behavior:**
Request: 
```
curl 'http://localhost:8200/v1/kv1/data' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: http://localhost:8200/ui/vault/api-explorer' -H 'X-Vault-Token: <token>' -H 'Origin: http://localhost:8200' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data ''
```
Response: `{"errors":["missing data fields"]}`

**Steps to Reproduce:**
* Enable new engine and select KV
* Provide a path (Example: `kv1`) and select version as `1`
* Navigate to `http://localhost:8200/ui/vault/api-explorer`
* Scroll down to `POST​ /kv1​/{path}` section
* There is an option to add `path` but no option to add `Request body`

**Comment by hellobontempo** [comment]
The request body is now present in the openAPI explorer!

![Image](https://github.com/hashicorp/vault/assets/68122737/0f22c9aa-9a56-4bbc-adf3-debdee3e9efd)
