### ISSUE TITLE
Vault Agent silently ignores malformed configuration files

### ISSUE THREAD

**Issue by BrandonHarrisonCode** [hashicorp/vault#8338]
**Describe the bug**
Vault Agent will silently ignore malformed or misconfigured agent configuration files.

**To Reproduce**
1. Set the agent configuration file to be a working configuration with some number of nonsense blocks:
```hcl
pid_file = "./pidfile"

vault {
        address = "https://127.0.0.1:8200"
}

listener "tcp" {
  address = "127.0.0.1:8100"
  tls_disable = true
}

garbage_block {
  this_is_ok = true
  foo = "bar"
}

cache {
}
```

2. Run `vault agent -config=agent.hcl`
3. The server starts successfully without any issues or even any logging indicating that the configuration is malformed.

**Expected behavior**
The agent should not start successfully with an error message indicating that there is a block that it does not recognize.  

This came up when attempting to use the vault agent templating feature in a version of vault before the feature was released: instead of producing an error vault happily silently ignores the `template` block leading to confusing debugging on why templating was not working.

**Environment:**
* Vault Server Version (retrieve with `vault status`): v1.3.2
* Vault CLI Version (retrieve with `vault version`): v1.3.2
* Server Operating System/Architecture: Darwin Kernel Version 19.2.0 running macOS Catalina 10.15.2

Vault server configuration file(s):
Run using the development server `vault server -dev`

** Additional Information **
Note that if there is a syntax error inside of the block (e.g. putting an illegal character like '?') then the agent will produce an error.  So Vault is evaluating the block but ignoring things that it does not recognize.

**Comment by tyrannosaurus-becks** [comment]
This is similar to https://github.com/hashicorp/vault/issues/3455 though not an exact dupe, as one is asking for a validation command and the other is asking for different start-up behavior.

**Comment by BrandonHarrisonCode** [comment]
@tyrannosaurus-becks From my understanding they are similar problems with different causes.  The vault-agent configuration loading logic is in https://github.com/hashicorp/vault/blob/master/command/agent/config/config.go while the vault configuration loading logic is in https://github.com/hashicorp/vault/blob/master/command/config/config.go. 

Looking through the code, it looks like the config looks for certain keys like "listener" or "auto-auth" and then ignores anything that doesn't match the expected keys.

Maybe it might be a good idea to check if there are any parsed objects left at the end and print a warning in the log for each of them?

**Comment by aphorise** [comment]
While I agree (like #3455) an operator that checks (eg: `vault conf validate`) config files would be nice - I'm not sure if there should be any exclusions for entries that may otherwise be outside the scope of any minimal scheme required for Vault itself. There's also the issue of that's a minimum given the vast number of CLI options (`vault sever ………`) that may be passed in-line instead of them being mandatory in any HCL scheme. So other considerations are for example running in dev mode vs not running in dev - should name resolutions also be performed as well? - what about resource checks on binds? - what about storage check? - etc.

In any event - it may be better to define some minimal config set's and checks that would be ideal if possible (perhaps doing so on #3455).

**Comment by aphorise** [comment]
I believe this request should be closed in favour of some minimums as per #3455.

What's more - as per my earlier notes I do not believe any exclusionary clause should be put in place especially plugins or release specific paramters may be applicable or left in place from some custom build or version.

@BrandonHarrisonCode do you agree?

**Comment by BrandonHarrisonCode** [comment]
@aphorise I agree. The referenced issue seems like it encompasses my use case, and a check then apply paradigm seems to be in line with similar tools.

**Comment by aphorise** [comment]
On the most recent versions of Vault (eg: 1.12.0) the default log levels actually give a `WARN` message regarding portions of the log that it doesn't understand. So I took your original conf (from the start) - and trying to start the Vault process then shows:

```bash
sudo /usr/local/bin/vault server -config=/etc/vault.d/vault2.hcl
  # A storage backend must be specified
  # … [WARN]  unknown or unsupported field vault found in configuration at /etc/vault.d/vault2.hcl:3:1
  # … [WARN]  unknown or unsupported field garbage_block found in configuration at /etc/vault.d/vault2.hcl:12:1
  # … [WARN]  unknown or unsupported field cache found in configuration at /etc/vault.d/vault2.hcl:17:1
  # … [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
```

So even at present this can be used as a form of soft sanitation checks against the conf to ensure no `WARN` occur before restarting services.

@BrandonHarrisonCode - close this issue if you feel it's ok and we can continue to add notes on the linked issue - WDYT?

I'll add the above observation to the other issue as well.

**Comment by BrandonHarrisonCode** [comment]
Perfect, that sounds like more recent versions of Vault directly address the issue I was originally facing. Thank you for all of the info!
