### ISSUE TITLE
Compiling from master is broken

### ISSUE THREAD

**Issue by rickdennis** [hashicorp/vault#8339]
**Describe the bug**
Building from the current master is broken for those of us without access to github.com/hashicorp/vault-plugin-secrets-mongodbatlas

This commit seems to be where it was added:
https://github.com/hashicorp/vault/commit/264c446de6979f1cb1b2d06ef7cdf2060753338e

When building it errors with:

```
build github.com/hashicorp/vault: cannot load github.com/hashicorp/vault-plugin-secrets-mongodbatlas: git ls-remote -q https://github.com/hashicorp/vault-plugin-secrets-mongodbatlas in /go/pkg/mod/cache/vcs/7339c23ca2344d78f0e1cef5
7b7b907caa1c33e41bf11ec23f96a4c4d19b4fc8: exit status 128:
        fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
make: *** [Makefile:40: dev] Error 1
root@fc50946e134b:/vault#
```

**To Reproduce**
1. Run `git clone https://github.com/hashicorp/vault.git`
2. Run `make bootstrap`
3. Run `make dev`

**Expected behavior**
Produce `bin/vault`.

**Workaround**
1. Run `git checkout 62be2a0` . (This is the commit before mongodbatlas was added)

**Comment by kalafut** [comment]
Hi @rickdennis. I thought both this and the DB repo got flipped to public but we apparently missed one. I've just changed the visibility, so please try again and let me know if it works now.

**Comment by briankassouf** [comment]
Closing since this should be fixed now that the repo is public. Let us know otherwise!
