### ISSUE TITLE
api client read does not return an error when the path doesn't exists

### ISSUE THREAD

**Issue by nicolas-martin** [hashicorp/vault#8361]
**Describe the bug**
When calling `client.Logical().Read("abc")` with an invalid path the error is nil as well as the return which causes null pointer exceptions if the returned value is used.

**Expected behavior**
An error is return saying that the path was invalid.

**Comment by jefferai** [comment]
We won't be changing this as it will break all other users relying on the current behavior. But the behavior as is isn't wrong, it's just a design choice; if the path is invalid, nothing is there -- hence nil. (Remember, it's an API client, not an HTTP client.)

**Comment by nicolas-martin** [comment]
It's a design choice, but isn't idiomatic go. [For example](https://golang.org/pkg/os/)

```
file, err := os.Open("file.go") // For read access.
if err != nil {
	log.Fatal(err)
}
```
returns `open file.go: no such file or directory`

To your point, success should not be defined as "did the api call run successfully?" but "is there a secret I can use at this location?" 

This change would also be backwards compatible as this would return nil AND an error, which current consumers both check at the moment.

**Comment by jefferai** [comment]
It may not be idiomatic Go, but changing it now would not be backwards compatible (you'd return an error where previously you did not), so such a change would need to wait for an API revision.

**Comment by nicolas-martin** [comment]
Perhaps I'm not understanding what you mean by "not be backwards compatible"? I'm not seeing a case where it would actually _break_ something.

- Ignoring error but checking the secret. `s, _ := client.Logical().Read("abc")`. Would result in the same flow as the secret is still nil.

- Checking both would handle the new error.

**Comment by jefferai** [comment]
Most people don't ignore the error. So instead of checking that the error is nil, then handling the case of the secret being nil, they will see a non nil error and take a different code path.
