### ISSUE TITLE
I have given CN="securityGroup from my DA"and bindnpass=null, the ldap auth keeps giving the error Error Authentication failed: ldap operation failed. It is funtioning properly only when I give CN="samaccountname"and Bindpassword ="myad password" Just authenticating one user is not really helpful

### ISSUE THREAD

**Issue by muthulakshmia** [hashicorp/vault#8363]
Please post questions on the discussion forum (https://discuss.hashicorp.com/c/vault) rather than in GitHub issues.

The discussion forum gets a _lot_ more eyes on any particular question. You'll get an answer faster, not slower, by taking advantage of the suggestions and answers provided by the wealth of experience that long-time users and devs bring to the forum.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!

**Comment by michelvocks** [comment]
Hi @muthulakshmia!

I'm a bit confused by this issue. Is this a question? It would be quite helpful if you could provide more context here.

Also, as you've mentioned, please use the discussion forum for questions.

Cheers,
Michel

**Comment by tyrannosaurus-becks** [comment]
Closing this because it doesn't appear actionable at this time. Thanks for opening the issue and please do feel free to reopen it if needed, with additional clarification. Thanks!
