### ISSUE TITLE
when `vault write`, `-field` option being ignore in certain position

### ISSUE THREAD

**Issue by ryuheechul** [hashicorp/vault#8366]
**Describe the bug**
basically this below doesn't work
```
vault write auth/approle/login \
  -field=token \
  -format=json \
  role_id=$(cat ${APPROLE_ROLE_ID_PATH}) \
  secret_id=$(cat ${APPROLE_SECRET_ID_PATH}) 
```
when this below works
```
vault write -field=token auth/approle/login \
  -format=json \
  role_id=$(cat ${APPROLE_ROLE_ID_PATH}) \
  secret_id=$(cat ${APPROLE_SECRET_ID_PATH}) 
```

Interestingly `-format` is respected even though it's placed in same position as `-field`

**To Reproduce**
1. Run 
```
vault write auth/approle/login \
  -field=token \
  -format=json \
  role_id=$(cat ${APPROLE_ROLE_ID_PATH}) \
  secret_id=$(cat ${APPROLE_SECRET_ID_PATH}) 
```
2. See output field is not respected, therefore showing all the output not just `token`

**Expected behavior**

output just being `token`

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.0
* Vault CLI Version (retrieve with `vault version`): 1.3.2
* Server Operating System/Architecture: _not sure at the moment_

Vault server configuration file(s):
_I have no access to the server at the moment_

**Additional context**
I don't think it's related to server and it's just CLI's issue.

**Comment by spangenberg** [comment]
Hi @ryuheechul ,

This doesn't seem like a miss behavior, the documentation states that the options have to be specified before the path:
`vault write [options] PATH [DATA K=V...]`

`vault write PATH -field=token -format=json ...` format=table field=

**Comment by spangenberg** [comment]
Hi @ryuheechul ,

This issue doesn't seem like a miss behavior.
The documentation states that the options have to be specified before the path:
```bash
vault write [options] PATH [DATA K=V...]
```

I tested this with those different options:
`vault write PATH -field=token -format=json ...`results in `format=table` `field=`
`vault write -field=token PATH -format=json ...` results in `format=table` `field=token`
`vault write -field=token -format=json PATH ...` results in `format=json` `field=token`

I hope this solved your issue. I'll close it, but feel free to comment on it in case you think there is more to it.
