### ISSUE TITLE
Unable to establish TLS Connection with self signed certificate

### ISSUE THREAD

**Issue by lagging** [hashicorp/vault#837]
I have used self signed certificate using openssl and installed ca certificate .
## config.hcl

backend "mysql" {
  username= "root"
  password= "root"
  address = "127.0.0.1:3306"
}
listener "tcp" {
  address = "www.example.com"
  tls_cert_file = "/home/ashish/Documents/ssl/server-cert.pem"
  tls_key_file= "/home/ashish/Documents/ssl/server-key.pem"
}
disable_mlock=true
## used this link to generate certificate

https://jamielinux.com/docs/openssl-certificate-authority/create-the-root-pair.html

I have also mapped my www.example.com in /etc/hosts file of ubuntu
127.0.0.1:8200  www.example.com

**Comment by jefferai** [comment]
What is the problem you are seeing? Connecting to Vault from a client? Or some issue with the Vault server?

If the issue is connecting to Vault from a client, you'll need to either have your CA certificate available to your client, or you'll need to disable checking. The Vault CLI offers the `-tls-skip-verify` parameter for all commands (or via the `VAULT_SKIP_VERIFY` env var; if you are using e.g. `curl` you can use the `--insecure` flag.

**Comment by lagging** [comment]
I am unable to authenticate my client after enable cert backend.
I have made my client cert using this:

shell> openssl req -newkey rsa:2048 -days 3600 \
         -nodes -keyout client-key.pem -out client-req.pem
shell> openssl rsa -in client-key.pem -out client-key.pem
shell> openssl x509 -req -in client-req.pem -days 3600 \
         -CA ca.pem -CAkey ca-key.pem -set_serial 01 -out client-cert.pem

and yes i have installed ca certificate client side.

for creating user:
$ vault write auth/cert/certs/web \
    display_name=web \
    policies=prod \
    certificate=@client-cert.pem \
    ttl=1h


for authenticating user:
$ curl --cacert ca.pem --cert client-cert.pem --key client-key.pem \
    $VAULT_ADDR/v1/auth/cert/login -XPOST

**Comment by jefferai** [comment]
What is the value of $VAULT_ADDR?

**Comment by lagging** [comment]
www.example.com

**Comment by lagging** [comment]
https://groups.google.com/forum/#!searchin/vault-tool/cert/vault-tool/DPLA6y4kh0U/CJ9qKaPiMQUJ

I used this and was able to successfully run it.

**Comment by lagging** [comment]
Now I am trying to authenticate my client using java but it is throwing 400 error.
my keystore: contains servert.crt
my truststore: contains client.crt and client.key

public class Test {
    public static void main(String[] args) {
        String keyStorePath = "/home/ashish/Documents/prodssl/auth/client.p12";
        String keyStorePass = "whatever";
        String trustStorePath = "/home/ashish/Documents/prodssl/auth/client-truststore.jks";
        String trustStorePass = "whatever";
        String postData = "<request></request>";
        String url = "https://www.example.com:8200/v1/auth/cert/login";

        SSLContext sslContext = GetSSLContext(keyStorePath, keyStorePass, trustStorePath, trustStorePass);
        PostData1(postData, url, sslContext);

       
    }

    public static void PostData1(String dataToPost, String serviceUrl, SSLContext sslContext) {
        try {
            URL url = new URL(serviceUrl);

            HttpsURLConnection.setDefaultSSLSocketFactory(sslContext.getSocketFactory());
            HttpsURLConnection urlConn = (HttpsURLConnection)url.openConnection();
            urlConn.setDoOutput(true);
            urlConn.setDoInput(true);
            urlConn.setUseCaches(false);
            urlConn.setRequestMethod("POST");
            urlConn.setRequestProperty("Content-Type", "application/xml");
            urlConn.connect();

            PrintWriter out = new PrintWriter(urlConn.getOutputStream());
            out.println(dataToPost);
            out.close();

            System.out.println("Response Code 1: " + urlConn.getResponseCode());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    

    public static SSLContext GetSSLContext(String clientStorePath, String clientStorePass, String trustStorePath, String trustStorePass) {
        SSLContext sslContext = null;

        try {
            KeyStore clientStore = KeyStore.getInstance("PKCS12");
            clientStore.load(new FileInputStream(clientStorePath), clientStorePass.toCharArray());

            KeyManagerFactory kmf =KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
            kmf.init(clientStore, clientStorePass.toCharArray());
            KeyManager[] kms = kmf.getKeyManagers();

            KeyStore trustStore = KeyStore.getInstance("JKS");
            trustStore.load(new FileInputStream(trustStorePath), trustStorePass.toCharArray());

            TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            tmf.init(trustStore);
            TrustManager[] tms = tmf.getTrustManagers();

            sslContext = SSLContext.getInstance("TLS");
            sslContext.init(kms, tms, new SecureRandom());

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        return sslContext;
    }

    
}

**Comment by jefferai** [comment]
@lagging Unfortunately I really don't know the Java crypto API so I don't really know what might be going wrong.

**Comment by mycraftmw** [comment]
Hey bro, I went into the same problem when I ran vault in development mode with `vault server -dev` and tried to login with self signed certificate. However, vault throw out an error like this:

`URL: PUT http://127.0.0.1:8200/v1/auth/cert/login`
`Code: 400. Errors:`

`* tls connection required`

I list all the command I used below for reproducing this problem:
1. generate the self signed certificate
`openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365`
`openssl rsa -in key.pem -out key.ins.pem`

2. start the vault server in development mode, setup the env and auth-enable certificate
`vault server -dev`
`export VAULT_ADDR=http://127.0.0.1:8200`
`vault auth-enable cert`

3. then write these information into the vault
`vault write auth/cert/certs/web display_name=web policies=root certificate=@cert.pem ttl=3600`


Up TO NOW, all these commands go very well, then I try to use the commands below
`vault auth -method=cert -client-cert=cert.pem -client-key=key.ins.pem`
or
`vault auth -method=cert -tls-skip-verify -client-cert=cert.pem -client-key=key.ins.pem`
However, both of them return the error message as I describe in the very beginning

I'll appreciate it a lot if there is someone can help me!

**Comment by jefferai** [comment]
Dev servers don't run with TLS listeners, therefore you are not connecting with TLS, therefore you cannot authenticate with TLS certificates. You'll need to use a real server.

**Comment by mycraftmw** [comment]
Thank you for your suggestion!
Since I don't have a real server, I cannot really set up a https server. Is there any way for me to test using certificate to auth?

**Comment by jefferai** [comment]
There isn't a way to test it without using https, but you can use any valid https certificates...you can even generate certificates with Vault's PKI backend using a dev instance, then use those certificates for Vault itself.

**Comment by mycraftmw** [comment]
Great! I think it can help a lot. Thank you!

**Comment by sirkubax** [comment]
EXTFILE for IP SANS !!!! when signing CSR to CRT
https://www.golinuxcloud.com/openssl-create-client-server-certificate/
openssl x509 -req -in server.csr -CA selfca.crt -CAkey selfca.key -CAcreateserial --extensions v3_req -extfile server.req -out server.crt
