### ISSUE TITLE
Prometheus metrics docs and guidelines

### ISSUE THREAD

**Issue by riuvshyn** [hashicorp/vault#8382]
Hello! I have a couple of questions:
1) where I can read actual prometheus metrics documentation?
I've tried to go through https://www.vaultproject.io/docs/internals/telemetry/ but this looks outdated and does not cover lots of exposed in prom format metrics so it is absolutely not clear how to use the metric...
ex: I have k8s auth plugin enabled so I have metrics:
```
vault_route_rollback_auth_kubernetes__sum 0.5904119880869985
vault_route_rollback_auth_kubernetes__count 28
``` 
but there is no anything related to this in docs nor plugin repo https://github.com/hashicorp/vault-plugin-auth-kubernetes

and there are many such examples so it feels quite inconsistent.

another ex: https://www.vaultproject.io/docs/internals/telemetry/#secrets-engines-metrics covers only Databases but how do I monitor transit backend? what metrics it exposes?

can this doc also cover what is the `rollback` and `route rollback` operations?

2) is there any guidelines on monitoring/alerting?  WOuld be nice to see what should be in focus.

**Comment by catsby** [comment]
Hello! There is some additional documentation about using Prometheus here, albeit not much:

- https://www.vaultproject.io/docs/configuration/telemetry/

It does seem like our documentation on metrics needs some updating :/

**Comment by omerlh** [comment]
I'm struggling with this also. Spent around half an hour digging around the code and trying to find where the metrics are defined - so far couldn't find anything. My main concern is to find out what I should monitor. I can see a lot of metrics like `vault_gcs_put`, but I can't figure which one are important - and how I can monitor errors. Can someone help clearing it out?

**Comment by aphorise** [comment]
There's also a recent learn guide that provides a little bit more detail and example of extrapolating insights from [Audit & Telemetry in Splunk](https://learn.hashicorp.com/tutorials/vault/monitor-telemetry-audit-splunk).

**Comment by aphorise** [comment]
@riuvshyn - have you reviewed available documentation since opening your request and is still relevant for you?

**Comment by aphorise** [comment]
Closing as there's been no follow-up. Please re-open if I've misunderstood or still relevant.
