### ISSUE TITLE
Root CA not included in client cert ca_chain

### ISSUE THREAD

**Issue by jpds** [hashicorp/vault#8407]
**Describe the bug**

Using a root CA and intermediate CA (both in Vault), the resulting client certificate does not have the root CA in it's ca_chain output.

**To Reproduce**:

Using the steps described in: https://learn.hashicorp.com/vault/secrets-management/sm-pki-engine

```
vault secrets enable pki
vault secrets tune -max-lease-ttl=87600h pki
vault write -field=certificate pki/root/generate/internal \
        common_name="Test CA" \
	key_bits=4096 \
        ttl=87600h > ca.cert
vault write pki/config/urls \
        issuing_certificates="http://127.0.0.1:8200/v1/pki/ca" \
        crl_distribution_points="http://127.0.0.1:8200/v1/pki/crl"
vault secrets enable -path=pki_int pki
vault secrets tune -max-lease-ttl=87600h pki_int
vault write -format=json pki_int/intermediate/generate/internal \
        common_name="Test Intermediate Authority" \
	key_bits=4096 \
        | jq -r '.data.csr' > pki_intermediate.csr
vault write -format=json pki/root/sign-intermediate csr=@pki_intermediate.csr \
        format=pem_bundle ttl="87600h" \
        | jq -r '.data.certificate' > intermediate.cert.pem
vault write pki_int/intermediate/set-signed certificate=@intermediate.cert.pem
```

Now generate a client under the intermediate cert:

```
vault write pki_int/roles/test \
        allowed_domains="test" \
	allow_localhost=false \
        allow_subdomains=false \
	allow_bare_domains=true \
	allow_ip_sans=false \
	basic_constraints_valid_for_non_ca=true \
	client_flag=false \
	enforce_hostnames=false \
	key_type=rsa \
	key_bits=4096 \
	key_usage="DigitalSignature" \
	server_flag=false \
        ttl="43800h"

vault write pki_int/issue/test \
	common_name="test" \
	exclude_cn_from_sans=true \
	ttl="43800h"
```

Observe that `ca_chain` only has the intermediate CA.

**Expected behavior**

I would expect both the root and intermediate CAs to be in ca_chain.

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault v1.3.0
* Vault CLI Version (retrieve with `vault version`): Vault v1.3.0

**Comment by catsby** [comment]
Hello -

The root certificate is not included in the chain, because those are assumed to be trusted by the OS or browser in use.

> The issuing CA certificate and CA trust chain are returned as well. The CA Chain returns all the intermediate authorities in the trust chain. The root authority is not included since that will usually be trusted by the underlying OS.

- https://www.vaultproject.io/docs/secrets/pki/#issue-certificates-1

I'm going to close this for now as I don't believe it represents a bug in Vault. Please let us know if you feel otherwise and we can reconsider, but for now this behavior is documented and intentional. 

Thanks!
