### ISSUE TITLE
AWS secrets engine: handle eventual consistent nature of generated creds

### ISSUE THREAD

**Issue by klebediev** [hashicorp/vault#8413]
As stated [here](https://github.com/hashicorp/vault/blame/master/website/pages/docs/secrets/aws/index.mdx#L147-L150):
>     Unfortunately, IAM credentials are eventually consistent with respect to other Amazon services. If you are planning on using these credential in a pipeline, you may need to add a delay of 5-10 seconds (or more) after fetching credentials before they can be used successfully.

Question: Adding "5-10 seconds" doesn't seem to be a production-ready approach. Is it possible to add some wait loop after creds are generated which checks that creds are able to work and only after this respond to client?

**Comment by kalafut** [comment]
Hi. The challenge is that the availability of the credentials is dependent on a lot of factors (region, az, service, etc.) and any validity check to one test endpoint might fail for the next until propagation has settled.

**Comment by klebediev** [comment]
Thank you for quick reply @kalafut 
Just confirmed with AWS support there is not good universal method to check that IAM stuff has propagated to a region.
