### ISSUE TITLE
Small documentation addendum request

### ISSUE THREAD

**Issue by kieferrj** [hashicorp/vault#8415]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An addendum to this documentation: https://www.vaultproject.io/docs/vs/kms/ that includes comparison to AWS Secrets Manager (https://aws.amazon.com/secrets-manager/) on top of the already included KMS segment.

**Comment by jefferai** [comment]
We have decided to remove that section, see https://github.com/hashicorp/vault/pull/8538
