### ISSUE TITLE
Support passing unseal tokens over a file / stdin.

### ISSUE THREAD

**Issue by grahamc** [hashicorp/vault#8416]
**Is your feature request related to a problem? Please describe.**

`vault operator unseal` strongly and rightly recommends using it at a tty, however in some cases like where another tool is automatically performing the unseal, the interface is lacking.

The alternative to typing it at a TTY is passing it as an argument. This is insecure because the argument will show up in process listings and likely history. 

**Describe the solution you'd like**

I would like to be able to specify a file Vault can read the unseal token from, where that file could be `stdin` by default. This would let me pass in a UNIX file handle, which would let me securely provide the token without typing it in by hand.

**Comment by grahamc** [comment]
Note, one gnarly way to do this is sticking this in `pass`:

```tcl
set address "http://127.0.0.1:8200"

proc unseal {token} {
  global address
  spawn vault operator unseal -address "$address"
  expect "Unseal Key"
  send -- "$token\r\n"
  interact
}


spawn vault operator -reset -address "$address"
interact

unseal "key1"
unseal "key2"
unseal "key3"
```

and then: `expect <(pass vault-unlock.expect)`

**Comment by calvn** [comment]
Another alternative would be to use `xargs` and pipe the output of the file into it like so:

```
› cat /my-unseal-key | xargs vault operator unseal
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.3.0
Cluster Name    vault-cluster-583ddb4e
Cluster ID      760b85e8-fe71-1b00-4190-4d03c1f5fb19
HA Enabled      false
```

**Comment by drawks** [comment]
It is worth noting that vault is merely calling an underlying http/s api for doing this operation. If you want automate unsealing it is perhaps not unreasonable to call the API directly. If the vault CLI exposes every possible way to interact with the underlying API it'll be a bad case of second system syndrome.

The example in the API documentation should be a pretty demonstration of how simple this is to do. https://www.vaultproject.io/api-docs/system/unseal/

just my .02 YMMV

**Comment by catsby** [comment]
Hello - thank you all for the discussion here. I think with the suggestions from @calvn and @drawks , there should be a path forward without modification to Vault at this time. I'm going to close this issue for now. If you have further questions about unsealing in this fashion, I recommend visiting our discussion site: https://discuss.hashicorp.com/c/vault/30

**Comment by grahamc** [comment]
Sure, that seems fine. Note, however, that the `xargs` example still puts the arguments in to the process table and should not be considered a safe way to enter the token.

**Comment by catsby** [comment]
That's an excellent point @grahamc , thank you; the above suggestions should work but are not considered to be safe or recommended. Users should understand and evaluate the risk(s), so thank you for the reminder 😄

**Comment by dhbaird** [comment]
Building on @drawks comment, here's how to do it with the API. This is a pretty good solution as it doesn't risk exposing the tokens in command lines, process tables, environment variables, which often candidates for logging/monitoring. Note that this works because "echo" is a shell builtin, i.e. not a program, and therefore echo will not appear in the process table:

    cat /datavol/.key | curl -X PUT -d @<(echo "{\"key\":\"$(cat /dev/stdin)\"}") $VAULT_ADDR/v1/sys/unseal

If jq is available, it comes out more elegantly, since there is no need to worry about quoting rules:

    cat /datavol/.key | curl -X PUT -d @<(jq -nrR 'inputs|{key:.}|@json') $VAULT_ADDR/v1/sys/unseal

Please don't do the xargs solution, as elegant as it may seem, because of reason in @grahamc's comment above, and is a known security bad practice.

**Comment by dhbaird** [comment]
One more catch: if you have logging turned on in the shell (e.g. `set -x` in bash), then that should be turned off with `set +x` for the "echo" as it will end up in the shell logs, i.e. this would work:

    cat /my-unseal-key | curl -X PUT -d @<(set +x; echo "{\"key\":\"$(cat)\"}") $VAULT_ADDR/v1/sys/unseal

**Comment by Xavantex** [comment]
> Building on @drawks comment, here's how to do it with the API. This is a pretty good solution as it doesn't risk exposing the tokens in command lines, process tables, environment variables, which are often candidates for logging/monitoring. Note that this works because "echo" is a shell builtin, i.e. not a program, and therefore echo will not appear in the process table:
> 
> ```
> cat /my-unseal-key | curl -X PUT -d @<(echo "{\"key\":\"$(cat /dev/stdin)\"}") $VAULT_ADDR/v1/sys/unseal
> ```
> 
> If jq is available, it works out more elegantly, since there is no need to worry about quoting rules:
> 
> ```
> cat /my-unseal-key | curl -X PUT -d @<(jq -nrR 'inputs|{key:.}|@json') $VAULT_ADDR/v1/sys/unseal
> ```
> 
> EDIT: revised path to match previous example

Why would you need to pipe it, would `curl -X PUT -d @<(echo "{\"key\":\"$(cat /my-unseal-key)\"}") $VAULT_ADDR/v1/sys/unseal` not be exactly the same?
