### ISSUE TITLE
Vault agent sidecar should be able to handle different location than /vault/secrets

### ISSUE THREAD

**Issue by JnMik** [hashicorp/vault#8421]
Hello guys ! 

**Is your feature request related to a problem? Please describe.**
When using the vault agent sidecar to inject secrets file into a container, it's always trouble because I can't specify my own location, i'm stuck with the default /vault/secrets.

**Describe the solution you'd like**
I would like to be able to tell the vault-agent-sidecar where to drop the file.
I would expect an annotation looking like this.
"vault.hashicorp.com/agent-inject-secret-filepath" = "/filepath/where/I/want/the/file/"

**Describe alternatives you've considered**

Considering it's for java app with springboot...

- Overriding environment variable SPRING_CONFIG_LOCATION to add another location, but I could be de-sync with the project paths if a developer updates the value in their yaml file and forget to update environment variable.

- Force the container to boot on a custom bootstrap.sh script, where I would copy the file to the right location before starting the java app. Not very elegant.

- Suggest developers that I will add _file:/vault/secrets_ path in their spring config location setting (it's what I choose as my workaround for now). But it feels cheap to alter their app core settings to provide secrets.

What do you think ? 
Cheers

**Comment by catsby** [comment]
Hey @JnMik - Vault Agent Injector has it's own GitHub project over at https://github.com/hashicorp/vault-k8s. If you'd like, I _believe_ I can transfer this issue over there, or you could remake it. Either way, I believe it's better served over there. Let me know what you think!

**Comment by JnMik** [comment]
Ok :)
done https://github.com/hashicorp/vault-k8s/issues/92

**Comment by catsby** [comment]
@JnMik Thanks! I clicked through and found that apparently it's a feature already merged, so yay!
