### ISSUE TITLE
unseal with wrong key returns HTTP 500 instead of 400

### ISSUE THREAD

**Issue by thomasmitchell** [hashicorp/vault#8425]
**Describe the bug**
When unsealing, if a wrong key was provided, Vault used to return 400 Bad Request from the HTTP API. Since version 1.3.0, it has returned 500 Internal Server Error.

The same error also occurs now when attempting a rekey, but providing the incorrect current key.

**To Reproduce**
1. Start a dev Vault
2. Initialize the Vault with 1 threshold/shares.
3. Attempt to unseal with the wrong key

**Expected behavior**
Expected a 400 Bad Request status code.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.0, 1.3.1, and 1.3.2
* Vault CLI Version (retrieve with `vault version`): n/a
* Server Operating System/Architecture: darwin/amd64

Vault server configuration file(s):

```hcl
backend "inmem" {}

disable_mlock = true

listener "tcp" {
  address = "127.0.0.1:8204"
  tls_cert_file = "/var/folders/k5/0b3rp3sd2xx17p2rls0cvjz40000gn/T/vaultkv-test-cert921136346"
  tls_key_file = "/var/folders/k5/0b3rp3sd2xx17p2rls0cvjz40000gn/T/vaultkv-test-key705165425"
}
```

**Additional context**
Here is a request/response dump from a very temporary dev Vault.

```
Request:
GET /v1/sys/health?standbyok=true HTTP/1.1
Host: 127.0.0.1:8204


Response:
HTTP/1.1 501 Not Implemented
Content-Length: 199
Cache-Control: no-store
Content-Type: application/json
Date: Wed, 26 Feb 2020 18:58:59 GMT

{"initialized":false,"sealed":true,"standby":true,"performance_standby":false,"replication_performance_mode":"unknown","replication_dr_mode":"unknown","server_time_utc":1582743539,"version":"1.3.0"}

Request:
PUT /v1/sys/init HTTP/1.1
Host: 127.0.0.1:8204

{"secret_shares":1,"secret_threshold":1,"root_token_pgp_key":"","pgp_keys":null}

Response:
HTTP/1.1 200 OK
Content-Length: 183
Cache-Control: no-store
Content-Type: application/json
Date: Wed, 26 Feb 2020 18:58:59 GMT

{"keys":["1da9ebe6fb67381a941e4618d64db5783c16ffddeb55abc3814059d78b2f4693"],"keys_base64":["Hanr5vtnOBqUHkYY1k21eDwW/93rVavDgUBZ14svRpM="],"root_token":"s.exbId61nhxrPGu0kPi8dZW0m"}

Request:
PUT /v1/sys/unseal HTTP/1.1
Host: 127.0.0.1:8204

{"key":"ada9ebe6fb67381a941e4618d64db5783c16ffddeb55abc3814059d78b2f4693"}

Response:
HTTP/1.1 500 Internal Server Error
Content-Length: 94
Cache-Control: no-store
Content-Type: application/json
Date: Wed, 26 Feb 2020 18:58:59 GMT

{"errors":["failed to decrypt encrypted stored keys: cipher: message authentication failed"]}
```

**Comment by aphorise** [comment]
Closing as the issue has since been resolved and in recent 1.11.x version it returns a valid HTTP-4xx response.

Hey @thomasmitchell thank you for reporting this when you did.
