### ISSUE TITLE
Policies and Authorization pages in Getting Started reference wrong order

### ISSUE THREAD

**Issue by cainejette** [hashicorp/vault#8436]
**Describe the bug**
The Getting Started workflow online walks through a number of aspects of Vault. After the [Help](https://github.com/hashicorp/vault/blob/245214bdd45e656eeb727d45952739221b10a18e/website/pages/intro/getting-started/help.mdx) section, it moves into [Policies](https://github.com/hashicorp/vault/blob/245214bdd45e656eeb727d45952739221b10a18e/website/pages/intro/getting-started/policies.mdx) and then [Authentication](https://github.com/hashicorp/vault/blob/master/website/pages/intro/getting-started/authentication.mdx).

The text of both the Policies and Authentication sections makes it clear that the order of these is wrong:

The Policies section says ["In the last section, we learned about authentication."](https://github.com/hashicorp/vault/blame/master/website/pages/intro/getting-started/policies.mdx#L10-L11) (when instead we really learned about the built in help tooling).

The Authentication section says ["On the next page, we talk about authorization."](https://github.com/hashicorp/vault/blame/master/website/pages/intro/getting-started/authentication.mdx#L18-L19) (when instead we really learn deploying Vault).

**Comment by cainejette** [comment]
Further, the policies section talks about tokens (which are introduced in the authentication section), without any language to the effect of "we'll talk about these later", which makes me think more and more that the pages are simply in the wrong order, not that the text on them needs to be updated.

**Comment by cainejette** [comment]
What's confusing to me is it looks like the Help file [actually does point to Authentication next](https://github.com/hashicorp/vault/blame/master/website/pages/intro/getting-started/help.mdx#L117-L118) but that is not what I see online. Has the latest version of this code been deployed?

**Comment by yhyakuna** [comment]
Hi @cainejette 

Thank you for bringing this to my attention.  It's [fixed](https://learn.hashicorp.com/vault?track=getting-started#getting-started) now. 

Thank you!
