### ISSUE TITLE
allowed_serial_numbers not documented

### ISSUE THREAD

**Issue by jpds** [hashicorp/vault#8443]
**Describe the bug**

I'm trying to issue a certificate with no common name (`require_cn: false`), but has the serial number in its Subject.

The option `allowed_serial_numbers` [here](https://github.com/hashicorp/vault/blob/1a451c67527911a3dedb1c74a5232b893945ba34/builtin/logical/pki/path_roles.go#L151) is not documented [here](https://www.vaultproject.io/api/secret/pki/index.html#createupdate-role).

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.2
* Vault CLI Version (retrieve with `vault version`): 1.3.2

**Comment by kitography** [comment]
Thanks for pointing this out!

allowed_serial_numbers documentation was here:  https://github.com/hashicorp/vault/commit/9a4ac84fcd9bc9d6a7676d70ccfa8852cf907c6a

If that doesn't solve your issue, feel free to reopen this.
