### ISSUE TITLE
The rekey API presents a data-loss hazard

### ISSUE THREAD

**Issue by hashbrowncipher** [hashicorp/vault#845]
When a rekey operation is completed, the new keys are returned as an API response to whoever submitted the last update.  If, for whatever reason, the node submitting the last update fails to durably store the new keys, it will become impossible to unseal Vault.

Suggested solution: when pgp_keys is provided, durably store the new unseal keys, as encrypted.  Provide an API for retrieving new key shares.  Key recipients should acknowledge receipt of their key through another API call, in which they provide their unseal key.

**Comment by jefferai** [comment]
This has been implemented for 0.5
