### ISSUE TITLE
Potential difficulty in data reconciliation at least while running in dev mode

### ISSUE THREAD

**Issue by avineshwar** [hashicorp/vault#8461]
**Describe the bug**
- A manual revocation of a generated (AWS IAM; not STS, etc) spits out an insufficiently clear message

**To Reproduce**
1. `vault read aws/creds/some-ec2-reads`
2. `vault lease revoke aws/creds/some-ec2-reads/toZdCnMUaPGF4tn1PcW3Mm32`
3. Check the **stdout** of the server

**Expected behavior**
**Some indication that this is a manual operation and not system-driven**

**Environment:**
`Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.3.2
Cluster Name    vault-cluster-6db9acc9
Cluster ID      9abf13a6-5222-4b22-72f7-dc33ba49bc27
HA Enabled      false`
* Server Operating System/Architecture:* Darwin

Vault server configuration file(s):
- _Running in dev mode_

**Additional context**
Output:
`2020-03-03T14:06:56.083-0800 [INFO]  expiration: revoked lease: lease_id=aws/creds/some-ec2-reads/toZdCnMUaPGF4tn1PcW3Mm32`

**Comment by catsby** [comment]
Hello -

Generally speaking, the server log will output events taken regardless of the source. If users want a log of actions specifically generated externally (by users, or really any API call), Vault provides support for audit devices:

>Audit devices are the components in Vault that keep a detailed log of all requests and response to Vault. Because every operation with Vault is an API request/response, the audit log contains every authenticated interaction with Vault, including errors.

- https://www.vaultproject.io/docs/audit/

The audit log will keep a record of all manual operations. Using your example, the audit log would record request and response entries for both step 1 above (reading the credentials) and step 2 (revoking the credentials). 

I'm going to close this issue for now and I don't believe it represents an issue with Vault, and we already provide the functionality described. Thanks!
