### ISSUE TITLE
Unable to have client authentication on vault using java showing 400 error

### ISSUE THREAD

**Issue by lagging** [hashicorp/vault#848]
I am trying to authenticate my client using java keystore and trustore. From CLI i am able to authenticate but from java it is throwing 400 error. I have used self signed certificate 

[Test (copy).txt](https://github.com/hashicorp/vault/files/60946/Test.copy.txt)

**Comment by jefferai** [comment]
What is the exact error you're seeing? Do you have any information in Vault's log?
