### ISSUE TITLE
vault not getting unsealed

### ISSUE THREAD

**Issue by mkaja** [hashicorp/vault#8498]
vault version = Version: Vault v0.6.4

# env | grep -i vault
VAULT_ADDR=http://ip:8200

# vault status
Error checking seal status: Error making API request.

URL: GET http://ip:8200/v1/sys/seal-status
Code: 500. Errors:

* failed to check seal configuration: AccessDenied: Access Denied
       	status code: 403, request id: 6CCBC42C83E7F7BD

# vault unseal
Error checking seal status: Error making API request.

URL: GET http://ip:8200/v1/sys/seal-status
Code: 500. Errors:

* failed to check seal configuration: AccessDenied: Access Denied
       	status code: 403, request id: 7628B777ECFF1292

--------logfile ---------------------

Vault server configuration:

                 Backend: s3
                     Cgo: disabled
              Listener 1: tcp (addr: "ip:8200", cluster address: "", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
                 Version: Vault v0.6.4
             Version Sha: f4adc7fa960ed8e828f94bc6785bcdbae8d1b263

==> Vault server started! Log data will stream in below:

**Comment by catsby** [comment]
Hello - the error message suggests an authentication / authorization issue, are you using a token that is known to be valid? What commands are being used to check the seal status? Any other additional information about the setup of Vault and how this error is being triggered would be helpful, but please be sure to remove any sensitive information

**Comment by catsby** [comment]
Hello -

Following up here. We haven't heard back and Vault v0.6.4 is over 3 years old, I'm going to close this issue for now. Please try upgrading to a newer version of Vault, and if you continue to experience this issue, please open a new issue with more information to reproduce the problem. 

Thanks!
