### ISSUE TITLE
Enhancement: Inactive standby mode for nodes removed from Raft cluster

### ISSUE THREAD

**Issue by vishalnayak** [hashicorp/vault#8529]
When `remove-peer` is invoked on a node that is in the raft cluster, it gets out of the raft cluster properly and gets into standby mode. But this standby mode should behave differently than the regular standby mode, wherein it shouldn't be able to handle requests and forward requests.

**Comment by aphorise** [comment]
There's stabilisation logic and other enhancements that have been added as per the documentations detailing some of this behaviour:

 - https://www.vaultproject.io/docs/concepts/integrated-storage/autopilot
 - https://www.vaultproject.io/docs/concepts/integrated-storage
 - https://www.vaultproject.io/docs/internals/integrated-storage

Closing as no updates or follow-up have been provided after inception and issue was already resolved near to the time.
