### ISSUE TITLE
OpenId Connect: Error “missing client token” when calling “/v1/auth/jwt/oidc/auth_url”

### ISSUE THREAD

**Issue by michael-engler** [hashicorp/vault#8531]
### Brief and concise problem description 

When trying to get the **auth_url** via the HTTP API, I receive an error "**missing client token**", which is unexpected, since I call this URL in order to authenticate and therefore do not have any client token yet. 

### Verbose problem description 
I have configured my local test Vault with an OIDC provider and can successfully authenticate with the vault CLI against my test Vault. So far so good. Now I need to write a command-line utility which fetches a secret from that Vault, still with OIDC authentication … and without using the vault CLI. My thoughts were:

1. Get the auth_url from Vault
2. Display the link to the user and asking him/her to:
    2a. open a browser
    2b. authenticate at the OIDC provider
    2c. paste the AuthCode to my command-line utility
3. Then my command-line utility can send this to the OIDC Callback URL
    /auth/jwt/oidc/callback at Vault and receive the token

I know I could use the vault CLI as well… no need to mention this :). Also I will try to offer an HTTP endpoint in the command-line utility where the redirect with the code can be sent to. But this is not the problem here now. 

So I send a request to my test vault like the following:
```
curl --location --request POST 'https://localhost:8200/v1/auth/oidc/auth_url' \
--header 'Content-Type: application/json' \
--data-raw '{
    "role": "managelmprole",
    "redirect_uri": "http://localhost:8888/oidc/callback"
}'
```
But sadly, instead of the desired **auth_url**, I get an HTTP 400 with the error “**missing client token**”.

Obviously I do not have a client token at this point in time, since I am yet trying to authenticate and for that I need to get the auth_url. Am I missing something here?

### To Reproduce 

```
vault secrets enable -version=2 kv
vault kv put kv/landscape-master-password landscape-master-password=evenmoresecret
vault policy write managelmp -<<EOF
path "kv/data/landscape-master-password" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
EOF

vault auth enable -path=authtest userpass
vault auth list
vault write auth/authtest/users/engler password=verysecret policies=managelmp

vault auth enable oidc
vault write auth/oidc/config -<<EOF
{
  "oidc_client_id"      : "...",
  "oidc_client_secret"  : "...",
  "oidc_discovery_url"  : "...",
  "default_role"        : "defaultrole"
}
EOF

vault write auth/oidc/role/defaultrole -<<EOF
{
  "verbose_oidc_logging"    : true,
  "user_claim"              : "sub",
  "groups_claim"            : "groups",
  "allowed_redirect_uris"   : "http://localhost:8888/oidc/callback,http://localhost:8250/oidc/callback,https://localhost:8200/ui/vault/auth/oidc/oidc/callback",
  "policies"                : [ "default" ]
}
EOF

vault write auth/oidc/role/managelmprole -<<EOF
{
  "verbose_oidc_logging"    : true,
  "user_claim"              : "sub",
  "groups_claim"            : "groups",
  "bound_claims": {
    "groups": "master"
  },
  "allowed_redirect_uris"   : "http://localhost:8888/oidc/callback,http://localhost:8250/oidc/callback,https://localhost:8200/ui/vault/auth/oidc/oidc/callback",
  "policies"                : [ "default", "managelmp"]
}
EOF
```

### Environment:
* Server and client version: Vault v1.3.2
* Server Operating System/Architecture: MacOs

Vault server configuration file(s):

config.hcl
```hcl
ui = true
log_level="trace"

storage "file" {
  path = "./vault-volume"
}

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_cert_file = "../vaulttestconfig/vaultcert.crt"
  tls_key_file = "../vaulttestconfig/vaultkey.key"
}
```

**Additional context**

**Comment by tyrannosaurus-becks** [comment]
Thanks for posting this issue! I've confirmed that I can duplicate it locally on Vault master. Your usage directly ties to [this doc](https://www.vaultproject.io/api-docs/auth/jwt/#oidc-authorization-url-request) and I can see [here](https://github.com/hashicorp/vault-plugin-auth-jwt/blob/f7b66bab6feac450a625be1e7a77e8e3fb3f1fb4/backend.go#L56) that the code should not require a token.

**Comment by kalafut** [comment]
@michael-engler I believe `https://localhost:8200/v1/auth/oidc/auth_url` should be `https://localhost:8200/v1/auth/oidc/oidc/auth_url`. "auth/oidc" is the mount, and "oidc/auth_url" is the path you're trying to hit.

**Comment by tyrannosaurus-becks** [comment]
Hi! It appears this is solved so I'm closing it. Please don't hesitate to reopen it if you have further issues. Thanks!
