### ISSUE TITLE
kv2 with file storage sub folders error

### ISSUE THREAD

**Issue by EwasWorld** [hashicorp/vault#8551]
**Describe the bug:**
I'm testing out vault using a kv-v2 secrets engine and I get an error whenever I try to create a secret in a path with more than two sub-levels: `vault kv put kv2/hello/test foo=bar` works fine but `vault kv put kv2/hello/test/inner foo=bar` gives the error:
```text
Error writing data to kv2/data/hello/test/inner: Error making API request.
URL: PUT http://computer-name:8200/v1/kv2/data/hello/test/inner
Code: 500. Errors:
* 1 error occurred:
* open \TestStorage\logical\1d34d4cd-84bd-4e83-626e-2e03da618724\d6ca3d58-c962-31e2-4e2a-a890b1ba86f9\metadata\5kKUZh9o4S1STwSKAzymlxgGxLvPUVMvjahvZ1OWMfWmFGFa9KrWZDzQuj0KLF\5kKQI7Q9VxMF429lZtiKLnFkqMrfuQzC9tHwF4SCFn5by302KXJvqSAu0tP0ex\_5kKV162Go76BWFUo9ByzLQtbzOrT4QyILUz5xeTOxe64mZmh8cmtMsKg3oelmq: The system cannot find the path specified.
```

After attempting this secret creation inside `inner`, doing `vault kv list kv2/hello` presents the folder `test/` as a key, showing that the folder `test` has been created, but `vault kv list kv2/hello/test` returns `No value found at kv2/metadata/hello/test`.

The same error occurs on the server when trying to convert a v1 kv engine into a kv-2 engine if the v1 kv engine has a secret nested in a path with more than two sub-levels. The engine then becomes inaccessible - forever giving the error `Upgrading from non-versioned to versioned data. This backend will be unavailable for a brief period and will resume service shortly` after attempting any calls.

**Important Factoids:**
Secrets engine: kv-v2
Server storage: file

The issue does not seem to appear with other secrets engines or other storage systems

**Environment:**
* Vault Version: Vault v1.3.2
* Operating System/Architecture: Win10

**Vault Config File:**
```hcl
ui=true

storage "file" {
  path    = "/TestStorage"
}

listener "tcp" {
 address     = "computer-name:8200"
 tls_disable = 1
}
```

**Comment by tyrannosaurus-becks** [comment]
Hi! Thanks for posting this issue. 

I'm presently on an Ubuntu machine and I can't reproduce the error. I notice that there are various potentially promising hits when I do [a search](https://www.google.com/search?q=Win10+The+system+cannot+find+the+path+specified&oq=Win10+The+system+cannot+find+the+path+specified&aqs=chrome..69i57j0l4.2141j0j7&sourceid=chrome&ie=UTF-8) for that error. Have you attempted going through any of the fixes there? If so, what were your results?

**Comment by EwasWorld** [comment]
I've tried many fixes:
-  Disable McAfee Security Scanner
- `sfc /scannow`
- Using different storage locations in the config file
- `DISM /Online /Cleanup-Image /RestoreHealth`
- sfc scan (again)
- Clean up temp files and folders using Windows' Disk Cleanup
- Repair registry using the program Registry Repair
- Update the OS
- `chkdsk /f C:` and restart the machine

None of these have resolved my issue. I've also tried on a new, clean vm, my works machine itself, and my personal computer (all win10).

Each time I start the server, unseal, and run:
```
vault secrets enable -path=kv2 kv-v2
vault kv put kv2/a/b/c/d foo=world
```

**Comment by jefferai** [comment]
Windows has maximum file path length restrictions. Try it with a dev server (which is in memory) and I bet it'll work fine. Unfortunately nothing we can do in this situation if that's the problem.

**Comment by jefferai** [comment]
Also if you don't specifically need kvv2 features, kvv1 doesn't encrypt paths so will more closely match the paths within Vault.

**Comment by EwasWorld** [comment]
Yes, as mentioned in the original post, the problem was only with the file-system storage, we can't replicate the problem with in-memory storage. Unfortunately we've been asked to specifically look into kvv2.
If it is that the length is the problem, it would be very helpful to know what the specific length restrictions are for vault paths. I couldn't find anything in the documentation.

**Comment by jefferai** [comment]
They're not Vault restrictions, they're Windows restrictions that affect all programs running on Windows. See https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation

You may be able to try increasing this max path length on Windows 10 but I have not tried it and cannot say if it will work.

**Comment by HridoyRoy** [comment]
Hi folks,
Is this issue good to close?
Thanks!

**Comment by EwasWorld** [comment]
Yes, it can close. If it's a windows restriction there's nothing we can do. Thanks
