### ISSUE TITLE
AWS secret: allow specifying custom policies for assume role at generation time

### ISSUE THREAD

**Issue by adongy** [hashicorp/vault#8552]
**Is your feature request related to a problem? Please describe.**
I'm managing authentication and authorization to my AWS infrastructure through Vault with its secret backend.

Currently, to follow the least privileges policy, I use the AWS secret backend `assume_role` credential type, documented here: https://www.vaultproject.io/docs/secrets/aws/index.html#sts-assumerole

A sample configuration looks like:
- an AWS IAM role, with a policy attached to it that describes the allowed actions
- a Vault secret role, with `credential_type = "assumed_role"` and `role_arns = [role_arn]`
- a Vault policy, with access to the `aws/creds/role-name` so Vault users can generate STS tokens

My issue comes from the fact that to add a new "role/authorization", I have to edit two different providers, both Vault and AWS. Furthermore, AWS holds a very interesting part (the policy contents), while Vault is holding the authorization part.

The Vault role declaration currently allows restricting the generated credentials through policy ARNs/documents, but they're only available at the role definition time. The `aws/{creds/sts}/role_name` endpoint that actually generate the credentials only allows choosing from a role ARN, so you still need to create roles on AWS.

**Describe the solution you'd like**
Expose the `policy_arns` and `policy_document` from the `aws/roles/:name` endpoint on `aws/{sts,creds}/:name`.

This way, you can allow a wide policy on the AWS role, configure a single Vault role with that role attached, and through Vault policies enforce the use of `policy_arns`/`policy_document` that conform to the Vault user rights. Vault becomes responsible for the whole chain of authorization.

**Describe alternatives you've considered**
I'm currently using configuration management tools such as Terraform to centralize my AWS and Vault configuration so they do not become out of sync. I create a AWS role, give proper AssumeRole rights to my Vault instance roles, and configure an extra role + policy.

**Additional context**
If this is interesting, it should also be defined what happens when both the Vault role and the credentials generation request provide policies:
- override the configured attributes
- merge the configured attributes

If a PR would be accepted, I can provide an implementation.

Thanks!

**Comment by joelthompson** [comment]
Hey @adongy -- what about having multiple Vault roles map to the same AWS role, but each with its own appropriate `policy_arns` and/or `policy_document` parameters? From an end-user perspective, I would prefer to just know the Vault role rather than also know the required `policy_arns` and/or `policy_document` parameters to provide. And from an operator standpoint, you see everything about the role in one spot -- you don't have to look at both the role and the policies to figure out the rights a given user has.

Thoughts?

**Comment by adongy** [comment]
Hey @joakimhellum, I can certainly see that as a viable solution. We name roles a specific way to get identity templating to grant authorizations properly but that can be worked around with existing features. I'll leave the request open, but feel free to close it if needed.

**Comment by hsimon-hashicorp** [comment]
Closing as per last comment; please feel free to re-open if needed!
