### ISSUE TITLE
credential owner

### ISSUE THREAD

**Issue by ampyla** [hashicorp/vault#8553]
Hey. If a user connects to the vault via ldap and generates credentials for the database, ssh, etc., and receives credentials with the following usernames v-ldap-ko.-test-Kker9AmSrxmE2y3DVKZD-158, how can I find out from the vault the owner this login? How do I know what kind of user is using these credentials?Well, or at least that he would generate a login with the full name of the LDAP user? Sorry for my bad english

**Comment by tyrannosaurus-becks** [comment]
Hi! Thanks for this question!

Are you aware we have a forum located [here?](https://discuss.hashicorp.com/c/vault/30) Happy to take on this question here, but going forward, if you post they're you'll typically get faster answers.

Using Vault's audit logs, you'd be able to tie that back to a user. An overview of audit logs is located [here](https://www.vaultproject.io/docs/audit/) and the API itself is located [here](https://www.vaultproject.io/api/system/audit.html#enable-audit-device). You'd check the audit logs for the response containing that username, and it would give you information about the request that was made and the token in use at the time.

**Comment by ampyla** [comment]
Thank you. It worked for me.
