### ISSUE TITLE
Vault UI Error

### ISSUE THREAD

**Issue by lcgkm** [hashicorp/vault#8568]
**Describe the bug**
Error message from Chrome developer console.
<img width="813" alt="Screen Shot 2020-03-16 at 10 32 15 AM" src="https://user-images.githubusercontent.com/5523451/76718403-aaa31000-6771-11ea-838a-17f132619136.png">

**Expected behavior**
No Error

**Environment:**
Vault 1.3.1+prem

**Comment by tyrannosaurus-becks** [comment]
Hi! Thanks for posting this! It looks like you're an enterprise customer - can I encourage you to open a ticket in our [support portal](https://support.hashicorp.com/hc/en-us)? That will be faster. The will probably need more information from you about how to replicate this issue.

**Comment by lcgkm** [comment]
Done. Thanks!
