### ISSUE TITLE
Main site does not render correctly under safari

### ISSUE THREAD

**Issue by pcastellazzi** [hashicorp/vault#858]
Attached is a screenshot of https://vaultproject.io as rendered by Safari running on a fully updated OS X  10.11.2

![screenshot 2015-12-15 01 10 33](https://cloud.githubusercontent.com/assets/753312/11801904/ee050046-a2c8-11e5-913b-9fd9ea3c8aa2.png)

**Comment by jefferai** [comment]
@captainill can you look into this?

**Comment by jefferai** [comment]
Closing as this should be fixed.
