### ISSUE TITLE
Vault audit log shows my Ldap password!

### ISSUE THREAD

**Issue by quangphuong1609** [hashicorp/vault#8580]
I know this is crazy but Vault audit log shows my username's pure password in the logging file.

This is unacceptable because Ldap password of any username must be hidden from any auditor!

Step to reproduce:
1. Enable Ldap method
2. Enable audit log
3. Login to Vault by Ldap account
4. Check the log

**Comment by chrishoffman** [comment]
We take Vault's security and our users' trust very seriously. If you believe you have found a security issue in Vault, please responsibly disclose by contacting us at security@hashicorp.com. Our PGP key is available at [our security page](https://www.hashicorp.com/security/).

Deleting this issue and if you believe it to still be an issue, please reopen using the responsible disclosure procedures above.
