### ISSUE TITLE
Fill identity.entity.aliases.<accessor>.metadata when perform AWS login

### ISSUE THREAD

**Issue by carnei-ro** [hashicorp/vault#8603]
I'd like to be able to query AWS Metadata (such IAM Role) from **identity.entity.aliases.<accessor>.metadata** when a login is performed using the method "aws". This feature enables the creation of custom template policies. Such feature exists in "kubernetes" method.

**Comment by kalafut** [comment]
Hi. Some metadata was added recently in 1.3.2:  #7985

**Comment by tyrannosaurus-becks** [comment]
Hi @carnei-ro , does the linked PR solve your request? Or are you looking for additional metadata? If you're looking for additional, can you state which particular fields?

Thanks for opening this, by the way!

**Comment by raskchanky** [comment]
Hi @carnei-ro 

We haven’t heard back from you on this for a while. I’m going to close this for now, but please feel free to re-open it with additional information!
