### ISSUE TITLE
LDAP policy vs entity policy - strange behavior

### ISSUE THREAD

**Issue by elvis2** [hashicorp/vault#8611]
**Describe the bug**
For some reason, I'm seeing odd behavior with policies and ldap users. We tested in the CLI and UI and get the same consistent behavior as reported below.

For example, if I add  the"admin" policy (only policy attached besides default) to my ldap user, I can access everything the "admin" policy allows.

If I add the "blah" policy that is restrictive, to secrets/blah/blahh/* (only policy attached besides default" to my ldap user, it's like the policy is not picked up, only the default policy is used.

If I remove the "blah" policy, and add the same one to the entity attached to my auth_ldap, access works fine as expected...

The kicker here, is sometimes, this behavior isn't consistent. For example, I assigned an "admin-for-BU" policy to another ldap user, their entity had no policies, and everything works great.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.3+ent
* Vault CLI Version (retrieve with `vault version`): 1.1.2
* Server Operating System/Architecture: CentOS 7.3

**Comment by tyrannosaurus-becks** [comment]
Hi! Thank you for opening this issue.

Can you provide more concrete steps to reproduce this? Even if the reproduction isn't 100%, if we could get it some percent of the time, that would be helpful. The docs on auth and secrets engines tend to have mini-walkthroughs of how to configure them via the CLI ([like this for example](https://www.vaultproject.io/docs/auth/ldap/)). 

It would be awesome to have something like that for this issue.

Thanks again!

**Comment by raskchanky** [comment]
Hi @elvis2 

We haven’t heard back from you on this for a while. I’m going to close this for now, but please feel free to re-open it with additional information!
