### ISSUE TITLE
Tag 1.3.4 and 1.3.3 Changelog is not correct

### ISSUE THREAD

**Issue by kkirsche** [hashicorp/vault#8628]
**Describe the bug**
The changelog for tag 1.3.4 and 1.3.3 shows version 1.3.2's changelog

**To Reproduce**
Visit one of the following URLs in your web browser https://github.com/hashicorp/vault/blob/v1.3.4/CHANGELOG.md
https://github.com/hashicorp/vault/blob/v1.3.3/CHANGELOG.md

**Expected behavior**
Should display changelog with 1.3.4's and/or 1.3.3's changes

**Environment:**
Github

Vault server configuration file(s):
N/A

**Comment by kalafut** [comment]
Hi. The changelog on master (https://github.com/hashicorp/vault/blob/master/CHANGELOG.md) is the definitive version covering all releases. There are sometime additions or corrections fixed post-release, so please refer to master.

**Comment by kkirsche** [comment]
@kalafut @vishalnayak understood, the problem though is this is what you link to on your website, https://www.vaultproject.io/downloads/, as such you are creating a situation where (if this continues) users can't easily tell what changes are for the latest release. 

I don't actually care about the tag, I care that your website no longer links to valid changelogs

**Comment by kalafut** [comment]
Ah, ok.  That link is indeed incorrect and will be fixed. Thanks for highlighting it.

**Comment by kkirsche** [comment]
No worries, sorry for not being more clear and highlighting that in the original issue

**Comment by kalafut** [comment]
@jescalan Could you help with this update? It appears that URL is part of an ui gen process that I'm not too familiar with.

**Comment by jescalan** [comment]
You got it, working on a resolution for this 😀

**Comment by aphorise** [comment]
Closing request as request 1.3.x versions and releases then are no longer supported.

A `main` branch is what's been switched to and the correct [CHANGELOG.md to refer](https://github.com/hashicorp/vault/blob/main/CHANGELOG.md) is that residing on the main branch. There are times when the CHANEGLOG.md may not generate correctly and that's then bundled with the releases which may then include errors and unless another release will will be made for these documentation type issues (not likely) then they will remain. It is better to refer to the projects master / main changelog which can continue to be updated even when related releases may have issues with their own notes at the time.

@kkirsche  thank you for reporting this.
