### ISSUE TITLE
Ability to set and change advertising address from CLI (vault admin)

### ISSUE THREAD

**Issue by mnikhil-git** [hashicorp/vault#863]
operational requirement would be to set the advertising address on vault servers dynamically/runtime via command line. The idea is basically to have dynamic discovery of the active leader in vault HA and expose it to the clients via service discovery/DNS.

**Comment by jefferai** [comment]
Hi,

See https://github.com/hashicorp/vault/pull/856 which adds the ability to set the address via a environment variable.

**Comment by mnikhil-git** [comment]
@jefferai  #856 is for during the startup. I meant to open this issue to set the advertiser address during runtime of vault not at the startup. Can you reopen this?

**Comment by jefferai** [comment]
@mnikhil-git Can you describe the use-case here? Especially given that you're talking about service discovery/DNS, it's not clear to me what you can achieve by setting this during runtime.
