### ISSUE TITLE
Provide a way to list paths in cubbyhole

### ISSUE THREAD

**Issue by johnnybubonic** [hashicorp/vault#8644]
**Is your feature request related to a problem? Please describe.**
Currently, there is no programmatic way via neither the API nor the client (obviously) to list the paths directly under `cubbyhole/`. This information is only exposed via the web UI.

**Describe the solution you'd like**
A listing of the secrets found under the cubbyhole. (e.g. `LIST /v1/cubbyhole/`) which will return the directories under there.

**Describe alternatives you've considered**
None available.

**Explain any additional use-cases**
Anything programmatic e.g. integrated client libraries, etc.

**Additional context**
None

**Comment by johnnybubonic** [comment]
actually, this seems to be my bad- for some reason, LIST /v1/cubbyhole/ DOES work, but wasn't working for me when i tried. whoops! closing. not sure what happened there.

**Comment by tyrannosaurus-becks** [comment]
Oh cool! I'm glad to hear that! Thanks for the follow-up.
