### ISSUE TITLE
add telemetry to vault agent

### ISSUE THREAD

**Issue by 45cali** [hashicorp/vault#8649]
**Is your feature request related to a problem? Please describe.**
We need a way to monitor vault agent. Currently if it fails to renew a lease, not authenticate with vault or retrieve a token, we dont know about it. 

**Describe the solution you'd like**
Add the telemetry stanza to vault agent and add a metrics for
- auto-auth failures
- lease renewal failures
- how many times a token has been renewed
- http response code from vaults api

It would also be nice if there was a prometheus endpoint available to scrape these metrics as well.

**Comment by TamasNeumer** [comment]
This would be also important for us.

**Comment by andrejvanderzee** [comment]
We are also very interested.

**Comment by BorisDr** [comment]
Really needed and important feature.

**Comment by jamesgoodhouse** [comment]
This makes the Vault agent a risky proposition to run in production systems, especially in Kubernetes. Without the ability to collect metrics and telemetry it's hard to determine when things are failing. This is crucial if it's to be relied upon to update secrets or renew leases. Last thing we would want is for lease renewals to silently fail and then start having cascading failures across the entire system.

**Comment by owenhaynes** [comment]
Yeah this would be helpful because k8s token issuer name change went undetected because of not have any telemetry about agent auth failures.

**Comment by fewknow** [comment]
We could really use this today at citizen bank.
