### ISSUE TITLE
[docs] GitHub documentation is up to date but not the Hashicorp documentation website 

### ISSUE THREAD

**Issue by carlosjgp** [hashicorp/vault#8652]
I'm seeing a missing `lease` on the website

> to revoke all AWS access keys, you can do `vault revoke -prefix aws/`

https://www.vaultproject.io/docs/concepts/lease/

but when I click on "edit this page on GitHub"

https://github.com/hashicorp/vault/blob/master/website/pages/docs/concepts/lease.mdx

documentation is up to date

**Comment by tyrannosaurus-becks** [comment]
Hi! Thanks for bringing this to our attention! 

There's a lag between when docs are updated and when they're pushed to our website. For ones that we want to go out before the next release, we put them onto our `stable-website` branch. For ones we want to go out with the next release (that are non-urgent), we leave them just on `master` and they go out with minor point releases.

Looks like the docs you're thinking of were updated 8 days ago (https://github.com/hashicorp/vault/pull/8330) so they will go out with the next minor point release. 

Thank you again! Going to close this as I don't think any further action is needed here.
