### ISSUE TITLE
Vault API Explorer does not allow parameters on /token/create

### ISSUE THREAD

**Issue by identitymonk** [hashicorp/vault#8665]
Hi,

**Describe the bug**
When using Vault API Explorer (through portal) and trying to create a token, I cannot specified all parameters allowed in the corresponding standard API call.

**To Reproduce**
1. Open Vault portal and authenticate
2. Launch graphical CLI and execute `api`
3. Filter API on `/token/create`
4. `POST` on `/token/create` expects `No parameters`

![image](https://user-images.githubusercontent.com/28766017/78261962-e6f2a200-74cd-11ea-9cb8-48f8f22e85d0.png)

**Expected behavior**
Parameters as in https://www.vaultproject.io/api-docs/auth/token/#create-token should be allowed

**Environment:**
* Vault Server Version 1.3.4

**Comment by tyrannosaurus-becks** [comment]
Thanks for posting this! Just to confirm, I am also able to reproduce this issue.

**Comment by bmcguire** [comment]
Also would it be possible to create tokens from the Vault-UI?
