### ISSUE TITLE
Broken link in `website/pages/docs/plugin/index.mdx`

### ISSUE THREAD

**Issue by kula** [hashicorp/vault#8683]
Potentially related to #8674 - the link in `website/pages/docs/plugin/index.mdx`:

```
Detailed information regarding the plugin system can be found in the
[internals documentation](/docs/internals/plugins).
``` 

on the website goes to `https://www.vaultproject.io/docs/internals/plugins.html` which 404s - looks like `https://www.vaultproject.io/docs/internals/plugins/` is the correct link

**Comment by cipherboy** [comment]
This now is in `plugin-management.mdx` and points back to `/docs/plugins`; `/docs/internals/plugins` is redirected also to `/docs/plugins`, so I'm going ahead and closing this.
