### ISSUE TITLE
Vault with ZooKeeper

### ISSUE THREAD

**Issue by narayan8291** [hashicorp/vault#870]
Scenario:
I have two servers (x,y) configured with the same backend zookeeper. 
**x and y are real machines with real ip addresses. 

Server Configuration for x:
backend "zookeeper" {
  address = "A"
  path = "vaultmaster"
  advertise_addr = "http://x:8200"
}
listener "tcp" {
 address = "x:8200"
 tls_disable = 1
}

Server Configuration for y:
backend "zookeeper" {
  address = "A"
  path = "vaultmaster"
  advertise_addr = "http://y:8200"
}

listener "tcp" {
 address = "y:8200"
 tls_disable = 1
}

When I do vault version in x, I can see it is in active mode
vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
Mode: active
Leader: http://x:8200

When I do vault version in y, I can see it is in standby mode and the leader ip has changed to the server which is active and hence http://x:8200
vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
Mode: standby
Leader: http://x:8200

Now, if I write a secret 'rfnew' to x and post the curl request, 
 curl -H "X-Vault-Token:<token>" http://x:8200/v1/secret/rfnew I get the right value. 

Now, I post the request in y, 
curl -H "X-Vault-Token:<token>" http://y:8200/v1/secret/rfnew I don't get the value since it is stand-by mode. 

Now, I kill the active server (x) and now the server y becomes the active server and the leader ip become 
http://y:8200. If i post the request, 
curl -H "X-Vault-Token:<token>" http://y:8200/v1/secret/rfnew I get the right value. 

Question:
1. I assume that we need to an endpoint which will help clients to discover who is in the active status. This is an extra hop. I was wondering if this is the right approach for my scenario ? 

2. When both the servers are alive (x:active and y:standby) and when the client does a CURL request to y, can that request be redirected to x since y doesn't reveal the secret as it is in standby mode.

**Comment by jefferai** [comment]
Hi there,

Can you please post questions on the mailing list (https://groups.google.com/forum/m/#!forum/vault-tool) rather than in GitHub issues? This gets a lot more eyes on any particular question or idea.

It also prevents problematic issue workflows for questions where either the issue is closed immediately but then discussion continues on a closed issue; or, the issue is not closed, discussion dies down, and the issue remains open indefinitely waiting for further potential replies.

Thanks!
