### ISSUE TITLE
Docs Improvement: Highlight consul-template on the Vault Agent page

### ISSUE THREAD

**Issue by CommanderTso** [hashicorp/vault#8701]
Hi folks,

I've been trying to resolve updating Vault templates on demand from CI; Vault Agent is a bad fit currently for this in a number of ways.  After a lot of research, I finally saw consult-template, and realized that it is a much better fit for this.

It would save a lot of time for people in this spot if you highlighted the different usecases these two tools cover and added that into your Vault documentation. I would think the Vault Agent page would be the best spot for that, but of course that's up to you.

Thanks.

**Comment by tyrannosaurus-becks** [comment]
@CommanderTso thanks for opening this! Can you elaborate further on the particular use cases you're thinking of, or on the particular docs you'd like to see? I'm not entirely clear from your description above.

**Comment by CommanderTso** [comment]
@tyrannosaurus-becks Thanks for the quick response! I hope my first response didn't come off as curt, I wrote it hurriedly after a long day of staring at bash scripts.  

My specific use case is that we have an internal Vault intstance and I'm trying to insert secrets into a set of .yaml files that will get placed on a VM via a GitLab CI job.  After reading the Vault docs, it seemed like the best bet to do this was to use Vault Agent - it's not well suited to this, though, in that it seems much more suited to monitor seldom-changing templates and update them when secrets change.  In this case, it's the templates driving the changes.  Agent also seems designed to run as a continuous background process, which wasn't optimal for doing inside a CI job.

After looking at consul-template, although I still need to auth into my Vault instance with a local Vault install on the build runner, I can then use the `-once` flag to update the templates and exit.

I know there are at least one or two workarounds I can do to some of my above issues, but I found myself incrementing closer and closer to a really hacky setup, and I wasn't sure where it was going to end.

It's quite possible I'm misusing Agent, and that was part of my problem - please let me know if that's the case.  Thanks.

**Comment by CommanderTso** [comment]
Forgot to answer your second part - I think it'd be helpful to mention consul-template and highlight the relative strengths of the two products in the Vault Agent documentation page, so someone going down the path I did can get a quicker handle on things.  Thanks.

**Comment by tyrannosaurus-becks** [comment]
Hi! Nope, the issue didn't come across as curt at all, I simply lacked the context you had on the question. Thanks for the elaboration, it helps a lot!

**Comment by aphorise** [comment]
Hey @CommanderTso - is this an for you and have you revisited the docs since?
 - [Vault Agent Templates](https://www.vaultproject.io/docs/agent/template#vault-agent-templates)

It may be different from the time when this issue was raised and I was curious of your thoughts.

**Comment by aphorise** [comment]
Closing due to no follow up. Please re-open if still relevant.
