### ISSUE TITLE
MSSQL as secrets engine is not working on minikube + vault server

### ISSUE THREAD

**Issue by lkasiuipath** [hashicorp/vault#8710]
Followed every step to get vault installed on minikube (https://learn.hashicorp.com/vault/getting-started-k8s/minikube)

I am trying to add mssql database secrets engine to test dynamic credentials. I have SQL Server Developer and SQL Server Express both installed locally, enabled TCP ports 8200, 1433 and UDP port 1434 firewall rules, inbound and outbound. I am able to connect to both these instances via SSMS (sql and windows auth)

$ vault write database/config/my-mssql-database plugin_name=mssql-database-plugin connection_url=“sqlserver://{{username}}:{{password}}@localho
st\SQLEXPRESS:1433” allowed_roles="*" username="…" password="…"

error creating database object: unable to parse connection url
Worked around by using a different syntax as described below

$ vault write database/config/my-mssql-database plugin_name=mssql-database-plugin connection_url=‘server=localhost;port=1433;user id="…";passwor
d="…";’ allowed_roles="*"

error creating database object: error verifying connection: Unable to open tcp connection with host ‘localhost:1433’: dial tcp 127.0.0.1:1433: connect: connection refused
$ vault write database/config/my-mssql-database plugin_name=mssql-database-plugin connection_url=‘server=localhost\SQLEXPRESS;port=1433;user id
="…";password="…";’ allowed_roles="*"

error creating database object: error verifying connection: Unable to get instances from Sql Server Browser on host localhost: read udp 127.0.0.1:47613->127.0.0.1:1434: read: connection refused
Any help to fix this is appreciated

**Comment by tyrannosaurus-becks** [comment]
Hi! When you drop into a command line within the node using kubectl exec, are you able to connect to MySQL using that connection URL?

**Comment by lkasiuipath** [comment]
I am new to using Kubernetes, can you please share how i can do this ? I am running this on a windows machine

**Comment by lkasiuipath** [comment]
I am running the cmds I listed inside cmdline created using : kubectl exec -it vault-0 -- /bin/sh

Please share if i need to do anything different

**Comment by lkasiuipath** [comment]
SQL Server instance is not running inside minikube and so this will not work, so will close this
