### ISSUE TITLE
Error unsealing: Error making API request.

### ISSUE THREAD

**Issue by prashansahans** [hashicorp/vault#8712]
* Deployed vault on Openshift
* Vault keys are Initialized
* While unsealing get error:-
     
      **_Error unsealing: Error making API request.

URL: PUT https://vault-vault-test-app.router.default.svc.cluster.local/v1/sys/unseal
Code: 500. Errors:

* failed to decrypt encrypted stored keys: cipher: message authentication failed_**

**Comment by tyrannosaurus-becks** [comment]
Hi @prashansahans , thanks for opening this issue! I'm sorry to hear you're running into issues. Can you provide additional information we'd need to further understand your issue? We would need everything contained in the [bug report](https://github.com/hashicorp/vault/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) template. Thanks again!

**Comment by prashansahans** [comment]
Hello,
I want to basically integrate vault with openshift following some blogs.
I deployed vault in let say vaulttest namespace
Then I have to again deploy vault for another nameSpace?
And I have done all the steps regarding it.
But still I get error message permission denied
Please help

**Comment by tyrannosaurus-becks** [comment]
Hi! I'm afraid I still lack the context I would need to answer that question. Can I recommend you move this question over to our forum? https://discuss.hashicorp.com/c/vault/30. That's generally a wide group of Vault users who may be able to relate to the issue you're encountering without needing as specific of steps to reproduce as we do here for bug reports and enhancement requests. Thank you and my apologies that I can't provide immediate assistance given this information.
