### ISSUE TITLE
After unseal, Vault goes into standby mode when using Consul storage backend

### ISSUE THREAD

**Issue by kenjones-cisco** [hashicorp/vault#872]
When running Vault with Consul storage backend (test environment), immediately after the Vault has been unsealed it will go into standby mode and the next action results in a `500 internal error`.

There seems to be a latency from when the Vault is unsealed until the Vault is ready to use. What is the expected flow/process? Instead of a random delay, do we need to start hitting `/v1/sys/health` until we get a `200` that indicates the Vault is ready for use?

```
2015/12/17 12:45:09 [INFO] core: vault is sealed
2015/12/17 12:45:14 [DEBUG] core: cannot unseal, have 1 of 2 keys
2015/12/17 12:45:14 [INFO] core: vault is unsealed
2015/12/17 12:45:14 [INFO] core: entering standby mode
2015/12/17 12:45:14 [ERR] core: token store is unavailable
2015/12/17 12:45:14 [ERR] core: token store is unavailable
2015/12/17 12:45:14 [INFO] core: acquired lock, enabling active operation
2015/12/17 12:45:14 [INFO] core: post-unseal setup starting
2015/12/17 12:45:14 [INFO] core: mounted backend of type generic at logical/49828245-a8d8-9357-7d91-7c9ff2812706/
2015/12/17 12:45:14 [INFO] core: mounted backend of type cubbyhole at logical/89520901-ccc1-83c1-d6c6-69a414692fe8/
2015/12/17 12:45:14 [INFO] core: mounted backend of type system at sys/
2015/12/17 12:45:14 [INFO] rollback: starting rollback manager
2015/12/17 12:45:14 [INFO] core: post-unseal setup complete
```

Consul Configuration:

```
{
  "data_dir": "/data",
  "server": true,
  "bootstrap_expect": 1,
  "datacenter": "dc1",
  "acl_datacenter": "dc1",
  "acl_default_policy": "allow",
  "acl_down_policy": "extend-cache"
}
```

Vault Configuration:

```
backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}

disable_mlock = true
```

**Comment by jefferai** [comment]
The behavior you're describing is not normal, but unfortunately, your logs don't agree with the behavior you're describing:
```
2015/12/17 12:45:09 [INFO] core: vault is sealed
2015/12/17 12:45:14 [DEBUG] core: cannot unseal, have 1 of 2 keys
2015/12/17 12:45:14 [INFO] core: vault is unsealed
2015/12/17 12:45:14 [INFO] core: entering standby mode
```
Here it's standby, because it just unsealed
```
2015/12/17 12:45:14 [ERR] core: token store is unavailable
2015/12/17 12:45:14 [ERR] core: token store is unavailable
2015/12/17 12:45:14 [INFO] core: acquired lock, enabling active operation
```
It got the lock, and is active
```
2015/12/17 12:45:14 [INFO] core: post-unseal setup starting
2015/12/17 12:45:14 [INFO] core: mounted backend of type generic at logical/49828245-a8d8-9357-7d91-7c9ff2812706/
2015/12/17 12:45:14 [INFO] core: mounted backend of type cubbyhole at logical/89520901-ccc1-83c1-d6c6-69a414692fe8/
2015/12/17 12:45:14 [INFO] core: mounted backend of type system at sys/
2015/12/17 12:45:14 [INFO] rollback: starting rollback manager
2015/12/17 12:45:14 [INFO] core: post-unseal setup complete
```
Post-unseal setup is complete...Vault should be up and running. This all looks quite normal. What does the output of "vault status" give you at this point?

Is there anything interesting in the logs for Consul and/or Vault? 500 errors should usually have a corresponding log entry.

**Comment by kenjones-cisco** [comment]
As these are automated tests, there is no assumption of a delay, so immediately after the unseal returns successfully the next operation will start which  is when the `core: token store is unavailable` happens in the Vault logs, and then the API calls are returning `500 internal error`.

**Comment by jefferai** [comment]
Oh, I see. There's not much that can be done about this on the Vault end. Vault needs to grab a lock from the HA backend, which takes some (small) time, and then when it grabs the lock, the active instance needs to set up the resources that it's managing, which also takes some time (which is also usually small, but will involve some number of round-trips to the storage backend). I recommend putting a delay between the unseal and the next command in your tests.

**Comment by kenjones-cisco** [comment]
Based on the logs coming out, there is a point where `post-unseal setup complete` happens, is there a mechanism to be notified when that happens or is the `/v1/sys/health` the only option for that?

**Comment by jefferai** [comment]
`sys/health` is the correct way to discover this in HA mode.

When running standalone, the instance will (after unsealing) change the standby mode to active before running post-unseal activities. If the post-unseal process fails, it will seal again, so the status endpoint will return 500; it's possible that a request could hit during the post-unseal process where we are not returning either 500 or 429 but are not entirely ready to service requests yet. I'll probably change this for 0.5.
