### ISSUE TITLE
golang: working directory is not part of a module

### ISSUE THREAD

**Issue by manjeetsorout** [hashicorp/vault#8736]
i have imported the gin package using "go get -u github.com/gin-gonic/gin" and i'm using Govendor as described in this link: https://gin-gonic.com/docs/quickstart/
but i'm getting the following error when i'm running the main.go file.

main.go:6:2: cannot find module providing package github.com/gin-gonic/gin: working directory is not part of a module.

please help me to resolve this issue

**Comment by pcman312** [comment]
This looks like you accidentally posted this on the wrong GitHub repository. Did you mean to post this on https://github.com/gin-gonic/gin ?

**Comment by manjeetsorout** [comment]
> This looks like you accidentally posted this on the wrong GitHub repository. Did you mean to post this on https://github.com/gin-gonic/gin ?

@pcman312  thanks sir. i have solved this problem by using the go module.

**Comment by manojj-ms** [comment]
How to solve this issue,

**Comment by eduard20028** [comment]
@manojj-ms look again. Wrong repository address  https://github.com/gin-gonic/gin and https://gin-gonic.com/docs/quickstart/ . The first one is right.
