### ISSUE TITLE
Raft (retry_join/CLI) leader-... options (file paths vs PEM data)

### ISSUE THREAD

**Issue by exo-cedric** [hashicorp/vault#8753]
**Describe the bug**

As per `raft`'s `retry_join` documentation - https://www.vaultproject.io/docs/configuration/storage/raft#retry_join-stanza - `leader_...` options are supposedly _path_ to CA/certificate/private-key files

Those must actually be the _PEM data_ in order for the joining to work.

This also stands true for the `vault operator raft join` CLI command - https://www.vaultproject.io/docs/commands/operator/raft#join - although it's less clear those options are not path to files (although other TLS-related options are; e.g. `-ca-cert`)

**Expected behavior**

Ideally, `leader-...` options should be _path to files_ (which makes it less cumbersome to specify multiple `retry_join` stanzas in the configuration file).

But if providing _PEM data_ is the intended behavior, then the [documentation](https://www.vaultproject.io/docs/configuration/storage/raft#retry_join-stanza) should be corrected and maybe the [CLI options](https://www.vaultproject.io/docs/commands/operator/raft#join) explicited.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.4.0
* Vault CLI Version (retrieve with `vault version`): 1.4.0
* Server Operating System/Architecture: n/a

**Comment by vvidovic** [comment]
Maybe "file options" should be provided for three certificate/key properties, for example:
leader_ca_cert_file

This would enable me to use a simple configuration in the OpenShift cluster, something like:
```
 "leader_ca_cert_file": "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
```
Instead of:
```
"leader_ca_cert": "-----BEGIN CERTIFICATE-----\nMIID...\n-----END CERTIFICATE-----"
```

**Comment by vvidovic** [comment]
In the similar configuration - seal/transit (https://www.vaultproject.io/docs/configuration/seal/transit) "tls_ca_cert" parameter takes a path to the cert file.

**Comment by Lucretius** [comment]
I ran into this as well.  [This function](https://github.com/hashicorp/vault/blob/master/physical/raft/raft.go#L138) appears to be the culprit.  The retry_join stanza is read but the file paths are never actually read by something like `ioutil.ReadFile` to get the actual byte contents.  Instead, the file content strings are [just casted to byte arrays and passed in to the TLS Configuration function](https://github.com/hashicorp/vault/blob/master/physical/raft/raft.go#L159).  The fix is to read the file contents, handling errors, before passing their contents in.

**Comment by zelch** [comment]
Looking at things, SetupTLSConfig and ClientTLSConfig really appear to be intended for the exact same thing, except one takes (in theory) byte arrays and one takes a conf map which holds things like tls_cert_file.

The only user in the vault repo of ClientTLSConfig is raft, which uses it incorrectly.

A slight refactor of both functions might be in order so we don't duplicate quite so much code, and so we actually handle the raft TLS settings correctly.

**Comment by calvn** [comment]
Thanks for bringing this up! This should be addressed by https://github.com/hashicorp/vault/pull/8894.

**Comment by exo-cedric** [comment]
Thanks for #8894 !
For consistency's sake, shouldn't the CLI part also be addressed (in `command/operator_raft_join.go`) ?
