### ISSUE TITLE
Vault and Okta OIDC configuration

### ISSUE THREAD

**Issue by gh-kgangineni** [hashicorp/vault#8766]
Hi
I was able to setup Okta OIDC app and integrate with Vault. I followed Auth0 example given in the vault docs. The second part of the doc talks about passing group information . What value should I pass in the groups_claim , when I create an oids role in vault
Below is the example from the doc with Auth0 as example
vault write auth/oidc/role/kv-mgr
bound_audiences="$AUTH0_CLIENT_ID"
allowed_redirect_uris="http://127.0.0.1:8200/ui/vault/auth/oidc/oidc/callback"
allowed_redirect_uris="http://localhost:8250/oidc/callback"
user_claim="sub"
policies="reader"
groups_claim="https://example.com/roles"

**Comment by trodemaster** [comment]
I am using these values in a known working okta/oidc config. 
user_claim              = "sub"
  role_type               = "oidc"
  groups_claim            = "groups"
  oidc_scopes             = ["profile", "groups"]

**Comment by aphorise** [comment]
I believe there's a learn guide that exemplifies this setup and another good reference material can be the Okta Auth specific documentation (not OIDC) - as per:

 - Learn: [OIDC Authentication with Okta](https://learn.hashicorp.com/tutorials/cloud/vault-oidc-okta)
 - Docs: [Okta Auth Method](https://www.vaultproject.io/docs/auth/okta#okta-auth-method)Okta Auth Method)

These may have not been avaible or as they are today. Hey @gh-kgangineni are you okay to close?

**Comment by aphorise** [comment]
Closing as there's been no follow up. Please re-open if still relevant.
