### ISSUE TITLE
No lease_id provided when getting secret

### ISSUE THREAD

**Issue by kenjones-cisco** [hashicorp/vault#877]
Following the documentation @ https://vaultproject.io/intro/getting-started/apis.html The `lease_id` is not provided like in the example. 

What is required to get the `lease_id`?

#### Steps taken and responses

```
$ curl -X PUT -d '{"secret_shares":1, "secret_threshold":1}'  http://localhost:8200/v1/sys/init
{"keys":["db5d4af39932a4c3f1c394aa96129884601e470dba05a0308393410ade4849a4"],"root_token":"978d22d3-3390-35eb-e842-808890240dee"}

$ export VAULT_TOKEN=978d22d3-3390-35eb-e842-808890240dee

$ curl -X PUT -d '{"key": "db5d4af39932a4c3f1c394aa96129884601e470dba05a0308393410ade4849a4"}' http://127.0.0.1:8200/v1/sys/unseal
{"sealed":false,"t":1,"n":1,"progress":0}

$ curl \
>     -X POST \
>     -H "X-Vault-Token:$VAULT_TOKEN" \
>     -d '{"type":"app-id"}' \
>     http://127.0.0.1:8200/v1/sys/auth/app-id

$ curl \
>     -X POST \
>     -H "X-Vault-Token:$VAULT_TOKEN" \
>     -d '{"value":"root", "display_name":"demo"}' \
>     http://localhost:8200/v1/auth/app-id/map/app-id/152AEA38-85FB-47A8-9CBD-612D645BFACA

$ curl \
>     -X POST \
>     -H "X-Vault-Token:$VAULT_TOKEN" \
>     -d '{"value":"152AEA38-85FB-47A8-9CBD-612D645BFACA"}' \
>     http://localhost:8200/v1/auth/app-id/map/user-id/5ADF8218-D7FB-4089-9E38-287465DBF37E

$ curl \
>     -X POST \
>     -d '{"app_id":"152AEA38-85FB-47A8-9CBD-612D645BFACA", "user_id": "5ADF8218-D7FB-4089-9E38-287465DBF37E"}' \
>     "http://127.0.0.1:8200/v1/auth/app-id/login"
{"lease_id":"","renewable":false,"lease_duration":0,"data":null,"warnings":null,"auth":{"client_token":"3bf8007c-5351-fa32-97ca-a527d5e5caf8","policies":["root"],"metadata":{"app-id":"sha1:1c0401b419280b0771d006bcdae683989086a00e","user-id":"sha1:4dbf74fce71648d54c42e28ad193253600853ca6"},"lease_duration":0,"renewable":false}}

$ export VAULT_TOKEN=3bf8007c-5351-fa32-97ca-a527d5e5caf8

$ curl \
>     -X POST \
>     -H "X-Vault-Token:$VAULT_TOKEN" \
>     -H 'Content-type: application/json' \
>     -d '{"bar":"baz"}' \
>     http://127.0.0.1:8200/v1/secret/foo

$ curl \
>     -H "X-Vault-Token:$VAULT_TOKEN" \
>     http://127.0.0.1:8200/v1/secret/foo
{"lease_id":"","renewable":false,"lease_duration":2592000,"data":{"bar":"baz"},"warnings":null,"auth":null}
```

#### Vault Logs

```
$ vault server --config=config/dev.hcl -log-level=debug
==> WARNING: mlock not supported on this system!

  The `mlock` syscall to prevent memory from being swapped to
  disk is not supported on this system. Enabling mlock or
  running Vault on a system with mlock is much more secure.

==> Vault server configuration:

         Log Level: debug
             Mlock: supported: false, enabled: false
           Backend: inmem
        Listener 1: tcp (addr: "0.0.0.0:8200", tls: "disabled")
           Version: Vault v0.4.0

==> Vault server started! Log data will stream in below:

2015/12/18 16:06:51 [INFO] core: security barrier initialized (shares: 1, threshold 1)
2015/12/18 16:06:51 [INFO] core: post-unseal setup starting
2015/12/18 16:06:51 [INFO] core: mounted backend of type generic at logical/a7b18ee9-bc81-1eec-1790-f24adbd49cf5/
2015/12/18 16:06:51 [INFO] core: mounted backend of type cubbyhole at logical/e437d652-feda-51df-3331-bfee7b2a3918/
2015/12/18 16:06:51 [INFO] core: mounted backend of type system at sys/
2015/12/18 16:06:51 [INFO] rollback: starting rollback manager
2015/12/18 16:06:51 [INFO] core: post-unseal setup complete
2015/12/18 16:06:51 [INFO] core: root token generated
2015/12/18 16:06:51 [INFO] core: pre-seal teardown starting
2015/12/18 16:06:51 [INFO] rollback: stopping rollback manager
2015/12/18 16:06:51 [INFO] core: pre-seal teardown complete
2015/12/18 16:08:08 [INFO] core: vault is unsealed
2015/12/18 16:08:08 [INFO] core: post-unseal setup starting
2015/12/18 16:08:08 [INFO] core: mounted backend of type generic at logical/a7b18ee9-bc81-1eec-1790-f24adbd49cf5/
2015/12/18 16:08:08 [INFO] core: mounted backend of type cubbyhole at logical/e437d652-feda-51df-3331-bfee7b2a3918/
2015/12/18 16:08:08 [INFO] core: mounted backend of type system at sys/
2015/12/18 16:08:08 [INFO] rollback: starting rollback manager
2015/12/18 16:08:08 [INFO] core: post-unseal setup complete
2015/12/18 16:08:27 [INFO] core: enabled credential backend 'app-id/' type: app-id
```

**Comment by jefferai** [comment]
That documentation needs to be updated; since 0.3 the `generic` backend no longer generates leases. I'll make sure it's updated...thanks for reporting it!

**Comment by kenjones-cisco** [comment]
I'm trying to build unit tests for `vaulted` around Lease renew/revoke, but they all require lease_id. So what is the simplest approach to getting one generated as part of a normal operation?

**Comment by jefferai** [comment]
It doesn't quite work like that...not all backends and/or operations within a backend generate leases. For instance, `generic ` (as of 0.3) never generates one, and `transit` never has and never will.

A value in `lease_id` indicates that a lease was created, and the lack of a value indicates it was not. There is no way to force generation of one for an operation that does not normally issue a lease.

**Comment by jefferai** [comment]
If you're just looking to get a lease, any lease, try the `pki` backend as it doesn't have external dependencies. Just generate a root cert, configure a role, and issue a cert.

**Comment by kenjones-cisco** [comment]
I have Consul secret backend enabled, so when using that backend instead of generic. So, if I use that backend, then a `lease_id` should be generated?

**Comment by kenjones-cisco** [comment]
Didn't see the comment on `pki` before the last comment, I will look into that. Thanks.

**Comment by kenjones-cisco** [comment]
Seems that the certs issued via `pki` are not renewable.

```
{ lease_id: 'pki/issue/example-dot-com/34801a2c-5a18-8435-9836-af28d046b489',
  renewable: false,
  lease_duration: 259199,
  data:
   { certificate: '<removed for brevity>',
     issuing_ca: <removed for brevity>',
     private_key: <removed for brevity>',
     private_key_type: 'rsa',
     serial_number: '4b:89:f9:a2:ea:95:66:81:9a:a1:e1:44:88:7f:99:dd:09:29:21:f5' },
  warnings: null,
  auth: null }
```

**Comment by jefferai** [comment]
That is correct, they are not.

**Comment by issacg** [comment]
@jefferai why not?  Wouldn't it make as much sense to store the CSR along with the cert and allow a cert to be renewed until max_ttl rather than issueing a new keypair every time you want to renew?

**Comment by jefferai** [comment]
@issacg If you're using CSRs you don't need a new keypair, just a new CSR.

**Comment by issacg** [comment]
@jefferai 

I'm not using CSRs.  I'm using /pki/issue, which AFAIK doesn't give me the CSR...

My intent was if vault saved the CSR in calls to /pki/issue (I'm assuming it's not saving the private keys) to allow the PKI backend to renew certs, rather than requiring apps to issue a new keypair (to "extend" the "lease")

**Comment by jefferai** [comment]
Vault doesn't generate CSRs in calls to `/pki/issue` -- it generates the certificate directly. It actually wouldn't be able to generate new CSRs even if it was, since they need to be signed by the private key, which as you noted Vault purposefully doesn't save. 

There's still a way it might be possible (not as-is, but in theory) but it hasn't been a request up to this point, because most people concerned with private keys transiting the wire are using CSRs anyways for exactly that reason, and once you get a private key from `/issue` you can generate a CSR from that in order to get a "renewal". So it hasn't been a need.

I'm happy to take that as a future enhancement request but there are going to be a lot of core enhancements coming in the next few releases that will also affect the backends a lot and I'd like to wait until after that happens to consider it. In the mean time, using CSRs, or "renewing" with CSRs, is a workaround.
