### ISSUE TITLE
Comparison with Barbican

### ISSUE THREAD

**Issue by achanda** [hashicorp/vault#88]
Please compare with Barbican, which is a project in OpenStack
https://wiki.openstack.org/wiki/Barbican

**Comment by armon** [comment]
@achanda We try to provide comparisons for widely used and well known software. Barbican does not help anchor people's thinking about Vault, as most people are not familiar with it.

**Comment by ches** [comment]
I beg to differ. I don't know of any other open source solution closer to Vault's problem space than Barbican, in other words it is exactly the most relevant comparison I could think of. It may be best known within the OpenStack community, but if you don't believe there's some overlap there with the audience of HashiCorp's projects, I believe you're making a mistake.

**Comment by armon** [comment]
Hi @ches, I definitely understand your concern. In talking with customers (both during the beta and after the initial release), we did not find a strong enough user base to justify the inclusion of such a comparison. Barbican is a very OpenStack-specific solution, and, to be totally honest, their architecture is very difficult to follow and much more complex than that of Vault. While the argument can be made that Vault and Barbican are in the same problem space, they take incredibly different approaches to solving that problem.

If a member of the community would like to submit a comparison, we will happily review it and consider it for inclusion in the documentation (all the docs are open source and in Vault's repo in the website/ folder), but this is not something we will be authoring ourselves. Please let me know if you have any questions.

**Comment by ches** [comment]
That's fair, thanks Armon.
