### ISSUE TITLE
storage / raft / retry_join / leader_ca_cert should accept a file path

### ISSUE THREAD

**Issue by vvidovic** [hashicorp/vault#8806]
On docs page (https://www.vaultproject.io/docs/configuration/storage/raft) leader_ca_cert is shown in the example as "/path/to/ca2" while it should be String of PEM certificate.

I expected this property to require a file path (similar to listener/tcp property tls_cert_file) so this required a bit of analysis from my side to find out what was causing TLS handshake errors.

Maybe "file options" should be provided for three certificate/key properties, for example:
leader_ca_cert_file

This would enable me to use a simple configuration in the OpenShift cluster, something like:
```
 "leader_ca_cert_file": "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
```
Instead of:
```
"leader_ca_cert": "-----BEGIN CERTIFICATE-----\nMIID...\n-----END CERTIFICATE-----"
```

**Comment by mengesb** [comment]
Is this issue duplicated by #8753 ?

**Comment by vvidovic** [comment]
Yes, it is (mostly) a duplicate. I was searching for "leader_ca_cert" and not "retry_join" and I didn't find issue #8753 .
The only difference here is suggestion to keep two sets of options:
- leader_ca_cert
- leader_ca_cert_file
I will add this notion to the other issue and close this one, thanks.
