### ISSUE TITLE
learn.hashicorp.com Typo on Secrets as a Service: Dynamic Secrets page

### ISSUE THREAD

**Issue by eyenx** [hashicorp/vault#8819]
**Describe the bug**
There is a bug in the code section of step 2 on this site:

https://learn.hashicorp.com/vault/secrets-management/sm-dynamic-secrets

Step 2:

```
vault write database/config/postgresql
        plugin_name=postgresql-database-plugin \
        allowed_roles=readonly \
        connection_url=postgresql://root:rootpassword@localhost:5432/postgres?sslmode=disable
```

The backslash is missing on the first line, making copy-paste not possible for users.

**To Reproduce**
* copy by using the `clipboard-icon`
* paste in terminal
* error

**Expected behavior**
Copy paste should work without issues. With an additional backslash on the first line, this would work.

**Environment:**
n/a

Vault server configuration file(s):
n/a

**Additional context**
n/a

**Comment by yhyakuna** [comment]
@eyenx  Thank you so much for reporting this!  It's [fixed](https://learn.hashicorp.com/vault/secrets-management/sm-dynamic-secrets#step-2-configure-postgresql-secrets-engine) now.
