### ISSUE TITLE
Policy: Not working when I have a policy starting with wildcard

### ISSUE THREAD

**Issue by RyanSiu1995** [hashicorp/vault#8835]
**Describe the bug**
I wanted to create a rule that match any kv engine with the secret name `sth` inside the engine.
For example, I had an automation that would generate a kv engine with a generated name. Inside that engine, we would create the secret `sth`. But I want to create a general account that could fit in all the product from this automation
So, I was setting up the policy with the following rules
```hcl
path "*/sth/*" {
  // sth
}
```
But it didn't work as expected.

**To Reproduce**
1. Create the policy as describe above
1. Assign this policy to particular account.
1. Try to use that account to read the secret

**Expected behavior**
That account should be able to retrieve the secret

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   false
Total Recovery Shares    1
Threshold                1
Version                  1.3.4+prem
Cluster Name             vault
Cluster ID               1233ec64-f4dc-551a-9490-fca261574418
HA Enabled               true
HA Cluster               https://10.127.4.2:8201
HA Mode                  active
Last WAL                 20396364
```
* Vault CLI Version (retrieve with `vault version`):
```
Vault v1.3.4
```
* Server Operating System/Architecture:
Debian

Vault server configuration file(s):
Cannot get the configuration for the time being.

**Additional context**

**Comment by pcman312** [comment]
Thanks for opening this issue! Unfortunately the wildcard syntax (`*`) is not a regular expression and is only supported as the last character of the policy path ([https://www.vaultproject.io/docs/concepts/policies#policy-syntax](https://www.vaultproject.io/docs/concepts/policies#policy-syntax)) so the policy you are trying to create isn't a valid policy. Can you instead set up your automation so it automatically updates the policy with the generated KV store name when the store is created?

**Comment by RyanSiu1995** [comment]
Sound good if I can use `+` sign to replace the wildcard syntax! 
Thank you for your quick reply!
