### ISSUE TITLE
Typo on Cubbyhole Response Wrapping Learn Tutorial

### ISSUE THREAD

**Issue by karras** [hashicorp/vault#8848]
There seems to be a typo in the Cubbyhole Response Wrapping tutorial:

https://learn.hashicorp.com/vault/secrets-management/sm-cubbyhole

It says:

`The unwrap the wrapped secret, you can do one of the following.`

I guess it should say:

`To unwrap the wrapped secret, you can do one of the following.`

PS: Let me know if I failed to find the sources for the Learn tutorial and I'll directly open a PR next time. :)

**Comment by calvn** [comment]
Thanks for the find! The learn site source is currently not publicly available due to various custom bits in there, but we'll get the docs updated whenever we receive reports like these.

**Comment by yhyakuna** [comment]
@karras  Thank you so much for reporting this.  It's now fixed!
