### ISSUE TITLE
delete all secrets under a path

### ISSUE THREAD

**Issue by nickithewatt** [hashicorp/vault#885]
It would be very handy if vault allowed for the deletion of a whole path of secrets, rather than have to delete them one by one.

e.g. 
```
vault delete -recurse=true secret/teams/teamA OR
vault delete secret/teams/teamA/*
``` 

would delete everything under this path which may include for example secret/teams/teamA/password1, secret/teams/teamA/password2 but not secret/teams/teamB/password1 etc. 

You may say that you can simply mount different teams under different areas and then use unmounting as one option, which is true, however, if for whatever reasons, you choose to partition vault in another way (maybe prod/dev/staging etc) having the ability to bulk delete secrets in this fashion is very handy (at least in the generic backend) provided you have the privs to do so of course

**Comment by jefferai** [comment]
Hi there,

We looked at it a bit ago as part of another feature we were implementing and found some issues, the main being that deletion behavior across physical backends did not always support recursive delete natively and performing a manual delete within Vault by recursively listing and deleting could have deleterious effects on the backends (especially HA backends) if the number of keys was large. This could mean that an operation could unexpectedly cause both a very long delay within a Vault-using application completing, and could put serious load on the backend.

For now we decided to stick to having clients recursively delete if they desire, but each operation then is much less likely to cause an issue, and the delete can be abandoned by the client at any point along the way and retried later if the backend has become too loaded.

What will help and allow this is that list support will come to generic soon (next release or two), so it then becomes a pretty easy walk of the tree and delete commands.

If we find a good way to support recursive delete across physical backends we will certainly be looking at implementing it.

**Comment by nickithewatt** [comment]
Thanks Jeff makes sense!

**Comment by RulerOf** [comment]
I wrote a ruby script to do this in our environment, then cleaned it up and put in in a repo in case anyone needs to do this: https://github.com/BuyerQuest/vault-recursive-delete

**Comment by hipyhop** [comment]
I came here looking for the same thing and ended up just using a bash for loop
`for path in $(vault list database/roles); do vault delete database/roles/${path}; done`

**Comment by Abukamel** [comment]
I have created a script that will recursively delete a path of kv secret engine versions 2.

It may help https://github.com/Abukamel/vault-recursive-delete

**Comment by gw0** [comment]
I also ended up using a bash loop:

```bash
$ path="kv/foo/bar"; for key in $(vault kv list -format=json "$path" | jq -r '.[]'); do vault kv metadata delete "$path/$key"; done
```

**Comment by kauedg** [comment]
I'll leave my script here, also

```
#!/bin/bash

# $1        kv mount
# $2        path

delete_path()
{
    IFS=$'\n' values=($(vault kv list -format=json "$1" | jq -r '.[]'))

    if [ -z $values ]; then
        echo "delete $1"
        vault delete $1
    else
        for key in ${values[@]} ; do
            echo enter: "$1$key"
            delete_path "$1$key"
        done
        
        echo "delete $1";    
    fi
}

delete_path "$1/$2/"
```

**Comment by bobthebuilderberlin** [comment]
Another workaround using a local-exec provisioner:
```
resource "vault_generic_secret" "my_secret" {
  path = "<secret-engine-mount-path>/<path-to-secret>"

  data_json = <<EOT
{
  "FOO": "BAR"
}
EOT
  # Delete on_destroy
  //count = 0
  provisioner "local-exec" {
        when        = "destroy"
        command     = "curl --header \"X-Vault-Token: $${VAULT_TOKEN}\" --request DELETE \"$${VAULT_ADDR}/v1/kv/metadata/<path-to-secret>""
  }
}
```

Comment in the `//count = 0` to delete the secret with all versions.

**Comment by TommyStarK** [comment]
Updated your script if you wish to permanently delete all secrets under the given path.

```bash
#!/bin/bash

# $1 secret/foo/

delete_path()
{
    IFS=$'\n' values=($(vault kv list -format=json "$1" | jq -r '.[]'))

    if [ -z $values ]; then
        echo "delete $1"
        versions=$(vault kv metadata get -format=json $1 |jq '.data.versions | keys_unsorted[] | tonumber' | tr '\n' ',')
        vault kv destroy --versions=$versions $1
        vault kv metadata delete $1
    else
        for key in ${values[@]} ; do
            echo enter: "$1$key"
            delete_path "$1$key"
        done
        
        echo "delete $1";    
    fi
}

delete_path "$1"

```

**Comment by snahelou** [comment]
Hello 

What's the difference between  `vault kv destroy --versions=$versions $1` and `vault kv metadata delete $1`  ? 

`kv metadata delete` should delete all versions, isn't it ? 

BR

**Comment by sjiveson** [comment]
> Updated your script if you wish to permanently delete all secrets under the given path.
> 
> ```shell
> #!/bin/bash
> 
> # $1 secret/foo/
> 
> delete_path()
> {
>     IFS=$'\n' values=($(vault kv list -format=json "$1" | jq -r '.[]'))
> 
>     if [ -z $values ]; then
>         echo "delete $1"
>         versions=$(vault kv metadata get -format=json $1 |jq '.data.versions | keys_unsorted[] | tonumber' | tr '\n' ',')
>         vault kv destroy --versions=$versions $1
>         vault kv metadata delete $1
>     else
>         for key in ${values[@]} ; do
>             echo enter: "$1$key"
>             delete_path "$1$key"
>         done
>         
>         echo "delete $1";    
>     fi
> }
> 
> delete_path "$1"
> ```

Thanks for this. I found that vault was returning a new line in it's response, leading the tr command to add a trailing space. I had to change this line to remove it:
```
        versions=$(vault kv metadata get -format=json $1 |jq '.data.versions | keys_unsorted[] | tonumber' | tr '\n' ','| sed 's/\(.*\),/\1 /')
```
