### ISSUE TITLE
Rejoin nodes after they have been removed

### ISSUE THREAD

**Issue by ngarafol** [hashicorp/vault#8854]
I am not sure I understand or use raft correctly. 
Normally I use HA with 3 nodes, transit unseal node1 that becomes leader.
Raft join node2 and node3 to leader (node1). All seems good, three nodes visible in raft configuration.

Now I remove peer, say node2 from raft configuration. And then how do I re-join node2 back to leader? 
Repeating same raft join command now fails because raft is still initialized and error message is:

`{"errors":["raft storage is already initialized"]}`

Raft join command I use is this:

`curl -H "Content-Type: application/json" --request POST --data '{"leader_api_addr": "http://leader-node.vault-internal:8200", "retry_join": "true"}' http://node2.vault-internal:8200/v1/sys/storage/raft/join`

Looking at code, there is only check if raft is initialized, which it stays no matter if node is member of raft or not -> https://github.com/hashicorp/vault/blob/master/vault/raft.go#L570

So would it make sense to keep track if node is also a member of raft cluster, in order to be able to rejoin to leader (even different one) or am I using it wrong? 

I would expect that remove-peer removes, but that there is still some "reconnect" method existing in case I want removed node back in raft cluster.

**Comment by aphorise** [comment]
A work-around that I tried in a similar 3 node cluster - with vault2 removed from the peers list - was delete the Raft `vault.db` file on vault2, restarting the service on the node and re-`join` which works fine.

However with this approach upon adding node2 back a re-election occurs causing node1 (leader from start) to become a follower of vault3 that's then the leader (unexpectedly).

```
# // Before & After removal of node2
vault operator raft list-peers
 # Node      Address                 State       Voter
 # ----      -------                 -----       -----
 # vault1    192.168.178.253:8201    leader      true
 # vault2    192.168.178.252:8201    follower    true
 # vault3    192.168.178.251:8201    follower    true

vault operator raft list-peers
 # Node      Address                 State       Voter
 # ----      -------                 -----       -----
 # vault1    192.168.178.253:8201    leader      true
 # vault3    192.168.178.251:8201    follower    true

sudo rm -rf /vault/data/vault.db
sudo service vault restart
vault status
 # Key                      Value
 # ---                      -----
 # Recovery Seal Type       awskms
 # Initialized              false
 # Sealed                   true
 # Total Recovery Shares    0
 # Threshold                0
 # Unseal Progress          0/0
 # Unseal Nonce             n/a
 # Version                  n/a
 # HA Enabled               true
vault operator raft join https://192.168.178.253:8200
 # Key       Value
 # ---       -----
 # Joined    true
vault status
# Key                      Value
# ---                      -----
# Recovery Seal Type       shamir
# Initialized              true
# Sealed                   false
# Total Recovery Shares    1
# Threshold                1
# Version                  1.4.2+ent
# Cluster Name             primary
# Cluster ID               21761b05-7e4e-50b0-fcd8-78599c882264
# HA Enabled               true
# HA Cluster               https://192.168.178.251:8201
# HA Mode                  standby
# Active Node Address      https://192.168.178.251:8200
# Raft Committed Index     280
# Raft Applied Index       280
```

Repeating similar steps as above but deleting both the `vault.db` & `raft.db` however **did work as expected without any re-election**.

I'm wondering if the following log message from the leader also point to the Vault process continuing to make election calls after it has been removed:

```
…  vault1 vault[3679]: …  [WARN]  storage.raft: rejecting vote request since we have a leader: from=192.168.178.252:8201 leader=192.168.178.253:8201
…  vault1 vault[3679]: …  [WARN]  storage.raft: rejecting vote request since we have a leader: from=192.168.178.252:8201 leader=192.168.178.253:8201
…  vault1 vault[3679]: …  [WARN]  storage.raft: rejecting vote request since we have a leader: from=192.168.178.252:8201 leader=192.168.178.253:8201
# // 192.168.178.252 is the removed vaul2 node.
```

**Comment by ncabatoff** [comment]
Hi @ngarafol,

There's no provision for rejoining an existing node that has left the cluster.  This is a sufficiently rare use case that it's probably not worth adding explicit support for it - especially since you can simply join a new node instead, or equivalently, wipe the db files from the node before attempting a new join with it.
