### ISSUE TITLE
unable to build Ui in mac

### ISSUE THREAD

**Issue by rohan2546** [hashicorp/vault#8875]
using the below command

''' 

make static-dist dev-ui

'''

getting the following errors

✨  Done in 100.54s.

--> Generating static assets

make: go-bindata-assetfs: No such file or directory

make: *** [static-assets] Error 1

Although, the file is there in the directory

**Comment by calvn** [comment]
Have you ran `make bootstrap` beforehand? If not, can you give that a try and re-run `make static-dist dev-ui` afterwards?

**Comment by rohan2546** [comment]
Yeah make bootstrap is done and make dev is working fine

**Comment by rohan2546** [comment]
I tried to install go-assetfs but still make static-dist dev-ui is not working

**Comment by roommen** [comment]
I just a fine build of UI on my mac. The make static-dist dev-ui command went fine without a glitch!
Time to resolve this as NAB

**Comment by HridoyRoy** [comment]
Hi, I was able to build on my Mac as well. I'm going to go ahead and close this issue, but please feel free ask setup questions in our [discuss forums](https://discuss.hashicorp.com/c/vault/30). Thanks!
