### ISSUE TITLE
Support for parallel storage migration

### ISSUE THREAD

**Issue by gites** [hashicorp/vault#8883]
**Is your feature request related to a problem? Please describe.**
Migration of Vault storage containing a lot of keys can take a long time (that depends on the storage backend). As this operation should be done when the cluster is offline it can follow to the situation where long cluster downtime is not acceptable. 
In my case doing migration for ~100k keys from Consul to GCS took ~3h 40m. That was waaaaay more than acceptable for Vault in my case.

**Describe the solution you'd like**
Speed up the migration process as much as possible. Migrate the keys in parallel. I prepared a PR adding that feature https://github.com/hashicorp/vault/pull/8857
 
**Describe alternatives you've considered**
I tried to do a Consul -> Local Filesystem migration and then put those data into GCS bucket using `gsutil`.  Unfortunately, this didn't work due to Vault storing data in a bit different format on local fs and GCS bucket.

**Explain any additional use-cases**

**Additional context**
The parallel migration uses way more resources (CPU, RAM) than the current solution, but that was acceptable as this was a one time job. In my case, the migration time for  ~100k keys from Consul to GCS was shortened from ~3h 40m to ~5m (using 100 goroutines). The time gain is highly dependent on the type of storage being migrated and migration direction.

**Comment by peteski22** [comment]
https://github.com/hashicorp/vault/pull/18817 should resolve this.
