### ISSUE TITLE
TYPO in Vault DR Replication HOWTO

### ISSUE THREAD

**Issue by eyenx** [hashicorp/vault#8897]
**Describe the bug**
On this HowTo regarding DR Replication, there is a typo

https://learn.hashicorp.com/vault/operations/ops-disaster-recovery#dr-operation-token-strategy

Step: DR Operation Token Strategy

Command:

```
vault polcy write ...
```

should be

```
vault policy write
```

**Comment by pcman312** [comment]
Thanks for the bug report @eyenx!

**Comment by pcman312** [comment]
This should be fixed now. Thanks again for reporting this!
