### ISSUE TITLE
Vault works static-creds with MS SQL Server

### ISSUE THREAD

**Issue by arieldalefe** [hashicorp/vault#8930]
I would really like Vault static-creds to work with MS SQL Server. There is a forecast for this implementation on your Roadmap?

Thanks.

Vault is an excellent tool. Congrats!

**Comment by austingebauer** [comment]
Thanks for the feature request, @arieldalefe! I don't have a timeline to share with you on that, but your request has been seen.

**Comment by austingebauer** [comment]
@arieldalefe - Static role rotation for the MSSQL database secrets engine has been added in https://github.com/hashicorp/vault/pull/9062 and will be available in the next Vault release.
