### ISSUE TITLE
Vault UI does not update user list when sequentually oppening several auth methods of the same type

### ISSUE THREAD

**Issue by HnH** [hashicorp/vault#8932]
**Describe the bug**
Vault UI is not updating list of users within an auth method if there was an auth method of the same type previously observed through UI.

**To Reproduce**
```
[sergey@dev]$ vault write sys/auth/first/storage type=userpass
Success! Data written to: sys/auth/first/storage

[sergey@dev]$ vault write sys/auth/second/storage type=userpass
Success! Data written to: sys/auth/second/storage

[sergey@dev]$ vault auth list
Path               Type        Accessor                  Description
----               ----        --------                  -----------
first/storage/     userpass    auth_userpass_c1be1488    n/a
second/storage/    userpass    auth_userpass_74c53fc1    n/a
token/             token       auth_token_852ab06f       token based credentials

[sergey@dev]$ vault write auth/first/storage/users/antoniobanderas password=something
Success! Data written to: auth/first/storage/users/antoniobanderas

[sergey@dev]$ vault write auth/second/storage/users/angelinajolie password=something
Success! Data written to: auth/second/storage/users/angelinajolie

[sergey@dev]$ vault list auth/first/storage/users
Keys
----
antoniobanderas

[sergey@dev]$ vault list auth/second/storage/users
Keys
----
angelinajolie
```
Although observing theese auth methods though UI will result in showing both storages have only antoniobanderas, either angelinajolie depending on the first auth method that was observed. Reproduces in both chrome and firefox.

First storage | Second storage
------------ | -------------
![image](https://user-images.githubusercontent.com/1931443/81149073-28bbb000-8f86-11ea-958e-dfa890301fb2.png) | ![image](https://user-images.githubusercontent.com/1931443/81149082-307b5480-8f86-11ea-8d0d-a28efcf1771c.png)

**Expected behavior**
I expect UI to show list of users from the auth method it's being asked for, not the one that was cached.

**Environment:**
* Vault Server Version (retrieve with `vault status`): v1.4.1
* Vault CLI Version (retrieve with `vault version`): v1.3.2
* Server Operating System/Architecture: Linux 5.6.7-1-MANJARO SMP PREEMPT Thu Apr 23 10:50:31 UTC 2020 x86_64 GNU/Linux
* Vault server configuration file(s): default config from docker image

**Comment by sfynx** [comment]
This also happens with the Roles section of the Kubernetes auth method, so it is definitely a general problem with listing extra information related to any auth method of the same type. Very annoying indeed. Still happens with v1.5.0.

**Comment by hellobontempo** [comment]
Thank you for reporting! Closing this out as I tested as far back as 1.9.10 and the issue has been resolved. Please reopen if you experience otherwise.
