### ISSUE TITLE
How to use vault DNS to inject secrets.

### ISSUE THREAD

**Issue by rdeb22** [hashicorp/vault#8941]
When using Standalone Vault , we used DNS for checking status, leader, secrets etc.
like,
```
curl https://vault-int.com/v1/sys/health
curl https://vault-int.com/v1/sys/leader
curl https://vault-int.com/v1/secret/$path
```
in K8s.
I have vault running in HA
```
vault-helm-0                                                     1/1     Running   0          46h
vault-helm-1                                                     1/1     Running   0          46h
vault-helm-2                                                     1/1     Running   0          46h
```
And service available to me
```
vault-helm                                          ClusterIP   10.97.39.84      <none>        8200/TCP,8201/TCP                                                         47h
vault-helm-active                                   ClusterIP   10.96.166.70     <none>        8200/TCP,8201/TCP                                                         47h
vault-helm-internal                                 ClusterIP   None             <none>        8200/TCP,8201/TCP                                                         47h
vault-helm-standby                                  ClusterIP   10.102.25.22     <none>        8200/TCP,8201/TCP                                                         47h
vault-helm-ui                                       ClusterIP   10.99.53.225     <none>        8200/TCP
```

I created an Ingress and created a dns pointing to the above service, but these commands are not working and throwing default backend - 404

$curl https://vault-int.com/v1/sys/health
default backend - 404.

How can I do the same in k8s.
Why there are so many SVC.
I understand the use of UI. But what are others used for?

**Comment by pcman312** [comment]
Thanks for opening this issue. Are you aware of our forum located here: https://discuss.hashicorp.com/c/vault/30? If possible, we appreciate it when folks ask questions there because we generally use Github for bugs and enhancement requests.

If you've set up your own load balancer outside of the official helm chart, you can point it at the `vault-helm-active` service. The helm chart also has an ingress option available that handles load balancing.

**Comment by jasonodonnell** [comment]
Hi @rdeb22:

> Why there are so many SVC. I understand the use of UI. But what are others used for?

These services have different purposes.
* `vault-helm` is a generic general use service that round robin load balances requests over all the Vault pods.
* `vault-helm-active` directs traffic to the active Vault pod.  This service is helpful for write traffic, or during upgrades where the active pod needs to be upgraded last. This requires Kubernetes service registration to be enabled in your configuration file: https://github.com/hashicorp/vault-helm/blob/master/values.yaml#L375
* `vault-helm-standby` directs traffic to the standby Vault pods.  This service is helpful for read only traffic, or during upgrades where standbys need to be upgraded first.  This requires Kubernetes service registration to be enabled in your configuration file: https://github.com/hashicorp/vault-helm/blob/master/values.yaml#L375
* `vault-helm-internal` is used by the Vault pods themselves to communicate directly with each other using DNS.  This is required for Vault when using Raft storage as the pods need to coordinate leader elections and communicate directly with each pod.  This is known as a headless service and shouldn't be used by anything other than the Vault pods internally.

Hope that clarifies the services.

**Comment by rdeb22** [comment]
@jasonodonnell  Thank you so much, the explanation was in detail.
