### ISSUE TITLE
OIDC Provider Logo (auth0 shown even if not correct)

### ISSUE THREAD

**Issue by ttinkr** [hashicorp/vault#8949]
**Describe the bug**
Vault tries to guess the OIDC provider by matching inaccurate strings in the domain. I.e. if the domain contains "Auth0" it shows a logo for the Auth0 provider. Our OIDC server has the string "auth0" in it's hostname and so this results in an Auth0-logo being shown and therefore is misleading users.

**To Reproduce**
1. Enable OIDC
2. Configure a callback URL which has _somewhere_ in the URL the string "auth0"
3. Auth0 logo is shown erroneously 

**Expected behavior**
Matching of providers should be based on accurate domain matching. I think the imprecise matching of domains happens here:
https://github.com/hashicorp/vault/blob/8afe8d02f5447268f2174234d93f513cc574aa8d/ui/app/models/role-jwt.js#L12

**Environment:**
* Vault Server Version 1.4.1
* Vault CLI Version: 1.4.1
* Server Operating System/Architecture: Kubernetes 

Thanks!

**Comment by techs07** [comment]
is it also possible to enable logo for other providers. may be some customisation settings to specify the logo details

**Comment by hashishaw** [comment]
Thanks for the report! We are not currently able to customize the UI, but while I'm updating this code I would be happy to add logos from other providers. Are there providers other than the ones listed that you'd like to see logos for @techs07 ?
