### ISSUE TITLE
Include key version in transit sign data response

### ISSUE THREAD

**Issue by chulkilee** [hashicorp/vault#8955]
**Is your feature request related to a problem? Please describe.**

I want to know which version of key is used for signature when I sign data with transit backend when version is not given (which uses the latest version).

**Describe the solution you'd like**

Include the version used to sign the data. Note that it's in `data` so it should work for batch inputs.

Current:

```json
{
  "data": {
    "signature": "vault:v1:MJw4yYv9/Ax49GmKBZ53dMnp1+6ige6eZ/Uj9iUBXwedjrkIxuvSpXQo7bNs7Jqcx+Lgfyt65MXoM6IV8PbOkZy5SVpVPCTldfwNphU1rV0riensP/0xLGOW4P8v3eJst8oP3LM5wX5MmLRotfzW81h3zSpH42RgmgxMmWBd1cxVaHua3IaNUZFp4kxfXldM4568fsnY/R7H8rBp5nGpI/QL30flFeCxUj6nM24RqcmwkKHR5Xn6sUDBvzNeBG7XRvLWqvLQlSZQGFiGEjt7oXzyeMH+YBF4n0zgI+m0bgDH0mjtpQosORxu0T3DwNY2R9255nCjrV+Nj3v8Wciuhw=="
  }
}
```

Proposed:

```json
{
  "data": {
    "signature": "vault:v1:MJw4yYv9/Ax49GmKBZ53dMnp1+6ige6eZ/Uj9iUBXwedjrkIxuvSpXQo7bNs7Jqcx+Lgfyt65MXoM6IV8PbOkZy5SVpVPCTldfwNphU1rV0riensP/0xLGOW4P8v3eJst8oP3LM5wX5MmLRotfzW81h3zSpH42RgmgxMmWBd1cxVaHua3IaNUZFp4kxfXldM4568fsnY/R7H8rBp5nGpI/QL30flFeCxUj6nM24RqcmwkKHR5Xn6sUDBvzNeBG7XRvLWqvLQlSZQGFiGEjt7oXzyeMH+YBF4n0zgI+m0bgDH0mjtpQosORxu0T3DwNY2R9255nCjrV+Nj3v8Wciuhw==",
    "version": 1
  }
}
```

**Describe alternatives you've considered**

Right now I have to read the key (`GET /transit/keys/:name`) and pick the latest version, and specify it (`key_version `) when requesting sign data.

**Comment by gobins** [comment]
Just wondering if it's the text in the data.signature that is showing the version of the key being used.
`"signature": "vault:**v1**`
In the above example, v1 being the version of the key being used.

**Comment by chulkilee** [comment]
Any documentation on the format of the signature? It's not clear whether "1" from "valut:v1:" is the version of key, or version of the structure

**Comment by gobins** [comment]
Can't find any documentation on this but I can find this in the code:
https://github.com/hashicorp/vault/blob/2e1f75a26e53089e4452309f60f2572b13cf64cf/sdk/helper/keysutil/policy.go#L1226

Also, I was able to produce a different version number in the response after I rotated the key.

**Comment by chulkilee** [comment]
Thanks @gobins for investigation!

 I may "parse" the value, but unless it's documented and the support is guaranteed, this value should be treated as opaque so I'd like to avoid that.

So.. to know the version of used key we need one (or both) of followings:

- Make the structure official (`vault:v<version>:...`)
- Return the version in the payload

**Comment by gobins** [comment]
Probably for the Hashicorp Vault team to answer.

**Comment by alexanderbez** [comment]
Based on the [trainsit docs](https://www.vaultproject.io/docs/secrets/transit#usage), the returned ciphertext includes the version of the key used to encrypt the plaintext. However, I'm not sure there is commitment to this format as @chulkilee pointed out. So we can add the key version used to the response 👍
