### ISSUE TITLE
Vault UI allows empty string key 

### ISSUE THREAD

**Issue by mbwkww** [hashicorp/vault#8958]
**Description**
The Vault web-UI allows for a user to insert a secret (key value pair) with the empty string as a key. The UI will block the user from adding additional keys to the file, but still saves the key. Example saved JSON: 
  ```json 
{
          "":"-----BEGIN-CERTIFICATE---- 3U#(kd9m3I*fve ..."
}
```

**To Reproduce**
Login via the web UI. 
Create a secret file. 
Save a secret, leaving the key field unfilled. 

**Expected behavior**
Unless there is a clear use case for this, the UI should prevent the saving of secrets with no associated keys. 

**Environment:**
Vault 1.4 KV engine v2

**Comment by aphorise** [comment]
This is actually a valid case and there's no bug since the proposed write object is **valid json** so the UI behaves the same as the CLI - as per:

```shell
vault secrets enable -path=kv -version=2 kv ;
vault kv put kv/b ""="..." ;
vault kv get -format=json kv/b | jq -r '.data.data|.""' ;
```

Hey @mbwkww I wonder what's your thoughts are and how this may be an issue for you?

**Comment by aphorise** [comment]
Closing due to no response. Please re-open if still relevant.
