### ISSUE TITLE
MongoDBAtlas and Static Roles

### ISSUE THREAD

**Issue by alexpekurovsky** [hashicorp/vault#8966]
Update:
I opened this issue thinking about MongoDB plugin, however seems like problem is with mongodbatlas-database-plugin. I could open new issue, however I decided to update this one.

Original issue:
**Is your feature request related to a problem? Please describe.**
According to documentation MongoDB plugin supports static roles: https://www.vaultproject.io/docs/secrets/databases/mongodb
However in the code of mongo plugin function is no-op https://github.com/hashicorp/vault/blob/master/plugins/database/mongodb/mongodb.go:
```
// RenewUser is not supported on MongoDB, so this is a no-op.
func (m *MongoDB) RenewUser(ctx context.Context, statements dbplugin.Statements, username string, expiration time.Time) error {
	// NOOP
	return nil
}
```

**Describe the solution you'd like**
Fix documentation (fast-win)
Implement functionality (better)

**Describe alternatives you've considered**
Not managing static user via Vault currently

**Comment by ncabatoff** [comment]
Hi @alexpekurovsky,

Looks like static roles were added for MongoDB last year in #7003.  I'm not very familiar with their implementation but it doesn't look like `RenewUser` is a requirement.  I'm going to assume this is a misconception on your part and that it works correctly, as there is a good integration test in that PR.  Please re-open if you find that it doesn't work.

**Comment by alexpekurovsky** [comment]
I would be happy to find some example of using static-roles with mongo, can't find any on the internet

**Comment by alexpekurovsky** [comment]
So after having conversation with Mongo Atlas support, they asked to raise question on Hashicorp's side.

Steps to reproduce:
```
vault write database/config/mymongo \
  plugin_name=mongodbatlas-database-plugin \
  allowed_roles="mongo-rw" \
  public_key="xx" \
  private_key="yy" \
  project_id="zz"

vault write database/static-roles/mongo-rw \
  db_name="mymongo" \
  username="user_existing_in_atlas" \
  creation_statements='{ "database_name": "admin", "roles": [{"databaseName": "ecomm", "roleName": "readWrite"}]}' \
  rotation_period=60
Error writing data to database/static-roles/mongo-rw: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/static-roles/mongo-rw
Code: 500. Errors:

* 1 error occurred:
	* error setting credentials: empty creation statements
```

any games regarding trying `rotation_statements` instead of `creation_statements` leads to the same error - `error setting credentials: empty creation statements`

**Comment by ncabatoff** [comment]
Ok, I've reproduced the bug and understand the issue.  I think the fix is simple enough that I'll take care of it now.

**Comment by themantissa** [comment]
Just jumping in here from MongoDB- so the MongoDB Atlas secret engine is, as you noted @alexpekurovsky  quite different from the MongoDB secret engine.  We did not test supporting static credentials.  I believe we'd have to support that first before you could use that Vault feature with MongoDB Atlas.  It looks like perhaps  @ncabatoff  perhaps is fixing this so the error is more informative but it won't add in the support you seem to be seeking.   If this is a feature you believe we should support please submit it via our Feature request https://feedback.mongodb.com/forums/924145-atlas and select Vault plugin.  Hope this helps!  Feel free to reach out directly.
