### ISSUE TITLE
Vault Sealed when tried to restore backup. 

### ISSUE THREAD

**Issue by rdeb22** [hashicorp/vault#8967]
When I tried to restore an existing backup of keys into vault pods, all pods got sealed and I could not unseal even with unseal Key. 
Steps: Backup File `k8s-backup`
```
#copying the backup folder into consul sever.
Step 1: kubectl cp /tmp/k8s-backup consul-consul-server-0:/tmp 
#restoring
Step 2: onsul snapshot restore /tmp/k8s-backup
```
Result in all Vault Pods got sealed and failed to unseal even with unsealing key. 

could it be because of consul key has to be passed during the vault initialization?

**Comment by ncabatoff** [comment]
Hi @rdeb22,

I see you've already posed this question in the right place (on the [community forum](https://discuss.hashicorp.com/t/how-to-initialise-vault-with-existing-consul-key/8604)) so I'm going to close this issue and respond there.
