### ISSUE TITLE
Vault UI: support default auth method when type != path

### ISSUE THREAD

**Issue by adongy** [hashicorp/vault#8968]
**Is your feature request related to a problem? Please describe.**
Vault UI has a feature that I can't find explicit documentation for, but if there are any authentication backends with `path == type` and `listing_visibility == unauth`, the first will be selected as the default auth backend at the login page.

Unfortunately, it uses both of the cited requirements. The code can be found here (at least that's my understanding of it)

Fetching the mounts with `listing_visibility == unauth` through the internal endpoint https://github.com/hashicorp/vault/blob/80ab8d6a458baeb4a3cecc1134164a0b9e7f499b/ui/app/adapters/auth-method.js#L18-L42

Filtering to the first, or `token` if none match the condition
https://github.com/hashicorp/vault/blob/80ab8d6a458baeb4a3cecc1134164a0b9e7f499b/ui/app/components/auth-form.js#L79-L105 
https://github.com/hashicorp/vault/blob/80ab8d6a458baeb4a3cecc1134164a0b9e7f499b/ui/app/components/auth-form.js#L150-L156

My usecase is a custom oidc plugin (forked from the official `jwt` auth plugin). I want users using the web UI to have the auth method selected by default when arriving to the login URL.

**Describe the solution you'd like**
Remove the `path == type` requirement or any other way to get an auth mount with `path != type` to be selected by default when arriving to the login URL.

**Describe alternatives you've considered**
Currently, users click on the dropdown and select the OIDC mount, after which the flow stays the same.

I also recommend users to bookmark the link with `https://vault.example.com/ui/vault/auth?with=oidc` but that is arguably harder to say than using the base URL only.

Note that I could overwrite the `jwt` auth type with my plugin and that would work, but could cause confusion if I'd ever enable other `jwt` auth mounts.

**Explain any additional use-cases**
-

**Additional context**
-

Thanks!

**Comment by hellobontempo** [comment]
Hi @adongy! We currently aren't able to customize the dropdown and/or have a default selection - but there's an open feature request for that work to be prioritized. 

In the meantime, you can configure an auth mount to be added as a tab to the login form by tuning the [listing_visibility](https://developer.hashicorp.com/vault/docs/commands/auth/tune#listing-visibility) 
```
 vault auth tune -listing-visibility='unauth' <auth_path/>
```
This will add the auth method as a tab to the auth form via its `mount_path`:

<img width="400" src="https://user-images.githubusercontent.com/68122737/231023359-98d919da-7214-4469-b137-aad53487c342.png"/>





Steps with screenshots [in this comment](https://github.com/hashicorp/vault/issues/9076#issuecomment-1498234524)

**Comment by hsimon-hashicorp** [comment]
Hello @adongy - as it's been some time since we've heard from you regarding @hellobontempo's workaround, I'm going to go ahead and close this issue now. Please note as she mentions that we have a feature request logged with our product and engineering teams for the enhancement. If you need to open a new bug report or feature request, please feel free to do so. Thanks!
