### ISSUE TITLE
[1.4.x] Nomad integration breakage with aws / aws-ec2 auth and instance metadata 

### ISSUE THREAD

**Issue by stevenscg** [hashicorp/vault#8972]
Upgrading vault from 1.3.x to 1.4.x causes token renew-self failures with nomad 0.11.1 (and possibly others). This might be a silent BC break for nomad users. It went unnoticed for several days in my test environment, but I suspect that it could have lead to widespread downtime if left long enough.

Error message logged by nomad:
```
nomad.vault: got error or bad auth, so backing off: error="failed to renew the vault token: Error making API request.#012#012URL: PUT https://active.vault.service.consul:8200/v1/auth/token/renew-self#012Code: 500. Errors:#012#012* 1 error occurred:#012#011* failed to renew entry: unable to fetch instance ID from metadata during renewal#012#012" recoverable=true
```

Gitter discussions:
* https://gitter.im/hashicorp-nomad/Lobby?at=5eb99c3a8c044c1914946c21
* https://gitter.im/hashicorp-vault/Lobby?at=5eb9972d20eaac185302484d

The issue seems to be related to recent value changes related to EC2 instance metadata:
* https://github.com/hashicorp/vault/pull/8783
* https://github.com/hashicorp/vault/pull/8880

In my environment, adding back the the ec2_metadata attributes appears to completely fix the issue:
```
vault write auth/aws-ec2/config/identity ec2_metadata=account_id,auth_type,ami_id,instance_id,region iam_metadata=account_id,auth_type,canonical_arn,client_arn,client_user_id,inferred_aws_region,inferred_entity_id,inferred_entity_type
```

I also added iam_metadata based on a previous community member's findings, but those may not be necessary to fix this particular problem.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.4.1
* Vault CLI Version (retrieve with `vault version`): 1.4.1
* Server Operating System/Architecture: CentOS 7

**Comment by avoidik** [comment]
I faced the same, in some cases mandatory metadata field will be required

https://github.com/hashicorp/vault/blob/master/builtin/credential/aws/path_login.go#L965-L969

**Comment by kalafut** [comment]
The update to the metadata handling was indeed an API change, but it definitely should not have broken token renewal.  A fix will be coming soon, and in the interim the manual configuration you've mentioned is the correct mitigation. We've added a [1.4.1 upgrade guide](https://www.vaultproject.io/docs/upgrading/upgrade-to-1.4.1) and updated the 1.3.5 guide to describe this situation and workaround.

After the fix, the metadata customization will not be a requirement. You'll be able to set that as appropriate (or not at all), and Vault will always retain what is needed for token renewal.

Thank you for reporting this!
