### ISSUE TITLE
How to build Vault Ui for window ?

### ISSUE THREAD

**Issue by solitarysp** [hashicorp/vault#8977]
I want to build vault Ui at window os.
But when run ```make static-dist dev-ui``` not working.

How to build vault Ui at window os?

**Comment by austingebauer** [comment]
Hi, @solitarysp. If your goal is to get Vault running on Windows, then it may be easier to download and install a precompiled binary from [Vault downloads](https://www.vaultproject.io/downloads) and use the [Vault install guide](https://www.vaultproject.io/docs/install).

If you need to build Vault from source, I can try to help you out. Could you share the logs from running `make static-dist dev-ui` which failed for you?

**Comment by solitarysp** [comment]
> Hi, @solitarysp. If your goal is to get Vault running on Windows, then it may be easier to download and install a precompiled binary from [Vault downloads](https://www.vaultproject.io/downloads) and use the [Vault install guide](https://www.vaultproject.io/docs/install).
> 
> If you need to build Vault from source, I can try to help you out. Could you share the logs from running `make static-dist dev-ui` which failed for you?

the script in make.bat does not exist dev-ui .
I using ubuntu build for window, but default build is Linux/amd64
