### ISSUE TITLE
OIDC: Issue with multi key group claim 

### ISSUE THREAD

**Issue by techs07** [hashicorp/vault#8979]
**Describe the bug**
Getting an error message of "groups claim could not be parsed as string" when the claim is multi-valued and groups_claim is set as 'groups' .
Tried setting up groups_claim=groups/name and got an error of 'groups/name claim not found in token'

**error:value map[$ref:http://abc:123/admin/v1/Groups/asjhfgdijsgdosfh id:asjhfgdijsgdosfh name:someother_group] in groups claim could not be parsed as string** 

Please handle this use case and provide the option to refer keys in groups claim.
**To Reproduce**

Vault server configuration file(s):

1. start vault: 1.4.1 in dev mode.
$ vault server -dev -dev-root-token-id=root
2. Enable oidc plugin
vault auth enable -plugin-name='oidc' plugin
3. Setup oidc and role
**OIDC config:**
vault write auth/oidc/config \
        oidc_discovery_url="https://abc-xyx.com" \
        oidc_client_id="xxxx" \
        oidc_scopes=“openid,groups”\
        verbose_oidc_logging= true \
        oidc_client_secret="xx-xx" \
        default_role="reader" token_ttl=1h

**Role:**
$cat vault-user. json
 {
    "user_claim": "sub",
    "groups_claim": "groups",
    "policies": [
        "admin"
    ],
    "allowed_redirect_uris": [
        "http://localhost:8200/ui/vault/auth/oidc/oidc/callback",
        "http://localhost:8250/oidc/callback"
    ],
    "bound_claim": {
        "groups": {
            "name": [
                "vault-user"
            ]
        }
    },
    "verbose_oidc_logging": "true",
    "oidc_scopes": "groups"
}
$ vault write auth/oidc/role/dvault-user @demo/vault-user.json

**OIDC provider response**: 
sample claim captured from the debug logs
claims=
{
    "given_name": "First",
    "groups": [
        {
            "$ref": "http://abc:123/admin/v1/Groups/asjhfgdijsgdosfh",
            "id": "asjhfgdijsgdosfh",
            "name": "someother_group"
        },
        {
            "$ref": "http://admin:9246/admin/v1/Groups/kjdfhjdhfjhff",
            "id": "kjdfhjdhfjhff",
            "name": "vault-user"
        }
    ],
    "sub": "name@name.com",
 }

**Expected behavior** Should be able to iterate through the groups using groups_claim even when there are nested level keys.

**Comment by austingebauer** [comment]
Thanks for opening this issue. For bug reports, I'd be great if you could fill in the bug issue template including reproduction steps, expected behavior, etc.

You can currently use JSON pointer ([rfc6901](https://tools.ietf.org/html/rfc6901)) syntax in `groups_claim` to refer to keys nested at a lower levels in the JSON. This is described in https://www.vaultproject.io/docs/auth/jwt#claim-specifications-and-json-pointer. 

In your case, it looks like the groups key refers to an array. So instead of `groups_claim=groups/name`, try using something like `groups_claim=groups/0/name` (where 0 is the index of the group you want to target).

**Comment by techs07** [comment]
Thanks @austingebauer  for the analysis.
setting groups_claim=groups/0/name may not work out as there might be multiple groups available and there are chances of missing group if we  just refer group by the index. (As index may also change with addition/deletion of groups).
Is there any other workaround ?

**Comment by austingebauer** [comment]
Unfortunately, I don't see a workaround that allows for extracting specific key values among all JSON objects in the list of groups you provided. It's expected that the claim value be a list of strings as in the [api docs](https://www.vaultproject.io/api/auth/jwt#groups_claim). That is why you're seeing the error coming from [vault-plugin-auth-jwt/path_login.go#L351](https://github.com/hashicorp/vault-plugin-auth-jwt/blob/master/path_login.go#L351).

**Comment by techs07** [comment]
Is it possible to handle this scenario in the upcoming build or provide a fix which I can build locally.

**Comment by austingebauer** [comment]
I suggest that you open a [feature request](https://github.com/hashicorp/vault/issues/new?template=feature_request.md) if you'd like to see this ability in Vault. I won't be able to provide a fix that you can build locally.

Another suggestion is to check if your provider configuration for `groups` can be changed. It could even be possible to create a new claim with the desired contents (list of strings) to target instead.

**Comment by techs07** [comment]
Is it possible to set groups_claim  something like "groups[*].name" Refer https://jmespath.org/

**Comment by austingebauer** [comment]
That is currently not possible. Only JSON pointer ([rfc6901](https://tools.ietf.org/html/rfc6901)) syntax can be used now. If that's something you'd like to see in Vault, feel free to open a feature request.
