### ISSUE TITLE
[ui] [transit] File upload -> Decrypt -> Download

### ISSUE THREAD

**Issue by iridian-ks** [hashicorp/vault#8984]
**Is your feature request related to a problem? Please describe.**

We're looking for a way to self-service frequent requests to decrypt bank data. We're thinking of using Vault as a way to allow users to securely decrypt their own data. The bank files are quite large and the users aren't super technically savvy. A button to upload an encrypted file that Vault could then decrypt and send back to the user as a download could be an interesting way to overcome this.

**Describe the solution you'd like**

In the UI, under the decrypt tab, add a button for a file upload, which would proceed to decrypt the data and send back to the user as an automatic download.

**Describe alternatives you've considered**

I haven't looked into alternatives. The best alternative would probably be to build a separate service to talk to Vault to implement this feature.

Or use something like Jenkins or Ansible AWX as the frontend and script the behavior. Although, in this method we'd have to use something like email, which is less than ideal.

**Explain any additional use-cases**

Unsure

**Additional context**

**Comment by hellobontempo** [comment]
@iridian-ks, thank you for filing this issue. Is this still something you're looking for? We're reviewing issues over a few years old to see if there is still interest so we can then prioritize them.

**Comment by raskchanky** [comment]
Since it's been awhile with no response, I'm going to close this issue. Please reopen if there's more to add here.
