### ISSUE TITLE
Allow Identity groups to be shared across multiple authentication mount points / paths 

### ISSUE THREAD

**Issue by gavinelder** [hashicorp/vault#9020]
**Is your feature request related to a problem? Please describe.**
We're currently migrating from JWT -> OIDC authentication on the same backend and as such the user claims are the same, currently there is no clear way of migrating existing policies which are mapped to a particular backend to make them accessible via both login methods 

**Describe the solution you'd like**

The ability to define both OIDC & JWT authentication or more to a single group. 

**Describe alternatives you've considered**

- Within the auth backend appending a suffix to user claims to allow them to be unique to vault.

**Explain any additional use-cases**

We have tooling which requires use of the JWT token for CI access and local development workflows which exists before the use of full OIDC, the ability to use the same claims allows an easier migration path and improves our ability to support multiple authentication workflows across the business. 

**Additional context**

**Comment by techs07** [comment]
+1
