### ISSUE TITLE
Vault 1.4.1 ARM on Raspberry Pi 4: Error initializing storage of type raft: cannot allocate memory

### ISSUE THREAD

**Issue by dehuszar** [hashicorp/vault#9026]
**Describe the bug**
I have twice now attempted to run a Vault cluster on Raspberry Pis using Vault's local raft storage.  In both cases, the vault.db file gets to ~1GB in size after a few weeks of running successfully and then the nodes start exploding and eventually won't start.  The first cluster originally started on v1.3.2 using the beta raft implementation.
That cluster had gRPC sync errors that caused the various nodes to pop on and off periodically.  They would not stay on long enough to be able to complete a snapshot, I had to manually list and get secrets out of the secrets mount during the leader node's short lifespan.

This second cluster, I have not attempted to restore any secrets and have focused solely on getting it properly integrated with my consul, nomad, and consul-template agents.  Consul-Template would print out new certs for Consul and Nomad.  Vault would keep it's own certs long-lived to start. I was also printing certs via Vault integration for various Nomad jobs like Prometheus and Traefik who reach into the Consul catalog, or otherwise need a TLS cert generated.

Other than generating the initial PKI and PKI-Int certs (or even just re-importing them) again, the entire configuration is Terraform deployable once the cluster is up in some fashion.

There were probably 24-30 entities generating new certs every day.  No tokens were being issued, I was using the root token to start.

Doesn't seem like a lot of data, but maybe expired certs weren't getting cleared out.  Regardless, once the vault db got to 1GB+, it started failing.  My pis all have 4GB, but I'm wondering whether the internal raft storage raises the minimum RAM requirements?

[Here](https://discuss.hashicorp.com/t/vault-ha-cluster-w-raft-storage-outage-on-armhf-out-of-memory/8837/8) is a link to a discussion on the discuss.hashicorp.com site that goes into some of the details around attempts to triage the problem.

**To Reproduce**
1. If you have three Raspberry Pis, set up a Vault cluster using 1.4.1 w/ internal raft storage and print out a bunch of certs until your vault.db reaches 1GB

**Expected behavior**
My expectations is that whatever was being stored would get compacted and collected such that the database would not get so big, such that it would sink the memory capacity of the hardware.  Prior to reaching this juncture, the cluster was performing just fine.  I could print out EC-formatted certs in half a second.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.4.1
* Vault CLI Version (retrieve with `vault version`): 1.4.1
* Server Operating System/Architecture: Raspian/Debian Buster

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
// server config
// opting for the new vault storage option, and not linking to an external consul cluster
storage "raft" {
  path    = "/opt/vault/"
  node_id = "security1"
}

seal "awskms" {
  access_key = "xxxxxxxxxxxxxxxxxxxx"
  secret_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  region     = "us-east-1"
  kms_key_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_cert_file = "/opt/vault/agent-certs/agent.crt"
  tls_key_file = "/opt/vault/agent-certs/agent.key"
}

// duplicate the contents of the above listener with the resolvable ip address
// of the node to be able to access the ui from the local network
listener "tcp" {
  address     = "192.168.1.129:8200"
  tls_cert_file = "/opt/vault/agent-certs/agent.crt"
  tls_key_file = "/opt/vault/agent-certs/agent.key"
}

api_addr     = "https://localhost:8200"
cluster_addr = "https://192.168.1.129:8201"
disable_mlock = true
ui=true

```

**Additional context**
Attempts to migrate the vault data to my laptop to triage have not gone well.  Vault appears to be, regardless of the -address flags passed into the statement or VAULT_ env vars set, attempting to point back to the original node ip address.  Attempts to disable clustering produce a segfault
```
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by dehuszar** [comment]
Quick update.  I successfully attempted to re-init Vault using the DynamoDB storage engine.  While the agents are able to run longer, they still eventually reach an Out of Memory error.

Moreover, the 16GB SD card I've placed on these Vault agents quickly fill up once Vault runs out of memory and fails resulting in the daemon.log and syslog files climb to 5-10GB before all remaining systems fail.

**Comment by ncabatoff** [comment]
Let's see where that memory is going.  Can you use `vault debug` to generate some heap.prof files (once memory starts filling up) and send them my way?

**Comment by dehuszar** [comment]
Thank you in advance!

[vault-debug-2020-05-27T15-53-12Z.tar.gz](https://github.com/hashicorp/vault/files/4689993/vault-debug-2020-05-27T15-53-12Z.tar.gz)

**Comment by ncabatoff** [comment]
From what I can tell, it looks like the bulk of the memory is being used by the expiration manager.  I believe you said you're mostly using this for PKI right now?  How many certs do you have in Vault?   How many leases?

To count leases you can look at the metric vault.expire.num_leases.  If you don't have metrics set up, send a USR1 signal and look in the logs.

**Comment by ncabatoff** [comment]
Hi @dehuszar,

Based on your discuss post today it sounds like the cluster is behaving normally based on what you're asking it to do, i.e. store an excessive number of PKI certs and leases.  I'm going to close this issue as it doesn't seem like a bug at this point.

**Comment by hookdotnet** [comment]
I don't know about this.. Please I need more enlighten please.

**Comment by dehuszar** [comment]
When I originally filed the bug, I thought that the issue might have been stemming from the ARM build.  But having moved from the 4GB Raspberry Pis to the 8GB pis, things have been pretty quiet since around July.  It appears that all of the offending certificates I describe in the discuss page were generated on December 1st, and are not long ttl certs.

My suspicion is that I screwed up the consul-template workflow and accidentally caused multiple consul-templates to pump out many multiples of the intended certificates.

I'm more than happy to have this closed out while I attempt remediations, but I'm also happy to provide any diagnostics which might be helpful.

Cheers
