### ISSUE TITLE
FS mount/retrieve as file

### ISSUE THREAD

**Issue by strarsis** [hashicorp/vault#903]
Let's say I stored generic secrets in vault, now a configuration file should point to them as files.
HTTP gets/URLs are not supported in that config, it must be a path to a file that can be read.

Ideally, the program could just access vault secrets as they would be on a file system, as files by path.
In any case, are there any patterns recommended?

Rendering the secret using consul-template isn't ideal because it may be a large 
or arbritary number of secrets, also it may be binary content.

Thank you and
with best regards

**Comment by jefferai** [comment]
(Closing due to discussion on IRC.)

**Comment by donaldquixote** [comment]
Can you elaborate on what was discussed on IRC? I saw a similar issue requesting a FUSE fs style interface for Vault. Did this IRC discussion overlap with that issue in any way?

Thanks.

**Comment by jefferai** [comment]
@donaldquixote The short answer is that there are no plans to produce a FUSE or FUSE-like filesystem for Vault, although there's also no reason that an interested third-party could not write such a thing.

It's not even clear what the initial use-case is; Vault is an API and HTTP gets/URLs *must* be supported in order to fetch secrets from it using your token. Having a filesystem abstraction wouldn't change anything except that the network activity might be hidden from the user.

There's nothing that prevents one process from reading a secret from Vault and writing it to the file system (say, in an encrypted ramdisk) for consumption by another process, if that second process can't perform network I/O. If the second process can perform network I/O, it can use Vault directly.

**Comment by strarsis** [comment]
Yes, more or less this was discussed on IRC plus 
usage of perl/lua in nginx config to use HTTP to fetch the files from vault HTTP API.

We got similar issues with consul: Most popular daemons are not consul-aware, 
maybe they shouldn't even be - we need some kind of generic protocol for consul (is it generic enough, can it be swapped out with e.g. Marathon?).
consul-template solves this - it uses the daemon config file as the interface, including a reload/restart command.

Now - couldn't we have the same for vault as consul-template for consul?
vault-file? vault-config?
For the advantages of vault one should be able to use vault everywhere,
all kinds of daemons, programs, apps, etc should be able to use vault secrets.

With best regards

**Comment by jefferai** [comment]
@strarsis You can use `consul-template` to read secrets from Vault and populate them into configuration files.

**Comment by strarsis** [comment]
@jefferai: Yes, this was also discussed in IRC.
This is actually a nice idea and would surely work well with a single file.

However, when I render an option with a path to such a file in a loop in the main config template, 
the number of files is unknown, it depends on the filtered tags or other logic in the consul-template.
There may be 10 lines in the config file, each a path to such a file.
I would need a script from the outside to handle this, more or less it boils down to a consul watch.

**Comment by strarsis** [comment]
- Pull secret directly in consul-template.
Inlining files, e.g. certificate keys, in config file is rarely supported, also there may be binary secrets.
Additionally the config may be readable to all, just the secret (files) should not, this wouldn't be possible either.

- Using a consul-template for (each) secret file
Can't dynamically scale, it has to be a fixed number of secrets and one must know their amount, paths and vault keys in advance.
For each secret file in config one would have to manage a consul-template file plus service entry.

- Using a consul watch and pull + write the secrets to file and run consul-template afterwards
Duplication of  filtering/loops in consul watch that consul-template already uses to get to the same secret file paths as being referenced/rendered in resulting configuration file.

- Is consul-template suited for secrets at all? Are secrets configuration?

- Add a feature to consul that allows writing secret files directly from inside a consul template file?

**Comment by jefferai** [comment]
I don't think everything you put above is correct, especially the generalization of it being rarely supported to keep secrets outside of configuration files, but I also don't know enough about consul-template to really add anything to the conversation. I suggest asking for advice from the consul-template maintainers.
