### ISSUE TITLE
Saving secret failing with " too many open files"  core: barrier init check failed: error="failed to check for initialization: open /opt/vault-0.10.1-x64/data/core: too many open files"

### ISSUE THREAD

**Issue by abhijith-vr** [hashicorp/vault#9040]
Vault Version - 0.10.1
Storage back end - File System (as its staging system)
ulimit -n
60000

Still Vault is giving error , too many open files.Mainly when lot of requests are coming to the server at a point.If we hit single request , "save" apis are successful

May 20 00:36:03 server.add vault[13293]: http: Accept error: accept tcp ip:8200: accept4: too many open files; retrying in 5ms
May 20 00:36:03 server.add vault[13293]: http: Accept error: accept tcp ip:8200: accept4: too many open files; retrying in 10ms
May 20 00:36:03 server.add vault[13293]: http: Accept error: accept tcp ip:8200: accept4: too many open files; retrying in 20ms
May 20 00:36:03 server.add vault[13293]: http: Accept error: accept tcp ip:8200: accept4: too many open files; retrying in 40ms
May 20 00:36:03 server.add vault[13293]: http: Accept error: accept tcp ip:8200: accept4: too many open files; retrying in 80ms
May 20 00:36:03 server.add vault[13293]: http: Accept error: accept tcp ip:8200: accept4: too many open files; retrying in 160ms
May 20 00:36:03 server.add vault[13293]: http: Accept error: accept tcp ip:8200: accept4: too many open files; retrying in 320ms
May 20 00:36:04 server.add vault[13293]: http: Accept error: accept tcp ip:8200: accept4: too many open files; retrying in 5ms
May 20 00:36:04 prometheus.

May 20 00:36:04 server.add vault[13293]: 2020-05-20T00:36:04.301Z [ERROR] core: barrier init check failed: error="failed to check for initialization: open /opt/vault-0.10.1-x64/data/core: too many open files"
May 20 00:36:04 server.add vault[13293]: 2020-05-20T00:36:04.302Z [ERROR] core: error checking health: error="failed to check for initialization: open /opt/vault-0.10.1-x64/data/core: too many open files"
May 20 00:36:04 server.add vault[13293]: http: Accept error: accept tcp ip:8200: accept4: too many open files; retrying in 10ms
May 20 00:36:04 server.add vault[13293]: 2020-05-20T00:36:04.301Z [ERROR] core: barrier init check failed: error="failed to check for initialization: open /opt/vault-0.10.1-x64/data/core: too many open files"
May 20 00:36:04 server.add vault[13293]: 2020-05-20T00:36:04.302Z [ERROR] core: error checking health: error="failed to check for initialization: open /opt/vault-0.10.1-x64/data/core: too many open files"
May 20 00:36:04 server.add vault[13293]: 2020-05-20T00:36:04.302Z [ERROR] core: barrier init check failed: error="failed to check for initialization: open /opt/vault-0.10.1-x64/data/core: too many open files"
May 20 00:36:04 server.add vault[13293]: 2020-05-20T00:36:04.303Z [ERROR] core: error checking health: error="failed to check for initialization: open /opt/vault-0.10.1-x64/data/core: too many open files"
May 20 00:36:04 server.add vault[13293]: 2020-05-20T00:36:04.302Z [ERROR] core: barrier init check failed: error="failed to check for initialization: open /opt/vault-0.10.1-x64/data/core: too many open files"
May 20 00:36:04 server.add vault[13293]: 2020-05-20T00:36:04.303Z [ERROR] core: error checking health: error="failed to check for initialization: open /opt/vault-0.10.1-x64/data/core: too many open files"

**Comment by ncabatoff** [comment]
Hi @abhijith-vr,

You're using a very old version of Vault and should upgrade.  Of course you can still run into this error in a newer version if you're using more file descriptors than your limits allow.  Consider using `lsof` to figure out how they're being used - note that each outstanding connection will use one.

I'm going to close this issue for now because if it does describe a Vault bug, it's probably one we fixed long ago, and this can happen normally without bugs when you don't give Vault enough file descriptors for its needs.  You may be able to find additional guidance on the [forum](https://discuss.hashicorp.com/c/vault/) if need be.
