### ISSUE TITLE
When upgrading to vault 1.4.1 I get metadata issues on token renewal

### ISSUE THREAD

**Issue by fernando-villalba** [hashicorp/vault#9042]
After upgrading to vault 1.4.1 I get metadata issues on token renewal with the following error:

`failed to renew entry: unable to retrieve canonical ARN from metadata during renewal
`
I am configuring Vault with terraform and I have no way to tune the iam_metadata I see on the API (or at least I haven't seen it)

Perhaps the defaults can be amended? Or is there anything I am missing that I need to do to make this work on my end? 

I don't want to have to do configuration outside of terraform to make this work if I can help it as it ruins the point of doing IaC.

If I am doing something wrong about any of this please do let me know. 

I believe the change that caused this is the following: 

https://github.com/hashicorp/vault/pull/8783

**Comment by kalafut** [comment]
Hi. This issue was raised in #8972 and will be fixed soon in the next minor release. In the meantime there are some workarounds described in the [1.4.1 upgrade guide](https://www.vaultproject.io/docs/upgrading/upgrade-to-1.4.1).

**Comment by kalafut** [comment]
Fixed in #8991
