### ISSUE TITLE
Select of algorithms aes128-gcm96, ecdsa-p384, ecdsa-p521 are missed in UI 

### ISSUE THREAD

**Issue by binlab** [hashicorp/vault#9069]
**Describe the bug**

Options `aes128-gcm96`, `ecdsa-p384`, `ecdsa-p521` are missed in selector by UI 

![transit](https://user-images.githubusercontent.com/6697280/82713854-21d6b200-9c95-11ea-9b72-b6df3c56d08d.png)

but declared in documentation https://www.vaultproject.io/docs/secrets/transit

![transit2](https://user-images.githubusercontent.com/6697280/82713856-24d1a280-9c95-11ea-8d1c-3bfab133cf97.png)

**To Reproduce**
1. Open https://example.com/ui/vault/secrets/transit/create
2. Try to select **Type**
3. Open a browser debugger

**Expected behavior**
Supporting all major algorithms

**Environment:**
* Vault Server Version: `1.4.2`
* Server Operating System/Architecture: `linux_amd64`

**Comment by aphorise** [comment]
Closing as all listed algorithms have since been added in the UI - also retested recently in 1.9.x as below

![image](https://user-images.githubusercontent.com/974854/188279160-657d62a1-80e8-4fa5-b898-2a2530aab644.png)

Thanks @binlab for reporting this when did.
