### ISSUE TITLE
SDK module version needs to be updated

### ISSUE THREAD

**Issue by davepgreene** [hashicorp/vault#9072]
**Describe the bug**

The changes in v1.4.2 from #8894 were made without updating the sdk module version. Consequently, programmatic access to anything that imports `physical/raft/raft.go` (pretty much anything) will fail building with the following error:

```
../golang/pkg/mod/github.com/hashicorp/vault@v1.4.2/physical/raft/raft.go:185:20: undefined: tlsutil.LoadClientTLSConfig
```

Note [the diff](https://github.com/hashicorp/vault/compare/v1.4.1...v1.4.2#diff-37aff102a57d3d7b797f152915a6dc16) between v1.4.1 and v1.4.2 in `go.mod` doesn't have any changes to `github.com/hashicorp/vault/sdk` which would be required to include the change in 7b2a85222c254048ee6cfdce127d4d0a5ee50eff.

**To Reproduce**

`go.mod`:
```
module github.com/davepgreene/repro-vault-issue

go 1.13

require github.com/hashicorp/vault v1.4.2
```

`main_test.go`:
```
package main

import (
	"testing"

	"github.com/hashicorp/vault/vault"
)

func TestReproModBuildIssue(t *testing.T) {
	_, _, _ = vault.TestCoreUnsealed(t)
}
```

```
❯ go test
# github.com/hashicorp/vault/physical/raft
../golang/pkg/mod/github.com/hashicorp/vault@v1.4.2/physical/raft/raft.go:185:20: undefined: tlsutil.LoadClientTLSConfig
FAIL	github.com/davepgreene/repro-vault-issue [build failed]
```

**Expected behavior**
The test builds and completes. 

Builds succeed if I use v1.4.1.

**Environment:**
* Vault Server Version (retrieve with `vault status`): N/A
* Vault CLI Version (retrieve with `vault version`): N/A
* Server Operating System/Architecture: macOS 10.15.4

**Comment by davepgreene** [comment]
Pinning SDK to commit 72d69106be0204647826fbedbc1909d59f663b31 resolves the issue.
`go get github.com/hashicorp/vault/sdk@72d69106be0204647826fbedbc1909d59f663b31`

**Comment by dio-trinny** [comment]
@davepgreene 's workaround worked for me, but this isn't a long-term solution!
