### ISSUE TITLE
Ability to generate token and render it in a template using Vault Agent

### ISSUE THREAD

**Issue by Is0MerLNtaLt** [hashicorp/vault#9074]
Right now there is no way to render a token to template using Vault Agent. Use case would be to get a token for Nomad to use. Using the existing `secret` function doesn't work either as mentioned in this Consul Template [issue](https://github.com/hashicorp/consul-template/issues/1222).

### Proposed solution
Adding a function similar to the `secret` function with usage like:
```
{{with token "/auth/token/create" "policy=somepolicy"}}{{ .auth.client_token }}{{ end }}
```

**Comment by F21** [comment]
This seems to be possible already using the `secret` function. I tested using Vault Agent 1.13.0 to create child tokens:

```hcl
{{with secret "/auth/token/create" "token_policies=mypolicy"}}
token: {{.Auth.ClientToken}}
{{ end }}
```

To create a token without passing in any parameters, just use `""` to force a write:
```hcl
{{with secret "/auth/token/create" ""}}
token: {{.Auth.ClientToken}}
{{ end }}
```

**Comment by VioletHynes** [comment]
@Is0MerLNtaLt can you confirm if the above approach works for you? I found this issue and the approach listed above definitely works, I've used it before successfully too. I don't think we need any new feature for this:

```
template {
	contents = "{{ with secret \"/auth/token/create-orphan\" \"policies=default\" \"ttl=10s\" \"explicit_max_ttl=25s\"}}{{.Auth.ClientToken}}{{ end }}"
	destination = "%s"
	error_on_missing_key = true
}
```

**Comment by VioletHynes** [comment]
I'm going to close this, as this functionality exists in Vault Agent today (see my above comment as an example).
