### ISSUE TITLE
Encryption "dropbox" for userpass accounts

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/vault#910]
It would be nice if there was a way to allow each account in `userpass` (or even ldap if possible) to have an encryption "dropbox" type key. I am thinking of something that is a bit of a combination of the `transit` (so anyone can encrypt) and `cubbyhole` (so only the intended recipient can decrypt) secret backends.

The scenario we're looking to solve is when "jane" wants to send "mike" a secret. e.g., mike's new account & password in XYZ application.

Jane could run `echo "some super secret thing" | base64 | vault write dropbox/encrypt/mike plaintext=-` to encrypt the secret.
Mike would then run `echo "vault:v1:blahblahblah" | vault write dropbox/decrypt/mike ciphertext=-` to decrypt it and get his credentials.

Yes, a new `transit` key could be created for each user and an acl created for each one but that is time consuming and difficult to manage. Also if we were to use the transit backend anyone with the `sudo` policy or `root` token could still decrypt the value.

**Comment by jefferai** [comment]
This kind of thing may be able to be supported in the future, but it's a ways off if so. Eventually we want to get to a notion of users, rather than simply tokens, and have this information be able to be provided by configured sources regardless of authentication method. Once that's in place (but it's a ways off), something like this may be possible.

There may be some kind of middle ground that could come earlier if someone is interested in writing it, where e.g. user A can give access to a value for user B by using a SHA256 sum of user B's vault token value.

**Comment by mtougeron** [comment]
No worries about it being a future thing. We are okay for now with using the `transit` backend for now but our Sec Ops/Compliance team would prefer that we lock it down a bit more. :)

**Comment by jefferai** [comment]
If your two users can pass a value back and forth, you could use `cubbyhole` for something like this:

* User A uses token A to create a new token Z using their Vault token. So long as they do not have `sudo` to the token creation path, they cannot create a token that gives more access than the parent -- but they can create a token with no policies other than the default, effectively (depending on what's in your `default` policy) making a token that can't be used for anything except cubbyhole access.
* User A writes a value into token Z's cubbyhole.
* User A gives token Z's value to user B.
* User B retrieves the value from token Z's cubbyhole
* User B lets token Z expire, or calls `revoke-self` on it.

**Comment by mtougeron** [comment]
What perms would User A need to create a new token? I thought that User A would need to have `sudo` in order to create a new token, even if that token had <= the same perms?

**Comment by jefferai** [comment]
As of Vault 0.4, User A simply needs write permissions on `auth/token/create`. `sudo` is only needed if they want to create a token that is an orphan, has a specific ID, or that has a set of policies outside of a subset of their own.

**Comment by mtougeron** [comment]
Excellent! I'm planning on upgrading to 0.4 next week so I'll test it out then.

**Comment by jefferai** [comment]
Did you get a chance to try this out? If so, how's it working for you?

**Comment by mtougeron** [comment]
Yes, the create-token approach works. There's been a few mixups by people, but it works. :)

**Comment by jefferai** [comment]
Neat! One other thing I thought of: you could create a token for shared cubbyhole access, then embed that into the metadata of other tokens that you create, so they can look up their own token metadata to get the value rather than having to pass it in some other way.
