### ISSUE TITLE
Vault becomes sealed after successful auto-unsealing 

### ISSUE THREAD

**Issue by eudalov** [hashicorp/vault#9115]
**Describe the bug**
We have Vault HA installation (2 nodes). It has Consul as storage backend. Auto unseal via AWS KMS is set up. But the problem is that Vault initially becomes unsealed successfully when restarted and then (in ~1.5 min) gets  the sealed state back again. 

**Expected behavior**
The Vault keeps unsealed state after it started and became auto-unsealed via AWS KMS.

**Environment:**
* Vault Server Version (retrieve with `vault status`): `1.1.0`
* Vault CLI Version (retrieve with `vault version`): `Vault v1.1.0 ('36aa8c8dd1936e10ebd7a4c1d412ae0e6f7900bd')`
* Consul Version (`consul version`): `Consul v1.3.1`
* Server Operating System/Architecture:
```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2079.3.0
VERSION_ID=2079.3.0
BUILD_ID=2019-04-22-2119
PRETTY_NAME="Container Linux by CoreOS 2079.3.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```

Vault server configuration file(s):

```hcl
storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault/"
  token   = "aaaabbbb-9431-15c8-200a-qqqqwwwweeee"
}

# disable tls locally (consul template will drop ssl cert and global listener)
listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = 1
}

seal "awskms" {
  region = "us-east-1"
  kms_key_id = "aaaabbbb-580c-490c-adc8-aaaabbbbcccc"
}

ui = true
log_level = "Trace"
```

Vault agent config:
```hcl
auto_auth {
  method "aws" {
    mount_path = "auth/aws"
    config = {
      type = "iam"
      role = "vault-role"
    }
  }

  sink "file" {
    config = {
      path = "/dev/shm/vault-role.token"
    }
  }
}
```

Consul config
```hcl
server = false
advertise_addr = "{{ GetInterfaceIP \"eth0\" }}"
bind_addr = "0.0.0.0"
retry_join = ["provider=aws tag_key=aws:cloudformation:stack-name tag_value=consul-production-HashiCorpConsulStack-1X808MWPXBUUO"]
encrypt = "PBViuAEKvf08+123456789=="

datacenter = "dc1"

/* CONSUL >= 1.4.0
primary_datacenter = "dc1"
acl {
  enabled = true
  default_policy = "deny"
  down_policy = "extend-cache"
  tokens {
    default = "AAAACCCC-6EAA-0000-9151-111122223333"
  }
}
// */

/* CONSUL < 1.4.0 >= 1.0.0 */
acl_default_policy = "deny"
acl_down_policy = "extend-cache"
acl_token = "AAAACCCC-6EAA-0000-9151-111122223333"
// */

data_dir = "/opt/consul/data"

disable_remote_exec = true
recursors = ["172.16.0.2"]

// ssl
verify_incoming = true
verify_outgoing = true
verify_server_hostname = false
ca_file = "/opt/consul/ssl/root-ca.cert"
cert_file = "/opt/consul/ssl/consul.cert"
key_file = "/opt/consul/ssl/consul.key"

// dns
ports {
  dns = 53
}
recursors = ["172.16.0.2"]
```

**Additional context**
[Vault server log](https://github.com/hashicorp/vault/files/4713709/Vault.server.log)

[Consul log](https://github.com/hashicorp/vault/files/4713712/Consul.log) (ip addresses are substituted with placeholders)

[Vault agent log](https://github.com/hashicorp/vault/files/4713713/Vault.agent.log)

**Comment by ncabatoff** [comment]
Hi @eudalov,

Thanks for reporting this issue.  It doesn't look like a bug however: we can see in the Vault server log that there is something wrong with your storage ("failed to read policy: decryption failed: cipher: message authentication failed").  Somehow you have data in Consul under Vault's storage path which wasn't encrypted using a key in your keyring.  But not all data, as we can see that leases are being loaded successfully.  I don't know what went wrong here, but I think the appropriate forum to discuss it is the mailing list or our forum.  I see you already started a discussion there, so I'm going to close this issue.
