### ISSUE TITLE
Migrating Vault v1.4.2 from etcd to raft fails (operator migrate)

### ISSUE THREAD

**Issue by goozbach** [hashicorp/vault#9117]
**Describe the bug**
Trying to migrate Vault storage from etcd to raft fails with the following error:

```Error migrating: error mounting 'storage_destination': could not start clustered storage: Empty address in configuration: {Voter vault0 }```

**To Reproduce**
1. Init, unseal and add secret to new vault instance using etcd as the backend with the attached  `config.json`
2. Attempt to migrate to raft backend using the attached migration config (tried both `migrate.json` and `migrate.hcl`)

**Expected behavior**
Migration of backend storage should commence.

**Environment:**
* Vault Server Version v1.4.2
* Vault CLI Version v1.4.2
* Server Operating System/Architecture: `vault:latest` (v1.4.2) container image from dockerhub

Vault server configuration file(s): attached

**Additional context**
When I do an init with the attached `raft.json` the server inits properly and I'm able to use it.
The migration is the only thing which is breaking

[config.json.txt](https://github.com/hashicorp/vault/files/4714064/config.json.txt)
[migrate.hcl.txt](https://github.com/hashicorp/vault/files/4714065/migrate.hcl.txt)
[migrate.json.txt](https://github.com/hashicorp/vault/files/4714066/migrate.json.txt)
[raft.json.txt](https://github.com/hashicorp/vault/files/4714068/raft.json.txt)

**Comment by goozbach** [comment]
Additional context: I migrated from etcd to consul, and then tried to migrate from consul to raft.

Same result, migration failed with the following error:

    Error migrating: error mounting 'storage_destination': could not start clustered storage: Empty address in configuration: {Voter vault0 }

**Comment by phannam1412** [comment]
same issue here, start a clean Vault enterprise 1.5.3 in new docker container with command `vault server -config config.hcl`,  

**config.hcl:**

```
log_level = "debug"

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = "true"
}

ui = "true"

storage "raft" {
  path = "/vault/data"
}
cluster_addr = "vault-enterprise-instance1:8201"
api_addr = "vault-enterprise-instance1:8200"
```

**Comment by aphorise** [comment]
There's been some major changes in with the last support for etcd2 at 1.9.x and recent editions now only have etcd3 support. In the latest editions when I have tested these it's worked fine.

Hey @goozbach I'm curious if you've retried this recently or how relevant it is for you still?

**Comment by aphorise** [comment]
Closing as there's been no follow-up. Please re-open if still relevant.

**Comment by dpedu** [comment]
I came across this issue because I was hitting the same error message. In my case it was because I omitted the `http://` prefix in the `cluster_addr` option in `migrate.hcl`. Your uploaded configs seem to have `http:/vault0:8201` - a typo. Problems with this prefix seem to be the reason for this error.
