### ISSUE TITLE
JWT auth backend?

### ISSUE THREAD

**Issue by donaldquixote** [hashicorp/vault#913]
I see that a JWT secret backend was implemented then shortly after dropped. But what about an auth backend? It seems reasonable and generic enough to say a user is authenticated if:
1. The token is from a trusted issuer
2. The token signature, expiration, etc is validated
3. The token contains claims that match auth backend configuration for key and value

Then, a claim configured through the auth backend is used to determine the authenticating user.

My use case:
Our microservice architecture uses JWT tokens with a tenant id claim as authorization tokens. It would be nice if any bearer of such a token could read or write secrets for the specified tenant. I could see our own services passing the caller's token directly to Vault to retrieve a secret for, say, retrieving a db user password for the tenant's data.

**Comment by jefferai** [comment]
@donaldquixote There's certainly nothing wrong with the concept, but it is not on our internal roadmap at the moment.

**Comment by ivan-padabed** [comment]
@jefferai any workarounds or recommended approach for that scenario, better aligned with your roadmap?

**Comment by jefferai** [comment]
There's a proposal; see #1986

**Comment by donaldquixote** [comment]
I only skimmed the proposal briefly, but it appears to be for a _secret_ backend, not an _auth_ backend. It may be premature to close this issue down without a replacing issue whose top-level consideration is a JOSE _auth_ backend. Am I missing something?

**Comment by jefferai** [comment]
No, I missed that this was for an auth backend :-)

**Comment by Danli741** [comment]
confront the same use case as @donaldquixote. Will this feature be supported or any plan?

**Comment by jefferai** [comment]
Auth plugins are on the roadmap which will make it very easy for this to be developed by any interested party. JWT in a specific sense is not currently supported.

**Comment by Rick-OS** [comment]
Has anyone looked at developing this as an auth plugin yet? Would be a great feature to see

**Comment by jefferai** [comment]
Closing in favor of https://github.com/hashicorp/vault/issues/2525#issuecomment-369718031
