### ISSUE TITLE
Kubernetes Service Registration doesn't recognize DynamoDB as HA storage  

### ISSUE THREAD

**Issue by iusergii** [hashicorp/vault#9153]
**Describe the bug**
My Vault Server deployed to Kubernetes and I use AWS DynamoDB as storage for Vault Server. After adding `service_registration` configuration stanza and perform an upgrade to 1.4.0 service failed to start with error:
```
service_registration is configured, but storage does not support HA
```

**Expected behavior**
Vault starts and applies labels to pods in Kubernetes as described in [docs](https://www.vaultproject.io/docs/configuration/service-registration/kubernetes#vault_k8s_namespace)

**Environment:**
* Vault Server Version: 1.4.0
* Vault CLI Version: 1.4.0
* Server Operating System/Architecture: Kubernetes

Vault server configuration file(s):

```hcl
disable_mlock = true
cluster_name = "vault-tst.com"
ui = true

listener "tcp" {
  tls_disable = 1
  address = "[::]:8200"
  cluster_address = "[::]:8201"
}

storage "dynamodb" {
  ha_enabled = 1
  table = "vault-tst"
}

service_registration "kubernetes" {}
```

**Comment by tvoran** [comment]
Have you tried setting `ha_enabled = "true"` instead of 1?

**Comment by iusergii** [comment]
Thank you @tvoran, that helped! Closing.
