### ISSUE TITLE
[Feature request] Export only the public key for asymmetric cryptography in Vault Transit 

### ISSUE THREAD

**Issue by fungiboletus** [hashicorp/vault#9159]
**Is your feature request related to a problem? Please describe.**
I would like to sign documents using Hashicorp Vault Transit and keep the private keys in the Vault. However I would like everyone to be able to verify the signatures using the public key, not necessarily using the Vault.

**Describe the solution you'd like**

An option in the `/transit/export` or a new API to export the public key and not the private key.

**Describe alternatives you've considered**

I can export the private key and generate the public key, and then remove the private key. It works but it means my private key has left the vault with all the security concerns it can have.

**Comment by clkamp** [comment]
You can already get the public key from the transit/key/:name endpoint in the field, data.keys[].public_key (at least for rsa keys)

**Comment by fungiboletus** [comment]
Indeed.
