### ISSUE TITLE
SSH connections are not closed

### ISSUE THREAD

**Issue by wikiwi** [hashicorp/vault#916]
I am using the ssh dynamic role type with a custom install script on CoreOS. My custom install script runs fine without problems, and vault ssh works fine too. But every time a key is requested, 3 SSH connections are opened. Every time a key is revoked, again 3 SSH connections are opened. Running vault ssh results in 6 additional opened SSH connections. The ssh connections keeps piling up until ssh refuses to accept any new connections.

It doesn't seem to be related to my custom install script nor CoreOS.
Anyone experiencing the same issue? 

```
systemctl status
             │ ├─sshd@20-172.17.9.101:22-172.18.0.9:46246.service
             │ │ ├─11092 sshd: vaultadmin [priv
             │ │ └─11094 sshd: vaultadmin@nott
             │ ├─sshd@36-172.17.9.101:22-172.18.0.9:46360.service
             │ │ ├─11932 sshd: vaultadmin [priv
             │ │ └─11934 sshd: vaultadmin@nott
             │ ├─sshd@21-172.17.9.101:22-172.18.0.9:46248.service
             │ │ ├─11097 sshd: vaultadmin [priv
             │ │ └─11099 sshd: vaultadmin@nott
             │ ├─sshd@12-172.17.9.101:22-172.18.0.9:46220.service
             │ │ ├─10881 sshd: vaultadmin [priv
             │ │ └─10883 sshd: vaultadmin@nott
             │ ├─sshd@19-172.17.9.101:22-172.18.0.9:46244.service
             │ │ ├─11088 sshd: vaultadmin [priv
             │ │ └─11090 sshd: vaultadmin@nott
             │ ├─sshd@13-172.17.9.101:22-172.18.0.9:46222.service
             │ │ ├─10886 sshd: vaultadmin [priv
             │ │ └─10895 sshd: vaultadmin@nott
             │ ├─sshd@14-172.17.9.101:22-172.18.0.9:46224.service
             │ │ ├─10897 sshd: vaultadmin [priv
             │ │ └─10899 sshd: vaultadmin@nott
             │ ├─sshd@31-172.17.9.101:22-172.18.0.9:46342.service
             │ │ ├─11888 sshd: vaultadmin [priv
             │ │ └─11890 sshd: vaultadmin@nott
             │ ├─sshd@38-172.17.9.101:22-172.18.0.9:46366.service
             │ │ ├─11993 sshd: vaultadmin [priv
             │ │ └─11995 sshd: vaultadmin@nott
             │ ├─sshd@32-172.17.9.101:22-172.18.0.9:46344.service
             │ │ ├─11892 sshd: vaultadmin [priv
             │ │ └─11894 sshd: vaultadmin@nott
             │ ├─sshd@39-172.17.9.101:22-172.18.0.9:46368.service
             │ │ ├─11997 sshd: vaultadmin [priv
             │ │ └─11999 sshd: vaultadmin@nott
             │ ├─sshd@33-172.17.9.101:22-172.18.0.9:46346.service
             │ │ ├─11896 sshd: vaultadmin [priv
             │ │ └─11898 sshd: vaultadmin@nott
```

**Comment by jefferai** [comment]
Any chance you can try with `master`? This may be related to a bug we found with connection handling in Vault so may already be fixed. It would be good to know either way.

**Comment by wikiwi** [comment]
I tried it on master already, same issue.

**Comment by jefferai** [comment]
Hi @wikiwi 

I just set up a test to reproduce it, but can't. I'm on Ubuntu connecting to another Ubuntu box (but which is also running systemd as it's 15.10).

When I use "vault ssh" to connect to a host, I do see an entry show up:
```

             │ │ ├─ 33606 vault server -config=config.hcl
             │ │ ├─ 35344 su - vault-ssh
             │ │ ├─ 36609 watch systemctl status | grep vault
             │ │ ├─ 37379 vault ssh -role dynamic_dev vault-ssh@127.0.0.1
             │ │ ├─ 37531 ssh -i vault_ssh_vault-ssh_127.0.0.1 -p 22 vault-ssh@127.0.0.1
             │ │ ├─ 37616 watch systemctl status | grep vault
             │ │ ├─ 37617 sh -c systemctl status | grep vault
             │ │ ├─ 37619 grep vault
               │ ├─37532 sshd: vault-ssh [priv
               │ ├─37575 sshd: vault-ssh@pts/
```
But, when I log out from that interactive terminal, it goes away:
```
               │ ├─ 33606 vault server -config=config.hcl
               │ ├─ 35344 su - vault-ssh
               │ ├─ 36609 watch systemctl status | grep vault
               │ ├─ 37964 watch systemctl status | grep vault
               │ ├─ 37965 sh -c systemctl status | grep vault
               │ ├─ 37967 grep vault
```
My guess at this point is that it is either related to the configuration of SSH in CoreOS, or that it has something to do with your custom install script. Any chance you can post those?

For reference, my `sshd_config` is as follows (and I am using Vault's default install script):
```
Port 22
Protocol 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
UsePrivilegeSeparation yes
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin without-password
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes
```
I don't see anything in there related to killing idle connections, but my guess is that one of two things is happening:

1. Your install script never actually terminates, so the SSH connection launched to manage SSH keys on the client never closes
2. Some configuration aspect of CoreOS's ssh client or daemon config is causing it to not clean up connections that have closed.

**Comment by wikiwi** [comment]
I'll dive deeper into this issue this week and report my findings.

**Comment by jefferai** [comment]
Great. I definitely want to know what you find!

**Comment by wikiwi** [comment]
Just ran a clean CoreOS stable 835.9.0 and Vault (4.0 and master) install and the same issue occurs. The ssh connections doesn't even seem to timeout. CoreOS uses systemd socket activation for ssh. I wonder if that causes the problem. I haven't looked into the relevant Vault source code yet.

Here is the CoreOS ssh default config script:
```
# Use most defaults for sshd configuration.
UsePrivilegeSeparation sandbox
Subsystem sftp internal-sftp
ClientAliveInterval 180
UseDNS no
```

The sshd@service file is:
```
[Unit]
Description=OpenSSH per-connection server daemon
After=syslog.target auditd.service

[Service]
ExecStart=-/usr/sbin/sshd -i -e
StandardInput=socket
StandardError=syslog
```

Here is my install script. I have verified that it runs successfully till the end and therefore should terminate:
```
#!/bin/bash
set -euo pipefail
# Storing arguments into variables, to increase readability of the script.
INSTALL_OPTION=$1
PUBLIC_KEY_FILE=$2
AUTH_KEYS_FILE=$3
TARGET_USER=$(printf "${AUTH_KEYS_FILE}" | awk -F / '{ print $3 }')
HASH=$(md5sum "${PUBLIC_KEY_FILE}" | awk '{ print $1 }')

# Delete the public key file and the temporary file
function cleanup
{
  rm -f "${PUBLIC_KEY_FILE}"
}
# 'cleanup' will be called if the script ends or if any command fails.
trap cleanup EXIT
# Return if the option is anything other than 'install' or 'uninstall'.
if [ "${INSTALL_OPTION}" != "install" ] && [ "${INSTALL_OPTION}" != "uninstall" ]; then
  exit 1
fi

if [ "${INSTALL_OPTION}" == "install" ]; then
  # this terminates the public key file correctly.
  echo >> "${PUBLIC_KEY_FILE}"
  sudo /usr/bin/update-ssh-keys -u "${TARGET_USER}" -a "vault_${HASH}" "${PUBLIC_KEY_FILE}"
else
  sudo /usr/bin/update-ssh-keys -u "${TARGET_USER}" -d "vault_${HASH}" || true
fi
```

**Comment by wikiwi** [comment]
I tried using @jefferai sshd_config. It didn't solve the problem.

**Comment by jefferai** [comment]
Any change if you use the stock script rather than your custom version?

**Comment by jefferai** [comment]
Also, if you want to try using SSH as a service rather than socket-activated (which some Googling shows people have had trouble with in the past), I *think* this should do it -- as long as CoreOS actually ships with the SSH service unit file as well:
```
systemctl disable ssh.socket
systemctl enable ssh.service
```
If that works in CoreOS it might be good to give that a try and see if that change the behavior.

**Comment by wikiwi** [comment]
I think I located the bug being in the go source code of Vault. The connection doesn't seem to be closed by Vault. Working on a PR.

**Comment by jefferai** [comment]
Can you point me towards where you think the issue is?

**Comment by jefferai** [comment]
As a follow-up to my previous comment: when you built `master`, did you build it using `make dev` or did you just pull and go a `go install`?

**Comment by wikiwi** [comment]
I use godep style to build:

```
#/bin/bash
export GOPATH=$(pwd)/src/github.com/hashicorp/vault/Godeps/_workspace:$(pwd):$GOPATH
go build github.com/hashicorp/vault
```

Yes I can point it out for you.

The connection created here is never closed after usage:
https://github.com/hashicorp/vault/blob/master/builtin/logical/ssh/communicator.go#L105

I have fixed this locally, and 2 out of the 3 connections, were closed. 

Still one connection remaining and the issue seems to be here:
https://github.com/hashicorp/vault/blob/master/builtin/logical/ssh/util.go#L45

The client and its underlying connection here are never closed too.

**Comment by wikiwi** [comment]
Submitted PR that solves this issue. I needed to do a tiny bit of refractoring. With that, only the ssh communicator is responsible for connecting to the server and only 1 connection is needed instead of 3. No traces of open connections in my logs any more :-)

If the PR needs adjustments, I'm ready to help.

Btw. feel free to publish my custom install script for CoreOS. The stock install script doesn't work properly as all changes in CoreOS needs to go through `/usr/bin/update-ssh-keys`.

**Comment by jefferai** [comment]
I'll take a look. BTW, you can make your build process simpler by using `godep go build` or `make dev`, which basically does that.

**Comment by jefferai** [comment]
(removing this from the milestone as I've added the PR to it)
