### ISSUE TITLE
Consul Secret Engine without Consul Storage: "401 (ACL support disabled)"

### ISSUE THREAD

**Issue by Legogris** [hashicorp/vault#9164]
**Describe the bug**

Having some issues configuring the Consul Secrets Engine with Vault.

Consul Storage Backend is not configured (using Raft Storage). Consul is, however, configured for service registration, which works fine using the same local agent at `127.0.0.1:8500`.

Policies and roles are configured according to [docs](https://www.vaultproject.io/docs/secrets/consul). Same result when configuring the secrets engine with the bootstrap token.

Using the same approach was successful in a separate environment, the only two notable differences being the mount-point of the engine (`consul_nomad` instead of just `consul`) and storage.

```
$ vault read consul_nomad/roles/test
Key           Value
---           -----
lease         0
local         false
max_ttl       0s
policies      [test]
token_type    client
ttl           0s

$ consul acl policy read -name=test
ID:           abc-abc-abc-abc
Name:         test
Description:  test
Datacenters:
Rules:
key_prefix "test/" {
  policy = "write"
}
```

However,

```
$ curl -H "X-Vault-Token: $VAULT_ROOT_TOKEN" https://vault:8200/v1/consul_nomad/creds/test
{"errors":["Unexpected response code: 401 (ACL support disabled)"]}
```

All Consul clients and servers have datacenter and primary_datacenter set.
Nothing showing up in either consul (local agent or consul servers) or vault logs.

Vault version `1.4.1`
Consul version `1.7.3`

**Expected behavior**
` curl -H "X-Vault-Token: $VAULT_ROOT_TOKEN" https://vault:8200/v1/consul_nomad/creds/test` returns valid Consul token

**Environment:**
* Vault Server Version: 1.4.1
* Vault CLI Version: v1.4.1
* Server Operating System/Architecture: Ubuntu Server 18.04 LTS x86_64

Vault server configuration file(s):

```hcl
service_registration "consul" {
  address = "127.0.0.1:8500"
  token   = "abc-def-abc-def"
}

storage "raft" {
  node_id                = "vault-alpha"
  path                   = "/var/vault"
  performance_multiplier = "1"

  retry_join {
    ...
  }
}

service_registration "consul" {
  address = "127.0.0.1:8500"
  token   = "1234-5678-1234-5678"
}

ui = true
log_level = "Debug"
```

Consul agent config on vault node:

```

acl {
  tokens {
    agent        = "xxx"
    agent_master = "yyy"
    default      = "zzz"
  }
}
addresses {
  dns   = "127.0.0.1"
  http  = "127.0.0.1"
  https = "127.0.0.1"
 grpc  = "127.0.0.1"
}

primary_datacenter = "my_dc"
datacenter               = "my_dc"
server                      = false
verify_incoming        = true
verify_outgoing        = true
verify_server_hostname = true
encrypt               = "xxx"
key_file               = "xxx"
ca_file                 = "xxx"
cert_file               = "xxx"

bind_addr               = "192.168.1.101"
client_addr             = "127.0.0.1 192.168.1.101"

ports {
  grpc     = -1
  http     = 8500
  https    = 8501
  serf_wan = -1
}
```

**Comment by ncabatoff** [comment]
Hi @Legogris,

You mention that these are different environments: I'm guessing that means these are different Consul clusters.  Is it possible that the Consul cluster referenced in your new mount was never bootstrapped for ACLs?  That's how I interpret the error message.

**Comment by Legogris** [comment]
> Hi @Legogris,
> 
> You mention that these are different environments: I'm guessing that means these are different Consul clusters. Is it possible that the Consul cluster referenced in your new mount was never bootstrapped for ACLs? That's how I interpret the error message.

These two environment have nothing to do with each other; just mentioned it to highlight I've gone through the same procedure successfully before.

The Consul cluster in question is otherwise healthy and the same Vault deployment uses it for service registration successfully. (Also used by other Nomad and other services, all with ACLs).

**Comment by ncabatoff** [comment]
> The Consul cluster in question is otherwise healthy and the same Vault deployment uses it for service registration successfully. 

Service registration is orthogonal to ACLs so that's no surprise.  What's different about the Consul secrets engine is that it actually has to use the Consul ACL API.

> (Also used by other Nomad and other services, all with ACLs).

It may be that Nomad and those other services are providing a Consul token which is being ignored by Consul because ACLs haven't been bootstrapped.

The phrase "ACL support disabled" does not occur in the Vault codebase, but does within Consul's:

```
	const errDisabled         = "ACL support disabled"
```

```
	// ErrDisabled is returned when ACL changes are not permitted since
	// they are disabled.
	ErrDisabled = errors.New(errDisabled)
```

**Comment by Legogris** [comment]
That sounds very strange. Service registration requires ACL permissions once successfully bootstrapped, which would otherwise be a security issue, no? (Vault is here configured to use an ACL token with write permissions to the `vault` service) 

But you mentioning that makes me realize something is definitely wrong not with Vault itself (I guess this issue should be closed) but with the Consul agent on the Vault instance.

Running `consul members -detailed` shows `acls=1` on all the Consul servers, but `acls=0` on the clients (Nomad, Vault, etc). Still, attempting to accessing the API using ACL tokens with insufficient permissions denies access, as expected.

Looks like there's some digging to do on the Consul side. Thanks for pointing me in the right direction!

**Comment by praveenprem** [comment]
I'm also running into this issue trying to set up ACLs with Consul, did you manage to find the solution for this?

I don't see any errors being logged by the Vault server or Consul server.
```
$ vault read consul/roles/consul-client-role
Key                 Value
---                 -----
consul_namespace    n/a
consul_policies     [consul-clients]
lease               0
local               false
max_ttl             0s
node_identities     [ip-172-18-100-19:dc1]
partition           n/a
token_type          client
ttl                 0s
```

I was following the [Administer Consul access control tokens with Vault](https://developer.hashicorp.com/consul/tutorials/operate-consul/vault-consul-secrets#obtain-and-test-a-consul-acl-token) guide when I ran into this issue
