### ISSUE TITLE
Vault data directory is using a large amount of inodes

### ISSUE THREAD

**Issue by bigmyx** [hashicorp/vault#917]
Hi there!
We are using Vault `file` data backend.
We stored a several secrets there, created a tokens with `vault token-create -lease=20000h -policy=my-policy` command.
We are reading those secrets via REST API automatically.
Recently we have noticed a high usage of FS inodes by the data directory: 
`find /opt/vault/data/ -type f  | wc -l`
`280828`
We are using Vault v0.1.2
Question: is that possible to "clean" that directory somehow? i.e. remove old archive data, etc.
May be it is possible to export the data like tokens and secrets and import it on the new server?
If yes, will the same be possible if the new server will have the latest version?
Thanks!

**Comment by jefferai** [comment]
What is probably happening is that you are reading from a `generic` backend very often. Pre-0.3, reads from a generic backend with a `lease`/`ttl` set would result in lease generation. The idea was that you would use that as a hint for how often to read, but in many cases that's not what people did, with the end result that there are a huge number of leases floating around.

The best way to deal with this, if that's indeed the issue, is for you to upgrade to 0.4 (plus, fixed security issues, many security enhancements, etc.). Over time, as those leases expire, your file count will go down.

**Comment by bigmyx** [comment]
Thanks Jeff!
Shall upgrade from Vault v0.1.2 to the latest stable one have any issues?
Specifically, will the current vault storage be compatible with the new version?
If not, what is the recommended upgrade path?
Thanks!

**Comment by jefferai** [comment]
Hi @bigmyx ,

You should read the upgrade details between the versions at https://hashicorp.com/blog/vault-0-2.html , https://hashicorp.com/blog/vault-0.3.html , and https://hashicorp.com/blog/vault-0.4.html. There are some incompatible changes you need to be aware of, even though the physical storage should (I believe) not be incompatible. Take a backup, of course :-)

Generally speaking I highly recommend staying relatively current with Vault. It's still a young project and we're constantly fixing issues and enhancing security.

**Comment by bigmyx** [comment]
After upgrading vault, we got this error:
`Error checking seal status: Get https://vault.corp.dropbox.com:8200/v1/sys/seal-status: x509: certificate signed by unknown authority`

our config file looks like this:
```
disable_mlock = true

backend "file" {
  path="/opt/vault/data"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  # disable_mlock = 1
  # tls_disable = 1
  tls_enable = 1
  tls_cert_file = "/etc/ssl/private/vault.pem"
  tls_key_file = "/etc/ssl/private/vault.pem"
}
```
`vault.pem` chain file was working perfectly before ..

Please help.

Thanks!

**Comment by jefferai** [comment]
Where are you seeing these errors -- in the Vault log? Are you using the Vault client? HTTP interface?

**Comment by bigmyx** [comment]
I am using the Vault client and see those in the console.
The Vault client also was upgraded to the same version.
Our scripts are using the `curl` command to fetch the secrets: 
`curl -s --cacert  /etc/ssl/private/vault.pem  --header 'Cookie: token=xxx-xxx-xxx-xxxx' http://vault.example.com:8200/v1/secret/`

**Comment by jefferai** [comment]
For the client, are you using the `-ca-cert` or `-ca-path` parameters with the client to specify your internal CA?

For `curl`, the header is `X-Vault-Token`, not `Cookie`. See the [upgrade details for 0.3](https://hashicorp.com/blog/vault-0.3.html).

**Comment by bigmyx** [comment]
Jeff,
I did not use either `-ca-cert` or `-ca-path` for the new client (may be thats the reason for an error).
Also, thanks for pointing out the header vs. cookie issue (will change that).
One issue left unclear is: `missing client token` error with the Vault client when we have disabled the SSL. As I mentioned we used exactly the same token as before.
Appreciate your help!

**Comment by jefferai** [comment]
If your internal CA is installed in the default (OS-dependent) location, the Vault client should access it automatically -- if you do not explicitly provide a CA cert or path, it falls back to your system certs. The best thing would be to try using `-ca-cert` and/or `-ca-path` - if that fixes that problem for you, then it means that you just need to get the CA certs installed in your system default location. (Alternately you can use the environment variables `VAULT_CACERT` or `VAULT_CAPATH` to set it in your shell init scripts.)

As for the `missing client token` error, you do need to provide the client with a Vault token. You can either put it in `~/.vault-token`; have Vault put it in there for you by doing `vault auth <token>` -- but this requires Vault being unsealed, I think; or, put the value in the VAULT_TOKEN environment variable. If you don't have a token either in the `VAULT_TOKEN` env var or in `~/.vault-token` then the client won't have a value to provide to the API.

**Comment by bigmyx** [comment]
I did 'vault auth' command , previously unsealed the vault with 3 unseal
keys.

**Comment by jefferai** [comment]
@bigmyx Check your env var and ~/.vault-token anyways...the client can clear out ~/.vault-token after a time.

Also, please check that you're using the right (updated) client, because if you're using the old client by accident (say, a path issue), it would cause this behavior.

**Comment by bigmyx** [comment]
Thank you for helpful guidelines!
You can close this Issue.

**Comment by jefferai** [comment]
Glad to help... let me know if you have more issues!
