### ISSUE TITLE
Vault Status Command Differs Depending on Format

### ISSUE THREAD

**Issue by jamiegwatkin** [hashicorp/vault#9185]
**Describe the bug**
The output of `vault status` differs depending on the format selected.

For instance, `vault status -format=table` has the following HA output:
```
HA Enabled               true
HA Cluster               https://10.10.99.20:8201
HA Mode                  active
```

However those three keys are missing form `vault status -format=json`.

**To Reproduce**
1. Execute `vault status -format=json`
2. Execute `vault status -format=table`
3. Notice how the key and value pairs are not the same

**Expected behavior**
I expect to be able to get the same information when I execute `vault status -format=json` as when I execute `vault status -format=table`.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.4.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.4.2
* Server Operating System/Architecture:
```bash
ubuntu@ip-10-10-75-128:~$ cat /etc/*version*
buster/sid
Ubuntu 18.04.4 LTS (Bionic Beaver)`
```

**Comment by dedamico** [comment]
This appears to be same/similar to https://github.com/hashicorp/vault/issues/6179

**Comment by akshya96** [comment]
Hi @jamiegwatkin, We only display the relevant fields for "table" format. I've added the expected differences in the vault status documentation https://github.com/hashicorp/vault/pull/19361.

**Comment by akshya96** [comment]
Since the expected differences are documented, I'm going to go ahead and close this issue now. Thanks.
