### ISSUE TITLE
core: failed to run existence check - context canceled 

### ISSUE THREAD

**Issue by Hawkinsonb** [hashicorp/vault#9205]
**Describe the bug**
Vault is running in docker via docker-compose with a consul storage backend(of which is also in the same docker-compose file in it's own container). Upon attempting to write a secret vault fails to exec the write. Consul shows request finished. 
```bash
 vault_1 | 2020-06-11T20:09:47.204Z [ERROR] core: failed to run existence check: error="Get http://consul:8500/v1/kv/vault/logical/deee283f-11da-5d32-0dff-574779ed3a85/4c1e5c8b-aad1-3b41-42af-7f26e2062ff4/metadata/5kKRrmEytUxdON11nZxsAzfjDC53W9P6SfHDVXkM0pcK5SR0NahRAeaYQI2QGh/1TfzvsKllSc3msurizoa2SxlvborAM0WIgyxhCmFxtR6cdEOwvMaweOrmYEP7CkfUQcfJstrL/EHdh8bYtwRnRssZ7oSL1v9M297yabLdNwKvAk0ptbirRp41RF8ziA9dskyCSNWiCdS4SzRUN8GeRF7muOAbNgKEJB6FKYxxLqaz58V059YwyFvEFZSNBGRcM2hwTHD/p0D1qDFzS3tnq3WvyYUqXgE4iq0WFrRuRYkPfKgX3Z3pHm4z4a2FF7OdgoEceGlLLqt: context canceled"
```
Upon observation, vault status also hung and vault was unable to respond. 

**To Reproduce**
Unknown

**Expected behavior**
Context canceled should not occur. 

**Environment:**
* Vault Server Version (retrieve with `vault status`): v1.4.2
* Vault CLI Version (retrieve with `vault version`): v1.4.2
* Server Operating System/Architecture: Docker-Compose alpine:latest

Vault server configuration file(s):

```json
{
  "backend": {
    "consul": {
      "address": "consul:8500",
      "cluster_address": "vault:8201",
      "path": "vault/"
    }
  },
  "listener": {
    "tcp":{
      "address": "0.0.0.0:8200",
      "tls_disable": 1
    }
  },
  "ui": true
}
```
docker-compose:
```Docker
version: '3.7'

services:
  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    volumes:
      - /opt/<redacted>/vault/config:/vault/config
      - /opt/<redacted>/vault/policies:/vault/policies
      - /opt/<redacted>/vault/data:/vault/data
      - /opt/<redacted>/vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
      - VAULT_CLUSTER_ADDR=http://127.0.0.1:8201
    command: server -config=/vault/config/config.json
    cap_add:
      - IPC_LOCK

  consul:
    build:
      context: ./consul
      dockerfile: Dockerfile
    ports:
      - 8500:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -config-file=/consul/config/config.json -bootstrap-expect 3
    volumes:
      - /opt/<redacted>/consul/config:/consul/config
      - /opt/<redacted>/consul/data:/consul/data
      - /opt/<redacted>/consul/backups:/consul/backups
    restart: always

  consul-1:
    build:
      context: ./consul
      dockerfile: Dockerfile
    command: agent -server -retry-join consul -config-file=/consul/config/config.json
    volumes:
      - /opt/<redacted>/consul/config:/consul/config
    restart: always
    depends_on:
      - consul

  consul-2:
    build:
        context: ./consul
        dockerfile: Dockerfile
    command: agent -server -retry-join consul -config-file=/consul/config/config.json
    volumes:
        - /opt/<redacted>/consul/config:/consul/config
    restart: always
    depends_on:
        - consul

  consul-3:
    build:
        context: ./consul
        dockerfile: Dockerfile
    command: agent -server -retry-join consul -config-file=/consul/config/config.json
    volumes:
        - /opt/<redacted>/consul/config:/consul/config
    restart: always
    depends_on:
        - consul

  consul-4:
    build:
        context: ./consul
        dockerfile: Dockerfile
    command: agent -server -retry-join consul -config-file=/consul/config/config.json
    volumes:
        - /opt/<redacted>/consul/config:/consul/config
    restart: always
    depends_on:
        - consul
```

Consul config:
```Json
{
  "datacenter": "localhost",
  "data_dir": "/consul/data",
  "log_level": "DEBUG",
  "server": true,
  "ui": true,
  "bootstrap_expect": 3,
  "ports": {
    "dns": 53
  }
}
```

**Additional context**
Vault has run pretty smoothly other than this issue since swapping to a consul backend.

**Comment by austingebauer** [comment]
Thanks for opening the issue, @Hawkinsonb. It will be difficult to help you without reproduction steps and the docker compose file that you used. Are you able to provide both of those?

**Comment by Hawkinsonb** [comment]
Hi @austingebauer , I'm unsure of the reproduction steps. Vault was working, then simply stopped working for this reason on attempting to write a new secret. 

I've updated the original comment with the docker compose file as well as the current consul config.

**Comment by ncabatoff** [comment]
Hi @Hawkinsonb,

The "context cancelled" error is Go's way of saying "a timeout occurred".  In this case your Consul storage backend is timing out when servicing a storage request from Vault.  Perhaps it is underprovisioned for your workload, or perhaps the Consul cluster encountered an issue.

I don't think this is actually a bug - the Vault behaviour you describe is normal if storage is wonky.  I suggest you take your question to the [forum](https://discuss.hashicorp.com/c/vault/30) and perhaps someone there will be able to help you figure out why Consul is timing out your request sometimes.  If you haven't already reproduced this with Consul debug logging enabled, that would probably be a good first step.
