### ISSUE TITLE
Vault Root Token Error: Missing Client Token

### ISSUE THREAD

**Issue by alireza95jalili** [hashicorp/vault#9220]
**Describe the bug**
i am getting "Authentication failed: missing client token" when trying to login with root token in UI.
i tried to create a  new user via cli with admin policies. then i could login in ui. but also when i go to policies tab or access tab, i get this error in ui:

```
Ember Data Request GET /v1/sys/policies/acl returned a 400 Payload (application/json) [object Object]

missing client token
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.4.2
* Vault CLI Version (retrieve with `vault version`): 1.4.2
* Server Operating System/Architecture: Ubuntu lts 20.04

Vault server configuration file(s):

```hcl
disable_cache = true
disable_mlock = true
ui = true
listener "tcp" {
   address          = "0.0.0.0:8200"
   tls_disable      = 1
}
storage "file" {
   path  = "/var/lib/vault/data"
 }
api_addr         = "http://0.0.0.0:8200"
max_lease_ttl         = "10h"
default_lease_ttl    = "10h"
cluster_name         = "vault"
raw_storage_endpoint     = true
disable_sealwrap     = true
disable_printable_check = true
```

**Additional context**

- cat  ~/.vault-token return True token.
- i can enter with cli and i did login with ```vault auth``` in cli.

**Comment by austingebauer** [comment]
Hi, @alireza95jalili. Are you able to add steps to reproduce this issue along with the expected behavior to the bug description? Thanks.

**Comment by alireza95jalili** [comment]
hi @austingebauer 
this is exact steps i did to install vault.

```
VAULT_VERSION="1.4.2"
curl -sO https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
unzip vault_${VAULT_VERSION}_linux_amd64.zip
sudo mv vault /usr/local/bin/
vault -autocomplete-install
complete -C /usr/local/bin/vault vault
sudo mkdir /etc/vault
sudo mkdir -p /var/lib/vault/data
sudo useradd --system --home /etc/vault --shell /bin/false vault
sudo chown -R vault:vault /etc/vault /var/lib/vault/
touch /etc/systemd/system/vault.service
nano /etc/systemd/system/vault.service
touch /etc/vault/config.hcl
nano /etc/vault/config.hcl
sudo systemctl daemon-reload
sudo systemctl enable --now vault
export VAULT_ADDR=http://ip:8200
echo "export VAULT_ADDR=http://ip:8200" >> ~/.bashrc
sudo rm -rf  /var/lib/vault/data/*
vault operator init > /etc/vault/init.file
vault auth
```

then if i go to http://ip:8200 i cant login with root token and i show a error says: "missing client token".
i can create new user with user/pass in cli mode (where root token is acceptable and i can login with that), but if i go to those tabs i said in issue ... i will get 'missing client token' again

**Comment by alireza95jalili** [comment]
@ausmartway 
i tired version 1.4.0 and the error still was there

**Comment by alireza95jalili** [comment]
@austingebauer 
i tired version 1.4.0 and the error still was there

**Comment by alireza95jalili** [comment]
screen shots:

https://ibb.co/0Qkw5Sx
https://ibb.co/k4DyGZ3
https://ibb.co/cwqCSGZ

**Comment by alireza95jalili** [comment]
@jefferai @vishalnayak 
this issue was opend in 15 days ago

**Comment by ausmartway** [comment]
@alireza95jalili which browser do you use? do you have any ad-blocking plugins? can you please try a browser without any blocker?
