### ISSUE TITLE
I would like to use azure cosmos db or mongodb as a secrets engine. Is that possible?

### ISSUE THREAD

**Issue by zimmerab** [hashicorp/vault#9230]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have a highly available secrets engine that is also easily movable to many regions.

**Describe the solution you'd like**
I would like to be able to configure vault to leverage azure cosmos db as a secrets engine in a yaml file for kubernetes. 

**Describe alternatives you've considered**
I have considered alternatives like mysql and consul but, I believe no sql would be a better use case in this instance. It would be extremely high available and I would have a fast response time. It would also be easy for dr plans.

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

I have a kubernetes cluster in azure. It is known as AKS. I want to leverage aks to host vault. When picking a back end that is highly available it seems that cosmos db may be the best option.

**Additional context**

**Comment by austingebauer** [comment]
Hi, @zimmerab. I'll try to answer your questions first and see if we need to keep this feature request open. There currently isn't a Vault secrets engine for Azure Cosmos DB. Vault does have database secrets engines for [MongoDB](https://www.vaultproject.io/docs/secrets/databases/mongodb) and [MongoDB Atlas](https://www.vaultproject.io/docs/secrets/databases/mongodbatlas). Vault also has a [helm chart](https://github.com/hashicorp/vault-helm) that could be of use for your kubernetes related needs.

If you'd like to keep this issue open as a feature request for an Azure Cosmos DB secrets engine, I suggest that you focus this issue (title, description) on that. Thanks!

**Comment by raskchanky** [comment]
Hi @zimmerab,

We haven’t heard back from you on this for a while. I’m going to close this for now, but please feel free to re-open it with additional information!
