### ISSUE TITLE
No Access-Future access denied and past access deleted and changes restored.

### ISSUE THREAD

**Issue by pacificandreascc** [hashicorp/vault#9243]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by ncabatoff** [comment]
Hi @pacificandreascc,

I'm going to close this issue as it was submitted without any information.
