### ISSUE TITLE
Transit key rotation performance

### ISSUE THREAD

**Issue by jgaxn** [hashicorp/vault#925]
We would like to implement a feature with our transit encrypted values where we rotate the key every hour and continuously rewrap all our values. Once a key version is no longer in use (which could take a while... we currently have 3MM values and expect that to grow 10x and 100x in the next year or two) we would adjust the minimum decryption version and basically have a sliding subset of keys which could be used for decryption at any time.

We did some rough benchmarking and found that performance on encrypts, decrypts and rewraps degrades as the number of key versions increases. There is also no performance benefit gained by changing the minimum decryption version. (Ex: decrypting with key version 10000 takes the same amount of time whether the minimum decryption version is 0 or 10000.) I'm unfamiliar with Go array performance, but it seems like we could build an `ActiveKeys` array every time we change the minimum decryption version and look at that array instead of `Keys` when inside the `DeriveKey` function here: https://github.com/hashicorp/vault/blob/7c7b21c61ebadd1c714f6a83346d4f027d885fb7/builtin/logical/transit/policy.go#L124

That would definitely give us a performance benefit for our use case since we will be performing our key rotations in a background job invisible to the end user.

I'm a novice at Go, but this is something I could work on. I wanted to make sure this is something that **should** be built before I build it.

**Comment by jefferai** [comment]
Hi @jgaxn ,

That's definitely something to look at. I don't think we'd considered the case of keys rotating that often and I wouldn't be surprised if we can eke some performance increases there. I'll try to get to it for 0.5.

**Comment by jefferai** [comment]
Just to add to my previous comment: it's not really the array performance that's the problem, it's loading it from physical storage that is the issue. The keys are loaded on each request. A cache might help, but if you're rotating once an hour, you could have the real possibility of blowing out the cache after a bit, in which case you'd be back to this behavior. So i'm going to implement key archiving, and we may add a cache too at some point.

**Comment by jefferai** [comment]
@jgaxn If you'd like to test this out (I probably won't get back to this until late next week), there's a branch called `transit-key-archiving` in the repo. It should automatically archive when you change the minimum key version, so that only the window between the minimum and the latest are in the main data structure. Note that as the number of keys increases, changing the minimum key version will become a longer operation since it will have to load the archive, add the now-old version(s), and then save it back. But that's one administrative operation vs. loading it each time.

I may also explore archiving each key individually in the storage backend and loading them on-demand, rather than storing them in a slice. This would mean you wouldn't get into a memory pressure situation as the number of rotated keys grows to huge numbers, but not all storage backends deal well with large numbers of individual files. If you're rotating several million times, that could become a serious problem (and cause memory pressure anyways).

If you try it, let me know how it goes. I haven't had time to run any tests yet.

**Comment by jgaxn** [comment]
@jefferai I'll run some tests on it today. Thank you!

**Comment by jgaxn** [comment]
@jefferai 
I got the following error when trying to set a `min_decryption_version` greater than 1.

```
17:07 $ vault2 write transit/keys/named_key/config min_decryption_version=1000
Error writing data to transit/keys/named_key/config: Put http://127.0.0.1:8200/v1/transit/keys/named_key/config: EOF
```

And here's what Vault had to say at the same time:
```
2016/01/15 17:24:16 http: panic serving 127.0.0.1:52079: runtime error: index out of range
goroutine 12977 [running]:
net/http.(*conn).serve.func1(0xc82028e4d0, 0x1ba0028, 0xc82023a010)
  /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/hashicorp/vault/builtin/logical/transit.(*Policy).handleArchiving(0xc8202e4280, 0x1d098f8, 0xc820376da0, 0xc8204a45e5, 0x9, 0x0, 0x0)
  /Users/jgaxn/apps/go/src/github.com/hashicorp/vault/builtin/logical/transit/policy.go:182 +0x46b
github.com/hashicorp/vault/builtin/logical/transit.(*Policy).Persist(0xc8202e4280, 0x1d098f8, 0xc820376da0, 0xc8204a45e5, 0x9, 0x0, 0x0)
  /Users/jgaxn/apps/go/src/github.com/hashicorp/vault/builtin/logical/transit/policy.go:239 +0x6e
github.com/hashicorp/vault/builtin/logical/transit.pathConfigWrite(0xc8202e4100, 0xc820302760, 0x0, 0x0, 0x0)
  /Users/jgaxn/apps/go/src/github.com/hashicorp/vault/builtin/logical/transit/path_config.go:81 +0x8be
github.com/hashicorp/vault/logical/framework.(*Backend).HandleRequest(0xc82028e8f0, 0xc8202e4100, 0xc8202e4100, 0x0, 0x0)
  /Users/jgaxn/apps/go/src/github.com/hashicorp/vault/logical/framework/backend.go:189 +0x830
github.com/hashicorp/vault/vault.(*Router).routeCommon(0xc820262c00, 0xc8202e4100, 0x0, 0x0, 0x0, 0x0, 0x0)
  /Users/jgaxn/apps/go/src/github.com/hashicorp/vault/vault/router.go:271 +0xbd6
github.com/hashicorp/vault/vault.(*Router).Route(0xc820262c00, 0xc8202e4100, 0xc8202e4100, 0x0, 0x0)
  /Users/jgaxn/apps/go/src/github.com/hashicorp/vault/vault/router.go:187 +0x3c
github.com/hashicorp/vault/vault.(*Core).handleRequest(0xc8201e11e0, 0xc8202e4100, 0x0, 0x0, 0x0, 0x0)
  /Users/jgaxn/apps/go/src/github.com/hashicorp/vault/vault/core.go:515 +0x9d7
github.com/hashicorp/vault/vault.(*Core).HandleRequest(0xc8201e11e0, 0xc8202e4100, 0x0, 0x0, 0x0)
  /Users/jgaxn/apps/go/src/github.com/hashicorp/vault/vault/core.go:436 +0x498
github.com/hashicorp/vault/http.request(0xc8201e11e0, 0x1d0eed8, 0xc82028e580, 0xc8200be540, 0xc8202e4100, 0xc820302200, 0xe)
  /Users/jgaxn/apps/go/src/github.com/hashicorp/vault/http/handler.go:82 +0x2f
github.com/hashicorp/vault/http.handleLogical.func1(0x1d0eed8, 0xc82028e580, 0xc8200be540)
  /Users/jgaxn/apps/go/src/github.com/hashicorp/vault/http/logical.go:68 +0x5a1
net/http.HandlerFunc.ServeHTTP(0xc820279340, 0x1d0eed8, 0xc82028e580, 0xc8200be540)
  /usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc82027d6e0, 0x1d0eed8, 0xc82028e580, 0xc8200be540)
  /usr/local/go/src/net/http/server.go:1699 +0x17d
github.com/hashicorp/vault/http.handleHelpHandler.func1(0x1d0eed8, 0xc82028e580, 0xc8200be540)
  /Users/jgaxn/apps/go/src/github.com/hashicorp/vault/http/help.go:18 +0x11d
net/http.HandlerFunc.ServeHTTP(0xc820279380, 0x1d0eed8, 0xc82028e580, 0xc8200be540)
  /usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.serverHandler.ServeHTTP(0xc82022ad80, 0x1d0eed8, 0xc82028e580, 0xc8200be540)
  /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82028e4d0)
  /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
  /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

Looks like the problem is here: https://github.com/hashicorp/vault/blob/cfc64141c1ad0554e1ef62d5ca08e30f8ba346d4/builtin/logical/transit/policy.go#L182

**Comment by jefferai** [comment]
Yeah, not totally unexpected, as I said I literally have not tested it at all :-) I'm on vacation, if I get a chance I'll look, otherwise later this week.

**Comment by jgaxn** [comment]
Thank you! Enjoy your vacation!

**Comment by jgaxn** [comment]
@jefferai 

I figured out the bug. Both the key archiving for loop [Line 181](https://github.com/hashicorp/vault/blob/cfc64141c1ad0554e1ef62d5ca08e30f8ba346d4/builtin/logical/transit/policy.go#L181) and the key deleting for loop [Line 192](https://github.com/hashicorp/vault/blob/cfc64141c1ad0554e1ef62d5ca08e30f8ba346d4/builtin/logical/transit/policy.go#L192) should be incrementing instead of decrementing.

With that change everything looks to be working and there's a noticeable improvement in performance.

**Comment by jefferai** [comment]
@jgaxn Ah crap -- I had originally gone the other way in the `for` loops and when I changed the conditions I totally forgot to change the increment. Thanks for catching this (I literally finished the code I had there directly before heading to the airport) -- I'll update the branch. And eventually (when I'm back in town) I'll be adding copious tests.

**Comment by jefferai** [comment]
Branch is updated.

**Comment by jgaxn** [comment]
@jefferai 
Awesome, thanks. FYI: It looks like there's also an issue with restoring archived keys. I get an error when trying to decrypt with a key that had been archived:
```
* crypto/aes: invalid key size 0
```
I'm sure this will get sniffed out during testing. In the meantime I can verify that the performance benefits are as expected when the `min_decryption_version` is adjusted. Thank you very much!

**Comment by jefferai** [comment]
@jgaxn I found a logic bug when restoring keys. I haven't written unit tests but now have a test script and have done some decently extensive testing on the command line. Can you see if the problem you found has been fixed?

**Comment by jgaxn** [comment]
@jefferai I'll check. Thanks!

**Comment by jgaxn** [comment]
@jefferai I'm still seeing the same error on my end

```
$ vault2 write transit/encrypt/named_key plaintext=test
Key       	Value
ciphertext	vault:v1:9VSNEpnTY1PwYPbhOiUqL1KnCnCem7/I+SxOAkZ+6w==

$ vault2 write -f transit/keys/named_key/rotate
Success! Data written to: transit/keys/named_key/rotate

$ vault2 write -f transit/keys/named_key/rotate
Success! Data written to: transit/keys/named_key/rotate

$ vault2 read transit/keys/named_key
Key                   	Value
archive_version       	0
cipher_mode           	aes-gcm
deletion_allowed      	false
derived               	false
keys                  	map[1:1.453421397e+09 2:1.453421514e+09 3:1.453421516e+09]
latest_version        	3
min_decryption_version	0
name                  	named_key

$ vault2 write transit/rewrap/named_key ciphertext=vault:v1:9VSNEpnTY1PwYPbhOiUqL1KnCnCem7/I+SxOAkZ+6w==
Key       	Value
ciphertext	vault:v3:H4tRbo1e/WKKcitCImwG5DYe1DSfJnspfFmWttsCHQ==

$ vault2 write transit/keys/named_key/config min_decryption_version=3
Success! Data written to: transit/keys/named_key/config

$ vault2 write transit/decrypt/named_key ciphertext=vault:v3:H4tRbo1e/WKKcitCImwG5DYe1DSfJnspfFmWttsCHQ==
Key      	Value
plaintext	test

$ vault2 write transit/decrypt/named_key ciphertext=vault:v1:9VSNEpnTY1PwYPbhOiUqL1KnCnCem7/I+SxOAkZ+6w==
Error writing data to transit/decrypt/named_key: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/transit/decrypt/named_key
Code: 400. Errors:

* ciphertext version is disallowed by policy (too old)

$ vault2 write transit/keys/named_key/config min_decryption_version=1
Success! Data written to: transit/keys/named_key/config

$ vault2 write transit/decrypt/named_key ciphertext=vault:v1:9VSNEpnTY1PwYPbhOiUqL1KnCnCem7/I+SxOAkZ+6w==
Error writing data to transit/decrypt/named_key: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/transit/decrypt/named_key
Code: 500. Errors:

* crypto/aes: invalid key size 0
```

**Comment by jefferai** [comment]
That's super weird because in my testing I put in code to check the key values in the archive vs the restored values (using a third map that held *all* of the keys) and everything matched. Thanks for the CLI commands, that will be very helpful in figuring out what's going on. I'll update when I have more...

**Comment by jefferai** [comment]
@jgaxn Thanks, this was very helpful.

The problem was that I wanted to avoid archiving if the minimum decryption version was set to < 2, but I should have only been fast-pathing out of that function if the min decryption version was set to < 2 *and we are saving keys*, not restoring them. The keys weren't lost -- they were properly in the archive -- they just weren't being loaded back into the main map.

The main issue was dealing with the case where the min decryption version was set to 0. As of Vault 0.3, keys start with `v1` rather than `v0` (although v0 is an alias so internally they are the same). But, instead of dealing with the fast-pathing at all, what I did is simply add a check anywhere the policy is persisted (or when the policy is loaded) and on configuration that ensures that if `min_decryption_version` is set to 0, it is automatically set to 1. Then the archiving can work on values 1+, which match the versions of keys.

In my testing this fixes the problem you saw using your CLI commands. I just pushed changes -- please give them a try if you get a chance!

**Comment by jgaxn** [comment]
@jefferai Thanks! Looks like it's working great!
