### ISSUE TITLE
 expiration: error restoring leases, ldap Unexpected response code: 500 

### ISSUE THREAD

**Issue by elikt** [hashicorp/vault#9255]
**Describe the bug**
Vault keeps getting sealed with same error message in the logs (It happens once in a while)

**To Reproduce**

**Expected behavior**

**Environment:**
* Vault Server Version 1.4.2
* Consul 1.6.0 as storage
* Running on k8s pods v1.13

Vault server configuration file(s):

```hcl
{
  "api_addr": "http://vault.svc.kube:8200",
  "cluster_addr": "http://vault.svc.kube:8201",
  "listener": {
    "tcp":{
      "address": "0.0.0.0:8200",
      "tls_disable": 1
    }
  },
  "seal": {
     "gcpckms": {
        "credentials": "cred",
        "project": "myproject",
        "region": "us",
        "key_ring": "my-keyring",
        "crypto_key": "my-key"
    }
  },
  "storage": {
    "consul": {
      "address": "consul.service.consul:8500",
      "lock_wait_time": "1h",
      "consistency_mode": "strong",
      "path": "vault/"
    }
  },
  "ui": true
}
```
**Logs before the seal**
  
	12:01:12.058Z [INFO]  core: pre-seal teardown starting
	12:01:12.560Z [DEBUG] expiration: stop triggered
	12:01:12.561Z [INFO]  core: pre-seal teardown complete
	12:01:12.560Z [INFO]  rollback: stopping rollback manager
	12:01:12.560Z [DEBUG] expiration: finished stopping
	12:01:13.726Z [INFO]  core: acquired lock, enabling active operation
	12:01:13.750Z [DEBUG] core: generating cluster private key
	12:01:13.761Z [DEBUG] core: generating local cluster certificate
	12:01:13.785Z [INFO]  core: post-unseal setup starting
	12:01:13.787Z [DEBUG] core: done clearing forwarding clients
	12:01:13.787Z [DEBUG] core: clearing forwarding clients
	12:01:13.787Z [DEBUG] core: persisting feature flags
	12:01:13.800Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
	12:01:13.800Z [INFO]  core: loaded wrapping token key
	12:01:13.804Z [INFO]  core: successfully mounted backend: type=system path=sys/
	12:01:13.805Z [INFO]  core: successfully mounted backend: type=kv path=secret/
	12:01:13.805Z [INFO]  core: successfully mounted backend: type=identity path=identity/
	12:01:13.805Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
	12:01:13.824Z [INFO]  core: successfully enabled credential backend: type=ldap path=ldap/
	12:01:13.824Z [DEBUG] expiration: collecting leases
	12:01:13.824Z [INFO]  core: restoring leases
	12:01:13.824Z [INFO]  rollback: starting rollback manager
	12:01:13.824Z [INFO]  core: successfully enabled credential backend: type=token path=token/
	12:01:13.829Z [DEBUG] identity: loading entities
	12:01:13.831Z [DEBUG] identity: entities collected: num_existing=3
	12:01:13.831Z [DEBUG] expiration: leases collected: num_existing=51
	12:01:13.831Z [DEBUG] identity: entities loading: progress=0
	12:01:13.834Z [INFO]  identity: entities restored
	12:01:13.834Z [DEBUG] identity: identity loading groups
	12:01:13.840Z [DEBUG] identity: groups collected: num_existing=3
	12:01:13.908Z [INFO]  expiration: lease restore complete
	12:01:13.908Z [INFO]  identity: groups restored
	12:01:13.973Z [DEBUG] core: done clearing forwarding clients
	12:01:13.973Z [DEBUG] core: clearing forwarding clients
	12:01:13.973Z [DEBUG] core: leaving request forwarding setup function
	12:01:13.973Z [DEBUG] core: request forwarding setup function
	12:01:14.564Z [INFO]  core: post-unseal setup complete
	12:03:13.735Z [INFO]  core: pre-seal teardown starting
	12:03:14.235Z [DEBUG] expiration: finished stopping
	12:03:14.235Z [INFO]  rollback: stopping rollback manager
	12:03:14.235Z [DEBUG] expiration: stop triggered
	12:03:14.235Z [INFO]  core: pre-seal teardown complete
	12:03:15.292Z [INFO]  core: acquired lock, enabling active operation
	12:03:15.312Z [DEBUG] core: generating cluster private key
	12:03:15.323Z [DEBUG] core: generating local cluster certificate
	12:03:15.356Z [INFO]  core: post-unseal setup starting
	12:03:15.358Z [DEBUG] core: done clearing forwarding clients
	12:03:15.358Z [DEBUG] core: persisting feature flags
	12:03:15.358Z [DEBUG] core: clearing forwarding clients
	12:03:15.374Z [INFO]  core: loaded wrapping token key
	12:03:15.374Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
	12:03:15.379Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
	12:03:15.379Z [INFO]  core: successfully mounted backend: type=kv path=secret/
	12:03:15.379Z [INFO]  core: successfully mounted backend: type=system path=sys/
	12:03:15.379Z [INFO]  core: successfully mounted backend: type=identity path=identity/
	12:03:15.398Z [INFO]  rollback: starting rollback manager
	12:03:15.398Z [INFO]  core: successfully enabled credential backend: type=token path=token/
	12:03:15.398Z [INFO]  core: successfully enabled credential backend: type=ldap path=ldap/
	12:03:15.398Z [INFO]  core: restoring leases
	12:03:15.398Z [DEBUG] expiration: collecting leases
	12:03:15.402Z [DEBUG] identity: loading entities
	12:03:15.404Z [DEBUG] identity: entities collected: num_existing=3
	12:03:15.404Z [DEBUG] identity: entities loading: progress=0
	12:03:15.410Z [DEBUG] identity: identity loading groups
	12:03:15.410Z [INFO]  identity: entities restored
	12:03:15.411Z [DEBUG] identity: groups collected: num_existing=3
	12:03:15.412Z [DEBUG] expiration: leases collected: num_existing=51
	12:03:15.436Z [INFO]  identity: groups restored
	12:03:15.440Z [DEBUG] core: clearing forwarding clients
	12:03:15.440Z [DEBUG] core: request forwarding setup function
	12:03:15.440Z [DEBUG] core: done clearing forwarding clients
	12:03:15.440Z [DEBUG] core: leaving request forwarding setup function
	12:03:15.475Z [INFO]  expiration: lease restore complete
	12:03:16.032Z [INFO]  core: post-unseal setup complete
	12:05:15.298Z [INFO]  core: pre-seal teardown starting
	12:05:15.798Z [DEBUG] expiration: finished stopping
	12:05:15.798Z [DEBUG] expiration: stop triggered
	12:05:15.798Z [INFO]  rollback: stopping rollback manager
	12:05:15.799Z [INFO]  core: pre-seal teardown complete
	12:05:16.866Z [INFO]  core: acquired lock, enabling active operation
	12:05:16.898Z [DEBUG] core: generating cluster private key
	12:05:16.925Z [DEBUG] core: generating local cluster certificate
	12:05:16.962Z [INFO]  core: post-unseal setup starting
	12:05:16.965Z [DEBUG] core: persisting feature flags
	12:05:16.965Z [DEBUG] core: done clearing forwarding clients
	12:05:16.965Z [DEBUG] core: clearing forwarding clients
	12:05:16.985Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
	12:05:16.985Z [INFO]  core: loaded wrapping token key
	12:05:16.996Z [INFO]  core: successfully mounted backend: type=kv path=secret/
	12:05:16.996Z [INFO]  core: successfully mounted backend: type=system path=sys/
	12:05:16.996Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
	12:05:16.996Z [INFO]  core: successfully mounted backend: type=identity path=identity/
	12:05:17.036Z [DEBUG] expiration: collecting leases
	12:05:17.036Z [INFO]  rollback: starting rollback manager
	12:05:17.035Z [INFO]  core: restoring leases
	12:05:17.035Z [INFO]  core: successfully enabled credential backend: type=token path=token/
	12:05:17.035Z [INFO]  core: successfully enabled credential backend: type=ldap path=ldap/
	12:05:17.043Z [DEBUG] identity: entities loading: progress=0
	12:05:17.041Z [DEBUG] identity: loading entities
	12:05:17.043Z [DEBUG] identity: entities collected: num_existing=3
	12:05:17.049Z [INFO]  identity: entities restored
	12:05:17.050Z [DEBUG] identity: groups collected: num_existing=3
	12:05:17.050Z [DEBUG] expiration: leases collected: num_existing=51
	12:05:17.049Z [DEBUG] identity: identity loading groups
	12:05:17.070Z [DEBUG] core: done clearing forwarding clients
	12:05:17.070Z [DEBUG] core: shutdown called
	12:05:17.070Z [ERROR] core: shutting down
	12:05:17.070Z [INFO]  core: marked as sealed
	12:05:17.070Z [ERROR] expiration: error restoring leases: error="failed to read lease entry auth/ldap/login/USERNAME/h9524e102644b1af5ea4e53a64eaac04cb1c6c1e5669d994b606bd65d1efc5953: Unexpected response code: 500"
	12:05:17.070Z [DEBUG] core: clearing forwarding clients
	12:05:17.174Z [DEBUG] core: clearing forwarding clients
	12:05:17.174Z [DEBUG] core: request forwarding setup function
	12:05:17.174Z [DEBUG] core: done clearing forwarding clients
	12:05:17.171Z [INFO]  identity: groups restored
	12:05:17.174Z [DEBUG] core: leaving request forwarding setup function
	12:05:17.760Z [INFO]  core: post-unseal setup complete
	12:05:17.760Z [DEBUG] core: shutting down leader elections
	12:05:17.760Z [DEBUG] core: shutting down periodic leader refresh
	12:05:17.760Z [DEBUG] core: shutting down periodic key rotation checker
	12:05:17.760Z [INFO]  core: pre-seal teardown starting
	12:05:17.760Z [DEBUG] core: finished triggering standbyStopCh for runStandby
	12:05:18.260Z [INFO]  rollback: stopping rollback manager
	12:05:18.260Z [DEBUG] expiration: finished stopping
	12:05:18.260Z [DEBUG] expiration: stop triggered
	12:05:18.261Z [INFO]  core: pre-seal teardown complete
	12:05:18.303Z [INFO]  core.cluster-listener: forwarding rpc listeners stopped
	12:05:18.303Z [INFO]  core: stopping cluster listeners
	12:05:18.303Z [DEBUG] core: runStandby done
	12:05:18.539Z [INFO]  core.cluster-listener: rpc listeners successfully shut down
	12:05:18.539Z [DEBUG] core: sealing barrier
	12:05:18.539Z [INFO]  core: cluster listeners successfully shut down
	12:05:18.539Z [INFO]  core: vault is sealed
**Additional context**
Using google kms to auto-unseal and LDAP auth method

**Comment by ncabatoff** [comment]
Hi @elikt,

It is normal for Vault to seal itself if it gets errors from the underlying storage system - in this case, it's getting a 500 (internal server error) from Consul.  You should look at the Consul system logs to see why that's happening.
