### ISSUE TITLE
Transit EaaS with custom keys

### ISSUE THREAD

**Issue by friendzis** [hashicorp/vault#9264]
**Is your feature request related to a problem? Please describe.**
Currently, the transit backend only supports Vault internally generated keys. As per Issue [#2667](https://github.com/hashicorp/vault/issues/2667) only Vault-generated keys can be imported. This is an issue in cases where an organisation is not the owner of keys - e.g. keys are part of the use contract and provided by an external service.

**Describe the solution you'd like**
Allow to import externally generated keys, preferably with a wider (relaxed) set of key algorithms (e.g. 1024 bit RSA) than the set used for new key generation.

**Describe alternatives you've considered**
Change organisational workflow, which is not always possible. Limit Vault's usage inside organisation.

**Explain any additional use-cases**
Additional set use cases arise with legacy, closed-source, and third-party applications having already established set of encrypted/signed data. Even in situations where key rotation is supported, key versioning is not necessarily supported, meaning key rotation comes with organisational issues: encrypted data at rest must be reencrypted offline with Vault generated key requiring downtime, stored signatures are invalidated and must be discarded, which may not be acceptable organizationally.

**Comment by ae6rt** [comment]
We have a similar interest, where keys are prospectively exported from a legacy HSM and into Vault.  One could reverse engineer how Vault `backup` works, and format the inbound keys the same way in preparation for `restore`, but that seems risky as it depends on undocumented and perhaps unstable Vault backup formats.

**Comment by fdaruos** [comment]
This could be also an interesting capability to make more flexible the Transit engine in regards to the used Encryption key.
