### ISSUE TITLE
TOTP paths support

### ISSUE THREAD

**Issue by weitzjdevk** [hashicorp/vault#9273]
**Is your feature request related to a problem? Please describe.**
I would like to have paths when using the TOTP secret engine.

**Describe the solution you'd like**
The TOTP secret engine should work similar to the KV engine, supporting paths, which can be controlled by policies

**Describe alternatives you've considered**
Mount many TOTP secret engines for different paths

**Explain any additional use-cases**
M teams are owners of N AWS accounts, whereas each AWS account can have at most one `owner`. And this owner can at most have 1 MFA device.

Therefore the owner of the account is kind of treated as a "technical user", which should only be used in the worst case. And for this worst case there would need to be >1 administrators, which need to access the AWS account with said root-user. To access the account they need static credentials (KV-Engine) + OneTimeToken.

It would be nice to put this "virtual MFA device" inside Vault and use policies to get a `code` for said device. Only some team members of a team should use "their" MFA device of said root-account (owner). Each uage would be tracked in the auditlog. The OTP-Key would be seal-wrapped possibly with KMS or an HSM.

**Comment by remilapeyre** [comment]
Hi @weitzjdevk, is this not already possible by using multiple totp mounts:

```
$ vault secrets enable -path topt1 totp
$ vault secrets enable -path topt2 totp
```

?

**Comment by hghaf099** [comment]
Hi @weitzjdevk, as mentioned by @remilapeyre you can already mount several totp engines in different paths. Please take a look at https://www.vaultproject.io/docs/secrets/totp for further information. I am going to close this issue for now. Please feel free to reopen the issue or open a new one for further discussion.
