### ISSUE TITLE
 x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by st33v** [hashicorp/vault#928]
I'm using vault with a consul backend and registering vault as a service with consul. I have a cert with the IP san name 'vault.service.consul'. I export VAULT_ADDR:

```
[root@ip-10-48-235-142 cloud-user]# set |grep VAULT
VAULT_ADDR=https://vault.service.consul:8200
```

'vault status' works:
```
[root@ip-10-48-235-142 cloud-user]# vault status
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0

High-Availability Enabled: true
	Mode: standby
	Leader: https://10.48.235.49:8200
```

but when I try to read a secret:
```
[root@ip-10-48-235-142 cloud-user]# vault read -ca-path=/etc/pki/ca-trust/source/anchors -field=value secret/my_role/foo 
Error reading secret/my_role/foo: Get https://10.48.235.49:8200/v1/secret/my_role/foo: x509: cannot validate certificate for 10.48.235.49 because it doesn't contain any IP SANs
```

the hosts resolve via DNS:
```
[root@ip-10-48-235-142 cloud-user]# nslookup vault.service.consul
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:	vault.service.consul
Address: 10.48.235.49
Name:	vault.service.consul
Address: 10.48.235.142
```

so why does `vault read` use the resolved IP when doing the TLS validation instead of the name?

**Comment by jefferai** [comment]
Hi @st33v ,

`vault read` is using the advertised address of the leader, as you can see in your `vault status` output. Your certificate does not contain `10.48.235.49` in its IP SANs, so the certificate is being rejected.

Check the [`advertise_addr`](https://vaultproject.io/docs/config/index.html) parameter if you want to control the leader's advertised address, and thus the address the CLI client uses for connections.

**Comment by st33v** [comment]
Thank you!

**Comment by stampycode** [comment]
@jefferai The `advertise_addr` parameter seems to be missing from the Vault docs, has this been removed or replaced with an alternative?
Thanks!

**Comment by chrishoffman** [comment]
@stampycode The advertise address has been replaced with a top level `api_addr`.  See https://www.vaultproject.io/docs/configuration/index.html#api_addr.

**Comment by sirkubax** [comment]
EXTFILE for IP SANS !!!! when signing CSR to CRT
https://www.golinuxcloud.com/openssl-create-client-server-certificate/
openssl x509 -req -in server.csr -CA selfca.crt -CAkey selfca.key -CAcreateserial --extensions v3_req -extfile server.req -out server.crt
