### ISSUE TITLE
Fatal plugin crashes not logged normally - wrong log level

### ISSUE THREAD

**Issue by universam1** [hashicorp/vault#9290]
**Describe the bug**
When plugin crash this information is not forwarded to the standard log level. 
For operators there is no indication that a fatal issue happened.

It requires "DEBUG" log level being enabled to see relevant logs, which is terrible for production systems

**To Reproduce**
1. Let the plugin crash, no error logged just a warning 
`[WARN] error closing client during Kill: err="rpc error: code = Canceled desc = grpc: the client connection is closing"`
2. enable "debug" log level, now ERROR is logged like
`[DEBUG]  panic: runtime error: invalid memory address or nil pointer dereference`

**Expected behavior**
Panics and such are not "debug" but "error" log level

**Environment:**
* Vault Server Version 1.4.2
* Server Operating System/Architecture: AWS ECS

**Comment by ShacharN** [comment]
@ncabatoff any updates on this topic?

**Comment by raskchanky** [comment]
Since it's been awhile with no response, I'm going to close this issue. Please reopen if there's more to add here.
