### ISSUE TITLE
Cannot connect to vault server from the vault cli with selfcreated certificate

### ISSUE THREAD

**Issue by Shinzu** [hashicorp/vault#930]
Hello,

im trying to connect to the vault server with the cli, the server has tls enabled and i provided cert/key by a self created ca . 

VAULT_ADDR	 VAULT_CACERT  env's are set.

if i try to cennect i get following error:

    ~#vault status
    Error initializing client: error reading environment: Error setting up CA path: x509: negative serial number

same is set VAULT_CAPATH instead.

the connection with openssl say following:

    echo quit | openssl s_client -connect server1:8200 -CAfile /etc/ssl/certs/ca-certificates.crt  
    ...
    Start Time: 1452780695
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)

any idea why this happend?

**Comment by jefferai** [comment]
Hi,

Released versions of Go are strict about RFC requirements that the serial number of a certificate is positive. Some CAs (either based off of older RFCs, or just buggy) issue certs with negative serial numbers, which Go does not currently handle.

See https://github.com/golang/go/issues/8265 for a long discussion, but the takeaway is that this behavior is changed in Go 1.6, which is what we are planning to use for Vault 0.5. So one option would be to wait until then (a few weeks...ideally soon after Go 1.6 drops).

In the mean time, you can try another certificate, or build Go and Vault from source.

Sorry -- not much I can do from the Vault end.

**Comment by Shinzu** [comment]
thy for the infos, will try to build it with go 1.6

**Comment by jefferai** [comment]
@Shinzu We're considering releasing 0.5 with a patched version of 1.5.3 to include this fix. Any chance you can send along this CA certificate (not the key, obviously) for testing, since it is a known trigger?

**Comment by Shinzu** [comment]
@jefferai this certificate is long gone, but i did some testing by myself today:

i created a ca for myself and then also a key/certificate for vault with a negative serial:

    openssl req -new -key server2.key -out server2.csr
    openssl x509 -req -in server2.csr -CA rootCA.pem -CAkey rootCA.key -set_serial -12345678 -out server2.crt -days 500 -extfile extfile.cnf

with vault build with go 1.5.2 i was not able start vault:

    vault server -config=/Users/shinzu/Projects/vault/config.hcl
    ==> WARNING: mlock not supported on this system!

      The `mlock` syscall to prevent memory from being swapped to
      disk is not supported on this system. Enabling mlock or
      running Vault on a system with mlock is much more secure.

    Error initializing listener of type tcp: error loading TLS cert: x509: negative serial number

i build then vault with the go 1.6beta2 and i could start vault:

        ./bin/vault_1.6 server -config=/Users/shinzu/Projects/vault/config.hcl                                        
        ==> WARNING: mlock not supported on this system!

      The `mlock` syscall to prevent memory from being swapped to
      disk is not supported on this system. Enabling mlock or
      running Vault on a system with mlock is much more secure.

      ==> Vault server configuration:

             Log Level: info
                    Mlock: supported: false, enabled: true
               Backend: consul (HA available)
     Advertise Address: https://127.0.0.1:8200
            Listener 1: tcp (addr: "127.0.0.1:8200", tls: "enabled")
               Version: Vault v0.4.1

    ==> Vault server started! Log data will stream in below:

connection with a vault (build with go 1.5.2) was not possible:

    vault init                                                                                                
    Error initializing Vault: Put https://127.0.0.1:8200/v1/sys/init: tls: failed to parse certificate from server:   x509: negative serial number

connection with the go 1.6beta2 build was then possible:

    ~/go/src/github.com/hashicorp/vault/bin/vault_1.6 init         
    Key 1:....

if you need this certs files , i can send you this files by gpg encrypted mail, pls also write which file you need exactly

**Comment by jefferai** [comment]
Test certs not used for anything don't really need to go by encrypted mail  :-)

Regardless, you already gave me what I needed -- I didn't know about set_serial. Thanks!

**Comment by jweisner** [comment]
I saw this problem last week, but since nobody else had reported it, I assumed it was something on my side.

This is the result of the reaction people often get from open source maintainers when reporting problems: nobody wants to stick their neck out and get lambasted.
