### ISSUE TITLE
Vault operator raft remove-peer never fails & always 'Peer removed successfully!'

### ISSUE THREAD

**Issue by aphorise** [hashicorp/vault#9318]
A success & 0 exit code is unconditionally returned when [performing `vault operator raft remove-peer NODE_ID`](https://www.vaultproject.io/docs/commands/operator/raft#remove-peer) where an erroneous or non-existing NODE_ID is used. 

The [`/sys/storage/raft/remove-peer` API similarly](https://www.vaultproject.io/api-docs/system/storage/raft#remove-a-node-from-raft-cluster) returns a HTTP-204 **without** any response body (json - like other API calls).

There's presently no way to determine if and when a node has been successfully removed from a raft peers list (without an additional `list-peers` after remove reqeust and comparison - deductively determed rather than empiristic)

**To Reproduce**

```bash
vault operator raft remove-peer NODE_ID ; echo $?
 # Peer removed successfully!
 # 0

vault operator raft remove-peer NODE_ID ; echo $?
 # Peer removed successfully!
 # 0

curl -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"server_id":"NODE_ID"}' https://192.168.178.252:8200/v1/sys/storage/raft/remove-peer
 # < HTTP/2 204
 # < cache-control: no-store
 # < content-type: application/json
 # < date: Thu, 25 Jun 2020 14:02:48 GMT
 # <
 # * Connection #0 to host 192.168.178.253 left intact
```

**Expected behavior**
Provide contextual response which express a HTTP-2xx / 0 exit code and success message that's only returned when a node has actually been removed.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 
    ```bash
    #vagrant@vault2:~$ \
    vault status
     # Key                      Value
     # ---                      -----
     # Recovery Seal Type       shamir
     # Initialized              true
     # Sealed                   false
     # Total Recovery Shares    1
     # Threshold                1
     # Version                  1.4.2
     # Cluster Name             primary
     # Cluster ID               77630d84-f85d-ba19-0d92-5427949ff371
     # HA Enabled               true
     # HA Cluster               https://192.168.178.253:8201
     # HA Mode                  standby
     # Active Node Address      https://192.168.178.253:8200
     # Raft Committed Index     375
     # Raft Applied Index       375    
    ```
* Server Operating System/Architecture: **`uname -pisorv ; # Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) GNU/Linux`**

**Comment by hixichen** [comment]
And, the response code is always `204`:

eg: remove with valid input first time, then remove it again, which suppose to be 404?
Have to get list again to make sure that the peer had been removed from the cluster.


```
~$ curl -k -i -H "X-Vault-Token: $VAULT_TOKEN" --request POST --data '{"server_id": "d01"}' $VAULT_ADDR/v1/sys/storage/raft/remove-peer
HTTP/2 204
cache-control: no-store
content-type: application/json
date: Tue, 22 Jun 2021 00:24:54 GMT
```

```
~$ curl -k -i -H "X-Vault-Token: $VAULT_TOKEN" --request POST --data '{"server_id": "d01"}' $VAULT_ADDR/v1/sys/storage/raft/remove-peer
HTTP/2 204
cache-control: no-store
content-type: application/json
date: Tue, 22 Jun 2021 00:25:51 GMT
```

**Comment by ncabatoff** [comment]
In general Vault provides idempotent behaviour where possible - so just about any other "delete" operation you can think of will have similar behaviour, whether it's an unmount or a KV secret delete or whatnot.  This is sometimes convenient and sometimes less so but it's not something we're likely to change.
