### ISSUE TITLE
Vault doesn't respect max_ttl and ttl defined in rabbitmq config/lease

### ISSUE THREAD

**Issue by cropalato** [hashicorp/vault#9336]
**Describe the bug**
Rabbitmq engine accept max_ttl and ttl configuration, but it fails to use those parameters if it is higher than default max_ttl. Database engine has a different behave (accept max_ttl and ttl override).

**To Reproduce**
1. Enable rabbitmq engine `vault secrets enbale -path=rmq_ttl_test rabbitmq`
2. Configure rabbitmq connection `vault rmq_ttl_test/config/connection ...`
3. Configure rabbitmq lease `vault write rmq_ttl_test/config/lease ttl=<higher than maxt_ttl configured in vault config> max_ttl=`
4. Create rabbitmq rule `vault write rmq_ttl_test/roles/ttl_test1 vhosts='{"/":{"write": ".*", "read": ".*"}}'`
5. Create credential `vault read rmq_dsm-rmqluna-live-shared/creds/ttl_test1`
6. See the output

**Expected behavior**
As database engine, rabbitmq engine should support ttl and max_ttl override.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.4.2
* Vault CLI Version (retrieve with `vault version`): v1.4.2
* Server Operating System/Architecture: Linux/x86_64

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
{
  "storage": {
    "raft": {
      "path": "/opt/data/vault/storage",
      "node_id": "foo-vault007-001",
      "retry_join": {
        "leader_api_addr": "https://****:8200",
        "leader_ca_cer_file": "/etc/pki/tls/private/foo*.ca-bundle",
        "leader_client_cert_file": "/etc/pki/tls/private/foo*.crt",
        "leader_client_key_file": "/etc/pki/tls/private/foo*.key"
      }
    }
  },
  "listener": {
    "tcp": {
      "address": "0.0.0.0:8200",
      "cluster_adress": "***:8201",
      "tls_disable": 0,
      "tls_cert_file": "/etc/pki/tls/private/tls.crt",
      "tls_key_file": "/etc/pki/tls/private/tls.key",
      "tls_min_version": "tls12"
    }
  },
  "default_lease_ttl": "24h",
  "max_lease_ttl": "24h",
  "ui": true,
  "log_level": "DEBUG",
  "cluster_name": "foo.vault007",
  "api_addr": "https://****:8200",
  "cluster_addr": "https://****:8201",
  "disable_mlock": true
}

```

**Additional context**

**Comment by meet101** [comment]
@cropalato I was able to fix same issue by following this https://developer.hashicorp.com/vault/docs/commands/secrets/tune

**Comment by hsimon-hashicorp** [comment]
Closing due to workaround provided. Please feel free to re-open if needed, or open a new issue. Thanks!
