### ISSUE TITLE
The first example under policies doesn't work.

### ISSUE THREAD

**Issue by shallquist** [hashicorp/vault#9337]
**Describe the bug**
I followed the example in the policies documentation and tried the following simple policy:
```
path "secret/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "secret/admins" {
  capabilities = ["deny"]
}
```
**Expected behavior**
I expected that users who are members of the group that the policy was assigned to would be able to access and create secrets everywhere in the path below secrets except admins.  However, those user were able to read the secrets under the secret/admins path.

**Describe the bug**
I also tried this:
```
path "secret/*" {
  capabilities = ["list"]
}

path "secret/users/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "secret/users/" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "secret/users" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
```

**Expected behavior**
I expected users to be able to create and read secrets in the secret/users path, however I get the message that

> You don't have access to secret/.

I've tried many different combinations and nothing seems to work according to the documentation.

I am running Vault  1.4.2 Ubuntu 19.2 Linux (64-bit).

**Comment by ncabatoff** [comment]
Hi @shallquist,

I'm not sure which docs page you were looking at (link?) but I suspect you've run afoul of a common confusion resulting from us having changed how policies need to be setup for KVv1 versus KVv2 mounts.  By default a kv mount will be v2, which needs slightly different ACL paths, as detailed here: https://www.vaultproject.io/docs/secrets/kv/kv-v2#acl-rules

**Comment by shallquist** [comment]
Thanks,  That fixed my problem.  BTW  The links I was referring to when creating policies were:
https://www.vaultproject.io/docs/concepts/policies

Policies | Vault by Hashicorp

|  |  | 
Policies | Vault by Hashicorp
 |




I did now notice that the first link has /data/ included in the path however, the written documentation never mentions it's required.  I just assumed that was included as an example and not a requirement.
Thanks,  Steig Hallquist

    On Monday, July 6, 2020, 11:15:26 AM EDT, ncabatoff <notifications@github.com> wrote:  
 
 


Hi @shallquist,

I'm not sure which docs page you were looking at (link?) but I suspect you've run afoul of a common confusion resulting from us having changed how policies need to be setup for KVv1 versus KVv2 mounts. By default a kv mount will be v2, which needs slightly different ACL paths, as detailed here: https://www.vaultproject.io/docs/secrets/kv/kv-v2#acl-rules

**Comment by aphorise** [comment]
Closing as @shallquist has resolved their issue. For future reference the 1-5 P1+P2 rules detailed further down the page of the policy docs are still relevant:

 - [Policy Syntax](https://www.vaultproject.io/docs/concepts/policies#policy-syntax)
