### ISSUE TITLE
Vault Service systemd Question

### ISSUE THREAD

**Issue by st-isidore-de-seville** [hashicorp/vault#935]
Hello.  I am writing a systemd service unit for Vault.  In doing the same for Consul, I read in the docs that various Unix signals sent control how Consul leaves the cluster.  I did not see any such documentation regarding Vault and wondered if a particular Unix signal should be sent to Vault to kill it?

Thanks in advance!

**Comment by jefferai** [comment]
Hi there,

SIGINT and SIGTERM both work (they are totally interchangeable for this purpose).

Good luck!

**Comment by st-isidore-de-seville** [comment]
Thanks @jefferai!
