### ISSUE TITLE
Hashicorp Vault- General Usage related queries

### ISSUE THREAD

**Issue by banandh** [hashicorp/vault#9358]
Hi , 

Im new to hashicrop vault usage. I need some general information's.

1. Can I have  LDAP authentication for vault sever and at path level enabling AppRole Login, so that my spring cloud vault can connect to vault using the appRole login and if there are any config change i can do at vault server using LDAP login  ?? 

2. I have an use case of singing JWT using certificates. Is there are any possibility to read certificates from vault??
I have generated signed certificate from Vault server but i need to dynamically read those in my spring application as similar to what im doing for secrets. - Is there any possibility of doing it and need reference for the same.

Thanks for any help.

**Comment by ncabatoff** [comment]
Hi @banandh,

Github is not the best place to ask questions like this.  I suggest you try our [community forum](https://discuss.hashicorp.com/c/vault) instead.
