### ISSUE TITLE
Could not detect default username. Please provide one explicitly

### ISSUE THREAD

**Issue by sokoow** [hashicorp/vault#938]
Got this error when trying to configure postgres as per  https://www.vaultproject.io/docs/secrets/postgresql/index.html. Anyone knows what to do here ?

**Comment by jefferai** [comment]
Hi there,

Can you provide your parameters (with the password obfuscated)?

Thanks!

**Comment by sokoow** [comment]
```
vault write postgresql/config/connection value="postgresql://superuser1:XXXXXX@postgres.pharaoh.local:5432/postgres"
```

it's telling me same when I use root account also

**Comment by jefferai** [comment]
What version of Vault are you using?

**Comment by sokoow** [comment]
Vault v0.5.0-dev (996cb54b9926d6c6e15e739e437eaabf8af499f9+CHANGES)

**Comment by jefferai** [comment]
How did you build it? `make dev`? Or some other way?

**Comment by sokoow** [comment]
I think it was ```make dev```, does it matter ?

**Comment by jefferai** [comment]
Yes, it can, because `make dev` uses the versions of libraries in Godeps, whereas e.g. "go install" uses your system versions. I don't see anything obvious in the URL that is wrong, so I thought maybe it was a change in e.g. `pq`.

I'll try to reproduce this...

**Comment by sokoow** [comment]
ok thanks, in meanwhile I'll go and build using make dev... to be sure

**Comment by sokoow** [comment]
just built with make dev, same

**Comment by jefferai** [comment]
Unfortunately I'm not entirely sure what to tell you. If I start up Postgres in a container and use your connection string, with the username/port changed and turning off SSL:
```
$ vault write postgresql/config/connection value="postgresql://postgres:XXXXXX@localhost:32768/postgres?sslmode=disable"
Success! Data written to: postgresql/config/connection
```
That error is coming from `pq`, the library we use for Postgres. It first tries to parse the URL, and then if a user is not found there, it tries to find the current user's name. If it can't look that up, it throws that error.

**Comment by jefferai** [comment]
It also works for me when using `superuser1` as the username.

**Comment by jefferai** [comment]
If I alias your host, same deal:
```
$ vault write postgresql/config/connection value="postgresql://superuser1:XXXXXX@postgres.pharaoh.local:32772/postgres?sslmode=disable"
Success! Data written to: postgresql/config/connection
```
At this point my suggestion would be to file a bug against https://github.com/lib/pq.

**Comment by jefferai** [comment]
Hi,

Please reopen if you have further info. Thanks!
