### ISSUE TITLE
Merge data from multiple Vault clusters

### ISSUE THREAD

**Issue by solitarysp** [hashicorp/vault#9396]
Our company is using vault to encrypt, decode...etc...
But :( Unfortunately, we have 3 server vault with different master keys. Vault servers have a lot of data. I need to move the servers to a single server.

For example 1:
Data of servers 1 and 2 moves to server 3. Later I could then remove servers 1 and 2.
Or 
Example 2:
I created a new server vault. Data of servers 1, 2, and 3 moves to the new server.

Or in some way or idea that I can do it but I need help :(.
Thanks

**Comment by ncabatoff** [comment]
Hi @solitarysp,

Sadly, I don't think there is a good general way right now to merge multiple Vault cluster's data.  You may have to script something.

**Comment by solitarysp** [comment]
Thanks
