### ISSUE TITLE
LDAP Support as Auth Backend

### ISSUE THREAD

**Issue by Govinda-Fichtner** [hashicorp/vault#94]
Are there any plans to support LDAP as an auth backend?

This would have to be added in 
`https://github.com/hashicorp/vault/tree/master/builtin/credential`
in a similar fashion to the existing auth backends. Right?

By the way is there a roadmap for vault?

**Comment by keithchambers** [comment]
:+1: This would be huge for Enterprise users.

**Comment by mtougeron** [comment]
:+1: on this

**Comment by tehmaspc** [comment]
+1

**Comment by xtrasmal** [comment]
Yeah would like that too. Working with FreeIPA at the moment and it might be a good fit in future.

**Comment by rasky** [comment]
I've begun implementation in my fork (rasky/vault branch ldap). Authentication part is done (though I'm not sure all configuration knobs are exposed), but it's still missing authorization part. I plan to expose an endpoint to configure a mapping between LDAP groups and policies.

**Comment by armon** [comment]
@rasky If you want to open a WIP PR, I'm happy to provide early feedback!

**Comment by stewarda** [comment]
LDAP integration would be huge, very much looking forward to seeing what Rasky puts forth
