### ISSUE TITLE
Default connect_timeout in cassandra secret plugin is not according to docs

### ISSUE THREAD

**Issue by enudler** [hashicorp/vault#9400]
**Describe the bug**
When setting up Cassandra secret backend and trying to get creds to Cassandra I'm getting timeouts and errors like this:
```
{
    "errors": [
        "1 error occurred:\n\t* read tcp 192.168.80.3:49848->192.168.80.2:9042: i/o timeout\n\n"
    ]
}

 
```

I suspect that the default "connect_timeout" is not a string of "5s" but an integer with a value of 5.

**To Reproduce**
1. mount secret backend of type 'database'
2. create a role with creation statement
3. configure a connection to Cassandra without "connect_timeout" (/v1/database/config/{dbName})
4. get creds "v1/database/creds/{roleName}"
5. see the error (i/o timeout)
6. configure new connection to Cassandra this time with default "connect_timeout" from the docs which is 5s
7. get creds "v1/database/creds/{roleName}"
8. all good, creds returned 
**Expected behavior**
no timeouts

**Environment:**
* Vault Server Version: 1.4.2
* Server Operating System/Architecture: vault 1.4.2 running in dev mode (docker) and  Cassandra (docker)

**Comment by aphorise** [comment]
This was addressed in: [fix cassandra db plugin timeout to 5s as in docs #12443](https://github.com/hashicorp/vault/pull/12443)
Hey @enudler - thanks for reporting this.
