### ISSUE TITLE
missing connection_url with postrgresql backend and VAULT_PG_CONNECTION_URL setted

### ISSUE THREAD

**Issue by vasiliy-shakhunov-advascale** [hashicorp/vault#9422]
**Describe the bug**
VAULT_PG_CONNECTION_URL is not used with vault postrgresql backend. It stll require connection_url

**To Reproduce**
Set VAULT_PG_CONNECTION_URL in /etc/environment
```hcl
storage "postgresql" {
  connection_url = ""
}
```

**Expected behavior**
Vault is connecting to postrgresql backend.
But got in the logs: "vault: Error initializing storage of type postgresql: missing connection_url"

**Environment:**
* Vault Server Version (retrieve with `vault status`): Vault v1.4.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.4.2
* Server Operating System/Architecture: aws ec2

Vault server configuration file(s):

```hcl
storage "postgresql" {
  connection_url = ""
}
```

**Comment by webchi** [comment]
@ncabatoff hi. I have resolved that issue. It was strange systemd behavior with requires pointing to  /etc/environment to have this env variables.
