### ISSUE TITLE
Unable to specify TLS options for Consul secret backend

### ISSUE THREAD

**Issue by bodgit** [hashicorp/vault#944]
I have Vault configured to use Consul as a storage backend, I'm using self-signed certs to TLS all the things and have configured both Consul and Vault such that Vault is happy writing its state to Consul without needing to disable TLS verification.

I've also configured the Consul secret backend and specified the scheme to be `https` however when I try and request a Consul API token through Vault I get `x509: certificate signed by unknown authority` but I see no way to set the CA certificate used to verify the certificate presented by Consul. I mistakenly thought it might use the same one I specified in the `backend` section but that doesn't appear to be the case.

**Comment by jefferai** [comment]
@bodgit Do you mean "to verify the certificate presented by Vault"?

**Comment by jefferai** [comment]
@bodgit Assuming that's what you meant, and assuming you are trying to use the Vault CLI to talk to Vault when you are seeing this problem, use the `-ca-cert` or `-ca-path` flags to the CLI, or set the `VAULT_CACERT` or `VAULT_CAPATH` environment variable.

**Comment by bodgit** [comment]
Not quite, sorry if that wasn't clear. I can access other parts of Vault fine, but when I do `vault read consul/creds/<role>` I get an error from Vault that it doesn't trust the certificate presented by Consul.

**Comment by jefferai** [comment]
@bodgit Ah, I see. It doesn't look like that backend supports setting a CA certificate at this time. It should default to your system certs, however, so if you put your CA cert in the appropriate system path it should work.

**Comment by satheeshaGowda** [comment]
Am running into same problem, with Vault Version: 0.7.0, and above suggestion is not working, is it working for anyone out there ? thanks please.

**Comment by jefferai** [comment]
@satheeshaGowda You're not stating what your exact issue is, but note that we use the official API client for Consul so I believe it should honor Consul env vars for setting TLS settings.

**Comment by jaloren** [comment]
I have also encountered this problem. After some looking through the vault source code and some educated guessing, I was able to make this work. The trick is to set the following environment variables **before** the vault process starts up.

```
CONSUL_CACERT="/opt/vault/config/keys/server.ca.pem"
CONSUL_CLIENT_CERT="/opt/vault/config/keys/server.cert.pem"
CONSUL_CLIENT_KEY= "/opt/vault/config/keys/server.key.pem"
```

Note you are setting consul environment variables in the docker container or VM where the vault process is running and *not* on the consul agent that vault is connecting to. I do think its a bit peculiar that there's no way to specify these settings on the consul/config/access path in vault. This also seems to be undocumented as well.

**Comment by Nazrax** [comment]
I'd also like to see this implemented.

**Comment by Crizstian** [comment]
I have done the following and still no luck

```
root@dc1-consul-server:/home/vagrant# export CONSUL_HTTP_ADDR=https://172.20.20.11:8501
root@dc1-consul-server:/home/vagrant# export CONSUL_CACERT=/var/vault/config/ca.crt.pem
root@dc1-consul-server:/home/vagrant# export CONSUL_CLIENT_CERT=/var/vault/config/server.crt.pem
root@dc1-consul-server:/home/vagrant# export CONSUL_CLIENT_KEY=/var/vault/config/server.key.pem
root@dc1-consul-server:/home/vagrant# VAULT_TOKEN=s.ROylb229oEYsMyWlHvKIuJrz vault read -format=json consul/creds/operator-prefix
Error reading consul/creds/operator-prefix: Error making API request.

URL: GET https://172.20.20.11:8200/v1/consul/creds/operator-prefix
Code: 400. Errors:

* Put https://172.20.20.11:8501/v1/acl/token: x509: certificate signed by unknown authority
```

**Comment by filintod** [comment]
@Crizstian probably the cert is unknown for your system you could test with `export CONSUL_HTTP_SSL_VERIFY=false`, also if the IP 172.20.20.11 is not part of the cert or altnames it might fail too.

**Comment by michelvocks** [comment]
Closing this since it has been resolved with https://github.com/hashicorp/vault/pull/8253

**Comment by bodgit** [comment]
Yay, only took four years! 🙄
