### ISSUE TITLE
DOCS: API documentation for endpoint sys/internal/ui/resultant-acl

### ISSUE THREAD

**Issue by stuartpurgavie** [hashicorp/vault#9468]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be documentation for the endpoint `sys/internal/ui/resultant-acl` however it is present in the `default` policy and obviously returns data.

**Describe the solution you'd like**
Would like to see documentation on the endpoint, including what parameters it takes, if any.

**Explain any additional use-cases**
Possible additional use case for being able to provide a token, entity, or role to the endpoint as a parameter to see what the resultant ACL would be for that object, if it does not exist. Without documentation it's hard to know, but seems likely it's an introspection endpoint only, which is only useful to a given token.

**Additional context**
Was attempting to [troubleshoot an ACL issue](https://groups.google.com/forum/#!msg/vault-tool/PbwI7iDg5WY/nUmRXZDcBgAJ) where when `+` is used as a path segment wildcard, there are some unexpected resultant ACLs. This seemed like it could be a useful endpoint for figuring out what was going on in the user's scenario. Yes, the `sys/capabilities*` family of endpoints does exist, but you have to know the paths in advance to query, whereas the `resultant-acl` endpoint simply lists all endpoints for you without passing paths as parameters.

**Comment by ncabatoff** [comment]
Hi @stuartpurgavie ,

I won't rule out the possibility that we document this, but the `internal` part of the path is an indicator that this endpoint is deliberately undocumented: it's used by the UI, and you can call it if you want, but it's not part of the regular API, insofar as we make no promises not to break it between versions.

**Comment by v6** [comment]
It's good to know about.

Kind of interesting that there's this function and the relatively anemic https://www.vaultproject.io/api/system/capabilities endpoint.

**Comment by v6** [comment]
@burstingninja

**Comment by aphorise** [comment]
There is already:
 - https://www.vaultproject.io/api-docs/system/internal-ui-resultant-acl
Hey @stuartpurgavie were you after something more or are you ok to close?
