### ISSUE TITLE
Ability to import PKI certificates

### ISSUE THREAD

**Issue by aeria** [hashicorp/vault#947]
Currently you can BYO a root CA. It would be great to be about to POST to /pki/cert/<serial> or similar.

It'd be nice to be able to import existing certificates that are valid under the same CA.

Example scenario would be a large vault, and an off site vault with a sub-set of of these certificates.

Ability to retrieve the Private key from an existing vault would also be a bonus to assisting this, but could  assume that these are stored elsewhere or in the generic secret after generation.

**Comment by jefferai** [comment]
Interesting idea!

**Comment by aeria** [comment]
Any reason for closing?

**Comment by vishalnayak** [comment]
@aeria 

Some of the Vault issues were closed by mistake from a syncing software. We apologize for the confusion caused. We have reopened the issues that were closed and are investigating the problem that caused this. Again, we are very sorry for the inconvenience.

**Comment by anotheral** [comment]
This fits my use case, which is to migrate our internal CA into vault without having to distribute a new certificate to the entire organization.  I understand why Vault doesn't support this for security reasons, but it is a migration path into using the PKI functionality for organizations who want to adopt vault.

**Comment by jefferai** [comment]
@anotheral I'm not following your use-case there. You can migrate your CA into Vault, but why does that then require distributing new certificates to the entire organization?

**Comment by jefferai** [comment]
Closing as we do not plan to implement this currently.
