### ISSUE TITLE
DOCS: raft snapshots

### ISSUE THREAD

**Issue by assareh** [hashicorp/vault#9481]
Hi team,

The documentation on raft snapshots is minimal. Perhaps we can take some verbiage from the [Consul](https://www.consul.io/docs/commands/snapshot) docs. Other questions I have heard from my customers are: 

- guidance on whether this is an offline or online operation
- guidance on whether this should be done once per vault server node, or once per cluster (and if so, from which node)

Thanks for reading!

**Comment by aphorise** [comment]
Closing since the learn guides & documentation now include snapshot guidance:

 - Learn: [Vault HA Cluster with Integrated Storage](https://learn.hashicorp.com/tutorials/vault/raft-storage)
 - Docs: [operator raft](https://www.vaultproject.io/docs/commands/operator/raft#snapshot)
