### ISSUE TITLE
VAULT_RAFT_PATH env var does not work or docs are unclear

### ISSUE THREAD

**Issue by srhb** [hashicorp/vault#9484]
**Describe the bug**
According to the raft backend docs,

> path (string: "") – The file system path where all the Vault data gets stored. This value can be overridden by setting the VAULT_RAFT_PATH environment variable.

However, unless overridden really means "you must still set the option in the config file", it appears that `NewFSM` prevents the use of `VAULT_RAFT_PATH` because the env var is never checked there before bailing. https://github.com/hashicorp/vault/blob/3118ed77b72c3367ebfbcdb73a41f96f70b5e05d/physical/raft/fsm.go#L89-L92

Likely, either `NewFSM` should also get the env var, or the documentation should be fixed.

**To Reproduce**
Set `VAULT_RAFT_PATH`. Do not set path in config.
Start vault.

**Expected behavior**
Vault starts up as if path were defined with the same value as `VAULT_RAFT_PATH`

**Actual behaviour**
`Error initializing storage of type raft: failed to create fsm: 'path' must be set`

**Environment:**
* Vault Server Version 1.3.6

**Comment by aphorise** [comment]
>     * Vault Server Version 1.3.6

@srhb I suspect its the same behavior in the [latest 1.4.3 & release-candidates](https://releases.hashicorp.com/vault/) as the source looks similar - can you kindly confirm?

**Comment by ncabatoff** [comment]
This was fixed in #9128.
