### ISSUE TITLE
Vault client fails with "net/http: TLS handshake timeout"

### ISSUE THREAD

**Issue by rsk0** [hashicorp/vault#9492]
**Describe the bug**
Vault client fails with "net/http: TLS handshake timeout"

**To Reproduce**
1. Be on macOS
2. Make about 120 certificate exceptions, have them added to your Keychain certificates
3. Attempt Vault login (or, presumably, any hashitool action requiring TLS)

```
% vault login -field=token -method=ldap username=$USER
Password (will be hidden):
Error authenticating: Put "https://vault.mydomain.com:8200/v1/auth/ldap/login/myusername": net/http: TLS handshake timeout
```

**Environment:**
* Vault Server 1.3.4+prem
* Vault CLI v1.4.2
* macOS Catalina 10.15.5

**Additional context**
IIRC, there seemed to be a period of erratic failures before this began failing consistently.  Those might have been before I upgraded from Sierra.  The increase in failure frequency might have corresponded to a continuing accumulation of certificates that gradually slowed the process down and/or to OS upgrade.

**Comment by ncabatoff** [comment]
Hi @rsk0,

This doesn't sound like a Vault issue.  If you're timing out during the TLS handshake trying to talk to Vault, that probably has more to do with your system or network health than anything else.  You might want to look in the vault logs to see if there are any errors that might provide another explanation.  You could also try posting on our discussion [forum](https://discuss.hashicorp.com/c/vault) to see if anyone else has any ideas.
