### ISSUE TITLE
Vault: upstream rate limited error

### ISSUE THREAD

**Issue by ananthbh-debug** [hashicorp/vault#9497]
Hi,

We use Hashicorp Vault for authenticating our pods in the EKS clusters we run in us-east-1 and eu-central-1.
This means the pods make a call to Vault, which then queries the API server to authenticate the request.

However, it seems that, in our systems, we are being rate limited and seeing an error message in vault pod logs 

"error": "1 error occurred:\n\t* upstream rate limited\n\n",

 Could you please let me know this particular error message is due to which API from AWS side and the reason for this error?

**Environment:**
* Vault Server Version (retrieve with `vault status`): "version": "1.2.2"
* Vault CLI Version (retrieve with `vault version`): Vault v1.2.2

**Comment by ncabatoff** [comment]
Hi @ananthbh-debug ,

I'm afraid I don't know the answer to your question.  That error is based on this code:

```
func CheckAWSError(err error) error {
	// IsErrorThrottle will check if the error returned is one that matches
	// known request limiting errors:
	// https://github.com/aws/aws-sdk-go/blob/488d634b5a699b9118ac2befb5135922b4a77210/aws/request/retryer.go#L35
	if awsRequest.IsErrorThrottle(err) {
		return ErrUpstreamRateLimited
	}
```

which I believe is used generically in handling calls to various AWS APIs.  Do you have any more context for the error?

**Comment by raskchanky** [comment]
Hi @ananthbh-debug,

We haven’t heard back from you on this for a while. I’m going to close this for now, but please feel free to re-open it with additional information!
