### ISSUE TITLE
how to build vault in window?

### ISSUE THREAD

**Issue by ftyszyx** [hashicorp/vault#95]
i want to build the source in vault ,how can i do that?

**Comment by sethvargo** [comment]
Hi @ftyszyx 

Thank you for opening an issue. In order to build Vault, you will need Go 1.4+. Then clone the repository and run `make dev`. You can find more information in the [README](https://github.com/hashicorp/vault#developing-vault). did you hit a specific bug or error?

**Comment by ceh** [comment]
I can volunteer to provide a make.bat, similar to the [one] in Terraform, if that'd help.

The tests does not currently pass on Windows though. I might have a stab at that as well.

[one]: https://github.com/hashicorp/terraform/blob/master/make.bat

**Comment by mitchellh** [comment]
@ceh That'd be great on both points, we haven't had a chance to test on Windows yet.

**Comment by ftyszyx** [comment]
thank you

**Comment by ceh** [comment]
@ftyszyx Did it solve your use case? Is there anything else you need?

**Comment by drusellers** [comment]
I have go 1.4 / Windows Server 2012 R2 / followed the instructions on the home page. :) `make.bat` still fails (guessing tests) but `make.bat dev` seems to work.

**Comment by drusellers** [comment]
Trying to run `vault.exe server -dev` is giving me an error though.

![image](https://cloud.githubusercontent.com/assets/63355/7443393/947ab80e-f10c-11e4-8cca-c2e6069d4c29.png)

**Comment by ceh** [comment]
@drusellers Yes, that's a correct observation. Running make.bat without a target runs the tests per default, which still fail.

Windows binaries will most likely keep failing until all tests pass.

**Comment by drusellers** [comment]
@ceh I figured, just wanted to give an update on building with Windows.

**Comment by ceh** [comment]
For the record, [7bbc827590 test log](https://github.com/ceh/cb-log/blob/master/ceh-windows-amd64/github.com/hashicorp/vault/daily/2015-05-04/7bbc8275906c7d1ed4efad223199662ad8371d17.log).

**Comment by ftyszyx** [comment]
@ceh 
i run "make" ,there is a error:go exit status 2, 
![image](https://cloud.githubusercontent.com/assets/3063779/7465853/48de9108-f30b-11e4-8253-b6c37124d3cb.png)

but when i run "make dev",it's ok.

**Comment by armon** [comment]
I've pushed a change that switches using sh to cmd, hopefully this resolves this. https://github.com/hashicorp/vault/commit/d9c5a691c8ff2ebe59a70319d8a170ad11f33e6f

**Comment by sethvargo** [comment]
Hi @ftyszyx @drusellers is this still an issue?

**Comment by drusellers** [comment]
It was, but currently (I just pulled down the latest of master) `make.bat` is giving me a `godep: go exit status 1` - I'm pretty sure its a test that's failing is the issue. `make.bat dev` is giving me an executable that is running.
