### ISSUE TITLE
Postgres secret backend locks up after a certain amount of time

### ISSUE THREAD

**Issue by hobbeswalsh** [hashicorp/vault#950]
Hi there,

I'm using the Postgres secret backend to dynamically generate secrets for one of our production databases. Immediately after I mount the secret backend and configure it, a `vault read` succeeds without a problem, and I can see my newly-created user in the Postgres database:

```
postgres=# \du
                                                  List of roles
                       Role name                       |                 Attributes                  | Member of 
-------------------------------------------------------+---------------------------------------------+-----------
 daemon                                                |                                             | {}
 admin                                                 | Create DB                                   | {}
 ldap-hobbeswalsh-f7318add-1ae7-d7e1-9653-24242d4e0c30 | Password valid until 2016-01-21 06:50:56+00 | {}
 postgres                                              | Superuser, Create role, Create DB           | {}
 readonly                                              |                                             | {}
```

However, when I walk away from the console and then try to get a password later, the Vault server freezes up.

```
➤ vault read postgresql/creds/readonly
Error reading postgresql/creds/readonly: Error making API request.

URL: GET https://vault.mydomain.com/v1/postgresql/creds/readonly
Code: 504. Raw Message:

```

I see that the Vault server has active connections to our database server:

```
vault$ netstat -tn | grep '<DB_IP>'
tcp        0      0 10.128.1.36:41389       <DB_IP>:5432      ESTABLISHED
tcp        0      0 10.128.1.36:40861       <DB_IP>:5432      ESTABLISHED
tcp        0      0 10.128.1.36:41429       <DB_IP>:5432      ESTABLISHED
tcp        0      0 10.128.1.36:41388       <DB_IP>:5432      ESTABLISHED
```

But a `tcpdump` does not show any activity to that IP address when I perform a `vault read` for some credentials.

The Vault server is a standard EC2 instance in a VPC. The database server is in our data center, so there are several routers (and firewalls!) that a connection from Vault to the database would have to traverse. I suppose my three questions are:

 * What can I do to further troubleshoot this?
 * Why does Vault think the best policy is to just keep a connection open to the database forever (I could be misunderstanding, but I think that's what [this stanza](https://github.com/hashicorp/vault/blob/master/builtin/logical/postgresql/backend.go#L59-L61) is about)?
 * What's the deal with `netstat` showing this connection as `ESTABLISHED`? Shouldn't I see Vault send out some TCP chatter when I request a secret?

Thanks a lot.

**Comment by jefferai** [comment]
@hobbeswalsh the Postgres library in use is I think built on the underlying Go sql layer, which uses connection pools. It's common for it to have long running connections. It's not common for it to freeze up. :-)

I have a few guesses as to what's going on, but these are suppositions:

1. It's not actually frozen forever, and will eventually time out and give an error, but it's doing TCPish things causing it to take a long time because the connection was actually severed
2. The connection was severed because one of the firewalls along the way is losing track of if in its state, possibly due to e.g. a lack of heartbeats

One thing that might be possible would be to use https://golang.org/pkg/database/sql/#DB.Ping within the `DB()` function to verify it before returning, establishing a new connection if needed. I don't know if that would solve the problem, however, or just present the problem in a different location.

Are you okay building your own version of Vault? I can make you one that behaves in that way and we can see if it fixes the problem.

**Comment by hobbeswalsh** [comment]
I'm fine building our own version of Vault, thanks. This is our production instance so we'll need to be careful about taking down, restarting, and unsealing, but that's our problem and not yours.

I already have the code checked out in my `$GOPATH`, so if you want to just push a commit and give me instructions on how to properly build it, that would be great. One other thing to note is that our server is currently at 0.3.1, as are our clients. Will this require a client update (I assume you're going to fork 0.4)?

Thanks!

**Comment by jefferai** [comment]
It would require a client update generally -- many things would likely work, but some things wouldn't, and I honestly am not sure what might break between client/server. I can fork 0.3.1 if you need...would that be preferable?

**Comment by hobbeswalsh** [comment]
If we're going to have to stop and start all of our Vault servers, we may as well upgrade. The HTTP (read: `hvac`) clients will still work, right?

**Comment by jefferai** [comment]
@hobbeswalsh I honestly don't know re: `hvac`. It looks like they stay pretty current so it seems like it would work but may require ensuring that that is upgraded too.

If you'd rather wait, I'm happy to branch off of 0.3.1. 0.5 will be out soonish so you could save your upgrade cycle (clients, libs) for an upgrade to that.

**Comment by jefferai** [comment]
@hobbeswalsh Actually, are you on IRC or any other real-time communication tool? It'd be nice to ask some questions in real-time so that we can try to do this in as few start/stop cycles in your production as possible.

**Comment by hobbeswalsh** [comment]
I'll be in `#vault-tool` on Freenode; if there's a Slack channel that's fine too.

**Comment by jefferai** [comment]
I've got a fresh new branch for you to try: https://github.com/hashicorp/vault/tree/issue-950 -- based off of 0.4.1 (which is 0.4.0 built against the security fix in Go 1.5.3).

It adds max_idle_connections as a configuration parameter to the backend. Try setting it to a negative value and let me know how that goes.

**Comment by hobbeswalsh** [comment]
aha! progress.

I left a `psql` prompt running on the Vault server for a long time...

```
postgres=> \dt;
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Succeeded.
```

So the connection _is_ getting severed. I believe your patch should help, though I'll have to figure out a good time to do the maintenance, upgrade, and unseal.

**Comment by jefferai** [comment]
It probably will; in theory the go library should reconnect like your psql did but it seems something is going wrong.

**Comment by hobbeswalsh** [comment]
Okay, we just swapped out our production Vault server instances with this new version. It appears to be working. An initial read of Postgres credentials was successful; one an hour later was too. I'm going to wait until later this afternoon and try again.

Will this commit make it into Vault 0.5.0?

**Comment by jefferai** [comment]
Sure will, if it ends up being successful. The weekend might be a good test; let me know how things are on Monday?

**Comment by jefferai** [comment]
^ is the PR against `master`. It's marked for the 0.5.0 milestone, but I'll wait on merging it until I get confirmation.

**Comment by hobbeswalsh** [comment]
@jefferai This works after a weekend of not reading from Vault. Thanks a lot for the patch. I'd say it's ready to go!

**Comment by jefferai** [comment]
Great!
