### ISSUE TITLE
Secret backend for Azure

### ISSUE THREAD

**Issue by joaocc** [hashicorp/vault#952]
Any plans to add Azure as a supported secret backend?
Thx

**Comment by jefferai** [comment]
It is not currently on the internal roadmap.

**Comment by lmickh** [comment]
@jefferai There is interest in my group to use Vault to manage Azure AD service principals via a secret backend in the same fashion as the AWS IAM backend and the GCP backend feature request (#1052).  If there is a formal process to get feature requests on the roadmap, let me know.

If you need to gauge interest, could we re-open this issue?  Don't want to spawn new ones if there is another internal reason for closing this such as the current state of [azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go).

**Comment by vishalnayak** [comment]
@lmickh Its just that internally we have other items lined up and currently we don't have this in the roadmap. Having said that, if anyone wants to tackle this, we would be happy to review an RFC followed by a PR.

**Comment by uepoch** [comment]
Hello @jefferai and @vishalnayak , we would currently be interested in contributing for this if it's not on the short-term roadmap, do you have any RFC guidelines we must follow ?

The main usecase we see is the same as for AWS and GCP backends, to be able to generate leased identities with binding/permissions

**Comment by kalafut** [comment]
Thanks for your interest in helping out with this! This feature is now on our roadmap and is being actively developed internally.

**Comment by uepoch** [comment]
Can you provide an ETA / target version for this ?

**Comment by kalafut** [comment]
It's in active development and will be in the next release after it's finished.

**Comment by jorisd** [comment]
Hello,
Does it include support for Storage account SAS token generation ?

**Comment by jorisd** [comment]
@kalafut can you show us your roadmap or explain the scope of work being done ? This issue description is vague.

**Comment by kalafut** [comment]
Regarding scope, the goals for Azure secrets are similar to those of other secrets engines such as [AWS](https://www.vaultproject.io/docs/secrets/aws/index.html) and [GCP](https://www.vaultproject.io/docs/secrets/gcp/index.html). But as this is in work in progress, I don’t have more details to give at this time.

**Comment by alphalzh** [comment]
Any updates on the progress of this task?

**Comment by kalafut** [comment]
Azure Secrets is in the 0.11.0-beta1 release that was just [announced](https://groups.google.com/forum/#!topic/vault-tool/MfnKdP_TJAg). You can take a look at the [plugin repo](https://github.com/hashicorp/vault-plugin-secrets-azure) if you're interested. Docs aren't yet published on the main Vault Doc website, but you can check out the source: [docs](https://github.com/hashicorp/vault/blob/master/website/source/docs/secrets/azure/index.html.md) / [api](https://github.com/hashicorp/vault/blob/master/website/source/api/secret/azure/index.html.md).
