### ISSUE TITLE
AWS Secret Lease Deleted before TTL constantly 

### ISSUE THREAD

**Issue by Isan-Rivkin** [hashicorp/vault#9532]
Hi, 

**Describe the bug**

I am trying to use the AWS secrets engine feature to manage iam_user credentials with a TTL. 
After I configured the secret engine with 1-year default TTL and some policy for example "test". 
**I am creating credentials and updating their TTL to 4 months** (for example) using the renew subcommand in vault CLI. 
After approx a week the lease get's deleted even though the TTL was much longer. 

**To Reproduce**

0. Created an AWS Secret engine with all the permissions required. Default TTL for policies - 1 year.

1. Create a new Role: 
```
vault write aws-my-name/roles/test \                                                                  (arn:aws:eks:us-east-
credential_type=iam_user \
policy_document=-<<EOF
{
// some IAM policy 
}
EOF
```
2.Create new Lease: 
```
vault read aws-data-external-clients/creds/test
```

3. Update TTL to ~4month 
```
vault lease renew -increment=10368000  <lease-id>
```

Everything works fine. When I look at the TTL in the UI I see the expected expiration time. 
Then, after 6-7 days each time, I can see in CloudTrail that the lease is deleted and all its related aws resources (I am user, policy) 

**Expected behavior**

That the lease will be deleted at the TTL specified running the "renew" subcommand. 

**Environment:**
* Vault Server Version (retrieve with `vault status`):
➜  ~ vault status                                                                                                                
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.0.1
Cluster Name    vault-cluster-xxx
Cluster ID      xxxx-eb2e-8fb1-a2f7-xxx
HA Enabled      true
HA Cluster      xxxurlxxx
HA Mode         active
```

* Vault CLI Version (retrieve with `vault version`):

```
Vault v1.3.0
```
* Server Operating System/Architecture:

Centos 7 

Vault server configuration file(s):

```
{
  "default_lease_ttl": "24h",
  "listener": {
    ....
  },
  "max_lease_ttl": "24h",
  "storage": {
    ....
  },
  "telemetry": {
    ....
  },
....
}
```

**Additional context**

I have another AWS Secrets engine for a different account with a default TTL of 1 week and its newer get "renewed", i.e all the leases that are created from the account survive exactly 1 week.

**Comment by shaharba** [comment]
Hi,
I'm suffering from the same behavior as @Isan-Rivkin described when renewing a lease.

**Comment by nshazly** [comment]
I have the same issue running v1.3.4

**Comment by Isan-Rivkin** [comment]
I managed to solve this finally. 

I created the lease every time while being authenticated with an Approle. 
The **Approle auth method** had max ttl of 7 days. 
So I had to:
- Tune the approle auth method max-ttl 
- Tune the specific approle I was using to have a default-ttl and max-ttl high enough 

Then I was able to create leases with 1 year ttl using that approle. 

Closing the issue.
