### ISSUE TITLE
ui 1.4.3: Leases not shown unless logged in with root token

### ISSUE THREAD

**Issue by andreas-p** [hashicorp/vault#9556]
In order to avoid using a root token on my Vault 1.4.3, my admin user has all privileges including sudo for "sys/leases/*".

`vault list sys/leases/lookup/auth` will show auth methods as expected, same when using a root token with the ui: `https://<vault-server>:8200/ui/vault/access/leases/list/auth` displays all auth methods currently in use.

When using the admin user's token, `https://<vault-server>:8200/ui/vault/access/leases` will only show "find lease",  with ../leases/list/ manually entered the browser shows "t is undefined" (Firefox) or "Cannot read property 'leases' of undefined" (Chrome).

Policy used:
path "sys/leases/*" {
  capabilities = ["list", "read", "update", "create", "delete", "sudo"]
}

I'd expect the ui to show the same lease information that I can retrieve via api/cmdline.

Vault 1.4.3 on Debian10.4-amd64, installed from the apt.releases.hashicorp.com repository.

**Comment by TamasNeumer** [comment]
I'm experiencing the same issue.

**Comment by evberde2e** [comment]
I can confirm this is happening on 1.6 as well.

**Comment by norrit** [comment]
This is an issue for us as well. Vault 1.6.2

GUI shows as root, doesn't show as user, CLI displays list.

**Comment by alexintech** [comment]
I had the same problem. My admin user had two assigned policies `admin policy` and `default`.
You can check it:
```
$ vault token lookup
Key                            Value
---                            -----
...
identity_policies             [admin policy]
policies                     [default]
...
```

My `admin policy` was as yours
```
# Allow managing leases
path "sys/leases/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
```

In `default` policy you can find the rule:
```
# Allow looking up lease properties. This requires knowing the lease ID ahead
# of time and does not divulge any sensitive information.
path "sys/leases/lookup" {
    capabilities = ["update"]
}
```

Path `sys/leases/lookup` is more concrete, and it overrides the `sys/leases/*` path.

You can check what capabilities you have on the path using this command:
```
$ vault token capabilities sys/leases/lookup
update
```

**Solution**
For UI you must add at least `list` and `sudo` permissions in your `admin policy` like that:
```
# Allow managing leases
path "sys/leases/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}

path "sys/leases/lookup"
{
  capabilities = ["list", "sudo"]
}
```

After that you will see that capabilities are combined and UI looks the same as you've logged with root token:
```
$ vault token capabilities sys/leases/lookup
list, sudo, update
```

**Comment by andreas-p** [comment]
Thank you @alexintech this is the explanation and the solution!

Adding the specific path "sys/leases/lookup" does the trick.

**Comment by dspaeth-breuni** [comment]
@alexintech your solution worked for me too, but ... why does `"sys/leases/*"` not cover `sys/leases/lookup`?

**Comment by alexintech** [comment]
> @alexintech your solution worked for me too, but ... why does `"sys/leases/*"` not cover `sys/leases/lookup`?

@dspaeth-breuni because you already have `sys/leases/lookup` in default policy

```
# Allow looking up lease properties. This requires knowing the lease ID ahead
# of time and does not divulge any sensitive information.
path "sys/leases/lookup" {
    capabilities = ["update"]
}
```

`"sys/leases/*"` won't override capabilities for specific path.

**Comment by dspaeth-breuni** [comment]
in my vault server the default policy looks like this:

```
 Allow tokens to look up their own properties
path "auth/token/lookup-self" {
    capabilities = ["read"]
}

# Allow tokens to renew themselves
path "auth/token/renew-self" {
    capabilities = ["update"]
}

# Allow tokens to revoke themselves
path "auth/token/revoke-self" {
    capabilities = ["update"]
}
```

do  I miss some thing?
