### ISSUE TITLE
How to define policy to concrete path without excluding all other paths

### ISSUE THREAD

**Issue by Anti-neutrino** [hashicorp/vault#9579]
**Bug Description**
I am searching for a way how to grant access to a specific path in Vault without excluding all other secret paths. I have created the following policy:

```
path "sys/capabilities-self" {
    capabilities = ["update"]
}
path "kv2/metadata/*" {
  capabilities=["list", "read"]
}
path "kv2/metadata/landscape/rsyslog/CF/*" {
  capabilities=[]
}
path "kv2/data/landscape/rsyslog/CA/*" {
  capabilities=["read","list"]
}
```

The certs in "kv2/metadata/landscape/rsyslog/CF" folder can be listed but cannot be read. If I want to grant access only to the CA folder I have to set empty array of capabilities to the other folders.(e.g. kv2/metadata/landscape/rsyslog/CF/*). Do you know what is the appropriate way for setting permissions to a specific path without excluding the other ones?

**Environment:**

* Vault Version:
* Operating System/Architecture:

**Vault Config File:**

```hcl
path "sys/capabilities-self" {
    capabilities = ["update"]
}
path "kv2/metadata/*" {
  capabilities=["list", "read"]
}
path "kv2/metadata/landscape/rsyslog/CF/*" {
  capabilities=[]
}
path "kv2/data/landscape/rsyslog/CA/*" {
  capabilities=["read","list"]
}
```

**Startup Log Output:**

```text
# Paste your log output here
```

**Expected Behavior:**
Grant access to a specific path without excluding all other paths.

**Actual Behavior:**
All paths have to be excluded unless the specified path

**Steps to Reproduce:**

**Important Factoids:**

**References:**

**Comment by calvn** [comment]
I believe that is because you also have the `"kv2/metadata/*"` policy which grants access to `"kv2/metadata/landscape/rsyslog/CF/*"` unless you explicitly disallow operations on the more specific path like you're doing so.

If you want to only grant read and list access to the CA path, would something like this work or do you need the broader `"kv2/metadata/*"` policy path in there for some reason?

```
path "sys/capabilities-self" {
    capabilities = ["update"]
}

path "kv2/metadata/landscape/rsyslog/CA/*" {
  capabilities=["read","list"]
}

path "kv2/data/landscape/rsyslog/CA/*" {
  capabilities=["read","list"]
}
```

**Comment by Anti-neutrino** [comment]
When I specify the policy described by you the colleagues could not access the CA path. 
Output
```
Not Authorized
You don't have access to kv2/. If you think you've reached this page in error, please contact your administrator.
Go back home .
```
Do you have any idea why this is happening?

**Comment by Timur07Kabar** [comment]
Ok

**Comment by calvn** [comment]
> When I specify the policy described by you the colleagues could not access the CA path.

What's the URL path that they are hitting?

**Comment by aphorise** [comment]
The [Policy Syntax](https://www.vaultproject.io/docs/concepts/policies#policy-syntax) documentation and the 1-5 P1+P2 rules detailed there are what's applicable here.

My approach is to be as explicit as possible and avoid any `+` or `*` as much as possible or limit them to a single path only without any overlap.

@Anti-neutrino if you've resolved your  issue can you share an update and if possible close?

**Comment by aphorise** [comment]
Closing due to no response. Kindly re-open if still relevant.
