### ISSUE TITLE
PKI engine role to allow hostnames as SAN in certificates

### ISSUE THREAD

**Issue by smirta** [hashicorp/vault#9610]
**Is your feature request related to a problem? Please describe.**
Customers keep asking how they could define a pki engine role that allows hostnames as SAN in certificate signing requests. We did not find a way to allow a specific subdomain and hostname only.

A certificate like below should be possible:
  Subject: CN = host1.sub1.example.com
  X509v3 extensions:
   X509v3 Subject Alternative Name:
    DNS:host1.sub1.example.com, DNS:host1

Allowed are only *.sub1.example.com and e.g. ^[A-z0-9]+$ .

**Describe the solution you'd like**
A parameter to allow "DNS:host1" and . E.g. allow_hostname or allow_san_hostname.

**Describe alternatives you've considered**
Using Sentinel. Implementing Sentinel just for this use-case seems a bit of an overkill.

**Comment by cipherboy** [comment]
Hi @smirta -- sorry about the delay. This is definitely possible by using the [`alt_names`](https://www.vaultproject.io/api-docs/secret/pki#generate-certificate) parameter of the issue endpoint. It has been included in Vault since ~2015. 

E.g.:

```
$ vault write pki/roles/matching-example allowed_domains=example.com allow_subdomains=true
$ vault write pki/issue/matching-example common_name=*.sub1.example.com alt_names=other.example.com,secondary.example.com
```

The cert will have subject:

```
SEQUENCE (1 elem)
      SET (1 elem)
        SEQUENCE (2 elem)
          OBJECT IDENTIFIER 2.5.4.3 commonName (X.520 DN component)
          UTF8String *.sub1.example.com
```

And SANs:

```
SEQUENCE (2 elem)
          OBJECT IDENTIFIER 2.5.29.17 subjectAltName (X.509 extension)
          OCTET STRING (64 byte) 303E82122A2E737562312E6578616D706C652E636F6D82116F746865722E6578616D70…
            SEQUENCE (3 elem)
              [2] (18 byte) *.sub1.example.com
              [2] (17 byte) other.example.com
              [2] (21 byte) secondary.example.com
```
