### ISSUE TITLE
Can't authenticate with OIDC via curl (or any external request)

### ISSUE THREAD

**Issue by axfelix** [hashicorp/vault#9616]
**Describe the bug**
We can't seem to make OIDC authorization work when initiated from an external CURL request when trying to follow the documentation in https://learn.hashicorp.com/vault/operations/oidc-auth. 

**To Reproduce**
1. Configure vault to use OIDC authorization (eg using Google OAuth) and ensure that the workflow is functional when authenticating via the browser or the `vault` client.
2. Attempt to post to auth URL using `payload.json` as in Vault docs: `curl --request POST --data @payload.json  http://127.0.0.1:8200/v1/auth/oidc/oidc/auth_url`
3. Returned response is:
```
{
  "role": null,
  "redirect_uri": "http://localhost:8250/oidc/callback" 
}
```

When trying to post with `http://127.0.0.1:8200/ui/vault/auth/oidc/oidc/callback` as the `redirect_uri`, the returned `auth_url` triggers the Google OAuth workflow, but returns this url, `http://localhost:8250/oidc/callback?state=83c879a2d283b6e487a87929d7d63a4b549dead5&code=4%2F2QHope3dmeFJ7gn7X1eXOCyd87mV9vE6EjtHwHfoQ4lOly6h44SHeG4rx_6GHK-nIMisPhJhOqEqHOjJrqSw8mk&scope=openid&authuser=0&prompt=consent#`, which just throws a "localhost refused to connect" error in the browser. We're not entirely sure where port 8250 is coming from here.

Also, just running `curl http://127.0.0.1:8200/v1/auth/oidc/oidc/callback?state=83c879a2d283b6e487a87929d7d63a4b549dead5&code=4%2F2QHope3dmeFJ7gn7X1eXOCyd87mV9vE6EjtHwHfoQ4lOly6h44SHeG4rx_6GHK-nIMisPhJhOqEqHOjJrqSw8mk&nonce=bea85102826d1612f9bf98b3f7b795ceafd2d8ad` returns `{“errors”:[“Vault login failed. No code or id_token received.“]}`

**Expected behavior**
OAuth workflow should open in a browser window and return token.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.4.0
* Vault CLI Version (retrieve with `vault version`): 1.4.0
* Server Operating System/Architecture: macOS 10.13.6

Vault server configuration file(s): Server started in dev mode with no additional config provided (verified this also happens in non-dev mode).

**Comment by axfelix** [comment]
Let me know if this belongs in https://github.com/hashicorp/vault-plugin-auth-jwt and I can move it, sorry for the confusino.

**Comment by kalafut** [comment]
The `vault login` command (https://learn.hashicorp.com/vault/operations/oidc-auth#step-4-login-with-oidc) is doing more than just posting to the login endpoint. It is opening the browser to the IdP, listening for the redirect on localhost, and completing the OIDC auth flow. This isn't possible with just `curl`.

**Comment by axfelix** [comment]
Thanks -- going to close this and open an issue under the plugin repo.

**Comment by kalafut** [comment]
Moved to https://github.com/hashicorp/vault-plugin-auth-jwt/issues/126
