### ISSUE TITLE
listing all created tokens 

### ISSUE THREAD

**Issue by eladapps** [hashicorp/vault#965]
i would like to have a way to list all my created tokens via cli /api

**Comment by jefferai** [comment]
Hi,

This is not something we will be implementing. This is an potentially very dangerous capability to make available and we would rather err on the side of safety.

At most organizations we've talked to, nobody would be allowed to have that kind of access. However, if this is not the case at your organization, someone that is approved for that level of access is likely able to get access to the physical store too. If you have access to the physical store, you can use knowledge of the keys and the `/sys/raw` endpoint to retrieve records, allowing you to perform this type of listing capability yourself via a script.

Sorry!
