### ISSUE TITLE
Vault not booting when using a AWSKMS Seal

### ISSUE THREAD

**Issue by marcofranssen** [hashicorp/vault#9656]
I'm unable to boot vault when using a `awskms` seal.

Also see here how the deployment is done.

https://github.com/hashicorp/vault-helm/issues/368

Is there a way to debug? I'm not sure if this is a bug in vault or the helm chart. Or some missing configuration.

**Comment by ncabatoff** [comment]
Hi @marcofranssen ,

It looks like you got some help in that vault-helm issue.  I'm going to close this issue because it's been inactive for a long time.  Please open a new issue if you have further problems.
