### ISSUE TITLE
Vault HA setup

### ISSUE THREAD

**Issue by bhanukumar22** [hashicorp/vault#9672]
I want to deploy 2 vaults in 2 servers. But both server would be pointing to one storage, so that same secrets are available on both the servers. How can I achieve that? Please help.

If one vault goes down, I can connect to other one to fetch secret.

I tried on the servers and at a time, only one vault is up. Other will go down and it goes to sealed state. 
Error unsealing: Put https://x.x.x.x:8200/v1/sys/unseal: dial tcp x.x.x.x:8200: connect: no route to host

**Comment by bhanukumar22** [comment]
I get below output, when I copy files under secret to other server secret path

uid=xxxx(userid) gid=xxxx groups=xxxx,xxxx(userid)
uid=xxxx(userid) gid=xxxx groups=xxxx,xxxx(userid)
============ Adding .crt files to ca-certificates... ============
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
uid=xxxx(userid) gid=xxxx groups=xxxx,xxxx(userid)
uid=xxxx(userid) gid=xxxx groups=xxxx,xxxx(userid)
================== Configuring vault server... ==================
==================== Running vault server... ====================
WARNING! Unable to read storage migration status.
2020-08-06T14:02:00.919Z [WARN]  storage migration check error: error="open /secrets/core/_migration: permission denied"
2020-08-06T14:02:02.920Z [WARN]  storage migration check error: error="open /secrets/core/_migration: permission denied"
2020-08-06T14:02:04.920Z [WARN]  storage migration check error: error="open /secrets/core/_migration: permission denied"
==================== Already initialized... ====================
======================== Fetching keys... =======================
======================= Unsealing vault... ======================
2020-08-06T14:02:06.921Z [WARN]  storage migration check error: error="open /secrets/core/_migration: permission denied"
Error unsealing: Put https://x.x.x.x:8200/v1/sys/unseal: dial tcp x.x.x.x:8200: connect: no route to host

**Comment by aphorise** [comment]
Each node must have its own dedicated storage with the ability to lock and this cannot be done in a co-shared manner as you may be thinking. I'd recommend referring to the [Vault reference-architecture](https://learn.hashicorp.com/tutorials/vault/reference-architecture) where either [Consul](https://learn.hashicorp.com/tutorials/vault/deployment-guide?in=vault/day-one-consul) or [(Raft) Integrated Storage](https://learn.hashicorp.com/tutorials/vault/raft-deployment-guide?in=vault/day-one-raft) is what's detailed and for overall options you can [explore `docs/configuration/storage`](https://www.vaultproject.io/docs/configuration/storage). The overall literature may make the 1:N relationship clear where you can only ever have a single (1) leader per cluster and not two. What's more cluster sizes [similar to 3, 5 or 7](https://www.vaultproject.io/docs/internals/integrated-storage#deployment-table) are what's typically to have some tolerance for failure. All the available docs and tutorials should hopefully help you.

**Comment by bhanukumar22** [comment]
Thanks for the info.
