### ISSUE TITLE
Correlation between audit logs and generated secret 

### ISSUE THREAD

**Issue by a8j8i8t8** [hashicorp/vault#9730]
**Is your feature request related to a problem? Please describe.**
We've audit logs enabled for Vault server.
We've vault server configured with LDAP auth.
We've configured Vault for dynamic database secret generation.
All employees can read credentials for let's say a database using `vault read database/creds/some-db`.

There is currently no way to check who has got which secrets.

**Describe the solution you'd like**
It'd be better to have some kind of link between audit logs and created secrets.

**Comment by aphorise** [comment]
A raw audit device can be enabled on temporary basis with [the parameter `log_raw`](https://www.vaultproject.io/docs/audit/file#log_raw)? - it will show all details in raw / non-HMAC including tokens + secrets so don't forget to disable it ;-)

Hey @a8j8i8t8 - have you looked at that? - if so please update / close.

**Comment by aphorise** [comment]
Closing due to no follow up. Please re-open if still relevant.
