### ISSUE TITLE
Missing telemetry core metrics when using prometheus

### ISSUE THREAD

**Issue by elikt** [hashicorp/vault#9771]
**Describe the bug**
Missing telemetry core metrics when using prometheus , such as vault.core.unsealed. the metrics that are shown are:
`
{"Timestamp":"2020-08-18 17:02:00 +0000 UTC","Gauges":[{"Name":"vault.expire.num_leases","Value":3,"Labels":{}},{"Name":"vault.runtime.alloc_bytes","Value":12463680,"Labels":{}},{"Name":"vault.runtime.free_count","Value":7205781,"Labels":{}},{"Name":"vault.runtime.heap_objects","Value":60019,"Labels":{}},{"Name":"vault.runtime.malloc_count","Value":7265800,"Labels":{}},{"Name":"vault.runtime.num_goroutines","Value":49,"Labels":{}},{"Name":"vault.runtime.sys_bytes","Value":77529336,"Labels":{}},{"Name":"vault.runtime.total_gc_pause_ns","Value":23970076,"Labels":{}},{"Name":"vault.runtime.total_gc_runs","Value":147,"Labels":{}}],"Points":[],"Counters":[],"Samples":[{"Name":"vault.barrier.get","Count":1,"Rate":0.005162499845027924,"Sum":0.051624998450279236,"Min":0.051624998450279236,"Max":0.051624998450279236,"Mean":0.051624998450279236,"Stddev":0,"Labels":{}},{"Name":"vault.barrier.put","Count":1,"Rate":1.1247740745544434,"Sum":11.247740745544434,"Min":11.247740745544434,"Max":11.247740745544434,"Mean":11.247740745544434,"Stddev":0,"Labels":{}},{"Name":"vault.consul.put","Count":1,"Rate":1.1183171272277832,"Sum":11.183171272277832,"Min":11.183171272277832,"Max":11.183171272277832,"Mean":11.183171272277832,"Stddev":0,"Labels":{}}]}
`

**To Reproduce**
1. access vault's metrics`/v1/sys/metrics`
2. See no core metrics 

**Environment:**
* Vault Server Version :  v1.4.3 
* Server Operating System/Architecture: k8s 

Vault server configuration file(s):

```hcl
{
  "api_addr": "http://vault:8200",
  "cluster_addr": "http://vault:8201",
  "listener": {
    "tcp":  {
      "address": "0.0.0.0:8200",
      "tls_disable": 1,
      "telemetry": {
        "unauthenticated_metrics_access": true
      }
    }
  },
  "seal": {
     "gcpckms": {
        "credentials": "gcpckms",
        "project": "gcpckms",
        "region": "us",
        "key_ring": "vault-keyring",
        "crypto_key": "vault-key"
    }
  },
  "telemetry": {
    "prometheus_retention_time": "30s",
    "disable_hostname": true
  },
  "storage": {
    "consul": {
      "address": "consul",
      "lock_wait_time": "1h",
      "consistency_mode": "strong",
      "path": "vault/"
    }
  },
  "ui": true
}
```

**Comment by ncabatoff** [comment]
Hi @elikt,

Many core metrics are only set sporadically, and will expire if not updated recently based on your configured `prometheus_retention_time`.  `unsealed` is one of those.

**Comment by elikt** [comment]
Hi @ncabatoff,

Even setting the `prometheus_retention_time` to `1h` doesn’t show the `unsealed` metric. we've even tried to use statsd exporter, it does show some core metrics but not all of them as described in the documentation.

**Comment by ncabatoff** [comment]
Does setting it to `1h` and then restarting or sealing/unsealing show the `unsealed` metric?

**Comment by ncabatoff** [comment]
Oh, looks like `unsealed` was only added in 1.5.0.

**Comment by elikt** [comment]
oh, my bad. thank you for the quick help @ncabatoff !

**Comment by ncabatoff** [comment]
No trouble!

**Comment by exo-cedric** [comment]
Same here, using Vault `1.5.0` and `prometheus_retention_time = 24h`

**Comment by exo-cedric** [comment]
I should have mentioned this happens on a HA Raft Follower (standing-by node).

Quickly going through `core.go`, `core_metrics.go` and `ha.go`, it _seems_ to me that `emitMetrics` (which spawns the `metrics
Loop` to refresh the `core.unsealed` metric) is only called via `postUnseal`, which is _not_ called for HA standing-by HA node (in `core.go`); only the Leader/Active node actually calls `postUnseal` (in `ha.go`).

The lack of `core.unsealed` metrics for a HA standing-by node is problematic since it prevents to monitor the health of all HA nodes (and make sure HA is actually still available).

**Comment by exo-cedric** [comment]
@ncabatoff Should I open a new separate issue to follow this (closed) one up ?

**Comment by ncabatoff** [comment]
@exo-cedric yes new issue please.  On enterprise postUnseal *is* called for performance standby nodes.  I agree it would be good if regular standbys also reported unsealed status.
