### ISSUE TITLE
Signing a Vault generated intermediate CA CSR in openssl causes encoding issue

### ISSUE THREAD

**Issue by alem117** [hashicorp/vault#9787]
### Environment
```
(client - signer)
   macOS 10.15.6
   LibreSSL 2.8.3
(Vault - server)
   docker 2.3.0.4
   Vault v1.4.2
```

### Goal
To build an intermediate CA using Vault. Keeping the root CA offline.

### Operation flow (Expected behaviour)
1. Establishing a PKI secret engine to be used as an intermediate CA.
2. Contact Vault though CLI to generate an intermediate CA csr from vault for that PKI secret engine and save it in a local file.
3. Sign the intermediate CA csr file with our organization's own private root ca through openssl.
4. Push the signed intermediate CA certificate to vault to begin operations.

### Scenario
We need to match the County(C) and Organization (O) with our root config file. The string mask used in the config file is utf8only. the problem stems from here.
```
a test root-ca.conf
[ default ]
ca                      = root-ca                            
dir                     = .                                 
name_opt                = multiline,-esc_msb,utf8      
[ req ]
default_bits            = 2048                    
encrypt_key             = no                        
default_md              = sha256                     
utf8                    = yes                              
string_mask             = utf8only                  
prompt                  = no                             
distinguished_name      = ca_dn              
req_extensions          = ca_reqext              
[ ca_dn ]
0.domainComponent       = "ex"
1.domainComponent       = "org"
countryName             = "EX"
organizationName        = "Org Name"
organizationalUnitName  = "Org Unit"
commonName              = "Org Root CA"
[ ca_reqext ]
keyUsage                = critical,keyCertSign,cRLSign
basicConstraints        = critical,CA:true
subjectKeyIdentifier    = hash
[ ca ]
default_ca              = root_ca               
[ root_ca ]
certificate             = $dir/ca/$ca.crt       
private_key             = $dir/ca/$ca/private/$ca.key 
new_certs_dir           = $dir/ca/$ca           
serial                  = $dir/ca/$ca/db/$ca.crt.srl 
crlnumber               = $dir/ca/$ca/db/$ca.crl.srl 
database                = $dir/ca/$ca/db/$ca.db 
unique_subject          = no                    
default_days            = 3652                  
default_md              = sha256                
policy                  = match_pol             
email_in_dn             = no                   
preserve                = no                    
name_opt                = $name_opt             
cert_opt                = ca_default            
copy_extensions         = copy                 
x509_extensions         = intermediate_ca_ext  
default_crl_days        = 100                   
crl_extensions          = crl_ext               
[ match_pol ]
domainComponent         = optional
countryName             = match
stateOrProvinceName     = optional
localityName            = optional
organizationName        = match
organizationalUnitName  = optional
commonName              = supplied
[ root_ca_ext ]
keyUsage                = critical,keyCertSign,cRLSign
basicConstraints        = critical,CA:true
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid:always
[ intermediate_ca_ext ]
keyUsage                = critical,keyCertSign,cRLSign
basicConstraints        = critical,CA:true
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid:always
[ crl_ext ]
authorityKeyIdentifier  = keyid:always
```
**Create the PKI secret engine**
`vault secrets enable testpki`

**Generating the csr through the cli and saving it in a local file**
```
vault write -format=json testpki/intermediate/generate/internal \
common_name="Vault Intermediate Authority" country="SA" organization="Org Name" | jq -r '.data.csr' > pki_intermediate.csr
```
**Signing the csr with our test root ca**
`openssl ca -in pki_intermediate.csr -out pki_intermediate.crt -config etc/root-ca.conf`

**The following error is generated from the previous command**
```
Using configuration from etc/root-ca.conf
Check that the request matches the signature
Signature ok
The organizationName field needed to be the same in the
CA certificate (Org Name) and the request (Org Name)
```
This problem persists in all fields, except the country name field.

### Possible cause
We think the problem might be caused by the utf8only string mask. Which is ambiguous because per rfc 2459, the recommended string encoding for certificates should be utf8. so in that regards the csr coming from vault should be utf8 encoded, but it seems like this is not the case.

### What worked
The only field that is working properly is the country name field (C/country). We discovered that by constantly changing our certificate policy until we left the country name field as the only one that should match.
```
From our root-ca.conf
...
[ match_pol ]
...
countryName             = match
organizationName        = optional
...
```
**We generated a new root certificate with the modified config file, after which we tried signing the vault int ca csr**
`openssl ca -in pki_intermediate.csr -out pki_intermediate.crt -config etc/root-ca.conf`

**The operation was successful, we uploaded the certificate back to vault to set it as the signed intermediate ca certificate**
```
vault write testpki/intermediate/set-signed certificate=@pki_intermediate.crt
Success! Data written to: testpki/intermediate/set-signed
```
**To test that everything went smoothly, we created a test role to generate a dummy end entity certificate from.**
```
vault write testpki/roles/example \
    allowed_domains=example.com \
    allow_subdomains=true max_ttl=72h
Success! Data written to: testpki/roles/example
```
**Generating a certificate using example role, the operation was successful.**
```
vault write testpki/issue/example \
    common_name=test.example.com
Key                 Value
---                 -----
ca_chain            [-----BEGIN CERTIFICATE-----
.................................................
```
### Current mitigation
To generate our own intermediate CA certificate and push it to Vault for it to use in the PKI engine.

**Comment by rrayst** [comment]
The PKIX recommendations changed over the years. The openssl configuration option names for ``string_mask`` are therefore a bit misleading. Taken from [the openssl configuration sample](https://github.com/openssl/openssl/blob/7bfd934049021ebf56db3f9670961c958104445d/apps/openssl.cnf#L148) from the latest master commit (the corresponding code parsing the ``string_mask`` value is [here](https://github.com/openssl/openssl/blob/9311d0c471ca2eaa259e8c1bbbeb7c46394c7ba2/crypto/asn1/a_strnid.c#L48)) the possible ``string_mask`` values are :
* ``default``: PrintableString, T61String, BMPString.
* ``pkix``	 : PrintableString, BMPString (PKIX recommendation before 2004)
* ``utf8only``: only UTF8Strings (PKIX recommendation after 2004).
* ``nombstr`` : PrintableString, T61String (no BMPStrings or UTF8Strings).
* ``MASK:XXXX`` a literal mask value.

But if you look e.g. at the PKIX RFC from 2008 [section 4.1.2.4](https://tools.ietf.org/html/rfc5280#section-4.1.2.4) it allows PrintableStrings as well as UTF8Strings.

I solved the problem mentioned in the OP by setting the following mask, which allows UTF8Strings and PrintableStrings.
```
string_mask = MASK:8194
```

Note though that 
* the root CA needs this setting to be present from the start (so that the root CA cert also uses PrintableStrings),
* when using this setting emails are still encoded in IA5Strings, which also conforms to the recommendation mentioned above.

**Comment by pengliaoye** [comment]
mark

**Comment by bjencks** [comment]
I can confirm this affects me too. Since reissuing a root CA is not always feasible, and the spec allows multiple behaviors, would it be possible to add options to the intermediate/generate API to select the string encoding so it will match what the user's CA needs? That's the only endpoint that generates something for an external CA to deal with, so it shouldn't be necessary on other endpoints.

**Comment by cipherboy** [comment]
The recommendation by @rrayst is correct and there isn't much we can do on the Vault side to address this:

We use [Go's `pkix.Name` type](https://pkg.go.dev/crypto/x509/pkix#Name), which [automatically](https://cs.opensource.google/go/go/+/refs/tags/go1.19.5:src/crypto/x509/pkix/pkix.go;l=196-212;drc=007d8f4db1f890f0d34018bb418bdc90ad4a8c35) gets serialized into a subject [on the CSR](https://github.com/hashicorp/vault/blob/main/sdk/helper/certutil/helpers.go#L1071-L1072), meaning we have no control over `UTF8String` vs `PrintableString`.

Given the root CA already exists, there's two workarounds for this:

1. As mentioned in @alem117's post, generate the Intermediate CA outside of Vault and import. This is less desirable.
2. Pass the `-subj` parameter to the `openssl ca` option. This is more preferable: CSRs attributes are taken _at the CA's prerogative_ and so can be overwritten.

The second one looks like (for this example intermediate):

<details>
<summary>
Command: 

 ```
 $ openssl ca -batch -in pki_intermediate.csr -out pki_intermediate.crt -extensions intermediate_ca_ext -subj '/O=Org Name/C=EX/CN=Vault Intermediate Authority' -config ca.cnf 
```

</summary>

```
Using configuration from ca.cnf
Check that the request matches the signature
Signature ok
Certificate Details:
        Serial Number: 2 (0x2)
        Validity
            Not Before: Jan 30 14:47:47 2023 GMT
            Not After : Jan 29 14:47:47 2033 GMT
        Subject:
            countryName               = EX
            organizationName          = Org Name
            commonName                = Vault Intermediate Authority
        X509v3 extensions:
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Key Identifier: 
                A2:8C:04:67:42:BE:C3:12:3E:08:9D:03:F4:4F:81:CA:AC:3C:C3:7D
            X509v3 Authority Key Identifier: 
                DC:76:2C:90:EF:65:B3:7F:D5:FB:4D:CA:CC:07:2E:41:5C:56:94:B1
Certificate is to be certified until Jan 29 14:47:47 2033 GMT (3652 days)

Write out database with 1 new entries
Data Base Updated
$ openssl x509 -in pki_intermediate.crt -outform DER | openssl asn1parse -inform DER
    0:d=0  hl=4 l= 919 cons: SEQUENCE          
    4:d=1  hl=4 l= 639 cons: SEQUENCE          
    8:d=2  hl=2 l=   3 cons: cont [ 0 ]        
   10:d=3  hl=2 l=   1 prim: INTEGER           :02
   13:d=2  hl=2 l=   1 prim: INTEGER           :02
   16:d=2  hl=2 l=  13 cons: SEQUENCE          
   18:d=3  hl=2 l=   9 prim: OBJECT            :sha256WithRSAEncryption
   29:d=3  hl=2 l=   0 prim: NULL              
   31:d=2  hl=2 l= 114 cons: SEQUENCE          
   33:d=3  hl=2 l=  18 cons: SET               
   35:d=4  hl=2 l=  16 cons: SEQUENCE          
   37:d=5  hl=2 l=  10 prim: OBJECT            :domainComponent
   49:d=5  hl=2 l=   2 prim: IA5STRING         :ex
   53:d=3  hl=2 l=  19 cons: SET               
   55:d=4  hl=2 l=  17 cons: SEQUENCE          
   57:d=5  hl=2 l=  10 prim: OBJECT            :domainComponent
   69:d=5  hl=2 l=   3 prim: IA5STRING         :org
   74:d=3  hl=2 l=  11 cons: SET               
   76:d=4  hl=2 l=   9 cons: SEQUENCE          
   78:d=5  hl=2 l=   3 prim: OBJECT            :countryName
   83:d=5  hl=2 l=   2 prim: PRINTABLESTRING   :EX
   87:d=3  hl=2 l=  17 cons: SET               
   89:d=4  hl=2 l=  15 cons: SEQUENCE          
   91:d=5  hl=2 l=   3 prim: OBJECT            :organizationName
   96:d=5  hl=2 l=   8 prim: UTF8STRING        :Org Name
  106:d=3  hl=2 l=  17 cons: SET               
  108:d=4  hl=2 l=  15 cons: SEQUENCE          
  110:d=5  hl=2 l=   3 prim: OBJECT            :organizationalUnitName
  115:d=5  hl=2 l=   8 prim: UTF8STRING        :Org Unit
  125:d=3  hl=2 l=  20 cons: SET               
  127:d=4  hl=2 l=  18 cons: SEQUENCE          
  129:d=5  hl=2 l=   3 prim: OBJECT            :commonName
  134:d=5  hl=2 l=  11 prim: UTF8STRING        :Org Root CA
  147:d=2  hl=2 l=  30 cons: SEQUENCE          
  149:d=3  hl=2 l=  13 prim: UTCTIME           :230130144747Z
  164:d=3  hl=2 l=  13 prim: UTCTIME           :330129144747Z
  179:d=2  hl=2 l=  71 cons: SEQUENCE          
  181:d=3  hl=2 l=  11 cons: SET               
  183:d=4  hl=2 l=   9 cons: SEQUENCE          
  185:d=5  hl=2 l=   3 prim: OBJECT            :countryName
  190:d=5  hl=2 l=   2 prim: PRINTABLESTRING   :EX
  194:d=3  hl=2 l=  17 cons: SET               
  196:d=4  hl=2 l=  15 cons: SEQUENCE          
  198:d=5  hl=2 l=   3 prim: OBJECT            :organizationName
  203:d=5  hl=2 l=   8 prim: UTF8STRING        :Org Name
  213:d=3  hl=2 l=  37 cons: SET               
  215:d=4  hl=2 l=  35 cons: SEQUENCE          
  217:d=5  hl=2 l=   3 prim: OBJECT            :commonName
  222:d=5  hl=2 l=  28 prim: UTF8STRING        :Vault Intermediate Authority
  252:d=2  hl=4 l= 290 cons: SEQUENCE          
  256:d=3  hl=2 l=  13 cons: SEQUENCE          
  258:d=4  hl=2 l=   9 prim: OBJECT            :rsaEncryption
  269:d=4  hl=2 l=   0 prim: NULL              
  271:d=3  hl=4 l= 271 prim: BIT STRING        
  546:d=2  hl=2 l=  99 cons: cont [ 3 ]        
  548:d=3  hl=2 l=  97 cons: SEQUENCE          
  550:d=4  hl=2 l=  14 cons: SEQUENCE          
  552:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Key Usage
  557:d=5  hl=2 l=   1 prim: BOOLEAN           :255
  560:d=5  hl=2 l=   4 prim: OCTET STRING      [HEX DUMP]:03020106
  566:d=4  hl=2 l=  15 cons: SEQUENCE          
  568:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Basic Constraints
  573:d=5  hl=2 l=   1 prim: BOOLEAN           :255
  576:d=5  hl=2 l=   5 prim: OCTET STRING      [HEX DUMP]:30030101FF
  583:d=4  hl=2 l=  29 cons: SEQUENCE          
  585:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Subject Key Identifier
  590:d=5  hl=2 l=  22 prim: OCTET STRING      [HEX DUMP]:0414A28C046742BEC3123E089D03F44F81CAAC3CC37D
  614:d=4  hl=2 l=  31 cons: SEQUENCE          
  616:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Authority Key Identifier
  621:d=5  hl=2 l=  24 prim: OCTET STRING      [HEX DUMP]:30168014DC762C90EF65B37FD5FB4DCACC072E415C5694B1
  647:d=1  hl=2 l=  13 cons: SEQUENCE          
  649:d=2  hl=2 l=   9 prim: OBJECT            :sha256WithRSAEncryption
  660:d=2  hl=2 l=   0 prim: NULL              
  662:d=1  hl=4 l= 257 prim: BIT STRING        
```

</details>

Note that Vault accepts the intermediate regardless of what changes the CA has made to it on signing (though, it must use the same key material obviously). 

This requires no updates to the config file, and other usage of the OpenSSL CA are not affected, unlike regenerating the Root CA.
