### ISSUE TITLE
Examples for webdevelopers

### ISSUE THREAD

**Issue by xtrasmal** [hashicorp/vault#98]
My UseCase:

I have developed a php app as microservice, which is being called by the main application. The main application is on another server.  The microservice is a notification messages app, that has it's own database to store messages. 

The main application can perform CRUD actions on the microservice. Right now I am looking into vault to implement some authentication. But it's not very clear on how it all fits in. I get the bigger "vault" picture.. but I do not get how I should get authentication working through REST calls. 
Do I need to set headers? Do I run php exec?  

It would be nice to get a broader view on how you would like us to work with this.

**Comment by sethvargo** [comment]
Hey @xtrasmal 

Thank you for opening an issue. Could you clarify your use case a bit more?

If you are trying to store sensitive information in the database, you can use [Vault's transit backend](https://www.vaultproject.io/docs/secrets/transit/index.html). The process looks like this:

```text
encryption: plaintext ---> vault ---> ciphertext ---> store in database
decryption: ciphertext ---> vault ---> plaintext
```

With the transit backend, Vault transparently handles the creation and distribution of encryption keys. You can also easily do key-rolling without ever updating your application's code. This is great for storing sensitive customer information in a database like phone numbers or credit card numbers.

From your description, it sounds like you may also be interested in using [Vault's App ID authentication](https://www.vaultproject.io/docs/auth/app-id.html).

It is a bit unclear to mean what you mean by "Right now I am looking into vault to implement some authentication" - could you please elaborate a bit more? Who are you trying to authenticate and what are you trying to authenticate against?

**Comment by xtrasmal** [comment]
Hello @sethvargo 

Thank you for your information. I've been looking at the documentation more clearly and 
setup a ```vault server -dev``` and right now everything starts to get more clear to me. At the moment I'm in the proces in looking how I can set up auth OR if I actually need that. 

My goal is to get API calls authenticated with some key that will generated by Vault. 
Still I'm pretty new to the lease of App ID's and authentication in this manner, so I might ask some questions in this issue later if that is ok?

**Comment by sethvargo** [comment]
Sounds good
