### ISSUE TITLE
Asterisk at the end of path does not work when multiple plus sign operators are used in policy

### ISSUE THREAD

**Issue by fernando-villalba** [hashicorp/vault#9805]
I am not sure if this is by design or a bug, but either way it is weird and confusing, so an explanation would be nice to read.

When using kv2 this policy path works:

`kv/+/directory/*
`
The first plus sign would correspond to the data,delete,metadata etc that's needed to use kv2.

However if I do this with multiple plus signs:

`kv/+/+/+/+/directory/*
`
This policy does not work, and if I do this:

`kv/+/+/+/+/directory/+
`
That works.

Even though the last line fulfils my particular purpose, if I wanted to give permission to create indeterminate amount of subdirectories after the last path I would not be able to with that last policy.

If this was by design perhaps it should be explained more clearly in the documentation as I don't really get that from what I read, otherwise it would nice to "fix it" so it works as expected.

**Comment by aphorise** [comment]
Already known issue and similar to: #7161 - will hopefully resolve in the forthcoming releases.

@fernando-villalba - can you kindly add your note to the above issue and close this instead?

**Comment by fernando-villalba** [comment]
Okay thank you, closing this issue and adding note to #7161
