### ISSUE TITLE
Migration problem

### ISSUE THREAD

**Issue by srikarrampa** [hashicorp/vault#9809]
I had a doubt regarding the migration procedure pointed out here https://www.vaultproject.io/docs/commands/operator/migrate#run-the-migration

What does "Stop Vault" mean here? Should I seal the vault?

**Comment by Danielwinship** [comment]
Stop means Vault on the source node should not be running.

**Comment by raskchanky** [comment]
@srikarrampa It means shut down the Vault process. Vault will seal itself when you do this. As an example, if you were running Vault under systemd, you might run something like: `systemctl stop vault`.

**Comment by raskchanky** [comment]
I'm going to close this for now, but feel free to reopen it if there is more to discuss.
