### ISSUE TITLE
1.5.1 and 1.5.2 releases not tagged in github

### ISSUE THREAD

**Issue by swills** [hashicorp/vault#9811]
The 1.5.1 and 1.5.2 releases don't seem to be tagged in GitHub. The releases page here doesn't show them:

https://github.com/hashicorp/vault/releases

but the releases page here does:

https://releases.hashicorp.com/vault/

 Is this intentional? Thanks!

**Comment by swills** [comment]
And now the 1.5.1 and 1.5.2 tags have appeared, along with some other older versions, making my comment appear incorrect.

**Comment by mladlow** [comment]
Hi @swills,

Your original comment was definitely correct. We were delayed in publishing the tags. I'm going to close this for now, but thanks for the reminding us!

**Comment by swills** [comment]
Thanks for confirming. FWIW, I now see a 1.5.2.1 here:

https://releases.hashicorp.com/vault/

but not in the GitHub tags. Perhaps that's related to another issue?

**Comment by mladlow** [comment]
It's an enterprise patch - we re-issued some enterprise binaries, but there were no associated OSS changes (https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#1521).
