### ISSUE TITLE
Vault service failing to startup

### ISSUE THREAD

**Issue by dhlaluku** [hashicorp/vault#9822]
**Describe the bug**

vault: Error loading configuration from /etc/vault/vault.d/config.hcl: At 26:2: object expected closing RBRACE got: EOF
Aug 25 09:09:36 xetdflvcl1 systemd: vault.service: main process exited, code=exited, status=1/FAILURE
Aug 25 09:09:36 xetdflvcl1 systemd: Unit vault.service entered failed state.
Aug 25 09:09:36 xetdflvcl1 systemd: vault.service failed.

**To Reproduce**
1. Run `vault write ...`
2. Run `vault login....`
3. See error

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`):
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
vault {
        address = "https://vault.service.co.za:8200"
}

auto_auth {
        method "aws" {
                mount_path = "auth/aws-subaccount"
                config = {
                        type = "iam"
                        role = "foobar"
                }
        }

        method "approle" {
            role_id_file_path = "/etc/vault/role"
            secret_id_file_path = "/etc/vault/secret"


        sink "file" {
                config = {
                        path = "/etc/vault/sink"
                }
        }

}
```

**Additional context**

**Comment by ncabatoff** [comment]
Hi @dhlaluku ,

You're missing a closing brace on your `method "approle"` stanza.  In future, please take questions of this sort to the [discuss forum](https://discuss.hashicorp.com/c/vault/30) instead of filing bugs.
