### ISSUE TITLE
Resource vault_gcp_secret_backend must support all relevant parameters for vault_mount also

### ISSUE THREAD

**Issue by abhyasa** [hashicorp/vault#9837]
**Is your feature request related to a problem? Please describe.**
The vault_gcp_secret_backend also takes care of making api call for performing gcp secret engine mount. But it does not support all parameters relevant for mounting gcp secret engine as supported by vault_mount resource. 

**Describe the solution you'd like**
For backward compatibility, update the vault_gcp_secret_backend  code to support additional input parameters that can be used for mounting (similar to vault_mount) the gcp secret engine.

**Describe alternatives you've considered**
Make api request separately for mounting the gcp secret engine, then make another api call to configure the gcp secret engine. Then use terraform for managing roleset settings. But this solution is not good as we have to use two methods (api and terraform) for managing resources.

**Explain any additional use-cases**
The terraform resources must map one to one with backend api. For example, we could use vault_mount and vault_gcp_secret_backend separately, but unfortunately the provider code for vault_gcp_secret_backend is not defined that way.

**Additional context**

**Comment by catsby** [comment]
Hey @abhyasa - I noticed your other issue open on the Vault Terraform provider, so I'm going to close this issue in favor of that one (https://github.com/terraform-providers/terraform-provider-vault/issues/852)

Thanks!
