### ISSUE TITLE
PPC64LE Support

### ISSUE THREAD

**Issue by kandarpamalipeddi** [hashicorp/vault#9855]
**Is your feature request related to a problem? Please describe.**

I have been working on porting Vault to ppc64le and as of today, we are able to build it without any errors.

However, some test failures were observed which were primarily due to the unavailability of some of the dependent docker images like consul, cockroachDB, nomad etc (Tests depends even on Vault docker image). We have been able to build most of these images locally and use them in our testing and now most of the tests are working as expected.

The tests that are failing are related to MSSQL, SSH, DynamoDB and Kubernetes. 

**Describe the solution you'd like**
We are working on failures related to SSH (Fixed 3 out of 5 failures) and DynamoDB, whereas MSSQL is not supported on ppc64le and we are thinking to make these tests conditional, any thoughts on this?

### **Additional context**
**MSSQL Test Failures**
We tried using MySQL instead of MSSQL and following are the logs:

> --- FAIL: TestBackend_basic (66.35s)
>     mssqlhelper.go:48: Could not connect to MSSQL docker container: Unable to open tcp connection with host 'localhost:1433': dial tcp 127.0.0.1:1433: connect: connection refused
> --- FAIL: TestBackend_roleCrud (73.70s)
>     mssqlhelper.go:48: Could not connect to MSSQL docker container: Unable to open tcp connection with host 'localhost:1433': dial tcp 127.0.0.1:1433: connect: connection refused
> --- FAIL: TestBackend_leaseWriteRead (72.15s)
>     mssqlhelper.go:48: Could not connect to MSSQL docker container: Unable to open tcp connection with host 'localhost:1433': dial tcp 127.0.0.1:1433: connect: connection refused
> FAIL
> FAIL    github.com/hashicorp/vault/builtin/logical/mssql        212.260s
> ?       github.com/hashicorp/vault/builtin/logical/mssql/cmd/mssql      [no test files]
> --- FAIL: TestBackend_basic (0.41s)
>     backend_test.go:31: Could not start local MySQL docker container: : no matching manifest for linux/ppc64le in the manifest list entries
> --- FAIL: TestBackend_basicHostRevoke (0.26s)
>     backend_test.go:31: Could not start local MySQL docker container: : no matching manifest for linux/ppc64le in the manifest list entries
> --- FAIL: TestBackend_roleCrud (0.27s)
>     backend_test.go:31: Could not start local MySQL docker container: : no matching manifest for linux/ppc64le in the manifest list entries
> --- FAIL: TestBackend_leaseWriteRead (0.35s)
>     backend_test.go:31: Could not start local MySQL docker container: : no matching manifest for linux/ppc64le in the manifest list entries
> FAIL
> FAIL    github.com/hashicorp/vault/builtin/logical/mysql        1.454s
> ?       github.com/hashicorp/vault/builtin/logical/mysql/cmd/mysql      [no test files]
> 

SSH Test Failures:

> --- FAIL: TestSSHBackend_CA (79.88s)
>     --- FAIL: TestSSHBackend_CA/defaultSignerSSHDSupport (10.26s)
>         backend_test.go:150: SSHAddress : 127.0.0.1:34534
>         testing.go:364: Failed step 3: unable to dial sshd to host "127.0.0.1:34534": ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
>     --- FAIL: TestSSHBackend_CA/rsaSignerSSHDSupport (12.58s)
>         backend_test.go:150: SSHAddress : 127.0.0.1:34535
>         testing.go:364: Failed step 3: unable to dial sshd to host "127.0.0.1:34535": ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

Observed following failure with Consul, this is due to using latest consul instead of mentioned version:
> --- FAIL: TestConsul_TooLarge (6.99s)
>     consulhelper.go:20: preparing test container
>     consulhelper.go:100: Generated Master token: 23346ad5-65f5-4a27-ca8d-4197822a4807
>     consul_test.go:249: expected value too large error, got Unexpected response code: 413 (Request body(600000 bytes) too large, max size: 524288 bytes. See https://www.consul.io/docs/agent/options.html#kv_max_value_size.)

Kubernetes Test failures:

> --- FAIL: TestRetryHandlerSimple (0.00s)
>     testserver.go:84: open /home/user6/kp/vault/serviceregistration/kubernetes/testing/token: no such file or directory
> --- FAIL: TestRetryHandlerAdd (0.00s)
>     testserver.go:84: open /home/user6/kp/vault/serviceregistration/kubernetes/testing/token: no such file or directory
> --- FAIL: TestRetryHandlerRacesAndDeadlocks (0.00s)
>     testserver.go:84: open /home/user6/kp/vault/serviceregistration/kubernetes/testing/token: no such file or directory
> --- FAIL: TestRetryHandlerAPIConnectivityProblemsInitialState (0.00s)
>     testserver.go:84: open /home/user6/kp/vault/serviceregistration/kubernetes/testing/token: no such file or directory
> --- FAIL: TestRetryHandlerAPIConnectivityProblemsNotifications (0.00s)
>     testserver.go:84: open /home/user6/kp/vault/serviceregistration/kubernetes/testing/token: no such file or directory
> --- FAIL: TestServiceRegistration (0.00s)
>     testserver.go:84: open /home/user6/kp/vault/serviceregistration/kubernetes/testing/token: no such file or directory
> FAIL
> FAIL    github.com/hashicorp/vault/serviceregistration/kubernetes       0.004s
> --- FAIL: TestClient (0.00s)
>     testserver.go:84: open /home/user6/kp/vault/serviceregistration/kubernetes/testing/token: no such file or directory
> FAIL
> FAIL    github.com/hashicorp/vault/serviceregistration/kubernetes/client        0.007s
> 

Dynamodb Test failures:

> panic: test timed out after 45m0s
> 
> goroutine 64 [running]:
> testing.(*M).startAlarm.func1()
>         /home/user6/kp/vault/go/src/testing/testing.go:1509 +0xcc
> created by time.goFunc
>         /home/user6/kp/vault/go/src/time/sleep.go:168 +0x44
> 
> goroutine 1 [chan receive]:
> testing.(*T).Run(0xc00013cd80, 0x6b4fff, 0x13, 0x6d7940, 0x3ae)
> ...
> ...
> goroutine 62 [IO wait]:
> internal/poll.runtime_pollWait(0x3fff7bced308, 0x72, 0xffffffffffffffff)
>         /home/user6/kp/vault/go/src/runtime/netpoll.go:203 +0x50
> internal/poll.(*pollDesc).wait(0xc0002faf18, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
>         /home/user6/kp/vault/go/src/internal/poll/fd_poll_runtime.go:87 +0x40
> internal/poll.(*pollDesc).waitRead(...)
>         /home/user6/kp/vault/go/src/internal/poll/fd_poll_runtime.go:92
> internal/poll.(*FD).Read(0xc0002faf00, 0xc0002f9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
>         /home/user6/kp/vault/go/src/internal/poll/fd_unix.go:169 +0x17c
> net.(*netFD).Read(0xc0002faf00, 0xc0002f9000, 0x1000, 0x1000, 0x0, 0x0, 0xc000072b10)
>         /home/user6/kp/vault/go/src/net/fd_unix.go:202 +0x48
> net.(*conn).Read(0xc0001023d0, 0xc0002f9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
>         /home/user6/kp/vault/go/src/net/net.go:184 +0x84
> net/http.(*persistConn).Read(0xc0002c26c0, 0xc0002f9000, 0x1000, 0x1000, 0x0, 0x60, 0x0)
>         /home/user6/kp/vault/go/src/net/http/transport.go:1825 +0xf4
> bufio.(*Reader).fill(0xc0002f3140)
>         /home/user6/kp/vault/go/src/bufio/bufio.go:100 +0x120
> bufio.(*Reader).Peek(0xc0002f3140, 0x1, 0xc000123d40, 0x0, 0x0, 0x0, 0x0)
>         /home/user6/kp/vault/go/src/bufio/bufio.go:138 +0x48
> net/http.(*persistConn).readLoop(0xc0002c26c0)
>         /home/user6/kp/vault/go/src/net/http/transport.go:1978 +0x15c
> created by net/http.(*Transport).dialConn
>         /home/user6/kp/vault/go/src/net/http/transport.go:1647 +0xacc
> 
> goroutine 63 [select]:
> net/http.(*persistConn).writeLoop(0xc0002c26c0)
>         /home/user6/kp/vault/go/src/net/http/transport.go:2277 +0xd8
> created by net/http.(*Transport).dialConn
>         /home/user6/kp/vault/go/src/net/http/transport.go:1648 +0xaec
> FAIL    github.com/hashicorp/vault/physical/dynamodb    2700.026s

**Comment by HridoyRoy** [comment]
Hi @kandarpamalipeddi 
Currently there are no plans on making these tests conditional. I'm going to close out this issue, but please feel free to reopen it if closing is premature. 
Thanks!
