### ISSUE TITLE
rpm mirror failed

### ISSUE THREAD

**Issue by Slm0n87** [hashicorp/vault#9857]
**Describe the bug**
We try to mirror the rpm repository: https://rpm.releases.hashicorp.com/RHEL/8/x86_64/stable/, but it fails.  
Our company's security does not allow to contact an rpm mirror directly, we need to mirror the full repo internally.

**To Reproduce**
0. User a rhel8 or centos8 system
1. Install dnf plugins
```
dnf install dnf-plugins-core
```

2. Configure the repo:
```
cat /etc/yum.repos.d/hashicorp.repo 
[hashicorp]
name=Hashicorp Stable - $basearch
baseurl=https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
enabled=1
gpgcheck=1
gpgkey=https://rpm.releases.hashicorp.com/gpg
```

3. Start the sync of the repository with dnf:
```
dnf reposync -v --destdir repo/rhel8/ --download-metadata --repoid hashicorp
[...]
(15/107): vault-1.4.5-1.x86_64.rpm                                                     11 MB/s |  38 MB     00:03    
(16/107): consul-1.8.3-2.x86_64.rpm                                                    12 MB/s |  33 MB     00:02    
(17/107): terraform-0.12.29-1.x86_64.rpm                                              9.4 MB/s |  22 MB     00:02    
(18/107): vault-enterprise-1.2.7+ent-1.x86_64.rpm                                      14 MB/s |  37 MB     00:02    
[MIRROR] vault-1.5.0-2.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 41461060 but expected size is: 41458500
[MIRROR] vault-1.5.0-2.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 41461060 but expected size is: 41458500
[MIRROR] vault-1.5.0-2.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 41461060 but expected size is: 41458500
[MIRROR] vault-1.5.0-2.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 41461060 but expected size is: 41458500
[FAILED] vault-1.5.0-2.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success    
```

**Expected behavior**
The whole repository should get synced.

**Environment:**
* CentOS 8:*

**Comment by kpenfound** [comment]
Hi @Slm0n87 ,

This appears to have been an issue with the metadata of 2 specific vault packages. I've corrected this issue and was able to `reposync` successfully.

Thanks so much for reporting this!

**Comment by Slm0n87** [comment]
Hi @kpenfound , I can confirm the issue is solved.  
Thanks for the quick resolution.

**Comment by zicklam** [comment]
Hi, the repository is again not available. Could you please check again?

**Comment by kpenfound** [comment]
Hi @zicklam , I was able to reposync succesfully on centos8 just now. Are you having the same issue as above?

**Comment by zicklam** [comment]
On **Pulp2** we get following error:
`PulpCodedException: Malformed repository: metadata is missing for some packages in filelists.xml and in other.xml`
Last successfull sync was on 03 nov 2021.

On **Pulp3** the sync works when i set the checksum to sha1

**Comment by sawkhaing** [comment]
created by dnf config-manager from https://rpm.releases.hashicorp.com/RHEL/                  239  B/s | 295  B     00:01    
Errors during downloading metadata for repository 'rpm.releases.hashicorp.com_RHEL_':
  - Status code: 404 for https://rpm.releases.hashicorp.com/RHEL/repodata/repomd.xml (IP: 18.155.68.57)
Error: Failed to download metadata for repo 'rpm.releases.hashicorp.com_RHEL_': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried.

May I know vault repo is unavailable. Is anyone facing like me?
