### ISSUE TITLE
Unable to enable custom auth plugin in Windows #File does not exist error occurs.

### ISSUE THREAD

**Issue by buvanes12** [hashicorp/vault#9861]
Describe the bug
Using the auth implemention in github enable a custom auth method results in vault on Windows results in the following error code:

via CLI:

Command used to register in catalog:
vault write sys/plugins/catalog/auth/example-auth-plugin \
   sha_256="$SHASUM" \
   command="example-auth-plugin"
Received Output for the above command as - Success! Data written to sys/plugins/catalog/auth/example-auth-plugin

C:\vault>vault auth enable -path=example -plugin-name=example-auth-plugin plugin
Error enabling example-auth-plugin auth: Error making API request.
URL: POST https://127.0.0.1:8200/v1/sys/auth/example
Code: 400. Errors:

exec: "C:\vault\vault_plugins\vault-auth-example": file does not exist

Same as issue #6842

**Comment by calvn** [comment]
It looks like the binary can't be found on the plugin_directory location. Can you share your vault config file (interested in the `plugin_directory` value), and the output of `dir C:\vault\vault_plugins\`?

**Comment by buvanes12** [comment]
Thank you for the response.

Adding the steps to reproduce and its response.

I am using the following command to build the plugin.
go build -o /tmp/vault_plugins/vault-auth-example
File available in the folder.

C:\>vault write sys/plugins/catalog/auth/vault-auth-example sha_256=$SHASUM command="vault-auth-example"
Success! Data written to: sys/plugins/catalog/auth/vault-auth-example

C:\>vault auth enable -path=example -plugin-name=vault-auth-example plugin
Error enabling vault-auth-example auth: Error making API request.

URL: POST http://127.0.0.1:8200/v1/sys/auth/example
Code: 400. Errors:

* exec: "C:\\tmp\\vault_plugins\\vault-auth-example": file does not exist

C:\>dir C:\tmp\vault_plugins

 Directory of C:\tmp\vault_plugins

09/02/2020  11:50 AM    <DIR>          .
09/02/2020  11:50 AM    <DIR>          ..
09/02/2020  11:50 AM        16,445,952 vault-auth-example
               1 File(s)     16,445,952 bytes
               2 Dir(s)  193,870,114,816 bytes free

Plugin directory
plugin_directory = "C:/tmp/vault_plugins"
api_addr = "http://127.0.0.1:8200"

Now file is available in the path, but receiving the error as file does not exist.

Note : My assumption is the file generated may not be the required format. File in the folder is of type File.

**Comment by ncabatoff** [comment]
At a guess, you should instead

```
move vault-auth-plugin-example.exe /tmp/vault_plugins/vault-auth-plugin-example.exe
vault write sys/plugins/catalog/auth/vault-auth-plugin-example sha_256="$SHA" command="vault-auth-plugin-example.exe"
```

I haven't used Windows much but I believe it's particular about file extensions for executables.

**Comment by buvanes12** [comment]
Thank you so much. This resolved my issue.

**Comment by stefan-zh** [comment]
On Windows, renaming the executable from `{filename}` to `{filename}.exe` solved the problem for me.
I wasn't able to start the Vault dev server with `-dev-plugin-dir` on Windows 11, but now it works!
