### ISSUE TITLE
AWS root token rotation

### ISSUE THREAD

**Issue by devops-rob** [hashicorp/vault#9862]
AWS root credentials need to be rotated according to security requirements of organisations.  This is mostly done via cron jobs.  Once these are rotated, the Vault config for the AWS secrets engine is now outdated. To update the secrets engine manually is an overhead.  To try to automate this is hacky at best.

It would be great if Vault could own the root credential rotation and and feed this to the AWS secrets engine to keep credentials rotated and AWS secrets engine config updated.

**Comment by calvn** [comment]
Hi there! You can delegate the rotation of root credentials to Vault with [this endpoint](https://www.vaultproject.io/api/secret/aws#rotate-root-iam-credentials). If you want rotation periodically, you would have a cron job (or similar process) calling this endpoint instead.
