### ISSUE TITLE
Vault

### ISSUE THREAD

**Issue by devops-rob** [hashicorp/vault#9864]
Consul and Nomad support cloud auto-join, whereby we can use cloud resource tagging to automatically join nodes to the cluster (Cloud auto-join).  They also have a feature called auto-pilot which does a lot of things but in this context, it cleans up dead servers. Consul also has a snapshot agent which automates the  backup process of its data and relieves operational overhead.

Now that Vault has Integrated storage with Raft, I think it should also have these features built in to it.  I also think that when using cloud auto join, the auto pilot functionality should be enabled by default.  Without it, you will run into cluster problems, which i learnt the hard way when using cloud auto join with Consul the first time.  It doesn't play nice without Auto pilot in my experience.

**Comment by aphorise** [comment]
I believe that this has since been delivered:
- Learn: [Integrated Storage Autopilot](https://learn.hashicorp.com/tutorials/vault/raft-autopilot)

Hey @devops-rob ok to close?

**Comment by devops-rob** [comment]
Yes fine to close @aphorise
