### ISSUE TITLE
KV Version 2: List of keys name

### ISSUE THREAD

**Issue by iusergii** [hashicorp/vault#9874]
**Describe the bug**
 According to KV Version 2  [docs](https://www.vaultproject.io/api/secret/kv/kv-v2.html#list-secrets) we can get a list of key names with LIST methods.  I've tried this example with Vault  1.4.2 and 1.5.2 and both fail. 
  
**To Reproduce**
1.  I have two keys 
```bash
vault kv list /kv-v2/folder
Keys
----
key-a
key-b
```
2. `curl` with LIST method fails:
```bash
curl \
  -H "X-Vault-Request: true" \
  -H "X-Vault-Token: $(vault print token)" \
  --request LIST \
  https://vault-tst.com/v1/kv-v2/metadata/folder

HTTP/1.1 400 Bad Request
```
3. Works with HTTP GET methods
```bash
curl \
  -H "X-Vault-Request: true" \
  -H "X-Vault-Token: $(vault print token)" \
  https://vault-tst.com/v1/kv-v2/metadata/folder?list=true | jq .data
{
  "keys": [
    "key-a",
    "key-b"
  ]
}
```

**Expected behavior**
The response returns a list of key names  

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.4.2 / 1.5.2
* Vault CLI Version (retrieve with `vault version`):  1.4.2

**Additional context**
We would like to use [hvac](https://github.com/hvac/hvac) as API client and it `list_secrets` methods fails seems due to this.
```python
list_response = client.secrets.kv.v2.list_secrets(mount_point="kv-v2", path="folder")
('Oops!', <class 'hvac.exceptions.InvalidRequest'>, 'occurred.')
Exception: , on list https://vault-tst.com/v1/kv-v2/metadata/folder
```

**Comment by pippo** [comment]
I was unable to reproduce the issue using the steps provided.
Here's what I did.

1. Started Vault in dev mode
```
vault server -dev
```
2. Enabled the KV v2 secret engine:
```
vault secrets enable --path=kv-v2 kv-v2
```
3. Created 2 dummy entries:
```
vault kv put kv-v2/folder/foo foo=foo
vault kv put kv-v2/folder/bar bar=bar
```
4. Made a LIST request to the API:
```
curl -X LIST -H "X-Vault-Token: **redacted **"  http://127.0.0.1:8200/v1/kv-v2/metadata/folder | jq .data

{
  "keys": [
    "bar",
    "foo"
  ]
}
```

**Comment by pippo** [comment]
@iusergii Is there a chance there's a reverse proxy in front of the Vault on `https://vault-tst.com` (or whatever you're actually using), which might be failing to serve `LIST` requests?

**Comment by iusergii** [comment]
@pippo yes, it's deployed to Kubernetes Cluster/Istio. Vault behind Ingress and envoy-proxy. Seems there is an issue there. 
Closing this one. Thank you much!

**Comment by Mr-YYM** [comment]
same for me! @pippo
