### ISSUE TITLE
Documentation: Required capabilities for /ssh/sign/:name not clear

### ISSUE THREAD

**Issue by kartsm** [hashicorp/vault#9888]
**Describe the bug**

According to https://www.vaultproject.io/docs/concepts/policies#capabilities the capabilities `create` and `update` are almost equivalent in most places, but differences should be noted in documentation.

When I grant only the `create` capability on the path `/ssh/sign/:name` to a role, my request is refused with 403 Forbidden.  When I grant only the `update` capability, the request is accepted.  https://www.vaultproject.io/api/secret/ssh#sign-ssh-key does not appear to mention that `update` is the required capability, not `create`.

https://www.vaultproject.io/api/secret/ssh#sign-ssh-key says that `/ssh/sign/:name` expects the HTTP `POST` method.  The CLI program appears to use the `PUT` method instead.    Both `POST` and `PUT` appear to be acceptable methods, when policies allow them.  The documentation mentions the rough equivalency of `POST` and `PUT` for write-like operations, but this is still a difference between the documentation and the actual behavior.

**To Reproduce**
1. Start vault in dev mode, `vault server -dev &`.  Take note of root token (`$root_token`) in log output.
1. `export VAULT_TOKEN=$root_token`
1. `export VAULT_ADDR=http://127.0.0.1:8200`
1. Arrange Terraform content and policies below into desired directory structure.
1. `VAULT_TOKEN=$root_token terraform import vault_mounts.secrets secret`
1. `VAULT_TOKEN=$root_token terraform apply -auto-approve`
1. `VAULT_TOKEN=$root_token vault token create -policy automation-engineering`.  Take note of new token (`$autoeng_token`).
1. `ssh-keygen -N '' -C vaultsigntest -f $HOME/.ssh/vaultsigntest`
1. `VAULT_TOKEN=$autoeng_token vault write ssh/sign/jenkins public_key=@$HOME/.ssh/vaultsigntest.pub`
1. Observe refusal with 403 Forbidden.  Also observe use of `PUT` method, when documentation suggests `POST`.
```
Error writing data to ssh/sign/jenkins: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/ssh/sign/jenkins
Code: 403. Errors:

* 1 error occurred:
        * permission denied
```
11. Update policy in `automation_engineering.hcl` to use `update` instead of `create`
1. `VAULT_TOKEN=$root_token terraform apply -auto-approve`
1. `VAULT_TOKEN=$autoeng_token vault write ssh/sign/jenkins public_key=@$HOME/.ssh/vaultsigntest.pub`
1. Observe success
```
Key              Value
---              -----
serial_number    17ff90745191807a
signed_key       ssh-rsa-cert-v01@openssh.com KEY-MATERIAL-REDACTED
```
15. `VAULT_TOKEN=$autoeng_token vault write -output-curl-string ssh/sign/jenkins public_key=@$HOME/.ssh/vaultsigntest.pub`
1. Observe `curl -X PUT` in output, when documentation suggests `POST`.
```
curl -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"public_key":"ssh-rsa KEY-MATERIAL-REDACTED vaultsigntest\n"}' http://127.0.0.1:8200/v1/ssh/sign/jenkins
```

**Expected behavior**

Documentation should clearly indicate that the `update` capability is required for `/ssh/sign/:name`, and that the `create` capability is not effective.

Documentation should mention that both `POST` and `PUT` are honored for `/ssh/sign/:name`, when policies are set to allow it.

**Environment:**
* Vault Server Version (retrieve with `vault status`):

```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.5.3
Cluster Name    vault-cluster-d43c932a
Cluster ID      b7b8fdf5-7a13-f774-5a79-6887b5dadd17
HA Enabled      false

```

* Vault CLI Version (retrieve with `vault version`):

```
Vault v1.5.3 (9fcd81405feb320390b9d71e15a691c3bc1daeef)
```

* Server Operating System/Architecture:

```
Darwin HOSTNAME-REDACTED 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
```

*About This Mac* says `Version 10.15.6`.

Vault server configuration file(s):

We have been using Terraform's Vault provider to configure Vault; our configuration is expressed in that language.

`main.tf`
```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values

# For testing and legacy support
resource "vault_mount" "secrets" {
  path = "secret"
  type = "kv"
  options = {
    version = 1
  }
}

resource "vault_mount" "ssh" {
  type = "ssh"
  path = "ssh"
}

resource "vault_ssh_secret_backend_ca" "certificate_authority" {
  backend              = vault_mount.ssh.path
  generate_signing_key = true
}

resource "vault_ssh_secret_backend_role" "jenkins" {
  name                    = "jenkins"
  backend                 = vault_mount.ssh.path
  key_type                = "ca"
  default_user            = "jenkins"
  allowed_users           = "jenkins"
  allow_user_certificates = true
  max_ttl                 = "3600"
  ttl                     = "3600"
}

resource "vault_policy" "autoeng" {
  name = "automation-engineering"

  policy = <<EOF
${file("${path.module}/policies/ssh.hcl")}
${file("${path.module}/policies/automation_engineering.hcl")}
EOF
}
```

`policies/ssh.hcl`

```hcl
path "ssh/lookup" {
  capabilities = [ "update" ]
}
path "ssh/config/ca" {
  capabilities = [ "read" ]
}
path "ssh/config/zeroaddress" {
  capabilities = [ "read" ]
}
path "ssh/roles" {
  capabilities = [ "list" ]
}
path "ssh/roles/*" {
  capabilities = [ "read" ]
}
```

`policies/automation_engineering.hcl`

```hcl
path "ssh/sign/jenkins" {
  capabilities = [ "create" ]  /* toggle between `create` and `update` as necessary to demonstrate difference */
}
```

**Additional context**

_(this space intentionally left blank)_

**Comment by aphorise** [comment]
Hey @kartsm - I wonder if you agree that there could be a similar note as per the [API transit method that calls this out](https://www.vaultproject.io/api-docs/secret/transit#encrypt-data) - something like:

> This endpoint signs an SSH public key based on the supplied parameters, subject to the restrictions contained in the role named in the endpoint. This path supports `create` and `update` policy capabilities as follows: if the user has `create` capability for this endpoint, and the key does not exist, it will be created with the default parameters already configured. If the user only has `update` capability and the SSH key does not exist, an error will be returned. To fully manage the signing of SSH keys using a single role both `create` and `update` capabilities will be required.

Is this valid and should be we do a PR on the [API Docs: Sign SSH Key](https://www.vaultproject.io/api-docs/secret/ssh#sign-ssh-key)?

**Comment by kartsm** [comment]
@aphorise That looks good to me.  Please proceed with the suggestion.
