### ISSUE TITLE
Allow raft member weighting

### ISSUE THREAD

**Issue by drawks** [hashicorp/vault#9893]
**Is your feature request related to a problem? Please describe.**
In the current raft implementation there is no way to favor a specific host as a leader or exclude a given host from being the leader. It would sometimes be beneficial to administratively be able to "put your thumb on the scale" to influence which machine is the leader or to prevent a given machine from becoming the leader but still being able to serve in an `ha_storage` raft pool as a tie breaking vote.

**Describe the solution you'd like**
Some configuration options in the `storage`/`ha_storage` stanza for the raft storage backend to indicate leader preference as an integer that defaults to 1, where 0 would indicate not eligible for leader and greater than 1 would indicate a greater preference for being a leader.

**Describe alternatives you've considered**
`operator step-down` will demote the current leader to a follower, but there is no determinism in which instance will become the new leader aside from machines with higher latency tend to lose the election.

**Explain any additional use-cases**
It may be desirable to have a tie breaking vote cast by a machine which is not ever intended to server as the "active" component in a cluster. This would for instance allow for deploying 2 nodes with fast storage in an HA pair and running a third node only to guarantee an odd number of quorum votes.

**Comment by mladlow** [comment]
Hi @drawks,

Thanks for the feature request. At this time, this isn't something we plan to pursue.

Separately from the feature request, we don't recommend running a cluster where some nodes couldn't handle being the leader, but were curious about the motivation for doing that?

**Comment by drawks** [comment]
As mentioned in my description, it may be desirable to provision two nodes with more resources (fats storage, faster network, cpu, etc) that could be a leader, but you need a third vote to prevent split brains and form a proper quorum. It could make sense to provision a third voting but not leader eligible node that could be provisioned on cheaper/slower hardware since it never has to carry the weight of being master and servicing requests. I would think with all the increased focus on cloud deployment it would be pretty obvious that "smaller" server instances are cheaper to run than larger ones.

**Comment by mladlow** [comment]
Thanks for the clarification!

**Comment by ncabatoff** [comment]
Closing this belatedly, since we decided not to pursue the idea.
