### ISSUE TITLE
RADIUS/Diameter support as Auth Backend

### ISSUE THREAD

**Issue by C-Duv** [hashicorp/vault#99]
Is there any plan to add RADIUS and/or Diameter as authentication backend?

_Very classic question indeed but I have to ask ;)_

**Comment by danshao** [comment]
+1 for RADIUS backend

**Comment by msessa-cotd** [comment]
RADIUS support has been implemented and released in v0.6.5

**Comment by vishalnayak** [comment]
Fixed by #2268
