### ISSUE TITLE
complete:13: command not found: compdef

### ISSUE THREAD

**Issue by queglay** [hashicorp/vault#9901]
After following the instructions to install auto completion for hashicorp vault - https://www.vaultproject.io/docs/commands
```
vault -autocomplete-install
```

Every time I open a new terminal in macos 10.15.6 I see this error:
```
complete:13: command not found: compdef
```

I'm not sure why or how to fix it to get autocompletion working.  Any pointers?

**Comment by calvn** [comment]
This looks like a zsh-related issue. Can you try the suggestions from [here](https://github.com/ohmyzsh/ohmyzsh/issues/3356#issuecomment-94344463)?

**Comment by stevenzamborsky** [comment]
[This](https://apple.stackexchange.com/a/340718/377013) link helped me fix the issue.  My `.zshrc` looks like the following.

> Note: your `vault` path may be different if you installed with something other than `homebrew`

```
autoload -Uz compinit
compinit
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /opt/homebrew/bin/vault vault
```

**Comment by kitography** [comment]
Awesome!  I'm glad you were able to figure it out.  I'm closing this, since I'm not sure what changes could be made from the vault-side of things, but feel free to reopen if you have a change in mind.
