### ISSUE TITLE
Upgrade github.com/ulikunitz/xz to v0.5.8

### ISSUE THREAD

**Issue by tsaarni** [hashicorp/vault#9914]
Vault is (indirectly) depending on github.com/ulikunitz/xz v0.5.7 which is now being tagged by vulnerability scanners as security issue.

The security issue is reported in https://github.com/ulikunitz/xz/security/advisories/GHSA-25xm-hr59-7c27

The vulnerability has been fixed in https://github.com/ulikunitz/xz/releases/tag/v0.5.8.

**Comment by pmmukh** [comment]
Closed by https://github.com/hashicorp/vault/pull/12253
