### ISSUE TITLE
Incorrect documentation on disabling max_request_size

### ISSUE THREAD

**Issue by somethingnew2-0** [hashicorp/vault#9936]
**Describe the bug**
The current [documentation for `max_request_size`](https://www.vaultproject.io/docs/configuration/listener/tcp#max_request_size) states:
> `max_request_size` (int: 33554432) – Specifies a hard maximum allowed request size, in bytes. Defaults to 32 MB. Specifying a number less than or equal to `0` turns off limiting altogether.

However when setting `max_request_size` to 0, according to the code Vault currently sets it to the default of 32 MB instead of disabling the request size limiting feature.
https://github.com/hashicorp/vault/blob/v1.5.3/http/handler.go#L266

Also when setting `max_request_size` to -1 or any negative number, according to the code an error is thrown "max_request_size cannot be negative" which halts Vault from starting up
https://github.com/hashicorp/vault/blob/v1.5.3/internalshared/configutil/listener.go#L151

Please correct the documentation, correct the code, or both as currently this `max_request_size` limiting feature cannot be disabled at all.

**To Reproduce**
Set a vault server setup with Vault config such as demonstrated below 
- if max_request_size is set to 0, then it is not disabled, but set to the default of 32 MB.
- if max_request_size is set to less than 0, then it is not disabled, but Vault does not correctly startup and instead throws an error of an invalid config as the value is incorrectly not allowed to be negative.

**Expected behavior**
Setting `max_request_size` to 0 or a negative number should disable limiting request sizes.

**Environment:**
* Vault Server Version: 1.5.3
* Vault CLI Version: N/A
* Server Operating System/Architecture: N/A

Vault server configuration file(s):

Setting max_request_size to 0 should disable max request size limiting, but it is set to the default of 32MB
```hcl
...
listener "tcp" {
  ...
  max_request_size = 0
}
```

Setting max_request_size to a negative should disable max request size limiting, but Vault fails to boot and throws this error

> error loading configuration from /secret/config.hcl: error parsing 'listener': listeners.0 max_request_size cannot be negative

```hcl
...
listener "tcp" {
  ...
  max_request_size = -1
}
```

**Comment by jay-dee7** [comment]
@guacamole want to take this one up?

**Comment by guacamole** [comment]
Hey @raskchanky , I would like to give it a shot.

**Comment by guacamole** [comment]
@raskchanky I went through the code and i think the conditions where-all  max_request_size <= 0 occurs can be removed without breaking anything. Let me know what you think!

**Comment by HridoyRoy** [comment]
@guacamole @somethingnew2-0 the PR looks great, and @raskchanky and I have approved and merged! I'm going to go ahead and close this git issue, but please feel free to reopen if closing this is premature. 

Thanks!
