### ISSUE TITLE
Unable to login into postgres sql using the generated dynamic user credentials

### ISSUE THREAD

**Issue by andrewKev12** [hashicorp/vault#9938]
Working with Vault - PostgreSQL database plugin. Have generated the dynamic credentials, but unable to login into PostgreSQL using the generated credentials.

Steps done:

vault secrets enable database
Success! Enabled the database secrets engine at: database/

vault write database/config/my-postgresql-database plugin_name=postgresql-database-plugin allowed_roles="my-role" connection_url="postgresql://{{username}}:{{password}}@localhost:5432/" username="postgres" password="vaultpass"

vault write database/roles/my-role  db_name=my-postgresql-database creation_statements="CREATE ROLE Developer WITH LOGIN PASSWORD 'pwd' VALID UNTIL '12-10-2020'; GRANT SELECT ON ALL TABLES IN SCHEMA public TO Developer";" default_ttl="1h" max_ttl="24h"
Success! Data written to: database/roles/my-role

vault read database/creds/my-role
Key                Value
---                -----
lease_id           database/creds/my-role/2f6a614c-4aa2-7b19-24b9-ad944a8d4de6
lease_duration     1h
lease_renewable    true
password           8cab931c-d62e-a73d-60d3-5ee85139cd66
username           v-vaultuse-e2978cd0

When using the username and password that is generated to login into the postgres server using,
 psql -h localhost -d postgres -U v-vaultuse-e2978cd0 -W 8cab931c-d62e-a73d-60d3-5ee85139cd66

Receiving Password authentication failed error.

Please help me with what I am missing.

Thanks in advance.

**Comment by rewanth1997** [comment]
Even I'm facing a similar issue.

```
/ $ vault read database/creds/my-role
Key                Value
---                -----
lease_id           database/creds/my-role/kTGeDriVMrkrQSytdAwlbKHq
lease_duration     1h
lease_renewable    true
password           A1a-iU8CzS8wxE8VIG9W
username           v-token-my-role-r9a48PMx1qcMMZJkxI9j-1603951591
```

The role is created successfully in postgres db.

```
postgres-# \du
                                                      List of roles
                    Role name                    |                         Attributes                         | Member of
-------------------------------------------------+------------------------------------------------------------+-----------
 postgres                                        | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 v-token-my-role-r9a48PMx1qcMMZJkxI9j-1603951591 | Password valid until 2020-10-29 07:06:36+00                | {}
```

When I try to log in, these creds don't work
```
# psql -U v-token-my-role-r9a48PMx1qcMMZJkxI9j-1603951591 -h postgres
Password for user v-token-my-role-r9a48PMx1qcMMZJkxI9j-1603951591:
psql: error: could not connect to server: FATAL:  database "v-token-my-role-r9a48PMx1qcMMZJkxI9j-1603951591" does not exist
```

My vault config for reference

```
vault write database/config/my-postgresql-database \
    plugin_name=postgresql-database-plugin \
    allowed_roles="my-role" \
    connection_url="postgresql://{{username}}:{{password}}@postgres:5432/?sslmode=disable" \
    username="postgres" \
    password="vaultpass" \
    sslmode="disable"
```

**Comment by rewanth1997** [comment]
@andrewKev12 I got the solution.

When we try to login, we need to provide the database name as well.

```
psql -U v-token-my-role-r9a48PMx1qcMMZJkxI9j-1603951591 -h postgres -d <database_name>
```

But the database might not be present from beginning, so I logged in as postgres user

```

psql -U postgres -h localhost
...
postgres=# CREATE database <database_name>;
CREATE DATABASE
```

Finally, once the database is created, you can run the above login command and it will work like charm.

For your case, you are granting permissions for `my-postgresql-database` database and trying to access `postgres` database with a dynamic user, hence it didn't work. Try to login as `postgres` user, create `my-postgresql-database` database` and login with new dynamic creds, it will work.

```
psql -h localhost -d my-postgresql-database -U v-vaultuse-e2978cd0 -W 8cab931c-d62e-a73d-60d3-5ee85139cd66
```

**Comment by pcman312** [comment]
Hi @andrewKev12 ! It looks like your creation statements are set up incorrectly. For dynamic roles, Vault is creating a randomized username and password that is then used within the creation statements (and all of the other statement fields). When configuring the role, the operator doesn't know what the username and password are since they are generated when the `/creds` endpoint is called.

Your creation statements:
```mysql
CREATE ROLE Developer WITH LOGIN PASSWORD 'pwd' VALID UNTIL '12-10-2020';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO Developer";
```
These are explicitly stating a hard coded username and password (`Developer` and `pwd` respectively) rather than using the ones that are generated by Vault. They can be referenced by using `{{username}}` and `{{password}}` within the creation statements. Additionally, the field `{{expiration}}` is also used to reference the expiration date/time of the user which is also generated by Vault when the `/creds` endpoint is called.
```mysql
CREATE ROLE {{username}} WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO {{username}}";
```

**Comment by sgmiller** [comment]
@pcman312's take is correct, closing this issue.  Please reopen if you have further problems.
