### ISSUE TITLE
The 'EDIT THIS PAGE' links at the bottom of each Vault doc page is not clickable

### ISSUE THREAD

**Issue by grempe** [hashicorp/vault#994]
I tried clicking this link in Chrome, Safari and TorBrowser on OS X.  It is not clickable, and it does not react on mouseover.  I suspect that this link (which is actually part of the footer and not the bottom of the content) is in a layer behind the content which is blocking it.

**Comment by jefferai** [comment]
@captainill Can you look into this?

**Comment by captainill** [comment]
@jefferai It looks like the fix for this is actually already merged but the site needs to be deployed. Is there any reason to hold off on deploying or can we give that a go now?

**Comment by jefferai** [comment]
@captainill It's not deployed from `master` -- do you know which commit the fix is in? I can cherry-pick it over.

**Comment by captainill** [comment]
@jefferai found it was fixed here https://github.com/hashicorp/vault/pull/888

**Comment by jefferai** [comment]
OK, thanks

**Comment by jefferai** [comment]
It's deploying now!

**Comment by grempe** [comment]
:+1: Works now. Thx
