### ISSUE TITLE
version_base is stuck to 1.5.0 for the entire 1.5.x release

### ISSUE THREAD

**Issue by aieri** [hashicorp/vault#9943]
Any vault version from the 1.5.x release series reports itself as being version 1.5.0.

This appears to be due to [version_base](https://github.com/hashicorp/vault/blob/v1.5.3/sdk/version/version_base.go#L111) not having been updated as minor versions got released.

**Comment by mladlow** [comment]
Hi @aieri,

Thanks for flagging this. It's an oversight on our part and we'll fix it for the next 1.5 release.

**Comment by mladlow** [comment]
Hey @aieri - no worries if you don't get back to this, but do you happen to have or remember a description of how this was reported? I believe it should be corrected now for Vault versions after 1.5.4, but even with earlier 1.5 versions, `vault version` would report the correct version.

We're trying to understand where the incorrect version was visible.

**Comment by aieri** [comment]
Hi @mladlow, no problem: we had originally (incorrectly) reported this as a bug in the nrpe check deployed by the vault charm. See https://bugs.launchpad.net/vault-charm/+bug/1895548.

The incorrect response was being returned when [querying via curl](https://bugs.launchpad.net/vault-charm/+bug/1895548/comments/1).

**Comment by ncabatoff** [comment]
I'm unable to reproduce this issue.  I've tested on 1.5.2 and 1.5.3.  Here's an example with the former:

```
==> Vault server configuration:

             Api Address: http://0.0.0.0:8200
                     Cgo: disabled
         Cluster Address: https://0.0.0.0:8201
              Go Version: go1.14.7
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: trace
                   Mlock: supported: false, enabled: false
           Recovery Mode: false
                 Storage: inmem
                 Version: Vault v1.5.2
             Version Sha: 685fdfa60d607bca069c09d2d52b6958a7a2febd
...

$ curl -s http://127.0.0.1:8200/v1/sys/health?standbyok=true 
{"initialized":true,"sealed":false,"standby":false,"performance_standby":false,"replication_performance_mode":"disabled","replication_dr_mode":"disabled","server_time_utc":1618250753,"version":"1.5.2","cluster_name":"vault-cluster-9bdad743","cluster_id":"44c6fe1b-f626-a7dd-ed9b-338e9a6018c4"}
```

While it is true that we failed to update `version_base.go` in git for the 1.5.0-1.5.3 releases, our build/release tool modifies the variable via the linker, so that shouldn't matter:

https://github.com/hashicorp/vault/blob/master/packages-oss.yml#L88

```
build-command: VERSION_PKG_PATH=github.com/hashicorp/vault/vendor/github.com/hashicorp/vault/sdk/version;
  go build -v
    -tags ui
    -ldflags "
      -X $VERSION_PKG_PATH.GitCommit=$PACKAGE_SOURCE_ID
      -X $VERSION_PKG_PATH.Version={{.PRODUCT_VERSION_MMP}}
      -X $VERSION_PKG_PATH.VersionPrerelease={{.PRODUCT_VERSION_PRE}}"
```

**Comment by ncabatoff** [comment]
Having thought about it a bit more, I realize that the missing piece of the puzzle is probably that the bug reporter did not use our official packagespec-built-release as I did when attempting to repro.  They built their own binary using the Makefile, which doesn't provide the ldflag to override what's in version.go.

**Comment by vishalnayak** [comment]
Closing the issue due to staleness.

Closing stale issues helps us keep the issue count down and the project healthy. Keeping the issue count under a manageable number helps us provide faster responses and better engagement with the community.

If you feel that the issue is still relevant, or if it is wrongly closed, please leave a comment and we'd be happy to reopen it.
