### ISSUE TITLE
Docs: API documentation for endpoint sys/monitor

### ISSUE THREAD

**Issue by manderson-it** [hashicorp/vault#9953]
**Is your feature request related to a problem? Please describe.**
When I apply the admin policy from the website and login with the userpass admin account that has the admin policy assigned and run a `vault monitor` I get permission denied.
The API endpoint `sys/monitor` is not documented on the website.

```
vault monitor
Error starting monitor: Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/monitor?log_level=info
Code: 403. Errors:

* 1 error occurred:
        * permission denied
```

**Describe the solution you'd like**
Describe the API endpoint `sys/monitor` on the website.

**Comment by raskchanky** [comment]
@manderson-it Thanks for opening this issue! I'm working on API docs for this now, which should be available in the next major release. In the short term, can you verify that the admin policy you're using has read permission on the `sys/monitor` path? I think that's all that's required.

**Comment by manderson-it** [comment]
@raskchanky confirmed. Adding `read` capability on `sys/monitor` is sufficient.
