### ISSUE TITLE
Dynamic k8s service account tokens

### ISSUE THREAD

**Issue by sanbornick** [hashicorp/vault#9961]
**Is your feature request related to a problem? Please describe.**
Would like to use vault to generate dynamic kubernetes service account tokens.

**Describe the solution you'd like**
Something like this https://github.com/jetbrains-infra/vault-plugin-secrets-kubernetes in tree

**Describe alternatives you've considered**
In what I've encountered people generally get tokens from k8s and place them in static secret store like k/v and just read them from there. In some cases they've created rotation processes to try to make those tokens less static. I've also seen some cases of delegating token generation to another process (not Vault) which can often lead to a significant risk surface increase.

**Explain any additional use-cases**
We have a process in which our k8s clusters automatically set up the cluster resources needed for k8s auth backend and write the SA token used by vault for out-of-band verification to a K/V path. A process takes that information and sets up the authentication backend in the vault instance. This covers the use case of allowing workloads in any cluster, even ephemeral ones, to be able to auth to vault. However, in the case of a new cluster or an application that is new to a cluster there is manual work of grabbing the k8s SA tokens needed for integrations, by a ci/cd pipeline for example, and placing those tokens into K/V paths for consumption. If vault allowed me to generate k8s SA tokens I could have clusters bootstrap dynamic secrets backends for themselves and automate application deployment end to end.

**Comment by seanmalloy** [comment]
@sanbornick is this a duplicate of https://github.com/hashicorp/vault/issues/3839?

**Comment by sanbornick** [comment]
Yes... yes it is 🤦
