### ISSUE TITLE
Docs: AWS Auth Method with IAM and inferred entity type - clarify bound_region

### ISSUE THREAD

**Issue by sriedel** [hashicorp/vault#9979]
Currently https://www.vaultproject.io/api-docs/auth/aws#create-role states for the bound region attribute:
"[...] This constraint is only checked by the ec2 auth method as well as the iam auth method only when inferring an ec2 instance. [...]"

However, trying to create an IAM type role with entity inferrence and a bound_region results in a 400 from the vault server:

    vault write auth/aws/role/my-role \
           type=iam \
           policies=my-policy-name \
           bound_region=my-region \
           bound_vpc_id=my-vpc \
           inferred_entity_type=ec2_instance \
           inferred_aws_region=my-region \
           token_ttl=30
    Error writing data to auth/aws/role/my-role: Error making API request.

    URL: PUT https://vault.example.com:8200/v1/auth/aws/role/my-role
    Code: 400. Errors:

    * specified bound_region but not specifying ec2 auth_type

(real values obviously replaced)

This is with vault verison 1.5.2.

I'm assuming that with the introduction of `inferred_aws_region`, `bound_region` was no longer used for IAM roles with inferred entities?

**Comment by HridoyRoy** [comment]
From the docs:

` At least one constraint must be specified on the role. The available constraints you can choose are dependent on the auth_type of the role and, if the auth_type is iam, then whether inferencing is enabled. `

In the above command, the auth type was not specified, so as far as I can tell there is no constraint specified on the role.
