### ISSUE TITLE
vault:latest image have security vulnerabilities while scanning the image through Atrifactory X-ray scanner

### ISSUE THREAD

**Issue by anilsaini1212** [hashicorp/vault#9980]
Hi ,Have a Good Day , we are using the vault:latest image from hub.docker.com in our Env
We found some vulnerabilities while scanning the image through Atrifactory X-ray scanner

![vault](https://user-images.githubusercontent.com/39952553/93452275-dc01c180-f8f5-11ea-8c8a-6ac4df3cd3c8.PNG)

please have a look 

Thank
Anil

**Comment by mladlow** [comment]
Hi Anil,

Thanks for reporting. Please send security issues to security@hashicorp.com and do not use the public issue tracker.
